### ISSUE TITLE
OS Startup

### ISSUE THREAD

**Issue by vlados** [nwjs/nw.js#1000]
Is there any way to access Windows registry to set application to start with OS?
##

**Comment by javorosas** [comment]
There is this node package called [auto-launch](https://www.npmjs.com/package/auto-launch) which does exactly that for Windows and Mac. It would be interesting to include it in the nw core though.

**Comment by baconface** [comment]
Personal opinion but I don't think it belongs in the core. Doesn't make sense to bloat NW.js even more when such functionality can be included into your project as an NPM.

**Comment by shaynem** [comment]
Agree

It would start a very bad precedence and i do not see any reason why you
cannot just include it in your project like the rest of your code.

**Comment by turshija** [comment]
Sorry for bumping dead post, but this one is top on google when searching "node webkit start on boot", so I would like to share a solution for that:
https://www.npmjs.com/package/auto-launch
I've tested it on Mac so far, but it says its working on Windows too !

**Comment by mscreenie** [comment]
I implemented this by editing the start up users registry. It's the cleanest solution without the need for a specific module.

**Comment by bhaveshgohel** [comment]
Application working fine using [auto-launch] (https://www.npmjs.com/package/auto-launch) on Windows! :+1:

**Comment by mscreenie** [comment]
@vlados  Please close this as it can be achieved with a registry edit on windows and similar on other platforms.
