### ISSUE TITLE
Access about:flags or chrome://flags

### ISSUE THREAD

**Issue by distracteddev** [nwjs/nw.js#1004]
I need to enable certain flag that doesnt seem to have a command line option associated with it. 

Also I was wondering if there was a way to build node-webkit that uses the latest Chrome Canary binary?

Furthermore, I noticed that when using node-webkit, I can call getUserMedia and it seems that the permissions have been granted by default (i.e - Chrome does not ask me to allow the camera through). This is great and I want to emulate this behavior on a regular installation of Chrome and was wondering how node-webkit bypasses this permission checking.

**Comment by PierBover** [comment]
Anyone knows how to access other features in chrome://flags such as "Maximum Tiles" or "Number of Raster Threads" ?
