### ISSUE TITLE
File dialog's language is always English regardless of current locale.

### ISSUE THREAD

**Issue by zcbenz** [nwjs/nw.js#103]
This seems to be a Mac only issue.

**Comment by dolt131943** [comment]
There is a similar error only occur in NON-SDK Version:
when use input element with required that always show hint "Please fill out this field.",  it alway show english, not match the local system language.

when use 0.14.7-SDK to build app, the hint is shown right, match the local system language.

nwjs version : 0.14.7
OS: Windows XP 32bit Chinese version

how to resolve this problem?
