### ISSUE TITLE
how can i use Webview Tag ?

### ISSUE THREAD

**Issue by thecotne** [nwjs/nw.js#1030]
google chrome has Webview Tag and i want to use it in node webkit 

http://developer.chrome.com/apps/webview_tag.html

i want to make simple web browser

**Comment by rogerwang** [comment]
webview tag is supported starting from 0.12.0-alpha1 now.

**Comment by TriBlade9** [comment]
@rogerwang Does the new 0.12 webview tag support enabling/disabling node support, and have an equivelant to nwfaketop? If so, how? If not... please? :smiley_cat:

**Comment by niutech** [comment]
What;s the difference between `<webview>` and `<iframe nwdisable nwfaketop>` in NW.js?

**Comment by Mithgol** [comment]
I'm not sure. Currently https://developer.chrome.com/apps/webview_tag.html is an error 404.
