### ISSUE TITLE
Start from CD/ DVD very slow

### ISSUE THREAD

**Issue by unicumBL** [nwjs/nw.js#1041]
Hi, 
i put my app, without packing on a dvd.
When i run nw.exe from dvd, the time till a window appears is very long (> 10 seconds). Then appears a white window which remains again more then 10 seconds till the loading process i completed. The second start on the same machine then is much faster. 

Some more details:
- Windows 7 Prof. 64 Bit
- The total size of data on the dvdare about 300mb (The application is something like a product catalog which shows pdfs and video files).
##

**Comment by xadhatter** [comment]
I am having the same problem with v0.11.6.  Has anyone found a fix other than copying the files to a writeable directory?

**Comment by mscreenie** [comment]
Should this be an issue. I think this is developer specific and a 300 mb app running without install off a CD will take long in any case. @xadhatter  @unicumBL

**Comment by baconface** [comment]
> Should this be an issue. I think this is developer specific and a 300 mb app running without install off a CD will take long in any case. 

It it does hinder the ability to run your program from the CD/DVD _without_ an install. While this might not be common with NW.js applications it is a common practice called live CD/DVD. Which could be desired.

**Comment by marckris** [comment]
Searching for the web for node-webkit DVD gives me about 4 results. Either almost nobody has a problem, or almost nobody does it. I've done it last year with no problem. It was a 400MB app (mostly images). I'm doing it again this year with a minor but very annoying problem when building for Linux. I'm on the verge of giving up the Linux build.

https://github.com/nwjs/nw-builder/issues/401
https://github.com/nwjs/nw.js/issues/5287

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
