### ISSUE TITLE
[osx] add ability to listen to dock icon being clicked

### ISSUE THREAD

**Issue by theabraham** [nwjs/nw.js#1047]
On OSX applications, it's common to click the dock icon to bring up the main application window if it's currently closed or hidden. Being able to bind an event listener to a "dock clicked" event would be helpful in implementing this functionality.

![screen shot 2013-08-29 at 9 36 20 am](https://f.cloud.github.com/assets/387734/1049857/104f6a04-10b0-11e3-9413-bfa7d437218c.png)

**Comment by mrfabbri** [comment]
Closing as there is no further report of issues.

**Comment by Saravanan90** [comment]
Tried the reopen event in nw.js v0.16.1 as well as in v0.17, this event wasn't fired after some time the app is opened. Any new event introduced for the same in the latest version?

**Comment by moscartong** [comment]
v0.17.4, reopen event is **not** fire when clicking the dock icon :(
