### ISSUE TITLE
chromium-args not apply

### ISSUE THREAD

**Issue by icode** [nwjs/nw.js#1060]
"chromium-args"  : "--enable-webgl --ignore-gpu-blacklist"

not support , mast use nw . --enable-webgl --ignore-gpu-blacklist

node-webkit-v0.7.1-linux-x64
##

**Comment by chriddyp** [comment]
Some other command line args: https://chromium.googlesource.com/chromium/src/+/38.0.2125.104/ui/gl/gl_switches.cc (reference: #3035 )

**Comment by sanemat** [comment]
`"chromium-args": "--file-descriptor-limit=2000"` does not work on `nwjs-v0.12.2-osx-x64`.
`$ nwjs target/ --file-descriptor-limit=2000` works well.

**Comment by CyberianIce** [comment]
Proxy server bypass also won't work with nwjs-v0.12.2. Seems like there is no chromium argument that actually works with nw.js

```
"chromium-args" : "--no-proxy-server"
```

**Comment by lapsio** [comment]
I also have issues with --no-proxy-server
As I'm using i2p which takes like 5 min to load any website and I need to bypass proxy in 90% of apps i use it makes nwjs impossible to use. I've managed to force set proxy from the inside of nwjs programmatically but it's more complex and annoying than cmd switch

**Comment by rafaelCMoura** [comment]
`"chromium-args": "--disable-web-security"` also won't work.

```js
{
  "name": "nwapp",
  "main": "index.html",
  "window": {
    "title": "nwapp",
    "icon": "favicon.ico",
    "toolbar": true,
    "frame": true,
    "width": 1100,
    "height": 800,
    "position": "center",
    "min_width": 700,
    "min_height": 600
  },
  "chromium-args": "--disable-web-security"
}
```

**Comment by humiston** [comment]
` "chromium-args": "--url=http://nwjs.io"` doesn't seem to work either, which is a 1-for-1 code sample from the NWjs documentation. 

```
{
  "name": "nwjs_basic",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "./nwjs-sdk/nwjs.app/Contents/MacOS/nwjs ."
  },
  "author": "",
  "license": "ISC",
  "webkit": {
    "plugin": true
  },
  "chromium-args": "--url=http://nwjs.io"
}
```

**Comment by well0nez** [comment]
any news?

**Comment by Christywl** [comment]
The original issue is too old. If you meet any problem for some argument with the latest nwjs build, please file a new issue for it.

**Comment by nurky** [comment]
I'm building a Discord Client using NW.js and can't include the discord web page with iframe due to Same-origin policy.
`"chromium-args": "--disable-web-security"` <- this thing still hasn't been fixed, and this issue was first reported in 2013.
