### ISSUE TITLE
How to call nodejs from the remote page?

### ISSUE THREAD

**Issue by HnLong** [nwjs/nw.js#1065]
Hi guys:
       Now i want to call nodejs from my remote page,but got the error:'Uncaught ReferenceError: require is not defined '.How to solve?
       Some information:
       win7;node-webkit 0.6.2;
       one jsp page as follow:

<html  class="mod-win-dialog">
   <head>
    <meta charset="UTF-8" />  
    <title>test</title>
    <script  >
            function setMax(){
             var gui = require('nw.gui');
             var win = gui.Window.get();
             win.maximize(); 
             }
    </script>
   </head>
    <body >
     ..
       <a onclick="setMax();"></a>
     ..
    </body>
</html>

   package.json
{
    "name" : "test",
    "main" : "http://localhost:8080/test/index.jsp",
    "description" : "test nodewebkit",
    "version" : "1.0",
     "webkit": {
             "page-cache":false,  
              "plugin": true
              },
    "window" : {
        "toolbar" : false,
        "icon" : "icon.png",
        "frame": false,
        "title" : "test",
        "position" : "center",
        "width" : 1000,
        "height" : 860
            }
}

**Comment by Losses** [comment]
@Mithgol After I add this to my package.json, this information appeared:

Error Loading Extension

Failed to load extension from:
[path]
Invalid value for 'app.urls[0]': Missing scheme separator.

oops.....
