### ISSUE TITLE
Print font-face does not work properly

### ISSUE THREAD

**Issue by feugy** [nwjs/nw.js#1070]
Printing works pretty well unless your page uses @font-face.
Have a look at the "dive into html5" front page inside node-webkit (on the left)
and the print result (on the right)

![print-font-problem](https://f.cloud.github.com/assets/186268/1087219/a796e6ec-1611-11e3-9e58-001628b7e37a.png)

See how paragraph's characters have been totally messed up ? 

It seems related to [chromium](https://code.google.com/p/chromium/issues/detail?id=132239), but latest Chrome handle web font perfectly.

Any idea ?

**Comment by feugy** [comment]
On the Windows 32bit version, printing does not do anything. No crash, no error in console, but no output on printer.

**Comment by theteep** [comment]
Also seeing the no print issue on Windows 7 64 bit with nwv0.11.5 (32bit), this is a massive problem for me as my app really needs to print reports.

**Comment by feugy** [comment]
Yes.

**Comment by ghostoy** [comment]
Should be working with latest 0.13.0-beta2.
