### ISSUE TITLE
how to change the package's icon?

### ISSUE THREAD

**Issue by malpower** [nwjs/nw.js#1078]
im on windows, i used the command "copy /b nw.exe+abc.zip abc.exe".then i got a execute file, but i don't know how to change it's icon.Does any one konw the way to change it?

**Comment by vivekgaikwad** [comment]
Can somebody tell me how to change the nwjs.app icon in mac?
 I have replaced nw.icns inside /Contents/Resources directory with new nw.icns but it still not changing the package's icon.

**Comment by sapioit** [comment]
Apparently, you can do that in either the siftware Web2Executable, or using one of the following answers:
[Changing node webkit app icon on windows from cli](http://stackoverflow.com/questions/21304845/changing-node-webkit-app-icon-on-windows-from-cli)
[how do I programmatically change icon of a Windows executable and Mac application?](http://stackoverflow.com/questions/26986874/how-do-i-programmatically-change-icon-of-a-windows-executable-and-mac-applicatio)

**Comment by ghostoy** [comment]
On Mac, icon is cached by the system. You have to move your app to a new
folder to see icon changed.

sapioit <notifications@github.com>于2015年12月19日周六 05:51写道：
