### ISSUE TITLE
Simplify dependency management - npm style

### ISSUE THREAD

**Issue by marcooliveira** [nwjs/nw.js#1086]
I've created a node module that simplifies the management of dependency on node-webit versions: https://npmjs.org/package/node-webkit-builds

I needed this while creating an app builder task. I can declare node-webkit dependency just like any other nodejs module this way. The module then provides me links for each of the OS builds on the version I specified and also the release notes.

Not sure why this didn't exist yet, I'm sure other people trying to automate app builds would enjoy this. I'd like to propose to include this in the node-webkit project @rogerwang. I'll be managing the module by myself for now, and will set it up to update automatically when new versions are released here on Github. Yet it would be great if there was a mention somewhere of this module to help other people.

Thanks.

**Comment by rogerwang** [comment]
This is now provided by another project in nwjs org.
