### ISSUE TITLE
Odd behavior when disabling/enabling MenuItems in a window menu

### ISSUE THREAD

**Issue by schmod** [nwjs/nw.js#1094]
Enabling and disabling `MenuItem`s in a window menu appears to be unreliable.  

If I disable a `MenuItem`, the `MenuItem` does not actually become disabled until after I also click on some other item in the same menu.  

Here's a simple test case:

````javascript
var gui = require('nw.gui');

var menubar = new gui.Menu({type: 'menubar'});
var fileMenu = new gui.Menu();
fileMenu.append(new gui.MenuItem({label: 'Disable Me', enabled: true}));
fileMenu.append(new gui.MenuItem({label: 'Re-Enable'}));
fileMenu.append(new gui.MenuItem({label: 'Do Nothing'}));

fileMenu.items[0].click = function(){
	fileMenu.items[0].enabled = false;
	alert("Disabling");
}
fileMenu.items[1].click = function(){
	fileMenu.items[0].enabled = true;
}

menubar.append(new gui.MenuItem({label: 'File', submenu: fileMenu}));
gui.Window.get().menu = menubar;
````
To reproduce: 

1. Click File->'Disable Me' 
2. Return to File menu; 'Disable Me' is not greyed out, and the 'click' handler still executes if the item is clicked.
3. Click 'File->Do Nothing'
4. Return to File menu.  'Disable Me' is now greyed out, and does nothing when clicked.

Curiously, this bug does not seem to affect context menus.  If I append the following code to the above example, enabling/disabling items works as one would expect it to. :
````javascript
document.body.addEventListener('contextmenu', function(ev) { 
  ev.preventDefault();
  fileMenu.popup(ev.x, ev.y);
  return false;
});
````

I'm using NW 0.7.2 on Windows 7.

**Comment by rogerwang** [comment]
should be working with latest 0.13 version.
