### ISSUE TITLE
--allow-running-insecure-content doesn't work in node-webkit

### ISSUE THREAD

**Issue by sirisian** [nwjs/nw.js#1113]
I have an iframe that points to a server then within that iframe it points to another server. That second iframe throws the error:
"[blocked] The page at [...] ran insecure content from [...]."

I read that "--allow-running-insecure-content" would fix it, but that didn't work with node-webkit. It still says it's blocked.

What version of webkit is being used? Apparently this was a bug close to a year ago with webkit.
##

**Comment by mscreenie** [comment]
@rogerwang please kindly support this option (arg), our app authenticates over ssl then loads an iframe, the iframes is loaded over ssl to prevent session jacking, within the iframe is various user added content which cannot be loaded by proxy.  this is causing our project to be set back,

**Comment by mscreenie** [comment]
@sirisian please close this as was fixed from 12.3.
