### ISSUE TITLE
Not fully supported cromium-args

### ISSUE THREAD

**Issue by PhantomArt** [nwjs/nw.js#1134]
In your wiki in the description of the manifest parameter "chromium-args", you refer to the document http://src.chromium.org/svn/trunk/src/content/public/common/content_switches.cc But I did not find parameters which I needed that however work in chromium, in particular --proxy-server and --proxy-pac-url. Searching in google I found another document: http://src.chromium.org/svn/trunk/src/chrome/common/chrome_switches.cc Why don't this argument list work in the node-webkit?

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
