### ISSUE TITLE
Add option to resize fonts in dev tools

### ISSUE THREAD

**Issue by denysonique** [nwjs/nw.js#1138]
In Chromium  Ctrl++ and Ctrl+- allow the fonts to be increased/decreased.

Similar functionality is desired, some times the letters in dev tools can be too small or too large for some of us

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.

**Comment by PriteshGajjar008** [comment]
Ctrl ++/ Ctrl-- not working for my application. It is using 0.14.7.
