### ISSUE TITLE
Print Preview

### ISSUE THREAD

**Issue by bear888** [nwjs/nw.js#1139]
In issue #56, it says that print preview will be supported before 0.5.2.
But from the document provided in Wiki, I cannot find any reference to this feature. Can you let me know how to invoke the print preview function?
Thank you very much

**Comment by rogerwang** [comment]
This will be supported in the first alpha version of upcoming nw13:

![screenshot from 2015-04-30 14 38 06](https://cloud.githubusercontent.com/assets/165401/7407577/94569324-ef46-11e4-8ded-c4d742cca5f7.png)

**Comment by AndryBray** [comment]
:+1:  this is a great news @rogerwang !!!

**Comment by rogerwang** [comment]
It's now available. See https://groups.google.com/d/msg/nwjs-general/IqfH1RXNGlw/2PgeRGHO-B4J

**Comment by AlbertSanIza** [comment]
Is there any plans for silent print?
