### ISSUE TITLE
Connection timeout - display a connection error page

### ISSUE THREAD

**Issue by Jrags87** [nwjs/nw.js#1149]
When a user starts my app it displays a webpage. If the web server is down, or the internet connection is lost, the page just displays a blank white background. Is there a way I can have it display a page saying cannot make connection, and retry, or something similar?

Thanks for any help.

**Comment by nigelvon** [comment]
Is there any solution about this? Thanks.

**Comment by bhaveshgohel** [comment]
Try out this : https://github.com/HubSpot/offline :+1:
