### ISSUE TITLE
[Linux] in 0.7.x it's not possible to move windows beyond bounds of visible screen space.

### ISSUE THREAD

**Issue by miklschmidt** [nwjs/nw.js#1152]
Tested on Linux Mint Cinnamon (Debian) x86 and x64.
See #1043 for code to reproduce. This is the same issue as #1043, just on linux instead of OSX.
##

**Comment by miklschmidt** [comment]
It's still an issue, but i guess everybody has found workarounds by now.

**Comment by rogerwang** [comment]
CC @Christywl please verify.

**Comment by Christywl** [comment]
@miklschmidt , the result on my Linux with nwjs-sdk-v0.25.4:
```
nw.Window.open('1.html', {
  frame: false,
  width: 400,
  height: 0,
  always_on_top: true,
  show: false,
  resizable: false
},function(newWindow){

newWindow.on('loaded', function() {
  var x;
  newWindow.show();
  x = newWindow.window.screen.availLeft + newWindow.window.screen.availWidth;
  console.log('x: ' + x);
  console.log('availWidth: ' + newWindow.window.screen.availWidth);
  newWindow.moveTo(x, 0);
  newWindow.resizeTo(400,200);
});
```
![1152-1](https://user-images.githubusercontent.com/20039821/31324012-aaa62680-ace0-11e7-9e84-e055c8992b4f.png)
If comment out `moveTo()`, the result is:
`//newWindow.moveTo(x, 0);`

![1152-2](https://user-images.githubusercontent.com/20039821/31324022-bbd67c7a-ace0-11e7-85bb-34c447e62637.png)
