### ISSUE TITLE
node-webkit and express

### ISSUE THREAD

**Issue by jaeh** [nwjs/nw.js#1163]
hi there :)

i really need to have node-webkit and express work together nicely.

the node-webkit app is getting started and basically just shows a loading page.

the express server is starting in the background and as soon as it started the webkit app is redirected to localhost:2323, where the webkit admin started.

the application will also have a web backend running on top of express which loads static html files generated by the node-webkit application OR by a server side admin backend.

i want to keep the code for both the server side and the node-webkit app the same,
which means that express will have to run in node-webkit.

in the example:
[node-webkit-express](http://github.com/jaeh/node-webkit-express)

express gets started perfectly fine,
but as soon as i start the developer tools i get the error that require is not defined:
shell:
[32417:0930/173202:INFO:CONSOLE(1)] "Uncaught ReferenceError: require is not defined", source:  (1)

this error gets emited the moment i start the dev tools, in the shell that started node-webkit as well as in the dev tools in chrome.

to test the issue just load the repo above, then include nw, nw.pak, libffmpegsumo.so and nwsnapshot and then start the app as usual.

everything still seems to work after the error and the error disappears after the first pageload and does not reappear so i will ignore it, for now, but i still think that this is an issue.

have fun

jascha

**Comment by maheshsetti** [comment]
@jaeh everytime we have to start server, it seems only for online desktop apps. previously i was build an Sails app in node-webkit. I never run server my self. i just added below code in index.html
onload="process.mainModule.exports.onLoad(); in html.

to use express we have alternative too
configure  like below:

"node-main": "./bin/www",
"main": "http://localhost:3000"

source(https://github.com/nwjs/nw.js/wiki/NW.js-use-express-and-similar-web-frameworks)

but for me express version is not working :P

**Comment by jaeh** [comment]
to be honest i am still surprised about the 22 stars my repo has, it is a very dirty prototype after all ;)

the documentation you pointed to was written a few months ago and did not exist when i wrote my prototype, neither did bin/www exist back then.

thanks for the link though, i will read it and see if i can change my app according to it.

@bhaveshgohel Glad that you can use it but please do not base anything on my prototype without rewriting most of it, this is neither good code nor is it updated to reflect modern techniques, i just wanted to see if express works in node-webkit back when i wrote it (fetch instead of http.get for example, and promises. it should also be updated to use es6 and babel. multiple other things come to mind.)

**Comment by maheshsetti** [comment]
@jaeh there is very less configuration needed.. you can done
