### ISSUE TITLE
bugs in frameless window

### ISSUE THREAD

**Issue by zh99998** [nwjs/nw.js#1168]
i'm building a frameless node-webkit app and found some bugs:

1. i have a frameless window, and i add 【-webkit-app-region: drag;】 to some elements to drag window and double-click maximize.
but once it maximized, the drag elements don't work any more. i can't get window unmaximized.

2. focus/blur event can't trigger.

3. maybe same problem as 2. i have a element with hover css, when i hover that element then move mouse out of window, that element still shown as hover.

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
