### ISSUE TITLE
Win7-8 Intermittent Mouse Event Lag (Simple Test Case Included)

### ISSUE THREAD

**Issue by gurok** [nwjs/nw.js#1169]
Hello,

I've noticed Node Webkit behaving strangely when it comes to mouse events on my main Windows 8 machine. An object set to move on mousemove will sometimes stop and lag for a good 2-3s before the object catches up with the mouse. In Chrome, the same code behaves normally. I have tried using the profiling tools to determine the cause of the issue, but they just show a huge gap between frames and no processing occurring in the gap. If I turn on the FPS meter, the frame rate doesn't drop even though it's clearly giving an incorrect value (no frame for 2-3s = 60FPS?).

I've created a test case which demonstrates my problem:

http://goldenflameproductions.com/unrelated/testcase.zip

Strangely, I can "fix" the problem with the following code (that I've commented out of the test case):

setInterval(function()
{
}, 30);

I have a fair idea of how this is working. If I use 500 for the interval, the maximum lag I'll see is 500ms rather than 2-3s. I'd say it's just making NW check for events more often than it would otherwise.

It might be specific to my machine in some way, just not sure what it is. I know it's at least somewhat OS-specific. I'm running Windows 8 Professional (64-bit). I couldn't replicate it on my 32-bit XP-based netbook. I'm using NW 0.75.

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
