### ISSUE TITLE
Chromium arg "data-path" doesn't work in Mac OS X?

### ISSUE THREAD

**Issue by vaughnroyko** [nwjs/nw.js#1175]
I am currently using:
<pre>"chromium-args": "--data-path='./save/'"</pre>

Which works great in Windows/Linux 32/64-bit; however, under Mac OS X, this directory is never made and/or never saved to.

This issue mentions that the path could be relative to somewhere inside the .app directory; however, I have not seen any "save" folder being created anywhere. https://github.com/rogerwang/node-webkit/issues/992

I can confirm this as we can't load this data back in as we can in Windows/Linux, it simply is not created as far as I can tell.

**Comment by shrewdlogarithm** [comment]
Just adding my 10p to this - --data-path still doesn't work (as of 0.11.5) on OSX (Mavericks)

What's worse is that if you specify the parameter, nw fails to create ANYTHING (thus no localStorage/cookies/WebDB/cache or anything else) - even if it just ignored the parameter it would be better than nothing!?

A possible related issue is people using process.execPath to find 'the Node Executable' will get a nasty shock on OSX (as it's buried inside the Node WebKit Application folder structure) - process.cwd() seems to return a more useful value tho?

**Comment by shaynem** [comment]
i've been using 

"chromium-args": "--data-path='/etc/appname/data/'"

without any issues on osx.. 

Are you sure it's not a permissions issue to the directory your writing to ?

trying executing nw with sudo just to check.

nw ver 0.10.5

**Comment by shrewdlogarithm** [comment]
Don't think it's permissions - even if I pre-create the folder it just doesn't bother writing anything to it (and no errors are generated in the console that I can see, either)

I notice you have a fully qualified path from root which MIGHT be why it works for you - but that isn't what most people would want (anyone working cross-platform would DEFINATELY not want to do that).  

I've tried "data" and "./data" - neither works

gui.App.dataPath reports the correct values too

**Comment by shaynem** [comment]
I must admit i use different package.json for windows which is taken care of in my build scripts

and just use gui.App.dataPath; for windows

I think i may have run into the same problem as you and had issues which is why i've gone down the route of the full path for osx

**Comment by mdb** [comment]
@vaughnroyko @shrewdlogarithm I suspect that you are running into permissions problems. `/Applications` is often owned by root on Mac OS, I believe.

Note that if you are setting `data-path` to a location within your `.app` -- and if the `.app`'s parent directory (likely `/Applications`?) is owned by root -- the user running the application may not have write permissions to the custom data path, thus yielding the failure you're describing.
