### ISSUE TITLE
Mac file drop is not working on development

### ISSUE THREAD

**Issue by wilkerlucio** [nwjs/nw.js#1176]
Hi,

I'm trying to use the Dragging files into page, as described here: https://github.com/rogerwang/node-webkit/wiki/Dragging-files-into-page

When I run my app using `nw .` (pointing to the folder), every time I drag a file onto the screen I get: `CoreDragMessageHandler : Cannot track drag receiver.  No pasteboard name.`

And no drag events are fired at all (dragover/dragend/drop).

I noticed that if I generate a dist build (I'm using grunt-node-webkit) it works fine.

**Comment by Necmttn** [comment]
@julienr  same error, same reason. while I develop electron  app. 
thanks for tip.
