### ISSUE TITLE
How to get the location of nw.exe?

### ISSUE THREAD

**Issue by DineshDevaraj** [nwjs/nw.js#1197]
I tried process.cwd() but I'm getting some weird location : C:\Users\Dinesh\AppData\Local\Temp\nw2300_31612 
nw.exe is at the location : C:\Users\Dinesh\Programs\Node-Webkit\Package

why is this difference in the paths and how can I get the location of nw.exe?

**Comment by dragonjet** [comment]
sorry for necro'ing an almost 3-year old thread, but it seems there still isn't a way of getting the source of the exe without side by side packaging, so building upon @Subash's code, we can do:

```
var path = require('path');
var nwPath = process.argv[0];
var nwDir = path.dirname(nwPath);
```
then `nwDir` should be the one the user originally opened, not the unpacked one from temp folders
