### ISSUE TITLE
Fails on too deeply nested folders in .nw packages

### ISSUE THREAD

**Issue by FredrikNoren** [nwjs/nw.js#1199]
If you create a .nw package (/zip file) with a too deep folder structure node-webkit fails to unpackage the app with the error message "Cannot extract package. Failed to unzip the package file: package.zip". The zip file can be opened with other programs though so should be a "legit" zip file.

This means for instance lodash.find can't be used since once of it's dependencies resolves into: package.zip\node_modules\lodash.find\node_modules\lodash.forown\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createbound\node_modules\lodash._createobject\node_module\lodash._noop\

Os: Win7-32bit

**Comment by faytom** [comment]
@NathanaelA thx buddy it works for me by moving the sub-directory node_modules to its parents node_modules folder. It works like a charm.

**Comment by Mithgol** [comment]
Fortunately, the most recent `npm` versions (3.x.y) automatically generate much flatter directory structure (most packages coexist under the first level of `node_modules` unless a conflicting version of a package becomes required and thus is installed deeper), and therefore this issue has few chances to surface nowadays.
