### ISSUE TITLE
Crash when an apostrophe is in the name of directory

### ISSUE THREAD

**Issue by akhansari** [nwjs/nw.js#1206]
On Windows, when there is an apostrophe in the directory name (like : te'st), node-webkit crash ! Only when resources are behind nw.exe and I execute it directly.

**Comment by sebbu2** [comment]
It seems to be fixed for names of directory for starting nw, but not for filenames following links, like for example clicking on the link in the following html:
`<a href="someone's something.html">here</a>`
makes nwjs crash.

**Comment by gordon-quad** [comment]
I wonder what would happen if I put it into directory named `test\\'; console.log("Hi there"); a = \\'` on Linux?
