### ISSUE TITLE
Crashing on malloc: *** mach_vm_map(size=484315136) failed (error code=3)

### ISSUE THREAD

**Issue by lahdekorpi** [nwjs/nw.js#1216]
I keep getting crashes that output this:
```
node-webkit Helper(696,0xa16881a8) malloc: *** mach_vm_map(size=484315136) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Terminating process due to a potential for future heap corruption: errno=000
```
Any idea on what would be the best way to start debugging?
I'm using the latest stable as I'm not at the moment able to set up an build-env.

There's nothing special in my code, it's just hundreds of these <div><div>hundreds of lines of text on each</div></div>

shrunk down in CSS with height (yes, there is a reason I'm not cutting the text itself).

This seems to happen somewhat randomly when doing things that require redraws.

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
