### ISSUE TITLE
Resource loading

### ISSUE THREAD

**Issue by shaunbyrnes** [nwjs/nw.js#124]
Hi,

It seems that all resources/files are loaded via a file:/// path?

Is it possible to load via http://localhost or something of the sort? Currently as the resources are all being loaded via file paths this breaks ajax calls etc which should work over http.

Thanks

**Comment by raminbp** [comment]
i think some exception happens and it gets swallowed up. data gets loaded and nothing is sown in dataview

**Comment by raminbp** [comment]
I have checked it inside Extjs source, although the ajax returns the data, since the status code is 0, 
onComplete function in 'Ext.data.Connection' doesn't fire 'requestcomplete', so the problem happens here.

**Comment by raminbp** [comment]
problem is solved. it seems that when you set a relative path for extjs proxy, nodewebkit adds file:// protocol to it. if you use absolute path, there is no problem. something like this: 
http://localhost/{app-directory}/{path to action}
 you can use any CORS enabled domain.
@zcbenz it's not an Extjs bug. extjs acts on standards.
