### ISSUE TITLE
print - silent print [$100]

### ISSUE THREAD

**Issue by ahmedkandel** [nwjs/nw.js#1263]
Hi,
about the printing functionality is it stable now and mature, then i wan to ask how can i silent print the page some thing like chromes --kiosk --kiosk-printing. thanks

**Comment by bestplay** [comment]
+1

**Comment by RobinMalfait** [comment]
+1

**Comment by elbertcastaneda** [comment]
+1

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by rogerwang** [comment]
To all the people requesting silent printing -- I'd love to support this. Does `--kiosk --kiosk-printing` switches works for you? I'm looking to support those switches in nw13.

**Comment by RobinMalfait** [comment]
@rogerwang i would love this, for mr those switches would work :)

**Comment by RobinMalfait** [comment]
Or maybe a --printing so you don t need kiosk mode

**Comment by jonathandelgado** [comment]
@rogerwang That is an excellent first step. However, I think the majority of users requesting silent printing also need the ability to select a specific printer. There isn't a printer API in chromium, so that would have to be an external dependency.

**Comment by acicali** [comment]
Doesn't QT already provide cross-platform functionality for all of this? Ideally, NW would offer the ability to query for attached printers, then would allow some way to choose a printer + settings when calling window.print() (or some variation).

I was able to cobble together a printing solution in NW, but would love to replace it with something more robust.  I have an addon that returns a list of printers (Windows only), and when the application needs to print it renders a PDF of the page (phantomjs) then uses Foxit PDF reader command line for printing. It's a real glue and duct tape solution.

**Comment by villanus** [comment]
That would be fantastic!

**Comment by Vandalko** [comment]
I work on Kiosk application and in deep need of good silent print support.
Currently. I have two solutions, both based on https://github.com/tojocky/node-printer :
 - Hack a bit this gist https://gist.github.com/zhchbin/4749217#gistcomment-1392153 and save captured image to file and print it - it utilise an interesting behavior of `Window.capturePage(...)` functions which allows to capture invisible window (with `show:false`) 
 - Directly draw your content to a Canvas - it might be a bit hard, depending on what you desire to print but, anyway, there are tonns of helper libraries

**Comment by rogerwang** [comment]
It is supported now by command line switch '--kiosk-printing'

**Comment by Vandalko** [comment]
@rogerwang why didn't you claim the reward then ? :)

**Comment by ahmedkandel** [comment]
thanks @rogerwang for the hard work. want to ask is it just a switch or does it have an api to select printer and its preferences? thanks again.

**Comment by rogerwang** [comment]
@ahmedkandel Currently no.. But in Chromium upstream the feature is working by automatically confirm in the print preview WebUI, which is written in JS/HTML and builtin in the resource file in the release. 

If I enable a feature that the WebUI files can be override by you, so you can take the JS files for print preview from Chromium, modify it whatever you want, will that be good enough for you?

See the JS files for print view here: https://github.com/nwjs/chromium.src/tree/nw13/chrome/browser/resources/print_preview

**Comment by ahmedkandel** [comment]
would be a workaround but i prefer to wait for a more robust solution. please take your time thanks again.

**Comment by acicali** [comment]
I hope this might help someone else. I needed silent printing in NWJS (Windows only) with the following requirements:

1. Ability to pre-select one or more printers for later printing
2. Ability to print HTML/CSS provided as a string to a given printer without user interaction

I was able to accomplish this via the following (general overview):

1. A node addon (c++/win32api) that displays the Windows common printing dialog and returns a JavaScript object containing the selected printer's name and properties
2. Including PhantomJS for rendering the provided HTML/CSS as a PDF (and writing that PDF to disk)
3. Including SumatraPDF for PDF printing, providing it the PDF filename/path plus printer name

**Comment by Vandalko** [comment]
@acicali I have recently done very similar thing, but because of 3D transformations, I was not able to render proper PDF file.
That's why I've ended up taking PNG snapshot of invisible page as described here https://gist.github.com/zhchbin/4749217#gistcomment-1392153 and printing it using IrfanView

**Comment by saaiful** [comment]
add following code in `package.json` , your app will open with kiosk-printing. It's not pretty print dialog stays for .5-1 second.
```
"window": {
        "kiosk-printing": true
}
```

**Comment by acicali** [comment]
@Vandalko 
What then do you use to send the PNG to a desired printer?

**Comment by Vandalko** [comment]
@acicali I've configured Windows default printer and IrfanView printing, and then:
```javascript
        win.capturePage(function(img) {
          var base64Data = img.replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
          var fileName = printFolder + 'out-' + Date.now() + '.png';
          require("fs").writeFile(fileName, base64Data, 'base64', function(err) {
            if (err) {
              winston.error('Print error', {error: err});
            }
            var iPrint = spawn('C:\\Program Files (x86)\\IrfanView\\i_view32.exe', [fileName, '/print']);
            iPrint.on('close', function(code) {
              winston.info('IrfanView exit code: ' + code);
              var maxWaiting = global.konfig.printTime;
              var timeout = maxWaiting - (Date.now() - model.startTime);
              setTimeout(function() {
                global.printDone();
              }, Math.min(Math.max(timeout, 0), maxWaiting));
            });
          });
        }, 'png');
```

**Comment by AndryBray** [comment]
@rogerwang do you have any idea about the possibility to customize/override the print_preview webUI and default preferences?

**Comment by rogerwang** [comment]
@AndryBray  my last proposal is to provide a way that developer can override the webUI by copying chrome/browser/resources/print_preview tree to somewhere under the application's directory and then modify it. Does that sound good to you?

Of course we would like to provide some API for this later, but the override way is straightforward in implementation.

**Comment by AndryBray** [comment]
Yes it could be a perfect solution, the most important is to let us interact with default html & js files so we could be able to change behavior of chrome preview. How long does this task take? Is it possibile to have some preview on next nw15? thanks a lot!!!

**Comment by rogerwang** [comment]
Yeah, will see this in 0.15.0 or 0.15.1 as Chromium 51 will be released soon in ~ 1 week.

**Comment by AndryBray** [comment]
Great! Please, could you do the same for nwjs 0.14 ? It's important because of XP and legacy MacOS versions support. Thank you

**Comment by rogerwang** [comment]
@AndryBray yeah, as we announced 0.14 will be under development with new features in at least one year.

**Comment by AndryBray** [comment]
@rogerwang You rock man!

**Comment by rogerwang** [comment]
@AndryBray I've done the overriding part but unfortunately the HTML file in that directory is not real HTML. It has tags like `<include>` and `<if>` which is used in chromium resources processing. I'll see how to deal with this. The original proposal may not be doable because of this.

**Comment by AndryBray** [comment]
Oh no! How about the possibility to build a bridge between app (nw) and print preview gui? something to let's setup default properties... the best would be a kind of API like:
```
window.customPrint({
  destination: 'pdf',
  margins: 0
  headings: false,
 printFrom: 1,
 printTo: 3,
 ... and so on
});
```

**Comment by AndryBray** [comment]
@rogerwang do you think is a kind of API doable in short time? Thank you

**Comment by rogerwang** [comment]
@AndryBray currently I'm not sure how long it will take. At least it's longer than the previous proposal. If it's really urgent on your side, perhaps just change the preview UI files and rebuild NW would be the fastest way.

**Comment by jasminmif** [comment]
Any news about silent printing, im actually waiting for the release.
For the moment im using a node module to convert and compile html to pdf, than with a python script, print the result.

**Comment by rogerwang** [comment]
@jasminmif see my previous comment https://github.com/nwjs/nw.js/issues/1263#issuecomment-204324768 for silent printing.

To all: I'm closing this issue and opened a new issue for custom printing API https://github.com/nwjs/nw.js/issues/4911

**Comment by jasminmif** [comment]
@rogerwang Can you please provide a sample code of --kiosk printing, where should i add that option?

And is there a way to select a specific printer to print the document ?
```
window.print({
    options: { '-kiosk-printing': true}
})
```

**Comment by rogerwang** [comment]
@jasminmif the argument is used in command line when you launch NW.js

**Comment by rogerwang** [comment]
NW v0.14.6 LTS released with custom printing API http://nwjs.io/blog/v0.14.6/ . Please follow up in #4911
