### ISSUE TITLE
Hover event for MenuItem

### ISSUE THREAD

**Issue by Bastian82** [nwjs/nw.js#1264]
Hello,

I cannot find hover event for MenuItem object, similiar to 'click':

``` javascript
var FileItem = new gui.MenuItem({
                label: 'File',
        click: function () {

                FileItem_submenu.popup();

                }
    });
```

I wish to make submenu popup when i hover mouse over MenuItem element, the same as i can do it by clicking on it.

**Comment by RukshanJS** [comment]
Hello @Bastian82, although it's been a long time, could you please did you come up with a solution to this?
