### ISSUE TITLE
webkit html body margin added out of nowhere

### ISSUE THREAD

**Issue by AYAXGVLVI5** [nwjs/nw.js#1283]
node-webkit v0.8.0-rc1
Win 7-64bit 

The styles like margin are not taken and translated to the webkit window, or new window, can't find a work around. 

I'm trying to put a background image in fullscreen, with a standard ctx.drawimage, but even a drawn rectangle like in the pic shows an 8 pixel margin at every border out of nowhere (it doesn't work either in non-fullscreen mode, and I saw the 8 pixel in the object inspector). Because of this, I get unwanted scroll bars. Have tried to use styles in the target html file and it just doesn't work. 

![border](https://f.cloud.github.com/assets/4458541/1460428/c3697dfa-4436-11e3-8f56-2f46f1a01b38.png)

In the picture the drawn rectangle made with ctx.fillRect(0,0,w,h). The white border shouldn't be there, neither the scrollbars. The Html file works fine stand alone in chrome and firefox. Webkit just add this margin so It doesn't work neither with the same html, or building a new window (I need 2 for 2 monitors), as with the code below adapted from an example found here in the wiki, 

gui = require('nw.gui')

var w = window.screen.availWidth;
var h = window.screen.availHeight;
var thirdth = Math.floor(w/3);

mainWindow = gui.Window.get();
mainWindow.resizeTo(w, h);
mainWindow.moveTo(0, 0);
mainWindow.on('close', gui.App.quit);
console.time('leftWindow')
leftWindow = gui.Window.open('page2.html', {
    "show": false, "margin":0 // margin desperate attempt
});
console.time('rightWindow')
rightWindow = gui.Window.open('page3.html', {
    "show": false, "frame":false, "toolbar" :false
});

// rightWindow.show()
rightWindow.on('loaded', function() {
    rightWindow.moveTo(w+1, 0); 
    rightWindow.resizeTo(w, h);
    rightWindow.enterFullscreen();
    rightWindow.show();
});

// leftWindow.show()
rightWindow.on('loaded', function() {
    leftWindow.moveTo(0, 0);
    leftWindow.resizeTo(w, h);
    leftWindow.enterFullscreen();
    leftWindow.show();
});

//mainWindow.show();

**Comment by dtruel** [comment]
I had a similar issue with including an iFrame at 100% width and height.  For anyone else who may have a similar issue, I found the problem was that the iFrame had a 2px border, so to fix I needed to add code: `iframe{ border:0; }
