### ISSUE TITLE
support Travis-ci to build binary automic ?

### ISSUE THREAD

**Issue by tfzxyinhao** [nwjs/nw.js#1286]
build node-webkit is difficult in my eye.
can build it by [Travis CI](https://travis-ci.org/) ?

**Comment by JimmyBoh** [comment]
Has anyone out there discovered any other ways to work with Travis CI, for at a minimum of running tests?

**Comment by jthrilly** [comment]
Any chance of reopening this? What are the obstacles?

**Comment by rogerwang** [comment]
Now we've been using buildbot as our upstream for CI: http://buildbot-master.nwjs.io:8010/waterfall
