### ISSUE TITLE
nwsnapshot fails silently ~25% of the time.

### ISSUE THREAD

**Issue by miklschmidt** [nwjs/nw.js#1295]
nwsnapshot says everything is good. But loading the resulting snapshot doesn't work (nw crashes). I get errors like these at random in my code: `Uncaught TypeError: Property 'ToInteger' of object [object builtins] is not a function` (output on commandline)

This is happening in 0.7.x and has kept me from updating from 0.6.x for quite a while now. Haven't tried 0.8.x yet. It has been the cause of several headaches :( .. Can't figure out what the hell is happening. Any ideas? it seems broken to me..

**Comment by miklschmidt** [comment]
it seems like this won't be fixed.. It's okay though, i got your back. Just use  [node-nw-snapshot](https://github.com/miklschmidt/node-nw-snapshot). I'm gonna go ahead and close this issue.

**Comment by rogerwang** [comment]
@mikischmidt thanks. we still want to fix it. After nw13 we plan to promote this feature from experimental, at that time will look into this again.

**Comment by miklschmidt** [comment]
@rogerwang sounds good! looking forward to it.

**Comment by rogerwang** [comment]
there is a new tool for this feature in 0.12.0-rc1, which removes the size limitation. please try it: https://groups.google.com/d/msg/nwjs-general/Sykci3Qhgus/AoF0zT7TEIoJ
