### ISSUE TITLE
gui.Window.open and nodejs:false option

### ISSUE THREAD

**Issue by StudioQuendi** [nwjs/nw.js#1301]
Hi,

Maybe I have misunderstanded this functionnality, but when I use nodejs:false with gui.Window.open, JavaScript is still executed in node context.

Example :

```javascript
// main window
var win = gui.Window.open("popup.html", {nodejs:false});
win.on("loaded",function(){
    win.window.start();
});

// popup
function start(){
    console.log(some_undefined_variable); // NW crash with node undefined error
}
```

I understand that this function is normally executed in node context since I call it from window loaded event, but the nodejs:false option isn't it made to avoid this ?
Is there a way to force every JavaScript from a popup to WebKit context, but still have access to child's window object ?

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
