### ISSUE TITLE
title bar icon (.ico) not shown in 0.8.0 (works in 0.7.4)

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#1313]
a title bar icon in the format/extension **.ico** is not shown in
node-webkit 0.8.0, but it dit work in version 0.7.4.

or are since version 0.8.0 only **.png** and **.jpg**
formats for icons supported ?

i'm on Win7 32bit. here is a simple example:

package.json

``` js
{
    "main": "index.html",
    "name": "test",
    "window": {
        "icon": "icon.ico"
    }
}
```

index.html

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    test
  </body>
</html>
```
##

**Comment by justinmchase** [comment]
+1

I am seeing this on Win8.1 x64

**Comment by Condor2708** [comment]
+1

**Comment by CamiloMM** [comment]
One trick to deal with this is having both a `.png` and an `.ico`:

```html
<head>
    <link rel="icon" href="app.ico" type="image/x-icon" />
</head>
```

```json
{
  "window": {
    "icon": "app-32px.png"
  }
}
```

This way, the titlebar icon will come from the `.ico` and the taskbar icon will come from the `.png`.

This is not a real fix though, I want to just specify one `.ico` with all resolutions.

**Comment by Christywl** [comment]
This works fine for me on Windows 8.1 with nwjs-sdk-v0.26.6. Please try the latest nwjs build.
![image](https://user-images.githubusercontent.com/20039821/33052328-423d5236-cea9-11e7-9938-f076597e5d6f.png)

**Comment by Christywl** [comment]
close until there is more information
