### ISSUE TITLE
Support for screen geometry and transparency [$145]

### ISSUE THREAD

**Issue by peters** [nwjs/nw.js#132]
Adding screen geometry is crucial for multi-monitor applications and for enabling docked applications (clock-wise of course). 

Transparency is always handy, i know WebkitGtk (experimental) and CEF has solved this already, so i guess this should be an easy fix, if there is not any major blockers that i'm unaware of.

What is your policy on accepting patches for these kind of features (I would only submit for linux and windows) and what code style should one adhere to?

**Comment by rurigk** [comment]
@jakehh The problem is an outdated library in elementary os moon has to do with the version of ubuntu 12.04 is not supported

I think you will not have problems when released freya

**Comment by jakehh** [comment]
@rurigk i was using freya beta 1.

**Comment by Ivshti** [comment]
@jtg-gg is resizing a transparent window supported on Windows? It doesn't seem so for me (tested with NW 0.11 and 0.12 alpha)

**Comment by fritx** [comment]
any progress on background blurring effect? @rogerwang @jtg-gg

**Comment by tomasdev** [comment]
@fritx you could use http://www.blurjs.com/ ...

**Comment by dkfiresky** [comment]
-webkit-backdrop-filter: blur(10px);

**Comment by matthew-dean** [comment]
@tomasdev @dkfiresky I doubt either of those will have the effect you think it will, because you have to consider that that takes effect on the rendering context of the web page. The background of the OS desktop is not "visible" to CSS, nor rendered by the browser, so it's not possible for anything you do in the browser to have an effect on it. It has to be done at the native / OS binding level.

**Comment by jtg-gg** [comment]
@fritx currently we have no plan for it, sorry about that, we are now busy with nw13

**Comment by fritx** [comment]
Thanks, guys!

**Comment by dkfiresky** [comment]
@matthew-dean I agree that this might not work. If somehow this would be implemented not only to allow backdrop filters, but using them on background under the window – this would be great.

**Comment by psmithiv** [comment]
Any updates on click through on Linux? Thx.

**Comment by jeancode** [comment]
Me pareció  muy divertido que backdrop-filter funcionara lamentablemente no fue asi solo queda un fondo negro lastima, me parece que la solución esta en ffmpeg grabando el explorer  directamente sin las ventanas sobre el explorer

**Comment by enber79** [comment]
Hola jeancode, puedes elaborar un poco más esa solución que aportas? Quiero conseguir el mismo efecto, que la ventana de nw aplique blur sobre el escritorio de windows. Gracias.

**Comment by rogerwang** [comment]
@jeancode @enber79 please use only English in this project so all users can read. Thanks.
