### ISSUE TITLE
require error loading nw.gui when loading a remote application

### ISSUE THREAD

**Issue by jhandel** [nwjs/nw.js#1327]
We have a hosted HTML5 app that we currently distribute va phonegap and a custom Win32 Chrome Embedded client..  I am trying to get node-webkit rolling, but running into a weird require.js issue.

I created a package that consisted of an index page which changes the window location to where my hosted app is.   The hosted app uses require a lot (its an AMD based architecture).  When I run the app, it seems to run but I get the following error

Uncaught Error: Module name "nw.gui" has not been loaded yet for context: _. Use require([])

Looks like nw.gui isn't getting loaded for what ever reason and someone is asking for it?  Sometimes this locks up the app, other times the app will just run fine. In either case the error always shows up.

**Comment by Nudelsieb** [comment]
@jhandel @JohnRSim Could you possibley give a brief explanation on how you solved this problem. THe mentioned FAQ are not clear enough to me. It would be a big help. Thanks.

**Comment by codekraft-studio** [comment]
@JohnRSim mee too, I'm using requirejs and this cause conflicts but I'm not able to resolve it.
