### ISSUE TITLE
Get native OS window handle ID

### ISSUE THREAD

**Issue by johnathanhebert** [nwjs/nw.js#1337]
There doesn't seem to be a way to access the underlying window ID provided by the OS.  For example, on Windows, each native window has an integer ID used to access the native window handle.  Can this be exposed through the JavaScript bindings for the window object?
##

**Comment by wwwtyro** [comment]
+1 I'd like this so I can properly interact with the Oculus SDK.

**Comment by jahrain** [comment]
+1

My use case for this is want to use node-webkit as a front-end launcher for desktop games/emulators etc. However, after closing the game, I want to reopen the launcher by returning focus back to the launcher.

**Comment by omrilitov** [comment]
+1

I need it too to use some win32 api.
Is there any news about this?

**Comment by Qix-** [comment]
Would you accept a PR for this? I require this in order to make child windows for this specific use-case.

**Comment by rogerwang** [comment]
Sure, thanks.

**Comment by shark-o** [comment]
+1

**Comment by arkiruthis** [comment]
+1

We have a use case where one process needs to 'parent' another node based process and obtaining the window handle would be very helpful.

**Comment by tharatau** [comment]
Tracked by #7468
