### ISSUE TITLE
Workspace management

### ISSUE THREAD

**Issue by devingfx** [nwjs/nw.js#1348]
The workspaces management is a must have for node-webkit !!

Since the recent Chrome 30.x the powerfull workspace updates transform the browser into really handy code editor. It wich you can live edit your code while debugging ! CSS modification in Element panel are saved automaticaly... 
Bref ! I invite you to try it...
https://developers.google.com/chrome-developer-tools/docs/settings#workspace

In a recent update of node-webkit, the devtool look like gain these updates from webkit (blink?) updates, but not working.

 - context menu in the sources panel in sources tab show 'Add folder to workspace' but nothing appends.

- 'Workspace' tab in devtool's settings panel invites to 'Add folder' but nothing appends.

- context menu's save (or Ctrl+S) action open a save as dialog (pointing always at a "lost in space" Download folder) instead of just save the same path.

I assume node-webkit use pretty much the unmodified devtool from webkit, so perhaps the steps making this working are not that giant! :)

I'l be happy to test theses fonctionnality on desktop app developpement ! !

**Comment by adam-lynch** [comment]
:+1:

**Comment by thomaswrenn** [comment]
+1

**Comment by 2youyouo2** [comment]
+1
any plan on this issue?

**Comment by ahizzle** [comment]
This would indeed be awesome...

**Comment by cklanac** [comment]
+1

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by orielz** [comment]
+1

**Comment by Zurico** [comment]
+1

**Comment by lee-nk** [comment]
+1

**Comment by dottgonzo** [comment]
+1

**Comment by rogerwang** [comment]
This was supported starting from 0.13.0-alpha0. So closing it. Any further issue please report here. Thanks.
