### ISSUE TITLE
[windows] win.maximize() causes also win.show()

### ISSUE THREAD

**Issue by szwacz** [nwjs/nw.js#1350]
Snippet to reproduce the issue...
`package.json`:
```javascript
{
  "name": "nw-test",
  "version": "0.1.0",
  "main": "main.html",
  "window": {
    "show": false
  }
}
```
`main.html`:
```html
<html>
  <body>
    <script>
      var gui = require('nw.gui');
      var win = gui.Window.get();
      win.maximize();
      setTimeout(function () {
        win.show();
      }, 5000);
    </script>
  </body>
</html>
```

The window will appear visible immediately, not after 5 seconds.
Is this bug or feature? :)
Tested on Win7, NW v0.8.1

**Comment by yrdivya** [comment]
This issue is still seen with nwjs-v0.22.0. If the window is hidden and if win.maximize() is done, it opens up the window.

**Comment by gpetrov** [comment]
also have the issue on 0.24+ @rogerwang could you please put the fix back in the new codebase?
