### ISSUE TITLE
Extra height added to real window height when read it with gui.Window.get().height

### ISSUE THREAD

**Issue by kolonist** [nwjs/nw.js#1359]
Extra height added to window, at least in linux x64 gnome-shell env. It seems that when we read height with `gui.Window.get().height` then it returns height with window frame.

I added workaround in https://github.com/rogerwang/node-webkit/wiki/Preserve-window-state-between-sessions, but it seems to be some kind of bug.
##

**Comment by cristianfraser** [comment]
Same problem
