### ISSUE TITLE
Accessing youtube in iframae

### ISSUE THREAD

**Issue by viperfx** [nwjs/nw.js#1376]
I am trying to convert my AngularJS app (https://github.com/viperfx/ng-juketube) to use node-webkit. For the most part its working, the app is working, the socket.io server is working and there are no issues there. 
There problem seems to be that youtube videos are not playing. I am using the youtube IFrame API and it works fine in chrome on localhost and remote. However when I try with webkit lauched through `node-webkit` I get a message saying `This video contains content from *. It is restricted from playback on certain sites`. This message is the same for any video. There are no specific errors on the console so its not to with the API, it seems to be some restriction either with the app:// protocol?

package.json

```
{
  "name": "nw-jukebox",
  "node-main":"server.js",
  "main": "app://localhost/index.html",
  "webkit": {
    "plugin": true
  }
}
```

**Comment by moranm6** [comment]
I'm also using angular in node webkit and cannot get embedded youtube videos to play. I get "An error has occurred. Please try again later"

**Comment by hendricha** [comment]
Same error here as @moranm6
