### ISSUE TITLE
Source panel of devtools shows old source code and error messages

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#1384]
Code of `<iframe>`:
```javascript
if (notExist) { // ReferenceError for "notExist"
    console.log('never goes here');
} else {
    console.log('here!');
    exec('something'); // ReferenceError for "exec"
}
```

Steps to produce the bug:
 1. Load the source code within an `<iframe>`
 1. Open devtools and click the errors in the console. Now **Source** panel is opened and you will see an `ReferenceError` since `notExist` variable does not exist
 1. Modify the first line to `if (window.notExist) {` and reload the `<iframe>` by `location.reload()` or `iframe.src=iframe.src`
 1. You will see `"here!"` and another `ReferenceError` on console
 1. Click the new `ReferenceError` and you will see the code **does not changed** and **both** errors shows in source panel

And sometimes, you may even see the source code is totally **blank** but error messages still appear (see below).

![screen shot 2013-12-10 at 10 59 19](https://f.cloud.github.com/assets/471928/1711213/7f5c43bc-6147-11e3-8d6c-1d1d4513e096.png)

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
