### ISSUE TITLE
Cannot catch the Click Event which sets "-webkit-app-region: drag" on the element

### ISSUE THREAD

**Issue by ankyo** [nwjs/nw.js#1412]
I make a Dropdown Menu and bind Click Event on Document

then I click on the Element which sets "-webkit-app-region: drag"

the Click Event cannot pass to Document

**Comment by VoidVolker** [comment]
Bug is still exists.
I used this code: http://stackoverflow.com/questions/37185354/nwjs-chat-head-click-not-working-if-webkit-app-region-drag-is-set
