### ISSUE TITLE
tooltip not show

### ISSUE THREAD

**Issue by magicone** [nwjs/nw.js#1417]
tray = new gui.Tray({title:'CPD',tooltip:'CPD777777',icon:'icon.png'});

tooltip not show

what's wrong??

**Comment by DreamSeeker321** [comment]
@magicone 你托盘图标闪烁的功能实现了吗？同样请教啊！

**Comment by DreamSeeker321** [comment]
@magicone have you successed to make the tray blink ？can you tell me how to deal with it?
