### ISSUE TITLE
[Windows]Build node-webkit failed

### ISSUE THREAD

**Issue by zbapi** [nwjs/nw.js#1420]
![image](https://f.cloud.github.com/assets/6262802/1809556/86ec1e36-6df4-11e3-9e1b-f064c27472b8.png)
Follow wiki's tips ,I sync node-webkit src,and 
after doing these works:
set GYP_DEFINES=component=shared_library
set GYP_GENERATORS=ninja
cd ./src
python build/gyp_chromium 
python content/content.gyp
ninja -C out/Release nw -j4

The cmd shows:
compiler is out of heap space
ninja: build stopped: subcommand failed.

anyone teach me where I did wrong.

**Comment by abhijeetk** [comment]
@rogerwang : Does node webkit officially supports shared liabrary build like chromium ? I did not find any information about shared library(component build) on official site.

**Comment by andresiraola** [comment]
Last time I checked, it wasn't working.

Right now, I can think one reason why it won't work without changes: v8's isolate uses TLS to store its key and I think roger is exporting v8 funcs through nw.dll (for nw13 at least) and linking node.dll to it on purpose so they share the same isolate. I'm just guessing and there should be another reason.

I'm also interested in getting this to work so if you have any progress, please share!
