### ISSUE TITLE
Won't Build on Ubuntu 13.10 x64

### ISSUE THREAD

**Issue by 161chihuahuas** [nwjs/nw.js#1461]
I have been trying for days to get Node-Webkit to build, so that I can create a custom version of `libffmpegsumo.so` to enable support for h.264 video.

I followed the instructions here in the [wiki page](https://github.com/rogerwang/node-webkit/wiki/Building-node-webkit) several times. I had to modify the `build_install_deps.sh`, to allow me to run it on 13.10 since the version is not included in the supported list. This was fine, I just had to install some packages manually.

Syncing using `gclient` and `./build/gyp_chromium content/content.gyp` both complete successfully.

I modify the the lines in `build_ffmpeg.sh` as you state in the [wiki](https://github.com/rogerwang/node-webkit/wiki/Support-mp3-and-h264-in-video-and-audio-tag) ...

```
add_flag_common --enable-decoder=aac,h264,mp3
add_flag_common --enable-demuxer=mp3,mov
add_flag_common --enable-parser=aac,h264,mpegaudio
```

Then I run the build using `ninja`:

```
ninja -C out/Release nw -j4
```

It does it's thing and get almost completely finished before it dies at:

```
cc1plus: all warnings being treated as errors
[9268/9901] CXX obj/content/browser/accessibil...ontent_browser.browser_accessibility_manager.o
ninja: build stopped: subcommand failed.
```

Now, even though I don't get the `nw` executable from this, it does in fact give me `libffmpegsumo.so`, so I figured I should be able to use this with the latest pre-built binary.

Nope. It behaves exactly as before. I tried numerous times with numerous different versions of Chrome and Chromium, just taking their copy of `libffmpegsumo.so`, but when I use theirs, my app simply crashes after about 2 seconds with no output.

This is a showstopper for me and it's extremely frustrating, because I have read the Node-Webkit documentation and the referenced Chromium documentation up and down to try and get this to work and I am at a complete loss. :sweat: 

What am I missing? Or where can I acquire a proper working copy of `libffmpegsumo.so` for the lastest version of node-webkit that includes the GPL licensed h.264 and mp3 support?

Your help is very much appreciated!

**Comment by smolleyes** [comment]
hi

thanks for the comment lixiaohui

when i download sources with gclient and nw12 i don t have build_ffmpeg.sh do i have to use .py ?

**Comment by smolleyes** [comment]
ffmpeg seems ok with the .py i modified... im building nw now on linux x64

still searching howto setup the windows env exactly (cygwin..)

++

**Comment by smolleyes** [comment]
ok got everything working 

nw build with hevc/dts/dtshd/flac/ac3/mp3/opus... only problem is avi with a small frame rate or don t know what is not fluid... 

if someone know howto cross compile from ubuntu 64 to 32 with the same sources i m interested :)

thanks

**Comment by jduncanator** [comment]
@smolleyes you can't.

**Comment by smolleyes** [comment]
i m done with it by chroot...

got some difficulties with windows now (and again pfffffffffffffffff)

i m on pt channel on irc if you can help with it , might be cool

**Comment by smolleyes** [comment]
https://github.com/nwjs/nw.js/issues/3275

**Comment by jduncanator** [comment]
@smolleyes I'm sorry, I haven't touched the Chromium source in months. I never got anything building on Windows so I can't help.

**Comment by smolleyes** [comment]
ok thanks :) windows is boooooooooooooorrring :(

**Comment by smolleyes** [comment]
got my win32 build YEAAAHHH :dancer:

**Comment by imShara** [comment]
How do you add `audio` tag codec support? After adding FLAC mimetype, file defined as audio, but not played. 

```c
# mime_util.cc

static const char* const common_media_types[] = {
  // Ogg.
  "audio/ogg",
  "application/ogg",
#if !defined(OS_ANDROID)  // Android doesn't support Ogg Theora.
  "video/ogg",
#endif

  // WebM.
  "video/webm",
  "audio/webm",

  // Wav.
  "audio/wav",
  "audio/x-wav",

  // FLAC.
  "audio/flac",

#if defined(OS_ANDROID)
  // HLS. Supported by Android ICS and above.
  "application/vnd.apple.mpegurl",
  "application/x-mpegurl",
#endif
};
```

libffmpegsumo compiled with

```py
# libffmpegsumo.py

configure_flags['Chrome'].extend([
    '--enable-decoder=aac,flac,mp3',
    '--enable-demuxer=aac,flac,mp3',
    '--enable-parser=aac,flac,mpegaudio',
])
```

**Comment by imShara** [comment]
Selfanswer: FLAC works with CromeOS branding and added flac mimetype.

```cc
# src/net/base/mime_util.cc

static const char* const common_media_types[] = {
  // Ogg.
  "audio/ogg",
  "application/ogg",
#if !defined(OS_ANDROID)  // Android doesn't support Ogg Theora.
  "video/ogg",
#endif

  // WebM.
  "video/webm",
  "audio/webm",

  // Wav.
  "audio/wav",
  "audio/x-wav",

  // FLAC.
  "audio/flac",

#if defined(OS_ANDROID)
  // HLS. Supported by Android ICS and above.
  "application/vnd.apple.mpegurl",
  "application/x-mpegurl",
#endif
};
```

```python
# src/third_party/ffmpeg/ffmpeg.gyp

['chromeos == 1', {
  'ffmpeg_branding%': '<(branding)OS',
}, {  # otherwise, assume Chrome/Chromium.
  'ffmpeg_branding%': 'ChromeOS',
}],
```

But how to make custom codec list support still interesting

**Comment by smolleyes** [comment]
hi

i never touched to mime_util.cc ...

here are all the changes i made...

https://github.com/smolleyes/nw_ffmpeg

then i build with (exemple for linux x64)

```
./chromium/scripts/build_ffmpeg.py linux x64
./chromium/scripts/copy_config.sh
./chromium/scripts/generate_gyp.py
cd ../..
./build/gyp_chromium -D linux_dump_symbols=0 -D proprietary_codecs=1 content/content.gyp
ninja -C out/Release -j16 ffmpegsumo
ninja -C out/Release -j16
```

++

**Comment by imShara** [comment]
> i never touched to mime_util.cc ...
@smolleyes, did you add new extension? Without modify `mime_util.cc`, `*.flac` files opened with "save as" dialog, not as audio (like `*.mp3`).

Thanks for diff!

**Comment by jduncanator** [comment]
@imShara You need to serve them with correct headers, `Content-Type: audio/flac`

**Comment by imShara** [comment]
@jduncanator, served with header `Content-Type: audio/x-flac`

```bash
xdg-mime query filetype "song.flac"
```
audio/x-flac

**Comment by jduncanator** [comment]
Try also adding "audio/x-flac" to the mime_utils.cc file.

**Comment by imShara** [comment]
@jduncanator, why need? It works with `"audio/flac"` only in `mime_utils.cc`

**Comment by imShara** [comment]
@jduncanator, you are right, `audio/x-flac` need in `mime_utils.cc` for correct working `.canPlayType()` audion tag function.

**Comment by jduncanator** [comment]
@imShara It depends on what Content-Type you serve it with. You could serve it with `audio/poop` so long as `audio/poop` was in `mime_utils.cc`

**Comment by devlo** [comment]
I am trying to get custom ffmpeg working under cygwin on win 10 x64,
 python build_ffmpeg.py win ia32
./copy_config.sh
python generate_gyp.py

But i get error when generating gyp:
```
Processing build directory: build.ia32.win
Traceback (most recent call last):
  File "generate_gyp.py", line 661, in <module>
    main()
  File "generate_gyp.py", line 644, in main
    s = GetSourceFileSet(object_to_sources, object_files)
  File "generate_gyp.py", line 290, in GetSourceFileSet
    source_set.add(object_to_sources[name])
KeyError: 'compat/strtod.o'
```

Anyone knows why ?
