### ISSUE TITLE
setMaximumSize / setMinimumSize don't work in combination on Linux

### ISSUE THREAD

**Issue by HaiColon** [nwjs/nw.js#1467]
The problem is that only the last setting you make works, so if you use setMaximumSize first and then setMinimumSize, only the minimum size setting works and the other is ignored. This also applies to the corresponding window fields in the package.json file, min_width and max_width.

The problem seems to be known but I couldn't find a bug report for it. It's mentioned in the [Wiki](https://github.com/rogerwang/node-webkit/wiki/Window#issues) at the very bottom in the section "Issues" and there is a [pull request](https://github.com/rogerwang/node-webkit/pull/700) from 8 months ago to fix the problem but I don't think it was ever merged in, at least the bug is still there.

setMaximum also only works partially, but that might be a different problem, while it keeps the window from being made wider by pulling the window with the mouse, it still grows wider when the window is maximized or in Gnome 3 maximized to half the screen width by moving the window to the left or right screen edges.
##

**Comment by rogerwang** [comment]
close until more information is available.
