### ISSUE TITLE
"require is not defined" error when placing node modules in the root of nw file.

### ISSUE THREAD

**Issue by glenlivet** [nwjs/nw.js#1471]
Hi, 

I have a project, which works fine when leaving node modules outside the nw but in the computer's classpath. However, when i place them in the root of nw file, "require is not defined" is caught. the node_modules file which contains all the modules is kinda big, about 50MB. and there's no remote invoking. I think the reason could be some wrong configuration. Any suggestion?

tested on win7 pro 32bit with node-webkit v0.8.3.
Ended up with:

Failed to unzip the package file: C:\node-webkit\nw\chat.nw
"Uncaught ReferenceError: require is not defined " in console.

package.json:
{
  "main": "index.html",
  "name": "nw-demo",
  "single-instance": false,
  "dom_storage_quota": 80
  "window": {
    "title": "node-webkit demo",
    "icon": "link.png",
    "toolbar": true,
    "frame": true,
    "width": 1024,
    "height": 768,
    "position": "center"
  }
}
##

**Comment by zeeshanjan82** [comment]
I am also facing the same issue. I am able to zip the entire website which is an angularjs systemjs website and then have a app.nw file. But when I try to run the app using nw.exe I get 'require is not defined' error and I have no idea what is causing this error.
