### ISSUE TITLE
Exec Permission Denied

### ISSUE THREAD

**Issue by sdog869** [nwjs/nw.js#1489]
I have an external Objective-C console application it print "Hello World" and exits. When I run it I get permission denied on the exec, but if I look at the file permissions they seem find to me, plus node-webkit runs as root so I don't know why it would matter.

Here is the C code:

int main(int argc, const char *argv[]) {
    // insert code here...
    printf("Hello, World!\n");
}

Thanks!

**Comment by zwhitchcox** [comment]
Sorry, but what was the resolution to this? I'm having the same problem, and the group no longer exists.

**Comment by mrfabbri** [comment]
@zwhitchcox https://groups.google.com/forum/#!msg/nwjs-general/doRWZ07LgWQ/4fheV8FF8zsJ
