### ISSUE TITLE
Can a Raspberry Pi (a ARMv6 nano-computer) run node-webkit?

### ISSUE THREAD

**Issue by btwael** [nwjs/nw.js#1491]
It's possible to run node-webkit on Raspbian(based on debian) or Fedora in a [Raspberry Pi](http://en.wikipedia.org/wiki/Raspberry_Pi) (nano-computer with ARMv6 processor architecture) ??

**Comment by jalbam** [comment]
Hello,

I have just created a repository with the node-webkit binary port that runs on Raspbian, tested and working on Raspberry Pi 1 and Raspberry Pi 3 so it is ARMv6 and ARMv7 compatible.

Here you can check it: https://github.com/jalbam/nwjs_rpi
