### ISSUE TITLE
Package.json - "always-on-top"

### ISSUE THREAD

**Issue by umavenkitachalam** [nwjs/nw.js#1497]
Hi
I have packaged an application using node-webkit. I want this to remain on top always
## On Windows 

When I use the "always-on-top" : true in package.json, I noticed that when I start the app using  a batch file ( which does nw <app name> ), this flag is not effective. I am still able to navigate to other apps on the system

However when I build an exe by combining the nw.exe + app.nw , then this works fine

Is this the expected behavior?
## On Linux (32-bit )

Setting the "always-on-top" : true doesnt keep the application on top, whether I open using the ./nw app.nw or I combine both into a single executable

Please let me know if there is a solution to these

Thanks
Uma

**Comment by Vorlot** [comment]
Hello,

This issue still appears to be present.

I am running Xubuntu 14.04 64-bit and Node-webkit 0.11.5 64-bit

**Comment by tommoor** [comment]
Does this work for you? https://github.com/rogerwang/node-webkit/wiki/Window#windowsetalwaysontopboolean-top

**Comment by Vorlot** [comment]
That surprisingly did work. Well, that saves a lot of time debugging various parameters.

**Comment by sandeepks1** [comment]
if anything for always-on-bottom ?
