### ISSUE TITLE
require modules inside a folder

### ISSUE THREAD

**Issue by theHazzard** [nwjs/nw.js#1501]
Hi, first of all, sorry for my english and thanks for your help
I have a problem while trying to require a module that is defined by my inside of my app structure.
this is how the file structure looks like
-- core
---- models
------ connection.js
---- srv
------ index.js
---- app.js
-- index.html

in index.html I call app.js in this way
    <script src="core/app.js"></script>

and inside app.js I have this
    require('srv');

in the debugging tools I have this error 
    Uncaught Error: Cannot find module 'srv' module.js:343

I've tried 
    require('srv');
    require('../srv');
    require('../srv/index');
    require('../srv/index.js');
    require('./../srv');
etc

can anyone help me with this?

**Comment by AlexKvazos** [comment]
How do you call a file from the index.html file?

I have the following:

- daemon/
---- app.js
- index.html

and from the index I do this:

require('./daemon/app');

and it wont work. Any ideas why?

**Comment by Mithgol** [comment]
Works for me.

Try `console.log( process.cwd() )` to check whether `'./daemon/app'` is relative to a directory you haven't expected.

**Comment by lili21** [comment]
@Mithgol What if I have no main html file ?  Like below manifest config
```
{
  ...
  "main": "http://mywebsite.com"
  ...
}
```
, then what's the resolved according path ?

**Comment by Mithgol** [comment]
`¯\_(ツ)_/¯`   I have no idea because I've never tried that yet.
