### ISSUE TITLE
child_process.fork() workaround for windows

### ISSUE THREAD

**Issue by kraag22** [nwjs/nw.js#1516]
If you want to use child_process.fork() you cannot, because of issue #213 
But if specify your own node executable in the options like this
`var processing = ch.fork('c:\\reader.js', [], {execPath: 'c:\\node.exe'})`
you can use it. There is no problem running on mac, but in windows you forked node will crash if there is any stdio operation. Child process will crash with exit code 8.

So example code:

```
var ch = require('child_process')

console.log("I'm alive");

var processing = ch.fork('c:\\reader.js', [], {execPath: 'c:\\node.exe'})

processing.on('message', function(data) {
    console.log(data);
    if (data['status'] === 'ok') {
        console.log('ok');
    } else if (data['status'] === 'error') {
        console.log('error');
    }
});
processing.on('exit', function(code) {
    console.log('exited with code:', code);
});
processing.send({});
```

This code will fail on windows when the reader.js prints anything in the console for us. The workaround is adding silent:true to fork() options.

`var processing = ch.fork('c:\\reader.js', [], {execPath: 'c:\\node.exe', silent: true})`

I hope this will save some time to anyone experiencing this problem.

**Comment by JoyKrishnaMondal** [comment]
Thanks a lot !! This is amazing

**Comment by nobook** [comment]
Thanks a lot !!
