### ISSUE TITLE
Transparency in window.capturePage

### ISSUE THREAD

**Issue by piezas** [nwjs/nw.js#1523]
Thanks for the wonderful project.

I have need to retain the alpha of a transparent page render (for content generation purposes).  The code I believe for such an operation is in capture_page_helper.cc here:

 case FORMAT_PNG:
      encoded = gfx::PNGCodec::EncodeBGRASkBitmap(
          screen_capture,
          true,  // Discard transparency.  <-- move to false, that easy?
          &data);

Thinking about going through the 14G build process with Chromium again makes me cry a little.  I've searched around for a debug build of node-webkit, but haven't found one.  Is a symboled build for Mac available?  If so, I'd be happy to hex edit true to false in hacker spirit and call it a day if it works.

Is such a build available?  Ultimately, I think PNG w/alpha support or someone else's suggestion for the raw buffer to node (and avoid the encoding step for a possibly video accelerated step) would be very useful for a variety of applications.

Thanks!
##

**Comment by bsudekum** [comment]
Any updates here? I'm interested in flipping this flag to `true` for a screen capture tool I'm working on.
