### ISSUE TITLE
(0.8.4-2) Unable to display source of scripts in Devtools.

### ISSUE THREAD

**Issue by BKcore** [nwjs/nw.js#1531]
### Version

`node-webkit ~0.8.4-2 OSX 10.9`
### Context

Given a simple project:

```
app/
  index.html
  index.js
  lib/
    main.coffee
```

package.json:

``` json
{
  "author": "<author>",
  "name": "<name>",
  "description": "<description>",
  "version": "<version>",
  "private": true,
  "main": "index.html",
  "scripts": {
    "start": "nodewebkit"
  },
  "dependencies": {
    "nodewebkit": "~0.8.4-2",
    "coffee-script": "~1.6.3"
  }
}
```

index.html:

``` html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<script src="index.js"></script>
</body>
</html>
```

index.js:

``` js
require('coffee-script');
require('./lib/main').init();
```
### Problem

In the devtools, I can see the source for `index.js`, but `lib/main.coffee` is absent. Also, putting a `debugger;` statement in `lib/main.coffee` pauses the execution, but the source tab doesn't show the file or the breakpoint.
### Notes

I'm running this via `npm install nodewebkit` and `npm start`
I'm sure lib/main.coffee is loaded properly since the code inside it runs (some log statements).
##

**Comment by glikker** [comment]
I don't know if this is the same issue or related, but I can't view source files that were loaded in Node after a page change.  Same symptoms, but only after a page change (window.location = "newfile.html"), and only for sources loaded into Node (using require) on the previous page.  Also, I'm using 0.12.2.
