### ISSUE TITLE
Middle click on link in iframe bug

### ISSUE THREAD

**Issue by VoidVolker** [nwjs/nw.js#1547]
Middle click or ctrl+enter or ctrl+click is open link in the same window where iframe, but not in iframe.
OS: Windows 7 x64 Pro
NW: 0.9.0

**Comment by gdbate** [comment]
Heh did you figure this out @VoidVolker I am running into the same issue, the new-win-policy doesn't seem to get triggered.. when control+clicking a link.

**Comment by VoidVolker** [comment]
Yes, this bug still exist.

**Comment by gdbate** [comment]
I fixed it by adding an onclick event to all the anchors on the iframe pages checking for control being clicked. [https://github.com/gdbate/nw.js-iframe-browser](https://github.com/gdbate/nw.js-iframe-browser "https://github.com/gdbate/nw.js-iframe-browser")

**Comment by jorisvddonk** [comment]
@gdbate That doesn't fix the issue with middleclicking on links; middleclicking still causes the middleclicked link to open in the entire window.
@rogerwang Since this issue hasn't been resolved, can this issue be reopened again?
