### ISSUE TITLE
Javascript "alert" crashes v.0.9.0 on windows

### ISSUE THREAD

**Issue by gunnar-t** [nwjs/nw.js#1552]
Hi Roger,

when I call "alert" via javascript, the nw.exe crashes directly. (I have tested this in my programs and in an "naked" nw.exe via the developer console). 
This happens since v.0.9.0. 

==> Win7, node-webkit v.0.9.0

By the way: great work anyways :)

**Comment by kikong** [comment]
Alert window still can't drag in 0.12.0-alpha3
