### ISSUE TITLE
Blurry icon on Windows 8 in title bar

### ISSUE THREAD

**Issue by jufoslav** [nwjs/nw.js#1554]
The icon of my application in the title bar is blurry, but only on Windows8. The used image has a size of 256x256 and I tried also other sizes. This counts for my own icon and also for the default node-webkit icon (see attached Screenshot).

Do anybody knows a solution for this?
![bildschirmfoto 2014-02-11 um 10 00 48](https://f.cloud.github.com/assets/3041105/2135273/7046e770-92fb-11e3-9b96-4c16d4c44e80.png)
##

**Comment by 1j01** [comment]
I think "jagged" is more descriptive. Looks like it's being downscaled using nearest-neighbor interpolation. It would look better with pretty much any other interpolation algorithm.
:+1: You should be able [to specify multiple icon sizes](https://github.com/nwjs/nw.js/issues/986)
