### ISSUE TITLE
nwsnapshotted app crash in forEach/map (0.9.1 win32)

### ISSUE THREAD

**Issue by igorklopov** [nwjs/nw.js#1569]
The app is compiled by nwsnapshot. When array is iterated via forEach, the app crashes at 130-th element (256 boundary hit somewhere?). Map, filter, reduce and others are also affected. Hence, nwsnaphot way is not usable at all in 0.9.1. Node-webkit 0.9.0-rc1 has the bug either. Node-webkit 0.8.4 passes successfully (but the source code is disclosed in "test.bin").
### test.bat

```
nwsnapshot.exe --extra-code test.js test.bin
nw.exe
```
### test.js

```
function F() {
  var test = [];
  for (var kk = 0; kk < 180; kk++) {
    test.push(12345);
  };
  test.forEach(function(i, x) {
    // crashes when x is 130, even if no payload
  });
  alert("success");
};
```
### test.htm

```
<!doctype html>
<html><head>
</head>
<body onload="F();">
</body></html>
```
### package.json

```
{
  "name": "test",
  "main": "test.htm",
  "snapshot": "test.bin",
  "window": {
    "position": "center"
  }
}
```
##

**Comment by rogerwang** [comment]
there is a new tool for this feature in 0.12.0-rc1, which removes the size limitation and fixes crashes. please try it: https://groups.google.com/d/msg/nwjs-general/Sykci3Qhgus/AoF0zT7TEIoJ
