### ISSUE TITLE
process.title crashes the nw process

### ISSUE THREAD

**Issue by nebulade** [nwjs/nw.js#1570]
A plain <script> process.title = 'foobar'; </script> in the main html file lets the nw application crash right away.

I am not sure which of the webkit processes it would set the title in the first place, but it should not crash.

This happens at least on v0.9.0 on ArchLinux.

Let me know if you need more information.

**Comment by 1j01** [comment]
I'm also seeing the unicode garbage on Windows 8.1
Sometimes it returns an empty string
![process title](https://cloud.githubusercontent.com/assets/3630663/7099970/ec2e8394-dfd4-11e4-8f98-4f6d73b3d2b6.png)

**Comment by niemyjski** [comment]
Also getting this garbage.
