### ISSUE TITLE
WebWorker not working anymore (from v0.8.4 to 0.9.1)

### ISSUE THREAD

**Issue by gunnar-t** [nwjs/nw.js#1575]
Hi Roger, 

my project heavily depends on WebWorkers for long running tasks. I figured out that with change to v.0.9.1 none of my web workers are working anymore. 

The web worker is created (as far as I can see) and immediately sends diconnect and close events.

I switched back to 0.8.4 and everything works fine again. 

Did I miss some changes in the release notes?!  Maybe the switch to chromium 32?
This feature is crucial for my app (and maybe for some other people too).

Thanks again for your work :)

**Comment by mib4fun** [comment]
Is it fixed ?
