### ISSUE TITLE
inject-js-start and inject-js-end issues

### ISSUE THREAD

**Issue by hugomarisco** [nwjs/nw.js#1585]
Hey, I'm trying to make use of inject-js-start/inject-js-end to inject some javascript in every page loaded but it doesn't seem to work.

I'm using a simple `alert("injected");` to test it, running under Windows 8.1.

`package.json`

``` json
{
  "name": "nw-demo",
  "main": "index.html",
  "inject-js-end": "init.js"
}
```

`init.js`

``` javascript
console.log("injected");
```

https://github.com/rogerwang/node-webkit/search?q=inject-js-start&type=Issues
https://github.com/rogerwang/node-webkit/search?q=inject-js-end&type=Issues

didn't help...

Thanks in advance for any help!

**Comment by Kuchiriel** [comment]
Still did't working.
