### ISSUE TITLE
Developer tools: most shortcuts don't work (OS Windows)

### ISSUE THREAD

**Issue by GHSoCoder** [nwjs/nw.js#1597]
I'm working with automation, so I need shortcuts. Most of the shorcuts don't work. And it's not possible to select the main menu items via [Alt+_] combinations. I'm a Windows user.
Thanks for any hints.
##

**Comment by TheJaredWilcurt** [comment]
I'm working on a framework to help assist those starting with NWJS. It's aimed specifically at those creating a GUI for CLI. However there are many toys and tools I'm throwing in there just to make life easier for any NWJS developer. One of these is keyboard shortcuts. I'm not 100% sure what you're requesting, but I have the following shortcuts created and usable with copy/paste:

* **F5** Soft Refresh
* **Shift+F5** Refresh ignoring cache
* **CTRL+F5** Hard Refresh
* **F12** or **CTRL+Shift+I** Open Webkit's Developer Tools

My project is called UGUI (Universal GUI). It is not to version 1.0 yet, but should be there in the next 7-12 days. One of the finishing touches I need to put on it is testing the keyboard shortcuts in linux and osx. Right now they only work in Windows.

* https://github.com/TheJaredWilcurt/UGUI/blob/master/_scripts/ugui.js#L414

**Comment by GHSoCoder** [comment]
Hello TheJaredWilcurt,

many thanks for your answer. I will take a look in your project asap.

The shortcuts I'm missing are the ones mentioned here in section "Sources Panel":
Keyboard Shortcuts - Google Chrome
https://developer.chrome.com/devtools/docs/shortcuts

Especially those for stepping, go to line and so on.


Pls. contact me via PM.

Many thanks and greetings
GHSoCoder

**Comment by TheJaredWilcurt** [comment]
There is no way to message users directly on GitHub. This feature was removed. If you think that was a dumb idea, like I do, at the bottom of the page, click Contact and send them a message requesting the feature be brought back.

That page lists like a million shortcuts. I'm pretty sure most of these are possible with the current version of nw.js. I'm just creating a function that detects key presses and runs built in features listed on the nw.js documentation.
