### ISSUE TITLE
Open local files outside app.nw in app folder

### ISSUE THREAD

**Issue by daggert** [nwjs/nw.js#161]
Hello! I'm starting using node-webkit in my project and got some little trouble. I had make fullscreen app and burn it into CD, to show my app. But then I start .exe file, app starting read all zip... slowly read... 460Mb...

Then I open browser and read all wiki, but I find no any decision to load file inside app home folder.

There is "app tree" I would like to create:
CD
| data
|__sound1.ogg
|__sound2.ogg
|__pictures
|____picture1.png
|____picture2.png
| app.exe
| nw.pak

The main idea - the app.exe it's just packed app and all resourced files it's placed outside.

**Comment by shikha91** [comment]
hi 

i am doing the same like but i have a problem please help me ..

i have created or app.exe by nw.exe and zipped all files in this exe....
and with this exe i have a file (file.txt) and i want to read that file how can it possible ....please help

**Comment by shikha91** [comment]
hi 
one thing more what is nw.pak i have in nwjs resources.pak ...is there any diffrence in both...

**Comment by rogerwang** [comment]
@shikha91 please ask questions in the mailing list https://groups.google.com/forum/#!forum/nwjs-general

do not hijack threads.
