### ISSUE TITLE
 App.clearCache() is ineffective?

### ISSUE THREAD

**Issue by gallex** [nwjs/nw.js#1610]
test version is 0.92
##

**Comment by RaghavRamesh** [comment]
+1

**Comment by gearintellix** [comment]
+1 im trying do same

**Comment by Christywl** [comment]
I try a simple test and it works fine on nwjs-sdk-v0.26.6. Please try the latest nwjs build, if still reproduce, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
