### ISSUE TITLE
node-main: errors and console.log not redirected to webkit console

### ISSUE THREAD

**Issue by FunkMonkey** [nwjs/nw.js#1629]
tested with nw version: 0.8 and 0.9.2 on windows

We had errors in our script that is used as `node-main`. Unfortunately neither the errors nor `console.log` appeared in the webkit console. Not even in the terminal.

We could only retrieve the errors by logging them to file, having a big try/catch block around everything.

Apart from this bug, I would propose two new options for `package.json`, one for logging everything (errors, `console.whatever` from windows and `node-main`) to a log-file and one for logging everything to the terminal.

Thanks a lot. Great tool! :)

p.s. Linux shows errors in terminal (on windows nw seems to create a child process)
##

**Comment by frankhale** [comment]
I cannot get any of the proposed work arounds to work in 0.13.1. Is there anyway to output to STDOUT or STDERR messages for debugging node-main scripts?

**Comment by mpech** [comment]
you may try
`process.stdout.write(util.format.apply(util, arguments));`

**Comment by frankhale** [comment]
Thanks @mpech , I will give this a try!!!

**Comment by phroph** [comment]
None of the solutions have worked for me, however I'm running the application through an IDE (using an NPM script) so there is more potential for issues there. I've tried all the suggestions in this thread to no avail (including using process.stdout/stderr).

**Comment by coolguy001tv** [comment]
Actually, console.log is ok. You should check the log in the app with mouse right click, and choose the last item(*检查背景页(B)* which in English may be *check background(B)*), and it shows the log.

**Comment by Shawn-ye** [comment]
@coolguy001tv 
really wish the problem is that simple, but the fact is , we know how to open the devTools.

**Comment by Christywl** [comment]
I try a simple test on nwjs-sdk-v0.26.6, the error in node.js script(`node-main`) could be shown in the DevTools for background page.
Does it still reproduce for you? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
