### ISSUE TITLE
Caching issue with Flash files

### ISSUE THREAD

**Issue by sagibb** [nwjs/nw.js#1642]
It seems that SWF files are not cached properly in NW so though the server returns the proper headers, a new request is always issue (200 response, rather than 200 (cached) or 304).

I've created a very basic demo that showcases the problem. The zip files can be download here: https://drive.google.com/file/d/0B_R2Y-rDlXfVakNUZWVfdjdNbTQ

I am currently using v0.8.5

![headers](https://f.cloud.github.com/assets/399461/2301152/b9459660-a129-11e3-8dcf-28163e6d7e72.png)
##

**Comment by manast** [comment]
I am having the same problem, but with video files. I guess it happens with any file that is over a given certain size... Small videos files are cached properly.
