### ISSUE TITLE
require.resolve and require.cache are undefined

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#1659]
Node-Webkit replaced the `require` with a wrapper of original node.js `require`. But another two APIs `require.resolve` and `require.cache` are not there. This is slight difference may cause some error for node.js modules depending on these APIs.
##

**Comment by josephlimb** [comment]
In version 0.12.0 the require.resolve and require.cache variables still return undefined. Any update on this issue?

**Comment by jaruba** [comment]
@josephlimb 

``require`` is ``global.require`` in NW.js

So just use ``global.require.resolve`` and ``global.require.cache``
