### ISSUE TITLE
SpeechSynthesis Voices missing

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#1661]
Somehow, the Speech Synthesis Voices are missing in node-webkit. The APIs are available, but nothing is heard, because there is no voice.

speechSynthesis.getVoices(); --> []

So, text-to-speech capabilities are missing.

**Comment by ruffrey** [comment]
There is an npm package `say` - i wonder it it would work.

**Comment by ryanwashacked** [comment]
I would recommend the google translate tts API untill this feature is fully supported.

http://translate.google.com/translate_tts?tl=en&q=Hello

**Comment by sholladay** [comment]
I haven't tested this, but I wonder if it only _appears_ this way. You see, Chrome loads the voices asynchronously, and yet stupidly provides this synchronous `getVoices()` API that is incompatible with the actually strategy of loading them. The result is that typically, in Chrome, when you first call `getVoices()` it will give you an empty list. On top of that, it only loads the voices on-demand and doesn't populate the original array. So you must call `getVoices()`, wait for the `voiceschanged` event, then call `getVoices()` a second time, before you can actually get your hands on the voices. It is ridiculous.

**Comment by helloncanella** [comment]
same problem.

**Comment by benoist1** [comment]
btw, if you are OSX you can use the command line program 'say' instead
of the browser based solution.

**Comment by helloncanella** [comment]
I thank you for the suggestion, but my main concern is to deploy it (the speechSynthesis) in a cross-platform...

**Comment by franciclo** [comment]
please fix it, thank you, it would be really cool to use the text to speech api.

**Comment by offshore** [comment]
Maybe it's time to check out [chrome.tts](https://developer.chrome.com/apps/tts)?
```javascript
chrome.tts.speak("Maybe it's time to check out Chrome TTS API?");
```

**Comment by benoist1** [comment]
Is Chrome. TTS supported yet? I found this thread
but its hard to see what was actually made to work...
https://github.com/nwjs/nw.js/issues/518

**Comment by rasouar** [comment]
As a work around we can use eSpeak, with or without cylon,js to achieve Speech Synthesis.
We can overwrite the SpeechSynthesis methods to lunch a node child process with text as commandline argument  to eSpeak to synthesize the voice. 
eSpeak is available on both Windows and Linux (don't know about iOS), it may be a solution for some people. I'm not sure if anyone is interested in bundling it with NW.js

http://espeak.sourceforge.net/index.html
http://cylonjs.com/documentation/platforms/speech/

**Comment by tatosgames** [comment]
Need it for accessibility software for blind, I would like to get the official support not the workaround :+1:

**Comment by ghostoy** [comment]
This should be fixed in 0.13.0 RC.

**Comment by tatosgames** [comment]
I tested, it works!

**Comment by KingRial** [comment]
I can confirm too.

The quality leaves much to be desired but, it works!

**Comment by lellex** [comment]
Could you provide a working example of using speechSynthesis with eSpeak please ?
I try to build an app for blind and I need it.
Already try with electron, tts work fine but I have poor performance, I would like to test with nw...

**Comment by rogerwang** [comment]
NW's performance should be the same as Chromium, which you might want to try.

**Comment by lellex** [comment]
Oh yes ! espeak is enable on Chromium only with command flag "--enable-speech-dispatcher"... so it's the same with NW : 

`nw . --enable-speech-dispatcher`

**Comment by lellex** [comment]
Another weird issue : voices are available on linux (which I use for dev) only with Cylon, but windows doesn't support cylon and it work fine without it.

Any idea ? Does anyone already use NW and speechSynthesis on linux ?

**Comment by rogerwang** [comment]
On windows it may be using the OS support. And 
please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
