### ISSUE TITLE
No contextmenu in DevTools

### ISSUE THREAD

**Issue by b1rdex** [nwjs/nw.js#1666]
Test case:
1. Open dev tools, `Elements` tab
2. Rightclick on any DOM node

Expected: contextmenu
Got: nothing

You can see this menu in Chrome or any webkit-based.

NB: this menu works as expected and properly if you start nw with `--remote-debugging-port=9222` and then open `http://localhost:9222` in any other browser.
NB2: it's wow-amazing, but if you navigate `http://localhost:9222` with new instance of nw, contextmenu will work → it's not work only in devTools.

**Comment by boggen** [comment]
is there a fix to this?

duplicate -> https://github.com/nwjs/nw.js/issues/2143

has an example ->
http://stackoverflow.com/questions/27754720/indexeddb-how-to-get-updated-data-without-reloading-the-page

direct link to example ->
http://jsfiddle.net/kzwtyn2c/

i can add, put, get, delete to my hearts content. but i only get a one shot update, or less i manually refresh the page.

off to find a indexeddb vanilla script that i can load directly into page.
