### ISSUE TITLE
win.cookies.remove() crash on Maverick [$25]

### ISSUE THREAD

**Issue by gabrielstuff** [nwjs/nw.js#1678]
Try to open the nodewebkit app and run the following in the console :

```
var gui = require('nw.gui');
var win = gui.Window.get();
win.cookies.remove();
```

the app crash instantanely.

Here's the log : 

http://hastebin.com/teragituqa.avrasm

**Comment by Weiyoung-Zhou** [comment]
That works perfectly, thanks much! @kamesh-a

**Comment by eabovsky** [comment]
+1 - win.cookies.remove() - crashes on OSX 10.10.1

**Comment by AlexWindHope** [comment]
cookies.remove crashes for a reason, you should pass 2 parameters as described in [official documentaton](https://developer.chrome.com/extensions/cookies#method-remove)

Also, if your goal is to delete all existing cookies across all domains (which is probably why you was trying to call this method at the first place), than you need to get them and remove one by one, you can get the list of all cookies using getAll method (which also accepts 2 parameters) like this:
```
require('nw.gui').Window.get().cookies.getAll({}, function(cookies) {
	cookies.forEach(function(cookie) {
		console.log(cookie);
	})
});
```
Overall – as long as you follow official chrome extension documentation everything should work just fine.

**Comment by hxzqlh** [comment]
@AlexWindHope  you did me a favor, this sln is ok! Thank~
