### ISSUE TITLE
Tray icon remove() method doesn't remove the icon from second display

### ISSUE THREAD

**Issue by HaiColon** [nwjs/nw.js#1691]
When you create a tray icon and remove it with

```
tray.remove();
tray = null;
```

, the tray gets correctly removed from the first display connected to the computer, but not from the second.

node-webkit 0.9.1, Mac OS X. I don't know if this also happens on other platforms as this problem was reported to me by a user of my application and I don't have two displays connected to try it out myself.

**Comment by mrfabbri** [comment]
No further issues report, closing this one.
