### ISSUE TITLE
how to catch nodejs error

### ISSUE THREAD

**Issue by askie** [nwjs/nw.js#1699]
error on nw win ,error display such like bellow:

Uncaught node.js Error 

TypeError: Cannot call method 'get' of undefined
    at Object.nav (http://a.tbcdn.cn/apps/userportal/console/js/header-min.js:1:61)
    at eval (http://a.tbcdn.cn/apps/userportal/console/js/header-min.js:1:446)
    at _fireReady (http://a.tbcdn.cn/s/kissy/1.2.0/kissy.js:2905:20)
    at _bindReady.fire (http://a.tbcdn.cn/s/kissy/1.2.0/kissy.js:2824:17)
    at HTMLDocument.domReady (http://a.tbcdn.cn/s/kissy/1.2.0/kissy.js:2837:17)

**Comment by sergiovilar** [comment]
Anyone can answer this question about the better way in production?

**Comment by hsdk123** [comment]
I feel this needs more attention - so what should we be doing in production?

**Comment by runningship** [comment]
I have the same question.I'm still confused of the way nw handle uncaught exceptions . 
Is it possible nw catch all all uncaught exception natively and log error info in console,I think that will be good enough.

**Comment by bhaveshgohel** [comment]
This is how i handle Uncaught Nodejs Error:

```javascript
/*------------ Uncaught Nodejs Error prevent and Logger-----------*/

// clean exceptions from a previous load (refresh case)
if(process._events.uncaughtException.length > 0){
    process._events.uncaughtException.splice(0,1);
}
process.on('uncaughtException', function(e){
    console.group('Node uncaughtException');
    if(!!e.message){
        console.log(e.message);
    }
    if(!!e.stack){
        console.log(e.stack);
    }
    console.log(e);
    console.groupEnd();
});
// Clean Buggy thing
if(process._events.uncaughtException.length > 1 
    && !!process._events.uncaughtException[0].toString().match(/native code/)
){
    process._events.uncaughtException.splice(0,1);
}

/*------------ Uncaught Nodejs Error prevent and Logger-----------*/

```
Hope it helps! :+1:
