### ISSUE TITLE
CSS :hover broken in kiosk mode

### ISSUE THREAD

**Issue by pauliusuza** [nwjs/nw.js#170]
Bug in 0.3.2 - 0.3.3 on OSX 10.7.5

The CSS :hover property is not working when application is in kiosk mode.

To debug, please use the source code from: 
https://s3-eu-west-1.amazonaws.com/pauliusuza/shared-node-webkit/node-webkit_bug_168.zip

To reproduce the bug, hover on the "Close" button while in kiosk mode - no border will appear. Click the button to exit the kiosk mode, try to hover on the button again - border will appear.

**Comment by lennerd** [comment]
Any news?

**Comment by samvieten** [comment]
reproducing the issue, any fix?

**Comment by rogerwang** [comment]
@samvieten it there a case for this? and is it reproducible in Chromium browser?
