### ISSUE TITLE
Sometimes quit node-webkit does not trigger "close" or "closed" event

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#1713]
On Mac OSX, there are several ways to quit node-webkit app:
* `Cmd+Q` or click "Quit xxx..." on menu
* Close a window through "x" button on top left
* **Use `App.quit()`**
* **Right click on the app icon on the dock, and click quit**

The first 2 cases trigger `close` and `closed` event correctly on `Window` object. But on node-webkit **0.8.5**, the **last case** does **NOT** trigger these events. And on node-webkit **0.9.2**, the **last 2 cases** do **NOT** trigger these events.

**Comment by zweicoder** [comment]
This is not working on Windows 8. Having a `win.close()` in my tray icon menu fails to register the `close` event. Repeating the logic there for now.

**Comment by MadLittleMods** [comment]
[According to the docs](https://github.com/nwjs/nw.js/wiki/app#quit) `App.quit()` doesn't fire the `close` event.

With OSX on nw.js@0.12.3, the following methods fire the `close` event for me.

 - Cmd+Q or click "Quit xxx..." on menu
 - Right click on the app icon on the dock, and click quit
