### ISSUE TITLE
Context menu in popup window.

### ISSUE THREAD

**Issue by orthecreedence** [nwjs/nw.js#1718]
Hello, my app is making good use of the new "Taskbarless window" feature just recently released, however I'm noticing that when I spawn a context menu via `new gui.Menu().popup(x,y)` it always shows in the main window (or, at least, the x,y coordinates are relative to the main window). Is there a way to attach a menu to another window, or at least translate the coordinates somehow?
##

**Comment by Yerhabe** [comment]
Any progress with this?
