### ISSUE TITLE
"Third party browser plugins#Location of plugins" it doesn't work

### ISSUE THREAD

**Issue by Labber1900** [nwjs/nw.js#1723]
I put my NPAPI plun-in file( named NetscapeCoreAnimationMoviePlugin.plugin) on the /plugins Folder.And then ,run  nw /demo,start node-webkit,but it alert: can't load the plugin.The plugin can work at FireFox and Safari brower.

**Comment by rogerwang** [comment]
NPAPI is not supported by Chrome and NW any more.
