### ISSUE TITLE
Error: Module version mismatch. Expected 13, got 11 with node-webkit and node-java

### ISSUE THREAD

**Issue by bradylove** [nwjs/nw.js#1726]
I am trying to use node-java to use the a java library with node-webkit v0.8.5. After installing node-java with `npm install java` i then recompile node-java with nw-gyp `cd node_modules/java; nw-gyp rebuild java --target=v0.8.5`. Compilation completes successfully however when I package and run the app I am getting the following error.

```
Uncaught node.js Error 

Error: Module version mismatch. Expected 13, got 11.
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at Object.eval (/private/var/folders/zm/72hftccn4y179wsblnt_n30w0000gn/T/.org.chromium.Chromium.9Q6nN8/node_modules/java/lib/nodeJavaBridge.js:5:16)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
```

Here is my `package.json` and `app.js` file that is is loading node-java

```
  "name":"test-node-java",
  "version":"0.0.1",
  "main": "index.html",
  "dependencies": {
    "java": "0.3.1"
  }
```

```
var java = require("java");
```

I have tested the above code outside of node-webkit (before rebuilding node-java) and everything worked great using Node 0.10.26.

Did I miss any steps here? Has anyone successfully used node-java with node-webkit? Any help/tips would be appreciated.
Edit: I should also note that I am using node-webkit 0.8.5 32bit on OSX.

**Comment by AnnamrajuSarvani** [comment]
Hi 
I am getting following error when try to rebuild with nw 0.22.3 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/cronj-10/.nvm/versions/node/v5.11.0/lib/node_modules/nw-gyp/lib/build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-115-generic
gyp ERR! command "/home/cronj-10/.nvm/versions/node/v5.11.0/bin/node" "/home/cronj-10/.nvm/versions/node/v5.11.0/bin/nw-gyp" "rebuild" "--target=0.22.3"
gyp ERR! cwd /home/cronj-10/Sarvani/offline-sample-app-new/node_modules/java
gyp ERR! node -v v5.11.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
