### ISSUE TITLE
getting/setting position or resolution results are different between OS when window is minimized

### ISSUE THREAD

**Issue by CodeTrol** [nwjs/nw.js#1731]
On Windows if I hit command `require('nw.gui').Window.get().x` when window is minimized result is -32000. I can't change position/resolution of window in this state (tested on XP,7). 
Linux - works perfectly. (tested on Kubuntu 12.04)
MacOS - not tested.

node-webkit: v0.9.2.

My goal is to display window (which is unique) at last state it was when was closed.

To reach this goal I should catch 'move','resize','maximize' events and do own way just for Windows (should I do it for Mac too?). 
##

**Comment by tphalp** [comment]
This is still an issue with 0.12.3. I've found the same issue. When the app is minimized, the x and y coordinates are both changed to -32000.
