### ISSUE TITLE
Persistance in nw apps, what to use?

### ISSUE THREAD

**Issue by jeroenransijn** [nwjs/nw.js#174]
Node-webkit is a great platform to develop in, but lately some issues about supported databases arose. In addition to this I would like some clarification, what kind of persistance is currently supported in node-webkit.

The following is what I understand and assume, please correct this if I am wrong:
- localStorage is supported with no size limit, this object exists on the window object so can't be used within a node context, with the consequence that it can't be required, but instead needs to be a script tag in the index.html. Also localStorage is exposed.
- Web SQL, is basically SQLite within the webkit context. So this can't be required also. And this is exposed.
- If I want to include models from different files build on top of localStorage or Web SQL, I need to include those in my index.html and add them to the window object, to expose them to other files.
- I can do persistance/db's in node with node modules such as MongoDB or CouchDB, but they are really made for a server environment, so is this a best choice?

More confusion I have is about the webkit and node context. If I would like to build a MVC framework for my app, how would I include those files? Add them to my index.html, or require them over node?

**Comment by ashantyk** [comment]
to the author of this issue: localStorage is limited in size. i capped it at around 13MB

**Comment by louischatriot** [comment]
NeDB uses the best storage engine available, usually indexeddb with no hard limit (you'll reach NeDB's limits before running out of space)
