### ISSUE TITLE
v0.9.2 does not capture keyboard input on OSX 10.9

### ISSUE THREAD

**Issue by thebradbain** [nwjs/nw.js#1760]
When running a node-webkit app via

```
# note app is the directory with my package.json file
nw app
```

the window created does not allow me to enter input at all: not in the address bar, not in the developer console window, and not within input fields in the body of the document.

I'm running OSX 10.9 with Node 0.10.26 and version 0.9.2 of node-webkit. Obviously this isn't a common occurrence or it would have been noticed much sooner. Any suggestions would be greatly appreciated.
##

**Comment by i-have-no-name** [comment]
I create alias, but after run the window created does not allow to enter text

**Comment by octalmage** [comment]
I was having the same issue with the nw npm package, updating solved it for me! So this was fixed at some point.
