### ISSUE TITLE
Auto-update node-webkit from app (nw.pak completely locked)

### ISSUE THREAD

**Issue by Gregg8** [nwjs/nw.js#1763]
I have reviewed issue [#233](https://github.com/rogerwang/node-webkit/issues/233) and see that there is good discussion on this topic and that one day, there will be an auto-updater.

In the mean time, I am trying to write a specific one for our app which is distributed as four files: `{app}.nw`, `nw.exe`, `nw.pak` and `icudt.dll`.

While the app is running, Windows allows us to rename `nw.exe` and `icudt.dll`, then we can copy the new ones in. Great.

The `{app}.nw` file is not locked so we can just replace that. Easy.

The `nw.pak` file however, is locked in a more serious way and doesn't allow us to rename it. Ugghh!

Is there a way around this, apart from exiting the app and running a separate updater (as that would need updating as well and would ultimately suffer from the same problem anyway)?

Is there a way that `nw.exe` could open `nw.pak` without locking it so completely?
##

**Comment by Morched23MJ** [comment]
Just an idea for new comers.

In order to apply the update, you may copy the whole app folder into a temporary directory. Run the app from there, apply the update, thus overwriting the original app folder. Rerun the updated app from its folder once again.
