### ISSUE TITLE
API for get all windows

### ISSUE THREAD

**Issue by halida** [nwjs/nw.js#1764]
Hi, I think it is convenient to have a API which can get all windows, like this:

```js
windows = require("nw.gui").Window.getAll()
// => windows = [Window1, Window2, ...]
```

Using that I can track and monitor user behavior, and do some cross window operation properly.

Even though I can record the window handle after calling `Window.open`, Tracking opened window is a messy job for developer.

**Comment by AndrePessoa** [comment]
@nwjs-bot, I just tryed to update a app to 0.16 now and "global.__nwWindowsStore" didnt works... 

I found "__nw_windows" but it's not the same... How get all windows now?

**Comment by ghostoy** [comment]
You can use `chrome.app.window.getAll` to get all AppWindows. If you want to get corresponding `nw.Window`, use `nw.Window.get(appWindow.contentWindow)`.

**Comment by AndrePessoa** [comment]
@ghostoy, thks very much!

**Comment by surinder83singh** [comment]
if you are using "new_instance: true"  while opening new window then 
`chrome.app.window.getAll` fails

try this

> chrome.windows.getAll({populate: true}, function(wins){
>     console.log("windows", wins)
> })

**Comment by gazhay** [comment]
This is still the top result on google, but yields 

`TypeError: Error in invocation of nw.Window.getAll(function callback): No matching signature.`
