### ISSUE TITLE
How to set the NW default window's background?

### ISSUE THREAD

**Issue by linb** [nwjs/nw.js#1776]
How to set the NW default window's background? 

Add a background picture or a progress bar.

The uggly default window alway shows a few seconds before the real app UI was loaded.

**Comment by capsule5** [comment]
@treeform hey I cant find the option you're talking about. How to hide the original window before code is ready?

**Comment by shichon64** [comment]
@capsule5 Maybe you want this :
https://github.com/nwjs/nw.js/wiki/Show-window-after-page-is-ready

**Comment by capsule5** [comment]
@shichon64 thank you!
