### ISSUE TITLE
MenuItem type: 'checkbox' event, can't set this.checked properly

### ISSUE THREAD

**Issue by ivantodorovich** [nwjs/nw.js#1780]
I'm trying to prevent the checkbox from being checked if a confim('Are you sure?') response is false.

The code looks like this:

```
var item = new gui.MenuItem({
	label: 'Menu Item Label',
	type: 'checkbox',
	checked: false,
	click: function(e) {
		if (this.checked) {
			if (confirm('Are you sure?')) {
				// do stuff
			} else {
				this.checked = false // prevent check
			}
			win.focus() // fix window losing focus after confirm
		} else {
			// dont do anything
		}
	}
})
```

Behaviour isn't as expected. Setting the checked property from inside the callback doesn't seem to work. Causes a weird bug where the visual style doesn't get updated (At least I think that's what's happening) while the checked property is indeed being set.

**Comment by qinyuanpei** [comment]
What a fuck! 
I meet the same problem in here and did you solve this problem?

**Comment by qinyuanpei** [comment]
Yesterday  I had try it successfully and it should be write as this:
```
viewMenu.append(new gui.MenuItem({ 
    label: '实时预览',
    type: 'checkbox',
    checked: 'true',
    click: function(){
      if(this.checked==false){
        ed.unwatch(function(){
          console.log("hide the preview")
        });
      }else{
        ed.watch(function(){
          console.log("show the preview")
        });
      }
    } 
  }));
```
