### ISSUE TITLE
I package the app. It could run on my computer. But it doesn't work on another window 7 computer.

### ISSUE THREAD

**Issue by zalezhu** [nwjs/nw.js#1800]
I require node-java module in my app.  I could run the app in my computer after package. But When I put it to another computer(windows 7) I got the error 
Uncaught Error: The specified module could not be found.
C:\Users\icy\AppData\Local\Temp\nw7696_15867\node_modules\java\build\Release\nodejavabridge_bindings.node 

What's wrong? 
##

**Comment by bgSosh** [comment]
@zalezhu - Did you resolve this?
