### ISSUE TITLE
node-ffi & NodObjC

### ISSUE THREAD

**Issue by marcfowler** [nwjs/nw.js#1811]
I'm trying to make use of specifically [node-castro](https://github.com/hugs/node-castro). This looks to be pretty simple, and depends on [NodObjC](https://github.com/TooTallNate/NodObjC) to work.

So I have looked through the tree and found all dependencies myself:
- bindings
- debug
- libxmljs
- node-ffi
- NodObjC
- ref
- ref-struct

Of these, **ref**, **node-ffi**, and **libxmljs** require rebuilding with nw-gyp.

I'm using v0.9.2, and when I try `nw-gyp rebuild --target=0.9.2` on **node-ffi** it fails with the following output: http://jmp.sh/v/RxRcwbZo769WyvOhD3lM

Next I tried all previous versions, and once I got down to `nw-gyp rebuild --target=0.8.6` it succeeded. So I tried to use that, **and** I did roll back myself to be using node-webkit 0.8.6 (and repeated the nw-gyp command afterwards just in case there was some effect).

However when I try to use it, simply by starting with `var castro = require('castro');` in my project, I am getting the following error:

`Uncaught Error: dlopen(/Users/marc/Screen/App/node_modules/node-ffi/build/Release/ffi_bindings.node, 1): Symbol not found: _ffi_type_double
  Referenced from: /Users/marc/Screen/App/node_modules/node-ffi/build/Release/ffi_bindings.node
  Expected in: dynamic lookup`

Does anyone know why I'm having this problem? I am sure the issue is in how nw-gyp is failing when I specify 0.9.2 as my target?

I'd really appreciate some help - thanks very much guys,

**Comment by sarangsapre** [comment]
If this is not solved yet. This should help 

Change 'Set' to 'ForceSet' in ref module ...

**Comment by ghostoy** [comment]
I have a fix for supporting NW11 here https://github.com/ghostoy/node-ffi.
