### ISSUE TITLE
Parseable list of node-webkit releases

### ISSUE THREAD

**Issue by steffenmllr** [nwjs/nw.js#1821]
Hey Roger, 

it would be great if there was a list with alle the node-webkit versions which is parseable. The reason is I'm trying to make an option for https://github.com/mllrsohn/node-webkit-builder/ and https://github.com/mllrsohn/grunt-node-webkit-builder/ to use the latest version. For now I was parsing the aws xml - which isn't up to date anymore.

Are the git tags or the git releases representative for all the releases or is there a dir list for the dl.

Steffen

**Comment by rogerwang** [comment]
http://nwjs.io/versions.json
