### ISSUE TITLE
Emit and listen to custom events on Window

### ISSUE THREAD

**Issue by imjoshdean** [nwjs/nw.js#1846]
It would be really nice if there was a way to emit and listen to events that aren't just native events (e.g. close, loaded, focus, restore, etc.). I am working with a current example where I want to open a new window, have some JavaScript run (compile a template, add it to the page, etc) and then notify the parent window. I am currently getting around that by opening a window hidden (with show: false) and listening for when the window is focused. The newly opened window does it's JavaScript, then shows the window and focuses the window calling the function I set to run on focus. It works...but it's hella sloppy.

If there's something I missed that might make this easier, I'd love to know, but everything I've tried really hasn't given me anything that was worth while.

**Comment by jportoles** [comment]
As of 0.20.0:

> nw.Window.get().emit
_undefined_

Intended? How would one go about passing custom events to the Window object in that case?

**Comment by xland** [comment]
Reopen this issue

**Comment by omenus** [comment]
There is problem with CustomEvent in latest nw.js version 0.73.0 - issue valid,
If I use som libraries example uPlot or use in my code simple usage:
window.addEventListener("testevent", (e) => {
    console.log(e);
});

let ev = new CustomEvent("testevent", { bubbles: true, cancelable: false });
window.dispatchEvent(ev);

there is error: 
Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at index.js:9:8

There is no such issue in older version like 0.52.x but in 0.70.x there is was this event
