### ISSUE TITLE
show_in_taskbar partially broken on OSX

### ISSUE THREAD

**Issue by kethinov** [nwjs/nw.js#1848]
On OSX if you set `show_in_taskbar` to false in package.json, then later do something like this:

``` js
var gui = require('nw.gui'),
    mainWindow = gui.Window.open('main.html', {
      'show_in_taskbar': true
    });
```

It doesn't work. The window opens, but no dock entry is created.

I believe @imjoshdean observed a similar issue here https://github.com/rogerwang/node-webkit/issues/1762
##

**Comment by stalinb87** [comment]
I have exactly the same issue on mac, @tphalp how  do yo solved, there is a workaround ?
nwjs: 0.12.3

**Comment by tphalp** [comment]
@stalinb87 I honestly can't remember how I fixed this. I'm on 0.12.3, and am not having this issue any more. 

I looked at my code, and I am explicitly setting the `setShowInTaskbar` method to `false` once I open the secondary window (the one that I don't want to show in the task bar). I think that is how I overcame that issue.
