### ISSUE TITLE
webgl demo not working(webgl in general) in win7??

### ISSUE THREAD

**Issue by aremes** [nwjs/nw.js#185]
I've been trying to get node-webkit to show any support for webgl under win7, but i've failed terribly.
Both systems i've tried on (7 Home, and 7 Pro) support webgl using chrome(testing done using both get.webgl.org as well as a custom html that just tries to get the experimental-webgl context from a canvas node)

trying to run the webgl demo or the custom html file described above doesn't work in node-webkit.
specifically, it says webgl disabled

i installed all the latest graphics drivers on both systems. no change.

graphics hardware is intel HD 945gm and ati radeon mobility hd4330 none of which show up under chrome's unsupported devices list.

btw, i've tried all of this with 0.3.3 and 0.3.2. --> same result.

**Comment by meiyoulixiang** [comment]
win7下汉字不能正常显示，有的系统没有问题，有的系统存在问题，特别是32位的系统出现该情况的问题比较多一点，后经过再页面上将字体的字号写成18px以上，或者字体加上bold式样以后能正常显示，请问这该如何处理
