### ISSUE TITLE
Enabling touch-events in package.json?

### ISSUE THREAD

**Issue by mgcrea** [nwjs/nw.js#1854]
`"chromium-args" : "--enable-touch-events --enable-pinch"` does not work while it does work with latest Chromium (v34). Any idea why this is not working? I'm using the latest (v0.9.2) nw release.
##

**Comment by Sato-jsx** [comment]
Hello everyone. Unfortunately I have the same problem: 
nwjs' window not handle touch events of the touch screen. Just click event.

After reading all of the above and other articles in interenet I had write in the **package.json**
```javascript
...
"chromium-args" : "--touch-devices=10 --touch-events=enabled --enable-pinch"
```

Of course, I pre-determined number of touch device (according this article http://askubuntu.com/questions/471513/chrome-touchscreen-unity-14-04).

But nothing helps. Does not work in Linux, and in Windows 7 does not work ((
Any ideas, suggestions?

**Comment by Emnalyeriar** [comment]
Hey, I know this might be a bit old issiue but right now I am forced to use nwjs 0.9 for a touch app I'm currently working on. For me adding 
`--touch-events=enabled`
to package.json has worked but only when I added
`event.preventDefault();`
`return false;`
in my event callbacks. Hope this helps someone.

**Comment by nbriz** [comment]
i'm just running into this issue, i've posted details on stackoverflow >> http://stackoverflow.com/questions/33811587/touch-events-in-node-webkit-nw

**Comment by HC1988** [comment]
hello everyone,I got a problem,when I add:
"chromium-args": "--touch-events=disabled", to package.json ,and it work well that touch event can not work.but when my app is running , i want to switch the status and make touch event can work, how i do can make it ?@Mithgol

**Comment by Emnalyeriar** [comment]
Well, I guess you should not do it this way but rather operate on EventListeners. When you need touch support bind to touchstart event, then remove it and bind your functions to mousedown event.

**Comment by HC1988** [comment]
yes , you @Emnalyeriar are right. we went to map touch events to mouse events in our app. I just want to know   how change chromium-args when my app is running ,because the window's size of node-webkit can be changed ,so i think maybe ''--touch-events=disabled'' also do.

**Comment by HC1988** [comment]
and I have copyed something link to https://github.com/HC1988/JS/blob/master/touchTransMouse .
