### ISSUE TITLE
Cut/copy/paste right click context menu

### ISSUE THREAD

**Issue by frinkz** [nwjs/nw.js#1861]
Is there any reference implementation on how to do this? 

This is made harder for me by the fact that the entire app has an iframe with third party content that I cannot modify. I was able to set a context menu in a blank app, but it doesn't appear when I have the iframe take over the entire window.

(I use $(document).on("contextmenu", ..)

How can I make it do it's work in the iframe too?

**Comment by sktguha** [comment]
err why was  this issue closed ? I was actually in need of such a solution. I am facing a similiar problem as @frinkz

**Comment by mgroshevoy** [comment]
This is the solution I think.
1. Insert in package.json:
` "inject_js_end": "js/end.js",
  "node-remote": "<all_urls>"`
2. JS file for injection:
`    //get node webkit GUI
    var gui = require('nw.gui');

    // get the window object
    var win = gui.Window.get();

    var menu = new gui.Menu();
    menu.append(new gui.MenuItem({
        label: 'Line1'
    }));
    menu.append(new gui.MenuItem({
        type: 'separator'
    }));
    menu.append(new gui.MenuItem({
        label: 'Line2',
        click: function() {
            alert('Hi!')
        }
    }));

    document.body.addEventListener('contextmenu', function(ev) {
        ev.preventDefault();
        menu.popup(ev.x, ev.y);
        return false;
    });
`

**Comment by zuozonglin** [comment]
oh,just use inject_js_end in mainfest,and success

**Comment by Christywl** [comment]
@sktguha , does `inject_js_end` work in your case?

**Comment by Christywl** [comment]
close until there is more information
