### ISSUE TITLE
Symbol not found: __ZTVN2cv11_InputArrayE

### ISSUE THREAD

**Issue by mooglin** [nwjs/nw.js#1867]
I'm trying to use opencv with node-webkit. 
I have a node-webkit app running fine. 
I installed node-opencv, `npm install opencv`. 
I checked to make sure it works fine in a normal node environment, it did. 
I went to `/Users/moog/nw_cv/node_modules/opencv/` and ran `nw-gyp rebuild --target=0.7.5`
Everything seems to check out and build fine except when I require opencv from my node-webkit app I get this error.

```
[54956:0514/102937:INFO:CONSOLE(359)] "Uncaught Error: dlopen(/Users/moog/nw_cv/node_modules/opencv/build/Release/opencv.node, 1): Symbol not found: __ZTVN2cv11_InputArrayE
  Referenced from: /Users/moog/nw_cv/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup
", source: module.js (359)
```

Thanks for any insight. 
##

**Comment by PierBover** [comment]
Was anyone able to use OpenCV in NWJS?

**Comment by dasantonym** [comment]
i'm currently using opencv (2.4.9 hombrew install) in nwjs 0.12.0 on mac os 10.10.

never managed to compile with nw-gyp but it successfully builds with:
```
node-pre-gyp rebuild --runtime=node-webkit --target=0.12.0
```
