### ISSUE TITLE
Security risk: Javascript in iframe can call window.parent & access filesystem

### ISSUE THREAD

**Issue by Dshankar** [nwjs/nw.js#1873]
Load up a webpage inside an iframe inside a Node-webkit window.
Javascript in that webpage can access window.parent.

Implication: a malicious webpage could run window.parent.require('fs') and get full filesystem access.

I understand that the `nwdisable` attribute fixes this problem but shouldn't this be default behavior? Perhaps instead of `nwdisable`, an `nwenable` attribute would allow access to nodejs modules if the developer requires such functionality?

**Comment by sheley1998** [comment]
Hi Roger, is there a way to lift this window.parent restriction?
