### ISSUE TITLE
Application title

### ISSUE THREAD

**Issue by JokerQyou** [nwjs/nw.js#188]
When I use ./nw app.nw to run a application, there would be a default icon appear on the application bar of Ubuntu unity, but the title of this icon (the text appears when you hover over the icon) is just 'node-webkit', since the title of the application appears differently according to the package.json, I expect the title of the icon would also change according to the package.json. By the way, do you have a icon for node-webkit?

**Comment by haiw2** [comment]
> I guess that's because your right title is specified in HTML (`<title>`…`</title>`) only.
> 
> When the application starts (before it reads your HTML), the window's title is the `window.title` value from the `package.json`, or “node-webkit” if the title is not defined in that JSON. (See the “Window Sub Fields” section in the “[Manifest format](https://github.com/rogerwang/node-webkit/wiki/Manifest-format)” article in the wiki.)

Thanks your answer, it does work !!
