### ISSUE TITLE
Gamepad API not working

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#1932]
navigator.webkitGetGamepads() won't pick up any controller. It works in chrome it just won't work in node webkit

using nw 9.2

**Comment by starbug8866** [comment]
Hi Bigmacbook,

I am having the exact same issue and it is driving me crazy. Could you possibly share the code you are using to access the controller. Mine is as follows. Again, works in the Chrome browser using a standard xbox 360 controller and windows 8.1.

'''

			var gamepads = navigator.getGamepads();

			for (var i = 0; i < gamepads.length; ++i)
			{
	        		var pad = gamepads[i];
				console.log(pad); // pad is undefined using nw
'''

Thanks

**Comment by zachstronaut** [comment]
I'm also having a problem with xbox 360 gamepads (usb wired) and windows 8.1 ... they work fine in Chrome but not in node-webkit.  Calling navigator.getGamepads() shows nothing connected in nw.  @starbug8866 @Bigmacbook Either of you have an update on this?

**Comment by zachstronaut** [comment]
Ok, an update for all the other people who will arrive here via Google with this problem on Windows 8.1. You just need to install the Windows 7 driver for the xbox 360 controller. Here is the link for the WIRED controller:

https://www.microsoft.com/hardware/en-au/d/xbox-360-controller-for-windows

And for wireless:

https://www.microsoft.com/hardware/en-au/d/xbox-360-wireless-controller-for-windows

Hope this saves somebody the weekend of wasted work I just had.
