### ISSUE TITLE
Cannot find module 'nw.gui' from node-main file

### ISSUE THREAD

**Issue by michielbrinkers** [nwjs/nw.js#1937]
I've added a node-main to my package.json and I'm trying to require nw-gui, but I'm getting a "Cannot find module 'nw.gui'" error. I'm not doing anything else in the js file and the index.html is a basic hello world example. Is this correct behaviour? And if so is there a workaround?

**Comment by loretoparisi** [comment]
Uhm not sure, but it's happening to me using `window`.

```shell
  var gui = window.require('nw.gui');
            ^
ReferenceError: window is not defined
```

My package.json looks like

```json
"main": "index.html",
"node-main": "app.js",
"node-remote" : "*://index.html",
```

NWJS is `nwjs-macappstore-v0.12.3-osx-x64`.

**Comment by codekraft-studio** [comment]
same with me: 
```bash
var gui = window.require('nw.gui');
          ^
ReferenceError: window is not defined
```

and package.json
```javascript 
...
"node-main": "./app.js",
"main": "http://localhost:3000",
...
```
