### ISSUE TITLE
min-height and min-width do not resize window when first opened

### ISSUE THREAD

**Issue by ChadKeating** [nwjs/nw.js#1959]
```javascript
{
  "name": "myApp",
  "main": "defaultBrowser.html",
  "window":{
    "toolbar":true,
	"icon":"package.png",
    "fullscreen":false,
	"frame":true,
	"min_width":1024,
	"min_height":768
  },
  "dom_storage_quota":40,
  "chromium-args":"--disable-device-orientation"
}
```
This is package.json used. Not sure if this is a bug, but just in case. 
When the app is first opened the window is very small 600x400.
This is resolved just by adding the "width" and "height" to the json file. 
I feel as if this should not be required though after specifying a minimum?

**Comment by Ha990143** [comment]
idont know
