### ISSUE TITLE
console.log from node modules

### ISSUE THREAD

**Issue by AlgoTrader** [nwjs/nw.js#196]
I see the strange behavior. If module installed in node_modules contains console.log, my app "hangs" , gray screen is shown and debugger go unresponsive. console.log in webkit side works just fine.

After removing console.log from node libs app returns to work. What may cause hang while printing console.log from node.js side?

**Comment by karlrwjohnson** [comment]
I think that @nathansobo's issue from Nov 26, 2012 has reappeared: I find myself unable to log to either DevTools or the command line on linux using the v0.13.0alpha6 build.

index.html:
```
<!DOCTYPE html>
<html>
<head></head>
<body>test</body>
<script>
    'use strict';
    nw.Window.get().showDevTools();
    var testmodule = nw.require('./testmodule');
    console.log(console);
    console.log(testmodule.console);
    console.log(console === testmodule.console);
</script>
</html>
```

testmodule.js:
```
'use strict';
console.log('hello from testmodule'); // prints nothing
module.exports.console = console;
```

```
user@hostname /path/to/nw$ .
[1208/012935:INFO:nw_package.cc(175)] /path/to/nw .
```

Meanwhile, the DevTools renders something like this:
```
▶ Console                                                            index.htm:9
▶ Console                                                           index.htm:10
false                                                               index.htm:11
```

So obviously, a required module has a reference to *some* console object. However, it is clearly not the same one the page is getting.

**Comment by karlrwjohnson** [comment]
I found a workaround for my own issue. Although required modules don't get the same console as the window script, they all get *the same* console. This means one can set it once, in one file, without modifying every file.

Put the following code into a file and call it, say, consoleHack.js:
```
'use strict';
module.exports = function consoleHack (newConsole) {
  console = newConsole;
};
```

Then, from index.html or wherever, do this before any other modules are required:
```
nw.require('./consoleHack')(console);
```

Voila.

**Comment by jeffzemla** [comment]
I am having the same issue (on mac os). The workaround suggested by @karlrwjohnson works. The current behavior is very confusing and not intuitive.
