### ISSUE TITLE
<img> tag fails to load images

### ISSUE THREAD

**Issue by kethinov** [nwjs/nw.js#1961]
None of these various attempts at loading the image work:

```html
<p class='icon'><img src='img/icon.png' width='62' height='52'></p>
<p class='icon'><img src='/img/icon.png' width='62' height='52'></p>
<p class='icon'><img src='./img/icon.png' width='62' height='52'></p>
<p class='icon'><img src='app://img/icon.png' width='62' height='52'></p>
<p class='icon'><img src='app:///img/icon.png' width='62' height='52'></p>
<p class='icon'><img src='app://./img/icon.png' width='62' height='52'></p>
```

Sourcing `img/icon.png` from CSS works.

And stuff like this in the same file is working:

```html
<script src='bower_components/page/index.js'></script>
<script src='bower_components/teddy/teddy.js'></script>
<script src='main.js'></script>
```

This is on OSX 10.10 Yosemite using node-webkit-v0.9.2-osx-ia32.

**Comment by kethinov** [comment]
This appears to be an artifact of using [page.js](https://visionmedia.github.io/page.js/) in NW.js.

Because NW.js uses `file:///` protocol it messes up page.js for some reason.

However I was able to deploy an effective workaround by using [app protocol](https://github.com/nwjs/nw.js/wiki/App%20protocol).

Once I reset my `main` to use something like the `whatever` example, relative paths worked again.

**Comment by clintwood** [comment]
Aaaah... great thanks!

**Comment by lxhao** [comment]
hello! could you teach me how to show image in nw.js page in terms of local path.
