### ISSUE TITLE
Memory issue with gui.Window.get()

### ISSUE THREAD

**Issue by raviraj555** [nwjs/nw.js#1968]
In page I have iframe, after loading iframe application memory goes from 30mb to 80mb.
if i use  following code anywhere in page Memory never comes down after removing iframe

```
var gui = require('nw.gui');
var win = gui.Window.get();
```

if above code is removed memory goes down to 30mb after removing iframe from page as expected 
is there any fix for this issue to reduce memory?
please help 
##

**Comment by NicolasKovalsky** [comment]
Hi kamesh, 
I'm facing the same issue. Could you share with me your solution?
Thanks!
