### ISSUE TITLE
alert() and confirm() do not show when 'frame' was set false in package.json

### ISSUE THREAD

**Issue by daguike** [nwjs/nw.js#1970]
When alert and confirm do not show, nw will block and app will do not respond any action!
So, i should not use alert() and confirm() when frame was set false? 
ps:
version: 0.9.2
platform: win xp

package.json:
"window": {
    frame : true
}
alert shows
![360-39042656](https://cloud.githubusercontent.com/assets/7608246/3313583/9ec0e076-f6e5-11e3-9d78-08b3c270fcb3.jpg)
package.json:
"window": {
    frame : false
}
alert does not show
![360-39070593](https://cloud.githubusercontent.com/assets/7608246/3313618/0402cc92-f6e6-11e3-8820-6bdf108e4582.jpg)
##

**Comment by aknife** [comment]
when I use node-main:hello.js ,
"window.alert" it doesn't work, too.
