### ISSUE TITLE
Windows Version of app doesn't use CSS / JS correctly? (frame: false)

### ISSUE THREAD

**Issue by thewatts** [nwjs/nw.js#1982]
First off - this works like a champ on Mac OSX.

Second, this only happens when I set the package settings to `frame: false`.

When I build the `app.exe` file from the `app.nw` and the `nw.exe` - it opens the app up and it's as if the js isn't being loaded at all.

Also - it's as if the Windows version isn't using Chromium - it doesn't recognize animations?
( and simple CSS that works fine in a normal chrome browser on windows breaks in the node-webkit app )

As a side note, this software is totally legit. I am loving the simplicity of things. So all in all - great work!
##

**Comment by rogerwang** [comment]
close until more information is available.
