### ISSUE TITLE
Desktop keyboard shortcuts support [$160 awarded]

### ISSUE THREAD

**Issue by asbrodov** [nwjs/nw.js#200]
I'd like to use node-webkit to create an application that's run in background and can be opened by keyboard shortcut. According to  <a href='https://github.com/rogerwang/node-webkit/wiki/Native-UI-API-Manual'>this documentation</a> it's impossible to listen desktop keyboard shortcut in current version.

This is feature that I realy need. Thanks.
##

**Comment by steelskysoftware** [comment]
I wrote a workaround for reassigning the winkeys using an AutoHotKey script as a child process:
https://github.com/steelskysoftware/nwjs-winkey-ahk

Might be useful for until winkeys are supported.
