### ISSUE TITLE
start express server in a new process

### ISSUE THREAD

**Issue by JohnnyFee** [nwjs/nw.js#2014]
I'll integrate a http server(express) and a http client together. Because of some reason, I should use synchronous ajax request in the http client. But when I do a synchronous request, the node webkit was hanged up and has no any response.

I know this is because the node and dom are in the same process and use the same message loop. So I want start the express in a new process, but some questions can't be solved. The main code:

The scaffold of my app is generated by [expressjs/generator](https://github.com/expressjs/generator).

**bin/www:**

``` javascript
#!/usr/bin/env node
var debug = require('debug')('sample');
var app = require('../app');

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});
```

The app is used to initialize the express instance:

``` javascript
var express = require('express');
var app = express();
app.set('views', path.join(__dirname, 'views'));
...
module.exports = app;
```

**bin/janus:**

I expect it will fork a child process to start process.

``` javascript
#!/usr/bin/env node
console.log('main process pid=' + process.pid);

var cp = require('child_process');

// spawn
var www = cp.spawn('node', ['./www']);
console.log('cpid=' + www.pid);

// and i tried exec and fork method, the result is the same
```

**public/javascripts/index.js**

``` javascript
var bindEvent = function(){
    // 同步请求
    $('#btnAjax').on('click', function(){
        $.ajax({
            url: '/users',
            type: 'POST',
            async: false,
            data: { params: {name: 'feiq'} },
            success: function (result) {
                console.log(result);
            },
            fail: function (result) {
                console.log(result);
            }
        });
    });
};

$(function(){
    bindEvent();
});
```

There is a button in `index.html` with id `#btnAjax`. Please notice that the `async` property in ajax is set to `false`, so the request will be synchronous.

**package.js:**

``` json
"name": "express4",
"version": "0.0.1",
"private": true,
"node-main": "./bin/www",
"main": "http://localhost:3000",
"dependencies": {
    "express": "~4.2.0",
    "static-favicon": "~1.0.0",
    "morgan": "~1.0.0",
    "cookie-parser": "~1.0.1",
    "body-parser": "~1.0.0",
    "debug": "~0.7.4",
    "jade": "~1.3.0"
  }
```

When the `node-main` is set to `./bin/www`, the express server can start normally, and the `main` url is redirected rightly. but when the button in `index.html` is clicked, the app begins frozen.

When the `node-main` is set to `./bin/janus` to start express in a new process. The server seemly not starts, because the `http://localhost:3000` opened in nw.exe is empty, and I tried to open the url in Chrome, the address can't be found.

But, I debug it in webstorm, the process ids of main process and child process is diffirent, and the server starts normlly. 

So any idea? Thankds in advance.

**Comment by sergzak022** [comment]
I have the same problem with version 0.12.3.
