### ISSUE TITLE
Issue with Cut,Copy,Paste Shortcuts

### ISSUE THREAD

**Issue by quasado** [nwjs/nw.js#2039]
hi,

We'd like to use the native shortcuts for copy,cut,paste,select all etc. form the browser for any input field or contenteditable fields. However, for any other case we'd need to handle the commands ourself. How can this be done?

thanks
##

**Comment by donaldpipowitch** [comment]
Hi @rogerwang,

could you please either close this issue (#2039) or issue https://github.com/nwjs/nw.js/issues/1955? They seem to be duplicates.
What are you plans for solving this or do you think this is already solved by either `Menu.createMacBuiltin` or https://github.com/nwjs/nw.js/issues/1958#issuecomment-48096087?
It would be nice to be more flexible here and to be more platform independent. There is some weird behavior here: I can't create a MenuItem called "Edit" with a SubMenuItem "Select All ⌘A" myself which triggers a correct "Select All" functionality, but I can call `Menu.createMacBuiltin` and rename the labels afterwards (with this little workaround https://github.com/nwjs/nw.js/issues/2988). Can't nw.js call `Menu.createMacBuiltin` implicitly internally, if someone creates a "Edit" menu? Or can't we pass a flag to the MenuItem options like 

````
new gui.MenuItem({
  label: 'Edit', // so this can be translated easily
  macBuiltin: 'Edit'  // will be ignored on Linux and Windows, very easy
})
````

**Comment by rogerwang** [comment]
Hi @donaldpipowitch , `createMacBuiltin` is a formal API so I think it resolve the issue here. OSX handles menu a little bit differently so it needs a special API. I'll see #2988 and the issue in your comment, which should be fixed.

**Comment by donaldpipowitch** [comment]
Thank you for the response!

**Comment by donaldpipowitch** [comment]
> createMacBuiltin is a formal API so I think it resolve the issue here.

So should this issue (#2039) be closed, too? Else it would possibly create confusion that there will be ongoing work at this topic.

**Comment by AngelFraga** [comment]
I've got  paste in another app from nodewebkit men !!

http://stackoverflow.com/questions/37447911/how-execute-a-combination-key-on-node-webkit-like-c-sharp-sendkeys
