### ISSUE TITLE
Speech recognition standard

### ISSUE THREAD

**Issue by andreprates** [nwjs/nw.js#2051]
Please suport the Speech recognition standard

**Comment by JaredCubilla** [comment]
+1

**Comment by jhermsmeier** [comment]
@rogerwang What's the status on this? I tested it today with the `0.12-alpha1`, but still no funktionality.

**Comment by rogerwang** [comment]
merged with #1115. I updated that issue with some update.

**Comment by soutom-genpact** [comment]
is it solved in new version already ?
