### ISSUE TITLE
creating snapshot of a javascript file

### ISSUE THREAD

**Issue by GayatriN** [nwjs/nw.js#2056]
Hello everyone,

I would like to create a binary for javascript file, say "snapshot.bin" using the nwsnapshot.exe available in node-webkit,

When I did the same for a simple js file with one function which does a basic calculation and updates the html page, it worked fine.

But, when I tried to create snapshot of a js file which is using node-java module in it, it fails. I tried the same with nwsnapshot.exe of node-webkit versions 0.9.2 and 0.8.5.

Isn't it possible to create a binary for the javascript file which uses node-java module?

Appreciate any help in this regard.

Thanks,
Gayatri
##

**Comment by rogerwang** [comment]
there is a new tool for this feature in 0.12.0-rc1, which removes the size and closure limitation and fixes crashes. please try it: https://groups.google.com/d/msg/nwjs-general/Sykci3Qhgus/AoF0zT7TEIoJ
