### ISSUE TITLE
When plan to support the PNaCl

### ISSUE THREAD

**Issue by jie1985** [nwjs/nw.js#2061]
When plan to support the PNaCl? 0.10.0 release or later? Thank you.
##

**Comment by cytrowski** [comment]
+1 for this one. I can make a fork to implement this but I need some guidance and hints. Did you guys have a look at this recently? How much work would it take to implement this stuff?

**Comment by francoislaberge** [comment]
This would rock, being able to mix javascript, dom based UI, with portable native performant content would be an awesome foundation for a portable decently highend game engine

**Comment by rogerwang** [comment]
We'll see this in nw13. Thanks.

**Comment by francoislaberge** [comment]
:+1:

**Comment by cytrowski** [comment]
Do you have any "guesstimation" when the nw13 will be released?

**Comment by csantosbh** [comment]
I asked this on gitter, but just for the records, I'll ask it here as well: Wouldn't it be possible to achieve the same with native node modules (and maybe some hacking)? I'm particularly interested in messing with the webgl canvas from my C++ module, though I have no idea how feasible that would be.

**Comment by rogerwang** [comment]
close as it's supported.
