### ISSUE TITLE
[Windows] Window can't get bigger than screen resolution

### ISSUE THREAD

**Issue by FWeinb** [nwjs/nw.js#2071]
On OS X and Linux it is possible to create a headless window (using `show : false`) to create a browser that is bigger than the current screen resolution. This isn't working on Windows. There all windows are resized down to fit in the viewport.

**Comment by nitriques** [comment]
Nobody found a fix to this yet ?

**Comment by nitriques** [comment]
This may help ? https://msdn.microsoft.com/en-us/library/windows/desktop/ms632626(v=vs.85).aspx ?

**Comment by nitriques** [comment]
Wow great to see someone assign to the issue.

I fiddle around the code but since I am a complete gtk n00b, I did not knew what to look for...

I am willing to test any patch tho...
