### ISSUE TITLE
Node-Webkit not working with moment.js

### ISSUE THREAD

**Issue by jbescoyez** [nwjs/nw.js#2075]
This bug is super easy to reproduce:
`package.json`

```
{
  "name": "nw-demo",
  "main": "index.html"
}
```

`index.html`

```
<html>
<head>
<title>Hello World!</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js"></script>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>
```

Launch nw (tested with 0.9.2 an 0.10.0). Open console. 

```
$ moment
=> ReferenceError: moment is not defined
```

Launch browser, open index.html

```
$ moment
=> function (b,d,e,f){var g;return"boolean"==typeof e&&(f=e,e=a),g={},g._isAMomentObject=!0,g._i=b,g._f=d,g._l=e,g._strict=f,g._isUTC=!1,g._pf=c(),db(g)}
```

No idea why `moment` is not defined in node-webkit since it is in other browsers.

Cheers

**Comment by boiawang** [comment]
moment = global.moment

**Comment by cybercoder** [comment]
I'm using electron to create a desktop app with angular, There's no problem when i use gulp-webserver in develop time, but when i need to test in electron prebuilt environment then i see this error. I can fix in electron env with using require npm package but how can fix in both?
