### ISSUE TITLE
Debugging in Sublime Text 2/3 Linux/Ubuntu

### ISSUE THREAD

**Issue by KeizerDev** [nwjs/nw.js#2076]
It seems there isn't a method for debugging in linux/ubuntu on sublimet text..?

Wiki: https://github.com/rogerwang/node-webkit/wiki/Debugging-with-Sublime-Text-2-and-3

**Comment by ericx19** [comment]
You could build your own Build method for your nodewebkit project on Linux, here's my build script for Sublime Text 3:

https://gist.github.com/ericx19/9341848
