### ISSUE TITLE
Is there any way to access Windows registry to set application to start with OS?

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#2078]
Is there any way to access Windows registry to set application to start with OS? I find this Issue https://github.com/rogerwang/node-webkit/issues/1000. but the node-windows is doesn't work and it's last updated time is 2 years ago.
(sorry, my english is poor!)

**Comment by ell1e** [comment]
Is there a way to do this without running commands with parameters that involve path/value arguments that might need complicated escaping? This seems like a really risky and unclean way to do it.
