### ISSUE TITLE
v0.10.0-rc1 localStorage unavailable

### ISSUE THREAD

**Issue by dmpost** [nwjs/nw.js#2087]
I save a data in my app using windows events,
but for some reason in the new version localStorage == null

win.on('close', function() {
   console.log("localStorage ", localStorage); // null
});

I've tried another events

win.on('move', function() {
   console.log("localStorage ", localStorage); //  null again
});

**Comment by TatriX** [comment]
I have the same problem in 19.4
`Error in event handler for nw.Window.onClose: TypeError: Cannot read property 'localStorage' of null`
in
`window.localStorage.setItem(...);`

I can reproduce it easily in my app, but cannot make a simple test with the same results.

**Comment by TatriX** [comment]
Press reload, then quit. (in the real app I have a win.close(true) in the handler, but have the same error.
```js
<button id="reload">reload</button>
<button id="quit">quit</button>
<script>
 var gui = require("nw.gui");
 var win = gui.Window.get();
 win.on("close", () => {
     save();
 });

 document.getElementById("reload").onclick = () => {
     document.location.reload();
 }
 document.getElementById("quit").onclick = () => {
     require("nw.gui").App.closeAllWindows();
 }

 function save() {
     localStorage.setItem("test", 1);
 }
</script>
```
