### ISSUE TITLE
Saves file without extension if "Hide extension" is checked

### ISSUE THREAD

**Issue by csugden** [nwjs/nw.js#2108]
Saving a file using the file dialog, with "Hide extension" checked, resulted in a file being saved that had no file extension at all. Standard OS X behaviour (when hiding extensions) is for the file to show up in folder views as having no extension after its name, but for it to still have a file extension (visible in Get Info and often in its icon).
##

**Comment by matthew-dean** [comment]
Ah, I see this is a known issue. However, I would tweak this a bit: even if you DON'T have "Hide extension" checked, if you click on a previously existing file, for me, it output a file without an extension in the Save As textbox, which is exactly how I saved.

More bizarrely, as I kept testing, I was able to replicate that behavior a number of times. However, once I had checked and then un-checked "Hide Extension" (or saved once or twice, not sure what triggered it), I was never able to replicate it again.

**Comment by conceptualspace** [comment]
occurs on windows as well, the dialog shows the file type as "all files"

**Comment by conceptualspace** [comment]
adding an "accept" attribute for the extension worked for us, ie,

<input type="file" nwsaveas accept=".zip">

tested against nw 11 on win 7x64 and osx 10.11.2

**Comment by bra1n** [comment]
Tested `accept=".txt"` as proposed by @conceptualspace and confirmed it works with the OSX 32bit build. Instead of preselecting "hide extension", it now shows the extension by default (and unselects "hide extension") Meaning, this problem can be fixed in the documentation. :)

**Comment by fritx** [comment]
I had been using this following hack until I saw this issue :sob: 

```js
if (!extname(savepath)) { // fix mac extension
  savepath += extname(savename)
}
```
