### ISSUE TITLE
Can't get serialport to work

### ISSUE THREAD

**Issue by wbw20** [nwjs/nw.js#2129]
I am trying to use serialport, a node-gyp package, in a node-webkit application, but no matter what I do I get the same error:

> Uncaught Error: Module did not self-register.

I have tried old and new versions of node-webkit, and I have tried different versions of serialport.  Nothing works.  I am building serialport with:

``` code
  node-pre-gyp rebuild --runtime=node-webkit --target=0.9.1 --target_arch=ia32
```

I have no problems requiring other 3rd party packages, like async.  It is just this gyp package that is giving me trouble.  Thanks.

I am on 64 bit osx Mavericks

**Comment by RIAEvangelist** [comment]
I couldn't get any of the suggested fixes to work from the multitude of threads with this issue.

So I am starting a pure JS serialport implementation called serialport-js it uses nodes built in tty which I found out is getting sucked up by the nwjs console. So I implemented a proxy to the users local version of node via a spawn command. The users local version of node then runs a node thread with serialport-js that proxies info back to the node-webkit app. both syntax are exactly the same. The only difference is that one uses require('serialport-js') and the proxy uses require('serialport-js').node()

seems like a decent way to do it for apps you plan to deploy so the user does not need to have compile tools on their system. Just node.

right now its just linux, but its only been a few days. hopefully soon I'll get it going on mac and win so everyone can enjoy.

super alpha so feedback would be appreciated.

https://github.com/RIAEvangelist/serialport-js
