### ISSUE TITLE
crash when show desktop notification

### ISSUE THREAD

**Issue by fzx** [nwjs/nw.js#2147]
node-webkit v 0.10.1 crashed when running http://jsfiddle.net/yoshi6jp/Umc9A/ to show notification (I am using Windows 7 32 bit).

**Comment by MarxGames** [comment]
Crashes on Windows 7 32-bit. I have a sound effect after the "new Notification" in code which is being played so the crash is not instant.
Confirmed working on Ubuntu 14.04, Mac 10.10, Windows 8.1 64-bit.

**Comment by jakehh** [comment]
@jtg-gg Is this to do with Windows 7 not having a notifications system like Windows 8?

**Comment by jtg-gg** [comment]
@MarxGames what version you are using? @jakehh earlier version of NW11 known to have this problem, but I've fixed it on the latest version 0.11.5

**Comment by MarxGames** [comment]
@jtg-gg I'm using 0.11.5 and if it matters then I'm not compiling it myself but rather using https://github.com/jyapayne/Web2Executable
