### ISSUE TITLE
-webkit-font-smoothing is not working?

### ISSUE THREAD

**Issue by b1rdex** [nwjs/nw.js#2159]
Here is demo page http://maxvoltar.com/sandbox/fontsmoothing/
And here is description with screenshots http://maxvoltar.com/archive/-webkit-font-smoothing

Dev tools has completion for this css property and shows it as good property. But any values has no effect.

**Comment by marbemac** [comment]
@theolampert Was the font rendering updated in the end? We're past Chrome 37 and I'm still seeing blurry fonts in Windows.
