### ISSUE TITLE
speechSynthesis

### ISSUE THREAD

**Issue by jkramp** [nwjs/nw.js#2165]
It seems as though the HTML 5 option of speechSynthesis is showing on the Window object but is not working. No error is thrown. Should this be working?

var u = new SpeechSynthesisUtterance('This is a test');
speechSynthesis.speak(u);

This is likely related to this 
https://github.com/rogerwang/node-webkit/issues/1661
##

**Comment by tatosgames** [comment]
Same here, I need SpeechSynth on nw.js for blind accessibility :+1:

**Comment by helloncanella** [comment]
same problem. window.speechSynthesis.getVoices always return empty array. To be released I just need this function in my app.
