### ISSUE TITLE
MediaSource screen capture

### ISSUE THREAD

**Issue by Shadowfaxenator** [nwjs/nw.js#2169]
How is it possible to implement this using node-webkit? I also enabled `"chromium-args": "--enable-usermedia-screen-capturing"` but this doesn't help

``` javascript
navigator.webkitGetUserMedia({audio: false, video: {
      mandatory: {
                          webkitMediaSource: 'screen',
                          maxWidth: 1280,
                          maxHeight: 720
                      },
                      optional: []

    }},
      function(stream) {
     document.getElementById('camFeed').src = webkitURL.createObjectURL(stream);
      },
      function() {
        //Error, no stream provided
        alert("Error");
      }
  );
```

**Comment by gabrielstuff** [comment]
Hey there, it did perfectly works in 0.9.0 up to 0.9.2
For 0.10.0 it brakes

```
name:trackstarterror
```

and up to 0.11.5 i'm not able to run and capture

**Comment by kaosdynamics** [comment]
Same here!
Just like in #2706, but - in my case - I only need audio.

`navigatorUserMediaError {constraintName: "", message: "", name: "DevicesNotFoundError"}`
