### ISSUE TITLE
Snapshot - Protecting multiple Javascript files

### ISSUE THREAD

**Issue by alexandervrs** [nwjs/nw.js#2179]
In my application I do use multiple javascript files and have broken up my app into modules pretty much. From what I see though, node-webkit snapshot tool does not support protecting multiple files.

It would be very useful if we could pass a folder instead like,
nwsnapshot --extra_code "javascripts/" mytest.bin

And then node-webkit would load all the javascript files inside the relative "javascripts" folder.

There is one concern though, about in what order the files would load.
Node-webkit could use a directive in a comment,

For example a file which has the line:

// [node-webkit-order=3]

would be loaded third compared to the other js files.

Since nwsnapshot has a limit for a single JS file, this would help as the files could be saved like
mytest1.bin
mytest2.bin
mytest3.bin
mytest4.bin
etc.

Some ideas. Thanks :)

**Comment by rogerwang** [comment]
there is a new tool for this feature in 0.12.0-rc1, which support this request and removes the size limitation and fixes crashes. please try it: https://groups.google.com/d/msg/nwjs-general/Sykci3Qhgus/AoF0zT7TEIoJ
