### ISSUE TITLE
Document the new Notifications API

### ISSUE THREAD

**Issue by zenorocha** [nwjs/nw.js#2184]
I couldn't find any official resource that explains the Notifications API. We should probably create a wiki page for that since it's available since the latest version (0.10.1)

**Comment by Zarel** [comment]
It's just the HTML5 Notification API, but without a need for the permission system, right? Is there any other way that it differs from the official spec?

**Comment by jtg-gg** [comment]
the Document is here https://github.com/nwjs/nw.js/wiki/Notification
