### ISSUE TITLE
How to disable drag and drop?

### ISSUE THREAD

**Issue by allencblee** [nwjs/nw.js#219]
I've written an application with node-webkit.   But when I drag a html file into the canvas, the html is displayed replacing my app.  Is there any way to prevent this?

**Comment by stephan-nordnes-eriksen** [comment]
I am having trouble with this still.. I did, I believe, was is described in [drag files into page](https://github.com/nwjs/nw.js/wiki/Dragging-files-into-page). Is this a bug, or am I failing at writing `window.ondragover = function(e) { e.preventDefault(); return false };
window.ondrop = function(e) { e.preventDefault(); return false };` at the top of my script?

**Comment by stephan-nordnes-eriksen** [comment]
Yeah.. It was me messing it up

**Comment by danschumann** [comment]
This is behaving RANDOMLY.  Sometimes 1st, 2nd, 3rd, but eventually I will drag a file and it will not catch the event.  Then my app is basically busted because its on another url and can't go back..

**Comment by rellame** [comment]
I am haveing the same trouble with you @felixSchl, did you fixed it?

**Comment by sayaniHalderMphasis** [comment]
you can try adding 
[ondragstart="return false;" ondrop="return false;"](url)
 in the html tag to disable the drag & drop
