### ISSUE TITLE
Global Hotkeys don't work if another app is fullscreen (mac OS & Windows)

### ISSUE THREAD

**Issue by tstefanich** [nwjs/nw.js#2209]
I'm not sure if this is a bug or not or a limitation. But On Mac, if you launch another .app with a node-webkit project that goes into full screen. Global hotkeys stop working..... but works if it launches an .app that is windowed. 
##

**Comment by Zazama** [comment]
I still have this problem, I'm trying to make a music player but as soon as a game or something else starts in full screen, the media keys stop working. Any ideas?

**Comment by tstefanich** [comment]
Me too..... not sure if its been looked at or not.
