### ISSUE TITLE
Double-clicking on {-webkit-app-region: drag} area doesn't make frameless window maximize

### ISSUE THREAD

**Issue by asinverse** [nwjs/nw.js#2210]
I've tried with Node Webkit v0.10.2 on Windows 7 x64. Thanks for your work. :) 
But when I double-click on the area set {-webkit-app-region: drag}, it doesn't make my frameless window maximize. It works normally with Node Webkit v0.9.2.

**Comment by adam-lynch** [comment]
This still doesn't work in 0.11.5. Ugh.
