### ISSUE TITLE
ffmpegsumo file for NW 0.10.2 win/mac anyone?

### ISSUE THREAD

**Issue by weblancaster** [nwjs/nw.js#2216]
I upgraded my www.soundnodeapp.com (which need mp3 codec/library) from NW 0.9.2 to 0.10.2 but I can't find the right fmpegsumo librarry Mac/Win I tried the latest and Prev ffmpegsumo version from Google Chrome and Google Canary.

Anyone has the ffmpegsumo.so and ffmpegsumo.dll for NW 0.10.2?

**Comment by darxides** [comment]
ffmpegsumo.dll for NW 0.10.2 64-bit
https://www.dropbox.com/s/qb58w1p06pbith8/ffmpegsumo.dll?dl=0
Just upgraded my project, works fine.

**Comment by Qqwy** [comment]
@darxides: Finally a version that worked. Thank you very much! ^^

**Comment by weblancaster** [comment]
what about for Mac @darxides ?

**Comment by FlorianBELLAZOUZ** [comment]
@darxides thank you so much ! =)

**Comment by hems** [comment]
For some reason all the versions i tried simply crash node-webkit when i try to play a file, even a WAV file, i'm running the 32 bits version and got the .so file from: 36.0.1985.125, it says

````
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
````

which is funny, because i'm on OSX and don't even need/use jack... seems like a linux message error :(

**Comment by ghostoy** [comment]
See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for latest instructions for NW.js 0.13.0 or later.

**Comment by hems** [comment]
@ghostoy the problem is people with finished projects done in previous versions can't seamless update to new ones. i tried the new version with my project and i got assorted errors, unfortunately my deadline didn't allow me to dive deeper.

**Comment by ghostoy** [comment]
@hems Yeah, I understand. Currently bug fixes will only be done on latest LTS and stable versions just like Chromium and Node. And issues for old versions will be closed. So we encourage you can move your app to the latest version to experience the up-to-date features and avoid security vulnerabilities.
