### ISSUE TITLE
Native OS theme/layout (Windows, QT, GTK3, ...)

### ISSUE THREAD

**Issue by skerit** [nwjs/nw.js#2227]
I was wondering if anyone has needed their node-webkit application to blend in with the theme settings of the operating systems, and how they did it.

I realize being able to use HTML & CSS gives you great flexibility in designing the UI,
and that that is actually a selling point of of node-webkit, but it would be nice to create something that doesn't stick out as much.

Any suggestions are welcome. Just getting the basic colour palette would help :)
##

**Comment by Gimmeaphatbeat** [comment]
Doesn't work with Gnome dark theme (tested on Fedora 23).

For example "color: Window" appears as white.
