### ISSUE TITLE
Chromedriver with Karma [$100 awarded]

### ISSUE THREAD

**Issue by mikemilano** [nwjs/nw.js#2229]
Should I be able to use `chromedriver2_server` to test node-webkit apps with Karma or Protractor?

I'm building a front-end with AngularJS and access node modules directly in the app. I've downloaded the `chromedriver2_server` binary and directed karma & protractor to use it, but it just errors out saying that it can't locate the Chrome binary.

I suspect I'm going about it the wrong way though. If it's might be possible to run the recommended AngularJS testing frameworks (karma & protractor) in a node webkit instance, please let me know.
##

**Comment by marnen** [comment]
I'm still getting "cannot find Chrome binary" errors on Mac OS X 10.10 with Protractor. I've tried linking `support/nw` and `support/nodewebkit` to `node_modules/.bin/nw` and `node_modules/nw/bin/nw`, and `support/node-webkit.app` and `support/nwjs.app` to `node_modules/nw/nwjs/nwjs.app`, and so on. Nothing works with Protractor, although I've been able to get Karma to launch nw through Chromedriver by pointing it to `./node_modules/.bin/nw`. Help?

**Comment by marnen** [comment]
Ah...looks like the name of the Mac app didn't get changed from `node-webkit.app` to `nwjs.app`: https://github.com/nwjs/chromium.src/blob/nw12/chrome/test/chromedriver/chrome/chrome_finder.cc#L91

**Comment by marnen** [comment]
Got it! You can specify the Chrome binary in `protractor.conf.js`:

```js
'use strict';

exports.config = {
  chromeDriver: './support/chromedriver', // relative path to node-webkit's chromedriver
  chromeOnly: true, // starting Selenium server isn't required in our case
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      binary: process.env.PWD + '/support/nwjs.app/Contents/MacOS/nwjs'
    }
  },
  specs: ['test/e2e/**/*.js'],
  baseUrl: 'file://' + process.env.PWD + '/build/',
  rootElement: 'html', // specify a correct element where you bootstrap your AngularJS app, 'body' by default

  onPrepare: function() {

      // By default, Protractor use data:text/html,<html></html> as resetUrl, but
      // location.replace (see http://git.io/tvdSIQ) from the data: to the file: protocol is not allowed
      // (we'll get ‘not allowed local resource’ error), so we replace resetUrl with one
      // with the file: protocol (this particular one will open system's root folder)
      browser.resetUrl = 'file://';

      // This isn't required and used to avoid ‘Cannot extract package’ error showed
      // before Protractor have redirected node-webkit to resetUrl.
      browser.driver.get('file://');
  }
};
```

**Comment by marnen** [comment]
This should probably go in the wiki. I'll write something up if folks want it.

**Comment by brian-mann** [comment]
How are you guys dealing with logic that goes through `require("nw.gui").App.manifest` ?  Unless I'm mistaken, all of the examples show protractor connecting to an external server.  But usually when you launch your NW app it's through `nw` directly, which looks for your `package.json`, among other things.  

When I run my tests, I'll get `Unexpected end of input` invoking App.manifest because naturally NW hasn't processed `package.json`.  Am I missing something?

**Comment by marnen** [comment]
@brian-mann If I understand you correctly, you're missing the use of the special NW version of Chromedriver.

**Comment by bhalajin** [comment]
I am facing the same issues reported by @samuelcastro (commented on Oct 22, 2014). What is the solution for the above issue?

Driver info: chromedriver=2.13, platform=Windows NT 6.1 SP1 x86_64

**Comment by anjanapaulose** [comment]
@brian-mann, where you able to solve the issue you faced? I am also not able to run protractor if I use require for nw or other node modules. I am using chrome driver for nw.

**Comment by anjanapaulose** [comment]
Actually, other node modules like fs, and my custom module which has methods to be invoked are working. When I try, var nw = require("nw.gui"), its also returns, The issue if I access  nw.App or anything, the result is a json object which has only  strings , the inner contents are not json objects anymore. eg: I get nw.App , but not nw.App.manifest.

**Comment by reynoldsalec** [comment]
Note to anyone who is trying to run Protractor tests with NWJS 0.13+, with the change over to the chrome-extension:// protocol, I noticed I had to change a couple things:

- Even if you've set baseUrl in the config file, that baseUrl doesn't seem to automatically append to the paths you call using browser.get():

```
browser.get('/dashboard'); // v0.12
browser.get(browser.baseUrl + '#/dashboard'); // v0.13+
```

- I'm hoping there's a way around this, but for me the only successful baseUrl I could set was 'chrome-extension://noakblofbajciaghholgljpkieiennnn/index.html':

```
var baseUrl = 'file://'+ path.resolve('build/index.html') + '#'; // v0.12
var baseUrl = 'chrome-extension://noakblofbajciaghholgljpkieiennnn/index.html'; // v0.13+
```

Once I switched these over and made sure to replace any other references to the "file://" protocol, my tests ran as they did on v0.12.

**Comment by vsathyak** [comment]
@reynoldsalec : Can u please share your conf.js? I would like to refer it since my attempt to run protractor test with nwjs 0.15.4 is failing.

Please see my conf.js and let me know if there is anything wrong.(This was working fine with nwjs : 0.12.3).


    exports.config = {
        directConnect: true,
        chromeDriver: '/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.23',

        capabilities: {
            browserName: 'chrome',
            chromeOptions: {
                binary: '/Applications/....../..../MacOS/nwjs'
            }
        },
        baseUrl: '',
        rootElement: 'html',
        onPrepare: function() {
            browser.resetUrl = '';
            // browser.driver.get('file://');
        },

        getPageTimeout: 150000,
        allScriptsTimeout: 150000,
        framework: 'jasmine2',
        specs: ['../test/abc/*_spec.js'],
        jasmineNodeOpts: {
            showColors: true,
            defaultTimeoutInterval: 150000
        }
    };
