### ISSUE TITLE
Can't use Bootstrap Glyphicons in node-webkit v0.10.2

### ISSUE THREAD

**Issue by Antrikshy** [nwjs/nw.js#2232]
When I attempt use one inside a Bootstrap button, I get

`Failed to load resource file:///blahblah/lib/fonts/glyphicons-halflings-regular.woff`
`Failed to load resource file:///blahblah/lib/fonts/glyphicons-halflings-regular.ttf`
`Failed to load resource file:///blahblah/lib/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular`

I have included the Bootstrap CSS inside my HTML as usual. Rest of the CSS seems to work normally.
##

**Comment by metal3d** [comment]
Same here with material-design icons, Tried with app:// and `./` or `/` path in 'url'. 
On nwjs v0.12.2
