### ISSUE TITLE
download file dialog

### ISSUE THREAD

**Issue by benag** [nwjs/nw.js#2236]
Hello ,

I have an iframe inside a nodewebkit, when a user clicks a download url the file dialog opens to chose a download location. I want to replace this behavior with automatic download to a certain location, any clue how this can be done?

Thanks,ben

**Comment by joelz** [comment]
Anyone got a solution for this problem?

**Comment by himanshub16** [comment]
The file could be downloaded by placing a download attribute to <a> tag.
However, there is no information about the progress, or completion of download once it starts.
Any idea?

**Comment by Mithgol** [comment]
NW.js does not (unlike Chrome) provide a GUI that displays information about the progress or completion of the download; however, the information itself is programmatically available (see #5650) and thus you may write some JavaScript to display that information on your page(s).
