### ISSUE TITLE
Spawn a second node-webkit app

### ISSUE THREAD

**Issue by gerwinbrunner** [nwjs/nw.js#2245]
Hi, 

I'm currently working on an improved auto-updater for node-webkit.

When I spawn a second node-webkit app (a copy of the current version) and try to send a message via ipc to the parent the child app hangs.

``` js

function run(path, args, options, cb){
  logger.info("run:", path, args, options);
  var opts = {
    //detached: true,
    stdio: [ 'ignore', 'ignore', 'ignore', 'ipc']
  }
  for(var key in options){
    opts[key] = options[key];
  }

  var sp = spawn(path, args, opts);

  sp.on('message', function(buf) {
    console.log("msg: "+buf);
  });
```

On the child I try to call 

``` js
process.send('Hello');
```

The Command does not return on the child and the whole apps "hangs".

This occurs on osx 10.9 with version 0.10.2. and 0.9.2 of node-webkit.

Any idea what the reason for this could be?
Or is there another way (already tried pipes) to send an info from the child to the client? I just want to let the parent know that the child has started successfully.

Cheers,
Gerwin
##

**Comment by fritx** [comment]
> process.send function is undefined
any progress on this? 0.12.x
