### ISSUE TITLE
Download files from <a href="data:application/octet-stream;base64,**" style

### ISSUE THREAD

**Issue by cloverstudio** [nwjs/nw.js#2255]
Hi

I have blob data in javascript and I need to save the data local. I tried to the approach which I wrote in subject but it looks like doesn't work.

Does anyone know how to achieve that ?

**Comment by NLKNguyen** [comment]
It solved my problem. Thanks.

**Comment by JoaoHeckmann** [comment]
Solved my problem as well

**Comment by yusufaliselek** [comment]
Solved my problem, thanks

**Comment by grandpa1946** [comment]
> Solved my problem, thanks

so when i have my base64 string, how do i actually convert it to a file?
