### ISSUE TITLE
Video in 10.2 (ffmpegsumo.so)

### ISSUE THREAD

**Issue by Kureev** [nwjs/nw.js#2256]
What about ffmpegsumo.so for 10.2? Files from @garryguzy not working in this version. Replacing with Chrome's ffmpeg throws error when i'm start to play video.

**Comment by sarrimaxime** [comment]
I found a version for NW 10.5 osX 32bit, you can download it here: https://drive.google.com/open?id=0B-W5PD832un2ZGJLc3R6SFZwc1k&authuser=0
Not working with 64bit :(

**Comment by hems** [comment]
@sarrimaxime for some weird reason i downloaded hundreds of them and none of them worked and them found your link!! I was so luck this was still available for download! 

saved my day big time!!!
