### ISSUE TITLE
Disabled menu item, still accessible via hotkey

### ISSUE THREAD

**Issue by guigrpa** [nwjs/nw.js#2261]
When disabling a menu item, by setting `menuItem.enabled = false`, it effectively prevents it from being clicked in the GUI. However, if the item is assigned a key (with some modifiers) the command can still be run. In my opinion, the hotkey should also be disabled.

Environment: node-webkit v0.10.2 running on Windows

**Comment by BoatsAreRockable** [comment]
This is still an issue in win 10 x64 with nw v0.13.2.

**Comment by rogerwang** [comment]
@ghostoy pls follow this.
