### ISSUE TITLE
how do I get node-serialport working in node-webkit?

### ISSUE THREAD

**Issue by TakahashiNZ** [nwjs/nw.js#2262]
First I tried installing node-serialport with "npm install serialport" and then copying the serialport folder into the node_modules folder of by webkit project. I get the following error:

Error: Cannot find module 'c:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\build\serialport\v1.4.5\Release\node-webkit-v14-win32-ia32\serialport.node'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\serialport.js:14:25)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)

Then I tried:
npm install -g nw-gyp
nw-gyp configure --target=0.10.2

And I get this error:
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.2
gyp info using node@0.10.30 | win32 | ia32
gyp info spawn C:\Programming\Python27\python.exe
gyp info spawn args [ 'C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\user\.nw-gyp\0.10.2\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\user\.nw-gyp\0.10.2',
gyp info spawn args   '-Dmodule_root_dir=C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:352:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js" "configure" "--target=0.10.2"
gyp ERR! cwd C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport
gyp ERR! node -v v0.10.30
gyp ERR! nw-gyp -v v0.12.2
gyp ERR! not ok

Finally I tried:
npm install node-pre-gyp -g
node-pre-gyp build --runtime=node-webkit --target=0.10.2

And now I get this error:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.5.23
node-pre-gyp info using node@0.10.30 | win32 | ia32
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.2
gyp info using node@0.10.30 | win32 | ia32
gyp info spawn C:\Programming\Python27\python.exe
gyp info spawn args [ 'C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\user\.nw-gyp\0.10.2\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\user\.nw-gyp\0.10.2',
gyp info spawn args   '-Dmodule_root_dir=C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  serialport_win.cpp
..\src\serialport_win.cpp(254): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modul
es\serialport\build\serialport.vcxproj]
          C:\Users\user.nw-gyp\0.10.2\deps\v8\include\v8.h(1665) : see declaration of 'v8::String'
..\src\serialport_win.cpp(254): error C3861: 'New': identifier not found [C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialpor
t\build\serialport.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\user\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js" "configure" "build" "--name=serialport" "--conf
iguration=Release" "--module_name=serialport" "--version=1.4.5" "--major=1" "--minor=4" "--patch=5" "--runtime=node-webkit" "--node_abi=node-webkit-v0
.10.2" "--target=0.10.2" "--platform=win32" "--target_platform=win32" "--arch=ia32" "--target_arch=ia32" "--module_main=./serialport" "--host=https://
node-serialport.s3.amazonaws.com/" "--module_path=C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\build\serialpor
t\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32" "--module=C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport\buil
d\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32\serialport.node" "--remote_path=./serialport/v1.4.5/Release/" "--package_name=node-web
kit-v0.10.2-win32-ia32.tar.gz" "--staged_tarball=build\stage\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32.tar.gz" "--hosted_path=http
s://node-serialport.s3.amazonaws.com/serialport/v1.4.5/Release/" "--hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.5/Release/
node-webkit-v0.10.2-win32-ia32.tar.gz"
gyp ERR! cwd C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport
gyp ERR! node -v v0.10.30
gyp ERR! nw-gyp -v v0.12.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd configure build --name=serialport --configuration=Release --module_name=serialport --vers
ion=1.4.5 --major=1 --minor=4 --patch=5 --runtime=node-webkit --node_abi=node-webkit-v0.10.2 --target=0.10.2 --platform=win32 --target_platform=win32
--arch=ia32 --target_arch=ia32 --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=C:\Users\user\Downloads\node-
webkit-v0.10.2-win-ia32\node_modules\serialport\build\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32 --module=C:\Users\user\Downloads\node-w
ebkit-v0.10.2-win-ia32\node_modules\serialport\build\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32\serialport.node --remote_path=./serialpo
rt/v1.4.5/Release/ --package_name=node-webkit-v0.10.2-win32-ia32.tar.gz --staged_tarball=build\stage\serialport\v1.4.5\Release\node-webkit-v0.10.2-win
32-ia32.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.5/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws
.com/serialport/v1.4.5/Release/node-webkit-v0.10.2-win32-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\Users\user\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp" "build" "--runtime=node-webki
t" "--target=0.10.2"
node-pre-gyp ERR! cwd C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_modules\serialport
node-pre-gyp ERR! node -v v0.10.30
node-pre-gyp ERR! node-pre-gyp -v v0.5.23
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd configure build --name=serialport --configuration=Release --module_name=serialport --version=1.4.5 --major=1 --minor=4 -
-patch=5 --runtime=node-webkit --node_abi=node-webkit-v0.10.2 --target=0.10.2 --platform=win32 --target_platform=win32 --arch=ia32 --target_arch=ia32
--module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_mo
dules\serialport\build\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32 --module=C:\Users\user\Downloads\node-webkit-v0.10.2-win-ia32\node_mod
ules\serialport\build\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32\serialport.node --remote_path=./serialport/v1.4.5/Release/ --package_na
me=node-webkit-v0.10.2-win32-ia32.tar.gz --staged_tarball=build\stage\serialport\v1.4.5\Release\node-webkit-v0.10.2-win32-ia32.tar.gz --hosted_path=ht
tps://node-serialport.s3.amazonaws.com/serialport/v1.4.5/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.5/Release/
node-webkit-v0.10.2-win32-ia32.tar.gz' (1)

Any suggestions would be greatly appreciated.

**Comment by egysuccess** [comment]
i have the same issue & CONFUSED :(
