### ISSUE TITLE
App crashes on Windows (7 x64) when OpenGL is used

### ISSUE THREAD

**Issue by iacovlev-pavel** [nwjs/nw.js#2266]
I am building an app which shows some panoramas to the user using krpano.

To reproduce the crash, open nw.exe and paste the following link:
http://krpano.com/krpano.html?xml=tours/corfu/tour.xml&html5=prefer+webgl
and then start dragging on the panorama, eventually you should get a crash - especially if you try to drag the panorama very fast (if not close and open again), it's not a 100% drag and crash scenario - but it happens in 50% of cases which makes the app unusable.

I reproduced the bug on different windows machines with different video cards.
krpano works fine in chrome/firefox.

Here is the .dmp file:
https://drive.google.com/file/d/0B-yuOHy4_x8scjA1ak1oRzVJcXc/edit?usp=sharing

If any other info is needed or you have some idea to make the crash go away, please write.

**Comment by publicENEMY** [comment]
Did you test on x32 bit?
