### ISSUE TITLE
Execute external programm (windows)

### ISSUE THREAD

**Issue by kitingChris** [nwjs/nw.js#2283]
Hi there,

Shell shows how to open files in their default editor:
https://github.com/rogerwang/node-webkit/wiki/Shell

But how can I run a specific executable?
(relative Path to executable is known)

I want to set up a button in my node-webkit app which opens a specific executable.
It need to work with windows. But of course an os independend solution would be better.

<bountysource-plugin>

**Comment by larssb** [comment]
Hi @kitingChris,

I know this questions is old but I was wondering how you managed to get it to work. I'm having issues invoking an external .exe with child_process. Could you please elaborate on how you fixed it?

- I'm on Windows server 2012R2
- using nwJS v0.13 beta5
- When I use .exec on child_process I can see that the process starts (I see this in taskmanager). However, I want to be able to see and interact with the process I'm invoking.
- I'm invoking the .exe via child_process inside my .html body, via a button that calls a function that is placed inside a <script> tag.

Here is the code:
`<!DOCTYPE html>
<html>
  <head>
    <title>Box Of Power</title>
  </head>
  <body>
    <table style="width:100%">
        <tr>
            <button type="button" onclick="executeScript()">

                Click it bitch!
            </button>
                <script>
                    function executeScript() {
                        //nw.Shell.openItem('PATH TO FILE ');
                        nw.Shell.openItem('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noexit -File PATH TO FILE ');
                        
                        /*window.gui = require('nw.gui');
                        var exec = require('child_process').exec;
                        //var spawn = require('child_process').spawn;
                        //var app = process.execPath + "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" + process.cwd() +" PATH TO FILE ";
                        //exec(app);
                        
                        exec('powershell.exe -noexit -File PATH TO FILE ', function(error, stdout, stderr) {
                           console.log('stdout: ', stdout);
                           console.log('stderr: ', stderr);
                           if(error !== null) {
                               console.log('exec error: ', error);
                           } 
                        });
                        */
                        /*
                        exec('dir c:', function(error, stdout, stderr) {
                           console.log('stdout: ', stdout);
                           console.log('stderr: ', stderr);
                           if(error !== null) {
                               console.log('exec error: ', error);
                           } 
                        });                        
                        */
                        /*
                        spawn('cmd.exe', ['/c', ' PATH TO FILE '], {
                           detached: true 
                        });
                        */
                    }
                    
                    function osType() {
                        // get the system platform using node.js
                    var os = require('os');
                    document.write('You are running on ', os.platform());    
                    }
                                            
                </script>
        </tr>
        <tr></tr>
        <tr></tr>
    </table>
  </body>
</html>`

--------

I hope the above is enough info for you to elaborate on how you fixed/give me some tips. Looking forward to your input and have a great evening.

**Comment by larssb** [comment]
Managed to get it to work. By using child_process.spawn() - that was a hard nut to crack. Love it.
