### ISSUE TITLE
node webkit renders slow when app opens maximized or fullscreen

### ISSUE THREAD

**Issue by Jrags87** [nwjs/nw.js#2287]
I have noticed when opening my app fullscreen or maximized in Windows that the renderer seems to run slowly. If the page is opened in a window with a set width and height within package.json, it does not exhibit this. 

It seems to do this because the window when maximized or set to fullscreen mode has to conform to the resolution (width x height) of the monitor. 

Is there a way to alleviate this? Or is this something that can be fixed in an upcoming release?

I have tried numerous ways of counteracting this, but nothing seems to help including setting show to false in package.json, and then opening the app within js.
##

**Comment by bradparks** [comment]
I have exactly the same issue on Mac OSX Lion... But it doesn't have anything to do with starting a window maximized, it happens whenever a window is maximized, possibly one that's using webgl.

For example, if I open a new, unmaximized window pointing to the Bunny Mark PixlJS sample app:

http://www.goodboydigital.com/pixijs/bunnymark/

It loads and runs at 60 fps. Which is great.

If I maximize the window, without even adding any more bunnies, the FPS drops to 26. With only 2 bunnies!

Here's the function I'm using to show the page:
```
function showTestPage()
{
  var gui = require('nw.gui'); 
  var config = {
      frame:true,
      toolbar: false,
      transparent:false
  };

  var url = "http://www.goodboydigital.com/pixijs/bunnymark/";
  var nw = gui.Window.open(url,config);

  nw.show();
}
```

**Comment by felicienfrancois** [comment]
May be related to #3030

**Comment by bradparks** [comment]
I think it may be related... thanks for the pointer! And to be 100% clear, you can duplicate this problem using just this package.json file

package.json
-----------------------------------------------------
```
{
  "name": "Problem with WebGL",
  "version": "1",
  "main":"http://www.goodboydigital.com/pixijs/bunnymark/",
  "window": {
    "frame": true,
    "width": 1024,
    "height": 768,
    "toolbar": true,
    "transparent":false,
    "position": "center",
    "resizable": true
  }
}
```

So just save that into `package.json`, and run it like so on a mac:

`/Applications/nwjs.app/Contents/MacOS/nwjs .`

then maximize the window, and tada, ~25 fps with just 2 bunnies ;-(

**Comment by bradparks** [comment]
I'm relatively new to Node Webkit, but in searching for solutions to this problem found

https://github.com/atom/atom-shell

which requires a bit more leg work to setup, but *seems* on first glance to be more configurable, and at least, renders my game *exactly* as chrome does - fast! I'm still following this, as I do believe that Node webkit is better supported, and very much worth knowing/investing in. Thanks!
