### ISSUE TITLE
[ubuntu14.04][nw 0.10.3] child_process.fork('ungit/source/server.js') error

### ISSUE THREAD

**Issue by luozhihua** [nwjs/nw.js#2293]
I want to run [ungit]() with child_process.fork('ungit/source/server.js') in node-webkit, but it throw an error on startup, I used `node-webkit v0.10.3` and my OS is `ubuntu 14.04 64 Bit`, error is like this:

``` bash
info: BugTracker set version: 0.8.2
info: BugTracker set user hash
info: BugTracker set version: 0.8.2


#
# Fatal error in ../../v8/src/runtime.cc, line 799
# CHECK(V8::ArrayBufferAllocator() != NULL) failed
#

==== C stack trace ===============================

 1: ??
 2: ??
 3: ??
 4: ??
Stopped keeping ungit alive
```

**Comment by reppners** [comment]
I'm having the same error but different circumstances: 
* OSX Yosemite
* Node-Webkit v0.11.5

The app I'm developing uses express @ 4.10.6
I execute this in a forked child process.

As soon as I run 

       var app = express();

the error occurs.

I checked and ungit uses express @ 4.10.3
