### ISSUE TITLE
Use of LSFileQuarantineEnabled on OS X

### ISSUE THREAD

**Issue by asmeurer** [nwjs/nw.js#2294]
The Info.plist in OS X has 

``` xml
    <key>LSFileQuarantineEnabled</key>
    <false/>
```

This causes all files created by the application (or any subprocess) to be quarantined by default, meaning the get the `com.apple.quarantine` extended attribute, and if you try to double click them in the finder it warns you about them, and, if the program being run is not code signed (I believe), will not let you open them unless you right click and choose open, choose "Open Anyway" from the Security preferences, or change the Gatekeeper settings in the Security preferences. 

This setting makes sense for a web browser, where created files are typically files that are downloaded from the internet, and should be quarantined, but for other kinds of applications, which assumedly node-webkit is designed to build, it makes less sense. 

Would it make sense to disable this by default? It took me some time to figure out that this was what was causing this behavior.

**Comment by corwin-of-amber** [comment]
This is *not* solved. See the mentioned issue.
