### ISSUE TITLE
Window Titles doesn't stack up in MAC Doc Tray ICON in v0.10.3

### ISSUE THREAD

**Issue by kamesh-a** [nwjs/nw.js#2300]
Hi,
When an app has one or more window opened. Application title used to stack up in mac doc tray icon/Window menu options. Behavior works fine v0.9.2. Attached screen shot.

code snippet : 

```
var nw = require('nw.gui');
var win = nw.Window.get();

// To enable default menu for mac 0.10.3
    process.core = process.versions['node-webkit'].split('.')[1];
    if (process.core > 9 && process.platform == 'darwin') {
      var nativeMenuBar = new gui.Menu({
        type: "menubar"
      });
      nativeMenuBar.createMacBuiltin("Full Client");
      win.menu = nativeMenuBar;
    }

// In right click menu Web app title should appear as independent opened window
var win1 = nw.Window.open('http://google.com');
var win2 = nw.Window.open('http://yahoo.com');

```

![v0 9 2-window-stack](https://cloud.githubusercontent.com/assets/3531949/4152607/500324be-3450-11e4-9a87-7b9d046ff993.png)

In case n0.10.3 windows are not stacking. Which makes it tough navigate to other opened windows which are not hidden.

Thanks.
##

**Comment by Christywl** [comment]
It works fine on Mac with nwjs-sdk-v0.26.3.
<img width="1280" alt="screen shot 2017-11-10 at 1 14 12 pm" src="https://user-images.githubusercontent.com/20039821/32643882-37f835cc-c619-11e7-90ff-be492d143b10.png">

**Comment by Christywl** [comment]
close until there is more information
