### ISSUE TITLE
Mac: File dialog (select file) files are dimmed for OS X Document Packages

### ISSUE THREAD

**Issue by docmars** [nwjs/nw.js#2305]
On trying to get my application's file format working, `*.wires`, the File Dialog has them grayed out.

These files are [Document Packages](https://developer.apple.com/library/mac/documentation/corefoundation/conceptual/cfbundles/DocumentPackages/DocumentPackages.html), so they're directories containing the meat of my file format's data as files and additional folders.

I also tried using `<input type="file" nwdirectory>` but it seems that it's explicitly looking for a folder, even though these files are treated as folders.

When using `<input type="file" accept=".wires">`, they still are not allowed to be selected. Removing the `accept` attribute does not allow them to be selected either. I tried using a file input in Chrome and was able to select these files, so what's different about **node-webkit's** File Dialogs compared to Chrome's in terms of file selection?
##

**Comment by javorosas** [comment]
+1 for this issue. I'm using 0.12.2

**Comment by javorosas** [comment]
Ok, this is not a solution but it worked in my specific case. If you let the user drag and drop the file, instead of selecting from the dialog, you can successfully get the path of the file.

https://github.com/nwjs/nw.js/wiki/Dragging-files-into-page
