### ISSUE TITLE
'enabled' property of menu item with submenu not working on linux

### ISSUE THREAD

**Issue by SamyPesse** [nwjs/nw.js#2312]
On mac, if I create an entry in the main menu of the app with a submenu and I disable it using: `entry.enabled = false`, the menu is disabled (gray and impossible to click on the submenu entries), this is the normal behaviour. 

But on linux, this is not working, the menu is still enabled.

I was not able to test on Windows.

node-webkit version: 0.10.3
##

**Comment by Kagami** [comment]
:+1: experience same issue with `nw@0.13.0-rc1sdk`
@rogerwang @ghostoy could you guys look at this please? Seems like this bug exists for a long time.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
