### ISSUE TITLE
"resizable": false in package.json does not work

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#2319]
Setting the window subfield "resizable" to "false" has no effect on Windows. The window can still be resized.

Demo HTML + package.json: https://dl.dropboxusercontent.com/u/15217362/nwresizable.zip

**Comment by srinathh** [comment]
This seems to be broken now. I'm using nwjs v0.20.0 on Ubuntu with XFCE and setting resizable to false doesn't prevent the window from being resized.

The work around of setting both min & max width to the same as width & height does seem to work still.

**Comment by tailot** [comment]
@srinathh try:
```
var gui = require('nw.gui');

var win = gui.Window.get();

win.setResizable(false);
```
