### ISSUE TITLE
NW crashing when using selenium-webdriver node module

### ISSUE THREAD

**Issue by fcarreno** [nwjs/nw.js#2325]
Hi,

I am getting my app crashed when using the node module selenium-webdriver:
https://www.npmjs.org/package/selenium-webdriver

The offending line seems to be the one indicated below:

var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder().usingServer('http://localhost:4444').build(); // --> here
    
driver.get('http://www.google.it');
driver.findElement(webdriver.By.name('q')).sendKeys('charles');
driver.findElement(webdriver.By.name('btnG')).click();

driver.getTitle().
        then(function(value) {
            console.info(value);
});

driver.quit();

-----
I have a crash dump file but not sure how to attach it.
The same code works (having phantomjs running webdriver on port 4444 - with: phantomjs --webdriver=4444 from command line) when running it in regular node.

nw:version in the chromium toolbar shows:
node-webkit v0.10.4
node.js v0.11.13-pre
Chromium 35.0.1916.157

My OS is Windows 7 - SP1

Thanks,
Fernando.

**Comment by zalow517** [comment]
Any updates on this? I'm having the same issue with chromedriver (2.14) and selenium-webdriver (2.44)... NW crashes.
