### ISSUE TITLE
Bug: child_process has incorrect PID, non working kill()

### ISSUE THREAD

**Issue by mangecoeur** [nwjs/nw.js#2340]
I updated to the latest node-webkit from 0.9.3 on MacOSX and I'm finding weird problems with child_process that i rely.

First, PIDs are wrong by one - I spawn a process and it tells me PID is e.g. 33774, but in fact it is 33775 (seen in activity monitor and the programs own logging).

Then when I want to kill the process, using `processVar.kill()` it just doesn't work. The process object has the field `killed: true` but the process is actually still running.

I am only able to kill the process using the ShellJS  to run `exec('kill ' + (PID+1) )`.

This worked with earlier versions of Node webkit.

Using OSX 10.9.4, node webkit 0.10.4 binary
##

**Comment by johnthedebs** [comment]
Thanks for creating this issue, I've been pulling my hair out trying to figure out why `.kill()` wasn't working until I discovered this.

I'm running NW.js 0.12.0 on OS X 10.10.2.

Adding 1 to the PID worked around the issue in my case, *however*, a co-worker tried running this on Ubuntu 14.04 and had much more sporadic pid issues which we don't yet have a workaround for.

**Comment by Boltgolt** [comment]
I'm having the same problem, Ubuntu 15.04

**Comment by xGabryMC** [comment]
I'm having the same problem on ubuntu 16.04... but the pids are totally wrong!
