### ISSUE TITLE
Node-webkit Heap size / Node.js Heap Size

### ISSUE THREAD

**Issue by rewiko** [nwjs/nw.js#2349]
Hi, 

I have a nodeJS process into a node-webkit application, this process need a lot of memory. I would like to increase the "max-old-space-size" parameter or the heap size memory of nodejs inside node-webkit.

My process nodejs works fine with option --max-old-space-size=8192 when i launch nodeJS alone. How pass a parameter to nodeJS inside node-webkit?

Thanks in advance.

**Comment by JamesJansson** [comment]
Hey Roger. Firstly, I'd like to say great work. 
I can get this to work by passing in 
    "js-flags": "--max-old-space-size=2047" 
Anything bigger and it breaks. 2GB is pretty good, but it would be amazing to use more in node. Is there anyway to get above this level?

**Comment by JamesJansson** [comment]
I've also checked this on the nw.js 0.12.0 alpha. It now only kills the console, but in reality it only ever gets to 1.5GB before it clunks out (despite the window console saying it has the full 2GB using performance.memory.jsHeapSizeLimit;)

**Comment by rogerwang** [comment]
@JamesJansson interesting. I'll look into this.

**Comment by sledorze** [comment]
@rogerwang Any news on this one?

**Comment by pedro-lucas** [comment]
+1

**Comment by cpainchaud** [comment]
+1   :)

**Comment by kevwilso** [comment]
Hi Roger,

This is an old issue but wondering if the limit of 2G is still in place?  We have a large application that can hit that limit.  Its not a common scenario but we are seeing it so would like to know what options we have in these scenarios.  

Thanks,

Kevin

**Comment by rogerwang** [comment]
Will check this soon.

**Comment by rogerwang** [comment]
With check this soon with 0.13. 0.12.x will not receive any updates.

**Comment by rogerwang** [comment]
@kevwilso I just checked with 0.13 , max-old-space-size larger than 2G is OK. Do you have any test case to verify it's working?

**Comment by rogerwang** [comment]
close as it looks ok. reopen if there are further information.

**Comment by kevwilso** [comment]
Roger,

Thanks for the information......

Kevin
