### ISSUE TITLE
HTTP slow buffering

### ISSUE THREAD

**Issue by ssssssssssss** [nwjs/nw.js#2356]
Dear All,

I'm trying to play video iva HTML5 video tag with relative high bit-rate (~10Mbps, latest Win32 pre-built binary), it's OK to play local files, but always buffering if using the HTTP protocol. I tried Chrome which is OK, so I think it must be something wrong with the build configurations.
Any hints?

**Comment by hzeroo** [comment]
Experiencing this too. Works well on mac but the video lags after some seconds. I noticed much less network usage on NW than Chrome, maybe a too short buffering time? :confused:

**Comment by hzeroo** [comment]
I'm using flash plugin to allow windows users a "smooth" experience, but that's a dirty workaround  :(
