### ISSUE TITLE
On OSX hidden windows to not receive 'close' event when menu Quit is triggered

### ISSUE THREAD

**Issue by tonypee** [nwjs/nw.js#2357]
Steps
- launched an app with show:false. (a background application)
- create a builtin menu 
- popup a different window (your application) 
- hide the application (as if you want to fall back to a tray app) 
- cmd-q or click on Quit

the hidden app does not receive 'close' events. This makes having a 'tray' app seem very buggy, since the menu becomes inactive. I tried to 'focus' the background app, but that just made its window visible (which is not desirable)

**Comment by mrfabbri** [comment]
I'm closing this as there hasn't been any further report of issues.

**Comment by achekulaev** [comment]
It still does not receive events when Quit is triggered from the main menu on the hidden window.
