### ISSUE TITLE
-webkit-app-region dragging not working after window resize from bottom

### ISSUE THREAD

**Issue by JonathanRowley** [nwjs/nw.js#2375]
If you create a new page with an element (div) spanning across the top, assign "-webkit-app-region: drag;" to it's css then resize the window from the bottom. (drag the bottom of the window up/down) and attempt to use drag the window from that top element, nothing happens. Tested in Both 32 and 64 bit versions of node-webkit on Mavericks. (v0.10.5 and v0.10.4)

**Comment by newoverguy** [comment]
@JonRowley 
You, cool~.
I had to write code like this from your thoughts.

```javascript
            mainWindow.current_height = mainWindow.height;
            var resizeHandler = null;
            mainWindow.on("resize", function (width, height) {
                if(mainWindow.current_height != height) {
                    if (resizeHandler) {
                        clearTimeout(resizeHandler);
                    }
                    resizeHandler = setTimeout(function () {
                        this.resizeBy(1, 0);
                        this.resizeBy(-1, 0);
                    }, 100);
                    mainWindow.current_height = height;
                }

            });
```

**Comment by newoverguy** [comment]
@JonRowley 
You, cool~.
I have written some code like this from your thoughts.
```javascript
            mainWindow.current_height = mainWindow.height;
            var resizeHandler = null;
            mainWindow.on("resize", function (width, height) {
                if(mainWindow.current_height != height) {
                    if (resizeHandler) {
                        clearTimeout(resizeHandler);
                    }
                    resizeHandler = setTimeout(function () {
                        this.resizeBy(1, 0);
                        this.resizeBy(-1, 0);
                    }, 100);
                    mainWindow.current_height = height;
                }

            });

**Comment by imjoshdean** [comment]
@newoverguy How does this look when you're resizing though? Does it look like it stutters?

**Comment by aretias-kr** [comment]
@imjoshdean
I tried using the code above.
With timeHandler (timeoutHandler) is fantastic compared to when not in use.
When fully granted a timeout move smoothly during resize operations
( I gave 500 ms)

**Comment by iwege** [comment]
Most of draggable regions are at the top of window and maybe with `width:100%`. But if the element region doesn't be changed in window resize, it still can not to be draggable. 

This code can forces node-webkit to update the draggable regions. 
~~~
<style>
  body,html{
    padding:0;
    margin:0;
  }
</style>
<div id="test" style="-webkit-app-region: drag;background:black; height:100px; width:100px;">
  
</div>

<script>
var nw = require('nw.gui');

var win = nw.Window.get();
var current_height = win.height;
var count = 99;
var _timer;
window.onresize = function (width, height) {
  if(_timer){
    clearTimeout(_timer);
  }
  _timer = setTimeout(function(){
    console.log(count);
    document.getElementById("test").style.width = count+"px";
    if(count == 100){
      count = 99;
    }else{
      count = 100;
    }
  },50);
};
</script>
~~~

**Comment by imjoshdean** [comment]
@iwege Your solution is basically black magic to me, but it works.

Thank you! :+1:

**Comment by eavae** [comment]
@iwege Your solution is completely worked for me.

Thank you very much!

**Comment by chevex** [comment]
My scenario may be different, but I was able to slim @iwege's solution down to a single `div` at the bottom of my app body.

```html
<body>
  <!-- app content here -->
  <div style="-webkit-app-region: no-drag;"></div>
</body>
```

The other CSS rules didn't appear to have any effect. The element at the top didn't appear to have any effect for me either. The bottom element with the `no-drag` rule seems to be all you need.

**Comment by iwege** [comment]
@chevex  Yes , the `no-drag` rules is the key of my solution because  node-webkit will update the draggable region  when user resize the element which has  `-webkit-app-region` rule. All other rules is make the element invisible with user.


And if you have an element at the bottom of your app and can be resized by window resizing , you can just add this rule to that element without add any redundant `div` element.

**Comment by chevex** [comment]
This is the most irritating bug. I still have it happen sometimes, even with the CSS fixes above and even with the width resizing scripts. It's getting old :(

**Comment by octalmage** [comment]
I've been trying to get one of these solutions to work, and I can't figure it out. No matter what I do the window can be dragged unless I maximize then unmaximize the window. I'll keep playing with it.

**Comment by octalmage** [comment]
Also this happens when my app is opened, it just starts broken.

**Comment by Karlheinzniebuhr** [comment]
same issue

**Comment by Nemesis9765** [comment]
Some other observations regarding this issue.

This fixes the drag issue for me when running it at startup.
```
Window.width += 1;
Window.width -= 1;
```

However, adding code to focus on the window like below breaks the fix,
```
Window.width += 1;
Window.width -= 1;
Window.focus();
```

But, to get around that, wrapping the focus in a short timeout seems to fix that as well,
```
Window.width += 1;
Window.width -= 1;
setTimeout(function onFocus() {
    Window.focus();
}, 50);
```

Looks like the bug may be related to how the window is rendered.  Just shooting in the dark here, but it looks like the window may try to make it draggable on load, but some other process interrupts (like my Window.focus in my second example) the process before it can make the window draggable, which is why wrapping it in a timeout seems to resolve the issue because it allows it time to finish.

**Comment by chino23** [comment]
@rogerwang is there a fix planned for this? Having the same issue in nw13 alpha7

**Comment by alo** [comment]
+1
