### ISSUE TITLE
Screen API should mark which screen is the primary one

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2383]
Related: #2178
##

**Comment by tphalp** [comment]
I can confirm that, on my setup, the main screen has `0` for `bounds.x` and `bounds.y`

**Comment by adam-lynch** [comment]
@tphalp It would be good to know which platforms you tested

**Comment by tphalp** [comment]
Edited my original post. Sorry for leaving that out originally.

**Comment by adam-lynch** [comment]
@tphalp thanks! My team won't need this soon but I will report back when we look into it more.
