### ISSUE TITLE
Window.open should allow you to pick a screen

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2384]
I guess by passing in a screen (/ screen ID) from the [Screen API](https://github.com/rogerwang/node-webkit/wiki/Screen). The coordinates you give then should be relative to that screen. Should be optional & defaults to the current screen (where the app is placed) / the "primary" one (see #2383). 

But then I guess if this was added, then there should also be a function to move a window to another screen (again by passing a screen / ID).

Related: #2178
##

**Comment by fritx** [comment]
```js
// Calculating for new win position
const depWin = global._wins['home'] ||
  global._wins['login'] || win
const winCX = depWin.x + depWin.width / 2
const winCY = depWin.y + depWin.height / 2
const curScr = _.find(screens, (scr) => {
  const { x, y, width, height } = scr.bounds
  return winCX >= x && winCX < x + width &&
    winCY >= y && winCY < y + height
}) || screens[0] // todo: Some more calculating
const wrkCX = curScr.work_area.x + curScr.work_area.width / 2
const wrkCY = curScr.work_area.y + curScr.work_area.height / 2
opt.x = wrkCX - opt.width / 2
opt.y = wrkCY- opt.height / 2
```
