### ISSUE TITLE
Act as a WebView container

### ISSUE THREAD

**Issue by claudioc** [nwjs/nw.js#2402]
I wonder if it would be possible to make node-webkit work like the container for a "webview", the concept that we have on Android/iOS. Basically you provide an URL to the webview component and it will load the website inside it. The nice thing about it is that you have total control over the resource loading (which means that you could embed websites and decide programmatically what to load and what not).

The problem, I guess, is that if I now embed an IFRAME inside the main index.html file, I would not receive any event for resource loading requests. Am I right?

**Comment by mrfabbri** [comment]
@claudioc [<webview>](https://developer.chrome.com/apps/tags/webview) tag support from Chrome apps api landed in NW.js v0.12.0-alpha1 (will ship in NW.js v0.12.0).
