### ISSUE TITLE
Memory is not released after page navigation

### ISSUE THREAD

**Issue by Nate-git** [nwjs/nw.js#2408]
Hi,

Not sure if this is the best forum for this question/issue.  If not, I'll apologize in advance and kindly ask to be pointed in the right direction.

It appears that node-webkit is holding onto memory past page navigation/reload.  I'm using the win32 distribution (node-webkit-v0.10.5-win-ia32).  To illustrate, I've got a single page application that purposefully bleeds memory.

Past normal reload or navigation to another site, the memory is not released (.reloadDev(); does release the memory).  Eventually this will cause node-webkit to hang or crash.

Is this a known issue and is there a work around?

Attachment Example - Scale memory then navigate to github, the heap is not reduced and Windows Task Manager also reports no reduction in physical memory:
![screenshot](https://cloud.githubusercontent.com/assets/8971897/4465882/7bee5fdc-48df-11e4-9029-d0b63ef79769.png)

Thanks

**Comment by Fogrunner** [comment]
is it fixed? 

i tested it in nwjs-v0.12.2-win-x64.



![shot](https://cloud.githubusercontent.com/assets/11848318/9019630/c25686d6-3829-11e5-9282-351eae65492c.png)
