### ISSUE TITLE
Can't make a shortcut for "Cmd+?" with gui.MenuItem or gui.Shortcut

### ISSUE THREAD

**Issue by Paxa** [nwjs/nw.js#2424]
I want to make shortcut for "Cmd+?", most of native applications have menu "Help" for that button

I can make it only with javascript lib like this:

```js
  window.Mousetrap.bind("command+shift+/", function () {
    callMenuItem('Window', 'Help');
    return false;
  });
```

If I try to use `gui.MenuItem` or `gui.Shortcut` it doesn't work.

**Comment by pouu69** [comment]
not working Commad key
