### ISSUE TITLE
how to make node-webkit genernate one tmp data

### ISSUE THREAD

**Issue by alexanderkenndy** [nwjs/nw.js#2434]
Hi 
      when node-webkit started, it will generate a folder in /tmp/(Ubunut), such as .org.chromium.Chromium.6igVUp , and when node-webkit closed,the folder .org.chromium.Chromium.6igVUp  still exists, and start the node-webkit again,then another .org.chromium.Chromium.xxx will be generated.

so I think if after a long times, and start/stop the node-webkit, there would be so many folders in /tmp/ named .org.chromium.Chromium.xxx, I am care about the space of disk......

so is the problem:
how could I make the node-webkit only generate the tmp file/folder in the same path only one folder ? just replace origin folder also make scense, though I don't know much about the chromium, and if we can control it will be helpful for user.
##

**Comment by adam-lynch** [comment]
If the app is killed from Window's task manager, etc. it won't be cleaned up. @rogerwang could NW.js keep track of the last temp directory name and clear it the next time the app starts?
