### ISSUE TITLE
JavaScript being throttled! [Game Dev] 

### ISSUE THREAD

**Issue by Bigmacbook** [nwjs/nw.js#2443]
I'm a web developer trying to code a game in javascript, but I have one problem.

when ever the game window is unfocused or minimized the JavaScript is throttled and creates a bottleneck. I know this happens with all web browsers. Node Webkit may use broswer technology, but it is not a browser.

I was hoping there was a way you could add an option for the JavaScript to run normally. I'd rather not code around this flaw. This flaw is what is holding back web game development.

Thanks
##

**Comment by rogerwang** [comment]
this is now supported by --disable-raf-throttling: http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-disable-raf-throttling
