### ISSUE TITLE
Windows 8.1 node-webkit crash while app is idle

### ISSUE THREAD

**Issue by abilash-amara** [nwjs/nw.js#2446]
Node webkit is crashing in windows 8.1. machine surface pro 3. The crash happened completely out of the blue. No user interaction was performed on when all of a sudden I saw the crash report. 

@jamesmortensen -- tagging you in this post 

I am pasting the event info and the 
 Event ID  1001
Task Category None
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Synclio Alpha v0.9.exe
P2: 0.0.0.0
P3: 5417ccda
P4: Synclio Alpha v0.9.exe
P5: 0.0.0.0
P6: 5417ccda
P7: 80000003
P8: 0004abf3
P9: 
P10: 

Attached files:
C:\Users\Abilash\AppData\Local\Temp\WERD04E.tmp.WERInternalMetadata.xml
C:\Users\Abilash\AppData\Local\Temp\WER4D5E.tmp.appcompat.txt
C:\Users\Abilash\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_Synclio Alpha v0_71c0a678f7b6d02acca54d8eb0fcb420ef746a_c4206365_cab_13ed4ee4\memory.hdmp
C:\Users\Abilash\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_Synclio Alpha v0_71c0a678f7b6d02acca54d8eb0fcb420ef746a_c4206365_cab_13ed4ee4\triagedump.dmp
WERGenerationLog.txt

These files may be available here:
C:\Users\Abilash\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_Synclio Alpha v0_71c0a678f7b6d02acca54d8eb0fcb420ef746a_c4206365_cab_13ed4ee4

Analysis symbol: 
Rechecking for solution: 0
Report Id: a2c3b7aa-50a5-11e4-828d-6002920b5873
Report Status: 100
Hashed bucket: 

Event ID 100 
Task Category (100)
Faulting application name: Synclio Alpha v0.9.exe, version: 0.0.0.0, time stamp: 0x5417ccda
Faulting module name: Synclio Alpha v0.9.exe, version: 0.0.0.0, time stamp: 0x5417ccda
Exception code: 0x80000003
Fault offset: 0x0004abf3
Faulting process id: 0x1f90
Faulting application start time: 0x01cfe49ec02cfebf
Faulting application path: C:\Program Files (x86)\Synclio\Synclio Alpha v0.9\Synclio Alpha v0.9.exe
Faulting module path: C:\Program Files (x86)\Synclio\Synclio Alpha v0.9\Synclio Alpha v0.9.exe
Report Id: a2c3b7aa-50a5-11e4-828d-6002920b5873
Faulting package full name: 
Faulting package-relative application ID: 

crash file in zip format --- >  http://1drv.ms/ZiMU4k 
contents
memory.hdmp
Report.wer
triagedump.dmp
WER4D5E.tmp.appcompat.txt
WERD04E.tmp.WERInternalMetadata.xml

Hope this will be enough to find out why the app is crashing randomly. 
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
