### ISSUE TITLE
Feature request: create and support an official npm package that would download and install node-webkit

### ISSUE THREAD

**Issue by Mithgol** [nwjs/nw.js#2453]
The final goal of this feature is to enable the easiest possible way of an installation of a node-webkit-based application:

`npm install -g appname`   *(substitute `appname` with a real package's name of the application)*

And the easiest way to run it:

`appname`

Now a couple of questions:

* What should an application do to reach such goal?

* What should node-webkit do to reach such goal?

- - -

## Application

Obvously, such an application relies on Node.js (and npm) for the application's installation and also for every launch. The application itself must reside in an npm package and be installed globally on the system, and such installation in turn requires some Internet access.

The application's `package.json` must contain [`"preferGlobal": true`](https://www.npmjs.org/doc/files/package.json.html#preferglobal) to warn against local installations.

The application must add node-webkit to [`dependencies`](https://www.npmjs.org/doc/files/package.json.html#dependencies) in `package.json` and declare the necessary version(s) of node-webkit (using [semantic versioning](http://semver.org/)).

Having declared that dependency, the application (after it is installed) may expect node-webkit to have the relative path of `node_modules/node-webkit-package-name/nw`. Substitute `node-webkit-package-name` with a (future) name of the npm package of node-webkit. Substitute `/nw` with `/node-webkit` on Mac OS X.

The application must declare a [`bin`](https://www.npmjs.org/doc/files/package.json.html#bin) field in `package.json` and must contain a corresponding CLI part that reacts when `appname` command is given to the system. That CLI part must be a (relatively simple) tool that merely runs node-webkit in the application's root directory (where the application's `package.json` resides) and lets node-webkit to do the rest.

- - -

## Node-webkit

In order to support all of the above, an npm package of node-webkit has to exist — so that `npm install node-webkit-package-name` causes node-webkit to appear in `node_modules/node-webkit-package-name` directory.

Node-webkit has a number of platform-dependent versions, and thus the package cannot directly contain any of them.

However, the package has to know all of these versions. For example, the package `node-webkit-package-name@0.8.6` has to know the following URLs:

* http://dl.node-webkit.org/v0.8.6/node-webkit-v0.8.6-linux-ia32.tar.gz

* http://dl.node-webkit.org/v0.8.6/node-webkit-v0.8.6-linux-x64.tar.gz

* http://dl.node-webkit.org/v0.8.6/node-webkit-v0.8.6-win-ia32.zip

* http://dl.node-webkit.org/v0.8.6/node-webkit-v0.8.6-osx-ia32.zip

Also `package.json` has to contain a `script.install` value pointing to a script that would run immediately after the package's installed. Such script has to detect the target system (no big deal, it's `process.platform` and `process.arch`) and download the necessary node-webkit from the Internet to the current directory.

(For example, that's almost how [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp/) installs the binary parts of [`sqlite3`](https://github.com/mapbox/node-sqlite3/) immediately after `npm install sqlite3` intalls the JavaScript parts. The binaries are downloaded from the Internet if available.)

The node-webkit's package does not have to contain all the code necessary to download a file from the Internet. The package may have its own dependencies and then they would be installed before the `script.install` runs.

- - -

## The end

If anything of the above is not clear, ask questions.

**Comment by shama** [comment]
Now there is an official npm installer: https://github.com/nwjs/npm-installer Thanks everyone!
