### ISSUE TITLE
Windows: path.join is lowercasing the drive letter

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2466]
To reproduce:
- Run `nw.exe` from [0.10.5](http://dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-win-ia32.zip)
- Paste this in the dev tools console:
  
  ``` javascript
  var path = require('path');
  var os = require('os');
  console.log(path.join(os.tmpdir(), 'Ab'));
  ```

Expected: `C:\........\Ab`

Actual:  `c:\....\Ab`

---

Happens with 0.10.5 but not 0.8.6. Tested on Windows 7 and 8.
##

**Comment by Christywl** [comment]
Works fine on nwjs-sdk-v0.26.3, please try the latest nwjs build.

**Comment by adam-lynch** [comment]
Optimistically closing 😄
