### ISSUE TITLE
Exec / spawn hanging main process

### ISSUE THREAD

**Issue by tommoor** [nwjs/nw.js#2492]
We've been seeing this in our application from 10.4 onwards, currently running 10.6rc. I'm putting this here as we've been trying to find the cause for weeks and wonder if anyone else is running into similar issues,

The entire node-webkit application hangs for 3-30 seconds at a time (rendering, timeouts, everything), the debugger is completely fine however running a CPU profile reveals nothing as this seems to hang along with the main process.

We're running a fair amount of video / canvas / all the good stuff :)

@rogerwang how would I go about debugging this?
##

**Comment by iofjuupasli** [comment]
I can confirm this on 0.12.3, when spawn external process on os x
