### ISSUE TITLE
[nw11] on starting devtools: "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by mrohnstock** [nwjs/nw.js#2495]
OS: Ubuntu 14.04.1 x86_64
build: http://dl.node-webkit.org/live-build/10-22-2014/7585bf4-a6fbff6-844fd24-f5b2bc8-255644a-9c142e5/

Don't know, if this is a bug, but on opening developer tools the following error appears:

```
(on shell:)
[5952:1022/101914:INFO:CONSOLE(1)] "Uncaught ReferenceError: require is not defined", source:  (1)

(on javascript console in developer tools:)
Uncaught ReferenceError: require is not defined
```
##

**Comment by simechiang** [comment]
I have the same problem. 
`"main": "http://127.0.0.1:5000/index.html"`
 `[3261:0520/140433:INFO:CONSOLE(1)] "Uncaught ReferenceError: require is not defined", source:  (1)`

When I changed the "main" filed : `"main": "index.html"` in package.json file, It' works. Is this a bug? @rogerwang
