### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by hems** [nwjs/nw.js#2507]
i just have this on my index.hmtl:

`level = require( "level")`

i have "level" on my package.json and executed "npm install" on my osx

```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at bindings (/Users/hems/git/oceanelevent/WHDApp/app/app/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/hems/git/oceanelevent/WHDApp/app/app/node_modules/leveldown/index.js:1:99)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
```

Tested with `node-webkit-v0.10.5-osx-x64`

**Comment by mangaga** [comment]
hi, everyone. @ghostoy @rogerwang

some of my users got the error "Module did not self-register." just sometimes when they access the app's local sqlite3 database(node-sqlite3) on nwjs, but some of users did never got this and never did myself. And never got this error access by node.js v4.x and v5.x.

Who can tell me why? What the true problem is？ thanks all.

test on computer environments :
window xp & WIN7 32bit & WIN7 64 bit
both nw0.12.3 node.js v4.x node-sqlite3 v3.1.x node-sqlite3 rebuilded by nw-gyp
nw0.13.x - nw0.14.x node.js v5.x and node-sqlite3 v3.1.x node-sqlite3 rebuilded by node-gyp

.node path for nw0.14.x and node.js v5.x
.node path:
path\app\node_modules\sqlite3\lib\binding\node-v47-win32-ia32\node_sqlite3.node
path\app\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node

nw0.12.3
.node path for node.js v4.x (never got this error):
path\app\node_modules\sqlite3\lib\binding\node-v46-win32-ia32\node_sqlite3.node
path\app\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node
.node path for nwjs v0.12.3:
path\app\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-ia32\node_sqlite3.node
path\app\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64\node_sqlite3.node

**Comment by hems** [comment]
@mangaga if a user does "npm install" on the folder and they are running the "wrong" node.js version that error will pop. you probably already know that, but doesn't hurt saying.

good luck
