### ISSUE TITLE
Window.reload() different from clicking refresh in toolbar.

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#2510]
I think I found a bug where Window.Anything() won't work every other refresh.

Example:

```
var gui = require('nw.gui');
var win = gui.Window.get();
console.log( win.width );
```

If you refresh using the toolbar every other refresh will return "undefined", the rest return the correct width. However if you use Window.reload() or Window.reloadIgnoringCache() it always returns the correct width.

It's not just width though, on the "undefined" refreshes none of the Window.things() things work. For example, the following won't work if you fresh with the toolbar:

```
$(".close").click( function() {
    win.close(true);
});
```

I created a sample app.nw file to reproduce the issue.
- https://db.tt/KIOrf4Ir

I'm using v0.10.5 (win32) on Windows 7 Pro SP1 64-Bit.
##

**Comment by mitselek** [comment]
I have an media player, where HTML5 contents is getting manipulated intensively all the time. Node leaks as hell - I can get memory usage of node-webkit helper from 50MB to 2GB in couple of minutes by just changing element.style from display="none" to display="block" and back.

So I needed to reload the application and player_window.reload() ( or player_window.reload(3) or player_window.reloadDev() ) does the trick. Only problem with this is that it works only once. All consecutive calls to reload just get silently ignored as if i didnt call them at all.

**Comment by TheJaredWilcurt** [comment]
Tested in NW.js 0.12.3 (64-bit), which is the last version to have a toolbar. The issue does not exist. Closing this issue.
