### ISSUE TITLE
0.11 RC1 does not use DirectWrite

### ISSUE THREAD

**Issue by matthiasg** [nwjs/nw.js#2524]
I had hoped font rendering issues (such as https://github.com/rogerwang/node-webkit/issues/734) would go away with the new 0.11 rc1 based on Chrome 38.

Sadly fonts rendered on a high dpi windows device (SurfacePro3) still look extremely mushy . It affects standard fonts and custom web fonts. I would assume DirectWrite is not enabled in the RC ?

Enabling direct write via chromium args doesnt work either (mostly i would assume because the chromium arg has now switched to 'disable' instead of 'enable')

Is this still something that is being worked on ? Why would this not be automatically resolved when using chromium 38 underneath ?

**Comment by mercurylmy** [comment]
@rogerwang I always use css like "@media all and (min-device-width: 1920px) {html,body {font-size: 150%;}" to adjust font size. I upgrade the nw, and it looks really ugly. Please give me a option in package.json to disable high dpi detect.
BTW in 10.1-10.3 both fs.writeFile and fs.writeFileSync can't wirte utf-8 text from <textarea> (direct wirte in javascript's string is ok). But the latest version is ok. Did I misconception something?
Thank you for your help.
