### ISSUE TITLE
Window width increases when application is restored after minimized.

### ISSUE THREAD

**Issue by CommissarXiii** [nwjs/nw.js#253]
I'm noticing an increase in window width when the application is restored from the taskbar (Windows 7, 64-bit) after it has been minimized. 

This happens even when resizable is set to false, or when all the height and width options (default, min, max) are set to the same value in package.json - in my case 1024w X 768h. 

See the attached image for an example.
![restore_width_issue](https://f.cloud.github.com/assets/165624/9004/87f9c090-4491-11e2-8102-4e77cb4c4abc.jpg)

Thanks!
##

**Comment by mfkddcwy** [comment]
windows 8.1
```
nw.js v0.12.0
io.js v1.2.0
Chromium 41.0.2272.76
```
my package.json
```
"height": 540,
"width": 800,
"min_height": 360,
"min_width": 580,
```
first time minimize and restore
```
winload: width: 816, height: 579
minimize: width: 160, height: 28
restore: width: 816, height: 579
```
change the width to minimum by mouse, then minimize and restore
```
minimize: width: 160, height: 28
restore: width: 740, height: 579
```
increase the width a little by mouse, again
```
minimize: width: 160, height: 28
restore: width: 744, height: 579
```
the issue hadn't happen

so, when `json.min_width + minimize.width > window.width` (`580 + 160 > 740`), this issue would happen.

how to fix it?

**Comment by 823639792** [comment]
or set "frame": false,

**Comment by 32u2** [comment]
I figured out the condition under which this still happens in Windows ("nwVersion": "0.27.5"). If the second monitor is present and this monitor has non-standard display settings ('Scale and layout', size of text set at 125%, or higher), upon restoring from the minimized, or maximized state, the scaling for the wrong monitor is applied **irrespective** of which monitor the app resided in the last time it was in the normal state.
