### ISSUE TITLE
nwsnapshot examples

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#2532]
Hi,

I've experimented with the nwsnapshot tool in the last days, but haven't really made a breakthrough.

I managed to compile some sample app (the angularJS tutorial) and run it, and it works fine. However, what I've seen is that the nwsnapshot binary differs from version to version and sometimes it doesn't work, sometimes it does, and even in the different versions of node-webkit the browser either crashes or at least gives me an error.

I never managed to get the snapshot run with my other app. It compiles, but when I include it, just a crash or weird error messages. Without the snapshot the single JS file works fine.

Did someone have more success with it? I can't seem to find anything on the subject.

- what version of nwsnapshot / node-webkit is proven to work?
- is there an example of a bigger project that compiles? or a tutorial of sorts?
- does anyone use node-nw-snapshot? It never works for me, and the documentation is bad.

Also I've run into problems with lodash and momentjs, as they don't seem to declare their variables globally. Using node style require didn't work either.

I'd appreciate it if someone could post a working example or has some insight on it. I'm kind of stuck after days of testing back and forth. 

Thanks a lot!

**Comment by rogerwang** [comment]
there is a new tool for this feature in 0.12.0-rc1, which removes the size limitation and fixes crashes. please try it: https://groups.google.com/d/msg/nwjs-general/Sykci3Qhgus/AoF0zT7TEIoJ

**Comment by chino23** [comment]
Thanks @rogerwang, that sounds great! I'll try that one out! :) Really appreciate the work on this feature!

**Comment by chino23** [comment]
So great this new tool! :) thanks a ton!
