### ISSUE TITLE
different default behavior for main window and any other window

### ISSUE THREAD

**Issue by dcohenb** [nwjs/nw.js#2543]
When setting up the window parameters in the `package.json` it will take over any other window we open in the app.
An example of the issue is that I only want the main window to be frameless but any other window should have a frame.

I can manually open a window and control its parameters but sometimes I don't have control over it
i.e:
- opening href link with `target='blank'`.
- social plugins login (facebook, google, twitter etc) where they control the window that opens.

I would love to see the option in the `package.json` to set different default flags for the main window and any child window.
something like:
`"window": {
    "title": "My App",
    "toolbar": false,
    "frame": false,
    "icon": "app_icon.png",
  },
"child-window": {
    "title": "Popup menu",
    "toolbar": false,
    "frame": true,
    "icon": "popup_icon.png",
  }`

**Comment by Gimmeaphatbeat** [comment]
While I can see there were two commits relating to this, what is the actual answer?
