### ISSUE TITLE
API for node-webkit-based applications to register themselves as certain file type handlers on OS level

### ISSUE THREAD

**Issue by Mithgol** [nwjs/nw.js#255]
A feature request: node-webkit could provide some API generalization of the underlying OS interfaces for an application to register itself as a handler for a given file type (extension).

For example, a DooM level visualizer could register itself as the [WAD file](http://en.wikipedia.org/wiki/Doom_WAD) handler, so that, for example, in Windows a double click on a WAD file launches the visualizer.

With this I am upgrading [the related Google Groups thread](https://groups.google.com/forum/?fromgroups=#!topic/node-webkit/plLi4mY9qIA) to a GitHub issue, because here it is more convenient to track.
##

**Comment by jaruba** [comment]
@Mithgol with ```npm install windows``` it might even be possible to register protocol associations from what I can tell, as it has ```registry()``` and could register the protocol to the app as [explained here](https://msdn.microsoft.com/en-us/library/ie/aa767914%28v=vs.85%29.aspx)

Can't figure out how atm. If anyone could post an example of registering a protocol to an app with ```register()```, I'd love to see it.

**Comment by jaruba** [comment]
I stand corrected, after attempting to use ```windows``` and fixing the error from ```require('windows')```, I realized that nothing works, not even file association (at least not on win8).

I then tried to use ```assoc``` and ```ftype``` in the command line and I get ```access denied```. It seems that on Win8 (donno about others) you need an elevated command prompt to use these commands.

**Comment by matthew-dean** [comment]
So, wait... with nwjs you can only associate file types with your app on Mac? Not Windows or Linux? o_O

**Comment by Mithgol** [comment]
I have an idea: you also might try using [`node-windows`](https://www.npmjs.com/package/node-windows) package, especially its `.elevate` or `.sudo` method.

**Comment by matthew-dean** [comment]
Can this be re-opened since there's not a solution for it in any packaging tool?

**Comment by Mithgol** [comment]
@zcbenz If you are still somewhere here with us, consider reopening this issue. (I'd reopen it myself, but GitHub won't let me; I presume that's because I'd be overriding a decision of a GitHub staff member.)

**Comment by Mithgol** [comment]
This issue is technically still valid (i.e. there's no API for NW.js-based applications to register themselves as certain file type handlers on OS level) and thus I am reopening it, fulfilling the request of @matthew-dean. (Now GitHub lets me do it because I am a collaborator.)

**Comment by matthew-dean** [comment]
Thanks! And hopefully this will be addressed soon!

**Comment by Mithgol** [comment]
On the contrary, it won't be easy to address this issue, especially on systems other than Windows.

**Comment by matthew-dean** [comment]
Any chance of this being addressed now that we're past the nw13 mark?

**Comment by Mithgol** [comment]
`¯\_(ツ)_/¯`
