### ISSUE TITLE
<audio> element has no .play();

### ISSUE THREAD

**Issue by CelestialWalrus** [nwjs/nw.js#2551]
Hey,

I was getting HAVE_NOTHING error stuff so I've replaced my libffmpegsumo.so with the one from Chrome and element does not have the .play method now. What can I do to get mp3 files to work in node-webkit?

I use ArchLinux.

-CW

**Comment by ghostoy** [comment]
See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for latest instructions for NW.js 0.13.0 or later.
