### ISSUE TITLE
File/color dialogs are not modal (windows)

### ISSUE THREAD

**Issue by jledentu** [nwjs/nw.js#2554]
Hi ! :)

I'm developing a nw app in Windows 7. Currently `<input type="file">` and `<input type="color">` open a window which is not modal, unlike in Chromium. These dialogs should be modal, don't you think ?
Or at least, an option could be added to specify the modal/not modal behaviour.

**Comment by ghostoy** [comment]
This bug should be reopened. File dialog is fixed. But color chooser is not modal on nw.js, which is a modal dialog on Chrome.
