### ISSUE TITLE
node-webkit File-dialogs problem

### ISSUE THREAD

**Issue by danvim** [nwjs/nw.js#2571]
I've also posted this problem on StackOverflow, but no one really reads that.

I wanted to **enumerate file names under selected directory from webkitdirectory <input>, but only returned the directory name** just like how https://github.com/rogerwang/node-webkit/wiki/File-dialogs says.
HTML:
-

    <input id="dialog-choose-photo-folder" type="file" webkitdirectory>

Console Returned:
-

    > document.getElementById("dialog-choose-photo-folder").files
        FileList {0: File, length: 1, item: function, clear: function, append: function}
          0: File
            lastModifiedDate: Tue Oct 07 2014 23:02:54 GMT+0800 (中國標準時間)
            name: "Pictures"
            path: "C:\Users\Daniel\Pictures"
            size: 40960
            type: ""
            webkitRelativePath: "Daniel/Pictures"
            __proto__: File
          length: 1
        __proto__: FileList

Version of Node Webkit:
-

v0.10.5

The `document.getElementById("dialog-choose-photo-folder").files` returned a length of `1` but there are actually many.

How comes it returned the directory name? Am I doing anything wrong? I even followed closely to https://github.com/rogerwang/node-webkit/wiki/File-dialogs

I've seen the `nwdirectory` attribute and I believe mine behaved exactly like that, is it a bug?

If I'm doing everything wrong, I actually want to result of: http://www.thecssninja.com/demo/webkitdirectory/

Please help me! :(

**Comment by chafey** [comment]
FYI - this bug exists in 0.12.0.  Please fix!

**Comment by chafey** [comment]
Note - this seems to work fine in 0.8.6

**Comment by vimxts** [comment]
Leaving a link to my StackOverflow question, just in case: http://stackoverflow.com/questions/26800822/node-webkit-try-enumerate-file-under-directory-from-webkitdirectory-input-but/29608142#29608142

**Comment by yolo2013** [comment]
It is a bug.....please fix it.

**Comment by hxzqlh** [comment]
I had the save problem, version v0.12.3. This is a horrible bug, can someone fix it?I am new to nw.js......

**Comment by Docteur-RS** [comment]
Hi !
Using V0.25.2 and its not working.
It lists all the files that are in the directory instead of giving me the directory's path...

**Comment by Docteur-RS** [comment]
Finaly I used this https://www.npmjs.com/package/nw-dialog !
