### ISSUE TITLE
Clipboard Returns [object Array] Every Time on Windows 8.1

### ISSUE THREAD

**Issue by kirkouimet** [nwjs/nw.js#2575]
Here's my issue:

![capture](https://cloud.githubusercontent.com/assets/62191/4961239/4c81cb70-66cc-11e4-9266-b66416aaad63.PNG)
##

**Comment by Christywl** [comment]
I can't reproduce this on nwjs v0.26.3. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information
