### ISSUE TITLE
How to change title and icon of notification?

### ISSUE THREAD

**Issue by island205** [nwjs/nw.js#2582]
FIY:

![screen shot 2014-11-10 at 5 29 15 pm](https://cloud.githubusercontent.com/assets/610094/4973715/c318c1be-68ff-11e4-8afb-e19ecf1d2341.png)
![screen shot 2014-11-10 at 5 29 37 pm](https://cloud.githubusercontent.com/assets/610094/4973714/c316f3e8-68ff-11e4-8e75-104239e0a7a1.png)

**Comment by cristianfraser** [comment]
@island205 How did you fix it?

**Comment by Paxa** [comment]
Still can not change that icon

**Comment by baconface** [comment]
Example code here works for me: https://github.com/nwjs/nw.js/wiki/Notification#sample-code

**Comment by Paxa** [comment]
Thank you. On mac it looks like this:

![screen shot 2015-05-18 at 10 50 50](https://cloud.githubusercontent.com/assets/26019/7674168/da0618f0-fd4b-11e4-9193-6f58c53309dd.png)

How to change icon on a left?

**Comment by jtg-gg** [comment]
@Paxa the icon on the left is the application icon, you can change the application icon in manifest

**Comment by Paxa** [comment]
@jtg-gg When I change in manifest it not working on mac

When I run like this:

```
./node_modules/.bin/nw --mac_plist ./mac_files/app.plist --mac_icon ./mac_files/app.icns
```

it working only sometimes. You can try it with sample application I made:

https://github.com/zcbenz/nw-sample-apps/tree/master/notifications
