### ISSUE TITLE
Feature Request: gui.Shell.openItem() could pass arguments

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2584]
Useful for auto-updating, etc. They'd get passed to the new node-webkit app ( i.e. `argv`).

**Comment by ghostoy** [comment]
`child_process` module of Node.js can help to run arbitrary command with arguments. How about using that?

**Comment by adam-lynch** [comment]
I think I've had mixed results. This would be like calling this method then immediately quitting (which seems to work even if an app is single-instance). 

This feature request isn't a big deal. I'm not depending on it or anything. I'll close.
