### ISSUE TITLE
nw v0.11.0 Make My ExtJs Application Not Show Any Text

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#2593]
I use nw in Windows 7 and try the 32bit / 64bit verson.

The login form under nw v0.11.0:
![not show any text](http://61.147.77.60:91/media/uploads/201411/f12T09443977.jpg)

The same login form under nw v0.10.5:
![normal](http://61.147.77.60:91/media/uploads/201411/f12T09463713.jpg)
##

**Comment by fzx** [comment]
To reproduce this error, I modified the demo project “menus” to redirect to my login page:http://61.147.77.60:91/soft/workfiles/c5ec3098aaa311e4983f005056af7c8f/download

**Comment by fzx** [comment]
bump!

**Comment by fzx** [comment]
This problem solved by v0.12.0.
