### ISSUE TITLE
Modal dialogs do not appear with 0.11.0 on Linux

### ISSUE THREAD

**Issue by rprichard** [nwjs/nw.js#2609]
On Linux (tested on Xubuntu 14.04), with node-webkit 0.11.0, the `prompt`, `confirm`, and `alert` functions return immediately without showing a modal dialog.

`confirm` returns false.
`prompt` returns null, rather than a string.
##

**Comment by jonwwilkes** [comment]
Can confirm on Debian Jessie with 0.11.5
