### ISSUE TITLE
Element close to edge will keep hover state even after mouse leaves app

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2610]
Or even after another app is focused.

Example:
 ![image](https://cloud.githubusercontent.com/assets/1427241/5045077/4755a954-6bf0-11e4-823a-4d3e92a605ed.png)

Is there any workaround for this? I'm not sure if it's possible to force an element to lose hover state.
##

**Comment by willurd** [comment]
I'm experiencing similar issues. I'm not getting hover states at all. Things are simply not responding to mouse over events. Instead my buttons' hover states (and mouse over events) are being applied/fired when I click on them, at which point they remain active/focused. Should I file a separate ticket?

FWIW I'm building my app in React, using nw.js version 0.12.0.
