### ISSUE TITLE
SVG Images get Save As dialog instead of displaying

### ISSUE THREAD

**Issue by kcunningham** [nwjs/nw.js#2617]
Running 0.11 on Windows. When a program, such as Inkscape, registers for the svg file extension, SVG images do not display correctly in node-webkit. Instead, a save as dialog shows offering to save the image. This happens when displaying with either img or object tags.
##

**Comment by akluthe** [comment]
Same thing happens to me with tif images, whether they exist on disk or not (in my case they didn't, but I tried with existing ones and got the same result).

**Comment by stwiname** [comment]
This still happens on Windows with 0.12.2

**Comment by rogerwang** [comment]
merge with #2869
