### ISSUE TITLE
Problem with webgl on windows

### ISSUE THREAD

**Issue by romaindurand** [nwjs/nw.js#2620]
Hi,
I just started a new node-webkit project using nw-sample-apps :
https://github.com/zcbenz/nw-sample-apps
But I can't get the demo "webgl" to work.

I get this message : 

Uncaught node.js Error 
TypeError: Cannot read property 'getExtension' of null
    at file:///D:/node-webkit-v0.11.0-win-x64/vendor/three.js/build/three.min.js:449:32
    at new THREE.WebGLRenderer (file:///D:/node-webkit-v0.11.0-win-x64/vendor/three.js/build/three.min.js:451:65)

I get the same message when using this project :
https://github.com/jeromeetienne/threejsboilerplate

Any known issue with v0.11 on windows 8.1 x64 and webgl ?
##

**Comment by luizbills** [comment]
+1

**Comment by Baccanno** [comment]
Some gpus (even last gen) might be getting some hatred there, when I tried my game demo some PCs were behaving OK and others would just say that WebGL is not activated, when I tried the online version on the chrome browser of those machines it worked.

I'm much eager to see a solution too

**Comment by gabrielstuff** [comment]
Ok, I'll try later this week but the best would be to list the CGs that we test on :)

**Comment by Baccanno** [comment]
I'll ask for those shortly !

**Comment by Baccanno** [comment]
tested the build on 780GTX and 980GTX and both didn't work, it works on 760GTX but chrome/chromium has severe issues and have a very strange behaviour (a bit like requestAnimationFrame was triggering abnormally)

On my i5 with HD4000 it works great, ... looks like having no dedicated GPU is the best option :/

**Comment by Baccanno** [comment]
This issue is not getting any news. Tried anything from installing DX redist and adding flags to the build ( using node webkit builder )

But still many computers can't get my game to work although it works perfectly well on their chrome browser. 

Pretty urgent need :)

**Comment by felicienfrancois** [comment]
Do you tried to ship `D3DCompiler_43.dll` and `d3dx9_43.dll` alongside node-webkit binaries ?
https://github.com/nwjs/nw.js/wiki/Webgl-support-on-windows

**Comment by Baccanno** [comment]
Tried both installing Dx runtime and adding those dll in the execution folder.

**Comment by aglew** [comment]
@Baccanno I have met the problems as you said and tried all solution which didn't work. I wonder know whether the problem has been solved. if there are some effective solution?

**Comment by sourceskyboxer** [comment]
You need to upgrade threeJS from r67 to r72 /vender/three.js/build/threejs-min.js

![update_boilerplate_with_threejs_r72](https://cloud.githubusercontent.com/assets/3496136/10117152/d66b4346-644d-11e5-8105-5f62cb0ed309.PNG)

@gabrielstuff 
Good point i have tested it and using 0.12.3 nw.js works fine without local server thank you - i am very happy now to develop own custom game-client yeah
