### ISSUE TITLE
webGL not working since NW 0.8.0 (Chromium 30) on 32-bit Windows

### ISSUE THREAD

**Issue by notsospecial1** [nwjs/nw.js#2630]
On my Win 7and Win XP systems (32-bit),  webGL was working through NW 0.7.5.  After eliminating all other causes ( Three.js,  dll 's, etc.)  I now realize that webGL  (as evidenced by inablility  to run "webgl" node-webkit sample app) has been unavailable from NW 0.8.0 onward -- Chromium 30+.

I have tried every chromium-flag I can dig up -- including 

```
  --enable-webgl    --ignore-gpu-blacklist  --enable-webgl-draft-extensions 
  --enable-experimental-canvas-features   --use-gl=egl     --gpu-startup-dialog
```

to no avail.  WIth no other changes to my hardware or environment, after moving to chromium 30 and beyond,  javascript  can no longer open a webGL  ('3d')  context with either
    canvas.getContext( 'webgl')   or   canvas.getContext( 'experimental-webgl').

I have looked through NW  issues relating to "WebGL"  as well as chromium issues  -- and this same problem seems to arise (for either OS X, Linux, or Windows) after many chromium releases --  but  I can not dig out a solution for NW.

Any help would be appreciated.  (Game-producers ?? ---  Anyone ?? )
##

**Comment by chriddyp** [comment]
It looks like those flags are only available on the experimental version of chromium - I opened up a issue for an experimental build here: https://github.com/nwjs/nw.js/issues/3035
