### ISSUE TITLE
Using Cluster with Node Webkit

### ISSUE THREAD

**Issue by Lesanjo** [nwjs/nw.js#2637]
Does anyone have a working example of usage of the
cluster module from within node webkit?
I have used cluster successfully but from command line.
However, I haven't been able to do so in node WebKit due
to errors such as an 'EPIPE' error.
I would like to assess working code to see where I've
been going wrong
Thanks
NB: I'm using Windows 8.1 and node.WebKit 0.9.2
##

**Comment by xcoderzach** [comment]
+1
