### ISSUE TITLE
is JXcore a option for Node-webkit ?

### ISSUE THREAD

**Issue by smiling-Jack** [nwjs/nw.js#2651]
Hallo
I think http://jxcore.com/home/ is a good altanative for the normal node.js

@ rogerwang
Do you think it#s a big problem to make a nodewebkit build with jxcore ?
##

**Comment by fithwith** [comment]
+1 for this, and JXCore is open source

**Comment by sajjad-ser** [comment]
+1 for this ;)

**Comment by bondneverdies** [comment]
Now that JXCore is open source, can run on mobile platforms (iOS, android and WP soon), it would be amazing that NWJS can run on the top of JXCore, this would unleash the power of NWJS for mobile applications. +1000 for this !

**Comment by LinkTree3** [comment]
Are there any updates on this?

**Comment by rogerwang** [comment]
Now we implemented Node.js support in WebWorkers, so NW programmers can write multithreaded JS code in this way.
