### ISSUE TITLE
node-webkit crash when use ctrl+shift change ime on windows XP

### ISSUE THREAD

**Issue by allenm** [nwjs/nw.js#2656]
I have uploaded the dump file to : http://api.allenm.me/nw-crash-dmp.zip

OS: Windows XP SP3
IME: 智能ABC ，极品五笔  
operating steps：In the textare , input some words, then use ctrl+shift to change the ime , then input some words . Then the app crash .
##

**Comment by guxing** [comment]
i use v0.14.7 but it not be fixed!  node version is v5.12.0!   uninstall the 智能ABC fixed，but not best way，because i can't ask my customers do like that!
