### ISSUE TITLE
child_process.fork() close with 3221225477

### ISSUE THREAD

**Issue by smiling-Jack** [nwjs/nw.js#2664]
Hello
since V0.11.0 i get directly after start a child_process.fork() on the close event the code "3221225477"

my operating system is Win 7 and node-webkit win32 & win64

if i change back to V0.10.5 the child process is running but I have sporadic delay on the message event.

What can i do to run code in a different process that is non blocking the main process ?

**Comment by matthew-dean** [comment]
What was the cause of this? I'm getting an immediate exit code of 3221226356 on Windows 8.1 after forking a child process. I'm on NWJS 0.12.2. Not sure if it's related. Should this be reopened?
