### ISSUE TITLE
Breakpoints invalidate after 0.11.0

### ISSUE THREAD

**Issue by woc2006** [nwjs/nw.js#2668]
platform: Mac OS 10.10
nw: 0.11.0  32bit

I set breakpoints in node context, but the code never stopped on that.

I tested 0.11.1, the same issue.

**Comment by Phoenixmatrix** [comment]
+1 on this issue. I'm having the same problem right now, and am having trouble isolating it (using 0.12). Breakpoints in the web context work fine. For stuff running in the node context, they do not work for callbacks. ie: if I'm creating an http server, I can break on http.createServer, but I won't be able to break inside the callback.

**Comment by astoilkov** [comment]
+1 for the issue...experiencing the same problem it is just not possible to develop when you can't debug the code

**Comment by rogerwang** [comment]
merge with #2996, which is fixed.

**Comment by woc2006** [comment]
Debugger doesn't stop at the right lines if source code contains unicode comments.
Version: 0.12
