### ISSUE TITLE
NW 0.11.1 doesn't work on ubuntu 12.04 x64 system

### ISSUE THREAD

**Issue by rhiokim** [nwjs/nw.js#2669]
It's not working. I did not anything for run NW. Can I get any information?

``` bash
my@ubuntu:~/Works/my/nw$ lib/node-webkit-v0.11.1-linux-x64/nw
[52043:1122/235010:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! 
See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/mnt/hgfs/Works/my/nw/lib/node-webkit-v0.11.1-linux-x64/nw
LaunchProcess: failed to execvp:
/proc/self/exe
[52043:1122/235010:ERROR:child_process_launcher.cc(344)] Failed to launch child process
```

**my ubuntu box information**

``` bash
my@ubuntu:~/Works/my/nw$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
```

``` bash
my@ubuntu:~/Works/my/nw$ uname --all
Linux ubuntu 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dyu** [comment]
@rhiokim I got the same error.  What was the problem that you solved?

**Comment by rhiokim** [comment]
@dyu I don't know exactly solution. I just update my ubuntu using `sudo apt-get dist upgrade` command.

**Comment by dkvbabu** [comment]
Hi All,
I am getting the same issue as above while trying to run getusermedia () in my ubuntu 12.04. Below is the error.
[15680:0224/134236:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.

I tried with chmod 4750 to attach a suid with the linux executable without any success.
Please guide.

**Comment by mathieumg** [comment]
> I got the same error. What was the problem that you solved?

Same. :+1:

**Comment by mathieumg** [comment]
I had this problem as well using 0.12.1, and it went away when installing 0.12.2. I'm on Ubuntu 12.04 x64 too.
