### ISSUE TITLE
v0.11 - Slow canvas?

### ISSUE THREAD

**Issue by quasado** [nwjs/nw.js#2675]
Upgrading to v0.11.x made the canvas blitting (multiple canvases on top of each other) very slow compared to previous v0.10. What is the reason for this and how to fix it? 
Running the same app in standalone Chrome-App v38.x at the same window size works much more performant as expected?

System is OS-X Yosemite

**Comment by rogerwang** [comment]
Does it work for you with v0.12.1 or v0.13.0-alpha0?
