### ISSUE TITLE
URGENT - how to load https pages from remote server, and execute locally for nodejs usage?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#2679]
![untitled presentation](https://cloud.githubusercontent.com/assets/107349/5163850/7a4a698e-73d0-11e4-96d3-1b4d6489ae2d.jpg)

Introduction: 

We are doing a new research project recently with node-webkit see the above picture. Where node-webkit loads a simple https web url where we have all our nodejs scripts to access serial port, java-applets, tcp/udp etc etc to send and receive commands from a robot. after receiving all those information we need to send them to server, server does all the management and do a proper interpretation for the other robots to simulate same actions.

Problem: 

But the node-webkit limitation is killing our project deadline because its not allowing very basic access when we load the pages using https / http instead of local. 

We have our closed source code in cloud servers, all the node-webkit runs in Local machine and executes the web page as https://load-from-server, now we place all our device access codes in remote server instead of local and we need to have full access on that PC just like if you had the script executed locally. We also require this because our remote scripts get automatically upto date.

How can we make this possible in node-webkit, its a very important requirement for our use case but i have not found any solution for it yet. 

Question: How can i tell node-webkit that following lines if loaded via https or http from remote server run them as it was running well using local index.html?

```
var gui = require('nw.gui');
var sys = require('sys')
var exec = require('child_process').exec;
var os = require('os');
var win = gui.Window.get();
```

**Comment by kospot** [comment]
has the same question!And I am also confusing about how to require local node
 modules~
if my main is "/source/index.html", I can require local module which is start from "/source"
but if my main is "http://test.com/test/index.html", how can I require my local node module
