### ISSUE TITLE
window.print() crashes app on Windows with Nodewebkit 32bit

### ISSUE THREAD

**Issue by westonganger** [nwjs/nw.js#2693]
Same issue from #2515 except with the stable build, not live build. Tested on 0.11.1
##

**Comment by feugy** [comment]
With version 0.11.5, Windows 32bit, printing does not crash anymore, but it simply prints nothing. The printer's queue is still empty as if an error had prevented data to be sent to printer.

**Comment by ergoli** [comment]
With version 0.12.0, windows 32bit, window.print() still crash.

**Comment by bestplay** [comment]
With version 0.12.0, windows 32bit, window.print() still crash.

+1

!
@rogerwang

**Comment by bestplay** [comment]
With version 0.12.0, windows 64 bit, window.print() still crash.

+1

!

**Comment by bestplay** [comment]
Sorry, I forgot to ship the pdf.dll.

**Comment by bestplay** [comment]
After shipping pdf.dll and print. it will finish printting. and also crash : APPCRASH . Not crash the whole app.(app is still running.). Just alert the crash window. 

Not happen with win7 32bit, only 64bit.

**Comment by bestplay** [comment]
I will try again with the newest version 0.12.1

**Comment by elbertcastaneda** [comment]
I have the same problem nw 012.1 x64

**Comment by hernanBeiza** [comment]
With version 0.12.0, windows 64 bit, window.print() crash. :(

**Comment by hernanBeiza** [comment]
I compiled using the version 0.12.2 and I tested in Windows 7 64 bit, window.print() doesn't crash anymore :)
