### ISSUE TITLE
Node-webkit v0.11.0+ extremely janky for games

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#2698]
Node-webkit v0.11.0+ is based on Chromium 38, and therefore inherits the following bug which I believe is only in Chrome M38: https://code.google.com/p/chromium/issues/detail?id=422000 (I think it's a Windows-only v-sync bug which makes it jitter badly)

This can make HTML5 games published with node-webkit appear pretty poorly on some systems. It does not appear to affect all systems since I can't see any problems at all on my Windows 8.1 system with Node-webkit 0.11.1, but there are still lots of complains from Construct 2 users using that version - see this thread: https://www.scirra.com/forum/node-webkit-jerkiness_t119430

In general it would be good if NW could keep pace with Chrome stable updates - M39 is already stable and I think helps a lot, but I don't know how much work the rebasing is.

**Comment by AshleyScirra** [comment]
The latest patch in the upstream issue appears to have resolved it, at least for me. It looks like the patch went in to M41, so it would be useful for C2 users if the next major node-webkit update could base off that.

**Comment by rogerwang** [comment]
Yes the next nw 12 will be based on chrome 41. The first alpha release we have is on an earlier version of M41. Will do a rebase after the first alpha release.
