### ISSUE TITLE
show chinese txt wrong

### ISSUE THREAD

**Issue by wildcatking** [nwjs/nw.js#2703]
I run node-webkit-v0.11.0-win-ia32 in win7 32bit，visit fllow htm page：
&#60;html&#62;
&#60;head&#62;
    &#60;title&#62;TEST&#60;/title&#62;
        &#60;meta http-equiv="Cache-Control" content="no-store" /&#62;
        &#60;meta http-equiv="Pragma" content="no-cache" /&#62;
        &#60;meta http-equiv="Expires" content="0" /&#62;  
    &#60;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&#62;
&#60;/head&#62;
&#60;body&#62;
中文
&#60;/body&#62;
&#60;/html&#62;
in nw show nothing，but change "中文" write engish sample"test",show test normal.
and in this pc,use chrome,IE or firebox visit this page ，show normal。
why？I must config anything？

**Comment by wangyazhen** [comment]
What is the reasons for this problem
