### ISSUE TITLE
Is there any way to disable node-webkit cache?

### ISSUE THREAD

**Issue by xuanhun** [nwjs/nw.js#2707]
I have to config the develop tool to make programs from the effects of caching.
![config](http://images.cnitblog.com/blog/42533/201411/272143167629719.jpg)

**Comment by ojde** [comment]
The fix https://github.com/nwjs/nw.js/issues/2707 has been disabled (six days later) in commit https://github.com/nwjs/nw.js/commit/4315a197f1f439707edaa1e6e7dcbcef11b7807e on Dec, 8th, 2014 and calling Window.disableCache() results in Error 
``"window_bindings.js:517 Uncaught Error: Unable to convert 'args' passed to CallObjectMethod"``

Reopen this?

**Comment by s2young** [comment]
+1

**Comment by handitan** [comment]
disableCache is accepting an array as the argument.
So do this Window.disableCache([true]) if you want to disable the cache.
