### ISSUE TITLE
How to build nw addon with dylib?

### ISSUE THREAD

**Issue by woc2006** [nwjs/nw.js#2709]
I wrote a nw c++ addon, the building.gyp is linke:

```
{
  'targets': [
    {
      'target_name': 'test',
      'sources': [ 'binding.cc' ],
      'conditions':[
            ['OS=="mac"',{
                'include_dirs':['./mac/inc'],
                'libraries':['../mac/lib/libmain.dylib']
            }]
      ]
    }
  ]
}
```

and i put both test.node and libmain.dylib under node_modules, 

but nw crashed with the error:

 "Uncaught Error: dlopen(/proj/node_modules/test.node, 1): Library not loaded: @rpath/libmain.dylib
  Referenced from: /proj/node_modules/test.node
  Reason: image not found", source: module.js (354)

Is there any mistakes in building.gyp or the dylib?
##

**Comment by Nitin2222** [comment]
I am facing same issue...is there any update?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
