### ISSUE TITLE
Application crashes when new window is opened

### ISSUE THREAD

**Issue by gleitz** [nwjs/nw.js#2713]
I'm using node-webkit to build a wrapper for Asana, which uses Google OAuth as a login option. When I try loading https://app.asana.com in an iframe in v0.8.6 for OSX, the "Log In with Google Account" button works just fine. When I try the same using v0.11.2, clicking the button (which opens a new window) causes the application to crash. I've tried using an iframe with nwdisable/nwfaketop and the problem still remains.

Here is [a sample applciation](https://dl.dropboxusercontent.com/u/101688/delete/node-webkit-test.zip) that exhibits the crashing behavior.

```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Asana</title>
    </head>
    <body>
        <iframe id="asana-iframe" title="Asana" src="https://app.asana.com" style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;">
        </iframe>
    </body>
</html>

```

**Comment by gleitz** [comment]
@rogerwang I've noticed with the latest release (v0.11.5) that the app no longer crashes, but OAuth login is not successful. OAuth login is successful in v0.8.6.

Is it possible I need to use addOriginAccessWhitelistEntry to make OAuth function properly? It appears that something changed between these two versions but I can't tell what I need to do to make OAuth work in v0.11.5.

You can reproduce this issue by using my [sample application](https://dl.dropboxusercontent.com/u/101688/delete/node-webkit-test.zip), or by simply opening the bare node-webkit and navigating to https://app.asana.com 

Thanks!

**Comment by rogerwang** [comment]
@gleitz could you please give any detail or error message for the unsuccessful oauth login? It seems that you need addOriginAccessWhitelistEntry because that's the API for, see #1908

**Comment by gleitz** [comment]
In v0.9.2 (and below), oauth works as expected. Visiting https://app.asana.com and clicking the "Log in with Google Account" button opens a popup window, logging the following messages to the console:

```
Calling gapi.auth.authorize
(credentials are entered in the popup window)
Got gapi.auth.authorize callback
Got auth response, submitting login
```

In v0.10.0 (and above), clicking "Log in with Google Account" opens a popup window, but the `gapi.auth.authorize` callback never fires.

Oauth works in Chromium 32, 35, and 38 so I believe the issue is specifically with node-webkit.

I believe I have narrowed the issue down to a problem with `new-win-policy`. Take the following [sample project](https://dl.dropboxusercontent.com/u/101688/delete/node-webkit-new-win-policy-test.zip):

```
<html>
    <head>
        <script>
            var gui = require('nw.gui'),
                win = gui.Window.get();
            win.on('new-win-policy', function (frame, url, policy) {
              console.log('opening new window ' + url);
            });
        </script>
    </head>
    <body>
        <iframe src="https://app.asana.com"></iframe>
    </body>
</html>
```

Running this code on v0.9.2 and clicking "Log in with Google Account" fires the `new-win-policy` event and logs this message to the console:

```
[INFO:CONSOLE(10)] "opening new window https://accounts.google.com/o/oauth2/auth?client_id=1032199425885.apps.googleusercontent.com&scope=email+profile+http%3A%2F%2Fwww.google.com%2Fm8%2Ffeeds%2F&authuser=&include_granted_scopes=true&proxy=oauth2relay559440497&redirect_uri=postmessage&origin=https%3A%2F%2Fapp.asana.com&response_type=token&state=418304553%7C0.2500649756&authuser=0", source: file:///Users/bgleitzman/projects/asana/node-webkit-test/index.html (10)
```

Running this code on v0.11.5 and clicking the button never fires the `new-win-policy` event, even though a popup window appears. It is as if node-webkit opens the popup window in a separate context from the parent. This may explain why the `gapi.auth.authorize` callback never fires in the parent window after credentials are entered into the oauth popup.

If the issue with `new-win-policy` not being fired for popup windows in v0.11.5 is resolved, I believe the oauth flow will also function as expected.

Thanks, and please let me know if you require any additional information.

**Comment by gleitz** [comment]
@rogerwang let me know if you require any additional information. seems the fix for `new-win-policy` may be relatively simple?

**Comment by gleitz** [comment]
Would you let me know if this `new-win-policy` bug is something that will be fixed? I'd like to know if this is something that will be addressed in an upcoming release.

**Comment by krneticz** [comment]
I'm having same issue with gapi.auth.authorize not firing callback in node-webkit (latest 0.11.x) as @gleitz . I'm using it to login users into Google Calendar and in node-webkit it does not work. 

@rogerwang is this something that you consider fixing *soon* ?

Thanks!

**Comment by gleitz** [comment]
I just downloaded the latest version of nwjs (v0.12.0) and still experience this issue. As other are having a similar problem `new-win-policy` please let me now when you believe it will be resolved.

**Comment by rogerwang** [comment]
Will fix this in 0.12.1. Thanks.

**Comment by gleitz** [comment]
Thanks Roger that's fantastic news! Please let me know if I can help in any way.

**Comment by krneticz** [comment]
Thanks Roger! Looking forward for that.

**Comment by brettpaden** [comment]
I'm looking forward to this fix, too, as are our users.  Any sense on a time frame?

**Comment by gleitz** [comment]
@rogerwang I just checked and this bug still exists in 0.12.1. It's really a pretty terrible blocker that makes the underlying application almost unusable, and there isn't any way I can see to fix it on my end because the `new-win-policy` never fires.

I know you guys are working hard. I hope this fix makes it into the next release (or at least a patch I can pull into my own branch).

**Comment by rogerwang** [comment]
@gleitz will try to fix it in this week. Thanks for your patience.

**Comment by rogerwang** [comment]
@gleitz The link to your sample code is broken in https://github.com/nwjs/nw.js/issues/2713#issuecomment-68625296 . Could you please upload it again?

**Comment by gleitz** [comment]
@rogerwang THANKS!

**Comment by krneticz** [comment]
@rogerwang Highly appreciated, thanks!

**Comment by ondra-novak** [comment]
Unfortunately i have to reopen this issue, because it doesn't work the same way as before. Now the GetWindowId fails when someone is trying to open new window to an external site from the application, or worse, if there is an iframe with an external content (a web page) and it wants to open a new window. You will receive this error in the console and no window appears:

```
Uncaught SecurityError: Blocked a frame with origin "http://www.w3schools.com" from
accessing a frame with origin "app://test".  The frame requesting access has a protocol
 of "http", the frame being accessed has a protocol of "app". Protocols must match.
```

app://test

```
<html>
    <head>
    <script type="application/javascript" src="js.js"></script>
    </head>
    <body>
        <iframe nwdisable nwfaketop   style="width: 100%; height: 100%;"></iframe>
    </body>
</html>
```

js.js
```
var qui = require("nw.gui");
var win = qui.Window.get();

document.addEventListener("DOMContentLoaded", function(event) {
    var iframe = document.querySelector("iframe");
    iframe.src = "http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open";
}
```
