### ISSUE TITLE
Frameless window "drifting" on OSX Yosemite using "-webkit-app-region".

### ISSUE THREAD

**Issue by ffdd** [nwjs/nw.js#2714]
Reproduced in this video: https://www.youtube.com/watch?v=RkhmsFzUqV4&feature=youtu.be

Could there be a timer that node-webkit is using to get the mouse position in this mode and the behavior is the result of a race condition?
##

**Comment by tphalp** [comment]
I'm seeing the same thing. OS X Yosemite 10.10.4, nw.js 0.11.6
