### ISSUE TITLE
 Change `single-instance` during runtime

### ISSUE THREAD

**Issue by majodev** [nwjs/nw.js#2729]
[node-webkit-updater](https://github.com/edjafarov/node-webkit-updater/issues/62#issuecomment-65238692) works more consistent if `single-instance` is set to `false` within the manifest. However, I'm sure certain apps want to disallow other instances of their app to be launched. 

Is there a way to change `single-instance` during runtime to `false` to temporary allow other instances of the app and then revert back?
##

**Comment by fritx** [comment]
+1. I also need to receive an cli arg to decide single-instance to be true or false.
