### ISSUE TITLE
Setting window.resizable to false does not stop re-sizing of window in Windows XP.

### ISSUE THREAD

**Issue by Joncom** [nwjs/nw.js#273]
The same packaged app.exe is not re-sizable in Windows 7 (as is desired), but in Windows XP it is. Is there any way to enforce no-resize in XP?
##

**Comment by alexandervrs** [comment]
Bug is still there with latest NW.js. Tested on Win XP SP3. The window border still can be resized.

**Comment by swfall** [comment]
I've just tested it on Linux (Xubuntu 14.04),  window is still resizable after setting window.resizable to false or calling window.setResizable(false)

**Comment by keshavbhatt** [comment]
var gui = require('nw.gui');
var win = gui.Window.get();
win.setResizable(false);

works fine on Ubuntu 16.04 (Linux)  Unity Desktop environment .

**Comment by Christywl** [comment]
Does this issue still reproduce on Windows XP? I have no Win XP device, just try it on Win 8.1, it works fine.

**Comment by Christywl** [comment]
close until there is more information
