### ISSUE TITLE
Move to io.js?

### ISSUE THREAD

**Issue by vanesyan** [nwjs/nw.js#2742]
Any plan to move to io.js instead of node.js?

**Comment by geddski** [comment]
@rogerwang is this planned for the near future or further down the road?

**Comment by rogerwang** [comment]
v0.12.0-alpha1 is released with io.js

**Comment by commadelimited** [comment]
To be clear, does this mean that "NodeWebkit" is no longer "NodeWebkit" and is now "IoWebkit"? Not trying to be obtuse, but I'd like a clear answer as I'm going to be presenting NW at a conference in May.

The description on the front page of the repo still reads "Call all Node.js modules directly from DOM". I haven't really been following along with the Node/IO split, and I don't really care about it. But I want to make sure I'm communicating the correct information.

**Comment by rogerwang** [comment]
Thanks for presenting NW. it's like 'io-blink' or 'io-chromium'. io.js remains compatible with the 3rd party modules which referred by 'Node.js modules'.

**Comment by OlivierCo** [comment]
So good news....
