### ISSUE TITLE
Will node-webkit change names?

### ISSUE THREAD

**Issue by RubrikBonnier** [nwjs/nw.js#2745]
Since WebKit has nothing to do with Chromium since a long time, should node-webkit be renamed? I think it would be a good idea. Every single person I mention node-webkit to starts lecturing me about what I already know: WebKit is not part of Chromium. It's Blink since what feels like forever.

**Comment by geddski** [comment]
Some ideas:
blend.js
JScore
CoreJS
IronCore (earths inner core is mostly iron)

**Comment by rogerwang** [comment]
http://nwjs.io
