### ISSUE TITLE
Windows: Shows blue frame temporarily when clicking blurred app

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2784]
1. Unfocused app:
   
   ![unfocused](https://cloud.githubusercontent.com/assets/1427241/5374447/5a7f7b88-8057-11e4-9e33-1241af123508.png)
   
   That top bar is draggable.
2. If I click the draggable area, I see the following: 
   
   ![blue frame](https://cloud.githubusercontent.com/assets/1427241/5374454/72e3ddd6-8057-11e4-99f4-c8eb42f9ec07.png)
   
   The top left contains the app icon & name.

---

If I click and hold, the effect is shown continuously up for up to 2 seconds and then disappears, even if I still have my mouse down on the draggable area.

If I click and drag the app, it's not shown as long as it would if I clicked and held down the mouse (without moving it). In this case it's shown about as long as it would if I just made a simple click on the draggable area.

---

node-webkit: 0.11.2.
Windows: 8.1 64-bit.
##

**Comment by sourceskyboxer** [comment]
Hi adam really I don't know that is big? Wow you create chromeless window right?  Thanks for truth. I will test. But I am using 0.12.3 and it hasn't bug right? 

Best regards Jens Eckervogt ( aka username SourceSkyBoxer )

**Comment by adam-lynch** [comment]
@sourceskyboxer I think this has been fixed in later versions. I'm using 0.12.2 and it's fine. @jtg-gg this is ok to close right?

**Comment by sourceskyboxer** [comment]
I understand. Thanks.
