### ISSUE TITLE
List of opened Windows

### ISSUE THREAD

**Issue by Wortex17** [nwjs/nw.js#2803]
Is there any way i can get a list of all currently open (chromium) windows?
I would need this e.g. for an automatic exit once the last window besides a designated "root" window is closed.

**Comment by Wortex17** [comment]
as of now, i'm trying to orient myself in my pulled nw source, to implement such api.
In the meantime, to share with everybody, there is a private container accessible over JS:
global.__nwWindowsStore

As it is undocumented it probably is not our best choice to use it in production, but seems like it cannot be THAT hard to get a hardene api call for that

**Comment by Wortex17** [comment]
global.__nwWindowsStore is insufficient, as it "oversees" windows opened through "Open as new Tab" (Middle mouse click), at leats those originating of external pages

**Comment by RIAEvangelist** [comment]
using an IPC method would be the best way to do this. Have the opened windows register with the master as well as their children.

**Comment by Wortex17** [comment]
i'm absolutely new to the chromium source and am still trying to get a grip of the structure, especially with nw's code plastered into it.
TBH my current roadblock is still to find the correct place where a new "window" (as perceived by the user) is actually created and ready to be registered. my current guess is the constructor of content::Shell in nw_shell.cc/.h. Still unsure if i unsertood the workflow of creating the Window wrappers, and if it would be a problem to generate such an instance for any/all shells (which is definitely not the case)

@RIAEvangelist sorry, i'm not sure what you mean by "with the master as well as their children."
