### ISSUE TITLE
Proxy settings and unknown crashes

### ISSUE THREAD

**Issue by swaitz** [nwjs/nw.js#2805]
Hi,

I have a question regarding the newly implemented proxy settings. 

We have a customer who uses an auto config URL which will set the config for the proxy in PAC format. But I can't connect to our node.js server which is a push service (primus with ws) via websocket. I get an error messages which states that the push service is not reachable.

I have this two functions implemented to check if the push service is available:

``` javascript
function testConnection(port, host) {
    var net         = require('net'),
        deferred    = q.defer(),
        testCon     = net.createConnection(port, host);

    testCon.on("connect", function(e) {
        deferred.resolve(e);
    });

    testCon.on("error", function(e) {
        deferred.reject(new Error(e));
    });

    return deferred.promise;
}

function checkIfFileAvailable(file) {
    var http        = new Object(),
        url         = require('url'),
        parsedUrl   = url.parse(file),
        deferred    = q.defer();

    if(parsedUrl.protocol == 'http:') {
        http = require('http');
    }
    else if(parsedUrl.protocol == 'https:') {
        http = require('https');
    }
    else {
        http = require('http');
    }

    http.get(file, function(res) {
        if( res.statusCode == 200 ) {
            var body = '';

            res.on('data', function(chunk) {
                body += chunk;
            });

            res.on('end', function(chunk) {
                var jsFile  = document.createElement('script'),
                    header  = document.getElementsByTagName('head');

                jsFile.type = 'text/javascript';
                jsFile.innerHTML = body;

                header[0].appendChild(jsFile);

                deferred.resolve(res);
            });
        }
    })
    .on('error', function(e) {
        deferred.reject(new Error(e))
    });

    return deferred.promise;
}
```

Now my question is it possible that the proxy settings are not send down to the node.js service in node-webkit so that this components won't get through the proxy?

Now to the unknown crashes...
We use the same application in our company and the application crashes on close for an unknown reason. I have finally got an mini dump file when this happens. Can someone look into it and give me some hints what goes wrong there?

I hope this link to google drive will work: https://drive.google.com/file/d/0B_qpWnk-ONPRX0JOd1c2ZC1BV1U/view?usp=sharing

If you need some more informations please let me know that.

Thanks for the support and this nice tool to create desktop apps!

Regards,
Sascha
##

**Comment by swaitz** [comment]
I was wondering if you need some additional informations regading to my bugs I have posted some time ago. If so please tell me what you need to track these issues down.

**Comment by rogerwang** [comment]
Please try the latest version. Thanks.
