### ISSUE TITLE
Crash of the application

### ISSUE THREAD

**Issue by User199011** [nwjs/nw.js#2810]
Hello,

I'm starting to develop an application using angularjs and node webkit. However sometimes the application crashes, how can I find why ? Is there somewhere some log files generated after these crashes ? (I din't find any).

When I launch my application I have at least 5 process running, is it normal ?

Thank you
##

**Comment by User199011** [comment]
@tommoor Here is the dump file, it doesn't help me a lot... http://www.filedropper.com/31e57eae-0776-4832-b3b7-cd050ce9ef23
It often happens when I log out (where i cancel all my $timeout maybe it's related ?)

**Comment by MarcFowler** [comment]
It's possible that [my suggestion over here](https://github.com/rogerwang/node-webkit/issues/2912#issuecomment-69668666) will help.. To confirm, I'm suggesting adding that code to a file (exception.js) and then adding `"node-main"` to your package.json file, pointing to that script. Then try to reproduce the error, and you should see a stack trace in the error.log file on your desktop.

I found that this helped me for when I wasn't sure on the context that the error was being thrown in and when I couldn't figure out an obscure crash.

**Comment by rogerwang** [comment]
Please try with the latest version. Thanks.
