### ISSUE TITLE
[Mac-only] Remove "Start Dictation" and "Special characters" from window menu

### ISSUE THREAD

**Issue by felicienfrancois** [nwjs/nw.js#2812]
We should be able to remove thoose menu items.
Its seems to be added in all cases to the second window menu item, whatever its name.

**Comment by Montoya** [comment]
Any update on this? I'm running into this issue over a year later...

**Comment by ghostoy** [comment]
@Montoya @felicienfrancois I made a PR #5132 which updates the menu items under `Edit` menu when setting menubar for your app. Then you can iterate the items and decide whether to remove the items or not. A new property of `nw.MenuItem` called `native` is a boolean to indicate whether they are added by native system.

For example,

```javascript
var menu = new nw.Menu({type:'menubar'});
menu.createMacBuiltin('myapp');
nw.Window.get().menu = menu;

// iterate the items under Edit
var editMenu = menu.items[1].submenu;
editMenu.items.forEach((item, i)=>{
  // remove all native items
  if (item.native) editMenu.remove(item);
});
```

If you want to keep just one, `item.label` will tell you the name of the item. Keep the one you want and remove the others. In my test, the automatically added items are actually **localized**, which is different from @felicienfrancois 's investigation. There is no way to tell the translated names for them AFAIK. So be careful when testing the names of the items if you just want to keep one.
