### ISSUE TITLE
Cookies missing with Web Sockets

### ISSUE THREAD

**Issue by bertung** [nwjs/nw.js#2819]
Cookies are not sent with Web Socket requests

**Comment by bertung** [comment]
Cookies are not sent with the request when opening the web socket which switches the protocol from http to ws. We use tomcat 7.x as the server side. It works with chrome so the link you given is irrelevant in this case.

**Comment by caomu** [comment]
we meet the same problem. when we use chrome,every thing is ok.we use netty.and we need to pass through http only cookie

**Comment by caomu** [comment]
we meet the same problem. when we use chrome,every thing is ok.we use netty.and we need to pass through http only cookie

**Comment by bgSosh** [comment]
Can confirm this issue (have confirmed server side).  Cookies are not sent during websockets upgrade request.  This makes session management impossible, rendering websockets useless for most real-world situations.

**Comment by bgSosh** [comment]
Can we remove the needinfo tag please?  (or please describe what info needed)

**Comment by komite** [comment]
I think cookie is cut off in nw, it's not a full webBrowser now

**Comment by rogerwang** [comment]
binary available: http://dl.nwjs.io/live-build/04-13-2015/154b760-0aa4273-be948af-459755a-2bdc251-1764a45/

**Comment by jarlah** [comment]
This is not fixed.
