### ISSUE TITLE
v0.10 > v0.11 - Broken mp4 direct play & youtube iframes

### ISSUE THREAD

**Issue by SwissEngine** [nwjs/nw.js#2821]
Hello,

When upgrading to 0.11 from 0.10 when I go to mp4s directly the request seems to be stopped mid transfer, causing the player to be broken. I realized this when youtube https iframes stopped working too because of "insecure" content being loaded via http.

Anyone else experienced this ? Simply try a page with a youtube iframe (https) or load a simple mp4 directly.

I'm guessing this is a Chromium issue ?
##

**Comment by ayushmxn** [comment]
Fixed in upstream
