### ISSUE TITLE
issue building on ubuntu-14.10-amd64

### ISSUE THREAD

**Issue by joiky** [nwjs/nw.js#2828]
I try to compile on ubuntu-14.10-amd64 by following the instructions.

$ ./build/gyp_chromium content/content.gyp 

Updating projects from gyp files...
gyp: Error importing pymod_do_mainmodule (grit_info): No module named grit_info while trying to load content/content.gyp

Any ideas what could be done to fix this?
Thank you very much.

**Comment by mrfabbri** [comment]
No further report, build is working fine on a ubuntu-14.10-amd64 box.
