### ISSUE TITLE
in nw0.11.2 diffrent win question

### ISSUE THREAD

**Issue by wildcatking** [nwjs/nw.js#2831]
I use nw0.11.2 work In win7，my app open two windows。one window is local page use one NPAPI, another window is remote page and use same NPAPI.
when i in local page call NPCAP method dosomething,this method need 10 min return.now this window see stopped responding ,but other window do nothing, it stopped responding  too.
how to avoid this question?

 by the way nw can provide one way create thread run NPAPI,in node can not visit NPAPI 
##

**Comment by rogerwang** [comment]
close as NPAPI has been deprecated in Chromium.
