### ISSUE TITLE
Issue with icon  for win7 and Desktop notifications

### ISSUE THREAD

**Issue by racso051** [nwjs/nw.js#2835]
Hi, I'm having troubles using desktop notifications  (https://developer.mozilla.org/en/docs/Web/API/notification), The export works perfect to MAC and windows, but when a notification is generate in windows the app crash. I found a possible bug, when I remove the attribute icon of the window field from package.json the app works fine and the notification is generated, but when this attribute is present the app crash. 

Thanks.

**Comment by sanjoc** [comment]
I have the same problem ... Any solution ??

**Comment by drikin** [comment]
I have not 100% confident yet. But it seems if Notification message string is too long, application is also crashing on windows 7. Probably it's ok on windows 8.

**Comment by ixiyang** [comment]
same problem with racso051

**Comment by racso051** [comment]
Hi xiyang, what size icon did you use?
