### ISSUE TITLE
White flash when starting app since v0.9.0; goes away after using --disable-gpu

### ISSUE THREAD

**Issue by Jrags87** [nwjs/nw.js#2837]
I have an app that starts maximized with a dark background. Every NW release since 0.9.0 when I start my app there is a quick white flash (I'm assuming something related to the hardware renderer). if I use --disable-gpu argument, the white flash does not occur, but this is not a solution for me as I need gpu acceleration. 

Also, if I update all files except nw.exe, the white flash will not occur. This leads me to believe my issue is related to a change made to the nw.exe file between v0.8.4, and v0.9.0.

I am already setting show: false in manifest, and then doing win.maximize(); win.show(); within my app.

With NW v0.8.4 and earlier the app launches perfectly without the flash.

Can this be fixed in an upcoming version? I have tested with Windows 7 and 8.1 also using Intel, nVidia, and AMD graphics cards and get the same results
##

**Comment by karlkrach** [comment]
hi, i have the same problem - slightly different however:
i do not really care about any white flashes on startup but on `window.location.reload` (so `show: false` in manifest does not do the trick). which results in a white flash lasting about a full second - which happens on mac as on pc. how can i possibly get rid of this?

**Comment by karlkrach** [comment]
hi, i just downloaded the latest version (20.2 sdk) and checked but the white flash on reload is still there - on mac as well as on pc...

**Comment by rogerwang** [comment]
merge this issue with #5502
