### ISSUE TITLE
Uniform separators (i.e. "_" vs "-") in API objects fields

### ISSUE THREAD

**Issue by mrfabbri** [nwjs/nw.js#2838]
Some fields adopts `_` as separator (e.g. max_height) while others adopt `-` (e.g. `always-on-top`).

The `_` has benefit that the property would be a valid field name in object literals (without need for quoting, I saw this recently being mistakenly reported as an issue).

This can be uniformed while providing backward compatibility for "`-`"-using fields.
- [ ] `Window always-on-top`
- [ ] `Window visible-on-all-workspaces`

Another equally valid (and maybe more JavaScriptish) solution would be using a `camelCase` convention for long name fields.
##

**Comment by sholladay** [comment]
+1 I find this super annoying. I can remember a field name and what it does and still have to look it up in the docs.

**Comment by TriBlade9** [comment]
:+1: I vote camelCase though, as I come from a Java background.
