### ISSUE TITLE
web-kit applications?

### ISSUE THREAD

**Issue by ravivrk** [nwjs/nw.js#2841]
##

**Comment by vsathyak** [comment]
@chino23 :: the link you provided is invalid. Can you please provide the correct link??

**Comment by vsathyak** [comment]
@ravivrk : Please let me know which tool you used!!

**Comment by kamijoutouma** [comment]
@vsathyak the link isn't invalid the site is just gone. https://web.archive.org/web/20141121051859/http://blog-en.leapoahead.com/post/testing-angularjs-app-in-node-webkit-with-protractor

Learn to use "the way back machine" people.

**Comment by vsathyak** [comment]
@kamijoutouma  : Thanks a lot..

**Comment by kamijoutouma** [comment]
@vsathyak np ;)
