### ISSUE TITLE
Tray menu is huge on High-DPI Windows machine

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2847]
![image](https://cloud.githubusercontent.com/assets/1427241/5520133/9934a416-896c-11e4-9fe3-f989fd0136f3.png)

In previous versions, this was fine. 

Related: #1318

**Comment by B3rn475** [comment]
Reproduces on my machine
DELL XPS 15 (3200x1800)
Windows 8.1

**Comment by adam-lynch** [comment]
Think this is ok now (0.12.0)

**Comment by mscreenie** [comment]
Working OK for me in nwjs 12.0. Consider closing for now?

**Comment by B3rn475** [comment]
I confirm that is working now

**Comment by jtg-gg** [comment]
Hi guys I've just submit the fix https://github.com/nwjs/chromium.src/commit/637a4cb938ef9fc91490ad21d279d4fd76a8417e
