### ISSUE TITLE
Setting user-agent since v0.11.0 is ineffective [$5]

### ISSUE THREAD

**Issue by charuruflex** [nwjs/nw.js#2850]
When I try to set a custom user-agent in package.json file, the user-agent detected is still the default one.

**Comment by ishirav** [comment]
+!

**Comment by rogerwang** [comment]
@CharuruFleX it works for me. Which version are you using and what's in your package.json?

**Comment by CharuruFleX** [comment]
@rogerwang my bad, it works for me too but only in pure HTTP. When I try to use websocket, no user agent is sended with v0.11. but it works with v0.10.5.

Here my package.json : 

{
  "name": "My project",
  "description": "My project",
  "version": "0.3",
  "node-remote": "*",
  "main": "http://myproject.fr/",
  "user-agent": "tatatata",
  "single-instance": true,
  "window": {
    "title": "My project",
    "show": true,
    "toolbar": false,
    "frame": true,
    "position": "center",
    "width": 500,
    "height": 190,
    "resizable": false,
    
  }
}

To check the user agent, I used wireshark with these results : 

node-webkit v0.10.5

GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: x.x.x.x:10060
Origin: http://myproject.fr
Sec-WebSocket-Protocol: sip
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: 8ggod+pwIpvl2ekdp7fgMQ==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits, x-webkit-deflate-frame
User-Agent: tatatata


node-webkit v0.11.6

GET / HTTP/1.1
Host: x.x.x.x:10060
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://myproject.fr
Sec-WebSocket-Version: 13
User-Agent:
Accept-Encoding: gzip,deflate
Accept-Language: en-US,en-us;q=0.8,en;q=0.6
Sec-WebSocket-Key: vtxtiFosAEGyP1hFaRPETA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: sip

**Comment by CharuruFleX** [comment]
I tried with v0.12.0 and got the same result.

**Comment by inoc603** [comment]
v0.12.1 encountered the same problem

**Comment by pla1** [comment]
Blank **User-Agent** on websocket http upgrade. Version 0.12.2. 
![Wireshark screenshot](http://i.imgur.com/0hlVBzL.png) 

**package.json**

    {
      "name": "Play on Kodi",
      "main": "index.html",
      "user-agent": "%name %osinfo",
      "window": {
        "width": 800,
        "height": 600,
        "toolbar": true
      }
    }

**Comment by gerwinbrunner** [comment]
I have the same issue.
Has anybody found a solution for this issue?

**Comment by bgSosh** [comment]
Custom user agent is working fine for us in 0.12.3 (but not in 0.13).

**Comment by hankbao** [comment]
It seems the custom user-agent resets to default one every time after reloading in 0.12.3.

**Comment by mato75** [comment]
It works for me in 14.5 version. In 12.3 it doesn't work.
