### ISSUE TITLE
node-webkit can only play one html5 video in an application with multiple windows

### ISSUE THREAD

**Issue by bmorwood** [nwjs/nw.js#2853]
I have an kiosk application that spawns a second window, the 'onlooker' screen that is shown on a second monitor that plays an attraction loop. When the kiosk is idle, I would like it to play the attraction loop on both screens; the issue I am experiencing is that the video only plays on either the kiosk main monitor or the 'onlooker' screen and other screen is black and does nothing, it seems this video playback issue is a race condition because which ever window loads the video first, it plays fine the other monitor is black.

any suggestions would be greatly appreciated. 
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
