### ISSUE TITLE
some chrome://components missing

### ISSUE THREAD

**Issue by mschwartz** [nwjs/nw.js#2858]
Netflix in an iframe

![](https://dl.dropboxusercontent.com/s/9oi9rjr20iojmoj/2014-12-23%20at%202.12%20PM.png)

**Comment by tommoor** [comment]
Yep, this is chrome only - we're using chromium.

**Comment by mschwartz** [comment]
Netflix works in nodewebkit-0.9.2.  Something you changed broke it :)

**Comment by tommoor** [comment]
Nope, netflix changed how they deliver video.

**Comment by mschwartz** [comment]
I have netflix running in node-webkit-0.9.2 but not the latest.

So something changed in node-webkit, too.

**Comment by Gimmeaphatbeat** [comment]
Maybe Netflix deliver content differently depending on useragent header? Has the user agent header changed?

**Comment by pi-anl** [comment]
Are you on windows/mac?
Older version of chrome use silverlight to watch netflix, if I try to watch netflix on nw 0.9.2 on my win7 box it asks me to install silverlight.

chrome/chromium post version 37 won't use silverlight however, opting for html/widevine playback. 
I believe with chromium you can manually install widevine but I haven't tried this myself, certainly don't know how to get it into nw.js

On a related note, does anyone know what's stopping nw.js from being able to show chrome://components screen?

**Comment by andrewleech** [comment]
Are you on windows/mac?
Older version of chrome use silverlight to watch netflix, if I try to watch netflix on nw 0.9.2 on my win7 box it asks me to install silverlight.

chrome/chromium post version 37 won't use silverlight however, opting for html/widevine playback. 
I believe with chromium you can manually install widevine but I haven't tried this myself, certainly don't know how to get it into nw.js

On a related note, does anyone know what's stopping nw.js from being able to show chrome://components screen?
