### ISSUE TITLE
Mac OSX Yosemite - All apps to large for window (zoomed in)

### ISSUE THREAD

**Issue by bigdavisc** [nwjs/nw.js#2863]
I have downloaded quite a few apps and even have built some simple ones. There is one glitch I am having though.

Whenever I use an app made entirely out of node-webkit (with the frameworks and such), the window is too "zoomed in". What I mean is that the content inside the programs window does not fit. (See Images Below.)

![screen shot 2014-12-25 at 2 25 01 pm](https://cloud.githubusercontent.com/assets/5247345/5554775/0e02e80c-8c42-11e4-82f0-09ff310eb1c1.png)
![screen shot 2014-12-25 at 2 25 13 pm](https://cloud.githubusercontent.com/assets/5247345/5554776/0e13d31a-8c42-11e4-9ebe-318bcbd067be.png)
![screen shot 2014-12-25 at 2 24 21 pm](https://cloud.githubusercontent.com/assets/5247345/5554777/12cce6b2-8c42-11e4-914d-818f5beb8edf.png)

I am running Mac OS X Yosemite if this makes a difference.

I hope to hear back from someone.

**Comment by tommoor** [comment]
I'm running node-webkit on yosemite both retina and standard resolution and haven't seen this one. Could you provide more details on your screen setup?

**Comment by yuters** [comment]
I have the same issue since the Yosemite 10.10.2 beta update. A way around it is to check "Open in Low Resolution" in the .app info window.

**Comment by yuters** [comment]
Sooo...
* I've connected an external display with apps opened (with low res checkbox) 
* Unchecked the low res checkbox
* Reopened one of the app (It looked fine on external display and retina)
* Disconnected the external display (The app still looked fine on the main retina display)
* Closed the app and reopened it to make sure, everything looks fine.

I don't know what caused this in the first place. Even a reboot wouldn’t solve the issue before.
