### ISSUE TITLE
Memory leak on window resize

### ISSUE THREAD

**Issue by b1rdex** [nwjs/nw.js#2866]
Detected on windows 8.1 x64 with node-webkit 0.11.4 x32 build.
Reproducible with node-webkit 0.11.3 x32 build.

Test case:
  - open nw.exe (even with no app)
  - click and hold right border of window
  - move your mouse left and right

No matter you will move mouse smooth or edgy. Speed of moving also doesn't matter. The leak will be there after 10 or more iterations.

I found that problem is possibly caused by gpu memory overflowing. Take a look at this:
![image](https://cloud.githubusercontent.com/assets/312855/5556347/2fa44eb4-8d24-11e4-8a30-9995b6b72108.png)
Look at gpu dedicated memory. Pikes represents window resising. After gpu memory is full, node-webkit starts to eat ram. This memory is freed on app close.

Just in case, my gpu is amd radeon hd 7770 series. And drivers are installed from windows update and are up to date.

**Comment by b1rdex** [comment]
Looks like fixed 0.12.0-alpha1

**Comment by robaweb** [comment]
+1 same memory leaks on window resize with nw 0.12.1
