### ISSUE TITLE
Can't display SVG images

### ISSUE THREAD

**Issue by joatoche** [nwjs/nw.js#2869]
Hello,
I decided to give nw a try earlier today, but I'm facing a problem when attempting to add a SVG image. It does not display, the broken image symbol appears. I have no problems adding .png images.
##

**Comment by RainbowDashDC** [comment]
I have this similar issue, however when trying to access it via the browser frame it renders it as XML, perhaps the wrong Content Type?

**Comment by docotronic** [comment]
Same issue. Files render correctly in browser. Seems dependent on the system environment.

**Comment by yuyat** [comment]
+1

**Comment by siqi2006** [comment]
+1,  3 years later, this issue still exists。

**Comment by rogerwang** [comment]
CC @Christywl

**Comment by Christywl** [comment]
I use the following codes and it works fine for me on Windows/Linux with nwjs-sdk-v0.25.4.
```
<!DOCTYPE html>
<html>
<body>

<svg width="100" height="100">
  <circle cx="50" cy="50" r="40"
  stroke="green" stroke-width="4" fill="yellow" />
Sorry, your browser does not support inline SVG.
</svg>
 
</body>
</html>
```
![image](https://user-images.githubusercontent.com/20039821/31702921-8fb1f100-b40c-11e7-9f98-5223f2a70b3f.png)

@siqi2006 , could you please share your codes for me to double check?

**Comment by siqi2006** [comment]
previous:       <img src='1.svg'>;  
                      it doesn't display.
now:               <div id='1'></div>
                     <script>
                    Snap.load('1.svg', function (svg) {
                         (#1).appendChild(svg.node);
                     })
                     </script>
                   display success~

**Comment by Christywl** [comment]
`img` tag works fine for me on Windows with nwjs-sdk-v0.25.4. I download the svg image from https://svgstudio.com/pages/free-sample.
```
<!DOCTYPE html>
<html>
<body>
<img src='Freesample.svg'>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/20039821/31754904-55eb1ad4-b4cd-11e7-809a-4970251ff18c.png)

**Comment by rogerwang** [comment]
close as it actually works.

**Comment by siqi2006** [comment]
@_@dizzy~~~
mine display broken pic.
it might be another reason.
i'll test it
