### ISSUE TITLE
Application crash after refresh with right button

### ISSUE THREAD

**Issue by pVesian** [nwjs/nw.js#2870]
Hi,

I'm on Win7 Pro with node-webkit-v0.10.5. I have a menu entry with trigger keys "CRTL" and "O" (Open). On first load, if I press the keys, my listener is called.
If I refresh the app using the left refresh button, and press the keys again, it works.
If I refresh the app using the right refresh button, and press the keys again, the app crashes.
I have a try/catch at the root of my app that catches every error, but here there doesn't seem to be one...

Thanks!
##

**Comment by tshinnic** [comment]
Still present under slightly different circumstances with nwjs 0.12.0 and Win7 HomePremium.

Single entry as 'menubar' menu with `key` and `modifiers` properties and a `click` handler doing a `console.log`.

Start with code "`key: 'a', modifiers: 'alt', ...`".  Run program.  Use keyboard Alt-A repeatedly and see console output repeatedly.  

**Change code** to now read "`key: 'b', ...`".  Reload with left reload button.  Use Alt-B and see console output.  **Use Alt-A and see console output!** 

Reload with right reload button.  Use Alt-B and see console output.  **Use Alt-A and see crash!**
