### ISSUE TITLE
Run node-webkit on Windows 9x / NT (Windows 95, Windows 98, Windows ME and Windows NT)

### ISSUE THREAD

**Issue by jalbam** [nwjs/nw.js#2877]
According to the specifications, node-webkit is Windows 32 bit compatible. Would it run on Windows 95, 98, ME and NT?

On the other hand, would it be possible to port node-webkit to BeOS / Haiku?

Thank you in advance.
##

**Comment by Anachron** [comment]
io.js and chronium don't support these Versions. So how can nw.js support it?

Also, it shouldnt be supported. Those operating systems are out of support for ages.

**Comment by jalbam** [comment]
It is a pity. It would be nice to see node-webkit working virtually everywhere when possible. And being out of support doesn't prevent some people from still using them.

Regarding Haiku / BeOS, it would be a great step for the community if people could create standalone web apps for so promisinng operating system.
