### ISSUE TITLE
Use of Socket.io in Node-Webkit Interferes with Inspector (Debugging)

### ISSUE THREAD

**Issue by zebulonj** [nwjs/nw.js#2882]
When I use the Socket.io client in a node-webkit application, it appears to interfere with debugging in the inspector.

Message: "Remote debugging has been terminated with reason: websocket_closed"

![screen shot 2014-12-31 at 4 49 09 pm](https://cloud.githubusercontent.com/assets/1703671/5591375/019016ba-910d-11e4-91a7-1a04ec4ae959.png)
##

**Comment by staygrimm** [comment]
I'm experiencing this same issue while using PouchDB with the latest node-webkit release.

**Comment by brandonpapworth** [comment]
I am also experiencing the same Dev Tools error, however I'm not using socket.io-client (I DO plan on it, however). I'm just using React.js and TweenMax being precompiled with Browserify. I'll look in to taking things out to see if I can find a more-direct culprit.

**Comment by brandonpapworth** [comment]
**Inlined source maps** were causing the issue for me. When I disabled the base64-encoded source map insertion that Browserify can do (when you enable "debug" in the Browserify config options), the dev tools opened perfectly.

When source maps are inlined, something like this ends up getting tossed at the end of the file:
```javascript
//# sourceMappingURL=ewogICJ2ZXJzaW9uI...
```
...and so on.

I quickly tested to see if using an external source map file would work, and, although looking at the "mapped" source js file in the dev tools inspector came up blank, the dev tools opened and functioned fine.

It appears that node-inspector has this same issue and it hasn't been resolved yet: [node-inspector issue #401](https://github.com/node-inspector/node-inspector/issues/401)

Maybe this issue runs pretty deep?

**Comment by zebulonj** [comment]
I can confirm that when I turn the inlined source maps created by Browserify off, the dev tools work as expected. Thanks, @brandonpapworth.
