### ISSUE TITLE
ctrl + click will open multiple instances of the app

### ISSUE THREAD

**Issue by dcohenb** [nwjs/nw.js#2883]
if you have a simple link in the app and you hit ctrl + click on it (open in a new window)
You will get a new instance of the app,
I'm not sure this is a native behavior you would expect from a desktop app
Any ideas on how to disable it without catching all ctrl key down events everywhere in the app?
##

**Comment by adam-lynch** [comment]
If you have jQuery, do the following: 

```javascript
$(document).on('click', function(e){
// or $('a').on('click', function(e){
    if(e.which === 2){
        e.preventDefault();
    }
});
```

Tested on node-webkit 0.11.5.

**Comment by adam-lynch** [comment]
Wait sorry, that just prevents middle-clicking links (which has the same effect). This covers middle-clicking and ctrl+click or cmd+click:


```javascript
$(document).on('click', function(e){
// or $('a').on('click', function(e){
    if(e.which === 2 or e.which === 1 && (e.ctrlKey || e.metaKey)){
        e.preventDefault();
    }
});
```

**Comment by adam-lynch** [comment]
Aaaaand I've just properly read your issue (it's late here, forgive me) :smile:....

> how to disable it *without* catching all ctrl key down events

Ah well, it's there if anyone needs it anyway.

**Comment by tommoor** [comment]
I believe you can use the new-win-policy to prevent this behaviour.

https://github.com/nwjs/nw.js/wiki/Window#new-win-policy
