### ISSUE TITLE
nw.isHidden / nw.isShown

### ISSUE THREAD

**Issue by dcohenb** [nwjs/nw.js#2884]
We have the `nw.show()` & the `nw.hide()` methods
but no indication if the app is shown or hidden

we do have this with:
`nw.isFullscreen`
`nw.isKioskMode`
`nw.isDevToolsOpen`

show `isAppHidden/Shown` seems pretty mandatory to me
any thoughts 
##

**Comment by kamesh-a** [comment]
+1

**Comment by icode** [comment]
+1

**Comment by sanemat** [comment]
:+1:
