### ISSUE TITLE
self-compiled ffmpegsumo for mkv,avi,wmv, etc

### ISSUE THREAD

**Issue by jnorris441** [nwjs/nw.js#2885]
I managed to compile an ffmpegsumo with more options included (mkv, avi, wmv, mpeg).

I have been playing with Chromium's net/base/mime_util.cc to force all mime types to be supported.

It looks like I would also have to add every specific codec I need to media/ffmpeg/ffmpeg_common.cc.

So far it hasn't worked out. I don't know too much about Chromium.

Has anyone done this? I think PopcornTime hacked theirs to play at least AVI.
##

**Comment by jakemmarsh** [comment]
A self-compiled ffmpegsumo but would be great, much better than attempting to copy the codecs from the correct version of Chrome. +1

**Comment by endorama** [comment]
+1

**Comment by tonidy** [comment]
+1

**Comment by smolleyes** [comment]
hi

i already posted some custom builds for nw 0.12 and 0.12.1 with many codecs (hevc included) for linux 32/64 osx and win here:

https://www.streamstudio.me/StreamStudio/nw12/

waiting next 0.13 to update it (if i can, very hard to do...) :p

**Comment by tonidy** [comment]
@smolleyes 

How about nw 0.12.2, currently I am using this version? Or could you give the details to build nw.js with many codecs in windows?

Thanks

**Comment by xuanhun** [comment]
@smolleyes How about win 64 version?
