### ISSUE TITLE
node-webkit page-cache always enabled on v0.11.5

### ISSUE THREAD

**Issue by micc83** [nwjs/nw.js#2889]
Hi,
Whether I set webkit -> page-cache to true or false in the manifest file when i navigate inside an iframe:

```
<iframe src="http://www.google.com" style="width: 80%;height:400px;" nwdisable nwfaketop></iframe>
```

I always find some cached data stored in the dataPath. Is that the expected behavior or something went wrong?

v0.11.5 on Mac Os X 10.0

It might be related to #2606
##

**Comment by willbarrett** [comment]
I've also experienced this on the Linux 64bit build.
