### ISSUE TITLE
prevent from window minimize

### ISSUE THREAD

**Issue by zscorpio** [nwjs/nw.js#2892]
How can I prevent from window minimize or hide minimize....

I found an issue about this and will be supported in future list.. 
##

**Comment by Wortex17** [comment]
couldn't you just restore the window in the minimize event? (Haven't tested it, could be a visible flicker)

**Comment by NanaMorse** [comment]
I've just tried the following code and it seems to work in Chrome.

```js
window.addEventListener('keydown', e => {
  if (e.metaKey && e.keyCode === 'M'.charCodeAt(0)) {
    e.preventDefault()
    alert('caught')
  }
})
```

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
