### ISSUE TITLE
Window.title does not update nw window title

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#2895]
Windows XP SP3, node-webkit v0.11.5.

When I try to change the `Window.title` property by [this API](https://github.com/rogerwang/node-webkit/wiki/Window), the nw window title changes only in the application's button on the Windows taskbar. To change the very nw window title I must do one of these window operations:

`Window.minimize(); Window.restore();`
`Window.hide(); Window.show();`
`Window.resizeBy(x, y);`
`Window.resizeTo(x, y);`

or I must do something like that manually.

Window moving does no effect.

`document.title` has the similar issue.

May be this **title update** issue and the **[active/non-active style update](https://github.com/rogerwang/node-webkit/issues/2896)** issue are somehow connected.
##

**Comment by tommoor** [comment]
Could you try changing it to a nonsense value, then immediately changing it to the value you want.

**Comment by vsemozhetbyt** [comment]
Sorry, no effect even by `setInterval` with different parameters in a function. Only the taskbar changes. I've just check in the Windows 7 SP1 and nwjs-v0.12.0-alpha1-win-ia32 — the same issue remains.

**Comment by llxwj** [comment]
Windows XP SP3,nwjs-v0.12.0-win-ia32.
I also found this problem, use the `document.title= "value";` and `require ("nw.gui").Window.get().title="value";`, are unable to update title bar immediately, only in the switch Windows application window, and then switch to the node-webkit window, only to find that the title of the content change.Should be the "value" set to memory, but no paintings to the title bar.
Chinese:只用在切换了Windows的窗口后,再切换到node-webkit窗口后,这时才发现标题栏的内容发生了变化.应该是把"value"设置到了内存,但是没有绘画到标题栏上.

**Comment by matthiasg** [comment]
this is a general issue it seems. when the application window opens up it shows node-webkit (correct icon/wrong text) [this is on Windows Server 2008 R2]. Resizing the window manually (by a pixel or maximizing) corrects it.

It seems the title refresh behavior is incorrect.

PS: It works correctly on Windows 10 64bit.

**Comment by rufushuang** [comment]
Same issue on Window 7 32bit.
Instead of setting the Window.title API, we set the title by HTML title Tag in Head section of first html page. The title keeps "node-webkit" value, and on the taskbar is correct new value.
And the title changes CORRECTLY when after an active application switch by ALT+TAB or so.

**Comment by rufushuang** [comment]
With further investigation, find out this issue is associated with Window AERO effect, or some other dynamic effect.
When turn off the dynamic effect, by setting your computer right mouse key - system - advanced system settings - visualization - settings - BEST PERFORMANCE, this issue can be re-produced.

**Comment by credomane** [comment]
Needs reopening as this issue is still present in nwjs 0.28.1.

**Comment by WolfGames** [comment]
I have the same problem.
Title always is "Listening...".
But nothing from this issue works

**Comment by morpatr** [comment]
> I have the same problem.
> Title always is "Listening...".
> But nothing from this issue works

Try this:
`window.document.title="myNewTitle"`

**Comment by haiw2** [comment]
> Windows XP SP3,nwjs-v0.12.0-win-ia32. I also found this problem, use the `document.title= "value";` and `require ("nw.gui").Window.get().title="value";`, are unable to update title bar immediately, only in the switch Windows application window, and then switch to the node-webkit window, only to find that the title of the content change.Should be the "value" set to memory, but no paintings to the title bar. Chinese:只有在切换了Windows的窗口后,再切换到node-webkit窗口,这时才发现标题栏的内容发生了变化.应该是把"value"设置到了内存,但是没有绘画到标题栏上.

same issue. i tried to set the `title` and `name`  fields in `package.json`, but did not work. Then i tried to add the js code `document.title = xxx` is successful, but this way appear the same issue that the window title can't changed immediately, only be showed after the refresh.

**Comment by haiw2** [comment]
I solved this problem, just comment the line code `<title> ... </title>` in the file `public/index.html`, then the nw app window title will show normally.
