### ISSUE TITLE
Working ffmpegsumo.dll for Chromium 38.0.2125.104 / Node-Webkit 0.11.5?

### ISSUE THREAD

**Issue by Bigmacbook** [nwjs/nw.js#2898]
Does anyone have a working ffmpegsumo.dll for Chromium 38.0.2125.104 

I can't find one anywhere. The one in Chromium 39.0.2171.95 crashes node webkit
##

**Comment by SwissEngine** [comment]
https://github.com/Soundnode/soundnode-app/blob/master/assets/codecs-libs/ffmpegsumo.dll seems to be working for me

**Comment by laraduarte** [comment]
It is not working for me. Do you have another link please?

**Comment by laraduarte** [comment]
Hi, i need the dll for the version 0.11.5 - Chromium 38.0.2125.104. anyone? Thanks

**Comment by jakemmarsh** [comment]
I get `Uncaught ReferenceError: Audio is not defined` when using the codecs linked above from Soundnode. Does anyone have working codecs or a solution for this problem?

**Comment by gunstarpl** [comment]
Here is a DLL from 64bit version of Chrome 38.0.2125.122 - http://s000.tinyupload.com/?file_id=98439818087699648975. Slightly newer than the one 0.11.5 uses but seems to be working perfectly. Source: http://nomanatif.blogspot.com/2014/11/download-google-chrome-v380-2125122.html

**Comment by jakemmarsh** [comment]
@gunstarpl what about for OSX? That's what I'm developing on, so can't test with that `dll`!

**Comment by gunstarpl** [comment]
@jakemmarsh: You have to find an offline installer for an older Chrome version (38.0.2125.xxx). Few MB download is online, 35MB+ is offline. I recommend uninstalling Chrome first and then installing the older one with your internet connection disabled, so it doesn't automatically update. Then look for OSX equelevant of the DLL file in Chrome directory. Just remember Chromium != Chrome, the former has needed codecs disabled.

Here's the first result from Google: http://infoter.blg.lt/look/Google_Chrome_38_0_2125_104/Download_Google_Chrome_38_0_2125_104__FileHippo_com/aHR0cDovL2ZpbGVoaXBwby5jb20vZG93bmxvYWRfZ29vZ2xlX2Nocm9tZS81ODk0Ny8=_blog

**Comment by jakemmarsh** [comment]
@gunstarpl I tried using the `ffmpegsumo.so` from multiple versions of Chrome downloaded [from here](http://google-chrome.en.uptodown.com/mac/old). Unfortunately, if I go any older than the current version (39.0.2171.xx), I get the `Audio is not defined` error. If I use the current version, Audio is defined but crashes when playing.

**Comment by gunstarpl** [comment]
@jakemmarsh: I am on Windows myself, so I have no idea why it won't work on OSX. Sorry.

**Comment by fcore117** [comment]
where to get dll for my 42.0.2273.0 that plays h264, 64bit

**Comment by deanshub** [comment]
for the latest nw i used the ffmpegsumo.dll within the last 41 version in [this site](http://portableapps.com/apps/internet/google_chrome_portable)
