### ISSUE TITLE
Streaming Response and WritingFile via fileStream, UTILIZES 100% cpu in Mac Maverics/Yosemite

### ISSUE THREAD

**Issue by kamesh-a** [nwjs/nw.js#2899]
Hello,
We wrote a sample file download snippet, while creating request  and piping the response to file stream, cpu utilization in MAC goes beyond 100%, Once file download is completed, node-webkit cpu usage rate reduces down to normal state.

We have tried in Windows 8, high cpu usage is not happening. 

Config Info :
Mac: Testing in both Maverics and yosemite
Engine used : 0.10.6, 0.11.x that includes latest 0.11.5 Build.

code snippet:
```
var http = require('http');
var fs = require('fs');
var path = require('path');

function download(url, callback) {

    var dest;

    if(/darwin/.test(process.platform))
        dest = path.join(process.env.HOME,'Downloads',path.basename(url));
    else if(/^win/.test(process.platform))
        dest = path.join( process.env.HOMEDRIVE, process.env.HOMEPATH,'Downloads',path.basename(url));
    else{
        console.warn('Platform is not Win/Mac');
        return;
    }

    var file = fs.createWriteStream(dest);

    var request = http.get(url, function(response) {
        
        response.pipe(file);

        var len = parseInt(response.headers['content-length'] || response.headers['x-goog-stored-content-length'], 10);
        var total = len / 1048576;
        var cur = 0;
        
        response.on("data", function(chunk) {
            cur += chunk.length;
            console.log("Downloading " + (100.0 * cur / len).toFixed(2) + "% " + (cur / 1048576).toFixed(2) + " mb\r" + " Total size: " + total.toFixed(2) + " mb")
        });

        file.on('finish', function() {
            file.close(); // close() is async, call callback after close completes.
            if (callback)
                callback('success');
        });

        file.on('error', function(err) {
            fs.unlink(dest); // Delete the file async. (But we don't check the result)
            if (callback)
                callback(err.message);
        });
    });
}

download('http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-osx-ia32.zip',function(){console.error(arguments);});

```

![cpu_112_percentage_node_webkit](https://cloud.githubusercontent.com/assets/3531949/5613610/068fa21c-950d-11e4-92b5-2a8c9646a9e3.png)

Please let us know if any way we can assist.

**Comment by kamesh-a** [comment]
@rogerwang any idea this related to hight cpu usage, i believe i have seen similar threads regarding high cpu usage.

**Comment by iwege** [comment]
Test the code on OSX 10.10.1 

Engine used : 0.11.0-ia32
CPU Usage: 10%~14%.


Engine used : 0.11.5-ia32
CPU Usage: 19%~27%

Engine used : 0.11.5-x64
CPU Usage: 9% ~ 21%

**Comment by kamesh-a** [comment]
Hello iwege,

I can give some ways of reproducing, but while developing/testing i have tried in both OS X Yosemite/Maverics. file size 30mb, Please try to download bit higher files like 100mb >. for us reproducible every time.

Even as stand-alone node-webkit application/developing along with sublime environment.
Test Environment:
node-webkit : nw 0.11.x 32bit version
Mac version : Yosemite and maverics
our Bandwidth 3 - 4mbps
```
download('http://images.sb.a-cti.com/testing/nw_v0.11.5.zip',function({console.error(arguments)});
```
Please let us know if it's not reproducible, will try to provide some examples.

**Comment by kamesh-a** [comment]
Added to it, it is reproducible to one other user who have also tested and replied through Node-webkit google forums. Please check the link.

https://groups.google.com/forum/#!topic/node-webkit/0j9xaOSbgxw

Thanks

**Comment by iwege** [comment]
I have run this testcase with  two files ( 900mb, 68mb).
Test Environment:
nw       : 0.11.5 ia32
OS X   :  10.10.1
CPU    : 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Bandwidth: 3 - 4mbps

my result:
900mb 5 times keeps 30% ~ 34% cpu usage.
68mb 2/5 reached 90%, usually 25%.

And I test this code with node 0.11.14, the cpu usage is only 4% ~ 8%.

**Comment by Solomon-m** [comment]
Hello all, 
       I have run following Node webkit build (node-webkit-v0.11.5-osx-ia32.zip) downloaded from this url (http://dl.node-webkit.org/v0.11.5/). I tried to download a file. What i found is node webkit takes more CPU usage in MAC. It goes 90 plus percentage everytime. 

![90_plus_percentage](https://cloud.githubusercontent.com/assets/8034514/5649155/c1b9c6dc-96b9-11e4-98fd-eaf321f7ef3c.png)

**Comment by kamesh-a** [comment]
@iwege Thanks for testing, Can you please share the node-webkit setup which you are using, because we have tried in engine which is downloaded from 

http://dl.node-webkit.org/v0.11.4/node-webkit-v0.11.4-osx-ia32.zip
http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-osx-ia32.zip

Attached my machine config, have upgraded OS-X just for testing purpose.

![system_os_config](https://cloud.githubusercontent.com/assets/3531949/5648959/8f8de7f2-96b8-11e4-8ecb-e781815fd306.png)
Nw 0.11.4 : 
![nw_0 11 4_1](https://cloud.githubusercontent.com/assets/3531949/5649089/53b58c5c-96b9-11e4-86f0-c5c8deb12ae7.png)
![nw_0 11 4_2](https://cloud.githubusercontent.com/assets/3531949/5649090/53c21788-96b9-11e4-8d4d-1074d516b564.png)
NW 0.11.5: we have three node-webkit helper which added to usage goes beyond 120% cpu usage.
![nw_0 11 5_1](https://cloud.githubusercontent.com/assets/3531949/5649192/fb13d788-96b9-11e4-9f56-a9610759e09d.png)
![nw_0 11 5_2](https://cloud.githubusercontent.com/assets/3531949/5649191/fb11cfa6-96b9-11e4-84e2-377daa94dab7.png)

Can you please confirm are you using the production version downloaded from the above url. but HIGH cpu usage consistently reproducible in our end

**Comment by cristianfraser** [comment]
I have this problem using `node-webkit-updater`, whenever the update is being downloaded on a Mac, CPU goes up all the way.

**Comment by rogerwang** [comment]
merge this issue with #2723
