### ISSUE TITLE
Provide toggle to disable node.js inside WebKit

### ISSUE THREAD

**Issue by zcbenz** [nwjs/nw.js#29]
Since some users are using node-webkit as their HTML5 game platform, and they don't use node.js stuff, so it could be gain to provide a toggle in manifest file to disable node.js, which would improve stability and performance.

An example could be: 

```
{
  ...
  "nodejs": false
}
```

**Comment by lalakiwe** [comment]
switches::kNoSandbox is appended to command_line in  ShellBrowserMainParts::PreEarlyInitialization() and ShellMainDelegate::PreSandboxStartup() both.
 Is it possible to be a flag to "enable" sandbox in manifest file?
