### ISSUE TITLE
Can't create a tooltip to show without hover on tray icon

### ISSUE THREAD

**Issue by Thatkookooguy** [nwjs/nw.js#2907]
When writing windows applications with system tray icons, sometimes you want to have a notificaiton on the icon with a windows tooltip.

you can't with Tray. Tooltip is only set to show on hover.

I don't know what is the equivalent on mac and linux. maybe a system notification?
##

**Comment by RIAEvangelist** [comment]
I believe you might be able to achive the same goal via web notifications :

https://developer.mozilla.org/en-US/docs/Web/API/Notification/Using_Web_Notifications
