### ISSUE TITLE
errors in node-main file fail silently

### ISSUE THREAD

**Issue by jwoertink** [nwjs/nw.js#2912]
I have my `node-main` set to a index.js file. Inside the index.js file I have a function that is appended to the `module.exports`. It seems that when there is an error inside of this file, I don't get any errors, but instead, the `process.mainModule.exports` will just return an empty object. 

Here is my index.js file

``` javascript
function displayDate() {
  var MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  WEEKDAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  var today = new Date(),
  dateString = WEEKDAY_NAMES[today.getDay()] + ', ' MONTH_NAMES[today.getMonth()] + ' ' + today.getDate() + ', ' + today.getFullYear();
  return dateString;
}

module.exports.printer = function(storeDocument) {
  var content = {
    logo: 'switch-mini.jpg',
    badgeNumber: '1200',
    guestName: 'Gunter Hanz McBaggins',
    company: 'Wintech, LLCoolJ',
    date: displayDate()
  };
  // do other stuff
};
```

When I build my app, my `process.mainModule.exports` will return `{}`. This is because I have a syntax error in my `displayDate` function. If I fix the error, then rebuild, my exports will show the `{printer: function()...`. I would expect that nw would just blow up and let me know I had the syntax error. Maybe there needs to be a special logging turned on?
##

**Comment by MarcFowler** [comment]
I haven't tried this, but I had a similar issue myself where I wasn't getting an error when I expected to. I used the following code in my `node-main`. I don't know if it will catch this or if it will be helpful but it might?

```
process.on('uncaughtException', function(error) {
  var message = '[' + (new Date()).toISOString() + '] ' + 
                error.stack + '\n' + 
                Array(81).join('-') + '\n\n';

  require('fs').appendFileSync(process.env.HOME+'/Desktop/error.log', message);

  process.exit(1);
});
```
