### ISSUE TITLE
Useragent is not send via Websockets

### ISSUE THREAD

**Issue by bachel** [nwjs/nw.js#2914]
Useragent is not send via Websockets in request header.  
You can try it here. Tested on node webkit 0.11.5.
https://www.websocket.org/echo.html
##

**Comment by Destreyf** [comment]
I can confirm this behavior, it works in Chrome and Firefox, but node-webkit 11.X and nw.js 0.12.X seem to exhibit this behavior.

I will be testing chromium later today.

**Comment by Destreyf** [comment]
I just tested with the latest nightly of Chromium (32 bit) and it is working as expected.

So this is definitely something that needs to be adjusted in node-webkit/nw.js i am currently looking through the code to see if i can spot the culprit.

It would be great to get some feedback from someone on the development team.

**Comment by robaweb** [comment]
+ 1

**Comment by robaweb** [comment]
+1

**Comment by bgSosh** [comment]
Can confirm this issue.  (Related, cookies are also missing from upgrade request : issue #2819)

**Comment by farwless** [comment]
+1

**Comment by caomu** [comment]
+1

**Comment by weikaolun** [comment]
+1

**Comment by jarlah** [comment]
Whats the point in not passing cookies/headers in ws upgrade request? Is there some underlying problems with this? I see that in #2819 there was made a commit that added more schemes for the cookie store but obviously this didnt work. Are no one looking at this issue?

**Comment by b1rdex** [comment]
This is fixed in v13. But v13 is full of other bad bugs.

**Comment by b1rdex** [comment]
Here is pull that fixed this in electron: https://github.com/atom/electron/pull/2197

@rogerwang and other devs — I know you're concentrated to bring v13. But as I tested it today it's unusable. But my app depends on this feature. Is there planned v12 "support" release?

**Comment by rogerwang** [comment]
@b1rdex what're the bad bugs in 0.13? We are eager to fix them before the beta release. There might be a 0.12 update, but it should happen after 0.13 release.

**Comment by b1rdex** [comment]
@rogerwang I wrote to google group about bugs before posting here
