### ISSUE TITLE
no Chinese characters on windows 7

### ISSUE THREAD

**Issue by lildemon** [nwjs/nw.js#2915]
![image](https://cloud.githubusercontent.com/assets/314119/5677315/7743f3ea-981f-11e4-9e82-7954fd8fda1c.png)

The same problem doesn't occurred on windows 8

**Comment by lildemon** [comment]
thanks! that actually worked, but I wonder why

**Comment by UsernameLoading** [comment]
DirectWrite is an experiment feature in chromium, which is used for font rendering in Windows, and you can find this feature in  chrome if you enter chrome://flags into the browser’s address bar. But there seems to be some problem with Chinese characters in windows7 after it was enabled by default in chrome 37.

**Comment by tommoor** [comment]
great solution :)
