### ISSUE TITLE
MP3 patent expiry

### ISSUE THREAD

**Issue by ijcheung** [nwjs/nw.js#2919]
According to Wikipedia, "MP3 decoding may be patent-free in the US by September 2015". Is there any consideration for adding mp3 support into the project when the time comes?

**Comment by RIAEvangelist** [comment]
Playing MP3s is already supported by web audio elements and javascript.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video

**Comment by tommoor** [comment]
@ijcheung when the time comes it will be considered :)
