### ISSUE TITLE
Gap between app and bottom edge of screen when maximized

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#2921]
This is a screenshot from Windows 7 where the app is placed on a screen without a taskbar and maximized.

![untitled](https://cloud.githubusercontent.com/assets/1427241/5691920/07698672-98d6-11e4-8099-d64210348142.png)

(The red lines were added by a user)

This is a screenshot from Windows 8.1. Weirdly, there seems to be a border before the gap too. i.e. the actual Windows application border / frame. Keep in mind, my app is frameless and transparency is not enabled.

![image](https://cloud.githubusercontent.com/assets/1427241/5691910/d0beed9c-98d5-11e4-9b0e-67d4a669c801.png)

---

Might be related to #2374 but I doubt it.

**Comment by adam-lynch** [comment]
To be clear, this is what the bottom of my app looks like when not maximized (with my wallpaper behind):

![image](https://cloud.githubusercontent.com/assets/1427241/5691935/72b555fa-98d6-11e4-99e5-51f789f2cacb.png)

**Comment by adam-lynch** [comment]
As I said in #3290, this causes the resize cursor to be shown as well (in Windows 8) when moving your mouse over the bottom edge of the app touching the taskbar.

I disabled the *show taskbar on all screens* setting and maximized it. This is what I saw (while using Window's Magnifier):

![untitled](https://cloud.githubusercontent.com/assets/1427241/6814549/8223ca14-d277-11e4-8e02-37e646cc16f8.png)

The light grey border is noticeable.

We're now using 0.11.6, not sure which version the original report was based on to be honest.

**Comment by cmosespl** [comment]
I'm also experiencing the same problem with frameless window when maximized. Problem exists even on second (and third) monitor where is no taskbar. Just 1px tall gap on the bottom of app with vertical resize cursor.

OS: Win 7.
NWJS: 12.0, 12.1, 12.2

screenshot (see red line)
![err](https://cloud.githubusercontent.com/assets/12611018/7813346/6c40f8ec-03ba-11e5-984c-c99fe03845d0.png)
