### ISSUE TITLE
Make Node-Webkit use less memory using switches

### ISSUE THREAD

**Issue by firebbs** [nwjs/nw.js#2922]
I developing programm that will open a lot of windows. That programm consumes a lot of memory, because node-webkit itself used switch *--process-per-tab*. Is it possible to start app with switch *--single-process*, *--process-per-site* or *--process-per-site-instance* ?

**Comment by gunstarpl** [comment]
https://github.com/rogerwang/node-webkit/wiki/Manifest-format#chromium-args

**Comment by tommoor** [comment]
@firebbs looks like your question has been answered, chromium args is the way to go.
