### ISSUE TITLE
Logo improvement suggestion

### ISSUE THREAD

**Issue by iclanzan** [nwjs/nw.js#2931]
Since the name of the project is NW.js, wouldn’t it make sense for the compas to be pointing north-west?

**Comment by edi9999** [comment]
Funny +1

**Comment by jayrhynas** [comment]
As taeric [pointed out on HN](https://news.ycombinator.com/item?id=8888743), compass needles always point north, so the logo as-is is already facing NW.

**Comment by iclanzan** [comment]
My bad @jayrhynas, you are totally right.
@edi9999 funny indeed.
