### ISSUE TITLE
[0.12.0-alpha1] ReferrenceError in native module function createWritableDummyStream

### ISSUE THREAD

**Issue by felicienfrancois** [nwjs/nw.js#2933]
When I use [connect](https://www.npmjs.com/package/connect) module to create a simple static server, I get the following Error:

```
Uncaught ReferenceError: stream is not defined
   createWritableDummyStream (node.js:478)
  (anonymous function) (node.js:573)
  (anonymous function) (.../connect/node_modules/debug/node.js:478)
  ...
```

The `node.js` file where the errors occurs seems to be the native library. I can see the source code with dev tools:
```javascript
476  function createWritableDummyStream(fd) {
477    var DummyStream = NativeModule.require('dummystream');
478    stream = new DummyStream();
479    stream.fd = fd;
480
481    stream._isStdio = true;
482
483    return stream;
484    
485  }
```

And the stream variable seems to be lacking a declaration (`var` keyword)
I don't know if it's part of the io.js release used in nw.js as I have not found these line of code in there repository.

**Comment by felicienfrancois** [comment]
When making a google search with "createWritableDummyStream", I get only one result wich is node-webkit related: https://github.com/trevorlinton/node/blob/2449080cc25eb91d6c171471e69ddf1412db696c/src/node.js#L484

The code is not exactly the same (not the same line numbers) but still have the missing declaration

**Comment by rogerwang** [comment]
I'm trying to reproduce it to confirm my local fix, but could reproduce the error with the sample from the official page of the module. Could you please provide a simple case?

**Comment by felicienfrancois** [comment]
I'm able to reproduce it with the following code:

	var connect = require("connect");
	var servestatic = require("serve-static");

	var server = connect();
	server.use(servestatic("some/path"));
	server.listen(8000); // or any other port

**Comment by madfox** [comment]
try
```js
require("child_process").exec("uname");
```
node.js file running at strict mode in nwjs 1.0 !!!

**Comment by rogerwang** [comment]
fix available from here: http://dl.nwjs.io/live-build/01-16-2015/3f3500b-0962e6a-b477a2d-2e978ac-1116f2c-fd87c8d/
