### ISSUE TITLE
IO.js & production apps

### ISSUE THREAD

**Issue by RIAEvangelist** [nwjs/nw.js#2937]
Is the upcoming switch to IO.js going to effect stability.

I have read several articles on it now all praising it from a developer standpoint, yet clearly stating it is not ready for use in production.

I plan on using NW in production applications in regulated industries. Having an unstable application would be very bad for me. 

Could you address the stability concerns for me?

**Comment by rogerwang** [comment]
Hello, currently the stable versions are 0.11.5 and 0.8.6. There will be still several 0.11 releases before the final 0.12 release.

**Comment by RIAEvangelist** [comment]
What are your thoughts on the stability of io.js when 0.12 comes out? The apps we are building will be available for a long time to come. I do not want to get stuck on an old nw.js version

**Comment by gyzerok** [comment]
@rogerwang currently 0.8 is a long term support version, right? Is there any thoughts about new long term support version?

**Comment by rogerwang** [comment]
@gyzerok yes. 0.8 is maintained for stable Node.js 0.10

@RIAEvangelist we'll release stable nw v0.12 when both io.js & Chrome 41 become stable

**Comment by RIAEvangelist** [comment]
@rogerwang is io.js planned to become stable? From what I understand it is planned to always be on the bleeding edge right?

I guess I'll have to wait and see.

**Comment by rogerwang** [comment]
It will follow new V8 releases closely as Chrome. I guess that is received as "bleeding edge".
