### ISSUE TITLE
Can not write file as zipped app.nw 

### ISSUE THREAD

**Issue by leijing7** [nwjs/nw.js#2940]
```
var jf = require('jsonfile');

jf.writeFile("./setting.json", newSettings, function(err) {
    if (err){
        console.log("writing file err: ", err);
    } else {
        console.log("setting saved successfully.");
    }
});
```

Above code reports successfully in both development (npm start) and distribution (zip to app.nw and put it in node-webkit.app Resources dir), but only the file in development changed. I dont know why. Have tried utf8 and base64 encoding, both of them are the same.

Or is there a way to get around it? Like put the setting.json file somewhere else?

I tried to use PouchDB. The same thing happened. It works in development, but once I put app.nw in the resource, the changes can not be saved. 

Looks like in a sandbox? How would I save data in node-webkit?
##

**Comment by xqwzts** [comment]
I think this is a pathing issue?

Try replacing `./setting.json` with `path.join(path.dirname(process.execPath), 'setting.json');`
