### ISSUE TITLE
Does't support added c++ for Node-webkit 0.11.5?

### ISSUE THREAD

**Issue by slikel** [nwjs/nw.js#2943]

**Comment by slikel** [comment]
![aaa](https://cloud.githubusercontent.com/assets/10388222/5756513/67113aac-9ceb-11e4-9527-b64220691577.jpg)
![b](https://cloud.githubusercontent.com/assets/10388222/5756526/8d509d3e-9ceb-11e4-8d36-0a4754198407.jpg)

**Comment by tommoor** [comment]
These seem like syntax errors in your code.

**Comment by slikel** [comment]
Thank you for the reply!
I perform 'nw-gyp configure --target=0.8.6' and 'nw-gyp build' is successful,but 'nw-gyp configure --target=0.11.5' and 'nw-gyp build' was a failure.

**Comment by rogerwang** [comment]
The module uses API from a old version of V8. So it's supposed to be supported only by 0.8 branch.
