### ISSUE TITLE
What is the purpose of the download link on the website?

### ISSUE THREAD

**Issue by jorisw** [nwjs/nw.js#2944]
When I download Version 0.12.0-alpha1, what am I supposed to do with the .app inside? Even in the Package Contents of the .app I don't see anything to work with.

What I expected to see was a boilerplate folder of a framework and possibly a set of libraries, accompanied by docs, to start work on a NW.js project.

**Comment by iamphill** [comment]
https://github.com/nwjs/nw.js#quick-start helpful?

Last time I built an app I used https://github.com/mllrsohn/grunt-node-webkit-builder but not been updated to NW.js yet.
