### ISSUE TITLE
emoji not support

### ISSUE THREAD

**Issue by zscorpio** [nwjs/nw.js#2945]
It seems that emoji is not support?

**Comment by tommoor** [comment]
Please provide more details? Where are you referring to? What do you expect to see, what do you actually see?

**Comment by tonypee** [comment]
emoji is not supported in chromium - therefore not in node-webkit (bing). It might be coming soon 
https://code.google.com/p/chromium/issues/detail?id=62435

or replace emojis with images (or fonts) in js: 
http://www.emojione.com/

**Comment by zscorpio** [comment]
o~thx,I typed emoji in <div> or in a textarea,in chrome,it is ok,so i think that node-webklit will support
then i will use image replace
