### ISSUE TITLE
Uncaught Error: The specified module could not be found

### ISSUE THREAD

**Issue by slikel** [nwjs/nw.js#2951]
I use the node-webkit version is 0.8.6.
I carried out the following command, received a app.exe:
```javascript
copy /b nw.exe+app.nw app.exe
```

Then I run the app.exe,then appeared the following error:
```
Uncaught Error: The specified module could not be found.
C:\Users\ADMINI~1\AppData\Local\Temp\nw28072_22654\node_modules\hello.node 
```
Please help me.

**Comment by rogerwang** [comment]
you should pack the module with your app as well

**Comment by slikel** [comment]
my app contains the module file.
app.nw structure is as follows
![a](https://cloud.githubusercontent.com/assets/10388222/5772665/fbe044a2-9d90-11e4-8510-42215541fde9.png)

```javascript
 var tmp = require('hello');
 console.log(tmp.hello());
```

**Comment by tommoor** [comment]
I believe each module should have it's own folder, package.json etc - make sure you stick to the conventions.

**Comment by slikel** [comment]
you are right.i should stick to the conventions,but the problem still there

**Comment by sword36** [comment]
Your .exe file should be called "nw.exe"

**Comment by wadecha** [comment]
why must be called "nw.exe",  I met this problem too, if I change .exe file nw.exe, it work well, else not. if I want to rename .exe file, how can I do?

**Comment by slikel** [comment]
Sorry,I have no solution

**Comment by slikel** [comment]
@wadecha 
Sorry, I have no solution.This may be a design flaw

**Comment by wadecha** [comment]
I have solved.
https://github.com/nwjs/nw.js/issues/199 have solution, and someone write a patching in http://developers.ironsrc.com/rename-import-dll/ this website

**Comment by slikel** [comment]
Good.Thanks

**Comment by slikel** [comment]
@wadecha 
Good. Thanks
