### ISSUE TITLE
nwjs - ReferenceError - Debugging with Sublime Text 2

### ISSUE THREAD

**Issue by shichon64** [nwjs/nw.js#2958]
Hello,

I'm using Sublime Text 2.0.2 build 2221 and I have followed the guide [`Debugging with Sublime Text 2 and 3`](https://github.com/nwjs/nw.js/wiki/Debugging-with-Sublime-Text-2-and-3) (my OS : Windows 7 x64).

I have an empty HTML page with a ```<script>``` tag with inside ```var a = require('gulp');```.
Every time I make a build, with nwjs v0.12.0-alpha1 referenced for "path", it throws an error `Uncaught ReferenceError: stream is not defined`.

I tried to load others modules than Gulp :
* grunt : same error.
* proxy : no error.
* request : no error.

But when I set node-webkit v0.11.5 for "path", the app starts correctly, without error, for any modules.

**Comment by shichon64** [comment]
Maybe a duplicate of [#2933](https://github.com/nwjs/nw.js/issues/2933) ...

**Comment by ghostoy** [comment]
The stream issue is fixed. Could you check with latest live build http://dl.nwjs.io/live-build/01-16-2015/e0d5ce6-0962e6a-b477a2d-2e978ac-1116f2c-fd87c8d/ ?

**Comment by rogerwang** [comment]
merge with #2933
