### ISSUE TITLE
-webkit-app-region: drag; stopped working in version 0.12.0-alpha1

### ISSUE THREAD

**Issue by rodrigopandini** [nwjs/nw.js#2963]
Seems that

```css
-webkit-app-region: drag; 
```
stopped working in version 0.12.0-alpha1 on Windows 7 - 32bits.

#2952

**Comment by rogerwang** [comment]
released in 0.12.0-alpha2

**Comment by oknoorap** [comment]
I download from http://dl.nwjs.io/v0.12.0-alpha2/nwjs-v0.12.0-alpha2-win-ia32.zip
still not working

**Comment by rogerwang** [comment]
@oknoorap I tested it with the frameless app in the samples repo. If it's not working for you, please provide a case. thanks.

**Comment by oknoorap** [comment]
if in package.json, window toolbar set as true, it's not working anymore, but if false, it works.

**Comment by rogerwang** [comment]
currently the toolbar is not supposed to work in frameless window.

**Comment by oknoorap** [comment]
@rogerwang but version 0.8 support frameless window with toolbar (drag feature also works), this is useful when i need to debug app by clicking developer tools button, btw, i'm still using 0.8 right now.
