### ISSUE TITLE
Developer Window

### ISSUE THREAD

**Issue by PewienTyp** [nwjs/nw.js#2965]
Please add paste and copy option in developer console.

**Comment by ghostoy** [comment]
Duplicate of #2660. Please try this link http://dl.nwjs.io/live-build/01-17-2015/be29028-d8ecacd-9a15a52-f2f89e2-d9a9d39-cdd879e/.

**Comment by PewienTyp** [comment]
Copy and paste in rigth click menu

**Comment by ghostoy** [comment]
Does `ctrl+c` and `ctrl+v` work for you?

**Comment by jakehh** [comment]
If you're on OS X, adding a App Menu worked for me (adds the cmd+c/cmd+v shortcuts)

**Comment by PewienTyp** [comment]
ctrl+c and ctrl+v works but this menu will be usable
