### ISSUE TITLE
copy local file to clipboard 

### ISSUE THREAD

**Issue by zscorpio** [nwjs/nw.js#2966]
I copyed a localfile from a folder.
Will it be able to get the file in node-webkit?
I only get this![image](https://cloud.githubusercontent.com/assets/1071075/5788800/3d1f6d80-9e86-11e4-962d-a800279aebba.png)
##

**Comment by tommoor** [comment]
I believe this is a restriction of the HTML5 clipboard API in chromium.

**Comment by zscorpio** [comment]
Is there any mac api can nodejs get from?just like 

osascript -e 'display notification '

**Comment by tommoor** [comment]
I believe you'd have to use an 'open file' type dialog unfortunately.

**Comment by zscorpio** [comment]
yes,I just copyed local  file and then paste on node-webkit.
But in a normal app.It can show the real pic

**Comment by RIAEvangelist** [comment]
you could use the node fs read.

What does the clipboard actually contain? I assume it will have the file path.

**Comment by zscorpio** [comment]
It seems there is no file path....
