### ISSUE TITLE
Weird svg clipping/repainting

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#2969]
1) Use the attached index.html as the main page for a node-webkit app
2) when nw starts, make the window smaller than the svg so that scrollbars appear
3) Adjust the window scrollbars to show the bottom right corner of the svg
4) move the mouse around on the document and watch the black rectangle.  It should simply follow the mouse.
- On node-webkit v0.8.6-linux-ia32, the black rectangle follows the mouse motion
- On node-webkit v0.11.5-linux-ia32, the black rectangle randomly gets clipped and/or gets stuck and doesn't repaint properly
- On nwjs-v0.12.0-alpha1-linux-ia32, I can't be sure whether it works or not because document.onmousemove erroneously binds to left-click of the mouse!
- just for reference-- On atom-shell-v0.20.6-linux-ia32, the black rectangle follows the mouse motion

Unfortunately I don't have a standalone version of Chromium to compare to 11.5.  But the atom-shell I tested uses Chromium 39.
##

**Comment by ghostoy** [comment]
Please attach the test app.

**Comment by jonwwilkes** [comment]
<html>
<head>
</head>
<body>
<svg height="1000" width="1000">
<rect id="foo" x="20" y="20" height="20" width="60"/>
</svg>
<script>
document.onmousemove = function() {
  var rect = document.getElementById("foo");
  rect.setAttributeNS(null, 'x', event.pageX);
  rect.setAttributeNS(null, 'y', event.pageY);
}
</script>
</body>
</html>

**Comment by jonwwilkes** [comment]
I think the code above should be enough to show the problem.

I tested on Debian testing (Jessie) 32bit.

**Comment by jonwwilkes** [comment]
Not sure why it is tagged with "needinfo"-- the example code above should be enough to show the problem.

**Comment by jonwwilkes** [comment]
Bug is also present on Windows 7 Professional (64-bit).

**Comment by jonwwilkes** [comment]
This bug does not happen on Windows 7 when using Version 0.12.0-alpha2.  It's possible that I'm using software rendering on the machine running GNU/Linux-- I'll try to test on a different distro later.

**Comment by rogerwang** [comment]
close until more information is available.
