### ISSUE TITLE
Taskbar context menu is not working in windows

### ISSUE THREAD

**Issue by b1rdex** [nwjs/nw.js#2971]
How to reproduce:
  1. Open nw.exe
  2. Right click nw icon in taskbar

Result: nothing happens
Expected: windows context menu with pin, close and so on

NW.js v0.12.0-alpha2 x32 on Windows 8.1 x64

**Comment by tommoor** [comment]
Could you confirm if this is a regression, please try some earlier builds.

**Comment by yuchuan1** [comment]
Tried on my environment.
NW.js v0.12.0-alpha2 x32 on Windows 8.1 x64
Context menu was shown as expected. Plz see below.
![untitled-3](https://cloud.githubusercontent.com/assets/684074/5890503/537d5f1a-a499-11e4-8d0a-57b8533b07e2.png)

**Comment by b1rdex** [comment]
Looks like it was problems with my windows, working good on second computer.
