### ISSUE TITLE
Documentation Project

### ISSUE THREAD

**Issue by tommoor** [nwjs/nw.js#2972]
I'd like to suggest moving the documentation from a freely editable wiki to github pages with jekyll that works as a standalone site. We could map it to docs.nwjs.io very simply too.

I'm happy to take the lead on this and get a framework in place so that other stakeholders can get a feel for how this would work before going too far...

This would also give us the big advantage of having documentation under source control. We could also require that pull requests to the main project include a corresponding PR in the documentation where it makes sense.

/cc @rogerwang 
##

**Comment by overlords** [comment]
＋1

**Comment by ePirat** [comment]
What about using https://readthedocs.org? It offers already a very nice styled layout which is easy to use.

**Comment by rogerwang** [comment]
close as it's been moved to git and readthedocs.org.
