### ISSUE TITLE
snapshot in new nw.js 0.12

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#2974]
Hi,

thanks first of all to constantly moving this amazing project forward. I have 2 questions:

1. In the 0.12 download I don't see a snapshot binary, will this be included once the 0.12 is out of alpha? This is the most important feature for me.
2. Given that the v8 has been majorly updated now, will that fix some of the snapshot problems that come with big files? This size limit has been an issue for me, always. 

Any answer is greatly appreciated! Keep up the great work guys!

**Comment by rogerwang** [comment]
It will be included before the final release. But we'll need longer time to fix the limitations.

**Comment by chino23** [comment]
Thanks @rogerwang, looking forward to that!

I'd really appreciate it if at some point the size limitations could be improved, but I understand it's a bit more difficult. :)
