### ISSUE TITLE
App freezes (it worked a week ago)

### ISSUE THREAD

**Issue by dpaloucva** [nwjs/nw.js#2978]
Hi,

I have a single page app built with Node-Webkit. This app worked fine the last time I built it (like a week ago). Today I built a new version and I found that the app is not working at all. I had to add the following line to my Gruntfile options to be able to build it using grunt-node-webkit-builder:

downloadUrl: 'http://dl.nwjs.io/'

I tested it in a Mac OS X 10.9.5, a Mac OS X 10.7.5 and a Windows XP and the result is the same in all of them. The first view is rendered fine, but if I try to navigate to another view (I replace the body's html code with the new one using jQuery) the app freezes and I become unable to click anything or even close my app (I have to kill it). 

I'm using the same NW version as the last build: 0.10.5. I also tried using 0.11.5 but the error is still there. The same code works like a charm in a PhoneGap app. 

How can I solve this?

Thank you.

**Comment by ghostoy** [comment]
Please add your app to reproduce the issue. And what's the working version for you?

**Comment by dpaloucva** [comment]
Reviewing the code I've seen that a co-worker added some JS code, and that code was the cause of this issue. Sorry for opening this issue, I close it now.
