### ISSUE TITLE
localStorage and sessionStorage unaccessibles

### ISSUE THREAD

**Issue by skol-pro** [nwjs/nw.js#2984]
I get an error when trying to access localStorage or sessionStorage :
**Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.**
**Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.**

I didn't find anyone anywhere talking or asking help regarding this issue.
##

**Comment by biggbest** [comment]
Related to this: code.google.com/p/chromium/issues/detail?id=304828
So I'm facing this issue right after opening the devtools, that redirect me to a data:text/html error page (node-webkit page). Wondering why I'm the only one reporting those 2 "events" with node-webkit.

**Comment by tommoor** [comment]
This isn't an error, this is a 'feature' of chromium. The question is why is your app going to an error page?

**Comment by biggbest** [comment]
Let's explain the steps:
- I open up my nw application, landing on my index.html page, everything works well
- I click on the devtools button, bang, error page
    => **TypeError: Cannot read property 'Window' of undefined at <anonymous>:1:18**
- I click back button. After less than a second on my index.html, it shows me the above error
    => **Error: Failed to execute 'getItem' on 'Storage': access is denied for this document. at Error (native)**

**Comment by danschumann** [comment]
I'm getting this too, when I listen to callbacks on Window resize, restore, maximize.  It seems like it has a different global context when calling functions from those callbacks.  Ring any bells?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information

**Comment by danschumann** [comment]
Pretty sure I had a case where it appeared and left my notes in case it happened to someone else, but.. it seems like someone deleted it?  Weird.
