### ISSUE TITLE
How to print?

### ISSUE THREAD

**Issue by loveencounterflow** [nwjs/nw.js#2986]
I'm looking for a way to output a page rendered in nw.js as a PDF, like what you get in the print dialog under OSX (preview / save as PDF). However i can't figure out how to print at all, it's mentioned in issues and on the mailing list, but nowhere in the wiki.

* is it possible to print the contents of a nw.js window? if so, how?
* is there a print preview dialog?
* is it possible to print silently to a file?

**Comment by Gimmeaphatbeat** [comment]
+ if it IS possible to silently print, is it possible to print to a certain printer name, rather than the default?

**Comment by felicienfrancois** [comment]
You can do it with a node module https://github.com/tojocky/node-printer

**Comment by filipinascimento** [comment]
It would be nice to have a way to render the page or a set of elements to PDF (and maybe other formats) without requiring the use of the featureless window.print() function. An example case: data analysis and visualization app (for instance, using d3.js) that exports the PDF of some elements, so we can use them as figures on a scientific papers. HTML5+d3 is an awesome combination for creating interactive and data exploration apps, this is far more advanced than many static tools for other programming languages such as matplotlib and matlab/scilab/R. Please consider this on the next versions. Thanks.

**Comment by jamalkhan2k6** [comment]
You can just use a command line html printers like:
http://www.printhtml.com

**Comment by rogerwang** [comment]
This is now supported. See #4911 #5036
