### ISSUE TITLE
Unable to drop files to tray icon on OSX

### ISSUE THREAD

**Issue by marcfowler** [nwjs/nw.js#2995]
I've packaged up my app into an .app file using [node-webkit builder](https://github.com/mllrsohn/grunt-node-webkit-builder), and I've then gone through and edited my .plist file to allow support for all documents.

```
<key>CFBundleDocumentTypes</key>
<array>
    <dict>
        <key>CFBundleTypeName</key>
        <string>Video</string>
        <key>LSHandlerRank</key>
        <string>Alternate</string>
        <key>LSItemContentTypes</key>
        <array>
            <string>public.content</string>
        </array>
    </dict>
</array>
```

I've added the `public.content` type to allow anything, but I also tried `public.audiovisual-​content` too.

I'm able to drop files onto the .app file itself with no problems - I get my alert with the path that's been dropped on just fine with this simple code to test:

```
gui.App.on('open', function(cmdline) {
  alert('command line: ' + cmdline);
});
```

However, I also launch a tray icon by using:

```
var tray = new gui.Tray({
    'icon': './icon.png'
});
```

I was expecting that I'd be able to drop files onto this as well, like you can with things like Jumpshare etc, but no luck. I see that this was [referenced before](https://github.com/nwjs/nw.js/issues/1894) and more relevantly, [here](https://github.com/nwjs/nw.js/issues/162) but it was explained to add the `UTExportedTypeDeclarations` key to the .plist. However, I'm not using custom file types - I want people to be able to drop, for example, PNG and JPG or MP4 and AVI files.

Am I even editing the correct .plist file?

Any help would be greatly appreciated!

(To confirm, I'm using OSX **10.10.1** and node-webkit **0.11.5**).
##

**Comment by MarcFowler** [comment]
Does anyone have any ideas on this? I've not been able to get this working at all! I can't seem to find any actual examples of how this is done :(

**Comment by maxhoffmann** [comment]
Also bumped into this issue on **10.10.2** and nwjs **0.12**. Can’t make dropping a file on the dock icon work.

My steps:

1. Converted app folder to nw executable with `zip -r ../${PWD##*/}.nw *`
2. Renamed the file to `app.nw` and put it inside of `Contents/Resources` of the `nwjs.app`
3. Added this to to `Contents/Info.plist` inside of `<array>` under the `CFBundleDocumentTypes` key:

```xml
<dict>
	<key>CFBundleTypeName</key>
	<string>Images</string>
	<key>LSHandlerRank</key>
	<string>Alternate</string>
	<key>LSItemContentTypes</key>
	<array>
		<string>public.image</string>
	</array>
</dict>
```

**Comment by MarcFowler** [comment]
I've had no luck getting it to work either. Really not sure where the issue lies unfortunately!

**Comment by maxhoffmann** [comment]
I just tried reproducing the steps I wrote down with a new copy of `nw.js`. Dropping on the dock icon now works for me.

**Comment by MarcFowler** [comment]
I still couldn't get this working. Could you post an example of your full .plist file so I can check if I'm in the right place @maxhoffmann?

How are you registering it as a tray app too? I don't suppose I could trouble you for a quick demo could I? Tearing my hair out on this one!!

I'm now on nwjs 0.12 as well but still no luck.

**Comment by maxhoffmann** [comment]
Sorry, dropping on the dock icon works for me, not on the tray. I’m not sure if native OS X apps support this?

**Comment by MarcFowler** [comment]
Yes, definitely they do - Dropbox, Jumpshare, Copy etc all handle it as quick examples. Sorry if I wasn't clearer, it does work via the dock and via the app itself but I particularly want it on the `gui.Tray` instance.

@rogerwang do you know if this is something that's possible? It was discussed in https://github.com/nwjs/nw.js/issues/1894 and it would be really great to have this!
