### ISSUE TITLE
devtools doesn't stop at breakpoint in node context in 0.10.x & 0.11.x & 0.12-alpha2

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#2996]
When breakpoint is set to the code which is immediately invoked within or after `require()`, devtools doesn't stop at the breakpoints. But adding a "debugger" statement works.

For example, set breakpoint in the first line of `test.js` and execute `require('./test')`. Or set breakpoint in function `hello()` in `test.js` and execute `require('./test').hello()`. In both of the two cases, devtools will not break at the breakpoints.

This issue does not exist on 0.8.x. So it's a regression.

**Comment by ghostoy** [comment]
Sample1: **index.html**
```html
<script>
function test() {
  require('./test');
}
</script>
```

**test.js**:
```javascript
// set breakpoint below, but devtools doesn't stop here
console.log('test.js loaded');
debugger; // devtools will stop at debugger statement
console.log('test.js continue');
```

**Comment by ghostoy** [comment]
Sample2: **index.html**
```html
<script>
function test() {
  require('./test').hello();
}
</script>
```

**test.js**:
```javascript
exports.hello = function(){
  // set breakpoint below, but devtools doesn't stop here
  console.log('test.js loaded');
  debugger; // devtools will stop at debugger statement
  console.log('test.js continue');
};
```

**Comment by Phoenixmatrix** [comment]
Looks related to #2668, but your repro steps are clearer. I have the same issues: breakpoints work perfectly in 0.10.5, devtools seemed broken in 0.11.5 so I couldn't test those. The issue above occures in 0.12.

**Comment by astoilkov** [comment]
+1 for the issue...experiencing the same problem it is just not possible to develop when you can't debug the code

**Comment by Phoenixmatrix** [comment]
Yeah, i'm actually wondering if people use some kind of workaround. Seems like a lot of people using 0.11.x, but I can't see how they would without module debugging.

**Comment by Phoenixmatrix** [comment]
Some additional info.

Testing with 0.11.6 (since the changelog said it had a lot of bug fixes). 

If I put a debugger statement or a breakpoint after my app load, my breakpoint gets hit ONCE. Then never again. If I then -refresh- (using the refresh button with toolbar enabled), my breakpoint then work consistantly, 100% of the time, including resuming/closing devtool, reopening, etc.

**Comment by rogerwang** [comment]
available in live build: http://dl.nwjs.io/live-build/02-20-2015/fbb9040-4aad9fe-be948af-add523e-2bdc251-c114bb7/

**Comment by ghostoy** [comment]
@rogerwang The build didn't fix the issue.

**Comment by rogerwang** [comment]
@ghostoy I tried it in linux64 with your case and it works for me:

```
<head>
<script>
function test() {
  require('./test').hello();
}
</script>
</head>
<body>
<button onclick="test()">test</button>
</body>
```

```
exports.hello = function(){
  // set breakpoint below, but devtools doesn't stop here
  console.log('test.js loaded');
  debugger; // devtools will stop at debugger statement
  console.log('test.js continue');
};
```

1. click test (so that the code will be executed and appear in devtools)
2. open devtools
3. set breakpoint
4. click test again

**Comment by ghostoy** [comment]
@rogerwang I see this fixed the issue partially. But it still has some issue. Here is the steps to reproduce:

1. run nw.js with `--remote-debugging-port=9222` (make sure devtools remember breakpoints)
2. open devtools
3. click test (so that the code will be executed and appear in devtools)
4. set breakpoints at two `console.log()` statements: one before `debugger` and one after it.
5. close nw.js and reopen it with `--remote-debugging-port=9222` (make sure devtools remember breakpoints)
6. open devtools
7. click test

You will see manually set breakpoints restored. But breakpoints **before** `debugger` not get stopped. However `debugger` statement and breakpoint after `debugger` work as expected. If you click test again, all breakpoints works.

This process is common steps for debugging Node.js code executing at `require()` time, which is executed only once. So you don't have a chance to break and debug it. Though a **workaround** could be adding `debugger` statement at the beginning of node code to make all breakpoints are **after** `debugger`, it still cause some inconvenience for debugging.
