### ISSUE TITLE
webview tag does not work when "frame": false, for child window

### ISSUE THREAD

**Issue by PhilAndrew** [nwjs/nw.js#2997]
The case seems to be slightly complicated. My package.json

  "window": {
    "frame": true
  },

Then I create a window as follows.

var gui = require('nw.gui');
var win = gui.Window.get();
var a_window = gui.Window.open('browser.html', {
 "frame": false,
 "toolbar": true,
 "resizable": false
});

browser.html contains

... html stuff
<body style="margin: 0px;width:800px;height:800px;overflow:scroll">
<webview id="foo" src="https://www.github.com/" style="width:640px; height:480px"></webview>
</body>

Then in this case, the webview inside browser.html does not show github.
##

**Comment by PhilAndrew** [comment]
I'm using nwjs-v0.12.0-alpha2-win-x64

**Comment by bachel** [comment]
This is not frameless window problem,but child window. Similar to #3302
