### ISSUE TITLE
0.12.0 Windows high dpi support broken [$100]

### ISSUE THREAD

**Issue by KenRmk** [nwjs/nw.js#2998]
Even though it worked well in 0.11

reported from Surface Pro 3 running Windows 8.1

![nwjs-dpi](https://cloud.githubusercontent.com/assets/3995401/5884384/d66e931e-a35c-11e4-9b52-340a6a8584d5.png)

**Comment by benjismith** [comment]
@rogerwang Any update on this issue? Builds on Windows are basically unusable right now...

**Comment by benjismith** [comment]
@rogerwang I'd be happy to put a $50 bounty on this issue if you think it can be done this week...

**Comment by benjismith** [comment]
I just placed a $100 bounty on this issue, since this is the only remaining obstacle for me releasing my product using the 0.12.0 version of NWJS. In every other way, version 0.12 is working flawlessly, and I'm grateful for the overwhelming awesomeness of NWJS. I would be absolutely delighted if a 0.12.1 release could fix this issue while keeping everything else stable.

Thanks in advance!

**Comment by rogerwang** [comment]
@benjismith would like to fix this soon.

**Comment by benjismith** [comment]
Thanks @rogerwang!! You're the best :)

**Comment by KenRmk** [comment]
@rogerwang @benjismith Thank you :)
![](http://cdn.meme.am/instances/500x/60762627.jpg)

**Comment by benjismith** [comment]
@rogerwang Do you have a rough idea of *how* soon this can be fixed? More like a week, or more like a month? Or longer than a month? Sorry to be impatient, but this is the only thing blocking a release :)

Thanks!

**Comment by rogerwang** [comment]
@benjismith I'd like to fix it in a week.

**Comment by benjismith** [comment]
Awesome. Thank you so much, Roger :)

**Comment by benjismith** [comment]
Great! Have the binaries been built?

**Comment by rogerwang** [comment]
not yet. I'm trying to include another fix for crash dump generator.

Will build it today and post the link here.

**Comment by benjismith** [comment]
:dancer: :racehorse: :dancer: :racehorse: :dancer:

**Comment by rogerwang** [comment]
please try the build here: http://dl.nwjs.io/live-build/04-08-2015/f19f713-3865e3a-be948af-459755a-2bdc251-c114bb7/

**Comment by benjismith** [comment]
Works like a charm! Thank you so much @rogerwang. I really appreciate it :)

**Comment by benjismith** [comment]
Hey @rogerwang don't forget to claim the bounty: https://www.bountysource.com/issues/7995247-0-12-0-windows-high-dpi-support-broken-100

**Comment by rogerwang** [comment]
Thanks @benjismith but I'm not going to claim it because it's my duty to fix the issues here.

**Comment by Rob--** [comment]
You da real mpv @rogerwang
