### ISSUE TITLE
mousemove event mapped wrong

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#3001]
The following snipped will print to the console when the mouse enters or leaves the window.  Of course it should instead print when the mouse moves.

This happens on the 32-bit Linux Binary on Debian Jessie.

```
<html>
<head>
<script>
document.onmousemove = function() {console.log("hello from mouseover/mouseout");};
</script>
</head>
<body>
<h1>Hello World</h1>
</body>
</html>
```

**Comment by ghostoy** [comment]
Did you have your main window getting the focus? Seems that it happens only when the window is losing focus. And please also provide the nw version you are testing on.

**Comment by jonwwilkes** [comment]
This is with nwjs-v0.12.0-alpha2-linux-ia32

It absolutely happens when the main window (which is the only window) has focus.  The "onmousemove" callback is invoked when the mouse is clicked.  I'm using a touchpad on an HP Pavilion, which worked perfectly well with 11.5 and 8.6.

**Comment by jonwwilkes** [comment]
This bug does not happen on Windows 7 using Version 0.12.0-alpha2.

**Comment by ghostoy** [comment]
Confirmed. It should be a regression of nw.js 0.12.

**Comment by rogerwang** [comment]
@jonwwilkes could you please try again with the latest build? It works for me in Debian sid: 
http://dl.nwjs.io/live-build/02-19-2015/fcf09f1-4aad9fe-b1a5bb9-add523e-2bdc251-c114bb7/

**Comment by rogerwang** [comment]
@ghostoy does it work for you?

**Comment by ghostoy** [comment]
@rogerwang Tested with 0.12-rc1. It works for me.

**Comment by forellana-digithinkit** [comment]
Hi

I am on ubuntu seeing the same issue back on v0.12.3-linux-x64
Anybody else seeing this?

Same sample code at the top of this issue breaks in the same manner as reported for the 32bit version. While win-x64 works fine for me.

**Comment by forellana-digithinkit** [comment]
Some more info...

Also, noticed that onmousemove event gets triggered if I scroll my mouse wheel up and down while moving my mouse.

**Comment by forellana-digithinkit** [comment]
extra info, figured out the issue happens in virtualbox for 32 and 64bit ubunut trusty but not on a regular computer installation. Don't know if you guys are concerned with virtual machiens, I use them a lot to test different environments.

**Comment by jonwwilkes** [comment]
I agree-- the reason I found this bug is because I use virtual machines to test Ubuntu builds.
-Jonathan


     On Tuesday, September 15, 2015 11:50 AM, Felipe Orellana <notifications@github.com> wrote:
   

 extra info, figured out the issue happens in virtualbox for 32 and 64bit ubunut trusty but not on a regular computer installation. Don't know if you guys are concerned with virtual machiens, I use them a lot to test different environments.—
