### ISSUE TITLE
version 0.11.15 not playing videos

### ISSUE THREAD

**Issue by waldemarnt** [nwjs/nw.js#3002]
Hello all, i'm working in the version 0.11.15 and are using ffmpegsumo.dll from google chrome 40.0.2214.91.
my plugin is enabled like this
    "webkit": {
    "plugin": true,
    "java": true
  }

but i can't play videos or sounds in my app.
someone could help me? these are not yet stable version?
Tnx all
##

**Comment by notsospecial1** [comment]
The latest (and purportedly last) version 11 is 0.11.06,  so your issue with "version 0.11.15" is puzzling.  Nevertheless,  all  nw.js version 11 is based off of chromium 38.0.2125.104, so using ffmpegsumo.dll from chrome 40.0.2214.91 will not work.

**Comment by waldemarnt** [comment]
i've tried with ffmpegsumo.dll from 38.0.2125.104 and the error continues..
