### ISSUE TITLE
No surround sound

### ISSUE THREAD

**Issue by Torsten85** [nwjs/nw.js#3004]
Hey,
my goal is to be able to play 1080p mkv files with dts sound via <video> tags.
I've already changed ffmpeg, activated all necessary codes and the mkv plays with sound!

But my 5.1 dts capable sound system only receives stereo (2ch) sound. Playing with e.g. VLC shows the correct DTS sound stream.

Is there a flag or something like that to globally activate surround sound or disabling some kind of down mix / resampling? 

Thanks
##

**Comment by FFAxKenny** [comment]
@Torsten85: I think you might be able to force 5.1 surround with the `--disable-audio-output-resampler` and `--try-supported-channel-layouts` flags. 

Background:

* https://productforums.google.com/forum/#!topic/chrome/bskC-dMyp7E
* http://www.reddit.com/r/chrome/comments/2dwgmo/chromeyoutubehtml5no_51_sound/
