### ISSUE TITLE
New-win-policy handler is not called

### ISSUE THREAD

**Issue by bachel** [nwjs/nw.js#3006]
The problem is in simulating javascript click on element with target blank. 
Here is web page loaded in iframe to reproduce problem.

```
<html>
    <script>
        function openTest (url){
            var a = document.createElement("a");
            a.target = "_blank";
            a.href = url;
            a.click()
        }
    </script>
    <button onclick="openTest('http://google.com')">Create Window</button>
</html>
```

New-win-policy handler is not called, but the window is created.

```
win.on('new-win-policy', function(frame, url, policy){
  policy.ignore();
});
```

The problem is related to https://github.com/nwjs/nw.js/issues/2926
##

**Comment by bachel** [comment]
Problem is in node-webkit\src\content\nw\src\api\dispatcher.cc on lide 224
Where nwapi::Dispatcher::GetWindowId() returns NULL
```
id_val = nwapi::Dispatcher::GetWindowId(web_view->mainFrame());
```

**Comment by choppsta** [comment]
The following in an iframe also doesn't trigger the new-win-policy event:

    <button onclick="window.open('http://google.com');">window.open test</button>

Back in version 0.9.2 this worked, but since then it hasn't worked.

Also, this is only within an iframe.  If this is in the main node webkit window html then it works as expected.
