### ISSUE TITLE
unmaximize and restore not work after hide&&show method called

### ISSUE THREAD

**Issue by paseo** [nwjs/nw.js#3010]
Hello,all,i'm working in the version 0.11.5 and are using Windows 7 OS.I have a problem as below.
#### steps:
1. open a nw window with 800*600
2. call gui.Window.maximize()
3. call gui.Window.hide()
4. call gui.show()
5. call gui.Window.unmaximize() or call gui.WIndow.restore()
#### result:

gui Window can not resize to 800*600

anyone can help me ?
Thx
##

**Comment by SophinQ** [comment]
I met with the same problem.Have you solved it?
