### ISSUE TITLE
Event object is not created from right class in <iframe> (0.11.6)

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#3011]
We are testing a program that extends `Event.prototype` with additional method `Event.prototype.consume`. And event listeners will invoke that function as below:
```js
document.addEventListener('keydown', function(evt) {
    evt.consume();
}, false);
```
It works fine if it's directly run within NW. However if the program is loaded in `<iframe>`, it reports `evt.consume` is `undefined`. When I set breakpoint at this point, `evt instanceof Event` is `false`, but `evt instanceof parent.Event` is `true`. That means `evt` is created from parent window, not in the iframe. That's not the expected result.

I tried to re-compile NW.js 0.11.6 and commented out following functions in `dispatcher.cc`:
* `DidFinishDocumentLoad`
* `DidCreateDocumentElement`
* `documentCallback`

This will break `document-{start|end}`, but fixed my issue. So I suspect this issue is related to `document-{start|end}`.

**Comment by bachel** [comment]
In which context do you add this prototype? In context of main window? If you want do add this prototype to all frames. Best solution is [inject-js-start in manifest ](https://github.com/nwjs/nw.js/wiki/manifest-format#inject-js-start--inject-js-end ). Or you can use document-start event with Window.eval(frame,"script to run")

**Comment by ghostoy** [comment]
No, it's not intentionally inject code in iframe. The script is loaded directly by the iframe. However it looks like the script is executed in the context of parent frame.

**Comment by ghostoy** [comment]
Test case

*index.html*
```html
  <h1>index.html</h1>
  <iframe src="child.html"></iframe>
  <script>
  function handler1(e) {
    console.log('handler1');
  }

  // if you bind to different functions, it doesn't fail
  function handler2(e) {
    console.log('handler2');
  }

  document.addEventListener('mousedown', handler1, false);

  require('nw.gui').Window.get().on('document-start', function(frame){
    var doc = frame.contentDocument;
    doc.addEventListener('mousedown', handler1, false);
  });

  </script>
```

*child.html*
```html
  <h1>Child.html</h1>
  <script>
  Event.prototype.consume = function() {
    alert('success');
  };
  
  document.addEventListener('mousedown', function(e) {
    try{
      e.consume();
    } catch (ex) {
      alert('failed');
    }
  }, false);
  </script>
```

**Comment by rogerwang** [comment]
This is expected behavior -- the 2 event handers are defined in different context, while the event object is constructed in the context of the first event handler get called. So it is a object from foreign context to the 2nd handler.

**Comment by ghostoy** [comment]
If it's the case, a slightly changed test case with right binding sequence should fail, too. But it doesn't.

Click the buttons in this order: 1. Add Frame, 2. Add Parent Listener, 3. Add Child Listener.

* index.html*
```html
<button onclick="addFrame()">1. Add Frame</button>
  <button onclick="addParentListener()">2. Add Parent Listener</button>
  <script>
  function handler1(e) {
    console.log('handler1');
  }

  function addFrame() {
    var iframe = document.createElement('iframe');
    iframe.src = 'child.html';
    document.body.appendChild(iframe);
  }

  function addParentListener() {
    document.addEventListener('mousedown', handler1, false);
  }

  </script>
```

*child.html*
```html
  <button onclick="addChildListener()">3. Add Child Listener</button>
  <script>
  Event.prototype.test = function() {
    alert('success');
  };

  function addChildListener() {
    document.addEventListener('mousedown', function(e) {
      try{
        e.test();
      } catch (ex) {
        alert('failed');
      }
    }, false);
  }
  </script>
```

**Comment by rogerwang** [comment]
Your updated case is not identical regarding the event binding: the document object is different (`document' vs `doc')

**Comment by ghostoy** [comment]
@rogerwang I just tested against same test case on Firefox and IE. But it succeeded. I think it's an upstream Chromium issue.

**Comment by ghostoy** [comment]
Just reported this issue to upstream Chromium https://code.google.com/p/chromium/issues/detail?id=454351

**Comment by rogerwang** [comment]
close since it's an upstream issue.
