### ISSUE TITLE
-webkit-app-region: drag, how to disable the effect of none-client frame,on windows

### ISSUE THREAD

**Issue by petitlen** [nwjs/nw.js#3012]
-webkit-app-region: drag, how to disable the effect of none-client frame,on windows.
when i dbclick the drag region, the app set max!!!and right click the drag region,it show the windows toolbar menu(with close ALT+4)....
how can i do to disable these effect?
##

**Comment by perpyy** [comment]
**嗨,Mr.Lin**


>-webkit-app-region: drag, how to disable the effect of none-client frame,on windows.
 when i dbclick the drag region, the app set max!!!and right click the drag region,it show the windows toolbar menu(with close ALT+4)....
 how can i do to disable these effect?

*I found you, ha ha*

**Comment by RIAEvangelist** [comment]
-webkit-app-region: no-drag on the elements you want to not be draggable?

Most of those sound like default OS level behaviors.

**Comment by zzbo** [comment]
@RIAEvangelist He want to dblclick the drag region without maximize the window.

**Comment by zzbo** [comment]
I encountered the same problem, I try to solve it as following:
```javascript
var gui = require('nw.gui');
var win = gui.Window.get();
win.on('maximize', function () {
	return false;
});
```
It will appear flash when the user dblclick the drag region, can you tolerate it?
