### ISSUE TITLE
[Mac] Opening file dialog a few times crashes app

### ISSUE THREAD

**Issue by 4ver** [nwjs/nw.js#3013]
Running v0.11.5 on Yosemite. I've added a sample app here: https://github.com/4ver/nw-mac-file-input-test

In the app I am building it crashes much more consistently (almost always the third time you open the dialog).

The following error are printed before a crash:

``` log
2015-01-27 20:10:31.202 node-webkit[80237:788258] Unable to setup extension context - error: Couldn’t communicate with a helper application.
2015-01-27 20:10:31.202 node-webkit[80237:788259] plugin com.getdropbox.dropbox.garcon interrupted
** Unknown exception behavior: 0
```

Thanks!
##

**Comment by adam-lynch** [comment]
+1. 

It does not happen on Mavericks at all. I've had one Yosemite user say it doesn't happen for them so maybe it only happens to some people. Not sure.

**Comment by adam-lynch** [comment]
Could this have a problem with Yosemite's Finder's Dropbox integration? Just came across this [StackOverflow answer](http://stackoverflow.com/a/28223181/727074).

**Comment by adam-lynch** [comment]
Seems to be fine with OSX 10.10.3
