### ISSUE TITLE
can’t set breakpoints when using non-ascii-chars in comments

### ISSUE THREAD

**Issue by jdittrich** [nwjs/nw.js#3023]
**Problem**: I am unable to set breakpoints via the chromium dev-tools in script files, as long as they contain  non-ASCII Characters (Tested with Ä,Ö,ß,…, ’) in comments. 
If I replace them (e.g. with A,O, s,...,'), I can set breakpoints.

**Comment by cycorey** [comment]
I am also unable to set breakpoints via the chromium dev-tools in script files, as long as they contain non-ASCII Characters (Tested with chinese chars '你好') in comments.
how to fix it?

**Comment by cycorey** [comment]
if I press reformat button, then I can set breakpoints.
but we want set breakpoints in the original script files...

**Comment by rogerwang** [comment]
It works for me with the following sample:

index.html:  
```html
<html>
<head>
<script src="a.js"></script>
</head>
<body>
<button onclick="test()">test</button>
</body></html>
```

a.js:  
```js
function test() {
console.log("hello"); //你好
}
```

**Comment by myren** [comment]
hello, This problem still exists~you can reproduce it like this:

var data="你好";
/**
** 这是我的一个测试用例
**/
function test() {
console.log(data); 
}
test();

**Comment by zcxp** [comment]
+1

**Comment by zcxp** [comment]
@rogerwang My scripts is in UTF-8 encoding, and I have set the charset in the html, if I convert the js file to ASCII, it's OK
