### ISSUE TITLE
child_process.fork explodes on expressjs

### ISSUE THREAD

**Issue by brian-mann** [nwjs/nw.js#3024]
I'm using the latest version of NW.

Forking works fine in regular node (all my node tests pass), but it immediately blows up in NW.

The error message is this:

```
#
# Fatal error in ../../v8/src/runtime.cc, line 790
# CHECK(V8::ArrayBufferAllocator() != NULL) failed
#

==== C stack trace ===============================

 1: ??
 2: ??
 3: ??
 4: ??
```

I've reduced the error message down to me requiring `express` within the fork.

The moment express is required it bombs.  Removing this one line prevents the fork from crashing.
##

**Comment by matthew-dean** [comment]
I just started getting this error. Not sure what I did that triggered it.
