### ISSUE TITLE
show_in_taskbar not working on Yosemite

### ISSUE THREAD

**Issue by Jonovono** [nwjs/nw.js#3025]
Hi. I am trying to make a Mac app that is only a Menu Bar app. I don't want an Dock Icon at all.

I just downloaded the 64 Bit nwjs for Mac and running on my Yosemite installation. 

This is my package.json:

    {
     "name": "notta",
      "description": "Best note taking app",
      "main": "index.html",
      "window": {
           "frame": true,
           "toolbar": false,
           "show_in_taskbar": false
      }
    }

Do I need to specify a menubar icon first or something? 

Thanks.

**Comment by mrfabbri** [comment]
You should specify the status menu icon using the `Tray` API object, you can take a look at the `custom_tray_icon` example in manual tests.

**Comment by Jonovono** [comment]
Awesome, thanks. That works! It seems like the app still flashes in the dock like it's going to appear but then disappears. Is that normal?

**Comment by mrfabbri** [comment]
I didn't noticed this before (hidden dock) but this seems to be the "normal" behaviour. Anyway, it shouldn't flicker, so please file another bug.
