### ISSUE TITLE
Mac OS vs Windows / Linux performance

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3029]
I have a rather big app in AngularJS and just put it on 0.11.6 in Windows, on a 5 year old crappy laptop and it runs smooth as butter. Same on Linux.

However on Mac it's slow, on a newer machine which is much more powerful than the Windows laptop, everything from dragging elements, to load a new page, etc. I don't see any crazy CPU issues now though, as reported in another issue here.

Does anyone else have these issues when testing cross platform?

**Comment by felicienfrancois** [comment]
I have the same issue.
Even on the same computer (macbook end 2013), with mac OS, windows and ubuntu installed in multiboot, I get lags on Mac OS X and it runs smoothly on both windows and linux.

I have not made advanced benchmark (to determine what is lagging and what is not), but it seems to have trouble at least with scrolling and CSS3 animations / transitions.

I tried the `--ignore-gpu-blacklist` flag but i have not noticed any changes.

**Comment by willbarrett** [comment]
We have similar performance issues in two applications. Both perform well on Linux, but eat CPU on Mac.

**Comment by felicienfrancois** [comment]
We may have several combined issues, and part of it may come from blink/chromium.

We have to preciley identify the problem(s), check if it also occurs on chrome/chromium, and also identify on which setup it occurs (OSX version, macbook/desktop, retina/not retina)

It seems that chromium have already some performance issues opened on OSX. In the [chromium issues list](https://code.google.com/p/chromium/issues/list?can=2&q=osx+performance), there are reports about:
- high CPU usage / high battery consumption
- Poor scrolling performance (scrolling not smooth)

**Comment by felicienfrancois** [comment]
#3030 CSS3 transitions not smooth on Mac OS X

**Comment by morgondag** [comment]
Having the same problems with our mac builds for a game.
Runs good on a 10 year old win7 laptop but is really slow on even the never macbook air.
The fan kicks in and the computer gets very warm.
```-ignore-gpu-blacklist``` seams to do nothing and disabling gpu (chrome args) dosen't seam to help either. It's almost at the point that we can't use this in production.

Guess this is the same as:
#2723 #2372 #3046 #3030
