### ISSUE TITLE
show_in_taskbar == true not working

### ISSUE THREAD

**Issue by lucastan** [nwjs/nw.js#3031]
I set it to true but it doesn't appear in the Task bar in Yosemite. 64Bit Mac
Release node-webkit 0.11.6

```
"window": {

    "toolbar": false,
    "frame": true,
    "min_width": 1024,
    "min_height": 768,
    "width": 1024,
    "height": 768,
    "position": "center",
    "show_in_taskbar": true,
    "resizable": true
  },

**Comment by mrfabbri** [comment]
How are you starting your nwjs app?

**Comment by tommoor** [comment]
@lucastan sounds like you're getting the dock and menubar confused. This option is to show the app in the dock and is true by default. To create a menubar icon you should look here: https://github.com/nwjs/nw.js/wiki/Tray

**Comment by lucastan** [comment]
erm, it is NOT shown in the tray nor the dock. 

i start using `node-webkit .` in the app dir.

**Comment by tommoor** [comment]
You should see the node-webkit icon by default - try leaving that attribute out of the manifest altogether as it's true by default

**Comment by lucastan** [comment]
yes i left it out -- still doesn't work.

How did you install the node-wekit.app ? Put it in /Applications? How do you run it?

**Comment by lucastan** [comment]
Ok, this is kind of weird, I started using `/Applications/node-webkit.app/Contents/MacOS/node-webkit .` and it works fine. But if I created a symlink /usr/local/bin/node-webkit to  the actual binary and started it using `node-webkit` (as /usr/local/bin is in PATH), then weird things happen.
