### ISSUE TITLE
window not focused on startup when started from command line

### ISSUE THREAD

**Issue by lucastan** [nwjs/nw.js#3032]
node-webkit 0.11.6 on 64-bit Mac Yosemite.

I run it using `node-webkit .` and the window that appeared is not focused automatically. I had to click once to focus on the window and  another time to click a button in the window.

```
"window": {

    "toolbar": false,
    "frame": true,
    "min_width": 1024,
    "min_height": 768,
    "width": 1024,
    "height": 768,
    "position": "center",
    "show_in_taskbar": true,
    "resizable": true
  },

```

**Comment by gihrig** [comment]
I'm having success with this Javascript snippet loaded from the  `main` html:

```  
  var win = gui.Window.get();

  // Open and focus application window with appServer content  (a URL)
    win.window.location = appServer;
    win.on('loaded', function () {
        win.show();
        win.focus();
    });
```

The main window is not shown until the `loaded` event fires. Add `"show": false` to your `window` property in package.json. see: https://github.com/nwjs/nw.js/wiki/Show-window-after-page-is-ready

**Comment by lucastan** [comment]
@gihrig  does not work for me. the window blurs immediately upon showing.

**Comment by lucastan** [comment]
Ok, this is kind of weird, I started using `/Applications/node-webkit.app/Contents/MacOS/node-webkit .` and it works fine. But if I created a symlink /usr/local/bin/node-webkit to  the actual binary and started it using `node-webkit` (as /usr/local/bin is in PATH), then weird things happen.

**Comment by OlsonDev** [comment]
I don't think this is `mac-only`. I'm having similiar issues on Windows 10 (build 10130). The suggestion provided by @gihrig does not work either.
