### ISSUE TITLE
unable to select window in mission control (Mac)

### ISSUE THREAD

**Issue by lucastan** [nwjs/nw.js#3033]
node-webkit 0.11.6 on 64-bit Mac Yosemite.

I run it using `node-webkit .` and I wasn't able to select the window in mission control mode (The mode where u get to see all app windows)

```
"window": {

    "toolbar": false,
    "frame": true,
    "min_width": 1024,
    "min_height": 768,
    "width": 1024,
    "height": 768,
    "position": "center",
    "show_in_taskbar": true,
    "resizable": true
  },

```

**Comment by gihrig** [comment]
I'm not seeing that issue. Running the same nw.js and Mac versions as you. 

I press F-9 to get Mission Control, I see 8 windows, one is my nw.js app. Clicking that window brings it to the foreground. Same as any other window. Is this not what you are seeing?

Here's some possibly relevant sections from my package.json.

```  
{
  "name": "iCrumz",
  "version": "0.0.1",
  "main": "index.html",
  "description": "iCrumz - Start here",
  "contributors": ["iCrumz team"],
  "no-edit-menu": true,
  "macIcns": "img/app/Logo-square.icns",
"window": {
    "title": "iCrumz - Start here",
    "icon": "img/app/Logo-square.png",
    "toolbar": false,
    "width": 1080,
    "height": 700,
    "position": "center",
    "min_width": 400,
    "min_height": 250,
    "show": false,
    "resizable": true,
    "single-instance": true
  }
}
```
also see my window loading snippet in #3032

**Comment by lucastan** [comment]
see this screen capture https://dl.dropboxusercontent.com/u/17243832/Screen%20Recording.mov 
i tried to switch from sublime to the node-webkit window, it flashes and then disappears

**Comment by lucastan** [comment]
Ok, this is kind of weird, I started using `/Applications/node-webkit.app/Contents/MacOS/node-webkit .` and it works fine. But if I created a symlink /usr/local/bin/node-webkit to  the actual binary and started it using `node-webkit` (as /usr/local/bin is in PATH), then weird things happen.

**Comment by neves** [comment]
Same here. My solution was to create an alias to executable:
alias nwjs=/Applications/nwjs.app/Contents/MacOS/nwjs
