### ISSUE TITLE
Build node-webkit with experimental chromium to enable --use-gl=osmesa flag

### ISSUE THREAD

**Issue by chriddyp** [nwjs/nw.js#3035]
I'd like to use the `--use-gl=osmesa` for my webkit app, which is only available on the experimental version of Chromium. For reference, here is are the switches for the experimental version of Chromium: [https://chromium.googlesource.com/experimental/chromium/src/+/lkgr/ui/gl/gl_switches.cc](https://chromium.googlesource.com/experimental/chromium/src/+/lkgr/ui/gl/gl_switches.cc) and here are the switches from the latest chromium shipped with NW (38.0.2125.104):  [https://chromium.googlesource.com/chromium/src/+/38.0.2125.104/chrome/common/chrome_switches.cc](https://chromium.googlesource.com/chromium/src/+/38.0.2125.104/chrome/common/chrome_switches.cc)

Does anyone have any experience [building node webkit](https://github.com/nwjs/nw.js/wiki/Building-node-webkit) with the experimental version? Are there any known roadblocks to get this going?

Perhaps related: https://github.com/nwjs/nw.js/issues/3035

Thanks a bunch for the great work!

**Comment by bpostlethwaite** [comment]
Excellent, I would love this! +1

**Comment by chriddyp** [comment]
Nevermind, looks like that switch *is* available! The `chrome_switches.cc` file is not a complete list of switches, the `use-gl` switch is here: https://chromium.googlesource.com/chromium/src/+/38.0.2125.104/ui/gl/gl_switches.cc

See the relevant discussion with Chromium here: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/xKNEABURzUk
