### ISSUE TITLE
constructing module path with incorrect version

### ISSUE THREAD

**Issue by bretg** [nwjs/nw.js#3037]
Having an issue with node-webkit finding a C/C++ module in a scenario similar to one resolved last fall for sqlite3 in https://github.com/mapbox/node-sqlite3/issues/328, except I’m working with serialport.

OSX 10.9.5
node 0.10.35
node-webkit 0.8.6
node-pre-gyp 0.6.2
serialport 1.4.10

sudo node-pre-gyp rebuild --runtime=node-webkit --target=0.8.6 --target_arch=ia32
node-pre-gyp builds serialport nicely and puts it in:
        /usr/local/lib/node_modules/serialport/build/serialport/v1.4.10/Release/node-webkit-v0.8.6-darwin-ia32/serialport.node

But node-webkit looks for it as ‘v11’ instead of ‘v0.8.6’:

"Uncaught Error: Cannot find module '/usr/local/lib/node_modules/serialport/build/serialport/v1.4.10/Release/node-webkit-v11-darwin-ia32/serialport.node'", source: module.js (343)

The module works if I add the appropriate symlink.

Got similar results trying node 0.11.13 with node-webkit 0.11.6, except the error was
"Uncaught Error: Cannot find module ‘[…]/node-webkit-v14-darwin-x64/serialport.node'", source: module.js (343). It would have succeeded had it looked in […]/node-webkit-v0.11.6-darwin-x64/serialport.node

Spent a couple evenings reading various threads and tried a number of approaches. Happened to notice serialport comes bundled with 0.5.9 version of node-pre-gyp, but upgrading that didn’t help. Tried a recursive grep in several trees to see where the ‘v11’ js coming from… not seeing it.

Appreciate any insight into how node-webkit constructs the module path. i.e. why it’s choosing v11 (or v14). In the meantime, the symlink works ok.
##

**Comment by RIAEvangelist** [comment]
There is a lot of trouble with serial port, if you search the closed bug list you'll find a lot of info.

So much trouble in fact that I am building a pure JS implementation for serial coms.

**Comment by bretg** [comment]
Thanks RIAEvangelist, though the specific issue I'm having seems to be more just path related -- serial port functionality is ok with the limited testing I've done so far after the symlink made it work. 

Still interested if anyone can shed light on how node-webkit constructs the module path -- i.e. where's it getting that "v11"?

In any case, will keep an eye out for your JS implementation.

**Comment by endorama** [comment]
Hello everyone, I'm having the same issue @bretg is having.

After a bit of struggle I was able to compile node-serialport with node-pre-gyp, but the compilation produces the folder `build/serialport/v1.4.10/Release/node-webkit-v0.11.5-linux-x64` while node-webkit seems to need the folder `build/serialport/v1.4.10/Release/node-webkit-v14-linux-x64`

I've copied the folder naming it as required and everything is working fine, but this is a bit of a problem when others have to npm install the project dependencies.

I'm on Ubuntu 14.04, x86_64.
Node webkit is 0.11.5 ( I've tried with no luck the 0.12.0-alpha2 relase )

Thanks in advance for the help provided!

**Comment by RIAEvangelist** [comment]
@bretg check it out here : https://github.com/RIAEvangelist/serialport-js

**Comment by bretg** [comment]
Nice progress - checked it out and generally like the interface. Would like
to be able to get port info like the other serial port module does.
e.g. port.manufacturer.

Not working for me in Ubuntu (14.10) and of course not on Mac.

FWIW, here's the paths to my serial ports:

Ubuntu: /dev/ttyACM0
Mac: /dev/cu.usbmodem1421

Watching the repository -- happy to help test.

**Comment by RIAEvangelist** [comment]
Thanks for the info!
