### ISSUE TITLE
Window.on('reloading', ...)

### ISSUE THREAD

**Issue by danielwertheim** [nwjs/nw.js#3038]
Missing an event for `reloading`. Useful, e.g. if you want to re-register shortcuts. Scenario:

Since shortcuts are global, you might want to register them on `loaded` and `focus` and deregister on `blur`. If you `reload` the window, it will trigger `loaded` twice, but no `blur` hence shortcuts might be registered twice and then failing.

Yes, you can design around it, by keeping global state, but it would be much nicer with a `reloading` event.
##

**Comment by broderix** [comment]
Try 
```javascript
var win = gui.Window.get();
win.once('loaded', function(){...});
win.on('unloaded', function(){...});
```
events
