### ISSUE TITLE
Permanent directory for a nw.js app (snapshot)

### ISSUE THREAD

**Issue by Lcfvs** [nwjs/nw.js#3041]
Hi all,

Is it possible to (add an option to) create a snapshot that only runs from the nw.js application installation directory, please?

I wish to avoid a new temporary directory creation on each app execution.

For example, if my user installs & run my app in his "C:\programs\my_app" directory
I want to have a cwd that equals to "C:\programs\my_app"
Not from a random temporary directory like "C:\users\...\AppData\Local\Temp\nw7508_17111"

What else?

**Comment by RIAEvangelist** [comment]
process.execPath should help you out. The files are extracted into the tmp dir when you run them, however if you need access to the path and can't seem to find another way, that should do the trick.

http://nodejs.org/api/process.html#process_process_execpath

**Comment by felicienfrancois** [comment]
You can just just put your files alongside the nw.exe instead of packing its in it

https://github.com/nwjs/nw.js/wiki/How-to-run-apps

**Comment by Lcfvs** [comment]
@RIAEvangelist Yeah, it's exactly what I made... :)

But thanks to you 2. ;)
