### ISSUE TITLE
child spawn not working

### ISSUE THREAD

**Issue by zwhitchcox** [nwjs/nw.js#3044]
for some reason, my code breaks right [here](https://github.com/zwhitchcox/2git/blob/master/test.js#L28)

I get an EACCES error

And I chmod'd  777 on all the binary files

```sh
mac:sofarsogood zane$ ls -al bin
total 976
drwxr-xr-x  5 zane  staff     170 Jan 31 23:42 .
drwxr-xr-x@ 9 zane  staff     306 Feb  1 00:24 ..
-rwxrwxrwx@ 1 zane  staff    9316 Jan 31 23:42 convert
-rwxrwxrwx  1 zane  staff  220064 Jan 31 23:42 ffmpeg
-rwxrwxrwx@ 1 zane  staff  265804 Jan 31 23:42 gifsicle
```

But it's still not working.

I can't figure out why this wouldn't be executed.

**Comment by RIAEvangelist** [comment]
you may need to run as root.

**Comment by RIAEvangelist** [comment]
sudo

**Comment by zwhitchcox** [comment]
I tried that, but for some reason, it says Maximum call stack exceeded.

What ended up working, per [this google group](https://groups.google.com/forum/#!msg/nwjs-general/doRWZ07LgWQ/4fheV8FF8zsJ), I had to chmod 777 all of the binary files after nodewebkit had run, because the file permissions do not get copied over.

This is the code I used:

```js
    fs.chmodSync('bin/ffmpeg', 0777);
    fs.chmodSync('bin/convert', 0777);
    fs.chmodSync('bin/gifsicle', 0777);
```
