### ISSUE TITLE
nwjs 0.12.0 alpha2 - CSS animation and high CPU usage

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#3046]
Testing nwjs 0.12.0 alpha2 with CSS animations on MacOS 10.6.8 and 10.8.5 (both 64bit) I have this problem:
On the oldest, the CPU reaches 90-150%, on the new one 30-40%.
This is a test case: http://codepen.io/anon/pen/jEGbdZ
This is another, with 2 identical animations: http://codepen.io/anon/pen/LEzGPE

Using nodewebkit 0.10.5 the CPU usage is less but in my opinion still too much (about 10% of a i7 quad core 2,8GHz)

Testing it on Windows 7 the CPU usage il 15-20%.

PS: Testing the same on Chrome 40.0.2214.94 and the chrome process reaches 20 - 25 % of CPU usage for i7 MacOs 10.8.5 and 40-50% on MacOs dual core 10.6.8

**Comment by AndryBray** [comment]
This is the chrome://gpu export of the newest Mac.

![gpu1](https://cloud.githubusercontent.com/assets/4180209/5993392/4e9c1fc0-aa4f-11e4-83ea-5f84729f9f76.png)
![gpu2](https://cloud.githubusercontent.com/assets/4180209/5993395/55510d62-aa4f-11e4-9d6b-05e7e27435c0.png)

**Comment by AndryBray** [comment]
After some time investigating on this problem I found this post:
http://stackoverflow.com/questions/13176746/css-keyframe-animation-cpu-usage-is-high-should-it-be-this-way

I can confirm, with the same test cases, adding transform: translateZ(0); we can save 10-15% of CPU... but it's still too high!
=(

**Comment by brandonpapworth** [comment]
Have you tried the test case with something like Greensock TweenMax (or, since you're doing keyframes, TimelineMax)? Logic dictates that CSS3 should be more performant when compared to JavaScript-controlled animation, but that isn't always the case.

**Comment by rogerwang** [comment]
Is it similar with #2723 which is just fixed?
