### ISSUE TITLE
Wiki References to node-webkit

### ISSUE THREAD

**Issue by alanjames1987** [nwjs/nw.js#3048]
Should the references in the wiki to `node-webkit` be changed to `NW.js`, `nw.js`, `nwjs` or just be left alone? I've seen it written all three ways now.
##

**Comment by gihrig** [comment]
Given the chosen project title "nw.js", I would expect to see that consistent throughout.

**Comment by chaseWillden** [comment]
@mrfabbri You can assign this to me if it's something that needs to be done.

**Comment by mrfabbri** [comment]
@chaseWillden a documentation project see #2972 is in the workings so the material on the wiki will be subject to some revision for consistency. (I left this open as a reminder)
