### ISSUE TITLE
ERROR: WSALookupServiceBegin failed  with: 0

### ISSUE THREAD

**Issue by niquedegraaff** [nwjs/nw.js#3049]
**Problem**
When i run `nw.exe --logging-enabled G:/projects/Node-webkit/ledger` from the command line the project runs just fine. But I get this annoying error every freaking time. I tried to Google for the error but no info found. This error also occurs when doing a blank `nw.exe --logging-enabled` execution (without project).

**Log**
`[2372:0202/110951:ERROR:network_change_notifier_win.cc(157)] WSALookupServiceBegin failed with: 0`

**Versions**
node-webkit v0.11.6
node.js v0.11.13-pre
Chromium 38.0.2125.104
##

**Comment by denised** [comment]
Any notes on this?  I get it too.

**Comment by dmouton** [comment]
I get it too

**Comment by Christywl** [comment]
Run `nw.exe --logging-enabled`, don't see the log file. So I use `nw.exe --enable-logging --v=1`, don't see this error in chrome_debug.log file. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information
