### ISSUE TITLE
Nodewebkit - when will upgrade version 38 to 40? Google chrome stable is now 40

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#3052]
Nodewebkit community is very very very very slow on keeping the Google  Chrome stable version with Nodewebkit version. 

Still its version 38 where Google Chrome stable is 40 and very soon it will be 42, there are hundreds of bug fixes above v38.

Can anyone be serious in Nodewebkit team or make a easy way so that (we) can migrate / inject the latest versions too ourself? (some easy tutorial how to do it ourself).

We need this tracking and upgrade because many apps only working in v40, v42 but not anymore in v38. Please consider it as important and give us some solution for this.

![screen shot 2015-02-04 at 06 10 39](https://cloud.githubusercontent.com/assets/107349/6035546/1f6262b2-ac36-11e4-88c6-cce1db9c5ecf.png)

**Comment by ghostoy** [comment]
Please test with [nw.js 0.12](http://nwjs.io/), which is based on Chromium 41.

**Comment by rogerwang** [comment]
We have been testing with the upcoming v0.12 release and will reach beta soon. After nw13 we will bring some changes and will rebase to new upstream faster, hopefully we'll reach our goal to release on every upstream version in this year.
