### ISSUE TITLE
Shared memory creation failed; out of file descriptors

### ISSUE THREAD

**Issue by tonypee** [nwjs/nw.js#3055]
In 11.5 and 11.6 ( i have been stuck on 10.5 for a long time) i get an error:

[2351:0204/211544:WARNING:shared_memory_posix.cc(386)] Shared memory creation failed; out of file descriptors

quite often. it means that resources in my app (for instance, <img>'es fail to load) - they come up as broken images. It causes other issues too (like crashes.. probably other code missing for example) 

in the console i have:

Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES 

any ideas?
##

**Comment by tonypee** [comment]
noone else get this?

**Comment by Montoya** [comment]
I just ran into this problem. I have an app that loads up tons of images. Never was a problem in the browser or in frameworks like Cordova/Phonegap, but it's a problem here =/

**Comment by tonypee** [comment]
This is not a node-webkit specific bug, as i tried electron js too - and that has the same error. It is due to the loading of the assets over the file:// protocol, rather than http://. Looks like chromium has made a change that breaks this. 

If you load the assets more slowly - then you will not have errors. I spaced my image loads out over 1 second. Either that, or serve your assets via http (you could run an express server from the node code- but this seems excessive.. however, works)

**Comment by Montoya** [comment]
OK, that worked for me, I had to load images more slowly. Still seems like a huge problem... there should at least be a better workaround than intentionally making my app run slower.
