### ISSUE TITLE
SSL error when requestCert = true

### ISSUE THREAD

**Issue by ldstein** [nwjs/nw.js#3056]
Assume the following simple HTTPS server:

```js
var https = require('https');
var fs = require('fs');

var options = {
    requestCert: true,
    key: fs.readFileSync (path_to_valid_key),
    cert: fs.readFileSync(path_to_valid_cert)
};

https.createServer(options, function (req, res) {
    res.writeHead(200);
    res.end("hello world\n");
}).listen(8000);
```

'Hello World' is displayed in all major web browsers and also returned by curl (```curl -v -s -k https://site_name.com:8000).

However trying to access the same URL via Node-Webkit:

```
require('nw.gui').Window.open('https://site_)name.com:8000')
```

Results in a blank window. It looks like it is silently failing during the TLS handshake.

However, if I set ```requestCert``` to false, "Hello World" is successfully loaded in Node-Webkit.

Any suggestions on why ```requestCert``` is only affecting Node-Webkit and not other major browsers / Curl?

**Comment by thojansen** [comment]
see #893 .. client certificates are not passed or not fetched correctly

**Comment by rogerwang** [comment]
close as the duplicate. it's now fixed in that issue.
