### ISSUE TITLE
<select> crash on OSX on version higher v0.10.5. OK in Win

### ISSUE THREAD

**Issue by jsys** [nwjs/nw.js#3057]
This simple code crash on Mac OS (10.6.8) when I click on the select.

``` html
<html>
  <body>
    <select>
      <option>Value1</option>
      <option>Value2</option>
      <option>Value3</option>
    </select>
  </body>
</html>
```

| Version / OS | osx32 | osx64 | win32 |
| --- | --- | --- | --- |
| 0.10.5 | OK | - | OK |
| 0.11.0 | bug on focus out | - | OK |
| 0.11.2 | bug on focus out | - | OK |
| 0.11.5 | bug on focus out | - | OK |
| 0.12.0-alpha2 | bug on clic | bug on clic | OK |

I use node-webkit-builder and change version on options param.

With 0.12.0-alpha2 version :
2015-02-05 15:31:26.880 nwjs Helper[1128:107] -[NSPopUpButtonCell
drawFocusRingMaskWithFrame:inView:]: unrecognized selector sent to
instance 0x46dae0
2015-02-05 15:31:26.882 nwjs Helper[1128:107] An uncaught exception was raised
2015-02-05 15:31:26.883 nwjs Helper[1128:107] -[NSPopUpButtonCell
drawFocusRingMaskWithFrame:inView:]: unrecognized selector sent to
instance 0x46dae0
2015-02-05 15:31:26.891 nwjs Helper[1128:107] \* Terminating app due
to uncaught exception 'NSInvalidArgumentException', reason:
'-[NSPopUpButtonCell drawFocusRingMaskWithFrame:inView:]: unrecognized
selector sent to instance 0x46dae0'
##

**Comment by chaseWillden** [comment]
I'm not getting this same issue.
