### ISSUE TITLE
bug: 0.11.6 linux x64 dev tools

### ISSUE THREAD

**Issue by RIAEvangelist** [nwjs/nw.js#3059]
11.6 Linux 64 dev tools do not work. 

They show a solid black pane.

![broken dev tool 0.11.6](http://i.imgur.com/DVa5UiH.png)
##

**Comment by TriBlade9** [comment]
Could you provide more specific details? It seems to work fine for me in 0.12.0-alpha 3. Are you using single-instance mode?

**Comment by RIAEvangelist** [comment]
Please close if fixed in alpha 3.

This was in alpha 2
