### ISSUE TITLE
XMLHttpRequest to a local file returns e.request.status with value equal to 0

### ISSUE THREAD

**Issue by astoilkov** [nwjs/nw.js#3064]
I have scenario where I am using a framework which makes a XMLHttpRequest to a file that is in the project which calls the error method regardless of the file successfully requested because in the arguments the e.request.status is equal to 0.

```javascript
xhrLoad: function (e) {
  var request = e.target;
  // here the status = 0
  var status = request.status;
  var isSuccess = status >= 200 && status < 300 || status === 304;
  if (isSuccess) {
    this.callSuccess(request.responseText);
  } else {
    this.callError(request.statusText);
  }
}

```

**Comment by iwege** [comment]
The file protocal is always return the status code  as 0;

See the solution in jQuery:https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js#L17

**Comment by astoilkov** [comment]
My bad. Thank you very much for the help.
