### ISSUE TITLE
Windows can't be as small as you want in Windows

### ISSUE THREAD

**Issue by edi9999** [nwjs/nw.js#3065]
I'm trying to create very tiny windows to show only a bit of text at some positions of the screen.

In linux (running on xubuntu), the windows can get 'as small as you want', but on windows (windows 8), they seems to be a limit and the window has a minimum size of something like 30x10 (width X height).

Here's some sample code to reproduce:

# index.html

```
<html style="background-color:white">
Hi
</html>
```

# package.json

```
{
  "name":"test window",
  "main": "index.html",
  "window": {
    "toolbar": false,
    "frame": false,
    "width": 10,
    "height": 10,
    "position": "mouse",
    "min_width": 10,
    "min_height": 10,
    "max_width": 10,
    "max_height": 10
  }
}
```

I'm actually creating these windows programmaticaly but for the sake of simplicity I put an example of the main window.

I'm running on nw.js v0.12.0-alpha2

Here's a screenshot 

![image](https://cloud.githubusercontent.com/assets/2071336/6097491/b740fe86-afbf-11e4-9488-ddb0a2f602a3.png)

**Comment by edi9999** [comment]
Any ideas @rogerwang ?

**Comment by asheraScout** [comment]
I have the same problem.
The window can't be smaller than 132 x 38.
My system is Windows7 32bit and nw.js version is v0.11.13-pre.

**Comment by rogerwang** [comment]
looks like an upstream issue, please check http://code.google.com/p/chromium/issues/detail?id=442259

**Comment by edi9999** [comment]
They say it is windows that restricts frameless windows to have a minimum size:

**Comment by edi9999** [comment]
They say it is windows that restricts frameless windows to have a minimum size:


 > The reason this happens is because Windows imposes a minimum width based on the style flags of the window. The style flags must be set in a way that ensures features like minimize/maximize, resize, drag, etc work correctly. The minimum width is set implicitly, so we can't really control it.

**Comment by edi9999** [comment]
One way to work around is to use transparency and clickthrough https://github.com/nwjs/nw.js/pull/2859 to make the windows seem smaller
