### ISSUE TITLE
Allow window operations on any type of event

### ISSUE THREAD

**Issue by SEAPUNK** [nwjs/nw.js#3066]
Say I have this script:

``` javascript
window.onmousedown = do_this();

function do_this(){
  //win = nw.gui's Window
  win.maximize();
}
```

When I trigger a `mousedown` on the window, the window doesn't maximize. If I, on the other hand, use `onclick` instead, everything triggers fine. I'd like to be able to do window operations such as `maximize()` and `unmaximize()` on any event, including `mousedown` and `mousemove`.

I am using `Version 0.12.0-alpha2` on Windows 7, 32-bit.
##

**Comment by Strat-** [comment]
bump
