### ISSUE TITLE
Mouse events don't trigger on -webkit-app-region: drag elements

### ISSUE THREAD

**Issue by SEAPUNK** [nwjs/nw.js#3067]
I am using Version 0.12.0-alpha2 on Windows 7, 32-bit.
##

**Comment by KeitIG** [comment]
Same issue here on a Ubuntu-based distro.  `-webkit-app-region: drag ` is not working

**Comment by Strat-** [comment]
bump

**Comment by KeitIG** [comment]
Well, since 0.12, drag is triggered when `window.frame : false` for me.

**Comment by Strat-** [comment]
@KeitIG I'm talking about events such as `mouseover` and `click`.

**Comment by KeitIG** [comment]
Oh nevermind. It's not a bug, according to the doc:

```markdown
And note that if you have made the whole window draggable,  you must also **mark buttons and custom window buttons as non-draggable**, otherwise it would be very hard for users to click on them:
```

**Comment by Strat-** [comment]
@KeitIG - They're not buttons. The doc refers to if the buttons have a draggable area, it would be *hard* to click on the buttons, not impossible, because if you click and drag, it would trigger the window drag event.

**Comment by Strat-** [comment]
I'm talking about programmatical events. For example, if you have an area that is `-webkit-app-region: drag`, and then did an `$("#area").on("mouseover", function(){console.log("okay");});`, the console wouldn't say "okay".

**Comment by KeitIG** [comment]
This is exactly what I'm talking about, when I read ` you must also **mark buttons and custom window buttons as non-draggable**`, the doc mean you attach events to them. And these events can't be triggered because of `-webkit-app-region: drag;` which has priority over events

**Comment by Strat-** [comment]
@KeitIG Well, I consider this an issue anyway, and it should be fixed. Draggable regions should still emit events.
