### ISSUE TITLE
Latest version of nodewebkit is used but how can i add document sharing extentions?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#3068]
With Canary, Chrome we have stable screen sharing extension which is working. 

Now i am using NW latest version: http://dl.nwjs.io/live-build/02-08-2015/c91494c-4aad9fe-dc10e62-add523e-40ccb71-c114bb7/

But How can i use the extensions with NW or make it compatible with NW?

**Comment by iwege** [comment]
I have done this before in nw 0.11 . You can add `"chromium-args" : "--enable-usermedia-screen-capturing"` in your package.json to enable the screen capturing API.

https://github.com/iwege/getScreenMedia

**Comment by shamun** [comment]
@iwege: I will test myself and update this follow up later.

I need to make this compatible with NodeWebkit, have you used this one from Henrik? e.g: https://github.com/HenrikJoreteg/getScreenMedia/tree/master/chrome-extension-sample

**Comment by iwege** [comment]
@shamun 
I changed this library, see this commit : https://github.com/iwege/getScreenMedia/commit/c9c47c6fe1e4ef4ab36927e1226068adf92ea6d5

And I wrote a sample for node-webkit:
https://github.com/iwege/getScreenMedia/tree/master/node-webkit-sample

**Comment by shamun** [comment]
@iwege: i just used it with nodewebkit 12(alpha) and working. But please note following:

- Quality of capture is slow
- Quality of screen capture is not crisp and clear

Compared to Canary, Google Chrome Stable the speed and quality is much better. Why is it not similar with nodewebkit and your solution, any idea please?

**Comment by iwege** [comment]
@shamun 
Maybe you can change those options:https://github.com/iwege/getScreenMedia/blob/c9c47c6fe1e4ef4ab36927e1226068adf92ea6d5/getscreenmedia.bundle.js#L35

But I don't know how to change the quality of screen capture. Changing the video size to the window size is a good solution for me. 
https://github.com/iwege/getScreenMedia/blob/master/node-webkit-sample/index.html#L18

**Comment by shamun** [comment]
@iwege: i will close this issue as its fixed. And open issue in your issue repository for the quality follow up (Which is other topic)

Thank you for your support, appreciate it, i will play with your suggestion i think it has to do with the tuning of resolutions and framerate somewhere.

**Comment by shamun** [comment]
@iwege: you do not have issue tracker there. I wanted to inform you that. In Google Chrome/Canary when i click screen share i get a small popup to select : screen1 or screen2 or running applications.

With your solution how can i have that selection dialog window please?

**Comment by iwege** [comment]
@shamun I don't find any solution for it. Maybe you need to follow those issues: https://github.com/nwjs/nw.js/issues/576

**Comment by shamun** [comment]
OK 

- [here on #576](https://github.com/nwjs/nw.js/issues/576) follow up posted

**Comment by shamun** [comment]
@iwege: do you know any updates on this issue yet? https://github.com/nwjs/nw.js/issues/3077

**Comment by iwege** [comment]
@shamun sorry, I don't know.
