### ISSUE TITLE
Can you please implement functions for input simulation.

### ISSUE THREAD

**Issue by plasmashadow** [nwjs/nw.js#3070]
i am a fan of node-webkit but i don't find any inbuilt functions for input simulation. such as click, moving mouse typing etc. I kind kindly request you to have these kind of feature in your roadmap.

**Comment by Paxa** [comment]
In what case you need it?

**Comment by plasmashadow** [comment]
combined with webrtc support for node-webkit. This allows the node-webkit be a gateway for remote-desktop control over webrtc.

**Comment by plasmashadow** [comment]
It will help to create more interactive applications using node-webkit.
