### ISSUE TITLE
Release infrastructure

### ISSUE THREAD

**Issue by lorddoig** [nwjs/nw.js#3071]
Just a few (hopefully useful) suggestions.

An RSS feed or something like a parseable `listing.txt` file at dl.nwjs.io would be great and allow easy unofficial mirroring (lack of mirrors has bitten me more than once).  A `/stable/` symlink would be useful too.

Regarding security, there isn't actually any way to get the binaries except over plain HTTP, right? So a security-conscious setup would have to build from source for 3 platforms and 2 architectures which seems like a lot of duplicated effort. Echoing #3062 - it would make me kind of nervous auto-updating/building from dl.nwjs.io with neither HTTPS nor PGP signing in place, so a strong +1 to both of those (especially PGP).

Related: #233. 
##

**Comment by rogerwang** [comment]
Thanks for the suggestion. Will provide it with automatic release script. Currently only 'live-build' folder is automated.
