### ISSUE TITLE
Using application cache in iframe

### ISSUE THREAD

**Issue by omg-a-bear** [nwjs/nw.js#3072]
I'm using v.0.12.0-alpha2.

I'm trying to implement a part of a website in an NW.js application, and simply referring to a web page in an iframe:

```
<iframe src="http://mydomain.com/mypage.html"></iframe>
```

This works well when the application has an internet connection, but I also want to be able to show a cached version when the application is offline. So I set up the "mypage.html" to serve an HTML5 Application Cache manifest, with all resources specified:

```
CACHE MANIFEST

CACHE:
mypage.html
images/image.png
css/default.css

NETWORK:
*
```

This works well when trying it out in a browser (Chrome) and in offline mode, even when I dynamically add an iframe pointing to "mypage.html" the cached version is presented.

However, the NW.js-application doesn't seem to treat the iframed version as available in cache - the inspector shows the regular error of _net::ERR_INTERNET_DISCONNECTED_.

When the application is online, I can see the standard output from using a HTML5 Application Cache, in the inspector - i.e. "Application Cache NoUpdate event" etc. So the application recognises the page as an HTML5 Application, I can even inspect the application under "Resources". But when serving it offline nothing happens, the "Resources" tab is empty (under Application Cache).

Am I missing something or is there some restrictions under NW.js?

Best regards,
##

**Comment by omg-a-bear** [comment]
Update:

This works as expected in v0.8.6. The webpage is showing even though the computer doesn't have an internet connection.

**Comment by pakastin** [comment]
I can confirm appcache doesn't work after 0.11.6

**Comment by ghosert** [comment]
Yes, please, I don't see this work after 0.11.6 as well. Means, if you are in the offline mode, you can't reopen node-webkit by reloading the application cache resources.

**Comment by shaynem** [comment]
reference  #3361
