### ISSUE TITLE
Custom JS promts

### ISSUE THREAD

**Issue by cristianfraser** [nwjs/nw.js#3073]
Is it possible to have custom alert(), confirm() and prompt() boxes? Adding title and custom labels for the buttons.

For example, it'd be useful if the confirm dialog had `No` and `Yes` instead of `Cancel`/`OK`, and have a custom title too. Currently, nwjs only displays the alert text, with no title.

Something like this, with custom title and button labels.
![](http://dbushell.com/wp-content/uploads/2012/02/macosx-confirm1.png)

**Comment by tommoor** [comment]
Absolutely, you can launch a new window, position it and render the content in html. Have a look at the Window API: https://github.com/nwjs/nw.js/wiki/Window

**Comment by cristianfraser** [comment]
Thanks for replying about JavaScript prompts with a link to the Window API...

**Comment by Strat-** [comment]
@cristianfraser Well, you can't really "style" prompts with the regular `alert()` `confirm()` and `prompt()` boxes. You're better off writing a small library that opens up new windows with their custom views for that sort of thing.

**Comment by cristianfraser** [comment]
@Strat- I know, but desktop apps all have their alert notifications and I was wondering if nwjs had them or there were plans to. Maybe asking about customising js prompts for nwjs was the wrong way to ask this, but I don't see the point on @tommoor answering something that wasn't asked in that way...

**Comment by tommoor** [comment]
@cristianfraser I wasn't being obtuse, if you want to create a custom prompt the best way to do it is probably with the Window API, you have full control of everything then. I believe the aim of prompt, alert etc is to be compatible with existing javascript API's.

We're also trying to keep questions out of the issues and instead direct them towards the community chat and google groups :smile:

**Comment by jakehh** [comment]
Alertify sounds similar to what you want.

http://fabien-d.github.io/alertify.js/

**Comment by Strat-** [comment]
@cristianfraser Most desktop apps aren't built with NW, so in that sense, you don't have as much flexibility as to how you want windows designed.

**Comment by smolleyes** [comment]
hi

i use this for alerts, confirm ...

http://tristanedwards.me/sweetalert

works great :p

++

**Comment by cristianfraser** [comment]
@tommoor I'm sorry for misreading you then.

Anyway, it'd be nice if JS prompts showed the name of the app per default, showing the text only feels empty.

**Comment by lashanchenqi** [comment]
Some guys above advise to take the place of  native Alert   with  JS Alert .  
 What you have missed is that  the former  can block the UI but  the latter can not. 
Huge numbers of  web apps  right   take  the advantage  of that  blocking  where you can not use  js Alert instead.

remark：there are still bugs about  Alert   Confirm  . See： https://github.com/nwjs/nw.js/issues/3980
I eager to wait its fix.
