### ISSUE TITLE
Empty default app on old Windows XP

### ISSUE THREAD

**Issue by brospars** [nwjs/nw.js#3078]
My app works fine in most cases but somehow display a empty node-webkit app when launched in a specific version of windows xp embedded (service pack 3) on a old Samsung touch terminal.

![capture](https://cloud.githubusercontent.com/assets/5736114/6147932/ddeb4d0e-b1fc-11e4-93ed-32225f683786.JPG)

However the app works fine if I type the file url in the adress bar.. Even on a second Samsung terminal (Windows XP too) the app works fine.

I'm a little out of idea at this point, so any help would be great !
##

**Comment by Strat-** [comment]
How did you run the app?

**Comment by benuts** [comment]
I built the app.exe : ``copy /b nw.exe+app.nw app.exe `` on my dev pc
And then simply run the app.exe on others terminals (it works fine on most, but not this one :s )

I've also tried to build the app and run it directly on this pc but it isn't working either.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by brospars** [comment]
I don't know it was at my old job, I can't test it anymore...

**Comment by Christywl** [comment]
Close this issue. Once you meet this again, please reopen it or file a new issue.
