### ISSUE TITLE
Highlighting words (spellcheck-like)

### ISSUE THREAD

**Issue by cristianfraser** [nwjs/nw.js#3079]
I know spellcheck is an issue already (https://github.com/nwjs/nw.js/issues/332), but I was wondering if there was an API or something for highlighting words (with the red dotted line) available or not.

**Comment by adam-lynch** [comment]
Hey @cristianfraser, I'm not sure but maybe ask in the [Google group](https://groups.google.com/forum/#!forum/nwjs-general)
