### ISSUE TITLE
create a child process :option "detached:false" doesn't work.

### ISSUE THREAD

**Issue by HC1988** [nwjs/nw.js#3080]
I created a nw app,with cmdline comond: nw main  ,and 'main' is my work directory with a package.json.  then that be used: require('child_process').spawn('calc',[],{detached:false});  . this calc can be started. but when i closed my App including the process, this calc still be there. My OS is windows 7, and with node-webkit-v0.8.6- win-ia32. This app project is big . but when I use a little demo of project with other version of nw, it works well. I want to know why? It is a reason of environment ?  thank you for any answers.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
