### ISSUE TITLE
Global shortcuts don't seem to work in Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by nknapp** [nwjs/nw.js#3084]
I tried to register a global shortcut with Ubuntu 14.04.1 LTS, nwjs 0.12.0-alpha2 with the following code-snippet

```
// Load native UI library.
var gui = require('nw.gui');

var option = {
    key : "a"
};

// Create a shortcut with |option|.
var shortcut = new gui.Shortcut(option);



// Register global desktop shortcut, which can work without focus.
gui.App.registerGlobalHotKey(shortcut);


shortcut.handleEvent = function(ev) {
    console.log("event:");
    console.log(ev);
}
```

I used `shortcut.handleEvent = function()` in order to catch _all_ events, not just `active` and `failed` because I never got any console output. 
With this code, I notice that the `a` key is not working anymore globally (in shells, editor, etc.), but neither do I get a console-output from the event handler.

When I change `key: "a"` to `key: "aaa"`, I receive a `failed`-event, so this part seems to work. I never receive an `active` event though, even if I press the `a`-key
##

**Comment by nknapp** [comment]
Duplicate of issue #3199

**Comment by Christywl** [comment]
The following code works fine on Linux with nwjs-sdk-v0.24.2.
```
<script>
            var option = {
              key : "a",
              active : function() {
                alert("Global desktop keyboard shortcut: " + this.key + " active.");
              },
              failed : function(msg) {
                console.log(msg);
              }
            };

            var shortcut = new nw.Shortcut(option);
            nw.App.registerGlobalHotKey(shortcut);
</script>
```

**Comment by nknapp** [comment]
I can confirm, that is working with nw 0.24.3 and Ubuntu 16.04
