### ISSUE TITLE
show: false and fullscreen: true doesn't work together on windows (but works on linux)

### ISSUE THREAD

**Issue by hogart** [nwjs/nw.js#3085]
My package.json:

``` json
{
  "name": "test",
  "main": "index.html",
  "window": {
    "show": false,
    "fullscreen": true
  }
}
```

Intended effect is full-screen application, initially hidden and showed by some other means. Given package.json works fine on linux (Unity DE, more precisely), but on Win7 application is visible from start. Tested on 0.12.0-alpha2 and latest live build.
##

**Comment by mizhigang407** [comment]
I have the same problem,No one has any ideas?

**Comment by Christywl** [comment]
I try your package.json on Windows with nwjs-sdk-v0.24.2. The app isn't visible.

**Comment by Christywl** [comment]
close until there is more information.
