### ISSUE TITLE
[Version 0.12.0-alpha3] process.version showing as 1.2.0 but should be v0.12

### ISSUE THREAD

**Issue by JavaScriptDude** [nwjs/nw.js#3087]
Not sure if this a legacy issue but process.version is showing 1.2.0 when it should be 0.12.0.

**Comment by KenRmk** [comment]
process.version returns version of node.js not node-webkit. And NWJS 0.12 migrated from node.js to io.js version 1.2.0. Take a look here https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md

**Comment by JavaScriptDude** [comment]
Makes sense. I missed the post that the project was migrated to io.js.
