### ISSUE TITLE
Smooth scrolling?

### ISSUE THREAD

**Issue by groovy354** [nwjs/nw.js#3093]
Is there a way to enable smooth scrolling in nw.js apps? Currently the scrolling is jittery... I know that Chrome has an "--enable-smooth-scrolling" flag, can I somehow enable it in my app?

**Comment by Thiht** [comment]
I'm interested on this too, is there a reason for not enabling it by default ?

**Comment by FFAxKenny** [comment]
@groovy354 - sounds like your issue has been resolved. Please close :)
