### ISSUE TITLE
Loading bootstrap.css is very slow on Windows

### ISSUE THREAD

**Issue by wangyanxing** [nwjs/nw.js#3096]
Loading bootstrap.css(~140K) is very very slow on windows, ~15 to 20 seconds.

For now it takes me ~20s in total to start the app. If I delete the css files, the loading would be very fast.

I also tried LazyLoad.js, nothing changes actually.

Mac has no such problem. I am using the latest version of nw.js.
Thanks!
##

**Comment by Alexufo** [comment]
Rename any text file simular to file size  css to bootstrap.css and try again.
 Speed still slow?)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
