### ISSUE TITLE
Content visible behind corners with transparent: true

### ISSUE THREAD

**Issue by cristianfraser** [nwjs/nw.js#3098]
In OSX, with frame: false, transparent: true, I get rounder corners on top. I'm playing with some CSS to hide a portion of my app by going up, but when it goes up the corners are "filled" by this and don't remain transparent.

I consider this a bug, is it?
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
