### ISSUE TITLE
Can not run nw

### ISSUE THREAD

**Issue by jsloyer** [nwjs/nw.js#3100]
I am trying to run nw on Raspbian.

I am getting the following error:

`pi@display-pi ~/.nw $ ./nw`

`-bash: ./nw: cannot execute binary file`

Anyone see this before?

**Comment by kohenkatz** [comment]
Are you using binaries that you downloaded from nwjs.io? Raspberry Pi is an ARM processor.  You need a version of NW.js that runs on ARM.  Binaries for that architecture are not currently available on nwjs.io - you'll have to build your own or find someone else who has built them.

**Comment by brandonpapworth** [comment]
I'd definitely love a version compiled for ARM to run on the Raspberry Pi. Maybe we should make a new Issue as a Feature Request?

**Comment by felicienfrancois** [comment]
#193

**Comment by jsloyer** [comment]
Closing as issue #193 covers this.

**Comment by jalbam** [comment]
Check this: https://github.com/jalbam/nwjs_rpi
