### ISSUE TITLE
nwjs alpha 3 devtools clipboard not working

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3101]
hi

when i try to copy something in the devtools i have

Clipboard is not enabled in hosted mode. Please inspect using chrome://inspect

and chrome://inspect is empty...

thanks
##

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by mqtstbh** [comment]
+1

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
