### ISSUE TITLE
Can't extract package when umlauts (ä,ö,ü) in folder/file names

### ISSUE THREAD

**Issue by Witchtower** [nwjs/nw.js#3102]
Recreation of Error:
create folder or file with umlauts: "testä/whatevär.html"
zip them with package.json, rename to "*.nw" start with nw.exe.

Tested on Windows 7. 
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8.1 with nwjs-sdk-v0.24.2.

**Comment by Christywl** [comment]
close until there is more information.
