### ISSUE TITLE
Newly opened window in frameless is not frameless

### ISSUE THREAD

**Issue by groovy354** [nwjs/nw.js#3105]
I'm developing a frameless application (`frame: false` in `package.json`). The first window is in fact frameless, but each consecutive window opened with `gui.Window.open` does have frames (and a menu-bar!). How to make the new windows frameless?
I'm using `Ubuntu 14.04` with `Gnome 3.12` and `node-webkit v0.11.6`

**Comment by RIAEvangelist** [comment]
gui = require('nw.gui');
    gui.Window.open('http://google.com',{toolbar:false,frame:false});

![windowless image](http://i.imgur.com/uq80iEK.png)

**Comment by tommoor** [comment]
@RIAEvangelist the screenshot you posted is frameless, try seeing the difference when you pass frame: true

**Comment by tommoor** [comment]
@RIAEvangelist good answer :smile:

**Comment by RIAEvangelist** [comment]
@tommoor Thanks ;)

**Comment by groovy354** [comment]
Well, if opening a frameless window from a frameless window requires passing a parameter, then there's a discrepancy between the wiki page at https://github.com/nwjs/nw.js/wiki/Frameless-window and the actual state - the page states that if I have `frame` attribute set to `false` in `package.json`, "then your main window and windows opened by window.open will have no frames."

**Comment by RIAEvangelist** [comment]
@groovy354 good call!

**Comment by RIAEvangelist** [comment]
Doc updated

**Comment by gomestai** [comment]
using latest version fresh build, I'm experiencing same issue, from my frameless main window i can not open a frameless window. I declared `frame `attribute `false `in `package.json` 

both

`gui.Window.open('/xxx.html');`

and

 `gui.Window.open('/xxx.html',{toolbar:false,frame:false});`

not working
