### ISSUE TITLE
Hide Application Icon

### ISSUE THREAD

**Issue by hhsnopek** [nwjs/nw.js#3106]
Is it possible to hide the application icon from the application bar and create a **Tray Only** application?

I haven't found a solution nor has anyone responded in the gitter channel. Thank you for taking the moment to respond.

**Comment by cristianfraser** [comment]
https://github.com/nwjs/nw.js/wiki/Manifest-format#show_in_taskbar

**Comment by hhsnopek** [comment]
Thank you so much @cristianfraser
