### ISSUE TITLE
Transparency + frameless - resize broken in NW0.12 [$15]

### ISSUE THREAD

**Issue by Ivshti** [nwjs/nw.js#3108]
@jtg-gg can you look at this please?

Resizing a frameless transparent window is broken for NW 0.12 Alpha3. It seems to be related to this https://github.com/nwjs/nw.js/issues/1021

Keep it mind it works on a frameless non-transparent window.
I should also point out that it is not broken in Alpha2.

**Comment by FiatPax** [comment]
Indeed, I was wondering if it is from my codes. I have the same problem.

**Comment by Ivshti** [comment]
Hello. 

I found the issue with 80% certainty.

It seems when the rebase was done for NW 0.12, this fix last lost: https://github.com/nwjs/chromium.src/commit/30e20550bed65261147acc65139e4519c9d0ee1d

Essentially the window needs the WS_THICKFRAME style.

**Comment by jtg-gg** [comment]
@Ivshti I've committed the fix https://github.com/nwjs/chromium.src/commit/a1a1d6c3252bdd9319ac8d430fd52a56ecd7370c
wait for the live build

**Comment by Ivshti** [comment]
Hello,

This works for the latest live build, thank you @jtg-gg. I tried to fix it myself but I would have never thought WS_THICKFRAME has to be removed and not added.  Windows is confusing.

Anyway, in NW 0.11 there was an issue which caused sometimes, I can't figure out exactly why, transparent windows let clicks/hovers through even though their background is not transparent. This happened with/without ``--force-cpu-drawing --disable-gpu``. This seems to have disappeared in NW 0.12, but are you aware of this?

**Comment by EladBezalel** [comment]
:+1:

**Comment by jtg-gg** [comment]
@Ivshti I never experience that, if you can reproduce it, give me the sample code, I'll try to debug
