### ISSUE TITLE
Disable the "bounce" effect on scroll

### ISSUE THREAD

**Issue by nikkow** [nwjs/nw.js#3109]
Hello,

I'm using the latest alpha version of NW.JS (yes, I know, it's "only" alpha...). Thing is, I'm running it on Mac OSX 10.10 and I have this "bounce" effect when I want to over-scroll the page (top and bottom).

I read awhile ago that the Chromium team was not planning to fix it (see [here](https://code.google.com/p/chromium/issues/detail?id=111745)), as it is supposed to follow Apple's guidelines. However, is there a way to disable it in NW.JS? It clearly does not have the look of a native app with this ugly effect.

I've tried some tricks that are known to work on mobile Safari (settings the main container to absolute, etc...) but they're not working in that case. 

Thanks,
N.
##

**Comment by PierBover** [comment]
You could maybe control all the scrolling via JS and put all your content into a container with overflow hidden.

**Comment by nikkow** [comment]
I managed to disable de bounce effect by watching the scroll on the document. I put the JS code I used here: https://gist.github.com/nikkow/9e249af14d8607c5f649 
Since I don't need to have a scroll bar, I don't know how it reacts with scrollable div.

**Comment by ABeltramo** [comment]
@nikkow your code disable all the scroll in the page.
To only remove the bounce effect you should put this css trick
```
html, body {
  height: 100%;
  overflow: hidden;
}
```

**Comment by nikkow** [comment]
@ABeltramo thanks for the hint. It didn't work with 0.12-alpha3, when I opened the thread (just tested again with this version). It has been updated since then, and with the latest version (0.12.2) it is now working again.

**Comment by talldude** [comment]
I'd love to see this be a setting in package.json, or an App setting - the trick above for setting overflow to hidden DOES work, but it has the side effect of breaking scroll events in jQuery and you're left trying to hack in your own.

**Comment by fritx** [comment]
Thanks for tips from @ABeltramo, will try soon

**Comment by achekulaev** [comment]
This solution is not good. If content is longer then the window then it will not scroll.
You need this
```
html, body {
  height: 100%;
  width: 100%;
  overflow: auto;
}
html { 
  overflow: hidden;
}
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
