### ISSUE TITLE
`-webkit-app-region: drag` does not work with `toolbar: true` in `package.json`

### ISSUE THREAD

**Issue by kuba-orlik** [nwjs/nw.js#3110]
As stated in this [stackoverflow question](http://stackoverflow.com/questions/25735127/webkit-app-region-drag-only-allowing-drag-in-small-region-of-element), if app's package json has `toolbar` set to `true`, most of the area of elements with `-webkit-app-region: drag` does not enable the user to drag the window. 
##

**Comment by iwege** [comment]
To make your window frameless, you just need to add `"frame": false` in your app's package.json's window field, toolbar need to be disabled as well:

https://github.com/nwjs/nw.js/wiki/Frameless-window

**Comment by groovy354** [comment]
So it's a feature, not a bug?

**Comment by Christywl** [comment]
`toolbar` is deprecated and it’s always false. 
http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by Christywl** [comment]
close until there is more information.
