### ISSUE TITLE
How to make request from web to nw.js app?

### ISSUE THREAD

**Issue by nidhin001** [nwjs/nw.js#3111]
I'm developing an application in nw.js and also I do have a website. I need to do something on nw app when an action is done in the website. Can we make requests to nw app from website ? Or is there any better way to do this ?

**Comment by Wortex17** [comment]
Which browser is used to open the website? Your app itself or an 'external' (i.e. chrome, firefox, ie, another nw.js app)

If it is opened inside your app, there are a multitude of ways including whitelisting your website for nodejs use, which would enable direct communication between the environments, to [cross-document messaging](http://ejohn.org/blog/cross-window-messaging/).

If they are not, your best bet would be to use nodes [TCP or UDP capabilities](http://nodejs.org/api/net.html) to let the client communicate with the server. If you dont want another communication interface on your server, you can communicate with good old REST calls, again from the node context, e.g. using [unirest](http://unirest.io/nodejs.html), allthough they are harder to manage (in terms of push/pull cycles) than socket based solutions.

**Comment by mrfabbri** [comment]
Hi @nidhin001 as @Wortex17 there are many ways to do this (you may also take a look at websockets and socket.io), depending on the architecture of your system, please note that this sort of discussion are more pertinent (and better addressed) to the mailing list
