### ISSUE TITLE
nwdirectory does not returns the folder path properly

### ISSUE THREAD

**Issue by andrewdex** [nwjs/nw.js#3112]
As guided in the Documentation, i have used <input type="file" nwdirectory /> to choose a directory and get the directory path, but as the result value, i get all the file path values inside the directory. Example implementation is below,

<input id="choose" type="file" nwdirectory />

//Choose File
    var chosen = document.getElementById("choose");
    chosen.addEventListener("change", function (evt) {
 
        dir = this.value;
            
        console.log(dir);
     
 }, false);

//Console returns all the file paths instead of the directory path

**Comment by felicienfrancois** [comment]
Known bug in 0.12.0-alpha1 to 0.12.0-alpha3 #2961
Fixed in git https://github.com/nwjs/nw.js/issues/2961#issuecomment-75163873
Will be shipped in next release

**Comment by andrewdex** [comment]
@felicienfrancois , Thanks for the update !
