### ISSUE TITLE
Possibility of Nw.js and JXCore?

### ISSUE THREAD

**Issue by sashahilton00** [nwjs/nw.js#3113]
##

**Comment by sashahilton00** [comment]
JXCore has just been open sourced here: https://github.com/jxcore/jxcore and brings a whole raft of features which would make nw.js a feasible option for a peoduction environment, including multithreading, and source encryption. Is there any chance of switching from node to jxcore, given the advantages?

**Comment by felicienfrancois** [comment]
+1

**Comment by SgtConti** [comment]
+1 Adding Multithreading this easy would be huge.

**Comment by sashahilton00** [comment]
@rogerwang any views on this?

**Comment by sashahilton00** [comment]
bump

**Comment by rogerwang** [comment]
This is interesting. But it need some time to be looked into ... currently I'm focused on NW13 development.

**Comment by CrandellWS** [comment]
+1

**Comment by LinkTree3** [comment]
Are there any updates on this?

**Comment by makkesk8** [comment]
multi threading is very very appealing feature of jxcore, I would very much like to see this as a replacement for node.js in node-webkit

**Comment by DaniellMesquito** [comment]
Replacement? Can node.js and jxcore work togheter, or simulate jxcore features with a node.js package?

**Comment by rogerwang** [comment]
Merge with #2650.Now we implemented Node.js support in WebWorkers, so NW programmers can write multithreaded JS code in this way.
