### ISSUE TITLE
EADDRINUSE from within node context (node-main)

### ISSUE THREAD

**Issue by diimdeep** [nwjs/nw.js#3115]
package.json:
```
    "main": "app/index.html",
    "node-main": "app/index.js",
```
index.js:
```
exports.init = function() {
    var httpProxy = require('http-proxy')

    default_router =  {
    }
    var router = default_router

    var options = {
        router: router
    }

    var proxyServer = httpProxy.createServer(options);
    proxyServer.listen(8088);
};
```

If run function from index.html - OK.
```
    <script>
        process.mainModule.exports.init();
    </script>
```
if run function from node-main:

```
[16966:0221/142943:ERROR:nw_shell.cc(325)] Error: listen EADDRINUSE :::8088
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1153:14)
    at listen (net.js:1179:10)
    at Server.listen (net.js:1266:5)
    at ProxyServer.listen (node_modules/http-proxy/lib/http-proxy/index.js:135:16)
    at Object.exports.init (app/index.js:35:17)
    at Object.<anonymous> (app/index.js:38:9)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
```

**Comment by mrfabbri** [comment]
It seems you have some other service running and bound to the port 8088 (that's what EADDRINUSE suggests).

**Comment by diimdeep** [comment]
Why is it then work when I run it from browser context ?

**Comment by mrfabbri** [comment]
@diimdeep my wild guess is that your are calling `exports.init()` twice.

**Comment by diimdeep** [comment]
This might be relevant https://github.com/nodejitsu/node-http-proxy/issues/777#issuecomment-75379382, thus problem in library.

**Comment by drschwabe** [comment]
Same problem with this simple express example, runs fine in vanilla node: 
```
var express = require('express'),
    app = express()

var server = app.listen( 5001 , function() {
  console.log('Listening on ' + server.address().port);
})
```
But throws error in nw: 
```
events.js:125
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE :::5001
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1153:14)
    at listen (net.js:1179:10)
    at Server.listen (net.js:1266:5)
    at EventEmitter.app.listen (/home/derrick/dev/g/scrollcraft/demos/nw/node_modules/express/lib/application.js:595:24)
    at Object.<anonymous> (/home/derrick/dev/g/scrollcraft/demos/nw/server.js:4:18)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
[23325:0420/220710:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```
express does not require node-http-proxy as a dependency.

**Comment by Nullpo** [comment]
Currently I'm having the same problem :(.

**Comment by jgoalby** [comment]
@Nullpo could it be related to node main being called twice such that the port you specify is taken up by the first invocation?  See these:

https://github.com/nwjs/nw.js/issues/3248
https://github.com/nwjs/nw.js/issues/2981

**Comment by brzpegasus** [comment]
@diimdeep Yes, that is exactly why. The `node-main` script runs twice. I ran into something very similar and had to initialize the proxy server from the main app, just like you did with `process.mainModule.exports.init();`

**Comment by iw2rmb** [comment]
Confirm same problem. Can issue be reopened?

**Comment by jgoalby** [comment]
Does the workaround in 2981 not remove your issue?  It removed the issue for me, and it does appear to be a little hacky as a real solution would be preferable, but I think there are bigger issues that don't have workarounds?

**Comment by iw2rmb** [comment]
@jgoalby agree with you — there are workarounds, they just seems risky to me (forget about some global variable on page refresh, for example).

**Comment by jgoalby** [comment]
I agree @iw2rmb.  The issue I see is that while there is work happening on version 13, version 12 seems to be in some kind of limbo.  I look at the activity on electron and wonder if the grass is greener.  A few apps made the transition.  I don't particularly want to, but short of fixing things myself I am not sure how some of these issues will get resolved.

**Comment by cyphunk** [comment]
The work around given in 2981 does not work (nwjs-v0.12.3-linux-x64). Has anyone seen any other possible solutions/hacks around this problem?

**Comment by WolfieWerewolf** [comment]
My experience with this error message is simply that there's an orphaned process holding onto the socket..  Out of curiosity what happens if you reboot and test again?

**Comment by WolfieWerewolf** [comment]
BTW I'm not suggesting a reboot as a fix, just a test :-)

**Comment by cyphunk** [comment]
Yeah I thought about this and changed the port it is attaching to with the exact result.

**Comment by WolfieWerewolf** [comment]
If you were keen to zip up a sample test case I'd be interested in troubleshooting this for you...  Also let me know exact versions of everything you're using including your OS and Kernel.

**Comment by cyphunk** [comment]
http://cypherpoet.com/tmp/temp has a .js package.json and .html. Installed requirements with ``npm install --runtime=node-webkit --target=0.12.3`` and executed nw 0.12.3 with ``nw .``. This was on ubuntu 14.04 lts vm with kernel 3.13.0-77-generic

**Comment by WolfieWerewolf** [comment]
Cool thanks.  I'll be able to look at this over the next couple of days.  I'll let your know, first off, whether or not I'm able to duplicate the issue.  That should at least point us in the right direction.

**Comment by WolfieWerewolf** [comment]
Mate I haven't forgotten about you.. just up to my you know what with customer stuff... just wanted to let you know.  I have to install all this on a vm somewhere....

**Comment by cyphunk** [comment]
no worries.
