### ISSUE TITLE
Clean machine dependencies?

### ISSUE THREAD

**Issue by zalow517** [nwjs/nw.js#3117]
Hi all, I'm still new to all this node-webkit stuff but it looks really interesting!

I was wondering if once the 'node_modules' folder is included in the node-webkit application distributable, this can then be deployed on a machine without the need for NodeJS and the other npm packages that are in the 'node_modules' to be installed manually?

That's all... thanks!

**Comment by mrfabbri** [comment]
Hi @zalow517 have a look at [How-to-package-and-distribute-your-apps](https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps), short answer: once the app is packaged it contains also the node_modules and NW.js (hence node or iojs depending on the version).

Please note that this sort questions are better addressed on the mailing list.
