### ISSUE TITLE
Error when trying to change the URL from the menu (the second time) [$15]

### ISSUE THREAD

**Issue by johnlindquist** [nwjs/nw.js#3118]
It always works once, then the second time it throws a
```"Uncaught Error: Unable to get render view in CallStaticMethodSync"```

Video of issue: http://www.screencast.com/t/hVZ9ZALU

``` js
var nw = require('nw.gui');
var menu = new nw.Menu({
    type: 'menubar'
});

menu.createMacBuiltin("Demo");

var submenu = new nw.Menu();
submenu.append(new nw.MenuItem({
    label: 'Lesson 1',
    click: function click() {
        nw.Window.get().window.location = "http://google.com";
    }
}));

submenu.append(new nw.MenuItem({
    label: 'Lesson 2',
    click: function click() {
        nw.Window.get().window.location = "http://yahoo.com";
    }
}));

menu.append(new nw.MenuItem({label: "Lessons", submenu: submenu}));

nw.Window.get().menu = menu;
```

**Comment by rogerwang** [comment]
This is because the menu API is privileged and can be run in Node frames only. I'll see how to fix this. In the mean time, you can add the domain in 'node-remote' in manifest: https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote
