### ISSUE TITLE
window.close() Won't Close

### ISSUE THREAD

**Issue by FiatPax** [nwjs/nw.js#3119]
Have an element like this:

`<a id="why" href="#">click here</a>`

after clicking on it, running window.close() gives this error:

```
"Scripts may close only the windows that were opened by it."
```
##

**Comment by liyingzh** [comment]
It's not reproduced.

The window closed corectly  with ````<a href="javascript:window.close();">click here</a>```` in  nw v0.12.0-rc1.

**Comment by SystemZ** [comment]
I had the same issue like @FiatPax using nwjs-v0.12.0-rc1-linux-x64 build.
Solution was... restarting nw.js.
Seems that refresh from toolbar is blocking `window.close()`

**Comment by FFAxKenny** [comment]
Was able to reproduce the issue; @SystemZ is right - the refresh from the toolbar appears to be blocking window.close() since it spawns a new page? Appears to be a browser security feature....

**Comment by fucazu** [comment]
You can close using this function
```javascript
function winclose() {
  var gui = require('nw.gui');
  var win = gui.Window.get();
  win.close();
}
```

**Comment by FFAxKenny** [comment]
@fucazu: the issue still occurs for me if i use the call that comes from gui.Window.get(). Can you confirm?

**Comment by fucazu** [comment]
@FFAxKenny: I was able to reproduce the error. Using the function that I suggest its a workaround for this issue.

**Comment by benag** [comment]
var gui = require('nw.gui');
var win = gui.Window.get();
win.close();

doesn't work in framless window, amazing!

**Comment by mitselek** [comment]
+1: Can't close frameless window on osx with window.close()

**Comment by Christywl** [comment]
I can't reproduce on nwjs-sdk-v0.24.2. Please run your test on the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
