### ISSUE TITLE
[Windows] High DPI support does not work via chromium-args

### ISSUE THREAD

**Issue by chennney** [nwjs/nw.js#3120]
Adding `--high-dpi-support=1 --force-device-scale-factor=1` in the chromium-args field does not work.  However, these params do work when launching via command line, i.e., `nw.exe app.nw --high-dpi-support=1 --force-device-scale-factor=1`.
##

**Comment by mscreenie** [comment]
@chennney  Do you know if this fixed in nw12?

**Comment by chennney-highfive** [comment]
@mscreenie nw12 seems to ignore these flags from command line and chromium args.  Not sure if this is intentional, but it seems the high-dpi-support is enabled by default and does not require these extra chromium args.

**Comment by chennney** [comment]
@mscreenie nw12 seems to ignore these flags from command line and chromium args. Not sure if this is intentional, but it seems that high-dpi-support is missing: #2998

**Comment by GitYong** [comment]
same issue here

**Comment by Christywl** [comment]
Seem it works fine on Windows with nwjs-sdk-v0.24.2. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
