### ISSUE TITLE
[Windows] NPAPI plugins on Windows are not loaded when inside app.nw /plugins folder

### ISSUE THREAD

**Issue by chennney** [nwjs/nw.js#3121]
On Windows, adding a plugin into an app's /plugins folder does not seem to work.  This does work on Mac.  The current workaround on Windows is to add the chromium-args `--load-plugin=app.nw\\plugins\\plugin.dll`.  
##

**Comment by ghostoy** [comment]
On Windows, the dll file name should be in form of `np*.dll`.

**Comment by Christywl** [comment]
Please follow http://docs.nwjs.io for the latest nwjs build.
`Put the plugin files (including ‘manifest.json’ of it) in the ‘PepperFlash’ subdirectory under NW.js binary`. It works fine for me on nwjs-sdk-v0.24.0.

**Comment by Christywl** [comment]
close until there is more information.
