### ISSUE TITLE
SSL "--allow-running-insecure-content" won't work with chromium-args  [$5]

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3123]
Our app requires SSL through Node-Webkit while it does authentication. After authentication an iframe is created with SSL to prevent `MIMA` (man in the middle attacks) of Session ID's and leakage of other information.

When loading resources ranging from images or YouTube videos inside SSL iframe. Node-Webkit prevents loading non ssl resources even with a `--allow-running-insecure-content` chromium-argument.

This really halts our development and it's a *little* frustrating seeing `--allow-running-insecure-content` is a valid argument that works with Chromium. So.. **assuming** it was valid we started development. :sweat: 

I guess we should have checked to see if nwjs supported SSL connection fully (our fault) before starting development, theres even an issue about this back in 2013 https://github.com/nwjs/nw.js/issues/1113

Your help or suggestions are very much appreciated, even a work around would be nice!

Bug Reproduce-able on 11.6

**Comment by mscreenie** [comment]
If you need to reproduce this bug please try loading ANY website over SSL that has non-ssl resources inside nw-js by iframe.

**Example site** https://www.rackspace.co.uk


Loaded with Chrome 40 and you'll get the "Load Unsafe Scripts" bubble which you can accept or if you start Chrome with `--allow-running-insecure-content` the unsecured content will be loaded.


Doing the same with nw-js and inspecting network resources you will see the same unsecured files omitted from loading.

**Comment by mscreenie** [comment]
any update on this?

**Comment by rogerwang** [comment]
thanks for reporting. will see this before the next release.

**Comment by mscreenie** [comment]
Thank you very much @rogerwang . I will be supporting this project in the future.

**Comment by mscreenie** [comment]
12.0 released. will test to see if this was fixed.

**Comment by mscreenie** [comment]
Tested. This feature was not fixed for 12.0 stable.

**Comment by mscreenie** [comment]
12.0 released. will test to see if this was fixed. edit.. Tested. This feature was not fixed for 12.0 stable.

Just to add to this issue, if an Iframe is loaded within nwjs over https, anything within the Iframe that is non-ssl will not be loaded, I did not realise until I tried changing my application to work around this bug, seems I can't use a work around either.

**Comment by mscreenie** [comment]
We've dropped SSL altogether for the time being because we've migrated from 11.6 to 12. 

Another problem is loading Fonts from Google, no fonts will load or any resource infact from normal http if https is used.

**Comment by mscreenie** [comment]
@rogerwang could this be fixed in the next release? 12.1 ? thank you (appreciate your work, its allowed us to create a whole new venture)

**Comment by mscreenie** [comment]
@rogerwang would it be possible to get an approx eta for this fix? 

(appreciate your work - so far allowed us to create a whole new venture)

**Comment by rogerwang** [comment]
@mscreenie will see this this week. Thanks for your patience.

**Comment by mscreenie** [comment]
Look forward to it, thanks for committing to an ETA @rogerwang  *hug*

**Comment by rogerwang** [comment]
Please find the binaries in http://dl.nwjs.io/live-build/04-14-2015/a77b085-0aa4273-be948af-459755a-2bdc251-1764a45/

**Comment by mscreenie** [comment]
Successfully loaded non SSL resources over a SSL iframe and now works as expected with flag / arg. 

![image](https://cloud.githubusercontent.com/assets/11147410/7140965/7250143a-e2c6-11e4-88c8-f142e550b89b.png)

We're extremely grateful for your work and efforts, may only good come to you. Thanks!

**Comment by r1si** [comment]
Hi, don't work for me... console says: Failed to load resource: net::ERR_INSECURE_RESPONSE

in my package there is: 

<code>
{
  "main": "index.html",
  "name": "nw_test",
  "description": "Optimize application",
  "version": "1.0.0",
  "keywords": [ "nw", "node-webkit" ],
  "window": {
    "toolbar": false,
    "icon": "drk_browser.png",
    "position": "center",
    "min_width": 800,
    "min_height": 500,
    "as_desktop": true,
    "resizable": true,
    "frame": true,
	"chromium-args": "--allow-running-insecure-content"
  },
  "webkit": {
    "plugin": true,
    "page-cache": true
  }
}
</code>

**Comment by mscreenie** [comment]
I'll run a test to see if I can reproduce. 

Make sure you've downloaded the binaries @rogerwang has provided. Also post your app code.

**Comment by r1si** [comment]
here my app code:<br>
<b>index.html<b>
```html
<!doctype html>
<html style="height: 100%;overflow: hidden;">
<head>
    <meta charset="UTF-8">
    <title>DkR Browser v. 1.0.0</title>
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="css/materializecss_dkr.css"  media="screen,projection"/>
</head>
<body style="margin: 0;height: 100%;overflow: hidden;">
<div class="navbar-fixed navbar-desktop" style=" -webkit-app-region: drag; ">
    <nav style="background-color: #252525;">
        <div class="nav-wrapper row">
            <div class="col s12 m12" style="padding-right: 0;">
                <a href="#" class="navbar-desktop-title">DkR Browser v. 1.0.0</a>
                <ul class="right">
                    <!--@TODO fare la ricerca nelle opzioni se diventano molte-->
                    <li class="navbar-desktop-button"><a href="#" onclick="win_immersive();"><i class="mdi-navigation-fullscreen"></i></a></li>
                    <li class="navbar-desktop-button"><a href="#" onclick="win_minimize();"><i class="mdi-content-remove"></i></a></li>
                    <li class="navbar-desktop-button"><a href="#" onclick="win_maximize();"><i class="mdi-action-flip-to-front"></i></a></li>
                    <li class="navbar-desktop-button"><a href="#" onclick="win_close();"><i class="mdi-navigation-close"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<!-- self signed ssl -->
<iframe id="page_cnt" src="https://example.com" style="width:100%;height:-webkit-calc(100% - 29px);border:0;padding:0" nwUserAgent="DKRBRO" nwfaketop></iframe>
<!--nwfaketop nwUserAgent="DKRBRO"-->
<!--<iframe src="http://www.laboncloud.it/test.html" style="width:100%;height:100%;border:0;padding:0" nwfaketop></iframe>-->
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/materialize.js"></script>
<script type="application/javascript" src="js/laod_cfg.js"></script>
<script>
    /*
    * INIZIO MAIN
    */
    // Carico la libreria d'interfaccia
    var gui = require('nw.gui'); //or global.window.nwDispatcher.requireNwGui() (see https://github.com/rogerwang/node-webkit/issues/707)
    var win = gui.Window.get();

    // Dichiaro le altre finestre aperte
    var win_option, win_info;

    win.maximize();

    // Eseguo la funzione di override delle opzioni

</script>
</body>
</html>
```

**Comment by mscreenie** [comment]
What are you loading inside the SSL Iframe?

Try loading a non-ssl image , js or css hosted on a cdn or your own server. See if it loads. When I tested a few weeks ago it worked.

**Comment by r1si** [comment]
Thanks for tip @mscreenie 
If I try to load a valid ssl (green in chrome) page it works. 
But I need to allow a self signed SSL certificate (red in chrome). 
I put --ignore-certificate-errors in chrome args but still dont work... :(  
here new manifest chrome args 
"chromium-args": "--allow-running-insecure-content --ignore-certificate-errors"

**Comment by mscreenie** [comment]
Try 

--remember-cert-error-decisions 
--ignore-certificate-errors 
--ignore-urlfetcher-cert-requests 

I've tested the second with a self signed ssl served over LAN, generated for ligttpd. Worked like a dream. There are variations in self signed certs too and Chromium may be a little sensitive. Just ensure your self signed cert isnt giving you any other errors in your browser.

**Comment by r1si** [comment]
I try with that params but still don't work :(
mmmm....
let's do it like this...
could you try to compile with this url inside iframe? https://www.pcwebshop.co.uk/
If your code work can you post here manifest and appcode?
with this method I can debug my code...
Thanks you a lot @mscreenie

**Comment by mscreenie** [comment]
Sure, I'll do this when I return to my office. But here is what my self signed cert looks like in Chrome. What error message do you get when you try to load that URL in nwjs? Does it load at all?

![image](https://cloud.githubusercontent.com/assets/11147410/7343268/329d754e-ecb7-11e4-8be3-6d08190c77b4.png)

**Comment by r1si** [comment]
nwjs show this error: 
Failed to load resource: net::ERR_INSECURE_RESPONSE
and I did show nothing, only white screen.
Thanks for your try !

**Comment by mscreenie** [comment]
Just tried and works. Have you downloaded the latest binaries?

![image](https://cloud.githubusercontent.com/assets/11147410/7344935/5053663c-ecc8-11e4-8656-36cefbb4d776.png)

**Comment by r1si** [comment]
Mmm I supposed there is a problem with my code, because the binaries is the latest...
(I am using mac osx.... You use windows???) 
Can you give me your test app code?  So I can test your same code on mac and on windows ...
if you don't want post here,  I give you my mail address elia.baragiola@gmail.com.
Thanks a lot!!

**Comment by mscreenie** [comment]
I'm using Win 8.1 32 bit , Download this binary and try it http://dl.nwjs.io/live-build/04-14-2015/a77b085-0aa4273-be948af-459755a-2bdc251-1764a45/nwjs-v0.12.1-win-ia32.zip

**Comment by r1si** [comment]
I have tried but still dont work :( 
![capture](https://cloud.githubusercontent.com/assets/6353773/7348480/539b99ac-ecf2-11e4-94f5-588ddf7bb822.PNG)
I have created a simple test app that reproduce the problem...
here the binaries. 
only two file: package.json
```javascript
{
  "main": "index.html",
  "name": "https test",
  "description": "bla bla",
  "version": "1.0.0",
  "keywords": [ "DkR", "node-webkit" ],
  "window": {
    "toolbar": false,
    "icon": "",
    "position": "center",
    "min_width": 800,
    "min_height": 500,
    "as_desktop": true,
    "resizable": true,
    "frame": true,
	"chromium-args": "--remember-cert-error-decisions --ignore-certificate-errors --ignore-urlfetcher-cert-requests"
  },
  "webkit": {
    "plugin": true,
    "page-cache": true
  }
}
```
and index.html
```html
<!doctype html>
<html style="height: 100%;overflow: hidden;">
<head>
    <meta charset="UTF-8">
    <title>https test</title>
</head>
<body style="margin: 0;height: 100%;overflow: hidden;">
<iframe id="page_cnt" src="https://www.pcwebshop.co.uk/" style="width:100%;height:-webkit-calc(100% - 29px);border:0;padding:0" nwUserAgent="DKRBRO" nwfaketop></iframe>
<script>
    var gui = require('nw.gui'); //or global.window.nwDispatcher.requireNwGui() (see https://github.com/rogerwang/node-webkit/issues/707)
    var win = gui.Window.get();
    win.maximize();
    win.showDevTools();
</script>
</body>
</html>
```
and the result is this on macosx (on your binaries)
![macos result](https://cloud.githubusercontent.com/assets/6353773/7348834/09325ef2-ecf5-11e4-9d00-df5a2f56656a.png)

and this on windows x64
![nw](https://cloud.githubusercontent.com/assets/6353773/7348840/147e62ba-ecf5-11e4-823b-0e77d63afefb.png)

hope it helps to debug this :( 
thanks a lot

**Comment by r1si** [comment]
Hi @mscreenie any news about code?

**Comment by shaynem** [comment]
try this

process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

**Comment by jamesabbottsmith** [comment]
The binaries provided by rogerwang are now no longer available
(http://dl.nwjs.io/live-build/04-14-2015/a77b085-0aa4273-be948af-459755a-2bdc251-1764a45/)

Whats the current state of this? Is this fix included in any of the recent branches?

I've just tried the latest dev branch downloads and it didn't seem to work. 

Many thanks :)

**Comment by mscreenie** [comment]
It seems to be working for me in 12.3 build. I'm developing on this build, just tried embedding a non-ssl image and it works OK. http://dreamatico.com/data_images/cat/cat-6.jpg

**Comment by clyang82** [comment]
@r1si I met the same problem with you. I spent half a day to find out the reason. Now, it works well in my environment. Share to you:
Just add this line in package.json. 
{
...
"chromium-args": "--ignore-certificate-errors"
"window": ....
...
}
Please note: "chromium-args" is not a sub element of "window". it is same level as "window".

**Comment by nwcclink0** [comment]
@r1si 

Thanks for effort, I tried it at 0.12.3-win-x64 and it works.
Now I can use it on my self signed SSL certificate.  :)

**Comment by nwcclink0** [comment]
@clyang82 

Thanks for the effort, It works on 0.12.3-win-x64.
Now I can use it on my self signed SSL certificate. :)

**Comment by hxzqlh** [comment]
Basically you need to use:
```
"chromium-args": "--allow-running-insecure-content --ignore-certificate-errors",
```
The import thing is that:it has to go outside of the window object (e.g. after name property) in the package.json file.
