### ISSUE TITLE
Possible to make DOM elements behave like windows?

### ISSUE THREAD

**Issue by imjoshdean** [nwjs/nw.js#3125]
I have an experimental app that I am writing where in I make the app window the size of the entire screen as well as 100% transparent with click through enabled. I then create a bunch of elements that behave like windows (e.g. z-indexing, resizing, dragging, etc). All of this is done in order for each of the windows to behave and operate off of the same set of observable objects. For the most part it works pretty alright.

The real hiccup comes when you move into, say, Mission Control in OSX or Win + Tab management in Windows when the application is shown for what it really is - one large windowed app.

I was curious - is it possible to change this behavior? That way each of my faux "Windows" shows up as it's own Window in this mode?
##

**Comment by akagomez** [comment]
+1

**Comment by jonwwilkes** [comment]
I'm not sure I understand the problem.  Why not just have your data in a node context, and share that node context among multiple Window objects?

**Comment by imjoshdean** [comment]
@jonwwilkes Can you provide a really simple example of what you're talking about?
