### ISSUE TITLE
Troubles with Web Audio and ffmpeg.so on Mac

### ISSUE THREAD

**Issue by JaredCubilla** [nwjs/nw.js#3127]
I am attempting to develop an application with the ability to play MP3s, and was following [this page](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-%28H.264%29-using-the--video--&--audio--tags.) for guidance on allowing this to happen. I followed everything in the tutorial exactly how it said (except I did nw.js instead of node-webkit), but now when I try to test the app, it quits seconds after opening. However, when using the nw.js app as a browser it functions normally. I suspect it has to do with the Web Audio and playing mp3s itself.

I use a Mac (10.10, Yosemite), Google Chrome 40, and using nw.js 0.12.0-alpha3.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
