### ISSUE TITLE
Unlocalized File Dialogs

### ISSUE THREAD

**Issue by goldenbs** [nwjs/nw.js#3128]
![chinesedialog](https://cloud.githubusercontent.com/assets/11178938/6353360/e55dfee6-bc16-11e4-9d57-b732f7940d83.png)
Hello:

I've experienced this problem with NW V 11.3, 11.1 and 10.5.  It has occurred on Simplified and Traditional, Chinese, FIGS, Korean, Russian systems and more. It occurs on Windows.

When using the file open dialog, most of the open dialog is translated to the language of the operating system.  However, the item circled in the attached PNG, remains in English.  I am using an input with an "accept" attribute to filter the input files:

input id="load-custom-colorbar" type="file"  accept=".eps,.pdf" class="group1-2" name="files"

Any suggestions about how I can get the entire dialog localized properly?

Thank you
##

**Comment by Christywl** [comment]
I try `.png`/`.pdf`/`.eps` on nwjs-sdk-v0.24.0. The dialog remains in English. 
`<input id="load-custom-colorbar" type="file" accept=".png" class="group1-2" name="files">`
`<input id="load-custom-colorbar" type="file" accept=".pdf" class="group1-2" name="files">`
`<input id="load-custom-colorbar" type="file" accept=".eps" class="group1-2" name="files">`
If more file extensions are listed in `accept`, the dialog will change according to the language.
`<input id="load-custom-colorbar" type="file" accept=".png,.pdf" class="group1-2" name="files">`
`<input id="load-custom-colorbar" type="file" accept=".eps,.pdf" class="group1-2" name="files">`

And Chrome gets the same results.

**Comment by Christywl** [comment]
close until there is more information.
