### ISSUE TITLE
Open up chrome.devtools to expose extension API

### ISSUE THREAD

**Issue by kolodny** [nwjs/nw.js#3129]
I know that the because of the new version of the Chromium, extensions can't be used, but is it possible to expose the chrome.devtools or any other API ( https://developer.chrome.com/extensions/samples#search: ) to use directly inside of the regular javascript content, (similar to how the node environment is exposed) ?

**Comment by kolodny** [comment]
nevermind, I just realized that was what the other issue were about

**Comment by felicienfrancois** [comment]
which issue are you talking about ? can you link it please

**Comment by kolodny** [comment]
http://stackoverflow.com/questions/17116509/is-it-possible-to-load-chrome-extension-in-node-webkit-window
https://github.com/nwjs/nw.js/issues/792
https://github.com/nwjs/nw.js/issues/518
https://github.com/nwjs/nw.js/issues/749
