### ISSUE TITLE
Supporting more keys in global Shortcut API

### ISSUE THREAD

**Issue by rchanou** [nwjs/nw.js#3131]
The Shortcut API is almost great, but is there a reason the following keys can't currently be captured?

Caps Lock, Scroll Lock, Num Lock, Print Screen, Pause/Break, Tab, Enter, Backspace, Space, most punctuation

**Comment by gihrig** [comment]
+1

See #3039

**Comment by rchanou** [comment]
Looks like most, if not all of this, has been taken care of, or is being worked on. In either case, other similar, more active issues already exist.
