### ISSUE TITLE
elastic scroll for mac is enabled by default in nwjs v0.12 alpha3

### ISSUE THREAD

**Issue by memyselfandyasir** [nwjs/nw.js#3132]
elastic scroll in mac is enabled by default in nwjs v0.12 alpha3(which was disabled till alpha2) which is causing a web view like effect:

![image](https://cloud.githubusercontent.com/assets/4433993/6367281/dbef8780-bcf2-11e4-94ae-e432f5a31ac5.png)

**Comment by tommoor** [comment]
:+1:

**Comment by zhangmhao** [comment]
Is there any way that I can disable elastic scroll ?

**Comment by memyselfandyasir** [comment]
use alpha2 or 11.6 for now.. because I tried javascript to stop it, but it didn't workout..

**Comment by loveencounterflow** [comment]
what i REALLY want to have is bouncy rubberband elastic whatchamaycallit scrolling but *only* for content elements, not the chrome that i implement on the same webpage in JS. is that conceivable? 

The alternative would be to disable elastic scrolling (how?) and then re-implement it in JS. So far i've found that the JS tools are better usable than the "browser-side" / app-side ones (so i used JS for Keyboard shortcuts and will use CSS transforms to implement proper zooming), but i couldn't find a decent JS lib to give me proper bouncy scrolling so far. 

BTW nw is just great, i love it; if you're interested in a pre-alpha nascent nwjs app, have a look at https://github.com/loveencounterflow/mingkwai-app/releases/tag/tr5 (only OSX for now).

**Comment by memyselfandyasir** [comment]
@zhangmhao adding  'overflow: hidden;' to html/body style will resolve the problem in nwjs 12.0 final

**Comment by zhangmhao** [comment]
It works! Thank you @memyselfandyasir

**Comment by talldude** [comment]
Is it possible to disable elastic scrolling another way?  Setting overflow:hidden on the html/body element disables scroll events in jQuery (i.e. scrollTop), which we need in our app.

**Comment by achekulaev** [comment]
This solution is not good. If content is longer then the window then it will not scroll.
You need this
```
html,
body {
  height: 100%;
  width: 100%;
  overflow: auto;
}
html { overflow: hidden }
```
