### ISSUE TITLE
is it possible to download pdf using nwjs

### ISSUE THREAD

**Issue by HedCET** [nwjs/nw.js#3133]
currently i am using phantomjs to download `content-disposition: inline` pdf from google

`page.onUnsupportedContentReceived = function(_F) {
    page.saveUnsupportedContent(store + port + ".pdf", _F.id);
}`

is it possible with nwjs ?
##

**Comment by 1j01** [comment]
It's pretty easy to download files with with nw.js (or just node.js) with the [request](https://www.npmjs.com/package/request) module.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
