### ISSUE TITLE
Unable to run NW.JS in Ubuntu 12.10

### ISSUE THREAD

**Issue by Legrandk** [nwjs/nw.js#3134]
Hey guys,

Today I've installed a fresh Ubuntu 12.10 (32bits) in a machine of mine and downloaded the last version of NW.JS (node-webkit-v0.11.6-linux-ia32).

Unfortunately I was unable to run _nw_ due the following errros:

```
./nw: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./nw)
./nw: /usr/lib/i386-linux-gnu/libnss3.so: version `NSS_3.14.3' not found (required by ./nw)
```

I've checked the libraries versions my system has installed:

```
$ strings /usr/lib/i386-linux-gnu/libstdc++.so.6  | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

```
$ strings /usr/lib/i386-linux-gnu/libnss3.so| grep NSS_3
NSS_3.2
NSS_3.2.1
NSS_3.3
NSS_3.3.1
NSS_3.4
NSS_3.5
NSS_3.6
NSS_3.7
NSS_3.7.1
NSS_3.8
NSS_3.9
NSS_3.9.2
NSS_3.9.3
NSS_3.10
NSS_3.10.2
NSS_3.11
NSS_3.11.1
NSS_3.11.2
NSS_3.11.7
NSS_3.11.9
NSS_3.12
NSS_3.12.1
NSS_3.12.3
NSS_3.12.4
NSS_3.12.5
NSS_3.12.6
NSS_3.12.7
NSS_3.12.9
NSS_3.12.10
NSS_3.13
```

Do I have to recompile the NW.js in order to be able to use it on my system?
Do you have any suggestion to fix the problem and allow the 0.11.6 binaries be able to run?

Thanks in advance!
##

**Comment by micnic** [comment]
Ubuntu 12.10 is quite old (more than 2 years from release) and is not a LTS version, you have to ways to fix this: install the missing packages or upgrade to a LTS version (12.04, 14.04) or the latest version of Ubuntu (14.10)

**Comment by Legrandk** [comment]
@micnic 
Thanks for your suggestion! I'll try with 12.04.

**Comment by Legrandk** [comment]
@micnic 

I just tried with 12.04 LTS version but GLIBC doesn't match the required version:
```
./nw: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./nw)
```

I'm going to upgrade to 14.04 and try again. I'll keep you updated

**Comment by Legrandk** [comment]
I've tested with a fresh Ubuntu 14.04 version and now got this error:
```
./nw: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```
How to fix it is well documented in this post https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0

Creating a symlink to the current libudev.so.1 file does the trick:
```
$ cd /lib/i386-linux-gnu
$ sudo ln -sf libudev.so.1 libudev.so.0
$ ls -l libudev.so.*
lrwxrwxrwx 1 root root    12 Mar  3 10:02 libudev.so.0 -> libudev.so.1
lrwxrwxrwx 1 root root    16 Mar  3 09:43 libudev.so.1 -> libudev.so.1.3.5
-rw-r--r-- 1 root root 71044 Feb  4 10:01 libudev.so.1.3.5
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build in your environment?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by gwicksted** [comment]
For those googling: you can resolve the error:

`./nw: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
`

Which occurred with `nwjs v0.26.0` on a `Debian 8.9` VM w/ `LXDE`.

Run:

```bash

sudo apt-get update
sudo apt-get install libnss3-dev
```

and try again.

**Comment by LinuxCao** [comment]
because current gcc version is too low
fixed solution ：
#apt-get install gcc-5
