### ISSUE TITLE
Change name package.json to avoid conflicts with the npm one ?

### ISSUE THREAD

**Issue by remss** [nwjs/nw.js#3135]
A nodejs application has usually a package.json file that define some properties and dependencies.
To install nodejs dependencies i just need to call npm install in the application directory.
The problem is that nw.js use its own package.json file too.

A simple solution is to rename package.json to nw-app.json or something else ?

It will be nice to have an arg like --manifest to nw.exe to load a specific manifest file.

**Comment by 1j01** [comment]
This isn't usually a problem, and sometimes it's helpful, if you can get away with using the same file for both. Then you don't have to duplicate information and it works nicely. What exactly is the problem?

**Comment by felicienfrancois** [comment]
you can merge both files fields

**Comment by 1j01** [comment]
If there are conflicts, e.g. you want an uppercase name for the app but a lowercase dashed name for the npm package, you can separate the package files by moving the application into a subfolder. You may have to duplicate some information, which is not ideal, but it works.

**Comment by remss** [comment]
Ok cool it works with nodejs and nw fields in the same package.json file

The arg like --manifest to nw.exe can still be useful to load a debug version of the same app or having several nw applications in the same project.

Example : nw.exe . --manifest="package-debug.json"
