### ISSUE TITLE
Is it possible to open and have control of 3-rd party site

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [nwjs/nw.js#3141]
I am developing parsing tool for our clients and question is, can I run JS + Node modules on 3-rd party site?

For instance I would like to grab search field value from jquery.com site.

http://stackoverflow.com/questions/28765941/can-i-get-access-using-node-webkit-from-third-party-site?stw=2

**Comment by rogerwang** [comment]
yes. see `node-remote`: https://github.com/nwjs/nw.js/wiki/Manifest-format

and Window.eval(), `inject-js-start`: https://github.com/nwjs/nw.js/wiki/Window

and please ask questions with our mailing list for stackoverflow.
