### ISSUE TITLE
Remote debugging/devtools page blank in v0.12

### ISSUE THREAD

**Issue by polpo** [nwjs/nw.js#3143]
Starting nw with the `--remote-debugging-port` option does not work. nw listens on the port but does not return any data.

Starting nw: `nwjs-v0.12.0-rc1-linux-x64/nw --remote-debugging-port=9090`

Testing connection on this port:
```
$ telnet localhost 9090
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 200 OK
Content-Length:0
Content-Type:text/html; charset=UTF-8

```

I tested all v0.12.0 alphas and the rc1 release and all have the same issue on Linux x64. This issue is not present in v0.11.6.

**Comment by wuyuehang** [comment]
Invoke telnet can't access the remote debugging server unde my test.
But try "curl -I http://localhost:9090" can obtain right output with same test environment.

**Comment by polpo** [comment]
I get the same `Content-Length: 0` result with `curl -I` as the manual telnet method on Linux x64 and Windows with x64 and ia32 builds of nw.js v0.12.x

I could not get nw.js (or node-webkit v0.11, v0.10, v0.8) to listen on a remote debugging port at all on OS X with x64 or ia32 builds. That's probably a separate issue.

**Comment by polpo** [comment]
Looks like my problem on OS X was using "localhost" which curl resolves to `[::1]`, and `--remote-debugging-port` only listens on IPv4. Using 127.0.0.1 with curl results in the same behavior as on Linux and Windows (`Content-Length: 0`).

**Comment by polpo** [comment]
After some more investigation, while `http://localhost:9090/` does not work, it looks like `http://localhost:9090/json` works. If I go to the `devtoolsFrontendUrl` in that JSON document I get a working remote devtools. Clumsy but it is a workaround.

@ghostoy [in this comment](https://github.com/nwjs/nw.js/issues/2996#issuecomment-76318608) and @felicienfrancois [in this comment](https://github.com/nwjs/nw.js/issues/2976#issuecomment-70808045) you mention using the `--remote-debugging-port` option. Was the debugging url without `/json` suffix working for you in any v0.12 version?

**Comment by julienbu** [comment]
Hi,
I have met the same issue than plpo (blank localhost:9222 and response with localhost:9222/json) with w7 64bits.
I tried to manually open the URL of devtool in chrome and obtained a blank the tool without data into
![scchrome](https://cloud.githubusercontent.com/assets/8348537/6671778/fabb7100-cc07-11e4-8efb-ea4bd8da1a2c.png)
bottom left : webApp to debug
bottom right : original dev console
top right : remote devtool (with opened devtool frame inside)

 (Web Socket connection failed as you can see on the devtool of the devtool : inception inside J)

**Comment by jerone** [comment]
I confirm this issue on Windows 8.1 64-bits for v0.12.0, v0.12.0 RC1 and v0.11.6.
It does however work on Windows 8.1 64-bits on v0.8.6 and it does work on Windows 7 64-bits with v0.12.0.

I tried all situations with args `--remote-debugging-port=9222` on and off. Also, all situation does return a JSON list on `http://localhost:9222/json`.

**Comment by polpo** [comment]
As a workaround the following code snippet can be used in a bookmarklet to load the devtools when your browser is on the blank page. It can also load the devtools if you have stopped and restarted the host NW.js app, and it also works around another issue where the `devtoolsFrontendUrl` key can be missing from the response to `/json`.

```javascript
javascript:(function(){var xhr = new XMLHttpRequest(), go = function () { xhr.open('GET', '/json'); xhr.send(); }; xhr.onload = function () { var url = JSON.parse(xhr.responseText)[0].devtoolsFrontendUrl; if (url) { window.location = url; } else { xhr.abort(); go(); }}; go();})()
```

**Comment by maxbarry** [comment]
Exact same situation here as described by polpo, running 0.12.0 on Ubuntu 14.04.2 LTS x64.

Thanks very much for the workaround.

**Comment by adriancooney** [comment]
@polpo Thanks for the handy snippet! :+1:

**Comment by timkalinowski** [comment]
@polpo thanks for your solution, also experienced this on the 0.12.0 linux arm build.
