### ISSUE TITLE
Error compiling addon v0.11.6 of node-webkit

### ISSUE THREAD

**Issue by edwin1329** [nwjs/nw.js#3144]
I have a file in C ++ and I am compiling so: I run the command nw-gyp configure --target = 0.8.6 and then run nw-gyp build up here everything works fine, I run the project and does everything as it should be, the problem is when I try to compile for version 0.11.6, compiles fine but when I run the program I get the following error:

Error: dlopen(ruta/addon.node, 1): no suitable image found. did find: Ruta/addon.node: mach-o, but wrong architecture

Alguna idea de que pueda suceder

**Comment by mrfabbri** [comment]
@edwin1329 my guess is your version 0.8.6 is 32bit and 0.11.6 64bit instead. Check the architecture of the version 0.11.6 (it should be 64bit) if this is the case you should pass also the `--arch=x64` option to `nw-gyp configure`.
