### ISSUE TITLE
Building nw due to renaming nw.exe issue

### ISSUE THREAD

**Issue by mese79** [nwjs/nw.js#3145]
Hi
I have few questions about building nw from the source.
1- in [here](http://www.chromium.org/developers/how-tos/build-instructions-windows) it's mentioned that:

> You must build with Visual Studio 2013 Update 4, no other versions are supported.
> You must have Windows 7 x64 or later. x86 OSs are unsupported.

So is this true for latest nw too? if yes can i build only x86 version on Win7 x64?

2- Since i only want to have a Windows x86 built is this `.gclient` file ok?

```
solutions = [
   { "name"        : "src",
     "url"         : "https://github.com/rogerwang/chromium.src.git@origin/nw",
     "deps_file"   : ".DEPS.git",
     "managed"     : True,
     "custom_deps" : {
       "src/third_party/WebKit/LayoutTests": None,
       "src/chrome_frame/tools/test/reference_build/chrome": None,
       "src/chrome_frame/tools/test/reference_build/chrome_win": None,
       "src/chrome/tools/test/reference_build/chrome": None,
       "src/chrome/tools/test/reference_build/chrome_win": None,
     },
     "safesync_url": "",
   },
]
```

3- as [SingKo](https://github.com/SingKo) mentioned at [#199](https://github.com/nwjs/nw.js/issues/199) building steps:

> 1,You have got a copy of nw src,open nw.gypi.
> 2,modify " 'target_name':'nw' " to '' 'target_name':'xxx' ",about in line 621.
> 3,modify " 'dependencies':['nw',] " to '' 'dependencies':['xxx',] ",about in line 588.

I found other bunch of nwxxx stuff like ```'target_name': 'nw_lib'  or  'target_name': 'nw_resources'  or 'target_name': 'nw_pak'.
Should i rename those too? (line numbers doesn't match anymore)

Please help me!
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
