### ISSUE TITLE
Node-keychain unpredictably returns null and causes fatal error in nw.js only

### ISSUE THREAD

**Issue by cperryk** [nwjs/nw.js#3146]
The module [node-keychain](https://github.com/drudge/node-keychain), which allows node access to the Mac keychain, behaves unpredictably in nw.js. Consider this main.js script, where _userName_ is the user name for one of your keychain keys and _serviceName_ is one of the services:

```
var keychain = require('keychain');
function getPass(){
    keychain.getPassword({account:'userName', service:'serviceName'}, function(err, pass){
        console.log(err, pass);
    });
}
setInterval(getPass, 50);
```

Simply run this in node, and it always retrieves the password successfully at every interval. Run this in node-webkit, however, and it will sometimes log {} as the err and null as the password. It will also eventually cause this fatal nw.js error:

```
TypeError: Cannot read property '1' of null
    at ChildProcess.eval (/Users/kirkcp/Documents/node_play/slatemail/node_modules/keychain/keychain.js:73:47)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
```

Keychain.js line 73 is:

```
password = password.match(/"(.*)\"/, '')[1];
```

A spawned child-process running <code>/usr/bin/security</code> sets _password_ initially before this match regex happens. For some reason, that sometimes results in a password of " ", which is why the match doesn't work. This happens ONLY in nw.js. ([see keychain.js script](https://github.com/drudge/node-keychain/blob/master/keychain.js)).

Using node-webkit 0.8.6
##

**Comment by xueeinstein** [comment]
cannot reproduce it on nwjs-12.

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.24.0.

**Comment by Christywl** [comment]
close until there is more information.
