### ISSUE TITLE
Remove Badge Labels

### ISSUE THREAD

**Issue by windht** [nwjs/nw.js#3147]
Is there anyway to remove the badges after using the window.setBadgeLabel?
I looked up the source code and found out it set any string or numbers pass in.
So will there be a way to delete the badges? For example pass in a specific param?

**Comment by rdtsc** [comment]
Passing an empty string to `Window.setBadgeLabel` should get rid of the badge:

```javascript
(function() {
  var win = require('nw.gui').Window.get();

  win.setBadgeLabel(Math.floor(Math.random() * 10));

  setTimeout(function() {
    win.setBadgeLabel('');
  }, 3000);
})();
```

## Reference

**[NativeWindowAura::SetBadgeLabel](https://github.com/nwjs/nw.js/blob/master/src/browser/native_window_aura.cc#L691-697)**

```cpp
HICON icon = NULL;
HWND hWnd = views::HWNDForWidget(window_);

if (badge.size())
  icon = createBadgeIcon(hWnd, base::UTF8ToUTF16(badge).c_str(), 32, 32);

taskbar->SetOverlayIcon(hWnd, icon, L"Status");
DestroyIcon(icon);
```

<p align="center">:small_red_triangle_down: :small_red_triangle_down: :small_red_triangle_down:</p>

**[ITaskbarList3::SetOverlayIcon](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391696#content)**

> *hIcon* [in] Type: **HICON**
>
> This value can be **NULL**. How a **NULL** value is handled depends on whether the taskbar button represents a single window or a group of windows.
> - If the taskbar button represents a single window, the overlay icon is removed from the display.
> - If the taskbar button represents a group of windows and a previous overlay is still available (received earlier than the current overlay, but not yet freed by a **NULL** value), then that previous overlay is displayed in place of the current overlay.

**Comment by windht** [comment]
@rdtsc Thanks so much! This worked so well!
