### ISSUE TITLE
WebGL Issue

### ISSUE THREAD

**Issue by mese79** [nwjs/nw.js#3150]
Hi
I have a pc with `WinXP SP3` and `Google.Chrome.v40.0.2214.115`  and `intel G33/G31` vga which shows webgl contents well!
But either `node-webkit 0.11.6` or `nwjs 0.12.0-rc1` doesn't work with webgl context on this pc(i tried get.webgl.org too). I'v tried `--ignore-gpu-blacklist` switch and copying `d3dx9_43.dll` and `d3dcompiler_43.dll` into nw.exe folder with no success :( .
So why is this happening? isn't nw and chrome engine are the same? I've read an issue about _nw doesn't honor the `ignore-gpu-blacklist`_. if this is true, is there any workaround or i should recompile nw from the source?
Thanks in advance!
##

**Comment by Baccanno** [comment]
Probably related to #1060

**Comment by Christywl** [comment]
I try https://get.webgl.org on nwjs-sdk-v0.24.0. It works fine.

**Comment by Christywl** [comment]
close until there is more information.
