### ISSUE TITLE
nwsnapshot fails almost every time

### ISSUE THREAD

**Issue by transaction** [nwjs/nw.js#3151]
nwsnapshot fails 95% of the time. It seems the failure % increases when the input file grows longer. It's not a silent fail like #1295 since there's no crash on startup, it just seems the JS code gets compiled wrong.

This is on an old version (0.10.5), have there been any changes in nwsnapshot since that release?

Examples of output when the app is started, all different times with the same source file:

`function encodeURI() { [native code] } is not a constructor`

```
TypeError: undefined is not a function
    at Window.__defineGetter__ (native)
    at Function.Window.init (window_bindings.js:173:18)
    at Function.startup.initNw (node.js:803:19)
    at startup (node.js:76:15)
    at node.js:885:3
```

```
"<unknown message uncaught_exception>", source: module.js (338)
"<unknown message uncaught_exception>", source: module.js (338)
```

```
node.js:33
    process.__proto__ = Object.create(EventEmitter.prototype, {
                               ^
RangeError: Maximum call stack size exceeded
    at Int16Array (native)
    at new TypeError (native)
    at Int16Array (native)
    at new TypeError (native)
    at Int16Array (native)
    at new TypeError (native)
    at Int16Array (native)
    at new TypeError (native)
    at Int16Array (native)
    at new TypeError (native)
```

```
node.js:319
                   .replace(/"/g, '\\"')
                    ^
illegal access
```

**Comment by transaction** [comment]
When the .bin compiles successfully, there also seems to be differences in how functions are executed.

2 async calls to $scope.$apply (angular) execute without issues in plain JS but NW crashes when this is done from a compiled function.

**Comment by liyingzh** [comment]
take a look https://github.com/nwjs/nw.js/issues/3091#issuecomment-76338153

**Comment by transaction** [comment]
Thanks @liyingzh, totally missed that one. Using an RC for production isn't ideal but it beats uncompiled code. I'll keep this issue updated.

**Comment by transaction** [comment]
Works flawless with 0.12.0-rc1, awesome!
