### ISSUE TITLE
process.send function is undefined

### ISSUE THREAD

**Issue by 5paceManSpiff** [nwjs/nw.js#3157]
Hello!  I'm trying to communicate with a node webkit subprocess from a regular node script by using the `ipc` stdio flag in `child_process.spawn`.  `process.send` seems to appear in other similar frameworks like atom-shell, though node-webkit doesn't seem to support this.  Is this a bug, or am I just missing something?

I should probably note I'm launching the app from the following bash script.

``` bash
#!/usr/bin/env bash
cd `dirname $0`
nw
```
##

**Comment by 5paceManSpiff** [comment]
This seems to be related to #2245 and #213.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
