### ISSUE TITLE
Is it possible to create custom OS native right-click context menus?

### ISSUE THREAD

**Issue by jonathanhardie** [nwjs/nw.js#316]
If not, is it a planned feature?

**Comment by jmorrisIII** [comment]
@d-oliveros did you ever figure out if its possible to right click a file and open a context menu?

**Comment by d-oliveros** [comment]
Hey @jmorrisIII, I honestly don't remember what I ended up doing. I think I wasn't able to create the contextual menu, at least not with nw alone.

**Comment by masterpat** [comment]
@jmorrisIII The entries in the context menu for explorer or desktop are set in the registry. You can install the "windows" npm package (https://www.npmjs.com/package/windows) and add them in your app. Here is an article about what to edit for different file types etc.: http://www.howtogeek.com/howto/windows-vista/add-any-application-to-the-desktop-right-click-menu-in-vista/

**Comment by jmorrisIII** [comment]
@masterpat thanks. I will look into it. It looks like it will work for me.
