### ISSUE TITLE
Segmentation fault when opening inspector

### ISSUE THREAD

**Issue by tommoor** [nwjs/nw.js#3160]
The output in the console looks like this:

```
[51986:0302/171941:ERROR:nw_shell.cc(334)] Unable to load URL: 
** Unknown exception behavior: 0
Segmentation fault: 11
```

**Comment by rogerwang** [comment]
which version are you using?

**Comment by tommoor** [comment]
Hey Roger, I'm actually on 0.11.6 as there are too many regressions on OSX on the 0.12 branch. I'll give it a try there though and get back.

**Comment by tommoor** [comment]
0.12.3 fixes this

**Comment by ghostoy** [comment]
@tommoor Do you have a test case to reproduce this issue on 0.11.6?
