### ISSUE TITLE
Mac OSX only) when window is hidden, window.on("close") not triggered on CMD + Q

### ISSUE THREAD

**Issue by aretias-kr** [nwjs/nw.js#3162]
```javascript
            mainWindow.on("close", function (event) {
                if (event == 'quit') {
                    myapp.windowHandler.quit();
                } else {
                    mainWindow.hide();
                }
            });
```
I'm using the code above to handling close event and cmd + q action.
normally this code works fine.
But after mainWindow hidden, close event is not triggered.

I know that I can avoid this issue to implement menu myself.
But I think it's wrong working.

**Comment by PierBover** [comment]
I'm using this to create a global shortcut and it works even when the main window is hidden.

```
var gui = require('nw.gui');

var quitKeys = {
    key: "Ctrl+Q"
};

var shortcutQuit = new gui.Shortcut(quitKeys);


gui.App.registerGlobalHotKey(shortcutQuit);


shortcutQuit.on('active', function() {
   // quit your app
});
```

**Comment by aretias-kr** [comment]
@PierBover  Thanks, It seems nice solution.
But on MAC OS X, It is little wired cause application usually has quit menu on top status bar.

**Comment by PierBover** [comment]
You can add menu items on the top bar too.

https://github.com/nwjs/nw.js/wiki/Menu

**Comment by banezaklan** [comment]
I'm having the same problem. When app is hidden/minimized, the osx app menu stays active. However the app cannot be quit when selecting menu->quit. Once the app is restored the menu->quit option works again. Other osx apps also leave the menu active when minimized, but it works just fine.
