### ISSUE TITLE
snapshot works like a charm now

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3164]
Hey @rogerwang,

After all the problems I've had with the old nwsnapshot tool, the new nwjc is amazing. I've successfully snapshotted a 200kb minified JS file and it works great.

Feel free to close this issue, as it's not really a problem here. Just wanted to let you know I immensely appreciate the effort to fix that! You're awesome! :) Thank you so much!

**Comment by rogerwang** [comment]
good to know it.

**Comment by bestplay** [comment]
+1

awesome!
