### ISSUE TITLE
Make the nw app a command tool (CLI)

### ISSUE THREAD

**Issue by remss** [nwjs/nw.js#3166]
Hello,
I'd like to make my nw app callable as a CLI.
But i have to issues with that:
- i cannot write to strout / stderr (nothing happens when process.stderr.write)
- i cannot exit the app with a status code (0 if success 1 or more if errors)
Any clue to tackle this  problem ?

ps: if you wonder why i want to do that, is simple: i have a working nw app that do lots of actions through the GUI, and i want to expose some of them in CLI mode to be part of a batch process.

**Comment by hdf** [comment]
+1

**Comment by mrfabbri** [comment]
Hi @remss (maybe be stating the obvious here…) what about having it the other way around a nwjs that leverages a node command-line tool / module?

PS: console.log/error work as usual.

**Comment by remss** [comment]
Your are right but not if the application is highly tied to the browser (ie. DOM). In my case, the application is a full ExtJS one, which is not compatible with nodejs.

Are the two feature requests hard to implement in nw ?

**Comment by mrfabbri** [comment]
For 1) did you tried `console.log()`/`console.error()` ? For 2) you can have a look at the entry point of the `App.quit()` API (in `api/app/app.cc`).

**Comment by remss** [comment]
On Ubuntu, running `nw .` from a terminal launches the app, the command keeps going with JS console messages printed to STDERR. So far so good.
But on Windows, running `nw.exe .` from cmd launches the app but the command return immediately. Nothing in the output for the command. Erf !
So the behaviour is different depending of the platform...

Thanks to point the app.css, i see there is no argument for status code in App.quit(). But my thing is JS dev, not C++ so no PR from me sorry.

But i think CLI mode is a feature that NW should consider to provide solution to test a nw-app or run tasks. Currently it seems the only way to do that is to use other HTML5 containers like PhantomJS or Atom-Shell :-(
