### ISSUE TITLE
NW crashing when calling Protractor's init function [$40]

### ISSUE THREAD

**Issue by zalow517** [nwjs/nw.js#3168]
I'm having an issue with Protractor 1.7.0 module. When calling its init function NW is crashing.

I am calling this init function specifically to specify my configuration file instead of having to build and set a new one everytime. 

Any pointers as to why NW is crashing? #2325 is similar to this issue but using selenium-webdriver and chromedriver directly instead. But it was somewhat solved with the latest 2.44 selenium-webdriver update.

This is the code that is making NW crash at the moment:

var protractor = require('protractor');
var x = require('./node_modules/protractor/lib/launcher');

x.init('./workspace/Project/config-local.js');

Would love to get some feedback on this one, many thanks!
##

**Comment by mediaslav** [comment]
try to catch crash error 
```
process.on('uncaughtException', function (e) {
    var fs = require('fs');
    var util = require('util');
    fs.writeFileSync('NW_CRASH.log', util.inspect(e, true, 99) + "\n");
    });
      
```

**Comment by zalow517** [comment]
Thx for your reply. This is the caught error:

Uncaught ReferenceError: XMLHttpRequest is not defined @ C:\Protractor\node_modules\protractor\node_modules\q\q.js:126
and @
C:\Protractor\node_modules\protractor\node_modules\source-map-support\source-map-support.js:60

This is the specific area where the error is occurring:

  if (isInBrowser()) {
    var xhr = new XMLHttpRequest(); <<<< ----- ERROR line ----- <<<<
    xhr.open('GET', source, false);
    xhr.send(null);
    fileData = xhr.readyState === 4 ? xhr.responseText : null;

    // Support providing a sourceMappingURL via the SourceMap header
    var sourceMapHeader = xhr.getResponseHeader("SourceMap") ||
                          xhr.getResponseHeader("X-SourceMap");
    if (sourceMapHeader) {
      return sourceMapHeader;
    }
  }

**Comment by mediaslav** [comment]
this code here is executed in node context, not in webkit context, that's why XMLHttpRequest is not defined

so I believe isInBrowser() detection needs fix

**Comment by mediaslav** [comment]
And, of course, someone already made a PR for that in relevant repo here
https://github.com/evanw/node-source-map-support/pull/44

**Comment by zalow517** [comment]
Added:
return ((typeof window !== 'undefined') && (typeof XMLHttpRequest === 'function'));
@ isInBrowser() within node-source-map-support.js

Now NW is just crashing with no other errors in console, except a warning:

[Q] Unhandled rejection reasons (should be empty): ReferenceError: jasmine is not defined @ ./node_modules/protractor/node_modules/q/q,js:989

Seems like it's a small bug in Q which shouldn't be an issue here?

**Comment by mediaslav** [comment]
the error is actually popping elsewhere before Q - 
where someone tried to use jasmine and got error thrown, which later was catched by Q, while Q was expecting promise

try searching for "jasmine" usage up in your call "stack" and see why its not defined, it's probly another context issue and there's ```window.jasmine``` defined or another "isInBrowser" fail, which needs fix

**Comment by zalow517** [comment]
The launcher is calling the runner, which in turn is calling the jasmine's run method:

    frameworkPath = './frameworks/jasmine.js';

    return require(frameworkPath).run(self, self.config_.specs).
        then(function(testResults) {
          return helper.joinTestLogs(pluginSetupResults, testResults);
        });

Then from within jasmine the only signal I can get is before these requires:

  console.log('Last input before crash');
  var minijn = require('minijasminenode');

  require('jasminewd');
  /* global jasmine */

So I would think this global jasmine thing is the issue... but don't really know how I can fix it.

Any ideas?

**Comment by zalow517** [comment]
UPDATE: How I fixed the 'jasmine not defined' error:

var isCommonJS = typeof window !== "undefined" && typeof exports == "object";
@ within jasmine-1.3.1.js

This way the window object doesn't have to be "undefined".

So, I managed to start web-driver but NW is now crashing when the test is finished.

Tried to catch different type of errors but nothing is being caught. Also tried listening for NW's window exit signal, to stop it from closing but window is still being closed, therefore I suspect this is just another crash.

On a side note, I can't seem to get the Crash Dump File to generate in my system temp file (i'm on Windows), so can't really debug from there :/

**Comment by mediaslav** [comment]
try that as well to catch err in webkit context
```
window.addEventListener('error', function (e) {
        var fs = require('fs');
        var util = require('util');
        fs.appendFileSync('CRASH_DUMP_WEBKIT.log', util.inspect(e, true, 99) + "\n");
});
```

**Comment by zalow517** [comment]
Thanks @mediaslav, tried that too but nothing.

I suspect the issue resides somewhere in jasmine, after onComplete and before onCleanup method is called, as the latter is not being called at all after the tests are finished running.

Most probably another context issue.

**Comment by zalow517** [comment]
This function is not returning anything, it's here that the last signal is sent to:

DriverProvider.prototype.teardownEnv = function() {
  return q.all(this.drivers_.map(this.quitDriver.bind(this)));
};

This method is called by Protractor's runner to tell the driverProvider to quit the driver. There's something NW doesn't like about this.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
