### ISSUE TITLE
node-webkit with angular html5Mode set as true

### ISSUE THREAD

**Issue by Yimiprod** [nwjs/nw.js#3170]
Hi
I create a desktop webapp with angular, wrapped in node-webkit.
I have set to html5mode at true for better url syntax. But when i reload the page, if it's not app://myapp/index.html, it fail.
I wanted to know if i can force node-webkit to prevent the reload, or at least load index.html and let angularjs handle the current url.
##

**Comment by HMUDesign** [comment]
While I have not tried this in NW, I can tell you how I solve this in in a normal browser.

Usually, I try to have actual content at the url, for search engines, etc. But on each of those pages, I have a javascript that redirects to index.html#!/url, and angular sees that (might need to change the # and ! syntax to make it work) and updates the history accordingly.

If you add this logic to a 404 error page, it also works, sending the user to the correct page (making sure your angular app has its own error page).

I am unsure, however, if you can overwrite the default error page in NW.

**Comment by Yimiprod** [comment]
There is no 404 logic in node-webkit (at first glance), it just show a blank page. That's why i have no idead how to deal with this problem. Same thing, if in angularjs i sat ```.otherwise({redirectTo: '/'});``` it work when app load but reloading the window and i can see my folders.

**Comment by Yimiprod** [comment]
So, i see i can create a node-main js file, i think it's a good way to handle url on first-load/reload, but i don't know how i can see the current path.
At first i've thinked of using inject-js-start, but this won't work because the injection only append when there is no 404.

**Comment by transaction** [comment]
Why do you want to use html5mode in nwjs? The usual way of these kinds of apps is that they don't show the url bar so there's no real advantage of html5mode.

I use angular and I've just set it to false. Links go to /#/login instead of /login etc.

**Comment by Yimiprod** [comment]
We need it in this app

**Comment by Yimiprod** [comment]
Well I'll remove it for for the moment, but the project owner will certainly going to need it later.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
