### ISSUE TITLE
Window.on('restore') bug on Windows

### ISSUE THREAD

**Issue by CamiloMM** [nwjs/nw.js#3171]
Windows 7+ has this button on the lower-right corner that minimizes all windows. If I press it, and then restore a NW.js window, the `Window.on('restore')` event will not be fired.
##

**Comment by Christywl** [comment]
It works fine on Windows 8.1 with nwjs-sdk-v0.24.0.
```
<script>
var win = nw.Window.get();
win.on('restore', function(event){alert("restore");});
</script>
```

**Comment by Christywl** [comment]
close until there is more information.
