### ISSUE TITLE
Warnings Should be Raised for Invalid Apps?

### ISSUE THREAD

**Issue by skibulk** [nwjs/nw.js#3174]
I just created my first app. Not knowing that spaces are disallowed in the Manifest's "Name" field, I attempted to use them. Upon dragging myApp.nw onto nw.exe, nothing happens. It would be useful to display some kind of warning when the manifest file is not valid, with appropriate instructions.
##

**Comment by skibulk** [comment]
Actually it's something else, but I'm still not getting any feedback from nw.exe. It's really difficult to debug something this way.

Here's my package.json:
{
  "name": "helloworld",
  "version": "0.1.0",
  "description": "",
  "main": "index.html",
  "window": {
    "show": false,
    "toolbar": false,
    "frame": false,
    "position": "center",
    "width": 360,
    "height": 300,
    "min_width": 220,
    "min_height": 220
  }
}

And here's my index.html:
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>Hello World</title>
		<style>
			* {
				box-sizing: border-box;
				margin: 0;
				padding: 0;
			}
			html, body {
				width: 100%
				height: 100%;
			}
			p, h1, h2, h3, h4, h5, h5 {
				padding: 10px;
			}
		</style>
	</head>
	<body>
		<h1>Hello World</h1>
	</body>
</html>

**Comment by skibulk** [comment]
For the above code, I zipped and renamed to helloworld.nw, using the same file name as the manifest name field. In this case, nw.exe fails to run.

I just zipped the same app and renamed to hello.nw and at least this time nw.exe opened. It says unable to parse package.json: Line 3, Column 2 trailing comma not allowed.

Yet when I paste my package.json file into JSLint, I have valid JSON syntax.

**Comment by skibulk** [comment]
I can't figure out what's happening behind the scenes, but therew's something about the name "helloworld" that fails every time. It seems that using different app names it seems to work.

**Comment by Christywl** [comment]
It works fine on nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
