### ISSUE TITLE
Native node.js module node-cuda can't be build

### ISSUE THREAD

**Issue by pavel-kudinov** [nwjs/nw.js#3176]
https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

>NOTE: The V8 version in node-webkit is different with the version in Node.js. And because V8 doesn't have any stable ABI, your native module could be broken. But we are trying our best to support native modules, deprecated API is supported to maintain backward compatibility. And if you find your module can't be built, file an issue.

Okay:

module "node-cuda" can't be build on Win64, but built successfully for node.js on the same platform. 

https://github.com/kashif/node-cuda

build commands:

cmd /C "nw-gyp configure --arch=x64 --target_arch=x64 --target=0.11.6 --msvs_version=2013"
cmd /C "nw-gyp build"

next, I have errors like this:

c:\users\pavel_kudinov\yandexdisk\void\lib\node-cuda\src\bindings.hpp(12): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\mem.cpp) [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
c:\users\pavel_kudinov\yandexdisk\void\lib\node-cuda\src\bindings.hpp(12): error C2143: syntax error : missing ',' before '&' (..\src\mem.cpp) [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
c:\users\pavel_kudinov\yandexdisk\void\lib\node-cuda\src\bindings.hpp(13): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\mem.cpp) [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
c:\users\pavel_kudinov\yandexdisk\void\lib\node-cuda\src\bindings.hpp(13): error C2143: syntax error : missing ',' before '&' (..\src\mem.cpp) [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]

...

..\src\ctx.cpp(70): error C2660: 'v8::Number::New' : function does not take 1 arguments [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
..\src\ctx.cpp(73): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
..\src\ctx.cpp(73): error C2143: syntax error : missing ',' before '&' [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
..\src\ctx.cpp(74): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
          C:\Users\pavel_kudinov\.nw-gyp\0.11.6\deps\v8\include\v8.h(816) : see declaration of 'v8::HandleScope::HandleScope'
          C:\Users\pavel_kudinov\.nw-gyp\0.11.6\deps\v8\include\v8.h(800) : see declaration of 'v8::HandleScope'
..\src\ctx.cpp(75): error C2653: 'ObjectWrap' : is not a class or namespace name [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
..\src\ctx.cpp(75): error C2065: 'Unwrap' : undeclared identifier [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
..\src\ctx.cpp(75): error C2275: 'NodeCuda::Ctx' : illegal use of this type as an expression [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]
..\src\ctx.cpp(75): error C2065: 'args' : undeclared identifier [C:\Users\pavel_kudinov\YandexDisk\VOID\lib\node-cuda\build\cuda.vcxproj]

**Comment by xueeinstein** [comment]
@pavel-kudinov , every time your add tag `--target` , `nw-gyp` would download corresponding nwjs-header files. I have met the same problem when using nwjs v0.11.6 header files. I recommend you to update version 0.12.0, and use v0.12.0 header files. And try to build again.

**Comment by xueeinstein** [comment]
The mistake should be this issue #2994 !
