### ISSUE TITLE
e.target.pathname prefixes pathnames with "/C:" on Windows

### ISSUE THREAD

**Issue by kethinov** [nwjs/nw.js#3177]
Suppose you have the following HTML:

``` html
<a id='somewhere' href='/somewhere'>somewhere</a>
```

Then you attach a click event to it:

``` js
document.getElementById('somewhere').addEventListener('click', function(e) {
  alert(e.target.pathname);
}, false);
```

Actual results:
- Linux and OS X return "/somewhere"
- Windows returns "/C:/somewhere"

Expected:
- All operating systems should return "/somewhere"

This bug breaks libraries like [page.js](https://github.com/visionmedia/page.js).
##

**Comment by Christywl** [comment]
`/somewhere` returns on Windows with nwjs-sdk-v0.24.0.

**Comment by Christywl** [comment]
close until there is more information.
