### ISSUE TITLE
Window position does not work in OSX 10.9

### ISSUE THREAD

**Issue by PierBover** [nwjs/nw.js#3178]
Using "center" does nothing, and "mouse" seems to center the window...
##

**Comment by bakman2** [comment]
Same here (10.10.5)

**Comment by PierBover** [comment]
What I did was simply to position the window using `x` and `y`.

**Comment by Christywl** [comment]
`position:"mouse"` in `package.json` works fine on nwjs-sdk-v0.24.0.
For `win.setPosition()`, it doesn't work . Please see http://docs.nwjs.io/en/latest/References/Window/#winsetpositionposition

**Comment by Christywl** [comment]
close until there is more information.
