### ISSUE TITLE
Weird behavior for non-resizable application | Windows 7 64bit - node-webkit 0.11.3 64bit - nwjs 0.12.0 64bit

### ISSUE THREAD

**Issue by cyrusthegreatking** [nwjs/nw.js#3180]
# Problem:
## node-webkit 0.11.3 64bit:

When set false for **resizable in package.json**, clicking on app task-button in taskbar didn't minimize/restore app window. And when remove resizable: false from package.json and set window resizable with **win.setResizable(false)**, clicking on app task-button in taskbar works very well and prev problem disappear and it will minimize or restore app window, but a new problem will be happen. We know that double-clicking on element with css "-webkit-app-region: drag;" property will maximize window, and drag-n-drop window to the top or top-left/top-right corner of screen will maximize or make window to fit half of screen. So now with setting resizable by win.setResizable(false), these things will happen for apps and will be maximized.
# nwjs 0.12.0 64bit

Using both approaches will make strange behavior as node-webkit 0.11.3 64bit when using win.setResizable(false). No difference.
# More info

I think node-webkit use different approaches for these two ways of making window non-resizable and both of them have some serious problem. And in nwjs 0.12.0 their functionality are same but with maximizing problem.
# Suggested Solution

1-  Set resizable:false in package.json, and make an event for clicking on app task-button in taskbar, then trigger the window minimize/restore according to current window state. And after all, make setResizable functionality same as setting resizable in package.json.

2- Fix  issue of current clicking on task-button in taskbar and make setResizable functionality same as setting resizable in package.json.

_I will be happy to hear about some solution for this problem._
##

**Comment by cyrusthegreatking** [comment]
# Tricky solution
Well, after some testing in nwjs 0.12.0 64bit, i found a tricky solution for this problem.
package.json:
```javascript
"window": {
        "title": "Test",
        "toolbar": false,
        "frame": false,
        "width": 1000,
        "height": 600,
        "position": "center",
	"resizable": false
}
```
index.html (just a style tag):
```html
<style>
	body {
        -webkit-app-region: drag;
        background: #333;
	}
</style>
```
First, here is a screenshot of my app in its default state:
![05](https://cloud.githubusercontent.com/assets/11227866/6517712/4fd94444-c3b3-11e4-8af6-cd9845c6b50a.jpg)

And when double clicking or drag the window to the top border of screen:
![09](https://cloud.githubusercontent.com/assets/11227866/6517780/aa40c074-c3b3-11e4-901e-d4dee1be41b3.jpg)

And when drag to the top-left corner of screen:
![10](https://cloud.githubusercontent.com/assets/11227866/6517792/caacea54-c3b3-11e4-92c7-f0bdf3e765c3.jpg)

First give a maximum height and with to window.
package.json:
```javascript
"window": {
        "title": "Test",
        "icon": "link.png",
        "toolbar": false,
        "frame": false,
        "width": 1000,
        "height": 600,
        "max_width": 1000,
        "max_height": 600,
        "position": "center",
	"resizable": false
}
```
But a new problem. Those transparent borders in left and bottom sides when maximize:
![06](https://cloud.githubusercontent.com/assets/11227866/6517842/6591288c-c3b4-11e4-94b8-9459449b997e.jpg)

And a cutted window if windows width is more than half of the screen width resolution when drag to top-left/right corners:
![07](https://cloud.githubusercontent.com/assets/11227866/6517875/c9f1d542-c3b4-11e4-9821-b87e4ee21d92.jpg)

So more changes needed to get desired behavior. Listen to some window events and do something according to it. Like below code:
```javascript
var gui = require('nw.gui');
var Window = gui.Window.get();
var minimized = false; // Flag to check if user really minimized the window. For resize event. Because when drag to top-left/right corner of screen window will be resized not maximized. and when minimizing, resize event will triggered.
Window.on('maximize', function(event){
    Window.unmaximize();
});
Window.on('resize', function(event){
    if(!minimized)
    Window.unmaximize();
});
Window.on('minimize', function(event){
    minimized = true;
});
Window.on('restore', function(event){
    minimized = false;
});
```

# Final Solution:
1- Give max_width/height same as main window width and height. **Note:** Giving min_width/height will make some other problems. So don't use them.
2- Add these Javascript to your application:
```javascript
var gui = require('nw.gui');
var Window = gui.Window.get();
var minimized = false;
Window.on('maximize', function(event){
    Window.unmaximize();
});
Window.on('resize', function(event){
    if(!minimized)
    Window.unmaximize();
});
Window.on('minimize', function(event){
    minimized = true;
});
Window.on('restore', function(event){
    minimized = false;
});
```

**Comment by xueeinstein** [comment]
## Reproduce results

### define:

__Problem 1__: taskbar problem
__Problem 2__: drag to screen's top border/corners problem
with `frame: false`,  `resizable: false` in `package.json`

version | result
------------ | -------------
v0.12.0 | Only Problem 2
v0.11.3 | Only Problem 1

with `frame: false`, `resizable: true` in `package.json`, `win.setResizable(false)` in `index.html`

version | result
------------ | -------------
v0.12.0 | Only Problem 2
v0.11.3 | Only Problem 2

However, I found __`frame` in `package.json` also influence resizable-behavior__. And the detailed results is:
with `frame: true`,  `resizable: false` in `package.json`

version | result
------------ | -------------
v0.12.0 | __OK__
v0.11.3 | Only Problem 1

with `frame: true`, `resizable: true` in `package.json`, `win.setResizable(false)` in `index.html`

version | result
------------ | -------------
v0.12.0 | __The window is still resizable__
v0.11.3 | __The window is still resizable__

Obviously, if it's not mandatory to use frameless window for your application, using nw-v0.12.0 with `resizable: false` in `package.json` will satisfy the unresizable windows requirement. For frameless window, we'll investigate later, may implement it natively without js tricky.

**Comment by Christywl** [comment]
I try on Windows with nwjs-sdk-v0.24.0. Set `frame: false` and `resizable: false` in `package.json`. Clicking the icon in the taskbar can minimize/restore app window.

**Comment by Christywl** [comment]
close until there is more information.
