### ISSUE TITLE
Strange behavior on tray right click - nwjs-v0.12.0

### ISSUE THREAD

**Issue by johansatge** [nwjs/nw.js#3187]
Hello,

when building a tray with no menu, right click does not seem to work properly.
- When **left** clicking multiple times the event is triggered each time and the active status works well 
- When **right** clicking multiple times, the event is triggered once, then the tray keeps its active status, and a left click is needed to reset it

![screen](https://cloud.githubusercontent.com/assets/5699295/6524226/a8257ee4-c3f7-11e4-83eb-827240f56ddd.png)

---
## Sample code

`package.json`:

``` json
{
  "name": "",
  "inject-js-start": "app.js",
  "main": ""
}
```

`app.js`:

``` javascript
var gui = require('nw.gui');

var tray = new gui.Tray({
    title: '',
    icon: 'tray_icon.png',
    alticon: 'tray_icon.png'
});

// When adding a sample menu, everything works fine,
// i.e. left and right clicks produce the same behavior

// var menu = new gui.Menu();
// menu.append(new gui.MenuItem({type: 'checkbox', label: 'box1'}));
// tray.menu = menu;

tray.on('click', function()
{
    console.log('click');
});
```

---
## Environment
- **OSX** version: `Yosemite 10.10 (14A389)`
- **NW.js** version: `nwjs-v0.12.0-osx-x64`
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
