### ISSUE TITLE
Opening a child window from a <webview> having itself a <webview> is blocking

### ISSUE THREAD

**Issue by armoret** [nwjs/nw.js#3188]
Hi guys,
I have decided to test the new "webview" object released in the nwjs v0.12.0 to build my "business browser" because I wasn't satisfied by the iFrame object (mainly because the pop-up opening event was not thrown as expected, see related issue).

Now, the new window opening event is well catch and I'm able to manage the design of the new window (which is, by the way, the same document than the parent window).

Anyway, I meet an issue : the new open child window contains a webview object that doesn't seem to work and it is even blocking the parent window.

For example, here is how I'm catching the opening event in my browser.html page (snippet):

``` javascript
   <script type='text/javascript'>
    var webview = document.getElementById('webview');

    webview.addEventListener('newwindow', function(e) {     
    // Open new child window, url is passed in a global variable
    var targetUrl = e.targetUrl;
            console.log('Opening url in new window: ' + targetUrl);
            global.url = targetUrl;

     // Load native UI library
    var gui = require('nw.gui');
            var new_win = gui.Window.open('browser.html', {
                "show": true,
                "toolbar": true,
                "icon": "icon.png",
        "title": "CuteBrowser",
                "frame": true,
                "focus": true,
                "position": "center",
                "width": 1024,
                "height": 768,
                "min_width": 640,
                "min_height": 480
            });
    });

        onload = function() {
            console.log('document loaded');
        var webview = document.getElementById('webview');
             webview.src=global.url:
        });

    </script>
```

And here is how the webview is defined:

```
<webview id="webview" src="" style="" autosize="on"></webview>
```

Note : As the url is not static, it is not set in the webview tag itself but only when the window document is loaded otherwise, I can't make it work. 

Do you have an idea why the second window is blocking? Am I missing something?

Best regards
##

**Comment by bachel** [comment]
I have similar problem with webview. When I open new window with gui.Window.open() and there is webview defined with src it doesn't load.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
