### ISSUE TITLE
Researching Compatability with CanIUse.com

### ISSUE THREAD

**Issue by kumavis** [nwjs/nw.js#3192]
When I want to check for cross-browser compatability, my first stop is `caniuse.com`? ([example](http://caniuse.com/#feat=cryptography))
On edge `nw.js`, where should I look on their tables?
If none of those are really appropriate targets, maybe `caniuse.com` would accept `nw.js` as a new target.

**Comment by chino23** [comment]
nw.js uses the Chromium branch, which is the bleeding edge of Chrome. So my guess is that Chrome would do there. Chromium is always ahead of Chrome, so just check the version numbers of the latest build (Chromium 41.0.2272.76 to date).

**Comment by adam-lynch** [comment]
I'd say find the version you're using in the [Downloads section](https://github.com/nwjs/nw.js#downloads) in the readme or [in this wiki entry](https://github.com/nwjs/nw.js/wiki/Downloads-of-old-versions) if it's not there. The Chromium version should be listed there. e.g. `0.8.6: (Apr 18, 2014, based off of Node v0.10.22, Chrome 30.0.1599.66)`.

So just use Chrome 30 in this case as your reference when using `caniuse.com`.

**Comment by kumavis** [comment]
Thanks!
