### ISSUE TITLE
Why u don't use v8/v8-git-mirror new versions of v8?

### ISSUE THREAD

**Issue by LestaD** [nwjs/nw.js#3193]
Where is ECMA Script 6??

**Comment by mrfabbri** [comment]
Hi @LestaD please keep in mind that this sort of inquiries are better addressed by the mailing-list,  anyway nw.js ships with the v8 version matching the upstream chromium (41.0.2272.76 for nwjs 0.12.0 see https://groups.google.com/forum/#!msg/nwjs-general/NJA-Up4MFug/1jmBPjzklSUJ ).

**Comment by mrfabbri** [comment]
see https://github.com/nwjs/nw.js/issues/3193#issuecomment-77656754 

EcmaScript 6 is supported (try `let answer = 42;` for example), some features are behind `--javascript-harmony` argument switch.

**Comment by LestaD** [comment]
Thanks )))
