### ISSUE TITLE
websocket does HTTP CONNECT to SOCKS proxy on Ubuntu

### ISSUE THREAD

**Issue by financehoncho** [nwjs/nw.js#3194]
It seems on Ubuntu node-webkit chooses to connect to websockets (ws/wss) via a SOCKS proxy if both HTTP/HTTPS and SOCKS are configured on the system. That's fine, however it seems to issue an HTTP CONNECT command to the SOCKS proxy instead of using the SOCKS protocol.

**Comment by dehubbed** [comment]
never mind, updating from 0.9.6 to 0.11.6 fixed it.

**Comment by dehubbed** [comment]
please close this.

**Comment by financehoncho** [comment]
never mind, upgrading from 0.9.6 to 0.11.6 fixed this.
