### ISSUE TITLE
NWJC - Windows fail

### ISSUE THREAD

**Issue by acidhax** [nwjs/nw.js#3197]
`test.js`
    function test() {
	console.log(test);
    }

`nwjc.exe test.js test.bin`

`require('nw.gui').Window.get().evalNWBin(null, 'test.bin');`

`test()
VM142:2 Uncaught ReferenceError: test is not defined`

**Comment by Bryan-Turek** [comment]
It's saying test is not defined. Is test an object? or are you trying to do:

    function test() {
      console.log('test');
    }

**Comment by acidhax** [comment]
test is a named function from test.js
When I compile and eval, the named function still isn't available..

**Comment by xueeinstein** [comment]
@acidhax, I have retried you snippet. But I cannot get your error, indeed, it `test()` inner statements become native code. The whole console looks like this:
![image](https://cloud.githubusercontent.com/assets/3424201/6550357/62b993d4-c660-11e4-91cb-549a18742458.png)

**Comment by acidhax** [comment]
This is really odd... Does it still work if you use nwjs x86?

**Comment by acidhax** [comment]
I feel like I'm missing a fundamental step. It either fails compiling (which it doesn't notify me of) or it fails loading because I'm missing something.

**Comment by transaction** [comment]
Looks like you are calling the function from the snapshot itself, outside the function? That might be the wrong way. Try to just define test() with a simple log statement, compile, eval, run test() from console. That should work.

The idea with nwjc is to wrap stuff into functions and calling them from html/js files after loading, for example by passing angular or nw.gui to an init() function defined in the snapshot.

**Comment by acidhax** [comment]
I'm defining test, compiling, evaling and running test() but to no avail. Nothing works, even if its 
function() {
console.log('test');
}

**Comment by transaction** [comment]
Can you post your whole code? test.js, index.html and any other intermediate js files.

Also double-check test.js is the right file and not an old version or a wrong filepath.

**Comment by acidhax** [comment]
https://gist.github.com/acidhax/c3d3c905a79b122f595b

**Comment by acidhax** [comment]
No something else is wrong. My project is busted somehow.

**Comment by acidhax** [comment]
I tracked it down. I have to eval the script in index.html.
