### ISSUE TITLE
Global Hotkeys not working in Ubuntu

### ISSUE THREAD

**Issue by alvarezmario** [nwjs/nw.js#3199]
Hello,
I'm currently trying to achieve a global hotkey command for my app without any luck. In Windows works fine, but not in Ubuntu. I follow the API docs and search over the Internet without success. 
This is my `index.html` with JS code:

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>NW App</title>
        <script>
            var gui = require('nw.gui');
            var option = {
              key : "Ctrl+Alt+M",
              active : function() {
                alert("Global desktop keyboard shortcut: " + this.key + " active."); 
              },
              failed : function(msg) {
                console.log(msg);
              }
            };

            var shortcut = new gui.Shortcut(option);
            gui.App.registerGlobalHotKey(shortcut);
        </script>
    </head>
    <body></body>
</html>
```

And this one my `package.json`

``` javascript
{
  "name": "nw-app",
  "main": "index.html",
  "version": "0.1.0",
  "dependencies": {
    "nw": "^0.12.0"
  },
  "window": {
    "width": 300,
    "height": 500
  },
  "scripts": {
    "start": "nw"
  }
}
```

As you can see is a very simple piece of code only to test the Global Hotkey support, but it isn't working :( :( Does anyone know why isn't working and how can I solve it?
I have NodeJS 0.12 installed. 
Thanks in advance
##

**Comment by nknapp** [comment]
Registration with the windowing system seems to work. Registering a key "a" (without modifiers) causes the "a" not to work anymore in other applications (Terminals, Editors, etc.) 

Also, registering a wrong key "aaa" causes a "failed"-event.

**Comment by apolllo** [comment]
NW 0.12.1 - also seeing the issue

**Comment by outbounder** [comment]
:+1: I have the same issue on Ubuntu 15.04 w/ gnome shell 3.14

**Comment by outbounder** [comment]
btw with nodewebkit v0.10.5 the problem doesn't exists

**Comment by thatwill** [comment]
Also seeing this issue with nwjs-v0.12.2-linux-x64 on Ubuntu 15.04 with gnome 3.16.3.

Can confirm that global hotkey registration works - I also thought to test registering "a", which stops the key from working in other applications. No event appear to be fired off however; no console log from either the active or failed events.

Doesn't make a difference what the shortcut is - tested with various Ctrl+Shift and Ctrl+Alt shortcuts too.

**Comment by CalinLeafshade** [comment]
This seems to also be the case on non ubuntu distros using gnome.
I'm using Arch Linux with Gnome

**Comment by waitianlou** [comment]
I have the same issue on debian8 with nw.js(v0.12.3)

**Comment by tomoki** [comment]
I have the same issue using twm and 3wm with nw.js-v0.12.3-linux-x64 in Arch linux.
This issue may be not gnome only issue.

**Comment by nknapp** [comment]
Oh, I didn't mention that I'm using Lubuntu (LXDE, which uses Openbox as a Window-Manager). It's definitely not Gnome only.

**Comment by nknapp** [comment]
I've just noticed that global shortcuts work on [electron](http://electron.atom.io/docs/v0.27.0/api/global-shortcut/) which is not `nwjs`, more like a competing project. It powers github's atom.io-editor and also is basically a node and a chromium.

**Comment by Pro** [comment]
Same for me on Ubuntu Gnome 15.10, no media keys

**Comment by Christywl** [comment]
`Global Hotkeys` works fine on Linux Ubuntu with nwjs-sdk-v0.24.0.

**Comment by Christywl** [comment]
close until there is more information.

**Comment by szkrd** [comment]
To me "command+something" type shortcuts need to be pressed twice to register (both in mate and gnome3), while they work fine on fluxbox. This happened to me on ubuntu 18 (bionic beaver), on two different installs - though I'm not sure if anyone can reproduce it... would be glad to hear about it.
