### ISSUE TITLE
Fade in/out Window Frame on Focus/Blur

### ISSUE THREAD

**Issue by jaruba** [nwjs/nw.js#3200]
I'm building a video player in node-webkit and this sort of feature would be very helpful for when a video is always on top. Is there any possible way to do something like this atm?

I've checked [the documentation](https://github.com/nwjs/nw.js/wiki/Frameless-window) but it seems to be possible only in the manifest.
Is there a limitation that does not allow doing this while the app is already running or could this be a feature in the next releases?
##

**Comment by PierBover** [comment]
You can make a window transparent, and then you should be able to change the background color in jQuery or any other tween engine to fake a fade in effect of the window

https://github.com/nwjs/nw.js/wiki/Transparency

**Comment by jaruba** [comment]
Do you mean I should draw the window frame in html/css and fade it with jQuery?

**Comment by PierBover** [comment]
Yes, something like that.

**Comment by Christywl** [comment]
Please ask questions and discuss in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
