### ISSUE TITLE
bulid v0.12 cann't running

### ISSUE THREAD

**Issue by coojee2012** [nwjs/nw.js#3203]
Packaged applications use v 0.12, runtime only show nw.js
![qq 20150309112643](https://cloud.githubusercontent.com/assets/3349176/6549499/358c6d20-c64f-11e4-9f19-94d0515d4262.png)

**Comment by coojee2012** [comment]
then  I do this in cmd by using zip.

it says :

Cannot extract package 

Failed to unzip the package file: D:\GitHub\SccinAgi\ReportAPI\cache\0.12.0\win64\App.nw

**Comment by xueeinstein** [comment]
'cannot extract package', maybe your zip package has broken. As guided on wiki, you should package your files, __be attention__: the `package.json` file is in the root directory (if you make a zip file containing a folder with your stuff in it, then it's not going to work). And then rename it as `package.nw`.

The package app works well on my win7/nwjs-v0.12.0
