### ISSUE TITLE
how to register a shortcut only for the application?

### ISSUE THREAD

**Issue by PierBover** [nwjs/nw.js#3204]
I'm using `registerGlobalHotKey` but they get triggered even outside the application.

Is there a way of creating application shortcuts via some NWJS object?

Yes, I can use JS to make my own, but they require the window to be in focus to receive keyboard events. In OSX an application can have many windows and none of those windows be in focus, while the application is indeed in focus. I was wondering if there was something already done in NWJS in this front.
##

**Comment by broderix** [comment]
See https://github.com/nwjs/nw.js/wiki/Shortcut
You can try something like this to get focus:
package.json:
`
"window": {
    "show": false,
...
}
`

```javascript
var window = gui.Window.get();
window.focus();
var shortcut = new gui.Shortcut(option);
...
```
