### ISSUE TITLE
path with # . Uncaught ReferenceError: require is not defind

### ISSUE THREAD

**Issue by HC1988** [nwjs/nw.js#3205]
I created a folder named  "test#" in windows 7,then put my APP in that folder. when i used command line "nw main" open the APP. show  "Uncaught ReferenceError: require is not defined" . But if i renamed my folder with "test". it works well. I don't know what happend . please tell me why and how to resolve it.  thank you for any anwser.I am very anxious to solve this problem.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by HC1988** [comment]
I don't have a try,our app need to support windows XP ,so we don't update the version of nwjs. I'will try   and give you some response.
