### ISSUE TITLE
Webview can't play (flash) video. [$15]

### ISSUE THREAD

**Issue by bachel** [nwjs/nw.js#3207]
When I try to play video from youtube.com in webview I only here sound. In iframe it works fine.
Tested with nw12 on window 7 x64 with flash installed. 

I suspect flash, because it looks like youtube.com try to acces some chrome extensions when loading and after this fail it starts to load flash player instead of html5 video.

```
<html>
    <webview src="https://www.youtube.com/" autosize="on"></webview>   
</html>
```
##

**Comment by iwege** [comment]
Maybe it is html5 video If you can hear the sound.

You can find some helps here :https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.

**Comment by bachel** [comment]
It's not codec problem. Youtube use mostly webm. I can see video in iframe but not in webview element.

**Comment by mckay20** [comment]
I'm seeing the exact same issue. Navigating to any site using Flash or Silverlight content, within a webview, will only play the sound without any video. Video playback works fine in an iframe, even with nwfaketop and nwdisable included. I have verified that HTML5 video works correctly once you have the ffmpegsumo.dll updated.

I have tested this on Windows 8.1 both 32-bit and 64-bit.

**Comment by bachel** [comment]
Works in 0.13.0 alfa2 ... it was ppapi vs npapi flash problem

**Comment by Christywl** [comment]
Also works fine on nwjs-sdk-v0.24.0.

**Comment by Christywl** [comment]
close until there is more information.
