### ISSUE TITLE
Change icon in OSX of nwjs.app

### ISSUE THREAD

**Issue by PierBover** [nwjs/nw.js#3209]
I'm writing this in case anyone struggles as I did.

The only way I've found to change the icon of nwjs.app is to create an icns file, copy it inside the Resources folder of the app (nwjs.app/Contents/Resources) then open a get info window of the nwjs.app file and drag the icns from the Resources over the small icon in the get info window.

Now the new icon appears both in the Finder and Dock. Anything else resulted in either the icon not showing up, or being unable to open the app with an error messages saying it was damaged.

**Comment by felicienfrancois** [comment]
This was documented here: https://github.com/nwjs/nw.js/wiki/Icons
The manipulation you made is equivalent to copying the icns to `nwjs.app/Contents/Resources` and editing `Contents/info.plist` to set CFBundleTypeIconFile to your icns file name

**Comment by PierBover** [comment]
Yes I saw that wiki but it didn't work for me. Doing the steps you describe didn't work either. The finder and dock icons won't change. The only thing that works for me is doing it the way I described.

**Comment by felicienfrancois** [comment]
OK, strange. It may be due to icon cache

**Comment by PierBover** [comment]
Yes it's what I thought too. It seems with `touch` it is possible to refresh this cache.

https://gist.github.com/fabiofl/5873100

I will try some time later and come back. If it works it should be added to the NWJS wiki.
