### ISSUE TITLE
logging not working?

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3216]
Hi,

I've tried to create the debug.log like in chrome, with the chromium-args

```
--enable-logging
```

But nothing gets created. I want to redirect everything that's pushed to the console (errors etc) there. 

Is this not implemented or am I missing something?
##

**Comment by Christywl** [comment]
`"chromium-args":"--enable-logging"` works fine for me on Linux with nwjs-sdk-v0.24.0. The debug log is created in the path `/home/<your user name>/.config/<app name>`.

**Comment by Christywl** [comment]
close until there is more information.
