### ISSUE TITLE
Code.bin not working on windows

### ISSUE THREAD

**Issue by jyapayne** [nwjs/nw.js#3217]
See here for more details: https://github.com/jyapayne/Web2Executable/issues/26

It works when I compile the js file in Linux and then export a linux binary, but if I compile the js file in Windows and export a Windows exe, the resulting app just hangs and I can't even access the console window.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
