### ISSUE TITLE
process.execPath on OS X is not what expected

### ISSUE THREAD

**Issue by B3rn475** [nwjs/nw.js#3224]
Hello.

I'm trying to use nw.js on OS X, and I'm coming up with this particular problem.

process.execPath does not return the path to nwjs ........./My App Name.app/Contents/MacOS/nwjs
It returns ............/My App Name.app/Contents/Framework/nw Helper.app/Contents/MacOS...........

This is really strange.
Expecially because there are 3 nw Helper apps.

How can I get to the real nwjs executable directory?
##

**Comment by adam-lynch** [comment]
`path.join(process.cwd(), '../../..')`

**Comment by B3rn475** [comment]
That could be a workaround, but it breaks the OS independent nature of the project.
If there is no way I'll go for that solution.

**Comment by adam-lynch** [comment]
AFAIK, that's what you'll have to do.

**Comment by shaynem** [comment]
Can just detect if it's OSX

if(process.platform == 'darwin') {}
