### ISSUE TITLE
 FileDescriptorSet destroyed with unconsumed descriptors: 0/1 crash nw12

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3225]
hi

some users report crash with this error or warning ( ubuntu 12.04 64 bit)

>  [3960:0311/011553:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1

how can we have crashdump with nw 12 ?

thanks
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
