### ISSUE TITLE
Support secure binary downloads

### ISSUE THREAD

**Issue by micahflee** [nwjs/nw.js#3228]
The nw.js project distributes binaries at http://dl.nwjs.io/, which is really convenient because then projects like [node-webkit-builder](https://github.com/mllrsohn/node-webkit-builder) can pull them from there.

But as far as I can tell, they're all distributed over http, without support for https, and there also aren't any PGP signatures available.

This means that if I'm a developer working on a nw project and I run my deploy script which downloads nw binaries, I have no way to prevent or even detect an attack. An attacker in this case could replace `nwjs-v0.12.0-win-ia32.zip` with the exact same thing, except replacing `nw.exe` inside with a version that also contains malware. Then when I distribute my software, I'm actually distributing malware without my knowledge.

I think the easiest way to make this problem less bad is to force dl.nwjs.io to go over https. But it would be good to also do what Linux software repositories do, and include a `SHA256SUMS` as well as a `SHA256SUMS.asc` file (which would be a PGP signature, generated with a key controlled by a nw.js developer who does the builds, and tries to keep safe).

This way my deploy script has a way to verify that an attack didn't happen before deciding to bundle binaries downloaded over http with my project.

**Comment by mscreenie** [comment]
+1 Although the cost of an SSL these days isn't prohibitive maybe we could raise the necessary funds for this to happen? 

It's probably worth asking Roger if he has something like this planned, would not be surprised if its crossed his mind already.

**Comment by shaynem** [comment]
Or you could pull and check md5 to your own sever and deploy however you
wish.

**Comment by micahflee** [comment]
The problem with hardcoding the `MD5SUMS` files and comparing hashes each time you download a file is it's not very robust, and there's no way to bootstrap trust the first time.

For example, let's say I hardcode http://dl.nwjs.io/MD5SUMS into my project. How can I be sure that I downloaded that correctly to begin with? (There are some tricks, like download it several times from different IPs and compare, but people shouldn't have to do things like that.)

As of now that file only includes hashes for up to v0.12.0. What happens when a new version comes out? I have no way of confirming that the new binaries are trustworthy, and if I update my `MD5SUMS` file I again have no way to know that I downloaded it without getting attacked.

Because keep in mind that any attacker who can make me download a fake `nwjs-v0.12.0-win-ia32.zip` can just as easily make me download a fake `MD5SUMS`. This is why actual PGP digital signatures, where a developer maintains a private key that's used to sign the checksum file (or the individual binary files) is significantly more secure.

Also, at this point MD5 is pretty much useless for security, and only useful for checking for download errors. It has been [broken](https://en.wikipedia.org/wiki/MD5#Collision_vulnerabilities) for many years, and an attacker would be able to create a malicious `nwjs-v0.12.0-win-ia32.zip` that has the same MD5 hash as the real one. If you're using a hash function for security, you should use SHA256 or stronger.

**Comment by shaynem** [comment]
The point i was trying to make was you could download directly from github
that provides HTTPS.

However upon checking i notice the pre-built binary's are linked to
dl.nwjs.io from the github page.

My suggestion albeit not very clear was to download the binary to your own
server (verify however you wish) - and then bootstrap from your application
to your own server establishing the trust, that way each time your project
has the trusted binary.

The only way to-do this by establishing first trust would be to build from
source since it's hosted via HTTPS.

While it's a painful work around, if you highly regard this as a major
issue spending the extra time to build from source and deploy from your own
server to your application would be desirable since you would be in-control
of the entire deploy process even if nwjs.io had a HTTPS certificate.

**Comment by transaction** [comment]
Digital signatures would be a simple, inexpensive solution. I use it for verifying auto updates on our nwjs app.

**Comment by j13z** [comment]
I’d really like to have checksums, too (or HTTPS). 

What about adding a checksums file for the builds served from `http://nwjs.io` to this GitHub repo (HTTPS)?

**Comment by micahflee** [comment]
I agree that digital signatures are a much better solution than just checksums, and it's pretty simple to do in practice. If you only provide a checksums file and an attacker is able to either hack the web server or modifying downloads in transit for a specific developer, the attacker could just change the checksums file so that it all checks out. This attack becomes much more expensive if you're using signatures.

It would basically just involve this: After making a new nw.js release and building all associated files (like everything in here http://dl.nwjs.io/v0.12.0/), run a script that takes sha256 hashes of each file and stores it in a file called `SHA256SUMS`, and then run `gpg -a --detach-sig SHA256SUMS`, which would end up giving you a new file called `SHA256SUMS.sig`. The person in charge of making these releases would just need to generate a master nw.js signing key and keep it safe.

At that point, even if you keep dl.nwjs.io http, it will be possible for people to download binaries and verify that they're legit.

**Comment by barrykeegan** [comment]
Any update or anyone working on this issue? I currently am the maintainer of the nwjs-sdk release on the arch user repository.  This currently requires me to download the 64bit and 32bit versions (which is slow), run sha1sum over them (without knowing whether or not they got corrupted on the way) and updating the PKGBUILD file with the relevant release version and sha1sum info for makepkg to use for verification (again without knowing if the sha1sum was generated from a corrupted file).

It would be much better if just after building each release a checksum document of some sort (hosted on github) would be updated with the latest release checksums generated from a known clean build of the release in question.

**Comment by rogerwang** [comment]
This is now supported: https://dl.nwjs.io
