### ISSUE TITLE
My game in fullscreen mode,the node-webkit app( which set always on top) disappear?

### ISSUE THREAD

**Issue by xiebaochun** [nwjs/nw.js#3230]
As the title described，anyone can help me? I will appreciate it.
##

**Comment by knockshore** [comment]
Are you saying that the window disappears after setting it always on top?

and can you post the results from dev tools:
```
process.versions
process.arch
process.platform
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
