### ISSUE TITLE
Cannot extract package 

### ISSUE THREAD

**Issue by coojee2012** [nwjs/nw.js#3231]
Cannot extract package 

Failed to unzip the package file: App.zip

---

When a program when a dependent package 'node - highcharts - exporter, run a zip or nw packages, prompt unable to unpack the package.
To remove the bag, the program is running normally.
I doubt is depend on the package containing dependent package path is too deep, to make mistakes!

当程序中安装有依赖包‘node-highcharts-exporter’时，运行zip或nw包时，提示无法解压包。
删除该包，程序运行正常。
我怀疑是依赖包里面包含的依赖包路径太深，导致解出错！
##

**Comment by iwege** [comment]
put the deep module to the `dependence` and use `npm dedupe` to reduce the path length.

**Comment by coojee2012** [comment]
thanks iwege.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
