### ISSUE TITLE
nwjc snapshot question regarding platforms

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3232]
I understand that I can only build a Mac snapshot on a Mac, and a Windows one on Windows, etc.

But how about the 64bit/32bit difference?

Can I use nwjc to create a snapshot on Windows 64bit and then use the snapshot.bin in both the 64bit and 32bit app? Or does this also apply here, one snapshot per platform and 64bit/32bit?

**Comment by liyingzh** [comment]
Tested result is snapshot made by 64bit nwjc only works on 64bit nw.

**Comment by chino23** [comment]
Ah ok, I see. Thanks for comfirming!

**Comment by chino23** [comment]
One more thing: Doing a snapshot on Windows 7 64 bit, does it work on Windows 8 as well?

And how about Mac OS, having a snapshot on 10.10 does it run on 10.9 and below?

**Comment by liyingzh** [comment]
please take a look at https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot#limitation-of-nwjc

**Comment by chino23** [comment]
Ok, I think that solves it. Thanks!
