### ISSUE TITLE
How to use child_process API with nw.js?

### ISSUE THREAD

**Issue by cookiengineer** [nwjs/nw.js#3233]
Hey everyone, I'm using the latest stable 0.12 from the iojs build (linux amd64).

Unfortunately I can't spawn any processes and I have no clue why.
I'm currently developing a tool that should be a GUI for my webserver / websocket servers, so that you can start/stop the webserver easier than running shell scripts.

For that purpose I created a helper.sh that opens everything for each operating system, but using the xdg-open or open binary on OSX / Linux. The shell script itself works without any issues and is returning a proper exit(0);

When I try to spawn / fork / exec / execSync within nw.js however, I can't see any process that was created. As I might have observed already, it seems as executing the shell scripts won't work because the spawn args are always containing the nw binary as the first argument (and that can of course not execute shell scripts).

See this screenshot that contains also all relevant code:
http://i.imgur.com/EDORGRN.png

Am I missing something?
Should I use the child_process.spawn API directly?
How to launch a process with /bin/bash?
##

**Comment by martensms** [comment]
I think, even when using child_process.exec() directly, the spawnargs are false.

Look at this screenshot: http://i.imgur.com/uU2guI2.png

The third argument is missing "args0 args1", so the final executed command is ```sh -c helper.sh arg0 arg1``` which should be ```sh -c helper.sh "arg0 arg1"```

**Comment by polpo** [comment]
In your first screenshot, you are using `child_process.fork()` which is for starting new Node/io.js/nw.js processes, with a `.js` file as the argument.

The `spawnargs` in the second screenshot are correct. There are no missing quotes. For example, when running `sh -c "helper.sh arg0 arg1"` from a shell, the shell interprets the `"` characters, resulting in a process with three entries in `argv[]`: `sh`, `-c`, and `helper.sh arg0 arg1`.

If you leave off the inner `"` characters in your `child_process.exec('"helper.sh file:///home/test"');` line and it should work.

Your `child_process.spawn()` line should be working. The setuid sandbox error is a red herring and can be ignored (see [this issue](https://github.com/nwjs/nw.js/issues/2699)).

In a project of mine I am running bash with code similar to the following and it all works fine:
```javascript
var myProcess = child_process.spawn('bash', ['-c', 'source ./my_env.sh; ./my_program arg0 arg1']);
```
