### ISSUE TITLE
Event based APIs cause crashes when an event fires after registering window has closed

### ISSUE THREAD

**Issue by redgecombe** [nwjs/nw.js#3236]
If a window registers an event with a node-webkit API that has callbacks (Tray, Screen, etc), and then that window is closed while the app remains running, node-webkit will exit/crash.

For example have an App with two windows open.  In one window, register for some events like this:
gui.Screen.Init();
gui.Screen.on("displayRemoved",function(){console.log("display removed")});
var tray = new gui.Tray({ title: 'Tray'});
tray.on("click",function(){console.log("tray click");});

Then close the window that registered the events, then make an action that triggers one of the events (click the tray or remove a display).  The remaining open window will close as the event fires and node-webkit will exit.

I can reliably reproduce this in my own app on Windows with in 0.12.0, I will upload a simple app that can reproduce the issue on Monday.
##

**Comment by redgecombe** [comment]
Here is a sample that reproduces:
https://gist.github.com/redgecombe/f3804711c67802142d5b

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
