### ISSUE TITLE
Consider using the courgette of Chromium for software update?

### ISSUE THREAD

**Issue by bestplay** [nwjs/nw.js#3237]
As the title, can we use the courgette for increment update?
##

**Comment by bestplay** [comment]
Just like the way chrome auto update,  called courgette. It depend on bsdiff, and sound like better than bsdiff. 

It can compare two versions of binary, and generate patch for update.

Just download the patch with different. NOT the whole new version.

I have try to compile courgette of chrome, but failed by the network (GFW) in my (tianchao) country.

Any help will help! thanks.

**Comment by bestplay** [comment]
@rogerwang

**Comment by bestplay** [comment]
I have finished compiling courgette of chrome. And i use it as a tool for my software update.

It is great. 

maybe

**Comment by remicaillot** [comment]
Can you tell me how did you do that, this is interresting me. i'm always asking how to make a update system.

**Comment by bestplay** [comment]
@remicaillot 
Sorry about my delay response, the guides I follow all in below.
 
http://stackoverflow.com/questions/12542591/how-to-compile-google-courgette-tool
http://www.chromium.org/developers/how-tos/build-instructions-windows

**Comment by bestplay** [comment]
@remicaillot 
If you only use it in windows. I can send the courgette.exe which i currently using  to you.

**Comment by czciou** [comment]
@bestplay hi.i'm from tianchao too.could I have your courgette.exe please? I could not figure it out on my mac.let me try it in windows.Any help will much appreciative. my address is czciou@qq.com

**Comment by twinslizzy** [comment]
@bestplay hi, could you share the courgette.exe for me, thanks, do you use it in 32-bit or 64-bit? thanks
my email is twinslizzy@163.com

**Comment by bestplay** [comment]
@twinslizzy  win32 only, but you can get it by compiling the source.

@czciou 

I will send to you by email.

**Comment by rogerwang** [comment]
We'll consider using this if we work on the auto update feature. Merging this issue with #233

**Comment by sgegmbh** [comment]
@bestplay Would you mind sharing the windows 32bit executable? I am interested in it.

**Comment by bestplay** [comment]
@sgegmbh of course, leave your E-mail. I will send it to you

**Comment by sgegmbh** [comment]
Perfect. 13141516 [a] gmx.de Thanks.

**Comment by bestplay** [comment]
@sgegmbh Sent.

**Comment by keshav0891** [comment]
@bestplay Can you please share the executable at dragonite0891@gmail.com? Thanks.

**Comment by Ajeey** [comment]
@bestplay And I assume this only updates the chromium or does it update the entire node webkit binary?

Also can you share the exe to me at ajey.charantimath@gmail.com

**Comment by bestplay** [comment]
@Ajeey you need handle it yourself. 
I use courgette + async

**Comment by trueYJlove** [comment]
@bestplay how to use courgette? 
The difference file suffix I produced with courgette is .diff. The size is only 1k (because I haven't changed much). I didn't produce a exe file with a difference. Why is this?

**Comment by bestplay** [comment]
@trueYJlove You need courgette.exe to build the new version with the old one and the diff file.
- server side: 
  - Use courgette to prepare the diff file from old version to new
- client side:
  - I packed courgette.exe inside client side app. when new version found, client side will download the diff file, and use courgette to build a new one

**Comment by trueYJlove** [comment]
@bestplay 
Hey, thanks for the reply. I first generated a mini_installer.exe and then installed it. At this time I put chrome.7z courgette.exe setup.exe in the local directory C:\Temp\base, and then modify build.gn to release the difference update settings. Then execute ninja -C out/X86 mini_installer to try to generate a differential update file, but the generated mini_insataller.exe size is the same as I originally generated. I don't know where the problem is.
Are you also Chinese? You can add contact information or send an email to you to explain the details and then guide me, this problem has been bothering me for a long time...
