### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by mn1aC** [nwjs/nw.js#3238]
If I run a PHP page package.json looks like this: "main": "http://10.0.1.4/optios/admin/adminpanel.php?optios_id=55"

And I'm trying to detect node webkit with this javascript code on adminpanel.js
var isNode = (typeof process !== "undefined" && typeof require !== "undefined");
	alert(isNode);
	var isNodeWebkit = false;
		
	//Is this Node.js?
	if(isNode) {
	  //If so, test for Node-Webkit
	  try {
	    isNodeWebkit = (typeof require('nw.gui') !== "undefined");
	  } catch(e) {
	    isNodeWebkit = false;
	  }
	}
	alert(isNodeWebkit);
I get 2x "false"

when I'm using a .html file with the same piece of javascript, the alert prompts 2 x "true"

What I'm I doing wrong?

**Comment by shichon64** [comment]
Instead of replace all of your post by "solved" you could share your solution no? ... -_-
