### ISSUE TITLE
registerGlobalHotkey inconsistent behavior

### ISSUE THREAD

**Issue by flamingtop** [nwjs/nw.js#3239]
on windows 7 professional N 64bit

```
  var option = {
    key: "M",
    active : function() {
      console.log("Global desktop keyboard shortcut: " + this.key + " active.");
    },
    failed : function(msg) {
      console.log(msg);
    }
  };
  var shortcut = new gui.Shortcut(option);
  gui.App.registerGlobalHotKey(shortcut);
```

issue 1: pressing 'm' key when nw window is not focused could crash nw, a windows pops up saying "nw.exe" stopped working
issue 2: console reports "Register global desktop keyboard shortcut failed." while the 'm' key is actually being listend on
issue 3: 'm' key stops propgating - not showing up in a a textarea or text box
##

**Comment by totyumengr** [comment]
Same on my desktop: crash but no window popup...

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
