### ISSUE TITLE
Feature request: get error codes from network requests

### ISSUE THREAD

**Issue by oNaiPs** [nwjs/nw.js#3245]
I understand that the standard does not want you to access this information programmatically, but due to the fact we're targeting locally rendered pages, it would be very useful to get a string error of for example a failed socket connection. One place that chrome currently shows the error is in dev tools, or the error page.

What about something like, 
```
window.errorStringForRequest(xhrrequest)
```

Other option would be to directly insert in the object.
![screen shot 2015-03-16 at 11 46 27 am](https://cloud.githubusercontent.com/assets/374130/6673659/202e5eba-cbd2-11e4-8f2a-441b46dc0fcd.png)

**Comment by polpo** [comment]
The chrome webrequest API, new in nw.js v0.12.0, should be able to do this. See the [onErrorOccurred](https://developer.chrome.com/extensions/webRequest#event-onErrorOccurred) event.

**Comment by oNaiPs** [comment]
It does work ;) thank you very much
