### ISSUE TITLE
Open .nw file in OS X

### ISSUE THREAD

**Issue by Paxa** [nwjs/nw.js#3247]
It worked before (0.9.1), but with new version of nwjs it's not working
##

**Comment by Christywl** [comment]
It works fine for me on Mac with nwjs-sdk-v0.24.0. Put `app.nw` into `nwjs.app/Contents/Resources`, and run `./nwjs` in `nwjs.app/Contents/MacOS`.

**Comment by Christywl** [comment]
close until there is more information.
