### ISSUE TITLE
latest stable runs node-main twice

### ISSUE THREAD

**Issue by soldair** [nwjs/nw.js#3248]
node main gets executed twice on startup. tested on linux 64

package.json

```
{
"main":"index.html",
"node-main":"index.js"
}
```

index.js

```
process.stdout.write("starting node main pid "+process.pid);
```

index.html

```
hi
```

``` sh
~/nwjs-v0.12.0-linux-x64/nw ./
```
##

**Comment by PavelSapachev** [comment]
I have the same problem. Does anyone know the solution?

**Comment by soldair** [comment]
I worked around it by only running code in the background page :(
not ideal but just have your main module export a function and call it in the index.html. I think this works even with no ui. And I'm pretty sure this is what I ended up doing.

**Comment by JanStevens** [comment]
Same issue using 0.12.02

**Comment by jgoalby** [comment]
Same issue nwjs-v0.12.2-osx-x64.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
