### ISSUE TITLE
does not exit the whole app

### ISSUE THREAD

**Issue by askie** [nwjs/nw.js#325]
I'm using code to exit whole app 

``` javascript
mainwin.on('close', function () {
    gui.App.closeAllWindows();
    gui.App.quit();
});
```

or 

``` javascript
mainwin.on('close', function () {
    gui.App.quit();
});
```

but there are some hide windows still working on background

os  win7
node-webkit v0.3.6
node.js v0.8.14

**Comment by vivekgaikwad** [comment]
You can use below code to close all the running windows in the background:
var gui = require('nw.gui');
var win = gui.Window.get();

mainwin.on('close', function () {
        gui.App.closeAllWindows();
        win.close(true);
}
By the above all the windows running in the background will be closed and you can check task manager after that.
