### ISSUE TITLE
Proxy Configuration Crash using AJAX Request

### ISSUE THREAD

**Issue by brospars** [nwjs/nw.js#3250]
Hi !
The Proxy Configuration opens a dialog to enter login/password but crash when submitted. (Windows 8 & Ubuntu 14.04 64bits)

Second issues :
Is there a way to autocomplete the login/password without opening this prompt ? My app is meant to run alone without any interaction so it would be great to pass it like this maybe `gui.App.setProxyConfig("login:password@192.168.0.5:3128");`
##

**Comment by benuts** [comment]
It seems it was the timeout in AJAX requests that crashed the app.

Now the problem is to autologin. Is there a way to do that ? 

Thanks for the help !

**Comment by Robing** [comment]
I have the same problem, I don't know how to prevent application crash

**Comment by kennyhk** [comment]
me too.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
