### ISSUE TITLE
SSL self signed certificate inside iframe extend --ignore-certificate-errors

### ISSUE THREAD

**Issue by r1si** [nwjs/nw.js#3253]
Hi all,<br>
I have a nw.js app with this package json

``` javascript
{
  "main": "index.html",
  "name": "test_app",
  "window": {
    "toolbar": false,
    "position": "center",
    "min_width": 800,
    "min_height": 500,
    "as_desktop": true,
    "resizable": true,
    "frame": true,
    "chromium-args": "--ignore-certificate-errors"
  },
  "webkit": {
    "plugin": true,
    "page-cache": true
  }
}
```

my index.html include this code:<br>

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>demo</title>

</head>
<body>
<iframe src="https://www.example.com"></iframe> 
<script type="text/javascript" src="js/jquery.min.js"></script>
<script>
    function myfunc(){
        alert("my func");
    }
</script>
</body>
</html>
```

the problem:<br>
for example: 
my site (src of iframe) https://www.example.com have a self signed certificate, so if I try to load in console give me this error:<br>
Failed to load resource: net::ERR_INSECURE_RESPONSE  
Why --ignore-certificate-errors don't extended inside iframe child?
thanks in advance!
##

**Comment by r1si** [comment]
any news?

**Comment by ralamgstromg** [comment]
Hi Friend, try this config file:

{
  "main": "index.html",
  "name": "test_app",
  "chromium-args": "--ignore-certificate-errors"
  "window": {
    "toolbar": false,
    "position": "center",
    "min_width": 800,
    "min_height": 500,
    "as_desktop": true,
    "resizable": true,
    "frame": true
  },
  "webkit": {
    "plugin": true,
    "page-cache": true
  }
}

**Comment by Christywl** [comment]
The ralamgstromg's package.json works fine for me on Linux with nwjs-sdk-v0.24.0. I don't see `Failed to load resource: net::ERR_INSECURE_RESPONSE`. Please add "chromium-args" in package.json directly, not in window field.

**Comment by Christywl** [comment]
close until there is more information.
