### ISSUE TITLE
You can open a file dialogue multiple times on windows, it should block.

### ISSUE THREAD

**Issue by tonypee** [nwjs/nw.js#3257]
When using <input type="file"> you can click it multiple times, since you are able to defocus the dialogue (not possible in Webkit - chrome) then click the input again. When this happens, as soon as you select a file in the 1st dialogue, another will popup. Only the value selected in the 1st dialogue is sent to your application as a 'change' event. This means all other dialogues are useless, and confusing. 

tested on 0.10.5
##

**Comment by iwege** [comment]
+1

**Comment by Christywl** [comment]
close until there is more information.
