### ISSUE TITLE
Node-webkit notification styles

### ISSUE THREAD

**Issue by zhailei31665431** [nwjs/nw.js#3261]
How to change Notification style. Using html5 default style?Using version 0.12.0 will be two icon...

**Comment by rogerwang** [comment]
nw v0.13.0-alpha0 now supports rich notifications, with which you can put buttons, images, lists etc in the notification. See https://groups.google.com/d/msg/nwjs-general/IqfH1RXNGlw/2PgeRGHO-B4J

**Comment by Paxa** [comment]
Are you looking for something like this https://www.npmjs.com/package/nw-notify
