### ISSUE TITLE
NW.js 0.12 Closes Unexpectly

### ISSUE THREAD

**Issue by andresmart** [nwjs/nw.js#3262]
Hi,

when nw is minimized to Tray in Windows 7, the app closes unexpectly without error message. Looking for in Event Viewer appear this

Faulting application name: nw.exe, version: 0.0.0.0, time stamp: 0x54f7d2ce
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x83fddba8
Faulting process id: 0x16fc
Faulting application start time: 0x01d0617d2baa78f6
Faulting application path: C:\Users\myusername\nw\nw.exe
Faulting module path: unknown
Report Id: 9cb9ef77-cda0-11e4-9e90-b8ac6f827f03

Thanks
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
