### ISSUE TITLE
Shortcut example not working?

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3263]
I'm trying to get keyboard shortcuts/hotkeys working inside the sample node webkit app. I'm using the code found in the shortcuts wiki page (which can be found here: https://github.com/nwjs/nw.js/wiki/Shortcut)

But it keeps breaking on this line saying ```undefined is not a function```

```
var shortcut = new gui.Shortcut(option);
```

**Comment by justinmchase** [comment]
Which version of nwjs are you using? I tried it also and it was working for me. Can you inspect what gui is for more info?

    var util = require('util')
    console.log(util.inspect(gui))
    console.log(util.inspect(gui.Shortcut)
    console.log(util.inspect(option))

I do believe the option object has to have two functions on it, it could be that you forgot one or misspelled the name of the property.

**Comment by joshuaterrill** [comment]
Here is what I get from those three console.log's.

```
using node-webkit v0.8.6 webkit-controls.js:7
inspect { Base: 
   { [Function: Base]
     super_: { [Function: EventEmitter] listenerCount: [Function] } },
  MenuItem: { [Function: MenuItem] super_: { [Function: Base] super_: [Object] } },
  Menu: { [Function: Menu] super_: { [Function: Base] super_: [Object] } },
  Tray: { [Function: Tray] super_: { [Function: Base] super_: [Object] } },
  Clipboard: { get: [Function] },
  Window: { get: [Function], open: [Function] },
  Shell: 
   { openExternal: [Function],
     openItem: [Function],
     showItemInFolder: [Function] },
  App: {} } webkit-controls.js:14
inspect undefined 
inspect undefined 
```

I prefaced each one with "inspect" before the output. As you can see, the last two say undefined. I'm using nodewebkit version ```0.8.6```

Could you give me an example of the code that you used where yours worked?

**Comment by stephan-nordnes-eriksen** [comment]
I am having the same issue on `0.12.0` using osx. Global shortcuts work fine.

Output:

```
    var util = require('util')
    console.log(util.inspect(gui))

{ Base: 
   { [Function: Base]
     super_: 
      { [Function: EventEmitter]
        EventEmitter: [Circular],
        usingDomains: false,
        defaultMaxListeners: 10,
        init: [Function],
        listenerCount: [Function] } },
  MenuItem: { [Function: MenuItem] super_: { [Function: Base] super_: [Object] } },
  Menu: { [Function: Menu] super_: { [Function: Base] super_: [Object] } },
  Tray: { [Function: Tray] super_: { [Function: Base] super_: [Object] } },
  Clipboard: { get: [Function] },
  Window: 
   { get: [Function],
     open: [Function],
     canSetVisibleOnAllWorkspaces: [Function] },
  Shell: 
   { openExternal: [Function],
     openItem: [Function],
     showItemInFolder: [Function] },
  App: {},
  Shortcut: { [Function: Shortcut] super_: { [Function: Base] super_: [Object] } },
  Screen: { Init: [Function] } }



    console.log(util.inspect(gui.Shortcut)

{ [Function: Shortcut]
  super_: 
   { [Function: Base]
     super_: 
      { [Function: EventEmitter]
        EventEmitter: [Circular],
        usingDomains: false,
        defaultMaxListeners: 10,
        init: [Function],
        listenerCount: [Function] } } }



    console.log(util.inspect(option))
    { key: 'H', active: [Function], failed: [Function] }
```

**Comment by shaynem** [comment]
The wiki does say

Shortcut API requires node-webkit >= 0.10.0

I'm using 11 and short cuts are working fine. If you want a code example
let me know as I'm not at the computer atm.

**Comment by stephan-nordnes-eriksen** [comment]
@shaynem If you have some example of working code that would be great. I can't seem to get my local shortcuts to work. My global shortcuts work fine. Very strange.

**Comment by dwkns** [comment]
I'm having exactly the same problem (on OS X). Here is my code : 

	 var gui = require('nw.gui');
	 gui.Window.get().showDevTools();

	var option = {
	     key: "Ctrl+Alt+Z",
	     active: function() {
	         console.log("Global desktop keyboard shortcut: " + this.key + " active.");
	     },
	     failed: function(msg) {
	         // :(, fail to register the |key| or couldn't parse the |key|.
	         console.log(msg);
	     }
	 };

	 // Create a shortcut with |option|.
	 var shortcut = new gui.Shortcut(option);

	 // Register global desktop shortcut, which can work without focus.
	 gui.App.registerGlobalHotKey(shortcut);

	console.log("node.js : "+process.version);
	console.log("nw.js : "+process.versions['node-webkit']);
	var util = require('util');
	console.log(util.inspect(gui));
	console.log(util.inspect(gui.Shortcut));
	console.log(util.inspect(option));

And the console output (dev tools window wouldn't let me copy/paste - related?) :
![image of my code](http://i.imgur.com/qBQQG3u.png)
