### ISSUE TITLE
Maxium WebGL texture size differs from Chrome

### ISSUE THREAD

**Issue by ChiChou** [nwjs/nw.js#3265]
Running the following javascript code snippet both nw.js and Chromium leads to quite different results.

```javascript

var canvas = document.createElement('canvas');
var gl = canvas.getContext('webgl');
gl.getParameter(gl.MAX_TEXTURE_SIZE);

// returns 16384 in Chrome, 4096 in nw.js

```

Is there any limit by OpenGL ES specification or it's just a bug?

My system enviromnent:

> MacBook Pro (Retina, 13-inch, Mid 2014)
> OS X Yosemite 10.10.2
> Graphics: Intel Iris 1536 MB

> Google Chrome Version 40.0.2214.111 (64-bit)

> nw.js v0.12.0-alpha2 with Chromium 41.0.2236.2

![image](https://cloud.githubusercontent.com/assets/2802045/6724201/23486d3a-ce2e-11e4-9aa7-92b67a11ff87.png)

**Comment by sandover** [comment]
This issue is important for applications targeting larger screen sizes.
