### ISSUE TITLE
Chinese document is down

### ISSUE THREAD

**Issue by jiyinyiyong** [nwjs/nw.js#3268]
This one http://www.xuanhun521.com/?search=node in https://github.com/nwjs/nw.js/wiki#for-users

**Comment by xuanhun** [comment]
I checked the url you gave, it's ok。

**Comment by jiyinyiyong** [comment]
OK now. Probably network problem... where is that PHP server hosted?

**Comment by xuanhun** [comment]
Asp.net mvc4，IIS hosted。

**Comment by jiyinyiyong** [comment]
Is that outside mainland China...?
