### ISSUE TITLE
getMediaSource() video y offset

### ISSUE THREAD

**Issue by deificx** [nwjs/nw.js#3269]
A bit of googling returns this issue: https://code.google.com/p/chromium/issues/detail?id=376228

I seem to have the same problem on nwjs 0.12.0 on Windows with chromium 41.0.2272.76
##

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.24.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
