### ISSUE TITLE
Are the applications required to be .nw files?

### ISSUE THREAD

**Issue by baconbrad** [nwjs/nw.js#3270]
I noticed I was able to build and run a NW.js project just by making it a zip and running `copy /b nw.exe+myfile.zip myapp.exe`. I couldn't see an issue with the result and it has ran as good as my .nw builds. But everywhere I look it is encouraged to rename the extension before the build. I figured if it was major nw.js would check the file extension and throw an exception if it was not a .nw file during unpacking. Is the renaming just a name convention or is there a really important reason it needs to be an .nw file?
##

**Comment by transaction** [comment]
I believe it's only an issue when using native modules. If you rebuild them for nwjs and change the exe, the module won't be found.

Would be great if this could be fixed without building nwjs yourself though, not sure if that would require alot of work.

**Comment by baconbrad** [comment]
I haven't been into NW.js development for a while. But this still seems like the case. Closing it because [you should automate the process through build tools](https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps#step-2a-put-your-app-with-nw-executable) and it really doesn't affect this project in a way that needs to be fixed.
