### ISSUE TITLE
On hires displays, texts look sharp in 0.11.6, but blurry in 0.12.0

### ISSUE THREAD

**Issue by highco** [nwjs/nw.js#3272]
Texts look sharp in node-webkit 0.11.6, but blurry in NW.js 0.12.0.
![blurry-text](https://cloud.githubusercontent.com/assets/373616/6760947/399ee444-cf4e-11e4-88ea-c08c59850494.png)
The image is magnified by 300%. I'm using a 3200 x 1800 display and Windows 10. What changed in 0.12.0 that could have caused this?

**Comment by benjismith** [comment]
The problem has been reported, in this issue: https://github.com/nwjs/nw.js/issues/2998

As you can see from the notes, @rogerwang self-assigned the issue on January 25, but there hasn't been any update since then.

**Comment by rogerwang** [comment]
fixed and released in 0.12.1
