### ISSUE TITLE
Prevent maximizing on double-click using `-webkit-app-region:drag

### ISSUE THREAD

**Issue by edi9999** [nwjs/nw.js#3274]
Hi,

I have the opposite issue of #2210.
I'm using the `-webkit-app-region:drag` css style on my body.

I would like to use drag-drop functionality for my nw-windows, without giving the possibility to maximize them by doubleclicking, because those windows aren't supposed to be maximized at all.

I have tried to overwrite the onclick event on the whole body of my window:

```
document.onclick=function(e){
  e.preventDefault();
}
```

but this doesnt have any impact.

Is they anyway to have the drag-drop behaviour without also having the doubleclicking behaviour ?
##

**Comment by Strat-** [comment]
Related: #3067

**Comment by ligolas** [comment]
I've been subscribing this issue for a while and got no update, then I tried some other keywords, and I find this #2319.They did not fix the problem, but they did have given a workaround by  'setting min_width/height and max_width/height to your initial width/height' . Might be useful for you @edi9999 :)

**Comment by gbraga** [comment]
+1 
I need enable the drag, but I want disable the double click (to maximize).

function disableDoubleClick () {
                var elem = $('#titlebar');

                elem.dblclick(function (e) {
                    console.log("test");
                    e.preventDefault();
                });
            }

**Comment by fritx** [comment]
(Again, related: #3067)
Seems the `-webkit-app-region:drag` currently isn't in control.
And we had the same issue, we wanted to prevent from maximziing with double-click.
Finally, we implemented a custom-dragging in JavaScript, so we did it!
Here is our code to self-implement dragging on frame window, it works well now:
https://github.com/h5lium/xstu/commit/305caab064efdbf293fa49796c4d3bad3c8b0117

```js
var dragging = false
var mouse_x, mouse_y
var win_x, win_y
$nav.on('mousedown', function(e){
  e = e.originalEvent || e
  var isbg = $(e.target).closest('.navbar-nav, #form-user').length < 1
  if (!isbg) return
  dragging = true
  mouse_x = e.screenX
  mouse_y = e.screenY
  win_x = win.x
  win_y = win.y
})
$win.on('mousemove', function(e){
  if (!dragging) return
  win.x = win_x + (e.screenX - mouse_x)
  win.y = win_y + (e.screenY - mouse_y)
})
$win.on('mouseup', function(){
  dragging = false
})
```

**Comment by wufeng87** [comment]
@fritx , this method could lose the mousemove event when you drag fast and move mouse out of the window. If you mousedown on the window edge, the bug could  reproduce more easily.

**Comment by wufeng87** [comment]
Using this method (thx my friend), work much better.
```javascript
    var wX = 0;
    var wY = 0;
    var dragging = false;
    $nav.mousedown(function(e){
        dragging = true;
        wX = e.pageX;
        wY = e.pageY;
    });
    $(window).mousemove(function(e){
        if(dragging){
            win.moveTo(e.screenX-wX, e.screenY-wY);
        }
    });
    $(window).mouseup(function(){
        dragging = false;
    });
```

**Comment by fritx** [comment]
Thanks! Your one is simpler. @wufeng87

**Comment by bansalvks** [comment]
@wufeng87 You code is not working for me. Here is what I did

**```
>         $(document).ready(function () {
> 
>             var wX = 0;
>             var wY = 0;
>             var dragging = false;
>             $('#chatIcon').mousedown(function (e) {
>                 dragging = true;
>                 wX = e.pageX;
>                 wY = e.pageY;
>             });
> 
>             $(window).mousemove(function (e) {
>                 e.stopPropagation();
>                 e.preventDefault();
>                 if (dragging) {
>                     var xLoc = e.screenX - wX;
>                     var yLoc = e.screenY - wY;
>                     win.moveTo(xLoc, yLoc);
>                 }
> 
>             });
> 
>             $(window).mouseup(function () {
>                 dragging = false;
>             });
>         });
```**

And this is what is happening

![capture](https://cloud.githubusercontent.com/assets/8565993/15213876/8296bc36-1867-11e6-8982-807bc33049ca.PNG)

**Comment by Christywl** [comment]
@edi9999 , does wufeng87's code work for you? Can we close this issue?

**Comment by edi9999** [comment]
Sorry, the project that I had that had this issue is now dead, so I can't try it out.

**Comment by edi9999** [comment]
We can close this
