### ISSUE TITLE
-webkit-app-region dragging not working in iframe

### ISSUE THREAD

**Issue by wufeng87** [nwjs/nw.js#3277]
The same code below worked in top window, but not working in iframe.( can't drag )

  \<div style="-webkit-app-region:drag;width:200px;border:solid 1px red">1\</div>

nw.js v0.12.0
Chromium 41.0.2272.76

Best regards.

**Comment by wufeng87** [comment]
drag works when I config this in package.json

    "toolbar":false,
    "frame":false,

**Comment by Gimmeaphatbeat** [comment]
@wufeng87 Not sure why you've closed this issue? It doesn't work in iframe still.
