### ISSUE TITLE
How to get a no developer tools nw.js?

### ISSUE THREAD

**Issue by xuanhun** [nwjs/nw.js#3278]
By modifying the package.config file,any one can use developer tools and debug nw applications.
So, how to prevent this kind of behavior or where to get a no developer tools nw.js version?
Thanks!

**Comment by shaynem** [comment]
+1 should be able to use js to stop it.

However remote debugging flag you can't.

**Comment by rdtsc** [comment]
If your users are knowledgeable enough to find and poke around in your app's internals, there's going to be very little you can do to stop them. Even if there were NW binaries that shipped without DevTools, what's to stop your users from downloading a fresh (developer) copy and running your app through that?

In any event, if you *really* want to do this and are only interested in stopping the most basic forms of manipulation, you've got a few options:

#### 1) Custom Build
Build NW yourself and strip out all relevant DevTools functionality.

#### 2) JavaScript
Like @shaynem suggested, use JS to "block" DevTools from running by listening to the `devtools-opened` event and immediately calling `Window.closeDevTools()`:
```javascript
var win = require('nw.gui').Window;

win.on('devtools-opened', function() {
  win.closeDevTools();
});
```
#### 3) NW Binary Patching (Windows Example)
If you don't have the resources to get custom builds of NW going, you can patch the existing binaries to effectively neuter the inspector:
```python
#!/usr/bin/env python

# nwjs-v0.12.0-win-ia32
OFFSET = 0x25EB420

with open('nw.exe', 'r+b') as nwbin:
  nwbin.seek(OFFSET)
  if nwbin.read(14).decode('ascii') == 'inspector.html':
    nwbin.seek(OFFSET)
    nwbin.write(b' ')
```

Below is a demo of a combination of methods 2 and 3. Again, this is very weak protection.

![nw-devtools-demo](https://cloud.githubusercontent.com/assets/6773893/6782102/782dc684-d148-11e4-8203-d1d25307f567.gif)

**Comment by baconface** [comment]
It is impossible to stop the reverse engineering of a NW.js application without the developer assuming some responsibility in preventing it. You can always use a server side language like PHP or .Net and put your entire code base on a web server. Using ```node-remote``` to specify the server will allow it to execute node.js code on the client side. Your front end code still faces some risks of being exposed but your back end code and sensitive DB strings etc will be protected on your server. Your front end should have a build process that adds minification and obfuscation to it's code base that makes snooping or getting it in readable format a bigger chore. If possible for your project make your JavaScript a v8 snapshot which makes it machine code. Finally if you are doing Windows builds only you can use Enigma Virtual Box which will help prevent exposing it on another level. If you do this you eliminate most curious individuals/amateurs and it becomes a task for an experienced programmer/hacker.

**Comment by justinmchase** [comment]
It seems a little inconsistent to write your app in javascript then not want the devtools to be showable. I would just recommend not worrying about it :smile:

**Comment by xuanhun** [comment]
Thanks @rdtsc , what you said can solve my problems.
