### ISSUE TITLE
Please include prebuilt node-ffi in downloads for all platforms.

### ISSUE THREAD

**Issue by gogins** [nwjs/nw.js#3281]
No point in using NW.js for me unless my users can count on NW.js having the ability to use various bindings without my users having to compile node-ffi themselves.
##

**Comment by Jaredjin** [comment]
+1 
need it.

**Comment by wanjochan** [comment]
+1

**Comment by gogins** [comment]
csound.node currently is maintained only for Linux. A prebuilt release of csound.node, which depends on Csound being installed, is available at https://github.com/gogins/csound-extended/releases.
