### ISSUE TITLE
Support for find on page? (Ctrl+F) 

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3283]
I haven't found anything that currently points to the support of finding text on a page, similar to pressing Ctrl+F in Chrome, for instance. Is this on the road map? Or am I missing something and there is a way to enable this?

**Comment by VoidVolker** [comment]
Just use some libraries like: http://www.listjs.com/ or https://github.com/Extaze/fuzzy.js

**Comment by wotzisname** [comment]
@VoidVolker I don't think either of those really do what he's looking for. He's looking for highlighting of matching text in a page like pressing Ctrl+F in Chrome.

**Comment by VoidVolker** [comment]
Solution is `document.execCommand` - it works like standard search.

**Comment by benjismith** [comment]
@VoidVolker Can you elaborate on that? I'm familiar with `document.execCommand` for modifying the DOM of a `contentEditable`, but I don't know how I'd use it to rebuild Chrome's typeahead-find feature.

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by VoidVolker** [comment]
Sorry, correct is `find()` function. I use it for webview. Try to search in chrome API documentation.

**Comment by wotzisname** [comment]
find() isn't what I was talking about, but it may be possible with Rangy's highlighte module https://github.com/timdown/rangy/wiki/Highlighter-Module still it would be nice if this cam included.

**Comment by VoidVolker** [comment]
Use webview for webcontent. Start/continue searching:
```javascript
    webview.find('string to find', { backward: false, matchCase: false })
```
It works very good. To stop searching:
```javascript
    webview.stopFinding('clear')
```
It works very good.
