### ISSUE TITLE
[Linux] Directly render to framebuffer instead of window

### ISSUE THREAD

**Issue by PTS93** [nwjs/nw.js#3285]
I'm mainly interested in digital signage applications with nw.js and I was wondering if its possible to compile or run nw.js with specific flags so it renders its content directly to the framebuffer instead of a window.
My reason for that is that I can't use or sometimes even install a desktop environment on most of these setups for performance reasons.
##

**Comment by ags131** [comment]
My solution for this has been to install base xserver (No desktop environment or window manager)
Then a simple .xinitrc file and X will start right into nw.js. The only problem I've had is going fullscreen, I have to use the nw.gui window api to move and resize.

**Comment by PTS93** [comment]
The reason I want this is because I don't want to have an xserver installed, its unnecessary overhead that also needs correct configuring to work properly for kiosk applications.
