### ISSUE TITLE
[Windows] Notificaiton onclick not fireing

### ISSUE THREAD

**Issue by vexii** [nwjs/nw.js#3286]
tested on windows 7 32 bit
steps to reproduce:
    a = new Notification("foo");
    a.onclick = function(){ console.log("bar");    
the only thing happning is the notification closing

**Comment by composite** [comment]
same here.
windows 8.1 x64
nw.js 0.12.0 x86

**Comment by jtg-gg** [comment]
@vexii @composite I've just push the fix into master https://github.com/nwjs/nw.js/commit/92c35d3632696a0558be7fff52076c94970ee787

please help me to close the issue if you have verify the fix

**Comment by vexii** [comment]
i test it when i get home to my desktop

**Comment by broderix** [comment]
You should create Tray first. Notifications will be shown at Tray.
