### ISSUE TITLE
Mac: Resizing window to fullscreen from keyboard is broken

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#3287]
The window goes off the top of the screen (which is not supposed to be possible.)

![image](https://cloud.githubusercontent.com/assets/1427241/6804918/3f0dd84e-d238-11e4-9feb-0f460d240782.png)
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
