### ISSUE TITLE
osX nw build error

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3291]
hi

how can i fix this nw error please (@rogerwang)

[4402/4422] CXX obj/content/nw/src/nw_lib.nw_shell.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/content/nw/src/nw_lib.nw_shell.o.d -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=223108 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DBREAKPAD_IMPLEMENTATION -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DMOJO_USE_SYSTEM_IMPL -DLIBPEERCONNECTION_LIB=1 -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_LEGACY_DRAWPICTURECALLBACK -DSK_USE_POSIX_THREADS -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_MAC -DWEBRTC_POSIX -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DUSE_LIBPCI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -I../../v8 -I../../third_party -I../../third_party/WebKit/Source -I../../third_party/WebKit/public/web -I../../breakpad/src -Igen/blink -Igen/blink/bindings/core/v8/ -Igen/chrome -I../../third_party/khronos -I../../gpu -I../../skia/config -Igen/angle -Igen/components -I../../third_party/WebKit -Igen/content/app/resources/ -I../../third_party/skia/src/core -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/utils/mac -I../../skia/ext -I../../third_party/node/deps/uv/include -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -Igen/ui/resources -I../../v8/include -I../../third_party/libyuv/include -I../../third_party/libyuv -I../../third_party/webrtc/overrides -I../../third_party/zlib -I../../third_party/WebKit -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/libpng -I../../third_party/libwebp -I../../third_party/ots/include -I../../third_party/qcms/src -I../../third_party/iccjpeg -I../../third_party/libjpeg_turbo -Igen/extensions -Igen/components/strings -Igen/content -Igen/nw -I../../breakpad/src/client/apple/Framework -I../../third_party/google_toolbox_for_mac -I../../third_party/google_toolbox_for_mac/src -I../../third_party/google_toolbox_for_mac/src/AppKit -I../../third_party/google_toolbox_for_mac/src/DebugUtils -I../../third_party/google_toolbox_for_mac/src/Foundation -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -O2 -gdwarf-2 -fvisibility=hidden -Wnewline-eof -mmacosx-version-min=10.6 -arch x86_64 -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -std=c++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /Users/smo/Documents/nwjs/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -fcolor-diagnostics -fno-strict-aliasing  -c ../../content/nw/src/nw_shell.cc -o obj/content/nw/src/nw_lib.nw_shell.o
../../content/nw/src/nw_shell.cc:549:30: error: no member named 'to_string' in namespace 'std'
  SendEvent("progress", std::to_string(progress));
                        ~~~~~^
1 error generated.
[4402/4422] CXX obj/content/nw/src/nw_lib.shell_content_browser_client.o
ninja: build stopped: subcommand failed.


only problem in my build :/

thanks !

**Comment by justinmchase** [comment]
Can you format the error a little better with the code formatting? It's really hard to read like this.
https://guides.github.com/features/mastering-markdown

**Comment by smolleyes** [comment]
sorry, i know the markdown but was on hackintosh and problems ith the 
keyboard can t found the ` ... :p

i added a small function to fix this problem... build is complete now

**Comment by justinmchase** [comment]
Ok cool :smile: 

But for next time I believe you just wrap your text in three back-ticks: 

    ```
    my error message...
    ```

Which produces:
```
my error message...
```

**Comment by rogerwang** [comment]
I believe this commit fixed it?

https://github.com/nwjs/nw.js/commit/00dd9ed16bbc4bbee50f781b52f613790d9610bf

**Comment by smolleyes** [comment]
hello

will try as soon as possible roger :)

do you have an idear on this error  too when i build ffmpeg with ac3 
enabled on osX (only, ok with linux and windows ) i have

Undefined  symbols  for  architecture  i386:
   "_ff_eac3_apply_spectral_extension",  referenced  from:
       _decode_audio_block  in  ac3dec_float.o
   "_ff_eac3_decode_transform_coeffs_aht_ch",  referenced  from:
       _decode_transform_coeffs_ch  in  ac3dec_float.o

at the end of compile when generating the libavcodec.56.dylib

?

thanks
