### ISSUE TITLE
[Linux] Resource id not set for component_extension_resources.grd

### ISSUE THREAD

**Issue by wuyuehang** [nwjs/nw.js#3292]
After gclient sync with the latest codes,  the following codes in nw.gypi seems no work
```python
        {    
          'action_name': 'nw_components',
          'variables': {
            'grit_grd_file': 'src/resources/component_extension_resources.grd',
          },   
          'includes': [ '../../build/grit_action.gypi' ],
        } 
```
As digging into the destiney file "/node-webkit-src/src/tools/gritsettings/resource_ids", there are
only "nw_resources.grd" and "nw_strings.grd" get successful, but no any message relative with
"component_extension_resources.grd"...

```python
  "third_party/WebKit/public/blink_resources.grd": {
    "includes": [30500],
  },  
  "content/nw/src/resources/nw_resources.grd": {
    "includes": [57500],
    "structures": [58000],
    "messages": [59000],
  },  
  "content/nw/src/resources/nw_strings.grd": {
    "messages": [60000],
  }, 
```

**Comment by wuyuehang** [comment]
related issue but without any usefull clues https://github.com/nwjs/nw.js/issues/1808

**Comment by rogerwang** [comment]
https://github.com/nwjs/chromium.src/blob/nw12/tools/gritsettings/resource_ids#L253

**Comment by wuyuehang** [comment]
thanks @rogerwang . I used old chromium source tree for mistakes.
