### ISSUE TITLE
resizeTo doesn't work when using transparency and --disable-gpu --force-cpu-draw switches

### ISSUE THREAD

**Issue by edi9999** [nwjs/nw.js#3294]
I'm running nw@0.12.0 (commit f6c7f79-10b9c03-be948af-459755a-2bdc251-c114bb7)

The following code:
# index.html

```
<html>
    Main
    <script type="text/javascript">
        gui = require('nw.gui');
        W = gui.Window;

        config ={
            url:"subWindow.html",
            frame:false,
            width:200,
            height:200,
        }
        sub = W.open ("subWindow.html",config);
        sub.setTransparent(true)
        setTimeout(function () {
            console.log('resizing');
            sub.resizeTo(400,400);
            console.log(sub.width,sub.height);
        },1000)
    </script>
</html>
```
# subWindow.html

```
<html style="background-color:rgba(255,0,0,1)">
Sub
</html>
```
# package.json

```
{
  "name": "test-resizeTo-transparency",
  "version": "0.1.0",
  "dependencies": {
  },
  "main": "index.html",
  "window": {
  },
  "engines": {
    "node": ">=0.6"
  }
}
```

works correctly when running `nw .` , but it does not when running `nw . --disable-gpu --force-cpu-draw` , eg the subWindow is never resized:
# Runing `nw .`

![image](https://cloud.githubusercontent.com/assets/2071336/6820298/d3cf3938-d2cd-11e4-8b24-5a7832631a69.png)
# Running `nw . --disable-gpu --force-cpu-draw`

![image](https://cloud.githubusercontent.com/assets/2071336/6820306/f746938e-d2cd-11e4-858a-13d26f32be07.png)

Is they any reason why the switch makes the resizeTo not work ? 

Related to https://github.com/nwjs/nw.js/pull/2859
##

**Comment by dantheuber** [comment]
I'm seeing this happen as well. It appears that the window is resized, however nothing to the right of the original size is shown.. 

I can also see this odd behavior AFTER the app is loaded, by click-dragging the right side of the window, the window is resized to the size i drag to, but the actual window content is not shown beyond the original window size. It appears that dragging the left side of the window to resize fixes this issue.

Appears to be some issue with resizing while leaving the windows top left x/y the same?

**Comment by edi9999** [comment]
Yes probably, I still haven't solved this

**Comment by Christywl** [comment]
Some features have changed from v0.13.0, such as Window.open(), win.setTransparent(true).  Please refer to http://docs.nwjs.io. And I try with nwjs v0.23.7. It works fine with `--disable-gpu --force-cpu-draw`.

**Comment by Christywl** [comment]
close until there is more information.
