### ISSUE TITLE
taskbar hint( when mouse hover ) not showed in win8

### ISSUE THREAD

**Issue by wufeng87** [nwjs/nw.js#3300]
A friend had the same problem. the taskbar hint only show in mac. not works in win8.

nw.js v0.12.0
Chromium 41.0.2272.76

Best regards.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
