### ISSUE TITLE
[bug] css :hover not triggered when webview is focused

### ISSUE THREAD

**Issue by felicienfrancois** [nwjs/nw.js#3303]
### The problem

When a webview is focused, overring an element outside the webview does not "trigger" the css :hover selector, whereas javascript mouseover, mouseout and mousemove are well triggered.
### Snippet to reproduce:

``` html
<!DOCTYPE html>
<html>
<head>
    <style>
        html, body {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
        }
        #div, #webview {
            height: 90%;
            width: 50%;
            float: left;
        }
        #div {
            background: grey;
            font-size: 100px;
            color: white;
        }
        #div:hover {
            background: red;
        }
    </style>
</head>
<body>
    <div id="div" onmouseover="this.innerHTML = 'over'" onmouseout="this.innerHTML = 'out'"></div>
    <webview id="webview" src="https://google.com"></webview>
</body>
</html>
```
##

**Comment by felicienfrancois** [comment]
@rogerwang any idea of workaround ?
I tryed to blur the webview, focus the main window or trigger click on the main window using javascript but it does not work.

**Comment by bachel** [comment]
I am experiencing same issue on windows in 12.2. On mac it's fine.

**Comment by acicali** [comment]
I've experienced a similar issue, I believe it's the same bug. Moving the mouse between two elements that are using -webkit-app-region: (one with "drag", the other with "no-drag") does not honor the :hover state. Specifically, the "no-drag" item will keep its :hover state even after the mouse has moved off of it.

Reproduce with:
```html
<style>
#titlebar {
	float: left;
	width: 100%;
	line-height: 50px;
	background: #000;
	-webkit-app-region: drag;
}

.button {
	float: left;
	padding: 0 10px; 
	color: #FFF;
	-webkit-app-region: no-drag;
}

.button:hover {
	background: #444;
}
</style>
<div id='titlebar'>
	<div class='button'>Click me, but don't drag</div>
</div>
```

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.23.7. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.

**Comment by this-is-michael** [comment]
perfect - removing the app-region drag item solved the issue for me! Thank you!!
