### ISSUE TITLE
MacOSX - selenium fails creating a new session 

### ISSUE THREAD

**Issue by emlloyd** [nwjs/nw.js#3304]
After our app has been updated to use V0.12 our selenium tests no longer work, the following is seen when the selenium server attempts to start a session:
Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary

I have a workaround of renaming /node-webkit.app/Contents/MacOS/nwjs to /node-webkit.app/Contents/MacOS/node-webkit but I don't know what other side affects this could have?

I believe I have traced back the code to chrome/test/chromedriver/chrome/chrome_finder.cc in the chromium.src

Also created #37 against nwjs/chromium.src?
##

**Comment by Paxa** [comment]
For now you can override chrome binary path.
How you run chromedriver?

You can add
```js
chromeOptions: {
  binary: "/Applications/nwjs.app/Contents/MacOS/nwjs"
}
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
