### ISSUE TITLE
[Help] disable print preview

### ISSUE THREAD

**Issue by stove654** [nwjs/nw.js#3306]
hi all, thanks you team nw. i like app on window building with nw.this is awesome. I want to ask how to disable the print preview. I'm doing app can connect the printer and preview problems when using window.print (). I can do without the preview printing is not? if you wish the guide. thanks for looking at my question
- I have tried this way https://github.com/nwjs/nw.js/issues/3240 but is there any solution to print without a pdf file.

**Comment by rogerwang** [comment]
This is now supported. See #4911
