### ISSUE TITLE
Appended zip application fails to expand fully sometimes

### ISSUE THREAD

**Issue by nrydn** [nwjs/nw.js#3309]
Steps I take.
1) I zip the application folder.
2) I append the zipped file to the nw.exe with:
copy /b nw.exe+my.zip my.exe
3) I run my.exe

Every time I launch the application it creates a folder in %TEMP% that contains the extracted contents of my.zip. However problem is that sometimes the zip is not fully extracted hence application fails to run properly. Weird part is that it doesn't always happen. It happens around half of the time. It almost feels like there is a timeout and the app stops extracting once it hits it and other times sometimes it manages to fully extract and app works properly.

Zipped folder is about 11mb (and 33mb uncompressed).

Do you have any suggestions?

**Comment by VoidVolker** [comment]
Do not append this big zip to `nw.exe` and store app in `package.nw`

**Comment by nrydn** [comment]
Yes that's pretty much what I've been doing at the moment.
