### ISSUE TITLE
Cookie persistence delays

### ISSUE THREAD

**Issue by chennney** [nwjs/nw.js#3310]
I'm seeing an issue on v0.12.0 where cookie persistence will take around 30 seconds before saved to the cookies sqlite table. A good way to reproduce this is to create a new cookie via document.cookie, then quit the app after a few seconds.  If you wait around 20-30 seconds, the value will finally be persisted in the sqlite table (you can use a sqlite browser and continuously refresh the table data).  This is an issue because if a user logs out and you remove the cookie, when they relaunch the app, the user is still logged in.
##

**Comment by bachel** [comment]
Yes, I noticed same behavior with 0.12.1 on mac and windows.

**Comment by baconface** [comment]
Not saying this shouldn't be fixed but you can write code that helps prevent log out failures. I do it on every login system just to be sure I can nuke the session.

What I like to do is make a column that supports a unique alpha/numeric/symbol string in the user session/login table. When they log in generate this string and put a copy in your session cookie. Compare these two when you do any action against the server. When you log out send a request to destroy or change the copy in your database. Have a callback check if this action succeeded. If not log out failed and try again or alert the user. If succeeded the key is destroyed on the server side and if the client cookie fails to be deleted (like in this case) you will not be able to validate as logged in.

There are likely better solutions than this but this works for most cases.

**Comment by bachel** [comment]
This is fix to force cookies to save when app is closing.
```javascript
var gui = require("nw.gui")
var win = gui.Window.get();
win.on("close",function(){
    win.cookies.remove({url:"app://fake",name:Math.random()},function(e){})
})
```

**Comment by willian12345** [comment]
So, I roll back to 0.11.6 version, And seem to be all right

**Comment by leyanlo** [comment]
@bachel's hot-fix was helpful but didn't actually close the window for me. I needed to add `win.close(true);` or else the window would stay open:
```js
var gui = require("nw.gui");
var win = gui.Window.get();
win.on("close",function(){
    win.cookies.remove({url:"app://fake",name:Math.random()},function(){});
    win.close(true);
})
```

**Comment by leyanlo** [comment]
Actually, this leads to some crashes when closing the app quickly. A better hot-fix by @chennney is:

```js
var gui = require("nw.gui");
var win = gui.Window.get();
win.on('close', function() {
    var w = this;
    this.hide();
    this.cookies.remove({url: "app://fake", name: Math.random()}, function() {
        w.close(true);
    });
});
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
