### ISSUE TITLE
one click nw.exe,appears four nw.exe processes.

### ISSUE THREAD

**Issue by mustapha-wang** [nwjs/nw.js#3311]
mouse click on nw.exe,launched four nw.exe processes.wrong or design as?
windows 7 64bit
node-webkit 0.12.0
##

**Comment by justinmchase** [comment]
I believe it's by design.

**Comment by baconface** [comment]
Design. I believe because of different processes/treads for different things like your app, WebKit/blink, node.js/io.js, etc.

**Comment by mustapha-wang** [comment]
But,If i use a cloudTag control in html,three of four processes cpu loading are over 20%.

**Comment by Christywl** [comment]
Any problems for this? Could we close it?

**Comment by rogerwang** [comment]
close as it's intended under Chromium's multi-process architecture.
