### ISSUE TITLE
node webkit app-view permissions

### ISSUE THREAD

**Issue by xabies** [nwjs/nw.js#3314]
I have a backbone web app and everything works fine in my browser. Now I want to make a .exe with Node webkit.

This is my package.json file:

{
"name": "XXXX",
"main": "index.html",
"window": {
    "toolbar": true,
    "width": 800,
    "height": 600
},
"single-instance": false,
"version": "1alpha",
"private": true
}

but when I execute the program I obtain these message in the js console:
You do not have permission to use the appview element. Be sure to declare the 'appview' permission in your manifest file and use the --enable-app-view command line flag.

I've been trying to enable this pemission but I haven't found any way to do it?

Any idea? Thanks
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
