### ISSUE TITLE
undefined symbol: gtk_recent_info_get_gicon

### ISSUE THREAD

**Issue by wpp2014** [nwjs/nw.js#3315]
I wrote a 3rd party modules with C/C++ addons and I successfully compiled it。However，when I debug the program the main interface crashed。The reason is “symbol lookup error: /home/wpp/Desktop/webApp/build/Release/manager.node: undefined symbol: gtk_recent_info_get_gicon”
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by wpp2014** [comment]
This issue is resolved, thank you!
