### ISSUE TITLE
The KIOSK mode is not disabling the WINDOWS keyboard button

### ISSUE THREAD

**Issue by Miciurash** [nwjs/nw.js#3318]
When in the KIOSK mode users are still able to push WINDOWS keyboard button to get to the system menu. (on WINDOWS XP/7/8)
##

**Comment by VoidVolker** [comment]
Just replace shell to your programm and no problems with menu.
`HKEY_Current_User\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\Shell`
Details: https://msdn.microsoft.com/en-us/library/ms838576(v=winembedded.5).aspx
But user still can start task manager and then explorer. In this case, you need to replace and task manager too.
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\taskmgr.exe`

**Comment by Christywl** [comment]
@Miciurash , does VoidVolker's suggestion work for you?

**Comment by syedhassaanahmed** [comment]
I've [created a Kiosk demo](https://github.com/syedhassaanahmed/kiosk-demo-electron) which uses Shell Launcher to enable the app as custom shell. Check it out!

**Comment by Christywl** [comment]
close until there is more information
