### ISSUE TITLE
spell-check available?

### ISSUE THREAD

**Issue by pcarion** [nwjs/nw.js#332]
Hi,

Is it possible to enable the google spell-check which is available under chrome (using right click)?

Thank you

Pierre

**Comment by mihapirnat** [comment]
> I suppose it's not possible because spellcheck, while being a part of Google Chrome, has never made it to those parts of Chromium that node-webkit is based on.

My understanding is it is implemented in Chromium:
http://www.chromium.org/developers/how-tos/editing-the-spell-checking-dictionaries
http://hunspell.sourceforge.net/

**Comment by cristianfraser** [comment]
+1

**Comment by zulucoda** [comment]
+1
anyone got a solution for this? or we still waiting for feedback from @rogerwang ?

**Comment by rogerwang** [comment]
Will try to fix this in nw13.

**Comment by TheJaredWilcurt** [comment]
If you need something in your app prior to NW v13, there are several JavaScript based spellcheck libraries available that should tide you over.

Adds about 1MB to your project size:

* http://www.javascriptspellcheck.com

**Comment by rogerwang** [comment]
Release in 0.13.0-alpha1 with `--enable-spell-checking` switch: https://groups.google.com/d/msg/nwjs-general/c25l_jGMqj8/rsAtdSQuxeUJ

**Comment by adam-lynch** [comment]
@rogerwang will it always be behind this `--enable-spell-checking` switch or is that just for alpha builds?

**Comment by rogerwang** [comment]
@adam-lynch yes. It will always be like that unless other ways are proposed. 

The current implementation uses the same one inside Chromium browser. The feature is builtin so app developers don't have to write their own spell check providers. In the upcoming alpha releases there will be options to control the language support for the spell checker. 

In future releases we'll provide an API for writing your own spell checker provider. If anyone need this before that please open a new issue.

**Comment by adam-lynch** [comment]
@rogerwang thanks for that. I'm not sure how I'd pass that flag when I give an end user my `.exe` / `.app`. Maybe it could also be a property in the JSON manifest?


I'm assuming that if I were to put it in `chromium-args` with the current alpha build it wouldn't work because [`chromium-args`](https://github.com/nwjs/nw.js/wiki/Manifest-format#chromium-args) is for Chromium stuff only.

**Comment by rogerwang** [comment]
@adam-lynch it should work with `chromium-args`

**Comment by adam-lynch** [comment]
@rogerwang Great thanks! :+1:

**Comment by S-ed** [comment]
How to define dictionary file?
Afaik there is a Chromium API function to do so.
Would be nice to have an ability to switch them on the go.

**Comment by laduran** [comment]
Does anyone know whether or not in the 0.13 beta 5 if the spell check dictionary can be either extended or replaced? I want a medical dictionary. Yes, I know javascriptspellcheck has this, I looked at that already and it has a server dependency that I don't think we can use for our packaged app (unless someone can tell me how to add PHP support to the node server that webkit uses).

**Comment by TheJaredWilcurt** [comment]
@laduran 

* **[Typo.js](https://github.com/cfinke/Typo.js)**

That one doesn't require any PHP nonsense. I had no idea that "JavaScript Spellchecker" was a Scooby Doo villain. Once I pull off its mask it turns it it was "PHP Spellchecker" all along. He would have gotten away with it to if it wasn't for your meddling, laduran!

**Comment by laduran** [comment]
@TheJaredWilcurt 

Ha! I was looking at Typo.js as you wrote that. Yeah, just a client side Javascript library. Seems super barebones though. Very low level. I have to write all the UI pieces myself. For example, squiggly underline misspelled words, context menu to show suggested corrections, etc. It may as well be assembly language. :-)

**Comment by laduran** [comment]
By the way, my ideal solution would still be to update to NWJS v0.13 and use built in spell correction. In addition, it would be nice to be able to replace the built-in dictionary with a Hunspell compatible medical dictionary. For example: [Hunspell Medical Dictionary](https://github.com/Glutanimate/hunspell-en-med-glut)

**Comment by JohnCPayne** [comment]
Two simple, I hope, questions. Is spell check implemented/available for v0.13.1?  If yes, how do i enable it?  Keep any discussion of enabling simple, I'm an end user not a programmer.

Thanks
John

**Comment by laduran** [comment]
Honestly, we switched from NWJS to Electron mostly because of the poor spell check support in NWJS. We could never get it working per user expectations in NWJS and just getting it working poorly took more work than necessary. Have a look at Electron.

**Comment by rogerwang** [comment]
The dictionary can be customized in the same way as in Google Chrome, see https://www.quora.com/Is-there-a-way-to-remove-a-word-from-Chromes-spell-check-dictionary

**Comment by rogerwang** [comment]
btw, In 0.13 we changed to an optimized architecture so more features can be supported beyond spell checking, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

**Comment by GaragusoPD** [comment]
In case anybody finds this useful, you can enable spell check with `"chromium-args":"--enable-spell-checking"` in package.json

**Comment by thedrean** [comment]
Is there a way to use "chromium-args":"--enable-spell-checking", but only have the spellcheck active in textareas that use spellcheck="true"?

**Comment by bluthen** [comment]
Set spellcheck=false for the textfields and input you don't want it enabled on? You should be able to use javascript to find the ones that don't have it set to true already and set false on them.
