### ISSUE TITLE
"Download" attribute in combination with HTTP AUTH results in crash

### ISSUE THREAD

**Issue by joshuajung** [nwjs/nw.js#3322]
Consider the following simple index.html:

``` html
<html>
  <body>
    <a href="https://aqsas.de/neo/test.pdf" download="MyFile.pdf">Download</a>
  </body>
</html>
```

**Intended behaviour**: present a login prompt and then the download dialog with proposed filename "MyFile.pdf".

**Observed behaviour**: nw.js v0.12.0 _crashes_ on both Win32 and Mac when clicking the link, _if the link points at a URL protected by HTTP AUTH_ (such as the example URL above).

**Remarks**: The link works fine as soon as I (1) remove the download attribute, (2) point to a non-protected file,  (3) use nw.js v0.8.6, or (4) use a browser instead of nw.js.

I'm sticking to v0.8.6 for the moment, but would like to update soon and enjoy this bug to be fixed.
##

**Comment by Christywl** [comment]
No crash happens on nwjs v0.23.7. No login prompt, but a download dialog opens when clicking the link.

**Comment by Christywl** [comment]
close until there is more information.
