### ISSUE TITLE
'Make' method to build from linux seems to be deprecated... Update Wiki

### ISSUE THREAD

**Issue by shyne99** [nwjs/nw.js#3323]
Hello,

Apparently, it's no more possible de build nw using make....

Ligne 272 of gyp_chromium seems to block the command, for reference:

```
    if re.search(r'(^|,|\s)make($|,|\s)', os.environ.get('GYP_GENERATORS', '')):
        print 'Error: make gyp generator not supported (check GYP_GENERATORS).'
        sys.exit(1)
```

As it is mentionned to use make in the wiki, maybe an update have to be done. (And I don't know how to build it without make...)
##

**Comment by Christywl** [comment]
Please refer to http://docs.nwjs.io.

**Comment by Christywl** [comment]
close until there is more information.
