### ISSUE TITLE
nwjs crashes once memory reaches 175MB (0.12.0-RC1 - OS X Yosemite)

### ISSUE THREAD

**Issue by transaction** [nwjs/nw.js#3324]
I'm unit testing an angular based nwjs app, meaning a lot of reloading/initializing stuff in the same session. Somewhere in my code is a leak so memory increases, however it's low priority since we have no production issues.

Once the total memory (including the nwjs helpers) reaches 175MB it crashes but I can't get a crashdump.

Any advice or a workaround? Forcing gc isn't possible in Chrome I think so that's not an option.

Edit, seems to be a context/JS specific issue. If I load dev tools and snapshot the heap, memory increases with about 250MB and nothing happens. When I manually rerun a single unit test however it crashes. If I run too many tests in the same session the crash also happens.
##

**Comment by bestplay** [comment]
Did you used snapshot to protect js code?

Maybe,you can update nwjs to 12.0. And use nwjs

**Comment by bestplay** [comment]
I mean nwjc

**Comment by transaction** [comment]
@bestplay Yes I snapshot before testing (quite alot of code too). Totally missed the 0.12.0 release, thanks, I'll see if that helps.

If all else fails I'll try it on Windows 8 to see what happens there.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
