### ISSUE TITLE
Trying to manipulate font-size through keybind + mouse event

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3331]
I'm trying to simulate what ctrl+mouse scroll does in browsers to my webkit container. I've got the key bound to alt+mouse scroll. Here is a fiddle showing what I've got working: http://jsfiddle.net/ceghdzxp/

And here is my code:
```
$('#wrapper').bind('mousewheel DOMMouseScroll',function(e){
    // determines direction of scroll
    var delta = e.originalEvent.wheelDelta || -e.originalEvent.detail; 
    var curSize = parseInt($(this).css('font-size'),10);
    console.log(e);
    if (e.altKey === true ) {
        if(delta>0) {
            curSize += 1;
        } else {
            curSize -= 1;
        }
        $(this).css({"font-size" : curSize+"px"});
    }
});
```

For some reason it doesn't even log out that I'm scrolling in webkit at all. What could be causing this?

**Comment by jaguarsy** [comment]
it works well in nwjs-v0.12.0, maybe there is something wrong with the other code?

**Comment by joshuaterrill** [comment]
I'm not on that late of a version of nodewebkit, unfortunately. I'm using 0.8.6 and due to some restrictions in applets I'm using within my app, that's the version that I'm stuck with for the time being.

**Comment by rdtsc** [comment]
FWIW, your snippet works without issue (albeit with perceivable lag) on the win32 build of v0.8.6:

![0.8.6 Win32 Scroll Wheel Demo](https://cloud.githubusercontent.com/assets/6773893/6985056/f45c5bdc-d9fc-11e4-9867-4b5f78000912.gif)

---

#### index.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NW Scroll Wheel Test</title>
    <style>
      html, body {height: 100%}
      body {margin: 0}
    </style>
  </head>
  <body id="wrapper">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>
      $(function() {
          $('#wrapper').bind('mousewheel DOMMouseScroll',function(e){
              // determines direction of scroll
              var delta = e.originalEvent.wheelDelta || -e.originalEvent.detail;
              var curSize = parseInt($(this).css('font-size'),10);
              console.log(e);
              if (e.altKey === true ) {
                  if(delta>0) {
                      curSize += 1;
                  } else {
                      curSize -= 1;
                  }
                  $(this).css({"font-size" : curSize+"px"});
              }
          });
      });
    </script>
  </body>
</html>
```

**Comment by joshuaterrill** [comment]
That's interesting. There must be something wrong with some other piece of code somewhere in my app. Going to look into it and report back.
