### ISSUE TITLE
how to get error info  when resource file not found in code?

### ISSUE THREAD

**Issue by gy190** [nwjs/nw.js#3332]
example: chrome console appear "net::ERR_FILE_NOT_FOUND"

**Comment by VoidVolker** [comment]
var urlsFilter = { urls: ["<all_urls>"] };
    chrome.webRequest.onErrorOccurred.addListener(function(details){
        console.log('Network error: ', details);
    }, urlsFilter );

But, be don't reload page after listener is added: https://github.com/nwjs/nw.js/issues/3334
