### ISSUE TITLE
chrome.webRequest.onBeforeRequest.addListener reload crash

### ISSUE THREAD

**Issue by VoidVolker** [nwjs/nw.js#3334]
_Windows 7 x64, nwjs x64 (x86 not tested)_

**Variant 1**

Code:

```
chrome.webRequest.onBeforeRequest.addListener( function(details){
        console.log( 'beforeRequest; details: ', details);
        return { cancel: false };
    }
    , {urls: ["<all_urls>"]}
);
```
1. Launch `nwjs.exe`
2. Open Developer Tools
3. Insert code
4. Press `Reload` button
5. Isert code again.
6. Crash.

**Variant 2**

Create file `index.html` with this code:

```
<!DOCTYPE html><html><head>
    <meta charset="UTF-8">
</head>
<body>
<script type="text/javascript">

    chrome.webRequest.onBeforeRequest.addListener( function(details){
            console.log( 'beforeRequest; details: ', details.url );
            return { cancel: false };
        }
        , {urls: ["<all_urls>"]}
    );
</script>
</body>
</html>
```
1. Open this file in `nwjs.exe`.
2. Reload page.
3. Crash.
##

**Comment by VoidVolker** [comment]
`chrome.webRequest.onErrorOccurred` - same error

**Comment by allanguys** [comment]
i have this error too,are you fixed it?

**Comment by VoidVolker** [comment]
Nop, looks like it is some kind error of chrome API integration. I tryed chek listeners before add new — but there are no listeners. This API can be used only if not reload the page. Need to wait when it be fixed.
Here is very many issues and important bugs can be lost here. 
Lets try to call @rogerwang . Roger, did you see this bug? Can you give some comments in this topic, please?

**Comment by Jackcu** [comment]
+1111111

**Comment by tinybug** [comment]
I can't use this either, is there anybody can handle this problem?

**Comment by joelz** [comment]
I can't use this either, is there anybody can handle this problem?

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.23.6. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
