### ISSUE TITLE
Terminal mode

### ISSUE THREAD

**Issue by monolithed** [nwjs/nw.js#3335]
I'd like to run my tests without any GUI like PhantomJS.
Is there any way to implement the invisible/background/terminal mode?

![1428098513254](https://cloud.githubusercontent.com/assets/803674/6989646/d127e7d4-da66-11e4-9ea1-cf69c1198cae.png)

**Comment by bhaveshgohel** [comment]
The discussion is going on for the headless version of nwjs, Keep an eye on issue #769 for update.

**Comment by monolithed** [comment]
Oh, thanks

**Comment by bhaveshgohel** [comment]
Still there is One way is to to hide the window at app start using "show":false in Manifest and use win.show() when you want to show the window. This work done but its still not like terminal mode/headless version like phantomjs you're expecting.

Hope it helps. :)
