### ISSUE TITLE
Notification.requestPermission() not working?

### ISSUE THREAD

**Issue by ralucas** [nwjs/nw.js#3341]
I'm trying to call:
```
Notification.requestPermission(function(status) {
  console.log('status: ', status);
});
```
There is no prompt like that in Chrome.  The function is there and the result is always `granted`.  Is the prompt not enabled in node-webkit?  Thanks.

Richard

**Comment by rogerwang** [comment]
Hello,

You can use our notification API in NW without requesting permission first because it's a native application.

However we will fix support for this (permission) API in nw13.

Thanks,

Roger

**Comment by ralucas** [comment]
Makes sense :)  Thanks, Roger.

Cheers!

Richard

**Comment by martinsuchan** [comment]
@rogerwang Hi, is there a way now to capture the call for requestPermission in our app and ask user for confirmation, instead of automatically giving permission?
