### ISSUE TITLE
Create new window with no toolbar

### ISSUE THREAD

**Issue by kevkha** [nwjs/nw.js#3344]
My main window is set <code>"toolbar": false</code> and works fine.
Within the main window I create a new window without toolbar like below but not working. Is it possible?

<pre>
// Create a new window and get it
var new_win = gui.Window.open('new.html', {
  position: 'center',
  toolbar: 'false'
});
</pre>

**Comment by VoidVolker** [comment]
Property `toolbar` require boolean, not string:

    var new_win = gui.Window.open('new.html', {
        position: 'center',
        toolbar: false
    });

**Comment by kevkha** [comment]
Thanks VoidVolker! That worked.
