### ISSUE TITLE
Menulet icon (tray icon) does not support cmd+drag in OS X 

### ISSUE THREAD

**Issue by kethinov** [nwjs/nw.js#3347]
Actual:

1. Build app with a menulet icon (tray icon) in OS X.
2. Attempt to rearrange its position with cmd+drag.
3. It triggers the tray menu.

Expected:

It should allow repositioning the icon rather than triggering the tray menu.

**Comment by MarcFowler** [comment]
I'm not able to move *any* tray icon on OSX (Yosemite). Are you 100% sure it's a nwjs issue?

**Comment by kethinov** [comment]
Menumeters does it, as do most built-in Apple menulets like time machine, bluetooth, wifi, sound, date, battery, etc.

**Comment by kethinov** [comment]
Although I do agree it seems rare for third party apps. Most of mine (aside from Menumeters) do not have this feature.

**Comment by brian-mann** [comment]
I would also like this feature.

**Comment by tommoor** [comment]
None of my (many) tray apps offer this functionality, not that I think it's a bad idea. Feels like this should be implemented at the OS level!

**Comment by ePirat** [comment]
This is not a bug, as there is no public API that supports this. Only OS menubar items (like clock or battery) support this using special private API.

**Comment by kethinov** [comment]
@ePirat interesting! Good to know. I'll close this issue then.

Seems like it would still be possible to implement the feature via an unsupported third party plugin/extension for NW.js, but I definitely agree that the App Store complications mean it should not be part of the main project.

**Comment by MarcFowler** [comment]
Sorry, I hate to reopen but are you 100% sure that's right? I personally don't know ObjC but our company had an app created which accepts files to be dropped onto a tray menu, in fact we've done it twice. Neither of these are in the App Store but I'm not aware of any private API being used to do it.

The two answers to this question seem to indicate that it is possible? http://stackoverflow.com/questions/5663887/drag-and-drop-with-nsstatusitem/6493240

**Comment by ePirat** [comment]
This bug is not about file drag and drop but about moving the menu item around by holding cmd and dragging it around.

**Comment by MarcFowler** [comment]
Whoops! You're right; a thousand apologies!

**Comment by kethinov** [comment]
I updated [the wiki](https://github.com/nwjs/nw.js/wiki/Tray) to reflect this conversation.
