### ISSUE TITLE
HTTP Requests using HTTP module not working

### ISSUE THREAD

**Issue by KyleRoss** [nwjs/nw.js#3348]
**Version:** nw.js v0.12.0
**Commit Hash:** `f6c7f79-10b9c03-be948af-459755a-2bdc251-c114bb7`
**Platform:** Windows 7 64-bit

With the latest version of NW, I am unable to make HTTP requests using the `http` module or using the `request` module. I opened a fresh instance of NW and in the dev tools tried to make a request and a response is never returned. See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/2508347/7032750/d2b63338-dd42-11e4-9362-7350173c937a.png)

You can try this by running this example:

    http = require('http');
    req = http.get({host: "google.com", port: 80, path: "/"}, function(res) {
        console.log("Response:", res);
    });

I am behind a corporate firewall, although I've never had this issue with previous versions of NW, including a couple of the alpha builds of 0.12. Unless something drastic changed that I'm unaware of, this should be working.

**Comment by VoidVolker** [comment]
![nwhttp](https://cloud.githubusercontent.com/assets/5086438/7062717/b0726686-dea8-11e4-850e-750b6a91df7f.jpg)

**Comment by KyleRoss** [comment]
@VoidVolker - Thanks for testing this. I'm now curious what has changed from the earlier alpha versions (and older versions of NW) that is causing this. Does anyone know if there any type of proxy settings that would need to be set? I just find it odd that making remote JSON requests through jQuery and loading the entire app from a domain outside of our firewall (using node-remote) works perfectly fine, but then any requests made using Node fail to run.

If anyone has any insight on this, it would be gratefully appreciated!

**Comment by VoidVolker** [comment]
Did you test this code in early versions? I think this is your's internet connection problems.

**Comment by KyleRoss** [comment]
Just ran some tests and the issues persist in the older versions also. It must have been due to loading resources from within the firewall previously and now it's loading them externally. I will close this issue since it's an issue directly with our network and not NW. Although I'd still like to figure out how to connect through the firewall eventually using the `http` module.
