### ISSUE TITLE
nwjs helper 100% cpu and use lot of memory osX

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3349]
hi 

problem on osX (10.9.5)  just compiled tonight 

35592  nwjs Helper  cpu = 127.9     27:10.39 22/2 1    187   2170  memory used = 646M

reading a simple video...

thanks

**Comment by rogerwang** [comment]
could you please give an example so I can reproduce it here? Thanks.

**Comment by smolleyes** [comment]
hi roger

nothing special just add a <video> tag and play a video ...

**Comment by AndryBray** [comment]
do you have any CSS animation / GIF images?
If you have one of these, remove it and test it again...

**Comment by smolleyes** [comment]
will make more tests then report if confirmed

on linux i see only one process for my app on osX in have 4 nwjs helper and only one is 100 % maybe normal... 

i don t have any css3 animation  no (or not when the "problem" occur)

thx
