### ISSUE TITLE
Sandbox entire new window instance with whitelist API

### ISSUE THREAD

**Issue by pocesar** [nwjs/nw.js#3353]
Whats the best approach to do this? Suppose I want to execute external untrusted code inside NW.js, so it can actually build the UI for me, but in a controlled environment inside my own NW.js that launches this sandboxed version of NW.js. 
Basically I want to "catch" calls for the fs, path modules when they are executed inside the sandboxed instance, and replace their contents if they are in my whitelist of allowed functions, but the main application should still work with fs and path like it normally would. 
Something like https://github.com/bcoe/sandcastle, since it uses spawn to create a subprocess and execute the code, it wouldn't work with NW.js, but the concept is similar
##

**Comment by matthew-dean** [comment]
I was looking at the same problem a while back. You may have to end up monkey-patching those modules, the way that graceful-fs. But of course, if any modules are using graceful-fs... not sure. I haven't yet found a solution to intercept fs and path calls.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?
