### ISSUE TITLE
Read the code of nw.js

### ISSUE THREAD

**Issue by songxiaoyuan** [nwjs/nw.js#3356]
I have a question when read the code of nw.js. when I read the  message_pump_uv.cc, it has a function Run(Delegate* delegate), it  has the some lines:
 // call tick callback after done work in V8,
// in the same way node upstream handle this in MakeCallBack,
// or the tick callback is blocked in some cases
    if (node::g_env) {
        v8::HandleScope handleScope(isolate);
        node::CallTickCallback(node::g_env, v8::Undefined(isolate));
      }
I don't understant it, can you explain it to me.

**Comment by songxiaoyuan** [comment]
@rogerwang

**Comment by rogerwang** [comment]
The comment explains it well. What's your question? And please ask questions in our mailing list.
