### ISSUE TITLE
Can't hide cursor with "kiosk": true (v0.12.0, Mac)

### ISSUE THREAD

**Issue by cylinderStudio** [nwjs/nw.js#3358]
I've tried calling `document.body.style.cursor = 'none'` from JavaScript and using `cursor: none` in CSS. Cursor is still always visible.
##

**Comment by shaynem** [comment]
Possible its not supported on body tag. Tried wrapping everything in a div
and doing it on that ?

**Comment by cylinderStudio** [comment]
Yep, tried that. No luck. I tried it on several individual div elements, wrappers, etc.

**Comment by cylinderStudio** [comment]
Apparently it only happens when using "kiosk": true in the manifest. As a workaround I have to achieve a kind of kiosk mode by just leaving off the menu and frame, fixing with width and height to that of my display, setting "always-on-top": true, etc.

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.23.6.

**Comment by Christywl** [comment]
close until there is more information.
