### ISSUE TITLE
'require is not defined'

### ISSUE THREAD

**Issue by xzh-loop** [nwjs/nw.js#3359]
package.json: "main": "htttp://localhost"

The html file is loaded from the server.  `require('nw.gui')` cause an error `'require is not defined'`.

However, this error would not appear when this html file is loaded from local directory.

**Comment by makerimages** [comment]
Sounds like a case of #199 ?

**Comment by rdtsc** [comment]
I think it's just a case of not having specified a [`node-remote`](https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote) key in your [manifest](https://github.com/nwjs/nw.js/wiki/Manifest-format). For example:

#### package.json
```json
{
  "name": "your-nwjs-app",
  "main": "http://localhost/",
  "node-remote": "localhost"
}
```
:warning: **DANGER**: This grants sources matching the specified `node-remote` pattern node-level execution privileges. You should be as specific as possible when constructing such patterns.

**Comment by xzh-loop** [comment]
@rdtsc , many thanks for your help! I just try and succeed. close #3359

**Comment by xzh-loop** [comment]
close #3359
