### ISSUE TITLE
Package.json window.min_width not working

### ISSUE THREAD

**Issue by xingped** [nwjs/nw.js#3365]
It appears that the min_width attribute of window in package.json does not prevent the window from going below that minimum width when the user resizes the window. max_width works as expected.
##

**Comment by VoidVolker** [comment]
It works. Where the code?

**Comment by xingped** [comment]
This is my package.json file:

'''
{
	"name": "MyApp",
	"main": "index.html",
	"version": "0.8.0",
	"window": {
		"toolbar": true,
		"width": 500,
		"height": 320,
		"max_width": 500,
		"min_width": 450
	}
}
'''

**Comment by VoidVolker** [comment]
OS?

**Comment by xingped** [comment]
Linux Mint 17.1, sorry.

**Comment by ToadKing** [comment]
Are you using a high-DPI monitor? I have a similar issue on Windows with high-DPI screens (#2878)

**Comment by OlsonDev** [comment]
I also have this issue. High DPI, yes.

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.23.5.

**Comment by Christywl** [comment]
close until there is more information.
