### ISSUE TITLE
12.1 no update of io.js or Chromium?

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3366]
So glad to see this project active and being developed, you're doing a great job.

Just one question: Why no use the lastest version of io.js and Chromium in this one? Especially io.js has made a lot of updates already.

**Comment by rogerwang** [comment]
We'd like to keep them updated in 0.12.x releases. We released 0.12.1 before that because there was emergency bug fix which need to be released early.

**Comment by chino23** [comment]
Ok, good to know. Thanks for the clarification Roger!

**Comment by rogerwang** [comment]
btw, currently we're actively developing the first NW13 alpha release. After that we'll update 0.12.

See https://groups.google.com/d/msg/nwjs-general/A7VpwOztU_s/Tg1L6nS2RBsJ

**Comment by chino23** [comment]
Great! Love to see this project in so active development and plans for the future!
