### ISSUE TITLE
app run fixed path?

### ISSUE THREAD

**Issue by fifsky** [nwjs/nw.js#3368]
Web2Executable create package

first run path in:
file:///C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/nw5264_24825/client.html
second run path in：
file:///C:/DOCUME~1/ADMINI~1/LOCALS~1/Temp/nw5220_8179/client.html

I want to specify a fixed path？

package.json
```json
{
    "nodejs": true, 
    "additional_trust_anchors": "", 
    "inject-js-end": "", 
    "node-remote": "", 
    "user-agent": "%name %ver %nwver %webkit_ver %osinfo", 
    "window": {
        "show": true, 
        "always-on-top": false, 
        "frame": true, 
        "focus": true, 
        "height": 600, 
        "visible": true, 
        "as_desktop": true, 
        "min_width": 800, 
        "fullscreen": false, 
        "title": "Verystar POS", 
        "mac_icon": "logo.icns", 
        "exe_icon": "logo.png", 
        "width": 800, 
        "resizable": true, 
        "kiosk": false, 
        "min_height": 500, 
        "show_in_taskbar": true, 
        "transparent": false, 
        "toolbar": true, 
        "icon": "logo.png", 
        "kiosk_emulation": false, 
        "position": "center"
    }, 
    "version": "1.0.0", 
    "inject-js-start": "", 
    "main": "index.html", 
    "node-main": "", 
    "description": "demo", 
    "webkit": {
        "page-cache": false, 
        "java": false, 
        "plugin": false
    }, 
    "js-flags": "", 
    "name": "demo-pos", 
    "single-instance": true, 
    "snapshot": "", 
    "chromium-args": ""
}
```

**Comment by baconface** [comment]
I advise against using fixed paths and using something like ```process.cwd()``` if you can. This removes the dependency of an exact path. Access to a specific path won't be guaranteed especially when using temp directories.

Additionally you can put your project directory in a folder with your executable. And call it by making ```main``` be ```../project/index.html```. That is if you absolutely need to know your path. Otherwise getting it from the process object like described above is your safest bet.

**Comment by inkhsutesou** [comment]
@baconface Agreed.  Also, it may interfere when using this for Linux or OSX since they may not have those exact paths.  Users may not appreciate if you create these folders either.

**Comment by fifsky** [comment]
@baconface @inkhsutesou  Thanks a lot for your help. :)
