### ISSUE TITLE
Bad path resolution when packaged for windows v0.12.1

### ISSUE THREAD

**Issue by aaerox** [nwjs/nw.js#3369]
I'm using the serialport package which contains a native module. When trying to import it as a module it throws the following error: 

`Uncaught Error: error: 126C:\Users\JON~1.DAL\AppData\Local\Temp\nw54264_14028\node_modules\serialport\build\serialport\v1.6.3\Release\node-webkit-v43-win32-ia32\serialport.node`

This error only seems to occur when I run the app using the packaged node-webkit-builder executable. When run directly from this same location with the unpackaged nw.js it executes with no errors.

I can't think of a reason why packaging it would make a difference when it's running from the same location. Any ideas?

Cheers
##

**Comment by bzuillsmith** [comment]
I also have this issue and it is not specific to node-webkit-builder. Runs fine as long as I don't combine the ```nw.exe``` and ```package.nw```. When combined, I get the following error in the console.
```
The specified module could not be found.
C:\Users\Ben\AppData\Local\Temp\nw9404_24027\node_modules\cataloger\node_modules\odbc\build\Release\odbc_bindings.node
```
I checked the temp directory, and the file is definitely there. Tried running as Administrator just to be sure it was not a permissions issue and it still did not work.

**Comment by inoc603** [comment]
Getting the same error here.

After some searching I found this in the [Using-Node-modules](https://github.com/nwjs/nw.js/wiki/Using-Node-modules) document:

>  Important note 1:   on Windows the engine's executable file must have the name nw.exe for addons to work (i.e. you cannot rename nw.exe if you need any addon-containing modules). They use parts of the engine to sustain their execution.

Renaming your built .exe file to `nw.exe` will get things working, and you can create a shortcut to it with the name you want.

I don't know the details, but it seems at the moment we can only stick to this workaround.

**Comment by rDr4g0n** [comment]
@inoc603 Thanks for posting about this. It saved me more windows related frustration.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
