### ISSUE TITLE
Help, I cant find mp4-capable ffmpegsumo for 0.8.6 for linux platforms

### ISSUE THREAD

**Issue by mitselek** [nwjs/nw.js#3375]

**Comment by RainbowDashDC** [comment]
Build it yourself? Would solve the issue.

**Comment by mitselek** [comment]
Thnx, I'll try.

**Comment by ghostoy** [comment]
0.8 is no longer supported. See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for latest instructions for NW.js 0.13.0 or later.
