### ISSUE TITLE
Set window class-name attribute for X11

### ISSUE THREAD

**Issue by nisargjhaveri** [nwjs/nw.js#3378]
Is there any way by which the class-name can be set of windows? Currently it shows blank value as class-name.

If not, it would be nice if we give an option for this.

Related to http://stackoverflow.com/questions/29219998/how-to-set-window-class-in-nw-js
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
