### ISSUE TITLE
Win / Transparency - lets clicks through when resized to a bigger window

### ISSUE THREAD

**Issue by Ivshti** [nwjs/nw.js#3379]
Hello, I encountered a strange and very critical bug with transparency on Windows in NW 0.12.

Steps to reproduce
1. Blank app in NW.js 0.12, with a semi-transparent background on the html element (`background-color: rgba(0,0,0,0.1)`)
2. set `resizable: true` in package.json
3. Start the app, resize the window
4. The area which was not a part of the window's original size lets click's through - doesn't capture clicks at all, they directly go to whatever is below that area; essentially makes the app unusable

**Warning: seems to happen randomly. Will investigate cause.**

@jtg-gg do you have any ideas? Could this be related to click-through functionality?

**NOTICE** I did find what causes the issue in the first place. It's a missing d3dcompiler_47.dll. So I'm guessing this issue happens **only in non-hardware accelerated mode**.

**Comment by jtg-gg** [comment]
@Ivshti so did you enable the click through from command line ?
i.e. disable the the gpu, and force cpu draw ?

if you never use those command line, click through should never happen

and btw have you solved it ? with the d3d dll ?

**Comment by Ivshti** [comment]
@jtg-gg I am not using any command line switches. And yes, it was solved by the addition of the d3d compiler dll. 

When I ran the app without it (due to a freak bug where unrar was not extracting the d3d dll from the archive), the bug appears. But transparency runs fine otherwise.
