### ISSUE TITLE
"Remote debugging has been terminated with reason: websocket_closed"

### ISSUE THREAD

**Issue by adriancooney** [nwjs/nw.js#3380]
For some reason, the Dev Tools just tanks whenever I include source maps in my JS file. When the source maps are included the file size jumps from ~700kb to 2.1mb and this happens when I open Dev Tools. The application works fine however. Any ideas?

![screen shot 2015-04-16 at 17 58 24](https://cloud.githubusercontent.com/assets/621110/7186569/a361501e-e462-11e4-8448-cd3be0c89297.png)

Update:
In Chrome (this might not even be relevant but anyway), the source maps work fine. I'd say it's probably the sheer size of the map is somehow overloading it. For some reason, browserify is packing the `node_modules` directory.
##

**Comment by allenm** [comment]
I have seen this error today , no idea yet .

**Comment by adam-lynch** [comment]
See #2738

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
