### ISSUE TITLE
So large, 1.6 GB binary after build with WIKI instructions

### ISSUE THREAD

**Issue by imShara** [nwjs/nw.js#3383]
Here is my build script:

```bash
#!/bin/bash

# Getting main version of node-webkit
cat <<EOF > .gclient
solutions = [
   { "name"        : "src",
     "url"         : "https://github.com/nwjs/chromium.src.git@origin/nw12",
     "deps_file"   : "DEPS",
     "managed"     : True,
     "custom_deps" : {
       "src/third_party/WebKit/LayoutTests": None,
       "src/chrome_frame/tools/test/reference_build/chrome": None,
       "src/chrome_frame/tools/test/reference_build/chrome_win": None,
       "src/chrome/tools/test/reference_build/chrome": None,
       "src/chrome/tools/test/reference_build/chrome_linux": None,
       "src/chrome/tools/test/reference_build/chrome_mac": None,
       "src/chrome/tools/test/reference_build/chrome_win": None,
     },
     "safesync_url": "",
   },
]
EOF

# Syncing code
gclient sync --no-history

# Build
cd src
export GYP_GENERATORS='ninja'
./build/gyp_chromium content/content.gyp
ninja -C out/Release nw -j4

# Done
echo "Done!"
```

I think binary is so large because includes all static libraries. How to build with shared libraries when env variable ignored? Do i need to modificate `content/content.gyp` file?

**Comment by smolleyes** [comment]
hi

add -D linux_dump_symbols=0 to the gyp_chromium command

> ./build/gyp_chromium -D linux_dump_symbols=0 content/content.gyp

or just run 

> strip nw 

after build ...

++

**Comment by imShara** [comment]
Thank you @smolleyes. If only add `linux_dump_symbols=0` binary will be 100+MB. But If make `strip nw ` after this, binary will be 74MB.

PS. [How buildbot works?](http://buildbot-master.node-webkit.org:8010/builders/linux64_nw12/builds/4)

**Comment by smolleyes** [comment]
can t answer on this, sorry :)

**Comment by 823639792** [comment]
I have problem when download source code, can you give me you source code? thanks.

**Comment by imShara** [comment]
@823639792, what problem do you have?

**Comment by 823639792** [comment]
$ ./build/gyp_chromium content/content.gyp
Enabled Psyco JIT.
Updating projects from gyp files...
Using overrides found in C:\Users\yu\.gyp\include.gypi
and not generate sln and vcproj files。

**Comment by rogerwang** [comment]
closing since OP's issue has been resolved.

@823639792 we build with ninja, not VS.
