### ISSUE TITLE
Other app windows don't refresh when brought to front over nw js window (Windows 7)

### ISSUE THREAD

**Issue by davidearl** [nwjs/nw.js#3384]
Starting with a nw.js window partially in front of another app window (it doesn't matter what app, it happens with everything), if I click in the other app's window to bring it to the front and focus, it only partially gets redrawn - the Windows system chrome is redrawn, but not the app content. If I ALT+TAB to bring the app to the front it is fine. Sometimes (not always) by clicking back and forth I can then get it to refresh the other window, but nearly always not.

See before and after screenshots attached.

This is Windows 7 64-bit running with dual monitors. It's a basic (non-aero) theme, so there's no semi-transparency involved. nw.js version 0.12.0, io.js 1.2.0 chromium 41.0.2272.76 commit hash: f6c7f79-10b9c03-be948af-459755a-2bdc251-c114bb7

In these screen shots, the other app is Emacs for Windows, but as I say it could be anything. The nw.js app is also running a debug window on a second monitor. I haven't done any packaging of the app yet: I'm just starting it using nw.exe with my app's folder as argument (from a windows shortcut).

![before](https://cloud.githubusercontent.com/assets/1050651/7216263/2eb47044-e5f1-11e4-829e-04e9c638a68e.png)
![after](https://cloud.githubusercontent.com/assets/1050651/7216264/3629100a-e5f1-11e4-984e-4fa673f519b2.png)
##

**Comment by Christywl** [comment]
It doesn't reproduce for me on Windows with nwjs-sdk-v0.23.5. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.

**Comment by davidearl** [comment]
I haven't seen this bug since I switched to Windows 10, so updating probably won't make any difference.
