### ISSUE TITLE
Window.focus() not taking focus

### ISSUE THREAD

**Issue by fifsky** [nwjs/nw.js#3387]
```
"window": {
    "fullscreen": false, 
    "resizable": true, 
    "show": false, 
    "always-on-top": true, 
    "frame": false, 
    "title": "Verystar POS", 
    "focus": true, 
    "height": 600, 
    "min_height": 500, 
    "visible": true, 
    "as_desktop": true, 
    "width": 800, 
    "position": "center", 
    "min_width": 800, 
    "exe_icon": "logo.png", 
    "show_in_taskbar": true, 
    "mac_icon": "logo.icns", 
    "transparent": false, 
    "toolbar": false, 
    "icon": "logo.png"
}, 
```

``` js
function showWindow(){
win.show();
win.focus();     <---  not working
}
```

version nwjs 0.12.1, win32

A similar problem：

focus() works on 'loaded' but fails on 'restore' in recent versions 

https://github.com/nwjs/nw.js/issues/3042
##

**Comment by bagana** [comment]
I don't know why, but, for me:

this.show(); this.focus(); // does not work
this.minimize(); this.restore(); this.show(); // does not work
this.minimize(); this.restore(); this.show(); this.focus(); // does not work
this.show(); this.minimize(); this.restore(); // does not work
this.show(); this.minimize(); this.restore(); this.focus(); // does not work
this.minimize(); this.restore(); this.show(); this.minimize(); this.restore(); this.focus(); // WORKS!
this.minimize(); this.restore(); this.show(); this.minimize(); this.restore(); // WORKS!

I'm on Windows 7 64bit, nw.js 0.12.1.

**Comment by baconface** [comment]
@fifsky ```win``` is not available in your function. Try:
```javascript
function showWindow(){
    var gui = require('nw.gui');
    var win = gui.Window.get();
    win.show();
    win.focus();
}
```
@bagana Try likewise.

If still no luck please send results from your developer tools console.

**Comment by rurigk** [comment]
@baconface
My code is
var gui = require('nw.gui');
var win = gui.Window.get();
win.maximize();
win.setAlwaysOnTop(true);

gui.App.on('open', function() {
	Show();
});
win.on('blur',function(){
	Hide();
})
window.addEventListener('load',function(){
	window.addEventListener('keydown', function(e){
		if(e.keyIdentifier === 'F5'){window.location.reload();}
		if(e.keyIdentifier === 'F12'){win.showDevTools();}
		if(e.keyCode === 27){
			Hide();
		}
	});
})
function Show(){
	win.show();
	win.focus();
}
function Hide(){
	win.hide();
}

The window is always displayed but only occasionally focus

**Comment by jaruba** [comment]
I'm on Windows 8, ``win.focus()`` works only if I have a different window from the same app or focused or the console log focused.

If I have a windows explorer window focused, then ``win.focus()`` only triggers the ``focus`` event but does not really focus the window..

**Comment by fritx** [comment]
:dizzy_face:

**Comment by Christywl** [comment]
It works fine for me on Windows with nwjs-sdk-v0.23.5. Please try the latest nwjs build.

**Comment by fifsky** [comment]
In the past for too long，Maybe your can try latest version

**Comment by darkguy2008** [comment]
Same happened to me when spawning a window today using a js file as main entrypoint.

Fixed it with:
```
            win_main.setAlwaysOnTop(true);
            win_main.setAlwaysOnTop(false);
            win_main.requestAttention(true);
            win_main.requestAttention(false);
```
