### ISSUE TITLE
trouble waiting for results from websql query

### ISSUE THREAD

**Issue by kas240sx89** [nwjs/nw.js#3389]
the problem im having is my functions start before the the query finishes. i am trying to get the foreign key results from one query  to run on another query. but the query takes to long and throws undefined. the only fix i have been able to find is the setTimeout. this works for one function but the rest of the program gets messed up. here is a section of the code i have been using for testing:

function checkForFiles()
{
var rows =1;

 console.log('Here we go');

```
DB.transaction(function (tx) {
    tx.executeSql('SELECT * FROM Files WHERE Files.path == (?) AND Files.file == (?)',[filePath,fileName],
                function (tx, result) {

                    rows = result.rows.length;
                    console.log(rows);

            })
});

setTimeout(function () { console.log('Done ' + rows) }, 3500 );
```

}

without the setTimeout i get
done 1
3

when i should be getting 
3
done 3
##

**Comment by mscreenie** [comment]
You're code is probably expecting "rows" before it is actually complete. You might want to write a function that is called after the query is executed or write asynchronous code using promises

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please upload a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
