### ISSUE TITLE
Disable zoom

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#3390]
I'm trying to disable zoom (actually, pinch zooming) in a nw app, but nothing seems to be working.

I've already put a "zoom" event listener on current window, but it never gets fired unless I fire it manually;
the "viewport" meta tag doesn't work either.

Framework used: AngularJS (with angular-touch support library)
##

**Comment by fxpoet** [comment]
+1

**Comment by fxpoet** [comment]
there is a simple solution, it is to use preventDefault method.

var cancelZooming = function(e) { 
    if (e.touches.length > 1) e.preventDefault();
    return false; 
}

document.body.addEventListener("touchmove", cancelZooming, true);

it works for me.

**Comment by Baccanno** [comment]
There is chromium flag for this, --disable-pinch, add it to your manifest (see wiki page related)

**Comment by lorenzoambrosi** [comment]
@fxpoet 's fix worked wonders. Gonna try the --disable-pinch flag soon

**Comment by Baccanno** [comment]
This flag works in my case

2015-05-18 15:31 GMT+02:00 Thunder <notifications@github.com>:

> @fxpoet <https://github.com/fxpoet> 's fix worked wonders. Gonna try the
> --disable-pinch flag soon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwjs/nw.js/issues/3390#issuecomment-103060741>.
>



-- 
Michaël Picovschi, Morphiks
http://www.morphiks.com

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
