### ISSUE TITLE
win7

### ISSUE THREAD

**Issue by meiyoulixiang** [nwjs/nw.js#3392]
win7下汉字不能正常显示，有的系统没有问题，有的系统存在问题，特别是32位的系统出现该情况的问题比较多一点，后经过再页面上将字体的字号写成18px以上，或者字体加上bold式样以后能正常显示，请问这该如何处理
##

**Comment by Christywl** [comment]
Please try the latest nwjs build, and please use English so all users can read, or the issue will be closed directly.
