### ISSUE TITLE
Fixed page title?

### ISSUE THREAD

**Issue by cjroth** [nwjs/nw.js#3394]
Is it possible to set an option so that the page title is fixed by what I set in the manifest and _does not update_ based on the page title or javascript calls?
##

**Comment by 1j01** [comment]
You could try wrapping the page in a page with an `iframe`
The entire contents of `wrapper.html` could be `<iframe src="app.html"/>`

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
