### ISSUE TITLE
调用win.close时 程序未完全退出

### ISSUE THREAD

**Issue by lijia008** [nwjs/nw.js#3395]
调用win.close时 程序未完全退出 进程管理器里面还能看到
##

**Comment by clanwqq** [comment]
可能页面报脚本错误了。你可以看下。

**Comment by lijia008** [comment]
谢谢  我有在调试页面看 没有错误；而且是有时候程序能完全退出  有时候不能

**Comment by clanwqq** [comment]
你自己调用Close的代码是不是使用的是，win.on('close',function(){win.close(true)});  这个监听close事件当页面刷新时。这个事件就无效了。我也不知道为什么。我的做法是在这个方法前增加了。removeAllListner()






在 2015-04-24 09:18:29，"lijia008" <notifications@github.com> 写道：


谢谢 我有在调试页面看 没有错误；而且是有时候程序能完全退出 有时候不能

**Comment by lijia008** [comment]
我是监听的一个按钮button.on('click',function(){win.close(true)});我试试你的方法  非常感谢

**Comment by Christywl** [comment]
Please use English so all users can read, or the issue will be closed directly.
