### ISSUE TITLE
nwjc and datas not encrypted (security issue)

### ISSUE THREAD

**Issue by yoyoy** [nwjs/nw.js#3399]
Hi there,
I try to encrypt datas in a bin file for a FTP configuration ... 
it work with nwjc but if I open the .bin file with a notepad... 
i can read all my FTP datas in clear among the other encrypted parts of my file ... 
did you have any idea to avoid that ? 
thanks

**Comment by yoyoy** [comment]
I tried to include the ftp config in my global application script and complie it with nwjc... the .bin file is bigger but the problem persist ... 
this is a real security issue :'(

**Comment by yangguo-chromium-org** [comment]
Please do not rely on the startup snapshot to provide any value regarding encryption. It "encrypts" not more than any compiler would.

**Comment by rogerwang** [comment]
Right. The tool is only for compile JS source to binary. And if you write a string literal in C++, you'll see it in plain text in the compiled binary too...

**Comment by yoyoy** [comment]
ok sorry for my confusion... but how can I protect this datas ? 
is it a way ? 
thanks
