### ISSUE TITLE
How to config the browser name

### ISSUE THREAD

**Issue by badnewfish** [nwjs/nw.js#3402]
I want get the browser name on server , for example in iis ASP.net MVC,the client browser is nw.js，but on  the server，the c# code get the browser name is "Chrome",the c# code like this:
requestContext.HttpContext.Request.Browser 
in the application Fiddle，can catch the httpcontext like this:

![3](https://cloud.githubusercontent.com/assets/10934040/7313049/3625a06e-ea88-11e4-98de-999b31eb261d.png)

if i want creat a  custom httprequset by nw,how  to config the browser name ?

**Comment by rogerwang** [comment]
You can change the user agent string: https://github.com/nwjs/nw.js/wiki/Manifest-format#user-agent

**Comment by badnewfish** [comment]
@rogerwang  ： my json config is：
![4](https://cloud.githubusercontent.com/assets/10934040/7314366/5e399566-ea96-11e4-95fe-70c8e5bb7a9e.png)
but  i still get the browser name is "Chrome"，both in c# code and Fiddle. why?

**Comment by shaynem** [comment]
Try doing it how the doco states..

Its a string... And % values use the fields from the configuration.

"user-agent":"%name"

Would show STP as the user agent string.

Same as how you have node-remote.
