### ISSUE TITLE
How to protect sensible datas in my code ?

### ISSUE THREAD

**Issue by yoyoy** [nwjs/nw.js#3404]
Hi there.
I would like to hide some datas (ftp connexion infos for example) in my code (see this post https://github.com/nwjs/nw.js/issues/3399 )

I tried to compile my js with nwjc but i can read my file with notepad and see some confidential datas...
Is it a way to encrypt my JS to avoid problem if I distribute my app with node-webkit-builder ? 

thanks a lot

**Comment by 1j01** [comment]
Even if you did, someone would still be able to use a packet sniffer like WireShark, wouldn't they?
I guess that's considerably more work than reading a text file, if that's worth something to you.
You can hide the source code with [v8 snapshots](https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot).

**Comment by baconface** [comment]
Unless being used by yourself sensitive data like connection info for FTP servers and databases should never be included in a distributed project. Instead create a secure RESTful API you can interact with using JS on your client side. Otherwise it is easily obtained from the reverse engineering source code or packet sniffing.

**Comment by rogerwang** [comment]
Hello, our goal is to provide the same level of support that a C++ application would do. A compiled C++ app doesn't protect your string literals in the source code. As mentioned above, the data could still be sniffed on the network.

If you just want it not to be plaintext in the distributed binary, you can consider writing an algorithm to decoded it in the runtime. The algorithm's code is protected by the binary compilation.
