### ISSUE TITLE
Unlimited Storage Flag for Chromium not working

### ISSUE THREAD

**Issue by jbrosi** [nwjs/nw.js#3405]
Hi there,

it seems like the --unlimited-storage option for chromium does not work. I put it within the "chromium-args" in my manifest and I am able to see it in the list of command line options under "chrome://gpu". But whenever I request more then 10 GB of Storage it only returns 10 GB as granted.

```
navigator.webkitPersistentStorage.requestQuota(1024 * 1024 * 1024 * 50, function(granted){console.log(granted);})
//outputs 10 gb
```

If I start the corresponding chromium version (38 / 41) with the same args directly on commandline, it would return all free disk space available (890GB for me), even if i only ask for some bytes. If I don't specify the option, it returns 10 GB like node webkit does all the time.

I tested this on 11.5, 11.6 and 12.1 - it behaves all the same on windows and mac and with 32 and 64 bit versions.

(Yes I know I could use node fs in order to write as much as i like, but I have to do this from webworkers where i don't have node context available and the child_process fork / communicate stuff seems still bugged)
##

**Comment by NagrajGajengi** [comment]
is this issue been fixed ? or what workaround have you used ?

**Comment by rogerwang** [comment]
It should be fixed in 0.13.0 RC.

**Comment by Christywl** [comment]
It works fine for me on Linux/Windows with nwjs-sdk-v0.23.5. It returns the correct storage.

**Comment by Christywl** [comment]
close until there is more information.
