### ISSUE TITLE
Node Webkit Crashes With Jquery

### ISSUE THREAD

**Issue by jeandrelucas** [nwjs/nw.js#3407]
Hello,

I'm using node webkit and it crashes when I simply use some basic features of jquery as FadeIn/FadeOut and/or Ajax Callbacks, as Success.
It crashes and closes. Sometimes the screen turns to dark.
I was debuging my code and I noticed that when Success callbacks runs (yes, it runs), after it simply crashes..
On chrome and firefox browsers everything is OK. The app runs normally.
I'm using HTML, Javascript/Jquery and CSS only. I've tried everything I could on code side.
I'm using Windows 7.

Thanks.
##

**Comment by benjismith** [comment]
That's odd... I use jQuery extensively in my nwjs app, and I've have never had a problem. Can you post a minimal test case?

**Comment by jeandrelucas** [comment]
With the code below node-webkit DO NOT CRASHES, and don't work because the //
			if ( dataUsers[idUser].status == true ) {
				localStatus = '#localStatus_' + idUser;
		//		$(localStatus).fadeIn('fast');
			} else if ( dataUsers[idUser].status == false ) {
				localStatus = '#localStatus_' + idUser;
		//		$(localStatus).fadeOut('fast');
			}

The code below CRASHES
                       if ( dataUsers[idUser].status == true ) {
				localStatus = '#localStatus_' + idUser;
				$(localStatus).fadeIn('fast');
			} else if ( dataUsers[idUser].status == false ) {
				localStatus = '#localStatus_' + idUser;
				$(localStatus).fadeOut('fast');
			}

I know that's odd, and I don't know what to do.

**Comment by arivera12** [comment]
I have the same problem using mac os x. I have used jQuery on a lot of projects but now jQuery crashes without generating a dump file. Even using the Request module I have the same behavior. The app just simply closes when the success handler its called...

**Comment by sumeetsd700** [comment]
I am also facing the same problem..

My index.html file contains...
`<div class="temp-div" style="top: 40px;">
                                <span id="temp_c">--</span>
                            </div>`

and my script.js contains....
`$('#temp_c').text(weather_result.temperature);`

I have checked each and every thing in my code using alerts and every thing is working file, but when it comes to manipulate the page like adding content via JavaScript, even the basic functions like `$('#xyz').html(<b>ABC</b>)` don't work. I am using JQuery 2.x.

**Comment by Christywl** [comment]
It works fine for me on Linux/Windows 8 with nwjs-sdk-v0.23.5. No crash happens. I use https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_html_set to check this.

**Comment by arivera12** [comment]
This got fixed updating nwjs. This thread should be closed more than a year ago cause nwjs have done a lot of updates.

**Comment by rahulsharma841990** [comment]
I just noticed that if there is an error on your jQuery code then app crashed. But there i just use try catch to get jQuery error..you need to put your all jquery code in try:

var dataArray = [1,2,3,4,5,6];
        try{
            $.each(dataArray, function(key, value){
                console.log(valuedd);
            });
        }catch(e){
            console.error(e);
        }
