### ISSUE TITLE
gui.Shell.openItem() "error opening location: No application is registered as handling this file"

### ISSUE THREAD

**Issue by xingped** [nwjs/nw.js#3408]
Just trying to execute a generic, extension-less executable I've compiled, but I get the following error:

```
$ gvfs-open: /home/xingped/Desktop/myapp/myapp: error opening location: No application is registered as handling this file
```
##

**Comment by thesbros** [comment]
Does the executable have +x?

**Comment by xingped** [comment]
It does.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
