### ISSUE TITLE
Window.focus() won't bring in front of other applications

### ISSUE THREAD

**Issue by mmorrisontx** [nwjs/nw.js#341]
Calling focus() on a Window won't bring a window to the front if another application has focus -- it only seems to work correctly if the nw application is the one in front.

**Comment by sergiovilar** [comment]
Issue from 2013, we already in 2015.. same here too.

**Comment by rajdsouza** [comment]
The below code should work. it works for me
```
var jQuery = require('jquery');
var fs = require('fs');
var gui = require('nw.gui');

jQuery(function(){
	win.focus();
});

**Comment by iXshad0w** [comment]
same here,
tried by using:
```javascript
win.setAlwaysOnTop(true);
```
but that wouldn't work :<

**Comment by cotejp** [comment]
I'm on macOS 10.12.6 and it does not work (nor does `setAlwaysOnTop(true)`.
