### ISSUE TITLE
Can context menu's be styled?

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3412]
I haven't seen anything regarding this on the wiki, so I figured I would ask if anyone knew if nw context menu's can be styled or not. Thanks.

**Comment by Baccanno** [comment]
Usually in JS you do style the context menu by capturing the right click and adding whatever you need to do there. I don't know for tuning the system context in NW but I thinks JS event bases solution would be simplier ( and you would find a lot of resources on the net )

**Comment by watdafox** [comment]
you can bind whatever you want to right click (a bootstrap menu for example), but I don't think `gui.MenuItem` can be stylized except for an icon and the title.
