### ISSUE TITLE
NW.js crashing silently, not generating crash dumps (0.12.1)

### ISSUE THREAD

**Issue by johnthedebs** [nwjs/nw.js#3415]
I'm developing an app that's primarily running on Mac & Windows and is crashing intermittently, but I'm unable to get any feedback about the causes of the crashes. It crashes silently and there is no crash dump information available as far as I can tell (on both Mac & Windows).

I've read over the [crash dump docs](https://github.com/nwjs/nw.js/wiki/Crash-dump) a few times and have tried triggering crashes manually and setting the crash dump dir explicitly but neither has helped.

I'm testing on OS X 10.10.3 and a Windows 8.1 VM. NW.js version is 0.12.1, and I'm building using node-webkit-builder (also set explicitly to version 0.12.1).

Any advice is appreciated!
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
