### ISSUE TITLE
Get rid of Screen.Init() (and maybe revise requires in general?)

### ISSUE THREAD

**Issue by 1j01** [nwjs/nw.js#3416]
This API goes against node.js conventions, and is confusing.
This code, for example:
```js
var Screen = require("nw.gui").Screen;
Screen.Init();
Screen.screens[0];
```
Does not work, because `Init()` doesn't modify the object of which `Init()` is a method.

This code would work, and return the actual usable module:
```js
require("nw.gui").Screen.Init()
```
This code would throw an error:
```js
require("nw.gui").Screen.Init()
```
It's the same code, but you ran it a second time, maybe in a separate file or maybe a library used it previously, or something, so now `require("nw.gui").Screen` is the actual module, not containing an `Init()` method, so `undefined is not a function`.

Furthermore, there is of course no case where you would not want it initialized!

`nwDispatcher.nwGui.Screen` could be a getter that initializes it the first time.

`Init()` can be deprecated by providing a method on the module that logs a warning.

To take it further, here is what the `require` API *really* ought to be like:
```js
require("nw/screen").screens
require("nw/window").get()
```
(or if you *really* want, the module names *could* be uppercase)

**Comment by KenRmk** [comment]
I agree. But dont' worry. NW13 will move it's api towards Chrome api.

announcement:
https://groups.google.com/d/msg/nwjs-general/A7VpwOztU_s/Tg1L6nS2RBsJ

We'll be soon using this
https://developer.chrome.com/apps/system_display

**Comment by 1j01** [comment]
Cool :+1:
