### ISSUE TITLE
Draggable bounding box doesn't match element on mac.

### ISSUE THREAD

**Issue by zachrip** [nwjs/nw.js#3418]
[This issue only applies to Mac] - Elements that are draggable appear to have an issue where the bounding box for the mouse is shifted down. This example code shows this problem in action:

NW HTML file: http://pastebin.com/cWgayEM8
NW Package.json: http://pastebin.com/61MeG5TX
##

**Comment by Christywl** [comment]
I try on Mac with nwjs-sdk-v0.23.5,  it works fine except that the mouse position may change when dragging. Is this same with yours?

**Comment by zachrip** [comment]
@Christywl I'm not sure, this issue is from 2015..I don't own a mac to test on. You can close this issue if you like.
