### ISSUE TITLE
Dev Tool issues, black window or nw crash

### ISSUE THREAD

**Issue by daron1337** [nwjs/nw.js#3419]
Hi all, 
- nw 0.8.x last version under Windows 7 64 bit, click on dev tool button on toolbar -> nw crashes !
- nw 0.12.x last version, same environment, the dev tool window is black !
- If I run my app using nw 0.8.x the app get stucked on launch and nw.exe is "not responding"

It happens only on one computer, as far as i know at the moment.
Windows 7 64 bit, i7 cpu, 24gb ram , geforce gt430, dx11.
nw.pak is on the same folder as nw.exe
Antivirus is off.
No proxy.

Suggestions?
##

**Comment by riadd** [comment]
Having the same problem. Did you find a solution?

**Comment by daron1337** [comment]
Nope,
the only difference between that computer and others where nw was working was the graphic driver.
I did not understand the problem, as far as I know after a os format the problem was gone.

**Comment by Gimmeaphatbeat** [comment]
I can consistently reproduce this when I already have a njws application running (e.g. Popcorn Time) then run *my* application and attempt to open Dev tools.

Basically it crashes if the Dev tools port is already in use, I think.

**Comment by Christywl** [comment]
Run a simple app and dev tools works fine for me on Windows with nwjs-sdk-v0.23.5. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
