### ISSUE TITLE
Frameless + Maximize = Frame exposed outside window area

### ISSUE THREAD

**Issue by baconbrad** [nwjs/nw.js#3421]
I am having this issue with 0.12.1.

No frame enabled via manifest and using  win.maximize exposes part of the window frame in the taskbar and a little bit into the adjoining monitors on Windows 8.1.

Annoying to look at but not breaking anything for me as far as I know.
##

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by Elity** [comment]
+1  0.21.4 have some problem

**Comment by Christywl** [comment]
It works fine on my windows 8 with nwjs-sdk-v0.23.5. Please try the latest nwjs build, if still reproduce for you, please upload your sample.
package.json:
```
{
  "name": "3421",
  "main": "index.html",
  "window": {
    "frame": false
  }
}
```
index.html:
```
<button onclick="Maximize()">Maximize</button>
<button onclick="Restore()">Restore</button>
<script>
var win = nw.Window.get();
function Maximize(){
win.maximize();
}
function Restore(){
win.resotre();
}
</script>
```

**Comment by Christywl** [comment]
close until there is more information.
