### ISSUE TITLE
Cookies not sent on websocket upgrade request

### ISSUE THREAD

**Issue by feelingweird** [nwjs/nw.js#3422]
Hi,
I am having an issue when users authenticate. The code works fine in Chrome (desktop), and older NWK (10.1 i think) but fails on 11.6, 12.0 and 12.1 

basically it boils down to no cookies are sent with the websocket upgrade request. 
So the negotiate request will look like this:

```
GET http://localhost/signalr/negotiate?clientProtocol=1.4&connectionToken=qs09pHGxr6x5fff1GJ%2FChWUnpSLX5ljV8FuS3h06P%2FhpS55cjNvh2uFHHTXukDI%2BK%2BcgsC6%2BWVJHba4xrkt6IVc2KwGIfm4eeyHrigNFRotjBYKb&connectionData=%5B%7B%22name%22%3A%22windowmanagementhub%22%7D%5D&_=1429572950768 HTTP/1.1
Host: localhost
Connection: keep-alive
Accept: text/plain, */*; q=0.01
 X-DevTools-Emulate-Network-Conditions-Client-Id: 2E81759B-036D-4E92-ADF4-865AFBF59D2
 User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
 Content-Type: application/x-www-form-urlencoded; charset=UTF-8
 Accept-Encoding: gzip, deflate
 Accept-Language: en-GB,en-us;q=0.8,en;q=0.6
 Cookie: ASP.NET_SessionId=opyggkqxnudnuag5mtxy40ai; __APPLICATION_LANGUAGE=en-GB; __RequestVerificationToken=eoB...GHjTo1; .ASPXAUTH=6909...82ED0; WindowsAuthCookie.LoginName=userName
 Origin: http://localhost
```

and the response to that is:

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
Expires: -1
Server: Microsoft-IIS/8.5
Access-Control-Allow-Origin: http://localhost
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Mon, 20 Apr 2015 23:46:49 GMT

177
{"Url":"/signalr","ConnectionToken":"LwJz6Ev3+9C/NbKBqHkrI8KwYaz53qiBbzDJVlcse1qRXU3loCqOI68kUb4kpyk8gdQlkKRJ0wBrpb+VVtUMFtrtSQOEhGQE9ZNaMDBajyK2/Evz","ConnectionId":"68e7751b-aaee-4ed7-aa36-a2d1ab25107f","KeepAliveTimeout":20.0,"DisconnectTimeout":30.0,"ConnectionTimeout":110.0,"TryWebSockets":true,"ProtocolVersion":"1.4","TransportConnectTimeout":5.0,"LongPollDelay":0.0}
0
```

The subsequent request to upgrade the http connection to a websocket connection will fail because the headers don't include the cookies of the previous request. see below

```
GET http://localhost/signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=LwJz6Ev3%2B9C%2FNbKBqHkrI8KwYaz53qiBbzDJVlcse1qRXU3loCqOI68kUb4kpyk8gdQlkKRJ0wBrpb%2BVVtUMFtrtSQOEhGQE9ZNaMDBajyK2%2FEvz&connectionData=%5B%7B%22name%22%3A%22windowmanagementhub%22%7D%5D&tid=0 HTTP/1.1
Host: localhost
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://localhost
Sec-WebSocket-Version: 13
User-Agent:
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-us;q=0.8,en;q=0.6
Sec-WebSocket-Key: HqfgeBw4svkTTpBK2CfaJA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

And the 403 response. 

```
HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/html
Expires: -1
Server: Microsoft-IIS/8.5
Access-Control-Allow-Origin: http://localhost
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Mon, 20 Apr 2015 23:46:49 GMT

61
Unrecognized user identity.  The user identity cannot change during an active SignalR connection.
0
```

SignalR then falls back to Server Sent Events, by re-sending the `http://localhost/signalr/connect?` request, but this time it includes the cookies so SignalR connects successfully. 

It seems to be an issue when handing off to window.WebSocket() inside the jquery/signalr library. 

there is a StackOverflow question for this. 
http://stackoverflow.com/questions/29761076/signalr-node-webkit-node-fails-to-connect-over-websockets-when-authenticated

cheers
kle
##

**Comment by jaymes-bearden** [comment]
I am also having this exact same issue.

Here's what happens in my situation:

- Authenticate with server which responds with session cookie
- Attempt websocket connection (Stomp over SockJS)
- GET .../websocket fails with server responding with custom 419 auth required because the session cookie was not sent
- SockJS falls back to long polling
- App proceeds but is now connected via long polling.

This app has a variation working in Chrome (42) and Firefox. Browser Chrome sends the cookies as expected.

**Comment by shenanigans** [comment]
@rogerwang Is this ever getting fixed? I really need it.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? How could I reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
