### ISSUE TITLE
Attempting to get and close a Window - "Element already exists"

### ISSUE THREAD

**Issue by imjoshdean** [nwjs/nw.js#3425]
This only seems to happen on Windows, but when I open up a Window (using gui.Window.open) and then, inside of that Window, attempt to get the Window and close it - it occasionally crashes with the following error:

```
Error: Element already exists
    at Error (native)
    at new Window (window_bindings.js:23:32)
    at Object.exports.Window.get (window.js:40:15)
```

Does anyone know why this happens? I can't seem to find anything in the source that would indicate the problem.
##

**Comment by imjoshdean** [comment]
Bump.

**Comment by iofjuupasli** [comment]
Only on Windows (7 x64).

nw version: 0.12.3

```
{
  "level": "warn",
  "message":"Failed to update tray menu [Error: Element already exists] Error: Element already exists
    at Error (native)
    at new MenuItem (menuitem.js:82:6)
    ...",
  "timestamp":"2015-09-23T16:33:27.148Z"
}
```

With this error app crashes.

**Comment by fritx** [comment]
```plain
- jquery等部分模块 internal+external双重身份 已在tool/pack.js中定义
- 普通form一定要禁止默认submit行为 否则重复提交会导致 Error: Element already exists 崩溃
- win.close已绑定默认行为(跳转/close) 如需解绑 则自行win.
```

Here is some of the note I took couple of months ago.
Seems it was an unexpected `form.submit` behavior that causes such an "crashing" error.

**Comment by fritx** [comment]
8 months later, I met the same issue again.
This time I forgot to wait until `win.on('loaded')` to modify contents of `win.window`.

**Comment by Christywl** [comment]
It works fine on my Windows 8 with nwjs-sdk-v0.23.5. No crash happens.
```
<script>
nw.Window.open('local.html', {}, function(win) {
setTimeout(function(){win.close();},1000);
});

</script>
```
Please try the latest nwjs build, if still happens, please upload your sample to reproduce it.

**Comment by Christywl** [comment]
close until there is more information.
