### ISSUE TITLE
OS X App can only be launched from the terminal

### ISSUE THREAD

**Issue by brannondorsey** [nwjs/nw.js#3427]
I'm experiencing a strange bug (or perhaps operator error) where my packaged application crashes 2 seconds after its blank window appears. This occurs when I launch the app by clicking on it. If I run:

```
/path/to/application.app/Contents/MacOS/nwjs
```

with no command line arguments the application launches and runs correctly. 

I followed the instructions in the _[How to Package and Distribute Your Apps](https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps)_ wiki page and have also tried an automated build with [node-webkit-builder](https://github.com/mllrsohn/node-webkit-builder) but to no avail.

I'm running OS X 10.10.1 on a 2012 Macbook Pro w/ Node Webkit v12.1.

**Comment by rogerwang** [comment]
could you please upload the crash dump? see https://github.com/nwjs/nw.js/wiki/Crash-dump .

**Comment by brannondorsey** [comment]
I don't have a `~/Library/BreakPad` directory. Is there a way to log the output of the application somewhere without opening it from the terminal?

**Comment by brannondorsey** [comment]
I've gotten a simple app to work correctly, so it would seem that something is wrong with [my project](https://github.com/brannondorsey/ProbeRequestCollectorsKit). Finding a way to log the output of the application would greatly help in debugging.

**Comment by xueeinstein** [comment]
@brannondorsey , your project anatomy is quite strange. NW.js just as client in `public` folder ? The simple app that you mentioned is `cssButterfly.html`? How can I reproduce you work on your project?

**Comment by brannondorsey** [comment]
I've figured this out, but unfortunately don't have time to post about my findings here. Closing for now with hopes to re-open/re-post with info about the issue I discovered. Thanks all who offered to help!
