### ISSUE TITLE
stdin Implementation

### ISSUE THREAD

**Issue by Cedriking** [nwjs/nw.js#3428]
Hello,
I'm having some problem with the way parents and child processes comunicate.

Currently I made some changes to my main app, and it spawn a child_process then I use the `child.stdout.on('data');` event listener and in the child I use: `process.stdin.resume();`

The child is spawned correctly and stdout doesnt throw any error (for now), but as soon as the child exe file is running, I receive this error:

```
Error: Implement me. Unknown stdin file type!
```

The problem is in the call of `process.stdin.resume();` in the child process.

How I can resolve this? I need this so the child can send to the parent process if its need to close or stay open.

Thank you for your time and help.
##

**Comment by rmoncho** [comment]
Hi Cedriking, did you resolve this problem? I have the same.

**Comment by Cedriking** [comment]
Hello @rmoncho it seems to be a problem with Windows devices, unfortunately I wasn't able to resolve this issue.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
