### ISSUE TITLE
Discuss: CMake.js for node/io.js/nw.js native modules

### ISSUE THREAD

**Issue by unbornchikken** [nwjs/nw.js#3432]
Hi there,

First of all, thanks for this great software! 

I'm here because I wanted you to know, that I created a new build system for node which is based on CMake instead of gyp. See there: [unbornchikken/cmake-js](https://github.com/unbornchikken/cmake-js). Today I implemented nw.js support, which means if someone make his/her native C++ module based on CMake.js, it will be already compatible with nw.js runtime (along with node/io.js), there is no *nw-gyp* like magic required.

It's easy to use, at least not harder than node-gyp, please [take a look at the first tutorial](https://github.com/unbornchikken/cmake-js/wiki/TUTORIAL-01-Creating-a-native-module-by-using-CMake.js-and-NAN). Because it's based on the industry standard CMake, you can use your favorite C++ IDE to develop node addons, as described in the [second tutorial](https://github.com/unbornchikken/cmake-js/wiki/TUTORIAL-02-Creating-CMake.js-based-native-addons-with-QT-Creator). And of course it has no Python 2 dependency.

I hope that you find it useful. If you do, don't you think that there can be a section about CMake.js in the Wiki [regarding the using of C++ addons](https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons)?

**Comment by unbornchikken** [comment]
Moving this to the mailing list instead, sorry.

**Comment by Mithgol** [comment]
For future fererences, https://groups.google.com/d/msg/nwjs-general/dwTGxMZo7W0/8Xj9xEpPdWQJ in the mailing list.
