### ISSUE TITLE
h264 support windows

### ISSUE THREAD

**Issue by r3dsm0k3** [nwjs/nw.js#3433]
I have created a custom video player using node-webkit, and due to technical restrictions, only audio and video format available for me are MP3 & MP4 (H.264). So according to wiki page of nw.js "Using MP3 & MP4 (H.264) using the video & audio tags.", I added the ffmpegsumo.dll file to my nw.js distribution directory. It works fine for Mac and Linux; but on Windows the app crashes without any error report or anything. Has anyone have any idea what maybe the problem here, or anyone had faced a similar issue and might know the solution? Also I'm stuck with the situation of bundling the app for distribution on OS, Linux and Windows platforms, as node-webkit-builder downloads a fresh copy of node-webkit package, but I need to replace the ffmpegsumo.dll file with Chrome one before bundling. Thanks in advance.

**Comment by smolleyes** [comment]
You re using a wrong ffmpegsumo if it crash

**Comment by r3dsm0k3** [comment]
Im using 42.0.2311.135 version of ffmpegsumo. Isn't that the one Im supposed to be using?

**Comment by smolleyes** [comment]
Look processus.versions un your app it must stick To chromium version

**Comment by sirisian** [comment]
Would it be possible for the maintainers of nw to include a working h264 ffmpegsumo.dll with node-webkit someplace on every release? I don't mean in the actual files, but just a separate download. Building and getting the required file is extremely time consuming.

**Comment by baconface** [comment]
[The method to do this](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-%28H.264%29-using-the--video--&--audio--tags.) would require everyone to release their NW.js projects source under the GPL. And I think the maintainers of NW.js have their hands too busy to focus maintaining custom ffmpegsumo.dll releases. I recommend possibly taking on the project yourself or asking others in the community much like the direction the ARM builds have gone. Maybe not the best solution but it is better than nothing.

**Comment by ghostoy** [comment]
See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for latest instructions for NW.js 0.13.0 or later.
