### ISSUE TITLE
App protocol doesn't work in Windows

### ISSUE THREAD

**Issue by kethinov** [nwjs/nw.js#3437]
The [app protocol](https://github.com/nwjs/nw.js/wiki/App-protocol) example doesn't work in Windows.
- Make an init.html with whatever in it.
- Make a package.json with the below code in it.
- Do the npm install.
- Run "npm run windows" in the console from Windows. It fails.
- Run "npm run mac" in the console from a Mac. It works.

package.json

``` json
{
  "name": "nw-app",
  "version": "1.0.0",
  "main": "app://app/init.html",
  "engines": {
    "node": ">=0.10.0"
  },
  "engineStrict": true,
  "window": {
    "show": true,
    "show_in_taskbar": true
  },
  "dependencies": {
    "nw": "0.12.2"
  },
  "jshintConfig": {
    "camelcase": true,
    "curly": true,
    "devel": true,
    "evil": true,
    "indent": 2,
    "node": true
  },
  "scripts": {
    "mac": "nodemon -e js,json,css,html --exec \"./node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ./\" --ignore node_modules/",
    "unix": "nodemon -e js,json,css,html --exec \"./node_modules/nw/nwjs/nw ./\" --ignore node_modules/",
    "windows": "nodemon -e js,json,css,html --exec \"cd node_modules/nw/nwjs && nw.exe ../../../\" --ignore node_modules/"
  },
  "private": true
}
```

This works in OS X but not on Windows.

The error is: "Not allowed to load local resource: app://app/init.html"

![screen shot 2015-05-04 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/419567/7460876/34c958a2-f274-11e4-811f-4a361f43116a.png)
##

**Comment by kethinov** [comment]
Confirmed still an issue in 0.12.2.

I also tested 0.10.x and it's an issue there too.

**Comment by baconface** [comment]
There must be an issue with the NPM. That is the only way I can replicate it.

Try downloading the binaries from the site and do the command line action to package in your scripts. That works for me.

**Comment by kethinov** [comment]
I'm still having the same issue running the command directly using a NW.js 0.12.2 downloaded directly from the site:

`.\nw.exe ../../../`

Can you post the precise method you used to get my example to work in Windows?

**Comment by baconface** [comment]
Must be a contextual issue with the paths and not so much the NPM now that I think about it.

Here is my working solution. I downloaded the binaries to a directory. Made a "test" folder with my package.json and init.html. Running ```npm run windows``` seems to load it no issue.

My package.json:
```json
{
  "name": "nw-app",
  "version": "1.0.0",
  "main": "app://app/init.html",
  "engines": {
    "node": ">=0.10.0"
  },
  "engineStrict": true,
  "window": {
    "show": true,
    "show_in_taskbar": true
  },
  "dependencies": {
    "nw": "0.12.2"
  },
  "jshintConfig": {
    "camelcase": true,
    "curly": true,
    "devel": true,
    "evil": true,
    "indent": 2,
    "node": true
  },
  "scripts": {
    "mac": "nodemon -e js,json,css,html --exec \"./node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ./\" --ignore node_modules/",
    "unix": "nodemon -e js,json,css,html --exec \"./node_modules/nw/nwjs/nw ./\" --ignore node_modules/",
    "windows": "nodemon -e js,json,css,html --exec \"cd ../ && nw.exe ./test\" --ignore node_modules/"
  },
  "private": true
}
```
Let me know if that works for you. And then I will try to troubleshoot a working configuration that is compatible with your NPM binaries.

**Comment by kethinov** [comment]
Hmm... yep your example works.

The only real difference seems to be that the app (`test` in your case) is a direct child of nw.exe rather than the execution path involving going up the directory tree.

This still seems like a legit bug to me, but it's nice to have a workaround that seems to work.

**Comment by kethinov** [comment]
Here's my full workaround for anyone who might benefit from it:

```json
  "scripts": {
    "windows": "nodemon -e js,json,css,html --exec \"cd node_modules/nw/nwjs && IF NOT EXIST app (mklink /J app ..\\..\\..\\ && nw.exe app) ELSE (nw.exe app)\" --ignore node_modules/"
  }
```

Basically it works by creating a symlink to the app rather than going up three directories during execution.

**Comment by baconface** [comment]
Personally I avoid putting commands in the scripts section and instead call a script be it a JavaScript, batch, or bash file. Based off of where the script is relative of your manifest file it might fix your path issues.

**Comment by Christywl** [comment]
This `app://` protocol is deprecated since 0.13.0. Please see http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/.

**Comment by Christywl** [comment]
close until there is more information.
