### ISSUE TITLE
Feature Request: showDevTools() jail based on element selector.

### ISSUE THREAD

**Issue by baconface** [nwjs/nw.js#3438]
I have a project where I open jsFiddle in an iframe. I can so far only jail the iframe jsFiddle is in. But I cannot jail the result iframe within the parent iframe. So my dev tools can target the result frame but it picks up everything going on in jsFiddle as well. It would be nice to be able to give it a selector or something along the lines of:
```
var jsFiddle = $('#jsFiddle').contents(); //Gets the iframe jsFiddle is in
var result = jsFiddle.find('#result iframe'); //Element selection of the result iframe
win.showDevTools(result); //Assigning the selection to the dev tools jail
```
Currently this crashes NW.js.

A minor request but it would be nice to see implemented if possible.

**Comment by ghostoy** [comment]
Are you using jQuery selector? You should pass DOM element to `showDevTools()`, instead of jQuery object. So you can try with `showDevTools(result[0])`.

**Comment by baconface** [comment]
Awesome, that was a big oversight on my part. Did the trick.
