### ISSUE TITLE
failed to load resources : net :; ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by ksubilal** [nwjs/nw.js#3441]
I have a jsp page which loads into the iframe of index.html.

But when the page loads inside, it fails to load some dependent files such as jquery and css files.
The path shown of those files in console as "file:///abc/xyz.css" which is wrong. It is supposed to be "http://omg.com/abc/xyz.css". However the page ("http://omg.com/")loads as normal and the problem is only with there resources. 

Hence these files are not loading, the web application is not working as expected.

PLZ HELP!! Thanks in advance
##

**Comment by rogerwang** [comment]
Does the app protocol work for you? https://github.com/nwjs/nw.js/wiki/App-protocol

**Comment by ksubilal** [comment]
No. That didn't work

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
