### ISSUE TITLE
Uncaught node.js Error | Error: Module did not self-register.

### ISSUE THREAD

**Issue by GauravGupta04** [nwjs/nw.js#3444]
Hi team,

Issue context: While calling FFI node module, by node webkit throw following error:

Uncaught node.js Error
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at bindings (C:\Users\GAURAV~1\AppData\Local\Temp\nw7356_8469\node_modules\ffi\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\GAURAV~1\AppData\Local\Temp\nw7356_8469\node_modules\ffi\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)

Following are the details on which we were working and stuck due to above error.
Environment :=>
                             Windows : 64 Bit
                             Node.js : 0.10.33
                             NW.Js    : 0.8.6
                             ffi           : Latest
                             nw-gyp  : Latest 
                             ref           : Latest
                             Python : 2.7.6
                             Visual Studio 2013
We followed following steps to setup the environment and Project :=>
1.  Installed all the software/module written above.
2.  Call the ffi module with Node.js and it is working fine. I’ve tried to call one C DLL by javascript code and which provides the correct response. no issue found until now.
3.  Now tried to compile or build the ffi module with nw-gyp with following a command:
a.  nw-gyp configure  --target =0.8.6
b.  build ffi through ‘nw-gyp build’ command:
              i.    Build fails because I do not have Visual studio 2010 has not been installed on my system.
             ii.    I opened the VC++ project in Visual Studio 2013. This step convert my 2010 project to visual studio 2013 project.
            iii.    Again I tried to run the command ‘nw-gyp build’ and build the project.
4.  Create the .Nw file.
5.  Run .Nw File.
After doing lots of googling and tried all the solution from web, but didn't able to fix the issue. Still throwing Uncaught node.js Error | Error: Module did not self-register error.

Any one from developer community face similar issue, then please comment or provide the resolution, other wise this seems to be defect in nw.js.
##

**Comment by psy21d** [comment]
I already have this error with npm module.

**Comment by Christywl** [comment]
Similar with #5522?

**Comment by Christywl** [comment]
close until there is more information.
