### ISSUE TITLE
'Blank Window' bug - seems to be triggered by using 'require' for js loading - ideas?

### ISSUE THREAD

**Issue by shrewdlogarithm** [nwjs/nw.js#3446]
I can't yet get a simple test-case to show this problem so I wondered if anyone had chanced-across it/might know what's going on (I've seen this in ever recent version from 11.3 through 12.1)

Window(s) are opening to the right size/location but appearing just 'white' and I couldn't interact with them.  If I trigger the Devtools programatically I can step-through setup code and it seems everything loads OK (no errors shown at-least) - but I can't click/use keys/get any response whatsoever.

At first this tended to happen only after reloading a Window - I put it down to a Chrome issue - but when I fully switched from <script> to "require" for .js modules, the problem came back full-time - reverting to all <script> has meant the problem stopped appearing entirely.

Any ideas at all what might be causing this - as I say, code seems to load and run fine but the display isn't being rendered/input isn't being detected (all you can do is alt-F4)
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
