### ISSUE TITLE
very long startup time when using v0.12.1

### ISSUE THREAD

**Issue by signals2** [nwjs/nw.js#3447]
It seems an obvious bug in version 0.12.1, old versions can startup quickly without any pause.
##

**Comment by kai22** [comment]
I've noticed this too, it's like a 3 second pause before the window opens and anoth 3 seconds before the index page loads up...

**Comment by Christywl** [comment]
It looks normal for me. Please try the latest nwjs build. If still reproduce in your side, please provide a sample to reproduce.

**Comment by Christywl** [comment]
close until there is more information.
