### ISSUE TITLE
console output in terminal prints empty "" (osx) 

### ISSUE THREAD

**Issue by Nodman** [nwjs/nw.js#3451]
Hi, everyone!
After updating nwjs to latest version, console.log() prints properly only in devtools, and in terminal it just     looks like: 
`[5248:0507/203857:INFO:CONSOLE(1002)] "", source: file:///nj/core.js (1002).` 
printing just line number and empty "" 

Any ideas? 
Thank you!
##

**Comment by Christywl** [comment]
Please see http://docs.nwjs.io/en/latest/For%20Users/FAQ/#consolelog-doesnt-output-to-linux-terminal.

**Comment by Christywl** [comment]
close until there is more information.
