### ISSUE TITLE
Window download/url events?

### ISSUE THREAD

**Issue by RyanTheAllmighty** [nwjs/nw.js#3452]
Hi,

I'm currently making an application using NW.js and I'm having some issues trying to get things working in the way I need them to.

I'm currently creating a window and looking to hook into that windows events to either emit when the download popup would normally be triggered so I can overwrite it's functionality or be able to hear about url change events when the user navigates on that window.

So far I've come up blank, only being able to hook into the new-win-policy but only fires an event on a new _blank window.

Now Electron provides 'did-get-response-details' and 'will-navigate' events which I can use to achieve what I want.

Just wondering maybe if there's something I'm missing or if there is some easy way to add in these events to be used.

Thanks

**Comment by rogerwang** [comment]
There is a 'new-win-policy' event to catch popup window. Is that what you want?

**Comment by RyanTheAllmighty** [comment]
Unfortunately not. That only sends events for popup windows.

What i'm mainly looking for is a way to get window url changes, so in a window shown to the user, when they click a link on that shown website, an event is sent with the details of that change in location.

**Comment by rogerwang** [comment]
@RyanTheAllmighty what's the exact point when the event is expected to be fired? before loading the url, or when new document element of the new DOM is available or something else?

**Comment by rogerwang** [comment]
If it's the latter, there is 'document-start' or 'document-end' event for this: https://github.com/nwjs/nw.js/wiki/Window#document-start

**Comment by RyanTheAllmighty** [comment]
Unfortunately that doesn't help.

The way I understand this functionality works in Electron for example is the event is dispatched when the frame has been told to load and render a new url.

For instance clicking on a link on a page within the window I've open will send the event with the details of the new location.

The docs on it for example are at https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-did-get-response-details

The goal would be to get the new destination/response details in an event before it's started to process the DOM then you can stop it, read the new url, old url etc.

The main goal is for me to be able to see where the user has navigated to using the window and in some cases download files automatically.

I hope this is making sense :\

**Comment by rogerwang** [comment]
I see what you are trying to do. There is an internal event in Chromium fired upon navigation. I'll expose it to JS. It should be straightforward thing.

**Comment by RyanTheAllmighty** [comment]
Thankyou, that would be excellent :)

**Comment by rogerwang** [comment]
btw, developing browser like application with in JS is better supported with the 'webview' tag in Chromium upstream. There is a sample browser application here: https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webview-samples/browser

webview is supported in NW.js now.

**Comment by subwaymatch** [comment]
The events described by @RyanTheAllmighty is something that I have been looking for in nw.js. +1 for the request. Thanks @rogerwang, I will be waiting for the new API.

**Comment by rogerwang** [comment]
We have an emergent bug fix release this week. Unfortunately this new API was not able to catch in this release. Will see it in 0.12.3 or 0.13.0-alpha1.

**Comment by rogerwang** [comment]
a 'navigation' event is added to the 'Window' object to support this. It's released in 0.13.0-alpha1: https://groups.google.com/d/msg/nwjs-general/c25l_jGMqj8/rsAtdSQuxeUJ

**Comment by RyanTheAllmighty** [comment]
Did this end up making it into 0.12.3 @rogerwang or if not any chance we can see it added to the next 0.12 release as 0.13 seems to be a ways off.
