### ISSUE TITLE
PepperFlashPlayer works on Windows/Linux but crashes on Mac

### ISSUE THREAD

**Issue by janpetersen** [nwjs/nw.js#3453]
Hi,

I'm trying to embed the PepperFlashPlayer with nw.js. So far, it works very well with both Linux (Ubuntu) and Windows: I put the library into a subfolder of nwjs, then add the chromium startup flag, and Flash content gets rendered fine.

But on Mac (OSX 10.10), the plugin immediately crashes. For a brief moment, I can see a "gray box" that is supposed to contain the swf file, but it then vanishes. Nw.js keeps running; just the plugin dies.

Here's some crash report that I found: http://pastebin.com/5PhKzkdv

These are my chromium-args:
"chromium-args": "--ppapi-flash-path=/Library/Internet\\ Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin --ppapi-flash-version=17.0.0.169"

If I start Chromium (from shell) with the same arguments, the PepperFlashPlayer will work:

open -a Chromium --args --ppapi-flash-path=/Library/Internet\ Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin --ppapi-flash-version=17.0.0.169

Has anyone managed to get the PepperFlashPlayer on Mac working with nw.js?

Any help would be greatly appreciated!

**Comment by janpetersen** [comment]
I just re-tested this issue with the 0.13.0-alpha release this morning. The error remains the same: The plugin seems to crash; the browser displays that "Unhappy plugin icon":

![Plugin Crash](http://i.imgur.com/3lZS1PK.gif)

As I mentioned before, this only happens on OSX. On Linux and Windows, all works fine.

**Comment by janpetersen** [comment]
As a fallback, I used the NPAPI Flash Plugin with the OSX release. But I would highly appreciate to be able to use the PPAPI version since it has some benefits over the NPAPI (e.g. supports the rendering of the "Steam overlay" on top of Flash content with wmode=direct, since we use nwjs as a wrapper App for our Flash-based Steam game).

**Comment by xueeinstein** [comment]
@janpetersen , I have checked nwjs v0.12.1 and nwjs v0.13.0-alpha on OSX. Pepper flash plugin works well. Have you setup right pepper flash plugin path? please check it under `chrome://plugins/ `. Thanks.

**Comment by janpetersen** [comment]
@xueeinstein Well, I want to embed the Flash plugin within the application. So I put it into some subfolder of the app, set the appropriate paths (as mentioned above), and then I remove the system's default Flash plugin as well as the one of Chrome. That's important, because I want my app to be running on Macs without any Flash plugins, and I want my app to use the plugin I provide - not any one it may find elsewhere (that's a standard behavior of nwjs: It tries to find required plugins in "common" paths, like the Google Chrome installation folder).

You need to make sure that the plugin that you provide with your app is used - and not any other.

This works for both Windows and Linux fine: I put the PPAPI plugin in a folder inside of my app, link it via Chromium args, and it will be used. But if I do the exact same thing on Mac, the plugin crashes with that "Unhappy icon" above.

But if I copy the NPAPI Flash plugin into my app folder, it will be loaded automatically. Since nwjs will check its own "plugins" directory for NPAPI plugins first, before trying to load them from other sources (e.g. Google Chrome).

Do you manage to get the PPAPI plugin running if you put it into a subfolder of your app, and remove the other ones?

**Comment by xueeinstein** [comment]
Couldn't reproduce this. btw, I use http://www.chemgapedia.de/vsengine/help/en/flash/index.html page to test flash plugin.

>This works for both Windows and Linux fine: I put the PPAPI plugin in a folder inside of my app, link it      via Chromium args, and it will be used. But if I do the exact same thing on Mac, the plugin crashes with that "Unhappy icon" above.

If I put the plugin in the subfolder of an nw.js app, without linking Chromium args, it's loaded, but the test page shows me "Flash not running" :(
