### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by shalaby** [nwjs/nw.js#3456]
How to handle downloading binary files (.exe) in nw.js, and how to monitor the download progress, in my project I used <a> which download the file but nothing presented to the user to indicate the progress of the file download.

**Comment by mscreenie** [comment]
If you're wanting to do this through NodeJS then look at http.request,  you could update a divs width percentage with the 

```
response.on('data', function (data) {
}
```

I've done this and it works great, plus I've done some file integrity check to see if the file came back intact.

**Comment by shalaby** [comment]
Thank you :)

**Comment by mscreenie** [comment]
Welcome, please close if answered.

**Comment by serkanp** [comment]
İ can send you a complete Class for both progress and Limit speed Of
download any Kind Of file with Custom Event emitters
i also wrote a download manager if you are interested

10 Mayıs 2015 Pazar tarihinde, Muhammad Shalaby <notifications@github.com>
yazdı:
