### ISSUE TITLE
Is there any way to detect click event for mouse side buttons?

### ISSUE THREAD

**Issue by Diablohu** [nwjs/nw.js#3457]
Or more specificly, how can I make mouse button 4 & 5 to navigate through history like in Chrome?
##

**Comment by ComSecNinja** [comment]
Testing with `monitorEvents(document.body)` I found that no event fires when pressing other mouse buttons than the three main ones, so it seems like this is not possible to do right now.

**Comment by Diablohu** [comment]
That's unfortunate...Thanks for your response anyway.

Now I only wish nw.js will support mouse side buttons to navigate history natively.

**Comment by watdafox** [comment]
That would be so cool for html apps involving multiple views :o

**Comment by max-collomb** [comment]
Support for mouse button 4 & 5 would be very usefull.
And also keyboard special keys XF86Back and XF86Forward that have the same functions.
