### ISSUE TITLE
App crash on history forward with 5th mouse button when window menu enabled.

### ISSUE THREAD

**Issue by zamiere** [nwjs/nw.js#3458]
App crash on history forward with 5th mouse button when window menu enabled.
Affected versions: 0.12.0, 0.12.1
##

**Comment by zamiere** [comment]
possible duplication of #1507 see 2nd comment

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by zamiere** [comment]
It works correctly for the examples I tried.
