### ISSUE TITLE
require('nw.gui').gui.Window.get().showDevTools() is an undefined function/Cannot read property of 'Window' of undefined

### ISSUE THREAD

**Issue by Mimerme** [nwjs/nw.js#3459]
var gui = require('nw.gui');

var window = gui.Window.get();

window.showDevTools();

Error: Function is undefined

==========================

require('nw.gui').gui.Window.get().showDevTools();

Error: Cannot read property of 'Window' of undefined

**Comment by zschuess-nerdery** [comment]
This is a context issue. Try the following:

    var gui = window.require('nw.gui');
    gui.Window.get().showDevTools();

**More Info**

Related Issue
https://github.com/nwjs/nw.js/issues/1937#issuecomment-45107856

Context Information
https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts#features-andlimitations-of-thenodes-context

**Comment by zschuessler** [comment]
This is a context issue. Try the following:

    var gui = window.require('nw.gui');
    gui.Window.get().showDevTools();

**More Info**

Related Issue
https://github.com/nwjs/nw.js/issues/1937#issuecomment-45107856

Context Information
https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts#features-andlimitations-of-thenodes-context

**Comment by baconface** [comment]
If you are calling it from your node-main it could be a context issue like mentioned above. You would need to set a delay or call it from a script loaded from script tags in the main document to get around this.

If that is not the case I would avoid calling var "window" and opt for "win" instead. window is a reserved global in JavaScript. Even if this is not the reason for your issue re-purposing a global is bad practice.

Try:
```
var gui = require('nw.gui');
var win = gui.Window.get();
win.showDevTools();
```

If this doesn't work and it isn't related to the context issue then likely NW.js isn't available. Cases like this would be if you created an iframe and a non file:// resource inside of it wasn't whitelisted in node-remote. IE: <local> or whatever.com

**Comment by Mimerme** [comment]
Ah I understand the issue, I guess a quick glance was not enough
