### ISSUE TITLE
v0.13.0-alpha0 doesn't start app

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3460]
Hi @rogerwang,

Great to see the development moving so fast to a new version.

I know 0.13.0 is still in alpha, but I have a question anyway as I wanted to test it:

I can't load the app (OSX). putting my files like usual in
````
nwjs.app/Contents/Resources/app.nw
````

just starts the blank nwjs, but the app doesn't load. 

Did something change there? I've tried both the sdk and normal version

**Comment by rogerwang** [comment]
should be a bug. does the way of launching it via command line argument work for you?

**Comment by rogerwang** [comment]
available here: http://dl.nwjs.io/live-build/nw13/05-11-2015/d6f9e97-f9c9062-d4969c0-f914aaa-36da454-96c4b49/

**Comment by chino23** [comment]
Thanks Roger. It starts now, but can't test it cause storage isn't supported yet. Anyway it's an alpha :) But this issue is fixed now, thanks for that!

**Comment by rogerwang** [comment]
@chino23 what do you mean by 'storage isn't supported'? I'd like to fix it.

**Comment by chino23** [comment]
@rogerwang 

ok 3 issues here: (see screenshot below)

1) we use localstorage in our app, which wasn't an issue before, but now I get an error saying it's not supported. We use the https://github.com/gsklee/ngStorage module for angular, but basically it just wraps around the localstorage

2) some of the icons don't get loaded, while most of the others do (png), it says unsafe.

3) when the app starts, it wants to connect go maps.google.com. This is weird as we don't use any google api at all, especially not maps stuff. Why does that happen?

See screenshot:
![screen shot 2015-05-11 at 4 54 54 pm](https://cloud.githubusercontent.com/assets/7042593/7561483/d2f5fbf4-f7fe-11e4-831d-c3a62cb825c8.png)

**Comment by rogerwang** [comment]
The 3rd one is interesting. Do you have any Chrome extension/app installed in that system?

**Comment by chino23** [comment]
I have some extensions installed in Chrome but nothing with google maps. But anyway, those should be separate from the chrome installation, right? 

And the funny thing is, it only happens once I open the developer tools. But now, it doesn't ask for maps.google.com anymore. It wants to go to ***accounts.youtube.com***. Weird.

**Comment by rogerwang** [comment]
@chino23 Right. I'm just trying to isolate the root cause, because it doesn't launch the requests here.

**Comment by rogerwang** [comment]
For the issue of web storage not supported, I fixed it and built a version here: http://dl.nwjs.io/live-build/nw13/05-12-2015/d6f9e97-8dec1d9-d4969c0-f914aaa-36da454-96c4b49/

The 2nd issue looks like in Angular, see http://stackoverflow.com/questions/15606751/angular-changes-urls-to-unsafe-in-extension-page

**Comment by chino23** [comment]
Thanks, the web storage issue is gone now, that works!

The unsafe issue: Ok, I try that out. But why is that marked as chrome-extension files? It's just some picture files getting loaded. I don't really understand what's happening there :)

As for the connections, now it wants to connect to plusone.google.com, and later on in the app it wants to go to id.l.google.com. All of those requests are port 443. And it's all google related (we had maps, youtube, accounts, plusone, and id.l.google.com

**Comment by rogerwang** [comment]
All the app resources are now loaded with the "chrome-extension" protocol. I'll see the last issue.
