### ISSUE TITLE
How to access require('os') of nw from a page inside iframe (different domain)

### ISSUE THREAD

**Issue by ksubilal** [nwjs/nw.js#3461]
I use a webapp which loads inside iframe. Inside the webapp i want to write a script which has access to use nw library (i.e. require('os') , require('nw.gui') etc.). But it gives the error of different protocol. The webapp is http:// and the parent is file://. Both these browser and webapp belongs to me and hence i can work on both side. 

Any help.. it's being a few months am sitting on this :(

**Comment by mscreenie** [comment]
Can you post your app code? I'll have a look. Calling require from within an Iframe should work.

**Comment by janpetersen** [comment]
Have you tried these chromium arguments?

http://peter.sh/experiments/chromium-command-line-switches/#unsafety-treat-insecure-origin-as-secure

**Comment by baconface** [comment]
Since the web app uses http:// it is no longer allowed access to using node.js code until it is white listed using node-remote.

https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote

**Comment by ksubilal** [comment]
You're rocking guys!!  Thanks alot. The 'node-remote' worked for me. Hurray!!
