### ISSUE TITLE
v0.13.0-alpha0-win: No JS code executed

### ISSUE THREAD

**Issue by JohannesHaible** [nwjs/nw.js#3462]
Hello,

I tested
* nwjs-v0.13.0-alpha0-win-ia32
* nwjs-v0.13.0-alpha0-win-x64

on Windows 7.

When I try to execute the "Quick Start" project (https://github.com/nwjs/nw.js#quick-start), no JavaScript Code is executed at all. Source code works great for earlier NW.js implementations.

Regards,
Johannes

**Comment by rogerwang** [comment]
Hello, there is a "known issue" section in the release notes:

* (windows) need to specify full path to the package directory as the command line argument

Is it happening there?

**Comment by JohannesHaible** [comment]
Ah ok, I have to package the folder first.

I made a package following this guide:
https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#windows

Then I get the following error:
```
"Error Loading Extension"
"Failed to load extension from <path to my 'source.nw'> Manifest file is missing or unreadable."
```

Then I put a file "manifest.json" with the following code in the "source.nw" file:
```
{
	"name": "My First Extension",
	"version": "1.0",
	"manifest_version": 2,
	"description": "The first extension that I made.",
	"browser_action": {
		"default_icon": "icon.png"
	},
	"permissions": ["node"]
}
```

But I still get the error "Error Loading Extension".

This is how I start nw:
```
C:\Users\<username>\Downloads\nwjs-v0.13.0-alpha0-win-x64>nw.exe C:\Users\<username>\Downloads\nwjs-v0.13.0-alpha0-win-ia32\source.nw
```

**Comment by rogerwang** [comment]
could you please upload your sample somewhere so I can try it?

**Comment by JohannesHaible** [comment]
Here are my source files:
https://mega.nz/#!PRBEAB5K!nnAAuh0vRwKUhv0AcGumOI8OgMWTI3QDV5QOGGVtFOU

I tried different approaches to execute my code (drag and drop, source folder, source.nw file) but with no luck.

Thanks for having a look.

**Comment by psy21d** [comment]
Yes, already have this error! Why you dont fix it?
Its just stupid error, package.json was not readed at all.
Older version make error "module not self-registered", that error from old node.js implementation.

**Comment by DanielJoyce** [comment]
One problem is chrome apps have the structure of /lib, and /web/manifest.json

The top level of the zip thus would look like

/lib
/web/manifest.json

Which is different from nw.js expecting /package.json at the top level.

This needs to be supported when loading .nw files.

**Comment by ToadKing** [comment]
I am also having this issue with "Error Loading Extension".  Johannes' example also does not work for me. Does anyone have a working example that runs in nw.js 13?

**Comment by rogerwang** [comment]
@ToadKing it is in the zip format. There is a bug on this, will be fixed in the next alpha version soon.
