### ISSUE TITLE
Max width of window not working correctly.

### ISSUE THREAD

**Issue by WebFreak001** [nwjs/nw.js#3465]
I want to make a tool window that has 50px width but because there is a general minimum window width of about 100px I cant make it like that. The minimum width should actually be gone when disabling the frame (which doesnt work) or when setting it to a tool window (which is not possible I think).
This is actually the window style I want to achieve:

![Toolbar window style instead of regular window style](http://i.webfreak.org/CC2D3D.png)
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
