### ISSUE TITLE
Build 0.13 alpha

### ISSUE THREAD

**Issue by MikeGCV** [nwjs/nw.js#3466]
Is there any instructions for building this version ourselves. I need to test some codecs in ffmpeg

**Comment by broderix** [comment]
@MikeGCV check this out http://dl.nwjs.io/v0.13.0/alpha0/

**Comment by rogerwang** [comment]
It's very similar with NW12, except that you'll need to manually checkout the nw13 branch of the 6 repos. and run 'gyp_chromium' without 'content/content.gyp'. I'll update the build instructions in the wiki.

**Comment by rogerwang** [comment]
It should be helpful to check the official build log as well: http://buildbot-master.node-webkit.org:8010/waterfall

**Comment by MikeGCV** [comment]
That last link helped. An updated build instrutions would be great. Thanks!
