### ISSUE TITLE
Window opened in bg-script can't require() relative paths

### ISSUE THREAD

**Issue by polpo** [nwjs/nw.js#3467]
I am using `bg-script` in my manifest. In the script file, I open a new NW window with `gui.Window.open()`. In JS code for that window, I do a `require('./reqtest.js');` but get `Error: Cannot find module './reqtest.js'`.

I've noticed that the URL in the title bar for the new window is `chrome-extension://[random string]/test.html` and in the Sources tab of devtools, my `reqtest.js` file does not exit, either in the [random string] location or (no domain) location.

I can `require()` a module that is in `node_modules` and that works fine, and the contents of `node_modules` shows up in the (no domain) location in the Sources tab of devtools.

**Comment by snymax** [comment]
I am also experiencing this issue is there any way to pass the node-context on to the newly opened window?

**Comment by rogerwang** [comment]
@ghostoy did your case cover this? could you please verify it?

**Comment by ghostoy** [comment]
I can't reproduce it with latest live build. And I will add test case for this issue.

**Comment by rogerwang** [comment]
No need to add case, it should be the same with normal window
