### ISSUE TITLE
Transparency support on Windows 8.1

### ISSUE THREAD

**Issue by C4Grey** [nwjs/nw.js#3469]
Sorry to disappoint, but it looks like the transparency feature is broken again...On Windows 8.1, with "transparent" flag set to true, it looks like this:
![transparency_issue](https://cloud.githubusercontent.com/assets/2578826/7611706/cd9237cc-f98e-11e4-9b91-f095e84297b9.png)
I've tried version 0.12.1(screenshot is made from the app running on it) and version 0.13.0-alpha(built on 05-12-2015). On version 0.13.0 it simply renders a non-transparent window(but the frame doesn't look like DWM is not working, as it can be seen on the screenshot above).
I am choosing between CefSharp and nw.js to use in my new project and a possibility to use a transparent window with a native frame is required for it. Is there any possibility to fix this issue(I mean, some ideas where the problem is)?

**Comment by baconface** [comment]
I cannot duplicate the issue. Can you make sure these are set in your package.json?
```
"frame": false,
"toolbar": false,
"transparent": true,
```

**Comment by baconface** [comment]
I reread your issue. Transparency for the frame is only possible with setting frame to false in your package.json.

**Comment by C4Grey** [comment]
Thank you for the answer. Yes, I need a transparent html body on top of an opaque frame...anyway, maybe there should be some reference to the such behaviour in the [project wiki](https://github.com/nwjs/nw.js/wiki/Transparency)?

**Comment by baconface** [comment]
Ah I see now. I don't know how the behavior can be changed to get an opaque frame and transparent body nor have I came across anything showing this as possible.

**Comment by baconface** [comment]
One thing I do know is the 8.1 window system is really weird with NW.js particularly with frames. I posted issue #3421 not long ago. And during my research in the issues I have found #383 implying frames have been a constant quirk.

**Comment by C4Grey** [comment]
Just has tested this feature on the [Electron](https://github.com/atom/electron) - works like a charm, at least on the Windows 8.1.
![electron](https://cloud.githubusercontent.com/assets/2578826/7639650/2fe01fc8-fa86-11e4-929b-9989848c60d8.png)
