### ISSUE TITLE
Integrate anonymity support by supporting native bundling of Tor binary

### ISSUE THREAD

**Issue by fpietrosanti** [nwjs/nw.js#3471]
This ticket is integrate anonymity support by supporting native bundling of Tor binary within the nw.js runtime.

Currently a very edge requirements for many web application is to be able to connect anonymous to the internet and/or to bypass censorship. 

To do that the most commonly used software is Tor, available for Linux, Windows, Mac OS X.

This ticket is to provide native support for Tor integration, by shipping it within the nw.js runtime and/or provide guidance/support for proper integration.

**Comment by baconface** [comment]
Although I like the idea I disagree that this should be part of the core. This would be much more reasonable as a fork or side project built on NW.js and not so much as added bulk users may or may not wish to have/use.

**Comment by fpietrosanti** [comment]
@baconface do you think that an npm module that does the inclusion/handling/startup of Tor would be the right way to go?

**Comment by rogerwang** [comment]
It should be integrated with something like a npm module, making it optional to developers.

**Comment by baconface** [comment]
@fpietrosanti Yes, I don't see how you couldn't package, shell and integrate with Tor. I think there are several NPM packagess out their that perform similar functionality. You could see if those work for you, create a working example, and post a boiler plate project on Github for others to use. I did a similar project using the PHP binaries and a modified NPM package to introduce PHP support to NW.js.
