### ISSUE TITLE
Cursor gets stuck inside Frameless Apps in v10 on Windows after resize

### ISSUE THREAD

**Issue by benbowentx** [nwjs/nw.js#3472]
I am encountering an issue with v0.10 of node-webkit where frameless applications cause an issue with set to be resizable.  Basically after the resize, the mouse cursor will become trapped within the application.  This only happens on Windows.

I can easily reproduce this issue with a simple test application that just has a frameless panel.  When I move the test application to node-webkit v0.11 or later the issue goes away.  I unfortunately cannot move my real application to a never version at this time.

I thought that the change made for #1978 would fix this issue, but it does not.  
I dug through the Chromium bug reports and found that a similar issue exists for Chromium frameless extensions(https://code.google.com/p/chromium/issues/detail?id=390088), however I don't know if this would apply to node-webkit apps directly.

Would it be possible to patch this on native_window_win.cc(v10 is still on M35)?  Any advice would be greatly appreciated. 
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.23.3(chrome-sample-apps/clock).

**Comment by Christywl** [comment]
close until there is more information.
