### ISSUE TITLE
iframe crash introduced in branch 12.x  on win64

### ISSUE THREAD

**Issue by mforget0** [nwjs/nw.js#3473]
i have witnessed a bug introduced in 12.1 branch on windows 64.   my application now crashes where the exact same code works properly in 11.x branch or linux 12.x (x64) versions. 

i have identified that the crash happens when i set a iframeElement.src  to whatever-string-value  
(in the webkit javascript context) 

i have also witnessed that if i console.log(iframeElement)  (so see the iframe dom node in the dev tools)  and mouse-over the iframe element in the DevTools,  nwjs crashes instantly

-- update : the crash doen't happen if the console has never been opened --
tested in 12.0 win32, 12.1 win32, 12.1 win64 ,same behavior

i am not sure what information to report on this bug, is there s process to include a "crashdump"  in my report that could help ?  let me know, thanks 
##

**Comment by MadfishDT** [comment]
check remote url, bacause of SOP(same origin policy), if you try to open page that have different origin from parent  in iframe or window.open.  nw window context make some crash.
to solve this problem you can edit package,json node-remote item like "node-remote": "http://*,https://*"

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
