### ISSUE TITLE
Nodejs & io.js merge? What now?

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3475]
Just read http://venturebeat.com/2015/05/13/node-project-spinoff-io-js-is-moving-to-the-node-js-foundation-with-a-merge-in-progress/

"In a major step toward reconciliation with the open-source project for trendy server-side JavaScript framework Node.js, the technical committee in charge of the Io.js group, which split off from the Node project several months ago, today voted to join the Node.js Foundation."

Any thoughts / ideas if we'll see nodejs for nwjs13 or is it too early to switch back ?
##

**Comment by rogerwang** [comment]
I'll see how they'll deal with v8. One of the reason NW chose IO.js is that the v8 version is updated. Our integration requires that Node uses a similar v8 version with Chromium. V8 upgrades fast with Chromium updates and it doesn't have any stable API...

**Comment by rogerwang** [comment]
See also https://github.com/iojs/io.js/issues/1451 which currently block us to update to Chromium 44.

**Comment by mscreenie** [comment]
io,js seems to offer significant speed improvements over nodejs too, the benchmarks I saw were done with server tests/benches. Interesting thread never the less.

**Comment by mscreenie** [comment]
Closing.
