### ISSUE TITLE
Disabling paste popup and caret pointer menu

### ISSUE THREAD

**Issue by askbeka** [nwjs/nw.js#3476]
I am developing kiosk app for vending machine with KeeTouch sensor on top of monitor.
And after tapping on input elements or address bar appears standard chrome paste pop up and caret pointer like this
![paste-pop-up](https://cloud.githubusercontent.com/assets/3000474/7637958/6d05cdb4-fa93-11e4-81d3-7675297844c7.png)
##

**Comment by shaynem** [comment]
This is generic behavior not nwjs specific

Googling your issue...

http://stackoverflow.com/questions/11237936/mobile-web-disable-long-touch-taphold-text-selection

**Comment by AskarovBeknar** [comment]
@shaynem Thank you for your answer. But that is not my problem, it can be solved just by <code>user-select: none</code> but none of css or javascript based solutions not working. Also I have no problem now with paste pop up, it's not showing up if there is nothing to paste. But caret pointer, that blue water drop on image, refuses to disappear.
My problem is that I have a custom keyboard and I don't know how to paste text to the specific position in input element that is under focus. And also this pointer can be dragged around inside input, and I can't imagine how to handle this ether. I know that it is a feature not a bug and I would like to use it, but... 
If you know how to do that, I will be thankful if you could point me.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
