### ISSUE TITLE
video codec support changes between builds?

### ISSUE THREAD

**Issue by jpmorrison** [nwjs/nw.js#3477]
I built popcorn time from git source, and it distributes node-webkit-v0.9.2-win-ia32.zip 

I dropped nwjs-v0.12.1-win-x64.zip in to replace nw.exe, ran popcorn time.

The app seemed to work fine and download a video torrent but was unable to play the video in nwjs 0.12.1  

is there a quick way to check the codecs built into the binary nw or ffmpeg?
have any codecs been disabled by default since 0.9.2?
##

**Comment by mscreenie** [comment]
The codecs supported by nwjs or node webkit are the same as the supported codecs as per version of Chromium. Best thing would be to see if there have been any changes with Chromium builds during the course of 0.9.2 and 12.1. If its codec support then I believe ffmpeg would be responsible for supporting codecs. AFAIK node webkit doesn't attempt to alter the supported codecs by adding or removing.

I checked to see If I could find the Chromium version 0.9.2 was built on and afraid I couldn't. One other thing to keep in mind , you can use ffmpeg's from Google's distribution of Chromium, Chrome. This contains the relevant support for common web codecs.
