### ISSUE TITLE
dns.resolve very slow in nw

### ISSUE THREAD

**Issue by liyangready** [nwjs/nw.js#3478]
**windows7 64bit && nw.js v0.12.1**

a simple demo : 
![image](https://cloud.githubusercontent.com/assets/5040076/7647622/b22b74b2-fb0a-11e4-8f6a-500ccebef0e4.png)

result:
![image](https://cloud.githubusercontent.com/assets/5040076/7647626/c0a76028-fb0a-11e4-9871-581804663ea1.png)

but if just use nodejs with same code
![image](https://cloud.githubusercontent.com/assets/5040076/7647649/2291b2d4-fb0b-11e4-9721-771433a979c7.png)

result:
![image](https://cloud.githubusercontent.com/assets/5040076/7647650/336a0318-fb0b-11e4-9f23-a3e1bade612e.png)

need help ^ ^
thanks!
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux and Windows with nwjs-sdk-v0.23.3.

**Comment by Christywl** [comment]
close until there is more information.
