### ISSUE TITLE
Shortcuts no longer binding after nw>=0.11

### ISSUE THREAD

**Issue by twolfson** [nwjs/nw.js#3479]
Google Music upgraded their UI today which required an upgrade for the nw version on my OS. After upgrading, I noticed that media key shortcuts (and all global shortcuts in general) have stopped functioning.

I created a gist a while ago which is how I ran my shortcuts. On a machine and `nw` that binds properly, the program text changes to "Shortcut activated".  With `0.10.5`, the shortcuts bound and updated the text. With `0.11.3` and `0.12.1`, the shortcuts presented no error messages but wouldn't activate when pressed.

https://gist.github.com/twolfson/9480774

My OS is Linux Mint 17.1 64 bit with Cinnamon as its desktop environment.
##

**Comment by twolfson** [comment]
I should note that I am getting failure messages if the shortcut is already bound.

**Comment by Christywl** [comment]
I try the codes in https://gist.github.com/twolfson/9480774, shortcut is activated on Linux ubuntu with nwjs-sdk-v0.23.3.

**Comment by twolfson** [comment]
This issue is 2 years old. I no longer use `nw.js`; I use `electron` instead. Closing issue. Sorry for wasting your time
