### ISSUE TITLE
Can't add menu items to window native menu (Mac OS 10.8.2)

### ISSUE THREAD

**Issue by apetrosian** [nwjs/nw.js#348]
I used prebuilt binaries (v0.3.7 — Jan 6, 2013).

Following code doesn't work on Mac OS 10.8.2: 

```
var gui = require('nw.gui');

// Create an empty menu
var myMenu = new gui.Menu({
    type:   'menubar'
});

// Append menu item
myMenu.append(
    new gui.MenuItem({
        label: 'Test'
    })
);

gui.Window.get().menu = myMenu;
```

**Comment by jimmyc1987** [comment]
@mydigitalself You were right, you just needed to go one step further with your .notation selector.

In your case:
var gitterMenu = nativeMenuBar.items[0].submenu;

you can append to that.

**Comment by reganmusic** [comment]
@mydigitalself You were right, you just needed to go one step further with your .notation selector.

In your case:
var gitterMenu = nativeMenuBar.items[0].submenu;

you can append to that.
