### ISSUE TITLE
How to prevent to maximize the window

### ISSUE THREAD

**Issue by mydansun** [nwjs/nw.js#3480]
In the package.json, I write "resizable": false. But when I double-click the element of "-webkit-app-region:drag;", the windows will be maximized!!!

My current solution is as follows

var gui = require('nw.gui');
var Window = gui.Window.get();
Window.on('maximize', function(event){
Window.unmaximize();
});

The disadvantage is that double-clicking will cause the window flashing. Do I have a better way to achieve this function?
##

**Comment by cjhanson** [comment]
It would be nice if this got fixed properly :)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
