### ISSUE TITLE
Strange tray behaviour on KDE 5

### ISSUE THREAD

**Issue by Grief** [nwjs/nw.js#3481]
https://github.com/wlaurance/slack-for-linux/issues/48
##

**Comment by Mte90** [comment]
the problem exist also in KDE 4

**Comment by nar39** [comment]
And also on Gnome-Shell, Unity and Cinnamon so the problem exists on linux :)

**Comment by 4031651** [comment]
Have same problem. Kubuntu 14.04.1 x86_64

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by 4031651** [comment]
Hi. I haven't chance to try it now.

**Comment by Christywl** [comment]
close until there is more information.
