### ISSUE TITLE
Webview question, spawning seperate process

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3482]
Are we able to spawn a separate process for each webview tag, and then destroy the element and subsequently killing / closing the associated process?
```
<webview id="ee3" partition="d3" style="width: 450px; " src="http://www.bbc.com"></webview>
```

I read inside 12.0 release notes that there is only one separate process for dealing with extra Chrome API's like webview. But in Chrome it is possible.

**Comment by rogerwang** [comment]
It should be a separate process for each of the webview. The release notes are confusing you.

**Comment by mscreenie** [comment]
@rogerwang Cheers , thank you for clarifying.
