### ISSUE TITLE
package.json not recognize

### ISSUE THREAD

**Issue by gabrielstuff** [nwjs/nw.js#3484]
Using latest build and testing : https://github.com/zcbenz/nw-sample-apps

The app won't load on `OSX 10.7.5`

Here is the command line that I run : `open -n -a nwjs ~/Downloads/nw-sample-apps-master/file-explorer/`

Any fix ?
##

**Comment by gabrielstuff** [comment]
Note that it works perfectly with nodewebkit 0.8

**Comment by Christywl** [comment]
You could open the application with nwjs directly, no need with `open `command.
`~/nwjs-sdk-v0.23.2-osx-x64/nwjs.app/Content/Mac/nwjs <app path>`

**Comment by Christywl** [comment]
close until there is more information.
