### ISSUE TITLE
Google WideVine PPAPI plug-in inside of nwjs

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3486]
How can we use WideVine PAPPI found in all Chrome versions above 38 with nwjs.

I copied the files 
widevinecdmadapter.dll
widevinecdm.dll

But the element that uses WideVine does not work, anyone shed some light on how I can see if a plugin has been loaded by nwjs?

**Comment by christomitov** [comment]
@mscreenie did you figure this out? why did you close this issue? Please let me know what you did to get this to work

**Comment by mscreenie** [comment]
Yes. I manage to get Widevine loaded with nwjs 12 using the standard plugins method that are detailed in the docs. The plug in is not included by default as with  Chrome dists.

**Comment by christomitov** [comment]
I have the chrome libwidevinecdm so's in the plugins folder , what docs are you specifically referring to? I'm also trying this in linux not windows but the linux version of nwjs 12 should have Pepper API support.. Can you please elaborate on what you did? Thanks!

**Comment by mscreenie** [comment]
AFAIK widevine is not supported in Linux? Unless you've read otherwise. Last I checked it was not supported by Linux.

**Comment by christomitov** [comment]
Pretty sure it is because I got the libwidevinecdmadapter.so and libwidevinecdm.so from my local /opt/google/chrome install. The plugins were right there, also I can watch netflix in chrome on linux so I know it works. (and furthermore I can see the components loaded in chrome://components or chrome://plugins)

**Comment by mscreenie** [comment]
That's new to me, Good news. I'll try this when I get home under Linux, but I'd suspect following the standard nwjs plugins docs would enable this. Try the console.log command for a read out of loaded plugins too. 

Which Linux distribution are you using?

**Comment by christomitov** [comment]
I'm using Lubuntu . Also, I've tried looking at navigator.plugins but there's nothing there. I'm not sure if I need to specify specific chromium-args options in my package.json , that's why I was asking if there was anything specific you did aside from dumping the files into /plugins

**Comment by mscreenie** [comment]
Can you post your full package file here?

**Comment by christomitov** [comment]
```
{
    "name": "Apptui",
    "main": "views/index.html",
    "version": "3.0.1",
    "single-instance": true,
    "window": {
        "toolbar": false,
        "frame": true,
        "show": true,
        "width": 730,
        "height": 400,
        "icon": "./images/windowsIcon.ico",
        "show_in_taskbar" : true
    },
    "webkit": {
        "plugin": true
    },
    "manifestUrl": "https://apptui.com/downloads/releases/package.json",
    "packages": {
        "mac": {
            "url": "https://apptui.com/downloads/releases/mac/Apptui.dmg"
        },
        "win": {
            "url": "https://apptui.com/downloads/releases/win/Apptui.zip"
        }
    },
    "chromium-args": "--child-clean-exit"
}
```

I think the key here is that I need some chromium args to specifically load the pepper plugins.

**Comment by mscreenie** [comment]
Looks good, Just tried loading Widevine on Windows and works as expected though I had to use non standard standalone plugin files . I'll test on Linux though not sure if I can do this any-time soon. Let us know if you find a solution.

**Comment by christomitov** [comment]
Why is this closed? the issue still exists

**Comment by christomitov** [comment]
@mscreenie can you provide the non-standard widevine dll's that you used? I want to try this on Windows for my sanity. I have not been able to get the linux .so's working

**Comment by andrewleech** [comment]
I would also love some pointers as to how you got it working @mscreenie 
The docs say ppapi is not supported, not sure if they're out of date? https://github.com/nwjs/nw.js/wiki/third-party-browser-plugins

I've tried this on windows, with "webkit": { "plugin": true } in package.json
copied widevine dll's from chrome to <app package folder>/plugins and also tried copying entire Widevine folder to the plugins folder. Starting my app package and running navigator.plugins in console shows that some plugins are getting found and used (MS Office and such) but the widevine one isn't.

**Comment by mscreenie** [comment]
Super sure I had Widevine loaded in nwjs. The non standard dll's were from the widevine installer. Had to dig around in %appdata% to find the dlls. 

I'm also quite sure I did this (Installed Widevine) inside a VM and have it somewhere. I'll attempt to find it and see if I have the project somewhere.

**Comment by mscreenie** [comment]
Widevine loaded.

![capture](https://cloud.githubusercontent.com/assets/11147410/10605087/d8cbc5da-7720-11e5-944c-5ed5431f38f5.PNG)

**Comment by christomitov** [comment]
@mscreenie Hmm.. Ya I grepped for that after installing from the widevine site, dumped it into the plugins folder with plugins enabled, but netflix won't play. I think widevine that's in chrome for DRM is different than that plugin. Are you able to play Netflix on your setup?

**Comment by andrewleech** [comment]
Ahh, I also went down that road initially. I didn't get even that far due to using a x64 copy of nwjs. 

Switching to 32 bit and grabbing npwidevinemediaoptimizer.dll from the widevine installer:
http://www.widevine.com/download/videooptimizer
gets me npwidevinemediaoptimizer.dll: version 6.0.0.12442 from 2012
This is certainly not the same as the combo of widevinecdmadapter.dll & widevinecdm.dll used in chrome. I'm not sure if it does not have the CDM capability for netflix, or it's just too old a version.

I haven't had any luck getting my hands on a Version 41 copy of widevinecdmadapter.dll & widevinecdm.dll to see if they'll work, the ones from Version 45 certainly don't work (nor would I expect them to).

**Comment by andrewleech** [comment]
There's a newer version of widevine media optimiser at:
https://support.google.com/widevine/answer/6072067?hl=en
Thanks to procmon I found it gets installed to:
C:\Program Files (x86)\Google\Chrome\Application\Plugins\npWidevineMediaOptimizer.dll
Version 6.0.0.12757  (10/06/2014)

This will also be loaded by nwjs but does not work for netflix. 

It's safe to assume that Widevine Media Optimizer != Widevine Content Decryption Module 
(seems obvious when I write it like that)

**Comment by romaincointepas** [comment]
Similar thread on the Electron project:
https://github.com/atom/electron/issues/2085 (Loading pepper plugins and EME support via CDMs)

> Starting with a build of Chromium 45 I can get encrypted Widevine media playing back by using the switch --register-pepper-plugins="widevinecdmadapter.plugin;application/x-ppapi-widevine-cdm".

PS: I'm also desperately looking for a solution to play Netflix inside nw.js.

**Comment by christomitov** [comment]
@romaincointepas I'm assuming you've already tried using [chromium-args](https://github.com/nwjs/nw.js/wiki/manifest-format#chromium-args)?

**Comment by romaincointepas** [comment]
@christomitov Yes (with nw 0.12.3 though). No idea how to build with a more recent version of chromium.

**Comment by pi-anl** [comment]
v0.13.0-alpha2 is with a newer chromium, but it doesn't appear to have any plugin support yet from my limited testing.

fwiw CEF has recently added support for widevine when proprietary_codecs is enabled: https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm
This includes automatic component download of widevine on osx and win, linux still appears to need manual copying of the libs from chrome.
I've built brackets-shell against this and have netflix working on windows in something similar but not quite a convenient as nwjs :-) 
I havent pushed my changes to support newer CEF back to mainline yet so if you want to try get it from here and follow the official brackets-shell build process: https://github.com/andrewleech/brackets-shell

**Comment by andrewleech** [comment]
v0.13.0-alpha2 is with a newer chromium, but it doesn't appear to have any plugin support yet from my limited testing.

fwiw CEF has recently added support for widevine when proprietary_codecs is enabled: https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm
This includes automatic component download of widevine on osx and win, linux still appears to need manual copying of the libs from chrome.
I've built brackets-shell against this and have netflix working on windows in something similar but not quite a convenient as nwjs :-) 
I havent pushed my changes to support newer CEF back to mainline yet so if you want to try get it from here and follow the official brackets-shell build process: https://github.com/andrewleech/brackets-shell
