### ISSUE TITLE
Node Frames

### ISSUE THREAD

**Issue by Mimerme** [nwjs/nw.js#3487]
Node frames do not appear to work properly. When I embed a local HTML file into my iFrame of index.html (declared in package.json) it does not run within the Node context.
##

**Comment by baconface** [comment]
What is the src of your iframe?

**Comment by Mimerme** [comment]
I was running my application locally, fixed by whitelisting '.html'. Something was a bit off in the documentation, I assumed Node frames were seperate DOM elements, or a certain style like '-webkit-app-region'

**Comment by baconface** [comment]
I would not white list *.html. Doing so you white list http://badhost.com/anyfile.html as well.

Try ```<local>``` or file://* instead.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
