### ISSUE TITLE
Best-practice for end-user controlled chromium-args flags?

### ISSUE THREAD

**Issue by eabovsky** [nwjs/nw.js#3488]
I'm making a somewhat graphically-heavy app, and users with different hardware configurations may benefit from being able to toggle certain GPU options, which are typically controlled via chromium-args.

So, for example, if I wanted to let the user enable/disable gpu acceleration, what is the best practice for doing that? One thought I had is to actually open the package.json file and re-write the chromium-args section from the process, then restart the app... but somehow that just doesn't smell right to me because this could cause problems with future version upgrades/etc.

Any advice?

**Comment by rdtsc** [comment]
If you don't want to modify the manifest directly, how about implementing a small loader for your app and then firing up an instance of the NW binary with the appropriate [command-line arguments](https://github.com/nwjs/nw.js/wiki/Command-line-switches)?

## Example Workflow
- Chromium command-line arguments could be stored in the user's home directory (e.g., `my-app/config.json`), Chromium's `data-path`, `localStorage`, registry, etc.
- User shortcuts to your app should be to the loader binary, and not to the underlying NW binary.
- Once the user launches your app, the loader process looks for the appropriate settings in a location specified by the first point and launches the real NW binary with the arguments it finds.

## Demo
![nw-launcher-demo](https://cloud.githubusercontent.com/assets/6773893/7673665/3cf0172e-fce6-11e4-8bb4-b6fc988dee82.gif)

Source for the demo above is available in [this Gist](https://gist.github.com/rdtsc/68479f267693d536fc38).

**Comment by eabovsky** [comment]
That's a good idea. Thanks!

**Comment by xueeinstein** [comment]
@rdtsc, awesome demo. Thanks!
