### ISSUE TITLE
Emoji followed by Unicode Variation Selector not rendered correctly

### ISSUE THREAD

**Issue by idmean** [nwjs/nw.js#3489]
It seems like neither v0.12.1 nor v0.13.0-alpha0 is able to correctly render Unicode Emojis followed by the Variation Character U+FE0F.

For instance:

✒️ (a nib) Unicode: U+2712 U+FE0F

Is rendered like this in v0.13.0-alpha0:
![screen shot 2015-05-18 at 14 26 29](https://cloud.githubusercontent.com/assets/5495918/7680778/252157a0-fd6a-11e4-8f76-da23dacd4ac6.png)

And like this in v0.12.1:
![screen shot 2015-05-18 at 14 26 53](https://cloud.githubusercontent.com/assets/5495918/7680779/254bac12-fd6a-11e4-8247-12c801a2f47b.png)

I thought this is somehow related to [this bug](https://code.google.com/p/chromium/issues/detail?id=468349) in Chromium, which should be fixed in Chromium 42. However v0.13.0-alpha0 is based of Chromium 43 and but still seems contains this bug.
##

**Comment by idmean** [comment]
Changing the font makes the characters at least visible in their non-emoji variation:

![screen shot 2015-05-18 at 14 46 56](https://cloud.githubusercontent.com/assets/5495918/7681064/bf218a3a-fd6c-11e4-97cf-8b4eaa4dc98a.png)

The Emoji version gets visible (at least on Macs) when using `Apple Color Emoji` as font, however that breaks up anything else, since this font doesn't support white spaces.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
