### ISSUE TITLE
[nw13]navigator.getUserMedia doesn't work any more

### ISSUE THREAD

**Issue by gitawego** [nwjs/nw.js#3491]
while calling this method, it throws error:

```
NavigatorUserMediaError {}
constraintName: "
"message: "
"name: "InvalidStateError"

__proto__: NavigatorUserMediaError
```

I've tried as well with this url: http://simpl.info/getusermedia/sources/, it doesn't work neither.

**Comment by rogerwang** [comment]
It's working now with the latest binary.
