### ISSUE TITLE
enterFullscreen does nothing on 64-bit Mac

### ISSUE THREAD

**Issue by Montoya** [nwjs/nw.js#3493]
Tried window.enterFullscreen with the latest nw.js (0.12.1) for 64-bit Mac OSX and nothing happens. enterKioskMode works fine though. Anyone else run into this problem? 
##

**Comment by firsara** [comment]
+1
just noticed this. works on a debug run for me when trying ./nwjs.app/Contents/MacOS/nwjs package.json but not on a compiled app. did not try on windows yet

**Comment by allenm** [comment]
Try v0.12.2 , and make sure have not set the window.fullscreen field in your package.json

**Comment by firsara** [comment]
Works for me, thanks! :+1:

**Comment by rafaelbuiu** [comment]
Removing the fullscreen option from package.json worked for me!

**Comment by Christywl** [comment]
window.enterFullscreen works fine on Mac with nwjs-sdk-v0.23.2. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
