### ISSUE TITLE
nw.js v0.12.1 64 bit version crushed on windows 8.1 of surface pro

### ISSUE THREAD

**Issue by xuanhun** [nwjs/nw.js#3494]
It can't be opened.

**Comment by divineprog** [comment]
I have also seen reports of this problem (or a similar problem). When nw.js launches a window opens and closes instantly. Starting nw.js from the command line does not show any error messages.

**Comment by LeeLarson** [comment]
I have a similar problem, on windows 8.1, but when I initially downloaded evothings studio, it actually worked and I could run and modify aps on my Ipad.  Then it stopped working and I get the behavior you see, a window opens and immediately closes.  From the cmd line, no messages occur.  I have deleted the Ap and all the data I could find and then reinstalled it and the open/close window behavior is the same.

**Comment by xuanhun** [comment]
I open nw from windbg, geted follow infos,but I do not know what should be done for next step.

Microsoft (R) Windows Debugger Version 6.3.9600.17336 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: E:\node-webkit\nwjs-v0.12.0-win-x64\nwjs-v0.12.0-win-x64\nw.exe
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
ModLoad: 00007ff6`a35b0000 00007ff6`a7078000   nw.exe  
ModLoad: 00007ffd`7b8f0000 00007ffd`7ba9c000   ntdll.dll
ModLoad: 00007ffd`7b0d0000 00007ffd`7b20e000   C:\windows\system32\KERNEL32.DLL
ModLoad: 00007ffd`78b70000 00007ffd`78c85000   C:\windows\system32\KERNELBASE.dll
ModLoad: 00007ffd`7b7a0000 00007ffd`7b8f0000   C:\windows\system32\GDI32.dll
ModLoad: 00007ffd`76880000 00007ffd`768a2000   C:\windows\SYSTEM32\WINMM.dll
ModLoad: 00007ffd`7b5a0000 00007ffd`7b5fa000   C:\windows\system32\WS2_32.dll
ModLoad: 00007ffd`7a9a0000 00007ffd`7aa4a000   C:\windows\system32\ADVAPI32.dll
ModLoad: 00007ffd`77aa0000 00007ffd`77aca000   C:\windows\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffd`79270000 00007ffd`79277000   C:\windows\system32\PSAPI.DLL
ModLoad: 00007ffd`74c70000 00007ffd`74eea000   C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.17810_none_6240b9c7ecbd0bda\COMCTL32.dll
ModLoad: 00007ffd`6c980000 00007ffd`6c98c000   C:\windows\SYSTEM32\Secur32.dll
ModLoad: 00007ffd`78c90000 00007ffd`78e6f000   C:\windows\system32\CRYPT32.dll
ModLoad: 00007ffd`7ab00000 00007ffd`7ab36000   C:\windows\system32\IMM32.dll
ModLoad: 00007ffd`75350000 00007ffd`753ba000   C:\windows\SYSTEM32\OLEACC.dll
ModLoad: 00007ffd`77a90000 00007ffd`77a9a000   C:\windows\SYSTEM32\VERSION.dll
ModLoad: 00007ffd`6c4f0000 00007ffd`6c506000   C:\windows\SYSTEM32\USP10.dll
ModLoad: 00007ffd`7af20000 00007ffd`7af74000   C:\windows\system32\SHLWAPI.dll
ModLoad: 00007ffd`6f8b0000 00007ffd`6f932000   C:\windows\SYSTEM32\WINSPOOL.DRV
ModLoad: 00007ffd`78f80000 00007ffd`79036000   C:\windows\system32\COMDLG32.dll
ModLoad: 00007ffd`7b600000 00007ffd`7b794000   C:\windows\system32\ole32.dll
ModLoad: 00007ffd`793a0000 00007ffd`79461000   C:\windows\system32\OLEAUT32.dll
ModLoad: 00007ffd`78260000 00007ffd`78281000   C:\windows\SYSTEM32\USERENV.dll
ModLoad: 00007ffd`70340000 00007ffd`704c5000   C:\windows\SYSTEM32\urlmon.dll
ModLoad: 00007ffd`7af80000 00007ffd`7b0c1000   C:\windows\system32\RPCRT4.dll
ModLoad: 00007ffd`6f670000 00007ffd`6f739000   C:\windows\SYSTEM32\WINHTTP.dll
ModLoad: 00007ffd`72920000 00007ffd`7293a000   C:\windows\SYSTEM32\dhcpcsvc.DLL
ModLoad: 00007ffd`76740000 00007ffd`76752000   C:\windows\SYSTEM32\WTSAPI32.dll
ModLoad: 00007ffd`7ab60000 00007ffd`7acd7000   C:\windows\system32\USER32.dll
ModLoad: 00007ffd`76710000 00007ffd`7673a000   C:\windows\SYSTEM32\WINMMBASE.dll
ModLoad: 00007ffd`7aa50000 00007ffd`7aafa000   C:\windows\system32\msvcrt.dll
ModLoad: 00007ffd`79470000 00007ffd`79479000   C:\windows\system32\NSI.dll
ModLoad: 00007ffd`7aec0000 00007ffd`7af19000   C:\windows\SYSTEM32\sechost.dll
ModLoad: 00007ffd`77a80000 00007ffd`77a8a000   C:\windows\SYSTEM32\WINNSI.DLL
ModLoad: 00007ffd`78b00000 00007ffd`78b11000   C:\windows\system32\MSASN1.dll
ModLoad: 00007ffd`7ad60000 00007ffd`7aeb2000   C:\windows\system32\MSCTF.dll
ModLoad: 00007ffd`79050000 00007ffd`79261000   C:\windows\system32\combase.dll
ModLoad: 00007ffd`79480000 00007ffd`7a999000   C:\windows\system32\SHELL32.dll
ModLoad: 00007ffd`78a50000 00007ffd`78a65000   C:\windows\SYSTEM32\profapi.dll
ModLoad: 00007ffd`70ad0000 00007ffd`70d97000   C:\windows\SYSTEM32\iertutil.dll
ModLoad: 00007ffd`71040000 00007ffd`7129a000   C:\windows\SYSTEM32\WININET.dll
ModLoad: 00007ffd`78b20000 00007ffd`78b6f000   C:\windows\SYSTEM32\cfgmgr32.dll
ModLoad: 00007ffd`777f0000 00007ffd`77818000   C:\windows\SYSTEM32\DEVOBJ.dll
ModLoad: 00007ffd`78920000 00007ffd`7892b000   C:\windows\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffd`76760000 00007ffd`76812000   C:\windows\SYSTEM32\SHCORE.DLL
ModLoad: 00007ffd`788b0000 00007ffd`78913000   C:\windows\SYSTEM32\bcryptPrimitives.dll
ModLoad: 00007ffd`78880000 00007ffd`788ae000   C:\windows\SYSTEM32\SSPICLI.DLL
(215c.2304): Break instruction exception - code 80000003 (first chance)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
ntdll!LdrInitShimEngineDynamic+0x330:
00007ffd`7b9b1970 cc              int     3
0:000> g
ModLoad: 00007ffd`77840000 00007ffd`7784b000   C:\windows\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ffd`776c0000 00007ffd`777e9000   C:\windows\system32\uxtheme.dll
ModLoad: 00007ffd`6f5c0000 00007ffd`6f66b000   C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
ModLoad: 00007ffd`757d0000 00007ffd`759bd000   C:\windows\SYSTEM32\dwrite.dll
ModLoad: 00007ffd`75550000 00007ffd`75571000   C:\windows\system32\dwmapi.dll
ModLoad: 00007ffd`77230000 00007ffd`7724b000   C:\windows\system32\NLAapi.dll
ModLoad: 00007ffd`62690000 00007ffd`6270e000   C:\windows\system32\audioses.dll
ModLoad: 00007ffd`789f0000 00007ffd`78a36000   C:\windows\SYSTEM32\powrprof.dll
ModLoad: 00007ffd`75e40000 00007ffd`75eb0000   C:\windows\system32\MMDevAPI.DLL
ModLoad: 00007ffd`72710000 00007ffd`72726000   C:\windows\SYSTEM32\dhcpcsvc6.DLL
ModLoad: 00007ffd`79280000 00007ffd`79336000   C:\windows\SYSTEM32\clbcatq.dll
ModLoad: 00007ffd`7b3c0000 00007ffd`7b59a000   C:\windows\system32\SETUPAPI.dll
ModLoad: 00007ffd`78f20000 00007ffd`78f71000   C:\windows\system32\WINTRUST.dll
Application "\??\E:\node-webkit\nwjs-v0.12.0-win-x64\nwjs-v0.12.0-win-x64\nw.exe" found in cache
ModLoad: 00000001`80000000 00000001`80078000   C:\windows\system32\ASProxy64.dll
ModLoad: 00007ffd`78290000 00007ffd`782e9000   C:\windows\SYSTEM32\MSWSOCK.dll
ModLoad: 00007ffd`77d70000 00007ffd`77dca000   C:\windows\SYSTEM32\WINSTA.dll
ModLoad: 00007ffd`78240000 00007ffd`78260000   C:\windows\SYSTEM32\CRYPTSP.dll
ModLoad: 00007ffd`77f30000 00007ffd`77f66000   C:\windows\system32\rsaenh.dll
ModLoad: 00007ffd`78570000 00007ffd`78596000   C:\windows\SYSTEM32\bcrypt.dll
ModLoad: 00007ffd`6c740000 00007ffd`6c7d2000   C:\windows\SYSTEM32\mscms.dll
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\windows\system32\ASProxy64.dll - 
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???
0:013> g
(215c.12d0): Illegal instruction - code c000001d (first chance)
(215c.12d0): Illegal instruction - code c000001d (!!! second chance !!!)
ASProxy64!AuthenticateLicense+0x9b:
00000001`80007f9b 0e              ???

**Comment by xuanhun** [comment]
In windows 8.1  system that does not have  ASProxy64.dll, nw runs correct。

**Comment by LeeLarson** [comment]
I don’t think this email is for me as I am not running SW on a surface pro tablet.

Lee Larson
lee@isedesign.com<mailto:lee@isedesign.com>
www.isedesign.com<http://www.isedesign.com>




On Aug 5, 2015, at 1:47 AM, 玄魂 <notifications@github.com<mailto:notifications@github.com>> wrote:


In windows 8.1 system that does not have ASProxy64.dll, nw runs correct。
