### ISSUE TITLE
CRASH CRASH - urgent fix required

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#3495]
Used (http://dl.nwjs.io/v0.12.1/nwjs-v0.12.1-win-x64.zip)

![20150520_092348](https://cloud.githubusercontent.com/assets/107349/7720874/76535222-fed2-11e4-9dc8-c59033de3d58.jpg)

Windows 8.1 Pro 64-bit machine i am using nodewebkit as a boot-loader via regedit > run. On windows boot it execute nw.exe and then crash.

Its running this following script:

```
<!DOCTYPE html>
<html>
<body style="margin:0px;padding:0px; background-color:black;"  onload="boot();" >

<script>
var gui = require('nw.gui');
var sys = require('sys')
var exec = require('child_process').exec;
var child;
var child1;
var killing = null;
var killing1 = null;


function runme(input) {
	child = exec(input, function (error, stdout, stderr) {
		sys.print('stdout: ' + stdout);
		sys.print('stderr: ' + stderr);
		if (error !== null) {
			console.log('exec error: ' + error);
		}
	});
}

function runme1(input) {
	child1 = exec(input, function (error, stdout, stderr) {
		sys.print('stdout: ' + stdout);
		sys.print('stderr: ' + stderr);
		if (error !== null) {
			console.log('exec error: ' + error);
		}
	});
	
	child1.on('exit', function(code) {
	  gui.App.quit();
	});
}

function boot() {
    runme('taskkill.exe /im chrome.exe');
	
	killing = setTimeout(function() {
		runme('lummens.lnk');
		clearTimeout(killing);
	}, 3000);
	
	
	killing1 = setTimeout(function() {
		runme1('chrome.lnk');
		clearTimeout(killing1);
	}, 3000);
}
</script>
<h1 style="color:white;">Loading....</h1>
</body>
</html>
```

**Comment by shamun** [comment]
v0.12.1, v0.12.0, v0.13.0-alpha0 all failed and crashed.

**Comment by shamun** [comment]
Please let me know which version i can use. 

I have to prepare some KIOSKs which has to run the nodewebkit as backend to controle digital-signage, automation, robotic activity. 

Need to use one which is stable and not crashing at-least.

**Comment by Strat-** [comment]
@shamun It'll be a good white before that happens. nw.js, AFAIK is mostly a volunteer effort, so if you want it stable, you'll have to chip in as well.

**Comment by baconface** [comment]
If you are looking for stability always avoid an alpha release. Alpha versions of software are never meant for production.

**Comment by shamun** [comment]
Please confirm if this is resolved. if not please confirm why. I have been waiting for a while and i am facing serious issues with bank. 

I think i have to make my own chrome version i cant wait such long for those fixes. Please kindly let me know if this issue is resolved, i have to take a decision to use nodewebkit or not.

**Comment by Strat-** [comment]
@shamun There probably hasn't been a fix issued yet. Try remolding your software for [electron](https://github.com/atom/electron), and see if that works.

**Comment by rogerwang** [comment]
@shamun does 0.13.0-beta4 still crash there?

**Comment by shamun** [comment]
@rogerwang: in windows 8.1 when i execute nw.exe nothing happens, now gui starts.

```
{
  "name": "VDAB-Plaza", 
  "main": "index.html",
  "window" : {
    "title": "VDAB-Plaza",
    "toolbar" : true, 
    "frame" : true,
    //"resizable": true, 
    "kiosk": false,
    "always-on-top": false,
    //"width":1024,
    //"height":768,
    "show": true
  }
}
```

**Comment by shamun** [comment]
Very very very strange. Few minutes it did not worked. And suddenly official Google Chrome crashed and then nw.exe started.

now its not crashing anymore. so it seems like this issue is completed. Thanks a lot.

**Comment by shamun** [comment]
@rogerwang: its now working in beta4. thanks
