### ISSUE TITLE
Webview not working when served using express server

### ISSUE THREAD

**Issue by macqm** [nwjs/nw.js#3496]
I have a very simple html file:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test express</title>
</head>
<body>
  <webview id="site" src="http://www.google.com" style="width: 800px; height: 600px;" />
</body>
</html>
```

When I use nw.js to navigate to this view using `file:///` protocol, then it works just fine. However, I used existing Express server code that is launched by nw.js. The app serves the view as a static file (using `res.sendFile(...)` ). 

The resulting DOM contains `<webview>` tag, however it seems to be ignored, nothing is displayed. Moreover, if I use `<iframe nwfaketop nwdisable ... />`, then it works OK too, but it would be great to be able to use the goodness of the webview tag.
##

**Comment by RaghavRamesh** [comment]
+1

**Comment by JahlomP** [comment]
+1

**Comment by ppoo24** [comment]
+1

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide the full sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
