### ISSUE TITLE
nw12 branch is missing 0.12.1 related commits

### ISSUE THREAD

**Issue by btjones** [nwjs/nw.js#3497]
I'm doing custom builds of nwjs using the nw12 branch and noticed that the 0.12.1 related commits are only available on the master branch. Is the nw12 branch intended to always have all 0.12.x related commits or should I be using master instead (pointing to a specific 0.12.1 commit instead of HEAD)?

Thanks!

**Comment by liyingzh** [comment]
In the ````.gclient````the url is ````https://github.com/nwjs/chromium.src.git@origin/nw12````, and https://github.com/nwjs/chromium.src/blob/nw12/DEPS#L139 currently is nw.js.git master branch. 
So, it should be master branch in content/nw after synced.

**Comment by rogerwang** [comment]
It's moved to master branch.

**Comment by btjones** [comment]
Thanks!
