### ISSUE TITLE
chooseDesktopMedia does not pull in application name in properly

### ISSUE THREAD

**Issue by eabovsky** [nwjs/nw.js#3498]
So, maybe I'm missing something, but I can't seem to get the desktop screen chooser to properly display my application name. Maybe I'm just not setting some package field that it's looking for?

Screenshot:

![image](https://cloud.githubusercontent.com/assets/1509638/7741137/64fd2850-ff30-11e4-97f6-2da7bdecc878.png)

**Comment by jtg-gg** [comment]
@eabovsky sorry, I never pass the app's string name to the UI, I've fixed it
https://github.com/nwjs/nw.js/commit/caedb6a2bec6b339fc86d0f229807aa752b11818

hopefully you can get it in the new build

**Comment by eabovsky** [comment]
Thanks! Will this be in the nightly build?
