### ISSUE TITLE
how to show toolbar v0.13

### ISSUE THREAD

**Issue by sujkh85** [nwjs/nw.js#3500]
package.json
{
	"name": "test",
	"version": "0.0.1",
	"main": "contact1.html",
	"window": {
		"title": "test",
		"toolbar": true,
		"width": 400,
		"height": 600
	}
}

**Comment by rogerwang** [comment]
toolbar is not ported to nw13 yet. For now you can launch devtools with hotkey.

**Comment by sujkh85** [comment]
thank you

**Comment by divinemanwah** [comment]
Cannot seem to show devtools even if I press F12.

**Comment by rogerwang** [comment]
@divinemanwah you need to download the sdk build.

**Comment by divinemanwah** [comment]
@rogerwang thanks for the clarification!
