### ISSUE TITLE
CSS sourcemaps crashes / detaches devtools

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#3501]
Our LESS -> CSS sourcemaps (generated in our gulp build) crashes the NW.js devtools. Devtools becomes "dettached" every time we open the window. They work fine in Chrome. Is this known? Any ideas why? I doubt it's due to the size of the sourcemap, it's not that big.

**Comment by 1j01** [comment]
This is known: https://github.com/nwjs/nw.js/issues/2738

**Comment by adam-lynch** [comment]
:+1:
