### ISSUE TITLE
menuitem key, modifiers not showing in menu

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#3504]
I have this code:

```
menu = new gui.Menu({ 'type': 'menubar' });
var menuItemFile = new gui.MenuItem({ label: 'File' });
var fileMenu = new gui.Menu();
fileMenu.append(new gui.MenuItem({ label: 'Open...', key: 'l', modifiers:'ctrl', click: function() { console.log('clicked!'); } }));
menuItemFile.submenu = fileMenu;
menu.append(menuItemFile);
gui.Window.get().menu = menu;
```

It shows the item in the menu, but without any shortcut text.
I've tried with 0.12.1 and 0.12.2
on windows vista.
##

**Comment by wotzisname** [comment]
I have this issue on Windows 8.1. Works fine on Mac.

**Comment by Christywl** [comment]
The above code works well for me on Windows with nwjs-sdk-v0.23.2. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
