### ISSUE TITLE
v0.12.1 64 bit can't start multi instances on osx

### ISSUE THREAD

**Issue by xuanhun** [nwjs/nw.js#3506]

**Comment by baconface** [comment]
In your package.json have you set single-instance to false?

**Comment by xuanhun** [comment]
Yes, I had set single-instance to false.

**Comment by matthiasg** [comment]
i get the same behavior on 0.13.0 alpha 1 on windows 64bit .. it actually closes the other running instance instead of opening a new one and single-instance is set to false.

**Comment by xuanhun** [comment]
It is osx default behavior,by using 'open -n' from command line to resolve it.
