### ISSUE TITLE
Issues with GUI not updating properly until resize.

### ISSUE THREAD

**Issue by chevex** [nwjs/nw.js#3507]
Has anyone else encountered issues like this? The following is a small frameless window app I'm building.

![render-issue](https://cloud.githubusercontent.com/assets/874394/7791136/1afa522a-0258-11e5-8988-af38d60289de.gif)

I'm using AngularJS to do a simple DOM update.

``` javascript
app.controller('trackerCtrl', function ($scope) {
  $scope.selectedZone = "deck";
});
```

``` html
<div ng-controller="trackerCtrl">
  <select ng-model="selectedZone">
    <option value="deck">Deck</option>
    <option value="hand">Hand</option>
    <option value="play">In Play</option>
    <option value="grave">Graveyard</option>
  </select>
  <h1>{{ selectedZone }}</h1>
</div>
```

The issue seems to be that the element text updates but for some reason redraws over the old value. The issue is fixed by simply resizing the frameless window slightly. After that the UI seems to redraw correctly upon further updates.

![render-issue2](https://cloud.githubusercontent.com/assets/874394/7791190/ffab6332-0258-11e5-9f16-0a61bb7590a7.gif)

I've been able to fix this in a few other places by programmatically resizing the nw window.

``` javascript
logWatcher.on('game-start', function (player) {
  $scope.$apply(function () {
    $scope.playerName = player.name;
    mainWindow.resizeTo(mainWindow.width, mainWindow.height + 1);
    mainWinow.resizeTo(mainWindow.width, mainWindow.height - 1);
  });
});
```

That worked but in the first example you'll notice there isn't a place where I manually update the scope variable. I just set `ng-model` on the `<select>` element and bind to the value in the `<h1>` element. I'm not sure where to inject my little hack. Though obviously I'd prefer to not need this hack at all if I can.

Any ideas?
##

**Comment by chevex** [comment]
PS - Angular is loaded via a `<script>` tag when the app starts up, but then all the controllers are loaded via calls to `require`.

Here is the index file that initializes the app: https://github.com/codetunnel/hearthtunnel-deck-tracker/blob/master/src/index.jade

**Comment by chevex** [comment]
I spent all evening re-creating my app from scratch piece by piece until the issue appeared. I've narrowed it down to the angular-animate library. I am using it to animate my views when the route changes, like this:

![render-issue3](https://cloud.githubusercontent.com/assets/874394/7793353/16cc8290-027b-11e5-8894-01078b9a876f.gif)

Notice the issue is present after the animated view change. Now here is the same view change without animation:

![render-issue4](https://cloud.githubusercontent.com/assets/874394/7793384/73368a8a-027b-11e5-8e30-f837a2c475b2.gif)

So I've at least narrowed it down to the animation library. Anyone know what is happening here? The relevant animation rules for this view change can be found here: https://github.com/codetunnel/hearthtunnel-deck-tracker/blob/master/src/css/app.styl#L100-L111

**Comment by chevex** [comment]
Well, I still don't know why the animation causes this strange behavior. Discovering that the route change animation triggers this glitch,and knowing that a single resize of the nw window rectifies the problem until another route change, the following hack seems to work.

```javascript
app.controller('mainCtrl', function ($rootScope, mainWindow) {
  $rootScope.$on('$routeChangeSuccess', function () {
    mainWindow.resizeTo(mainWindow.width, mainWindow.height + 1);
    mainWindow.resizeTo(mainWindow.width, mainWindow.height - 1);
  });
});
```

If anyone is able to explain this strange glitch I would be very grateful. For now, this hack works if you're experiencing similar issues and can't seem to solve the render bug.

**Comment by rogerwang** [comment]
Thanks for reporting. Could you please upload your case somewhere so I can try it?

**Comment by chevex** [comment]
The best way is going to be to clone my repo and run it. I've had trouble duplicating the issue in isolation. I've made a special branch with my hacks removed so the issue can be reproduced.

1. `git clone https://github.com/codetunnel/hearthtunnel-deck-tracker.git`
2. `cd ./hearthtunnel-deck-tracker`
3. `git checkout render-bug`
4. `npm install`
5. `gulp build`
6. `npm start`

Then just do what I do here:

https://www.youtube.com/watch?v=XwJsukygaSY

This issue definitely isn't unique to this one place, it just happens to be where I've reliably recreated it for testing.

After running the `gulp build` task the app will be built into the `/build` directory. If you're looking to tweak or debug things, you can fiddle around in that directory. Just be aware that running `gulp build` again will blow away any changes in the build directory.

The commented out event handler [here](https://github.com/codetunnel/hearthtunnel-deck-tracker/blob/render-bug/src/js/controllers/main.js#L20-L26) is the hack that seems to fix the bug. Simply uncomment that code and you'll notice things render correctly.

**Comment by CareyJWilliams** [comment]
Possibly related, I've had a few issues with certain elements using font-awesome icons not displaying them until the window is resized, though I've not noticed any patterns as of yet.

**Comment by Christywl** [comment]
I try to reproduce this with the above steps, but the app UI is different from the screenshot in the bug, so I can't check this issue. Is this issue still reproduced in your side with the latest nwjs build?

**Comment by CareyJWilliams** [comment]
I haven't experienced this issue recently (touch wood). Currently using 0.21.4.
