### ISSUE TITLE
nwjs-v0.13.0-alpha0-win-ia32   can not excute alert("1");

### ISSUE THREAD

**Issue by xland** [nwjs/nw.js#3508]
package.json:
{
  "name": "nw-demo",
  "version": "0.0.1",
  "main": "index.html"
}

index.html:
![1](https://cloud.githubusercontent.com/assets/2980915/7792373/16c5daa8-02e4-11e5-98cf-5ba24a077cd3.png)

System Environment:
windows 8.1  x64
user: administrator

description:
alert box  does not show!
##

**Comment by rogerwang** [comment]
It will be fixed in alpha1. Thanks.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.

**Comment by xland** [comment]
ok！close it~
