### ISSUE TITLE
PDF Plugin on Windows

### ISSUE THREAD

**Issue by docteuri** [nwjs/nw.js#351]
Dear All

I tried, tried and tried again, but I can't find the right pdf.dll plugin to put in the plugins directory of my app before zipping.

On Windows, the pdf.dll of Chrome 25 is not recognizer when I type navigator.plugin on console. the plugin is not in the list.

On Mac, the plugin is in the list, but the pdf can't display : Can't load plugin.

You help would be great.

Thanks a lot

Edouard

**Comment by rogerwang** [comment]
should be fixed with 0.13.0 RC.
