### ISSUE TITLE
nwjs-v0.13.0-alpha0-osx-x64 How to package for distribution? app.nw files are ignored!

### ISSUE THREAD

**Issue by zachstronaut** [nwjs/nw.js#3510]
The OSX package+distribute instructions don't appear to work with nwjs-v0.13.0-alpha0-osx-x64.  Placing an app.nw folder with application files (index.html, package.json, etc) in Contents/Resources/ inside the nwjs.app doesn't work.  It appears to be ignored, and instead you get the default grey window with the animated nw.js message.

Similarly, I tried the Windows packaging process as well, and the app files are also ignored there.

What's the proper packaging for distribution process for 0.13?

**Comment by rogerwang** [comment]
Thanks for reporting. Will fix this soon.

**Comment by zachstronaut** [comment]
Excellent!  Let me know if you need any information on reproducing this problem, but it sounds like you've identified the issue.

Thanks!

**Comment by ToddG** [comment]
Seeing similar behaviour on linux. 

Repro: 

1. Created the app mentioned in QuickStart (https://github.com/nwjs/nw.js/).

nwjs-app
├── index.html
└── package.json

2. Launch directly

```bash
$ cd nwjs-app
$ ~/bin/nwjs/nwjs-v0.13.0-alpha0-linux-x64/nw .
```

App launches as expected in a window.

3. Package per instructions at https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps

3.a Create the nw zip file

```bash
$ zip -r ../${PWD##*/}.nw *
```

3.b Concatenate 

```bash
$ cat ~/bin/nwjs/nwjs-v0.13.0-alpha0-linux-x64/nw nwjs-app.nw > app
$ chmod +x app
```

4. Copy other resources from distribution ... (copied them all)

```bash
$ cp -rv ~/bin/nwjs/nwjs-v0.13.0-alpha0-linux-x64/* .
```

Resulting directory structure...

```bash
├── app
├── credits.html
├── icudtl.dat
├── libffmpegsumo.so
├── locales
│   └── en-US.pak
├── natives_blob.bin
├── nw
├── nw_100_percent.pak
├── nwjs-app
│   ├── index.html
│   └── package.json
├── nwjs-app.nw
├── resources.pak
└── snapshot_blob.bin
```

5. Just getting the grey screen...

Output below:

```bash
[todd@lnx-todd nwjs-testing-alpha]$ ./app
[0601/153138:INFO:nw_package.cc(174)] ./app
[24874:24874:0601/153138:ERROR:url_pattern_set.cc(240)] Invalid url pattern: chrome://print/*
LaunchProcess: failed to execvp:
[24901:24901:0601/153138:ERROR:sandbox_linux.cc(342)] InitializeSandbox() called with multiple threads in process gpu-process
[24901:24901:0601/153138:ERROR:sync_control_vsync_provider.cc(60)] glXGetSyncValuesOML should not return TRUE with a media stream counter of 0.
[24901:24901:0601/153138:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D018D0E8A32B0000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
```

**Comment by rogerwang** [comment]
merge with #3460
