### ISSUE TITLE
Build nw.js with Sparkle Framework [$75]

### ISSUE THREAD

**Issue by btjones** [nwjs/nw.js#3514]
I am trying to do a custom build of nw.js with [Sparkle](https://github.com/sparkle-project/Sparkle).

I am building nwjs 0.12.2 on a mac and am having trouble getting it to build with Sparkle. I believe it is probably related to framework search paths in nw.gypi. When I add `#import <Sparkle/Sparkle.h>` to `src/browser/native_window_mac.mm` and build I get "fatal error: 'Sparkle/Sparkle.h' file not found".

You can see the changes I've tried to make to nw.gypi here: https://gist.github.com/btjones/dd85898f662ce6ab7d40/revisions

I've also tried lots of variations on the above changes to nw.gypi with no luck.

The one thing that is working properly is the copy task because when I remove the #import from native_window_mac.mm and build nwjs.app successfully, the framework is in the proper place (nwjs.app/Contents/Frameworks/Sparkle.framework).

Ideally I wouldn't need to put the framework in `/Library/Frameworks` and could instead use @loader_path (or whatever) so that I can store the framework in my project / repo and use a relative path.

What I need is to be able to compile with the framework in place when I add `#import <Sparkle/Sparkle.h>` to `src/browser/native_window_mac.mm` and the bounty is yours. I can take it from there. Thanks!

**Comment by cgrossde** [comment]
Were you able to get this working?

**Comment by btjones** [comment]
No not yet (though I've put this issue aside for a while).
