### ISSUE TITLE
Frameless window resize glitch

### ISSUE THREAD

**Issue by suns-echoes** [nwjs/nw.js#3515]
There is a noticable glitch when resizing frameless window. Before content resizes it is possible to see frame of normal windows window. It is constant behavior (console on and off, page blank or with content), see screenshot below:

![err](https://cloud.githubusercontent.com/assets/12611018/7813525/3b84d3b6-03bc-11e5-941d-c1053248a5c9.png)

OS: Windows 7 64bit
NWJS: 12.0, 12.1, 12.2
##

**Comment by VINTproYKT** [comment]
Such behavior is in browsers too. I think it's manufacturing issue. If your app is not supposed to do online stuff or use many features of NW.js that are not presented in other alternatives, it's good time to think about target and to use alternative. :key: :thought_balloon:

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
