### ISSUE TITLE
Frameless window shadow.

### ISSUE THREAD

**Issue by suns-echoes** [nwjs/nw.js#3516]
When I open frameless window it does not have shadow, but when I maximize it and then unmaximize, shadow is fixed.

OS: Windows 7 64bit
NWJS: 12.0, 12.1, 12.2
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
