### ISSUE TITLE
How to get the current directory?

### ISSUE THREAD

**Issue by tosone** [nwjs/nw.js#3521]
I want to build some data on the current directory ? But how to get the current directory? 
console.log(__dirname)
I try that, but it doesn't work.
I want a little help.

**Comment by tosone** [comment]
Some temp files were built in the temp directory when it work on. How to get the real dirname?

**Comment by baconface** [comment]
```javascript
var path = require("path");
```

**Comment by baconface** [comment]
Just so you know your project is compressed, packed, and concatenated into the binary. So when it runs it will unpack to a temp directory in order to be accessed.

Get path of project directory (temp dir):
```javascript
console.log(process.cwd());
```

Get path of project binary:
```javascript
var path = require("path");
console.log(path.dirname(process.execPath));
```

**Comment by jingn** [comment]
It seems that your problem have been solved！

**Comment by fritx** [comment]
```
process.cwd()
```
