### ISSUE TITLE
Resize coordinates appearing while resizing window

### ISSUE THREAD

**Issue by ip** [nwjs/nw.js#3522]
Top right corner. Is it possible to hide it?

![](http://i.imgur.com/dMBlsfd.png)
##

**Comment by baconface** [comment]
This is caused when the developer tools are opened. If you do not intend on showing the developer tools for production use you should be okay.

However I second asking how to hide it. I am writing several projects with developer tools in an iframe. They are jailed to monitor another iframe. Even with nwfaketop assigned to the jailed iframe it still shows on my parent window. It would be nice to either suppress this or make it show in the jailed iframe instead.

**Comment by needhash** [comment]
@baconface Thanks very much. I am not familiar with native side of nw.js but guess it is just HTML element running in some isolated context, like Chrome UI, so it should be possible to hide it with "display: none" style.

**Comment by baconface** [comment]
I figured that might be the case. Just unsure of the element selector I need to set it to. Be nice to move it to the  iframe though. I think that could be done via JavaScript but it would give the size for the window and not the frame. Might require more hacking at the devtools core than what its worth.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
