### ISSUE TITLE
When window is in fullscreen, hide window doesn't work well on Mac

### ISSUE THREAD

**Issue by rnons** [nwjs/nw.js#3523]
When window is in fullscreen state, if I call `window.hide()`, it leaves a black screen there.

If I call `window.leaveFullscreen(); window.hide()`, the leaveFullscreen animation seems to block window.hide() 
Listen to the `leave-fullscreen` event, then call `window.hide()` also failed to hide window.

How to ensure window.hide() works well when in fullscreen?

**Comment by baconface** [comment]
First avoid calling it ```window```. ```window``` is a JavaScript global and calling it this might cause conflicts.

It would be safer to use the following:
```javascript
var gui = require('nw.gui');
var win = gui.Window.get();
```

As a work around have you tried to add a timeout to the ```win.hide()```?

This example will fire leaveFullscreen and then wait a second to hide it:
```javascript
winleaveFullscreen();
setTimeout(win.hide, 1000);
```

**Comment by rnons** [comment]
I know I can possibly use setTimeout, but I don't believe it's a reliable way.

**Comment by baconface** [comment]
I can agree with that. But does it work? It could give a little insight on what is happening. Such as the window is unavailable for a short period of time.

**Comment by rnons** [comment]
Yes it works.

**Comment by rnons** [comment]
One second delay is not reliable. I ended up using two seconds delay

**Comment by porsager** [comment]
Why was this closed? I don't think a setTimeout hack is a proper solution?
