### ISSUE TITLE
Window Selection text input problem in macOSX Yosemite

### ISSUE THREAD

**Issue by jfarid27** [nwjs/nw.js#3527]
NWJS version: 64bit nwjs-v0.12.2

I was having trouble with window selection where running an app from a symbolically linked nwjs would not allow me to type within the application. The text for some reason would be diverted to the terminal. The workaround was dump the contents of the nwjs folder directly into the application and specifically call

``` bash
./nwjs.app/Contents/MacOS/nwjs .
```

I'm sort of new to the nwjs but apparently this is an issue and I want to log it. Feel free to comment for more information about any other details.
##

**Comment by felixSchl** [comment]
I am experiencing the same issue on OSX 10.11.3. The workaround is not doing it for me either.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
