### ISSUE TITLE
Checkbox icon toggle

### ISSUE THREAD

**Issue by JahlomP** [nwjs/nw.js#3530]
Regarding checkbox menuitem type, wont it be ok for the checkbox icon to display if checked == true and hide icon if checked == false?
item = new gui.MenuItem({ label: 'Simple item', type: checkbox});
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
