### ISSUE TITLE
How to build v0.10.5 nw

### ISSUE THREAD

**Issue by Johnbug** [nwjs/nw.js#3533]
##

**Comment by Johnbug** [comment]
I'm working on win7 64bit.
I get the code @origin/nw12 following https://github.com/nwjs/nw.js/wiki/Building-nw.js. And I build the nw12 successfully. Now I want to build version 0.10.5, I checkout the tag with v0.10.5. and run glient sync but It does not work. This is the error message:

Error: Command svn checkout https://github.com/nwjs/chromium.src.git@origin/trun
k/deps/canvas_bench@122605 d:\nwjs\src\chrome\test\data\perf\canvas_bench --revi
sion 122605 --non-interactive --ignore-externals returned non-zero exit status 1
 in d:\nwjs

I try to run ./build/gyp_chromium content/content.gyp
but it does not work either.

So how can I build?

And I wonder how to to get the v0.10.5 symbols? And How to analysis the dump file?

**Comment by chaseWillden** [comment]
Do you still have issues?

**Comment by Christywl** [comment]
Is this issue still reproduced now?

**Comment by Christywl** [comment]
close until there is more information.
