### ISSUE TITLE
Frameless + Maximize / Minimize does not keep the current route. 

### ISSUE THREAD

**Issue by gbraga** [nwjs/nw.js#3534]
I'm using AngularJS v1.3.15 and NW v0.12.1 with Windows 7 SP1 64 Bits.
My application have a problem with window operations. When I called win.maximize() or anyone, the route change to Index.

I think that var win = nw.Window.get(); see the index as your current window, because the window.location.path refers to index.

However, if I keep frame = true in my package.json, the frame buttons work perfectly.
The behavior of object window is different of nw than native frame.

**Comment by Paxa** [comment]
Has duplicate https://github.com/zcbenz/nw-sample-apps/issues/29

**Comment by gbraga** [comment]
Sorry, I discovered the problem.
I remade my solution to be equal the examplo that I found (http://nodehead.com/node-webkit-custom-window-controls-26/).

In this example he uses <a href='#'></a>... This is the problem, but with one page (case of example) work perfectly.
I will close the issue.
Thanks!
