### ISSUE TITLE
app:// protocol under nw.js 0.13 alpha breaks, nw.js asks to launch local application via xdg-open 

### ISSUE THREAD

**Issue by DanielJoyce** [nwjs/nw.js#3535]
app:// no longer works properly on nw.js 0.13 on linux. Instead triggers popup asking to launch local application.

  "main": "app://whatever/index.html",

Would cause nw.js 0.13 to trigger a popup asking to launch a local application called "whatever"
##

**Comment by rogerwang** [comment]
Hi Daniel,

For now you can use the 'chrome-extension://' protocol to replace app protocol -- just write "main":"index.html" then it will be loaded via 'chrome-extension://' protocol by default.

**Comment by gleitz** [comment]
@rogerwang thanks for this info. I believe the "app://" protocol also allowed the file to be treated as a local file and thus had access to Node functionality.

When I switch to "main": "index.html" I get errors in the developer console like "Uncaught ReferenceError: require is not defined" for a line that includes `require('nw.gui')`

Is there a new way in 0.13 to allow Node access?

**Comment by gleitz** [comment]
I also saw [this issue](https://github.com/nwjs/nw.js/issues/3993) which partially answers my question. It would be nice to have a small page on the proposed and/or current breaking changes in nwjs13

**Comment by rogerwang** [comment]
If you're writing a NW app rather than Chrome app, then Node is available through the chrome-extension protocol.

**Comment by rogerwang** [comment]
btw, now we support 0.12 APIs on top of 0.13 API (nw.require() etc ) with a wrapper. You could try it now.

**Comment by scottdarch** [comment]
To use chrome-extension how do we get the extension name for our app?

**Comment by Christywl** [comment]
Any problems for this now? If no problem, let's close it.

**Comment by Christywl** [comment]
close until there is more information.
