### ISSUE TITLE
Non interactable 5pixel margin around window

### ISSUE THREAD

**Issue by serpent666** [nwjs/nw.js#3536]
Tested and replicated on 3 different computers running windows 7, and nwjs v0.12.2(x64) and nwjs v0.13.0 alpha 0 (x64), there is no issue on chrome/firefox (even F11 fullscreen)

Pretty much, no matter what i can do, every app (window/frameless/fullscreen/kiosk) has a 5 pixel border around the edges that cannot be interacted with.

i have used css reset \* { margin: 0; padding: 0; } and it is still there, almost seems like a webkit issue
I created a simple example to copy and try
https://jsfiddle.net/rv35ksde/9/

i know its only 5 pixels, but since i am creating a program on an old touchscreen computer that is only 1024 x 768, id like to be able to use ever pixel
##

**Comment by serpent666** [comment]
Half solved by removing the frame option in the package.json as per the wiki's instruction
https://github.com/nwjs/nw.js/wiki/Manifest-format#fullscreen

still an issue when in a window but fullscreen works fine now.

**Comment by VINTproYKT** [comment]
I think it needs to be corrected as soon as possible. It "makes glitches" by UX. At the time there is only one solution: make margin in `body`, so custom window controls will not be overlapped by mysterious invisible window border.

**Comment by Christywl** [comment]
Seem I can't reproduce this issue on nwjs-sdk-v0.23.1. I check it with 
`nw --url=https://jsfiddle.net/rv35ksde/9/`

**Comment by Christywl** [comment]
close until there is more information.
