### ISSUE TITLE
input type="date" Spin button issue

### ISSUE THREAD

**Issue by navinkrishnan** [nwjs/nw.js#3537]
Hi,
I have been using node-webkit / nw for my project. Found an issue on using the spin button in
 `<input type="date"/>`

When using the spin button decrement it produces the junk values.

The initial component

![date_1](https://cloud.githubusercontent.com/assets/5877724/7938497/75a15680-0963-11e5-8725-e03008e670f6.JPG)

On pressing the decrement spin button

![date_2](https://cloud.githubusercontent.com/assets/5877724/7938503/836b699a-0963-11e5-8d38-c7a6c6ed0e27.JPG)

The expected result should be `2014` but the actual result `275760`

I have verified the same issue occurs in all different versions (v0.10.0, v0.10.5, v0.11.0, v0.11.6, v0.12.0)

We have already moved this project to production, so switching to a jQuery datepicker will not be a good option at this time.

Any solution for this issue will be appreciated. Thanks 
##

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.23.1. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
