### ISSUE TITLE
nw.js 0.13.0alpha: window icon not working

### ISSUE THREAD

**Issue by scotttesler** [nwjs/nw.js#3539]
The icon property in window (https://github.com/nwjs/nw.js/wiki/Manifest-format#window-subfields) does not seem to be taking effect in nw.js 0.13.0alpha.
##

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.23.1. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
