### ISSUE TITLE
nw.js application bootstrap slow

### ISSUE THREAD

**Issue by jabez128** [nwjs/nw.js#3544]
nw.js is cool, but I find that nw.js application is very slow when bootstrap, it will take a while after I double click the app icon and before I can see the app interface. is there some method to short bootstrap time?
##

**Comment by baconface** [comment]
Are you loading just bootstrap or do you have a massive app in it? When you click that icon NW.js decompresses your .nw file to a temp dir. The bigger you make that .nw file the longer it takes to decompress. I found it quicker to keep node_modules and large resources outside of that and put them in my app's binary root instead.

I have a bootstrap app. Minor wait for it to load up but I wouldn't call it slow. How many seconds or minutes does it take for it to load?

**Comment by divinemanwah** [comment]
@baconface I think what he meant by *bootstrap* was the "starting-up" phase or "boot up"of his app. Please correct me if I'm wrong though.

**Comment by ra00l** [comment]
On windows, unpacking the zip happened EVERYTIME you ran the app. So it introduces a huge bottleneck.

The way I solved this (on windows, btw) was to distribute the app unpacked. 

Just copy the nw files into the app directory. Then, simply click the nw.exe app, and you're good to go.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
