### ISSUE TITLE
Can't assign hotkey to F9, F10 or F12

### ISSUE THREAD

**Issue by baconface** [nwjs/nw.js#3545]
NW.js fails to register a hot key to F9, F10, or F12. F1-F8 and F11 work fine.
```javascript
var gui = require('nw.gui');
var testhotkey = new gui.Shortcut({
	key: "F12",
	active: function() {
		alert('If you see this it worked!');
	},
	failed: function() {
		alert('If you see this it failed. :(');
	}
});
gui.App.registerGlobalHotKey(testhotkey);
```

**Comment by baconface** [comment]
Forgot to mention this is with NW.js 0.12.1.

**Comment by mscreenie** [comment]
Having same issue but 12 is no longer supported. @baconface A little off topic but have you moved from nwjs to electron? Don't see you here as much here as before.

**Comment by baconface** [comment]
@mscreenie Yes, I have completely switched to Electron.

Additionally I found out Electron had similar issues because it would not reassign an already assigned key by another program. Since I didn't mind that my program had to be in focus I used regular JavaScript key events and avoided hotkeys altogether. You can use JavaScript key events for the F keys on NW.js as well.

**Comment by mscreenie** [comment]
Thanks for that will try it.! Seeing you've used and presumably switched an app from nwjs to electron how easy was it and are issues quickly fixed? Shamefully off topic I know.
