### ISSUE TITLE
Issue with how some elements show up when being printed

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#3548]
I've got an element on a page that looks like this when viewed in chrome:
![](http://i.imgur.com/8bEWLyO.png)

I know that there are issues with gradient backgrounds when printing, so I've applied a @print css selector to change all the backgrounds to solid colors as well as take any text-shadow and text-decoration away when being printed.

When I print in chrome, I get this:
![](http://i.imgur.com/4f6z2pD.png)

When I print in node-webkit, I get this:
![](http://i.imgur.com/z23Frf8.png)

What's going on with the text in the node-webkit version?

Edit: When adding a color of black to the css elements that have the white boxes, I see the black text over the white box.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?
