### ISSUE TITLE
After gui.App.setProxyConfig Devtools show Empty 

### ISSUE THREAD

**Issue by bestplay** [nwjs/nw.js#3549]
With 12.0 & 12.2 for win7 32bit .
And  operating system is win7 64bit.

After set proxy by setProxyConfig. and proxy works good.
But Devtools show Empty.

My proxy string pass to setProxyConfig is : 
"http=192.168.2.2:8087;https=192.168.2.2:8087;socks=direct://"   OR
"http=192.168.2.2:8087;direct://" 

Both cause the same result.

Remote debugging via local socket?
And how can I passby the local socket for remote debugging?
## Another issue:

Sometimes it crash without any notify. Just quit the program while doing websocket connection,
or other http connection with Bad Network or wrong proxy setting.

Thanks !
##

**Comment by mcutalo88** [comment]
Im running into the same issue. @bestplay have you found a workaround for this?

**Comment by tkang007** [comment]
When you use "direct://;http=192.168.2.2:8087" instead of "http=192.168.2.2:8087;direct://",  it will be solved in my case. But some delay can be happend when direct accessing is not possible for proxy required systems. 

Is there any way to set no_proxy option at nwjs ?  I think it will be better then direct option.

**Comment by tkang007** [comment]
Does anybody try to use --proxy-bypass-list chronium option to bypass proxy for localhost or internal network systems at nwjs ?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a full sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
