### ISSUE TITLE
nw13 devtools not showing

### ISSUE THREAD

**Issue by divinemanwah** [nwjs/nw.js#3554]
The title says it all. Even if I press F12.

I'm using **nwjs-v0.13.0-alpha0-win-x64** (not the **sdk** version)

**Comment by rogerwang** [comment]
thanks. but devtools is supposed to be removed in non-sdk build. please use the sdk build for development.

**Comment by divinemanwah** [comment]
thanks for the clarification!

**Comment by GastonFerrari** [comment]
Can you tell me how to build the SDK build?

**Comment by rogerwang** [comment]
define `nwjs_sdk=1` when you run `gyp_chromium`

**Comment by jetiny** [comment]
@rogerwang how to define nwjs_sdk=1 when you run gyp_chromium
I can not build sdk version even if 

    set DEPOT_TOOLS_WIN_TOOLCHAIN=0
    set GYP_DEFINES="clang=0 nwjs_sdk=1 disable_nacl=0"
    set GYP_MSVS_VERSION=2013
    set GYP_GENERATORS=ninja

The resources.pak is 7mib only and the locales dir only have one en-US.pak file 

ninja dist output nwjs-v0.14.5-win-ia32.zip

**Comment by rogerwang** [comment]
@jetiny the trick of setting GYP_DEFINES in windows is that you need to remove the double quote and keep the space:

set GYP_DEFINES=clang=0 nwjs_sdk=1 disable_nacl=0

**Comment by jetiny** [comment]
@rogerwang  ok and thanks, I will try again later.
