### ISSUE TITLE
Option to hide only the address bar

### ISSUE THREAD

**Issue by plentz** [nwjs/nw.js#3557]
I wish that we have the option to show the back/refresh buttons but not the address bar(I don't want my users to know what is the url)
##

**Comment by plentz** [comment]
(probably what #1675 meant but wasn't clear enough)

**Comment by RIAEvangelist** [comment]
I started pseudo coding you an answer and just decided to build a browser "framework"

You can do what you want as can #1675 with my [nwjs browser repo](https://github.com/RIAEvangelist/nwjs-browser-framework)

your browser.config.json would be :

    {
        "homepage": "google.com",
        "name": "nw.js browser framework",
        "showDevTools":false,
        "header":{
            "navigation":true,
            "refresh":false,
            "dev":false,
            "address":false
        }
    }

here is an example of a full address bar :
![full browser](http://i.imgur.com/xHfzdua.png)

her is an example of what your looking for (the config above gave this) :
![only back forward browser](http://s15.postimg.org/xmn0xl2fv/Screenshot_from_2015_06_12_00_54_41.png)

**Comment by RIAEvangelist** [comment]
updated so you can control back & forward independently.

    {
        "homepage": "google.com",
        "name": "nw.js browser framework",
        "showDevTools":false,
        "header":{
            "back":true,
            "forward":true,
            "refresh":false,
            "dev":false,
            "address":false
        }
    }

**Comment by plentz** [comment]
@RIAEvangelist awesome. that's exactly what I wanted. Do you mind creating a PR to this repo?

**Comment by RIAEvangelist** [comment]
which repo?

**Comment by RIAEvangelist** [comment]
Unless you mean to my repo. By all means, please do.

**Comment by Christywl** [comment]
Seems RIAEvangelist's codes work well. Could we close this issue now?

**Comment by Christywl** [comment]
close until there is more information.
