### ISSUE TITLE
Unable to set transparent background in fullscreen or kiosk mode

### ISSUE THREAD

**Issue by mizhigang407** [nwjs/nw.js#3562]
I want to set transparent background in the kiosk mode ,or the fullscreen mode,but it's no way,Only I can see is black background. It works well in frameless window,but it seems  cannot set transparent in kiosk or fullscreen mode.
Is it unable to access browser settings in fullscreen or kiosk mode?
I just want to create a transparent layer cover the whole screen,and use canvas to draw something.

**Comment by ghostoy** [comment]
@mizhigang407 Try adding `--disable-gpu` in `chromium-args` field in package.json.

**Comment by mizhigang407** [comment]
yep,it's ok,thanks
