### ISSUE TITLE
"Download dialog" when header data was send

### ISSUE THREAD

**Issue by meron1122** [nwjs/nw.js#3565]
Table export plugin - http://ngiriraj.com/pages/htmltable_export/demo.php
Use header `data:application/<type>` to send exported data to download dialog.
when i use this plugin nw.js only open a empty window, so, download dialog is not implemented?
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
