### ISSUE TITLE
"-webkit-app-region: drag" Does not work unless the window loses focus and regains focus.

### ISSUE THREAD

**Issue by gridwalk** [nwjs/nw.js#3568]
Discovered in v 0.12.2 
Mac OS X

I'm using the frameless window setup as [described here](https://github.com/nwjs/nw.js/wiki/Frameless-window). When I open my app the draggable regions do not respond to dragging. If I click outside to the desktop or another app and return to my app the draggable regions work fine.

I discovered it after updating NWJS from version 0.12.0.
##

**Comment by forhappy** [comment]
I have met the same problem too, my nw.js version is 0.12.2, Mac OS X 10.10.3

**Comment by totyumengr** [comment]
Me too.
nw.js version is 0.12.2, Mac OS X 10.10.3

**Comment by danielwhyte** [comment]
Also having this problem, have to alt+tab to annother application to move the app around, only happens when I build the app out, not when I just run it.

**Comment by tphalp** [comment]
Same here, NWJS 0.11.6, OS X 10.10.4. I haven't tried 0.12.x.

**Comment by fritx** [comment]
Same here OSX with nw 0.12.2

**Comment by fritx** [comment]
Accoring to the clue provided by @gridwalk, we regress nw to 0.12.0 from 0.12.2, and it seems to work well now.

**Comment by Kajinor** [comment]
That problem is still not fixed? It still happens for me on 0.14.3.... is there any good workaround? Even if I call blur() - focus() after creation it doesn't work, my only workaround is to call hide() - show() but that results in a flicker-effect which looks very strange for the user.

It only happens on Mac OS X. Windows and Linux are working fine.

**Comment by fritx** [comment]
@Kajinor are you using `win.hide();win.show()`?
It could cause a big flicker-effect.
Try `win.blur();win.focus()`. I know it could take no effect.
BUT:
I've found a workaround:

```js
function winBlur {
  // anotherHiddenWin.focus()
}
```

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Mac with nwjs-sdk-v0.23.0.

**Comment by Christywl** [comment]
close until there is more information.
