### ISSUE TITLE
Thoughts on protecting source code using openSSL library

### ISSUE THREAD

**Issue by mfarahats** [nwjs/nw.js#3569]
basically. i don't want the end user to play with my code. specially js files as it contain sensitive info

the main idea is modifying Chromium so that
when i finish the project. i encrypt all the files and hard code the keys in Chromium files and build it.
when Chromium start. it decrypt the needed files and use it on the fly.

i think this may also protect package.json file 

i searched for encryption library in C/C++ and i found this
http://stackoverflow.com/questions/1052184/what-is-the-best-way-to-encrypt-a-text-file-in-c-c
openSSL can be used as simple encryption library
so i Thought to use it as it embedded by default in Chromium

Anyone have any idea on this approach?

**Comment by baconface** [comment]
1) You can protect source code from being put into a reusable format by making it a v8 snapshot. Notice I said reusable. This is just going to make it hard for them to rip and reuse easily.

2) Never put any sensitive information in a client side application. Packet sniffing, stack traces, hex editors, web dev dev tools, etc will eventually expose it. I don't see OpenSSL protecting your application. When you use encryption or obfuscation your file must be unencrypted in some way to be processed and usable for your end user. This will make your sensitive information vulnerable to interception to that user.

3) This type of post comes up several times a month. I just want to stress this is not just a limitation of NW.js applications but even native applications face this issue. You can make it hard but ultimately it can't be fixed. If you have sensitive duties they should be done server side and you should have some kinda of secure authentication/data exchange API to interact with that server.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
