### ISSUE TITLE
nwjs-v0.12.1-win-ia32 seems to have a min size for mouse penetration when set to frameless window 

### ISSUE THREAD

**Issue by krasewallet** [nwjs/nw.js#3570]
my package.json file looks like below:
{
  "main": "./lib/index.html",
  "name": "toolbar",
  "window": {
    "width":150,
    "height":60,
    "toolbar": false,
    "frame": false,
    "show":true,
    "transparent": true,
    "resizable":false,
    "always-on-top":true,
    "show_in_taskbar":false
  }
}
if window's height less than 60, it seems that there is an area below the window where the mouse click can't penetrate
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.23.0.

**Comment by Christywl** [comment]
close until there is more information.
