### ISSUE TITLE
[nw13] package.json - node-remote

### ISSUE THREAD

**Issue by tiitremmel** [nwjs/nw.js#3572]
I have package.json with multiple [node-remote](https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote) items, but when i start nwjs from terminal (Mac OS X 10.10.3) then i got error

```
[0611/122731:INFO:nw_package.cc(174)] ./nwjs ../Resources/
```

and it crashes. It worked with prev versions (nw11,nw12)
Here's my package.json

```
{
    "main": "index.html",
    "name": "foo",
    "node-remote": "http://google.com:80,http://local:88,192.168.25.1/24",
    "chromium-args": "--auth-schemes='digest,ntlm,negotiate,basic' --disable-web-security --disable-gpu --force-cpu-draw"
}
```
##

**Comment by dmx-patrick** [comment]
I also had problems with adding multiple item to node-remote, found out that you have to pass it as an array.

`"node-remote": ["http://google.com:80", "http://local:88", "192.168.25.1/24"]`

**Comment by ghostoy** [comment]
@dmx-patrick was correct. The spec was changed since 0.13.0. Please read our document for `node-remote` in manifest. http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote
