### ISSUE TITLE
Chromium mousemove bug

### ISSUE THREAD

**Issue by mizhigang407** [nwjs/nw.js#3575]
It looks like a old bug.but NOT solve at all.
I add mousedown mouseup mousemove different event handler on body,but when I click left mouse button, WITHOUT mouse move, it will trigger the mousedown mouseup mousemove event.
Why?
It's Chromium's BUG? How to solve it?
##

**Comment by Christywl** [comment]
Is this issue still reproduced now? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
