### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by broderix** [nwjs/nw.js#3576]
Hi,

Can anyone successfully build app on windows (7,8,8.1,2012R2), all my attempts over with nwjs blank page. If i run nw.exe src\ - works well.
I have tried with @mllrsohn/node-webkit-builder and manually like this
`copy /b nw.exe+app.nw ..\build\win32\myapp.exe`

Which version officially supported by nw.js? 
Since nw13 has new architecture where app source need to be located?

Thanks!
##

**Comment by mscreenie** [comment]
Try Web2Executable by @jyapayne. It's very good and has active support. https://github.com/nwjs/nw.js/issues/3576

**Comment by RIAEvangelist** [comment]
@broderix  I do not reccomend building with nw13 yet. It is bleeding edge and for the most part is missing a LOT yet, it is still super alpha. Lots of things are broken too, for now.

The officially supported version currently is 0.12.2
[nwjs official builds](http://nwjs.io/)

**Comment by Christywl** [comment]
Packaging the app works well for me on Windows with nwjs-sdk-v0.22.3

**Comment by Christywl** [comment]
close until there is more information.
