### ISSUE TITLE
Consistent crash on windows

### ISSUE THREAD

**Issue by venki-thiyag** [nwjs/nw.js#3578]
We are seeing a consistent crash when using node webkit. Crash points to the following check failure:

  DCHECK_LE(tilings_->num_tilings(),
            layer_tree_impl()->create_low_res_tiling() ? 2u : 1u);

This seems to be linked to https://code.google.com/p/chromium/issues/detail?id=469176. Any idea on how this fix this.

Issue is consistent on Windows 7 64 bit.
##

**Comment by venki-thiyag** [comment]
To add more info we are using 0.12.2 code base of node webkit.

**Comment by venki-thiyag** [comment]
Also further investigation reveals that pre built binaries are not having this issue but when building the source code locally issue seen.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
