### ISSUE TITLE
Could it have a disassembly command?

### ISSUE THREAD

**Issue by rexdf** [nwjs/nw.js#3580]
Something like javac-javap, there should be nwjc-nwjp
##

**Comment by mscreenie** [comment]
Why?

**Comment by baconface** [comment]
While I think there are some good reasons on a dev point I think the main reason NW.js has a V8 snapshot tool is to counter disassembly.

**Comment by FiatPax** [comment]
I wouldn't like my app being disassembled easily.

**Comment by Christywl** [comment]
Please ask questions and discuss in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
