### ISSUE TITLE
Get mouse position 

### ISSUE THREAD

**Issue by edi9999** [nwjs/nw.js#3581]
Is they a way to get the current mouse position, even if the window is not currently focused ?
##

**Comment by thelaw44** [comment]
Use a native c++ addon.

**Comment by Programming4life** [comment]
Take a look at this node module its used for automating things like clicking stuff on screen but it'll give you the mouse x,y of the mouse. https://github.com/octalmage/robotjs

**Comment by danschumann** [comment]
With robotjs, how would people who download my nw.js program have to install it?  Can I run `npm` commands on users' machines after they download my nwjs program?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
