### ISSUE TITLE
C++ Addons stops working after compiling nw to exe

### ISSUE THREAD

**Issue by Acanguven** [nwjs/nw.js#3582]
Hello,

I am working on a project that needs a native c++ addon. Everything works perfect when I <code>nw /app</code> But after I compile the application to exe using <code>copy /b nw.exe+main.nw app.exe</code> c++ addon stops working.

I used nw-gyp to build my addon.

I hope you can help me.
##

**Comment by yuchuan1** [comment]
I believe this is related to https://github.com/nwjs/nw.js/issues/199

**Comment by githubuserxj** [comment]
how to rebuild nw with ninja,like "ninja -C out/Release xxx -j8",you will get xxx.exe and xxx.lib.
thanks.

**Comment by githubuserxj** [comment]
@yuchuan1
how to rebuild nw with ninja,like "ninja -C out/Release xxx -j8",you will get xxx.exe and xxx.lib.
thanks.

**Comment by edwin1329** [comment]
Named after compiling your .exe with nw.exe, the addons need this name to function well.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?
