### ISSUE TITLE
Shortcuts don't trigger active.

### ISSUE THREAD

**Issue by jaredallard** [nwjs/nw.js#3583]
I'm registering as such:

``` js
  /* register key events */
  var gui = require('nw.gui');

  var option = {
    key : "Ctrl+T"
  };

  // Create a shortcut with |option|.
  var shortcut = new gui.Shortcut(option);

  shortcut.on('active', function(e) {
    console.log("Global desktop keyboard shortcut: active.");
  });

  // Register global desktop shortcut, which can work without focus.
  gui.App.registerGlobalHotKey(shortcut);
```

When Ctrl+T is pressed, nothing happens. If I change the key to "T" the input is intercepted, but nothing happens.

nw: `0.12.2`
platform: `linux`
arch: `x64`
##

**Comment by jakejarrett** [comment]
Can confirm, Linux shortcuts aren't behaving correctly on 0.12.2, 0.10.4 works fine.

**Comment by petre2dor** [comment]
similar problems here on ubuntu 15.04 and 14.04

**Comment by jaredallard** [comment]
Anything, @rogerwang?

**Comment by floriangosse** [comment]
Same problems on Fedora 22

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.22.3. When press 'Ctrl + T', 'active' event is triggered, and the console log is displayed.

**Comment by Christywl** [comment]
close until there is more information.
