### ISSUE TITLE
Menu item mnemonics show but don't activate on keypress in Windows 7.

### ISSUE THREAD

**Issue by davewthompson** [nwjs/nw.js#3584]
You can add mnemonics for each menu item using the ampersand character (for example, &File) which means the menu should be selectable by pressing the Alt key and hitting F.

Currently, nw.js shows the character underline when you press the Alt key, but the menu is not selected when you press the correct key on the keyboard.

OS: Windows 7 x64
NW: nwjs-v0.12.2-win-ia32

My guess here is the global hotkey code is intercepting these requests.

Thanks,
Dave
##

**Comment by eco747** [comment]
Same on Windows 10

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
