### ISSUE TITLE
node webkit that works bith on win32 and win64

### ISSUE THREAD

**Issue by benag** [nwjs/nw.js#3586]
Hello,

Is there a way to write a simple node webkit app that will work both on win32 and win64?
can I build win32 node webkit that will also work on win64?
##

**Comment by shaynem** [comment]
32bit apps can run on 64bit systems, 64bit apps cannot run on 32bit.

**Comment by OrganicChem** [comment]
I am having issues building win32 using nw-builder.  I am getting this error on launching.
![nw error](https://cloud.githubusercontent.com/assets/3411037/20451796/c5ca7232-adcb-11e6-958a-aebfcc0ff99b.png)

**Comment by ghostoy** [comment]
@shaynem is correct.
@OrganicChem Please post your issues to nw-builder.

Please ask further questions in our mailing list https://groups.google.com/forum/#!forum/nwjs-general.
