### ISSUE TITLE
MP3 enabling support

### ISSUE THREAD

**Issue by abertranb** [nwjs/nw.js#3588]
Hello we are using Debian 7 (32 bits) and we want to enable MP3 (https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.)

When we tried copy the "libffmpegsumo.so" doesn't work, and stops the application when tries to play an mp3 file.

Then we tried to "Build it Yourself" then we have to issues *after hours of downloads, :)*: 

1. There are not src/third_party/ffmpeg/chromium/scripts/build_ffmpeg.sh file, there are only the src/third_party/ffmpeg/chromium/scripts/build_ffmpeg.py  I changed the lines from to and put as:
     #Google Chrome & ChromeOS specific configuration.
      configure_flags['Chrome'].extend([
          '--enable-decoder=aac,h264,mp3',
          '--enable-demuxer=aac,mp3,mov',
          '--enable-parser=aac,h264,mpegaudio',
      ])
    
    
    Per:
    
      # Google Chrome & ChromeOS specific configuration.
      configure_flags['Common'].extend([
          '--enable-decoder=aac,h264,mp3',
          '--enable-demuxer=aac,mp3,mov',
          '--enable-parser=aac,h264,mpegaudio',
      ])

2. Then we tried using the .sh file from https://chromium.googlesource.com/chromium/third_party/ffmpeg/+/62ec545dd6d919e70ab9587e224773b682bbc149/chromium/scripts/build_ffmpeg.sh
3. Launch it from chromium/src/third_party/ffmpeg
    ./chromium/scripts/build_ffmpeg.py linux ia32 "/absolute_path/chromium/src/third_party/ffmpeg/"
4. Getting this error:
    License: LGPL version 2.1 or later
    Creating config.mak, config.h, and doc/config.texi...
    Building libavutil/libavutil.so.52 for Chromium...
    make -j1 libavutil/libavutil.so.52
    make: *** There are no rules to build the target `libavutil/libavutil.so.52'.  Stop.    
    
Any idea?

**Comment by abertranb** [comment]
Hello I can create a libffmpegsumo.so but when I added to compiled installation and tries to play a mp3 fails (the nw is closed), doesn't show any error

export GYP_DEFINES="proprietary_codecs=1 clang=0"
cd /home/user/node-webkit/src/third_party/ffmpeg
./chromium/scripts/copy_config.sh 
cd /home/user/node-webkit/src
./build/gyp_chromium content/content.gyp
ninja -C out/Release -j8 ffmpegsumo

and creates a libffmpegsumo.so

But if I create with -j4 shows an error

ninja -C out/Release -j8 ffmpegsumo

Shows
[12866:0622/090427:WARNING:channel.cc(553)] Failed to send message to remove remote endpoint (local ID 3, remote ID 2147483649)
[12866:0622/090427:WARNING:channel.cc(553)] Failed to send message to remove remote endpoint (local ID 1, remote ID 1)


Any idea?

**Comment by ghostoy** [comment]
See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for latest instructions for NW.js 0.13.0 or later.
