### ISSUE TITLE
Offscreen rendering / render to texture

### ISSUE THREAD

**Issue by matthewrobb** [nwjs/nw.js#359]
Is there a plan to support off-screen rendering and/or rendering directly to a 3d texture?

Projects such as Awesomium and Berkelium support this and it makes them very useful for creating embedded video game UI.
##

**Comment by matthewrobb** [comment]
@rogerwang I am still very interested in this feature :)

**Comment by rogerwang** [comment]
@matthewrobb good to know it. I'd like to see this after NW13 release.

**Comment by vibber** [comment]
+1

**Comment by pergy** [comment]
+1

**Comment by gridwalk** [comment]
I'm very interested in this as well. As @vibber commented, the offscreen rendering might be usable to feed frames to Syphon on Mac or Spout on Windows. I'm in the same position, and would love to implement something like this in my visuals app [gifSlap](http://gifslap.com).

**Comment by ojack** [comment]
any updates with this?

**Comment by rogerwang** [comment]
Currently there is no one working on this. But it's still on our radar. Could you please give detail about usage scenario for this feature? It could be helpful to prioritize it.

**Comment by saabi** [comment]
I'd love to be able to use this for mixing WebGL visualizations with other real time video effects software for VJing.

**Comment by rogerwang** [comment]
Offscreen rendering will be released with 0.29.0 soon, with support for accelerated graphics and plugins etc. It mirrors the content as a media stream. See the demo here: https://github.com/rogerwang/nw-offscreen-tab

**Comment by rogerwang** [comment]
close as it's shipped in 0.29.0.
