### ISSUE TITLE
Correct behavior of win.on('close') event?

### ISSUE THREAD

**Issue by marbemac** [nwjs/nw.js#3590]
Perhaps I'm misunderstanding the window on close event, but should it wait until this.close(true) is called? I'm trying to shut down a couple of servers when the user quits (cmd + q, or via the top menu), but the below is not being honored. I'd like the app to close only after the servers have been shutdown (in the callbacks below).

Thoughts?

```js
  var gui = require('nw.gui')
  var win = gui.Window.get()

  // when the window is closed, make sure to shutdown the api and proxy
  win.on('close', function() {
    var $this = this

    process.mainModule.exports.api.stop(function() {
      process.mainModule.exports.proxy.stop(function() {
        $this.close(true)
      })
    })
  })
```

**Comment by AndrePessoa** [comment]
Im trying to create a confirm dialog at my app, but the close event is not firing. 

```
gui.Window.open( "editor.html#" + tela.id , {	icon: "imgs/logo_icon.png", frame: debbug, /*toolbar : debbug,*/ width: 1024, height: 768 }, function(new_win){
	new_win.on('close', function() {
		new_win.window.alert.confirm('Essa tela não está salva.<br/> Fechar mesmo assim?',function(){
			new_win.close(true);
		});
		new_win.restore();
		return false;
	});
});
```

Any error? Before version 0.13 I forced the avoid creating a error inside the event, but this workaround is not working at current version... = (

**Comment by darshan2357** [comment]
@marbemac why did you close this issue, i'am searching for this exact scenario and unable to find any solution.

**Comment by marbemac** [comment]
Honestly I don't remember, sorry! We've since moved to Electron, and have loved it.
