### ISSUE TITLE
Would like devtools-opened event to also pass in the dev tools window object

### ISSUE THREAD

**Issue by jgoalby** [nwjs/nw.js#3591]
When the devtools-opened event is called on window, it is passed the URL as a parameter.

I am working on saving the state of the dev tools window as part of my application.  This is fine when I am the one calling showDevTools as I can capture the return value, which is the window object.  In the case where the toolbar is clicked, I don't have access to that return value.  I was wondering if the dev tools window object could be passed as a second parameter to the devtools-opened event handler?
##

**Comment by MadfishDT** [comment]
when dev tool is opening, you can see make new nw process, devtool is independent have render process, i think devtool is different window from application window.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
