### ISSUE TITLE
inject script to remote page 

### ISSUE THREAD

**Issue by tr0yka** [nwjs/nw.js#3592]
Hello! I need to insert the script in the remote page . inject-js-end is not working as it should. Performed only "pure " js. I would like to insert, for example socket.io code to connect to the local server . It is possible to make ? Thank you !

**Comment by baconface** [comment]
The remote page needs to be given access to node in order to perform node.js code. Check out [node-remote](https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote) on how to do that.

**Comment by tr0yka** [comment]
on the remote page does not node.js. And the window is not an instance nwjs? and it can not run scripts nodejs?

**Comment by baconface** [comment]
Ah, yeah. The JS is only going to have access to libraries within that frame/window. I suggest in your code you inject script elements with the src attribute pointing to your socket.io code. Or you can do the approach I took with [nwFiddle](https://github.com/baconface/nwFiddle/blob/master/js/app.js) and just add injections/bindings to the frame as if it was a same domain privilege. As a result it still had access to jQuery and other functions in my code.

**Comment by RIAEvangelist** [comment]
if its in an iframe you can inject any script like so :

pseudo code below

    var fs=require('fs')
    var script='<script>{{content}}</script>';

    fs.readfile(
        {
            encoding:'utf8'
        },
        './myfile.js',
        function(data){
            var head=frame.contentWindow.document.querySelector('head').appendChild(
                script.replace('{{content}}',data)
            )
       }
    )

or some such code. There are many many ways to do it.


    function myFunc(){
        ...
    }

    frame.contentWindow.document.yourFunc=myFunc;

     frame.contentWindow.document.yourFunc();

is another way too I think...

**Comment by tr0yka** [comment]
executed in the parent window(((

**Comment by rogerwang** [comment]
@tr0yka should you please show a case which doesn't work for you?

**Comment by RIAEvangelist** [comment]
@tr0yka only the last is executed in parent window, the fs read method is injected and run in the frame window scope.

**Comment by tr0yka** [comment]
>frame.contentWindow.document.yourFunc=myFunc;
> frame.contentWindow.document.yourFunc();

```javascript
function myFunc {
  $('body').append("string");
}
```
result inserted in parent window

**Comment by RIAEvangelist** [comment]
@tr0yka I'm not sure where I wasn't clear enough for you... My apologies. 

I quote :
"@tr0yka only the last is executed in parent window, the fs read method is injected and run in the frame window scope."

you then pasted the last example...

try the first example which as a said uses fs read. Just an idea.

**Comment by tr0yka** [comment]
@RIAEvangelist 
```
var fs=require('fs');
var script='<script>{{content}}</script>';
...
```

Unfortunately, the result is the same . So you can not run the script in the plug-in page.

**Comment by RIAEvangelist** [comment]
if you inject it into the frames head, it isn't the same. I'm not sure which part I'm not understanding with what you are looking to do.

I'm not sure what your going after, but lets just say you want to increment a variable in the frames window scope.

Here is a clever example :

    function changeIt(){
        var window=document.querySelector('iframe').contentWindow;
        window.theVarToChange++;
    }

    document.querySelector('iframe').contentWindow.changeIt=changeIt;

    setInterval(
        document.querySelector('iframe').contentWindow.changeIt, //or in this example just changeIt
        1000
    )

now lets say you wanted to overload some function in the window which already increments the var we were incrementing above :

    function changeIt(){
        var window=document.querySelector('iframe').contentWindow;
        window.theVarToChange++;
    }

    document.querySelector('iframe').contentWindow.funcToOverload=changeIt;

    // now the function in the frame that calls funcToOverload should be executing changeIt instead.
    // this is kinda not cool in some ways because you are hijacking the pages logic

maybe I'm failing to see what you are looking to do? could you give a direct example?

An example of socket.io would be to fs read the socket.io file wrap it into a script and inject it into the frames contentWindow.document.querySelector('head')

Even if all else fails, you can run socket.io from your parent and bind the events you want to listen for in the frames contentWindow and pass the information back to your server via the socket.
