### ISSUE TITLE
Handle connection error using remote files

### ISSUE THREAD

**Issue by MasDevProject** [nwjs/nw.js#3598]
I'm developing an application using Node WebKit and AngularJS.

The app gets the html/js/css files from the web, my package.json looks like:

``` javascript
{
  "main": "http://mysite.com/index.html",
  ...
}
```

I noticed that when a connection error occurs, node-webkit displays a blank screen. That screen is not "user friendly" so I need to display a custom screen. (e.g. a friendly page with a "reload" button).

Is there a way to obtain such behavior?

Thanks a lot!
##

**Comment by samlin08** [comment]
how about embed the remote page index.html in iframe

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
