### ISSUE TITLE
0.11.5 --single-process debug mode bug fix

### ISSUE THREAD

**Issue by MadfishDT** [nwjs/nw.js#3599]
node-webkit use single render process model for global object. but because of this option, node-webkit have tiny bug. 

if you went debugging node-webkit with --single-process command line in window environment, you could meet crash. but out of debug mode and release binary, this crash might be not happened.

this bug according to v8 inintialize. 

see isolate_holder.cc source code, you can see EnsureV8Initialized function call in IsolateHolder::IsolateHolder function. but, you can see EnsureV8Initialized function call in RenderThreadImpl::EnsureWebKitInitialized() function. when start node-webkit start and load some page, you can see EnsureV8Initialized called twice.
to fix this bug, remove EnsureV8Initialized function call in IsolateHolder::IsolateHolder function
##

**Comment by pavel-kudinov** [comment]
Hello!

So, is it possible to use node-webkit with --single-process command line option?

We really need it option ( for some patch of nw.js to make possible WebGL buffers directly accessible from node-webkit plugins ), but on OpenGL level it is only possible if renderer and plugin processes are the same processes.

--single-process crashes our runtime and I found this comment:

"This isn't possible, sorry! The code that allows single-process in Chromium is busted and bitrotted"

http://stackoverflow.com/questions/31061262/grouping-child-processes-in-node-webkit-or-atom-electron

If you know how to use --single-process flag on node-webkit, please let me know.

thanks

**Comment by bschmitlin** [comment]
so it's fixed in #3898 I guess?

**Comment by Christywl** [comment]
Debugging with `--single-process` command line option works well for me with nwjs-sdk-v0.22.3. Please try the latest build.

**Comment by Christywl** [comment]
close until there is more information.
