### ISSUE TITLE
how to change frame after window opened

### ISSUE THREAD

**Issue by ouonet** [nwjs/nw.js#3601]
I want to control whether the applicatoin show frame .
But I found I can only control the frame when the window startup by config:{frame:false/true}.
After the window opened, I can't hide/show the frame.
##

**Comment by tr0yka** [comment]
```
win = gui.Window.get(); //this window
win.show();//win.hide();
```
not work?

**Comment by ouonet** [comment]
@tr0yka 
sorry, I havn't express myself clearly.
what I want to do is Showing/Hiding the frame of window,i.e. window has a frame or not.

**Comment by MegaApuTurkUltra** [comment]
I would like to know if this is possible as well.

Currently I'm using a pre-main-window page that loads my app options and then opens the main app window with a frame or not depending on what's set. However, it would be nice to be able to change whether there is a frame or not without having to restart my entire app.

In other words, is there a way to control the frame other than the `frame` option of the window subfields?
