### ISSUE TITLE
"Uncaught Error: Unable to get render view in CallStaticMethod" while App.quit() in v0.12.2

### ISSUE THREAD

**Issue by snakevil** [nwjs/nw.js#3602]
I tried to create a dummy APP with nw.js 0.12.2 on OS X 10.10.3. Everything else works great except the custom exit button.

``` javascript
window.quit = function() {
  require('nw.gui').App.quit();
};
```

``` html
<button onclick="quit()">EXIT</button>
```

"Uncaught Error: Unable to get render view in CallStaticMethod" would be occurred when I clicked the EXIT button.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Mac with nwjs-sdk-v0.22.3. The app quits normally.

**Comment by Christywl** [comment]
close until there is more information.
