### ISSUE TITLE
[OSX] Selecting a directory - the file dialog "opens" directories but does not "select"

### ISSUE THREAD

**Issue by AoDev** [nwjs/nw.js#3604]
Hello, 

I have been trying to simply let the user choose a directory from a file dialog and display the path in a form field.

I've checked docs and tons of issues in Github and I still can't make it work.

The basic snippet being: `<input type="file"  nwdirectory/>`

It displays the file dialog, but I can't "select" a directory. The dialog only presents the "open" (and "cancel") buttons. If I click a directory, it will open it and display its files. (normal file dialog selection)

What am I missing?
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.22.3. Click 'Choose File' and the dialog opens, select one folder, and click 'select' button. The selected folder name will be displayed in the app page.

**Comment by AoDev** [comment]
Hi. I don't develop with node webkit anymore. I won't be able to further investigate this.
You could close the issue until someone reports it again?
