### ISSUE TITLE
fs.access() giving wierd results

### ISSUE THREAD

**Issue by watdafox** [nwjs/nw.js#3605]
Hello, 

I'm trying to figure out if the nwjs app was launched with admin mode or not, but I'm facing an issue with fs: 

```
    fs.access(process.env.APPDATA, fs.W_OK, function (err) {
        console.log(err ? 'no access!' : 'can read/write');
     });
```

This should always be ok on Windows, yet it never is. I can totally write a file to process.env.APPDATA with fs.writeFile() but fs.access() keep telling me 'no no you cannot'. 
##

**Comment by Christywl** [comment]
The code works well on Windows with nwjs-sdk-v0.22.3 for me. The console log shows 'can read/write'.

**Comment by Christywl** [comment]
close until there is more information.
