### ISSUE TITLE
[armhf][Raspberry PI] Cross Compiled executable over 1 GB, and cannot execute it

### ISSUE THREAD

**Issue by sdinesh86** [nwjs/nw.js#3606]
Hello All,

I have been going through all the threads and specifically #193 I am looking to build NW for the my Raspberry pi 1 B+, my setup is as follows

Ubuntu 12.04 LTS Desktop on amd 64 machine
gist for cross compiling : https://gist.github.com/sdinesh86/bca4592f530ea00e8c77
*\* I used http://ports.ubuntu.com for armhf binaries as the main repo didnt had them.

I synced the chromium src without history, I was able to compile nw but the new binary is over 1 GB, other binaries that i have seen here are not more than 50 mb in size, also I am not able to execute the binary.

did i miss anything or have i done something wrong.

Thanks,
Dinesh
##

**Comment by jtg-gg** [comment]
@sdinesh86 you need to "strip" the binary to discard the debug info, 
from my experience, I can't strip arm binary from x64 host
so copy first to your raspberry machine, and strip it there

I am curious if anyone knows how to strip arm binary from x64 host

**Comment by hkaya** [comment]
@jtg-gg Have you tried using the `strip` coming with the toolchain? Something like this should reduce the armhf binary size on x64:

`arm-linux-gnueabihf-strip -s <nw binary>`

**Comment by sdinesh86** [comment]
@jtg-gg and @hkaya : thanks for the solutions I tried it and it worked it seems but ow I have bumped into another problem.

When I try to run the nw executable in raspberry it says "commad not found", i checked online and found posts that suggest this message is caused due to wrong architecture

I am using MINIBIAN a minimal raspbian image, I confirmed that the image that i have is armhf, so now that means the binary that got compiled is for armel its seems, is there any flag that we need to set in order to build amrhf binary ?

**Comment by JohnMurga** [comment]
@sdinesh86 I thought that armel should work (a bit slower).
It could be an ARMv6 VS ARMv7 thing, meaning that your binary might work on an RPi2.
I actually have both, so I can try for you if you post the binary.

**Comment by sdinesh86** [comment]
@JohnMurga I am not at home right now, I will upload the build once I am at home ASAP.

**Comment by sdinesh86** [comment]
I had some space issues on my ubuntu so I had to reinstall everything,

but now when I try to sync the project i get the following error.

Error: Command 'git checkout --quiet refs/remotes/origin/nw12' returned non-zero exit status 1 in /home/user/NWJS/src/content/nw
error: pathspec 'refs/remotes/origin/nw12' did not match any file(s) known to git.



Warnings:
Conflicting directory /home/user/NWJS/src/content/nw moved to /home/user/NWJS/_bad_scm/src/content/nwh_smiD.

**Comment by omghaxzs** [comment]
If you're running Ubuntu Precise there is a 'binutils-arm-linux-gnueabi' package from apt-get.
Seemed to work for me:

    daniel@ubuntu:~/chromium/src$ arm-linux-gnueabi-strip out/Release/nw
    daniel@ubuntu:~/chromium/src$ ls -lah out/Release

    -rwxrwxr-x  1 daniel daniel  49M Aug 31 10:04 nw

In general I find Ubuntu Precise Server to be the least frustrating platform to build nw on...

**Comment by sdinesh86** [comment]
i was using trusty

**Comment by jalbam** [comment]
Maybe this can be useful: https://github.com/jalbam/nwjs_rpi

**Comment by Christywl** [comment]
Is this issue still reproduced?

**Comment by Christywl** [comment]
close until there is more information.
