### ISSUE TITLE
localStorage sometimes null after Window close event

### ISSUE THREAD

**Issue by Z3TA** [nwjs/nw.js#3607]
I'm using this code:
https://github.com/nwjs/nw.js/wiki/Preserve-window-state-between-sessions

But sometimes the localStorage is null!

localStorage works fine until hitting the close button in windows (to close the app). 
Then sometimes the localStorage works and sometimes it's null.

Test code:
if(!localStorage) throw new Error("localStorage not available!");
##

**Comment by Z3TA** [comment]
Might be the same as:
https://github.com/nwjs/nw.js/issues/2087

**Comment by Christywl** [comment]
Is this issue still reproduced for you? Due to #4487, I can't run the code normally on the latest nwjs build.

**Comment by Z3TA** [comment]
I've not been able to reproduce this.

I have not seen this for a very long time. I've refactored the code to make a more "soft" close, by running everything and then calling this.close(true);
I'm also trying to use as little nw.js code as possible an rely only on native web API's, so that I can run my app entirely in the browser.
