### ISSUE TITLE
[nw13] - alpha2 New Window Creation CallBack doesn't work

### ISSUE THREAD

**Issue by kamesh-a** [nwjs/nw.js#3610]
We are trying to test with nw13 release, in recent alpha2 release, new window callback doesn't work on checking that. nw13-alpha2 has introduced this bug.

![nw13_alpha2_newwindow](https://cloud.githubusercontent.com/assets/3531949/8339951/e0eae66e-1ad8-11e5-9135-87a246320928.png)

Attached screen shot and code snippet.

nw13-alpha1 works fine.
nw13-alpha2 emits this error.

System Info:
Mac OSX
nw13-alpha2 64bit SDK Version

```
chrome.app.window.create('http://my.setmore.com',{},function cb(e){
console.debug('Arguments : ',arguments);
})

```

Thanks 
##

**Comment by tshinnic** [comment]
Tested with 0.13.0-alpha3 (on Win7) and also get that error message and traceback, but about half the time I *don't* get that error message.  Each time, whether the error is seen or not, the new window does get created and is visible.

**Comment by Christywl** [comment]
It works well on Linux/Windows with nwjs-sdk-v0.22.3. Please try the latest build.

**Comment by Christywl** [comment]
close until there is more information.
