### ISSUE TITLE
will get stuck when i enable multiple instances

### ISSUE THREAD

**Issue by MouLingtao** [nwjs/nw.js#3612]
when i enable multiple instances and use javascript to clear app cache, the new instances will get stuck!

of course,  run `require('nw.gui').App.clearCache()` in the second instances,  the system also get stuck instead of throw exception.
##

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <[nw.js] will get stuck when i enable multiple instances (#3612)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
