### ISSUE TITLE
Devtools fails to display UTF-8 chinese characters

### ISSUE THREAD

**Issue by woc2006** [nwjs/nw.js#3617]
![qq 20150627100033](https://cloud.githubusercontent.com/assets/1716430/8390016/82d0367e-1cb3-11e5-8902-21e58d447811.png)

source code format: UTF-8 without BOM,  CRLF
nw version: both 0.11 and 0.12.2

**Comment by CarlosRen** [comment]
maybe  your IDE char setting  is gbk2312

**Comment by woc2006** [comment]
@CarlosRen   
![qq 20150627100917](https://cloud.githubusercontent.com/assets/1716430/8390035/9f510c3c-1cb4-11e5-9618-33a3ead188af.png)

WebStorm 10.0

**Comment by CarlosRen** [comment]
i notice that your file  is a javascript , try to open it with browser and check the chinese characters in source

**Comment by mcdongWang** [comment]
I also encountered the same problem. I'm sure my IDE using UTF-8
I hope someone can answer this question.

**Comment by mcdongWang** [comment]
@woc2006  

I solved the problem. 

you need save the file use by UTF-8 with BOM

**Comment by mcdongWang** [comment]
but i do not know why

who can tell me.

**Comment by cecilpeng** [comment]
The same problem here!
I hope someone can help me, as debugging is so hard!

**Comment by rogerwang** [comment]
0.13.0 beta version fixed this.
