### ISSUE TITLE
Memory can not be released, consume too much.

### ISSUE THREAD

**Issue by zg2013** [nwjs/nw.js#3619]
hello,
I use a scroll bar. "Malihu-custom-scrollbar-plugin"
Using NW to open his dome found that memory has been unable to release, and the growth rate is far more than chrome.
Test environment:
X64 win7
Nw.12.0
Nw.12.1
Nw.12.2
Test address:
http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/scrollbar_themes_demo.html

![mem](https://cloud.githubusercontent.com/assets/5134292/8395700/7c9998cc-1db2-11e5-9db8-580454f5be17.png)
##

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
