### ISSUE TITLE
Feature Request: Add switch to disable the remote debugging server

### ISSUE THREAD

**Issue by erezcohen** [nwjs/nw.js#3620]
As nwjs starts it opens a tcp port on local host (for remote debugging / devtools) and listens on it.
I would prefer to be able to supply a command line switch that will tell nwjs not to open the port.

Motivation: Enterprise organizations with high security restrictions (e.g. banks) many times prevent end users from running apps that try to open and listen on ports (even on local host).

Note: At first I thought it is solely a Chromium issue (see: https://code.google.com/p/chromium/issues/detail?id=503566) however it seems that running a simple chromium installation doesn't open the mentioned port - so I guess this behavior is determined somewhere in the nwjs integration?

**Comment by erezcohen** [comment]
See https://code.google.com/p/chromium/issues/detail?id=349558#c4:
According to them: "Desktop Chromium would only enable remote debugging if started with --remote-debugging-port command line option" - Then why is it enabled by default in nwjs?

**Comment by erezcohen** [comment]
I'm thinking of fixing it myself.
Possibly, in order to maintain backward compatibility, the devtools server should be started by default.
Can anyone point me to a starting point?
Is the fix should be in Chromium or nwjs? (or in the build/config files?)

**Comment by xiaoyongwu** [comment]
Any updates on this issue? Looks like this should be a fix from nwjs in  src/shell_browser_main_parts.cc.
` if (command_line.HasSwitch(switches::kRemoteDebuggingPort)) {
    int temp_port;
    std::string port_str =
        command_line.GetSwitchValueASCII(switches::kRemoteDebuggingPort);
    // FIXME: should revert to `temp_port > 0` when chrome-devtools:// is enabled
    if (base::StringToInt(port_str, &temp_port) &&
        temp_port >= 0 && temp_port < 65535) {
      port = temp_port;
    } else {
      DLOG(WARNING) << "Invalid http debugger port number " << temp_port;
    }
  }
  devtools_delegate_ = new ShellDevToolsDelegate(browser_context_.get(), port);
`
The code above should try to detect a special port such as -1 and not to start the remote debugging?

**Comment by rogerwang** [comment]
Will disable this in normal build.

**Comment by xiaoyongwu** [comment]
Is this going to be disabled for next release in normal build?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by AllencxWang** [comment]
For those who are still using the older version of nwjs (eg. 0.12.x), you can simply modify "nw/src/shell_browser_main_parts.cc" like this:

![screen shot 2016-06-13 at 10 52 10 am](https://cloud.githubusercontent.com/assets/4864146/15995969/f9c18056-3154-11e6-9fd3-59d3c9e97c37.png)

Once it's rebuilt, nwjs will start listening on the remote debug port only if it's specified. (nw --remote-debugging-port=9222).

If you want to disable this remote debugging port forever, you can use devtools_http_handler_.reset(), just like the else clause did.
