### ISSUE TITLE
js代码有中文就无法调试

### ISSUE THREAD

**Issue by redhat** [nwjs/nw.js#3621]
js代码中如果存在中文，调试工具就无法打断点，希望尽快修复（nw.js v0.12.2）

**Comment by shipengyan** [comment]
我也遇到了，而且此时断点会错位

**Comment by Tukeping** [comment]
我也遇到了，求解决方法。  现在即使是在 js中 输入 debugger让webkit强制断点住，也会遇到 断点错位的问题。

**Comment by rppig** [comment]
好像windows下还是可以打断点的，mac下不行。

但是mac下可以通过右击来增加断电

**Comment by wufeng87** [comment]
把js脚本放到html中可以正常调试。错位也不是能调试吧，可以看各个状态来判断大致的当前行数。
要不就写个程序，运行时去掉js文件里的注释？

**Comment by Tukeping** [comment]
比如在index.js中有中文，那么打开developer tools后 ，在sources 下对index.js是无法点击左边来设置断电的，  后来我直接在index.js中加入debugger之后，developer tools会在一个叫：“VM132 index.js” 里进入断点。里面的所有中文都变成乱码，有时运气好不会错位，运气差错位的离谱，其实我不仅仅是注释里才有中文的，这个没法避免。  在html里放入<script>进行js中文调试确实可以。但是这样 是不是太 那个了。   还是给一个 靠谱的办法呗。

**Comment by Tukeping** [comment]
在html里放入放入js代码以及中文，只要设置好encoding是可以正常 进行调试的，但是 这样我就都不能用外部js了。能不能给一个靠谱一点的解决方法，谢谢各位。

**Comment by waiting0729** [comment]
在原文件任意地方打个空格就行了

**Comment by cecilpeng** [comment]
use utf8 through replace <= nwjs-v0.12.x.  upgrade nw to v0.13.x is another choice.
```
replace(/[^\x00-\xff]/g, function($0) {
    return '\\u' + $0.charCodeAt(0).toString(16);
})
```

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.

**Comment by cecilpeng** [comment]
check if added: <meta charset="utf-8">

**Comment by anchengjian** [comment]
My page always contains `<meta charset= "UTF-8" >`, and I tried `<script src= "scripts/main.js" charset= "UTF-8" ></script>` as well but useless.

**Comment by cecilpeng** [comment]
I think it is a messy encoding problem: the encoding of the tip come from server response or local javascript, is gbk?
anyway, a tiny sample will be helpful!

**Comment by Losses** [comment]
same problem, the encoding of JS file and html file are both UTF-8 without BOM, but in Javascript, if I run 
```
document.querySelector('#someElement').innerHTML = '一些中文字符';
```
The content of the element will become something else, not the Chinese character.
