### ISSUE TITLE
[nw13] : nw13 session/cookie niether persistent nor sharable between frames/webview

### ISSUE THREAD

**Issue by kamesh-a** [nwjs/nw.js#3622]
Hello,

While doing mock codes we found that, session are not persistent in the app created with nw13, this is one of the major missing pieces in "CHROME APP" which made us to migrate to node-webkit. 

OS Env :
 - Mac OSX 
 - Win 7,8

Engines used to test:
comparison between nw-0.12.2 vs nw-0.13.0-alpha2

We want to bring this up during development phase of nw13 re-engineering works,so it might be easy for developers to act now while code is hot.

Sample example app is attached.
https://dl.dropboxusercontent.com/u/42787852/nw-crash/nw13_session_cookie_not_shared_or_persistent.zip

**Comment by bachel** [comment]
I can confirm losing cookies after app close in 0.13.0 alfa2 on win 7. Even when I am using same partition persist ID. 

With same partition persist ID webview remembers zoomMode and zoomLevel from previous session and shares cookies between frames/webview, but all webviews are in the same process so when one stuck all stuck until unresponsive event is called.

**Comment by kamesh-a** [comment]
Any luck on this issue, Will nw13 make sessions to share with multiple process creation in webview?

**Comment by kucix** [comment]
+1

**Comment by ocher** [comment]
We also have the problem that cookies set by <webview> tag are not being persisted. It is a very big issue for us, and 0.13 is not usable at all with that bug.

**Comment by rogerwang** [comment]
Will fix soon.

**Comment by rogerwang** [comment]
@ocher @kamesh-a does this help? http://stackoverflow.com/a/23684875

**Comment by ocher** [comment]
@rogerwang Yes, it worked. Thanks! However, the problem is that cookies defined in the "main" nw.js app are not available to the <webview> element. But maybe we will be able to deal with it somehow.

**Comment by rogerwang** [comment]
Reopen this issue if you cannot find a way. Thanks.
