### ISSUE TITLE
Embed pdf with the object tag using pdf.dll

### ISSUE THREAD

**Issue by natcohen** [nwjs/nw.js#3624]
Embedding a pdf inside an object tag doesn't display the pdf even with the pdf.dll in the package...
##

**Comment by rogerwang** [comment]
What's your version? This is supported in the 0.13.0 version.

**Comment by natcohen** [comment]
@rogerwang  Well, the 0.13.0alpha2 doesn't include the pdf.dll and there is no instruction for packaging... (what is the nw.dll for example? Which files to package with the windows command? Which files to include in the enigma box?)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
