### ISSUE TITLE
fullscreen:true and show:false can't use together

### ISSUE THREAD

**Issue by mizhigang407** [nwjs/nw.js#3625]
when set fullscreen:true ,transparent:true and show:false in package.json, show:false not works,the window display anyway.
Then I try another way,set fullscreen:false,transparent:true and show:false in package.json, and use 
onload = function() {
  gui.Window.get().show();
  gui.Window.get().enterFullscreen();
}
it works,but both two ways the window is white about 1s before showing the application.
Have any ideas to prevent it?
##

**Comment by baconface** [comment]
I am having trouble figuring out why someone would want to hide a full screen window.

**Comment by zhangzq608** [comment]
I have encountered the same problem, how did you solve it?

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.22.3. 
package.json:
```
{
    "name": "test",
    "main": "index.html",
    "window": {
      "frame": false,
      "fullscreen": true,
      "transparent": true,
      "show": false
    }
}

```

**Comment by Christywl** [comment]
close until there is more information.
