### ISSUE TITLE
The inject-js function and node frame

### ISSUE THREAD

**Issue by jgoalby** [nwjs/nw.js#3630]
To have inject-js (start or end) specified file to be able to use require or global you need to not specify nwdisable in the frame attributes.  This means if you load public websites from the frame that they will have access to node also.

Is there a way to have the file specified by inject-js-start and inject-js-end be run in the context of node and the rest of the page that the file is injected into run as however the nwdisable attribute is set (either disabled or not)?

So, if I specify this:
    "inject-js-start": "./app/inject.js"

Then I would like inject.js to be able to access node, e.g. require or global etc.

Then I would like to specify nwdisable for the frame and have public webpages not have access to node.
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
