### ISSUE TITLE
 app.js run two times

### ISSUE THREAD

**Issue by hjhuangjun** [nwjs/nw.js#3631]
nwjs0.12.2
package.json
{
  "main": "index_frame.html",
  "name": "CardLib",
  "version": "1.0.0",
  "nodejs":true,
  "single-instance":true,
  "webkit": {
    "page-cache":false,
    "plugin":true
  },
  "window": {
    "frame":true,
    "toolbar":true,
    "kiosk": false
  },
  "node-main":"js/app.js",
  "always-on-top":true
}

app.js
var _logger = require('tracer').dailyfile({root:'./log',dateformat : "HH:MM:ss.L"});
_logger.info("program start...");

logger file record 2 row program start...
it mean app.js run two times
why?

**Comment by glenn9** [comment]
Is `app.js` loaded in `index.html`?

**Comment by jgoalby** [comment]
Possible duplicate: https://github.com/nwjs/nw.js/issues/3248

**Comment by hjhuangjun** [comment]
@glenn9 
Is app.js loaded in index.html?  
app.js only call in package.json

**Comment by yunqingmo** [comment]
Thanks,the problem has been solved.
