### ISSUE TITLE
links starting with "//" perceived as file

### ISSUE THREAD

**Issue by needo2** [nwjs/nw.js#3633]
example 
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
tries to load it as file//maxcdn....
##

**Comment by Skysplit** [comment]
that's pretty obvious, as `//` is for using the same protocol as used currently, which in nwjs app is `file://`

**Comment by yunqingmo** [comment]
Thanks, the problem has been solved.

**Comment by Christywl** [comment]
Could we close this issue now?

**Comment by Christywl** [comment]
close until there is more information.
