### ISSUE TITLE
Multiple OS

### ISSUE THREAD

**Issue by rochapablo** [nwjs/nw.js#3634]
Hi!

I'm starting play with nw.js and I'm wonder if it's possible configure my first app running in two systems. Well I'm not sure if this (what I'm thinking) is the right way, but I'm thinking of something like:

```
- app
  - linux
    - nw files...
  - windows
    - nw files...
  - css
  - js
  - index.html
  - package.json
```

So... any idea? Is this possible?

**Comment by bhaveshgohel** [comment]
Have a look at this -  https://github.com/mllrsohn/node-webkit-builder

**Comment by rochapablo** [comment]
Thanks @bhaveshgohel

**Comment by yunqingmo** [comment]
Thanks, the problem has been solved.
