### ISSUE TITLE
MS Surface input backspace crash

### ISSUE THREAD

**Issue by mondasd** [nwjs/nw.js#3635]
Running on a MS Surface Pro 3 Atom processor.  Steps...
- Enter text in an input field
- Long press to bring up cursor position drag icon
- Touch the cursor drag position icon
- Back space on keyboard....application crashes.

Please see  screen shots.

![cursor position](https://cloud.githubusercontent.com/assets/5275237/8502069/699e9066-2171-11e5-9784-d61272fcbccb.PNG)
![crash](https://cloud.githubusercontent.com/assets/5275237/8502074/6d5fb18a-2171-11e5-9a6a-dfa33c7032ba.jpg)

html...

<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>

```
<div>
    <input>
</div>
```

</body>
</html>

package.json....

{
    "name": "bad input",
    "main": "html/main/badinput.html",
    "window": {
        "toolbar": true,
        "title": "",
        "width": 1100,
        "height": 600
    }
}
##

**Comment by mondasd** [comment]
An additional question as well...

Can the blue teardrop cursor position drag marker be replaced in any way?  i.e. is the ability for an app developer to provide their own icon exposed in nw.js?

**Comment by mondasd** [comment]
updates on this one?

**Comment by Christywl** [comment]
I can't reproduce this issue on Surface Pro 3 with nwjs-sdk-v0.22.3. No crash.

**Comment by Christywl** [comment]
close until there is more information.
