### ISSUE TITLE
Right click save image as?

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3636]
Does anyone know of a way to use the context menu to create a right click save image as dialog?

**Comment by joshuaterrill** [comment]
I was able to create one by getting the stream of the image and writing it out like this:
```
// get the image stream
        var request = http.get(savingImage, function(res){
            var imagedata = ''
            res.setEncoding('binary')
            
            // get the data
            res.on('data', function(chunk){
                imagedata += chunk
            });

            res.on('end', function(){
                // write it to a file
                fs.writeFile(fileLocation, imagedata, 'binary', function(err){
                    if (err) throw err
                    console.log('[WEBKIT: IMAGE SAVED]');
                    exec("cd " + directory + " && start " + fileName, function (error, stdout, stderr) {
                        if (error !== null) {
                           console.log('exec error: ' + error);
                        }
                    }); 
                });
            });

        });
```

Note, mine also opens the image after it has saved it.

**Comment by jgoalby** [comment]
This solution appears to download the image a second time.  Is that correct?  It would be better I think if it were possible to get the image (or any asset for that matter such as pdf) from what was downloaded originally.  Would that be possible?

**Comment by joshuaterrill** [comment]
I don't see how it gets downloaded a second time? First it grabs the data and puts it into a variable, then it writes the data to a file.

**Comment by jgoalby** [comment]
What is in savingImage?  Is it the image url?  That http get would then issue a HTTP request for the image?

I presumed you had already gone to a URL in the app for a webpage that contained the image.   Then the image was downloaded via chromium.  I presumed then that you wanted to get the image data that chromium downloaded?

Maybe I misunderstand?

John.

**Comment by joshuaterrill** [comment]
```savingImage``` is the src of the image that I right clicked on. In my example, you have an image on a page, you right click it to initiate a context menu, then when you click Save Image As, it grabs the src, and does a request on it to download it. So I guess TECHNICALLY the image is being downloaded twice (once by the browser, and once to my computer) :)

**Comment by jgoalby** [comment]
Yeah, I am not talking about TECHNICALLY.

The image you clicked on.  Where did it come from?  Downloaded over HTTP to chromium I presume?

Then, when you do your http get request, you initiate another HTTP request.  So, I think that means you downloaded from the server over HTTP twice.

And if we want to get technical, you it is also copied to your disk on your computer twice.

I believe that is what is happening if the saving Image is a url.  A better solution within nw.js would be if you could get access to the actual file downloaded from chromium.  I don't know if that is possible or not.  It doesn't appear many people on the nw.js project are responding these days.

**Comment by joshuaterrill** [comment]
I'm not pointing my webkit at local files. The image does not exist on my computer until I download it. My webkit points to a server that serves up the images.
