### ISSUE TITLE
Display specific url in nwjs webbrowser

### ISSUE THREAD

**Issue by Silvering** [nwjs/nw.js#3641]
Hi ! I created a tcp server which listen to a client. This client sends command to the server. When a specific command is received by the server it open a node webkit webbrowser. I'm using this one : https://bitbucket.org/misterdai/node-webkit-browser/src However when the command is sent and received by the server, the nwjs browser always open his home page (google.com) and never the url I chose… Here is my tcp server : https://gist.github.com/Silvering/f9fecc415a4acf6c4fed
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
