### ISSUE TITLE
[WIN] Crash on mouse navigation button press

### ISSUE THREAD

**Issue by patrickm** [nwjs/nw.js#3643]
NW.js on WIN crashes when using mouse side buttons or mouse thumb area buttons.

Reproduction:
- use mouse with navigation buttons (buttons around thumb area/side buttons). Typically they are set as back/forward buttons in explorer / browser.
- launch nw.js, open dev tools, setup your menubar

```
var gui = require('nw.gui');
var your_menu = new gui.Menu({ type: 'menubar' });
your_menu.append(new gui.MenuItem({ label: 'Item A' }));
gui.Window.get().menu = your_menu;
```
- go back to main window, press first side button, [press another side button]
- node-webkit will crash

Affected versions: 11.0+ (32 bit), 12.0+ (32 bit), works fine on 10.5 (32 bit)
I wasn't able to test 64 bit version.

Tried many official builds available (32 bit), all above 10.5 seem to crash, sometime after few button presses.

Test env: win 7 32bit, hidpi.

Can anyone confirm it crashes on:
- non HIDPI OS
- 64 bit nwjs

Thanks
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by EvanBalster** [comment]
The TiddlyDesktop app by @Jermolene manifests this issue.  See the issue there:
https://github.com/Jermolene/TiddlyDesktop/issues/119
