### ISSUE TITLE
Title is shown when setting transparent to true on OSX

### ISSUE THREAD

**Issue by 7nights** [nwjs/nw.js#3645]
![image](https://cloud.githubusercontent.com/assets/3193621/8538786/961270a0-24a4-11e5-915f-1b93b5f61eec.png)

You can see there's a title( `C...`) at the top-right corner. Even if I set the opacity of html to 0, that title will still be there. BTW, calling setTransparent(true) at runtime doesn't work. It will not actually make the window transparent, but it removes the window's shadow, and gives the window a gray background. 

Yosemite 10.10.4 & nwjs-v0.12.2-osx-x64
##

**Comment by jtg-gg** [comment]
@7nights have you tried disabling the window's frame ?

I also encounter the bug (gray background window)
this is due to the app is linked with 10.9 framework.
I've my own build (linked with 10.8 framework) it is working

**Comment by 7nights** [comment]
@jtg-gg  Yes I tried, you can see there's no window frame in the screenshot.

Temporarily, I set the title to '\u3000' to solve this problem.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?
