### ISSUE TITLE
[Mac] Transparent app background but visible toolbar

### ISSUE THREAD

**Issue by kisPocok** [nwjs/nw.js#3647]
Hi,

I'm new to nw.js. This project looks good, but the documentation is missing.
Anyway. I would use  transparency on my Mac app's background. It works. But I would keep the original top frame. Any advice is appreciated! 

Here is my setup:

```
"window": {
  "transparent": true,
  "frame": true,
  "toolbar": false
}
```
##

**Comment by sapioit** [comment]
I can't get it working on Windows, 0.12.3... also tried to set it transparent from CSS...

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full tests to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
