### ISSUE TITLE
app.argv is not  correct when file name has blank space

### ISSUE THREAD

**Issue by xuanhun** [nwjs/nw.js#3648]
There is a file named "缩略图 1.dbk", when dragging and dropping it to nw.exe, app.argv is ["C:\Users\Administrator\Desktop\缩略图 1.DBK.dbk"], that is right.
But start nw.exe by double clicking dbk file(I have bound dbk file to nw.exe),app.argv is ["C:\Users\Administrator\Desktop\缩略图", "1.DBK.dbk"] on windows 7, and on windows 8 it is ["C:\Users\t540p\Desktop\缩略图~1.DBK"],
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, please tell how to bound dbk file to nw.exe.

**Comment by Christywl** [comment]
close until there is more information.
