### ISSUE TITLE
Does nw.js app support windows surface swipe gesture?

### ISSUE THREAD

**Issue by zdnet** [nwjs/nw.js#3649]
Any sample app is like this?
##

**Comment by baconface** [comment]
Considering you can add swipe functionality to mobile websites using JavaScript as well as browsers as old as IE7 I do not see why not. Try opening NW.js, in the address bar put in http://codepen.io/justincavery/pen/saEyI and try this swipe.js demo. Or try some of the jQuery Mobile demos. http://demos.jquerymobile.com/1.4.5/

A popular library to add swipe functionality is [swipe.js](https://github.com/thebird/swipe) but there are more out there like it.
