### ISSUE TITLE
Cannot extract package if xxx.nw too big.

### ISSUE THREAD

**Issue by maomaoispan** [nwjs/nw.js#3650]
![001](https://cloud.githubusercontent.com/assets/3338967/8588532/12367ce0-263e-11e5-8227-d3ef3d51f9a4.jpg)
![002](https://cloud.githubusercontent.com/assets/3338967/8588535/1729e520-263e-11e5-9543-9d2bf5c3e941.jpg)
##

**Comment by Christywl** [comment]
I can't reproduce on Windows with nwjs-sdk-v0.22.3. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
