### ISSUE TITLE
Window.requestAttention doesn't seem to do anything on Fedora/Ubuntu

### ISSUE THREAD

**Issue by ermenkov** [nwjs/nw.js#3651]
**Window.requestAttention** doesn't seem to do anything on Linux. I've tested it with Fedora 22 on Gnome 3.16.2 and with Ubuntu 14.04.1 on Unity 7.2.5. 
Same goes for **Window.setBadgeLabel** . It's already stated in the docs that its Linux support is very limited but non of the supported stuff works.
#571 seemed to be closed as fixed but doesn't seem like it from what I've tested
##

**Comment by jtg-gg** [comment]
@ermenkov you'll need ".desktop" file for the ubuntu, last time I test on Ubuntu 14.04 LTS using unity, it worked

**Comment by ermenkov** [comment]
@jtg-gg I have a .desktop file. I've followed all the instructions for a valid .desktop file, I even copied the one that google chrome uses and just changed the *Exec* row to point to my app, since it has attention, badge and even progressbar features. Unfortunately non of the mentioned functionalities work with the nw.js app.

**Comment by jtg-gg** [comment]
@ermenkov it is a valid bug, I've just fixed it https://github.com/nwjs/nw.js/commit/f5019bc643599246e2cc1ea8cc97b4cb6bcfb156

**Comment by ermenkov** [comment]
Awesome, thanks. When and are you planning on merging it in version 0.12?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
