### ISSUE TITLE
Using Scipy library

### ISSUE THREAD

**Issue by VolosTom** [nwjs/nw.js#3653]
I am trying to use the Optimization module of the Scipy python library. There is a node wrapper for the library (https://www.npmjs.com/package/scipy-optimize#min), but that launches a python engine as a child process and streams the results to node. I was wondering either if anyone had tried something like this before in NW.js, or if there was a javascript equivalent to the Scipy library.
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
