### ISSUE TITLE
nw.js inject-js-end worked partially

### ISSUE THREAD

**Issue by wildtang** [nwjs/nw.js#3654]
The detail of problem is below.
http://stackoverflow.com/questions/31314521/nw-js-inject-js-end-worked-partially

Can anyone take a look and give me an answer? Thank U first.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
