### ISSUE TITLE
gui.Shortcut: Binding to Ctrl key on Mac OS X?

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#3656]
From the [Shortcut](https://github.com/nwjs/nw.js/wiki/Shortcut) wiki entry: 

> Supported keys: A-Z, 0-9, **Comma**, Period, Home, End, PageUp, PageDown, Insert, Delete, Arrow keys (Up, Down, Left, Right) and the Media Keys (MediaNextTrack, MediaPlayPause, MediaPrevTrack, MediaStop). Note that Shortcut.key can have exactly one keycode.

What's "Comma"? If you try to add a `Comma+V` shortcut, it'll complain that the key isn't valid, so I thought it that's just a typo in the wiki and should be "Command". It doesn't complain if you use `Command+V` (even on Windows) but it never fires the callback when the keys are pressed (on Mac OS X). 

---

> Modifiers: Ctrl (**On Mac OS X, "Ctrl" correspond to the Command keys on the Macintosh keyboard**), Alt, Shift. Note that Shortcut.key takes zero or more modifiers.

This is really weird. I think the user should have to check the current platform and bind to `ctrl` or `command` themselves accordingly. With the current implementation, how can I bind to `ctrl` on Mac OS X? It seems impossible.
##

**Comment by adam-lynch** [comment]
Ok, sorry I misunderstood one part:

> Note that Shortcut.key can have exactly one keycode.

I assumed this was pointing out that passing `A` on its own was valid but instead it's pointing out that `A+B` (or `Comma+V`) isn't. I've changed it in the wiki to: 

>Note that `Shortcut.key`  has to have exactly one keycode, multiple aren't supported.

Ignore the top half of my original comment :smile:

**Comment by fritx** [comment]
Is `ctrl` key forcely correponded to `cmd` key in Mac as described in wiki? Is it still possible?

**Comment by adam-lynch** [comment]
@fritx as far as I know, you can't bind to `ctrl` on OSX.

**Comment by fritx** [comment]
Oops but seems electron does, why?

**Comment by fritx** [comment]
Now seems both Command/Ctrl work with 0.18.8 in Mac.
I don't have to forcibly replace Command with Ctrl in Mac any more.

**Comment by ghostoy** [comment]
@fritx Actually the behavior was changed since 0.13.0. And now `Command` / `Super` / `Cmd` are the same key. On Windows & Linux, it is WinKey. On Mac, it's Command key.
