### ISSUE TITLE
Window title bar doesn't change

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#3658]
I've got a page that has a `<title>` of "Start" and another that has a title of "End". When I click a link to go from the start page to the end page, the window title bar doesn't change. However, when I switch focus from the window to something else, then back to the window, the title changes.

Edit: seen in 0.12.2
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?
