### ISSUE TITLE
win7 gclient sync fault!!!

### ISSUE THREAD

**Issue by myren** [nwjs/nw.js#3659]
when i check nw.js code on win platform but i get fatal error!
Syncing projects:  30% (28/93) src/third_party/WebKit

src/content/nw (ERROR)
----------------------------------------
[0:00:12] Started.

________ running 'git reset --hard HEAD' in 'D:\project\node-webkit\src\content\
nw'
[0:00:41] HEAD is now at 094674d Fix #3462: support passing zip filename as argu
ment
_____ src\content\nw at origin/nw12
[0:00:43] Switching upstream branch from refs/remotes/origin/nw13 to refs/remote
s/origin/nw12
----------------------------------------
Error: Command git branch -f gclient_nw12 refs/remotes/origin/nw12 returned non-
zero exit status 128 in D:\project\node-webkit\src\content\nw
fatal: Not a valid object name: 'refs/remotes/origin/nw12'.

what i can do??

**Comment by rogerwang** [comment]
It works for me. You can try removing content/nw and try gclient again.

**Comment by myren** [comment]
thanks fo your reply~ i do it by git it alone

**Comment by LeonardLaszlo** [comment]
I have a similar problem. When I run gclient sync --no-history I get this message: 
Error: Command 'git checkout --quiet refs/remotes/origin/nw12' returned non-zero exit status 1 in ~/playground64/node-webkit/src/content/nw
error: pathspec 'refs/remotes/origin/nw12' did not match any file(s) known to git.



Warnings:
Conflicting directory ~/playground64/node-webkit/src/content/nw moved to ~/playground64/node-webkit/_bad_scm/src/content/nwQLK9Nt.

**Comment by chaseWillden** [comment]
I'm getting the same issue as @LeonardLaszlo

**Comment by LeonardLaszlo** [comment]
@chaseWillden I think we should open other issue for that. This one is closed.

**Comment by 823639792** [comment]
try this：https://github.com/nwjs/nw.js/wiki/Building-nw.js#common-errors

**Comment by dariukas** [comment]
Have you tried: gclient sync  --with_branch_heads
