### ISSUE TITLE
require is not define

### ISSUE THREAD

**Issue by qychen1982** [nwjs/nw.js#3661]
在nwjs12中是完全正常的，然后在nwjs13中打开，就出现这个Uncaught ReferenceError: require is not defined，但是很奇怪的是，如果用sublime来运行，又是正常的，就出现在直接文件夹拖拉到nw.exe上，打包后也是这个错误。不知道是什么原因导致的呢？

**Comment by Jackcu** [comment]
same problem with me

**Comment by andresiraola** [comment]
in nw13 requiere was moved to "nw" so try nw.requiere
