### ISSUE TITLE
Problems run a server along with NW.js?

### ISSUE THREAD

**Issue by forhappy** [nwjs/nw.js#3664]
Hi, I encountered a weird problem when I run a server along with NW.js, here is the description.
First of all, I have the package.json file settings:

```
{
    "name": "RegexKit",
    "main": "index.html",
    "version": "0.1.1",
    "node-remote": "<local>",
    "webkit": {
        "page-cache":false
    },
    "window": {
        "toolbar": true,
        "frame": true,
        "width": 1320,
        "height": 768
    }
}
```

Then in the index.html, I wrote the following code according to the issue https://github.com/nwjs/nw.js/issues/2901#issuecomment-68782375 :

```
<!DOCTYPE html>
<html>
<head>
    <script>
        var connect = require('connect');
        var serveStatic = require('serve-static');
        var path = require('path');
        connect().use(serveStatic('./public')).listen(18788);
        if (window.location.href.indexOf('localhost') < 0) {
            window.location = 'http://localhost:18788';
        }
    </script>
</head>
<body>
</body>
</html>
```

Then in the public directory I have a small file index.html file just "<body> It works <body>" etc.

What make me confused is:
When I built the app and open it, nothing showed, it's blank:

<img width="711" alt="node-webkit_and_new_issue_ _nwjs_nw_js" src="https://cloud.githubusercontent.com/assets/706422/8654681/8e76c7be-29be-11e5-8b7c-6759dea6f1fd.png">

However when I connect my any VPN(to US or Beijing) Or even when I opened my Charles then open the app, It did worked as expected and showed "It works"
<img width="714" alt="regex_javascript__python__php__and_pcre_and_regexkit" src="https://cloud.githubusercontent.com/assets/706422/8654752/ef2b3c84-29be-11e5-9a23-1ed15bfd97ba.png">

Is there anything what I'm missing when run a server along with NW.js ? Any help would be much appreciated, thanks ;-) 
##

**Comment by baconface** [comment]
Unsure if it is the issue but you should put your check for localhost in connect's callback for when the server starts. Your code that checks and redirects will likely fire off before your server is started. Thus failing. But if it is in the callback it will only run once the server goes online.

**Comment by Christywl** [comment]
I try your codes, but an error occurs when I start the app, seem 'node-remote' causes it. Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
