### ISSUE TITLE
Cannot extract package when run *.nw in the upstart file

### ISSUE THREAD

**Issue by angelmic** [nwjs/nw.js#3666]
I wrote an application using node-webkit and this application needs to be executed when the ubuntu system boot-up every time. I put the command, `/path/nodewebkit/nw /path/myapp.nw`, into a upstart file, but I got the node-webkit window showed the error message, "Cannot extract package file: /path/myapp.nw". I'm pretty sure that the application works fine when I used the same commands in the terminal. Comparing the difference between the console result and upstart result, I found that in the console result, the node-webkit will extract all files into the folder, `/tmp/.org.chromium.Chromium.xxx`, however, only few files will be extracted to the folder(`/tmp/.org.chromium.Chromium.yyy`) in the upstart result. Please someone give me some hints to solve this issue. Appreciate.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
