### ISSUE TITLE
Launching app results in a blank nw.js window

### ISSUE THREAD

**Issue by hermwong** [nwjs/nw.js#3669]
I've created nwjs app, but when some of my users launch the app they get a blank window that simply displays NW.JS on the screen instead of my app.

Please see the following issues for more details:
1. https://github.com/phonegap/phonegap-app-desktop/issues/362
2. https://github.com/phonegap/phonegap-app-desktop/issues/372
##

**Comment by wholroyd** [comment]
Possible duplicate of https://github.com/nwjs/nw.js/issues/3212

**Comment by hermwong** [comment]
Please see: https://github.com/phonegap/phonegap-app-desktop/issues/362#issuecomment-130775883

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
