### ISSUE TITLE
[nw13] [alpha2] [win] Iframes throw "ReferenceError: nw is not defined"

### ISSUE THREAD

**Issue by Dragory** [nwjs/nw.js#3672]
Error:

```
Uncaught ReferenceError: nw is not defined                      process_main2:1
```

package.json

``` json
{
  "name": "test",
  "main": "index.html"
}
```

index.html

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <iframe src="https://www.google.com/" frameborder="0"></iframe>
</body>
</html>
```

Command line is `path/to/nwjs.exe .`
Local files throw the same error but twice. Nwdisable/nwfaketop/other attributes don't make a difference. Mixed context doesn't have an effect either.
Tested only on Windows 7 Enterprise 32bit (for now) using `nwjs-sdk-v0.13.0-alpha2-win-ia32`.

Possibly related: the iframe does not bypass security restrictions like it did in 0.12 (e.g. google.com doesn't load because of X-Frame-Options set to SAMEORIGIN).
##

**Comment by Christywl** [comment]
I don't see this error on Linux/Windows with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
