### ISSUE TITLE
Enable devtools programmatically

### ISSUE THREAD

**Issue by joshuaterrill** [nwjs/nw.js#3674]
In my manifest I have toolbar and devtools set to false. Is there any way to programatically enable these from inside my app via javascript?

**Comment by jgoalby** [comment]
https://github.com/nwjs/nw.js/wiki/Debugging-with-devtools

**Comment by joshuaterrill** [comment]
Sorry, I left out a big piece of this whole thing, I need to be able to open devtools for the parent window. I have only seen documentation on how to do this for an iframe.

**Comment by paseo** [comment]
try this.create a .bat file to your nwjs exec path. code as fllow:
```
start ./nw.exe --remote-debugging-port=9999
start chrome http://localhost:9999
```

run this bat file.
I'm windows 7
Good luck.

**Comment by joshuaterrill** [comment]
I can't use command line switches like that because I'm using node-webkit-builder.

**Comment by legionsra** [comment]
it is much better if you debug using sublime text 2 or 3. you can build from there directly from your own app and debug on real time.

**Comment by joshuaterrill** [comment]
I am not explaining what I'm trying to accomplish very well. This is a feature to an app. By default I am disabling devtools, and under certain circumstances I need to be able to enable devtools programatically. Only using my app.

**Comment by baconface** [comment]
You should be able to call dev tools programmatically with ```require('nw.gui').Window.get().showDevTools();``` and by default it does it for the main window. Take note by default it will also do it for all windows in the app. The only way to lock it down to a certain window is to make your app appear in a full window iframe and jail that iframe.

**Comment by baconface** [comment]
Also if you wanted remote debugging all you would have to add is ```--remote-debugging-port=9999``` to [chromium-args](https://github.com/nwjs/nw.js/wiki/Manifest-format#chromium-args) in your package.json.

**Comment by adam-lynch** [comment]
What @baconface said
