### ISSUE TITLE
Can a native module be built for both node and nw?

### ISSUE THREAD

**Issue by vasanthps** [nwjs/nw.js#3675]
I am having a requirement where I need to  use a native module in node.js and nw.js. Currently, The only solution I found is to have two copies of native module and build it using node-gyp and nw-gyp and use it separately. Is there any better solution?
##

**Comment by spirodonfl** [comment]
I dunno if this helps but I was able to build a native module using C with node-gyp (on Linux) and it worked fine for me on nwjs v 0.13-beta6

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
