### ISSUE TITLE
Context reset to "window" inside a function

### ISSUE THREAD

**Issue by rawghi** [nwjs/nw.js#3677]
Hello guys,
NW is fantastic. However I'm experiencing an issue and I don't really know if it's a bug or my misunderstangings of base NW principle.
I've also opene a stackoverflow topic with no luck: http://stackoverflow.com/questions/31418841/angularjs-in-node-webkit-function-lose-scope

The problem is:
Whenever I call a child function, it seems that the parent object variables are replaced by the window object. Like the function loose its context, example:
(this is an angular controller)

(function() {
    'use strict';

```
angular
    .module('antApp')
    .controller('VesselNewController', VesselNewController);

function VesselNewController($scope, $rootScope, $state, $stateParams, RenderingService, GameService){
    var self = this;
    self.init = init;
    self.init();

    function init(){
        //here the "self" variable, or whatever the name, becomes the "window" object 
    };
```

})();

Again, I'm sure I'm missing something.
Thanks for you time
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide the full test and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
