### ISSUE TITLE
gui.Shell.openItem not works correctly

### ISSUE THREAD

**Issue by paseo** [nwjs/nw.js#3679]
OS:windows 7
NW version: 0.12.2

I install wamp server and then create a short cut icon on desktop which path is C:\\Users\\paseo\\Desktop\\WampServer64.
Then i create a folder named WampServer64 with same path.

When i use gui.Shell.openItem("C:\\Users\\paseo\\Desktop\\WampServer64"). nwjs start the wamp application instead of open the folder.

**Comment by paseo** [comment]
nwjs implement the gui.Shell.openItem function with Windows system api directly in source code.
And then Windows system open the application.
I try to distinguish the differences of the short-cut link icon and directory with nodejs api.But failed.
Any one can fix it ?

**Comment by baconface** [comment]
If I read right you want to open up the folder in Explorer?

Try:
```gui.Shell.openItem("explorer C:\Users\paseo\Desktop\WampServer64");```
