### ISSUE TITLE
[0.12.2] Webview gets terminated, when onload attribute is present in body tag.

### ISSUE THREAD

**Issue by kamesh-a** [nwjs/nw.js#3681]
Loading these websites in webview tag, terminates the webview.
- https://my.setmore.com/ - we tried removing onload tag it worked 
- https://jersey.java.net/apidocs/latest/jersey/index.html - it didn't work in this case

Development Env Info:
- NWJS 0.12.2
- Mac OS-X Yosemite,  Windows 7 64 bit , 8 64 bit.

Code snippet:

```

var webviewTest = document.createElement('webview');
webviewTest.src = 'https://my.setmore.com/'; // replace the URL with the second one to test as well.
webviewTest.style.width = '100%';
webviewTest.style.height = '100%';
document.body.appendChild(webviewTest)

```
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full test cases to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
