### ISSUE TITLE
why ctrl f5 doesn't work on nw.js

### ISSUE THREAD

**Issue by qiye** [nwjs/nw.js#3685]
Chrome Developer Tools can't be used
##

**Comment by TemaSM** [comment]
All base Chromium hotkeys are disabled for security reasons.
You can bind any key (F5,Ctrl+F5, ...) to open DevTools.

Example code for you:
```javascript
var App = {};
// Node-Webkit binding with GUI
App.NW  = require('nw.gui');
// Node-Webkit Chromium Window binding
App.Window = App.NW.Window.get();
// DevTools handler by Ctrl+D
$(document).bind('keydown', 'ctrl+d', function() {
	App.Window.showDevTools();
});
```

**Comment by Christywl** [comment]
Dev Tools works well for me on nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
