### ISSUE TITLE
WM_CLASS is no longer set

### ISSUE THREAD

**Issue by wnayes** [nwjs/nw.js#3689]
The `WM_CLASS` X property used to be "Nw" in older versions ("node-webkit" days). Now, the property is no longer set. This makes it harder to setup special rules in window managers, for example.

The specific value isn't particularly important, as long as it's predicable.

On Linux, run an instance of nw.js and then use `xprop` to see a listing of all the properties.

I think this might be something you can set through GTK (I was thinking `src\browser\native_window_gtk.cc`).
##

**Comment by jackwilsdon** [comment]
+1 this seems to be the cause of most of the window title problems (Unknown title) as well as the duplicate icon issue.

**Comment by adambro** [comment]
Indeed, it seems to cause issue #3266 among others.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
