### ISSUE TITLE
Include latest > v0.x.x symlink for dl.nwjs.io

### ISSUE THREAD

**Issue by martensms** [nwjs/nw.js#3690]
Hey guys,

I'm currently building up an auto-build stack for debian packages and everything around iojs / nodejs / nwjs. What's missing is a point to figure out what the latest nwjs build is - without knowing the version number.

On iojs and other projects, there's always an SHASUMS256.txt file that you can easily parse with a shell script (without having to have a JSON parser or similar, which eases up integration to existing build chains).

The dl.nwjs.io build server already has a SUMS file (the MD5SUMS.txt), but no entry point on how to figure out what the latest build is. Note that fuzzy-parsing the version in filenames is error-prone and not future-proof, so it's being avoided.

I would instead love to have a simple dl.nwjs.io/latest symlink that points to the correct directory, and each directory having an MD5SUMS.txt file. That way it would be easily integratable without much pain for other build chains.

An example here is the iojs build server setup: https://iojs.org/dist/latest/SHASUMS256.txt
Note that the hash sums text file only has filenames of the parent folder (build version) and no files listed of other versions or previous builds.

Also, you guys are changing the folder structure _every_ single release. Why?

**Comment by martensms** [comment]
*bump*

Any hints? If there's no reply - who is the guy to talk to that manages the nwjs distribution folder?

**Comment by rogerwang** [comment]
fixed. Thanks for your patience.

**Comment by martensms** [comment]
Well, what I basically meant was that in other projects there's a symlink on the server's root folder.

So dl.nwjs.io/latest should point to dl.nwjs.io/v0.13.0 so that it would ease up things to find the latest build in a shell script.

Then, most build servers have inside each build an MD5SUMS file, so that you can easily get always the latest version without any further crawls of sub-URLs or sub-links.

1. Shell scripts look if dl.nwjs.io/latest/MD5SUMS has changed.
2. If md5sums file is changed, check MD5SUMS file for windows/linux/osx.
3. Download the files if version name has also changed and package new things.

Here's an example on how it looks like if it's implemented: [Example update.sh](https://github.com/LazerUnicorns/lycheeJS-runtime/blob/master/iojs/update.sh)
