### ISSUE TITLE
Memory usage issue related to iframes

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#3691]
I develop an app that uses iframes very heavily. There's an outer frame and then an iframe where content is displayed, when users navigate, the src of the iframe is changed to the page they are navigating to and the outer frame remains the same. I've noticed that when I navigate from page to page and use the nwjs's Timeline in the devtools, the documents and memory just keep increasing without getting released, thus the memory use in task manager shows that it keeps increasing as well. From my understanding, when changing the src of an iframe, it should do garbage collection and load the new document.... it doesn't seem like that's happening. 

I've found an issue related to chromium that seems like it could be related, but I figure I would post it here to see if anyone has some input on it.
https://code.google.com/p/chromium/issues/detail?id=359401
https://code.google.com/p/chromium/issues/detail?id=64748
##

**Comment by mscreenie** [comment]
Try using webviews. I'm not sure if it solves the issue entirely. When the webview element is destroyed the process associated to that webview is destroyed also. There are some problems though. Webview does not seem to work as expected if you have basic css transitions. Like toggling between two elements. 

The issue is talked about in several stackoverflow pages, albeit Android webview, but looks to me the same bug:

https://stackoverflow.com/questions/9476151/webview-flashing-with-white-background-if-hardware-acceleration-is-enabled-an
https://stackoverflow.com/questions/15826997/web-view-content-flickering-in-android

**Comment by joshuaterrill** [comment]
Is a webview specific to mobile development? If so, this isn't a mobile app, so I don't think it would work.

**Comment by joshuaterrill** [comment]
My work around for now has been to write a script that runs as a scheduled job to look at how much memory ```nw.exe``` is using. If it exceeds more than X% of the computer's total memory, then ```Window.reloadDev()``` gets called before the next page reload so that webkit releases all of the memory and loads the new page.

**Comment by baconface** [comment]
Webviews are not mobile specific. [More information.](https://developer.chrome.com/apps/tags/webview)

**Comment by joshuaterrill** [comment]
I just created a test case simulating multiple page loads with a webview, it appears the same memory issues persist.
```
<webview id="foo" name="foo" src="http://www.google.com/" style="width:640px; height:480px"></webview>
<button onclick="refresh()">refresh</button>
function refresh() {
    console.log("Refresh");
    document.getElementById("foo").src = "http://google.com";
}
```

**Comment by mscreenie** [comment]
Try removing the element from the dom, then recreate it using vanilla js and not jquery. Check the associated pid to see if its killed.

**Comment by hems** [comment]
@joshterrill window.reloadDev() ? what this is doing?

reloading my index.html file doesn't seem to clean it !

**Comment by makkesk8** [comment]
window.reloadDev() does not destroy the previous document, it will sit there and idle until you exit the app... in fact that's even worse.

**Comment by Christywl** [comment]
I use the codes in https://github.com/nwjs/nw.js/issues/3691#issuecomment-125398281 on Linux with nwjs-sdk-v0.25.0. After click the refresh button, the memory increases, and then it goes down.

**Comment by joshterrill** [comment]
The example I provided was on a windows x64 machine.

**Comment by joshterrill** [comment]
It does appear that with the newer versions of nwjs, the memory issues have been handled. not sure if that's because of chromium or nwjs, but it back when I created this (I think it was 0.12 or 0.13?) it was a problem. I'll close it out now.
