### ISSUE TITLE
clipboard other types than text 

### ISSUE THREAD

**Issue by fithwith** [nwjs/nw.js#3692]
how can I get the clipboard for other types than text.
##

**Comment by baconface** [comment]
As far as I know you cannot in any released version. Unsure about development builds.

**Comment by fritx** [comment]
:+1:

**Comment by daysv** [comment]
I also need this feature.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
