### ISSUE TITLE
How to disable window maximize

### ISSUE THREAD

**Issue by MeowSprite** [nwjs/nw.js#3693]
I wrote a frameless window with a title using '-webkit-app-region:drag' options. And also set the window fixed size. I don't want this window maximized. But when double-clicking the title, it's maximized. 
the follow code is my way to resolve this problem now.
win.on('maximize', function(){
	win.unmaximize();
});

And is there any better solutions? 
Thanks!

**Comment by fritx** [comment]
:+1:

**Comment by zetsingithub** [comment]
:+1:

**Comment by fritx** [comment]
related: #3274
I had a workaround yesterday... hope that helps
