### ISSUE TITLE
File dialog breaks when application is minimized

### ISSUE THREAD

**Issue by jlaplante** [nwjs/nw.js#3696]
Google has not given me any results on this issue, so I suspect it might be a bug.

When I open a file dialog in an NW.js app and then minimize the application (which on OS x can happen accidentally by double clicking the app), when I restore it the file dialog is hidden. I am unable to open the dialog again, or any other file dialogs, until the application has been closed and reopened.

I am using Mac OS X, and building with node-webkit-builder v1.0.12 on Node v0.12.4.

Thanks!
##

**Comment by jlaplante** [comment]
I should have also mentioned that I'm using NW.js v0.12.2.

**Comment by snehasis** [comment]
I am getting the same Issue.
Version : v0.12.3
Platform : Mac OS All version

How to Reproduce : 
1)Create <input type="file"> in a html page
2) Double Click on the file browse option
3) You will see App will get Minimize and Open once again
4) After that you can never open the browse File Window until close the app and restart.

Anyone from the team can help on this ?

**Comment by Christywl** [comment]
It works fine for me on Mac with nwjs-sdk-v0.25.0. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
