### ISSUE TITLE
nwworkingdir is not working

### ISSUE THREAD

**Issue by ognb** [nwjs/nw.js#3701]
nwworkingdir is not working v0.12
##

**Comment by legionsra** [comment]
Try this workaround:
`var dir = require("path").dirname(process.execPath).replace(/\\/g,"/")`

**Comment by ognb** [comment]
no difference. It us working v0.11

**Comment by chaseWillden** [comment]
Is this still an issue?

**Comment by Christywl** [comment]
It works well on Linux/Windows with nwjs-sdk-v0.22.3.
