### ISSUE TITLE
nwsaveas removing extention

### ISSUE THREAD

**Issue by ognb** [nwjs/nw.js#3702]
nwsaveas="filename.txt" it will be "filename" why?
##

**Comment by conceptualspace** [comment]
try adding an accept attribute to your input (http://www.w3schools.com/tags/att_input_accept.asp) and just provide the extension, ex, `accept=".txt"`

**Comment by Christywl** [comment]
should be duplicate of #4460

**Comment by Christywl** [comment]
close until there is more information.
