### ISSUE TITLE
Onclick not working?

### ISSUE THREAD

**Issue by pillows** [nwjs/nw.js#3703]
This is mainly my demo:

    $(document).ready(function() {

        $("#changer").load("./install.html");
	    $("#step-1").on("click", function() {
		     alert(1);
	    });
     });

I have a demo of what I have so far here: https://mega.co.nz/#!DcIBjbiT!8gReRNP9TKi5i0CLHWEl6yhWPeHnpFw3Wlhy-ZssHig

Whenever the #step-1 button is clicked nothing happens. Now I don't believe this is a jquery problem since it works fine on the console when I copy and paste the #step-1 click function.

This might not be the right place to post I understand but this problem has been bugging me for days :(

**Comment by Destreyf** [comment]
@pillows this appears to be a chicken and egg problem, where is your step-1 button located? inside of install.html?  if so, you need to put a callback on your load, to fire your event binding after its loaded.

**Comment by pillows** [comment]
@Destreyf Thank you for that solution. This will teach me to look at the jquery docs next time :P
