### ISSUE TITLE
ui-select not working

### ISSUE THREAD

**Issue by benag** [nwjs/nw.js#3704]
tryied ui-select angular wrapper for select2.
Doesnt seem to work inside node-webkit the same code works well in web:
http://plnkr.co/edit/mndGwxilzqW6wuEIC6lj?p=preview
##

**Comment by Christywl** [comment]
I try this url on Linux/Windows with nwjs-sdk-v0.22.3. Seem it works well. The color could be selected.

**Comment by Christywl** [comment]
close until there is more information.
