### ISSUE TITLE
`<object>` tag sometimes not working

### ISSUE THREAD

**Issue by jonathan-roy** [nwjs/nw.js#3705]
`<object>` tag for loading SWF is sometimes not working correctly, nothing appears and when I right click on it I can see a 'Movie not loaded...' message in the Flash player menu. Below are some examples of code that do not work, tested with nw.js v0.12.2 on Windows and OS X.

Example 1: should play a video. Even when removing the 'FlashVars' param, we should see a flash player with a black background and some controls but nothing appears. Works well with Chrome web browser.
```html
<object type="application/x-shockwave-flash">
    <param name="movie" value="http://flv-player.net/medias/player_flv_maxi.swf">
    <param name="FlashVars" value="flv=http%3A//vdtools.caldera.com/bugnwjs/barsandtone.flv&amp;autoplay=1">
</object>
```

Example 2: should also play a video. Works well in Chrome web browser.
```html
<object width="400" height="225">
    <param name="allowfullscreen" value="true">
    <param name="allowscriptaccess" value="always">
    <param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=2012469&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=cfb915&amp;fullscreen=1">
</object>
```

And package.son:
```json
{
  "name": "nw-demo",
  "version": "0.0.1",
  "main": "index.html",
  "webkit": { "plugin": true }
}
```

**Comment by Spiffyk** [comment]
I've got this problem, too. Does not work in an iframe either.

**Comment by jlcastillo** [comment]
This might be related to these bugs:

https://code.google.com/p/chromium/issues/detail?id=466456ç
https://code.google.com/p/chromium/issues/detail?id=464629

I solved it by following the directions in this issue:

https://github.com/nwjs/nw.js/issues/2923

In short, use the Pepper Flash plugin instead of Adobe's one. Add this to the package.json

Linux:
 "chromium-args": "--ppapi-flash-path=plugins/libpepflashplayer.so --ppapi-flash-version=17.0.0.134"  

Windows:
 "chromium-args": "--ppapi-flash-path=plugins/pepflashplayer.dll --ppapi-flash-version=17.0.0.134"

**Comment by jonathan-roy** [comment]
Thank you for your answer! I downloaded the PPAPI version of flash player from the Adobe's official website, copied it in a 'plugins' folder located in my NW project folder, then updated the package.json accordingly, but SWFs are not loaded anymore... Am I missing something?

**Comment by jlcastillo** [comment]
@jonathan-roy I tested your 2 examples and they work ok without any modification, using nwjs 12.0 and pepflashplayer.dll v19 from Chrome 46 in Windows 10. 

Remember to put the DLL in the plugins subfolder of the nw.exe's folder. This is my package.json:

{
  "name": "nwclient",
  "description": "nwclient",
  "version": "0.1",
  "main": "main.html",
  "single-instance": false,
  "node-remote": "*",
  "webkit": {
    "plugin": true
  },
  "window": {
    "show": true,
    "transparent": false,
    "toolbar": true,
    "frame": true,
    "position": "center",
    "width": 900,
    "height": 700,
    "min_width": 900,
    "min_height": 700
  },
  "chromium-args": "--ppapi-flash-path=plugins/pepflashplayer.dll" 
}

Please be careful with the "node-remote": "*"  param, as it might pose a security risk.

**Comment by jonathan-roy** [comment]
Ok sorry I copied the DLL in the wrong folder, now it's working well! Thank you very much!
