### ISSUE TITLE
gui.App.clearCache() would crash

### ISSUE THREAD

**Issue by fritx** [nwjs/nw.js#3707]
I'm on OSX 10.10.3
When I commented that line, it began to work
##

**Comment by chaseWillden** [comment]
Is this still an issue?

**Comment by phungne** [comment]
Any solution for this issue??

**Comment by Christywl** [comment]
I don't meet crash issue when using nw.App.clearCache() on Linux/Mac with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
