### ISSUE TITLE
TCP socket can not be opened localhost

### ISSUE THREAD

**Issue by RIAEvangelist** [nwjs/nw.js#3708]
due to io.js integration

If the client machine is not connected to a network, TCP sockets do not work.

An example is to install [node-ipc](https://github.com/RIAEvangelist/node-ipc) npm install node-ipc

then run the basic TCP server and clients with network connection and without.

tested using iojs install on windows 7 x32
works with network connection
can not connect without network connection even on localhost

tested using nw.js with both iojs and nodejs install on windows 7 x32
nw.js like atom uses io.js on its back end.
works with network connection
can not connect without network connection even on localhost

referenced here in the node-ipc module RIAEvangelist/node-ipc#32
and here on atom electron atom/electron#2299
and here on io.js nodejs/io.js/issues/2237

figured I would share the fact that this bug exsits incase anyone else runs into this issue.
##

**Comment by Christywl** [comment]
Seem this works well on my Windows 8 with nwjs-sdk-v0.22.3. 
1. install node-ipc
2. start server: node example\TCPSocket\basic\world-server.js
3. start the client with nwjs(with or without PC internet connection)

Result: could receive and get a message "hello world!"

**Comment by Christywl** [comment]
close until there is more information.
