### ISSUE TITLE
Ctrl clicking of middle mouse clicking does not trigger new-win-policy in 0.12.2

### ISSUE THREAD

**Issue by aymanar** [nwjs/nw.js#3710]
Ctrl clicking of middle mouse clicking does not trigger new-win-policy in 0.12.2. It replaces the entire node-webkit contain with the external website.
##

**Comment by aymanar** [comment]
Actually, merely clicking a link such a:
<a href="http://www.cnn.com">CNN</a>
replaces the entire container, and doesnt trigger new-win-policy

**Comment by sumit6b** [comment]
Also facing this issue in version 0.19.5

**Comment by Christywl** [comment]
It works well on Windows/Linux on nwjs-sdk-v0.22.3. `new-win-policy` could be triggered.
```
<!DOCTYPE html>
<html>
<head>
<script>
nw.Window.get().on('new-win-policy',function(frame,url,policy){
policy.ignore();
nw.Shell.openExternal(url);
});
</script>  
</head>
<body>
<a href="https://www.baidu.com/" target='_blank'>https://google.com/</a>
</body>
</html>
```

**Comment by Christywl** [comment]
close until there is more information.
