### ISSUE TITLE
Temp files not being deleted automatically when windows shuts down and force closes the app.

### ISSUE THREAD

**Issue by shovonnn** [nwjs/nw.js#3711]
I have created a small app that runs as a windows startup program. When i shut down windows, temp files created by it doesn't get deleted. so it has to create new temp files on each startup. 

![temp](https://cloud.githubusercontent.com/assets/5825667/8893583/b6792c40-33b7-11e5-8fe2-4cf06e9b1d03.PNG)
##

**Comment by shovoncoding** [comment]
i tried listening for exit signal on the process and calling both app.quit and closeAllWindows functions but still no luck :(

**Comment by shaynem** [comment]
+1

**Comment by shaynem** [comment]
not zipping your app isn't a solution FYI

Some people need or want to use the ZIP although it takes a few seconds to
load (or un-useable for larger apps)

i.e it's all good and well not to create temporary files when not zipping
the app and using engima - however to automate the build process in enigma
each file needs to be added to the XML evb - so if you create a new file in
your app you have to add it to the evb file so you can use the command line
utility to build it - it's a pain. (also not sure about read/write within
the enigma virtual box)

**Comment by baconface** [comment]
Windows is responsible for clearing temp files when you shut down or restart your computer. Make sure you do not have settings on that disable deletion of files or if there are system permissions which deny the deletion of temp files. Your app should never modify such settings on behalf of the user as that could be unwanted by said end user.

**Comment by mib4fun** [comment]
How can i achieve this with nwjs ? any hints ?

**Comment by rahulsharma841990** [comment]
is there any way to delete the app temp files on app close?

**Comment by Christywl** [comment]
I try the simple app with nwjs-sdk-v0.22.3. The temp folder could be deleted automatically when the app closes normally.

**Comment by Christywl** [comment]
close until there is more information.
