### ISSUE TITLE
Security issue: .git directory is publicly accessible

### ISSUE THREAD

**Issue by mpreziuso** [nwjs/nw.js#3713]
Hi @rogerwang, I just noticed that the NW.js .git directory is publicly accessible at http://nwjs.io/.git and this is dangerous as it might expose sensitive information.
More info at http://www.jamiembrown.com/blog/one-in-every-600-websites-has-git-exposed/

**Comment by rogerwang** [comment]
Thanks for reporting. It's fixed now.
