### ISSUE TITLE
Can a started nw.js app with single-instance, bring to front again and with new arguments?

### ISSUE THREAD

**Issue by rufushuang** [nwjs/nw.js#3714]
open event was not fired when i run nw.exe from command line again.
In app document, i found it said:

Note: open event is sent only if your app is a standalone app.

But, why standalone app is a must?
##

**Comment by Christywl** [comment]
Here is my result, it works well with nwjs-sdk-v0.22.3, the file path could be returned:
index.html:

<script>
nw.App.on('open', function(cmd){
document.write(cmd);
});
</script>
My steps:

1. Start the app: nw.exe App/
2. Start the app again: nw.exe App/ --foo 1.html
3. You will see the full cmd line in the app page

**Comment by Christywl** [comment]
close until there is more information.
