### ISSUE TITLE
Add book to list of available resources?

### ISSUE THREAD

**Issue by paulbjensen** [nwjs/nw.js#3715]
Hi,

I'm the author of "NW.js in action" - http://manning.com/jensen, a book that I'm currently writing.

I'd like to provide a link to the book on the website, so that people interested in NW.js will know about the book and can have a look to find out more. In return, Manning will offer a code that can be used to purchase the book at a discounted price.

I can submit a PR, but I thought it would be best to ask first if this is ok.
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
