### ISSUE TITLE
window.maximize should not work as a toggle

### ISSUE THREAD

**Issue by gera2ld** [nwjs/nw.js#3716]
Since there are both `window.maximize` and `window.unmaximize`, I think they should just work as the method names mean.

Actual: `window.maximize` works like a toggle on OSX.

Expected: `window.maximize` should only maximize the windows instead of either maximize or unmaximize them.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Christywl** [comment]
`win.maximize()` works fine on Mac with nwjs-sdk-v0.26.3. And `win.unmaximize()` is deprecated since 0.13.0. See http://docs.nwjs.io/en/latest/References/Window/#winunmaximize.

**Comment by Christywl** [comment]
close until there is more information
