### ISSUE TITLE
nwjs-v0.13.0-alpha3 gclient sync error

### ISSUE THREAD

**Issue by jtg-gg** [nwjs/nw.js#3717]
I can't gclient sync 
keep getting this error in 'src/third_party/webrtc' and 'src/third_party/libjingle/source/talk', 
I've deleted the whole webrtc and talk folder, and still getting this error
@rogerwang any idea how to fix this ?

src/third_party/webrtc (ERROR)
----------------------------------------
[0:00:21] Started.
[0:00:26] _____ src/third_party/webrtc : Attempting rebase onto 1cb9d1223356c551a92bd9da41a3eddce15bee64...
[0:00:26] 
[0:00:26] Rebase produced error output:
fatal: Needed a single revision
Does not point to a valid commit: 1cb9d1223356c551a92bd9da41a3eddce15bee64
----------------------------------------
Error: 65> Unrecognized error, please merge or rebase manually.
65> cd /Users/Work/chromium/node_webkit/src/third_party/webrtc && git rebase --onto 1cb9d1223356c551a92bd9da41a3eddce15bee64 refs/remotes/origin/master

and alos this

src/third_party/libjingle/source/talk (ERROR)
----------------------------------------
[0:00:10] Started.
[0:00:11] _____ src/third_party/libjingle/source/talk : Attempting rebase onto 411c9af27df0d133df43df2d1a49962b56f7d7ac...
[0:00:11] 
[0:00:11] Rebase produced error output:
fatal: Needed a single revision
Does not point to a valid commit: 411c9af27df0d133df43df2d1a49962b56f7d7ac
----------------------------------------
Error: 36> Unrecognized error, please merge or rebase manually.
36> cd /Users/Work/chromium/node_webkit/src/third_party/libjingle/source/talk && git rebase --onto 411c9af27df0d133df43df2d1a49962b56f7d7ac refs/remotes/origin/master

**Comment by rogerwang** [comment]
Please try '--with_branch_heads' with gclient.

**Comment by jtg-gg** [comment]
@rogerwang thx it works

**Comment by wpp2014** [comment]
I try '--with_branch_heads' with gclient but failed:
wpp@wpp:~/Work/nw13$ gclient sync --with_branch_heads
Syncing projects: 100% (80/80), done.                                                

________ running '/usr/bin/python src/build/landmines.py' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/build/download_sdk_extras.py' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/chrome/installer/linux/sysroot_scripts/install-debian.wheezy.sysroot.py --running-as-hook' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/build/vs_toolchain.py update' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' in '/home/wpp/Work/nw13'
Clang already at 233105-2

________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/build/util/lastchange.py -s src/third_party/WebKit -o src/build/util/LASTCHANGE.blink' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s src/buildtools/win/gn.exe.sha1' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s src/buildtools/mac/gn.sha1' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s src/buildtools/win/clang-format.exe.sha1' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s src/buildtools/mac/clang-format.sha1' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/third_party/binutils/download.py' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-eu-strip -s src/build/linux/bin/eu-strip.sha1' in '/home/wpp/Work/nw13'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-drmemory -s src/third_party/drmemory/drmemory-windows-sfx.exe.sha1' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/build/get_syzygy_binaries.py --output-dir=src/third_party/syzygy/binaries --revision=24bc1affd8aecfdcbe87c0802372ae766bf2507b --overwrite' in '/home/wpp/Work/nw13'
INFO:get_syzygy_binaries.py:Output directory does not exist, skipping cleanup.

________ running '/usr/bin/python src/build/get_syzygy_binaries.py --output-dir=src/third_party/kasko --revision=b8adaf37ad3beae939ee2db5ae9c0f8b380d2060 --resource=kasko.zip --resource=kasko_symbols.zip --overwrite' in '/home/wpp/Work/nw13'
INFO:get_syzygy_binaries.py:Unexpected output directory, skipping cleanup.

________ running 'download_from_google_storage --no_resume --platform=win32 --directory --recursive --no_auth --num_threads=16 --bucket chromium-apache-win32 src/third_party/apache-win32' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/third_party/mojo/src/mojo/public/tools/download_shell_binary.py --tools-directory=../../../../../../tools' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/third_party/instrumented_libraries/scripts/download_binaries.py' in '/home/wpp/Work/nw13'

________ running '/usr/bin/python src/content/nw/tools/patcher.py --patch-config src/content/nw/patch/patch.cfg' in '/home/wpp/Work/nw13'
/usr/bin/python: can't open file 'src/content/nw/tools/patcher.py': [Errno 2] No such file or directory
Error: Command '/usr/bin/python src/content/nw/tools/patcher.py --patch-config src/content/nw/patch/patch.cfg' returned non-zero exit status 2 in /home/wpp/Work/nw13

**Comment by andresiraola** [comment]
@wpp2014 for now, you have to clone nwjs@nw13 manually into src/content/nw

For more details, check this: http://buildbot-master.node-webkit.org:8010/builders/nw13_sdk_win64/builds/15

i believe it will be added to the DEPS file in the next release.

**Comment by wpp2014** [comment]
I clone nwjs@nw13、nwjs@v8、nwjs@node manually into src and build. But failed.
../../gin/public/context_holder.h:22:32: error: no member named 'kDebugIdIndex' in 'v8::Context'
  kDebugIdIndex = v8::Context::kDebugIdIndex,
                  ~~~~~~~~~~~~~^
In file included from ../../gin/modules/timer.cc:5:
In file included from ../../gin/modules/timer.h:13:
../../gin/wrappable.h:72:17: error: no template named 'WeakCallbackInfo' in namespace 'v8'; did you mean 'WeakCallbackData'?
      const v8::WeakCallbackInfo<WrappableBase>& data);
            ~~~~^~~~~~~~~~~~~~~~
                WeakCallbackData
../../v8/include/v8.h:444:7: note: 'WeakCallbackData' declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:5:
In file included from ../../gin/modules/timer.h:13:
../../gin/wrappable.h:72:17: error: too few template arguments for class template 'WeakCallbackData'
      const v8::WeakCallbackInfo<WrappableBase>& data);
                ^
../../v8/include/v8.h:444:7: note: template is declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:5:
In file included from ../../gin/modules/timer.h:13:
../../gin/wrappable.h:74:17: error: no template named 'WeakCallbackInfo' in namespace 'v8'; did you mean 'WeakCallbackData'?
      const v8::WeakCallbackInfo<WrappableBase>& data);
            ~~~~^~~~~~~~~~~~~~~~
                WeakCallbackData
../../v8/include/v8.h:444:7: note: 'WeakCallbackData' declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:5:
In file included from ../../gin/modules/timer.h:13:
../../gin/wrappable.h:74:17: error: too few template arguments for class template 'WeakCallbackData'
      const v8::WeakCallbackInfo<WrappableBase>& data);
                ^
../../v8/include/v8.h:444:7: note: template is declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:5:
In file included from ../../gin/modules/timer.h:13:
../../gin/wrappable.h:76:7: error: no type named 'Global' in namespace 'v8'
  v8::Global<v8::Object> wrapper_;  // Weak
  ~~~~^
../../gin/wrappable.h:76:13: error: expected member name or ';' after declaration specifiers
  v8::Global<v8::Object> wrapper_;  // Weak
  ~~~~~~~~~~^
In file included from ../../gin/modules/timer.cc:8:
In file included from ../../gin/object_template_builder.h:13:
../../gin/function_template.h:55:17: error: no template named 'WeakCallbackInfo' in namespace 'v8'; did you mean 'WeakCallbackData'?
      const v8::WeakCallbackInfo<CallbackHolderBase>& data);
            ~~~~^~~~~~~~~~~~~~~~
                WeakCallbackData
../../v8/include/v8.h:444:7: note: 'WeakCallbackData' declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:8:
In file included from ../../gin/object_template_builder.h:13:
../../gin/function_template.h:55:17: error: too few template arguments for class template 'WeakCallbackData'
      const v8::WeakCallbackInfo<CallbackHolderBase>& data);
                ^
../../v8/include/v8.h:444:7: note: template is declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:8:
In file included from ../../gin/object_template_builder.h:13:
../../gin/function_template.h:57:17: error: no template named 'WeakCallbackInfo' in namespace 'v8'; did you mean 'WeakCallbackData'?
      const v8::WeakCallbackInfo<CallbackHolderBase>& data);
            ~~~~^~~~~~~~~~~~~~~~
                WeakCallbackData
../../v8/include/v8.h:444:7: note: 'WeakCallbackData' declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:8:
In file included from ../../gin/object_template_builder.h:13:
../../gin/function_template.h:57:17: error: too few template arguments for class template 'WeakCallbackData'
      const v8::WeakCallbackInfo<CallbackHolderBase>& data);
                ^
../../v8/include/v8.h:444:7: note: template is declared here
class WeakCallbackData : public PhantomCallbackData<P> {
      ^
In file included from ../../gin/modules/timer.cc:8:
In file included from ../../gin/object_template_builder.h:13:
../../gin/function_template.h:59:7: error: no type named 'Global' in namespace 'v8'
  v8::Global<v8::External> v8_ref_;
  ~~~~^
../../gin/function_template.h:59:13: error: expected member name or ';' after declaration specifiers
  v8::Global<v8::External> v8_ref_;
  ~~~~~~~~~~^

**Comment by Ajeey** [comment]
@andresiraola getting 404 for the link that you mentioned. Please share updated link.

**Comment by Ajeey** [comment]
@wpp2014 getting the same `/usr/bin/python: can't open file 'src/content/nw/tools/patcher.py': [Errno 2] No such file or directory`. How did you resolve it?

**Comment by wpp2014** [comment]
I clone nwjs and checkout nw13, then move it to src/content/nw @Ajeey
