### ISSUE TITLE
Really weird screen capturing issue with chooseDesktopMedia with Microsoft Office products

### ISSUE THREAD

**Issue by eabovsky** [nwjs/nw.js#3719]
I've been playing with the chooseDesktopMedia functionality for capturing a desktop or window feed for a desktop sharing application. It works pretty well, but then a really strange behavior surfaced. When running on windows, sharing a Microsoft Office window doesn't work right a lot of the time. The behavior I get is that the feed just freezes. For example, in word, when I scroll the page down, the captured content doesn't update - it'll just be stuck on the previous page, yet, if I have my mouse cursor over the content, it still tracks its motion just fine. I've been able to reproduce this on multiple windows machines with office.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
