### ISSUE TITLE
'require is not defined' on nwjs-v0.13.0-alpha3 

### ISSUE THREAD

**Issue by jtg-gg** [nwjs/nw.js#3720]
I've 'require is not defined' on my java-script when running it on nwjs-v0.13.0-alpha3
the java script is inside an html file, it is working fine with nwjs-v0.12
anybody know how to fix it ?

this is what I'm trying to do
var gui = require('nw.gui');

**Comment by joshuaterrill** [comment]
Do me a favor and type in ```typeof process``` into the console. What does it return?

**Comment by jtg-gg** [comment]
@joshuaterrill it return "undefined"

**Comment by siddhartha-gupta** [comment]
Please refer to following discussion - https://groups.google.com/forum/#!topic/nwjs-general/3vUVKsDOZhY

**Comment by joshuaterrill** [comment]
So with 0.13 are we going to have to change the way that we check to see if we're in webkit and do requires? Right now, it seems most people use ```if (typeof process !== "undefined")``` to check for webkit.
