### ISSUE TITLE
Is there any way to use separate cookies in different windows?

### ISSUE THREAD

**Issue by beta** [nwjs/nw.js#3724]
I'm displaying a web page in a `<iframe>`, and using `gui.Window.open` to open more windows displaying the same page. However all the windows share the same cookies, which means after I logged in one of the pages using an account, all the pages will be logged in with the same account. I want to make the cookies separate in different windows, how can I achieve this? Any ideas and suggestions will be appreciated.
##

**Comment by mscreenie** [comment]
See Webview with partitions. 

https://developer.chrome.com/apps/tags/webview


```
Storage partition ID used by the webview tag. If the storage partition ID starts with persist: (partition="persist:googlepluswidgets"), the webview will use a persistent storage partition available to all guests in the app with the same storage partition ID. If the ID is unset or if there is no 'persist': prefix, the webview will use an in-memory storage partition. This value can only be modified before the first navigation, since the storage partition of an active renderer process cannot change. Subsequent attempts to modify the value will fail with a DOM exception. By assigning the same partition ID, multiple webviews can share the same storage partition.


```

**Comment by bachel** [comment]
in NW12 all webviews share cookies even with different partition. In nw13 alfa2 different partition mean different cookie storage, but cookies are lost after application is closed.

**Comment by bachel** [comment]
For different windows you can use --data-path argument when executing your app. This create new application profile.
```javascript
var child_process = require('child_process')
var path = require('path');
var profilePath = utils.path.join(gui.App.dataPath,Math.random());
var child = child_process.spawn(process.execPath, ["--data-path="+profilePath,"],{detached: true});
 ```

**Comment by genesix-eu** [comment]
Did this changed or bachel answer still applies to newer versions?
