### ISSUE TITLE
Toolbar not showing in Alpha

### ISSUE THREAD

**Issue by Septimus** [nwjs/nw.js#3725]
I tried finding something about this but wasn't able to find anything. I have true set on the toolbar in package.json but it is not showing up at all. Same with other fields like resizable. Worked fine for me in v0.12 but the package.json I had in there doesn't work in the alpha. The only reason why I switched to the new verison is I was getting verison mismatch errors with node modules. Thank you for any help and answers to this problem.

**Comment by rdtsc** [comment]
This is addressed in the [release notes](https://groups.google.com/forum/#!msg/nwjs-general/zeC6SedUSFY/BlumrYJeVHYJ):

> There are 2 builds for each platform - normal build and sdk build. **Normal build doesn't have devtools, only SDK build does**. lt can be opened by pressing F12 (Cmd-Alt-I on OSX). SDK package will also have more development tools to be exposed in the following releases.

---
**SDK Builds**:
- http://dl.nwjs.io/v0.13.0/alpha2/nwjs-sdk-v0.13.0-alpha2-win-x64.zip
- http://dl.nwjs.io/v0.13.0/alpha2/nwjs-sdk-v0.13.0-alpha2-osx-x64.zip
- http://dl.nwjs.io/v0.13.0/alpha2/nwjs-sdk-v0.13.0-alpha2-linux-x64.tar.gz

**Comment by erik-reppen-discoveryusa** [comment]
I just recently thought this was broken even in the SDK given prior experience with nw.js. It's just confusing on OS-X because there is no actual toolbar and it takes a while to open dev tools the first time.
