### ISSUE TITLE
showDevTools window open happens too slowly to catch early errors

### ISSUE THREAD

**Issue by hartsantler** [nwjs/nw.js#3726]
using the following `require('nw.gui').Window.get().showDevTools()` to open the javascript debugger when a window first loads up will fail to appear quickly enough to catch early errors in javascript run from the HTML `body` onload event.

``` html
<html>
<script>
require('nw.gui').Window.get().showDevTools()
var throws_error = function () { a.b.c = 1 }
</script>
<body onload="throws_error()">
</body>
</html>
```

a solution could be a simple command line option `--devtools` that brings up the developer tools before the main NW app window.
##

**Comment by egauci** [comment]
Here's how I deal with this. I make a little menu and attach it to a tray icon:

    var tray;
    var gui = global.window.nwDispatcher.requireNwGui();
    function createDevMenu() {
        var menu = new gui.Menu();
        menu.append(new gui.MenuItem({label: 'Developer tools'}));
        menu.append(new gui.MenuItem({label: 'Reload'}));
        menu.items[0].click = function() {
          gui.Window.get().showDevTools();
        };
        menu.items[1].click = function() {
          gui.Window.get().reload();
        };
        tray = new gui.Tray(
          // the tray variable must be declared outside this function
          // to avoid garbage collection.
          {
            title: '',
            icon: 'winicon/tray.png',
            menu: menu,
            iconsAreTemplates: false
          });
        tray.tooltip = 'MyApp';
    }
    createDevMenu();

I can then open dev tools, set breakpoints, and reload the app.

**Comment by hartsantler** [comment]
@egauci  i tried it, and your solution using a tray applet fails to with Gnome Desktop on Linux.  (nothing happens when clicking the applet)

your solution also requires a few clicks: click the applet, then click to reload the webpage. 
 
What i am looking for is a simple automated way to launch my webpage and devtools from the command line, right when NW.js startsup, because if there are errors early on somewhere in my javascript, i want to see those errors in the devtools window and have break points work.

I know that NW.js prints all debugging info into the terminal from which it was launched, but breakpoints will not work until the devtools window is ready.

**Comment by egauci** [comment]
@hartsantler did you right-click? On Windows 7 you have to right-click on the tray icons. I don't know about Gnome Desktop on Linux.

I hear you about what you want. I use this technique specifically for debugging startup code. The reload restarts the page while devTools are already open and breakpoints in the startup code will work. You're right, it takes clicks :(

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
