### ISSUE TITLE
snapshot can't load when open a new window

### ISSUE THREAD

**Issue by SholvaBai** [nwjs/nw.js#3727]
when I use [gui.Window.open()]  to open a window,require('nw.gui').Window.get().evalNWBin(null,"js.bin") can't work!

**Comment by rufushuang** [comment]
if page is quite complicated, you should use setTimeout trick
maybe take look at this?
https://github.com/nwjs/nw.js/issues/827

**Comment by SholvaBai** [comment]
@rufushuang  it is ok, thanks!
