### ISSUE TITLE
Main process hang

### ISSUE THREAD

**Issue by KodekPL** [nwjs/nw.js#3729]
Running nwjs 0.12.2 on Windows 7.

**Issue:** When running application and closing it with system close button the main process (nw.exe) stays and it is never terminated unless manually.
The reason for the process to stay running is x360ce (https://github.com/x360ce/x360ce) application. Because x360ce application is working as intended I am submitting this issue here.
I can reprocude this error every single time when using x360ce application.

NWJS process have no reason to stay on after the application has been closed and should remove the main process. Because of the main process hang, the application cannot be run again correctly and requires manual removal of nw.exe process.

I can provide additional information if needed.

**Comment by rimlin** [comment]
+1
Windows 7, nwjs v0.12.0
