### ISSUE TITLE
DevTools - Debugger still not ready after devtools-opened event fires

### ISSUE THREAD

**Issue by JavaScriptDude** [nwjs/nw.js#3730]
When debugging boot code of a nw.js app, the debugger in DevTools is not ready to execute breakpoints making it difficult to debug boot code.

I have created [a test case](https://github.com/JavaScriptDude/node-chromium-tests/tree/master/nwjs/dev-tools-local/DevToolsBreakTest) to illustrate the issue.

In my opinion, the devtools-opened event should not fire until the debugger is fully ready to assert breakpoints. There is a workaround as illustrated in my testcase but its still quite weak and prone to confuse many nw.js application developers.
##

**Comment by Christywl** [comment]
'devtools-opened' is deprecated since 0.13.0. Use the callback passed to win.showDevtools instead. Please see the doc: http://docs.nwjs.io/en/latest/References/Window/#event-devtools-openedurl .
Please try this on the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
