### ISSUE TITLE
*.swf file can not show in developer tools network tab, and can not be cached.

### ISSUE THREAD

**Issue by eddieyang** [nwjs/nw.js#3733]
nw.js: 0.12.3
system: win7 64bit

package.json:
"chromium-args": "--enable-application-cache --data-path='data/'"

I used nw.js browsing our website.

Usually, all web site *.swf file, which will be list at developer tools network tab, but i cant see in the nw.js dev tools.

And every times, I find every *.swf resource, can not be cached; only *.swf can not be cached,
our web site swf file (flash) is so lager and provide some main function for us, 
it is very disturbing that the flash files can not be cached and affect our user experience much.

Any ideas and suggestions will be appreciated, thanks.

![2015-08-06_11-12-09](https://cloud.githubusercontent.com/assets/7836285/9103122/fa233670-3c2c-11e5-9b87-b8a8c4929162.png)
##

**Comment by Christywl** [comment]
Seem this works well for me with nwjs-sdk-v0.22.3. Please try the latest nwjs build.
![image](https://cloud.githubusercontent.com/assets/20039821/26518344/59f79584-42e1-11e7-979b-c3aaf34f100e.png)

**Comment by Christywl** [comment]
close until there is more information.
