### ISSUE TITLE
snapshot of a div, not whole page

### ISSUE THREAD

**Issue by rufushuang** [nwjs/nw.js#3735]
We can take snap shot of window by capturePage
But is it possible to just shot a div instead of whole page?

Furthermore, if the div is wider / higher than the window size?
##

**Comment by rufushuang** [comment]
found a solution by using html2canvas. Include the html2canvas.js on webpage side, not node side. Then:


    html2canvas($('div#main')).then(function(canvas) {
      var dataurl = canvas.toDataURL();
      dataurl = dataurl.replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
      require("fs").writeFile("C:\\out.png", dataurl, 'base64', function(err) {
        console.log(err);
      });
    }).catch(function(e) {
      console.log(e);
    });


But further, instead of using this directly, can this be an initial feature supported by nw.js?

**Comment by xuanhun** [comment]
There's no perfect way to do it.
