### ISSUE TITLE
Predictable Installer URLs

### ISSUE THREAD

**Issue by jacobpurcell** [nwjs/nw.js#3737]
Not sure if this issue is better off in the https://github.com/nwjs/npm-installer repo, but...

There's a few npm packages out there, such as nw-builder, for managing nwjs as a node dependency.  To do this, they assume a predictable url for the different installer versions.

With the latest release the url format has changed slightly (alpha builds are contained in sub-directories).  It might be best to come up with a predictable url format for these tools, or perhaps provide a lookup somewhere.
##

**Comment by ayushmxn** [comment]
https://nwjs.io/versions
The file contains all nwjs version info
