### ISSUE TITLE
nwjs can detect system login username?

### ISSUE THREAD

**Issue by oukan** [nwjs/nw.js#3738]
I want to get system login username in nwjs app, how can I do?
thank you.
##

**Comment by tmfksoft** [comment]
Hi, Your best bet would be StackOverflow for this question :P 
For Windows (at least) theres process.env.username, I assume something similar for other platforms.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
