### ISSUE TITLE
[nw13] no nw.require when using manifest.json

### ISSUE THREAD

**Issue by Imskull** [nwjs/nw.js#3750]
I am porting my chrome app with NWJS, my app is using NACL on chrome, so I need to write some native code for NWJS as an addon, but it seems nw.require is undefined when using manifest.json. It's ok when using package.json. 

How can I get nw.require defined? or it's not supported as of now? thanks.

**Comment by wjmjimmie** [comment]
After I add 'node' in permissions of manifest.json, I can get nw.require function.

But I can't nw.require javascript file,  like ```nw.require('./test.js')``` . Only can I require builtin modules, like fs, os, process and so on.

**Comment by Imskull** [comment]
Ok, my fault, forgot the `node` permission.

I use nw.require to load addons only.
