### ISSUE TITLE
Replaced my Own Icon, but The new window's icon i opened is still the compass icon

### ISSUE THREAD

**Issue by willian12345** [nwjs/nw.js#3752]
I use the restorator replace icon resource on Windows plactform, And it works.

But when i use "gui.Window.open" open a new window
The new window's icon i opened is still the compass icon,
why?

**Comment by solumstone** [comment]
This might be Window's caching. If you rename the exe slightly, this won't be an issue. Use a tool like CCleaner to clear Window's icon cache.

**Comment by willian12345** [comment]
It's not Window's caching. I had distributed  it to other pc . 

The first window's icon is my icon.  But when i use  "gui.Window.open" 
The new opened  window's icon is still displayed the compass

**Comment by antontriola** [comment]
Using replace-icon on your local machine won't affect the embedded icon in nw.exe on another machine.

Actually replacing the icon resource in the exe (or dlls in some cases) is the way to achieve this, as with resource hacker: 
http://www.angusj.com/resourcehacker/

**Comment by willian12345** [comment]
thx, I have fixed it
