### ISSUE TITLE
Enable continuous page repainting for Steam Overlay?

### ISSUE THREAD

**Issue by jahrain** [nwjs/nw.js#3753]
I been trying to get the Steam in-game overlay to work for a game that doesn't use the Canvas and thus doesn't repaint the screen constantly (issue #2560 doesn't address this issue). This causes the entire window to hang upon pressing the Shift+Tab key. 

My only workaround I have found for this was to manually repaint the window using some show+hide hack on the body element on a 60 fps interval. It is a bit dirty, but I noticed there is a "Enable continuous page repainting" option in the chrome dev tools which makes the Steam overlay work flawlessly. If there was a way to enable this option from Javascript without the dev tools, it would allow Steam overlay to be used without any hacky workarounds.
##

**Comment by Baccanno** [comment]
You should use a 1x1 canvas with requestAnimationFrame. 

Try this thread https://github.com/greenheartgames/greenworks/issues/16

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
