### ISSUE TITLE
[nw13]chrome.identity broke app

### ISSUE THREAD

**Issue by imskull** [nwjs/nw.js#3756]
```
chrome.identity.getAuthToken(...)
```

console output:

```
Check failed: browser->is_type_popup(). opening browser window.
```

[88560:1299:0811/222412:FATAL:browser_window_cocoa.mm(134)] Check failed: browser->is_type_popup(). opening browser window.

```
and app crashed immediately.

```

**Comment by Imskull** [comment]
To reproduce this problem, you must have `client_id` in package.json or manifest.json
```
  "oauth2": {
    "client_id": "72031406....apps.googleusercontent.com",
  }

**Comment by rogerwang** [comment]
Please see the follow up in #5574
