### ISSUE TITLE
Window title changes when maximizing window frame

### ISSUE THREAD

**Issue by rwtaylorjr** [nwjs/nw.js#3758]
I'm running nwjs-v0.12.3-win-ia32 on Windows XP SP3.

I have a simple test app with the following package.json file:

    {
      "name": "appname",
      "version": "3.0",
      "main": "index.html",  
      "window": {
        "title": "My Test",
        "icon": "doh.png",
        "toolbar": false
      }
    }

When i first launch the app the title displays "My Test" as expected. However, when clicking on the maximize window in the upper right hand corner, the window maximizes and the window title changes to "index.html". It remains as such even after taking the screen out of maximize mode.

The window title will also change to "index.html" if the window loses focus. For example, if I launch my app, initially the title is correct and displays "My Test". However, if i launch a browser or some other app, then the title changes to "index.html".

Is there a setting which controls this behavior, or is it a bug?

**Comment by Spiffyk** [comment]
The title property is supposed to fill the title before the HTML loads, as the wiki states. You should set the caption of your window using the <title> tag in the head your HTML file.

**Comment by rwtaylorjr** [comment]
Got it...thanks. I've read through the wiki....i suppose i just missed it. I thought setting the window title in the package.json was sufficient. Thank you.
