### ISSUE TITLE
Issue with renaming node-webkit nwjs helper applications and nwjs application executor for Mac.

### ISSUE THREAD

**Issue by rishu-kumar-88** [nwjs/nw.js#3759]
Hi,

I am observing issue while renaming the node-webkit application and helper application executor from nwjs to name which contains space e.g.- 'nwjs test'. I have tried to rename application by updating 'nw_product_name' inside nw.gypi file and rebuild it. But, it crashed when open the application file. 

Can you please provide an approach to rename nwjs helper applications and nwjs application executor for Mac. 

Regards,
Rishu
##

**Comment by rishu-kumar-88** [comment]
any update on this....

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
