### ISSUE TITLE
Invoke native c++ plugin from nwjs application

### ISSUE THREAD

**Issue by rishu-kumar-88** [nwjs/nw.js#3760]
Hi,

I am working to implement customize native OS notification using C++ plugin. C++ plugin methods invoke from the nwjs helper application using node-ffi module. So, nwjs helper application is added to the System Preference 'Notifications' preference pane.  

How can we invoke native plugin method from the nwjs application using node-ffi module instead of nwjs helper application?

Regards,
Rishu
##

**Comment by VoidVolker** [comment]
Basically, you need to rebuild ffi with nw own node build tools, but I can't achive this (https://groups.google.com/forum/#!topic/nwjs-general/Xro9ezezDmQ)

**Comment by spirodonfl** [comment]
You can also use node-gyp now if you're willing to use 0.13-beta6

**Comment by rishu-kumar-88** [comment]
any update on this....

**Comment by ghostoy** [comment]
@rishu-kumar-88 Would you explain the difference between invoked from "nwjs application" and "nwjs helper application"?

**Comment by rishu-kumar-88** [comment]
@ghostoy  This is the desired behaviour of Chromium framework which created sub-process with one main process. To get this, open activity monitor on Mac and search "nwjs" after running the node-webkit application.

But my question is to load dylib on main process not on sub-process or helper process.
