### ISSUE TITLE
[nw 0.13] how to create menu?

### ISSUE THREAD

**Issue by oknoorap** [nwjs/nw.js#3765]
in old nwjs to define menu is using gui, but in newer version gui is not defined? where is gui variable?
##

**Comment by masterT** [comment]
From the [NW.js wiki](https://github.com/nwjs/nw.js/wiki/Menu):
``` javascript
// Load native UI library
var gui = require('nw.gui');

// Create an empty menu
var menu = new gui.Menu();

// Add some items
menu.append(new gui.MenuItem({ label: 'Item A' }));
menu.append(new gui.MenuItem({ label: 'Item B' }));
menu.append(new gui.MenuItem({ type: 'separator' }));
menu.append(new gui.MenuItem({ label: 'Item C' }));

// Remove one item
menu.removeAt(1);

// Popup as context menu
menu.popup(10, 10);

// Iterate menu's items
for (var i = 0; i < menu.items.length; ++i) {
  console.log(menu.items[i]);
}
```

**Comment by oknoorap** [comment]
it's not working when I'm using nw 0.13
1. now ``require``` is ```nw.require```
2. ```nw.require('nw.gui')``` module doesn't exists

**Comment by aacotroneo** [comment]
Try this. You can put some breakpoints in dev tools console and inspect nw object. It's that or reading the source code :)
var menu new gui.Menu();  --> var menu = nw.Menu.createMenu ()

**Comment by oknoorap** [comment]
@aacotroneo can you show me, nw gui works in 0.13? (screenshot / codes)

**Comment by aacotroneo** [comment]
Sorry, I dont have the time. :frowning:

Put a console.log(nw) o console.log(nw.Menu) and look at that.. I think parameters are the same.

**Comment by oknoorap** [comment]
@aacotroneo I think this is bug,
```nw.Menu``` is undefined in 0.13, fyi I've been always develop app with 0.8x and I know how to create menus, etc, but I didn't find a way how to handling gui menus in 0.13

**Comment by aacotroneo** [comment]
Ok.. just run /nw.exe with no params and open console ->
![image](https://cloud.githubusercontent.com/assets/10578291/9413939/6d64e978-480b-11e5-9e62-11da91d56437.png)

**Comment by oknoorap** [comment]
here's mine, https://gyazo.com/f2a439171ca3732931fda7f4089bdbde

**Comment by aacotroneo** [comment]
can you run the nw with no params?. May be it's your manifest configuration. What alpha release are you using?

**Comment by oknoorap** [comment]
yes i'm using alpha version, is there new release?

**Comment by aacotroneo** [comment]
there is an alpha-2 release. Im using the live-builds http://dl.nwjs.io/

**Comment by oknoorap** [comment]
I'm using this build http://dl.nwjs.io/v0.13.0/alpha2/nwjs-sdk-v0.13.0-alpha2-win-ia32.zip
hmm this is weird..

**Comment by tshinnic** [comment]
Hmm, reviewing the announcements it seems the menu stuff wasn't ported until v0.13.0-alpha3.  Using [that announced release](https://groups.google.com/forum/#!msg/nwjs-general/wYi5D8SvQ_E/UZ3h0fGDAgAJ) I can see that 'nw.Menu' that has APIs ```nw.Menu.createMenu()``` and ```nw.Menu.createItem()```.

Can you move to the more recent alpha3 release and try again?

**Comment by oknoorap** [comment]
okay thank you, for telling me.. I'll download alpha3...

**Comment by jtg-gg** [comment]
anybody know how to use nw.Menu.createMenu() ?
I keep getting this error
Uncaught TypeError: Cannot read property 'parameters' of undefinednormalizeArgumentsAndValidate @ extensions::schemaUtils:110(anonymous function) @ extensions::binding:374clickFunction

**Comment by tshinnic** [comment]
Can you show us more of your code?  Also, which OS and NW.js versions you are using?  On Win10/v0.13.0-alpha3 after just starting nw.js without a project, typing this into devtools debugger (F12) 'works' ...
```
m = nw.Menu.createMenu({type: 'menubar'})
i = nw.Menu.createItem({label: 'test1'});
m.append(i)
nwwin = nw.Window.get()
nwwin.menu = m
```
in that I see the single item menubar show up.
Even typing in this without options doesn't blow up ...
```
z = nw.Menu.createMenu()
```
so I'm wondering what you are using for options/arguments?  Should be more or less the same stuff as for v0.12 ...

**Comment by jtg-gg** [comment]
@tshinnic thx, already solved my problem
I was blindly do find and replace, 
so the code that causes the error is something like this: 
var menu = new nw.Menu.createMenu(...);

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
