### ISSUE TITLE
NodeWebkit Grunt is not working properly

### ISSUE THREAD

**Issue by dalisoft** [nwjs/nw.js#3766]
Hi!
I'm using NodeWebkit! In few days i seen grunt in more sites and says this is useful and live reload (its super feature)!
I downloaded Grunt demo (https://github.com/nwjs/grunt-nw-builder).
If i open nw.exe, NodeWebkit runs Gruntfile.js!
I extraced nw and grunt-nw in same folder, maybe its wrong?
I am using Windows 10 x32 (x86)

Let me know if somehow wrong, sorry for bad english :)

**Comment by bleush38p** [comment]
It's possible you have nw.js/NodeWebkit confused with node.js itself. nw.js is a app runtime, for making native apps with HTML/JS. [Node.js](https://nodejs.org/) is a "platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications."

grunt-nw-builder is for building up and packaging nw.js applications, not for live reload within them.

[grunt](http://gruntjs.com/), on the other hand is a task runner for node.js applications—that is, still only for building them, not for use while running them.

grunt-nw-builder is one of the many packages available for grunt, including grunt-contrib-watch, which may be related to what you are talking about.


There's a [wiki page](https://github.com/nwjs/nw.js/wiki/Livereload-nw.js-on-changes) on implementing live reload inside nw.js applications, which is what I think you might be trying to do.

**Comment by dalisoft** [comment]
Hi and Thanks @bleush38p 
I'm know what is Node.js and NodeWebkit and it's difference, my problem is:
1) Package extraced and placed as showed in NodeWebkit README and NodeWebkitGrunt README
=> 2) If i open NW.exe and running with Command Prompt, running Gruntfile.js!

I what need do for running page, not a Gruntfile.js?

**Comment by bleush38p** [comment]
What is it that you are trying to do? Are you trying to implement live reload on your application? Or are you trying to automatically build node webkit packages?

**Comment by dalisoft** [comment]
I want implement gruntjs to nw

**Comment by bleush38p** [comment]
Okay, but why? What do you want to do with grunt?

**Comment by dalisoft** [comment]
Ok, thanks! I seen gruntjs is useful application/product in many sites/blogs.
