### ISSUE TITLE
Please, update io.js engine and chrome base

### ISSUE THREAD

**Issue by acterhd** [nwjs/nw.js#3767]
In august released io.js 3.0.0 and chromium version 46. Please, upstream base versions. Main problem: I can't run ES6 code, compiled by TypeScript from default example source. Not supported arrow functions by Chromium 43-44.

**Comment by lmk123** [comment]
+1

**Comment by rogerwang** [comment]
0.13.0-alpha3 will be released soon with Chromium 44 and IO.js 3.0. We cannot rebase it to Chromium 46 with IO.js 3.0 because the v8 versions in them mismatch. Chromium 44  and IO.js 3.0 shares the same V8 version.
