### ISSUE TITLE
Can't get serialport for node.js to work in node webkit 0.8.6, 0.13.0, or 0.12.3.

### ISSUE THREAD

**Issue by WPoole** [nwjs/nw.js#3769]
Hi everyone, I am trying to get the node serialport module to work inside node webkit and have had no luck so far. I have seen solutions for various other versions of webkit, but can't seem to make anything work for any of the currently released versions listed above. Can someone please help me and maybe provide a decent walkthrough of how to do this? If possible it would be greatly appreciated.

Thanks!

Stephen
##

**Comment by VoidVolker** [comment]
Try this version: https://files.gitter.im/nwjs/nw.js/5JeU/serialport.7z ([2](https://mega.nz/#!8Rl1BADa!icijUMsn5ndD-TM22K3gwCGGdoN2PUomA3mUjq6pmDY))  - I don't remeber what exactly I change there, but it works with nw v0.9.2.

**Comment by Christywl** [comment]
I try a simple test on Linux with nwjs-sdk-v0.22.3. It works well.
```
var SerialPort = require('serialport');
SerialPort.list(function (err, ports) {
  ports.forEach(function(port) {
    console.log(port.comName);
    console.log(port.pnpId);
    console.log(port.manufacturer);
  });
});
```

**Comment by Christywl** [comment]
close until there is more information.
