### ISSUE TITLE
Error : The specified module could not be found. 

### ISSUE THREAD

**Issue by bgSosh** [nwjs/nw.js#3771]
Hi,

I am trying to use the greenworks module, and have compiled for nwjs 0.12.3, using the following options:

    nw-gyp configure --target=0.12.3 --arch=x64

This completed without error. However, when I try to include the module, using:

    var greenworks = require('./greenworks-win64');

I get the error

    Error : "The specified module could not be found. xxxx\greenworks-win64.node"'

I have confirmed that the compiled .node file exists in the same directory as the nw.exe, so am a bit confused by this error.

After some googling, I see other users getting this problem when they have renamed nw.exe, but we have not done this.

**Does anyone know what might be causing this?**

Note that if the file is simply missing, or referred to incorrectly then it's a distinctly different error:

         Error {code: "MODULE_NOT_FOUND", stack: "Error: Cannot find module './greenworks-win64'"}

**Comment by bgSosh** [comment]
This problem resolved (.node file was not in same folder as steam libs)

**Comment by wozzup** [comment]
hi @bgSosh i have same problem, which folder you put the `.node` file into?
