### ISSUE TITLE
How can node webkit use local node module install with -g option

### ISSUE THREAD

**Issue by bigfactory** [nwjs/nw.js#3774]
```
$ npm install -g express
```

in nw.js:
```
require('express');
```

not working...

I have try to assign the NODE_PATH in index.html
```
process.env.NODE_PATH = '/usr/local/lib/node_modules/';
```

still not working, is that any way to make this work

**Comment by sholladay** [comment]
First, prove to yourself that your global modules are where you think they are:
````sh
npm root -g
````
Then read a few paragraphs on the `require()` algorithm.
[Loading Modules](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)

At this point it should be obvious why it doesn't work out-of-the-box. The `require()` algorithm never searches a place where it would find your global installs, unless you change where your global installs go.

There is a section in the Node.js docs about loading from global locations, which mentions your `NODE_PATH` approach.
[Loading Global Modules](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders)

However, I don't _think_ you can set `NODE_PATH` internally like that on `process.env` and have it be effective (not 100% sure). It probably has to come from the environment, before Node is started.

**Comment by adam-lynch** [comment]
Yeah, it doesn't work like that. Thanks @sholladay
