### ISSUE TITLE
Node.js not working on iframes (nw.js v0.12.3)

### ISSUE THREAD

**Issue by ButzYung** [nwjs/nw.js#3775]
For some unknown reasons, iframes never load as "Node frames" in nw.js v0.12.3, while the exact same codes worked (ie. iframes loaded as Node frames with local files, as expected) in previous versions of node-webkit (the last version I checked is node-webkit v0.11.6). Those iframes all load local files, which should start as Node frames as described in https://github.com/nwjs/nw.js/wiki/Security

Is it a bug since v0.12? Or is there any (new) way to enforce Node-frame support on iframes?

OS: Windows 10 Home 64-bit
##

**Comment by namaljayathunga** [comment]
+1

**Comment by ButzYung** [comment]
@namaljayathunga I found a solution. On package.json, add this

`"node-remote" : "<local>"`

This isn't necessary in previous versions, but at least it fixes the problem on v0.12.

**Comment by Christywl** [comment]
So it works well now? could we close this issue?

**Comment by Christywl** [comment]
close until there is more information.
