### ISSUE TITLE
Remote debugging tools: Console is unscrollable in Chrome/ium 44+

### ISSUE THREAD

**Issue by maxbarry** [nwjs/nw.js#3777]
When starting an app with --remote-debugging-port=9222 and viewing it in Chrome/Chromium 44, 45, or 46, the "Console" tab cannot be scrolled with a mousewheel or any keys (pageUp, arrows).

This happens even when starting nwjs without any app running, i.e. just the big "NW.JS" on the gray background.

It worked fine in Chromium 43.

Scrolling does work when viewing the Console in the inbuilt debugging tools (e.g. right-click on app and select "Inspect element").

Scrolling can be forced to work by manually editing the Console's CSS and changing the ".root-view" element from "overflow:hidden" to "overflow:scroll". However, this also allows the header bar ("Elements Network Sources Timeline Profiles Resources Audits Console") to scroll out of view instead of remaining fixed in place like usual.

Affects nwjs 0.12.2 and 0.13.0-alpha2, tested in Ubuntu 15.04.

**Comment by eugirdor** [comment]
I have the same issue.

nwjs 0.12.2
OS X 10.10.4
Chrome 44

**Comment by maxbarry** [comment]
Issue persists in 0.13.0-alpha3.
