### ISSUE TITLE
You can not open the application, because this is not supported by PowerPc

### ISSUE THREAD

**Issue by fengliner** [nwjs/nw.js#3778]
OSX: 10.10.1
nw: 0.12.3

I get an error "You can not open the application, because this is not supported by PowerPc" when I open the application which is constructed by nw.

Why?

How can I do?
##

**Comment by stefano055415** [comment]
I have the same problem

someone has solved ?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
