### ISSUE TITLE
is it possible to run node webkit without node.js installed?

### ISSUE THREAD

**Issue by syedfaizan** [nwjs/nw.js#3779]
my node webkit app uses fs module and i am afraid the people who will use my app will have to install node.js to use my app, i tried including the fs module in the node_modules in the project itself, but i think its useless as the module just contains 2 files and i dodnt want people using my app to install node.js

**Comment by Tribex** [comment]
@syedfaizan nw.js (That's what node-webkit is called now.) has io.js (~node.js) bundled with it. You won't have to include the fs module in your node_modules folder, or install node separately.

**Comment by syedfaizan** [comment]
awesome, thanks i am sorry to have included this in the issues, it should be one of the questions.
