### ISSUE TITLE
HTML fails to update from process.nextTick in latest 12.3 build

### ISSUE THREAD

**Issue by Metric** [nwjs/nw.js#3782]
Hi again! With a new project I have been working on and using async.js. I noticed that my progress bars wouldn't update properly until after async had finished all the items. I tested this theory by using async.js to process the items and also using a basic setTimeout() with a delay of 1ms. The setTimeout() updates the HTML UI just fine. Async.js will always use process.nextTick if available, otherwise it will switch to setTimeout.

I should also mention that I am using jQuery to access the DOM.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Metric** [comment]
Wow, I totally forgot I posted this. I don't even remember what project I
was having this issue on now.

If you can't reproduce in latest build, then I assume it is probably fixed.

Simplest test is try and do any DOM changes via process.nextTick in a js
file that is then imported via the script tag in html. If it changes the
html, then I would say the issue is fixed. I say this, because if I
remember correctly I tested with both pure process.nextTick and setTimeout
at the time.

**Comment by Christywl** [comment]
Seem it works fine for me with nwjs v0.25.4. Close it.
