### ISSUE TITLE
Drag and Drop Files Path no longer available in nw13

### ISSUE THREAD

**Issue by Loggic-Is-Dumb** [nwjs/nw.js#3784]
In the nw13 alpha3 there doesn't seem to be the functionality to get local file path from files that were dragged and dropped.

Current Stable: NWjs v12.3 has the ability to get path as [e.dataTransfer.files[i].path](https://github.com/nwjs/nw.js/wiki/Dragging-files-into-page)

The NWjs 13 alpha 3 doesn't seem to have that. Is that intentional? If so what's the new method

**Comment by rogerwang** [comment]
This is now fixed in git and will be available in the next release.
