### ISSUE TITLE
Configuring gyp modules with target=0.13.0-alpha3 on Windows leads to configure.js script errors. [$100]

### ISSUE THREAD

**Issue by truefedex** [nwjs/nw.js#3786]
When trying to configure existing gyp modules with
nw-gyp configure --target=0.13.0-alpha3
got the following errors (modules not use openssl library):

gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.12.7 | win32 | ia32
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\Users\PDT\AppData\Roaming\npm\node_modules\nw-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'D:\Projects\C\nwjslogger\logger\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\PDT\AppData\Roaming\npm\node_modules\nw-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\PDT\.nw-gyp\0.13.0-alpha3\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\PDT\.nw-gyp\0.13.0-alpha3',
gyp info spawn args   '-Dmodule_root_dir=D:\Projects\C\nwjslogger\logger',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\Projects\C\nwjslogger\logger\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\PDT\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\Users\PDT\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js" "configure" "--target=0.13.0-alpha3" "--msvs_version=2013"
gyp ERR! cwd D:\Projects\C\nwjslogger\logger
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
##

**Comment by anjanapaulose** [comment]
Has somebody been able to do this. I tried what atom did for same error https://github.com/atom/node/blob/atom/common.gypi , but then its throwing up a whole other bunch of errors

**Comment by tolrtd** [comment]
I have gotten around this issue by adding --openssl_fips=X to my configure command.  The modules I am building don't use openssl either, so the X seems like it can be anything.  Once I got around that, I had a bunch of build errors, but they were all because of the migration to Node 5.x.  I updated my modules to work with Node 5.x and fiddled with nan versions and they are all building properly now.

**Comment by AllenKll** [comment]
@tolrtd Thank you!  I struggled with this for a while.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
