### ISSUE TITLE
WARNING:ipc_channel_posix.cc(910)] Message needs unreceived descriptors channel [$100]

### ISSUE THREAD

**Issue by dekker7** [nwjs/nw.js#3788]
Dear All,

I have the following error. 
While the app is running NW JS crashes with no reason. 

I get the following error in terminal:
[3674:0100/000000:WARNING:ipc_channel_posix.cc(910)] Message needs unreceived descriptors channel:0x1b4b9663c800 message-type:4294967280 header()->num_fds:1

I have searched on google for solutions, but i can't find any working solution. 

The machine:
Xubuntu 14.04 x64
NW JS 0.12.3
INTEL D2550 1.86ghz
2GB RAM
GMA 3650
I make use of binary files see https://github.com/nwjs/nw.js/wiki/Protect-JavaScript-source-code-with-v8-snapshot
SELINUX disabled
Dump file: https://www.dropbox.com/s/krs9gyoismtzy6d/chromedump.dmp?dl=0

What i have tried 
- restorecon -R ~/.config see https://code.google.com/p/chromium/issues/detail?id=81413
- removed ~/config/.appname

thanks in advance,

**Comment by dekker7** [comment]
Can somebody give me atleast a hint in what direction i must looking? Thanks!

**Comment by neogeek83** [comment]
I just had something similar happen with my NW app. What did you end up doing to fix this? Or is it still an open issue?
