### ISSUE TITLE
disable navigator.geolocation

### ISSUE THREAD

**Issue by nexus-uw** [nwjs/nw.js#3789]
as of 0.12.3, `navigator.geolocation` is fully defined but it never actually works for me.
I tried using `navigator.geolocation.getCurrentPosition()` but it always times out after 15 seconds (my app's configured timeout). A longer timeout should not help this issue.

If this is the expected result, is there someway to disable the geolocation functionality?

Thanks, Simon
##

**Comment by luannpeixe** [comment]
I have same problem...

**Comment by luannpeixe** [comment]
0.14, 0.15 same problem...

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
