### ISSUE TITLE
Request support of global keyboard listener

### ISSUE THREAD

**Issue by shycherry** [nwjs/nw.js#379]
Hello nw team !

I need my NW application to react whenever some key, or keys combinations are pressed, even if my NW app is not focused (a sort of keylogger).
I think that a "global input listener" service would fit well with NW purposes and that it would be nice to provide a generic API for all the NW's targeted platforms.

Thank you !

**Comment by hoschi** [comment]
@rogerwang 
> This is now supported.

I didn't find docs how to do this :( I only found [intercepting](https://github.com/nwjs/nw.js/wiki/Shortcut) not listening key presses, like a key logger would do.

I try to build a counting global hotkey, like "Counting combos" from [Keypress](http://dmauro.github.io/Keypress/).
