### ISSUE TITLE
Is there any way to use Fido U2F with node webkit application?

### ISSUE THREAD

**Issue by asinverse** [nwjs/nw.js#3790]
Hi everyone,

I would like to allow user use FIDO Universal 2nd Factor (U2F) to authenticate when logging in the application (written on Node Webkit framework).
Can I do this with Node webkit application since U2F requires https protocol and an chrome extension?

Thank you for any suggestion,

**Comment by UniDyne** [comment]
I've not done this myself, but it seems your best bet would be the node-hid module and use the FIDO device in challenge/response mode.

**Comment by asinverse** [comment]
Thank you @UniDyne, 
I solved my problem. I did write a small C module using [hidapi](https://github.com/signal11/hidapi) library to communicate with U2F divice. It's not very good but at least I can work with this.
