### ISSUE TITLE
Linux: Users can still access the computer although in kiosk mode

### ISSUE THREAD

**Issue by waitianlou** [nwjs/nw.js#3791]
Hello!
I want disable users from accessing the computer even in kiosk mode,such as Alt+F4 or Alt+Tab.
In https://github.com/nwjs/nw.js/issues/3424
Someone use shortcuts to bind to the key combo to disable it, however, in Ubuntu and Debian, When I bind Alt+F4, I get "Register global desktop keyboard shortcut failed"
How do I solve this problem?

Ubuntu:14.04
Debian8
node-webkit-v0.10.2(shortcuts in v0.12.3 seems do not work in linux)

**Comment by mscreenie** [comment]
The best solution would be to have a third party process manage implementing kiosk mode. Also monitor if the process crashes etc.

**Comment by waitianlou** [comment]
@mscreenie 
Thanks so much for response
I have tried, but seems i can't grab the global keyinput to disable system global shortcut:

1: use XGrabkey: failed.
because according to XGrabkey(https://tronche.com/gui/x/xlib/input/XGrabKey.html), If some other client has issued a XGrabKey() with the same key combination on the same window, a BadAccess error results(I think is the system shortcut key).

2: use QxtGlobalShortcut,failed.
same reason as 1.

3: just disable system shortcut:failed.
I wish to do this in command line, because i must run it by script. so I use gsettings set org.gnome.desktop.wm.keybindings. However:
In ubuntu: close(Alt+F4) worked;switch-applition(Alt+Tab) failed
In debian8: close(Alt+F4) failed;switch-applition(Alt+Tab) failed
it seems there is no effective by use gsettings 

Do you have any other solution?

**Comment by VoidVolker** [comment]
You need to use simple window manager and set nw as default shell. Here simple sript to make kiosk mode for linux: https://github.com/VoidVolker/kiosk

**Comment by waitianlou** [comment]
@VoidVolker Tankyou, it help me
