### ISSUE TITLE
new builds fail on win10

### ISSUE THREAD

**Issue by shenanigans** [nwjs/nw.js#3792]
On windows 10, when attempting to load a valid package, `0.12.3` launches four processes but fails to open any windows while `0.13.0-alpha2` opens a dialogue indicating that the package.json cannot be found. Version `0.8.6` almost works correctly, except the first (and only the first) css3 transition to draw fails - properties do not change until the animation timeout expires, then pop to the target value.

**Comment by shenanigans** [comment]
OK, so this is more of a "silent failure" issue. Apparently these are all symptoms of having an improperly-built native module. I was able to use `0.8.6` to debug the issue most of the way and ultimately tested the final successful configuration with `0.12.3` as I am on x64. A win10-specific note for `nw-gyp` is that you may need to rub some `--msvs_version=2013` on it even if your normal gyp builds are working ok.

**Comment by shenanigans** [comment]
An update - you get silent failure and zombie processes on win10 whenever your application includes module loading issues, native build issues, or syntax errors. I've been forced to keep `0.8.6` around for debugging this sort of mistake, which is very irritating.

I've also been experiencing a lot of BSODs but I'm not sure yet who the culprit is. The suspects other than Node-Webkit itself are `gulp.watch` which sometimes drops out with segfaults, the `lwip` native module, Windows Update which logs tons of kernel-mode errors and recently killed the MBR on my C drive, and the very buggy win10 service Windows Shell Experience Host. Will update further if I ever manage to isolate the issue.

**Comment by tshinnic** [comment]
I noted with interest your mention of syntax errors causing silent/zombie processes on Win10, because I've got a mystery that only occurs on Win10.  Unfortunately, while I can use Win7 and Linux and 0.13.0-alpha3 to figure out the syntax errors and get my test file running on those, the Win10 platform still shows only two 'zombie' 'silent' processes every time I run even the cleaned up version.  I think I've caused Win10 to refuse to run NW.js 0.13.  Of course NW.js 0.12.3 runs fine... :anguished:

**Comment by sourceskyboxer** [comment]
Hey guys, nope failures. I have tested node webkit 0.12.3 x64 on Windows 10 Pro x64 and it works fine. No errors! If you has issus than check your correct architectures x86 and x64 like Windows 10 x86 and Windows 10 x64.

**Comment by shenanigans** [comment]
OK, so since opening this I've noticed that the "zombie" issue is just a failure of the default show behavior for the primary window in the event that an Error is thrown in your first lap round the event loop. If you ask for devtools before risking any Errors you'll have a debug window to explain what you did wrong.

```javascript
var winnder = require ('nw.gui').Window.get();
winnder.on ('loaded', function(){
    winnder.showDevTools();
});
// .. rest of your application
```
