### ISSUE TITLE
How to intercept http request?

### ISSUE THREAD

**Issue by hengyunabc** [nwjs/nw.js#3794]
Chrome extendsions can  intercept http request, how to do it in nwjs?

https://developer.chrome.com/extensions/webRequest

``` javascript
      chrome.webRequest.onBeforeRequest.addListener(
        function(details) {
          return {cancel: details.url.indexOf("://www.evil.com/") != -1};
        },
        {urls: ["<all_urls>"]},
        ["blocking"]);
```
##

**Comment by VoidVolker** [comment]
https://github.com/nwjs/nw.js/issues/3334

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
