### ISSUE TITLE
global object cannot save property permanently

### ISSUE THREAD

**Issue by futurist** [nwjs/nw.js#3795]
I've stored a property to global object as below:
````
global.__count = 1234;
````
But after press REFRESH button on toolbar, the __count property lost.

Is this a bug?

**Comment by VoidVolker** [comment]
Refresh on toolbar = reload full application with node and browser.

**Comment by tkang007** [comment]
Left side stop/reload button does not clear global,but right side reload button clear it.
So, there is no way to use the default toolbar when we use global for sharing something between multiple windows.

**Comment by futurist** [comment]
got it!!!!
