### ISSUE TITLE
zoomLevel not working on devTools window

### ISSUE THREAD

**Issue by rdesoky** [nwjs/nw.js#3796]
Can't change zoomLevel in devTools windows neither with keyboard shortcut nor via code.

Thanks.
##

**Comment by Christywl** [comment]
Run nw.exe(nwjs-sdk-v0.22.3) and open devtools, press `Ctrl + '+'` or `Ctrl + '-'`, the devtools page size could be changed.
Is this issue still reproduced in your side? If so, could you please provide the code to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
