### ISSUE TITLE
First input automatically gets focused on win.show()

### ISSUE THREAD

**Issue by evgenyzinoviev** [nwjs/nw.js#3797]
Hello.

This is a sample that reproduces my problem.

package.json:
```
{
  "name": "test",
  "main": "app.html",
  "window": {
    "title": "test",
    "show": false
  }
}
```

app.html:
```
<html>
<head>
<title>test</title>
<script type="text/javascript">
window.onload = function() {
  var win = require('nw.gui').Window.get();
  win.show();
  win.focus();
  document.getElementById('input2').focus();
}
</script>
</head>
<body>
  <input type="text" id="input1" /><br/>
  <input type="text" id="input2" />
</body>
</html>
```

The problem is that first input (#input1) automatically gets focused after I call win.show(), even if I do document.getElementById('input2').focus() to manually set focus to another input.

I can get it working only with some relatively-long timeout, for example 50ms:
```
setTimeout(function() {
  document.getElementById('input2').focus();
}, 50);
```
This way focus moves to the second input.

PS. I use OS X if that matters, nwjs version is 0.12.3.
PPS: If I set "show": true for "window" property in package.json, everything works fine (no input gets focused automatically).

**Comment by evgenyzinoviev** [comment]
Yesterday we figured out that for ```document.getElementById('input2').focus();``` working properly without a timeout we need to call it after win.focus event. But there is still a bug when using win.show() focuses first input in a document, obviously it shouldn't.

**Comment by macecchi** [comment]
I think this should be reopened. 

As pointed out by @evgenyzinoviev, the window focusing on the first input when using win.show() is still _really_ weird behaviour.

To get around this bug I'm manually adding `input.blur()` after win.focus event.

**Comment by evgenyzinoviev** [comment]
You can also make a "hidden" `input` element with style like `position: absolute; top: -9999px; left: -9999px`, and this `input` will receive the focus after page load. But actually I "fixed" this by migrating to Electron.
