### ISSUE TITLE
Crypto.setEngine('ENGINE_METHOD_ALL') - error:25078067

### ISSUE THREAD

**Issue by roman-sopov** [nwjs/nw.js#3798]
```javascript
var Crypto = require('crypto');
Crypto.setEngine('ENGINE_METHOD_ALL');
```
**Return error:** Uncaught Error: error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library

What is the problem?

Win7 64bit
NW 0.12.3 32bit

**Comment by ghostoy** [comment]
The first parameter of `setEngine(engine, [flags])` is the id or path of the engine, and 'ENGINE_METHOD_ALL' should be the second one `flags`. See https://nodejs.org/api/crypto.html#crypto_crypto_setengine_engine_flags.
