### ISSUE TITLE
Node USB binding error (Invalid access to memory location)

### ISSUE THREAD

**Issue by PimButton** [nwjs/nw.js#3799]
I'm trying to use Noble (https://github.com/sandeepmistry/noble) in a NW.Js application for windows. Noble depends on node-usb which is throwing an error when I launch the application with nw.exe. With the 32bit nw.exe i'm seeing the following error:

`Uncaught Error: Invalid access to memory location.
C:\Users\Kokkerelletje\Documents\GitHub\vanErum-pcApp\node_modules\noble\node_modules\bluetooth-hci-socket\node_modules\usb\src\binding\usb_bindings.node`

And the 64bit version i'm getting this error:
`Uncaught Error: %1 is not a valid Win32 application.
C:\Users\Kokkerelletje\Documents\GitHub\vanErum-pcApp\node_modules\noble\node_modules\bluetooth-hci-socket\node_modules\usb\src\binding\usb_bindings.node`

Searching on that last error I see a lot of hits that suggest renaming app.exe to nw.exe but in my case the filename is already nw.exe. I have rebuild all the relevant modules with `nw-gyp rebuild --target=0.12.3` but this did not resolve the issue. 

Any ideas?
##

**Comment by Calderis** [comment]
Hi! I got a similar problem : 
I've called `var usb = require("usb")` and then i get a ` Uncaught Error: Une routine dinitialisation dune bibliothèque de liens dynamiques (DLL) a échoué.
C:\Users\Calderis\AppData\Local\Temp\nw3136_31267\node_modules\usb\src\binding\usb_bindings.node`.

I'm clearly desesperate and i'm completly blocked until i solved this :/

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
