### ISSUE TITLE
In frameless window after setting an image as -webkit-app-region: no-drag; still cant click it

### ISSUE THREAD

**Issue by benag** [nwjs/nw.js#3800]
```
<image class="Close fixClose" style="position: absolute;left: 96%;top: 7px;" src="application/img/button_close.png"></image>
```

in style.css

.fixClose{
    -webkit-app-region: no-drag;
}
.Close{
    -webkit-app-region: no-drag;
}
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide the full tests to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
