### ISSUE TITLE
Prevent CTRL or CMD + W?

### ISSUE THREAD

**Issue by imjoshdean** [nwjs/nw.js#3801]
Hey, I recently noticed that in my app I am able to hit CMD + W and close the Window with no way to get it back.

Is there a way to prevent this or a better alternative than preventing this?
##

**Comment by rdtsc** [comment]
This only happens in the newer v0.13 builds, right? What happens if you eat the event? For example:

```javascript
window.addEventListener('keydown', function(event) {
  // Ctrl + W
  if(event.ctrlKey && event.keyCode === 87) {
    event.preventDefault();
  }
});
```

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
