### ISSUE TITLE
Is github being abandoned?

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#3802]
I usually check here to see if there are any new versions out, especially for the 0.13 alpha branch.

Then I realized by chance on the google groups the 0.13.3 has been introduced, a week ago. https://groups.google.com/forum/#!msg/nwjs-general/wYi5D8SvQ_E/UZ3h0fGDAgAJ

But this repository is still saying 0.13.2, now is this no longer being updated?
##

**Comment by matthew-dean** [comment]
Uh, the latest commit here was only 14 days ago. Why would you think it was abandoned?

**Comment by cchersin** [comment]
Could you tell me please, when is planned to be released 0.13.3 ?
Thank you.

**Comment by baconface** [comment]
13.x releases are still in alpha and only released for testing and preview. They still have bugs and unfinished features and are not attended for production use. That is why promoting 12.x releases is done here.
