### ISSUE TITLE
iframe form post with target is sending get

### ISSUE THREAD

**Issue by VoidVolker** [nwjs/nw.js#3806]
Iframe post form is sending get, instead of post, if target is `_blank` or `_top`:
`index.html`
```
<html>
<body>
<iframe src="http://wltest.dsd.globo-tech.com/form.php"></iframe>
</body>
</html>

```
`form`
```
<form action="/landing.php" target="_blank" method="POST"> 
    <input type="hidden" name="foo" value="bar"></input>
    <input type="submit" value="submit"></input>
</form>
```
landing.php is returns post arguments

Open nwjs and insert code into console:
```
window.document.body.innerHTML = '<iframe src="http://wltest.dsd.globo-tech.com/form.php"></iframe>'
```
Then press `submit` on page — you will get new window with text `array(0) { }`.
But, if remove target attribute, you will get `array(1) { ["foo"]=> string(3) "bar" }` as resutl.

**Comment by rogerwang** [comment]
We fixed a similar issue. Could you please check again with 0.13.0-beta4?

**Comment by VoidVolker** [comment]
Fixed.
