### ISSUE TITLE
error C2220: warning treated as error - no 'object' file generated

### ISSUE THREAD

**Issue by tinybug** [nwjs/nw.js#3807]
when I run:  ninja -C src/out/Release nw
I got that error msg:
[37/14494] CXX obj\components\crash\app\crash_component_lib.crash_keys_win.obj
FAILED: ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe" /nologo /showIncludes /FC @obj\components\crash\app\crash_component_lib.crash_keys_win.obj.rsp /c ..\..\components\crash\app\crash_keys_win.cc /Foobj\components\crash\app\crash_component_lib.crash_keys_win.obj /Fdobj\components\crash_component_lib.cc.pdb
c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(1544): error C2220: warning treated as error - no 'object' file generated
c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
c:\program files (x86)\windows kits\8.1\include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
[37/14494] CXX obj\third_party\pdfium\core\src\fpdftext\fpdftext.fpdf_text.obj
ninja: build stopped: subcommand failed.

can anybody help me ? Thanks!

**Comment by tinybug** [comment]
when I changed vs2015 to vs2013, i could build succeed.

**Comment by monajalal** [comment]
^So there's no fix for VS2015?

**Comment by rogerwang** [comment]
The current stable version is built with VS2015.
