### ISSUE TITLE
How to cover a fullscreen window?

### ISSUE THREAD

**Issue by waitianlou** [nwjs/nw.js#3809]
Two nw,js windows,
window A:  always-on-top:false;  fullscreen mode
window B:  always-on-top:true; opened with gui.Window.open(windows A), want to used as a popwindow.

when window B open, it will on the top. 
however, when windows A get focus(such as click), window A will on the top and cover window B, how can I let window B always on the top?(if window A is not in fullscreen mode, worked fine).

How can I solve this problem? 

(
use:
win_B.on('blur', function() {
       win_B.focus()
});
will get what i want. however, I think is not a good solution when the focus change frequently.
)

**Comment by 1j01** [comment]
How about in window A add
```js
window.addEventListener("mousedown", function(){
    global.win_B.focus();
});
window.addEventListener("focus", function(){
    global.win_B.focus();
});

```

**Comment by waitianlou** [comment]
I use Qt create window B, set window as Qt::X11BypassWindowManageHint solve this problem.

**Comment by 1j01** [comment]
If you've solved your problem you can close this issue. I'm curious how you're using Qt together with nw.js though.

**Comment by waitianlou** [comment]
Two applications, communicate with unix socket
