### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [nwjs/nw.js#3812]
Any plans to fix the NW.js download links  ?

**Comment by joshterrill** [comment]
What download links are you referring to? I can't find any on the README or the http://nwjs.io website that are broken.

**Comment by Karlheinzniebuhr** [comment]
http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-ia32.zip
http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-x64.zip
http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-ia32.zip

are these working for you? In that case sorry but I'm getting ERR_CONNECTION_TIMED_OUT for several day's now on these links

**Comment by joshterrill** [comment]
Yeah they work for me.

**Comment by Karlheinzniebuhr** [comment]
ok thanks
