### ISSUE TITLE
Can't use import syntax (v0.12.1)

### ISSUE THREAD

**Issue by Yimiprod** [nwjs/nw.js#3813]
In my app, i tried to use `import * as myModule from ('./path/to/module')` in a file loaded with balise script in my index.html but i get the error `SyntaxError: Unexpected reserved word`.

We can't use it this way?
I do that to load node modules in the angular part in my app.

**Comment by Bryan-Turek** [comment]
I don't believe any official versions of iojs or nodejs support the `import` keyword yet.
So you won't be able to use it within the node/iojs context.

Node v4 I'm not sure about though, but that doesn't work with nwjs yet anyway.

**Comment by matthew-dean** [comment]
You would need to use a transpiler like Babel in order to use ES6 with the current release of NWJS.

**Comment by Yimiprod** [comment]
My bad, i probably read in the wrong wiki that we can use it without a transpiler.
