### ISSUE TITLE
No success implementing Google Analytics

### ISSUE THREAD

**Issue by weblancaster** [nwjs/nw.js#3816]
Have been trying to implement analytics for a while but haven't succeed yet.

Is there a service that works out-of-the-box with NW.js? or does anyone know how to use GA on NW.js?

**Comment by matthew-dean** [comment]
I've done it successfully using the Node version of GA: https://www.npmjs.com/package/universal-analytics

You just have to set / call events manually based on what you want to track, but it's been working fine for me.

**Comment by weblancaster** [comment]
Thanks @matthew-dean I'm going to give it a try.

**Comment by weblancaster** [comment]
Oh that was easy. I remember trying while ago and not sure but I did not get working.

Thanks @matthew-dean
