### ISSUE TITLE
Using node.js v4

### ISSUE THREAD

**Issue by kk86bioinfo** [nwjs/nw.js#3819]
Will there any chance for nw.js to build with node.js back using version 4 (LTS)

https://nodejs.org/en/blog/release/v4.0.0

**Comment by bhaveshgohel** [comment]
:+1:  I was thinking to post the same!

**Comment by Yimiprod** [comment]
:+1: Came for this, not disappointed.

**Comment by jloveric** [comment]
:thumbsup: Same

**Comment by Ehesp** [comment]
+1.

**Comment by matthew-dean** [comment]
Yeah, curious if that's going to go into v13 for nwjs. Also, kinda funny that node-webkit changed the name partially because of the move from node to IO.js and now there is no IO.js.

**Comment by mikestopcontinues** [comment]
+1

**Comment by baslr** [comment]
+1

**Comment by Mithgol** [comment]
NW.js v0.13.0-alpha4 [provides support](https://groups.google.com/d/msg/nwjs-general/zzszAUlDSVM/0asr0DJPBQAJ) for Node.js v4.1.2.

This issue may now be closed.
