### ISSUE TITLE
building nw12 faild

### ISSUE THREAD

**Issue by yubb** [nwjs/nw.js#3821]
set GYP_DEFINES=component=shared_library
ninja -C out\Debug nw -j4
v8.h
# error both BUILDING_V8_SHARED and USING_V8_SHARED are set - please check the\

  build configuration to ensure that at most one of these is set
##

**Comment by ghostoy** [comment]
So far shared library build is not supported.

**Comment by yubb** [comment]
那修改源码后使用静态链接重新编译十分耗时，有什么好方法修改并调试源码吗？

**Comment by ghostoy** [comment]
I don't think so. You have to rebuild it again. That's what I'm doing now.

**Comment by was4444** [comment]
What about this?
https://chromium.googlesource.com/chromium/src/+/master/docs/linux_faster_builds.md#Linking

Maybe you should re-run:
```
./build/gyp_chromium content/content.gyp
```
after you set GYP_DEFINES

**Comment by Christywl** [comment]
Is this issue still reproduced now?

**Comment by Christywl** [comment]
close until there is more information.
