### ISSUE TITLE
if the nwjs window lost focus,the window is broken

### ISSUE THREAD

**Issue by sorawa** [nwjs/nw.js#3822]
![Uploading image.png…]()
##

**Comment by sorawa** [comment]
damn,i can't upload the photo

**Comment by sorawa** [comment]
![](https://raw.githubusercontent.com/sorawa/golang_dns_server/master/pic/abc.png)

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.22.2. If still reproduce in your side, please upload your tests.

**Comment by Christywl** [comment]
close until there is more information.
