### ISSUE TITLE
ffi and ref module can't install for nwjs

### ISSUE THREAD

**Issue by komalsingh54** [nwjs/nw.js#3823]
Hi,
I am unable to use ffi and ref module for node-webkit.
i install nw-gyp
then nw-gyp rebuild --target=0.5.0

```
      C:\Users\ksingh1\.nw-gyp\0.5.0\deps\v8\include\v8.h(1467) : see decla
```

  ration of 'v8::Integer'
..\src\ffi.cc(127): error C2065: 'NanNew' : undeclared identifier [C:\Users\ksi
ngh1\Desktop\node-ffi-master\build\ffi_bindings.vcxproj]
..\src\ffi.cc(127): error C2275: 'v8::String' : illegal use of this type as an
expression [C:\Users\ksingh1\Desktop\node-ffi-master\build\ffi_bindings.vcxproj
]
          C:\Users\ksingh1.nw-gyp\0.5.0\deps\v8\include\v8.h(1098) : see decla
  ration of 'v8::String'
..\src\ffi.cc(127): fatal error C1003: error count exceeds 100; stopping compil
ation [C:\Users\ksingh1\Desktop\node-ffi-master\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ksingh1\AppData\Roaming\npm\
node_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces

can u suggest me any solution.
or anyone can provide me  ffi and ref node-modules  for node-webkit
so i can use them directly.
##

**Comment by ghostoy** [comment]
NW 0.5.0 is not supported now. Please consider latest stable 0.12.3.

**Comment by komalsingh54** [comment]
thanks for reply 
i did for 0.12.3 
now its showing module mismatch version - expected 43, got 46

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.22.2.

**Comment by Christywl** [comment]
close until there is more information.
