### ISSUE TITLE
v0.12.3-win-x64 NPAPI plugin not loaded

### ISSUE THREAD

**Issue by yohaia** [nwjs/nw.js#3824]
Hello,

I've try to load a simple NPAPI plugin, but failed to do it.
when i have in the packaje.json this:
"webkit": {
    "plugin": false
  }
And in the console I invoke "navigator.plugins", I see the empty array.
When I turn it to "true", I can see all the plugins that are in the reg: "HKEY_LOCAL_MACHINE\SOFTWARE\MozillaPlugins\"

What am I missing? Is NPAPI support removed from nw.js project?
##

**Comment by ghostoy** [comment]
There is a trick on Windows that you have to name your plugin as `np*`, e.g. `npMyPlugin.dll`, and place it to your app's `plugins/` folder.

**Comment by yohaia** [comment]
Thanks for the replay, but I've already try it before posting here.
Any other ideas? 
Anyone one if this approach going to be deprecated with this removed from Chrome?

**Comment by ghostoy** [comment]
@yohaia I think nw12 still support NPAPI plugins. Does the plugin built for x64 or x86? 64bit NW only load x64 plugins.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full tests to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
