### ISSUE TITLE
nw13 gclient sync --with_branch_heads error

### ISSUE THREAD

**Issue by wpp2014** [nwjs/nw.js#3825]
I can't gclient sync --with_branch_heads and get this error : 

Did not find prebuilt clang 233105-2, building
Android NDK not found at src/tools/clang/scripts/../../../third_party/android_tools/ndk
The Android NDK is needed to build a Clang whose -fsanitize=address
works on Android. See 
http://code.google.com/p/chromium/wiki/AndroidBuildInstructions for how
to install the NDK, or pass --without-android.
Error: Command '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 1 in /home/wpp/Work/nw13
Hook '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' took 127.59 secs

 any idea how to fix this ?
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
