### ISSUE TITLE
[nw12] nwfaketop and top window navigation

### ISSUE THREAD

**Issue by lalakiwe** [nwjs/nw.js#3826]
I'd embedded an iframe with `nwdisable` and `nwfaketop` for minibrowser. It's almost perfect, exclude in the website [https://chaseonline.chase.com/Logon.aspx](https://chaseonline.chase.com/Logon.aspx). After I clicking the submit button with random id/pw in page, I got an error as follows:
> Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://chaseonline.chase.com/Logon.aspx' from frame with URL 'https://mfasa.chase.com/auth/alogin.jsp'. The frame attempting navigation is neither same-origin with the target, nor is it the target's parent or opener.

This website is failed to replace the whole page with [https://chaseonline.chase.com/Logon.aspx](https://chaseonline.chase.com/Logon.aspx) with click event. Due to this error, it cannot login in this site. 

Also, I had tried to remove `nwfaketop`. It could login in this site without error message, but whole page is replaced. Is it possible to conquer this website with nwfaketop?

package.json
<pre>
{
  "name": "TEST",
  "main": "index.html",
  "window": {
    "frame": true,
    "width": 1024,
    "height": 768,
    "toolbar": true
  }
}
</pre>

 index.html
```html
<!DOCTYPE html>
<html>
	<head></head>
	<body>
		<iframe src="https://chaseonline.chase.com/Logon.aspx" width=100% height=700px nwdisable nwfaketop></iframe>
	</body>
</html>
```

**Comment by MartySVK** [comment]
Hi, did you fix this problem ?

**Comment by lalakiwe** [comment]
Hi @MartySVK, no fixing or workaround until now

**Comment by mscreenie** [comment]
Your manifest is missing the appropriate node-remote param.

**Comment by lalakiwe** [comment]
It doesn't matter what you say. The cause of remote page loading failure the iframe and the top frame (nwfaketop) is not same-origin I thought.

**Comment by mscreenie** [comment]
try 
    "node-remote": "*",

**Comment by rogerwang** [comment]
Close as nw 0.12 is not supported now. Please try the latest version.
