### ISSUE TITLE
Make application window display below

### ISSUE THREAD

**Issue by georgii-ivanov** [nwjs/nw.js#3828]
Hi.

I use Ubuntu 14.04 LTS, node-webkit and X11 with OpenBox.
Using X11 property setting i can move that window below of other windows.

In node.js i found `as_desktop` property used in manifest. I used that but window state is still floating by desktop.

I found issue #2833 and pull request #51 - it's not working for me (tested on Ubuntu with unity and on Mac). Maybe this solution is only for GTK+? #51 edits is currently builded with node-webkit?

Is there any solution to solve my problem with openbox or compiz WM (unity) and what WM supported with this property?
##

**Comment by Christywl** [comment]
see the docs http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/:

> as_desktop option is not supported for now

For another question, please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
