### ISSUE TITLE
How node-main's node.js access any windows?

### ISSUE THREAD

**Issue by waitianlou** [nwjs/nw.js#3830]
If window A in package.json open a new window B, how can node-main access it?
package.json

``` json
{
  "main": "index.html",
  "name": "Hello NW.js",
  "node-main": "nodemain.js",
  "window": {
    "toolbar": true 
  }
}
```

index.html

``` html
<body>
<script src="test.js">
</script>
</body>
</html>
```

test.js

``` javascript
var gui = require('nw.gui'); 
var win = gui.Window.get();
var testval = "window1"
var test = function()
{
    alert(testval);
}
gui.Window.open ('index2.html', {
});
```

index2.html

``` html
<html>
<body>
<script src="test2.js">
</script>
</body>
</html>
```

test2.js

``` javascript
var gui = require('nw.gui'); 
var win = gui.Window.get();

var testval = "window2"
var test = function()
{
    alert(testval);
}
```

And here is nodemain.js

``` javascript
setTimeout(function() {
  var gui = window.require('nw.gui');
  gui.Window.get().test();
}, 1000);
```

When I start, there have a alert window says: window1. How can let is call funcation in test2.js which is included in index2.html, make the alert window say:window2?
##

**Comment by b1rdex** [comment]
You must store references to your windows somewhere and then use them.
The non-leaky way to do this is to store `window.__nwWindowId` of created windows and then get that windows by `gui.Window.get(idYouStored before)`.

**Comment by b1rdex** [comment]
Api ref: https://github.com/nwjs/nw.js/blob/nw13/src/api/window/window.js#L25

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
