### ISSUE TITLE
Render crash is not generating any dump file

### ISSUE THREAD

**Issue by wcalderipe** [nwjs/nw.js#3831]
I'm facing a render crash and I can't find any dump file to solve this. I tried to use `gui.App.setCrashDumpDir` but doesn't work as well.

Here's my script to force a crash error

```
gui.App.setCrashDumpDir('/path/to/my/desktop'); // yes, i have permissions to write there.

setTimeout(function() {
  gui.App.crashRenderer();
}, 10000);
```

Please, I need to find a way to check where the render is broken a stack error or something.

Another question is: where nw.js put all chromium dump files by default?

**Comment by ghostoy** [comment]
`setCrashDump` is broken. The crash dumps are generated in temp folder of your system.

**Comment by wcalderipe** [comment]
I had to create myselft the folder `~/Library/Breakpad` to nw.js can dump my files there but the .dmp is impossible to read.

How can I get something more "friendly" or how can I turn the .dmp file in something more readable?

**Comment by ghostoy** [comment]
@wcalderipe You can set `BREAKPAD_DUMP_LOCATION` env to target mini dump folder. Note that due to [this bug](https://code.google.com/p/chromium/issues/detail?id=414239), Chrome can not generating crash dump files on Yosemite+.

**Comment by wcalderipe** [comment]
So, if I run my app in development mode on Ubuntu for instance I'll be able to see all the stack trace before the render crash?

**Comment by ghostoy** [comment]
Yes. You will find .dmp files generated.

**Comment by wcalderipe** [comment]
Actualy I'm on Yosemit right know and after I created the **~/Library/Breakpad** folder I started to get some .dmp files. You can download the last three of them [here](https://drive.google.com/file/d/0B-v42hw-YyJoaGxMdkFuU2loWEE/view?usp=sharing).

**Comment by ghostoy** [comment]
@wcalderipe Well, [the bug fix](https://codereview.chromium.org/571663002/diff/80001/components/crash/app/breakpad_mac.mm) said in-process reporter can only catch crashes in browser process only. Did you generate it with `creashBrowser()` or `crashRenderer()` ?

**Comment by ghostoy** [comment]
You want to decode *.dmp file? You need `minidump_stackwalk` tool, built from breakpad. And read [this article - Decoding Crash Dumps](https://www.chromium.org/developers/decoding-crash-dumps) for how to use it.

**Comment by wcalderipe** [comment]
The app closes without any message so I've being using `crashRenderer()` to simulate the error. I'm just wondering if you could you get the error stack from any of those .dmp files?

**Comment by ghostoy** [comment]
Please read the article above for the usage of `minidump_stackwalk` tool to decode *.dmp files. You will also need NW.js symbols, which can be downloaded from http://dl.nwjs.io/<version>/*-symbol-*. And there is [another article](https://code.google.com/p/google-breakpad/wiki/LinuxStarterGuide#Producing_symbols_for_your_application) for how to put symbol files in correct location with correct file name.

**Comment by wcalderipe** [comment]
Thanks for your patiance and time man!

**Comment by ghostoy** [comment]
Welcome :)
