### ISSUE TITLE
--enable-file-cookies 

### ISSUE THREAD

**Issue by LeiO-Angel** [nwjs/nw.js#3832]
i use the file:///E:/NWJS/nwjs-v0.12.3-win-x64/nwjs-v0.12.3-win-x64/test/test.html to access the https server, fiddler can catch the cookies but the nwjs webkit cannot , i don't know why .and the nwjs webkit
gives the tips in resources:   by default cookies are disabled for local files. You could override this by starting the browser with --enable-file-cookies command line flag
##

**Comment by LeiO-Angel** [comment]
I send the ajax request via the local html page, I can get the data , but the cookie can not.....
Please help , why ... seems like the webkit restrict that behavior....... help!!!!!!!!!!!!  help!!!!!!!!!!!!

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
