### ISSUE TITLE
Window can be dragged under kiosk mode on Mac

### ISSUE THREAD

**Issue by cotejp** [nwjs/nw.js#3833]
On Mac OS, it is possible to drag around a frameless window in kiosk mode. Even if -webkit-app-region: no-drag; is added to the body tag, it is still possible to click anywhere in the window and drag it around.
##

**Comment by harmvandendorpel** [comment]
Noticed this too, please fix

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.22.3. 
package.json:
```
{
  "name": "test",
  "main": "index.html",
  "window" :{
    "frame": false,
    "kiosk": true
  }
}
```

**Comment by cotejp** [comment]
I tried reproducing it myself and couldn't either. It's not clear if the problem was resolved through a NW.js update or because I upgraded to El Capitan. In any case, I guess we can close this one. Thanks.
