### ISSUE TITLE
Scrollbar missing in v0.13.0-alphaX releases

### ISSUE THREAD

**Issue by brannondorsey** [nwjs/nw.js#3834]
How can I get the scrollbar (and URL field) back in the new v0.13 alpha releases? I assume they will return in time for the actual releases, is this the case? Also where can I find information about anticipated timeline for v0.13?

**Comment by thinhit** [comment]
i have same issue :(

**Comment by Mithgol** [comment]
I also have the missing scrollbars in NW.js v0.13.0 alpha 6 SDK build on Windows 64bit.

Additionally the windows does not seem to scroll when I scroll the wheel on my mouse.

The alternative scrolling technique (click the wheel, release the wheel, drag the mouse) works, however.

**Comment by Mithgol** [comment]
Keyboard buttons that are usually used for scrolling (`PgUp`, `PgDn`, `Home`, `End`) also don't seem to work at all.

**Comment by rogerwang** [comment]
It inherits the same behavior from default Chrome App window. I'll look to fix it.

**Comment by rogerwang** [comment]
This is now fixed in git.
