### ISSUE TITLE
[nw13] Crash when inspecting 'chrome' object

### ISSUE THREAD

**Issue by maxbarry** [nwjs/nw.js#3835]
To reproduce on Ubuntu 15.04:

1. Run:

    nwjs-sdk-v0.13.0-alpha3-linux-x64/nw

1. Open dev tools by right-clicking in nwjs window and selecting "Inspect background page"
1. In dev tools, click "Console" tab
1. Type "chrome" and press Enter. Output is:

    Object {accessibilityFeatures: Object, accessibilityPrivate: Object, activityLogPrivate: Object, alarms: Object, app: Object…}

1. Click that output text.

Result: nwjs crashes. Command line displays:

    [1:1:0916/144046:FATAL:v8_schema_registry.cc(97)] Check failed: schema. chromeosInfoPrivate

This doesn't happen in nwjs 0.12.3.

**Comment by tshinnic** [comment]
This had happened to me under Win10 with 0.13.0-alpha3 a few days ago, but I couldn't see any output/logs.  So, not just Ubuntu.

**Comment by rogerwang** [comment]
This is fixed in git and will be released in the next version.
