### ISSUE TITLE
error message "require undefined" 

### ISSUE THREAD

**Issue by faytom** [nwjs/nw.js#3837]
I tried to build a server/client application all packed in a single nw file. However, when i use require() in both server and client code, the error message always appeared in the console. The modules I used in server.js are express, socket.io and http. The module i used in the client.html is serialport.js. 
##

**Comment by joshterrill** [comment]
Are you using `nwjs-v0.13.0-alpha3`? If so, check out this google group thread. https://groups.google.com/forum/#!topic/nwjs-general/3vUVKsDOZhY

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
