### ISSUE TITLE
nw.js with command line argument?

### ISSUE THREAD

**Issue by sourceskyboxer** [nwjs/nw.js#3838]
Hello gyus, 

I want to create invokement like Adobe Air or node webkit with parenments.

example:
nw.exe -paren1 <path or line>
```
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>GameLauncher</title>
</head>

<body onLoad="init">
	<script type="text/javascript">
		function init(){
			var gui = require('nw.gui');
			var commands = gui.App.argv;
			gui.App.on('open', function(cmdline) {
				switch(commands)
				{
					case '-testargs':
						cmdline = alert("Test Alert into NW.js")
						break;
					default:
						break;
				}
			});
		}
	</script>
</body>
</html>
```
is it correct or wrong?
i want to create for example:

game.exe was packed by Engima Virtual Box with nw.exe
game.exe -game `<moddirectory>`
game.exe starts default example `<defaultdirectory>`
```
game.exe
../mod <- mod game directory
../game <- default game directory
```
Why do i like this because i am exited to build own gamelauncher for HTML5, CSS3, Javascript with node Webkit JS :)

Can you help me a bit because i want know like real game like Quake 3 and Half-Life 2 were moved to HTML5 and Javascript frameworks because they are working under all plattform speficetion.

Thanks sorry for bad english

**Comment by sourceskyboxer** [comment]
How do I get command from app.exe like it myapp.exe -paren1 -paren2 true or more how does it work?

**Comment by joshterrill** [comment]
Navigate to the directory where app.exe is in a command prompt or shell,
then execute app.exe --paren1 --paren2, etc.

On Wed, Sep 16, 2015 at 4:24 PM, Jens Eckervogt <notifications@github.com>
wrote:

> How do I get command from app.exe like it myapp.exe -paren1 -paren2 true
> or more how does it work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwjs/nw.js/issues/3838#issuecomment-140924608>.
>



-- 
Josh Terrill // developer
209-676-7334

**Comment by sourceskyboxer** [comment]
Thanks but me doesn't work :( How do i fix what is code?

If you say "correct code" because i have written code post#1 i have written it. And you should check my code when it doesn't show like detect extisting directory? or Show Alert?

**Comment by sourceskyboxer** [comment]
![gamelauncher_without_command](https://cloud.githubusercontent.com/assets/3496136/9977126/34fa2734-5efd-11e5-909c-5e0e7b53358d.PNG)
This is without command of arguments!

![gamelauncher_with_command](https://cloud.githubusercontent.com/assets/3496136/9977130/4d1b75a2-5efd-11e5-92a5-258c4a204ab6.PNG)
This ist command with argument.

Code 
![coding_for_nw_command](https://cloud.githubusercontent.com/assets/3496136/9977134/77b1e242-5efd-11e5-830e-ff3ea0fa7da2.PNG)

Why does it not show if i command like "app.exe Read" than it need to write to document. But it doesn't work. WHY???

**Comment by joshterrill** [comment]
Your original code is wrong. When you call your `init` function, you need to call it like `<body onload="init()">`. Once you do that, it will work. See my screenshot:

![http://i.imgur.com/6IB7UJb.png](http://i.imgur.com/6IB7UJb.png)

**Comment by sourceskyboxer** [comment]
Thank you for explain!

But i want important argument like example:

switch(command)
{
  case "-version":
  document.write("Version is 1.0.0)
  break;
}

Is it correct or wrong?

**Comment by joshterrill** [comment]
Since the return of `commands1` is an array, you would need to loop through the array to find what command line arguments were entered. Then you can perform your switch or if statement. Here is an example of using an if statement:

```
<!DOCTYPE HTML>
<html>
<body onLoad="init()">
    <script type="text/javascript">
        function init() {
            var gui = require('nw.gui');
            var commands = gui.App.argv;
            for (i in commands) {
                if (commands[i] === "command1") {
                    console.log("Entered command 1")
                }
            }
        }
    </script>
</body>
</html>
```

**Comment by sourceskyboxer** [comment]
Thanks for help! I am sorry for late because I am busy from my work.  I will try your good statement "if else" so close like Adobe Air from starling website I have tried to invoke,  to get argument.  Why does nw js not need to call "invoke" event? 

Example 1:
Correct file type will double click by user into launching nwjs! Like invoking file to application? 

Example 2:
File was dropped by user to nw or nw "filename extension"
If it hasn't features for correct version of nwjs 

Example 3:
-game "correct directory of mod game" like hl.exe -game csttike and hl.exe starts default directory valve. 
Is it possible for if-else statement like your code? 

Thanks

**Comment by joshterrill** [comment]
I don't really understand what you're trying to accomplish. Could you give me some code examples?

**Comment by sourceskyboxer** [comment]
I am sorry my dear. my english is not good. :/

I explain you again.

I will know that like commands by Valve Software "hl.exe" is Half-Life has loaded default directory "/valve" and if it uses "-game <mod name of directory" example hl.exe -game cstrike. It is mod of Half-Life called Counter-Strike.

For example with nwjs:
nw.exe
./default <- it is default loading game without "-game <directory>"
./mod <- It is other distirbutaion of game like Half-Life i have explainned it. 

Which 3d engine for Javascript? without locals erver? Or i need to use local server?

PS: I know ThreeJS uses only local server like xampp or nwjs http-server.
If they say ThreeJS is sensitive to locals erver than i build www directory like this
nw.exe <- it is gamelauncher
./contents <- it is www root directory
../default <- default game
../mod <- mod game with "-game <mod name>"

and it is possible?

Thanks!

**Comment by sourceskyboxer** [comment]
This is example 
```
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Test Command</title>
</head>

<body onLoad="init()">
	<script type="text/javascript">
		function init()
		{
			var gui = require('nw.gui');
			var commands = gui.App.argv;
			var modPath;
			for (var i in commands) {
                if (commands[i] === "-game ") {
					if("-game" === modPath)
					{
						document.write(modPath); // if you use -game <mod name directory> than it shows  e.g. nw -game mymod
						break;
					}else
					{
						document.write("default");
						break;
					}
                }
            }
			
			document.write("default"); // this is default game for example
		}
	</script>
</body>
</html>
```

Look my example like alternative from starling website 
http://forum.starling-framework.org/topic/how-does-air-app-load-default-game-directory-like-half-lifes-directory

But i want to know with Javascript and HTML5 :D Because i like HTML5 they want use HTML5 that is why Flash and Air will die soon. I don't worry that HTML5 and CSS4. Javascript.

Thanks for help!

**Comment by joshterrill** [comment]
You could set a variable if `-game` is present, then if both `modpath` and the `-game` variable are true, return your result. Here is a working example.
```
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>Test Command</title>
</head>

<body onLoad="init()">
    <script type="text/javascript">
        function init()
        {
            var gui = require('nw.gui');
            var commands = gui.App.argv;
            var modPath;
	    var gameValue = false;
            for (var i in commands) {
                if (commands[i] === "-game") {
		    gameValue = true;
		}
		if (commands[i] === "modpath" && gameValue === true) {
		    document.write("Both -game and modpath present");
		}
            }
            document.write("default"); // this is default game for example
        }
    </script>
</body>
</html>
```

**Comment by sourceskyboxer** [comment]
Hello my dear thanks for help. But nwjs couldn't work if i "-game <mod name>" Adobe Air is better than nwjs :(

I am sorry for trying to result. 

```
if (commands[i] === "modpath" && gameValue === true) {
    document.write("Both -game and modpath present <br />");
}
```
It is wrong not "modpath" just modPath is String  like command of nw -game mymod or -game othermod. This can not recognize to string of other mod path. I am sorry for that nwjs can not work.

Adobe Air 19.x has good features because invoke has no problem like -game<mod name directory> it can recognize to path- PS: Please add "invokement" to nwjs like Adobe AIr feature. because it is very simple:
```
function myInvoke(ive)
{
 ive.arguments > Array
ive.currentDirectory > File or i/O load from current application directory like nw.exe call our content.
ive. ... > more features of invokements
}

this.addEventListener(NWInvoke.invoke, myInvoke);
```

So sadly with nwjs I need to wait next features. Please improve and add new feature "invokement under nw.js" 

Best greeting day ( night ) I would like to hope you improve next feature for nw.js

Should i close it?

**Comment by joshterrill** [comment]
I understand that `modpath` isn't actually the string `modpath`, it would be a path to a file. But what you could do is grab the position of `-game`, in this case if you execute `nw -game /path/to/mod` then `-game` would be in position `0`. Then grab the value that is in position `0` + 1, which would be `1`, and store that in a variable so you can reference it in your app.
