### ISSUE TITLE
Is there a way to disable notification sounds?

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#3840]
If you read the comments on https://github.com/nwjs/nw.js/issues/27 or see https://github.com/nwjs/nw.js/pull/2289 you'd think there is no sound when a notification is triggered but there is (on Mac and Windows). 

So is it (still) possible to disable it? How so?

cc @jtg-gg @jamesmortensen

---

This is needed as a workaround for #3839 (along with in-app settings for notification sounds).

**Comment by jtg-gg** [comment]
@adam-lynch, which version are you using?
I've just tested OSX, v 0.12.3, there is no sound

**Comment by adam-lynch** [comment]
I don't have my mac nearby but I think it was 0.12.2 on Mavericks. I'll try again to be sure I'm being stupid.

**Comment by adam-lynch** [comment]
Confirmed no sound with 0.12.2 on Windows 10 anyway.

**Comment by adam-lynch** [comment]
Ugh sorry! Got confused in my middle of other issues. Confirmed: no sound on OSX 10.9.1. with nw@0.12.2.
