### ISSUE TITLE
Opening links in same iframe

### ISSUE THREAD

**Issue by akashnimare** [nwjs/nw.js#3842]
How do I open a new link in the same iframe instead of default browser. I am not able to understand forceCurrent property.

**Comment by MadfishDT** [comment]
what is your problem? 
A iframe display AA site, and then Do you want BB site in A iframe? in runtime?
iframe.src = newurl;

**Comment by akashnimare** [comment]
No. I am loading quora.com in a iframe. So whenever I click on a link it opens in the default browser. I want this to be open in same iframe and same window.
