### ISSUE TITLE
notification encoding 

### ISSUE THREAD

**Issue by thib3113** [nwjs/nw.js#3846]
I have a notification encoding problem, i take your test : https://github.com/nwjs/nw.js/tree/nw13/tests/manual_tests/notification 
and try to write special characters ( àé ), and they have problem.

![snip_20150920004923](https://cloud.githubusercontent.com/assets/5489218/9978480/958ac80e-5f31-11e5-99a6-773d8ee6cb43.png)

With search, on my computer ( W10 64bits)
this encoding works : 
iso-8859-14
iso-8859-15
windows-1252
windows-1254

**Comment by jtg-gg** [comment]
I tried the sample from https://developer.mozilla.org/en-US/demos/detail/html5-notifications
it works, it can display the  àé character
so it might be the html file encoding
