### ISSUE TITLE
Windows toolbar miniature buttons ?

### ISSUE THREAD

**Issue by puluch** [nwjs/nw.js#3847]
Hello,

is there anyway to create buttons in the miniature displayed on mouse hover on the toolbar/dock like vlc / spotify ?

Thanks for you answers !

![thumbnail button](https://cloud.githubusercontent.com/assets/11314944/9981886/34a59f3e-5fca-11e5-9738-b906d1961936.png)
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
