### ISSUE TITLE
moveTo "reactivates" the bounce effect 

### ISSUE THREAD

**Issue by moritzmhmk** [nwjs/nw.js#3848]
The [bounce effect](https://github.com/nwjs/nw.js/issues/3109) when scrolling on OS X can be deactivated with [this](https://github.com/nwjs/nw.js/issues/3109#issuecomment-105283351) css trick.

This works fine until the window is moved with `gui.Window.get().moveTo(x,y)` - now the bounce effect is suddenly back and the only workaround I found for this is calling `gui.Window.get().resizeBy(0, 1)` and optionally `gui.Window.get().resizeBy(0, -1)`.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
