### ISSUE TITLE
Using webview tag in NW

### ISSUE THREAD

**Issue by christiannwamba** [nwjs/nw.js#3849]
Been struggling to build a mini browser with node-webkit and have not even been able to do the most basic thing which is to use webview (not iframe) to display a url content in my app. It was announced that this feature is available since v0.12.0 but yet I can't get it working.
##

**Comment by christiannwamba** [comment]
If you care to replicate, I used [this](https://npmjs.com/package/generator-wean) Yeoman generator for node webkit and then added 
````<webview id="foo" src="http://www.google.com/" style="width:640px; height:480px"></webview>```` 
the content of app/views/index.ejs

**Comment by asuchar** [comment]
Could you post your manifest.json and package.json?

**Comment by sapioit** [comment]
Thanks! I'm also trying a few things using webviews...

**Comment by Christywl** [comment]
Seem it works fine for me on Linux with nwjs v0.25.0:
![1](https://user-images.githubusercontent.com/20039821/30200991-bfa92750-94ab-11e7-93b8-508053ded21a.png)

**Comment by Christywl** [comment]
close until there is more information.
