### ISSUE TITLE
global object 

### ISSUE THREAD

**Issue by tosone** [nwjs/nw.js#3850]
If I build an object in one page, how can I get it in another page? 
global object?
With Express?

**Comment by tshinnic** [comment]
In NW.js 0.12 and before, every context has the same variable `global`. A variable set within that object by one window will be visible in another window's context.  That value would also be visible within the `global` object in the context node modules run in.

In the new NW.js 0.13 I believe the same is true, except that in window contexts `global` has now been put more tidily under the single variable `nw`, so in that version `nw.global` in a window context is the same as plain `global` is within node.

**Comment by tosone** [comment]
I have resoled it. thank you very much...Another question, I found in nwjs cannot run `crypto.createECDH `, I know it beause the version of iojs, how can I repleace it with a newer version nodejs. Rebuild nwjs with the source code myself?   OMG.
