### ISSUE TITLE
get downloads folder path in sandbox

### ISSUE THREAD

**Issue by HanaHsu** [nwjs/nw.js#3852]
In my app, there is a function to show users the download path they selected and the default path is set to be the Mac OS Downloads folder "/Users/username/Downloads".

I add the key "com.apple.security.files.downloads.read-write" to my plist and have my app signed successfully.

Is there any method I can use to show the direct path of Downloads folder (not the sandbox path), just like the "NSDownloadsDirectory" method does in Objective-C ?
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
