### ISSUE TITLE
Unable to load external resources from filesystem

### ISSUE THREAD

**Issue by RiderSx** [nwjs/nw.js#3853]
Trying to play a video using `video` html tag, but on any kind of path devtools says that request for this video was canceled.
![developer tools - file____c__users_alexr_000_documents_nw-projects_bakaru_app html 2015-09-23 03 18 13](https://cloud.githubusercontent.com/assets/213272/10035355/c97127ae-61a1-11e5-9b8f-9a1b339a4592.png)

Actually it doesn't matter if file sits in app folder or anywhere else in filesystem.

nw.js v0.12.3
io.js v1.2.0
Chromium 41.0.2272.76
commit hash: 591068b-b48a69e-27b6800-459755a-2bdc251-1764a45

Windows 10

nwjs folder contains:
```
29.07.15  06:53           872 384 credits.html
29.07.15  06:53         4 173 928 d3dcompiler_47.dll
29.07.15  06:53           987 648 ffmpegsumo.dll
29.07.15  06:53        10 457 856 icudtl.dat
29.07.15  06:53            86 016 libEGL.dll
29.07.15  06:53         1 890 304 libGLESv2.dll
22.09.15  20:57    <DIR>          locales
29.07.15  06:53        61 057 536 nw.exe
29.07.15  06:53         7 482 865 nw.pak
29.07.15  06:53         6 873 600 nwjc.exe
29.07.15  06:53        14 879 232 pdf.dll
22.09.15  21:16        61 058 108 test.exe
22.09.15  21:16               572 test.nw
```

**Comment by RiderSx** [comment]
Problem was with ffmpegsumo.dll, which were already in distro of Win64 0.12.3 nwjs, it just don't work. Found ffmpegsumo.dll from latest stable chromium and here we go, it works now.

**Comment by RiderSx** [comment]
Only now understand that nwjs comes with pre-built ffmpegsumo.dll which has no support for mp3 or MPEG-4 depite of what this [page](https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.) says, ugh %)

**Comment by devlo** [comment]
@RiderSx 
Um didn't chromium drop ffmpegsumo.dll support from like june 2015 ? Where did you get working ffmpegsumo.dll  with 0.12.3 that supports mp4/h264?

**Comment by RiderSx** [comment]
@devlo well, just googled it actually and there was some guy with a link to a working lib :)
