### ISSUE TITLE
Crash on creating notification

### ISSUE THREAD

**Issue by iofjuupasli** [nwjs/nw.js#3857]
On Windows (7, x64)

nw version: 0.12.3

``` js
for (var i = 0; i < 10; i++) {
  setTimeout(function(){
    new Notification('test');
  }, i * 500);
}
```

Then sometimes **click** several times on notification.

App crashes without throwing Error.
##

**Comment by jtg-gg** [comment]
@iofjuupasli I've just tested the official build v 0.12.3
both 32 bit and 64 bit, it doesn't crash
which version are you using ?

**Comment by tshinnic** [comment]
I also tested several times with 0.12.3 64bit, on Win7 and Win10 (noticing how differently the notifications appear on Win10!), and couldn't get anything to glitch.  A more interesting (and local?) problem than you'd hoped?

**Comment by iofjuupasli** [comment]
> which version are you using ?

0.12.3 from npm

> I also tested several times with 0.12.3 64bit, on Win7 and Win10

I can't reproduce it on win 8, so probably it's related only to win 7

Exact steps to reproduce (on my side):
1. Show noty 1
2. Before noty 1 dissapears, show noty 2
3. Click on noty 2
4. Show noty 3
5. App crashes on `new Notification('test');` line without throwing an Error.

Windows 7 ultimate sp1 (build 7601)

**Comment by tolrtd** [comment]
I also see this on Windows 8.1 x64.

**Comment by samlin08** [comment]
it also happens to me , while frequently show notifications and click on it.it seems the click event  trigger the crash

**Comment by hisune** [comment]
me too.my nwjs version is 0.12.3. and I test it on win7 x64

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.22.3. App doesn't crash.

**Comment by Christywl** [comment]
close until there is more information.
