### ISSUE TITLE
miniBrowser how to mointer http requesting

### ISSUE THREAD

**Issue by jstdoit** [nwjs/nw.js#3859]
hello, I am making a browser with NW.js, the browser with navigation bar, and a iframe tag embeded, I wanna to mointer what the iframe's request is doing, so I can change the navigation bar's status.

Is there any to set callback when nw.js is doing some http request?

Thanks.
##

**Comment by jstdoit** [comment]
@rogerwang could you help me?

**Comment by jstdoit** [comment]
I think I can goto #409, is it right?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
