### ISSUE TITLE
window.print() can't work on Windows.

### ISSUE THREAD

**Issue by wowosky** [nwjs/nw.js#3864]
nw version: nwjs-v0.12.3-osx-x64.

I'm using nw to create my project, and trying to call window.print() to print a web page. It works well on linux and mac, but failed on Windows.

On Windows, after window.print() is called, a dialog to select printers can be shown, after I selected a correct printer, nothing happened.  Then if I repeated this action multiple times, the program crashed.

I searched the issue history, seems it said window.print() has already been supported since the older version.  
Anyone succeeds printing web page in nw?  If not, any alternative?  Your suggestions are appreciated.

**Comment by joshterrill** [comment]
Do you see the `pdf.dll` file inside the root directory where `nw.exe` is?

**Comment by wowosky** [comment]
No. pdf.dll was not in my build package.
<img width="364" alt="screen shot 2015-10-02 at 17 45 11" src="https://cloud.githubusercontent.com/assets/12205482/10243758/65940998-692d-11e5-8d9d-b9f2394c9ede.png">

Shall I build pdf.dll to the package? If so, how to add it the build? Where to find pdf.dll? Can I just add it to root dir where nw.exe is ?

**Comment by wowosky** [comment]
Closed the issue by mistake, reopen it.

**Comment by joshterrill** [comment]
Go to one of the other versions, download it, take it out of that archive and copy it into yours. There was one or two versions where it was forgotten, I think.

**Comment by wowosky** [comment]
"the other version"? Do you node webkit packages on Windows? any clue for the  archive name that I can try to look for?  Thanks.

**Comment by joshterrill** [comment]
I edited my post previously with a link.

On Fri, Oct 2, 2015 at 3:11 AM, wowosky <notifications@github.com> wrote:

> "the other version"? Do you node webkit packages on Windows? any clue for
> the archive name that I can try to look for? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwjs/nw.js/issues/3864#issuecomment-144982266>.
>



-- 
Josh Terrill // developer
209-676-7334

**Comment by wowosky** [comment]
Thanks, Joshua. I will have a try. :-)

**Comment by wowosky** [comment]
I had a try,  it is solved. Thanks, Joshua. 

BTW, will missing pdf.dll be fixed in the future version of nw?  This simple missing really made me search around for a while.

**Comment by joshterrill** [comment]
Excellent, go ahead and close out this issue :)

What version of nwjs are you using?

**Comment by wowosky** [comment]
The latest version I'm using: nwjs-v0.12.3-osx-x64.

**Comment by joshterrill** [comment]
I believe that is the only version that has the pdf.dll file missing. I
believe there was another ticket that brought it up, so I'm sure it will be
fixed with the next version.

On Sat, Oct 3, 2015 at 12:46 AM, wowosky <notifications@github.com> wrote:

> The latest version I'm using: nwjs-v0.12.3-osx-x64.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwjs/nw.js/issues/3864#issuecomment-145212202>.
>



-- 
Josh Terrill // developer
209-676-7334

**Comment by wowosky** [comment]
Great, thanks for the update. I will close this issue. :-)
