### ISSUE TITLE
directory sopport not work when operation with flow.js

### ISSUE THREAD

**Issue by hxzqlh** [nwjs/nw.js#3866]
I used flow.js(https://github.com/flowjs/flow.js) version v2.9.0 in nw.js (v0.12.3), when I choose a directory, flow.js cannot read the file in that dir,it just read the dir link.How does it happen?Is it the flow's bug or nw.js?

my tutorial:https://github.com/hxzqlh/nw_flow
##

**Comment by yolo2013** [comment]
I have the same problem. Please focus on this.

**Comment by Christywl** [comment]
I try this on Linux with nwjs-sdk-v0.22.3. The results are: 
When I click 'select folder', it opens a dialog 'Select Folder', you could choose any folder(not file). 
You said it cannot read the file in that dir, but I think this is a expected behavior, it should choose a folder not file, right?

**Comment by Christywl** [comment]
close until there is more information.
