### ISSUE TITLE
iframe content visible even when iframe.style.visibility is "hidden"

### ISSUE THREAD

**Issue by jonathan-roy** [nwjs/nw.js#3867]
For demo purpose, I created a nw.js app which simply creates a hidden iframe loading a URL. The problem is that, in that example, the iframe's content is visible once loaded whereas the iframe itself is hidden (iframe.style.visibility = "hidden"). The code of the app:

``` html
<!DOCTYPE html>
<html>
    <head>
        <script>
            window.addEventListener("load", function ()
            {
                var iframe = document.createElement("iframe");
                iframe.style.width = "800px";
                iframe.style.height = "400px";
                iframe.src = "http://demo.vdcloud.caldera.com/Apps/welcome/data/main.html";
                iframe.style.visibility = "hidden";
                document.body.appendChild(iframe);
            });
        </script>
    </head>
    <body>
    </body>
</html>
```

This issue is present on Windows 7 32bits, with nw.js 0.12.3. On OS X there isn't any problem, the iframe and its content are not visible. On Windows, when you try to scroll the iframe, then the content becomes hidden.

I tried adding 'nwdisable' and 'nwfaketop' attributes to the iframe, same result.
##

**Comment by baconface** [comment]
Try the following instead:
```javascript
iframe.style.display = "none";
```
And you can display it again with:
```javascript
iframe.style.display = "block";
```

**Comment by jonathan-roy** [comment]
Thank you, this is what I did as a temporary fix, even if setting visibility instead of display would be more adapted to my needs.

**Comment by Christywl** [comment]
Seem I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.3. 
When set `iframe.style.visibility = "hidden";`, the iframe and its src are hidden. When remove it, the iframe and its src are visible.

**Comment by Christywl** [comment]
close until there is more information.
