### ISSUE TITLE
node-webkit-v13 no gui win/osx/linux 

### ISSUE THREAD

**Issue by p5150j** [nwjs/nw.js#3869]
## NO gui elements seem to work in v13-Nacl:

https://github.com/nwjs/nw.js/wiki/window
https://github.com/nwjs/nw.js/wiki/menu
https://github.com/nwjs/nw.js/wiki/Screen
https://github.com/nwjs/nw.js/wiki/tray
https://github.com/nwjs/nw.js/wiki/app
https://github.com/nwjs/nw.js/wiki/Frameless-window

Is there an initiative to have this available soon?
##

**Comment by baconface** [comment]
Currently these parts are being rewritten for the 13.x releases. Please use 12.x in the mean time.

**Comment by tshinnic** [comment]
Variables and APIs have been moved around in nw.js 0.13.0  
Everything is now underneath/within the global variable 'nw', which more or less replaces the "require('nw.gui')" construct.

For instance there is now `nw.process`, `nw.global`, `nw.require`.
APIs have been moved under `nw` such as `nw.App`, `nw.Clipboard`, `nw.Menu`, `nw.Shell`, `nw.test`, and `nw.Window`.

But even when present in v0.13.0-alpha3 some of the APIs have been changed to better conform(?) with newer versions of Chromium/v8.  
One example of that is the `Menu` API:
```
    var gui = require('nw.gui');
    var menu = new gui.Menu({});
```
is now 
```
    var menu = nw.Menu.createMenu({});
```

And other APIs or *parts thereof* have not yet been ported into v0.13.0-alpha   The reasons to use v0.13.0-alpha are to test your apps' dependencies against the in-progress version, or if you really need a feature from the newer Chromium in v0.13.0-alpha  (currently Chromium 44.0.2403 vs. 41.0.2272).

I'm hoping that one or another of us will come up with shim code to bridge the differences between versions.  I'd started on Menu but had to drop it for awhile.

**Comment by p5150j** [comment]
@tshinnic Thanks Ill check it out!! :beers:

**Comment by Christywl** [comment]
Please see http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

> All NW specific APIs, including require() is moved into a nw object from the nw.gui library. However, we provided a builtin wrapper library to provide compatibility for 0.12 apps. You can use nw.gui library for some time before we deprecate it in 0.14 or later.
