### ISSUE TITLE
v13-Nacl zombie process stay alive after app has closed. win 8 & 10

### ISSUE THREAD

**Issue by p5150j** [nwjs/nw.js#3870]
# Issue:

> Using the basic hello world nacl app (to keep this issue simple)

https://developer.chrome.com/native-client/devguide/tutorial/tutorial-part1

> Then create a windows build v13-Nacl with the hello world Nacl example:

 _Test app can be found here_

https://s3-us-west-2.amazonaws.com/dubhouse/Roger/forRoger.zip

> Open the app

<img width="979" alt="appopen" src="https://cloud.githubusercontent.com/assets/444888/10197903/fd9dae48-6756-11e5-86d7-8acc9ac319ca.png">

> It works!, Great...NaCL app can be used with NWjs.
> 
> Then close the application and you will see the zombie processes still running. They **never go away**, **die off**... nothing.

<img width="980" alt="appclose" src="https://cloud.githubusercontent.com/assets/444888/10197931/1094009c-6757-11e5-9a44-5f28d528cc36.png">

> Every time you open a **new instance** of the app **new zombie process'** are created and dont die off.
##

**Comment by shenanigans** [comment]
Do they die when you kill the application explicitly?

```javascript
var gui = require ('nw.gui');
var winnder = gui.Window.get();
winnder.on ('close', function(){
    gui.App.quit();
});
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by p5150j** [comment]
@Christywl Sep 30, 2015 Ill close this
