### ISSUE TITLE
"cmd + shift + v" shortcut doesn't paste

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#3871]
cmd+shift+v doesn't do anything (it should paste).

My app runs in NW.js and the Web so it's just broken in NW.js. I could patch it in NW.js by using the Shortcut API, checking if the currently focused element is a field / textarea, finding the caret position and inserting the content myself... but that's a lot of hassle.
##

**Comment by adam-lynch** [comment]
I created a new simple app with nw@0.12.2 on OS X Mavericks to prove this by the way. It's not something in my app breaking it.

**Comment by dkfiresky** [comment]
Why does "cmd+shift+v" shortcut should paste? On mac's you should use "cmd+v" shortcut, or you redefined the shortcut in Settings->Keyboard->Shortcuts?

**Comment by adam-lynch** [comment]
It works in Chrome. No I didn't.

**Comment by dkfiresky** [comment]
The shortcut you're talking about is for `"Paste and Match Style"`, which should be in `Edit` menu of your application, 'cause it does not present by default.

**Comment by adam-lynch** [comment]
>The shortcut you're talking about is for "Paste and Match Style"

Hmm, I'm used to being "Paste as plain text".

> should be in Edit menu of your application, 'cause it does not present by default.

So you're saying I basically need to write the implementation myself?

**Comment by dkfiresky** [comment]
@adam-lynch Yes, you need to specify menu in your application.
[Menu](http://electron.atom.io/docs/v0.33.0/api/menu/) and [MenuItem](http://electron.atom.io/docs/v0.33.0/api/menu-item/) modules may help you in this.

**Comment by adam-lynch** [comment]
Wrong project @dkfiresky. Anyway, this issue is for NW.js to allow shift to be pressed when pasting. It's kinda expected behaviour.

**Comment by dkfiresky** [comment]
@adam-lynch sorry, wrong links

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
