### ISSUE TITLE
No PDF Reader?

### ISSUE THREAD

**Issue by ken92** [nwjs/nw.js#3873]
I first noticed a problem in my packaged executable when instead of simply showing a PDF that was embedded in an iframe on a page I had navigated to using gui.Window.open, a file download dialog would appear, prompting the user to download the PDF. When testing by opening the program with "nw ." from the command line, nothing displays. There's no file dialog and no file displayed -- simply a blank page.

To reproduce this error:

``` javascript
var new_win = gui.Window.open("http://some/pdf/url.pdf");
```
##

**Comment by formula1** [comment]
Until there is a native solution, there is also https://github.com/mozilla/pdf.js/

**Comment by julmot** [comment]
Is it possible that there's now a built-in PDF viewer?

[This page](http://nwjs.io/blog/whats-new-in-0.13/) says:

> NW.js v0.13 brings most features [...] builtin PDF viewer [...]

**Comment by ghostoy** [comment]
I tested with 0.14.6 and 0.18.7 and it works. I think this issue can be closed. Please reopen it if you still experience this issue.

**Comment by EthraZa** [comment]
Is the bultin PDF Viewer working on Linux (Ubuntu 16.04.3)?
I just tryed with NW.js 0.24.4 and 0.18.7 (as mentioned) but it just open a gray window, no errors, nothing, but the lack of a callback for the opened window.

Test code:
```
nw.Window.open("tst.pdf", function(win) {
    win.on('loaded', function() {
        win.print({});
            setTimeout(function() {
                win.close();
            }, 100)
    });
});
undefined
VM210:2 Uncaught TypeError: Cannot read property 'on' of undefined(…)
```
