### ISSUE TITLE
App.Open doesn't provide args on OSX / only filename 

### ISSUE THREAD

**Issue by ThorstenHans** [nwjs/nw.js#3874]
When executing a standalone app for the second time using osx temrinal by invoking

`open -a mynwjs.app /path/to/file --args foobar` 

the `App.open` event is executed but instead of receiving the entire command (as mentioned in the docs) I receive only the filename eg. `/path/to/file`

Any workarounds or suggestions on that?
##

**Comment by gabereiser** [comment]
does https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments#difference-between-appargv-and-open-event provide the args in `App.argv`?

**Comment by armandn** [comment]
I noticed it too. To clarify:
`gui.App.argv` works as specified on Win & OSX.
`gui.App.on('open'...` returns on Win the full commandline but it only the argument on Mac.
This happens on 0.12.3. Windows 10 and Mac OS X El Capitan.

I am working making my app handling files as arguments ("Open with...") and this inconsistency makes it frustrating.
On windows I receive `"C:\Path\MyApp.exe" --original-process-start-time=13094153790134232 "D:\Test\file"` while on Mac I receive just `/Test/file`

Personally I'd prefer to receive just the file path argument. I don't understand why the behavior was changed in 0.7

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows/Mac with nwjs-sdk-v0.22.3, the file path could be returned:
index.html:
```
<script>
nw.App.on('open', function(cmd){
document.write(cmd);
});
</script>
```
My steps:
1. Start the app: ./nwjs.app/Contents/MacOS/nwjs  App/
2. Start the app again with the file path: ./nwjs.app/Contents/MacOS/nwjs  App/ /User/***/local.html
3. You will see the file path in the app

**Comment by Christywl** [comment]
close until there is more information.
