### ISSUE TITLE
App crashes and restarts on it's own when closing

### ISSUE THREAD

**Issue by jaruba** [nwjs/nw.js#3876]
I'm using `NW.js 0.12.3` along with [WebChimera.js.node](https://github.com/RSATom/WebChimera.js), rarely, when closing the app, it just restarts by itself (and also resends all the command line args from the first time it loaded to this new window).

I can't (for the life of me) debug it. An interesting thing I discovered though is that from the multiple processes that NW.js starts on Windows, only the main process crashes and restarts, all other processes it originally created retain the same PID.

I've checked `C:\Windows\Temp\` in hopes of finding a `.dmp` file, but no luck, there's no file that has that extension.

This is really driving me crazy and I have no idea how to find the reason behind it..

Is there any way I can debug this? Any hints as to what could cause such a strange crash on app close that restarts the main process? Could it be related to the use of the `.node` file? Could queued events cause this? (ie: an event is triggered at the exact millisecond when the app closes and that restarts NW.js)

Thank you in advance
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
