### ISSUE TITLE
Frameless Window Controls Visual Bug

### ISSUE THREAD

**Issue by jaruba** [nwjs/nw.js#3877]
I'm using the frameless window feature, as such I've created my own design for the window header / controls.

Everything works fine up until I click the header of the window for the first time after the window has been resized, this also happens after just doing `win.maximize()`, `win.minimize()`, `win.restore()`, etc.

A simple click would just make this bug show and hide fast, but keeping the mouse button down will show it for a longer period of time. Clicking the window header for a longer time is not uncommon though as this is the normal behavior of a user that wants to move the window.

Tested on: Windows 8.1 64bit - NW.js 0.12.3

Screenshot of the issue:

![nw-js-bug](https://cloud.githubusercontent.com/assets/1777923/10337169/9b9d8988-6d06-11e5-8ee5-018fad0aca84.png)
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
