### ISSUE TITLE
node-webkit-v13 package.json window is ignored 

### ISSUE THREAD

**Issue by p5150j** [nwjs/nw.js#3878]
``` json
    "window": {
        "icon": "icons/bla.png",
        "toolbar": true,
        "frame": true,
        "width": 1200,
        "min-width": 1200,
        "height": 800,
        "min-height": 800,
        "position": "center",
        "title": "nope"
    },
```

![screen shot 2015-10-07 at 10 10 53 am](https://cloud.githubusercontent.com/assets/444888/10343670/27500922-6cdc-11e5-8a47-7ee0dec1b8e8.png)

as you can clearly see package.json manifest not respecting values.
Is there some kind of override here that Im not seeing?
##

**Comment by Christywl** [comment]
I see window subfields(`width/height`,` position`, `icon`, ...) work well on Linux/Windows with nwjs-sdk-v0.22.3. Please try the latest nwjs build.
