### ISSUE TITLE
how to disable image download in nodewebkit when open some webpage?

### ISSUE THREAD

**Issue by ouonet** [nwjs/nw.js#3886]
how to disable image download in nodewebkit when open some webpage?
##

**Comment by dkfiresky** [comment]
@ouonet [Stackoverflow](http://stackoverflow.com/) is there to help you.

**Comment by ouonet** [comment]
@dkfiresky hi, have you found same question in Stackoverflow? I didn't find.thks

**Comment by dkfiresky** [comment]
@ouonet maybe you should ask there?

**Comment by b1rdex** [comment]
It's not possible in normal browser AFAIK — http://stackoverflow.com/questions/6929662/how-do-i-abort-image-img-load-requests-without-using-window-stop

The only way to do this in nw.js might be https://github.com/nwjs/nw.js/wiki/Manifest-format#inject-js-start--inject-js-end
I'm still unsure it'll work, but you should try.

**Comment by ouonet** [comment]
@dkfiresky normally, browser provides configuration about 'disable showing image'. but I dont't find such option in [http://peter.sh/experiments/chromium-command-line-switches/](http://peter.sh/experiments/chromium-command-line-switches/)

**Comment by dkfiresky** [comment]
@ouonet i don't have any option to `disable image download/showing` in Safari/Firefox/Chrome.
The simplest solution is to use jQuery and remove all `src` attributes on `img` and remove `background-image` css styling from elements before loading the page (before `DOM ready` event).

**Comment by xuzicn** [comment]
Certainly you can do this follow below steps:
1) you must declare a "webRequest" permission in package.json.
```
"permissions": ["webRequest"]
```
2)Add a listener to chrome.webRequest and block any requests you want. here is the sample code
```    
var gui = require('nw.gui');
    gui.Window.open("http://www.google.com.hk", {
        "inject-js-start": 't.js'
    });
    var blackList = [
        "https://www.google.com.hk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"];
    chrome.webRequest.onBeforeRequest.addListener( function(details){
            console.log( 'beforeRequest; details: ', blackList.indexOf(details.url) >= 0 );
            return { cancel: blackList.indexOf(details.url) >= 0 };
        }
        , {urls: ["<all_urls>"]}
        , ["blocking"]
    );
```

**Comment by skerit** [comment]
Adding 

    "permissions": ["webRequest"]

to the package.json file results in an error when starting nw.js version 0.13:

    Failed to load extension from: /path/project. The 'webRequest' API cannot be used with event pages.

Without it, I can add a webRequest listener in a bg-script, but it doesn't do anything.

**Comment by b1rdex** [comment]
This can be done using service workers I think.

**Comment by xuzicn** [comment]
@skerit you cannot use webRequest api in bg-script, you must use it in the main html, and the html must be a local html(dont know why you must use it in local html)

Try this sample
package.json
```javascript
{
    "name": "blockImageSample",
    "main": "app.html",
    "window": {
        "show": true
    }
}
```
app.html
```
<html>
<head>
    <title> Menu </title>
<script>
    var gui = require('nw.gui');
    chrome.webRequest.onBeforeRequest.addListener(function(details){

            return { cancel: true };
        }
        , {urls: [
            "*://*.google.com.hk/*"
        ], types:["image", "stylesheet"]}
        , ["blocking"]
    );
    gui.Window.get().window.location = 'http://www.google.com.hk';
</script>
</head>
<body>

</body>
</html>
```

**Comment by afloesch** [comment]
Your best bet for this is to load the content in a webview and setup webrequest filters on the webview object. See here:

https://developer.chrome.com/apps/tags/webview#type-WebRequestEventInterface

For example, this code will disable all images and stylesheets for all domains and paths. Tested with nwjs 0.16.

```javascript
    webview.request.onBeforeRequest.addListener(
      function(details) {
        return {
          cancel: true
        };
      }, {
        urls: ["*://*/*"],
        types: ["image", "stylesheet"]
      }, ["blocking"]
    );
```

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
