### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by Anonymitet** [nwjs/nw.js#3888]
Hi.

I'm working in Construct 2 and to be able to implement steam plugins I'm forced to use NW10.5 which is ok by me except for one thing. The NW10.5 doesn't seem to be able to detect a new gamepad after the launch of the game?

This is a big problem becuase when playing with a wireless gamepad and it turns off for some reason (batteries or idle too long) you have to restart the game to continue.

This seems to be fixed in the new NW which I can't use with construct 2 and Steam. So is there a way for me to at least get the NW10.5 to handle gamepads like the new NW version does?

Would greatly appreciate any help on this. Thank you in advance!
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
