### ISSUE TITLE
Multiplatform with 3rd party modules & C addons 

### ISSUE THREAD

**Issue by gfwilliams** [nwjs/nw.js#3889]
I just got https://github.com/espruino/EspruinoWebIDE (a Chrome Web App which uses chrome serial) working nicely with nw.js and node-serialport.

But now I'd like to package it up for each major platform - it looks like actually doing that normally would be pretty easy to do from 1 PC, but since `serialport` uses C/C++ it seems like I'd have to build it for each supported platform (which presumably means I'd need at a minimum OSX, Linux and Windows machines to build from).

Is there a way around this?
- A set of packages of `serialport` (and/or other common nw.js modules) with binaries compiled for different versions of nw.js?
- A way of cross-compiling packages for all platforms from within Linux?
- A build system that magically handles building packages for each platform even when there are C/C++ modules? I didn't see any mention of that when I looked for tools

thanks!
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
