### ISSUE TITLE
Tray icons aren't cleaned up on shutdown

### ISSUE THREAD

**Issue by mmorrisontx** [nwjs/nw.js#389]
As stated in the title, many frameworks nowadays will clean up tray icons for you when that application shuts down (qt and wx come to mind). On windows, tray icons which aren't destroyed in nw persist after the application has closed.
##

**Comment by mrfabbri** [comment]
@adam-lynch @sonicsnes do you have a test case?

**Comment by adam-lynch** [comment]
@mrfabbri no, I can't share my app. I'm away for the next week so I can't do anything really right now sorry
