### ISSUE TITLE
'openssl_fips' is not defined

### ISSUE THREAD

**Issue by bgSosh** [nwjs/nw.js#3890]
I'm trying to build greenworks against nw13.0-alpha3, but am hitting an error during the configure stage:

     nw-gyp configure --target=0.13.0-alpha3 --arch=ia32

     gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp

Does anyone know what the problem is?  

I can't find much info on the 'openssl_fips' error, other than [an issue with node-gyp](https://github.com/nodejs/node-gyp/issues/652).

node v0.12.7
npm v2.11.3
nw-gyp v0.12.4

**Comment by rogerwang** [comment]
This is fixed in alpha7.

**Comment by rtliu** [comment]
I'm trying to build in alpha7, but also error
	gyp info it worked if it ends with ok
	gyp info using nw-gyp@0.13.0
	gyp info using node@0.12.7 | darwin | x64
	child_process: customFds option is deprecated, use stdio instead.
	gyp info spawn python
	gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'make',
	gyp info spawn args   '-I',
	gyp info spawn args   '/Users/liurongtao/Documents/dev/nw/nwjs-v0.13.0-alpha7-win-x64/node_modules/sqlite3/build/config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/Users/liurongtao/.nw-gyp/0.13.0-alpha7/common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=/Users/liurongtao/.nw-gyp/0.13.0-alpha7',
	gyp info spawn args   '-Dmodule_root_dir=/Users/liurongtao/Documents/dev/nw/nwjs-v0.13.0-alpha7-win-x64/node_modules/sqlite3',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '-Dv13=1',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp
	gyp ERR! configure error 
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/nw-gyp/lib/configure.js:361:16)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
	gyp ERR! System Darwin 15.0.0
	gyp ERR! command "node" "/usr/local/bin/nw-gyp" "configure" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.13.0-alpha7" "--target_platform=win32"
	gyp ERR! cwd /Users/liurongtao/Documents/dev/nw/nwjs-v0.13.0-alpha7-win-x64/node_modules/sqlite3
	gyp ERR! node -v v0.12.7
	gyp ERR! nw-gyp -v v0.13.0
	gyp ERR! not ok
