### ISSUE TITLE
Trust On First Use not possible.

### ISSUE THREAD

**Issue by conartist6** [nwjs/nw.js#3892]
I have an application that needs to make use of HTTPs Trust On First Use.

Normally this would be the SSL error screen, which forces you to click "Advanced" and then "proceed to blah (unsafe)". In nw.js there is only a blank screen when an SSL error is encountered.

I grabbed a copy of chromium and confirmed that the window is indeed a chromium feature and not a chrome one, and am now starting to dig through the chromium sources and am working on getting nw.js to build. What I want to know is: if chromium supports this, why doesn't nw.js? When I try to put the chromium code back, what stumbling block am I going to hit? I'm a bit out of my element here, and I need the simplest possible solution that supports my requirements.
##

**Comment by conartist6** [comment]
Looks like I'm going to be able to add TOFU back, is there a reason it would not be merged back into nw.js?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
