### ISSUE TITLE
在 "inject-js-start" 或 "inject-js-end" 那里访问不了global对象

### ISSUE THREAD

**Issue by wanjochan** [nwjs/nw.js#3893]
上下文：需要在每一个popup出来（包括popup的popup）时注入一小段代码，"inject-js-start" 有成功注入，现在但这段代码因为呼叫不了什么nwjs的函数对象（比如global和require）导致没办法做比较高级的应用。有其它的解决方案吗？

**Comment by qierqiang** [comment]
同问……
inject-js-start or inject-js-end can't access to "global" or "require" etc.
any suggestions? thanks.
