### ISSUE TITLE
nw crashes with chromium-args: --single-process

### ISSUE THREAD

**Issue by anjanapaulose** [nwjs/nw.js#3898]
Hi,

I want to make nw.js (.12.3 version)app runs as a single process rather than using the multiprocess architecture of chrome. But the app crashes , with the argument passed. Has somebody been able to do this. Help is much appreciated,

**Comment by anjanapaulose** [comment]
This is giving error when using "require". var nw= require('nw.gui'). This fails with require not found error. happens only when I add --single-process flag

**Comment by gwicksted** [comment]
Looks like it won't be possible.  See #3599

**Comment by anjanapaulose** [comment]
Yes, i tried with "chromium-args":"--in-process-gpu", this is working and will reduce the processes to 3
