### ISSUE TITLE
Multiple monitor cloning?

### ISSUE THREAD

**Issue by sergeantjonas** [nwjs/nw.js#3900]
All,

I am currently developing a screensaver application for our marketing department and managed to create it in nw.js. It does everything required, but unfortunately I ran into an issue on multiple monitor systems. The app only runs on one screen, which is not really the intention. Is there any way I can either:

a) Clone the window to all monitors connected to the system
b) Make the other monitors go to sleep/show a black screen?

I looked around and didn't really find anything that could help me further. 

Thanks in advance!
##

**Comment by makkesk8** [comment]
Well this is possible to fix actually...
Be aware that if a horizantal & vertical setup is used this will probably not work as intended, but that's quite rare actually.

console.log(screens) to see what you have to work with, its quite simple actually.
Screen: https://cloud.githubusercontent.com/assets/2333584/8568311/e1933f96-256c-11e5-82a4-1fd56fa94f4d.png

That's actually from another project with a similar issue with the screens, but you'll get the idea.

CODE:

    // Initiate screens
    gui.Screen.Init();
    var screens = gui.Screen.screens;

    // if more than 1 screen
    if(screens.length > 0) {
       for(var i=0; j=screens.length,i<j; i++) {
          // Add up the pixels of width & height for all screens and modify window height & width
       }
    }

**Comment by sergeantjonas** [comment]
@makkesk8 I'm not sure I understand what this code is supposed to do? I'm obviously not at work and I can't really test it at home so maybe I'm just being dumb. What is that for loop supposed to do? Go through the screens object and assign x, y coordinates to new window objects based on what's in there? Or am I understanding this wrong?

**Comment by makkesk8** [comment]
The point was to calculate the maximum screen size and then stretch the window. I don't see any other practical solution other than stretching.

But you did raise another idea, cloning the window... I can't see how this wont end up being a nightmare... but ofc its worth a try. You can use the same loop to spawn more windows for each screen. then just set window.moveTo

```
Window.moveTo(x, y)

Moves a window's left and top edge to the specified coordinates.
```

**Comment by albi90** [comment]
if anyone is still looking for a solution then this should work,

`		var gui = require('nw.gui');
		var win = gui.Window.get();
		gui.Screen.Init();
		var screens = gui.Screen.screens;
		var width = screens[0].bounds.width;
		var height = screens[0].bounds.height;
		var x = 0;
		var y = 0;
		for(var i = 0; i < screens.length; i++) {
			//find lowest x pos
			if(screens[i].bounds.x < x)
				x = screens[i].bounds.x;
			//find lowest y pos	
			if(screens[i].bounds.y < y)
				y = screens[i].bounds.y;
			//add to width	
			if(screens[i].bounds.x !== 0)
				width = width + screens[i].bounds.width;
			//add to height	
			if(screens[i].bounds.y !== 0)
				height = height + screens[i].bounds.height;
		}
		//set screen width and height to span multi monitors
		win.resizeTo(width, height);
		win.moveTo(x, y);`

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
