### ISSUE TITLE
Using both the "browser" and "Node" contexts concurrently

### ISSUE THREAD

**Issue by coltonoscopy** [nwjs/nw.js#3902]
Is it possible to be able to access browser and Node methods concurrently in a NW project? Previously, I was having everything require other modules without using Browserify, which was making things operate such that "document" was unavailable from within modules external to the main entry point script (my "main.coffee/main.js"), and this made it impossible to separate my classes (given Coffeescript) into separate files. I switched to Browserify and bundled everything together, and this got rid of "document" being unavailable, but now I can't use Node modules like "fs", which I need (I'm building a game using Phaser that also generates levels that need to be saved in JSON format).

I guess my overall question is: can I use both internal Node modules like "fs" while still having access to what I perceive is NW's "browser mode"? Thank you for your time and help!
##

**Comment by jyting** [comment]
To provide a possible solution to your initial problem of losing access to the document:

I personally have never touched CoffeeScript before, but if it's an option - refactor every module you originally had to be encapsulate in a factory that takes options - one of which is the 'document' that you need access to from all your files. You could then pass the document from main.js which is actually included as a script in your index.html - and you could then pass it everywhere, providing access to the 'document.'

E.g.:
In main.js which is included in the html file:
`var someModuleFactory = require('js/someModule.js');
 var someModule = someModuleFactory({
     document: document
});`

The 'someModule' would then have access to the document - you could apply this to anything in your project. I have been doing this for the JQuery (same difference, really) and the nw.gui part of NWjs for my project.

**Comment by ghostoy** [comment]
You can turn off builtin modules in Browserify
```none
--no-builtins

    Turn off builtins. This is handy when you want to run a bundle in node which
    provides the core builtins.
```
