### ISSUE TITLE
trouble in building nw12

### ISSUE THREAD

**Issue by haseebpk** [nwjs/nw.js#3905]
<b>On WINDOWS 7 64-bit following steps are performed to build nw12</b>

1-synced source from "https://github.com/nwjs/chromium.src.git@origin/nw12" by using 
```gclient sync --no-history```
before sync i removed ```content/nw``` from DEPS file as it was giving url error then manually cloned nw source of nw12 branch through following command
```D:\node-webkit\content\nw> git clone -b nw12 https://github.com/nwjs/nw.js.git```
2- Set Variable as per wiki
```D:\node-webkit>set DEPOT_TOOLS_WIN_TOOLCHAIN=0```
```D:\node-webkit>set GYP_MSVS_VERSION=2013```
```D:\node-webkit>set GYP_DEFINES=host_arch=x64 target_arch=x64```
```D:\node-webkit>set GYP_GENERATORS=ninja```

3- ```D:\node-webkit\src>python build/gyp_chromium content/content.gyp```
```Enabled Psyco JIT```
```Updating projects from gyp files...```

4-```D:\node-webkit\src>ninja -C out/Release_x64 nw -j4```
All 14926 files compiled with few warnings then stopped at linking

```[14926/14926] LINK_EMBED nw.exe```
from here i waited for 10 hours but no progress so after CTRL+C following errors appeared

```ninja: error: remove(nw.exe.pdb): Permission denied
ninja: build stopped: interrupted by user.
ninja: error: remove(nw.exe.pdb): Permission denied```

my Release_x64 binaries folder is of 9.21 GB size and wondering how it will reduce to 103MB which is size of downloaded build version and also can't find nw.exe in this folder
this is first time i'm building through ninja , how much time this linking actually takes or i'm doing something wrong. please guide

**Comment by haseebpk** [comment]
Thanks to Roger adivse; my  problem solved by increasing the RAM

**Comment by 823639792** [comment]
When I run build/gyp_chromium content/content.gyp just output:
$ ./build/gyp_chromium
Enabled Psyco JIT.
Updating projects from gyp files...
Using overrides found in C:\Users\yu\.gyp\include.gypi
Can you help me？
