### ISSUE TITLE
probleb with nw12 on start

### ISSUE THREAD

**Issue by microshine** [nwjs/nw.js#3906]
I have a problem with nw v.0.12.3. I joined ap.nw and nw.exe using `copy` function. Then I start my app and it works Ok. But then I created and login to my Windows 7 OS by domain user. My app doesn't start in this way. It shows start nw windows. I looked tmp node-webkit folder in tmp folder. It was created but haven't got all files (also it hasn't got `package.json` file). But sometimes it's running correctly (I see all extracted files).
So when I start my app from domain user it has sometime errors. When I start my app from user it works Ok.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8 with nwjs-sdk-v0.22.3. App which is created by local user works well in domain user. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
