### ISSUE TITLE
indexdb for multiple instance

### ISSUE THREAD

**Issue by kyle-ilantzis** [nwjs/nw.js#3907]
**When an app uses indexdb and has multiple nwjs instances open, indexdb fails.**

The sample mdn app https://github.com/mdn/to-do-notifications which can be tried out here http://mdn.github.io/to-do-notifications/ works on Google Chrome when you have it open on seperate tabs or seperate windows.

I adapted it for nwjs (just added package.json) here https://github.com/kyle-ilantzis/to-do-notifications. With one instance of nwjs it works just like in Google Chrome. When a 2nd instance of nwjs opens there is an error opening the database.

I cant say what the logs print for the sample mdn app. I just used the mdn sample to see if the problems I was having with indexdb were caused by nwjs.

I can however provide logs from my app found here https://github.com/kyle-ilantzis/pl-sql-client. When the 2nd nwjs instance opens I receive an error:

```
DOMError
message: "Internal error opening backing store for indexedDB.open."
name: "UnknownError"
```

And my friend has provided me with some of their logs:

```
[769:1016/203531:ERROR:leveldb_database.cc(302)] Failed to open LevelDB database from /home/plcstpierre/.config/pl-sql-client/IndexedDB/file__0.indexeddb.leveldb,IO error: /home/plcstpierre/.config/pl-sql-client/IndexedDB/file__0.indexeddb.leveldb/LOCK: No further details. (ChromeMethodPFE: 15::LockFile::1)
[769:1016/203531:ERROR:indexed_db_backing_store.cc(1025)] Unable to open backing store, not trying to recover - IO error: /home/plcstpierre/.config/pl-sql-client/IndexedDB/file__0.indexeddb.leveldb/LOCK: No further details. (ChromeMethodPFE: 15::LockFile::1)
```

As a workaround I open and close the indexdb database on each read/write operation (in the branch https://github.com/kyle-ilantzis/pl-sql-client/tree/history-multi-window) and that seems to work. However there are still cases where the 2 nwjs instances will fight for the indexdb "lock" and one of the 2 windows will fail to open the database. 

So as a second workaround I have added a retry loop, it tries at most 30 times and waits 500 milliseconds before trying again. This approach help with rare cases when one of the 2 nwjs instances could not open the database. However, it has to try 3 to 4 times which is almost 2 seconds of waiting.

---

**nwjs**
nw.js v0.12.3
io.js v1.2.0
Chromium 41.0.2272.76
commit hash: 591068b-b48a69e-27b6800-459755a-2bdc251-1764a45

**Google Chrome** 
Version 46.0.2490.71 m
##

**Comment by makkesk8** [comment]
Good read that might resolve your issue:
http://www.w3.org/TR/IndexedDB/#dfn-mode 

If you cannot solve this I recommend to switch to a more redundant db.

**Comment by kyle-ilantzis** [comment]
I dont think transactions are the problem.

The problem is that an app can run in Google Chrome in multiple tabs or multiple windows where as in nwjs that same app can only run on a single instance.

The code for https://github.com/mdn/to-do-notifications is using transactions.

**Comment by makkesk8** [comment]
Interesting... Seems nw.js is locking the db longer than it has to. Seems like the only logical explanation atm.

**Comment by Christywl** [comment]
http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/:

> single-instance is deprecated and it’s always true. You CANNOT have multiple instances for your app unless you’re using different user data directory (by --user-data-dir). You may also want to use the open event: the first instance will be notified with this event when user tries to launch the second instance.

I can open two instances with `--user-data-dir`, and notification works well.
`Linux/nwjs-sdk-v0.22.2`

**Comment by Christywl** [comment]
close until there is more information.
