### ISSUE TITLE
Debugging not working in latest version (live builds)

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#3910]
I tried to debug in live builds, but get white page. No logs, etc.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.2. Please try the latest nwjs build.

**Comment by sourceskyboxer** [comment]
@ghost You mean log
Same or may #862

**Comment by Christywl** [comment]
close until there is more information.
