### ISSUE TITLE
Can iframe working in a separated process like electron's <webview> ?

### ISSUE THREAD

**Issue by wilsoncook** [nwjs/nw.js#3911]
Formerly i used nw to build an browser-like app under Windows with iframe(like the wiki talked), i found that every "open/close" an iframe will use more memory and it will not decrease at all.
As i know, the iframe is just working in the single main process, can it being seperated?
##

**Comment by asuchar** [comment]
Hi, I believe support for the chrome <webview> tag was added in version 0.12 alpha
https://github.com/nwjs/nw.js/issues/1030

**Comment by mscreenie** [comment]
Yes. I experimented webviews previously and it does run in a separate process. 

It worked well but there was a rendering bug and some weird issue with CSS transitions. It flashes white when CSS transitioned. 

I am still using Iframes but will switch to webviews if this problem is resolved.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general, or submit the issue with detail.
