### ISSUE TITLE
通过 eval() 访问 iframe中的iframe 时程序自杀

### ISSUE THREAD

**Issue by wanjochan** [nwjs/nw.js#3913]
如题，通过 eval() 访问nwjs窗口中的 iframe中的iframe 时程序自杀
简单的猜测觉得应该是 在主线程中用eval 访问 js线程时，可能因为iframe中的iframe在另一个线程导致指针错误

**Comment by xueeinstein** [comment]
Using `eval()` to inject JavaScript code into iframe is quite tricky. My previous NW.js project used this tricky, and NW.js v0.12.0 supports it well. Please check your NW.js version. 

Even though `eval()` doesn't work, after you got the iframe reference, you almost can do everything in iframe, why must use `eval`?

By the way, please use English on github.

**Comment by wanjochan** [comment]
nwjs get suicides once access iframe in iframe, no matter using eval or direct access in iframe.iframe or even event "inject-js-start"

**Comment by wanjochan** [comment]
BTW, 楼上那位大咖，英语只是推荐语言，GITHUB不是强制要求的。而且现在全世界都在学习中文，说中文并没有问题的，挺直腰杆做人。

**Comment by xueeinstein** [comment]
The same code to operate iframe in iframe works on NW.js v0.12.0, but crashes on Chrome 45.0. So I believe it's chromium security update which forbidden this potential unsafe operation.

Using English on github is just for better communication. Maybe if you post your problem in English, many foreigner developers would provide better solutions.

**Comment by wanjochan** [comment]
OK, understand. thanks :)
