### ISSUE TITLE
建议：在"new-window-policy"中最好可以有办法捕获弹出后的html window

### ISSUE THREAD

**Issue by mgttt** [nwjs/nw.js#3914]
现在一般的做法是在 "new-window-policy" 时执行 policy.ignore() 然后重新用 open方法打开新的窗口。

但这样做法有两个问题，一，如果 url为空时无效（有时html应用会先window.open再往新window写入代码或者跳转）；二，html应用中如果要把open()的窗口句柄需要继续操作时，这样做法就无效。

建议可以在 policy.forceNewWindow() 或 .forceNewPopup() 中加参数 callback，当这个窗口弹出后呼叫这个 callback(newFrameWindow) 应该能彻底解决需求。
##

**Comment by dkfiresky** [comment]
Semi-automatic translation:
> Now general practice is to perform policy.ignore() when "new-window-policy" and then re-use the open method to open a new window.

> But this approach has two problems:
>  - if the url is empty, sometimes html application will first open a new window with window.open, write  code or jump.
>  - if we want to open a window then the handle is required to continue to operate, so the practice is invalid.

> Recommendations are to add callback parameter to policy.forceNewWindow() or policy.forceNewPopup(), when the window pops up call this callback (newFrameWindow) should be able to thoroughly address the needs.
