### ISSUE TITLE
Is it possible to programmatically log to stdout?

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/nw.js#3915]
I'd love to be able to use something like [bunyan](https://github.com/trentm/node-bunyan) to log to the command-line console. That might be impossible though. Could someone clear that up for me?
##

**Comment by karlrwjohnson** [comment]
Is [process.stdout.write()](https://nodejs.org/api/process.html#process_process_stdout) not suitable? I can use it from both <script>-included and require()'d modules.

The one caveat is that it expects a single string parameter, so you can't log, for instance, objects and expect it to print out properties like with console.log()

**Comment by adam-lynch** [comment]
Works on Mac, will confirm tomorrow when on Windows.

**Comment by adam-lynch** [comment]
Hmmm no, doesn't work. Probably for the same reason that the NW.js logs themselves aren't shown on Windows.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
