### ISSUE TITLE
Inject css/js

### ISSUE THREAD

**Issue by akashnimare** [nwjs/nw.js#3916]
How do I preload javascript files and inject css into an iframe?
##

**Comment by sapioit** [comment]
Also interested in this...

**Comment by tza17313** [comment]
you can use document-start event : [window document-start event](https://github.com/nwjs/nw.js/wiki/Window#document-start)

**Comment by sapioit** [comment]
I think for CSS it could be done with this JS, but you need it to be loaded using the solution presented above.

    var head=document.getElementsByTagName( "head" )[0];               
    head.appendChild( '<link rel="stylesheet" type="text/css" href="style.css">');

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
