### ISSUE TITLE
Whether the icon of tray and menuitem can be coloured?

### ISSUE THREAD

**Issue by BabyLillian** [nwjs/nw.js#3917]
for example, could we distinguish user status(like available, away, and do not disturb)by the color of the icon in chatting program. Only black seems not enough,as shown in the picture:
![image](https://cloud.githubusercontent.com/assets/12102261/10627974/398adc5e-77f2-11e5-9def-14851fda2053.png)
##

**Comment by CosmoMyzrailGorynych** [comment]
You may use progress bar's intermediate and 100% states %)

* [Window.setProgressBar(progress)](https://github.com/nwjs/nw.js/wiki/Window#setprogressbarprogress)

Or you may use a badge with text like "o" (offline), "a" (avaliable):

* [Window.setBadgeLevel(String)](https://github.com/nwjs/nw.js/wiki/Window#setbadgelabellabel)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
