### ISSUE TITLE
Is there a way to get current window(which one is focused)

### ISSUE THREAD

**Issue by leecade** [nwjs/nw.js#3919]
or maybe need reg a `focus` callback event in each html file to indicate which one is current window??

very stupid way, maybe I lost some api??

``` js
var gui = require('nw.gui')
var win = gui.Window.get()
win.on('focus', function() {
  global.currentWindow = win
})
```
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
