### ISSUE TITLE
Flash objects remains after been hidden

### ISSUE THREAD

**Issue by julienbu** [nwjs/nw.js#3921]
Hi !
The bug I've seen is quite simple.
I have a flash Object contained in an iFrame.
When I pass my iFrame into hidden state using the workaround proposed by @baconface in #3867, the iFrame globally disappear, but the the Flash object still appear during 50ms to 500ms.

Before Hide Action of the iFrame
![beforehide](https://cloud.githubusercontent.com/assets/8348537/10633876/17590f56-77ee-11e5-8440-0bbcfd5d2626.png)

After Hide Action of the iFrame
![afterhide](https://cloud.githubusercontent.com/assets/8348537/10633875/1755fc12-77ee-11e5-88c1-cc84d20c6d8f.png)

N.B : I was not quick enough to screenshot the bug, so the after state has been build with paint, but it is exactly what the user see during transition.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.22.3.

**Comment by Christywl** [comment]
close until there is more information.
