### ISSUE TITLE
Can nwjs realize tag like browser?

### ISSUE THREAD

**Issue by waiting0729** [nwjs/nw.js#3927]
hello all:)i want to use nwjs for opening a link to be a tab like browser.When i open a link,it will open a new window.It does not i want . meanwhile,the tab can close go through mouse click. I want to open a link like this:
![Image of Yaktocat](http://a3.qpic.cn/psb?/V10VfOdT0BMwie/kE1X4yK0Q135fxikJ.dwx2OmJ8suVZhs062jxkdq6T4!/b/dGQBAAAAAAAA&bo=5wJNAAAAAAADB4o!&rf=viewer_4)
  What  could I do  here?
Thanks in advance)))
##

**Comment by CosmoMyzrailGorynych** [comment]
You can create tabs, but for now you sholda code them by your own. I'm using riot and listening to multiple window events.

You can start from here: 

* [How to create a _**very** basic_ tabbed browser on nw.js](http://www.sitepoint.com/tabbed-browser-node-webkit-angularjs/)
* [Window events](https://github.com/nwjs/nw.js/wiki/Window#events)

**Comment by waiting0729** [comment]
I carefully read the article,thank you for very much~

**Comment by waiting0729** [comment]
I carefully read the article,thank you for very much~@CosmoMyzrailGorynych

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
