### ISSUE TITLE
Translating the Wiki to anothe languages

### ISSUE THREAD

**Issue by osvaldoabel** [nwjs/nw.js#3928]
Is there any way to contribute by translating the Wiki ?
##

**Comment by CosmoMyzrailGorynych** [comment]
It must be "Yes" x)
But I wonder, in which form? Should we create a separate repository or mb a bunch of pages in this one? 
I would like to translate wiki to Russian language.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
