### ISSUE TITLE
[nw 0.13] WebStorm debugging broken

### ISSUE THREAD

**Issue by TrevorPT** [nwjs/nw.js#3930]
I am currently able to run/debug a nw.js application with WebStorm and nw 0.12.3.  When I tried nw 0.13, though, debugging doesn't hit breakpoints and nothing is output to the WebStorm console.  

I did notice that nw.js is listening on a different port than the one shown in the console as one of the startup flags, eg. 

in the console: `nw.exe --remote-debugging-port=49563`
open port for nw.exe: `49564`

and each time I launch the debugger, the ports are one-off from each other.

Not sure if this is a nw.js issue, or one with WebStorm, but I logged an issue with JetBrains here: https://youtrack.jetbrains.com/issue/WEB-18588#tab=Comments
and they figure it may be due to the API compatibility (at this alpha stage) of nw 0.13.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
