### ISSUE TITLE
BUG - FileSystem - createReadStream - uncatchable Error

### ISSUE THREAD

**Issue by gesior** [nwjs/nw.js#3931]
When I try to open file that does not exist, it somehow throws uncatchable error:
(code to reproduce, tested on NWJS 0.12.3)

```
try
{
    var stream = fs.createReadStream('no_exist.exe')
}
catch(e)
{
    console.log(e)
}
```

'console.log' does not execute, but in console appear:

**Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\M\Desktop\file-explorer\no_exist.exe'**

This kills my child processes. Of course I can use **fs.accessSync** to check, if I can open file (**accessSync** error is catchable!), but **createReadStream** errors should be catchable as every other function errors.
##

**Comment by dkfiresky** [comment]
@gesior You should use event handler to handle errors in Readable streams:

```js
'use strict';

const FILE = `${__dirname}/read.txt2`;

let fs = require('fs'),
    stream = fs.createReadStream(FILE);

stream.on('readable', function() {
    console.log('stream is readable');
});

stream.on('data', function(chunk) {
    console.log('got %d bytes of data', chunk.length);
});

stream.on('end', function() {
    console.log('stream ended');
});

stream.on('error', function(error) {
    //if (error) throw error;
    if (error) console.log('error occured!');
});
```

Reference: [Readable Stream](https://nodejs.org/api/stream.html#stream_class_stream_readable)

**Comment by gesior** [comment]
@dkfiresky 
Of course I use error handlers to handle read/write errors, but this error occurs when I use:
**xyz = fs.createReadStream(fromLocalFile);**
so there is no stream (yet) to add error handler. Error comes from nowhere as 'uncaught'.

**Comment by Christywl** [comment]
@gesior , does dkfiresky's advice work for you?

**Comment by Christywl** [comment]
close until there is more information.
