### ISSUE TITLE
Set position x,y in i.e. bottom left, top left in manifest

### ISSUE THREAD

**Issue by bluejamesbond** [nwjs/nw.js#3932]
Is this possible? If so how?
##

**Comment by iteufel** [comment]
I think it's not possible, but you can use [Window.moveTo(x, y)](https://github.com/nwjs/nw.js/wiki/Window#windowmovetox-y).

	//Set window show in your manifest file to false.
	
	var gui = require('nw.gui');
	var win = gui.Window.get();
	win.moveTo(x, y)
	win.show()

**Comment by chaseWillden** [comment]
Is this solved?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
