### ISSUE TITLE
[Question] node-webkit didn't store app's data under the directory named name?

### ISSUE THREAD

**Issue by RyanBram** [nwjs/nw.js#3933]
Dear developer,
I am an indie developer using game engine as my tool.

When creating package.nw with nwjs, I set **nodejs** as **true**. But when my app create a save file, nwjs will automatically erase the save file during exit which make my game cannot be saved.

Based on the documentation, node-webkit will store app's data under the directory named **name**. Then I tried to set **nodejs** as **false**. It solve the problem as it store the data under the directory named name as document said. But unfortunatelly it will make some feature become unusable.

My question
Is it possible to make my game store its data under the directory named **name** even though I set **nodejs** as **true**?

Regards,
Ryan
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
