### ISSUE TITLE
Caching Issue - Loading angular js web application inside node webkit

### ISSUE THREAD

**Issue by hmikhail** [nwjs/nw.js#3934]
I am loading an angular js website inside node-webkit
Whatever updates I do to the templates takes much time to update in the desktop app even if the server is updated. Setting page-cache to false doesn't solve the issue. How can I prevent caching?

Removing C:\Users\MyUser\AppData\Local\APPNAME\Cache solves the issue.
Any help is appreciated.

My package.json

{
  "name": "AppName",
  "main": "index.html", 
  "webkit": {
         "page-cache":false
   },
  "window": {
    "toolbar": false,
    "icon": "images/ico.png",
    "width": 731,
    "height": 552,
    "min_width": 731,
    "min_height": 552,
    "max_width": 731,
    "max_height": 552,
    "show_in_taskbar": true,
    "show":false,
    "position" : "center"  
  }
}

Attached index.html file.
![image](https://cloud.githubusercontent.com/assets/2143018/10763158/886359c6-7cd1-11e5-9941-51fcded0ef3a.png)
##

**Comment by glenn9** [comment]
Try using version numbers in your files to force the download of the new files, eg templates.js?v=1234

**Comment by hmikhail** [comment]
I already do that, the website is updated normally, but node webkit app doesn't

**Comment by glenn9** [comment]
Do you reload the page in nw.js after reuploading the templates? Actual reloading not changing the location

**Comment by hmikhail** [comment]
No I just close and re open the app, isn't that enough?

**Comment by glenn9** [comment]
Browsers in general can be aggressive when caching. Version strings in files and Angular templates should be enough since it forces a redownload of the file.

**Comment by gwicksted** [comment]
That sounds like it was a cache control header from the server causing it to persist across app reloads.  You might be able to work around it via `window.reloadIgnoringCache();` or `app.clearCache();` or possibly a chromium arg:
```
"chromium-args": "--disk-cache-size=1 --media-cache-size=1 --incognito"
```
or a webkit setting:
```
"webkit": {
    "page-cache": false
},
```
(the last 2 suggestions are in your package.json)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please upload your full tests and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
