### ISSUE TITLE
v0.13.0-alpha4 doesn't work because it cannot load libnode.so

### ISSUE THREAD

**Issue by jungyilin** [nwjs/nw.js#3938]
We are currently using v0.12 and everything works well.
I just downloaded the lastest v0.13.0-alpha4 for linux x64 to make an upgrade. However it shows error at renderer_main.cc, libnode.so, cannot open shared object file, no such file or directory.
libnode.so is at the lib directory. I copied it to /lib, /usr/lib, or with nw executable file, no luck.
If anyone has clue please let me know, thanks.

**Comment by rogerwang** [comment]
Please add `--no-sandbox` in the command line as a workaround. Will fix it in the next version. Thanks.

**Comment by rogerwang** [comment]
fixed in git.
