### ISSUE TITLE
when min_width/min_height in package.json, the window size will change after minimize the window

### ISSUE THREAD

**Issue by lindn0** [nwjs/nw.js#3941]
I add min_width/min_height in package.json, same to width/height. For example:
        "width": 800,
        "height": 600,
        "min_width": 800,
        "min_height": 600,

When I minimize the app, then restore the app, I found the window size of the app has changed.
How to fix it?
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows  with nwjs-sdk-v0.22.2.

**Comment by lindn0** [comment]
I test on Windows with nw.js v0.12.2 two years ago.

**Comment by lindn0** [comment]
I test on Windows with nw.js v0.12.2 two years ago.

**Comment by Christywl** [comment]
Does it reproduce for you with the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
