### ISSUE TITLE
nw.exe close instantly

### ISSUE THREAD

**Issue by fredaudy** [nwjs/nw.js#3942]
Hi Everybody,

my node-webkit (v0.12.3-win-64) application, which prevously run fine (on win 8.1),
now close instantly when i launch nw.exe, without no errors message.

is there someone who can deal with this issue?
(and sorry for my poor english)
##

**Comment by fredaudy** [comment]
it seem's to be ann issue du to the 64bit version,

all my node-webkit applications build on the v0.12.3-win-x64 are down,
while the applications build on the x32bit version are running well.

????!!!!!

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 64bit with nwjs-sdk-v0.22.2.

**Comment by Christywl** [comment]
close until there is more information.
