### ISSUE TITLE
win.focus() / win.show() doesn't bring the window to the top.

### ISSUE THREAD

**Issue by robinknaapen** [nwjs/nw.js#3944]
As i read in the previous version of this issue https://github.com/nwjs/nw.js/issues/341, I also have this problem and i guess allot more people do too.<br>
In my case i try to focus the application after i clicked a notification. it will just flash in the taskbar and nothing happends.<br>

``` javascript
var gui = require('nw.gui');
var win = gui.Window.get();
// both these functions make the icon blink in the taskbar
win.focus();
win.show();
```
##

**Comment by chaseWillden** [comment]
What version of nw are you using? Is this still an issue?

**Comment by iXshad0w** [comment]
I will try to update, i was using the latest stable at the time.  I will keep you informed. First school :V

**Comment by Christywl** [comment]
`win.focus()` and w`in.show()` work well on Windows with nwjs-sdk-v0.22.2.

**Comment by Christywl** [comment]
close until there is more information.
