### ISSUE TITLE
How can I know if a single-instance nwjs app run(double click exe) twice or more

### ISSUE THREAD

**Issue by nigelvon** [nwjs/nw.js#3949]
Is there any event will be trigger(or other way) when a running nwjs app be double clicked again?

**Comment by dkfiresky** [comment]
You can use something like (File Locking)[https://en.wikipedia.org/wiki/File_locking] to lock a single file and check that file each time your application runs.

**Comment by nigelvon** [comment]
But I can't run any code when the app is already running.

**Comment by dkfiresky** [comment]
You should create lock file when your app initialisation starts. If you run application second time, lock file will be already created, so your app can check that and prevent/continue running.

**Comment by nigelvon** [comment]
A single-instance app can run twice? The problem is that I can do nothing when the app is already running.

**Comment by dkfiresky** [comment]
How do you think your idea should be implemented? If you can't run any checks while your app is already running, then it's problem with your implementation/idea, because you're asking not logical things to happen.

There is no API in nw.js for such things.

**Comment by nigelvon** [comment]
I just want to show() and focus() the running app, when user launch the app again.

**Comment by dkfiresky** [comment]
Check following docs:
[Manifest format](https://github.com/nwjs/nw.js/wiki/Manifest-format)
[Play with window](https://github.com/nwjs/nw.js/wiki/Play-with-window)
[Show window after page is ready](https://github.com/nwjs/nw.js/wiki/Show-window-after-page-is-ready)

**Comment by nigelvon** [comment]
Yeah, Thanks, I knew these docs.
But the nwjs will trigger nothing when user re-launch the app.
The problem is: How can I knew It, when the app re-launched.

**Comment by rdtsc** [comment]
Pick one of the following:

1. Patch NW.js not to bail when it finds a lockfile in `App.dataPath`.
2. Notify your app's master instance that it should focus itself via client-side code. See below for a possible bare bones implementation.
3. Use a separate launcher process that does this for you. Since you mentioned `exe`'s, take a look at `EnumProcesses`, `EnumWindows`, and `GetWindowThreadProcessId` from the Windows API.

Either way, you should handle cases where your app is going to be running concurrently under mutliple user accounts.

![1](https://cloud.githubusercontent.com/assets/6773893/10948838/9e379c80-82fd-11e5-883e-f9ed880378ca.gif)

### package.json
```json
{
  "name": "nw.js",
  "main": "index.html",
  "single-instance": false,
  "window": {
    "show": false
  }
}
```

### index.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NW.js App</title>
    <script src="single-instance.js"></script>
  </head>
  <body>
    <h1>Instance: <span id="app-id"></span></h1>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        document.querySelector('#app-id').innerText = Date.now();
      });
    </script>
  </body>
</html>
```

### single-instance.js
```javascript
(function() {
  'use strict';

  var gui = require('nw.gui');
  var http = require('http');

  var ipcServer = http.createServer(function(request, response) {
    if(request) gui.Window.get().focus();
    response.end();
  });

  ipcServer.on('error', function(error) {
    if(error.errno === 'EADDRINUSE') {
      http.get({hostname: '127.0.0.1', port: 37561}, function(response) {
        process.exit(0);
      });
    }

    else process.exit(1);
  });

  ipcServer.listen(37561, '127.0.0.1', function() {
    gui.Window.get().show();
  });
})();
```

Also consider playing around with [persistent storage](https://github.com/nwjs/nw.js/wiki/Save-persistent-data-in-app) and call `Window.show` when your master process gets a data change notification.

**Comment by nigelvon** [comment]
Thanks, rdtsc. It's brilliant.

**Comment by cecilpeng** [comment]
why not use the open event of nw.App ?

**Comment by octachrome** [comment]
The `open` event suggested by @cecilpeng answers the original question perfectly:

    var gui = require("nw.gui");

    gui.App.on('open', function (argString) {
        // Parse argString to find out what args were passed to the second instance.
    });

**Comment by maikonmatheus** [comment]
To just show() and focus() the running app when the user tries to open a new instance, the following code (based on comments above) is already sufficient:

`nw.Window.open(win_url, { }, (win) => {
  gui.App.on('open', function(argString) {
    win.maximize();
    win.show();
    win.focus();
  });
});`

**Comment by maikonmatheus** [comment]
To just show() and focus() the running app when the user tries to open a new instance, the following code (based on comments above) is already sufficient:

```
nw.Window.open(win_url, { }, (win) => {
  gui.App.on('open', (argString) => {
    win.maximize();
    win.show();
    win.focus();
  });
});
