### ISSUE TITLE
OAuth worflow redirect in nw.gui window popup error

### ISSUE THREAD

**Issue by hermesdj** [nwjs/nw.js#3951]
Hello,

I am trying to implement an Oauth style worflow process : i open a new window using 

``` javascript
var gui = require('nw.gui'), win = null;
var defaults = {
    focus: true,
    position: 'center',
    width: 300,
    height: 500,
    toolbar: true //this is just for dev purpose
};
win = gui.Window.open(url, options);
```

With the url set to my oauth provider (which is a local one, not a known one like dropbox or google).  My oauth flow is working but when the server sends a redirect to my callback_url passed as parameter in the original url (which is https://localhost/callback), the popup window has a correct location such as https://localhost/callback?token=MY_TOKEN but when i try to access this field from my original code like 

``` javascript
win.on('loaded', function () {
    console.log('loaded', win.window.location.href);
});
```

The data returned is 'data:text/html,chromewebdata', therefore my code does not detect the original callback_uri and cannot retrieve the token, and that's a "bit" problematic. FYI, this is displayed only when the popup receives the redirect. For the previous step of the oauth workflow, the Href change is correct...

Does anyone have any idea what is wrong with my code ?

For info, and for dev purposes, here are some configuration line of codes i have in the application :
gui.App.addOriginAccessWhitelistEntry('*', 'app', 'myapp', true);
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full tests to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
