### ISSUE TITLE
Injecting cookies into the app

### ISSUE THREAD

**Issue by toptierlabs** [nwjs/nw.js#3952]
Im creating a node-webkit app, and for advertising purposes, I need to extract cookies from browsers and inject them into the app. I know that node-webkit is basically a chromium, so it stores cookies into a sqlite database. While im able to inject cookies into this sqlite database, Im not seeing any cookies in the app ( developer console, resources, cookies ).

Anyone knows how does chromium knows if X third-party cookie should be shown in Y webpage? Or anyone has any idea how could I collect advertising cookies from browsers and place them into the app?

thanks in advance!
##

**Comment by iteufel** [comment]
https://github.com/nwjs/nw.js/wiki/Window#windowcookies
