### ISSUE TITLE
Problem with Facebook and touch screen [$100]

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#3953]
When using touch to close shared image in Facebook, nwjs freezes and stop responding to any further interaction- need to be killed and restarted. However, when that same image is closed by mouse click it doesn't cause any problem. 

How to reproduce:

On Windows touch screen device (tablet or AIO), unpack latest nwjs 0.12.0 and run nw.exe to open browser. In browser, open Facebook.com, login into Facebook and open any shared image. Touch "x" mark in image corner with finger in order to close it. Result is nw.js is "frozen" and does not respond to any further interaction.
##

**Comment by krneticz** [comment]
Update: this is happening with both 0.12.3 and 0.13.alpha5 32 bit and 64 bit.

**Comment by Christywl** [comment]
Is this still reproduced for you on the latest nwjs build? Seem it works fine for me on Windows nwjs-sdk-v0.24.4.

**Comment by sourceskyboxer** [comment]
What's fuck why do you need Facebook connection? Oh shit bad liar want get NW.js thanks for hurting me. And bye i never develop with nw.js now why do you care shitlikers of Facebook? I am mad now.

**Comment by Christywl** [comment]
close until there is more information.
