### ISSUE TITLE
Speedtest.net tests causes nwjs to stop responding

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#3954]
When singe multiple broadband tests on the website http://speedtest.net, it takes 5 tests in a row at maximum, to cause nwjs to stop responding. Sometimes it stops responding at second attempt.

How to reproduce:

On Windows 8 or 7, use latest stabile nwjs 0.12.0 with latest stabile NPAPI flash player enabled, open http://speedtest.net and do tests.

I have built simple test app that just have this as index.html:

<html>
	<head>
	
	</head>
	<body>
	</body>
	<script type="text/javascript">

	window.location.href='http://speedtest.net';
	</script>
</html>

And this is package.son:

{
  "name": "nwtest",
  "description": "nwtest",
  "version": "0001",
  "main": "index.html",
  "single-instance": true,
  "node-remote": "<local>",
  "chromium-args": "--enable-strict-site-isolation --enable-usermedia-screen-capturing --enable-http-screen-capture  --ignore-certificate-errors --allow-running-insecure-content --enable-media-stream --disable-session-crashed-bubble --unlimited-storage",
  "window": {
    "title": "nwtest",
    "width": 1024,
    "height": 768,
    "toolbar": false,
    "frame": true,
    "show": true,
    "kiosk": false,
    "fullscreen": false,
    "always-on-top": false,
    "resizable": false 
  },
  "webkit": {
    "plugin": true,
    "java": false
  }
}

In plugins folder there are NPSWF32.dll and NPSWF64.dll, flash player 19.0.0226 . NOTE: It is happening with older flash players too: 17, 18 ...

**Comment by krneticz** [comment]
Update: This is only happening with NPAPI Flash, not with PPAPI Flash!

**Comment by rogerwang** [comment]
close as NPAPI is not supported.
