### ISSUE TITLE
Wrong path to nw after npm install (in OS X)

### ISSUE THREAD

**Issue by taseenb** [nwjs/nw.js#3957]
I did:

```
npm install -g nw
```

Then:

```
nw
```

And got this error:

```
bash: /Applications/node-webkit.app/Contents/MacOS/node-webkit: No such file or directory
```

The path is wrong.
The right path should be `/usr/local/lib/node_modules/nw/bin/nw`

I can temporarily fix it manually with:

```
alias nw=/usr/local/lib/node_modules/nw/bin/nw
```
##

**Comment by dkfiresky** [comment]
Everything works fine for me:
```js
 ~ ❯ npm install -g nw
/Users/dkfiresky/npm/bin/nw -> /Users/dkfiresky/npm/lib/node_modules/nw/bin/nw

> nw@0.12.3 postinstall /Users/dkfiresky/npm/lib/node_modules/nw
> node scripts/install.js

nw@0.12.3 /Users/firesky/npm/lib/node_modules/nw
├── merge@1.2.0
├── file-exists@0.1.1
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── multimeter@0.1.1 (charm@0.1.2)
├── semver@4.3.6
├── rimraf@2.4.3 (glob@5.0.15)
├── yargs@3.29.0 (camelcase@1.2.1, decamelize@1.1.1, window-size@0.1.2, y18n@3.2.0, os-locale@1.4.0, cliui@3.0.3)
├── decompress@2.3.0 (get-stdin@4.0.1, vinyl-assign@1.2.1, concat-stream@1.5.1, buffer-to-vinyl@1.1.0, stream-combiner2@1.1.1, decompress-unzip@3.4.0, decompress-tar@3.1.0, decompress-tarbz2@3.1.0, decompress-targz@3.1.0, meow@3.5.0, vinyl-fs@1.0.0)
└── download@3.3.0 (get-stdin@3.0.2, gulp-rename@1.2.2, each-async@1.1.1, url-regex@2.1.3, vinyl@0.4.6, stream-combiner@0.2.2, ware@1.3.0, rc@0.5.5, decompress-unzip@2.1.2, through2@0.6.5, meow@2.1.0, concat-stream@1.5.1, decompress-targz@2.1.0, decompress-tar@2.0.2, decompress-tarbz2@2.0.2, download-status@2.2.1, vinyl-fs@0.3.14, request@2.65.0)
```

Maybe you should check your nodejs/npm configuration.

**Comment by taseenb** [comment]
@dkfiresky did you try to run `nw` after installing?

installing is not the problem.

**Comment by dkfiresky** [comment]
@taseenb yes, everything works fine

**Comment by ghostoy** [comment]
Did you setup the `alias` to nw before?
BTW, you should raise this issue in [nwjs/npm-installer](https://github.com/nwjs/npm-installer) repo.

**Comment by taseenb** [comment]
@dkfiresky @ghostoy I never set the alias before. I think that happened because i installed the old NWJS with the OS X installer some time ago, before installing it globally with npm. That's why it is looking for `/Applications/node-webkit.app/Contents/MacOS/node-webkit`. It is strange that is it looking for the old node-webkit path though. 

Anyway thanks for your help. Sorry for posting it in the wrong repo.

**Comment by dkfiresky** [comment]
@ghostoy there is no need to setup alias for nw.js binary.
@taseenb you might want to check following directories:
- ~/npm/bin (there might be symlink to wrong binary)
- ~/npm/lib/node_modules (there should be package `nw`)
- ~/.npm (there might be cashed version of nw.js module)

**Comment by taseenb** [comment]
@dkfiresky thanks. I tried everything (cleaning npm's cache, removing all nw related packages and nw itself) and still, the alias was there. If i did `unalias nw`, it would come back after i logged back in. Finally i opened the `~/.bash` and `/.bash_profile` (hidden files in OS X), to see if there was something there. 

I found this in `/.bash_profile`: 
```
# alias to nw
alias nw="/Applications/node-webkit.app/Contents/MacOS/node-webkit"
```

Not sure *who/what* put it there. I suppose, it was the old OS X Node Webkit installer?

**Comment by dkfiresky** [comment]
@taseenb I'm glad you found it :+1:. We're all sometimes forget what we done.

**Comment by Christywl** [comment]
`npm install -g nw` works well for me on Mac.

**Comment by Christywl** [comment]
close until there is more information.
