### ISSUE TITLE
[Question] Scraping Dynamic content issue

### ISSUE THREAD

**Issue by himanshu1691** [nwjs/nw.js#3958]
Was anyone able to do dynamic content scraping in Nodewebkit?
I tried using phantom and tried using jsdom.
Either I get import issues or the function is not recognizable?
If anyone was able to do it can you please tell me what I should use and how?

**Comment by iteufel** [comment]
Try [cheerio](https://www.npmjs.com/package/cheerio) + [request](https://www.npmjs.com/package/request).

**Comment by makkesk8** [comment]
@iteufel Cheerio can't parse dynamic context i've been told.
@himanshu1691 I have had success using phantomjs (on linux though), and I see you've tried it. Try googling about your errors.

**Comment by himanshu1691** [comment]
Found it.
Yes, cant be done using cheerio.
Worked easily using node-phantom-simple module.
