### ISSUE TITLE
Prompt window renders clipped and without icon

### ISSUE THREAD

**Issue by hems** [nwjs/nw.js#3959]
I just realised that the Prompt window ( generated by javascript command "confirm" ) :
- renders clipped 
- without an icon ( like the OSX version )
- Doesn't close after pressing "RETURN" ( have to manually click the clipped button )

Running nw-js version 0.12.3 on this Virtual Machine i'm using running WIN7

Win:
![screen shot 2015-11-08 at 05 30 02](https://cloud.githubusercontent.com/assets/27327/11018963/08c0b5bc-85da-11e5-9218-0cbf900e5e53.png)

OSX:
![screen shot 2015-11-08 at 05 32 38](https://cloud.githubusercontent.com/assets/27327/11018964/24c57608-85da-11e5-9b0e-98796bdf8e38.png)
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by hems** [comment]
@Christywl i opened this issue  Nov 2015! 

i didn't test with the latest unfortunately and probably won't be testing so soon!
