### ISSUE TITLE
[nw13] alpha5: https is not working

### ISSUE THREAD

**Issue by andresiraola** [nwjs/nw.js#3960]
The "http" module loads and works correclty (so far) but I cannot use "https".

I try to load it by doing:

```javascript
var https = nw.require('https');
```
but I get a blank page and devtools doesn't show up when I press F12.

It seems like some kind of deadlock when node is trying to load the module.

Did you have the same problem? Is there a temporary workaround? How can I help you to fix it? Do you have an idea of what can be the issue here?

Thanks!

**Comment by phil-legitmix** [comment]
I am having problems with https as well. I created a separate project where I make an http request to https://www.google.com and I get the following output when I run the app:

```
[1113/190904:INFO:nw_package.cc(175)] /home/phil/Downloads/nwjs-sdk-v0.13.0-alpha5-linux-x64/nw .
[22454:22454:1113/190904:ERROR:sandbox_linux.cc(340)] InitializeSandbox() called with multiple threads in process gpu-process
../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected. 
[1113/190905:ERROR:nacl_helper_linux.cc(314)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
```

Here are my exact steps to reproduce.

1. Make a new directory (mine was in /tmp) with 4 files
    * package.json
    * main.html
    * test.js

2. Make the contents of package.json to be:

	```json
	{
	   "name": "ssltest",
	   "main": "main.html",
	   "dependencies": {
	      "console.log": "*"
	   }
	}
	```

3. Make the contents of main.html to be:

	```html
	<!DOCTYPE html>
	<html>
	<head>
	   <script>
	      var nw = nw || this;
	      nw.require('./test.js');
	   </script>
	</head>
	<body>
	   <h1>TEST</h1>
	</body>
	</html>
	```

4. And test.js should contain:

	```javascript
	require('console.log');

	var https = require('https');
	https.get('https://www.google.com', function(response){
	   console.log('status code:', response.statusCode);
	   var body = "";
	   response.on('data', function(chunk){
	      body += chunk;
	   });
	   response.on('end', function(){
	      console.log(body);
	   });
	});
	```

5. Finally cd into the directory and run "npm install ." and then run the app with the nw binary (something like "/path/to/nw .")

Your terminal should display 200 followed by the html content of google's home page. However at the moment, using the alpha 5 build this crashes nwjs.

**Comment by rogerwang** [comment]
It's fixed now.

**Comment by phil-legitmix** [comment]
I just tried this with the nwjs-sdk-v0.13.0-beta2-linux-x64 and the nwjs-sdk-v0.13.0-beta3-linux-x64 build from Jan 13, 2016 and my test above crashes in pretty much the same way I originally mentioned. Output follows

"""
[13472:13472:0112/154510:ERROR:sandbox_linux.cc(340)] InitializeSandbox() called with multiple threads in process gpu-process
../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected.
"""
