### ISSUE TITLE
gm works with node, in nw.js error occurs

### ISSUE THREAD

**Issue by emmanuelmillionaer** [nwjs/nw.js#3961]
I have a simple script:

```
var fs = require('fs')
    , gm = require('gm');

function Preview(){
  gm("/Users/hans/Desktop/DSC00980.JPG")
         .crop(300,300,0,0)
         .write("/Users/hans/Documents/scans/nicky.JPG", function (err) {
            console.log(err);
            if (!err) console.log('done');
         });
 }

 module.exports = Preview;
```

When I let it run in a node console, it works, I see a resized image:

```
node
var Preview = require('./Preview.js')
new Preview();
```

<b>However when requiring it in nw.js I get an error:</b>

```
 Could not execute GraphicsMagick/ImageMagick: gm "convert" ....
 this most likely means the gm/binaries can't be found
```

<p> In my nw.js project I call this code in index.html with:</p> 

```
       <scrip>
             var Preview = require('./Preview.js')
             new Preview();
       </script>
```

<b>What do I wrong? Is there some restriction in nw.js which I have to disable? Thanks for your help!</b>
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.22.2.
`gm = require('gm').subClass({imageMagick: true});`

**Comment by Christywl** [comment]
close until there is more information.
