### ISSUE TITLE
Packaging app into .exe opens as the default nw:blank gray page

### ISSUE THREAD

**Issue by ilaif** [nwjs/nw.js#3962]
Hey guys,

I've used both nwbuild (nwbuild -v 0.12.0 -p win32 <path_to_app>) and manual packaging of app (zip app, rename to .nw, copy with nw.exe -> run with dlls in the same folder) and it opens like so:
![screen shot 2015-11-09 at 18 14 30](https://cloud.githubusercontent.com/assets/3540825/11038863/bde54e2e-870d-11e5-84a9-bbf0c4574e70.png)

You can see versions attached.

I also noticed that when I run "nwbuild -r" it works fine.

Anyone knows what's causing this? Not sure what I did wrong

Thanks for the awesome product!
Ilai
##

**Comment by Blatman** [comment]
Hi there,
not sure if it is your issue but I had an exe on Windows 10 that would start and give me the NW.JS screen as above rather than run the app.  I had used Web2Executable to build the app and on OSX it worked fine but in the end it turned out to be a node_module package (sync-request I think) that was using paths too long for windows to handle - once the module was removed the exe worked fine.

**Comment by ilaif** [comment]
Thanks Blatman!

How did you find out about this? console.log not showing anything interesting...

**Comment by Blatman** [comment]
Probably luck really - I was using Windows in Parallels and tried to copy the app source project to the VM which then allows you to run the app without packaging by dragging the App folder onto a copy of nw.exe. In this case Windows was not allowing the project transfer and gave an error indicating a path in a sub-folder was too long - Windows has never liked long paths.

**Comment by Christywl** [comment]
`Package to a zip file, rename to .nw, copy with nw.exe` works well on Windows with nwjs-sdk-v0.22.2.

**Comment by sourceskyboxer** [comment]
I think better another method:
If you have problem with zip / nw
No problem:
Just buy BoxedApp Packer
Input nw.exe output nw_embed.exe
and add directory path to root of nw.exe and dlls, paks...

Than you make sure if your package.json in directory example <root directory of nw>/app/ <here is contents of package.json >
You switch enable commandline bottom of output nw.embed.exe or /output/nw.exe
<BoxedAppVar:OldCmdLine> ./app/
and build it and check where is problem? Non errors.

I hope my good method helps you.

**Comment by Christywl** [comment]
close until there is more information.
