### ISSUE TITLE
freeing "nwjs helper" memory

### ISSUE THREAD

**Issue by ziwar** [nwjs/nw.js#3963]
window.reload is not freeing memory of "nwjs helper" renderer. 
window.reloadDev does by instantiating a new renderer but it never kills the old renderer process. it keeps accumulating them... so if I call reloadDev 5 times I will get 5 extra processes of the helper and these processes do not exit even if I quit the app... 
The only thing that is truly freeing memory is app restart.
I am using 0.13.0

How can we free memory without restarting the entire app?

**Comment by makkesk8** [comment]
Duplicate of https://github.com/nwjs/nw.js/issues/3519 ?
