### ISSUE TITLE
v0.13.0-alpha5 Doesn't work because it cannot load libnode.so

### ISSUE THREAD

**Issue by joneqian** [nwjs/nw.js#3964]
I just downloaded the lastest v0.13.0-alpha5 for linux x64.
However it shows error at renderer_main.cc, libnode.so, cannot open shared object file, no such file or directory.
libnode.so is in 'nwjs/lib/'!
If anyone has clue please let me know, thanks.

**Comment by rogerwang** [comment]
Please add `--no-sandbox` in the command line as a workaround. Will fix it in the next version. Thanks.

**Comment by rogerwang** [comment]
close as duplicate of #3938

**Comment by hjondi** [comment]
sometimes it happens because you don't have execute permission to the folder of nw
