### ISSUE TITLE
v8 snapshot not load in subdirectory

### ISSUE THREAD

**Issue by glmanhtu** [nwjs/nw.js#3965]
I've got an issue that v8 snapshot not working when I click tag <a> to redirect to subdirectory. For example :
My working tree: 
![screen shot 2015-11-12 at 9 27 28 am](https://cloud.githubusercontent.com/assets/6909106/11109160/380b6f8a-8920-11e5-98a7-4087590499fc.png)
In package.json, I'm using index.html (root) as main

> "main": "index.html", 

In index.html (root), I'm create <a> tag to redirect to subdirectory

```
<!DOCTYPE html>
<html>
<body>
   <a href="S3/index.html">move</a>
</body>
</html>
```

in index.html (subdirectory), i'm calling v8 snapshot

```
<!DOCTYPE html>
<html>
<body>
<script> require('nw.gui').Window.get().evalNWBin(null, 'addfunc.bin');</script>
<script>
    document.write(add(3,4));
</script>
</body>
</html>
```

file addfunc.js :

```
function add(a, b){
    return a+b;
}
```

If I remove index.html (root) and move index.html (subdirectory) to root, v8 snapshot now working. 

My question's how to keep index.html in subdirectory and make v8 shapshot working ?
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.2. 

`<script> require('nw.gui').Window.get().evalNWBin(null, './S3/addfunc.bin');`

**Comment by Christywl** [comment]
close until there is more information.
