### ISSUE TITLE
ffmpeg for nwjs 13?

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#3967]
Just preparing myself for upcoming nwjs 13 stable and was looking around. I couldn't find a ffmpegsumo file on Windows sdk or dist packages.

So i'm guessing the file name has changed or functionality of this file is built into the build. Can anyone shed some light on this? @jtg-gg  @rogerwang 

Does nwjs support various codecs out of the box?

Thank you guys for an awesome project.

**Comment by phil-legitmix** [comment]
+1

The instructions here no longer work https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.

**Comment by jtg-gg** [comment]
chrome now statically link the ffmpeg library by default :(
I've successfully make a build supporting mp4, change the 'ffmpeg_branding%' to 'Chrome'
and in buid/common.gypi, search for 'proprietary_codecs%' set it to 1

**Comment by rogerwang** [comment]
yes, now you have to rebuild nw.js because upstream make ffmpeg builtin. @jtg-gg could you please update the wiki with your steps? thanks in advance.

**Comment by mscreenie** [comment]
Thank you both, I will be interested in knowing how to do this with the new changes.

**Comment by smolleyes** [comment]
+1 for the new build infos if possible :)

**Comment by rogerwang** [comment]
merge with #4492 . Please see the updates there.
