### ISSUE TITLE
outside the exit  :    FATAL:render_frame_host_manager.cc(869) 

### ISSUE THREAD

**Issue by baihuibo** [nwjs/nw.js#3968]
In the frequent operation 'refresh button' and 'history.back()' greater chance outside the exit, the console information is as follows 

[21963:1113/174841:FATAL:render_frame_host_manager.cc(869)] Check failed: !dest_instance->IsRelatedSiteInstance( render_frame_host_->GetSiteInstance()). 
** Unknown exception behavior: 0

Process finished with exit code 133

**Comment by ghostoy** [comment]
Please post the nw version / os / code / steps to reproduce. Thanks.

**Comment by baihuibo** [comment]
nw   nwjs-v0.12.3-osx-x64
os    os x 10.11.1
code  https://github.com/baihuibo/testNw

steps   :  
1  'index'and'new' page to visit each other repeatedly,
2  Next click the 'refresh' button,
3  The next step is still to visit several times,
4  Start clicking the'back'button several times,
5  Program interrupt

**Comment by ghostoy** [comment]
I can't reproduce it with given configuration.

**Comment by baihuibo** [comment]
OK
I recorded the video and uploaded it to the demo project.
github https://github.com/baihuibo/testNw

**Comment by ghostoy** [comment]
I can reproduce it now. It only crashes when clicking **the reload button on right toolbar**.

**Comment by YLivay** [comment]
Hey, is this issue abandoned? We've just encountered this on nwjs 0.12.3, Fedora 23 x64.

**Comment by ghostoy** [comment]
We have moved on to nw14 now. And toolbar doesn't exist since nw13. I suggest you to migrate from nw12 to nw14. Here is the migration notes http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/
