### ISSUE TITLE
when  download nwjs , whether add progress bar?

### ISSUE THREAD

**Issue by xuwenmin** [nwjs/nw.js#3969]
when  download nwjs , whether add progress bar ?

**Comment by ghostoy** [comment]
Do you mean how to show progress bar when downloading files with nw.js?
If so, you can use XHR to download and attach "progress" handler with it (see [this doc](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress)).
Or use Node modules, like [request-progress](https://www.npmjs.com/package/request-progress), to get the progress info.

**Comment by ghostoy** [comment]
If you have further questions, please post your questions on [Gitter](https://gitter.im/nwjs/nw.js) or [Google Groups](https://groups.google.com/forum/#!forum/nwjs-general).
