### ISSUE TITLE
[nw13] [Win] [bug] Invalid value for 'app.urls[0]'

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nwjs/nw.js#3972]
My project worked on nw.js v0.12.3 but it fails to load on v0.13.0 a5 :c
I'm trying to load it on Windows by dragging an app's folder to the nw.exe file, but it shows me such a message:

![default](https://cloud.githubusercontent.com/assets/3174357/11172137/d3b21e44-8c5d-11e5-8a3c-72a54de49fb6.JPG)

And my package.json doesn't have such fields.
I can also see that since that two nw.js processes begin to hang forever.
My version:
![default](https://cloud.githubusercontent.com/assets/3174357/11172126/adcba9b6-8c5d-11e5-9731-25964fd84b7f.JPG)
##

**Comment by CosmoMyzrailGorynych** [comment]
#3881 may be the same problem

**Comment by CosmoMyzrailGorynych** [comment]
#3881

**Comment by rogerwang** [comment]
could you please provide a sample for this bug?

**Comment by prathap0611** [comment]
I too faced the same issue. The problem in my case is I was using node-remote attribute as "<local>" which is deprecated in 0.13.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.2 when drag an app's folder to the nw binary folder.

@prathap0611 , please see the docs about `node-remote`: http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

> The format of node-remote is changed to array of match patterns used by Chrome extension.

**Comment by Christywl** [comment]
close until there is more information.

**Comment by yyf1994gggg** [comment]
> I too faced the same issue. The problem in my case is I was using node-remote attribute as "" which is deprecated in 0.13.

you are right ,just remove the node-remote from pachage.json
