### ISSUE TITLE
[nwjs13 alpha5] Crashes when using the exec function of the child_process module

### ISSUE THREAD

**Issue by phil-legitmix** [nwjs/nw.js#3975]
Title says it all, try `require('child_process').exec('ls')` to reproduce. I'm on CentOS 7. Alpha 3 works though.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.22.2.

**Comment by Christywl** [comment]
close until there is more information.
