### ISSUE TITLE
Any way to trigger a click outside window?

### ISSUE THREAD

**Issue by thoughtspacewebsites** [nwjs/nw.js#3977]
Alright, so I'm looking to recreate something along the lines of click-through transparency. I followed this guideline for a little bit:

https://github.com/nwjs/nw.js/wiki/Transparency#click-through-transparency

The problem is that in order to enable click through transparency natively, I have to disable GPU rendering, which causes my app to appear pretty laggy. Unfortunately, I need to maintain GPU rendering for certain elements, and it appeared the only way to do that was to not disable it in the first place.

With this in mind, I created my own version of click through transparency with a few lines of jQuery. I have an OS X menu bar app, and I need to be able to hang things outside of my "window". You can see the app here:

http://mapleapp.info

I need to be able to have notifications hanging outside my app, which means I have to extend the width and height of my actual window beyond the visible "window" for my app. I then need the window to hide when you click off of it (like a menu bar app should). I can't use click-through transparency because of the laginess of software rendering. What I ended up doing is creating a larger transparent window, and then sizing my app to fit appropriately within the window (leaving window overhang on every side of the actual app). Then, I used this bit of jQuery:

```
 $("html").on('click', function(e){
     if(e.target.nodeName == "BODY" || e.target.nodeName == "HTML"){
         var gui = require('nw.gui');
         gui.Window.get('menuBarWindow').hide();
     }
 })
```

My html and body elements are styled in CSS with width:100%, height:100%. The jQuery above essentially catches every click, and if the click occurred on the HMTL or BODY element directly (outside of my app's inner "window"), then it hides the NWJS window. This lets me achieve my click off effect while still having transparent window overhang for things to hang outside of the apparent app window.

The problem is that the app currently behind the window is not focused, since I'm _technically_ still clicking on the window. If I could figure a way to "pass the click through" to the window behind my app, then it would work. Is there any way to focus another app's window using NWJS, or better yet, pass the click through to the app behind the NWJS app? 
##

**Comment by thoughtspacewebsites** [comment]
I solved my own issue, but I want to leave this here for anyone else that may have a similar experience in the future. 

My app is a Mac only app, so I ended up finding an OS X command line binary that enabled mouse control, aptly named MouseTools:

http://www.hamsoftengineering.com/codeSharing/MouseTools/MouseTools.html

MouseTools enables you to get and set mouse information (like getting the position or triggering a left / right click). It works on OS X >= v10.4.

I expanded on my above jQuery so that any time a click on the html element occurs, it hides the NWJS window and then immediately triggers a second click using a MouseTools command, which essentially focuses the window that's directly below my mouse. Here's the full code:

     $("html").on('mousedown', function(e){
	     if(e.target.nodeName == "BODY" || e.target.nodeName == "HTML"){
             //Hide the window
		     var gui = require('nw.gui');
		     gui.Window.get('menuBarWindow').hide();
		     //Trigger a mouse click to focus the window under the mouse
		     var exec = require('child_process').exec;
		     exec('./lib/MouseTools -leftClickNoRelease; ./lib/MouseTools -releaseMouse');
	     }
     });

This essentially simulates click through transparency for anything outside of my main app window, without having to disable GPU rendering. I get the best of both worlds with performance and functionality.

I really think something like this could be beneficial to the core of NWJS, and might be a more efficient way of enabling click through transparency than the current method of boot flags "--disable-gpu --force-cpu-draw", since it still allows the GPU to process animations. It could pretty easily be moved from jQuery to pure JS, and porting it would only require finding other binaries for linux / windows. Looks like a linux version can be found here:

http://tuxradar.com/content/xdotool-script-your-mouse

and it appears something similar can be achieved in Windows with WASP. Other than that, this isn't true click through transparency, but rather "click on body results in window hide, and the body just so happens to be transparent". Click through transparency could be achieved however by getting the color of the pixel below the mouse, and if it's transparent, running the above jQuery. This seems like a much more efficient method of disabling click-through transparency to me as it allows the GPU to stay enabled for graphic rendering. Does anybody else want to weigh in here and let me know if I'm missing something?

**Comment by ghostoy** [comment]
@thoughtspacewebsites Feel free to contribute your founds to the [wiki](https://github.com/nwjs/nw.js/wiki). It's open editing to everyone.

I also found some NPM modules that can play with mouse:

* https://www.npmjs.com/package/autorobo
* https://www.npmjs.com/package/macmouse
