### ISSUE TITLE
app.nw invoke outside .exe

### ISSUE THREAD

**Issue by joneqian** [nwjs/nw.js#3983]
my folder:
├── app.nw
└── bin
         └── run.exe

I want to invoke run.exe in app.nw, how do it?
when 'nw app.nw' , app.nw will been extracted to temp folder, so can't find run.exe!!

**Comment by rdtsc** [comment]
Assuming: 
- NW.js isn't globally installed;
- You don't want to pack `run.exe` and its dependencies in `app.nw`;
- `app.exe` lives alongside `nw.exe`...

... Then you can just sniff `process.execPath`:

```javascript
function runHelperProcess() {
  var path   = require('path'), 
      exec   = require('child_process').exec, 
      binary = path.join(path.dirname(process.execPath), '/run.exe');

  exec(binary);
}
```

```html
<button onclick="runHelperProcess()">Run Process</button>
```

**Comment by joneqian** [comment]
I will try it, thanks
