### ISSUE TITLE
Video play on ui.Screen.DesktopCaptureMonitor

### ISSUE THREAD

**Issue by panminghua** [nwjs/nw.js#3985]
Hi:
What is correct usage on ui.Screen.DesktopCaptureMonitor api? 
I capture a stream by ui.Screen.DesktopCaptureMonitor and play the stream at video dom element.It display like that:

![a](https://cloud.githubusercontent.com/assets/2967011/11298638/7bdc2050-8fbb-11e5-9396-33a81f502331.JPG)

What is wrong with me?

OS:Win 7
nw.js version:nwjs-v0.12.3
##

**Comment by panminghua** [comment]
Any advice？

**Comment by dlmwolf** [comment]
看你这个是个截图或者录屏的软件？你这个类似于无限循环，一个屏幕里的窗口包涵这个屏幕，则屏幕内会出现屏幕自身。并且无限个。如果你在另一屏幕打开窗口或者使用其他机器链接查看就不会有这个问题了。

**Comment by panminghua** [comment]
看到中文真亲切，问题我想做本地录屏，另一个机器就没有意义了。用官方的例子跑似乎也有这个问题，所以我怀疑要不是某些参数我没有配置好，要么就是一个bug。

**Comment by dlmwolf** [comment]
本地录屏你可以直接保存，然后打开保存的

**Comment by dlmwolf** [comment]
即时查看肯定会大屏套小屏

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it? 
And please use English in the issue.

**Comment by sourceskyboxer** [comment]
You mean [JsCapture](https://github.com/mgechev/jscapture#how-to-use)? Or I understand wrong?

**Comment by Christywl** [comment]
close until there is more information.
