### ISSUE TITLE
KeyboardEvent.location incorrectly set to 0 on keyup

### ISSUE THREAD

**Issue by SlugFiller** [nwjs/nw.js#3986]
Running the following JS code, and then pressing the right alt key:

``` js
window.addEventListener("keydown", function(e) {
  console.log("keydown", e.which, e.location);
});
window.addEventListener("keydown", function(e) {
  console.log("keyup", e.which, e.location);
});
```

The expected output is:

```
keydown 18 2
keyup 18 2
```

The received output is:

```
keydown 18 2
keyup 18 0
```
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.2.

**Comment by SlugFiller** [comment]
Can't seem to reproduce it now, either. This is from over a year ago, though, and a lot has changed about my set-up, including my keyboard and OS version. I do wish I had at least written the version of nwjs I used at the time, so I could confirm whether this was a version-specific issue or a host-specific issue. At least, it seems to work correctly on 0.12.3 for my current box.
