### ISSUE TITLE
[nwjs13 alpha5] How to debug like older versions

### ISSUE THREAD

**Issue by manhdn** [nwjs/nw.js#3988]
Hi,
I'm trying nwjs13 alpha5, when open it do not have "browser address bar" and do not have any option to open "Developer Tools" to check & debug application.

I also try set in package.json

{
  "window": {
    "toolbar": true
  }
}

but it still do not display toolbar. Can anyone help me about it?

Thank you!
##

**Comment by andresiraola** [comment]
The toolbar seems to be gone. You can open the devtools with F12 in the sdk build

**Comment by manhdn** [comment]
Thank you Andresiraola, I've open nw and try F12 but it happen nothing, no popup or dev tool display! don't know why, please help!

**Comment by andresiraola** [comment]
do you have a sdk build?

**Comment by manhdn** [comment]
Hi, what sdk build do you mean. 

I just download  v0.13.0-alpha5 (Windows: 32bit / 64bit) from http://dl.nwjs.io/v0.13.0-alpha5/nwjs-v0.13.0-alpha5-win-x64.zip, extract and run nw.exe file.

**Comment by manhdn** [comment]
Yes, I see what you mean now Andresiraola, do you mean SDK build version, I've found it in https://groups.google.com/forum/#!msg/nwjs-general/YuwMHd_uvPM/pLFWG3vYBwAJ, on downloading and will try it, before I download wrong version!
Thank you again !

**Comment by Christywl** [comment]
@manhdn , does the nwjs sdk build work for you? If so, let's close this issue.

**Comment by manhdn** [comment]
Yes @Christywl , Thank you very much!
