### ISSUE TITLE
require('Any path') throw error on winXP/win7

### ISSUE THREAD

**Issue by leecade** [nwjs/nw.js#3991]
only require(`module-name`) works.

**Comment by chaseWillden** [comment]
Does the file actually exist? Have you tested this on osx or Linux?

**Comment by leecade** [comment]
no just exist on winXP/win7

**Comment by chaseWillden** [comment]
Which version of nw.js are you using?

**Comment by leecade** [comment]
`0.12.3`

**Comment by chaseWillden** [comment]
Are you following the usage rules in the [documentation](https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-javascript-modules)?

**Comment by leecade** [comment]
> However, it is generally wise not to use the explicit relative paths (starting with ../ or ./) at all. Instead of it, just calling require('modulename') is enough — if the module has been put in the /node_modules subdirectory of your application. 

I see, thanks @chaseWillden I put the js file into node_modules and works fine.
