### ISSUE TITLE
[nwjs13] Any official document for nw.require, nw.Window or nw.App?

### ISSUE THREAD

**Issue by manhdn** [nwjs/nw.js#3993]
Hi,
When I try upgrade from nw 0.12.3 to nw 0.13.0-alpha5 it seem have a lot of changes in Api and cause errors and it require to search and fix issues like:

1) Uncaught ReferenceError: require is not defined  => and found that it now change to nw.require
2) nw.gui do not exists and found that now should use nw.Window
3) I try nw.Window with 
var win = nw.Window;
win.width=500;
win.height=500;
win.show();
And it have error Uncaught TypeError: win.show is not a function...
etc... and I don't know any more issues like this ahead.

So, can anyone show me the documents for the nw13 (api changes, objects, etc... so it can be using to refer when changing to new version)?

Thank you very much!

**Comment by namaljayathunga** [comment]
+1

**Comment by gleitz** [comment]
+1 Would be great to get at least a brief overview of breaking changes for 0.13

**Comment by rogerwang** [comment]
we are working on new official documentation, see https://groups.google.com/d/msg/nwjs-dev/it3C5KelBTc/TLIsgzIGCwAJ

**Comment by manhdn** [comment]
Great! thank you very much rogerwang!

**Comment by ghostoy** [comment]
@manhdn Our new documentation site is online now http://docs.nwjs.io/. I think you will find the answers to all your questions.
