### ISSUE TITLE
v0.13.0-alpha5: fullscreen/kiosk not working

### ISSUE THREAD

**Issue by namaljayathunga** [nwjs/nw.js#3995]
My project work well on v0.12.3. But that version not support to the html5 video full screen api. So I want develop it on the new alpha version. But now have a another problem, Alpha version not work 'kiosk' or 'fullscreen' mod. I added "kiosk": true in to the package.json. Instead of full screen it has small window.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.1. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
