### ISSUE TITLE
Clicking on desktop notification when hidden to tray won't reopen app on windows

### ISSUE THREAD

**Issue by ManuelOverdijk** [nwjs/nw.js#3998]
I'm encountering the following problem. When I spawn a new notification when the application is hidden to the tray (win.hide()), the notification will fire but clicking on it won't reopen/reshow the application. I only encounter this type of behaviour on Windows, and only if the application is hidden. So just minimalizing the application and clicking the application works just fine. 

Has anybode an elaborate guess or has encountered this before?

My code to minimize the application to the tray:

``` javascript

  win.on('close', ()=>{
                this._minimize(win, gui)
            });

_minimize(win, gui){
        // Hide window
        win.hide();

        // Show tray
        let tray = new gui.Tray({ title: title, icon: 'img/app.png' });

        tray.menu = menuTray;

        // Show window and remove tray when clicked
        tray.on('click', function() {
            win.show();
            this.remove();
            tray = null;
        });
    }
```

My onclick code

``` javascript
  notification.onclick = function(){
            var gui = require('nw.gui');
            var win = gui.Window.get();
            win.show();
            win.focus();
            notification.close();
        }.bind(this);
```
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full tests and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
