### ISSUE TITLE
mixing python and nw.js

### ISSUE THREAD

**Issue by hartsantler** [nwjs/nw.js#4003]
Has anybody tried compiling NW.js with CPython2?
I'm interested to know what is the recommend way to integrate NW.js with libpython, just the first compile and link steps.  I am not yet going for complete integration where python is wrapped and exposed to the js runtime.

**Comment by MaxMorais** [comment]
@hartsantler I made some tests using pypyjs.org and https://github.com/chromium/axiom

Nothing satisfactory!

**Comment by hartsantler** [comment]
PyPyJs is a joke, not even worth mentioning.

What i want to do is pretty simple, compile CPython into NW.js, statically linked or dynamically link to libpython2.7.so.  And after NW.js has loaded, call from C++:
```c++
	Py_Initialize();
	PyRun_SimpleString(cstr(std::string("result = 1+2")));
	auto mod = PyImport_AddModule(cstr(std::string("__main__")));
	auto mdict = PyModule_GetDict(mod);
	auto result = PyDict_GetItemString(mdict, cstr(std::string("result")));
	auto x = unbox(result);
	std::cout << x << std::endl;
	Py_Finalize();
```

**Comment by MaxMorais** [comment]
@hartsantler have a very old fork of webkit with Python, http://www.gnu.org/software/pythonwebkit/, maybe it can give a light to you!

**Comment by hartsantler** [comment]
I found what i was looking for:
* https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp
* https://github.com/nodejs/node-v0.x-archive/tree/master/test/addons/hello-world
