### ISSUE TITLE
Request sent through GET instead of POST

### ISSUE THREAD

**Issue by davidsupan** [nwjs/nw.js#4005]
I'm using **nwjs sdk v0.13.0 alpha7** (also applies to alpha6, does not even work in v0.12) on a Windows machine to directly open a https website, The problem arises when I need to log in and the credentials are passed to the server through *the GET method instead of the POST method*, even though the login (using POST) works properly in a standalone browser.
There is a similar issue, but it is still open: https://github.com/nwjs/nw.js/issues/3806, so I'm guessing it hasn't been addressed yet(?).
Is there a way to address this problem? Is this a nwjs or a Chromium issue?

nwjs:
![nwjs](https://cloud.githubusercontent.com/assets/8118541/11442347/df4a711a-9514-11e5-9207-8e6c8f78557f.JPG)

standalone:
![standalone](https://cloud.githubusercontent.com/assets/8118541/11442318/b3a48366-9514-11e5-9f96-b74e00e384bd.JPG)

**Comment by tymat** [comment]
Seeing this issue as well.

**Comment by rogerwang** [comment]
We fixed a similar issue. Could you please check again?

**Comment by rogerwang** [comment]
close for now since #3806 is now reported working.
