### ISSUE TITLE
0.13.0-alpha6 (sdk) language / l10n problem - MacOS

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4006]
I see the alpha6 of 0.13.0 (SDK with dev tools) does not support the Spanish & Italian langs. 
In the top menu I see other strings. 
For example I see "allow the app to know you position"(in italian) instead of string "Quit cmd+Q"... 
This problem is only on SDK version, symbol version is OK but only in English.

Is this a work in progress issue?
Thank you
##

**Comment by AndryBray** [comment]
same problem on alpha7

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
