### ISSUE TITLE
Can't find client libraries in windows but can find in Linux and OS X (v0.12.3)

### ISSUE THREAD

**Issue by tymat** [nwjs/nw.js#4012]
Scripts are loaded from index.html and running the OSX builds of nwjs works but windows build can't find various javascript libraries (moment.js)

Looks like it's time to move on to Electron.   This project has open 1,549 issues, platform inconsistencies, and no support from devs.  
##

**Comment by tymat** [comment]
Fixed this by doing global.moment

**Comment by Christywl** [comment]
@tymat , as you said, it worked for you, so could we close this issue now?

**Comment by Christywl** [comment]
close until there is more information.
