### ISSUE TITLE
nwjs 0.13 alpha MacOS crash

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4013]
Hello, I'm trying to upgrade to nwjs 0.13 but I see this new version is a disaster on MacOS (tested on 10.10.5)

Language file/string doesn't match with the english version. https://github.com/nwjs/nw.js/issues/4006
The app crash very often (in any case/site/app)
Reloading the page something with Window object will break https://github.com/nwjs/nw.js/issues/4007

I read the comment of @rogerwang https://groups.google.com/d/msg/nwjs-general/l-vc2U9mSsA/AwL0zb7QAwAJ [..] RC and final version will follow shortly because the current code quality is stable [...] 
IMO and based on my own experience, the new nwjs is not stable... more, I see a lot of tracked issues without answers and only commits from @rogerwang ... the public website incomplete... maybe this project is too big to be handled just by 1 person, do you agree?

I like nwjs but at this point, if the 0.13 doesn't work... I'm considering to move to some other project.
I hope I'm wrong and this is just caused from alpha stage.

Anyway congrats to @rogerwang for all what you have done.

**Comment by rogerwang** [comment]
Which version are you using? Someone reported crash issue shortly after alpha6 release which is fixed later in git (as mentioned in the thread you referred to). You could try the live build here: http://dl.nwjs.io/live-build/11-27-2015/91c3eee-cfca207-d224eab-31578cb

If that still doesn't work for you. Please re-open this issue and attach a case so we can reproduce it.

**Comment by AndryBray** [comment]
I can confirm https://github.com/nwjs/nw.js/issues/4006 and https://github.com/nwjs/nw.js/issues/4007 even on latest alpha-7 release.
