### ISSUE TITLE
nwjs 0.13 alpha7 crash on macos

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4014]
Just doing some web navigation the app will crash (MacOS 10.10.5)
https://gist.github.com/AndryBray/61cbd2072e3d581a913e

**Comment by rogerwang** [comment]
We can confirm there is crash on new window popup. It's now fixed in git in the chromium repo and will be available in live-build soon: http://buildbot-master.node-webkit.org:8010/waterfall

**Comment by chaseWillden** [comment]
I'm closing this issue since it's fixed in the next release.
