### ISSUE TITLE
nw.js rebuilt sqlite

### ISSUE THREAD

**Issue by waiting0729** [nwjs/nw.js#4016]
I rebuild sqlite for nw.js to use npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target=$(NODE_WEBKIT_VERSION),but I find generated node_modules/sqlites file is too big,I want to reduced this file,What could I do here?My nw.js version is nwjs-v0.12.3-win-ia32
Thanks in advance)))
##

**Comment by Aufree** [comment]
How big?

**Comment by ghostoy** [comment]
@waiting0729 Is the binary larger than the Node.js version?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
