### ISSUE TITLE
TLS1.2 not supported?

### ISSUE THREAD

**Issue by thoughtspacewebsites** [nwjs/nw.js#4017]
I have an app that makes AJAX requests to a server. The server is set up to only allow SSL over TLS v1.2. Unfortunately, these requests are failing from within my NWJS app. How can I get TLSv1.2 support in my app?
##

**Comment by flohdot** [comment]
+1

I am seeing the following errors when attempting to communicate with servers using TLS v1.2 only: 

```
[3412:0113/110429:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12188 (SSL_ERROR_INTERNAL_ERROR_ALERT) mapped to net::ERR_SSL_PROTOCOL_ERROR
```

**Comment by crash369** [comment]
Throwing in a "me too".
In the last 1+ month, something changed and I can no longer connect via SSL.  Result: net::ERR_SSL_PROTOCOL_ERROR.

Linux x64 - 3.16.0-38
NWjs 0.12.3

Updating to 0.13x fixes the issue, but this release is not compatible with my apps.

**Comment by matiu** [comment]
I think this could be related to https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1520568

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
