### ISSUE TITLE
Crash when accessing HTMLElement properties from node's vm module

### ISSUE THREAD

**Issue by rogual** [nwjs/nw.js#4018]
Here's a minimal example:

package.json:

```
{
    "name": "crash test",
    "main": "bug.html"
}
```

bug.html:

```
<script src='bug.js'></script>
```

bug.js:

```
window.onload = function() {
  var vm = require('vm');
  var c = vm.createContext({e: document.body});
  var script = 'e.style';
  vm.runInContext(script, c);
};
```
##

**Comment by chaseWillden** [comment]
I think you are forgetting the ```new``` keyword. 

```
var c = new vm.createContext({e: document.body});
```

See [Documentation](https://nodejs.org/api/vm.html#vm_script_runincontext_contextifiedsandbox_options)

**Comment by rogual** [comment]
I think that's a mistake in the docs — seems weird to require new there, and there's another sample on that page that doesn't have it.

Tried anyway, but it doesn't stop the crash.

**Comment by imyzf** [comment]
Modified code according to newest node.js doc, still crash.
```
var vm = require('vm');
var c = new vm.createContext({e: document.body});
var script = new vm.Script('e.style');
script.runInContext(c);
```

**Comment by rogerwang** [comment]
This is fixed in git and is available in the latest nightly build.
