### ISSUE TITLE
application responds slowly on windows

### ISSUE THREAD

**Issue by johnwonder** [nwjs/nw.js#4019]
hi,
when app running time is long,open it from Minimize to maximize it will responds slowly 

why is this happen?
##

**Comment by chaseWillden** [comment]
Just to clarify, if the app is "idle" or in use for a long time (how long usually?), if you maximize from the minimized state, the app responds slowly. How slowly? Do you have an example application?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
