### ISSUE TITLE
how to get schema url's parameters on osx

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4021]
The schema url : < a href='smsv://roomId:aaa&user:bbb'> 启动sms</a" >"

click it only run the nw,but the "nw.App.argv()"   return null;  

How to get the parameters form the url,like "roomId:aaa&user:bbb";

The nw version: v0.13.0-alpha6

System is Mac OS X 10.11.1
##

**Comment by Mithgol** [comment]
Please report your operating system's name (Linux, Mac, Windows?…) and version.

**Comment by zhenlovezhen2012** [comment]
Thanks,system is Mac OS X 10.11.1

**Comment by Christywl** [comment]
Please see the doc: http://docs.nwjs.io/en/latest/References/App/#appargv
And Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
