### ISSUE TITLE
gui.Window.get() in "node-main" file crahes NW.js

### ISSUE THREAD

**Issue by Klestofer** [nwjs/nw.js#4022]
Hello to all.
I've encountered something strange.

My `package.json` is

```
{
  "name": "name",
  "node-main": "script.js"
}
```

`script.js` is 

```
setTimeout(function() {
  var gui = window.require('nw.gui'); // 1
  var win = gui.Window.get();         // 2
 }, 1000)
```

After start, 'nw:blank' window is appearing, this is good, but after 1 second it is closed! The problem is in line 2. If we comment it out, the window is not closing.
`gui.Window.get(window);` behaves the same.
So NW.js crashes?

I'm using NW.js 0.12.3 with Windows10
##

**Comment by Klestofer** [comment]
I also discovered this:
We can comment out line 2 and start application. All is working good. Now we uncomment line and reload application without closing it, by pressing Reload button in the toolbar. In this case NW.js is not crushing. Line 2 returns Window object to `win` variable, and we can use it further. But if now we exit application and run it, keeping line uncommented, it crushes.

**Comment by Christywl** [comment]
It works fine in my test on Linux/Windows with nwjs-sdk-v0.22.2. No crash.
package.json:

```
{
  "name": "name",
  "main": "index.html",
  "node-main": "script.js"
}
```

Please try the latest nwjs build.

**Comment by Klestofer** [comment]
It was long ago, 1.5 years. It was probably fixed since then.
