### ISSUE TITLE
[NW13] Debugging incredibly slow

### ISSUE THREAD

**Issue by andresiraola** [nwjs/nw.js#4024]
Debugging in devtools in nwjs 13 alpha 7 (and also previous versions) is incredibly slow.

Executing a single line could take 5 seconds. Same for using the console to watch a variable's value.

Devtools doesn't block but every action takes a few moment. It seems like the response to a request to v8 is taking a lot of time to come back. In the console, if I enter a variable name and then hit enter, the value of the variable is not printed until 4 or 5 seconds later. In the meantime, I can continue to use the console but the response to any request is deferred some seconds.

**Comment by andresiraola** [comment]
I just compiled the last published version on git and the problem seems to be gone.

I'll keep you posted. I'm leaving this issue open for now.

**Comment by rogerwang** [comment]
Yes I just fixed it. Please reopen if it still exists.
