### ISSUE TITLE
要是能有个中文手册就好了，菜鸟看了太累

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#4031]
要是能有个中文手册就好了，菜鸟看了太累

**Comment by billyct** [comment]
wiki 上不是好像就有的么，[http://www.cnblogs.com/xuanhun/category/568577.html](http://www.cnblogs.com/xuanhun/category/568577.html)

**Comment by waiting0729** [comment]
不全

**Comment by billyct** [comment]
自己去翻译个全的😄

**Comment by Gtskk** [comment]
[相对蛮全的教程](http://www.cnblogs.com/2050/p/3543011.html)

这个写的还蛮全，从0到有:smile:
