### ISSUE TITLE
unsealed contents present in the bundle root

### ISSUE THREAD

**Issue by dibeesh** [nwjs/nw.js#4032]
Hi, 
Am trying to signing my app build with nwjs in Mac. https://github.com/nwjs/nw.js/wiki/MAS:-Signing-the-app

Following are the steps i tried. Out of 8 steps upto 7 worked for me. When i run the 8th command am getting "unsealed contents present in the bundle root" error message.
1. export IDENTITY= "*******" 
2. export PARENT_PLIST=/path/to/parent.plist
3. export CHILD_PLIST=/path/to/child.plist
4. export APP_PATH=/path/to/yourapp/YourApp.app
5. codesign --deep -s $IDENTITY --entitlements $CHILD_PLIST $APP_PATH"/Contents/Frameworks/nwjs Helper.app"
6. codesign --deep -s $IDENTITY --entitlements $CHILD_PLIST $APP_PATH"/Contents/Frameworks/nwjs Helper EH.app"
7. codesign --deep -s $IDENTITY --entitlements $CHILD_PLIST $APP_PATH"/Contents/Frameworks/nwjs Helper NP.app"
8. codesign --deep -s $IDENTITY --entitlements $PARENT_PLIST $APP_PATH 

Please see the screen shot for my file structure

![screen shot 2015-12-03 at 6 37 11 pm](https://cloud.githubusercontent.com/assets/8565773/11561570/4e870e7a-99ee-11e5-9cb5-69121ac9ef13.png)

I can see some hidden files and Icon? folder in app directory. If i remove them the signin command works, but the app rejected. Should the hidden files needed for build? 
![screen shot 2015-12-04 at 2 30 23 pm](https://cloud.githubusercontent.com/assets/8565773/11585724/100a2e6a-9a94-11e5-88a3-88396df39a22.png)
##

My info.plist file 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>BuildMachineOSBuild</key>
        <string>14B25</string>
        <key>CFBundleDevelopmentRegion</key>
        <string>en</string>
        <key>CFBundleDisplayName</key>
        <string>OutboxPro</string>
        <key>CFBundleDocumentTypes</key>
        <array>
            <dict>
                <key>CFBundleTypeIconFile</key>
                <string>nw.icns</string>
                <key>CFBundleTypeName</key>
                <string>node-webkit App</string>
                <key>CFBundleTypeRole</key>
                <string>Viewer</string>
                <key>LSHandlerRank</key>
                <string>Owner</string>
                <key>LSItemContentTypes</key>
                <array>
                    <string>com.intel.nw.app</string>
                </array>
            </dict>
            <dict>
                <key>CFBundleTypeName</key>
                <string>Folder</string>
                <key>CFBundleTypeOSTypes</key>
                <array>
                    <string>fold</string>
                </array>
                <key>CFBundleTypeRole</key>
                <string>Viewer</string>
                <key>LSHandlerRank</key>
                <string>None</string>
            </dict>
        </array>
        <key>CFBundleExecutable</key>
        <string>node-webkit</string>
        <key>CFBundleIconFile</key>
        <string>nw.icns</string>
        <key>CFBundleIdentifier</key>
        <string>com.unifiedinbox.outboxpro</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>OutboxPro</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>21</string>
        <key>CFBundleVersion</key>
        <string>21</string>
        <key>DTSDKBuild</key>
        <string>13F26</string>
        <key>DTSDKName</key>
        <string>macosx10.9</string>
        <key>DTXcode</key>
        <string>0611</string>
        <key>DTXcodeBuild</key>
        <string>6A2008a</string>
        <key>LSFileQuarantineEnabled</key>
        <true/>
        <key>LSMinimumSystemVersion</key>
        <string>10.6.0</string>
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
        <key>NSSupportsAutomaticGraphicsSwitching</key>
        <true/>
        <key>SCMRevision</key>
        <string>290379</string>
        <key>LSApplicationCategoryType</key>
        <string>public.app-category.entertainment</string>
        <key>UTExportedTypeDeclarations</key>
        <array>
            <dict>
                <key>UTTypeConformsTo</key>
                <array>
                    <string>com.pkware.zip-archive</string>
                </array>
                <key>UTTypeDescription</key>
                <string>node-webkit App</string>
                <key>UTTypeIconFile</key>
                <string>nw.icns</string>
                <key>UTTypeIdentifier</key>
                <string>com.intel.nw.app</string>
                <key>UTTypeReferenceURL</key>
                <string>https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps</string>
                <key>UTTypeTagSpecification</key>
                <dict>
                    <key>com.apple.ostype</key>
                    <string>node-webkit</string>
                    <key>public.filename-extension</key>
                    <array>
                        <string>nw</string>
                    </array>
                    <key>public.mime-type</key>
                    <string>application/x-node-webkit-app</string>
                </dict>
            </dict>
        </array>
    </dict>
</plist>
##

**Comment by swati-srivastava** [comment]
were u able to sign it properly, ma having same issue
