### ISSUE TITLE
can not read property of log

### ISSUE THREAD

**Issue by johnwonder** [nwjs/nw.js#4034]
i write  global.console.log  , but it throw a error like  'can not read property of log'
##

**Comment by karlrwjohnson** [comment]
Could you include the entire error message? Platform, version, and example code?

This might be a case where "console" is not a defined property on global. (I don't know what's supposed to be there normally; It's hard keeping track of what the "global" object is in different contexts.) Maybe "global" is some other object. Then again, maybe you misspelled "console" in the code.

Either way, JS evaluates anObject.nonExistantProperty to undefined. If you try to access a sub-property off of that, e.g. anObject.nonExistantProperty.someOtherProperty, *then* it throws an error.

This commonly manifests in an error such as, "undefined is not a function".

IMO, it's a weakness of JS that errors aren't thrown for nonexistent properties. But it is what it is.

**Comment by Christywl** [comment]
I can't reproduce this on Linux with nwjs-sdk-v0.22.2. Please try the latest nwjs build.
` global.console.log("This is a test");`

**Comment by Christywl** [comment]
close until there is more information.
