### ISSUE TITLE
how can i build nw source in osx-10.11.1 with xcode-7.1.1

### ISSUE THREAD

**Issue by billyct** [nwjs/nw.js#4035]
how can i build nw source in osx-10.11.1 with xcode-7.1.1?
i followed [https://github.com/nwjs/nw.js/wiki/Building-nw.js](https://github.com/nwjs/nw.js/wiki/Building-nw.js)

but it's said ```Mac OS X - Use ninja as described bellow, XCode will die building node-webkit :(.```

i  tried with ```ninja -C out/Release nw -j4```  and it really broken

so ,how can i build nw source?

**Comment by jtg-gg** [comment]
you can copy older SDK from older version of Xcode
and copy it to the framework folder of xcode-7.1.1 (search for exact path)

after that, re-run the gyp-chromium (if not, ninja will still try to use the 10.11.1 sdk) basically the sdk "linking" is done by gyp-chromium.

for nw13 you'll need osx 10.10
for nw12, I prefer 10.8, but it also works with 10.9, never test it with 10.10

**Comment by billyct** [comment]
@jtg-gg it's worked with 10.9,thx
