### ISSUE TITLE
gui.Window.open() opens 2 windows instead of 1 in "node-main" script

### ISSUE THREAD

**Issue by Klestofer** [nwjs/nw.js#4036]
Another strange thing:

`package.json` is

```
{
  "name": "name",
  "node-main": "script.js"
}
```

`script.js` is 

```
setTimeout(function() {
  console.log('start');
  var gui = window.require('nw.gui');
  var win = gui.Window.open('https://google.com');
}, 1000)

```

Application starts and opens 2(!!!) Google windows. 'start' is printed only once in console. If we reload application without closing, it opens Google once, like it should be.

This bug may be connected to [another one](https://github.com/nwjs/nw.js/issues/4022).
Having "node-main" script is a great idea, but it seems unusable now.
##

**Comment by Christywl** [comment]
It works fine in my test on Linux/Windows with nwjs-sdk-v0.22.2. Only one Google window opens.
package.json:
```
{
  "name": "name",
  "main": "index.html",
  "node-main": "script.js"
}
```
script.js:
```
setTimeout(function() {
  console.log('start');
  var gui = window.require('nw.gui');
  var win = gui.Window.open('https://google.com');
}, 1000)
```

**Comment by Klestofer** [comment]
It was long ago, 1.5 years. It was probably fixed since then.
