### ISSUE TITLE
Remote Debugging Detached From The Target

### ISSUE THREAD

**Issue by Daemondeal** [nwjs/nw.js#4040]
<img src="http://i.imgur.com/CAqYZRx.png" alt="Remote debugging has been terminated with reason: websocket_closed">
I get this issue every time I open nw.js Dev Tools, on every project, even if it's blank.
The project works fine, but not Dev Tools.
I'm using 0.12.
##

**Comment by pioneer32** [comment]
+1
I face it too, so i have to reload the page every time.
I use Node Inspector v0.12.7 and Chrome 51.0.2673.0 canary (64-bit)

**Comment by Christywl** [comment]
Dev Tools works well for me on Linux/Windows nwjs-sdk-v0.22.2. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
