### ISSUE TITLE
list of API changes for 13 available?

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#4044]
I know the version 13 is still in alpha, but from what I understand there are some changes to the API, like menu generation and the like.

Is there already a complete list of what did change from 12 to 13?

**Comment by ghostoy** [comment]
https://github.com/nwjs/nw.js/wiki/NW.js-0.13.0-Migration-Notes

chino23 <notifications@github.com>于2015年12月7日周一 17:24写道：

**Comment by chino23** [comment]
thanks! missed that.
