### ISSUE TITLE
nwjs任务栏关闭问题

### ISSUE THREAD

**Issue by waiting0729** [nwjs/nw.js#4045]
在nwjs里面需要监听到任务栏关闭事件  可以阻止任务栏关闭，请问大家有什么好的方法吗
##

**Comment by iwege** [comment]
是强制杀死么？如果强制杀死没有办法解决的。
如果是正常关闭，可以考虑监听close事件。

**Comment by Christywl** [comment]
Please use English so all users can read, or the issue will be closed directly.

**Comment by jan4984** [comment]
应用程序基本不可能阻止操作系统强行关闭，除非用一些病毒技术。

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
