### ISSUE TITLE
Crash in node-webkit 0.12.3 win32

### ISSUE THREAD

**Issue by 7demo** [nwjs/nw.js#4047]
My app is  easy, the main file(index.html) just has a piece of js -----  'window.location.href=''http://.......', of course , the website  is complicated.

However, it wil crash sometime width no regular.  The error dump  is : 
# 
# 

Microsoft (R) Windows Debugger Version 6.12.0002.633 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Users\Administrator\Desktop\943e11d1-0ae4-4035-bf21-f311ebb7602e.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: **\* Invalid ***

---
- Symbol loading may be unreliable without a symbol search path.           *
- Use .symfix to have the debugger choose a symbol path.                   *
- After setting your symbol path, use .reload to refresh symbol locations. *
  ****************************************************************************
  Executable search path is: 
  Windows 7 Version 7601 (Service Pack 1) MP (4 procs) Free x86 compatible
  Product: WinNt, suite: SingleUserTS
  Machine Name:
  Debug session time: Tue Dec  8 09:41:16.000 2015 (UTC + 8:00)
  System Uptime: not available
  Process Uptime: 0 days 0:01:48.000
  ................................................................
  ........................................
  Loading unloaded module list
  ...............
  This dump file has an exception of interest stored in it.
  The stored exception information can be accessed via .ecxr.
  (4088.2ed8): Access violation - code c0000005 (first/second chance not available)
  eax=00000000 ebx=00000000 ecx=079cf9c8 edx=034f002e esi=00000110 edi=00000000
  eip=7720f911 esp=001dee20 ebp=001dee8c iopl=0         nv up ei pl zr na pe nc
  cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
  **\* ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
  ntdll!ZwWaitForSingleObject+0x15:
  7720f911 83c404          add     esp,4
  0:000> 
# 
# 

Who can give me some tips?
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.2.
`window.location.href = "https://nwjs.io/";`

Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
