### ISSUE TITLE
I can't find any ffmpegsumo files in Chrome Version 47.0.x

### ISSUE THREAD

**Issue by Aufree** [nwjs/nw.js#4050]
![image](https://cloud.githubusercontent.com/assets/5310542/11688192/0e4dcaba-9ec6-11e5-9e86-475d24d6aacf.png)

![image](https://cloud.githubusercontent.com/assets/5310542/11688158/e3d5cd8c-9ec5-11e5-8b57-d5a1a365c39e.png)

**Comment by mscreenie** [comment]
Also see https://github.com/nwjs/nw.js/issues/3967#issuecomment-158148085

**Comment by rogerwang** [comment]
merge with #3967
