### ISSUE TITLE
nw13 API changes confusion

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#4055]
nw13 alpha7, Mac OS X 10.10

Hi,

I've got a question about the changes in API for the nw13 alpha.

Looking at https://github.com/nwjs/nw.js/wiki/NW.js-0.13.0-Migration-Notes it says 
````
require('nw.gui') does NOT exist. Instead, you can directly access NW.js API via nw.*.
````

But there are a few issues where this still works

1) using the nwjc compiled bin files, can still do
````
require('nw.gui').Window.get().evalNWBin(null, 'snapshot.bin');
````
or
````
nw.Window.get().evalNWBin(null, 'snapshot.bin');
````

2) getting the window object

Still works:
````
var win = require('nw.gui').Window.get();
````
as well as
````
nw.Window.get();
````

3) loading files with require

It said: Global Node.js objects, such as require, process, Buffer etc., do NOT exist. All Node.js objects are now loaded in nw.*. Just use nw.require('http') to require Node.js modules.

I can still do
````
var _ = require('lodash')
````
same as 
````
var _ = nw.require('lodash')
````

Is this a shim or why is this still working when it's stated it doesn't exist anymore?

**Comment by mscreenie** [comment]
I noticed this aswell. I think @rogerwang will or is cleaning up the API and I personally don't mind if there is breakage between 12 and 13. If it means better logic in naming than so be it.

**Comment by rogerwang** [comment]
We added a shim for backward compatibility. The document was written earlier.

**Comment by chino23** [comment]
thanks for clearing that up @rogerwang. So is the shim going to stay? or is this planned to be dropped at some point?

**Comment by rogerwang** [comment]
Yeah. It's going to stay for quite some time. At first it will be enabled by default (and disabled by a switch); later it will be disabled by default and enabled with a switch.
