### ISSUE TITLE
nw13 win.on(close) not working correctly

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#4057]
Mac OS X 10.10.

A window can be closed by 3 things:
1) Menu -> quit
2) red x button clicked 
3) Dock right mouse button -> quit

nw12.x : no problem.

nw13 alpha7: 

only number 2 is caught using:

````
var win = nw.Window.get();
win.on('close', function() {
    ....
````

So when I close the app using the menu or from the dock, the on('close) doens't fire.

**Comment by rogerwang** [comment]
Thanks for reporting. This is now fixed in git and will be available in today's nightly build.

**Comment by chino23** [comment]
Thanks a lot, working in git!
