### ISSUE TITLE
compile from source on windows 7

### ISSUE THREAD

**Issue by deostroll** [nwjs/nw.js#4058]
Looking for some info on how to compile this project for windows 7. I couldn't find it in the readme.

**Comment by dkfiresky** [comment]
![screen shot 2015-12-10 at 2 22 55 pm](https://cloud.githubusercontent.com/assets/2175645/11715311/90e58606-9f49-11e5-9832-f8d9451ab7c1.png)

**Comment by mscreenie** [comment]
Lol.

**Comment by chaseWillden** [comment]
Amen to the meme above.

See: https://github.com/nwjs/nw.js/wiki/Building-nw.js
