### ISSUE TITLE
JS redirecting breaks functionality

### ISSUE THREAD

**Issue by Erveon** [nwjs/nw.js#4059]
Hey,

(Please note, I have not worked with nw js or node for very long)

After a redirect, a lot of things break for me.
Lots of investigating later, my conclusion is that elements are not the same after a redirect.
(Using the jQuery node module)

When the first page is loaded by nw js,

``` javascript
console.log($('#main'));
```

shows

``` javascript
jQuery.fn.init[1]
   0: main#main
   context: document
   length: 1
   selector: "#main"
   __proto__: jQuery[0]
```

Which is the intended functionality.
After a page is redirected (using both jQuery, and vanilla JavaScript)
The same exact code will output

``` javascript
[main#main, context: document, selector: "#main", jquery: "2.1.4", constructor: function, toArray: function…]
   0: main#main
   context: document
   length: 1
   selector: "#main"
   __proto__: jQuery[0]
```

This seems to break any jQuery selectors and events.
Is this a nw js issue or something I could fix myself?

EDIT:

Same issue even when using

``` javascript
var gui = require('nw.gui');
var win = gui.Window.get();
win.on('loaded', function() { });
```

or

``` javascript
$(document).ready(function() { });
```
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full tests to reproduce it?
Btw, I try the following code on Linux with nwjs-sdk-v0.22.1. It works well.
```
var gui = require('nw.gui');
var win = gui.Window.get();
win.on('loaded', function() { });
```

**Comment by Christywl** [comment]
close until there is more information.
