### ISSUE TITLE
nw.js browser showing Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Rzeiwald** [nwjs/nw.js#4061]
trying to run my exe using nw.js browser.I downloaded nw.js from this link https://github.com/nwjs/nw.jsThen I created package.jason file like this
{
 "name": "sample",
 "version": "1.0.0",
 "description": "",
 "main": "index.html",
 "window": {
 "toolbar": false,
"frame": false,
"resizable": false,
"show": true,
"kiosk": true,
"title": "kiosk example"
 },
"webkit": {
"plugin": true
  },
  "chromium-args": "--ppapi-flash-path=plugins/libpepflashplayer.so --ppapi-flash-version=17.0.0.134",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "rohan",
"license": "ISC",
"dependencies": {
"express": "^4.13.3",
"gulp": "^3.9.0",
"nw-flash-trust": "^0.3.0"
}
}
and my index.html is like this

       <html>
       <head>

       <script>  

       function RunExe()   
     {   

       var child_process = require('child_process')
      , exec = child_process.exec
      , execSync = child_process.execSync
      , execFile = child_process.execFile
       , execFileSync = child_process.execFileSync
       ;

       exec('quiz.exe');

        } 

      </script> 
     </head> 
     <body> 
     <h1>Run a Program</h1> 
     This script launch the file any Exe File<p> 
     <button onclick="RunExe()">Run Exe File</button> 
     </body> 
     </html> 
I placed my quiz.exe in same folder where nw.exe is present but when my index.html page loads and i click on run exe file button nothing happens,I checked console and it is showing this error message "Uncaught ReferenceError: require is not defined" please help!.

**Comment by aestrada7** [comment]
What version of nw.js do you have? it should be v0.13 alpha 7. 

Also, why don't you use nw.js's API for this? specifically the Shell API, something like this:

```
    var path = require('path');
    var pathDir = path.dirname(process.execPath);
    gui.Shell.openItem(path.join(pathDir, 'quiz.exe'));
```

The execPath is where nw.exe is, so if it's a packaged application, it should be on the same level, if you're actively working on it and debugging, it probably is under node_modules/nw, and that's where quiz.exe should reside

Good luck!

**Comment by zhenlovezhen2012** [comment]
should use 'nw.require' instead of 'require' in nw.js v0.13

**Comment by Rzeiwald** [comment]
it works on clean nw.js v0.12.3 32bit.mine was 64bit
