### ISSUE TITLE
nw.exe and packaging file size, slow extracting

### ISSUE THREAD

**Issue by Varooneh** [nwjs/nw.js#4062]
hi, i'm not sure is an issue or not, but I've problem with nw packaging and i thing is important for my customer. I read all issue's about packaging but can not solve it.

1- we created an node webkit desktop app work with mysql as database, total project size is ~20MB .
2- when we want create release pack, last total project with nw is ~60MB, we zipped project and rename to projectname.nw and create exe with this command : https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#step-2b-alternative-way---making-an-executable-file-out-of-a-nw-file .
3- package run successfully but it's very very slow to start . 

please help us, how to reduce start time?

sorry for bad english and if i write wrong place.

**Comment by ghostoy** [comment]
NW has to extract files to disk at start. I recommand not to use zip if you
care about starting speed.

Varooneh <notifications@github.com>于2015年12月11日周五 23:38写道：

**Comment by Varooneh** [comment]
@ghostoy 
a way for this problem : 
1- i created a project folder
2- root of this folder contains project file and RTL (run time library contains nw requirement) folder 
3- copy package.json to rtl folder and change index.html path
4- run nw.exe
with this way not need to zip or extract with nw and work fine for me .

**Comment by ghostoy** [comment]
So non-zip workarounds the issue, right? I'm closing this issue. You can reopen it if you see different.
