### ISSUE TITLE
Some of my users can't launch NW.js apps

### ISSUE THREAD

**Issue by Baccanno** [nwjs/nw.js#4064]
Hi,

I'm one of the creator of the game Synchrom,

Although there was always some launch issues on some Linux and Mac OS machines up to date windows machine launched the game pretty easily.

Since Windows 10 arrived I have some users reporting that the application is not launching at all. I thought it was an issue with the Steam client where the game is distributed however even when providing them an independent build it won't launch.

What should I ask them to do in order to have a clue on their issue ?

Thanks

NW.js 12.3
Greenworks 0.4.1
##

**Comment by ghostoy** [comment]
You can monitor the exit code of NW to see if it's exited normally.

**Comment by Baccanno** [comment]
I will ask for this. Meanwhile I asked them to launch the 0.13-beta1 and it
seemed to work.

2015-12-31 17:41 GMT+01:00 Cong Liu <notifications@github.com>:

> You can monitor the exit code of NW to see if it's exited normally.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nwjs/nw.js/issues/4064#issuecomment-168218798>.
>



-- 
Michaël Picovschi, Morphiks
http://www.morphiks.com

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
