### ISSUE TITLE
nw13 {show: false} instantly crashes

### ISSUE THREAD

**Issue by brian-mann** [nwjs/nw.js#4070]
Setting `{"window": {"show": false}}` in `package.json` instantly crashes nw13alpha7.

**Comment by brian-mann** [comment]
Also, calling `nw.Window.get().hide()` will also cause instantly kill the running process.

**Comment by rogerwang** [comment]
upstream doesn't allow Chrome running with hidden windows: https://code.google.com/p/chromium/issues/detail?id=450710

Will fix this soon.

**Comment by rogerwang** [comment]
fixed in git.

**Comment by brian-mann** [comment]
So this will be fixed in alpha8? What is the ETA on that release?

**Comment by brian-mann** [comment]
What do you mean fixed in git?

**Comment by rogerwang** [comment]
@brian-mann the fix is in the master patch of chromium repo.
