### ISSUE TITLE
nw13 no self extraction?

### ISSUE THREAD

**Issue by andresiraola** [nwjs/nw.js#4071]
I packed nw13 using my modified version of nw-builder (to support nw13 packing) and I noticed that self extraction wasn't working so I added at the very beginning of Package::Package() (inspired by nw12) this:

```c++
  base::FilePath path = GetSelfPath();

  // First try to extract self.
  if (InitFromPath(path))
    return;  
```

and now it self extracts. Perhaps you can include this in future nw13 builds. It is a quick change.

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.
