### ISSUE TITLE
Removing nwjs app not clearing indexeddb data(windows)

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#4075]
I'm using a client side database(pouchdb, wrapper for indexeddb) for an offline app with nwjs; upon removal of the app the data somehow persists.. where is this data stored? how can I manage it explicitly?
##

**Comment by ghostoy** [comment]
See http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-data-path

**Comment by ohenepee** [comment]
The data seems to be somehow stored in PREFETCH FOLDER (on Windows XP, my test platform) and I don't know how to set data-path in MANIFEST

**Comment by ohenepee** [comment]
The data seems to be somehow stored in PREFETCH FOLDER (on Windows XP, my test platform) and I don't know how to set data-path in MANIFEST

**Comment by ghostoy** [comment]
It's changed to `--user-data-dir` http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir

**Comment by Christywl** [comment]
@ohenepee , does ghostoy's advise work for you?

**Comment by Christywl** [comment]
close until there is more information.
