### ISSUE TITLE
nw13: Escape key exits fullscreen mode

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#4076]
Pressing the escape key exits fullscreen mode in 0.13.x, whereas in previous versions it did not (the exitFullscreen method would have to be used instead).

First reported here: https://www.scirra.com/forum/r218-nw-0-13-a7-pressing-escape-quit-fullscreen-mode_t165072

**Comment by rogerwang** [comment]
This is fixed in git and will be released in the next nightly build.
