### ISSUE TITLE
nw13: <input type="file" nwdirectory> not supported

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#4077]
The nwdirectory attribute on a file input used to bring up a folder picker. This does not appear to be supported in nw13 and it falls back to opening a normal "open file" dialog.

First reported here: https://www.scirra.com/forum/r218-amp-nw-js-0-13-alpha-6-show-folder-dialog-doesn-t-work_t165015

**Comment by rogerwang** [comment]
it's now fixed in the last nightly build: http://dl.nwjs.io/live-build/12-17-2015/de349e4-f881d56-1f75962-18afa85/
