### ISSUE TITLE
what method is there can listen to the operating system of the keyboard or mouse event

### ISSUE THREAD

**Issue by fuwenchun** [nwjs/nw.js#4079]
what method is there can listen to the operating system of the keyboard or mouse event, I would like to achieve a function that keyboard and mouse 5 minutes without action to automatically executive a function

**Comment by ghostoy** [comment]
You can register system wide shortcut with App.registerGlobalHotkey. But doesn't have one for mouse.

**Comment by ghostoy** [comment]
You can ask further questions on [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter IM](https://gitter.im/nwjs/nw.js). So I'm closing this issue.
