### ISSUE TITLE
v0.13-alpha7 (sdk) Window.open fails with position property passed (OSX)

### ISSUE THREAD

**Issue by fedot** [nwjs/nw.js#4081]
Passing *position* property to `Window.open` options fails with `Error: Invalid value for argument 2. Property 'position': Unexpected property.`
```javascript
var win = nw.Window.open ('https://github.com/nwjs/nw.js', {
  position: 'center',
  width: 901,
  height: 127
});
```

**Comment by fedot** [comment]
Looks like `position` property specified in manifest (package.json) for window doesn't work as well

**Comment by rogerwang** [comment]
Thanks for reporting. This is now fixed in git and will be available in next nightly build.
