### ISSUE TITLE
v0.13-alpha7 (sdk) Window.open doesn't return a window (OSX)

### ISSUE THREAD

**Issue by fedot** [nwjs/nw.js#4082]
Calling `Window.open` doesn't return any result, using next code results in `TypeError: Cannot read property 'on' of undefined`

```javascript
var win = nw.Window.open ('https://github.com/nwjs/nw.js', {
  width: 901,
  height: 127
});

win.on ('loaded', function(){
  // the native onload event has just occurred
  var document = win.window.document;
}); // -> TypeError: Cannot read property 'on' of undefined
```

BTW, DevTools console also have next error message printed while opening any external resource:
`Error in response to app.window.create: TypeError: Cannot read property 'initializeAppWindow' of undefined` with pointer to the line with `Window.open` call

**Comment by fedot** [comment]
After a bit of play I was able to get the the opened window via undocumented callback function passed as third parameter to `Window.open` and using relative URL to local file like this:

```javascript
nw.Window.open('dummy.html', {}, function(win){
  win.on ('loaded', function(){
    // the native onload event has just occurred
    var document = win.window.document;
  });
})
```
Passing external URL does result in opened window but `loaded` event not triggered.

**Comment by rogerwang** [comment]
Yes. It's changed to callback in 0.13. We're working on the documentation and it will be published with beta.

Will see the external URL issue.

**Comment by tiitremmel** [comment]
There's still bug. I rannw.Window.open('http://github.com', {}, function(win){
  console.log('cb',win);
  win.on ('loaded', function(){
    console.log('loaded');
  });
})*

**Comment by tiitremmel** [comment]
There's still bug.
I ran
```javascript
nw.Window.open('http://github.com', {}, function(win){
    console.log('cb',win);
    win.on ('loaded', function(){
        console.log('loaded');
    });
});
```
As result i got only error without console.log callbacks.
```
Error in response to app.window.create: TypeError: Cannot read property 'initializeAppWindow' of undefined
```
![Image of Error]
(https://photos-5.dropbox.com/t/2/AADOrUSsXh5AWdQCK3hWDd7RFieiDg7tXepVz6tc184xqQ/12/58525510/png/32x32/3/1450447200/0/2/Screen%20Shot%202015-12-18%20at%2011.48.50.png/EPCdnC0Yo98nIAEgAigB/CF-nfm_oiiewhNwtCnLtTMUpOyoB6ebox_QyC3C6_U4?size_mode=3&size=2048x1536)
Tested with http://dl.nwjs.io/live-build/12-18-2015/5151bab-bf9dca3-1f75962-18afa85/v0.13.0-alpha8/nwjs-sdk-v0.13.0-alpha8-osx-x64.zip

**Comment by rogerwang** [comment]
Thanks for reporting. The external URL case is now fixed and available in nightly build.

**Comment by dvlsg** [comment]
I am still having intermittent issues with this and external URLs. Seems to happen about 40% of the time, and adding fake delays with setTimeout() inside the `nw.Window.open()` callback tends to circumvent the issue.

I'm currently on Windows 8 x64, and using the nwjs-sdk-v0.15.0-beta2-win-x64 files from the [04-28-2016 nightly build](http://dl.nwjs.io/live-build/04-28-2016/nw15-d55bd1f-4e44b9d-142e835-a4e5a41/v0.15.0-beta2/).

Code required to reproduce on my computer:

    <!DOCTYPE html>
    <html>
    <head>
      <title>nw.Window.open() Undefined Example</title>
    </head>
    <script>

    var win = nw.Window.get();
    win.showDevTools();

    nw.Window.open('https://github.com', {}, function(new_win) {
      if (new_win === undefined)
        console.log('new_win was undefined!');
      else
        console.log('new_win was defined:', new_win);
    });

    </script>  
    </body>
    </html>

Screencap of bug in action:

![nwjs-bug-external-url](https://cloud.githubusercontent.com/assets/4721566/14894232/7cabe346-0d27-11e6-9cd2-2a1552903a0e.gif)
