### ISSUE TITLE
[nw13] console in Node context doesn't output to DevTools

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#4084]
I can't see the output of `console.log()` in Devtools.

See https://gist.github.com/ghostoy/789092f37bc3bb5989d1

**Comment by ags131** [comment]
placing 
`global.console.log = (...args)=>window.console.log(...args);`
at the top of my main JS file worked as a workaround for me.

**Comment by ghostoy** [comment]
@ags131 Yes, but NW should provide it by default to compatible with older versions.

**Comment by rogerwang** [comment]
Node's context is now the DOM context of the background page. If you inspect the background page you can see the log there. It's logged to the console in Linux or OSX as well.
