### ISSUE TITLE
Saving files is not enabled in hosted mode

### ISSUE THREAD

**Issue by zhengyongrui** [nwjs/nw.js#4085]
Saving files is not enabled in hosted mode. Please inspect using chrome://inspect
Why Can't Save har?
##

**Comment by ghostoy** [comment]
Could you show the steps how to get this error?

**Comment by ghostoy** [comment]
@zhengyongrui Could you show the steps how to get this error?

**Comment by lcb931023** [comment]
+1.

This happens when I try to save a Timeline record data in the devtool.

**Comment by GeneGenie** [comment]
+1

**Comment by ghostoy** [comment]
@lcb931023 Could you also provide the NW.js version and OS?

**Comment by lcb931023** [comment]
The bug appeared on 0.12.3 on Windows 64-bit. Good to hear it's fixed on the newer versions :)

**Comment by ghostoy** [comment]
Yes, it's fixed in 0.13 or later.

Changbai Li <notifications@github.com>于2016年7月23日周六 02:39写道：

**Comment by Christywl** [comment]
@zhengyongrui , is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
