### ISSUE TITLE
Linux HiDPI?

### ISSUE THREAD

**Issue by cydrobolt** [nwjs/nw.js#4087]
I attempted to run an app running nw.js version 0.12.2 on my Linux laptop (3200x1800), which has a 13" laptop screen.

The text appeared tiny and did not scale like the rest of my GTK apps (I run GNOME 3.18.2), such as HexChat or Google Chrome (which has HiDPI support).

Was this never fixed or is this a regression? Looking through the issues, I saw some tickets that seemed to indicate HiDPI was being addressed. Perhaps not on Linux?

**Comment by ghostoy** [comment]
Could you try latest nw13 alpha to see if it's working?

Chaoyi Zha <notifications@github.com>于2015年12月21日周一 08:33写道：

**Comment by cydrobolt** [comment]
Ah, let me try that.

**Comment by cydrobolt** [comment]
@ghostroy I tried packing it with 0.12.3, but no luck there.
I couldn't get the app to build correctly with 0.13.0-alpha7.

Looking at some of the console output that occurs when I run the app, it seems to indicate the presence of Chromium somewhere in nw.js. Chromium works fine with my HiDPI display. It's simply a question of `chromium --force-device-scale-factor=2`, but I don't need to add the argument for Chrome standalone because it seems to detect my scale factor from GNOME somewhere.

Perhaps this can be added to nw.js also?

**Comment by ghostoy** [comment]
NW12 is based on Chromium 41, but I'm not sure whether the switch works. I don't have a HiDPI device. You can try to add this flag to `chromium-args` in `package.json`.

**Comment by braydonf** [comment]
This should be working now based on Gnome display settings. Related https://github.com/nwjs/nw.js/issues/5165

**Comment by ghostoy** [comment]
@cydrobolt This issue should be fixed in latest 0.16.0, see #5165. NW.js will automatically set the scaling factor and you don't have to set `--force-device-scale-factor` argument manually.
