### ISSUE TITLE
OSX crash on startup: Socket path too long

### ISSUE THREAD

**Issue by smr-el** [nwjs/nw.js#4090]
I had an OSX build crash on startup suddenly. 32, 64-bit, blank index file, bare minimum package file. Nothing made it work again. Hours into this problem, I accidentally double-clicked on the compiled nwjs executable inside the compiled app. It loaded a terminal window and displayed the following:

```
$ /Users/username/Development/really-long-app-name/native/really-long-app-name/osx64/really-long-app-name.app/Contents/MacOS/nwjs ; exit;
[3094:1222/102250:FATAL:process_singleton_posix.cc(253)] Check failed: path.length() < arraysize(addr->sun_path). Socket path too long: /var/folders/cb/_95tdlxd2v3dpyh6x7czl37c0000gn/T/.com.nw-builder.really-long-app-name.OD2Ztz/SingletonSocket
** Unknown exception behavior: 0
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...3 completed.

[Process completed]
```

Buried in this output is "socket path too long error". Socket path length maximum on linux is 108 characters. Which is how long my app's socket path was, actually. [Except on OSX the max length is 104 characters](http://serverfault.com/a/641388). 

My solution, of course, was to reduce the length of my app name such that this wouldn't be a problem. Except that's not a permanent solution since I only have control one piece of a very long string.
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
