### ISSUE TITLE
[nw13] Close after download

### ISSUE THREAD

**Issue by sabereen** [nwjs/nw.js#4096]
Hi,
After downloading completed (with node http module), the nw.js window will be closed automatically!

```javascript
var http = nw.require('http');
var fs = nw.require('fs');

var file = fs.createWriteStream("g.png");
var req = http.get("http://www.angusj.com/resourcehacker/bm00.png", function (res) {
	res.pipe(file);
});
```
I tested it with version 0.13 alpha7.

**Comment by rogerwang** [comment]
this is now fixed in git and will be available in the next nightly build. The root cause is that Node is using different memory allocator with chromium. We provided a work around for now and will work on a final solution.
