### ISSUE TITLE
Execute .js when open .js with nw.exe

### ISSUE THREAD

**Issue by Dimtime** [nwjs/nw.js#4099]
I dont sure bug that or option, but i want open .js like .txt file to editing it then in my programm

I want know if it option - how it fix?
If it bug - pretty good to fix it in new version...

Explain  steps
1) Find some.js file example:
var fs = require('fs');
fs.writeFile("c:/temp/test.txt", "test");
2) Right click open with nw.exe
3) Now you .js file execute and process exit before window loading

I dont want to execute it - just open like .txt file.

**Comment by VoidVolker** [comment]
Solution is:

    nw.exe mycommand "file.js"

And result is:

    nwGui.App.argv
    ["mycommand ", "file.js"]

**Comment by Dimtime** [comment]
Thanks, will test it...
But this is not easy solution...
Maybe exist more good...

**Comment by Dimtime** [comment]
Step how to some-fix in windows

1)Delete "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\UserChoice" with .js 
2) create path HKEY_CLASSES_ROOT\.js\shell\open\command with key:
"Disk:\path\nwjs.exe" command "%1"

3) command blocked executing .js, but i think this is no clean way to fix problem...
need some changes in nw.exe how i think...

**Comment by rogerwang** [comment]
If nw.exe takes an argument ends with '.js', it will try to act in the same way as Node -- try to execute it. That's necessary for child_process.fork()

**Comment by Dimtime** [comment]
Hm, yes i understand that, but what way to open it like text?
Solution with command arg is best way?

**Comment by ghostoy** [comment]
As @VoidVolker said, write your NW app which takes the CLI arguments, reads
it and renders in text.

Dimtime <notifications@github.com>于2015年12月28日周一 13:15写道：

**Comment by Dimtime** [comment]
Yes, i use solution and it works... just don't sure that it is best way...
I some new in nw js... maybe later return to this theme with knowledge...
