### ISSUE TITLE
Working with react.js

### ISSUE THREAD

**Issue by cloudy064** [nwjs/nw.js#4100]
My app was base on react.js and nw.js. But it seems like something goes wrong with onPaste, onCut and onCopy. It bothered me for a long time. Where can I find a solution to this? Or, should I provide some stubs for these events?

**Comment by ghostoy** [comment]
Please post your NW version, os and samples.

cloudy064 <notifications@github.com>于2015年12月28日周一 02:22写道：

**Comment by cloudy064** [comment]
nw.js v0.12.3 on Mac OSX 10.11.2
``` javascript
var CustomInput = React.createClass({
    getInitialState: function() {
        return {
            style: customInputStyle.inputNormal
        };
    },

    handleChange: function(event) {
        console.log(event);
        this.props.handleChange(event.target.value);
    },

    handleFocus: function(event) {
        this.setState({style:customInputStyle.inputFocus});
    },

    handleBlur: function(event) {
        this.setState({style:customInputStyle.inputNormal});
    },

    handleCopy: function(event) {
        console.log(event);
    },

    handleCut: function(event) {
        console.log(event);
    },

    handlePaste: function(event) {
        console.log(event);
    },

    render: function() {
        var eventHandlers = {
            onFocus: this.handleFocus,
            onBlur: this.handleBlur,
            onChange: this.handleChange,
            onPaste: this.handlePaste,
            onCut: this.handleCut,
            onCopy: this.handleCopy
        };

        return (
            <div styles={[this.state.style, this.props.style]}>
                <input id={this.props.id} value={this.props.value} type="text" style={customInputStyle.inputEdit} {...eventHandlers} />
            </div>
        );
    }
});
```

And I pack my js files with webpack into bundle.js.

**Comment by cloudy064** [comment]
Well, I found a solution just now. Add the following code to global context.
```javascript
var gui = require("nw.gui");
var option = {
    key: "Ctrl+V",
    active: function() {
        document.execCommand("paste");
    }
};

var shortcut = new gui.Shortcut(option);
gui.App.registerGlobalHotKey(shortcut);
```

But I think it's unnecessary to do this. Why paste, cut and copy events are deprecated?

**Comment by ghostoy** [comment]
On Mac, you have to create builtin menus to support copy paste. See Menu
API.

cloudy064 <notifications@github.com>于2015年12月28日周一 12:36写道：

**Comment by cloudy064** [comment]
@ghostoy Thanks a lot, But what about Windows. Builtin menus are needed as well? My app doesn't support paste on Windows too.

**Comment by fritx** [comment]
Also this ;) https://github.com/nwjs/nw.js/issues/1955

**Comment by cloudy064** [comment]
Well, thanks a lot, and I will try it out. For the moment, I just register global hot keys when my window is activated and unregister them on inactive.
