### ISSUE TITLE
nw13  build no zip and libnw not striped

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#4104]
hi

i finish my nw13 build (ninja -j 8 -C out/Release nwjs)

and don t have any zip at the end as nw12 and lib/libnw.so is 2.6 go

what do i miss ?

thanks

ps: normal to not have libffmpegsumo or need to build it ? thanks

**Comment by rogerwang** [comment]
It's fine.
It's supposed to be stripped in 'dist' build target to dump symbols used for decoding crash dump.
Upstream changed libffmpegsumo to be builtin by default.

**Comment by rogerwang** [comment]
btw, it's better to be discussed in the development mailing list 'nwjs-dev' in google groups.
