### ISSUE TITLE
Nw13-alpha7 self close window without notification when run some code mongodb

### ISSUE THREAD

**Issue by manhdn** [nwjs/nw.js#4105]
Hi all,
I'm trying using NW13-Alpha7 but it got error as bellow.

I'm tried to run simple code to query database, but it self close NW window without notice, this code can run well in node.exe script.js from command line, but failure when run in Node Webkit Page (Js file)

 var MongoClient = require('mongodb').MongoClient;
 MongoClient.connect('mongodb://localhost:27017/db', function(err, db) {
 var collection = db.collection("product");
 setTimeout(function() {
            collection.count({}, function(err, item) {
                console.log(item);
                db.close();
            })
        }, 100);
 });

Note:
- mongodb install well with : npm install -g mongodb
- database db exists and can return result 5 from node.exe script.js
- this code still run well in nw0.12.2

Anyone got this error ? Please help me!

Thank you very much,
##

**Comment by rogerwang** [comment]
Could you please try the latest nightly build? : http://dl.nwjs.io/live-build/

**Comment by Christywl** [comment]
I try on Linux with nwjs-sdk-v0.22.1. `0 ` is returned in the console, and the app isn't closed.
package.json:
```
{
  "name": "test",
  "main": "index.html"
}
```
index.html
```
<script>
var MongoClient = require('mongodb').MongoClient;
MongoClient.connect('mongodb://localhost:27017/db', function(err, db) {
var collection = db.collection("product");
setTimeout(function() {
collection.count({}, function(err, item) {
console.log(item);
db.close();
})
}, 100);
});
</script>
```
Could you please try the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
