### ISSUE TITLE
Nwjc Octane performance

### ISSUE THREAD

**Issue by sirceljm** [nwjs/nw.js#4107]
Hi,

I was thinking of changing Crosswalk to run JS code as a binary (to protect code) and I stumbled upon this project. I set it up to run an Octane benchamrk. But I cannot get nowhere near 30% performance. 

I took a part of Octane javascript like richads.js and compiled it to richards.bin and replaced it index.html

The .bin score is abourt 10x to 20x slower than .js.   

richards.js - ~29000
richards.bin - ~1700

I also thried compiling with different flags like --crankshaft but there it seems that it has no efect on the compiled bin file. The files are identical with many of those flags.

Is there something I am missing?

I also think that implementing this functionality in Crosswalk is a dead end as the performance just isnt there. What do you think?

**Comment by rogerwang** [comment]
Hello, the reason for the slowness is that the V8 engine need the source code to do the further optimization at run time.

We have documented a warning for performance loss in nwjc guide. Currently consider it a trading for source code security with performance. In future we may provide a tool to let you warm up your code with provided data and then dump the fully optimized code.

**Comment by ohenepee** [comment]
@rogerwang Can you promise this warm up and dumping in version 0.13?
