### ISSUE TITLE
couldn't open simple app using nwjs-v0.13.0-beta1-win-ia32

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4109]
When I drag and drop test.nw on nw.exe, it gets stuck to task bar and never opens

debug.log:
[1229/123008:INFO:nw_package.cc(175)] "D:\NW\version_nwjs\nwjs-v0.13.0-beta1-win-ia32\nw.exe" "D:\NW\version_nwjs\nwjs-v0.13.0-beta1-win-ia32\Test.nw"
[1229/123012:ERROR:image_metadata_extractor.cc(112)] Couldn't load libexif.

**Comment by rogerwang** [comment]
There is known issue on some package way. Could you please try unzip it and drag the folder instead? If it's not working for you please submit a sample. Thanks.

**Comment by vivekgaikwad** [comment]
Hey Rojer thanks for replying. I have attached the link of nwjs-v0.13.0-beta1-win-ia32.zip.
I have added Test folder inside nwjs-v0.13.0-beta1-win-ia32 directory and tried to drag and drop on nw.exe folder it opens at stuck to task bar. I also tried to drag and drop on test.nw on nw.exe but it still stuck to taskbar. I am trying this on windows 7 OS(32 bit).

https://www.dropbox.com/s/v6s613ik1qenv6p/nwjs-v0.13.0-beta1-win-ia32.zip?dl=0

**Comment by rogerwang** [comment]
I can confirm this issue and am working on a fix. The window is opened at a position out of the screen so the bug passes all our automatic test.

**Comment by vivekgaikwad** [comment]
Hey Rojer I have changed position: mouse after that it was visible. I have one more issue. When i set toolbar: true in package.json file it still don't shows toolbar when app is opened.

**Comment by rogerwang** [comment]
The fix was just released with beta2. the toolbar is not supported now. btw.
