### ISSUE TITLE
0.13-beta1 toolbar can not open

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4112]
I find this in docs:"As a workaround, you can open / close DevTools with F12 (Windows & Linux) or ⌘+⌥+i (Mac)."

But Windows  is  the same as Mac，all can not open toolbar;

**Comment by rogerwang** [comment]
Do you want to open the toolbar or devtools?

**Comment by zhenlovezhen2012** [comment]
yes,but click F12 can not open devtools.

**Comment by ghostoy** [comment]
Did you downloaded the SDK flavor? DevTools is only available in SDK flavor.

Medusa_Li <notifications@github.com>于2015年12月30日周三 20:41写道：

**Comment by zhenlovezhen2012** [comment]
Thank you very much，I didn't pay attention to the details.  The sdk build can open devtools. Thanks.
