### ISSUE TITLE
how to settle conflicts between Require.js and require within Node.js

### ISSUE THREAD

**Issue by malin1988** [nwjs/nw.js#4113]
I have an online web page which previously embedded in a C++ client, and now I want transfer this page into NW.js environment.

I inject a  JS file using the "inject-js-start" option in manifest.json, to redefine the interface previously defined by C++ clients. But my web page using Require.js as the module management framework, it seems that it's conflicted with the require of Node.js. So do you have any suggestions for me to this problem?

**Comment by makkesk8** [comment]
Don't use requirejs?

**Comment by malin1988** [comment]
Because my web page is already matured and used online for longtime, there's no plan to switch to other framework, it's very inconvinient for me to abandon Require.js

**Comment by rogerwang** [comment]
this is duplicate with #621

**Comment by mcw0933** [comment]
Posting as a heads up for anyone else who finds this issue via search:

The embedded Node.js runtime can be turned off using a manifest setting.  This may help if you (like me) have static content or no need to use Node inside nw.js.

https://github.com/nwjs/nw.js/wiki/faq-name-conflict
https://github.com/nwjs/nw.js/wiki/Manifest-format#nodejs
