### ISSUE TITLE
0.13.0-beta1 package.json bug - MacOS 10.10.5

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4114]
Hi @rogerwang 
trying to launch an app with "window.show = false" in package, it will crash (it doesn't even start).

```
{
  "name": "myapp",
  "description": "my app",
  "version": "0.1.0",
  "main": "app.html",
  "window": {
    "icon": "icon.png",
    "show": false,
   "width": 1000,
    "height": 600,
    "min_width": 800,
    "min_height": 400,
    "position": "center"
   }
}
```

**Comment by AndryBray** [comment]
PS: after the launch of app I run 
var mainWin = nw.Window.get();
mainWin.showDevTools();

Maybe it's related to devtools?

**Comment by rogerwang** [comment]
this is now fixed in git and will be available in the next nightly build.

**Comment by AndryBray** [comment]
@rogerwang 
I have the same problem if I try to run a packaged app with `"show" : false` (nwjs 0.13 beta3 of 6th Jan)
It crash only for packaged app version, if I open the app by CLI it doesn't crash instead.
