### ISSUE TITLE
Using F11 to make application full-screen

### ISSUE THREAD

**Issue by kursatk** [nwjs/nw.js#4115]
Hi;

Is there a way to use fullscreen like browsers'? I mean, pressing F11 will make fullscreen, again F11 press will make it out.

Thanks in advance.

**Comment by chaseWillden** [comment]
Use the [Shortcut](https://github.com/nwjs/nw.js/wiki/shortcut) API and bind it with F11. Also use the [Window enter full screen](https://github.com/nwjs/nw.js/wiki/Window#windowenterfullscreen) API to make it full screen.
