### ISSUE TITLE
0.13 beta1 Renaming app on MacOS X

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4116]
@rogerwang 
I'm trying to rename the nwjs.app in "MyApp.app"
but when I go to change the CFBundleDisplayName in Info.plist, the filename displayed on the finder (mac os) will go back to "nwjs" =/
If I try to list with console (terminal) ls -a in my folder, I see "MyApp.app"

It's really strange situation and I'm going crazy with that... this does not happen with 0.12 version

Checked permissions, roles etc... I can't figure out !!
##

**Comment by AndryBray** [comment]
OK, just figured out that there are new files for localization inside Contents/Resources/en.lproj/InfoPlist.strings
There I should change with my app name!

**Comment by chaseWillden** [comment]
Can I close this?

**Comment by AndryBray** [comment]
I think yes because the app name it's good changing the translation strings.

**Comment by ghostoy** [comment]
@rogerwang We should doc this.
