### ISSUE TITLE
0.13 beta2 package.nw vs app.nw

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4117]
Did you test to pack and run some app with package.nw or app.nw?
Which one do I have to use?
Tested with both (zipped or not) and the app will crash on MacOS (it runs just for 1 second)

**Comment by AndryBray** [comment]
I found the problem:
I was trying to hiding the main app window as a workaround of this bug: https://github.com/nwjs/nw.js/issues/4114

So the app will never start if you try to hide o to start with show=false the main window/app.

Hope this will be fixed asap.
Thank you

**Comment by rogerwang** [comment]
merge with #4114
