### ISSUE TITLE
0.13.0 beta2 - nwjs Helper process not closed

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4118]
@rogerwang 
when I launch an app with sdk build and dev tools opened, when I close it (cmd+q) or right click -> close from dock, I see there is one process still alive in background.

MacOs 10.10.5

Please, could you confirm it?
Thank you

**Comment by AndryBray** [comment]
on MacOS 10.6 I see there is one "blinking" process. It exists for a while, then it disappears and again back after some second. 
Is this normal behavior?

**Comment by rogerwang** [comment]
Thanks I can confirm it.

I'm not sure what do you mean on 10.6. Is it happening during launching or closing?

**Comment by rogerwang** [comment]
this is now fixed in git and will be available in the next nightly build.

**Comment by AndryBray** [comment]
@rogerwang 
on MacOS 10.6 it's happening during all the execution of the app. I will try with the next release and I'll let you know.
