### ISSUE TITLE
Unable to load local resources with AJAX / XMLHttpRequest from the "file://" protocol

### ISSUE THREAD

**Issue by uggrock** [nwjs/nw.js#4119]
In beta2 of version 0.13.0 it is not possible anymore to load local resources from the "file://" protocol. This is the error message in console:

_XMLHttpRequest cannot load file:///home/username/project1/templates/toolbar.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource._

The functionality is widely used in projects of mine for loading templates or translation files and was working in all nw.js versions up to 0.12.3.

Tested under Ubuntu Linux.
##

**Comment by AndryBray** [comment]
As I read, app:// and file:// protocol should be replaced by chrome-extension:// 
please read here: http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by ghostoy** [comment]
@uggrock Is the local path within or out of your nw app?

**Comment by rogerwang** [comment]
We'll see to support this. @uggrock could you please provide a sample case?

**Comment by ghostoy** [comment]
@uggrock I tested with tutorial and it works in latest nw nightly except the images are broken.

The images issue is because AngularJS added `unsafe:` prefix to unknown URLs. In NW.js, the URLs are started with `chrome-extensions:`. The solution is here https://github.com/angular/angular.js/issues/3721. You can add following configs to fix image issues:

```javascript
myApp.config(['$compileProvider',
  function($compileProvider) {
    $compileProvider.imgSrcSanitizationWhitelist(/^\s*((https?|ftp|file|blob|chrome-extension):|data:image\/)/);
    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|tel|file:chrome-extension):/);
  }]);

```

**Comment by uggrock** [comment]
Thank for the support, the reference to #4155 actually solve my issue for now.

**Comment by conceptualspace** [comment]
@uggrock any chance that flag still works for u? trying it on nw 0.20.2 but no dice

use case for me is trying to use a browser library which normally accepts a URL to retrieve via ajax (https://github.com/katspaugh/wavesurfer.js)

**Comment by uggrock** [comment]
We have moved on to electron and are no more maintaining our nw.js api ....
