### ISSUE TITLE
[nw13beta2] Crash when using devtools to view source

### ISSUE THREAD

**Issue by maxbarry** [nwjs/nw.js#4121]
nwjs-sdk-v0.13.0-beta2-linux-x64 experiences a fatal crash on Ubuntu 15.10 when clicking a link in devtools to view the source of a custom module included with nw.require().

To reproduce:

1. Start nwjs: `nwjs-sdk-v0.13.0-beta2-linux-x64/nw`
1. Open devtools by right-clicking in window and selecting "Inspect".
1. Require a custom module, e.g. `var m = nw.require('/home/max/code/myApp/js/Game')`. (The problem also occurs when requiring a custom module via a relative path, e.g. `var m = nw.require('./js/Game')`)
1. If there's an error in the module, the devtools console will display a line like: `Uncaught ReferenceError {message: "myTestThing is not defined"} /home/max/code/myApp/js/Game.js:31`
Similarly, the module might produce output via console.log().
1. Clicking the underlined filename:lineNumber above in order to view the source code crashes everything (dev tools + app). The command line displays: 
```
[5482:5482:1231/150908:FATAL:browser_view.cc(530)] Check failed: browser->is_type_popup(). opening browser window.
#0 0x7f726e52852e <unknown>

Aborted
```
Notably, this only happens when clicking a link that displays the module's full pathname. In some contexts, only the filename is shown instead (e.g. "Game.js:31"), and in these cases, hovering over it pops up a link like "chrome-extension://bdmasdoiqaslfdkhjasfhsda/js/Game.js", and I can click it to successfully navigate to view its source. However, when the full pathname is displayed, hovering will pop up a link like "chrome-devtools://devtools/home/max/code/myApp/js/Game.js", and clicking it will always produce a crash.

**Comment by rogerwang** [comment]
Could you please upload your sample for this?

**Comment by maxbarry** [comment]
```
console.log("hello");
```
If that code is ```/home/max/myModule.js```, I can get a crash by running ```nwjs-sdk-v0.13.0-beta2-linux-x64/nw``` (with no arguments), opening devtools with Right-Click -> Inspect Background page, and typing ```var m = nw.require('/home/max/myModule.js')``` into the devtools console. 

It then displays:
```
hello                                         /home/max/myModule.js:2
```
... and crashes when I click that link "/home/max/myModule.js:2".

**Comment by maxbarry** [comment]
Here is another way to do it:

package.json:
```
{
  "name": "sample",
  "main": "index.html"
}
```

index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <script>
    nw.require('./myModule.js');
    </script>
  </body>
</html>
```

myModule.js:
```
console.log("hello");
```

To reproduce:
  1. ```nwjs-sdk-v0.13.0-beta2-linux-x64/nw .```
  1. Right-click -> Inspect background page
  1. See console output: ```hello                                         /home/max/myModule.js:1```
  1. Click link above to myModule.js

Command-line displays:
```
[10666:10666:0105/144647:FATAL:browser_view.cc(530)] Check failed: browser->is_type_popup(). opening browser window.
#0 0x7f39436a352e <unknown>

Aborted
```

**Comment by rogerwang** [comment]
With the latest nightly build it shouldn't crash any more, but the pointed URL is not found. @ghostoy could you look into this?

**Comment by ghostoy** [comment]
It doesn't crash but popup a new window looks like this:
![screen shot 2016-01-06 at 1 07 13 pm](https://cloud.githubusercontent.com/assets/471928/12135437/752e3952-b476-11e5-8519-515ef3f4542e.png)

**Comment by rogerwang** [comment]
I knew it looks like this ... I mean could you please look to fix it?

**Comment by ghostoy** [comment]
Yeah. I'll take a look at this issue.

**Comment by gwicksted** [comment]
(related?) Crashes (for real) if you click on "module.js" link from Devtools console when it shows an error related to loading a module (eg if the module was not found).  Let me know if this should be a new issue.

**Comment by maxbarry** [comment]
Not sure this is fixed. I get the same (crash) result from the same action with a slightly different test case in beta4.

package.json:
```
{
  "name": "sample",
  "main": "index.html"
}
```

index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <script src="myModule.js"></script>
  </body>
</html>
```

myModule.js:
```
console.log("Loading myModule2...");

nw.require('./myModule2');
```

myModule2.js:
```
myTestError();
```

To reproduce:
  1. Run ```nwjs-sdk-v0.13.0-beta4-linux-x64/nw .```
  1. Right-click on window and select "Inspect"
  1. Click to view Console. (It doesn't start in console by default any more?)
  1. See two lines of output:
```
Loading myModule2...         myModule.js:1 
Uncaught ReferenceError: myTestError is not defined    /home/max/code/sports/test2/myModule2.js:1
```

Clicking the first line of output ("Loading myModule2.js...") does work, kind of: It takes me to the source of myModule.js, although it forgets which line number it's supposed to be showing (instead of scrolling to and highlighting the right one).

Clicking the "Uncaught ReferenceError" line produces the same crashing error as before:
```
[9837:9837:0119/101658:FATAL:browser_view.cc(533)] Check failed: browser->is_type_popup(). opening browser window.
#0 0x7fae84f450ee <unknown>

Aborted
```

**Comment by rogerwang** [comment]
@ghostoy pls follow up.

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.
