### ISSUE TITLE
window on close and on loaded events are not working with nwjs 0.13

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4123]
My code :

var gui= require('nw.gui');
var win = gui.Window.open(
			'test.html', {
			frame: true,
			width: 290,
			height: 0,
			resizable: false
		});

win.on('close', function(){
alert("New Window closed");
});

win.on('loaded', function(){
alert("New Window Loaded"); 
});

Its not working any more.

Also window.open with parameters always-on-top is not working. I have tried it on nwjs-sdk-v0.13.0-beta2-win-ia32.

var win = gui.Window.open(
			'test.html', {
                        'always-on-top': true,
			frame: true,
			width: 290,
			height: 0,
			resizable: false
		});
Not working anymore. I have tried it on nwjs-sdk-v0.13.0-beta2-win-ia32.

**Comment by AndryBray** [comment]
Window.open now accepts a callback as third argument. It doesn't return anymore the window object.
You should use:

```
nw.Window.open(url, options, function(win) {
   //here you can add listeners
})
```

**Comment by rogerwang** [comment]
@AndryBray is correct. As for "always-on-top", it's renamed "always_on_top", documented here: http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#api-changes

**Comment by f0rmiga** [comment]
Sometimes window is not available in third argument's callback. When cascading windows like this:

`
nw.Window.open(url, options, function (win1) {
    nw.Window.open(url2, options2, function (win2) {
        // accessing win1.window gives error saying win1 is not defined
    }
});
`

Note that I wasn't able to reproduce the error every run. It seems that the callback function is returning whether the window is ready or not.
