### ISSUE TITLE
0.13 beta2 - Windows package.nw merge/run problem

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4124]
Hi @rogerwang 
I'm trying to package my app for windows.
If I create a folder with all nwjs files and the zipped package.nw (in separate file) everything works as expected.
If I try to merge nw.exe with package.nw (copy /b nw.exe+package.nw app.exe) when I launch the app.exe I will see the default NW.js splashscreen (it seems my package is not loaded)
##

**Comment by ghostoy** [comment]
@AndryBray Currently appending zip file to exe is not supported yet. It's a [known issues](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues) and will be fixed later.

**Comment by AndryBray** [comment]
Thank you @ghostoy 
I didn't read about that... anyway trying to append plain files doesn't work.
It just works with separate package.nw (zipped or not)

**Comment by ghostoy** [comment]
I didn't mean to append plain files. Just put plain files along with NW exe.

**Comment by tolrtd** [comment]
I am having a similar issue.  For me, if I create a zipped package.nw, the default nw.js page opens.  If I put the same exact files in a folder named package.nw, it opens fine.

Windows 8.1 x64 using nw 0.13 beta 2 (same behavior on regular 32-bit, regular 64-bit, and SDK 64-bit builds)

**Comment by kucix** [comment]
When is planned to support appending executable?

**Comment by Christywl** [comment]
> If I try to merge nw.exe with package.nw (copy /b nw.exe+package.nw app.exe) when I launch the app.exe I will see the default NW.js splashscreen (it seems my package is not loaded)

@AndryBray , I try this, it works well for me on Windows with nwjs-sdk-v0.22.1. The app could be opened if run `app.exe`. Could you please try the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
