### ISSUE TITLE
Unresolved symbols when compiling native node module (serialport) with node-pre-gyp on Windows with nwjs v0.13.0-beta2

### ISSUE THREAD

**Issue by cityant** [nwjs/nw.js#4125]
Hi, when trying to compile serialport (a native node module) with nw.js v0.13.0-beta2 and nodejs5.1, the following linking errors appear:

<pre>
serialport.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) unsigned int __cdecl node::Buffer::Length(class v8::Local<class v8::Object>)
" (__imp_?Length@Buffer@node@@YAIV?$Local@VObject@v8@@@v8@@@Z) [C:\Users\xm\App
Data\Roaming\npm\node_modules\serialport\build\serialport.vcxproj]
serialport.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) char * __cdecl node::Buffer::Data(class v8::Local<class v8::Object>)" (__imp_?Data@Buffer@node@@YAPADV?$Local@VObject@v8@@@v8@@@Z) [C:\Users\xm\AppData\Roa
ming\npm\node_modules\serialport\build\serialport.vcxproj]
...
</pre>

The commands are: 
<pre>
node-pre-gyp configure --runtime=node-webkit --target=0.13.0-beta2 --target_arch=ia32 --target_platform=win32
node-pre-gyp build --runtime=node-webkit --target=0.13.0-beta2 --target_arch=ia32 --target_platform=win32
</pre>

However, when compiling it with nw.js v0.12.2 was perfectly fine!

**Comment by ghostoy** [comment]
Latest NW13 is split into two libraries on Windows: node.lib and nw.lib. You need latest `nw-gyp` on GitHub to support dual library and it's not released yet. `node-pre-gyp` is based on `nw-gyp`.

You can install `nw-gyp` from Github to get it supported:

```bash
npm install -g git+https://github.com/nwjs/nw-gyp.git
```

**Comment by ghostoy** [comment]
@cityant I'm closing this issue now. If you see any problem, please reopen it.
