### ISSUE TITLE
0.13 beta2 - devTools not working on Windows

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4126]
@rogerwang 
testing devtools on Windows 7 but without success.
If I open devtools from code of my app, I see only a blank new page (here should be the console and tools)... more if I do right click on app I see no context menu to open devtools (on MacOS I can see it).
Even shortcut to open it doesn't work

**Comment by rogerwang** [comment]
Are you using the SDK build?

**Comment by AndryBray** [comment]
Ok! I'm sorry, my bad... I was just to tired and downloaded the wrong build!
It works

Thank you
