### ISSUE TITLE
window.opener on new window is giving null value instead of correct window object

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4127]
If we open new window and check window.opener on new window it is giving null value instead of correct window object.

**Comment by vivekgaikwad** [comment]
Can you please reply me as it little bit urgent.

**Comment by ghostoy** [comment]
Are you using nw.Window.open or window.open?

**Comment by vivekgaikwad** [comment]
I am opening new window using javascript window.open to open new

**Comment by ghostoy** [comment]
You have to include your site in ["node-remote" in your `package.json`](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote) to access `window.opener`.

**Comment by ghostoy** [comment]
@vivekgaikwad I'm closing this issue. If you see any problem, please reopen it.

**Comment by rogerwang** [comment]
This is incorrect. `node-remote` should not be a requirement.

**Comment by vivekgaikwad** [comment]
Hello Roger,

I have checked if you don't include node-remote in package.json file, window.opener will return null. Is there any other solution for this?

**Comment by rogerwang** [comment]
Could you please try beta3, we fixed a similar bug. If it doesn't work, please provide your case. thanks.

**Comment by vivekgaikwad** [comment]
I have tried it on nwjs-sdk-v0.13.0-beta3-win-ia32 and window.opener still gives null on window.opener.
I have written code for window.open('test.html') in main.html and written window.opener in test.html it returns null.

**Comment by vivekgaikwad** [comment]
Hey Roger,

$_SERVER['HTTP_REFERER'] returns empty if we add node-remote in package.json. 
Please check this issue as it is urgent.

**Comment by vivekgaikwad** [comment]
Any updates?

**Comment by ghostoy** [comment]
Could you show a full sample?

**Comment by vivekgaikwad** [comment]
I have checked today window.opener returns window object and $_SERVER['HTTP_REFERER'] returns value and it is working. Thank you.
