### ISSUE TITLE
nw13 beta2 - not able to quit fullscreen

### ISSUE THREAD

**Issue by andresiraola** [nwjs/nw.js#4129]
I noticed that I'm not able to go out of fullscreen by pressing escape anymore. 

In previous versions it was possible to go back to the previous window state (what now is called restore) by just pressing escape.

Is it possible to have it back?

**Comment by ghostoy** [comment]
This should be expected. So that developer can control whether user can leave fullscreen mode.
Please use nw API to leave fullscreen mode. And you can register a hotkey of ESC to do it.

**Comment by ghostoy** [comment]
I'm closing this issue because NW worked as expected. Please reopen it if you see different.

**Comment by eridal** [comment]
Hey, we found the same problem. Which is the workaround?

**Comment by ghostoy** [comment]
@eridal That's the recommended way. :+1:

**Comment by rogerwang** [comment]
it should be put into FAQ.
