### ISSUE TITLE
nwjs 0.13 beta3 - request / http not working after new window is open and closed

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4130]
Hi @rogerwang 
I'm trying to make some request from my app using 'request' module (https://www.npmjs.com/package/request) or even http nodejs module... 
It's impossibile to get a response from servers... I tried getting some html page or jpeg file on http or https url, but nothing.

Please could you confirm is it a nwjs bug?

OS: MacOS 10.10.5
node-remote enabled on package.js
PS: my app is running on self-signed https/ssl connection ignoring certificate errors as chromium arguments

**Comment by ghostoy** [comment]
The spec of `node-remote` is changed. And a related bug is fixed in git. Could you try the nightly to see if it's fixed? And please post your sample here.

**Comment by AndryBray** [comment]
node-remote is updated to the new spec.
Anyway you can test it running a simple script using https://www.npmjs.com/package/request

```
var request = require('request');
request('http://www.google.com', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body) // Show the HTML for the Google homepage. 
  }
})
```

You could see the request will not receive a response

**Comment by AndryBray** [comment]
I can confirm this issue even on nwjs 0.13 beta3 (build of 01-02-2016)

**Comment by ghostoy** [comment]
I don't see any problem with `request`. Here is my test app.

package.json
```json
{
  "name": "test-request",
  "main": "index.html",
  "dependencies": {
    "request": "^2.67.0"
  }
}
```

index.html
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>index.html</title>
  <link rel="stylesheet" href="">
</head>
<body>
  <h1>Index.html</h1>
  <button onclick="testRequest()">test request</button>
  <script>

  function testRequest() {
    var request = require('request');
    var ret = request('http://www.google.com', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        console.log(body) // Show the HTML for the Google homepage. 
      }
    })
  }
  </script>
</body>
</html>
```

**Comment by AndryBray** [comment]
I think it's something related with RequireJS framework.
If I exclude require.js it works... 
Please, could you confirm ?

**Comment by AndryBray** [comment]
Finally I found the problem...
It's not related to require.js but to the syntax 'use strict'; 
I'm using nw-boilerplate module and this is using the env_config.js with 'use strict' mode enabled.

Removing it the request will be done. Is that normal?

**Comment by AndryBray** [comment]
There is another bug:
running your example works only the first time... if you reload the page (CMD+R) when you click "test request" nothing happens =(

I can't figure out how to fix it

**Comment by ghostoy** [comment]
What's inside env_config.json? Could you paste it out?

**Comment by AndryBray** [comment]
I just tested your example without any extra file/config.
I found another way to break it:

Open your app and click "test request" , here works
Open devtools and execute:
```
nw.Window.open('anotherPage.html', {}, function(ssWin) {

	ssWin.on('loaded', function() {
		setTimeout(function() {ssWin.close(true)}, 2000);
	});
});
```
Click again "test request" - here doesn't work!


anyway this was the env_config.json:
```
// Loads config/env_XXX.json file and puts it
// in proper place for given Electron context.

'use strict';

(function () {
    var jetpack = require('fs-jetpack');
    if (typeof window === 'object') {
        // Web browser context
        window.env = jetpack.read('env_config.json', 'json');
    } else {
        // Node context
        module.exports = jetpack.read(__dirname + '/../../env_config.json', 'json');
    }
}());
```

**Comment by ghostoy** [comment]
@rogerwang @AndryBray  I've written a test case for this issue in my branch. https://github.com/ghostoy/nw.js/tree/issue-4130

**Comment by rogerwang** [comment]
This is now fixed in git and will be available in the next nightly build.

The reason is the process.exit function is executed incorrectly called when window is closed.
