### ISSUE TITLE
nw13 moveTo

### ISSUE THREAD

**Issue by jssuttles** [nwjs/nw.js#4136]
moveTo coordinates are flip-flopped

line 351: nw.Window
NWWindow.prototype.moveTo = function (x, y) {
      this.appWindow.outerBounds.top = x;
      this.appWindow.outerBounds.left = y;
    };

should be:

NWWindow.prototype.moveTo = function (x, y) {
      this.appWindow.outerBounds.top = y;
      this.appWindow.outerBounds.left = x;
    };

**Comment by ghostoy** [comment]
and `moveBy` is also affected.
