### ISSUE TITLE
nw13 border and shadow on transparent window

### ISSUE THREAD

**Issue by jssuttles** [nwjs/nw.js#4137]
<img width="443" alt="screen shot 2016-01-01 at 2 29 06 pm" src="https://cloud.githubusercontent.com/assets/8527741/12071922/0d2293fc-b094-11e5-9815-83b82423ca3d.png">

nw 12 allowed for a frameless, transparent window that I could use as a splashscreen? Is that going to be available in nw13?

**Comment by ghostoy** [comment]
Could you provide the exact OS, NW version and samples?

**Comment by ghostoy** [comment]
and `moveBy` is also wrong.

**Comment by jssuttles** [comment]
OS X 10.11.2, 0.13.0-beta2sdk.
I'll get back to you with more samples as soon as I get my project back to a running state.
However, here are the window parameters that I used.

nw.Window.open('splash.html', {
    'width': 400,
    'height': 73,
    'min_height': 73,
    'min_width': 400,
    'resizable': false,
    'frame': false,
    'transparent': true,
    'icon': 'trayIcon.png',
    'position': 'center',
    'always_on_top': true
  });

**Comment by jssuttles** [comment]
Here's what splash.html looks like:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Title</title>

  </head>
  <body>
    <img src="./logo.svg">
  </body>
</html>

**Comment by ghostoy** [comment]
@jtg-gg Could you take a look at this issue?

**Comment by jtg-gg** [comment]
hmm, ok will fix it next week
I was using yosemite when developing this transparency feature, if I'm not wrong, in yosemite the drop shadow actually follows the transparency shape.

now I'm using el capitan, and I got exactly ugly drop shadow like @jssuttles 
so I think I'll disable the drop shadow

**Comment by jtg-gg** [comment]
should be fixed at nw13-beta4 build

**Comment by rogerwang** [comment]
The transparency patch is left behind in beta4, but it's enabled in the last nightly build.
