### ISSUE TITLE
nwjs 0.13 beta3 - window not closed

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4138]
@rogerwang 
Very often it's impossible to close windows (click on X native button) on MacOS 10.10.5
This happens even with window popup.

It's hard to give you a test case as it does not depend on my code...

**Comment by AndryBray** [comment]
Many times the window become not closable if I reload my app from console CMD+R

**Comment by ghostoy** [comment]
I can confirm this issue on my mac.

**Comment by rogerwang** [comment]
Does it happen only after reload?

**Comment by FiatPax** [comment]
This is probably also related to this error I am getting on Windows, when I press F5 on console.

The JavaScript context calling chrome.app.window.current() has no associated AppWindow.

**Comment by ghostoy** [comment]
Correction: I can close the window with "X" button when new window is open (0.13.0-beta2). Even after reload with Cmd+R in devtools. But the app don't quit if DevTools is open (reported in #4164).

@AndryBray Did you listen to the `close` event of that window? And could you submit a sample here?

**Comment by AndryBray** [comment]
Yes @ghostoy , my app is listening for the "close" event and I do something like this:

```
nw.Window.open(url, options, function(w) {
	w.on('close', function() {
		w.hide();
		//here I do my stuff
		w.close(true);
	});

	w.on('loaded', function() {
		//here I do something..
	});

	//here I open devtools 
});
```

**Comment by rogerwang** [comment]
I'm confused. Could you please submit a full case to reproduce.

**Comment by AndryBray** [comment]
@rogerwang now I'm able to reproduce (tested on MacOS):

Nwjs: 0.13.0 beta3 - nightly build 2016-01-06 (latest when I'm writing)

package.json must have 
```
....
"window": {
    "show": false,
    "icon": "icon.png",
    "width": 800,
    "height": 600,
    "min_width": 800,
    "min_height": 400,
    "position": "center"
  },
"node-remote": "*://*.yourserver.com/*"
```

Inside your main page/script run this:

```
var winCfg =  {
   "frame": true,
    "position": "center",
    "kiosk" : false,
    "fullscreen" : false,
    "show": false,
    "focus": true,
    "resizable": false,
    "icon": "icon.png",
    "width": 900,
    "height": 700,
    "min_width": 900,
    "min_height": 700,
    "max_width": 900,
    "max_height": 700
};

nw.Window.open('https://yourserver-allowed-in-your-noderemote', winCfg, function(w) {
	w.on('close', function() {
		nw.App.closeAllWindows();
		nw.App.quit();
	});

	w.on('loaded', function() {
		w.show();
		w.showDevTools();
	});
});
```

After the devtools are visible, try to open a new window, even e new popup `window.open('https://www.google.it')` and you will see this new window is not closable by "X" button.

**Comment by ghostoy** [comment]
@AndryBray @rogerwang  I nail down the case. When listening to `close` event to any window, either the first window or the new open window, any other windows can't be closed. See the test case in PR #4197

**Comment by Kagami** [comment]
>When listening to close event to any window, either the first window or the new open window, any other windows can't be closed

I can confirm this, I experience the same on Linux and I thought it was planned to behave like this at first. Now I just listen for `"close"` event on all windows and do `win.close(true)` inside manually.
