### ISSUE TITLE
nwjs 0.13 beta3 - network problems after window.close / reload

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4140]
I'm experiencing a lot of problems with modules that need network transfers (like request) after the window.close()  (nw.Window api) or window reload (CMD+R from devtools)

I opened another related ticket https://github.com/nwjs/nw.js/issues/4130 where you can see the "request" example... but I have the same problem with other modules like tcp-socket handlers.

**Comment by ghostoy** [comment]
This issue should be fixed with #4130. Please check.

**Comment by ghostoy** [comment]
I'm closing this issue. Please reopen it if it doesn't fix your problem.
