### ISSUE TITLE
nwjs 0.13 beta3 - save as... dialog not working

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4142]
In the new version of nwjs when I save some remote file, the browser does not ask me where I have to save the file ("save as" dialog) but it saves automatically in the Downloads folder of MacOS.
The same code in nwjs 0.12 would show the saving dialog.

Is this behavior changed with latest chromium?

Test case:
http://jqueryfiledownload.apphb.com/

**Comment by rogerwang** [comment]
Which link in the test case should I click? I tried several in Chrome browser and none of them trigger the save-as dialog.

**Comment by ghostoy** [comment]
@rogerwang I think you can test with our website  http://nwjs.io/

**Comment by rogerwang** [comment]
Fixed in git.
