### ISSUE TITLE
nwjs 0.13 beta 2 - "node-main" is no longer process.mainModule

### ISSUE THREAD

**Issue by bfattori** [nwjs/nw.js#4144]
I use node-main to bootstrap some background processes. I tried using bg-script but it's undocumented so I don't know what to do with it. Anyway, I checked to see what the value was for `nw.process.mainModule` and it referred to my "main" html file. I looked to see if it had been moved elsewhere but didn't see it.
##

**Comment by gleitz** [comment]
Same issue here. If I have a `main` and `node-main` I can't seem to get a reference on `node-main`

**Comment by Christywl** [comment]
`node-main` works fine on nwjs-sdk-v0.24.4. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
