### ISSUE TITLE
nwjs + MP3 special build for Europe?

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4149]
Hello,
I read about MP3 patent limits on new nwjs and as I read on wikipedia this codec is patent-free for Europe:

`The basic MP3 decoding and encoding technology is patent-free in the European Union, all patents having expired there.`
https://en.wikipedia.org/wiki/MP3#Licensing.2C_ownership_and_legislation

Please, could you add to your builds another one special for Europe companies? (something like nwjs-eu)
Thank you
##

**Comment by ghostoy** [comment]
@AndryBray Currently we don't release NW with proprietary codecs like MP3 and H.264 because of license. But you can build NW with those codecs if you are eligible to use them. See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/).

**Comment by rogerwang** [comment]
@ghostoy I think @AndryBray already knows that ... He is suggesting that since users don't need license for MP3 codec in Europe, we should include it in the official binary.

**Comment by ghostoy** [comment]
@rogerwang How about also providing official binary with all proprietary codecs for developers or company who is eligible to use them?

**Comment by AndryBray** [comment]
It would be nice just to download the built package with proprietary codec.
As @ghostoy said, the company should care to choose which one is eligible to use.

@rogerwang how much time do you think we have to wait for this feature?
Thank you

**Comment by night** [comment]
@rogerwang Electron bundles proprietary codecs, so why doesn't nwjs? With ffmpegsumo gone you're leaving people to download and build nwjs, which is a massive amount of wasted time (downloading and compiling a 20G project) to set two flags on a build. There would be far less confusion and issues cropping up over this if it was just built in or at least included in a separate build.

**Comment by rogerwang** [comment]
@night we'd like to. But we don't have any license to distribute the codecs in question. If we provide a build for application developers who have a license, that's still a violation.

**Comment by mscreenie** [comment]
I agree rebuilding for the he sake of setting two flags is a real set back. 

Is there an easier way? Loading externally?

**Comment by AndryBray** [comment]
@rogerwang why don't you build over a mirror european server? that's not a violation as in Europe every patent is expired.

**Comment by rogerwang** [comment]
We need to be careful verifying the information on wikipedia. In the mean time this issue is assigned to Kevin, who is not an Intel employee.

**Comment by abhijeetk** [comment]
@rogerwang How about providing JS API to enable codec ? 
- Enable all codecs supported by ffmpeg(including proprietary codecs) 
- by default disable proprietary codecs in chromium layer.
- Allow user to enable proprietary codec at chromium layer using JS API. (It is responsibility of developer to enable it)

JS -----> chromium(disabled) ---> ffmpeg(enabled)

After enabling proprietary codec using JS API.(say, mp4)

windows.enableMimeType('video/mp4') ----> chromium(enabled) ---> ffmpeg(enabled)

Please let me know your opinion on this approach.

**Comment by AndryBray** [comment]
@abhijeetk great idea!
:+1:

**Comment by tomekmarchi** [comment]
@abhijeetk love it

**Comment by GnorTech** [comment]
Since the patents on MP3 decoding are expired in the last month, NW.js should enable the mp3 decoding support.
https://en.wikipedia.org/wiki/MP3#Licensing.2C_ownership_and_legislation

**Comment by rogerwang** [comment]
@abhijeetk the API idea won't work. The patent infringement happens when you redistribute the codec binary, not using it.

**Comment by rogerwang** [comment]
Mp3 decoder is in official NW binary since 0.22.1
