### ISSUE TITLE
is it possible to use webpack bundle all node_modules

### ISSUE THREAD

**Issue by mashaly100200** [nwjs/nw.js#4151]
Hi

i can use webpack to bundle the  front-end code  , also i can bundle my own back end code with this article  http://jlongster.com/Backend-Apps-with-Webpack--Part-I

the article show you how to bundle your own code only .
is it possible  to bundle all node_modules also?

when i tried do do , webpack bundle all node_modules  files in one file 5MB  , and i can call that file and work , but it gives me error when load express library . 

Uncaught Error: ENOENT: no such file or directory, open 'D:\types\mime.types'

although my main project folder path is 
D:\temp\testBundle\MyProject

any help or suggestions  ?

thanks in advance

`

**Comment by ghostoy** [comment]
Does your packed modules work in Node.js? If not, it's probably will not be supported by NW.js.

Apps running in local don't suffer serious loading issues as web apps which has to be loaded remotely. So you don't have to pack them into one.

However for NW apps, you can pack your app into zip and load it through NW to reduce the size of your app. See [Package and Distribute](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/).

**Comment by mashaly100200** [comment]
many thanks @ghostoy ,
yes my package modules work in node.js

when i use zip file , the application take long time to startup

**Comment by ghostoy** [comment]
Could you post a simple case of packed modules here?

**Comment by xuzicn** [comment]
Yes it's possible if all node_modules are just require js files.
The problem you met should be some modules are reading local resource, which is located at "types\mime.types". You must change the source code of the module and point the location of resource manually.

**Comment by mashaly100200** [comment]
thanks ghostoy , after two days , i think it's not possible , or need more effort
