### ISSUE TITLE
v0.13.0-beta2: Exception in nw.dll when running native module serialport

### ISSUE THREAD

**Issue by cityant** [nwjs/nw.js#4152]
First, thanks for helping solving the unresolved symbols issue (#4125). The module got compiled successfully, however when trying to running the following js code, an exception threw out. 

Environment: nwjs-sdk-v0.13.0-beta2-win-ia32 + serialport2.0.5 (using natvie module nan@2.1.0")

Js code: 
<pre>
var SerialPortT = require("./node_modules/serialport");
var rsComm = null;

rsComm = new SerialPortT.SerialPort('COM5', {
                  baudrate: 115200
                }, false); 
console.log("open...");

rsComm.open(function (error) {
      if ( error ) {
        console.log('failed to open: '+error);
      } else {
        console.log('open success!');
        }
});
</pre>

Exception:
<pre>
>	serialport.node!Nan::Callback::Call(int argc, v8::Local<v8::Value> * argv) Line 1396	C++
Unhandled exception at 0x5515AFEE (nw.dll) in nw.exe: 0xC0000005: Access violation reading location 0x00000000.
</pre>

**Comment by rogerwang** [comment]
Will look to fix it soon.

**Comment by rogerwang** [comment]
I just pushed a patch to git, which fixed crash with the example of Nan. It should fix the same bug of yours. Please wait for the next nightly build and try again.

**Comment by cityant** [comment]
Thanks for the fix. We tried 0.13.0-beta3 of 2016/1/10, the exception didn't occur again. 
I am also curious that I didn't see your patch in git :)

**Comment by rogerwang** [comment]
There are other repos, chromium and node. The patch for this bug is in Node
repo IIRC.

Yuanping Xiao <notifications@github.com>于2016年1月13日周三 上午11:30写道：
