### ISSUE TITLE
在v0.13.0-beta2版本中使用nodejs闪退

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4156]
我早在0.13的alpha版本就做过测试是有闪退这种情况（想使用nodejs实现nw的自动更新），使用简单第三方库superagent去下载一个zip，就会闪退；

今天，我使用https://github.com/edjafarov/node-webkit-updater去做自动更新，也会闪退，但在0.12版本不会出现闪退的情况。

不知道是不是0.13版本对nodejs支持还没完善？

英文不好，只能用中文了，抱歉

**Comment by ghostoy** [comment]
Please post your issue in English so that everyone can understand and answer your questions.
At least, you can try to use Google Translate or other tools to translate your question and post it here.
