### ISSUE TITLE
window.location.href and nw.Window.get()

### ISSUE THREAD

**Issue by cosminButnaru** [nwjs/nw.js#4157]
After changing the window location with any method (link, window.location.href, window.location.replace, window.location.assign )  the nw.Window.get() method returns a null window (not null but a null window which cannot be altered). Storing the window refference in the global object does not help too - after changing the location the old window is lost.

Version 0.13 beta 2

**Comment by cosminButnaru** [comment]
Version 0.13 beta

**Comment by ghostoy** [comment]
I can confirm this issue. See my test case https://github.com/ghostoy/nw.js/tree/issue-4157
