### ISSUE TITLE
Submenu on the context menu ?

### ISSUE THREAD

**Issue by hems** [nwjs/nw.js#4163]
I would like to do something like "Add to playlist ->" then a list of playlists when right clicking, but it seems that menu.append only accepts MenuItem and that MenuItem doesn't have an "append" method, so i'm not exactly sure how or if that would be possible ?

**Comment by ghostoy** [comment]
Then you need [`menuitem.submenu`](http://docs.nwjs.io/en/latest/References/MenuItem/#itemsubmenu).

**Comment by hems** [comment]
@ghostoy ohhh i didn't see that documentation, i was just looking on the WIKI !

By bad, thanks!
