### ISSUE TITLE
Mac: NW.js doesn't quit if DevTools has opened once

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#4164]
Once DevTools is opened, NW.js won't quit even all window are closed including DevTools.

**Comment by rogerwang** [comment]
I don't think it should be marked as 'mac-only'. It's happening on Linux too at least.

**Comment by ghostoy** [comment]
@rogerwang It doesn't happen on Linux for me.

**Comment by rogerwang** [comment]
I downloaded http://dl.nwjs.io/live-build/01-07-2016/4c67d57-72597e7-1f75962-d4e251b/v0.13.0-beta3/nwjs-sdk-v0.13.0-beta3-linux-x64.tar.gz 

run './nw'
open devtools
close the 2 windows

and the process doesn't quit ....

**Comment by rogerwang** [comment]
There are 2 bugs lead to this. One is crossplatform, the other is mac only. Both of them are fixed now.
