### ISSUE TITLE
Form data is not getting passed with post method in nwjs0.13

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4168]
I have tried following method:

1. Created main.html file which contains a form passing data using POST and jquery ajax call passing data using POST.
2. Test.php file contains print_r($_GET) and print_r($_POST).

Ajax call works fine.
When i try to pass data using form submit its not getting passed using POST. When I check the inspector i found that the request method happens to be GET.

PFA link for the same:
https://www.dropbox.com/s/ltxoqer4zam6syk/Test.zip?dl=0

**Comment by ghostoy** [comment]
It should be fixed in git. See #4131. Please wait and test with the nightly build today.

**Comment by vivekgaikwad** [comment]
I would also like to mention that $_SERVER variable is giving empty array.
I have tried window.open('test.php') in main.html on button, and in test.php i have added following code:

echo "Reffer: ".$_SERVER['HTTP_REFERER'];
print_r($_SERVER);

It returns Reffer: & empty array. Hople this will be fixed in the nightly build.

**Comment by rogerwang** [comment]
This should be fixed in the nightly build.
