### ISSUE TITLE
[v0.13.0-beta2] Crash when use nodejs in NWJS

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4169]
Nw crash when I use "superagent" to download a zip file.

But in 0.12 it works fine;

I did test a long time ago,the nw 0.13alpha is the same as v0.13.0-beta2.
##

**Comment by ghostoy** [comment]
Could you post a sample code here?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
