### ISSUE TITLE
[Win 10][nwjs-0.12.3] Invalid audio output parameter received for a specific speaker

### ISSUE THREAD

**Issue by gracesusanchen** [nwjs/nw.js#4170]
I am having trouble with nwjs-0.12.3 on Win 10 with the [Yamaha PJP-20UR](http://www.yamaha.com/products/en/communication/usb_conference_speakerphones/pjp-20ur/?mode=model) speaker. 

I have replaced the `ffmpegsumo.dll`, and can successfully play mp3 with node-webkit. I have three audio devices: 

* laptop's default speaker (Realtek High Definition Audio)
* minotor speaker (BenQ GL2450H (Intel Monitor Audio))
* [Yamaha PJP-20UR](http://www.yamaha.com/products/en/communication/usb_conference_speakerphones/pjp-20ur/?mode=model)

Out of the three, only the Yamaha one isn't able to play sounds coming from node-webkit.

The yamaha speaker is able to play system sounds and mp3 / video sounds from Chrome (the newest version), but unable to play sounds from nwjs.

I have a basic setup of an MP3 file embeded in a sample page, like so:
``` html
<html>
<head>Test</head>
<body>
<audio controls autoplay src="./mono.mp3">
<p>Your browser does not support the <code>audio</code> element.</p>
</audio>
</body>
</html>
```

When running nwjs with the `--enable-logging` option with the Yamaha speaker, I have this error message:
```
[3168:0106/164324:VERBOSE1:resource_loader.cc(434)] OnReadCompleted: "file:///D:/tests/mono.mp3" bytes_read = 32768
[3168:0106/164324:ERROR:audio_manager_base.cc(250)] Invalid audio output parameters received; using fake audio path. Channels: 0, Sample Rate: 48000, Bits Per Sample: 16, Frames Per Buffer: 480
```

After combing through the Chromium source ([here](https://github.com/nwjs/chromium.src/blob/nw12/media/audio/audio_parameters.cc#L75), and [here](https://github.com/nwjs/chromium.src/blob/nw12/media/base/channel_layout.cc#L13)), I've found that the `Channels` code 0  indicates that the Yamaha speaker channel layout is not supported. But it has mono layout and can play sounds that are not coming from node-webkit.

What might be the reason for this?

I would be grateful for any pointers! Thanks!

**Comment by ghostoy** [comment]
The prebuild NW.js doesn't have MP3 codecs because of license. See [this page](https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags.)

**Comment by gracesusanchen** [comment]
Oh, I forgot to mention. I have replaced the `ffmpegsumo.dll`, so that the other stereos can successfully play sound by node-webkit. The only failing speaker is the Yamaha one. I'll edit the issue to reflect that :)

**Comment by gracesusanchen** [comment]
For what it is worth, I have managed to get the MP3 playing by using the chromium flag `--force-wave-audio`, which forces use of Windows waveXxx API. Apparently, this is a higher-level API whihc uses the Core APIs ([see here](https://msdn.microsoft.com/zh-tw/library/windows/desktop/dd370784%28v=vs.85%29.aspx))

**Comment by ghostoy** [comment]
Glad to see you work out this issue. It sounds like a bug of upstream Chrome.
