### ISSUE TITLE
window on close is working with window.close() but does not actually works when you close the window('click on X on window')

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4171]
I tried following:

var win = nw.Window.get();

win.on('close', function() {
  alert('close');
});

It works when i write win.close(); but it does not work when i actually click on X(close) of Window.
How to capture minimize(_), maximize(o), close(X) events of Window.

**Comment by vivekgaikwad** [comment]
Any updates???

**Comment by rogerwang** [comment]
@ghostoy could you please verify this? It worked for me IIRC.

**Comment by vivekgaikwad** [comment]
I have created test app you can download the files for the same:

https://www.dropbox.com/s/zb2trgmnjd0fbxw/Test2.zip?dl=0

I works on nwjs0.12.3 but not on nwjs-sdk-v0.13.0-beta3-win-ia32

**Comment by ghostoy** [comment]
@rogerwang This issue seems to be Windows only. It works on Linux and Mac, but not on Windows.

A minimal test case would be:

_index.html_
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>win close event</title>
</head>
<body>
  <script>
  var gui = require('nw.gui');
  var win = gui.Window.get();
  win.on('close', function(event) {
    alert('close');
  });
  </script>
</body>
</html>
```

**Comment by vivekgaikwad** [comment]
Any updates?

**Comment by rogerwang** [comment]
@ghostoy OP's report is about `closed` event but in your comment it's `close` ... those are different events.

**Comment by ghostoy** [comment]
@rogerwang The demo @vivekgaikwad provided via Dropbox is trying to hook up `close` event. But the initial post was `closed`.

`close` event doesn't work on Windows, but works good on Mac and Linux. This should be a bug.
`closed` should not be able to run `alert()` since browser window was closed already. That's expected.

**Comment by ghostoy** [comment]
And `closed` event is good on all platforms.

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by vivekgaikwad** [comment]
I'll check it. Thank you

**Comment by vivekgaikwad** [comment]
var gui = require('nw.gui');
var win = gui.Window.get();
win.on('close', function(event) {
alert('closing');
win.close(true);
});
It goes into infinite loop. Is there any way of closing window completely. 
I have checked the same code in nwjs0.12.3 and it is working properly, giving only single alert and window.close(true) closes window completely(If you check it in processes in taskbar, it ends completely in nwjs0.12.3). Why is it going in an infinite loop in nwjs0.13?

**Comment by vivekgaikwad** [comment]
I have checked the same code in Mac and it is working properly.

**Comment by vivekgaikwad** [comment]
win.on('close', function() {
  this.hide(); // Pretend to be closed already
  console.log("We're closing...");
  this.close(true); // then close it forcely
});

 I copied this code from the documentation but it shows error at this.hide(). this is not working in nwjs 0.13

**Comment by rogerwang** [comment]
@ghostoy please cover the loop scenario in your case.

**Comment by ghostoy** [comment]
@rogerwang Yeah. Will do.

**Comment by vivekgaikwad** [comment]
Any updates??

**Comment by rogerwang** [comment]
this was fixed as it was closed by the commit.
