### ISSUE TITLE
in beta 13 of NW,why cant't use 'new-instance' as the option of window

### ISSUE THREAD

**Issue by malin1988** [nwjs/nw.js#4176]
Uncaught Error: Invalid value for argument 2. Property 'new-instance': Unexpected property.

this message emitted if the options containing "new-instance" in nw.Window.open???????why????????

**Comment by rogerwang** [comment]
We're working to fix this. Thanks.

**Comment by gleitz** [comment]
Thanks @rogerwang. I believe the same error occurs for `Unexpected property, Property 'inject-js-end'`

**Comment by ghostoy** [comment]
@gleitz It's renamed to `inject_js_end`. See http://docs.nwjs.io/en/v0.13.0-beta6/For%20Users/Migration/From%200.12%20to%200.13/#manifest-format.

**Comment by gleitz** [comment]
Thanks for the info @ghostoy. I noticed that when using `inject_js_end` in 0.12 the file would be injected when a child iframe is loaded (for example, a child iframe in the HTML specified in `main`). In 0.13 this doesn't seem to be the case. Is there another way to inject JavaScript into a child iframe?

**Comment by malin1988** [comment]
@gleitz,Hi,I have exactly the same problem of iframe injectiong with you,have you solved this problem yet??

**Comment by gleitz** [comment]
@malin1988 no, I haven't. Would you mind submitting a separate bug since this isn't really related to this thread?

**Comment by malin1988** [comment]
@gleitz ,I have solved my situation by just binding functions directly to frame when is ready,like this:
var frame = frame[0];
frame.methoe = function(){};

And the author of NW have suggested me to use webview tag to inject js,you can try it.
https://developer.chrome.com/apps/tags/webview#method-executeScript
