### ISSUE TITLE
Can`t load flash in window 10

### ISSUE THREAD

**Issue by 7demo** [nwjs/nw.js#4177]
I have to use flash in my app. It works well in window 7, but it does`t  work in window 10. The app shows 'Couldn`t load plug-in'

My config :

```
{
  "name": "shiyin-client",
  "main": "index.html",
  "nodejs":false,
   "window": {
    "title": "shiyin",
    "icon": "shiyin.png",
    "toolbar": true, 
    "width": 800, 
    "height": 600,
   "resizable":true,
   "show_in_taskbar":true
  },
  "webkit":{
  "plugin":true
  }
}
```

How can I slove it ?

**Comment by rogerwang** [comment]
Which version are you using?

**Comment by 7demo** [comment]
nwjs-v0.12.3-win-ia32.  My pc is x64.   (I hope my app can work in x64/x86 computer)
However , i work it out.

1, download flashplayer_NPAPI in a x86 pc and installed it.
2, copy the file who is like 'NPSWF64_20_0_0_267.dll' and put in the /plugins (the path is 'C:\Windows\System32\Macromed\Flash')
3, change the config , <code>plugin:true</code>
4, run the 'nw.exe'


It work !!!
