### ISSUE TITLE
nwjs 0.13 beta3 - window.open not loaded using node-remote

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4180]
`window.open('https://jsfiddle.net/thyb/JMTVz/5/')` will not load the page if package.json contains `"node-remote": "*://*.mydomain.com/*"`

I see `nw.Window.open('https://jsfiddle.net/thyb/JMTVz/5/')` works instead (anyway this is not the solution as the window.open method is called by any oauth plugin/system)

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.
