### ISSUE TITLE
nwjs 0.13 beta3 - window title not visible on MacOS

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4186]
Hello, I see the native window title (on the top small bar) is not visible anymore on nwjs 0.13.
With nwjs 0.12 the window title takes the document title value (same value visible on dock context menu for opened windows)
OS: MacOS 10.10.5 / tested on nwjs with sdk
Is this a bug?

**Comment by AndryBray** [comment]
Hi @rogerwang 
please, could you confirm this issue?
Thank you

**Comment by rogerwang** [comment]
Confirmed. Thanks.

**Comment by rogerwang** [comment]
Fixed in git.
