### ISSUE TITLE
0.13.0-beta4 - app crash when closing window if package.window.show is false (MacOS)

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4187]
Same error https://github.com/nwjs/nw.js/issues/4114#issuecomment-169757994  but with beta3 and only if app is launched from zipped app.nw.

Maybe reopen this issue https://github.com/nwjs/nw.js/issues/4114?

**Comment by rogerwang** [comment]
@ghostoy pls add case for this.

**Comment by AndryBray** [comment]
@rogerwang it should be the same as https://github.com/nwjs/nw.js/issues/4114

Try to package some app using this package.json

```
{
  "name": "myapp",
  "description": "my app",
  "version": "0.1.0",
  "main": "app.html",
  "window": {
    "icon": "icon.png",
    "show": false,
   "width": 1000,
    "height": 600,
    "min_width": 800,
    "min_height": 400,
    "position": "center"
   }
}
```

show: false was breaking my packaged app. I will test it again with beta4 and I'll let you know

**Comment by AndryBray** [comment]
@rogerwang I found the problem.

It's not only related to the `show` parameter but there is a special test case to follow:

pacakge.json
```
{
  "name": "myapp",
  "description": "my app",
  "version": "0.1.0",
  "main": "app.html",
  "window": {
    "icon": "icon.png",
    "show": false,
   "width": 1000,
    "height": 600,
    "min_width": 800,
    "min_height": 400,
    "position": "center"
   }
}
```

splashscreen.html
```
<b>Just a splashscreen page with some image</b>
```

app.html (app.js included) <-- this window should be hidden as described in package
```
<script>
//bootstrap code
var _showSplashScreen = function () {
	return new Promise(function(resolve) {
		nw.Window.open('splashscreen.html', {
		    'frame'			: false,
		    'position'		: 'center',
		    'always_on_top'	: true,
		    'width'			: 800,
		    'height'		       : 500,
		    'show'			: false,
		    //'toolbar'		: false,
		    'focus'			: true,
		    "icon"			: "icon.png"
		}, function(ssWin) {

			ssWin.on('loaded', function() {
				console.log('on ssWin loaded');
				ssWin.show();
				resolve(ssWin);
			});
		});
	});
};

//...
_showSplashScreen().then(function(w) {
	window.setTimeout(function() {
		w.close(); //here the app will crash
		w = null;

		//other code useless for test case

	}, 3000);
});
</script>
```

So the app will crash when starts with `show:false`, shows a window and close it.

**Comment by AndryBray** [comment]
I see this happens even if the package has window.show = true and I try to hide right after the main app window (app.html) like that

```
package.json => window: { show: true, .... } ...

var mainWin = nw.Window.get();
//let's hide the main app as first task
mainWin.hide();

//open the splashscreen
// here same code of previous comment
```

The app will crash anyway. So I think it's something related to the visibility of main app window.

@rogerwang  Could you confirm?

**Comment by ghostoy** [comment]
It's mac only. And NW wasn't crashed, but quit the event loop after hidden window is closed. I will add a case for it.

**Comment by rogerwang** [comment]
Fixed and available in the last nightly build.
