### ISSUE TITLE
Alert in nwjs 0.13

### ISSUE THREAD

**Issue by s2dent** [nwjs/nw.js#4190]
How do I get the old version of the "alert" window?
New version:
![1](https://cloud.githubusercontent.com/assets/5107044/12211018/e069bf74-b666-11e5-83c6-6ff223ba1c73.jpg)
Old version:
![2](https://cloud.githubusercontent.com/assets/5107044/12211205/24c45f98-b668-11e5-8d09-1b6a728e817e.jpg)

**Comment by Kagami** [comment]
Try `global.alert()`. It should be native, but probably will still have `the page at xxx says` stuff.

**Comment by rogerwang** [comment]
Will fix the message in the dialog box.

**Comment by tiitremmel** [comment]
Would be really cool to get this working for both - **alert** and **confirm**. I don't know if `global.alert()` should already work as shown above but at least it's not working with OS X 10.10.5 nwjs version http://dl.nwjs.io/live-build/01-26-2016/87b697a-8f8a96a-828b3d9-42be98d/v0.13.0-beta5/nwjs-sdk-v0.13.0-beta5-osx-x64.zip
![screen shot 2016-01-25 at 23 19 59](https://cloud.githubusercontent.com/assets/6403731/12564867/420d1428-c3ba-11e5-9944-5a8210d44948.png)

**Comment by kucix** [comment]
+ prompt()

**Comment by Hectorhammett** [comment]
I have the same problem. Will be waiting for a fix. For now, back to 0.12

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by aparna-singhal** [comment]
i am using 0.16.1 version but still unable to use alert()

**Comment by gencer** [comment]
@rogerwang, sorry to post here but is it possible to get native os messagebox via `alert()` (or equivalent)  instead of chrome's builtin white+blue messagebox? Just like electron does?

**Comment by xchellx** [comment]
You can use the "alert" node package for this as a direct replacement of a native alert dialog. For greater functionality, like message box, input box, and more use the "dialog-node" node package. The advantage of these is that they have no dependencies and is cross-platform compatible.
