### ISSUE TITLE
How to prevent a move action ?

### ISSUE THREAD

**Issue by waitianlou** [nwjs/nw.js#4191]
I use nw.js on debian with two screen in fullscreen mode, I want nw.js alway on primary screen, how ever, when primay screen resolution is lower than vice screen, it is possible that nw.js will move to screen which resolution is higher.

ex:
primay screen(x,y,w,h) 0x0 1280x768
vice screen(x,y,w,h) 1280x0 1920x1010

I move nw.js to 0x0 and register move event and output log.
first, recive move event to 0x0
and soon,recive move event to 1920x0(which is not my action, maybe is the debian window manager)

so, how can i solve this problem

(i try when receive move event to 1920x0, move to 0x0 again, however, it will make a infinite loop)
##

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
