### ISSUE TITLE
[v0.13.0-beta2] Crash when using maximised windows on OSX

### ISSUE THREAD

**Issue by jbaron** [nwjs/nw.js#4192]
Recently upgraded my app (CATS, an IDE for TypeScript) so it also runs on 0.13.0-beta2. One thing I noticed is if when I used full maximised windows (so not even showing the window title bar), I get very quick (reproducible) crashes. Just calling showDevTools or even just switching desktops is already enough to create the crash. When I don't fully maximise the app window (so the titlebar of the window is still showing on the screen), I don't get the crash.

The stacktrace is always similar:

2016-01-09 10:20:35.258 nwjs[565:21845] An uncaught exception was raised
2016-01-09 10:20:35.259 nwjs[565:21845] Item to be removed is not in the menu in the first place
2016-01-09 10:20:35.259 nwjs[565:21845] (
	0   CoreFoundation                      0x00007fff9220bae2 __exceptionPreprocess + 178
	1   nwjs Framework                      0x0000000103cc194e ChromeMain + 596110
	2   libobjc.A.dylib                     0x00007fff8bf9af7e objc_exception_throw + 48
	3   CoreFoundation                      0x00007fff9220b8ba +[NSException raise:format:arguments:] + 106
	4   Foundation                          0x00007fff9173588c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	5   AppKit                              0x00007fff9b205c7f -[NSMenu removeItem:] + 300
	6   nwjs Framework                      0x0000000106afeb25 _ZN2v88UnlockerD1Ev + 20013093
	7   nwjs Framework                      0x0000000106afe535 _ZN2v88UnlockerD1Ev + 20011573
	8   nwjs Framework                      0x0000000106afe019 _ZN2v88UnlockerD1Ev + 20010265
	9   CoreFoundation                      0x00007fff921c570c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	10  CoreFoundation                      0x00007fff921c567f ___CFXRegistrationPost_block_invoke + 63
	11  CoreFoundation                      0x00007fff921c4d47 _CFXRegistrationPost + 407
	12  CoreFoundation                      0x00007fff921c4ab2 ___CFXNotificationPost_block_invoke + 50
	13  CoreFoundation                      0x00007fff921bed42 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	14  CoreFoundation                      0x00007fff920ad145 _CFXNotificationPost + 693
	15  Foundation                          0x00007fff9167a921 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	16  AppKit                              0x00007fff9b2ae7d6 endKeyAndMain + 99
	17  AppKit                              0x00007fff9b0c1fac -[NSApplication sendEvent:] + 6991
	18  nwjs Framework                      0x0000000103cc23dd ChromeMain + 598813
	19  nwjs Framework                      0x000000010419fb9a ChromeMain + 5700314
	20  nwjs Framework                      0x0000000103cc2098 ChromeMain + 597976
	21  AppKit                              0x00007fff9aff403a -[NSApplication run] + 796
	22  nwjs Framework                      0x000000010417cce1 ChromeMain + 5557281
	23  nwjs Framework                      0x000000010417c3e4 ChromeMain + 5554980
	24  nwjs Framework                      0x00000001041bea33 ChromeMain + 5826931
	25  nwjs Framework                      0x0000000103cc728f ChromeMain + 618959
	26  nwjs Framework                      0x0000000106ea6b39 _ZN2v88UnlockerD1Ev + 23846969
	27  nwjs Framework                      0x0000000106ea90a2 _ZN2v88UnlockerD1Ev + 23856546
	28  nwjs Framework                      0x0000000106ea2bd7 _ZN2v88UnlockerD1Ev + 23830743
	29  nwjs Framework                      0x0000000104139008 ChromeMain + 5279560
	30  nwjs Framework                      0x0000000104138616 ChromeMain + 5277014
	31  nwjs Framework                      0x0000000103c30102 ChromeMain + 66
	32  nwjs                                0x0000000103c25f39 main + 9
	33  nwjs                                0x0000000103c25f24 nwjs + 3876
	34  ???                                 0x0000000000000002 0x0 + 2
)

**Comment by rogerwang** [comment]
Could you please submit a case or the crash dump? btw, you could also try the nightly build: http://dl.nwjs.io/live-build/

**Comment by jbaron** [comment]
The nightly build crashes at startup with an out of memory (OSX 10.11.2, 8 Gig mem). So couldn't use that.

Hereby the complete dump (from starting up the app till it dies). I also added the dump file if I'm guessing correctly its location. Let me know if there is something more I can help with.

[dump.zip](https://github.com/nwjs/nw.js/files/86857/dump.zip)



peter$ ../nwjs-sdk-v0.13.0-beta2-osx-x64/nwjs.app/Contents/MacOS/nwjs ./
[0112/071903:INFO:nw_package.cc(175)] ../nwjs-sdk-v0.13.0-beta2-osx-x64/nwjs.app/Contents/MacOS/nwjs ./
2016-01-12 07:19:11.189 nwjs[492:14912] *** Assertion failure in -[NSMenu removeItem:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.34/Menus.subproj/NSMenu.m:832
2016-01-12 07:19:11.192 nwjs[492:14912] An uncaught exception was raised
2016-01-12 07:19:11.192 nwjs[492:14912] Item to be removed is not in the menu in the first place
2016-01-12 07:19:11.192 nwjs[492:14912] (
	0   CoreFoundation                      0x00007fff8e4e0ae2 __exceptionPreprocess + 178
	1   nwjs Framework                      0x000000010ca2b94e ChromeMain + 596110
	2   libobjc.A.dylib                     0x00007fff8826ff7e objc_exception_throw + 48
	3   CoreFoundation                      0x00007fff8e4e08ba +[NSException raise:format:arguments:] + 106
	4   Foundation                          0x00007fff8da0a88c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	5   AppKit                              0x00007fff974dac7f -[NSMenu removeItem:] + 300
	6   nwjs Framework                      0x000000010f868b25 _ZN2v88UnlockerD1Ev + 20013093
	7   nwjs Framework                      0x000000010f868535 _ZN2v88UnlockerD1Ev + 20011573
	8   nwjs Framework                      0x000000010f868019 _ZN2v88UnlockerD1Ev + 20010265
	9   CoreFoundation                      0x00007fff8e49a70c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	10  CoreFoundation                      0x00007fff8e49a67f ___CFXRegistrationPost_block_invoke + 63
	11  CoreFoundation                      0x00007fff8e499d47 _CFXRegistrationPost + 407
	12  CoreFoundation                      0x00007fff8e499ab2 ___CFXNotificationPost_block_invoke + 50
	13  CoreFoundation                      0x00007fff8e493d42 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	14  CoreFoundation                      0x00007fff8e382145 _CFXNotificationPost + 693
	15  Foundation                          0x00007fff8d94f921 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	16  AppKit                              0x00007fff975837d6 endKeyAndMain + 99
	17  AppKit                              0x00007fff97396fac -[NSApplication sendEvent:] + 6991
	18  nwjs Framework                      0x000000010ca2c3dd ChromeMain + 598813
	19  nwjs Framework                      0x000000010cf09b9a ChromeMain + 5700314
	20  nwjs Framework                      0x000000010ca2c098 ChromeMain + 597976
	21  AppKit                              0x00007fff972c903a -[NSApplication run] + 796
	22  nwjs Framework                      0x000000010cee6ce1 ChromeMain + 5557281
	23  nwjs Framework                      0x000000010cee63e4 ChromeMain + 5554980
	24  nwjs Framework                      0x000000010cf28a33 ChromeMain + 5826931
	25  nwjs Framework                      0x000000010ca3128f ChromeMain + 618959
	26  nwjs Framework                      0x000000010fc10b39 _ZN2v88UnlockerD1Ev + 23846969
	27  nwjs Framework                      0x000000010fc130a2 _ZN2v88UnlockerD1Ev + 23856546
	28  nwjs Framework                      0x000000010fc0cbd7 _ZN2v88UnlockerD1Ev + 23830743
	29  nwjs Framework                      0x000000010cea3008 ChromeMain + 5279560
	30  nwjs Framework                      0x000000010cea2616 ChromeMain + 5277014
	31  nwjs Framework                      0x000000010c99a102 ChromeMain + 66
	32  nwjs                                0x000000010c990f39 main + 9
	33  nwjs                                0x000000010c990f24 nwjs + 3876
	34  ???                                 0x0000000000000002 0x0 + 2
)
2016-01-12 07:19:11.193 nwjs[492:14912] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Item to be removed is not in the menu in the first place'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8e4e0ae2 __exceptionPreprocess + 178
	1   nwjs Framework                      0x000000010ca2b94e ChromeMain + 596110
	2   libobjc.A.dylib                     0x00007fff8826ff7e objc_exception_throw + 48
	3   CoreFoundation                      0x00007fff8e4e08ba +[NSException raise:format:arguments:] + 106
	4   Foundation                          0x00007fff8da0a88c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	5   AppKit                              0x00007fff974dac7f -[NSMenu removeItem:] + 300
	6   nwjs Framework                      0x000000010f868b25 _ZN2v88UnlockerD1Ev + 20013093
	7   nwjs Framework                      0x000000010f868535 _ZN2v88UnlockerD1Ev + 20011573
	8   nwjs Framework                      0x000000010f868019 _ZN2v88UnlockerD1Ev + 20010265
	9   CoreFoundation                      0x00007fff8e49a70c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	10  CoreFoundation                      0x00007fff8e49a67f ___CFXRegistrationPost_block_invoke + 63
	11  CoreFoundation                      0x00007fff8e499d47 _CFXRegistrationPost + 407
	12  CoreFoundation                      0x00007fff8e499ab2 ___CFXNotificationPost_block_invoke + 50
	13  CoreFoundation                      0x00007fff8e493d42 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	14  CoreFoundation                      0x00007fff8e382145 _CFXNotificationPost + 693
	15  Foundation                          0x00007fff8d94f921 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	16  AppKit                              0x00007fff975837d6 endKeyAndMain + 99
	17  AppKit                              0x00007fff97396fac -[NSApplication sendEvent:] + 6991
	18  nwjs Framework                      0x000000010ca2c3dd ChromeMain + 598813
	19  nwjs Framework                      0x000000010cf09b9a ChromeMain + 5700314
	20  nwjs Framework                      0x000000010ca2c098 ChromeMain + 597976
	21  AppKit                              0x00007fff972c903a -[NSApplication run] + 796
	22  nwjs Framework                      0x000000010cee6ce1 ChromeMain + 5557281
	23  nwjs Framework                      0x000000010cee63e4 ChromeMain + 5554980
	24  nwjs Framework                      0x000000010cf28a33 ChromeMain + 5826931
	25  nwjs Framework                      0x000000010ca3128f ChromeMain + 618959
	26  nwjs Framework                      0x000000010fc10b39 _ZN2v88UnlockerD1Ev + 23846969
	27  nwjs Framework                      0x000000010fc130a2 _ZN2v88UnlockerD1Ev + 23856546
	28  nwjs Framework                      0x000000010fc0cbd7 _ZN2v88UnlockerD1Ev + 23830743
	29  nwjs Framework                      0x000000010cea3008 ChromeMain + 5279560
	30  nwjs Framework                      0x000000010cea2616 ChromeMain + 5277014
	31  nwjs Framework                      0x000000010c99a102 ChromeMain + 66
	32  nwjs                                0x000000010c990f39 main + 9
	33  nwjs                                0x000000010c990f24 nwjs + 3876
	34  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by jbaron** [comment]
Seems to be working fine in 0.14-rc1, thanks!  So I will close this issue now.
