### ISSUE TITLE
launch two nwjs applications

### ISSUE THREAD

**Issue by billib** [nwjs/nw.js#4193]
I have two applications I created, each application have its own nwjs folder.
When I launch an application I can't launch the second one.
Is it possible to launch more than one nwjs application?

**Comment by offshore** [comment]
You may have over 9000 folders with same count of unique code contained in there.
But if the name of your application in manifest definition is not unique, it considered being duplicate.
See this: [Manifest reference for `name` field](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#name)
Also have a look at this, paying attention to deprecation note: [Manifest reference for `single-instance` field](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#single-instance)

**Comment by billib** [comment]
correct, the two applications had the same name.
When I put differents names I was able to start the two applications at the same time.
Thank you for pointing me the right direction.
