### ISSUE TITLE
Devtools crashing when "--use_strict" js-flag is used.  

### ISSUE THREAD

**Issue by jhm-ciberman** [nwjs/nw.js#4194]
PROBLEM: When you use  "js-flags":"--use_strict" in the manifest, nw starts fine, but when you open devtools, it simply shows a white window. 

EXPECTED: This flag should force "use strict"; in all your app. without affecting devtools. 

FIX: The "--use_strict" flag should affect only your app, not the devtools. (or you can fix the part of the devtools that is not writed in strict mode)

Thanks. 
##

**Comment by rogerwang** [comment]
Thanks for reporting. Which version are you using?

**Comment by jhm-ciberman** [comment]
Oh, sorry. I am ussing NW 13 Beta 2. SDK Flavor.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.1. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
