### ISSUE TITLE
[0.13.0-beta2] "No accessible cookie store found for the current execution context."

### ISSUE THREAD

**Issue by ocher** [nwjs/nw.js#4199]
It is not possible to set cookie in 0.13.0-beta2. The very similar code works fine in 0.12.3. Here you can see an example:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
    <script>
      nw.Window.get().cookies.set({
        url: 'http://www.test.com',
        name: 'testcookie',
        domain: 'test.com',
        path: '/',
        value: 'Hi there!'
      });      
    </script>
  </head>
  <body>
    <div>Cookie value: "<span id="cookie"></span>"</div>
    <script>
      var details = {name: 'testcookie', url: "http://www.test.com"};
      nw.Window.get().cookies.get(details, function(cookie) {
        document.getElementById('cookie').innerHTML = cookie.value;
      });
    </script>
  </body>
</html>
```

After running that code you can see in the console "No accessible cookie store found for the current execution context." exception. However, when I'm trying to set the cookie from the console, it works ok. Am I missing something, or is it some kind of regression?

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.
