### ISSUE TITLE
[0.13.0-beta2] Cannot change window size

### ISSUE THREAD

**Issue by ZOTTCE** [nwjs/nw.js#4201]
Hello.

I cannot set window size in a manifest file and in code. Window keep latest size value.

I have the manifest file:

```
{
    "name": "NameName",
    "main": "index.html",
    "window": {
        "width": 400,
        "height": 150
    }
}
```

It work correct in stable nw version but have troubles in v0.13.0-beta2.

OS: Windows 10. Build 11082.
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 10 with nwjs-sdk-v0.22.1. `width` and `height` in `window` work well.

**Comment by Christywl** [comment]
close until there is more information.
