### ISSUE TITLE
[0.13.0-beta2] How to find generated extension ID when using chrome-extension protocol

### ISSUE THREAD

**Issue by Jrags87** [nwjs/nw.js#4203]
I am trying to migrate my app to v13 and it will not open because app protocol is deprecated. Inside my manifest I am using the following:

{
  "main": "app://server/bin/splash.html",
  "name": "Server",
  "version": "4.0.4",
  "node-remote": "https://domain.com"
  }
}

How do I find the generated extension ID so I can use chrome-extension instead of the app protocol.
##

**Comment by rogerwang** [comment]
You can just use the relative path for "main" and it will be loaded with the chrome-extensions protocol.

**Comment by 1j01** [comment]
In other cases you may need it though. You can get it with `chrome.runtime.id` which I found [here](https://github.com/nwjs/nw.js/issues/4806#issuecomment-223102980).

**Comment by Christywl** [comment]
@Jrags87 , does the above advise work for you? If so, let's close this issue.

**Comment by Jrags87** [comment]
Yes it has, thanks for the help!
