### ISSUE TITLE
0.12.3 windows executables are being flagged by virustotal

### ISSUE THREAD

**Issue by flohdot** [nwjs/nw.js#4204]
for nwjs-v0.12.3-win-x64/nw.exe:

> VirusTotal's antivirus scan report for the file with MD5 28c9c790e6e6cf97436b7668b07212ca at 2016-01-11 22:45:01 UTC. 1 out of 55 antivirus detected the file as malicious. Some of the detections were: Heur.PIF.a

[source](https://www.virustotal.com/en/file/d975a82b0f7996e3a76e445b4ea371cd9a50556d82b664c3c1a3877cd2a1840f/analysis/1452552301/)

for nwjs-v0.12.3-win-ia32/nw.exe

> VirusTotal's antivirus scan report for the file with MD5 34b2c7330223936153e420910608ccba at 2016-01-11 22:45:14 UTC. 2 out of 54 antivirus detected the file as malicious. Some of the detections were: Trojan.Win32.Filecoder.nfr (v), Trojan.Win32.Filecoder.nfr (v)

[source](https://www.virustotal.com/en/file/ca24339612adf954f5adb123df3e302cfc40d89940083df10fc81aa276dcb0f9/analysis/1452552314/)

The equivalent files from 0.12.2 and 0.13.0-beta2 are okay. Presumably this is a false positive, but it's bad news for users/developers.
##

**Comment by leandroclem** [comment]
Hello, having the same problem.

https://www.virustotal.com/pt/file/0d22f2e0ff4e03f28bf0a0deaccd089f883a3648c57ae133ec10b59db7f3684a/analysis/1453397630/

**Comment by Christywl** [comment]
I can't reproduce on nwjs-sdk-v0.24.4-win-x64. 

Detection ratio: | 0 / 65
-- | --

**Comment by Christywl** [comment]
close until there is more information.
