### ISSUE TITLE
[0.13 beta3] chrome.tabCapture.capture [only console capture]

### ISSUE THREAD

**Issue by danhanfry** [nwjs/nw.js#4206]
forgive me for my English.

Testing chrome extension

I try to capture the tab with

Very simple code

```
var gui = require('nw.gui');

   chrome.tabCapture.capture({
        audio: true,
        video: true,
        videoConstraints: {
            mandatory: {
               chromeMediaSource: 'tab'
            },
        },
    }, function(stream) {

      console.log('...', stream)

      document.getElementById('video').src = URL.createObjectURL(stream);
      document.getElementById('video').play();

    });
```

I recorded toolbar
I do not understand why not record my main index.html file tab

![image](https://cloud.githubusercontent.com/assets/8139751/12253116/a319edaa-b8dd-11e5-8ddc-9ded8594a631.png)
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide your full tests and steps to reproduce it?

**Comment by thedracle** [comment]
This is still reproducible for me.

It seems like the main window isn't considered a tab for some reason:

chrome.tabs.getAllInWindow((tabs) => {console.log(JSON.stringify(tabs))})
undefined
VM1299:1 [{"active":true,"audible":false,"autoDiscardable":true,"discarded":false,"height":730,"highlighted":true,"id":-1,"incognito":false,"index":0,"mutedInfo":{"muted":false,"reason":"capture"},"pinned":false,"selected":true,"status":"complete","title":"Developer Tools - chrome-extension://kkbllamfdjhlalijflccbgbcdigikgcg/index.html","url":"chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome…om/serve_file/@2a03c99a5f45c6d507af8eb2345ad68a565d1518/&dockSide=undocked","width":1142,"windowId":4}]

As you can see, the only tab that shows up using chrome.tabs is the Developer Tools panel, in the event you have the devtools open.

**Comment by Christywl** [comment]
I  can reproduce the thedracle's issue with nwjs-sdk-v0.25.4.

**Comment by GnorTech** [comment]
Supported in 0.29.0 pre-release, see https://github.com/nwjs/nw.js/issues/359#issuecomment-368778855
