### ISSUE TITLE
Touchstart event triggers twice

### ISSUE THREAD

**Issue by Pandzinho** [nwjs/nw.js#4211]
It seems that nw.js app triggers touchstart event twice. I get events in next order:

``` javascript
-touchstart
-touchend
-click
-touchstart
-touchend
-click
```

If touch is longer than 300ms then events occur in next order

``` javascript
-touchstart x 2
-touchend
-click
```

HTML content is empty, with only these 3 event listeners attached to the document.

``` html
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
<script type="text/javascript">
    document.addEventListener('click', function(e){
        console.log('click');
    });

    document.addEventListener('touchstart', function(e){
        console.log('touchstart');
    });

     document.addEventListener('touchend', function(e){
        console.log('touchend');
    });

</script>
</head>
<body>
</body>
</html>
```

I couldn,t find any flag which would prevent this kind of behaviour.

Versions with this behavior - '0.12.3', '0.13.0-beta2', 'node-webkit-0.11.2'
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 10 with nwjs-sdk-v0.22.1.

**Comment by Christywl** [comment]
close until there is more information.
