### ISSUE TITLE
Crash reports are stored outside of user-data-dir on nw13

### ISSUE THREAD

**Issue by Kagami** [nwjs/nw.js#4212]
Hi. This is probably known issue as listed in [migration docs](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues), but I haven't found anything similar here in bugtracker.

I have `"chromium-args": "--user-data-dir=MyAppData"` in `package.json` and all configs & cache are stored in my custom dir, as expected. `dataPath` also contains the correct value:

```
>>> nw.App.dataPath
"/home/kagami/MyAppData/Default"
```

The problem is, `Crash Reports` dir get created in default location every time, I haven't found any way to change it, including chrome options like `--crash-dumps-dir` and `--disable-breakpad`. Relevant strace:

```
$ strace -f ./nwjs-sdk-v0.13.0-beta3-linux-x64/nw app/ |& grep "Crash Reports"
access("/home/kagami/.config/app/Crash Reports", F_OK) = -1 ENOENT (No such file or directory)
stat("/home/kagami/.config/app/Crash Reports", 0x7ffea9b73c48) = -1 ENOENT (No such file or directory)
mkdir("/home/kagami/.config/app/Crash Reports", 0700) = 0
```
#2906 is probably related, but I don't use `setCrashDumpDir` and have correct `app-data-path` so I suppose it should be stored there?

Is there any other way to disable/change `Crash Reports` directory location? Thanks.
##

**Comment by Christywl** [comment]
seem duplicate with #5248 , it should be fixed on the latest nwjs build, please double check.

**Comment by rogerwang** [comment]
yeah, it's duplicate and should be fixed.
