### ISSUE TITLE
Cut, Copy and paste in nwjs

### ISSUE THREAD

**Issue by Olumyco** [nwjs/nw.js#4219]
What is the native code for copy, cut and paste in nwjs. I am currently working on my app menu bar
##

**Comment by ghostoy** [comment]
You might want to use [Clipboard API](http://docs.nwjs.io/en/latest/References/Clipboard/).

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
