### ISSUE TITLE
Renaming node-webkit require and using requirejs throws error

### ISSUE THREAD

**Issue by ericduran** [nwjs/nw.js#422]
I've already rename window.require to window.requireNode but as soon as soon as I run

```
  var gui = requireNode('nw.gui');
```

There's an error about window.require.

Everything work if I don't load any of the GUI libs. I can use requireNode to load node modules without a problem.

**Comment by silistri** [comment]
Hello 

I've fixed this issue by redefining require function before configuring requirejs.

<code>
window.require = (function(nodewebkit, requirejs) {
    result = function(arg0) {
        if (Array.isArray(arg0)) {
            return requirejs.apply(null, arguments);
        }
        else if (arg0 == 'nw.gui') {
            return nwDispatcher.requireNwGui();
        }
        else {
            return nodewebkit.apply(null, arguments);
        }
    };
    for (var i in requirejs) {
        if (!result[i]) {
            result[i] = requirejs[i];
        }
    }
    //Simulate special require.nodeRequire, something added by r.js.
    result.nodeRequire = nodewebkit
    return result;
})(global.require, window.require);
</code>

Furthermore, this plugin can load nodejs packages with the requirejs AMD style

<code>
// this plugin loads nodejs module with node webkit loader
define('nodejs', ['module'], function(module) {
    'use strict';
    
    var config = (module.config && module.config()) || {};
    return {
        load: function(name, req, done) {
            // If we're optimizing, do nothing
            if (config && config.isBuild) {
                done();
                return
            }
            
            if (name == 'nw.gui') {
                done(nwDispatcher.requireNwGui());
                return;
            }
            
            // Try to load, but throw errors if not found
            try {
                done(global.require(name));
            }
            catch (e) {
                done.error(e);
            }
        }
    }
})
</code>

**Comment by MiniGod** [comment]
@silistri :+1: 
Your overloading of `window.require` works perfectly for me.

But I had to keep the [official name conclict solution][1] as well, before loading `require.js`.
So I had to do in order:
1. [Official name conclict solution][1]
2. Load require.js
3. Overload using @silistri's solution above
4. Then config

[1]: https://github.com/nwjs/nw.js/wiki/faq-name-conflict
