### ISSUE TITLE
No permission to use webRequest api in nw.js v0.13.0-beta2

### ISSUE THREAD

**Issue by skerit** [nwjs/nw.js#4220]
I have an NW.js app with the following in my `bg-script`:

	chrome.webRequest.onBeforeRequest.addListener(function(details) {
		process.stdout.write('\nGot request...');
		process.stdout.write(JSON.stringify(details));
		process.stdout.write('\n');
	},
	{urls: ["<all_urls>"]});

However, each time I get the following error:

    Unchecked runtime.lastError while running webRequestInternal.addEventListener: You need to request host permissions in the manifest file in order to be notified about requests from the webRequest API.

I've seen a few issues here that state the node context already has permission to use every chrome api. Adding a `permissions` entry to the package.json file also does not work: nw.js will refuse to start.

I've tried using the window chrome object, but that doesn't work either.

**Comment by rogerwang** [comment]
Will fix this. Could you please provide a full sample?
