### ISSUE TITLE
nwjs 0.13 beta3 - window.open size different from manifest

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4221]
Hello,
when you try to open a new window (window.open - used also in oauth login systems, where we can't set the window size as parameters) it doesn't care about the package.json window manifest setup.

In nwjs 0.12 I see the default window size is this one specified inside the package.json.

TEST CASE:
package.json
```
{
  "name": "App",
  "version": "1.0.0",
  "main": "app.html",
  "window": {
    "show": true,
    "icon": "icon.png",
    "width": 800,
    "height": 600,
    "min_width": 800,
    "min_height": 400,
    "position": "center"
  }
}
```

call `window.open('http://www.google.it')` after launch... and you will see a 512x448 window size when I expect to be 800x600.

**Comment by ghostoy** [comment]
I'll look into this issue.

**Comment by ghostoy** [comment]
Could you try if `new-win-policy` can solve your problem?

**Comment by AndryBray** [comment]
@ghostoy how can I use the new-win-policy with an "automatic" xauthpopup? I don't create this window so I don't have any reference to it.
Thank you

**Comment by ghostoy** [comment]
`new-win-policy` event is expected to be triggered when any window is popup.

**Comment by AndryBray** [comment]
Please, could you show me an example about how I can listen for this event? Do I have to attach it on main window app?

**Comment by ghostoy** [comment]
In your main html file:
```html
<script>
nw.Window.get().on('new-win-policy', function(frame, url, policy) {
var manifest = nw.App.manifest;
policy.setNewWindowManifest(manifest.window);
})
</script>
```

**Comment by AndryBray** [comment]
thank you @ghostoy  but it doesn't work. The google xauth popup is smaller than the manifest window size.

**Comment by ghostoy** [comment]
@AndryBray It works for my case. Would you post your app?

**Comment by AndryBray** [comment]
It's too much complex and it couldn't work as it's related to a local server... anyway is this expected behavior on nwjs 0.13?  Could you fix this issue to allow new windows to take the manifest default size?

PS: I will try to write a little test case to reproduce my app issue.

**Comment by ghostoy** [comment]
Which platform did you working on ? Windows, Linux or Mac?

**Comment by AndryBray** [comment]
MacOS 10.10.5 - nwjs 0.13 beta4

**Comment by rogerwang** [comment]
Will use the manifest value as the default window dimension.

**Comment by AndryBray** [comment]
@rogerwang  is this fixed?

**Comment by AndryBray** [comment]
Just tested with 0.13-rc1 and there are no changes...

**Comment by rogerwang** [comment]
@AndryBray we're reviewing the change. It will be in rc2. Thanks for your patience.

**Comment by AndryBray** [comment]
@rogerwang thank you all for you work
