### ISSUE TITLE
[0.12.3-linux-ia32] nw-headers 404 on nw-gyp configure

### ISSUE THREAD

**Issue by bredmor** [nwjs/nw.js#4222]
I'm attempting to rebuild ssh2 for use with nw.js, but receive this error output:

`nw-gyp configure`
`gyp info it worked if it ends with ok`
`gyp info using nw-gyp@0.13.0`
`gyp info using node@0.10.25 | linux | ia32`
`gyp http GET http://node-webkit.s3.amazonaws.com/v0.10.25/nw-headers-v0.10.25.tar.gz`
`gyp http 404 http://node-webkit.s3.amazonaws.com/v0.10.25/nw-headers-v0.10.25.tar.gz`
`gyp WARN install got an error, rolling back install`
`gyp ERR! configure error `
`gyp ERR! stack Error: 404 status code downloading tarball`
`gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/nw-gyp/lib/install.js:236:14)`
`gyp ERR! stack     at Request.EventEmitter.emit (events.js:117:20)`
`gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/nw-gyp/node_modules/request/request.js:951:10)`
`gyp ERR! stack     at ClientRequest.EventEmitter.emit (events.js:95:17)`
`gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1688:21)`
`gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)`
`gyp ERR! stack     at Socket.socketOnData (http.js:1583:20)`
`gyp ERR! stack     at TCP.onread (net.js:525:27)`
`gyp ERR! System Linux 3.16.0-57-generic`
`gyp ERR! command "node" "/usr/local/bin/nw-gyp" "configure"`
`gyp ERR! cwd /home/test/Desktop/ESConsole/node_modules/ssh2`
`gyp ERR! node -v v0.10.25`
`gyp ERR! nw-gyp -v v0.13.0`
`gyp ERR! not ok `

**Comment by ghostoy** [comment]
You should pass `--target=0.12.3` to `nw-gyp configure`.

**Comment by ghostoy** [comment]
I'm closing it. Please reopen if it doesn't solve your problem.
