### ISSUE TITLE
The process.versions object uses "node-webkit" as the key for NW.js' version

### ISSUE THREAD

**Issue by cotejp** [nwjs/nw.js#4230]
The `process.versions` object uses `node-webkit` and `nw` as the property names for NW.js' version. In the documentation, it is stated that the version is available via `process.versions['nwjs']`.

Tested under NW.js version 0.13.0-beta3 on Mac.

**Comment by cotejp** [comment]
I just saw that there is a property named simply `nw`. I guess the documentation should be updated to use that...

**Comment by cotejp** [comment]
Fixed by patch #4232. Already merged.

**Comment by rogerwang** [comment]
Thanks for the patch. `node-webkit` is being migrated to `nw` and it will be removed in future version.
