### ISSUE TITLE
[mac] Application fails to launch

### ISSUE THREAD

**Issue by nayanbhana** [nwjs/nw.js#4233]
I had an application that was packaged using nw-builder and everything was working perfectly.
I am releasing my application for 2 platforms, Windows and Mac. 
They both use the same code but the one for Mac doesn't launch. It was working perfectly fine and then like a switch it stopped working. Whenever I try to launch the program, the app icon will show up in the taskbar at the bottom however nothing loads. I get the same behaviour if try to load it via command line or if I package it up in a .app file.

Only now I saw errors in the Mac Error Console. This is what I see whenever I try to launch the app.

https://gyazo.com/cd880fcc25fdd805a6d2b9b010bd19af

I have scoured through all other issues but can't find an answer to why this is happening. Has anyone else faced anything like this?
##

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
