### ISSUE TITLE
[windows] app-id in package.json does not set AppUserModelID

### ISSUE THREAD

**Issue by bjoernneumann** [nwjs/nw.js#4238]
When setting app-id in package.json like described here https://github.com/nwjs/nw.js/wiki/Notification, the AppUserModelID remains empty.

Tested on Windows 7 and 8.1 with nwjs-v0.12.3-win-x64.

This can be determined by some C++ code.
```
HRESULT hr
HWND hwnd = FindWindow(NULL,TEXT("My App"));
if (hwnd != 0) {
	// We found our Window
	IPropertyStore *pps;
	hr = SHGetPropertyStoreForWindow(hwnd, IID_PPV_ARGS(&pps));
	if (SUCCEEDED(hr)) {
		PROPVARIANT pv;
		pps->GetValue(PKEY_AppUserModel_ID, &pv);
	}
}
```
After this pv remains empty, meaning that there is no AppUserModelID assigned.

I'd like to add JumpLists by using ICustomDestinationList::SetAppID() which doesn't work unless the AppUserModelID is set before by IPropertyStore::SetAppID.

**Comment by jtg-gg** [comment]
@bjoernneumann what are you trying to do ?
the app id will be set to the shortcut link, after that then you can use the toast notification.

**Comment by bjoernneumann** [comment]
I want to add jumplist tasks to the taskbar on Windows by an external application. Therefore the nwjs app needs an explicit AppUserModelID assigned, to use (https://msdn.microsoft.com/en-us/library/windows/desktop/dd378416(v=vs.85).aspx)

I got that working by assigning the AppUserModelID with the help of the window handle.

And perhaps i somehow misunderstood the purpose of app-id.
