### ISSUE TITLE
[suggestion] merge docs and wiki, use docs as main info source and more to say

### ISSUE THREAD

**Issue by offshore** [nwjs/nw.js#4239]
Walking around docs and wiki I realized that both duplicates each other less or more; some very important things are missing in the docs, but presented in wiki (for example, [Console and timers](https://github.com/nwjs/nw.js/wiki/Console-and-timers), [Icons](https://github.com/nwjs/nw.js/wiki/Icons), info about [The Kiosk mode](https://github.com/nwjs/nw.js/wiki/The-Kiosk-mode), etc) and vice versa; they are even almost always not cross-linked, its very difficult to search for info, not only for newbies, but also for people who are familiar with chrome, node, and js at all. Finally, I really should not mention total wiki structure absence and docs' lack of examples.
So. Do you have any roadmap for that? If you do, I think it should be provided to community to help you with it's implementation. I really think that there are a lot of people who can and **want** to help, but don't know where to start. And if you don't have some specific notes and TODOs about docs/wiki, we can start from creating some.
For me to say, I'm ready to help; if you (or anybody else) need my contact, it can be found easily on my profile page.

**Comment by rogerwang** [comment]
We used to use wiki only for the documentation and users contribute a lot. Starting from 0.13 early development we planned to maintain an official documentation (and it's good for the versioning) and has been moving contents in wiki to docs.nwjs.io. Currently we don't have any roadmap so please feel free to propose your idea. And welcome to contribute to it.

**Comment by offshore** [comment]
I think I can organize some things to implement in docs, for that I need some info about priorities and maybe some (internal?) guidelines to jump in without bicycle reinvention. Also some notes about team vision for this roadmap and docs at all.
*P.S. check your letterbox.*

**Comment by offshore** [comment]
Moved to dev maillist: https://groups.google.com/forum/#!topic/nwjs-dev/2EB5AzQd2-0
