### ISSUE TITLE
Ability to open a new window without focus

### ISSUE THREAD

**Issue by mmorrisontx** [nwjs/nw.js#424]
To be used in conjunction with #132 and #251 , we typically do not want popup notifications to pull focus from the application. It would probably make sense to make a focus: false option for the gui.Window constructor:

``` javascript
var win = gui.Window.open('popup.html', {
    skip-taskbar: true,
    focus: false
});
win.setAlwaysOnTop(true);
```

**Comment by fifsky** [comment]
+1 Is pit dad BUG

**Comment by dalidong2009** [comment]
I hava try this issue in nw version 0.19.0 ,OS is  win7 32, the config is :
{
                width: 200,
                height: 150,
                x: screen.availWidth - 200,
                y: screen.availHeight - 150,
                resizable: false,
                focus: false,
                show_in_taskbar: false,
                always_on_top: true
            }
the bug which this issue mention  is not appear.

**Comment by zaygraveyard** [comment]
For anyone having this problem, I worked around the issue by having:
* the window opened with:
```js
{
  frame: false,
  show: true,
  focus: false,
  transparent: true,
}
```
* the `<html>` element of the window having `display: none`

and when it's time to show it I just remove the `display: none`

I have tested this on macOS, I don't know if it works on windows or linux.
I hope this helps.
