### ISSUE TITLE
Window.show does not work on linux

### ISSUE THREAD

**Issue by vf1** [nwjs/nw.js#425]
I tested Tray example on Ubuntu 12.10 and Mint. Window can not be restored from the tray, I see only strange blinks on taskbar.
##

**Comment by Joldnine** [comment]
The problem still exists... My code:
    tray.on('click', function() {
      win.show();
    });

    win.on('minimize', function() {
      win.hide();
    });

**Comment by Christywl** [comment]
I can reproduce this on Linux with nwjs-sdk-v0.27.5. 
_It works fine on Windows._
