### ISSUE TITLE
Not able to compile nwjs for windows

### ISSUE THREAD

**Issue by msnj** [nwjs/nw.js#4252]
Not able to compile nwjs for windows. Here are the steps i followed:

Set up the path for depot_tools (https://src.chromium.org/svn/trunk/tools/depot_tools.zip)
gclient
Install VS 2013 community edition
Install Windows 10 SDK
set DEPOT_TOOLS_WIN_TOOLCHAIN=0
set GYP_DEFINES="clang=0"
mkdir -p $HOME/nwjs
cd $HOME/nwjs
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw13
	"custom_deps" : {
	  "src/third_party/WebKit/LayoutTests": None,
	  "src/chrome_frame/tools/test/reference_build/chrome": None,
	  "src/chrome_frame/tools/test/reference_build/chrome_win": None,
	  "src/chrome/tools/test/reference_build/chrome": None,
	  "src/chrome/tools/test/reference_build/chrome_linux": None,
	  "src/chrome/tools/test/reference_build/chrome_mac": None,
	  "src/chrome/tools/test/reference_build/chrome_win": None,
	}
set GYP_MSVS_VERSION=2013
gclient sync --with_branch_heads
Install DirectX SDK
	You have to uninstall VS 2010 redistributable package
	Install DirectX SDK
	Install VS 2010 redistributable package
mkdir -p C:\tmp/nwjs/src/third_party/directxsdk/files
Copied files from /c/Program\ Files\ \(x86\)/Microsoft\ DirectX\ SDK\ \(June\ 2010\)/*  to C:\tmp\/nwjs/src/third_party/directxsdk/files/
cd src
ninja -C out/Debug nwjs

Here is the compilation error i got. Is it some kind of sync issue with v8 checkout ?

C:\tmp\nwjs\src\out\Debug>ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64_x86\cl.exe"  /nologo /FC @obj\gin\gin.converter.obj.rsp /c ..\..\gin\converter.cc /Foobj\gin\gin.converter.obj /Fdobj\gin\gin.cc.pdb
converter.cc
C:\tmp\nwjs\src\gin\converter.h(164) : error C2143: syntax error : missing ';' before '<'
        C:\tmp\nwjs\src\gin\converter.h(199) : see reference to class template instantiation 'gin::Converter<std::vector<T,std::allocator<_Ty>>,void>' being compiled
C:\tmp\nwjs\src\gin\converter.h(164) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\tmp\nwjs\src\gin\converter.h(165) : error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:\tmp\nwjs\src\gin\converter.h(213) : error C2039: 'MaybeLocal' : is not a member of 'v8'
C:\tmp\nwjs\src\gin\converter.h(213) : error C2143: syntax error : missing ';' before '<'
C:\tmp\nwjs\src\gin\converter.h(213) : error C2988: unrecognizable template declaration/definition
C:\tmp\nwjs\src\gin\converter.h(213) : error C2059: syntax error : '<'
C:\tmp\nwjs\src\gin\converter.h(217) : error C2065: 'T' : undeclared identifier
C:\tmp\nwjs\src\gin\converter.h(217) : error C2923: 'gin::ToV8ReturnsMaybe' : 'T' is not a valid template type argument for parameter 'T'
C:\tmp\nwjs\src\gin\converter.h(220) : error C2143: syntax error : missing ';' before '<'
C:\tmp\nwjs\src\gin\converter.h(220) : error C2059: syntax error : '<'
C:\tmp\nwjs\src\gin\converter.h(220) : error C2143: syntax error : missing ';' before '{'
C:\tmp\nwjs\src\gin\converter.h(220) : error C2447: '{' : missing function header (old-style formal list?)
C:\tmp\nwjs\src\gin\converter.h(233) : error C2977: 'gin::ToV8Traits' : too many template arguments
        C:\tmp\nwjs\src\gin\converter.h(220) : see declaration of 'gin::ToV8Traits'
C:\tmp\nwjs\src\gin\converter.cc(18) : error C2039: 'MaybeLocal' : is not a member of 'v8'
C:\tmp\nwjs\src\gin\converter.cc(18) : error C2873: 'MaybeLocal' : symbol cannot be used in a using-declaration
C:\tmp\nwjs\src\gin\converter.cc(44) : error C2660: 'v8::Value::BooleanValue' : function does not take 1 arguments
C:\tmp\nwjs\src\gin\converter.cc(84) : error C2660: 'v8::Value::IntegerValue' : function does not take 1 arguments
C:\tmp\nwjs\src\gin\converter.cc(96) : error C2660: 'v8::Value::IntegerValue' : function does not take 1 arguments
C:\tmp\nwjs\src\gin\converter.cc(126) : error C3083: 'NewStringType': the symbol to the left of a '::' must be a type
C:\tmp\nwjs\src\gin\converter.cc(126) : error C2039: 'kNormal' : is not a member of 'v8'
C:\tmp\nwjs\src\gin\converter.cc(126) : error C2065: 'kNormal' : undeclared identifier
C:\tmp\nwjs\src\gin\converter.cc(128) : error C2228: left of '.ToLocalChecked' must have class/struct/union
C:\tmp\nwjs\src\gin\converter.cc(213) : error C3083: 'NewStringType': the symbol to the left of a '::' must be a type
C:\tmp\nwjs\src\gin\converter.cc(213) : error C2039: 'kInternalized' : is not a member of 'v8'
C:\tmp\nwjs\src\gin\converter.cc(213) : error C2065: 'kInternalized' : undeclared identifier
C:\tmp\nwjs\src\gin\converter.cc(215) : error C2228: left of '.ToLocalChecked' must have class/struct/union

Will i be able to download and compile nw12 ?
I tried changing this command line from 
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw13
to
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw12
but no luck.

**Comment by vishalup** [comment]
I am not able to download node-webkit itself. I am getting following error with following errors.

1. ​D:\Workspace\NW>fetch --no-history chromium --nosvn=True
Running: 'D:\Workspace\depot_tools\python276_bin\python.exe' 'D:\Workspace\depot_tools\gclient.py' root
Running: 'D:\Workspace\depot_tools\python276_bin\python.exe' 'D:\Workspace\depot_tools\gclient.py' config --sp
ec 'solutions = [
  {
    "managed": False,
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "custom_deps": {},
    "deps_file": ".DEPS.git",
    "safesync_url": "",
  },
]
'
Running: 'D:\Workspace\depot_tools\python276_bin\python.exe' 'D:\Workspace\depot_tools\gclient.py' sync --no-h
istory
Error: Command 'D:\\Workspace\\depot_tools\\python276_bin\\python.exe src/build/landmines.py' returned non-zer
o exit status 1 in D:\Workspace\NW
Traceback (most recent call last):
  File "D:\Workspace\depot_tools\\fetch.py", line 346, in <module>
    sys.exit(main())
  File "D:\Workspace\depot_tools\\fetch.py", line 341, in main
    return run(options, spec, root)
  File "D:\Workspace\depot_tools\\fetch.py", line 335, in run
    return checkout.init()
  File "D:\Workspace\depot_tools\\fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "D:\Workspace\depot_tools\\fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "D:\Workspace\depot_tools\\fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "D:\Workspace\depot_tools\python276_bin\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('D:\\Workspace\\depot_tools\\python276_bin\\python.exe', 'D:\\Workspa
ce\\depot_tools\\gclient.py', 'sync', '--no-history')' returned non-zero exit status 2

and some more issues like Managed checkout of code. Will put some logs once I got them.

**Comment by msnj** [comment]
You dont need to download chromium ( i guess you are executing this as mentioned in the depot_tools setup page)

**Comment by rogerwang** [comment]
This is not an issue. You can refer to our official build logs or discuss this in the mailing list.

http://buildbot-master.nwjs.io:8010/waterfall
