### ISSUE TITLE
0.13-beta3 console.log doesn't work in node context

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#4254]
On Linux i386 0.13-beta3, I can't get console.log to print to the terminal window from the node context. Also, it seems that errors originating in the node context don't get output to the terminal window, either.

package.json:
{
  "name": "foo_app",
  "main": "index.html"
}

index.html:
<html>
<head><title>Hello</title></head>
<body>
  Hello World
  <script>
    var foo = require("./foo.js");
    // This will print to the devtools window
    console.log("hello from browser context");
    // But this doesn't print anything...
    foo.bar();
  </script>
</body>
</html>

foo.js:
exports.bar = function() {
    // console.log("hello from node context");
    global.console.log("hello from node context");
}

**Comment by jonwwilkes** [comment]
Just to give a little more info: in nw.js 0.12 I get this to the devtools window _and_ the Gnome terminal:

[15259:0115/231555:INFO:CONSOLE(2)] ""hello from node context"", source: /home/user/Downloads/nwjs-v0.12.2-linux-ia32/foo.js (2)

I can't figure out a trivial test, but in my application there is a class of error messages that only get printed to the Gnome terminal.  In nw.js 0.12 it gives the stack trace for those errors, which of course is a much valued feature. :)

**Comment by offshore** [comment]
See #4244

**Comment by jonwwilkes** [comment]
@offshore: thanks for the reference.  But I'm not looking for workarounds-- I'm reporting a regression.  I want node-context errors reported to the terminal window from which I started nw.js.  With 0.12 I get that.  With 0.13-beta3 I cannot.  Therefore it's a regression.

Also notice that "console.log" and/or "global.console.log" do _not_ print out to a devtools window.

**Comment by jonwwilkes** [comment]
Also-- I apologize for not having a clear example of an error message being printed to the terminal in 0.12 but getting suppressed in 0.13-beta3.  However, it's pretty easy to think of examples where this would happen.  For example: suppose I have a node module that depends on the "net" module to receive data over the wire.  If I screw up the algorithm that processes the data the resulting error won't get printed because it's not associated with any browser context.  Therefore I should get an error printed to the terminal window, as happens in 0.12.

try/catch can help in the interim, but that is too clunky, verbose, complicated, and error prone to be a general solution.

**Comment by offshore** [comment]
@jonwwilkes
That's not a regression. Please read carefully the [0.13 Architecture changes](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#architecture-changes). And I was referencing #4244 not for workarounds, but for paying attention to that changes.
As for me, the **real** problem here is that is no way to fine-control console output for now; and **this** maybe needs to be taken into consideration, well, if it's not already.

**Comment by jonwwilkes** [comment]
I'm really only interested in errors that got reported under 0.12 and now don't get reported at all under 0.13.  I gave console.log as an easily reproducible example of suppressing output, but I think it's a different issue.  I'll file another bug to show suppression of error output in the node context.

**Comment by jonwwilkes** [comment]
@offshore: would you mind explaining exactly what "background page" means in the Architecture changes you told me to carefully read?  Thanks.

**Comment by offshore** [comment]
@jonwwilkes from [this comment](https://github.com/nwjs/nw.js/issues/4244#issuecomment-171706674):
> ...And finally, have a look at [0.12 to 0.13 migration notes' architecture changes](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#architecture-changes):
>> The Node.js context is put in the DOM context of the background page, which is shared between opening windows as in 0.12 and before.

This means that in 0.13 you have to expect things sent to console.log inside node context appear in background's page devtools. The terminal window seems not related to this for me; as I said above, I think it's another issue about fine-controlling std streams.

**Comment by jonwwilkes** [comment]
@offshore: in my example code above, what is the "background page devtools"?  Is it the devtools window for index.html?

If so, then the bug I'm reporting is that there is a class of node context errors which do not get printed there.  (And again, I'll try to supply a better example to show this.)

**Comment by offshore** [comment]
@jonwwilkes we are just talking about different things. A better example is definitely an option.

**Comment by jonwwilkes** [comment]
@offshore: I'll do that.  But I still don't understand what "background page" refers to, and the documentation you told me to carefully read doesn't explain what it refers to.

**Comment by offshore** [comment]
![image](https://cloud.githubusercontent.com/assets/464558/12399670/797db216-be2c-11e5-894c-7a5ae9ce01bc.png)
Just to make things clear :))
Or maybe we completely misunderstood each other.

**Comment by jonwwilkes** [comment]
@offshore: Ah, I see.  The documentation is very difficult to understand in this case-- if you're not already thinking about that menu item it's an ambiguous term.

Anyhow, I'll do some more testing and try to post a clean bug example later.

**Comment by offshore** [comment]
Np, I thought you saw [that comment](https://github.com/nwjs/nw.js/issues/4244#issuecomment-171734352) about connecting to debugger from outside; "index" page has a list of devconsoles available, one of them is "background".

**Comment by rogerwang** [comment]
I'll see having logs from background page printed to console too.

**Comment by jonwwilkes** [comment]
@rogerwang: sounds good.  I just wasn't thinking in terms of the Chrome app, so it did not click what "background page" in the architecture description meant.

Thanks to @offshore for the screenshot clearing that up.

**Comment by rogerwang** [comment]
@jonwwilkes turns out ` --enable-logging=stderr` is needed with the new Chromium code. Will add this to FAQ.
