### ISSUE TITLE
nwjs 0.13 beta3 - plugin: false doesn't disable the built in flash player plugin

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#4257]
Hi guys, like the title says, is this happening on purpose? 
The bug i am running into is the youtube iframe api "randomly" (i can't provide a test case) ends up complaining about old version of the flash player.

I already set the plugin property of webkit  to false in package.json, this didn't help.

using 

function blockAdobeFlashPlayer(block) {
    chrome.contentSettings.plugins.set({
        primaryPattern: '<all_urls>',
        resourceIdentifier: {
            id: 'adobe-flash-player'
        },
        setting: block ? 'block' : 'allow'
    });
}

doesn't help either, is there some other more "proper" way of disabling the flash plugin? or can i somehow update the flash plugin to the latest version?

**Comment by offshore** [comment]
Maybe it's somehow related to PPAPI?
See https://support.google.com/chrome/answer/6258784?hl=en

**Comment by cTn-dev** [comment]
Thanks for the link, it might be true but since there is no way to pull out navigation/toolbar in 0.13, there is no way for me to access chrome://plugins or chrome://components to have a look at this stuff.

**Comment by offshore** [comment]
Well, you can use `navigator.plugins` to enumerate things, as described here: https://github.com/nwjs/nw.js/wiki/third-party-browser-plugins#listing-of-the-loaded-plugins

**Comment by cTn-dev** [comment]
Thanks, but how does that help me with the issue ? Can you actually disable the plugin through navigator.plugins ? As far i know that's not possible, and since the navigator.plugins returns plugin library as "pepflashplayer.dll" (which is i am guessing built into the nw.dll) there is no way for me to replace the file manually.

**Comment by offshore** [comment]
Aw, sorry, missed point a little.
The doc says about `webkit.plugins` flag that it's for *external* plugins. It might not be possible to disable integrated one. I can be wrong.

**Comment by rogerwang** [comment]
will fix this.

**Comment by cTn-dev** [comment]
Hi @rogerwang , any progress on this? i noticed that the beta-4 already runs on 48.0.2564.82, but the pepper flash is still old, is there any specific reason why the plugin wasn't updated with it ?

In the future you might consider the old flash player as security issue, because if i am viewing the version number correctly, it seems to be quite old.

Shockwave Flash 18.0 r0 vs Shockwave Flash 20.0 r0

**Comment by rogerwang** [comment]
I just fixed it in the nightly build, you can try it now. btw, the version string is wrong, the binary is actually newer than the reported version string... I'll see this too.

**Comment by cTn-dev** [comment]
Thanks @rogerwang , the plugin: false in the latest nightly build seems to work the way it should now, yay!

Regarding the version string, i guess that one will require manual updating in the future?
It would seem that youtube api just checks the version in navigator.plugins and then throws an error if flash version isn't above some minimum requirement.

**Comment by rogerwang** [comment]
I just update the version string in git. Please see the next nightly build.
