### ISSUE TITLE
nwjs 0.13 - Possible to use NPAPI silverlight plugin

### ISSUE THREAD

**Issue by Jrags87** [nwjs/nw.js#4258]
I understand that chrome has dropped support for all NPAPI plugins (flash, silverlight, etc.). My app requires silverlight, and I've been able to load NPAPI plugins with v0.12.3. Is it still possible to load these NPAPI plugins with NW 0.13?

**Comment by TateHuang** [comment]
any solutions?

**Comment by offshore** [comment]
Well... Point of no return is left (far) behind, guys.
https://productforums.google.com/forum/#!topic/chrome/ZrwCwA9724A:
> Starting in Chrome 42, NPAPI plugins like Silverlight have begun the final phase of removal, and will no longer work nor be shown in the chrome://plugins page.
http://www.chromium.org/developers/npapi-deprecation
As far as I know, there is no PPAPI version of Silverlight yet, so these plugin files are not supported.
You can help by asking such websites/webmasters to change to using modern, secure PPAPI/Pepper plugins and HTML5, which will be supported by Chrome.
