### ISSUE TITLE
nwjs 0.13 beta3 - the window subfield "icon" in package.json do not work

### ISSUE THREAD

**Issue by guhaibin1847** [nwjs/nw.js#4260]
Hello,
I find a problem that the window subfield "icon" do not work in nwjs 0.13 beta3. Here is my package.json:
```javascript
{
  "name": "test",
  "version": "0.0.1",
  "main": "index.html",
  "window": {
    "icon":"logo.png",
    "height":900,
    "width":1200
  }
}
```
In nwjs12, the window's icon will be logo.png but in nwjs 0.13 beta3 it is 
![1](https://cloud.githubusercontent.com/assets/697193/12381268/38b9ef1c-bdc1-11e5-9015-a1055ad734b2.png)
![2](https://cloud.githubusercontent.com/assets/697193/12381267/3802b392-bdc1-11e5-816c-7a271357798c.png)

**Comment by offshore** [comment]
Things with icons are complicated a little.
There is a documentation lack for all-cases-cover, the only info page currently available is [wiki about Icons](https://github.com/nwjs/nw.js/wiki/Icons), and it is talking about *icon in title bar of your app* only, not an icon in taskbar, regardless it's almost same things (for windows, at least).
So. when I ran into same issue, I found out that it's still possible to control taskbar icon, it depends not only on `window.icon` field value, **but also on window's page favicon** and it's dimensions.
All you need to do is provide an icon file of correct dimensions for your `window.icon`:
![image](https://cloud.githubusercontent.com/assets/464558/12390236/46213678-bdef-11e5-94b3-7b80b1aee8d3.png)
To achieve this I used 48x48 png file for `window.icon` field in `package.json`, and `<link rel="icon" type="image/png" href="ico16x16.png">` in page's `<head>`
.
P.S. **It's better to not rely on this behavior for now**, it's not documented, may have to change and I cannot guarantee that it is platform-independend. Also it seems that nwjs does not handle a set of icons in one .ico file correctly.

**Comment by guhaibin1847** [comment]
@offshore Thanks for your reply.It seems that 0.13.0-beta4 fix this problem.
