### ISSUE TITLE
Can I follow same thing Node-Webkit on windows?

### ISSUE THREAD

**Issue by upvishalup** [nwjs/nw.js#4264]
This link say, how to build Node Webkit on OSX(https://github.com/nwjs/nw.js/issues/69#issuecomment-9102209). Same thing I want to do on windows, many things are not clear here. 
Why downloading chromium tar ball?
Building node(https://github.com/nwjs/nw.js/wiki/Building-node-webkit) webkit. Link is broken.

Also for node webkit 0.12.3 version, I am unable to download code. 
Please can some help building window 0.12.3 node webkit on windows?

**Comment by ghostoy** [comment]
Please refer to the official document site http://docs.nwjs.io/

upvishalup <notifications@github.com>于2016年1月18日周一 14:59写道：

**Comment by upvishalup** [comment]
I followed this too. But faced lot of issue. Ubuntu, I have built successfully. Same I am try to get for Windows 64 and 32 Bits. Will keep posted here with latest one.

**Comment by upvishalup** [comment]
This document for NW.js 0.13.0, but I want to build 0.12.3. Will it work?

**Comment by ghostoy** [comment]
Oh, the old build wiki is here https://github.com/nwjs/nw.js/wiki/Building-NW.js

**Comment by upvishalup** [comment]
'[4:07:17] Still working on:
[4:07:17]   src/third_party/WebKit
Syncing projects: 100% (93/93), done.

________ running 'D:\Workspace\depot_tools\python276_bin\python.exe src/build/landmines.py' in 'D:\Workspace\N
W18'



Please follow the instructions at https://www.chromium.org/developers/how-tos/build-instructions-windows


Traceback (most recent call last):
  File "src/build/landmines.py", line 215, in <module>
    sys.exit(main())
  File "src/build/landmines.py", line 202, in main
    gyp_environment.SetEnvironment()
  File "D:\Workspace\NW18\src\build\gyp_environment.py", line 33, in SetEnvironment
    vs_toolchain.SetEnvironmentAndGetRuntimeDllDirs()
  File "D:\Workspace\NW18\src\build\vs_toolchain.py", line 34, in SetEnvironmentAndGetRuntimeDllDirs
    Update()
  File "D:\Workspace\NW18\src\build\vs_toolchain.py", line 179, in Update
    subprocess.check_call(get_toolchain_args)
  File "D:\Workspace\depot_tools\python276_bin\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\\Workspace\\depot_tools\\python276_bin\\python.exe', 'D:\\Workspa
ce\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'D:\\Workspace\\NW18\\src\\bu
ild\\win_toolchain.json', 'ee7d718ec60c2dc5d255bbe325909c2021a7efef']' returned non-zero exit status 1
Error: Command 'D:\\Workspace\\depot_tools\\python276_bin\\python.exe src/build/landmines.py' returned non-zer
o exit status 1 in D:\Workspace\NW18
Hook ''D:\Workspace\depot_tools\python276_bin\python.exe' src/build/landmines.py' took 29.04 secs

D:\Workspace\NW18>set DEPOT_TOOLS_WIN_TOOLCHAIN=0`


**I think code has been downloaded completely. I am getting above issue.  Considering fetch complete, When I am doing 'gclient runhooks` getting following error**.

`________ running 'D:\Workspace\depot_tools\python276_bin\python.exe src/tools/check_git_config.py --running-as
-hook' in 'D:\Workspace\NW18'
--------------------------------------------------------------------------------
Your gclient solution is not set to use supported git workflow!

Your 'src' solution (in D:\Workspace\NW18\.gclient):
{ 'deps_file': 'DEPS',
  'managed': True,
  'name': 'src',
  'url': 'https://github.com/nwjs/chromium.src.git@origin/nw12'}

Correct 'src' solution to use git:
{ 'deps_file': 'DEPS',
  'managed': False,
  'name': 'src',
  'url': 'https://chromium.googlesource.com/chromium/src.git'}

Please update your .gclient file ASAP.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
You are using managed gclient mode with git, which was deprecated on 8/22/13:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/n9N5N3JL2_U

It is strongly advised to switch to unmanaged mode. For more information about managed mode and reasons for it
s deprecation see:
http://www.chromium.org/developers/how-tos/get-the-code/gclient-managed-mode

There's also a large suite of tools to assist managing git checkouts.
See 'man depot_tools' (or read depot_tools/man/html/depot_tools.html).
--------------------------------------------------------------------------------

________ running 'D:\Workspace\depot_tools\python276_bin\python.exe src/tools/remove_stale_pyc_files.py src/to
ols' in 'D:\Workspace\NW18'

D:\Workspace\NW18\src>gclient runhooks
.gclient file in parent directory D:\Workspace\NW18 might not be the file you want to use
Error: There is a syntax error in .gclient
Line #13, character 18: "     "custom_deps" : { "`

**Comment by ghostoy** [comment]
The warning of managed mode doesn't matter. Just ignore it.

The last issue "Error: There is a syntax error in .gclient" seemed to be caused by a broken `.gclient` file. Please check if you modified the file by mistake.

**Comment by rogerwang** [comment]
Close since it's not an issue. Please discuss in the mailing list.
