### ISSUE TITLE
.nw Apps not working on Windows 10 with the v0.13.x builds

### ISSUE THREAD

**Issue by JustSimplyT** [nwjs/nw.js#4265]
Hi,
It seems that nw.exe doesn't run any packed .nw apps or .nw folder on the v.0.13.x builds in Windows 10, regardless if it's the sdk builds or the regular builds.
I tried the beta2, beta3 and even beta4. All give me the same results. 
It just creates 2 NWJS processes, but there is no window being made, or any output in the debug.log file.
I can't even get a default index.html with nothing but a "Hello world" to display.
No events are created in the eventmanager and can't find any errors that may give an indication of what goes wrong.
Running nw.exe without any .nw apps does work, and it shows the default grey-background nw.js window.
They work perfectly fine on the OSX builds of v0.13.x and the 0.12.x builds on Windows.

**Comment by rogerwang** [comment]
Could you please try different packaging ways? There are users run it well on Windows 10.

**Comment by castpixel** [comment]
The exact same happens to me :( It's a Construct 2 export (https://www.scirra.com/) and I have no control over the way it gets packaged. Since it happens to other nw users, I doubt Scirra is going to be the first to try and fix it. 

It just creates 2 NWJS processes, but there is no window being made.

win7 64bit here. All v.0.13.x builds are unusable, last usable one 0.12

Any ideas?

**Comment by rogerwang** [comment]
@castpixel it should be a bug we fixed in beta2. The window is displayed out of the screen and the coordinates is saved and restored in the user data dir.

**Comment by castpixel** [comment]
Thanks for getting back to me @rogerwang  ! Using beta 4 ( v0.13.0 beta 4 (Chromium 48) ), so I don't know if it's that. So just deleting the exported data dir should solve the problem? I already know that renaming the exported project.exe solves the problem (because it's exported in a new folder)

**Comment by JustSimplyT** [comment]
@rogerwang I went to ask about this in the room yesterday where I got directed to another 'hello world' example. I tried that and that magically worked, where my 'hello world' code didn't. It was the same minus the <script>tag he uses.
