### ISSUE TITLE
Toggle to enable sandbox (disable node.js) inside WebKit 

### ISSUE THREAD

**Issue by lalakiwe** [nwjs/nw.js#4266]
Hi, I'd found
> Provide toggle to disable node.js inside WebKit https://github.com/nwjs/nw.js/issues/29

which is a request long long time ago. However, it seems not work now. Since I'm using the rendering engine only, I'm wondering is it able to enable sandbox by toggling flag in manifest file?

**Comment by rogerwang** [comment]
It should be working if you set 'nodejs' to 'false' in manifest, see http://docs.nwjs.io/en/latest/References/Manifest%20Format/#nodejs

**Comment by lalakiwe** [comment]
Hello,

I've modified manifest like this:
```sh
{
  "version": "1.0.0",
  "name": "Test",
  "main": "index.html",
  "nodejs": false
}
```

However, he appended command line arguments of nw.exe as below:
```sh
"C:\Users\vince_li\Downloads\nwjs-v0.13.0-beta4-win-x64\nwjs-v0.13.0-beta4-win-x64\nw.exe" --type=gpu-process --channel="7228.0.1524996633\773608444" --no-sandbox --user-data-dir="C:\Users\vince_li\AppData\Local\Test\User Data" --supports-dual-gpus=false --gpu-driver-bug-workarounds=2,24,52 --gpu-vendor-id=0x8086 --gpu-device-id=0x0412 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=10.18.14.4264 --user-data-dir="C:\Users\vince_li\AppData\Local\Test\User Data" /prefetch:822062411
```
The **--no-sandbox** is still there?

Do I misunderstand anything?

**Comment by rogerwang** [comment]
That flag is sufficient to disable Node.js. Nothing to do with the `--no-sandbox` flag here.

**Comment by lalakiwe** [comment]
Thanks for your answer. Furthermore, if Node.js is disabled and **--no-sandbox** is still there, does it mean there is no sandbox protection of webkit?
