### ISSUE TITLE
Do you have any documentation regarding code-signing of app using nwjs 0.13

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4267]
I want to code-sign an app built using nwjs 0.13 outside mac store. I have checked documentation at following which worked perfectly in case on nwjs 0.12.3:
https://github.com/solvedio/checklists/blob/master/signing-node-webkit-app-for-mac.md

As components of nwjs folder changes in nwjs 0.13 from nwjs 0.12, do you have any documentation regarding code-signing an app using nwjs 0.13. Thank you.

**Comment by vivekgaikwad** [comment]
Need a steps like following one which works in nwjs0.12:
 Go to Terminal in the folder containing your .app
$ app="Your\ App.app"
$ identity="User ID" # (pasted from clipboard)
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/crash_inspector"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/nwjs Framework.framework"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/nwjs Helper EH.app"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/nwjs Helper NP.app"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/nwjs Helper.app"
$ codesign --force --verify --verbose --sign "$identity" "$app"
In nwjs0.13 as contents changes which frameworks and modules to be code-signed?

**Comment by vivekgaikwad** [comment]
I have created a developer certificate and code-signed following modules and frameworks but it didn't work:
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/Helpers/crashpad_handler"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/libnode.dylib"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/nwjs Framework"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/Libraries/exif.so"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/Resources/app_mode_loader.app"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Helper.app"
$ codesign --force --verify --verbose --sign "$identity" "$app"

**Comment by vivekgaikwad** [comment]
any updates?

**Comment by ghostoy** [comment]
See [MAS: Signing the app](https://github.com/nwjs/nw.js/wiki/MAS:-Signing-the-app). It was written for 0.12.x and you can try if it solves your problem.

**Comment by vivekgaikwad** [comment]
I have tried with same commands above and it works. It was issue of developer id certificate.

**Comment by vivekgaikwad** [comment]
Use following cammands for code-sign:

$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/Helpers/crashpad_handler"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework/libnode.dylib"
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Framework.framework
$ codesign --force --verify --verbose --sign "$identity" "$app/Contents/Versions/48.0.2564.82/nwjs Helper.app"
$ codesign --force --verify --verbose --sign "$identity" "$app"

Use following to command to verify your app:
codesign --force --verify --verbose --sign "$identity" "$app"

Make sure your path in terminal will be upto folder which contains nwjs binaries

**Comment by doronsever** [comment]
WOW @vivekgaikwad ! 
You do not know how much that script helped me!
Thank you so much!

@ghostoy please change the docs at https://github.com/nwjs/nw.js/wiki/MAS:-Signing-the-app to use @vivekgaikwad script.

Tested on v 0.16.0 and works perfect.

Thanks again!

**Comment by ghostoy** [comment]
@doronsever Wiki is open for anyone to editing. You can make the change ;)

**Comment by Okyne** [comment]
Any news about code signing with MacOS 10.14.6. I tried to follow the steps from [7117](https://github.com/nwjs/nw.js/issues/7117#issuecomment-520456999) without success. 

Even if each file "*.framework" "*.app" "*.xpc" "*.dylib" "*.bundle" or "*/Helpers/*" is signed and marked as `valid on disk` and `satisfies its Designated Requirement`. When I use this command line to check if the app is notarized and valid.
```
spctl --assess --type execute --verbose --raw --ignore-cache --no-cache "$APP_PATH"
``` 
I have his error : 
```
<key>assessment:authority:source</key> 
<string>Unnotarized Developer ID</string>
```
I'm completely stuck.  Any help on this will be very appreciated. 
Thx
