### ISSUE TITLE
nwjs 0.13 beta4 - App quit crash on MacOS

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4271]
Updated to latest beta4.
Everytime I close my app (nwjs with sdk tools) on MacOS 10.10.5, it will crash.

Report here: https://gist.github.com/AndryBray/002947c9e368c99eb3d0

The app is too complex to post a test case, but it's the same which one was working with nwjs 0.13 beta3
##

**Comment by timaschew** [comment]
Can you reproduce it with a  small subset of your complex app?
Other it might be not very usefull.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please try to provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
