### ISSUE TITLE
nw is not defined in nwjs-v0.12.3-osx-x64 (Getting Started

### ISSUE THREAD

**Issue by timaschew** [nwjs/nw.js#4276]
I run this example from the Getting Started: http://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/#example-2-using-nwjs-apis

nwjs-v0.13.0-beta4-osx-x64 is working fine, but 0.12.3 seems to be broken

```
$ ~/dev/tools/nwjs-v0.12.3-osx-x64/nwjs.app/Contents/MacOS/nwjs .
[5742:0119/112000:ERROR:nw_shell.cc(336)] ReferenceError: nw is not defined
    at file:///Users/anton/dev/gitCMS/index.html:12:16
[5742:0119/112000:INFO:CONSOLE(12)] "Uncaught ReferenceError: nw is not defined", source: file:///Users/anton/dev/gitCMS/index.html (12)
```

**Comment by ghostoy** [comment]
The doc site is written for 0.13.0. In 0.12.x or older version, you can use `require('nw.gui')` to replace `nw`. And the `require('nw.gui')` also works for 0.13.0 for backward compatibility. Please refer to the [wiki](https://github.com/nwjs/nw.js/wiki) for the detailed documents of previous releases.

**Comment by timaschew** [comment]
Thanks!
Sorry I did not see that. Are the old docs available anywhere?

**Comment by ghostoy** [comment]
They are on the wiki on github.
