### ISSUE TITLE
Tary can't capture mousehover event

### ISSUE THREAD

**Issue by Jetsly** [nwjs/nw.js#4281]
Tary can't capture mousehover event
##

**Comment by myccy8** [comment]
I  have the same problem

**Comment by offshore** [comment]
Can you provide minimal demo for this?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
