### ISSUE TITLE
Cannot insert breakpoint in DevTools when non-ASCII character in source

### ISSUE THREAD

**Issue by mjiricka** [nwjs/nw.js#4288]
I have following file that I load via Require.js:

**Test.js:**

    console.log('Ahoj');

Everything works fine.

After following change:

    console.log('Žluťoučký kůň!');

I cannot insert breakpoint in DevTools debugger. It looks like it depends on usage of non-ASCII characters.

Version info:
nw.js v0.12.3
io.js v1.2.0
Chromium 41.0.2272.76

**Comment by rogerwang** [comment]
This should have been fixed by 0.13.0-beta4.
