### ISSUE TITLE
node-sqlite3 not working after copyng to another machine.

### ISSUE THREAD

**Issue by persuader** [nwjs/nw.js#429]
Hi. Greetings for your great work,

I have build node-sqlite3 module using nw-gyp and msvs 1212 express and everithing works ok (win7 64bit) 

When i copy the node directory (including the node_modules) subdirectory to another machine (windows xp 32bit) i get the following error - 

Uncaught Error: The specified procedure could not be found.
C:\Documents and Settings\pentest\Desktop\node\node_modules\sqlite3\build\Release\node_sqlite3.node module.js:488

do i need to copy/install aditional software to the machine for the node-sqlite3 module to run ok? 10x in advance.

**Comment by bgSosh** [comment]
Does anyone know the reason why it needs to be compiled with VS2010? I'm having the same issue with another module.

**Comment by Mithgol** [comment]
I am not 100% sure, but it seems that the newer version of MSVS adds a dependency that does not exist on older Windows.
