### ISSUE TITLE
App.createShortcut() is not a function in nw.js 0.13.beta4

### ISSUE THREAD

**Issue by bjoernneumann** [nwjs/nw.js#4290]
Using CreateShortcut from here (https://github.com/nwjs/nw.js/wiki/Notification) is not possible any more.

**Comment by jtg-gg** [comment]
@bjoernneumann that function was created so we can have native widows notification works.
but now as nw13, the notification system is using the google chrome

**Comment by bjoernneumann** [comment]
@jtg-gg ok. So do you know a way to set an explicit AppUserModelID, or how to retrieve it within an app? For now they seem to be autogenerated, even with an manually created IShellLink. (e.g. _crx_ccngaplnjapopagbabkjcegndeflcehh).

**Comment by bjoernneumann** [comment]
It is retrieveable by
`var myUserModelAppID = '_crx_' + chrome.runtime.id`

**Comment by jtg-gg** [comment]
@bjoernneumann I'm not sure how chrome generate the appID
btw what are you trying to do ?

**Comment by bjoernneumann** [comment]
@jtg-gg It can be influenced by the key parameter in the manifest. But just reading the current one is ok.
I need the AppUserModelID to externally add Jumplist tasks to my app. This works now by handing the chrome.runtime.id over to my helper.exe.
It's similar to what is done in chrome/browser/jumplist_updater_win.cc  by JumpListUpdater::AddTasks.
