### ISSUE TITLE
always_on_top is ignored in package.json - nw.js 0.13.beta4

### ISSUE THREAD

**Issue by RafalR** [nwjs/nw.js#4292]
`always_on_top` property doesn't work when it is set in the file package.json. It works properly only when you open new windows using scripts. I'm using an additional html file with the script to fix it:
```html
<script>
nw.Window.get().hide()
nw.Window.open('index.html',{'always_on_top':true})
</script>
```

**Comment by rogerwang** [comment]
Thanks for reporting. Fixed in git and will be available in the next nightly build.
