### ISSUE TITLE
Window open 'always-on-top': true & show: false

### ISSUE THREAD

**Issue by fritx** [nwjs/nw.js#4295]
``` js
Window.open({
  'always-on-top': true,
  show: false 
})
```

This will make `show: false` ignored, the window will show.
And I have to move the logic to:

``` js
win.setAlwaysOnTop(true)
```

nw 0.12.3
Thanks!
##

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows/Linux with nwjs-sdk-v0.22.0. If set `show: false`, the window doesn't show.
`nw.Window.open("http://www.baidu.com", {"always_on_top": true, "show": false},function(win){console.log(win);});`

**Comment by Christywl** [comment]
close until there is more information.
