### ISSUE TITLE
[nw.js 0.13.beta3 & beta4] After press the “command+h” to minimize, but unable to recover

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4296]
[nw.js 0.13.beta3 & beta4] After press the “command+h” to minimize, but unable to recover.

Must exit and restart.

Mac OSX 10.11.2

**Comment by ghostoy** [comment]
Will look into this issue.

**Comment by rogerwang** [comment]
fixed in git and will be available in the next nightly build.
