### ISSUE TITLE
[mac] Need a way to differentiate Cmd-Q from closing window(s) [$500 awarded]

### ISSUE THREAD

**Issue by Flamefork** [nwjs/nw.js#430]
Common pattern for apps is to hide on window close but quit on `Menu->Quit` (Cmd-Q).

Currently, Quit menu item calls `closeAllWindows`, thus triggering `close` event for each window. There seems to be no straight way to distinguish between this two events.
##

**Comment by varshneyjayant** [comment]
Thanks guys! this saved my day :)
