### ISSUE TITLE
win10 frameless fullscreen gray border

### ISSUE THREAD

**Issue by shenanigans** [nwjs/nw.js#4301]
When a frameless window is fullscreen in win10, it draws a light gray border 8px wide just outside the screen's visible area when it's focused. This has two very irritating consequences:
1. With multiple monitors, the gray border is visible on your adjacent monitors.
2. Whether focused or not at the time, fullscreen windows include the border area in their dimensions and therefor misrepresent their size by +16 X +16.
##

**Comment by offshore** [comment]
There is [a notice in the docs about `window.fullscreen`](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#fullscreen). Maybe it's better to use [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)?
(I can be wrong about your case, I don't have Win10 to check out that, maybe it's really a problem).

**Comment by shenanigans** [comment]
Naw, the Fullscreen API is a bit closer to nw's Kiosk Mode. I (and the docs you linked) are just talking about when a window is set to span a physical monitor by clicking the lil box icon. In Windows and I think whatever nw calls "linux" (gtk2+?) this involves interacting with the OS as there is a concept of a fullscreen state. If I have all this right OSX doesn't do fullscreen so the bug shouldn't exist there, it's just the window in its normal state automatically sized to fit a Screen.

**Comment by Christywl** [comment]
I don't see the gray border in the frameless fullscreen window on Windows 10 with nwjs-sdk-v0.22.1.
```
{
    "name": "4301",
    "main": "index.html",
	"window":{
	  "frame": false,
	  "fullscreen": true
	}
}
```
Is this issue still reproduced for you? If so, could you please provide your sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by shenanigans** [comment]
This appears to be resolved as of............. no later than 0.21.2 Thanks!
