### ISSUE TITLE
Is it possible to have nw.js as a subview in a more complex view hierarchy?

### ISSUE THREAD

**Issue by zsszatmari** [nwjs/nw.js#4306]
Hi!

  I cannot seem to find this in the documentation. Is it possible to - instead of creating it's dedicated window, but with as little hackery as possible - embed nw.js as a subview in a view hierarchy? Under OS X, one would get an NSView *, under Windows, one would perhaps specify parent's HWND when creating as child window.
  Thanks!
##

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
