### ISSUE TITLE
How to make a screen capture

### ISSUE THREAD

**Issue by weiyukun** [nwjs/nw.js#4308]
Hello.
Now,I am in trouble when i am making an im app.This app has a function that sending a screen capture picture.I have researched somehing about 'capturePage' and 'DesktopCaptureMonitor',but these can not select an area what i need in the following pic.Could u tell some API or library can help me finish it.Thank u ver much~
![qq 20160125232055](https://cloud.githubusercontent.com/assets/16688334/12555102/80e133dc-c3ba-11e5-8153-2d86e13ccd2b.png)

**Comment by weiyukun** [comment]
hello?

**Comment by weiyukun** [comment]
hellohello！！

**Comment by ghostoy** [comment]
Two options:

* Capture entire screen and show it on a fullscreen window. Use js to draw UIs for clipping this image.
* Show a transparent fullscreen window. Use js to draw UIs for clipping. Capture entire screen and clip as requested.

**Comment by ghostoy** [comment]
Oh another option: find a native screen capture tool and execute it with Node `child_process.exec` API.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
