### ISSUE TITLE
"node-main"在Mac启动不了进程

### ISSUE THREAD

**Issue by owen-hong** [nwjs/nw.js#4309]
Mac系统：10.10.5
Nw：v0.12.3和v0.13.0

在windows下测试均是正常启动，不过有时候windows经常出现node-main启动失败，要经常尝试打开数次nw才能正常运行程序。

在Mac下面node-main完全无法启动进程。
##

**Comment by offshore** [comment]
You definetely should post in english here.

**Comment by Christywl** [comment]
Please use English so all users can read, or the issue will be closed directly.
