### ISSUE TITLE
Live builds page is not working due to CORS

### ISSUE THREAD

**Issue by dogancelik** [nwjs/nw.js#4314]
Live builds page ([dl.nwjs.io/live-build/](http://dl.nwjs.io/live-build/)) is not working due to CORS error as logged in the console by the page.

---

In both Chrome and Firefox, the page returns HTML content with JavaScript and CSS despite the `404 Not Found` in the response header.

Other related headers on `http://dl.nwjs.io/live-build/`:

```
x-amz-error-code:NoSuchKey
x-amz-error-detail-Key:live-build/index.html
x-amz-error-message:The specified key does not exist.
```

---

And in Firefox, you get this log saying that XML can't be loaded due to CORS.

```
Did you enable CORS? (live-build:316:25)
```

If you look at the S3 request `http://nwjs.s3-us-west-2.amazonaws.com/?delimiter=/&prefix=live-build%2F` and check the response header, there is no CORS header allowing such request.
**Edit:** Ajax request is actually **_http:_**
##

**Comment by rogerwang** [comment]
It's working for me

**Comment by dogancelik** [comment]
After some research I found that the XMLHttpRequest is blocked by EFF add-on HTTPS Everywhere because the page makes a HTTP request instead of a HTTPS request.

On line 289:

```
return '//' + bucketName + '.' + bucketEndpoint + '/' + requestUri;
```

should be replaced with:

```
return 'https://' + bucketName + '.' + bucketEndpoint + '/' + requestUri;
```

**Comment by Christywl** [comment]
http://dl.nwjs.io/live-build/ works well for me.

**Comment by dogancelik** [comment]
It works if you disable HTTPS Everywhere, although using `https://` rather than `//` is more secure.
