### ISSUE TITLE
debian, "/usr/bin/node" no longer exists; now it is "/usr/bin/nodejs"

### ISSUE THREAD

**Issue by eriksank** [nwjs/nw.js#4315]
The npm-based `nw` installation fails on debian/jessie:

    $ sudo npm install -g nw
    > nw@0.12.3 postinstall /usr/local/lib/node_modules/nw
    > node scripts/install.js
    sh: 1: node: not found
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian

It can be fixed using a workaround:

    sudo ln -s /usr/bin/nodejs /usr/bin/node

From there on, the postinstall script will run properly:

    /usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw
    nw@0.12.3 postinstall /usr/local/lib/node_modules/nw
    node scripts/install.js

In my impression, the post install script should check if either `/usr/bin/node` or `/usr/bin/nodejs` exists and use the version reported as existing. The `nw` installer may assume elsewhere that the node executable has been installed as `node` while this is no longer the case in the Debian distro.

**Comment by rogerwang** [comment]
This is not provided officially by us. Please report the issue to that module's maintainer.
