### ISSUE TITLE
"node-main" In the Mac can not start the process

### ISSUE THREAD

**Issue by owen-hong** [nwjs/nw.js#4316]
Mac:10.10.5
Nw：v0.12.3 and v0.13.0

Under Windows tests were normal start, but sometimes often node-main windows failed to start, we should always try to open the program to run properly several NW.

In the following node-main Mac completely unable to start the process
##

**Comment by owen-hong** [comment]
？？

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
