### ISSUE TITLE
Communicating between multiple instances of Node webkit

### ISSUE THREAD

**Issue by komab** [nwjs/nw.js#4317]
With respect to node webkit instance and an application running on it. Is there a way for **an instance A running an application A to know about the other instance B running application B**?

The use case is for e.g to have the main app A know about app B's time to load the page,profiling information like time for loading, scripting, rendering, painting,etc...and display those statistics in app A's view. This is just a probable example, I know it can be seen in the developer tools for each node webkit window.

Just want to know if an instance can be aware of the the app running in the other instance and get such kind of information as described above. If this is possible how can this be achieved.
##

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
