### ISSUE TITLE
chartset problem when debugger

### ISSUE THREAD

**Issue by hubbly** [nwjs/nw.js#4319]
I use nw to dev a application
If I add script ref code on the html file like "<script src=myjs.js />", when debug charset is all right
If I use extjs's method to create object like Ext.create("MyJsClass"), when debug charset is not all right

Is there any idea to solve this problem?

**Comment by rogerwang** [comment]
which version are you using?

**Comment by hubbly** [comment]
I use v12.3 try again, this problem is all the same

**Comment by offshore** [comment]
Maybe connected with #4288

**Comment by rogerwang** [comment]
This is fixed in 0.13.0 beta.

**Comment by hubbly** [comment]
beta version does not have toolbar option?
I want try 0.13.0 to debug my application, is there any way to do it?

**Comment by offshore** [comment]
@hubbly, 0.13 does not have toolbar at all, having this feature being deprecated. Use SDK builds for debug.

**Comment by hubbly** [comment]
@offshore ask a little, why not add toolbar in beta versions, :)
