### ISSUE TITLE
nwsaveas='filename.txt' is not working

### ISSUE THREAD

**Issue by AllencxWang** [nwjs/nw.js#4320]
I am using nw.js v0.12.2 on osx to create a "save as" file dialog by following the instruction(https://github.com/nwjs/nw.js/wiki/File-dialogs#save-file), I set my input tag like this: 
`<input id="fileDialog" type="file" accept=".txt" style="display:none" nwsaveas="filename.txt">`
When I click on that input element, the file dialog comes out with Untitiled.zip as the default file name.
I've tried combinations like using nwsaveas w/wo accept/style attribute but neither work.
Any idea?
##

**Comment by KSchreyer** [comment]
Hi,
it seems that there is a regression in v0.20.0 regarding the nwsaveas attribute.

When I'm using version **v0.19.2-linux-x64** the _nwsaveas="filename.txt"_ attribute is working and the attributes value is set as the default filename in the opened "Save as"-dialog.
But when I'm running the same application with version **nwjs-sdk-v0.20.0-linux-x64**, the default filename is **not set** anymore in the opened "Save as"-dialog.

Cheers,
Kai

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.22.0. The filename could be set in the 'Save As'.
`<input id="fileDialog" type="file" accept=".txt" nwsaveas="filename.txt">`
Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information.
