### ISSUE TITLE
Does nw.js support raspberry pi  armv7?

### ISSUE THREAD

**Issue by kscorpio** [nwjs/nw.js#4321]

**Comment by losywee** [comment]
Yes, but you need recompile.

**Comment by rogerwang** [comment]
close as duplicate with #193

**Comment by jalbam** [comment]
Hello,

I have just created a repository with the node-webkit binary port that runs on Raspbian, tested and working on Raspberry Pi 1 and Raspberry Pi 3 so it is ARMv6 and ARMv7 compatible.

Here you can check it: https://github.com/jalbam/nwjs_rpi

**Comment by sonicmouse** [comment]
@jalbam -- You haven't updated that in a year -- Are you going to anytime soon? Or can we all assume it's a dead project?
