### ISSUE TITLE
ShowDevTools crashes when called in an app packaged for the Mac App Store

### ISSUE THREAD

**Issue by bowringjb** [nwjs/nw.js#4327]
Well everything I need to say is in the title I think, I have an app which I have packaged according to the wiki guidelines for mac app store submission and it is accepted and uploaded to iTunes connect without any trouble. The issue is that my app allows access to the DevTools via a menu option. When I call ShowDevTools in a development environment everything works fine, but once I have packaged and signed my app for the Mac App Store any attempt to open the Dev Tools just causes a crash.
Is this normal behaviour? Is there any way round it?
Any advice is truly appreciated.
##

**Comment by DuBistKomisch** [comment]
:+1: We're also seeing this on our app. Recently switched from just distributing a `.dmg` to a signed `.pkg`, now it crashes every time we try to call `showDevTools` in the installed app. Still works fine as a `.app` before being packaged though.

Here's an OS X debug report: [pastebin link](http://pastebin.com/966gekyk) (including here goes over max character limit...)

**Comment by Christywl** [comment]
@bowringjb , is it still reproduce on the latest nwjs? If so, could you please upload the crash dump file?

**Comment by Christywl** [comment]
close until there is more information.
