### ISSUE TITLE
VPN connection

### ISSUE THREAD

**Issue by TransferFantasy** [nwjs/nw.js#4331]
Is there any way of getting VPN connection inside NW app?
I want only requests from NW app to go through VPN, not system-wide.

**Comment by losywee** [comment]
Yes, you can, but you need export an API for NW.

**Comment by makkesk8** [comment]
Popcorntime used a vpn client inside their app, take a look at their source and see how they did it.

**Comment by TransferFantasy** [comment]
I looked inside popcorn.io, but everything vpn.js does is
`var vpnClient = gui.Window.open('https://client.vpn.ht/', {
            position: 'center',
            title: 'VPN.HT',
            icon: 'src/app/images/icon.png',
            focus: true,
            toolbar: false,
            resizable: false,
            show_in_taskbar: false,
            width: 500,
            height: 500
        });`
This url gives 403 (

**Comment by TransferFantasy** [comment]
> losywee commented 6 hours ago
> Yes, you can, but you need export an API for NW.
How can I do this?

**Comment by shaynem** [comment]
OpenVPN has a socket interface so you can just nodejs to control the
management port

This should set you on the right track

alternatively you can just use the command line to start OpenVPN process
with a config file from nodejs also.

you can then make it just route a specific IP for example or use a proxy
server in nwjs and route that proxy only via OpenVPN that way all traffic
from the app goes via the VPN encrypted

**Comment by makkesk8** [comment]
@TransferFantasy That's weird... Looks like they removed the feature... Before you could enter in vpn details and hit connect basically. That's what I remember at least.

**Comment by rogerwang** [comment]
please submit questions to mailing list.
