### ISSUE TITLE
nwjs 0.13 - Webcam video - canvas problems (Mac OS 10.6)

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4332]
With latest upgrade to nwjs 0.13 / chrome 48 there is a new problem ** only on Mac OS 10.6**.
When I try to take a photo from webcam to video/canvas, the picture will be "broken".

I've tested even on Google Chrome 48.0.2564.97 (64-bit).

Test here (with a MacOS 10.6.x)
 https://jsfiddle.net/vh1socdc/

I know it's legacy system, is there anybody who could test this bug? Any workaround to fix it?

Thank you

**Comment by AndryBray** [comment]
Same issue on Chrome beta 49.0.2623.28 (64-bit)

**Comment by AndryBray** [comment]
Tested on latest nwjs 0.14 with Chrome 50 beta... same problem!

**Comment by rogerwang** [comment]
Do you mean the bug is also on upstream Chromium browser? If so, please report this bug to Chromium project.
