### ISSUE TITLE
How to decrease the app size?

### ISSUE THREAD

**Issue by losywee** [nwjs/nw.js#4333]
NW packed is too large, how to decrease the app size? Thanks. I don't want to use upx.

**Comment by ghostoy** [comment]
Choose a different build flavor. See
http://docs.nwjs.io/en/v0.13.0-beta4/For%20Users/Advanced/Build%20Flavors/

Losywee, An open source fan. <notifications@github.com>于2016年1月29日周五
20:49写道：

**Comment by losywee** [comment]
Thanks.
