### ISSUE TITLE
[win] ninja: error: unknown target 'nwjs' when building nwjs-13 on Windows server 2008 R2

### ISSUE THREAD

**Issue by guhaibin1847** [nwjs/nw.js#4337]
Hi,
I have confronted some problems when building nwjs-13 on Windows Server R2. I follow the steps in [Building NW.js](http://docs.nwjs.io/en/v0.13.0-beta4/For%20Developers/Building%20NW.js/), but something was wrong. Here are the problems:
### 1. when I ran "ninja -C out/Debug nwjs" command, I got these message : 
```
ninja: error: unknown target 'nwjs'
ninja: Entering directory `out/Release'
```

### 2. when I ran "gclient runhooks --force" command , I got these message : 
```
Updating projects from gyp files...
Traceback (most recent call last):
  File "src/build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
  File "src/build/gyp_chromium.py", line 336, in <module>
    sys.exit(main())
  File "src/build/gyp_chromium.py", line 323, in main
    gyp_rc = gyp.main(args)
  File "E:\nwjs\src\tools\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\nwjs\src\tools\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "E:\nwjs\src\tools\gyp\pylib\gyp\generator\ninja.py", line 2403, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "E:\depot_tools\python276_bin\lib\multiprocessing\pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "E:\depot_tools\python276_bin\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
AssertionError: make_global_settings needs to be the same for all targets. [] vs . [['CC', 'third_party/llvm-build/Release+Asserts/bin/clang-cl']]
过程试图写入的管道不存在。
过程试图写入的管道不存在。
Error: Command 'E:\\depot_tools\\python276_bin\\python.exe src/build/gyp_chromium' returned non-zero exit status 1 in E:\nwjs
Hook ''E:\depot_tools\python276_bin\python.exe' src/build/gyp_chromium' took 69.84 secs
```
The english version of “过程试图写入的管道不存在” is "The process tried to write to a nonexistent pipe."

**Comment by ghostoy** [comment]
>> CLang is the build tool used by non-Windows platforms. On Windows, it’s not supported yet. You need to run set GYP_DEFINES="clang=0" to disable CLang on Windows before going to next steps.

**Comment by guhaibin1847** [comment]
@ghostoy Thanks for you reply! set GYP_DEFINES="clang=0" solved my problem, but when I ran "ninja -C out/Debug nwjs" command again and here comes another problem: the building program stopped at  : 

```
[127/20395] RULE net_derived_sources: dafsa_d85f4f8c30faaed8b5a9a15112b26930 base\registry_controlled_domains\effective_tld_names_unittest4.gperf
ninja: build stopped: subcommand failed.
```

By the way , I want my nw application to play mp3 media, so I need to build nwjs follow the steps in [Enable Proprietary Codecs](http://docs.nwjs.io/en/v0.13.0-beta4/For%20Developers/Enable%20Proprietary%20Codecs/)

**Comment by guhaibin1847** [comment]
@ghostoy My OS and VS2013 are all Chinese Simplified version. Can that cause any problem?

**Comment by ghostoy** [comment]
You should see the error before the progress line. And Chinese version should be ok.

**Comment by guhaibin1847** [comment]
@ghostoy Hi, I update my vs2013 to vs2013 with update4 and the "ninja: build stopped: subcommand failed" did not happen. But when the progress come to "CXX obj\third_party\node\src\node.tls_wrap.obj" the **link.exe** consumed all memory of my server and then hang at this point. could you give me some suggestion?

**Comment by guhaibin1847** [comment]
@ghostoy  By the way, I build nwjs on Aliyun server with 4 core CPU and 8G memory .

**Comment by guhaibin1847** [comment]
@ghostoy Thank for your help.I update my vs2013 to vs2013 with update 4 and solve the problem.
