### ISSUE TITLE
Audio element setSinkId does not work

### ISSUE THREAD

**Issue by jasonmcaffee** [nwjs/nw.js#4340]
Creating a new audio element, then setting it's sinkId, does not result in the sound playing through the selected device.  The sound continues to play through the default device.

Flags passed:

```
--enable-blink-features=EnumerateDevices,AudioOutputDevices
```

Fetching available output options works via navigator.mediaDevices.enumerateDevices()
Creating an Audio element, then setting the sinkId via

```
            this.audioEl = new Audio();
            this.output = this.getAudioContext().createMediaStreamDestination();
            this.audioEl.src = URL.createObjectURL(this.output.stream);
            this.audioEl.play();
            this.audioEl.setSinkId(deviceId);
```

With appropriate flags set in Chrome, this behavior works, but does not appear to in NW.js
##

**Comment by matthieusieben** [comment]
Do you still have this issue ? I've got a similar problem in Chrome (52) and my workaround was to do:
```js
element.setSinkId('default').then(() => element.setSinkId(sinkId))
```

**Comment by sporsh** [comment]
I've also had issues with setSinkId in nw.js recently where I needed to change the sink after a video had started playing.

Briefly setting the `src = ''` before calling `setSinkId()` and then re-setting the `src` worked for me in this case.

Worth noting that this workaround was not necessary in chrome of the same chromium version (nw.js v0.17.6)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by whatisor** [comment]
> Do you still have this issue ? I've got a similar problem in Chrome (52) and my workaround was to do:
> 
> ```js
> element.setSinkId('default').then(() => element.setSinkId(sinkId))
> ```

Not really need to reset, this also works
      setTimeout(()=>
        element.setSinkId(sinkId))
      ,0)
      
     I wonder why

**Comment by whatisor** [comment]
I found issue related to srcObject updated after setSinkId in my case
