### ISSUE TITLE
Couldn't load libexif

### ISSUE THREAD

**Issue by greasynose** [nwjs/nw.js#4343]
I download  nw.js-v0.13.0-beta4-win-x64.zip, extract it and add the director to the PATH.
when I excute my project in CMD, it show that " This webpage is not available".
Open the debug.log, found an error, "Couldn't load libexif. 126". 
##

**Comment by offshore** [comment]
Could you provide minimal demo?

**Comment by Smurf-IV** [comment]
Beta 5:
Do not specify an icon in package.json
Windows x64
```
[0201/130236:ERROR:image_metadata_extractor.cc(112)] Couldn't load libexif. 126
```
Embedded shows correctly, then is immediately replaced with a file icon in the taskbar.
_Nothing to do with opening websites._

**Comment by janRucka** [comment]
For me all the time I open nw.exe (nwjs-sdk-v0.13.0-beta6-win-x64) in debug.log file I got:

[0222/112726:INFO:nw_package.cc(175)] "C: \nw13test\nw.exe"
[0222/112726:ERROR:image_metadata_extractor.cc(112)] Couldn't load libexif. 126

Don't know whether error message can be ignored or 'libexif.dll' is really missing (when nwjs is build 'libexif.dll' is available)...

**Comment by brandousov** [comment]
I have the same error in NW-v0.13.0-b7-ia32 for Windows.

**Comment by gwicksted** [comment]
Even occurs in the nwjs-sdk-v0.13.0-win-x64 for Windows (10) with an icon specified in the package.json but does not exist on disk.  If the icon is specified and exists, no error is logged.

**Comment by Christywl** [comment]
I don't see this error in my test with nwjs-sdk-v0.22.0, could you please try the latest nwjs build? If still reproduce, please upload a sample.

**Comment by Christywl** [comment]
close until there is more information.
