### ISSUE TITLE
nw13-b4 webview mouse middle button click ,crash

### ISSUE THREAD

**Issue by wzquyin** [nwjs/nw.js#4346]
use webview tag in my app,when i middle click the link in webview,the nw crash......it seems a bug
##

**Comment by wzquyin** [comment]
And ....click any links in nwapp with middle button,it's crash too

**Comment by rogerwang** [comment]
It works for me. Could you please try the latest nightly build?

**Comment by Christywl** [comment]
@wzquyin , it also works well for me. Please try the latest nwjs build, if still reproduce, please upload your tests.

**Comment by Christywl** [comment]
close until there is more information.
