### ISSUE TITLE
nw.js crashes when browsing a website

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#4347]
When using the latest  nw.js win 64 builds, both 12 and 13,  nw.js always crashes within 10-15 minutes of browsing The Guardian International website and looking at pictures in maximised mode. 

Here's how to reproduce:

1. Unpack the  latest nwjs build, 12 or 13.

2. Start nw.exe

3. If nw 12, open http://www.theguardian.com/international in it by typing in address bar. If nw13, press F12 to open dev tools and then do location.href='http://www.theguardian.com/international' from console and then close dev tools.

4. Just browse website and in articles that have photos, click "circle with arrows" icon in upper right corner of the photo, to launch the photo viewer. Go through all the photos, click "i" to open info and then just close, go to some other article and repeat everything.

5. Within 10-15 minutes of browsing, nw.js will just disappear

**Comment by krneticz** [comment]
Just tried with the latest nwjs 13 beta 5, and it's the same. I managed to kill it in a way described above within 3 minutes.

**Comment by krneticz** [comment]
Roger,

can you please let me know what is the status of tis issue and when it might be resolved?

Thanks a lot!
Zoran

**Comment by rogerwang** [comment]
I did some test as you said but cannot reproduce it. I guess I didn't do it long enough. Will try it again. Could you please send me the crash dump file (.dmp)?

**Comment by tarva** [comment]
It happen to me also. I can reproduce that, and here is dump file in attachment.
[nw-guardian-reproduced-dump file.zip](https://github.com/nwjs/nw.js/files/140386/nw-guardian-reproduced-dump.file.zip)

**Comment by krneticz** [comment]
Roger,

is there anything else that you need regarding this issue? We have client waiting for this bug to be fixed.

Thanks,
Zoran

**Comment by rogerwang** [comment]
a similar issue of #4422 was just fixed. Please wait for the next nightly build and try again.

**Comment by rogerwang** [comment]
nightly build with the fix: http://dl.nwjs.io/live-build/03-08-2016/8376d68-2c53f2b-3d99a78-93e6ec5

**Comment by krneticz** [comment]
This one is fixed, but not completely. Now it don't crash nwjs, but (lot less often then before) still causes trouble: from time to time, webpage goes completely black and in dev tools I get message that dev tools are disconnected from the page. If I do Ctrl+R in dev tools it reload site and it can be used again... until it black out. See attachment.
<img width="1680" alt="screen shot 2016-03-08 at 10 17 25 am" src="https://cloud.githubusercontent.com/assets/281657/13613981/a2d9430a-e56e-11e5-834a-e3ab747497f1.png">

**Comment by krneticz** [comment]
Update: issues that I have reported are happening only when dev console is opened.
