### ISSUE TITLE
BUG :nw13-b5 Webview Permission Request doesn't work

### ISSUE THREAD

**Issue by wzquyin** [nwjs/nw.js#4348]
I set webkit.plugins:true ,
 webview.addEventListener("permissionrequest", function (evt) {

```
            evt.request.allow();

        });
```

It doesn`t work when i need flash player ppapi version
But in nw13-b4,It works well
##

**Comment by ghostoy** [comment]
According to the official doc, the permissionrequest is an _enum of "media", "geolocation", "pointerLock", "download", "loadplugin", "filesystem", or "fullscreen"_. It is NOT related to permissions inside a plugin, which should be managed by flash runtime.

**Comment by wzquyin** [comment]
So how can i make flash run?
It says "Adobe flash player needs your permission to run".

**Comment by Christywl** [comment]
@wzquyin , could you please try the latest nwjs? If still reproduce, please provide your tests for us to reproduce it.

**Comment by Christywl** [comment]
close until there is more information.
