### ISSUE TITLE
Why can't node-webkit support mp3/mp4 file playback?

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#4353]
Why can't node-webkit support mp3/mp4 file playback?
Should not be a technical problem, right?

**Comment by abhijeetk** [comment]
Due to licensing issues node webkit doesn't support mp4.
https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-(H.264)-using-the--video--%26--audio--tags.

**Comment by rogerwang** [comment]
yeah. it's the license issue. and you can rebuild the binary according to our guide if you are free with the license.
