### ISSUE TITLE
Unable to play audio/video with nwjs0.13

### ISSUE THREAD

**Issue by abhimanyubind** [nwjs/nw.js#4355]
I have tried to use video tag in main.html. But the video is not working. 

main.html:
`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" style="width:100%;height:100%;">
 	<head>
	  	<title>Testing project</title>
	</head>
	<body>
		<h1> Hello, This is Test Project</h1>
		<video width="400" controls>
  			<source src="http://dev1.browwwse.com/ticket/cometchat/SampleVideo.mp4" type="video/mp4">
  		</video>
	</body>
</html>`

package.json:

{
  "main": "main.html",
  "name": "TestApp",
  "title": "TestApp",
  "description": "A desktop application for chat",
  "version": "2.0",
  "window": {
    "title": "TestApp",
    "width": 350,
    "height": 540,
    "icon": "icon.png"
  }
}

Can anyone help me to play video in nwjs0.13

**Comment by abhijeetk** [comment]
node webkit doesn't support MP4.
Refer : https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-(H.264)-using-the--video--%26--audio--tags.

**Comment by rogerwang** [comment]
see also http://docs.nwjs.io/en/v0.13.0-beta5/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by Bigmacbook** [comment]
As a web developer its too cumbersome to try learn how to compile Proprietary Codecs. I use to get ffmpegsumo.dll from chrome installation but they no longer seem to be there.

mp3 and mp4 support is a must for me.

Might have to either stay with 0.12 or move to electron
