### ISSUE TITLE
Crash with malloc error on new Buffer(ascii, 'base64')

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#4357]
Our app crashes after running for random period of time (minutes to hours)  when executed under nw13. We observed it with all the alpha3 - beta5 versions on Mac OS X (El Capitan, currently 10.11.3).
The same javascript codebase runs without any issues under last few releases of nw12 for days or weeks.
There is no much information available in the logs, just the following:

------------------------------------------------------------------------------------------------------------------------
[0203/134613:INFO:nw_package.cc(175)] /.../node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ./dist
...
nwjs Helper(7995,0x7fff7732f000) malloc: *** error for object 0x13df3e1a4000: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Received signal 6
 [0x00010942861a]
 [0x7fff98d65eaa]
 [0x7fff56f2fc60]
 [0x7fff8afb86e7]
 [0x7fff87356f9c]
 [0x000113e9b481]
 [0x000113e9bbcd]
 [0x00010a6e2763]
 [0x00010a705c06]
 [0x00010a70b001]
 [0x31528d70b61b]
[end of stack trace]
------------------------------------------------------------------------------------------------------------------------

We don't see any particular pattern in amount of time or specific logic that is being executed at the time of those crashes, the app just exits and prints this malloc error.

Are there any instructions available on how to troubleshoot / provide better crash reporting for this type of errors?

Regards,
Alex

**Comment by rogerwang** [comment]
Could you please send a sample to reproduce this? The crash dump file in the user data dir would also be useful.

**Comment by arudnev** [comment]
Roger, I've tried to reproduce it on a small test / demo data sets (the app works with binary files, IndexedDB, network, crypto, keeps quite a bit of data in memory), but no luck. 
I'm going to write some script to generate higher volumes of test data / simulate higher load to create memory pressure, and once I can reliably cause crashes on something that I can make easily accessible I'll share the crash dumps and provide instructions on how to reproduce.

**Comment by arudnev** [comment]
[nwjs-issue-4357.zip](https://github.com/nwjs/nw.js/files/140853/nwjs-issue-4357.zip)

It seems that all is needed to reproduce is to execute the following javascript, where variable "data" has some magic properties: new Buffer(data, 'base64')

The same code works fine when executed from node.

Here is sample output:

node --version && npm --version && node index.js && npm install && npm start
v5.6.0
3.7.4
buffer length: 24160

> nw@0.13.0-beta6sdk postinstall /Users/alex/WS/nwjs-issue-4357/node_modules/nw
> node scripts/install.js

nwjs-issue-4357@0.0.1 /Users/alex/WS/nwjs-issue-4357
└── nw@0.13.0-beta6sdk

npm WARN nwjs-issue-4357@0.0.1 No repository field.
npm WARN nwjs-issue-4357@0.0.1 No license field.

> nwjs-issue-4357@0.0.1 start /Users/alex/WS/nwjs-issue-4357
> nw --version && nw .

NWJS 48.0.2564.109
[0222/102001:INFO:nw_package.cc(175)] /Users/alex/WS/nwjs-issue-4357/node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs .
[12851:32515:0222/102001:WARNING:address_sorter_posix.cc(378)] FromSockAddr failed on netmask
[12851:32515:0222/102001:WARNING:address_sorter_posix.cc(378)] FromSockAddr failed on netmask
[12851:32515:0222/102001:WARNING:address_sorter_posix.cc(378)] FromSockAddr failed on netmask
nwjs Helper(12855,0x7fff7732f000) malloc: *** error for object 0x33105acc8000: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Received signal 6
 [0x00010a40b69a]
 [0x7fff98d65eaa]
 [0x000000000006]
 [0x7fff8afb86e7]
 [0x7fff87356f9c]
 [0x000114e9ce51]
 [0x000114e9d59d]
 [0x00010b6c6653]
 [0x00010b6e9af6]
 [0x00010b6eeef1]
 [0x3e6911e0b61b]
 [0x3e6911fb263e]
 [0x3e6911fb23f4]
 [0x3e6911e35075]
 [0x3e6911fb2123]
 [0x3e6911e37164]
[end of stack trace]
[12851:1295:0222/102002:WARNING:launcher.cc(248)] Extension does not provide a valid file handler.

**Comment by arudnev** [comment]
I just tried the sample code on 0.13.0-rc3 and live builds, still crashes with the same error. 
It crashes on Windows as well, even though I don't see anything in the output

Current workaround is to either use pure-javascript base64 lib to convert between ascii string and Buffer or Array / ArrayBuffer, or a simple non-optimized hack similar to this:

```javascript
/**
 * convert base64 encoded string to bytes
 *
 * @return (Uint8Array) binary data
 * @param ascii (String) base64 encoded string
 */
function atob(ascii) {
  // return new Uint8Array(new Buffer(ascii, 'base64'));
  let decoded = window.atob(ascii);
  let size = decoded.length;
  let array = new Uint8Array(size);
  for (let i = 0; i < size; ++i) {
    array[i] = decoded.charCodeAt(i);
  }
  return array;
}
```
Unfortunately, those workarounds will not work with 3rd party libraries that call new Buffer(encoded, 'base64'), so it would be great to fix it before GA release.

**Comment by rogerwang** [comment]
Will look into it.

**Comment by rogerwang** [comment]
Fixed with a workaround and will be available in the next nightly build.

Root cause is Node is just mapping v8's arraybuffer allocator API to malloc/free, but Chromium uses a heap. It's unified to Chromium's but realloc() is left behind.
