### ISSUE TITLE
nw-gyp rebuild error

### ISSUE THREAD

**Issue by bgobi1991** [nwjs/nw.js#4364]
Hi Team,

The given steps I followed
 
Step 1: npm install printer
 
Step 2: npm install -g nw-gyp
 
Step 3: cd node_modules/printer
 
Step 4: nw-gyp rebuild
         This step given this error
       stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/nw-gyp/lib/install.js:236:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/nw-gyp/node_modules/request/request.js:952:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.19.0-49-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "rebuild"
gyp ERR! cwd /home/sathish/nodejs/node-printer-master/node_modules/printer
gyp ERR! node -v v4.1.2
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok

**Comment by thomaswelton** [comment]
Not sure but think you may need to include the target flag to the rebuild command
https://github.com/nwjs/nw-gyp#how-to-use

`nw-gyp configure --target=v0.13.0-beta5`

Think that may be the correct command?

**Comment by rogerwang** [comment]
btw Native modules built by node-gyp/npm is now supported : https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ
