### ISSUE TITLE
nwjs 13 doc

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#4365]
hi

trying to migrate my app from 0.12 to 13 i discover all the changes made... 

changing all require to nw.require etc but can t start my app

no way to add informations about how to start apps with nw13 now ?

since main : "index.html" seems not working for me right now

what s the best way to start a nwjs app like a chrome extension now ? 

(exemple of package.json and pages to start the app)

thanks

**Comment by jmx** [comment]
I have found http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/ helpful

My package.json looks like:

```
{
"name": "example",
"version": "0.0.1",
"main": "index.html",
"window": {
	"title": "example",
	"toolbar": false,
	"width": 1024,
	"height": 768,
	"min_width": 1024,
	"min_height": 600,
	"resizable": true
	}
}
```
