### ISSUE TITLE
v0.13.0 beta 5 NORMAL - inspect on right click

### ISSUE THREAD

**Issue by kucix** [nwjs/nw.js#4366]
Hi,
i build simple browser for one webpage, webview fill entire page, plus few functions.
In normal version (non-sdk), if i right click on webview i get context menu with "Inspect".
I tryied to disable with event listeners on contextmenu event with prevent default, but with no result.

``` javascript
document.addEventListener("contextmenu", function(e){
    e.preventDefault();
    e.stopPropagation();
    return false;
});

document.getElementById('webview').addEventListener("contextmenu", function(e){
    e.preventDefault();
    e.stopPropagation();
    return false;
});

document.getElementById('webview').addEventListener("load", function(e){
    document.getElementById('webview').executeScript({code:'document.addEventListener("contextmenu", function(e) { e.preventDefault(); })'});
});
```

How do i get rid of the "Inspect" in final product?

Thanks

**Comment by kucix** [comment]
Any tips for removing this menu?

**Comment by kucix** [comment]
HA
I found a workaround

```javascript
document.getElementById('webview').contextMenus.onShow.addListener(function(e){
	e.preventDefault();
});
```

**Comment by bckp** [comment]
:+1: workaround works :)

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-v0.22.0(normal).

**Comment by Christywl** [comment]
close until there is more information.
