### ISSUE TITLE
[mac] Promise not returning

### ISSUE THREAD

**Issue by nayanbhana** [nwjs/nw.js#4367]
When I run the application from my command line using

`/Applications/nwjs.app/Contents/MacOS/nwjs /path/to/myapp`

The app runs correctly as intended returning the promise as seen in the screenshot below from the console.

![](https://i.gyazo.com/3f4024416a0b49f0dfafa3912bb80df7.png)

However if I package the myapp up into a .app file the promise never returns as seen below

![](https://i.gyazo.com/0e729e52ca233befe2312d49dab13287.png)

Does anyone know why? This is driving me nuts.

**Comment by ghostoy** [comment]
Could you please post your NW version, OS and a sample app (at least the impl. of `isUpdateRequired`)?

**Comment by nayanbhana** [comment]
Hi @ghostoy 
I am using nw v0.13.0-beta5-osx-x64
OS X: El Capitan 10.11.1
isUpdateRequired: https://github.com/nayanbhana/nwjs-armorcritical/blob/macUpdate/js/isUpdateRequired.js

My project is open-source at https://github.com/nayanbhana/nwjs-armorcritical/blob/macUpdate/

**Comment by ghostoy** [comment]
I can't reproduce this issue with latest NW.js.

BTW, the code in `isUpdateRequired.js` doesn't `reject` when  error thrown in `getRemoteHash`. And the code in `main.js` calling to `isUpdateRequired` doesn't handle rejected promises as well. That means, when `getRemoteHash` fails, it fails silently.
