### ISSUE TITLE
Crash when bg-script calls nw.Window.get()

### ISSUE THREAD

**Issue by DigitalIO** [nwjs/nw.js#4368]
Calling `nw.Window.get()` from a background script causes nw.js to crash. This may be related to #3474

Os: Win 10 x64

> nw.js v0.13.0-beta5
> Node v5.4.1
> Chromium 48.0.2564.97
> commit hash: cb79ab8-7b8b7ed-a93f67b-09f2a6d

**To re-produce:**

package.json
```JSON
{
  "name": "test-app",
  "main": "index.html",
  "bg-script": "crash.js"
}
```
index.html
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crash Test</title>
</head>
<body>
    <h1>Crash Test</h1>
</body>
</html>
```

crash.js
```javascript
var win = nw.Window.get();
```

**Comment by DigitalIO** [comment]
Uploaded sample repo with a crash dump.
https://github.com/DigitalIO/nwjs-crash-test/

**Comment by rogerwang** [comment]
in 0.13, bg-script is running in the background page, which has no corresponding window. But it shouldn't crash. I'll fix the crash. Thanks.
