### ISSUE TITLE
Compiling for Ubuntu 12.04 ARM (OMAP4)

### ISSUE THREAD

**Issue by UweTrottmann** [nwjs/nw.js#437]
This is somewhat related to #193.

I tried to build node-webkit for Ubuntu 12.04 ARM using the regular build-setup as given in the wiki in addition to instructions from recipe 3 on the [Chromium ARM Wiki page](http://code.google.com/p/chromium/wiki/LinuxChromiumArm#Recipe3:_Packaged/Automated_Cross_compiling).
I modified the recipe 3 build script for node-webkit and the soft-float variant builds fine. Have a look at [the build script](https://gist.github.com/UweTrottmann/4753899) and [how to setup multiarch on the target ARM device including required dependencies](https://gist.github.com/UweTrottmann/4753899)  for node-webkit.

Now **when running the nw binary** on the ARM device (a Pandaboard) I get the following error:

```
$ ./nw
[1747:0218/095952:ERROR:zygote_host_impl_linux.cc(146)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
$ [1749:0100/000000:ERROR:zygote_linux.cc(508)] write: Broken pipe
```

Does anybody by any chance know about this? It's a long shot, but maybe this problem is already well known to you.
##

**Comment by jalbam** [comment]
Hello,

I have just created a repository with the node-webkit binary port that runs on Raspbian, tested and working on Raspberry Pi 1 and Raspberry Pi 3 so it is ARMv6 and ARMv7 compatible.

Here you can check it: https://github.com/jalbam/nwjs_rpi
