### ISSUE TITLE
arrow keys don't work on window menubar in Linux on 0.13-beta5

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#4372]
If you click a menu in a window menubar, the menu appears. The up and down arrow keys will correctly highlight the various menu items there, but the left and right arrow keys won't navigate to the other menus.

**Comment by jonwwilkes** [comment]
Oops.. I shouldn't have put 0.13-beta5 in the title, because this issue existed for 0.12, too.

**Comment by jonwwilkes** [comment]
Same for beta7, tested on Ubuntu 14.04 lts amd_64

**Comment by ghostoy** [comment]
Merged to #4943
