### ISSUE TITLE
nw.App.registerGlobalHotKey misspelled in 0.13.0

### ISSUE THREAD

**Issue by scottdarch** [nwjs/nw.js#4373]
appears as `nw.App.registerGlobalHotkey` instead:

<img width="532" alt="screen shot 2016-02-05 at 9 31 47 pm" src="https://cloud.githubusercontent.com/assets/1971146/12864875/fb400b24-cc4f-11e5-9595-1371ac2fc62f.png">

Listed as [registerGlobalHotKey](http://docs.nwjs.io/en/v0.13.0-beta5/References/App/#appregisterglobalhotkeyshortcut) in docs.

**Comment by rogerwang** [comment]
This was fixed in the nightly build. Thanks.
