### ISSUE TITLE
crash when  alert  repeatedly  if  the web page  is on remote

### ISSUE THREAD

**Issue by lashanchenqi** [nwjs/nw.js#4375]
My environment ： Windows 7 64-bit    using   **nwjs-v0.13.0-beta5-win-ia32**

A  simple  html button  in my web page   that  acts  an  alert：

`<input type='button' value='button' onclick="alert('xxx')" />`

If the web page  is on  remote server  that means it is  acccessed by "http://"   , then,  when you  click the input button  alert   repeatedly  more  than  20 times   nw.js  will crash.

For  example   put  this  package.json  below  to your  nw.js  and try.....

{
    "main": "http://jn.yimaijian.com/test.html",
    "name": "test"
}

**Comment by lashanchenqi** [comment]
I have found out that if  you  add  your page in "node-remote" for package.json， the  alert crash will not  happen any more.

**Comment by ags131** [comment]
Happens for me too, except in my case, node-remote didn't effect it for me.
OS: Linux Ubuntu 15.10 x86_64

**Comment by divinemanwah** [comment]
Same. Happens to me too. My version is **nwjs-sdk-v0.15.3-win-x64**. Putting it on the `node-remote` didn't fix the problem.

**Comment by icerleer** [comment]
crash when alert、cofirm and prompt repeatedly if the web page is on remote

My version is nwjs-v0.15.4-win-ia32. Putting it on the node-remote fix It.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows on nwjs-sdk-v0.22.0.

**Comment by Christywl** [comment]
close until there is more information.
