### ISSUE TITLE
[Windows] nw.js (array instanceof Array) == false

### ISSUE THREAD

**Issue by zsxsoft** [nwjs/nw.js#4377]
Version: Windows 32-bit, 0.13.0-beta5
OS: Windows 10 x64(14257)

As the following image, It's right.
![image](https://cloud.githubusercontent.com/assets/2398785/12871182/d414cff4-cda7-11e5-8303-322b7b3a3467.png)

But: 
```javascript
var http = require('http');
http.get("http://127.0.0.1:3333/", (res) => {
	console.log(res.headers['set-cookie']);
	console.log(res.headers['set-cookie'] instanceof Array);
})
```
![image](https://cloud.githubusercontent.com/assets/2398785/12871184/f0fa670a-cda7-11e5-8a34-9153f4e507ea.png)

In Node (v5.0.0):
![image](https://cloud.githubusercontent.com/assets/2398785/12871187/1822bd00-cda8-11e5-82bd-7bc1e61dbad5.png)

I don't know that why it responded a wrong result, as https://github.com/nwjs/node/blob/9babc095181835d07a814bc4d4b81b72fbf92127/lib/_http_incoming.js#L135, it's just a normally array.
```javascript
    case 'set-cookie':
      if (dest[field] !== undefined) {
        dest[field].push(value);
      } else {
        dest[field] = [value];
      }
      break;

```

**Comment by zsxsoft** [comment]
To the documentation of node(https://nodejs.org/api/http.html#http_http_get_options_callback), 
> set-cookie is always an array. Duplicates are added to the array.

**Comment by zsxsoft** [comment]
That's a hard question and I don't think it can be solved. Closed..

**Comment by rogerwang** [comment]
This issue duplicates with many existing issues, e.g.  https://github.com/nwjs/nw.js/issues/3107

Search for 'instanceof' and you'll see all of them.
