### ISSUE TITLE
When is the famous v0.13 expected to go stable?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [nwjs/nw.js#4378]
I've been holding out to learn NW.js for a long time now because I perceive that the change between 0.12 and 0.13 is major, in spite of it not being called 1.0, which I had hoped.

When can I expect it to be released? I'm not comfortable using beta/RC software, and I don't wanna use the old 0.12.

**Comment by chino23** [comment]
0.13 is surprisingly stable. It's not expected to see major breaking changes now. Give it a shot. That way when it's going officially stable, you're already set.

**Comment by rogerwang** [comment]
Yeah. it's stable and we didn't release RC because there is a few features left in 0.12 to be ported.
