### ISSUE TITLE
Games with Adobe flash and java plugin not working with nwjs0.13

### ISSUE THREAD

**Issue by vivekgaikwad** [nwjs/nw.js#4379]
As per the documentation on your site Migrate from 0.12 to 0.13: "webkit.{plugin|java|page-cache} option in package.json is not supported for now: plugins are enabled by default." I have tried games without following parameters:
"webkit": {
        "plugin": true,
        "java":true
 }
but it didn't work.
I have also tried adding above parameters in manifest file but it still didn't work.

**Comment by vivekgaikwad** [comment]
Any updates???

**Comment by vivekgaikwad** [comment]
Hello,

Its urgent please reply as soon as possible.

**Comment by vivekgaikwad** [comment]
Is there any solution so that i can try to work java plugin in nwjs?

**Comment by rogerwang** [comment]
Should be working now with the latest version. If not, please submit a new issue with more information.
