### ISSUE TITLE
Get cpu serial number

### ISSUE THREAD

**Issue by shakogegia** [nwjs/nw.js#4388]
Can I get cpu serial number with nw.js?

**Comment by makkesk8** [comment]
yes, using child_process.exec and "wmic cpu get ProcessorId"

**Comment by gianluca-nitti** [comment]
> using child_process.exec and "wmic cpu get ProcessorId"
Please note that this will work on Windows only, on other systems (Unix) you may use something like `dmidecode`.

**Comment by makkesk8** [comment]
@gianluca-nitti right, it's quite obvious so I assumed he knew :)

**Comment by rogerwang** [comment]
Thanks for answering.

And please submit questions to the mailing list: https://groups.google.com/forum/#!forum/nwjs-general
