### ISSUE TITLE
[node@5.6.0 | linux | x64] nw-headers 404 when nw-gyp rebuild

### ISSUE THREAD

**Issue by koloda** [nwjs/nw.js#4389]
`gyp info it worked if it ends with ok`
`gyp info using nw-gyp@0.13.0`
`gyp info using node@5.6.0 | linux | x64`
`gyp http GET http://node-webkit.s3.amazonaws.com/v5.6.0/nw-headers-v5.6.0.tar.gz`
`gyp http 404 http://node-webkit.s3.amazonaws.com/v5.6.0/nw-headers-v5.6.0.tar.gz`
`gyp WARN install got an error, rolling back install`
`gyp ERR! configure error `
`gyp ERR! stack Error: 404 status code downloading tarball`
`gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/nw-gyp/lib/install.js:236:14)`
`gyp ERR! stack     at emitOne (events.js:95:20)`
`gyp ERR! stack     at Request.emit (events.js:182:7)`
`gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/nw-gyp/node_modules/request/request.js:951:10)`
`gyp ERR! stack     at emitOne (events.js:90:13)`
`gyp ERR! stack     at ClientRequest.emit (events.js:182:7)`
`gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:425:21)`
`gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)`
`gyp ERR! stack     at Socket.socketOnData (_http_client.js:315:20)`
`gyp ERR! stack     at emitOne (events.js:90:13)`
`gyp ERR! System Linux 3.19.0-49-generic`
`gyp ERR! command "/usr/local/bin/node" "/usr/bin/nw-gyp" "rebuild"`
`gyp ERR! cwd /var/www/knopka/desktop-app-js/node_modules/canvas`
`gyp ERR! node -v v5.6.0`
`gyp ERR! nw-gyp -v v0.13.0`
`gyp ERR! not ok `

**Comment by busykai** [comment]
try specifying nw.js version explicitly: `--target=0.13.0-beta5` (for example).

**Comment by rogerwang** [comment]
Yeah, please specify version. btw, now we support native modules built by node-gyp/npm: https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ
