### ISSUE TITLE
Mac OSx app crashes on close when using menu APIs 0.13.0

### ISSUE THREAD

**Issue by scottdarch** [nwjs/nw.js#4390]
If you use the menu apis to replace the default menu the app will crash on close. Also, the quit action doesn't work. 

To reproduce just run the file explorer demo using 0.13.0. When you close it you get:

```
2016-02-11 19:21:02.558 nwjs[36517:616716] *** Assertion failure in -[NSMenu removeItem:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.34/Menus.subproj/NSMenu.m:832
Illegal instruction: 4
```

**Comment by scottdarch** [comment]
Response to this bug in forum: https://groups.google.com/d/msg/nwjs-general/YXevsGRkii8/zT3N2fMJDgAJ

**Comment by rogerwang** [comment]
merge with #4374
