### ISSUE TITLE
Best IDE to DEVELOPER?

### ISSUE THREAD

**Issue by iurimattos** [nwjs/nw.js#4393]
Hi guys.
I'm developing systems only in html + css + js + db ( indexedDB ) and looking for an IDE for Development . 

What do you think of Frefox WebIDE ??

**Comment by makkesk8** [comment]
dude this is not the place to discuss what IDE is the best, if you don't have a real issue related to nw.js don't post.

**Comment by rogerwang** [comment]
Please discuss in the mailing list: https://groups.google.com/forum/#!forum/nwjs-general
