### ISSUE TITLE
require('nw.gui').Window.get().evalNWBin(null, 'jquery.bin') is not working on Fancybox.css

### ISSUE THREAD

**Issue by namaljayathunga** [nwjs/nw.js#4394]
I used "require('nw.gui').Window.get().evalNWBin(null, 'jquery.bin');" inside fancybox loaded page. But error say "require is not define". fancybox open when click on div. 
`<div class='fancybox fancybox.iframe' href='video.htm?id=1.2'>`
How can I solve this problem? Thank

**Comment by namaljayathunga** [comment]
I added "node-remote": "<local>" to pakage file then bellow code is working on fancybox.
`require('nw.gui').Window.get().minimize();`
But bellow code is NOT working.
`require('nw.gui').Window.get().evalNWBin(null, 'jquery.bin');`

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
