### ISSUE TITLE
Is it possible to use node-webkit without node.js

### ISSUE THREAD

**Issue by sksar** [nwjs/nw.js#4395]
Hi i would like to know if i was able to use only the webkit part of nw.js and not use the node.js(means install node.js on host system).. As the app i was developing is simply a desktop version of a webapp which doesnot require to call native i/o like functions...

**Comment by kucix** [comment]
node.js is part of the nw.js app, it is not required to install node.js on host system, all is built in

**Comment by sksar** [comment]
how do i install nw.js then.... also i have installed node.js so shall i need it anymore or shall i remove it if nw.js provides me with an integrated node.js

**Comment by kucix** [comment]
nw.js has no installer, just download it on http://nwjs.io/
if you want installer for your app, you must create your own
http://docs.nwjs.io/en/v0.13.0-beta5/For%20Users/Package%20and%20Distribute/
If you don't need node.js on your system, you can uninstall it, but if you want package from npm, keep node.js installed, then you can use npm to install packages from repository.
But for running app in nw.js node.js is not required

**Comment by sksar** [comment]
ok i got it but how do i package an app(along with the executable) nicely so that the packaged files could not be read by apps such as archive manager..

**Comment by kucix** [comment]
as far as I know, it's not possible
example of nw.js app (web browser based on nw.js 0.12) 
https://www.seznam.cz/aplikace/
all sources are readable in install dir

in future will be possible to append zip to executable, but is only appended, teoretically you can extract that too

**Comment by sksar** [comment]
what if i apply a password to the zip archive... and also how do i run multiple instances of the same app. which i was was unable to do with the `nw` binary file. i tried to run it multiple times (while one instance was already running) but it didn't

**Comment by kucix** [comment]
if you apply password, app will not run, you need plain text files, like on the web pages, it's just javascript...
if you create package.nw file, it's only zip file and it's extracted to system temp directory before run.
if you want app, where user can't see anything of your code (why?), you must use another technology, like C, C++, C#, java, Delphi etc...
This is just help tool for creating "native like" apps with web technologies
I think that is intended to create open source apps with nw.js, not for business apps

**Comment by sksar** [comment]
how do i run multiple instances of the same app. which i was was unable to do with the nw binary file. i tried to run it multiple times (while one instance was already running) but it didn't

**Comment by kucix** [comment]
you can't run multiple instance

http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

> single-instance is deprecated and it’s always true. You CANNOT have multiple instances for your app unless you’re using different user data directory (by --user-data-dir). You may also want to use the open event: the first instance will be notified with this event when user tries to launch the second instance.

http://docs.nwjs.io/en/latest/References/Manifest%20Format/#single-instance

**Comment by kucix** [comment]
If you catch open event in running app, you can show notofication, open new tab, open dialog or open new window with same "page" and simulate second instance of app

**Comment by sksar** [comment]
if i create two different apps by integrating the executable and thus creating two different executable will i be able to run both the apps simultaneously.. as i think the case would be the same as running another instance as the binary executable is same..

**Comment by kucix** [comment]
yes, that is two apps, two directories, each asi single instance
even if you create one app and copy into two directories, you can run it both int the same time
(not tested)

**Comment by sksar** [comment]
i copied the nw executable in two seperate directories along with the required files but they wont start simultaneously. no problem when any instance is not running. only cannot start them together.

**Comment by kucix** [comment]
then is detected by the app name in manifest or something like that

**Comment by sksar** [comment]
what should i do to run them simultaneously.. change the app name??

**Comment by kucix** [comment]
i'm not on my dev machine to test it, but yes, i think that name is for detection, if another directory does'nt work 
if you create another app, it have another name too
I create only one simple app for specific task, so i not run two nwjs apps...

**Comment by sksar** [comment]
how do i change the name of the app

**Comment by sksar** [comment]
does the name field in the package.json changes the manifest name of the app too??

**Comment by kucix** [comment]
package.json is manifest, yes

**Comment by sksar** [comment]
but if i wanna change the name of the binary itself... what do i do then..

**Comment by kucix** [comment]
you ask how to rename file?
like F2 in explorer?

**Comment by sksar** [comment]
no.. i wanna change the manifest name off the binary i got right out of the package

**Comment by rogerwang** [comment]
Please submit questions to mailing list: https://groups.google.com/forum/#!forum/nwjs-general
