### ISSUE TITLE
which files are required by nw-js executable

### ISSUE THREAD

**Issue by sksar** [nwjs/nw.js#4396]
i wanna distribute a packaged app and found that two files need to be in the same folder as the nw executable. one is the `nw.pak` and the other is `icudtl.dat`. i wanna know is there some other files absolutely necessary to be included. or can both these files be excluded. Also i would like to know if i could combine all the three files along with the app.nw file to make a single executable file..

**Comment by rogerwang** [comment]
You should include all files in the official zip binary. And please submit questions to mailing list: https://groups.google.com/forum/#!forum/nwjs-general
