### ISSUE TITLE
where is ffmpeg.gyp? documentation update needed

### ISSUE THREAD

**Issue by Medioman92** [nwjs/nw.js#4397]
Hi,
I'd like to enable MP4 and MP3 by build my own version of NW.js.
The documentation talks about editing third_party/ffmpeg/ffmpeg.gyp but i can't find this file ?
is there a updated documentation for NWJS 13 ?

**Comment by ghostoy** [comment]
See [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/) for details.
