### ISSUE TITLE
how to run nwjs as library call

### ISSUE THREAD

**Issue by sksar** [nwjs/nw.js#4398]
i am creating several apps whose size are about ~10MB. there are about 5 apps so there is ~50MB files. But as each app is seperate and i need to create seperate .desktop files to run them i have to package each file seperately and the size becomes ~500MB [as 5 X (83mb + 10mb)] the 83MB file being the `nwjs `executable. 
So i wanna reduce this size and wanna ship much less amount of file size.. 
So is there any workaround so that the `nwjs` executable remains in one single directory such as in the `/bin` and the `app.nw` files in five separate directories in `/usr/nw-apps/`  and i call nwjs using shell command specifying the location of the app.nw file to run with..

**Comment by rogerwang** [comment]
You can develop a launcher to launch the single nw binary with different path arguments which points to different apps. And please submit questions to mailing list: https://groups.google.com/forum/#!forum/nwjs-general
