### ISSUE TITLE
FileReader seems to be broken in 0.13.0-beta5

### ISSUE THREAD

**Issue by sheley1998** [nwjs/nw.js#4399]
Hi,
the following code works in version 0.12.3, but not anymore in 0.13.0-beta5

`
var file = new File('image.jpg', 'randomDivName');

var fileReader = new FileReader();
fileReader.readAsDataURL(_file);

fileReader.onload = function(e)
{
    console.log('load complete');
};

fileReader.onerror = function(e)
{
    console.log(e);
};
`

fileReader is able to load image.jpg and trigger onload in 0.12.3, but in 0.13.0-beta5 it goes straight to onerror.

Thanks for your help!

**Comment by sheley1998** [comment]
BTW I am running the above code snippet under windows 10 x64, using SDK version of 64bit 0.13.0-beta5

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by sheley1998** [comment]
Thanks man, you're the best :D
