### ISSUE TITLE
node-ffi  not working with 0.13.0-beta5 on windows xp

### ISSUE THREAD

**Issue by coonooo** [nwjs/nw.js#4400]
I compile node-ffi  width vs2013.when i run nwjs on windows xp. It throw error 
** Uncaught Error: The specified procedure could not be found.
\\?\Z:\electron\node_modules\ffi\build\Release\ffi_bindings.node**

other lib like node-usb,ref works fine.

**Comment by coonooo** [comment]
没人解决吗？自己跟了下代码发现在node-ffi的源码中 

```
  Local<Object> o = Nan::New<Object>();
  o->Set(Nan::New<String>("dlopen").ToLocalChecked(),  WrapPointer((char *)dlopen));
这里报错，WrapPointer最终调用的是v8的ArrayBuffer::New，是这里出错。

测试代码：
char* data="hello"
ArrayBuffer::New( v8::Isolate::GetCurrent(), data,0,ArrayBufferCreationMode::kInternalized);
如果data是函数指针，则报错。
```

**Comment by rogerwang** [comment]
Hello, we are trying to set up a XP environment. Before that, is FFI working well in Win7?

**Comment by coonooo** [comment]
working well on windows 10.

**Comment by spirodonfl** [comment]
I was able to build a C native module using node-gyp with 0.13-beta6 in Linux (which would probably be similar in Windows, haven't tried yet). It might be worth looking into.

**Comment by coonooo** [comment]
solved.
remove the line 96 and 99 in file win32-dlfcn.cc (in the ffi source files)
```
    errorMode = GetErrorMode();

    SetErrorMode(errorMode | SEM_FAILCRITICALERRORS);
```
the error is gone. but i dont know why.only windows xp have this problem.

**Comment by ghostoy** [comment]
@coonooo VS2013 doesn't support XP. How would you managed to build node-ffi on XP?

**Comment by coonooo** [comment]
@ghostoy i just compile node-ffi use vs2013.it work well on xp sp3. I dont test on other version.

**Comment by ghostoy** [comment]
@coonooo Are you building on newer OS (like Win7) with VS2013 and targeting for XP? I just tried to install VS2013 on XP, but failed because of incompatibility.

**Comment by coonooo** [comment]
@ghostoy  yes.I building on windows 10 with vs2013.

**Comment by ghostoy** [comment]
@coonooo `node-ffi` doesn't work with Node.js on XP as well. I recommend you to submit the issue to [`node-ffi`](https://github.com/node-ffi/node-ffi)

**Comment by zhangzhichengyu** [comment]
请问一下，这个问题最终解决了吗？是需要修改ffi的源码吗？英文不好 没看太明白，请指点指点，非常感谢！

**Comment by ghostoy** [comment]
@zhangzhichengyu `node-ffi` 不支持XP。

@coonooo 通过[删除两行代码](https://github.com/nwjs/nw.js/issues/4400#issuecomment-187549385)，[修改`nw-gyp`生成的`vcxproj`项目文件](https://github.com/nwjs/nw.js/issues/4400#issuecomment-188025510)，并且在win10的vs2013上编译成功。

**Comment by zhangzhichengyu** [comment]
@ghostoy ffi在xp上是可以的，就是通过注释掉上面说的那两行代码的办法，已经测试成功！nw采用0.14.7的版本，也是在win10上基于vs2015编译的。
@coonooo 非常感谢你的指点，谢谢！

**Comment by oborba** [comment]
When I removed the two lines, it worked perfectly.

Can this change cause any problems?

**Comment by xh4722** [comment]
@zhangzhichengyu 
我用的NW0.14.7使用nw-gyp configure --target=v0.14.7的时候会出错，
提示Error:'gyp' failed with exit code:1
nw-gyp的版本是v3.4.0，你知道是什么原因吗？
