### ISSUE TITLE
is it possible to modify style of inner elements in iframes

### ISSUE THREAD

**Issue by xete** [nwjs/nw.js#4401]
Here I have sourced "google.com" into an iframe,
tried several methods but failed to modify the style as below (hide the button).
Could anyone point out what's wrong with my code or is there another way to achieve this ?
Also, I wonder whether `console.dir()` works for node-webkit?

``` html
<iframe id="ifr" src="https://www.google.com"> </iframe>
```

``` javascript
var win = require('nw.gui').Window.get();
win.on('document-end', function(iframe) {
  var script=iframe.contentWindow.document.createElement('script');
  script.innerHTML='document.getElementsByName("btnI")[0].style = "display: none !important";';
  iframe.contentWindow.document.body.appendChild(script);
});
```

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
