### ISSUE TITLE
nwjs application run in differently each time

### ISSUE THREAD

**Issue by mpsbhat** [nwjs/nw.js#4402]
I have created a nwjs application and I have created the distribution package using nw-builder as `sudo nwbuild -p linux -v 0.12.3 -o ~/Documents/output/ /home/path/to/application/files/` and it was created successfully. I used diskdb for data storage by following this[ tutorial series](http://thejackalofjavascript.com/node-webkit-powered-dashboard-app/).

The problem is, when i save some records and close the application and next time when i open the application, previously saved data is unavailable..! When I made `toolbar: true` in my `package.json` file i observed that each time the chromium webkit open as a temporary folder with temp link as, `file:///tmp/.org.chromium.Chromium.fK2Img/login.html, file:///tmp/.org.chromium.Chromium.dDiSrR/login.html `etc. How can I solve the same?

**Comment by rogerwang** [comment]
You should save the status of application to user data dir, or use a different packaging mechanism (non-zip). And please submit questions to mailing list: https://groups.google.com/forum/#!forum/nwjs-general
