### ISSUE TITLE
How can I made a dialogWindow?

### ISSUE THREAD

**Issue by te3** [nwjs/nw.js#4403]
First of all, the 'setAlwaysOnTop' method of window will set it to top of all window.But i just wish set it to top of it's parent window.

So I have made a dialogWindow, deppend on the focus event. Because there was't a beforefocus event, when i focused the parent window, the dialogWindow will covered by parent window,and showed on the top of the parent window in a few miiliseconds by dialogWindow's focus event.It's ugly very much.

My question is: Is there any way to handle 'top' event or 'beforefocus' event?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
