### ISSUE TITLE
0.12.3版本引入自定义的node模块，无法执行，也不报错

### ISSUE THREAD

**Issue by Hsinky** [nwjs/nw.js#4405]
![1](https://cloud.githubusercontent.com/assets/10111222/13065026/2f8bd16a-d493-11e5-82d5-69726e214fe3.png)

**Comment by taoqf** [comment]
你这个global中require的路径对不对

2016-02-16 

29957337 



发件人：Hsinky <notifications@github.com>
发送时间：2016-02-16 09:55
主题：[nw.js] 0.12.3版本引入自定义的node模块，无法执行，也不报错 (#4405)
收件人："nwjs/nw.js"<nw.js@noreply.github.com>
抄送：

**Comment by Hsinky** [comment]
路径是对的，从左侧的文件目录中可以看出来，且将代码放到0.13.5版本中，Tray模块是可以引入正常执行的

**Comment by Hsinky** [comment]
@taoqf 路径是对的，从左侧的文件目录中可以看出来，且将代码放到0.13.5版本中，Tray模块是可以引入正常执行的

**Comment by taoqf** [comment]
那就不清楚了，NW不太熟，但是node的话，你这个路径看你的截图好像是不对的global在js目录下，而Tray在app目录下，如果要在global中require Tray的话，似乎要写require('../app/Tray');

2016-02-16 

29957337 



发件人：Hsinky <notifications@github.com>
发送时间：2016-02-16 10:08
主题：Re: [nw.js] 0.12.3版本引入自定义的node模块，无法执行，也不报错 (#4405)
收件人："nwjs/nw.js"<nw.js@noreply.github.com>
抄送："taoqf"<29957337@qq.com>

路径是对的，从左侧的文件目录中可以看出来，且将代码放到0.13.5版本中，Tray模块是可以引入正常执行的

**Comment by Hsinky** [comment]
@taoqf 路径没有问题吧

**Comment by taoqf** [comment]
知不道啊，看不出来

**Comment by Christywl** [comment]
@Hsinky , is this issue still reproduced with the latest nwjs? If so, could you please upload your tests to reproduce it?
