### ISSUE TITLE
0.13.5版本无法获取当前窗口

### ISSUE THREAD

**Issue by Hsinky** [nwjs/nw.js#4407]
![2](https://cloud.githubusercontent.com/assets/10111222/13065159/91a682c2-d494-11e5-93fc-13224669b639.png)

**Comment by rogerwang** [comment]
in 0.13, bg-script is running in the background page, which has no corresponding window. But it shouldn't crash. I'll fix the crash. Thanks. And btw, please use English in this project so all users can read it.

merge with #4368

**Comment by Hsinky** [comment]
@rogerwang  thank you for your reply,my code had uploaded in github,the link is https://github.com/Hsinky/Cross.GPS, I hope you can help me, thanks again!

**Comment by Hsinky** [comment]
@rogerwang  you are admin? I have other question，https://github.com/nwjs/nw.js/issues/4405，please help me

**Comment by taoqf** [comment]
我估计他看得懂中文

**Comment by Hsinky** [comment]
我的英文太渣了

**Comment by SophinQ** [comment]
I need to use trays in bg-script, but it failed to get window events.

**Comment by SophinQ** [comment]
@rogerwang I need to use trays in bg-script, but it failed to get window events.
