### ISSUE TITLE
nwjs-0.13.0 版本nw-gyp 不能用vs2010编译

### ISSUE THREAD

**Issue by coonooo** [nwjs/nw.js#4408]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(252
6): error C2989: 'v8::Number' : class template has already been declared as a n
on-class template [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\includ
  e\v8.h(87) : see declaration of 'v8::Number'
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(254
1): error C2989: 'v8::Integer' : class template has already been declared as a
non-class template [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\includ
  e\v8.h(82) : see declaration of 'v8::Integer'
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(255
5): error C2989: 'v8::Int32' : class template has already been declared as a no
n-class template [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\includ
  e\v8.h(81) : see declaration of 'v8::Int32'
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(256
9): error C2989: 'v8::Uint32' : class template has already been declared as a n
on-class template [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\includ
  e\v8.h(107) : see declaration of 'v8::Uint32'
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(298
5): error C2989: 'v8::Object' : class template has already been declared as a n
on-class template [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\includ
  e\v8.h(89) : see declaration of 'v8::Object'
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(301
4): error C2989: 'v8::Array' : class template has already been declared as a no
n-class template [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\includ
  e\v8.h(69) : see declaration of 'v8::Array'
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(322
6): error C2504: 'v8::Object' : base class undefined [Z:\electron\node_modules\
ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(323
3): error C2061: syntax error : identifier 'FunctionCallback' [Z:\electron\node
_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(323
5): error C2059: syntax error : ')' [Z:\electron\node_modules\ffi\build\ffi_bin
dings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(323
5): error C2143: syntax error : missing ')' before ';' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(323
9): error C2061: syntax error : identifier 'FunctionCallback' [Z:\electron\node
_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(323
9): error C2059: syntax error : ')' [Z:\electron\node_modules\ffi\build\ffi_bin
dings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(323
9): error C2143: syntax error : missing ')' before ';' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(325
0): error C2059: syntax error : 'return' [Z:\electron\node_modules\ffi\build\ff
i_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(325
0): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(325
5): error C2146: syntax error : missing ';' before identifier 'Call' [Z:\electr
on\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(326
1): error C2270: 'GetName' : modifiers not allowed on nonmember functions [Z:\e
lectron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(326
9): error C2270: 'GetInferredName' : modifiers not allowed on nonmember functio
ns [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(327
5): error C2270: 'GetDisplayName' : modifiers not allowed on nonmember function
s [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(328
1): error C2270: 'GetScriptLineNumber' : modifiers not allowed on nonmember fun
ctions [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(328
6): error C2270: 'GetScriptColumnNumber' : modifiers not allowed on nonmember f
unctions [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(329
1): error C2270: 'IsBuiltin' : modifiers not allowed on nonmember functions [Z:
\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(329
6): error C2270: 'ScriptId' : modifiers not allowed on nonmember functions [Z:\
electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(330
2): error C2270: 'GetBoundFunction' : modifiers not allowed on nonmember functi
ons [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(330
4): error C2270: 'GetScriptOrigin' : modifiers not allowed on nonmember functio
ns [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(330
8): error C2059: syntax error : 'private' [Z:\electron\node_modules\ffi\build\f
fi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(330
9): error C2059: syntax error : ')' [Z:\electron\node_modules\ffi\build\ffi_bin
dings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(331
8): error C2504: 'Object' : base class undefined [Z:\electron\node_modules\ffi\
build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
0): error C2504: 'Object' : base class undefined [Z:\electron\node_modules\ffi\
build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
6): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
6): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
6): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
6): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
7): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
7): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
7): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(332
8): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(333
3): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(333
3): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(333
3): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(333
9): error C2061: syntax error : identifier 'Local' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
1): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
1): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
1): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
3): error C2061: syntax error : identifier 'Local' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
5): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
5): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
5): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(334
7): error C2061: syntax error : identifier 'Value' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(335
1): error C2061: syntax error : identifier 'Value' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
1): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
1): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
1): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
2): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
2): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
3): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
6): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
6): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
6): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
7): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
7): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(336
8): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(337
1): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(337
1): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(337
1): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(337
2): error C2143: syntax error : missing ';' before '<' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(337
2): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(337
3): error C2238: unexpected token(s) preceding ';' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(338
1): error C2061: syntax error : identifier 'Value' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(338
5): error C2061: syntax error : identifier 'Value' [Z:\electron\node_modules\ff
i\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(339
5): error C2332: 'enum' : missing tag name [Z:\electron\node_modules\ffi\build\
ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(339
5): error C2236: unexpected 'class' 'ArrayBufferCreationMode'. Did you forget a
 ';'? [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(339
5): error C3381: 'ArrayBufferCreationMode' : assembly access specifiers are onl
y available in code compiled with a /clr option [Z:\electron\node_modules\ffi\b
uild\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(339
5): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(339
5): error C2143: syntax error : missing ';' before '}' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(339
5): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(340
2): error C2504: 'Object' : base class undefined [Z:\electron\node_modules\ffi\
build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(341
9): error C2628: 'ArrayBuffer::Allocator' followed by 'void' is illegal (did yo
u forget a ';'?) [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(344
5): error C3861: 'data_': identifier not found [Z:\electron\node_modules\ffi\bu
ild\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(344
5): error C2461: 'Contents' : constructor syntax missing formal parameters [Z:\
electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(344
5): error C2059: syntax error : 'constant' [Z:\electron\node_modules\ffi\build\
ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(344
5): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int [Z:\electron\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Documents and Settings\coonooo\.nw-gyp\0.13.0-beta6\deps\v8\include\v8.h(344
5): error C2143: syntax error : missing ';' before '{' [Z:\electron\node_module
s\ffi\build\ffi_bindings.vcxproj]

**Comment by rogerwang** [comment]
Native modules built by node-gyp/npm is now supported: https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ
