### ISSUE TITLE
node-webkit的文档，真的是呵呵呵了，一团乱，耽搁无数时间

### ISSUE THREAD

**Issue by qinyang912** [nwjs/nw.js#4410]

**Comment by TonyWuLihu** [comment]
这种类型吐槽请移步论坛，不要发到maillist, 有想过 contributors 看到什么心情？ 吐槽无罪，请尊重他人劳动成果

2016-02-17 10:43 GMT+08:00 qin yang <notifications@github.com>:

**Comment by rogerwang** [comment]
The documentation in wiki was used to be contributed by the community. Starting from 0.13 we are migrating the contents to git as the official documentation and publish it under http://docs.nwjs.io . 

The official documentation will continue to be a community effort. Recently there is a proposal on the new organization of http://docs.nwjs.io: https://groups.google.com/d/msg/nwjs-dev/2EB5AzQd2-0/PQd0VFz_GAAJ  Your idea will be welcomed on how to make it better. Please post them there if there are any.

And please use English both in here and the mailing list so all users can read.
