### ISSUE TITLE
0.13 Feature request: win.showDevTools support webview

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#4411]
ye, i know i can jail webview's devtools use remote-debugging。

but if i do it, open devtools url would be  "hosted mode",that  can not use Clipboard and lots of other feature.

![snip20160217_1](https://cloud.githubusercontent.com/assets/3161552/13103719/4f9e7ac4-d593-11e5-963c-b64d83c215e9.png)

thank you~

**Comment by rogerwang** [comment]
Thanks for reporting. Will fix this.

**Comment by rogerwang** [comment]
If it's for debugging purpose, you can use this workaround: right click on webview, click "inspect".

**Comment by lin-chao** [comment]
@rogerwang 
thank you for answer

need this feature is not for debugging myself, i try to write tools for wechat web developers 。so if it can jail webview's devtools  would be better。

see the picture

![_20160218131107](https://cloud.githubusercontent.com/assets/3161552/13134427/2e1e6ad6-d641-11e5-87d7-f5f4fcc10d4c.png)

by the way, can  find current version here
[http://mp.weixin.qq.com/wiki/10/e5f772f4521da17fa0d7304f68b97d7e.html#.E8.B0.83.E8.AF.95.E5.BE.AE.E4.BF.A1.E7.BD.91.E9.A1.B5.E6.8E.88.E6.9D.83](url)
which was write by electron。

**Comment by rogerwang** [comment]
Good to know it. Will fix it soon.

btw, there is another feature in NW.js you can consider to use: put the target page in iframe and use 'nwfaketop' and 'jailed devtools'. That's what Intel XDK is currently using in their product. Intel XDK is an IDE for developing HTML5 apps. The iframe is an emulator used to simulate mobile device environment for the applications being developed in XDK.

The advantage of using iframe over webview is that you can access the DOM objects in that iframe directly, while the page in webview resides in another process.

See more on nwfaketop and jailed devtools here: 

http://docs.nwjs.io/en/v0.13.0-beta6/References/Changes%20to%20DOM/#attribute-nwfaketop
http://docs.nwjs.io/en/v0.13.0-beta6/References/Window/#winshowdevtoolsiframe-headless-callback

**Comment by lin-chao** [comment]
thanks again~

i know NW.js extended iframe tag .

there're some differences between XDK and me, we try to simulate web page working in wechat webview in our tools, like

- special url change
- wechat jssdk simulation
- and other specil fectures in wechat

so for me , webview is better than iframe, whick support addContentScripts and  chrome.webRequest , and webview working in another process is good.

**Comment by rogerwang** [comment]
Are you using the headless mode of devtools? or a separate devtools window is good for you?

**Comment by lin-chao** [comment]
ye.
a separate devtools window can work but switch windows when developing are not experience good 

more than one webview  would cost more time to find correct devtools window

**Comment by rogerwang** [comment]
@lin-chao  I just add showDevtools(bool) method to webview. Will implement headless mode soon.

**Comment by rogerwang** [comment]
The method will be in next nightly build.

**Comment by lin-chao** [comment]
👍

webview.showDevtools(bool) work good in nightly build 2.20

expect ‘headless mode’

**Comment by rogerwang** [comment]
@lin-chao where are you going to embed devtools? In an iframe or webview?

**Comment by lin-chao** [comment]
@rogerwang 
Either is OK

**Comment by rogerwang** [comment]
please try it with http://dl.nwjs.io/live-build/02-22-2016/962e194-ec121b9-12e9f94-44456c1/v0.13.0-beta7/

sample:
```html
<html>
  <head>
    <script>
      function test(show) {
        var cdt = document.getElementById('cdt');
        document.getElementById('wv').showDevTools(show, cdt);
      }
    </script>
  </head>
  <body>
    <webview id="wv" src="http://nwjs.io" style="width:640px; height:480px"></webview>
    <webview id="cdt" src="about:blank" style="width:640px; height:480px"></webview>
    <button onclick="test(true)">show</button>
  </body>
</html>
```

**Comment by lin-chao** [comment]
hi @rogerwang 

I test it with my mac and pc(win7 64), both worked fine.

thank you for lots of work.

**Comment by lin-chao** [comment]
hi @rogerwang 

there is a bug, with ‘headless mode’ .

- use test code
- make a javascript breakpoint
- reload webpage
- devtools's webview become unresponsive

![image](https://cloud.githubusercontent.com/assets/3161552/13278289/62a8f398-db0a-11e5-84ad-c2b78ad1b647.png)

OS Env :

Mac
Win7

**Comment by rogerwang** [comment]
How did you reload the webpage?

**Comment by lin-chao** [comment]
thank you for replying

many way can reload the webpage

eg:
in devtools executeScript location.reload() or in nwapp executeScript webview.reload()

the point is if set a breakpoint ,webview which used to jail devtools will become unresponsive.

**Comment by rogerwang** [comment]
I found in the debug version it crashes in blink when the site get reloaded. It has nothing to do with the devtools in webview (same bug when opening devtools in a new window). And it's specific to the site. Change it to 'dl.nwjs.io' works.

The crash stack trace is the same as a bug reported in upstream, so it looks like a bug in blink:

https://bugs.chromium.org/p/chromium/issues/detail?id=554315

**Comment by rogerwang** [comment]
Forget to say that I didn't set any breakpoint. So the crash may or may not be related to the issue you reported ...

**Comment by rogerwang** [comment]
I changed the site to 'www.google.com', set some breakpoints, reload and it works for me. So the unresponsiveness should be related  to the crash.

**Comment by lin-chao** [comment]
it was not crashed.

it can't use devtools view (click and right click not work), when a break point is reached, but can step or ruseme script on webpage's webview, and after ruseme devtools work fine again.

![image](https://cloud.githubusercontent.com/assets/3161552/13285147/0a785180-db34-11e5-92d9-a87bf31668e1.png)

**Comment by lin-chao** [comment]
hi, i find a way to fix this problem

set partition="persist:special" to webview which used to jail devtools.

**Comment by lin-chao** [comment]
i test again, set partition attributes on the webview dom which used to container the devtools, can make it work fine.

right now, if there is no other way to fixed this problem

suggest the method  webview.showDevTools(show, [container]) 

required container must to be set a  partition attributes with 'persist': prefix.

thanks for replying again~
