### ISSUE TITLE
Change title of dialogs using window.alert, window.confirm or window.prompt

### ISSUE THREAD

**Issue by martindrapeau** [nwjs/nw.js#4413]
When you run window.alert("Hello World!"), it shows a dialog with this text:
```
chrome-extension://dadfdjfhjdfhsjfdlkjasds says:
Hello World!
```

I believe `chrome-extension://` represents the page url. Any way to change or remove that? Not very professional.

Reproduced using v0.13.0-beta5 normal

**Comment by rogerwang** [comment]
It was fixed in beta6, which is just released today.
