### ISSUE TITLE
win10 0.12.3 unicode error

### ISSUE THREAD

**Issue by yuyinjun** [nwjs/nw.js#4414]
windows10   nw.js 0.12.3

String.fromCharCode("10004")  your get  is garbled
chrome:
![default](https://cloud.githubusercontent.com/assets/9817640/13133166/f067656a-d633-11e5-9a5e-3ad61b56de62.jpeg)

nw.js:
![default](https://cloud.githubusercontent.com/assets/9817640/13133118/82b05b08-d633-11e5-82f3-d5b2f0eaf355.jpeg)

**Comment by rogerwang** [comment]
It should have been fixed in the latest nightly binary, or 0.13.0-beta6.
