### ISSUE TITLE
How to cancel double click to maximize the window 

### ISSUE THREAD

**Issue by komoe** [nwjs/nw.js#4415]
I set up the configuration to allow the application to drag

-webkit-app-region: drag;

But when I double click it, it becomes the maximize, I don't want to let it to maximize, how should I do, please help me,
I tried a lot of ways, but I couldn't solve the problem.

win.on("maximize", function() {});
or 
win.setResizable(false);

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
