### ISSUE TITLE
0.13 beta6 - wrong app name on menu bar on Mac

### ISSUE THREAD

**Issue by cuongle121** [nwjs/nw.js#4416]
Hi,

My code is
`menuBar.createMacBuiltin("My App");`

The result is

![wrong name on menu](https://cloud.githubusercontent.com/assets/3232472/13137556/5135c650-d654-11e5-81ef-9d8726d9bb56.png)

Thanks for reading.

**Comment by ghostoy** [comment]
@cuongle121 You will need to edit `nwjs.app/Contents/Resources/en.lproj/InfoPlist.strings`. Find `CFBundleName` and change its value from `nwjs` to `your-app-name`. This is similar to 0.12.x, but a bit different.

See PR #4535

**Comment by codekiln** [comment]
Does this mean that `menuBar.createMacBuiltin` is no longer a valid way to change the application name in mac?

**Comment by rogerwang** [comment]
@codekiln it's still need for the menu.
