### ISSUE TITLE
End child process on close 

### ISSUE THREAD

**Issue by JoshuaJoell** [nwjs/nw.js#4419]
I've created a child process with execFile using node.js on both windows and mac without issues. The issue I am encountering is on closing nwjs the child process remains active and I can't figure out how to close it other than ending the process with process manager. I was also hoping I could simply just attach a script to the close button on the menu but also can't figure out how to do this. 

My last resort is to create custom css frames for each OS I'm targeting and attach the scripts this way to frameless windows but I was hoping I wouldn't have to and there was another way. 

Thanks for the help

**Comment by ghostoy** [comment]
You can use `close` event on `nw.Window` instance. See http://docs.nwjs.io/en/v0.13.0-beta6/References/Window/#event-close

**Comment by matthew-dean** [comment]
You have to manually close child processes using the close event as @ghostoy mentioned. They don't close themselves just because the main app closes.

**Comment by ghostoy** [comment]
I'm closing this issue. If you see different, please reopen it.
