### ISSUE TITLE
Node-ffi async call crashes nwjs-beta6 on OSX

### ISSUE THREAD

**Issue by cuongle121** [nwjs/nw.js#4420]
Hi,
Thanks for great project.

I am using `node-ffi async library call` in my project (see https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial#async-library-calls ). My project runs ok on Linux, but it crashes right away when I call the async function on OSX. (I have not tested on Windows yet). I also tested with nodejs only, it does not have any problem.

Here is the sample code to reproduce the crash
https://github.com/cuongle121/nwjs-demo-crash-on-Mac-beta6

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by cuongle121** [comment]
I tested on Beta7, it's fixed. Thanks!
