### ISSUE TITLE
Why are the v8 snapshots slower then plain JavaScript?

### ISSUE THREAD

**Issue by Programming4life** [nwjs/nw.js#4421]
I was looking into the V8 project and it stated that snapshots are faster then normal plain JavaScript, but why are the snapshots slower within nwjs?

Source:
https://developers.google.com/v8/embed search for "V8 snapshot feature" on the page.
http://v8project.blogspot.ca/2015/09/custom-startup-snapshots.html

**Comment by rogerwang** [comment]
The snapshot is not slower in NW.js. It's only slower when you want to hide the source code: https://github.com/nwjs/nw.js/issues/4107#issuecomment-167914774

**Comment by rogerwang** [comment]
And please ask questions in the mailing list.
