### ISSUE TITLE
Issue with National Geographic site

### ISSUE THREAD

**Issue by tarva** [nwjs/nw.js#4422]
version 0.12.

Open http://www.nationalgeographic.com/ (National Geographic) site.
Open one of the articles on front page
I opened http://news.nationalgeographic.com/2016/02/160218-oldest-dress-egypt-tarkhan-archaeology/
Scrool down/up with the mouse wheel for a while e.g.10-30 sec. Usually it crashes in 10-20 sec.

Tibor.

**Comment by tarva** [comment]
no dump file.
Just create folder e.g. nw9168_21547 (or other numbers and this folder is empty)

**Comment by zcurchin** [comment]
I could easily reproduce this issue within few seconds following mentioned steps.
I attached two dmp files generated after crash.

[nwjs_dmp_files_4422.zip](https://github.com/nwjs/nw.js/files/138328/nwjs_dmp_files_4422.zip)

**Comment by rogerwang** [comment]
does it work for you with 0.13.0-beta?

**Comment by tarva** [comment]
I tested it on 0.13 and it crashes. First time in about 2-3 minuts, and 2,3,4... time very soon (about 30 sec of surfing and scrooling on page). Please find dump file attached.
Tibor.
[nw0.13beta-NG-site-dump-file.zip](https://github.com/nwjs/nw.js/files/140378/nw0.13beta-NG-site-dump-file.zip)

**Comment by krneticz** [comment]
Roger,

is there anything else that you need regarding this issue? We have client waiting for this bug to be fixed.

Thanks,
Zoran

**Comment by rogerwang** [comment]
Will see it soon.

**Comment by rogerwang** [comment]
I can reproduce this. Pushed a fix in chromium repo. Please wait for the next nightly build: http://buildbot-master.node-webkit.org:8010/waterfall

**Comment by krneticz** [comment]
Roger,

thank you very much! Will try and let you know.

**Comment by rogerwang** [comment]
nightly build with the fix: http://dl.nwjs.io/live-build/03-08-2016/8376d68-2c53f2b-3d99a78-93e6ec5

**Comment by krneticz** [comment]
I confirm it is fixed. Thank you very much Roger!

**Comment by tarva** [comment]
I also can confirm this is fixed. 
At least, I was able to use NG site for more than  half hour.

**Comment by cryptedco** [comment]
Yep, MTV, too... but now I have that stupid flash bug - I wonder if anyone else sees an "outdated flash plugin" or is it just me with rc2? #4530
