### ISSUE TITLE
Loading a local file with webview

### ISSUE THREAD

**Issue by hkaya** [nwjs/nw.js#4425]
Hi,

I already wrote about this on [Google Groups](https://groups.google.com/forum/#!topic/nwjs-general/_TY3lWg6qn8) and I wanted to create an issue as well, as I think it's a valid use case:

I'd like to load an html file residing out of the application package in a webview. In 0.12, I can achieve this with:

`<webview src="/absolute/path/to/file.html"></webview>`

However, this method doesn't work in 0.13 since the default protocol changed from `file://` to `chrome-extension://`. So, the above line will result in a load request of `chrome-extension://ext-id/absoulute/path/to/file.html`, which obviously doesn't exist. First thing I tried was to use the file url scheme:

`<webview src="file:///absolute/path/to/file.html"></webview>`

It turned out, most of the url schemes are disabled for webview source tags including `file://`. So the above tag causes the following error:

`<webview>: The load has aborted with error -301: ERR_DISALLOWED_URL_SCHEME.`

The same blocking rules doesn't apply to iframes. I can replace the webview tag with an iframe tag and I can load a local file normally.

I understand that this is the desired behavior for security reasons on a regular Chromium browser but for NWJS perhaps we can disable this limitation or make it configurable. I'd like to know what the maintainers think about this.

Thank you!

**Comment by rogerwang** [comment]
Thanks for reporting. Will like to fix it soon. 

You're right that NW takes a different security model from Browser. We provide a native security model for trusted code while remains the strict W3C model for untrusted contents. So any feature requests under the native model are welcomed.

**Comment by hkaya** [comment]
Thank you Roger. I appreciate the prompt response.

**Comment by yjfdl123** [comment]
If i want load js script in local, what should i do.
Now it will do nothing when i  add js script in html files

**Comment by hkaya** [comment]
@rogerwang I'm getting inconsistent results when using a local file path as the source of the webview. I've tested with 0.13.0, 0.13.0-sdk, 0.13.0-sdk-1, 0.13.0-rc2sdk and 0.13.0-rc4sdk on Linux. Here is my test app:

`index.html:`
```html
<!DOCTYPE html>                                                                                                                                                                                              
<html>
<head>
<body>
  <webview id="wv" partition="trusted" src="file:///path/to/webview.html"></webview>
  <script type="text/javascript">
    // var wv = document.getElementById('wv');
    // wv.src = 'file:///path/to/webview.html';
  </script>
</body>
</html>
```
`package.json:`
```javascript
{
    "name": "app",
    "version": "1.0.0",
    "main": "index.html",
    "webview": {
        "partitions": [
            {
                "name": "trusted",                                                                                                                                                                           
                "accessible_resources": ["<all_urls>"]
            }
        ]
    }
}
```

When I load this app, I *sometimes* get the original ERR_DISALLOWED_URL_SCHEME error and sometimes I see the contents of the webview.html. I don't have a consistent way of reproducing this. You can try to open / close nw window multiple times to verify.

The second test I did was to delete the `src` attribute completely and try to set the value with javascript. When I do that, again I only sometimes see the content. But I never get the error even when I don't see the content. This happens with `wv.src = 'file:///xxx';` as well as with `ww.setAttribute('src', 'file:///xxx');`.

Finally, if I open the dev tools and set the `src` attribute of the webview manually, it works.

Thanks!
