### ISSUE TITLE
node-oracle Native modules built by node-gyp/npm is not supported

### ISSUE THREAD

**Issue by signhuwei** [nwjs/nw.js#4426]
I'm using node-oracledb@1.6.0,npm install and build it with nodejs@5.6.0.
  It's ok in nodejs ENV,but failed in nwjs.
>require('oracledb');
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\orcalTest\node_modules\oracledb\build\Release\oracledb.node

**Comment by rogerwang** [comment]
It works for me under Linux. I guess you forget to set the DLL path in windows?

**Comment by signhuwei** [comment]
OK,i will check it. Thanks!

**Comment by signhuwei** [comment]
Hi,
I have try it.
Actually nw-gyp rebuild oracledb ,it is ok in the seem enviroment(nw0.13,system path,vs2013,jdk1.7,win10X64 .etc)
But node-gyp rebuild ,it only can run in nodejs cmd env

**Comment by rogerwang** [comment]
Did you override `win_delay_load_hook.c` properly?

**Comment by signhuwei** [comment]
yes i did

**Comment by signhuwei** [comment]
Oh!!!!
I am so sorry to waste you time.It's my mistake.
I don't know why to install node-gyp twice,and the second installed module is not 'globle'.
When I uninstall the cwd module of 'node-gyp',it works!

**Comment by notsospecial1** [comment]
@signhuwei  
Would it be possible to detail the process (Windows) you used to successfully use a NODE-GYP processed native module in NW.js 0.13.0.  As described,  NW-GYP is no longer necessary, so your detailed steps could serve as the documentation for how to use ALL non-JS  ("native" CPP) node modules.  This would be a big help for all NW.js users !!   Thank you.

**Comment by rogerwang** [comment]
@notsospecial1  https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ 

will add this to docs.nwjs.io

**Comment by signhuwei** [comment]
I would glad to detail it.But Kevin Fan is completely correct! I don't know what can i do.
>npm install -g node-gyp
replace node-gyp\src\win_delay_load_hook.c with the 
https://github.com/nwjs/nw.js/blob/nw13/tools/win_delay_load_hook.c 
npm install "native-c node module"
The rebuilded module will work well in nw.js 0.13.x

**Comment by edwin1329** [comment]
I feel the same with node-Hid, could update the documentation that is in

[http://docs.nwjs.io/en/v0.13.0-beta6/For%20Users/Advanced/Use%20Native%20Node%20Modules/](url)

to better understand the solution

**Comment by brandonros** [comment]
If a module like node-hid is available via pre-gyp for the native platform, do you need to rebuild it with node-gyp after modifying the .c file?

**Comment by RohitSharma27** [comment]
If you have modified the native module, then yes, you have to rebuild it again.
