### ISSUE TITLE
Large datalist bug in 0.13.0 beta 5 & 6

### ISSUE THREAD

**Issue by Kriknos** [nwjs/nw.js#4428]
Noticed this in 0.13.0 beta 5 first but it has now also happen in beta 6. I can't speak to earlier version as I didn't have the datalist implemented prior to beta 5.

I have a large datalist (500+ options) if I start typing in the related input field all is fine, but if I click the drop down arrow first the screen will go complete black for a second and then it changes the nw.js frame (chrome) appearance. The nw.js normally uses my Windows theme and then I have my "window: icon" and "window: title" set. But after clicking the drop down arrow for the datalist suggestions the frame goes to a slightly darker blue and my title and icon are gone. And there is no way I can fix it. If I close the app and reopen it does not revert, and if I reboot my PC it does not revert.

I originally noticed it in beta 5 but when I updated to beta 6 it did fix it, that is till I clicked the drop down arrow for the datalist again. But this time it also had another effect. I usually have a couple Firefox windows open and for some reason after clicking the datalist drop down arrow it changed the "minimize", "restore", and "close" buttons in the upper right corner of Firefox. Maybe the Firefox thing is unrelated but why it changed when nw.js "glitched" is very odd. I tried reinstalling beta 6 and that did not fix it either.

Edit:
Just tried rebooting my PC again and it did fix the frame/chrome. I had rebooted twice prior posting this and it didn't work, not sure why it worked this time.

**Comment by Christywl** [comment]
@Kriknos , is this issue still reproduce with the latest nwjs? If yes, could you please upload a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
