### ISSUE TITLE
frameless window fullscreen bug on os x

### ISSUE THREAD

**Issue by goosefx** [nwjs/nw.js#443]
Hi, 
I have noticed a bug if a frameless window on os x leaves fullscreen. The system seems to draw a potion of the original resize icon after the window leaves fullscreen.

BTW whats the status of the missing rounded corners on top of the frameless window?

Thanks & keep on with your awesome project!

edit: it is the system fullscreen icon and the icon actually works, so it seems that after enter / leave fullscreen the first time the icon stay visible on frameless windows. Any chance to fix this?

Marcus
![node-webkit](https://f.cloud.github.com/assets/349705/160534/9323fa58-7768-11e2-9cf0-73fd0c7e78aa.png)

**Comment by rogerwang** [comment]
should be fixed with 0.13.0 RC.
