### ISSUE TITLE
Not able to run adobe flash on windows

### ISSUE THREAD

**Issue by rohanbritto** [nwjs/nw.js#4430]
I have latest flash player installed on my system(windows 64 bit). When i try to run flash inside nwjs(0.13.0-beta6) it says "Couldn't load plugin". Any idea about the issue?

**Comment by rohanbritto** [comment]
Adobe flash runs on google chrome browser. What is the issue with nwjs?

**Comment by rogerwang** [comment]
It tries to load the pepper API based Adobe flash plugin in bundle path: 'PepperFlash' sub-directory under the same directory where nw binaries resides. If failed, it will try to load the system flash plugin by looking up '"SOFTWARE\\Macromedia\\FlashPlayerPepper"' in the registry.

**Comment by rohanbritto** [comment]
Hey Roger,

I have downloaded PPAPI based flash player and checked , flash is running.
But I have installed it on my system, I want it to work through PepperFlash subdirectory in nwjs bundle.
I have tried following on machine where Adobe Flash with PPAPI is not installed:

I have copied all the files from  flash folder installed in System to PepperFlash folder inside nwjs directoy and then package them into test.new

Directory Structure:
test.nw
    -package.json
    -main.html
    -PepperFlash(contains pepperflash plugin files.)

But it still says "Couldn't load plugin". 
I have tried adding following in package.json file:
"chromium-args": "--ppapi-flash-path=path_to_pepperflash_directory/pepflashplayer64_20_0_0_306.dll --ppapi-flash-version=20.0.0.306",

But it didn't work.
Can you guide me where am i going wrong?
