### ISSUE TITLE
v0.12.3, `gui.Window.open('http://www.xxxx.com')` just crash on windows 10.

### ISSUE THREAD

**Issue by qdwang** [nwjs/nw.js#4431]
```
{
    "main": "loader.html",
    "name": "abc"
}
```

in `package.json`

```
<script type="text/javascript">
var gui = require('nw.gui');
gui.Window.open('http://www.xxxx.com'); // The app will just crash on this code. (only local path will not cause the problem)
</script>
```

in `loader.html`

**Comment by krum110487** [comment]
does adding `"node-remote": "*"` to your `package.json` prevent it from crashing?

If it does, at least that would make sense, as without node-remote, you shouldn't be able to do http sites, only local.

It still shouldn't crash, but at least that is more information for them to go off of.

**Comment by Christywl** [comment]
I can't reproduce on Windows/Linux with nwjs-sdk-v0.22.0. The second window opens successfully, no crash. @qdwang , could you please check on the latest nwjs?

**Comment by Christywl** [comment]
close until there is more information.
