### ISSUE TITLE
13.0-beta6: Access the chrome.privacy.* extension API to avoid WebRTC rampage

### ISSUE THREAD

**Issue by cryptedco** [nwjs/nw.js#4432]
The current (up to 49) Chromium release is not blocking IP leaks via WebRTC (search for "WebRTC IP leaks"), allowing every website to retrieve all locally available IP numbers via the browser. In order to block and avoid that, the chrome.privacy.\* namespace must be addressed and is not available in the current release.

Something like:

```
'use strict';

var pn = chrome.privacy.network;
var pi = chrome.privacy.IPHandlingPolicy;

chrome.runtime.onStartup.addListener(function(){
    pn.webRTCIPHandlingPolicy.set({
        value: pi.DISABLE_NON_PROXIED_UDP
    }, function() {});
});
```

has no effects on the leak when called as a plugin on start-up.

**Comment by ghostoy** [comment]
According to Chrome App document, `chrome.runtime.onStartup` is fired when a profile that has this extension installed **first starts up**. If I understand right, it will not fire after the first run.

In your case, you may need [`chrome.app.runtime.onLaunched`](https://developer.chrome.com/apps/app_runtime#event-onLaunched) and run it in background page (See [`bg-script`](http://docs.nwjs.io/en/v0.13.0-beta6/References/Manifest%20Format/#bg-script))

**Comment by cryptedco** [comment]
hi ghostoy, I tried different places to address the chrome.privacy. namespace and mentioned that to Roger in the googlegroup:

https://groups.google.com/forum/#!topic/nwjs-general/xGVHu1PBJ6o

I think he confirmed that the .privacy namespace is not available YET and will include that in one of the coming releases.

You can test the WebRTC leak on different pages, one I found is this:

https://whoer.net/#extended

scroll down to "Interactive detection" and see, what WebRTC is blasting out for you!

**Comment by rogerwang** [comment]
@cryptedco I checked the latest nightly build, chrome.privacy API is available.

**Comment by rogerwang** [comment]
Could you please provide a sample demonstrating the issue?

**Comment by cryptedco** [comment]
Thanks for looking into this! I am not sure, if I am missing something:

I do a

`
chrome.app.runtime.onLaunched.addListener(function() {
    var pn = chrome.privacy.network;
    var pi = chrome.privacy.IPHandlingPolicy;

    pn.webRTCIPHandlingPolicy.set({
        value: pi.DEFAULT_PUBLIC_INTERFACE_ONLY
       // or     value: pi.DISABLE_NON_PROXIED_UDP 
    });
    chrome.app.window.create('index.html', {
        'outerBounds': {
            'width': 1000,
            'height': 800
        }
    });
});
`

and have the permission set in the manifest:

`...
  "permissions": [
    "node",
    "privacy"
  ],
  "app": {
    "background": {
      "scripts": [
        "background.js"
      ]
    }
  },
....`

Then I set the proxy with 
`gui.App.setProxyConfig("my.proxy.ip");`

which works fine and I can see the value set by:

`chrome.privacy.network.webRTCIPHandlingPolicy.get({}, function(details) {
        alert(details.value); })`


then I go to one of the tests sites to see, if my IPs are still leaked and see them all on
https://whoer.net/#extended (interactive detection) 
under the WebRTC test...

Now I suspect that the privacy settings are only valid within the app, is that right? Or these set and just have no effect?

Clueless :-?

Thanks,
Ralf

**Comment by cryptedco** [comment]
I have also set the deprecated value:

`pn.webRTCNonProxiedUdpEnabled.set({value: false});``

which is set, but has no effect either... So, after much testing and trying to understand, if it is possible to disable the WebRTC leak in the current release... I think I am either still not smart enough or it just does not work...

I think of this as a serious security issue like these guys put it nicely - http://www.slimjet.com/en/how-to-disable-webrtc-in-chrome.php

**Comment by rogerwang** [comment]
Could you please upload your sample somewhere so we can try it?

Ralf Schwoebel <notifications@github.com>于2016年2月25日周四 下午7:48写道：

**Comment by cryptedco** [comment]
hi,

thanks, roger: https://www.dropbox.com/s/nlvc7z7hxra70sd/webrtcleak-nw.tgz?dl=0

very simple with an open proxy of mine, which will be closed when we are done...

**Comment by cryptedco** [comment]
Let me know, when I could remove the open proxy from the world, pls :-)

**Comment by cryptedco** [comment]
removing the file from dropbox, uploading it here as an example.... 
[webrtcleak.zip](https://github.com/nwjs/nw.js/files/150641/webrtcleak.zip)

manifest.json: defines the rights including "privacy"
background.js: sets the value to DISABLE_NON_PROXIED_UDP
index.html: gives you the clicks to show the value, set the proxy and then go to a UDP STUN test to find out your REAL ip number... especially bad, when you have cable, phone tethering and wifi, you get a lot of private IPs...

I will remove the file from dropbox now...

**Comment by Christywl** [comment]
I try this on my device with nwjs-sdk-v0.26.2. 
1. Launch the app
2. Click `Goto leak testing site to see your local IPs` and I could see the IP
3. Click `Set Open Proxy Provided for this test` and set the proxy
4. Click `Goto leak testing site to see your local IPs` again and the website can't be opened.
![image](https://user-images.githubusercontent.com/20039821/32314681-030534ae-bfe4-11e7-8383-960c3e2c8581.png)

**Comment by Christywl** [comment]
close until there is more information
