### ISSUE TITLE
Nw13 –If invalid certificate is proceed webview freezes

### ISSUE THREAD

**Issue by janRucka** [nwjs/nw.js#4433]
If webview is navigated to website without valid certificate (e.g. https://expired.badssl.com/ ) then there is usual ‘Your connection is not private’ page showed. But when ‘Advance’ and then ‘Proceed to expired.badssl.com (unsafe)’ is clicked webview is frozen. ‘Your connection is not private’ page is showed and there is no way to proceed to wanted page (page is visible but not responsible). Cookies are remembered so next time it works (without ‘Your connection is not private’ page).

Strange thing is that I get all events (e.g. "loadstart", "loadstop", "loadprogress") as if everything is Ok.

Unfortunately the issue is not 100% reproducible. On my computer (W7 64bit) I was able to reproduce it 10/10 but on another computer only sometimes (with also several times in row without reproducing).

When I tried it in debug build I sometimes get following error (see screenshot). Not 100% sure it is connected but it is certainly not Ok.

![error](https://cloud.githubusercontent.com/assets/16557373/13217822/95b39bfe-d965-11e5-90bd-3b9f70d8673c.png)

Also there is my minimal reproducing code:
[certificate.zip](https://github.com/nwjs/nw.js/files/140603/certificate.zip)

**Comment by rogerwang** [comment]
which version are you using?

**Comment by rogerwang** [comment]
btw, could you please run nw with logging enabled and use '--v=1' in the command line and send the log to me?

https://www.chromium.org/for-testers/enable-logging

**Comment by janRucka** [comment]
I wasn't able to run nwjs with --v=1 in release version. Is that Ok?
I used version from http://nwjs.io/ website: nwjs-sdk-v0.13.0-beta6-win-x64.zip

Then debug version builded by me with this latest commit:

chromium:
Revision: 954f9e50b70551b9c7ee75e0d080bde70a21f6b3
Author: Roger Wang <roger.wang@intel.com>
Date: 22.2.2016 10:27:57
Message:
NWJS master patch

nw:
Revision: 962e194c340a4e0291c376cf3eaf4b2e5ceb9a60
Author: Roger Wang <roger.wang@intel.com>
Date: 22.2.2016 3:24:10
Message:
docs and implementation for headless devtools in webview


My debug verssion was used for logging since release didn't work for me. But it is reproducible with both (release and debug) .

[chrome_debug.txt](https://github.com/nwjs/nw.js/files/142230/chrome_debug.txt)

[debug.txt](https://github.com/nwjs/nw.js/files/142231/debug.txt)

**Comment by janRucka** [comment]
Any progress? Did you have time to investigate it any further? Is it reproducible for you? I find it to be a critical issue and for our usage it is a blocker in update to nw13 (since it is working in 12.3).

**Comment by janRucka** [comment]
It seems not to be reproducible with latest version (rc2 live) for me. Good work with fixing it. I will close it as soon as I am able to try it with debug version (blocked with #4497).

**Comment by janRucka** [comment]
Works fine with debug as well. Well done.
