### ISSUE TITLE
What is the blue line in the bottom of my app? How can I remove it?

### ISSUE THREAD

**Issue by phamhongphuc** [nwjs/nw.js#4434]
This is my app when unmaximize with a custom title bar
(tut)( dineshs91.github.io/blog/post/custom_titlebar/ )
![image](https://cloud.githubusercontent.com/assets/11532116/13222286/a0eac102-d9c2-11e5-9ecd-527e80e7e851.png)

And when maximize
![image](https://cloud.githubusercontent.com/assets/11532116/13222252/7d1b9da0-d9c2-11e5-8a5e-585d14fcbf81.png)
zoom
![image](https://cloud.githubusercontent.com/assets/11532116/13222262/89e57c18-d9c2-11e5-8121-fe23fd9e9535.png)

What is the blue line in the bottom of my app? How can I remove it?

**Comment by Christywl** [comment]
@phamhongphuc , could you please upload your sample to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
