### ISSUE TITLE
0.13 beta6 dev tools show blank

### ISSUE THREAD

**Issue by qdwang** [nwjs/nw.js#4438]
![kcfp443xd9n fyze4cdcc y](https://cloud.githubusercontent.com/assets/403616/13240302/8a16b7c4-da1c-11e5-8eb3-33797a74bdd3.jpg)

**Comment by ghostoy** [comment]
Could you post a full sample app and steps to reproduce the issue?

**Comment by iteufel** [comment]
Try using the sdk build.

**Comment by ghostoy** [comment]
@iteufel I can't reproduce it with either beta6 or beta7 on Windows 8.1. My test app is simple:

```html
<button onclick="showDevTools()">Show DevTools</button>
<script>
function showDevTools() {
  nw.Window.get().showDevTools();
}
showDevTools();
</script>
```

**Comment by iteufel** [comment]
I think @qdwang used the NORMAL build not the SDK one.
The NORMAL build opens just an Empty DevTools Window.
The SDK build works fine.

**Comment by hisune** [comment]
@iteufel What is SDK build?

**Comment by camilom** [comment]
install sdk version http://nwjs.io/, the normal version have this problem
