### ISSUE TITLE
13.0 Enable chrome.devtools api

### ISSUE THREAD

**Issue by jmx** [nwjs/nw.js#4440]
Hi there

It'd be great if we could enable the devtools api so that devtools extensions can be added. (for example https://github.com/cerebral/cerebral-chrome-extension)

for example chrome.devtools.panels.create(...

Is there another way of achieving this because I'm quite willing to code around this if I can be pointed in the right direction?

**Comment by rogerwang** [comment]
there should already be supported according to test by @ghostoy

**Comment by rogerwang** [comment]
I just checked, there is no 'chrome.devtools' exposed. comments? @ghostoy 

It shouldn't be hard to be enabled. See also on our recent updates on #612

**Comment by jmx** [comment]
I should mention here I've got extensions to load using the mechanism mentioned in #612 (this may help for other types of extension), however the missing piece of the puzzle is the lack of "tabid" for chrome extensions, meaning that the extension cannot inject scripts into the target page and similarly can't use the chrome.tabs.sendMessage call to communicate.

**Comment by rogerwang** [comment]
devtools API is actually supported, so merge this issue with #612
