### ISSUE TITLE
How can i use the "--process-per-tab" "--process-per-site"args?

### ISSUE THREAD

**Issue by lee99** [nwjs/nw.js#4441]
I tried to add the args in "chromium-args",but it seem not work...

**Comment by rogerwang** [comment]
Why do you want to use this? There is no 'tab' in NW...

**Comment by lee99** [comment]
e~~

In my project, we need a multi-tabbed browser. Upload pictures like that.
All feature I have done, makes me very troubled by a few questions.

1. sometimes <webview>: "ERR_ABORTED" error.
2. All <webview> tag, sometimes get stuck. You can view, but not clickable.
3. I find it hard to debug error

............
![nb](https://cloud.githubusercontent.com/assets/2275619/13244752/b70bf8d0-da43-11e5-964c-b121fd6564b9.jpg)
![nb2](https://cloud.githubusercontent.com/assets/2275619/13244790/f95f66ea-da43-11e5-994e-264f1c0747ff.jpg)

**Comment by rogerwang** [comment]
All your questions are not related to the command line switches you asked. If you need help, please post your question with detail to our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
