### ISSUE TITLE
win.isFullscreen is a function

### ISSUE THREAD

**Issue by iteufel** [nwjs/nw.js#4446]
win.isFullscreen is a function but it should be a boolean.

version: v0.13.0-beta6

```
NWWindow.prototype.isFullscreen = function () {
  return this.appWindow.isFullscreen();
};
```

**Comment by chaseWillden** [comment]
I agree with this. I created a pull request here: [4448](https://github.com/nwjs/nw.js/pull/4448)

**Comment by iteufel** [comment]
@rogerwang This should be fixed or the [documentation](http://nwjs.readthedocs.org/en/latest/References/Window/) must be changed.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
