### ISSUE TITLE
Cross domain & WebGL

### ISSUE THREAD

**Issue by ParksProjets** [nwjs/nw.js#4447]
Hi,

I don't know if it's normal but the Cross Domain Policy applies in the WebGLRenderingContext even if it's a Node frames and must "Bypass all security restrictions".

Indeed, in [this file](https://github.com/nwjs/blink/blob/27b680078f32e59d6aabcbd63747e164997d3dd2/Source/core/html/canvas/WebGLRenderingContextBase.cpp), line 5463, Blink looks if the video respect the Cross Domain Policy.

``` js
bool WebGLRenderingContextBase::validateHTMLVideoElement(const char* functionName, HTMLVideoElement* video, ExceptionState& exceptionState)
{
    if (!video || !video->videoWidth() || !video->videoHeight()) {
        synthesizeGLError(GL_INVALID_VALUE, functionName, "no video");
        return false;
    }

    if (wouldTaintOrigin(video)) {
        exceptionState.throwSecurityError("The video element contains cross-origin data, and may not be loaded.");
        return false;
    }
    return true;
}
```

And the function "wouldTaintOrigin" does not return "false" all the time, as I expect. [source, line 319](https://github.com/nwjs/blink/blob/27b680078f32e59d6aabcbd63747e164997d3dd2/Source/core/html/HTMLVideoElement.cpp)

``` js
bool HTMLVideoElement::wouldTaintOrigin(SecurityOrigin* destinationSecurityOrigin) const
{
    return !hasSingleSecurityOrigin() || (!(webMediaPlayer() && webMediaPlayer()->didPassCORSAccessCheck()) && destinationSecurityOrigin->taintsCanvas(currentSrc()));
}

```

I think the Cross Domain Policy was not disabled for all media (video, image) and this will be a problem because in the next version of Blink, MediaElementAudioSourceNode will be conserned by  the Cross Domain Policy ([source](https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/webaudio/MediaElementAudioSourceNode.cpp)).

**Comment by rogerwang** [comment]
Please provide a sample and we'll support it in the Node security model.

**Comment by Christywl** [comment]
close until there is more information
