### ISSUE TITLE
[nw13 bug] :webview losing cookies and storage after application is closed 

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#4449]
hi 

i find webview will losing cookies and storages(localStorage, db .etc) after application is closed ,  even  using same partition persist ID.

OS Env :

- Mac
- Win7

**Comment by rogerwang** [comment]
It works for me with this sample: https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webview-samples/webview

**Comment by lin-chao** [comment]
oh sorry, i made a mistake

i read chrome webview document again and find

> If the ID is unset or if there is no 'persist': prefix, the webview will use an in-memory storage partition

and i used react, the attribute not real set to the dom.

![image](https://cloud.githubusercontent.com/assets/3161552/13285701/f5fe04f4-db36-11e5-8968-0c7075f7ac22.png)
