### ISSUE TITLE
[Mac] Crash dumps doesn't match hashes of symbol files

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#4450]
Manually triggering crashes with `nw.App.crashRenderer()` will generate crash dump files in `~/Library/Application Support/<app-name>/Crashpad/completed/`. Then decode the crash dump with `minidump_stackwalk` without symbol files to get the missing modules with hashes.

For 0.13.0-beta6, the expected hashes of crash dump reported by `minidump_stackwalk` are:

* nwjs Helper: 6DF796881593398486DD1562F11FB80B0
* nwjs Framework: 2076ED1863F130249C6F7AFECAC59FD70
* libnode.dylib: F19C267F429F37E0AA0721C5FE2719290

However the downloaded symbol files have different hashes:

* nwjs Helper: 6C36191D656F3A938B5EEF1548F0919E0
* nwjs Framework: 568D8E03EC8034A5B4EE86434B98E1820
* libnode.dylib: 38356D52AC5A304AA114817D1E51BFAD0

Also the symbol files contain almost meaningless names like:

```none
MODULE mac x86_64 38356D52AC5A304AA114817D1E51BFAD0 libnode.dylib
FUNC bc0 90 0 __ZN4node8debugger5AgentC1EPNS_11EnvironmentE
FUNC c50 100 0 __ZN4node8debugger5AgentD2Ev
FUNC d50 f0 0 __ZN4node8debugger5Agent4StopEv
FUNC e40 c0 0 __ZN4node8debugger5Agent5StartEib
FUNC f00 1c0 0 __ZN4node8debugger5Agent13ChildSignalCbEP10uv_async_s
FUNC 10c0 10 0 __ZN4node8debugger5Agent8ThreadCbEPS1_
FUNC 10d0 40 0 __ZN4node8debugger5Agent6EnableEv
FUNC 1110 130 0 __ZN4node8debugger5Agent14MessageHandlerERKN2v85Debug7MessageE
```

**Comment by jtg-gg** [comment]
@rogerwang / @ghostoy now I have problem in nwjs packaging in osx, it says it can't find "                'nwjs.breakpad.tar' which was created by https://github.com/nwjs/nw.js/commit/dec84d61f15ef6b1ef492c152b050317d96ee402

so how we distribute the symbol file ?

**Comment by rogerwang** [comment]
I think you did set mac_breakpad=1. Please refer to the official buildbot for build steps and configurations: http://buildbot-master.node-webkit.org:8010/builders/nw13_sdk_mac64/builds/272

**Comment by jtg-gg** [comment]
@rogerwang I've just added mac_breakpad=1, my build still fail on packaging due to missing 'nwjs.breakpad.tar'. it only happens if you start clean / empty because 'nwjs.breakpad.tar' never created if you start clean

**Comment by rogerwang** [comment]
It's now done here:
https://github.com/nwjs/chromium.src/blob/nw13/chrome/chrome_exe.gypi#L248
