### ISSUE TITLE
How can I know my app is shown or hidden??

### ISSUE THREAD

**Issue by malin1988** [nwjs/nw.js#4455]
is there any api for me to check if my app is opened and shown in desktop or hidden in task bar?

**Comment by cryptedco** [comment]
you could check win.x and win.y (and win.isFullscreen) to see, if the window is there... or minimized...

**Comment by malin1988** [comment]
@cryptedco ,thanks for your answer,i used win.x and y to implement it. I hope NW could offer official API for this function in future :).

**Comment by cryptedco** [comment]
:-) I know it is not elegant, but hey - if it gets the job done...
