### ISSUE TITLE
0.13 beta7 - the app asks for confidential information for NWJS Safe Storage in keychain

### ISSUE THREAD

**Issue by cuongle121** [nwjs/nw.js#4458]
Hi,
Thanks for great project.

I updated my project from beta6 to beta7 today. When I run my app on Mac, this dialog bellow appear:
<img width="437" alt="bitmark" src="https://cloud.githubusercontent.com/assets/3232472/13347334/a834999e-dc9f-11e5-9992-40d6e0ecd9c5.png">

I tried to make a sample by creating a totally new project with the `index.html` containing only some code to change some values in localStorage, and it does not show this dialog.
I will try to provide a sample later. But is the picture enough for you to guess what causing the dialog?

Thanks.

**Comment by cryptedco** [comment]
Are you using a webview?

**Comment by lee99** [comment]
yes! webview +1

**Comment by cuongle121** [comment]
hi @cryptedco , sorry for missing your comment. I am not using any webview in my app. But I am using an iframe. I am not sure if it is causing the dialog, but I have not seen it again for a while. I still do not know how to make it appear again.

**Comment by cryptedco** [comment]
I see it on Mac every time I start my app with a new release on nwjs13... like a fresh set of security rules being accepted. Also happens, when I sign the app with my Dev Certs ...

**Comment by Steveorevo** [comment]
RC1 here too. It's a "show stopper" for us. Anyway to avoid this?

**Comment by rogerwang** [comment]
fixed in git and will be available in the next nightly build.
