### ISSUE TITLE
How to include browser extension in nwjs

### ISSUE THREAD

**Issue by abhimanyubind** [nwjs/nw.js#4461]
I have created a browser extension and added it in chrome browser. 
How can i use it in nwjs?

**Comment by vivekgaikwad** [comment]
The extension include two javascript files, 3 image files, manifest.json file.

**Comment by cryptedco** [comment]
You can try to use '--load-extension=<path>' to load your unpacked extension ...

**Comment by rogerwang** [comment]
@cryptedco is correct.

**Comment by rogerwang** [comment]
and please submit questions to the mailing list: https://groups.google.com/forum/#!forum/nwjs-general
