### ISSUE TITLE
13.0-beta7: mtv.com crashes

### ISSUE THREAD

**Issue by cryptedco** [nwjs/nw.js#4465]
Because in terms of "not so good html and javascript practices", I always test against MTV.com ... 
When I surf to mtv.com and click on "Shows" in the main menu, nwjs13.0-beta7 on Mac 10.11.3 goes bye bye with

Feb 27 20:40:49  nwjs Helper[15381] <Error>: CGAffineTransformInvert: singular matrix.
Received signal 11 SEGV_MAPERR 000000000038
 [0x000106f941da]
 [0x7fff9965ceaa]
 [0x0ef7ed0fd610]
 [0x0001093e1c54]
 [0x0001095504e2]
 [0x3b7264d2b5d6]
[end of stack trace]

in a plain app.

**Comment by rogerwang** [comment]
Hi, I tried it with launching nw with --url="http://www.mtv.com" and it works for me. Could you please upload a full sample?

**Comment by cryptedco** [comment]
[app.nw.zip](https://github.com/nwjs/nw.js/files/150626/app.nw.zip)

here you go, plain app - opens index.html: follow the link, then click "full episodes" under "shows"... nwjs goes away... at least for me on Mac...

**Comment by cryptedco** [comment]
Downloaded the nightly build beta8 just now... tried it again: it works, no crash anymore! Whatever it was, you found it... closed!
