### ISSUE TITLE
0.13 beta 7 fails to start on OSX with case sensitive file system

### ISSUE THREAD

**Issue by zedesk** [nwjs/nw.js#4466]
On my macbook pro, my file system is case sensitive, and I can't start nwjs, and I think it's due to some inconsistency in the filenames case.

When I triy to open nwjs.app ( sdk and normal version ) I've got an error dialog box : 'nwjs left unexpectedly.'

when i try to open thanks to command line : `open -a nwjs.app` I've got the following error :

LSOpenURLsWithRole() failed for the application /Users/fablec/Desktop/nwjs-v0.13.0-beta7-osx-x64/nwjs.app with error -10810.

and when i try : `nwjs.app/Contents/MacOS/nwjs` 

dlopen /Users/fablec/Desktop/nwjs-sdk-v0.13.1.0-beta7-osx-x64/nwjs.app/Contents/MacOS/../Versions/48.0.2564.116/NWJS Framework.framework/NWJS Framework: dlopen(/Users/fablec/Desktop/nwjs-sdk-v0.13.1.0-beta7-osx-x64/nwjs.app/Contents/MacOS/../Versions/48.0.2564.116/NWJS Framework.framework/NWJS Framework, 257): image not found
Abort trap: 6

if I rename `nwjs Framework.framework/nwjs Framework` to `NWJS Framework.framework/NWJS Framework`

[0229/045222:ERROR:icu_util.cc(127)] icudtl.dat not found in bundle
[0229/045222:ERROR:icu_util.cc(146)] Invalid file descriptor to ICU data received.
[0229/045222:FATAL:content_main_runner.cc(721)] Check failed: base::i18n::InitializeICU().
0   NWJS Framework                      0x000000010ebf72f3 ChromeMain + 5228483
1   NWJS Framework                      0x000000010ec0edd9 ChromeMain + 5325481
2   NWJS Framework                      0x000000010eba7c29 ChromeMain + 4903161
3   NWJS Framework                      0x000000010eba73be ChromeMain + 4901006
4   NWJS Framework                      0x000000010e6fab72 ChromeMain + 66
5   nwjs                                0x000000010e493d52 main + 530
6   nwjs                                0x000000010e493b34 nwjs + 2868

Trace/BPT trap: 5

**Comment by rogerwang** [comment]
fixed in git and will be available in the next nightly build.

**Comment by GeorgeNava** [comment]
I am having this same problem, just installed nwjs 0.17.1 on OSX 10.9.5 and on running nwjs I get this:

dlopen /usr/local/bin/../Versions/53.0.2785.101/nwjs Framework.framework/nwjs Framework: dlopen(/usr/local/bin/../Versions/53.0.2785.101/nwjs Framework.framework/nwjs Framework, 257): image not found
Abort trap: 6

This is the output from node -pe process.versions

{ http_parser: '2.5.0',
  node: '5.0.0',
  v8: '4.6.85.28',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2d' }

Any help would be appreciated.
