### ISSUE TITLE
请问这个ip有什么用么？140.205.134.25:443

### ISSUE THREAD

**Issue by lee99** [nwjs/nw.js#4468]
@rogerwang 

140.205.134.25:443

![qq 20160229170144](https://cloud.githubusercontent.com/assets/2275619/13390005/74ea2680-df06-11e5-98e9-7608c5841912.png)

我的程序里没有任何关于阿里或这个IP的程序。

**Comment by ghostoy** [comment]
It doesn't look like sending by NW. Any NW app can make network request.

**Comment by lee99** [comment]
My problem is, I used to visit other website, this information do not appear, this message appears when i did nothing.

**Comment by rogerwang** [comment]
I can't reproduce this. There is only known issues about accessing Google
services by the code from Chrome browser.

Btw, please use English here so all users can read.

lee99 <notifications@github.com>于2016年2月29日周一 下午6:14写道：

**Comment by gitawego** [comment]
I think it might be sent by spyware integrated in 360zip or an ad. script in your application using alibaba advertising service (like google ad.). this ip is from Hangzhou Alibaba Advertising Co.,Ltd.
