### ISSUE TITLE
child_process.spawn doesn't work when first parameter is 'node'.

### ISSUE THREAD

**Issue by littledream2015** [nwjs/nw.js#4470]
when I use spawn like 'child_process.spawn('ls')',it really works, but when I try to use 'child_process.spawn("node",['--version'])',there is no response. is it a issue? Is there any solution for this? tks. because I want use spawn to run node command.

**Comment by ghostoy** [comment]
Cannot reproduce the issue with 0.13.0 beta7.
Do you have node installed? If yes, could you post a full sample app?

**Comment by Christywl** [comment]
@littledream2015 , is this issue still reproduced in your test? If yes, could you please upload a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
