### ISSUE TITLE
Error when trying to run the "ref" native module.

### ISSUE THREAD

**Issue by rodrigopandini** [nwjs/nw.js#4474]
I´m trying to run [node-ffi](https://github.com/node-ffi/node-ffi) module in the new NW 0.13.0-beta7, but I got this error:

```
Uncaught Error: Could not locate the bindings file. Tried:
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\build\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\build\Debug\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\build\Release\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\out\Debug\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\Debug\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\out\Release\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\Release\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\build\default\binding.node
 → C:\Users\Usuario\Documents\Aha\node_modules\ref\compiled\5.6.0\win32\x64\binding.node
```

The file `node_modules\ref\build\Release\binding.node` exists.
When I run on node it´s working.
I´m using Win7, 64bits.

**Comment by ghostoy** [comment]
I can't reproduce this issue with beta7. Two questions for you:

* Did you install node-ffi directly with **`npm`** by following [the doc](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/)? Or did you use the old way of using `nw-gyp`?
* Did you use same **architecture** (x64 or ia32) and **version** of NW.js and Node.js? For 0.13.0 beta7, the Node.js version should be 5.7.0.

**Comment by bachlx-bitmark** [comment]
I have the same error, I had using node 5.7 for nwjs 0.13.0 beta7 on Win7-64bit.
I created a sample for my error.
[nw-demo.zip](https://github.com/nwjs/nw.js/files/154674/nw-demo.zip)
Please check.
Thanks!

**Comment by rodrigopandini** [comment]
I´m using the new way. Just run `npm install ffi --save`.
Node v5.7.0, arch x64 (Win7-64bit) and nwjs-sdk-v0.13.0-beta7-win-x64

Check this simple demo:
package.json:
```json
{
  "name": "nwjs_ref",
  "main": "index.html",
  "dependencies": {
    "ffi": "^2.0.0"
  }
}
```
index.html:
```html
<!DOCTYPE html>
<html>
<head>
  <title>My OS Platform</title>
</head>
<body>
<!-- <script src="app.js"></script> -->
<script src="app2.js"></script>
</body>
</html>
```
app.js:
```js
var ffi = require('ffi'),
    ref = require('ref');

function call(nCode, wParam, lParam){
    console.log(lParam);
    return user32.CallNextHookEx(nCode, wParam, lParam);
}

var intPtr = ref.refType('int');
var funcPtr = ffi.Callback(intPtr, ['int', intPtr, intPtr], call);

var user32 = new ffi.Library('user32', {
    'SetWindowsHookExW': [intPtr, ['int', 'pointer', intPtr, 'int']],
    'CallNextHookEx': [intPtr, ['int', intPtr ,intPtr]],
    'UnhookWindowsHookEx': ['bool', [intPtr]],
});

var hook = user32.SetWindowsHookExW(13, funcPtr, ref.NULL, 0);

console.log(hook);
```
app2.js:
```js
var ref = require('ref')
 
// so we can all agree that a buffer with the int value written 
// to it could be represented as an "int *" 
var buf = new Buffer(4)
buf.writeInt32LE(12345, 0)
 
// first, what is the memory address of the buffer? 
console.log(buf.address())  // ← 140362165284824 
 
// using `ref`, you can set the "type", and gain magic abilities! 
buf.type = ref.types.int
 
// now we can dereference to get the "meaningful" value 
console.log(buf.deref())  // ← 12345 
 
 
// you can also get references to the original buffer if you need it. 
// this buffer could be thought of as an "int **" 
var one = buf.ref()
 
// and you can dereference all the way back down to an int 
console.log(one.deref().deref())  // ← 12345 
```
![node_ref](https://cloud.githubusercontent.com/assets/641525/13460696/27ae5548-e05b-11e5-8320-f47638f11888.png)

**Comment by ghostoy** [comment]
I still can't reproduce this issue. I guess you may patched a wrong `node-gyp`. `node-gyp` used by `npm` is located in `npm`'s installation directory. You can run `npm` and get the installation direction in the last line, something like `npm@3.6.0 C:\Program Files\nodejs\node_modules\npm`. Then the `node-gyp` is in `<npm-path>\node_modules\node-gyp`.

**Comment by rodrigopandini** [comment]
OK , I think that was my mistake. 
After replace the `win_delay_load_hook.c` file, I forgot to go inside the `ref` module and run the command:
```sh
node-gyp rebuild
```
Note: 
To work, I replaces the `win_delay_load_hook.c` file in AppData directory, not in npm instalation directory. 
`C:\Users\Usuario\AppData\Roaming\npm\node_modules\node-gyp\src\`

Question: 
Can I still use the new `win_delay_load_hook.c` file to build native modules that I use in node.js, not in nw.js? 
Or I need change and replace this file every time that I will build for node.js or for nw.js?

Thank you.

**Comment by ghostoy** [comment]
@rodrigopandini I'm updating docs in PR#4483.

You can directly use `npm` to build native modules for NW.js. When using `npm` you should patch `node-gyp` **inside** `npm`.
Or if you want to manually build with `node-gyp`, you should patch the **globally installed `node-gyp`**. In this case, you have to build **each native module**.

You only have to patch `node-gyp` once when you just installed or upgraded `npm`.

**Comment by RohitSharma27** [comment]
I am trying to run node-ref module on mac OS X El Capitan using the below command

> sudo npm install ref@1.2.0
This is working fine but when I am trying to configure it using 

> nw-gyp configure --target=0.13.0 --target-arch=x64
I am getting the following error message.
```
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/nw-gyp/lib/configure.js:361:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "configure" "--target=0.13.0" "--target-arch=x64"
gyp ERR! cwd /Users/rohit/node-webkit-html5-desktop/imeet-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/ref
gyp ERR! node -v v0.10.44
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok ``
```

I am trying to port my app from nw 0.12.3 to 0.13.0
I am using node v0.10.44 because I have to use ffi module as well.
This was running fine on nw 0.12.3 but i am sort of stuck here.
I can't use node v5.9.0 as of now because I have got to use ffi module(which only works till node v0.10.x) to get the application running on nw 0.13.0.
I basically need to run ref, ffi, ref-struct and sqlite3 module. Even if I use node v5.9.0 and build with node-gyp ref, ffi and ref-struct are looking to build fine, but I am getting error with the sqlite3 module and everything rolls back. All ref, ffi and ref-struct modules get deleted.
I am using the below command to build sqlite3 module. 

> sudo npm install sqlite3@3.1.0 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.13.0

I have gone through the nw 0.13.0 documentation and wiki pages of these modules, but I am still stuck. Please help me with this.

Thanks.
