### ISSUE TITLE
require("ffi") giving "Module version mismatch."

### ISSUE THREAD

**Issue by altelante** [nwjs/nw.js#4478]
Hi,
my setup details:
Windows 10 64 Bit
NW.JS 0.12.3
io.js v1.2.0
Chromium 41.0.2272.76
Python 2.7
Visual Studio 2015
Node.js v4.3.1
Node-Gyp v3.3.0

The steps I did to install & build ffi:
cd *project dir*
npm install ffi ---> success (created node_modules/ffi & builded successfully using node-gyp)
cd *ffi dir*
nw-gyp rebuild --target=0.12.3 --msvs_version=2015 ---> success

```
OUTPUT:
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file C:\****\node_modules\ffi\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  closures.c
  java_raw_api.c
  ffi.c
  ffi.vcxproj -> C:\*****\node_modules\ffi\build\Release\\libffi.lib
  threaded_callback_invokation.cc
  callback_info.cc
  ffi.cc
  win32-dlfcn.cc
     Creating library C:\*****\\node_modules\ffi\build\Release\ffi_bindings.lib and object C:\Sh
  ay\Work\NWJS\projects\scale\node_modules\ffi\build\Release\ffi_bindings.exp
  Generating code
  Finished generating code
  ffi_bindings.vcxproj -> C:\*****\node_modules\ffi\build\Release\\ffi_bindings.node
gyp info ok
```

then when I run my project using "nw.exe *projectdir*" the project runs but if I open console and try
var ffi = require("ffi"); I get:
Error {stack: (...), message: "Module version mismatch. Expected 43, got 46."}message: "Module version mismatch. Expected 43, got 46."stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: d

**Comment by altelante** [comment]
After further testing & reading I managed to make it work.
Apparently, when you use nw-gyp rebuild on a module (ffi) you also need to go to each submodule and rebuild it manually. In my case it was "ref".

The following doc explains it:
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/

**Comment by rodrigopandini** [comment]
Just a note: 
There is the [gypls](https://github.com/evanlucas/gypls) module that "_Recursively list all dependencies that have a gypfile_". 
This can help you if you don't know exactly the dependencies in your project.
