### ISSUE TITLE
Disable After Crash Dialog

### ISSUE THREAD

**Issue by lahdekorpi** [nwjs/nw.js#448]
1. Make node-webkit crash
2. Reopen node-webkit
3. This happens:

![Kuvankaappaus 2013-2-19 kello 15 05 44](https://f.cloud.github.com/assets/570545/171311/53cc2b0c-7a95-11e2-8ede-a652052a74e6.png)

Is this a feature? Does this actually restore anything? Should it be removed?

Tested on a Mac, with "Mon Feb 18 14:57:05 2013 +0800" source.

**Comment by chaseWillden** [comment]
@lahdekorpi can this be closed?

**Comment by mrfabbri** [comment]
I think this is something that Mac OS X displays by default if the app doesn't seem to be able to startup correctly (i.e. exits/fails very early).
