### ISSUE TITLE
Tray not working on Ubuntu 12.04 and 14.04

### ISSUE THREAD

**Issue by skyronic** [nwjs/nw.js#4481]
### Overview

Tray icons and menus aren't working on Ubuntu 12.04 and 14.04 with unity. We are sponsoring fixing this bug [via a **$2000** bounty on bountysource](https://www.bountysource.com/issues/31525242-tray-not-working-on-ubuntu-12-04-and-14-04)

### Steps to Reproduce

`package.json`

```
{
	"name": "nw-app",
	"main": "index.html"
}
```

`index.html`

```
<!DOCTYPE html>
<html>
<head>
	<title>Testcase</title>
<script type="text/javascript">
	var tray = new nw.Tray({ icon: 'icon.png' });
	var menu = new nw.Menu();
	menu.append(new nw.MenuItem({ type: 'normal', label: 'Test' }));
	tray.menu = menu;
</script>
</head>
<body>
</body>
</html>
```

`icon.png`

You can use `http://i.imgur.com/RsoNmTo.png` to test.

### Background

There is a bug #261 dating back to 2012 and a PR #2327 which supposedly provides a fix. We would like to see the issue fixed and verified on Ubuntu 12.04 and 14.04 (it works fine on 15.10).

**Comment by jtg-gg** [comment]
I might be interested to fix this, so you'll need to be fixed on latest nw13 (chrome 49) ?

**Comment by skyronic** [comment]
Yes! We need this fixed on nw13 (but we also need someone to build ready to use binaries for us since we don't have the experience or infrastructure to build the system reliably)

* nw13 Linux 64 bit (dev + prod builds)
* nw13 Linux 32 bit (dev + prod builds)

Should work on Ubuntu systems (with libindicator on 12.04 and 14.04) and non-libindicator systems.

Let me know if you have any questions and if you want to discuss in private, please email me on skyronic@gmail.com

**Comment by jtg-gg** [comment]
@skyronic I've just downloaded the official nw13-rc1 binary, your test case is running well on my ubuntu 14.04 64bit, I can see the tray icon and menu

**Comment by skyronic** [comment]
@jtg-gg: We need this for ubuntu 12.04 as well...

It's not working on my 14.04 setup. Let me see what the problem is.

**Comment by skyronic** [comment]
@jtg-gg after testing on a fresh ubuntu 12.04 it looks like it's working after making some changes to dconf. Please wait for a confirmation if this still needs to be fixed.

Apologies for the confusion.
