### ISSUE TITLE
nwjs13-rc1 nightly build 3/3 on Windows: The MTV bug is back again...

### ISSUE THREAD

**Issue by cryptedco** [nwjs/nw.js#4482]
Testing the rc1 build from tonight against mtv.com:

Open the plain nwjs, open the dev console, do a

window.location.href="http://www.mtv.com/full-episodes"

click on an episode and watch nwjs do nothing anymore...

I am testing that on Windows 10, nwjs-sdk-v0.13.0-rc1-win-x64

**Comment by rogerwang** [comment]
Will see it. Could you please post the link to the last nightly (beta8) version that works for you? We didn't fix the mtv issue on purpose.

**Comment by cryptedco** [comment]
Well, it was on Mac and this one: http://dl.nwjs.io/live-build/02-28-2016/a02a518-4bbe944-b8fe343-bce39d3/v0.13.0-beta7/nwjs-sdk-v0.13.0-beta7-osx-x64.zip - BUT it crashes, too... just 1 click later. I did not notice that. It seems to be some ugly tracking code causing this. The webview in the current release is just showing me a "Oh Snap" icon...

**Comment by rogerwang** [comment]
a similar issue of #4422 was just fixed. Please wait for the next nightly build and try again.

**Comment by cryptedco** [comment]
Thanks, much appreciated!

**Comment by rogerwang** [comment]
nightly build with the fix: http://dl.nwjs.io/live-build/03-08-2016/8376d68-2c53f2b-3d99a78-93e6ec5

**Comment by cryptedco** [comment]
It is working nicely, thanks Roger! Big progress here, loving it!

**Comment by krneticz** [comment]
It is behaving same as https://github.com/nwjs/nw.js/issues/4347.

This one is fixed, but not completely. Now it don't crash nwjs, but (lot less often then before) still causes trouble: from time to time webpage goes completely black and in dev tools I get message that dev tools are disconnected from the page. If I do Ctrl+R in dev tools it reload site and it can be used again... until it black out.

**Comment by krneticz** [comment]
Update: issues that I have reported are happening only when dev console is opened.
