### ISSUE TITLE
Is it possible to get rid of the 'Screen is sharing' prompt window?[nw0.13]

### ISSUE THREAD

**Issue by sean220** [nwjs/nw.js#4484]
In the version 0.13,When after call getUserMedia() to get a stream of screen share,A prompt box   appears from NW and need to be manually shut down,Is it possible to get rid of this prompt?

This problem exists in both OSX and Windows.

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next build.

**Comment by rogerwang** [comment]
The binaries will be in http://dl.nwjs.io/live-build/03-04-2016/e04cd75-242db83-3d99a78-8419c51/v0.13.0-rc2/

**Comment by sean220** [comment]
This live build crashes on startup.

**Comment by rogerwang** [comment]
New version: http://dl.nwjs.io/live-build/03-05-2016/e04cd75-96977b3-3d99a78-8419c51
