### ISSUE TITLE
win has no isDevToolsOpen method

### ISSUE THREAD

**Issue by march1993** [nwjs/nw.js#4487]
0.13.0 beta6 beta7 and rc1 all have no isDevToolsOpen method.
sdk version

**Comment by zenoamaro** [comment]
`0.14.0-sdk-1` also seems to be lacking `Window.isDevToolsOpen`

**Comment by Christywl** [comment]
`win.isDevToolsOpen()` is still undefined on nwjs-sdk-v0.21.5. But I find that `isDevToolsOpen()` is not supported for now in the docs(http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues). @rogerwang , am I right? 
duplicate of #5063

**Comment by fritx** [comment]
Same in 0.21.2-sdk, is there any alternative?

**Comment by CosmoMyzrailGorynych** [comment]
Still not fixed in 2020 D:
