### ISSUE TITLE
nwjs app will interrupt restart of mac 

### ISSUE THREAD

**Issue by lizijian** [nwjs/nw.js#4488]
but app is packaged and use customized name and user don't know which one is nwjs app.
how can I avoid of this interruption.
mac: 10.11.1
nw.js v0.12.3
io.js v1.2.0
Chrominum  41.0.2272.76
commit hash: 591068b-b48a69e-27b6800-459755a-2bdc251-1764a45

**Comment by Christywl** [comment]
@lizijian , I'm not clear about your issue, could you please provide more info(detailed results and a sample) to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
