### ISSUE TITLE
[nw 0.13] Windows taskbar context menu opening on top of Tray menu

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [nwjs/nw.js#4489]
Tested on Windows 8.1
nwjs 0.13-rc1

Intermittently when right-clicking on the Tray icon, the Windows taskbar context menu opens on top of the menu (you can see the Tray menu below it).

![image](https://cloud.githubusercontent.com/assets/7252279/13494785/5fcf7f54-e13e-11e5-9baf-fafa4868e7ba.png)

Other times it opens OK:

![image](https://cloud.githubusercontent.com/assets/7252279/13494787/6c5e6456-e13e-11e5-90f8-c8ba0fc48657.png)

**Comment by Christywl** [comment]
I try more times on Windows with nwjs-sdk-v0.22.0, can't reproduce this issue. There is no taskbar when right-click on tray icon, only tray menu shows.

**Comment by Christywl** [comment]
close until there is more information.
