### ISSUE TITLE
[0.13 RC1] Tray icon click event doesn't pass position info (x,y)

### ISSUE THREAD

**Issue by fyodorvi** [nwjs/nw.js#4491]
``` javascript
var tray = new nw.Tray({
    title: '',
    icon: 'dist/assets/images/menu-icon.png',
    iconsAreTemplates: false
});

tray.on('click', function (evt) {
    console.log(evt); //undefined
});
```

Works perfectly in 0.12

**Comment by mulhoon** [comment]
Was this dropped intentionally? It would be really useful to have back in.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.0. 
![image](https://cloud.githubusercontent.com/assets/20039821/25512485/afda6622-2c00-11e7-98bf-61f8734d5042.png)

**Comment by Christywl** [comment]
close until there is more information.
