### ISSUE TITLE
Need MP3 and MP4 in 0.13.0

### ISSUE THREAD

**Issue by Bigmacbook** [nwjs/nw.js#4492]
As a web developer its too cumbersome to try learn how to add Proprietary Codecs. I use to get ffmpegsumo.dll from chrome installation but they no longer seem to be there.

I have and always used mp3 and mp4, so support is a must for me.

Might have to either stay with 0.12 or move to electron.

Which is sad cause I like the NWjs environment better and its more upto date. Electron is still on chrome 47

**Comment by rogerwang** [comment]
In recent versions of Chromium project, ffmpeg DLL was changed to be builtin. And we don't have license to redistribute the codec in question. So developers don't have any ways to get the codec without compiling.

To make things easier, we'll build  ffmpegsumo as a separate DLL in the next RC version. The DLL we distribute will not contain any codec in question. Developers can recompile the DLL for themselves, which is much easier than compiling NW. Or they can get DLL from someone else from the community.

Note that developers can redistribute binaries containing these codecs as long as they have the license. If a developer doesn't have the license, moving to Electron doesn't make him/her eligible to redistribute the codecs.

**Comment by AndryBray** [comment]
@rogerwang will you write some doc about how to build the DLL? Is this procedure the same for Mac & Linux? Thank you

**Comment by AndryBray** [comment]
@rogerwang I'm trying to build the ffmpeg but without success. 
I don't know how to go on... the doc about that is really poor. 

Why don't you build it for who can use this feature? 

I mean it's the same like I will go to pay someone to build it for me... he/she doesn't need to be eligible to use MP3 codec/license because at the end he/she is not going to use it for personal/commercial purpose.

**Comment by barticus22** [comment]
@AndryBray I can build a custom nwjs that meets your requirements. Please let me know if you are interested.

**Comment by AndryBray** [comment]
thank you @barticus22 
but how will be with the next version? nwjs will go to change very fast and I'd like to be updated with latest versions, even nightly build.

The best would be to find this build inside the repository as a normal build, @rogerwang do you agree?

**Comment by fuwenchun** [comment]
@barticus22 I need the ffmpeg.dll of 32bit,support me3,can you help me to build it.

**Comment by rogerwang** [comment]
Theoretically the ffmpeg dll doesn't need to be rebuilt for minor version update. 

Per your previous question @AndryBray , I can't redistribute the binary because I don't have the license, as I stated repeatedly. And there is obvious difference between redistributing the dll and delivery to only you from someone doing it on your behalf.

**Comment by rogerwang** [comment]
The documentation for enabling the codecs in question is in http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/ . Anyone who need help  following the doc should follow #4595

**Comment by davidsonbpe** [comment]
cara to pressionando muito DLL ffmpeg mp3 e mp4 na v0.13.3

**Comment by guogaigai** [comment]
@barticus22 I also need the ffmpeg.dll of 32bit to support mp4 , can you help me to build it

**Comment by guogaigai** [comment]
@rogerwang  I can not compile the ffmpeg successful for cannot visit google site when compiling . If possible ,can you help me to build ffmpeg.dll for win32 , thank you ~

**Comment by iteufel** [comment]
@guogaigai You can download prebuilt binaries from https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

**Comment by guogaigai** [comment]
@iteufel  thank you very much ~

**Comment by vzamanillo** [comment]
Seems like building a custom ffmpeg with proprietary codecs support is not enought to get the it working, correct me if I am wrong or confused but the NW.js prebuilt needs a build with the interface to proprietary codecs (proprietary_codecs=true argument), I was testing the nwjs-v0.17.5 prebuilt with a custom ffmpeg library builded with proprietary codecs to get ac3 audio and did not work.

**Comment by rogerwang** [comment]
@vzamanillo interface to proprietary codecs is already enabled in official binary.

**Comment by vzamanillo** [comment]
@rogerwang Thank you, then I assume that a custom build of ffmpeg with extra codecs should work, or it is neccesary to do something else?.

**Comment by cecilpeng** [comment]
@iteufel Thanks very much for your contribution. It works well. https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases
