### ISSUE TITLE
Losing the NW object on window.location

### ISSUE THREAD

**Issue by Hectorhammett** [nwjs/nw.js#4494]
I was unsing the 0.12.3 version, and it was working until i needed native pdf viewer, so i decided to use the new version instead of using PDF js, but for some reason, i get the following error:

```
require is note defined
```

It was because i have an index.html with a js, that loads some things that i need, and then, i redirect to the login page, after i redirect, that's where i have the error.

Then i decided to put the js in the login page, and in the console i can open the nw object, but if i made a window.location to another file, the nw object is not defined. 

Any ideas?

**Comment by rogerwang** [comment]
Could you please try 0.13.0-rc1?

**Comment by Hectorhammett** [comment]
That's the version i'm using as of it now.

I kinda made it work using the load method on the jquery library, tho it still not perfect. I had to patch jquery to add the success method as a code of 0 onstead of 200.

**Comment by rogerwang** [comment]
It's 'nw.require' now. See http://docs.nwjs.io/en/v0.13.0-rc1/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by Hectorhammett** [comment]
Yeah, but that wasn't working as well.
When i changed to another file with window.location = another.html, My html was loading, but if in the console i typed nw, the object was indefined.

**Comment by Christywl** [comment]
@Hectorhammett , is this issue still reproduced on your test? If yes, could you please upload a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
