### ISSUE TITLE
nw 013.0-rc1 "node-main" is invalid.

### ISSUE THREAD

**Issue by owen-hong** [nwjs/nw.js#4495]
It throws an error "process.mainModule.exports.callback0() is not a function".  Is there some example that works with nwjs13?
It looks like the "node-main" is invalid.

**Comment by mani582** [comment]
I had the same issue and I just verified, actually node-main script defined in package.json seems is not executed since nw13 beta1.

**Comment by rogerwang** [comment]
Will fix it soon
