### ISSUE TITLE
Image decodes even if its already visible

### ISSUE THREAD

**Issue by ktxxt** [nwjs/nw.js#4496]
Could someone please look at this question and provide a helpful answer.
http://stackoverflow.com/questions/35506265/small-delay-on-drawing-large-images-in-node-webkit

To simplify it, node webkit does decode image when I switch from `opacity:0.2` to `opacity:1`. Chrome browser hasn't that problem.

Thank you :)

**Comment by swolfish** [comment]
I have the same problem and no solution yet. NW doesn't deal the best with large images/sprites.
Help would be appreciated.

**Comment by mscreenie** [comment]
What version are you using? @ktxxt

**Comment by ktxxt** [comment]
every detail is written here. I would appreciate if you take a look at this question

http://stackoverflow.com/questions/35506265/nw-node-webkit-image-decodes-even-if-it-is-already-visible

**Comment by ktxxt** [comment]
@mscreenie any news for this?

**Comment by rogerwang** [comment]
Please try with latest 0.13 versions.

**Comment by ktxxt** [comment]
How should I switch to 0.13-rc1(normal)?

**Comment by ktxxt** [comment]
With the latest 0.13v on Ubuntu, the performance of SVG-s was not so good and it laggs a lot comparing to the previous version I use now.  I will continue to test and will let you know about further details :) @rogerwang

**Comment by rogerwang** [comment]
I read the stackoverflow link but I'm still not sure about your specific issue. Could you please provide a case so we can reproduce it?

**Comment by ktxxt** [comment]
I will make a test scenario since I could not show you my original code.
