### ISSUE TITLE
Nw13 rc1 fatal error when starting in Win7

### ISSUE THREAD

**Issue by janRucka** [nwjs/nw.js#4497]
Error occur with every start of nw.exe. Fun thing is that if built in debug nw doesn’t even start. Attached log from debug version. Release version logs error but then seems to be working Ok.

Ed Gauci obviously has the same problem:
https://groups.google.com/d/msg/nwjs-general/3M812Nol_ZE/omXrZTOvAgAJ

[debug.txt](https://github.com/nwjs/nw.js/files/158523/debug.txt)

**Comment by rogerwang** [comment]
fixed in git and will be available in the next nightly build.
