### ISSUE TITLE
rc2: libffmpeg - not found

### ISSUE THREAD

**Issue by cryptedco** [nwjs/nw.js#4499]
Hi folks, have you linked the ffmpeg lib now dynamically? 

/Versions/49.0.2623.75/NWJS Framework.framework/NWJS Framework, 257): Library not loaded: /usr/local/lib/libffmpeg.dylib

I think that makes distribution of packages (apps on mac - ready to distribute & install, i mean) impossible, if the lib must be in the usr/local/lib/ directory...

Cheers,
Ralf

**Comment by rogerwang** [comment]
yeah. and it's been fixed here: http://dl.nwjs.io/live-build/03-05-2016/e04cd75-96977b3-3d99a78-8419c51/v0.13.0-rc2/
