### ISSUE TITLE
nwworkingdir not honored on nwsaveas dialog

### ISSUE THREAD

**Issue by ed4becky** [nwjs/nw.js#4502]
At least on Mac OSx, when providing an nwworkingdir entryand an nwsaveas entry, the nwworkingdir is ignored, defaulting to the current working dir

**Comment by matthew-dean** [comment]
That's been a problem for some time. There's another issue tracking this somewhere I think.

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.22.0. 
Both of `nwworkingdir` and `nwsaveas` could be set in my test.

`<input type="file" nwworkingdir="/Users/test/Desktop" nwsaveas="1.html">`
The file dialog will start in the given directory, not the current directory(`package.json` path).

**Comment by Christywl** [comment]
close until there is more information.
