### ISSUE TITLE
file type ignored in nwsaveas on Mac

### ISSUE THREAD

**Issue by ed4becky** [nwjs/nw.js#4503]
if a file name with a type is provided in nwsaveas on a Mac,the file type is ignored.

that is, file.txt becomes file, and the .txt is dropped

**Comment by silentrain** [comment]
+1

**Comment by ghostoy** [comment]
Please uncheck the "Hide Extension" in save as panel, then you will see the `.txt` extension. And if you want to specify multiple extension or mime types, use `accept` attribute with `<input>`.
