### ISSUE TITLE
Question : is possible to run my HTML5 under http:// instead of file:// ? (and PepperFlash problem)

### ISSUE THREAD

**Issue by josh83abc** [nwjs/nw.js#4504]
I'm an experienced web developer and flash developer but I'm quite new with NW.js and NodeJS.
When I run my HTML5 with NW.js, it loads with a local url, such as file://c:\myproject\index.html which is logical. However, my app also use some Flash and Flash applies some restrictions for local access. I know that there are way to unlock some of these restrictions, such as with https://github.com/szwacz/nw-flash-trust. However when using Flash workers, this doesn't work. It seems that there is no way for Flash Workers to access local content. http://stackoverflow.com/questions/30396401/as3-how-to-load-local-file-inside-the-worker
So a solution would be to run my NW.js app with http:// and not with file://, is this possible? If yes, could anyone could give me a working example? Is it possible that some firewalls block this to work? 
Thanks everybody,
Josh

**Comment by rogerwang** [comment]
Please try with latest 0.13 versions.

**Comment by josh83abc** [comment]
Hi Rogerwang :). What is going to be different with 0.13? I just tried but it seems that the 0.13rc1 doesn't work entirely on my computer, I can't make the toolbar to display, and the flash plugin doesn't load. Again I'm a beginner with NW.js, so maye I missed something :)

**Comment by rogerwang** [comment]
http://docs.nwjs.io/en/v0.13.0-rc1/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by josh83abc** [comment]
Thanks! lot of changes in there, but it is nice, well done! :)

> toolbar is deprecated and it’s always false.
Ok I understand now :)

>  you can open / close DevTools with F12
Actually doesn't work on my Windows10 laptop, can't make the devtools to display :/

**Comment by FiatPax** [comment]
You need to be using sdk version to display dev tools.

**Comment by josh83abc** [comment]
Great! thanks FiatPax!! I will try with the SDK tonight! 
Also do you have an idea with Flash doesn't work? maybe I should add it manually in my package.json under plugin:? I also read somewhere that the 0.13 use Flash PPAPI (Pepper) now, I'm I right?
NW.JS is amazing, I love it :)

**Comment by FiatPax** [comment]
I haven't worked with Flash so I don't know but check rogerwang's answer in this issue. https://github.com/nwjs/nw.js/issues/4430

**Comment by josh83abc** [comment]
You are the best, thanks!! I will try that! Hoping I will get lucky enough to have it working :)

**Comment by cryptedco** [comment]
As far as I understood is the flash plugin NOT shipped with the current nwjs13 release. You can, however, copy it over from your Chrome and it just works (not sure if that is evil or OK... but it works for me)... https://www.dropbox.com/s/24zq1mlkcyupyft/Screenshot%202016-03-07%2019.52.24.png?dl=0 ... just copy that directory over from your Chrome installation... it worked then for me.

**Comment by josh83abc** [comment]
Thanks all!! I just tried. The 0.13rc1 SDK brings the dev console by pressing F12, great! 
However I didn't managed to make Flash to work. I copied the C:\Program Files (x86)\Google\Chrome\Application\49.0.2623.75\PepperFlash directory under the same directory where nw binaries resides as @cryptedco (on MacOS) and @rogerwang suggests, no effect... I also double-checked the registry key SOFTWARE\Macromedia\FlashPlayerPepper which is pointing on the file C:\Windows\System32\Macromed\Flash\pepflashplayer64_20_0_0_306.dll. The file is indeed there. So as @rohanbritto in the issue [#4430](https://github.com/nwjs/nw.js/issues/4430), I can't manage to make Flash to load with the 0.13rc1 :/. I'm running a Windows 10 64bits.

**Comment by cryptedco** [comment]
When you download our PersonTool, which is based on rc2, you will see on Windows 10, that I just copied the PepperFlash over: https://www.dropbox.com/s/56kfkwpae581ikm/Screenshot%202016-03-07%2022.22.03.png?dl=0 and it should be from a Chrome V49 as well, I think...

Then, if you are trying to load it in a Webview, you have to explicitly allow the plugin to work:

    webview.addEventListener('permissionrequest', function (e) {
        console.log("webview"+objCount+": permission - "+e.permission);

        if (e.permission === 'loadplugin') {
            if(userSession.allowPlugins) {
                e.request.allow();
            } else {
                e.request.deny();
            }
        }

I have been playing around with that specifically for security aspects, so I know that Flash works on Win10 with rc1 and 2.. basically with every nightly build for the last 8 days...

**Comment by josh83abc** [comment]
Thanks a lot @cryptedco for your help!! :). Your screenshot make it clear, you indeed just copied the PepperFlash dir under the NW app dir. I exactly did the same :). Maybe it is something to do with 32bits or 64bits version of the Pepper plugin, I don't know. Where can I download your PersonTool app so I can try on my pc and grab the PepperFlash dir you used in order to copy it in my app. 
I'm not sure what's webview is, I tried the line of code you send, the chrome instance of nw.js is telling me 'webview is not defined' so I guess I'm not using it :). I really don't know what to do... :/

**Comment by cryptedco** [comment]
hi josh, ok, I see there are several layers of problems stacked on each other for you. first of all: do not mix 64 and 32 bit releases of any kind. I did PersonaTool.com on Win32bit, because it is working on Vista up to Windows 10 for me. But if you run 64 bit Win10 and mix that up with other versions, you will just create more mess.

So: if you are not sure, if you are using webviews: you are not. Because they are a bit complex to implement and if you don't know, you do not use them.

If you just download my release of PersonaTool for yourself and copy the Pepperflash out, I do not think it will help.

Lets go back to square 0 for you:

Download the latest nwjs 13 nightly build for windows (32 bit):

http://dl.nwjs.io/live-build/03-08-2016/8376d68-2c53f2b-3d99a78-93e6ec5/v0.13.0-rc2/nwjs-sdk-v0.13.0-rc2-win-ia32.zip

and then open your file explorer and go to your personal home directory:

C:\Users\Ralf\AppData\Local\Google\Chrome\User Data   (replace "Ralf" with your user)

there is a PepperFlash directory, right? If not, stop... something is wrong

If there is: that needs to go over to your nwjs directory. You can try and use vimeo.com to play videos, they still use flash...

**Comment by josh83abc** [comment]
Thanks man for the info and the RC2! So indeed mixing up 32/64bits stuff isn't recommanded you are right :). I assume the Pepper Flash plugin on Chrome is 32 bits. So I tried with the 32bits RC2 you sent me. Well, I got something interesting. My app still doesn't load any swf unfortunately BUT if in the dev console I type windows.open('http://vimeo.com') for instance, in this new window, Flash is accessible! I don't know of what this means... I'm using the debug version of Pepper Flash, maybe this could be an issue, I have to try with the regular one tomorrow...

**Comment by josh83abc** [comment]
Just to confirm, I tried with the normal PepperFlash, even with the RC2, when I load my app Flash doesn't load up (index.html specified in the package.json) and this without any error message. HOWEVER, when in the dev console I do a window.open, to webpage with some flash in it, Flash is loaded and works well. Maybe a bug?

**Comment by cryptedco** [comment]
When you start your app (as far as I understand the changes from 12 to 13), you basically start a Chrome app with nodejs support - that is the major step from 12 to 13. So, if your Chrome app loads, it needs permission. Maybe that is it? I am really not deep into the process, but I guess it is a rights problem here ... https://developer.chrome.com/extensions/declare_permissions and https://developer.chrome.com/extensions/manifest ... what kind of permissions did you set in your manifest? Do you start your app accordingly?

**Comment by josh83abc** [comment]
Hey! Thanks for the reply @cryptedco :). Yes it would make sense that this permissions mechanism applies to the 0.13 now. I didn't declare any permission in the manifest package.json, and you did you? According to the Google documentation, if you don't enable the need permission, you get a warning message which I don't get... I really don't know... :/

**Comment by cryptedco** [comment]
Josh, open the console and do a ... window.location.href="chrome://plugins" ... That should show you some info

**Comment by cryptedco** [comment]
That looks like that: since I updated to the latest build, my flash stopped working, too: https://www.dropbox.com/s/fq73u6xj2yvh4q2/Screenshot%202016-03-09%2000.11.53.png?dl=0

**Comment by cryptedco** [comment]
Ok, now I am officially confused, too... I have updated to the latest nightly build rc2 and updated my PepperFlash plugin to 20.0.0.306, I put it into the path:

nwjs.app/Contents/Versions/49.0.2623.75/nwjs Framework.framework/Internet Plug-Ins

and it is obviously loaded, when I do a "chrome://plugins" - just not with the right version. Is that an interface problem of the PPAPI loader? Or should I not do it like this at all?

This screenshot shows the plugins status page and the wrong version number, which the manifest shows the right version in the right path... I cleared caches and Application Support directories and tried to find out, why nwjs insists on the wrong version number. It is also shown, when there is no directory left!

![screenshot 2016-03-09 12 21 04](https://cloud.githubusercontent.com/assets/326428/13633911/515cbf6e-e5f2-11e5-8949-97bdc369dfa2.png)

**Comment by cryptedco** [comment]
I think the plugin is statically linked, because in a clean, fresh download, it is still referenced, even if it is not there...
![screenshot 2016-03-09 12 30 49](https://cloud.githubusercontent.com/assets/326428/13633964/e004874c-e5f2-11e5-9fea-51ec2556f0c6.png)

**Comment by josh83abc** [comment]
My chrome://plugins clearly indicated that Flash plugin is loaded, but I can certified, the SWF in my app silently failed to load. An interesting thing is that NW.js seems to load the system PepperFlash, not the one I put in the PepperFlash directory.

My chrome://plugins gives :
Adobe Flash Player - Version : 20.0.0.306
Shockwave Flash 20.0 r0
Nom :	Shockwave Flash
Description :	Shockwave Flash 20.0 r0 System
Version :	20.0.0.306
Location :	C:\WINDOWS\SysWOW64\Macromed\Flash\pepflashplayer32_20_0_0_306.dll
Type :	PPAPI (hors processus)

**Comment by cryptedco** [comment]
Well, for you it does load the right flash version at least... The crashing of your app should be solveable... Just to confirm your start: you have an "app.nw/" directory in your nwjs directory, right next to the "nw.exe" file? In that app.nw directory you have an "index.html" that loads your file like....? how? and also in your app.nw directory you have a "manifest.json" that defines the load process?

app.nw/manifest.json:

`{
  "manifest_version": 2,
  "name": "CoolFlashByJosh",
  "version": "2",
  "minimum_chrome_version": "49",
  "permissions": [
    "node"
  ],
  "app": {
    "background": {
      "scripts": [
        "background.js"
      ]
    }
  }
}`

and the background.js:

`chrome.app.runtime.onLaunched.addListener(function() {
    chrome.app.window.create('index.html', {
        'outerBounds': {
            'width': 1000,
            'height': 800
        }
    });
});`

and how does the flash loader part in HTML look like?

**Comment by josh83abc** [comment]
No I don't have a app.nw folder with my app, maybe this is the problem. I put all my app files (index.html...), my package.json, the nw.exe files, the PepperFlash dir, all in the same directory. Let me try your way, thanks Ralf!

**Comment by josh83abc** [comment]
I might be a stupid question, but how I will tell nw.exe to load my app in the app.nw folder? because it doesn't load it. 

In my app, I load swf like this :

_var str = "<object classid='clsid:d27cdb6e-ae6d-11cf-96b8-444553540000' codebase='http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0' id='myswf' width='1278' height='60'>";
str += "<param name='movie' value='"+url+"' /><param name='quality' value='low' /><param name='wmode' value='transparent' /><param name='allowScriptAccess' value='always' />";
str += "<embed src='"+url+"' quality='low' wmode='transparent' width='1278' height='60' id='myswf' allowScriptAccess='always' type='application/x-shockwave-flash' pluginspage='http://www.adobe.com/go/getflashplayer' /> </object>";_

**Comment by cryptedco** [comment]
Josh, drag and drop the app.nw folder onto the nw.exe... in this case you should do it like that first and when you want to distribute the app later, you can create one exe out of both... but it must work first with the drag and drop

**Comment by josh83abc** [comment]
Ok! Just did the darg and drop of the app.nw onto the nw.exe. It loaded the app fine! But still no Flash! except if I do window.open(...). Actually I have a web version of the app with the exact code. You can try it here http://you.dj. 

I load several SWF on the page, 2 of them are Youtube players for instance. I load all the swf dynamically with Javascript, like this : 

```
function core_init()
{
	var url = "myapp.swf";
	var str = "<object classid='clsid:d27cdb6e-ae6d-11cf-96b8-444553540000' codebase='http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0' id='player' width='1278' height='60'>";
	str += "<param name='movie' value='"+url+"' /><param name='quality' value='low' /><param name='wmode' value='transparent' /><param name='allowScriptAccess' value='always' />";
	str += "<embed src='"+url+"' quality='low' wmode='transparent' width='1278' height='60' id='player' name='player' allowScriptAccess='always' type='application/x-shockwave-flash' pluginspage='http://www.adobe.com/go/getflashplayer' /> </object>";
	div("flash2").innerHTML = str; 
}

```

**Comment by cryptedco** [comment]
Hmmm, indeed strange... the url of the file... is it ./some.swf ? or do you do file://some.swf... try relative paths?

**Comment by josh83abc** [comment]
Yes I tried with an absolute path (file://) and relative one. The YouTube player swf I have on my page is loaded over http://. I see the file loading in the dev console... I really don't have any idea... :/

**Comment by cryptedco** [comment]
Josh, have you tried the nightly build of today... solves a lot of little problems for me....  http://dl.nwjs.io/live-build/03-13-2016/c0a3f15-32d0338-3d99a78-678d67e/

**Comment by Gandii** [comment]
I have been playing around with the same issue the past days, my bet is that you have a sand box issue. As far as i can tell nw-flash-trust does not work with PepperFlash, in fact PepperFlash does not support trusted locations at all (i hope i am wrong about this).

 I have been playing around with the placement of the config file and structure based on https://forums.adobe.com/thread/1491485 with no luck. You can confirm this by downloading the PPAPI debug version from adobe and you will get prompted.

**Comment by RandyMustache** [comment]
Hi Gandii, you seem like you are running the same gauntlet as me. I am also running into issues with the flash sandbox. I've had to revert back to NWJS 12.3 in order to use the nw-flash-trust api. It works well, except for when running my app from external media (USB, CD, network). I require flash videos to trigger various javascript scripts, so the sandbox is an ongoing battle. This thread has just raised more questions for me, rather than giving many answers. 

Eventually my application will move away from Flash, and I am pushing for this to happen sooner, rather than later. But as it is, we have years of flash video content that needs to run *sigh*.
