### ISSUE TITLE
Module compilation error with v0.13.0-rc1

### ISSUE THREAD

**Issue by lexetam** [nwjs/nw.js#4506]
Hi, i am testing nw v0.13.0-rc1 and i try compile serialport module with

`node-pre-gyp rebuild --runtime=node-webkit --target=0.13.0-rc1 --target_arch=x64`

but i recive several error messages

> gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Gio\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:286:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)

But when i compile with de latest beta version, the program compile fine

`node-pre-gyp rebuild --runtime=node-webkit --target=0.13.0-beta7 --target_arch=x64`

I am runing a machine with: 
Win 10 x64
Node 5.6.0

**Comment by rogerwang** [comment]
Please see https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ

**Comment by lexetam** [comment]
i am replace the file win_delay_load_hook.c
`nw-gyp rebuild --target=0.13.0-rc1 --arch=x64`

> Undefined variable module_name in binding.gyp

**Comment by rogerwang** [comment]
The announcement said you should use npm/node-gyp, not nw-gyp.

**Comment by rogerwang** [comment]
And please post questions to the mailing list.
