### ISSUE TITLE
doc to build fmpeg

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#4510]
hi @rogerwang 

we need some doc to build the "new" ffmpeg.so/dll if possible (static build?)

thanks

**Comment by iteufel** [comment]
http://nwjs.readthedocs.org/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by rogerwang** [comment]
The improvement is compiling the full NW source is not needed. But the process is not optimal: it still need to checkout and sync the full source code of chromium. We'll see how to improve this.

**Comment by smolleyes** [comment]
hello

np, thanks for the reply :)
