### ISSUE TITLE
0.13.0-rc1's devtools cann't find emulation

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#4511]
hi 

in 0.13.0-rc1, when open devtools, can not find 'emulation', was this feature deleted?

![image](https://cloud.githubusercontent.com/assets/3161552/13565588/eb74e7e2-e48b-11e5-969a-d4f51b808be4.png)

and in beta7 had this feature

![image](https://cloud.githubusercontent.com/assets/3161552/13565600/0d697548-e48c-11e5-82b9-75b3ed44bf42.png)

**Comment by rogerwang** [comment]
We didn't touch this. In RC1 Chromium is updated to 49. You can check Chromium browser 49 first.

**Comment by lin-chao** [comment]
get

chrome 49 change emulation feature
