### ISSUE TITLE
window not available - 0.13-rc1-sdk

### ISSUE THREAD

**Issue by f0rmiga** [nwjs/nw.js#4513]
OS: Mac OSX
Version: 0.13-rc1-sdk

Sometimes window is not available in third argument's callback. When cascading windows like this:

```javascript
nw.Window.open(url, options, function (win1) {
    nw.Window.open(url2, options2, function (win2) {
      // accessing win1.window gives error saying win1 is not defined
    }
});
```

Note that I wasn't able to reproduce the error every run. It seems that the callback function is returning whether the window is ready or not.

**Comment by finim** [comment]
seems the same issue as mine:
[https://github.com/nwjs/nw.js/issues/4512](url)

**Comment by f0rmiga** [comment]
same as #4512
