### ISSUE TITLE
nwjs: v0.13.0-rc1: "AssertionError: path must be string" when importing requirejs

### ISSUE THREAD

**Issue by flynx** [nwjs/nw.js#4516]
**To reproduce:**

1. `npm install requirejs`
2. `require('requirejs')`

Wrorks in node.js 5.7.1 but breaks in nw.js 0.13.0-rc1

Throws an "AssertionError: path must be string"

**Comment by flynx** [comment]
still broken for rc2.

**Comment by ghostoy** [comment]
@flynx It's the problem of requirejs lib, which incorrectly detect NW as browser. I submitted a PR to fix this issue (see https://github.com/requirejs/r.js/pull/901). You can temporarily fix it by reorder the block of testing `browser` and `node` in `<your-app-path>/node_modules/requirejs/bin/r.js`.

**Comment by ghostoy** [comment]
@flynx The patch is now merged to `requirejs` as part of 2.1.23. Or you can test with its master branch on Github.

**Comment by flynx** [comment]
@ghostoy 2.1.23 appears to work fine, thanks!
