### ISSUE TITLE
how to  reduce RAM usage 

### ISSUE THREAD

**Issue by sorty** [nwjs/nw.js#4520]
I run both  nw.exe and chrome.exe to open the following  web site "http://www.craftymind.com/factory/html5video/CanvasVideo.html" 
one mintue later, the momory used by nw.exe is  455M, and  the chrome.exe is 70M.

Is there any way to reduce the RAM usage of nw.exe?

**Comment by mscreenie** [comment]
What version of nwjs are you using and which platform are you on?

**Comment by sorty** [comment]
win7 64  nwjs 0.13.0 rc1

**Comment by mscreenie** [comment]
I believe roger has fixed some issues with websites opening in the latest nightly build. See here: https://github.com/nwjs/nw.js/issues/4347 and test.

But the problem your describing might be different to the one reported earlier.

**Comment by rogerwang** [comment]
Will see it soon.

**Comment by rogerwang** [comment]
I can't reproduce it with the last nightly build. Could you please try with it? 

http://dl.nwjs.io/live-build/03-08-2016/8376d68-2c53f2b-3d99a78-93e6ec5/

It's launched with nw.exe --url=...

**Comment by sorty** [comment]
sorry ,my mistake. 
the shared momory used by nw,exe is up to 455M,not the momory only used by nw.exe。
![image](https://cloud.githubusercontent.com/assets/172805/13626228/ef47c040-e5fa-11e5-821d-0268225d34af.png)

I think the momory accquired by such as "CreateFileMapping","MapViewOfFile" apis in nw.exe  is not recycled in time.

**Comment by rogerwang** [comment]
Loading your url with nightly build here shows similar memory consumption with Chrome browser:

![1](https://cloud.githubusercontent.com/assets/165401/14165909/d7626302-f740-11e5-9317-9aad8234c4c3.png)


Please give more information on how you reproduce the issue, and what's the version of your OS, as well as hardware configuration including gfx card.

**Comment by rogerwang** [comment]
close until there is more information.
