### ISSUE TITLE
window.Notification.permission "granted" in main window only

### ISSUE THREAD

**Issue by bjoernneumann** [nwjs/nw.js#4521]
The permissions for Notifications are only set to "granted" in the main window.
For new windows (nw.window.open) or iframes within the main window, window.Notification.permission is always default.

Can window.Notification.permission be set to granted for all windows?

**Comment by ghostoy** [comment]
Actually not related to main window or not. Pages NOT starting with `chrome-extension://` will get `default`.

**Comment by rogerwang** [comment]
Just made 2 modifications in the live build for this:

1. window.Notification.permission is set to "granted" for all.
2. Apps can change the setting with chrome.contentSettings API (e.g. in 'bg-script')
https://developer.chrome.com/extensions/contentSettings
http://docs.nwjs.io/en/latest/References/Manifest%20Format/#bg-script

**Comment by bjoernneumann** [comment]
Great! Thank you very much.
