### ISSUE TITLE
nw.js 0.13.0-rc1 icon bug?

### ISSUE THREAD

**Issue by owen-hong** [nwjs/nw.js#4522]
![image](https://cloud.githubusercontent.com/assets/6466628/13597511/028c1e50-e554-11e5-83be-682f84ad69f2.png)

**Comment by yeaphone** [comment]
I meet the same problem, can't change the icon

**Comment by c-geek** [comment]
No icon at all on [latest Linux x64nightly build](http://dl.nwjs.io/live-build/03-10-2016/d0b5cf2-ea112a8-3d99a78-678d67e/v0.13.0-rc2/nwjs-symbol-v0.13.0-rc2-linux-x64.tar.gz).

**Comment by Christywl** [comment]
Just as the bug said, the nw.exe icon and its shotcut icon are different from the nwjs app default icon in the taskbar. @rogerwang , is a bug for nwjs icon?

**Comment by sourceskyboxer** [comment]
It is not bug just find chromium has icon please find resource and replace nw.js icon or simple into manifest path to icon like MAINEFEST_ICON 
```
{
    ...
    "icon" = "myapp.icon",
    ...
}
```

Please make sure if else statement if icon doesn't exist from package.json's icon-custom-path into default icon of nw.js

Please improve it! for Windows x86 and x64 Thanks
