### ISSUE TITLE
Unable to compile nw v0.13.0-rc1

### ISSUE THREAD

**Issue by imeetdevpgi** [nwjs/nw.js#4523]
Hi,

We are unable to compile nw v0.13.0-rc1 with below mentioned configuration:

set GYP_MSVS_VERSION=2015
set DEPOT_TOOLS_WIN_TOOLCHAIN=0
set GYP_DEFINES="clang=0"

System Info : **Window 10**

We have fetched the source code from shared steps [here](https://github.com/nwjs/nw.js/blob/nw13/docs/For%20Developers/Building%20NW.js.md). But it's unable to execute './build/gyp_chromium' and throw an error message:'Environment variable "SYSTEMROOT" required to be set to valid path' . 

Please provide us any workaround to compile the source code with VS 2015.

Regards,
Rishu

**Comment by ghostoy** [comment]
I haven't tested building on Windows 10. But it should be working on Win10 & VS2015. Make sure you follow the official Chromium build instructions here (https://www.chromium.org/developers/how-tos/build-instructions-windows).

I'm closing this issue. Please ask further dev questions in nwjs-dev mailing list (https://groups.google.com/forum/#!forum/nwjs-dev).

**Comment by rogerwang** [comment]
this is an upstream issue, see https://bugs.chromium.org/p/chromium/issues/detail?id=440500
