### ISSUE TITLE
when I was package app.exe on windows xp, crashed on windows 7 and windows 2013.

### ISSUE THREAD

**Issue by yuzishui** [nwjs/nw.js#4524]
is there anybody meet this question?

when I was package on windows xp, the app.exe crashed on windows 7 and windows 2013.

**Comment by mscreenie** [comment]
Can you provide more details on this, what version are you using? Does this same error happen if you try to package a sample app for example?

**Comment by yuzishui** [comment]
thank you sir,now I know the reason,it's because of I only copy app.exe to another OS.today it is ok when I take all files ,DLLs and other.

thank you.
