### ISSUE TITLE
nwjs-v0.13.0-rc1-win-x64 node-main not working?

### ISSUE THREAD

**Issue by digitronic-games** [nwjs/nw.js#4525]
I've run into a bit of a problem, I'm trying to get an express app working inside of nwjs. When I try to run the app the window shows:

This site can’t be reached
localhost refused to connect.
ERR_CONNECTION_REFUSED

	{
		"name": "test",
		"version": "0.0.0",
		"private": true,
		"node-main": "./bin/www",
		"main": "http://localhost:3000",
		"dependencies": {
			"body-parser": "~1.13.2",
			"cookie-parser": "~1.3.5",
			"debug": "~2.2.0",
			"express": "~4.13.1",
			"jade": "~1.11.0",
			"morgan": "~1.6.1",
			"serve-favicon": "~2.3.0"
		}
	}

I'm just using the default express generator template. Has the node-main changed in the new update?

**Comment by rogerwang** [comment]
This was fixed in the latest nightly build: http://dl.nwjs.io/live-build/
