### ISSUE TITLE
OSX - 0.13.0 rc2 sdk x64 - package.json name with hyphen stops main window from launching.

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#4526]
OSX 10.9.5 Mavericks
Index of /live-build/03-09-2016/f8a6967-7fee480-3d99a78-93e6ec5/v0.13.0-rc2/

name was php-webkit in package.json and main window did not appear although nwjs icon was in dock OK.  Changed php-webkit to php_webkit and window opened fine. NWJS docs suggest that hyphen is a valid character.
package.json
{
  "name": "php-webkit",
  "main": "index.html"
}

Cheers.

**Comment by ghostoy** [comment]
I can't reproduce this issue. Could you remove `~/Library/Application Support/php-webkit` and and try again?

**Comment by Blatman** [comment]
Yup - works OK with the php-webkit folder removed, new one created worked fine.
Thanks for your help.
Cheers.
