### ISSUE TITLE
Localstorage migration

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#4527]
There still seems to be an issue with the migration of the localstorage data when upgrading from `v0.12` to `v0.13`. This is a follow-up of #4469.

When using the old `app://` protocol in v0.12, the localstorage file is being read from in this path:
`/path/to/appdata/LocalStorage/app_appname_0.localstorage`

Now when I try to run my application with the latest nightly build (03-09-2016/f8a6967-7fee480-3d99a78-93e6ec5/v0.13.0-rc2, linux64) while using the relative path to my `package.json`'s `main` file, a new and **empty** localstorage file is being generated in this directory:
`/path/to/appdata/Default/LocalStorage/chrome-extension_appid_0.localstorage`

NW.js should copy the localstorage file of the old `dataPath` if the current one in the new `dataPath` directory is missing.

Thanks!

**Comment by rogerwang** [comment]
will fix this soon.
