### ISSUE TITLE
0.13.0-rc1 - setSinkId doesn't work on windows

### ISSUE THREAD

**Issue by porsager** [nwjs/nw.js#4529]
Hi.

setSinkId on audio and video elements doesn't work with nodewebkit.

It works correctly in chrome 49

Test link: https://webrtc.github.io/samples/src/content/devices/multi/

Try to use the above link to test with while having multiple audio output options available. Sending sound to any other output than default shows success (logs to console), but the sound never comes out of that output.

**Comment by porsager** [comment]
Hi @rogerwang 
Is there any chance this will make it into 0.14 ?
Thanks.

**Comment by rogerwang** [comment]
Will see it soon.

**Comment by rogerwang** [comment]
@porsager I think the reason is that the mp3 codec is not supported by default. If you play with the video under "local media files", does it work for you?

**Comment by porsager** [comment]
@rogerwang Well it plays from the default output fine (any of the four playback options) including local media files.
But when i choose any other output nothing plays. If I specifically choose the same output as the one that is default it also works.

This is on Windows 10.

**Comment by rogerwang** [comment]
I need to find a system with multiple playback devices to reproduce it. Thanks.

**Comment by porsager** [comment]
Ok.
I Just tested some more and tried installing a virtual sound card, which actually appeared to work. The one that doesn't work is a usb headset (specifically a Plantronics D100-M). I will try to narrow down which things it is that doesn't work before you look closer..

I'll post more here when I'm done.

**Comment by rogerwang** [comment]
run it with '--v=1' and enable logging would help. See https://www.chromium.org/for-testers/enable-logging

**Comment by porsager** [comment]
Ah. Brilliant. Thanks a lot!
That gives me the following error when i switch to the device that doesn't work:
```
[4720:3352:0405/154629:ERROR:audio_manager_base.cc(264)] Invalid audio output parameters received;
using fake audio path. Channels: 0, Sample Rate: 48000, Bits Per Sample: 16, Frames Per Buffer: 480
```

**Comment by rogerwang** [comment]
It looks similar with #4170 . But theoretically NW shouldn't have any difference with Chromium browser on this...

**Comment by porsager** [comment]
Hi Robert.

Yeah that does seem similar. I just tested, and I can't make the usb headset work in node-webkit even if I set it as default in windows. If I set --force-wave-audio as suggested in the issue it will play audio, but then I'm unable to use setSinkId...

On 0.12.3 the headset works fine though. (but setSinkId isn't available with that chromium version).

Let me know if there is anything else i could test.

**Comment by porsager** [comment]
@rogerwang Breakthrough!
I'm sorry i didn't check this before. I was running NW 64 bit and Chrome 32 bit. I just checked it now, and setSinkId works fine with NW 32 bit on windows 10. 

I will get chrome 64 bit now and i assume that it most likely doesn't work...

**Comment by porsager** [comment]
Yes, doesn't work in 64 bit chrome either. I have submitted a bug to chromium here:
https://bugs.chromium.org/p/chromium/issues/detail?id=600736

Thanks for the help in tracking this down...
