### ISSUE TITLE
v13-rc2 nightly build OSX64 - PepperFlash statically linked?

### ISSUE THREAD

**Issue by cryptedco** [nwjs/nw.js#4530]
Hi, I am playing around with the PepperFlash plugin and the actual build shows an old version number, even without any containing plugin at the position it claims to be (related #4504).

That PepperFlash/... directory does not exist:

![screenshot 2016-03-09 15 15 02](https://cloud.githubusercontent.com/assets/326428/13637896/054b0f32-e60a-11e5-9b51-21ad2d40cc74.png)

**Comment by cryptedco** [comment]
@rogerwang - am I too stupid or is that something in rc2? Sorry to bother, but it is my personal last issue with rc2 :-)

**Comment by rogerwang** [comment]
It's not builtin. I'll see why it's in the registry. Maybe it's used for
file detection.

Ralf Schwoebel <notifications@github.com>于2016年3月10日周四 上午4:42写道：

**Comment by cryptedco** [comment]
thx!

**Comment by rogerwang** [comment]
The version string is builtin and fixed. Will update it.

**Comment by cryptedco** [comment]
Hi Roger, just tested the rc3 nightly download and see the Flash plugin is gone completely... is it still supported, if I just put the latest plugin into the directory?

**Comment by cryptedco** [comment]
Forget this question: see it is working, perfect! Thanks a lot!!! Wonderful rc3 release for me!
