### ISSUE TITLE
Full Screen window frame changes to the title of the html

### ISSUE THREAD

**Issue by krum110487** [nwjs/nw.js#4531]
This is just a quirk I found.

if you have a window title in the package.json

```
{
    "main": "signin.html",
    "name": "Main Container",
    "window": {
      "title":"TEST",
      "frame":true,
      "toolbar":false,
      "width": 800,
      "height": 500,
      "min_width": 800,
      "min_height": 500
    }
}
```

and the singin.html has a `<title>FullScreen</title>` tag in the html. When you first open it, it opens with the window name, when you go full screen it uses the page title.

This is not very high priority, but doesn't seem like it should be default functionality. I would assume that the Window title would always take priority or some sort of concatenation, in my example "TEST - FullScreen"

**Comment by Christywl** [comment]
I can't reproduce your issue on Windows with nwjs-sdk-v0.22.0. When the app start, it opens with the title(in `package.json/window`), and then quickly changes to the` title` in `index.html`.

**Comment by krum110487** [comment]
I think this is no longer an issue
