### ISSUE TITLE
Parsing of the package.json is picky for some values

### ISSUE THREAD

**Issue by krum110487** [nwjs/nw.js#4532]
I was using the following package

```
{
    "main": "index.html",
    "name": "AppName",
    "window":{"show": false}
}
```

and I was getting a parsing error, it took me a bit but it turns out the space after the `"show":` and before the `false` was the culprit, but all of the other spaces work just fine. It was a frustrating event of trial and error.

From what I can tell online standard json allows spaces, so I am unsure what is going on.

**Comment by nofear87** [comment]
I have test it without any problems.

**Comment by krum110487** [comment]
What version of node are you using, I am currently using v0.12.3

if you are on latest and it is working, then I suppose we could close this ticket :-) otherwise I will test some more and figure out why mine has this issue.

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.22.0. No parsing error occurs.

**Comment by krum110487** [comment]
it doesn't occur on newer versions either, so I can say for sure this is no longer an issue.
