### ISSUE TITLE
Whether you can set the color of the window title？

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#4534]
Whether you can set the color of the window title?
I want to set the color of the window title to be compatible with my application.

**Comment by rogerwang** [comment]
This is supported by frameless window, where the title is drawn by DOM : https://github.com/nwjs/nw.js/wiki/Frameless-window

btw, please post questions to the mailing list, not here: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by ghostoy** [comment]
And also you can try Chrome App Window API. See https://developer.chrome.com/apps/app_window#type-FrameOptions

**Comment by phpjishu** [comment]
Thank you! @ghostoy
