### ISSUE TITLE
nwjs 0.13.0 crashes at startup on openSuse 42.1 Leap

### ISSUE THREAD

**Issue by bjoernneumann** [nwjs/nw.js#4538]
When starting nwjs on openSUSE 42.1 leap it crashes about 2 of 10 times, with the following message:

```
[8609:8609:0310/090433:ERROR:ppapi_thread.cc(331)] Failed to load Pepper module from /usr/lib/my-app/PepperFlash/libpepflashplayer.so (error: /usr/lib/my-app/PepperFlash/libpepflashplayer.so: cannot open shared object file: No such file or directory)
../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected.
```

**Comment by MartyBum** [comment]
@rogerwang  Any ideas?

**Comment by rogerwang** [comment]
Could you please provide the crash dump? http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by bjoernneumann** [comment]
Attached two .dmp files. nw version is 0.18.6

[Crash Reports.zip](https://github.com/nwjs/nw.js/files/602885/Crash.Reports.zip)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by bjoernneumann** [comment]
Leap 42.1 is EOL I think. and it runs on newer Leap versions.
Therefore > closed.
