### ISSUE TITLE
[BUG] nwjs webview tag 0.13.0 crashes 

### ISSUE THREAD

**Issue by wzquyin** [nwjs/nw.js#4540]
use webview tag to open www.baidu.com
Middle click  the link "新闻" on the top right corner 
nw crash in nw.dll

asm:
.text:000000018051EB34                 call    sub_180552080
.text:000000018051EB39                 test    al, al
.text:000000018051EB3B                 jnz     short loc_18051EB43
.text:000000018051EB3D                 int     3               ; crashes here
.text:000000018051EB3E                 add     rsp, 28h
.text:000000018051EB42                 retn

i nop the "int 3" 
nw will show me a new window ,url is chrome://invalid

this bug is exist from 0.13-b1 to 0.13-rc1

**Comment by rogerwang** [comment]
Could you please show a full example?

When I tried to do this nothing happened but a message was logged in the console:
"<webview>: A new window was blocked.", source: extensions::webViewActionRequests (84)

**Comment by cryptedco** [comment]
If you implement a WebView, as far as I understood, you have to take care of "newwindow" events yourself:

webview.addEventListener('newwindow', function (e) {
  // do something with e.targetUrl
});

I can not read Chinese, but Baidu works for me on wild clicking around without problems on rc3 from yesterday night... in a WebView...

**Comment by wzquyin** [comment]
I already addeventListener 'newwindow' event,
but it does not trigger,

before trigger newwindow event,it crash!

i tried 13-rc3, it worse then rc2, rc3 will disapper when a middle click, rc2 show a windows error dialog

there is my code 

/**************************package.json:********************************/
{
  "main": "index.html",
  "name": "test",
  "version": "3.1.0",
  "webkit": {
    "plugin": true
  },
  "window": {
    "title": "eee",
    "frame": false,
    "width": 2562,
    "height":768,
    "position": "center",
    "min_width": 1200,
    "min_height": 768,
    "icon":"icon.png",
    "transparent":false
  },
  "node-remote": "http://*/*",
  "nodejs": "true",
  "chromium-args": "--disable-web-security"
}



/***********************index.html:*******************************/
<html style="height:100%;">
<head>
    <meta charset="utf-8">
    <title></title>
</head>
<body>
        <webview tabindex="-1" src="http://www.baidu.com" partition="app:1457593180494"
                 style="width: 2562px; height: 1328px;" id="webview" height="800px"></webview>
				 <script>
				 
				 document.getElementById("webview").addEventListener("newwindow", function (evt) {
							console.log("newwindow: " + evt.targetUrl);
							

				});
				 </script>
</body>

</html>

this is the links you need middle click
[http://133.130.120.88:3000/1.png](url)

this is the error dialog
[http://133.130.120.88:3000/2.png](url)

**Comment by rogerwang** [comment]
will check your sample. btw, the crashes in the live build is a regression unrelated to this issue.

**Comment by wzquyin** [comment]
thanks a lot ,,,but i can`t find  any wrong is my sample,can you please point out that ,thanks very mush,and please,this problem has troubled me for a long time.

**Comment by wzquyin** [comment]
ok, I think i found why,
There are two reasons for this error
1. "node-remote": "http://*/*",
2.as long as you set "src" attribute  to  any local file a， then change it to "www.baidu.com" ,,middle click the links i said .it will crash

**Comment by rogerwang** [comment]
I didn't reproduce this. But this should be the same with #4587, which was just fixed.
