### ISSUE TITLE
0.13.0 toolbar won't show up

### ISSUE THREAD

**Issue by c-geek** [nwjs/nw.js#4541]
The toolbar doesn't show up since at least nwjs-v0.13.0-alpha3-linux-x64, to lastest nighlty build.

But It *does* with 0.12.3 (exact same configuration).

OS Ubuntu x64 14.04 LTS

**Comment by FiatPax** [comment]
I am not sure if that ever will come back again but you can use window.location.href="Your Url" command on console.

**Comment by c-geek** [comment]
I don't have devtools either :-/ so no console.

**Comment by c-geek** [comment]
You mean this is actually an intentional removal?

**Comment by Spiffyk** [comment]
It is intentional

**Comment by c-geek** [comment]
OK reading http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

I am closing.

**Comment by douineauromain** [comment]
0.14.0-rc3 :⌘+⌥+i  don't work
OSX El Capitan 10.11.2

**Comment by douineauromain** [comment]
Testing the 0.13.4 on Windows 10. F12 does nothing.

Maybe my package.json cause bug ?

```
{
    "inject-js-end": "",
    "node-main": "",
    "maintainers": [...],
    "keywords": [...],
    "snapshot": "",
    "js-flags": "",
    "version": "1",
    "chromium-args": "",
    "description": "...",
    "webkit": {
        "java": false,
        "plugin": false,
        "page-cache": false
    },
    "window": {
        "resizable": true,
        "exe_icon": "",
        "fullscreen": false,
        "as_desktop": false,
        "toolbar": true,
        "show_in_taskbar": true,
        "show": true,
        "title": "My Tool",
        "frame": true,
        "icon": "osx.png",
        "height": 600,
        "mac_icon": "",
        "visible": true,
        "transparent": false,
        "kiosk": false,
        "always-on-top": false,
        "kiosk_emulation": false,
        "width": 800,
        "position": ""
    },
    "name": "My_tool",
    "webexe_settings": {
        "linux-x64": true,
        "nw_compression_level": 9,
        "force_download": false,
        "mac-x32": true,
        "custom_script": "",
        "uncompressed_folder": false,
        "nw_version": "0.12.1",
        "download_dir": "C:/Users/me/AppData/Local/Web2Executable/Web2Executable/files/downloads",
        "export_dir": "D:\\Users\\me\\Node.js Webkit\\build",
        "windows-x64": true,
        "linux-x32": true,
        "windows-x32": true,
        "mac-x64": true
    },
    "single-instance": true,
    "main": "index.html",
    "user-agent": "",
    "additional_trust_anchors": [
        ""
    ],
    "nodejs": true,
    "inject-js-start": "",
    "app_name": "My Tool",
    "dependencies": {
        "auto-launch": "^1.1.1",
        "moment": "^2.11.1",
        "open": "0.0.5",
        "parse": "^1.7.1",
        "q": "^1.4.1",
        "underscore": "^1.8.3",
        "webtorrent": "^0.90.3"
    },
    "node-remote": "http://localhost",
    "bugs": "mailto:douineauromain@yahoo.fr"
}
```

**Comment by rogerwang** [comment]
@douineauromain are you using SDK build?

**Comment by douineauromain** [comment]
@rogerwang I use nwbuild

**Comment by RohitSharma27** [comment]
@douineauromain About package.json, Please refer this [http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#manifest-format](url)
link because a couple of things have changed from the previous versions like "inject-js-start" is "inject_js_start" and "toolbar" property is always "false". Just check out the new changes. Hope it will help.

**Comment by douineauromain** [comment]
@RohitSharma27 This json was generated with Web2Executable. I will take a look thx

**Comment by VikomiC** [comment]
I have same problem with 0.14.5 as above on Macs.
"⌘+⌥+i" doesn't open console. Is there any solution?
Manifest was checked, changes were applied. But, doesn't helped me.

**Comment by RohitSharma27** [comment]
@VikomiC if you are using SDK build, then it will definitely work. :)

**Comment by VikomiC** [comment]
@RohitSharma27, Yes, sure :) I found it after some time.

I can see that console.log is not written in the terminal, where nw.js is started. But logs are written in DevTools.
Will they be written to defined file, if I will not use SDK version for LIVE for example?

**Comment by RohitSharma27** [comment]
Well, No. Console.log will log to your console which is there in your dev tool. If you want to write it to some file, then you should look out for some logger node module. You can easily find one. Cheers.

**Comment by VikomiC** [comment]
So, found a solution to write logs also in syslog/terminal.
There is attribute in package.json for chromium. Just need to add "--enable-logging=stderr".

`"chromium-args": "--enable-logging=stderr",`
