### ISSUE TITLE
Error in gclient building in CentOS 6.7

### ISSUE THREAD

**Issue by Leprosy** [nwjs/nw.js#4542]
I'm trying to build nwjs under CentOS 6.7, this message appears when I do `gclient sync --no-history`:

```
Syncing projects: 100% ( 1/ 1) src

src (ERROR)
----------------------------------------
[0:00:00] Started.
_____ src at origin/nw12
----------------------------------------
Error: 1> Could not switch upstream branch from refs/remotes/origin/nw13 to refs/remotes/origin/nw12
1> Please use --force or merge or rebase manually:
1> cd /home/leprosy/develop/node-webkit/src; git rebase refs/remotes/origin/nw12
1> OR git checkout -b <some new branch> refs/remotes/origin/nw12

```

I'm following the steps detailed here : https://github.com/nwjs/nw.js/wiki/Building-nw.js

**Comment by Leprosy** [comment]
no chance?

**Comment by rogerwang** [comment]
try gclient sync --reset --force --with_branch_heads. http://docs.nwjs.io/en/v0.13.0-rc3/For%20Developers/Building%20NW.js/

**Comment by Leprosy** [comment]
It now show me
```error: pathspec 'refs/remotes/origin/nw13' did not match any file(s) known to git.```

**Comment by Leprosy** [comment]
Has anyone being able to build nwjs under CentOS 6.x or RH 6.x so far?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs?

**Comment by rogerwang** [comment]
close as chromium upstream doesn't support building from an old linux system: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_build_instructions.md#System-requirements
