### ISSUE TITLE
Intercepting all http requests

### ISSUE THREAD

**Issue by eriksank** [nwjs/nw.js#4547]
Would something like this be possible?
```javascript
app.on('httprequest')=function(url,postdata) {
	...
	return whateverCustomText;
}
```
nw.js would not execute any request by itself, but relegate that job to the app.on('httprequest') handler. Furthermore, nw.js would use the string returned as response to the request. Is it possible to implement this with existing facilities in nw.js?

**Comment by rogerwang** [comment]
Would like to support it. merge with #409 

See also https://bugs.chromium.org/p/chromium/issues/detail?id=104058

**Comment by zhalil** [comment]
same problem, jumps by 500 pieces with one mouse scroll
