### ISSUE TITLE
some bugs about  NWjs

### ISSUE THREAD

**Issue by lee99** [nwjs/nw.js#4549]
Hi,
I found there are some bugs,maybe it is reduplicative.
1. the contextmenu of image tag.click the " open image in the new tab" item ,the app crashed .
2. inside of the webview ,press "ctrl" key and scrolling  the mousewheel ,you will see the whole window are zooming,not only the Current webview, if you are opened some windows. you will see all the windows are zooming.
it is fine when i do that outside of the webview.
3. some logs,but it works

-- under win7 x32
`[0311/190300:ERROR:crash_report_database_win.cc(549)] CreateDirectory C:\Users\Lee99\AppData\Local\User Data\Crashpad: 系统找不到指定的路径。 (0x3)
[0311/190300:ERROR:registration_protocol_win.cc(82)] TransactNamedPipe: 管道已结束。 (0x6D)
[8836:5864:0311/194045:ERROR:browser_plugin_guest.cc(445)] Attempting to require callback on nonexistent surface`
-- under mac 
`2016-03-12 22:44:56.709 nwjs Helper[11202:1003408] Couldn't set selectedTextBackgroundColor from default ()
Mar 12 23:17:40  nwjs Helper[11271] <Error>: CGAffineTransformInvert: singular matrix.`

Thank you for your great work. @rogerwang

**Comment by ghostoy** [comment]
@lee99 Could you provide the version of NW.js and a sample app as well?

**Comment by xurweb** [comment]
when i use <webview> tag , click a link, alse has the same error  that [8836:5864:0311/194045:ERROR:browser_plugin_guest.cc(445)] Attempting to require callback on nonexistent surface .
do you resove this problem? @lee99
