### ISSUE TITLE
blackboxing working for anyone in DevTools for 0.13-rc1?

### ISSUE THREAD

**Issue by haraldox** [nwjs/nw.js#4550]
For Chrome blackboxing scripts feature, see: https://gist.github.com/paulirish/c307a5a585ddbcc17242

**Comment by rogerwang** [comment]
@Christywl please try this feature

**Comment by Christywl** [comment]
Seem it work fine on nwjs-sdk-v0.25.3.
![image](https://user-images.githubusercontent.com/20039821/30893312-0f91c790-a370-11e7-885a-7a747891a22c.png)

**Comment by Christywl** [comment]
close until there is more information
