### ISSUE TITLE
Console shows errors when frameless main window startup on OSX.  [nw0.13rc2]

### ISSUE THREAD

**Issue by sean220** [nwjs/nw.js#4552]
2016-03-11 23:13:05.951 nwjs[4043:370038] NSWindow warning: adding an unknown subview: <WebContentsViewCocoa: 0x7f91dacba640>. Break on NSLog to debug.
2016-03-11 23:13:05.952 nwjs[4043:370038] Call stack:
(
    0   AppKit                              0x00007fff9ed1e4ef -[NSThemeFrame addSubview:] + 107
    1   nwjs Framework                      0x00000001114a5cad _ZN2v88UnlockerD1Ev + 20590733
    2   nwjs Framework                      0x00000001114a54d0 _ZN2v88UnlockerD1Ev + 20588720
    3   nwjs Framework                      0x00000001114a462a _ZN2v88UnlockerD1Ev + 20584970
    4   nwjs Framework                      0x0000000111fc2a29 _ZN2v88UnlockerD1Ev + 32243209
    5   nwjs Framework                      0x0000000111f0f1c1 _ZN2v88UnlockerD1Ev + 31507873
    6   nwjs Framework                      0x0000000111fe0431 _ZN2v88UnlockerD1Ev + 32364561
    7   nwjs Framework                      0x0000000111fe22b9 _ZN2v88UnlockerD1Ev + 32372377
    8   nwjs Framework                      0x0000000111fe24df _ZN2v88UnlockerD1Ev + 32372927
    9   nwjs Framework                      0x0000000111ffb552 _ZN2v88UnlockerD1Ev + 32475442
    10  nwjs Framework                      0x00000001121ebd6f _ZN2v88UnlockerD1Ev + 34509135
    11  nwjs Framework                      0x0000000111b0cc58 _ZN2v88UnlockerD1Ev + 27303992
    12  nwjs Framework                      0x00000001118ed19f _ZN2v88UnlockerD1Ev + 25077119
    13  nwjs Framework                      0x0000000111a33929 _ZN2v88UnlockerD1Ev + 26414345
    14  nwjs Framework                      0x000000010f3c6e18 ChromeMain + 15791304
    15  nwjs Framework                      0x000000010e9a27ea ChromeMain + 5156506
    16  nwjs Framework                      0x000000010e9c4cd9 ChromeMain + 5297033
    17  nwjs Framework                      0x000000010e9c5218 ChromeMain + 5298376
    18  nwjs Framework                      0x000000010e997501 ChromeMain + 5110705
    19  nwjs Framework                      0x000000010e9bb1ba ChromeMain + 5257322
    20  nwjs Framework                      0x000000010e996f04 ChromeMain + 5109172
    21  CoreFoundation                      0x00007fff9e8e65c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    22  CoreFoundation                      0x00007fff9e8d841c __CFRunLoopDoSources0 + 556
    23  CoreFoundation                      0x00007fff9e8d793f __CFRunLoopRun + 927
    24  CoreFoundation                      0x00007fff9e8d7338 CFRunLoopRunSpecific + 296
    25  HIToolbox                           0x00007fff8e5ad935 RunCurrentEventLoopInMode + 235
    26  HIToolbox                           0x00007fff8e5ad76f ReceiveNextEventCommon + 432
    27  HIToolbox                           0x00007fff8e5ad5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
    28  AppKit                              0x00007fff9ed690ee _DPSNextEvent + 1067
    29  AppKit                              0x00007fff9f135943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    30  AppKit                              0x00007fff9ed5efc8 -[NSApplication run] + 682
    31  nwjs Framework                      0x000000010e997cff ChromeMain + 5112751
    32  nwjs Framework                      0x000000010e997354 ChromeMain + 5110276
    33  nwjs Framework                      0x000000010e9d82f3 ChromeMain + 5376419
    34  nwjs Framework                      0x000000010e54c265 ChromeMain + 608533
    35  nwjs Framework                      0x000000011183b1f7 _ZN2v88UnlockerD1Ev + 24348119
    36  nwjs Framework                      0x000000011183d962 _ZN2v88UnlockerD1Ev + 24358210
    37  nwjs Framework                      0x000000011183706d _ZN2v88UnlockerD1Ev + 24331341
    38  nwjs Framework                      0x000000010e957378 ChromeMain + 4848168
    39  nwjs Framework                      0x000000010e9567f6 ChromeMain + 4845222
    40  nwjs Framework                      0x000000010e4b7992 ChromeMain + 66
    41  nwjs                                0x000000010e23cd52 main + 530
    42  nwjs                                0x000000010e23cb34 nwjs + 2868

**Comment by jssuttles** [comment]
I've seen this as well.

**Comment by jssuttles** [comment]
"frame": false,
"transparent": true

**Comment by geisbruch** [comment]
I have a similar stack with a frameless app

2016-03-30 22:05:07.973 nwjs[29037:2674008] NSWindow warning: adding an unknown subview: <WebContentsViewCocoa: 0x7f94b07b5560>. Break on NSLog to debug.
2016-03-30 22:05:07.975 nwjs[29037:2674008] Call stack:
(
	0   AppKit                              0x00007fff98f854ef -[NSThemeFrame addSubview:] + 107
	1   nwjs Framework                      0x000000010a4f270d _ZN2v88UnlockerD1Ev + 20590669
	2   nwjs Framework                      0x000000010a4f1f30 _ZN2v88UnlockerD1Ev + 20588656
	3   nwjs Framework                      0x000000010a4f107a _ZN2v88UnlockerD1Ev + 20584890
	4   nwjs Framework                      0x000000010b00f5e9 _ZN2v88UnlockerD1Ev + 32243497
	5   nwjs Framework                      0x000000010af5bd81 _ZN2v88UnlockerD1Ev + 31508161
	6   nwjs Framework                      0x000000010b02d051 _ZN2v88UnlockerD1Ev + 32364945
	7   nwjs Framework                      0x000000010b02eed9 _ZN2v88UnlockerD1Ev + 32372761
	8   nwjs Framework                      0x000000010b02f0ff _ZN2v88UnlockerD1Ev + 32373311
	9   nwjs Framework                      0x000000010b048172 _ZN2v88UnlockerD1Ev + 32475826
	10  nwjs Framework                      0x000000010b238a0f _ZN2v88UnlockerD1Ev + 34509647
	11  nwjs Framework                      0x000000010ab59798 _ZN2v88UnlockerD1Ev + 27304152
	12  nwjs Framework                      0x000000010a939cef _ZN2v88UnlockerD1Ev + 25077295
	13  nwjs Framework                      0x000000010aa80469 _ZN2v88UnlockerD1Ev + 26414505
	14  nwjs Framework                      0x0000000108413768 ChromeMain + 15792152
	15  nwjs Framework                      0x00000001079ef13a ChromeMain + 5157354
	16  nwjs Framework                      0x0000000107a11629 ChromeMain + 5297881
	17  nwjs Framework                      0x0000000107a11b68 ChromeMain + 5299224
	18  nwjs Framework                      0x00000001079e3e51 ChromeMain + 5111553
	19  nwjs Framework                      0x0000000107a07b0a ChromeMain + 5258170
	20  nwjs Framework                      0x00000001079e3854 ChromeMain + 5110020
	21  CoreFoundation                      0x00007fff9d35b5c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00007fff9d34d41c __CFRunLoopDoSources0 + 556
	23  CoreFoundation                      0x00007fff9d34c93f __CFRunLoopRun + 927
	24  CoreFoundation                      0x00007fff9d34c338 CFRunLoopRunSpecific + 296
	25  HIToolbox                           0x00007fff9887a935 RunCurrentEventLoopInMode + 235
	26  HIToolbox                           0x00007fff9887a76f ReceiveNextEventCommon + 432
	27  HIToolbox                           0x00007fff9887a5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	28  AppKit                              0x00007fff98fd00ee _DPSNextEvent + 1067
	29  AppKit                              0x00007fff9939c943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	30  AppKit                              0x00007fff98fc5fc8 -[NSApplication run] + 682
	31  nwjs Framework                      0x00000001079e464f ChromeMain + 5113599
	32  nwjs Framework                      0x00000001079e3ca4 ChromeMain + 5111124
	33  nwjs Framework                      0x0000000107a24c43 ChromeMain + 5377267
	34  nwjs Framework                      0x00000001075989f5 ChromeMain + 608933
	35  nwjs Framework                      0x000000010a887d17 _ZN2v88UnlockerD1Ev + 24348247
	36  nwjs Framework                      0x000000010a88a482 _ZN2v88UnlockerD1Ev + 24358338
	37  nwjs Framework                      0x000000010a883b8d _ZN2v88UnlockerD1Ev + 24331469
	38  nwjs Framework                      0x00000001079a3cc8 ChromeMain + 4849016
	39  nwjs Framework                      0x00000001079a3146 ChromeMain + 4846070
	40  nwjs Framework                      0x0000000107503f92 ChromeMain + 66
	41  nwjs                                0x000000010729cd52 main + 530
	42  nwjs                                0x000000010729cb34 nwjs + 2868
	43  ???                                 0x0000000000000002 0x0 + 2
)

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.22.0, don't see these logs in the console.

.

**Comment by Christywl** [comment]
close until there is more information.
