### ISSUE TITLE
restore event wrongly fired on minimalization

### ISSUE THREAD

**Issue by r-flash** [nwjs/nw.js#4557]
Hi,
with 0.13.0-rc2 on Windows 7 I'm getting the 'restore' event on win fired right after window minimalization when minimizing from maximized state. This doesn't happen when minimizing from non-maximized state.

I suspect that the extra 'restore' event is fired because the window gets unmaximized along with minimization. When un-minimizing to maximized state, both 'restore' and 'maximize' are fired.

Is there a way to tell if the 'restore' event was fired due to un-maximalization or un-minimalization? Otherwise it's impossible to track the window state.

(I know it's hard to keep track of the states in this comment :) If you're getting lost, I can try to represent it in some kind of diagram.)

**Comment by ghostoy** [comment]
It was changed in 0.13.0. See migration notes here: http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#window.

**Comment by r-flash** [comment]
I'm aware of it. But now, when 'umaximize' got replaced with 'restore', it's sometimes hard to tell what caused a specific 'restore' event.

In 0.13.0, to be able to successfully tell whether the window is currently maximized, you have to keep track of whether the window was maximized before last minimization and how many 'restore's were fired since that minimalization.

It's not impossible to do (I know I said it was), just really inconvenient.

**Comment by ghostoy** [comment]
The changed behavior is consistent with Chrome API. See https://developer.chrome.com/apps/app_window#event-onRestored
You have to track the state of window for now. But it isn't a hard job.

**Comment by r-flash** [comment]
Alright. I created a [gist](https://gist.github.com/r-flash/4a9357f74c6f19955a90) to make it easier for others.
