### ISSUE TITLE
[OSX 10.11.3] win.setTransparent method not defined

### ISSUE THREAD

**Issue by cadorn** [nwjs/nw.js#4558]
Using: http://dl.nwjs.io/live-build/03-13-2016/c0a3f15-32d0338-3d99a78-678d67e/v0.13.0-rc3/nwjs-sdk-v0.13.0-rc3-osx-x64.zip

Following instructions: https://github.com/nwjs/nw.js/wiki/Transparency

When `  "window": { "transparent": true }` is set in `package.json` it does not start at all. When set to false, `win.setTransparent` is undefined.

Anyone else got transparency working on OSX?

Is there an example/test app for transparency somewhere?

**Comment by rogerwang** [comment]
@jtg-gg could you please look into this issue?

@cadorn transparency is now only supported via the manifest option. So win.setTransparent is no longer there.

**Comment by rogerwang** [comment]
@cadorn It's supposed to work only with frameless window. Please try setting "frame" to false. Will update docs.

**Comment by cadorn** [comment]
`{ "transparent": true, "frame": false }` works. I did not even have to set the command-line flags.

**Comment by jtg-gg** [comment]
@rogerwang sorry, I just saw this, we need to update the documentation for nw13, are we still using the wiki in the github ?

**Comment by rogerwang** [comment]
@jtg-gg no problem. We are using docs.nwjs.io now.

**Comment by cryptedco** [comment]
Roger, how can we support the documentation? Also: a search of the docs would be great....
![screenshot 2016-03-14 10 33 33](https://cloud.githubusercontent.com/assets/326428/13740301/4e23588a-e9d0-11e5-91a3-9721c77bac50.png)

**Comment by rogerwang** [comment]
@cryptedco  The documentation is in the docs directory of this repo. You're welcome to submit PR. A proposal for reorganizing the doc was posted and under discussion: https://groups.google.com/d/msg/nwjs-dev/2EB5AzQd2-0/PQd0VFz_GAAJ
