### ISSUE TITLE
Window title and icon misisng and taskbar is blocked

### ISSUE THREAD

**Issue by Kriknos** [nwjs/nw.js#4559]
For the rc1 I figured ok they'll get this issue fix asap. But it is still a problem in rc2. It all worked fine in beta 7.

The Window title and icon are not shown. Also I have my taskbar set to auto hide so I can not select anything on my taskbar with the nw.js app maximized, which is the default I have it set to at startup. As it maybe important I am running on windows 7. For now I have to stick with the beta 7 till this is fixed.

**Comment by rogerwang** [comment]
The title and icon issue is a duplicate of #4486 and it was just fixed in live build.

**Comment by Christywl** [comment]
@Kriknos , is this issue still reproduced on your test with the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
