### ISSUE TITLE
Node-Webkit: Child window to call parent window

### ISSUE THREAD

**Issue by anandh** [nwjs/nw.js#456]
Hi Everybody,
I have created one main window & child window , 
Parent window code:mainwin.html
++++++++++++++++++++++++++++++++++++++++++++++++++++++
var mainwin       = gui.Window.get();
var childwin = gui.Window.open('childwin.html', {
    x: 100, y: 100, width: 200, height: 300
  });
function changeparentmethod()
{
alert('came main');
mainwin.show(true);
}
++++++++++++++++++++++++++++++++++++++++++++++++++++++
inside childwin.html file, Can i call the any mainwin window methods and properties like below ?
Child window code:childwin.html
++++++++++++++++++++++++++++++++++++++++++++++++++++++
var currwin       = gui.Window.get();
currwin.opener.changeparentmethod();
++++++++++++++++++++++++++++++++++++++++++++++++++++++
For this i am getting an error, how to implement this functionality??
In javascript opener method is working fine.

**Comment by freddy-tech** [comment]
I got this Error in console while running above code

`extensions::schemaUtils:113 Uncaught Error: Invocation of form nw.Window.open(string, string) doesn't match definition nw.Window.open(string url, optional object options, optional function callback)`

**Comment by RohitSharma27** [comment]
@freddy-tech that's because be.Window.open has changed from nw13 and onwards. See the latest documentation.

**Comment by freddy-tech** [comment]
Thanks i found Solution it was simple with pure JavaScript 
`window.opener.function_name()`
is solved my issue..

**Comment by sourceskyboxer** [comment]
My god. what are you getting wrong English? Oh :(

hasParent() is correct because Adobe System writes clean like AS3 has "has[variable-functionname]" example hasEvent, hasProprety or whatever

Please change "haveParent" to "hasParent" because window = it that is why It has - But "have" means "we have" or "they have" or "You have". That is wrong. Thanks for changing alphabets.

Thanks!
