### ISSUE TITLE
Unable to play certain YouTube videos under NWJS, plays fine as Chrome Packaged App

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#4561]
For some reason I am unable to play a YouTube video inside a NWJS app but the exact same equivalent as Chrome packaged app plays the same video without any issues. The network log shows a "canceled" xhr request which leads to playback failure, the same call is made successfully on the chrome packaged app version.

![ss2](https://cloud.githubusercontent.com/assets/8498057/13729764/61823e72-e92c-11e5-9f38-cde667c605ed.png)

Sample test example displaying the problem:

**Folder structure**

<pre>main
|_ index.html
|_ package.json</pre>

**Contents**

 - index.html

````html
<!DOCTYPE html>
<html>
    <head>
        <title>YouTube player test</title>
        <meta charset="utf-8">
    </head>
    <body>
        <webview src="https://www.youtube.com/watch?v=8_tQr_uZMcg" style="position: fixed;bottom: 0;right: 0;top:0;left:0;"></webview>
    </body>
</html>
````

 - package.json
````json
{
    "name": "nw-app",
    "version": "1.0.0",
    "description": "",
    "main": "index.html",
    "author": "",
    "window": {
        "width": 760,
        "height": 460
    }
}
````

NW.js version being used: v0.13.0-rc2
OS: Win7 x64

I have tried modifying the request headers to be exactly the same as Chrome's (including user agent) but it did not make any difference, I cannot understand what is happening and would appreciate any help with this. `chrome://net-internals/#events` would probably shed more light on this issue, but I cannot open it under nwjs.

**Comment by cryptedco** [comment]
The webview asks for a permission to play media AND to start flash...:

You have to address these permissions, if you run it a webview:

`    webview.addEventListener('permissionrequest', function (e) {
        console.log("webview"+objCount+": permission - "+e.permission);

        if (e.permission === 'loadplugin') {
            if(userSession.allowPlugins) {
                e.request.allow();
            } else {
                e.request.deny();
            }
        }
        if (e.permission === 'download') {
            e.request.allow();
        }
        // media
        if (e.permission === 'media') {
            e.request.deny();
        }
        if (e.permission === 'geolocation') {
            e.request.deny();
        }
    });
`
I had the same problems with our personatool.com - you can download the source and look into js/app.js ...

**Comment by Yonezpt** [comment]
@cryptedco The webview never asks for flash/plugin permission, even in the packaged app version it uses only the HTML5 player for the exact same video. Regardless, I still tried your suggestion with the sample test I provided above, I even allowed any permission requested without conditions and also tried with

````json
    "webkit": {
        "plugin": true
    }
````
included in the manifest as well. Not once it asked for any permissions.

Unfortunately this is not the case of it trying to use a plugin and failing, it appears to be something else.

**Comment by Yonezpt** [comment]
I believe I might have found a probable cause for this, as I understand NWJS does not have mp4 playback capabilities due to licensing. The video in question that is trying to load and failing appears to be served in mp4 format while all the others that play with success (so far) are webm.

Am I right in assuming this? I mean the nwjs inability to play mp4 files.

**Comment by cryptedco** [comment]
Good point... I just dragged and dropped a MP4 file into NWJS-13 and it shows the play bar, but does not play... so I guess you are right... 
![screenshot 2016-03-13 22 26 51](https://cloud.githubusercontent.com/assets/326428/13731501/c990d2ec-e96a-11e5-9f85-84adcad67969.png)

**Comment by Yonezpt** [comment]
Thank you for the confirmation, I guess this is more than enough to confirm this issue. Hopefully it might help others that find themselves in the same situation. Again, thanks for your help!

**Comment by cTn-dev** [comment]
@Yonezpt @cryptedco sorry for bothering you guys, but does the ffmpegsumo.dll trick still applies? (when it comes to the released 0.13 and higher), i am currently on the latest stable version, 0.13.2 and i am unable to play any youtube videos, but from what i can see chrome is not being supplied with ffmpegsumo.dll anymore?, what is the current workaround ?

**Comment by cryptedco** [comment]
Stefan, no prob: the ffmpegsumo.dll trick in concept does still work, but is just ffmpeg.dll now... also a lot of YouTube videos should play without it:

could you open the DevTools and do a 

window.location.href="chrome://plugins"

you will also need to have the PepperFlash player in your root directory of nw.exe... you can find it either in your Chrome directory (note the versions)...

![screenshot 2016-03-31 16 08 08](https://cloud.githubusercontent.com/assets/326428/14178426/e3809a90-f75a-11e5-9807-420229838fe2.png)

**Comment by cTn-dev** [comment]
Thanks Ralf, @cryptedco i copied the latest pepper flash to the nwjs directory (the plugin does load properly) sadly i am still unable to play any youtube videos, from where do you get the latest ffmpeg.dll ? since ffmpeg.dll or ffmpegsumo.dll are not packed with chrome anymore.

I should probably note with nwjs 0.13 beta 1 or so everything worked fine, but with the latest version none of the videos play (just getting the regular "an error occurred, please try again later" message)

The network monitor has one xhr with (canceled) status as mentioned in the original post.

**Comment by cryptedco** [comment]
Depending now on how you load the youtube page: are you using a webview or directly? From here on, once you confirmed that the plugin is there, it is probably a rights problem... could you either post or mail me the URL of the video, so I can check if it is a dll problem or a rights problem?

**Comment by cTn-dev** [comment]
What i am doing is, having the youtube api/player load on a web server and i am embedding that in my app (to deal with the origin problems).

I can give you an id of one of the songs eDjc0CkkbTA or here is a full playlist https://www.youtube.com/watch?v=eDjc0CkkbTA&index=1&list=PL2mte-kJELfbMIJN1k-_gHiKpznIBDq27

Basically none of the videos of the playlist load (all of them end up in an error).
Keep in mind that i didn't replace the ffmpeg.dll since i am unable to find its replacement in the x64 chrome version that i got installed on my windows machine.

**Comment by cryptedco** [comment]
I can not pinpoint the reason for it here... it works in my tool: www.personatool.com - just download it for free and test it there... it plays for me... the tool is NWJS-13.3-pre both win or mac...
