### ISSUE TITLE
Mouse cursor visible in the full screen mode

### ISSUE THREAD

**Issue by swolfish** [nwjs/nw.js#4562]
Please, can someone take a look on this - 
http://stackoverflow.com/questions/34717296/cannot-completely-remove-mouse-cursor-in-nw-js-app.

It seems like some kind of NW.js overriding but cannot figure it.

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
