### ISSUE TITLE
Update engines for nw12

### ISSUE THREAD

**Issue by voxking** [nwjs/nw.js#4564]
some js and web features are missing and I dont like to work with prerelease version + my whole project will need a rewrite

**Comment by rogerwang** [comment]
The browser engine will not be updated in 0.12. There is major version bump when the browser engine gets updated.

The current RC version is very close to the final version and most APIs are compatible with 0.12.

**Comment by voxking** [comment]
ok thanks i will move to 0.13 when available and use typescript to produce ES5 code plus some polyfills :D :bow:
