### ISSUE TITLE
[docs] list extension API we supported

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#4565]
We already support all chrome.* API in the "Chrome App" platform

In addition, we supported some chrome.* API in the "extension platform, which should be listed in docs.

Difference between 2 platforms:
https://developer.chrome.com/apps/api_index
https://developer.chrome.com/extensions/api_index

**Comment by ghostoy** [comment]
I'll look into this issue.

**Comment by ghostoy** [comment]
@rogerwang Are you aware of which extension platform APIs can be used in NW.js?

**Comment by rogerwang** [comment]
I have a list for this
