### ISSUE TITLE
node-gyp rebuild ffi

### ISSUE THREAD

**Issue by waiting0729** [nwjs/nw.js#4570]
hi,all:)I want to use node-ffi in in nwjs.I node-gyp rebuild ffi ,occurr 
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platf
orm for project 'ffi.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to bui
ld a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [D
:\node-webkit\nwjs-v0.12.3-win-ia32\node-ffi\node-ffi-master\build\deps\libffi\ffi.vcxproj]
I want rebuilt ffi in linux for windows,becase it is  very complex in windows.What could I do here?My nw.js version is nwjs-v0.12.3-win-ia32
Thanks in advance)))

**Comment by rogerwang** [comment]
Please use latest 0.13.0-rc3. And see https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ
