### ISSUE TITLE
Sqlite3 module compilation error with v0.13.0-rc1 and v0.13.rc3

### ISSUE THREAD

**Issue by nerverwind** [nwjs/nw.js#4571]
hi, i am testing nw v0.13.0-rc1 and i try to compile node sqlit3, and i got same errors:

sudo node-pre-gyp rebuild --runtime=node-webkit --target=0.13.0-rc1
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.23
node-pre-gyp info using node@5.7.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.7.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@5.7.0 | darwin | x64
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/WZX/.nw-gyp/0.13.0-rc1/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/WZX/.nw-gyp/0.13.0-rc1',
gyp info spawn args   '-Dmodule_root_dir=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@5.7.0 | darwin | x64
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:9704:26: warning: unused variable 'sqlite3one'
      [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../src/database.cc:143:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:227:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:505:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:605:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings and 4 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:286:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "build" "--runtime=node-webkit" "--target=0.13.0-rc1" "--module=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/lib/binding/node-webkit-v0.13.0-rc1-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/lib/binding/node-webkit-v0.13.0-rc1-darwin-x64"
gyp ERR! cwd /Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3
gyp ERR! node -v v5.7.0
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp build --runtime=node-webkit --target=0.13.0-rc1 --module=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/lib/binding/node-webkit-v0.13.0-rc1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/lib/binding/node-webkit-v0.13.0-rc1-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "rebuild" "--runtime=node-webkit" "--target=0.13.0-rc1"
node-pre-gyp ERR! cwd /Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3
node-pre-gyp ERR! node -v v5.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.23
node-pre-gyp ERR! not ok 
Failed to execute 'nw-gyp build --runtime=node-webkit --target=0.13.0-rc1 --module=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/lib/binding/node-webkit-v0.13.0-rc1-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/WZX/Documents/Workspace/Aegean/Code47/WeciteDesktop/src/node_modules/sqlite3/lib/binding/node-webkit-v0.13.0-rc1-darwin-x64' (1)

sudo node-pre-gyp rebuild --runtime=node-webkit --target=0.13.0-rc3, i got the same errors.
but "sudo node-pre-gyp rebuild --runtime=node-webkit --target=0.12.3", it's working for me.

**Comment by rogerwang** [comment]
Please try this: https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ
