### ISSUE TITLE
NW.js 0.13.0 rc3 - Can't Set Mac OSX Bundle Name in Info.plist

### ISSUE THREAD

**Issue by jyapayne** [nwjs/nw.js#4572]
I tried setting the CFBundleName in the Info.plist to something else, but the name of the package stays at "nwjs" in Finder.

<img width="865" alt="error" src="https://cloud.githubusercontent.com/assets/2645657/13788578/ec0373b6-eaa5-11e5-8faa-925d10968b6f.png">

[Info.plist.txt](https://github.com/nwjs/nw.js/files/174523/Info.plist.txt)

**Comment by ghostoy** [comment]
@jyapayne `CFBundleName` has nothing to do with the name shown in Finder. Simply renaming the folder `nw.app` to `YouAppName.app` will do.

If you ever used `menu.createMacBuiltin()` to create a native Mac menubar, please follow the new instructions for 0.13.0 to fix the title of the menubar. See http://docs.nwjs.io/en/latest/For%20Users/Advanced/Customize%20Menubar/, search for "Fix the Title of Application Menu".

**Comment by jyapayne** [comment]
But the thing is, I did rename it. In the terminal, it's listed as Cargo.app, but in finder, it's listed as nwjs.

**Comment by ghostoy** [comment]
I see. Seems that you also need to change the value of localized `CFBundleDisplayName` in every `nwjs.app/Contents/Resources/*.lproj/InfoPlist.strings` file. Or you can remove it from `nwjs.app/Contents/Info.plist` to prevent it being localized.
