### ISSUE TITLE
Node webkit app crashing while loading Vimeo video

### ISSUE THREAD

**Issue by sujit-extentia** [nwjs/nw.js#4575]
I am working on a desktop application implemented in Node webkit. I have already integrated Vimeo Video Player (using Froogaloop) in it. Till last month, it was working fine, but since then, it has been crashing almost every time.

I checked with earlier versions of my app where it was working fine earlier, but it started crashing there as well.

I tested the basic [Vimeo Player code](https://developer.vimeo.com/player/js-api#universal-with-froogaloop) from their API. Its as follows:

**JS:**
```
$(function () {
            var iframe = $('#player1')[0];
            var player = $f(iframe);
            var status = $('.status');

            // When the player is ready, add listeners for pause, finish, and playProgress
            player.addEvent('ready', function () {
                status.text('ready');

                player.addEvent('pause', onPause);
                player.addEvent('finish', onFinish);
                player.addEvent('playProgress', onPlayProgress);
            });

            // Call the API when a button is pressed
            $('button').bind('click', function () {
                player.api($(this).text().toLowerCase());
            });

            function onPause() {
                status.text('paused');
            }

            function onFinish() {
                status.text('finished');
            }

            function onPlayProgress(data) {
                status.text(data.seconds + 's played');
            }
        });

```
**HTML:**
```
<script src="https://f.vimeocdn.com/js/froogaloop2.min.js"></script>
<iframe id="player1" src="https://player.vimeo.com/video/76979871?api=1&player_id=player1" width="630" height="354" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

    <div>
        <button>Play</button>
        <button>Pause</button>
        <p>Status: <span class="status">&hellip;</span></p>
    </div>

```
But even this is crashing when run through Node-webkit. Interestingly, above code works fine on webpage hosted through Apache (WAMP). It seems like something is changed from Vimeo front which Node webkit is unable to handle.

Can anyone please help? I have added same question on [Vimeo Forum](https://vimeo.com/forums/help/topic:281185).

Thanks.

**Comment by rogerwang** [comment]
What's the version are you using?

**Comment by sujit-extentia** [comment]
@rogerwang : I tried on nw.js v0.12.1/0_13_0, and node v5.8.0/0.12.2

**Comment by rogerwang** [comment]
Could you please upload the full sample?

**Comment by sujit-extentia** [comment]
Please find attached.





[server.js.txt](https://github.com/nwjs/nw.js/files/175595/server.js.txt)
[index.html.txt](https://github.com/nwjs/nw.js/files/175596/index.html.txt)
[package.json.txt](https://github.com/nwjs/nw.js/files/175597/package.json.txt)

**Comment by sujit-extentia** [comment]
And here is the Crash dump, but for my original project.
[9cb94c55-ce6d-428d-9b82-e34f9521b4ec.dmp.txt](https://github.com/nwjs/nw.js/files/175768/9cb94c55-ce6d-428d-9b82-e34f9521b4ec.dmp.txt)

 (Code attached in last comment is basic Vimeo player integration which still is crashing)

**Comment by rogerwang** [comment]
Which OS platform are you using? I can't reproduce the crash under linux.

**Comment by sujit-extentia** [comment]
I reproduced it on Windows 8.1 Pro and Mac Pro machine

**Comment by rogerwang** [comment]
Still cannot reproduce it under win7 x64. The player tries to play once click the play button, but stopped after a while with no crash.

Could you please upload the crash dump with windows? It's under %LOCALAPPDATA%\Crashpad 

And please use this version: http://dl.nwjs.io/live-build/03-17-2016/aedcee0-36bd43b-3d99a78-678d67e/

**Comment by sujit-extentia** [comment]
These 2 files created under "AppData\Local\Temp" folder after the last crash.
[db2c29f2-ab0f-4e4a-a83e-196b4ce6916d.dmp.txt](https://github.com/nwjs/nw.js/files/177762/db2c29f2-ab0f-4e4a-a83e-196b4ce6916d.dmp.txt)
[28e54976-5e89-4cf6-80f0-256b3cf1be2e.dmp.txt](https://github.com/nwjs/nw.js/files/177763/28e54976-5e89-4cf6-80f0-256b3cf1be2e.dmp.txt)

**Comment by rogerwang** [comment]
@sujit-extentia which exact nw version did you download and used? The crash dump file must match the nw version or it will be useless. Please use the exact nw version I referred to in the last comment.
