### ISSUE TITLE
[docs] reorder sections in navigation bar

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#4576]
The order of the left pane of docs.nwjs.io should be 
"For Users"
  "Getting Started"
  "FAQ"
  "Package ..."
  "Migration"
  "Advanced"
  ...
"References"
"For Developers"
...

**Comment by ghostoy** [comment]
@rogerwang And I would also rename some sections as proposed by @offshore:

* `For Users` => `For Developers`
* `For Developers` => `For Contributors`

The new names are more reasonable.

**Comment by rogerwang** [comment]
"For Users" should remain. And please just do the reordering for this issue. Do not bring in other refactoring.

**Comment by ghostoy** [comment]
OK.
