### ISSUE TITLE
Facebook kills nwjs-sdk-13-rc4 on Mac

### ISSUE THREAD

**Issue by cryptedco** [nwjs/nw.js#4577]
Just downloaded and played around with rc4 on Mac (download 03-16 / rc4) and went on Facebook... I log in and starts loading and then goes bye bye...

 
![screenshot 2016-03-16 09 49 11](https://cloud.githubusercontent.com/assets/326428/13806559/a79c7166-eb5c-11e5-8421-db8fccad02c4.png)

**Comment by rogerwang** [comment]
Is it a regression for you (previous version works well)?

**Comment by cryptedco** [comment]
Hi Roger - I just tried with rc3 and same thing, just goes away without even showing a blank... just crashes...
![screenshot 2016-03-16 09 59 45](https://cloud.githubusercontent.com/assets/326428/13806776/ed8aba92-eb5d-11e5-8692-310779ecdb46.png)

**Comment by cryptedco** [comment]
On Windows 10 it takes the 32bit release a bit longer (3 clicks) and then it goes bye bye on Facebook
![screenshot 2016-03-16 10 04 11](https://cloud.githubusercontent.com/assets/326428/13806880/8a2e70a0-eb5e-11e5-994a-513137daf8a8.png)

**Comment by rogerwang** [comment]
Could you upload your sample app? It works for me on win7 64bit with nw.exe --url=https://www.facebook.com

**Comment by cryptedco** [comment]
Roger, it is the plain vanilla download - no app, no changes... download, double click on the nwjs.app, open devtools, enter window.location.href="https://facebook.com" on the console... nothing more done

![screenshot 2016-03-16 10 22 04](https://cloud.githubusercontent.com/assets/326428/13807339/fecf88f2-eb60-11e5-803d-e750fe0fdae9.png)

**Comment by cryptedco** [comment]
Ok, field report: I downloaded the 64bit rc4 on Windows 10, went on facebook, logged in and scrolled down in my timeline... after about 4-5 screens, nwjs just crashes - window closes, gone... not sure, if the "debug.log" helps...
[debug.log.zip](https://github.com/nwjs/nw.js/files/175615/debug.log.zip)

**Comment by rogerwang** [comment]
Could you please send the crash dump? It's under %LOCALAPPDATA\Crashpad

Ralf Schwoebel <notifications@github.com>于2016年3月16日周三 下午5:33写道：

**Comment by krneticz** [comment]
I have experienced issue where in our win 64 nwjs rc3 based application, when we open Facebook in iframe, dev tools gets disconnected and application freezes.

**Comment by cryptedco** [comment]
Strange enough, it takes some time to kill nwjs... sometimes instantly, sometimes after you scroll down... if it is in a WebView: it takes a bit longer and does not really kill the app, but slow it down until you can not use it anymore...

**Comment by cryptedco** [comment]
And here the 2 crash dumps from Windows 10...

It is an address violation...

[reports.zip](https://github.com/nwjs/nw.js/files/175663/reports.zip)

**Comment by rogerwang** [comment]
Please try this build: http://dl.nwjs.io/live-build/03-16-2016/aedcee0-36bd43b-3d99a78-678d67e

**Comment by cryptedco** [comment]
Yes, that did it! Much faster! I scrolled, clicked, liked, changed pages for about 3 minutes like a maniac, no crash!

**Comment by krneticz** [comment]
Roger,

I can also confirm that  Facebook in iframe in our app does not freeze app anymore with http://dl.nwjs.io/live-build/03-16-2016/aedcee0-36bd43b-3d99a78-678d67e

Thanks!

**Comment by cryptedco** [comment]
Just downloaded the mac version and clicked around... works for me, closing out...
