### ISSUE TITLE
⌘+Q does not pass true as the first argument to the event

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#4580]
http://docs.nwjs.io/en/v0.13.0-rc3/For%20Users/Migration/From%200.12%20to%200.13/#known-issues

**Comment by robaweb** [comment]
Fix: [OSX] Cmd-Q does not pass true as the first argument to the event (#4580)

//nw 0.13.0-rc4  osx
var win = nw.Window.get();
win.on('close', function (event) {
   // on cmd+q still  event == undefined
});

**Comment by rogerwang** [comment]
@robaweb it works for me. Could you please show the full sample code?

btw, does quiting from dock trigger the event handler correctly?

**Comment by robaweb** [comment]
@rogerwang full sample code
```
//building mac menu
var windowMenu = new nw.Menu({ type: 'menubar' });
window.windowMenu = windowMenu;
windowMenu.createMacBuiltin('test');
nw.Window.get().menu = windowMenu;
//end building mac menu

var win = nw.Window.get();
// Listen to main window's close event
win.on('close', function (event) {
   console.info(event); // event == undefined
   if (event == 'quit') { 
      console.log("We're closing...");
   } else {
      win.hide();
   }
});
```
Quiting from dock menu and top menu just hide main window and not close.

I figured out that event == 'quit' not working with createMacBuiltin code.  Without 'building mac menu' event == 'quit' passing correctly by Cmd+Q.

**Comment by rogerwang** [comment]
@robaweb fixed again in git and will be available in the next build.

**Comment by robaweb** [comment]
@rogerwang thank you!
