### ISSUE TITLE
Only top left corner of window icon is shown in 0.13.0-rc3

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#4581]
The icon that is specified in window section of package.json is cropped incorrectly (top left quarter is shown) on Windows 2008 R2 (have not tried on more recent versions yet):

<img width="289" alt="sample" src="https://cloud.githubusercontent.com/assets/1192686/13831313/2bfe0b1c-eba9-11e5-8545-a585edd5625f.png">

This happens on 0.13.0-rc3, the same is on the latest live build. 
The cropped area does not depend on size of original icon file.

Here is sample to reproduce:

[nwjs-issue-window-icon.zip](https://github.com/nwjs/nw.js/files/177036/nwjs-issue-window-icon.zip)

**Comment by lashanchenqi** [comment]
I encounter the same issue.

**Comment by rogerwang** [comment]
Fixed in the last nightly build: http://dl.nwjs.io/live-build/03-18-2016/f02a67c-8dd41ff-3d99a78-bef2641/
