### ISSUE TITLE
Notification settings link opens up a blank screen in a new window on 0.13.0-rc3

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#4582]
When using [Notification](https://github.com/nwjs/nw.js/wiki/Notification) api the notifications show up with a settings button (in red on the screenshot), but when you click on it a blank screen is shown.
<img width="363" alt="screenshot 2016-03-16 19 56 43" src="https://cloud.githubusercontent.com/assets/1192686/13832353/ef17b3a2-ebb1-11e5-8219-a3e7539fc38d.png">

This is how it looks on Windows:
<img width="250" alt="screenshot 2016-03-16 19 38 34" src="https://cloud.githubusercontent.com/assets/1192686/13832214/6608a748-ebb0-11e5-8b4b-49295d559912.png">

And here it is on Mac:
<img width="282" alt="screenshot 2016-03-16 19 24 59" src="https://cloud.githubusercontent.com/assets/1192686/13832215/6609aec2-ebb0-11e5-9b5a-91320cd3177b.png">

Is there any workaround / setting available to control if that link should be shown or where it leads?

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build. The settings button is removed.
