### ISSUE TITLE
console file name begin with VMxxx

### ISSUE THREAD

**Issue by lashanchenqi** [nwjs/nw.js#4583]
![1](https://cloud.githubusercontent.com/assets/17034821/13833585/3787f5a0-ec22-11e5-96cc-c91b476e9b2d.jpg)

If   js file is  at  local ,  being  accessed by file system not  by  http  ,   and imported  by  jquery : “$.getScript()”,    then ,  the console  shows js file name  as "VMxxx"  ,  that  make it difficult  to  locate codes .

Is there anyway to show the true  js filename  when  console in that situation？

**Comment by iteufel** [comment]
Add this after you have loaded jQuery.

	$._getScript = $.getScript;
	$.getScript = function (file, callback) {
  		if (file.indexOf('http') == 0) {
    		$._getScript.apply(this,arguments);
  		}else {
  			var ele = document.createElement('script');
  			ele.src = file;
  			ele.addEventListener('load',callback);
  			document.body.appendChild(ele)
  		}
  	}

**Comment by lashanchenqi** [comment]
@iteufel    It works!    Thank you!

**Comment by Christywl** [comment]
@lashanchenqi , I saw you said it works. Could we close this issue now?

**Comment by Christywl** [comment]
close until there is more information.
