### ISSUE TITLE
ffi rebuild in nwjs

### ISSUE THREAD

**Issue by waiting0729** [nwjs/nw.js#4589]
hi,all)i install node-ffi for windows,my environment is:
Python 2.7.9
node v0.10.21
Microsoft Visual Studio 2010 Express
nwjs 0.12.3-ia32

when i node-gyp rebulid ,it occurs

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platf
orm for project 'ffi.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to bui
ld a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [D
:\node-webkit\nwjs-v0.12.3-win-ia32\node-ffi\node-ffi-master\build\deps\libffi\ffi.vcxproj]

what can i do ?thanks a lot.

ps:Now ,i have a idea that rebuilding node-ffi on linux for windows.Is this possible?

**Comment by rogerwang** [comment]
Did you read my comments in the same issue you reported in #4570 ?

**Comment by waiting0729** [comment]
Thanks.I read your comments,but it does not resolve my problem.I need use v0.12.3 a long time,but thank a lot
