### ISSUE TITLE
webview events not firing in remote page

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#4590]
webview events (loadstart, loadstop, permissionrequest...) are firing when webview is embeded in main html file of the app, but are not firing at all when webview is in page that gets loaded in main window from main html file. Even that events are not firing in this case, otherwise, webview responds on all methods: reload, back, forward, setZooom etc.

I have made two simple app cases:

1. in webview_main   webview is embeded directly in main html file of the app and you can see in console webview events being loged

2. in webview_remote, webview is embeded in page that is loaded from main html file of the app using location.href. Events are not being loged in console.

[webview_remote.zip](https://github.com/nwjs/nw.js/files/178124/webview_remote.zip)

[webview_main.zip](https://github.com/nwjs/nw.js/files/178125/webview_main.zip)

**Comment by krneticz** [comment]
Update:

Events are not firing even in main html page, if that page is not local file but remote url. E.g. in webview_remote if you set  "main": "https://seeyoulink.com/webview.html" it still won't work.

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by krneticz** [comment]
Roger,

Thanks a lot, this was critical for us!

Zoran

**Comment by rogerwang** [comment]
You can try it here:
http://dl.nwjs.io/live-build/03-19-2016/e167d5d-22af72e-3d99a78-5c8f26b

Zoran Krnetic <notifications@github.com>于2016年3月19日周六 下午3:13写道：

**Comment by krneticz** [comment]
Roger,

I tested in latest live build (live-build/03-21-2016/6dad6aa-9a310ac-3d99a78-5c8f26b/v0.13.0-rc4/) and is working now.

Thanks a bunch!
