### ISSUE TITLE
[0.13-rc3] chrome.identity.launchWebAuthFlow is causing a crash?

### ISSUE THREAD

**Issue by goodhyun** [nwjs/nw.js#4591]
The following code is killing a OS X process with the error saying "nwjs[72074:5492399] NSWindow warning: adding an unknown subview: <WebContentsViewCocoa: 0x7fa706382ec0>. Break on NSLog to debug.", "nwjs[72074:5492399] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Item to be removed is not in the menu in the first place'"

```
 chrome.identity.launchWebAuthFlow(
        {
            url: 'https://www.facebook.com/dialog/oauth?' +
                'client_id=' + CLIENT_ID + '&' +
                'response_type=token&access_type=online&' +
                'redirect_uri=' + encodeURIComponent(chrome.identity.getRedirectURL()) +
                '&scope=' + SCOPES,
            interactive: true
        },
        function(responseURL) {
          console.log(responseURL);         
        }
      );
```

It was okay before, but not sure what caused this symptom.

With this code, you can kill a process even from an inspect console.

**Comment by rogerwang** [comment]
Could you please upload a full sample which I can reproduce with?

**Comment by goodhyun** [comment]
You can easily replicate this crash.
First, launch any blank nwjs runtime and open an inspect window. 

Second, onto the console input some menu items like: 
```
// Load native UI library
var gui = require('nw.gui');

// Create menu
var menu = new gui.Menu({ type: 'menubar' });

// Create sub-menu
var menuItems = new gui.Menu();

menuItems.append(new gui.MenuItem({ label: 'Custom Menu Item 1' }));
menuItems.append(new gui.MenuItem({ label: 'Custom Menu Item 2' }));

// create MacBuiltin
menu.createMacBuiltin('Sample App',{
    hideEdit: true,
    hideWindow: true
});

// Append MenuItem as a Submenu
menu.append(
    new gui.MenuItem({
        label: 'Custom Menu Label',
        submenu: menuItems // menu elements from menuItems object
    })
);

// Append Menu to Window
gui.Window.get().menu = menu;
```

Third, cut and paste the launchWebAuthFlow code in the above post, with a dummy CLIENT_ID/SCOPES value.

Boom. :)

The chemistry between a menu setup code and chrome.identity seems causing this symptom.

**Comment by rogerwang** [comment]
Fix in git and will be available in the next nightly build: http://dl.nwjs.io/live-build/
