### ISSUE TITLE
menu.popup is blocking the main thread.

### ISSUE THREAD

**Issue by iteufel** [nwjs/nw.js#4593]
menu.popup is blocking the main thread.
Intervals & timeouts are not working.

Tested with: 0.13.0-rc3 & 0.13.0-rc4 on osx.

See the example app.
[Archive.zip](https://github.com/nwjs/nw.js/files/178896/Archive.zip)

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build: http://dl.nwjs.io/live-build/

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/03-19-2016/9c27ad6-9f49374-3d99a78-5c8f26b
