### ISSUE TITLE
how can i use typescript in nwjs

### ISSUE THREAD

**Issue by taoqf** [nwjs/nw.js#4594]
hi @rogerwang , i want use typescript in nwjs,but i find the path is not same as nodejs when i use require or nw.require(seems they are same). 
also, i seached docs and issues but get nothing.
can any one show me the way?
thanks.

**Comment by rogerwang** [comment]
Please post questions with details to the mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by taoqf** [comment]
@rogerwang .done. please check it. thanks
