### ISSUE TITLE
Is there any option about disable console when user press F12 on v0.13.0 rc3 SDK ver?

### ISSUE THREAD

**Issue by chunsun21** [nwjs/nw.js#4597]
How to disable console when user press F12 on v0.13.0 rc3?
Is there any javascript or manifest option?
I can't find about it from docs and wiki.

So I do call the function "return false" when user press F12.
But I want to find nice solution.

**Comment by Spiffyk** [comment]
The SDK version is for you, the developer. Your end user should get the Normal flavor (or the NaCl one if you use native client plugins) where there is no console.
