### ISSUE TITLE
Feature Request: Better Clipboard Support

### ISSUE THREAD

**Issue by lahdekorpi** [nwjs/nw.js#460]
Support getting/setting RTF, HTML and image data from/to clipboard.
Chromium has good clipboard support in ui/base/clipboard/clipboard.h and these could be implemented more extensively.

**Comment by ghostoy** [comment]
This feature is supported in NW.js [0.15.4 stable](https://nwjs.io/blog/v0.15.4/) and [0.14.7 LTS](https://nwjs.io/blog/v0.14.7/).
