### ISSUE TITLE
x64 v0.13.0 makes error on XP x64

### ISSUE THREAD

**Issue by chunsun21** [nwjs/nw.js#4600]
It returns error about 'wow64GetThreadContext'

**Comment by rogerwang** [comment]
@ghostoy I'll take this.

**Comment by chunsun21** [comment]
Okay. close this issue. they'll fix it.

**Comment by rogerwang** [comment]
Fixed in the nightly build: http://dl.nwjs.io/live-build/03-21-2016/e167d5d-9a310ac-3d99a78-5c8f26b
