### ISSUE TITLE
inject-js-end and inject-js-start renamed, documentation needs update

### ISSUE THREAD

**Issue by ewot** [nwjs/nw.js#4603]
The manifest properties inject-js-start and inject-js-end seems to have been ninja-renamed without the documentation being updated.  

They are now called **inject_js_start** and **inject_js_end** (with underscores).

Documentation needs to be updated.

**Comment by ewot** [comment]
Invalid, I was browsing the wrong version of the documentation.

**Comment by angufix** [comment]
its stil with the dashes on https://github.com/nwjs/nw.js/wiki/manifest-format
version nwjs-sdk-v0.14.2-win-x64  works with underscores
