### ISSUE TITLE
nw.Shell.openItem(""); doesn't do anything

### ISSUE THREAD

**Issue by klukule** [nwjs/nw.js#4605]
I'm currently in process of porting kOverlay (little program which i have made) and i'm trying to execute command/start application using nw.Shell.openItem("");
example:

```
nw.Shell.openItem("E:\WOW\Wow-64.exe");
nw.Shell.openItem("cmd");

```

it does literally nothing, i'm currently using nwjs-sdk-v0.13.0-rc3-win-ia32 and i have Windows 10 Pro x64, i'm using 32bit version for compatibility.

the same code snippet (except gui changed to nw) does work in version 0.12

```
 function ExecCommand(data){
   console.log("Executing " + data[0]);
   nw.Shell.openItem(data[2]);
   if(Data.settings.closeafterlaunch){
     HideWindow();
   }else{
     ShowMessageLaunching(data);
   }
 }
```

Is mistake between keyboard and chair or somewhere else? Thank you for your help in advance.

**Comment by MrVoltz** [comment]
You can try using child_process to open stuff, that will work 100% of the time.

**Comment by klukule** [comment]
@MrVoltz Thanks, but as i tested it more in-depth it looks like i forgot double backslashes, and both child_process and nw.Shell.openItem cant open CMD :) so it is combination of bad choices and insufficient testing

but it is interesting that worked in 0.12 :)

but as i said thanks for your help, i'l stick with child_process for now

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.22.0. It could open `cmd `application.
`nw.Shell.openItem("C:\\Windows\\System32\\cmd.exe");`

**Comment by klukule** [comment]
I'm not sure but i think it is already fixed, because it's more that year since i posted this, if i dig my old code somewhere I'l take i look... and this was tested using nwjs 0.13 at the time

**Comment by klukule** [comment]
After testing using newest SDK i can confirm that this works.
Closing the issue
