### ISSUE TITLE
capturePage not working on child window nwjs13 on WIndows 8/10 and captures only JPEG

### ISSUE THREAD

**Issue by nafem** [nwjs/nw.js#4609]
capturePage only fires callback if called on the current window. If a child window is launched, capturePage never fires the callback so capture is never completed.

Also even if the capturePage format is set to PNG, the format is always JPEG:

```
        win.capturePage(function(img) {
            var mimeString = img.split(',')[0].split(':')[1].split(';')[0];
             console.log(mimeString); //always returns JPEG
        }, {
            format: 'png',
            datatype: 'datauri'
        });
```

**Comment by rogerwang** [comment]
I just fixed the PNG issue. Could you please elaborate on the child window issue? We have a test case using capturePage and launching another window and it's working well: https://github.com/nwjs/nw.js/tree/nw13/test/remoting/capture_page

**Comment by nafem** [comment]
Thanks Roger.

I can't post code right now, but can do as little later if it helps. Your example captures the current window and populates a pop-up with the result.

The issue I am seeing is if you open a child window, then from the parent attempt to capturePage of the child window, it never completes, and does not throw an error.

**Comment by nafem** [comment]
Further to my comment earlier, I think the issue with capturePage on a child window is now fixed in rc4. I have not tested fully but first test with rc4 seems good.

I'll confirm when fully tested

**Comment by rogerwang** [comment]
Please reopen if you see it again.
