### ISSUE TITLE
Crash on confirm()

### ISSUE THREAD

**Issue by bruspal** [nwjs/nw.js#4612]
Hi there.

I'm using nw to encapsulate an old existing Web app. This app still using some confirm() call.

Today I switched to nw 0.13 rc4 unfortunately it didn't work anymore because anytime I call confirm() it crash silently.

I switched back to rc1 and it's ok. I plan to migrate to 'real' nw app in the futur. But I don't have time for now.

Thanks

**Comment by bruspal** [comment]
I forgot to say I'm running nwjs on windows 10. But this still occur on w7 and w8.1

**Comment by rogerwang** [comment]
It works for me. Please see the screenshot:

![confirm](https://cloud.githubusercontent.com/assets/165401/13935799/44b441d6-eff4-11e5-8fe2-158e82c50e9a.png)

**Comment by bruspal** [comment]
Hello,

In local context and in fresh remote page without any library it doesn't crash. However still crashing this the app, which is using numerous JS library.
I'm going to make further investigation. And let you know as soon as possible.

Thanks

**Comment by rogerwang** [comment]
You can send the crash dump file, which should be helpful: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by rogerwang** [comment]
Please reopen if you have more information.

**Comment by bruspal** [comment]
Hi,

Sorry, I was a bit busy last two weeks so I didn't have time to answert.

The app still crashing. But I have now more details.

```
Dump Summary
------------
Dump File:	f5aeb8ee-f123-4224-9496-82d43edbfb4e.dmp : C:\Users\INFORMATIQUE_1\AppData\Local\Crashpad\reports\f5aeb8ee-f123-4224-9496-82d43edbfb4e.dmp
Last Write Time:	06/04/2016 16:25:45
Process Name:	nw.exe : C:\nwdump\nw.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.10586
CLR Version(s):
```	

I'am using very classical JS lib : 
* jquery : 2.2.3 (I tried also with 1.9.x)
* jQueri-ui
* jQmodal 1.4.0
* ckEditor 4
* codemirror 5.9.0

I'm going to go further in testing and try to find an alternative. I attach the dump file to this message.

Best regards.

[nw-dump.zip](https://github.com/nwjs/nw.js/files/206500/nw-dump.zip)
