### ISSUE TITLE
App freezes after random period of time

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#4613]
This started happening after upgrade to 0.13.0-rc4, so far observed multiple times on different boxes running an app on Mac OS X El Capitan (Version 10.11.3) under normal and sdk builds.

After some period of time (10-40 minutes) the app suddenly stops responding to user input (mouse, keyboard), rendered html page does not change size / layout during resize of the window frame. 
Dev Tools are responsive, but don't report any new activity (network, console log). 
On attempt to pause javascript the button to pause becomes grey, but it does not go into javascript debug mode as it typically would at any other time.
The only way to exit the app after that is to force quit / kill it (that might be because we have javascript listener for app / window events and it does not look like any javascript can be executed in this state).

So far it's not clear if it's related to use of network, blobs, buffers, notifications or anything else specifically, no specific steps to reproduce.
It would be great to get some hint on how to troubleshoot it.

We saw somewhat similar behavior on 0.13.0-rc3, but only when using network throttling in the dev tools to cause request timeouts (request timeouts that were happening during regular use of the app did not cause any issues).

**Comment by rogerwang** [comment]
Did it happen everytime after the launch? And could you please send it to me so I can reproduce it here? Thanks.

**Comment by arudnev** [comment]
It looks like it depends on data / sequence of events. 
Unfortunately, I can not easily share data / environment setup on which it can be reproduced.
I'm trying to isolate it and create a sample on which it can be reproduced repeatedly.
So far I was able to get it to the state where it gets frozen in less than 5 minutes after making several attempts to execute https requests that timeout, all using network throttling profile in the dev tools and angular $http service, but there are still plenty of other moving parts that I'm trying to eliminate.
I hope that simple loop that calls XMLHttpRequest on some public data will be enough to reproduce, if so you should expect the sample code shortly.
Regards.

**Comment by arudnev** [comment]
I'm giving up on this one. After my last message yesterday I was able to reproduce it about ten more times within couple of hours going though somewhat similar flow of actions, created sample project that does very similar thing, failed to reproduce the freeze on that sample code, got back to the original code / data / environment, spent the whole day today trying to reproduce it again there, but no luck.
Since app code did not change, the only thing that I can think of is that it was something environmental, some kind of leftover from previous installs, tests, crashes, etc. I probably did some brew update / upgrade, npm install or ran some cleanup code that dropped all IndexedDB databases and cleared the file system in the data path, maybe killed some processes, and some of that fixed it.
Either way, since we only observed this freeze once on another install / box and I can no longer reproduce it I'm going to close this issue.
Thanks for the prompt reply.

**Comment by rogerwang** [comment]
Maybe something like a trace log would be helpful if this kind of thing happen again. Currently we have '--v=1' if logging is turned on, but I'm not sure that's good enough.

**Comment by arudnev** [comment]
I experienced couple of more freezes since my last message, so I guess the issue is not gone.

I have not turned the trace on yet, might need to ask for more details on that. In the last run (on the live build from yesterday) I had this as the last entry (after just couple of others that I normally see there after app starts) in the log output:

Mar 24 14:32:39  nwjs Helper[76040] <Error>: CGAffineTransformInvert: singular matrix.

It happened about 10 minutes after app started, not sure if it's related at all.

Will try to turn some trace on and collect more info. Can I somehow force crash / dump stack trace or something like that on the frozen app to provide more info?

**Comment by snehapshinde** [comment]
I am facing same issue. I am using 0.14.5 mac version. I am able to reproduce the freeze randomly. 
Added --v=1 parameter to command that executes the application, where can we find the logs?

**Comment by snehapshinde** [comment]
@arudnev did you get any work around for this?

**Comment by arudnev** [comment]
I'm still facing it a few times a day during debugging when on sdk build, but I don't see it when app is built with normal distro.

**Comment by snehapshinde** [comment]
Hi Roger, 
I am also facing this issue. However, I was able to produce sample app where the app freezes on print operations. For which, I have already opened: https://github.com/nwjs/nw.js/issues/5020
Could you please confirm if the two issues are inter-related?
Do you need any specific inputs for this ticket(4613)?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by arudnev** [comment]
I have not seen this issue in 0.23+ builds and don't remember seeing it several releases before that, but not sure when it got fixed.

**Comment by Christywl** [comment]
Thanks for your reply, close this now.

**Comment by Christywl** [comment]
@asadpakistani , could you please provide a sample to reproduce this?

**Comment by asadpakistani** [comment]
It stops working over some period of time. I am using the frameless window.

**Comment by asadpakistani** [comment]
I narrowed down the issue to a window.close() call even though I catch the close event and minimize the window.

Changing that to a direct nw minimize resolved the issue, however doing an alt+f4 and catching that close event and minimizing does not cause the same problem.
