### ISSUE TITLE
Performance degradation in constructing typed array from node buffer

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#4614]
It seems that constructing Uint8Array from Buffer is much slower in nw13 than it was in nw12, tens of times slower than simply copying it byte by byte in pure javascript.

I would expect that nativeCopy would work at least as fast as jsCopy in the following example:

```javascript
const bufferSize = 4 * 1024;

function someBuffer() {
  return new Buffer(bufferSize).fill('.');
}

function nativeCopy(buffer) {
  return new Uint8Array(buffer).buffer;
}

function jsCopy(buffer) {
  var ab = new ArrayBuffer(buffer.length);
  var view = new Uint8Array(ab);
  var i = buffer.length;
  while(i--) {
    view[i] = buffer[i];
  }
  return ab;
}

var runs = 3;
var iterations = 1000;
var nativeTime = 0;
var jsTime = 0;
for (var r = 1; r <= runs; r++) {
  var t0 = performance.now();
  for (var i = 0; i < iterations; i++) {
      nativeCopy(someBuffer());
  }
  var t1 = performance.now();
  nativeTime += (t1 - t0);

  var t2 = performance.now();
  for (var i = 0; i < iterations; i++) {
      jsCopy(someBuffer());
  }
  var t3 = performance.now();
  jsTime += (t3 - t2);
  
  console.log('#' + r  + ' native = ' + (t1 - t0).toFixed(2) + ' ms, js = ' + (t3 - t2).toFixed(2) + ' ms');
}
console.log('total: native = ' + nativeTime.toFixed(2) + ' ms, js = ' + jsTime.toFixed(2) + ' ms');
```

It was actually the case in nw12:

<img width="301" alt="screenshot 2016-03-22 22 00 00" src="https://cloud.githubusercontent.com/assets/1192686/13973683/d37f1508-f07b-11e5-8111-ae81ede3d1af.png">

But in nw13 it's 20+ times slower than implementation in pure javascript: 

<img width="299" alt="screenshot 2016-03-22 22 04 38" src="https://cloud.githubusercontent.com/assets/1192686/13973684/d37f29b2-f07b-11e5-83e5-0ad304f995f8.png">

Not sure if there a good reason for that and what else is affected, but just in case here is a small sample to reproduce:

[nwjs-issue-slow-buffer-copy.zip](https://github.com/nwjs/nw.js/files/185304/nwjs-issue-slow-buffer-copy.zip)

**Comment by rogerwang** [comment]
Thanks for reporting. I can reproduce it. Will fix it soon.

**Comment by rogerwang** [comment]
Please try the last night build for a workaround: http://dl.nwjs.io/live-build/03-24-2016/77fdcb9-c4d99d5-ee43248-5c8f26b/v0.13.1-pre/

The root cause is that new V8 is using an optimization trick where the passed buffer from another context is treated as an Iterable array: https://github.com/v8/v8/blob/4.9.388/src/js/typedarray.js#L254  (iteratorFn === ArrayValues is false when buffer is from another Context). So --mixed-context has been working well.

The workaround fixed this issue in non-mixed-context case.

**Comment by rogerwang** [comment]
CC #3107

**Comment by arudnev** [comment]
Wow, great improvement, almost 80 times, native being 4 times faster than pure javascript now and everything else seems to be fully functional.

<img width="299" alt="screenshot 2016-03-24 14 01 26" src="https://cloud.githubusercontent.com/assets/1192686/14026448/4e15b210-f1c9-11e5-8cb4-15aa5d98fa6f.png">

Thank you!

**Comment by rogerwang** [comment]
Reported v8 issue here: https://bugs.chromium.org/p/v8/issues/detail?id=4857
Please star it.
