### ISSUE TITLE
nw crash report，can anyone help me analyse it?

### ISSUE THREAD

**Issue by silentrain** [nwjs/nw.js#4615]
system: windows 7  32bit.
nw version: 0.12.3

Hi,I start nw app and hours later,It crash silently.The attachment is the crash log,can anyone help find some reason?   thx.
[dmp.txt](https://github.com/nwjs/nw.js/files/185309/localdmp.txt)

stack info:
----------------------------------------------------------
Thread 0 (crashed)
 0  Demo.exe!_purecall [purevirt.c : 58 + 0x0]
 1  Demo.exe!extensions::PermissionsData::CanExecuteScriptEverywhere(extensions::Extension const *) [permissions_data.cc : 57 + 0xc]
 2  Demo.exe!extensions::`anonymous namespace'::ParseHelper(extensions::Extension *,char const *,extensions::APIPermissionSet *,extensions::URLPatternSet *,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > *) [permissions_parser.cc : 165 + 0xc]
 3  Demo.exe!extensions::PermissionsParser::Parse(extensions::Extension *,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > *) [permissions_parser.cc : 252 + 0xf]
 4  Demo.exe!extensions::Extension::InitFromValue(int,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > *) [extension.cc : 528 + 0x5]
 5  Demo.exe!extensions::Extension::Create(base::FilePath const &,extensions::Manifest::Location,base::DictionaryValue const &,int,std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,std::basic_string<char,std::char_traits<char>,std::allocator<char> > *) [extension.cc : 129 + 0xe]
 6  Demo.exe!extensions::Extension::Create(base::FilePath const &,extensions::Manifest::Location,base::DictionaryValue const &,int,std::basic_string<char,std::char_traits<char>,std::allocator<char> > *) [extension.cc : 99 + 0x23]
 7  Demo.exe!extensions::ShellExtensionSystem::LoadInternalApp() [shell_extension_system.cc : 81 + 0x1c]
 8  Demo.exe!content::ShellBrowserMainParts::Init() [shell_browser_main_parts.cc : 269 + 0x7]
 9  Demo.exe!content::ShellBrowserMainParts::PreMainMessageLoopRun() [shell_browser_main_parts.cc : 148 + 0x5]
10  Demo.exe!content::BrowserMainLoop::PreMainMessageLoopRun() [browser_main_loop.cc : 770 + 0x8]
11  Demo.exe!content::StartupTaskRunner::RunAllTasksNow() [startup_task_runner.cc : 45 + 0x8]
12  Demo.exe!content::BrowserMainLoop::CreateStartupTasks() [browser_main_loop.cc : 668 + 0x8] 
13  Demo.exe!content::BrowserMainRunnerImpl::Initialize(content::MainFunctionParams const &) [browser_main_runner.cc : 188 + 0x8]
14  Demo.exe!content::BrowserMain(content::MainFunctionParams const &) [browser_main.cc : 22 + 0x8] 
15  Demo.exe!content::RunNamedProcessTypeMain(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,content::MainFunctionParams const &,content::ContentMainDelegate *) [content_main_runner.cc : 423 + 0xd] 
16  Demo.exe!content::ContentMainRunnerImpl::Run() [content_main_runner.cc : 800 + 0x6] 
17  Demo.exe!content::ContentMain(content::ContentMainParams const &) [content_main.cc : 19 + 0x7]
18  Demo.exe!wWinMain [shell_main.cc : 95 + 0x9]
19  Demo.exe!__tmainCRTStartup [crt0.c : 251 + 0xe]
20  kernel32.dll + 0x1919f
21  ntdll.dll + 0x5ad5f
22  ntdll.dll + 0x5ad2a

**Comment by rogerwang** [comment]
Please try with latest 0.13 and see http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by uppuluriaditya** [comment]
May i know what is the root cause of the issue? and what is being fixed in 0.13
