### ISSUE TITLE
pdf.js can't render fonts from v0.13.0-alpha4 to v0.13.0-alpha5 and above

### ISSUE THREAD

**Issue by neves** [nwjs/nw.js#4618]
Sample package.json
```javascript
{
  "name": "pdfjs",
  "main": "https://mozilla.github.io/pdf.js/web/viewer.html"
}
```

Same problem was reported here:
[https://github.com/rhysd/NyaoVim/issues/3](https://github.com/rhysd/NyaoVim/issues/3)

Console logs the follow error message:
[60314:1295:0323/104513:ERROR:gles2_cmd_decoder.cc(6874)] [.Offscreen-MainThread-0x7fe8cad97ca0]**GL ERROR :GL_INVALID_OPERATION : glUseProgram: program not linked**

OSX 10.11.3

Works till this version: (chromium 45.x)
http://dl.nwjs.io/v0.13.0-alpha4/nwjs-sdk-v0.13.0-alpha4-osx-x64.zip
![captura de tela 2016-03-23 as 10 46 31](https://cloud.githubusercontent.com/assets/881/13987204/3741dc7e-f0e5-11e5-9fd3-1b0bbd2446b0.png)

Stop working here, till v0.13.0 final release:  (chromium >= 46.x)
http://dl.nwjs.io/v0.13.0-alpha4/nwjs-sdk-v0.13.0-alpha5-osx-x64.zip
![captura de tela 2016-03-23 as 10 43 34](https://cloud.githubusercontent.com/assets/881/13987215/44a25470-f0e5-11e5-8cd1-381795f5b430.png)

**Comment by rogerwang** [comment]
@ghostoy I can't reproduce this on my Mac, can you?

**Comment by ghostoy** [comment]
Not able to reproduce.

**Comment by rogerwang** [comment]
@neves what's your hardware configuration including GPU model?

**Comment by neves** [comment]
@rogerwang 
MacBook Air (13-inch, Mid 2011)
1,7 GHz Intel Core i5
Intel HD Graphics 3000 384 MB
Is there anything I can help you with?

**Comment by neves** [comment]
Problem persists on v0.13.2 :sob:

**Comment by rogerwang** [comment]
it looks like related to hardware, we'll find a OSX with Intel gfx card to reproduce it.

**Comment by rogerwang** [comment]
@neves could you check the url with Chrome 49 in the same system then post the results of the page 'chrome://gpu' and the command line arguments of the Chrome process (`ps aux | grep -i chrome`); And do the same again for NW. Thanks.

**Comment by neves** [comment]
The only difference I spotted was NWJS has **--no-sandbox** 

### NWJS 0.13.2 (left) vs Chrome 49 (no difference)
![captura de tela 2016-03-31 as 23 23 18](https://cloud.githubusercontent.com/assets/881/14196150/c269c34e-f797-11e5-9940-ba2fa25715c4.png)

#### Chrome GPU
![chrome---gpu 1](https://cloud.githubusercontent.com/assets/881/14196149/c269141c-f797-11e5-8bb2-94be33f0e1cb.png)

#### NWJS GPU
![nwjs2](https://cloud.githubusercontent.com/assets/881/14196151/c26a3a7c-f797-11e5-8b44-49dc1bbdd6b9.png)

**Comment by rogerwang** [comment]
Can't reproduce this on a MBP with Intel HD 4000 ...
NW should be the same with Chromium on this. We should find what's the difference with Chromium.

**Comment by ghostoy** [comment]
@neves Did you check if the PDF works with Chromium 49 on your platform?

**Comment by neves** [comment]
Working fine with chromium

**Comment by rogerwang** [comment]
Does 0.14 RC version work for you?

**Comment by neves** [comment]
@rogerwang 0.14 works!
I see it's using Chrome 50, could that be it?

**Comment by rogerwang** [comment]
It should be the reason.
