### ISSUE TITLE
Print not working

### ISSUE THREAD

**Issue by andoitz** [nwjs/nw.js#4619]
![printnotworking](https://cloud.githubusercontent.com/assets/4107191/13995463/3f5ec8cc-f121-11e5-8b77-a52fa0a2d86e.png)

This is what happend when I click on print.

* I have my laptop with pdfPrinter as default printer.

**Comment by rogerwang** [comment]
I can't reproduce this. Could you please provide sample and steps to reproduce it?

**Comment by Blatman** [comment]
@andoitz    I had exactly this on a project using 0.13.1 on OSX 10.11.4 and it turned out to be the package.json - the webkit plugin parameter needs to be true for the pdf viewer plugin to work.
With the problem projects I had the plugin for webkit was set to false.
Hope this helps ...

**Comment by andoitz** [comment]
I'll try what you said hehe, Thanks!

**Comment by rogerwang** [comment]
Close unless there is more information.
