### ISSUE TITLE
Light problems nwjs and threejs 

### ISSUE THREAD

**Issue by gearpichon** [nwjs/nw.js#4620]
I'm having problems with the lighting in my proyect, I'm just using normal direct light but the problem is that with the 0.12.3 version of nwjs the objects in the scene are black (like if there was no lights) and sometimes the start  flickering in red, black and green.
 If I change the libEGL.dll and libGLESv2.dll with the ones in the 0.13.0 version of nwjs it works fine but only in some hardware... I don't know whtas going on, what can I do to make everything work just fine?
Thanks

**Comment by rogerwang** [comment]
Please use the latest 0.13 version, not mixing files. Thanks.
