### ISSUE TITLE
Notification undefined in node module

### ISSUE THREAD

**Issue by loretoparisi** [nwjs/nw.js#4621]
I have created a node module in the root folder:
- root
  - app.js
  - index.html
  - package.json
  - node_modules/
    - nwapp/
      - package.json
      -  lib/
        - nwapp.js

The `nwapp`  module is called by a javascript file that is loaded by the main html file like:

``` javascript
(function(){
  var path = require('path');
  var NWApp = require('nwapp');
  var app;
  app = new NWApp();
```

While the module entry point `nwapp.js` requires the `nw.gui` in this way:

``` javascript
(function() {
var gui = window.require('nw.gui');
//...
```

The app loads and run using `nw.gui`. At this point a notification is fired in the `app.js` file:

``` javascript
app.showNotification(window.document,"icon", "Hello.","World");
```

that will call the module function

``` javascript
   NodeWebKitApp.prototype.showNotification = function (document, icon, title, body, hide) {
      if (icon && icon.match(/^\./)) {
        icon = icon.replace('.', 'file://' + process.cwd());
      }
      var notification = new gui.Notification(title, {icon: icon, body: body});
      //...
```

The `Notification` seems to be undefined here.

**Comment by rogerwang** [comment]
What the version are you using?

**Comment by loretoparisi** [comment]
@rogerwang version is `nwjs-macappstore-v0.12.3-osx-x64`.

**Comment by Christywl** [comment]
@loretoparisi , is this issue still reproduce on your test with the latest nwjs? If yes, could you please upload your full tests for me to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
