### ISSUE TITLE
Chromedriver is absent for all 0.13 betas, rc and release versions

### ISSUE THREAD

**Issue by artzhuchka** [nwjs/nw.js#4623]
I couldn't find chromedriver for all 0.13 betas, RCs and release versions. Now I'm using chromedriver from latest 0.13-alpha version.

**Comment by rogerwang** [comment]
Thanks for report. It's in the SDK build now.

**Comment by artzhuchka** [comment]
Thanks, you are right. Maybe would be better to add a couple of words about it to 0.12 -> 0.13 migration guide?
