### ISSUE TITLE
devtools not open and package.json note-remote lead to crash

### ISSUE THREAD

**Issue by fifsky** [nwjs/nw.js#4624]
os x 10.11.3

⌘+⌥+i (Mac)  invalid 

in code call

```
nw.Window.get()  
```

Open a blank page 
# note-remote lead to crash log

> 3/24/16 17:14:20.339 nwjs[62670]: Call stack:
> (
>   0   AppKit                              0x00007fff947964ef -[NSThemeFrame addSubview:] + 107
>   1   nwjs Framework                      0x0000000109fb242d _ZN2v88UnlockerD1Ev + 20555245
>   2   nwjs Framework                      0x0000000109fb1c50 _ZN2v88UnlockerD1Ev + 20553232
>   3   nwjs Framework                      0x0000000109fb0d9a _ZN2v88UnlockerD1Ev + 20549466
>   4   nwjs Framework                      0x000000010aa83199 _ZN2v88UnlockerD1Ev + 31896409
>   5   nwjs Framework                      0x000000010a9cf931 _ZN2v88UnlockerD1Ev + 31161073
>   6   nwjs Framework                      0x000000010aaa0c01 _ZN2v88UnlockerD1Ev + 32017857
>   7   nwjs Framework                      0x000000010aaa2a89 _ZN2v88UnlockerD1Ev + 32025673
>   8   nwjs Framework                      0x000000010aaa2caf _ZN2v88UnlockerD1Ev + 32026223
>   9   nwjs Framework                      0x000000010aabbd22 _ZN2v88UnlockerD1Ev + 32128738
>   10  nwjs Framework                      0x000000010acac23f _ZN2v88UnlockerD1Ev + 34161663
>   11  nwjs Framework                      0x000000010a60cee8 _ZN2v88UnlockerD1Ev + 27218088
>   12  nwjs Framework                      0x000000010a3ed3ef _ZN2v88UnlockerD1Ev + 24991151
>   13  nwjs Framework                      0x000000010a533b79 _ZN2v88UnlockerD1Ev + 26328377
>   14  nwjs Framework                      0x0000000107edc058 ChromeMain + 15747912
>   15  nwjs Framework                      0x00000001074b7ada ChromeMain + 5113290
>   16  nwjs Framework                      0x00000001074d9fb9 ChromeMain + 5253801
>   17  nwjs Framework                      0x00000001074da4f8 ChromeMain + 5255144
>   18  nwjs Framework                      0x00000001074ac831 ChromeMain + 5067553
>   19  nwjs Framework                      0x00000001074d04aa ChromeMain + 5214106
>   20  nwjs Framework                      0x00000001074ac234 ChromeMain + 5066020
>   21  CoreFoundation                      0x00007fff8f3b95c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
>   22  CoreFoundation                      0x00007fff8f3ab41c __CFRunLoopDoSources0 + 556
>   23  CoreFoundation                      0x00007fff8f3aa93f __CFRunLoopRun + 927
>   24  CoreFoundation                      0x00007fff8f3aa338 CFRunLoopRunSpecific + 296
>   25  HIToolbox                           0x00007fff82f0d935 RunCurrentEventLoopInMode + 235
>   26  HIToolbox                           0x00007fff82f0d76f ReceiveNextEventCommon + 432
>   27  HIToolbox                           0x00007fff82f0d5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
>   28  AppKit                              0x00007fff947e10ee _DPSNextEvent + 1067
>   29  AppKit                              0x00007fff94bad943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
>   30  AppKit                              0x00007fff947d6fc8 -[NSApplication run] + 682
>   31  nwjs Framework                      0x00000001074ad02f ChromeMain + 5069599
>   32  nwjs Framework                      0x00000001074ac684 ChromeMain + 5067124
>   33  nwjs Framework                      0x00000001074ed523 ChromeMain + 5333011
>   34  nwjs Framework                      0x000000010706b5d5 ChromeMain + 606405
>   35  nwjs Framework                      0x000000010a33b447 _ZN2v88UnlockerD1Ev + 24262151
>   36  nwjs Framework                      0x000000010a33dbb2 _ZN2v88UnlockerD1Ev + 24272242
>   37  nwjs Framework                      0x000000010a3372bd _ZN2v88UnlockerD1Ev + 24245373
>   38  nwjs Framework                      0x000000010746c6a8 ChromeMain + 4805016
>   39  nwjs Framework                      0x000000010746bb26 ChromeMain + 4802070
>   40  nwjs Framework                      0x0000000106fd7552 ChromeMain + 66
>   41  nwjs                                0x0000000106d6fd52 main + 530
>   42  nwjs                                0x0000000106d6fb34 nwjs + 2868
>   43  ???                                 0x0000000000000002 0x0 + 2
> )
> 3/24/16 17:14:57.000 kernel[0]: nwjs[62682] triggered unnest of range 0x7fff8f200000->0x7fff8f400000 of DYLD shared region in VM map 0xe446c1836653e0c3. While not abnormal for debuggers, this increases system memory footprint until the target exits.
> 3/24/16 17:14:57.000 kernel[0]: nwjs Helper[62685] triggered unnest of range 0x7fff8f200000->0x7fff8f400000 of DYLD shared region in VM map 0xe446c1835c9e9c6b. While not abnormal for debuggers, this increases system memory footprint until the target exits.
> 3/24/16 17:14:57.000 kernel[0]: nwjs Helper[62686] triggered unnest of range 0x7fff8f200000->0x7fff8f400000 of DYLD shared region in VM map 0xe446c18364e28a7b. While not abnormal for debuggers, this increases system memory footprint until the target exits.
> 3/24/16 17:14:58.481 nwjs[62682]: NSWindow warning: adding an unknown subview: <WebContentsViewCocoa: 0x7fdc714b2980>. Break on NSLog to debug.

**Comment by rogerwang** [comment]
Could you please provide a sample? I'm not sure how to reproduce it.

**Comment by fifsky** [comment]
http://vscdn.b0.upaiyun.com/s/pay/nwjs-v0.13.0-osx-x64-debug.zip

Please download the sample,There are four different test,Double click on the nwjs to view detail

**Comment by Christywl** [comment]
@fifsky , is this issue still reproduced in your test? If yes, could you please upload your sample again for us to reproduce it? The above link is invalid.

**Comment by fifsky** [comment]
@Christywl  Thank, I've given up upgrade
