### ISSUE TITLE
How to keep the ratio of width to height when resizing the window

### ISSUE THREAD

**Issue by ToyYang** [nwjs/nw.js#4625]
* State which version  :   0.12.4
* State which OS version   :   Win 10

I tried to use resizeTo to keep ratio in the 'on resize' listener.
https://github.com/nwjs/nw.js/wiki/Window
However, It's not smooth in this way.

May anyone help me? Thx

**Comment by rogerwang** [comment]
We've never released 0.12.4. close as invalid.

**Comment by ToyYang** [comment]
@rogerwang  Sorry for the wrong release version.

The version is 0.12.3.

Do you know something about the ratio of window when resizing?
