### ISSUE TITLE
nwjs 0.13 - MacOS 10.10.5 - crash after some reload

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4626]
Today I've got many crash just reloading my app with this report:

```
<--- Last few GCs --->

25473739 ms: Mark-sweep 1228,6 (1434,3) -> 1226,6 (1434,3) MB, 2231,5 / 14 ms [allocation failure] [GC in old space requested].
25475979 ms: Mark-sweep 1226,6 (1434,3) -> 1224,0 (1434,3) MB, 2239,3 / 26 ms [last resort gc].
25477959 ms: Mark-sweep 1224,0 (1434,3) -> 1223,8 (1434,3) MB, 1980,7 / 25 ms [last resort gc].
25479921 ms: Mark-sweep 1223,8 (1434,3) -> 1223,7 (1434,3) MB, 1961,7 / 26 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x35b153608249 <String[8]: nw-token>
    1: getStyle [https://*************************my-app.js:36410] [pc=0x2fbd7404ad7f] (this=0x336cf3320071 <a constructor with map 0x625164c48a9>,property=0x3454d43fb1b9 <JS Array[4]>,inline=0x167a4c504189 <undefined>)
    2: arguments adaptor frame: 1->2
    3: getStyles [https://....project...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Received signal 6
 [0x0001073eda3a]
 [0x7fff8ad6af1a]
 [0x7fff58d55d70]
 [0x7fff8fce59ab]
 [0x0001121990ca]
 [0x00010867b6e0]
 [0x0001089037f8]
 [0x000108b30880]
 [0x000108b302f2]
 [0x0001089e409d]
 [0x0001089e0eee]
 [0x0001089e0c79]
 [0x000108a00169]
 [0x0001089c524f]
 [0x000108989c6f]
 [0x00010898a88d]
 [0x00010898a33a]
 [0x00010898c2ad]
 [0x00010898e6ae]
 [0x2fbd6b10c1fb]
 [0x2fbd7404ad7f]
[end of stack trace]
```

The moment before the crash the app was using more than 1.3Gb of RAM

**Comment by rogerwang** [comment]
It's crashed because of out-of-memory. Is there any memory leak in your app?

**Comment by AndryBray** [comment]
Hi @rogerwang 
I see there is unexpected memory grow every time I reload my app for dev purposes.
Example:
(Action / RAM)
Start my app / 300M
use it.. / 400M
Reload (from console) / 450M
Reload again  / 500M
Reload... / 600M
(and so on)
Of course after many reloads the app will reach 2/3Gb of ram

**Comment by rogerwang** [comment]
Could you please provide a sample?

**Comment by AndryBray** [comment]
It's hard to build an example as my app... did you try with a generic online website/app? 
Try to open it and reload many times from dev console. Does the RAM usage grow?

**Comment by allenm** [comment]
Maybe your app has memory leak when reload, cause by some code like this:
```
 app.on('reopen', funciton(){});
```

Remove event listener when reload window.

**Comment by AndryBray** [comment]
thank you for your tip @allenm but I don't have reopen listener on my app.

Now I see I made a system which keeps track of opened windows.. I need it because it's a multi-window app, imagine a mail window (like a dashboard) that needs to know all the opened windows, so I save inside a var "myWindowsStore" every Window instance. Do you think it could be the reason of this problem? Is there any other way to know which window is opened (like in old version of nwjs)?

**Comment by AndryBray** [comment]
Jut tried to remove the myWindowsStore mechanism... same problem

**Comment by rogerwang** [comment]
You can use the heap profiler in devtools to check what kind of JS objects are hogging the memory.

**Comment by AndryBray** [comment]
@rogerwang you can reproduce opening it with nwjs 0.14 rc2:
go to "http://examples.sencha.com/extjs/6.0.2/examples/kitchensink/#tree-two" open the console and reload the app a lot of time... you can see the ram usage will start to grow

**Comment by rogerwang** [comment]
I load the page with nw --url='....', open devtools, and run window.location.reload() many times.

Sometimes the memory consumption went up, but it also went down (should due to GC). The average memory consumption is steady.

**Comment by rogerwang** [comment]
You can try manually trigger gc by adding --js-flags='--expose-gc' and call gc() in dev console.

**Comment by AndryBray** [comment]
Are trying on MacOS 10.10.5?

**Comment by AndryBray** [comment]
I'm trying to call gc() on my app... but it does nothing, memory usage is high (only when I reload) My app is using IndexedDB intensively as well... maybe something related to this?

**Comment by AndryBray** [comment]
I found another way to reproduce (more similar to my app).
Open your nwjs and go to google / gmail, sign in with your gmail account... once loaded, reload many times.. It has just crashed with this dump
https://gist.github.com/AndryBray/75a7a160a57d899d297b270489c99480

**Comment by rogerwang** [comment]
@AndryBray I was trying from an OSX 10.10.3 system.

**Comment by AndryBray** [comment]
Any result from gmail test?

**Comment by AndryBray** [comment]
The new 0.14.2 version seems to have better memory handling. I'm reloading the same app with the same test cases and I don't use more than 600Mb for the main process (this one which was using to 2G and more). I will let you know more with next versions

**Comment by Christywl** [comment]
I can't reproduce this issue. Please try the latest nwjs build.
Mac
nwjs-sdk-v0.24.3

**Comment by Christywl** [comment]
close until there is more information.
