### ISSUE TITLE
Window size includes title bar in NW.js 0.13

### ISSUE THREAD

**Issue by geoffb** [nwjs/nw.js#4627]
NW.js 0.13.0, Windows 10

The window size specified in `package.json` now *includes* the title bar height which is a change from 0.12.3 where it *excluded* the title bar height.

For example, my game is 960x640. In 0.12.3, the width and height in `package.json` would be 960 and 640.

Now in 0.13.0, the height needs to *include* the title bar (25px or so, resulting in 960x665).

This is a problem because we don't exactly know how big the title bar will be. I assume that it'll be different on various Windows versions or skins and across OSes.

I'm wondering why this change was made and how I can get back to specifying the height of the window *excluding* the title bar in `package.json`.

Perhaps a `useContentSize` option (like [Electron has on its BrowserWindow object](http://electron.atom.io/docs/v0.37.2/api/browser-window/#class-browserwindow)) can be added if the NW.js team is set on the new behavior of width/height.

**Comment by rogerwang** [comment]
Will look to keep same behavior as 0.12 on this.

**Comment by rogerwang** [comment]
Fixed in latest nightly build.
