### ISSUE TITLE
nwsaveas is ignored when nwworkingdir is specified in nw13

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#4630]
It worked without issues in nw12, but seems to have regression in nw13 (tested on Mac and Windows).

In this case the dialog suggests filename.txt:

```html
<input type="file" nwsaveas="filename.txt" />
```

In this case it suggests Untitled:

```html
<input type="file" nwworkingdir="/tmp/" nwsaveas="filename.txt" />
```

Here is small sample to reproduce: [nwjs-issue-nwsaveas.zip](https://github.com/nwjs/nw.js/files/188962/nwjs-issue-nwsaveas.zip)

**Comment by fuwenchun** [comment]
@rogerwang I also have this problem

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.
