### ISSUE TITLE
How to keep the ratio of width to height when resizing the window

### ISSUE THREAD

**Issue by ToyYang** [nwjs/nw.js#4631]
State which version : 0.12.3
State which OS version : Win 10
I tried to use resizeTo to keep ratio in the 'on resize' listener.
https://github.com/nwjs/nw.js/wiki/Window
However, It's not smooth in this way.

May anyone help me? Thx

**Comment by rogerwang** [comment]
Please try with the latest 0.13 stable version.

**Comment by rogerwang** [comment]
Please post questions to our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
