### ISSUE TITLE
No dev tools and right click menu in v0.13

### ISSUE THREAD

**Issue by onedevteam** [nwjs/nw.js#4633]
After update to v0.13 stable, i can't access neither dev tools with F12 button, or nw menu with reload/inspect options.
Any ideas how to solve this?

**Comment by jssuttles** [comment]
npm install nw@0.13.1-sdk
The sdk includes the devtools

**Comment by frankhale** [comment]
The Release notes mention the different builds. Looks like you got the normal build that does not include the dev tools.

> There are 3 builds for each platform - normal build, sdk build and Nacl build. Normal build doesn't have devtools, only SDK build does. lt can be opened by pressing F12 (Cmd-Alt-I on OSX). SDK packages also have more development tools to be exposed in the following releases, as well as the NaCl support.

http://nwjs.io/blog/v0.13.1/

**Comment by geoffb** [comment]
Are there performance or stability improvements gained from omitting devtools from the main build?

**Comment by rogerwang** [comment]
@geoffb devtools doesn't affect performance or stability. It's stripped from normal build to provide another choice which some NW users want -- they prefer not shipping devtools with their apps.

The performance and stability of NW.js should remain the same with the Chromium browser and Node.js.
