### ISSUE TITLE
NW Caching remote files that no longer exist

### ISSUE THREAD

**Issue by griffinwebnet** [nwjs/nw.js#4634]
This seems to plague 0.11-0.13 Ubuntu 12.04 14.04 15.04 Window 7-8 and 10

My NWJS application is essentially being used as a specialized web browser with no address bar. the local index.html issues a redirect to an obscure port on my server that serves an angularjs application with a node backend. This could be a regular webapp, however were using this approach to ensure maximum compatibility (Ex: avoid issues like "oh you need to install chrome to fix this issue" etc).

The issue is it seems nwJS caches the entire application. HTML views, JS files Angular directives everything. updating files on the server doesnt updates files on the client end anymore. whatever files were accessed when they first opened the application is what they see (forever) For example we were in the beginnings of an alpha test so the ability to create your own user account was added to the login pages so we wouldnt have to add the alpha testers one by one into test companies. that funcxtion has now been removed, however even after updating the code those using the nwjs applicaiton still see the signup link, and they are still able to access the signup page and create an account despite that the angular controller for that page is gone, the angular route was removed, the html page is no longer present on the server etc (they can still add a user with the cached stuff because the user addition view uses the same node controller we previously used for the signup page). 

In fact to really test this out, i turned off apache and nodeJS and opened nodewebkit and was still shown the login page etc, i even got the errors i should becasue the node server wasnt running but alas i was shown nonexistent pages in nw.js rather than an internal server error message. how do i stop this behavior. even deleting all the nwjs files and redownloading fresh copies, regenerating the nw package from scratch and loading it up i still get this. how do i clear the cache out and stop this from ever happening in the future.

**Comment by rogerwang** [comment]
This shouldn't be an issue with 0.13. Could you please submit a sample to demonstrate this?

**Comment by griffinwebnet** [comment]
what needs to be in the sample? i dont know how i can send something like this to you considering your computer will not have an old cache copy

**Comment by griffinwebnet** [comment]
well as of this morning it seems to have cleared it self on my own computer i will have to ask around other alpha users to see if it has updated on their systems as well

**Comment by griffinwebnet** [comment]
nope issue is still there. it seems to have updated from that particular file but it is still not updating on demand as it should if i make changes, they are not reflected in nw what can is end you to help with this?

**Comment by griffinwebnet** [comment]
As far as what is in the nw app itself is nw.js 13's files:

Package.json:

`{`
`    "main": "index.html",`
`    "name": "HHW",`
`    "description": "HHW Desktop",`
`    "version": "0.0.2",`
`    "keywords": ["HH", "VSOFT"],`
`    "user-agent": "%name",`
`    "window": {`
`        "title": "HHW",`
`        "icon": "images/icon-master-round.png",`
`        "toolbar": false,`
`        "frame": true,`
`        "width": 1024,`
`        "height": 576,`
`        "position": "mouse",`
`        "min_width": 1024,`
`        "min_height": 576`
`    },`
`    "webkit": {`
`       "page-cache": false`
`    }`
`}`

Index.html:

`<!DOCTYPE HTML>`
`<html>`
`<head>`
`    <title>HHW</title>`
`    <link rel="icon" type="image/x-icon" href="images/icon-master-round.ico" />`
`    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>`
`    <script type="text/javascript">`
`        $(document).ready(function () {`
`            setTimeout(rdr, 1000)`
`            setTimeout(CS, 100)`
`            function CS() {`
`                $("body").css("background", "#d8d8d8");`
`            }`
`            function churl() {`
`                $(location).attr('href', "http://example.com:8000")`
`            }`
`            function rdr() {`
`                $("body").css("opacity", "0"); //smooth-state out animation`
`                setTimeout(churl, 500);`
`            }`
`        });`
`    </script>`
`</head>`
`<body>`
`</body>`
`</html>`

its the files at example.com:8000 that refuse to update not the internal index.html

**Comment by Christywl** [comment]
I try the sample code on Linux with nwjs-sdk-v0.24.4. I use node http-server to setup a service. Use `http://127.0.0.1:8080` to replace `http://example.com:8000`. Start the app, it shows some files and folders.
And then I delete a file. Restart the nwjs app, the deleted file still exits. So I delete the cache files in the path `/home/<your user name>/.cache/HHW`. Restart the nwjs app, the listed files update.
Please try this way, and check if it's ok for you.

**Comment by Christywl** [comment]
close until there is more information.
