### ISSUE TITLE
nwjs-v0.13.x crashes sometimes

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#4636]
I can not add javascript to index.html file (nwjs crashes sometimes):

Chromium console
Uncaught TypeError: Cannot read property 'loading' of undefined
chrome-extension://ckjhfbgmdfelgiieimnlnipfekccgk/js/myLoader.js

* State version: nwjs-v0.13.1-win-x64 (the problem with all versions: nwjs-v0.13.x)
* State OS version: Windows 10 32 bit, Windows 10 64 bit (admin)
* Crash dump file: [dump.zip](https://github.com/nwjs/nw.js/files/190465/dump.zip)

Debug.log:
[0326/125304:INFO:nw_package.cc(175)] "C:\Users\User\Desktop\Beta\13\nw.exe"
[0326/125309:ERROR:process_info.cc(608)] range at 0x7bd4369a00000000, size 0xed fully unreadable
[0326/125309:ERROR:process_info.cc(608)] range at 0x7bd436ba00000000, size 0xed fully unreadable
[0326/125309:ERROR:process_info.cc(608)] range at 0x0, size 0xed fully unreadable

**Comment by rogerwang** [comment]
This is fixed according to the crash dump. Please wait for the next nightly build and try again, and reopen if it doesn't work for you.

**Comment by rogerwang** [comment]
The build is here: http://dl.nwjs.io/live-build/03-28-2016/75b6e56-a75cea6-f039027-5c8f26b

**Comment by hooker99** [comment]
Now work like hell (0.13.x). Thanks you. 

But there is a little problem, debug.log shows an error (warning?):
[0402/150645:INFO:nw_package.cc(175)] "C:\Users\User\Desktop\Test\nwjs-sdk-v0.13.2-win-x64\nw.exe"

But the NWjs works very well nothing is happening... No crash dump file, only debug.log.

**Comment by rogerwang** [comment]
the debug.log file and the content in it is irrelevant.

Could you please submit a case so I can reproduce it?

**Comment by hooker99** [comment]
v0.14.1=> it works very well I will use this version
