### ISSUE TITLE
OSX - NWJS 0.13.1 - App will crash if CFBundleIdentifier in plist longer than 30 chrs

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#4638]
OSX 10.11.4 El Capitan
Used nwjs-v0.13.1-osx-x64 and placed app.nw folder into Resources folder of nwjs package.
Renamed app as PListBug13 
CFBundleIdentifier string edited to uk.org.wanderinghippo.123456789 - with this string the app crashed on start. If the /USER/Library/Application Support/plistbug13 folder was deleted and the plist string edited to uk.org.wanderinghippo.12345678 the app would start OK.
With v 0.12.3  the string uk.org.wanderinghippo.screenrulerapp was acceptable
With v 0.13.1 the string can't be any longer than uk.org.wanderinghippo.screenru
Problem occurs every time the length of the string in the plist file is too long.

![plistlenlim](https://cloud.githubusercontent.com/assets/11089335/14067445/b73d9808-f45c-11e5-869f-1ec897eaa778.jpg)
[plistbugfiles.zip](https://github.com/nwjs/nw.js/files/191078/plistbugfiles.zip)

**Comment by rogerwang** [comment]
fixed in git and will be available in the next nightly build.
