### ISSUE TITLE
OSX - NWJS 0.14.0-rc1 - Edit/Window menus broken

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#4640]
OSX 10.11.4 El Capitan
Using nwjs-v0.14.0-rc1-osx-x64  - Edit and Window menus appear a bit dodgy - see screenshot.
0.13.1 was OK.

![brokenmenus](https://cloud.githubusercontent.com/assets/11089335/14068235/dbe7a2d0-f474-11e5-953e-683d3960d178.jpg)

**Comment by rogerwang** [comment]
fixed in cr50 branch and will be available in the next nightly build.
