### ISSUE TITLE
Help: To intercept the authentication dialog

### ISSUE THREAD

**Issue by cityant** [nwjs/nw.js#4641]
Hi,

This is not an issue but a help. I am sorry if this is not the right place to post such. 

I don't know if there is any mechanism that authentication dialog can  be intercepted when 401 returned?
I need a customized dialog to replace the system one.

Thanks for your help in advance.

**Comment by rogerwang** [comment]
This API we support could help: https://developer.chrome.com/extensions/webRequest

**Comment by cityant** [comment]
Thanks for your help, Roger!
Another question, I have a window created by nw.gui.Window.open and in the html a chrome object is used. But after closing it by using Window.close and reopen it by the same API mentioned previously, the chrome object can't be found anymore. Could you give a clue what was happened behind?
