### ISSUE TITLE
"Inspect" Entry in Non-SDK PDF Viewer's Context Menu

### ISSUE THREAD

**Issue by rdtsc** [nwjs/nw.js#4642]
**Current Behavior**: The built-in PDF viewer in non-SDK builds contain an "Inspect" entry in the context menu. Clicking on said entry spawns an empty DevTools container window.

![nwjs-0 13-dist-pdf-inspect](https://cloud.githubusercontent.com/assets/6773893/14077069/cc3147ec-f4b5-11e5-90db-72490b7a6c6c.png)

**Expected Behavior**: Non-SDK NW.js builds should not display this entry in the context menu.

**NW.js Version**: 0.13.1 x86/x64.
**Distribution**: Normal (no DevTools).
**OS**: Confirmed on Linux and Windows. OS X untested, but likely has the same issue.

**Reproducible Via**:  `git clone https://gist.github.com/rdtsc/24cf8abc4fff32e69e47 pdf-test`

---

### package.json
```json
{
  "name": "nwjs",
  "main": "index.html"
}
```

### index.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NW.js PDF Test</title>
    <style>
      html, body, object {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        position: fixed;
      }
    </style>
  </head>
  <body>
    <!-- Base64-encoded version of the 138 byte variant from: https://stackoverflow.com/questions/17279712/what-is-the-smallest-possible-valid-pdf#answer-17280876 -->
    <object type="application/pdf" data="data:application/pdf;base64,JVBERi0xLjANCjEgMCBvYmo8PC9QYWdlcyAyIDAgUj4+ZW5kb2JqIDIgMCBvYmo8PC9LaWRzWzMgMCBSXS9Db3VudCAxPj5lbmRvYmogMyAwIG9iajw8L01lZGlhQm94WzAgMCAzIDNdPj5lbmRvYmoNCnRyYWlsZXI8PC9Sb290IDEgMCBSPj4="></object>
  </body>
</html>
```

**Comment by rogerwang** [comment]
fixed in nightly build.
