### ISSUE TITLE
Custom app icon with incorrect size under volume mixer

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#4649]
When setting a custom icon for the app in the manifest `"window":{"icon": "icon.png"}`, it will show with an incorrect size under the volume mixer. 

The following example shows the result of a simple app playing a YouTube video and the custom icon used in the manifest is [NWJS's own icon](https://github.com/nwjs/nw.js/blob/nw13/src/resources/default_100_percent/nw.png). The icon displayed in the volume mixer is too big as you can see:

![ss](https://cloud.githubusercontent.com/assets/8498057/14130153/5c0bdf38-f620-11e5-910c-ea3af02f6911.png)

Not using a custom icon in the manifest displays the default icon with the correct size.

NWJS: v0.13.2 SDK
OS: Win7x64

**Comment by rogerwang** [comment]
What's the DPI setting of your system?

**Comment by Yonezpt** [comment]
Standard windows 96 DPI, no retina display or anything similar.

![ss](https://cloud.githubusercontent.com/assets/8498057/14197470/38fc06ae-f7be-11e5-8c91-8b2b3240e11f.png)

The same problem happens on my laptop with same DPI and OS.

**Comment by ghostoy** [comment]
This issue also appears on upstream Chromium. I've reported in here https://bugs.chromium.org/p/chromium/issues/detail?id=601276. The fix is done in PR nwjs/chromium.src#14

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
