### ISSUE TITLE
Native titlebar on Windows Vista x86?

### ISSUE THREAD

**Issue by estebright** [nwjs/nw.js#4652]
Hi,

I tried nw.js today and like it, but I have one question:

Is it possible to use the native windows titlebar instead of the blue one?
![native titlebar](https://cloud.githubusercontent.com/assets/18160494/14133832/d250c0dc-f652-11e5-96aa-ef80481502d3.png)
![blue titlebar](https://cloud.githubusercontent.com/assets/18160494/14133833/d257dcbe-f652-11e5-8f94-70e639e8d15b.png)

I'm using 1.3.2 (but tried 1.3.1), ia32 build on Windows Vista Ultimate SP1 x86.

Thanks!

**Comment by rogerwang** [comment]
The native titlebar is supported when aero glass effect is on. But unfortunately Aero glass is not working on vista according to upstream, see https://chromium.googlesource.com/chromium/src.git/+/49.0.2623.111/ui/base/win/shell.cc#211
and
https://bugs.chromium.org/p/chromium/issues/detail?id=426573

**Comment by estebright** [comment]
Hi,

Thanks for the reply!

That's kinda wired, I use Chromium 39, and Aero glass is working like a charm? Is this a bug in the newer versions of Chromium?

![chromium](https://cloud.githubusercontent.com/assets/18160494/14134213/a59b3ca4-f655-11e5-962e-6c66f33bb562.png)

I guess there is no way to force using Aero glass? :(

**Comment by rogerwang** [comment]
The current Chromium browser is 49. Please try again and report this issue to upstream if so.

**Comment by estebright** [comment]
Indeed, does not work anymore with the latest build of Chromium browser :(

Anyway, thank you for your replies :D
