### ISSUE TITLE
0.14.0-rc1 on WinXP: GetThreadId could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by TheStalwart** [nwjs/nw.js#4655]
Trying to launch 0.14.0-rc1 on WinXP results in error message. 0.13.0 works ok.

---------------------------
nw.exe - Entry Point Not Found
---------------------------
The procedure entry point GetThreadId could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------

WinXP SP3 virtual machine from Microsoft's modern.IE.

Is this WinXP support officially dropped, or just an accident due to lack of testing?

**Comment by TheStalwart** [comment]
NW.js 0.14.0 is using Chromium 50.0 - i guess it means official WinXP drop

**Comment by rogerwang** [comment]
We'll see XP support, thanks.

TheStalwart <notifications@github.com>于2016年3月30日周三 下午7:04写道：

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by TheStalwart** [comment]
Issue is still reproducible in 04-01-2016 nightly build

**Comment by rogerwang** [comment]
Does RC2 work for you?

**Comment by TheStalwart** [comment]
RC2 doesn't work either. In fact, i checked RC2 first, then RC3-nightly

**Comment by rogerwang** [comment]
weird. It works for me. See the screenshot. What's the exact version of NW and your XP?

![screenshot from 2016-04-01 20-18-58](https://cloud.githubusercontent.com/assets/165401/14206634/120621c2-f847-11e5-91b5-e9ef63593705.png)

**Comment by TheStalwart** [comment]
I've tried:
http://dl.nwjs.io/live-build/04-01-2016/ae806d0-0d2d2fa-f17e9ae-998c2db/v0.14.0-rc3/nwjs-sdk-v0.14.0-rc3-win-ia32.zip

WinXP i'm testing on is a "IE8 on WinXP" VirtualBox image distributed by Microsoft - https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/mac/ , and it's fairly unmolested - i installed a few windows updates, chrome, firefox, opera and that's it. No .Net runtimes or anything like that - clean vanilla WinXP SP3

**Comment by TheStalwart** [comment]
Your wallpaper states you've got x64 edition - i believe it shipped with newer runtimes out of box than 32bit WinXP

**Comment by rogerwang** [comment]
I'll try your VM. What's the error are you getting? Still the same as the issue title?

**Comment by TheStalwart** [comment]
Yes, the error is the same. Thank you for investigating.

**Comment by rogerwang** [comment]
Please try http://dl.nwjs.io/live-build/04-01-2016/0d66481-f19aaa5-f17e9ae-998c2db

**Comment by TheStalwart** [comment]
This one works.

nw.js v0.14.0-rc3
Node v5.9.1
Chromium 50.0.2661.57
commit hash: 0d66481-f19aaa5-f17e9ae-998c2db

**Comment by rogerwang** [comment]
fixed in nightly build.

**Comment by jalbam** [comment]
Hi! I am having exactly the same issue using Windows XP SP3 32 bit with NW.js 0.16.0. Are there any fix for this?
