### ISSUE TITLE
inject-js-end not working in nwjs 50.0.2661.49 

### ISSUE THREAD

**Issue by carlskii** [nwjs/nw.js#4656]
Hi, I'm trying to use inject-js-start, however it NW.js throws the following error when loading: 

`extensions::schemaUtils:34 Uncaught Error: Invalid value for argument 2. Property 'inject-js-start': Unexpected property.`

This is my code. 

```javascript
 var gui = require('nw.gui');
    var new_win = gui.Window.open('https://github.com',
    {
        'inject-js-start': './script.js',
        position: 'center',
                width: 1000,
                height: 1000
    });
```

**Comment by rogerwang** [comment]
It's 'inject_js_start' now. See http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by carlskii** [comment]
Thanks for this. So `'inject_js_end'` does seem to work now without error. So in my view I should be able to do something like this to add JQuery to the page and then add a simple button? 

Its not actually working - so is this the right approach ? 

```
// injection technique borrowed from http://stackoverflow.com/questions/840240/injecting-jquery-into-a-page-fails-when-using-google-ajax-libraries-api
window.onload = function() {
    var script = document.createElement("script");
    script.src = "https://code.jquery.com/jquery-2.1.4.min.js";
    script.onload = script.onreadystatechange = function() {
        $(document).ready(function() {
            $("body").prepend('<div id="test2" style="position: absolute; left: 5px; top: 100px; z-index: 100;"><input type="button" value="Back" onclick="window.history.go(-1)" /></div>')
        });
    };
    document.body.appendChild(script);
};
```

**Comment by rogerwang** [comment]
will check it.

**Comment by rogerwang** [comment]
Need a case to cover remote page injection.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
