### ISSUE TITLE
期待解决共享内存占用高的问题

### ISSUE THREAD

**Issue by sorty** [nwjs/nw.js#4659]
nwjs的各个版本，共享内存的占用都比chrome,Electron高出太多太多，万能的开发大牛们，能解决一下吗？

**Comment by rogerwang** [comment]
Thanks for reporting, but it works for me. There is no known memory consumption issue. 

Please report issue with more detail so we can reproduce it. And please use English only here so all users can read.

**Comment by sorty** [comment]
thank you for replying!
the following are the detail steps。
1.  " http://www.craftymind.com/factory/html5video/CanvasVideo.html " for test。
2. use nwjs and electron(or chrome) to open the web site mentioned above。
3. open windows task manager,and watch。the number of "memory working set"  is growing fast!
![image](https://cloud.githubusercontent.com/assets/172805/14166406/b0a45964-f745-11e5-9d13-81c83c0db0de.png)
