### ISSUE TITLE
[sdk-0.13.0-ia32] nw process crashes when requiring child_process module.

### ISSUE THREAD

**Issue by weiht** [nwjs/nw.js#4660]
version: sdk-0.13.0-ia32
os: windows xp sp3
steps:

- Open nw window, eg., double click nw.exe
- Press F12 to summon devtools
- Switch to 'console' view, type nw.require('child_process')

result: The devtools window, and the nw window, disappear. No nw processes can be found in the Task Manager. And, no crash dump file is generated.

**Comment by rogerwang** [comment]
Is this XP only bug?

**Comment by weiht** [comment]
It's also found on a windows server 2003 (x86, maybe). Linux x64 version works fine on a Linux Mint desktop.

**Comment by rogerwang** [comment]
It works fine for me with latest nightly build of 0.13 on either XP or win7.

btw, we have test case guarding 'child_process': https://github.com/nwjs/nw.js/tree/nw13/test/remoting/child_process

**Comment by weiht** [comment]
I don't have python installed. I used nw.exe to run this test package and the process crashed with Windows XP and sdk 0.13.0, and the new downloaded sdk 0.13.2. I'll try the live-built version later.

**Comment by rogerwang** [comment]
Please attach the crash dump: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by rogerwang** [comment]
Because we can't reproduce, close until there is more information.

**Comment by weiht** [comment]
Sorry. I cannot reproduce this crash on my surface and any other 'concrete', or 'physical' machines either. The windows 2003 I experienced crashing was running on a customer's vmware server, and the windows XP was in a virtual box. And, no crash dump file was generated.
