### ISSUE TITLE
can't open devtools in version after 0.13.0-rc3

### ISSUE THREAD

**Issue by thib3113** [nwjs/nw.js#4661]
I try with : 0.13.1 and 0.13.2 .
My OS is a windows 10 64bits (i try with two differents computers)

Reproduce : 
```javascript
var gui = require('nw.gui');
var win = gui.Window.get();
win.showDevTools();
```

When I open devtools, I see just a blank page, with a strange URI
![devtools](https://cloud.githubusercontent.com/assets/5489218/14170263/0eae9268-f72d-11e5-94e7-756001482a81.PNG)

I use nwjs with npm installer (https://www.npmjs.com/package/nw)

**Comment by rogerwang** [comment]
You should use the SDK build. Normal build doesn't have devtools.
