### ISSUE TITLE
webview crashes when pdf file is loaded

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#4662]
**nwjs 0.13.2 on win 64 sdk on Windows 8.1**

When PDF file is attempted to open in the webview which is embedded in remote page, it crashes nwjs. Interestingly enough, if you open the same pdf in the webview that is embedded in the main html file, it works just fine. We had similar situation before, with the event of the the webview being fired in the main html file, but not in the the webview loaded in the remote page.

**To reproduce:**

1. Drag-and-drop attached "webview_remote" to the nw.exe
2. Google search page will show up. Type "pdf sample" and when results are shown, click on any pdf doc link and nwjs will crash
3. Doing same action with "webview_main" will result in opened pdf doc without any problems

[webview_remote.zip](https://github.com/nwjs/nw.js/files/197284/webview_remote.zip)
[webview_main.zip](https://github.com/nwjs/nw.js/files/197285/webview_main.zip)
[bb2c302b-762c-424a-9f4d-311671a5e32b.dmp.zip](https://github.com/nwjs/nw.js/files/197286/bb2c302b-762c-424a-9f4d-311671a5e32b.dmp.zip)

**Comment by rogerwang** [comment]
is it the same with #4644?

**Comment by krneticz** [comment]
@rogerwang Seems so! I cannot reproduce it in http://dl.nwjs.io/live-build/03-31-2016/6767077-802e375-f039027-404e0c2 . Thank you very much! When is release of 0.13.3 planed? Do you think http://dl.nwjs.io/live-build/03-31-2016/6767077-802e375-f039027-404e0c2 is ok for use in production?

**Comment by rogerwang** [comment]
It's ready for production according to our test results. And all checkins in 0.13 (stable) branch should be bug fixes. Significant changes will go to the beta branch (0.14).

0.13.3 should be released in a week.

**Comment by krneticz** [comment]
@rogerwang Thanks Roger!
