### ISSUE TITLE
Application crashing when calling nw.Window.get()

### ISSUE THREAD

**Issue by josephagoss** [nwjs/nw.js#4663]
My application is crashing whenever I call `nw.Window.get()`

main.js calls initMenu inside menu.js.

**main.js**
```
var menu = require("./../js/menu.js");
menu.initMenu();
```

**menu.js**
```
exports.initMenu = function(){
    var win = nw.Window.get();    
};
```

#### Version details
nw.js `v0.13.2`
Node `v5.9.0`
Chromium `49.0.2623.110`
commit hash: `91c14fe-ed8064e-f039027-5c8f26b`
OS `Windows 7, Service Pack 1`

#### Crash dump attached
[78697a36-c2ed-40c7-b589-9881ba91ac7b.zip](https://github.com/nwjs/nw.js/files/197640/78697a36-c2ed-40c7-b589-9881ba91ac7b.zip)

**Comment by rogerwang** [comment]
Thanks for reporting. This is duplicate with #4368

**Comment by rogerwang** [comment]
Regarding your code, menu.js is running in Node context (background page) so it's has no "current" window.
