### ISSUE TITLE
Is it possible to enable RequestAnimationFrame for background apps?

### ISSUE THREAD

**Issue by Dillybob92** [nwjs/nw.js#4664]
I need to enable RAF when my app is in the background (minimized).  Their is a command line argument for `chromium` called [disable-renderer-backgrounding](https://github.com/atom/electron/issues/4925#issue-143770188), but it currently only works for timers, not RAF. And, it looks like someone at the electron team is working on adding it for RAF too. So, just curious then if it's already possible to do that here with nw.js?

Thanks,

Nick

**Comment by rogerwang** [comment]
Do you have any simple case to verify this feature? Once I made some fix I could use your case to make sure it works and we'll add it to our test framework to make sure it works before release.

**Comment by Dillybob92** [comment]
Hey, sorry for the late reply. 
 
[RequestAnimationIssue.zip](https://github.com/nwjs/nw.js/files/198998/RequestAnimationIssue.zip)

This isn't my game, my game has 100k more lines of code :P. 
But, when you load it, then minimize the window, the game freezes because RAF get's disabled. What should happen is if you minimize the app window, and then return, you should be dead.  Hope this helps

**Comment by Dillybob92** [comment]
Just to add:

I have tried some chrome args as well:

` "chromium-args" : "--disable-renderer-backgrounding",`

Which, [is defined](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/content_switches.cc&q=kDisableRendererBackgrounding&sq=package:chromium&type=cs&l=270) to prevent throttling when in the background. But, as we can see from this [comment](https://github.com/atom/electron/issues/4317#issuecomment-192619978), it looks like `Chromium` is also throttling RAF.

You probably know all this already, but just wanted to let you know what I have tried :)

**Comment by rogerwang** [comment]
@Dillybob92 pls try this build with --disable-raf-throttling

http://dl.nwjs.io/live-build/04-01-2016/ae806d0-e421099-f17e9ae-998c2db

Note that the switch name is subject to change very soon.

**Comment by shikha91** [comment]
hi

i am doing the same like but i have a problem please help me ..

i have created or app.exe by nw.exe and zipped all files in this exe....
and with this exe i have a file (file.txt) and i want to read that file how can it possible ....please help

**Comment by Dillybob92** [comment]
It works!  

You honestly just saved me from converting my entire game into a new engine... I am speechless, this is awesome.

**Comment by rogerwang** [comment]
Will release with 0.13.3 and 0.14.0-rc3
