### ISSUE TITLE
hi   i have created or app.exe by nw.exe and zipped all files in this exe.... and with this exe i have a file (file.txt) and i want to read that file how can it possible ....please help

### ISSUE THREAD

**Issue by shikha91** [nwjs/nw.js#4667]
Read the following before submitting your issue, thank you.

* Use our mailing list to ask questions which don't imply bug or feature request: https://groups.google.com/forum/#!forum/nwjs-general
* State which version are you using
* State which OS version are you running with
* Provide a reproducible case if possible
* Attach the crash dump file if it's a crash: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

Issues meet the checklist above will be processed before those don't.

**Comment by rogerwang** [comment]
Please don't use issue system for questions.

**Comment by shikha91** [comment]
Please tell where can I ask node-webkit related questions...

**Comment by rogerwang** [comment]
https://groups.google.com/forum/#!forum/nwjs-general
