### ISSUE TITLE
Unzip package.nw to memory

### ISSUE THREAD

**Issue by VoidVolker** [nwjs/nw.js#4675]
I'm start this topic to discuss this feature. Simplest way, what I can see:

- Unzip package.nw to memory 
- Start node.js http-server
- Provide application files via local http-server

I think, as first stage of this feature this will cover almost all user cases. I suggest next logic: add option `http` into `package.json`, by default - `false`. If it `true` - nw will load files to memory. 
This feature is usable in case when app have many small files and also it allow to speed up application run on slow PC.

And in some far future this can be integrated with current logic of files loading.

**Comment by rogerwang** [comment]
merge with #2277

**Comment by VoidVolker** [comment]
Wow, did't find 2277, thanks Roger. Now package is unpack into memory?

**Comment by rogerwang** [comment]
No... because 2277 is still open.

**Comment by VoidVolker** [comment]
Ah, I look to wrong `closed` label.
