### ISSUE TITLE
The list of required files which should be shipped

### ISSUE THREAD

**Issue by myrzz0r** [nwjs/nw.js#4676]
In the 12 th version we can remove unnecessary files that are not used in the application. 
For example: https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#which-files-should-be-shipped

While the application is running, all files are used to them, but in the application are not used. Is possible to remove those files in nw 0.13.2?

**Comment by ghostoy** [comment]
@myrzz0r Only tools can be safely removed before redistribution including `payload`, `nwjc` and `chromedriver` in SDK flavor. I'll update clearly in our official document site http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#prepare-nwjs .

**Comment by Zarel** [comment]
Is this still up-to-date? NWjs has a lot more files now than four years ago. In particular, is the `pnacl/` directory still necessary if I don't use PNaCl? I deleted it and everything seems to still work.

**Comment by Zarel** [comment]
Also, how necessary is the locale directory? It's 40 MB and as far as I know, there's not all that much user-facing text in the app that isn't provided by the web part.
