### ISSUE TITLE
error when trying to build "ref", "ffi" and "sqlite3" module on "nw 0.13.0"

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#4677]
I am trying to run node-ref module on mac OS X El Capitan using the below command

> sudo npm install ref@1.2.0

This is working fine but when I am trying to configure it using 

> nw-gyp configure --target=0.13.0 --target-arch=x64

I am getting the following error message.
```
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/nw-gyp/lib/configure.js:361:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "configure" "--target=0.13.0" "--target-arch=x64"
gyp ERR! cwd /Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/ref
gyp ERR! node -v v0.10.44
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok ``
```

I am trying to port my app from nw 0.12.3 to 0.13.0
I am using node v0.10.44 because I have to use ffi module as well.
This was running fine on nw 0.12.3 but i am sort of stuck here.
I can't use node v5.9.0 as of now because I have got to use ffi module(which only works till node v0.10.x) to get the application running on nw 0.13.0.
I basically need to run ref, ffi, ref-struct and sqlite3 module. Even if I use node v5.9.0 and build with node-gyp ref, ffi and ref-struct are looking to build fine, but I am getting error with the sqlite3 module and everything rolls back. All ref, ffi and ref-struct modules get deleted.
I am using the below command to build sqlite3 module. 

> sudo npm install sqlite3@3.1.0 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.13.0

I have gone through the nw 0.13.0 documentation and wiki pages of these modules, but I am still stuck. Please help me with this.

Thanks.

**Comment by rogerwang** [comment]
nw-gyp is not maintained now. see https://groups.google.com/d/msg/nwjs-general/UqEq8ito2gI/W-ld9LSoDQAJ for the new solution.

**Comment by RohitSharma27** [comment]
Alright. So I am using node v5.9.0 to build my native modules. I was successfully able to configure and build "ref", "ffi" and "ref-struct" module (Although they have stated that "The current version is tested to run on node v0.6, v0.8, v0.9 and v0.10" on node-ffi's github page [https://github.com/node-ffi/node-ffi](url). But somehow it all went fine. ) Now, when i am trying to configure node-sqlite3 module, I am getting the following error.
`gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.9.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rohit/.node-gyp/5.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rohit/.node-gyp/5.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/rohit/node-webkit-html5-desktop/app-html5-nodeWebkit/versioned_modules/v_0.13.0/node_modules/sqlite3
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok `

I have used 

> sudo npm install sqlite3@3.1.0 

to install the node module and then after being inside the sqlite3 folder, I am running 

> node-gyp configure

This is when i get the above stated error. Is there something wrong with the sqlite3 module or the combination of these 4?

Thanks.
