### ISSUE TITLE
Build NW.js on CentOS 5.6

### ISSUE THREAD

**Issue by clyang82** [nwjs/nw.js#4678]
I am trying to build nw.js on CentOS 5.6 following the instruction(https://github.com/nwjs/nw.js/wiki/Building-nw.js). I spent the whole day to have a build. But still cannot have a successful build. When I follow the instruction to build nw12, there is no content/nw directory after execute "_git checkout nw12_". I switched to nw13, it throws the exception when run this command " _ninja -C out/Release nw -j4"_
ninja: Entering directory `out/Release'
ninja: error: '../../build/util/LASTCHANGE', needed by 'gen/chrome/common/chrome_version.h', missing and no known rule to make it

Who can point me out is it possible to build nw.js on CentOS 5.6? How to resolve my problem? If you have such package, could you please share me? many thanks in advance.

**Comment by rogerwang** [comment]
Please post questions to our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
