### ISSUE TITLE
Packaged application with command line parameter won't start

### ISSUE THREAD

**Issue by swaitz** [nwjs/nw.js#4681]
I came across a little problem which prevents my application from starting properbly when I use command line parameters. Without the command line parameter the application starts and works fine but with them the application won't start.

Here is an example of the parameters: ctiClient.exe --agentId 9999 --agentPass 9999
I have packaged the application with this command: copy /b nw.exe+ctiClient.nw ctiClient.exe

With the old version 12.3 the command line parameter work as expected but in the new version 13.3 the application won't start. I can see the application in the task manager but I can not see it on the screen.

I have played a litte with the parameters and found out that when I start my application like this
ctiClient.exe ctiClient.nw --agentId 9999 --agentPass 9999 everything works as expected.

But why should I give the application the name of the zip file as second parameter?

Here some informations about the application which could help you to find the problem

package.json: 
```json
{ 
 "name": "ctiClient",
 "main": "index.html",
    "version": "1.1.0",
    "window": {
        "title": "ctiClient",
        "icon": "icon_invert.png",
        "resizable": true,
        "frame":  false,
        "width": 750,
        "height": 390,
        "min_width": 375,
        "min_height": 195,
        "show": false
    }
}
```

Code which reads the parameter:
```javascript
if (app.argv.length > 0) {
    for(var i=0; i<app.argv.length; i++) {
        switch(app.argv[i]) {
            case '--agentId':
                    agentId         = app.argv[(i+1)];
                break;
            case '--agentPass':
                    agentPass       = app.argv[(i+1)];
                break;
        }
    }
}
```

Tested on the following operating systems:
Windows 7 64 Bit
Windows 8.1 64 Bit

Tested with nw.js Version:
SDK Version 13.2
SDK Version 13.3

I think it is the same problem which was discribed in this Issue #2416. 

If you need more informations please let me know that.

Thanks for the help,
Sascha

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
