### ISSUE TITLE
MediaEvent: PIPELINE_ERROR demuxer: could not open

### ISSUE THREAD

**Issue by loretoparisi** [nwjs/nw.js#4687]
I have a mp3 audio in the html index page:

```html
<audio id="audioAlertOK">
 <source src="assets/sounds/Sosumi.mp3" type="audio/mpeg">
</audio>
```

I try to preload the audio when the demux fails:

```javascript
var audio=document.getElementById("audioAlertDONE");
if(audio) {
  audio.load();
  console.log("Playing audio %s",audio.src);
  audio.play();
}
```

I have found a related issue in `Chromium`: https://bugs.chromium.org/p/chromium/issues/detail?id=572628

NWJS version: `nwjs-sdk-v0.13.3-osx-x64`

**Comment by iteufel** [comment]
NW.js doesn't support mp3 out of the box.
Please read [Enable Proprietary Codecs](http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/).

**Comment by loretoparisi** [comment]
@iteufel Yes I have update the so libraries using the `soundnode` build - see my comment here http://stackoverflow.com/questions/29590898/where-to-find-ffmpegsumo-libraries-for-nw-js-0-12-0-play-audio-files-in-nodewe/36463528#36463528

What happens is with `nwjs-macappstore-v0.12.3-osx-x64` I can hear no sound, but no error, while using the `nwjs-sdk-v0.13.3-osx-x64` I have the `demux` error. Both have the right lib there:

```shell
$ lipo -info ./nwjs Framework.framework/Libraries/ffmpegsumo.so is architecture: x86_6

**Comment by loretoparisi** [comment]
..uhm ok it's a bit complicated due to licensing issues, so it's better to

```shell
cd /assets/sounds/
for f in ./*.mp3; do ffmpeg -i "$f" -c:a libvorbis -q:a 4 "${f/%mp3/ogg}"; done
```

and then

```html
<audio id="audioAlertOK">
 <source src="assets/sounds/Sosumi.mp3" type="audio/ogg">
</audio>
```

problem solved!

**Comment by rogerwang** [comment]
@loretoparisi so what's not solved?
