### ISSUE TITLE
NW.js 0.13.3 : how to open a local pdf file in chrome://print window ?

### ISSUE THREAD

**Issue by joelz** [nwjs/nw.js#4688]
Hi,

Related google group post：https://groups.google.com/forum/#!topic/nwjs-general/uxd20LIWbHg

*****

Using： nw.js v0.13.3 on win ia32 sdk on Windows 7 sp1 x64。

Currently I'm testing the pdf viewer in nw.js 0.13.3. The pdf viewer is nice, I can open a local pdf file in the pdf viewer and press the Print icon on the top right corner to get the print preview. From the dev tool, I find this preview page's url is **chrome://print** :

![01](https://cloud.githubusercontent.com/assets/469974/14337205/4f972a4e-fc9e-11e5-8405-2c162c2f25d1.png)

Is it possible to open a local pdf file in this  **chrome://print**  without using  the pdf viewer? 

I tried with `  window.open("chrome://print?file:///test.pdf");  ` and got a print preview page ,but the preview area is empty (the characters just said "loading preview..."):  

![02](https://cloud.githubusercontent.com/assets/469974/14337209/571a59f8-fc9e-11e5-9adc-03f5f5b180da.png)

Anyone has some insights ? Or it's just impossible ?

Thanks for any help.

**Comment by rogerwang** [comment]
It should be possible and supported. We'll see this soon.

**Comment by rogerwang** [comment]
In Chromium upstream the PDF viewer is written in JS/HTML and builtin in the resource file in the release.

If I enable a feature that the PDF viewer files can be override by you, so you can take the JS files from Chromium, modify it whatever you want, will that be good enough for you?

See the JS files for PDF viewer here: https://github.com/nwjs/chromium.src/tree/nw13/chrome/browser/resources/pdf

**Comment by joelz** [comment]
The feature you mentioned would be very exciting, although it may not solve my problem. When would this feature be available? Is it on your schedule ?

Meanwhile I will take a look at those JS files for PDF viewer. Hope I can find some ideas on the reason why the preview area is empty. Maybe I missed something when opening **chrome://print** directly via ` window.open("chrome://print?file:///test.pdf");`

**Comment by rogerwang** [comment]
This is now supported. See #5002
