### ISSUE TITLE
nwjs can run on Ubuntu Server or not?

### ISSUE THREAD

**Issue by whatisor** [nwjs/nw.js#4689]
I want to run nodejs application with nwjs on Ubuntu Server to serve a image.
Can nwjs application run on Ubuntu Server?
Thank you

**Comment by ghostoy** [comment]
Currently NW.js requires XWindow to rendering the GUI. So you need to install sort of desktop like Unity (GNOME), or virtual XWindow server like Xvfb. Headless mode is on the based on the implementation of upstream Chromium (see #769).

If your app is pure Node.js, NW can run it without any GUI system like Node.js. Type `nw path/to/your/app.js`.
