### ISSUE TITLE
NW js 0.13.3 redirect canceled

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#4690]
nwjs0.12 is all right,but after I upgrade to 0.13.3 . The calling is error. 
redirect_uri = app://axe/token.html
It can not be redirected to this page. The request status is canceled.
http://accounts.axeslide.com/oauth/authorize?client_id=win64&redirect_uri=app%3A%2F%2Faxe%2Ftoken.html&state=my-nonce&scope=all&response_type=token 
@rogerwang

**Comment by liufangfang** [comment]
is "app://axe/token.html" this format is not supported?

**Comment by ghostoy** [comment]
`app://` protocol is deprecated in 0.13. Now all URLs are under `chrome-extension://`. See [migration notes](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/) from official document for this change.

**Comment by liufangfang** [comment]
I have seen it. Then I use "chrome-extension://axe/token.html" replace it. It's not work.
And I test it in package.json not work also.

**Comment by rogerwang** [comment]
Could you please share a minimum sample which works in 0.12 but not in 0.13?

**Comment by ghostoy** [comment]
The host part should not be 'axe'. It's your app id (try to log
location.href to see what it is).

Roger Wang <notifications@github.com>于2016年4月7日周四 20:37写道：

> Could you please share a minimum sample which works in 0.12 but not in
> 0.13?
>

**Comment by liufangfang** [comment]
Can I define app id by myself ? And I want it is uniform.

**Comment by Yonezpt** [comment]
@liufangfang `chrome.runtime.id` will give you the id of your current app, so for this case the result should be:

````js
redirect_uri = "chrome-extension://" + chrome.runtime.id + "/axe/token.html";
````

Assuming "axe" is at the root of your app folder.

**Comment by ghostoy** [comment]
You can't define it yourself. It's generated from the name of your app.

liufangfang <notifications@github.com>于2016年4月8日周五 10:27写道：

**Comment by ghostoy** [comment]
chrome.extensions.getURL could also help.

Particle <notifications@github.com>于2016年4月8日周五 22:24写道：

**Comment by liufangfang** [comment]
Thanks. I test it and find it should be related to the name setted in package.json.  @ghostoy

**Comment by ghostoy** [comment]
@liufangfang Please close the issue if your problem is solved.
