### ISSUE TITLE
NW-13.3 : random crash on confirm/prompt call

### ISSUE THREAD

**Issue by bruspal** [nwjs/nw.js#4692]
Hi,

I reopen the issue #4612.
Sorry, I was a bit busy last two weeks thus I didn't have time to focus on ths particular point. I upgraded my app with le last version but the app still crashing. The only change is instead of a systematic crash the application is now randomly crashing. It can crash on the first call as well as on the 10th. 

However I noticed that if intervals between calls are short it's ok but if the period between two call is long it tend to crashes.

This issue occur on windows 7,8 and 10 all x64 with more or less the same behavior.

I'am using very classical JS lib : 
- jquery : 2.2.3 (I tried also with 1.9.x)
- jQueri-ui
- jQmodal 1.4.0
- ckEditor 4
- codemirror 5.9.0

calls to prompt/confirm are linked to jQuery events, but I tried with native JS without changes. If I find something new I'll let you know.

Best regards.

Here is the dump summary

```
Dump Summary
------------
Dump File:  f5aeb8ee-f123-4224-9496-82d43edbfb4e.dmp : C:\Users\INFORMATIQUE_1\AppData\Local\Crashpad\reports\f5aeb8ee-f123-4224-9496-82d43edbfb4e.dmp
Last Write Time:    06/04/2016 16:25:45
Process Name:   nw.exe : C:\nwdump\nw.exe
Process Architecture:   x64
Exception Code: 0xC0000005
Exception Information:  The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:   Not Present

System Information
------------------
OS Version: 10.0.10586
CLR Version(s):
```

[nw-dump.zip](https://github.com/nwjs/nw.js/files/207853/nw-dump.zip)

**Comment by rogerwang** [comment]
I can fix the crash according to the crash dump. But it would be better to understand why it happens. Would you please attach a case to reproduce this?

**Comment by bruspal** [comment]
Hi,
Ok I'll try to produce reproductible case. I let you know as soons as possible.

Thanks.

**Comment by icerleer** [comment]
Hello, I have encountered the same problem

I use jquery version is 3.1.0, nwjs version 0.15.4

Step I test.

1. On page until a certain time, about 15 seconds
2. Click the button to confirm the method of calling Jquery

**Comment by bruspal** [comment]
Hello,
On my side a solved this issue by overiding these functions by mine this something like.
alert = function(message) {
   // custom code here
}

I had to push to prod so I cannot wait until it's fixed. Till now I didn't have any problems with solution. However I had to rewrite a bit code using prompt() and confirm() because new functions are async.

Bye.

**Comment by ghostoy** [comment]
Does it still happen on NW16?

bruspal <notifications@github.com>于2016年7月30日周六 17:54写道：

**Comment by bruspal** [comment]
Hi ghostoy.

Yep I did basic tests. Still silently crashing on NW16 with alert, prompt and confirm.

I tried to get dump files put nothing appears on C:\Users\XXX\AppData\Local\Crashpad but nothing appears. I tried to run on custom location using --user-data-dir but i didn't found any crash files.

There is any other location for dump files ?

**Comment by ghostoy** [comment]
@bruspal It should be in the `%LOCALAPPDATA%\Crashpad`. If not, we need a test case to reproduce the crash. Sorry :(

**Comment by bruspal** [comment]
@ghostoy dump still missing in the %LOCALAPPDATA%\Crashpad directory.

I will try to reproduce a test case ASAP.

**Comment by Christywl** [comment]
@bruspal , is this issue still reproduced with the latest nwjs? If yes, could you please upload a test case to reproduce it?

**Comment by bruspal** [comment]
@Christywl Hi, sorry for the delay. until I'm in production I choose to override default alert/prompt using homemade functions. 

I upgraded my client to 0.22.3 and it's now working perfectly. So I'll migrate my client and push it in production. Everythings should be allright.

Many thanks to @rogerwang , @ghostoy and all the nwjs team :)
