### ISSUE TITLE
[0.13.3] Linux Fedora application menu says 'nwjs' instead of package.json name

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [nwjs/nw.js#4693]
![image](https://cloud.githubusercontent.com/assets/7252279/14366695/f7a63bea-fd0b-11e5-968a-2b78d4ce92dc.png)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by ghostoy** [comment]
Regression in 0.18.2.

**Comment by ghostoy** [comment]
This issue will be fixed soon.

Workaround for 0.18.2: use `--class` CLI parameter to overwrite `WM_CLASS` property of your app.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
