### ISSUE TITLE
Unable to disable or clear cache/temp files

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#4695]
OS: Win7x64
NWJS: sdk0.13.3 and sdk0.14.0rc3

User data folder never empties or never clears, the result is a folder with navigation/usage history that keeps filling constantly during the app use.

In my case I moved the user data folder to the app root, but the problem also occurs if no custom path is set in package.json

````json
 ...
    "chromium-args": "--user-data-dir='temp/'",
 ...
````

While navigating YouTube, for this example, and watching videos the temp folder fills up with history and temporary files. Closing the app does not clear the data and using `nw.App.clearCache()` makes no difference either.

The result is a user data folder that starts with around 12MB on first app run
![small](https://cloud.githubusercontent.com/assets/8498057/14387816/a19e9c9e-fd9a-11e5-8bf7-26f604d25b92.png)

and ends up with over 200MB after watching a few videos or navigation a few pages.
![big](https://cloud.githubusercontent.com/assets/8498057/14387814/a0ad77ec-fd9a-11e5-86a7-484a09518e58.png)

I first noticed this when I found this folder with over 500MB and since then I tried to solve this problem but I haven't been able to disable cache ([WebKit page-cache option](https://github.com/nwjs/nw.js/wiki/manifest-format#page-cache) appears to have been dropped in the [official documentation](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#webkit-subfields)) or find a way to clear it up when the app is closed or once a certain size is reached.

**Comment by rogerwang** [comment]
Do you mean 'nw.App.clearCache()' ? Does it work for you?

**Comment by Yonezpt** [comment]
Yes, I mean clearCache, not clearData. It was a yping mistake. Whatever it does it is not clearing the cache in the user data dir.

**Comment by rogerwang** [comment]
How to reproduce this? I ran nw with 'nw --url=https://youtube.com', watched some videos but the size of user data dir doesn't grow.

**Comment by Yonezpt** [comment]
I am sorry for the delay, here is an example which can be used to reproduce the problem on Win7x64 NWJS sdk0.14.0rc3

using the `package.nw` folder method located in the `nwjs` root for this example, the following are its contents:

`index.html`

````html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/XPI6J6UF3Kg" frameborder="0" allowfullscreen></iframe>
</body>
</html>
````

`package.json`
````json
{
    "author": "",
    "chromium-args": "--user-data-dir='temp/'",
    "description": "test",
    "main": "index.html",
    "name": "name",
    "version": "1.0.0",
    "window": {
        "height": 505,
        "width": 949
    }
}
````

Set the video quality to high so that the user data folder size increment can be easily observed. After watching the video for 3 or 5mins the user data folder (`temp` folder located in `nwjs` root) went to 358MB. Closing the app and opening it again did not clean the folder and neither did `nw.App.clearCache()`.

**Comment by rogerwang** [comment]
I tried the sample with latest nightly build in Linux and clearCache() works: http://dl.nwjs.io/live-build/04-11-2016/05c3c52-fe0942b-5b48326-98bfcac

We fixed a bug in clearCache() recently.

Could you please verify it?

**Comment by Yonezpt** [comment]
Again I am sorry for the delay. Yes, what has been done in that version now allows `clearCache` to reduce the user data folder size. After letting it reach 400MB I executed it and the user data folder went down to 31MB.

If possible it would be best to have some sort of automatic control or limitation that can be set to prevent the user data folder from growing too much. On my larger duration test I was able to reach a user data folder that occupied 1.8GB and it never cleaned itself, I was forced to delete the files or folder manually. Most of these files I believe to be temporary (most of them are stored in the Cache folder), they should "expire" once they are too old or the size they are occupying is too big.

For the moment `clearCache` during app start/close will make things a bit easier, but it isn't a solution.

**Comment by rogerwang** [comment]
Yeah. Will add this option.

**Comment by Gimmeaphatbeat** [comment]
This works for me, in the `package.json`:

```
"chromium-args" : "--disk-cache-size=1"
```

**Comment by Yonezpt** [comment]
I have been struggling with this situation since this issue was posted, a few solutions have been working but not consitently, for some reason the cache still grows on its own and doesn't clear at all except by manually deleting the folder.

I think I now have managed to find out which file is causing problems and it is the `History` file (no extension) that is located inside the `Default` folder in your app cache directory. It is somehow increasing its size randomly and it never clears up by any methods suggested here or found elsewhere.

I haven't yet managed to reproduce the problem intentionally but I am still monitoring it with every step I take so that I can find the correlation.

Below are the methods I have already used to clear the cache folder programatically:

````json
"chromium-args": "--user-data-dir='temp/' --disk-cache-size=1 --media-cache-size=1 --incognito"
````

code APIs:
````javascript
window.nw.App.clearCache();

// this one will cause significantly increase the
// shutdown duration if run during app exit
window.chrome.browsingData.remove({
    since: 0
}, {
    appcache: true,
    cache: true,
    cookies: true,
    downloads: true,
    fileSystems: true,
    formData: true,
    history: true,
    indexedDB: true,
    localStorage: true,
    pluginData: true,
    passwords: true,
    serverBoundCertificates: true,
    serviceWorkers: true,
    webSQL: true
});
````

**Comment by Yonezpt** [comment]
Finally figured what was causing the History file bloat. For some reason using a non-nwjs built ffmpeg.dll (with proprietary codecs enabled) was causing an instant creation of a History file with 7.37MB. Using NWJS own ffmpeg.dll (and community contributed versions) made this problem stop completely.
With this conclusion I think it is time to close this issue since all the previous methods have been working correctly so far.
