### ISSUE TITLE
NWjs crashes sometimes on Windows when using menu.popup

### ISSUE THREAD

**Issue by iteufel** [nwjs/nw.js#4697]
NWjs crashes sometimes on Windows when using `menu.popup` .

The problem appears since the fix #4593.

[dmp.zip](https://github.com/nwjs/nw.js/files/211208/dmp.zip)
[menu-test.zip](https://github.com/nwjs/nw.js/files/211209/menu-test.zip)

**Comment by rogerwang** [comment]
I guess the menu is GCed before the crash. To verify this idea, does holding a reference to the menu object help?

**Comment by iteufel** [comment]
Yes it helps.

**Comment by rogerwang** [comment]
please try this build: http://dl.nwjs.io/live-build/04-10-2016/723bab6-897a464-c2a3dcf-65b297d/

**Comment by fritx** [comment]
Same here...
I'm using nwjs 0.14.7-sdk, in Windows the app crashes every time I run the following code:

```js
var gui = require('nw.gui');
var menu = new gui.Menu();
var item = new gui.MenuItem({ label: 'Item A' })
menu.append(item)
menu.popup(10, 10); // <---- crash
```

**Comment by fritx** [comment]
Both of nw 14.7 and 18.7 crash:

![image](https://cloud.githubusercontent.com/assets/6647633/20557669/5c3a89e4-b1a7-11e6-81f8-d19725dcd26e.png)

**Comment by fritx** [comment]
Related issue: https://github.com/nwjs/nw.js/issues/5331
