### ISSUE TITLE
Which UI Kit / Framework / Library do you use?

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#4699]
What UI framework do you tend to use with your nwjs projects? 

This isn't an issue exactly but there is no official recommendations for frameworks for use with desktop applications. I've looked through many many bootstrap type admin templates to find non really fit for desktop app purposes but this would depend per application.

Are there any specific frameworks you 1) would recommend? 2) have used already? 3) could showcase or share?
 
I personally have found mac style ui's (not material design) are most fitting for my desktop web apps. There is http://photonkit.com/components/ if anyone is interested.

**Comment by rogerwang** [comment]
Please discuss in the mailing list: https://groups.google.com/forum/#!forum/nwjs-general
