### ISSUE TITLE
webview http referer

### ISSUE THREAD

**Issue by elBarkey** [nwjs/nw.js#4703]
* nw version: 49.0.2623.112
* OS: Ubuntu 14.04

Hi
I can't find any reference about this feature in nw.js
Comparing to Electron, this feature was available  since long time ago.
Is there any possibiility we can get this in nw?

Thanks.

**Comment by rogerwang** [comment]
The webrequest API can cover this need. With it you can modify headers in the request: https://developer.chrome.com/extensions/webRequest

**Comment by elBarkey** [comment]
thanks @rogerwang 

Im not familiar with webrequest API, does it render the request like webview/iframe do ?

**Comment by elBarkey** [comment]
Sorry about my last dumb question.
After the first try, webrequest API only works on nw window instance
It doesn't catch any request made by webview.

**Comment by rogerwang** [comment]
webview supports the webrequest API. Please check https://developer.chrome.com/apps/tags/webview

**Comment by elBarkey** [comment]
yeah i read it already.
but the following snippet doesn't get fired at all.

```html
<!--index.html-->
<!DOCTYPE html>
<html>

<head>
    <title>RealTraffix</title>
    <link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>
    <webview class="webv" id="myWebv" src="https://www.whatismyreferer.com"></webview>
</body>
    <script type="text/javascript" src="main.js"></script>

</html>
```

```javascript
//main.js
(function(){
var webview = document.getElementById('myWebv');
webview.request.onBeforeRequest.addListener(
  function(details) { return {cancel: true}; },
  {urls: ["*://www.whatismyreferer.com*"]},
  ["blocking"]);
})();
//webview.request
                ^  request is undefined here.
```

nor this one
```javascript
//main.js
(function(){
var webview = document.getElementById('myWebv');
chrome.webRequest.onBeforeRequest.addListener(
  function(details) { return {cancel: true}; },
  {urls: ["*://www.whatismyreferer.com*"]},
  ["blocking"]);
})();
//not fired at all..
```

**Comment by elBarkey** [comment]
**UPDATE:**
Using the snippet above works good in the devtools.
So, maybe its just the execution order problem.
