### ISSUE TITLE
Failed to load node library libnode

### ISSUE THREAD

**Issue by xiwasong** [nwjs/nw.js#4704]
[root@localhost nwjs-v0.13.4-linux-ia32]# ./nw 
Xlib:  extension "RANDR" missing on display "localhost:11.0".
Xlib:  extension "RANDR" missing on display "localhost:11.0".
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[6890:6890:0702/010617:ERROR:gl_surface_glx.cc(386)] GLX 1.3 or later is required.
[6890:6890:0702/010617:ERROR:gl_surface_x11.cc(62)] GLSurfaceGLX::InitializeOneOff failed.
[6890:6890:0702/010617:ERROR:gpu_child_thread.cc(260)] Exiting GPU process due to errors during initialization
[6907:6907:0702/010617:FATAL:renderer_main.cc(179)] Failed to load node library (error: libnode.so: 无法打开共享对象文件: 没有那个文件或目录)
#0 0x0000b1b2b1ca <unknown>
#1 0x0000b1b46d4d <unknown>
#2 0x0000b597000d <unknown>
#3 0x0000b1af2479 <unknown>
#4 0x0000b1af29ac <unknown>
#5 0x0000b1af3642 <unknown>
#6 0x0000b1af1fb2 <unknown>
#7 0x0000b150427a ChromeMain
#8 0x0000b76a47b8 <unknown>
#9 0x0000b0c12b73 <unknown>

**Comment by rogerwang** [comment]
I cannot reproduce this. Is libnode.so there in your filesystem?

**Comment by xiwasong** [comment]
when i copied nwjs's lib/libnode.so to /usr/lib,and then it was ok.

**Comment by rogerwang** [comment]
It could some security measures in your system to prevent loading dynamic libraries from arbitrary path. Could you please check it?

**Comment by rogerwang** [comment]
close until there is more information.

**Comment by fcasarsasolari** [comment]
Hello,

it seems that the downloaded tar contains unusual permissions 700 or 600 instead of more common 755 / 644. 

After fixing permissions to root directory eg
chmod +r /runtimes/nwjs-v0.14.5-linux-ia32/
chmod 755 /runtimes/nwjs-v0.14.5-linux-ia32/locales/*
....

then for me it worked and it is possible also to call nw by not priviledged users.

**Comment by sparkleholic** [comment]
Is there any special reason that libraries (libnode.so, etc) have 700 permissions in the linux distribution ?

**Comment by PrakashK94** [comment]
Is there any other way using which we can launch NwJs application in linux from root? I mean to say something like updating the path of libnode.so in some environment variable? 

It is working fine if we copy the libnode.so to /usr/lib.

**Comment by LinuxCao** [comment]
because current gcc version is  too low
fixed solution ：
#apt-get install gcc-5
