### ISSUE TITLE
Content of file included via "inject_js_start" is executing twice

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#4705]
nw 0.13.0
node v5.9.0
mac OS X El Capitan

I have a file "app.js"  and I am injecting it via "inject_js_start". When I do "Inspect -> Console", I see the same output being logged "twice".

> One is from "VM181.js" and other is from "app.js".

It looks like the same content is getting executed twice. I have found out that when i click on the file "app.js" and use a breakpoint then it works but the same doesn't work in "VM181.js".

Also, the content of "app.js" is getting logged in the dev tool of background page. Why is that?
When I do "Inspect background page -> Console". I can see every content being logged their once from "app.js".

From the documentation, I can infer that node context is now put in DOM context of the background page, which means that node module's content should be logged there. Why is this app.js' content there?

One more thing the entire output from "VM181.js" gets logged first and I can only see the output from "app.js" being logged by placing breakpoints.

**Comment by RohitSharma27** [comment]
It looks like the script that is injected via "inject_js_start" is getting injected in every window that I open from the main window. It's output is getting logged in 
"Inspect background page -> Console" once from "app.js"
"Inspect -> Console" twice from "program.js or VMsomeNumber.js" and "app.js"
"Inspect -> Console" twice from "program.js or VMsomeNumber.js" and "app.js" on the new window that I have opened from the main window via "nw.open()"
@rogerwang

**Comment by RohitSharma27** [comment]
@rogerwang It is also there in nw 0.14.2.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by RohitSharma27** [comment]
@rogerwang Please re-open this issue. I have tried it with nw0.14.3. I am injecting "app.js" file using "inject_js_start", as before. Here is what is happening.
1. Background page's console isn't logging app.js' "console.log()" statements, which is the desired behaviour.
2. But, if I have opened a new window from "app.js" then the console.log() statements from "app.js" are there in newly opened window as well.
  2.1 If I use "new-instance:true" then the "Window" object in the callback of "nw.Window.open()" is                          undefined.
  2.2 If I don't use it then the "Window" object is there in the callback.

.

**Comment by rogerwang** [comment]
If I understand your situation correctly, 2nd point is expected because 'inject_js_start' script in manifest is supposed to be global and apply to every windows. So what you're logging in app.js will be in the newly opened window as well.

**Comment by RohitSharma27** [comment]
Ummm...okay cool. Thanks for letting me know that. But, what about the point 2.1 and 2.2?
This is the content of "app.js"
` nw.Window.open("hehe.html",{"new_instance":true,"id":"1","show":true},function(win){
 	win.on('loaded',function(){
 		console.log("successfully opened :",win);
 	});
 });`
It logs undefined. But, if I don't use new_instance:true then, it works fine.
