### ISSUE TITLE
Window.open(url, [options], [callback]) set to "new-instance:true", then nw.exe just can open once.

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#4706]
@rogerwang 
Write like this. And just can open once?? If not set this configuration item, it can open multiple window. 
![image](https://cloud.githubusercontent.com/assets/3468473/14458166/fba26604-00e1-11e6-8d71-1e08121f6290.png)

**Comment by RohitSharma27** [comment]
"new_instance" here means that the new window will have it's own seperate node-context which is otherwise shared among all the windows.

**Comment by liufangfang** [comment]
@RohitSharma27 My question is that it can open new window just once.

**Comment by RohitSharma27** [comment]
@liufangfang  Well no. You can open any number of windows even after using 

> "new_instance" : true
This is what I meant it doesn't restrict it from opening multiple windows. But,

> You will have to use different Ids for opening new windows since,  you are specifying your own Ids. 
I hope this will answer your question.

**Comment by liufangfang** [comment]
OK, I test it's well. @RohitSharma27

**Comment by liufangfang** [comment]
And, I have another question. How to pass a parameter to the new window when open. Do you know? @RohitSharma27

**Comment by ghostoy** [comment]
@liufangfang Please ask questions in the mail list. https://groups.google.com/forum/#!forum/nwjs-general
