### ISSUE TITLE
[0.13.4] how could I change the icon of the devtools? 

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#4707]
version: 0.13.4
os:  win

package.json set the icon like this:

```
{
  "main": "index.html",
  "name": "demo",
  "window": {
    "icon": "icon.png",
    "width": 799,
    "height": 799
  }
}
```

then open nw

the main window's icon is icon.png,but if i open the devtools, find its icon still was nwjs'icon.

![image](https://cloud.githubusercontent.com/assets/3161552/14459167/fb781ffa-00e8-11e6-8f2e-5166c6055361.png)

![image](https://cloud.githubusercontent.com/assets/3161552/14459180/081f0386-00e9-11e6-917f-59576144281f.png)

So I wonder if there's any way to accomplish this? Every response will be appreciated, thank you.

**Comment by rogerwang** [comment]
Will fix this with using the same icon.
