### ISSUE TITLE
[0.13.4]Shortcut not work in devtools while it placed in a webview

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#4709]
version: 0.13.* 
os: just mac

test code:
```
<!DOCTYPE html>
<html>

<head>
  <title></title>
  <style type="text/css">
  #demo {
    display: inline-block;
    height: 500px;
    width: 320px;
  }

  #demodev {
    display: inline-block;
    height: 500px;
    width: 640px;
  }
  </style>
  <script>
  function test(show) {
    var demodev = document.getElementById('demodev');
    document.getElementById('demo').showDevTools(show, demodev);
  }
  </script>
</head>

<body>
  <webview partition="persist:trusted" id="demo" src="http://xw.qq.com"></webview>
  <webview partition="persist:trusted" id="demodev" src="about:blank"></webview>
  <button onclick="test(true)">show</button>
</body>

</html>
```

```
{
  "main": "index.html",
  "name": "nw-demo",
  "window": {
    "height": 700,
    "width": 1000
  },
  "webview": {
     "partitions": [
        {
          "name": "trusted",
          "accessible_resources": [ "<all_urls>" ]
        }
     ]
  }
}

```

After show the devtools, can find shortcut like command + c , command + a ... not work.

![image](https://cloud.githubusercontent.com/assets/3161552/14482318/0865483e-016e-11e6-9b60-f4f963176e25.png)

**Comment by ghostoy** [comment]
Not seeing this issue. Could you please post a sample app?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
Please test with http://dl.nwjs.io/live-build/04-14-2016/1a750fd-f581ec8-c2a3dcf-65b297d

**Comment by lin-chao** [comment]
hot keys can work now

thanks~

**Comment by lin-chao** [comment]
hi @rogerwang 

0.16.0 and 0.16.1 have this problem again.

Shortcut not work in devtools while it placed in a webview

**Comment by rogerwang** [comment]
This is fixed in git and is available at https://dl.nwjs.io/live-build/08-17-2016/nw16-1d6387e-f529e82-b879ccd-80ede20/v0.16.2/
