### ISSUE TITLE
How to pass a parameter to the new window when open

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#4712]
How to pass a parameter to the new window when open. I want set a user-defined property “fileName” but not work.
![image](https://cloud.githubusercontent.com/assets/3468473/14483718/6ba54aa8-017c-11e6-8c5e-1cee257a60d4.png)

**Comment by liufangfang** [comment]
@rogerwang Could you answer my question?

**Comment by ToyYang** [comment]
I used URL parameters...

example, 

https://google.comin=titlesposts&sortBy=timestamp&sortDirection=desc&showAs=posts&_=1460994485984&page=2

**Comment by linquize** [comment]
Same question for me!

**Comment by pablozandona** [comment]
+1

**Comment by kailniris** [comment]
Ask questions in the mailing list

```
nw.Window.open(path, {}, (newWin) => {
  newWin.on('loaded', () => {
    newWin.window.myvar = myvar;
  });
});
```

**Comment by RohitSharma27** [comment]
You can try the following ways as per your need.

- As suggested by @K68 , you can use url parameters

- Window.postMessage API to communicate between windows.

- You can go for the Local Storage (Assuming that the new window is going to have the same domain as that of the parent window.)

- You can save it in the process object and then retrieve it back in child window (Assuming you aren't running your app in mixed-context mode and the new window hasn't been opened with new-isnstance set to true.)

I hope this will help. Cheers. :)

**Comment by pablozandona** [comment]
I tryed postMessage but doesnt work:

```
                    if(new_win) {
                        window.postMessage("hey", '*');
                    } else {
                        new_win = gui.Window.open(url, {
                            position: 'center',
                            width: 800,
                            height: 600,
                            frame: false
                        }, function (win) {
                            new_win = win;
                        });
                    }
```

**Comment by rogerwang** [comment]
thanks for the answer from @kailniris
