### ISSUE TITLE
Feature request: Relative cookie store in folder.

### ISSUE THREAD

**Issue by luckcolors** [nwjs/nw.js#4715]
Is it possible to instruct nw.js to save any cookie data generated by the web app into a datastore relative to where the app is run by only specifing an new option on package.json?
This would allow for example effortless distribution of html5 games which are requiring cookies to store stats and saves.

**Comment by rogerwang** [comment]
You could use '--user-data-dir' and a relative path. It can be used in command line or written in package.json. Please ask further questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
