### ISSUE TITLE
node-webkit crashed when onclick on function that is not defined

### ISSUE THREAD

**Issue by idoaizenshtein** [nwjs/nw.js#4716]
node-webkit crashed when onclick on function that is not defined.
example:
`<div onclick="someFunIsNotDefined()">click</div>`
How to prevent this collapse?
The crashes are only versions 0.13.4-0.14, are not there at 0.12-0.13.3.

**Comment by rogerwang** [comment]
This should be fixed in 0.14.1. Please try again.

**Comment by idoaizenshtein** [comment]
Thank's.
