### ISSUE TITLE
Font size issue in v0.14.0

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#4717]
* NW.js v0.14.0
* Windows 7 x64

I have a simple test app:

```json
{
  "name": "nw-test",
  "main": "index.html",
  "window": {
    "title": "NW Test"
  }
}
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>NW Test</title>
  </head>
  <body>
    <pre><script>
      document.write(JSON.stringify(process.versions, null, '  '));
    </script></pre>
  </body>
</html>
```

Strangely if I open it in the nwjs-sdk, the font size is normal, but in the nwjs-normal the font size is extremely small. Deleting app folder in the user appdata does not fix the issue. The usual Chrome Ctrl++, Ctrl+-, Ctrl+0 don't change the font size in both nw flavors.

**Comment by rogerwang** [comment]
I couldn't reproduce this in my system. Could you please follow https://www.chromium.org/for-testers/enable-logging  and post the log files for both versions?

**Comment by vsemozhetbyt** [comment]
SDK screenshot and debug log:

![sdk](https://cloud.githubusercontent.com/assets/10393198/14524341/88b32c68-0240-11e6-90f0-170f8f2edbf6.png)

[chrome_debug.sdk.txt](https://github.com/nwjs/nw.js/files/218850/chrome_debug.sdk.txt)

Normal screenshot and debug log:

![normal](https://cloud.githubusercontent.com/assets/10393198/14524378/b61d967a-0240-11e6-940e-c4a72e07441e.png)

[chrome_debug.normal.txt](https://github.com/nwjs/nw.js/files/218855/chrome_debug.normal.txt)

**Comment by vsemozhetbyt** [comment]
Command lines (check if I get it right):

...\nwjs-sdk\nw.exe --enable-logging --v=1 ...\test\

...\nwjs\nw.exe --enable-logging --v=1 ...\test\

**Comment by rogerwang** [comment]
Does it happen in 0.13.4?

**Comment by vsemozhetbyt** [comment]
@rogerwang 
0.13.4 is OK.
0.14.1 has the same issue.

**Comment by rogerwang** [comment]
Did you use 'package.json' or 'manifest.json' as the filename for the manifest? And do you have all the files in 'nwjs' directory as we distributed in our official zip file?

**Comment by vsemozhetbyt** [comment]
package.json

I don't remove or add any files from/to distributed zip file after unzipping.

**Comment by wJsJwr** [comment]
Same problem here on Windows 10 x64 with 0.14.x.

**Comment by hooker99** [comment]
Me too: Windows 10 x64 with 0.14.1 (only normal version, sdk is fine)

**Comment by vsemozhetbyt** [comment]
Seems to be fixed in the 0.14.2.

**Comment by rogerwang** [comment]
Yeah. we fixed a related issue #4746 in 0.14.2. glad to see it helps this issue.

**Comment by PriteshGajjar008** [comment]
@rogerwang I am using 0.14.7 and Ctrl++/Ctrl-- not working for my application. Please confirm.

**Comment by rogerwang** [comment]
cc @Christywl

**Comment by Christywl** [comment]
`Ctrl++` and `Ctrl--` don't work on nwjs-sdk-v0.21. But I think it should be another issue, not same with this bug.

**Comment by PriteshGajjar008** [comment]
So you want me to raise new bug?

**Comment by PriteshGajjar008** [comment]
I am using 0.14.7 and it doesn't work on that as well.

**Comment by rogerwang** [comment]
@PriteshGajjar008 It shouldn't be a default behavior. you can set NWWindow.zoomLevel and bind it to the hotkeys.

**Comment by PriteshGajjar008** [comment]
Thanks, got it. I could register this shortcut.
