### ISSUE TITLE
C++ module

### ISSUE THREAD

**Issue by waiting0729** [nwjs/nw.js#4718]
hi,all)I build a C++ module in nodejs,it works well .But in nwjs i require this module ,it occur : Uncaught Error: Module did not self-register. 
my nodejs version is v0.10.21
nwjs version is nwjs-v0.12.3-win-x64
js code:

var hello = require('./hello');
console.log(hello.hello());

c++ code:
#include <node.h> 
using namespace v8; 
Handle<Value> Hello(const Arguments& args) 
	{ 
		HandleScope scope; 
		return scope.Close(String::New("Hello world!")); 
	} 
	void init(Handle<Object> target) 
		{ 
			NODE_SET_METHOD(target, "hello", Hello); 
		} 
	NODE_MODULE(hello, init)
thanks a lot.

**Comment by rogerwang** [comment]
Please try again with 0.13 or later. 0.12 is not supported any more.

**Comment by RohitSharma27** [comment]
@waiting0729  Did you try rebuilding it with nw-gyp before using it in nw? Although you should try nw 0.13 and above.
