### ISSUE TITLE
slimscroll not working in nwjs13.0 above version for Windows

### ISSUE THREAD

**Issue by BarthibanNadar** [nwjs/nw.js#4719]
Hello,

We have uploaded "test.nw" file on the below link. On the test.html file we have included the code for slimscroll bar.
slimscroll bar code works well with nwjs 13.0 for windows 7 and also on the website, but on the nwjs version 13.3, 13.4, 13.5 and 14.0 the scrollbar is visible but it doesn't work as it use to be.
We are unable to drag the slimscroll bar and pull it down or up, but it is working with mouse scroll.
Also we have checked package nwjs 13.0 for slimscroll bar on windows 10 it show same issue, but it works on windows 7

This problem occurs only with nwjs Windows package, MAC package is working fine.

Link:
https://drive.google.com/file/d/0ByDtTMHCU39BSWZjNW9UbFY1MEU/view?usp=sharing

**Comment by BarthibanNadar** [comment]
Hello,

It is working with package "13.0-beta6" version, but it doesn't work with other versions.

**Comment by rogerwang** [comment]
I tried your sample but didn't notice anything wrong ... I thought I didn't fully understand your case then I tried another slimscroll sample and it works well too:

nw.exe --url=http://rocha.la/jQuery-slimScroll

**Comment by BingleBongle** [comment]
Is this a more general problem? In Windows 10, I am finding an issue with the standard vertical scroll bar: it can only be dragged if the cursor is on the left of the scroll bar - go too close to the edge of the window, nothing happens.

Problem occurs with a basic HTML file (some text in the body, no JS or CSS) with NW.js 14.0 and 13.1, but not 12.3.

**Comment by gorelics** [comment]
Hi, the same problem, invisible eventless area around all sides. html and body padding and margin 0px.
![invis_clip_area](https://cloud.githubusercontent.com/assets/7573291/14673015/05d39a6c-0704-11e6-99e8-a5d7537f1190.gif)

**Comment by gorelics** [comment]
Fixed in 14.2 [](https://github.com/nwjs/nw.js/issues/4749)

**Comment by rogerwang** [comment]
Yeah, it should be the same issue. @BarthibanNadar please check with this build

http://dl.nwjs.io/live-build/04-21-2016/2ee30e9-bf774e7-3d8c7fc-c56a187/v0.14.2/

**Comment by BarthibanNadar** [comment]
I have checked and it is working with 14.2. Thank you.
