### ISSUE TITLE
nw.Menu.popup works only once - v0.14.0 SDK - Win x64

### ISSUE THREAD

**Issue by FiatPax** [nwjs/nw.js#4721]
As the title says.

**Comment by rogerwang** [comment]
It works for me. Could you please provide a sample? I was reusing code from #4697

**Comment by FiatPax** [comment]
Yes:

`<html>
<body>
</body>
</html>
<script>
var contextMenu = new nw.Menu()
document.addEventListener('contextmenu', function(event) {
    event.preventDefault();
    contextMenu.popup(event.x, event.y)
});
contextMenu.append(new nw.MenuItem({
    label: 'Boop',
    click: function() {
        console.log('Beep')
    }
}))
</script>`

**Comment by FiatPax** [comment]
Yes: [contextmenu-test.zip](https://github.com/nwjs/nw.js/files/219095/contextmenu-test.zip)

**Comment by FiatPax** [comment]
Interestingly it worked more than once when I tried just now and in the next restart it didn't work more than once.

**Comment by cszucko** [comment]
I'm encountering this issue as well.  If I create a new menu each time (like in #4697) it works fine, but if I try to reuse a menu (like in the example from @FiatPax) `popup()` usually only works once.  I don't encounter the issue on every app launch, but it happens much more frequently than it doesn't.

I checked a few different releases and have not been able to trigger the issue under 0.13.x, but can get it to occur starting from 0.14.0.  I'm running a 64-bit version of Windows 10 and the problem affects both the 32 and 64-bit versions of NW.js.  I also checked to see if it might an issue of `nw.Menu()` vs `gui.Menu()`, but found no difference.

**Comment by timdrub** [comment]
Same here on **Win7** and **Mint 17.3** both with **nw.js 14.2**

All the context menu demos work only after the first click, successive clicks do not.

Furthermore, not sure if this is related. I have a HTML _textarea_ that I update with `document.getElementById("id").textContent`.

This works multiple times as long as I do not change anything in the textarea. Once I click into the form field and change something or delete the whole content, it stops working. If I write the content to the console it is there but the GUI does not get refreshed. Anyone else experiencing this?
