### ISSUE TITLE
Error with packaging app for windows 10 x64

### ISSUE THREAD

**Issue by rom4eg999666** [nwjs/nw.js#4722]
I package my app with nw.js v.0.14.0 and v.0.12.3. For win 10 I have this error: `[0414/135120:ERROR:main_dll_loader_win.cc(134)] Failed to load NW DLL from C:\Users\Roman\Desktop\win64\nw.dll: Не найден указанный модуль. (0x7E)`. When I start my app on Linux or OSX app starts.

**Comment by rogerwang** [comment]
Could you please run it in English locale and post the message of 'Не найден указанный модуль.' ?

**Comment by rom4eg999666** [comment]
Could not find the specified module

**Comment by rom4eg999666** [comment]
I found text of this error in debug.log file.

**Comment by rogerwang** [comment]
Is nw.dll missing in the directory?

**Comment by rom4eg999666** [comment]
No, nw.dll exists in directory.

**Comment by rom4eg999666** [comment]
List of files in directory:
`d3dcompiler_47.dll;
icudtl.dat;
libEGL.dll;
libGLESv2.dll;
natives_blob.bin;
node.dll;
nw.dll;
nw_100_percent.pak;
nw_200_percent.pak;
nw_elf.dll;
resources.pak;
snapshot_blob.bin
app.exe`;

**Comment by rom4eg999666** [comment]
I found this error. In my app I use dns module, when I packed app with this module I have error for win 10, and when I packed app without dns module my app starts on win 10 without problems. Thank you.
