### ISSUE TITLE
[Win/Linux, nw 0.13+] Menu still is visible in fullscreen and cannot be removed once set

### ISSUE THREAD

**Issue by sebadorn** [nwjs/nw.js#4725]
_Windows 7, Windows 10 (both 32bit in a VM) and Linux (Ubuntu 14.04) with NW.js **v0.13.4**:_

The window menu set with `nw.Window.get().menu = myMenu;` is still visible when in fullscreen mode or kiosk mode. As a workaround I tried to temporarily remove the menu when entering fullscreen mode, but `nw.Window.get().menu = null;` didn't change anything.
It's possible to set an empty menu with `nw.Window.get().menu = new nw.Menu({type: 'menubar'})`, but that still leaves the – now empty – menu bar.

 ---

_Only tested on Windows 10 with NW.js **v0.14.0**:_

Clicking a menu item which has a submenu doesn't open the submenu. Nothing happens. Also still visible in fullscreen/kiosk mode.

**Comment by ghostoy** [comment]
@rogerwang @sebadorn  On 0.12.x, the menubar shows in fullscreen on Linux, but doesn't show it on Windows. However neither shown or hidden is defined in the doc or wiki. Some one may need the menubar on full screen mode, and some one may not. So I think it's better to leave the choices, whether to show or hide menubars in full screen mode, to the developers.

Anyway, when set `win.menu = null`, the menubar should disappear on all platforms. I'll try to fix this issue and update the usage of setting `win.menu = null` on the doc site.
