### ISSUE TITLE
new Window not have "global" 0.14 sdk

### ISSUE THREAD

**Issue by nwhead** [nwjs/nw.js#4726]
hello. 
i create new window
```
require('nw.gui').Window.open {new_instance = true or false}
or
nw.Window.open {new_instance = true or false}
```
and new window not have global object. 

is me, very need global object. help me, how to create a new window that she is have global object.

**Comment by RohitSharma27** [comment]
`nw.Window.open("url",{"new_instance":true/false},function(){ })`
should do it.

**Comment by nwhead** [comment]
it's mystic. one time not work another time it work.
thank you

**Comment by nwhead** [comment]
i am find my problem.
`var appdir = nw.__dirname + './app/'` that too easy a location html file.
if use this method, all opened files ok, but in new window not have global object

if  use 
`var appdir = './app/'` then all html file opened ok and new window have global object
