### ISSUE TITLE
如何将新打开的窗口移出屏幕外？

### ISSUE THREAD

**Issue by fanchou** [nwjs/nw.js#4728]
应用场景中需要双屏，两个屏幕显示不同的内容，我能想到的方法是将新的窗口移出屏幕外，想通过这样的方式显示到扩展屏上，但好像新的窗口只能在当前桌面移动，最大只能移动到屏幕边缘。不知道是否有相关的解决方案？

**Comment by rogerwang** [comment]
Will check this issue. Please use English so all users can read it.
