### ISSUE TITLE
GMail crush after load - nw.js 0.14.0.

### ISSUE THREAD

**Issue by tarva** [nwjs/nw.js#4729]
nw.js crushes when called from command line directly to url http://mail.google.com after login and register with google user name. This was issue also in 0.13.3 pre. 

Please find attached dump files with two different gmail accounts.

Tibor

[crash-dumps-reports.zip](https://github.com/nwjs/nw.js/files/221472/crash-dumps-reports.zip)
Read the following before submitting your issue, thank you.

* Use our mailing list to ask questions which don't imply bug or feature request: https://groups.google.com/forum/#!forum/nwjs-general
* State which version are you using
* State which OS version are you running with
* Provide a reproducible case if possible
* Attach the crash dump file if it's a crash: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

Issues meet the checklist above will be processed before those don't.

**Comment by rogerwang** [comment]
Thanks for reporting. I cannot reproduce it but I made a fix according to your crash dump. Will be available in the next nightly build.

**Comment by rogerwang** [comment]
please try again with this build: http://dl.nwjs.io/live-build/04-17-2016/1d8df9b-45ea533-6f7e880-10ab86b

**Comment by tarva** [comment]
Thanks! 
I tried it, and it don't crush with google mail accounts.
Tibor.
