### ISSUE TITLE
Event is not triggerd

### ISSUE THREAD

**Issue by fotoKrille** [nwjs/nw.js#4732]
nw.js v0.13.3
Node v5.10.0
Chromium 49.0.2623.110
Windows 7 64bit

I can not get the events or any event to trigger on main or new window.

```javascript
var gui = require('nw.gui');
var new_win = gui.Window.open('http://www.frysen.nu', {
    kiosk: true
});

new_win.on('new-win-policy', function(frame, url, policy) {
    policy.ignore();
});

new_win.on('navigation', function(frame, url, policy){
    whiteListCheck(url);
});
```

**Comment by sean220** [comment]
Please refer to the API docs for nwjs0.13 [Window](http://docs.nwjs.io/en/latest/References/Window/)

**Comment by rogerwang** [comment]
Yeah. The API is changed a little for opening new windows, see http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#window

**Comment by fotoKrille** [comment]
So this is not possible? Check what the user is navigate on the new window?

```javascript
nw.Window.open('http://www.frysen.nu', {}, function(new_win) {
    new_win.on('navigation', function(a,b,c){
        console.log(a,b,c);
    });
 });
```

**Comment by daniel-j** [comment]
+1
I get no navigation or new-win-policy event callbacks. Other events work.
