### ISSUE TITLE
Multiple NWJS windows/instances

### ISSUE THREAD

**Issue by mato75** [nwjs/nw.js#4733]
I am trying to open multiple NW.js windows/instances, but always only first instance works, the other are closed automatically with log:
App exited with code 0 

My conf:
Port is changing for every instance 9222, 9223,...
````
{ appDir: './nwapp',
  files: './nwapp/**/**',
  platforms: [ 'osx', 'win' ],
  buildDir: './dist',
  buildType: 'versioned',
  version: 'v0.12.3',
  'single-instance': false,
  argv: [ '--remote-debugging-port=9222', '--debug=true' ],
  _: [] }
````

What could be the reason, that the other instances are closed?

**Comment by mato75** [comment]
Ok figured it out, single-instance to false.

**Comment by fritx** [comment]
Accoring to latest docs, nw21, `single-instance` does not work any longer.
Is there any solution?
http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/
http://docs.nwjs.io/en/latest/References/Manifest%20Format/

**Comment by RohitSharma27** [comment]
There can only be a single instance of NW by default. In case you want to run more than one instances then, you can specify different user directory i.e. using --user-dir . Please see the docs to know more about it.

**Comment by remi-grumeau** [comment]
Very old topic but note that if you move an app to a specific screen and close it, Windows remembers on which screen it was and reopens it on the same screen.
