### ISSUE TITLE
webgl black frame

### ISSUE THREAD

**Issue by wzhsunn** [nwjs/nw.js#4740]
Version :nwjs-v0.14.1-win-ia32
OS: win10 

When open 
http://threejs.org/examples/#webgl_loader_collada_keyframe
 the keyframe is black, but it works sometimes and always works in chrome. 
May be it is a bug .

Thank you :)

![2](https://cloud.githubusercontent.com/assets/528348/14606353/7bba55a0-05af-11e6-8a85-4e7bafdd4d0e.png)
![1](https://cloud.githubusercontent.com/assets/528348/14606362/80ae0232-05af-11e6-80a7-05fb44eacadf.png)

**Comment by rogerwang** [comment]
What's the Chrome version of yours?

**Comment by wzhsunn** [comment]
My Chrome version  is  50.0.2661.75 m .

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.21.6. It works well.

**Comment by Christywl** [comment]
close until there is more information
