### ISSUE TITLE
v0.14.1 Invalid path when select application bundles on osx

### ISSUE THREAD

**Issue by pedro-lucas** [nwjs/nw.js#4742]
I'm developing a application that i need to select application / files bundles on osx, but when i select a bundle using <input type="file" accept=".app" /> it will return a path with the zip files of the bundle like this: /var/folders/7_/2cy_hy8s443fvyxv43w9yls80000gn/T/io.nwjs.nw/zip_cache/CCC15035-8A93-4462-B9B8-CC62DB537CF2-32107-00003154761DE0EC.

I just need to get the "real" path and not a zip with the files in bundle.

I made a sample to illustrate the issue. Could you help me @rogerwang ?

**Sample**: https://github.com/pedro-lucas/nwjs-issue-select-bundle-osx

You can reproduce this issue selecting a .app in your /Application directory.

It's a issue on nw.js in osx version.

NW version: 0.14.1
SO: OS X

Thank you!

**Comment by rogerwang** [comment]
I checked your sample. Does it seem to be a bug in the 'node-webkit-fdialogs' you are using?

**Comment by pedro-lucas** [comment]
No it's not. I will put the <input> tag directly in the file index.html.

**Comment by pedro-lucas** [comment]
@rogerwang,

Please, try again. I have changed the sample code.

**Comment by pedro-lucas** [comment]
Maybe there's a issue here: src/browser/file_select_helper_mac.mm

Line: 99

```
BOOL isPackage =
        [[NSWorkspace sharedWorkspace] isFilePackageAtPath:filename];
    if (isPackage && base::DirectoryExists(file_info.local_path)) {
      base::FilePath result = ZipPackage(file_info.local_path);

      if (!result.empty()) {
        temporary_files.push_back(result);
        file_info.local_path = result;
        file_info.file_path = result;
        file_info.display_name.append(".zip");
      }
    }
```

This behavior makes sense to chromium not to nwjs.

Thank you.

**Comment by pedro-lucas** [comment]
@rogerwang will you make the changes in chromium.src or I need to send another pull request to chromium.src? 

Thank you for your attention and I'm sorry about my english.
