### ISSUE TITLE
Window not opening on Windows (8/10)

### ISSUE THREAD

**Issue by phwitti** [nwjs/nw.js#4745]
Using v0.14.1, I can open exactly one nw application only once. This occured on one Windows 8 as well as one Windows 10 PC. The Application does actually open, spawns 3 Processes of which one uses up one core to the full (the other two doing kinda nothing) and does not crash. The Window won't open. (This also happens with running nw.exe without custom application)

If I remove the User Data Folder (AppData\Local\nwjs\User Data) it would work again.
Actually ... I don't have to remove the whole User Data Folder, but, out of the Local State File (see below) it's sufficient to only remove the Bold-Printed part.

`{"browser":{"last_redirect_origin":""},"easy_unlock":{"user_prefs":{"":{"easy_unlock.proximity_required":false}}},"hardware_acceleration_mode_previous":true,"policy":{"last_statistics_update":"13105581731527831"},"profile":{"info_cache":{`**"Default":{"avatar_icon":"chrome://theme/IDR_PROFILE_AVATAR_26","background_apps":false,"gaia_id":"","is_ephemeral":false,"is_omitted_from_profile_list":false,"is_using_default_avatar":true,"is_using_default_name":true,"managed_user_id":"","name":"","user_name":""}**`}},"shutdown":{"num_processes":0,"num_processes_slow":0,"type":0},"startup_metric":{"last_startup_timestamp":"13105583413535694","last_startup_version":"50.0.2661.75","same_version_startup_count":6},"uninstall_metrics":{"installation_date2":"1461108203","launch_count":"6"},"user_experience_metrics":{"low_entropy_source2":7872,"machine_id":12019202,"session_id":5,"stability":{"child_process_crash_count":0,"crash_count":0,"debugger_not_present":6,"execution_phase":700,"exited_cleanly":true,"extension_renderer_crash_count":0,"extension_renderer_failed_launch_count":0,"incomplete_session_end_count":0,"last_timestamp_sec":"1461109818","launch_count":6,"launch_time_sec":"1461109815","page_load_count":0,"renderer_crash_count":0,"renderer_failed_launch_count":0,"renderer_hang_count":0,"session_end_completed":true,"stats_buildtime":"1459659600","stats_version":"50.0.2661.75-64-devel"}},"was":{"restarted":false}}
`

Both PCs this was tested on have no Chrome installed (if this could be important ... to me this seems more like a Chromium issue but one of nw.js).

[This issue could be existing for quite some time now .. seeing some 'Window won't open' reports in the mailing list, but couldn't find a reported bug here (dunno if it should be reported, if it was some chromium issue .. well, now it is.)]

**Comment by rogerwang** [comment]
Could you please upload a sample app?

**Comment by rogerwang** [comment]
Could you please upload the sample data folder?

**Comment by sand123** [comment]
Confirm same behavior. Use 0.14.1 x64 on Win10 with this package.json

`{
  "version": "1.0.2",
  "name": "support",
  "main": "http://support.local",
  "chromium-args": "--process-per-site --no-sandbox --disable-gpu --disable-plugins --disable-transparency --no-proxy-server --user-data-dir='./profile/' --num-raster-threads=1", 
  "nodejs": false,
  "node-remote": "http://*.local",
  "window": {
    "title": "Support tool",
	"toolbar": false,
	"show_in_taskbar": true,
	"show": true,
	"plugin": false,
	"position": "center",
	"width": 1500,
    "height": 800,
	"min_width": 400,
	"min_height": 600,
	"icon":"./app.ico"
  },
  "webkit": {
    "plugin": false,
	"java": false,
	"page-cache": true
  }
}`

**Comment by phwitti** [comment]
Which folder do you mean by sample data folder?

I can reproduce this by simply downloading the newest build for windows x64 and running nw.exe twice -- second time this bug occurs (without creating any custom files/package).

**Comment by sand123** [comment]
In my case:
- I've downloaded and extracted http://dl.nwjs.io/v0.14.1/nwjs-v0.14.1-win-x64.zip
- extract [github.zip](https://github.com/nwjs/nw.js/files/227945/github.zip) to the same folder
- from cmd in folder run `nw.exe .\github` and all worked fine. Window opened, github home page loaded
- close app, ensure that all nw processes exited, run again `nw.exe .\github` - and nothing!
Application window didn't appear, main process load 25% CPU and one child process with args is launched
` --type=crashpad-handler /prefetch:7 --no-rate-limit --database=C:\Users\user\AppData\Local\Crashpad --annotation=channel= --annotation=plat=Win64 --annotation=prod=nwjs --annotation=ver=-devel --handshake-handle=0x178`

Kill process, remove profile directory wich I passwed with `--user-data-dir` - and app works again. But once

**Comment by rogerwang** [comment]
@phwitti I cannot reproduce it, so I need the "User Data Folder (AppData\Local\nwjs\User Data) " in your original report. It should be at the state blocking NW.js start. I'll put it in my disk to reproduce the issue.

**Comment by phwitti** [comment]
Here you go, .. hope it can help you: [nwjs.zip](https://github.com/nwjs/nw.js/files/228668/nwjs.zip)

**Comment by alinnert** [comment]
I'm experiencing the same problem as @phwitti. I've tried it on my PC at work (HP ‒ Win8.1) and two PCs at home (1 Intel NUC, 1 acer notebook ‒ both Win10 ‒ 1x Slow Ring, 1x Fast Ring) › same result everywhere.
Just a shot in the dark but I noticed that @phwitti is from Germany as well as I am. Could it be some kind of localization issue? Other than that the affected systems are very different.

**Comment by artemnikotin** [comment]
Hi, guys. May be this will help:
I could not reproduce the problem, but my manager (from Germany) can. When I got his application data folder, my nwjs application also not opening. Moreover - I removed this folder and rebuild application, but now my machine not opening application window.
P.S.: problem only with windows x64 application version.

**Comment by alinnert** [comment]
I can only test it on one machine right now but this bug seems to be fixed with version 0.14.2 released yesterday. Can you test it again with that version?

**Comment by sand123** [comment]
I have RU locale - and see the same behaviour
Confirm that fixed in 0.14.2

**Comment by artemnikotin** [comment]
Yes, for 0.14.2 works fine for me too.

**Comment by phwitti** [comment]
Yep, also fixed for me in 0.14.2 on all PCs the problem occured on :)

**Comment by ljgww** [comment]
Just to leave a note that this also happened on Win7 Pro - nw.js v0.14.1, Node v5.10.0, Chromium 50.0.2661.75

Main reason for reporting here is knowledge sharing (took me a while to figure out that I am fiddling with wrong data).

 **If one specifies application "name" in package.json, path to local data changes from 'AppData\Local\nwjs\User Data' to AppData\Local\<choosen-name>\User Data** 

Hope this helps someone and save some time.

**Comment by syedmohiseen** [comment]
I've downloaded and extracted http://dl.nwjs.io/v0.14.1/nwjs-v0.14.1 for linux
extract github.zip to the same folder
But when I tried to open nw in that downloaded file I am unable to open.Can u help me where I did wrong.

**Comment by AndreYin** [comment]
Ran into this issue in 2026, found out that I was packaging with a key named "appname" and another key just "name". This somehow made the app open fine for the first time, but after closing and re-opening, nothing happened, just a ghost nwjs process on the task manager. Removing the appname key fixed it.
