### ISSUE TITLE
Weird popup in custom URL protocol

### ISSUE THREAD

**Issue by sand123** [nwjs/nw.js#4746]
I implemented custom URL scheme myapp:// to handle internal links. When you click on such link for the first time, usually browser asks permission to handle custom link protocol. But in NW In 0.14.1 I've got this

![nwscreen](https://cloud.githubusercontent.com/assets/3256430/14664605/d360319e-06e5-11e6-9698-ea8f5ebb56c9.png)

Is it chromium or what?

**Comment by rogerwang** [comment]
Could you please change the system locale to English and make another
screenshot so I can read the message? Thanks.

**Comment by rdtsc** [comment]
@rogerwang: Below is a translated version (from `ru-RU`) of the dialog in question.

![nwjs-ru-dialog-translated](https://cloud.githubusercontent.com/assets/6773893/14674805/c7abc88e-06d3-11e6-8b69-b98981610f7d.png)

Looks like most locale bundles except `en-US` contain these strings (or a localized version of them).

**Russian (ru-RU)**
```bash
~/dev/test/nwjs-v0.14.1-win-x64 $ grep -lri "пожаловать" # "welcome"
locales/ru.pak
```

**French (fr-CA)**
```bash
~/dev/test/nwjs-v0.14.1-win-x64 $ grep -lri "extraterrestre" # "alien"
locales/ca.pak
```

**Comment by rogerwang** [comment]
Looks like the resource string is wrongly mapped to the default names given to a newly created profile:

https://github.com/nwjs/chromium.src/blob/nw14/chrome/app/generated_resources.grd#L10695

Will fix it soon.

**Comment by sand123** [comment]
@rdtsc thanks for screen. I've used URL scheme successfully in 0.13.x branch - with requesting permission on first launch and appropriate alert

**Comment by rogerwang** [comment]
@sand123 could you please provide a sample app?

**Comment by sand123** [comment]
@rogerwang [sample.zip](https://github.com/nwjs/nw.js/files/227995/sample.zip)
Also notice that before running you should register `myapp://` protocol handler - I included sample reg file inside archive with `notepad.exe` as destination app. Otherwise chromium won't do anything on clicking such links

**Comment by rdtsc** [comment]
@rogerwang: Based on @sand123's sample app, the following behavior is observed when testing against v0.14.1 x64:

![nwjs-protocol-handler-dialog-ss](https://cloud.githubusercontent.com/assets/6773893/14677981/f0b3c9f8-06e1-11e6-95f9-c2060fdabb8b.png)

SDK build is on the left, non-SDK (dist) build is on the right. Both instances were launched via: 
```bash
nw.exe --lang=en-GB
```

Looks like all locales other than `en-US` are affected in the non-SDK builds.

**Comment by rogerwang** [comment]
Thanks for the sample & the testing. It's very helpful to the fix.

**Comment by rogerwang** [comment]
The root cause is that there is old locale files on the buid slave for the normal win build.

The locale files built and shipped in normal build are supposed to be only en-US.pak. Developers are supposed to copy locale files they want from SDK build. The old locale files were packaged with the new build. 

For now the workaround is just replacing the pak files from SDK build. After deleting them in the build slave, the next nightly build should be fine.
