### ISSUE TITLE
nwsnapshot sometimes evaluated and sometimes not

### ISSUE THREAD

**Issue by iLeonidze** [nwjs/nw.js#4750]
Hi! I have a very strange bug with my nwsnapshot. I have an [app](https://github.com/iLeonidze/xbooster) and this is launcher. This launcher load the manifest, manifest load binary snapshot, save it and run it. But! When the first run program download snapshot to some path and run it - nothing happened, but when the second run program start this snapshot prom the path successfully. I cant understand the reason. So here the code:
`mkdirs(xbooster_raw_path,null,function(){
    console.log('Checking builds');
    if(file_exists(xbooster_raw_path+'xbooster.bin.version')&&file_exists(xbooster_raw_path+'xbooster.bin')){
        console.log('Loading build version...');
        local_build_version = Number(fs.readFileSync(xbooster_raw_path+'xbooster.bin.version',"utf8"));
    }
    if(isNaN(local_build_version)||local_build_version!==current_build_version){
        console.warn('Seems to be you have an old version, downloading!');
        download('http://kernel.xbooster.ru/kernel.bin',xbooster_raw_path+'xbooster.bin',function(err){
            if(err){
                console.log(err);
                alert(err);
            }
            console.log('You have been updated to the latest version!',current_build_version);
            fs.writeFile(xbooster_raw_path+'xbooster.bin.version',current_build_version,function(err){
                if(err) return alert(err);
                    run_snapshot();
            });
        });
    }else{
        run_snapshot();
    }
});
var download = function(url, dest, cb) {
    var file = fs.createWriteStream(dest);
    var request = http.get(url, function(response) {
        response.pipe(file);
        file.on('finish', function() {
            file.close(cb);
        });
    }).on('error', function(err) {
        fs.unlink(dest);
        if (cb) cb(err.message);
    });
};
function run_snapshot(){
    console.info('Running snapshot...');
    require('nw.gui').Window.get().evalNWBin(null,xbooster_raw_path+'xbooster.bin');
}`

**Comment by iLeonidze** [comment]
Fixed by forced restarting, but the problem is still here

**Comment by rogerwang** [comment]
nwsnapshot is deprecated by nwjc in latest versions, see  http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/  for usage.
