### ISSUE TITLE
Enabling spdy support in nwjs 12.3

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#4752]
Has anyone needed to use spdy with nginx to load content externally ? It seems with spdy enabled, dev tools reports the content still loading over http 1.1. 

I'm assuming newer versions support http 2 by now but seeing spdy support was introduced into chromium since 4 it should work in 41?

**Comment by rogerwang** [comment]
Unfortunately 0.12 is not maintained any more. So close this issue...
