### ISSUE TITLE
Can't prepare project if run gclient with --no-history argument (main problem in gclient_scm.py)

### ISSUE THREAD

**Issue by biaks** [nwjs/nw.js#4753]
I trying to compile nwjs, I do by these instructions http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/

I took the latest versions of nwjs (commit f581ec88844cc8767482e19055820cf1f9e7e7cf) and depot_tools (commit 6f830d75c683dad1905cfc92ce819cdb2e15c75d) from their repositories.

For saving space I run gclient with --no-history argument.
When it tries to prepare nwjs repository, an error occurs.

I found reason for this error:
At first, if I set --no-history argument, gclient run git clone repository with argument --depth=1.
After it, repository stay on the last commit in nwjs repository: origin/master.
And then gclient try to switch branch on origin/nw13 and run command git checkout origin/nw13. But git can't find it.

If gclient run with --no-history argument, the correct branch must be specified in git clone command.

Now it looks like this:
gclient_scm.py:948: git clone some_rep --depth=1
gclient_scm.py:963: git checkout some_branch
ERROR

**Comment by rogerwang** [comment]
This looks like a bug in gclient. You can work around it by commenting out our repos in DEPS file, run gclient, then deal with our repos, and finally run 'gclient runhooks'.

**Comment by nightwend** [comment]
For those interested, I patched gclient to support --no-history with branch.  
```diff
diff --git a/gclient_scm.py b/gclient_scm.py
index 07ca6b8..5884aad 100644
--- a/gclient_scm.py
+++ b/gclient_scm.py
@@ -953,6 +953,10 @@ class GitWrapper(SCMWrapper):
       else:
         # Otherwise, we're just interested in the HEAD. Just use --depth.
         clone_cmd.append('--depth=1')
+        if revision.split('/')[-1]!='master':
+            clone_cmd.append('-b')
+            clone_cmd.append(revision.split('/')[-1])
+            clone_cmd.append('--single-branch')
 
     tmp_dir = tempfile.mkdtemp(
         prefix='_gclient_%s_' % os.path.basename(self.checkout_path),
```
