### ISSUE TITLE
[bug] clipboard.set does not work correctly with russian symbols

### ISSUE THREAD

**Issue by webkitten** [nwjs/nw.js#4754]
nw 0.13, 0.14, Windows 7
`var clipboard = gui.Clipboard.get();`
`clipboard.set('russian text', 'text')`
with nw 0.12 it works, but in new versions dont, it sets incorrect symbols

**Comment by PavelSapachev** [comment]
I have the same problem

**Comment by dr15x86** [comment]
You can test this bug with code
```javascript
var clipboard = gui.Clipboard.get();
clipboard.set('russian text: Превед Медвед', 'text');
```
