### ISSUE TITLE
Node does not work when the manifest field of 'main' is a remote http server url.

### ISSUE THREAD

**Issue by whrool** [nwjs/nw.js#4755]
Version: nwjs v 0.12, 0.13, 0.14

Here is my problem:
A local http server such as 'http://127.0.0.1:8080'
![image](https://cloud.githubusercontent.com/assets/7413974/14705436/1aeeae4e-07ec-11e6-9026-0642ec175e9c.png)

Manifest:
![image](https://cloud.githubusercontent.com/assets/7413974/14705479/5e03cebc-07ec-11e6-9db1-3c9cede9fe7a.png)

And console reported an error as follows:
![image](https://cloud.githubusercontent.com/assets/7413974/14705560/c167c31e-07ec-11e6-822e-8a5198d52ec1.png)

So nwjs does not work with a remote http server ? Or something I missed ?

**Comment by rdtsc** [comment]
This is expected behavior; node execution in remote pages is opt-in. You'll need to set [`node-remote`](https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote) in your manifest to enable this. This field is dangerous, so be as granular as possible when creating your pattern(s).

**Comment by rogerwang** [comment]
close per last comment.

**Comment by whrool** [comment]
@rdtsc Thanks guy
