### ISSUE TITLE
NW 13 / 14 not migrating WEBSQL

### ISSUE THREAD

**Issue by dekker7** [nwjs/nw.js#4757]
Once i open a nwjs12 app with nwjs 13 or 14 all the tables are truncated. 

OS: ubuntu 14.04 x64

**Comment by dekker7** [comment]
I have fixed it by dumping te contents of the websql to a file and reimporting it after. 
If someone wants the code, let me know.

**Comment by mscreenie** [comment]
+1 Have the same issue, no migration from 12 to 14. Have not tested 13.

**Comment by rogerwang** [comment]
This was fixed by 0.15.3. Will be in 0.14.7 too.

**Comment by rogerwang** [comment]
correction: this was just fixed in git and will be available in 0.15.4 and 0.14.7.

**Comment by dekker7** [comment]
Thanks rogerwang
