### ISSUE TITLE
[NW13,14] - nw.App.on("open", ...) doesn't fire  

### ISSUE THREAD

**Issue by bachel** [nwjs/nw.js#4759]
Event nw.App.on("open", console.log.bind(console)) is not fired when app is open again.
I even try nw.App.onOpen.addListener(consle.log.bind(console)) also with no result.
With event "reopen" on Mac it's the same story.

We try that on Mac 10.11 with version nw 0.13.3 and nw 0.14.1.

Can you help us with that? It’s MAJOR drawback for us.

**Comment by bachel** [comment]
This problem only occure on Mac if in package.json your app name is with "." 
example:
{
    "name":"facebook.com",
    "main":"index.html"
}

**Comment by razzbee** [comment]
The onOpen event is not working for me on windows 10 sdk 0.17.4  , the docs says the app needs to be packed but still it doesnt work after packaging it : 
```js
nw.App.on("open",function(args){
  console.log("On Opened Triggered");
});
```
