### ISSUE TITLE
无法使用flash插件

### ISSUE THREAD

**Issue by jamtanghub** [nwjs/nw.js#4760]
按照官方文档将pepflashplayer.dll文件和manifest.json文件放到了nwjs文件夹内，再次启动提示manifest缺少manifest_version描述，我加上后nw无法显示，只在后台运行。
系统环境：win10 64位，nw版本：0.14

**Comment by rogerwang** [comment]
Please use English so all users can read.

**Comment by jamtanghub** [comment]
发送到
