### ISSUE TITLE
window.close() does not use "force" option

### ISSUE THREAD

**Issue by PavelSapachev** [nwjs/nw.js#4761]
By reference, the **window.close()** method has "_force_" option: https://github.com/nwjs/nw.js/wiki/window#windowcloseforce. Current version of NW (and 0.13 too), does not use this option and doing loop when trying to close window.

Here is simple example:
```
var win = nw.Window.get();
win.on('close', function () {
	if (confirm("Do you want to close this window?")) {
		this.close(true);
	}
});
```

**Comment by rogerwang** [comment]
'win.close(true)' should be used because 'this' is not pointing to the object you want ...
