### ISSUE TITLE
Issue playing *some* YouTube videos - DOMException: The play() request was interrupted by a new load request.

### ISSUE THREAD

**Issue by frankhale** [nwjs/nw.js#4762]
nwjs builds:

nwjs 0.14.2
nwjs 0.13.4 
nwjs 0.12.3 
nwjs 0.11.6

All nwjs builds are x64 and ran on Windows 10

I'm seeing an issue with nwjs playing some YouTube videos where as Chrome and Electron have no issues playing the same videos using the YouTube embed iframe or the YouTube iframe API.

Something is causing the following error which seems to occur in the YouTube player API and only happens in nwjs as far as my tests go:

> base.js:4165 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.

I've Googled this error a lot today and cannot find any references or fixes for it. I don't think it's an issue specifically in the YouTube API because the videos in question work fine in Chrome and Electron.

Here is a reproducible test case that shows off the problem:

Once nwjs loads, click the video to play and it will error and not play. The devtools will display the error message above.

index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <title>YouTube Test</title>

    <style>
      #player {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
      }
    </style>

    <script>
      var win = nw.Window.get();

      win.on("loaded", function() {
        win.showDevTools();
      });
    </script>
  </head>
  <body>
    <iframe id="player" src="https://www.youtube.com/embed/D_8y-XX9wM8" frameborder="0" allowfullscreen></iframe>
  </body>
</html>
```

package.json

```json
{
  "name": "yt-test",
  "main": "index.html",
  "window": {
    "toolbar": false,
    "width": 640,
    "height": 400,
    "min_width": 640,
    "min_height": 400
  }
}
```

**Comment by frankhale** [comment]
Here is a screenshot showing the error along with what you see in the embedded YouTube player. This is with the sample code in the original issue above.

![nw-yt-video-playback-error](https://cloud.githubusercontent.com/assets/190154/14758678/1412b896-08d6-11e6-9fd4-d432e961c903.PNG)

**Comment by frankhale** [comment]
Here are a few more YouTube video ID's that cause this problem: K3crNooxyAM, UEqMD-5urik and CgU8VIna5aM

NOTE: The problem only manifests with some YouTube videos. Most videos play fine. Additionally I tested loading pepper flash to see if that would help but it doesn't.

**Comment by frankhale** [comment]
Okay this is related to not having something compiled into ffmpeg.dll perhaps H.264? I dunno, I'm just guessing. I copied the ffmpeg.dll from Electron over the one provided by NWJS and now videos that failed to play are playing.

**Comment by frankhale** [comment]
Possibly related issue: https://github.com/nwjs/nw.js/issues/1835

**Comment by rogerwang** [comment]
See discussion here on concerns about distribution of proprietary codes:
https://github.com/nwjs/nw.js/issues/4492

**Comment by frankhale** [comment]
I wonder how Electron gets away with shipping a more capable ffmpeg. I'm just glad that replacing the ffmpeg.dll with a different one solves my problem. My app is a YouTube player so I need the videos to work.

**Comment by rogerwang** [comment]
@frankhale this question should be submitted to their project. They should have a license to redistribute, or they are violating the license of the codec in question. Either way it doesn't make you or other app developers eligible to redistribute the codec.

**Comment by frankhale** [comment]
Yeah the question I supposed was a rhetorical question.
