### ISSUE TITLE
Information regarding OSX App Store sandboxing regarding file/ folder access

### ISSUE THREAD

**Issue by bowringjb** [nwjs/nw.js#4763]
I'm hoping someone can help shed some light on how to deal with sandboxing when submitting an application to the OSX app store. I have recently published an application which uses nw.js and I'm having some trouble with a few features which require arbitrary file access. In a nutshell my app is an animation tool, something like Flash. The user can create a project file with the app and image assets are imported into the project directory as an animation is created.
It is at this point that i'm running into trouble. My app created a project file (basically just some JSON describing the animation) and the assets are stored in the same folder as the project. This works perfectly in my development environment but fails entirely after the project has been downloaded from the app store, presumably because the sandboxing won't let me access arbitrary files. 
Now my idea for a solution is to have the user select a project directory instead of a project file because i'm sure i've read in the relatively sparse documentation that having the user select a folder should give access to the contents of the folder too.
However...I can't find any reference either in apples documentation or on nw.js that explains if there is anything else I need to do make this all work. Will something like:
<input style="display:none;" id="NewProjectDialog" type="file" nwdirectory />
trigger the OS to grant me access to the folder? For how long? Do I need to keep some kind of reference to the folder to keep accessing it? I'm just not sure.
Which brings me to my final question, is there any way to test how an nw.js application will react once sandboxed? The steps to code sign the app for distribution also seem to leave me with an application that I cannot run until it comes back to me from the app store, which entails all the time it takes for apple to approve an update, and means I have to publish applications to my userbase without knowing whether they will work or not. I can't find a way of testing the sandboxing issues until everything is published and publicly available. Obviously this is less then ideal, so is there a way to test sandboxing *before* publishing?
Thanks for your time and any advice you can offer.

**Comment by rogerwang** [comment]
@ghostoy has been working on this.

**Comment by ghostoy** [comment]
@bowringjb We are working on the MAS flavor build. The sandbox issue will be tracked there and fixed soon. #4556
