### ISSUE TITLE
memory leak when use iframe in my web page on nwjs

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#4765]
hey!

 I found that memory did not released after  the iframe redirect to other src or be removed, 
and the memory of nw progress are aways increasing。 
but this not found when browse my web page in the chrome browser。

is there a memory leak?  if not ,what can i do to aviod this. 

Win7 32/64 bit, and NW version both 0.12.3 / 0.14.1

**Comment by mscreenie** [comment]
Please provide a sample app / case so roger can test

**Comment by mangaga** [comment]
here are my simple demo, sorry that i found the problem not exists on nwjs v0.14.1，just v0.12.3 has the problem when i tested again。

however，i found other problem that when nwjs catched any event from mouse ,the memory will increased  4kb even more, but not released 。

OS:WINDOWS 7 32 bit
& nwjs-sdk-v0.14.1-win-ia32



[Uploading nwjs-sdk-v0.14.1-win-ia32-demo.zip…]()

**Comment by rogerwang** [comment]
Since it's fixed in 0.14 I'll close this issue. For your other problem, please open another issue.
