### ISSUE TITLE
Re-position bug in nwjs14 and nw15

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#4766]
http://www49.zippyshare.com/v/tRLGCGft/file.html

Calling win.setPosition("center") after resize or setMinimumSize does not work. Sample app attached.

OS: Windows 7 Sp1
nwjs 14.2 

```

        var nw = require('nw.gui');
        var win = nw.Window.get();
        var appConfig = {
            "appHeight":500,
            "appWidth":500
        };
                win.setMinimumSize(appConfig["appWidth"],appConfig["appHeight"]);
                win.resizeTo(appConfig["appWidth"],appConfig["appHeight"]);
                win.setPosition("center");
                win.setResizable(true);


```

``````
{
  "name": "Hello-3D-World",
  "version": "1.0.0",
    "chromium-args": "--allow-running-insecure-content --ignore-certificate-errors --enable-usermedia-screen-capturing --allow-http-screen-capture --disable-permissions-bubbles --disable-web-security ", 
  "main": "index.html",
  "window": {
        "fullscreen": false, 
        "height": 180, 
        "resizable": false, 
        "show": true, 
        "always-on-top": false, 
        "frame": false, 
        "kiosk": false, 
        "kiosk": false, 
        "kiosk_emulation": false, 
        "min_height": 100, 
        "visible": true, 
        "as_desktop": false, 
        "min_width": 100, 
        "position": "center", 
        "show_in_taskbar": true, 
        "width": 180
  }

```}
``````

**Comment by mscreenie** [comment]
Getting another bug, this time when I reference the parents appConfig variable from an Iframe. Very weird because from console I can access it and it exists.

I will open another issue as its seperate. Sticking to 12.3 as its most stable in my case.

**Comment by rogerwang** [comment]
It works for me with the latest 0.14 version on win7.

**Comment by mscreenie** [comment]
Tried on win 7 after clearing cache also. Resize and setresizable works find. Window position center does not 

This bit of code doesnt center in dev tools either, only when run twice.
`
                win.resizeTo(500,500);
                win.setPosition("center");
                win.setResizable(true);
`

 I'll try see if I can reproduce inside a VM as I could have some other prefs files I haven't .

**Comment by ddvkid** [comment]
+1 with 0.15.0 on win10
using win.moveTo() as workaround

**Comment by mscreenie** [comment]
I forgot to update this last week, bug still exists. Can be reproduced by just moving the window and running the code in dev tools. Window will not center.

**Comment by mscreenie** [comment]
Still exists in latest 15.4.  win.resizeTo(500,500); break api for some small amount of time.

**Comment by mscreenie** [comment]
setPosition is async which is why this happened.
