### ISSUE TITLE
SQLite3 Nwjs 0.14.2 Binding

### ISSUE THREAD

**Issue by putraxor** [nwjs/nw.js#4767]
**DEAR EVERYONE**
I'm so frustrated of build sqlite3   from source for nwjs (windows 32 bit)
Please help me send the built binding 
**I'M HOPELESS**, PLEEEEEEEASE

**Comment by RohitSharma27** [comment]
Please provide the steps that you are performing and the error that you are getting. A little more info like the node version that you are using would be great.

**Comment by rogerwang** [comment]
Please send questions to our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
