### ISSUE TITLE
nw.exe creates files out of passed arguments

### ISSUE THREAD

**Issue by angufix** [nwjs/nw.js#4768]
## Affected

Versions: 0.13.x, 0.14.2
OS: Windows 7
## Description

Invoking nw.exe on command line and passing an argument without a minus sign before it lets nw exe create a file with the name of the passed argument.
## Reproduce

just test in windows console:
nw thisisatestargument

and search for the file "thisisatestargument" in the app folder

**Comment by SuperGod** [comment]
I have this program too.
I do this befor running nw.exe:

```
copy /b nw.exe+app.nw app.exe 
```

then if I parse arguments to app.exe, it will create new file

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.21.6.
   run `nw.exe abcabc`, no `abcabc` file is created in `nw.exe` folder . 
@angufix , is this issue still reproduced in your environment? I saw you wrote `nw thisisatestargument` in the bug, I also try your cmd, still can't reproduce.

**Comment by rogerwang** [comment]
close until more information is available
