### ISSUE TITLE
crash when call multiple services ajax

### ISSUE THREAD

**Issue by idoaizenshtein** [nwjs/nw.js#4771]
node-webkit crash when call multiple services ajax, When there is a large transferred browser ... You can see it at the bottom of Network tab.
I checked all the versions from 13.0 to 14.2.
Older versions (12.0) do not have any problem of such falls.

**Comment by rogerwang** [comment]
Could you please upload the crash dump? See http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by idoaizenshtein** [comment]
[33b16f65-c326-435b-81bd-ec5ad4c25ebe.dmp.zip](https://github.com/nwjs/nw.js/files/236222/33b16f65-c326-435b-81bd-ec5ad4c25ebe.dmp.zip)

**Comment by idoaizenshtein** [comment]
<img width="1201" alt="screen shot 2016-04-26 at 11 55 44" src="https://cloud.githubusercontent.com/assets/17689180/14812535/42ca40be-0ba6-11e6-8089-5f105151229a.png">

**Comment by idoaizenshtein** [comment]
This is what I see when I try to read the file ... By the way, this is almost always this error ... How can figure out is what exactly caused the problem? The source of the error is almost always the same ....?
How can decode and understand the source of the error?

**Comment by rogerwang** [comment]
It's in the doc if you want to decode it, but it's mostly for NW.js maintainers.

**Comment by idoaizenshtein** [comment]
What I'm doing now through the Visual studio is not enough Decode good?

**Comment by rogerwang** [comment]
@idoaizenshtein the crash is due to out of memory. You would need to check if there is a memory leak in your application by using devtools heap profiler. If you're sure it's not due to leak in your app, please reopen this bug and attach a sample to reproduce.
