### ISSUE TITLE
nw 0.14.2 crashes when calling native module

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#4772]
nw 0.14.2
node v5.9.0
Mac OS X El Capitan
Hi Guys,
I have written a simple native addon which is running asynchronously using libuv's worker thread. When I am running the module using node then it is working all fine. But, when I am trying to run it on "nw 0.14.2", nw crashes and I see the following message on the Console.

>  com.apple.xpc.launchd[1]: (io.nwjs.nw.201632[608]) Service exited with abnormal code: 11

What could be the possible reason? Please help.

**Comment by RohitSharma27** [comment]
You may try to reproduce the issue by running [https://github.com/paulhauner/example-async-node-addon](url) in nw 0.14.2 but remove the "sleep(3)" call.
So, basically it looks like if I don't hold the UV thread for some time then the app crashes.
Even "sleep(1)" is enough. But, without the sleep call, app crashes.
I am really on a tight deadline with my addon. I need a direction to look in to. It will be appreciated.
Thanks.

**Comment by rogerwang** [comment]
Will fix it soon.

**Comment by rogerwang** [comment]
I just tried the example -- it works for me.

btw, my Node is 5.11.0 but it may not be related.

**Comment by RohitSharma27** [comment]
This is what you should do to see the issue.
1. Comment out the  sleep() call in the above mentioned addon's cc file.
2. Inject a file using "inject_js_start" and in that file require the above mentioned module and you will see that when you start the app. It crashes. 
Thanks.

**Comment by RohitSharma27** [comment]
@rogerwang 
You can download the sample app from [https://www.dropbox.com/s/l1jqtcbr4ggy8ut/sampleApp.zip?dl=0](url)
I have commented the "sleep()" call. You'll need to perform `node-gyp configure` and `node-gyp build`.
The app will crash and if I write even "sleep(1)" then it works fine.
Hope it will help you identify the issue.
Thanks.

**Comment by rogerwang** [comment]
I commented the sleep() call, but I didn't do the "inject_js_start". Will check it again.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
