### ISSUE TITLE
Reference to a window after reloading is broken

### ISSUE THREAD

**Issue by franchuk** [nwjs/nw.js#4774]
In my test app i open a window on app start
`nw.Window.open(nw.App.manifest.onlineURL, windowProperties, function (win) {
	        win.on('close', function (shouldQuit) {
	            if (shouldQuit) {
	                nw.App.quit();
	            } else {
	                win.hide()
	            };
	        });
	        nw.App.on('reopen', function () {
	            win.show();
	        });
	        tray.on('click', function () {
	        	win.show();
	        });
            win.window.onload = function (){
                setTimeout(function(){
                    win.window.location.href = nw.App.manifest.onlineURL;
                }, 5000);
            }
	    });`
And i have a Tray click handler.
After reloading the window tray.on('click) does not work. The window is hidden and i do not have any reference to it.

NW 0.14.2 Windows 10 x64.
My test app:
[test_app.zip](https://github.com/nwjs/nw.js/files/236509/test_app.zip)

**Comment by rogerwang** [comment]
close as it duplicates with #4773
