### ISSUE TITLE
app:// with nw.js 0.14.2 

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#4776]
I have a very simple setup, that I was working with for nw.js v0.12.3. 
It no longer works with 0.14.2, so I assumed app:// handling had changed. I was right about that:

> NW.js application is running as a Chrome App internally. All chrome.\* platform APIs and features can be used in NW application now. The default protocol is changed from file:// to chrome-extension://, where the host part of the URL is the generated id. The app:// protocol in 0.12 is replaced by chrome-extension:// protocol.

```
{ "name": "AntiMiner",
  "main": "app://whatever/htmlf/index.html",
  "window": {
    "toolbar": true,
    "fullscreen": false
  }}
```

but just changing app:// to chrome-extension:// does not work. I've found out how simple the solution is now (just use the relative path), but maybe it could be stated a bit more clearly in the documentation?
...
"main": "/htmlf/index.html",
...

**Comment by 823639792** [comment]
how can you do:"main" start with app://? I am using 0.12.3

**Comment by marcgfx** [comment]
"main": "app://whatever/htmlf/index.html" as stated above.
the whatever thing threw me off too, but it worked. If I recall correctly I passed the folder containing htmlf. the solution for 0.14.2 is much better though.
