### ISSUE TITLE
node.js should work in webview

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#4780]
Need to check Node.js within webview

**Comment by frankhale** [comment]
I have a webview in my app that loads a remote page from a server on my local machine. I have specified node-remote in my package.json to enable Node in the remote pages but it looks like Node is not working in the remote pages inside the webview. If I try to require a Node module I get an error saying require is not defined.

**Comment by olamedia** [comment]
> Node frames have following extra capabilities than normal frames:
> - Access Node.js / NW.js APIs
> In NW.js, frames matching ALL of the following criterias will be a node frame:
> - Frames or parent frames NOT in <webview> tag

**Comment by frankhale** [comment]
@olamedia I don't particularly need Node support in my webview in my app but I was checking based on what Roger said above. I'm assuming that it will be desirable to have Node support inside the webview. In my case I want the content I load isolated from any Node support so I'm actually good at the moment.

**Comment by frankhale** [comment]
bump @rogerwang. Any thoughts on this issue? I'm assuming you will enable Node based on the title. It doesn't appear to be currently working at the moment.

**Comment by uselec** [comment]
It's necessary.
The `webview `uses a separate render-process, in contrast to the `iframe`.

**Comment by olamedia** [comment]
@frankhale It is designed to be isolated. Adding node support will break isolation. Why are u trying to break things?

**Comment by frankhale** [comment]
I'm not trying to do anything, look above at Rogers issue, the title clearly says "node.js should work in webview". The question is, did he make a mistake in title?

For me, I don't need Node in my webview and if it was there I'd turn it off for my particular app.

**Comment by darcectech** [comment]
> It's necessary.
The webview uses a separate render-process, in contrast to the iframe.

I agree, simply because of its seperate render-process capability which iframe doesnt offer!

**Comment by frankhale** [comment]
@olamedia having Node in a webview doesn't mean you lose isolation. The Node inside a webview would be in a separate context all it's own and still be isolated.

**Comment by olamedia** [comment]
@frankhale having node means having access to server data. "separate context" does nothing isolated if you can load and use libraries from server, for example fs

**Comment by uselec** [comment]
@olamedia node-context in `webview `can be included at the request of both in `frame` by option

> Use iframe for non-isolated webview.

It is not the same. Iframe uses the parent render-process.

**Comment by olamedia** [comment]
@uselec can u tell me a reason why can u need separate render process that u can't create by node itself?

**Comment by uselec** [comment]
@olamedia, as an example of the browser tab. but if the tabs you have local applications that require node-context, the only way to isolate them render, do it before the proxy node. Also, in browser uses one render-process for host in the same domain, and this could be simulated by using iframes (with nwfaketop and etc) in separate renderers by webview with node-context (for control). The point is that wibview and iframes is DOM-nodes, unlike windows, more opportunities for manipulation.

**Comment by uselec** [comment]
@olamedia also, in the electron (atom-shell) has the opportunity to include node-context in webview, but there is no way to disable node-context in iframe and simulate nwfaketop as nwjs. 

it would be useful to have such opportunities

**Comment by uselec** [comment]
@olamedia I, as a hobby, developing a desktop environment (with extensions instead native apps), is completely based on the nwjs. For example, I really miss such a possibility of isolated render-processes with node integration.

**Comment by frankhale** [comment]
@rogerwang please comment on this, what are your thoughts on the issue you filed? Clearly there are differing views in the community and they won't be resolved until you give your view on this.

**Comment by rogerwang** [comment]
This will be enabled with a flag attribute of the webview tag to turn it on/off.

**Comment by lviggiani** [comment]
Hi, is there any progress on this? I see that it was added to 0.14.x milestone. I'm now on 0.15.4 but I still can't access `require` method within a `<webview>`, nor I see any change to the `<webview>` tag documentation...

**Comment by rogerwang** [comment]
@lviggiani This is still a todo item. 

Currently we have 2 release branches, 0.14.x (LTS) and stable branch (currently 0.15). The 0.14.x tag is used for some tasks to be committed in both branches so you are seeing this in 0.15 as well.

**Comment by mdh-cc** [comment]
Hi,

is there any update on this feature? We are currently using `<webview>` in our project but access to node could be necessary in the upcoming releases. Switching to `<iframe>` could be an option but may lead to other problems, so having this feature would be great.

**Comment by rogerwang** [comment]
@mdh-cc will see this feature after we release the pending work in hand after 0.18.5 release. Thanks.

**Comment by rogerwang** [comment]
update: it is expected to be ready soon within 1-2 weeks.

**Comment by rogerwang** [comment]
This is now supported in the latest nightly build: 

You need to add attribute 'allownw' to the webview tag to turn on Node in the webview.

https://dl.nwjs.io/live-build/01-09-2017/nw19-563bc80-2ff22ca-287bf0e-78766fc/v0.19.5/

**Comment by wadjeroudi** [comment]
@rogerwang Just to be sure to understand. With a remote page loaded in a webview, can I use for example this module https://github.com/bchelli/node-smb2 in my remote page and connect to the local network of the client (creating a local tcp socket) ?

**Comment by rogerwang** [comment]
Yes, as long as with the allownw attribute.

**Comment by wadjeroudi** [comment]
@rogerwang  I'm using nwjs 0.19.5 sdk linux version but node is not available in the webview.
console.log(process.version) returns nothing. Do you have an idea ? (not sure if partition part is need, tried with both).
Here is my sample.

```javascript
// package.json
{
  "name": "myapp",
  "main": "index.html",
  "dependencies": {
    "smb2": "*"
  },
  "webview": {
    "partitions": [
      {
          "name": "trusted*",
          "accessible_resources": ["*"]
      }
    ]
  }
}
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <style type="text/css">
            html, body, webview {
                display: block;
                margin: 0; padding: 0; border: 0;
                width: 100%; height: 100%;
            }
            html, body {
                overflow: hidden;
            }
            webview {
                position: absolute;
                top: 0; left: 0;
            }
        </style>
    </head>
    <body>
	<webview src="http://localhost:3000/" partition="persist:trusted" allownw></webview>
    </body>
</html>
```
