### ISSUE TITLE
chrome app not show window after run

### ISSUE THREAD

**Issue by yunnysunny** [nwjs/nw.js#4782]
As mentioned in [What's new in NW.js v0.13](http://nwjs.io/blog/whats-new-in-0.13/)

> After supporting many chrome.\* APIs, the manifest spec for Chrome Apps are also supported in straightforward way. That means many Chrome Apps can be run directly on NW. Clone the sample apps repository and run one of them with:
> $ /path/to/nw.exe <folder path of the manifest.json file>

I clone the repository and cd to the directroy of `samples\clock`, then ran `/path/to/nw.exe .`.At first , it can show the window, and then i closed it. But when i ran it second time, nothing happended, i could not saw the window, though the process of `nw.exe` could be found in task manager.Then , i tried many times, the problem is still there.

**Comment by yunnysunny** [comment]
I found that nw 0.14.0 has this problem, but when i change to 0.13.1, the problem disappeared.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.21.5. `samples\clock` starts successfully every time.
