### ISSUE TITLE
Issue with chrome-extension, redirect and addOriginAccessWhitelistEntry

### ISSUE THREAD

**Issue by hermesdj** [nwjs/nw.js#4783]
Hello,

I have an issue in an oauth process with NW 0.14.2-sdk

My app opens a new window containing an oauth form. The callback parameter I use is 

`https://my_host:8443/oauth/authorize?response_type=token&client_id=CLIENT_ID&redirect_uri=chrome-extension://cgdaijcidmmjpompcjjjdbojbcijabch/callback.html`

In my application code, I have the following white listing :

`nw.App.addOriginAccessWhitelistEntry('https://my_host:8443', 'chrome-extension', location.host, true);`

(host has been masked)

In my manifest, my main is declared as follow :

`"main": "chrome-extension://cgdaijcidmmjpompcjjjdbojbcijabch/app.html",`

However, when the oauth process trigger the redirect to the redirect_uri, the console shows the following error :

`Denying load of chrome-extension://cgdaijcidmmjpompcjjjdbojbcijabch/callback.html#access_token=TEST_TOKEN&token_type=bearer&expires_in=3600. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.`

This is a migration of 0.12.3 where I was using the app:// protocol to make this work. However it no longer works in 0.14.2.
Does someone has the same issue or help me ?
Thanks you !

**Comment by rogerwang** [comment]
Try to use 'app.html' as 'main'. The host name (app id) of chrome-extension protocol is generated by NW. It could change.

**Comment by hermesdj** [comment]
Hello @rogerwang 

Thank you for the suggestion, I changed the main to put only app.html into it. However, I still have the "Denying Load" error in the window.

This window is opened through nw.Window.open

Can I provide any more information to help resolve this ?

**Comment by rogerwang** [comment]
Yeah. If you can provide a sample which reproduce the issue it would be very helpful.

**Comment by cqusuperyang** [comment]
@hermesdj 
have you solved the problem? I have met the same problem!
Denying load of chrome-extension://ebchibcefakmmaoecabblabaaimgdngm/index.html#code=413469d8096cc44bf61a12b0c9e3aed4. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

**Comment by Christywl** [comment]
@hermesdj , could you please provide a sample to reproduce this issue?
