### ISSUE TITLE
NW0.14.2 There is a BUG, can not be re run after the error

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#4786]
I have made a mistake in the configuration as follows: NW cannot be opened.
`{
  "name": "test2",
  "version": "0.0.1",
  "main": "https://mpkf.weixin.qq.com",
  "inject_js_start" : "start.js",
  "node-remote" :["*"],//Wrong configuration item 

  "window": {
        "icon": "logo.png",
        "width": 1200,
        "height": 768,
        "resizable": false,
        "position": "center",
        "transparent":false,
        "frame": true
    }
}`
Error message as shown below, I have to modify the configuration file is still unable to run, restart the computer can not run the interface.
Because the picture can not be uploaded, so put a link to other places
http://f.xinyisoft.org/482e7b8d8856331cce2f03f2a7e4338b

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.21.6. After modify the `node-remote` configureation, app starts successfully.

**Comment by rogerwang** [comment]
close until more information is available
