### ISSUE TITLE
about   node-remote Please help me

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#4787]
I hope that the HTTP request and HTTPS open link can call the local API NW how to configure
"node-remote" :["*://*/*"],
This configuration is not enough!!!!!
Who knows please give an example, thank you

**Comment by RohitSharma27** [comment]
`"*://*/*"` should do you.
This pattern should match all URL Patterns with http and https schemes, with any valid host and path. I hope it helps.

**Comment by rogerwang** [comment]
Please see https://developer.chrome.com/extensions/match_patterns for patterns

**Comment by phpjishu** [comment]
Thank you @RohitSharma27 ! Thank you @rogerwang

**Comment by phpjishu** [comment]
Please look at this error. My login page is https, I need to jump to a successful landing after an http URL, this time being given! I can not directly upload pictures, I'm sorry, I can only send pictures link http://f.xinyisoft.org/349ef27aed906e056b2e4672f49ef2e3

**Comment by phpjishu** [comment]
@rogerwang 
This is my profile
`{
  "name": "test2",
  "version": "0.0.1",
  "main": "https://mpkf.weixin.qq.com",
  "node-remote" :["*://*/*"],
  "window": {
		"icon": "logo.png",
		"width": 1200,
		"height": 768,
		"resizable": false,
		"position": "center",
		"transparent":false,
		"frame": true
	}
}`
