### ISSUE TITLE
how to open a new window on another display

### ISSUE THREAD

**Issue by fanchou** [nwjs/nw.js#4792]
I have two displays, i just can open a new window on the main display，but how to open a new window on another display

**Comment by bjskistad** [comment]
You would need to check your OS, I believe.

**Comment by phpjishu** [comment]
var win = nw.Window.get();

nw.Window.open('https://github.com/nwjs/nw.js', {x:1024,y:768}, function(new_win) {
  new_win.enterFullscreen();
});

First set the upper left corner of the window that opens to coordinate positioning the second panel, set up after the full-screen window opens, example of x, y can be modified according to the actual situation.

**Comment by rogerwang** [comment]
http://stackoverflow.com/questions/17328295/chrome-packaged-app-and-dual-monitors
