### ISSUE TITLE
Why are nw and window accessible under node.js context?

### ISSUE THREAD

**Issue by chenlucan** [nwjs/nw.js#4793]
Under Mac
nwjs version - nwjs-sdk-v0.14.3-osx-x64

Running in separate context mode, go to Inspect Background Page, I could access all nw, window and even alert objects.
 - nw
   - Object {global: Window, process: process, root: Window, App: Object, Obj: Object…}
 - window
   - Window {external: Object, chrome: Object, document: document, global: Window, process: process…}
 - window.nw
   - Object {global: Window, process: process, root: Window, Window: Object, test: Object…}
 - alert
   - alert() { [native code] }

Question:
Why are nw and window available in node context under separate context mode?
According to this doc: http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#access-browser-and-nwjs-api-in-node-context
window and nw are not supposed to be available.

**Comment by rogerwang** [comment]
Background page has a window object. It has nothing to do with the window shown on screen.

**Comment by chenlucan** [comment]
@rogerwang  thanks.
I mixed these two objects.
