### ISSUE TITLE
Can't seek some Videos

### ISSUE THREAD

**Issue by iteufel** [nwjs/nw.js#4794]
Since nwjs v0.14.0(chromium 50) I can't seek some videos.
If i try seeking to a position using the video element the video jumps back to the beginning.
But after reloading the page in Developer Tools seeking works fine.
I can also load the video without any problems directly from the package.json file.

I have tested it on mac and windows with every nwjs version since v0.14.0.

(I'am using a custom build libffmpeg)

**Comment by frankhale** [comment]
I'd be curious to see if the ffmpeg library that comes with Electron will be any better here. I know it works fine as a custom ffmpeg because I use it. It'd also be nice if you had a small sample app to demonstrate this behavior.

**Comment by frankhale** [comment]
Or maybe give this ffmpeg library a try to see if it fixes the issue:

https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

**Comment by iteufel** [comment]
@frankhale Electron is using Chromium: 49.0.2623.75

The problem appears since NWJS is using Chromium 50

Here is sample app
Please run npm install first to install all dependencies 
[video_test.zip](https://github.com/nwjs/nw.js/files/244304/video_test.zip)

**Comment by frankhale** [comment]
I am definitely using the ffmpeg library from Electron 37.7 successfully in NW.js 0.15 beta1 as well as 0.14.x. I was just mentioning that so you could test it and see if it's doing the same thing as your custom ffmpeg.

**Comment by iteufel** [comment]
@frankhale the Electron 37.7 FFmpeg libs are having the same problem.

**Comment by frankhale** [comment]
I'm not a developer on NW.js just a curious person so I'm gonna run your sample on my machine and see what happens. I thought about using the ffmpeg from Chrome install but looks like Google is no longer building that library, I guess they are statically linking that code now.

**Comment by iteufel** [comment]
I have compiled the Chrome 50.0.2661.94 FFmpeg libs and they are having the same problem.

**Comment by frankhale** [comment]
Yeah I've been playing with your sample for an hour I am seeing exactly what you are seeing. This is a weird one. I wonder since this involves using a custom ffmpeg if the NW.js devs will even look at this issue.

**Comment by iteufel** [comment]
I's a bug in chromium blink 
https://chromium.googlesource.com/chromium/src.git/+/1fed486149cdfb7ad37fe474e3ab78d62cab42db

**Comment by frankhale** [comment]
Interestingly enough I ported your code to Electron 37.8 and the case where it wasn't seekable was fine and working.

**Comment by frankhale** [comment]
But that's because it's still Chrome 49 so maybe not a good test at all.

**Comment by frankhale** [comment]
@iteufel, good job on the Chromium bug find!
