### ISSUE TITLE
Starting new process

### ISSUE THREAD

**Issue by NegativeIQ** [nwjs/nw.js#4795]
How can i start new process but also pass few arguments? For example:
"C:\some.exe" -d val1 -t val2

A working example would be best, but i will take anything :D

**Comment by vsemozhetbyt** [comment]
Have you read the [child_process](https://nodejs.org/api/child_process.html) part?

**Comment by NegativeIQ** [comment]
Yeah i did, anyway i just managed to start my app.
By the way, if someone stumbles on same problem. Use child_process.spawn if you want to pass arguments execFile fails for some reason (and i dont see why)

**Comment by RohitSharma27** [comment]
@NegativeIQ It shouldn't crash. Can you provide a sample of the execFile() code,please?

**Comment by NegativeIQ** [comment]
It doesnt crash, it just fails to pass arguments. (Or im using it the wrong way)
`execFile("\"C:\FilePath\FileName.exe\" -a1 test -a2 test2");`

I also tried using something like these: (With no luck)
`execFile('C:\FilePath\FileName.exe', ['-a1 test','-a2 test2']);`

**Comment by RohitSharma27** [comment]
@NegativeIQ Can you please try this?
`execFile("\"C:\\FilePath\\FileName.exe\"", ['-a1 test','-a2 test2']);`

**Comment by NegativeIQ** [comment]
Already tried using every combination of single and double quotes with and without escaping both double quotes and backslashes so i dont think that will work. But i will try that once i get home. Also im pretty sure its not nw.js problem. Im pretty sure i have done something wrong since i didnt spend much time with JS language. But spawn works like a charm, so it must be checking and fixing my mistake or its just windows bug like with most of the things (I know that there was/is something with shortcuts when you had to quote and escape certain characters).

Like i said when i get home, i will try that and i will copy/paste current working example just in case.

**Comment by vsemozhetbyt** [comment]
Maybe you should consider to pass argument like this: `['-a1', 'test', '-a2', 'test2']`.

**Comment by NegativeIQ** [comment]
`execFile("\"C:\\FilePath\\FileName.exe\"", ['-a1', 'test', '-a2', 'test2']);`
That way just worked, and i also noticed that i used same way with spawn. My guess? Its the way application accepts/reads arguments (but it doesnt make any sense since arguments are supposed to be split by white space - at least as far as i know), or i could be wrong (and probably im) but i dont see where or how, since splitting arguments works and not splitting them does not...

Anyway when i get some time i will create simple CLI in VS just to test and see if its gonna work both ways. But i dont see these as some issue anymore since it works. So, my lesson: SPLIT YOUR ARGUMENTS AND PARAMETERS JUST IN CASE! :D

**Comment by RohitSharma27** [comment]
Interesting. How about you try without splitting your args, the way I suggested and use space as an escape character in both the args or may be combine them too.
