### ISSUE TITLE
menu.popup(x,y) only works once

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#4796]
nw.js 0.14.3 on Ubuntu LTS 14.04 i386

1. Make a simple nw.js app using the simple popup menu code shown here:
http://docs.nwjs.io/en/latest/References/Menu/#synopsis
2. Open the devtools console for the window
3. Type `menu.popup(10, 10)`

Bug: the menu doesn't pop up anymore.

Also-- if you comment out `menu.popup(10, 10);` from the demo code, you can make the menu pop up from the console exactly one time.  Then it won't pop up anymore.

**Comment by FiatPax** [comment]
https://github.com/nwjs/nw.js/issues/4721

**Comment by jonwwilkes** [comment]
Bug happens sporadically, but it isn't consistently reproducible on Windows 7 with version 0.14.3.

**Comment by rogerwang** [comment]
close as duplicated.
