### ISSUE TITLE
Cannot open multiple instances at once

### ISSUE THREAD

**Issue by mato75** [nwjs/nw.js#4797]
Even when single-instance: false, we cannot open multiple nwjs app.

**Comment by Taldrain** [comment]
[single-instance has been deprecated](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#single-instance)

**Comment by mato75** [comment]
So this is no longer possible in new versions, or is there a new setting, that allows multiple instances?

**Comment by Taldrain** [comment]
[it seems possible with `--user-data-dir`](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#manifest-format)
