### ISSUE TITLE
"Releases" on Github doesn't match actual progress?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [nwjs/nw.js#4800]
Compare this: https://github.com/nwjs/nw.js/releases
With this: http://nwjs.io/

Something is odd. The Github "releases" page has v0.14.0 as the latest version, and has it timestamped as only 19 days ago, but the project is at v0.14.3 already, and surely v0.14.0 is much older than 19 days?

**Comment by frankhale** [comment]
It's probably just an oversight that a snapshot of the code was not made the day a release came out.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
Huh?

**Comment by frankhale** [comment]
All of the "Github Releases" under the "Releases" tab are just snapshots of the code. Roger probably forgot to make a snapshot when he made an official release. In other words the releases aren't really tracked using the Github Releases feature.

**Comment by rogerwang** [comment]
We don't use anything with the "release" feature provided by github. Github should provide an option to turn it off to avoid confusions. Last time I checked there is not.
