### ISSUE TITLE
window.print

### ISSUE THREAD

**Issue by UncleCo** [nwjs/nw.js#4801]
In versions 0.14 and 0.14.3 (Ubuntu 14.0.4 32bit) window.print() incorrectly works. There is a stop at a printer choice window. 
There is a message: "The printer is unavailable or set incorrectly. Check it or select another"
In version 0.12 everything works perfectly.

**Comment by rogerwang** [comment]
The extra step is supposed to be there in  the same way as Chrome browser. Is Chrome browser able to detect your printer?

**Comment by UncleCo** [comment]
Hello, Mr. Roger Wang! Yes, the Chrome browser finds my printer and prints. I have a network printer connected via router: 192.168.0.1:9100 -- Ivanov-PolishKonstantin Vyacheslavovich  04.05.2016, 12:26, "Roger Wang" <notifications@github.com>:> The extra step is supposed to be there in the same way as Chrome browser. Chrome browser Is able to detect your printer?>> —> You are receiving this because you authored the thread.> Reply to this email directly or view it on GitHub

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by UncleCo** [comment]
No. More problem didn't appear. Thanks. The subject is closed.
