### ISSUE TITLE
Any errors will lead to a program can not run

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#4803]
I want to listen for events F5 to refresh the page, but once my JS error occurs once, I call this method F5 refresh, all the callback methods can not use! For example socket link
F5 monitor events：
window.onkeyup = function (e){
                if(e.keyCode == '116'){
                    var win = nw.Window.get();
                    win.reloadIgnoringCache()
                }
            }
Socket：
var net = require('net');
var clientSocket = new net.Socket();
clientSocket.on('data',function(data){
    console.log('Data = ',data.toString());
});
clientSocket.on('close', function (e){
    console.log('Close = ',e);
});
clientSocket.on('error', function(e) {
    console.log('Error = ',e);
    clientSocket.destroy();
});
console.log('Connecting!!!'); 
clientSocket.connect('5555', '127.0.0.1', function() {
    console.log('Currently connected!'); 
    //win.reloadIgnoringCache() before the connection can be established,
    //If JS no errors after the execution can still link, but if a mistake happened, you can not connect properly, and I understand that the implementation of this method will reload the entire page.
});

**Comment by Christywl** [comment]
I try this on Linux with nwjs-sdk-v0.24.4. When an error happens, I press F5, the page is reloaded:
![image](https://user-images.githubusercontent.com/20039821/29912946-18b248d2-8e66-11e7-9d2d-a7cb9904a770.png)

**Comment by Christywl** [comment]
close until there is more information
