### ISSUE TITLE
app crash due to sandbox issues

### ISSUE THREAD

**Issue by jpittner** [nwjs/nw.js#4805]
Getting the following in console when trying to load application (nwjs.io 0.14.2). I'm trying to package it for MAS. 

3-5-2016 11:19:21.347 AM sandboxd[51551]: ([6325]) nwjs(6325) deny file-read-data /dev/fd
3-5-2016 11:19:21.353 AM sandboxd[51551]: ([6323]) nwjs(6323) deny mach-lookup org.chromium.crashpad.child_port_handshake.6325.8800375.QKIDRWBGYEZQMVGD
3-5-2016 11:19:21.361 AM sandboxd[51551]: ([6323]) nwjs(6323) deny file-read-data /
3-5-2016 11:19:21.372 AM sandboxd[51551]: ([6323]) nwjs(6323) deny file-read-data /
3-5-2016 11:19:21.382 AM sandboxd[51551]: ([6323]) nwjs(6323) deny file-read-data /
3-5-2016 11:19:21.386 AM sandboxd[51551]: ([6323]) nwjs(6323) deny network-bind /private/var/folders/1w/47h393v5165d_kgmy6cn0cpm0000gp/T/com.me.myapp/.com.me.myapp.WXmedN/SingletonSocket

Signing:

codesign --force --verify --verbose  -s "$identity" --entitlements "$CHILD_PLIST"  $app/Contents/Versions/$HELPER_VERSION/nwjs\ Framework.framework/crashpad_handler
codesign --force --verify --verbose  -s "$identity" --entitlements "$CHILD_PLIST"  $app/Contents/Versions/$HELPER_VERSION/nwjs\ Framework.framework/libnode.dylib
codesign --force --verify --verbose --deep -s "$identity" --entitlements "$CHILD_PLIST"  $app/Contents/Versions/$FRAMEWORK_VERSION/nwjs\ Framework.framework/
codesign --force --verify --verbose  -s "$identity" --entitlements "$CHILD_PLIST"  $app/Contents/Versions/$HELPER_VERSION/nwjs\ Helper.app/

echo "### signing app"
codesign --force --verify --verbose  -s "$identity"  --entitlements "$PARENT_PLIST"  $app

echo "### verifying signature"
codesign -vvv -d "$app"
sudo spctl -a -vvvv "$app" <- NOTE THAT THIS DISPLAYS REJECTED, WITH NO ADDITIONAL INFO.

I'm signing with the 3rd Party Mac Developer Application certificate (valid, not expired).

Entitlements:

    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/> 

with child entitlements inheriting as you'd imagine.

@alexeyst or  @johansatge any ideas?

**Comment by rogerwang** [comment]
We are working on MAS support. Merge this issue with #4556
