### ISSUE TITLE
open remote url , loaded event do not fired!

### ISSUE THREAD

**Issue by denvor** [nwjs/nw.js#4808]
Hi，  I am using nwjs 0.14.3 -win32 sdk version , when I using
window.open to open a local fire , the loaded event is OK
but when open an remote url , the loaded event do not fired. 
code as below:

			nw.Window.open(
				"test.html",
				{},
				function(win) {
					
					win.on('loaded',
						function () {
							alert("loaded!");
						}
					)	
				}
			)
 if url is localfile as test.html , the event is ok.
if I replace "test.html " as "http://www.google.com" , the event won't fired.

**Comment by RohitSharma27** [comment]
Use "https". I guess.

**Comment by rogerwang** [comment]
Merge with #4788 ; This is just fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
Please try with this build: http://dl.nwjs.io/live-build/05-05-2016/nw14-9726928-f31ba84-756e507-24751d8/v0.14.4/
