### ISSUE TITLE
Rendering issue with v0.14.2

### ISSUE THREAD

**Issue by PavelDemyanenko** [nwjs/nw.js#4815]
Hi there,
Using v0.14.2 cause problems in rendering, some elements are hidden from user and become visible only when you touch css property, for example font-weight: 300. Was there any reports with this issue? 
Thank you in advance!
Regards,
Pavel

**Comment by rogerwang** [comment]
Could you please try and compare the same page in Chrome 50 and 0.14.3?

**Comment by rogerwang** [comment]
close until there is more information.
