### ISSUE TITLE
0.14.3 Tray Error: Cannot read property 'menu' of undefined

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#4816]
when i want to use the tray on my web iframe occur this error, but it ok on nw0.12.3.

# error message:
extensions::nw.Tray:146 Uncaught TypeError: Cannot read property 'menu' of undefined

# error position :
Tray.prototype.__defineGetter__('menu', function() {
  return privates(this).menu;
});

# my  code:
    var menu = new nw.Menu({type: 'menubar'});
    var openMenu = new nw.MenuItem({
        label: "open",
        click: function() {
            nw.Window.get().focus();
        }
    });

    var exitMenu = new nw.MenuItem({
        label: "exit",
        click: function() {
            nw.Window.get().focus();
			nw.Window.get().close();
        }
    });

    menu.append(openMenu);
    menu.append(new nw.MenuItem({
        type: "separator"
    }));
    menu.append(exitMenu);
	
	var tray = new nw.Tray({
	        title: 'Tray',
	        icon: './favicon.png',
			tooltip: 'tray',
			menu: menu
	});
	
    //tray.menu = menu;
	//click事件
    tray.on('click',
    function() {
	trayClick();
    });
	
global.myAppTray = tray;

# on my web iframe where error happened:
  var tray = global.myAppTray ;
   if (tray) {
    tray.menu.items[2].click = myfunction;

**Comment by ghostoy** [comment]
@mangaga I can't reproduce the issue with NW.js 0.14.3 on all three platforms. See the sample I tested below.

------

`index.html`:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>tray in frame</title>
</head>
<body>
  <iframe src="iframe.html"></iframe>
  <script>
  var menu = new nw.Menu({type: 'menubar'});
  var openMenu = new nw.MenuItem({
      label: "open",
      click: function() {
          nw.Window.get().focus();
      }
  });

  var exitMenu = new nw.MenuItem({
      label: "exit",
      click: function() {
          nw.Window.get().focus();
          nw.Window.get().close();
      }
  });

  menu.append(openMenu);
  menu.append(new nw.MenuItem({
      type: "separator"
  }));
  menu.append(exitMenu);

  var tray = new nw.Tray({
          title: 'Tray',
          icon: './favicon.png',
          tooltip: 'tray',
          menu: menu
  });

  // tray.menu = menu;
  //click事件
  tray.on('click',
  function() {
    trayClick();
  });
  global.myAppTray = tray;
  </script>
</body>
</html>
```

`iframe.html`:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>iframe</title>
</head>
<body>
  <h1>iframe</h1>
  <script>
    var tray = global.myAppTray;
    if (tray) {
      tray.menu.items[2].click = function() {
        alert('exit');
      };
    }
  </script>
</body>
</html>
```

**Comment by mangaga** [comment]
thank you！  @ghostoy  

I'm sorry I did not clearly described， my iframe page is not a local page， it is a remote page. 
And I create the Tray on my local index.html page after startup the nw.exe，and when finished it will
redirect to my remote website.

package.json : 
{
    "main": "index.html",
    "name": "myApp",
    "node-remote": ["*://localhost/*","*://192.168/*"],
     ...
    "Url" : "http://localhost/remote-index.html"
}

**Comment by mangaga** [comment]
help me! please @ghostoy @rogerwang ，it still not ok on nw0.14.4 & 0.14.5

**Comment by ghostoy** [comment]
@mangaga This issue is because of Tray was garbage collected after navigation, which is similar to #4313. Currently I suggest to create and use tray in background page if your window can be navigated.

You have to get current window in your navigated page (the remote page) and send it to background page by `chrome.extension.getBackgroundPage().currentWindow = window`. Currently it's a workaround due to #4881. Once it's fixed, you will be able to get the window directly in the background page.

**Comment by ghostoy** [comment]
I will document on the usage of `nw.Tray` API in case of navigation.
