### ISSUE TITLE
Error while syncing nw14

### ISSUE THREAD

**Issue by abhijeetk** [nwjs/nw.js#4821]
I want to build nw13 or nw14 branch.
for nw14, In .gclient file I have added
    "url"         : "https://github.com/nwjs/chromium.src.git@origin/nw14",

but while syncing code using gclient sync it is giving error :
I tried gclient sync --force and gclient sync --with_branch_heads also.
```
src/third_party/libjingle/source/talk (ERROR)
----------------------------------------
[0:23:46] Started.

________ running 'git reset --hard HEAD' in 'D:\nw14\src\third_party\libjingle\s
ource\talk'
[0:24:01] HEAD is now at 0619e8b Merge branch 'master' of https://chromium.googl
esource.com/external/webrtc/trunk/talk
[0:24:02] _____ src\third_party\libjingle\source\talk : Attempting rebase onto 0
4170d694b177d0e4b2c4f191daad36e88f765b2...
[0:24:04]
[0:24:04] Rebase produced error output:
fatal: Needed a single revision
Does not point to a valid commit: 04170d694b177d0e4b2c4f191daad36e88f765b2
```

I noticed that the commit hash **04170d694b177d0e4b2c4f191daad36e88f765b2** is not present in https://chromium.googlesource.com/external/webrtc/trunk/talk.git (I manually cloned repo. and searched for 4170d but it is not present).

**Comment by rogerwang** [comment]
Thanks for reporting. But the DEPS file is good. see https://chromium.googlesource.com/chromium/src.git/+/50.0.2661.94/DEPS

**Comment by iteufel** [comment]
@rogerwang i had also some problems syncing the code.

The nw14 DPES file is missing some deps.

https://github.com/nwjs/chromium.src/blob/nw14/DEPS
```
"src/content/nw": "https://github.com/nwjs/nw.js.git@origin/nw14",
"src/third_party/node": "https://github.com/nwjs/node.git@origin/nw14",
"src/v8": "https://github.com/nwjs/v8.git@origin/nw14"
```

**Comment by rogerwang** [comment]
@iteufel please check this for the 3 repos: https://groups.google.com/d/msg/nwjs-dev/cF68Dr-IyNM/GHPgtix4NAAJ

**Comment by abhijeetk** [comment]
I tried syncing code again but same error
```
Error: Command 'git checkout --quiet 04170d694b177d0e4b2c4f191daad36e88f765b2' r
eturned non-zero exit status 128 in D:\nw14_OS\nw14\src\third_party\libjingle\so
urce\talk
fatal: reference is not a tree: 04170d694b177d0e4b2c4f191daad36e88f765b2
```

I noticed that the commit hash 04170d694b177d0e4b2c4f191daad36e88f765b2 is not present in https://chromium.googlesource.com/external/webrtc/trunk/talk.git . Please check once.

**Comment by rogerwang** [comment]
@abhijeetk I think '--with_branch_heads' doesn't work on your side correctly.

**Comment by abhijeetk** [comment]
@rogerwang : I am able to sync code properly. Thanks for Help. Could you please let me know which VS2015 you are using for development (Update 1 or Update 2) . Chromium latest using Update 2, But I am getting some error due to compiler flags while building nwjs. Does chromium version we sre using nw13 is compatible with VS2015 Update 2 ?

**Comment by rogerwang** [comment]
We are using VS2013 in nw14 and VS 2015 update 2 in nw15 branch. 

btw, you can see the build log of official binary here: http://buildbot-master.nwjs.io:8010/waterfall

**Comment by jetiny** [comment]
@rogerwang But what's the build env and steps detail for nw14 & nw14 ? the document 's not good.
