### ISSUE TITLE
Any errors will cause all nodejs callback method fails, this is a big problem.

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#4822]
Any errors will cause all nodejs callback method fails, even if an error occurs and nothing to do, and these problems in the 0.13. * Version does not exist.
E.g:
I happened on a wrong page opens a new window, which is a new socket link, then the link will not correct socket connection callback results and event listeners.

This is very annoying, because I want to load a lot of remote pages, I can not guarantee that other pages of the JS code is absolutely correct!
Very much I like to fix this problem!

@rogerwang

**Comment by phpjishu** [comment]
@rogerwang I wrote an example.
http://f.xinyisoft.org/ab88fb9f11e84fee7bf7763d93a4cf02

**Comment by phpjishu** [comment]
Examples are detailed instructions, please take a look at

**Comment by phpjishu** [comment]
@ghostoy

**Comment by ghostoy** [comment]
@rogerwang @phpjishu I can reproduce this issue. When errors thrown, `process.nextTick` never get called. But browser timers, like `setTimeout`, just work.

This is a minimal case to reproduce.

----
`index.html`:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>callback fail</title>
</head>
<body>
  <button onclick="fail()">fail</button>
  <button onclick="runNextTick()">process.nextTick</button>
  <button onclick="runTimeout()">setTimeout</button>
  <script>
  function fail() {
    funcNotExist();
  }

  function runNextTick() {
    process.nextTick(function() {
      console.log('nextTick');
    });
  }

  function runTimeout() {
    setTimeout(function() {
      console.log('setTimeout');
    }, 10);
  }

  </script>
</body>
</html>
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by phpjishu** [comment]
Will Can you tell me when I could not send version to solve this problem?

**Comment by ghostoy** [comment]
@phpjishu You can try latest live build in http://dl.nwjs.io/, or wait for next release.

**Comment by phpjishu** [comment]
@ghostoy Thank you !
