### ISSUE TITLE
Changing default "AppData" path for <a> with download attribute

### ISSUE THREAD

**Issue by fritx** [nwjs/nw.js#4823]
``` html
<a download="image.png" href="some/url"></a>
```

`C:\Users\fritz.lin\AppData\Local\GT\Downloads`
It could be unfriendly to the user, because it's little deep and relevant.
How can I specify a directory?
Thanks!

https://github.com/nwjs/nw.js/issues/3372#issuecomment-147936759
This workaround works, but seems only for the other usage:

``` html
<input type="file" nwsaveas="" nwworkingdir="" onChange />
```

I've also tried giving an absolute path as filename, but it turns out
`C:\Users\fritz.lin\Documents\picture_1462522221691.png`
=> `C--Users-fritz.lin-Documents-picture_1462522221691.png`

I have both of these usages in my app.

**Comment by matthew-dean** [comment]
@fritx In your "it turns out" example, is that the output file? If so, maybe it's just some string conversion problem?

**Comment by fritx** [comment]
@matthew-dean yeah, seems Chrome had converted `C:\Users\fritz.lin\Documents\picture_1462522221691.png`
to `C--Users-fritz.lin-Documents-picture_1462522221691.png`

absolute path doesn't work for the case?

**Comment by Christywl** [comment]
I tried on Windows with nwjs-sdk-v0.21.5. The default path is `C:\Users\<your name>\Downloads\`. Is this ok for you?

My code: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download2
