### ISSUE TITLE
[OSX v0.14.x] Normal version crashes because of different language file.

### ISSUE THREAD

**Issue by sebadorn** [nwjs/nw.js#4824]
The Windows version seems to be fine, but OSX with NW.js v0.14.x (normal, not SDK) is affected.

How to reproduce:
1. System language has to be something else than english/"en". In my case it's german/"de".
2. Copy from the SDK version the directory `Contents/Resources/de.lproj` into the normal version.
3. Try to start the normal version. The following error will occur:

```
$ ./nwjs-v0.14.4-osx-x64/nwjs.app/Contents/MacOS/nwjs 
[1014:1299:0506/122412:FATAL:chrome_browser_main_mac.mm(114)] Check failed: !loaded_locale.empty(). Default locale could not be found
0   nwjs Framework                      0x0000000110252973 ChromeMain + 4930083
1   nwjs Framework                      0x000000011026a4b9 ChromeMain + 5027177
2   nwjs Framework                      0x000000010fe27420 ChromeMain + 558288
3   nwjs Framework                      0x00000001131c7fe1 _ZN2v88UnlockerD1Ev + 23875985
4   nwjs Framework                      0x00000001131cdacc _ZN2v88UnlockerD1Ev + 23899260
5   nwjs Framework                      0x00000001131c7575 _ZN2v88UnlockerD1Ev + 23873317
6   nwjs Framework                      0x0000000110209288 ChromeMain + 4629304
7   nwjs Framework                      0x0000000110208736 ChromeMain + 4626406
8   nwjs Framework                      0x000000010fd9ef92 ChromeMain + 66
9   nwjs                                0x000000010fd37d52 main + 530
10  nwjs                                0x000000010fd37b34 nwjs + 2868
11  ???                                 0x0000000000000001 0x0 + 1

Trace/BPT trap: 5
```

```
$ ll nwjs-v0.14.4-osx-x64/nwjs.app/Contents/Resources/
total 1528
-rw-------  1 sebadorn  staff  378456  5 Mai 02:02 app.icns
drwxr-xr-x  3 sebadorn  staff     102  6 Mai 12:16 de.lproj
-rw-------  1 sebadorn  staff  378456  5 Mai 02:02 document.icns
drwxr-xr-x  3 sebadorn  staff     102  6 Mai 12:23 en.lproj
drwxr-xr-x  3 sebadorn  staff     102  6 Mai 12:23 io.nwjs.nw.manifest
-rw-------  1 sebadorn  staff   16933  5 Mai 02:02 scripting.sdef
```

Without `de.lproj` it will use `en.lproj` and not cause the error.

**Comment by Ajrarn** [comment]
I tried the same thing with the fr.lproj.

I think that's because there is other language files that you can find  here nwjs.app/Versions/ <chromium-version> / nwj Framework.framework/Resources.

But it will be better to find all the languages in all the Normal versions

**Comment by Ajrarn** [comment]
That's it !
You must copy the locale.pak file from the nwjs.app/Versions/ChromiumVersion/nwj Framework.framework/Resource/de.lproj

But please, give us the normal versions with all the languages...

**Comment by rogerwang** [comment]
The language pak files in SDK build are supposed to be usable in normal build. Is that the case there?

**Comment by Ajrarn** [comment]
Yes you can copy the language files from the SDK version to the normal version.
But to build our apps, we need to download the SDK version and the normal version and proceed to all the copies. 

It will be easier if the languages files were already in the normal version.
But perhaps, there is a good reason to not doing it.

**Comment by silentsakky** [comment]
Any reason for not including language files in normal version?

**Comment by chino23** [comment]
just ran into the same question. What's the reason for omitting them from production?

**Comment by nurishi** [comment]
Had the same issue and the solution by @sebadorn and @Ajrarn saved me. Thank you.
Hope this could be fixed in nwjs build script.

**Comment by fritx** [comment]
+1, after copying `nwjs.app/Contents/Resources/*.lproj` into `MyApp.app/Contents/Resources/`, the `navigator.language` which I'd been using works again.

**Comment by Christywl** [comment]
nwjs-v0.24.4 works fine on Mac. And the language files are included in the normal builds.

**Comment by Christywl** [comment]
close until there is more information
