### ISSUE TITLE
[OSX 0.15.0rc1-SDK] - Adobe Flash Player needs permission, won't load

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#4826]
OSX: El Capitan 10.11.4
NWjs 0.15.0rc1-SDK and also beta2 (haven't tried beta1).
Attached test project worked fine with 0.15.0pre-SDK and builds prior back to 0.13 using PepperFlashPlayer.plugin v 21.0.0.182. I have included the manifest.json from the plugin and the PepperFlash folder is placed in the Internet Plug-Ins folder inside the NWjs binary's nwjs Framework.framework package.
Cheers.

![flashpermission](https://cloud.githubusercontent.com/assets/11089335/15087214/bf36eedc-13de-11e6-9ce0-605dc2a26c52.jpg)
[PepperFlashTest.zip](https://github.com/nwjs/nw.js/files/253084/PepperFlashTest.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
The workaround is to download and use Adobe's pepper flash plugin, change 'x-ppapi-arch' in manifest.json from "mac" to "x64".

The flash plugin loading can be verified with /path/to/nwjs --url='chrome://plugins'
