### ISSUE TITLE
Nice suggestion for Windows 7, 8 and 10

### ISSUE THREAD

**Issue by sourceskyboxer** [nwjs/nw.js#4828]
If you do not want to copy same nw.js 

I have idea nw.js installation - if you do not need to worry via system varioable:

NWPATH = C:\Program Files\nw.js\
PATH = .....;%NWPATH%

A small program checks if %NWPATH% doesn't exist than it need to download and unpack to nw.js installation and applies "NWPATH" for correct "Path to nw.js" and small program protects package nw file

like this

%NWPATH%\nw.exe ( 32 or 64 Bit )

small program:
nw-starter.exe example:
method no protection:
nw-starter ( %NWPATH%\nw.exe myapp.nw ) just not copy /b ...

method protection:
nw-starter ( %NWPATH% §#% ) §#% means binary from nw-starter with nw package like copy /b nw-starter.exe+myapp.nw myapp-starter.exe

I have created small program from powershell but it sees not good. How do I get simple exe if starter reads nw than it will start automatic if nwe package was packed to nw-starter than it doesn't throw error if it load from binary data ( packed nw package )

Is it possible C++ or C#?

Thanks I will support your nice nw.js addon

How does nw-starter detect to current architecture like x86 or x64?

Thanks for understanding and supporting!

PS: For Linux and Mac starter small program should works too .. Why not?
For Mac OS X example $NWPATH = /Applications/Utilities/node-webkit.app/Contents/MacOS/node-webkit
$NWPATH myapp.nw from nw-starter.app ( packed nw package in /Contents/Resources/myapp.nw

For Linux example $NWPATH = /usr/shares/nw.js/
$NWPATH/nw myapp.nw from nw-starter
$NWPATH/nw §#% like Windows binary nw-starter ( Is it possible cat command nw-starter with nw package to own binary? )

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
