### ISSUE TITLE
`require` not working correctly in the `main` file when `node-main` specified

### ISSUE THREAD

**Issue by Bartozzz** [nwjs/nw.js#4830]
- Node version : `v5.10.1`
- OS version : `OS X El Capitan v.10.11.4`
- Nw.js version  : `v0.14.4`

```
├ package.json
├─┬ client/
│ ├── index.html
│ ├── index.js
│ └─┬ scripts/
│   └── bootstrap.jsx
└─┬ server/
  └── server.js
```

The `client` folder contains all the front-end and the `server` contains an API made with `express.js` - it doesn't returns any HTML files, just JSON responses with data.

So basically I have a `package.json` (at this moment I am not running the server) in which I am loading the `client/index.html` file:

```json
{
    "name" : "some_project",
    "main" : "client/index.html",
    "chromium-args" : "--mixed-context"
}
```

... in the `client/index.html` file I am loading the `index.js` file like this:

```html
<script src="index.js"></script>
```

In the `index.js` I am loading a bootstrap file:

```javascript
require( "./scripts/bootstrap.jsx" );
```

Everything is working fine until I am trying to run the server by adding this line to the manifest file:

```
"node-main" : "server/server.js"
```

... when I do so, the servers
 runs properly on `http://localhost:8080`, but when I open the app there's an error: `Uncaught Error: Cannot find module './scripts/bootstrap.jsx'` (in the `index.js` file). I could load the the bootstrap file specifying the full path like this: `require( __dirname + "/client/scripts/bootstrap.jsx" );` but I wonder why the base directory is changing when I specify the `node_main` property. Not sure if this is a bug - I could find nothing in the documentation.

I wonder if there is another way of loading the bootstrap file than giving the full path?

**Comment by 823639792** [comment]
try this：
|-package.json
|-node_modules
      |-bootstrap.jsx
and just require("bootstrap.jsx");
and you will find the module on type "window.process.mainModule"

**Comment by Bartozzz** [comment]
I believe the problem was just that `node-main` changes the context root, so i must provide a path relative to the root, not to the `main` field. Anyway if this is the normal behaviour, you could write a small note about it in the documentation.
