### ISSUE TITLE
Crash on win32 (nwjs 0.14.4) pe_image_reader.cc(144)] CodeView debug entry of unexpected size

### ISSUE THREAD

**Issue by marianoguerra** [nwjs/nw.js#4831]
complete error in debug.txt file:

    [0509/021816:WARNING:pe_image_reader.cc(144)] CodeView debug entry of unexpected size in C:\WINDOWS\system32\OLEACC.dll

may it be related to this?

https://groups.google.com/a/chromium.org/forum/m/#!topic/crashpad-dev/iPBVDxsciGk

attached crash dump

[crash.dmp.zip](https://github.com/nwjs/nw.js/files/254641/crash.dmp.zip)

**Comment by rogerwang** [comment]
The warning may not be related to your crash. What's your OS version? Is dbghelp.dll in the same dir with nw.exe?

**Comment by marianoguerra** [comment]
was windows XP

no, dbghelp.dll wasn't on the build, I added it and now it runs.

is that the expected behavior?

**Comment by rogerwang** [comment]
Yeah, it's needed in XP.
