### ISSUE TITLE
Pepper Flash plugin not loading on Mac nwjs 0.14.4

### ISSUE THREAD

**Issue by futurmat** [nwjs/nw.js#4833]
As stated in the documentation I copied the PepperFlash plugin from 

/Applications/Google Chrome.app/Contents/Versions/50.0.2661.94/Google Chrome Framework.framework/Internet Plug-Ins/PepperFlash/PepperFlashPlayer.plugin

to

nwjs.app/Contents/Versions/50.0.2661.86/nwjs Framework.framework/Internet Plug-Ins/PepperFlash/PepperFlashPlayer.plugin

However, PepperFlash plugin is not loaded in nwjs and I don't see it listed in the list of plugins on chrome://plugins.

I'm using nwjs 0.14.4 SDK, but also tried with the non-SDK build for Mac and running OS X 10.11.3.

Any ideas? Thanks for your help,

Peter

**Comment by Blatman** [comment]
Hi Peter,
You will also need a manifest.json in the folder alongside the PepperFlashPlayer.plugin - the chrome binaries don't seem to include this.
The one I use is in the zip file with #4826
Cheers,
Blane

**Comment by futurmat** [comment]
Hi Blane,

right, now the Flash Plugin is loaded fine! Thanks for your help!
Perhaps this could be stressed in the documentation (http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Flash%20Plugin/) since manifest.json is not included in Chrome's Plugin folder. 

Peter

**Comment by rogerwang** [comment]
I'm closing this issue because 'manifest.json' is mentioned in the document. Thanks.
