### ISSUE TITLE
v0.15.0-rc1 doesn't start on WinXP

### ISSUE THREAD

**Issue by TheStalwart** [nwjs/nw.js#4834]
Trying to start RC1 nw.exe results in error. 
Beta1 was working ok.

---------------------------
nw.exe - Entry Point Not Found
---------------------------
The procedure entry point GetFileInformationByHandleEx could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------

I'm using WinXP SP3 virtual machine from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms

**Comment by vsemozhetbyt** [comment]
It seems 0.15.0-rc1 contains Node.js 6.1.0 and Node.js [ceases support of Windows XP and Vista from v6.0.0](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2016-04-26-version-600-current-jasnell).

**Comment by TheStalwart** [comment]
@vsemozhetbyt that's true, but as i mentioned, nw.js v0.15.0-beta1 containing Node.js v6.0.0 works fine on WinXP.

When nw.js v0.14.0-rc1 broke support for WinXP with another Entry Point Not Found error, @rogerwang promptly fixed it (#4655), so i'm hoping there's a workaround.

In worst case scenario, we'll stay on nw.js v0.14.4 LTS

**Comment by rogerwang** [comment]
I'll look to fix it. But in the long run XP is supported in 0.14.

**Comment by rogerwang** [comment]
It's fixed in this build: http://dl.nwjs.io/live-build/05-11-2016/nw15-0c38002-f9a8ce2-1334c59-64201b8/v0.15.0-rc2/

**Comment by TheStalwart** [comment]
Excellent. Thank you!

**Comment by gearintellix** [comment]
I do same problem in v0.20.x
pls inform
