### ISSUE TITLE
Window event "unmaximize" not triggered upon unmaximize.

### ISSUE THREAD

**Issue by danvim** [nwjs/nw.js#4835]
Specs:

- Windows 10
- NW.JS 0.14.4 SDK

I'm using frameless Window, so I have to create my own window buttons. My app is for Windows OS only and below is my implementation of the idea.

```javascript
$(".win-max-btn").click(function() {
    if (!win.isMaximized)
        win.maximize();
    else
        win.unmaximize();
});
win.on("maximize", function(){
    $(".win-max-btn").find("i").attr("class", "ws ws-restore"); //change the button's icon
    win.isMaximized = true;
});
win.on("unmaximize", function(){
    $(".win-max-btn").find("i").attr("class", "ws ws-maximize"); //change the button's icon
    win.isMaximized = false;
});
```

The problem is The button is changed to the "restore" icon when maximized and `win.isMaximized` is set to true, but when I unmaximize the window through mean of clicking the button or dragging the "window frame area" down, the window is unmaximized but the icon isn't changed because the event `unmaximize` was never triggered.

I have tested with the event `restore` is it did work and was triggered when the window was unmaximized but that isn't what I want.

So if I read the docs right, the event `unmaximize` might be bugged?

**Comment by iteufel** [comment]
NWjs has no `isMaximized` you must use `chrome.app.window.current().isMaximized()`

**Comment by iteufel** [comment]
But you can try using: https://developer.chrome.com/apps/app_window#events

**Comment by danvim** [comment]
@iteufel Thank you for informing me :) `isMaximized` is just my own property I put in because I have no knowledge of `chrome.app.window.current().isMaximized()`.

I think someone should update the docs because I don't see the word deprecated anywhere near.

Thanks again.

**Comment by rogerwang** [comment]
The 'unmaximize' event is deprecated, please see http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by rogerwang** [comment]
There is an error in the document, we'll fix it soon.
