### ISSUE TITLE
window print default settings / custom preview

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4836]
Hi @rogerwang 
Is there any way to load a kind of config on the window.print() method?

The most important would be the possibility to auto select:

Save as PDF (in the printer/destination option)
Options (print header/footer, layout, margins,...)

The best solution would be the possibility to customize / override the print preview GUI & Api methods (https://github.com/nwjs/chromium.src/tree/nw13/chrome/browser/resources/pdf and 
https://github.com/nwjs/chromium.src/tree/nw13/chrome/browser/resources/print_preview),
for example switch the "Print" button in "Save PDF", hidding the printers select/input, and so on...

The main reason of this feature would be to save html pages as file using the chrome rendering process.

**Comment by AndryBray** [comment]
Another good alternative would be some method to pass html and call the pdf preview process returning a datauri pdf content... I hope it could be done in some way. Thank you

**Comment by rogerwang** [comment]
Thanks for the suggestion. There was some discussion in https://github.com/nwjs/nw.js/issues/1263#issuecomment-205197124 for nw13 on this. I'm merging this issue with it. Please post your idea there and we'll continue the discussion.
