### ISSUE TITLE
Disabling DEVTOOLS in SDK build for using NACL functionalities without NACL specific build

### ISSUE THREAD

**Issue by armoret** [nwjs/nw.js#4839]
Background: 
- Starting with NWJS 0.14.4, specific NACL builds are not available any longer but NACL functionalities remain available in SDK build and needed by some rare -but important- applications!

Request:
- To allow to use the NACL (or other) functionalities from SDK build without giving an access  to the dev tools to the users, a flag can be added (in command line ?) and will make the NWJS application behave like if it was started with the standard runtime.
Obviously, it must disable right-click debugger option items and keyboard debugger shortcuts.

Thanks

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
The command line argument is '--disable-devtools'.
