### ISSUE TITLE
cannot use nested node_modules

### ISSUE THREAD

**Issue by shenanigans** [nwjs/nw.js#4849]
Node's processing of the require search path is pretty cool. It allows you to position a `node_modules` directory at any point in your source tree and reach those modules with simple names from anywhere within that parent leaf. Unfortunately this doesn't seem to work fully in nw... **edit** when an html document within the source tree is loaded **/edit** only the `node_modules` directory sibling to the `package.json` is honored **edit** for non-local names.**/edit** 

```
project-root/
    node_modules/
        async/
    src/
        node_modules/
            localUtils.js
        inner-tools/
            iCanSeeLocalUtils.js
        views/
            specialView.html
            specialView.js
```

**edit** When `specialView.html` is loaded, its local javascript file `specialView.js` can only reach `localUtils.js` with the path `../node_modules/localUtils`. If, however, you call `require ("../inner-tools/iCanSeeLocalUtils.js");` then it's no problem for `iCanSeeLocalUtils.js` to call `require ("localUtils");`**/edit**

It's a decent workaround to just not use that node feature and position any source you want to use this way on the root `node_modules` directory. Major downside is managing the `.gitignore`.

Tested using 0.14.5 SDK on win10 amd64... when I noticed the bug I checked what version I was on, whoops 0.12.3, so it's been around a while.

**edit** Sorry the initial bug report was so crap. This time it's only 2:30am so my coherence in human languages is somewhat better. **/edit**

**Comment by Christywl** [comment]
Is this issue still reproduced in the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information

**Comment by shenanigans** [comment]
This bug is no longer an issue, thanks!
