### ISSUE TITLE
Provide alternative to win.reloadDev() to clear all cache and memory leaks

### ISSUE THREAD

**Issue by ermenkov** [nwjs/nw.js#4856]
Since you decided to drop support or just ignore the window's reloadDev() method from 0.13, which did a nice job clearing all Window object memory leaks that are left with the normal reload(), can you provide an alternative to it?

**Comment by mscreenie** [comment]
+1 

I use this heavily in my app and was not aware was removed :( 

I was expecting to migrate this month but there have been many issues left unfixed since 13. 12.3 really and is still the most stable in my eyes.

**Comment by rogerwang** [comment]
reloadDev() was an internal function call to provide the functionality for the 'reload dev' button on the toolbar in 0.12. It's for development purpose and never supposed to be used as a workaround for the issues in your applications. Now the reload dev button in 0.12 has been replaced by "restart app" menu in the context menu in SDK build. I can see to expose it and API. Please track it in #149 

If you find a real bug with the caching or memory leak in NW.js, you'll be more than welcome to open another issue.

**Comment by rogerwang** [comment]
@mscreenie what issues do you have when you migrate to 0.13 and later?

**Comment by mscreenie** [comment]
@rogerwang 

12.3 to 14.x - migration issues with localsql. https://github.com/nwjs/nw.js/issues/4757
if i upgrade this automatically breaks the app for all existing users

basic nwjs apis broken in 14 and 15 - calling resizeTo breaks setResizable, setPosition. https://github.com/nwjs/nw.js/issues/4845#issuecomment-219210966 https://github.com/nwjs/nw.js/issues/4766

ffmpeg - not an issue anymore as it as been worked on a ffmpeg can now be loaded externally without building.  

thanks.
