### ISSUE TITLE
Chage .html to any other ??!

### ISSUE THREAD

**Issue by javidoweb** [nwjs/nw.js#4858]
Hello
For example,If u change index,html to index.abc and open it on chrome (or others) this page run very well.
Is there any way to  nwjs show this files like browsers???
I wnat to change every .html files to anothers in my app.
Thank you

**Comment by farhadt0020** [comment]
It's possible in cordova/phonegap .There is no way for it in nwjs?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
