### ISSUE TITLE
Image Caching on NWJS v0.14.2

### ISSUE THREAD

**Issue by puntubabu** [nwjs/nw.js#4859]
I would like to understand how image caching works on nwjs. I have a server that serves images with an ```age``` header of approximately two weeks. Upon updating the image on the server, nwjs does not pick up the new image. Even after closing and re-opening nw, nw still serves the image from cache.

How does nw load a new image that has been updated on the server, when the image's ```age``` has not expired?

Thanks!

**Comment by iteufel** [comment]
- Please ask questions on the mailing list https://groups.google.com/forum/#!forum/nwjs-general
- Or use Gitter https://gitter.im/nwjs/nw.js

nw.js is based on chromium its caching should be the same.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html

**Comment by rogerwang** [comment]
Yeah, it should be the same with Chromium. If you find it's different, please file an issue or re-open this.
