### ISSUE TITLE
Nwjs generates broken local state file

### ISSUE THREAD

**Issue by Anonymitet** [nwjs/nw.js#4864]
Hi.

When I export my game and run the exe it boots up just fine. But after closing it you can never get it to run again. Not even after a system reboot. No error messages just nothing happens.

We have found that the problem is the local state file generated in appData folder and if you delete it you can start it again. But then the same problem comes back when quitting the game.

Any ideas how to correct the broken local state file that is being generated?

I'm on the 0.14 version of nwjs and the problem occurs on both my computers with win7 x64 and win10 x64. Can't change to a newr version as it is not yet supported in the engine.

I hope to find a solution asap as many users on Steam have complained now when they can't launch the game :(

Thank you in advance!

**Comment by rogerwang** [comment]
Could you please upload an example with the broken state?

**Comment by Anonymitet** [comment]
This is an example project that generates a broken local state file on some computers. Not all seems to be affected but many enough to be a real problem.

So in this example when you run the game it will open for 5sec and then quit which is intended in this example. But when you try again it will never start again on some systems due to the local state file generated in: "user folder/your name/appData/local/NwjsTest/user data/"

**[LocalStateTest Download](https://dl.dropboxusercontent.com/u/100012196/Demos/LocalStateTest.rar)**

**Comment by jorritd** [comment]
This Local State file causes nwjs not to show up on launch

[Local_State.js.zip](https://github.com/nwjs/nw.js/files/343241/Local_State.js.zip)

**Comment by jorritd** [comment]
The 64 bits version works as expected, the problem only exists in the 32 bits version (tested 0.15.3)

**Comment by anchengjian** [comment]
I also encountered this problem. `nwjs-v0.14.7-win-ia32`

**Comment by Christywl** [comment]
@Anonymitet , I can't access your download address, it's invalid. Could you please upload the files again to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available
