### ISSUE TITLE
I am making a browser using nwjs with url hidden. I will deploy the application through citrix xenapp. so every user will open an instance of the application. i expect 200-250 users simultaneously. do i need to take care of anything while doing this? 

### ISSUE THREAD

**Issue by ksubilal** [nwjs/nw.js#4867]
Read the following before submitting your issue, thank you.

* Please use English so all users can read, or the issue will be closed directly.
* Use our mailing list to ask questions which don't imply bug or feature request: https://groups.google.com/forum/#!forum/nwjs-general
* State which version are you using
* State which OS version are you running with
* Provide a reproducible case if possible
* Attach the crash dump file if it's a crash: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

Issues meet the checklist above will be processed before those don't.

**Comment by rogerwang** [comment]
Please post this to our mailing list.

**Comment by frankhale** [comment]
@ksubilal here is a link to the information on where the mailing list is: 

https://github.com/nwjs/nw.js#community
