### ISSUE TITLE
Tab key with Webview Triggering Blur Event

### ISSUE THREAD

**Issue by tsnelson1** [nwjs/nw.js#4869]
Hi,

I found a discrepancy in the use of Tab key focus switching between elements between OS X and Windows using nw.js 14.3, but I think it has been there for quite a while.

All I have is a simple webview element inside my body element, after page loads, simply do <Shift-Tab> followed by <Tab> and a blur event is triggered, but only on OS X (tested on 10.7 and above). I can only see that the document.activeElement is the HTMLBodyElement outside the webview, which I didn't believe is correct, as it doesn't occur on Windows.

My package.json:

```
{
  "name": "AppName",
  "version": "3.x",
  "main": "index.html",
  "window": {
    "toolbar": false,
    "show": false,
    "resizable": false,
    "frame": false,
    "always_on_top": true,
    "visible_on_all_workspaces": true
  }
}
```

My index.html:

```
<html>
<head>
    <script>
        var gui = require('nw.gui');
        var win = gui.Window.get();
        win.enterKioskMode(); <-- added to launch on Windows
        win.focus();
        win.on('blur', function() {alert(document.activeElement.outerHTML);});
    </script>
    <style>
        #webView {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }
    </style>
</head>
<body>
    <webview id="webView" src="https://www.google.com/"></webview>
</body>
</html>
```

Made an adjustment (from my oversimplification) so it will launch on Windows now too.

Thanks!

**Comment by rogerwang** [comment]
What's the behavior in the Chromium/Chrome browser?

**Comment by tsnelson1** [comment]
With the Chrome browser, it deviates even further.On Windows vs. Mac, Windows adds several additional tab key stops (incognito had 3 in addition to the Address Bar as opposed to 2 when not in incognito mode), and OS X appears to have only the extra tab stop for the Address Bar, and no more. Further investigation appears to be that Windows has the additional for cases of Security/Permissions Details, Address Bar, and Manage Passwords, but OS X only has a Tab Stop for the Address Bar.

In my NWJS project, I hide the Address.Bar, Toolbar and Frame, so it doesn't make sense why there is any Tab Stop beyond what is in my loaded Page.

**Comment by Christywl** [comment]
Is this issue reproduced in your side? Here is my result:
Windows 10 on nwjs-sdk-v0.24.4:
![4869-windows](https://user-images.githubusercontent.com/20039821/29809998-c8afca12-8cd0-11e7-90c0-ff6f4d6cfaca.png)
Mac on nwjs-sdk-v0.24.4:
<img width="1280" alt="4869-mac" src="https://user-images.githubusercontent.com/20039821/29810006-d2bb0d78-8cd0-11e7-99ff-877ecade50f0.png">

**Comment by Christywl** [comment]
close until there is more information
