### ISSUE TITLE
Add MS Visual Studio Code to the Real Apps list

### ISSUE THREAD

**Issue by silvioprog** [nwjs/nw.js#4871]
Hello,

VS Code window:

![image](https://cloud.githubusercontent.com/assets/1456829/15432492/d3eb76da-1e84-11e6-835c-0a4add752c33.png)

Please sorry if I'm wrong, but it seems [VS Code](https://code.visualstudio.com/) was done with NW, if so, it should be added on the Real Apps List. See VS Code directory files:

![image](https://cloud.githubusercontent.com/assets/1456829/15432365/4cd11ea2-1e84-11e6-93f0-5ee5a12bb64e.png)

**Q/A from the MS VS Code FAQ:**

***What is the Visual Studio Code?***

Visual Studio Code is a streamlined code editor with support for development operations like debugging, task running and version control. It aims to provide just the tools a developer needs for a quick code-build-debug cycle and leaves more complex workflows to fuller featured IDEs.

***Which OS's are supported?***

VS Code runs on Mac, Linux, and Windows.

Project page: https://code.visualstudio.com/

Thank you!

**Comment by frankhale** [comment]
VS Code uses Electron as it's platform

**Comment by silvioprog** [comment]
You are right. Sorry for the wrong think. ^^'
