### ISSUE TITLE
Build node webkit 0.12.3 but can not find sln and vsproj

### ISSUE THREAD

**Issue by 823639792** [nwjs/nw.js#4874]
When I run gclient sync：

`________ running 'C:\Python27\python.exe src/build/gyp_chromium' in 'G:\node-webkit-12\node-webkit-12'
Enabled Psyco JIT.
Updating projects from gyp files...
Using overrides found in C:\Users\yu\.gyp\include.gypi
Hook ''C:\Python27\python.exe' src/build/gyp_chromium' took 76.21 secs

________ running 'C:\Python27\python.exe src/tools/check_git_config.py --running-as-hook' in 'G:\node-webkit-12\node-webkit-12'
--------------------------------------------------------------------------------
Your gclient solution is not set to use supported git workflow!

Your 'src' solution (in G:\node-webkit-12\node-webkit-12\.gclient):
{ 'deps_file': 'DEPS',
  'managed': True,
  'name': 'src',
  'url': 'https://github.com/nwjs/chromium.src.git@origin/nw12'}

Correct 'src' solution to use git:
{ 'deps_file': 'DEPS',
  'managed': False,
  'name': 'src',
  'url': 'https://chromium.googlesource.com/chromium/src.git'}

Please update your .gclient file ASAP.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
You are using managed gclient mode with git, which was deprecated on 8/22/13:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/n9N5N3JL2_U

It is strongly advised to switch to unmanaged mode. For more information about managed mode and reasons for its deprecation see:
http://www.chromium.org/developers/how-tos/get-the-code/gclient-managed-mode

There's also a large suite of tools to assist managing git checkouts.
See 'man depot_tools' (or read depot_tools/man/html/depot_tools.html).
--------------------------------------------------------------------------------

________ running 'C:\Python27\python.exe src/tools/remove_stale_pyc_files.py src/tools' in 'G:\node-webkit-12\node-webkit-12'
`
and 

set GYP_GENERATORS=msvs,ninja
set GYP_MSVS_VERSION=2013

then run
./build/gyp_chromium content/content.gyp

but not generate any sln and vcproj file。

if I build with  ninja
output：
ninja: build stopped: subcommand failed.

**Comment by rogerwang** [comment]
We build with ninja, not VS. And 0.12.x is not supported any more.
