### ISSUE TITLE
child_process.fork() creates a process that closes instantly...

### ISSUE THREAD

**Issue by flynx** [nwjs/nw.js#4876]
A small self-contained example:
```
var cp = require('child_process')
var child = cp.fork('./child')

child.send({some: 'message'})

``` 

child.js:
```
process.on('message', function(msg){
  console.log('Child got:', msg)
})

```

What we get:
`Uncaught: Error {message: "channel closed"}`

The same code works on node.js

This appears to be related to #4875 (see note)

---
nw.js: 0.14.5
OS: Windows 10

**Comment by rogerwang** [comment]
The forked script should end with '.js'.

btw, we have a test case guarding this feature, see https://github.com/nwjs/nw.js/tree/nw14/test/sanity/child_process

**Comment by flynx** [comment]
OK, but two points:
- this seems to be different to how pure node handles this, though in their docs they do seem to always indicate the ext, so I appear to be a minority here, easy enough to to adapt, so no problem.
- this should not be silent, but this is another issue (#4875)
