### ISSUE TITLE
[How To] Browser-Addons

### ISSUE THREAD

**Issue by Anonyfox** [nwjs/nw.js#488]
Hey, is it possible to include & load some Browser-Plugins in NW? I mean stuff like Adblock & Ghostery for example. Some kind of special directory name in Project, and some lines in the manifest file maybe?

**Comment by milankragujevic** [comment]
Any news, given the overhaul and implementation of new APIs in 0.13..?

**Comment by corwin-of-amber** [comment]
Seems like NWjs supports some chrome.* APIs.
Is that enough to allow running Adblock for example, in an iframe?
