### ISSUE TITLE
Errors from node context not propagated to devtools...

### ISSUE THREAD

**Issue by flynx** [nwjs/nw.js#4882]
Think it is better to do this as a separate issue rather than just mentioning in a note (#4875), plus it might serve as a test case....

**Browser context promise:**
```
new window.Promise(function(a, b){
  throw 'Error'
})
```

This will produce this error, as expected:
`Uncaught (in promise) Error`

**Node context promise:**
```
new global.Promise(function(a, b){
  throw 'Error'
})
```

This will return a promise object but no error is propagated to devtools

---
nw.js: 014.5
OS: Windows 10

**Comment by flynx** [comment]
BTW, I'm also having trouble with `console.log(..)` and friends not printing from node context in some situations while printing in others, but can't yet isolate it into a repeatable and small sample... will post an issue as soon as I catch it.

**Comment by rogerwang** [comment]
It should appear in the background page, where Node context lives by default. You can try to inspect the background page.

**Comment by flynx** [comment]
@rogerwang nope, devtools shows only one (top) context....

it might be because the promise ends too fast for it to stick around or even get displayed, and I'm not fast enough to check this... on the other hand adding a setTimeout/setInterval to the promise to make it live long enough, does not make it visible as a context in devtools...

So, either I'm doing something wrong or this still stands.
