### ISSUE TITLE
Kiosk api on windows and linux

### ISSUE THREAD

**Issue by juzerali** [nwjs/nw.js#489]
I need to create a kiosk with Windows and Linux. Can I have a fully blocking kiosk which doesn't even respond to alt+f4 keys, or asks for password before quitting. Like [opera does it](http://www.opera.com/support/mastering/kiosk/) with its noexit option. I certainly don't expect @rogerwang to support this, although if he does it would be great, otherwise can you point me in the right direction as to how I can go about doing it for myself. A simple _how to_ to begin with will be great.
##

**Comment by juzerali** [comment]
Bumping this to attract some comments.

**Comment by OlsonDev** [comment]
It may not be ideal but you could try running a supplemental application configured to prevent Alt+F4 even going through, or restarting your kiosk app if it crashes. A quick Google search turned up [5 applications](https://www.raymond.cc/blog/prevent-program-closing-disabling-close-button/) that may suffice.

**Comment by juzerali** [comment]
@OlsonDev But that still doesn't stay anything about Linux Desktop Environments. What I've found instead is that I can listen to Alt+F4 keypress via `registerGlobalHotkey` and it disables window close on pressing Alt+F4. Also for anyone interested following code will prevent switching of window.

```
window.onblur = function() { 
  window.focus();
};
```

Next thing I want to disable window keypress and that will complete my Ubuntu based Kiosk application.

**Comment by OlsonDev** [comment]
Fair that that solution isn't cross-platform but as someone who's made commercial kiosk software, I find it odd you don't have full control over the kiosk hardware, OS, software stack. That is, ideally you should only need to worry about one platform. Anyway, g'luck in your endeavors!

**Comment by juzerali** [comment]
Its not about the control, its licencing. I specifically want it to work on Linux based OSes.

**Comment by OlsonDev** [comment]
Sure. Sounds like you're almost there. I don't really get what you mean by "Next thing I want to disable window keypress and that will complete my Ubuntu based Kiosk application." ... you want to disable any key being sent to the window? That sounds too easy..? `preventDefault`, `stopPropagation`, `stopImmediatePropagation`? Like I said, I'm not sure what you meant.

**Comment by juzerali** [comment]
I am creating an application which needs to be run in a sandbox. Nothing should be visible on the screen except for the application. Pressing the window key should not pop up the window menu. Thats what I want to achieve. I don't want to tweak and maintain the OS. I want to achieve this on app level.

**Comment by OlsonDev** [comment]
Oh, you mean the Windows key! I did a little digging; you could try building from source after modifying some of the functionality related to the Shortcut API. Add in the constant for a [Super-key](https://en.wikipedia.org/wiki/Super_key_(keyboard_button)) in [shortcut_constants.cc](https://github.com/nwjs/nw.js/blob/nw13/src/api/shortcut/shortcut_constants.cc) and its corresponding `shortcut_constants.h` file. Also add it to [`shortcut.cc`](https://github.com/nwjs/nw.js/blob/nw13/src/api/shortcut/shortcut.cc), it looks like. Dig through the rest of the code to see if you need to do anything else; that should get you started at least. You'll probably also want to handle the [Menu key](https://en.wikipedia.org/wiki/Menu_key) while you're at it. To get a list of keycodes, check out Chromium's [`keyboard_codes_win.h`](https://chromium.googlesource.com/chromium/chromium/+/master/ui/base/keycodes/keyboard_codes_win.h) and [`keyboard_codes_posix.h`](https://chromium.googlesource.com/chromium/chromium/+/master/ui/base/keycodes/keyboard_codes_posix.h). You're interested in `VKEY_LWIN`, `VKEY_RWIN`, `VKEY_LMENU`, `VKEY_RMENU` and maybe more.
