### ISSUE TITLE
One nw.js browsers spawns two processes

### ISSUE THREAD

**Issue by mato75** [nwjs/nw.js#4890]
When we open a nw.js browser it spawns two processes. Why?

![screen shot 2016-05-24 at 21 39 54](https://cloud.githubusercontent.com/assets/616192/15517840/3d950e48-21fa-11e6-822d-259d02bb8269.png)

**Comment by mato75** [comment]
It looks like it spawns helpers:

![screen shot 2016-05-24 at 21 52 56](https://cloud.githubusercontent.com/assets/616192/15517925/a90701cc-21fa-11e6-962a-4384768a4eaa.png)

Is it possible to disable helpers?

**Comment by rogerwang** [comment]
This is expected since Chromium has multiple process architecture.
