### ISSUE TITLE
Enter 'Backspace' This site can't be reached

### ISSUE THREAD

**Issue by owen-hong** [nwjs/nw.js#4892]
Enter 'Backspace' This site can't be reached
![image](https://cloud.githubusercontent.com/assets/6466628/15534264/9641ef5c-229a-11e6-852f-fd71abd364f0.png)

**Comment by rogerwang** [comment]
Thanks for reporting. Will fix it soon.

**Comment by rogerwang** [comment]
@owen-hong how to reproduce this?

**Comment by owen-hong** [comment]
@rogerwang Open http://localhost:3030 with NW, then click "backspace",u'll see it

**Comment by rogerwang** [comment]
How did you open it? I cannot reproduce...

**Comment by owen-hong** [comment]
My index.html use  "window.location = 'http://localhost:3030';"  open http://localhost:3030

**Comment by rogerwang** [comment]
I still cannot reproduce it with the following sample, does it reproduce for you?

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <title>NW Test</title>
  </head>
  <body>
    <script>
function test2() {
  window.location = 'http://localhost/';
}
    </script>
<button onclick="test2()">test2</button>
  </body>
</html>
```

**Comment by liaozhongwu** [comment]
I met the same problem and solved with the following code.
```js
window.addEventListener('keydown', function (e) {
  if (e.keyCode === 8 && e.target === document.body) {
    e.preventDefault();
  }
});
```

**Comment by owen-hong** [comment]
I solved with the following code.
```javascript
window.addEventListener('keydown', function (e) {
  var type = e.target.type;
  if(e.keyCode==8 && type !== 'text' && type !== 'password' && type !== 'textarea'){
      e.preventDefault();
   }
});
```

**Comment by liaozhongwu** [comment]
would tagName !== 'INPUT' && tagName !== 'TEXTAREA' be better?

**Comment by Christywl** [comment]
I also can't reproduce this issue with `window.location = 'http://localhost:8080/'` on nwjs-sdk-v0.21.5.
