### ISSUE TITLE
close

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#4893]

**Comment by rogerwang** [comment]
could you please attach a full case?

**Comment by idoaizenshtein** [comment]
Yes, I use the software for sending **many services** ... when after all the running I do Reload (**win.reload()**) to program.
After several reload the program closes.
After Monitoring for a long time were the problems I have written, I tested it using the Add / Remove above functions, and the whole time I checked the Profiles tab, the Heap Snapshot and saw a very large increase in any of the above functions.

For the **CPU** checked not only a celeron but also a more powerful computer with I3 processor 4GB RAM, I check this system performance .. and see that it reaches 100% and closed.

**Comment by idoaizenshtein** [comment]
For the CPU problem I resolved that issue ... but, about the leak memory problems remained.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
