### ISSUE TITLE
nw crash with a big array

### ISSUE THREAD

**Issue by asinverse** [nwjs/nw.js#4896]
Dear team,

I've just tested [nwjs-sdk-v0.14.5-win-x64](http://dl.nwjs.io/v0.14.5/nwjs-sdk-v0.14.5-win-x64.zip) on Windows 8.1 with simple test function and it crashed. I don't know how to get the log, but I think you can reproduce this problem. Here is my test:

> function testArray() {
	var t = Date.now();
	var arr = new Array();
	for (var i = 0; i < 100000000; i++) arr.push(i);
	var index = arr.indexOf(50000);
	console.log(index, Date.now() - t);
}

This code runs normally on browser.

Cheers,

**Comment by vsemozhetbyt** [comment]
This is not a NW.js bug, this is default V8 memory limit (~ 1500 MB).

With default settings this code is aborted with 'out of memory' in the Node.js, Google Chrome and NW.js.

To complete such a big array allocation, ~2000 MB is enough in my machine and OS. Try this:

Node.js: `node --max_old_space_size=2048 script.js`

Google Chrome: `chrome.exe --js-flags="--max_old_space_size=2048"`

NW.js: add `"js-flags": "--max_old_space_size=2048"` to the `package.json`.

If 2 GB is not enough, try more.

**Comment by asinverse** [comment]
Thank you @vsemozhetbyt. I got it.
