### ISSUE TITLE
Ability to disable/handle drag and drop events on iframes

### ISSUE THREAD

**Issue by alexandervrs** [nwjs/nw.js#4914]
There should be the ability to disable/handle drag and drop events on iframes. If you have an app that uses iframes, dropping items on it will replace the entire app. In my case, I wanted to grab if the dropped file on the iframe was an html document and set its src attribute to that file.
Assuming "main" is the id of the iframe, the following will have no effect:

```
document.getElementById("main").addEventListener("dragover", function(e){
  e.preventDefault();
  e.stopPropagation();
}, false);

document.getElementById("main").addEventListener("drop", function(e){
  e.preventDefault();
  e.stopPropagation();
}, false);
```

**Comment by iteufel** [comment]
@alexandervrs this should work 

    document.getElementById('main').contentWindow.addEventListener("dragover", function(e){
      e.preventDefault();
      e.stopPropagation();
    }, false)

**Comment by Christywl** [comment]
@alexandervrs , does iteufel's advise work for you? If this issue still reproduces for you, could you please upload a full test to reproduce it?

**Comment by rogerwang** [comment]
close until more information is available.
