### ISSUE TITLE
WebGL shaders (such as bump mapping) not rendered correctly or not rendered at all

### ISSUE THREAD

**Issue by v00d00m4n** [nwjs/nw.js#492]
Making game with Constuct 2 which have built-in node-webkit.
Notticed that bump mapping effect that looks and works find in Chrome and Maxthon does not work at all in exported Node-webkit wrapper and instead texture looks just as flat as without bumpmapping.

Tried to update Constuct 2 bundled version to latest version from site - aint worked.

Tried to put DX9 43 dlls into Folder - aint worked.

Tried to put arguments  --enable-webgl --ignore-gpu-blacklist to package.json - aint worked.
(full arg line, if this might help is this:
--disable-extensions --disable-plugins --disable-internal-flash --disable-popup-blocking --disable-software-rasterizer --enable-gamepad --enable-html5-camera --allow-file-access-from-files --enable-webgl --ignore-gpu-blacklist
)
Tried http://get.webgl.org/ however it shows cude and same results as Chrome and Maxthon browsers, so that means WebGL enabled but doesnt work right or not fully featured in Node-webkit.

Also tried to get WebGL libs from Maxthon and Chrome and replace node-webkit shipped libs with them - aint worked as well.

Googled a little and found more reports like this, which state that "WebGL looks ugly in node-webkit comparing to Chrome and other browsers".

Please fix this issue asap.

**Comment by rogerwang** [comment]
should be fixed with 0.13.0 RC.
