### ISSUE TITLE
http://dl.nwjs.io down?

### ISSUE THREAD

**Issue by eridal** [nwjs/nw.js#4920]
Hi all,

The main website is up, but when attempting to download any file it says:

```
Error connecting to bucket
```
## 

EDIT: ok, seems like while the bucket is down, the links still works.
- http://dl.nwjs.io/v0.15.0/nwjs-v0.15.0-win-ia32.zip
- http://dl.nwjs.io/v0.15.0/nwjs-v0.15.0-win-x64.zip

(taken from [download page](http://nwjs.io/downloads/))
## 

EDIT2

The problem seems to be that `S3Index.prototype.listObjects` returns the _requestUrl_ to be scheme-relative to the current page which is http, instead of https

This line:

``` js
return '//' + bucketName + '.' + bucketEndpoint + '/' + requestUri;
```

Generates:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://nwjs.s3-us-west-2.amazonaws.com/?delimiter=/&prefix=v0.15.0%2F. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by rogerwang** [comment]
It works for me.
