### ISSUE TITLE
<title> specified in main.html persists in window title, even after setting win.title

### ISSUE THREAD

**Issue by applebya** [nwjs/nw.js#4921]
Occurs on nw v0.14.5

Before nw 0.13, this wasn't an issue.

Basically, if you set `<title>old title</title>` in your main.html (let's call this a default title, for when title isn't specified in the `Window.open(...)` params), it can't be overridden by calling `win.title = "new title"`.

I've resolved this in my app by simply removing the HTML `<title>`, but I feel many developers won't implicitly know to do this.

This is my first issue report, let me know if I can improve on anything. Thanks for all the NW love!

**Comment by evshiron** [comment]
I think the `Window.title` is used only when creating a window. BTW the `<title>` can be changed by setting `document.title`.

**Comment by applebya** [comment]
Thanks @evshiron, but setting `win.title` is part of the nw API - which may be called on the nw Window at any time. Yes, setting `document.title` would probably do it if you have `<title>` set in `main.coffee` like I did, but I prefer using nw to do so.

**Comment by conceptualspace** [comment]
issue still occurs when title is passed as an option to Window.open

**Comment by xzhan96** [comment]
@conceptualspace @applebya thanks for reporting the issue.
But I can't reproduce it. Here is my sample code:
```
<!DOCTYPE html>
<html>
<head>
  <title>Context Menu</title>
</head>
<body style="width: 100%; height: 100%;">

<p>'Right click' to show context menu.</p>

<script>
nw.Window.open('test.html', {
    // title: 'The tile',
    width: 600,
    height: 600,
    resizable: false,
    position: 'center',
    focus: true
}, function(win){
  win.title = "new window";
  console.log("new window title = " + win.title); 
});
</script>  
</body>
</html>
```

test.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <title> </title>
</head>
<body >
	<div>new window content
	</div>
</body>
</html>
```

**Comment by conceptualspace** [comment]
thanks @xzhan96 

haven't looked at this in a while but IIRC the issue occurs when passing the title as an option to window.open -- in your example that is commented out

```
nw.Window.open('test.html', {
    title: 'The tile', // set a title here for the new window, and then try setting it via win.title
}
```

**Comment by conceptualspace** [comment]
ok so I was able to replicate this using your example, but you need to have an actual title string in test.html -- the problem does not occur when the title is blank

to be explicit:

when a title is specified via `<title>` tag inside the window HTML, it cannot be overriden via `win.title` (either in the callback as your example or when used as an option in `window.open`)

**Comment by xzhan96** [comment]
#5000

**Comment by xzhan96** [comment]
@conceptualspace this is not a bug
As the document description: 
> "[title](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#window-subfields#title)" is the **default title** of window created by NW.js. 
It can't override the document.title that was set on the loading html, and DOM window object doesn't have title property, so the document.title is the true title to show. Maybe we need update the nwjs's doc.

**Comment by conceptualspace** [comment]
thanks for the update @xzhan96 -- agree a blurb in the docs would be helpful

FYI, when printing, the document title is used as the page header -- it only shows when set via html tag. when setting a title via nw window API the print header will show the URL instead
