### ISSUE TITLE
Why is reloaddev() not supported in v0.14.6?

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#4926]
Just curious. I have an app that we use it on to clear memory out, and we want to upgrade, but not if reloaddev() isn't supported. Thinking of creating a branch and putting it back in for my own implementation, but want to know why it's not supported anymore. Thanks.

**Comment by iteufel** [comment]
@joshterrill you can try `chrome.runtime.reload()`

**Comment by rogerwang** [comment]
close as duplicate of #4856
