### ISSUE TITLE
Not able to compile nw 0.14.6 

### ISSUE THREAD

**Issue by Rishu** [nwjs/nw.js#4928]
@rogerwang We are trying to compile nw 0.14.6 on mac os x 10.11.3 but, it throw 5 error due to new printer api as mentioned below:

`../../content/nw/src/api/nw_window_api.cc:636:27: error: no member named 'EnumeratePrintersOnFileThread' in namespace 'chrome'
      base::Bind(&chrome::EnumeratePrintersOnFileThread,
                  ~~~~~~~~^
../../content/nw/src/api/nw_window_api.cc:662:13: error: no type named 'NWPrintSetCustomPrinting' in namespace 'chrome'
    chrome::NWPrintSetCustomPrinting(auto_print);
    ~~~~~~~~^
../../content/nw/src/api/nw_window_api.cc:664:13: error: no type named 'NWPrintSetDefaultPrinter' in namespace 'chrome'
    chrome::NWPrintSetDefaultPrinter(printer_name);
    ~~~~~~~~^
../../content/nw/src/api/nw_window_api.cc:666:13: error: no member named 'NWPrintSetPDFPath' in namespace 'chrome'
    chrome::NWPrintSetPDFPath(base::FilePath::FromUTF8Unsafe(pdf_path));
    ~~~~~~~~^
../../content/nw/src/api/nw_window_api.cc:667:11: error: no type named 'NWPrintSetOptions' in namespace 'chrome'
  chrome::NWPrintSetOptions(dict);`

It was compiling with same step on nw 0.14.5

**Comment by ghostoy** [comment]
@Rishu This patch contains fixes on Chromium. Did you updated the repo of Chromium?

**Comment by Rishu** [comment]
Thanks for your update. I have tried to fetch chromium update with gclient sync command and got this error. But when i fetch it from source tree, it's working.
