### ISSUE TITLE
SHASUMS256.txt is totally useless

### ISSUE THREAD

**Issue by cookiengineer** [nwjs/nw.js#4930]
Issues I have with the dl.nwjs.io server:

1) latest is no symlink and totally outdated
2) in latest folder in the MD5SUMS are listed files that do NOT exist (like OSX builds)
3) http://dl.nwjs.io/v0.15.1/SHASUMS256.txt has only one entry, which is pointless

Please fix the SHASUMS256 file. Otherwise people will have to download everything manually and you can't build any automated script file for that.

Please take a look at http://nodejs.org/dist/latest/SHASUMS256.txt if you're unsure why SHASUMS files do exist. They are there for a reason, to help build automated checks against the index files, so people can build their own update.sh scripts without downloading everything from the server and having to hash it later locally.

Reason to do this: Saves you guys lots of unnecessary download traffic.

**Comment by cookiengineer** [comment]
This issue is still valid, and still occurs. Manual maintenance of the versions of nwjs have to be done in build scripts - as there is no index file.

**Comment by rogerwang** [comment]
Fixed: https://github.com/nwjs/nw.js#verifying-binaries
