### ISSUE TITLE
Event listener are gone on window.location change

### ISSUE THREAD

**Issue by angufix** [nwjs/nw.js#4931]
Verions  tested 0.13 and  0.14
OS: Win7

Can not listen for window events like 'resize', 'move' after windows.location.href was changed. It seems like all listeners are gone after a new page was loaded. In my project I need to load many different urls in the app. 

**main.html:**
```html
<!DOCTYPE html>
<html>
    <head>
        <script>
            var win = nw.Window.get();
            var text = '';
            
            function test()
            {
                text+= 'test - ';
               
                console.log(text);
                //win.window.location.href='http://github.com';
                win.window.location.assign('http://github.com');
            }
           
            win.window.addEventListener
            (
                'resize',
                test
            );
            
        </script>
    </head>
    <body>        
    </body>
</html>
```
**package.json:**
```
{
  "name": "h2",
  "version": "0.0.1",
  "private": true,
  "main": "main.html",
  "window": {
    "show": true
  }
}
```

**Comment by RohitSharma27** [comment]
@angufix The problem with this approach is that your javascript code gets GCd when you do this. You should write this javascript code in separate file, let's say "app.js" and inject it via "inject_js_start" from package.json. This file will be injected in every window you open. So, this should help you. Cheers.

**Comment by rogerwang** [comment]
Thanks for answering. Yes the code in DOM are supposed to be destroyed upon navigation.

**Comment by angufix** [comment]
@RohitSharma27, @rogerwang thank you very much, I already imagined that the code was GCd and tested the inject-js-start / inject-js-end as it stays in docs, but they do not work, the dashes should be changed to underscores in docs.
