### ISSUE TITLE
nw 0.13.4 sdk silently crush

### ISSUE THREAD

**Issue by dasmike** [nwjs/nw.js#4932]
Hi, I'm using nw 0.13.4 sdk version for my app. This app sometimes chashes without errors. 
Could you give me advise, please, where I can find something which will help me find causer of it?

**Comment by frankhale** [comment]
Can you provide a reproducible sample that demonstrates the crash? Have you tried your app in a later version of NW.js? Do you see the same results there?

**Comment by dasmike** [comment]
I had 0.12.1 version before, and everything was good. but with new version I added second window which often change url.

**Comment by frankhale** [comment]
Have you tried any of the NW.js releases from 0.14.x or 0.15.x? I don't think Roger is going to respond quickly without more information and/or a sample project that reproduces the error.

**Comment by dasmike** [comment]
project is pretty big and I dont know what show you, because I have no idea where is a problem =) and no, I haven't tried latest versions

**Comment by frankhale** [comment]
I'd try a later version of NW.js from 0.14 or 0.15 and see if the crash still happens. Still need more information about what you are actually doing in your app that causes the crash.

**Comment by rogerwang** [comment]
Please try the latest version. If it still crash, please upload the crash dump.
