### ISSUE TITLE
No notifications on Linux

### ISSUE THREAD

**Issue by Sytten** [nwjs/nw.js#4933]
Hi,

I am currently updating Messenger For Desktop from version V0.12.3 to V0.15.1.
Chromium notifications appears fine on Windows, but they don't appear at all on linux (I am on Linux Mint 17.3).
I usually don't have any problems with notifications when I use the chrome browser.
Am I the only one with this problem? 

Thank you.

**Comment by rogerwang** [comment]
It works for me with Debian Gnome. Will check with Mint.

**Comment by Sytten** [comment]
What?!? Lol probably just my computer then -_-

**Comment by Sytten** [comment]
Have you tested it? I will test myself on ubuntu and opensuse during the weekend...

**Comment by Sytten** [comment]
No notification on Ubuntu 15.10 neither. Strange that it works on windows and mac, but the same code doesnt work on linux...

**Comment by cassiodoroVicinetti** [comment]
I'm testing Messenger for Desktop 1.5.0-beta.0 and notifications are working in my GNU/Linux system (Debian 9 "Stretch"). The only difference is that they are not native (libnotify), but they are Chrome-based.

**Comment by Sytten** [comment]
Good to hear, must be a problem with my system then.
Yes I had no choice, but to embrace that new notification system...

**Comment by Sytten** [comment]
Ha never forgot to turn it on haha
