### ISSUE TITLE
Preload tag for webview

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#4936]
Hi,

I have been trying to "inject" Javascript into a webview and after some research, I came to a conclusion that the way to do it is to use the preload tag. The problem is this was referenced in the electron page. Is there anything similar in Nw Js? Because  the official documentation does not mention anything about it anywhere.

Thanks,
Anesu

**Comment by frankhale** [comment]
Webview has executeScript method which may help you. I use this to inject code into a webview in my app and it works well.

https://developer.chrome.com/apps/tags/webview#method-executeScript

**Comment by frankhale** [comment]
If you want to call code inside the webview from outside it then you can inject a script block that appends to the head and has a self executing function using the executeScript method on the webview. This works well for me as I am also doing this in my app.

**Comment by anesuc** [comment]
Awesome, thanks! Will try that soon!

**Comment by frankhale** [comment]
You should be able to close the ticket on your own since you opened it.

**Comment by anesuc** [comment]
Oh, I see, didn't see the "close and comment" below. Ok should be done now.

**Comment by frankhale** [comment]
Have fun @anesuc!

**Comment by anesuc** [comment]
Sorry, I started working on it but I ran into problems. I am trying in replace the default scroll bar with the niceScroll js scroll bar. I have attempted to attatch it to the html tag like this:
"$(document).ready(function() {  
    $("html").niceScroll();
});"

and also set the body tag style height to 100% and overflow to hidden. I think my problem is my attempt to insert the nicescroll script which I tried by either using a local file I had and replacing the code you gave from "code:" to "file:"and also tried to insert this:
"var script = document.createElement("script");
script.src = "..."
document.body.appendChild(script); //Sorry if something is slightly wrong, I did this on another computer I am not logged into, but you get the gist
Still no bar appears. Have any idea?

**Comment by frankhale** [comment]
if you are injecting code after the page is already done maybe the call to document.ready is not happening because it already happened prior to you injecting code. Try calling `$("html").niceScroll();` without using the document.ready function.

**Comment by anesuc** [comment]
Hi, I did that, and I always get the "$" is not defined error. Even if I I just "appended" jquery 2 earlier....

**Comment by frankhale** [comment]
Have you tried to inject a script tag for jQuery into the webview?

**Comment by anesuc** [comment]
Long story short got it resolved by giving a timer after loading jquery  and then a timer after loading nicescroll. One more question, is there a way to add a local script file? That's because when I tried it on an "https" website and I was loading the nicescroll from a non secure connection, it didn't allow it. I am assuming it would allow local files? If not, then I guess I would have to fins a secure host I guess.

**Comment by anesuc** [comment]
Thats the last question I promise XD

**Comment by frankhale** [comment]
I haven't tried local files inside the webview but you may be able to do it.

https://developer.chrome.com/apps/tags/webview#partition
http://docs.nwjs.io/en/latest/References/webview%20Tag/

```
loading local files in webview

Add the following permission to the manifest:
  "webview": {
     "partitions": [
        {
          "name": "trusted",
          "accessible_resources": [ "<all_urls>" ]
        }
     ]
  }

and add ‘partition=”trusted”’ attribute to the webview tag.
```
