### ISSUE TITLE
ReferenceError: nw is not defined after changing windows location

### ISSUE THREAD

**Issue by angufix** [nwjs/nw.js#4937]
Verions  tested 0.13.4 sdk x64  and  0.14 sdk x 64
OS: Win7

Getting the "ReferenceError: nw is not defined" after changing windows location. The strange thing is that in main.html the win variable is properly initialized with the nw.Window.
![untitled](https://cloud.githubusercontent.com/assets/15122959/15790984/0c623124-29d5-11e6-8377-943eb88b6cad.jpg)

**main.html:**

``` html
<!DOCTYPE html>
<html>
    <head>
        <script>
                win.window.location.assign('http://github.com');
        </script>
    </head>
    <body>        
    </body>
</html>
```

**package.json:**

```
{
  "name": "h2",
  "version": "0.0.1",
  "private": true,
  "main": "main.html",
  "window": {
    "show": true
  },
  "inject_js_start":"./lib/winsave.js"
}
```

**./lib/winsave.js**

```
var win       = nw.Window.get();
console.log('test');
```

the winsave.js script stops working

**Comment by RohitSharma27** [comment]
@angufix Add `"node-remote" : "<all_urls>"` in your `package.json`. Check [this](http://docs.nwjs.io/en/latest/References/Manifest%20Format/) out for possible node-remote values.

**Comment by hiwanz** [comment]
@RohitSharma27 thx,it works!

**Comment by hiwanz** [comment]
@RohitSharma27 thx,it works!

**Comment by gazhay** [comment]
This "fix" clobbers the window object.

For example, I have a sourced js file <script src= included that adds a property to the window object.
After adding "node-remote" : "<all_urls>" it is removed. Ok, I can now access nw but the rest of the page now breaks.

Is it really "one or the other" ?
