### ISSUE TITLE
[MAS]I meet the issues of 'Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.'.

### ISSUE THREAD

**Issue by superyyl** [nwjs/nw.js#4939]
I have an App which made with NW.JS 0.12.2.
I want to publish it at Mac App Store(MAS), and I follow the [GUIDELINE](https://github.com/nwjs/nw.js/wiki/Mac-App-Store-%28MAS%29-Submission-Guideline).

I use the [Automatic builds](https://github.com/nwjs/nw.js/wiki/MAS%3A-Packaging-your-app).
Finally I submit the binary with Application Loader.
And I receive an email of 'Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.'

How can I remove these 'Deparecated API Usage'.

Thank you.

**Comment by rogerwang** [comment]
CC @ghostoy

**Comment by ghostoy** [comment]
@superyyl Currently we only support MAS on [0.12.3](http://dl.nwjs.io/v0.12.3/) or [0.14.4](http://dl.nwjs.io/live-build/05-09-2016/nw14-df7f7cf-723666b-756e507-5a26102/v0.14.4/). Make sure you downloaded the one named `nwjs-macappstore-v0.12.3-osx-x64.zip` for 0.12.3 or `nwjs-mas-v0.14.4-osx-x64.zip` for 0.14.4, which were customized for MAS by removing those *Deprecated API*.
For signing and submitting, the [pages on wiki](https://github.com/nwjs/nw.js/wiki/Mac-App-Store-%28MAS%29-Submission-Guideline) are for 0.12.3. For 0.14.4, please see https://groups.google.com/forum/#!topic/nwjs-general/ekyP85rS1Lo.

**Comment by gpetrov** [comment]
@ghostoy any word when MAS will be available for the 0.15.x builds?

**Comment by ghostoy** [comment]
@gpetrov Currently we can successfully sign and upload NW to MAS without errors. But haven't tested whether it can be approved for publication by Apple. Would you like to test if 0.14.4 works for you? Once confirmed, we will end the alpha test and publish MAS builds for LTS and each stable releases.

**Comment by ghostoy** [comment]
@superyyl Do you still experience this issue with 0.14.4 MAS build?
