### ISSUE TITLE
Node should work in Web Workers [$105]

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#494]

**Comment by burakcan** [comment]
What is the status on this?

**Comment by ekelokorpi** [comment]
Any news on this? Or other workarounds?

**Comment by makeusabrew** [comment]
Really interested in this too :) /cc @rogerwang

**Comment by makeusabrew** [comment]
For what it's worth `child_process.fork` worked nicely for me. A lot of the documentation / issues on the subject (including those links) are quite old. I've only tested on Linux and OS X but so far no problems.

**Comment by shabeepk** [comment]
The issue is windows specific.

Thanks,

Regards,

Sharique

**Comment by makeusabrew** [comment]
@shabeepk I've just been able to test things on two windows machines (7 and 8) and `child_process.fork` still worked well. What issues are you experiencing with the latest 0.12.x builds?

**Comment by michahell** [comment]
How does the bountysource thing work? Can I +1 this feature and add 5$ or something?

**Comment by lcb931023** [comment]
1. Any news on this?
2. What's the issue with Windows and `child_process.fork`?

**Comment by makeusabrew** [comment]
@lcb931023 regarding (2): I've not encountered any issues with `child_process.fork` under windows in an app which has been in use since April last year. That's not to say there aren't potential issues somewhere, just that I've yet to encounter any :).

**Comment by lcb931023** [comment]
@makeusabrew haha good to know, thanks, will keep an eye out

**Comment by rogerwang** [comment]
Node.js is now supported in Web Workers. The feature is now in git and will be released with 0.18.4 soon.

If you find any bug about the feature, please do NOT follow up here, file a new issue instead.

**Comment by rogerwang** [comment]
It's built here: http://dl.nwjs.io/live-build/10-28-2016/nw18-64d2849-1d4579d-ae7e389-41840a3/v0.18.4/

You need to use '--enable-node-worker' to turn on this feature.

**Comment by rogerwang** [comment]
docs commit: https://github.com/nwjs/nw.js/commit/226c3566387a461bb4155f0d113d6f39e6c5ad4e
