### ISSUE TITLE
app crash with iframe error (all errors)

### ISSUE THREAD

**Issue by c3g2e** [nwjs/nw.js#4940]
I am use in my project iframe component (nwdisable nwfaketop).
When iframe load js-file in which error (syntax or other error (throw)) application crash(close).

How do that application not crash (close), just write to console about error.

Sorry my English. I try learn.

**Comment by vsemozhetbyt** [comment]
Maybe this is your case: #4912

**Comment by rogerwang** [comment]
Which version are you using?

**Comment by rogerwang** [comment]
close as duplicate. Thanks to @vsemozhetbyt
