### ISSUE TITLE
Where does chromium creates it's domain folder in Mac

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#4941]
Mac OS X
NW v0.14.6
Hi all,
As there are issues with file protocol( i have opened an issue for that #4806), I am trying to use chrome-extension protocol to access local files. But, I am unable to locate domain(that I have specified in my package.json) folder in my application. I am hoping to get domain directory's location and then use relative path to access local files. I have been able to do this for windows but not for Mac.
P.S. : I have been able to go back from domain folder in windows ( i mean using "../") but i don't know if it's allowed in Mac and if it is, i would be able to this only after getting the location of the domain folder in my mac's file system.
Thanks in advance. :)

**Comment by rogerwang** [comment]
What do you mean by "domain folder"? And please post questions to the mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by RohitSharma27** [comment]
I meant the domain field that you can now specify in your package.json in nw v0.14.6
