### ISSUE TITLE
nwjs 0.15 / 0.16 with dev tools - windows frozen after some reload - Mac OS 10.10

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#4942]
Hi @rogerwang, during last test happens that after some reload of my app the viewport is locked (no click/scroll response from window), high RAM usage (at the moment I can see more than 2GB of ram). 
More, in this status I can't close the windows and I have to kill the main process.

**Comment by AndryBray** [comment]
I see the same problem leaving the app in stand-by. I still haven't found an exact way to reproduce it. Nobody else have the same?

**Comment by AndryBray** [comment]
After some test I see there are 2 duplicate processes (nwjs Helper) that even if I quit my app, they are alive in background, this happens always when the app view is locked/frozen

**Comment by frankhale** [comment]
Are you using any native modules?

**Comment by AndryBray** [comment]
@frankhale what do you mean exactly? I just use a normal build, no extra plugins/module.... I just use some nodejs module but not in the moment when the app is freezing...

Package.json changes:
```
"chromium-args": "--child-clean-exit --ignore-certificate-errors",
"user-agent": "%name/%ver (%osinfo) AppleWebKit/%webkit_ver nw/%nwver  MyUserAgent",
"node-remote": "*://*.mydomain.com/*"
```

**Comment by frankhale** [comment]
Okay just checking because it's possible Native Node modules could be a problem but apparently for you that's not the case.

**Comment by rogerwang** [comment]
I can't reproduce it here. 

Why are you using "--child-clean-exit"? Does removing it make any difference?

**Comment by AndryBray** [comment]
@rogerwang this param is coming from the oldest versions on node-webkit. As I remember I used it because of problems closing the app (active processes after closing). I will try to remove and test it again.

**Comment by AndryBray** [comment]
@rogerwang even removing this param the problem is still there... just happened again, the dev console and app window are not responding to any action (reload/close/right click). Maybe it's something related to on('close') events? I use these listeners to know when the window is going to be closed then I close(true). Anyway, the same code was working without issues on nw14

**Comment by rogerwang** [comment]
Could you please upload a case and detail steps to reproduce?

**Comment by AndryBray** [comment]
It's really hard to reproduce. I will with some existing website/app and I'll let you know.
Even with my app is not the same all the times...

**Comment by AndryBray** [comment]
@rogerwang my app uses the google js api client, maybe it's related to this? (I just inform you if it can help you)
```
 <script src="https://apis.google.com/js/client.js"></script>
```

**Comment by AndryBray** [comment]
@rogerwang if you remember I had some problem with RAM usage everytime I was reloading my app. This problem was fixed with last versions of nwjs 0.14... now I see the same on nwjs0.16
Reloading many time:
on nwjs0.14 - RAM : 500M-1Gb
on nwjs 0.16 - RAM : 900M - 2Gb

**Comment by rogerwang** [comment]
Do you have an issue number?

**Comment by AndryBray** [comment]
@rogerwang  https://github.com/nwjs/nw.js/issues/4626

**Comment by AndryBray** [comment]
@rogerwang I always see this happen when I reach 1GB or more of RAM usage. I think it's pretty related to dev tools reload action

**Comment by AndryBray** [comment]
@rogerwang same problem with 0.15.2

**Comment by AndryBray** [comment]
@rogerwang same problems with latest 0.16

**Comment by Christywl** [comment]
I try the test case in #4626 comments, can't reproduce this issue. Please try the latest nwjs build.
Mac
nwjs-sdk-v0.24.3

**Comment by Christywl** [comment]
close until there is more information
