### ISSUE TITLE
Print Dialog Fails to Resize With Window

### ISSUE THREAD

**Issue by rdtsc** [nwjs/nw.js#4946]
The recently introduced Chromium-style print dialog fails to resize itself with the containing window after it's first spawned. Seems like it saves its size on spawn and doesn't get/react to parent window sizing updates.

---
- **OS**: Windows 7 x64, though this shouldn't be OS-specific.
- **NW.js**: `nwjs-v0.15.2-win-x64` (both SDK and non) from `06-06-2016` - `nw15-024592f-5c2963f-0b926c0-c74d4b4` as well as `nwjs-v0.16.0-beta1-win-x64`.

---
##### Current Behavior:

<p align="center"><img src="https://cloud.githubusercontent.com/assets/6773893/15824119/a0ff4f4a-2bcb-11e6-8afc-596c1091920f.gif"></p>

##### Expected Behavior:

<p align="center"><img src="https://cloud.githubusercontent.com/assets/6773893/15824127/acf82ec0-2bcb-11e6-886a-2f2adebaf011.gif"></p>

##### Test Case:

``` html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Print Test</title>
    <style>@media print {button {display: none}}</style>
  </head>
  <body>
    <pre>Lorem ipsum dolor sit amet, consectetur adipisicing.</pre>
    <button onclick="window.print()">Print</button>
  </body>
</html>
```

**Comment by jasminmif** [comment]
@rdtsc If you close the print dialog, and close it, it fixes the re-sizing. So a small fix would be to close, and reopen as you re-size the window.

**Comment by Christywl** [comment]
I can reproduce this issue on Windows 7 with nwjs-sdk-v0.21.3, but can't reproduce on Linux and Windows 8/10.

**Comment by rdtsc** [comment]
Looks like a stale issue at this point. No longer reproducible in recent builds. Thanks!

**Comment by rogerwang** [comment]
@rdtsc great to know it. Thanks.
