### ISSUE TITLE
Problems with debug node modules

### ISSUE THREAD

**Issue by acterhd** [nwjs/nw.js#4948]
Hello. I have problems with debugging "require" modules. I can't see any sources in DevTools. Even not working "console.log". I don't know why...?

**Comment by MrHalfman** [comment]
Hello, you are probably using browser console for node-context modules.

Try Right Click > Inspect Background Page

**Comment by gpetrov** [comment]
I also wondered why console.log in node modules does not work suddenly in the latest 0.14 / 0.15 nwjs versions.

@rogerwang is this by design? We use to debug our node modules this way.
Or is it a hidden switch to re-enable?

**Comment by gpetrov** [comment]
ah sorry found the Inspect Background Page ...

**Comment by MrHalfman** [comment]
@gpetrov I think that you should enable --mixed-context to have your outputs in the browser console instead of "Background console".

**Comment by acterhd** [comment]
I seen only script names with directory, no sorting.

**Comment by rogerwang** [comment]
Close since  you should inspect background page

**Comment by jan4984** [comment]
where is ` Inspect Background Page`, the document said `right click` the `app`. but what is the `app`? I can not find the menu.

**Comment by jan4984** [comment]
@kailniris got. thanks.
