### ISSUE TITLE
Can I take to maximize and minimize button set on the menubar?

### ISSUE THREAD

**Issue by zenglzh** [nwjs/nw.js#4949]
Hello. My app is a  frameless window,and there is a menu bar.I want set maximize , minimize ,close button on top right-hand of the menu bar.
OS:xp,win7+
nwjs:nwjs-v0.15.0-win-x64

**Comment by iteufel** [comment]
@zenglzh Please use the mailing [list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter](https://gitter.im/nwjs/nw.js) to ask questions.
