### ISSUE TITLE
handing files issue

### ISSUE THREAD

**Issue by littledream2015** [nwjs/nw.js#4951]
I have read this post [https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments.](https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments)
but one issue occurs, I am trying to develop an IDE using node-webkit, nw can handle any files (e.g. css,html and etc ) except for js.( it's working on mac, but not on windows )
Is there any reason for security that nw ignore js file?
How can I fix it? 
tks.

**Comment by rogerwang** [comment]
What do you mean by "handle js files"?

**Comment by littledream2015** [comment]
@rogerwang  according to this post [https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments.](https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments.), my nw application( an IDE ) can open css and html file,but couldn't open js file. I doubt if you design this on purpose, is there any solution????

**Comment by littledream2015** [comment]
@rogerwang Do you have any solution? Why doesn't it work in the windows?

**Comment by rogerwang** [comment]
how does your app open the files?

**Comment by littledream2015** [comment]
@rogerwang
 case 1: double-click js file,there is no response, my simple IDE couldn't open.but it works for html,css and php files.
 case 2: use 'open with' method to open js file, it still doesn't work.

tips:
1.the cases only happen in the windows.
2. when my IDE tries to open js file. gui.App.argv is always empty.

**Comment by rogerwang** [comment]
Please give more detail so I can understand your situation.

**Comment by littledream2015** [comment]
@rogerwang 
Let's see the following code
when nwapp tries to open a specific file using 'open-with' , gui.App.argv has the parameter.
and my nwapp is just a simple IDE,I want to use it to open javascript file,
but in the windows, gui.App.argv is always empty , it works in the Mac.
I extremely want to know why my IDE couldn't open javascript file in the windows.

**code**:
`        if( gui.App.argv.length ){
        	var openFiles = gui.App.argv.splice(0,gui.App.argv.length);
            for(var i=0,len=openFiles.length;i<len;i++){
                fileInstance.openfile(openFiles[i]);
            }
        }
`

**Comment by rogerwang** [comment]
The information you provided is not enough. The root cause may be in your app rather than NW.

Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general  and provide more details.

**Comment by octachrome** [comment]
This looks like the same issue as https://github.com/nwjs/nw.js/issues/5242 - the command line argument gets swallowed. Still broken in v0.21.3.
