### ISSUE TITLE
a

### ISSUE THREAD

**Issue by idoaizenshtein** [nwjs/nw.js#4952]

**Comment by rogerwang** [comment]
We support the same Linux distributions as Chromium does.

**Comment by idoaizenshtein** [comment]
Thank’s.
You know how install .deb that clickable nw file?

**Comment by frankhale** [comment]
You'll be more likely to get a response by asking questions on the mailing list:

https://groups.google.com/forum/#!forum/nwjs-general

or asking on the NW.js Gitter:

https://gitter.im/nwjs/nw.js
