### ISSUE TITLE
[0.14.5] Unexpected file created from command-line argument

### ISSUE THREAD

**Issue by asinverse** [nwjs/nw.js#4953]
Hi team,

Currently, my app (using 0.12.3) allows users login with the password in the command line. 
When I change to nw 0.14.5, a file is created with the name is the user's password even in normal mode.
My source code is in `package.nw`
and my command line is: `app.exe --pass <mypassword>`
then, file `mypassword` appears in same folder as `app.exe`

I could delete this file afterward, but is it your plan? If not, should it be fixed soon?

PS: I haven't tested new nw version.

**Comment by Batcherinho** [comment]
I believe this is already reported.. I've experienced similar issues with versions 0.13.x and above and ultimately had to prefix the arguments with an additional '-' to get around the issue.

**Comment by asinverse** [comment]
Ah, thank you @Batcherinho. This duplicates #4768. But I hope this would be fixed.
