### ISSUE TITLE
devtool doesn't open on recent version

### ISSUE THREAD

**Issue by rkmax** [nwjs/nw.js#4955]
I'm using node 6.2.1 and install nw 0.15.1 on linux

I have a simple index.html with a hello world and my package.json is the following

```json
{
  "name": "hello",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "start": "nw ."
  },
  "dependencies": {
    "nw": "^0.15.1"
  },
  "window": {
    "width": 600,
    "height": 800,
    "toolbar": true,
    "resizable": false
  },
  "chromium-args": "--mixed-context"
}
```

After running `npm start` the window with the html content is shown but if I press the F12 button the devtool doesn't open

there's something I'm missing?

I also tried the remote debug without success

I've executed the command `nw --remote-debugging-port=9222 .` but nothing listen on that port

**Comment by frankhale** [comment]
Are you using the SDK build of NW.js? The regular build does not contain the devtools.

**Comment by rkmax** [comment]
I'm using the regular package from npm. there's some npm package that include the devtools?

**Comment by rkmax** [comment]
@frankhale I found the SDK flavor. would be great if each flavor have his own package through npm something like 

- nw-sdk-flavor
- nw-mac-flavor
- nw-naci-flavor

cheers!

**Comment by edysegura** [comment]
Hi @frankhale !!

You can use [nwjs version manager](https://www.npmjs.com/package/nwjs) and after install it you can execute the command below:

```nw install 0.14.7-sdk```

After that just do

```nw .```
