### ISSUE TITLE
Performances issues

### ISSUE THREAD

**Issue by Sytten** [nwjs/nw.js#4958]
Hi

I was just wondering if this performance behavior was a "normal" behavior of NWJS or I'm doing something wrong with a script causing useless renders.
When my application is IDLE on a none moving page the chromium browser seems to render the page at rate of around 12FPS.
In comparison with a normal chromium browser where its around 1-2FPS when IDLE.
This create a noticeable performance issue (and drains battery life) for my users from the feedback I was given. I know it comes from the render process since when the window is hidden the CPU usage drops instantly (+ I can attach some timeline log if needed). 

Thank you very much @rogerwang for your good work

**Comment by rogerwang** [comment]
Could you please provide more details? And a case to reproduce it would be best

**Comment by Sytten** [comment]
Yes, I have this problem with Messenger For Desktop (https://github.com/Aluxian/Facebook-Messenger-Desktop/tree/develop)

This screenshot is from messenger.com in chrome browser
![screenshot from 2016-06-11 12 04 27](https://cloud.githubusercontent.com/assets/2366731/15986087/f4790a58-2fcc-11e6-8cdd-22a7e07b46ea.png)

This one is from the dev tools in the chromium browser of NWJS
![screenshot from 2016-06-11 12 01 44](https://cloud.githubusercontent.com/assets/2366731/15986093/15c367c6-2fcd-11e6-892e-4b15a5677ea5.png)

Those two where taken when the page was idle.

**Comment by Sytten** [comment]
On Ubuntu 15.10, I also see that the compiz process rise to about 66% of one core when the window is up (and go down to 6% when its hidden). The rendering must be very costly...

**Comment by Sytten** [comment]
I'm still investigating. From my experiences its almost certain that its a call in my code or in the scripts of messenger.com that triggers those repaint. When I only have a loading screen the CPU seems to go down. Still if someone have an idea, share it!

**Comment by kailniris** [comment]
Also noticed even in idle state the nw.js process uses 10% cpu.

**Comment by Sytten** [comment]
Thanks, not the only one :)

**Comment by rogerwang** [comment]
Here is what I did trying to reproduce but did not find the periodic painting as you did:

![screenshot from 2016-06-27 10-54-57](https://cloud.githubusercontent.com/assets/165401/16367401/bd2544be-3c55-11e6-9734-56b014a9265f.png)

1. Download http://dl.nwjs.io/v0.15.4/nwjs-sdk-v0.15.4-linux-x64.tar.gz to Debian/Gnome system
2. run nw --url='https://www.messenger.com'
3. Login with with my account and stay at the chat main screen
4. open devtools and record JS & painting.

**Comment by Sytten** [comment]
And I guess the CPU usage is low. Probably yes.
Then, do you have ideas of what might trigger those repaints?
Is there a way to see the call stack?
This is the code I'm working on:
https://github.com/Aluxian/Facebook-Messenger-Desktop/tree/V1.5.X

**Comment by rogerwang** [comment]
First you need to rule out the issue in NW or in your application. Chromium browser is a good baseline, but you'll need to compare the **same web page** in both NW and Chromium.

**Comment by Sytten** [comment]
Well there not much difference between the https://www.messenger.com except that its in an iframe.
When I try to load that page in chromium (without the scripts obviously), it doesn't seem to like it very much:
Refused to display 'https://www.messenger.com/login' in a frame because it set 'X-Frame-Options' to 'DENY'

**Comment by Christywl** [comment]
@Sytten , is this issue reproduced in your side on the latest nwjs build？

**Comment by Sytten** [comment]
The version using NWJS is deprecated since the original dev decided to rewrite in electron. I have not tested with the latest build.
