### ISSUE TITLE
crash when calling JSON.stringify(window)

### ISSUE THREAD

**Issue by raxvan** [nwjs/nw.js#4959]
I stumbled upon a crash with very simple repo steps:

1: node-webkit sdk version 0.15.2(64 bit): http://dl.nwjs.io/v0.15.2/nwjs-sdk-v0.15.2-win-x64.zip
2: os: windows 8.1 64 bit (not sure if it's important)
3: crash dump: [2f303dbc-885d-4ddb-b66d-9f070e76fc55.zip](https://github.com/nwjs/nw.js/files/307302/2f303dbc-885d-4ddb-b66d-9f070e76fc55.zip)
4: package.json:
`{
	"name": "test",
	"main": "index.html"
}`
5: index.html:
`<!DOCTYPE html>
<html>
<body onload="JSON.stringify(window)">
</body>
</html>`
6: can be reproduced by executing `nw.exe` from cmd with path to the folder containing package.json.

I spotted the issue while running a sublime text build system. Sublime console had some more info on the crash (not sure if relevant):

	[0609/185030:ERROR:process_info.cc(608)] range at 0xcb12485200000000, size 0x5c fully unreadable
	[0609/185030:ERROR:process_info.cc(608)] range at 0xcb12487200000000, size 0x5c fully unreadable
	[0609/185030:ERROR:process_info.cc(608)] range at 0x0, size 0x5c fully unreadable

**Comment by iteufel** [comment]
@raxvan This is a wanted behaviour.
Chromium says: `Uncaught TypeError: Converting circular structure to JSON(…)`
To prevent your app from crashing add `process.on('uncaughtException', uncaughtExceptionHandler);`

**Comment by raxvan** [comment]
@iteufel Have you tested your solution ? the crash still occurs. I checked the behavior of this on a regular chrome browser and it's handled all nicely with the exception printed in console (without `uncaughtException` hack)

**Comment by iteufel** [comment]
@raxvan Sry I have not tested it.

**Comment by rogerwang** [comment]
This is due to "experimental.devtools.audits" is wrongly enabled in nwjs app. It's supposed to be only in devtools page.

It's fixed in git and will be available in the next nightly build.
