### ISSUE TITLE
Local storage migration issue

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#4962]
OS : Windows 7
NW : v0.14.6

Hi All,
I am trying to migrate from 0.12.3 to 0.14.6. I have observed that the local storage is not migrating and I have gone through #4853. I have observed that there's a local storage created for every domain. I have a domain, let's say `https://xyz.com` and it's corresponding data is stored in the local storage in 0.12.3. Now, when I run 0.14.6 app, the files aren't migrated to `local/myapp/user Data/default/local storage` and it creates a new local storage for this domain, instead.
If I run my 0.12.3 app, then the app detects the previous local storage as if it was never migrated. So,  basically both 0.12.3 and 0.14.6 have their own local storage which they can use independently.
P.S. : If I copy the domain related local storage from 0.12.3 and paste it at it's appropriate location in 0.14.6, it works.

**Comment by rogerwang** [comment]
please upload a sample with user data dir of 0.12 so I can reproduce it

**Comment by RohitSharma27** [comment]
@rogerwang Will try to do that. :)

**Comment by rogerwang** [comment]
This was fixed by 0.15.3. Will be in 0.14.7 too.

**Comment by RohitSharma27** [comment]
Thanks @Rogerwang.

**Comment by RohitSharma27** [comment]
@rogerwang Please re-open this issue as it isn't completely resolved in NW0.14.7. I have tried this on MAC and observed that only storage file corresponding to file is getting transferred correctly as chrome-extension one but, not the files related to different domains. Should it not migrate everything that's there in local storage to it's new location correctly?
