### ISSUE TITLE
Missing WebRTC.Video.AVSyncOffsetInMs

### ISSUE THREAD

**Issue by thedracle** [nwjs/nw.js#4965]
Chromium 51 added a new histogram state for AVSyncOffset in WebRTC.

Issue:
https://bugs.chromium.org/p/webrtc/issues/detail?id=5493

PSA for Chromium M51 release including the above feature:
https://groups.google.com/d/msg/discuss-webrtc/GdsmhrVaxdU/q99shod9OAAJ

I'm using NWJS 0.15.2, which should be against chromium 51.0.2704.84

When I open chrome://histograms via:
> nw.Window.open('chrome://histograms')

I never see the WebRTC.Video.AVSyncOffsetInMs

I've started/stopped incoming and outgoing WebRTC streams.

When the other end of the WebRTC conversation is Chrome Version 51.0.2704.84 (64-bit)
going to chrome://histograms shows the relevant AVSyncOffset statistic:

`Histogram: WebRTC.Video.AVSyncOffsetInMs recorded 3 samples, average = 10230.3 (flags = 0x1)`

Any reason why this wouldn't show up in NWJS which is as far as I can tell against the exact same build, 51.0.2704.84?

**Comment by rogerwang** [comment]
It should be supported. Will check it. Thanks. Do you have a screenshot for this?

**Comment by thedracle** [comment]
After more investigation, I think it's an issue upstream where the message doesn't appear until certain very specific conditions are met with regards to the stream.
