### ISSUE TITLE
'show_in_taskbar' isn't working

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#4970]
NW : v0.14.6 sdk
OS : win 7
Hi,
I am facing the titled issue and below is the screenshot for that.
![capture](https://cloud.githubusercontent.com/assets/18210507/15999733/441b557c-3165-11e6-8a43-4f5dae8ef1c7.PNG)

**Comment by chrisjandrade** [comment]
I also have the same issue...
0.17.6-sdk
win 7, x64

![ss](https://cloud.githubusercontent.com/assets/3063835/19311242/86075058-905b-11e6-960b-c27fded62e13.png)

**Comment by IrisGitHub** [comment]
I also have the same issue...  0.17.0-sdk

**Comment by fusionstream** [comment]
This issue is still preset in 0.18.8 SDK and 0.19.0 SDK nightly (30/11/2016)
