### ISSUE TITLE
window close event doesn't fire

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [nwjs/nw.js#4972]
OS: Windows 8.1
Version: 0.15.2

This event has stopped working. 
Used to work in 0.15.0
Haven't tested 0.15.1.

http://nwjs.readthedocs.io/en/latest/References/Window/#event-close

**Comment by ghostoy** [comment]
@Gimmeaphatbeat I can't reproduce the issue with 0.15.2 and latest 0.15.4. Could you post a sample app for reproduction?

**Comment by ghostoy** [comment]
Close it since not receiving feedbacks in 2 weeks. Please reopen it if you have further comments.
