### ISSUE TITLE
icon  doesn't work with windows xp sp3.

### ISSUE THREAD

**Issue by zytse** [nwjs/nw.js#4973]
Mainifest->Window Subfields->icon  doesn't work with windows xp sp3.

**Comment by Pumpernickel61** [comment]
Sorry that's not a lot of information. Please provide a copy of package.json and size and format of your icon. I addition please let us know what you expect and what exactly you get/see. Thank you.

**Comment by Christywl** [comment]
@zytse , is this still reproduced for you? If yes, please provide more info to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
