### ISSUE TITLE
while screen sometimes emerge when opening new window.

### ISSUE THREAD

**Issue by qdwang** [nwjs/nw.js#4974]
The option of window has already been set `transparent: true`.

Sometimes it just display the while screen for about 1 sec and then the background turns to transparent.

And the HTML content has been set background of body to transparent.

![screenshot](https://cloud.githubusercontent.com/assets/403616/16038817/67efcc2c-3259-11e6-95ed-ecf936f76fc4.png)
Display like this pic.

info:
nw.js v0.15.2 32bit
windows 8.1 64bit, windows server 2008 r2 64bit

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8 with nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
close until more information is available.
