### ISSUE TITLE
two hyphens are replased by n-dash in the doc example of command line option

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#4978]
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Flash%20Plugin/

> The flash plugin loading can be verified with /path/to/nwjs **–**url=’chrome://plugins’

**Comment by Christywl** [comment]
@rogerwang , please confirm this.

**Comment by rogerwang** [comment]
yeah it should be a bug.
