### ISSUE TITLE
Flash plugin compatibility

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#4979]
[The doc](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Flash%20Plugin/) has no information about Flash plugin version compatibility or possible download/copy location.

Say, I use NW 0.15.2 with Chromium 51.0.2704.84 for Win x64. And I use Google Chrome Cannary 53.0.2767.0  for Win x64. If I copy PepperFlash folder from Google Chrome directory to NW-sdk  directory, NW do shows Pepper Flash in the chrome://plugins:

![1](https://cloud.githubusercontent.com/assets/10393198/16064584/243fd204-32ab-11e6-8ee2-75bc1fa7facb.png)

However if I load in the NW some .swf, I get this error:

![2](https://cloud.githubusercontent.com/assets/10393198/16064787/e12cc0c4-32ac-11e6-91c5-d493a2697859.png)

Should I add to the NW directory the Pepper Flash for the same Chromium version? And if so, how can I obtain it? Are there any other causes for plugin fail?

**Comment by rogerwang** [comment]
Could you please try the file from a same Chrome version?

**Comment by vsemozhetbyt** [comment]
@rogerwang Should I install Chrome 51.0.2704.84 or is there a repository with portable binaries for all the Chrome/Chromium versions?

**Comment by vsemozhetbyt** [comment]
I've just tried to install the current stable Chrome version, but the installer demands to uninstall my dev version first. Is there a simpler way to get Pepper Flash compatible with NW 0.15.2?

**Comment by Blatman** [comment]
FWIW I tried this on win 64 with 0.15.2 just for interest but couldn't get the pepperflash to work - got permission error same as with OSX #4826. Went back to OSX and tried a few pepperflash builds and got -
Using 0.15.2 (51.0.2704.84) with -
48     20.0.0.306  OK
49     20.0.0.306  OK
50     21.0.0.213  OK
51     21.0.0.242  FAIL
I used the pepperflash builds form the slimjet archive site - http://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by vsemozhetbyt** [comment]
I've tried the same on Win 7 x64 and I have FAIL for all the four versions.

By the way, is `nw --url="chrome://plugins" on Windows works only with SDK version, simple version crashes.

**Comment by Blatman** [comment]
Went back to PersonaTool 3.1 which uses 0.14.2 32bit and it works OK so I tried a plain load of NWJS (0.14.2) with the PersonaTool flash (20.0.0.306) and it was OK too (on Win10 x64). Tried the same flash with 0.15.2 (32bit) and it failed (on OSX the same flash version will work with 0.15.2). In both cases the manifest.json was set for ia32 and win.
The test project was the same as for #4826

**Comment by lipan** [comment]
v0.15.4 couldn't load plugin....

**Comment by RohitSharma27** [comment]
In order to use pepper flash player on windows, you can place 'pepflashplayer.dll' in the same directory as your 'nw.exe' and use following arguments in your package.json file
"chromium-args": "--ppapi-flash-path=pepflashplayer.dll --ppapi-flash-version=20.something something"
As far as your swf files are concerned, you are trying to load some local swf, maybe?

**Comment by lipan** [comment]
@RohitSharma27   thanks !

**Comment by vsemozhetbyt** [comment]
@RohitSharma27 Thank you. I've tried your tip both for a project and a command line and it works:

`package.json`
```JSON
{
  "name": "nw-test",
  "main": "http://vsemozhetbyt.github.io/test/5.swf",
  "chromium-args": "--ppapi-flash-path=PepperFlash/pepflashplayer.dll"
}
```
Or just cli:
```
nw --url="http://vsemozhetbyt.github.io/test/5.swf" --ppapi-flash-path=PepperFlash/pepflashplayer.dll
```
@rogerwang May be the doc shoud be updated.

**Comment by vsemozhetbyt** [comment]
By the way

1. With `--ppapi-flash-path` it works even with PepperFlash from the last Canary (22.0.0.200).
2. If I drop `pepflashplayer.dll` and `manifest.json` just in the nw directory, I get the error, so they both should be in the `PepperFlash` subdirectory.

**Comment by RohitSharma27** [comment]
@vsemozhetbyt you're welcome. I am glad it helped. Cheers. :)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
