### ISSUE TITLE
webgl issues

### ISSUE THREAD

**Issue by cjdg** [nwjs/nw.js#4980]
i made a small html which uses three.js and i get the following error

three.js:24962 THREE.WebGLRenderer: Error creating WebGL context.

TypeError: Cannot read property 'getExtension' of null
    at get (chrome-extension://ahhodkmfkdogfgflegfnkjmlklhpdcch/three.js:28599:19)
    at new THREE.WebGLRenderer (chrome-extension://ahhodkmfkdogfgflegfnkjmlklhpdcch/three.js:24969:13)
    at chrome-extension://ahhodkmfkdogfgflegfnkjmlklhpdcch/index.html:15:19

**Comment by rogerwang** [comment]
Could you please upload the sample? Thanks.

**Comment by vaporwave98** [comment]
Using the latest version of THREE.js and nwjs, it seems to work fine for me.

**Comment by cjdg** [comment]
finally works!, im using nwjs 0.15.4 and three.js r78
