### ISSUE TITLE
Support for Eval remote 

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#4983]
Has anyone tested opening of a new window and loading of a remote compiled v8 file? 

Using 
`Window.evalNWBin(frame, 'https://gg.com/s.bin')`

Is this at all possible? If not could it be kindly requested?

**Comment by rogerwang** [comment]
Could you use the inject js options together with evalNWBin?

**Comment by mscreenie** [comment]
Thanks for reply. Is that possible? Can you post an example?

**Comment by mscreenie** [comment]
I suppose I should be asking, does evalNWBin support strings or loading remote files via http

**Comment by mscreenie** [comment]
feature added https://github.com/nwjs/nw.js/issues/5220
