### ISSUE TITLE
Can't use require to load node modules in mixed context mode

### ISSUE THREAD

**Issue by ataylor09** [nwjs/nw.js#4987]
I have managed to get an Angular 2 app working by following the solution to: #4838 (running nw.js with mixed context mode). I've also added the workaround from #4282 (redefining global to nw_global before angular dependencies are loaded) However, I am now unable to use require to load node modules.

For example In the Dev tools console I run the command:

`require('nedb')`

which returns an error:

```
module.js:439 Uncaught TypeError: Cannot read property '__nwjs_cv' of undefined
    at Object.Module._extensions..js (module.js:439:13)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
    at Module.require (module.js:385:17)
    at Object.require (internal/module.js:16:19)
    at <anonymous>:2:4
    at Object.InjectedScript._evaluateOn (<anonymous>:878:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluate (<anonymous>:667:21)
```

I'm using version 0.13.3 on Windows 10.

**Comment by rogerwang** [comment]
Could you please try the latest version?

**Comment by ataylor09** [comment]
Same issue with latest version (0.15.4)

**Comment by ataylor09** [comment]
@rogerwang Any other suggestions? Would really love to get this working!

**Comment by ataylor09** [comment]
I just discovered that if I call require('package_name') before the angular dependencies are loaded then it works fine. Would this suggest that somewhere along the line, Angular 2 and/or its dependencies are messing with the require functionality. 

I'm a little bit out of my depth here, but hopefully this will help someone come up with a reason why the problem is occurring.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
