### ISSUE TITLE
My program in window7 64 bit systems without reason to quit

### ISSUE THREAD

**Issue by hxfdarling** [nwjs/nw.js#4990]
My program in window7 64 bit systems without reason to quit
nwjs version is .12.3

How can I solve this problem？

**Comment by RohitSharma27** [comment]
What exactly is your issue?

**Comment by gtrevg** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (207/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:50952 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bE6vH-0007HW-DF
	for github@trevorgattis.com; Sat, 18 Jun 2016 03:27:51 +0000
Date: Thu, 16 Jun 2016 05:50:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466081451;
	bh=V5hJVX5em1GaQcUoqkMeAoYhpHhZkifiCYpBOmz4zmE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ID/auU5IzTSldpDtBUUue2h/zZq+Mp1Ch3eGzO3efvD/IdttNCaLvI6afml1+4eBo
	 JtVIFUgoByyLhrdsBt5jYwB8WUwTklzLMbq5ToqB3IhJJCuOmKl4HwlnYWSxIxjmoX
	 OuNxCKlt7XiWI9knzfX5bTbA3d1vsYM+/2kvgyxQ=

**Comment by rogerwang** [comment]
0.12 is not supported any more. You can ask this in the mailing list.
