### ISSUE TITLE
registerGlobalHotKey  and  alert

### ISSUE THREAD

**Issue by xland** [nwjs/nw.js#4992]
nw version:0.15.2
os version:windows 10 x64
code:

``` javascript
var option = {
    key: "Ctrl+Shift+N",
    active: function() {
        alert("1")
    },
    failed: function(msg) {
        alert("2")
    }
};
var shortcut = new nw.Shortcut(option);
nw.App.registerGlobalHotKey(shortcut);
```

description:
When app is minsized and the shortcut is pressed, the alert dialog can not  show and the app is disabled.

**Comment by ghostoy** [comment]
I can confirm this issue. Looks like it only happens on Windows. I will try to fix it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by xland** [comment]
OK~Thanks a lot!
