### ISSUE TITLE
Window resize event returns undefined for height

### ISSUE THREAD

**Issue by vzamanillo** [nwjs/nw.js#4993]
Nwjs 0.15.2
Ubuntu Linux 64 bit

```javascript
window.on('resize', function(width, height)){
});
```
`height` is always `undefined`.

**Comment by joshterrill** [comment]
What are you using to define `window`?

**Comment by vzamanillo** [comment]
Hi joshterrill,

is the main app window.

`win = nw.Window.get();`

thank you!

**Comment by joshterrill** [comment]
Interesting, I'm getting the same results. So I was looking into some of the included JS libraries for webkit, and when I put a breakpoint on line 283 of `extensions::nw.Window`, the height is shown in a callback passed back to `Window` (this). So I'm not really sure where the height is getting lost in translation. Below is a screenshot.

![Imgur](http://i.imgur.com/QsEi0PP.png)

**Comment by vzamanillo** [comment]
Thank you very much for your feedback.

**Comment by fcard** [comment]
I am pretty sure **[this](https://github.com/nwjs/nw.js/blob/0a316ed3ecfcc02038afc8a60f0a4d13e29e8321/src/resources/api_nw_window.js#L283)** is the problem line.
```js
callback.call(self.width, self.height);
```
Since callback.call should take `this` as its first argument.

**Comment by joshterrill** [comment]
@fcard yes I believe it is!

**Comment by ghostoy** [comment]
I will fix it soon.
