### ISSUE TITLE
Set window borderless (frame: false) on the fly

### ISSUE THREAD

**Issue by Curirin107** [nwjs/nw.js#4994]
How can I set a window to borderless on the fly (remove the border, set frame: true)?
Thank you!

**Comment by frankhale** [comment]
I don't think it's possible. The best place to ask question is on the mailing list or on the Gitter site.

https://groups.google.com/forum/#!forum/nwjs-general
https://gitter.im/nwjs/nw.js

**Comment by Curirin107** [comment]
So I'll leave an answer there, thank you.

**Comment by rogerwang** [comment]
Unfortunately this is not supported. Thanks.
