### ISSUE TITLE
WebPage don't close

### ISSUE THREAD

**Issue by rodrigofaria** [nwjs/nw.js#4996]
I'm using gui.Shell to open a webpage:

gui.Shell.openExternal('file://' + file); //open URL with default browser

This page contains a video that will play automatically when the page will be open.
So when I close the page, the window closes normal (Google Chrome) but the video is still playing.
I just know this because the audio is still executing.

Any idea to solve this?
Thanks!

**Comment by rogerwang** [comment]
Could you please show a full demo?

**Comment by rodrigofaria** [comment]
Hi rogerwang!

Sorry for delay!
So...when I try to create a full demo to show to you, I discovery that problem is in my code :)

Thanks for all!
