### ISSUE TITLE
App.dataPath returns default profile path instead of application path

### ISSUE THREAD

**Issue by vzamanillo** [nwjs/nw.js#4998]
Nwjs 0.15.2
Ubuntu Linux 64 bit

In nw.js == 0.12.3 App.dataPath returned ~/.config/<name-in-manifest>
In nw.js > 0.12.3 App.dataPath returned ~/.config/<name-in-manifest>/Default (the default profile folder)

Is this intentional or it is a bug?

**Comment by vzamanillo** [comment]
Related to #4696

**Comment by rogerwang** [comment]
close as duplicate of #4696
