### ISSUE TITLE
'resizable' Window subfield does not effect on Window.open

### ISSUE THREAD

**Issue by vzamanillo** [nwjs/nw.js#5000]
Nwjs 0.15.2
Ubuntu Linux 64 bit

The `resizable` [window subfield](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#window-subfields) doesn't work when opening a new window.

``` javascript
nw.Window.open('https://...', {
    title: 'The tile',
    icon: 'src/app/images/icon.png',
    width: 600,
    height: 600,
    resizable: false,
    position: 'center',
    focus: true
}, function(win){
    //
});
```

I have to use `window.setResizable(boolean);`

``` javascript
nw.Window.open('https://...', {
    title: 'The tile',
    icon: 'src/app/images/icon.png',
    width: 600,
    height: 600,
    position: 'center',
    focus: true
}, function(win){
    win.setResizable(false);
});
```

**Comment by vzamanillo** [comment]
@rogerwang , thank you for your support.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.21.3.

**Comment by xzhan96** [comment]
@rogerwang I'd like to investigate it.

**Comment by xzhan96** [comment]
@Christywl did you try on Windows or Mac? It should be only reproduced on Linux, please confirm it.
If yes, it is chrome upstream issue.

**Comment by Christywl** [comment]
@xzhan96 , this issue doesn't occur on Windows and Mac.

**Comment by xzhan96** [comment]
@rogerwang are you working on this? if not, I'd like to investigate it.

**Comment by xzhan96** [comment]
@vzamanillo  Chrome also has the same issue in Linux.
I have reported it to upstream, please track it here, https://bugs.chromium.org/p/chromium/issues/detail?id=708866
