### ISSUE TITLE
 It should not trigger an "loaded" event on nwWindow when call window.history.replaceState()

### ISSUE THREAD

**Issue by sean220** [nwjs/nw.js#5001]
The duplicated nwWindow  'loaded' event  triggers When call window.history.replaceState() in the new window.

**Comment by sean220** [comment]
After history.pushState() and call history.back() has the same problem. 
The new HTML5 history API does not result in the actual document reload.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
