### ISSUE TITLE
Can the PDF viewer have the node context?

### ISSUE THREAD

**Issue by IBSNA** [nwjs/nw.js#5002]
Hi everyone,

I was wondering why the PDF viewer doesn't have access to the node context, I was trying to find a way to use the custom print feature however after testing it appears this extension doesn't have access to the node context.

I tried using "node-remote": "chrome-extension://*/*" but it said that it is an invalid scheme.

Is there anyway around this?

Thanks!

**Comment by rogerwang** [comment]
What's the details of the issue? It may not be related with Node context.

**Comment by IBSNA** [comment]
Hi @rogerwang, Basically I am programmatically opening a window to a PDF file and then executing the print method in that window, however it only fires the standard window.print() function, When I inspected the PDF page, it appears it does not have access to the node context ( I tried requiring something directly in pdf.js source within the DevTools but it didn't recognize the **require** method )

I know I can use Kiosk mode to automate the printing, however the problem is that I am choosing which printer to print to, but the standard window.print doesn't support the printer option.

**Offtopic:** thank you for creating this project.

Regards.

**Comment by IBSNA** [comment]
@rogerwang A short term solution would be a way to set the default printer programmatically, so I was wondering is there an exposed API that does this? I assume the chrome printing window has something like this because when you change the printer, it persists if you close the print window and open it again.

Regards.

**Comment by joshterrill** [comment]
Have you tried setting `node-remote: *`? Maybe that will work?

**Comment by IBSNA** [comment]
@joshterrill Hi, yes I tried, unfortunately "chrome-extension://" is considered an invalid scheme.

**Comment by IBSNA** [comment]
@rogerwang Any suggestion on how to do this?

**Comment by joshterrill** [comment]
I didn't mean to try `chrome-extension://` inside there, just put `*` in there...

**Comment by IBSNA** [comment]
@joshterrill Thank you, I tried that as well, but I am getting this error: "Missing scheme separator"

Looks like in the new build you must include a scheme. and "chrome-extension://" Happens to be considered invalid.

Regards.

**Comment by joshterrill** [comment]
What are you putting into the `node-remote` field. Copy and paste that in this thread, exactly what you have.

**Comment by IBSNA** [comment]
I also tried using {nodejs: true} with Window.open, but it didn't recognize that attribute.

**Comment by IBSNA** [comment]
@joshterrill Here you go:

`"node-remote": "*"`

**Comment by joshterrill** [comment]
How would you modify the chrome-extension file you're looking to modify to add node to anyway? Where would you modify the file at? Are you compiling webkit yourself?

**Comment by IBSNA** [comment]
@joshterrill The idea is to programatically open a new window to a PDF file like so: 

`gui.Window.open( "app/test.pdf", {show: true}, function( secondaryWindow ) {
    secondaryWindow.print({
         printer: "Printer Name",
    });
});
`

and then execute the new print method, to print to a specific printer. However since it runs the PDF viewer extension which doesn't happen to have the node context it ends up running the normal HTML .print() method. which doesn't support the `printer` option

**Comment by joshterrill** [comment]
So your end goal is to just use the print api in nwjs to automatically print a PDF? You could do this by `win.print({"printer": "Printer Name", "pdf_path": "app/test.pdf"})`... unless I'm misunderstanding what you're trying to do.

**Comment by IBSNA** [comment]
@joshterrill I want to open an existing PDF and send it to the printer of my choice. the example you gave is used to print the page to a new PDF file.

Basically: open an existing PDF file in a new window, and execute the .print method however as I explained there is no node context in the PDF viewer extension, so it just executes the normal browser .print method that doesn't support the custom options such as `printer`

I hope the idea is clear now. Thanks!

**Comment by joshterrill** [comment]
I just got it working.

in `package.json`:
`"node-remote": "*://*"`

In code:
```
require("nw.gui").Window.open( "test.pdf", {show: true}, function( secondaryWindow ) {
    var win = require("nw.gui").Window.get();
    win.print({"printer": "Printer Name"})
  });
```

**Comment by joshterrill** [comment]
I've almost got it working. Try `"node-remote": "*://*"`

**Comment by IBSNA** [comment]
@joshterrill Yes that almost did the job. however it looks like `var win = require( "nw.gui" ).Window.get();` returns the original window, so it ends up printing it instead of the newly opened PDF window.

**Comment by IBSNA** [comment]
@joshterrill I Inspected the PDF viewer window just to bsure and it looks like it doesn't have the node context even with the nifty `"node-remote": "*://*"` configuration.

**Comment by joshterrill** [comment]
So here's how I'm able to interact with the new window:
```
  var gui = require("nw.gui");
  var win = gui.Window.open ('test.pdf', {
    position: 'center',
    focus: true
  }, function(win) {
    win.on ('loaded', function(){
      this.print({});
    })
  });
```

So interestingly enough, when you call just `this.print()`, it interacts with nwjs' print method, not the default `window.print()` one. The reason I know this is because calling `this.print()` throws the same error that `win.print()` throws, it expects a json object to be put into it. Which means `this.print({})` is what works. For some reason, it's just not printing automatically.

**Comment by IBSNA** [comment]
@joshterrill Intersting... I just tried this however I am still getting the same behavior. `this.print` acts the same way as the default browser print method(), whether I supply an argument or not.

If only there is a way to get the node context available when the PDF viewer extension runs. that would solve all of this.

What version have you tested this with?

**Comment by joshterrill** [comment]
It doesn't act the same though... when I just call `this.print()` I get an error. I'm using the `0.15.3 sdk`

**Comment by IBSNA** [comment]
@joshterrill Very peculiar, I just downloaded the last 0.15.3 sdk version and tried the exact code you provided and I am getting the old behavior :(

**Comment by joshterrill** [comment]
You don't see this?
![Imgur](http://i.imgur.com/SDzdSbn.png)

**Comment by IBSNA** [comment]
@joshterrill For some reason I don't, I just downloaded a new `0.15.3 sdk` and used the exact same code as in the screenshot, but I am getting the same behavior I described earlier.

Can you share your package.json file? Thanks!

**Comment by rogerwang** [comment]
Unfortunately the pdf viewer is opened in new process, so accessing the nw.Window object from the main process is not working. Will look to fix this.

**Comment by IBSNA** [comment]
@rogerwang Thank you, this will be amazing when it's added..

Let me know if you need any help with it, I am happy to assist in anyway I can ( Testing, etc. )

@joshterrill Thank you for your effort as well.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/06-29-2016/nw15-cc83171-b33fad2-3ee2c58-8655cb9/v0.15.5/

**Comment by IBSNA** [comment]
Hi @rogerwang I just downloaded the latest build and tested my code, and it is working flawlessly.

Thank you very much for your amazing speed and support!

**Comment by jasminmif** [comment]
Is there a way to catch the callback, after sending the print job to the printer, to close the PDF Print preview page ?

```
nw.Window.open('C:/document.pdf', function(win) {
	win.on('loaded', function() {
		win.print({}, function(callback) {
			win.close();
		});
	});
});
```

**Comment by kailniris** [comment]
@jasminmif win.print({}) is a sync function win.close() will always happen after the job is sent to the printer in theory but sometimes not...

if you want to be sure you can do something like this.

```
nw.Window.open('C:/document.pdf', function(win) {
    win.on('loaded', function() {
        win.print({});
            setTimeout(function() {
                win.close();
            }, 100)
    });
});
```

the setTimeout will put the win.close() to the begining of the next call stack after the win.print is finished + 100 ms.

**Comment by IBSNA** [comment]
Try this

`nw.Window.open('C:\\document.pdf', { show: false }, function(win) {
        win.print();
});`

**Comment by romych78** [comment]
Hi guys. Printing works, but (in same context)
win.getPrinters(function (callback) {
     alert(callback);
});
doesn't work. What I'm doing wrong? I need somehow to get list of available printers in the system.

Thanks.

**Comment by LoGazer** [comment]
Maybe you already figured it out by yourself, but I hope it may help others as well. I ran over this problem myself and solved it.
`callback` in your code is an array of objects. You can see its structure by parsing it:
```
win.getPrinters(function (callback) {
    alert(JSON.stringify(callback));
});
```
Now that you should be able to see something, it should be clear how to access the printer information.
So each printer is accessable via `callback[printer]` <- with "printer" as the element of the array "callback".
Most likely you will need the "deviceName" for using it with `win.print()`.
This is how to simply list all the printers by their deviceName:
```
win.getPrinters(function(callback){
    forEach(function(printer) {
        let p = document.createElement("p");
        p.innerHTML = printer["deviceName"];
        document.appendChild(p);
        document.getElementsByTagName("body")[0].appendChild(p);
    }, this);
});
```
