### ISSUE TITLE
Is there size limit for the nw package?

### ISSUE THREAD

**Issue by kristiyanushatov** [nwjs/nw.js#5003]
We are developing cross-platform application for watching videos.
The application is loading from USB drive and content is 50GB.
When the content is zipped is 45.4GB and NWJS doesn't load the content and nothing appears only blank screen. Is there any solution for the videos to be outsite of the zip, if is too heavy.
All the videos needs to be on the USB, we can't upload them to server, because this flash drive need to be available offline.
We have tried everyting we can.
Please advice!
Thank you!

**Comment by rogerwang** [comment]
There is no known size limitation in NW. How do you package the app? For large content it'd be better to just redistribute the directory tree.

**Comment by kristiyanushatov** [comment]
We are zipping the content with 7-Zip.
I don't really understand what do you mean with directory tree.
Is your idea to have the video file into the folder with the html files?
Thank you for the quick reply!

**Comment by sean220** [comment]
On Windows and Linux, you can put the files of your app in the same folder of NW.js binaries and then ship them to your users. Make sure nw (or nw.exe) is in the same folder as package.json. Or you can put the files of your app in a folder named package.nw in the same folder as nw (or nw.exe).

On Mac, put the files of your app into a folder named app.nw in nwjs.app/Contents/Resources/ and done.

It’s the recommended way to pack your app.

**Comment by frankhale** [comment]
Instead of zipping your code and files just leave them unzipped and put them in package.nw which is at the root of your NW.js folder.

**Comment by rogerwang** [comment]
Close since it's not a bug.
