### ISSUE TITLE
Video decode on multi gpu

### ISSUE THREAD

**Issue by Batcherinho** [nwjs/nw.js#5004]
OS: Win 8
Version: 0.15.2 win64
Specs: Intel Celeron G1620, Nvidia GT 720, 4GB RAM 
The device is using both onboard Intel HD 2500 graphics and the GT 720 (multi monitor setup).

Issues: 
- I've noticed that opening certain external apps that contain Flash lead to really high cpu usage and sluggish framerate. 
- Logs show ERROR:gpu_video_decode_accelerator.cc(362) - HW video decode not available for profile 0

One aspect of the problem could be related to Chromium where the gpu process for some reason always ends up on the Intel HD card, regardless of system settings (inspected with process explorer).
Running chromium flags regarding blacklists and overrides didn't have any effect and I'm guessing the app doesn't use hardware acceleration.

Is there any way to work around the issue, or any chance of controlling gpu affinity?

**Comment by rogerwang** [comment]
Is your issue reproduced in Chromium browser?

**Comment by Batcherinho** [comment]
I've tested with Chrome 51 and the performance seems to be better (slightly less cpu usage overall, with slightly better fps). However chrome logs also show the gpu_video_decode errors.

**Comment by rogerwang** [comment]
Then it should be an upstream issue. You may  find more information in upstream issue tracker: http://crbug.com/ or try Chromium 52 (nwjs v0.16 beta).
