### ISSUE TITLE
window menubar can be unreadable on certain OS themes

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#5007]
Version 0.15.3 on Ubuntu 14.04

A user of my application has reported an unreadable window menubar when using the "Dark Theme" on Ubuntu.

It looks like nw.js window menubar is inheriting the background color from the theme, but not the text color?

![dark-theme](https://cloud.githubusercontent.com/assets/7570428/16206530/d5b29aea-36f6-11e6-97f0-420a4b287509.png)

**Comment by ghostoy** [comment]
@jonwwilkes The text shows on 3 themes installed by default on Ubuntu 14.04. I don't see "Dark Theme" in the settings. Where can I get and install the "Dark Theme" so that I can test with it?

**Comment by jonwwilkes** [comment]
@ghostoy Oops, I neglected to get the name of the theme from the user.  I had wrongly assumed it was a built-in theme.  I'm waiting on a response from the user to get the exact name of the theme (and where he/she got it...)

**Comment by jonwwilkes** [comment]
@ghostoy I've been told the theme is numix
