### ISSUE TITLE
Command line option --url=http://nwjs.io does not work

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5008]
I have been trying to trial an app that starts with a website instead of the index.html file and I read in the documentation that the `--url` option is suppose to do just that:

http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-url

The problem is that nothing happens, not even the `--new-window` option. As I was inspecting all the linked chromium options I noticed that the `--url` option does not even exist:

https://github.com/nwjs/chromium.src/blob/nw13/chrome/common/chrome_switches.cc

https://github.com/nwjs/chromium.src/blob/nw13/content/public/common/content_switches.cc

http://peter.sh/experiments/chromium-command-line-switches/

And I cannot find any alternative option to replace it. Is there a way to do this without having to use the `index.html` file?

OS: Win7x64
NWJS: 15.3 SDK

Tried using just the following in the manifest with no success, with and without `' '` containing the url

````json
{
    "author": "",
    "chromium-args": "--url='https://www.google.com'",
    "description": "",
    "main": "index.html",
    "name": "test",
    "version": "1.0.0"
}
````

**Comment by snehapshinde** [comment]
https://groups.google.com/forum/#!topic/nwjs-general/Mjtgi8qDQm0

**Comment by Yonezpt** [comment]
>Just figured out that it works if package.json is not defined/missing.
In earlier versions, --url used to override package.json 'main' parameter value.

I don't understand, for this to work `package.json` needs to be missing or not defined? Then how is the chromium arg passed if there is no `package.json`? Via shortcut command?

**Comment by snehapshinde** [comment]
That's the current behavior with --url (and needs a fix). We need package.json for other parameters, so --url can not be used.

**Comment by Yonezpt** [comment]
I see, so the current workaround is having an `index.html` redirecting to the url we want.

**Comment by snehapshinde** [comment]
Yup.

**Comment by Yonezpt** [comment]
I found a better alternative which kinda makes the `--url` option redundant, a url can be used in the `main` option:

>You can specify a URL here. You can also specify just a filename (such as index.html or script.js) or a path (relative to the directory where your package.json resides).

http://docs.nwjs.io/en/latest/References/Manifest%20Format/#main

Works perfectly for what I was looking for and since this seems to make what the other option should do I think this issue can be closed.
