### ISSUE TITLE
Permission Denied error when using chrome.bluetoothLowEnergy API

### ISSUE THREAD

**Issue by rexpie** [nwjs/nw.js#5010]
NW.js version 
nwjs-sdk-v0.15.3-osx-x64

OS
El Capitan 10.11.5 64bit

code:

```javascript
chrome.bluetooth.startDiscovery();
chrome.bluetooth.onDeviceAdded.addListener(device => {
  console.log(device.name + ":" + device.address);
  if (device.name == 'REXBLUNO') { // bluetooth name of my arduino with built-in bluetooth
    console.log(device);
    chrome.bluetooth.stopDiscovery(
      function () {
        if (chrome.runtime.lastError) {
          console.log('Failed to stop discovery: ' + chrome.runtime.lastError.message);
          return;
        }
        // so far no error
        chrome.bluetoothLowEnergy.connect(device.address, function () {
          if (chrome.runtime.lastError) {
            console.log('Failed to connect: ' + chrome.runtime.lastError.message);
            return;
          }
        });
      });
  }
});
```

Console output:
```
server.js:16 Failed to connect: Permission denied
```

According to [this issue](https://github.com/nwjs/nw.js/issues/4143), NW.js should enable all chrome.* API. Some how the connect function within the bluetoothLowEnergy object fails.

The Bluetooth hardware is fine, my Android phone can connect to it and read/write data.

API reference:
https://developer.chrome.com/apps/bluetoothLowEnergy

**Comment by rogerwang** [comment]
I agree that it should be enabled by default in NW apps.

For now it can be workaround by adding `"bluetooth": {"low_energy": true}` in package.json: https://developer.chrome.com/apps/app_bluetooth

**Comment by rogerwang** [comment]
This is now fixed in git and will be available in the next nightly build.
