### ISSUE TITLE
NWJS does not close completely if audio/music is playing.

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#5011]
tested with:
version 0.13.0 to 0.15.0
os: vista/win7/win10

To be more clear, I have been using Construct2 with nwjs to create a game.
When there is music playing, it causes something so that when the app is closed, nwjs processes remain in windows task manager.
It doesn't matter if the audio is stopped before closing- as long as music starts, it doesn't close completely.
The type of audio file is .ogg, if that info is important.
Let me know if you need more information.

**Comment by rogerwang** [comment]
Does chromium browser behaves thisway with the same page in the same system?

**Comment by prominentdetail** [comment]
No, chromium browser closes completely. No processes are shown in windows task manager.

**Comment by rogerwang** [comment]
Could you please upload a sample web page?

**Comment by prominentdetail** [comment]
https://1drv.ms/u/s!AhHSZHEulqh_gU3Th80nrXyoYoej

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8.1 with nwjs-sdk-v0.24.3. The nwjs processes end when the app closes(audio is playing)

**Comment by Christywl** [comment]
close until there is more information
