### ISSUE TITLE
xajax function called by "close" event sometimes works, sometimes it doesn't

### ISSUE THREAD

**Issue by cybercharles** [nwjs/nw.js#5012]
Hi everybody!! I'm from Mexico, I'm doing some desktop app hosted in a remote server, but called to desktop via nwjs.  There's a PHP - XAJAX function that executes when the user closes the window, but it only works sometimes and sometimes it doesn't, and i don't know why.  The calling to the function is like this:

```
win.on('close', function() {
  xajax_sesion_close(1);
  this.close(true); 
});
```

The XAJAX function code:

```
function sesion_close($value) {
    $out = new xajaxResponse(); 
    openupdate("tbsessions", "number", "number - ".$value, "", null, "", null, "", null, "", null, "", null, "", null, "", null, "", null, "", null, "id", "=", 1, "", null, null, "", null, null, "", null, null, "", null, null);     
    $out->Alert("Well Done!!"); 
    return $out;        
}   
```

I don't know what can be wrong with it, i hope you can find something.  Sorry about my english, i know it's pretty bad

**Comment by kailniris** [comment]
Use the https://groups.google.com/forum/#!forum/nwjs-general group for asking questions not related to bugs.

Btw sometimes xajax_sesion_close(1) will happen later then this.close(true). you have to wait for xajax_sesion_close(1) to happen first, with callback if possible or with setTimeout

**Comment by Christywl** [comment]
@cybercharles , does kailniris's advice work for you?

**Comment by rogerwang** [comment]
close until more information is available.
