### ISSUE TITLE
About compatibility 

### ISSUE THREAD

**Issue by hisune** [nwjs/nw.js#5019]
My nwjs version is 0.12.3.

My question is:
Part of my user can't open my app(probably 1/10 of all users). like this:
![ttt](https://cloud.githubusercontent.com/assets/7941669/16289901/d8ee1d24-392b-11e6-9b49-4ace8cb07694.jpg)

As far as I know, all user's system is win7 x64. But in my test, its ok.

Anybody who can tell me how to find the solution to the problem?

**Comment by rogerwang** [comment]
http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

and please ask questions in the mailing list.
