### ISSUE TITLE
Feature Request: Kiosk command line switch

### ISSUE THREAD

**Issue by mrohnstock** [nwjs/nw.js#502]
Would be great, if a command line switch could get added, to start node-webkit in kiosk-mode.
(without creating package.json with:

``` json
{
  "window": {
    "kiosk": true
  }
}
```

or adding

``` js
<script>
var gui = require('nw.gui');
gui.Window.get().enterKioskMode();
</script>
```

to sourcecode)
##

**Comment by sebastianvilla** [comment]
:+1:

**Comment by baconface** [comment]
@sebastianvilla Just so you know, these have been implemented.

**Comment by sebastianvilla** [comment]
Oh really, we tried launching nw.exe from the command line with --kiosk and it does not turn on Kiosk mode (it does if kiosk is set true in package.json or via in app method per OP's notes)

**Comment by baconface** [comment]
Oops. My bad. I read this as if he wanted the above solutions implemented.

**Comment by sebastianvilla** [comment]
ah, nw. With Chromium you can launch using the CL switches, --kiosk is one of the flags. Access to the built-in collection of switches from the CL would be great (i.e. debugging info, fps, turn off GPU etc). 

To make a case for Kiosk in particular, the app could launch normally during development and run in kiosk mode only when distributed, without having to always remember to set kiosk to true in package.json before packaging for distribution.

**Comment by baconface** [comment]
We have a POS that runs in kiosk mode. We do a similar method but the other way around. The program will always run in kiosk mode. But when we build and run from our editor we feed it a command line argument to indicate we are testing. Before we fire off ```enterKioskMode()``` we check for this parameter via ```gui.App.argv[0]```. If found we don't go into kiosk mode. This way we don't have to remember to set anything before releasing a production build.
