### ISSUE TITLE
Serious Fonts Rendering Bug

### ISSUE THREAD

**Issue by patrickm** [nwjs/nw.js#5021]
**This is a very serious bug with disappearing fonts/texts after opening a frameless window.**

### Versions:
* Affected nwjs versions: 0.14.x and 0.15.x (tested)
* Affected os: win7, os x 10.11.5 (tested)
* Possible bug in nwjs / chromium: nwjs

### Bug Description:

Site uses custom fonts via @font-face.

Set custom font to h1 and h2, hide h2.

Open a frameless window with css that has the same @font-
face declarations.

Show h2, h2 text won't be visible unless you toggle some css in devtools.

### Reproduction:

1. Clone https://github.com/patrickm/nwrenderingbug
2. run nwrenderingbug project as nwapp in nw 0.14.x or nwjs 0.15.x (mac or win)

### Related bugs:

Maybe it's related to *NSWindow warning: adding an unknown subview*

See #4336

**Comment by patrickm** [comment]
![image](https://cloud.githubusercontent.com/assets/206838/16302472/a8a33346-394b-11e6-9425-a4f8c133349b.png)

Notice test2 has no text in red box

**Comment by rogerwang** [comment]
Does it happen only with frameless window? Your screenshot shows a framed window.

And does the page work well in Chromium browser in the same system?

**Comment by patrickm** [comment]
This screenshot shows the finished state, when you run demo there's a button that will load a frameless window and then it will display red boxes (2 and 4) 
@rogerwang please clone this repo and run it yourself

It works in any browser, in general that bug is only present in nwjs because it's happening after you show element in dom AFTER opening a frameless window

**Comment by rogerwang** [comment]
I tried you sample and I don't think frameless matters -- if I change it to "frame: true" the demo still behave the same way.

When you said "it works in any browser", do you have a comparable case working in browser? -- do the same window opening trick as well. It may probably behave the same way in browser. Maybe the window opening trick triggers some issue inside chromium browser.

**Comment by patrickm** [comment]
You're right, fame:false doesn't change anything.
It works in chrome and canary - meaning texts display properly

Makes it unrelated to  #4336

@rogerwang any ideas ?

**Comment by patrickm** [comment]
I would say.. if it's not related to frame setting it makes this issue even widespread and more dangerous

**Comment by patrickm** [comment]
Updated https://github.com/patrickm/nwrenderingbug to support testing in browser, opened window now has a frame

**Comment by rogerwang** [comment]
Thanks for the demo. I made a PR for your repo to make it work in Chrome browser as a Chrome App so that we are testing the same thing (in your version the callback is called as timeout callback, not exactly the same time as my version as a window open callback). Unfortunately Chrome has this bug too. NW behaves the same as Chrome browser. So it should be reported to upstream: http://crbugs.com/
