### ISSUE TITLE
Include "minidump_stackwalk" tool in SDK build

### ISSUE THREAD

**Issue by benjismith** [nwjs/nw.js#5023]
It seems like the only option for reading NWJS crash dumps right now is to build the "minidump_stackwalk" tool from source. I haven't been able to find pre-compiled binaries anywhere, or even any real instructions for building on a Mac.

It would be very handy to have this tool as part of the SDK build.

**Comment by rogerwang** [comment]
Thanks. Will do that.

**Comment by rogerwang** [comment]
Unfortunately windows build is not supported in upstream. But you can still decode windows dump files in Linux or OSX systems.

**Comment by benjismith** [comment]
Awesome. Thank you!
