### ISSUE TITLE
V8 differences between NW.js 0.15.3 and Node.js 6.2.2

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#5025]
Following is the comparison of V8.h between NW.js 0.15.3 (v8 version: 5.1.281.65) and Node.js 6.2.2 (v8 version 5.0.71.52):

![sample](https://cloud.githubusercontent.com/assets/471928/16330735/0f70441a-3a1e-11e6-9d19-6b58838e826f.png)

It will cause `IsUndefined()` and many APIs returns bad value **when used in native modules built directly with node-gyp or npm**.

One example is Sqlite3. When sqlite3 is built with node-gyp directly using Node.js 6.2.2, following sample app failed to run and threw `Callback expected` error at `db.run()`, which means it requires a callback function. However it runs without problem with Node.js 6.2.2 directly.

```javascript
// hack sqlite3 to find correct path of binaries built for node
delete process.versions['node-webkit'];

var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

db.serialize(function() {
  db.run("CREATE TABLE lorem (info TEXT)");
});

db.close();
```

**Comment by childwho** [comment]
can't run [firmata.js](https://www.npmjs.com/package/firmata)(including serialport) perfectly in nw.js

**Comment by ghostoy** [comment]
@childwho You can ask questions in our mailing list https://groups.google.com/forum/#!forum/nwjs-general. And if you believe it's a bug, please submit a new issue with necessary details, including your sample app, NW.js version and OS.

**Comment by danielsokolowski** [comment]
Is there any way to avoid having the nw-gyp hack?
