### ISSUE TITLE
I can not remove shortcut key at menuItem

### ISSUE THREAD

**Issue by phanthinh** [nwjs/nw.js#5026]
Hi everybody!

I have problem broken with menuItem at window XP. 

![2016-06-24_08h43_57](https://cloud.githubusercontent.com/assets/5910795/16334212/d1742a58-3a29-11e6-99f6-5dd32156b9cb.png) 

I can not remove it with shortcut key. What can help me at here?

Thanks all

**Comment by phanthinh** [comment]
@ghostoy @rogerwang 

Can you help me?

**Comment by ghostoy** [comment]
Would you mind to post sample code? Is it part of tray?

**Comment by phanthinh** [comment]
@ghostoy 

Hi, i send my code below:
```

var itemOnline = new gui.MenuItem({
    type: 'normal',
    label: status.online.label,
    icon: status.online.icon,
    iconIsTemplate:false,
    click:function(){
      statusItem.label = status.online.label;
      statusItem.icon = status.online.icon;
      userService.changeStatus(1);
    }
  });
```

**Comment by ghostoy** [comment]
@phanthinh I can confirm the bug. Will fix it soon.

**Comment by phanthinh** [comment]
@ghostoy Thank for support
