### ISSUE TITLE
options WebRTC

### ISSUE THREAD

**Issue by c3g2e** [nwjs/nw.js#5027]
please, do options to package.json, that off WebRTC.

how difficult this feature?
how long time need that build project nwjs of source?

**Comment by rogerwang** [comment]
do you need an option to turn off webrtc?

**Comment by c3g2e** [comment]
yes. i know that can off webrtc at extension in google chrome, maybe their can use in nwjs project. but, i want full off webrtc in my project or use webrtc, depending from my specific project.

**Comment by rogerwang** [comment]
How do you turn off webrtc in Google Chrome?

**Comment by c3g2e** [comment]
this extension turn off https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml?hl=ru

if i'm not mistake extinsion from google chrome can be used in nwjs, but i'm afraid at artful manipulation can turn on again. I would like to avoid such situations.

**Comment by rogerwang** [comment]
You can call the following JS in your app to do the same thing as the extension from Google:

```js
                chrome.privacy.network.webRTCIPHandlingPolicy.set({
                    value: 'default_public_interface_only'
                });
```

**Comment by c3g2e** [comment]
i know this. 
at call chrome.privacy.......... i can be sure that don't turn on this option of iframe (nwdisable and nwfaketop)?
