### ISSUE TITLE
Window position value only update after mouse release

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#5028]
Hi,

Is there a way to get when the window start moving (i.e the user starts dragging the window)? because the event "move" and also the x and y values are only updated AFTER the user releases the mouse. Also I am doing this in borderless mode with a draggable div and I did try to detect on mousedown and it doesn't work on that kind f div.

Edit: I am fine with a solution that just tells me to know when the window starts moving even if it doesn't tell me the co-ordinates.

Thanks,
Anesu

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
