### ISSUE TITLE
window.focus/show on OSX

### ISSUE THREAD

**Issue by Kajinor** [nwjs/nw.js#5031]
Hello everyone,

first of all, I don't know if there is already a workaround but: On OS X window.focus/show doesn't work as expected if you want to use is to simulate modal-windows. It seems the chromium developers implemented a timer on OS X to check when was the last call of windows.show/focus and if the time-span is too small they will not focus the window. You can find this here:

https://github.com/nwjs/chromium.src/blob/5c2963ff9ad644fa2c50894b0fe6a757341c4d31/chrome/browser/ui/cocoa/apps/native_app_window_cocoa.mm#L500

We played around with it and just removed the timer stuff and then everything works as expected. No side effects so far it seems. However, it requires a custom build of NW.js which is a bit uncomfortable because we cannot update to new versions without rebuilding NW.js. 

It seems that timer stuff was implemented to fix another kind of OS-X specific bug in Chrome but maybe that isn't relevant for NW.js applications? (Didn't read everything about that yet). I was just thinking that for NW.js the timer stuff could be removed to give full control about focus handling? Much better would be to have native modal window-support of course but I think thats a bit more complicated.

Thanks,
Kajinor

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
