### ISSUE TITLE
Can't control IME in input

### ISSUE THREAD

**Issue by firzen** [nwjs/nw.js#5032]
* All NWJS version
* MacOS / WindowsXP / Windows7

Sometimes we need to disabled IME ( chinese / japanese keyboard) strict in some field. But Nwjs can't do that.

**Comment by rogerwang** [comment]
How would you do that in Chromium browser?

**Comment by firzen** [comment]
Dear Roger
For example, in many inputbox do not accept Chinese, we can disable the IME in that box. Or some inputbox need caps on, we can make caps on to make user do not need to switch IME or press Caps Lock btn.

**Comment by rogerwang** [comment]
I see that in mobile browsers, but I'm not sure desktop Chrome browser support this. Could you please show an example?

**Comment by firzen** [comment]
Chrome browser does not support that feature :( 
Can NWJS support ?

**Comment by rogerwang** [comment]
We'd like to but currently we don't have resources for that.
