### ISSUE TITLE
Margin option support for printer api

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5033]
Can we have margin option support for printer api please?
I created an invoice printer app and everything works flawlessly with the printing api expect that I can't change margin options. I found out in the app Preferences file there is 2 options regarding to this.
"marginsType\":3 // 0 is for default margin, 1 is for no margin 2, is for minimal margin, 3 is for custom margin
'customMargins': { 'top': 12, 'right': 12, 'bottom': 12, 'left': 12 }

Can you please upgrade the print api with margin option support?

**Comment by rogerwang** [comment]
This is fixed in chromium repo and will be available in the next nightly build. cc #4911

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/06-28-2016/nw15-250f6cb-db31318-3ee2c58-8655cb9/v0.15.5/

**Comment by kailniris** [comment]
Tested the new build, everything works fine expect the 'marginsType': 2 (Minimum) it works same as the  'marginsType': 1 (no margin).
