### ISSUE TITLE
Add publisher for nw.exe for win10 SmartScreen

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5037]
![smartscreen](https://cloud.githubusercontent.com/assets/19587188/16404867/2c89c0de-3d03-11e6-8cd3-ed7296c1b258.jpg)

At first run windows 10 terrorises me with this security alert. Not a big deal cuz it only shown once but it maybe an issue when distributing an nw.js app.

**Comment by mscreenie** [comment]
You should package your app so your app files are combined into an .exe. You would then digitally sign it or digitally sign an installer that unpacks the app. 

I don't think much can be done here although I may be mistaken. It's up to the developer here.

**Comment by kailniris** [comment]
Oh, thanks for the info, its all good that way too.

**Comment by geek1011** [comment]
You can also launch your nw.js app from a batch file. This will skip smartscreen.

**Comment by davecarlile** [comment]
On windows 10 right-click nw.exe and select the "Unblock" checkbox. It's flagged on your computer because it has the mark of the web.
