### ISSUE TITLE
Print api issues

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5040]
After several tests i founds some issues regarding to the print api:

Can not print to a shared printer:
`win.print({"printer": "\\OFFICE-5\HP LaserJet P2035" });`
The printer name was returned by
`win.getPrinters(function(printers){console.log(printers)});`

Margin related issue:
"marginsType": 2 does not change top and bottom margins to minimum.
```
"marginsType": 3,
"marginsCustom": { "marginBottom": 12, "marginLeft": 12, "marginRight": 12, "marginTop": 12 }
```
does not change top and bottom margins to 12 which is equals to minimum.

Whole function:
```
win.print({
   "printer": "SHARP AR-5620N",
   "marginsType": 3,
   "marginsCustom": { "marginBottom": 12, "marginLeft": 12, "marginRight": 12,  "marginTop": 12 },
   "mediaSize": { "name": "invoice", "width_microns": 210000, "height_microns": 297000, "custom_display_name": "invoice", "is_default": true }
   });
```

Elements which has page-break functionality will prevent printing the elements after them.
I have an element like this:
`<div class="page-break"></div>`
Whit this class:
```
@media all {
	.page-break	{
    display: block;
    page-break-before: always;
  }    
}
```
If i print this page with window.print() the elements after this element will be on another page but if i print this page with win.print({"printer": "SHARP AR-5620N"}); the elements after this page-breaker will disappear and the printer will print empty pages after this element.

Using windows 10 64 bit.

With this nightly build
http://dl.nwjs.io/live-build/06-28-2016/nw15-250f6cb-db31318-3ee2c58-8655cb9/v0.15.5/

Thanks You!

Solutions found:
Shared printer: win.print({"printer": "\\\\OFFICE-5\\HP LaserJet P2035" }); solves the issue
Margins: works as intended

**Comment by kailniris** [comment]
Also worth to mention both page-break and margin work with "pdf_path": "C:/Dev/test.pdf"

**Comment by kailniris** [comment]
@rogerwang I made some other test and I have an update about this issues.
Margins works nicely, did not know what was wrong yesterday.

About the page break issue:
The problem is not with the page break, the print api just won't print pages after 2 page.

I made a test case.
HTML:
```
<html>
<head>
<style type="text/css"></style>
</head>
<body>
  <div class="page">page1</div>
  <div class="page">page2</div>
  <div class="page">page3</div>
  <div class="page">page4</div>
  <div class="page">page5</div>
</body>
</html>
```
CSS:
```
.page {
    width: 210mm;
    height: 297mm;
    padding: 50px;
}
```
Then i call the print with:
```
nw.Window.get().print({
                    "printer": "HP LaserJet P2035",
                    "marginsType": 3,
                    "marginsCustom": { "marginBottom": 0, "marginLeft": 0, "marginRight": 0, "marginTop": 0 },
                    "mediaSize": { "name": "test", "width_microns": 210000, "height_microns": 297000, "custom_display_name": "test", "is_default": true }
                });
```

The problem is: page3, page4 and page 5 are empty pages. Tried with multiple different printers, same result.

If i print it with window.print() it works as it should.

Can you please look into this? My app is almoast ready only this issue remained to resolve.

**Comment by GopianiS** [comment]
nw.Window.get().print({printer: "MyPrinterName"}) does not work for me within the app, it does not print silently and also sets the destination to "Save as PDF". When I do nw.Window.get().print({printer: "MyPrinterName"}) via devtools, it works just fine.

**Comment by kailniris** [comment]
@GopianiS 
With this version:
http://dl.nwjs.io/live-build/06-28-2016/nw15-250f6cb-db31318-3ee2c58-8655cb9/v0.15.5/

If you try to use a non existing printer nothing will happen, in later versions a default printer will be used.

Try the following:
nw.Window.get().print({"printer": "MyPrinterName"});

**Comment by IBSNA** [comment]
@kailniris When you print to the network printer with `win.print({"printer": "\\OFFICE-5\HP LaserJet P2035" });`

`\\` is escaped, so the printer name becomes `\OFFICE-5HP LaserJet P2035`

Try `win.print({"printer": "\\\\OFFICE-5\\HP LaserJet P2035" });`

**Comment by kailniris** [comment]
@IBSNA Thanks It works!

**Comment by IBSNA** [comment]
@kailniris Great!

**Comment by fanchou** [comment]
may be we should encapsulate chrome serial api，then we can use printer without driver and get more control of printer，and control hardware

**Comment by kailniris** [comment]
All the issues were solved expect the missing pages bug, its a chromium bug
