### ISSUE TITLE
v0.15.4   couldn't  load plugin....

### ISSUE THREAD

**Issue by lipan** [nwjs/nw.js#5041]
Windows: 32bit  

PeperFlash 

help!

**Comment by lipan** [comment]
{
    "description": "Pepper Flash Player", 
    "name": "Flapper", 
    "version": "21.0.0.216", 
    "x-flapper-revision": "45688", 
    "x-ppapi-arch": "ia32", 
    "x-ppapi-os": "win",

**Comment by rogerwang** [comment]
close as duplicate of #4979

**Comment by RohitSharma27** [comment]
Please refer the comment on #4979 and see if it helps.

**Comment by lipan** [comment]
@RohitSharma27   thanks !
