### ISSUE TITLE
how to debug node module in nw

### ISSUE THREAD

**Issue by aeolusheath** [nwjs/nw.js#5045]
except console.log in html page \<script\> tag.  

the modules quoted by  require
I use console.log. 
it doesn't work.

anybody has idea?

**Comment by RohitSharma27** [comment]
You can use any logger node module to write your logs on some file, other than the console we have in nw. And please ask questions in the mailing list.
P.S. : node modules' log will be there in the background page's console i.e. the one that you get from inspect background page.

**Comment by rogerwang** [comment]
Please ask  questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
