### ISSUE TITLE
0.15 bugs? middle click-open new window event miss !

### ISSUE THREAD

**Issue by wzquyin** [nwjs/nw.js#5046]
version:0.15.4 win 32bit
os:win 10 64
useing webview tag open a website,middle click a link in the website ,if this link tag has no "target" tag:
(like： <a href="***">clickme</a>),nwjs will open a full new window to open this link, but I can`t capture this event by "new-win-policy" or weview.newwindow event .

but in old version like 0.13.*, I can capture webview.newwindow event when i do that.

am i miss something between 13-15 ? or just the nwjs-dev group forgot add this event?

**Comment by bezformy** [comment]
I noticed this too. When the link has a `target="_blank"` attribute the `new-win-policy` event is fired. But when I try to `ctrl+click` on a link that has no `target` the event is not fired.

**Comment by Christywl** [comment]
@wzquyin , could you please upload your test for to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
