### ISSUE TITLE
Update package and distribute docs to be based off nwjs-builder rather than nw-builder.

### ISSUE THREAD

**Issue by orther** [nwjs/nw.js#5054]
Considering [nw-builder](/nwjs/nw-builder) doesn't seem to support the versions after 0.12.3 of nw.js (I had tons of issues and ended up moving on to [nwjs-builder](/evshiron/nwjs-builder)) I believe [nwjs-builder](/evshiron/nwjs-builder) should replace [nw-builder](/nwjs/nw-builder) on the Package and Distribute doc page. I was considering forking this repo and updating the Package and Distribute page to link to and show [nwjs-builder](/evshiron/nwjs-builder) examples rather than [nw-builder](/nwjs/nw-builder) but before I spend time doing that I wanted to ask if that is something you would even appreciate/consider for pulling?

If people haven't looked at [nwjs-builder](/evshiron/nwjs-builder) for a robust easy way to build nwjs v0.13.x+ apps for the 3 major platforms (OSX, Windows, Linux) I highly recommend you take a look.

**Comment by rogerwang** [comment]
CC @adam-lynch

**Comment by adam-lynch** [comment]
@orther thanks for the feedback. Sorry about this. We're working on it right now and we're very close. The creator of nwjs-builder is onboard. See #327 and #333. It just needs to be tested a bit more (I'll be doing some testing on Windows myself today). If you want to test that branch, you can via `npm i --save nwjs/nw-builder#newer_versions`. 

So... soon nw-builder will be fine and then we'll move onto adding stuff like the ability to choose flavors and other stuff. So I think this can be closed. Thanks again.

**Comment by adam-lynch** [comment]
Woops, I mean https://github.com/nwjs/nw-builder/issues/327 and https://github.com/nwjs/nw-builder/issues/333

**Comment by orther** [comment]
I'll likely get testing and involved in helping update `nwjs/nw-builder` once I get some more free time (i.e. after I'm done pushing my nwjs based app's major release and migration to nwjs v0.15.4) in a week or two.

Thanks for the feedback @adam-lynch

**Comment by adam-lynch** [comment]
:+1:

**Comment by rogerwang** [comment]
I don't see any one is picking up nwjs/nw-builder so far. So I'm re-opening this issue for the official documentation.  CC @evshiron

@ghostoy please check whether the steps in the official documentation asap. If they are broken, the official documentation should be fixed immediately.

**Comment by evshiron** [comment]
I have watched nwjs/nw-builder#327 but I am afraid I am not going to bother maintaining 2 similar projects, when to me `nwjs-builder` is more familiar and requires less efforts.
I am glad that `nwjs-builder` could be listed in the documentation as an option for building applications. It's not widely used though, but things should just work.
If there is anything I can help, let me know.

**Comment by rogerwang** [comment]
Thanks @evshiron I didn't notice the name difference.

We are thinking about the change for official doc but we'll for sure list your project since it's actively maintained.

**Comment by chino23** [comment]
those builders are greatly appreciated!

**Comment by ghostoy** [comment]
Currently both [nw-builder](https://github.com/nwjs/nw-builder) and [nwjs-builder](https://github.com/evshiron/nwjs-builder) are listed as recommended tools for packing NW.js based apps on official document site. Close this issue.
