### ISSUE TITLE
Double click on nw.exe after process is started ?

### ISSUE THREAD

**Issue by zxvfbg** [nwjs/nw.js#5057]
I am using nwjs 15.4 x86 with Windows 7

How we can show and focus a window which is hidden on the tray ?

Is there some event fired or something like that ?

Thanks

**Comment by jwilcurt-salesforce-com** [comment]
http://docs.nwjs.io/en/latest/References/Tray/

**Comment by zxvfbg** [comment]
@jwilcurt-salesforce-com i am asking about nw.exe not about the tray.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
