### ISSUE TITLE
Choose directory dialog shows "Upload" instead of "Select" on OS X since 0.13

### ISSUE THREAD

**Issue by gaspard** [nwjs/nw.js#5058]
The select directory `nwdirectory` has a wrong validation button. It shows "Upload" instead of "Select".

OS: Mac OS X 10.11.5

This simple html file and a manual click on the input is enough to view the problem:
```html
<html>
  <head>
    <title>File test</title>
  </head>
  <body>
    <input type='file' nwdirectory/>
  </body>
</html>
```

Affects all versions from 0.13 (0.14, 0.15 and 0.16beta)

![screenshot 2016-07-01 00 09 53](https://cloud.githubusercontent.com/assets/21707/16506131/c5e4aff4-3f20-11e6-8bfe-6c26b1a9640f.png)

This is what 0.12 returns and what it should be:

![screenshot 2016-07-01 00 11 13](https://cloud.githubusercontent.com/assets/21707/16506171/0307274a-3f21-11e6-97c9-af54b643f0cd.png)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
