### ISSUE TITLE
生成的exe文件无法用upx391进行压缩（nwjs-v0.15.4-win-x64）

### ISSUE THREAD

**Issue by tianweimian** [nwjs/nw.js#5059]
生成的exe文件无法用upx391进行压缩（nwjs-v0.15.4-win-x64），错误如下，exe可运行

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91w       Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: lop_boxed.exe: CantPackException: section size problem

Packed 1 file: 0 ok, 1 error.

**Comment by rogerwang** [comment]
Please use English so all users can read.
