### ISSUE TITLE
Add git tag for v0.15 and later

### ISSUE THREAD

**Issue by linquize** [nwjs/nw.js#5060]
No git tag after v0.14.
Could you tag those versions?

**Comment by rogerwang** [comment]
Before we tag it, you can find the commit id for all the 4 repos in each version after you launch nw. It's at the right bottom. <nwjs>-<chromium>-<v8>-<node>

**Comment by rogerwang** [comment]
We have added the tags for some of 0.15.x versions and later version. We also added a step for git tags in our release scripts.
