### ISSUE TITLE
Programmatically identify SDK from Normal

### ISSUE THREAD

**Issue by kimhonoridez** [nwjs/nw.js#5062]
How to programmatically identify SDK from Normal build?

**Comment by divinemanwah** [comment]
Maybe like this:

```
var win = nw.Window.get(), isSDK = 'showDevTools' in win;
```

where `isSDK` yields `true` if you are using the SDK build.

**Comment by iteufel** [comment]
var isSDKBuild = (window.navigator.plugins.namedItem('Native Client') !== null);

**Comment by ghostoy** [comment]
I think we can add the flavor to `process.versions`. @rogerwang

**Comment by rbeer** [comment]
@iteufel 
Your solution would give a false positive with the upcoming NaCL flavor, wouldn't it?
https://github.com/nwjs/nw.js/wiki/Build-Flavors
@divinemanwah 
Your's yields `true` with the normal version of v0.19.5, but happily throws errors then
```text
[24298:24298:0110/140755:ERROR:CONSOLE(1)] "Uncaught ReferenceError: DevToolsAPI is not defined", source:  (1)
[24298:24298:0110/140755:ERROR:CONSOLE(1)] "Uncaught ReferenceError: DevToolsAPI is not defined", source:  (1)
```

**Comment by iteufel** [comment]
@rbeer No the `NaCL` flavor isn't used anymore.

**Comment by rbeer** [comment]
@iteufel 
Huh... How was I under the impression, 0.13.x would be an _upcoming_ release? :joy:
Your line works just fine, then. Thank you! :)

**Comment by chadams77** [comment]
Doesn't work if plugins are disabled, any plans to adding the flavor id to process?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
