### ISSUE TITLE
win.isDevToolsOpen() not supported in v0.15.3?

### ISSUE THREAD

**Issue by kimhonoridez** [nwjs/nw.js#5063]
I wanted to trigger this function but it is undefined:

```
var win = nw.Window.get();
win.isDevToolsOpen();
```

**Comment by Christywl** [comment]
win.isDevToolsOpen() is still undefined on nwjs-sdk-v0.21.4. But I find that this is not supported for now in the docs(http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues). @rogerwang , am I right?

**Comment by rogerwang** [comment]
close as duplicate of #4487
