### ISSUE TITLE
NWWindow.reload() breaks window methods; .isFullscreen return false, leaveFullScreen not working

### ISSUE THREAD

**Issue by VoidVolker** [nwjs/nw.js#5064]
**OS**: Windows (7,8.1); Linux (Fedora 23)
**nwjs versions:** 14.0-16.0

Test case one - all works as expected:

``` javascript
var w; nw.Window.open('http://google.com', function(win){ w = win; setTimeout(function(){ win.close(); },4000) });
```

Test case 2 - use `win.reload()`:

``` javascript
var w; nw.Window.open('http://google.com', function(win){ w = win; win.reload(); setTimeout(function(){ win.close(); },4000) });
```

And nothing happens. Manual try:

``` javascript
w.close(); w.enterFullscreen();
```

Nothing happens.

Leaving of fullscreen is doesn't works too:

``` javascript
nw.Window.open('http://192.168.1.166:1337/test',function(win){ win.enterFullscreen(); setTimeout(function(){ win.leaveFullscreen(); },4000) });
```

**Comment by FayneAldan** [comment]
I believe that's intended since you are recreating the window. Try regrabbing the window (`nw.Window.get()`) after reloading.

**Comment by Christywl** [comment]
`win.reload` works well for me in the new created window.
But `win.isFullscreen` returns `false` after the window enters the fullscreen mode and `win.leaveFullscreen()` doesn't work in the new window.

```
<script>
nw.Window.open('http://www.baidu.com',function(win){ 
setTimeout(function(){ win.reload(); },2000);
setTimeout(function(){ win.enterFullscreen();console.log(win.isFullscreen); },3000);
setTimeout(function(){ win.leaveFullscreen(); },4000);
setTimeout(function(){ win.close(); },5000);
});
</script>
```
```

Environment:
nwjs-sdk-v0.21.3
Linux/Windows
```

**Comment by xzhan96** [comment]
@rogerwang  if this indeed is a bug, I'd like to investigate it.

**Comment by xzhan96** [comment]
should be related with #5000

**Comment by xzhan96** [comment]
@VoidVolker 
This is not a bug. Chrome also has the same result with the sample code. 
For example, the console.log in below code will also output false in[ chrome app](https://developer.chrome.com/apps/app_codelab_basics).
```
chrome.app.runtime.onLaunched.addListener(function() {
  chrome.app.window.create('index.html', {
    id: 'main',
    bounds: { width: 620, height: 500 },
  }, function(win){ 
	setTimeout(function(){ win.fullscreen(); console.log(" ==== " + win.isFullscreen()); },3000);
	setTimeout(function(){ win.restore(); },4000);
	//setTimeout(function(){ win.close(); },5000)
  });
});
```
However, if you change part of the code to below, the output is **true**.
` setTimeout(function(){ win.fullscreen(); setTimeout( function() {console.log("xiaofeng: ==== " + win.isFullscreen());}, 1000) },1000); // the delay time is related with next function run time `
or
print the log in next statement 
`setTimeout(function(){ win.restore(); console.log(" ==== " + win.isFullscreen()); },4000);`

All the things above are the same with the results of nwjs. So it's maybe related with chrome design or code execution, **and not nwjs bug.**

@Christywl please double check and let's close it.

**Comment by Christywl** [comment]
Tried xiaofeng's code on chrome app , my results are same with his. 

```
false:
chrome.app.runtime.onLaunched.addListener(function() {
  chrome.app.window.create('index.html', {
    id: 'main',
    bounds: { width: 620, height: 500 },
  }, function(win){ 
	setTimeout(function(){ win.fullscreen(); console.log(" ==== " + win.isFullscreen()); },3000);
	setTimeout(function(){ win.restore(); },4000);
	//setTimeout(function(){ win.close(); },5000)
  });
});
```

```
true:
setTimeout(function(){ win.restore(); console.log(" ==== " + win.isFullscreen()); },4000);
```
