### ISSUE TITLE
can't set win.title on nw0.14.6

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#5065]
nw0.14.6 & winows7 32bit

win.title = "anything" not become effective. And set by document.title = "anything" also not become effective, but after win.reload(), title was changed !

**Comment by divinemanwah** [comment]
The title will really change if you reload the page, that is the expected behavior when using `document.title`.

**Comment by mangaga** [comment]
hello @ghostoy  @divinemanwah  
not only the win.title can't modify, also the Tray icon . And after win.reload(), it will really change.
chrome.extension.getBackgroundPage().tray.icon = './2.png';

And I use timmer to change the tray.icon also no effective on my remote iframe page.

function ToggleIcon()
{
	if(chrome.extension.getBackgroundPage().tray.icon == './1.png')
	{
		chrome.extension.getBackgroundPage().tray.icon = './2.png';
	}
	else if(chrome.extension.getBackgroundPage().tray.title == './2.png')
	{
		chrome.extension.getBackgroundPage().tray.icon = './1.png';
	}
}

function NotifyTray()
{
    if (nw.App.TrayTimer == null) {
        var timmer = setInterval(ToggleIcon, 500);
        nw.App.TrayTimer = timmer;
    } else {
        clearInterval(nw.App.TrayTimer);
        delete nw.App.TrayTimer;
        var timmer = setInterval(ToggleIcon, 500);
        nw.App.TrayTimer = timmer;
    }
}

**Comment by ghostoy** [comment]
@mangaga I can confirm that `nw.Window.get().title=newtitle` doesn't work with 0.14 or later on Win 7 and Mac. But `document.title=newtitle` always works. Please double check if you are running in the top frame.

As for the tray, please create another issue and I will follow up.

**Comment by mangaga** [comment]
thank you for your reply. I solved this two problem. 
So I'll close this issue.
