### ISSUE TITLE
session lost after open the develop tool and close it on nw0.14.6

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#5066]
nw0.14.6 & windows7 32 bit

open the develop tool frist time,local cookies as follow:

and open the develop tool  second time ,the session was lost as follow:

**Comment by cecilpeng** [comment]
I have the same problem in nw-v0.14.7. Who can help me?

**Comment by hxfdarling** [comment]
I have the same problem in nw-v0.14.7.
