### ISSUE TITLE
webview in 0.15 bugs!!!!

### ISSUE THREAD

**Issue by wzquyin** [nwjs/nw.js#5067]
nwjs :0.15 windows x86
os:win10 64
in webview middle click any link tag A,if the attr target of A is not  “_blank”, it will open a new nwjs, and you can`t get "newwindow" event from webview;

TAG A like
a target="any thing not _blank"

**Comment by Christywl** [comment]
@wzquyin , is this issue still reproduced in your test on the latest nwjs? If yes, could you please upload your test to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
