### ISSUE TITLE
OSX Flash player broken since 0.15.0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5068]
Still having troubles with this since #4826.
Using PepperFlash from Chrome Canary which now appears to include a manifest.json file.
It appears that up to 0.14 any installed flash within NW.js package would work OK even without chromium-args specified in package.json and if not available then system installed pepper flash would be used.
Since 0.15.0 I can't use flash installed within NW.js and can only use system installed pepper flash if the manifest.json is set lower than 21.0.0.213

Tests::
For the following tests the system installed PepperFlash is 21.0.0.242
System flash will be located at –
Macintosh HD/Library/Internet Plug-ins/PepperFlashPlayer/
Note: the manifest.json file is set for "x-ppapi-arch": "mac",
The manifest.json file for the NW.js installed flash is set to  "x-ppapi-arch": "x64",

0.14.5  OSX x64 SDK 
PepperFlash 22.0.0.200 installed in NW.js
Manifest.json set to 22.0.0.200
No chromium-args used in package.json
Webview tag used in HTML.

PepperFlash  works OK  and About Flash shows 22.0.0.200 
If the NW.js PepperFlash is not available then the system installed PepperFlash is used and About Flash shows 21.0.0.242.
 If there is no flash available at all then webview will show a white rectangle.

0.15.0  OSX x64 SDK  & 0.15.5 OSX x64 SDK
PepperFlash 22.0.0.200 installed in NW.js
Manifest.json set to 22.0.0.200
No chromium-args used in package.json
Webview tag used in HTML.

PepperFlash FAIL’s and webview shows –
Adobe Flash Player needs your permission to run.
If the manifest.json is changed to 21.0.0.182 (flash still 22.0.0.200) the plugin will not work but NW.js will use the system installed PepperFlash and work OK – About Flash will show 21.0.0.242. 
If the manifest.json was changed to 21.0.0.213 the system flash would not be used.

If there is no flash available at all then webview again the permission error.

It seems that up to 0.14 flash worked OK but something changed prior to 0.15.0 and flash will only work if the system installed flash is available but only if the version in manifest.json is lower than 21.0.0.213 (eg: 21.0.0.182).

I also tried flash on Win 10 and got similar results - 0.14 and prior was fine - maybe more clarity is required on the chromium-args path method but 0.14 and prior didn't need them and worked fine.

The test project is the same as per #4826.
[PepperFlashTest.zip](https://github.com/nwjs/nw.js/files/344624/PepperFlashTest.zip)
 
Also took note of #4979 for the Win scenario but couldn't get the chromium-args to work for me although I don't have PepperFlash installed on the Win 10 system at all.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/07-06-2016/nw16-0a316ed-964c7ef-d88e3a2-77f39b5/v0.16.0/

**Comment by Blatman** [comment]
Thanks Roger - tried osx-sdk-x64 with 22.0.0.200 and works well.
