### ISSUE TITLE
Cannot load node_modules if %TEMP% is on a RAM disk

### ISSUE THREAD

**Issue by linquize** [nwjs/nw.js#5070]
My `%TEMP%` is on a ram disk `Z:\Temp`

* nwjs: 0.15.4 win64 (normal and sdk)
* Win 7 x64

I pack my app with `nw-builder` so that the app is appended to the end of `nw.exe`
My app has a `node_modules` directory with a library `minimist`

When I call `require('minimist')`, it throws exception 
```
Error: ENOENT: no such file or directory, realpath 'Z:\Temp\nw3264_28016\node_modules\minimist\index.js'
```
If you check that path, the js file actually exists.

If I set `%TEMP%` and `%TMP%` to a real hard disk, such as `C:\Temp`, the packed `nw.exe` loads the library `minimist` successfully.

**Comment by vsemozhetbyt** [comment]
Maybe this is connected with [this bug](https://github.com/nodejs/node/issues/6861) (see the end of the conversation).

**Comment by RohitSharma27** [comment]
Looks like @vsemozhetbyt is right. It seems that this is associated with node's implementation of fs.realpath. Can you try requiring the same module from node.js. Please use the same version as that of nw0.15.4

**Comment by linquize** [comment]
Yes, node 6.2.2 cannot load any file on RAM disk, but node 4.4.7 can

**Comment by rogerwang** [comment]
close since it's an upstream bug.
