### ISSUE TITLE
Window Icon Requirement?

### ISSUE THREAD

**Issue by divinemanwah** [nwjs/nw.js#5071]
Hi,

Is there a requirement in `v0.15` (SDK) for the window icon? `v0.13` was working fine before, but now I can't set an icon in `package.json`. Tested using the same image, but only worked in `v0.13`. I also saw an issue that was closed saying that the DevTools window icon would use the app's icon, but upon testing, it doesn't. I'm using Windows 7.

Thanks!

**Comment by divinemanwah** [comment]
Removing these options from `package.json` solved the problem:
```
"chromium-args": "--disable-devtools --disable-gpu"
```
But I need those in my app.

**Comment by rogerwang** [comment]
Could you please provide a sample?

**Comment by divinemanwah** [comment]
It turns out upon adding `--force-cpu-draw`, everything turns out okay.
```
"chromium-args": "--disable-devtools --disable-gpu --force-cpu-draw"
```
Taskbar icon is now shown correctly.

**Comment by Christywl** [comment]
close this issue per above comments.
