### ISSUE TITLE
when use new_win and change the href of the new window, the new_win.window did not changed.

### ISSUE THREAD

**Issue by leavesgreen** [nwjs/nw.js#5073]
hello, everybody,

i use the nw.js 
var new_win = gui.Window.get(window.open(www.163.com));
to show a new external window,which i can reach the html code in the website, but when i click a href and the new page is loaded; 
but when  i use  new_win.window try to get the new html dom , it  still showes the previous html code;
how can i get the new html code? in that situation?
thanks you all.
- we use v0.15
- win10 x64

**Comment by kailniris** [comment]
Use this insead:
nw.Window.open('https://www.google.com', {}, function openNewWin(newWin) {
   newWin.on('loaded', function winOnLoad() {
         console.log(newWin);
   });
});

Docs:
http://docs.nwjs.io/en/latest/References/Window/#window

**Comment by leavesgreen** [comment]
@kailniris 

thanks dear, 
I try what you said and it make sense.
but I found some website, maybe they use a server.transfer background on the server ,and the url seems not changed ,but page is different. so in that situation, I still got the wrong html dom.
I am not sure about that, I'll try more. thanks a lot.

**Comment by kailniris** [comment]
@leavesgreen can you show some example?

**Comment by Christywl** [comment]
@leavesgreen , is this issue still reproduced in your test? if yes, could you please provide a sample to reproduce?

**Comment by rogerwang** [comment]
close until more information is available.
