### ISSUE TITLE
The value of process.cwd () is not equal to __dirname when package all files into package.nw folder.

### ISSUE THREAD

**Issue by sean220** [nwjs/nw.js#5075]
1.These two values are equal when start the application with command line 'nw xxx/appRoot'.
2.The value of process.cwd () not refer to the home directory is causing the incorrect relative path in nodejs.

**Comment by ghostoy** [comment]
@sean220 Could you post a sample app?

**Comment by sean220** [comment]
Sorry,It just happen in a very weird situation, I create 'package.nw' folder use 'ln -s' on OSX,And test it on Window8 VM.

If just use 'mklink' to create 'package.nw' folder on window8,process.cwd() returns the correct home directory path.

**Comment by ghostoy** [comment]
Seems to be an issue of network fs. I'm closing this issue. Please reopen it if you see different.
