### ISSUE TITLE
The language of nw-v0.12.3

### ISSUE THREAD

**Issue by wpp2014** [nwjs/nw.js#5076]
The pop-up window shows English language but my system language is chinese
![2016-07-05 11 40 24](https://cloud.githubusercontent.com/assets/7447933/16573381/c101540a-42a5-11e6-9f2f-e5b032cd825a.png)
 
the version of nw is 0.12.3, my system is Linux Mint 17.3

**Comment by rogerwang** [comment]
0.12.x is not supported any more.

**Comment by wpp2014** [comment]
The nw-v0.15.0 also has the same problem.
