### ISSUE TITLE
How to use winAPI sendInput by NW?

### ISSUE THREAD

**Issue by comptron** [nwjs/nw.js#5077]
Hi,

I am using NW.js v.0.15.1, on windows 7
And i would like to know if there is a way to use the winAPI - sendInput.

Also, 
Is there a way to get the system type by code? (32 or 64 bit)

Thanks,

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
