### ISSUE TITLE
Drag and drop: drag out files - feature request

### ISSUE THREAD

**Issue by bennol** [nwjs/nw.js#5079]
A new requirement for an existing nwjs project of mine is being able to drag files (Images, PDFs) out of the app directly into programs like Word. 

The only possibility to do this right now (that I am aware of) is using DownloadURL like this
`evt.dataTransfer.setData("DownloadURL",fileDetails);`
Problem with this approach is that the DownloadURL isn't directly resolved to a local file path but is delivered as some kind of _streaming file_ or _file promise_ that can't directly be handled by targeted programs.

I've been looking into this for a while and there should be support in Chromium for it due to the [dragging out of downloaded files](https://cs.chromium.org/search/?q=DragDownloadItem&sq=package:chromium&type=cs).

For Electron there has been created an [API](https://github.com/electron/electron/pull/6333) for it very recently so that drag-out of native files works.  

I know there are probably other issues with higher priority but shouldn't this be a rather low hanging fruit for nwjs? I have no real overview of the codebase yet but would be willing to help implementing it.

**Comment by rogerwang** [comment]
Will support this. Does Chrome browser support something like this?

**Comment by lee99** [comment]
BTW, @rogerwang will fix this bug? [file dragover event can't through the webview](https://github.com/nwjs/nw.js/issues/4653)

**Comment by bennol** [comment]
@rogerwang If you download a file in Chrome and drag it from the _downloaded files list_ it is a normal file drag.

**Comment by bennol** [comment]
@rogerwang Can you estimate a rough time frame when this will be available? Not being impatient, just planning for a future project that relies on this feature and whether to switch to Electron for that release. Any information appreciated

**Comment by bennol** [comment]
Should be covered by #2200 (with bounty)

**Comment by hems** [comment]
@bennol / @rogerwang has this actually being solved? i have seen this project: https://github.com/Extensis/node-webkit-dragout but it looks like it's 3 years old and i didn't find any other updates regarding this issue on the official repo..

Am i missing something?
