### ISSUE TITLE
problem with @font-face url and relative path

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#5080]
nw.js 0.15.4
Windows, OSX, and GNU/Linux

No trivial example of the bug yet, though I can link to a binary of the application where it happens and give instructions to reproduce if needed.

I've got a bug in my application, and I'm trying to figure out whether it is due to a) nw.js, b) chromium, or c) something obvious that I'm missing.

I ship a ttf font for "DejaVu Sans Mono" with my app.  I use @font-face in css with the url() syntax to import my font into the page.  The ttf file is in the same directory as the css that includes it, which itself is in directory where my app's package.json is located.  I use a relative path inside url() which as the W3C docs say will be relative to the containing css.  This will successfully pull the font into the page in nw.js.

Then the bug starts.  It seems to happen on particular DOM mutations-- for example, if I delete some nodes that have SVG text, then create new nodes with SVG text at a different pixel font size.  What happens is that the new text will be invisible, and when I check devtools it tells me it is rendering a system font (liberation sans in my case).  This implies that the page could not load the font I specified with @font-face, and is falling back to a system font.

Furthermore, if I replace the relative path in url() with the equivalent base64-encoded data for the same font, the bug doesn't happen.

So...

I'm wondering if there is some kind of conflict between nw.js treating my local directory as "remote", and Chromium trying to keep the user secure by disallowing local resources from being used in the @font-face url.

Any ideas?  I can post a link to my app to demo the bug, but I don't have a small, trivial example to report in the issue tracker.

**Comment by frankhale** [comment]
Do you have a leading '.' in your font path like this: `url('./path/to/my/font')`, if not try it.

**Comment by RohitSharma27** [comment]
I have got relative paths ( like ../../) in my CSS which refer to images and these images weren't loading. I am gonna try and look deep in to what actually is happening in my case. But, it's just my guess and not an observation that chrome-extension:// protocol isn't working properly with relative paths.
I will try to find out the real cause tomorrow. :)

**Comment by jonwwilkes** [comment]
@frankhale: It's not a contradiction, but inconsistent behavior:

1. The window loads
2. I mutate the DOM by adding some nodes that use the font I specified in the relevant css with `@font-face` rule. These nodes display properly.  For example, if I look at the computed value for the font in devtools it tells me "DejaVu Sans Mono" and marks it as "remote"
3. I mutate the DOM by erasing those nodes, then I add new nodes which have a different font-size attribute but use the same font specified by the `@font-face` rule as above.  This time, however, the text is invisible-- it takes up space and I can get a bbox selection in devtools but it doesn't display.  Now devtools tells me the font is "Liberation Sans" and "local".

In other words, something happens during the DOM mutation that causes my font loaded with `@font-face` to be rejected and replaced with a system font for the newly created DOM nodes.

This is just one example of a DOM mutation that triggers the bug.  There are other (more complex) ways I've seen the bug happen.  I don't see an obvious relationship between the ways the bug manifests, but I can consistently reproduce it on all OSes supported by nw.js.

Also-- I mentioned SVG text originally, but the same bug applies to HTML elements (like `<div>`) as well.

Finally-- if I go into devtools and change the font-size for the buggy, invisible text nodes to any other value, they will display properly.  However, I've tried using different initial font-sizes and the bug still happens, so it doesn't seem related to the value I set for the font size.

**Comment by jonwwilkes** [comment]
A bit more data-- if I start with an svg or html element with text at font-size of "10px", delete it, then append a new element with font size >= "16px", the text remains visible and the font face correctly renders as "DejaVu Sans Mono".  If, however, my font-size for the new element is >= "10px" and < "16px", the bug triggers.

Again, I get no bug at all if I give the `@font-face` url as base64-encoded data for the same font.

**Comment by rogerwang** [comment]
What does the log say? https://www.chromium.org/for-testers/enable-logging

**Comment by jonwwilkes** [comment]
@rogerwang unfortunately that Chromium flag doesn't get me a log. :(

I'm fairly convinced that this is a bug with Chromium's rendering for fonts defined by the `@font-face` rule.  I saw lots of reports and discussions over the past few years of disappearing text in my Google searches.

I spent about 3 hours trying to whittle my application down to a trivial example, but I never got there.  What I can say is that the bug has something to do with two different windows referring to the same css file that includes a `@font-face` rule.  Opening the second window actually breaks the display of the `@font-face` font in the first window (as it falls back to a local font).  That breakage happens even without the two windows sharing a node.js module.

Anyway, I just gave up and base64-encoded the font I was referencing and put it directly in a css file.

**Comment by tphalp** [comment]
OS X: 10.11.6
nwjs: 0.16.1

I also have an app that creates multiple windows (just one, besides the main window), and uses relative urls in font-face. I'm experiencing the same thing with text not rendering (invisible). If I do not create the other window, the rendering issue goes away, and the text appears as it should.

**Comment by jonwwilkes** [comment]
@tphalp If you get a chance, could you try to post a small example app that consistently reproduces this bug?  I tried doing that but could never reproduce the bug outside of my own app... :(

**Comment by tphalp** [comment]
@jonwwilkes I'll try, but this project is fairly large, and I have other things that I need to work on. I may just inline the fonts via base64 as you mentioned, and be done with it.

**Comment by jonwwilkes** [comment]
@tphalp I understand.

An FYI: if you use the base64-encoded workaround, devtools no longer picks up the correct font name for the computed styles window.  It just shows some of the leading characters of the base64 data.

To the nw.js devs: the other difficulty of the workaround is that it makes it more complicated to add or change out the fonts.  Rather than just adding a font file to the dir and a path to a CSS file, you have to instead generate base64 output from the file, paste it into its own CSS file (otherwise the long data string makes it difficult to manipulate and browse the main CSS), and add an extra html line to pick up the CSS file that holds the base64-encoded font.

**Comment by oaleynik** [comment]
@rogerwang here is what chromium log says at the moment when bug is triggered (I have pretty solid steps to reproduce in this issue in our application)

```
[16471:1547:0922/083202:VERBOSE1:script_context.cc(111)] Created context:
  extension id:           obmdnneehibdanjlgbfflnbacibdafjg
  frame:                  0x13037a2164d8
  URL:                    
  context_type:           BLESSED_EXTENSION
  effective extension id: obmdnneehibdanjlgbfflnbacibdafjg
  effective context type: BLESSED_EXTENSION
[16471:1547:0922/083202:VERBOSE1:script_context.cc(111)] Created context:
  extension id:           (none)
  frame:                  0x0
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[16471:1547:0922/083202:VERBOSE1:dispatcher.cc(442)] Num tracked contexts: 4
[16471:1547:0922/083204:VERBOSE1:dispatcher.cc(590)] Num tracked contexts: 3
[16471:1547:0922/083204:VERBOSE1:script_context.cc(120)] Destroyed context for extension
  extension id: obmdnneehibdanjlgbfflnbacibdafjg
  effective extension id: obmdnneehibdanjlgbfflnbacibdafjg
[16471:1547:0922/083204:VERBOSE1:script_context.cc(120)] Destroyed context for extension
  extension id: 
  effective extension id: 
[16471:1547:0922/083204:VERBOSE1:script_context.cc(111)] Created context:
  extension id:           obmdnneehibdanjlgbfflnbacibdafjg
  frame:                  0x1365e6346c30
  URL:                    
  context_type:           BLESSED_EXTENSION
  effective extension id: obmdnneehibdanjlgbfflnbacibdafjg
  effective context type: BLESSED_EXTENSION
[16471:1547:0922/083204:VERBOSE1:script_context.cc(111)] Created context:
  extension id:           (none)
  frame:                  0x0
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[16471:1547:0922/083204:VERBOSE1:dispatcher.cc(442)] Num tracked contexts: 4
[16471:1547:0922/083227:VERBOSE1:dispatcher.cc(590)] Num tracked contexts: 3
[16471:1547:0922/083227:VERBOSE1:script_context.cc(120)] Destroyed context for extension
  extension id: obmdnneehibdanjlgbfflnbacibdafjg
  effective extension id: obmdnneehibdanjlgbfflnbacibdafjg
[16471:1547:0922/083227:VERBOSE1:script_context.cc(120)] Destroyed context for extension
  extension id: 
  effective extension id: 
```

**Comment by jonwwilkes** [comment]
@rogerwang any updates on this bug in light of @oaleynik 's chromium log?

**Comment by Christywl** [comment]
Could you please upload a sample to reproduce this?

**Comment by jonwwilkes** [comment]
@Christywl Given the plethora of information on this year-old bug, please tell me your reason for requesting that:

1. You or Roger need a demo because you have time and want to work on this bug (say, within the next few weeks).
2. You are doing regular issue tracker maintenance by bulk-labeling bugs to give them a richer set of metadata.

If you or Roger promise it is the first answer I'll promise to spend the hour necessary to go back and research this year-old bug that I've already worked around and no longer have personal interest in.

If it's the second answer then I'm sorry but I don't have sufficient time to add slightly more data to this year-old report.
