### ISSUE TITLE
Disabling SDK context menu options.

### ISSUE THREAD

**Issue by orther** [nwjs/nw.js#5081]
I am developing an app for OSX and Windows and we recently moved from nwjs v0.12.3 to v0.15.4 SDK build flavor and node v6.2.2. In our app we open the DevTools programmatically or more often use remote debugging. Currently when using the SDK build flavor the following 4 context menu items are added:
 - Reload App
 - Simulate Browser Restart
 - Inspect
 - Inspect Background Page

I would like the ability to NOT add these context menu items when using the SDK build. Originally I figured I would solve this by manually setting the handler of the `contextmenu` event during window creation (example code below). The problem with this is that there are default context menu items I want to show up (e.g. selected text should have context menu to copy text).

It would be much more straight forward to have a manifest option or method to disable these context menu items. If there are already facilities to manipulate the default context menus programmatically so I could remove only the 4 listed above in my JS code I would settle on that as a good solution and appreciate information on doing so.

--

Example code used to disable context menus on window creation:
```js
    // disable context menu
    newWindow.window.document.body.addEventListener('contextmenu', (e) => { 
      e.preventDefault();
      return false;
    });
```

**Comment by ghostoy** [comment]
I think you can use `inject_js_start` to inject your script to every frame. Please let me know if it doesn't work for you.

**Comment by orther** [comment]
@ghostoy thanks for your feedback but I am looking for a way to programmatically remove those 4 context menu items while keeping the other default context menus. It isn't obvious how `inject_js_start` moves me closer to that goal (I am already successfully running my code on newly created windows). Can you provide example code if `inject_js_start` does make this possible?

**Comment by ghostoy** [comment]
@orther Sorry, I misunderstand your request. I'll look into a fix to let you programmatically remove the 4 devtools items from default context menu.

**Comment by orther** [comment]
Curious if there is anything I can do to help this cause. Let me know if there is, thanks!

**Comment by RohitSharma27** [comment]
Till we get a manifest option you can use the below solution.
It works without writing the return false statement as well. So now you can start listening for context menu event and add your custom menu using the "Menu" api.

**Comment by orther** [comment]
Thanks for the input @RohitSharma27 but I am not understanding how that gets me to what I want which is: keep the default context menu items (e.g. copy/cut for selected text; copy/cut/paste for text inputs) and remove ONLY the sdk related context menu items (e.g. Reload App, Inspect Element, etc.). Unless I can access the default context menu for the `contextmenu` event within the event handler so I can alter it programmatically (i.e. remove the 4 sdk related context menu items) I don't see how to do it. If I am mistaken and you can provide more specifics to accomplish what I want, please do!

**Comment by RohitSharma27** [comment]
In order to remove default context menu items and add your own custom menu items, you can do this.

> var menuInstance = new nw.Menu({
> 					type: 'menubar'
> 				}),
> 
> 				cutItem = new nw.MenuItem({
> 					label: "Cut",
> 					click: function() {
> 						document.execCommand("cut");
> 					}
> });
> /* you can write other options accordingly */
> $(document).on("contextmenu", function(e) {
> 					e.preventDefault();
> 
> 					if (window.getComputedStyle(e.target, null).webkitUserSelect !== "none")   {
> 						menuInstance.append(cutItem);
> 					}
> 
> 					if (menuInstance.items.length > 0) {
> 						menuInstance.popup(e.originalEvent.x, e.originalEvent.y);
> 					}
> });

See if it helps.

**Comment by orther** [comment]
Yeah that's a partial solution I considered but it felt like it required me to manually override the default context menus all together and manually build custom menu items I want left. It is the solution I was hoping not to have to do and why I reach out for help here. Correct me if I'm wrong. It this still requires I manually recreate any of the default context menu items I do want to keep (there are tons and it would be a pain to have to go back and recreate everything. Not to mention dealing with changes in nwjs's default context menus moving forward). All I really need is to get access to the menu created by the default event emmitter so I can alter it or copy it so I can remove the sdk items and open whatever default menu items were left.

Appreciate the responses! Thx @rohitsha

**Comment by edysegura** [comment]
Hi @orther !

To disable these context menu I used the chromium-args below:

![image](https://cloud.githubusercontent.com/assets/5324414/17272673/f62cd218-5672-11e6-9f73-f7c70a107a24.png)

Hope it can help you!

**Comment by orther** [comment]
Thanks @edysegura that worked for me!
