### ISSUE TITLE
[0.15-*] webview.clearData make crash 

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#5087]
execute webview.clearData make nw crash

version: 0.15-*
os: both mac and win

test code:
```
{
  "main": "index.html",
  "name": "demo",
  "window": {
    "width": 900,
    "height": 900
  }
}
```

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body style="width:800px; height:800px">
  <div style="width:800px; height:800px">
    <webview src="http://xw.qq.com" id="webview" style="display:block;width:700px; height:700px"></webview>
  </div>
  <button id="clear">clear data</button>
  <script type="text/javascript">
  window.onload = () => {
    var webview = document.getElementById('webview')
    var clear = document.getElementById('clear')

    clear.addEventListener('click', () => {
      var data = {
        appcache: true,
        cache: true,
        fileSystems: true,
        indexedDB: true,
        localStorage: true,
        webSQL: true
      }
      webview.clearData({
        since: 0
      }, data, () => {
        console.info('WebviewBody.js _clearWebviewData success!')
      })
    })
  }
  </script>
</body>

</html>
```

**Comment by ghostoy** [comment]
Would attach the crash dump file and corresponding version, flavor, os and arch?

**Comment by rogerwang** [comment]
@ghostoy , OP's report is good enough with a case. I can reproduce it with the case. No further information is needed.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

Note that the next stable release will be 0.16.0 soon. There is no more 0.15.x releases.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/07-11-2016/nw16-e410c99-c556dbe-d88e3a2-77f39b5/v0.16.0/

**Comment by lin-chao** [comment]
hi @rogerwang 

i tested on my windows(win7 Windows 64-bit)

 click  "clear button" twice, nw crash again.

download  [minidump file](http://7oxjpb.com1.z0.glb.clouddn.com/webview-clearData-dmp.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/07-12-2016/nw16-e410c99-10b4d75-cd7731c-3151ede/v0.16.0/

btw, clearData() may not work for webview, see http://crbug.com/615429

**Comment by lin-chao** [comment]
i tested on mac and win, both work fine now. thanks ~

And  clearData() always worked in my project~
