### ISSUE TITLE
small typos in docs

### ISSUE THREAD

**Issue by Klestofer** [nwjs/nw.js#5091]
[To distribute your app through the package management sys**m**tem](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#platform-specific-steps)

**Comment by Klestofer** [comment]
also:
> your own icon and b**o**undle id

**Comment by Klestofer** [comment]
[Here](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#nodejs-changes) is something strange:

>which should be migrated to latest NaN 2

**Comment by ghostoy** [comment]
@Klestofer The first 2 are the typos. I will correct them.

NaN is referring to https://github.com/nodejs/nan.
