### ISSUE TITLE
How to set application window property?

### ISSUE THREAD

**Issue by aleki** [nwjs/nw.js#5092]
How I set _NET_WM_WINDOW_TYPE to DOCK?

Example in Gdk: https://people.gnome.org/~gcampagna/docs/Gdk-3.0/Gdk.WindowTypeHint.html

**Comment by ghostoy** [comment]
Does [x11](https://www.npmjs.com/package/x11) module on NPM work for you?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
