### ISSUE TITLE
Failure compiling '<script file>' (see above)

### ISSUE THREAD

**Issue by ohenepee** [nwjs/nw.js#5094]
- State which version are you using: NW.js SDK 0.13.4 Win ia32
- State which OS version are you running with: Windows XP SP3

Doing this `nwjc <script.js> <script.bin>` gives me `Failure compiling '<script.js>' (see above)`

Could I be doing something wrong?

**Comment by ohenepee** [comment]
FOUND the problem... ES6 kinda isn't supported by `nwjc` even though Chromium 49+ supports it pretty well. I was using block-scoped declarations like `let` and callback shorthand like `() => console.log(something)`

Don't know whether to file this under FEATURE REQUEST or BUG

**Comment by Christywl** [comment]
It works fine on Windows with nwjs-sdk-v0.24.4. Please try the latest nwjs build.
