### ISSUE TITLE
nw is creating a file with the first command line argument it's opened with

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#5097]
NW v0.14.6
OS : Windows 7

Hi guys,
I have observed that NW creates a file in the same directory as your "nw.exe" when it's opened with command line arguments. Steps to reproduce the issue are as follows : 
1. Open cmd and navigate to your directory containing nw.exe
2. Type `nw.exe first second`
Observation : 
nw creates a file with the name `first` in the same directory as your nw.exe
Try to run the same command in cmd again and now nw won't even open.
P.S. : If you delete this newly created file then nw when opened with the same command will get opened and will again create the same file.
Also, if you do `nw.exe -first -second` then it doesn't create the file and works fine every time.
This issue wasn't there in NW v0.12.3.

**Comment by rogerwang** [comment]
It works for me with the latest 0.14 build: http://dl.nwjs.io/live-build/06-25-2016/nw14-c61038e-64fe72c-2a9e6e1-66f8f40/v0.14.7/

**Comment by RohitSharma27** [comment]
@rogerwang The issue is still there. I have only tried 32-bit window SDK build.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by RohitSharma27** [comment]
If i can get a link to verify, then it would be great. Thanks for your efforts Roger. :)

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/07-15-2016/nw16-da06d55-d913fa5-242f304-773ddd8/v0.16.0-rc2/

**Comment by RohitSharma27** [comment]
It works like charm. Thanks @rogerwang. Will this be in 0,14.7 as well? I would love to have this in NWv14.
