### ISSUE TITLE
inject_js_start/end does not work for every page navigation.  

### ISSUE THREAD

**Issue by Nabeelhassan** [nwjs/nw.js#5098]
Hello sir,

I have some scripts that I want to run on every page navigation via inject_js_start and inject_js_end.
Unfortunately it seems to work only when i create the window via Window.open for the first time.
when navigation happens in the same window again the scripts do not work.
They code is working fine on v0.12.3 , when i ported it to v0.13.0 it didn't work , then I checked on v0.15.4 and came up with this bug.

please look into this , tell me how can i be of further use. 
Regards

**Comment by rogerwang** [comment]
Please provide a sample to reproduce.

**Comment by Nabeelhassan** [comment]
I apologize for the wrong report.. actually the loaded , loading events are not being trigger the 2nd time,the scripts are injected properly.

**Comment by rogerwang** [comment]
Please file another issue with examples if loading events don't work for you.
