### ISSUE TITLE
Javascript Alert crashes nwjs. Nwjs practically closes when an alert shows. This is happening in 0.16 - windows

### ISSUE THREAD

**Issue by onimisionipe** [nwjs/nw.js#5099]
Read the following before submitting your issue, thank you.

* Please use English so all users can read, or the issue will be closed directly.
* Use our mailing list to ask questions which don't imply bug or feature request: https://groups.google.com/forum/#!forum/nwjs-general
* State which version are you using
* State which OS version are you running with
* Provide a reproducible case if possible
* Attach the crash dump file if it's a crash: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

Issues meet the checklist above will be processed before those don't.

**Comment by rogerwang** [comment]
It works for me. Could you provide the exact commit hash? It's on the right bottom when NW starts.

**Comment by divinemanwah** [comment]
Also happens to me, maybe this is something like #4375
This occurs to me when:
- Triggering Alert multiple times
- Calling Alert with empty message

**Comment by rogerwang** [comment]
merge with #4375
