### ISSUE TITLE
[OS X] Tray click event ($50 bounty)

### ISSUE THREAD

**Issue by sindresorhus** [nwjs/nw.js#510]
[Tray docs](https://github.com/rogerwang/node-webkit/wiki/Tray) says:

> ### click
> 
> Emitted when user clicks the menu item with left mouse button. You can only catch this event on Windows and Linux, since there is no way to catch it on Mac. So you should never make user interactive rely on the click event.

I'm pretty sure it's possible. A lot of apps already do this: Evernote, Livereload, Caffeine, Breaktime, Codebox, etc.

It's useful for creating your own tray menus, like the Evernote one: 
![ 2013-03-05 20-04-11](https://f.cloud.github.com/assets/170270/223966/977819e6-85c7-11e2-89af-e9c07fdef015.png)

**Comment by shams-ahmed** [comment]
+1

**Comment by jrcahoon** [comment]
It may not be a perfect solution but I just used the tray click event to position a new window.

tray.on('click',function(e) {
        new_win = gui.Window.open('file:///',{
            x: e.x,
            y: e.y,
            width: 365,
            height: 500
        })
    })

**Comment by raguay** [comment]
This isn't working for me on the last two builds (currently 0.32.1) on the Mac OS 10.13.6. I really need this too!

**Comment by raguay** [comment]
Never mind. I needed to look on the background page, not the foreground page. My bad. Also, a mistake in the code.
