### ISSUE TITLE
How to change tray icon or making tray icon flashes?

### ISSUE THREAD

**Issue by hisune** [nwjs/nw.js#5102]
How to change tray icon or making tray icon flashes?

**Comment by ghostoy** [comment]
You can set `tray.icon` to a new icon file to change the tray icon. To make it flash, you can use following  to toggle icons between 1.png and 2.png every 300 ms for 10 times.

```javascript
var count = 10;
var timer = setInterval(function(){
  tray.icon = (tray.icon === '1.png' ? '2.png': '1.png');
  if (--count === 0) clearInterval(timer);
}, 300)
```

**Comment by hisune** [comment]
@ghostoy 
Thx, works perfectly!
