### ISSUE TITLE
NWJS doesn't work properly with GRPC for Node.js

### ISSUE THREAD

**Issue by pocographdotcom** [nwjs/nw.js#5103]
NWJS doesn't work with GRPC for Node.js,
Run it with Node.JS directly just act as normal.

* State which version are you using
    Version 0.15.4

* State which OS version are you running with
    OS X El Captian

* Provide a reproducible case if possible
    Install GRPC node.js module in the project folder.
    $ npm intall grpc
    and run the application that using GPRC via nwjs.

* Error message
```
    /Users/David/Downloads/app.nw/node_modules/grpc/src/node/src/client.js:334
    var call = new grpc.Call(channel, method, deadline, host,
             ^TypeError: Call's fifth argument must be another call, if provided
    at TypeError (native)
    at getCall (/Users/David/Downloads/app.nw/node_modules/grpc/src/node/src/client.js:334:14)
    at Client.makeUnaryRequest [as sayHello](/Users/David/Downloads/app.nw/node_modules/grpc/src/node/src/client.js:372:16)
    at chrome-extension://jdgkbifmkkkcgglljmlojibojoafmlhi/test.js:13:8
```

Here is the source code: [Archive.zip](https://github.com/nwjs/nw.js/files/361033/Archive.zip)

**Comment by rogerwang** [comment]
CC @ghostoy , this may be similar with the issue you just resolved.

**Comment by ghostoy** [comment]
GRPC is a native module written in C/C++. Did your rebuild it with `node-pre-gyp`? If not, please install latest `nw-gyp` with NPM and rebuild with following command:

```bash
cd node_modules/grpc
./node_modules/.bin/node-pre-gyp rebuild --runtime=node-webkit --target=0.15.4 --target_arch=x64
```

Or you can build `grpc` at the time of installing it with NPM by using following command:

```bash
npm install grpc --build-from-source --runtime=node-webkit --target=0.15.4 --target_arch=x64
```

**Comment by ghostoy** [comment]
@pocographdotcom Did you still experience the issue after the rebuild?

**Comment by pocographdotcom** [comment]
Yes it works after recompile with nw-headers.

**Comment by david9991** [comment]
@black Sorry I have no computer has Windows installed and no experiences with it. Just follow the ghostoy's instruction and tell what happened, maybe someone could help. ;) 

BTW, as mentioned that gRPC is a native module that needs to be recompiled on each platform and each version upgrade. So NWJS --> WebSocket to gRPC gateway (very easy to be implemented by Go) --> gRPC backend may be a better solution.
