### ISSUE TITLE
can not play mp3 ? version 0.15.4

### ISSUE THREAD

**Issue by caojianfei** [nwjs/nw.js#5107]
before 0.12 can use ffmpegsumo.dll to support mp3, but what should i do with version 0.15.4?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by RohitSharma27** [comment]
You are gonna have to rebuild ffmpeg to support mp3 mp4 and other formats. And there's some licensing issue as well. You may find it somewhere in the documentation.
