### ISSUE TITLE
update angle patches for nw17 branch

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#5108]

**Comment by ghostoy** [comment]
@rogerwang This patch should not be necessary since [cd9aa12afc83b9765ac78b6683f7f17fc03a8f42](https://chromium.googlesource.com/angle/angle/+/cd9aa12afc83b9765ac78b6683f7f17fc03a8f42). I will test if it solves our problem.

**Comment by ghostoy** [comment]
@rogerwang I don't see crashes or black screen issue on pressing Alt+Enter with 0.17 on Windows 8.1 / 10. This patch can be safely removed.

**Comment by rogerwang** [comment]
so launch a PR to remove it.
