### ISSUE TITLE
process.env.PATH is different by running nw app/  and running a built package

### ISSUE THREAD

**Issue by wowosky** [nwjs/nw.js#5110]
NW version: 0.12.2
OS version: OS X 10.11.5.

When I used "nw app/" to run an nw app,  process.env.PATH returned the right path of the current user.

When I used grunt to build a package, and run this app package directly,  process.env.USER returned the current user, but process.env.PATH returned "/usr/bin:/bin:/user/bin:/sbin", not the current user path.

Anyone hit the similar issue?  Any solution to make a built package running in the correct env?

**Comment by dkfiresky** [comment]
@wowosky probably you should use `process.env.HOME` as it will point to a user home directory.
Here is a [link](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_02.html#table_03_01) where most of environment variables described.

**Comment by wowosky** [comment]
@dkfiresky  Thanks for the response.  I'm not to get the current user home. My problem is why the PATH is different in the different running modes.

I think that I know why.

nw app/ was started from terminal,  its parent process was a terminal process,  the PATH of the terminal process was propagated to node process.

The parent process of  a app starting from a package was null. Its own was the first process. the PATH was a default path.
