### ISSUE TITLE
How to disable the right click menu, when the element's style is "-webkit-app-region: drag;"?

### ISSUE THREAD

**Issue by zhouce** [nwjs/nw.js#5112]
I have tride to use some ways, such as:
1. `<body oncontextmenu="return false;">`
2. document.body.addEventListener('contextmenu', function(ev) {
        ev.preventDefault();
        return false;
    });
but not work.
Any help will be appreciated.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by ruleechen** [comment]
I have the same issue. @zhouce 
Do you have any solution?

**Comment by L4P** [comment]
The question is posted in the mailing list and is unanswered. It still seems that you cannot disable that menu when right clicking on the toolbar/drag area.
