### ISSUE TITLE
Always On Top Bug?

### ISSUE THREAD

**Issue by divinemanwah** [nwjs/nw.js#5114]
I don't know if this is an intended behavior, but when I do Window 7's [_shake window to minimize all (Aero Shake)_](https://www.youtube.com/watch?v=9DgaGwle7mg) and repeat it again to maximize all, the current window that I am dragging is on top of my `always-on-top` window. Bringing focus to the `always-on-top` window fixes the problem.

**Update**:
Seems like the current window that I used for the Aero Shake became always on top too. Other windows cannot go over it. Bringing focus to it causes it to go above my NW app. Tried it multiple times with same result.
- nwjs-sdk-v0.15.4-win-x64
- Windows 7 64bit

**Comment by Christywl** [comment]
Seem it works fine for me on Windows with nwjs-sdk-v0.24.2. The nwjs app is always on the top.

**Comment by Christywl** [comment]
close until there is more information
