### ISSUE TITLE
How to remove  the right click for the frameless window?

### ISSUE THREAD

**Issue by my891008** [nwjs/nw.js#5116]
Is there any api to disable the right click ??
- [ ] 1. 
  ![default](https://cloud.githubusercontent.com/assets/19380655/16908711/527f4a9a-4d00-11e6-8f41-4668474f1777.png)

**Comment by zytse** [comment]
USING WINDOWS API
like this :
SetWindowLong(this.Handle, -16, 369164288);

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
