### ISSUE TITLE
intercept new window

### ISSUE THREAD

**Issue by c3g2e** [nwjs/nw.js#5117]
v0.15.4
how to intercept the creation of a new window? (action ctrl+leftbtnmouse, middle click mouse and other)

**Comment by bezformy** [comment]
I think you can't do this right now. Seems to be a bug. This is related to: https://github.com/nwjs/nw.js/issues/5046

**Comment by c3g2e** [comment]
I will wait when a bug fix.
Thank You.

**Comment by rogerwang** [comment]
Use this event: http://docs.nwjs.io/en/latest/References/Window/#event-new-win-policy-frame-url-policy

**Comment by bezformy** [comment]
@rogerwang The problem is that it does not work. At least the only time I can use that event is when the link has a `target="_blank"` attribute. If it is missing then a new window is created and the event is not fired.

**Comment by c3g2e** [comment]
@rogerwang, thank you man. you answer not decide problem.
later, i again create issues with this bug.

maybe you need help? i can you help work above API and design articture, but i not can in c++, because too during much to grasp.

of javascript context to nwjs engine execute (no matter how ctrl + mouseleftclick OR mousemidleclick ...) command create window. in c++ code you need create wrap function .....
is it really so difficult to?

**Comment by VoidVolker** [comment]
Yes, same problem: `new-win-policy` event broken again...
