### ISSUE TITLE
0.16.0-rc1 crashes on navigation / new win on trusted frame

### ISSUE THREAD

**Issue by wehowski** [nwjs/nw.js#5119]
On Navigation to a site the following code 
- **crashes** with version 0.16.0-rc1
- works as expected with version 0.15.4

````

nw.Window.get().on('new-win-policy', function(frame, url, policy) {
  try{
    var u = new frdl.Url(url);
    var h = u.getHost().split('.').reverse();
   
  if('de' === h[0]){
  	 if('webfan' === h[1])return true;
  	 if('domainundhomepagespeicher' === h[1])return true;
  	 if('frdl' === h[1])return true;
  }
     
  if('http' === u.getScheme() || 'https' === u.getScheme()) {
  	 policy.ignore();
  
    	(window.top || window).Tabs().addTab(u.getHost() , url, null, 'browser', true, undefined, true);
  	 return false;
    }	
  }catch(err){
  	console.error(err);
  /*	nw.Shell.openExternal(url); */
  }
  

   
   
  
});



nw.Window.get().on('navigation', function(frame, url, policy) {
 try{
  var u = new frdl.Url(url);
  var h = u.getHost().split('.').reverse();
  
  if('de' === h[0]){
  	 if('webfan' === h[1])return true;
  	 if('domainundhomepagespeicher' === h[1])return true;
  	 if('frdl' === h[1])return true;
  }
    
   if('http' === u.getScheme() || 'https' === u.getScheme()) {
  	 policy.ignore();
  
    	(window.top || window).Tabs().addTab(u.getHost() , url, null, 'browser', true, undefined, true);
  	 return false;
   }
  }catch(err){
  	console.error(err);
  	/*	nw.Shell.openExternal(url); */
  }   
   
  
}); 

````

Function addTab creates an iframe like

````

<webview resizable onload="browserOnLoad(this);" data-frdl-mod-browser="'+ID+'" src="'+url+'" frdl-id="'+ID+'"   style="border:none; width:100%; height:100%; display:block;top:0;bottom:0;margin: 0 auto;"></webview>

```` 

The navigated pages IP has node-remote privilege. 

OT: Some version updates ago navigation had a different behavior?

**Comment by rogerwang** [comment]
Could you please submit a full case?

**Comment by wehowski** [comment]
sorry, i'm not really sure what you mean.
The case is that the 0.16.0-rc1 chrashes in the same situation where the version before (0.15.4) works as expected, on windows. 
The situation where it chrashes I discribed above I guess has something to dow with the webview/iframe permissions.
I can give further information maybe if needed.
Sorry, if I did something wrong with my post!?

**Comment by rogerwang** [comment]
I mean could you please upload a runnable  demo so I can reproduce it? Thanks.

**Comment by wehowski** [comment]
Oh, please excuse me. Yes, in this posting https://github.com/jyapayne/Web2Executable/issues/152#issuecomment-233222927 you can find links to all my projects downloadable runable and source code.

**Comment by rogerwang** [comment]
http://cdn.webfan.de/cdn/application/webfan/widget.zip returns 404. Please send me  a URL to the source .

**Comment by wehowski** [comment]
its http://cdn.webfan.de/cdn/application/webfan/

**Comment by wehowski** [comment]
If it helps, here is a crash dump 
[0727/200804:ERROR:process_info.cc(608)] range at 0xef6c419000000000, size 0xa0 fully unreadable
[0727/200804:ERROR:process_info.cc(608)] range at 0xef6c41b000000000, size 0xa0 fully unreadable
[0727/200804:ERROR:process_info.cc(608)] range at 0x0, size 0xa0 fully unreadable
...
The problem still exists in version 0.16.0

I changed 
````
h += '<webview resizable onload="browserOnLoad(this);" data-frdl-mod-browser="'+ID+'" src="'+url+'" frdl-id="'+ID+'"   style="border:none; width:100%; height:100%; display:block;top:0;bottom:0;margin: 0 auto;"></webview>';
````

to 

````
          	h += '<iframe resizable onload="browserOnLoad(this);" data-frdl-mod-browser="'+ID+'" src="'+url+'" frdl-id="'+ID+'"   style="border:none; width:100%;height:100%; display:block;top:0;bottom:0;margin: 0 auto;" nwdisable nwfaketop></iframe>';
````

But it does not help, the app still crashes when navigating to ANY(?) url

**Comment by rogerwang** [comment]
http://cdn.webfan.de/cdn/application/webfan/ still returns 404

**Comment by wehowski** [comment]
Sorry, I disabled the dowload fwe time ago due to an update, now it is enabled again and you can download it!
Please note, the current version is alpha not stable and work in progress, I will find time for a next version maybe weekend. Yet I did not test this version about the issue here, I guess the problem could have to do something with permissions. The App uses webview (I changed to iframe with the nw attributes for test) and loads pages from node anabled IP. I noted that the app chrashes, if there are permission problems or if a page returns 404 (I still have to work on this). 
So currently  have to use nw.js 0.15.4 to get a stable.

**Comment by wehowski** [comment]
I have to report that my app does not crash anymore with nw.js version 0.16.1.
Thanks!
