### ISSUE TITLE
chrome.runtime.sendMessage isn't working

### ISSUE THREAD

**Issue by Pandzinho** [nwjs/nw.js#5124]
I am replacing my chrome app with nw.js app and it It seems that `chrome.runtime.sendMessage` isn't working at all. Example:

Sending msg from content script:

`chrome.runtime.sendMessage({port: devicePort})`

Msg isn't detected in script defined as main prop in package.json(ie there isn't any log):

```
chrome.runtime.onMessage.addListener(
    function(request, sender, sendResponse) {
        console.log(request);
    }
);
```

I'm using nw0.15.1sdk on Ubuntu 16.04.
Any ideas?

**Comment by gpetrov** [comment]
did you got it working?

**Comment by Pandzinho** [comment]
I really cant remember now, I abandoned the migration. Sry
