### ISSUE TITLE
Cannot register MediaPlayPause global hotkey

### ISSUE THREAD

**Issue by darkguy2008** [nwjs/nw.js#5131]
NW.js 0.15.4
Windows 8.1 x64

```
Error: Unable to register the hotkey
    at Function.Shortcut.registerGlobalHotKey (extensions::nw.Shortcut:204:29)
    at Object.bindingsAPI.compiledApi.registerGlobalHotKey (extensions::nw.App:114:45)
    at chrome-extension://fecikcldbcbcepbalhlchiehkcmheehc/main.js:12:9

```

I'm using this code:

```
var gui = require('nw.gui');

var sc = new gui.Shortcut({
  key : 'MediaPlayPause',
  active : function() {
    console.log("Global desktop keyboard shortcut: " + this.key + " active.");
  },
  failed : function(msg) {
    console.log(msg);
  }
});
gui.App.registerGlobalHotKey(sc);

```

I don't know what could be blocking those keys from being taken, but it's Windows so there is no random equalizer or volume app roaming around.

Any help is greatly appreciated!

**Comment by ghostoy** [comment]
@darkguy2008 This usually happens when there is another app registered the same hotkey.

**Comment by darkguy2008** [comment]
@ghostoy yeah but what app? as I said it's Windows, plain Windows, there's no other audio app installed, registered or running grabbing those keys. Do you know how can you see which app is doing it, if so?

**Comment by darkguy2008** [comment]
Alright, turns out Chrome is the culplit:

![image](https://cloud.githubusercontent.com/assets/6304136/17028376/a282582c-4f24-11e6-9036-e8d8fa979220.png)

However, a nice enhancement would be to tell which app is blocking the associated hotkeys, just like this app does (while crashing in the process)

**Comment by Christywl** [comment]
Seem it's not nwjs bug , can we close it?
