### ISSUE TITLE
MEAN application to NW app is not working as expected

### ISSUE THREAD

**Issue by kkorada** [nwjs/nw.js#5135]
I tried searching some tutorials and found something on github.

https://github.com/nwjs/nw.js/wiki/NW.js-use-express-and-similar-web-frameworks

I tried according to but I am getting error like

**This site can’t be reached

hmgnojaahbhcbbknpphpfodbkmmabfkk’s DNS address could not be found. Diagnosing the problem.**

and also app is opening in browser also, in browser everything seems to work good. But NW app window I am getting error.

**Comment by rogerwang** [comment]
The example is a special case to be used with a local http server.

Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
