### ISSUE TITLE
[nw17] update issue3835-inspect-crash case

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#5139]
The case failed but manual test is ok.

It should be the change of devtools.

see http://buildbot-master.node-webkit.org:8010/builders/nw17_sdk_linux32/builds/4/steps/test_release/logs/stdio

**Comment by ghostoy** [comment]
This is a bug of chromedriver. See
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1411#c4. I will
make a temp fix and see if upstream will fix it or not.

Roger Wang <notifications@github.com>于2016年7月22日周五 09:43写道：
