### ISSUE TITLE
slow startup on packaged windows app

### ISSUE THREAD

**Issue by zippo445** [nwjs/nw.js#514]
I packaged my node-webkit app for windows as described in https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps

the startup is very slow when double-clicking on the resulting app.exe ( ~ 15 secs).  On the same platform, when I start my app by dragging the uncompressed nw directory on nw.exe the startup time is quite good ( < than 2 sec).  dragging a compressed folder has a slow startup time as well, bringing me to believe the problem is around uncompressing of resources by node-webkit...  any way around the compression for a stand-alone app on windows?  if not, would it be possible to display some kind of feedback during startup (splash screen, progress)?

tested on win7 running in virtualbox

**Comment by VoidStatic** [comment]
Any update on this issue?

**Comment by Codelica** [comment]
If you're willing/able to use Enigma Virtual Box with your project to wrap it into a single .exe you can leave things unzip'd in their container and performance is quite good.  We've done this on a couple projects now with good results.  From my earlier post if you missed it:

"Just to follow-up, we seem to have found some success in leaving the application completely uncompressed (package.json, index.html, nw.exe, etc...) and wrapping it all up (again uncompressed) via Enigma Virtual Box. http://enigmaprotector.com/en/aboutvb.html

**Comment by mustapha-wang** [comment]
Yes，don`t packaged into *.zip,use Enigma box you application directory directly.
Launching nw_boxed.exe is more faster,about 5 seconds.

**Comment by christomitov** [comment]
@mustapha-wang I'm sorry I'm trying to use enigma virtual box without packaging anything (just raw directory structure with package.json) . When it's boxed with enigma virtual box I see it in task manager but nothing is running. When I click the nw.exe in the folder the app loads instantly as expected.. so I'm not missing any modules or anything in the virtual boxed exe, any ideas?

**Comment by Codelica** [comment]
@christomitov  Hard to say off hand.  We just use nw.exe as the "Input file" and drag all the assets for NW and our application to the "Files" section.   Here is a screenshot example (from an older version of NW, but we've used it with the latest also):

![enigmavirtualbox_screenshot](https://cloud.githubusercontent.com/assets/386101/6927654/05f87306-d7ac-11e4-9da1-16735f80c8f2.png)

**Comment by matthew-dean** [comment]
Not sure why this is closed. For me, my app starts in a few seconds for Mac, and takes 2-3 MINUTES to open on Windows. I have timing analytics which show that the difference in running the actual app between platforms is only a few seconds, so all the extra time is spent loading node-webkit itself (and I guess extracting the package?).

**Comment by baconface** [comment]
@matthew-dean How massive is your app because it sounds like you might have a bit in it? Mac has an obvious advantage. ["The bonus over other platforms is that app.nw does not need to be a zip file, if you want to speed up startup, you can make app.nw your app's directory."](https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#mac-os-x) Otherwise your application needs to unpack itself every run. You can reduce this load time by moving resources out of your .nw file and into the applications root directory where nw.exe is stored for an example.

**Comment by matthew-dean** [comment]
@baconface - It's not huge in size, but there a number of node modules included for distribution that have lots of files.

It would be great if the extraction was a one-time event, but I'll probably look for a way to not zip them because even an initial load of 3 minutes is a lot. Enigma Virtual Box looks promising, but looks like you can only build on Windows, not with Wine.

**Comment by baconface** [comment]
@matthew-dean That can cause it. More files is worse than big files. You can put your node_modules folder in the same directory as your nw.exe and it will function like normal.

**Comment by matthew-dean** [comment]
@baconface Oh interesting. I'm using nw-builder so it just zips them together. I'm thinking I can probably modify the gulp file to exclude node_modules from zip and then copy them to the build folder before packaging. Thanks for the tip!

**Comment by matthew-dean** [comment]
> You can put your node_modules folder in the same directory as your nw.exe and it will function like normal

.... Um, how do you get this to work exactly? You mean the node_modules folder in the same folder as my executable? That doesn't seem to work.

**Comment by ABeltramo** [comment]
Same problem here! In Windows it's super slow but on other platforms works really fast. 
Can't understand why this issue is closed.

**Comment by matthew-dean** [comment]
To follow up, I used the as-of-yet-unmerged pull request here: https://github.com/nwjs/nw-builder/pull/200

This made Windows startup decrease from 2 MINUTES to a few seconds.

**Comment by soichih** [comment]
+1 I am having the same slowness issue. I am using nw-builder to build the application package. I've tried setting "zip:false" with nw-builder but it didn't make any difference.

**Comment by donkonstante** [comment]
same issue here, it takes over 3 minutes to load in windows, as opposed to 5 seconds in my mac

**Comment by datnordstrom** [comment]
Same here, are there any solutions yet?

**Comment by RohitSharma27** [comment]
Your packaged app is too big and has got too many files, may be? If this is the case then you may try upgrading to nw >= 0.13. As you don't need to zip your files on windows anymore. But this would increase your app's size. Anyways this could be an option.

**Comment by matthew-dean** [comment]
@RohitSharma27 Wait, how do later versions of NW.js resolve this?

To my knowledge, `zip: false` should fix this now.

**Comment by RohitSharma27** [comment]
@matthew-dean I thought @datnordstrom is doing it manually and not with the "nw-builder". As far as I know, before nw 0.13, we had to zip our file and and name them "app.nw" for windows but now you can put them in a folder(zipping it is not required for windows anymore) named "package.nw" and put it in the same directory as "nw.exe". See this [http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/](url)

**Comment by matthew-dean** [comment]
@RohitSharma27 Oh. So why doesn't nw-builder do this?

**Comment by RohitSharma27** [comment]
May be because this was the only possibility back with nw <= 0.12 versions. I don't use the zip:false option. But as far as I understand it just put our files with nw binaries, as stated in the quick start way. I will try the zip:false option when I get the bandwidth. In case you try then please share your observation.
