### ISSUE TITLE
When loading the plugin, command line appear will disappear in a short time

### ISSUE THREAD

**Issue by my891008** [nwjs/nw.js#5140]
the package.json

 "chromium-args": "--ppapi-flash-path=pepflashplayer.dll",
  "window": {
    "min_width": 950,
    "min_height": 600,
    "width": 950,
    "height": 600,
    "resizable": true,
    "frame" :false,
    "transparent" : false,
	"toolbar": true,
  },
  "webkit":{
	  "plugin":true
}

whether  iframe \ webview \ window.open(url)

this situation will  happen

**Comment by ghostoy** [comment]
It should be windows only.

**Comment by hxfdarling** [comment]
I also encountered this problem

**Comment by ghostoy** [comment]
merged to #5278
