### ISSUE TITLE
Massive memory leak with YouTube Material Layout

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5141]
Tested in NWJS sdk15.4 and sdk16.0, using YouTube with the new Material Layout in either a webview or iframe (haven't tested in other ways) results in a constantly increasing memory usage the further a user navigates.

Sample test

package.nw
- package.json
- index.html
- index.js

Contents

package.json

``` json
{
    "author": "",
    "chromium-args": "--user-data-dir='temp/' --disk-cache-size=1 --incognito --enable-logging",
    "description": "test",
    "main": "index.html",
    "inject_js_start": "index.js",
    "name": "test",
    "version": "1.0.0",
    "node-remote": ["<all_urls>"]
}
```

index.html

``` html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body style="margin:0">
        <iframe id="youtube" name="youtube" src="https://www.youtube.com/?gl=US" style="width:100%;height:100%;border:0;position: absolute;" nwfaketop nwdisable allowfullscreen></iframe>
    </body>
</html>
```

index.js

``` js
if (window.chrome.cookies) {
    window.chrome.cookies.set({
        url: "https://www.youtube.com",
        domain: ".youtube.com",
        expirationDate: (new Date(Date.now() + 31536E6)).getTime(),
        httpOnly: true,
        name: "VISITOR_INFO1_LIVE",
        path: "/",
        sameSite: "no_restriction",
        secure: false,
        storeId: "0",
        value: "Qa1hUZu3gtk"
        }, function (cookie) {
            console.log(cookie);
    });
}
```

Steps to reproduce the problem: Navigate for a while, watch videos but never sign in since the new layout is not enabled for logged in sessions. Monitor the memory usage and it will start growing over time and never decrease. I have reached a session where the maximum memory usage was over 900MB.

The Material Layout makes heavy use of custom properties attached to DOM elements, this may be the cause behind this problem, either by failed garbage collection or improper handling of missing DOM objects and its properties (zombie compartments maybe?).

This problem does not appear to prevail when testing it on Chrome browser.

OS: Win7x64

**Comment by Yonezpt** [comment]
Issue submited by error, will fill in the missing information and delete this reply when completed.

**Comment by rogerwang** [comment]
Do you see the leak if you disable injecting index.js?

**Comment by Yonezpt** [comment]
Same problem persists, over 600MB of memory after 20minutes of navigation and video watching, never releases it. I removed the injection from the manifest like you asked.

**Comment by rogerwang** [comment]
I think the cookie callback creates a closure which holds a reference to the global window, so it doesn't get GCed after navigation.

Is there anyway we can try the Material Layout without this callback?

**Comment by Yonezpt** [comment]
Yes, there is. YouTube must set the cookie by itself, which does not happen that often, or sert the cookie manually via devtools.

**Comment by Yonezpt** [comment]
I have tested with the manifest's `main` pointed at `https://www.youtube.com/?gl=US`, cookie already set in cache from previous tests and the problem still remains without using the cookie setter. Only a simple window using the new Material Layout, memory leak still happens.

**Comment by rogerwang** [comment]
After I remove index.js from manifest it works for me. The memory consumption doesn't grow after navigation.

**Comment by Yonezpt** [comment]
I re-tested the same configuration you mentioned, this is the memory use after 10 minutes of navigation and video watching:

![ss](https://cloud.githubusercontent.com/assets/8498057/17160537/26f4c242-5395-11e6-84de-21269c104a92.png)


Are you sure you tested with the new Material Layout and not with the normal layout? Because there is no memory leak while using the normal layout, which is why I ask since you didn't experience memory consumption and I still do.

**Comment by rogerwang** [comment]
I think I was testing the Material Layout because I was using the same user data dir in tests and I was able to reproduce the leak as you do with index.js. Is there any way to make sure?

**Comment by Yonezpt** [comment]
Yes, if it has that icon with the little man running on the bottom-left corner of the page (you can see it in my previous screenshot) then you are using the Material Layout.

**Comment by rogerwang** [comment]
Could you please send the configuration you used and the user data dir for the cookies?

**Comment by renemarty** [comment]
Any news on this? It's a serious bug of nw... I'm analysing to migrate a huge app to electron only due to this memory issue. Any advice or comment will be appreciated.

**Comment by Yonezpt** [comment]
I have given up on trying to load Material in NWJS, no solutions I found prevented the memory leak and recent versions appear to still suffer from this problem.

**Comment by Christywl** [comment]
Seem I can reproduce this issue on Windows 8.1 with nwjs-sdk-v0.24.4. Play the video for 40 minutes:
![5141](https://user-images.githubusercontent.com/20039821/29758586-43a3f99a-8be7-11e7-8a7b-8914b22b732f.png)

**Comment by Yonezpt** [comment]
It appears that this problem has not been as severe since this issue was opened (using sdk 0.29.0-b1)
