### ISSUE TITLE
nw.js v0.16.0 crashes when loading greenworks native module

### ISSUE THREAD

**Issue by hokein** [nwjs/nw.js#5142]
nw.js v0.16.0 crashes when loading a native module (https://github.com/greenheartgames/greenworks).

Reproduce steps:
```
cd <greenworks_src_dir>
nw-gyp rebuild --target=0.16.0
<path/to/nwjs> samples/nw.js
```

Crash stack trace:
```
#
# Fatal error in ../../v8/src/api.cc, line 1027
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

 1: v8::Unlocker::~Unlocker()
 2: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 3: (anonymous namespace)::init(v8::Local<v8::Object>)
 4: node_module_register
 5: v8::FixSourceNWBin(v8::Isolate*, v8::Local<v8::UnboundScript>)
 6: v8::FixSourceNWBin(v8::Isolate*, v8::Local<v8::UnboundScript>)
 7: v8::FixSourceNWBin(v8::Isolate*, v8::Local<v8::UnboundScript>)
 8: 0x356d86208ba7
 9: 0x356d8639da79
10: 0x356d863959b2
```

* OS: Mac OSX 10.11.6
* nw-gyp: 3.4.0

[3e05b1c9-9e5b-494c-ac4e-2312caee5093.dmp.zip](https://github.com/nwjs/nw.js/files/379410/3e05b1c9-9e5b-494c-ac4e-2312caee5093.dmp.zip)

**Comment by ghostoy** [comment]
@hokein I don't have Steamworks SDK to build your module. So I tested sqlite3 with 0.16.0, and it worked as expected. Could you check if the module is compatible with latest V8? And if possible, could you upload dependencies for the module so that we can test?

**Comment by rogerwang** [comment]
This could be an issue specific to or in the 'greenworks' native module. And the crash dump file submitted by @hokein is not from official NW binary so we can do nothing with it :(

**Comment by hokein** [comment]
@ghostoy , @rogerwang Thanks for your investigation! I will take a look on it.

**Comment by hokein** [comment]
The crashes is caused by a deprecated v8 API, which is not related to nw.js. Closing now.

**Comment by liboyue23** [comment]
how to resolve？
