### ISSUE TITLE
chrome-extension:// protocol does not work for img.src and a.href

### ISSUE THREAD

**Issue by chenlucan** [nwjs/nw.js#5143]
Running nwjs-sdk-v0.14.3-osx-x64 on mac 10.11.5

As I understand, from version 0.13, file:// protocol is supposed to be replaced by chrome-extension.

- Replacing file:// from my html tag img.src and a.href with chrome-extension does not work. Did I miss anything?

- Opening too many images with file:// results in error due to occupying to many file handles. Does chrome-extension:// solve this issue?

**Comment by RohitSharma27** [comment]
You don't need to write chrome-extension manually when you're accessing files that are going to be there in your "package.nw". Just provide the relative path there and nw will access that file using the chrome-extension protocol. If the file that you're trying to access lies outside the package.nw then file protocol is used to access that file.

**Comment by chenlucan** [comment]
i'm using absolute path accessing files outside package.nw.
So file protocol still applies here? What's the recommended way solving problem caused by opening to many images ?

**Comment by rogerwang** [comment]
chrome-extension protocol is limited to files inside the app. For other local folders, file protocol is supported. If you find any issue loading resources with file protocol, please file another issue.
