### ISSUE TITLE
nwjs execute native module, which is a C++ addon that execute ioctl() with NVMe device, Permission denied

### ISSUE THREAD

**Issue by Gengju-Li** [nwjs/nw.js#5146]
nwjs v0.15.4 execute native module, which is a c++ addon that execute ioctl() with NVMe device, then the ioctrl() return fail (-1), and the error information returned from linux is "Permission denied". (in the situation of root)
However, the exactly same one native module of c++ node addon, when load and execute in node.js 6.2.0, the ioctl() return success and the function run perfectly.
In a word, node.js run it well but node-webkit run it bad, therefore, it's a issue. 

Besides, nwjs load a native c++ addon module, which execute ioctl() with a SATA device not a NVMe device, ioctrl() run well and return success(0).

NVMe device : /dev/nvme0
SATA device : /dev/sda1

Version : nwjs v0.15.4,  node.js 6.2.0.
OS : Ubuntu 15.04

**Comment by rogerwang** [comment]
Could you please provide more information? e.g. how did you launch the application as root.

**Comment by Gengju-Li** [comment]
I log-in Ubuntu system with root user, not use "sudo" command. 
Besides, the same one node addon, we load and execute it in node.js, function run perfectly.
Our project must use ioctl() with NVMe disk device, so we change to use the Electron, which is similar with nw.js. When load the same one node addon, the Electron load and execute it also run perfectly.

**Comment by Gengju-Li** [comment]
Do you have a NVMe disk ? After all, SATA disk is most universal and NVMe device is not widespread. 
(However, NVMe is next generation disk protocol. ^_^)

**Comment by rogerwang** [comment]
I don't have any NVMe disk so I cannot reproduce this. If you are still interested in debugging this issue with us, you can run the NW processes with strace and send the log to us.

**Comment by rogerwang** [comment]
close until more information is provided.
