### ISSUE TITLE
NWJS crashes if <iframe> has JavaScript error

### ISSUE THREAD

**Issue by Klestofer** [nwjs/nw.js#5148]
Application folder has 3 files:
- `package.json` has `{ "name": "name", "main": "main.html"}`
- `main.html` has `<iframe src="frame.html" nwdisable></iframe>`
- `frame.html` has `<script>error</script>`

Application starts and instantly crashes on Windows 10.

`iframe`'s `src` can point to some site that has errors in console, result is the same. `nwdisable` is not necessary in this case, for example: `<iframe src="https://www.microsoft.com/en-us/windows/windows-10-upgrade"></iframe>`

NW.js is v0.16.0

**Comment by Glogau** [comment]
I find a similar error. I use a jQuery-based Framework. i used an invalid Selector (wrong id) and nw.js crashed.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
