### ISSUE TITLE
I Can't use WebRTC Because of the version of chrome

### ISSUE THREAD

**Issue by zhumi123** [nwjs/nw.js#5149]
My project use WebRTC.But since chrome 47, it can't be used 'getusermedia()' if you don't use https://

some reason , I can't change to HTTPS .
So i want to ask for help.1、How can I change the version of chrome in nw.js 0.15 or higher?
                                       2、It's some args allow me to use WEBRTC in http:// ?
                                      3、other

Thank a lot

**Comment by rogerwang** [comment]
will look to support this. Is there any http site we can use to test?

**Comment by zhumi123** [comment]
oh there is an args work for me.
add it in package.json

"chromium-args" : "--unsafely-treat-insecure-origin-as-secure=http://127.0.0.1",
