### ISSUE TITLE
menubar click is not firing

### ISSUE THREAD

**Issue by AndrePessoa** [nwjs/nw.js#5150]
I´m trying insert a menubar at a dynamic created window, but the click is not firing... 

Win 7, NW v nwjs-sdk-v0.16.0-win-x64

```
gui.Window.open( path, {	icon: "imgs/logo_icon.png", width: 1024, height: 768 }, function(new_win){
	// Create an empty menu
	var menu = new gui.Menu({ type: 'menubar' });
	var mobile_deitado = new gui.MenuItem({
		label: 'Mobile deitado',
		click: function() { 
			console.log('clicked');
			new_win.resizeTo( 640, 480);
		}
	});
	menu.append(mobile_deitado);

	new_win.menu = menu;
});
```

**Comment by ghostoy** [comment]
@AndrePessoa The top level items are buttons on the menubar. When you click it, submenu will be shown. Currently we don't support click event on the menubar buttons.

**Comment by AndrePessoa** [comment]
@ghostoy, tnks! But it is no more supported or not yet? This worked before but I´m not sure about the version.

**Comment by ghostoy** [comment]
@AndrePessoa Oh, I didn't know that. Then we'll support this feature soon.
