### ISSUE TITLE
Autofill turned on by default and can't be turned off, 0.16.0

### ISSUE THREAD

**Issue by EddieK31** [nwjs/nw.js#5151]
Issue is in version 0.16.0
Running on a Windows 10 machine

In version 0.15.4 no auto filling was being done on forms by default, in the current version 0.16.0 user names and password fields are being automatically filled in.  

Attempted to use the chromium argument --disable-single-click-autofill but this seems to have no effect.

**Comment by fanchou** [comment]
autocomplete="off"

**Comment by EddieK31** [comment]
thank you very much for this answer, is this in the package.json file?  What section?

**Comment by fanchou** [comment]
just for form element

**Comment by rogerwang** [comment]
@EddieK31 the switch is not for disabling the autofill suggestions completely as you expected. It is for autofill with a single click.

To disable the suggestion list, please try @fanchou 's method.

**Comment by oaleynik** [comment]
@rogerwang `autocomplete="off"` doesn't help. In my case the input field has type password and is outside of the `form` tag.

**Comment by oaleynik** [comment]
Simplest page for testing:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <h1>Hello there!</h1>
  <form action="http://localhost:3000/login" method="POST" autocomplete="off">
    <input type="password" name="password" autocomplete="off"/>
    <input type="submit" />
  </form>
</body>
</html>
```

![Result](https://www.dropbox.com/s/27b0lcn58bsunjo/Screenshot%202016-08-01%2012.16.01.png?dl=1)
