### ISSUE TITLE
CLI Arguments in 0.16.0

### ISSUE THREAD

**Issue by CyberianIce** [nwjs/nw.js#5155]
I'm having trouble using command line arguments with nwjs 0.16.0

It used to work just fine before but after upgrade to 0.16.0 I have failed to make use of `--url` switch, it seems to be completely ignored, although documented [here](http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#command-line-options) and used as described in documentation.

For instance:
`nw.exe --url="https://www.github.com/"`
Above command will always result in opening default page defined in package.json, instead of GitHub homepage

**Comment by rogerwang** [comment]
The 'url' switch is supposed to be used without package.json or any app.

**Comment by CyberianIce** [comment]
I see. I am confused because up to 0.12.3 `--url` switch used to work just like a charm together with package.json. 

Is there a workaround to use CLI switch `--url` with:
- custom trust anchors?
- custom window properties?
- custom chromium arguments?
- custom js flags?
- custom user agent?
- and other package.json flags...

How would one use app url (`main` or whatever) with access to WIN64 system variables such as `%USERNAME%`, `%APPDATA%`, and so on, together with above parameters? For instance: `"main": "https://www.github.com/%USERNAME%"`?

Until now, it was easily avoided by using package.json (pointing main anywhere) and creating shortcut with custom `--url` argument. If none of above is possible anymore, I would consider that as a major deficiency.
