### ISSUE TITLE
HTML5的Notification.requestPermission总是得到granted

### ISSUE THREAD

**Issue by dalidong2009** [nwjs/nw.js#5160]
Notification.requestPermission(function (s) {
        console.log(s)
    });
会得到一个promise，向用户询问是否允许，得到denied或者granted。
但是我在nw0.15.4下不向用户询问，总是得到granted。

**Comment by ghostoy** [comment]
@dalidong2009 Please use English to raise issues so that anyone can understand your problem.

For your issue, since NW.js app should behave like a native app, it's always granted for showing notifications. See #3341 for details.
