### ISSUE TITLE
Errors from handlers attached to Nodejs's EventEmitter events aren't showing up in devTool for nw@0.15.4-sdk

### ISSUE THREAD

**Issue by lcb931023** [nwjs/nw.js#5162]
Running nw@0.15.4-sdk on Windows 10. 

Steps to reproduce:
In `index.html` include `main.js` via script tag; 
In `main.js` create Nodejs's EventEmitter instance and make it global;
In a js module, attach a function that would throw an error to a custom event that EventEmitter listens to
In another js module, use EventEmitter to dispatch that event.
Error does not show up in devtool.

Anybody ran into issue like this as well?

**Comment by RohitSharma27** [comment]
Have you tried looking for it in the background page's console i.e. right click -> Inspect background page? It works for me in both 14 and 16 versions.

**Comment by lcb931023** [comment]
@RohitSharma27 That did the trick! Thanks.
