### ISSUE TITLE
new_instance does not create new renderer process

### ISSUE THREAD

**Issue by tolrtd** [nwjs/nw.js#5163]
I've had a problem since sometime in 0.13 with new_instance on nw.Window.open not actually spawning a new renderer process.  This did appear to work at some point between 0.12 and 0.13 but I forget which build.  I am on Windows 8.1 (x64) using nwjs 0.16.0 SDK.

Here is my demo:

package.json
```javascript
{
  "name": "NW Test",
  "main": "./demo.js",
  "description": "test",
  "version": "1.0.0",
  "node-remote": "<all_urls>"
}
```

demo.js
```javascript
(function(){
	nw.Window.open('./demo.htm', {
			'id': 'window1'
		}, function(win){
			nw.Window.open('./demo.htm', {
					'id': 'window2',
					'new_instance': true
				}, function(win2){}
			);
			nw.Window.open('./demo.htm', {
					'id': 'window3',
					'new_instance': true
				}, function(win2){}
			);
	});
})();
```

demo.htm
```html
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
Testing
</body>
</html>
```

And here is what I see in my task manager.
![demo](https://cloud.githubusercontent.com/assets/10121985/17200008/da85e134-543e-11e6-9570-1661b0d17b68.png)

Now perhaps I am reading something wrong or missing something.  But any insight would be very helpful!

**Comment by rogerwang** [comment]
fixed in http://dl.nwjs.io/live-build/08-24-2016/nw17-ff103c3-2487fce-de19b1f-6c79a25/v0.17.0-rc1/

**Comment by xuanhun** [comment]
When to release nw17?

**Comment by rogerwang** [comment]
@xuanhun it will be released in 1-2 days after Chromium 53 stable is released. Hopefully before Sep.
