### ISSUE TITLE
v0.16.0 and later live versions make error on XP x64, XP ia32

### ISSUE THREAD

**Issue by chunsun21** [nwjs/nw.js#5166]
It returns error about 'The procedure entry point ReleaseSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll' on XP x64.

And, also it returns error about 'The procedure entry point GetThreadId could not be located in the dynamic link library KERNEL32.dll' on XP ia32.

**Comment by ghostoy** [comment]
Google ended the support for XP in Chrome M50. NW.js LTS is based on the last compatible version of Chrome. So please use the LTS version (0.14.x) for XP support.
