### ISSUE TITLE
nw package shows default screen when packaged, working without packaged.

### ISSUE THREAD

**Issue by shaaw** [nwjs/nw.js#5170]
Im making an app with node-webkit and everything is fine until i try to package my app to distribute.
I have followed the wiki step by step, cant manage to make it work.
Im using windows 10 x64 and node-webkit 0.16 sdk x64.

I have used the nwbuilder package to build it or doing manually and both cases shows the default nw screen.
The only time i have gotten an error was when executing
`./nw.exe package.nw`

i get "Coudnt load the extension from "Path to package.nw". Missing manifest file or coudn't be read.

But i have my package.json on the root of the package.nw.

Its the same problem as described here
http://stackoverflow.com/questions/33955898/package-node-webkit-app-for-windows-showing-blank-screen-when-run

This is the repository where my code is if you need to try it. https://github.com/shaaw/shaawchat dev branch

I can still package it distributing the full folder of the app and executing ./nw.exe as it reads the package.json on the current folder, but i would still want to build a proper package.

**Comment by ghostoy** [comment]
@shaaw For NW.js 0.13.0 or later, please read the guide on official document site (http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/).

I tried your case, and it works with 0.16.0. If you put plain files in `package.nw` folder, no special work is needed. If you zip your app into package.nw, make sure `package.json` is in the root of zip. And you don't need to pass `package.nw` as CLI argument.

**Comment by shaaw** [comment]
Thanks, i got it working now. I believe the problem i had was with the limit of 260 filename chars on windows. I now can package it to package.nw folder or zip and it works like a charm. Thanks a lot.

**Comment by ghostoy** [comment]
Great :)

Jonathan Onrubia Mogica <notifications@github.com>于2016年8月1日周一 18:05写道：
