### ISSUE TITLE
The LTS version isn't published in NPM

### ISSUE THREAD

**Issue by edysegura** [nwjs/nw.js#5171]
It is not possible to install the LTS vesion 0.14.7 through npm.

```npm install nw@0.14.7-sdk```

![image](https://cloud.githubusercontent.com/assets/5324414/17281105/b773607a-576f-11e6-96bb-f6defd006584.png)

**Comment by ghostoy** [comment]
@Mithgol FYI

**Comment by rogerwang** [comment]
Please file the issue to the proper project. The 'nw' module is not maintained by us.

**Comment by Mithgol** [comment]
Fixed in nwjs/npm-installer@06b0b494abec829d79bf9a7910d963fcf13790ab.
