### ISSUE TITLE
Cannot handle error/exception

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5174]
Hi it's may be problem with my knowledge level, i tried to handle all errors with below code but it's not working can anyone help me?
`
window.onerror = function(e) {  
    alert("Error found in code!");
};
`

`process.on('uncaughtException', function(e) {
    alert("Exception found in code");
});
`

**Comment by rogerwang** [comment]
Please submit a full case.

**Comment by freddy-tech** [comment]
I fixed that that's error fired from iframe but i'm still doubted why nw.js can't handle any error's
globally.Now i need to prevent app being crashed see my new issue https://github.com/nwjs/nw.js/issues/5180

**Comment by ghostoy** [comment]
@freddy-daniel I can't reproduce this crash on Windows / Mac of both SDK and normal build. Please provide a full test case to reproduce.

**Comment by rogerwang** [comment]
close as duplicate of #5148
