### ISSUE TITLE
0.16.0 on WinXP: GetThreadId could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by alborq** [nwjs/nw.js#5175]
Hello ! 

I have a same problem :  https://github.com/nwjs/nw.js/issues/4655
@jalbam look like has same too... 

Is this WinXP support officially dropped, or just an accident due to lack of testing?

Thanks

**Comment by ghostoy** [comment]
@alborq Chrome has ended support for WinXP this year. Please use NW.js LTS version (0.14.x) which is using the last Chrome version M50 supporting WinXP. See http://nwjs.io/blog/v0.14.7/ for release notes for 0.14.7.

**Comment by alborq** [comment]
Thanks for fast reply.



On Tue, Aug 2, 2016 at 3:29 AM +0200, "Cong Liu" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #5175<https://github.com/nwjs/nw.js/issues/5175>.

-
