### ISSUE TITLE
Printing mediaSize not being used on Windows

### ISSUE THREAD

**Issue by juanchel** [nwjs/nw.js#5176]
I'm trying to print, and using a mediaSize that should correspond to envelope sized paper:
```
mediaSize: {
  width_microns: 241300,
  height_microns: 104648
}
```

However, when it prints, either through a printer or to pdf, the paper is still sized as if it were printed as letter. I have tried passing a variety of different parameters into the print function but was unable to get this working.

I am on NW.js v0.16.0-rc2 and Windows 10.

I have tried this on OSX as well, and it works fine there, it is only on Windows where I have this issue.

**Comment by rogerwang** [comment]
It works for me with the following example in 0.16.0 and win10:

https://gist.github.com/rogerwang/4d6f3af648e7d54a4407fca06edea237
