### ISSUE TITLE
HTML5 Filesystem API doesn't work

### ISSUE THREAD

**Issue by tarruda** [nwjs/nw.js#5177]
package.json:

``` json
{
  "name": "html5-fs-fail",
  "main": "http://html5-demos.appspot.com/static/filesystem/filer.js/demos/index.html",
  "chromium-args": "--enable-logging=stderr"
}
```

Opening the page will show 0 bytes of free space and something like this on console: "WARNING:chrome_quota_permission_context.cc(287)] Attempt to request quota from a background page". Chrome  shows about 10mb when the user gives permission.

Something else to consider: Chrome asks the user if the app should allow filesystem API access, but for nw.js there should probably be an user-provided callback to decide based on URL.

**Comment by timfish** [comment]
I thought nwjs allows any requested quota but you have to actually request a quota. I've got HTML5 filesystem working well on `0.16.1` using `cordova-promise-fs` which simply uses code like this:
```
navigator.webkitPersistentStorage.requestQuota(storageSize, function(grantedBytes) {
   window.requestFileSystem(type, grantedBytes, resolve, reject);
}, ...
```

**Comment by Christywl** [comment]
Reproduced on Linux/Windows with nwjs-sdk-0.21.2.

**Comment by rogerwang** [comment]
@Christywl how did you reproduce it? it should be working ...

**Comment by Christywl** [comment]
I just used the `package.json` in the bug. 
Log in console:
`[10416:10416:0315/062554.429536:WARNING:chrome_quota_permission_context.cc(287)] Attempt to request quota from a background page: 3,7`

![5177](https://cloud.githubusercontent.com/assets/20039821/23931049/f0b3f3ec-096a-11e7-8f8e-d2e4f4a8979e.png)

**Comment by rogerwang** [comment]
In browser the user will have to approve the usage. In NW the application needs to apply for quota first as @timfish said. 

We could add a callback as reporter proposed, or just let it pass first to make it easier for newcomers.

**Comment by rogerwang** [comment]
changed the default setting to allow quota in git. Will be available in the next nightly build.
