### ISSUE TITLE
Access Chrome packaged App Apis

### ISSUE THREAD

**Issue by euforic** [nwjs/nw.js#518]
[Packaged App APIs](http://developer.chrome.com/apps/api_index.html)

I know some of these apis may be irrelevant but, would it be possible to make some of the chrome packaged apps/extension apis available in node-webkit. For example chrome's tts and ttsEngine
##

**Comment by rogerwang** [comment]
'webview' tag and chrome.webrequest API and background script is available in nw12 testing version now. We do plan to support more chrome.* APIs. Please leave your wishes as comments.

**Comment by whatsdis** [comment]
please add support for 

the message listener, communicating to background.js from content script.

chrome.storage
chrome.cookies

**Comment by chrisglasier** [comment]
Plus 

Chrome Speak

please!

**Comment by rduckett** [comment]
Would be looking to unit test Streamus chrome extension using NW.JS

**Comment by shaynem** [comment]
chrome.proxy please :)

**Comment by RIAEvangelist** [comment]
Chrome Bluetooth
https://developer.chrome.com/apps/bluetooth

Chrome Serial
https://developer.chrome.com/apps/serial

**Comment by shaynem** [comment]
Chrome.proxy please.

**Comment by jkramp** [comment]
We would love the option to do remote desktop sharing. This can be done with a chrome extension and webrtc. Not sure off hand if this could be done without an extension and just using chrome api (chrome.desktopCapture) but if so....awesome

Other than that chrome.proxy

**Comment by J4G-** [comment]
I would love chrome.tabCapture in addition to (or instead of) chrome.desktopCapture.

**Comment by Destreyf** [comment]
@rogerwang 

The 4 that i would like to see are

chrome.idle
chrome.bluetooth
chrome.desktopCapture

I'm working on a XMPP/SIP client, and could really use chrome.idle as well as chrome.bluetooth.

We are also working on a video conferencing client which would benefit greatly from the desktop capture API.

**Comment by AndryBray** [comment]
Chrome Bluetooth
https://developer.chrome.com/apps/bluetooth

Chrome Serial
https://developer.chrome.com/apps/serial

+1 please

**Comment by whatsdis** [comment]
any updates?

I want to port my chrome extension to nw.js

**Comment by RIAEvangelist** [comment]
:+1:

**Comment by rogerwang** [comment]
while I'm working on nw13 the current API implementations will be refactored to use the underlying chrome extension mechanism. So many chrome.* API could be supported, see https://groups.google.com/d/msg/nwjs-general/A7VpwOztU_s/Tg1L6nS2RBsJ

**Comment by whatsdis** [comment]
so when will nw13 come out?

**Comment by rogerwang** [comment]
@whatsdis the first alpha version is expected to be be available in early May.

**Comment by bhaveshgohel** [comment]
+1

**Comment by Aph0** [comment]
chrome.runtime: https://developer.chrome.com/extensions/runtime
(mainly getting *var port = chrome.runtime.connect(chrome.runtime.id);* to work)
and
chrome.desktopCapture: https://developer.chrome.com/extensions/desktopCapture

**Comment by eriegz** [comment]
Could you please add support for Chrome USB API? https://developer.chrome.com/apps/usb

**Comment by rogerwang** [comment]
Close as chrome.* APIs are supported now. If you find any API is not working, please file a new issue. Thanks.
