### ISSUE TITLE
How to prevent App being crashed

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5180]
Hi,
I need to prevent app being crashed when uncaught error occurred.Currently i can handle errors from nw.js by
 
       process.on('uncaughtException', function(e){
                  alert('Error found');
       });

But app being closed after alert.How to prevent this default behavior `return false;` is not working.

**Comment by Kilgaloon** [comment]
What version you are using. I'm loging uncaughtException also, and my app is never crashing when uncaughtException occurs.

**Comment by RohitSharma27** [comment]
What do you see in the debug file that gets generated?

**Comment by freddy-daniel** [comment]
I'm using latest version( v0.16.0) SDK version will never crashed it will handle these exceptions but Normal version being crashed.

**Comment by ghostoy** [comment]
@freddy-daniel I can't reproduce this crash on Windows / Mac of both SDK and normal build. Please provide a full test case to reproduce.

**Comment by freddy-daniel** [comment]
This is my index.html
`
<!DOCTYPE html>
<html style="width: 100%;height:100%">
    <head>
        <title >Test Application</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="css/window.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <div id="app">
            <iframe id="mainFrame" src="https://em.techgentsia.com/"></iframe>
        </div>           
    </body>
</html>
`

And this is css/window.css

`
/* NW Window styles */
html,body{
    overflow: hidden;
    width: 100%;
    height:100%;
    margin: 0 !important; 
    padding: 0 !important;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
}
iframe{
    border:none !important;
    border-width: 0 !important; 
    width: 100%;
    /*height:calc(100% - 30px); */
    height: 100vh;
    margin: 0 !important; 
    padding: 0 !important;
}
.window-titlebar{
    height: 30px;
    border-bottom: 1px solid #e8e8e8;
}
.window-titlebar .title{
    float: left;
    width: 90%;
    width: calc(100% - 135px);
    text-align: left;
    line-height: 28px;
    padding-left: 35px;
    font-weight: 100;
    color: #a2a2a2;
    -webkit-app-region: drag;
}
.window-titlebar .title .icon{
    position: absolute;
    left: 10px;
    line-height: 36px;
    font-size: 18px;
    color: #2e6583;
}
.window-titlebar .tools{
    float: right;
    text-align: right;
}
.window-titlebar .tools a{
    display: inline-block;
    width: 30px;
    height: 30px;
    text-align: center;
    line-height: 32px;
    text-decoration: none;
    color: #ddd;
}

/* NW Window styles */
`
Run app with these codes and Click forgot password> Reset password it will throw uncaught error and app being crashed

**Comment by freddy-daniel** [comment]
Hi i found this old NWjs normal version [v15.2](http://nwjs.io/blog/v0.15.2/)  working without crashed.but latest NWjs normal version is still crashed why.

**Comment by freddy-daniel** [comment]
This issue is related to https://github.com/nwjs/nw.js/issues/4912. 
It is fixed for version 0.15.2 but appears in 0.16.0

**Comment by rogerwang** [comment]
This should be a duplicate of #5148 and was fixed in git.

**Comment by freddy-daniel** [comment]
Thanks for your support this issue solved with current build [Nightly build 08-04-2016](http://dl.nwjs.io/live-build/08-04-2016/nw16-a3bea28-a464d98-91db929-80ede20/v0.16.1/)
