### ISSUE TITLE
App reload (sdk build ctx menu)

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5183]
I see on the sdk build there is a contexual menu (right click) with "Reload app" item/option.
@rogerwang could you expose this API to fire it with javascript?

Something like `nw.App.reload()` 

PS: I see other older issues like this, I reopen because of new nwjs 0.14/0.16

**Comment by rogerwang** [comment]
Is it chrome.runtime.reload()? https://developer.chrome.com/extensions/runtime

**Comment by AndryBray** [comment]
Oh! Yes! It works as expected. Thank you
