### ISSUE TITLE
Icon for Mac package

### ISSUE THREAD

**Issue by RichardFoss** [nwjs/nw.js#5185]
I have been following the instructions to package and distribute my app on:
>> https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps

I have created the fully prepared .nw file  
>> Run zip -r ../${PWD##*/}.nw *

I renamed my .nw file to be app.nw. I created an nw.icns file from a series of tiff icon images (1024x1024, 512x512, etc). Followed - https://www.youtube.com/watch?v=3TPtHX9O3IU
I went to the package contents of nwjs.app, and placed app.nw and nw.icns in Contents/Resources.

nwjs, when opened now runs my application (an immersive sound server), which is wonderful, but my icon is not associated with the nwjs app package. I believe it should be. Any help would be much appreciated!

**Comment by evshiron** [comment]
Use `app.icns` instead or edit `Info.plist`.

**Comment by RichardFoss** [comment]
Thanks for the suggestion evshiron. I did try using app.icns and also put the following into Info.plist:
	<key>CFBundleIconFile</key>
	<string>ServerIcon.icns</string>
but still no joy unfortunately.

**Comment by RichardFoss** [comment]
Looks like my problem was that I was using the SDK version of nwjs. When I downloaded and used the 'Normal' version your suggestion worked. Thanks!!

**Comment by rogerwang** [comment]
SDK version shouldn't have the difference with normal version on this.

**Comment by RichardFoss** [comment]
Thanks a lot for confirming this Roger! The SDK version is now showing the icon - I think it might have been a caching issue.
