### ISSUE TITLE
nw.App.argv issue 

### ISSUE THREAD

**Issue by littledream2015** [nwjs/nw.js#5187]
in 0.12 and before, nw app can use nwgui.App.argv to receive arguments.
in 0.13 and later, nw.App.argv is always an empty array.
I also wonder if nw.App.onopen event is working.

this issue is from google group:[https://groups.google.com/forum/#!topic/nwjs-general/9trxxPNMezY](url)

**Comment by ghostoy** [comment]
@littledream2015 `nw.App.argv` works for me. Could you provide a sample app to reproduce?

**Comment by littledream2015** [comment]
@ghostoy is your nw the latest version? I downloaded the latest version and it failed to work.
and I tell Roger, he let me file a issue

**Comment by rogerwang** [comment]
@littledream2015 that doesn't mean I acknowledge the issue is valid. Our test cases  cover this: https://github.com/nwjs/nw.js/tree/nw16/test/sanity/app-argv and the nightly tests show that it's passing on the latest version. So please provide a sample if it doesn't work for you.

**Comment by ghostoy** [comment]
@littledream2015 I'm using 0.16.0 SDK. Please attach your case and post the NW.js version and OS you are working on.

**Comment by littledream2015** [comment]
nw version:0.16.0 sdk
OS:win7
--------------------------------------------
package.json code:
`{
    "name": "test",
    "main": "index.html"
}`

index.html code:( I only added a script in the body)
`console.log( nw.App.argv);`

@ghostoy @rogerwang 
my code is so simple,

**Comment by RohitSharma27** [comment]
@littledream2015 launch your nw.exe from command line with any argument and you will see them logged in console this time. I think you mistook it for something else.

**Comment by rogerwang** [comment]
close as invalid.

**Comment by littledream2015** [comment]
@RohitSharma27  
just like what you suggests,in the command line , it really works
but when I tried to use nw application to open a file using open-with method or directly drag a file to nw.exe. nw application couldn't open. it blocks. maybe it's another issue.

@rogerwang

**Comment by ghostoy** [comment]
@littledream2015 Dragging a file or a folder to `nw.exe` is same as executing `nw.exe file-or-folder-path`. `nw.App.argv` is supposed to contain arguments after `file-or-folder-path`.

**Comment by littledream2015** [comment]
@ghostoy actually it's not. In the early version,such as 0.12. both actions are the same。
Let me try it in my colleagues' pc.

**Comment by ghostoy** [comment]
@littledream2015 Do you mean if you drap a folder to nw.exe and `App.argv` will contains the path to the folder? I tested on 0.12.3 and it didn't work as you said.

**Comment by littledream2015** [comment]
@ghostoy I am sure, all the platforms support it. there are two ways to use the arguments.
1. drag a file to nw.exe, App.argv can get the file path
2. select a file, and open with the nw.exe application. App.argv also can get the file path.

by the way, I check it , the version is 0.12.3

I think I should record a video, later I will upload the address.
