### ISSUE TITLE
How to Disable Developer tools

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5188]
Hi again,
I'm facing another trouble now.I want disable developer options in NW.js SDK version (Want remove dev options in right click,Triggering Developer tools while pressing F12 key).I found `--disable-devtools` in nw.js commandline options but i don't know how to use it.I've tried to `"chromium-args" : "--disable-devtools"` in package json but i  can't find this option in [chromium-command-line-switches](http://peter.sh/experiments/chromium-command-line-switches/).Now i just want disable developer options in NW.js SDK version (I'm using latest version v0.16.0 of NW.js)
I also referred these sites but i can't find anything useful 
[Command line options](http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-disable-devtools)
[Manifest format- chromium-args](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#chromium-args)
[chromium-command-line-switches](http://peter.sh/experiments/chromium-command-line-switches/)

**Comment by ghostoy** [comment]
@freddy-daniel Do you still need DevTools? If not, you can choose the normal version.

**Comment by freddy-daniel** [comment]
Normal version is crashed on uncaught exception.See my issues https://github.com/nwjs/nw.js/issues/5174 , https://github.com/nwjs/nw.js/issues/5180

**Comment by freddy-daniel** [comment]
Thanks for your help. Switching to normal version helps.

**Comment by rogerwang** [comment]
In future please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
