### ISSUE TITLE
nw.exe - entry point not found

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#5189]
nwjs v0.16.0 win x64
vista sp2
I used example template in the documentation (just a json file and index.html).

Error:
nw.exe - entry point not found
The procedure entry point TryAcquireSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll

log:
[0803/165022:ERROR:main_dll_loader_win.cc(136)] Failed to load NW DLL from C:\nwjs-v0.16.0-win-x64\nw.dll: The specified procedure could not be found. (0x7F)

**Comment by rogerwang** [comment]
vista is supported in the LTS branch: https://groups.google.com/d/msg/nwjs-general/KMT8supwj2o/MOueFNU_AwAJ
