### ISSUE TITLE
"chromium-args": "--single-process" not working

### ISSUE THREAD

**Issue by qdwang** [nwjs/nw.js#5195]
- nwjs version v0.15.2
- windows 8.1

**Comment by ghostoy** [comment]
@qdwang I tested with 0.16.0 on Windows 8.1 and it works. Note that there will be two processes if you run with `--single-process`. One is nw itself, and another one is crash handler for catching crash reports.

Without `--single-process`, you will get at least 3 processes: one for crash handler, one for browser and one for renderer. And you may also get a forth GPU process without this argument.

**Comment by mangaga** [comment]
@ghostoy is this argument supported on NW14 ?, When I tested it on NW0.14.6, it couldn't load to the main frame.

**Comment by ghostoy** [comment]
@qdwang @mangaga My mistake. I tested `--single-process` in CLI, not with `chromium-args`.

**Comment by rogerwang** [comment]
This was fixed in the latest release.
