### ISSUE TITLE
Menu issue in version 0.16.1

### ISSUE THREAD

**Issue by kappe** [nwjs/nw.js#5200]
I'm using version 0.15.3 with the following code snippet. **Every thing works fine!**.
After upgrading to version 0.16.1 without changing my code, the program crashes at startup or the very first item is not displayed

_let _subM  = new nw.MenuItem( {"type" : "checkbox", "label" : "MITTE", "click" : () => { _chgeGrp( "MITTE" ) } } );
_let _subO  = new nw.MenuItem( {"type" : "checkbox", "label" : "OST",   "click" : () => { _chgeGrp( "OST" ) } } );
_let _subW  = new nw.MenuItem( {"type" : "checkbox", "label" : "WEST",  "click" : () => { _chgeGrp( "WEST" ) } } );
_let _subB  = new nw.MenuItem( {"type" : "checkbox", "label" : "BAO",   "click" : () => { _chgeGrp( "BAO" ) } } );

_let _tray  =   new nw.Tray( { "title" : "TetraConsole", "tooltip" : "TETRA-Console", "icon" : "wt.png" } );
_et _menu  = new nw.Menu();
    
//-- ...................................................................+
    _menu.append( _subM );
    _menu.append( _subO );
    _menu.append( _subW );
    _menu.append( new nw.MenuItem( {"type" : "separator"} ) );
    _menu.append( new nw.MenuItem( { "label" : "Einstellungen", "click" : _issi2Opta } ) );
    _menu.append( new nw.MenuItem( {"type" : "separator"} ) );
    _menu.append( new nw.MenuItem( { "label" : "beenden", "click" : function() { 
        let __winPos = {x: win.x, y: win.y};
        localStorage.setItem( "WinPos", JSON.stringify( __winPos ) );
        nw.App.quit() 
    } } ) );
    _tray.menu = _menu;

**Comment by kappe** [comment]
sorry I forgot to tell You the platform: Windows 8.1 x64

**Comment by ghostoy** [comment]
@kappe Merged to #5202.
