### ISSUE TITLE
NW Making call to clients.l.google.com upon launch

### ISSUE THREAD

**Issue by shaynem** [nwjs/nw.js#5206]
Reproduce: use any app with a package.json file (it does not work running standard nw.exe without any package.json)  - I used the camera sample app from 

https://github.com/zcbenz/nw-sample-apps

when you first run nw.exe / or mac and linux equiv it sends a HTTP request to clients.l.google.com

To me, this is a security risk and is an un-required HTTP call

"Why is this needed" and how can it be blocked from doing so ?

**Comment by ghostoy** [comment]
@shaynem I can't reproduce it with latest 0.16.1. When Could you please post your NW.js version?

**Comment by shaynem** [comment]
I was using 0.16.0 - I'll download the latest and take a look and update my findings

**Comment by Christywl** [comment]
@shaynem , any update for this issue in your environment? `file-explorer` app works well for me(https://github.com/zcbenz/nw-sample-apps/tree/master/file-explorer) on Linux and nwjs-sdk-0.21.0.

**Comment by rogerwang** [comment]
close until more information is available.
