### ISSUE TITLE
Language files missing from production version of NWJS

### ISSUE THREAD

**Issue by silentsakky** [nwjs/nw.js#5209]
SDK Build is having language files for all languages in nwjs.app/Contents/Resources, but same is missing from Production Build

I have checked this issue for Mac Build only but issue is present for all OS Builds

check below screenshot: 

![NWJS Language Bug](http://i68.tinypic.com/99jsxy.png "NWJS Language Bug")

**Comment by ghostoy** [comment]
merged to #4824
