### ISSUE TITLE
v0.16.1 could't init tray menu

### ISSUE THREAD

**Issue by Hsinky** [nwjs/nw.js#5210]
I import v0.16.1,the  code of index.html  is : 
var tray = new nw.Tray({ title: 'Tray', icon: 'img/icon.png' });
var menu = new nw.Menu();
menu.append(new nw.MenuItem({ type: 'checkbox', label: 'box1' }));
tray.menu = menu;
but the v0.15.4 is normal.

**Comment by ghostoy** [comment]
merged to #5202.
