### ISSUE TITLE
Getting Started Guide is broken

### ISSUE THREAD

**Issue by cookiengineer** [nwjs/nw.js#5211]
Hey guys,

the Getting Started Guide and the package.json manifest format is still broken.

If you follow the steps of the latest tutorial, you will get some errors: http://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/#write-nwjs-app

Questions:

- How to start an nwjs App now, if not with the index.html as an entry point?
- The nw binary assumes an index.js file as an entry point, otherwise the token "<!doctype ..." will result in an error when loading an index.html as in older versions.
- Is there a _complete_ package.json example available with ALL possible settings?

When loading a folder directly via "nw /path/to/directory" you will get an `[18624:18624:0812/162308:ERROR:component_loader.cc(168)] Failed to parse extension manifest.` error without any clue on what's going on or what the error actually is.

**Version** 0.16.1
**OS** Ubuntu GNU/Linux
**Arch** amd64
**Self-compiled?** No, used binaries from website directly.

**Comment by ghostoy** [comment]
Could you post your package.json in /path/to/directory?

**Comment by ghostoy** [comment]
The helloword sample app works flawlessly on Linux. Please check if you have a valid `package.json` inside `/path/to/directory`. See http://docs.nwjs.io/en/latest/References/Manifest%20Format/ for detailed specification.

**Comment by vonEdfa** [comment]
Slight necro, but I have this on MacOS. (NW.js version 0.38.4)

package.json:
```
{
  "name": "Test",
  "main": "index.html"
}
```
index.html
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
```
(Copy pasted from the getting started guide)

Starting with `nw .` seems to work fine, but outputs the error in the terminal:
```
[43051:775:0605/112150.361560:ERROR:component_loader.cc(167)] Failed to parse extension manifest.
```

Want me to create a new issue or should we keep it here?

**Comment by rogerwang** [comment]
@vonEdfa please create a new one as it looks different. Thanks.

**Comment by vonEdfa** [comment]
Will do!

**Comment by boguz** [comment]
i think it would also be useful to explain how to install nw.
It says on top of the Getting Started page where you can download it, but it never tells you what to do with it afterward. (or did i miss that?)
Maybe even an example on how to install it using npm...?
