### ISSUE TITLE
open another html  but request like js or img doesn't work

### ISSUE THREAD

**Issue by sanrudongfeng** [nwjs/nw.js#5216]
I try to do a thing :
         1. use module 'request' of node to fetch some pages  from some websites ;
         2.  use nw.js to render a '.html' file so that '.js' can be exectued and I can get the page that js 
     has rendered.
    I did like this:
# **enviroment-----**

os:  windows 10   version 1607
nw.js: version  v0.16.1
# **project**

index.html
target.html
package.json

my index.html is just like this:

```
<html>
<head>
  <title>Hello World!</title>
  <meta charset='utf8'>
</head>

<body>
  <h1>Hello World!</h1>
  <p id='36kr'>链接主页</p>
  <script src='./jquery.js'></script>
  <script> 
    var request = require('request');
    var fs = require('fs');
  </script>
  <script>
          $(function(){
             $('body').on('click', '#36kr', function(){
               console.log('jinlai');
                request('http://36kr.com/p/5051172.html',function(err,response,body){
                  console.log(err,body);

                           fs.writeFile('./target.html',body,function(err){
                             if(err)return console.log(err);
                             window.location.href = './target.html';
                   })
                });    
             });
          }); 
    </script>
</body>
</html>
```

   click `<p id='36kr'>链接主页</p>` ,as could be expected,the chrome will load target.html.but just like this :'<script src='//a.com/b'></script>' just become
  '<script src='chrome-extension://a.com/b'></script>' , not 
  '<script src='http://a.com/b'></script>'.is there any way to solve this problem?
@ghostoy

**Comment by ghostoy** [comment]
Updated question with valid Markdown syntax. @sanrudongfeng

**Comment by ghostoy** [comment]
@sanderboom I don't quite understand "the window open another list.html.but the requests 'list.html' dosen't matter". Please show what is expected and what is the actual result.

**Comment by sanderboom** [comment]
@ghostoy you mean @sanrudongfeng I guess? :wink:

**Comment by Christywl** [comment]
@sanrudongfeng , is this issue still reproduced on your environment with the latest nwjs version? If yes, could you please provide the screenshot or logs of your failure? I just try to reproduce with your code(after npm install `request` and `jquery` modules), the window switches to another page, but there are many errors in the console. Meanwhile, I'm also not quite clear your result description.

**Comment by rogerwang** [comment]
close until more information is available.
