### ISSUE TITLE
desktop notification close and click functions not working in vm 

### ISSUE THREAD

**Issue by anjanapaulose** [nwjs/nw.js#5217]
Hi,
I am trying to create desktop notifications.  But if the system is a VM,  the close and click methods are not getting triggered. If i call notification.close() programmatically, it works. But user clicks are not working. The close button is not getting highlighted. Also the click method is applicable only to the icon area , not any the body area.

I tried with nw.js 14.5 and latest stable 16.1, using example at https://github.com/nwjs/nw.js/tree/master/tests/manual_tests/notification  

Please help.

**Comment by Christywl** [comment]
@anjanapaulose , I can't run the test in the link. Error `gui.App.createShortcut is not a function` throws. Is this issue still reproduce in your side? If yes, could you please provide other sample to reproduce this issue?

**Comment by anjanapaulose** [comment]
latest nw does not have nw.gui. You need to use nw istead. Please use the modified file, rename it to .html

[desktop-notfication.txt](https://github.com/nwjs/nw.js/files/895172/desktop-notfication.txt)

**Comment by Christywl** [comment]
hi, @anjanapaulose , the modified file also doesn't work for me, the error occurs(`Uncaught TypeError: nw.App.createShortcut is not a function`). Seem nw.App doesn't have createShortcut method. Btw, I also change other code(`gui.MenuItem` to `nw.MenuItem`). Does this modified file work for you? I use nwjs-sdk-v0.21.4 on Windows.

**Comment by anjanapaulose** [comment]
Please use these files
[package.json.txt](https://github.com/nwjs/nw.js/files/895645/package.json.txt)
[index.html.txt](https://github.com/nwjs/nw.js/files/895646/index.html.txt)

Please remove .txt from files

Sometimes you can also see that the notifications appear as half, half part is not displayed at all. This issue we have seen in actual systems also.

**Comment by Christywl** [comment]
I tried these two files on my Windows 10 with nwjs-sdk-v0.21.4. Seem notification show/click/close work fine for me. And the notification displays normally. Please see the screenshot:
![image](https://cloud.githubusercontent.com/assets/20039821/24733882/f51f94f6-1aac-11e7-9421-9c0b1fcfcb2f.png)

**Comment by anjanapaulose** [comment]
I was using nw 14.5 , and close never used to work in a VM. In latest version it is working fine.  But I have noticed that randomnly , the notification appears half - not fully displayed. I couldn't get a screenshot. This is observed in latest versions as well.

**Comment by anjanapaulose** [comment]
Hi,

Attached a pic with notofication half cut.
![nw_notification_cut](https://cloud.githubusercontent.com/assets/15088695/26543872/39e14176-447d-11e7-9066-3a341b855956.png)

**Comment by anjanapaulose** [comment]
Also , we see the same issue with close icon now also. The difference we have is , the icons we use are dynamic, they are different for different messages, so we pass byte64 array instead of a file. Is this why we are getting the issue?

**Comment by anjanapaulose** [comment]
Hi, any updates on this?

**Comment by taher** [comment]
we are also facing issue of half cut notifications on nwjs v0.19.5 on windows 10 machine on attached monitor (21 inch)

**Comment by Christywl** [comment]
I still can't reproduce this issue in VM(Windows 10). nwjs-sdk-v0.26.0.
![5217-vm](https://user-images.githubusercontent.com/20039821/31752700-e5ec062a-b4be-11e7-8681-46807a3d9771.png)
