### ISSUE TITLE
Checkign object on Console in SDK crashes app

### ISSUE THREAD

**Issue by MichalMisiaszek** [nwjs/nw.js#5218]
I am using 0.16.0 on OSX 10.10. When inspect app and trying to open object in console tab I am getting: 

nwb nwbuild -v 0.16.0-sdk -r .
{ platform: 'darwin',
  arch: 'x64',
  version: 'v0.16.0',
  flavor: 'sdk' }
workingDir: /var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi
FATAL ERROR: v8::Object::GetAlignedPointerFromInternalField() Not a Smi

 1:
node::UVException(v8::Isolate_, int, char const_, char const_, char const_, char const_) [/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/libnode.dylib]
 2:
node_module_register [/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/libnode.dylib]
 3:
v8::Object::SlowGetAlignedPointerFromInternalField(int) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 4:
v8::Unlocker::~Unlocker() [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 5: ChromeMain [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 6:
v8::FixSourceNWBin(v8::Isolate_, v8::Localv8::UnboundScript) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 7:
v8::FixSourceNWBin(v8::Isolate_, v8::Localv8::UnboundScript) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 8: v8::FixSourceNWBin(v8::Isolate_, v8::Localv8::UnboundScript) [/private/var/folders/6q/dv0_ykj128j6_86nvcl5r0_m0000gn/T/d-116716-50248-b4pyeq.u74bh2gldi/nwjs.app/Contents/Versions/52.0.2743.82/nwjs Framework.framework/nwjs Framework]
 9: 0x25872f408ba7

10: 0x25872fb0c427

**Comment by ghostoy** [comment]
@MichalMisiaszek I see `FixSourceNWBin`. Is the object inspected generated from pre-compiled source code?

**Comment by MichalMisiaszek** [comment]
Not really, this is pure JS with JQuery. Now I added some more changes and it is crashing when opening console :(

FATAL ERROR: v8::Object::GetAlignedPointerFromInternalField() Not a Smi
Received signal 6
 [0x0001029c8e3a]
 [0x7fff956c5f1a]
 [0x7fff5d750ea8]
 [0x7fff90eed9ab]
 [0x00010d8eefca]
 [0x000103d83406]
 [0x0001050606b5]
 [0x000103c1bbad]
 [0x000103d9b818]
 [0x000103dc8680]
 [0x000103dd9c07]
 [0x3ede2290961b]
 [0x3ede2349ba3e]
 [0x3ede2349ad4a]
 [0x3ede2290d157]
[end of stack trace]

**Comment by rogerwang** [comment]
How can we reproduce this? Are you using any native modules?

**Comment by MichalMisiaszek** [comment]
Yes, I am using couple of native modules:

<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  <script src="https://www.mapquestapi.com/sdk/leaflet/v2.2/mq-map.js?key=YeGYuNylqPhzgbGx3eSGDlmZyoij9bRz"></script>
  <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  
  <script type="text/javascript" src="./js/metisMenu.min.js"></script>
  <script type="text/javascript" src="./js/sb-admin-2.js"></script>

  <script type="text/javascript" src="./js/d3.min.js"></script>
  <script type="text/javascript" src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script type="text/javascript" src="./js/micropolar-v0.2.2.js"></script>
  <script type="text/javascript" src="./js/jquery.csv.js"></script>
  <script type="text/javascript" src="./js/jquery.knob.js"></script>
  <script type="text/javascript" src="./js/leaflet.iconlabel.js"></script>
  <script type="text/javascript" src="./js/date.format.js"></script>

**Comment by ghostoy** [comment]
@MichalMisiaszek These scripts are not native modules. Native modules are C/C++ addons loaded with Node.js, e.g. [node-sqlite3](https://github.com/mapbox/node-sqlite3).

**Comment by MichalMisiaszek** [comment]
How about proto-buffers?

**Comment by rogerwang** [comment]
Did you rebuild them against NW? The native modules built for Node are not compatible with NW after 0.14.

**Comment by rogerwang** [comment]
btw, please submit a reproducible case or the crash dump.

**Comment by MichalMisiaszek** [comment]
It is hard to build app as it works in connection with server. I am using 0.16.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample or upload the crash dump files?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @MichalMisiaszek)
