### ISSUE TITLE
Remote loading JS Bin Eval with evalNWBin()

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#5220]
Feature: Allow evalNWBin to load files remotely or through a variable.

This would be an excellent feature and addition to evalNWBin . 

A simplistic example.

```
var async_bin = $.ajax("/bins/file,bin")
evalNWBin(async_bin , frame)
```

https://github.com/nwjs/nw.js/issues/5168
@ghostoy

**Comment by mscreenie** [comment]
Excellent! I will test when once ready and inside builds.

**Comment by VasiliyIsaichkin** [comment]
#5233 still not merged :( :( :( 
Why? Really need it!
