### ISSUE TITLE
Stuck on "Adobe Flash needs your permission to run" 

### ISSUE THREAD

**Issue by raexman** [nwjs/nw.js#5224]
App won't run Flash. Stuck on "Adobe Flash needs your permission to run" and when selecting "Run this plugin", nothing happens. No errors in console. Attaching project files.

I'm using:
Windows 10 (x64)
NW.js SDK v0.16.1
Pepper Flash Player 22.0.0.209

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/601249/17792307/de781dc6-6554-11e6-8589-dc834b441e2e.png)

**File structure:**
![image](https://cloud.githubusercontent.com/assets/601249/17792328/fde3ac2a-6554-11e6-83b8-65c2f6fd1c8c.png)

**Project files:**
[PepperFlashTest.zip](https://github.com/nwjs/nw.js/files/425976/PepperFlashTest.zip)

**Comment by raexman** [comment]
Ok, so I decided to rollback the Pepper Flash Plugin to version 22.0.0.209 as mentioned in #4979 and it appears to work with no issue.

**Comment by rogerwang** [comment]
Should be fixed now. merge with #5278
