### ISSUE TITLE
PDF prints different from NW.js and Adobe

### ISSUE THREAD

**Issue by EddieK31** [nwjs/nw.js#5227]
Using 0.15.4 (but have also tested in 0.16.1, issue still exist)
Windows 10 (64bit)

The attached pdf will print differently from NW.js and Adobe.  When printed from Adobe the lines in the middle of the page are printed correctly.  When printed from NW.js, the lines are printed very small in the upper left of the page, maybe 1in by 1/2in.  I have also tried to print from Chrome (52.0.2743.116 m), lines to not print where they are supposed to but do not appear in the upper left of the page.

I am thinking this might be a Chromium bug, but since the printing is different from Chrome and NW.js I figured it couldn't hurt to submit here.

[RonBurgundy07-27-2016.pdf](https://github.com/nwjs/nw.js/files/427299/RonBurgundy07-27-2016.pdf)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
