### ISSUE TITLE
All Enterprise systems are down, all in panic

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5228]
This is the package.json used. I have a Chromium.exe running in --kiosk mode, on top of that Chromium.exe i need to have nw.exe but following is not working anymore. 

nw.exe is running but its always behind the Chromium.exe

How can i bring the nw.exe on top of Chromium.exe (chromium is in kiosk mode)?
(All the enterprise used the nw.exe just because it worked in past, but now not anymore working, all the systems/kiosks are down, officially enterprises want to block or remove nodewebkit from there policy permanently, if i cant fix it within nodewebkit)

Can anyone please fix this?

{
  "name": "", 
  "main": "http://www.example.com/",
  "window" : {
    "title": "",
    "toolbar" : false, 
    "frame" : true,
    "resizable": false, 
    "kiosk": false,
    "always-on-top": true,
    "width":1280,
    "height":768,
    "show": true
  }
}

**Comment by RohitSharma27** [comment]
This is how always _on_top should be wriiten i.e. with an underscore

**Comment by shamun** [comment]
Thank you @RohitSharma27 , i will test with all the versions and give you feedback.

**Comment by kailniris** [comment]
how came its just not working all the sudden?

**Comment by ghostoy** [comment]
- Before 0.13.0, it was `always-on-top`.
- After 0.13.0, it was changed to `always_on_top`.

**Comment by Christywl** [comment]
I can't reproduce this issue with `always_on_top`. @shamun , is `always_on_top` ok for you?

**Comment by shamun** [comment]
Problem was not noticed anymore in recent version. (closing the issue, hoping it was fixed).
