### ISSUE TITLE
0.17.0-beta2 is crashing on OS X

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#5229]
[Crash report](https://gist.github.com/oaleynik/1a486b0cc399d6051e220e37ec0fb30b)

**Comment by oaleynik** [comment]
#5193 may be related

**Comment by Blatman** [comment]
Yup - I get the same error myself when I use 0.17.0b2 with a project that uses Mac menus. When I got the good 0.17.0b1 build to work OK (as in #5193) I was using another project (PHP-POST-Test) without the menus - I will try to get a pared down example shortly which may help.

**Comment by rogerwang** [comment]
@oaleynik Could you please send the spec of your mac system including the CPU model? We'll check whether it's due to lacking AVX support as in #5193.

**Comment by oaleynik** [comment]
@rogerwang I've sent you email with the full system report.

**Comment by Blatman** [comment]
Here is a basic project which demonstrates the crash - just place 0.17b2 into folder.
If line 31 of appbasic.js is remmed out crash will not occur (type: 'menubar'). This same code line is causing the crash on a more complicated project of mine.
[017CrashTest.zip](https://github.com/nwjs/nw.js/files/430918/017CrashTest.zip)

**Comment by oaleynik** [comment]
@Blatman confirmed! Without custom menu 0.17.0-beta2 can start. /cc @rogerwang

**Comment by rogerwang** [comment]
please try http://dl.nwjs.io/live-build/08-23-2016/nw17-ca8692b-15c7eff-b55ab72-6c79a25/v0.17.0-rc1/

**Comment by oaleynik** [comment]
@rogerwang live build 0.17.0-rc1 works

**Comment by Blatman** [comment]
@rogerwang  - live build fine, thanks
