### ISSUE TITLE
nwapp can't run again with args

### ISSUE THREAD

**Issue by felenwe** [nwjs/nw.js#5231]
I had created an desktop app with nw.js-v0.15.4, and package it with nw-builder.
It named my-first-app.exe.
It was running when I first run it with args like:
"my-first-app.exe -u user -p pwd"

And it can't run again behind i closed it.

It's in windows7 64bit.
Can you help me ? 
Sorry for my poor English . Best wishes!

**Comment by felenwe** [comment]
When i run my-first-app.exe with args in the second , the third, the forth ..... ,   it can't display again. And no "my-first-app.exe" in the process list.
If i run it without args , it will be running well every time.

**Comment by ghostoy** [comment]
This issue should be fixed in 0.16.0 or later in #5097. Please reopen if it didn't fixed.

**Comment by felenwe** [comment]
Fixed with 0.16.1 . Thank ghostoy.
