### ISSUE TITLE
Question: Custom (static) package id (chrome-extension://<package_id>)

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#5235]
Hi,

Is it possible to set custom "package id" (part which follows chrome-extension://)?

Use case: integration with the third-party systems, which has js dropins. For example, dropbox. We need to provide domain name from which dropin will be used to make it work. So, we need to make sure that package id will never change.

Thanks!

**Comment by RohitSharma27** [comment]
Yes you can. Use domain property in your package.json. See manifest formats in the documentation.
And, please ask questions in the mailing list.

**Comment by oaleynik** [comment]
@RohitSharma27 oh, sorry, my bad! Thanks for the help!
