### ISSUE TITLE
nw is not defined in normal build

### ISSUE THREAD

**Issue by Llorx** [nwjs/nw.js#5237]
I'm running NW.js 0.16.1 normal build under Win 7 x64 because I don't want DevTools overhead.

There are my files:
package.json:
```
{
  "name": "Browser",
  "main": "./index.html",
  "nodejs": false,
  "single-instance": false,
  "window": {
    "toolbar": false
  }
}
```

index.html:
```
<!DOCTYPE html>
<html>
<head>
<title>Browser</title>
</head>
<body>
Loading...
<script>
load = function() {
	try {
		nw.Window.get().maximize();
	} catch (e) {
		document.write(e);
	}
};
setTimeout(load, 1000);
</script>
</body>
</html>
```

I added a timeout just in case, for testing, and all I get is "nw is not defined". Do normal build come with global webkit variables? I just want to maximize the window and get the command line arguments.

**Comment by Llorx** [comment]
I'm stupid... I thought that nodejs disabled only nodejs background process, but seems to disable nw too.

**Comment by rogerwang** [comment]
close as invalid.
