### ISSUE TITLE
打包exe文件，界面调用不出来

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#5238]
哪位大神帮个忙，我的nwjs打包exe文件后，界面调用不出来，直接拖放是可以的，目录结构应该没问题，
package.json是在打包根目录下面，不胜感激涕零！！！我的邮箱myisis@qq.com

**Comment by linquize** [comment]
你的 `%TEMP%` 或 `%TMP%` 是否在 RAM disk ?

**Comment by rogerwang** [comment]
Please use English only so all users can read
