### ISSUE TITLE
Where is nw.pak?

### ISSUE THREAD

**Issue by gtk2k** [nwjs/nw.js#5240]
download nomal and sdk. but not includes nw.pak. (0.16.1)

**Comment by nhutle** [comment]
Hi gtk2k,

I'm packaging nw with Enigma Virtual Box but I can't find the pw.pak?

It's supposed that I need to import all *.dll and pw.pak inside nwjs folder with the built app.exe right?

Where did you find it?

Thanks.

**Comment by QianruChan** [comment]
I'm new to nw / js and I have the same question too! The README instructions mentioned the files "come with the node-webkit distribution" but I couldn't find them anywhere in the nw.js folder. Please help?

**Comment by nhutle** [comment]
@CQRuu: I found the solution. Importing all file inside nw.js folder excluding app.exe, app.nw and nw.exe will solve the problem.

**Comment by CQRuu** [comment]
@nhutle Thanks Nathan! :D I found this youtube tutorial useful for me too! https://www.youtube.com/watch?v=IhcUWEN6uTY (Native apps from Node webkit)
