### ISSUE TITLE
nwjs crash if I click to close button

### ISSUE THREAD

**Issue by error414** [nwjs/nw.js#5243]
Hi,

nwjs crash if I click to close button in window header. See video https://www.youtube.com/watch?v=rokemotXvA8  If I open devel tools before close window, all is fine.

v0.16.1 has same behaviour.

crash report: http://pastebin.com/YxiG7vQq
# nw --version

1.4.2
# Using nw.js v0.17.0-beta2-sdk

OSX: 10.10.5 (14F27)

**Comment by ghostoy** [comment]
@error414 Please upload your crash dump (*.dmp) file inside `~/Library/Application Support/<your-app-name>/Crashpad/completed/`. And it's even better if you can upload your sample app to reproduce the crash.

**Comment by error414** [comment]
http://blog.petr-cada.cz/000f5a46-d63a-4239-aba7-dbaedb12e5d1.dmp
http://blog.petr-cada.cz/devel.zip

I upgraded to 10.11.6 (15G31), but without success. I found weird solution 

```
var gui = require('nw.gui');
var win = gui.Window.get();

//protect crash, i dont know why it works
win.on('open', function() {
    setTimeout(function(){
        win.focus();
    }, 1000);
});
```

**Comment by Christywl** [comment]
I can't reproduce this crash issue with your tests(devel.zip), it works fine on my Mac with nwjs-sdk-v0.21.3. @error414 , Is this issue still reproduced in your environment?

**Comment by error414** [comment]
No, in 0.21.3 everything is ok, Thank you.
