### ISSUE TITLE
window.reload cann't release memory. 

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#5244]
window.reload() cann't release app's memory. Before nw13.0  I use window.reloadDev() when need to refresh window, but now it is not supported.

**Comment by rogerwang** [comment]
You need to make sure there is no memory leak bug in your app first. This normally happen when you hold references to objects in DOM context from Node context. window.reload() refreshes DOM contexts only.

btw, you may also consider chrome.runtime.restart().

**Comment by liufangfang** [comment]
but if I use chrome.runtime.restart(), when I open two window already this two window all will be closed.

**Comment by rogerwang** [comment]
The memory leak bug in your application should be fixed. reloadDev() is just a workaround and should be used for developing purpose only.

**Comment by liufangfang** [comment]
I know. If the problem of using chrome.runtime.restart() can be solved in 0.17.
