### ISSUE TITLE
How to enable normal non-sdk right-click contextmenu

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5245]
I have been searching through the issues and documentation, but I cannot find anything explaining how the default context menu can be enabled (either in SDK or normal NWJS version). **By normal context menu I mean the one you can access just by right-clicking in this page or any page inside your browser.**

The only thing I can do is disable devtools context-menu, nothing else shows up after that. I have been trying to enable it in an iframe (tested with local and online pages) but all it does is nothing when I press right-click inside the iframe.

It is very important that I can enable the default context-menu so that I can test the cast api (and yes, the `--media-router` flag is enabled in chromium-args): http://thenextweb.com/apps/2016/01/12/soon-youll-be-able-to-use-your-chromecast-without-a-browser-extension/

Currently using NWJS SDK 0.17.0beta2 on Winx64, tested as well on v0.16.0 and v0.16.1 with same results.

**Comment by RohitSharma27** [comment]
There's been a discussion on #5081 see if it helps.

**Comment by Yonezpt** [comment]
@RohitSharma27 I already read that issue during my previous searches, it does not help this because it either explains how to make a custom context menu or disable the SDK context menu.

**Comment by ghostoy** [comment]
Highlighted the request in original issue.

**Comment by Yonezpt** [comment]
@ghostoy So I take it that this is something that is currently not available? If that is the case then I can finally stop trying to search for the solution.

**Comment by ghostoy** [comment]
@Yonezpt Yes.

**Comment by Yonezpt** [comment]
Closing this, collaborator is no longer in the project and after 2 years it feels like this request was abandoned.
