### ISSUE TITLE
In downloads please suggest note about the node.js version whitch is supported in

### ISSUE THREAD

**Issue by arhangelsoft** [nwjs/nw.js#5246]
Greetings!

Today I'm develop somethinng at old machime under windows XP, also the node.js project leave this OS permanently emm... at v5 branch. I'm wasgo to nw.js downloads, but don't found with wich version of node.js LTS or STABLE, or LATEST builds works, thisee info only in changeslist :( 

Please, can you add this info for SDK flawors? Something like "Require Node.js v5.14.7"

**Comment by ghostoy** [comment]
Will be fixed with PR nwjs/website#30
