### ISSUE TITLE
nwjs-sdk-v0.16.1-win-ia32 crash dump generated in the wrong location

### ISSUE THREAD

**Issue by digital-flowers** [nwjs/nw.js#5248]
for nwjs-sdk-v0.16.1-win-ia32 the crash dump is generated inside `%LOCALAPPDATA%\Chromium\User Data\Crashpad\reports` where in the documentation it should be generated inside `%LOCALAPPDATA%\CrashPad`

**Comment by xzhan96** [comment]
@rogerwang per the descripton [here](https://www.chromium.org/developers/crash-reports#TOC-On-Windows1)

>  Any crashes will then cause a minidump file (.dmp) and metadata sidecar (.txt) to be generated in %HOME%\AppData\Local\Chromium\User Data\Crash Reports.

Do you think it's better to update the document of http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/?

**Comment by xzhan96** [comment]
@ghostoy any comment on my previous comment?

**Comment by rogerwang** [comment]
It should be in user data dir of the application: '%HOME%\AppData\Local\appname\User Data\Crash Reports', not Chromium's. And the documentation need to be fixed as well.

**Comment by rogerwang** [comment]
PS: generating it in some common location like '%LOCALAPPDATA%\CrashPad' is good too.

**Comment by rogerwang** [comment]
FYI upstream had a related change: https://codereview.chromium.org/2487783002

**Comment by xzhan96** [comment]
thanks, I will take a look at the upstream change

**Comment by ShobanaV** [comment]
Any update on this? 
Still, the crashdump file is getting created in "C:\Users\<Username>\AppData\Local\Chromium\User Data\Crashpad\reports" folder.

**Comment by Christywl** [comment]
The crash file is still created on `C:\Users<Username>\AppData\Local\Chromium\User Data\Crashpad\reports` folder on Windows with nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by semmel** [comment]
Thank you, great work! 🙇 
The bug, that **no dump file at all is generated**  when `--user-data-dir=<some folder>` is specified as launch argument for nw.exe is now resolved as well!
I just tested with `nw 0.21.5` : 
```
c:\nwjs-v0.21.5-win-ia32\nw --user-data-dir=%APPDATA%\App_B\ App_A\
``` 
and the crash dump is properly generated in 
`C:\Users\Admin\AppData\Roaming\App_B\Crashpad\reports\`

Otherwise 
```
c:\nwjs-v0.21.5-win-ia32\nw App_A\
```
the dump is found here: 
`C:\Users\Admin\AppData\Local\App_A\User Data\Crashpad\reports`

Good work!

**Comment by panther7** [comment]
Please fix doc: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

In legacy version (nwjs0.14.7) dumps are at path `C:\Users\<Username>\AppData\Local\Crashpad\reports`.

**Comment by duaneking** [comment]
Would you be willing to share what you did to fix this? There is no referenced check in, And the issue I'm dealing with is similar enough that I think I can learn something from the change you made to share perspective on my issue.
