### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT loading stylesheet

### ISSUE THREAD

**Issue by afloesch** [nwjs/nw.js#5249]
I'm getting this error trying to load a css file into the main index.html, but only on Mac OS, and only with versions greater than 0.12. On Windows, or when using an older version of node webkit, the resource loads fine.

Using an older version doesn't seem to be an option for me since some of the chrome APIs aren't available.

Has anyone else run into this?

**Comment by rogerwang** [comment]
Could you please submit a case to reproduce this?

**Comment by afloesch** [comment]
My mistake. This turned out to be an issue with the ad blocking software IT has installed on this machine. Since the ad blocker they have installed has some lower hooks into the system (not an extension), I didn't figure it out until trying on another machine.

Interesting that it worked with an older version of Chromium though.
