### ISSUE TITLE
Cannot require any third party node module in windows xp sp3

### ISSUE THREAD

**Issue by qdwang** [nwjs/nw.js#5250]
version: 0.15.4 32bit sdk version
os version: windows xp sp3 32bit

Do `require('request')` in console, it tells me that 
![image](https://cloud.githubusercontent.com/assets/403616/18118951/9ae7dff2-6f8a-11e6-99b2-278b27d1a4bb.png)

**Comment by rogerwang** [comment]
Windows XP and vista is supported with the LTS version.
