### ISSUE TITLE
Web Request interface appears not to be available

### ISSUE THREAD

**Issue by hammer65** [nwjs/nw.js#5252]
I have a Webview tag in my main HTML which I can't seem to use the webRequest API on. request and webRequest is undefined. Attempts to make permissions work in the package.json file causes an error but it was my understanding that all such Chrome APIs were supposed to be automatically enabled. 

`<webview id="app-view" src="http://google.com" />
<script>
  const appView = document.getElementById('app-view');
  console.log(appView.webRequest);
  console.log(appView.request);
</script>`

nw.js v0.16.1
Node v6.3.1
Chromium 52.0.2743.116
commit hash: a3bea28-143aee6-b879ccd-80ede20

**Comment by ghostoy** [comment]
According to [Chrome's document](https://developer.chrome.com/apps/tags/webview#property-request), the event is on `webview.request` property.

**Comment by hammer65** [comment]
Yes and we view.request was undefined. I did read the docs.

**Comment by ghostoy** [comment]
As in the [examples in the documents](https://developer.chrome.com/apps/tags/webview#example), you should access `<webview>` tag in `onload` callback.

**Comment by Christywl** [comment]
@hammer65 , is this issue still reproduced for you with ghostoy's advice?  If yes, could you please provide a sample to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
