### ISSUE TITLE
dragging audio file out of window isn't recognised as audio file?

### ISSUE THREAD

**Issue by hems** [nwjs/nw.js#5256]
I'm trying to drag files out of the window onto other software, for instance drag an audio file onto a music app ( like Logic Pro, Garage Band, Ableton Live, etcs ) but the application doesn't recognise it as audio. 

The only workaround is to drag the file out of the window to the desktop and then onto the app, which is very un-intuitive.

Ideally files like movies and audio will be dragged out it would from a native application and recognized as such so users can drag them directly into a time in the timeline without having to drag to desktop first.

Unfortunately i don't have a test app to illustrate the problem, but there is a dragout example here: https://www.thecssninja.com/html5/gmail-dragout

Thanks a lot.

**Comment by Christywl** [comment]
@hems , how do I reproduce this issue with the link? I try `nw.exe --url=https://www.thecssninja.com/html5/gmail-dragout`, but files can't be dragged out when I drag any link. Does this link reproduce your issue in your side with nwjs?

**Comment by hems** [comment]
@Christywl the issue is if i set an audio file, for instance a .wav or .mp3 file as the download-file and try to drag into an audio application it won't let me drag the file to its "timeline". In order to do it i have to first download the file to the desktop so it will be "downloaded" there and then from there you can drag into the audio application, which is very un-intuitive :(

**Comment by hems** [comment]
At least this is what was happening to me back in 2016 when i was playing around with this feature, since them i haven't updated nw.js and have found a several people looking for similar feature, some of them even moved to electron as reported on this issue: https://github.com/nwjs/nw.js/issues/2200

**Comment by Christywl** [comment]
@rogerwang , can it be merged into #2200?

**Comment by rogerwang** [comment]
merge with #2200. Thanks.

**Comment by hems** [comment]
so this is now fixed? : D

**Comment by hems** [comment]
@Christywl / @rogerwang is it working ( or is there a patch / example somewhere ) using a recent version of nw.js ?
