### ISSUE TITLE
win32 NWjs sdk zip filename might be wrong

### ISSUE THREAD

**Issue by erase2004** [nwjs/nw.js#5258]
nw-builder version: v2.2.2

Today, I'd like to use nw-builder to build NWjs app with v0.17.0.
When nw-builder downloading NWjs, it showed it couldn't find **nwjs-sdk-v0.17.0-win-ia32.zip**.
Then I changed version to v0.16.0. It was ok.
So I inspected https://dl.nwjs.io/,
and found that there was no **nwjs-sdk-v0.17.0-win-ia32.zip** but **nwjs-sdk-v0.17.0-win-x86.zip **.
I am wondering whether there is a mistake on filename.

**Comment by rogerwang** [comment]
The correct file will be available in the folder after build. Thanks.
