### ISSUE TITLE
window.opener is not null

### ISSUE THREAD

**Issue by fangsmile** [nwjs/nw.js#5259]
In nwjs12.3, I open a new nw.exe using 
`require("child_process").execFile('nw.exe', function (err, stdout, stderr) {});` 
The  window.opener is null in the new window. But in 16.1, window.opener is like bellow
![image](https://cloud.githubusercontent.com/assets/3468473/18167676/73601300-7084-11e6-8964-13e9e92df6cf.png). It occurs when using window.reload.

**Comment by RohitSharma27** [comment]
This is not an issue. This is the changed behaviour from v0.13 and onwards. There is a hidden background window which opens the main window you see. Just see what has changed in nw13. It will save you a lot of trouble when you're coming from previous versions.

**Comment by liufangfang** [comment]
@RohitSharma27   how to identify new window is opend through 
`("presenter-view.html", {
                                new_instance: true,
                                focus: true,
                                "icon": "resources/img/axeslide.png"
                            }, function (new_win) {
                                    new_win.moveTo(0, 0);
                                    new_win.focus();
                                    new_win.enterFullscreen();
                                }`
In nwjs12 I judge it using 'window.opener==null'

**Comment by RohitSharma27** [comment]
When and how do you include the file containing this code in your app?
I suppose there is a main window in your application and from that window you run this code. In that case, the window containing "presenter-view.html" is opened by the main window. 
So, `new_win.window.opener` is your main window, `new_win.window.opener.opener` is your hidden background  window and `new_win.window.opener.opener.opener` will be null.

**Comment by Christywl** [comment]
Close per above comments.
