### ISSUE TITLE
graphic interface will not load

### ISSUE THREAD

**Issue by tlacaelelrl** [nwjs/nw.js#5260]
Version nwjs-v0.17.0-win-x64
OS win 7 x64 pro service pack 1
Ram 8GB 
graphics: matrox xenia pro
dell optiplex 990

I built an app which is working on all computers that it is used except this one, I initially thought the issue was something with the app so in order to verify it I went today to the nwjs.io site and downloaded latest version and also the sdk one, tested both and I get the same behavior as with my app so the issue is not related to the app but something with this computer and nw.js.

The app opens up the icon is then displayed in the start bar of windows the process is displayed on the task manager but the interface never loads. Tried in safe mode and got it to run there without any issues so obviously there is something with the OS or an app in it which is not allowing nwjs to display the UI.

I am thinking this is got something to do with the graphics card but I am unsure.

Has anyone experience such kind of issues before?

**Comment by tlacaelelrl** [comment]
Just realized google chrome has the same behavior on this machine.

**Comment by baconface** [comment]
This seems like an issue with the machine and not with Chrome or NW.js.

**Comment by rogerwang** [comment]
As this is in Chrome as well please report issue to upstream. Thanks.
