### ISSUE TITLE
Is the "Enable Proprietary Codecs" GYP guide still valid for NWJS 0.17.0?

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5263]
I am under the impression that NWJS17 is now using GN instead of GYP, so are the instructions in this guide still valid or do they need to be updated to reflect the recent update?

http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by rogerwang** [comment]
Yeah it needs updates. Thanks
