### ISSUE TITLE
Ability to set the description for nwdirectory in "Browse for Folder" dialog

### ISSUE THREAD

**Issue by alexandervrs** [nwjs/nw.js#5265]
I am using **nwdirectory** attribute to an input="file" field in order to trigger the "Browse for Folder" dialog. However the description on the dialog is misleading, I don't want to "_upload_" a folder, but rather choose a folder. It can also give a wrong impression to the user, that you are actually going to upload his, often private, files somewhere.

![browsefolder](https://cloud.githubusercontent.com/assets/899446/18227246/7dd3806c-7226-11e6-95b6-7e8efd9b6efa.png)

Could we have an extra attribute **nwdirectorydesc** that would allow us to set that description? Like so,

`<input id="folder-open-dialog" type="file" style="display: none;" nwdirectory nwworkingdir="" nwdirectorydesc="Please select a folder" role="hidden" />`

**Comment by motla** [comment]
+1

**Comment by octachrome** [comment]
@rogerwang I considered trying to fix this, but after looking through the source code I'm confused about why the message reads "Select Folder to Upload".

- I checked out `nwjs/chromium.src` and looked for the string "Select Folder to Upload" - it only occurs as part of the label `IDS_SELECT_UPLOAD_FOLDER_DIALOG_TITLE`.
- I looked for usages of the label - it is only used when the file select helper is opened with dialog type set to `SELECT_UPLOAD_FOLDER`.
- I checked the `nwjs/nw.js` source, and `SELECT_UPLOAD_FOLDER` is never used - NW.js only uses `SELECT_FOLDER`, which should result in the label `IDS_SELECT_FOLDER_DIALOG_TITLE` being used instead, which reads "Select Folder".

Do you have any idea how/why the "Select Folder to Upload" label is being used?

I am using branch `nw22`.

**Comment by rogerwang** [comment]
Thanks. You can check the following files:
ui/shell_dialogs/select_file_dialog_win.cc
chrome/browser/ui/libgtkui/select_file_dialog_impl_gtk.cc
chrome/browser/ui/libgtkui/select_file_dialog_impl_kde.cc

**Comment by octachrome** [comment]
@rogerwang The reason I was confused is because I was assuming that `nw.js/src/browser/file_select_helper.cc` was used instead of `chromium.src/chrome/src/browser/file_select_helper.cc`. However, debugging shows that this is not the case. The version of `RunFileChooserOnUIThread` in NW.js passes `SELECT_FOLDER` as expected, whereas the Chromium version of `RunFileChooserOnUIThread` passes `SELECT_UPLOAD_FOLDER`. The Chromium version of the function is being invoked, so the wrong message is being displayed.

What is the relationship between these two source files?

**Comment by octachrome** [comment]
@rogerwang Can you shed any light on this?

**Comment by rogerwang** [comment]
The source files in the NW repo was for pre-0.13 and should be removed.

**Comment by octachrome** [comment]
@rogerwang OK. I propose reapplying the following change to `chrome/browser/file_select_helper.cc`:

    -      dialog_type_ = ui::SelectFileDialog::SELECT_UPLOAD_FOLDER;
    +      dialog_type_ = ui::SelectFileDialog::SELECT_FOLDER;

As originally committed in https://github.com/nwjs/nw.js/commit/c5ef962b46b5af0b21a9b85d9c30ea6bdcbba908.

I can do a pull request, but I'm not sure which branch to fork. I can see that `chromium.src/nw22` has the entire NW.js changeset squashed and rebased onto it, so I'm guessing a pull request onto that branch would not be useful to you...

**Comment by octachrome** [comment]
@rogerwang What do you think of my suggestion?

**Comment by octachrome** [comment]
@rogerwang Do you (or someone else) have time to look at my suggestion? I am very happy to spend time working on this issue if it helps to resolve it, but I need some feedback :)

**Comment by rogerwang** [comment]
Sure, will look to fix it with your patch.

**Comment by Pabloandumundu** [comment]
In nw.js version 0.23.6 for windows still appear "Select Folder to Upload". That message is very horrible when you create an application where files are handled locally.

**Comment by charlielee** [comment]
@octachrome @rogerwang I was wondering what the status of this issue was. It is still present in v0.26+. Many thanks :)

**Comment by octachrome** [comment]
@rogerwang I would also like to know the status of this. It seems like a really simple fix, unless there is something I don't understand about it, but it has been many months and many posts to this thread and it is still not resolved.

Is there some way we can help with this? By creating a pull request? Or something else?

**Comment by rogerwang** [comment]
Will see it soon. Thanks.

**Comment by rogerwang** [comment]
Just fixed this in nw28 branch. Added `nwdirectorydesc` as proposed and changed the default string to `Select Folder`. It will be available in the next 0.28.0-rc1 build.

**Comment by octachrome** [comment]
Thanks, really appreciated!

**Comment by rogerwang** [comment]
Please try it: https://dl.nwjs.io/live-build/01-04-2018/nw28-f7b3808-0581a4d-e3aa6ab-1b41f4f/v0.28.0-rc1/

**Comment by octachrome** [comment]
@rogerwang I have updated to 0.28 and this works perfectly now. Many thanks!
