### ISSUE TITLE
Question about MySQL and NW.js

### ISSUE THREAD

**Issue by epixelwebdev** [nwjs/nw.js#5267]
Hi! My name is Gabriel.

I'm new in node.js, and nw.js so, guess that I have a database in a remote location, how can I access to that database using nw.js? there is any method? thanks!

**Comment by RohitSharma27** [comment]
This is not a bug. Please ask questions in the mailing list. 
What you are looking for is a node module that you can use in NW. There are lots of modules that give you this functionality. Just search them out and use whichever suits you.

**Comment by epixelwebdev** [comment]
I've been searching since I've post this. I found that the module 'knex'
would be useful for me, but I can't find a guide, there are all for linux,
and I'm using Windows, how can I install that module in windows without all
these commands like "apt-get install"?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
