### ISSUE TITLE
Failed to load node library (liblibnode.dylib) on child_process.fork

### ISSUE THREAD

**Issue by sporsh** [nwjs/nw.js#5269]
nwjs v0.17.0 osx 64 (sdk version)

```[0905/115312:FATAL:chrome_main_delegate.cc(530)] Failed to load node library (error: dlopen(nwjs-sdk-v0.17.0-osx-x64/nwjs.app/Contents/Versions/53.0.2785.89/nwjs Framework.framework/liblibnode.dylib, 1): image not found)```

Encountered this after upgrading to v0.17.0 on osx.
`liblibnode.dylib` seems wrong, as it's prefixed with a `lib` too many...

I'm currently working around it by symlinking `nwjs.app/Contents/Versions/53.0.2785.89/nwjs Framework.framework/libnode.dylib` to `nwjs.app/Contents/Versions/53.0.2785.89/nwjs Framework.framework/liblibnode.dylib`

`package.json`:
```json
{
    "name": "test-child-process",
    "main": "index.html"
}
```

`index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf8">
    <title>child_process test</title>
  </head>
  <body>
    <h1 id='result'>child_process test</h1>
    <script type="text/javascript">
      var childprocess = nw.require('child_process');
      var worker = childprocess.fork('worker.js');
      worker.stdout.on('data', function(data) { console.log(String(data)); });
      worker.stderr.on('data', function(data) { console.error(String(data)); });
      worker.on('error', function(err) { console.error(err); });
      worker.on('message', function(msg) { console.log(msg); document.getElementById('result').innerHTML = msg; });
      worker.send('message from main.js');
    </script>
  </body>
</html>
```

`worker.js`:
```javascript
process.on('message', function(msg) { process.send('success: message from worker'); });
```

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/09-06-2016/nw17-a2a8780-0b13b2d-3cf5744-92f2bdc/v0.17.1/
