### ISSUE TITLE
Cash in Debug NW 0.12.2

### ISSUE THREAD

**Issue by yirenyiai** [nwjs/nw.js#5270]
I build Debug Version with NW, When I  open the website : 
https://weixin.meimeifa.com

nw will crash when open first,   if I open another website (emaple :  https://weixin.meimeifa.com/crm/#/download)  and then I open the website : https://weixin.meimeifa.com , the nw run ok.

the dump Snapshot link url : 
[http://7xjh5l.com1.z0.glb.clouddn.com/20160906094939.png](url)

**Comment by rogerwang** [comment]
0.12 is not supported any more.

**Comment by yirenyiai** [comment]
thanks ,  It has the LTS version ?
