### ISSUE TITLE
some problem about new version 13 14 15 16 17

### ISSUE THREAD

**Issue by liufangfang** [nwjs/nw.js#5280]
Firstly, our product "axeslide" application is based on nw. At the very start we use 0.12 , and last for near two years.
since the new version 13.0 released, we want to upgrade to lastest version. now we have do this work for two months.  During this time, you have released several versions. Of course , every app has its bugs , the same to your nw. But it cause distress to us, such as the window.open("",function(newWin){}). In 16.1, it is OK. But 16.1 is not supported for XP system. So we use LTS 14.7, but window.open is wrong.  Another problem is window.settimeout setinterval and so on. In the opened window those functions is wrong . Like in the picture below. the left function is not normal.. We has spend so such time on upgrading. Can you give us a  stable nw as soon as possible . Thanks!
![image](https://cloud.githubusercontent.com/assets/3468473/18309683/3167ef42-752d-11e6-86b5-ec58a52c1dd2.png)
@rogerwang  @ghostoy

**Comment by rogerwang** [comment]
The current NW is stable -- it has different API with 0.12 so migration effort is needed. See http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

You described several issues in this one but none of them are with enough details with which we can follow up. For example, 'window.open' is wrong, but how? Please submit issues for each of your problem respectively, better with a reproducible case so we can start working on it quickly.

**Comment by RohitSharma27** [comment]
IMHO nw 13 and others may have their issues and i really like and appreciate the work you guys are doing. It's just the effort that is required to move an already stable, huge code base from 0.12 to the LTS version. I have had my fair share of trouble with the upgradation and seems like i am almost done with it. This issue #4806 is a huge setback for me. What we could have had to ease our pain is backward compatibility, atleast the APIs could have had been exposed like that. For example, window.open could have been easily made compatible with the way it used to return windows. I can't say same about the architectural behaviour update though, which is pretty nice by the way. Thanks for that. :)

**Comment by mscreenie** [comment]
+1 I am looking to migrate from 12 to something with long term support but I can no longer find any updates to 14.
