### ISSUE TITLE
Unable to load node-sass (DLL failed to initialize)

### ISSUE THREAD

**Issue by bajankristof** [nwjs/nw.js#5281]
Hi,

I've been trying to include node-sass (postscss) in my app but on windows I get an error in the console which looks something like this: 
"Dynamic Link Library (DLL) failed to initialize in .../node-sass/vendor/win32-64"

I've tried to build node-sass binaries several ways to resolve this issue, but none of them actually did... 
Here's what I've tried:
- node-gyp (successful build, error in app)
- node-sass' built in build script (successful, error in app)
- nw-gyp (unsuccessful configure action: "undefined component")

I tested this in 0.16.1 and 0.17.0 on windows. (On OS X it works as intended)

Thank you!

**Comment by GendelfLugansk** [comment]
Have similar issue on Ubuntu 16:

`/path/to/project/node_modules/nw/nwjs/nw: symbol lookup error: /path/to/project/node_modules/node-sass/vendor/linux-x64-48/binding.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi`

**Comment by matthew-dean** [comment]
+1 following - I've tried multiple times in the past to compile node-sass for NW.js, but have never been successful.

**Comment by ghostoy** [comment]
@bajankristof Could you please post how your rebuild with nw-gyp?
And we have official document on how to install and rebuild native modules for NW.js. http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/

**Comment by Christywl** [comment]
close until there is more information.
