### ISSUE TITLE
nw.Shell.openItem Relative Path

### ISSUE THREAD

**Issue by longang520** [nwjs/nw.js#5284]
I want to use nw.Shell.openItem Relative Path But I can't start
For example:
nw.Shell.openItem(test\\test.exe)
nw.Shell.openItem(.\\test\\test.exe)

The above can not be, please tell me how to start And increase the startup parameters

example：nw.Shell.openItem(.\\test\\test.exe ttt.text)

**Comment by FiatPax** [comment]
nw.Shell.openItem("test\test.exe")

**Comment by longang520** [comment]
@FiatPax 无法启动，只要在子目录都无法启动。

**Comment by longang520** [comment]
no start @FiatPax

**Comment by ghostoy** [comment]
You should escape `\` in JS strings. e.g. `"test\\test.exe"`.
To spawn a child process, please look into [`child_process` API](https://nodejs.org/api/child_process.html) in Node.js.
