### ISSUE TITLE
OSX - v0.18.0-beta1 aborts/crashes on start

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5285]
nwjs binary (Live Builds - 09/08/16  12:50AM) aborts immediately without creating application folder - tried running in its own folder after unzipping. 
Appears to be similar to OSX bug report part of #5193 which occurred with early pre-release builds of 0.17

OSX 10.11.6 El Capitan  Mini 2012

![krash18](https://cloud.githubusercontent.com/assets/11089335/18338543/99b5c2ae-7591-11e6-80fb-3d8c2f5abd08.jpg)

**Comment by rogerwang** [comment]
@ghostoy please follow this. It's reproducible with the case in #5229 . We also need case to guard this.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
