### ISSUE TITLE
chrome.app.window reference lost after reload

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5294]
This bug is related to : https://github.com/nwjs/nw.js/issues/5181

chrome.app.window.getAll() will return NULL values if you try to reload the content (CMD+R) of window.
I think this shouldn't be the normal behaviour.

Tested on 0.18 beta-1 on Windows 7 and MacOS X.

This feature is important to check which instance is opened every time and I don't want to allow opening the same window multiple times.

Example
Supposing we are running the app with those windows:
window 1 = myapp.com/app1.html
window 2 = myapp.com/app2.html
..
window N = myapp.com/appN.html

If the user click a link with url "myapp.com/app1.html" the Window 1 must be focused (instead to open a new window).

What is the best way to know every opened window?
I was trying with nw.global.__windows and with chrome.app.window.getAll()  but both are bugged, is there any other way (native/api way)
In the past I used a global object where to track every window... but I had to fight with memory leaks and issues like that.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
