### ISSUE TITLE
Signal app doesn't store session data permanently

### ISSUE THREAD

**Issue by onny** [nwjs/nw.js#5295]
Hi,
I'm packagin the chrome extension "[Signal Private Messenger](https://github.com/WhisperSystems/Signal-Desktop)" for ArchLinux using nw.js 0.17.1. Here's the package https://aur.archlinux.org/packages/signal/
Unfortunately session data is lost after closing the program. The directory ~/.config/"Signal Private Messenger" is used.
I'm guessing that Signal is using some kind of safe or crypted storage format which isn't supported by nw.js?!
Any hint would be very welcome.
Best regards,
Jonas

**Comment by rogerwang** [comment]
Hello, as long as it's working as a Chrome App it should be working with NW.js.

**Comment by supervacuo** [comment]
I experience the same behaviour.

Using `nwjs-sdk-v0.18.0-beta1-linux-x64` and `Signal-Desktop` `b1afb79`, according to these instructions: https://timtaubert.de/blog/2016/01/build-your-own-signal-desktop/

The app seems to lose all configuration data whenever it is closed and re-opened. It works in Chrome / Chromium.

1. Launch the app with `nwjs`
2. Scan the QR code to link the app with mobile device
3. Close the app
4. Open the app again

Expected:

Messages are shown

Actual:

Set-up displayed again.

**Comment by onny** [comment]
I've fixed this issue. I skipped the part ziping the dist directory and instead launched it directly
`nwjs ./dist`
Now session data will be permanent.
Unfortunately, the setup wizard will also start again every time.

**Comment by supervacuo** [comment]
Using `nwjs ./dist` I see the setup wizard.. and my messages previously sent from Signal-Desktop aren't visible.

What am I missing? How is this "fixed" if you need to set up the app again every time you launch it?

**Comment by chaoscommander** [comment]
I thought I had a solution, but didn't. Still sharing, since it might help someone not as clueless:
A fairly recent git version of Signal produced output that it couldn't use kwallet. So I made sure kwallet was installed and running, hoping it would be used for session storage. No such luck. Errors disappeared, but the session still is lost on restart (or termination, who knows).

**Comment by onny** [comment]
@supervacuo: Thats true, somehow the registration wizard always reapear but the rest of the program starts fine and remembers its configuration so I'll close this issue for now.
