### ISSUE TITLE
how to use Node.js Addons ?

### ISSUE THREAD

**Issue by pjdepractica** [nwjs/nw.js#5296]
I'm starting with Node.js Addons, I made my own addons node.js guiding me to the documentation.

**hello.cc**

Here defini one methods for running and walking and returns a string.

```
#include <node.h>


namespace demo {


using v8::Exception;
using v8::FunctionCallbackInfo;
using v8::Isolate;
using v8::Local;
using v8::Number;
using v8::Object;
using v8::String;
using v8::Value;


void Walk(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = args.GetIsolate();
  args.GetReturnValue().Set(String::NewFromUtf8(isolate, "Walinkg.." ));
}


void Init(Local<Object> exports) {
  NODE_SET_METHOD(exports, "walk", Walk);
}


NODE_MODULE(addon, Init)


}
```

**binding.gyp**

Here follow the instructions in the documentation.

```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "hello.cc" ]
    }
  ]
}
```

**test.js**

Here I call the module and use.

```
const addon = require('./build/Release/addon');


console.log(addon.walk()); // 'walking'

```

To test this use: node test.js, and working properly.

Now as I can use my module in Nw.js?

**package.json**

```
{
  "name": "namemodule",
  "version": "1.0.0",
  "description": "simple example",
  "main": "index.html"
}
```

**index.html**

This script returns:

```
Uncaught error: an initialization routine dynamic link library (DLL).
\\? \ C: \ Users \ .......\addons.node
```

```
<body>
  <h1>Addons</h1>
  <p>
    Lorem ipsum dolor sit amet.
  </p>


  <script type="text/javascript">
  alert("hello");
    var addon = require('./build/Release/addon');


    alert(addon.walk()); // 'walking'
    alert(addon.fly()); // 'flying'


  </script>
</body>
```

I have also built all of the above with node-pre-gyp, nw-gyp. All this guiding me to the documentation.

But nowhere you put a precise / clear example of how to implement it.

I have to do something else to use my module in nw.js?
I omitted some way?

**Thanks to all who can help, any suggestions are welcome.** 

_Excuse my English, I speak Spanish. Gracias._

**Comment by baconface** [comment]
Just curious but why don't you create modules in pure JavaScript instead?

**Comment by pjdepractica** [comment]
Thanks for your suggestion @baconface.

I want to use to manipulate, control the operating system, only windows. Specifically I want to use a dynamic class librearia (.DLL) that construire in C #. I want to use the DLL in C / C ++. I got the idea to do this. But if there is any way to control natively with OS microsft javascritp the windows, make it known. If there is any way, my aims are control files, directories, registry keys, services, etc.  @baconface  thank you very much for your help.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by RohitSharma27** [comment]
Which nw's version are you using?

**Comment by pjdepractica** [comment]
@RohitSharma27  I'm using the version 0.17.1.
