### ISSUE TITLE
Does not support “-webkit-text-size-adjust”

### ISSUE THREAD

**Issue by witcoder** [nwjs/nw.js#5297]
I want to set the font size less than 12px，How to do it?
version：0.14.7

**Comment by rogerwang** [comment]
Is it working in Chromium browser?

**Comment by witcoder** [comment]
woking in nwjs，version：0.14.7

**Comment by lin-chao** [comment]
chrome not support webkit-text-size-adjust from 27

**Comment by rogerwang** [comment]
close per previous comment.

**Comment by lin-chao** [comment]
@witcoder 

i find a way to set the font size less than 12px

use chrome app api chrome.fontSettings.setMinimumFontSize

https://developer.chrome.com/extensions/fontSettings

**Comment by winston1991** [comment]
@lin-chaoThanks
