### ISSUE TITLE
OSX - 0.18b1 POST on first page submit then GET on succeeding page submits

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5299]
OSX 10.11.6 (El Capitan)
Stripped down project attached to demonstrate - first submit of form is a POST but further submits are seen as GET - this worked OK upto 0.17.2 but broke on 0.18b1.
Tried Chrome Canary (55.xxxx) on localhost:3000 and it worked fine as did Firefox Nightly.
Add nw.js app to App folder of test project. Use Inspect on DevTools which shows status of IncomingMessage
[POSTtest2.zip](https://github.com/nwjs/nw.js/files/469413/POSTtest2.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
