### ISSUE TITLE
Default printer changed after printing

### ISSUE THREAD

**Issue by petermeester** [nwjs/nw.js#5300]
Hi, the new printing feature is awesome . We are using it in our application. We developed an application for our delivery partners (restaurants) so they can receive orders from our website which will be automatically printed. Works fine. We can't push multiple printjobs at once because we first create a local PDF file received from our API but we have settle this using a custom function which check every five seconds for new printjobs and execute one printjob at a time (some kind of print queue).

In our application the client can choose a normal A4 printer and a POS printer. We noticed that when a printjob is executed, the default printer on Windows has been changed. Is this a bug in Chromium? When we execute the print function, we define the printer name, so we don't use the default printer. Is there a way to get the default printer and set the default printer back again after the printjob has been executed?

NWjs version: nwjs-sdk-v0.17.0-win-x64
OS version: Windows10

**Comment by rogerwang** [comment]
Should be a bug in NW. Will fix it.

**Comment by petermeester** [comment]
Hi @rogerwang,

I just tested it again with nwjs-sdk-v0.19.3-win-x64 and it appears to be solved. 
Is that right, did you solved this? If so, this issue can be closed.

**Comment by rogerwang** [comment]
I didn't do anything. So it looks like an upstream issue and automatically
fixed by upgrading to latest Chromium. it can be closed now.

**Comment by petermeester** [comment]
Thnx, I will close this issue.

**Comment by murrah** [comment]
Hi. 

Thanks so much for this print API. It has allowed me to completely ditch iText on the backend. Cool!

However, I think this might still be a bug.
nw.js SDK v0.28.3, Win64

I print the current window html to a pdf as below. If I then do a win.print() to open the "normal" print dialog box the default printer has been set to "Save as PDF". I am happy to reinstate the original printer but could not find a way to get it before I save as pdf, nor reinstate the default.

	win.print({
		pdf_path: me.pdfDestinationFile, 
		headerFooterEnabled: false
	});

If I subsequently do this to open a (non nw.js) window, the chrome print dialog opens as it should but the printer is set to "Save as PDF"

	var win = window.open();
	win.print();  

If I set it to a printer then close and re-open it stays set to the printer. And, if I then run the above print to pdf code the default reverts to "Save as PDF".

Any ideas? Is it possible to find out the current printer and re-select it afterwards?

Thanks so much,
Murray

**Comment by rogerwang** [comment]
@murrah could you please submit a new issue for this? Thanks.

**Comment by murrah** [comment]
Sure. :-)
