### ISSUE TITLE
Setting win title so that you can open to a window if it exists

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#5301]
In javascript, you can set a window title and then when you call a `window.open('http://link.com','titleOfWindow')` it will open the link in a window with that title. But then if you do the same thing with a different link, it will open the other link in the same window if a window with the title already exists. Is there a way to do this using webkits `win.open()`? I've tried doing 

```
nw.Window.open('http://link.com', {title: '_windowTitle'}, function(win) {
});
```

So when I call that from a window, it opens another window with _windowTitle as the title. But then when I go back to the first window and call that again, it opens another window (rather than it opening the link in the window that already is open).

**Comment by RohitSharma27** [comment]
It's the ID that is used to remember the window and it's properties. Have you tried that?

**Comment by joshterrill** [comment]
Okay, something weird is happening. I've got this:
```
// button1
nw.Window.open('http://link.com', {id: '_windowTitle'}, function(win) {
});

// button2
nw.Window.open('http://link2.com', {id: '_windowTitle'}, function(win) {
});

// button3
nw.Window.open('http://link3.com', {id: '_windowTitle'}, function(win) {
});
```

When I click `button1`, it opens a new window, works fine. When I go back to the first window, and click `button2`, it refocuses the newly opened window, but does not take me to http://link2.com. It stays on http://link.com from the first click. Same thing happens when I click `button3`, it focuses the window, but doesn't change the URL.

**Comment by Christywl** [comment]
@joshterrill , is this still reproduce in your environment? If yes, could you please provide a sample to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
