### ISSUE TITLE
NWJS 0.17.1 crashes on start

### ISSUE THREAD

**Issue by GeorgeNava** [nwjs/nw.js#5302]
I just installed nwjs 0.17.1 on OSX 10.9.5 and on running nwjs I get this:

dlopen /usr/local/bin/../Versions/53.0.2785.101/nwjs Framework.framework/nwjs Framework: dlopen(/usr/local/bin/../Versions/53.0.2785.101/nwjs Framework.framework/nwjs Framework, 257): image not found
Abort trap: 6

This is the output from node -pe process.versions

{ http_parser: '2.5.0',
node: '5.0.0',
v8: '4.6.85.28',
uv: '1.7.5',
zlib: '1.2.8',
ares: '1.10.1-DEV',
icu: '56.1',
modules: '47',
openssl: '1.0.2d' }

Any help would be appreciated.

**Comment by ghostoy** [comment]
This issue looks like you symbolic linked `Contents/MacOS/nwjs` to `/usr/local/bin`. It's not a supported way to start NW. You can use `alias` instead of a symbolic link to start it.

**Comment by GeorgeNava** [comment]
That's what I did. Ok, thanks.
