### ISSUE TITLE
Child window goes fullscreen (as desktop) in El Capitan

### ISSUE THREAD

**Issue by gdiazfor** [nwjs/nw.js#5303]
Hi everyone,

I'm using version 0.12.3 of  nw.js.
Im trying to create a custom notification for my app.

When using my app in native macOS fullscreen I try to open a new -floating- window with the following code:

`var a_window = gui.Window.open('notification.html', {
      width: 300,
      height:150,
      frame:false
});`

The thing is, this new window automatically goes fullscreen as a new desktop (space) in mission control (you can see the mini notification as a whole new window in the image I uploaded). 
I want this new window to be independent from the main window, and appear in the current active monitor. 

I have already tried using window.open, but cannot remove the toolbar since it is used in the main window.

Thanks in advance

![screen shot 2016-09-14 at 16 33 18](https://cloud.githubusercontent.com/assets/20682933/18526945/057e4ea0-7a99-11e6-9e31-89197cbaf8cf.png)

**Comment by rogerwang** [comment]
0.12.x is not supported any more. Thanks.
