### ISSUE TITLE
[request] Let win.evalNWBin support Buffer

### ISSUE THREAD

**Issue by finscn** [nwjs/nw.js#5304]
I want to load the  bin file from remote server via Ajax or WebSocket .
So I hope it  could support Buffer , Thanks.

Or support dataURL or base64 code.

**Comment by finscn** [comment]
Or support dataURL or base64 code

**Comment by mscreenie** [comment]
This was already requested by me. https://github.com/nwjs/nw.js/issues/5220

I have yet to test it but it looks good so far.

**Comment by rogerwang** [comment]
close as duplicate.
