### ISSUE TITLE
NW.js version 0.18.0 beta 1 starts with a greater `window.devicePixelRatio` than the previous versions

### ISSUE THREAD

**Issue by Mithgol** [nwjs/nw.js#5306]
This issue is observed on Windows 7 where the system's control panel setting for font size and other elements is 125%, see the screenshot:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/18558799/258a47aa-7b7d-11e6-9070-834af04263d4.png)

NW.js version 0.18.0 beta 1, unlike the previous NW.js versions, seems to observe this (system-wide) setting and starts with `window.devicePixelRatio` equal to `1.25`, see the screenshot:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/18558927/b1cea2b0-7b7d-11e6-9344-e69b98fa5ec1.png)

As a result,

* text is larger (in all windows) than in the previous versions of NW.js,

* images are also larger, raster images become blurry and not pixel-perfect any longer (such as icons in “Developer Tools” console on the above screenshot).

This issue may be seen either as a bug (because raster images lose their pixel-to-pixel perfection) or as an intended behaviour (because NW.js now adheres to an additional system-wide setting).

If it's a bug, it should be fixed.

If it's an improvement, there should be a known (documented in release notes) setting to opt out of it. (For example, users of Mozilla Firefox may set `layout.css.devPixelsPerPx` to `1` on their `about:config`; is there anything like that in Chromium settings controlled by the file `package.json` of a NW.js-based application?)

**Comment by rogerwang** [comment]
Thanks for reporting. What about Chromium 54 on this? We should be the same.

**Comment by Mithgol** [comment]
I don't really know where to get a build of Chromium 54 for Windows, but Chromium 55 from https://download-chromium.appspot.com/ is indeed the same (larger fonts and images, also `window.devicePixelRatio` is `1.25`).

**Comment by Mithgol** [comment]
The direct cause of this change seems to be https://codereview.chromium.org/2157243003

**Comment by Mithgol** [comment]
However, there does not seem to be an accepted workaround recipe. If there is, I've yet to discover it.

(People at https://bugs.chromium.org/p/chromium/issues/detail?id=642613 reported that `zoom: reset` might help in undoing the zoom. But that's treated as a bug.)

**Comment by rogerwang** [comment]
https://www.chromium.org/getting-involved/dev-channel

**Comment by rogerwang** [comment]
"--force-device-scale-factor" can be used to force setting it.

**Comment by rogerwang** [comment]
close as it seems to be a change in upstream.

**Comment by rogerwang** [comment]
It's noted in the release notes.

**Comment by Mithgol** [comment]
Thanks.

( for future references: that note is at http://nwjs.io/blog/v0.18.0/ )

**Comment by Siizer** [comment]
I have tried to use the body reset zoom approach but while it size the window "ok", a lot of DOM element like sliders or button are completely "skewed" in their window positioning.
I have a project fully developed on nw.js and would like to migrate it to the latest version.
I have a first question with the pixel ratio has been changed?
And second any solution to solve the "skewness"?

**Comment by Mithgol** [comment]
@Siizer

1) Have you tried the `--force-device-scale-factor` idea that @rogerwang recommends?

2) Can you attach a screenshot that demonstrates such skewness?

**Comment by Siizer** [comment]
@Mithgol 
Hi there! Solution 1 did it. I simply added "chromium-args" : "--force-device-scale-factor" on package.json file right after the window option list and everything is as on previous NW.JS version.
Thanks a lot for your help.
Regards

**Comment by Mithgol** [comment]
For the record, the alternative hack of `body { zoom: reset; }` stopped working in NW.js v0.23.x and thus `"chromium-args": "--force-device-scale-factor"` is the only remaining solution.
