### ISSUE TITLE
Always receive "Couldn't set selectedTextBackgroundColor from default ()"

### ISSUE THREAD

**Issue by finscn** [nwjs/nw.js#5307]
When App started , the console will display
```
2016-09-16 01:40:14.993 nwjs Helper[63603:633952] Couldn't set selectedTextBackgroundColor from default ()
```

Is it an issues ?

**Comment by rogerwang** [comment]
Chromium browser should also have this, please follow https://bugs.chromium.org/p/chromium/issues/detail?id=641509
