### ISSUE TITLE
error nw 0.7.3  win.reloadDev() is not a function

### ISSUE THREAD

**Issue by aldisseia** [nwjs/nw.js#5308]
I am using windows 8 did the whole process but when I try win.reloadDev (), giving this error win.reloadDev () is not a function.
can help, thank you

**Comment by rogerwang** [comment]
See doc regarding this function: http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by timfish** [comment]
If `reloadDev` is no longer going to be supported, it should be removed from the latest docs:

http://docs.nwjs.io/en/latest/References/Window/#winreloaddev
