### ISSUE TITLE
[osx] Remove dialog when running on read only volumes (.dmg)

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#5309]
When running packaged NW.js apps on read only volumes, the a dialog showed up to install it. The dialog has nothing to do with NW.js, but was part of Chrome startup check. It should be remove.

See discussions on mailing list in https://groups.google.com/d/topic/nwjs-general/-b_4toDe-uY/discussion

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

Please follow up in the mailing list.
