### ISSUE TITLE
Tray is not working

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5313]
nwjs-v0.16.1-win-ia32 tray events and menu is not working.Menu is not populated to tray and there is just icon only  i'm using 32 bit normal edition but it is working fine with nwjs-v0.15.2-win-ia32.

Below sample code i'm using to populate tray

```
// Load native UI library
var gui = require('nw.gui');

// Create a tray icon
var tray = new gui.Tray({ title: 'Tray', icon: 'img/icon.png' });

// Give it a menu
var menu = new gui.Menu();
menu.append(new gui.MenuItem({ type: 'checkbox', label: 'box1' }));
tray.menu = menu;
```

**Comment by rogerwang** [comment]
Please try the latest version.

**Comment by freddy-daniel** [comment]
Thanks latest version is working perfect
