### ISSUE TITLE
NW.exe doesn't open my package.json when app is packaged in .nw (zip) - Manifest file missing or unreadable

### ISSUE THREAD

**Issue by angularchobo** [nwjs/nw.js#5319]
My NWJS applications runs fine, until I try and package it in a zip file. I follow the guide on github [here](https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps).

I get an error "Failed to load extension from: <mypath..> . Manifest file is missing or unreadable".

The package.json is in the root of the archive as indicated in the guide. I've tried to run other people's projects and it loads fine. I simply have no idea on how to debug this.

I am running Win7 x64

Versions are as follows:
nw.js v0.17.4
Node v6.6.0
Chromium 53.0.2785.116

**Comment by ghostoy** [comment]
@angularchobo Could you upload your app or at least a reproducible case? BTW guides on wiki are only for 0.12 or earlier versions. Please follow guides on our official document site http://docs.nwjs.io.

**Comment by angularchobo** [comment]
I resolved my issue by trial and error, I suspected it was the Google Voice API node module, since with its dependencies it's something like 17k files in 1.8k folders and extremely deeply nested. Since I've had problem with Win7 max filepath with this module, I thought it might be breaking NWJS.

I used the "flatten-packages" module and it loads fine, albeit with a 30-35 seconds of loading time even in an uncompressed zip.

**Comment by ghostoy** [comment]
With latest npm (>3.0 I think), the dependencies should be really flat.

**Comment by angularchobo** [comment]
I did indeed use npm 3.10.7 to install dependencies, they weren't flat. Flatten-packages worked well and didn't break anything. Anyway, you can mark this as closed or I'll close it, if you don't think it's indeed an issue with NWJS.

Now to address the resulting 30 second loading time..

**Comment by ghostoy** [comment]
Closing this issue. Please open another to address the loading time issue and make sure to provide a sample app to reproduce.
