### ISSUE TITLE
Unable to access files using absolute path on Mac

### ISSUE THREAD

**Issue by KiresMA** [nwjs/nw.js#5320]
**NW version**: 16.1 sdk-x64
**Angular**: 1.49
**Platform**: Mac, OS X El Capitan, Version 10.11.6
**Issue (appears only on Mac)**: Failed to load resource net::ERR_FILE_NOT_FOUND chrome-extension://[id]/[absolute path to a file] 
#### Full issue description

Our app supports Windows and Mac platforms. We moved application **from NW 12.3 to 16.1**
On Windows there were issues with chrome-extension ERR_UNKOWN_URL_SCHEME loading pictures which were solved using $compileProvider like it's suggested in NW docs ( http://docs.nwjs.io/en/latest/For%20Users/FAQ/#images-are-broken-in-anugarjs-and-receive-failed-to-load-resource-xxx-neterr_unknown_url_scheme-in-devtools )

But on Mac appears another error loading, for example, fonts, audios or pictures:
Failed to load resource net::ERR_FILE_NOT_FOUND chrome-extension://[host id]/[absolute path to a file] 
Files are in place and if I manually change chrome-extension:// to file:///  OR if I change the path to relative it works fine.
I saw in this issue https://github.com/nwjs/nw.js/issues/5143 that chrome-extension works only for files inside my app and file protocol should be used instead automatically, but didn't see a solution and I don't understand why it continues to use chrome-extension even though absolute path is provided.
So I suppose NW treats the path like '/Users/username/Project/name.app/Content/...' as a relative path and that's why uses chrome-extension protocol instead file, like it should in this case.

Thanks

**Comment by ghostoy** [comment]
@KiresMA There is no file path in web world, but only URL. Once given a "path", browser will compose a URL based on existing URL. Usually a `path` will become `<scheme>://<host>/<path>`. If you want to load a local file, you need to provide a URL, like `file:///<path>` instead of `/<path>`.

**Comment by KiresMA** [comment]
So what are you suggesting to do, replace everywhere /<path> to file:///<path> ? This doesn't seem to be a good option, since everybody will have to do it after upgrading nwjs version and if the project is large enough it will bring a lot of problems and take a lot of time.
Is there any other solution I can use?
And I still don't understand why it works on Windows, but does NOT on Mac?

PS: thank you for your correction with url and path, I will be informed in future :)

**Comment by ghostoy** [comment]
Ideally you can just redirect your homepage to the same file rewritten with `file:` URL, like `location = 'file://' + process.cwd() + location.pathname`. However due to #4806, Node APIs doesn't work for `file:` currently. So I would suggest you using following workaround for loading resources (image, video etc.) only.

You can insert a `<base>` tag with `href` set to `file:` URL of your app. For example, insert following code with [`inject_js_start`](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#inject_js_start):

```js
document.addEventListener('DOMContentLoaded', ()=>{
  // early exit for non chrome-extension: scheme
  if (location.protocol !== 'chrome-extension:') return;
  var base = document.createElement('base');
  base.href = encodeURI('file://' +
  // Windows: replace \ with / and add prefix /
                process.cwd().replace(/\\/g, '/').replace(/^(?=[^\/])/g, '/') +
                '/');
  document.head.appendChild(base);
})
```

Limitation: the code will fail for node disabled frames.

**Comment by ghostoy** [comment]
BTW why it works on Windows? I guess you simply use the path on the disk of the resource. Windows uses `\` as path separator, which makes NW.js treat it as a local file instead of composing it as part of URL.

**Comment by KiresMA** [comment]
I attached a simple example to recreate the issue, NW 16.1
[app.zip](https://github.com/nwjs/nw.js/files/486806/app.zip)

On Windows the picture is displayed and in devtools I can see that it uses 'file' protocol.
On Mac the picture is not displayed and 'chrome-extension' protocol used instead.
Of course it doesn't make sense to use cwd() in this case, but it's just in order to see the problem.

**Comment by ghostoy** [comment]
@KiresMA That's exactly what I guessed. On Windows, path separator is `\` which makes NW.js think it's a local file. But on other OSes, paths are separated by `/`, which is same as separators used in URL. NW.js, also browsers, will assume it's a path of URL instead of local file. You can use my previous tricks to avoid this issue. Or you have to replace any file path with `file://` URL.

**Comment by KiresMA** [comment]
Unfortunately solution with base.href won't work in our case.
Is there a way/chrome-argument I can tell chromium to treat all paths started with / as absolute paths to local files, not as a part of URL?
It would be a nightmare to replace all file path in the app :(

**Comment by ghostoy** [comment]
@KiresMA I don't know other tricks can do this. I tried my workaround and it works. Could you post a sample app that the workaround won't work?

**Comment by iLeonidze** [comment]
The same issue (from nwjs v16.1). Solved using "file://", works both Windows & MacOS.

**Comment by Christywl** [comment]
'file://' also works fine for me on Mac with nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
close until more information is available.
