### ISSUE TITLE
How to show already running app in windows

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5322]
In mac reopen feature is showing app if opened.How to handle this feature with windows nothing happening after executing again.I know official document is not provided this feature but this is important.App must be show window if already running

**Comment by ghostoy** [comment]
@freddy-daniel Does [`open` event of App](http://docs.nwjs.io/en/latest/References/App/#event-openargs) help? It's fired when same app is launched. You can listen to the event and do anything you want, such as show a window.

**Comment by freddy-daniel** [comment]
Open event is not working .actually it is for 
"Emitted when users opened a file with your app".
I need show opened window if user reopen same app again.

**Comment by freddy-daniel** [comment]
Thanks it's worked.....
