### ISSUE TITLE
nw.js causes websocket open error

### ISSUE THREAD

**Issue by pmenico** [nwjs/nw.js#5325]
When I use https://apprtc.appspot.com/r/2762825 using Chrome from my desktop I have no issues,
But when I load the same using a nw.js package I get a "Websocket open error: Websocket error."
The error shows up once I press the Join button. The video of myself shows fine on my end.

The response I got from apprtc support is "You cannot use the websocket server from other domains." which is cause by nw.js

Any ideas how to fix or get around this? I am running on desktops not servers.

The nodewebkit package.json I am using is below:

'{
 "main": "https://apprtc.appspot.com/r/2762825",
 "name": "nw-WebRTC",
 "description": "nw-WebRTC",
 "version": "0.1.0",
 "keywords": [ "nw", "node-webkit", "WebRTC", "Video", "nodejs" ],
 "window": {
 "title": "nw-WebRTC",
 "icon": "http://piwas1030/Logo/Logo.png",
 "toolbar": true,
 "frame": true,
 "width": 700,
 "height": 600,
 "position": "center",
 "min_width": 50,
 "min_height": 50,
 "max_width": 1900,
 "max_height": 1900,
 "resizable": true,
 "show_in_taskbar": true,
 "show": true
 },
 "webkit": {
 "plugin": true
 },
 "maintainers":[ {
 "name": "PM",
 "email": "pm@gm.com",
 "web": ""
 }]
 }'

**Comment by rogerwang** [comment]
It should be downloaded and launched from local directory, or add 'node-remote' to package.json for the domain.
