### ISSUE TITLE
how to require local node modules when use the "node-remote"?

### ISSUE THREAD

**Issue by kospot** [nwjs/nw.js#5326]
My mainfist like this:
```
{
···
"main": "http://192.168.44.125:3000/helper/source/index.html",
 "node-remote": "http://*",
···
}
```
node-remote can make the remote page use nodejs~but what is the base path of node ?
if I use local main file such as "/source/index.html", I can require a node file "/source/node_src/test.js" by this way require("./node_src/test"), but if my main is a remote page, how to require local node modules?

**Comment by rogerwang** [comment]
It should be put in a directory 'node_modules' under the directory where package.json resides. And 
please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
