### ISSUE TITLE
nwworking dir on windows with multiple attribute  ? 

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#5327]
hi

nwworking dir seems not working on select file dialog (open) on windows (nwjs 14.7 / 17.4 / 18 ... ) when i try to open a mapped drive like Z:\2016\CA\EIFFAGE\Paris\16CA091 or \\Myserver\something\blabla it s not working (pasting the same link in the just opened file dialog works normally), it always open my execdir ...

in my code i just have

`<input nwworkingdir="${defaultPath}" style="display:none;" id="fileDialog" type="file" multiple />
`
seems working without the multiple attr :/

no problems on osx/linux

thanks

**Comment by ghostoy** [comment]
Did you tried to escape `\` with `\\` in `defaultPath` ?

**Comment by smolleyes** [comment]
hi ghostoy

yes same thing with \ or \\ multiple attribute is the problem, works fine in chrome with same path

**Comment by ghostoy** [comment]
@smolleyes I was wrong about the escaping. You don't need to escape the path. I can confirm the bug on Windows with `multiple` attribute set. And it should have nothing to do with network mapped drive.

**Comment by smolleyes** [comment]
hello

thanks ghostoy ;)

**Comment by smolleyes** [comment]
hello

some progress on this ghostoy ? :p

thanks!

**Comment by smolleyes** [comment]
hi 

thanks for the fix ghostoy, i don t have windows now ... is it included in lastests builds ? (so can be closed) ?

**Comment by ghostoy** [comment]
@smolleyes Not yet.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
