### ISSUE TITLE
minimize and restore workin together

### ISSUE THREAD

**Issue by OjciecStalin** [nwjs/nw.js#5328]
There is something strange when use nw.Window.get().minimize(); after this function nwjs call two events first minimize and after this next restore but didn't restore window. Bug?

Edit.

And more it does only when window is Maximized.

**Comment by tiegeda** [comment]
Got this problem too。 turn minimize from maximize， a restore event come after minimize。very confused。

**Comment by ghostoy** [comment]
merged to #5388
