### ISSUE TITLE
Set WM_CLASS

### ISSUE THREAD

**Issue by rightaway** [nwjs/nw.js#5329]
I'm on Linux and when using `xprop` to get the window properties of an application based on nwjs, there's no WM_CLASS property set for window managers to use for mapping windows. Please see https://github.com/butterproject/butter-desktop/issues/356.

**Comment by ghostoy** [comment]
It should be fixed in #4693 for nw 0.14 or later.

**Comment by ghostoy** [comment]
Merged to #4693
