### ISSUE TITLE
NWJS kills session on close

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#5330]
Is there a way to preserve cookies and sessions after close? It seems that when I close my app, it kills everything, so when I open it again, it has me login to my app again.

**Comment by ghostoy** [comment]
@joshterrill Could you please post your sample app , NW.js version and OS?

**Comment by Christywl** [comment]
@joshterrill , is this issue still reproduced for you? If yes, could you please provide your sample app to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
