### ISSUE TITLE
How to run nwjs executable on ubuntu 16.04

### ISSUE THREAD

**Issue by sksar** [nwjs/nw.js#5332]
I am unable to open nwjs executable on ubuntu 16.04, its showing that its a shared library and ubuntu does not know how to open it, i am tring to run nwjs version 0.17.4 (linux ia32),

The allow executing file as a program is checked, but still when i open it it shows me this, 

![image](https://cloud.githubusercontent.com/assets/11752260/18816862/e3672cf8-836f-11e6-9e72-37f5d7267691.png)

How do i fix this... ?

**Comment by Asp3ctus** [comment]
Just open it in your terminal

**Comment by ghostoy** [comment]
merged to #5287

**Comment by sksar** [comment]
but i want it to be run by double clicking, as i will distribute my app as such.

**Comment by ghostoy** [comment]
@sksar There was a discussion in mailing list: https://groups.google.com/d/topic/nwjs-general/2bnKU8dYZrA/discussion . You can create a bash script or a `.desktop` file to launch your app.
