### ISSUE TITLE
shortcut is active when the  nw app is blur

### ISSUE THREAD

**Issue by dalidong2009** [nwjs/nw.js#5333]
hi :
I use the code Synopsis like http://docs.nwjs.io/en/latest/References/Shortcut
and it work well.
but  when the nw app window is blur, the Shortcut still active.
is there  any way to disable the Shortcut whe the window is blur?

**Comment by dalidong2009** [comment]
OS: windows 7  32 bit
nwjs version: 0.15.4

**Comment by ghostoy** [comment]
The shortcut is globally available in your OS. You can register/unregister it or simply do nothing when window is blur by using `blur` and `focus` events. See http://docs.nwjs.io/en/latest/References/Window/.

However if you only want a window scoped shortcut, I recommend you to use DOM key events.

**Comment by dalidong2009** [comment]
thanks,
