### ISSUE TITLE
How to communicate with newly opened window?

### ISSUE THREAD

**Issue by FiatPax** [nwjs/nw.js#5334]
I'm starting a second window and injecting a script in it, I need to receive some feedback from the script. How do I do that?

```
nw.Window.open('https://github.com', {
                    'inject_js_end': './test-script.js'
                })
```

**Comment by RohitSharma27** [comment]
What sort of information do you want to communicate? You can access parent window in the child window using window.opener and window.postmessage() is always there to communicate between windows.
Since, this is not a bug. Please close the issue and ask questions in the mailing list. :)

**Comment by FiatPax** [comment]
Thanks those suggestions should do.
