### ISSUE TITLE
warning of "ATTENTION: default value of option force_s3tc_enable overridden by environment."

### ISSUE THREAD

**Issue by bandittalent** [nwjs/nw.js#5335]
Hi buddy:

I'm just developing a project based on nwjs+nodejs, it goes on well after many reading and tries. But I found the warning message "ATTENTION: default value of option force_s3tc_enable overridden by environment." comes out in terminal each time nw window is shown. 

Can somebody tell me why this information is shown? As I want to distribute my project to other guys and they will also need explanation on this strange message. Anyway it would be appreciated if the message can be avoided if not necesary.

It happens on following environment:
node-v6.2.1-linux-x86.tar.gz + nwjs-sdk-v0.15.2-linux-ia32.tar.gz
node-v6.6.0-linux-x86.tar.gz + nwjs-sdk-v0.17.4-linux-ia32.tar.gz

my OS: ubuntuLTS14.04

result from "uname -a" is : "Linux rex-ubuntu32-lvm 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:22:19 UTC 2016 i686 i686 i686 GNU/Linux"

You can reproduce with this simple example html code:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js .
    <p><div class="log"> </div></p>
    <script type="text/javascript">
    </script>
  </body>
</html>
```

Thanks very much for help from anyone :)

**Comment by sirrobert** [comment]
I'm having the same problem.  My example code:

    <!DOCTYPE html>
    <html>
    <head></head>
    <body>Example text.</body>
    </html>

**Comment by ghostoy** [comment]
Does your app crash or behave strange?

**Comment by bandittalent** [comment]
oh my god, I was giving up on this topic since no one gave an notice for a long time. My app didn't crash, it's just strange to have this message always shown. While explanation on it would be appreciated.

**Comment by rogerwang** [comment]
Someone reported Google Chromium giving the same error message in their system. We believe that it's a Chromium warning. You could try with Chromium and ask this in upstream project. Thanks.

**Comment by neofutur** [comment]
still , explanation on it would be appreciated.

**Comment by OlafSzmidt** [comment]
Exactly what @ProhtMeyhet has written. The value in your bash files has been overridden by the running build.

**Comment by Mrnumbers9** [comment]
This is a error from SDL. Simply calling `SDL_Init(SDL_INIT_EVERYTHING)` will trigger it.
