### ISSUE TITLE
Error: bind EACCES 0.0.0.0:69

### ISSUE THREAD

**Issue by stts-x** [nwjs/nw.js#5338]
When i'm trying to bind (datagram) socket to 69 port in Linux I'm getting 
`Error: bind EACCES 0.0.0.0:69
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`
error.
No difference if I run program by root, with sudo, compiled or from interpreter - the error is the same.
The port is definitely free. If I build and run simple C test program, it binds successfully.
Also I double-checked that I have no any special ACL modules in my system, no special glibc replacers and so on.

Tested an reproduced at least in three different x86_64 linux systems:
Mageia 5, Manjaro, Fedora.
NWJS version : 0.17.4

**Comment by dmitrydvorkin** [comment]
any comments, guys?

**Comment by dmitrydvorkin** [comment]
?

**Comment by stts-x** [comment]
up

**Comment by baconface** [comment]
You can check if it is a privilege issue by trying a free port higher than 1024. If you were to try port 1025 or above that isn't already binded do you still get this error? And if not have you tried a different free port 1024 and below and get this error?

**Comment by baconface** [comment]
Second thought I don't think it would be a privilege issue since you would likely get `listen EACCESS` instead of a `BIND` error. You might have something causing you not to bind to 0.0.0.0 as your interface. Have you tried 127.0.0.1, the hostname, or a different local IP instead?

**Comment by baconface** [comment]
Also, what are you running a server for? It could be an issue with that particular package/dependency and not an NW.js issue.

Beyond everything I stated there is no way we can troubleshoot it further without a minimal test case provided to us.

**Comment by rogerwang** [comment]
It should be that you'll need root privilege to bind to that port.
