### ISSUE TITLE
the <input> in <iframe> auto focus after the iframe page loaded , even when I was using other <input>

### ISSUE THREAD

**Issue by mobljs** [nwjs/nw.js#5339]
[example.zip](https://github.com/nwjs/nw.js/files/502038/example.zip)
nwjs-v0.17.4-win-x64,

I have several input element in my page , and I also have some iframe element load some pages , when I was typing, once one iframe loaded , if this iframe has an autofocus input , my working input will blur , how can I run away this issue ?

**Comment by rogerwang** [comment]
Could you please upload an example page?

**Comment by mobljs** [comment]
@rogerwang  see 'example.zip'

**Comment by mobljs** [comment]
I have work around thie by set "inject_js_start" : 

document.addEventListener('DOMContentLoaded', function(){
     var inputs = document.querySelectorAll('input,textarea');
     var len = inputs.length;
     for(var i=0; i<len; i++){
          inputs[i].focus = function(){}
     }
}, false);

but this still was not the absolute solution, it just can work for the focus by javascript code , **if the HTML is `<input type="text" autofocus>` , it can not work.**

**Comment by Christywl** [comment]
I can reproduce this issue with example.zip on Linux and Windows with nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
@Christywl thanks. what's the behavior in Chromium browser?

**Comment by Christywl** [comment]
Yes, it also reproduces on Chrome M57 on Linux.

**Comment by rogerwang** [comment]
Then please report this to upstream @mobljs
