### ISSUE TITLE
prevent window.parent access from iframe

### ISSUE THREAD

**Issue by danyocom** [nwjs/nw.js#534]
Hello, 
      I am looking into developing an application using node-webkit. One thing this application will do is load untrusted content (html/js) (served from a webserver running on localhost) into an iframe. I noticed that no matter what sandbox attributes I set on the iframe (but always allowing js), the javascript inside the Iframe can call window.parent.someNodeJsCommand(). 

Is there a way to prevent the iframe from being able to access window.parent?  I do need to communicate between the iframe and the parent application, and was planning on using window.postMessage for that.

Thanks,
       Dan

**Comment by aymanar** [comment]
If the target for an <a> tag is something other than "_blank" the "new-win-policy" does not fire. So there is still an issue, it replaces the entire nwjs container (i.e. especially with ctrl+clicking a link)

**Comment by baconface** [comment]
On the original topic this is easier than you guys think.

```javascript```
var iframe = document.getElementById("your-iframe-id");
iframe.contentWindow.window.parent = "";

iframe.addEventListener('onload', function() {  
  iframe.contentWindow.window.parent = "";
});
```

What this does is nuke the iframe's (with the id value of "your-iframe-id") window.parent. And the listener renukes if if they refresh the iframe.

**Comment by brettz9** [comment]
Not fully sure, but I think one may also need to deal with `window` properties such as `top` and `frameElement`.

**Comment by aymanar** [comment]
@baconface  This doesn't the problem of ctrl-clicking or shift-clicking

**Comment by yybawang** [comment]
然而看了半天还是不知道本地node如何控制iframe，蛋疼
