### ISSUE TITLE
Unable to monitor http/https requests made by node

### ISSUE THREAD

**Issue by harumando** [nwjs/nw.js#5341]
Hello,
When I make a request I don't see it in the developer tools. I can see the request only when it's made with jquery or native xmlhttprequest.

I've binded console.log on the 'end' event and I can see that node-webkit is actually doing the request and it's returning me a correct response. But doing these "blind requests" is very hard. May be i'm missing something? How can i debug native node http requests without console.log'ing them.
Thank you.

**Comment by gpetrov** [comment]
I was actually wondering the same. Inspecting the background page where node runs, shows zero on the network traffic tab while a lot of node http/https requests are going on made by require('http") module

@rogerwang any chance on getting the node http traffic  on the network tab there?

**Comment by rogerwang** [comment]
It might be doable, but requires some effort since requests from Node don't go through Chromium's logic.

**Comment by gpetrov** [comment]
@rogerwang actually it is already build in the latest NodeJS - so you can easily bind with the --inspect flag
See https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.x2ysytoqe

So it should be just a matter of activation ...

**Comment by rogerwang** [comment]
The link describes JS debugging only. I don't think the network monitoring
feature is in there.

**Comment by gpetrov** [comment]
well other people have done it nicely in devtool: https://mattdesl.svbtle.com/debugging-nodejs-in-chrome-devtools

and also in node-inspector https://github.com/node-inspector/node-inspector

See also https://github.com/cyrus-and/chrome-remote-interface

It will be really neat to have the full debugging tools available in NWjs - it will make our lives really much more easier! Thanks for consideration @rogerwang !

**Comment by rogerwang** [comment]
In the link you provided, network monitoring is done by using a xhr-request
module in application... Could you please make sure of it?

**Comment by gpetrov** [comment]
Well the whole v8_inspector was landed in Node 6.3:

https://github.com/nodejs/node/pull/6792

so check it and also:
https://chromium.googlesource.com/chromium/src/third_party/WebKit/Source/platform/v8_inspector

it should be all there

**Comment by rogerwang** [comment]
The v8 inspector is used for inspecting V8 thus JS execution, nothing to do
with network monitoring.

Are you able to monitor traffic from http module in Node?

**Comment by gpetrov** [comment]
My bad about the v8_inspector - will check for the http monitoring with it when using the --inspect command line in node.

But you should really check https://github.com/cyrus-and/chrome-remote-interface - it has the network monitoring in the very first sample...

**Comment by rogerwang** [comment]
I came across that repo. It is just a API layer exposing devtools inside
Chromium. The feature you want has to be done in Node -- integrate http
module with devtools.
