### ISSUE TITLE
nw unzips the content again even when the app is already running

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#5342]
NW : 0.14.7
OS : Windows

Hi guys,
I have zipped my content and merged it with "myApp.exe", as we used to do in nw0.12.3. Now, I have a listener for the `open` App event. I run my application and it unzips the content in `temp` directory. So, my application is now in running state and I am listening for the `open` event. When I invoke my application with arguments (let us say using the command prompt), it takes quite a lot time for my `open` event listener to invoke. The reason is : 
NW unzips the content again in the temp directory then deletes this new folder and starts using the old folder again (there was already a nw_1243... folder in the temp directory as my app was in running state).
I don't understand the reason to unzip it again. :( This unzipping makes our app look slow. I just want to know the reason why it is being done and if we can change this behaviour, in case the app is already running, without breaking anything.
If I don't zip it and place it using the current way i.e. inside the `package.nw` directory, then the `open` event's handler gets invoked in less than a second which is awesome. :)

**P.S**. : I know that we don't need to zip the content anymore in case of windows. We can place it in the "package.nw" folder. But, it will make our app vulnerable and we don't want to do that.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
