### ISSUE TITLE
open _blank link in new browser error

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#5344]
Hi,

I'm trying to open a link from my app in NWJS in a browser.

Before it ignored it, but then I've used this snippet from the docs:

```
nw.Window.get().on('new-win-policy', function(frame, url, policy) {
        // do not open the window
        policy.ignore();
        // and open it in external browser
        nw.Shell.openExternal(url);
    });
```

Problem is, once i click it, it shows a popup reading this:

```
There is no application set to open the URL unsafe:chrome-extension://lmgkoofikellalepboimckhheffpoioh/null.
```

How can I get rid of this popup an make a specific link open the standard browser on the user's operating system with the given url?

**Comment by chino23** [comment]
Hmm... I haven't changed anything and now it seems to work.

Is there a reason that showed once? Don't want to run the risk of it happening again

**Comment by Christywl** [comment]
The code in the docs also works well for me. I don't reproduce this error on Linux with nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
Will add a test case to guard this.
