### ISSUE TITLE
Chrome App Identity Login Not Working

### ISSUE THREAD

**Issue by putraxor** [nwjs/nw.js#5351]
Hello, I tried using chorome.identity to auth my app but it seems NWJS can not load login page that provided by chrome at chrome://chrome-signin/?access_point=6&reason=0.
I have my package.json just like this:

```
    "permissions": ["tabs", "identity", "storage", "https://www.googleapis.com/*",
        "https://*.googleusercontent.com/*",
        "https://ssl.gstatic.com/",
        "https://www.googleapis.com/",
        "https://accounts.google.com/",
        "chrome://chrome-signin/?access_point=6&reason=0"],
    
    "oauth2": {
        "client_id": "xxxxxx.apps.googleusercontent.com",
        "scopes": [
            "https://www.googleapis.com/auth/drive"
        ]
    },
    "key": "MIIBIjANBxxxxxxx"
```

and this is my code:
```
 chrome.identity.getAuthToken({'interactive': true}, function (token) {
            if (chrome.runtime.lastError) {
                console.log(chrome.runtime.lastError);
                return;
            }

            console.log('Tokennya adalah', token);
        });
```
![login](https://cloud.githubusercontent.com/assets/6225082/19216285/cbbefc14-8ddf-11e6-9bf9-8696b2e0a300.png)

is there any wrong code I've written?

**Comment by rogerwang** [comment]
It's a bug, will fix it soon.

**Comment by putraxor** [comment]
@rogerwang What exactly wrong?

**Comment by rogerwang** [comment]
The sign-in UI is not included.

**Comment by rogerwang** [comment]
@putraxor I have a fix for this. Is there any ready-to-run samples I can use to verify it?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/10-12-2016/nw18-6de67d1-48dbbce-ed8a267-ac9dfd6/v0.18.0/

**Comment by putraxor** [comment]
Thank you very much @rogerwang

**Comment by rajjerry** [comment]
I am not able login using google so can you guide me.

**Comment by rogerwang** [comment]
Please see the follow up in  #5574
