### ISSUE TITLE
session lost after open the develop tool and close it on nw0.17.6

### ISSUE THREAD

**Issue by cecilpeng** [nwjs/nw.js#5355]
nw.js 0.17.6  on Windows 7 x64

Reproduction steps:
1. run nw.exe
2. F12 open the devtools, run `window.location.href='https://www.baidu.com'` in Console Tab
3. switch to the Application Tab, check Cookies, then you will see Session Cookie, such as BD_HOME as follow:
![image](https://cloud.githubusercontent.com/assets/3832621/19259332/1c2c55a0-8fb3-11e6-8fa7-e3c173f773a6.png)
4. Close the devtools
5. F12 reopen the devtools, check Cookies, then Session Cookie lost as follow:
![image](https://cloud.githubusercontent.com/assets/3832621/19259315/f5e23e46-8fb2-11e6-9fd8-8147d730cda8.png)

This hinders my debugging.

**Comment by mscreenie** [comment]
I keep running into strange quirks when I think of upgrading to a newer version of nwjs. I've just encountered this bug but with non-sdk version. What irks me is seeing rebasing of newer Chromium versions when there are many bugs with current.

In my case, Opening a new window and closing it will cause session cookie to be lost. 

OS: Win 7
Nwjs: 18.4 win 32.

**Comment by ghostoy** [comment]
It should be fixed in 0.18.8.

**Comment by mscreenie** [comment]
@ghostoy  Great, confirmed as working. Will test more thoroughly as I encountered this problem on non-sdk version too.

**Comment by cecilpeng** [comment]
Doesn't work in 0.19.4? I retried but it still existed.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
