### ISSUE TITLE
msnodesqlv8 can not work in nwjs

### ISSUE THREAD

**Issue by hubbly** [nwjs/nw.js#5358]
msnodesqlv8 can not work in nwjs

I install msnodesqlv8 and it work well, but when I copy it to nwjs/node_modules, I got this error

Uncaught Error: None of the binaries loaded successfully. Is your node version either >= 0.12.7 or >= 4.2.x or >= 5.1.1 or >= 6.1.0failIfNoBinaryExported @ D:\nwjs-sdk-v0.17.6-win-x64\node_modules\msnodesqlv8\lib\sqlserver.native.js:61liveLoad @ D:\nwjs-sdk-v0.17.6-win-x64\node_modules\msnodesqlv8\lib\sqlserver.native.js:48(anonymous function) @ D:\nwjs-sdk-v0.17.6-win-x64\node_modules\msnodesqlv8\lib\sqlserver.native.js:24Module._compile @ module.js:580Module._extensions..js @ module.js:595Module.load @ module.js:497tryModuleLoad @ module.js:456Module._load @ module.js:448Module.require @ module.js:507require @ internal/module.js:20(anonymous function) @ D:\nwjs-sdk-v0.17.6-win-x64\node_modules\msnodesqlv8\lib\ConnectionWrapper.js:5Module._compile @ module.js:580Module._extensions..js @ module.js:595Module.load @ module.js:497tryModuleLoad @ module.js:456Module._load @ module.js:448Module.require @ module.js:507require @ internal/module.js:20(anonymous function) @ D:\nwjs-sdk-v0.17.6-win-x64\node_modules\msnodesqlv8\lib\sql.js:20Module._compile @ module.js:580Module._extensions..js @ module.js:595Module.load @ module.js:497tryModuleLoad @ module.js:456Module._load @ module.js:448Module.require @ module.js:507require @ internal/module.js:20self.require @ (program):11

and my code is below
var db = require("msnodesqlv8");
db.open("driver={sql server};server=192.168.2.58;database=cassrundb;uid=sa;pwd=sa;", function (err, conn) {
                if (err) throw err;
                //console.log(err);
                //console.log(conn);
                conn.query("select 100", function (err, res) {
                    if (err) throw err;
                    console.log(res);
                });
})

**Comment by kailniris** [comment]
you have to recompile the binaries with nw gyp

**Comment by ghostoy** [comment]
@kailniris is correct. Please rebuild your node modules with nw-gyp. Please read official document for details http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/.
