### ISSUE TITLE
can not see OK/Cancel button when  confirm  at onbeforeunload

### ISSUE THREAD

**Issue by dalidong2009** [nwjs/nw.js#5359]
here is my code :  

 window.onbeforeunload = function(evt) {
            return "请点击第二个按钮Cancel（否）留在本页面！";
        };
when onbeforeunload, the page show a confirm dialog like :  
![11111](https://cloud.githubusercontent.com/assets/8622414/19309235/3e260238-90b6-11e6-812d-7eb449695bd8.png)

if  i use confirm normally , the page show confirm dialog correctly

my environment is win7 x86
process.versions["node-webkit" ] is "0.15.4"

**Comment by ghostoy** [comment]
Could you post a full sample app and the your Windows theme?

**Comment by ghostoy** [comment]
We cannot reproduce this issue with latest NW.js and there is no response for 3 weeks. So close it. Please reopen it if you still see this issue.
