### ISSUE TITLE
Code Signing - Windows / Mac / Linux

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5361]
Trying to download my app built with nwjs, I get warning from chrome browser (at the end of download) that the app could be malicious / malware.

More, trying to open it on windows there is an alert about Unknown Author.

Please, could you tell how to fix it? Do I need to sign the code? 
Is there any specific tutorial for nwjs signing code?

Could I sign alle the 3 apps (platforms) with the same certificate?

Thank you

**Comment by cecilpeng** [comment]
You must sign the code. It depends on the certificate.
> Could I sign alle the 3 apps (platforms) with the same certificate?

**Comment by AndryBray** [comment]
I close this as it's not closely related to nwjs
