### ISSUE TITLE
Cannot rename nw.exe with 0.18.0

### ISSUE THREAD

**Issue by connectiblutz** [nwjs/nw.js#5362]
With 0.18.0 for Windows, if you rename nw.exe to anything else (nwNewName.exe, for example), the app will not run. This worked under 0.17.3 and earlier.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by AndryBray** [comment]
@rogerwang Do we have possibility to change even the "nwjs Helper.app" for macOS app into the name of application?

**Comment by rogerwang** [comment]
@AndryBray please file another issue for mac.
