### ISSUE TITLE
chrome onErrorOccurred - error page override

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5365]
@rogerwang @iteufel 
I open again a new ticket related to https://github.com/nwjs/nw.js/issues/4904

The solution proposed by @iteufel  doesn't work with nw.js 0.17.6 / 0.18 (there is no iframe) and even trying to replace DOM inside the event callback there is no possibility to do it.

I even tested this solution : http://stackoverflow.com/questions/14841256/change-chrome-4xx-page

```
chrome.webNavigation.onErrorOccurred.addListener(function (details) {
    // Updating the browser window with desired URL
    chrome.tabs.update(details.tabId, {
        url: chrome.extension.getURL("page.html")
    });
});
```

but on redirect I get chrome-extension:// invalid error ( Resources must be listed in the web_accessible_resources manifest key ) so I get a loop because of the redirect error.

Do I need to set my custom error page inside allowed resources? This is already a local resource.
I can't find a way to do what on chrome we do with:

```
"web_accessible_resources": [
        "page.html"
    ]
```

Any other way to accomplish it?
Thank you

**Comment by AndryBray** [comment]
@rogerwang I see if the connection goes down, the app is often redirected to this (horrible) pages of chrome. Can't we turn off this feature in some way?

thank you

**Comment by rogerwang** [comment]
@Christywl this may not be a question. Please verify the report.

**Comment by Christywl** [comment]
@AndryBray, is this issue still reproduced on the latest nwjs build? If so, could you please provide the full test case and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
