### ISSUE TITLE
app open event doesn't fire

### ISSUE THREAD

**Issue by jonwwilkes** [nwjs/nw.js#5366]
Read the following before submitting your issue, thank you.

on Ubuntu lts 16.04

from a terminal run the nw executable: `./nw &`

open the background window and set a listener for the open event:
`nw.App.on('open', function(data) {
  console.log("argv data is " + data);
});`

finally, try running another nw from the terminal: `./nw`

Bug: running the second nw does not trigger an "open" event in the first one.

**Comment by jonwwilkes** [comment]
tested on Windows 7 with nw.js 0.18.1

**Comment by ghostoy** [comment]
@jonwwilkes It works for me on Win 7 & Ubuntu 14.04 with NW.js 0.18.2.

Please submit your full sample app and NW.js version.

**Comment by jonwwilkes** [comment]
@ghostoy: just tried 0.18.2 on Windows.  I typed `nw.exe` on the command line, clicked "Inspect Background Page", set the listener shown above, then typed `nw.exe` again.  Nothing printed out in the devtools for the background page, nor in the devtools for the main page.

**Comment by ghostoy** [comment]
I see, it's the problem of the default app. The `open` event works in real app.

**Comment by jonwwilkes** [comment]
Ah, I see!  Thanks so much for catching that.

Indeed, it does work in my app.  It's quite possible I was looking for the log in the wrong devtools window.

**Comment by ghostoy** [comment]
I'm closing this issue and creating another issue for events issue of default app.
