### ISSUE TITLE
gui.App.clearCache() freez apllication nwjs 0.18.0

### ISSUE THREAD

**Issue by rudzikdawid** [nwjs/nw.js#5368]
Fedora 24
nwjs 0.18.0
Ctrl+Shift+C indeed deleted the cache files but also freez applications
Any idea how fix it?

**with nwjs 0.17.6 works like charm**
```
const gui = window.require('nw.gui');

var clearCache = {
    key : "Ctrl+Shift+C",
    active : function() {
        gui.App.clearCache();
    },
    failed : function(msg) {
        console.log(msg);
    }
};

var clearCacheShortcut = new gui.Shortcut(clearCache);

gui.App.registerGlobalHotKey(clearCacheShortcut);
```

**Comment by AshleyScirra** [comment]
This appears to be what breaks Construct 2 games in 0.18.0.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by AshleyScirra** [comment]
Thanks for the quick fix. Do you think this justifies a .1 release? I feel a bit nervous about sending out a nightly build to production.

**Comment by rogerwang** [comment]
Yeah. There's 0.18.1 scheduled tomorrow.

**Comment by AshleyScirra** [comment]
Awesome :)
