### ISSUE TITLE
nwjs-v0.17.6-win-ia32 broken when a timer app has alert 

### ISSUE THREAD

**Issue by carefreejiang** [nwjs/nw.js#5376]
I use nw.js(nwjs-v0.17.6-win-ia32) for a little app. It is a timer, two methods remind me,one is bell,another is alert window.On the macbook(nwjs-v0.17.6-osx-x64) all is ok,but on the windows bell is ok,alert window is wrong.The nw.exe died random,and if the app run on the windows at the same time open chrome, it will die quickly. This is my code:https://github.com/carefreejiang/timer
- State which version are you using:nwjs-v0.17.6-win-ia32
- State which OS version are you running with:win7/win8
- Provide a reproducible case if possible: ( upload failed,please see https://github.com/carefreejiang/timer)
- Attach the crash dump file : 170e5c28-d3d2-4f3b-b694-50a364824aaf.dmp ( upload failed)

**Comment by carefreejiang** [comment]
now,I use html5 notification,The nw.exe never died random. Maybe the nw.exe die by alert()? The alert() prevent nw.exe .

**Comment by Christywl** [comment]
@carefreejiang , I used your code https://github.com/carefreejiang/timer, seem the codes are updated. Are there codes to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
