### ISSUE TITLE
Gamepad API not working on Windows 10

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#5377]
The gamepad API does not seem to work in NW.js 0.18.1 on Windows 10. Here is a quick demo as a package.nw (although any html5 gamepad demo should do): https://dl.dropboxusercontent.com/u/15217362/bugs/nwjs-gamepad/package.nw

Testing with a wired Xbox 360 controller, it works fine in Chrome 54 stable, but in NW.js it never registers a gamepad connected or any inputs.

I heard the Win10 anniversary update changed details about how the gamepad drivers work, so maybe that affected it, but Chrome can still detect gamepads so perhaps there's a fix Google made that NW.js needs as well.

**Comment by mapmerry** [comment]
I get the same problem, NW.js 0.18.1 on Windows 10 using the wired Official Xbox 360 Controller for Windows and the pad stops working altogether. It is working fine in v0.17.0

**Comment by MadSpyxFR** [comment]
Same issue with nw0.18.1 and 0.18.2 (ia32 and x64 from https://dl.nwjs.io/) and package.nw from AshleyScirra on win7Pro-64b and win8.1Pro-64b

**Comment by dolomite** [comment]
Confirmed, gamepad no longer working on NW.js 0.18.1 on Windows 10.

**Comment by rogerwang** [comment]
NW 0.18.1 sdk works for me on windows 10 with this case: 'nw.exe --url=http://html5gamepad.com/'

I don't have any physical game controller so I was testing with a virtual one: http://vjoystick.sourceforge.net/

**Comment by rogerwang** [comment]
There is a bug in the case of using it in app rather than a remote URL. I'll fix it.

**Comment by finscn** [comment]
@rogerwang ,  recently , I reported a bug about gamepad API to chromium team: 

https://bugs.chromium.org/p/chromium/issues/detail?id=655037

They confirmed this bug and fixed. which version of nw.js could include the patch ?

**Comment by rogerwang** [comment]
@finscn it's not released. You can find that with the tool "Find releases" in https://omahaproxy.appspot.com/

**Comment by rogerwang** [comment]
The fix I pushed is a workaround. The root cause is the same issue with an upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=500931

Please vote on that bug for the real fix from upstream.
