### ISSUE TITLE
CentOS, Red hat enterprise linux - how to run NodeWebKit from command line in silence mode?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5379]
Use NodeWebKit in CentOS as streaming server, therefore we need to run the NodeWebKit (WebRTC) in silence mode for 30 instances.

On any interconnection, we will need to record the audio per instances and save it as below to stream:
`
 pacat -r -n "Chrome input" | sox -t raw -r 44100 -s -L -b 16 -c 2 - "output.wav"
`

Can you please do the follow up?

**Comment by shamun** [comment]
This project is to kill the YouTube closed source streaming concept and make our own open-source enterprise quality NodeWebKit Streaming server. Please advise, urgent.

**Comment by ghostoy** [comment]
@shamun Please ask questions in our mailing list @ https://groups.google.com/forum/#!forum/nwjs-general. Thanks.
