### ISSUE TITLE
Tray not Working in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5380]
Below basic code is not working. there no tray menu populating with this code please help me.

```
var gui = require('nw.gui');

var tray = new gui.Tray({ title: 'Tray', icon: 'img/icon.png' });

var menu = new gui.Menu();
menu.append(new gui.MenuItem({ type: 'checkbox', label: 'box1' }));
tray.menu = menu;
```

**Comment by freddy-daniel** [comment]
Please help anyone it is urgent . Anything wrong with tray icon concept in Linux. Please give replay

**Comment by banezaklan** [comment]
Just install libappindicator1 package and they will start working again.

`sudo apt-get install libappindicator1`

**Comment by Christywl** [comment]
@freddy-daniel , is this issue still reproduce in your test?

**Comment by freddy-daniel** [comment]
We fixed that issue by custom plugins.
