### ISSUE TITLE
Documentation "building nwjs" missing a step

### ISSUE THREAD

**Issue by vankasteelj** [nwjs/nw.js#5381]
Hi, 

I believe the docs are missing the final step. I followed everything up to https://github.com/nwjs/nw.js/blob/nw18/docs/For%20Developers/Building%20NW.js.md#build-flavors but I now have a multi-gigabyte folder, with the files required in them, but mixed with some other unneeded stuff. 

It used to be `ninja -C out/Release dist` but that's not recognized anymore. 

I don't know what to do to strip the wanted files now.

Also, my libnw.so is 3,3Gb for a reason, maybe the same as described above, but I'm not sure.

I currently use :

``` bash
# strip binaries & libs
cd out/nw 
strip nw
strip lib/*.so

# move required files to out/dist
cd .. 
mkdir -p dist
cp -R nw/nw nw/lib nw/locales nw/icudtl.dat nw/natives_blob.bin nw/nw_100_percent.pak nw/nw_200_percent.pak nw/resources.pak nw/snapshot_blob.bin dist/
rm -rf dist/lib/*.TOC
```

But there must be some ninja that can take care of that for me, isnt it?

**Comment by ghostoy** [comment]
@vankasteelj use `ninja -C out/nw dist`.

**Comment by Christywl** [comment]
@vankasteelj , is the cmd in the ghostoy's comment ok for you?

**Comment by vankasteelj** [comment]
I think so, but only on linux. If I remember correctly.

**Comment by Christywl** [comment]
Close this issue
