### ISSUE TITLE
Blank tray icon in Mac

### ISSUE THREAD

**Issue by freddy-daniel** [nwjs/nw.js#5384]
Hi, 
   I'm facing a trouble to integrate tray icon in nwjs app.I have png icon with 22x22 resolution.I have tested with another icon it appearing perfectly but not in real color.I need to appear my icon in real color.screenshots and icon attached below.I'm using latest nwjs v18.1

![capture](https://cloud.githubusercontent.com/assets/19286267/19548924/e035ef9e-96be-11e6-82e1-29279445f28e.JPG)

![this icon appearing](https://cloud.githubusercontent.com/assets/19286267/19548826/6902296a-96be-11e6-8875-53af178b1b53.png)

![capture2](https://cloud.githubusercontent.com/assets/19286267/19548960/0f0e73b8-96bf-11e6-9c5e-213a3e7da6ef.JPG)

![not appearing](https://cloud.githubusercontent.com/assets/19286267/19548828/6942de88-96be-11e6-96eb-00490791a6f7.png)

**Comment by ghostoy** [comment]
@freddy-daniel You can set `iconsAreTemplates` option to `false` when creating a tray. It's `true` by default. See [Apple's document about template property](https://developer.apple.com/reference/appkit/nsimage/1520017-template?language=objc).
