### ISSUE TITLE
missing window handle when open invalid url

### ISSUE THREAD

**Issue by walton007** [nwjs/nw.js#5385]
The same as this issue #https://github.com/nwjs/nw.js/issues/5105

**OS:** Mac OS EI Caption
**nw version:** 0.13
**bug description:**
   I tried to open an invalid url,  then there will be an invalid window popup without valid handler, and i can't control this invalid window anymore. The result is that user will see a strange window open. 

**Sample code:**
   You can looked at following code, _url is an invalid url, and the returned win value is undefined!

nw.Window.open(_url, {
      width: 200,
      height: 200,
      frame: false,
      //fullscreen: true,
    }, function (win) {
     console.log("win:", win)  // print undefined
})

**Question:**
Is there any workaround to close the invalid window?

**Comment by ghostoy** [comment]
This issue should be fixed with #5294 in 0.17.4 or later. Please try with latest stable NW.js version. Be free to reopen it if it still doesn't work for you.

**Comment by Comee** [comment]
@ghostoy  @walton007  #4844 Here is the solution.

```javascript
nw.Window.open(_url, {
	width: 200,
	height: 200,
	frame: false
}, function(win) {
	console.log("win:", win) // print undefined
	chrome.windows.getCurrent(function(win_current) {
		chrome.windows.remove(win_current.id); // remove the white window
	});
});
```

**Comment by Christywl** [comment]
@rogerwang , I can reproduce this issue. But Comee provided a solution, is it a final solution? Can we close this issue? Or I still triage as 'bug'?

**Comment by rogerwang** [comment]
is it a duplicate of #5105?

**Comment by Christywl** [comment]
I think so, + #4844

**Comment by rogerwang** [comment]
close as duplicate.
