### ISSUE TITLE
Specified "icon" in package.json is not considered anymore, at least since 0.18.1

### ISSUE THREAD

**Issue by KSchreyer** [nwjs/nw.js#5387]
- I've downloaded _nwjs-sdk-v0.18.1-linux-x64_ and started my existing nwjs-app
- When I'm now switching between my running desktop applications (via Alt+Tab), the application "icon" specified in package.json is not used anymore. Instead the default Chromium-Icon is shown in the application switcher. The same is true for the "normal" version _nwjs-v0.18.1-linux-x64_.
- When I start my nwjs-app with version _nwjs-sdk-v0.17.6-linux-x64_, the specified icon is displayed.

I'm using Linux Mint 17.3 Cinnamon 64-bit (codename _Rosa_), which is based on Ubuntu Trusty.

Kai

**Comment by bjoernneumann** [comment]
Additionally the chromium-icon is used when chromium-browser is installed. (nwjs 0.18.5)
This happened before with nwjs 0.13 #4537.

**Comment by ghostoy** [comment]
Merged to #5247. The fix is available on nwjs/chromium.src#43 and pending for review.
