### ISSUE TITLE
[v0.18.1] --single-process Is Not Working Properly

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#5389]
**General Information:**
- Using NWjs version 0.18.1
- Windows 7 with latest drivers
- Log file (converted into txt): [debug.txt](https://github.com/nwjs/nw.js/files/543333/debug.txt)

**Problem Description:**
When I'm trying to run a packaged _Construct 2_ game (HTML5) while having "--single-process" set as a property in the chromium-args, NWjs doesn't run properly and immediately closes itself.

**Observed Result**
NWjs single process starts to run and automatically closes itself after 1-2 seconds without any crash or visible error message.

**Expected Result**
NWjs should run fine with the recently added single processing argument.

**Comment by rogerwang** [comment]
Could you please provide a sample?

**Comment by TheRealDannyyy** [comment]
> Could you please provide a sample?

Surething here you go (it's in package.nw format): [package.zip](https://github.com/nwjs/nw.js/files/543571/package.zip)

**Comment by rogerwang** [comment]
Thanks. It appears that '--single-process' is only working with command line argument now. Will fix it.

**Comment by TheRealDannyyy** [comment]
Good news, thanks a lot.

**Comment by MadSpyxFR** [comment]
@rogerwang I still have the issue on nw.js0.18.2; tested with the file from TheRealDannyyy with nw.js0.18.1 and 0.18.2 (ia32 and x64 from https://dl.nwjs.io/ ) on win7Pro-64b and Win8.1Pro-64b

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by TheRealDannyyy** [comment]
@rogerwang is there any ETA when this will go stable?
Sorry I'm new here and don't know how you guys schedule those releases.

**Comment by rogerwang** [comment]
The next release is in a week. Thanks.

You can try the build for now from
http://dl.nwjs.io/live-build/11-05-2016/nw18-38c9a48-dd7db35-3bed0cb-c0c10eb/v0.18.6/
