### ISSUE TITLE
v0.18.1 incompatible with Enigma Virtual Box?

### ISSUE THREAD

**Issue by guidoselva** [nwjs/nw.js#5392]
**General Information:**

Windows 10 64bit
NW.js version 0.18.1 (same behaviour with version 0.18.0)
Enigma Virtual Box version 7.70

**Problem Description:**

Since version 0.18.0 I cannot package anymore my application with Enigma Virtual Box.
Before running Enigma Virtual Box, the application starts correctly. But after packaging it with Enigma Virtual Box, when I start the file app_boxed.exe nothing happens, and I only obtain a debug.log error file containing the following messages:

**[1020/132452:FATAL:chrome_elf_main.cc(82)] Check failed: patched == 0.
Backtrace:
  SuccessfullyBlocked [0x0000000180011821+38453]
[1020/132455:ERROR:file_io.cc(30)] read: expected 4, observed 0**

Everything worked fine up to version 0.17.6.

**Comment by rogerwang** [comment]
Please try this build: http://dl.nwjs.io/live-build/10-21-2016/nw18-a820695-68f77db-ae7e389-2021126/v0.18.2/ , which contain a fix.

**Comment by guidoselva** [comment]
That build is working fine, thanks for the quick fix.

Looking forward to the official release of v0.18.2...

**Comment by frinteractive** [comment]
The build is working fine all thanks to the fix
