### ISSUE TITLE
There is no win.isDevToolsOpen() method in v0.14.7 but had in document.

### ISSUE THREAD

**Issue by turnerguo** [nwjs/nw.js#5394]
I just using v0.14.7 LTS recently, and found there is no win.isDevToolsOpen() method in Window reference, but it is described in the document. So, is this a bug?
Really excepted that LTS version to be solid stabled, please have a look on this.

**Comment by divinemanwah** [comment]
Are you using the SDK version? Only that has devtools functions :)

**Comment by turnerguo** [comment]
@divinemanwah Yes I did, tried both nwjs-sdk-v0.14.7-osx-x64 and nwjs-sdk-v0.14.7-win-ia32，I believe the same issue in other versions.

**Comment by turnerguo** [comment]
And the doubt thing is that both win.showDevTools and win.closeDevTools methods exists, just missed win.isDevToolsOpen.

**Comment by WoodyWoodsta** [comment]
It is unfortunate that a method such as this one has been removed. Keeping track of the state of devtools by means of events is messy (especially when the `devtools-opened` event has been removed as well).

Would anyone happen to know of another way to detect the state of devtools?

**Comment by GeekHuber** [comment]
Anybody know of another way to detect the open state of devtools?

**Comment by Christywl** [comment]
Duplicate with #4487,#5063, @rogerwang

**Comment by rogerwang** [comment]
close as duplicate.
