### ISSUE TITLE
How to get app root directory in nwjs?

### ISSUE THREAD

**Issue by keyiis** [nwjs/nw.js#5395]
My app run on win10 and has many  sub directory under the app root directory,i want get the absolute path(app root) in any scripts(in sub directory),i try __dirname and cwd,
__dirname get  /
process.cwd() get /
so how absolute path of  app root directory?

**Comment by razzbee** [comment]
where are you calling __dirname from, main folder or sub folder

**Comment by kailniris** [comment]
/package.json

/asd/index.html

./ is the app root in node context
in browser context / is the root eg if you want to include a css or something

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
