### ISSUE TITLE
nwUserAgent not working...

### ISSUE THREAD

**Issue by deviantmoney** [nwjs/nw.js#5397]
nwUserAgent does not work, it will not change the iframes user agent....

**Comment by ghostoy** [comment]
It's a [known issue](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/#known-issues) for 0.13.0 or later.

>> * `nwUserAgent` attribute of `<iframe>` is not supported for now.

@rogerwang

**Comment by wanjochan** [comment]
nwUserAgent is very important for some tools...  is there any work-around?

**Comment by GnorTech** [comment]
Will look to fix this soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
