### ISSUE TITLE
Chrome permission request causes app to close

### ISSUE THREAD

**Issue by bayssmekanique** [nwjs/nw.js#5400]
When I perform a permission request the app stalls for a second and then closes without showing the permission request that normally appears when the app runs in Chrome.

If I open devtools, then the prompt will appear and I'm able to give access and everything works correctly.

The documentation made is sound as if all permissions should already be set to true when the app starts, but because this is a specific USB interface that requires being requested, I'm assuming it doesn't have a pre-existing permission override.  Are there any suggestions?

Here's the request code if it matters:

```
    const DALLAS_VENDOR_ID = 0x04FA;
    const DALLAS_PRODUCT_ID = 0x2490;
    const DEVICE_INFO = {
        'vendorId': DALLAS_VENDOR_ID,
        'productId': DALLAS_PRODUCT_ID,
    };

    const permissionObj = {
        permissions: [
            {
                'usbDevices': [DEVICE_INFO]
            }
        ]
    };

    ow.permission.request = function() {
        var deferred = Q.defer();
        chrome
            .permissions
            .request(permissionObj, function(result) {
                if (result) {
                    deferred.resolve();
                } else {
                    deferred.reject();
                }
            });
        return deferred.promise;
    };
```

I am running on Windows 10.

**Comment by abby03il05** [comment]
Hacktoberfest added 26 October 2017

**Comment by brunojokubauskas** [comment]
Hacktoberfest added 23/10.
