### ISSUE TITLE
Facebook Api Login NodeJS Uncaught Exception

### ISSUE THREAD

**Issue by Atralbus** [nwjs/nw.js#5405]
Hi,

I have an application where I need user to login his/her Facebook account to share something. When facebook login popup window appear my application crashes and message shows up on the screen;

Uncaught node.js Error 

Error: Cannot find module 'TimeSlice'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at window.require (<anonymous>:4:17)
    at https://www.facebook.com/login.php?
...

I checked the facebook login popup's console and those errors were coming from that popup like below;

Uncaught ReferenceError: __d is not defined KLwacKO4h5u.js:34
Uncaught Error: Cannot find module 'TimeSlice' module.js:338
Uncaught ReferenceError: requireLazy is not defined 
Uncaught Error: Cannot find module 'TimeSlice' module.js:338
Uncaught Error: Cannot find module 'BigPipe' module.js:338
Uncaught TypeError: Cannot read property 'beforePageletArrive' of undefined 
...

I searched online and tried to catch all node js exceptions with code below but it didn't help, Exceptions still throwing uncaught.

var process = require('process');
if(process) {
        process.on("uncaughtException", function(e) { console.log(e); });
}

What am I missing here? Could you show me a way to pass this issue?

**Comment by ghostoy** [comment]
Please try to disable nodejs for them and try again.

This might be caused by the js libraries that support modulations of both AMD (like require.js) and CommonJS (like Node.js). Once they detected the environment as CommonJS by testing `require` global variable, they use `require` and `exports` to define their module. However the js file wasn't placed in `node_modules` as required by Node.js, so that caused the error.

**Comment by Atralbus** [comment]
Thanks for your response.

I use Facebook SDK; and this SDK opens login window in "login" method like below;

FB.login(
    function(response) {
        if (response.status === 'connected') {
            ...
        }
    }
);

How can I disable nodejs for that part of application?

**Comment by ghostoy** [comment]
If you don't include URLs of Facebook in `node-remote` of `package.json`, Node APIs are disabled.

**Comment by Atralbus** [comment]
I saw that in package.json it was written as node-remote: "*". I tried to find a way to exclude "facebook" URL's but I think it doesn't support any exclusion pattern. So I removed that line and it worked. Do you think removing "node-remote" property affects the application in any bad way? e.g. does it have anything to do with fullscreen support(F11)?

**Comment by ghostoy** [comment]
Fullscreen should be triggered by NW API, which is enabled with Node APIs. And it's by default enabled for all local files, i.e. `file://` or `chrome-extension://` (new for nw13 or later). So if your fullscreen API is invoked in local files, `node-remote` has nothing to do with it.
If your fullscreen API is invoked in other URLs, such as `http://` or `https://` etc., you have to specify their hosts in `note-remote`. You can provide multiple hosts. See doc for NW version [< 0.13](https://github.com/nwjs/nw.js/wiki/Manifest-format#node-remote) or [0.13.0 +](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote).
