### ISSUE TITLE
What situation may causes “Nw.js No response"?

### ISSUE THREAD

**Issue by tiegeda** [nwjs/nw.js#5408]
I meet the **"Nw.js no response”** dialog Several times，but can't Reproduce it stable.

![image](https://cloud.githubusercontent.com/assets/8806147/19754021/3705038c-9c3c-11e6-979b-bc95fc1415fe.png)

I listen the open event to show the single-instance window when try to start another instance.

``gui.App.on('open', function(pathData) {
        gui.Window.get().show();   
  });``

I meet the **"Nw.js no response”** all on that when try to start a instance again, but not every time will appear this dialog. 
Is that code the culprit？ I can not find any problems with this code.
Or because maybe the web page was got stuck at the time try start again? so there is no response.

Even myself can't reproduce it stable, i though the only way to save this is a reason checklist.
Is there anyone know what reasons may called this no response， so that i can review the code to avoid this.

I'm using    nwjs: LTS v0.14.7 ia32     OS: win7 x64 （why use ia32 on x64 OS, cause we need to Compatible with ia32 too, and ia32 can run on both 32 and 64 bit system ）

**Comment by ghostoy** [comment]
I can't reproduce this issue simply with the code above.

Could you post a full sample app?

**Comment by tiegeda** [comment]
The full project was remote page which server is on a local area network.
And I can‘t reproduce this issue stable too. Only a few times will appear.
The ``on('open')`` code was just one of my speculations maybe cause this problem. I'm not sure.
Is this dialog show by nwjs or Windows？
If nwjs pop this dialog, then under what circumstances it will appear？Such as the js in page was stuck, etc. If the stuck will raise this dialog, a code walkthroughs may be needed.  This may more helpful to me. 
The biggest problem is that it can not reproduce stable.

**Comment by ghostoy** [comment]
Usually it is because of rendering process cannot response inputs or messages, e.g. using lots of sync APIs of Node.

**Comment by tiegeda** [comment]
Thanks for your suggestion, I think I found a place to start
