### ISSUE TITLE
OSX - NW 0.19beta1 crashes on start

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5410]
OSX El Capitan 10.11.6
nw 0.19-sdk-beta1-osx      live build 10-27-2016  nw19-e942a18-15c03a3-4c661d6-55f81f3

Crashes on start - occurs when run after unzipping - no need to try and run app.

![nw19b1crash](https://cloud.githubusercontent.com/assets/11089335/19763930/4dbfef0a-9c38-11e6-9c74-8fce233c4214.jpg)

**Comment by rogerwang** [comment]
Thanks. Should be fixed in http://dl.nwjs.io/live-build/10-27-2016/nw19-7f5878f-79142aa-59c75d1-55f81f3
