### ISSUE TITLE
Serve Multiple Directories

### ISSUE THREAD

**Issue by nueko** [nwjs/nw.js#5413]
Hi, is there a way to serve multiple static directories like what expressjs does on serve-static?
say, we have main: "app/index.html".
Inside the app/index.html, i we have 

``` html
<link rel="stylesheet" href="/bower_components/vendor/lib.css" />
```

we want to serve /bower_components that stands on ../ path.

thanks

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
