### ISSUE TITLE
Webview CORS Disable web security

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#5416]
Hi,

I have been trying to do this for a while with no success. electron has a feature were you can disable web security on a webview with a simple "disablewebsecurity" attribute. Is there a way to do this?

Thanks,
Anesu

**Comment by lin-chao** [comment]
have two way to able cors in webview

use node-remote

http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote

or

auto add Access-Control-Allow-Origin header while response


```
  webview.request  .onHeadersReceived.addListener(
  (details) => {
    let type = details.type
    if (type === 'xmlhttprequest') {
      let responseHeaders = details.responseHeaders || []
      responseHeaders.push({ name: 'Access-Control-Allow-Origin', value: "*" })
      responseHeaders.push({ name: "Access-Control-Allow-Headers", value: "X-Requested-With, Content-Type" })
      return { responseHeaders: responseHeaders }
    }
  }, { urls: ['<all_urls>'] }, ['blocking', 'responseHeaders']
)
```

**Comment by anesuc** [comment]
Thanks for the suggestions, will try them tonight! On the topic of event listeners (sorry kinda slightly off topic, but it's not important enough to start a whole "issue") Is there a way to listen for when audio is playing in a webview and when it is not (i.e stops)?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by zuishizhi** [comment]
@lin-chao i use your way in 0.28 nwjs 。 but show error "Cannot read property 'request' of undefined"
