### ISSUE TITLE
when I execute the command "nw-gyp configure --target=0.18.1", one error occur

### ISSUE THREAD

**Issue by hubbly** [nwjs/nw.js#5417]
when I execute the command "nw-gyp configure --target=0.18.1", one error occur
you can see by click the link below
https://github.com/nwjs/nw.js/issues/4009

**Comment by ghostoy** [comment]
From the error message, your network connection (ECONNRESET) to http://node-webkit.s3.amazonaws.com/v0.18.2/nw-headers-v0.18.2.tar.gz is broken. Please check if you can manually connect to the link above.

If you are in a firewall which blocks you from accessing the URL, you have to find a proxy and set `https_proxy` environment before running nw-gyp.

**Comment by ghostoy** [comment]
Close it since it's not a bug.
