### ISSUE TITLE
WebUSB API issue

### ISSUE THREAD

**Issue by drom** [nwjs/nw.js#5418]
I am trying to use WebUSB API and getting the error.

code: https://github.com/drom/jsdr/blob/master/experiments/WebUSB/src/app.js

My platform:
- nwjs 0.18.3
- Linux 4.8.4-1-default (x64)

Error:

```
drom@linux-xqxs:~/work/github/drom/jsdr/experiments/WebUSB> ./cache/web-usb-demo-v0.1.0-linux-x64/web-usb-demo --enable-experimental-web-platform-features
[21540:21540:1030/152608:ERROR:interface_registry.cc(99)] Failed to locate a binder for interface: device::usb::DeviceManager
[21540:21540:1030/152608:INFO:CONSOLE(0)] "Uncaught (in promise) NotFoundError: USB service unavailable.", source: chrome-extension://bpjaafjkaapkjdomphdmoljjgcdjbagn/index.html (0)
```

**Comment by rogerwang** [comment]
Does Chrome 54 working in the same system?

**Comment by drom** [comment]
Yes, it does works in chromium 54.0.2840.71 with flag: `--enable-experimental-web-platform-features`
on the same machine.

**Comment by rogerwang** [comment]
Upstream disabled this feature for Chrome Apps:  https://bugs.chromium.org/p/chromium/issues/detail?id=610880

We'll enable it because we use a different security model.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
