### ISSUE TITLE
[nw19] Crashed when exiting nw without --enable-node-worker

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#5420]
This crash happens when the app launched a worker or a shared worker. When exit, NW crashed with following error message:

```
nw: ../../third_party/node/src/node.cc:4922: void g_stop_nw_instance(): Assertion `tls_ctx' failed.
```

OS: Ubuntu 14.04 x64
NW: [live-build 0.19.0](https://dl.nwjs.io/live-build/10-28-2016/nw19-2d7ce23-1f6d0c0-59c75d1-bc66ff0/v0.19.0)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
