### ISSUE TITLE
How to use IE-Tab_v7.7.24.1.crx in nw.js 0.15.3?

### ISSUE THREAD

**Issue by chenhaiyun163** [nwjs/nw.js#5421]
Hi everyone.

I'm newer of nwjs.But I meet one isssue.How to use  IE-Tab_v7.7.24.1.crx in nw.js 0.15.3 in windows 64bit?
package.json as blow:
{
  "name": "test",
  "main": "login.html",
  "chromium-args" : "--load-extension=/path/to/nwjs –url='chrome://extensions'",
  "nodejs":true,
  "version": "0.15.4",
  "window": .....
  "webkit":{
	"plugin":true
  }
}
login.html as blow:
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>login</title>
		<script>
			function cet() {
				var gui = require('nw.gui');
				var win = gui.Window.get();
				win.maximize();
				window.location.href= "https://www.baidu.com";
			}
		</script>
	</head>
	<body onload="cet()">
	</body>
</html>

Is there anything wrong?

And  I think  wrong use in blow:

"chromium-args" : "--load-extension=/path/to/nwjs –url='chrome://extensions'",

Could somebody big god help me about the right use .Thanks very much.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
