### ISSUE TITLE
node worker Uncaught Error: No such module: url

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5422]
win 10 64 bit sdk build
NW.js v0.18.4

In web worker if You require the http module the following error will throw

> internal/url.js:11 Uncaught Error: No such module: url

**main.js**
```
var myWorker = new Worker('/worker.js');

myWorker.onerror = function (err) {
    console.log(err);
}
```

**worker.js**

`var http = require('http');`

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
