### ISSUE TITLE
console.time async bug

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5423]
win 10 64 bit sdk build
NW.js v0.18.4

```
http.get('http://localhost/test', (res) => {
    console.time('test');
    res.on('end', () => {
        console.timeEnd('test');
    });
    res.on('data', ()=>{});
});
```
**Outputs:**
test: 9.84e+03ms

one version before it was outputing something like:
test: 14765.0649ms

**Comment by vaporwave98** [comment]
That's not a bug, it's just scientific notation.

**Comment by kailniris** [comment]
How to convert it to be humanly readable?
Why does it changed all the sudden?
Why does it only representet like this in async code?

**Comment by vaporwave98** [comment]
Sometimes a number is just easier to represent that way.
https://en.wikipedia.org/wiki/Scientific_notation
