### ISSUE TITLE
NW crash accidentally 

### ISSUE THREAD

**Issue by thovo** [nwjs/nw.js#5425]
At first, thank nw team a lot for your efforts and your enthusiasm! 

It is fixed in recent version, please let me know to update the current nw! 
* State which version are you using
0.12.2
* State which OS version are you running with
Windows 7 64bit
* Provide a reproducible case if possible
Not sure how to get you reproduce the issue, I am trying to download parallel a list of files from a repository. In the same time, I tried to get the current progress of downloading every files into a progress bar. At first, the Developer Tool closed unexpectedly and when reopened, it didn't connect to current NW, looked like NW hanged right after. After few minutes, it just crashed.
When checked the performance tab in Task Manager, NW used up from 2 to 4Gb of ram in 1 minute and returned right after it crashed.
* Attach the crash dump file if it's a crash: 
[Crashdump](http://goo.gl/Ai23Rl)

Another feature request: I hope the nw team consider to use another more friendly dump report than the `dmp` like `json` . I currently have no idea how to install Google Breakpad in Windows 7 after many failed attempts and google around for a solution, someone else who know the other tool to read the `.dmp`, please advise!

**Comment by rogerwang** [comment]
I'm afraid 0.12.x is not supported any more.

**Comment by thovo** [comment]
Thank for your answer, so I think I will try to figure out myself, may you recommend how to read the `dmp` easily in Windows 7 and consider to update the way of return crash report more friendly?
