### ISSUE TITLE
Nw.js title is set to "Chromium-Browser"

### ISSUE THREAD

**Issue by MartyBum** [nwjs/nw.js#5427]
Nw.js title is set to "Chromium-Browser" when for example using alt-tab

Versions:

![nwjstitle](https://cloud.githubusercontent.com/assets/10170481/19963176/8abb6604-a1bb-11e6-8072-5b2e954255b4.png)

OS: Ubuntu Gnome 16.04.1

**Comment by rogerwang** [comment]
It should be the duplicate of #4693, which we just fixed in git.
