### ISSUE TITLE
Devtools extension load throws error

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5428]
win 10 64 bit sdk build
NW.js v0.18.5

I run my project with a shortcut with a target like this:

> C:\Dev\nwjs\nw.exe --load-extension="C:\Dev\vue-devtools"  "C:\Dev\test"

After the app loads I get the following errror:

> Uncaught TypeError: Cannot read property 'Window' of undefined
>     at get_nw (extensions::nw.Window:754:20)

The devtools says the problem is at this function:
```
function get_nw() {
  appWindowNatives.FixGamePadAPI();
  try_nw(window).nw.Window.get(); //error is thrown at this line
}
```

It was working with NW.js v0.18.4

**If I run the project without the --load-extension the error is not thrown**

**Comment by rogerwang** [comment]
Could you please upload the app and the extension?

**Comment by kailniris** [comment]
The app is as basic as possible.
The extension is the vue-devtools extension I downloaded it from the chrome app store.

[vue_devtools_include_test.zip](https://github.com/nwjs/nw.js/files/573153/vue_devtools_include_test.zip)
