### ISSUE TITLE
Node worker can't include plugin 

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5429]
win 10 64 bit sdk build
NW.js v0.18.5

If I enable node worker in the package.json like this:

> "chromium-args": "--enable-node-worker"

Then I can't include the IDBWrapper plugin like this in a web worker context:
`importScripts('/app/inc/js/idbstore.js');`

The problem is the IDBStore variable will be undefined after the include.

It works fine if I don't use the --enable-node-worker chromium argument.

Other plugins can be included like:
`importScripts('/app/inc/js/lodash.js');`

It was working with NW.js v0.18.4 even with --enable-node-worker enabled.

**repro case:**

**main.js**
`var workerIDBStore = new Worker('/app/worker.js');`

**worker.js**
```
importScripts('/app/inc/js/idbstore.js');
console.log(IDBStore);
```

**Comment by rogerwang** [comment]
So this bug is specific to the IDBWrapper plugin?

**Comment by kailniris** [comment]
no, I tried some other plugins too,
what I found out is func style plugins works
_moment.js
async
lodash_

**these works**
```
moment();
async.series();
_.toArray();
```

**but constructor like plugins does not works**
_BigNumber
IDBWrapper_

```
new BigNumber(1);
new IDBStore({});
```
In these cases BigNumber and IDBStore variables are undefined

**Comment by rogerwang** [comment]
With '--enable-node-worker', 'module' is defined so BigNumber thinks it's in Node: https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js#L2726

I'll remove the 'module' symbol in the worker's global scope.

**Comment by rogerwang** [comment]
We added the 'module' on purpose to make 'require()' work: https://github.com/nwjs/node/blob/nw16/lib/module.js#L426

Need to investigate whether removing this will break anything.

**Comment by kailniris** [comment]
What about the IDBWrapper? It should not work in node

**Comment by rogerwang** [comment]
IDBWrapper tests 'module' too.

**Comment by kailniris** [comment]
I was thinking about it and I have an idea.
Instead of importScripts, require() should be used for plugins/modules which can be included with a module manager. Plugins which do not support module managers still can be included with importScripts.

I tested It out, it works as It should. I used the following code to include BigNumber and IDBWrapper plugins.

```
var BigNumber = require('./bignumber.js');
var IDBStore = require('./idbStore.js');
```

**Full test case:**
[nwjs_node_worker_test.zip](https://github.com/nwjs/nw.js/files/573149/nwjs_node_worker_test.zip)

I think the only thing needs to be done is to explain in the docs how can you include external script in a node-worker.
What do you think @rogerwang?

**Comment by Christywl** [comment]
@rogerwang , does the usage need to be added in the docs as kailniris said?

**Comment by f3l1x** [comment]
This is old thread, but don't forget to update chromium-args.

```json
{
  "chromium-args": "--enable-node-worker"
}
```
