### ISSUE TITLE
gui.Window.open returning null again

### ISSUE THREAD

**Issue by fletchette** [nwjs/nw.js#5431]
Script is called from an index.html that just loads the script.
Run from console with 

> nw ./ 440 760

**index.js**
```
var fs = require('fs');
var gui = require('nw.gui');
var args = gui.App.argv;


var win = gui.Window.open ("idle.html", {
	position: 'center',
	width: 901,
	height: 127,
	show: true
});

win.on("loaded", function() {
	var data = {
		appid: args[i]
	};
	win.emit("data", data);
});
```
**idle.html**
```
<html>
<head>
  <meta charset="utf-8">
  <title>hai</title>
</head>

<body>
	<h1>Idle Sub</h1>
	<script src="idle.js"></script>
</body>
</html>

```
Throws 

> script.js:13 Uncaught TypeError: Cannot read property 'on' of undefined

idle.html opens **correctly**

> Windows 10
> nw.js v0.18.1
> Node v6.8.1
> Chromium 54.0.2840.59
> commit hash: 85cca29-0e33f86-ed8a267-2021126

**Comment by RohitSharma27** [comment]
Please see the documentation. Window.open now returns win object in the callback. It has changed since nw 0.12.x
