### ISSUE TITLE
[osx] [v0.18.5] PNaCl Folder missing in SDK release on OSX

### ISSUE THREAD

**Issue by vihangm** [nwjs/nw.js#5432]
As per discussion on https://groups.google.com/d/topic/nwjs-general/3co5__dgYvE/discussion

The `pnacl` folder is not packaged in the OSX build and so pages with PNaCl fail to load on OSX.
The same pages work on both Windows and Linux without a hitch.

**Repro Steps:**
- Download the latest OSX SDK build of nw.js
- Run `nwjs-sdk-v0.18.2-osx-x64/nwjs.app/Contents/MacOS/nwjs --url=https://gonativeclient.appspot.com/demo`
- Click one of the demos in the left sidebar.

**Expected:**
- The PNaCl demo should work fine on nw.js

**Actual:**
- You get a "Load Failed" on the demo page
- The DevTools show that Chromium couldn't find the PNaCl translator.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
