### ISSUE TITLE
nwjs helper eats up to 180% CPU with WeChat Web Dev IDE running

### ISSUE THREAD

**Issue by snakeninny** [nwjs/nw.js#5433]
Hi,

Today when I was running the latest WeChat Web Dev IDE (ver. 0.10.102800) for the first time on my macOS 10.12.1, the IDE was almost frozen that I couldn't do anything with it at all.

Then in Activity Monitor I saw nwjs helper eating a lot of CPU:

<img width="642" alt="screen shot 2016-11-04 at 16 51 49" src="https://cloud.githubusercontent.com/assets/641869/19999742/0fc4a682-a2af-11e6-9569-41a58e409af7.png">

But the problem disappeared on my other MacBook Pro running macOS 10.12.

Any ideas?

Thanks,

Yinglu

**Comment by rogerwang** [comment]
Please report the issue to WeChat first before it turns out to be a NW issue.
