### ISSUE TITLE
Crash on OsX due to args on package.json

### ISSUE THREAD

**Issue by wallydz** [nwjs/nw.js#5435]
While testing NWJS on OSX , when starting the application with frame = false, on package.json an error is generated on Startup 

This error stops when we disable frame line from package.json

> 2016-11-06 09:31:51.758 nwjs[62016:8980310] NSWindow warning: adding an unknown subview: <WebContentsViewCocoa: 0x7f9acfd30e20>. Break on NSLog to debug.

2016-11-06 09:31:51.759 nwjs[62016:8980310] Call stack:
(
	0   AppKit                              0x00007fffb32278f1 -[NSThemeFrame addSubview:] + 109
	1   nwjs Framework                      0x000000010bfd9bb9 _ZN2v88UnlockerD1Ev + 42308121
	2   nwjs Framework                      0x000000010bfd952d _ZN2v88UnlockerD1Ev + 42306445
	3   nwjs Framework                      0x000000010bfd870a _ZN2v88UnlockerD1Ev + 42302826
	4   nwjs Framework                      0x0000000109bbed16 _ZN2v88UnlockerD1Ev + 4449142
	5   nwjs Framework                      0x0000000109b065d1 _ZN2v88UnlockerD1Ev + 3693617
	6   nwjs Framework                      0x0000000109bdcda1 _ZN2v88UnlockerD1Ev + 4572161
	7   nwjs Framework                      0x0000000109bdbc4f _ZN2v88UnlockerD1Ev + 4567727
	8   nwjs Framework                      0x0000000109bde650 _ZN2v88UnlockerD1Ev + 4578480
	9   nwjs Framework                      0x0000000109bdeb0b _ZN2v88UnlockerD1Ev + 4579691
	10  nwjs Framework                      0x0000000109bfa5b9 _ZN2v88UnlockerD1Ev + 4693017
	11  nwjs Framework                      0x0000000109bfa48e _ZN2v88UnlockerD1Ev + 4692718
	12  nwjs Framework                      0x000000010b8f5eff _ZN2v88UnlockerD1Ev + 35083615
	13  nwjs Framework                      0x0000000108e9af91 ChromeMain + 5468801
	14  nwjs Framework                      0x0000000108c57e11 ChromeMain + 3096833
	15  nwjs Framework                      0x0000000108dba339 ChromeMain + 4548137
	16  nwjs Framework                      0x000000010b200b0b _ZN2v88UnlockerD1Ev + 27787627
	17  nwjs Framework                      0x000000010a15fdab _ZN2v88UnlockerD1Ev + 10351627
	18  nwjs Framework                      0x000000010a18161c _ZN2v88UnlockerD1Ev + 10488956
	19  nwjs Framework                      0x000000010a18195c _ZN2v88UnlockerD1Ev + 10489788
	20  nwjs Framework                      0x000000010a181d03 _ZN2v88UnlockerD1Ev + 10490723
	21  nwjs Framework                      0x000000010a183e8d _ZN2v88UnlockerD1Ev + 10499309
	22  nwjs Framework                      0x000000010a177afa _ZN2v88UnlockerD1Ev + 10449242
	23  nwjs Framework                      0x000000010a183894 _ZN2v88UnlockerD1Ev + 10497780
	24  CoreFoundation                      0x00007fffb569b4c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x00007fffb567c8cc __CFRunLoopDoSources0 + 556
	26  CoreFoundation                      0x00007fffb567bdb6 __CFRunLoopRun + 934
	27  CoreFoundation                      0x00007fffb567b7b4 CFRunLoopRunSpecific + 420
	28  HIToolbox                           0x00007fffb4c0b2ac RunCurrentEventLoopInMode + 240
	29  HIToolbox                           0x00007fffb4c0b0e1 ReceiveNextEventCommon + 432
	30  HIToolbox                           0x00007fffb4c0af16 _BlockUntilNextEventMatchingListInModeWithFilter + 71
	31  AppKit                              0x00007fffb320d6cd _DPSNextEvent + 1093
	32  AppKit                              0x00007fffb3984830 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2730
	33  AppKit                              0x00007fffb320206d -[NSApplication run] + 926
	34  nwjs Framework                      0x000000010a18460e _ZN2v88UnlockerD1Ev + 10501230
	35  nwjs Framework                      0x000000010a183ce4 _ZN2v88UnlockerD1Ev + 10498884
	36  nwjs Framework                      0x000000010a19e821 _ZN2v88UnlockerD1Ev + 10608257
	37  nwjs Framework                      0x0000000109ddb6d5 _ZN2v88UnlockerD1Ev + 6663477
	38  nwjs Framework                      0x0000000108b89f74 ChromeMain + 2253412
	39  nwjs Framework                      0x0000000108b8c822 ChromeMain + 2263826
	40  nwjs Framework                      0x0000000108b85e3c ChromeMain + 2236716
	41  nwjs Framework                      0x0000000109d9dfe7 _ZN2v88UnlockerD1Ev + 6411847
	42  nwjs Framework                      0x0000000109d9d156 _ZN2v88UnlockerD1Ev + 6408118
	43  nwjs Framework                      0x0000000108963d4a ChromeMain + 58
	44  nwjs                                0x0000000105277d6a main + 522
	45  nwjs                                0x0000000105277b54 start + 52
)

[crashdump.zip](https://github.com/nwjs/nw.js/files/573713/crashdump.zip)

**Comment by ghostoy** [comment]
It should only be some messages printed in console. However it should not be crashing your app. I will find a way to suppress the printing.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
