### ISSUE TITLE
nw.Window.open and gui.Window.open - nw is undefined in the new Window since 0.13 Migration

### ISSUE THREAD

**Issue by amazedsaint** [nwjs/nw.js#5438]
Since the 0.13 migration, nw.Window.open and gui.Window.open is always opening a new window with nw object as null - Unable to perform any operation from the new window opened

**Comment by RohitSharma27** [comment]
You must be using window.open the old way (as we used to in 0.12). It has changed in 0.13 and onwards. It's not a bug.

**Comment by amazedsaint** [comment]
What is the old way? Could you please clarify?

**Comment by RohitSharma27** [comment]
Please provide the environment details and code snippet, if possible. It would be easier to help.

**Comment by rogerwang** [comment]
close until more information is available. btw, it could be the duplicate with #4418
