### ISSUE TITLE
How do I distribute my app on linux?

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#5439]
I'm using 0.14.7, and ubuntu 32bit.
I recently updated from 0.12.2, and now the build process seems to be different or doesn't work.
I've added my files to package.nw and then appended to nw via:
cat nw app.nw > app && chmod +x app 
Then in the docs it says "On Linux, you need to create proper .desktop file."
But there aren't any directions specific for this case, If I try running nw, it says "There is no application installe for "shared library" files. Do you want to search for an application to open this file?"
So I'm assuming the .desktop file would fix this? It says you can create it via a text editor, but I have no idea what I should put inside it. Can't there be some more explanation for this? in 0.12.2 the .desktop step wasn't necessary.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
