### ISSUE TITLE
Tray icon flashes slower when window is minimized

### ISSUE THREAD

**Issue by Naiba01** [nwjs/nw.js#5440]
*Version: 0.14.7-sdk
*Operating system: windows 10
*Description:
I am working on the flash of tray icon. Here is my code:
``` javascript
setInterval(() => {
  tray.icon = tray.icon === trayOnlineIcon ? trayEmptyIcon : trayOnlineIcon;
}, 100);
```
When window is not minimized(even it is covered by another application), the tray icon flashes very fast. But when window is mininized, the tray icon flashes slowly down(always to be 1000ms/flash).

Is this still an unsolved problem?
How to keep the same behavior of 100ms per flash, regardless of whether window is minimized or not?

**Comment by Yechenxing** [comment]
> *Version: 0.14.7-sdk
> *Operating system: windows 10
> *Description:
> I am working on the flash of tray icon. Here is my code:
> 
> ```js
> setInterval(() => {
>   tray.icon = tray.icon === trayOnlineIcon ? trayEmptyIcon : trayOnlineIcon;
> }, 100);
> ```
> 
> When window is not minimized(even it is covered by another application), the tray icon flashes very fast. But when window is mininized, the tray icon flashes slowly down(always to be 1000ms/flash).
> 
> Is this still an unsolved problem?
> How to keep the same behavior of 100ms per flash, regardless of whether window is minimized or not?

How did you solve this problem
