### ISSUE TITLE
Slow startup time (2 minutes!) on Windows

### ISSUE THREAD

**Issue by pistacchio** [nwjs/nw.js#5442]
Hi,
Downloading the latest version of NW.js (0.18.5) for Windows, I experience an unacceptable startup time (around two minutes). I've tried both the 32 and the 64bit versions. I'm trying to run the default demo app, untouched.

This happens on a specific computer, an HP Elite x2. The computer is brand new and quite performant.

System specs:
OS: Windows 10 Enterprise (version 1607)
CPU: Intel Core m5-6y54 CPU @ 1.10GHz
RAM: 8 GB

I don't think it's an hardware issue. On a much less performant Windows system it works all right. I've also tried running Electron and it has the same problem. Visual Studio Code (built on Electron) won't start. It seems there's something wrong (possibly software of configuration-wise) with the whole node/javascript environment but I don't know where to look for a solution.

Thanks

**Comment by rogerwang** [comment]
Interesting. Could you please follow https://www.chromium.org/for-testers/enable-logging and upload the log?

**Comment by shamun** [comment]
I have tested on the same environment and no delay found. HP Elite x2 and HP other all in one has hardware issues, i had random HP all in one unit, and it was not the software but hardware causing the slow. 

Please file details and report HP support, there hardware is a piece of garbage now a days. Confuse the hell out.

**Comment by rogerwang** [comment]
close until more info is provided.
