### ISSUE TITLE
Problem with Steam Overlay on Linux

### ISSUE THREAD

**Issue by nmedic89** [nwjs/nw.js#5444]
Hello guys. I'm currently making my own game using HTML5/JS and I chose NW.js. I tried Steam Overlay and it works well on Windows. However, it also works on Linux but it doesn't accept mouse input in overlay (Can't click buttons and move window). Does anyone had similar issue and is there a fix for that? I will give info about specs I'm using:

GPU: nVidia GTX 750 Ti
CPU: Intel i3-6100
RAM: 8GB
Operating Systems: Manjaro 16.10 Fringilla/Ubuntu 16.10 (Both operating systems are 64-bit)

EDIT: I forgot to mention version of NW.js. It's v0.18.5 64-bit

**Comment by rogerwang** [comment]
Does --single-process switch with the latest version work for you?

**Comment by nmedic89** [comment]
I tried both --in-process-gpu and --single-process. None of them work. I also tried 32-bit version of NW.js.

**Comment by rogerwang** [comment]
Are there any steps we can follow to reproduce it here?

**Comment by nmedic89** [comment]
Here's simple way how to reproduce:

1) Open Steam
2) Click Games and then select "Add a Non-Steam Game to My Library..."
3) Steam allows you to choose only *.desktop file. Choose anything and click "Add Selected Programs"
4) Right click on recently added game in Library and click Properties
5) In Target, you type path of your executable. Ex: "/home/user/nwjs/nw"
6) In Start In, you type working directory. Ex: "/home/user/nwjs"
7) Close Properties and add this info into package.json (in my case, package.json is located in root of NW.js to avoid typing additional arguments in Steam):

{
  "name": "SteamTest",
  "main": "http://david.li/vortexspheres/",
  "chromium-args": "--in-process-gpu",
  "window": {
    "toolbar": false,
    "width": 800,
    "height": 600
  }
}

NOTE: http://david.li/vortexspheres/ is not my page and copyright goes to respectful owner.

**Comment by nmedic89** [comment]
I also want to mention that I tried other games on Steam (Starbound for example) and I can confirm that Steam Overlay works well on Linux. Probably a Chromium issue I guess.

**Comment by TatriX** [comment]
Same problem here. It seems that keyboard somehow works when overlay is on, but mouse don't.

**Comment by TatriX** [comment]
With nwjs v19.4 shift+tab just freezes the app, until shift+tab pressed again.

**Comment by kujovic** [comment]
> With nwjs v19.4 shift+tab just freezes the app, until shift+tab pressed again.

@TatriX Happens on Windows too. In my testing (recent NW.js version) I found that pressing just the Tab key freezes the NW.js app (CSS animations, HTML audio). I noticed that CSS hover continues to work though. Pressing Tab again does nothing, but clicking with the mouse anywhere unfreezes the app. But this is probably off topic for this issue, maybe a new one should be opened?

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.24.2.

**Comment by koobazaur** [comment]
Just adding a bump that I am experiencing the same issue with latest NWJS 0.25.4 as well, on Win10 64 bit. Tried all the fixes I could find (chrome args and forcing a canvas refresh) to no avail. 

Looks like it's been posted in other issues for over a year now - any chance this might be looked at more?

**Comment by rogerwang** [comment]
merge issue with #5871
