### ISSUE TITLE
Popup menu does not call click() of MenuItem in some cases

### ISSUE THREAD

**Issue by sonicsnes** [nwjs/nw.js#545]
I've created a very simple test case indicating the issue. This issue took a long time to narrow, and can be quite infuriating for the user experience -- sometimes menus work, sometimes they don't!

Test case: https://github.com/sonicsnes/node-webkit-issue-545

It seems there is some issue with popups that open at the same moment as the window focusing.

**Comment by rogerwang** [comment]
Please try the latest 0.13.0 release. It should be fixed.
