### ISSUE TITLE
language always 'en_US' . why?

### ISSUE THREAD

**Issue by pouu69** [nwjs/nw.js#5456]
- os : osx
- nw : 0.18.5

im using 'nw-builder' for build app

my build app start, 

always language 'en_US'  but developr mode is 'ko_kR'

how can fix it?

**Comment by fanchou** [comment]
+1 There is no better way to solve it

**Comment by pouu69** [comment]
really?
I saw it on another issue.
Move the locale folder.
isnt'it?
if you say yes, where is locale folder?

**Comment by fanchou** [comment]
you can download the SDK version and find language pack

**Comment by pouu69** [comment]
i always used sdk version 
`/nwjs-sdk-v0.18.5-osx-x64/nwjs.app/Contents/Resources**`
and  i find it below 

but not working

**Comment by pouu69** [comment]
i did find for fix it

`nwjs-sdk-v0.18.5-osx-x64/xxx.app/Contents/Info.plist`

open Info.plist file 
and find 

````
    <key>CFBundleDevelopmentRegion</key>
    <string>ko</string> <-- change language prefix
````

right?

**Comment by fanchou** [comment]
yes

**Comment by fanchou** [comment]
if you use nw-builder, you can set options like this

` macPlist: {
          CFBundleDevelopmentRegion: "ko",
          CFBundleDisplayName: "appName",
          CFBundleShortVersionString: "0.0.1",
          CFBundleName: "appName",
          NSHumanReadableCopyright: "appName Copyright©2016, xxx"
        }
`
