### ISSUE TITLE
Can't create Secure Websocket connections (wss) with SNI on OSX

### ISSUE THREAD

**Issue by porsager** [nwjs/nw.js#5461]
If trying to create a secure websocket connection to a host with [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) it will fail with 
`Error in connection establishment: net::ERR_INSECURE_RESPONSE`

Tested with
0.19.0-beta1 on MacOS 10.12.1

To reproduce, try to start a secure websocket connection to a host secured with SNI on OSX
```
new WebSocket('wss://exampleurl.com')
```

I've also tested this on windows where it works fine. (it also works fine in chrome if that's of any help)

**Comment by ghostoy** [comment]
@porsager Could you post a working URL with SNI enabled?

**Comment by porsager** [comment]
Hi.

Sorry for the late response, just found time today to dig a little deeper.

I just found out I hadn't checked with the corresponding chrome version.
It appears to be an issue with chromium 53 and 54 on OSX Sierra only. Chrome 55 / nwjs 0.19 works fine.

Sorry for submitting an issue about this too soon.

**Comment by porsager** [comment]
For anyone ending up here for any reason I just found out that there was missing intermidiaries in the certificates used by the server. Apparently chrome will work fine if it has cached or seen the missing intermidiaries before, but not for websocket connnections.
