### ISSUE TITLE
i want dynamic setup OS

### ISSUE THREAD

**Issue by pouu69** [nwjs/nw.js#5464]
nwjs : 0.18.5

i want dynamic setup for user agent OS

example)
browser : nwjs,
os : windows( or mac or linux)

how to?

**Comment by ghostoy** [comment]
Try use [chrome.webRequest](https://developer.chrome.com/extensions/webRequest#examples).

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
