### ISSUE TITLE
XMLHttpRequest download the file and save the local

### ISSUE THREAD

**Issue by longang520** [nwjs/nw.js#5465]
I use XMLHttpRequest to download files in nwjs
```
var Xhr=new XMLHttpRequest();
Xhr.responseType = "blob";
Xhr.open ("POST", "URL");
xhr.addEventListener("load", function (evt) {
//What am I to do
});
Xhr.send ();
```
How can I save the returned file to local
Or my method is not right, can you tell me an example?
Thanks.

**Comment by ghostoy** [comment]
You can try to request the data as an `ArrayBuffer`, so that you can directly convert it to `Buffer` in Node.js and save it to file.

Please ask further questions in our mailing list https://groups.google.com/forum/#!forum/nwjs-general.

**Comment by longang520** [comment]
thx,but 
`var aaa=Buffer([82, 97, 114, 33, 26, 7, 0, 207, 144, 115, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 7, 232, 116, 32, 146, 71, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 183, 239, 220, 131, 45, 120, 110, 73, 29, 48, 34, 0, 32, 0, 0, 0, 208, 194, 189, 168, 206, 196, 177, 190, 206, 196, 181, 181, 46, 116, 120, 116, 0, 101, 102, 176, 250, 94, 135, 44, 103, 96, 135, 99, 104, 46, 116, 0, 120, 116, 0, 240, 240, 11, 28, 49, 196, 61, 123, 0, 64, 7, 0]);
                        window.fs.writeFile("D:\\111.rar", aaa, function (err) {
                            console.log("OK ");
                        });`

Save the file becomes larger, but I save the txt file when there is no problem, the suspect coding problem.

**Comment by ghostoy** [comment]
I tested with the line you pated and it works. The RAR file can be extracted by 7z successfully. Could you please post a full sample?

**Comment by longang520** [comment]
I know, I doubt my node version. I don't have any problems with the node 6.4 version.
http://nwjs.io/downloads/
https://dl.nwjs.io/v0.14.7/nwjs-sdk-v0.14.7-win-ia32.zip
但是我在0.14.7下有问题.

**Comment by longang520** [comment]
I was in index.html using window.fs = require ('fs');
Follow up using window.fs to save the file

**Comment by ghostoy** [comment]
It worked well for me even with 0.14.7 on macOS and Windows. Please post a full sample app.

**Comment by longang520** [comment]
I have no problem in a single page project, I am looking for the next question, thank you for your help.
`<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
</head>

<body>
    <script type="text/javascript">
        try {
            window.fs = require('fs');
        }
        catch (e) {
            console.log("require", e);
        }
var aaa=Buffer([82, 97, 114, 33, 26, 7, 0, 207, 144, 115, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 7, 232, 116, 32, 146, 71, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 183, 239, 220, 131, 45, 120, 110, 73, 29, 48, 34, 0, 32, 0, 0, 0, 208, 194, 189, 168, 206, 196, 177, 190, 206, 196, 181, 181, 46, 116, 120, 116, 0, 101, 102, 176, 250, 94, 135, 44, 103, 96, 135, 99, 104, 46, 116, 0, 120, 116, 0, 240, 240, 11, 28, 49, 196, 61, 123, 0, 64, 7, 0]); 
window.fs.writeFile("D:\\111.rar", aaa, function (err) { console.log("OK "); });
    </script>
</body>

</html>`

**Comment by longang520** [comment]
http://url.cn/41Vp4LY
This is my example.
Run install NPM
Run run build NPM
Will generate files in the build directory. Copy to nwjs to run
Code segment in src/index.js
Help me to see.

**Comment by ghostoy** [comment]
The packed app includes an implementation of `Buffer` for browser. So fs won't work with it.
It's the issue of the way packing app, not NW.js.

**Comment by longang520** [comment]
How to work

**Comment by ghostoy** [comment]
I mean your app packed a module named `Buffer`, which overwrote the `Buffer` definition in Node.js. I've no idea about how to fix it since I'm not familiar with webpack tool.

**Comment by ghostoy** [comment]
Please ask further questions in our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [IRC channel](https://gitter.im/nwjs/nw.js).
