### ISSUE TITLE
--disable-raf-throttling broken in 0.18.6 on macOS Sierra

### ISSUE THREAD

**Issue by 2xAA** [nwjs/nw.js#5466]
Using 0.18.6-normal on macOS Sierra, RAF throttling is active even when using ```--disable-raf-throttling```
Not sure about Windows or Linux, I currently don't have the means to test these.

Hope we can get this fixed soon - thanks!

**Comment by rogerwang** [comment]
Thanks for reporting.What's the last working version btw?

**Comment by 2xAA** [comment]
I'm not sure of the NWJS version, sorry, but I just tested on a friend's Mac and he's running 10.11.5 (El Capitan) and the same thing happens.

**Comment by rogerwang** [comment]
Will fix it soon. It's a regression introduced in 0.18.0 -- works in 0.17.6.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/11-14-2016/nw18-5fc5ef5-a3607ba-90170c3-6232833/v0.18.7/nwjs-sdk-v0.18.7-osx-x64.zip
