### ISSUE TITLE
multiple .bin files in 0.14.7 LTS won't load.

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#5470]
I have this issue on 0.14.7 LTS : https://github.com/nwjs/nw.js/issues/5168
I can't use the 0.17- i'm stuck with 0.14.7
Can we get an update for LTS to fix that?
Also note.. it loads the first two, but not the third. If I swap 2nd and 3rd, whichever is 2nd loads fine. 3rd doesn't.

**Comment by rogerwang** [comment]
merge with #5168
