### ISSUE TITLE
[docs] adding Getting Started example to use JS as entrance

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#5471]
There is a common misunderstanding that NW must use HTML as the entrance of the app. This is not true. So we need another example in the "Getting Started" page, demonstrating JS entrance and create the main window from there.

**Comment by georgir** [comment]
Is setting main to a js file different from setting node-main?

**Comment by rogerwang** [comment]
@georgir in the past 'node-main' is supposed to be executed along with the 1st opening window. With 'main' pointing to a JS file, the 1st window is supposed to be opened by the JS file.
