### ISSUE TITLE
Build as module for real node.js

### ISSUE THREAD

**Issue by georgir** [nwjs/nw.js#5474]
Is it possible to modify the project to build the webkit part of the project as a node.js module for the standard node.js distribution, instead of building a new executable that has its own custom version of node.js built-in?

The use case is that the entry point of an application can be a regular node.js script which can conditionally decide to load the webkit engine and create the hidden and main window and their domains and contexts and all the nw bootstrap, or continue working as a normal node.js console app instead.
Another plus is that when that whole bootstrap is written as a node.js script it would be easier for people to see it and understand how the packaged node-webkit works and even modify it.

This "flavor" of nw would of course not be usable for packaging apps as single executable, so should not replace the usual build, but seems like a nice option if it is possible.

**Comment by ghostoy** [comment]
NW can now run as pure Node.js when passing a js file in CLI.

You can use js file as "main" in `package.json`, which is loaded in the background page. In this case, NW won't open a new window by default. You can open it after some initialization job has done.

**Comment by georgir** [comment]
A js file loaded in the background window is not quite like running a pure node.js script. The default exception handler does not cause program exit, console.log is non-functional, and NW-specific variables are also loaded in the script's context without the script explicitly requiring them, which is not as clean as it can be.
And even if nw can behave completely like node.js, that does not really answer my question. Can webkit be a standard module for node.js and share its js engine without requiring custom-built node.js?

**Comment by rogerwang** [comment]
In the very first beginning of node-webkit project, webkit is built as a module for upstream node. As the project evolves, we modify Node as we need and integrate it with Chromium to serve various requirements. 

Please move the discussion in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general.

If you hit any issue on exception handling, console logging and specific variables in JS entrance scenario, please submit additional issues and we'd like to fix them in the current architecture.
