### ISSUE TITLE
NW app hangs on Mac OS X(10.11.6)

### ISSUE THREAD

**Issue by PriteshGajjar008** [nwjs/nw.js#5479]
Our application frequently hangs and UI becomes unresponsive and only one option remains is "Force Quit".

We have added following chromium flags in manifest:
  "chromium-args": "--enable-logging --v=1 --crash-on-hang-threads=UI:3:18,IO:3:18,DB:3:18,FILE:3:18,CACHE:3:18",

crash dump file is not always generated.

I am attaching crash dump here and can someone help to give more details.
[Dumps.zip](https://github.com/nwjs/nw.js/files/591624/Dumps.zip)

Any help here would be great.

**Comment by rogerwang** [comment]
What's the version are you using?

**Comment by PriteshGajjar008** [comment]
0.14.7 (LTS)

**Comment by PriteshGajjar008** [comment]
We also tried different versions but similar issue is reproduced. Let us know if there is anything extra logging we should enabled, OR given dumps can give you an idea?

**Comment by Christywl** [comment]
@PriteshGajjar008 , is there a sample to reproduce your issue?

**Comment by Christywl** [comment]
close until there is more information
