### ISSUE TITLE
Process.uptime()

### ISSUE THREAD

**Issue by jssuttles** [nwjs/nw.js#5481]
Versions
<img width="635" alt="screen shot 2016-11-15 at 1 41 30 pm" src="https://cloud.githubusercontent.com/assets/8527741/20318813/d82a9a86-ab39-11e6-9011-e9b485b05862.png">

OS
<img width="196" alt="screen shot 2016-11-15 at 1 45 04 pm" src="https://cloud.githubusercontent.com/assets/8527741/20318815/d82fb26e-ab39-11e6-91fd-708fa50300d9.png">

Process.uptime()
<img width="246" alt="screen shot 2016-11-15 at 1 45 27 pm" src="https://cloud.githubusercontent.com/assets/8527741/20318814/d82f6c96-ab39-11e6-9bec-e53afdf6b5b0.png">

As you can see the process uptime is greater than the os uptime.
To figure out the real process uptime, I've had to store the start time and compare against the current time.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
