### ISSUE TITLE
SDK build reload app breaks the "global" object with --load-extension

### ISSUE THREAD

**Issue by kailniris** [nwjs/nw.js#5483]
win 10 64 bit sdk build
NW.js v0.18.7

I run my project with a shortcut with a target like this:

C:\Dev\nwjs\nw.exe --load-extension="C:\Dev\vue-devtools" "C:\Dev\test"

After I reload the app with the right mouse button on main window context menu "Reload app" button most of the properties in the "global" object will be null or undefined.
For an example `global.setImmediate` will be undefined.

This only happens if I load a devtools extension.

Repro case includes the extension and a basic app.
[global_var_test.zip](https://github.com/nwjs/nw.js/files/593947/global_var_test.zip)

Step by step reproduction:

1. Run the app in nw.js with `--load-extension`
2. Open the devtools context menu (right mouse button on the window)
3. Click on `Reload app` or `Simulate browser restart` context menu element
4. After app reload open the devtools
5. In the console check out the global object, e.g.: `global.setImmediate`

**Comment by Christywl** [comment]
Reproduced with the reporter's test case on Linux and Windows with nwjs-sdk-0.21.0.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
