### ISSUE TITLE
i can not run app after package  to file.exe when i to use  resources has XXX.png

### ISSUE THREAD

**Issue by 405go** [nwjs/nw.js#5485]
version:nwjs-sdk-v0.17.4-win-x64;
OS version:win7 64;
issues:i can not run app after package  to file.exe when i to use  resources has XXX.png,if i delete image dir ,i can run it;

**Comment by ghostoy** [comment]
Could you please post a full sample app?

**Comment by 405go** [comment]
@ghostoy  i have solved if because i create image name use chinese

**Comment by ghostoy** [comment]
Do you mean that your app will start when you changed Chinese file name into English? NW.js should be working with Chinese file names. I suggest you post your sample app, so that we could find out the root cause.

**Comment by 405go** [comment]
@ghostoy 我把图片的文件名改成英文之后就能运行了。

**Comment by ghostoy** [comment]
I tested a simple app with Chinese image file, and it works. I hope you can attach your app here so that we can reproduce this issue.

**Comment by 405go** [comment]
@ghostoy 开发工程中是可以运行的，不能运行时因为我已经把他打包成了exe文件，才不能运行。

**Comment by rogerwang** [comment]
@405go please do NOT use languages other than English so all users can read.

**Comment by 405go** [comment]
@rogerwang ok,i mean i can not run because i package it to app.exe and use chinese filename ,if i change filename to English and package it to app.exe ,i can run it success.

**Comment by ghostoy** [comment]
I tried the packaged app with Chinese filename and it still works. Please post your zipped app so that we can find out why.

**Comment by 405go** [comment]
@ghostoy 
i can not send email to you{

您的邮件被收件人（leehom2001@gmail.com）所在服务商判为垃圾邮件，对方不予接收。 
host gmail-smtp-in.l.google.com[64.233.188.27] said: 552 5.7.0 message content and attachment content guidelines. n28si2164987pgd.281 - gsmtp (in reply to end of DATA command)

}

**Comment by kailniris** [comment]
You can upload files directly here

**Comment by 405go** [comment]
i can not upload files here because when i upload demo.zip it says " We don’t support that file type."

**Comment by ghostoy** [comment]
You can share with Dropbox or other cloud storage services.

**Comment by 405go** [comment]
http://pan.baidu.com/s/1o8wFC6Y @ghostoy

**Comment by ghostoy** [comment]
I tried your app and it still works.

**Comment by 405go** [comment]
ok,Maybe my wrong,you can close it
