### ISSUE TITLE
tray menu click handle does not work

### ISSUE THREAD

**Issue by lili21** [nwjs/nw.js#5486]
```
// running in node context, I stored the nw at inject_js_start
var nw = require('./nw').get()
var win = nw.Window.get()
var tray = new nw.Tray({ title: 'tray' })
var menu = new nw.Menu()
var item = new nw.MenuItem({
  label: 'quit',
  click: function () {
    nw.App.quit()
  }
})
menu.append(item)
tray.menu = menu
tray.on('click', function () {
  win.show()
})

win.on('close', function () {
  this.hide()  
})

```

sometime it works, but most of the time, It does not. the click handle do not be executed. and no error, no info. nothing.

well, It yelled at me about that 'nw.Tray is not a conscturor' , few times. Don't know why.

macOs Sierra
nw.js v0.14.7

**Comment by ghostoy** [comment]
There is an issue with menus of tray in 0.14.7. Please use v0.14.6 or our stable version, like 0.18.6.

**Comment by lili21** [comment]
switched to v0.14.6, same problem. 
I need to support Windows XP. so

**Comment by ghostoy** [comment]
It works for me with 0.14.6 on Mac OS El Capitan and Sierra. But I didn't understand how you "store nw with `inject_js_start`". Could you post the code in `./nw.js`?

**Comment by RohitSharma27** [comment]
It works for me in 0.14.7 as well. What issue are you talking about @ghostoy?

**Comment by lili21** [comment]
inject_js_start.js
```
require('./src/nw.js').set(nw)
...
```

nw.js
```
var _nw

module.exports = {
  set: function (nw) {
    _nw = nw
  },
  get: function () {
    return _nw
  }
}
```

**Comment by lili21** [comment]
always works ? Huh, weird.

**Comment by ghostoy** [comment]
Do you mean tray.click or menu.click?

**Comment by lili21** [comment]
menu.click.

**Comment by ghostoy** [comment]
Menu click always work for me. tray.click does not. I will check it later.

**Comment by lili21** [comment]
do you run that code in node context ?

**Comment by lili21** [comment]
maybe this's the answer ?
<img width="816" alt="2016-11-17 6 37 44" src="https://cloud.githubusercontent.com/assets/4456380/20385908/51340a14-acf4-11e6-8e19-8c8c7da2d76c.png">

**Comment by lili21** [comment]
Is `bg-script` running in browser context ? cause I can get `nw` as global variable. But I cannot get current window by `nw.Window.get()`.

**Comment by ghostoy** [comment]
Scripts in `bg-script` is running in Node context, which is also the background page as in Chrome App. So you can't get current window for background page.

Navigation will make your callbacks in previous page GCed. If you want your callback work, put your script in background page instead.

**Comment by RohitSharma27** [comment]
Bg-script makes it run in the background page's context/node context. It's got no GUI, no browser context and hence you can't get the window.

**Comment by lili21** [comment]
thanks. Shouldn't skip the warning stuff.

**Comment by lili21** [comment]
> Scripts in bg-script is running in Node context,
But I can access `nw` as global variable, Is the `nw` same as `nw` in javascript context ?

**Comment by ghostoy** [comment]
Yes. It's the same `nw` created in background page. But the `nw.Window` APIs will get the actual window you are running in.

**Comment by zuozonglin** [comment]
bind funciton to open,such as : gui.App.on('open', function (args) {})           .
Then use nw.Shell.openItem(nw.process.execPath) to show the window
