### ISSUE TITLE
Support for angular batarang devtools extension?

### ISSUE THREAD

**Issue by angularchobo** [nwjs/nw.js#5488]
I see Google Chrome devtools extensions are supposed to be supported as referenced here https://github.com/nwjs/nw.js/issues/612

However this does not work as of NWJS 0.16.0 with Angular Batarang 0.10.6 or 0.10.7. I also tried adding the permissions given in the aforementioned thread to manifest.json, to no effect. I get no error when loading nw.exe with -load-extension=/path/etc/

The extension obviously runs fine with Chrome.

https://github.com/angular/batarang/releases

EDIT:

I've also tried with a fresh install of NWJS 0.18.7 SDK and Batarang 0.10.7, same thing - no errors, but the extension is not loaded.

**Comment by kailniris** [comment]
an extension load parameter ina  shortcut should look like this:
`C:\Dev\nwjs\nw.exe --load-extension="C:\Dev\vue-devtools" C:\Dev\myproject\`

What you may missing here is use `--load-extension=/path/etc/` not `-load-extension=/path/etc/`

**Comment by angularchobo** [comment]
If someone happens to encounter this issue in the future, do not get the Batarang extension from the link I posted, but rather install it to Chrome directly, and copy the folder from the Chrome local Application Data folder into your NWJS project, that worked for me.
