### ISSUE TITLE
how to run nw.js on remote web

### ISSUE THREAD

**Issue by badnewfish** [nwjs/nw.js#5490]
thank u,
my nw.js is v0.18.7 ,i can't config "node-remote" in "package.json" file,i must run node.js on remote iis webfile.
what can i do ???
thanks

**Comment by ghostoy** [comment]
Please read document for `node-remote` first on our official documentation site http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote.

If you have further questions, please ask in our mailing list https://groups.google.com/forum/#!forum/nwjs-general
