### ISSUE TITLE
video wrong ratio black bar

### ISSUE THREAD

**Issue by kkm** [nwjs/nw.js#5493]
I set camera width for 320 and 180 in height.
![image](https://cloud.githubusercontent.com/assets/134290/20478417/4337ea00-afda-11e6-88da-27d393aa9193.png)

But in Chrome looks fine.
![image](https://cloud.githubusercontent.com/assets/134290/20478468/82ec3462-afda-11e6-9637-88f06a01786a.png)

**Comment by ghostoy** [comment]
Please post your sample app to reproduce the issue.

**Comment by kkm** [comment]
```
var localVideo = document.getElementById('localVideo');
var width = 320;
var height = 180; //I know that is special ratio. I have Logitech HD Pro Cam C920.
var constraints = {
  audio : false,
  video : {
    "width" : {
      "min" : width,
      "max" : width
    },
    "height" : {
      "min" : height,
      "max" : height
    },
    "frameRate" : {
      "min" : "10",
      "max" : "25"
    }
  }
};
navigator.mediaDevices.getUserMedia(constraints).then(function(stream) {
  localVideo.srcObject = stream;
});
```


HTML
` <video autoplay id="localVideo"></video>`

I did test with Win10 and SDK 19.0 Beta.

**Comment by ghostoy** [comment]
I can't reproduce it on my Windows 8.1 with builtin camera. But I don't have Win10 with camera to test with.

Could you also test if it works on Chrome 55 and nw 0.18.7?

**Comment by kkm** [comment]
I found bug if I use with "chromium-args":  "--disable-gpu" in package.json
then I get always black bar with 16:9 Ratio from Camera.

**Comment by ghostoy** [comment]
I still can't reproduce it with `--disable-gpu`. Did you try with Chrome with `--disable-gpu`?

**Comment by ghostoy** [comment]
@kkm Does it break Chrome with `--disable-gpu` for you?

**Comment by kkm** [comment]
hi,

yes I use without --disable-gpu then I can set 320x180 on webcam for correct without blackbar.

**Comment by ghostoy** [comment]
That's not I'm asking for. I need to confirm whether the bug happens for Chrome with `--disable-gpu`.

**Comment by kkm** [comment]
![crwp](https://cloud.githubusercontent.com/assets/134290/20864699/e23afb72-b9fa-11e6-9688-3df6ea74dbc9.png)
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.14 Safari/537.36"

yeah same as in nwjs. I believe chrome or nvidia should be fix.

**Comment by ghostoy** [comment]
Yeah, it looks like an issue with upstream Chrome. Would you please submit a issue to https://crbug.com ? So we can track the issue.

**Comment by kkm** [comment]
I will test soon
