### ISSUE TITLE
Get/Set clipboard value doesn't work

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#5494]
NWJS: 0.18.7
Darwin Olegs-MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Wed Nov  9 19:52:37 PST 2016; root:xnu-3789.31.1~4/RELEASE_X86_64 x86_64

**Comment by oaleynik** [comment]
Also, Command+C, Command+V, Command+P have stopped working too.

**Comment by oaleynik** [comment]
`document.execCommand('copy')` doesn't work as well :\

**Comment by ghostoy** [comment]
It works for me.

Did you create your own menu without builtins? If so, try use `menu.createMacBuiltin` before adding your own menus.

**Comment by oaleynik** [comment]
@ghostoy `menu.createMacBuiltin` is exactly what I do. Nothing else.

**Comment by ghostoy** [comment]
Could you post a sample app?

**Comment by oaleynik** [comment]
@ghostoy this is super strange, but now regardless of what I try - everything works as expected. Closing this for now. Sorry for the false alarm.
