### ISSUE TITLE
Call SetWindowsHookEx to add a keyboard hook in a native node module not working

### ISSUE THREAD

**Issue by Shawyeok** [nwjs/nw.js#5496]
I want my windows application running in a fullscreen mode that cannot switch apps use some shortcuts like `alt+tab ` `win+D`.
I use [SetWindowsHookEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644990(v=vs.85).aspx) to add a keyboard hook, then I convert it to a nodejs addon use `node-gyp`.
```c++
// winhook/winhook.cc
#include "node.h"
#include "v8.h"
#include "windows.h"
#include "winbase.h"
#include "winuser.h"

HHOOK g_hKeyboardHook;
BOOL g_bFullscreen = true;

LRESULT CALLBACK LowLevelKeyboardProc( int nCode, WPARAM wParam, LPARAM lParam ) {
  if (nCode < 0 || nCode != HC_ACTION )  // do not process message
    return CallNextHookEx( g_hKeyboardHook, nCode, wParam, lParam);

  bool bEatKeystroke = false;
  KBDLLHOOKSTRUCT* p = (KBDLLHOOKSTRUCT*)lParam;
  switch (wParam)
  {
      case WM_KEYDOWN:
      case WM_KEYUP:
      {
          // Only block win keys in this case
          bEatKeystroke = (g_bFullscreen && ((p->vkCode == VK_LWIN) || (p->vkCode == VK_RWIN)));
          break;
      }
  }

  if( bEatKeystroke )
      return 1;
  else
      return CallNextHookEx( g_hKeyboardHook, nCode, wParam, lParam );
}

void addHook(const v8::FunctionCallbackInfo<v8::Value>& args) {
  // Initialization
  g_hKeyboardHook = SetWindowsHookEx( WH_KEYBOARD_LL,  LowLevelKeyboardProc, GetModuleHandle(NULL), 0 );
}

void clearHook(const v8::FunctionCallbackInfo<v8::Value>& args) {
  // Cleanup before shutdown
  UnhookWindowsHookEx( g_hKeyboardHook );
}

void init(v8::Local<v8::Object> exports) {
  NODE_SET_METHOD(exports, "addHook", addHook);
  NODE_SET_METHOD(exports, "clearHook", clearHook);
}

NODE_MODULE(binding, init);
```
```javascript
// winhook/binding.gyp
{
  'targets': [
    {
      'target_name': 'winhook',
      'defines': [ 'V8_DEPRECATION_WARNINGS=1' ],
      'sources': [ 'winhook.cc' ]
    }
  ]
}
```
nw-gyp build:
```
nw-gyp configure build --target=0.13.0 --arch=ia32 --msvs_version=2015
```
Here is my `package.json` and entrypoint file `main.js`:
```javascript
// package.json
{
  "name": "nwjs-demo",
  "version": "1.0.0",
  "main": "main.js",
  "dependencies": {
  }
}

// main.js
'use strict'

var winhook = require('./winhook/build/Release/winhook');

var mainWindow = null;
// Create a new window and get it
nw.Window.open('index.html', {}, function(win) {
  mainWindow = win;

  mainWindow.hide();
  mainWindow.on('close', function() {
    this.hide();
    console.log("We're closing...");
    winhook.clearHook();
    console.log("Clean the windows hook before exit.");
    this.close(true);
  });
});

var tray = new nw.Tray({ title: 'Tray', icon: 'tray.png' });

var menu = new nw.Menu();
tray.menu = menu;
menu.append(new nw.MenuItem({
  type: 'normal',
  label: 'Open',
  click: function() {
    mainWindow.show();
    mainWindow.setAlwaysOnTop(true);
    mainWindow.enterFullscreen();
    mainWindow.window.location.href = 'https://www.google.com/';
    mainWindow.focus();
    winhook.addHook();
  }
}));
menu.append(new nw.MenuItem({
  type: 'separator'
}));
menu.append(new nw.MenuItem({
  type: 'normal',
  label: 'Exit',
  click: function() {
    tray.remove();
    tray = null;

    mainWindow.close();
  }
}));
```
When I click `Open` menu on the tray, my keyboard will not response for a while(about 30 sec), after recovered my keyboard back to normal include `win` keys just like the hook doesn't working.

My environments as below:
```
nw.js: nwjs-sdk-v0.14.7-win-ia32
operation system: windows 10 Enterprise 64-bit
npm version:
{ 'nwjs-demo': '1.0.0',
  npm: '4.0.2',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.9.1',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

In the process explorer, I found my node.js code include `winhook.addHook()` running in a child process.
![image](https://cloud.githubusercontent.com/assets/5058708/20514293/0cbe3032-b0c6-11e6-8f39-c5349ece615b.png)

I'm not sure call `SetWindowsHookEx` in a child process cause this problem or not, I'm confused, what should I do? Ask for help, thanks!

**Comment by rogerwang** [comment]
The window is created by the browser process (12448 in your screenshot), not the renderer process. That should be the reason.

**Comment by Shawyeok** [comment]
@rogerwang Yes, I think so.

But browser process and node process are separately in NW.js, I also try `mixed context`, but still.
If I download the NW.js source code and add `SetWindowsHookEx` as a feature, does that work? Or are there other ways to do this work?

**Comment by rogerwang** [comment]
There is no such thing as "Node process" in NW. Please open https://www.chromium.org/developers/design-documents/multi-process-architecture to see what's 'browser process' and what's 'renderer process'.

**Comment by Shawyeok** [comment]
@rogerwang Thank you for telling this, I appreciate that.

Since my network condition, download the whole NW.js build env is too hard, so I still want to try **call SetWindowsHookEx in a child process, but the windows is create by main process**, could you provide any suggestions?

**Comment by rogerwang** [comment]
I'm not familar with this API, or any other API could do the same.
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by guxing** [comment]
hi, are you fix that?

**Comment by guxing** [comment]
> @rogerwang Thank you for telling this, I appreciate that.
> 
> Since my network condition, download the whole NW.js build env is too hard, so I still want to try **call SetWindowsHookEx in a child process, but the window is create by parent process**, could you provide any suggestions?

hi, did you fixed that?

**Comment by Shawyeok** [comment]
@guxing Finally, we spawn a child process (write in vc++) to do `SetWindowsHookEx` thing.

**Comment by guxing** [comment]
> @guxing Finally, we spawn a child process (write in vc++) to do `SetWindowsHookEx` thing.

@Shawyeok I tried like this:
`require('child_process').fork('winHook.js')`

my winHook.js as blew:
`require('./winhook/build/Release/winhook').hide()`

but not worked?  Is it convenient to provide same code?
