### ISSUE TITLE
Remove the restriction parent HTTPS trying to open HTTP or parent HTTP trying to open HTTPS

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5507]
Trillions of reason that HTTPS parent url should not block opening HTTP (via iframe or so), same way HTTP parent should also be not restricted to open HTTPS (via iframe or so).

Therefore, can we please make sure in all our node-webkit we respect that. (Google chrome team's are retired they do not listen nor care)

Can we have the confirmation if NodeWebkit will respect this or not? Because i have my own Chromium version where Google chrome/Chromium/NodeWebkit fails i do it in my own versions. I need to know if we can have that feature in our NodeWebKit as permanent please.

Please confirm.

**Comment by rogerwang** [comment]
Will like to support this in the NW security model. The DOM security model will stay unchanged.

**Comment by shamun** [comment]
Excellent. Thanks Guru!!

**Comment by rogerwang** [comment]
reopen to keep it in track.

**Comment by rogerwang** [comment]
merge this with #4213
