### ISSUE TITLE
webview tag issue

### ISSUE THREAD

**Issue by vicwang163** [nwjs/nw.js#5509]
when I am using webview tag like below
```
    <div id="webview" style="width:300px; height:480px" >
      <webview id="foo" src="http://m.baidu.com/" partition="persist:googlepluswidgets"</webview>
    </div>
```

1. issue one：
I should add a wraper for webview, and once webview is loaded,the render has issue that couldn't show the whole page,I have to manually modify the wrapper's width or height to trigger the re-render mechanism,so that the webview tag could show the whole page.

2.issue two:
I use another webview element to display the devtools for the above webview,I use this function:webview.showDevTools(show, [container]),if another webview doesn't have src attribute,when call 'showDevTools',it still still open a new window.

**Comment by vicwang163** [comment]
I added some screenshots in the [https://groups.google.com/forum/#!topic/nwjs-general/o_Tb6zdqPIM](https://groups.google.com/forum/#!topic/nwjs-general/o_Tb6zdqPIM)

**Comment by ghostoy** [comment]
1. Use `display:block;` with `<webview>` tag and try `autosize` attribute https://developer.chrome.com/apps/tags/webview#autosize.
2. I don't quite understand your problem.

**Comment by ghostoy** [comment]
Close this issue since not receiving feedbacks for 3 weeks. Please reopen it if you still experience this issue.
