### ISSUE TITLE
macOS Sierra 10.12.1 packaging/unpacking

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#5511]
I have the credits.html, the .app file and the package.nw file. I can start the app with no issue. When I zip these 3 together and then unzip them, the app starts but now shows the default nw.js test screen and no longer what is in package.nw. Any ideas what this could be caused by (It did not happen in older versions of the OS)?

I then switched out package.nw, this did not change the issue. Swapping .app resulted in the app working again, so something must be messing up the .app archive, but I have no idea what to do.

my app is a game and it no longer works for me (worked fine before my system update):
http://falkenbrew.com/devader/devader_osx64.zip

**Comment by ghostoy** [comment]
I tried to extract the downloaded zip file and it works for me. 
BTW the recommended package way is to put all files in your app in `Contents/Resources/app.nw`. If you zipped `app.nw`, it will slow down the start up since it will extract all the files first.

**Comment by marcgfx** [comment]
are you also using macOS sierra 10.12.1? It was working before the update, so I am assuming its related to some change in the system. Thanks for the info about packaging, I will check this out.

**Comment by ghostoy** [comment]
I'm on 10.12.2 beta. Currently I don't have a Mac with 10.12.1.

**Comment by ghostoy** [comment]
@marcgfx Any update?

**Comment by ghostoy** [comment]
Close it since no feedbacks for 3 weeks. Please reopen it if you still experience this issue.
