### ISSUE TITLE
Bug: App crashes when poping up a menu

### ISSUE THREAD

**Issue by zaygraveyard** [nwjs/nw.js#5513]
### Using
* nw v0.18.8 (sdk)
* macOS 10.12.1 (16B2555)

### How to reproduce
"crash.html"
```html
<html>
  <head>
    <script type="text/javascript">require('./crash.js')</script>
  </head>
  <body>
  </body>
</html>
```
"crash.js"
```js
var menu = new nw.Menu();
menu.append(new nw.MenuItem({
    label: 'Crash',
}));
menu.popup(0, 0);
```

Run an app having `"main": "crash.html"` in the "package.json"

### What's expected

The app lunches without crashing and a menu is open in the top left corner of the window.
See the workaround below. 

### What actually happens

The app crashs.

### Workaround

"nocrash.html"
```html
<html>
  <head>
    <script type="text/javascript">
      global.newMenu = function() {
        return new nw.Menu();
      };
      require('./nocrash.js');
    </script>
  </head>
  <body>
  </body>
</html>
```
"nocrash.js"
```js
var menu = global.newMenu();
menu.append(new nw.MenuItem({
    label: 'No Crash',
}));
menu.popup(0, 0);
```

### Crash Dump

I will provide one if needed.

**Comment by ghostoy** [comment]
The issue is caused by calling in background page. However background page does not have a  web page. So you will see the menu popup in the bottom left of the screen. I will fix the crash, but it's not recommended to call it in background page.

**Comment by zaygraveyard** [comment]
@ghostoy Thank you
Is there somewhere I read more about background pages?

**Comment by ghostoy** [comment]
The background page is a default HTML loaded on start. See [Chrome App Background Pages](https://developer.chrome.com/extensions/background_pages).

And "In NW.js, Node.js modules can be loaded in the context running in background page, which is the default behavior." See [Javascript Context in NW.js](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/).
