### ISSUE TITLE
High DPI scaling doesn't seem to work correctly on Windows 10

### ISSUE THREAD

**Issue by dslater38** [nwjs/nw.js#5518]
nw.js versions used: 0.18.3, 0.18.7, 0.18.8
OS version: Microsoft Windows 10 Professional 10.0.14393 N/A Build 14393
Display resolution: 3840x2160 with the display scaling setting on Displa ySettings page set to:
"Change the size of text, apps, and other items: 250% (Recommended)"

Create the following index.html:
<!doctype html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />
<title>Test</title>
<body>
<img style='width:640px;height:480px' />
</body>
</html>

and package.json
{
    "name":"test",
    "version":"0.0.0.1",
    "main":"index.html"
}

run nw . and note that the scroll bars are far too wide. ( see the attached image of what the nw window looks like on my machine).

I've also attached the output from systeminfo.
[SystemInfo.txt](https://github.com/nwjs/nw.js/files/625762/SystemInfo.txt)
![untitled](https://cloud.githubusercontent.com/assets/6516534/20812820/0f7dc086-b7e1-11e6-9b1a-79a50793d04a.jpg)

**Comment by ghostoy** [comment]
merged to #5401
