### ISSUE TITLE
CSS background url with relative paths (../../ etc)

### ISSUE THREAD

**Issue by FPChris** [nwjs/nw.js#5519]
Example tag src playbtn is overlayed fine. The style bg image is failing to resolve. 

`<img id="smpbCCBMRv2-022" src="playbtn.png" width="160" height="120" border="0" class="pres-image" style="background-image: url(&quot;../../../CCBMRv2/Presentations/CCBMRv2-022/CCBMRv2-022Th/CCBMRv2-022-Th001.jpg&quot;);">`

**Comment by ghostoy** [comment]
The relative path is resolved based on current URL **relative to your apps root directory.** It's not possible to resolve a path out of your app's directory.

**Comment by FPChris** [comment]
So only down from the app main html?

**Comment by FPChris** [comment]
Thx btw

**Comment by ghostoy** [comment]
Not from main HTML, but from `package.json`. So you can restructure your app to put `package.json` to an upper level of directory and re-set `main`.

**Comment by FPChris** [comment]
Ok thx
