### ISSUE TITLE
请问，有中文文档吗？

### ISSUE THREAD

**Issue by githublaohu** [nwjs/nw.js#5520]
学历不高，英语不好，
看英文，看不懂。
请问有中文文档吗？

**Comment by survivol** [comment]
国内搜一下肯定不少吧，感觉主要像是桌面应用的，类似于flex的air，或者wpf。移动端肯定也能做。
但感觉webkit本身就很大。

**Comment by githublaohu** [comment]
啊，没找到啊。

**Comment by survivol** [comment]
你用的ie6吧。。。

**Comment by githublaohu** [comment]
..   我只想找  node  webkit的中文文档。
你老这么说道ie6去了。

**Comment by windwhinny** [comment]
不能指望每个项目都有中文文档。
看不懂就硬着头皮查字典看，看多了就懂了，大家都是这么过来的。

**Comment by githublaohu** [comment]
好大也是，国人项目吧。
太偏心了吧。

**Comment by rogerwang** [comment]
@githublaohu For now, we are able to cover documentation for only one language with the resources we've got, and that's English. It has nothing to do with bias.

And please use English in issues so all users can read it.

**Comment by ghostoy** [comment]
There were personal translation projects, such as https://github.com/lxp135/NW.jsCnDocs. But they are not from official.

**Comment by paoyideyun** [comment]
我一开始都是百度nw的情况，发现奥，没啥资料，而且全是重复的，简直了。还是觉得github好点，资料也全，就是带着翻译软件看的。其实英文的，看多了，也就锻炼了，蛮好。
