### ISSUE TITLE
[win-ia32] [pnacl] nw hangs when loading a page with a PNaCl executable

### ISSUE THREAD

**Issue by seshness** [nwjs/nw.js#5524]
**Steps to repro:**

Download and extract `nwjs-sdk-v0.19.0-win-ia32.zip`.
Launch `nwjs-sdk-v0.19.0-win-ia32\nw.exe --url=https://gonativeclient.appspot.com/demo/bullet/` from Command Prompt.

**Expected:**

* PNaCl demo launches successfully.

**Actual:**

* App hangs unresponsively at the loading bar. Right clicking does not produce a context menu (has no effect).

**Versions:**

nwjs v0.19.0 win ia32: http://dl.nwjs.io/v0.19.0/nwjs-sdk-v0.19.0-win-ia32.zip
Windows 7 Professional, 64-bit Operating System

**Additional Information:**

Copying `nacl_irt_x86_64.nexe` and `nacl64.exe` from `C:\Program Files (x86)\Google\Chrome\Application\55.0.2883.75`, an existing installed 32-bit Chrome (version `55.0.2883.75 (Official Build) m (32-bit)`), to the `nwjs-sdk-v0.19.0-win-ia32` folder fixes the issue.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by seshness** [comment]
Thanks for the speedy fix, @rogerwang!
