### ISSUE TITLE
Install fails on ubuntu 16.04 lts

### ISSUE THREAD

**Issue by mythril** [nwjs/nw.js#5525]
reported on the npm-linked repo 24 days ago:

https://github.com/egoist/nwjs/issues/19

**Comment by mythril** [comment]
I'm guessing that repo was bs, because I found another on npm that works fine.

**Comment by mythril** [comment]
[the crap one](https://www.npmjs.com/package/nwjs)

**Comment by ghostoy** [comment]
Please follow up this issue on egoist/nwjs project. It's not maintained by us.
