### ISSUE TITLE
Print Preview does not Include PDF Viewer.

### ISSUE THREAD

**Issue by nawazishali** [nwjs/nw.js#5526]
Hi There @rogerwang!

I am having an issue with Print Preview on NW.js V 0.19 (win 32), My OS is Windows 8 and a screen shot can be seen attached below. The Print Preview Dialog says the following "NW.js does not include the PDF viewer which is required for Print Preview to function". Any help would be appreciated to resolve this issue. I might have missed something and was not able to find a solution anywhere in the docs or over here.

Regards,
Nawazish Ali

![untitled](https://cloud.githubusercontent.com/assets/16779681/20864565/30cf461a-b9ee-11e6-9332-f96277ad4a4a.jpg)

**Comment by ghostoy** [comment]
I can't reproduce this issue on Windows 8.1 with 0.19.0 ia32/x64. How do you invoke the print preview? And does it happen for other NW.js apps, like a hello world?

**Comment by nawazishali** [comment]
Never Mind, The problem was with my package.json settings, I had plugins set to false and Print preview relies on a PDF Reader plugin. So I set it to true and everything is working as desired. Thanks for looking into it though.

`{
  "name": "airblue-hrs-app",
  "version": "1.0.0",
  "description": "Airblue HRS/CYC Status App",
  "main": "index.html",
  "window": {
    "toolbar": true,
    "resizable": true
  },
  "webkit": {
    "plugin": false,
    "java": false,
    "page-cache": false
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Nawazish ALi",
  "license": "MIT",
  "dependencies": {
    "diskdb": "^0.1.17"
  }
}`

**Comment by nawazishali** [comment]
I am closing this Issue now as it is no longer valid. Thanks @ghostoy  for the effort. 👍
