### ISSUE TITLE
NW0.12.3 App often crash

### ISSUE THREAD

**Issue by mangaga** [nwjs/nw.js#5527]
We have no plans to upgrate nw version now, but user's app often crash ，and we can't find where the problem is. 

Any one could help to  analyse these mini dump files ， I am forever in your debt.`_`

nw version：nwjs-v0.12.3-win-ia32
these crash files were collected from my users, their OS  include winows xp/Windows 7 /Windows 10, ia32 and x64

[dumpfiles.zip](https://github.com/nwjs/nw.js/files/629993/dumpfiles.zip)

**Comment by rogerwang** [comment]
I'm afraid that we don't support 0.12.x now.
