### ISSUE TITLE
nssm + node-webkit

### ISSUE THREAD

**Issue by ubaltaci** [nwjs/nw.js#553]
Hi,

I developed some kind of kiosk application.  I use nssm[1] to adding app as a windows service on windows 7 machine. Since app will start whenever windows starts and if crash occurs, windows service re-starts my app.

I have experimented with some exe files ( winrar etc. ) nssm works good, Is it possible my nssm service not working because node-webkit executable structure differs than other executable files ? How can I handle this kinda situation ? 

All suggestions are welcomed :)

[1] http://nssm.cc/
##

**Comment by lklepner** [comment]
How did you make out on this? I'm thinking about giving it a try - I've got a kiosk style application as well.

**Comment by ubaltaci** [comment]
Hi @lklepner, we wrote small C# program, every X seconds, it checks process list and if our app is not in the list, it starts the app immediately.

**Comment by lklepner** [comment]
Thanks for the info @ubaltaci. Are you running the C# program via nssm? Any chance you could share a gist of the C# app?
