### ISSUE TITLE
Unable to drag frameless window when scroll down scrollbar

### ISSUE THREAD

**Issue by zhangyuqian** [nwjs/nw.js#5534]
Hi,
In my app, i use "-webkit-app-region: drag"  to enable frameless window drag feature, and there is a scroll bar below the topbar. When content overflew, scroll down the scrollbar, then drag topbar, it doesn't work, can't drag window.
Pls help to fix this issue,thks.

os: linuxMint 64
nwjs version: 0.19

**Comment by ghostoy** [comment]
Could you post a sample app?

**Comment by zhangyuqian** [comment]
Sorry to bother, it's confirmed as a app issue.
