### ISSUE TITLE
Content Verification// it can't take effect

### ISSUE THREAD

**Issue by Vincent2015** [nwjs/nw.js#5535]
sign an application with the demo keypair, do the following:
1,change to application directory
2,make sure verified_contents.json or computed_hashes.json is not there (you can just remove them)
3,run payload.exe; it will generate payload.json, which serves as input for sign.py
   on windows7
   1,fisrt run payload.exe (directory same as nw.exe), got payload.json
   2,i got private_key.pem and sign.py from nw.js/tool/sign
   3,python sign.py > /tmp/verified_contents.json same as below 4.
4,run python sign.py > /tmp/verified_contents.json (it’s important that the tmp destination directory is not application directory)
5,move the generated verified_contents.json file to application dir and it’s done.

   then i start nw from cmd, nw --verify-content=enforce_strict .
    and then try modify some files,but i don't found the Content Verification function.

**Comment by rogerwang** [comment]
It works for me.

It's fine to run the app with hacked files as long as the file is not accessed/loaded.

**Comment by Vincent2015** [comment]
is there any uncorrect operation ref above mine? Can you give me some specific guide. I don't want others to modify the unziped file

**Comment by rogerwang** [comment]
No. 

The guide is here: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Content%20Verification/

Please discuss this in the mailing list unless you find a bug.
