### ISSUE TITLE
Tray is not working!!

### ISSUE THREAD

**Issue by longang520** [nwjs/nw.js#5537]
I added a tray after the page from the new refresh, resulting in tray can not be used,
How could he get him from the new job.

Debugging time from the new application will also lead to tray does not work

**Comment by ghostoy** [comment]
It's recommended to create tray in background page, if the page can be refreshed or navigated. See http://docs.nwjs.io/en/latest/References/Tray/#synopsis

**Comment by lishichao1002** [comment]
```
window.addEventListener('beforeunload', function (event) {
    removeTray()
  })
```
