### ISSUE TITLE
Can't play video files anymore after upgrade to v0.19 

### ISSUE THREAD

**Issue by sica07** [nwjs/nw.js#5539]
Hi!
I upgraded our app from v0.17.4 to v0.19 (on Linux) and videos are not played anymore. 
The error we get is:
 `Uncaught (in promise) DOMException: Failed to load because no supported source was found.`
What we are doing is, uploada file as a blob and play it.

```javascript
nw.Window.open('video.html', {}, function(win){
    win.enterFullscreen();
    win.on('enter-fullscreen',function(win){
        var video = this.window.document.querySelector('video')
            try{
                video.src = URL.createObjectURL(fileObj);
                video.play();
            }catch(e) {
                ukNotify(e, 0)
            }
         video.webkitRequestFullscreen();
    });     
});          
```
Any idea why is this happening now?

**Comment by rogerwang** [comment]
Could you please provide a full case so we can reproduce it here?

**Comment by sica07** [comment]
Of course:
```html
<!DOCTYPE html>
<html>
    <head>
        <script src="vendor/jquery.min.js"></script>
    </head>
    <body>
        <button>Play</button>
        <input type="file" id="videoFile1" accept="video/mp4">
        <script>
            $(document).ready(function(){
                var videoFile;
                $("input").on('change',function(evt){
                    videoFile = evt.currentTarget.files[0];
                })
                $("button").click(function(){
                    var fileURL = URL.createObjectURL(videoFile);
                    nw.Window.open('video.html', {}, function(win){
                        win.enterFullscreen();
                        win.on('enter-fullscreen',function(win){
                            video = this.window.document.querySelector('video')
                                try{
                                    video.src = fileURL;
                                    video.play();
                                }catch(e) {
                                    //    ukNotify(e, 0)
                                }
                            video.webkitRequestFullscreen();
                        })
                    });
                });
            });
        </script>
    </body>
</html>
```
The video.html file is a plain html file with a `<video autplay type="video/mp4"></video>` element in it.

**Comment by Blatman** [comment]
FWIW, tried this on OSX with 0.19.1 and got the same but realized I needed to upgrade the libffmpeg.dylib to an mp4 capable version - worked fine (crashes on 0.20a1 tho')

**Comment by sica07** [comment]
I tried in Windows 10, same error message. So, it seems that it does not
work in any of the 3 OS.

**Comment by rogerwang** [comment]
@scia07 as reported by @Blatman I think you need another ffmpeg library -- the official one won't play mp4.

**Comment by sica07** [comment]
@rogerwang I don't understand what do you mean by that. I know that nwjs has the chromium ffmpeg library built in it. How can I use another ffmpeg library? How can I include it in nwjs?

**Comment by rogerwang** [comment]
We don't distribute the proprietary  codecs as we don't have the license. Read more here: http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/
