### ISSUE TITLE
Close and exit event triggering on launching child process 

### ISSUE THREAD

**Issue by sandeepks1** [nwjs/nw.js#5540]
Read the following before submitting your issue, thank you.

* Please use English so all users can read, or the issue will be closed directly.
* Use our mailing list to ask questions which don't imply bug or feature request: https://groups.google.com/forum/#!forum/nwjs-general
* State which version are you using
* State which OS version are you running with
* Provide a reproducible case if possible
* Attach the crash dump file if it's a crash: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

Issues meet the checklist above will be processed before those don't.
I am using the following code to launch the system calculator application and i need an event which trigger on closing that calculator application,but event is triggering on launching the application itself
.its been last 3 days i am looking for this issue same and the code working fine if i try to open notepad application

const spawn = require('child_process').spawn;
const bat = spawn('cmd.exe', ['/c', 'calc.exe']);
bat.on('exit', (code) => {
alert(Child exited with code ${code});
});

**Comment by ghostoy** [comment]
The code works for me with 0.18.7 and 0.19.0 on Windows. Could you also test if your code works in pure Node.js? If not, please post a full sample app.

**Comment by sandeepks1** [comment]
The issue is only with windows 10 and the issue is reprodusable with pure node Js also

Thanks
Sandeep KS

**Comment by ghostoy** [comment]
@sandeepks1 I suspect it's an issue of `calc`, which is a Windows Store App. For Win32 apps, like `notepad.exe`, `cmd /c` always wait until exit. Please try to raise issues to [Node.js](https://github.com/nodejs/node/issues) or [Microsoft](https://connect.microsoft.com/).

**Comment by sandeepks1** [comment]
@ghostoy Thanks for your reply :)
