### ISSUE TITLE
NW app damaged after distribution. Gatekeeper security problem (macOS Sierra).

### ISSUE THREAD

**Issue by gdiazfor** [nwjs/nw.js#5546]
Hi,

we are using nwjs version 19.0 for our app and having some issues with the new Gatekeeper security in macOS Sierra.
We have already singed the .app, but after uploading and distributing the applications, every user running Sierra gets the same message "The app is damaged and can't be opened".

After removing the attributes the external attributes with terminal (xattr -rc), the app seems to be working fine.

How can we fix this?

Thanks in advance.

![screenshot](https://cloud.githubusercontent.com/assets/20682933/21148522/4cf2f440-c137-11e6-9530-5a98c565a1f2.png)

**Comment by ghostoy** [comment]
Could you post how you sign, pack and redistribute your app?

**Comment by gdiazfor** [comment]
It was an error in our signing process. Thanks for the help anyway.
