### ISSUE TITLE
How can I require a local js file?

### ISSUE THREAD

**Issue by lucasalcantara** [nwjs/nw.js#5551]
I have a html file that use the first js file  `<script src="../../repository/client.js"></script>`

Inside my client.js I have this code below (it is trying to require the file clientDal which is in the same path )

```
$(function(){
	var something = require('clientDal.js');
});
```

the file clientDal is totally empty. So what I am missing? Why when I run the code the app stop to work.

**Comment by ghostoy** [comment]
You need to use `./clientDal.js` instead of `clientDal.js`. Same as Node.js.

**Comment by lucasalcantara** [comment]
Yeah, I already tried and did not work. Any other advice?

**Comment by ghostoy** [comment]
Oh, I see. `require` invoked from `<script>` tag will resolve the path based on the directory of HTML file, not the js file in `<script src>`. So if `clientDal.js` is in the same directory as `client.js`, you should use `require('../../repositories/clientDal.js)`.

**Comment by lucasalcantara** [comment]
Worked @ghostoy big thank you.
