### ISSUE TITLE
Chrome identity official sample app crashes nw.js on login

### ISSUE THREAD

**Issue by erickedji** [nwjs/nw.js#5552]
NW version: 0.19.2
OS: Ubuntu 16.04.1 LTS
Steps to reproduce:

1. Get the chrome identity sample app : https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/identity
2. Run it with: /path/to/nw /path/to/chrome/samples/identitiy
3. The apps opens correctly. Click on "Sign in".
4. A new window opens (chrome://chrome-signin/?access_point=6&reason=0). Enter your google login, then your password. Submit.
5. The form seems submitted, a blank page loads, then nw crashes

Console output:
`
[8771:8826:1214/080647:ERROR:extension_function_dispatcher.cc(629)] Permission denied for webRequestInternal.addEventListener
[8771:8826:1214/080647:ERROR:extension_function_dispatcher.cc(629)] Permission denied for webRequestInternal.addEventListener
[8771:8826:1214/080647:ERROR:extension_function_dispatcher.cc(629)] Permission denied for webRequestInternal.addEventListener
[8771:8826:1214/080647:ERROR:extension_function_dispatcher.cc(629)] Permission denied for webRequestInternal.addEventListener
[8993:8993:1214/080718:ERROR:KeyboardEventManager.cpp(344)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
`

[crash.dmp.zip](https://github.com/nwjs/nw.js/files/650975/crash.dmp.zip)

Thanks.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by erickedji** [comment]
That was very quick, thanks!

**Comment by rogerwang** [comment]
I fixed the permission error and crash only. 

The sample app doesn't work in Chromium browser, neither in NW.

**Comment by erickedji** [comment]
I did more testing with chromium (Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)) and found that the identity sample:

- does not work when you are not already logged into chromium (that is, using the browser login that saves passwords, syncs history, etc.). There is a generic error message every single time (see picture): "Uh-Oh! Service unavailable, try again later"
- works flawlessly when you are **already signed into** chromium: it asks for login and password, then shows the Oauth consent screen (asking for permissions, etc.)

I'm launching the sample in chromium with: 
`chromium-browser --silent-launch --load-and-launch-app=./chrome-app-samples-master/samples/identity/`

Maybe the browser signin UI is not included in NWJS.
Should I open a separate issue?

![chromium-login-issue](https://cloud.githubusercontent.com/assets/52732/21240639/741c8a00-c30c-11e6-9a5d-c46991f0a81b.png)

**Comment by erickedji** [comment]
Moved to #5574 5574
