### ISSUE TITLE
strip files and generate release zip when nwjs building is done

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#5554]
Hi @rogerwang @ghostoy 

i m bulding nwjs 0.19.1 since yesterday on osx Sierra and linux (many outdated or missing infos in the doc, will post another issue)

on previous build of nwjs when ninja finished build a zip was generated and files stripped automatically, now i just have a bunch of files in the out dir ...

how can i strip files and generate a zip like official release please (thru gn or gyp i think ..) ? 

thanks

**Comment by ghostoy** [comment]
Use `dist` target: `ninja -C out/nw dist`
