### ISSUE TITLE
nw.js0.19.2   ffi  winXp 

### ISSUE THREAD

**Issue by Power-Deng** [nwjs/nw.js#5560]
When I use nw.js + ffi to calling a *.dll in WinXp. The App have these two problems. 
![lalokw2gfnvnagm_515_123 png_620x10000q90g](https://cloud.githubusercontent.com/assets/18547539/21223761/eff523f2-c303-11e6-9952-84d47aba7fe9.jpg)
![lalokw2ga3fnafy_502_119 png_620x10000q90g](https://cloud.githubusercontent.com/assets/18547539/21223764/f13f0106-c303-11e6-9734-637720c50064.jpg)
But The App is running well in Win 7. Who can help me?
nw version：nwjs-v0.19.2-win-ia32
 OS : win Xp

**Comment by rogerwang** [comment]
Win XP is supported via 0.14.7: https://github.com/nwjs/nw.js#downloads
