### ISSUE TITLE
NW.js 19.2 - Webview freezes on almost any invalid certificate

### ISSUE THREAD

**Issue by janRucka** [nwjs/nw.js#5564]
If I create webview in NW.js and navigate it on almost any website with invalid certificate it will freeze. Works fine in Chrome (tested on webview created in extensions). 

You can try it here for example:
https://badssl.com/

The same applies to at least NW.js 18. Worked fine in NW.js 14.

**Comment by rogerwang** [comment]
Is this duplicate with #5544?

**Comment by janRucka** [comment]
I didn't see that issue (just looked in open issued) and it seems to be very similar. But I just tried this build:
https://dl.nwjs.io/live-build/12-16-2016/nw19-a83e646-5bca068-287bf0e-c183b55/v0.19.3/nwjs-sdk-v0.19.3-win-ia32.zip
And it still hangs. Should it be fix there?

Adding my test project:
[certTest.zip](https://github.com/nwjs/nw.js/files/656896/certTest.zip)

**Comment by bachel** [comment]
I have the same problem with webview. Even in latest 0.19.3 nightly build and 0.20.0-beta1. Both on windows
@rogerwang We should reopen issue #5544

**Comment by rogerwang** [comment]
@bachel I'll fix this issue soon. It should be different with #5544

**Comment by rogerwang** [comment]
I just tried http://dl.nwjs.io/live-build/12-20-2016/nw19-a83e646-0c6fe80-287bf0e-c183b55/v0.19.3/ and it works fine.

**Comment by janRucka** [comment]
Really? I tried it again with your link and it's the same. Please try my test project (attached to my previous comment). It will load badssl.com page - this works fine but whenever you click on any link with invalid certificate the whole NW.js will freeze.

**Comment by rogerwang** [comment]
I was trying your app and I clicked one of the blocks and it shows a result page, but I was trying win-x64 sdk version. Should be the same with 32bit version.

**Comment by janRucka** [comment]
Result page? Previous version of NW.js (14.x) shown chrome-like page which inform you that you have invalid certificate:
http://cdn.inmotionhosting.com/support/images/stories/website/errors/ssl/chrome-your-connection-is-not-private.png

So it is strange that you can see result page... For me nothing happens, it just freezes no chrome page no result page.

**Comment by rogerwang** [comment]
Here is what I was talking about:

![1](https://cloud.githubusercontent.com/assets/165401/21345474/5deaba90-c6db-11e6-95b0-e20dc2316ccf.png)
![2](https://cloud.githubusercontent.com/assets/165401/21345478/63914d1a-c6db-11e6-9f69-4ddf70fe15ce.png)

I just realized it may be that our corporate proxy has been injecting certificates trusted in our intranet. Will test again under a different network...

**Comment by janRucka** [comment]
As you said. It can be your proxy. I think you should be warned it is invalid certificate...

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by janRucka** [comment]
Confirmed - it works.
Well done.
