### ISSUE TITLE
The method "nw.Window.get().hide()" can't work on windows system.

### ISSUE THREAD

**Issue by lxhao** [nwjs/nw.js#5565]
I first open index.html  as main window,  then start several new windows. now, I need to hide main window, I tried  "nw.Window.get().hide()", but the method can't normal work on windows, and It work on ubuntu.

**Comment by ghostoy** [comment]
I can't reproduce the issue with 0.19.0 x64 on Windows 7. Could you post your sample app, NW.js version and Windows version?

**Comment by lxhao** [comment]
It's my test code on windows 7 32bit system with v0.14.7.    git@github.com:lxhao/testForNw.git , more over, I tried on windows 7 64bit  or windows xp 32bit, which also can't work.

**Comment by ghostoy** [comment]
Main window invoked `win.hide()` followed by `win.maximize()`. That will make the window show up. See https://github.com/lxhao/testForNw/blob/master/index.js#L27.

**Comment by lxhao** [comment]
you may misunderstand my code,  I just hide main window, and maximize new opened window.
