### ISSUE TITLE
ffmpeg with proprietary codecs breaks SDK 20.0b2

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5569]
Just tried the current beta SDK 20.0 beta 2 with the non-proprietary codecs bundled with the release and it works correctly, but once the ffmpeg is replaced with a version that has proprietary codecs enabled the application never launches, instead it throws the following error:

>nw.exe - Entry Point Not Found
>The procedure entry point avcodec_parameters_to_context could not be located in the dynamic link library ffmpeg.dll

I have used the most recent ffmpeg with enabled proprietary codecs available here, which is suggested in the NWJS guides: https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

To reproduce this problem, simply replace the beta's ffmpeg with the one available above and try to open the app.

OS: Win7 x64

**Comment by smolleyes** [comment]
hi

this fffmeg libs are builded against a specific nwjs version (max 0.19.2 currently)  it s n ot ready for nw20 yet (so not a bug)

++

**Comment by Yonezpt** [comment]
That was never an issue despite being released with version tags. I have been using the ffmpeg tagged for v0.16 through all NWJS versions without any issues, with the latest working version of NWJS being 19.0.2 using ffmpeg tagged v0.16

I also tested with Electron's 1.4.12 ffmpeg and the same error is displayed.

**Comment by smolleyes** [comment]
i said i think :p 

maybe an upstream change in chromium created this bug ... good chances :p

**Comment by Yonezpt** [comment]
Not trying to criticize, I also am not sure about my points, it could very well be just as you said. For the moment I am trying (read: struggling) to compile it on my own to see if I can confirm what you said and perhaps close this invalid bug and not loading devs with unnecessary tasks.

**Comment by Blatman** [comment]
@Yonezpt   Yes I agree - I found that 0.20 crashes on start when mp3/4 used with OSX.
I used the latest 0.19.2 dylib from iTeufel to check but have previously found that a specific version doesn't really matter. The NWjs binary will work OK on other codec types if I remove the mp file reference from the src of the embed/object tag - seems to be mpg upsetting things.

**Comment by Yonezpt** [comment]
Unfortunately I am completely stuck in step 2 from here: http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#build-ffmpeg-dll-without-building-nwjs

Because of this reason: https://github.com/nwjs/nw.js/issues/5571

I have absolutely no idea how to continue from there, the instructions are not clear about what should be done exactly so I have been trying to hack and slash my way through via Google without any idea of what I actually need to know: is "gn" an installer or a command part of a different installer? If yes, which installer is it? I have found GN related to Ninja-Nuild system builder, yet that isn't even an installer, and so on.

I am afraid that I cam completely unable to test whether this issue is related to the ffmpeg version or to the nwjs version because the building instructions are not helpful. If anyone else knows how to do it I would appreciate if he could test this problem and share with us exactly which steps to take in a way that is actually clear to the readers.

**Comment by Yonezpt** [comment]
And it looks like @smolleyes was correct. For some reason iteufel's most recente release was not showing up with the v20 ffmpeg: https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/tag/0.20.0-beta1

Having just tested it I could confirm that NWJS is working correctly again, for this reason I will close this issue seeing that it was not a bug but an incompatibility.
