### ISSUE TITLE
DOMException: The element has no supported sources

### ISSUE THREAD

**Issue by moran32** [nwjs/nw.js#5570]
I use nwjs-sdk-v0.14.7-win-x64 open a html page.
my html code:
`<audio id="audio1" src="a.wav" type="audio/wav"></audio>
<input type="button" value="play" onclick="playAudio()"/> `
my javascript code:
`var thissound = document.getElementById("audio1");
 thissound.play();`
when click button, devTool show this error:
DOMException: The element has no supported sources
How to solve it?

**Comment by moran32** [comment]
Need replace ffmpeg.dll? 
Who have this file?
Thanks

**Comment by phpjishu** [comment]
https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

**Comment by moran32** [comment]
Thank you very much.
