### ISSUE TITLE
"Enable Proprietary Codecs" is still lacking comprehensible information

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#5571]
Since the last review on this part of the documentation: http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

I noticed that a high degree of knowledge is still required to understand some of the steps, meaning that there are steps missing to make them more clear otherwise I am completely unable to continue on my own by following the instructions.

These are the steps that need to be explained in more detail or exemplified in order to allow less knowledgeable users to understand what it is required to do:

>Git clone following folders with corresponding commits as in DEPS file

I understand what cloning in git means, but the commands that are required for this step are a complete mistery, is it `git clone something.something buildtools` or just `git clone buildtools` or something completely different?

>Download gn tools in buildtools/<os> by

I have no clue about this one, I cannot find any `buildtools` folder inside the chromium.src which is distributed here: https://github.com/nwjs/chromium.src/tags

Do I have to download gn inside a new folder that I have to create with the name `buildtools` or is gn already inside that folder which should be in the chromium.src package or is it linked to the previous step?

Another problem is that absolutely no requirements are listed. Readers will follow the instructions assuming that nothing is needed beyond the cmd window, when it requires at least a Git client and Python 2.7.X , perhaps Gclient or Depot_tools but no mention of it is made anywhere in the documentation.

Finally, while the following steps appear to be straight forward, I cannot find in any of them where I choose which proprietary codecs to enable.

I would really appreciate if either the guide could be improved to a point where newcomers won't have an issue understanding how to build it by themselves, or provide a tool/script which automatically does all of those steps automatically with the only options prompted to the user being which codecs to enable.

**Comment by smolleyes** [comment]
look at this :p

https://github.com/butterproject/nwjs-build/blob/master/build_linux64.sh

i builded osx64 and linux64 versions with many codecs with the same type of process, doc will be updated soon :p (waiting for @ghostoy 's PR being merged)

**Comment by Yonezpt** [comment]
@smolleyes hey! Just one bash to do all the work? If so that is really great! Does it come with all proprietary codecs enabled?

Wondering if it is easy to adapt for Windows as well.

**Comment by smolleyes** [comment]
i used to to it a looooooooooooonnngg time ago with 0.7.3 on windows so i can t reply, it s a bit more complicated since you have to build the ffmpeglib in cygwin and nwjs thru windows console normally (if i remember)

you have to tweak the patch to add some codecs, (better to analyse the iteufel's script patchs if you want to learn)

i can post my 0.19.2 builds for osx64 and linux64 somewhere if you want, i ll try on windows tomorrow ,for the moment i fight with the 32 bits linux :/

currently i can read webm/mp4 (x264/x265-hevc)/mp3/aac/flac/avi (not always working)/opus and ac3/dts ...

**Comment by Yonezpt** [comment]
Yeah, that's not even an option now since NWJS moved from Cy to GN. There's no need to do that, I will just wait until the devs decide if the guide needs to be more clear, until then I'll be using the builds released by @iteufel https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

**Comment by smolleyes** [comment]
most important in the nwjs side (gn args) is to add

ffmpeg_branding="Chrome" nwjs_sdk=false proprietary_codecs=true enable_ac3_eac3_audio_demuxing=true enable_hevc_demuxing=true

that s all... doc is ok for this

**Comment by Yonezpt** [comment]
What you just said, I have no idea where to put it: when to do it and which tools are required to have installed in order to make it work. I explained that problem in the first post, that's the issue when someone like me with less experience reads it, it isn't sufficiently clear at certain points and it doesn't tell which requirements are needed.
I went today 5 straight hours trying to understand the instructions and eventually I was completely unable to get through step 2, this was not a situation of someone just being lazy, I did try, read and searched for hours and found nothing that could help me get through that step.

**Comment by smolleyes** [comment]
i understand, that s not easy yes... and take a looot of time and disk space too...

everything you need is in the first script i gave you ;) just read the code ... (easier than the nwjs doc for the moment) my previous comment is for the line 69 for exemple

**Comment by ghostoy** [comment]
## Dependencies
> Git clone following folders with corresponding commits as in DEPS file

All dependencies are not included in the source package. After extracted the source package, you will find `DEPS` file in the root. Search for `buildtools`, you can find something like

```python
'src/buildtools':
    (Var("chromium_git")) + '/chromium/buildtools.git@39b1db2ab4aa4b2ccaa263c29bdf63e7c1ee28aa',
```

* `src/buildtools` is the folder to clone the repo.
* string before `@` is the to the repo of official Chromium.
* string after `@` is the commit hash

Just use `git clone <url> buildtools` and `git checkout <commit-hash>` in `buildtools` folder.

## Prerequisites
I'll mention the prerequisites, like `depot_tools` in the document.

## Codec List
I'll mention the list of proprietary codecs in the document.

**Comment by Yonezpt** [comment]
Thanks @ghostoy for improving the instructions. In the first instructions you mention the `git clone <url>`, what I did was manually search for the `Var("chromium_git")` value inside the DEPS file, appended to the corresponding dependency url, in your example would be `/chromium/buildtools.git@39b1db2ab4aa4b2ccaa263c29bdf63e7c1ee28aa` but it wouldn't work, I had to remove everything after the dependency for it to work, so the final working url would be `https://chromium.googlesource.com/chromium/buildtools`.

I had no idea how to do it the way you just mentioned with buildtools and git separation.

Also the next step is also a complete mystery to me, unless the `gn` file is downloaded into the `buildtools/<os>` by correctly doing the steps you mentioned above.

If the instructions result in a fully proprietary enabled codec ffmpeg then it is allright, otherwise it would be a problem because we would have to try and guess where we could enable them on our own.

**Comment by Yonezpt** [comment]
Also, another pointer, in the dependencies step there is a path name that doesn't appear to be correct. For the gyp clone instructions it indicates the folder location to be `third_party/yasm/sources/patched-yasm` but chromium only has `source` (singular) folder. Is it a mistake or is it suppose to created a new folder with `sources` (plural)?

**Comment by Yonezpt** [comment]
Was finally able to compile the ffmpeg.dll with proprietary codecs enabled. Had no idea in step 2 all that was required was to literally run those instructions in cmd (with no other prefix commands such as gclient or gn)

> `download_from_google_storage --no_resume --platform=<os> --no_auth --bucket chromium-gn -s buildtools/<os>/<gn-exe>.sha1`

with the respective `os` and `gn-exe` info replaced.

Another thing that should be mentioned, no one with Windows will be able to pass step 4 because Windows cmd apostrophes will not work as a string delimiter, the apostrophes need to be replaced with double quotes and the previous double quotes need to be escaped with backslash, as such

> `gn gen //out/nw --args="is_debug=false is_component_ffmpeg=true target_cpu=\"<target_cpu>\" is_official_build=true ffmpeg_branding=\"Chrome\""`

One last problem, but this one is just typing mistake, there are 2 step fours: `Generate Ninja Files with GN Tools` is the original step four, but the next step `Build ffmpeg DLL` (should be step 5) is also step 4, and the last one should be step 6 instead of 5.

**Comment by ghostoy** [comment]
@Yonezpt The documentation will be refined with a simplified way, which depends on `gclient` tool instead of downloading them manually. Basic understanding of Python syntax is still required, but you don't have to reconstruct the URLs or use `git`.

**Comment by Yonezpt** [comment]
Thank you @ghostoy , a python barrier will definitely be far easier to learn since it is vastly more used than the other tool(s) and there are plenty of guides online for most things that readers might not understand.

**Comment by humiston** [comment]
Any idea when the pr linked to this ticket will be reviewed and merged? I'm using this thread in an attempt to rebuild FFmpeg for branch nw28 and seem to have gotten stuck at  

`download_from_google_storage --no-resume --platform=darwin --no_auth --bucket chromium-gn -s buildtools/mac/gn.sha1` 

where I'm currently in the `chromium.src-nw28/buildtools/mac` folder and am getting `download_from_google_storage: command not found`.

**Comment by rogerwang** [comment]
@humiston with @ghostoy left the team, we can't make sure this is officially supported through Chromium version updates. But we welcome anyone who is willing to maintain it.

**Comment by rogerwang** [comment]
To be specific, I'm considering removing the section `Build FFmpeg DLL without Building NW.js` from the official document since this part is not maintained.

**Comment by Yonezpt** [comment]
Closing this since it is no longer maintained.
