### ISSUE TITLE
Chrome identity official sample app does not complete oauth2 login in nwjs

### ISSUE THREAD

**Issue by erickedji** [nwjs/nw.js#5574]
(this is a followup to #5552)

NW version: 0.19.2
OS: Ubuntu 16.04.1 LTS

1. Get the chrome identity sample app : https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/identity
2. Run it with: /path/to/nw /path/to/chrome/samples/identitiy
3. The apps opens correctly. Click on "Sign in".
4. A new window opens (chrome://chrome-signin/?access_point=6&reason=0). Enter your google login, then your password. Submit.
5. The form is submitted, but then nothing happens

With chromium (Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)), the identity sample:

- does not work when you are **not already logged into chromium** (that is, using the browser login that saves passwords, syncs history, etc.). There is a generic error message every single time (see picture): "Uh-Oh! Service unavailable, try again later"
- works flawlessly when you are already signed into chromium: it asks for login and password, then shows the Oauth consent screen (asking for permissions, etc.)

I'm launching the sample in chromium with:
chromium-browser --silent-launch --load-and-launch-app=./chrome-app-samples-master/samples/identity/

Maybe the browser signin UI is not included in NWJS. If so, do you have any plan to include it?

![chromium-login-issue](https://cloud.githubusercontent.com/assets/52732/21304950/f3e0c24c-c5c8-11e6-90d5-669feb4993e6.png)

**Comment by rogerwang** [comment]
This is due to missing Google API Key in NW. I'll add a feature to let developers provide their own key.

**Comment by rogerwang** [comment]
I just tried the identity app with a valid API key and it works for me. So close this issue.

See https://www.chromium.org/developers/how-tos/api-keys for how to get/set the API key for your app.

**Comment by erickedji** [comment]
Nice, thanks!
