### ISSUE TITLE
Modifying content of external website in nwjs iframe(nwdisable,nwfaketop)

### ISSUE THREAD

**Issue by myfrndjk** [nwjs/nw.js#5577]
I am loading third party website inside my iframe.

```html
<iframe height="800" width="800" nwdisable nwfaketop src="http://www.example.com">
</iframe>
```

I want to inject  js into "example.com" HTML while rendering.
Is it feasible to inject js into third party website, while loading the website inside iframe

sample js:

```html
<script type="text/javascript">
function extractContent(value){
        var div = document.createElement('div')
        div.innerHTML=value;
        var text= div.textContent;            
        return text;
}
window.onload=function()
{
   alert(extractContent("<p>Hello</p><a href='http://w3c.org'>W3C</a>"));
};
</script>
```

If the option is already available please share the sample code if it is not available can we add this feature

Thanks

**Comment by ghostoy** [comment]
You can directly access the window object in the frame from outside with `frm.contentWindow`. Or use `inject_js_start` / `inject_js_start` to inject a script for all windows / frames. See http://docs.nwjs.io/en/latest/References/Manifest%20Format/#inject_js_start.

Github issues are used to tracking bugs and feature requests. Please post your further questions in mailing list https://groups.google.com/forum/#!forum/nwjs-general.
