### ISSUE TITLE
Node-webkit will hang when there is an alert

### ISSUE THREAD

**Issue by freewind** [nwjs/nw.js#558]
Visit http://angular-ui.github.com/bootstrap, click the "open module" button on the middle, there will be an dialog. Close it, there will be an alert dialog. Click on the page, then node-webkit hangs.

Here is my screencast:

![nw-alert-dead](https://f.cloud.github.com/assets/333781/284515/95cf2102-91ed-11e2-836b-0415f402fefe.gif)

**Comment by oknoorap** [comment]
yes this is absolutetly bug, my clients (buyer) were angry when there is a simple bug like this, true story.
