### ISSUE TITLE
Path resolving bug, when .js is used as "main" script

### ISSUE THREAD

**Issue by ggarek** [nwjs/nw.js#5582]
# Start
First of all i want to say, that i am aware of "different contexts thing", and i read several times the explanation.

**But**, i still think that there is a corner case:

# The case
## Content
```
(master)⚡ % tree nw-path-bug
nw-path-bug
├── a
│   └── index.js
├── b
│   └── data.json
└── package.json

2 directories, 3 files
```
```
(master)⚡ % cat nw-path-bug/package.json
{
  "name": "seems there is a bug",
  "version": "1.0.0",
  "main": "a/index.js"
}
```
```
(master)⚡ % cat nw-path-bug/a/index.js
const fs = require('fs');

// Works, but the path is wrong!
fs.readFileSync('./b/data.json');

// Fails, though path is correct
fs.readFileSync('../b/data.json');%
```

## Try to run it
```
(master)⚡ % ~/lib/nwjs/nwjs-v0.20.0-beta1-osx-x64/nwjs.app/Contents/MacOS/nwjs nw-path-bug/
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../b/data.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at chrome-extension://lghcaicggppoaecmnfacgidenooinold/a/index.js:7:4
```
```
(master)⚡ % ~/lib/nwjs/nwjs-sdk-v0.19.2/nwjs.app/Contents/MacOS/nwjs nw-path-bug/
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../b/data.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at chrome-extension://lghcaicggppoaecmnfacgidenooinold/a/index.js:7:4
```

# Additional info
I checked with 2 nwjs versions:
- nwjs-v0.20.0-beta1-osx-x64
- nwjs-sdk-v0.19.2

I run OSX 10.11.6 (15G1108)

in both cases i use
```
(master)⚡ % node -v
v7.2.1
```

# Example/Reporduction
[nw-path-bug.zip](https://github.com/nwjs/nw.js/files/669319/nw-path-bug.zip)

**Comment by ghostoy** [comment]
js script loaded via `main` was injected with `<script>` tag in the context of background page. But the background page is a virtual file generated in runtime. So it has no real file path on disk. Then the path resolution for `require` is based on the root of the app.

**Comment by ggarek** [comment]
@ghostoy but it means, that one needs to mangle with `require`s when sources are compiled to be launched/packed with nwjs... It is very inconvenient to say the least, because what one expects is just `cp src/ dist/ && cd dist/ && nw ./` will work, but it wont.

Is there anything what can be done to tackle this?

**Comment by ggarek** [comment]
Sure, one can workaround it by bundling main script (say with webpack), but i think it would be right think to do to teach the background page to know a project file structure. Though it may be tedious task.

**Comment by ghostoy** [comment]
@ggarek Sorry, I just reviewed your issue and found out you are talking about `fs.readFileSync` instead of `require`.

The relative path resolving is based on current working directory (CWD). And CWD is the root directory of your project (a.k.a. directory of `package.json`), no matter which context your script is loaded in. You can change your CWD to `a` by `process.chdir('a')`. It will make all subsequent relative path resolving based on `a`.

**Comment by ghostoy** [comment]
If the workaround above solve the problem, please close this issue and watch on #2836, which is the same request as yours.

**Comment by ggarek** [comment]
@ghostoy Sure, there are workarounds possible to mitigate this issue. But i am interested in enhancing this behaviour in NW.js, so let`s track it under #2836!
