### ISSUE TITLE
App not running on Windows, crush

### ISSUE THREAD

**Issue by robaweb** [nwjs/nw.js#5584]
In some cases, i don't know when and why, but app stops running. App can be ok few days or weeks after first run after build, but in some time app will broken and cannot be executed anymore. Can help only removing old app and install new.

CrushPad was founded in C:\Users\User\AppData\Local\Chromium\User Data\Crashpad\reports.
Folder C:\Users\User\AppData\Local\Crashpad is not exists.
[crushpad.zip](https://github.com/nwjs/nw.js/files/670506/crushpad.zip)

nwjs 0.19.2 Windows 10 64
In debug.txt file is same directory where app.exe:
`
[1223/104952:ERROR:process_info.cc(608)] range at 0xfe5ff000, size 0x230 fully unreadable
[1223/104952:ERROR:process_info.cc(608)] range at 0xfe5fb000, size 0xf84 fully unreadable
[1223/105115:ERROR:icu_util.cc(173)] Invalid file descriptor to ICU data received.
[1223/105115:FATAL:icu_util.cc(292)] Check failed: result. 
Backtrace:
    v8::Isolate::GetNumberOfDataSlots [0x5C9EB907+125719]
    std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Swap_alloc [0x5C993651+481873]
    v8::Extension::source [0x5CCF646C+1390732]
    v8::Unlocker::operator= [0x5C7A6B90+2928]
    v8::Unlocker::operator= [0x5C7A65EB+1483]
    ChromeMain [0x5BB13502+157]
    (No symbol) [0x008C448F]
    (No symbol) [0x008C27B0]
    IsSandboxedProcess [0x00903685+87499]
    BaseThreadInitThunk [0x74A93744+36]
    RtlSetCurrentTransaction [0x77339E54+212]
    RtlSetCurrentTransaction [0x77339E1F+159]
`

Crushpad decoded:

2016-12-23 12:09:07: minidump.cc:2875: ERROR: MinidumpMemoryList has a memory region problem,  region 1/199, 0x0+0x0
2016-12-23 12:09:07: minidump.cc:4869: ERROR: GetStream could not read stream type 5
Operating system: Windows NT
                  10.0.10240 17113
CPU: x86
     GenuineIntel family 6 model 71 stepping 1
     8 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_BREAKPOINT
Crash address: 0x5c9f22a9
Process uptime: 3 seconds

Thread 0 (crashed)
 0  nw.dll + 0xfd22a9
    eip = 0x5c9f22a9   esp = 0x007aeb08   ebp = 0x007af04c   ebx = 0x007af054
    esi = 0x007af060   edi = 0x007af05c   eax = 0x007aec00   ecx = 0x00000000
    edx = 0x00000284   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  nw.dll + 0x12d646c
    eip = 0x5ccf646c   esp = 0x007af054   ebp = 0x007af324
    Found by: previous frame's frame pointer
 2  nw.dll + 0xd86b90
    eip = 0x5c7a6b90   esp = 0x007af32c   ebp = 0x007af7c4
    Found by: previous frame's frame pointer
 3  nw.dll + 0xd865eb
    eip = 0x5c7a65eb   esp = 0x007af7cc   ebp = 0x007af7d8
    Found by: previous frame's frame pointer
 4  nw.dll + 0xf3502
    eip = 0x5bb13502   esp = 0x007af7e0   ebp = 0x007af8d4
    Found by: previous frame's frame pointer
 5  app.exe + 0x448f
    eip = 0x008c448f   esp = 0x007af8dc   ebp = 0x007af978
    Found by: previous frame's frame pointer
 6  app.exe + 0x27b0
    eip = 0x008c27b0   esp = 0x007af980   ebp = 0x007afab0
    Found by: previous frame's frame pointer
 7  app.exe + 0x43685
    eip = 0x00903685   esp = 0x007afab8   ebp = 0x007afafc
    Found by: previous frame's frame pointer
 8  KERNEL32.DLL + 0x13744
    eip = 0x74a93744   esp = 0x007afb04   ebp = 0x007afb10
    Found by: previous frame's frame pointer
 9  ntdll.dll + 0x59e54
    eip = 0x77339e54   esp = 0x007afb18   ebp = 0x007afb58
    Found by: previous frame's frame pointer
10  ntdll.dll + 0x59e1f
    eip = 0x77339e1f   esp = 0x007afb60   ebp = 0x007afb68
    Found by: previous frame's frame pointer

Loaded modules:
0x008c0000 - 0x009aafff  app.exe  0.0.0.0  (main)  (WARNING: No symbols, nw.exe.pdb, B6C959AD86B740D2933E42B7E82E0A6014)
0x5ba20000 - 0x5f8cffff  nw.dll  0.0.0.0  (WARNING: No symbols, nw.dll.pdb, 2540668EA63647DDB1C321AF3A69E1652e)
0x668c0000 - 0x66aaffff  DWrite.dll  10.0.10240.17146
0x6a160000 - 0x6a173fff  SAMCLI.DLL  10.0.10240.16384
0x6bd50000 - 0x6bfdafff  ESENT.dll  10.0.10240.16590
0x6cf30000 - 0x6d0cdfff  ffmpeg.dll  0.0.0.0
0x6d520000 - 0x6d58efff  nw_elf.dll  0.0.0.0
0x6fa70000 - 0x6fa8cfff  dxva2.dll  10.0.10240.16384
0x6fb80000 - 0x6fbacfff  credui.dll  10.0.10240.16384
0x712c0000 - 0x712dffff  ncrypt.dll  10.0.10240.16384
0x712e0000 - 0x71307fff  NTASN1.dll  10.0.10240.16384
0x728d0000 - 0x72ae2fff  d3d11.dll  10.0.10240.17113
0x72af0000 - 0x72cbbfff  d3d9.dll  10.0.10240.17113
0x72d80000 - 0x72dfdfff  dxgi.dll  10.0.10240.17113
0x72f00000 - 0x72f09fff  HID.DLL  10.0.10240.16384
0x72f10000 - 0x72fb7fff  WINHTTP.dll  10.0.10240.16942
0x730e0000 - 0x7321efff  dbghelp.dll  10.0.10240.16384
0x73260000 - 0x73269fff  Secur32.dll  10.0.10240.16384
0x732c0000 - 0x732dcfff  dwmapi.dll  10.0.10240.16392
0x732e0000 - 0x73302fff  WINMMBASE.dll  10.0.10240.16384
0x73310000 - 0x73333fff  WINMM.dll  10.0.10240.16384
0x73350000 - 0x733a2fff  OLEACC.dll  7.2.10240.17146
0x736d0000 - 0x736e5fff  USP10.dll  10.0.10240.16384
0x73eb0000 - 0x73ec8fff  USERENV.dll  10.0.10240.16603
0x73ed0000 - 0x73edefff  WTSAPI32.dll  10.0.10240.16384
0x73ef0000 - 0x73ef9fff  netutils.dll  10.0.10240.16384
0x73f00000 - 0x73f1bfff  srvcli.dll  10.0.10240.16724
0x73f20000 - 0x73f2ffff  wkscli.dll  10.0.10240.16724
0x73f60000 - 0x73f72fff  NETAPI32.dll  10.0.10240.16724
0x73f90000 - 0x74198fff  COMCTL32.dll  6.10.10240.17184
0x74280000 - 0x742a0fff  DEVOBJ.dll  10.0.10240.16384
0x742e0000 - 0x742fafff  bcrypt.dll  10.0.10240.17202
0x74370000 - 0x74377fff  VERSION.dll  10.0.10240.16384
0x74380000 - 0x743d8fff  bcryptPrimitives.dll  10.0.10240.17202
0x743e0000 - 0x743e9fff  CRYPTBASE.dll  10.0.10240.16384
0x743f0000 - 0x7440dfff  SspiCli.dll  10.0.10240.17113
0x74410000 - 0x744f9fff  ole32.dll  10.0.10240.17184
0x74500000 - 0x74541fff  WINTRUST.dll  10.0.10240.17184
0x74550000 - 0x7455dfff  MSASN1.dll  10.0.10240.16384
0x74560000 - 0x746d5fff  KERNELBASE.dll  10.0.10240.17184
0x746e0000 - 0x74722fff  sechost.dll  10.0.10240.16384
0x74730000 - 0x7486ffff  USER32.dll  10.0.10240.17202
0x74a80000 - 0x74b6ffff  KERNEL32.DLL  10.0.10240.17113  (WARNING: No symbols, wkernel32.pdb, 9090205DDD914D0C9346D44A073969B41)
0x74b70000 - 0x74ce4fff  CRYPT32.dll  10.0.10240.17184
0x74cf0000 - 0x74d6afff  ADVAPI32.dll  10.0.10240.16644
0x74e30000 - 0x74e65fff  cfgmgr32.dll  10.0.10240.16384
0x74e70000 - 0x74f2dfff  msvcrt.dll  7.0.10240.16384
0x74f30000 - 0x74f3efff  profapi.dll  10.0.10240.16384
0x74fa0000 - 0x750bffff  MSCTF.dll  10.0.10240.17184
0x750c0000 - 0x750cbfff  kernel.appcore.dll  10.0.10240.16384
0x750d0000 - 0x7515cfff  shcore.dll  10.0.10240.17202
0x752d0000 - 0x752d5fff  PSAPI.DLL  10.0.10240.16384
0x75300000 - 0x7532afff  IMM32.DLL  10.0.10240.16384
0x75330000 - 0x766eefff  SHELL32.dll  10.0.10240.17202
0x766f0000 - 0x76784fff  OLEAUT32.dll  10.0.10240.17113
0x768b0000 - 0x768f3fff  powrprof.dll  10.0.10240.16384
0x76900000 - 0x76a4cfff  GDI32.dll  10.0.10240.17202
0x76a50000 - 0x76f2bfff  windows.storage.dll  10.0.10240.17184
0x76f90000 - 0x7703bfff  RPCRT4.dll  10.0.10240.16841
0x770d0000 - 0x77289fff  combase.dll  10.0.10240.17202
0x77290000 - 0x772d3fff  shlwapi.dll  10.0.10240.16384
0x772e0000 - 0x77458fff  ntdll.dll  10.0.10240.17184  (WARNING: No symbols, wntdll.pdb, 98A5B7114B3849F9B9DC4635FD0489591)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by 1815368076** [comment]
How to solve？thanks
