### ISSUE TITLE
Crash dump file gets created inside C:\Users\<Username>\AppData\Local\Chromium\User Data\Crashpad\reports folder

### ISSUE THREAD

**Issue by ShobanaV** [nwjs/nw.js#5585]
Hi,

I am using node-webkit 0.19.3 in Windows 7. When the app crashes, the crash dump files are getting created inside "C:\Users\<Username>\AppData\Local\Chromium\User Data\Crashpad\reports" folder, instead of app-specific path.

Is this expected?

**Comment by ghostoy** [comment]
Close as duplicate of #5248.
