### ISSUE TITLE
webview tag Error loading page layout!

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5589]
@rogerwang @ghostoy 
Layout error when I want to load a web page with WebView tag!
I set the width of the WebView through the CSS, but I do not agree with the desired effect, please check whether there is a problem.
I have a SkyDrive I screenshots and source files are uploaded to the address below is the connection sharing, which can directly browse pictures online!

http://pan.baidu.com/s/1kUZhpXX

**Comment by rogerwang** [comment]
Does it work well in webview of a Chrome App?

**Comment by phpjishu** [comment]
The 0.13.* version is good!

**Comment by Christywl** [comment]
Reproduced on Linux with nwjs-v0.21.2.

**Comment by rogerwang** [comment]
Please upload the sample again. The link in the report is not working.

**Comment by phpjishu** [comment]
thanks!
