### ISSUE TITLE
Crash when continuously call window api

### ISSUE THREAD

**Issue by cecilpeng** [nwjs/nw.js#5595]
I'm using nwjs0.17.6 win64 sdk. It came a problem when I run a small script to continuously open, rezise and close window. I don't know how it works. Can you help me?

[dump.txt](https://github.com/nwjs/nw.js/files/675505/dump.txt)

...........................
Operating system: Windows NT
                  6.1.7601 23572
CPU: amd64
     family 6 model 78 stepping 3
     4 CPUs

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0xffffffffffffffff

Thread 0 (crashed)
 0  nw.dll + 0x3efa820
    rbx = 0x000007fecf41c8b0   r12 = 0x6666666666666667
    r13 = 0x000000000043aea0   r14 = 0x000007fecec96aa8
    r15 = 0x000000000043afd8   rip = 0x000007fece73a820
    rsp = 0x00000000001ee5f0   rbp = 0x00000000001ee699
    Found by: given as instruction pointer in context
 1  nw.dll + 0x4bdc8af
    rip = 0x000007fecf41c8b0   rsp = 0x00000000001ee618
    rbp = 0x00000000001ee699
    Found by: stack scanning
 2  nw.dll + 0x228f7fb
    rip = 0x000007feccacf7fc   rsp = 0x00000000001ee620
    rbp = 0x00000000001ee699
    Found by: stack scanning
 3  nw.dll + 0x227bb4a
    rip = 0x000007feccabbb4b   rsp = 0x00000000001ee660
    rbp = 0x00000000001ee699
    Found by: stack scanning
 4  nw.dll + 0x28b9ce5
    rip = 0x000007fecd0f9ce6   rsp = 0x00000000001ee670
    rbp = 0x00000000001ee699
    Found by: stack scanning
 5  nw.dll + 0x3efb025
    rip = 0x000007fece73b026   rsp = 0x00000000001ee6a8
    Found by: stack scanning
 6  nw.dll + 0x221d678
    rip = 0x000007fecca5d679   rsp = 0x00000000001ee700
    Found by: stack scanning
 7  uxtheme.dll + 0x1380
    rip = 0x000007fefb6d1381   rsp = 0x00000000001ee710
    Found by: stack scanning
 8  USER32.dll + 0x188cb
    rip = 0x00000000770d88cc   rsp = 0x00000000001ee730
    Found by: stack scanning
 9  USER32.dll + 0x175af
    rip = 0x00000000770d75b0   rsp = 0x00000000001ee750
    Found by: stack scanning
10  USER32.dll + 0x175e9
    rip = 0x00000000770d75ea   rsp = 0x00000000001ee780
    Found by: stack scanning
11  uxtheme.dll + 0x11cd
    rip = 0x000007fefb6d11ce   rsp = 0x00000000001ee790
    Found by: stack scanning
12  uxtheme.dll + 0x1643
    rip = 0x000007fefb6d1644   rsp = 0x00000000001ee7c0
    Found by: stack scanning
13  uxtheme.dll + 0x1444
    rip = 0x000007fefb6d1445   rsp = 0x00000000001ee870
    Found by: stack scanning
14  USER32.dll + 0x1758b
    rip = 0x00000000770d758c   rsp = 0x00000000001ee8b0
    Found by: stack scanning
15  USER32.dll + 0x188cb
    rip = 0x00000000770d88cc   rsp = 0x00000000001ee8c0
    Found by: stack scanning
16  nw.dll + 0x2237ca5
    rip = 0x000007fecca77ca6   rsp = 0x00000000001ee8d0
    Found by: stack scanning
17  USER32.dll + 0x17938
    rip = 0x00000000770d7939   rsp = 0x00000000001ee8e0
    Found by: stack scanning
18  uxtheme.dll + 0x133b
    rip = 0x000007fefb6d133c   rsp = 0x00000000001ee8f0
    Found by: stack scanning
19  uxtheme.dll + 0x11cd
    rip = 0x000007fefb6d11ce   rsp = 0x00000000001ee920
    Found by: stack scanning
20  uxtheme.dll + 0x2b8a
    rip = 0x000007fefb6d2b8b   rsp = 0x00000000001ee950
    Found by: stack scanning
21  nw.dll + 0x284b431
    rip = 0x000007fecd08b432   rsp = 0x00000000001ee990
    Found by: stack scanning
22  nw.dll + 0x284a9ba
    rip = 0x000007fecd08a9bb   rsp = 0x00000000001ee9c0
    Found by: stack scanning
23  USER32.dll + 0x19bda
    rip = 0x00000000770d9bdb   rsp = 0x00000000001eea00
    Found by: stack scanning
24  USER32.dll + 0x19b2e
    rip = 0x00000000770d9b2f   rsp = 0x00000000001eea90
    Found by: stack scanning
25  USER32.dll + 0x19bda
    rip = 0x00000000770d9bdb   rsp = 0x00000000001eea98
    Found by: stack scanning
26  USER32.dll + 0x1729a
    rip = 0x00000000770d729b   rsp = 0x00000000001eeac0
    Found by: stack scanning
27  nw.dll + 0x284a9ab
    rip = 0x000007fecd08a9ac   rsp = 0x00000000001eead0
    Found by: stack scanning
28  uxtheme.dll + 0x1444
    rip = 0x000007fefb6d1445   rsp = 0x00000000001eeb10
    Found by: stack scanning
29  USER32.dll + 0x167ff
    rip = 0x00000000770d6800   rsp = 0x00000000001eeb20
    Found by: stack scanning
30  USER32.dll + 0x19a85
    rip = 0x00000000770d9a86   rsp = 0x00000000001eeb40
    Found by: stack scanning
31  nw.dll + 0x284a9ab
    rip = 0x000007fecd08a9ac   rsp = 0x00000000001eeb48
    Found by: stack scanning
32  USER32.dll + 0x18cb0
    rip = 0x00000000770d8cb1   rsp = 0x00000000001eeb70
    Found by: stack scanning
33  ntdll.dll + 0x4bc64
    rip = 0x000000007732bc65   rsp = 0x00000000001eeb80
    Found by: stack scanning
34  USER32.dll + 0x16e19
    rip = 0x00000000770d6e1a   rsp = 0x00000000001eebb8
    Found by: stack scanning
35  nw.dll + 0x284a9ab
    rip = 0x000007fecd08a9ac   rsp = 0x00000000001eec00
    Found by: stack scanning
36  ntdll.dll + 0x3c90f
    rip = 0x000000007731c910   rsp = 0x00000000001eec08
    Found by: stack scanning
37  nw.dll + 0x1f6e8b3
    rip = 0x000007fecc7ae8b4   rsp = 0x00000000001eec10
    Found by: stack scanning
38  nw.dll + 0x284a9ba
    rip = 0x000007fecd08a9bb   rsp = 0x00000000001eec60
    Found by: stack scanning
39  ntdll.dll + 0x1103c7
    rip = 0x00000000773f03c8   rsp = 0x00000000001eec68
    Found by: stack scanning
40  ntdll.dll + 0x4dd47
    rip = 0x000000007732dd48   rsp = 0x00000000001eeca0
    Found by: stack scanning
41  nw.dll + 0x478fb2f
    rip = 0x000007fecefcfb30   rsp = 0x00000000001eecd8
    Found by: stack scanning
42  nw.dll + 0x1f6e46a
    rip = 0x000007fecc7ae46b   rsp = 0x00000000001eece0
    Found by: stack scanning
43  kernel32.dll + 0x21a09
    rip = 0x00000000771e1a0a   rsp = 0x00000000001eed60
    Found by: stack scanning
44  nw.dll + 0x2237ca5
    rip = 0x000007fecca77ca6   rsp = 0x00000000001eeda0
    Found by: stack scanning
45  nw.dll + 0x1f713c1
    rip = 0x000007fecc7b13c2   rsp = 0x00000000001eedd0
    Found by: stack scanning
46  USER32.dll + 0x188cb
    rip = 0x00000000770d88cc   rsp = 0x00000000001eee00
    Found by: stack scanning
47  nw.dll + 0x2237ca5
    rip = 0x000007fecca77ca6   rsp = 0x00000000001eee10
    Found by: stack scanning
48  USER32.dll + 0x17938
    rip = 0x00000000770d7939   rsp = 0x00000000001eee20
    Found by: stack scanning
49  uxtheme.dll + 0x133b
    rip = 0x000007fefb6d133c   rsp = 0x00000000001eee30
    Found by: stack scanning
50  uxtheme.dll + 0x11cd
    rip = 0x000007fefb6d11ce   rsp = 0x00000000001eee60
    Found by: stack scanning
51  nw.dll + 0x2219cea
    rip = 0x000007fecca59ceb   rsp = 0x00000000001eee90
    Found by: stack scanning
52  nw.dll + 0x2219c5d
    rip = 0x000007fecca59c5e   rsp = 0x00000000001eeec0
    Found by: stack scanning
53  nw.dll + 0x2219cea
    rip = 0x000007fecca59ceb   rsp = 0x00000000001eeed0
    Found by: stack scanning
54  ntdll.dll + 0x24b6e
    rip = 0x0000000077304b6f   rsp = 0x00000000001eef10
    Found by: stack scanning
55  USER32.dll + 0x19bda
    rip = 0x00000000770d9bdb   rsp = 0x00000000001eef40
    Found by: stack scanning
56  USER32.dll + 0x1758b
    rip = 0x00000000770d758c   rsp = 0x00000000001eef50
    Found by: stack scanning
57  nw.dll + 0x228af93
    rip = 0x000007feccacaf94   rsp = 0x00000000001eef70
    Found by: stack scanning
58  ntdll.dll + 0x24bea
    rip = 0x0000000077304beb   rsp = 0x00000000001eefa0
    Found by: stack scanning
59  USER32.dll + 0x19bda
    rip = 0x00000000770d9bdb   rsp = 0x00000000001eefe0
    Found by: stack scanning
60  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef008
    Found by: stack scanning
61  kernel32.dll + 0x21a09
    rip = 0x00000000771e1a0a   rsp = 0x00000000001ef020
    Found by: stack scanning
62  nw.dll + 0x2c58c2c
    rip = 0x000007fecd498c2d   rsp = 0x00000000001ef050
    Found by: stack scanning
63  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef098
    Found by: stack scanning
64  nw.dll + 0x221cadf
    rip = 0x000007fecca5cae0   rsp = 0x00000000001ef0b0
    Found by: stack scanning
65  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef0c8
    Found by: stack scanning
66  nw.dll + 0x365229f
    rip = 0x000007fecde922a0   rsp = 0x00000000001ef108
    Found by: stack scanning
67  nw.dll + 0x4bdc8ff
    rip = 0x000007fecf41c900   rsp = 0x00000000001ef110
    Found by: stack scanning
68  nw.dll + 0x4bdc8af
    rip = 0x000007fecf41c8b0   rsp = 0x00000000001ef118
    Found by: stack scanning
69  nw.dll + 0x3efb025
    rip = 0x000007fece73b026   rsp = 0x00000000001ef128
    Found by: stack scanning
70  USER32.dll + 0xb96b
    rip = 0x00000000770cb96c   rsp = 0x00000000001ef140
    Found by: stack scanning
71  nw.dll + 0x365229f
    rip = 0x000007fecde922a0   rsp = 0x00000000001ef158
    Found by: stack scanning
72  nw.dll + 0x44100df
    rip = 0x000007fecec500e0   rsp = 0x00000000001ef160
    Found by: stack scanning
73  nw.dll + 0x441008f
    rip = 0x000007fecec50090   rsp = 0x00000000001ef168
    Found by: stack scanning
74  USER32.dll + 0xb935
    rip = 0x00000000770cb936   rsp = 0x00000000001ef170
    Found by: stack scanning
75  nw.dll + 0x1f77d94
    rip = 0x000007fecc7b7d95   rsp = 0x00000000001ef178
    Found by: stack scanning
76  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef188
    Found by: stack scanning
77  nw.dll + 0x2289e67
    rip = 0x000007feccac9e68   rsp = 0x00000000001ef1a0
    Found by: stack scanning
78  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef1b0
    Found by: stack scanning
79  nw.dll + 0x225bf63
    rip = 0x000007fecca9bf64   rsp = 0x00000000001ef1d0
    Found by: stack scanning
80  nw.dll + 0x228a9b3
    rip = 0x000007feccaca9b4   rsp = 0x00000000001ef210
    Found by: stack scanning
81  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef218
    Found by: stack scanning
82  nw.dll + 0x221d2dd
    rip = 0x000007fecca5d2de   rsp = 0x00000000001ef230
    Found by: stack scanning
83  nw.dll + 0x2271abd
    rip = 0x000007feccab1abe   rsp = 0x00000000001ef260
    Found by: stack scanning
84  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef270
    Found by: stack scanning
85  nw.dll + 0x365229f
    rip = 0x000007fecde922a0   rsp = 0x00000000001ef280
    Found by: stack scanning
86  nw.dll + 0x206fd7b
    rip = 0x000007fecc8afd7c   rsp = 0x00000000001ef2b0
    Found by: stack scanning
87  nw.dll + 0x4a9405
    rip = 0x000007fecace9406   rsp = 0x00000000001ef330
    Found by: stack scanning
88  nw.dll + 0x4aaaca
    rip = 0x000007fecaceaacb   rsp = 0x00000000001ef380
    Found by: stack scanning
89  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef3a0
    Found by: stack scanning
90  nw.dll + 0x4a5696
    rip = 0x000007fecace5697   rsp = 0x00000000001ef3b0
    Found by: stack scanning
91  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef3c0
    Found by: stack scanning
92  nw.dll + 0x1f2eacd
    rip = 0x000007fecc76eace   rsp = 0x00000000001ef430
    Found by: stack scanning
93  nw.dll + 0x4400a2f
    rip = 0x000007fecec40a30   rsp = 0x00000000001ef448
    Found by: stack scanning
94  nw.dll + 0x1f2e9bf
    rip = 0x000007fecc76e9c0   rsp = 0x00000000001ef470
    Found by: stack scanning
95  0x13f99ffff
    rip = 0x000000013f9a0000   rsp = 0x00000000001ef4f8
    Found by: stack scanning
96  nw.dll + 0x1f2dd97
    rip = 0x000007fecc76dd98   rsp = 0x00000000001ef510
    Found by: stack scanning
97  0x13f99ffff
    rip = 0x000000013f9a0000   rsp = 0x00000000001ef518
    Found by: stack scanning
98  nw.dll + 0x3f4a1ff
    rip = 0x000007fece78a200   rsp = 0x00000000001ef530
    Found by: stack scanning
99  nw.dll + 0x8f961
    rip = 0x000007feca8cf962   rsp = 0x00000000001ef540
    Found by: stack scanning
100  0x13f99ffff
    rip = 0x000000013f9a0000   rsp = 0x00000000001ef548
    Found by: stack scanning
101  nw.exe + 0x3741f
    rip = 0x000000013f9d7420   rsp = 0x00000000001ef550
    Found by: stack scanning
102  nw.exe + 0x95af3
    rip = 0x000000013fa35af4   rsp = 0x00000000001ef560
    Found by: stack scanning
103  0x13f99ffff
    rip = 0x000000013f9a0000   rsp = 0x00000000001ef570
    Found by: stack scanning
104  nw.dll + 0x3f4baef
    rip = 0x000007fece78baf0   rsp = 0x00000000001ef588
    Found by: stack scanning
105  nw.dll + 0x46ef61f
    rip = 0x000007fecef2f620   rsp = 0x00000000001ef590
    Found by: stack scanning
106  nw.dll + 0x4dd2657
    rip = 0x000007fecf612658   rsp = 0x00000000001ef598
    Found by: stack scanning
107  nw.exe + 0xdf65f
    rip = 0x000000013fa7f660   rsp = 0x00000000001ef5c0
    Found by: stack scanning
108  nw.exe + 0x329e5
    rip = 0x000000013f9d29e6   rsp = 0x00000000001ef5d0
    Found by: stack scanning
109  nw.dll + 0x8f8df
    rip = 0x000007feca8cf8e0   rsp = 0x00000000001ef5e0
    Found by: stack scanning
110  nw_elf.dll + 0x55b67
    rip = 0x000007feef035b68   rsp = 0x00000000001ef5f8
    Found by: stack scanning
111  nw.exe + 0xdfca7
    rip = 0x000000013fa7fca8   rsp = 0x00000000001ef610
    Found by: stack scanning
112  0x13f99ffff
    rip = 0x000000013f9a0000   rsp = 0x00000000001ef648
    Found by: stack scanning
113  nw.exe + 0x39c5e
    rip = 0x000000013f9d9c5f   rsp = 0x00000000001ef660
    Found by: stack scanning
114  nw.exe + 0xb6384
    rip = 0x000000013fa56385   rsp = 0x00000000001ef690
    Found by: stack scanning
115  nw.exe + 0x32d55
    rip = 0x000000013f9d2d56   rsp = 0x00000000001ef6c0
    Found by: stack scanning
116  0x13f99ffff
    rip = 0x000000013f9a0000   rsp = 0x00000000001ef6e0
    Found by: stack scanning
117  nw.exe + 0x321f4
    rip = 0x000000013f9d21f5   rsp = 0x00000000001ef6f0
    Found by: stack scanning
118  nw.exe + 0xdfca7
    rip = 0x000000013fa7fca8   rsp = 0x00000000001ef730
    Found by: stack scanning
119  nw.exe + 0xb6384
    rip = 0x000000013fa56385   rsp = 0x00000000001ef7a0
    Found by: stack scanning
120  nw.exe + 0x122927
    rip = 0x000000013fac2928   rsp = 0x00000000001ef7c8
    Found by: stack scanning
121  nw.exe + 0x2bff3
    rip = 0x000000013f9cbff4   rsp = 0x00000000001ef7d0
    Found by: stack scanning
122  ntdll.dll + 0x2532d
    rip = 0x000000007730532e   rsp = 0x00000000001ef7e0
    Found by: stack scanning
123  nw.exe + 0xcd7ad
    rip = 0x000000013fa6d7ae   rsp = 0x00000000001ef800
    Found by: stack scanning
124  nw.exe + 0x2b8af
    rip = 0x000000013f9cb8b0   rsp = 0x00000000001ef818
    Found by: stack scanning
125  nw.exe + 0xcdc05
    rip = 0x000000013fa6dc06   rsp = 0x00000000001ef830
    Found by: stack scanning
126  nw.exe + 0xdd527
    rip = 0x000000013fa7d528   rsp = 0x00000000001ef838
    Found by: stack scanning
127  nw.exe + 0xb7159
    rip = 0x000000013fa5715a   rsp = 0x00000000001ef870
    Found by: stack scanning
128  nw.exe + 0xb66c0
    rip = 0x000000013fa566c1   rsp = 0x00000000001ef880
    Found by: stack scanning
129  nw.exe + 0x122f9f
    rip = 0x000000013fac2fa0   rsp = 0x00000000001ef888
    Found by: stack scanning
130  nw.exe + 0xdd527
    rip = 0x000000013fa7d528   rsp = 0x00000000001ef890
    Found by: stack scanning
131  nw.exe + 0xb6c15
    rip = 0x000000013fa56c16   rsp = 0x00000000001ef910
    Found by: stack scanning
132  kernel32.dll + 0x159cc
    rip = 0x00000000771d59cd   rsp = 0x00000000001ef950
    Found by: stack scanning
133  ntdll.dll + 0x2a560
    rip = 0x000000007730a561   rsp = 0x00000000001ef980
    Found by: stack scanning
134  kernel32.dll + 0x9baaf
    rip = 0x000000007725bab0   rsp = 0x00000000001ef9a8
    Found by: stack scanning
135  kernel32.dll + 0x9baaf
    rip = 0x000000007725bab0   rsp = 0x00000000001ef9b0
    Found by: stack scanning

**Comment by kailniris** [comment]
Please provide a test case

**Comment by ghostoy** [comment]
Could you upload the original `.dmp` file?

**Comment by cecilpeng** [comment]
you can download it from
http://oixk4v2c8.bkt.clouddn.com/crash.dmp

**Comment by ghostoy** [comment]
@cecilpeng Looks like it is a duplicate of #4918.

**Comment by cecilpeng** [comment]
thx. It crashed when I tried to close window twice at the same time (or approximately).

**Comment by cecilpeng** [comment]
I will close it, duplicate of #4918.
