### ISSUE TITLE
Why do I use the--no-proxy-server parameter to start, websocket fail?

### ISSUE THREAD

**Issue by mynameiswf** [nwjs/nw.js#5596]
Because my computer is configured with a local proxy, so I use the--no-proxy-server parameter to start nwjs. But websocket communication fails, the message was intercepted by the Agency. Can you solve this problem?

**Comment by ghostoy** [comment]
Could you provide a sample app to reproduce this issue? And also information of your NW.js version and OS.

**Comment by mynameiswf** [comment]
Nwjs version is v0.12.3, the operating system is WinXP. I set up a proxy address in IE browser, and nwjs apply inside the websocket connection does not respond. The same page is placed directly into the chrome browser running on, use the--no-proxy-server parameter to function properly. Websocket connection is very simple, connect to an address and port on the sent string, receive the string.

**Comment by ghostoy** [comment]
Could you test if it works on 0.14.7? We don't support 0.12.3 any more.

**Comment by Christywl** [comment]
@mynameiswf , is this still reproduced in your environment? If yes, could you please provide a sample to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is provided.
