### ISSUE TITLE
macOS app fails to launch a second time via Launchpad or the open command even after the first instance has exited

### ISSUE THREAD

**Issue by mjethani** [nwjs/nw.js#5598]
__Platform__: OS X Yosemite 10.10.5
__NW.js version__: 0.19.3

__Steps to reproduce the problem__:

 1.  Unzip [Hello World.zip](https://github.com/nwjs/nw.js/files/676975/Hello.World.zip) in the `/Applications` folder
 2.  Run `open /Applications/Hello\ World.app`
 3.  Run `open /Applications/Hello\ World.app` again
 4.  Close the app
 5.  Run `open /Applications/Hello\ World.app` again

__Expected behavior__: The app launches again

__Actual behavior__: Nothing happens, the `run.sh` script doesn't even get called!

**Comment by mjethani** [comment]
I've done some investigation on this.

First of all, here's a Python script for viewing Launch Services's view of the currently running instances of the app:

```python
# helloworldinstances.py

from AppKit import NSWorkspace

for app in NSWorkspace.sharedWorkspace().runningApplications():
    if app.bundleIdentifier() == 'com.example.HelloWorldApp':
        print app.bundleIdentifier()
        print app.processIdentifier()
        print app.launchDate()
        print app.isFinishedLaunching()
        print app.isTerminated()
        print app.isActive()
        print app.activationPolicy()
```

After we launch the app for the first time using `open /Applications/Hello\ World.app`, we get the following output from the script:

```
com.example.HelloWorldApp
12075
2016-12-29 11:14:47 +0000
True
False
False
0
```

Here 12075 is the process ID.

```console
$ ps -wxp 12075
 PID TTY           TIME CMD
12075 ??         0:01.00 /Applications/nwjs.app/Contents/MacOS/nwjs /Applications/Hello World.app/Contents/MacOS/helloworld
```

Now when we try to launch the app a second time (while the first instance is still running), it doesn't launch. This is correct behavior.

But this is what we see from the script:

```
com.example.HelloWorldApp
12075
2016-12-29 11:14:47 +0000
True
False
False
0
com.example.HelloWorldApp
12073
2016-12-29 11:17:56 +0000
False
False
False
1
```

Launch Services has added a new entry for the app, referring to the process ID of the parent process.

```console
$ ps -wxp 12073
  PID TTY           TIME CMD
12073 ??         0:00.00 /bin/bash /Applications/Hello World.app/Contents/MacOS/run.sh
```

This is where the bug is.

When we quit the app, both processes die as expected.

```console
$ kill -0 12075
-bash: kill: (12075) - No such process
$ kill -0 12073
-bash: kill: (12073) - No such process
```

But the script gives this output:

```
com.example.HelloWorldApp
12073
2016-12-29 11:17:56 +0000
False
False
False
1
```

Launch Services still thinks the app is running!

After this point, it is impossible to launch the app again using the `open` command or via Launchpad.

**Comment by ghostoy** [comment]
It's not the supported way to package the app. Please follow the document of [Package and Distribute](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/).

**Comment by shamun** [comment]
I have downloaded the latest stable on my OSX 10.11.6 (15G1212) and all works fine. Must be your packaging related issue.

**Comment by Christywl** [comment]
@mjethani , could you please retest according to ghostoy's comments?

**Comment by shamun** [comment]
It works with me, i use OSX general packaging by modifying the C++ source compile/build.

**Comment by rogerwang** [comment]
close until more information is available.
