### ISSUE TITLE
window.print() does not work

### ISSUE THREAD

**Issue by niloy** [nwjs/nw.js#56]
Tested on Ubuntu 12.04
nw version: 0.2.5

**Comment by JaredCubilla** [comment]
+1 for Print Preview

**Comment by inluxc** [comment]
I have the last version and can not print in windows with mozilla pdfjs. But it works in mac and linux. Pdfjs is in a iframe.

**Comment by mahavirjain** [comment]
Any update regarding Print Preview Feature.?

**Comment by consindo** [comment]
No.

**Comment by geekuillaume** [comment]
+1

**Comment by majodev** [comment]
+1

**Comment by aramirez92** [comment]
+1 for silent printing

**Comment by hvva** [comment]
NW 0.12.0 - window.print() stopped working.

**Comment by baconface** [comment]
I am 1+ for silent printing.

However. I might add printing and even silent printing can be done in NW.js using node. Possible methods:
+ Use a printing NPM
+ Execute a batch or shell script by calling it with node.js/io.js
+ Send one with node.js/io.js via the [IPP](http://en.wikipedia.org/wiki/Internet_Printing_Protocol) / network printer

**Comment by simoami** [comment]
+1 for silent printing!

**Comment by villanus** [comment]
+1

**Comment by joshuaterrill** [comment]
+1 what happened in 0.12.0 that made printing stop working?

**Comment by pettersonfaria** [comment]
+1 for silent print

**Comment by keanass** [comment]
+1

**Comment by rockedpanda** [comment]
+1 for Print Preview

**Comment by GnorTech** [comment]
@rockedpanda print preview is supported in nw 0.13.

I'm closing the issue. And silent printing is tracked in #1263
