### ISSUE TITLE
How to access 'nw' in the new window created by 'nw.Window.open'

### ISSUE THREAD

**Issue by linb** [nwjs/nw.js#5600]
When I used 'nw.Window.open' to open a window, I can't use 'nw' in the new window.

any idea?
----------------------------
error message: Uncaught ReferenceError: nw is not defined

**Comment by kailniris** [comment]
What version are you using?
Provide an example how did you opened the new window and how did you tried access the nw variable

**Comment by linb** [comment]
It's version "0.19.3"

code to open new window:
nw.Window.open('test.html');

in test.html
<script>
alert(nw.process.version);
</sciript>

**Comment by kailniris** [comment]
try the following
`<script defer> alert(nw.process.version); </script>`
Or wait for the window to fully load before access nw variable.
The problem might occur cuz the nw variable is not set up at the point you are trying to access it.

**Comment by linb** [comment]
It didn't work. 

Press F12 to show the debug window, type

nw

=>

VM478:1 Uncaught ReferenceError: nw is not defined
    at <anonymous>:1:1

**Comment by kailniris** [comment]
Can you upload a full test case pls

**Comment by linb** [comment]
[test.zip](https://github.com/nwjs/nw.js/files/678528/test.zip)

In my app, I have to open some html in local disk. That's the reason I used 'file:///xxxxx'.

**Comment by intralizee** [comment]
If you replace the code in your index.html for opening a new window with something like this:
```
nw.Window.open('test.html', {focus:true}, function(new_window) {
});
```
You will be able to get the version from nw.process.version successfully.

**Comment by kailniris** [comment]
I think the op stated he wants to open html files from the filesystem and not from the working dir. Thats why he used the file protocol

**Comment by linb** [comment]
Yes, I have to open an html file out of the working dir. Can I access 'nw' in this case?

**Comment by intralizee** [comment]
My mistake and I noticed it's also not possible to send messages to a window that is opened by the file protocol as well.
You could use socket.io and with a local port connection to execute tasks between file protocol windows and the main window which has access to nw for the meantime.

**Comment by linb** [comment]
I don't want to send or receive message to the main window.

I just want to use nw/nodejs functions in the new window opened by the file protocol.

**Comment by linb** [comment]
Any one else help me with this?

**Comment by linb** [comment]
I found a pending issue: https://github.com/nwjs/nw.js/issues/4806#event-782332903

**Comment by kailniris** [comment]
Looks like this is a limitation.
For a workaround you could use the fs module to copy the html you want to open to a temp dir in your nw.js working dir then open it in a new window.

**Comment by cecilemuller** [comment]
I had a similar issue with pages launched using `nw.Window.open`, despite having `"chromium-args": "--mixed-context"`.

In my case, it turned out it also needed `"node-remote": ["<all_urls>"]` (or the list of urls you're loading).
