### ISSUE TITLE
Help: How can i focus another application in win10

### ISSUE THREAD

**Issue by cecilpeng** [nwjs/nw.js#5601]
I need launch powerpoint from nw.js. I run a C# process to control powerpoint on windows. When i run the process by cmd, it can do well. However, powerpoint could not be focused properly when i use nw in a window to run it. it's ok on win7, but requires an attention on win10. Can anyone give me some ideas?

![p28hgahih2 r3 i4 ya o9](https://cloud.githubusercontent.com/assets/3832621/21560160/63200d82-ce95-11e6-95b2-859c96e798eb.png)

**Comment by intralizee** [comment]
I don't understand what you mean by "when i use nw in a window to run it" and I personally haven't written much code that functions with powerpoint.

Yet, you say that C# process you wrote can control powerpoint and I assume gain focus to powerpoint?
Why not just bundle the C# process with your nw.js app and launch the C# process by some code.

```
var PowerPointHelper;
var spawn = require('child_process').spawn;
var os = require('os'); // System info.
if (os.platform() == 'darwin')
   PowerPointHelper = spawn('./child_process/mac/PowerPointHelper');
else if (os.platform() == 'win32')
   PowerPointHelper = spawn('./child_process/windows/PowerPointHelper.exe');
PowerPointHelper.stdout.on('data', function(data) {
   console.log('stdout: ' + data);
});
PowerPointHelper.stderr.on('data', function(data) {
   console.log('stdout: ' + data);
});
PowerPointHelper.on('close', function(data) {
   console.log('closing data: ' + data);
 });
PowerPointHelper.on('exit', function (data) {
   console.log('exit data: ' + data);
});
```

You can send messages/data back and forth between your C# process and nw.js app for handling tasks that need to be done when user does something in nw.js or whatever.

On mac you can gain focus to windows with objective c code if you can find the application's bundle id.
I'm not sure if you're just targeting every platform or just window specific platforms.

There might be some other way to do with nw.js but if you're comfortable with C# you might like this approach.

**Comment by cecilpeng** [comment]
Very appreciate for your answer. I shall write some more.

> I don't understand what you mean by "when i use nw in a window to run it" and I personally haven't written much code that functions with powerpoint.

I wrote a pptListener just like you wrote, attaching to a c# child_process. I can receive data, or send message through stdio.
I use the the PowerpointHelper to write focus command (pptListener.focus() === stdin.write('ppt.focus')) in the nw.js dev-tools. It's ok on win7, but requests an attention on win10.

![image](https://cloud.githubusercontent.com/assets/3832621/21580014/a72ca0f2-d00d-11e6-9ba2-fa4eb30a66ae.png)

 This is a simple code to activate powerpoint. 
```C#
Context.App.ActivePresentation.SlideShowWindow.Activate()
WindowsUtils.ShowPowerPointView()
```

**Comment by cecilpeng** [comment]
I am comfused that what is the difference between cmd and nwjs. I don't know if nwjs support focus another application from a nwjs window. Or, i wrote some code wrong?

**Comment by cecilpeng** [comment]
http://oixk4v2c8.bkt.clouddn.com/TestFocusPowerpoint.zip

This is the sample of Activating powerpoint from cmd or nw.js.

Test from cmd:
1. input `node pages/PPTControl/PPTControl.node.js` in cmd
2. input `ppt.active` after powerpoint is shown

Test from nw.js:
1. copy the unzipped files to nw
2. run nw.exe
3. load -> play -> focus, just follow the instruction of the page.

Then, you can see that it is so difficult to focus powerpoint with nw.js in win10.

I need your help!

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
