### ISSUE TITLE
Scrolling in webview is too sensitive

### ISSUE THREAD

**Issue by bambooCZ** [nwjs/nw.js#5603]
Scrolling in webview is too sensitive. Only touchpads seems to be a problem. Everything is fine, when using standard mouse with wheel. Problem occurs on Mac and Windows. Don't know about Linux.

NWjs 18 was fine, NWjs 19 has this bug.

I am attaching minimal example where it is possible to test it. It is possible to launch it as an chrome app, or in NWjs. The bug exists only in NWjs. When running as an Chrome app, everything is fine.

[furious-scrolling.zip](https://github.com/nwjs/nw.js/files/680837/furious-scrolling.zip)

**Comment by bambooCZ** [comment]
NWjs v0.20.0-beta1 has this bug also

**Comment by martinsuchan** [comment]
Same problem here. Scrolling on touchpad is about twice as fast in NW.js 19.x.

**Comment by bambooCZ** [comment]
Problem has appeared in NWjs v0.19.2. NWjs v0.19.1 is OK

**Comment by janRucka** [comment]
I am another victim. It is really happening...

**Comment by rogerwang** [comment]
@bambooCZ thanks for the report. I can verify it but the difference is not so much here with my thinkpad.

With 0.19.2 if I use the command line switch `--isolate-extensions` then it seems to behave in the same way with 0.19.1. Can you verify that?

**Comment by bambooCZ** [comment]
@rogerwang I can confirm that the problem disappears when I use ```--isolate-extensions```. However I think scrolling should not be influenced by this switch.

BTW How does your touchpad work for scrolling? Does it scroll using two fingers (like it is common on Mac) or does it have a scrollbar on the edge of the pad? I've tested only two fingers scroll, because I don't have access to a touchpad with a scrollbar on the edge.

**Comment by rogerwang** [comment]
I'll check why this affects scrolling. but this looks like an upstream
issue since the changes between 0.19.1 and 0.19.2 are mostly upgrading
Chromium from 55.0.2883.75 to 55.0.2883.87. And the switch change is among
the few changes upstream had made.

**Comment by rogerwang** [comment]
Btw I'm using 2 fingers scrolling.

**Comment by janRucka** [comment]
The scrolling works fine with --isolate-extensions. But events from webviews are behaving differently. e.g. zooming. So currently it is not usable for us.

**Comment by rogerwang** [comment]
What's the difference?

**Comment by janRucka** [comment]
We prepared example (it is behaving differently on OS X and Windows btw). In OS X webview will scroll beside zoom. In Windows it zooms whole windows (outside webview as well).

This is not only issue, but nice example I think. And what is strange webview.getZoom() throws exception (probably another issue).
[test.zip](https://github.com/nwjs/nw.js/files/693430/test.zip)

**Comment by bambooCZ** [comment]
+1

**Comment by panther7** [comment]
+1

**Comment by zdenektopic** [comment]
+1

**Comment by Houzvicka** [comment]
Same problem here? Any news?

**Comment by Houzvicka** [comment]
Same problem here? Any news?

**Comment by rogerwang** [comment]
@janRucka does 0.19.1 works well with your sample without --isolate-extensions (in 0.19.1 this is on by default).

And it would be better to try again with a Chrome App in Chrome browser to confirm it's an upstream issue.

**Comment by janRucka** [comment]
I just tried in "furious-scrolling.zip" example provided by bambooCZ in first comment and it is NOT happening in Chrome 55.0.2883.87 m (64-bit).

**Comment by bambooCZ** [comment]
OK I gave it another iteration and made folowing discoveries.
============================================

This issue should be forked to:

* **Too Sensitive scrolling in webview**
  * Mac + Win (maybe Linux)
  * Can be worked around by `--isolate-extensions`
  * Appeared in 0.19.2 (probably because `--isolate-extensions` was turned OFF by default)
  * Is there a way to turn `--isolate-extensions` OFF in 0.19.1?

* **Ctrl + mousewheel is zooming whole window when `--isolate-extensions` is ON (manually or by default, doesn't matter)**
  * only Win (maybe Linux)
  * I haven't figured out, how to prevent it
  * appeared in 0.19.0-beta1

The combination of theese results in a situation when Something will be always broken when using nwjs19 or higher. Nwjs18 is unusable due to the certificate bug, but Nwjs18 have nothing of the above.

@janRucka `webview.getZoom()` throws, but `webview.getZoom(function(z){ ... })` doesn't. You are probably missing a callback. It doesn't return the value. :-)

Upgraded test
===========

* macOS 10.12.2 (x64)

  * Chrome 55.0.2883.95
    * everything works as expected

  * nwjs v0.18.8
    * everything works as expected

  * nwjs v0.19.0 - 0.19.1
    * **webview scrolls slightly while zooming**
    * sensitivity is normal

  * nwjs v0.19.2 - 0.19.4
    * **sensitivity is high**
    * webview doesn't scroll while zooming

  * nwjs v0.19.2 - 0.19.4, with `--isolate-extensions`
    * **webview scrolls slightly while zooming**
    * sensitivity is normal

  * nwjs v0.20.0-beta2
    * **sensitivity is high**
    * webview doesn't scroll while zooming

  * nwjs v0.20.0-beta2, with `--isolate-extensions`
    * **webview scrolls slightly while zooming**
    * sensitivity is normal

* Windows 10 (x64)

  * Chrome 55.0.2883.87
    * everything works as expected

  * nwjs v0.18.8
    * everything works as expected

  * nwjs v0.19.0 - 0.19.1
    * **whole window zooms**
    * sensitivity is normal

  * nwjs v0.19.2 - 0.19.4
    * **sensitivity is high**
    * only webview zooms

  * nwjs v0.19.2 - 0.19.4, with `--isolate-extensions`
    * **whole window zooms**
    * sensitivity is normal

  * nwjs v0.20.0-beta2
    * **sensitivity is high**
    * only webview zooms

  * nwjs v0.20.0-beta2, with `--isolate-extensions`
    * **whole window zooms**
    * sensitivity is normal

[isolate-test.zip](https://github.com/nwjs/nw.js/files/702600/isolate-test.zip)

**Comment by panther7** [comment]
Hi @rogerwang,
Hi @bambooCZ,
good job guys, I tried how works bamboo's example on Win10 with 0.19.0+, and this issue is problematic for my project.

**Comment by rogerwang** [comment]
The sample and the breakdown are helpful. Will find the root cause soon.

**Comment by rogerwang** [comment]
The issue can be reproduced in upstream Chromium browser (not Chrome) with the Furious Scrolling sample.  The latest Chromium was downloaded from: https://www.chromium.org/getting-involved/download-chromium

**Comment by rogerwang** [comment]
Reported in upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=681353

Please star the upstream issue for priority.

**Comment by rogerwang** [comment]
Close as upstream is working on it.
