### ISSUE TITLE
ATM Machine - Make window transparent?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5604]
![snap](https://pams.s3.amazonaws.com/prd/s3fs-public/submissions/screenshots/screenshot-1920x1080-P4C-1.png)

Live video which have transparent background (as above). But how to apply the nodewebkit window /GUI default as full opacity into 0% using package.json or ..?

**Comment by CosmoMyzrailGorynych** [comment]
I can hardly understand you. 

Are you trying to make a window transparent or not?

Have you read this? http://docs.nwjs.io/en/latest/For%20Users/Advanced/Transparent%20Window/

**Comment by ghostoy** [comment]
@CosmoMyzrailGorynych was correct.

Please post your further questions in our mailing list https://groups.google.com/forum/#!forum/nwjs-general. Github issues are used for bug reporting and feature requests.
