### ISSUE TITLE
Help: How to use evalNWBin in background page?

### ISSUE THREAD

**Issue by nurettinkaya** [nwjs/nw.js#5605]
How can i load compiled js (*.bin) on background page? I want to run compiled js on background page.

**Comment by ghostoy** [comment]
Try [`bg-script`](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#bg-script) in `package.json`.

**Comment by ghostoy** [comment]
Please post your further questions in our mailing list https://groups.google.com/forum/#!forum/nwjs-general. Github issues are used for bug reporting and feature requests.
