### ISSUE TITLE
Decode minidump on linux

### ISSUE THREAD

**Issue by adros** [nwjs/nw.js#5608]
The documentation (http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/) says that the tool will try to search for the **.sym** files in *SYMBOLS_ROOT* folder, which we should specify as path to downloaded symbol files.

But there are no *.sym* files in archive for linux (https://dl.nwjs.io/v0.18.4/nwjs-sdk-symbol-v0.18.4-linux-x64.tar.gz).

Did I download a wrong file? Or this this documentation just windows specific? How should I decode the dump on linux?

**Comment by rogerwang** [comment]
The sym files are there without the '.sym' extension. Will fix it.
