### ISSUE TITLE
Ability to customize process.env.LOCALAPPDATA/process.env.APPDATA?

### ISSUE THREAD

**Issue by vaughnroyko** [nwjs/nw.js#561]
Setting the process.env.LOCALAPPDATA or process.env.APPDATA after run-time doesn't seem to effect where data is placed locally. Ideally, we should be able to edit this, for example, 

```
process.env.LOCALAPPDATA = process.execPath + "\\Data";
```

Or perhaps even adding a custom attribute in package.json "data-path" - although, again, ideally we would be able to map relative to process.execPath.

Perhaps there is another way to do this already?

**Comment by fritx** [comment]
so.. there is no other way??

**Comment by karikera** [comment]
"chromium-args": "--user-data-dir='./data-path/'"
It works for me
