### ISSUE TITLE
nw.js v0.14.7 LTS crash when open("chrome://settings") in devtools

### ISSUE THREAD

**Issue by progblog** [nwjs/nw.js#5614]
nw.js v0.14.7
Node v5.12.0
Chromium 50.0.2661.102
commit hash: 9dd0ea2-c661222-2a9e6e1-7af389e

**Comment by progblog** [comment]
@rogerwang

**Comment by xzhan96** [comment]
@progblog could you use newer version? I tried v0.18.7 and some latest versions, issue is not reproduced.

**Comment by rogerwang** [comment]
@xzhan96 this issue is about 0.14, which is a branch we supported. So suggesting a higher version from another branch is not a solution ...

**Comment by xzhan96** [comment]
@progblog I can't reproduce your issue, could you double check?
![screenshot from 2017-02-27 09 59 36](https://cloud.githubusercontent.com/assets/13726257/23346184/e8b4a2ee-fcd2-11e6-80ae-31ab077bc125.png)

**Comment by xzhan96** [comment]
close until more information is provided.
