### ISSUE TITLE
nw.js 不支持"关闭 Google Chrome 后继续运行后台应用"吗?

### ISSUE THREAD

**Issue by progblog** [nwjs/nw.js#5615]
准备开发nwjs app后台运行获取推送消息然后使用Notification进行友好通知.
但是查看了readme没有找到这个功能啊,试着打开chrome://settings/ 结果nw.js奔溃了

**Comment by progblog** [comment]
@rogerwang

**Comment by rogerwang** [comment]
Please use English so all users can read and share the information.
