### ISSUE TITLE
User-agent options are not working. Is it right?

### ISSUE THREAD

**Issue by chunsun21** [nwjs/nw.js#5623]
User-agent options(package file's "user-agent", "nwUserAgent" attribut of <iframe>, "user-agent" of <nw.Window.open>'s meta) are not working in recent versions. Is it right? And why? Anybody else know about it?

**Comment by ghostoy** [comment]
"user-agent" should be supported. Could you please post your sample app?

`nwUserAgent` of `<iframe>` is not supported yet. We'll see to support in future.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by chunsun21** [comment]
nwUserAgent attribute in iframe is working now.
