### ISSUE TITLE
[v0.19.2+] --single-process Is Not Working Properly (Running Two Separate Processes)

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#5624]
**General Information:**
- Using NW.js version 0.19.2 & newer
- Windows 7 with latest drivers
- [Package.nw](https://github.com/nwjs/nw.js/files/697639/packagenw.zip) folder including _package.json_ manifest
- Task-Manager screenshot:
 ![Taskmanager Screenshot](https://cloud.githubusercontent.com/assets/15656049/21829320/a095ce64-d795-11e6-82e1-7fe9e5896743.PNG)

**Problem Description:**
When I'm trying to run a packaged _Construct 2_ game (HTML5) while having "--single-process" set as a property in the chromium-args, NW.js runs a total of 2 processes instead of the intended _single process_.

**Observed Result**
NW.js single process starts to run with two processes using "--single-process" specified inside the package.json manifest.

**Expected Result**
NW.js should run fine with the single processing argument and always run with a single process.

**Comment by rogerwang** [comment]
The additional process is used for crash dumping. And it's intended to be a separate process on windows: https://groups.google.com/a/chromium.org/d/msg/chromium-dev/gQ-IMJwedcs/ujos2lVTAAAJ

The other parts runs in the same process as expected.

Does this affect any aspect of you app?

**Comment by TheRealDannyyy** [comment]
It affects some game recorders that are not able to detect games with multiple processes.

**Comment by rogerwang** [comment]
Then we can have a workaround with an option to disable crash dumping.

**Comment by TheRealDannyyy** [comment]
That would be very much appreciated, thanks a lot.

I know the following question might be a little "off-topic" but I've also had some users reporting that they've experienced minor drops in their games performance while running in single process mode, is that expected behavior?

**Comment by TheRealDannyyy** [comment]
Both 32bit and 64bit (nw.js 0.20.1) versions crash when I use "--disable-crash-handler=true" as a command line flag inside a shortcut. I specified "--single-process" inside the manifest and I followed the required steps. All I can do is provide the [crashlog](https://github.com/nwjs/nw.js/files/748700/Crashlog.txt) by Windows (it's in _German_ but you guys will surely figure it out).

Am doing something wrong or is it indeed not working properly?

**Comment by rogerwang** [comment]
It's fixed again in git and will be available in the next nightly build of 0.20 branch.

**Comment by TheRealDannyyy** [comment]
>It's fixed again in git and will be available in the next nightly build of 0.20 branch.
Thanks again.

**Comment by rogerwang** [comment]
added tag to track the need for a test case for `--disable-crash-handler=true`

**Comment by TheRealDannyyy** [comment]
@rogerwang It works fine in Nw.js v0.27.2 and I assume in previous versions as well.

This is off-topic but I'd really appreciate it if you could "merge" this feature with the _--single-process_ arg or make it possible to disable the crash handler from the manifest.
