### ISSUE TITLE
Get a blank page when reload webview

### ISSUE THREAD

**Issue by JesonRondo** [nwjs/nw.js#5626]
nw ver `0.19.6`

All page is `local file`, Webview load one of the local file, when i reload the page in Webview, all will be blank

main page key code

```html
// index.html

<webview id="wv" src="about:blank"
  partition="trusted"
  style="display:block;width:300px;height:300px">
</webview>
<script>
  const wv = document.getElementById('wv')
  setTimeout(function() {
    wv.showDevTools(true)
    wv.setAttribute('src', './webview.html')
  }, 1000)
</script>
```

webview page key code

```html
// webview.html

<body>
  Hi, this is webview
</body>
```

first open like this

![image](https://cloud.githubusercontent.com/assets/1685674/21839181/56b28f5e-d811-11e6-8d1c-a06c5211327e.png)

when i run script `location.reload` in the opening webview inspect

![image](https://cloud.githubusercontent.com/assets/1685674/21839215/7f0bfdd2-d811-11e6-923b-00172b1c0379.png)

the main page become to blank with nothing

![image](https://cloud.githubusercontent.com/assets/1685674/21839224/988021c6-d811-11e6-9efb-ed0406cb81ae.png)

open dev-tool inspect, the html element has gone

![image](https://cloud.githubusercontent.com/assets/1685674/21839363/4d890ba0-d812-11e6-80ef-a6a1bb3fbc90.png)

**Comment by rogerwang** [comment]
It navigates to about:blank page, which should be intended. Please refer to upstream doc on how to reload webview: https://developer.chrome.com/apps/tags/webview

**Comment by JesonRondo** [comment]
All page blank, both `webview` and `container page`, not only `webview`

**Comment by rogerwang** [comment]
Could you please provide a full sample to reproduce it with the new reload method?

**Comment by rogerwang** [comment]
Close until more information is provided
