### ISSUE TITLE
I would like to get a chrome version of the 53.* version of the NW, the other is the latest, I would like to ask how to do?

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5627]
I would like to get a chrome version of the 53.* version of the NW, the other is the latest, I would like to ask how to do?
Since the 54 version of chrome after my web page has been broken, I did not find the reason!

**Comment by rogerwang** [comment]
See https://nwjs.io/versions.json for mappings of NW versions with Chromium/Node

And please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general , not here
