### ISSUE TITLE
NWJS Context Issue

### ISSUE THREAD

**Issue by jssuttles** [nwjs/nw.js#5629]
Related to https://github.com/node-schedule/node-schedule/issues/321
I'm having a cross-frame issue while using node-schedule. Node-schedule is not able to use instanceof Date and possibly other features. (I tried forking and just changing all the instanceof Date's to this: http://stackoverflow.com/a/1353711. That didn't work.) Not sure where this should be dealt with. Currently, to use node-schedule, I have to copy the contents of schedule.js into another file.

**Comment by ghostoy** [comment]
The trick on stackoverflow should be working. And using `instanceof` is not safe for multiple context scenario. Please follow up the issue on node-schedule.

**Comment by jssuttles** [comment]
Alright. Well... this is a month old now. I don't remember how I got around this. But I must have. So, I'm going to close this for you.
