### ISSUE TITLE
NwJS App crash, error log : `VMware: vmw_ioctl_command error Invalid argument`

### ISSUE THREAD

**Issue by finscn** [nwjs/nw.js#5630]
In Ubuntu , when I start my app , I could run , but when I click any button in app , the app crashed.
the log in console is :
```
VMware: vmw_ioctl_command error Invalid argument
```

Yes, I run Ubuntu in VMware ,   on  Window 7  in VMware , everything is OK.

My App is a  game , it uses WebGL & WebAudio 

-------------------------------
NwJS version:   0.20.0-beta2

OS :  Ubuntu 64bit v16  in VMware  on macOS 10.12 

Device:  MacBook Pro  16G + AMD GPU 

VMWare config :   4G mem + 2G Graphics mem , enable 3D acceleration

**Comment by rogerwang** [comment]
Does this thread help? It looks like a VMware issue.

https://groups.google.com/forum/m/#!topic/security-onion/g-PSbBjeXlU

**Comment by finscn** [comment]
the thread no helping.

**Comment by rogerwang** [comment]
Do you still see the issue with the latest version?

**Comment by rogerwang** [comment]
close until more information is available.
