### ISSUE TITLE
NW Notification,why can't change the icon?

### ISSUE THREAD

**Issue by Vincent2015** [nwjs/nw.js#5632]
![Logo](https://lh3.googleusercontent.com/-32eZ6RrebHE/WHghT24hlGI/AAAAAAAAACs/RxQccxX2RcccUzxSHPQvcBWjGWPBd8bTwCLcB/s1600/Fhp7FQcubLv_xv9-HFV8EBBoRrkA.jpg)
var notification = new window.Notification(title, {
		body: ‘hello’,
		icon: ‘logo.png’,
	});

i  try set the icon.but the icon is showed on the right.  

but if i try this on the chrome brower,the icon can be changed successful.

what is the problem?

**Comment by ghostoy** [comment]
It works for me with nw 0.19.5 on Windows & Mac. Could you post your NW & OS version?

**Comment by Vincent2015** [comment]
nw 0.12.3 && mac osx 10

**Comment by ghostoy** [comment]
@Vincent2015 We do not support 0.12 or earlier versions any more. Please try our latest stable binaries, currently 0.19.5. And if you are targeting to legacy OSes, like Windows XP/Vista or Mac OS X 10.6 or earlier, you can try the 0.14 releases.

**Comment by Vincent2015** [comment]
yes,I will upgrade later,but now have a critical thing，can you help me how to use noftication on nw0.12.3,thanks very much

**Comment by ghostoy** [comment]
Please post your questions to our mailing list (https://groups.google.com/forum/#!forum/nwjs-general) for the usage of NW.js. Github issues are only used for bug reports and feature requests.

**Comment by Vincent2015** [comment]
yes,i had submit last week.  and i use nw-builder  build app, and discover the nw 0.14.6 is very slow.
anyway can quickly for this.

**Comment by ghostoy** [comment]
I've replied on the mailing list. See https://groups.google.com/d/msg/nwjs-general/uLF28pDL2BU/srPsztQKCAAJ
