### ISSUE TITLE
About Window state

### ISSUE THREAD

**Issue by dio833** [nwjs/nw.js#5633]
Can I get a value that indicates whether a window is restored, minimized or maximized?

**Comment by Vincent2015** [comment]
you could use a global variable save the status of the window when you restored, minimized or maximized the window

**Comment by dio833** [comment]
I knew there are 3 events in Window . ( win.maximize() ,win.minimize() and win.restore().)
But if state is from maximized to minimized, then click the icon on task bar. win.restore() will be trigger  ,but win.maximized() will not happen.
In fact, the state should be maximized.

**Comment by Vincent2015** [comment]
generally the restore means from   from  minimized to maximized . if you want this,you could call the minimized do it.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
