### ISSUE TITLE
Error While uploading to MAS

### ISSUE THREAD

**Issue by dibeesh** [nwjs/nw.js#5635]
Error While uploading to MAS

Using version : nw.js V0.19.5 
Mac os version  : 10.12.2 (16C67)

I am using following documentation for signing app
https://github.com/nwjs/nw.js/wiki/MAS%3A-Signing-the-app    

Doubts 

But in version nw.js V0.19.5 the folder structure does not contains the frameworks folder instead a helper.app file is found in the .app/Contents/Versions/55.0.2883.87/nwjs Helper.app.

Please let me know which all files to be signed in this latest version..

How changes are to be made in the apps plist also which all plist are to be modified..??

We have managed to create a .pkg file but getting error when we try to upload it int to MAS(Please see screenshot attached)

Done following 
1. Taken App build as specified in documentation 
2. sign in the .app file using application installer certificate 
“codesign --deep -s "3rd Party Mac Developer Application: Unified Inbox Pte Ltd (8G4Y9A7XS2)" --entitlements /Users/apple/Desktop/paul/test/OutBoxPro.app/Contents/Info.plist /Users/apple/Desktop/paul/test/OutBoxPro.app”

codesign --deep -s "3rd Party Mac Developer Application: Unified Inbox Pte Ltd (8G4Y9A7XS2)" --entitlements "/Users/apple/Desktop/paul/test/OutBoxPro.app/Contents/Versions/55.0.2883.87/nwjs Helper.app/Contents/Info.plist" "/Users/apple/Desktop/paul/test/OutBoxPro.app/Contents/Versions/55.0.2883.87/nwjs Helper.app"

3.Make .pkg file and sign package using application installer certificate
productbuild --component "OutBoxPro.app" /Applications --sign "3rd Party Mac Developer Installer: Advanced Millenium Technologies Private Limited (LL44QWX773)" "OutBoxPro.pkg"

4. We only changed bundle identifier in the demo plist given 

Your help is much appreciated. Thank you. 
![screen shot 2017-01-12 at 17 35 18](https://cloud.githubusercontent.com/assets/8565773/21972234/19afb64c-dbde-11e6-9a47-dad2b04e291e.png)
![screen shot 2017-01-12 at 17 35 31](https://cloud.githubusercontent.com/assets/8565773/21972233/193aacc6-dbde-11e6-8208-bd42aaa86f42.png)

**Comment by ghostoy** [comment]
@dibeesh Please download the **MAS BUILD** from https://dl.nwjs.io/v0.19.5-mas-beta/

**Comment by ghostoy** [comment]
Does the errors disappear after changed to the MAS build? If so, please close this issue.

**Comment by dibishks** [comment]
@ghostoy Yes.. Its working now. Thank you.
