### ISSUE TITLE
invalid value for 'app.urls[0]':invalid port /////nw 0.14.6 ,app startup report error. 

### ISSUE THREAD

**Issue by Vincent2015** [nwjs/nw.js#5636]
invalid value for 'app.urls[0]':invalid port /////nw 0.14.6 ,app startup report error.

**Comment by ghostoy** [comment]
Did you used `node-remote` ? It's changed since 0.13.0. Please read the [document](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote) for the new spec.
