### ISSUE TITLE
does nw.js support "Continue running background apps when Google Chrome is closed"

### ISSUE THREAD

**Issue by progblog** [nwjs/nw.js#5638]
I'd like to make my app run mini after windows startup and friendly notice use window.Notification,
But when i am try open chrome://settings/ nw.js crashed

**Comment by ghostoy** [comment]
You could provide a js file as `main` in `package.json`, which is run in the background page and should not exit. If it doesn't solve your problem, please post your full sample app and NW.js version.

**Comment by progblog** [comment]
run nw.exe background not javascript file.

**Comment by ghostoy** [comment]
What do you mean by "run nw.exe background"?

**Comment by baconface** [comment]
@progblog Basically you have a `main` process and a `render` process. Your `render` process is in your visible window. So if you kill this window you kill any code running in that process. This is why he recommended running it in the `main` process. As long as you do no terminate your application it will run in the background. You can kind of fake the same behavior in the `render` process by hiding (but not terminating) the window. But it might not be as reliable as using the `main` process.
