### ISSUE TITLE
OSX deploy failed

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5639]
I am trying to make a DMG package but after deploying the package when i execute it, i get following ERROR:

![snap](http://i.imgur.com/K5aAw13.png)

How to resolve it? i am on OSX 10.11.6 (15G1212)

**Comment by ed4becky** [comment]
Did you use a Winbdows build of NWJS instead of the MAC build, and just
package it up like a Mac?  You need to use the MAC build.

**Comment by shamun** [comment]
NO its the OSX build from here : https://dl.nwjs.io/v0.19.5/nwjs-v0.19.5-osx-x64.zip, when i download it and manually execute it in my OSX it works.

But when i deploy that downloaded executable using OSX Packages builder then i am unable to execute it (which is shown in the error)

Any hints?

**Comment by shamun** [comment]
Fixed
- (awkward/retired OSX and package builder issue)
