### ISSUE TITLE
Security page on wiki is incomplete

### ISSUE THREAD

**Issue by henryptung** [nwjs/nw.js#5640]
I'm checking out nw.js for suitability of a helper app I want to write, but it involves working with an iframe from another origin. To evaluate whether origin security is going to be a blocker, I found [this wiki page](https://github.com/nwjs/nw.js/wiki/Security), but the information there seems incomplete. A few things that I think would drastically clarify the information there:

1. Rather than saying what "Node frames" _can access_, describe what normal frames _cannot access_, and indicate that Node frames do not abide by those restrictions.
2. How does the parent NW application come into play? It is neither kind of frame, so does it get access to all its children? None? By what criteria?
3. The algorithm for distinguishing "Node frame" from "normal frame" is incomplete. In particular, frames satisfying the following criteria are not covered:

- Does not have `nwdisable` attribute
- Is not a local file
- Is not an app-protocol frame
- URL does not match node-remote
- `new-instance != true` or `nodejs != false`

Given the conditions, I think the bulk of normal iframe usage actually falls in this bucket, so it's probably worth fleshing out that description some more.

**Comment by ghostoy** [comment]
The wiki page targets for legacy NW.js <= 0.12.x. For documents of latest NW.js, please refer to http://docs.nwjs.io/en/latest/.

BTW, wiki page is open for edit by anyone.
