### ISSUE TITLE
Cannot write product to "xxx.pkg". (Could not find appropriate signing identity for “xxx”.)

### ISSUE THREAD

**Issue by egorovsa** [nwjs/nw.js#5643]
Can't create package. Got this error.
I am use the guide https://github.com/nwjs/nw.js/wiki/MAS%3A-Uploading-the-binary

**Comment by ghostoy** [comment]
Please make sure you have the certificates in your Keychain Access and they are enabled.
And the wiki page was written for legacy NW.js 0.12.x. If you are looking for MAS support of latest NW.js, please read on [official document](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Support%20for%20Mac%20App%20Store/).

**Comment by egorovsa** [comment]
So... My first problem was solved....
Now i have next trouble.
I use this guide for make application.
After bundle my application works well.
i was uploaded my package to app store and uploading also well...

Now i receive email from apple, and i can't understand what's problem.
Real company name was changed to "MyCompanyName"


> Invalid Signature - The main app bundle MyCompanyName at path MyCompanyName.app has following signing error(s): valid on disk /Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s) . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> Invalid Signature - The nested app bundle at path MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework has following signing error(s): --prepared:/Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libffmpeg.dylib --validated:/Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libffmpeg.dylib --prepared:/Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libnode.dylib --validated:/Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libnode.dylib /Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A: valid on disk /Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s) . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> Invalid Signature - The nested app bundle nwjs Helper at path MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Helper.app has following signing error(s): valid on disk /Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Helper.app: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s) . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> Invalid Signature - The executable at path MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libffmpeg.dylib has following signing error(s): valid on disk /Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libffmpeg.dylib: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s) . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.
> 
> Invalid Signature - The executable at path MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libnode.dylib has following signing error(s): valid on disk /Volumes/data01/app_data/dstr/mz_7027004412904696039dir/mz_8595528145603168401dir/com.MyCompanyName.MyCompanyNameDesktop.pkg/Payload/MyCompanyName.app/Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/libnode.dylib: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s) . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information

**Comment by ghostoy** [comment]
What does `codesign -v -vvvv MyCompanyName.app` say?

**Comment by rogerwang** [comment]
close until more information is available.
