### ISSUE TITLE
.vtt subtitles not working

### ISSUE THREAD

**Issue by mk010101** [nwjs/nw.js#5644]
nwjs v. 0.18.5, osx64

Video subtitles are not working, console reports the following:
**Resource interpreted as TextTrack but transferred with MIME type text/plain**

**Comment by ghostoy** [comment]
Does it work on Chrome? And could you post a sample app?

**Comment by mk010101** [comment]
Yes, works in all browsers - tested on FF, Chrome, Safari (PC and Mac). 
Tested in new release of nwjs **0.19.5**, looks like the issue has been fixed since then!
