### ISSUE TITLE
0.19.5 console error - "Natives disabled"

### ISSUE THREAD

**Issue by tolrtd** [nwjs/nw.js#5645]
On Windows 8.1 x64, 0.19.5 SDK x64, I get an unhandled exception "Natives disabled"

console.trace yields

```
emitOne @ events.js:96
emit @ events.js:188
process._fatalException @ bootstrap_node.js:309
```

Does anyone know where this may be coming from?  I could prepare a sample but it would probably mean including my entire proprietary app, so it will take some time.  I am using quite a lot of modules from NPM (including 2 native compiled, which are working).  This seems to happen around the time I spawn a window with nw.Window.open, but I can't confirm it is related.

Thanks!

**Comment by rogerwang** [comment]
It's an internal exception, happening when internal JS code trying to call native code which is not available. A wild guess is that maybe it's happening when something is wrong in window loading remote pages.

**Comment by tolrtd** [comment]
I do use a bunch of npm modules, but excluding the 2 native ones doesn't remove this error.  I'm also not using remote pages.  I will try to dig into this to see what causes it, in case it helps anybody else.

**Comment by Christywl** [comment]
@tolrtd , is it reproduced in your test now? If yes, could you please provide your test case and steps to reproduce it?

**Comment by tolrtd** [comment]
On 0.19.5 I am no longer seeing it.  I think it may have had something to do with using the built in printing API, but I've removed that and don't see the error anymore.  I haven't looked into this any further.

**Comment by Christywl** [comment]
Closed per above comment.
