### ISSUE TITLE
MAS Review  INVALID SIGNATURE issue 

### ISSUE THREAD

**Issue by dibishks** [nwjs/nw.js#5646]
I have managed to sign in my app with following guidelines 
Beta build url: https://dl.nwjs.io/v0.19.5-mas-beta/
Mac OS version: 10.12.2 (16C67)
documentation:  http://docs.nwjs.io/en/latest/

1. I am generating .app file using the following command 
python build_mas.py -C build.cfg -I OutBoxPro.app -O OutBoxPro1.app

2. Then converting .app file to pkg using following command 

productbuild --component "OutBoxPro.app" /Applications --sign "3rd Party Mac Developer Installer: Advanced Millenium Technologies Private Limited (xxxxxxxxxx)" "OutBoxPro.pkg"

3. Upload the pkg file in iTutes using application loader 3.0 and shown success message and after we got the following reply from apple team.

Could you please let us know anything went wrong in my build steps. Your help is much appreciated. 

 We have discovered one or more issues with your recent delivery for
"OutBoxPro". To process your delivery, the following issues must be
corrected:

 INVALID SIGNATURE - The main app bundle nwjs at path OutBoxPro1.app has
following signing error(s): invalid Info.plist (plist or signature have
been modified) In architecture: x86_64 . Refer to the Code Signing and
Application Sandboxing Guide at
http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html
and Technical Note 2206 at
https://developer.apple.com/library/mac/technotes/tn2206/_index.html for
more information.

 INVALID SIGNATURE - The nested app bundle nwjs Helper at path
OutBoxPro1.app/Contents/Versions/55.0.2883.87/nwjs Helper.app has
following signing error(s): invalid Info.plist (plist or signature have
been modified) In architecture: x86_64 . Refer to the Code Signing and
Application Sandboxing Guide at
http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html
and Technical Note 2206 at
https://developer.apple.com/library/mac/technotes/tn2206/_index.html for
more information.

**Comment by ghostoy** [comment]
Did you changed Info.plist files after signing the app?

**Comment by ghostoy** [comment]
You can use `codesign -vvvv -v OutBoxPro.app` to verify the signature.

**Comment by dibeesh** [comment]
yes this worked for me when I used the below code for signing

step 1: 
python build_mas.py -C build.cfg -I OutBoxPro.app -O OutboxPro1.app -P OutboxPro1.pkg
I have successfully uploaded it for apple review. 

But when I try open my signed app file ie 'OutboxPro1.app' its giving error (see screen-shot)
"This site can’t be reached
outbox.pro’s DNS address could not be found. Diagnosing the problem." 

But the app before signing is working fine ie ('OutBoxPro.app' see screen-shot). 

I don't know what happened after running signing command in step 1. 

signing in status 
apples-Mac-mini:test Paul$ codesign -vvvv -v OutboxPro1.app
OutboxPro1.app: valid on disk
OutboxPro1.app: satisfies its Designated Requirement

i have not edited any file after signing the app
![screen shot 2017-01-18 at 16 21 05](https://cloud.githubusercontent.com/assets/8565773/22061269/3617edf0-dd9a-11e6-9353-5485e1fe1e8e.png)

working unsigned app screenshot..
![screen shot 2017-01-18 at 16 22 30](https://cloud.githubusercontent.com/assets/8565773/22061324/72964466-dd9a-11e6-8bab-f7ed12cf7ab3.png)

**Comment by ghostoy** [comment]
What's your entitlements? If you need network access, you should entitle the app with `com.apple.security.network.client`.

**Comment by dibeesh** [comment]
I have given the entitlement com.apple.security.network.client= boolean = YES in both the helper and main plists before code signing(attaching the screen shots of the plist)
main plist
![screen shot 2017-01-19 at 10 26 38](https://cloud.githubusercontent.com/assets/8565773/22094275/51f274bc-de32-11e6-90f0-d0f15cbcc6fa.png)
helper plist
![screen shot 2017-01-19 at 10 27 24](https://cloud.githubusercontent.com/assets/8565773/22094295/7d03cbd8-de32-11e6-809d-a29e6e79bd66.png)

**Comment by ghostoy** [comment]
The entitlements are not part of `Info.plist`. They are separate files provided when code signing. You should put your entitlements into `entitlements-parent.plist` and edit `ParentEntitlements` of `build.cfg` to point to your entitlements file.

**Comment by ghostoy** [comment]
Just leave `entitlements-child.plist` alone. By default, it will inherit all entitlements from parent.

**Comment by ghostoy** [comment]
Did you succeed with my suggestions?

**Comment by dibishks** [comment]
@ghostoy Yes..You are a life saver..Thank you so much. App is under review fingers crossed. :)

**Comment by zhailei31665431** [comment]
@ghostoy What's your Wechat number? I need your help...Thank you ...
