### ISSUE TITLE
how to run chrome app with chrome api on nw>=0.13

### ISSUE THREAD

**Issue by Vincent2015** [nwjs/nw.js#5647]
nwjs claim support chrome app,why i try on nw 0.19.0, and i drag chorme app to the nw window, 

under "chrome" context, have no "runtime ,storage" etc. chrome api interface.
![aa](https://lh3.googleusercontent.com/-Y7CasrPulYE/WH8aNjdCt-I/AAAAAAAAADE/M-hdxzxkTNkgCMYLERYwxF12uW9XWVuYgCLcB/s1600/12910C66-B189-4509-AC0D-91CFD9952785.png)
under chrome object only have  app,csi,webstore sub object
![vvv](https://lh3.googleusercontent.com/-dMgmLlhPnYo/WH8abIbZKsI/AAAAAAAAADI/gStfMYSyEaoWYgHmfI8dq5db6LSuxZtiwCLcB/s320/D44CA3A4-B044-46CD-BF44-AB2613AC092A.png)

**Comment by rogerwang** [comment]
How did you drag it?

**Comment by Vincent2015** [comment]
on mac osx, first i open the nwjs.app(unzip from the nwjs-v0.19.0-osx-x64.zip), and then drag the 

chromapp/chrome-app-samples/samples/rich-notification(chromapp form github).  

1,i found before drag the sample code to the nw window,the process and global is existed,but after,all became undfined.
2,i try to add 'node' permission to manifest.json, the issue didn't change.

so i ask for this. 

thanks.

**Comment by Vincent2015** [comment]
@rogerwang   any more info need?

**Comment by rogerwang** [comment]
You should drag the folder to the exe file. That is, starting nw.exe with an argument which points to the path of the app. Do not launch NW first.

**Comment by Vincent2015** [comment]
yes,i do. i draged the folder.  you mean start from cli?

**Comment by Vincent2015** [comment]
i got it ,thanks.
i found that copy the sample code into the nwjs.app's /resource/app.nw(new created), then back to the nwjs.app diretory, run the nwjs.app. that's ok.
