### ISSUE TITLE
Not possible to build latest NW19

### ISSUE THREAD

**Issue by janRucka** [nwjs/nw.js#5648]
It is not possible to build latest NW19:
 "switches::kNWAppPath" is not defined and it is used e.g. in "chrome\browser\chrome_content_browser_client.cc"

I guess you just forgotten to add it to "src\base\base_switches.h" (and *.cc) file.
And include "base\base_switches.h" into "src\content\nw\src\renderer\nw_extensions_renderer_hooks.cc"

Specific commits:
Chromium:
https://github.com/nwjs/chromium.src/commit/9ed150dc024c89eaf0dd28a566868ea65304c33a

NW.js:
https://github.com/nwjs/nw.js/commit/5a7238e3b34a3c157e6a12971a66291de50115bb

**Comment by rogerwang** [comment]
But our nightly buildbot builds the branch tip well: http://buildbot-master.node-webkit.org:8010/builders/nw19_sdk_win64/builds/101

**Comment by janRucka** [comment]
First of all, thank you for quick reply. I am sorry it is my bad. You are right it is there. Once again my merge disappointed me.

But I have to say I really dislike the way you maintain chromium fork. You just put all your changes on top of actual chromium. I know that it is making your life somewhat easier although I don’t know how exactly. But there are some issues because of that:

-No history so if there is anything strange or wrong one cannot check previous commits to find out why it is there. If I cannot understand something in the code, I use history a lot. Also if there is any new issue introduced one cannot (or with at least a lot more effort) trace it back.
-Merging is very inconvenient. If you have fork with just few custom changes it is really hard to keep it updated since even minor changes in NW.js makes merge very hard.
-Hard to find what was changed between versions in code (otherwise it is possible to just look into changelog).

Maybe there are solutions for these issues? I don’t know them. I don’t want to sound too critical but this thing I find very inconvenient in otherwise great project.

**Comment by rogerwang** [comment]
Regarding merge difficulty: you should rebase, not merge. That's the downstream should be doing, and that's what we do as the downstream of Chromium project.

In 0.12 and earlier, we used to maintain our changes in a series of commits on top of upstream and that doesn't work well. So after 0.13 we maintain it in a single patch and it has been working well. We have been able to release a major update for every single Chromium upgrade in 1-2 days in 2016.

**Comment by janRucka** [comment]
Rebase sounds reasonable - will try next time. Thanks
