### ISSUE TITLE
Single file executable instead of 'dual file' executable

### ISSUE THREAD

**Issue by cGuille** [nwjs/nw.js#565]
Hello!

Working on GNU/Linux, I followed [the steps explained in the wiki in order to package my app](https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps).

I eventually understood that the executable produced had to be in the same directory as the `nw.pak` file you provide.
I was wondering if there was a solution to get over this restriction since it might be easier to use.

**Comment by rogerwang** [comment]
Chromium upstream doesn't support put everything in a single executable file.

**Comment by fritx** [comment]
da*n

**Comment by 2596136372** [comment]
我下载的nw压缩包解压以后并没有发现**nw.pak**这个文件，谁知道这是怎么回事吗？
