### ISSUE TITLE
Is there any possibility to listenTo file download in node webkit?

### ISSUE THREAD

**Issue by blankzust** [nwjs/nw.js#5650]
like this 
![image](https://cloud.githubusercontent.com/assets/8541906/22091121/360e984a-de30-11e6-9582-f31cc77f08be.png)

**Comment by blankzust** [comment]
Need the download bar like chrome

**Comment by ghostoy** [comment]
You can try with `chrome.downloads` API. See https://developer.chrome.com/extensions/downloads. If it doesn't work, please feedback here.

**Comment by blankzust** [comment]
ok,I will try now

**Comment by blankzust** [comment]
![image](https://cloud.githubusercontent.com/assets/8541906/22098123/93849a7c-de5f-11e6-88c0-6d5524199ae3.png)
I don't know where is the "permission" should be added.package.json?
like this
![image](https://cloud.githubusercontent.com/assets/8541906/22098178/e5905d4c-de5f-11e6-93c8-5187566f00d3.png)

**Comment by ghostoy** [comment]
There is no need to set `permission` in `package.json`. If `chrome.downloads` doesn't work without the permission, we will seek to fix it.

**Comment by blankzust** [comment]
`chrome.downloads.download` is ok to run.But `chrome.downloads.onChanged.addListener` will cause the result that file download failed.
test code
```const chrome = window.chrome;
        if(chrome && chrome.downloads) {
            chrome.downloads.onChanged.addListener(({id, state={}, error}) => {
                console.log(id, state);
                if(state.current === chrome.downloads.State.COMPLETE) {
                    chrome.downloads.show(id);
                }
            })
        }```

**Comment by blankzust** [comment]
`chrome.downloads..download` was runned after `chrome.downloads.onChanged.addListener`

**Comment by blankzust** [comment]
Oh sorry.I find it ok when run the code again.
But I don't catch the method or any properties to show download bar in chrome extension api

**Comment by ghostoy** [comment]
Yes, there is no download UI for it. You can implement your own.

BTW, you can use Node.js APIs to download files as well. But `chrome.downloads` can intercept the downloads initiated from web page.

**Comment by blankzust** [comment]
I find another way to solve my problem.I can use `chrome.downloads.onChanged.addListener` to listen to my download percentange and show it on a message modal.Thank you. @ghostoy

**Comment by bwcxyk** [comment]
怎么解决？
