### ISSUE TITLE
Frameless window show a empty useless title bar on mac full screen mode

### ISSUE THREAD

**Issue by imyzf** [nwjs/nw.js#5651]
When setting `"frame": false` in manifest and using `nw.Window.get().toggleFullscreen()` to enter full screen mode, the application will show a empty useless title bar. It would be better to show three window buttons on full screen title bar like other native frameless application. 

![image](https://cloud.githubusercontent.com/assets/8298849/22096497/ec8358e2-de56-11e6-8fd6-edf06aa66048.png)

Other native frameless application like QQ show three window buttons in this case.
![image](https://cloud.githubusercontent.com/assets/8298849/22096521/0522ce14-de57-11e6-94a5-8e28755e26da.png)

**Comment by rogerwang** [comment]
Is this issue OSX only?

**Comment by imyzf** [comment]
@rogerwang I'm using mac OSX 10.11.6. Sorry I don't have windows and linux PC in my office.

**Comment by rogerwang** [comment]
@ghostoy please check this issue first.

**Comment by ghostoy** [comment]
Yes, I can confirm this issue. And it also happens for Chrome Apps.

**Comment by toxygen** [comment]
I don't think this is still an issue. `nw.Window.get().toggleFullscreen()` seems to work correctly (verified on macOS 12.6).

Also, macOS hides the title bar by default in fullscreen (see ["How to Make Your Mac's Menu Bar Stay Visible in Full Screen Mode"](https://www.macrumors.com/how-to/make-menu-bar-visible-full-screen-mode/). 

I propose closing this issue

**Comment by ayushmxn** [comment]
I don't have a Mac.  @toxygen could you post screencast/screenshot(s) here so I can confirm and close the issue. Thanks!

**Comment by toxygen** [comment]
[Link](https://darken.sk/tmp/Screen%20Recording%202022-10-15%20at%2023.13.11.mov) to video (it was too large for github)

**Comment by Bug-Reaper** [comment]
Sorry to bump here, but did you guys find a solution to this? I have a useless empty titlebar in fullscreen in a non-nw.js project,
