### ISSUE TITLE
[v0.19.5-sdk] strange red overlay and crash on alert();

### ISSUE THREAD

**Issue by strowbeary** [nwjs/nw.js#5655]
I'm on windows and nwjs is constantely freezing when he has not the focus or when i call alert();
**crashdump**
```
[0123/164027:ERROR:process_info.cc(608)] range at 0xa1c567000000000, size 0x233 fully unreadable
[0123/164027:ERROR:process_info.cc(608)] range at 0xa1c569000000000, size 0x233 fully unreadable
[0123/164027:ERROR:process_info.cc(608)] range at 0x0, size 0x233 fully unreadable
```
thanks

**Comment by ghostoy** [comment]
This is a just line of log, not a crash dump. Could you please post a sample to reproduce the crash and the OS? If not, could you submit the real crash dump (*.dmp) files found in `%LOCALAPPDATA%/Chromium/User Data/CrashPad` (on Windows) or `~/Library/Application Support/<app-name>/CrashPad` (on macOS).

**Comment by strowbeary** [comment]
resolved with the --single-instance flag but it's strange.
the sample app is https://github.com/strowbeary/PayPoint.

**Comment by rogerwang** [comment]
close until more information is provided.
