### ISSUE TITLE
menu.insert(item, i) doesn't register the shortcut (windows only)

### ISSUE THREAD

**Issue by adrianomelo** [nwjs/nw.js#5657]
Hi,

I am developing a desktop application using nw.js for both macOS and windows. We noticed that shortcuts are not working with the Menu system on windows. After some investigation I could verify that there are a few problems with the Menu system of nw.js:

- `menu.insert(item, i)` doesn't register shortcuts;
- shortcuts can't be deregistered (when using `menu.append(item)`).

I've used the latest version of nw.js to reproduce the bugs. There are two code samples for reproducing the problems.

Code sample for the first problem:
```
// Paste this code inside a nw.js window and try to use the shortcut bellow
var menuItem = new nw.MenuItem({
  label: 'test',
  key: 'i',
  modifiers: 'ctrl-alt',
  click: function() {console.log('hey')}
});

var menu = new nw.Menu({
  type: 'menubar'
});

// The menu item will be added but the shortcut won't work
menu.insert(menuItem, 0)

nw.Window.get().menu = menu;
// Actual Behaviour: Shortcuts don't trigger the click function on windows
// Expected Behaviour: Shortcuts should trigger the click function
```

Code sample for the second problem:
```
// Paste this code inside a nw.js window and try to use the shortcut bellow
var menuItem = new nw.MenuItem({
  label: 'test',
  key: 'i',
  modifiers: 'ctrl-alt',
  click: function() {console.log('hey')}
});

var menu = new nw.Menu({
  type: 'menubar'
});

// The menu item will be added but the shortcut won't work
menu.append(menuItem)

nw.Window.get().menu = menu;
nw.Window.get().menu = null;

// Actual Behaviour: Shortcuts work even without displaying the menu
// Expected Behaviour: Shortcuts shouldn't work after removing the menu
```

Windows 10 Enterprise N x64
nw.js v0.20.0 (32 and 64)
Node v7.4.0
Chromium 56.0.2924.72
commit hash: ff6b093f2941e47237b258de33e2

**Comment by azproduction** [comment]
Can someone guide me on how it can be fixed?

**Comment by azproduction** [comment]
@rogerwang could you help with this?
