### ISSUE TITLE
[needinfo] "nw.exe" Name Requirement For 3rd Party Modules Outdated?

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#5663]
**References:**
- Old documentation about 3rd party modules ([Link](https://github.com/nwjs/nw.js/wiki/using-node-modules#3rd-party-modules-with-cc-addons))
- New documentation about native modules ([Link](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/))
- Construct 2 Steam Plugins ([Steam4C2](https://www.scirra.com/store/construct2-plugins/steam4c2-2545) | [Greenworks](https://www.scirra.com/forum/experimental-greenworks-plugin_t117833))

**General Information:**
I'm a Construct 2 desktop developer and as you might already know, NW.js is the best thing for running HTML5 games offline. C2 offers Steam plugins which make use of 3rd party modules with C/C++ addons. 
A C2 user recently noticed that he could run NW.js + Steam Plugins just fine, even though his NW.js executable wasn't named "nw.exe", which is stated as a requirement inside the old documentation.

**My Question:**
Is it still required to name the NW.js executable as "nw.exe" or is this perhaps an outdated requirement and doesn't apply to releases starting from v0.13 anymore? I would also like to request an update to the new documentation which clearly states if this is still a requirement or not.

**Comment by SchizoDuckie** [comment]
You can rename nw.exe to anything you want.

I'm currently rebuilding DuckieTV to work with the new nwjs version. [You can find the windows specific implementation details here](https://github.com/DuckieTV/duckietv-builder/blob/master/platforms/windows.js), hope that helps :)

**Comment by TheRealDannyyy** [comment]
@SchizoDuckie Sorry for the extremely late response.
Thanks for the info, tests on my end also showed that changing the name of the application doesn't have any negative effects on 3rd party modules anymore.
