### ISSUE TITLE
Make methods more private (hide behind a login screen)

### ISSUE THREAD

**Issue by danschumann** [nwjs/nw.js#5665]
Hello Friends,

I'm wondering if and how there's a way to make sure my users are logged into an active account.

A way to break into my app would be:
Users can unzip my app.nw file, and open it with nw sdk.  Then, inside of console, they could call `MyApp.initialize()` after some digging.

Can you think of a pattern that would require them to be logged in and a way to make methods more private?

Also, this is a separate concern, one way to crack photoshop's verify servers is to change your host file so that it points to your computer and responds with a "success" response.  My current pattern for preventing this is:
I have a long key within one of the compiled javascript files and bcrypt.  Since I compile to a `.bin`, I think they cannot know what the pre shared key is.  So, I send the current timestamp to the server during login, and the server hashes it using the same key that's in my app's compiled javascript.  Then when I receive the encrypted string, I check to see if it matches.  
This way, even if someone changes their host file on their computer to send a "success" response, they still won't be able to trigger the success action, because they won't know how to encrypt the timestamp.  Does this sound reasonable or can you think of a way to figure it out?

**Comment by danschumann** [comment]
It seems setting a breakpoint currently crashes the app.  I'm trying to figure out how someone could set a breakpoint and eventually find my `MyApp` variable within the `scope` section of console.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
