### ISSUE TITLE
How can I rebuild node webkit under windows in order to use mp3 and mp4?

### ISSUE THREAD

**Issue by GERMANOCARELLA** [nwjs/nw.js#5666]
There is a way to build node webkit binaries in order to use mp3 and mp4? I have my own, and I need to play with node webkit. Do I need to rebuild node webkit, or I need to build ffmpeg library only?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
