### ISSUE TITLE
nwsaveas attribute regression

### ISSUE THREAD

**Issue by conceptualspace** [nwjs/nw.js#5667]
nw: v0.20.0
os: win 10x64; osx 10.11.6
node: v6.8.0

it seems that there is a regression in v0.20.0 regarding the [nwsaveas](http://docs.nwjs.io/en/latest/References/Changes%20to%20DOM/#attribute-nwsaveas) attribute.

it is working in nw0.17.6 but after upgrading to 0.20.0 the default filename is **blank**.

if it's helpful, the "accept" attribute still works (ie, the save file dialog shows my target extension, just not the file name)

**Comment by conceptualspace** [comment]
on OSX, the filename is at least "Untitled"; on Windows it is an empty string

**Comment by conceptualspace** [comment]
update:

issue only seems to occur if the node process is in development mode; in production mode everything works as expected

**Comment by rogerwang** [comment]
what do you mean by "development mode" and "production mode"?

**Comment by conceptualspace** [comment]
thought the behavior was being triggered by `process.env.NODE_ENV` being set to 'development', but it turns out that is not actually the case

**Comment by conceptualspace** [comment]
(in other words, issue is still present in both cases, unfortunately)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build. Thanks for reporting.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/02-09-2017/nw20-206df0d-6473ec0-a2ef613-1f1f729/v0.20.2/
