### ISSUE TITLE
v0.20.X: Enigma Virtualbox is not working anymore

### ISSUE THREAD

**Issue by guidoselva** [nwjs/nw.js#5670]
**General Information:**

Windows 10 64bit
NW.js version 0.20.2
Enigma Virtual Box version 7.70

**Problem Description:**

Since version 0.20.0 I cannot package anymore my application with Enigma Virtual Box.
Before running Enigma Virtual Box, the application starts correctly. But after packaging it with Enigma Virtual Box, when I run the file app_boxed.exe nothing happens at all, not even the creation of a debug.log error file.

Everything worked fine up to version 0.19.5.

**Comment by guidoselva** [comment]
I found a solution. In the .evb configuration file I had to change the following setting from false to true:

<MapExecutableWithTemporaryFile>true</MapExecutableWithTemporaryFile>

So it seems (at least for my project) that this setting is needed for NW.js since version 0.20.0

**Comment by rogerwang** [comment]
Thanks for sharing. Which setting did you change?

**Comment by guidoselva** [comment]
Oops, sorry, the setting had been lost with formatting. I updated my comment.
