### ISSUE TITLE
nwjs connects to google public dns (8.8.8.8) with every time on starting.

### ISSUE THREAD

**Issue by valera911** [nwjs/nw.js#5672]
nwjs connects to google public dns (8.8.8.8) with every time on starting. 
Is there any way to disable it?
os: osx 10.10

**Comment by rogerwang** [comment]
There is a change related to this issue in latest 0.20.3. Could you please try again?

**Comment by valera911** [comment]
I can confirm that the problem had been fixed in 0.20.3 version. 
Thanks a lot.
