### ISSUE TITLE
Frameless Windows on Mac css issue

### ISSUE THREAD

**Issue by akirapix** [nwjs/nw.js#5674]
Hi,
i am using nwjs 0.19.3 on OSX 10.12.1
On each frameless window i can see that all HTML elements that occupy space related to frame (about 25px on the top of the window) is not interpreted.

For example consider this an empty window without frame and this code:

```
<body>
    <div style="position: absolute; top:0px; left:0px; right:0px; height:50px;">
        <img src="icon.png" style="cursor:pointer; width:25px; height:25px;" />
    </div>
</body>
``` 

such image image is in the "missing frame" space. If you position pointer above image "cursor:pointer" property will not work. It looks like frame is not visible but still positioned above window html elements.

Windows version has not the same issue.

**Comment by Christywl** [comment]
@akirapix , I tried your code on Mac OS 10.11 with nwjs 0.19.3 and 0.20.3, "cursor:pointer" works for me. 
![1](https://cloud.githubusercontent.com/assets/20039821/23295052/7c405f3e-faa9-11e6-88d7-5510a5b3fe3b.png)

**Comment by akirapix** [comment]
Hi,
ok. In a window with frame (the toolbar with 3 buttons on the left and title) everytinh works fine. But if you set frame:false option when opening this window you will see this effect on the first 25px of your image.

![description](https://cloud.githubusercontent.com/assets/9852013/23296255/8a7f7a7e-fa74-11e6-85d6-c7399441c6f8.jpg)

**Comment by Christywl** [comment]
Yes, I reproduce when set window 'iframe:false' in package.json, "cursor:pointer" does not work on Mac OS, and it works fine on Windows.

**Comment by rogerwang** [comment]
@Christywl thanks. Does this reproduce with upstream Chrome App?

**Comment by Christywl** [comment]
@rogerwang , it doesn't reproduce with Chrome on Mac.

**Comment by rogerwang** [comment]
@Christywl I can reproduce it with a sample Chrome **App** in Mac. This issue should be in upstream.

**Comment by rogerwang** [comment]
@Christywl Chrome browser window is different with Chrome App window.

**Comment by rogerwang** [comment]
close as it's an upstream issue.
