### ISSUE TITLE
 Custom URI opens wrong node webkit application.

### ISSUE THREAD

**Issue by ShivaniPahuja02** [nwjs/nw.js#5676]
Hi,

we are also facing issue where wrong Node Webkit Application opened in Mac in case of URI invokation on nwjs build 14.7 . we followed the link 
https://github.com/nwjs/nw.js/issues/5592 
 
As a solution we tried the approach proposed by you,changed the last 4-characters in PkgInfo and cleared the cache. This solution worked for us. we did all the changes in final
nwjs build by extracting build package. But now we were trying to make changes in code itself so that final build PkgInfo and Info.plist should contain new value rather than ApplCr24. we changed mac creator in file "chrome_settings.gypi" as 'mac_creator': 'abcd'.

After this change PkgInfo in nwjs build still have ApplCr24 .we request you to please suggest how can we achieve this by code as now we are manuaaly replacing values each time we create a nwjs build.

Regards,
Shivani Pahuja

**Comment by ghostoy** [comment]
Are you building NW.js yourself? That's not necessary if you just want to change the creator info. And there is no `chrome_settings.gypi` file in nw14 or nw20. I think you could change `MAC_CREATOR` in `remoting/branding_Chromium` file.

**Comment by rogerwang** [comment]
close until more information is available.
