### ISSUE TITLE
Title bar not scaling properly between mixed DPI displays

### ISSUE THREAD

**Issue by jportoles** [nwjs/nw.js#5677]
Version: 0.20.0-sdk
OS: Windows 10

When a high pixel density display of a devicePixelRatio 2 (e.g. a Surface Pro) is plugged in to a low one of devicePixelRatio 1 (e.g. a 1080p monitor), the native windows title bar fixes its scaling to the first, looking comically large on the second display. This is consistent whether the app is started on the low pixel density display, or on the high one and then moved. The title bar remains at all times at the same fixed scaling.

The chromium `--force-device-scale-factor` flag makes no difference whether set or not, the title bar always exhibits this behavior regardless of it.

Expected: 
1) NW.js should detect the scaling of the current monitor where the app is launched and adjust the native title bar/frame around it, not just the primary one
2) When moving between displays, NW.js should redetect and readapt the native frame to the scaling of the new display (the default behaviour for native windows apps)

**Comment by Christywl** [comment]
Seem it works fine for me on Windows 10 with nwjs-sdk-v0.24.2.
Two displays(devicePixelRatio): 1 and 1.5
Start the nwjs app on the first display and move to the second, the window changes in the second display.

**Comment by Christywl** [comment]
close until there is more information
