### ISSUE TITLE
Identity chrome app not work

### ISSUE THREAD

**Issue by RajJariwala** [nwjs/nw.js#5681]
I used Identity chrome-app example. When I run using this command
**/Downloads/nwjs/nw /Downloads/Chrome-repo/chrome-app-samples/samples/identity/ --enable-logging=stderr** it opens. I clicked on signup it will open google dialog and at the end its give me error.
Error :
git
![error](https://cloud.githubusercontent.com/assets/25505443/22549574/f708cb1e-e971-11e6-983b-99014944240d.png)

I have nwjs-v0.19.4-linux-*64.tar.gz.
Similar to issue [#5574](https://github.com/nwjs/nw.js/issues/5574) in your repo.

In windows working fine but I can't get access token.

**Comment by Christywl** [comment]
I tried nwjs v0.20.2 with your steps, didn't meet this issue. A new window opened(chrome://chrome-signin/?access_point=6&reason=0) and 'Sign in to chrome' is shown, users could enter the account to login.
Environment:
nwjs-sdk-v0.20.2-linux-x64.tar.gz
ubuntu 14.04
![nwjs-5681](https://cloud.githubusercontent.com/assets/20039821/23193718/58613e68-f878-11e6-8c72-0dc9d7852ee9.png)

@RajJariwala , could you please try the latest release? Thanks.

**Comment by rogerwang** [comment]
close until more information is provided.
