### ISSUE TITLE
OSX - 0.21.0b1 - pdf in webview not loading, gives ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5682]
OSX 10.11.6 El Capitan

Problem occurs from 0.20.0 onwards - tested with 0.21.0b1. Works OK with 0.14.7 LTS.
Appears to be linked with the file:/// protocol. The webview works fine with a pdf file in the app root but when using a file in another local directory then file:/// is used and fails despite trusted permissions being set in package.json, etc.
Attached is a (simpler) wee project to demonstrate - just add nwjs binaries to PDFtest2 folder and replace username in index.html src file references - screenshots and error log in zip file.

Just as an aside I've noticed that 0.21.0 allows a SWF file to work again in webview - handy.
 
[PDFtest2.zip](https://github.com/nwjs/nw.js/files/749909/PDFtest2.zip)

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next nightly build.
