### ISSUE TITLE
Close print preview frame

### ISSUE THREAD

**Issue by joshterrill** [nwjs/nw.js#5683]
Is there any way to close the print preview frame from the main window print preview was opened from?

Edit: If not, what would be the best way to modify nwjs so that it can do this?

**Comment by conceptualspace** [comment]
https://github.com/nwjs/chromium.src/tree/nw13/chrome/browser/resources/print_preview

**Comment by joshterrill** [comment]
Thanks. Is there documentation on how to roll out a custom chromium.src with node webkit?

**Comment by conceptualspace** [comment]
http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/

**Comment by joshterrill** [comment]
From my understanding, even if I write that code, how will I be able to access it from my nwjs app context? They run on completely separate domains, the print being run on `chrome://`. How will I be able to access that? Or be able to send messages back to my app from the print preview context?

**Comment by conceptualspace** [comment]
ah i didnt read your message closely enough, "from the window it was opened from".. i was just thinking you could hack the UI itself; communication is another matter

can you elaborate on your use case? fyi there is a silent printing option if that is helpful -- #4911

**Comment by joshterrill** [comment]
Unfortunately silent printing will not happen. Here is the scenario, and a little background.

I have an app where when you exit the app, a modal/dialog comes up and says "Are you sure you want to exit?" and gives Yes or No options. Yes closes the webkit, no closes the dialog.

We have users who are going to pages, clicking print. The print preview window opens... then they decide they don't want to print, but instead of hitting cancel on the print preview frame, they click the "X" in the webkit application (because the top bar of the webkit is still visible). This causes the dialog message to show up UNDER the print preview frame, and to the user, they're trying to exit out of print preview, but it's just not doing anything.

So I was hoping that I could do something like if they hit the X in the webkit window, I could 
1. Check if print preview window was open or not (maybe by checking where focus in the app is/isn't?)
2. and close the print preview frame so they see the dialog message asking them if they want to close out of the app.

**Comment by joshterrill** [comment]
I noticed that the escape key triggers the print preview frame to close, so I thought maybe if I could call out to the OS to press the escape key when they press the X button and print preview is open. But the webkit window on close event does not get run while print preview is open. It only gets run once the webkit gets focus back. So if I have the following code:

```
win.on('close', function(event) {
 console.log('test');
});
```

I start my app, then open print preview, then hit the X on the app, nothing happens - no logs get fired, etc. But immediately after closing print preview, my log message shows up.

**Comment by conceptualspace** [comment]
so when listening for the on close event and u say nothing happens when u hit the "X" -- the window still closes?

**Comment by joshterrill** [comment]
No, when I say "nothing happens", I mean to the user nothing happens. When they hit the X, my dialog message asking them if they want to exit the app shows up, but it pops up UNDER the print preview frame. The app will not close unless they press "Yes" on that dialog. But they don't see the dialog because it's under the print preview window.

**Comment by conceptualspace** [comment]
how are you firing your confirmation dialog if not on close?

**Comment by conceptualspace** [comment]
alternatively what if you open a new window just for printing?

**Comment by conceptualspace** [comment]
(idea being you dont need the confirmation on the new window)

**Comment by joshterrill** [comment]
Good question on the confirmation dialog, I'll have to look into that on my specific app. I've been testing this on a vanilla webkit instance just to try to rule out possible issues with the app itself. 

And yes, a new window might be the way we'd have to go.
