### ISSUE TITLE
Latest NW.js 0.20+ causes touch events to freeze

### ISSUE THREAD

**Issue by matthew-dean** [nwjs/nw.js#5685]
This is probably a Chromium bug, but something NW.js users should be aware of. On Windows 10, using a touch screen, a sequence of rapid multi-touch events will suddenly cause all touch events to "hang". (The UI will become unusable and won't respond to touch events. If, however, you click on your app, then suddenly the browser quickly "catches up" and responds to all (or most of) your touch events.

The reason why I post this here: is it possible NW.js isn't correctly registering the main web page as the "foreground tab"? Background tabs in Chrome sometimes exhibit this behavior, I believe.

Whatever the reason, after 3 days of debugging and trying to figure out what in our app could possibly be causing touch events to not respond, re-compiling with NW.js 0.17.6 fixed the issue entirely.

**Comment by rogerwang** [comment]
Could you please post a sample? We'd like to find out whether the bug is in
NW or chromium.

Matthew Dean <notifications@github.com>于2017年2月4日周六 上午7:39写道：

**Comment by rogerwang** [comment]
Close until more information is provided.

**Comment by matthew-dean** [comment]
Sorry, the reason for not providing more info is that we're still getting this sporadically across all our NW.js apps now, and haven't been able to narrow down a cause. None of our NW.js apps before a certain date exhibited this behavior, and most but not all have these freezing problems. And it seems even setting the version to 0.17.6 has not addressed it.

**Comment by rotoglup** [comment]
We're encountering a similar issue on a project using nwjs v0.19.5.

It's not currently clear for us how to easily reproduce it, but when running with `--enable-logging`, the issue showed up at every use session after a few minutes.

**Comment by matthew-dean** [comment]
It's definitely not a Chromium issue. I think there's some issue with even delegation from the app frame to the browser window. It seems to act like the browser does not have the focus. Clicking on the app causes touch events to suddenly get "captured" and execute fairly quickly.

Also of note is that the main "app" is operating in an iframe, not sure if that makes a difference.

Because we could never solve the issue, we ended up switching to electron, which doesn't exhibit this behavior.

**Comment by rogerwang** [comment]
Someone reported touch event related issues and later found it's due to change in Chromium touch feature and triggered a bug in a library the app is used. So it would be easier to run your page in Chromium browser. If it works in Chromium but breaks in NW (which is rare case), we'd be happy to fix it with your page provided as a sample.

**Comment by rotoglup** [comment]
In my case, when it happens, I can't even open the context menu with a long press to access dev tools - I also saw the events execute quickly after plugging a mouse to manipulate the window.

Looks like a low level issue, not like a js lib issue.

If I get some repro easily, I'll let you know.

**Comment by nicomgd** [comment]
FWIW, we had the issue more often/easily when running our nwjs app with the ` --enable-logging` chrome flags, and the `chrome_log_file` environment variable set...

But yet no repro pattern...

**Comment by rotoglup** [comment]
For the record, we've ported our apps to electron, and the issue disappeared, so we basically dropped nwjs use because of this use.

**Comment by matthew-dean** [comment]
@rotoglup Yep, same. It definitely didn't happen in native Chrome and happened in NW.js, and it didn't occur in Electron, so we switched to Electron. Problem solved. Not being able to solve this meant NW.js was unusable for us.

@cupofnestor Definitely try switching to Electron. It is moderately painful at first, but having an actual community-supported auto-update system was a game changer for us. The app updates install in seconds vs. minutes for NW.js. For a public kiosk, Electron is more than stable. NW.js is not, as evidenced by this issue.

**Comment by rogerwang** [comment]
Please provide a sample page or url that works in Chrome but breaks in NW. Then we will reopen this issue.

With the information provided so far there is nothing we can act on. We can't reproduce it here either.

**Comment by rotoglup** [comment]
On my side, I could not reproduce the issue in my lab, it only happened on our client system which I can't access easily - it runs some Windows 10 version with IIyama touch screens (which had touch issues of their own) - and it was not easy to reproduce in synthetic use.

Not much of a help, I know.

**Comment by rogerwang** [comment]
Please provide hardware spec since this could be hardware specific: system model and touch screen model if it's not builtin. This could be helpful to track it down. 

btw, both upstream and Electron have similar bug reports.

**Comment by matthew-dean** [comment]
> btw, both upstream and Electron have similar bug reports.

@rogerwang I was not aware of this. Sorry if that was a misrepresentation. It just happened to fix the problem for us. I'm no longer at that company so it's impossible for me to contribute any helpful details. If I recall correctly, we encountered the issue on multiple brands of touch screens, with multiple versions of Windows, but only with NW.js, not with running in the Chrome browser, nor Electron. And the issue was limited to the app, not with other parts of the Windows UI or other apps. So, to us, it seemed very specific to NW.js, even if there may be problems that are described in similar ways for Electron.
