### ISSUE TITLE
Gmail issuies

### ISSUE THREAD

**Issue by lukoie** [nwjs/nw.js#5687]
This is what i've got for gmail for the latest nw.js (0.20.1) on my Win10 PC.
Is this the way it should look for the current version?
<img src="http://s008.radikal.ru/i304/1702/de/6cfff90f658b.png" border=0><br/>&nbsp;<br/>

**Comment by VasiliyIsaichkin** [comment]
0.20.2 win10/x64 corporate account
![170222-080149-61a2yqbjsb6piv0](https://cloud.githubusercontent.com/assets/1153891/23198011/68ed5fc0-f8d5-11e6-8b94-532b464830b0.png)

0.20.2 win10/x64 personal account
![170222-080548-02awzqv7awvotja](https://cloud.githubusercontent.com/assets/1153891/23198066/e04254ae-f8d5-11e6-9627-c592362c92f2.png)

**Comment by xzhan96** [comment]
@lukoie It works well for me with nwjs 0.20.1 and 0.20.2, could you double check? @VasiliyIsaichkin it seems the case also works well for you?

**Comment by Christywl** [comment]
It also seems work well for me with nwjs 0.20.2 on Windows 10.
![5687-1](https://cloud.githubusercontent.com/assets/20039821/23249589/03b7df16-f9e0-11e6-8ef0-5fa9f941adc4.png)

**Comment by VasiliyIsaichkin** [comment]
@xzhan96 everything works fine

**Comment by xzhan96** [comment]
@lukoie could you double check? If it also works fine for you, let's close this issue. Thanks.

**Comment by rogerwang** [comment]
close until more information is provided.

**Comment by lukoie** [comment]
still the same

![screenshot 2017-03-19 015](https://cloud.githubusercontent.com/assets/312253/24081784/b251ae40-0cc2-11e7-83ae-3f27ddee453b.png)

**Comment by lukoie** [comment]
nwjs-v0.21.3-win-x64 
and now it works fine!
thanx
