### ISSUE TITLE
Hotkeys?

### ISSUE THREAD

**Issue by lukoie** [nwjs/nw.js#5688]
I'm certainly sure that in the previous versions of nw.js it was possible to alt+arrows, F5 and backspace.
I can't find anything related to this on the nw.js' website.
Is it not possible at the moment to back/forward and refresh the pages, or should i tune it somehow?

**Comment by baconface** [comment]
I believe you have to write and assign your own hotkeys now.

**Comment by lukoie** [comment]
any tips about how to do that?

**Comment by baconface** [comment]
You can register a [system wide shortcut](https://github.com/nwjs/nw.js/wiki/Shortcut) or do it with a [JavaScript](https://www.google.com/search?q=javascript+keyboard+hotkey) or [jQuery](https://www.google.com/search?q=jquery+keyboard+hotkey) library.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
