### ISSUE TITLE
Raspberry Pi binary ?

### ISSUE THREAD

**Issue by caffaware** [nwjs/nw.js#5690]
Is it possible to run nwjs on a raspberry pi ? Or in other words do you perhaps provide any docs on how to compile for the arm architecture ? Would love to play with it on a RPi

**Comment by kailniris** [comment]
https://github.com/jalbam/nwjs_rpi

**Comment by caffaware** [comment]
Awesome ! Is there also a possibility to compile it ourselves, would like to have the newest nwjs versions

**Comment by kailniris** [comment]
There are lots of ARM build related issues and topics around.
https://github.com/LeonardLaszlo/nw.js-armv7-binaries

Anyway if you want to ask questions use the google group, post only issues here.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by kentmw** [comment]
For google searchers: https://github.com/jalbam/nwjs_rpi is not built with the the most recent versions of nw. I asked the maintainer if they would build a newer binary, but they're busy.
