### ISSUE TITLE
"Your preferences can not be read" message pop up when running nw.js from ubuntu

### ISSUE THREAD

**Issue by dk1301** [nwjs/nw.js#5691]
Version: nwjs-v0.20.1-linux-ia32/nwjs-v0.19.5-linux-ia32
OS: Ubuntu 16.04

Hi all,
I'm trying to run nw with a folder that contains my html front as following : 

> /home/npt/TEMP_2/nwjs-v0.20.1-linux-ia32/nw /home/npt/TEMP_2/frontend

and I get the following message in terminal :
**[11798:11798:0207/154100.026830:ERROR:desktop_window_tree_host_x11.cc(1131)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)**

and in the application the pop up message :
**"Your preferences can not be read. Some features may be unavailable and changes to preferences won't be saved."**

when I run the above command with sudo or gksu everything seems ok . The same happened for the 0.19.5 version as well.
I also found that this problem was happening on chrome browser as well.
Since I don't want to run it with root access , could you give some hint on how to solve it.

**Comment by rogerwang** [comment]
It should be that the file in the user data dir was changed to wrong permission/ownership. Please post this question to the mailing list as it's not a NW issue.
