### ISSUE TITLE
NW + SQLite3 "Module unregistered" Errors when using a File as Database

### ISSUE THREAD

**Issue by adikas2** [nwjs/nw.js#5693]
Hello there,
i'm kinda new to nodewebkit and trying to get sqlite3 to work with it.

**Operating system**:
Win 8.1 X64
**Tools used**:
    Python 2.7                  (Installed via "npm install -g windows-build-tools")
    MS Developers Tools (Installed via "npm install -g windows-build-tools")
    Nodejs 7.5 X64
    NW 0.20.1 X64 SDK

I compiled node-sqlite3 3.1.8 with the following command:
```shell
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.20.1
```
See output:
[sqlite3.install.txt](https://github.com/nwjs/nw.js/files/761898/sqlite3.install.txt)

I can use sqlite without problem when using a memory db. But when I want to use a filedb it gives me everytime Module unregistered errors:

> Uncaught Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\SQLITETEST\app\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)

Usualy this error comes from having version mismatch, but i didn't upgrade any of my Tools.

Despite throwing the errors the commands get executed, but still the debug console is unusable, cause everytime a command is executed it restarts the debug window.

Index.html:
```html
<!DOCTYPE html>
<html>
<head>
	<title>TEST SQLITE</title>
	<script src="node_modules/nw-dev/lib/dev.js"></script>
	<script>
		var sqlite3 = require('sqlite3').verbose();
		var db = new sqlite3.Database('test.db');     
		//var db = new sqlite3.Database(':memory:');
		db.serialize(function() {
			db.run('CREATE TABLE IF NOT EXISTS `test` (`id` INT)');
			//THIS THROWS ERRORS WHEN USING 'test.db' AS DATABASE
		});

		db.close();
	</script>
</head>
<body>
</body>
</html>
```
package.json:
```json
{
  "name": "SQLite_TEST",
  "version": "0.0.1",
  "description": "BLABLA",
  "main": "index.html",
  "author": "Me",
  "license": "GPL-3.0",
  "devDependencies": {
    "nw-dev": "^3.0.1"
  }
}
```
[app.zip](https://github.com/nwjs/nw.js/files/761902/app.zip)

Any ideas how to fix Module did not self-register errors?

Thx in advance.

**Comment by rogerwang** [comment]
It works for me and the db file is created. I'm using 0.20.2-sdk ia32 btw.

**Comment by rogerwang** [comment]
close until more information is provided.

**Comment by adikas2** [comment]
Thx for the reply.
Sorry, since this is a pet Project (or Hobby) I didn't have time to check back earlier.
I tested it with 0.20.3-sdk x64 and it doesn't happen anymore.
