### ISSUE TITLE
feature request: disable print headers and footers

### ISSUE THREAD

**Issue by conceptualspace** [nwjs/nw.js#5694]
in chrome, the print headers and footers output the page URL (useful). however in an nw app, the "URL" is really just some random extension ID which generates noise on printouts. ex:

`chrome­extension://adeblneekhebjfaocnggahcchppgfchf/src/main.html...`

which really makes nw unsuitable for any sort of app that depends on printing

**Comment by kailniris** [comment]
http://docs.nwjs.io/en/latest/References/Window/#winprintoptions

**Comment by rogerwang** [comment]
close as it's already provided.

**Comment by conceptualspace** [comment]
but the existing method is only for "silent printing" -- what about when using print preview, selecting a printer, and all the other options avail when not using nw's print api?

**Comment by conceptualspace** [comment]
it was actually the strange behavior of the print preview dialog popping up and closing (#4911) that led me away from it and to chrome's default -- but from a development standpoint i guess it makes sense to continue to improve 4911 than to hack up the chrome UI separately 👍
