### ISSUE TITLE
Chromium args as a command line switch?

### ISSUE THREAD

**Issue by Batcherinho** [nwjs/nw.js#5695]
Is there a way to pass chromium args as a command line switch, instead of defining entries in the package.json file?  

Something like:
` --chromium-args="--window-position=100,200"`

An example would be wanting to pass window-position values that can be defined dynamically, without the need to manually manipulate the window values through nw object.

If not, are there any plans to support this in the future?

**Comment by rogerwang** [comment]
The arguments can always be used in command line.
