### ISSUE TITLE
WebGL doesn't work in NW.js applications since 0.13

### ISSUE THREAD

**Issue by kakurasan** [nwjs/nw.js#5696]
chrome://gpu (`./nw --url="chrome://gpu"`) says "WebGL: Hardware accelerated" and WebGL works in HTTP/HTTPS sites (http://, https://) and local files (file://), but since version 0.13, WebGL doesn't work in NW.js applications.

* OS: Ubuntu 16.10
* Version: 0.20.1

**Comment by George35mk** [comment]
check if you can enable the flags in the package.json

**Comment by rogerwang** [comment]
I took a sample from https://github.com/WebGLSamples/WebGLSamples.github.io, wrap it with a simple package.json and it's working for me.

**Comment by kakurasan** [comment]
Adding `"chromium-args": "--enable-webgl"` to package.json doesn't work. Command line option "--enable-webgl" also doesn't work. (Note: `"chromium-args": "--disable-webgl"` disables WebGL in version 0.12.3)

It seems WebGL doesn't work *only in chrome-extension:// URLs*.

**Comment by rogerwang** [comment]
I didn't add any argument and webgl is working with  chrome-extension:// protocol . here is my package.json

````
{
  "name": "Test",
  "main": "field/field.html"
}
````

**Comment by George35mk** [comment]
just use Threejs

**Comment by George35mk** [comment]
stop using webGL  just use threejs and is have more examples end is more easy

**Comment by kakurasan** [comment]
> I didn't add any argument and webgl is working with  chrome-extension:// protocol . here is my package.json

This doesn't work for me (but `./nw --url="http://webglsamples.org/field/field.html"` works). The page says "It does not appear your computer supports WebGL. Status: Web page was not allowed to create a WebGL context."

![0 20 2-linux64-field](https://cloud.githubusercontent.com/assets/10556453/22931268/5e079b30-f307-11e6-9a33-85ee09060863.png)

**Comment by George35mk** [comment]
were you take this example ?? give  me the link

**Comment by George35mk** [comment]
omg my computer is gona expload with that example .  
I use Three.js for my 3D stuf dont start from webGl directly is very complecate start with this 

[Threejs](https://threejs.org/examples/#webgl_animation_cloth)

and is gona be more more easy if you start from this 

[Simple Cube](https://threejs.org/docs/index.html#Reference/Geometries/BoxGeometry)

**Comment by George35mk** [comment]
Start from this Site [Create a  simple 3d scene](https://threejs.org/docs/index.html#Manual/Getting_Started/Creating_a_scene)

**Comment by AshleyScirra** [comment]
Most likely Chrome now blacklists the GPU. The correct flag to avoid this is `--ignore-gpu-blacklist`

**Comment by rogerwang** [comment]
close as works for me and it should be hardware related with a workaround.

**Comment by kakurasan** [comment]
> Most likely Chrome now blacklists the GPU. The correct flag to avoid this is `--ignore-gpu-blacklist`

This option works for me (the GPU is Radeon HD 4200). Thanks.
