### ISSUE TITLE
接收再次启动时的消息

### ISSUE THREAD

**Issue by wurichengn** [nwjs/nw.js#5697]
由于英语很差，在这里直接使用中文提问，很抱歉
现在使用nw.JS开发了一个程序，在使用的过程中是通过外部程序打开的，nw.js不会同时打开两个程序，我希望能够当我已经存在一个程序的同时，能接收到再次打开的操作，以此处理一些相关事务，如果能接收参数的话那就更好了，不知道有没有方法可以实现。

**Comment by rogerwang** [comment]
Please use English so all users can read. And please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
