### ISSUE TITLE
listen restart

### ISSUE THREAD

**Issue by wurichengn** [nwjs/nw.js#5699]
Because English is very poor, can only translate here, I'm sorry
Now use the nw.JS developed a program, in the process of using is opened by the external program, nw.js will not open the two programs at the same time, I hope that when I have a program at the same time, can be received again open operation, in order to deal with some related affairs, if it can receive parameters the better, do not know if there is no method can achieve.

**Comment by rogerwang** [comment]
Could you please show a minimal sample to reproduce your issue?

**Comment by rogerwang** [comment]
close until more information is provided.
