### ISSUE TITLE
Menu Item Bugs

### ISSUE THREAD

**Issue by dubcanada** [nwjs/nw.js#570]
Hey,

I am playing around with the menu item trying to figure out how exactly it all works. And I seem to have ran into a few bugs.

https://gist.github.com/dubcanada/771ddc3d5a810d183d97

It seems that if I try to append an item I already appended to a menu attached to the menubar it hangs the inspector.

It also seems that any callback attached to the menu item (in the above case "Click me") doesn't get called. Even when you click on it.

Mac 10.8 - using the latest NW

**Comment by rogerwang** [comment]
should be fixed in 0.13.0 RC.
