### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by onny** [nwjs/nw.js#5705]
Hey,
as of the latest stable nwjs version (20.2), there is still no support for running it natively on a Wayland desktop. I guess this depends on Chrome upstream support?
![2017-02-14-133336_swaygrab](https://cloud.githubusercontent.com/assets/757752/22929148/72215f18-f2ba-11e6-8715-da63c27ca523.png)
Screenshot above shows Wayland desktop and the program xprop confirming that nwjs is running inside xwayland.
Thank you and best regards,
Jonas

**Comment by rogerwang** [comment]
Yes, it need upstream support. The latest status from upstream is: https://bugs.chromium.org/p/chromium/issues/detail?id=295089

**Comment by troysyh** [comment]
The upstream issus has beed fixed last month.

**Comment by rogerwang** [comment]
@troysyh good to know it. Will look to enable a wayland build in NW.js.

**Comment by tolrtd** [comment]
Hi, has anything been done with this?  Will there be more to the development than just the upstream fixes?

**Comment by folcik** [comment]
@rogerwang I have upstream 73.x working on Wayland/Weston on ARM7 with the Igalia work.  Can I use this Chromium to build nwjs for Wayland, or do I have to use the nwjs fork of Chromium?  Any advice on going down this path?

**Comment by tolrtd** [comment]
@rogerwang I have upstream 73.x working on Wayland/Weston on ARM7 with the Igalia work. Can I use this Chromium to build nwjs for Wayland, or do I have to use the nwjs fork of Chromium? Any advice on going down this path?

**Comment by travankor** [comment]
Chromium v87 adds the ozone platform, which supports wayland, to the default chromium build.

You can enable it by passing the flags ` -enable-features=UseOzonePlatform -ozone-platform=wayland`

**Comment by travankor** [comment]
I tried appending the flags to `package.json` on the latest 0.50 nightly, but it still ran in Xwayland. So nwjs's forked chromium does not seem to properly activate the ozone build option or there's some other nug affecting this.

**Comment by rogerwang** [comment]
This build should fixed it: https://dl.nwjs.io/live-build/nw50/20201018-085740/c7de0d21c/v0.50.0-beta1/

**Comment by travankor** [comment]
Thank you, that does fix it

**Comment by JoaquinDecima** [comment]
How can I configure the properties? for example, the layer...
