### ISSUE TITLE
OSX - since 0.19 flash in embed or object tag not working using file:///

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5706]
Similar to #5682 in that file:// seems to be problematic (PDF was fixed OK with #5682).
Attached test app shows that a locally sourced flash file using file:/// with embed or object tags will not work. 
Tested with 0.21.0b2-sdk-osx and appears to be faulty from 0.19 onwards. Tests OK with 0.14.7 LTS and 0.18

![baddo-0210b2](https://cloud.githubusercontent.com/assets/11089335/22945308/b07ce594-f2eb-11e6-9c7d-0951235c37e7.jpg)

[test.zip](https://github.com/nwjs/nw.js/files/775099/test.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
