### ISSUE TITLE
Can I capture the certificate error ?

### ISSUE THREAD

**Issue by lili21** [nwjs/nw.js#5707]
I want a customer page for the error instead of default page. 

This is what I mean about default page.

![certificate errrr](https://lh5.googleusercontent.com/DHCcVQTD_eUjtZQP9v4B9ajMJGsCh717F6-dwFtSvAhS8Xd-R8dqettLsMSRS-wUp3KxFLCNL8-oed2GUyMjQspvNWc3xdfNcTTta1xIEhLwrMghRaIIy99Z-otlaHBxeDTxNdQ)

I am using nw.js@14.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
