### ISSUE TITLE
NW.js Mouse Pointer Problems On Multi-Screen Setups

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#5709]
**General Information:**
- Using NW.js version 0.19.0 & newer
- Windows 7 with latest drivers
- Dual Screen Setup

**Problem Description:**
I'm running a packaged _Construct 2_ game (HTML5) in fullscreen mode.
In my game users are able to move the mouse pointer outside of the playable area, which can be considered as a major annoyance. Most of the times users are required to click on the NW.js window to get it back in focus again, this is a big deal especially for people like me that use NW.js to run their HTML5 video games.

As a side note, I think this happens because NW.js's fullscreen method is more of a "borderless fullscreen" mode instead of a native-like "exclusive fullscreen" mode.

**Observed Result**
I'm able to move the mouse pointer outside of the screen in fullscreen mode.

**Expected Result**
NW.js should lock the mouse pointer on the active screen and prevent it from leaving the screen.

**Comment by rogerwang** [comment]
It should be purpose of this API: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

**Comment by TheRealDannyyy** [comment]
Alright, I think I can make use of that.
Thanks for the info.
