### ISSUE TITLE
Mac App Store build for v0.20.2

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#5711]
I can't seem to find a latest MAS build for nw.js.

The one linked in the docs is http://dl.nwjs.io/v0.19.5-mas-beta/

Isn't there one available for every release? And if not, is there a reason for that?

**Comment by rogerwang** [comment]
We are working on this in nw20-mas branch. A previous 0.20 version passed Apple's review, but latest 0.20.2 based version was blocked in the review. Will keep this thread updated.

**Comment by chino23** [comment]
Ok, thanks for the update Roger!

**Comment by rogerwang** [comment]
Update: the reviewer from Apple thinks our app is too simple and rejected the new version (previous reviewers approved older version). So we either need a better application to test our binary against Apple's review process or need someone in the community to test for us.

Apple reviewer's comment attached:
````
Hello,

Thank you for your resubmission. However, upon further review, we found that your app is out of compliance with the following guideline(s): 

Design - 4.2


We found that your app provides a limited set of features and functionality to users and is therefore not appropriate for the App Store.

Next Steps

We encourage you to review your app concept and evaluate whether you can incorporate additional features to enhance the user experience.

For app design information, see the macOS Human Interface Guidelines. The Human Interface Guidelines provide in-depth guidance on the characteristics of a great Mac OS X app and describe appropriate technologies and interface elements of a Mac OS X app.

You may also want to review Programming with Objective-C, a guide to getting started with the Objective-C programming language.
````

**Comment by rogerwang** [comment]
Please try this build: http://dl.nwjs.io/live-build/02-23-2017/nw19-1ab035d-0be6760-a2ef613-43092ca/v0.20.2/nwjs-mas-v0.20.2-osx-x64.zip

**Comment by chino23** [comment]
Ok thanks Roger, I'll give that one a try

**Comment by rogerwang** [comment]
merge into #4556

**Comment by Arti3DPlayer** [comment]
@chino23 any luck ?
