### ISSUE TITLE
Mac App Store build - no way to compile with nwjc?

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#5721]
I just checked the 0.19.5 MAS build, but I don't see the nwjc in there.

Does that mean we can't compile the sources for that one? Is that a restriction in the app store?

Or can I just use the nwjc from the non-MAS 0.19.5 build?

**Comment by rogerwang** [comment]
You can just use the one from non-MAS.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by chino23** [comment]
Thank you
