### ISSUE TITLE
[Features] Open showDevTool for Node Context at Runtime

### ISSUE THREAD

**Issue by MeowWoem** [nwjs/nw.js#5723]
Hi! First sorry for my bad english.

In NW.js you can open a DevTools for a Window with "win.showDevTools()"  but you can't open a DevTools for the Node Context.

Can you add a method "Window.showDevToolsNode(callback)" or something like that?

I know you can open it from the context menu but if per example i wanna customize the context menu i can't anymore open Background DevTools

**Comment by bachel** [comment]
Hello,
If you want to open DevTools for _generated_background_page.html use this

`chrome.developerPrivate.openDevTools({ renderViewId: -1, renderProcessId: -1, extensionId: chrome.runtime.id})`

**Comment by rogerwang** [comment]
@bachel cool. I was thinking of but cannot recall this when the issue was reported. It's actually used in our test cases.
