### ISSUE TITLE
Backspace \u0008 character visible in 0.20.x

### ISSUE THREAD

**Issue by tolrtd** [nwjs/nw.js#5724]
In 0.19.x and below, the backspace character is not visible in UTF-8 encoding.  In 0.20.x, I see the backspace character as either an inverse bullet (a black rectangle with a white dot in the center) [or a "male gender" symbol].

Demo recreate:

package.json
```
{
  "name": "Demo",
  "main": "index.html",
  "description": "Demo",
  "version": "1.0.0"
}
```

index.html
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<style type="text/css">
		#test:before {
			content:'\b'
		}
	</style>
</head>
<body>
	<div>&#0008;</div>
	<div id="test"></div>
</body>
</html>
```

**Comment by Christywl** [comment]
I can reproduce this issue, but there are some difference on the different platforms.
`1. Windows 8`
![windows8](https://cloud.githubusercontent.com/assets/20039821/23287076/2cf8a4f0-fa76-11e6-940f-34f75ff20919.png)

`2. Linux and Windows 10`
![linux](https://cloud.githubusercontent.com/assets/20039821/23287056/09c0b950-fa76-11e6-81df-dfea26aa897e.png)
![windows10](https://cloud.githubusercontent.com/assets/20039821/23287080/316b834a-fa76-11e6-8716-fa3c6da91bcb.png)

**Comment by rogerwang** [comment]
@Christywl thanks. does it reproduce in upstream?

**Comment by Christywl** [comment]
@rogerwang , yes, it also reproduces on upstream 56.

**Comment by rogerwang** [comment]
@tolrtd please report this to Chromium upstream.
