### ISSUE TITLE
set main to .js,but It is invalid

### ISSUE THREAD

**Issue by Hsinky** [nwjs/nw.js#5727]
![image](https://cloud.githubusercontent.com/assets/10111222/23296167/c2cee72c-faae-11e6-885d-271e5f23f004.png)
![image](https://cloud.githubusercontent.com/assets/10111222/23296172/ca8db146-faae-11e6-870b-42624b090b84.png)

**Comment by Christywl** [comment]
Reproduced. Window frame is still visible when setting `main` as `main.js` and `frame:false`.

**Comment by rogerwang** [comment]
The 'window' field in manifest applies only when the main file is html. If the entry is JS, you can open the first window with nw.Window.open and pass the parameter there.
