### ISSUE TITLE
Unable to capture uncaughtExceptions in node context

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#5728]
NW: 0.14.7 SDK - LTS
OS: Win 7

Hi guys,
It looks like 
`process.on('uncaughtException', function(err){
console.log('Caught: ', err);
})`
isn't working as expected. The error is always captured by browser instead of the above handler.
I am throwing an error by running a script using require() inside the node context. But, it's captured by the browser instead of my handler. I have seen that there was an issue #3061 in which, browser exceptions were also captured by 'uncaughtException'. Have those changes lead to this behaviour or am I missing out on something here?

Thanks for your efforts.

**Comment by Christywl** [comment]
It seems be same as #3601, with the test case in #3601, the issue is reproduced, the uncaught Exceptions is captured by browser. @ghostoy , @rogerwang , could you please help check?

**Comment by rogerwang** [comment]
@Christywl does it happen only in 0.14 branch?

**Comment by Christywl** [comment]
@rogerwang , I used nwjs-sdk-0.20.3 to try the test case, it is still reproduced.

**Comment by rogerwang** [comment]
@Christywl could you please upload the case you used to reproduce? Thanks.

**Comment by RohitSharma27** [comment]
The test case that @christywl has used and its result should be the desired behaviour. In the above test case, a browser error is being thrown and browser is capturing it so, it's valid behaviour. My issue is that uncaughtexception isn't working. Browser is also capturing the errors thrown in node modules/context in 0.14.7 LTS

**Comment by rogerwang** [comment]
@Christywl please give the exact case you used to reproduce *this* bug.

**Comment by Christywl** [comment]
@RohitSharma27 , sorry for my misunderstanding before.  I wrote another test case:
index.html
```
<!DOCTYPE html>
<html>
<body>
<script>
process.on('uncaughtException', function(e) {
  console.log("Caught Error:" + e);
});
var url = require('url');
var requestURL = "http://example.com:1234/path?query=string#hash"
console.log(url.parse(requestURL).hostname); // valid url
url.parse(error_parameter).hostname; // invalid url
</script>
</body>
</html>
```
Result:
![1](https://cloud.githubusercontent.com/assets/20039821/23533569/827bf072-ffed-11e6-9203-0baadc810b11.png)

'uncaughtException' catches the exception. Is there anything wrong in my test case? If so, could you please share your detailed test case for me to reproduce this issue?

**Comment by RohitSharma27** [comment]
Hi @Christywl ,
Please find the attached zip file. You can unzip it and place it inside the same directory as your nw.exe
Once you run the application, open the dev tool and call `nodeFunction()`. Since, this code runs inside node context, the error should have been captured by our handlers instead of the browser. If that's not the desired behaviour then please let me know with an explanation.
Thanks for your time.
[package.nw.zip](https://github.com/nwjs/nw.js/files/815951/package.nw.zip)

**Comment by Christywl** [comment]
@RohitSharma27 , I used your attached files. Run the app, open the dev tool and call `nodeFunction()`, the result is:
![2](https://cloud.githubusercontent.com/assets/20039821/23544033/16f24fca-0030-11e7-9baf-3e0e198e82de.png)

If I add `nodeFunction();` in the app.js, the result is:
![3](https://cloud.githubusercontent.com/assets/20039821/23544053/3589a078-0030-11e7-9600-a565d48bf788.png)

**Comment by RohitSharma27** [comment]
Hi @Christywl , 
You're running it on nw0.20.3 while I am using 0.14.7 LTS. Anyways, you will get the same output on LTS. I had the impression that calling nodeFunction() from dev tool should also be captured by uncaughtException handler. It works fine if it's called from the application's JS code. I think we can close this issue if this is the desired behaviour.

**Comment by Christywl** [comment]
@rogerwang , could you please help confirm if it is the desired behaviour?

**Comment by rogerwang** [comment]
Yes, this is expected, as devtools handles this directly via v8 inspector API.
