### ISSUE TITLE
App freezes randomly

### ISSUE THREAD

**Issue by RohitSharma27** [nwjs/nw.js#5729]
NW: 0.14.7 LTS
OS: Mac OS Siera/El Capitan(10.11.6)

Hi guys,
We have an NW based application for both Mac and Windows. Recently, we've got complaints that the application just hung up. These issues have been more frequent on Mac than windows. They basically happen when the app is left idle for some time(it isn't consistent though). We don't know at which point of time it became unresponsive. I have also enabled the chromium logs using `--enable-logging --v=1 --no-sandbox`. The application became unresponsive and I've been studying the chromium-debug.log file since then but, it hasn't been much useful. We have a logging system where we write the data into a log file using a node-module(and this system has been in place since application's inception and we've never seen app's unresponsiveness in NW v0.12.3 and before). When the application becomes unresponsive, you can't execute any JS so, we just have to force quit the app. I'll monitor the CPU usage when I see this issue again. Because of this halt in JS execution, our logger is no more good. From the 3/4 application logs that I've, I can say that there's no pattern and it hung up at different span of execution. I have been looking out to see if some code is hi-jacking the JS thread(both windows and mac application share ALMOST similiar JS code). We have few native node modules of our own but, the thing is that the issue isn't consistent and we have been unable to isolate it. I have following questions about this.

- Is there any other way to enable more detailed logging?

- Can disk I/O thread somehow block the JS thread?

- What are the ways to block a JS thread?

- May be the renderer process or the browser process has halt due to some reason and that has made the app unresponsive? How do I eliminate  this possibility? Or, if this would have been the case then the app would have had crashed instead? I can't start a new renderer process because I can't execute JS in dev tool(I was thinking of opening a new window with different domain and chromium would have started a new renderer process). Is there some other way?

I know that this isn't detailed enough but, any help or guidance would be appreciated. It looked like an issue to me as it came in to the picture after NW 0.14.7. 
Thank you for your efforts.

**Comment by rogerwang** [comment]
Please use the latest version for the macOS version in your report. The
0.14 version is for legacy OSX versions and Win XP/vista only.

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by RohitSharma27** [comment]
Hi Roger,
Upgrading from the LTS version to the current stable version would be the last road we would like to take. Just to rule out the possibility that some code in our application isn't causing this issue, I have been analysing the application. There are basically 4 processes associated with our application. "One" App process and "three" App Helper processes.
The "App process" should be the browser process as per chromium's architecture (also, this is the parent process of every other process). One of the helper process is associated with "Dev tool", as it comes and goes with the dev tool. Second helper process should be the "renderer process" as the files placed in "app.nw" directory are being executed inside this process (there is just one window running the application. Also, the native node modules are running in this process). Third helper process should be the crash handler process for NW ( ghostoy mentioned about this process in one of his comments in an issue), also this process uses the least number of threads and you can kill this process without affecting your application. It restarts as soon as you kill it.
This is the interesting part. When the app became unresponsive all of the 4 processes were in sleeping state, they never woke up. There was 0 network activity except for the browser process, it was sending and receiving one packet which should be chromium's internal code, I guess. The other 3 processes had 0 network activity which should not have been the case as the app uses one active web socket connection.
The application becomes unresponsive only when you leave it in the background for some time and even then its occurrence is so less. But, it happens and can't be overlooked. I am hoping to get to the root cause and be sure that it'd be worth the effort to migrate  from LTS version to the current stable one.

**Comment by rogerwang** [comment]
Upgrading 0.14 to 0.20 should be straight forward as the new version is supposed to be a drop-in replacement. The 0.14 version shouldn't be really called LTS so we changed the name later in our website. Because it's sole purpose is to support legacy OS version. And there is much code in the new version for supporting the current OS well.

**Comment by madaono** [comment]
it happend to me too ,im using 0.14.7 for windows XP
