### ISSUE TITLE
webview does not work correctly when "node" added to Chrome app manifest

### ISSUE THREAD

**Issue by marlarius** [nwjs/nw.js#5730]
When "node" is added in the permissions in manifest.json in a Chrome App, a webview is not working immediately after the app has started. For example, the request handlers are undefined.

If you add a delay of say 500 ms, it works.

In the attached example it will print the stringified request handlers of the webview 1) just after startup and 2) after a delay. Only the delayed print will show the handlers.

If you remove node from the permissions, both are printed out correctly.

It is probably the whole UI that is delayed by adding node permission.

Also, the font changes when adding node to permissions. Why?

Sample tested in nwjs-sdk-v0.20.3-linux-x64 on Linux Mint 18.

[webviewtest.zip](https://github.com/nwjs/nw.js/files/801561/webviewtest.zip)

**Comment by Christywl** [comment]
I can reproduce this issue with nwjs-sdk 0.20.3 on Linux. The request handlers are undefined and the font changes when adding 'node' to permission. (it works fine on Chrome)

**Comment by rogerwang** [comment]
@marlarius pages in Chrome App is injected with built-in CSS files of Chrome by default. In NW.js Apps this is disabled.

See https://github.com/nwjs/chromium.src/blob/nw20/extensions/renderer/resources/extension_fonts.css

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by marlarius** [comment]
Is it the issue with webview not being ready that is fixed?

Re. the CSS I now simply use these reset styles and the app looks the same:

`html, body {
    overflow: hidden;
}
body {
    cursor: default;
    font-family: "Noto Sans", Arial, sans-serif;
    font-size: 75%;
    display: block;
    margin: 8px;
}
`

**Comment by rogerwang** [comment]
yes, it's fixed and available in the nightly build: http://dl.nwjs.io/live-build/

**Comment by marlarius** [comment]
Thanks, just tried and the bug is indeed gone :)
