### ISSUE TITLE
nwjc failure compiling async/await

### ISSUE THREAD

**Issue by VasiliyIsaichkin** [nwjs/nw.js#5731]
When I try to compile code via nwjs.exe with async/await, I got a message:
_Failure compiling 'test.js' (see above)_

Sample code:
```
function delay(ms) {
	return new Promise((resolve) => {
		setTimeout(resolve, ms);
	});
}

async function test() {
	console.log('Step 1');
	await delay(1000);
	console.log('Step 2');
}
test();
```
NWJS v.0.20.3 win x64
Windows 10 x64

**Comment by VasiliyIsaichkin** [comment]
It applicable also for just
`async function test() {}`

**Comment by rogerwang** [comment]
Thanks for reporting. Please try again with 0.21.0 rc version. It seems to work for me with the async sample.

**Comment by VasiliyIsaichkin** [comment]
nw.js v0.21.0-rc1 win x64 - сompiled successfully
