### ISSUE TITLE
Unable to Download nwjs 20 on MAC OS Sierra(10.12.3 beta).

### ISSUE THREAD

**Issue by ShivaniPahuja02** [nwjs/nw.js#5735]
Hi,

We are upgrading the nwjs version from 14.7 to latest nwjs 20.3 on MAC OS Sierra(10.12.3 beta). gclient sync command is not downloding the source, only showing message 
"Still working on" on terminal.

We are following the below link to download the nwjs source code.
https://github.com/nwjs/nw.js/blob/nw20/docs/For%20Developers/Building%20NW.js.md

As a Prerequisites we have installed depot_tools and added depot tools to the end of path variable as stated on below link.

"https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md"

Used below command to generate .gclient file.
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw20

gclient sync --with_branch_heads

but Nothing get downloaded src folder is still empty. we have tried nw19 and different mac verison as well but still getting same result.

We request you to please update if we are missing any change.

Regards,
Shivani Pahuja

**Comment by rogerwang** [comment]
It's a big repo to download -- several gigabytes. So it looks hanging. Please check the hidden directory '.git' in the src dir. And continue the discussion in the mailing list as it's not a bug.

**Comment by ShivaniPahuja02** [comment]
Hi Roger,
Thanks for quick reply.

To create .gclinet we have to use
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/
nw20.

But in the page it is written nw17, Do we need to use nw17 to get nw20 code.

Regards,
Shivani Pahuja
