### ISSUE TITLE
chooseDesktopMedia including audio on Mac

### ISSUE THREAD

**Issue by caffaware** [nwjs/nw.js#5736]
I'm developing a screensharing app using nwjs and use the below code. On windows I can get the audio sharing working on a mac this doesn't work, is this a bug ?

```
nw.Screen.chooseDesktopMedia(["screen","audio"], function(streamID)
{
localVideoStream = null;
if (!streamID)
{
return;
}
var videoConstraints =
 {
mandatory:
{
chromeMediaSource: 'desktop',
chromeMediaSourceId: streamID,
maxWidth: 1920,
maxHeight: 1080,
maxFrameRate: 30,
minFrameRate:5
},
};
var audioConstraints =
{
mandatory:
{
chromeMediaSource: 'system',
chromeMediaSourceId: streamID,
}
};
navigator.webkitGetUserMedia({audio: audioConstraints, video: videoConstraints}, mediaStreamSuccess, mediaStreamError);
});

function mediaStreamSuccess(stream)
{
localVideoStream = stream;
localVideoStream.getVideoTracks()[0].onended = function (){//};
};
function mediaStreamError(error)
{console.log("Stream error:"+error);};
```

**Comment by Christywl** [comment]
@caffaware , I just used your code(index.html) to reproduce this issue. The results on different platforms:
Windows:
![2](https://cloud.githubusercontent.com/assets/20039821/23646198/be6bad9c-034a-11e7-9f5d-8aaa3623f252.png)
Mac:
![3](https://cloud.githubusercontent.com/assets/20039821/23646209/c9f1964a-034a-11e7-8a39-dffb5fa0bc99.png)

Are the results same with yours? If not, please share me the detailed reproduced steps? Thanks.

**Comment by caffaware** [comment]
Correct, the results are exactly the same. I've tried to add an audio stream after the video stream was added, but with no luck either

**Comment by rogerwang** [comment]
@caffaware Chrome doesn't support capturing whole system audio on OSX. More information is in https://bugs.chromium.org/p/chromium/issues/detail?id=223639

So the "share audio" button will not be visible.
close as this is a limitation in upstream.
