### ISSUE TITLE
Nwjs crash when opening new window without menu on windows

### ISSUE THREAD

**Issue by zedissime** [nwjs/nw.js#5737]
Hello,

The application crashes when you try to open a new window without the window menu.
I've noticed that setting `win.menu = null` makes the application instantly crash.
I may have misunderstood the related [documentation](http://docs.nwjs.io/en/latest/References/Window/#winmenu) but it was working at least on 0.20.1 (I've skipped the 0.20.2). Also, I can't reproduce the error on MacOS. 
I also propose to add the [http://dl.nwjs.io/](http://dl.nwjs.io/) link on the [Understanding Crash Dumb](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/) documentation, in order to easily find the sym files.

* **Nw** : 0.20.3-sdk-win64 && 0.20.3-normal-win64
* **OS** : Windows 10 x64
* **Reproduce** : 
`nw.Window.open('file.html', {
    show: false
  }, function (newWindow) {
     newWindow.menu = null;
  });
`
* [crash_dump.dmp.zip](https://github.com/nwjs/nw.js/files/809991/crash_dump.dmp.zip)

**Comment by Christywl** [comment]
Reproduced with the code on Windows with nwjs-sdk-0.20.3 and 0.21.0.

**Comment by sunlin-link** [comment]
@rogerwang Can I take this issue?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
