### ISSUE TITLE
NW crash when call setAlwaysOnTop(true) on windows

### ISSUE THREAD

**Issue by Shawyeok** [nwjs/nw.js#5738]
I have a simple situation that just open a web page in full screen mode and `always on top` of desktop.

But the NW crash when I call `setAlwaysOnTop`, here is simple code to reproduce:
```
// main.js
nw.Window.open('http://www.bing.com/', {}, function(win) {
  win.enterFullscreen();
  win.setAlwaysOnTop(true);
});
```

NW version: nwjs-sdk-v0.14.7-win-ia32

Crash dump: [a62ee543-997e-4336-9667-22e881f1d6dd.zip](https://github.com/nwjs/nw.js/files/811318/a62ee543-997e-4336-9667-22e881f1d6dd.zip)

**Comment by Christywl** [comment]
Reproduced on Linux and Windows with nwjs-sdk-0.21.0.

**Comment by fujunwei** [comment]
I'd like to investigate it, assign it to me please, thanks.

**Comment by fujunwei** [comment]
@sunlin-link  will take this issue.

**Comment by Shawyeok** [comment]
Thanks a lot. I'm looking forward this BUG would be fixed.

**Comment by xzhan96** [comment]
@sunlin-link are you working on this? if not, I'd like to investigate it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
