### ISSUE TITLE
Documentation for Mac App Store up to date?

### ISSUE THREAD

**Issue by chino23** [nwjs/nw.js#5739]
I'm reading up here:

https://github.com/nwjs/nw.js/wiki/Mac-App-Store-(MAS)-Submission-Guideline

Now especially those pages:

https://github.com/nwjs/nw.js/wiki/MAS%3A-Packaging-your-app

Where it talks about removing the ffmpegsumo.so and the crash_inspector.

The Framework directory isn't there on the latest builds.

The MAS build doesn't have a crash handler, as it looks like, but there is a file called lybffmpeg.dylib

Does this one have to be deleted?

Then the other one:
https://github.com/nwjs/nw.js/wiki/MAS%3A-Configuring-children-apps

It talks about 3 helper apps.
Now the latest version only has one helper app, and it's sitting in a different directory. But I'm guessing the steps to adjust that is still the same?

https://github.com/nwjs/nw.js/wiki/MAS%3A-Signing-the-app talks about signing the helper app, is this still needed for the latest build too?

The newest documentation found in http://docs.nwjs.io/en/latest/For%20Users/Advanced/Support%20for%20Mac%20App%20Store/#support-for-mac-app-store
doesn't talk at all about those steps.

**Comment by rogerwang** [comment]
docs.nwjs.io is the official doc. We don't update wiki any more.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
