### ISSUE TITLE
Dock Icon Bounce Option for Mac Apps

### ISSUE THREAD

**Issue by Saravanan90** [nwjs/nw.js#5740]
Is there any option/ API to make the dock icon bounce for any new notifications in case of Mac Apps?

**Comment by Christywl** [comment]
@rogerwang , I don't find any docs about this, so mark as 'feature-request'. If wrong, please correct me.

**Comment by conceptualspace** [comment]
http://docs.nwjs.io/en/latest/References/Window/#winrequestattentionattension

**Comment by rogerwang** [comment]
close as we support it. thanks to @conceptualspace

**Comment by averzen** [comment]
it's not working on Mac:

win.requestAttention(true);
win.requestAttention(-1)
win.requestAttention(1)

all that calls do nothing.

mac os 10.12.6, NW.js v0.25.4 (0.26 laggy af, crashes and freezes every 5 mins)

**Comment by rogerwang** [comment]
Please file the (crash) issues of 0.26 as there is no 0.25 releases any
more.
