### ISSUE TITLE
OSX - 0.21.0 blank windows with chromium-args.

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5741]
OSX 10.11.6 El Capitan 
NW 0.21.0-sdk

Noticed that using "chromium-args": "--disable-gpu --force-cpu-draw" in package.json will cause windows (including debug tools) to be blank. This is only a problem if both args are used together.
Upto 0.20.3 worked OK but broken on 0.21.0 - possibly these args don't get used any more, I used to use them for transparency but they don't seem required anymore.

package.json - 
{
  "name": "Blank",
  "main": "index.html",
  "version": "1.0.0",
  "window": {
    "title": "nw demo"
  },
  "chromium-args": "--disable-gpu --force-cpu-draw"
}

index.html -
<pre><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>xxxxxxx</title>
</head>
  <body>
    <h1>Hello Hippos!</h1>
    We are using NWjs.io <script>document.write(process.version)</script>.
  </body>
</html>
</pre>

![ca](https://cloud.githubusercontent.com/assets/11089335/23509578/2a862710-ff4e-11e6-9434-8738ef338978.jpg)

**Comment by rogerwang** [comment]
Thanks for reporting. By " they don't seem required anymore", do you mean transparency is working someway without the arguments?

**Comment by rogerwang** [comment]
Also cc @jtg-gg who is maintaining this feature.

**Comment by Blatman** [comment]
Yes, my original app was running 0.12.3 and I decided to try 0.21.0 and found the issue. Just checked again and the args are now deleted from the manifest and I deleted the existing appdata folder - it was re-created OK and transparency works with 0.14.7 through to 0.21.0 without the args in the manifest. Not sure if they still exist in another cache somewhere ....

**Comment by Blatman** [comment]
Whoops - just doing a bit more playing around and I was having problems with click-through unless both args were available so it looks like transparency click-through requires both args therefore as at 0.21.0 apps that need both args won't work.
Cheers

**Comment by Christywl** [comment]
Reproduced with the `package.json` and `index.html` provided in the bug. App and devtools windows are blank with chromium-args. If removed these chromium-args, this issue doesn't occur.
```
Environment:
nwjs-sdk-0.21.0
Mac 10.11.6
```
This issue doesn't occur on Linux on Windows.

**Comment by jtg-gg** [comment]
oops, I've just read this, I've made fix for nw22

**Comment by rogerwang** [comment]
close as duplicate. Thanks.
