### ISSUE TITLE
Print cancel close app

### ISSUE THREAD

**Issue by AdrianoPatrizio** [nwjs/nw.js#5742]
When I cancel print from cancel button in default print dialog, my app close unexpectedly in Windows 7 and 10. I don't know if it crash or close for other problems.

Note: I call the default print dialog from main app into iframe with iframe.contentWindow.print(); method. The iframe have display:none.

**Comment by rogerwang** [comment]
Could you please upload a sample so we can reproduce it? Thanks.

**Comment by AdrianoPatrizio** [comment]
Thank you for attention. I have try this simple sample code and the app close too on cancel print button.
I have try different version of NWjs, the last 0.20.3 and an old 0.19.5.
The problem is random, not always the app close.

index.html:

`<html>
	<head>
		<script type="application/javascript">
			window.addEventListener("load",function(){
				var frm = document.createElement("iframe");
				frm.src = "frame.html";
				frm.style.display = "none";

				frm.onload = function(){
					frm.contentWindow.print();
				};

				document.body.appendChild(frm);
			});
		</script>
	</head>
	<body>
		<button id="printButton">Print</button>
	</body>
</html>`

frame.html

`<html>
	<body>
		<h2>This is a hidden frame page.</h2>
	</body>
</html>`

**Comment by Christywl** [comment]
Reproduced on Windows with nwjs-sdk-0.20.3. Tried 10 times, the reproducibility is 8/10. Btw, sometimes the app also crashed if clicking 'print' button.

**Comment by rogerwang** [comment]
@Christywl Thanks. Does it reproduce in the latest nightly build?

**Comment by Christywl** [comment]
@rogerwang , yes, it also reproduces in the latest nightly build: https://dl.nwjs.io/live-build/03-03-2017/nw21-02b12a2-6a70483-9396069-e47c2cc/v0.21.0/nwjs-sdk-v0.21.0-win-x64.zip

**Comment by rogerwang** [comment]
It's fixed in git and available at http://dl.nwjs.io/live-build/03-05-2017/nw20-c671da9-1bd0cf3-a2ef613-0e5235c/v0.20.4/
