### ISSUE TITLE
Google Maps Javascript API in NW.JS

### ISSUE THREAD

**Issue by robertocappa** [nwjs/nw.js#5744]
I'm trying to use Google Maps Javascript API inside NW.JS.  
It is mandatory for the API initialization to specify a key, created in the Google Development Portal. This key can be associated to: 1) a web domain, 2) a iOS or Android app ID.  None of these can be used in a NW.JS application (the domain doesn't work because in NW.JS the page url is like "file:///...").  

Any idea? 

Thanks.

**Comment by pdrd** [comment]
You should be able to create a api key for the 'Google Maps Javascript API v3' without the need for specifying a usage restriction. You simply have to keep in mind, that someone might use your api key on his own project, if it is not restricted to a domain or app.

If you want to distribute your app i'd try to setup a small website with a domain restricted api key and include this into your local app with an iframe or host the complete code on your website.

**Comment by robertocappa** [comment]
The first option is not suitabile  (we need usage restriction). 

The second option seems to be a good idea, but unfortunately there is a huge limit: I cannot perform actions from the map in iframe to the container page (for example, a click event on a map marker that changes container page's information).

**Comment by pdrd** [comment]
Well thats correct, but you _should_ be able to send cross origin messages by using the 'postMessage' function. Take a look at the corresponding mdn documentation [window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).
Since Chrome is supporting it at least from version 49, there should be no conflict with your nw.js setup. =)

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
