### ISSUE TITLE
Application Error (0xc0000005) Program randomly corrupts itself; have to constantly replace

### ISSUE THREAD

**Issue by tnvw** [nwjs/nw.js#5746]
Windows 7, running v0.20.3 now although this problem has been persistent for many versions now.

Example Video: http://www.fastswf.com/fgmqOEY

Repeated multiple times; at some point after opening up the application for the 1st time up to a random nth time, it will degrade and corrupt itself to that same error. Sometimes it's the error:
The application was unable to start correctly (0xc0000005) Click OK to close the application.
Other times it will go to WerFault.

I need a solution for this or at least signs to why it's doing this.

**Comment by rogerwang** [comment]
Could you please upload the crash dump: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by tnvw** [comment]
Tried looking under %LOCALAPPDATA%\Chromium\User Data\CrashPad
No new reports were generated.

**Comment by rogerwang** [comment]
It should be under the 'reports' folder.

**Comment by Christywl** [comment]
I saw the reporter's example video, and tried several times in his way on my Windows device with `nwjs-sdk-0.20.3`. I doesn't meet this issue, my nw.exe works fine. 

@tnvw , if you still meet this issue, please upload your logs, thanks.

**Comment by rogerwang** [comment]
close until more information is available.
