### ISSUE TITLE
Any plan about MacBook TouchBar support?

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#5756]
Hello, 
do you have any plan about TouchBar interface for macbook?

I just saw in electron they made it! 
https://electron.atom.io/blog/2017/03/08/touch-bar-support

Thank you

**Comment by rogerwang** [comment]
I'll put this on our TODO list. Thanks.

**Comment by fujunwei** [comment]
I will investigate this feature.

**Comment by fujunwei** [comment]
Touch bar support has been added to Chromium according to https://bugs.chromium.org/p/chromium/issues/detail?id=660126.
@Christywl Could you please help to verify it?

**Comment by Christywl** [comment]
@fujunwei , my Mac device doesn't support Touch Bar, it's not the newer MacBook Pro.

**Comment by strowbeary** [comment]
@fujunwei @rogerwang if you need the new macbook pro to test, tell me

**Comment by zdol** [comment]
You don't need a Macbook Pro to test this. While in Xcode, Window>Show Touch Bar.

**Comment by smotaal** [comment]
Any progress here? is there effort on this front at all?

**Comment by rogerwang** [comment]
close as duplicate of #5501
