### ISSUE TITLE
read-only file system and /root/.cache

### ISSUE THREAD

**Issue by diginfo** [nwjs/nw.js#5757]
I need to convert an existing deployment of nwjs running on Arch Linux to a read-only file system due to the fact that the users are switching the unit off at the wall socket and not powering it off resulting in corrupted file system.

Been doing this for the last 2 days and cannot crack the final hurdle and that is nwjs.

nwjs writes files to the user/.cache folder during startup, and without this folder being read/write it refuses to startup.

I have tried to create a symbolic link to a tempfs (which has 777 permission / mode)  and this won't work, the cache files are not created even though I can add / delete files from the command line.

I have also set the chromium-args in the package.json file and this appears to do absolutely nothing, I can set this path to anything even if the path does not exist and nwjs continues to use the user/.cache folder.

      "chromium-args": "--disk-cache-dir='/run/.cache' --data-path='/tmp'",

When I run nw --version it reports 50.0.2661.86 - so I guess this is nwjs 14.X.

Is there a way to disable caching or to specify the .cache folder that nwjs uses ?

I would rather not update to the latest as that will no doubt break a lot of other things that have been working 24x7 deployed in several countries for the last few years.

Update
==

I have just updated to the latest version (32 bit) nwjs 56.0.2924.87 and the behavior is the same.

I seem unable to override the .cache folder path ??

**Comment by rogerwang** [comment]
Please try `--user-data-dir`

**Comment by diginfo** [comment]
Thank you sooo much, that worked immediately :-)
