### ISSUE TITLE
[ES6] class autoloading like PHP?

### ISSUE THREAD

**Issue by Bizarrus** [nwjs/nw.js#5759]
This issue is not a directly question of `node-webkit`, rather be a question about `ES6`.
I've found yesterday on API-Docs of `Webkit` and `Moz` the implementation of `ES6` the `Class` definition: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes>

It's workin fine on `node-webkit` and i like it!

For example i had write sample classes for database endpoints:

**Database.js**

    class Database {
        construct() {

        }
    }

**SQLite3.js**

    class SQLite3 extends Database {
        construct() {

        }
    }

**MySQL**

    class MySQL extends Database {
        construct() {

        }
    }

My question is, how to create an `autoload` feature of classes like `PHP`. I don't want to include the `JavaScript` files manually, the best solution is, to load needed classes on the fly.

But it is possible?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by JamesPlayer** [comment]
@Bizarrus did you find any solutions? Mountains of `import` statements are a pain.

**Comment by Bizarrus** [comment]
im not had any solutions and i will not ask some external discusson platforms. The question was closed, and that is, why i had banned nw.js, im not longer using these.

**Comment by rogerwang** [comment]
The GitHub issue for this project is for bug reports and acts as developers task backlogs. It is not for support and questions, which should be in our mailing list. 

We have been redirecting questions without implications in issues to the mailing list. And will continue to do so. They have a better chance to be answered there. Thanks.
