### ISSUE TITLE
chromium-args not working?

### ISSUE THREAD

**Issue by YaroslavLyzlov** [nwjs/nw.js#576]
hello all :) I want to use node-webkit for screen sharing, using webrtc. In chromium everithing is working ok. In chromium there is a way to enable screen capturing with a flag enabling screen sharing for getUserMedia(). I wanted to do the same with node-webkit, and tried the following:

{
    "main" : "https://192.168.0.39:8080/#3SwVZXXu",
    "name" : "test app",
    "version" : "0.0.1",
    "chromium-args" : "--enable-usermedia-screen-capturing"
}

But us a result got the media from the webcamera and not the screen. What am I doing wrong here?

Thanks in advance)))

**Comment by shamun** [comment]
@rogerwang: FYI 

see the following screen shot please. that popup is not working with NodeWebkit 12 (alpha) latest version tested. But with Google Chrome Stable and Canary it works always.

![screen shot 2015-02-10 at 10 17 28](https://cloud.githubusercontent.com/assets/107349/6124579/f26cdaca-b10e-11e4-9985-968e45f0c56c.png)

**Comment by shamun** [comment]
Hello? What is the STATUS please?

**Comment by felicienfrancois** [comment]
@shamun the original issue (chromium-args not working) seems to be fixed.
You should check the `chrome://gpu` page in nw to check if all passed `chromium-args` are listed in the `Version info > Command Line Args`.

If so, and if screen capturing does not work, then you should create a separate explicit issue "Screen capturing does not work".

**Comment by shamun** [comment]
@felicienfrancois: Thank you. 

- Screen capture by selection does not work, please do the follow up here: [issue #3077](https://github.com/nwjs/nw.js/issues/3077)

**Comment by shamun** [comment]
Does anyone from here know? if this following issue was resolved by Roger Wang or by others yet? 

https://github.com/nwjs/nw.js/issues/3077
