### ISSUE TITLE
Unable to download from website

### ISSUE THREAD

**Issue by RollForReflex** [nwjs/nw.js#5760]
It seems that downloads for all of your OS's (both current and previous versions) are down on the website and have been for the last 24 hours or so. Is this known?

Example: https://dl.nwjs.io/v0.20.3/nwjs-v0.20.3-win-x64.zip

**Comment by rogerwang** [comment]
It works for me.

**Comment by RollForReflex** [comment]
Nevermind, looks like it's our company firewall that's blocking dl.nwjs. Closing
