### ISSUE TITLE
Upadte version and want reset use old version

### ISSUE THREAD

**Issue by zhailei31665431** [nwjs/nw.js#5761]
Your profile can not be used because it is from a newer version of NW.js.

Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js.

How Fix ?

**Comment by Christywl** [comment]
I also meet this issue on my Mac. I used nwjs-sdk 0.19.5, 0.20.0, 0.20.3 for some testing and met this issue now. The message in pop-up windows is same as this bug, and the log in Terminal is: 
`Cannot initialize the web database: 2`

Try to delete the following files, but it's not helpful.
```
/Users/Your Name/Library/Application Support/nwjs/Default/Web Data 
/Users/Your Name/Library/Application Support/nwjs/Default/Web Data-journal
```

**Comment by rohan-deshpande** [comment]
@Christywl's fix did not fix this issue for me. Wondering why this issue was closed? Would like to know what the cause of this is.

**Comment by rogerwang** [comment]
@rohan-deshpande Chromium changed the format of user data dir at some point. So if you run the same program once with newer version and then switch back to the old version you'll see the warning. It's not a bug of NW.

**Comment by rohan-deshpande** [comment]
Hmm I can produce this bug in a different way though. I am using the `nw` npm package `v0.20.3-sdk`. Manifest is as follows and is contained within the `app` directory which also contains an `index.html`

```
{
  "main": "index.html",
  "name": "my-app",
  "version": "0.0.1",
  "window": {
    "title": "my-app",
    "frame": true,
    "width": 1024,
    "height": 768,
    "position": "center"
  },
  "node-remote": "<all_urls>"
}
```

When I `nw app` I get the error as well as 

```
[53862:32263:0321/140138.618737:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 2
```

This is a fresh directory with a fresh install of `nw`.

**Comment by rogerwang** [comment]
You'll need to check user data dir: http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir

**Comment by rohan-deshpande** [comment]
Ah! right am I cool to just delete these directories? Once the app boots again it will populate them again right?

**Comment by rogerwang** [comment]
yes

**Comment by quantumproducer** [comment]
Hello, I still have this issue. I tried deleting those 2 folders.
https://github.com/nwjs/nw.js/issues/6188
