### ISSUE TITLE
nwjs 0.21.0 for win7 ia32 is not using the package.json *name* parm as part of folder *path* any longer

### ISSUE THREAD

**Issue by garfield69** [nwjs/nw.js#5762]
Hello NWJS team.     
I was previously using nwjs 0.20.3 for windows 7 ia32, and have just upgraded the NWJS components to 0.21.0, by simply replacing all the NWJS components in my app folder with everything from archive `nwjs-sdk-v0.21.0-win-ia32.zip`.        
This is something I've regularly done to upgrade NWJS for each SDK release previously published since 0.13.0 :-)       

Today I find that the path the 0.21.0 is using is now different from what was used by 0.20.3      

path for **0.20.3** `C:\Users\<username>\AppData\Local\Application Data\DuckieTV-Standalone-Development\User Data\Default`      
path for **0.21.0** `C:\Users\<username>\AppData\Local\Application Data\Chromium\User Data\Default`      

So 0.20.3 used the package.json `name` parameter to build its path, `  "name": "DuckieTV-Standalone-Development",` but 0.21.0 does not seems to be using this any longer, using `Chromium` instead.     

Was this intended?     
If so, what do I need to change in the package.json to restore the path back to the way it was in 0.20.3 ?
Thanks.

[Edit] corrections made to path details.

**Comment by rogerwang** [comment]
Thanks for reporting. This is a bug , will fix it soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in 0.21.1 soon.

**Comment by garfield69** [comment]
Terrific.  I can confirm that the path for the NWJS 0.21.1 windows ia32 SDK  build is now back to normal.     
Thank you for the prompt fix.     :smile:
