### ISSUE TITLE
it stoped when nw-gyp rebuild --target=0.18.8

### ISSUE THREAD

**Issue by xiaozhu20170310** [nwjs/nw.js#5764]
the error is this:
C:\Users\admin\Desktop\nwc1\node_modules\ffi>nw-gyp rebuild --target=0.18.8
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.2.0 | win32 | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.18.8/nw-headers-v0.18.8.tar.gz
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.18.8/nw-headers-v0.18.8.tar.gz

so you see , it stoped a long time and didn't work and I don't know why . Any suggestions?
Thank you very much!

I use win8.1 x64,vs2013,python2.7 and nodejs v6.2.0 and nwjs v0.18.8 . 
I install the latest npm , node-gyp and nw-gyp .
I install the windows sdk x64.
According to the article , I can run node C++ addOn .
But when I try to run dll by nw.js , it thows the following error:
     Dynamic Linking Error: Win32 error 193

So I installed nodejs and python 64bit  again. The dll is 64bit . nwjs and node-gyp ,nw-gyp(version0.18.8) are installed by npm . And it stoped when nw-gyp rebuild --target=0.18.8 

and after a long time , following is the error:

gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.2.0 | win32 | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.18.8/nw-headers-v0.18.8.tar.gz
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.18.8/nw-headers-v0.18.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:953:11)
gyp ERR! stack     at TCP.onread (net.js:563:26)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm
e_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.18.8" "--arch=x64"
gyp ERR! cwd C:\Users\admin\Desktop\nwc1\node_modules\ref
gyp ERR! node -v v6.2.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok

**Comment by rogerwang** [comment]
It should be a network issue.
