### ISSUE TITLE
Possible to have different package.json files for production and development?

### ISSUE THREAD

**Issue by rohan-deshpande** [nwjs/nw.js#5765]
I'm building a boilerplate CLI type package for bootstrapping nwjs projects. The idea is that you have nwjs as a main app shell and you can use any JavaScript framework you want to build your actual app, then just plug it into nwjs and it will work. My goal is to get it all working with ES6 goodness. 

I am using the `nwjs/npm-installer` and am running `0.20.3-sdk`. The first JavaScript app I am seeding with uses `create-react-app` and therefore `webpack-dev-server`. For my `package.json` I have a set up that works, but obviously, I'd only want this setup in development. When I actually package my app up, the package configuration will need to be different. 

Rather than have to manually configure my package.json for each use case, is there no way I can somehow tell `nw` to use a particular package.json? Or perhaps build a package.json programmatically before the app gets run? 

Any ideas?

**Comment by SchizoDuckie** [comment]
I do juggling like this in my build step. This is not the task of nwjs imo.

**Comment by pdrd** [comment]
I think SchizoDuckie is right. This would be a task that should be handled by your favourite build system.
But if i'm correctly understanding the usage of the 'create-react-app'-module, you should consider a completely other approach. You can f.e. create another package.json with `npm init` in your root folder that contains all the development relevant stuff (--save-dev option) and put your nwjs-package.json inside your 'src' folder or whatever you want to call it. That way you can write some npm scripts, where you can start your development server or start nw.js on the 'src' folder.

**Comment by rohan-deshpande** [comment]
Yep! Agreed, my CLI is heading this way now but it will be configurable when you `npm run dev` with some flags, should be done soon! Will close this issue.

**Comment by baconface** [comment]
Why not just specify dev modules as [devDependencies](https://docs.npmjs.com/files/package.json#devdependencies)?

**Comment by pdrd** [comment]
@rohan-deshpande perfect!
@baconface definitely the simplest solution! But it still depends on your build env and your personal preference.
In my understanding the package.json of nw.js is part of the source code, which is getting deployed in the final build. But normally you also need a lot of tools in your build process that are - in my case - all listed in my package.json, also with referenced scripts, a lot of config-dotfiles, etc, etc only for building.
At this point i personally dislike to ship a manifest, that references files which are not included in my build, so the simplest approach to get around this and get a complete clean build, is to separate it.
As often happens... it depends! ;)
