### ISSUE TITLE
HTTPS is the only thing considered secure?

### ISSUE THREAD

**Issue by jssuttles** [nwjs/nw.js#5766]
https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

<img width="351" alt="screen shot 2017-03-10 at 3 18 45 pm" src="https://cloud.githubusercontent.com/assets/8527741/23811847/b7d38b64-05a5-11e7-8e84-05899a36cca1.png">

I'm using NW.js as a native application. It is mostly built from files. So, login is a file:// not a https://. I haven't been keeping up with nw.js releases because I was satisfied with 0.17.2. Now I need 0.21.1 for the latest Chromium version. However, with this release I've run into the above issue. Any suggestions on how to deal with it?

**Comment by rogerwang** [comment]
will fix this.

**Comment by rogerwang** [comment]
I can't reproduce. Please provide a case.

**Comment by jssuttles** [comment]
Hello, created this small repo. I didn't test it with regular nw@0.21.1. I used SDK. I'm not sure if that matters.

https://github.com/jssuttles/nw-5766

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by jssuttles** [comment]
Thanks! Could you tell me the expected behavior now?

**Comment by jssuttles** [comment]
Alright. Works!
<img width="338" alt="screen shot 2017-03-17 at 12 15 13 pm" src="https://cloud.githubusercontent.com/assets/8527741/24052303/66ed96de-0b0b-11e7-901b-be703caef409.png">

**Comment by cecilpeng** [comment]
Is it only works on file protocol, not http?

**Comment by rogerwang** [comment]
@cecilpeng This is only removed in pages running in NW security model. See which pages are in NW model here: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/
