### ISSUE TITLE
0.21.1 New Window Icon

### ISSUE THREAD

**Issue by jssuttles** [nwjs/nw.js#5767]
http://docs.nwjs.io/en/latest/References/Manifest%20Format/#window-subfields

Previously, when opening windows from other windows, it was possible to set the new window's icon. That seems to crash the application at this point. (Tried on Windows)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by jssuttles** [comment]
👍

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/03-13-2017/nw21-e4053be-482e210-96303a2-f8653cb/v0.21.2/
