### ISSUE TITLE
node-remote does not working

### ISSUE THREAD

**Issue by kimtn-bitmark** [nwjs/nw.js#5776]
I just upgrade nwjs to 0.21.1 and got this error when i trying to open google from iframe.

```
Refused to display 'https://www.google.com/?gfe_rd=cr&ei=iBDJWOe8IpakvwSnh7qACg&gws_rd=ssl' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

I was research and add `node-remote` based on this issue https://github.com/nwjs/nw.js/issues/4787

But it does not succeed.
(i'm using OSx 10.12.3)

**Comment by rogerwang** [comment]
You need to use 'nwfaketop' attribute on the iframe element, not
node-remote.
