### ISSUE TITLE
Need to display jpeg image, help...

### ISSUE THREAD

**Issue by g00dnatur3** [nwjs/nw.js#5778]
Hi,

 I have a very simple request:

What is the most efficient way to display a jpeg image.

Assume, that I have a jpeg image loaded into a node js Buffer.

Should i use a canvas? 
Should i convert to base64?

What do you recommend?

I plan to be receiving jpegs from a socket every 80ms or so...

So it will be like a 12fps video.

Thanks for any help.

Cheers!

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
