### ISSUE TITLE
Manifest-format-->  "always-on-top"; This page write error,Should be "always-on-top"

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#5779]
Manifest-format-->  "always-on-top"; This page write error,Should be "always-on-top"

https://github.com/nwjs/nw.js/wiki/Manifest-format

Read the following before submitting your issue, thank you.

* Please use English so all users can read, or the issue will be closed directly.
* Use our mailing list to ask questions which don't imply bug or feature request: https://groups.google.com/forum/#!forum/nwjs-general
* State which version are you using
* State which OS version are you running with
* Provide a reproducible case if possible
* Attach the crash dump file if it's a crash: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file

Issues meet the checklist above will be processed before those don't.

**Comment by rogerwang** [comment]
@Christywl what's the issue?

**Comment by Christywl** [comment]
I think it should be 'always_on_top', not 'always-on-top' according to the docs.

**Comment by rogerwang** [comment]
Our doc is on http://docs.nwjs.io and there is a warning in the wiki page saying that it doesn't apply to new version. So closing this issue.
