### ISSUE TITLE
Cmd+Q causes crash

### ISSUE THREAD

**Issue by PriteshGajjar008** [nwjs/nw.js#5780]
Cmd+Q causes application crash. Attaching .dmp files.
Version: 0.14.7
OS (Mac OS X)
[Issue_Dumps.zip](https://github.com/nwjs/nw.js/files/846861/Issue_Dumps.zip)

**Comment by Christywl** [comment]
Seem Cmd+Q is the Shortcut Key in Mac OS X for all applications. The Cmd+Q key quits the entire app. So I think it's not nwjs crash issue.

**Comment by rogerwang** [comment]
@Christywl He probably means NW crashes in the middle of quitting. Worth a check to see if there is any crash dump file with the latest version.

**Comment by Christywl** [comment]
I checked on nwjs-sdk-v0.21.3, didn't reproduce this issue. I didn't find any crash file in `~/Library/Application Support\<app-name>\Crashpad`. @PriteshGajjar008 , is it still reproduced in your environment? If yes, could you please share your test case for me to reproduce?

**Comment by PriteshGajjar008** [comment]
It's not reproducible at the moment. It was intermittent. Closing this for now.
