### ISSUE TITLE
X-Frame-Options: deny blocks content in iframes

### ISSUE THREAD

**Issue by bjoernneumann** [nwjs/nw.js#5781]
If a site that has the X-Frame-Options: deny header set are not loadable any more to iframes.
For example https://web.whatsapp.com/.

Tested with nwjs 0.21.2.

Worked before with nwjs 0.19.5.

Setting nwfaketop as iframe attribute has no effect, as well as `"node-remote": "*://*/*"` in the manifest.
But commenting out line 110 in content/browser/frame_host/ancestor_throttle.cc
```
  //if (handle->frame_tree_node()->frame_owner_properties().nwfaketop)
    return NavigationThrottle::PROCEED;
```
does do the job. But fixing the if statement would be nicer of course.

**Comment by rogerwang** [comment]
Thanks, will fix it soon.

**Comment by rogerwang** [comment]
Could you please give the steps to reproduce it? Here the URL loads fine.

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by bjoernneumann** [comment]
Sorry for the late reply.
So you are right, works with nwfaketop, like:
index.html
```
<html>
 <head></head>
 <body>
  <iframe src="https://web.whatsapp.com/" nwfaketop></iframe>
 </body>
</html>
```
package.json
```
{
    "name":"test",
    "main":"index.html",
    "node-remote": "*://*/*"
}
```

But it doesn't without nwfaketop, even if node-remote should match the url. Which definitely worked before.

**Comment by rogerwang** [comment]
`node-remote` is not for this.

**Comment by bjoernneumann** [comment]
But wasn't it before the X-Frame-Options check was moved from webkit?

In chromium for nwjs 0.19.5 (5e25421ca844ce490196a275c8bf9e6165cd54b8) it was like:
third_party/WebKit/Source/core/loader/FrameLoader.cpp
```
@@ -1677,6 +1695,9 @@ bool FrameLoader::shouldInterruptLoadForXFrameOptions(
    if (m_frame == topFrame)
      return false;
  
 +  if (topFrame->isNodeJS())
 +    return false;
 +
    XFrameOptionsDisposition disposition = parseXFrameOptionsHeader(content);
  
    switch (disposition) {
```
And maybe I misunderstand that, but doesn't the documentation also say that it should work with node-remote?
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/
> In NW.js, frames matching ALL of the following criterias will be a node frame:
>
> nodejs set to true in manifest file
> **URL of windows and frames matching node-remote patterns in manifest file or chrome-extension:// protocol.**
> Frames or parent frames NOT having nwdisable attribute.
> Frames or parent frames NOT in <webview> tag

**Comment by rogerwang** [comment]
The document doesn't say X-Frame-Options should be ignored in Node Frame.

**Comment by bjoernneumann** [comment]
Ok.
I thought "Bypass **all** security restrictions, such as sandboxing, same origin policy etc" would also include that.

Sorry for the noise.
