### ISSUE TITLE
NW crash on 0.12

### ISSUE THREAD

**Issue by uppuluriaditya** [nwjs/nw.js#5782]
Hi,
My issue is similar to #4615 . I want to know the root cause of the issue. I have actually commented on the same post asking for the root cause but didn't got reply as it is an old post. Can anyone please explain me what has been fixed in 0.13 pertaining to the crash. It is extremely important for me to know the root cause. 
Let me know if i can provide you with anymore information

Thank you

Regards,
Aditya

**Comment by rogerwang** [comment]
I'm afraid 0.12 is not supported any more, nor do we look into its code to find the root cause because many code has been changed.
