### ISSUE TITLE
Disable "Login Not Secure" Warning

### ISSUE THREAD

**Issue by benjismith** [nwjs/nw.js#5783]
The login screen for my application recently started showing Chrome's "Login Not Secure" warning:

<img width="1392" alt="screen shot 2017-03-17 at 4 37 52 pm" src="https://cloud.githubusercontent.com/assets/458075/24066725/46877e2e-0b32-11e7-960c-c9432a76f67e.png">

I understand why this warning exists: because the password-manager sees an `<input type="password">` field, on a page that doesn't use the HTTPS protocol.

But in this case, the warning is wrong... My application loads all of its HTML from local resources in the "app.nw" bundle, or builds the UX in javascript, and it uses the [nodejs HTTPS api](https://nodejs.org/api/https.html) for all communication with our secure back-end servers. I've also double-checked the SSL certificate on the back-end looking for certificate problems. The login is *definitely* secure.

I'd like to request a feature that would selectively disable this warning message in cases like mine (where the entire UX is loaded from local resources, or where the DOM is built entirely via javascript APIs).

**Comment by rogerwang** [comment]
Thanks for reporting. What's the version you are using and is it duplicate of #5766?

**Comment by benjismith** [comment]
Oops, yes this is a duplicate! Thanks for the quick reply!

(I'm using 0.21.1, fwiw)
