### ISSUE TITLE
V13.0 new version can not load browser plug-in [web serial connection plug]

### ISSUE THREAD

**Issue by wywsq** [nwjs/nw.js#5784]
I run the program on the v.12.3 version, can be loaded with the browser plug-in [web] serial connection plug-in, but no print preview in this version, can set the print format, but I updated to v13.0 version, I found that when you can print preview, but is unable to load the serial plug-in, very depressed, excuse me which section and support print preview and support loading browser plug-ins, thank you very much... Waiting in

**Comment by rogerwang** [comment]
Could you provide more information about the plugin? And is it NPAPI based?

**Comment by wywsq** [comment]
Thank you very much for your answer, this plug-in is connected to the local serial port, is the third party plug-ins, the direct use of the v12.3 version is no problem, I do not know whether or not based on NPAPI, how should I do it?

**Comment by wywsq** [comment]
This is the use of the page:
<OBJECT id="tcom_OB" classid="clsid:987F8440-C95B-46EC-8CE5-C653E47593D5" width=0 height=0>
<embed id="tcom_EM" type="application/x-comm-nptcomm" width=0 height=0 pluginspage="/files/TComm.exe"></embed>
</OBJECT>

 v12.3 version can be opened to open the serial communication

**Comment by rogerwang** [comment]
If it is an NPAPI plugin: Chromium has dropped support for it: https://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html ; You can use Node module or chrome.serial API to access serial port if that's the case.

**Comment by wywsq** [comment]
Like this?

var SerialPort = require("browser-serialport").SerialPort
var serialPort = new SerialPort("/dev/tty-usbserial1", {
  baudrate: 57600
}, false); // this is the openImmediately flag [default is true]

serialPort.open(function (error) {
  if ( error ) {
    console.log('failed to open: '+error);
  } else {
    console.log('open');
    serialPort.on('data', function(data) {
      console.log('data received: ' + data);
    });
    serialPort.write("ls\n", function(err, results) {
      console.log('err ' + err);
      console.log('results ' + results);
    });
  }
});

**Comment by rogerwang** [comment]
Yes. And close until there is more information about the plugin.
