### ISSUE TITLE
how to open different window

### ISSUE THREAD

**Issue by jin-pan** [nwjs/nw.js#5785]
I want to achieve the follow purpose:
  My desktop has two shortcup A and B which poit to nw.js
  And when click A , it will start nw.js and load A.html, When click B , it will start nw.js and load B.html.
I don't  know how should i do to achieve this .

Thank you very much.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by jin-pan** [comment]
I can't view the google site due to i am in China.
Can you give me some help here? @rogerwang

**Comment by kailniris** [comment]
Create two different package.json-s in two different folders.
The 1st main should be A.html, the 2nd main should be B.html. Create 2 shortcuts of nw.js, one should open the folder with the first package.json the other shortcut should open the other one.

**Comment by jin-pan** [comment]
@kailniris 
thank you ,Please help to give more detail about how to start the nw.js by loading different package.json.

**Comment by kailniris** [comment]
Create multiple shortcuts
C:\path_to\nwjs_directory\nw.exe C:\path_to\directory_of_package_with_A.html\
C:\path_to\nwjs_directory\nw.exe C:\path_to\directory_of_package_with_B.html\

The directories should contains package.json-s like these:

package.json for A.html
{
  name: 'a',
  main: 'A.html'
}

package.json for B.html
{
  name: 'B',
  main: 'B.html'
}

http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/
