### ISSUE TITLE
MediaElementAudioSource outputs zeroes due to CORS access in NW.js (Chrome OK)

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#5787]
NW.js 0.21.3 (normal/sdk)
OS: Windows 10 32/64 bit

if I run this file (check attach) in Chrome and disable same origin policy (chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security), everything works fine.

But if you run it in NW.js, i got a warnning: MediaElementAudioSource outputs zeroes due to CORS access. 

I tried to use audio.crossOrigin = "anonymous", and nwjs displays an error: Failed to load because no supported source was found audio.

It possible to fix? 

[test_file.zip](https://github.com/nwjs/nw.js/files/852618/test_file.zip)

**Comment by rogerwang** [comment]
Should be fixed. Thanks for reporting.

**Comment by rogerwang** [comment]
I added a manifest and ran your sample but didn't hit any error:
````
{
  "name": "test",
  "main": "test.html"
}
````

**Comment by hooker99** [comment]
OK i know what happened... If i added a manifest everything is ok, but if i drag and drop file (my sample) to nwjs i got a warning:

![test](https://cloud.githubusercontent.com/assets/18085392/24081484/e66bcf16-0cb4-11e7-854f-9f2543640bc8.png).

Thanks Roger.

**Comment by rogerwang** [comment]
If you run it without manifest, then it's just a normal webpage that web security should be applied. See more on security model in NW here: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/
