### ISSUE TITLE
Iframe - fullscreen api

### ISSUE THREAD

**Issue by GroofyIT** [nwjs/nw.js#5788]
Using version 0.14.7 and 0.21.3 the HTML 5 Fullscreen API is unavailable in iframe.
Methods and props are in place, however document.fullscreenEnabled returns false.
Am I missing anything?

**Comment by rogerwang** [comment]
Is your code working in Chromium browser? If yes, please upload a sample and we'll fix it.

**Comment by GroofyIT** [comment]
It does work in chromium browser.
The situation is as following:

- The nwjs app is a dead simple app that acts as a closed down browser
- Due to having to (still) accept win xp, we are bound to 0.14 (but tested in 0.21.3 as well)
- The app itself has the ability to use the fullscreen api (with webkit preface), however external sites loaded into an iframe don't

I'm guessing I need to inject ?

[SRC.zip](https://github.com/nwjs/nw.js/files/856798/SRC.zip)

**Comment by GroofyIT** [comment]
@rogerwang Did you had the chance to take a look ?

**Comment by rogerwang** [comment]
@GroofyIT I tried to run your sample, but it hangs at "loading..." and the console shows the "express" module is missing. Could you please upload a sample which is ready to run?

**Comment by rogerwang** [comment]
cc @Christywl please triage once the new sample is uploaded.

**Comment by Christywl** [comment]
close until there is more information
