### ISSUE TITLE
Chrome Extension Functionality

### ISSUE THREAD

**Issue by jkramp** [nwjs/nw.js#5792]
We have a website that we use for a phone application currently in chrome. It uses a chrome extension to communicate with a soft phone that is running locally. I am trying to replicate this in NW with the latest SDK version on a Windows 10 box.

Unfortunately it is not working.

The extension appears to be running correctly. The content.js portion is running in a webview and is communicating with background.js. The background.js uses the chrome chrome.runtime.connectNative to connect to a local app, eg

chrome.runtime.connectNative('com.myApp.Myclient')

Then chrome.tabs.sendMessage and chrome.extension.onRequest.addListener for communication. 

Nothing is crashing or erroring out but the app is not working. I am trying to figure out if it is how the extension is communicating or with the chrome.runtime.connectNative call (this does appear to work in the console though)

Assuming that  chrome.runtime.connectNative should work, my thought is that maybe it is how it is figuring out where to send the message. In the extension, in background.js it is using 

chrome.tabs.query({}, function(tabs) {
					for (var i=0; i<tabs.length; ++i)
							chrome.tabs.sendMessage(tabs[i].id, msg);				
				});

This returns an empty array so this might be the guilty party (or it cannot be run in the console). 

Any ideas on whether this should work and if chrome.tabs.query would need to be swapped out to get the webview instances?

**Comment by rogerwang** [comment]
NW.js app is a Chrome App,which is different with Chrome extension. You can see the difference of APIs:
https://developer.chrome.com/extensions/api_index vs https://developer.chrome.com/apps/api_index

However, we do support some of the extension APIs, see http://docs.nwjs.io/en/latest/References/Chrome%20Extension%20APIs/

If you find any issue in them or want to add more, we'll see to support them.

**Comment by rogerwang** [comment]
btw, in NW there are no browser tabs as in Chrome.

**Comment by rogerwang** [comment]
More discussion on this is in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
and close since it's more like a question.

If you find any issue in chrome extension API support or want to add more, please submit specific issues. Thanks.
