### ISSUE TITLE
always-on-top won't work on mac

### ISSUE THREAD

**Issue by faytom** [nwjs/nw.js#5797]
I set the window attribute "always-on-top" to true, however it won't stay on top of screen. Can anyone  help me with it? Thanks in advance.

**Comment by RohitSharma27** [comment]
Please state your nw version. Assuming that you're using nw > 13, it's always_on_top.

**Comment by faytom** [comment]
@RohitSharma27 Thx for the help. The nw version I am using is 19, so it should be "always_on_top". Case closed
