### ISSUE TITLE
The resource in packed nw app could not be open because of permission issue

### ISSUE THREAD

**Issue by faytom** [nwjs/nw.js#5798]
I was trying to run a applescript to open a .mov file triggering by the command in the packed nwjs app. However, it says permission is required to open the .mov file. The .mov is located within the packed nwjs app. And before packing up the app, I changed the permission of .mov file to read and write.
The nwjs version I am using is 0.19.1, and it was running on Mac.

**Comment by Christywl** [comment]
@faytom , could you please provide your packed app to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
