### ISSUE TITLE
link issue for nwjs

### ISSUE THREAD

**Issue by vicwang163** [nwjs/nw.js#5799]
when I try to run nwjs in command,it works
`/Volumes/ext/template/nwjs.app/Contents/MacOS/nwjs`
then I try to add link using the following command
`sudo ln -s /Volumes/ext/template/nwjs.app/Contents/MacOS/nwjs /usr/local/bin/myapp`
and check the link exists , now I type the command `myapp`, the command throws error:
`dlopen /usr/local/bin/../Versions/54.0.2840.99/nwjs Framework.framework/nwjs Framework: dlopen(/usr/local/bin/../Versions/54.0.2840.99/nwjs Framework.framework/nwjs Framework, 257): image not found
Abort trap: 6`

OS system:10.11.5 (15F34)
nwjs version: 0.18.x

**Comment by vicwang163** [comment]
I found another solution,it works well
`sudo ln -s /Volumes/ext/template/start.sh /usr/local/bin/myapp`

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.21.3. But it works fine on Linux wiht nwjs-sdk-0.21.3.

**Comment by rogerwang** [comment]
@Christywl this should be reproducible in Chrome browser as well.

**Comment by Christywl** [comment]
@rogerwang , yes, it's also reproduced in Chrome on Mac.

**Comment by rogerwang** [comment]
close as it's an upstream issue.
