### ISSUE TITLE
Doesn't work flag enable-native-notifications since 20 version.

### ISSUE THREAD

**Issue by blaremc** [nwjs/nw.js#5800]
If I set the enable-native-notifications flag in chrome://flags , it works.

**Comment by rogerwang** [comment]
Could you please try `--enable-features=NativeNotifications` ?

**Comment by Christywl** [comment]
I tried `--enable-features=NativeNotifications`, it works on Mac with nwjs-sdk-v0.21.3.

**Comment by blaremc** [comment]
Yes it works! Thank you!
