### ISSUE TITLE
Is there any api like crashReporter in electron for nw to send crash report?

### ISSUE THREAD

**Issue by xingyuzhe** [nwjs/nw.js#5803]
Is there any api like crashReporter in electron for nwjs to send crash report?  I can't find it anywhere.

**Comment by kailniris** [comment]
Ask question in the google group:
https://groups.google.com/forum/#!forum/nwjs-general

As far as i know there is no built in crash reporter in nw.js.

**Comment by rogerwang** [comment]
We'll add this API. Before that you can upload the crash dump file with your own code: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by xingyuzhe** [comment]
@rogerwang I‘ve read the document in `http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/`， all i want is  get the crash report with environment info in time,  i don't really care about the dump files because it's hard to read and useless for me sometimes，all i want is:  if the crash happend, report to the remote server immediately. how can i get this?

**Comment by RohitSharma27** [comment]
You can have your application do that. Whenever you launch your application go and check the crash pad directory and if you find a dump file there then just report it to the server and delete it, if you're not planing to use them ever.

**Comment by rogerwang** [comment]
close as duplicate of #5533
