### ISSUE TITLE
BUG - when onscreen keyboard is used then on click on nwjs input field does not trigger keyboard

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5804]
Step 1: 

install  on screen keyboard: http://chessware.ch/virtual-keyboard/

Step 2: install new NWJS
```
package.json:
{
  "name": "Windows 8.1 - Tweak", 
  "main": "credits.html",
  "window" : {
    "title": "test",
    "toolbar" : false, 
    "frame" : false,
    "resizable": false, 
    "kiosk": false,
    "always-on-top": false,
    "width":400,
    "height":800,
    "show": true
  },
  "webkit": {
    "plugin": false,
	"java": false,
	"page-cache": true
  },
  "nodejs":true
}

credits.html:

page: <input type=text />
```
Step 3:

now while running onscreen keyboard, if you touch the input field keyboard does not show, but on chromium it works.

**Comment by Christywl** [comment]
I can reproduce this issue on Windows with nwjs-sdk-v0.21.3.

**Comment by rogerwang** [comment]
@Christywl does it work with Chromium in your system? Can you trigger the virtual keyboard by mouse click or finger touch?

**Comment by Christywl** [comment]
Yes, it works on Chrome on my Windows. The virtual keyboard will be triggered when I click the input area mouse click.

**Comment by rogerwang** [comment]
adding `--force-renderer-accessibility` seems to fix this issue, according to the keyboard software vendor: http://chessware.ch/forum/viewtopic.php?t=283

Looks like special handling is done in the software for Chrome. Will contact them to learn the detail.

**Comment by shamun** [comment]
Thank you.

FYI http://chessware.ch/forum/viewtopic.php?f=4&t=949 - We have released a new version of on-screen keyboard regarding this issue.

**Comment by shamun** [comment]
**FIXED**

![](http://i.imgur.com/45JTG9Q.jpg)

**Comment by prashanthsun9** [comment]
Sorry for opening this again, can you let us know how did you fix this issue?
