### ISSUE TITLE
Questions about webview and Node native modules

### ISSUE THREAD

**Issue by AdrianoPatrizio** [nwjs/nw.js#5805]
I have two questions about Webview and Node native modules.

1. work inject_js_start / inject_js_end into webview if Node is disabled in this and the script isn't a Node.js script?
2. From custom Node native module, i can access to render processes?

Thanks.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
