### ISSUE TITLE
UPX not working for nw.dll

### ISSUE THREAD

**Issue by gengshenghong** [nwjs/nw.js#5806]
Hi,

Is there anybody successfully used UPX compression on nw.dll? I've tried UPX (official command line tool), Free UPX (GUI of UPX) and web2executable, all are failed. I've also tested many versions of NWJS (>0.12), and all failed.

I've even tried to use UPX compression option of 1 and it will fail...all other dlls are ok,it failed only when run UPX on nw.dll.

Anybody tried to minimize nw binaries successfully and what is the exact version of tools used?

Below is the debug.log when using UPX on nw.dll:

[0327/121626:FATAL:sandbox_win.cc(646)] Check failed: result == 0. 
Backtrace:
	std::vector<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> >::crend [0x02D2FD87+39271]
	std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >::_Buy [0x02CEE331+123169]
	v8::HeapObjectStatistics::object_sub_type [0x0343416D+187373]
	v8::HeapObjectStatistics::object_sub_type [0x03436797+197143]
	v8::ExternalOneByteStringResourceImpl::~ExternalOneByteStringResourceImpl [0x02CB8D1E+418766]
	v8::ExternalOneByteStringResourceImpl::~ExternalOneByteStringResourceImpl [0x02CB74CE+412542]
	ChromeMain [0x0296197B+107]
	GetUploadedReportsImpl [0x013C62E2+2770]
	GetUploadedReportsImpl [0x013C5B8D+893]
	IsSandboxedProcess [0x01419310+195920]
	BaseThreadInitThunk [0x761C338A+18]
	RtlInitializeExceptionChain [0x76F19F72+99]
	RtlInitializeExceptionChain [0x76F19F45+54]

[0327/121626:ERROR:process_info.cc(608)] range at 0xfffde000, size 0x230 fully unreadable
[0327/121626:ERROR:process_info.cc(608)] range at 0xfffdd000, size 0xf84 fully unreadable
[0327/121626:ERROR:process_info.cc(608)] range at 0xfffda000, size 0xf84 fully unreadable

Thanks very much,
Shenghong

**Comment by VasiliyIsaichkin** [comment]
I test it, no errors:
> Windows 10 x64 (1607 / build 14393.953)
> UPX 3.93w
> NW.JS v.0.21.3 windows x64 and ia32

Commands for compression:
```
upx -5 nw.dll
upx -5 node.dll
```
Results:
_______
**nwjs-sdk-v0.21.3-win-x64**
```
94316544 ->  37478912   39.74%    win64/pe     nw.dll
5841920 ->   2295808   39.30%    win64/pe     node.dll
```
Result: **Works fine**
_______
**nwjs-v0.21.3-win-x64**
```
92585472 ->  37166080   40.14%    win64/pe     nw.dll
5840896 ->   2296320   39.31%    win64/pe     node.dll
```
Result: **Works fine**
_______
**nwjs-v0.21.3-win-ia32**
```
66619392 ->  26011648   39.05%    win32/pe     nw.dll
4865024 ->   1893376   38.92%    win32/pe     node.dll
```
Result: **Works fine**

**Comment by VasiliyIsaichkin** [comment]
ps: if you compress other dll's from nwjs, you will cause an error.

**Comment by Christywl** [comment]
It also works fine for me on Windows with nwjs-sdk-v0.21.3(`upx nwjs-sdk-v0.21.3-win-x64\nw.dll).` 
@gengshenghong , could you please provide your cmd and steps?

**Comment by gengshenghong** [comment]
@VasiliyIsaichkin @Christywl Thank you for providing the information. I've again tested based on your information. But it seems not working still.

Tools (all downloaded from github official release):
nwjs-sdk-v0.21.3-win-ia32.zip
upx393w.zip

OS info:
Windows 7 SP1 64bit

Command line:
upx -5 nw.dll
upx -5 node.dll
Results: crash with debug.log as I mentioned.

I've tested on Windows 10 64bit based on VasiliyIsaichkin's information, and it seems working well!! Any idea? Is it possible to make it work for all OSes. :(

Thanks,
Shenghong

**Comment by gengshenghong** [comment]
Also tested nwjs-sdk-v0.21.3-win-x64.zip on windows 7 64bit now, it failed with debug.log too.

**Comment by sourceskyboxer** [comment]
Wait wait why do you not NoVirusThanks EasyUPX http://www.novirusthanks.org/products/upx-easy-gui/ if you drop dll into easy upx faster .. So sad because you can not use UPX

I recommand you can compress with BoxedApp Packer http://www.boxedapp.com/boxedapppacker/ because BoxedApp Packer can nw.dll and node.dll into exe + ca 75 % high-compressing into standalone exe

**Comment by gengshenghong** [comment]
@sourceskyboxer Thank you for the information, I've tried "Enigma Virtual Box" and it get similar size compared with UPX, and it do works with packed app. I may use this safe way in my project.

Thanks,
Shenghong

**Comment by sourceskyboxer** [comment]
Welcome @Shenghong! Now they have no problem. But how are binaries for Linux and Mac OS X :( so sad. I think we need linux and mac os x binaries with mono or unity. I saw Unity creates simple standalone executable for Linux and Mac OS X. But I don't know how do we embed so into nw ( linux binary elf ) and dylib into nw.app/Contents/MacOS/nw ( binary of Mac OS X )

Yes you can use Enigma Virtual Box but it has not commandline access 😞 
I am sorry for busy thanks!
