### ISSUE TITLE
nwjs 21.3 on windows creates multiple process 

### ISSUE THREAD

**Issue by ShivaniPahuja02** [nwjs/nw.js#5807]
Hi,

we are upgrading nwjs from LTS version to latest version i.e nwjs 21.3. As per our analysis nwjs on windows creates total 5 process. One process is the main process and  one process is associated with DEV TOOL which end as we close the dubug window. We are targeting to rename the nwjs on windows platform. Is thers is any documnetation which states the purpose of all the process invoked by nwjs and their renaming procedure.Below is snapshot for the same.

<img width="230" alt="nwjsprocess" src="https://cloud.githubusercontent.com/assets/24776895/24341724/44e191dc-12d9-11e7-98d4-96b3543da559.PNG">

Regards,
Shivani Pahuja

**Comment by VasiliyIsaichkin** [comment]
In my experience it is enough to rename nw.exe to whatyouneed.exe

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by ShivaniPahuja02** [comment]
If we simply rename the nw.exe to MyApp.exe then on Windows 10 App name under process tab in the task manager does not reflect the new changed Application name where as Details Tab shows changed name .
Below is the Snapshot for the same 
_Process Tab Selected_  on Task Manager
<img width="204" alt="nwjsprocesstab" src="https://cloud.githubusercontent.com/assets/24776895/24350617/7be0f9a8-1300-11e7-9217-58ed484422fd.png">

_Detail Tab Selected_  on Task Manager
<img width="222" alt="myapp4" src="https://cloud.githubusercontent.com/assets/24776895/24350645/9d8571f6-1300-11e7-844b-630a4edc33a8.PNG">

Where as on windows 7 Rename procedure is working fine.

@rogerwang  we used below mailing list as well but there was no further updates on question

https://groups.google.com/forum/#!searchin/nwjs-general/shivani$20%7Csort:relevance/nwjs-general/24rtgtLpUXE/3vQA3Mx4FQAJ

We request you to update is there is any change in the rename procedure on Windows 10.

Regards,
Shivani Pahuja

**Comment by VasiliyIsaichkin** [comment]
For rename in task list you need update FileDescription field in Version resource section.
You can use commmand tool from (but need compile) [https://github.com/electron/rcedit](url) or you can take it from my repo - [https://github.com/VasiliyIsaichkin/rcedit/blob/master/bin/rcedit.exe](url)
Then rename nw.exe to MyApp.exe and run in console:
`rcedit MyApp.exe --set-version-string "FileDescription" "MyApp"`
