### ISSUE TITLE
WebUSB crash on device connect

### ISSUE THREAD

**Issue by drom** [nwjs/nw.js#5808]
## environment
```
nwjs-sdk-v0.22.0-beta1-linux-x64
Linux 4.10.4-1-default #1 SMP PREEMPT x86_64
```

## code
https://github.com/drom/jsdr/tree/master/experiments/WebUSB/src

The application requesting WebUSB device list on click of `Conncect` button.
In Chromium 57 I am getting the following menu to select device:

<img width="482" alt="screenshot_20170326_235532" src="https://cloud.githubusercontent.com/assets/511872/24344344/ea2ca938-127f-11e7-8a6e-f891e5300b92.png">

in nwjs I am getting crash with following error:

```
Segmentation fault (core dumped)
drom@linux-xqxs:~/work/github/drom/jsdr/experiments/WebUSB> [17923:17923:0327/000255.835727:WARNING:x11_util.cc(1360)] X error received: serial 204, error_code 176 (GLXBadWindow), request_code 153, minor_code 32 (X_GLXDestroyWindow)
[17923:17923:0327/000255.836097:WARNING:x11_util.cc(1360)] X error received: serial 206, error_code 9 (BadDrawable (invalid Pixmap or Window parameter)), request_code 152, minor_code 4 (DRI2DestroyDrawable)
[17923:17923:0327/000255.836122:WARNING:x11_util.cc(1360)] X error received: serial 207, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
```

Attaching Crash Report file.
[750f2692-2334-5551-55aa5d2b-3ffaf72b.dmp.txt](https://github.com/nwjs/nw.js/files/871679/750f2692-2334-5551-55aa5d2b-3ffaf72b.dmp.txt)

**Comment by Christywl** [comment]
I can reproduce this crash issue on Linux with nwjs-sdk-v0.21.3. And my chrome has no crash issue, but it has another error(`Uncaught TypeError: Cannot read property 'requestDevice' of undefined`).

**Comment by drom** [comment]
@Christywl you have to run chromium with keys:

```
--enable-experimental-web-platform-features
--disable-webusb-security
--enable-webusb
--enable-logging=stderr
```

**Comment by Christywl** [comment]
@drom , yes, chrome works fine for me with those keys:). Thanks.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by drom** [comment]
Thanks @rogerwang
