### ISSUE TITLE
nwjs 21.3 renaming issue on window 10

### ISSUE THREAD

**Issue by ShivaniPahuja02** [nwjs/nw.js#5809]
If we simply rename the nw.exe to MyApp.exe then on Windows 10 App name under process tab in the task manager does not reflect the new changed Application name where as Details Tab shows changed name .
Below is the Snapshot for the same
_Process Tab_ Selected on Task Manager
<img width="204" alt="nwjsprocesstab" src="https://cloud.githubusercontent.com/assets/24776895/24353785/d7bb7cf6-130c-11e7-8c25-71a8d3092512.png">

_Detail Tab_ Selected on Task Manager
<img width="222" alt="myapp4" src="https://cloud.githubusercontent.com/assets/24776895/24353790/e431d520-130c-11e7-9a2c-02abe62b47e8.PNG">

Where as on windows 7 Rename procedure is working fine.

We request you to please update is there is any change in renaming procedure on Windows 10.

Regards,
Shivani Pahuja

**Comment by VasiliyIsaichkin** [comment]
For rename in task list you need update FileDescription field in Version resource section.
You can use commmand tool from (but need compile) [https://github.com/electron/rcedit](url) or you can take it from my repo - [https://github.com/VasiliyIsaichkin/rcedit/blob/master/bin/rcedit.exe](url)
Then rename nw.exe to MyApp.exe and run in console:
`rcedit MyApp.exe --set-version-string "FileDescription" "MyApp"`

**Comment by rogerwang** [comment]
close and thanks to @VasiliyIsaichkin

**Comment by ShivaniPahuja02** [comment]
@VasiliyIsaichkin  Thanks for the update, File Description field updated successfully.

Can we use rcedit to edit any of the resource information. we tried to change the paramter 
"Original FileName" but it was not working .

Regards,
Shivani Pahuja

**Comment by VasiliyIsaichkin** [comment]
@ShivaniPahuja02 List of fields for version resource of nwjs.exe (please use as I pointed):
`CompanyName, FileDescription, InternalName, LegalCopyright, OriginalFilename, ProductName, CompanyShortName, ProductShortName, LastChange`

**Comment by vaibhavrmore1** [comment]
> @ShivaniPahuja02 List of fields for version section in resources of nwjs.exe (please use as I pointed):
> `CompanyName, FileDescription, InternalName, LegalCopyright, OriginalFilename, ProductName, CompanyShortName, ProductShortName, LastChange`
> For change Original FileName you need type
> 
> ```
> rcedit MyApp.exe --set-version-string "OriginalFilename" "MyApp.exe"
> ```

It's not working for me. It says "rcedit is not a command" nor it's allowing me to install exe.

Anything is missing there?

**Comment by RareScrap** [comment]
> [you can take it already compiled from my repo](#issuecomment-289428363)

> [It's not working for me. It says "rcedit is not a command" nor it's allowing me to install exe.](#issuecomment-789524252)

You can now download rcedit from [its release page](https://github.com/electron/rcedit/releases) and run as a regular exe in Windows CMD:
```
rcedit-x64.exe "My App.exe" --set-file-version "1.2.3.456"
```
