### ISSUE TITLE
NW.JS shows freezed showdevtool 

### ISSUE THREAD

**Issue by sourceskyboxer** [nwjs/nw.js#5810]
Hello guys, 

If I write var nw = require("nw.gui");
nw.Window.get().showDevTools();

Than It shows empty multi window :(

Is it bug nw.js 0.21.3 x86 Windows
![freezed_shopwdevtool](https://cloud.githubusercontent.com/assets/3496136/24378201/6954c4bc-1342-11e7-9882-7f5795bd78f2.JPG)

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8 and 10. Dev Tools could be shown normally.
![image](https://cloud.githubusercontent.com/assets/20039821/24384998/1fdc7c14-139a-11e7-82e3-e4929122b1c2.png)

**Comment by sourceskyboxer** [comment]
Thanks for resolve - But nwjs-v0.21.3 version can not show because showDevTools because it freezes 

sdk version has no problem thanks for resolving problem!

**Comment by rogerwang** [comment]
@sourceskyboxer Chrome stopped supporting NPAPI based plugins long time ago.
