### ISSUE TITLE
nw.js forgets to use existing localStorage and create a new empty localStorage

### ISSUE THREAD

**Issue by jardicc** [nwjs/nw.js#5811]
I am using `localStorage.getItem(a)` and `localStorage.setItem(a,b)` for saving my preferences.
It works good. I can close, open app and settings is still persistent.

If I pack my app into `package.nw` and I run my app then settings is saved into files in `users` folder which is ok. But when I open app again it ignores existing settings and creates new empty localStorage files.

How can I fix it?

```
nw.js v0.21.3
Node v7.7.3
Chromium 57.0.2987.110
commit hash: f770f4a-9af025f-16d3a8f-9af025f

Win 10
```

**Comment by RohitSharma27** [comment]
Is your application opening same domain the next time?

**Comment by jardicc** [comment]
What it means? My app is always in same folder and I am opening same index.html everytime and same url in webview.

**Comment by jardicc** [comment]
Now I know what is domain: https://groups.google.com/forum/#!topic/nwjs-general/Y5vzmtC3lD4

I think domain is different. I guess that .nw is unziped if I run app. And temp path could be different everytime. I will check it.

**Comment by jardicc** [comment]
Solved. You can close this issue.

There is "domain" property for package.json It doesn't works in manifest.json which is used in deprecated Chrome App. Works only in package.json.

I had problem with migration from manifest.json to package.json because "$" symbol was already reserved so I should reasign jquery into variable.
