### ISSUE TITLE
linux defunct process

### ISSUE THREAD

**Issue by pacmac** [nwjs/nw.js#5813]
Under Arch linux, I am getting 4 instances of nw despite single_instance = true is set in package.json:

	root      1790  1.6  4.2 388760 87188 tty1     Sl   10:28   0:02 /usr/share/nodejs/vwk/nw
	root      1792  0.0  1.3 174528 27572 tty1     S    10:28   0:00 /usr/share/nodejs/vwk/nw --type=zygote --no-sandbox --enable-crash-reporter=, --user-data-dir=/tmp
	root      1793  0.0  0.0      0     0 tty1     Z    10:28   0:00 [nw] <defunct>
	root      1825  5.0  4.3 385368 89192 tty1     Sl   10:28   0:05 /usr/share/nodejs/vwk/nw --type=zygote --no-sandbox --enable-crash-reporter=, --user-data-dir=/tmp

As you can see one of them is [defunct] and there are actually 4 processes running.

Why should there be so many processes running for a single instance and any idea why there is always one [defunct] process ?

**Comment by rogerwang** [comment]
NW is based on Chromium, it inherits the multiprocess architecture, see https://www.chromium.org/developers/design-documents/multi-process-architecture

And NW supports the single process mode: http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-disable-crash-handlertrue

The defunct process should not be there and maybe implies a bug.

**Comment by pacmac** [comment]
Thanks Roger;

--disable-crash-handler=true --enable-crash-reporter=false

seem to have no effect and I still have the same 4 processes running.

**Comment by rogerwang** [comment]
You need to pass --single-process as well

**Comment by pacmac** [comment]
Thanks so much for helping, but as in the original post, single_instance = true is already set in package.json.

So this has to be set in the command line and not the package.json ??

**Comment by rogerwang** [comment]
'single_instance' has nothing to do with the number of processes.

**Comment by pacmac** [comment]
Thanks, but it appears that command line args passed to the main thread are not inherited by it's children:

	root       915  2.7  4.4 406416 91856 tty1     Sl   11:57   0:03 /usr/share/nodejs/vwk/nw --disable-crash-handler=true --single-instance=true
	root       917  0.0  1.3 174528 27580 tty1     S    11:57   0:00 /usr/share/nodejs/vwk/nw --type=zygote --no-sandbox --enable-crash-reporter=, --user-data-dir=/tmp
	root       918  0.0  0.0      0     0 tty1     Z    11:57   0:00 [nw] <defunct>
	root       947  8.7  5.3 398940 109544 tty1    Sl   11:57   0:12 /usr/share/nodejs/vwk/nw --type=zygote --no-sandbox --enable-crash-reporter=, --user-data-dir=/tmp

**Comment by rogerwang** [comment]
it's not `--single-instance`, but `--single-process` ...

**Comment by Christywl** [comment]
close until there is more information
