### ISSUE TITLE
Doesn't work on Vista

### ISSUE THREAD

**Issue by techtonik** [nwjs/nw.js#5815]
It is said no Windows XP, but nothing about Vista. Running `nwjs-v0.21.4-win-ia32` there crashes:

![image](https://cloud.githubusercontent.com/assets/515889/24490866/3e39bd2c-152d-11e7-9fea-01a10e7e86af.png)

**Comment by rogerwang** [comment]
0.14 branch should be used for vista

**Comment by techtonik** [comment]
@rogerwang is it documented somewhere?
