### ISSUE TITLE
nw14 Issue :- Memory leakage when other window is open and closed from main app

### ISSUE THREAD

**Issue by hasanraz** [nwjs/nw.js#5819]
When I open and close a window from my main nw14 app memory is leaking below are my observation:-

1- When I launched my app the process was consuming 40 MB
2- When I opened a child window from my main memory increased from 40 MB to approx 65MB
3- When I closed the window memory consumption dropped to 45MB but never returned 40 MB which was expected.
4- When I again and again opened and closed the child window continuously for 1hr and 30 min memory increased from 40 MB to 125 MB.

My expectation was that this memory leakage issue has been taken case after 0.12.3 but it seems that memory leakage issue still persist in nw14. May not be with same magnitude but my observation is that even a blank window is opened and closed we can still find memory leakage on 3 to 5 MB each time.

I also tried by running global.gc() but that didn't work. As I expect that nw internally is also running garbage collector time to time. Also I tried to ClearCache() but that also didn't worked.

Can anyone give me any solution how to prevent this memory leakage. If anymore information is required then please let me know.

**Comment by hasanraz** [comment]
@rogerwang , Any thought on this.

**Comment by rogerwang** [comment]
You need to use the heap profiler in devtools to find out what's leaking memory.

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information

**Comment by Chia-L** [comment]
it's  Solved? @Christywl @rogerwang 
I also have the same problem，it doesn't seem to have any js memory leaks in devTool.
