### ISSUE TITLE
OSX auto-printing doesn't work

### ISSUE THREAD

**Issue by alexmccabe** [nwjs/nw.js#5820]
Version: 0.21.4
OS: OSX 10.12.4

I am trying to get the `Window.print()` function to work with autoprint enabled, but it just won't. The dialogue pops for a second then closes and nothing happens. If I `autoprint: false` and manually print, it works just fine. 

Printer.js

```js
Printer.prototype.print = function (options) {
    const self = this;

    try {
        currentWindow.print({
            autoprint: false
        });
    } catch (error) {
        console.log(error);    
    }
};

```

Calling code:

```js
const currentWindow = nw.Window.get();

currentWindow.showDevTools();

currentWindow.on('loaded', function () {
    currentWindow.print({
        autoprint: true,
        printer: 'Samsung_CLP_775_Series__SEC001599919F7A_'
    });
});
```

I have also tried some code that another user posted on an issue, that they claimed to work, but unfortunately I have no success:

```js
document.addEventListener('DOMContentLoaded', function () {
    var $ = document.querySelector.bind(document);
    const textarea = $('#payload');
    $('#print').onclick = function() {
        var data = textarea.value.trim();
        var payload = `data:text/html,${encodeURI(data)}`;
        nw.Window.open(payload, {show: true}, function (win) {
            win.on('loaded', function () {
                win.print({
                    autoprint: true,
                    printer: 'Samsung_CLP_775_Series__SEC001599919F7A_'
                });
                win.close();
            });
    });
 }
```

**Comment by alexmccabe** [comment]
Has anyone else experienced this issue, as I am still having it.

**Comment by alexmccabe** [comment]
I've just tested on Windows 10 (ia32) and I have the exact same issue, no printer activation and no items added to print queue when `autoprint: true`.

**Comment by rogerwang** [comment]
CC @Christywl

**Comment by Christywl** [comment]
I tried on Windows with nwjs-sdk-v0.21.4.  I'm not clear the expected behavior when `autoprint: true`. Please confirm. Here are my steps:
1) Start nwjs app
2) Input some words in the text area
3) Click **_Print_** button

Result:
A new window opens, it shows print page and quickly switches to the following window(automatically).
![image](https://cloud.githubusercontent.com/assets/20039821/24734190/9cf62fb8-1aae-11e7-96e5-6a2b9c41b6f9.png)

```
index.html:
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NW.js Silent Printing Demo</title>
  </head>
  <body>
    <textarea id="payload" placeholder="HTML"></textarea>
    <button id="print">Print</button>
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        const $ = document.querySelector.bind(document);
        const textarea = $('#payload');
        $('#print').onclick = () => {
          const data = textarea.value.trim();
          const payload = `data:text/html,${encodeURI(data)}`;
          console.log(payload);
          nw.Window.open(payload, {show:true}, (win) => {
            win.on('loaded', () => {
              win.print({
	       autoprint:true,
                printer: 'HP Universal Printing PCL 6'
              });
              win.close();
            });
          });
        };
      });
    </script>
  </body>
</html>
```

**Comment by alexmccabe** [comment]
The `autoprint: true`, according to the [documentation](http://nwjs.readthedocs.io/en/nw21/References/Window/#winprintoptions), automatically prints the document to the default printer on the operating system. 

What I am experiencing however, is that no print happens at all. With `autoprint: false` you get a print dialogue box, which when actioned, printing commences.

**Comment by Christywl** [comment]
I try this on Mac with nwjs-sdk-v0.25.3. Seem it works fine. `autoprint: true` automatically prints the web contents in the window. When launch the app, a save dialog pop ups and you could save the pdf file directly(no user’s interaction to print).
```
    <script>
const currentWindow = nw.Window.get();

currentWindow.on('loaded', function () {
    currentWindow.print({
        autoprint: true
    });
});
    </script>
```
If change to false, you will see a dialog and it needs your interaction.

**Comment by Christywl** [comment]
close until there is more information
