### ISSUE TITLE
Application crashes on start

### ISSUE THREAD

**Issue by nagarjuna993** [nwjs/nw.js#5823]
My application crashes on start on version 0.21.4. The app is working fine with 0.18.8 but it is crashing if i use any of the later versions after 0.18.8.

* State which version are you using
v0.21.4 SDK
* State which OS version are you running with
Windows 10 64bit
* Crash Dump
[crash dump.zip](https://github.com/nwjs/nw.js/files/888403/crash.dump.zip)

**Comment by Christywl** [comment]
@nagarjuna993 , I checked a simple app on Windows 10 with nwjs-sdk-v0.21.4, it works fine. Could you please share your sample to reproduce this issue?

**Comment by rogerwang** [comment]
@Christywl your simple app is different from the reporter's. Since it's a crash and the crash dump is provided, we have enough information for now to follow up.

**Comment by nagarjuna993** [comment]
This is still happening even in the latest version 22.3 SDK

**Comment by nagarjuna993** [comment]
Working in v0.23.4, don't know what was the issue.
