### ISSUE TITLE
(MacOS) SVG render issue

### ISSUE THREAD

**Issue by iw2rmb** [nwjs/nw.js#5824]
Get latest nwjs.
Open nwjs.app.
At DevTools console call 
`window.location = 'https://www.webcomponents.org/element/PolymerElements/iron-icons'`
All icons are rendered clearly.

Now create manifest like `{ "name": "test", "main": "<link_above>" }` 
Hit `nwjs.app/Contents/MacOS/nwjs <manifest.json>` — render is broken.
Why is that?

**Comment by iw2rmb** [comment]
Confirm it renders correctly with `"chromium-args": "--disable-gpu"` BUT without `--force-cpu-draw` flag.

**Comment by Christywl** [comment]
@iw2rmb , all icons renders correctly, you means icons in [Demo](https://www.webcomponents.org/element/PolymerElements/iron-icon/demo/demo/index.html) of the link , right? If yes, these two methods work fine for me on Mac with nwjs-sdk-v0.21.4(package.json without any `"chromium-args"`).

**Comment by rogerwang** [comment]
close until more information is available.
