### ISSUE TITLE
nw tray crashes when do remote desktop

### ISSUE THREAD

**Issue by anjanapaulose** [nwjs/nw.js#5827]
Hi,

We have an nw app running in windows.
Our nw app  start with system boot and it is in tray. Sometimes, if you remote deskop to the machine, the app crashes wit below exception 
[6308:808:0404/165531:FATAL:browser_process_impl.cc(1341)] Check failed: base::MessageLoop::current()->is_running(). 
Backtrace:
	v8::CpuProfiler::Dispose [0x00007FFE634BA4D1+378273]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE634456EC+1898528]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE63320A11+699205]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE632B10C9+242173]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE632B127F+242611]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE633F5D99+1572557]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE633C8FD1+1388805]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE633C9E28+1392476]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE633C8F06+1388602]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE633C903C+1388912]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFE633206FE+698418]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFE63271F05+1277813]
	v8::internal::NativesCollection<0>::GetScriptsSource [0x00007FFE62B4E854+1290916]
	v8::internal::NativesCollection<0>::GetScriptsSource [0x00007FFE62B4FF21+1296753]
	v8::internal::NativesCollection<0>::GetScriptsSource [0x00007FFE62B4A4FB+1273675]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFE6315B16E+135646]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFE6315B060+135376]
	v8::ResourceConstraints::set_max_executable_size [0x00007FFE6315A3E8+132184]
	ChromeMain [0x00007FFE62066031+209]
	(No symbol) [0x00007FF6AB875870]
	(No symbol) [0x00007FF6AB872EA0]
	IsSandboxedProcess [0x00007FF6AB8CC2F2+125470]
	BaseThreadInitThunk [0x00007FFE88C013D2+34]
	RtlUserThreadStart [0x00007FFE8B1D54E4+52]

This does not happen if the window is opened. It happens occasionally when app is minimzed and only in tray.

Any help is appreciated.

**Comment by anjanapaulose** [comment]
We had nw with version 14.5 which never had this issue. Started seeing this once we updated nw to 19.0. We have tried latest versions also, but same issue is there

**Comment by Christywl** [comment]
Is there a sample to reproduce this issue easily? Or please upload the crash dump files.

**Comment by anjanapaulose** [comment]
I have done some more tests. So we have modified the nw.exe - name , icon and version to our product requirements. Only with this changed exe , this issue is happening. There is no crash dump created with this, I got the above error from chrome debug log  by starting exe with --enable-logging --v=1 .

But we were doing the same thing with 14.5 nw, but never had this issue.

**Comment by anjanapaulose** [comment]
@Christywl, I got two dumps. Tried to analyze with minidumpstackwalk. Its crashing inside chrome. I am attaching them. Please check. 
Couldn't upload zip. Please change them back to .dmp
[a9b62b5d-72c0-455a-a63f-75c0bcdfd2e5.txt](https://github.com/nwjs/nw.js/files/925266/a9b62b5d-72c0-455a-a63f-75c0bcdfd2e5.txt)
[0dd21fca-70db-41c9-b517-50ca0ddb7d72.txt](https://github.com/nwjs/nw.js/files/925267/0dd21fca-70db-41c9-b517-50ca0ddb7d72.txt)

**Comment by anjanapaulose** [comment]
Another set of crash dumps , taken from win server 2012 R2 . (the above one is from a win7)

[70bd6af6-beae-4bb5-9680-b809321bf2ba.dmp.txt](https://github.com/nwjs/nw.js/files/928535/70bd6af6-beae-4bb5-9680-b809321bf2ba.dmp.txt)
[bbb3bd0d-0ad3-4846-9091-07877998a7d4.dmp.txt](https://github.com/nwjs/nw.js/files/928536/bbb3bd0d-0ad3-4846-9091-07877998a7d4.dmp.txt)

**Comment by rogerwang** [comment]
@anjanapaulose What's the exact version of NW for these dump files?

**Comment by anjanapaulose** [comment]
19.0 windows

**Comment by anjanapaulose** [comment]
@rogerwang , Also this is not particular to RDP. It happens, when you lock the system, and access it back after a period of time , say more than 15 mnts. But the system is not going to sleep.

**Comment by anjanapaulose** [comment]
@rogerwang , any timeline when you will check this. We would have to go back to 14.5, if this is not fixed by April end.

**Comment by rogerwang** [comment]
Will check it in this week. Thanks.

**Comment by anjanapaulose** [comment]
great, thank you

**Comment by rogerwang** [comment]
@anjanapaulose I decoded the stack dump, it's in the code of handling time zone change.
````
Thread 0 (crashed)
 0  nw.dll!`anonymous namespace'::PureCall [process_startup_helper.cc : 26 + 0x0]
 1  nw.dll!purecall [purevirt.cpp : 23 + 0x2]
 2  nw.dll!base::TaskRunner::PostTask(tracked_objects::Location const &,base::Callback<void ,1,1> const &) [task_runner.cc : 45 + 0x13]
 3  nw.dll!content::WorkerThreadRegistry::PostTaskToAllThreads(base::Callback<void ,1,1> const &) [worker_thread_registry.cc : 85 + 0x37]
 4  nw.dll!content::RenderThreadImpl::NotifyTimezoneChange() [render_thread_impl.cc : 1341 + 0x35]
 5  nw.dll!content::RenderThreadImpl::OnTimeZoneChange(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &) [render_thread_impl.cc : 2087 + 0x5]
````

However, the code has been largely changed in upstream in the latest stable version. So could you please try with latest version again?

**Comment by anjanapaulose** [comment]
@rogerwang  Thanks a lot for your help.  

We had tried with version 21 , when it was out, had the same issue.
Will try with latest - 22.0 . Need a couple of days to run it and see if its crashing. Will get back

Regarding the timezone, in our javascript code during startup, we set the locale to the system language . Do you think this  has anything to do with the issue. I mean any chance that this issue is triggered by the javascript code?

**Comment by anjanapaulose** [comment]
We have been trying with latest version - 22.0 for some time now. Not observed a crash so far.
Thank you for all the help. I am closing this bug.
