### ISSUE TITLE
NWJS rename to XYZ?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#5829]
Some Government organisation do not trust unknown names such as `nwjs` but they want to see suppliers name such as `Apple, Microsoft or XYZ`.
When i execute `nw.exe` i get this `nwjs` instead of package.json title or etc. 

How do i rename that nwjs into `i am company xyz or other app name related to lisensed / code signed company name`?

![](http://i.imgur.com/mce6XYc.png)

package.json had title without nwjs but still it shows nwjs.

**Comment by rogerwang** [comment]
Will provide a field in package.json for the replacement. btw, could you please provide an English version of the screenshot?

**Comment by shamun** [comment]
This is in OSX (manually from source code i modified) as English and the previous one was for Windows.
![screen shot 2017-04-05 at 11 52 22](https://cloud.githubusercontent.com/assets/107349/24702171/ebdc0172-19fd-11e7-8951-6ab6c31f951d.png)

**Comment by mscreenie** [comment]
Is this fixed?

**Comment by ayushmxn** [comment]
@mscreenie yup
