### ISSUE TITLE
App doesn't launch if user click on app icon 2-3 times without interval

### ISSUE THREAD

**Issue by tejendra007** [nwjs/nw.js#5830]
hi,

Iam working on desktop application which i'm creating using NWJS. Problem with my app is when i click repeatedly on app icon than application doesn't load, so i've used single instance : true in my package.json. this had fixed click issue but when i tried to launch app with pressing enter 2-3 times without interval it again stuck and app doesn't load. 
I can see multiple background processes created in task manager.

**Node Version:**
nw.js v0.12.3
io.js v1.2.0
Chromium 41.0.2272.76

**OS:**
Window 10

**Comment by Christywl** [comment]
@tejendra007 , could you please upload the full tests to reproduce this issue?

**Comment by tejendra007** [comment]
this issue can be mark as Fix. Issue is related to my javascript code not NWJS. because i've used settimeout and setInterval in my app which causing app to launch delay, in that case when someone again click on that app than App got stuck and won't launch.
