### ISSUE TITLE
NW Menu Bugged

### ISSUE THREAD

**Issue by keleko34** [nwjs/nw.js#5831]
0.20.1-sdk ++ through to 0.21.4-sdk
Windows: 10
Node: 7.8.0
Chrome: 57.0.2987.133 (64-bit)

Git Project: [App Example](https://github.com/keleko34/KonnektSuite_3D/tree/KSD-03)

Reproduction:

- Manifest
```
"window":{
    "frame":false,
    "transparent":true,
    "position": "center",
    "min_width": 400,
    "min_height": 300,
    "width": 1280,
    "height": 720
 },
"scripts": {
    "installer": "npm i && copy installer_files\\*.dll node_modules\\nw\\nwjs\\",
    "start": "node_modules\\nw\\nwjs\\nw . --disable-devtools --appmode=live",
    "debug": "node_modules\\nw\\nwjs\\nw . --enable-logging --remote-debugging-port=1729 --load-extension=Extensions\\ShaderEditorExtension\\src --appmode=debug",
    "editor": "node_modules\\nw\\nwjs\\nw . --appmode=editor"
  }
```
Using all above script commands:

1. `nw.Window.get().menu = null;`
 -- Causes a crash **note, no dump is made, attached npm log**
[debug-npm.txt](https://github.com/nwjs/nw.js/files/902102/debug-npm.txt)
2. `nw.Window.get().menu = new require('nw.gui').Menu({ type: 'menubar' });`
 -- Sets a gray bar over the top of the app that has a right click context.
![topbar](https://cloud.githubusercontent.com/assets/7937774/24747737/9bd6ad9c-1abd-11e7-94d9-ceeaadde68ae.PNG)
3. Do nothing
 -- any element with `-webkit-app-region: drag;` has right click context and no click events will work on it.
![topbar_normal](https://cloud.githubusercontent.com/assets/7937774/24747745/a2312a5a-1abd-11e7-9bd5-d3f95c3c702a.PNG)

My end goal is to have no context menu at all and allow for clicking/dblclicking on the topbar, but this doesnt seem possible right now.

**Comment by Christywl** [comment]
@keleko34 , I try to reproduce this issue.  Download your sample, and npm install, but there is no `node_modules\\nw\\nwjs\\nw` . My path is `node_modules\nw\bin\nw`.  
How should I check three issues you mentioned above? I just tried the cmd:
1. `cd KonnektSuite_3D-KSD-03\node_modules\nw\bin`
2.  `nw ..\..\..\..\KonnektSuite_3D-KSD-03 --disable-devtools --appmode=live`  **No crash issue**
![1](https://cloud.githubusercontent.com/assets/20039821/25366418/1b3bb3fa-29a2-11e7-88cd-989f22685666.png)

**Comment by keleko34** [comment]
@Christywl hmm.. I will double check tomorrow and get back to You, but that was the path that nwjs makes on mine. Sorry just got notice of the comment.

**Comment by Christywl** [comment]
close until there is more information.
