### ISSUE TITLE
how to get download file status

### ISSUE THREAD

**Issue by jin-pan** [nwjs/nw.js#5833]
I have a problem that if I want to download file to local, and i can't find the download status of the file.
   For example:
     there is a link in nwjs: &lt;a href="a.zip">download a file&lt;/a&gt;
     when click this link will pop out a saving file dialog,and the download will start when the saving path is selected.
    But i don't know whether the file is download completed or not.
    if i use web explorer to do this,it will have a download status,like this:
![11](https://cloud.githubusercontent.com/assets/17265536/24782722/7b3b9350-1b7a-11e7-86b8-74a8fa73e498.JPG)

And,How can i get this in nwjs??

Thank you and Please don't let me ask the question through google due to i can't view google website in China.

**Comment by CosmoMyzrailGorynych** [comment]
You should use chrome.downloads API: https://developer.chrome.com/extensions/downloads
It allows to control downloads and get their info programmatically. You also need to override the default behaviour in order to get a downloadID, which is required for all queries.

**Comment by CosmoMyzrailGorynych** [comment]
I zipped it in case developers site won't open

[chrome-downloads.zip](https://github.com/nwjs/nw.js/files/907294/chrome-downloads.zip)

**Comment by jin-pan** [comment]
@CosmoMyzrailGorynych 
thank you very much.
I think it maybe a solution.
But can you give me a sample about how to use it in nwjs.

**Comment by CosmoMyzrailGorynych** [comment]
@jin-pan actually this is how it is used in nwjs. I download updates for my app in such way. The chrome.downloads is a global object and can be used everywhere on the page.

`chrome.downloads.search` is a querying function that can be put into a `setInterval` to periodically update the progress info about download.

There is no easy way to create a UI for downloads though. I used chrome.notifications to display a popup message with progress bar, but, unfortunately, my solution is too tied for one file :(

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
