### ISSUE TITLE
autocomplete="off"Property not supported

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#5836]
autocomplete="off" Property not supported

**Comment by DinkoMiletic** [comment]
duplicate of #5184?

**Comment by Christywl** [comment]
`autocomplete="off"` works well for me on Linux with nwjs-sdk-v0.21.5 (code: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_input_autocomplete). @phpjishu , could you please provide your sample and nwjs version?

**Comment by rogerwang** [comment]
close until more information is available.
