### ISSUE TITLE
Use webrtc in node-webkit, why can only open 8-party video? 

### ISSUE THREAD

**Issue by zhaoshuyi** [nwjs/nw.js#5838]
Operating environment: Windows (x64) Chromium 57 + Node 7.8.0

Use webrtc in node-webkit, why can only open 8-party video? Where is there a limit?
Is Chromium 57 limited?

**Comment by rogerwang** [comment]
Please try Chromium browser first to make sure it's not a Chromium issue.

**Comment by zhaoshuyi** [comment]
I use Chromium Version 59.0.3068.0 test, 16 side video no problem, just now.

**Comment by zhaoshuyi** [comment]
I use Chromium Version 59.0.3068.0 test, 16-party video no problem. Is node-webkit limited?

**Comment by rogerwang** [comment]
You should test with Chromium 57.

**Comment by zhaoshuyi** [comment]
I use Chromium Version 57.0.2986.0 test, 16-party video is ok.But Node-webkit has more than 8 parties to get MediaStream failed.

**Comment by rogerwang** [comment]
Thanks. Please submit the sample so we can reproduce it.

**Comment by rogerwang** [comment]
close until more information is available.
