### ISSUE TITLE
Angularjs V1 issue with v8 Snapshot

### ISSUE THREAD

**Issue by webyot** [nwjs/nw.js#5839]
NW.js work fine with angular plain js file.

After compiling angularjs to v8 snapshot it stopped working
test app attached
[testApp.zip](https://github.com/nwjs/nw.js/files/913139/testApp.zip)

NW version : nwjs 57.0.2987.133
SDK : 0.21.5
MAC : 10.12.3 (16D32)

**Comment by rogerwang** [comment]
Could you please share the steps to reproduce the issue with your file?

**Comment by webyot** [comment]
In index.html file :

`      
  <script type="text/javascript" src="app.js"></script>
  
  
  <script>
//    require('nw.gui').Window.get().evalNWBin(null, 'app.bin');
  </script>`

Comment the app.js include & uncomment app.bin include.

and try run `nw .`

**Comment by rogerwang** [comment]
Could you please provide a un-minified  version so we can look into the JS source?

**Comment by webyot** [comment]
attached un-minified version of app.js
[app.js.zip](https://github.com/nwjs/nw.js/files/915663/app.js.zip)

**Comment by webyot** [comment]
tried with un-minified `nwjc app.js app.bin`

Still getting 

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.0-rc.2/$injector/modulerr?p0=testApp&p1=Typ…F%2Feppgdadlamekiimaloljfkbkmbpdklbl%2Flibs%2Fjs%2Fangular.min.js%3A20%3A1)
    at angular.min.js:6
    at angular.min.js:41
    at q (angular.min.js:7)
    at g (angular.min.js:40)
    at eb (angular.min.js:45)
    at c (angular.min.js:21)
    at Lc (angular.min.js:21)
    at oe (angular.min.js:20)
    at angular.min.js:327
    at HTMLDocument.b (angular.min.js:37)
```

**Comment by VasiliyIsaichkin** [comment]
I dnot why (a leave Angular developing many years ago - now use Vue), but if you use in .config Array-like arguments all works fine. 
This code works ok: [testApp.zip](https://github.com/nwjs/nw.js/files/915759/testApp.zip)

**Comment by webyot** [comment]
@VasiliyIsaichkin thanks working with Array-like arguments.

**Comment by Christywl** [comment]
I also can reproduce this issue on Linux/Windows with nwjs-sdk-v0.21.5. It works fine with plain js file. But it throws errors with `evalNWBin(null, 'app.bin')`.

**Comment by VasiliyIsaichkin** [comment]
@Christywl try to use my fix, its wotk :) But I dont know why :DDDD (I think problem in Angular magic)

**Comment by VasiliyIsaichkin** [comment]
Ok, I think I know what's happened. 
This example of code use config declaration method:
```
.config(function($stateProvider, $urlRouterProvider, $sceProvider) {
  ...
});
```
Angular for resolving variables names in anonymos function declaration ($stateProvider, $urlRouterProvider, $sceProvider) use something like .toString(). In normal JS we can parse result of .toString  (source of function with his declaration) and get names for declarated variables, but after nwjc calling method .toString() return only function () { [native code] } with empy variables declaration and angular cant resolve used variable names.
If you use array-like method, in first cells you set variables names manually and angular not use .toString

For 'compiled' code after nwjc we cant use .toString and others for functions.
I think need сlarify this point in documentation and close this issue.

p.s. sorry for my baaaad english :)

**Comment by webyot** [comment]
@VasiliyIsaichkin thinks for array-like config is working fine @rogerwang we can close the issue.

**Comment by chino23** [comment]
@webyot I suggest you take a look at https://github.com/olov/ng-annotate

This is designed to deal with those issues automatically. There are gulp and grunt scripts for that so you can just call that prior to your minification and  compiling. That's how I do it to make sure the variables don't get messed up.

**Comment by webyot** [comment]
@chino23 thanks thats the one we have used to fix issue at compile time.
