### ISSUE TITLE
Blurs on UI elements on HD monitors

### ISSUE THREAD

**Issue by skymen** [nwjs/nw.js#5841]
For a while now I have been experiencing various issues on NW.js apps and Electron apps.
I have a HD monitor, and I have heavy blurs on UI elements on apps built with NW.JS and Electron.
Notice that this does not happen when said apps are webapps. It only happens when they're built with NW.js or Electron.

![image](https://cloud.githubusercontent.com/assets/11213825/24954169/8b315ecc-1f7e-11e7-8ce8-397de89e7119.png)

![construct editor_2017-04-12_13-03-08](https://cloud.githubusercontent.com/assets/11213825/24954631/7dce399c-1f80-11e7-80f0-e6701a3b8606.png)
This last image is from a webapp that was wrapped. While the webapp when run in Chrome has absolutely no issue whatsoever, when it's running on NW.Js or Electron, it has those weird blurs.

I'm using a HD monitor (1920*1080) and I'm on Windows 10

**Comment by rogerwang** [comment]
Could you please upload a sample HTML which works fine in Chromium (not Chrome), but breaks in NW?

**Comment by skymen** [comment]
https://editor.construct.net/ is a webapp that works well on Chromium and that gets blurry when wrapped in NW.js and electron.

**Comment by Christywl** [comment]
nwjs-sdk-v0.21.5:
Tried on Windows 10(1366*768), the screenshot:

![5841](https://cloud.githubusercontent.com/assets/20039821/24988310/bb11ee36-2037-11e7-9336-862d3168436d.png)

Tried on Windows 8(1920*1080), the screenshot:
<img width="960" alt="5841-1" src="https://cloud.githubusercontent.com/assets/20039821/24988496/ea02e140-2038-11e7-8ecb-6011f1e14db1.png">

**Comment by skymen** [comment]
I'm on Windows 10 with 1920×1080. Or maybe this is an issue just for me,
and if it is I'd like to know how to possibly resolve it.

**Comment by skymen** [comment]
Okay, a friend helped me fiw this.
Apparently Nvidia's anti aliasing parameters were set to on for every app. When I switched it to none by default it stopped making that weird blur.
