### ISSUE TITLE
nw.js appears to have failed to download and extract. Attempting to download and extract again...

### ISSUE THREAD

**Issue by lazywe** [nwjs/nw.js#5844]
nw.js appears to have failed to download and extract. Attempting to download and extract again...

**Comment by rogerwang** [comment]
What is the URL?

**Comment by lazywe** [comment]
appledeiMac-2:socketIoTestTool apple$ nw -v
nw.js appears to have failed to download and extract. Attempting to download and extract again...

node version v6.10.0

**Comment by rogerwang** [comment]
How to reproduce this? And which version are you using? Please give detailed steps.

**Comment by lazywe** [comment]
I am in China

#  hear
appledeiMac-2:~ apple$ sudo npm install -g nw
...
npm http request GET https://registry.npmjs.org/invert-kv
npm http 200 https://registry.npmjs.org/invert-kv
/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw

> nw@0.21.5 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

#  stuck
#  How to correctly install

**Comment by rogerwang** [comment]
You should submit issue to the maintainer of the 'nw' npm module. It's not official/maintained by us.
