### ISSUE TITLE
What can I do if I want to disable the right-click context menu?

### ISSUE THREAD

**Issue by xuhaihao** [nwjs/nw.js#585]
I don't wanna show the context menu when I right-click.

[whose style is "-webkit-app-region: drag;"]

It's ugly.

**Comment by needhash** [comment]
If someone get there through Google, like me, there is a better way:
http://stackoverflow.com/questions/737022/how-do-i-disable-right-click-on-my-web-page

**Comment by ruleechen** [comment]
Stop 'contextmenu' event doesn't work on the element whose style is "-webkit-app-region: drag;"
