### ISSUE TITLE
NW.js Mouse Pointer Problem When Right-Clicking

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#5851]
**General Information:**
- Using NW.js version 0.19.0 & newer
- Windows 7 with latest drivers
- [Package.nw](https://cdn.discordapp.com/attachments/225550155531812865/303650028214419458/package.nw) File
- [C2 Mouse Plugin](https://github.com/nwjs/nw.js/files/1447723/C2.Mouse.Plugin.zip) Code

**Problem Description:**
I'm running a packaged _Construct 2_ game (HTML5).
I've recently noticed a NW.js specific issue with the mouse cursor in "none" mode.
Users have reported that the mouse cursor sometimes appears when performing a short right-click.

**Steps to reproduce:**
<1> Run the attached package.nw file using NW.js 0.19.0+
<2> Right click a few times while the cursor is on-screen
<3> Notice that the cursor sometimes appears even though it is set to "none"

**Observed Result**
The mouse cursor sometimes appears when right-clicking.

**Expected Result**
The mouse cursor should always be hidden in "none" mode.

**Comment by Christywl** [comment]
I can reproduce this issue on Windows with nwkjs-sdk-v0.21.6. It works fine on Linux.

**Comment by TheRealDannyyy** [comment]
This issue also seems to occur when using a custom cursor (sprite cursor).

**Comment by rogerwang** [comment]
Could you please provide a version running in Chrome browser or Chrome App so we can compare them?

**Comment by TheRealDannyyy** [comment]
[HERE](https://cdn.discordapp.com/attachments/225550155531812865/306999373072433154/NW.js_Mouse_Pointer_Problem_When_Right-Clicking.zip) is a Chrome App. I couldn't reproduce it in Chrome using the attached example.

**Comment by TheRealDannyyy** [comment]
@rogerwang [HERE](https://cdn.discordapp.com/attachments/225550155531812865/308889667766321152/mouse.zip) is the official Construct 2 mouse plugin*. 
Feel free to check out the code found inside the runtime.js file. 

*_More information on Construct 2 Plugins can be found [here](https://www.scirra.com/manual/69/plugins)._

**Comment by nafem** [comment]
I have had this issue as well. I thought it was a Chromium issue but now I have run further tests I can reproduce using the steps you have defined.

**Comment by nafem** [comment]
@rogerwang have you identified if this is a Chromium issue or NW.js specific? From my testing it looks like a NW.js issue.

**Comment by rogerwang** [comment]
I can reproduce it with 0.21.6 as @Christywl did, but with latest 0.23.2 or 0.22 it seems to work well.

**Comment by TheRealDannyyy** [comment]
Tried to reproduce this in nw.js v0.23.0 and the issue is even worse.

It seems like the initial issue has been resolved, however there is a rare case where the mouse still appears and this time it stays on the screen until any kind of mouse movement happens.

**Comment by TheRealDannyyy** [comment]
Tried to reproduce this in nw.js v0.24.0 with the same results.

> It seems like the initial issue has been resolved, however there is a rare case where the mouse pointer still appears and this time it stays on the screen until any kind of mouse movement/interaction happens.

**Comment by Christywl** [comment]
@rogerwang , I also reproduce this issue on Windows with nwjs-sdk-v0.24.0.

**Comment by IvanKorobko** [comment]
Still same result on Win7 x64 nwjs v0.25.0 - but not only for right mouse button click - for left button too... when fast clicking in the same point. 6 month without bugfix - whats wrong(

**Comment by TheRealDannyyy** [comment]
I can still reproduce this bug in nw.js v0.26.0, this still needs to get fixed.

**Comment by TheRealDannyyy** [comment]
@rogerwang If you got some time, I'd really appreciate a fix for this one for nw27 if possible.
I know it's a minor bug for web-based services but for video games it's quite an impactful one.

Can I provide something to help or is it already fixed in experimental builds and needs testing?

**Comment by call-me-bk** [comment]
That would not work, you will have to change the core drivers

**Comment by rogerwang** [comment]
Will see it. Thanks

**Comment by rogerwang** [comment]
@TheRealDannyyy  I think there is a chance that the issue is in c2runtime, not NW -- not able to confirm it since part of source code is minified.  The demo of pointer lock API works fine in NW: https://mdn.github.io/dom-examples/pointer-lock/

**Comment by TheRealDannyyy** [comment]
@rogerwang not sure if Construct 2 is really at fault. I'm not good with JS but you surely are, you can download the _mouse plugin_ as it comes with the engine here: [C2 Mouse Plugin.zip](https://github.com/nwjs/nw.js/files/1447723/C2.Mouse.Plugin.zip)

I'd appreciate if you could look into it and confirm that NW is not at fault.
I will close this issue and report the bug directly to the developer @AshleyScirra if that's the case.

**Comment by AshleyScirra** [comment]
This isn't about the pointer lock API, it's just the CSS 'cursor' style. The bug is when it's set to 'none', the mouse can still sometimes appear. AFAIK it stays hidden in Chrome so this is NW.js-specific.

**Comment by IvanKorobko** [comment]
@AshleyScirra, after the last update of the С2, I was able to run the preview in chrome and reproduce this bug there - with repeated pressing LMB the hidden cursor appears (only LMB)

**Comment by TheRealDannyyy** [comment]
@rogerwang Sorry for continuesly tagging you in here but this thread seems to go silent quite often.

Is there any progress being done towards fixing this issue? Ashley himself stated that NW.js is at fault (at least that's what I got from his response), so I assume the issue is with NW.js? 

> [C2 Mouse Plugin.zip](https://github.com/nwjs/nw.js/files/1447723/C2.Mouse.Plugin.zip) 
(Raw JS code used by Construct 2. The _runtime.js_ file should contain all the important code.)

**Comment by rogerwang** [comment]
@TheRealDannyyy no problem and thanks for pushing to fix. I tried the Chrome App you uploaded here in the latest Chrome browser and it has the same issue -- cursor sometimes appears. So this should be a bug in upstream and I suggest report this to Chromium upstream. There might be a workaround in C2: to use the pointer lock API instead but I'm not sure.

**Comment by TheRealDannyyy** [comment]
@rogerwang I'm not sure what "Chromium upstream" is, would you mind giving me a link to where you want me to report this?

**Comment by rogerwang** [comment]
https://bugs.chromium.org/p/chromium/issues/

**Comment by TheRealDannyyy** [comment]
Oh, you meant Chromium Bugs. 
My bad, I thought you meant some new type of chromium bug reporting site.

Here is the bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=788557
(Everyone reading, please **star** the report so we can get this fixed as soon as possible.)

**Comment by IvanKorobko** [comment]
@TheRealDannyyy, If still relevant, I found a way to get around this problem on Construct 2(at least, if it does not matter which mouse button is clicked).
You need to edit the runtime.js in the directory construct 2\exporters\html5\plugins\mouse
Delete the following lines:

`jQuery(document).mousedown(
				function(info) {
					self.onMouseDown(info);
				}
			);
			
			jQuery(document).mouseup(
				function(info) {
					self.onMouseUp(info);
				}
			);
			
			jQuery(document).dblclick(
				function(info) {
					self.onDoubleClick(info);
				}
			);`

To simulate clicks, you can use the Touch plugin. And the mouse plugin will be responsible for hiding the cursor, checking its location above objects, the coordinates of the custom cursor.

**Comment by TheRealDannyyy** [comment]
Thanks for the info but I'd rather like to see this getting fixed instead of doing a workaround.

**Comment by TheRealDannyyy** [comment]
Can't reproduce this issue using Chrome 65.0.3325.181 anymore. I assume this issue has silently received a fix from the Chromium Dev's. (Also tested using NW.js v0.29.0 with no problems.)

I'm not sure if this got backported to older versions but it's definitely working fine in Chromium M65+.
