### ISSUE TITLE
Sign the App Can not open~

### ISSUE THREAD

**Issue by zhailei31665431** [nwjs/nw.js#5853]
According to this link "http://nwjs.readthedocs.io/en/nw21/For%20Users/Advanced/Support%20for%20Mac%20App%20Store" and create new app。。The new app can not working...  Dobule click open then close...Version:nwjs-mas-v0.19.5-osx-x64

**Comment by chino23** [comment]
Open the app by terminal to see the error output:

````
cd 'folder where .app is in'
./nwjs.app/Contents/MacOs/nwjs
````

Then check there terminal for what errors pop up
