### ISSUE TITLE
Can nw.js protect the code of the server side app?

### ISSUE THREAD

**Issue by kanezch** [nwjs/nw.js#5857]
Hello, recently we develop a server side nodejs app, and we have to deploy it in our client's environment,  but we want to protect the source code. 

I read the docs of nw.js, and found that there is a note in the section "Protect JavaScript Source Code",
**The compiled code is executed in Browser Context**  . 

I just want to know if nw.js can protect our source code in this scenario. We want to find a tool that can really compile js into native machine code, rather than obfuscation.

**Comment by rogerwang** [comment]
It's supported. The binary can be compiled from Node.js code. The document means that the API used to load the binary should be called from DOM. 

And  please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by kanezch** [comment]
@rogerwang 
Firstly, thank you for your response!
It is a pity that I cannot access google group because I am behind the proxy of my company's network.

I have read the docs but didn't find a example of how to execute the node.js binaray file directly(not in a brower Context.)
Another question, how to pack a whole nodejs project into one binary file?
