### ISSUE TITLE
Module is not defined

### ISSUE THREAD

**Issue by xahon** [nwjs/nw.js#5861]
When i export custom module error shows in console "module is not defined".
I export module in standart way:
`var a = (function() {
    //stuff
});
module.exports = a;`

NW 1.2
Node v7.8.0
Ubuntu 16.04

**Comment by VasiliyIsaichkin** [comment]
Please provide whole smaple code as zip with calling file
Also does not exist NW.js ver 1.2.

**Comment by xahon** [comment]
[example.zip](https://github.com/nwjs/nw.js/files/940723/example.zip)
Here is minimized project. Sorry for waiting

**Comment by xahon** [comment]
In this #667 issue i've found solution. Just need to prepend module with `global.` scope. But require still not working

**Comment by xahon** [comment]
I've found a solution. `Require` requires absolute path

**Comment by VasiliyIsaichkin** [comment]
You have two problems in code:
1. You put your module `exporting_module.js` to html as `<script src="src/js/exporting_module.js" charset="utf-8"></script>`. The browser tries to load it as simple js file in browser context module, not as module and can't set exports for undefined 'module'. Just remove this line from html
2. You use relative path for require, but in nwjs if you call require from browser-context module you current path is where package.json. For fix problem you need use path from package.json `var exportable = require("./src/js/exporting_module.js");`

**Comment by xahon** [comment]
why when i import class
someClass.js
`class someClass {
    constructor() {
    }

    sayHello() {
         console.log("Hello");
    }
}
//module.exports is not defined
global.module.exports = someClass;
console.log(new someClass()); //Not called
`

from index.js
`var someClass = require("./src/js/someClass");
console.log(someClass);
`
it gives me empty object.
Path is right (If i make a typo it throws an error)
