### ISSUE TITLE
nw.js + vk api

### ISSUE THREAD

**Issue by necromind** [nwjs/nw.js#5862]
Help me pls. How to use vk api(vk.com) in nw.js app? Fow example https://github.com/57uff3r/nodejs-vksdk is for server side apps. How to use some api helpers for authorization and requests in nw.js standalone apps?

**Comment by VasiliyIsaichkin** [comment]
just insert to html `<script>require('./app.js')()</script>`, then create app.js:
```
module.exports=function(){
  //Your code here
}
```
And place your code like nodejs.

**Comment by rogerwang** [comment]
thanks to @VasiliyIsaichkin for answering.
@necromind 
please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
