### ISSUE TITLE
MacOS nwjs Framework image not found

### ISSUE THREAD

**Issue by cryomi** [nwjs/nw.js#5863]
Hi all,
MacOS 10.12.4 Sierra
nw js 0.22.0 sdk

`$ /0.22.0-sdk/osx64/nwjs.app/Contents/MacOS/nwjs `
```
dlopen /0.22.0-sdk/osx64/nwjs.app/Contents/MacOS/../Versions/58.0.3029.81/nwjs Framework.framework/nwjs Framework: 
dlopen(/0.22.0-sdk/osx64/nwjs.app/Contents/MacOS/../Versions/58.0.3029.81/nwjs Framework.framework/nwjs Framework, 257): 
image not found
Abort trap: 6
```

**Comment by rogerwang** [comment]
It works for me. How did you unzip the official package? I was using `unzip` in the command line.

**Comment by cryomi** [comment]
I did download/unpack with nw-builder https://github.com/nwjs-community/nw-builder.

**Comment by rogerwang** [comment]
That would be an issue with nw-builder. Please file an issue there.

**Comment by cxa** [comment]
I still encounter this issue by npm version, but no problem on directly downloaded version.
