### ISSUE TITLE
nw.js 0.22 - nothing rendered using specific chromium-args

### ISSUE THREAD

**Issue by tiitremmel** [nwjs/nw.js#5866]
With latest version of 0.22 [nwjs-sdk-v0.22.0-osx-x64.zip](http://dl.nwjs.io/live-build/04-21-2017/nw22-7b05249-eede001-35ab879-388a4fe/v0.22.0/nwjs-sdk-v0.22.0-osx-x64.zip) app does not show nothing - just gray window. Same thing with dev tools.
Simple package.json
```
{
    "name": "foo",
    "main": "http://google.com",
    "node-remote": "<all_urls>",
    "chromium-args": "--disable-web-security --disable-gpu --force-cpu-draw"
}
```

Result looks like this
![Screenshot](https://www.dropbox.com/s/mqpkd4t08sm25iy/Screenshot%202017-04-21%2010.21.22.png?dl=1)

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.22.0/v0.21.6. It works well on Linux/Windows.

**Comment by rogerwang** [comment]
@jtg-gg could you please check this as it involves the transparency switches?

**Comment by jtg-gg** [comment]
@rogerwang I'll take a look on this on weekend

**Comment by Blatman** [comment]
Note: same issue as #5741, it breaks click-through transparency 
cheers.

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request (https://github.com/nwjs/chromium.src/pull/80) for the fix

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
