### ISSUE TITLE
nwjs 0.18.1-sdk on Mac 10.12.3 is crashing when making many get requests

### ISSUE THREAD

**Issue by mfehrenb** [nwjs/nw.js#5867]
[stack_trace_decoded.txt](https://github.com/nwjs/nw.js/files/948271/stack_trace_decoded.txt)

Issues meet the checklist above will be processed before those don't.

We have a desktop client that allows us to sync content between the file system and our cloud system. As part of testing uploading many files (1000) I see a crash every now and then around our asynchronous api (Get to retrieve our node model after upload is complete). From logging in our system I see that we make a get request to our server that never returns. We are using this module to make requests:

var request = require('request');

I have attached a decoded stack trace (using the 0.18.1 symbols). I would like to get some feedback on the crash or know if this is fixed in a later version before making recommendations to product management regarding upgrading our code to the latest.

**Comment by Christywl** [comment]
@mfehrenb , is there a sample to reproduce this issue?

**Comment by mfehrenb** [comment]
I reproduced this using our core desktop client. To access that you can go here:

https://core.opentext.com/

Sign up for a free account and download the client. I then created 1000 dummy files on my mac 10.2.3 machine using this command:

dd if=/dev/random bs=1 count=1024*1000 | split -b 1024 -a 10

In the mac file explorer I drop the 1000 files into my sync folder location. I noticed the crash after about 600 files. 

If you prefer I can give you the failing route/request code to try and replicate against though I've only tried to replicate this against our running client.

For some additional context I'm adding in some captured wireshark logs a colleague retrieved. Looks like there is a dropped packet at the time of the crash. Might be unrelated but thought I'd add it here just in case.
[mac_crash_wireshark.zip](https://github.com/nwjs/nw.js/files/951575/mac_crash_wireshark.zip)

**Comment by Christywl** [comment]
@mfehrenb , could you please upload the code to reproduce this issue?  I have downloaded this client and created 1000 dummy files.

**Comment by mfehrenb** [comment]
I'm asking my boss what I can provide code wise here. Will most likely be snippets. Just to confirm: You installed the client, enabled desktop sync and dropped the 1000 files into your OpenText Core folder (should be created under your user folder by default)? And no crash?

**Comment by Christywl** [comment]
Installed the client, enabled desktop sync and dropped 1000 files into my OpenText Core folder. No crash happened. Is this still reproduced for you?

**Comment by Christywl** [comment]
close until there is more information
