### ISSUE TITLE
sdk can't close

### ISSUE THREAD

**Issue by keyiis** [nwjs/nw.js#5869]
OS :win10 x64
nw:0.14.7
I start app through command
`D:/nw/0.14.7-sdk/win32/nw.exe "./output/build"`
when i closed app,but app still run in backend
![qq 20170423161819](https://cloud.githubusercontent.com/assets/7766085/25312015/83c41a24-2840-11e7-93f0-560eaedf6354.png)

**Comment by Christywl** [comment]
I try some simple tests on Windows with nwjs-sdk-v0.22.0, can't reproduce this issue. @keyiis , could you please upload your sample to reproduce this issue?

**Comment by keyiis** [comment]
@Christywl thanks reply!my app too large,i used 0.14.7 and i can't upgrade,because my app need runing on xp.

**Comment by rogerwang** [comment]
close until more information is available.
