### ISSUE TITLE
How to set exe metadata

### ISSUE THREAD

**Issue by keyiis** [nwjs/nw.js#5870]
Has some tool can set nw app metadata,I used `nw-builder` to package app.
if i use electron,i can use `electron-packager` set `win32metadata`,nwjs can do?
![qq 20170424173214](https://cloud.githubusercontent.com/assets/7766085/25331078/5a11fe92-2914-11e7-8ebf-e5ff740e7041.png)

**Comment by VasiliyIsaichkin** [comment]
Read my comments in #5809 
Please ask questions in nwjs mailing list: https://groups.google.com/forum/#!forum/nwjs-general
Please close this issue.

**Comment by keyiis** [comment]
@VasiliyIsaichkin  thanks, if rcedit can integration to nw-builder just fine.

**Comment by keyiis** [comment]
@VasiliyIsaichkin i tyed it,but can't set copyright/language/Original File Name.

**Comment by keyiis** [comment]
@VasiliyIsaichkin sorry!I can't access google.

**Comment by VasiliyIsaichkin** [comment]
> @VasiliyIsaichkin i tyed it,but can't set copyright/language/Original File Name.
Please show your commads for it

**Comment by VasiliyIsaichkin** [comment]
This commands works fine:
```
rcedit nw.exe --set-version-string "CompanyName" "MyCorp inc."
rcedit nw.exe --set-version-string "FileDescription" "My Mega software"
rcedit nw.exe --set-version-string "InternalName" "my_mega_soft"
rcedit nw.exe --set-version-string "LegalCopyright" "(c)MyCorp inc. '2017"
rcedit nw.exe --set-version-string "OriginalFilename" "mymegasoft.exe"
rcedit nw.exe --set-version-string "ProductName" "MyMegaSoftware Hacker edition"
rcedit nw.exe --set-version-string "CompanyShortName" "MyCorp"
rcedit nw.exe --set-version-string "ProductShortName" "MySoft"
rcedit nw.exe --set-file-version "1.0.7.2757"
rcedit nw.exe --set-product-version "1.0.0.2757"
```
But you can't change language from rcedit because its stored in special VarFileInfo section in Translation key with 2 args - [read in MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381057(v=vs.85).aspx), rcedit has no support for edit Translation key.
I not need change lang and no have idea now how easy change Translation key (you need set it to 0x0404 0x04B0 for traditional chinese or 0x0804 0x04B0 for simplified chinese) via command-line tools,  you can try any Resource Hacker software with gui for editing this key.
![170424-140648-stoorwzoqx9uwhx](https://cloud.githubusercontent.com/assets/1153891/25334480/622940a8-28f7-11e7-91ad-26a4971f6bc8.png)

**Comment by keyiis** [comment]
@VasiliyIsaichkin  thanks a lot!

**Comment by mscreenie** [comment]
@VasiliyIsaichkin  Can you confirm this still works with the latest version? I'm trying rcedit however when I run the exe the app is missing / only shows nwjs default app page.

**Comment by VasiliyIsaichkin** [comment]
Tomorrow I'll check

**Comment by VasiliyIsaichkin** [comment]
At first look, there are no problems.
Tested with nwjs 0.24.3x64 + windows 10x64

[Used rcedit binary](https://raw.githubusercontent.com/VasiliyIsaichkin/rcedit/master/bin/rcedit.exe)
![image](https://user-images.githubusercontent.com/1153891/29489951-97a4debc-8546-11e7-94a1-63ec32fc37b3.png)
![image](https://user-images.githubusercontent.com/1153891/29490017-8315bf5a-8548-11e7-9526-04f6cbccffbd.png)

packages.json:
```
{
	"main"       : "index.html",
	"name"       : "5870test",
	"description": "5870 Test",
	"version"    : "0.1.0",
	"window"     : {
		"width" : 800,
		"height": 500
	},
	"webkit"     : {
		"plugin": true
	}
}
```
index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>5870 Test</title>
</head>
<body>
<h1>5870 test case is ok</h1>
<p>
	nw.js ver: <script>document.write(nw.process.versions['nw']);</script>
</p>
</body>
</html>
```

**Comment by mscreenie** [comment]
I did some further tests on Windows 10 and tried to combine package.nw zip and exe together. 

The app will not load anything if rcedit is used before combining or after the combine.

**Comment by mscreenie** [comment]
Update: I think assessment is premature. I am using Powershell to automate some of my build cycle and the culprit seems to be Compress-Archive cmdlet. When I compress an archive using 7zip and combine the two files it will work.

I'll do further tests to see if this is actually the case.

**Comment by mscreenie** [comment]
Solved: I installed 7zip cmdlet in Windows 

`Compress-7Zip -CompressionLevel Normal -Format Zip -Path "$nwjsWorkingApp" -ArchiveFileName "$nwjsTemp\package.nw"
`
