### ISSUE TITLE
Frameless windows don't trigger mouseout events

### ISSUE THREAD

**Issue by sonicsnes** [nwjs/nw.js#588]
There seems to be an issue generating mouseout events in frameless windows. This even adversely affects :hover css styles.

Create a frameless window with a different background-color in the body:hover css. Mouse over the frame, then back out, and notice how the background color doesn't change to normal. The same issue can be tested by listening for mouseout javascript events on the body object, which are never fired.

Neither issue occurs with framed windows.
##

**Comment by Nodebuck** [comment]
+1 it's still not fixed :(

**Comment by rogerwang** [comment]
@ghostoy could you verify this with 0.13.0 beta?

**Comment by ghostoy** [comment]
@rogerwang Tested on Windows and Linux. When move mouse slowly out of frameless window, `mouseout` and `:hover` are **NOT** triggered. But works well when you move mouse fast in and out. And it also happens on Chrome 48 stable. So I think It should be an issue of upstream.

**Comment by fuwenchun** [comment]
@rogerwang Tested with 0.13.1 ,hover is failure with the edge of the window elements.Example: the hover is not reverted to normal.
![image](https://cloud.githubusercontent.com/assets/13395537/14073455/e5d78706-f4fb-11e5-9b2c-904fcae0de63.png)

**Comment by ghostoy** [comment]
Upstream bug tracking in here: https://crbug.com/584841.
Currently it's still not fixed in M54.

**Comment by Yonezpt** [comment]
Hoping for a fast resolution on this from their part, I had to work around this by placing four invisible 5px borders inside the resizable frameless window so that the mouseout event can fire correctly.

**Comment by Nodebuck** [comment]
@Yonezpt I tried that workaround too but unfortunately the resizing of the window is weird (because you have to drag the invisible edges). Also you need to disable hardware acceleration, which is bad for graphically demanding apps.

**Comment by Yonezpt** [comment]
The window contents do not interfere with the resizing of my frameless window at all and I don't have to disable any hardware acceleration at all. The only downside is that I have less 5px of usable area around the window.
