### ISSUE TITLE
NW crash when debugging with developer tools

### ISSUE THREAD

**Issue by Shawyeok** [nwjs/nw.js#5882]
Example code(index.html):
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>.
    <script type="text/javascript">
      var request = require('request');
      setInterval(function() {
        request({
          url: 'http://www.bing.com',
          method: 'get'
        }, function(err, response, body) {
          if (err) return console.error(err.stack);    // line 16

          console.log(response, body);
        });
      }, 3 * 1000);
    </script>
  </body>
</html>
```
Open developer tools in the page above, add a **breakpoint** on line 16, NW will crash after click `Resume script execution` button second time.

Crash dump: [a9b42631-02f5-4f9b-a0cb-80bbb4675faa.zip](https://github.com/nwjs/nw.js/files/961306/a9b42631-02f5-4f9b-a0cb-80bbb4675faa.zip)

@xianlong1226

/cc @fujunwei @xzhan96 @rogerwang

**Comment by Shawyeok** [comment]
My environment:

nw.js v0.21.2
Node v7.7.3
Chromium 57.0.2987.98
commit hash: 6388aaa-d7e4cbf-96303a2-d7e4cbf
OS: MacOS 10.12.4

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by Shawyeok** [comment]
Can you please refer your commit that fix this bug?

**Comment by rogerwang** [comment]
https://github.com/nwjs/chromium.src/commit/f4bd6d4d8ef74d1132f2f73dd8639dd5c5d7f799
