### ISSUE TITLE
0.23.0b1 - Re-focus on inputbox with chars crashes nwjs

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5885]
OSX 10.11.6 El Capitan
nwjs 0.23.0b1-sdk-osx-x64

index.html with standard html5 inputbox - type in chars eg: ffffguyvjh then remove focus.
When inputbox is clicked again to regain focus the app crashes.
OK  with just numerics in inputbox.
OK with 0.22.1 and prior

Not much in app log at all.

Test app attached

![inputboxcrash](https://cloud.githubusercontent.com/assets/11089335/25498269/3c2e4b52-2b7f-11e7-8c9a-924f0f61d580.jpg)

[inputboxcrash.zip](https://github.com/nwjs/nw.js/files/962522/inputboxcrash.zip)

**Comment by Christywl** [comment]
@Blatman , Could you please share your download url for 0.23.0b1? I can't find this osx build in https://dl.nwjs.io/live-build/04-28-2017/nw23-3bd4af6-f7f5dca-5e6428a-f2085b9/v0.23.0-beta1/.

**Comment by Blatman** [comment]
Just noticed that it needs to be at least 5 chrs eg:  abcd is OK but abcde crashes.

**Comment by rogerwang** [comment]
The latest build seems to work well with your sample: https://dl.nwjs.io/live-build/04-29-2017/nw23-3bd4af6-4d7f95f-5e6428a-f2085b9/v0.23.0-beta1/

**Comment by Blatman** [comment]
OK - latest build works fine - earlier build still fails so maybe it was a bad build.

Thanks for that I will close this now.
