### ISSUE TITLE
Theme on my computer seems to default to a Blue title bar.

### ISSUE THREAD

**Issue by krum110487** [nwjs/nw.js#5886]
Hello everyone, for some reason my nwjs started to look like this:
![image](https://cloud.githubusercontent.com/assets/823986/25511718/90b17a16-2b96-11e7-9ce4-23580ef818bb.png)

my package looks like this:
```
{
  "main": "index.html",
  "name": "folder setup",
  "description": "demo folder setup",
  "version": "0.1.0",
  "keywords": [ "demo", "node-webkit" ],
  "window": {
    "title": "node-webkit demo",
    "icon": "link.png",
    "toolbar": false,
    "frame": true
  }
}
```

I expect the title bar to be the same theme as my computer which looks like this:
![image](https://cloud.githubusercontent.com/assets/823986/25511790/24cbdf5c-2b97-11e7-923c-86c7b4965648.png)

I am on Windows 7, I am using version 0.21.6

I also tried 0.22.0 and 0.20.3 all the way back to 0.16.x and the same code looks normal on other computers with the same code.

**Comment by Christywl** [comment]
I check this on Windows 8 with nwjs-sdk-v0.22.0. It's different from Window 7.
![image](https://cloud.githubusercontent.com/assets/20039821/25512227/b399c976-2bfe-11e7-9206-55ad4887718b.png)

**Comment by krum110487** [comment]
That is what is weird, on every other computer I tried, it looks as I expect. And at one point it looked normal on mine, I have no idea what changed, but no matter what I do, I cannot make it revert.

**Comment by Christywl** [comment]
The result is same as yours in my Windows 7. Maybe Windows 7 specific? @rogerwang

**Comment by krum110487** [comment]
On some windows 7 machine it works as expected, I am unsure what decides it.

**Comment by rogerwang** [comment]
It depends on the settings regarding Aero Glass effect or whether DWM of windows is working. It's the same behavior with upstream Chrome Apps.
