### ISSUE TITLE
Crash on send email CentOs7

### ISSUE THREAD

**Issue by flavienliger** [nwjs/nw.js#5888]
I am using nwjs 0.22.0, and I have a problem when I try to send an email via the Nodemailer library or gmail-sender-oauth on linux (centos7) nwjs crash.
This can come from the same problem as here https://github.com/nwjs/nw.js/issues/5796 , but the code works fine under NodeJs 7.9.0.
When it crashes it displays this message:
```[0428/171459.798971:WARNING:chrome_main_delegate.cc(565)] final extension: 
*** Error in `/usr/local/bin/nwjssdk/nwsdk': double free or corruption (out): 0x00007fbecfba2030 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7cfe1)[0x7fbec84c3fe1]
/usr/local/bin/nwjssdk/lib/libnw.so(+0x1736707)[0x7fbec9f3e707]
======= Memory map: ========
46b1f00000-46b1f80000 rw-p 00000000 00:00 0 
104a0040000-104a0041000 ---p 00000000 00:00 0 
...
[9923:9942:0428/171522.658786:ERROR:native_backend_kwallet_x.cc(813)] Error obtaining KWallet handle
```

Do you have an idea of the reason or a solution? On Windows / Mac it works correctly.

**Comment by rogerwang** [comment]
Could you please upload the crash dump file?

**Comment by flavienliger** [comment]
Yes of course.

[chromium-extension-minidump-31f188db0d65a867.txt](https://github.com/nwjs/nw.js/files/969998/chromium-extension-minidump-31f188db0d65a867.txt)

**Comment by flavienliger** [comment]
I do more tests, it crash 50% of the time if I use smtp as hotmail with the [emailjs](https://github.com/eleith/emailjs) library.

Here's another dump when emailjs crash, with sample code:
[chromium-extension-minidump-abdc2ac5b03ec719.txt](https://github.com/nwjs/nw.js/files/976123/chromium-extension-minidump-abdc2ac5b03ec719.txt)

```javascript
var email = require('emailjs');

var server 	= email.server.connect({
   user:    "xxx@hotmail.fr", 
   password:"xxx", 
   host:    "smtp-mail.outlook.com", 
   tls: {ciphers: "SSLv3"}
});

server.send({
   text:    "i hope this works", 
   from:    "you <xxx@hotmail.fr>", 
   to:      "someone <xxx@hotmail.fr>",
   subject: "testing emailjs"
}, function(err, message) { console.log(err || message); });
```
And if you need example with nodemailer :

```javascript
var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
	service: 'Gmail',
	auth: {
	  user: 'xxx@gmail.com',
	  pass: 'xxx'
	}
 });
 
transporter.sendMail({
	from: 'xxx <xxx@gmail.com>',
	to: "xxx <xxx@hotmail.fr>",
	subject: "title",
	text:    "i hope this works", 
	html: "test"
  }, function(err, message) { console.log(err || message); });
```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? I try this on Ubuntu 16.04 with nwjs-sdk-v0.24.2, don't meet crash issue. But there is an error(`Error: Invalid login: 534.5.7.14`) in my test.

**Comment by Christywl** [comment]
close until there is more information
