### ISSUE TITLE
Still stuck on "Right-click to run Adobe Flash Player"

### ISSUE THREAD

**Issue by MultiplyByZer01** [nwjs/nw.js#5891]
Same issue as #5224, except that it only occurs for SWFs embedded in a website embedded in an iframe.

My setup:

 - Windows 10 x64
 - NW.js SDK v0.22.0
 - Adobe Flash Player 25

package.json:

```json
{
	"name": "Test App",
	"main": "index.html"
}
```

index.html:

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Test App</title>
</head>
<body>
	<iframe src="http://www.notdoppler.com/strikeforceheroes2.php" nwdisable nwfaketop width="800" height="600"></iframe>
</body>
</html>
```

In previous versions of NW.js, you could select "Always allowed to run" in `chrome://plugins` to bypass this, but this is no longer possible, as the Chrome team has removed `chrome://plugins`.

**Comment by Christywl** [comment]
I try on Windows 8/Linux with nwjs-sdk-v0.22.0. Flash works well. But it doesn't work on Windows 10, the result is same as the reporter.

**Comment by MultiplyByZer01** [comment]
I should mention that this is a regression. It worked fine (with a workaround) on v0.20.0

**Comment by keerkeerhi** [comment]
I encounter the same problem . I user " Window.open(url, [options], [callback])"  replace "iframe".

**Comment by MultiplyByZer01** [comment]
Workaround:

```javascript
chrome.contentSettings.plugins.set({
	primaryPattern: "<all_urls>",
	resourceIdentifier: { id: "adobe-flash-player" },
	setting: "allow"
});
```

Nevertheless, the bug should be fixed.

**Comment by TianEn-Zhao** [comment]
> 解决方法：
> 
> ```js
> 铬。contentSettings 。插件。集合（{ 
> 	primaryPattern：“<all_urls>” ，
> 	resourceIdentifier：{  ID：“土坯-Flash播放器”  } ，
> 	设置：“允许” 
> } ）;
> ```
> 
> 尽管如此，该错误应已修复。

放在哪执行呢
