### ISSUE TITLE
nw.js title with chinese character encoding error in fedora 25 , gnome 3 desktop

### ISSUE THREAD

**Issue by suziwen** [nwjs/nw.js#5895]
nwjs version: 0.22.0, linux x64
os: fedora 25, gnome 3(gnome-shell) desktop

![09327d9e-dd23-40f5-ae5d-f1beabfa3853](https://cloud.githubusercontent.com/assets/57370/25626533/72b232f2-2f25-11e7-8a9b-90a481a45854.png)

## package.json

``` json
{
  "main": "index.html",
  "name": "你好もしもしhello",
  "description": "hello",
  "version": "1.0.0"
}
```
[hello.tar.gz](https://github.com/nwjs/nw.js/files/971013/hello.tar.gz)

**Comment by Christywl** [comment]
I checked on Linux Ubuntu/Windows 8 with nwjs-sdk-v0.22.0, can't reproduce this issue, the title shows `你好`, no encoding error.

**Comment by rogerwang** [comment]
close as it looks ok. reopen if there are further information.
