### ISSUE TITLE
:hover state not releases after window .hide()

### ISSUE THREAD

**Issue by xobotyi** [nwjs/nw.js#5896]
I have a button, it hides the window and have some css `:hover` styles. After the button pressed, callback performs `window.hide()` and `window.blur()` for sure. 
But, when I reopen hidden window (`window.show()` + `window.focus()`), button looks like it's hovered. Even if i'll hover other buttons - they look like hovered, but "stucked" button still looks like hovered. Hovered state releases only if i'll click window anywhere...

BTW window is frameless.

**Comment by xobotyi** [comment]
The only way i've found - to do `window.reload()` instead of `window.show()`

**Comment by xobotyi** [comment]
One more thing - it's only happening if elemnt have `tabindex` attribute..

**Comment by Christywl** [comment]
@xobotyi , could you please upload your sample to reproduce this issue?

**Comment by xobotyi** [comment]
@Christywl okay, this is not a bug of nw.js..
Bacause of `tabindex` element focuses even after clicking on it. And after hide and show all states are saved.

Issue can be closed/deleted
