### ISSUE TITLE
What is the best way to improve performance on a Click Through window 

### ISSUE THREAD

**Issue by cecilpeng** [nwjs/nw.js#5897]
In my application, I achieved an always-on-top float window. The feature of Click Through simplified my work (change the alpha of body = change the size of the window). And now, I need an sketchpad to run on it. The problem is that the line can not be draw smoothly. I think the core is the command line `--disable-gpu --force-cpu-draw`. Then, I'm confused that what is the best way to resolve it.
Maybe:
1. give up the feature of Click Through, however, I'm worried that it may display a gray border when resizing the window frequently.
2. run an another nwapp through the command line `--user-data-dir`.
3. need your help

**Comment by rogerwang** [comment]
CC @jtg-gg

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
