### ISSUE TITLE
Process remains in memory (windows)

### ISSUE THREAD

**Issue by TatriX** [nwjs/nw.js#5899]
I have a quite big game which use nwjs for distribution https://github.com/TatriX/rogalia/
Most of my users complain that after quiting the game it remains in the memory.
Here's what I'm using to handle quit:
```js
// "Quit" button handler
 const gui = require("nw.gui");
 gui.App.quit();
```
and
```js
var gui = require("nw.gui");
var win = gui.Window.get();
win.on("close", () => {
    // hack to fix nw.js bug
    // see https://github.com/nwjs/nw.js/issues/2087
    if (window) {
        this.save();
    }
    win.close(true);
});
```
Unfortunately I can't make a small reproducible example. Also I think I don't experience this issue on linux.

**Comment by rogerwang** [comment]
Do you reproduce this on your side? And what's the version are you using? It should be helpful to find what's the last good version.

**Comment by TatriX** [comment]
I think the problem is with steam, not nwjs, so I'll close this. Thanks.
