### ISSUE TITLE
authentication problems (dialog crashes etc)

### ISSUE THREAD

**Issue by matthiasg** [nwjs/nw.js#590]
we are having some problems with using node-webkit and web servers requiring authentication.

First of all node-webkit does not seem to support Integrated Authentication (Negotiate,Kerberos,Windows Authentication) which at least Google Chrome does (i would hope thats part of Chromium though).

It pops up an authentication dialog instead. This means i cannot use it transparently to develop line of business apps.

Now thats not good but the dialog that pops up is worse :)

First of all it CRASHES when i cancel the authentication dialog. It should show a simple Access Denied or redirect to the previous location instead.

Then it does not allow TAB which means i cannot just type my username and then TAB to the password field, i actually have to click it. Same for closing the dialog which does not support RETURN/ENTER.

Second of all when i disable Basic Authentication on the Server, but leave NTLM ON, which means node-webkit gets an www-authenticate header but with only and it still pops up the dialog.

Also after pressing ok it crashes quite often, sometimes it works sometimes it does not.

At the very least it should be possible via a html or node callback to be notified of an 401 before it is handled and abort it.

Did anyone have any success with using node-webkit against authenticated server ? Other than O-Auth etc...

**Comment by coreybutler** [comment]
Seems to be crashing again on 0.12.

**Comment by tomlandia** [comment]
Yeah because [they removed --auth-schemes flag](https://code.google.com/p/chromium/issues/detail?id=374951) and replaced it with a policy setting

**Comment by hermesdj** [comment]
Hello, I am having the same issue and i do not understand how i can modify the policy settings to prevent chromium to show the authentication popup. 
What am i missing ?

**Comment by maxfarseer** [comment]
Any good news ? 
Crashing on OS X 10.11 and node-webkit 0.12
