### ISSUE TITLE
How to enable the chrome://profiler page?

### ISSUE THREAD

**Issue by xingyuzhe** [nwjs/nw.js#5900]
version: 0.21.2-sdk
OS: MAC

I  want open url like 'chrome://tracing, chrome://profiler' in my app like real chrome does. but i finally can not figure it out.
I've read all the ducument in [http://peter.sh/experiments/chromium-command-line-switches/](http://peter.sh/experiments/chromium-command-line-switches/) and  [https://developer.chrome.com/extensions/api_index](https://developer.chrome.com/extensions/api_index), i found '--enable-navigation-tracing' work with url 'chrome://tracing', but no switche for 'chrome://profiler' found. Anyone known something about this?

**Comment by rogerwang** [comment]
Use `--url=chrome://tracing` and please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
