### ISSUE TITLE
nw.Window.open('chrome://profiler') not work

### ISSUE THREAD

**Issue by xingyuzhe** [nwjs/nw.js#5901]
version: 0.21.2-sdk
OS: MAC

as you see below, 'nw.Window.open('chrome://tracing')'  work well but 'nw.Window.open('chrome://profiler')' not.  

![111](https://cloud.githubusercontent.com/assets/3498363/25733091/6e111640-3188-11e7-8b1e-010bf9252878.png)
![222](https://cloud.githubusercontent.com/assets/3498363/25733093/70848196-3188-11e7-88fb-cd11c6d9e843.png)

**Comment by rogerwang** [comment]
Should be a bug, will fix it soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/05-05-2017/nw22-864c4f9-5e7b9cd-7800964-ebc7761/v0.22.2/
