### ISSUE TITLE
How to set the pdf_path of win.print()?

### ISSUE THREAD

**Issue by tangyue0924** [nwjs/nw.js#5903]
- 1. Using NW.js version 0.21.6
- 2. Windows 7 with latest drivers

Just want to know how to set this attribute.

```
let printFile = {
       autoprint: true,
       mediaSize: {'name': 'CUSTOM', 'width_microns': 215900, 'height_microns': 299400, 'custom_display_name':'Voucher', 'is_default': true},
	marginsType: 0,
	marginsCustom: {"marginBottom":0,"marginLeft":10,"marginRight":10,"marginTop": 0},
	headerFooterEnabled : false,
	landscape: false,
	shouldPrintBackgrounds: false,
	copies: 0,
	headerString: '',
	footerString: '',
	printer: '',
        pdf_path = path.dirname(process.execPath);
}
```
After this, I cannot find the PDF file anywhere. Could you tell me how to set `pdf_path` ?
Thanks!

**Comment by rogerwang** [comment]
the path should be a filename, not a dir name. 
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
