### ISSUE TITLE
Disable "save as" dialog

### ISSUE THREAD

**Issue by mi-k4** [nwjs/nw.js#5904]
State which version are you using : 0.22.1
* State which OS version are you running with: Debian

Hello, I wish to use nwjs in kiosk and i would like to know if it is possible to download a file without the modal "save as" display when i download a file.

![capture du 2017-05-08 12-51-23](https://cloud.githubusercontent.com/assets/3338681/25801346/7259561a-33ed-11e7-98d5-e9a54d453a3a.png)

Thanks very much

mi-k4

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by mi-k4** [comment]
thank you
