### ISSUE TITLE
nwjs is not accessing environment variables when launched using sudo in linux and mac (nwjs 14.7)

### ISSUE THREAD

**Issue by basavarajburge** [nwjs/nw.js#5905]
I am trying to read environment variables in nwjs, found 2 issues when we launching with sudo and without sudo.

1) When we launch nwjs using sudo environment variables are not accessible
2) It maintains 2 different Local storage, when we launch using sudo it gives different local storage data  and when we are launching without sudo it gives different local storage data 

Note: When launch nwjs without sudo i am getting all the environment variables
I am getting this issue in nwjs 14.7

Is this is issue with nwjs 14.7, or any other configuration i am missing?

**Comment by Christywl** [comment]
I try `process.env` on Linux with nwjs-sdk-v0.22.2. The returned env variables are different with or without `sudo`. I also try `process.env` with node, the returned variables are also different. @rogerwang , please help confirm.

**Comment by basavarajburge** [comment]
Yes even I have verified issue in linux also, same behavior with nodewebkit and node.
@rogerwang is there any workaround or change in configuration is available?
And also please look in to the Local storage issue with sudo and non-sudo

Thanks in Advance

**Comment by Christywl** [comment]
@basavarajburge , how do I check the Local storage issue? Could you please share a sample or steps?

**Comment by basavarajburge** [comment]
@Christywl LocalStorage issue is happening only in mac not in linux
you can test it as follows
1) Launch nwjs using sudo 
2) Open Web inspector (Right click Inspect element)
3) Go to console 
4) window.localStorage ( it will show all existing local storage data)
5) you can add data like window.localStorage.test = "Test  data"
6) Then close the nwjs and relaunch it without sudo
7) Again open web inspector and go to console
8) Now try window.localStorage it will not show window.localStorage.test which was added using sudo

even if we do vice versa same issue can seen.

**Comment by Christywl** [comment]
@basavarajburge , I see the different local storage with or without `sudo`.

**Comment by hujiajie** [comment]
I think that's the expected behavior. `sudo` resets your environment variables by default. See https://wiki.archlinux.org/index.php/sudo#Environment_variables for an example of preserving certain environment variables.
