### ISSUE TITLE
nwjs14.7 lib, nw and locales has 700 file permission due to that, it is not able launch using sudo in linux

### ISSUE THREAD

**Issue by basavarajburge** [nwjs/nw.js#5907]
My application is using nwjs 14.7 version. I found out that it is not launching in Linux with sudo (sudo ./nw)
Later if found out that that is because of lib, nw and locales have 700 permission and to launch nwjs using sudo these files need 755 permission.

below is the permission of nwjs14.7
-rw------- 1 user user  1339286 Jul 22  2016 credits.html
-rw------- 1 user user 10209568 Jul 22  2016 icudtl.dat
drwx------ 2 user user     4096 Jul 22  2016 lib
drwx------ 2 user user     4096 Apr 14  2016 locales
-rw------- 1 user user   408051 Jul 22  2016 natives_blob.bin
-rwx------ 1 user user   842920 Jul 22  2016 nw
-rw------- 1 user user   661275 Jul 22  2016 nw_100_percent.pak
-rw------- 1 user user  7609849 Jul 22  2016 resources.pak
-rw------- 1 user user  628140 Jul 22  2016 snapshot_blob.bin

And same thing when i tried with nwjs 22.3 which has permision as follows
-rw-r--r-- 1 user user  1867617 May 10 08:57 credits.html
-rw-r--r-- 1 user user 10130560 May 10 08:57 icudtl.dat
drwxr-xr-x 2 user user     4096 May 10 08:57 lib
drwxr-xr-x 2 user user     4096 Jan 11 14:52 locales
-rw-r--r-- 1 user user   262947 May 10 08:57 natives_blob.bin
-rwxr-xr-x 1 user user     6360 May 10 08:57 nw
-rw-r--r-- 1 user user   511673 May 10 08:57 nw_100_percent.pak
-rw-r--r-- 1 user user   804216 May 10 08:57 nw_200_percent.pak
-rw-r--r-- 1 user user  6140018 May 10 08:57 resources.pak
-rw-r--r-- 1 user user  1448208 May 10 08:57 snapshot_blob.bin

nwjs is able to launch using sudo without any issue

Is there any specific reason nwjs14.7 has 700 file permission?
Is there any other way to launch nwjs14.7 using sudo - without changing file permission to 755?

**Comment by sourceskyboxer** [comment]
Need chmod -R 777 /nw.app/Contents/*
Or check [StackOverFlow
](http://stackoverflow.com/questions/8328481/chmod-777-to-a-folder-and-all-contents)
