### ISSUE TITLE
want to know can i use nwjs setup to host my localhost node server into that. 

### ISSUE THREAD

**Issue by ShankzPatil** [nwjs/nw.js#5909]
I want to know, can i use nwjs setup to host my localhost node server into that so i can interact with my webpage using localhost url.

as my existing project i made self hosted WCF service in Windows service with localhost:9001 and that am using in angular to sign something and send to server.

i need equivalent in node js using nwjs.

please revert.

**Comment by elBarkey** [comment]
Probably you need to read the wiki/docs.
https://github.com/nwjs/nw.js/wiki/About-Node.js-server-side-script-in-nw.js

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
