### ISSUE TITLE
HTTPS decrypt performance issue

### ISSUE THREAD

**Issue by amon0915** [nwjs/nw.js#5910]
version: 0.12.3(32bit) and 0.18.4(32bit), both tried.
OS: win7 64bit
hardware: Xeon E5-2690 v2 3.00Ghz; 12GB mem;
example code: 
```
<!DOCTYPE html>
<html>
<head>
  <title>My OS Platform</title>
</head>
<body>
<button onclick="sendRequest()">send</button>
<script>
// get the system platform using node.js
 function sendRequest(){
     setInterval(function(){
        process();
     }, 10);
}
function process(){
     var http = require('https');
     var options = {
        hostname: '127.0.0.1',
        rejectUnauthorized:false,
        port: 443,
        path: '/',
        method: 'GET'
    };
    var req = http.request(options, function(res)  {
        res.on('data', function(d) {

        });
    });
    req.end();
    req.on('error', function(e) {
        console.error(e);
    });
}
</script>
</body>
</html>
```
my program is built for AWS S3 client, when I downloading Object with S3 interface in https, the transport speed reacch 15M/s and nw process cost CPU about 25% stablely, but the UI is almost cannot reply anything, does nw can't use multi core cpu performance?

TLS negotiation solution is: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

**Comment by rogerwang** [comment]
This may be expected since you are doing intensive tasks in the same thread
with UI. Consider using Web worker for this and we have Node.js support in
it.

**Comment by amon0915** [comment]
thanks for replay. Web worker is a better choice for UI.
We put the UI aside, why the https could cost 100% single CPU core while the transmisstion is not much fast(15M/s)?  
from the CPU Figure flame, I can see that idle and program cost much more CPU time, I think it was doing something about encryption/decryptyion.
Is this a common appearance that performance of encryption/decryptyion is inefficient in node.js ?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
