### ISSUE TITLE
I want show custom system notifications when moving the mouse over the tray icon,How to achieve it? 

### ISSUE THREAD

**Issue by amhoho** [nwjs/nw.js#5914]
![image](https://raw.githubusercontent.com/amhoho/Nwjs-cn-docs/master/demo/img/00.png)

1. mouse over the tray icon

2.show custom system notifications (But i do not think this is a frameless transparent window)

thank you!

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
