### ISSUE TITLE
Go back from an iframe page making win.realod not work.

### ISSUE THREAD

**Issue by lili21** [nwjs/nw.js#5915]
* State which version are you using
   **nw.js 0.14.7-sdk**
* State which OS version are you running with
   **macOS Sierra 10.12.4**
* Provide a reproducible case if possible
  [nwjs-issue](https://github.com/lili21/nwjs-issue)
  
* Reproduce step

  1. open devtools
  2. visit index, right click the page, click the `Reload` on the popup menu
  3. visit iframe, right click the page, click the `Reload` on the popup menu
  4. go back to index, right click the page, click the `Reload` on the popup menu, **Error**

**Comment by Christywl** [comment]
I can't run your codes and steps in https://github.com/lili21/nwjs-issue. There are some errors.

So, I remove `nw` dependency in `package.json` and use my local nw binary(`nwjs-sdk-v0.22.3-osx-x64.zip`). Seem the **first** `Reload `**doesn't work** in index page.  Please try the newer nwjs build in your side.

**Comment by lili21** [comment]
I can't use newer nwjs build, because my application need to support Windows XP system.

**Comment by lili21** [comment]
Could you be more specific about
> There are some errors

Cause I just ran the code, and everything work as expect.

**Comment by lili21** [comment]
@Christywl

**Comment by Christywl** [comment]
As the steps in https://github.com/lili21/nwjs-issue, `npm run dev` works fine, but when I run `npm start`, some errors occur:
```
$cd nwjs-issue

$npm start

> nw-issue@1.0.0 start /Users/WebQA/Desktop/nwjs/bugs/5915/nwjs-issue
> nw .

nw.js appears to have failed to download and extract. Attempting to download and extract again...
module.js:339
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/WebQA/Desktop/nwjs/bugs/5915/nwjs-issue/node_modules/nw/scripts/install.js:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/WebQA/Desktop/nwjs/bugs/5915/nwjs-issue/node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! nw-issue@1.0.0 start: `nw .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw-issue@1.0.0 start script 'nw .'.
npm ERR! This is most likely a problem with the nw-issue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nw .
```

**Comment by lili21** [comment]
@Christywl It looks like a issue to [npm-installer](https://github.com/nwjs/npm-installer).
Have you installed `nw.js` as global package ?

**Comment by lili21** [comment]
@rogerwang
