### ISSUE TITLE
Text injection can be used in phishing 404 page and should not include attacker text

### ISSUE THREAD

**Issue by Sajibekanti** [nwjs/nw.js#5916]
Hi 
Team 

Issue: Text injection can be used in phishing 404 page and should not include attacker text

i want to report a text injection and a Miss Configuration of the 404 page which can be used in phishing

the bug exists at :
https://nwjs.io/img/It%20has%20been%20changed%20by%20a%20new%20one%20https://www.hackerone.com%20so%20go%20to%20the%20new%20one%20since%20this%20one%20was%20not%20found%20on%20this%20server.

As you can see attacker text is included 
"It has been changed by a new one https://www.hackerone.com so go to the new one since this one was not found on this server."

Fix : just use a 404 page that don't include attacker text just as : hackerone do (a 404 page that don't include any external text

Raferance : https://www.owasp.org/index.php/Content_Spoofing

Hope you fix it

Thanks,
Sajibe kanti

**Comment by Christywl** [comment]
@Sajibekanti , could you please provide a sample which ready to run and reproduce this issue?

**Comment by Sajibekanti** [comment]
You should Read full my Report all are have in here

**Comment by rogerwang** [comment]
The issue should be reported to the website repo so that users would not confuse it with bug in NW.js runtime.

**Comment by Sajibekanti** [comment]
Yes i report for web , so can you forward it Web Engineer
