### ISSUE TITLE
Cannot require 'https' module in Web Worker

### ISSUE THREAD

**Issue by binamtech** [nwjs/nw.js#5918]
Trying to use 'https' module in Web Worker causes error: 
...
message: "Uncaught Error: No such module: js_stream",
filename: "_stream_wrap.js"
...

`const https = require('https');`

Environment:
- NW.js: v0.22.3 sdk;
- platform: Mac OSX (x64) Sierra.

**Comment by kailniris** [comment]
Did you enable node worker command line option?
http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-enable-node-worker

**Comment by binamtech** [comment]
Yes. Here is my "command line option":
"chromium-args": "--enable-gcm --enable-node-worker"

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.22.3.
![image](https://cloud.githubusercontent.com/assets/20039821/26229579/6c6f39f0-3c75-11e7-9877-5e3d468f3a33.png)
package.json:
```
{
  "name": "test",
  "main": "index.html",
  "chromium-args": "--enable-gcm --enable-node-worker"
}
```
index.html:
```
<script>
var worker = new Worker('task.js');
console.log(worker);
</script>

```
task.js(using the example in https://nodejs.org/api/https.html):
```
const https = require('https');
const fs = require('fs');

const options = {
  pfx: fs.readFileSync('test/fixtures/test_cert.pfx'),
  passphrase: 'sample'
};

https.createServer(options, (req, res) => {
  res.writeHead(200);
  res.end('hello world\n');
}).listen(8000);
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
please try this build: https://dl.nwjs.io/live-build/05-19-2017/nw22-772064c-90fd209-2d0e985-5b5a0ad/v0.22.4/

**Comment by binamtech** [comment]
Great! It works.
Thank you for the hotfix.
