### ISSUE TITLE
运行例子时意外退出

### ISSUE THREAD

**Issue by BigEagleWY** [nwjs/nw.js#5919]
通过npm安装的nw模块，安装完成之后按照文档的教程做了一个最基本的demo，然后每次通过命令行运行时都会弹出窗口提示nw意外退出

![ac976385-2d50-42fa-9df9-2a532da13879](https://cloud.githubusercontent.com/assets/20693687/26195281/cf58b2b8-3bed-11e7-820b-9d01d057cdbc.png)

**Comment by sourceskyboxer** [comment]
Please write English! Other understand you.

**Comment by Christywl** [comment]
Please use English so all users can read, or the issue will be closed directly.

**Comment by maicoder** [comment]
please use nw@0.21 ,
`npm install -g nw@0.21`
