### ISSUE TITLE
"chromium-args" : "--start-maximized" didn't work 

### ISSUE THREAD

**Issue by Fanjh2016** [nwjs/nw.js#5920]
i just do as the dom says,
 however ,it didn't work, same as 'node-main' and 'inject-js-end'.
use  nwjs-sdk-v0.19.2-win-ia32, and  my os is win7 -64 .
or there is something wrong with my package.json? 
????????????????????
{
  "name": "demo",
  "main": "localhost:8088/demo",
  "node-remote": "https://localhost:8088/demo",
  "chromium-args" : "--start-maximized",
  "window": {
    "title": "DEMO",
    "position": "center",
    "width": 1920,
    "height": 1080,
    "toolbar": true,
    "frame": true,
    "min_width": 1060,
    "min_height": 600
  },
  "nodejs": true
}

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.22.3. The app isn't opened in the maximized mode when setting "chromium-args" : "--start-maximized".

**Comment by fujunwei** [comment]
Can i take this issue?

**Comment by rogerwang** [comment]
@fujunwei no. This will be fixed after #5875

**Comment by rogerwang** [comment]
merge with #5875
