### ISSUE TITLE
Each startup will take about 1 to 2 seconds slow

### ISSUE THREAD

**Issue by xiongwenjun** [nwjs/nw.js#5921]
When hook up the IE LAN settings - auto detect settings, each time you start, it will be 1 to 2 seconds slow 。Slow time is primarily the response of the first waiting address .
use nwjs-sdk-0.12.2-win-ia32(or nwjs-sdk-v0.8.4-win-ia32), and my os is win7 -32 .

![1](https://cloud.githubusercontent.com/assets/28843429/26285760/5ea9839c-3e88-11e7-8c09-ca64707883ba.jpg)

**Comment by Christywl** [comment]
How do I check this with nwjs? Could you please share more info, the steps , codes or cmd?

**Comment by xiongwenjun** [comment]
index.html:
<!DOCTYPE html>
<html>
<head>
<title>test</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0,maximum-scale=1.0, user-scalable=no">
<script type="text/javascript" src="server.js"></script>
<style>
.loading-style {}
</style>
</head>
<body class="loading-style">
</body>
<script type="text/javascript">
  try {
     var gui;
     if (typeof require != 'undefined' && (gui = require('nw.gui'))) {
     	 console.log(gui.App.argv);
       window.location.href = "http://www.baidu.com";
     }
  }catch(e){
  }
</script>
</html>


package.json:
{
	"name": "Collaboration Creative",
	"version": "2.3.0",
	"patch": "0.0.1",
	"main": "index.html",
	"node-remote" : "*",
	"single-instance" : true,
	"chromium-args" : "--enable-file-cookies --load-plugin=plugins\\Screenshot.dll",
	"webkit":{
		"page-cache": true,
		"plugin": true
	},
	"window": {
    	"show": true,
    	"toolbar": true,
    	"frame": true,
        "resizable": true,
    	"position": "center",
    	"width": 1100,
    	"height": 620,
    	"min_width": 896,
    	"min_height": 560,
		"icon": "icons/logo.png"
	}
}

slow:

**Comment by Christywl** [comment]
I try on Windows 8 with nwjs-sdk-v0.22.3. It quickly goes to Baidu page after it loads the main page. Do your mean Baidu page start time is slow?

**Comment by xiongwenjun** [comment]
no, Any web page will be slower。But，I found IE8 under win7 is normal。I want to know what version you're using ie 。

**Comment by Christywl** [comment]
IE11
You mean the start time you open the web page directly in IE is quick than nwjs?
I think this is not related to LAN settings and there is a little difference. In your nwjs app, it loads the main page firstly and then loads the web page, not directly open the web page. So IMO, this is a normal result, not a issue. 
@rogerwang , could you please help confirm?

**Comment by Christywl** [comment]
@rogerwang , could you please confirm this?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please try other platforms, such as win64?  It works fine for me on Windows 8.1 64bit(I don't have win32 device).

**Comment by Christywl** [comment]
close until there is more information
