### ISSUE TITLE
Does nwjs still support transparency?

### ISSUE THREAD

**Issue by genesix-eu** [nwjs/nw.js#5923]
I can't make window transparent using nwjs 0.22.3 nor 0.23.0 on  Windows 10.
On older version (0.12.3) it is working.

Is this feature still supported?

https://github.com/nwjs/nw.js/wiki/Transparency

 label:question

**Comment by genesix-eu** [comment]
On v 0.15.4 it is also working

**Comment by Christywl** [comment]
It works well for me on Windows 10 with nwjs-sdk-v0.22.3. 
```
{
    "name": "test",
    "main": "index.html",
	"window": {
	  "frame": false,
	  "transparent": true
	}
}
```
See http://docs.nwjs.io/en/latest/For%20Users/Advanced/Transparent%20Window/.

Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
