### ISSUE TITLE
How to set the width of NW Window equals the width of Screen?

### ISSUE THREAD

**Issue by tangyue0924** [nwjs/nw.js#5927]
NW-version: 0.21.6
OS: Windows & Mac

I need to set the NW width 100% if the width of screen less than 1366.
But I couldn't get the Window Object.
Need your help!
THX!!

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by sadikyalcin** [comment]
You can do this when you create the window;

```
// if(screen.width < 1366....)

nw.Window.open(url, {
  id: windowid,
  position: 'center',
  width: Math.round(screen.width * .75),
  height: Math.round(screen.height * .75)
},
```

Or on launch via background.js

```
chrome.app.window.create(
    'index.html',
    {
      id: 'myid',
      bounds: {
        width: width,
        height: height,
        left: Math.round((screenWidth-width)/2),
        top: Math.round((screenHeight-height)/2)
      },
      innerBounds: {
        minWidth: 300,
        minHeight: 300
      }
    }
```

Or while the app is open...

[var mywindow = chrome.app.window.get('mainWindow');
mywindow.innerBounds.height = height;
mywindow.innerBounds.width = width;](url)

**Comment by rogerwang** [comment]
@sadikyalcin thanks for the answer.

**Comment by narek-king** [comment]
If still someone needs more detailed answer: another example.
in manifest i.e. package.json specify `"main": "main.js"`
And in main.js 
`
  if (typeof nw !== 'undefined') {
    nw.Window.open('index.html', {
      show: false
      },
      function(win) {
      win.maximize();
      win.focus();
      win.show();
    });
  }
`

This will open hidden window, maximize it then make it visible.
