### ISSUE TITLE
Chrome extension popup and event "chrome.browserAction.onClicked.addListener"

### ISSUE THREAD

**Issue by firebbs** [nwjs/nw.js#5929]
In chrome browser you have possibility to comunicate with extensions using popup window (browser_actions -> default_popup in manifest file) and event "_chrome.browserAction.onClicked.addListener_" (on click icon of extension). 
Is it possible to fire event _chrome.browserAction.onClicked.addListener_ using NW.JS? or maybe have possibility to show popup somehow (e.g. in new window)?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
