### ISSUE TITLE
Multiple NW.js apps on one system but only one nw.dll.

### ISSUE THREAD

**Issue by haschu** [nwjs/nw.js#5930]
I'm curious if it's possible to run multiple NW.js apps on one system but only distribute the NW.js library once. 

For example if you have three different apps which you want to distribute to one windows machine, you basically have to ship `nw.dll` (3x 97,6 MB) three times - or am I wrong?
Is it somehow possible to ship `nw.dll` just once? Same goes for the NW.js libraries for Mac and Linux.

Btw. thank you for the great work on NW.js and especially the nwjc compiler.
Bringing real source code protection to the Node world is amazing!

**Comment by rogerwang** [comment]
Yes it's possible. Please discuss in our mailing list.
https://groups.google.com/forum/#!forum/nwjs-general

**Comment by haschu** [comment]
Thanks. You can find die thread [here](https://groups.google.com/forum/#!topic/nwjs-general/6fbFbqr1egc).
