### ISSUE TITLE
Determine if app was killed on Windows via taskmanager or system shutdown

### ISSUE THREAD

**Issue by xobotyi** [nwjs/nw.js#5933]
I need to do some cleaning stuff before my app will be closed, but nothing helps. Neither `process.on('exit')` nor `process.on('SUGHUP')` nor anythig else, because node doesn't provide any signals on windows =(
Have found some solutions but it uses tty, but we have no tty in nw...

maybe someone have working soluton?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
