### ISSUE TITLE
How to set nwjs Window always in background in kiosk mode

### ISSUE THREAD

**Issue by sandeepks1** [nwjs/nw.js#5937]
I am running an NW js application in kiosk mode,and i am giving option to launch native windows desktop apps from it, Issue:- After i am launching the child application ,if i click any where in the body of nw js application,the child application window is going background of nwjs window,

Looking for: How to set NWjs window always in background ,if child window opens it should be in foreground until it minimize,

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
