### ISSUE TITLE
How to send RESTful request to the back-end implemented in Java from fron-end implemented in NW.js?

### ISSUE THREAD

**Issue by angela-fan** [nwjs/nw.js#5938]
Hi,
I have a web application whose front-end is implemented in extjs and back-end is implemented in java. The web application can run successfully when deployed both front-end and back-end in Tomcat.
Now, i want to change it into standalone desktop app.
What i did is as below:
1. Save as all the front-end resource to local host and wrapped them in NW.js
2. Deploy back-end part still in tomcat which is local

Now the issue i got is:
When front-end called in NW.js send RESTful request to back-end, the url is changed into "chrome-extension://pedkhegghbakdeaeelkjnajoobkpibbd/sso/auth". The correct one should be "http://localhost:8080/sso/auth"

Am i using NW.js in  a wrong way?

The version i am using is nwjs-sdk-v0.22.3-win-ia32.
The OS version is window 7 32 bit.

Thanks

**Comment by angela-fan** [comment]
The index.html is:

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>KMS - Non LDAP login</title>
<link rel="stylesheet" type="text/css" href="resources/css/honidlogin.css">
<style type="text/css">
.input {width:200px}
.label {width:200px}
.heading {padding:5px; margin:0px; background:#F5F5F5; color:white; display:block; width:290px}
html, body { margin: 0; padding: 0; font: 14px arial, verdana, helvetica, sans-serif; background:#F5F5F5}
input {width:200px}
.error, .center { }
.error{padding:5px;color:red;background:white;margin-top:5px;}
.form { margin-right: auto; margin-left: auto;  background:#587593; padding:5px;width:331px; margin-top:100px}
.inner{margin-top:0px;}
table,form{margin:0px;padding:0px}
</style>
</head>
<body>
	<div class="form">
		<div class="center">
			<form action="auth" method="post">
				<table cellspacing="0" cellpadding="1" border="0"
					class="loginborder">
					<tbody>
						<tr>
							<td>
								<table width="100%" cellspacing="0" cellpadding="3" border="0"
									class="login">
									<tbody>
										<tr class="loginbg">
											<td class="dialogtextwhiteb">Sign In</td>
											<td align="right"></td>
										</tr>
										<tr>
											<td align="right" class="dialogtextb">User ID:</td>
											<td><input type="text" tabindex="1"
												class="formtextfield" maxlength="64" name="user"></td>
										</tr>
										<tr>
											<td align="right" class="dialogtextb">Password:</td>
											<td><input type="password" tabindex="2"
												class="formtextfield" maxlength="56" name="password"></td>
										</tr>

										<tr>
											<td></td>
											<td><input type="submit" class="buttonlink"
												value="Sign In" name="honidsubmit" tabindex="4"></td>
										</tr>
									</tbody>
								</table>
								<table width="100%" cellspacing="0" cellpadding="0" border="0">
									<tbody>
										<tr class="spacer">
											<td colspan="2"></td>
										</tr>
									</tbody>
								</table>
								<table width="100%" cellspacing="0" cellpadding="3" border="0">
									<tbody>
										<tr class="loginaddonbg">
											<td class="dialogtext" colspan="2">
												Don't have a User ID? <a href="register">register</a></td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</form>
		</div>
		
	</div>
</body>
</html>


The package.json is:
{
  "name": "demo",
  "main": "index.html"
}

**Comment by Christywl** [comment]
I try your codes on Windows with nwjs-sdk-v0.22.3. 
Open the app:
![image](https://cloud.githubusercontent.com/assets/20039821/26661807/990f747e-46b2-11e7-8df9-0beab0dbf080.png)
Click 'Sign In', nothing happens.
Click 'register', the page changes and the url is `chrome-extension://ckjhfbgmdfelgiieimnlnipfekccgkak/register`:
![image](https://cloud.githubusercontent.com/assets/20039821/26661828/a52c1f14-46b2-11e7-8520-9aaa0b09dea8.png)
Do you mean this url is not correct?

**Comment by angela-fan** [comment]
Kind of this. The correct url should be http://localhost:8080/register. Is there any way that NW.js can change the url automatically? There are too many urls in my application. so i don't want to change it manually.

Thank you very much for your reply.

**Comment by Z3TA** [comment]
You have to use the full URL, including the protocol part!

For the a-elements you can make a script that adds http://localhost:8080/ before the REST endpoint to each element's href.

**Comment by angela-fan** [comment]
Thank you. Z3TA.
There are many html files in my application and many request URL. if i want to adds  http://localhost:8080/ to all of them automatically, how can i make the script? 
I am  fresh for nw.js. thank you.

**Comment by Christywl** [comment]
@rogerwang , could you please take a look at this?
