### ISSUE TITLE
Is there any way to implement Magic link like Slack?

### ISSUE THREAD

**Issue by varshneyjayant** [nwjs/nw.js#5940]
We want to invoke the app from the browser. Is there any way to implement Slack like link which can invoke app from browser?

**Comment by Z3TA** [comment]
You could try having a http socket open, hide the nw.js window and then show it again when you get a request on the http socket. For example <a href="http://localhost:8080/show">

**Comment by varshneyjayant** [comment]
In my case, app is not launched yet so need to start the process.

**Comment by bambooCZ** [comment]
I'd approach this with custom protocol. You will have to register your app as system handler for protocol ex. `varshneyjayant`. So your magic URL would be `varshneyjayant:show`, `varshneyjayant:hide`, `varshneyjayant:open%3Ahttps%3A%2F%2Fnwjs.io` (url encoded open:https://nwjs.io), etc..

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
