### ISSUE TITLE
Can we 'Dock' DevTools in main window?

### ISSUE THREAD

**Issue by jochemstoel** [nwjs/nw.js#5941]
I was not able to find a way to do this anywhere.  Both Chrome and Electron do not open DevTools in a separate window but dock them to the side. Can NW do this too?
![2017-05-31_17h43_33](https://cloud.githubusercontent.com/assets/4212360/26640775/f80190dc-4628-11e7-9154-ee9b313c8b41.png)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
Yes. you can put devtools in a webview.
