### ISSUE TITLE
nwjs0.14.7 can't get session 

### ISSUE THREAD

**Issue by aidetanxi** [nwjs/nw.js#5942]
The devtools show nothing in the Session Storage,but the browser has recorded the info of the user. The user‘s info will lose when the devtools is closed. I guess that the session is cleared as soon as i close the devtools。The nw-version is 0.14.7

**Comment by Christywl** [comment]
Is this reproduced on the latest nwjs build? And how do I check this?

**Comment by Christywl** [comment]
close until there is more information.
