### ISSUE TITLE
OSX - 0.23.0 with node 8 crashes on start using dblite node module

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5943]
OSX 10.11.6  El Capitan

Have attached a test sample - 0.23.0 using node 8.0.0-pre crashes on start. The database seems to be accessed OK but then a FATAL occurs.
0.23.0 with node 7.10.0 works fine as do all prior builds.
The dblite module is a wrapper for the system installed sqlite3 - I was using the sqlite3 npm module but the dblite dev says not supported - must be system installed executable.

nwjs 0.23.0 - node v 7.10.0
http://dl.nwjs.io/live-build/05-26-2017/nw23-b56aac2-03b9af7-4a0cadc-f041292/v0.23.0/nwjs-sdk-v0.23.0-osx-x64.zip

nwjs 0.23.0 - node v 8.0.0pre
http://dl.nwjs.io/live-build/06-01-2017/nw23-b56aac2-bda2584-10a09e1-6fcfd63/v0.23.0/nwjs-sdk-v0.23.0-osx-x64.zip

[crash0230withnode8.zip](https://github.com/nwjs/nw.js/files/1045183/crash0230withnode8.zip)

![dblite](https://cloud.githubusercontent.com/assets/11089335/26685934/65bb71aa-46e3-11e7-9877-ba69a6a7e86d.jpg)

**Comment by rogerwang** [comment]
Thanks for reporting. Does the module work well with upstream Node 8?

**Comment by Blatman** [comment]
Not sure - I have only ever used dblite in the nwjs environment.
Cheers.

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs nightly build v0.23.0(nodejs v0.8.0), crash happens. nwjs v0.23.0(nodejs v0.7.10.0) works well.

I also write a js file with some codes from the reporter's sample(use 'dblite' module).  Node v8.0.0 works well, no crash.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next build.

**Comment by rogerwang** [comment]
Please try this build: https://dl.nwjs.io/live-build/06-02-2017/nw23-b56aac2-bda2584-10a09e1-d3aaeb0/v0.23.0/

**Comment by Blatman** [comment]
Corker - works fine, thanks guys.
