### ISSUE TITLE
How do I customize the nwjs tray right-click menu?

### ISSUE THREAD

**Issue by ZeeRoc** [nwjs/nw.js#5946]
```
//add menu  
var menu = new gui.Menu();

menu.append(new gui.MenuItem({
    type: 'normal',
    label: 'show/hide',
    click: function() {
        if (isShowWindow) {
            win.hide();
            isShowWindow = false;
        } else {
            win.show();
            isShowWindow = true;
        }
    }
}));
tray.menu = menu;
```

This is part of the code I added to the menu, using the method provided by nwjs
[My app screen](https://i.stack.imgur.com/FXz5j.png)
[I expect the effect](https://i.stack.imgur.com/JNKJp.png)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
