### ISSUE TITLE
Where is the file named "nw.pak" in the nwjs-v0.22.3-win-ia32.zip?

### ISSUE THREAD

**Issue by 79257** [nwjs/nw.js#5954]
Where is the file named "nw.pak" in the nwjs-v0.22.3-win-ia32.zip?
I am going to  use Enigma Virtual Box

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
@Christywl is the file missing in our official ZIP? If no, we can close this issue.

**Comment by Christywl** [comment]
@rogerwang , I never see `nw.pak` in the nwjs unzip files, just see `nw_100_percent.pak` and `nw_200_percent.pak`.  Are they same?

**Comment by rogerwang** [comment]
Yeah. It was renamed to that starting from 0.13.
