### ISSUE TITLE
OSX - commit hash on nwjs splash screen incorrect

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5955]
Noticed the commit hash appears erroneous - appears to be happening since 0.21.6 at least.

eg: shows 2bad83e-ca7d50f-ef801be-ca7d50f
expected 2bad83e-ca7d50f-ef801be-1ac5823 or something.

![hasho](https://user-images.githubusercontent.com/11089335/26933202-c2aac846-4c5d-11e7-898d-1c0426058be1.jpg)

**Comment by rogerwang** [comment]
Thanks. The last segment refers to the version we used in the Node repo. I can confirm that the correct commit of Node is built, but the string used to show this information is generated incorrectly. Will fix this soon. And it's on Windows & Linux as well.
