### ISSUE TITLE
How to load extensions automatically in an extension?

### ISSUE THREAD

**Issue by azer** [nwjs/nw.js#5957]
Hi there,

We can load extensions by passing --load-extension to NW. It works for only development version, if we want to distribute an app that comes with an extension, it looks not possible. I tried changing CFBundleExecutable but it doesn't accept any parameters, also pointing to another script fails. 

Any workarounds or ideas ?

**Comment by rogerwang** [comment]
Does putting `--load-extension` in `chromium-args` in package.json work for you?

**Comment by azer** [comment]
@rogerwang I created an external script actually, it worked for me.

**Comment by codekiln** [comment]
For those that arrive here from google: `--load-extension` is actually a [Chromium command line argument](http://peter.sh/experiments/chromium-command-line-switches/), so you can put it in the `chromium-args` key of the manifest as so:

`"chromium-args": "--enable-logging=stderr --load-extension='./relative/path/to/ppbllmlcmhfnfflbkbinnhacecaankdh'"`. Somewhat surprisingly, I got this to work on Windows 7 with a relative path with forward slashes.
