### ISSUE TITLE
OSX - 0.24.0 beta1 SDK crash on start

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5961]
OSX 10.11.6 El Capitan

live-build/06-12-2017/nw24-0838f6b-5be0ec4-90cf6eb-5072877/v0.24.0-beta1/
osx-sdk build won't start - get abort trap 133 error - tried deleting old nwjs appdata folder to no avail.

**Comment by rogerwang** [comment]
Fix and available in https://dl.nwjs.io/live-build/06-12-2017/nw24-0974ab7-5be0ec4-90cf6eb-5072877/v0.24.0-beta1/

Thanks.
