### ISSUE TITLE
How can I use the Enigma Virtual Box for the v14 and V23 versions to package a separate executable file for exe?

### ISSUE THREAD

**Issue by 79257** [nwjs/nw.js#5963]
How can I use the Enigma Virtual Box for the v14 and V23 versions to package a separate executable file for exe?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by 79257** [comment]
How can I use the Enigma Virtual Box for the v14 and V23 versions to package a separate executable file for exe?
