### ISSUE TITLE
OSX - 0.23.2 will crash if using AppData produced by 0.24.0b1

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#5964]
Crash (trap 14) only occurs if later build (0.24.0b1) has been used. OK if appdata folder is deleted and then 0.23.2 is used. Normally there is a warning popup about using a later version of appdata folder but in this case a crash occurs instead.
User/Library/Application Support/nwjs/

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.24.0-beta1 and nwjs-sdk-v0.23.2.

**Comment by Christywl** [comment]
Crash also happens on Linux and Windows.

**Comment by rogerwang** [comment]
Switching the version back and forth is not supported by Chromium upstream. I'll see what we can do.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
