### ISSUE TITLE
capturePage and security

### ISSUE THREAD

**Issue by joeyhub** [nwjs/nw.js#5965]
There's an old closed issue about capturePage not working because node-remote needs to be set. This is still the case. While this is a workaround I don't understand how it is a solution as it breaks security.

A key point of something such as nwjs is that the main starting process is mean to have access to everything below it but not vice versa. It makes no sense to me that if in my opening index.html file I do something as simple as open a window as a child which should have no access to the parent and then try capture that window that I get an obscure error about an undefined variable because somehow despite that I am trying to operate on the child from a privileged context I can't.

If the workaround is to give the child privileged access then that is incompatible with the philosophy that nwjs should be following.

I might be wrong on the security but despite being marked as a documentation issue it's still not clear in the latest documentation what the security consequences are of adding a site to node-remote in the manifest. However as far as I can see in the documentation, the workaround turns the child window into a node frame which gives it full access to your system.

At the very least in the short run under node-remote say that this makes it a node frame then point to the security document. Next up is why from a parent context (unless callbacks can have context switched according to what they are called from), there's a degradation into the child scope to take a shot. Is this a difficulty linking chrome with node?

Please note my terminology can be mixed up. Where are contexts might be one thing (I think the global scope it starts with) and for security frames are another I tend to use the term context for both. As in for what your window object is and your security context (privileged, unprivileged). On that front can we be more precise with the explanations and terminologies? IE to openly say that a node frame is privileged where as another is not? I guess it can be confusing because you can have the node context in terms of global objects, etc but not the security privilege (some might work if they happen to be pure JS, others not if they for example try to access OS). Someone really needs to sort all of this out. We actually have 2 * 2 here.

    [new Browser(), new Node()] ✕ [new Privileged(), new Unprivileged()]

Where privileged can access parent as well as children even from differing origins (opposing extremes). Browser you wont get for example require in the global scope automatically. As for node, I'm not sure what browser has that is doesn't. I guess document :).

Even if node-remote can give the global scope with nw but not the privilege it's still not ideal (I won't even want my child context to know it's running in another global context, even if the security context is good such as being unprivileged). It's not just a security issue. I don't want to worry about the side effects of dropping weird stuff in a global scope like require which is also used by browser libs and some might chain as in if require in window put it to require_old in scope, try my require first then the one I found that I replaced. Unobtrusive for the win.

**Comment by rogerwang** [comment]
Hello, capturePage is an API that can be called only from [Node Frame](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/#node-and-normal-frames) 

It doesn't need `node-remote` to work.

**Comment by joeyhub** [comment]
I am calling it from a node frame. The issue was confirmed in the previous issue. In a node frame I create a window that isn't a node frame. Then from within the same node frame I call capturePage. It doesn't work. It is the same as the previous issue that was closed. The workaround is to make the window you created and are trying to call capture page on from the node frame a node frame as well.

Essentially right now you can only call capture page on a node frame from a node frame. It does need node remote to work. The issue was opened, acknowledged and then closed stating that making the child window node-remote is an acceptable work around.

I have a package.json that specifies an index.html file. Is that in a node frame or do I need to set nodejs true? Shouldn't it be that by default already? The documentation doesn't specify exactly what that applies to. Similarly there are things like fake top saying it also applies to subframes. Does that mean that subframes will all have a fake top of their own or that if they traverse their parents they will reach the same fake top?

Please try with...

{"name":"test","main":"index.html"}

Then...

Open a window to github, in the callback add an event for the Window.window load event, or just set a timeout, finally run capturePage on the Window.

**Comment by rogerwang** [comment]
Could you please submit a full sample? we'd like to fix it.

**Comment by Christywl** [comment]
close until there is more information.
