### ISSUE TITLE
window transparent not work on v0.23.2

### ISSUE THREAD

**Issue by yutent** [nwjs/nw.js#5973]
**OS:** Windows 10  x86
**NW:** 0.23.2
------------------

The same os, v0.22.3 works well.

**Comment by Christywl** [comment]
I can reproduce this issue on Windows with nwjs-sdk-v0.23.2. `window transparent` works fine on Linux.

**Comment by rogerwang** [comment]
@jtg-gg could you please help to see this?

**Comment by jtg-gg** [comment]
@rogerwang ok will look into this, may be next week
this week I'll be working on nw23 for OSX first

**Comment by rogerwang** [comment]
Thanks, and reassigning issue.

**Comment by jtg-gg** [comment]
I've made a pull request https://github.com/nwjs/chromium.src/pull/86
please also patch nw24

**Comment by xingyuzhe** [comment]
when will this fix be released? I think this is a serious bug.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
