### ISSUE TITLE
Add %chrome_ver or %chromium_ver to user-agent field in manifest

### ISSUE THREAD

**Issue by sean220** [nwjs/nw.js#5975]
To custom use-agent with chrome/chromium version, Add the relevant variable would be helpful .

**Comment by AshleyScirra** [comment]
This would be useful for us with Construct 2/Construct 3. Some of our code, and some of the libraries we depend on, do user-agent sniffing to determine what's supported. If Chrome/XX is not present in the user agent then these checks fail and then code that worked in Chrome no longer works in NW.js. This can be worked around by manually adding "(like Chrome/63 )" to the UA, but it would be nice if this auto-updated.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by AshleyScirra** [comment]
Great, thanks!
