### ISSUE TITLE
Broken link in the Wiki

### ISSUE THREAD

**Issue by Varunram** [nwjs/nw.js#5976]
<a href="https://github.com/nwjs/nw.js/wiki/Using-MP3-&-MP4-(H.264)-using-the--video--&--audio--tags#read-me">This</a> page in the wiki contains nothing (or was it intended to contain nothing?)

**Comment by rogerwang** [comment]
Here is the correct link:

https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.

**Comment by rogerwang** [comment]
Note the dot at the end.
