### ISSUE TITLE
Heap size don't take effect v0.23.3 SDK

### ISSUE THREAD

**Issue by Princbut** [nwjs/nw.js#5977]
I'm running NW.js 0.23.3 (SDK) in Windows 10 pro x64-bit (16GB RAM) when i set js flags "--max_old_space_size=4096" in package.json it don't take effect nw process close when memory usage reach 1.58GB

Thank

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this?

**Comment by Princbut** [comment]
js-flags is defined in package.json 
`  "js-flags": "--max_old_space_size=4096"
to fill memory i use this (test purpose only):

> var FILL = [];
for (var i = 0; i < 50000; i++) {
    for (var A = 0; A < 50000; A++) {
        FILL.push('RANDOM_BIG_STRING');
    }
}

![image](https://user-images.githubusercontent.com/935269/27320716-7a3ebf78-55a8-11e7-9d32-386d8ac6a6a7.png)

![heap](https://user-images.githubusercontent.com/935269/27320630-27302358-55a8-11e7-88dd-b1a85be1d792.gif)
Thank

**Comment by Christywl** [comment]
I run the above codes with nwjs-sdk-v0.23.3. The app crashed after a few seconds.

**Comment by Princbut** [comment]
Yes because the default heap of node js is full and i can't increase it with the following command line max_old_space_size if i run the code in Node JS console i get `JavaScript heap out of memory` with or without max_old_space_size
![image](https://user-images.githubusercontent.com/935269/27323011-196a4510-55b1-11e7-9a6f-f53b6c23bfbf.png)

**Comment by selim-g** [comment]
same issue here..

**Comment by rogerwang** [comment]
The is not hitting heap size limit, but the limit of array size. It failed here: https://github.com/nwjs/v8/blob/nw26/src/heap/heap.cc#L4227

If you think this is a bug. Please report it to upstream v8 project. Thanks.
