### ISSUE TITLE
node-webkit fails to start after signing

### ISSUE THREAD

**Issue by azer** [nwjs/nw.js#5978]
A simple node-webkit application fails to start after signing following the instructions existing in the wiki and also the new documentation.

Using both the old way (calling codesign) and the new way (calling build_mas.py) I'm unable to open my app after signing.  

I'm getting `[30493:36867:0620/051139.569236:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.` error. 

I can see the icon on the task bar, but the window is missing. Before signing, it works fine.

Googling this error doesn't return any helpful results. Any ideas how can I get it fixed ? I saw bunch of similar issues telling how signing process is causing similar issues but not sure if they were caused the same problem.

**Comment by azer** [comment]
Just solved this issue by not using entitlements.

**Comment by mslinn** [comment]
@azer I am new to node-webkit, can you tell a noob what you did to fix the problem?
