### ISSUE TITLE
(MacOS) Rendering Issues

### ISSUE THREAD

**Issue by denneboomyo** [nwjs/nw.js#5981]
When you try to run your app from a terminal by using `open "/Applications/AppName.app"` for example, the browser will render basic css animations and filters improperly or not render them at all.

It seems to be linked to #5845 and https://bugs.chromium.org/p/chromium/issues/detail?id=666228.
It also seems like this bug only occurs for MacOS systems with a German locale (de_DE).
In CEF you can set the locale to any locale string in the CefSettings, is there any way to change the locale used by nw.js ?

nw.js Version: 0.23.4 ; macOS Version: 10.12.4

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
