### ISSUE TITLE
Issue building branch 23

### ISSUE THREAD

**Issue by andrewpskelton** [nwjs/nw.js#5982]
Hi,

I am trying to build NW.js release 23 from the source code. I can checkout the nw23 branches of nw, node-nw and v8 without any issues, but when I run gclient sync I get the following error:

> error: pathspec 'refs/remotes/origin/nw23' did not match any file(s) known to git.

When I look in src/.git/refs/remotes/origin, the HEAD file contains "ref: refs/remotes/origin/nw22" which I guess is what is causing the problem.

My .gclient file has the URL set as "https://github.com/nwjs/chromium.src.git@origin/nw23" so I'm not sure where it is getting nw22 from. Maybe because it's the default branch on the Chromium mirror.

Is there anything else I need to change in order to build nw23?

Thanks.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
