### ISSUE TITLE
Register shortcut with more than one key

### ISSUE THREAD

**Issue by comptron** [nwjs/nw.js#5987]
Hi,

Is it possible to register shortcut with one modifier and **more than one** key?
like "Ctrl+R+T"

Thanks,

**Comment by jaredmcateer** [comment]
This isn't the appropriate place to ask help types of questions, it's mainly for reporting bugs or proposing features. You'll be able to find help on their [Google Group foum](https://groups.google.com/forum/#!forum/nwjs-general)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
