### ISSUE TITLE
nw.js 0.20.1&0.23.5 has memory leak when running simple web page, how to solve?

### ISSUE THREAD

**Issue by zhl2017** [nwjs/nw.js#5992]
use pidof nw(exe in 0.23.5)
top -p xxx,xxx

**Comment by zhl2017** [comment]
Does anybody knows the memory leak issue?

**Comment by rogerwang** [comment]
Please provide a reproducible case.

**Comment by zhl2017** [comment]
reproducible case: run web app , from head page to go next page  an go next,about 10 page, then return previous page until head page, see the changes of memory, use  pidof nw(exe in 0.23.5 version and later)
 top -p xxx,xxx,you will see the memory is always increasing.

**Comment by rogerwang** [comment]
close until more information is available. @zhl2017 please provide a case so we can reproduce it.
