### ISSUE TITLE
Command line arguments quotes are missing

### ISSUE THREAD

**Issue by nickverlinden** [nwjs/nw.js#5994]
Hi,

When passing an argument on commandline that contains quotes, the quotes are removed in nw.gui.App.argv (also in fullArgv). I need to pass json data as a commandline argument such as:

nwjs --config {"foo":"bar"}

This results in (gnw.gui.App.argv):
[ "--config", "{foo:bar}" ]

I can't parse this result using JSON.parse. When doing this using node.js, behavior is as expected and i get a parsable result in process.argv.

Tested this in 0.21.6-sdk on OSX & Windows 10, and 0.23.5 on OSX.

Kind regards,
Nick

**Comment by hujiajie** [comment]
Hi, @nickverlinden, I think double quotes will not be passed to nwjs or any other program by shell, unless it is escaped by `\` or quoted with `'`, so I really can't understand why things can work in node.js. Can you provide the exact command you tried with node.js?

**Comment by nickverlinden** [comment]
Hi hujiajie,

Sorry about that, the command used in node.js is actually indeed: 
--config {\"foo\":\"bar\"}

But this also does not work in nw.js, the nw.gui.App.argv still results in:
{foo:bar}

Kind regards,
Nick

**Comment by hujiajie** [comment]
I cannot reproduce the issue on Windows 10. How do you know it's `{foo:bar}` instead of `{"foo","bar"}`? Can you provide a minimal but complete test case?

**Comment by nickverlinden** [comment]
I'm afraid the problem exists between keyboard and chair.
I was starting nw.js as a child process from node and just pass the process.argv to the child_process. But I needed to escape the quotes again by doing so in order for it to work. I did not realize this until I was building a test case for you hujiajie.
I'm very sorry for wasting your time!
