### ISSUE TITLE
evalNWBin doesn't Load Compiled JavaScript from Remote on win32	

### ISSUE THREAD

**Issue by Erte148** [nwjs/nw.js#5995]
I'm using nw.js 0.20.3 and use nwjc tool to compile my js file. Then i load bin file with following line:
```
<script>
        require('nw.gui').Window.get().evalNWBin(null, 'bin/file.bin');
</script>
```
it works.
If compiled JavaScript is extracted from a remote server and executed on the fly, then it does not work.
```
<script>
url = 'http://test_site.com/bin/file.bin';
var xhr = new XMLHttpRequest();
xhr.responseType = 'arraybuffer'; 
xhr.open('GET', url, true);
xhr.send();
xhr.onload = () => { 
  nw.Window.get().evalNWBin(null, xhr.response);
}
</script>
```

 Errors do not produce any. Just does not work.
These problems only occur on win32. On win64, everything works.

**Comment by kkm** [comment]
can you test for me? https://github.com/nwjs/nw.js/issues/6001 I cant load with local and bin.

**Comment by Christywl** [comment]
It also works fine for me on Windows 8.1 x64 with nwjs-sdk-v0.24.2.  Seem it's a win 32 specific issue?

**Comment by Christywl** [comment]
I get a win32 device, and try the latest nwjs build v0.27.3-ia32, it works fine. Is this issue still reproduced for you with the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
