### ISSUE TITLE
The App open event were never triggered

### ISSUE THREAD

**Issue by uudiin** [nwjs/nw.js#6000]
The App open event were never triggered

**Comment by bambooCZ** [comment]
This have happen to me also. Do you have some special chars in your app name? I mean something like dot or dash etc.

**Comment by Christywl** [comment]
App open event works fine for me on Linux/Windows with nwjs-sdk-v0.23.5(http://docs.nwjs.io/en/latest/References/App/#event-openargs). Could you please upload your sample for me to check?

**Comment by Christywl** [comment]
close until there is more information.
