### ISSUE TITLE
node-main not work.

### ISSUE THREAD

**Issue by EdvaldoLima** [nwjs/nw.js#6002]
I'm having trouble executing a node js script, following documentation recommendations and even performance, I put the project folder in the same directory as the nwjs binaries, when running the application it runs normally, it does not show any errors, but one Server in escript nodejs does not run, whereas if I separate the project folder from the nwjs folder it runs normally with no problem whatsoever.

So the nodejs server runs:
![execut](https://user-images.githubusercontent.com/12137008/27796737-6ae40d92-5fe1-11e7-9283-28ee190212ee.jpg)

```
{
  "name": "cms",
  "version": "1.0.0",
  "description": "Application CMS",
  "node-main": "server.js",
  "main": "index.html",
  "window": {
    "icon": "img/icon.png",
    "frame": false,
    "resizable": false,
    "width": 700,
    "height": 450
  }
}
```

So the nodejs server does not run:
![mesmfolders](https://user-images.githubusercontent.com/12137008/27796862-dd9e1a76-5fe1-11e7-8710-9eee0b8124ce.jpg)

```
{
  "name": "cms",
  "version": "1.0.0",
  "description": "Application CMS",
  "node-main": "app/server.js",
  "main": "app/index.html",
  "window": {
    "icon": "app/img/icon.png",
    "frame": false,
    "resizable": false,
    "width": 700,
    "height": 450
  }
}
```

**_Windows 10 x64.
Nwjs 0.23.5_**

What can it be?

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows with nwjs-sdk-v0.23.5. `node-main` works fine in the two scenarios:
```
{
 "name": "test-6002",
 "main": "index.html",
 "node-main": "1.js",
 "dependencies": {
  "log4js": "^1.1.1"
 }
}
```
or
```
{
 "name": "test-6002",
 "main": "app\index.html",
 "node-main": "app\1.js",
 "dependencies": {
  "log4js": "^1.1.1"
 }
}
```
You can also upload your test cases, I'll help to check in my environment.

**Comment by EdvaldoLima** [comment]
A really intriguing question, if I simulate a wrong path in `"node-main"`, for example `"node-main": "../app/server.js"`, it returns errors, and with the right path no error is shown And the server does not start, the application runs normally, but the server pointed to in "node-main" is not started in any way.

**Comment by EdvaldoLima** [comment]
The strange thing is that if I put my project as 

> "package.nw"

 in the same directory as nw.exe it will run normally and will start the server, another test is, that if I put everything "loose" in the same directory as nw .exe will also run, I see the problem is when I separate my files into a specific directory, which in my case is the "app" directory, in which case the application runs, but the server does not start.

**Comment by EdvaldoLima** [comment]
problem solved.

**Comment by Llorx** [comment]
But, how do you solved it???

**Comment by Sigurthorb** [comment]
@EdvaldoLima Could you elaborate how you solved your issue?
This issue is in the top of google search for this issue.

**Comment by mironovpib101** [comment]
Hi 
"node-main" is "./bin/start_server.js" - is not correcnt.
"node-main": "/home/[UserName]/projects/HelloWorld/bin/start_server.js", - is correct.

UserName -  is you, not variable.

**Comment by mironovpib101** [comment]
hi my dears.
Use relative path is not correct, use absolute path.

**Comment by premalatha-bv** [comment]
node-main is not working in Mac machine, though have given correct path, the server is not getting started

**Comment by EdvaldoLima** [comment]
Greetings,

I apologize for the time I spent outside of github, I recreated the situation on my computer and it works perfectly according to the example of the .json file.

`
{
   "name": "nwjs",
   "version": "1.0.0",
   "description": "",
   "main": "app / index.html",
   "node-main": "app / server.js",
   "directories": {
     "lib": "lib"
   },
   "scripts": {
     "test": "echo \" Error: no test specified \ "&& exit 1"
   },
   "author": "Edvaldo Lima",
   "license": "ISC"
}

`
