### ISSUE TITLE
gclient sync throws 'src/content/nw/tools/patcher.py': [Errno 2] No such file or director

### ISSUE THREAD

**Issue by Ajeey** [nwjs/nw.js#6003]
gclient file - 
`solutions = [
  { "name"        : "src",
    "url"         : "https://github.com/nwjs/chromium.src.git@origin/nw17",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {
	    "src/third_party/WebKit/LayoutTests": None,
	    "src/chrome_frame/tools/test/reference_build/chrome": None,
	    "src/chrome_frame/tools/test/reference_build/chrome_win": None,
	    "src/chrome/tools/test/reference_build/chrome": None,
	    "src/chrome/tools/test/reference_build/chrome_linux": None,
	    "src/chrome/tools/test/reference_build/chrome_mac": None,
	    "src/chrome/tools/test/reference_build/chrome_win": None,
	}
  },
]
cache_dir = None
`

Ran the command - `gclient sync --with_branch_heads`

After 1 hour into the sync, 

I am getting this error - 
`________ running '/usr/bin/python src/content/nw/tools/patcher.py --patch-config src/content/nw/patch/patch.cfg' in '/home/ajey/nwjs'
/usr/bin/python: can't open file 'src/content/nw/tools/patcher.py': [Errno 2] No such file or directory
Error: Command '/usr/bin/python src/content/nw/tools/patcher.py --patch-config src/content/nw/patch/patch.cfg' returned non-zero exit status 2 in /home/ajey/nwjs
`

OS - ubuntu 16.04 LTS
Disk - 300 GB free

Please suggest way forward!

**Comment by rogerwang** [comment]
You should use the latest branch name 'nw23', where the NW repos are supposed to be cloned manually.

**Comment by Ajeey** [comment]
@rogerwang And in the .gclient file it should point to nw17 as in - 
`https://github.com/nwjs/chromium.src.git@origin/nw17`

and in the nw repos where we clone manually the branch should be nw23?

Have I got it correct?

**Comment by rogerwang** [comment]
Please use 'nw23' branch for all NW repos.

**Comment by Ajeey** [comment]
Yes got that about the NW repos, but what should be the chromium src "url" in .glcient file?

The documentation says - 
`gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw17` <--- //nw17 branch

But the nw repos are on nw23 branch.

Is this correct?

**Comment by rogerwang** [comment]
It should be 'nw23'.

**Comment by Ajeey** [comment]
Okay thank you. Please update the online doc. Really confusing for 1st time build :(
