### ISSUE TITLE
Windows Native Node Module issue

### ISSUE THREAD

**Issue by RichardFoss** [nwjs/nw.js#6007]
I have been successfully using the module cap in an osx node/nw program to receive and transmit Ethernet packets. I am porting the program to Windows, and have an issue with the cap module that can't be resolved on the cap site:
https://github.com/mscdex/cap/issues
Feedback is that nw is the problem. 
I am using node.js v6.11.0 and nw.js v0.23.5. Windows 8.1.

A problem arises at the statement:
var Cap = require('cap').Cap;
Where I get the following output:

module.js:640 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\AVBFlexSDK\node_modules\cap\build\Release\cap.node
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:527:32)
    at tryModuleLoad (module.js:490:12)
    at Function.Module._load (module.js:482:3)
    at Module.require (module.js:537:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\AVBFlexSDK\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (module.js:593:30)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:527:32)

The statement is not a problem within a node.js program, and the cap module installs fine (Python 2.7 and Visual C++ installed). I have done the following to resolve the issue:

1. Given that I am using an LTS release, I first replaced the win_delay_load_hook.cc file with the one given on the nw.js documentation page. The require statement resulted in the same error message.
2. I then followed the procedure for the non-LTS releases:
set PYTHON=C:\Python27\python.exe
set npm_config_target=0.23.5
set npm_config_arch=x64
set npm_config_runtime=node-webkit
set npm_config_build_from_source=true
set npm_config_node_gyp=C:\Users\<my info>\AppData\Roaming\npm\node_modules
Still the same result - an error at the require statement.

Any help/guidance would be much appreciated!

**Comment by Christywl** [comment]
Please try to use `nw-gyp`. In the node_modules/cap folder, run `nw-gyp rebuild --target=0.23.5`. This works fine for me.

**Comment by RichardFoss** [comment]
Thank you VERY much for this guidance. This has taken me beyond the 'require' statement. I am now getting 'undefined' from the cap findDevice method. However, this is a cap issue, and not relevant to this group. Thanks again, much appreciated!

**Comment by Christywl** [comment]
Close this as it's not a nwjs issue.
