### ISSUE TITLE
game no longer works in 23.5 on osx, works fine in 17.6

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#6008]
I've seen in the change log that it's no longer package.nw but app.nw. On start up still only the test page is shown, so there must have been another change I've missed?

**Comment by Christywl** [comment]
Could you please provide more info here? A sample, steps, ...

**Comment by marcgfx** [comment]
Sure thing. I was assuming I was just missing something obvious. You can download an older demo from here [ ](http://falkenbrew.com/). Taking the package.nw from the zip, I could not get it to launch with 23.5. It did not work at first, so I checked the changelog and renamed to app.nw but that did not change anything. It's likely something trivial?

**Comment by tekrat** [comment]
Your link did not come through via the email list,  Please paste the whole
into the email / web interface.

**Comment by marcgfx** [comment]
Sorry about that. I am not used to the way you have to add links to a comment on github, so I had to correct it after posting. I guess thats why it did not go through to the mailing list. Direct link to download: http://falkenbrew.com/devader/devader_osx64.zip

**Comment by Christywl** [comment]
It works fine for me on Mac with nwjs-sdk-v0.23.5. I unzip your file, and put `package.nw` in `nwjs.app/Contents/Resources/`, and rename `package.nw` to `app.nw`, and run `./nwjs` in `nwjs.app/Contents/MacOS/`.

**Comment by marcgfx** [comment]
Thanks for testing it out Christywl. I'm used to just dropping the package into the same folder, I'm guessing that will be the issue? I will try placing it within the folder you specified, thanks!

**Comment by Christywl** [comment]
@marcgfx , is this issue still reproduced for you?

**Comment by marcgfx** [comment]
@Christywl, the problem was solved by including it in the package. At some time I guess the way I was doing it was no longer a valid approach.
