### ISSUE TITLE
con of Node.js app is not visible in Windows X64

### ISSUE THREAD

**Issue by ayush191992** [nwjs/nw.js#6010]
I have my package.json contents as below

{
"name": "TestApp",
"main": "index.html",
"window": {
"width": 1200,
"height": 768,
"icon" : "Favicon.png",
"webkit": {
"plugin": true

    }
},
"description": "My Test App ",
"version": "1.0.0"	
}

icon I am using is of png type. I tested my App Icon is displaying in task bar in Windows 7/8 and Ubuntu 16.0 but When I launch my app in Windows 10 then I am not able to view the Icon in task bar for my node.js application.

Please share your comment on these

**Comment by EdvaldoLima** [comment]
Is the path of the icon correct? I could not reproduce this problem in Windows 10 x64, can you send an example to be able to test?

**Comment by ayush191992** [comment]
@EdvaldoLima Yes Path is correct. Issue is reproducible in windows 10 only. Can you share me the icon with which you are trying.May be the resolution and dimensions of icon matters.

**Comment by EdvaldoLima** [comment]
@ayush191992 ok, I tested this image [768px-APK_format_icon.png](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/APK_format_icon.png/768px-APK_format_icon.png) and everything is alright.

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 10 with nwjs-sdk-v0.23.5. Please upload your sample to reproduce your issue.

**Comment by ayush191992** [comment]
@EdvaldoLima @Christywl  Many thanks for your help there was some problem in my logo resolution properties it seems that's why it didn't worked for me. I corrected it. Now it works fine for me.
