### ISSUE TITLE
Something really wrong with nw.gui Window.open documentation

### ISSUE THREAD

**Issue by jochemstoel** [nwjs/nw.js#6011]
Hi, the documentation found on [Window documentation](https://github.com/nwjs/nw.js/wiki/window)  describes how to open a new window and have a reference to it. I think you made a small mistake or the documentation is really outdated. Please fix it.

The following code is copy pasted from documentation.  It suggests that identifier **win** will reference the child _NWWindow_ object but it is actually undefined.

```js
var win = gui.Window.open ('https://github.com', {
  position: 'center',
  width: 901,
  height: 127
});
win.on ('loaded', function(){
  // the native onload event has just occurred
  var document = win.window.document;
})
```
This is wrong.  The on loaded event will not happen because  there is no such thing. The variable **win** will be **undefined**. Of course I did not just come here to complain, here is what happens. 

In stead of a synchronous return, the child _NWWindow_ instance is passed to an optional callback function that you can pass as the **third** argument of Window.open. This is not in the documentation, I discovered this by random.
```js
/* this works. */
var nwgui = require('nw.gui')
/* declare win */
var win
nwgui.Window.open('http://github.com/', {
  focus: true, 
  position: 'center'
}, function(instance) {
	/* yay! instance now references the NWWindow object 
	 * so now we can reference instance.window.document, use onload
	 * events or expose it to this scope by assigning it to win. */
	win = instance
})
```
Please fix the documentation, I wasted a lot of time today with this.

**Comment by killerspaz** [comment]
You're probably looking at the wrong documentation. The Wiki on github is for 0.12, and you likely want the 0.13 version of the docs: http://docs.nwjs.io/en/latest/References/Window/#windowopenurl-options-callback

Notice on the link you provided (https://github.com/nwjs/nw.js/wiki/window), as well as the current docs state clearly in bold that there's a change with the version.

**Comment by Christywl** [comment]
Please refer to nwjs doc: http://docs.nwjs.io

**Comment by Christywl** [comment]
close until there is more information.
