### ISSUE TITLE
How does NW open chrome://downloads to view the list and schedule of currently downloaded files?

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#6013]
How does NW open chrome://downloads to view the list and schedule of currently downloaded files?
![qq 20170709224049](https://user-images.githubusercontent.com/6937002/27994818-b0ddf84c-64f7-11e7-9135-7ced08cae322.png)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
