### ISSUE TITLE
How to see cookies?

### ISSUE THREAD

**Issue by subversivo58** [nwjs/nw.js#6014]
Hi, i am use NWJS v0.23.5 [SDK] and Windows8 64bit.

I'm not view cookies stored in DevTools Panel -> Application -> Cookies

It's a bug or have one settingss of show this?

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
