### ISSUE TITLE
404 for the url -> https://chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/cookbook.md#Variable-mappings

### ISSUE THREAD

**Issue by Ajeey** [nwjs/nw.js#6016]
Trying to follow the document to build a custom binary and the link returns 404.

You can find the link here - 
http://nwjs.readthedocs.io/en/nw22/For%20Developers/Building%20NW.js/

And then search for this link - https://chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/cookbook.md#Variable-mappings

**Comment by Christywl** [comment]
Does this reproduce on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by hujiajie** [comment]
I can confirm this documentation issue
