### ISSUE TITLE
missing chrome.bluetoothLowEnergy  API

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6017]
i can't find chrome.bluetoothLowEnergy  API in nw version  23.5
is there any change ?

**Comment by Christywl** [comment]
I can reproduce this issue  with nwjs-sdk-v0.23.6.

**Comment by NAllred91** [comment]
I'm also not seeing chrome.bluetoothLowEnergy.  I thought NW.js supported all chrome.* API's, but https://developer.chrome.com/apps/bluetoothLowEnergy indicates that this api works only on ChromeOS

**Comment by NAllred91** [comment]
@rogerwang Should we expect chrome.bluetoothLowEnergy to be available, or should we pursue alternate solutions?

**Comment by action-hong** [comment]
i have some problem
chrome.bluetoothLowEnergy is available when nw.js 0.17.6, but it is undefined in nw.js 0.26.6

Windows NT 10.0; Win64; x64

@rogerwang

**Comment by rogerwang** [comment]
I am afraid we don't have any plan to implement it as upstream doesn't support it on the desktop platforms.
