### ISSUE TITLE
Reg: exe icon of NwJs Application

### ISSUE THREAD

**Issue by ayush191992** [nwjs/nw.js#6018]
NWJS application in linux are not showing NWJS Default exe icon as Windows applications are showing.Is this expected?

Is there any way which I can change exe icon of NwJs application in Linux environment. Also in windows i am able to do through resource hacker tool as suggested in github forums. Would there be any way through NWJS api i can achieve rather than using external tools.

Kindly share your feedback. Thanks

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
