### ISSUE TITLE
0.23.x - 0.25.x small icon inside Notification Center of macOS/OSX

### ISSUE THREAD

**Issue by deltapath-eric** [nwjs/nw.js#6020]
![image](https://user-images.githubusercontent.com/12286206/28147996-a7ff5b64-67b6-11e7-82a8-868ec3425edf.png)

This small icon will never follow the app.icns or document.icns
Seem like there is no way to change this

tested in 0.23.0, 0.23.1, 0.23.6

**Comment by deltapath-eric** [comment]
also tested in nwjs-sdk-v0.24.0-rc1-osx-x64.zip which still the same.

I am thinking maybe my .icns file is not correct?

Any help would be appreciated, thanks.

**Comment by deltapath-eric** [comment]
also tested in nwjs-sdk-v0.24.0-osx-x64.zip which having the same behavior.

provided the following demo index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
    <script>window.location = 'https://jsfiddle.net/yoshi6jp/Umc9A/';</script>
    </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>.
  </body>
</html>
```
 and package.json

```javascript
{
  "name": "nw-demo",
  "version": "0.0.1",
  "main": "index.html"
}
```

You can just directly replace the app.icns to go for the testing.

Thanks so much.

**Comment by Christywl** [comment]
I replace nwjs.app/Contents/Resources/app.icns in nwjs-sdk-v0.24.0, launch the sample, the small icon in Notificaiton doesn't change.

**Comment by deltapath-eric** [comment]
Hi, it's me again...
sorry bring this up again as we are facing the branding issue about this bug...

I already tried to use my **limited** skill to look into the src code and seem like i cannot found where that icon came from... i only notices the following files are photo/icon files
 - src/resources/default_100_percent/nw.png
 - src/mac/nw.icns
 - src/resources/nw.ico

can i have a hints where can i start if i would like to **TRY** to work on this?

Any help would be appreciated, thanks so much.

**Comment by deltapath-eric** [comment]
also tested in nwjs-sdk-v0.25.0-osx-x64.zip which having the same behavior.

Thanks for the great work!

**Comment by rogerwang** [comment]
Will see this soon

**Comment by rogerwang** [comment]
It isn't an issue in NW. Please see https://stackoverflow.com/questions/11856766/osx-notification-center-icon
