### ISSUE TITLE
Changing css not reflecting in kiosk mode. Transparency

### ISSUE THREAD

**Issue by psinha6** [nwjs/nw.js#6021]
When I change the css for background on runtime to set it to <body style="background-color:rgba(0,0,0,0);">
The UI remains the same but if I am focusing out and then focusing back the window.(using alt tab in windows it is working).
I have added in manifest
```
  "window": {
    "frame": false,
    "transparent": true,
    "kiosk": true
  }
```
Transparency is working if it is not in kiosk or fullscreen mode.
Also attaching a sample demo project for the same.

To run please add flags i.e.: **nw.exe --disable-gpu --force-cpu-draw**
[testPrj.zip](https://github.com/nwjs/nw.js/files/1144131/testPrj.zip)

**Comment by jtg-gg** [comment]
the pull request https://github.com/nwjs/chromium.src/pull/88
will fix this issue

**Comment by rogerwang** [comment]
Fixed in git and will be available in the next nightly build.

**Comment by psinha6** [comment]
Transparency is not at all working in the latest build. 
is it because of this issue??

**Comment by jtg-gg** [comment]
@psinha6 can you try this latest build
http://dl.nwjs.io/v0.23.7/
I've tested on win7/10 it should works

which windows version do you use ?

and btw from 0.23.7 you can use "--disable-gpu-compositing --force-cpu-draw"
I also has updated the document here: 
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Transparent%20Window/
