### ISSUE TITLE
Severe performance degradation from v 0.22.3 to 0.23.x for Google Maps StreetView

### ISSUE THREAD

**Issue by gouldingken** [nwjs/nw.js#6025]
Version 0.23 appears to degrade performance when running with Google Maps API. I have not seen this issue with other libraries, but it may be that Google Maps is exposing a larger issue. There appears to be more sluggish performance in a number of areas (such as generating polygons) but the easiest way to test is using the built-in functionality of StreetView.

Setup: Windows 10.

Steps to reproduce:

- Create a simple Google Maps site e.g. https://developers.google.com/maps/documentation/javascript/examples/map-simple
- Build this into a nw executable with version 0.23.0 or later (any flavor)
- Run the executable and drag the StreetView man to a street.

Performance degrades to the point where StreetView won't load. Compare this to the speed of StreetView when running in the browser or version 0.22.3 or earlier.

**Comment by Christywl** [comment]
It works fine for me on Windows with nwjs-sdk-v0.26.3. Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information
