### ISSUE TITLE
GPU process initialisation error in UBUNTU 17.04 when using VNC

### ISSUE THREAD

**Issue by asaptechnology** [nwjs/nw.js#6027]
Using Ubuntu 17.04 minimal 
Using latest nwjs-v0.23.6-linux-x64.tar.gz

Server has  GeForce GTX 1080 GPU (NVIDIA-SMI 375.66 Driver Version: 375.66  )  

**Used below to install Desktop**

sudo apt-get -f install -y ubuntu-desktop gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal g++ libgconf-2-4 mesa-utils gcc nvidia-375 nodejs xfce4 xfce4-goodies tightvncserver

Then I login from my mac to server using VNC and when call _nw ._ it fails to load GPU process which I need as I am doing graphic intensive work 

Below is the error (I spent ages on this, please help)

[error.txt](https://github.com/nwjs/nw.js/files/1150631/dump.txt)

Please advice what to do in this case. Thanks

**Comment by rogerwang** [comment]
What about Chromium browser in the same environment?

**Comment by asaptechnology** [comment]
I had to use virtualgl and got it working.

**Comment by rogerwang** [comment]
So Chromium and NW share the same issue?

**Comment by asaptechnology** [comment]
Yes they do
