### ISSUE TITLE
Crash on http if no internet connection

### ISSUE THREAD

**Issue by Zuzon** [nwjs/nw.js#6028]
When I use nodejs http module in webworker, it crashes if no internet connection. I will provide crash dump data soon as it possible.

**Comment by Christywl** [comment]
Please provide the platform and nwjs version. And could you share your sample to reproduce this issue?

**Comment by Zuzon** [comment]
Windows x64, nwjs 0.23.5

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
