### ISSUE TITLE
Webgl not working on windows7 32bit

### ISSUE THREAD

**Issue by felix2ch** [nwjs/nw.js#6029]
Testing on nwjs v0.23.6. in the virtual box.
although, chromium V59 works fine on it. 

chrome://gpu give below messages:

Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Flash: Software only, hardware acceleration unavailable
Flash Stage3D: Software only, hardware acceleration unavailable
Flash Stage3D Baseline profile: Software only, hardware acceleration unavailable
Compositing: Software only, hardware acceleration unavailable
Multiple Raster Threads: Disabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Software only, hardware acceleration unavailable
Video Encode: Software only, hardware acceleration unavailable
WebGL: Unavailable
WebGL2: Unavailable

Problems Detected
GPU process was unable to boot: GPU process launch failed.
Disabled Features: all
Accelerated rasterization has been disabled, either via blacklist, about:flags or the command line.
Disabled Features: rasterization
Raster is using a single thread.
Disabled Features: multiple_raster_threads
Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
Disabled Features: native_gpu_memory_buffers

Version Information
Data exported	2017/7/17 PM2:51:07
Chrome version	Chrome/59.0.3071.115
Operating system	Windows NT 6.1.7601 SP1
Software rendering list version	0
Driver bug list version	0
ANGLE commit id	a9042d3c1952
2D graphics backend	Skia/59 ef6f9c65527412ec4057ea0551f2e051beb94d32
Command Line Args	--use-gl=osmesa --ignore-gpu-blacklist --user-data-dir="C:\Users\admin\AppData\Local\mdesigner\User Data" --no-sandbox --no-zygote --flag-switches-begin --allow-insecure-localhost --show-composited-layer-borders --enable-display-list-2d-canvas --enable-experimental-canvas-features --enable-experimental-web-platform-features --enable-gpu-rasterization --javascript-harmony --enable-webgl-draft-extensions --ignore-gpu-blacklist --flag-switches-end --nwapp="C:\Users\admin\Desktop\x86"
Driver Information
Initialization time	0
In-process GPU	true
Passthrough Command Decoder	false
Supports overlays	false
Sandboxed	false
GPU0	VENDOR = 0xffff, DEVICE= 0xffff

**Comment by Christywl** [comment]
Run `nw.exe --url=chrome://gpu`, it works fine for me on Windows 8 with nwjs-sdk-v0.23.6:
![image](https://user-images.githubusercontent.com/20039821/28258737-69b4bd34-6b05-11e7-91c9-4008852406ec.png)

**Comment by felix2ch** [comment]
It works on 64bit windows, Is your windows 32bit?

**Comment by Christywl** [comment]
My device is Windows 8 x64(I have no Windows 32bit device), so it's a windows 32bit issue?

**Comment by felix2ch** [comment]
Yes

**Comment by Christywl** [comment]
@rogerwang , could you please take a look at this?

**Comment by rogerwang** [comment]
The GPU could be incapable. We shipped Swiftshader in 0.25.3 for this: https://nwjs.io/blog/v0.25.3/
