### ISSUE TITLE
Web bluetooth Crash NWSJ

### ISSUE THREAD

**Issue by felix2ch** [nwjs/nw.js#6030]
nwjs v0.22, chromium v58.0.3029.110
Macos 10.12.5

writeValue after startNotifications will be crash
Below is the code:

return device.gatt.connect()
            .then(server => server.getPrimaryService('0000ffe0-0000-1000-8000-00805f9b34fb'))
            .then(service => service.getCharacteristic('0000ffe1-0000-1000-8000-00805f9b34fb'))
            .then(characteristic => {
                connected = true;
                checkcharacteristic = characteristic;
                checkcharacteristic.addEventListener('characteristicvaluechanged',
                    this.checkNotification());
                return checkcharacteristic.startNotifications();
            })
            .then(_ => {
                console.log('check finish');
                return this.checkFileSize(fileData);
            })
            .catch(error => {
                console.log('Argh! ' + error);
            });

checkFileSize (fileData){
            const bytearray = this.getInt32Bytes(fileData.length);
            const array = new Uint8Array(5);

            array[0] = bytearray[3];
            array[1] = bytearray[2];
            array[2] = bytearray[1];
            array[3] = bytearray[0];

            return checkcharacteristic.writeValue(array.buffer);
    }

dump file :

[e80719c3-d6af-4a87-ab52-b41733f70f03.dmp.zip](https://github.com/nwjs/nw.js/files/1151825/e80719c3-d6af-4a87-ab52-b41733f70f03.dmp.zip)

**Comment by Christywl** [comment]
Could you please provide a sample and steps to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
