### ISSUE TITLE
Using node-webkit-builder with SQLite throws error

### ISSUE THREAD

**Issue by kralkurt** [nwjs/nw.js#6031]
Using Windows 10 x64
Using nw ^0.23.6-1, nw-builder ^3.4.1 & sqlite3 ^3.1.8 dependencies

I'm trying to build a question & answer game using node-webkit with sqlite for local storage, everything works fine during testing using "nw src/". However when I try to build the .exe file I get the following error:

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alejandro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! history@1.0.0 prod: `nwbuild --platforms win32,win64 --buildDir dist/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the history@1.0.0 prod script 'nwbuild --platforms win32,win64 --buildDir dist/ src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the history package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nwbuild --platforms win32,win64 --buildDir dist/ src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs history
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls history
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\alejandro\Documents\proyectos\nwjs\npm-debug.log
```
Project Structure:
![pic1](https://user-images.githubusercontent.com/25697711/28280254-23d96044-6af1-11e7-97a1-5b7c0ece5f68.png)

Package.json:
![pic2](https://user-images.githubusercontent.com/25697711/28280255-240a8368-6af1-11e7-934c-1bd6591461e7.png)

I have already tried updating both node-webkit & node-webkit-builder and it keeps throwing the error, I also tried building the sqlite3 for node-webkit and got the same result.

npm-debug.log:

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alejandro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle samurai@1.0.0~ preprod: samurai@1.0.0
6 silly lifecycle samurai@1.0.0~ preprod: no script for preprod, continuing
7 info lifecycle samurai@1.0.0~ prod: samurai@1.0.0
8 verbose lifecycle samurai@1.0.0~ prod: unsafe-perm in lifecycle true
9 verbose lifecycle samurai@1.0.0~ prod: PATH: C:\Users\alejandro\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\alejandro\Documents\proyectos\fix\project\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Condusiv Technologies\ExpressCache\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\sqlite;C:\Python27;C:\tools\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\alejandro\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\alejandro\AppData\Roaming\npm;C:\Users\alejandro\AppData\Local\atom\bin
10 verbose lifecycle samurai@1.0.0~ prod: CWD: C:\Users\alejandro\Documents\proyectos\fix\project
11 silly lifecycle samurai@1.0.0~ prod: Args: [ '/d /s /c',
11 silly lifecycle   'nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/' ]
12 silly lifecycle samurai@1.0.0~ prod: Returned: code: 1  signal: null
13 info lifecycle samurai@1.0.0~ prod: Failed to exec prod script
14 verbose stack Error: samurai@1.0.0 prod: `nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\alejandro\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\alejandro\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid samurai@1.0.0
16 verbose cwd C:\Users\alejandro\Documents\proyectos\fix\project
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alejandro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
19 error node v6.9.4
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error samurai@1.0.0 prod: `nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/`
22 error Exit status 1
23 error Failed at the samurai@1.0.0 prod script 'nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the samurai package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs samurai
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls samurai
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information.
