### ISSUE TITLE
Stop NW.js from crashing in mixed context mode?

### ISSUE THREAD

**Issue by rafaelferreiraql** [nwjs/nw.js#6032]
Running NWjs 0.23.2 in Windows 8.

I'm writing an app that relies a lot in modules. So, I've been using mixed context mode to make debugging less of a headache, but every time the Node part has any kind of error, the NW SDK rudely crashes and quits before I can do anything. I'm aware that NW offers a crash dump (I hadn't been able to set it up but admittedly I didn't try too hard), but it would be way more convenient to just use the regular Chromium console for that. Too bad the app crashes before I can read any errors. It stops happening when I go back to separate context, along with all the hassle of having to deal with two distinct console windows.

Is there a way to stop NW from crashing without having to leave mixed context?

**Comment by rogerwang** [comment]
Please provide a sample to reproduce. Thanks.

**Comment by Christywl** [comment]
close until there is more information
