### ISSUE TITLE
Requesting binary from remote server crashs

### ISSUE THREAD

**Issue by icezeko** [nwjs/nw.js#6033]
When i use the request binary to run my app i get this error (Only with nwjs windows x32), and app just close, already tried with 0,24 beta, 0.23, 0,22 with http with https with server ip always the same error

> [0717/233011.405:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol  (0x2ee6)

> [0717/233043.731:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol  (0x2ee6)

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this?

**Comment by Christywl** [comment]
close until there is more information.
