### ISSUE TITLE
app crashes when  alert or prompt is used in Javascript,in the latest version(0.23.6) when used with nw-builder in window7

### ISSUE THREAD

**Issue by gopaldigient** [nwjs/nw.js#6035]
os is windows 7
nw-builder is used for building--latest version 3.4.1
win32 exe is created
when an alert code is executed by script the total app gets closed
when alert in typed in the devtools console the app crashes and couldn't close the app

**Comment by gopaldigient** [comment]
But when the app is created with nw.js version 0.13.0 app is not crashing or closing works good but, no alert is coming

**Comment by vinaynb** [comment]
Same issue here. Ironically it runs for me in windows 7(32 bit) but app crashes in win 8(64 bit) and win 10 (64 bit).

**Comment by jtg-gg** [comment]
@gopaldigient this might be due to my transparency code
you can disable my code by adding "--disable-transparency"
or you can try this build which contain my fix
http://dl.nwjs.io/live-build/07-17-2017/nw23-ef6d067-0cdd0c3-bdcc2a7-93e37d9/v0.23.6/

**Comment by Christywl** [comment]
It works fine for me on Windows 10 with nwjs v0.23.7 and nw-builder 3.4.1.

**Comment by gopaldigient** [comment]
The issue i reported was for windows 7 service pack 1,and an additional info i use Inno-setup to build exe,
sorry for the late -reply

**Comment by Christywl** [comment]
Could you please provide your sample and the detailed steps? I'll check it on Windows 7.

**Comment by Christywl** [comment]
I check it on Windows 7(64 bit)/Windows 10 with nwjs-sdk-v0.26.6 and nw-build 3.4.1, it works fine.
`alert(Date.now());`
Please try the latest nwjs build, if still reproduced, please upload your sample.

**Comment by Christywl** [comment]
close until there is more information
