### ISSUE TITLE
Unsealed contents present in the root directory of an embedded framework

### ISSUE THREAD

**Issue by swati-srivastava** [nwjs/nw.js#6041]
me.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework: **unsealed contents present in the root directory of an embedded framework**

Can't understand this. All symlinks are proper and structure too.

NWJS : nwjs-v0.23.6-osx-x64.zip

**Comment by pz325** [comment]
the same issue here, for version 58.0.3029.96

**Comment by Christywl** [comment]
Is this issue reproduced on the latest nwjs build? How can I reproduce it?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by tankakatan** [comment]
The problem is still reproduced on 0.27.2 (63.0.3239.108). It's currently impossible to either sign app for distribution in App Store or to use Apple app sandbox capability. Please reopen the issue.

**Comment by tankakatan** [comment]
A fix for this problem has been found in the following thread: #6338
