### ISSUE TITLE
Reg: Memory Utilization in NwJs Applications

### ISSUE THREAD

**Issue by ayush191992** [nwjs/nw.js#6045]
I have build Nwjs Application which use jstree jquery plugin. Memory seems to continuously increasing on loading the Application and switch between various tabs. 

Please provide suggestion how to use the memory effectively and way to detect memory leaks for proper utilization of memory for my application.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
