### ISSUE TITLE
Sudden nwjs process exit when my native node module calls node::AtExit()

### ISSUE THREAD

**Issue by semmel** [nwjs/nw.js#6047]
When my add-on calls `node::AtExit(myCallback, NULL);` nwjs just exits suddenly:
>...
>The thread 0x25a4 has exited with code 3 (0x3).
>The thread 0x1b28 has exited with code 3 (0x3).
>The program '[10128] nwjs-sdk.exe' has exited with code 3 (0x3).

This occurs for nwjs v. `0.23.6` and `0.24-rc1 nightly`. It has worked fine before (i.e. in nwjs `0.22.3`).
So I *assume* it may be related to Node.js `v.8`? But that I have not verified since my dev machine still runs Node.js `0.6.9.something`.

I build and run the add-on on Windows 7 Professional 32-Bit using VS Studio 2015.

The test setup is the simplest Node add-on possible:
```C++
// file hello.cc
#include "node.h"
namespace demo {
	using v8::FunctionCallbackInfo;
	using v8::Isolate;
	using v8::Local;
	using v8::Object;
	using v8::String;
	using v8::Value;

	void Method(const FunctionCallbackInfo<Value>& args) {
	  Isolate* isolate = args.GetIsolate();
	  args.GetReturnValue().Set(String::NewFromUtf8(isolate, "world"));
	}
	// just test if node::AtExit crashes the process
	static void onExit(void*) {
		assert(true);
	}
	void init(Local<Object> exports) {
	  NODE_SET_METHOD(exports, "hello", Method);

	  node::AtExit(onExit, NULL);  // <--- offending line, set a breakpoint here
	}
	NODE_MODULE(addon, init)
}
```
`binding.gyp`
```json
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "hello.cc" ]
    }
  ]
}
```
Building the add-on is by the [book](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/):
```shell
nw-gyp configure --target=0.23.6 --arch=ia32 --debug
nw-gyp rebuild --target=0.23.6 --arch=ia32 --debug
```

Next you run `nw.exe` (the SDK build), attach the VS Debugger to the `nw.exe` process (the first in the process list), and when you load the add-on from the dev console with 
```javascript
var addon = nw.require(String.raw`Z:\MyApp\node-modules\hello\build\Debug\addon.node`);
```
the debugger stops at the breakpoint. Stepping over it will then quit the whole process.

Has anyone encountered issues with [`node::AtExit`](https://nodejs.org/api/addons.html#addons_atexit_hooks) ?

**Comment by d3x0r** [comment]
https://github.com/nwjs/nw.js/issues/685

If you run with `--enable-logging=stderr` does it report anything more useful?

```
H:\dev2\nwjs\nwjs-sdk-v0.25.4-win-x64\nw.exe: e:\build\nw25_sdk_win64\node-webkit\src\third_party\node-nw\src\node.cc:4624: Assertion `(env) != (nullptr)' failed.
[20628:14360:1111/201453.346:INFO:chrome_cryptauth_service.cc(222)] Profile is not authenticated yet; waiting before starting CryptAuth managers.
```

is what I get... and just removing my call to node::AtExit() allows my addon to work...
I also had hooks in my loading .js script for process.on( 'exit' ) but there's only one of those, so if something else sets and on-exit that way, I don't get called.

**Comment by rogerwang** [comment]
cc @Christywl

**Comment by Christywl** [comment]
I can reproduce this issue, try on Windows 10 with Visual Studio 2015:
1. Create `hello.cc` and `binding.gyp` files
2. Build addon in cmd:
```
   nw-gyp configure --target=0.26.6 --arch=x64 --debug
   nw-gyp rebuild --target=0.26.6 --arch=x64 --debug
```
3. Run nw.exe (the SDK build), attach the VS Debugger to the nw.exe process (the first in the process list)
4. Load addon in nwjs devtools console:
```javascript
var addon = nw.require(String.raw`C:\\nwjs\\bugs\\6047\\build\\Debug\\addon.node`);
```
5. nwjs just exits suddenly and Output in VS:
```
  ...
The thread 0x27ec has exited with code 134 (0x86).
The thread 0x18f8 has exited with code 134 (0x86).
The thread 0x3b04 has exited with code 134 (0x86).
The thread 0x269c has exited with code 134 (0x86).
The thread 0x25ec has exited with code 134 (0x86).
The thread 0x3584 has exited with code 134 (0x86).
The thread 0xd4 has exited with code 134 (0x86).
The program '[11596] nw.exe' has exited with code 134 (0x86).
```
Step 3: Run `nw.exe --enable-logging=stderr` , don't see any log in cmd.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
