### ISSUE TITLE
Crash when launching an already-running application in single-process mode

### ISSUE THREAD

**Issue by MultiplyByZer01** [nwjs/nw.js#6050]
I am using nw.js 0.23.5 on Windows 10 1511.

Use the following `package.json` file:

```json
{
	"name": "test",
	"main": "index.html",
	"chromium-args": "--single-process"
}
```

Run `nw .`, wait for the app to launch, and run `nw .` again.

Crash dump attached: [2a54e6c0-1f13-4140-97b8-ade517535f90.zip](https://github.com/nwjs/nw.js/files/1167828/2a54e6c0-1f13-4140-97b8-ade517535f90.zip)

I have a hunch that this is related to `nw.App` delivering the [`open`](http://docs.nwjs.io/en/latest/References/App/#event-openargs) event.

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.23.5/v0.23.7.
My index.html:
```
<script>
nw.App.on("open", function(args){document.write(args);});
</script>
```

**Comment by MultiplyByZer01** [comment]
I am no longer experiencing this error. Never mind.
