### ISSUE TITLE
App Crash on start OS X 10.9.5

### ISSUE THREAD

**Issue by vinaynb** [nwjs/nw.js#6051]
* State which version are you using
0.23.7
* State which OS version are you running with
Mac OS X 10.9.5
* Attach the crash dump file if it's a crash: 
I will attach images here as at the moment i don't have access to dump file but i have the images of crash dump from my end user (i have skipped unimportant dump logs as that will be a lot of files). I will try getting the dump and post it here once i have it. 
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/1573465/28515507-8152d838-707b-11e7-8605-91891a27547d.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/1573465/28515506-814fb270-707b-11e7-8803-161c1221f0fc.png">
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/1573465/28515505-814f0c30-707b-11e7-9170-84ab3aa9ef37.png">

I looked into #5873 and learnt that since 0.22 nw uses  symlinks. I am generating my builds using [nw-builder](https://github.com/nwjs-community/nw-builder) and its version is 3.4.1 and the build was created on a machine running OS X 10.12.5 and it runs fine on the same OS but when i try to run the executable on 10.9.5 it crashes with error *application quit unexpectedly*

The build was production build created using `--flavor normal` flag

**Comment by Blatman** [comment]
Yup - happens with me also.
I built an app with nw-builder 3.4.1 and 0.23.6 sdk and on Mavericks(10.9.5) it crashed - worked fine on El Capitan (10.11.6).

Special note:
Initially I dragged the app from El Cap to Mav (inside Parallels VM) and the resulting app package had no symlinks in the nwjs Framework.framework bundle only empty folders of same names.
I then moved the app file via the shared folders and it ended up with the appropriate symlinks intact and I then got the same problem as OP (duplicate services error).

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs v0.23.7 on Mac OS 10.12.5. So it only happens on Mac 10.9.5?

**Comment by vinaynb** [comment]
@Christywl yes it the crash happens only on 10.9.5. I haven't tested it on even more older versions of mac. Also i tried building the same project using nwjs v0.21.0 (which doesn't have symlinks) and it works on  10.12.5 (Sierra) and 10.9.5 (mavericks). Hence i guess introduction of symlinks are causing the crash on mavericks.

**Comment by rogerwang** [comment]
merge with #6108 . Please see more information there.
