### ISSUE TITLE
OSX - 0.24.0 Main window not closing if new window has been opened

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6054]
OSX 10.11.6  El Capitan  

If a menu window has been opened it is not possible to close the main window.
Sample project is attached - select Preferences and this will pop a window, only way to close main window is Force-Quit. 
0.24.0-sdk FAIL
0.24.0rc1-sdk FAIL
0.24.0b2-sdk OK
0.23.7-sdk OK
0.14.7-sdk OK

[wincloseissue.zip](https://github.com/nwjs/nw.js/files/1174994/wincloseissue.zip)

**Comment by rogerwang** [comment]
Thanks for reporting this regression!

**Comment by Christywl** [comment]
Reproduced on Mac with nightly build nwjs-sdk-v0.24.0.
