### ISSUE TITLE
OSX - Transparency - was fixed in 0.23.7 still broken 0.24.0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6055]
Not sure if latest fix is still to make it to 0.24.0 - works fine on 0.23.7

FAIL
![transfail](https://user-images.githubusercontent.com/11089335/28597374-5a3daed8-7195-11e7-9f06-0d36af2703f7.jpg)

OK
![transok](https://user-images.githubusercontent.com/11089335/28597384-6920c656-7195-11e7-854e-029fd200d0f6.jpg)

Cheers.

**Comment by rogerwang** [comment]
The patches were merged into 0.24 branch. CC @jtg-gg

**Comment by jtg-gg** [comment]
ah will look into this soon, hmm the patched was more for windows
looks like chromium 60 upstream has some changes for osx

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/91

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
