### ISSUE TITLE
Window.requestAttention doesn't seem to do anything on macOS

### ISSUE THREAD

**Issue by lili21** [nwjs/nw.js#6058]
* State which version are you using
   **nw.js 0.14.7-sdk**
* State which OS version are you running with
   **macOS Sierra 10.12.5**
* Provide a reproducible case if possible
  [nwjs-issue](https://github.com/lili21/nwjs-issue)
  
* Reproduce step

  1. open devtools
  2. run command `nw.Window.get().requestAttention(true)` through `console`

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.24.0. Nothing happens when run `nw.Window.get().requestAttention(true)` in the devtools console.
Windows: works fine
Linux: the first time works fine, but can't run `nw.Window.get().requestAttention(true)` continuously

**Comment by lili21** [comment]
I won't say it works fine on Windows. at least not with `nw.js@0.14.7-sdk`.

**Comment by rogerwang** [comment]
@Christywl it works for me. Note that Apple document said that "Sending requestUserAttention: to an app that is already active has no effect." https://developer.apple.com/documentation/appkit/nsapplication/1428358-requestuserattention?language=objc
