### ISSUE TITLE
Bundled ChromeDriver not compatible with NW.js

### ISSUE THREAD

**Issue by insightfuls** [nwjs/nw.js#6062]
NW.js 0.22.1: Chromium 58, ChromeDriver 2.27, however, it's ChromeDriver 2.28 that contains "Various updates to work with Chrome 57+" (according to their [https://sites.google.com/a/chromium.org/chromedriver/downloads](release notes)).

NW.js 0.24.0: Chromium 60, ChromeDriver 2.29, however, it's ChromeDriver 2.30 that contains "Various updates to work with Chrome 58+".

I'm on Mac OS X 10.12.5 (Sierra) and was experiencing some really strange behaviour running tests with Protractor with Mocha and Chai-as-promised with NW.js 0.22.1. As soon as you searched for an element, the window would flicker, the layout of some elements would change, and drag-and-drop event handlers would stop working. It took a long time to narrow down the problem to the incompatibility between components in the same NW.js release.

Is it possible to ensure the released versions of ChromeDriver are compatible with the versions of NW.js they are bundled with? Or release them separately so the user can match the versions up themselves? It is very unhelpful when incompatible versions are released together, but that has been the case with the two versions I've tried.

**Comment by kierans** [comment]
I've had similar problems.

**Comment by rogerwang** [comment]
Thanks for reporting. Will check it. Currently it's built from the same version of Chromium code base.

**Comment by insightfuls** [comment]
Thanks for looking into this. If they're in the same upstream codebase, perhaps there's a habit there of releasing Chromium and fixing ChromeDriver later, and since they're released separately, it doesn't matter. If that's the case, separate ChromeDriver zips may be the answer here too.

**Comment by rogerwang** [comment]
Turns out they are on different branches -- chromium is on release branch, chromedriver is on master branch.

**Comment by insightfuls** [comment]
Aha! That explains it! Will you be able to work that into your build to release the appropriate ones together?

**Comment by insightfuls** [comment]
I should say, too, what I should have said up front, which is thank you very much for all the work you do providing us with NW.js. We really appreciate it. It's a great project.

**Comment by rogerwang** [comment]
@insightfuls thanks. I'll see to separate chromedriver build with the master branch.

**Comment by kierans** [comment]
Has there been any movement on this?

**Comment by kierans** [comment]
@insightfuls This issue has been somewhat mitigated by the https://github.com/fleg/nw-chromedriver project.

I think it would be better though to still distribute a compatible ChromeDriver binary.

**Comment by rogerwang** [comment]
According to [upstream chromedriver announcement](https://groups.google.com/a/chromium.org/d/msg/chromium-dev/PgeTInYr7Zs/4ooKj670CgAJ), upstream is changing the release model to a new one similiar to ours. So the chromedriver released with NW.js is compatible.
