### ISSUE TITLE
nwjs connects back to Google after a few minutes open

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#6065]
I see a connection open in my firewall from the nwjs application.

1) Open just nwjs exe without a app
2) Wait 1 minute
3) See a new connection to gstatic.com

The payload is about 8KB in size. Unknown what it is and why nwjs is calling back to Google.

**Comment by Christywl** [comment]
I try on Windows with nwjs-sdk-v0.24.0. Open the default nwjs and wait 1 minute, nothing happens.

**Comment by Reaktive** [comment]
Could this issue [#5865](https://github.com/nwjs/nw.js/issues/5865) be related?

**Comment by Christywl** [comment]
If still reproduce for you, please add more information in #5865. 
Close this issue.
