### ISSUE TITLE
[Question] How to open 'chrome://media-internals/' OR 'chrome://gpu/'

### ISSUE THREAD

**Issue by Ajeey** [nwjs/nw.js#6066]
Hi, 

How do I open "chrome://media-internals/" OR "chrome://gpu/" page within nwjs?

**Comment by Christywl** [comment]
`nw.exe --url=chrome://gpu/`
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Ajeey** [comment]
@Christywl Thank you.
