### ISSUE TITLE
v0.14.6When the text is not selected, the custom right-click menu can be displayed, But when the text is selected, the right-click menu will not show up

### ISSUE THREAD

**Issue by boneVidy** [nwjs/nw.js#6070]
When the text is not selected, the custom right-click menu can be displayed,
But when the text is selected, the right-click menu will not show up；
my nw version is 0.14.6
os is window10
My code is as follows
`var menu = new nw.Menu();

    function createContextMenuList (window, win) {
        var contextMenuList = [

            {
                label: '剪切',
                click: function() {
                    window.document.execCommand('cut', false);
                }
            }, {
                label: '拷贝',
                click: function() {
                    window.document.execCommand('copy', false);
                }
            }, {
                label: '粘贴',
                click: function() {
                    window.document.execCommand('paste', false);
                }
            }, {
                label: '刷新',
                click: function() {
                    win.reload();
                }
            }, {
                label: '关于我们',
                click: function() {

                }
            }
        ];
        return contextMenuList;
    }
    function showMenu(e) {
        e.preventDefault();
        menu.popup(e.x, e.y);

    }

    // main
    // Add some items with label
    //parentWin.showDevTools();
    var contextMenuList = createContextMenuList(window, parentWin);
    contextMenuList.forEach(function(menyItem) {
        menu.append(new nw.MenuItem(menyItem));
    });

    // Hooks the "contextmenu" event
    document.body.addEventListener('contextmenu', showMenu, false);`

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows with nwjs-sdk-v0.24.0. 
![image](https://user-images.githubusercontent.com/20039821/28949778-918be2d4-78f1-11e7-933d-8f0ed05070b3.png)

**Comment by Christywl** [comment]
close until there is more information.
