### ISSUE TITLE
visible-on-all-workspaces not working on mac

### ISSUE THREAD

**Issue by FahadQurashi49** [nwjs/nw.js#6071]
I want to show a window opened from Window.open() on all screens of mac, I read this [issue](https://github.com/nwjs/nw.js/issues/2523), function [win.setVisibleOnAllWorkspaces(visible)](http://nwjs.readthedocs.io/en/stable/References/Window/#winsetvisibleonallworkspacesvisible-mac-and-linux) seems to do my job, but I tried this function and also I tried in manifest [visible-on-all-workspaces](https://github.com/nwjs/nw.js/wiki/manifest-format#visible-on-all-workspaces) but nothing seems to work. . I'm using macOS Sierra version 10.12.5, and nw.js version is 0.12.2, below is the code,

```
myWin = gui.Window.open(url, {
        "title": "test window",
        "frame": false,
        "toolbar": false,
        "focus": true,
        "width": 500,
        "height": 480,
        "resizable": false,
        "transparent": true,
        "position": "center",           
        "new-instance": false,
        "always-on-top": true,
        "visible-on-all-workspaces": true,
        "max_width": 500,
        "max_height": 480
    });

myWin.on('document-end', () => {
    myWin.setVisibleOnAllWorkspaces(true);
    myWin.focus();
});
```
I have also tried [this](https://github.com/nwjs/nw.js/tree/0d9a0319b49c665c88d69ee6b1093bb1ff8f4915/tests/manual_tests/visible_on_all_workspaces) test case but this does not work as well, running index.html gives error "Uncaught TypeError: undefined is not a function" at line 21, index2.html does not gives any error but the window does not show on all (screens/desktops/workspaces) on mac

**Comment by Christywl** [comment]
I try on Mac with nwjs-sdk-v0.24.0. It works fine. Your code is out of date for the latest nwjs build. Here is my code:
```
nw.Window.open("https://nwjs.io", {
        "title": "test window",
        "frame": false,
        "focus": true,
        "width": 500,
        "height": 480,
        "resizable": false,
        "transparent": true,
        "position": "center",           
        "new_instance": false,
        "always_on_top": true,
        "visible_on_all_workspaces": true,
        "max_width": 500,
        "max_height": 480
    }, function(myWin){myWin.on('document-end', () => {
    myWin.focus();
}); });
```

**Comment by FahadQurashi49** [comment]
Yes it is working fine, thanks for help.
