### ISSUE TITLE
The app crashes when sending data on the socket if the socket server that listens on a file descriptor is not started.

### ISSUE THREAD

**Issue by akuoo** [nwjs/nw.js#6073]
I'm writing two apps, the first ,as a server, starts a socket server that listens on a local file, and the secend as a client, sends messages to server throw the socket pipe.
When I start the socket server first and then send a message, it works fine. But when the socket server is closed, and I send a message using the client, it crashes, and there is no crash report at all.

Below is my code:

The server side:

    'use strict';
    const net = require('net');
    const path = require('path');
    const os = require('os');
    const tmpDir = os.tmpdir();
    let sockPath = path.join(tmpDir, 'midway.sock');
    if (process.platform === 'win32') {
        sockPath = sockPath.replace(/^\//, '');
        sockPath = sockPath.replace(/\//g, '-');
        sockPath = path.join('\\\\.\\pipe', sockPath);
    }

    var server = net.createServer(function (stream) {
        stream.on('data', function (msg) {
            console.log('data:', msg.toString());
        });
        stream.on('end', function () {
            console.log('end.');
        });
    });

    server.listen(sockPath);

The client side:

    'use strict';
    const net = require('net');
    const path = require('path');
    const os = require('os');
    const tmpDir = os.tmpdir();
    let sockPath = path.join(tmpDir, 'midway.sock');
    if (process.platform === 'win32') {
        sockPath = sockPath.replace(/^\//, '');
        sockPath = sockPath.replace(/\//g, '-');
        sockPath = path.join('\\\\.\\pipe', sockPath);
    }
    var stream = net.connect(sockPath);
    stream.write(Math.random().toString());
    stream.end();

When I comment the last line in the server side,
//server.listen(sockPath);
the crash happens when the client writes  a  message  at the line 
stream.write(Math.random().toString());

I'm using 0.24.0 under Windows 7.

How to fix it?

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8.1 with nwjs-sdk-v0.24.0. I have no Windows 7 to try. Does it only reproduce on Windows 7?

**Comment by akuoo** [comment]
I try it on Ubuntu16.04-x64, with nwjs-sdk-v0.24.0, and it happen too.
This is the error information.
The attach files are the code which I use.

ku@ku-virtual-machine:/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64$ ./nw index.html
[0804/173830.341962:WARNING:chrome_main_delegate.cc(586)] final extension: .html
ATTENTION: default value of option force_s3tc_enable overridden by environment.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED /tmp/midway.sock
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/nw[6778]: ../../third_party/node-nw/src/async-wrap.cc:735:Local<v8::Value> node::AsyncWrap::MakeCallback(const Local<v8::Function>, int, Local<v8::Value> *): Assertion `(env()->current_async_id()) == (0)' failed.
 1: node::Abort() [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnode.so]
 2: 0x7f00f19d267c [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnode.so]
 3: node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnode.so]
 4: node::ConnectionWrap<node::PipeWrap, uv_pipe_s>::AfterConnect(uv_connect_s*, int) [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnode.so]
 5: 0x7f00f1df5d94 [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnode.so]
 6: uv_run [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnode.so]
 7: 0x7f01052d6f53 [/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64/lib/libnw.so]
ku@ku-virtual-machine:/opt/filesocket/nwjs-sdk-v0.24.0-linux-x64$ 


[app.zip](https://github.com/nwjs/nw.js/files/1199927/app.zip)

**Comment by Christywl** [comment]
I can't reproduce this on Windows 7 with nwjs-sdk-v0.26.0.
![image](https://user-images.githubusercontent.com/20039821/31879552-4c32129a-b810-11e7-8705-006a39bcc711.png)
And I check your codes are for win32, may not usable for Linux.

**Comment by Christywl** [comment]
close until there is more information
