### ISSUE TITLE
Function type not shared in Mixed Content

### ISSUE THREAD

**Issue by NickClark** [nwjs/nw.js#6076]
When trying to use mixed content mode I have run into an issue where the Function's don't share the same global value. 

`chrome.extension.getBackgroundPage().Function === Function // Exptected to be true, is false` 

Version: 0.24.0-sdk

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce it?

**Comment by NickClark** [comment]
Sure, it doesn't need much, Any simple app does this for me. 

https://gist.github.com/NickClark/c913c92f286c4f3e3b42fbd32735bf39

**Comment by Christywl** [comment]
@NickClark , thanks. I can reproduce your issue on Linux/Windows with nwjs-sdk-v0.24.0.

**Comment by NickClark** [comment]
Thanks for taking a look at this. The is a huge blocker for us right now. Also, possibly unrelated though, is that `global`, and `nw.global` don't truly appear to be global. At least setting new properties on them don't seem to show up in other contexts.

**Comment by NickClark** [comment]
I also tried several older versions. Doesn't work there either. This is *supposed* to work right?

**Comment by rogerwang** [comment]
The mixed context mode means the Node context and the DOM context is the same one. But the background page and the visible window belongs to different page so they are supposed to be in different context.
