### ISSUE TITLE
internal error from NWJS when calling win.show and win.focus

### ISSUE THREAD

**Issue by mapleitalert** [nwjs/nw.js#6077]
got a lot of error  when calling parent's win.show and win.focus from child window, please check the gif below:

![error](https://user-images.githubusercontent.com/29968862/28953964-3e5811ba-790e-11e7-9d34-03428f00e208.gif)

**Comment by Christywl** [comment]
Could you please provide your sample to reproduce this?

**Comment by Christywl** [comment]
close until there is more information.
