### ISSUE TITLE
How can I get the computer's unique id based on hardware info?

### ISSUE THREAD

**Issue by linb** [nwjs/nw.js#608]
How can I get the computer's unique id based on hardware info?

like CPU serial or Hard Disk?

**Comment by bruno-preti** [comment]
What if the mac is not available or you can not rely on it because you're working on an app that runs in computers that don't have a network card?
I have the same issue of @linb and I need the ID of the HDD or CPU or something that you know it's there and won't be easily changed.

**Comment by srehanuddin** [comment]
@bruno-preti if you are using windows operating system, following code may help you to get HDD and CPU serial number 

```
var sys = require('util')
var exec = require('child_process').exec;
function puts(error, stdout, stderr) {
    console.log(stdout)
}

exec("wmic CPU get ProcessorId", puts);
exec("wmic DISKDRIVE get SerialNumber", puts);
```

**Comment by bruno-preti** [comment]
Thank you very much @srehanuddin ! I'll try with this if I'm required to do this again.
Have a nice day!

**Comment by Vishal1419** [comment]
@srehanuddin your answer is very much helpful to get hdd serial number. But I want to save this serial number to a variable. So, I want its value. If I try to console.log(stdout.SerialNumber) then it gives me undefined

**Comment by ibelem** [comment]
Perhaps the fingerprintjs2 is one of the solutions for this issue:

http://valve.github.io/fingerprintjs2/ 
https://github.com/Valve/fingerprintjs2

**Comment by Antony007** [comment]
Browser allows very limited access to hardware. I want to uniquely identify your clients, you can use the below chrome extension.

https://github.com/Antony007/ADNIdentifier

**Comment by trunghoang1991** [comment]
hi everyone. everyone for me asks about getting the device id of a computer from browser to send the access token between domain another, single sign-on. thank so much

**Comment by agentpx** [comment]
> 
> 
> Perhaps the fingerprintjs2 is one of the solutions for this issue:
> 
> http://valve.github.io/fingerprintjs2/
> https://github.com/Valve/fingerprintjs2

Not unique on every browser.

**Comment by TheJaredWilcurt** [comment]
As mentioned above, on Windows you can use `wmic` to check the hard drive serial number, but you can also check the motherboard serial number which is less likely to change. `wmic bios get serialnumber`

```js
try {
  const execSync = require('child_process').execSync;
  const response = execSync('wmic bios get serialnumber');
  const serial = String(response).split('\n')[1];
  console.log(serial);
} catch (err) {
  console.log('Error getting serial number', err);
}
```
