### ISSUE TITLE
Crash in win7

### ISSUE THREAD

**Issue by chaxiaoyou** [nwjs/nw.js#6082]
- I'm using Node Webkit 0.14.7

I opened the dump files with WinDbg and this is the output I'm getting:
`DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
DbsSplayTreeRangeMap::Add: ignoring zero-sized range at ?00000000`00000000?
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 7 Version 7601 (23677) MP (4 procs) Free x86 compatible
Product: WinNt
Machine Name:
Debug session time: Mon Aug  7 19:19:03.000 2017 (GMT+8)
System Uptime: not available
Process Uptime: 0 days 0:00:50.000
................................................................
......
Loading unloaded module list
..
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(3258.27f4): Access violation - code c0000005 (first/second chance not available)
eax=00000000 ebx=00000000 ecx=00b5a7e0 edx=0000038e esi=0565f428 edi=00000000
eip=77d4fda1 esp=0565f3e4 ebp=0565f44c iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
Unable to load image C:\Windows\SysWOW64\ntdll.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ntdll.dll
*** ERROR: Module load completed but symbols could not be loaded for ntdll.dll
ntdll+0x1fda1:
77d4fda1 83c404          add     esp,4`

**Comment by mscreenie** [comment]
I don't think that version is being developed anymore. AFAIK test on latest and see if the problem persist if so keep this issue open etc.

**Comment by chaxiaoyou** [comment]
What's the problem? TA only appears on individual win7。

**Comment by chaxiaoyou** [comment]
Is there anything wrong with that? It only appears in individual win7

**Comment by Christywl** [comment]
Does this issue happen on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.

**Comment by GraceLee1028** [comment]
how to fixed this problem?
