### ISSUE TITLE
Version 0.14.6 of NWJS cannot be started on win Xp

### ISSUE THREAD

**Issue by boneVidy** [nwjs/nw.js#6083]
Version 0.14.6 of NWJS cannot be started on win Xp
![img_8493](https://user-images.githubusercontent.com/10415170/29053429-9c68c2c4-7c22-11e7-8711-35cd988774ba.JPG)

**Comment by loumt** [comment]
你好，我也出现了这个报错。win32与64在xp上函数不匹。这个怎么解决。
