### ISSUE TITLE
SpeechSynthesisUtterance It can not speak chinese  not all.

### ISSUE THREAD

**Issue by huge818** [nwjs/nw.js#6084]
Read the following before submitting your issue, thank you.

* win10 x64 

Issues meet the checklist above will be processed before those don't.

var speak=function(str){
	var msg = new SpeechSynthesisUtterance(str);
	msg.lang = 'zh';
	msg.voice = speechSynthesis.getVoices().filter(function(voice) {
		console.log(voice);
		return voice.lang=="zh-CN";
	})[0];
	speechSynthesis.speak(msg);
}

//speak("1234"); // ok
speak("你好");  // no effect

It can not speak chinese  not all.

**Comment by Christywl** [comment]
I can reproduce this issue on nwjs-sdk-v0.24.2.

**Comment by huge818** [comment]
my english is poor
i say that
It can not speak chinese
this is a bug.

**Comment by rogerwang** [comment]
You should use a Google API key as this feature need that.
