### ISSUE TITLE
if  recognition.start() then  recognition.onerror  occur error

### ISSUE THREAD

**Issue by huge818** [nwjs/nw.js#6085]
* win10 x64
  nwjs-sdk-v0.24.1-win-x64

this my is code

var final_transcript = '';
var recognizing = false;
var ignore_onend;
var start_timestamp;

var recognition = new webkitSpeechRecognition();
recognition.continuous = true;
recognition.interimResults = true;

recognition.onstart = function() {
	recognizing = true;
	console.log('info_speak_now');
};	

recognition.onerror = function(evt) {
	if (evt.error == 'no-speech') {
		console.log('info_no_speech');
		ignore_onend = true;
	}
	else if (evt.error == 'audio-capture') {
		console.log('info_no_microphone');
		ignore_onend = true;
	}
	else if (evt.error == 'not-allowed') {
		if (evt.timeStamp - start_timestamp < 100) {
			console.log('info_blocked');
		} else {
			console.log('info_denied');
		}
		ignore_onend = true;
	}
	**console.log('recognition.onerror',evt);**
};

recognition.onend = function() {
	recognizing = false;
	if (ignore_onend) {
		console.log("ignore_onend");
		return;
	}
	if (!final_transcript) {
		console.log('info_start');
		return;
	}
	console.log('recognition.onend');
	if (window.getSelection) {
		window.getSelection().removeAllRanges();
		var range = document.createRange();
		range.selectNode(document.getElementById('final_span'));
		window.getSelection().addRange(range);
	}
};

recognition.onresult = function(event) {
	var interim_transcript = '';
	if (typeof(event.results) == 'undefined') {
		recognition.onend = null;
		recognition.stop();
		upgrade();
		return;
	}
	for (var i = event.resultIndex; i < event.results.length; ++i) {
		if (event.results[i].isFinal) {
			final_transcript += event.results[i][0].transcript;
		} else {
			interim_transcript += event.results[i][0].transcript;
		}
	}
	final_transcript = capitalize(final_transcript);
	final_span.innerHTML = linebreak(final_transcript);
	interim_span.innerHTML = linebreak(interim_transcript);
};

function upgrade() {
	console.log('info_upgrade');
}

var two_line = /\n\n/g;
var one_line = /\n/g;

function linebreak(s) {
	return s.replace(two_line, '<p></p>').replace(one_line, '<br>');
}

var first_char = /\S/;
function capitalize(s) {
	return s.replace(first_char, function(m) { 
		return m.toUpperCase(); 
	});
}

function copyButton() {
	if (recognizing) {
		recognizing = false;
		recognition.stop();
	}
}

function startButton(event) {
	if (recognizing) {
		recognition.stop();
		return;
	}
	final_transcript = '';
	recognition.lang = select_dialect.value;
	recognition.start();
	ignore_onend = false;
	start_timestamp = event.timeStamp;
}

**Comment by Christywl** [comment]
@huge818 , the codes don't work for me. Could you please provide a full sample to reproduce this?

**Comment by Christywl** [comment]
close until there is more information.
