### ISSUE TITLE
NWJS 24.1 no longer works on MAC

### ISSUE THREAD

**Issue by justintheice** [nwjs/nw.js#6086]
Hello,

We are currently using NWJS for a major project at our company. We have currently ran into the following issue when running code in a child_process through fork:

```
bootstrap_node.js:314       wrappedConsole[key] = inspector.consoleCall.bind(wrappedConsole,
                                                 ^

TypeError: Cannot read property 'bind' of undefined
    at installInspectorConsole (bootstrap_node.js:314:50)
    at get (bootstrap_node.js:297:13)
    at writeOut (internal/process/warning.js:27:3)
    at output (internal/process/warning.js:76:3)
    at process.on (internal/process/warning.js:107:7)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at internal/process/warning.js:81:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

We also use the VM module in node to load some remote javascript files into our current context. By doing this, it throws the following warning:

```
[0808/153441.749640:WARNING:chrome_main_delegate.cc(590)] final extension: .js 
```

These problems do not occur in 23.2 or 23.7 and seems to be an issue in the latest stable.

The OS version we are using to test this code is:
v10.11.6 OSX El Capitan

**Comment by rogerwang** [comment]
Thanks for reporting. Could you please provide a sample to reproduce? because our CI test on child_process.fork is passing: https://github.com/nwjs/nw.js/tree/nw24/test/sanity/child_process

**Comment by justintheice** [comment]
I will try to setup one during my lunch break or my off time. Since this is a company project, I can't really produce any code from that source.

Are there also tests on running the vm module? I am wondering if it has to do with this.

**Comment by justintheice** [comment]
From further investigation, it looks like a problem with the use of console in a forked process.

I will post a code sample to reproduce this issue in a few.

**Comment by justintheice** [comment]
Here is the gist that shows that the use of console.log in a child process crashes the child process.

https://gist.github.com/justintheice/140ef7fc6eca5d92c35ef549cbeac568

Thanks!

**Comment by Christywl** [comment]
It reproduces on Mac with nwjs-sdk-v0.24.1, but doesn't reproduce on nwjs-sdk-v0.24.2.

**Comment by justintheice** [comment]
any updates on this? I notice it does work on 24.2, but it is also busted on 24.0 which is supposed to be a LTS if I am correct.

**Comment by rogerwang** [comment]
close as it is working.

btw, there is no LTS plan with 0.24.0
