### ISSUE TITLE
[BUG] shortcut labels of menu items with F1 ~ F12 shortcuts missing in menu under Windows

### ISSUE THREAD

**Issue by dengkunli** [nwjs/nw.js#6090]
When there're multiple menuItems that have shortcuts F1 ~ F12 under the same submenu, the shortcut labels won't show up. For example consider a submenu with 4 menu items labelled A, B, C, D and have `key` defined as `F1, F2, F3, F4` respectively, then only one of the shortcut label will be shown. But the shortcut is still usable.

Information:
nw 0.24
Windows 10

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.24.2.
![image](https://user-images.githubusercontent.com/20039821/29202459-f322ec32-7e9a-11e7-8f92-7d35fc2e4eb9.png)

**Comment by rogerwang** [comment]
@Christywl could you please upload the sample you used to reproduce?

**Comment by Christywl** [comment]
@rogerwang , please download: [6090.zip](https://github.com/nwjs/nw.js/files/1224224/6090.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
