### ISSUE TITLE
input nwsaveas in mac missing extensionName

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6091]
```javascript 
 let input = document.createElement('input')
  input.style.display = 'none'
  input.setAttribute('nwsaveas', 'a.png')
  input.setAttribute('type', 'file')

document.body.appendChild(input)
 input.click()

```
in mac 10.12.5  。 the save file dialog only display "a" instead of "a.png"
but in windows the save file dialog can display "a.png"

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.24.2. It works fine on Linux/Windows.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
