### ISSUE TITLE
nw-sdk dont print file pdf in iframe

### ISSUE THREAD

**Issue by xerardoo** [nwjs/nw.js#6095]
Hi,  I'm trying to print a pdf that is displayed in a IFRAME but  the dialog window doesnt close and  isnt sent to print.
Thanks!

**Version**: nw-v0.24.2
**OS**: Windows 7 64bits

**Code**:
JS:
    `window.frames['printf'].print({printer:'HP LaserJet 1022', preview:'false'});`
HTML:

    `<iframe src="files/myfile.pdf" id="pdfFile" name="printf" frameborder="0" style="display: none;"></iframe>`

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows 8.1 with nwjs-sdk-v0.24.2.

**Comment by Christywl** [comment]
close until there is more information.
