### ISSUE TITLE
Uncorrect command line args order for loading extension

### ISSUE THREAD

**Issue by aprilandjan** [nwjs/nw.js#6098]
According to the document <http://nwjs.readthedocs.io/en/nw23/For%20Users/Debugging%20with%20DevTools/>, the loading extension script is as follow:

```bash
nw.exe --load-extension=path/to/devtools path/to/app/folder
```

I'm now using nw `v0.23.7` on mac and the start script

```bash
nw --load-extension=./react-devtools .
```

this will not work. But if I changed arguments order as follow:

```bash
nw . --load-extension=./react-devtools"
```

then the extension is loaded correctly. Is it the document mistake or bug when `nw executable` parsing arguments?  I uploaded my test project [here](https://github.com/aprilandjan/test-nw) if needed.

**Comment by Christywl** [comment]
Here is my result on Mac with nwjs-sdk-v0.24.2:
 `./nwjs-sdk-v0.24.2-osx-x64/nwjs.app/Contents/Mac/nwjs --load-extension=./react-devtools .`

<img width="1280" alt="screen shot 2017-08-16 at 2 08 56 pm" src="https://user-images.githubusercontent.com/20039821/29349537-26e2a8aa-828d-11e7-9c17-27d4b1af8bfb.png">

**Comment by aprilandjan** [comment]
@Christywl I use the the command `~/.nwjs/0.23.7-sdk/nwjs.app/Contents/MacOS/nwjs --load-extension=./react-devtools .` it worked. However, if I start the application from node script `nw --load-extension=./react-devtools .`, it won't work.

**Comment by Christywl** [comment]
I got the same results with `nw --load-extension=./react-devtools .` and `nw . --load-extension=./react-devtools `. Use nw-sdk-v0.26.6:
<img width="1280" alt="screen shot 2017-11-20 at 2 38 58 pm" src="https://user-images.githubusercontent.com/20039821/33005410-a5abbc26-ce00-11e7-9316-22700224dfa3.png">
<img width="1280" alt="screen shot 2017-11-20 at 2 41 07 pm" src="https://user-images.githubusercontent.com/20039821/33005470-e19fe982-ce00-11e7-9c43-820a5bc08f87.png">

Please try the latest nwjs build.

**Comment by Christywl** [comment]
close until there is more information
