### ISSUE TITLE
AdSense trouble in NWjs

### ISSUE THREAD

**Issue by bambooCZ** [nwjs/nw.js#6099]
Hi,

I've encountered a bug in NWjs which prevents AdSense to work in some cases in NWjs.

It has something to do with iframe cross-origin access. It fails in webview and in top window frame also.

![snimek obrazovky 2017-08-15 v 13 46 23](https://user-images.githubusercontent.com/8124126/29314856-3aa98b74-81c0-11e7-9619-c2a9552de61d.png)

**Comment by bambooCZ** [comment]
Sorry - test app (compatible with Chrome and NWjs)
[adsense-trouble.zip](https://github.com/nwjs/nw.js/files/1224917/adsense-trouble.zip)

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.24.2.

**Comment by bambooCZ** [comment]
Any news?

**Comment by rogerwang** [comment]
Will see this soon.

**Comment by rogerwang** [comment]
![screen shot 2017-10-17 at 10 27 21 pm](https://user-images.githubusercontent.com/165401/31670570-8448e9d0-b31d-11e7-9539-fd7700969f22.png)
The URL `https://sos.seznam.cz/campaign/bannerPreviewScreen?bannerId=1394729&onlyPreview=1` failed to load in Chrome 61 here either ...

**Comment by rogerwang** [comment]
I found the difference with NW and Chrome as the following. But with the minified JS it's hard to tell more information from it.

In the attached HTML downloaded from `https://ad.doubleclick.net/ddm/adi/N9166.161769.PROZENY.CZ/B20104791.201578368;dc_ver=41.108;dc_eid=40004001;sz=300x600;osdl=1;u_sd=1;dc_adk=4037388879;ord=lfmoe0;click=https%3A%2F%2Fi.imedia.cz%2Fclickthru%3FspotId%3D0%26destination%3D;dc_rfl=0,https%3A%2F%2Fsos.seznam.cz%2Fcampaign%2FbannerPreviewScreen%3FbannerId%3D1394729%26onlyPreview%3D1$0;xdt=0;crlt=bey8qr3aAx;sttr=117;prcl=s?`, only a small portion of function I is executed in NW. In Chrome the function E and F at the end of function I is executed. In NW only the line 287-290 and line 292-299 is executed.
[1.zip](https://github.com/nwjs/nw.js/files/1393756/1.zip)

**Comment by rogerwang** [comment]
btw upstream chrome crashed when I tried to debug it in another way. filed issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=775846

**Comment by bambooCZ** [comment]
Hi,

I've managed to isolate the issue. Try URL `https://xn--mrvk-xpa.tk/test/`

**Comment by rogerwang** [comment]
Great! This is very helpful. Will push a fix soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
http://dl.nwjs.io/live-build/10-19-2017/nw26-c8b2590-4dce140-99d3829-e7da451/v0.26.1/
