### ISSUE TITLE
Require fails to load node fs module after loading a new page

### ISSUE THREAD

**Issue by aquinq** [nwjs/nw.js#6100]
Node fs module loads successfully (and works without any trouble) on the first and main page of my app, but when I redirect user to a second one (using window.location.replace(url)), the exact same file that is supposed to load the fs module fails to do so. Maybe node modules should not be required more than one time per session ?

I'm using the latest nwjs version (v0.24.3) on Windows 7 x64.

Thanks for your help !

**Comment by aquinq** [comment]
I forgot to mention that when I load the second page in another session as the main page, the module is actually loaded.

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this?

**Comment by Christywl** [comment]
close until there is more information.
