### ISSUE TITLE
It's possible to build nwjs in RH6/CentOS6?

### ISSUE THREAD

**Issue by Leprosy** [nwjs/nw.js#6101]
It's possible to do this? I need to run nwjs on these distros, but I think the issue is the gtk3 dependency, I understand that gtk3 it's not supported on RH6/CentOS6. I followed the instructions in the "Building nwjs" doc page to no avail(too many weird error messages).

Is there a RH6/CentOS6 build of nwjs? Can it be achieved?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
