### ISSUE TITLE
Issue for setup chromium-args in cross platform app

### ISSUE THREAD

**Issue by chiangandy** [nwjs/nw.js#6102]
because my app uses Flash plugin, package.json need to setup "chromium-args"; for example...
"chromium-args": "--data-path='data/' --enable-application-cache --ppapi-flash-path='plugins/pepflashplayer.dll' --ppapi-flash-version=21.0.0.213",
  
if my app wan to package to both windows and mac osx platform. how to setup "chromium-args" to support both platforms(pepflashplayer.dll and pepflashplayer.plugin two files)?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
