### ISSUE TITLE
Change name of the nwjs helper.app

### ISSUE THREAD

**Issue by Silve2611** [nwjs/nw.js#6103]
NWJS Version : from 19.0 to the newest
Operating System : macOS 10.12.5 

### Expected behavior

Changing the name in the Plist file should change the display name of the nwjs helper.app

### Actual behavior

The helper app ist called nwjs helper.app. If multiple different Programs are using nwjs the user would see a lot of nwjs helper. app and has no chance to know which one actually belongs to a program that is allowed to run it. He might close all of them because he does not know he needs nw.js

### How to reproduce
Try renaming the nwjs helper.app in the newest version.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by Silve2611** [comment]
Great Work!
