### ISSUE TITLE
Can't download nw.js v0.23.6

### ISSUE THREAD

**Issue by Arti3DPlayer** [nwjs/nw.js#6104]
Trying to download `nw.js v0.23.6`

https://dl.nwjs.io/v0.23.6/nwjs-v0.23.6-osx-x64.zip

And get an error:
>part could not be saved, because the source file could not be read.
> Try again later, or contact the server administrator.

**Comment by Arti3DPlayer** [comment]
For other os zips, the same

**Comment by VasiliyIsaichkin** [comment]
I confirm the problem (http and https)

**Comment by Arti3DPlayer** [comment]
Still not fixed :(

**Comment by rogerwang** [comment]
It works for me.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rogerwang** [comment]
I just found it's one of the mirrors failed. Fixed now.
