### ISSUE TITLE
I can't download nwjs with curl from dl.nwjs.io

### ISSUE THREAD

**Issue by shkolyar** [nwjs/nw.js#6105]
NWJS Version: v0.24.3
Operating System: Ubuntu 17.04

Command:
```
$ curl https://dl.nwjs.io/v0.24.3/nwjs-sdk-v0.24.3-linux-x64.tar.gz
```
Error message:
```
(56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.
```

**Comment by VasiliyIsaichkin** [comment]
Everything works fine, but you can use http:// instead of https:// to prevent TLS errors.
![image](https://user-images.githubusercontent.com/1153891/29490060-294b8318-854a-11e7-9beb-3acae2b1d47e.png)

**Comment by shkolyar** [comment]
Thanks, today works.
