### ISSUE TITLE
NW.js On Windows 10 Doesn't Load All Files Into Memory

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#6110]
**General Information:**
- Using NW.js version 0.24.0
- Windows 7 & 10 with latest drivers
- [Package.nw](https://cdn.discordapp.com/attachments/225550155531812865/348986585582272522/package.nw) File
- Construct 2 [Runtime.js](https://github.com/nwjs/nw.js/files/1237494/runtime.zip) File (Audio Plugin)

**Problem Description:**
I'm running a packaged _Construct 2_ game (HTML5).
I've recently noticed a Windows 10 specific _issue_ regarding, loading audio files into memory.
NW.js on Windows 10 doesn't seem to load all audio files into memory.

**Steps to reproduce:**
<1> Run the attached package.nw file
<2> Open the task manager from the dev-tools window (right click on the window frame)
<3> Click on "Load All Audio Files Into Memory" (this button will be greyed on process completion)
<4> Notice that NW.js on Windows 10 only loads about ~200mb into memory (~950mb expected)

**Observed Result**
NW.js on Windows 10 seems to have issues with loading audio into memory.
It only seems to load a set of audio files into memory.

**Expected Result**
NW.js on Windows 10 should load all audio files into memory just like it does on Windows 7.

**Task Manager Screenshots**
_Windows 10 (observed result):_
![win10](https://user-images.githubusercontent.com/15656049/29499951-dd29984e-861b-11e7-999d-345e6c93dd8c.PNG)

_Windows 7 (expected result):_
![win7](https://user-images.githubusercontent.com/15656049/29499941-b13954d6-861b-11e7-8d63-f5ea69266135.PNG)

**Comment by Christywl** [comment]
I try it on Windows 10 with nwjs v0.24.0, but an error displays on the app window:
![6110](https://user-images.githubusercontent.com/20039821/29507033-fc4aa64a-8680-11e7-8ce9-483b7d1b1901.png)

**Comment by TheRealDannyyy** [comment]
@Christywl It's just a selfmade warning message since I shared the Construct 2 project file (capx) with others, in order to test this issue out on a Win10 machine, since I don't own one myself.

Thanks for your test and it further proofs that Windows 10 is indeed not loading all audio files into memory. It should load over 900mb in total into memory, which is clearly not the case.

**Comment by TheRealDannyyy** [comment]
I did some tests on this and this just seems to be a Windows 10 exclusive optimization.
Closing since it's not a bug and doesn't seem to cause any trouble at the moment.

**Comment by call-me-bk** [comment]
Use it under ios::app for loading all possible files into memory
