### ISSUE TITLE
Chrome://settings page 404

### ISSUE THREAD

**Issue by aasci** [nwjs/nw.js#6114]
Hi,
why location.url = 'chrome://settings' it goes on 404 page?
This i serve to set "ask where to save each file before downloading". 

thanks

**Comment by rogerwang** [comment]
we don't support browser settings page as NW is not browser.

**Comment by aasci** [comment]
Thank you very much
but how i set  automatic download (ask where to save each file before downloading)?

**Comment by davismiculis** [comment]
Hello, is there anything on this, I also need an option to automatically save file, so the dialog box won't open. Any workarounds are welcome, but without node.js manually downloadin file, as file is behind authorization etc.
