### ISSUE TITLE
Failed to require  inspector module

### ISSUE THREAD

**Issue by lin-chao** [nwjs/nw.js#6115]
- NWJS Version : 
nw.js 0.24.*-sdk

- Operating System : 
Mac and Win  

- How to recur
  * open devtools
  *  run command `const inspector = require('inspector')`
  * Then it shows an error: `Uncaught Error: Inspector is not available`

----

The inspector module provides an API for interacting with the V8 inspector [details](https://nodejs.org/dist/latest-v8.x/docs/api/inspector.html)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by lin-chao** [comment]
hi @rogerwang 

[nightly build](https://dl.nwjs.io/live-build/08-23-2017/nw24-baac03f-e2db204-9535c2d-ba4586b/v0.24.4/) only found linux version

**Comment by rogerwang** [comment]
Yeah. I'll fix it soon.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/08-23-2017/nw24-baac03f-e2db204-e1e774c-ba4586b/v0.24.4/

**Comment by lin-chao** [comment]
get 

thanks ~

**Comment by lin-chao** [comment]
hi roger

i try this build on Mac 

* open devtools
*  run command `const inspector = require('inspector');  inspector.open(8080)`
* then the crash occurred

**Comment by lin-chao** [comment]
and failed to download [windows version](https://dl.nwjs.io/live-build/08-23-2017/nw24-baac03f-e2db204-e1e774c-ba4586b/v0.24.4/nwjs-sdk-v0.24.4-win-x64.zip)

**Comment by rogerwang** [comment]
I just fixed the crash. Please wait for the next build...

**Comment by lin-chao** [comment]
thanks 

`inspector` works in node contexts
