### ISSUE TITLE
Serial Port access with node-serial port

### ISSUE THREAD

**Issue by RUSHt** [nwjs/nw.js#6116]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.24.9
Operating System : Win 10 - ePOS build

### Expected behavior

<!- What do you think should happen? ->

Have installed node-serial port.  Work OK on device in node 6.11.1

Working in node...

SerialPort = require('serialport');

port = new SerialPort('COM1', { baudRate: 57600 });
port.on('open',() => console.log('open'));

### Actual behavior

<!- What actually happens? ->

In nw.js.....

(unknown) Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\pa\nw-sdk\nw\node_modules\serialport\build\Release\serialport.node
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:527:32)
    at tryModuleLoad (module.js:490:12)
    at Function.Module._load (module.js:482:3)
    at Module.require (module.js:537:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\pa\nw-sdk\nw\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\pa\nw-sdk\nw\node_modules\serialport\lib\bindings\win32.js:2:36)
    at Module._compile (module.js:593:30)
    at Object.Module._extensions..js (module.js:610:10)

### How to reproduce

I first tried with the default node-serial port installation and then build for my environment using the Windows specific instructions at https://github.com/EmergingTechnologyAdvisors/node-serialport.
<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by Christywl** [comment]
Could you please try to use nw-gyp to rebuild node modules? See http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules

**Comment by Christywl** [comment]
close until there is more information.

**Comment by qpwo** [comment]
I had the same problem and rebuilding serialport with nw-gyp finally solved it. Thanks!
