### ISSUE TITLE
There is a problem with the require HTTP or net module causes the nw to crash

### ISSUE THREAD

**Issue by ChenxiangKasscloud** [nwjs/nw.js#6118]
NWJS` Version : 0.15.4
Operating System : windows xp sp2 version 2002

### Expected behavior
I thought there should be no problem, because the internal tests have been passed

### Actual behavior
In the operating system of xp sp2 , the client direct collapsed, finally found to be due to require the HTTP and net two modules, when I am with 0.12.3 version of nw, require these two modules will not collapse

###  copy code
`  

          <!DOCTYPE html>
          <html>
          <head>
	      <meta charset="utf-8">
	      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
          </head>
          <body >
             <h2>test</h2>
	         <script>
                  // no problem
                  var fs = require("fs"); 
                  // direct collapsed
                  var http = require("http"); 
                  var net = require("net");
	          </script>
         </body>
         </html>

`

### description

Use the above code to run on the 0.15.4 version of nw on the system of XP sp2 version 2002

I don't think this is a problem to reproduce simplely；

 I couldn't find the crash log，I'm sorry about that。

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows 8.1 with nwjs-sdk-v0.24.3.

**Comment by Christywl** [comment]
close until there is more information.
