### ISSUE TITLE
unable to use window.close() on nwjs 0.25.0-beta1

### ISSUE THREAD

**Issue by garfield69** [nwjs/nw.js#6122]
NWJS Version : 0.25.0-beta1 SDK
Operating System : windows7

### Expected behavior

From the Development tools Console at the `>` prompt, type `window.close(true)` and the app should shutdown.

### Actual behavior
an error is generated and the app remains running.
```javasscript
(BLESSED_EXTENSION context for bofiindjbjhkggnnpbomnkhgpajmhjdd) extensions::nw.Window:772: Uncaught TypeError: dispatchEventNW is not a function{TypeError: dispatchEventNW is not a function
    at onClose (extensions::nw.Window:772:3)}
```
![image](https://user-images.githubusercontent.com/6933240/29739920-64926190-8a9e-11e7-80f8-894ca9f70ab5.png)

### How to reproduce
see *expected behaviour* section above.

**Comment by rogerwang** [comment]
Thanks for reporting.
Please try this build: https://dl.nwjs.io/live-build/08-17-2017/nw25-44a520e-77cbe98-865ed67-5759fd8/v0.25.0-beta2/

**Comment by garfield69** [comment]
nwjs 0.25.0-beta2 works as expected. Thank you.
