### ISSUE TITLE
setInterval with low repeat time causes the app to freeze.

### ISSUE THREAD

**Issue by uplusion23** [nwjs/nw.js#6123]
NWJS Version : v0.24.2
Operating System : Windows 10 x64

Attempting to use a setInterval function with 200ms and lower seems to freeze the application. The lower the time, the faster the program freezes. I'm attempting to use the memoryjs module to edit memory in an application and need it to fire a function every 20ms. Attempting to do so will work only for around 30 seconds before the main window object hangs and no longer accepts input even using the console.

`app.intervals._doSomething = setInterval(app.doSomething.start, 20);`

```
app.doSomething.start = function() {
  app.doSomething.some();
  app.doSomething.thing();
  app.doSomething.foo();
}
```

Doing such code will break the program shortly. Only happens within NWJS. Using node with the same module works flawlessly when NWJS is not loaded.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux/Windows 10 with nwjs-sdk-v0.24.2/0.24.4. 
Run `setInterval(function(){console.log("Hello World");}, 20); `in the devtools console.

**Comment by uplusion23** [comment]
I'm working all week but I can check more into the issue this coming Friday. I'll see if it's an issue with the specific module interacting with NWJS or something I have done.

**Comment by uplusion23** [comment]
It seems to be an issue with a module. Using MemoryJs with it seems to be the issue. I'm going to toy with it further tonight.

**Comment by uplusion23** [comment]
Fixed by deleting a profile. I downgraded to 0.18.6, and it stated an issue was with my profile being from a newer version, deleted it, still no luck, but upon going back to 24, it seemed to work. No idea. But thanks.
