### ISSUE TITLE
Autoprint of Window.print can't print all papers in small memory environment.

### ISSUE THREAD

**Issue by tangyue0924** [nwjs/nw.js#6124]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.24.3 sdk
Operating System : Win7 (32bit)

### Expected behavior

win.print can print all papers rightly.

### Actual behavior

64bit can be done, but 32bit can't.
Maybe the reason is NW could not start printing after all papers was loaded.

### How to reproduce
I dont know. Perhaps it's a bug of Chrome.

THX for reading. English is not my language.

**Comment by Christywl** [comment]
Any error logs in the console? And does it work on Chrome?

**Comment by tangyue0924** [comment]
@Christywl emm...It was no errors of compilation. The entire program was OK. But the printer couldn't print all papers if I used low memory operating system.

**Comment by tangyue0924** [comment]
@Christywl Excuse me...There's another question about print.
 I have set the `mediaSize` before, but in the print page of Chrome, why the `paper select` was effective ?

**Comment by Christywl** [comment]
Could you please upload your sample to reproduce this issue? And does it only happen on Win 7? What about windows 8/10?

**Comment by kailniris** [comment]
https://github.com/nwjs/nw.js/issues/5111

**Comment by rogerwang** [comment]
close until more information is available.
