### ISSUE TITLE
WARNING: final extension

### ISSUE THREAD

**Issue by sharifzadesina** [nwjs/nw.js#6126]
NWJS Version : 0.24.4
Operating System : ArchLinux

### Expected behavior

There shouldn't be any warning!

### Actual behavior

By running the NW.js application we always have this warning:
```
[0830/030346.622408:WARNING:chrome_main_delegate.cc(590)] final extension:
```

### How to reproduce

- Run a NW.js application using command line, you will see the warning.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
