### ISSUE TITLE
In angular2,can't create webview tag

### ISSUE THREAD

**Issue by viggoChen** [nwjs/nw.js#6127]
In angular2, I want to create a webview tag;
`document.createElement('WEBVIEW')`
But throw an error
` Uncaught TypeError: GuestViewContainer[(this.viewType + "BrowserPlugin")] is not a constructor
    at WebViewImpl.GuestViewContainer.createInternalElement$ (extensions::guestViewContainer:97)
    at WebViewImpl.GuestViewContainer (extensions::guestViewContainer:26)
    at new WebViewImpl (extensions::webView:19)
    at HTMLElement.proto.createdCallback (extensions::guestViewContainer:246)
    at <anonymous>:1:3
`

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux with nwjs-sdk-v0.24.4.
index.html:
```
<!DOCTYPE html>
<html>

<head>
    <title>NW.js Test</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <script type="text/javascript" src="js/lib/angular.min.js"></script>
    <script type="text/javascript" src="js/lib/angular-resource.min.js"></script>
    <script type="text/javascript" src="js/lib/angular-route.min.js"></script>
    <script type="text/javascript" src="js/lib/jquery.min.js"></script>
    <script type="text/javascript" src="js/lib/bootstrap.min.js"></script>
</head>

<body class="container">
    <h1>NW.js Test</h1>
</body>
<script>
var webview = document.createElement('WEBVIEW');
console.log(webview);
</script>
</html>
```
You can also provide your sample here to double check this issue.

**Comment by Christywl** [comment]
close until there is more information.
