### ISSUE TITLE
Set the app-region to not work

### ISSUE THREAD

**Issue by ZeeRoc** [nwjs/nw.js#6128]
NWJS Version : nwjs-sdk-v0.14.7-win-ia32
Operating System : windows 10

### Expected behavior

When I set the app-region to no-drag, I want the interface to respond to my click and mouseover events, but it does not

### Actual behavior

It is still draggable and can not respond to clicks and other events

`
.modal .modal-body{
    background: #fff;
    height: 250px;
    -webkit-app-region:no-drag;
}
`

![image](https://user-images.githubusercontent.com/13727732/29911897-47fdeff0-8e62-11e7-8606-a38bc718b854.png)
![image](https://user-images.githubusercontent.com/13727732/29911925-681d1fe0-8e62-11e7-9ae5-b1344e264c70.png)

**Comment by Christywl** [comment]
Could you please provide your test case to reproduce this?

**Comment by Christywl** [comment]
close until there is more information.
