### ISSUE TITLE
Nw.js crashes if additional_trust_anchors provided and devtools are openned.

### ISSUE THREAD

**Issue by azproduction** [nwjs/nw.js#6135]
NWJS Version : nwjs-sdk-v0.24.4-osx-x64
Operating System : osx-x64

### Expected behavior

If any record in `additional_trust_anchors` is provided and you open dev tools nwjs crashes with segmentation fault.

### Actual behavior

Devtools are opened.

### How to reproduce

Please check attached archive with reproduction case and crash report.
[nwjs-crash.zip](https://github.com/nwjs/nw.js/files/1277109/nwjs-crash.zip)

It might be related to #4210 and #5279

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.24.4. 
The sample works fine on Linux/Windows.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
