### ISSUE TITLE
History escapes isolated iframe with nwfaketop

### ISSUE THREAD

**Issue by azproduction** [nwjs/nw.js#6136]
NWJS Version : nwjs-sdk-v0.24.4-osx-x64
Operating System : osx-x64

### Expected behavior

When user opens content in isolated frame with nwfaketop=true it's content should not be able to control history of the top window via history.back();

### Actual behavior

Iframe is able to control parent window using history.back()

### How to reproduce

Please use attached application to reproduce this issue 
[nwjs-history-escapes-iframe.zip](https://github.com/nwjs/nw.js/files/1277633/nwjs-history-escapes-iframe.zip)

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows/Mac  with nwjs-sdk-v0.24.4.

**Comment by rogerwang** [comment]
Chrome manages the history on the tab basis, and there is some discussion on separate iframe history here: https://groups.google.com/a/chromium.org/d/msg/site-isolation-dev/-gzveNDlWIc/yF5mZmwyBgAJ  which is useful for fixing this bug.

**Comment by rogerwang** [comment]
The fix is scheduled to be released in 0.28 beta soon.

**Comment by rogerwang** [comment]
The fix was released in 0.28.0-beta1.
