### ISSUE TITLE
Cannot run nwjs on MacOS due to dyld errors

### ISSUE THREAD

**Issue by xcmaya** [nwjs/nw.js#6137]
NWJS Version : 0.24.4
Operating System : macOS 10.12.6

### Expected behavior

The nwjs should be able to run as described in the 'Getting Started'.

### Actual behavior

nwjs cannot start and outputs the following error messages:

$ /Applications/nwjs.app/Contents/MacOS/nwjs
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Abort trap: 6

### How to reproduce

Just typing '$/Applications/nwjs.app/Contents/MacOS/nwjs' in the terminal.

->

**Comment by Christywl** [comment]
It works fine for me on Mac with nwjs-sdk-v0.24.4, the default nwjs app opens.
`/Users/<my name>/nwjs/nwjs-sdk-v0.24.4-osx-x64/nwjs.app/Contents/MacOS/nwjs `

**Comment by xcmaya** [comment]
I got the solution after spending hours of Googling. I fixed the issue based on the https://stackoverflow.com/questions/17643509/conflict-between-dynamic-linking-priority-in-osx.

Hope it helps for other users.

**Comment by Christywl** [comment]
Thanks for your comment. Close it now
