### ISSUE TITLE
Cannot display emoji characters correctly

### ISSUE THREAD

**Issue by xcmaya** [nwjs/nw.js#6138]
NWJS Version : v0.24.4
Operating System : macOS 10.12.6

### Expected behavior

Emoji characters should be displayed correctly as like in a normal Chrome browser.

### Actual behavior

Now Emoji characters (such as 🏠, ➕,➖ ) cannot be displayed correctly.

### How to reproduce

Just put some emoji characters  (such as 🏠, ➕,➖ )  in the html page.

->

**Comment by Christywl** [comment]
I got the same result on Mac with nwjs-sdk-v0.24.4 and Chrome 60.
my codes:
```
</html>
<head>
 <meta charset='utf-8'>
</head>
🚶, 💇, 💆‍♂️,➕,➖,🏠
</html>
```
![image](https://user-images.githubusercontent.com/20039821/30096698-826f86ae-930c-11e7-926e-0ad52ed65397.png)

**Comment by xcmaya** [comment]
Thanks. It turns out it's caused by the meta tag and inline style for HTML tag.

1: Forgot to add `<meta charset='utf-8'>`. (But it is interesting that a normal Chrome browser can render emoji characters propertly without adding meta tag.
2: Put an inline styling to html tag. (It is interesting that Chrome browser can allow inline style for html tag.)
