### ISSUE TITLE
when I use webview.find api in v0.24.4 , nwjs will crash , this is issue in v0.21.2 don't happen

### ISSUE THREAD

**Issue by SholvaBai** [nwjs/nw.js#6140]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :v0.24.4
Operating System :mac and win

### Expected behavior

<!- What do you think should happen? ->
anything is ok
### Actual behavior

<!- What actually happens? ->
when I use webview.find api in v0.24.4 , nwjs will crash 
### How to reproduce
use webview api 'find'
<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by Christywl** [comment]
It works fine for me on Mac with nwjs-sdk-v0.24.4. Could you please provide your sample to double check this?

**Comment by SholvaBai** [comment]
@Christywl Hi
not crash ,it is block or mean stuck , can't click anything in nwjs

![image](https://user-images.githubusercontent.com/4177125/30307481-0743dcb0-97b1-11e7-8e42-e140ee98ddba.png)

**Comment by Christywl** [comment]
close until there is more information
