### ISSUE TITLE
Is there a way to not show the authentication prompt window ?

### ISSUE THREAD

**Issue by ogo-adp** [nwjs/nw.js#6141]
NWJS Version : >= 0.24
Operating System : Windows

### Expected behavior

We are currently migrating our app from electron to nw.js (faster, and more in sync with chromium releases) but unfortunatly a feature is missing. Our app use integrated Windows authentication. Some clients are not on the domain, and trigger the authentication prompt window ("authentication required" window of chromium) when navigating to an url that returns 401 (unauthorized). Electron provided us a way to bypass this window and just reports the 401 error to the browser (in fact electron does this by defaults). Our app is designed to handle those 401 errors and fallback to another authentication mecanism.

### Actual behavior

The authentification window is always displayed and i didn't found any nw.js/chromium flag to bypass that.

### How to reproduce
Navigate to an url requiring authentication.
See the dialog appearing

**Comment by bjoernneumann** [comment]
@ogo-adp Maybe you can intercept with https://developer.chrome.com/extensions/webRequest#event-onAuthRequired

**Comment by ogo-adp** [comment]
@bjoernneumann  
Many thanks for your response :)

This "mostly" works. Here is the handler to put in code in case other users would need it : `chrome.webRequest.onAuthRequired.addListener(function (details, callback) { return { cancel: true }; }, { urls: ["<all_urls>"] }, ['blocking']);`

When I say 'mostly' there is a limitation in chrome explained in the docs which is "synchronous XMLHttpRequests from your extension are hidden from blocking event handlers in order to prevent deadlocks".

So it does not work with synchronous ajax calls, which is exactly what we happen to do in our app. But I can work around that refactored our code to use async calls. And with async call it DOES work :) 

Great

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
