### ISSUE TITLE
[macOS] Crash when called window nw.Window.get().setProgessBar()

### ISSUE THREAD

**Issue by bambooCZ** [nwjs/nw.js#6143]
Hi,

I've encountered another issue. NWjs crashes when you call nw.Window.get().setProgressBar(0.5) when there is an existing download which already draws the progresspie (Chromium feature?) on dock icon.

```javascript
chrome.downloads.download({ url: "http://releases.ubuntu.com/xenial/ubuntu-16.04.3-desktop-amd64.iso" });
setInterval(
    () => nw.Window.get().setProgressBar(Math.random()) // It crashes here
, 1000); 
```

Tested on NWjs v0.25.0 SDK, macOS 10.12.6

**Comment by panther7** [comment]
Little bit off topic: tested on NWjs v0.22.3, win10 build 15063.540 and works properly.

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.25.0. 
_It doesn't happen on Linux/Windows with nwjs-sdk-v0.25.0_

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
