### ISSUE TITLE
Page with Google IMA HTML5 library becomes unresponsive on load in nwjs v0.25.0

### ISSUE THREAD

**Issue by yss50829** [nwjs/nw.js#6145]
NWJS Version : sdk-0.25.0 (works in earlier versions and in Chrome 61)
Operating System : Win7, x64

### Expected behavior

Page is responsive.

### Actual behavior

Page is unresponsive.

### How to reproduce

1. Launch nw.exe (sdk-0.25.0)
2. Open DevTools
3. Run in console
```
location.href="https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector"
```

### Comments
Unfortunately, i can't provide you any details about this issue because DevTools are unresponsive too. 
Pause with step-by-step execution of scripts didn't help me to find a part of code with something like an infinite loop.
The page [https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) is just an example. This is an issue for any page with Google IMA HTML5 library used. For example: [https://googleads.github.io/videojs-ima/examples/simple/](https://googleads.github.io/videojs-ima/examples/simple/)

**Comment by Christywl** [comment]
Here is my result on Windows 8.1 with nwjs-sdk-v0.25.0, it could be navigate to the url, and have an error:

![image](https://user-images.githubusercontent.com/20039821/30256988-417507ae-96e1-11e7-80f3-326705656ff8.png)

**Comment by yss50829** [comment]
It seems like this issue depends on some other persistent factors of environment. I've tested it on different machines and i've got different results. With some environments it works well, but with others it isn't (page is unresponsive). In most cases it was Win7 x64 (with different results), but i've reproduced this issue also on Win10. So i have no way to tell you exactly what environment is required for reproducing this issue.

**Comment by yss50829** [comment]
I've got a new info. The issue is with HTML5 video (mp4, webm) in general and not with Google IMA.
Video plays in Google Chrome (v61) as well as in NWJS v0.24.2 (and previous), but can't be loaded (no request) and played in 0.25.0. Page becomes unresponsive. 
Do you have any idea what it can be and what I should try?

**Comment by rogerwang** [comment]
Could you please provide the video URL?

**Comment by yss50829** [comment]
For example: [https://s0.2mdn.net/4253510/google_ddm_animation_480P.mp4](https://s0.2mdn.net/4253510/google_ddm_animation_480P.mp4) from [https://s0.2mdn.net/4253510/google_ddm_animation_480P.mp4](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) .
But as i told before it depends on environment, so it can work well in your case.

**Comment by Christywl** [comment]
I try on my Windows 10/Windows 7 with nwjs-sdk-v0.25.3, the video also works fine.
