### ISSUE TITLE
require ali-oss node_modules and package to exe after, excute it without my project

### ISSUE THREAD

**Issue by zxc583700871** [nwjs/nw.js#6148]
NWJS Version :v0.25.0 and 0.14.7
Operating System :windows7

package exe after no project excute

### Actual behavior

package exe after no project excute

### How to reproduce

install ali-oss node_modules
package any project to *.exe
excute this exe

**Comment by rogerwang** [comment]
Please use English only in this project so all users can read.

**Comment by Christywl** [comment]
I can't reproduce  this issue on Windows 10 with nwjs-sdk-v0.25.0.
package.json:
```
{
  "name": "6148",
  "version": "0.1.0",
  "main": "index.html",
  "dependencies": {
    "ali-oss": "^4.10.1"
  }
}
```
index.html:
```
<script>
var oss = require('ali-oss');
var store = oss({
  accessKeyId: 'your access key',
  accessKeySecret: 'your access secret',
  bucket: 'your bucket name',
  region: 'oss-cn-hangzhou'
});
console.log(oss);
console.log(store);
</script>
```
Use `nw-builder` to build a win64 nwjs app: `nwbuild ..\6148 -p win64 -v 0.25.0 -o ..\6148`
Generate a `6148.exe`, double-click it and launch the app:
![image](https://user-images.githubusercontent.com/20039821/30265654-5b522462-970f-11e7-892b-596533a09883.png)

**Comment by zxc583700871** [comment]
@Christywl   but nwbuild is compress all the files into a single file,this file too big.I just compress code file,so i use 'copy /b nw.exe+app.nw app.exe',but it cannot excute...

**Comment by Christywl** [comment]
1. Package `index.html/package.json/node_modules` into a zip file and rename it as `app.nw`, and put it in the same folder as nw.exe. 
2. Run the cmd `copy /b nw.exe+package.nw app.exe`.
3. Double-click app.exe

It also works fine for me.
![image](https://user-images.githubusercontent.com/20039821/30303491-128c0f86-979b-11e7-87d8-2dbfe32dda34.png)

**Comment by zxc583700871** [comment]
@Christywl   As you said, I didn't succeed either. Could you show me the hierarchy and configuration files?

**Comment by zxc583700871** [comment]
@Christywl Can you tell me email? I'll send you the zip file

**Comment by Christywl** [comment]
There is no extra configuration file in my app. My codes have posted in my previous comment. `npm install ali-oss --save` and package all the files into a zip file. 
And I think your zip file may be wrong. Please make sure you package all your files(package.json/index.html/node_modules) into a zip file directly and rename to `app.nw`. DO NOT package a folder(including package.json/index.html/...) into a zip file.
**app.nw
 --node_modules
 --index.html
 --package.json**

http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-option-2-zip-file

> You can package all the files into a zip file and rename it as package.nw.

**Comment by zxc583700871** [comment]
@Christywl  Finally. It's a CNPM problem, not using the NPM installation module. Thank you for your patience, and follow your steps, I found the problem.

**Comment by Christywl** [comment]
@zxc583700871 , is it still reproduced for you now?

**Comment by Christywl** [comment]
close until there is more information
