### ISSUE TITLE
nw.Window.open callback get undefined

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6149]
```javascript
nw.Window.open('chrome-devtools://devtools/bundled/inspector.html', {
  width: 799,
  height: 799
}, function (win) {
  win.on('closed', function(){
    if (that.debugWin == this) {
      that.debugWin = null
    }
  })
})
```
in callback func  win is undefined
in version 24.4

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.25.0.

**Comment by rogerwang** [comment]
The chrome devtools has to be opened in a new process, where objects cannot refer to each other across process boundaries. See the workarounds and merge with #4418
