### ISSUE TITLE
console.log from node module not showing in webkit console or stdout

### ISSUE THREAD

**Issue by chhu** [nwjs/nw.js#6151]
NWJS Version : 0.25 SDK (0.24 as well)
Operating System : Linux

### Expected behavior
Output from console.log() appear in devtools and/ or stdout.

### Actual behavior
Silence if console.log called from node module.

### How to reproduce
- make directory node_modules/test in nw path
- create index.js with console.log("SOMETHING")
- run node REPL and say require("test"); --> console.log works as expected
- exit node and run nw, open dev F12
- enter in console require("test"); 
- module loads properly but no output.

Thanks,
C

**Comment by Christywl** [comment]
I think you should right click the app and choose “Inspect Background Page”.
see the doc: http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/#nodejs-modules-debugging

**Comment by chhu** [comment]
Should have read the manual... 
Thank you!
