### ISSUE TITLE
crashed nwjs 0.14.7 in mac osx ,get Exception Type: EXC_BREAKPOINT (SIGTRAP)

### ISSUE THREAD

**Issue by hxfdarling** [nwjs/nw.js#6155]
NWJS Version :0.14.7
Operating System :mac osx 10.12.6

### Expected behavior

crashed

### Actual behavior

normal

### How to reproduce
I click a input dom and got crashed

### report
Process:               nwjs [1147]
Path:                  /Applications/moa.app/Contents/MacOS/nwjs
Identifier:            com.moa.pc
Version:               1.0.10 (2661.102)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nwjs [1147]
User ID:               501

Date/Time:             2017-09-14 11:08:56.702 +0800
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        5846A6A8-0B23-FBEC-56B1-6F773CBDC1C7

Time Awake Since Boot: 5100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   io.nwjs.nw.framework          	0x0000000107a495a1 0x107594000 + 4937121
1   io.nwjs.nw.framework          	0x0000000107a62397 0x107594000 + 5038999
2   io.nwjs.nw.framework          	0x0000000107a7d6f3 0x107594000 + 5150451
3   io.nwjs.nw.framework          	0x0000000107a7e3b5 0x107594000 + 5153717
4   libsystem_malloc.dylib        	0x00007fffe3c5f282 malloc_zone_malloc + 107
5   libsystem_malloc.dylib        	0x00007fffe3c5e200 malloc + 24
6   com.apple.HIToolbox           	0x00007fffcdb198bb -[IMKInputSession _coreAttributesFromRange:whichAttributes:completionHandler:] + 61
7   com.apple.HIToolbox           	0x00007fffcdb1b939 -[IMKInputSession attributedSubstringFromRange:completionHandler:] + 186
8   com.apple.HIToolbox           	0x00007fffcdb0b137 __61-[IMKInputSession imkxpc_attributedSubstringFromRange:reply:]_block_invoke + 530
9   com.apple.CoreFoundation      	0x00007fffce37517c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
10  com.apple.CoreFoundation      	0x00007fffce355f84 __CFRunLoopDoBlocks + 356
11  com.apple.CoreFoundation      	0x00007fffce355ac6 __CFRunLoopRun + 1878
12  com.apple.CoreFoundation      	0x00007fffce355114 CFRunLoopRunSpecific + 420
13  com.apple.HIToolbox           	0x00007fffcdaf219e -[IMKInputSessionXPCInvocation invocationAwaitXPCReply] + 606
14  com.apple.HIToolbox           	0x00007fffcdaf4750 -[IMKInputSession activate] + 3471
15  com.apple.HIToolbox           	0x00007fffcdaa87ab IMKInputSessionActivate + 36
16  com.apple.HIToolbox           	0x00007fffcdaa7b3c ActivateInputMethodInstance + 100
17  com.apple.HIToolbox           	0x00007fffcda9bbcc utActivateInputMethod + 45
18  com.apple.HIToolbox           	0x00007fffcda9b735 utActivateIM4Document + 72
19  com.apple.HIToolbox           	0x00007fffcda9b5ad utOpenActivateThisDocsInputMethod + 125
20  com.apple.HIToolbox           	0x00007fffcd8c9e09 MyActivateTSMDocument + 1687
21  com.apple.AppKit              	0x00007fffcbf9288d -[NSTextInputContext activate] + 284
22  com.apple.AppKit              	0x00007fffcc823ec2 +[NSTextInputContext currentInputContext_withFirstResponderSync:] + 362
23  com.apple.AppKit              	0x00007fffcbe50e42 -[NSApplication updateWindows] + 96
24  io.nwjs.nw.framework          	0x000000010abd18f9 0x107594000 + 56875257
25  io.nwjs.nw.framework          	0x000000010abc550b 0x107594000 + 56825099
26  io.nwjs.nw.framework          	0x000000010abb53b9 0x107594000 + 56759225
27  io.nwjs.nw.framework          	0x00000001084b19e8 0x107594000 + 15849960
28  io.nwjs.nw.framework          	0x0000000107a4a80b 0x107594000 + 4941835
29  io.nwjs.nw.framework          	0x0000000107a6c923 0x107594000 + 5081379
30  io.nwjs.nw.framework          	0x0000000107a6cbfc 0x107594000 + 5082108
31  io.nwjs.nw.framework          	0x0000000107a6cdeb 0x107594000 + 5082603
32  io.nwjs.nw.framework          	0x0000000107a3eed1 0x107594000 + 4894417
33  io.nwjs.nw.framework          	0x0000000107a62f5a 0x107594000 + 5042010
34  io.nwjs.nw.framework          	0x0000000107a3e8d4 0x107594000 + 4892884
35  com.apple.CoreFoundation      	0x00007fffce375321 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
36  com.apple.CoreFoundation      	0x00007fffce35621d __CFRunLoopDoSources0 + 557
37  com.apple.CoreFoundation      	0x00007fffce355716 __CFRunLoopRun + 934
38  com.apple.CoreFoundation      	0x00007fffce355114 CFRunLoopRunSpecific + 420
39  com.apple.HIToolbox           	0x00007fffcd8b5ebc RunCurrentEventLoopInMode + 240
40  com.apple.HIToolbox           	0x00007fffcd8b5cf1 ReceiveNextEventCommon + 432
41  com.apple.HIToolbox           	0x00007fffcd8b5b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
42  com.apple.AppKit              	0x00007fffcbe4ea54 _DPSNextEvent + 1120
43  com.apple.AppKit              	0x00007fffcc5ca7ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
44  com.apple.AppKit              	0x00007fffcbe433db -[NSApplication run] + 926
45  io.nwjs.nw.framework          	0x0000000107a3f666 0x107594000 + 4896358
46  io.nwjs.nw.framework          	0x0000000107a3ed24 0x107594000 + 4893988
47  io.nwjs.nw.framework          	0x0000000107a82283 0x107594000 + 5169795
48  io.nwjs.nw.framework          	0x000000010761e608 0x107594000 + 566792
49  io.nwjs.nw.framework          	0x000000010a9c30b7 0x107594000 + 54718647
50  io.nwjs.nw.framework          	0x000000010a9c5682 0x107594000 + 54728322
51  io.nwjs.nw.framework          	0x000000010a9beecd 0x107594000 + 54701773
52  io.nwjs.nw.framework          	0x0000000107a00c18 0x107594000 + 4639768
53  io.nwjs.nw.framework          	0x0000000107a000c6 0x107594000 + 4636870
54  io.nwjs.nw.framework          	0x0000000107596b12 ChromeMain + 66
55  com.moa.pc                    	0x0000000107505d52 main + 530
56  com.moa.pc                    	0x0000000107505b34 0x107505000 + 2868

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac 10.12.6 with nwjs v0.14.7 and 0.25.0.

**Comment by hxfdarling** [comment]
My app crashes frequently for one user, though, who was kind enough to send crash reports
I can not reproduce on my Mac 10.12.6

**Comment by rogerwang** [comment]
It's recommended to use the latest version. 0.14 branch is only for legacy OS versions.

**Comment by rogerwang** [comment]
close until more information is available.
