### ISSUE TITLE
Capture part of DOM. Is it possible?

### ISSUE THREAD

**Issue by OReshetnikov** [nwjs/nw.js#6156]
Hi, 
I read http://docs.nwjs.io/en/latest/References/Window/#windowgetwindow_object and can't understand why nw.Window.get(); and nw.Window.get(iframe.contentWindow); have the same values?
Can you suggest how I can capture part of DOM elements (iframe) into base64?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
