### ISSUE TITLE
capturePage crashes if other app has focus on OSX

### ISSUE THREAD

**Issue by DjulLau** [nwjs/nw.js#6157]
NWJS Version : 0.25.0
Operating System : OS X El Capitan (10.11.6) 

### Expected behavior

capturePage should be able to capture window even if other app has focus

### Actual behavior

capturePage crashes if other app has focus

### How to reproduce

```javascript
        var wnd = nw.Window.get();
        wnd.showDevTools();
        const count = 10;
        const timeout = 2000;
        var counter = 0;
        var interval = setInterval(() => {
            wnd.capturePage((buffer) => {
                var data = buffer.replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
                ++counter;
                require("fs").writeFile("capture" + counter + ".png", data, 'base64');
                console.debug("Capture " + counter + "/" + count);
                if (counter >= count) {
                    clearInterval(interval);
                }
            });
        }, timeout);
```
- Run the code
- Wait for a few captures
- Focus on something else (like a finder window) for a few seconds
- Look at the error in the console

>Error in response to nw.currentWindowInternal.capturePageInternal: TypeError: Cannot read property 'replace' of undefined

Same test on windows 7 works as expected.

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.25.2.
_It works fine on Linux/Windows._

**Comment by rogerwang** [comment]
I can't reproduce this in latest 0.26.0. Please verify @Christywl

**Comment by Christywl** [comment]
@rogerwang , I also can't reproduce it with 0.26.0.
