### ISSUE TITLE
OSX - 0.26.0beta1-sdk not completing startup as standalone without app.

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6158]
OSX 10.11.6  El Capitan

Previous beta1 build works fine but latest won't start fully - activity monitor shows nwjs and one helper only, no window opens, no crash report appears and nwjs just stays in dock until it is manually quit.
Tried clearing nwjs appdata folder but still fails

OK -
Index of /live-build/09-08-2017/nw26-1e39c16-01ac9f1-1fa0ffe-3ce2582/v0.26.0-beta1/

FAIL -
Index of /live-build/09-14-2017/nw26-1e39c16-a34cdca-cc6a0af-f5e1aad/v0.26.0-beta1/

Ah - same thing with the latest 0.25.1 just posted - previous build OK

FAIL -
Index of /live-build/09-15-2017/nw25-9f74fd7-c1cff1d-5fc9423-3a82e10/v0.25.1/

**Comment by GnorTech** [comment]
Thanks for reporting. This was due to Node update to 8.5.0. It's now fixed in both branches and will be available in the next build.
