### ISSUE TITLE
Signing Mac Application

### ISSUE THREAD

**Issue by tommoor** [nwjs/nw.js#616]
It would be great to see something in the Wiki on signing mac applications. I'm currently attempting this but am getting errors that the app is already signed and that the signature is invalid (not surprising).

Has anyone managed to do this?

Seems like quite an important part of the distribution steps

**Comment by thekarel** [comment]
I had a lot of `code failed to satisfy specified code requirement(s)` errors when using @timhaak's script. Turns out, I had to include 

```
export CODESIGN_ALLOCATE="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate"
```

Based on [this post](http://blog.hoachuck.biz/blog/2013/10/29/codesign-useful-info-in-xcode-5-dot-0-1/)

**Comment by ericsaboia** [comment]
In addition to @timhaak script, I had to codesign some extra files: 

```
codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/node-webkit Helper EH.app/Contents/Resources/crash_report_sender.app"
codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/node-webkit Helper NP.app/Contents/Resources/crash_report_sender.app"
codesign --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/node-webkit Helper.app/Contents/Resources/crash_report_sender.app"
```

Note that you need to codesign all .app files. Run find apppath/appname.app -iname "*.app" to be sure you're covering everything.

**Comment by stephan-nordnes-eriksen** [comment]
Thanks a lot @timhaak! I had to do a few changes in the newer versions, as the `node-webkit` is changed to `nwjs`, but after that I was able to sign my app :)

**Comment by timhaak** [comment]
Glad this is still helping :)
