### ISSUE TITLE
NW crash when do debugging on NWJC snapshot

### ISSUE THREAD

**Issue by xcmaya** [nwjs/nw.js#6160]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.25
Operating System : macOS 10.12.6

### Expected behavior

I compiled the source code to binary using NWJC. The app can run properly. But when I do debugging in the devTool, the whole app will crash immediately.

The output on the terminal is the following:

`
Received signal 11 SEGV_MAPERR 00053f39f045
 [0x000109f8d55c]
 [0x000109f8d451]
 [0x7fffb6a74b3a]
 [0x053f4d702311]
 [0x0001092c124e]
[end of stack trace]
.....
`

### How to reproduce
1. Load an app which uses a binary snapshot generated from NWJC
2. Open Devtool.
3. Try move mouse to hover a variable to check it's value (or type some class names in the console), the app will crash.

**Comment by Christywl** [comment]
Seem it works fine on my Mac with nwjs-sdk-v0.25.0. Could you please upload your tests to reproduce your issue?

**Comment by noviwiden** [comment]
Can it be related to this? #6061

**Comment by Christywl** [comment]
Use the codes in https://github.com/nwjs/nw.js/issues/6061#issuecomment-329559500, I can reproduce the crash issue on Mac with nwjs-sdk-v0.25.2. i think they'are similar.

**Comment by rogerwang** [comment]
merge with #6061

**Comment by xcmaya** [comment]
Hello Roger, 

I found that the crash issue is still there. Attached please find the source files to reproduce the crash.

Step 1. Run nwjs to load the application.
Step 2. Open the DevTool and type "TestCrash." in the console. It will crash.

(I just tested the latest nw.js v0.25.4 on macOS 10.13. If you still cannot reproduce it, I will upload a video after.)

Thank you!

[nwjs_crash_bug.zip](https://github.com/nwjs/nw.js/files/1367115/nwjs_crash_bug.zip)

**Comment by xcmaya** [comment]
Hello, could we re-open this issue? Or need I open a new issue?

**Comment by Christywl** [comment]
I use your attached zip file and can't reproduce this issue on my Mac 10.13 with nwjs-sdk-v0.25.4. The app doesn't crash.
<img width="1280" alt="screen shot 2017-10-11 at 10 27 19 am" src="https://user-images.githubusercontent.com/20039821/31419600-480bc962-ae02-11e7-9f9b-f424f05cb727.png">

**Comment by noviwiden** [comment]
I tested the attached zip on Windows 10 with NW.js 0.25.4-sdk and can't reproduce it here either. The functions from the TestCrash class are running as expected.
Is the binary compiled with the 0.25.4-sdk version of nwjc ?

**Comment by Mann90** [comment]
Yes. I built the binary using 0.25.4-sdk of nwjc. 

Whenever I type 'TestCrash' in the console, it will crash immediately as shown in the following screenshot. (There are some warnings and errors messages in the terminal as shown in the screenshot.)

Since Roger Wang mentioned that this could be the same issue to #6061. I'll test on the next release after.

Thank you!

<img width="1141" alt="screen shot 2017-10-12 at 7 33 08 pm" src="https://user-images.githubusercontent.com/8889106/31523893-44003154-af84-11e7-9c18-df92b2ff248b.png">

**Comment by xcmaya** [comment]
The binary is built with the  0.25.4-sdk version of nwjc. Now it crashes whenever typing the 'TestCrash' in the console. The following screenshot shows some output in the terminal.

Since Roger mentioned that it could be fixed in the next release, I will test it on next release.

Thank you.

<img width="1141" alt="screen shot 2017-10-12 at 7 33 08 pm" src="https://user-images.githubusercontent.com/23344980/31524153-d15a8c74-af85-11e7-980a-bff8b72ffb69.png">

**Comment by rogerwang** [comment]
@xcmaya we couldn't reproduce with your case. Could you please provide the crash dump file?

**Comment by rogerwang** [comment]
close until more information is available

**Comment by xcmaya** [comment]
I confirm that this issue has been fixed in the v0.26. Thanks.
