### ISSUE TITLE
Window Keeping Aspect Ratio

### ISSUE THREAD

**Issue by jaehayoo** [nwjs/nw.js#6161]
I'm building nw.js app and I need to be able to resize the window keeping the aspect ratio.

Is there any good solution?
Is there any chromium-args to keep the aspect ratio?
or Is there any plan to add field in manifest package.js?

I read issue lists posted by another guys. Buy, I could not search the solution.

Please help me.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by jaehayoo** [comment]
Hi, I asked same question in your mailing list : https://groups.google.com/forum/#!topic/nwjs-general/jllQY_3HGf8

Please answer my question in mail or here.
Thanks!

**Comment by jaehayoo** [comment]
Is there any update?
I could not receive the answer from mailing list.
I am just wondering the plan for adding the function to keep aspect ratio of window.

Thanks,

**Comment by darkguy2008** [comment]
So... nothing yet?

**Comment by Watunder** [comment]
A temporary implementation, it work with frameless window
https://gist.github.com/Watunder/aabc136658f44c49a4c9f4986e23a9a3

**Comment by ayushmanchhabra** [comment]
> A temporary implementation, it work with frameless window https://gist.github.com/Watunder/aabc136658f44c49a4c9f4986e23a9a3

```js
let resizeTimeout;
let lastWidth = 0;
let lastHeight = 0;
let widthChanged = false;
let heightChanged = false;
let aspectRatio = 16 / 9;

const win = nw.Window.get();

win.on('resize', () => {
    clearInterval(resizeTimeout);
    resizeTimeout = setInterval(() => {
        win.setResizable(true);
        widthChanged = Math.abs(lastWidth - win.width) >= 2 * (1 / aspectRatio);
        heightChanged = Math.abs(lastHeight - win.height) >= 2 * (aspectRatio);

        if (widthChanged) {
            lastWidth = win.width;
            lastHeight = Math.floor(lastWidth * 1 / aspectRatio);
        }

        if (heightChanged) {
            lastHeight = win.height;
            lastWidth = Math.floor(lastHeight * aspectRatio);
        }

        if (widthChanged || heightChanged) {
            win.resizeTo(lastWidth, lastHeight);
            win.setResizable(false);
        }
    }, 1);
});
```
