### ISSUE TITLE
nw.js scrollbar

### ISSUE THREAD

**Issue by Ascolon** [nwjs/nw.js#6162]
Hey. Not a big problem with a scrolled window.
How do I disable scrolling at the window itself and turn it on in the browser. Or can I configure the scrolling of the window
I made my buttons to close the window and so the scrolling does not look correct
![screen](https://user-images.githubusercontent.com/28980152/30523264-b92e9466-9bf7-11e7-8e29-02d79fa1f82a.png)

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
