### ISSUE TITLE
NWjs stopped working on my system, regardless of version or reboots

### ISSUE THREAD

**Issue by koobazaur** [nwjs/nw.js#6163]
I got the latest build and copied my HTML files over and accidentally the (renamed) nw.exe as well. I ran the outdated .exe with all the new version files/dlls, and now, for some reason,  that version of NWjs will not run at all on my computer. I tried a backup, a previous stable release deployed and tested in a whole different folder I didn't even touch. I tried rebooting and nothing. What the heck happened? Is there any file cache somewhere that got corrupted?

When I launch, I get debug.log saying:

[0917/130647.111:ERROR:process_info.cc(631)] range at 0x987832fe00000000, size 0x26e fully unreadable
[0917/130647.112:ERROR:process_info.cc(631)] range at 0x9878331e00000000, size 0x26e fully unreadable
[0917/130647.112:ERROR:process_info.cc(631)] range at 0x0, size 0x26e fully unreadable
[0917/130647.268:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol  (0x2ee6)

Please help!

**Comment by koobazaur** [comment]
Update - so the latest build does work now when I re-copied the HTML files and package.json. But my old (stable and separate) build on the older version of nw.js still crashes. What the heck is going on??

**Comment by Christywl** [comment]
Which version did you use and find this issue ? And could you please upload your tests for me to reproduce it?

**Comment by AnthonyBSDE** [comment]
I've same problem : https://github.com/nwjs/nw.js/issues/6164

**Comment by koobazaur** [comment]
Not sure what the previous was, one of the 0.24.x versions. Is there a way I can find out? I can't log it in-code as it crashes on start. And no need for test, even an empty html file crashes.

**Comment by Christywl** [comment]
You could try to delete the app folder in the path `C:\Users\<user name>\AppData\Local`. And If there are crash dump files in `C:\Users\<user name>\AppData\Local\<app name>\User Data\Crashpad\reports`, please upload here.

**Comment by koobazaur** [comment]
Awesome, deleting the appdata local folder for the game solved it. I didn't realize it was creating a folder based on the title in package.json, so I was looking at nwjs folder only
