### ISSUE TITLE
Impossible to read webm file <video>

### ISSUE THREAD

**Issue by AnthonyBSDE** [nwjs/nw.js#6164]
NWJS Version : v0.25.2 SDK (already tried with stable version)
Operating System : Windows 10 64Bits

It's impossible for me to read video .WEBM (same problem for .OGV, .MP4 etc...) with tag <video/> into my app... 
For exemple, if i add this code in my index.html : 
`<video controls src="http://video.webmfiles.org/big-buck-bunny_trailer.webm" type="video/webm"  ></video>`
My App cant run (blank window) and when i quit, debug.log was generated with this content : 

![xcpd3sstpf](https://user-images.githubusercontent.com/5909362/30588538-59e7899a-9d37-11e7-8e1a-37a0606df314.gif)

[0919/122551.375:ERROR:process_info.cc(632)] range at 0x2d30453600000000, size 0x22b fully unreadable
[0919/122551.375:ERROR:process_info.cc(632)] range at 0x2d30455600000000, size 0x22b fully unreadable
[0919/122551.375:ERROR:process_info.cc(632)] range at 0x0, size 0x22b fully unreadable
[0919/122551.457:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: L’URL n’utilise pas un protocole reconnu  (0x2ee6)
I search solution on multiple forum but i never found response...

PS: Sorry for my bad english, i'm french.

**Comment by koobazaur** [comment]
Hey I found that if I change the "name" in package.js then my app is running again. 

My guess, somewhere NWjs stores some temp/cache files indexed by package name and those got corrupted, now it keeps reloading the corrupted files. Maybe?

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8.1/10 with nwjs-sdk-v0.25.2. The video plays normally.
![image](https://user-images.githubusercontent.com/20039821/30623232-dd8478ec-9de8-11e7-8c52-ccd88d6d8ffb.png)

**Comment by Christywl** [comment]
You could delete the user data folder in /Users/<user name>/AppData/Local/<app name>.

**Comment by Christywl** [comment]
close until there is more information
