### ISSUE TITLE
OSX - 0.26.0b1-sdk - file dialog using nwdirectory shows open rather than select

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6165]
OSX 10.11.6  El Capitan

Test project attached - input box set up for folders (nwdirectory) but acting as file open if Choose File method is used. DnD works OK when folder dragged onto input button.
0.25.3 and earlier builds (eg: 0.17.6) are fine. 

0.25.3 - OK
![ok-0_25_3-sdk](https://user-images.githubusercontent.com/11089335/30602778-86bf7bc8-9d5d-11e7-84a1-66af4a2dbd8d.jpg)

0.26.0 - Fail
![fail-0_26_0b1-sdk](https://user-images.githubusercontent.com/11089335/30602800-9383550a-9d5d-11e7-8691-84eca3ea36fc.jpg)

[nwdirectory Bug.zip](https://github.com/nwjs/nw.js/files/1314960/nwdirectory.Bug.zip)

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.26.0-beta1.

**Comment by rogerwang** [comment]
Thanks for reporting. 

This is fixed in git and will be available in the next build.
