### ISSUE TITLE
How to set 'scale' of print ?

### ISSUE THREAD

**Issue by tangyue0924** [nwjs/nw.js#6166]
NWJS Version : 0.24.3
Operating System : Windows 7

### Expected behavior
We can set the `page scale` in the `print options`.

### Actual behavior
Nw.js didn't provide this property to set the page scale.

### How to reproduce
If it's alright, maybe you can update to add this property.

THX!

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
The feature is implemented in git and will be released with 0.26.0.
