### ISSUE TITLE
Exported build crashing

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [nwjs/nw.js#6167]
Hello, i have a problem with a node js project i'm working on.
It's working without any problem, but when i use the command .nwbuild, the exported package take 10second to start and crash instantly.

Thx for your help.

{
  "name": "server.js",
  "version": "1.0.0",
  "description": "SMS",
  "node-main": "./server.js",
  "main": "http://localhost:8080/",
  "scripts": {
    "start": "nodewebkit server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.18.1",
    "bootstrap": "^3.3.7",
    "bson": "^1.0.4",
    "ejs": "^2.5.7",
    "express": "^4.15.4",
    "express-session": "^1.15.5",
    "materialize-css": "^0.99.0",
    "mongodb": "^2.2.31",
    "nwbuild": "0.0.5",
    "request": "^2.82.0",
    "touch": "^1.0.0"
  },
  "devDependencies": {
    "nodemon": "^1.12.1",
    "opn-cli": "^3.1.0"
  },
  "nodejs": true,
  "window": {
    "toolbar": false,
    "width": 1350,
    "height": 900
  }
}

**Comment by Christywl** [comment]
Could you please upload your full test to reproduce this?
