### ISSUE TITLE
Ubuntu navigator.mediaDevices is undefined

### ISSUE THREAD

**Issue by rx4hvn** [nwjs/nw.js#6168]
I have downloaded latest SDK version from [https://nwjs.io/](https://nwjs.io/)
Chrome 61 + Node 8.5.0 and v0.25.2
[https://dl.nwjs.io/v0.25.2/nwjs-sdk-v0.25.2-linux-x64.tar.gz](https://dl.nwjs.io/v0.25.2/nwjs-sdk-v0.25.2-linux-x64.tar.gz)

The problem is that navigaor.mediaDevices is not defined in Linux version. But it seems to be working when I download SDK for windows.

NWJS Version : **0.25.2**
Operating System : 
**Distributor ID: Ubuntu
Description: Ubuntu 14.04.5 LTS
Release: 14.04
Codename: trusty**

I am trying to record a audio using navigaor.mediaDevices 
Unfortunately due to some reason that navigator.mediaDevices is not defined.

I have tested using fresh install but does not seems to be working.

Please help.

**Comment by Christywl** [comment]
I can't reproduce this issue on Linux ubuntu 16.04 with nwjs-sdk-v0.25.2.
![6168](https://user-images.githubusercontent.com/20039821/30731939-cf126be6-9fa2-11e7-9286-e14de85b9c32.png)

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by rx4hvn** [comment]
@Christywl  could you please share the link from where you downloaded this version.

**Comment by Christywl** [comment]
https://dl.nwjs.io/v0.25.2/nwjs-sdk-v0.25.2-linux-x64.tar.gz
