### ISSUE TITLE
Kiosk Mode does not lock app in macOS 10.12+

### ISSUE THREAD

**Issue by mboylan** [nwjs/nw.js#6169]
NWJS Version : v.0.25.2
Operating System : 10.12.16

### Expected behavior

When using 
```
{
  "window": {
    "kiosk": true
  }
} 

```
or 

`gui.Window.get().enterKioskMode(); `

on macOS 10.12+, the app enters full screen but does not prevent the user from quitting the app, switching apps, force quitting the app, etc.

https://github.com/nwjs/nw.js/blob/1c6e8b1f54e440841973ab44cda1ac586a42205d/src/browser/native_window_mac.mm#L810-L820 seems to indicate that these NSApplicationPresentationOptions should be being set for the app, but they do not appear to be taking effect.

### Actual behavior

The app enters full screen mode, but is not locked like a kiosk. I tried the previous workaround of calling enterKioskMode() twice, but that is not working either.

### How to reproduce

1.) Create a small sample project with just package.json and index.html
2.) In the package.json file add window -> kiosk -> true
3.) Run the app
4.) Observe that the app enters full screen but is not locked in any way

Would greatly appreciate any quick fixes or workarounds for this issue. Thanks!

**Comment by Christywl** [comment]
It also doesn't work on Linux with nwjs-sdk-v0.25.2. The app enters full screen but I can still switch to other task.

**Comment by acketon** [comment]
I've also been able to replicate this behavior. In fact, I tried building the app with a nwjs v0.13 release and it had the same issue. However, pre-v0.13 releases don't have this issue and go into Kiosk mode properly on MacOS High Sierra

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by alexanderson1993** [comment]
@rogerwang Thanks for checking this out and getting it fixed! 👍

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/12-29-2017/nw27-732f2d7-3cce4e7-7a24307-547fb57/v0.27.4/
