### ISSUE TITLE
override modal upload window

### ISSUE THREAD

**Issue by dansachelarie** [nwjs/nw.js#6174]
I am working on a project and I am trying to intercept the upload window. I did that and I just create a new div and display some files to upload. Now I am trying to provide the path selected by user to the input type file to actually upload the file to a certain website. I know that it is not possible in javascript. but I am on nwjs, I hope there is maybe a flag to set it to allow me to do that or to install a plugin. Can you help me with that?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
