### ISSUE TITLE
32bit Windows FIN tcp packet sent causing TLS renegotiation

### ISSUE THREAD

**Issue by n3utrino** [nwjs/nw.js#6180]
NWJS Version : 0.20.3-sdk, v0.24.2-sdk
Operating System : Windows 32

### Expected behavior

TCP Connection of a TLS connection should get reused in 32bit nwjs on 32bit Windows by sending keepalives. The same version of Chrome doesn't show this 

### Actual behavior

Nwjs sends a FIN,ACK after it received the data for the http request, causing the tcp socket to close. The next request needs to renegotiate the TLS connection.

### How to reproduce

Open Wireshark capture a request to a server.

32Bit nwjs build on 32Bit Windows will look like this:
```
Client              Server
  |---->---[SYN]----->-|
  |----<---[ACK]--<----|
  |---->--[Data]--<----|
  |---->---[FIN]--->---|
  |----<---[ACK]---<---|
```
on a 32bit  nwjs build on 64Bit Windows
```
Client              Server
  |---->---[SYN]----->-|
  |----<---[ACK]--<----|
  |---->--[Data]--<----|
  |---->--[KEEP]--->---|
  |----<---[ACK]---<---|
  |---->--[KEEP]--->---|
  |----<---[ACK]---<---|
....SOME TIME LATER...
  |----<---[RST]---<---|
```

I tested with the according chromium version and it did NOT send the FIN packets so I assume it has something to do with nwjs.
It's a really strange case.

I am happy to provide more details.

**Comment by Christywl** [comment]
I try this on Windows 32 with nwjs-sdk-v0.27.3-win-ia32, don't see your issue on my device.
1. Open wireshark and get ready to capture
2. Launch nwjs: `nw.exe --url=https://nwjs.io`
3. I just see the [FIN,ACK] and [RSR] packets from the server to the client, don't see the [FIN] packet from the client to the server.

Is this issue still reproduced for you with the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
