### ISSUE TITLE
Memory and CPU with high consume

### ISSUE THREAD

**Issue by edelciomolina** [nwjs/nw.js#6181]
NWJS Version :
Tested with 0.20.20 and 0.25.4

Operating System :
Windows 7 and 10

Hi,
I noted a high consumer of memory and sometimes CPU on my app after running for a period more than 5 hours.
I already did some refactoring to improve that but no good results.
Today I´m using these chromium-args into my app:
"chromium-args": "--disable-device-orientation --user-data-dir='./Cache/' --force-cpu-draw --disable-transparency --disable-plugins --disable-bundled-ppapi-flash --disable-popup-blocking --disable-software-rasterizer --ignore-gpu-blacklist"

I believe that some of these args ae the problem, but I cant discovery. 
To be honest, I don´t know if I´m doing correct, but what I´m trying to do is to have the minimal possible of Memory and CPU used.
Is there a list of chromium-args that can I use or another way to solve it?

Best Regards

![image](https://user-images.githubusercontent.com/4604923/31015604-5ecaaac4-a4f7-11e7-8310-db69fa503314.png)

**Comment by Christywl** [comment]
Could you please upload a sample to reproduce it?

**Comment by edelciomolina** [comment]
Hi @Christywl ,
I appreciate your help, would be great to resolve more fast, but I can´t.
