### ISSUE TITLE
Linux desktop, the page can not enter Chinese

### ISSUE THREAD

**Issue by mynameiswf** [nwjs/nw.js#6183]
Linux desktop, the page can not enter Chinese

NWJS Version :all
**_Operating System :centos7_**

**Comment by Christywl** [comment]
Do you mean that you can't input Chinese character in the input box? It works fine for me on Ubuntu with nwjs-sdk-v0.25.3.

**Comment by yutent** [comment]
你的桌面是哪个 gnome? KDE?

**Comment by rogerwang** [comment]
Please use English in this project so all users can read.

**Comment by yutent** [comment]
The bug [#6117](https://github.com/nwjs/nw.js/issues/6117) is still live, T_T .

**Comment by Christywl** [comment]
Sogou-pinyin also works fine on chrome.

![6183](https://user-images.githubusercontent.com/20039821/31043469-e3a4976c-a5ee-11e7-98f3-d8cc2a135e82.png)

**Comment by mynameiswf** [comment]
centos

**Comment by mynameiswf** [comment]
@Christywl Operating System :centos7

**Comment by Christywl** [comment]
@mynameiswf , I have no Centos device now, does sogou pinyi work for Chrome?

**Comment by mynameiswf** [comment]
@Christywl Sogou-pinyin works fine on chrome.

**Comment by Christywl** [comment]
I setup CentOS 7 in VM and sougou pinyin works fine on nwjs-sdk-v0.26.2 and chrome.
![6183](https://user-images.githubusercontent.com/20039821/32257724-c2f11578-be84-11e7-80d3-8b4f1e01bcca.png)
