### ISSUE TITLE
Linux, Can 't launch app. Multiple open tab (Linux headless) 

### ISSUE THREAD

**Issue by Shanedjafaraly** [nwjs/nw.js#6185]
NWJS Version :
```
root@ns3051770:/home/shane/nws# npm install -g nw
/usr/bin/nw -> /usr/lib/node_modules/nw/bin/nw

> **nw@0.25.4** postinstall /usr/lib/node_modules/nw
> node scripts/install.js
Operating System : **Linux**
```

### Expected behavior
I would like to **launch my appli** (i have an .html with .js include (only a console.log for start).

### Actual behavior

```
root@ns3051770:/home/shane/nws# ./nws --nwapp chromedriver --disable-gpu **--headless** --no-sandbox --disable-infobars --allow-insecure-localhost --dump-dom -disable-multi-display-layout pfhtml/index.html
[1002/131046.897645:ERROR:headless_shell.cc(505)] **Open multiple tabs is only supported when remote debugging is enabled.**
```

or :

```
root@ns3051770:/home/shane/nws# ./nws --disable-gpu --headless --no-sandbox  -disable-multi-display-layout  pfhtml/
[1002/131550.765152:ERROR:headless_shell.cc(132)] Navigation to  failed

```

![sans titre](https://user-images.githubusercontent.com/25584648/31075165-76ee0068-a774-11e7-9b5c-75144a4d4aa8.png)

its same with .directory file. Im sorry, im a little bit new.

Plz help me, thanks

**Comment by Shanedjafaraly** [comment]
there is no **--headless** but --headless (i try to "bold" soz)

**Comment by Shanedjafaraly** [comment]
this work fine in ubuntu. the same file. but not working in headless in linux

**Comment by Christywl** [comment]
Try the above cmd on nwjs-sdk-v0.25.4:
```
lei@lei-dev:~/00_lei/nwjs/build/nwjs-sdk-v0.25.4-linux-x64$ ./nw --nwapp chromedriver --disable-gpu --headless --no-sandbox --disable-infobars --allow-insecure-localhost --dump-dom -disable-multi-display-layout ../../bugs/6185/index.html
[1009/151443.752437:ERROR:headless_shell.cc(505)] Open multiple tabs is only supported when remote debugging is enabled.
```
I add `--remote-debugging-port=9222` in the cmd:
```

lei@lei-dev:~/00_lei/nwjs/build/nwjs-sdk-v0.25.4-linux-x64$ ./nw --nwapp chromedriver --disable-gpu --headless --remote-debugging-port=9222 --no-sandbox --disable-infobars --allow-insecure-localhost -disable-multi-display-layout ../../bugs/6185/index.html
[1009/152147.700385:ERROR:headless_shell.cc(132)] Navigation to  failed
```

**Comment by Shanedjafaraly** [comment]
same error, and i have the last version for linux  0.25.4

`Open multiple tabs is only supported when remote debugging is enabled.`
`Navigation to  failed`

**Comment by damoebius** [comment]
Same error with 0.25.4 on ubuntu

**Comment by rogerwang** [comment]
The `--headless` switch of the NW binary is not supposed to run headless NW app. It's identical with the upstream headless feature, see https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md for the usage.

And see https://github.com/nwjs/nw.js/issues/769#issuecomment-294064358 for our headless plan.
