### ISSUE TITLE
Slow files selection via dialog + error in logs

### ISSUE THREAD

**Issue by oaleynik** [nwjs/nw.js#6187]
NWJS Version : 0.25.4-sdk
Operating System : Darwin Macbook-Pro-0x10.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

### Expected behavior

Fast files selection. No error in logs.

### Actual behavior

More files selected - longer delay observed with the "busy" system indicator instead of mouse pointer.
The following error observed in logs:

```
Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9575aa70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10e824cd8). One of the two will be used. Which one is undefined.
```

### How to reproduce

Add the following to html:
```html
<input type="file" multiple="" accept="image/*">
```
Click on it and select 200+ files.

**Comment by oaleynik** [comment]
```html
<input type="file" multiple="" accept="image/*">
```

**Comment by oaleynik** [comment]
App hangs for a solid 15-20 seconds when I select 200+ files.

**Comment by Christywl** [comment]
It works fine for me on Mac 10.12.6 with nwjs-sdk-v0.25.4. I select 220 images, the app doesn't hang. No errors.

**Comment by oaleynik** [comment]
@Christywl thanks for checking! You are on macOS Sierra, when I am on High Sierra - not sure if this impacts the results.

**Comment by Christywl** [comment]
on MacOS 10.13, I can reproduce this error, but I don't meet the delay issue.
<img width="1280" alt="screen shot 2017-10-11 at 10 41 15 am" src="https://user-images.githubusercontent.com/20039821/31419918-17afe120-ae04-11e7-974b-49a92cea486d.png">

**Comment by oaleynik** [comment]
@Christywl hm, ok. I will keep digging. If I will have the simple app example for you - will ping you here. You can close this issue if not relevant. Thanks!

**Comment by Christywl** [comment]
close until there is more information
