### ISSUE TITLE
Your profile cannot be used because it is from a newer version of NW.js some features may be unavailable

### ISSUE THREAD

**Issue by quantumproducer** [nwjs/nw.js#6188]
NWJS Version : 0.27.3
Operating System : OSX
### Expected behavior

App start normally

### Actual behavior

"your profile cannot be used because it is from a newer version of NW.js some features may be unavailable"

I have to press OK three times before the app will start.

<img width="412" alt="screen shot 2017-10-03 at 18 49 36" src="https://user-images.githubusercontent.com/11827932/31152779-ac03094a-a86b-11e7-80e8-d3d90e5e5619.png">

### How to reproduce

I have to use nw.js version 0.23.7 because that's the latest my dependency https://github.com/greenheartgames/greenworks/releases is compatible with .

I upload sample project that reproduces issue - just run the app on Mac OSX and you'll see the screenshot above

https://github.com/QuantumProductions/nwjs237-error-starting

**Comment by oaleynik** [comment]
You need to delete ~/Library/Application\ Support/<your app name> to clear this warning. I guess you've used newer version of nwjs for development so 0.23.7 would be downgrade.

**Comment by quantumproducer** [comment]
~/rm -rf ~/Library/Application\ Support/nw-demo
~/rm -rf ~/Library/Application\ Support/nwjs

I did, it happens immediately when I run my app again.

**Comment by CrackerakiUA** [comment]
Where is those two files in Windows?

**Comment by Christywl** [comment]
Please refer to http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir

**Comment by haoma2514** [comment]
After deleting it will still be prompted。。

**Comment by Christywl** [comment]
Delete the user data folder: `C:\Users\<your_user_name>\AppData\Local\<app_name_in_manifest>`, it works fine for me.

**Comment by danschumann** [comment]
For me, I had multiple copies of nw.. and after copying `app.zip` -> `app.nw` + `nw`, I copied the `app.exe` into the wrong nw directory.  So, my executable was looking at the wrong DLLs.

**Comment by anurag2911** [comment]
What is the impact of deleting the User data ? Will it cause any issue?

**Comment by JamesMoulang** [comment]
I was having this same issue on OSX, despite not even seeing any relevant folders in the Application Support folder.

I was able to resolve this issue by changing the name field in package.json. Originally it was 'test'. I'm not sure if that was a significant name, or if there are files somewhere that I'm not aware of, that matched the name.

**Comment by anurag2911** [comment]
> I was having this same issue on OSX, despite not even seeing any relevant folders in the Application Support folder.
> 
> I was able to resolve this issue by changing the name field in package.json. Originally it was 'test'. I'm not sure if that was a significant name, or if there are files somewhere that I'm not aware of, that matched the name.

It is a significant name, it is the name of the application which is used at many places.

**Comment by KoNickss** [comment]
what would the fix be in linux?

**Comment by robertocsa** [comment]
I was seeing a message like that when I was starting Postgresql. Then, I have renamed (adding the suffix _OLD) the folders pgadmin and pgadmin4 located at  <usersDriveLetter>:\\Users\<myusername>\AppData\Local and restarted the Postgresql application. Then two new folders were created automatically and the alert message disappeared.
