### ISSUE TITLE
[How] - to start without prompting to click share the screencapture?

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#6189]
How to start without prompting to click share? 

![image](https://user-images.githubusercontent.com/107349/31163688-eebb586e-a8e3-11e7-8dfd-20ed784fca56.png)

Following method always show the share button. **When i define `chromeMediaSourceId: 'screen:0',` it does not work to capture.**

```
  var gui = require('nw.gui');
  gui.Screen.Init();
  gui.Screen.chooseDesktopMedia(["screen"],
    function(streamId) {
      //sourceId = "screen:0";
      var vid_constraint = {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: streamId,
          maxWidth: 1920,
          maxHeight: 1080
        },
        optional: []
      };
      navigator.webkitGetUserMedia({audio: false, video: vid_constraint}, success_func, fallback_func);
    }
  );
```

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
