### ISSUE TITLE
macOS: Window reloadIgnoringCache does not work properly

### ISSUE THREAD

**Issue by HappyStriker** [nwjs/nw.js#6192]
NWJS Version : 0.25.4 with DevTools
Operating System : macOS 10.13 (using an encrypted, case-sensitive APFS disk)

### Expected behaviour

Using nw.Window.get().reloadIgnoringCache() should reload the content of the window without using cached files.

### Actual behaviour

At least inside the DevTools it looks like the page is being reloaded, but changes inside the source files are ignored, so I guess the cache is still used.
Even restarting NWJS does not immediately reload the page without the caches. Calling the reloadIgnoringCache method will work then once after calling it multiple times.

### How to reproduce

package.json:
```
{
   "name": "Test",
   "main": "index.html"
}
```

index.html:
```
<!DOCTYPE html>
<html>
   <head>
      <link rel="stylesheet" href="test.css">
      <script>
         var win = nw.Window.get();
      </script>
   </head>
   <body>
      <h1>Hello World!</h1>
      <input type="button" value="Reload" onclick="win.reloadIgnoringCache();">
   </body>
</html>
```

test.css:
```
html {
   background-color:blue;
}
```

Pressing the Reload button to call the method leads to the describes behaviour. In the test situation I have changed the color of the background inside the test.css and the change will not be applied after pressing the Reload button calling the reloadIgnoreCache method.
This issue only appears on macOS. If have tested it with version 10.13 High Sierra and an encrypted, case-sensitive APFS volume. I do not know if it happens on a different filesystem or previous version of macOS.
Besides of macOS I tested the same situation as well on Windows 10 and CentOS Linux 7 with GNOME Desktop and on these operating systems the describes issue does NOT occur.

Thanks for your time!
Happy Striker

**Comment by Christywl** [comment]
On Mac 10.12.6, nwjs-sdk-v0.25.4:
Open the app, the background is blue, change the color to green, click Reload button, the background changes to green.

**Comment by Christywl** [comment]
close until there is more information
