### ISSUE TITLE
Remove settings button from native notifications on Linux

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#6194]
Hi, I hope this is the right issue tracker for issues regarding nwjs' chromium.src repo...

In #4560, you said you wanted to wait for Chromium to implement native notifications on all platforms instead of re-adding the functionality back to 0.13. Chromium has now finally implemented native notifications on Linux after doing so on macOS a few months ago:

- Linux: Chromium 61 / NWjs 0.25 (https://crbug.com/676220)
- macOS: Chromium 54 / NWjs 0.18 (*I think* it got removed from the `--enable-features=NativeNotifications` feature flag in Chromium 59 / NWjs 0.23) (https://crbug.com/326539)
- Windows: still unsupported (https://crbug.com/516147)

**Now to the issue:**
Native notifications created by Chromium on both macOS and Linux always include a "Settings" action button. In NWjs, clicking this settings button opens a new window with a blank site. This behavior can't be changed or disabled, because it is hardcoded and it is super annoying. Especially since notifications with and without actions can be displayed completely differently on the system. And having such a settings button is confusing for the end user.

**On macOS, you've already disabled the behavior in NWjs 0.25:**

-  https://github.com/nwjs/chromium.src/blame/nw25/chrome/browser/notifications/notification_platform_bridge_mac.mm#L249
- https://github.com/nwjs/chromium.src/commit/223521f6649110b8394313379e18a211f8de5fc8#diff-068696dc76b814f0aa715cb5a9fe4d4bR249 (takes a while to load)

**On Linux, this is still enabled and needs a fix:**

- 0.25: https://github.com/nwjs/chromium.src/blob/nw25/chrome/browser/notifications/notification_platform_bridge_linux.cc#L586-L591
- 0.26: https://github.com/nwjs/chromium.src/blob/nw26/chrome/browser/notifications/notification_platform_bridge_linux.cc#L586-L591

Thanks for your consideration!

**Comment by rogerwang** [comment]
Could you please show some sample to trigger it? I tried some from chrome app notification sample but it doesn't show any settings button under Linux...

**Comment by bastimeyer** [comment]
When using the `window.Notification` API, the settings action will be added to the dbus call on Linux (it doesn't show the settings button on macOS, as it got removed in the linked commit-id above)
```js
new window.Notification( "foo", {
  message: "bar",
  actions: []
});
```

The `window.chrome.notification` API doesn't add a settings button neither on Linux nor on macOS. I was using this API for showing rich notifications on Windows 7 and wasn't aware of the difference in behavior on Linux after the recent changes.
```js
window.chrome.notifications.create( "id", {
  type: "basic",
  title: "foo",
  message: "bar",
  iconUrl: "file:///path/to/icon"
})
```

*(remember to set the `--enable-features=NativeNotifications` chromium parameter)*

**Comment by rogerwang** [comment]
I don't see any settings button `window.Notification`. Maybe it's added by your Desktop environment?

![screen sharing picture 24 october 2017 at 2 14 20 pm gmt 8](https://user-images.githubusercontent.com/165401/31927236-c03930d2-b8c5-11e7-8320-0bd205853d9a.png)

**Comment by rogerwang** [comment]
I don't see any settings button with `window.Notification` and `--enable-features=NativeNotifications`. maybe it's added by your linux desktop environment?
![screen sharing picture 24 october 2017 at 2 14 20 pm gmt 8](https://user-images.githubusercontent.com/165401/31927337-38841cd2-b8c6-11e7-8ec7-df2ad989b3e1.png)

**Comment by rogerwang** [comment]
CC @Christywl can you verify?

**Comment by bastimeyer** [comment]
No, NWjs adds the settings button and reacts to clicks with opening the blank Chromium settings window.
Run this to monitor the freedesktop notifications dbus interface:
```
$ gdbus monitor --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications
Monitoring signals on object /org/freedesktop/Notifications owned by org.freedesktop.Notifications
The name org.freedesktop.Notifications is owned by :1.60
/org/freedesktop/Notifications: org.freedesktop.Notifications.ActionInvoked (uint32 171, 'default')
/org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed (uint32 171, uint32 2)
/org/freedesktop/Notifications: org.freedesktop.Notifications.ActionInvoked (uint32 172, 'settings')
/org/freedesktop/Notifications: org.freedesktop.Notifications.NotificationClosed (uint32 172, uint32 2)
^C
```

```js
// normal click here
new Notification( "foo", {messge: "bar", actions: [] } );
// settings click here
new Notification( "foo", {messge: "bar", actions: [] } );
```

**Comment by bastimeyer** [comment]
@rogerwang 
The screenshot you've posted seems to be showing a Chromium rich notification, unless freedesktop notifications get rendered the same way on your system.

**Comment by rogerwang** [comment]
Maybe it fallbacks to rich notification somehow. Anyway I'll disable the code you referred to.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by deltapath-eric** [comment]
@rogerwang 
Sorry to bring this up and make the issues across but may i have a little attention and can you please also take a look on #6020 if possible ?
As I am facing that issue which also related to the notification...

Many thanks for the great work.
