### ISSUE TITLE
Debugging Crash dump?

### ISSUE THREAD

**Issue by quantumproducer** [nwjs/nw.js#6196]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.23.7
Operating System : OSX

### Expected behavior

Not crash

### Actual behavior

Crashes, leaves a crash dump (originally .dmp file), attached

How do I parse what's going on? I can trigger the crash reliably from my code but I don't know which part of my code causes the crash.

[97b59c38-f636-4368-8e57-ddbc2fc8a821.txt](https://github.com/nwjs/nw.js/files/1364702/97b59c38-f636-4368-8e57-ddbc2fc8a821.txt)

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce the crash issue?

**Comment by quantumproducer** [comment]
@Christywl :/ trying to debug a simpler example. I have a game that calls the greenworks library and it crashes if Steam isn't running. But when I reproduce just that call, not crashing.

**Comment by quantumproducer** [comment]
It is definitely crashing on using the greenworks API

var s = function(a, b, c) {
        console.log("yes" + a + "" +b + "" + c);
    }

    var e = function(a, b, c) {
      console.log("nope.. !?" + a + "" +b + "" + c);
    }
    console.log("OH BOY, ACHIEVING");
    setTimeout(function() {
      window.greenworks.activateAchievement(n, s, e);
    }, 5000);

but when I try a simpler example, it will not crash, unfortunately. Testing further but if I can't find anything -- this is probably more on the greenworks library than NW.js.
