### ISSUE TITLE
crash in webview - no info available

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6197]
I'm opening various simple web pages in a webview, but many of them crash the webview directly and a sad face is displayed.

When a webview is ok I can right click and call its dev tools and inspect it all but when it is crashed its inspector is no longer available.

I tried chrome://inspect#apps - but nothing in there and also nothing logged in consoles about any crashes - the webview just crashes (probably due some javascript errors - but I can't see them)

======== TEMPLATE BUG FORM ========

NWJS Version : 0.24.4
Operating System : Mac OSX 10.12.6

### Expected behavior

We should be able to see the errors in the crashed webview

### Actual behavior

webview crashes and sad face icon is displayed and nothing can be done any more with it

### How to reproduce

well just open a webview in nwjs and make it crash

**Comment by gpetrov** [comment]
After further investigation I did found some messages in the chrome_debug.log

```
[26682:775:1007/184313.693476:VERBOSE1:render_process_host_impl.cc(2877)] Blocked URL file:///Users/username/Documents/somesite/index.html
[26682:34563:1007/184313.699372:VERBOSE1:resource_dispatcher_host_impl.cc(2658)] Killed renderer for illegal origin: file://
[26682:34563:1007/184313.699412:ERROR:bad_message.cc(23)] Terminating renderer for bad IPC message, reason 95
[26682:34563:1007/184313.827400:VERBOSE1:resource_dispatcher_host_impl.cc(2658)] Killed renderer for illegal origin: file://
[26682:34563:1007/184313.827434:ERROR:bad_message.cc(23)] Terminating renderer for bad IPC message, reason 95
```

Is the webview process all crashing because of not allowed url? That seem really weird to me.

in my package.json I have allowed everything:

```javascript
"webview": {
    "partitions": [
      {
        "name": "trusted",                                                                                                                                                                           
        "accessible_resources": ["*"]
      }
    ]
  },
  "chromium-args": "--allow-file-access-from-files --disable-web-security --enable-logging --v=1",
```

Any ideas - what this might be @rogerwang ?

**Comment by gpetrov** [comment]
maybe related to https://bugs.chromium.org/p/chromium/issues/detail?id=627564
and https://chromium.googlesource.com/chromium/src/+/4bdb4f88f8197bebe32ce3480a3851201f648a8b

as I'm indeed using loadDataWithBaseURL and the crash seems to happen when loading some css font files.

Is that not merged with the current branch yet? I just tested with 0.25.4 and the same crash still occurs

**Comment by gpetrov** [comment]
after changing the "**accessible_resources**": **```["*://*/*"]```** seems all solved ... but still weird, normally the base url from the **loadDataWithBaseURL** should take care of the permissions

```
"webview": {
    "partitions": [
      {
        "name": "trusted",                                                                                                                                                                           
        "accessible_resources": ["*://*/*"]
      }
    ]
  }
```

**Comment by rogerwang** [comment]
Anyway it should not crash. Could you please provide a sample?

**Comment by Christywl** [comment]
close until there is more information
