### ISSUE TITLE
Chrome 61+ comes with ES6 support, but "import" is not working in NWJS

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6198]
NWJS Version : SDK version 26.0 b1
Operating System : Win7 x64

### Expected behavior

ES6 import should work properly as defined in the spec.
Short summary: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

### Actual behavior

An error is thrown in the console and import fails:

> Uncaught SyntaxError: Unexpected token import

### How to reproduce

basic NWJS template with the only JS code inside the HTML file being:

````html
<html>
    <head>
    </head>
    <body>
        <script>
            import * as testModule from 'random';
        </script>
    <body>
</html>
````

`random` is just an example and does not need to exist since import fails regardless.

**Comment by rogerwang** [comment]
chrome 61 supports import via script tag. The keyword will be supported in chrome 63.
