### ISSUE TITLE
changing webkit app region is not taking effect until the app repaints

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6201]
NWJS Version : SDK 26.0beta1
Operating System : Win7 x64

### Expected behavior

When setting or unsetting the `-webkit-app-region: drag` on an element the app should be draggable when dragging that element or stop dragging when the property is unset.

### Actual behavior

The property change only takes effect when there is a full page repaint. (i.e. font-family change, window resize, etc.)

### How to reproduce

With a basic template containing a simple HTML page and the window set to frameless, open the developer tools and set the css attribute `-webkit-app-region: drag` for the `html` or `body` element.
Try to drag the window by dragging the body element on that page and it will not drag.
Resize the app window and try dragging again, the page will now drag.
Unset/remove that property and drag the window again, it keeps dragging when it shouldn't since the property is no longer enabled.
Resize the app window and try dragging again, the page will now no longer drag.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.25.4.

**Comment by rogerwang** [comment]
@Christywl could you please share your sample?

**Comment by Christywl** [comment]
I just use a simple app to reproduce this. Launch the app and open the devtools, add `-webkit-app-region: drag` in `element.style` for `body` element. Drag the window in the body element, the window can't be dragged. Resize the window and try again, the window can be dragged.
package.json:
```
{
  "name": "6201",
  "main": "index.html",
  "window":{
   "frame":false
  }
}
```
index.html:
```
<!DOCTYPE html>
<html>
<title>HTML Tutorial</title>
<body>

<h1>This is a heading</h1>
<p>This is a paragraph.</p>

</body>
</html>
```
![image](https://user-images.githubusercontent.com/20039821/31597360-8430dc1c-b27a-11e7-9b91-d9e4cda1dcc7.png)

**Comment by rogerwang** [comment]
@Christywl could you please try whether it reproduces with a Chrome App in Chrome browser?

**Comment by Christywl** [comment]
Yes, this issue also appears with a Chrome App in Chrome 63.

**Comment by rogerwang** [comment]
@Yonezpt Please report it to the Chromium project. Thanks. https://bugs.chromium.org/p/chromium/issues/list

**Comment by Yonezpt** [comment]
Posting issue here for tracking purposes: https://bugs.chromium.org/p/chromium/issues/detail?id=803361

**Comment by Yonezpt** [comment]
Closing this since it is related to Chromium and not NWJS and the bug was marked as `WONTFIX` with the intent to remove the `webkit-app-region`.
