### ISSUE TITLE
NW.JS preventing shutdown on Mac

### ISSUE THREAD

**Issue by Silve2611** [nwjs/nw.js#6202]
NWJS Version : v0.25.3-osx-x64
Operating System : OSX 10.12.5

NWJS is preventing the shoutdown or restart. This happens if the close function is overwritten. Sometimes it is useful to only hide the program and not close ist to keep batchs running in the background. Also the app stays loaded as it is only hidden. However it does not respond correctly to apples restart/shutdown. 

### Expected behavior

The Program should close on restart or shutdown

### Actual behavior

A Popup appears that nwjs stopped the shutdown or restart

### How to reproduce

Make a nw.js application on mac. Add the following code
```
var win = nw.Window.get();
/**
 * Overwrite of the close function. It only hides so the batches can keep running
 */
win.on('close', function() {
  console.log('closed');
  win.hide(); // Pretend to be closed already
  win.setShowInTaskbar(false);
  //win.reload(3);
});
```

By the way. I encountered the same problems with many programs running electron. It is probably because the app is catching the close event.

**Comment by Christywl** [comment]
You could try to add `this.close(true)` to really close the window, see http://docs.nwjs.io/en/latest/References/Window/#event-close

**Comment by Silve2611** [comment]
Thx for the reply but this is not the problem. I can close the window if i want to. The Problem is that the system can't close the window which result in a message that "nwjs stopped the shutdown"

**Comment by Christywl** [comment]
Try your codes on Mac with nwjs-sdk-v0.25.4, I can see the console log('closed') in the devtools when I close the window. And the app hides and its icon doesn't appear in the Dock.`

> The Problem is that the system can't close the window which result in a message that "nwjs stopped the shutdown"

I don't see a message that "nwjs stopped the shutdown".

**Comment by Silve2611** [comment]
I will try to post ab github project within this week. 

Did you try to reboot while the app was still running?

**Comment by Christywl** [comment]
When I try to restart the Mac, it shows:
<img width="1280" alt="screen shot 2017-10-23 at 2 21 43 pm" src="https://user-images.githubusercontent.com/20039821/31874943-6b53aa5a-b791-11e7-9c30-a29587bcc942.png">
Click 'Terminate', Mac will restart.

**Comment by Silve2611** [comment]
The Problem ist not that i cannot click it. Our customers are confused if our Program interrupts the restart. It should not do that. If every program starts doing this you will have to terminate them all. 

In Swift you have the following option

`NSWorkspace.shared.notificationCenter.addObserver(self, selector: #selector(powerOff), name: NSWorkspace.willPowerOffNotification, object: nil)`

powerOff stands for the function that you call before shutdown. There you could save the sate or whatever and then close the application before the message appears. 

A hook that listenest to the restart reboot event would be important to prevent erros like the one you catched or to execute necessary code before shutdown

**Comment by reznikartem** [comment]
+1. nwjs 0.30.5 :(
