### ISSUE TITLE
Compile WebWorkers with nwjc and load them

### ISSUE THREAD

**Issue by Silve2611** [nwjs/nw.js#6203]
It would be great if the WebWorkers could be protected with nwjc and loaded from protected nwjc content.
This way there could be protected code running in the background of the application not affecting the GUI or other components. 

If you need any help testing this. let me know! 

NWJS Version : Actual
Operating System : Both

### Expected behavior

Load a compiled .bin with WebWorker and run it. 

### Actual behavior

Unable to load WebWorker files that are not .js files

### How to reproduce

Try loading a compiled nwjc file with `new Worker('compiled.bin')`

**Comment by rogerwang** [comment]
Will add a function `importNWBin(ArrayBuffer)` in worker context. And the binary file can be read to array buffer in the main thread, posted to worker and executed there with the new function.

**Comment by rogerwang** [comment]
This is fixed in nw27 branch and will be released in 0.27.0.

**Comment by rogerwang** [comment]
Please try it with https://dl.nwjs.io/live-build/11-22-2017/nw27-db52146-45be026-d9bee42-98d5195/v0.27.0-rc1/

**Comment by victorcid** [comment]
hey culd someone give an example of this, its no esy to use
