### ISSUE TITLE
nw app can't popup Win10 soft keyboard automatically.

### ISSUE THREAD

**Issue by aw3** [nwjs/nw.js#6205]
nwjs app(nwjs version >0.12.3) can't popup Win10 soft keyboard automatically on my different machine.

there is a touchscreen on my machines too. And run the same Win 10 system(use ghost),but their main-board is different. 

the same nw app, one machine can popup Win10 soft keyboard automatically when I touch the input element on page, and other one can't automatically popup soft keyboard.

if I use nwjs version 0.12, they both can popup soft keyboard automatically when I input。 
if I user nwjs version >0.12.3, for example: version 0.23, one can't automatically popup soft keyboard.
How odd！！

How can I fix this bug? Help me.

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce it? I'll check if it's reproduced on my machine.

**Comment by aw3** [comment]
Thanks @Christywl 
~
1. make sure your windows 10 is desk mode, NOT tablet mode.
2. There is no external keyboard connect to your machine.

here is my sample code :
**content of 2.html：**
`<html>
    <head>
        <title>test</title>
    </head>
    <body>
        <input size="20" />
    </body>
</html>`

**content of package.json**
`{
    "name":"test",
    "main": "2.html"
}`

**Comment by Christywl** [comment]
I try on Windows 10, soft keyboard doesn't popup automatically with nwjs-sdk-v0.26.0. And I also try other apps, some of them can popup soft keyboard automatically, such as Microsoft outlook, IE, some of them can't, such as chrome.

@rogerwang , is this a bug of nwjs?

**Comment by rogerwang** [comment]
We should check if Chrome has this issue. Please check upstream bug reports for this and report to them if there isn't any. And post the upstream issue link here.

**Comment by Christywl** [comment]
Similar issues for Chrome: 
https://bugs.chromium.org/p/chromium/issues/detail?id=767139
https://bugs.chromium.org/p/chromium/issues/detail?id=497381

**Comment by aw3** [comment]
Two machine（A and B），same OS（Windows 10），same App.
if use nwjs v0.12.3， machine A and B both can popup soft keyboard automaticlly. 
if use nwjs version > 0.12.3( such as 0.13.3 or 0.23.7), machine A can  popup soft keyboard automaticlly, machine B  Can't popup soft keyboard automaticlly。

I notice that the  nwjs v0.12.3 used Chrome 41 and nwjs v0.23.7 use Chrome 59
So did nwjs or chrome change some OS native api  when nwjs version  from 0.12 to 0.13?
 @rogerwang @Christywl

**Comment by carrotalan** [comment]
+1

**Comment by rogerwang** [comment]
btw, in the upstream issue, it's said there is a workaround: `--disable-usb-keyboard-detect`

**Comment by aw3** [comment]
yes！！`--disable-usb-keyboard-detect`  it works！thx，buddy

**Comment by DzmitryT** [comment]
I've been trying to run my application using different versions of nwjs (x64 builds, 0.29 .. 0.34.1) on Lenovo MIIX 320 tablet running Windows 10 Home Single language 64-bit. Seems this trouble appears again since 0.33.2 and not fixed yet.  But there is no any problems with onscreen keyboard in plain Chromium (69 .. 72).

**Comment by craigathook** [comment]
@DzmitryT Did you try the this fix from above?: --disable-usb-keyboard-detect
