### ISSUE TITLE
 The official "minimal example" of the "Manifest format" has a syntax error.

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [nwjs/nw.js#6206]
URL: http://docs.nwjs.io/en/latest/References/Manifest%20Format/#quick-start

{
  "main": "index.html",
  "name": "nw-demo",
}

It gives an error about the second comma if you try to run that in NW.js. Removing it makes it run. How this is possible, I don't know, but I really wish the documentation were better. It seems like it contains a lot of outdated info as well. (Although I hope I'm wrong.)

**Comment by rogerwang** [comment]
@FjicdeiwFeiej the official documentation has no known outdated information.
