### ISSUE TITLE
 nwjs can not enter Chinese characters on Linux desktop

### ISSUE THREAD

**Issue by mynameiswf** [nwjs/nw.js#6208]
Sorry, the front of the problem did not pay attention, here again:
In the Linux desktop, you can not enter the Chinese characters in the page input box. I use the operating system is centos7, The input method is sogou pinyin. nwjs version from 15 to 25 I have tested.

In fact, our project needs to support both KDE and gnome Linux desktops

**Comment by Christywl** [comment]
Duplicate of #6183 , please track in 6183, close this.
