### ISSUE TITLE
Init problems with require.js

### ISSUE THREAD

**Issue by janroesner** [nwjs/nw.js#621]
I tried nw 0.5.0 on OSX with a SinglePageApp created using yeoman 1.0.0beta3. I'm making use of require.js, so my index.html loads my packaged JS at the end like:

<script data-main="scripts/main" src="./components/requirejs/require.js"></script>

Which in turn loads the main.js and runs it. When I prepare my distribution directory and open my index.html from a final yeoman build, the app runs smoothly. Then I created a package.json, packed all as a zip, renamed it to .nw and opened it.

What happens now is, that my JS does not seem to run. The error I see at the console is:

Uncaught TypeError: Object function (name) {  if (name == 'nw.gui')    return nwDispatcher.requireNwGui();  return global.require(name);} has no method 'config'

Is this an issue related to my use of require.js, or am I doing something totally wrong?
##

**Comment by alanjames1987** [comment]
Has anyone found any better solutions to this other than altering the requirejs source code to expose different variable names.

**Comment by alanjames1987** [comment]
I was wrong about the comment above. Other modules that are AMD compatible might still use the `require` method and so they would fail to load.

**Comment by Nudelsieb** [comment]
Are there any updates here?

I am starting a http server and open a new window with gui.Window.open("local web address"). However, I get the error "Uncaught Error: Module name "nw.gui" has not been loaded yet for context: _. Use require([])" in the new window. This is an exception fired in requirejs directly. RequireJS is used in the website by the http server, not in the main window/app.

Unfortunately the faq is not clear enough on how to solve this issue.

**Comment by Mithgol** [comment]
This issue is definitely going to be fixed in the next release.

NW.js v0.13.0-alpha5 already has Node.js `require()` namespaced as `nw.require()`, for example. You'd still want to wait for a release because that alpha has usual alpha problems of incompleteness (such as #3945 or #3995 for example).

**Comment by McSodbrenner** [comment]
Could work around this by overwriting the require function:
```
<script data-main="js/bootstrap.js" src="js/lib/require.js"></script>
<script>
var node_require = window.require;
window.require = function(data) {
	return (typeof data === 'string' ? node_require : window.requirejs).apply(window, arguments);
}
</script>
```

**Comment by mcw0933** [comment]
Posting as a heads up for anyone else who finds this issue via search:

The embedded Node.js runtime can be turned off using a manifest setting. This may help if you (like me) have static content or no need to use Node inside nw.js.

https://github.com/nwjs/nw.js/wiki/faq-name-conflict
https://github.com/nwjs/nw.js/wiki/Manifest-format#nodejs

**Comment by daedeloth** [comment]
Have been struggling with this aswell, fixed it with setting the environment manually:

```        window.require.config({
            config: {
                text: {
                    //Valid values are 'node', 'xhr', or 'rhino'
                    env: 'xhr'
                }
            }
        });```

(Ofcourse after loading requirejs)

This will force the environment to be xhr, so it uses xhr instead of node require. Before loading requirejs I put node's require in window.nodeRequire and unset window.require.
