### ISSUE TITLE
Linux NWJS shows "unlock my login keyring" prompt

### ISSUE THREAD

**Issue by koobazaur** [nwjs/nw.js#6210]
Heya,

Using latest NWJS 0.25.4 on Ubunti 16.4 LT and Manjaro 17, I get a prompt asking to provide password for the keyring. From little RD I did, it seems to be a chrome thing. Any way to disable that?

Screenshot: https://i.imgur.com/iCdGUvt.png

Cheers,
Jakub

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
