### ISSUE TITLE
Frame shows when maximize the window with frame already being setted false

### ISSUE THREAD

**Issue by fengtaijun0507** [nwjs/nw.js#6213]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :  v0.14.7

Operating System : win7

### Expected behavior

Maximize the window with no frame

### Actual behavior

Frame shows when maximize the window And frame already being setted false

### How to reproduce
Just maximize
![example](https://user-images.githubusercontent.com/14059031/31703686-4fa558fa-b410-11e7-9218-d2a7960f2382.png)

**Comment by Christywl** [comment]
I try a simple case and can't reproduce this issue on Windows 8.1 with nwjs 0.26.0. Could you please provide your sample to reproduce this?

**Comment by Christywl** [comment]
close until there is more information
