### ISSUE TITLE
Print margins always same, regardless of setting

### ISSUE THREAD

**Issue by b3da-cz** [nwjs/nw.js#6214]
NWJS Version : 0.20.0 - 0.25.4
Operating System : ubuntu 16.04

### Expected behavior

change margins according to setting `marginsType` and `marginsCustom`

### Actual behavior

nothing happens, no matter how margins are set in nwjs, print looks always same

### How to reproduce

print with for example:

>            marginsType: 3,
>            marginsCustom: { marginBottom: 0, marginLeft: 0, marginRight: 0, marginTop: 20 },

then change it to another value and print..

**Comment by rogerwang** [comment]
I just tried with 0.25.4 and 0.26.0 and it's working well for me.

**Comment by Christywl** [comment]
close until there is more information
