### ISSUE TITLE
External dev tool extension batarang wont load

### ISSUE THREAD

**Issue by Arti3DPlayer** [nwjs/nw.js#6215]
NWJS Version : 0.25.4
Operating System : OSX

### How to reproduce
I created folder `devtools/` put `batarang-0.10.9` extension into it.
And run my project with command:

`path/to/nw --load-extension=./devtools/batarang-0.10.9/ --enable-logging=stderr .`

Get error:

```
"Uncaught Error: Cannot find module './loader'", source: module.js (553)
module.js:553
    throw err;
    ^

Error: Cannot find module './loader'
    at Function.Module._resolveFilename (module.js:551:15)
    at Function.Module._load (module.js:495:23)
    at Module.require (module.js:592:17)
    at require (internal/module.js:11:18)
    at self.require (<anonymous>:11:26)
    at chrome-extension://liaooeeeflejncbmngnjegjilecmbghd/hint.js:6:1
```

Tried different paths:
```
--load-extension=./devtools/batarang-0.10.9/loader.js
--load-extension=./devtools/batarang-0.10.9/manifest.json
```

etc.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Mac with nwjs-sdk-v0.25.4.

**Comment by rogerwang** [comment]
You can not using `hint.js` from the extension's source repo directly. Using the file in 'dist/' directory or the one from Chrome web store instead. After using the correct file the error message is gone. Closing as invalid.

**Comment by Arti3DPlayer** [comment]
@rogerwang Could you please show how do i need to set path ? When i set path to:
```
--load-extension=./devtools/batarang-0.10.9/dist/hint.js
```
I got error:
> Manifest file is missing or unreadable.
