### ISSUE TITLE
The frame border will be displayed when it is started

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#6217]
NWJS Version :0.26
Operating System :windows10 

### Expected behavior
my pacakage.json set
"window": {
    "toolbar": true,
    "frame": false,
    "show":true,
    "transparent": true,
    "resizable": false,
	"show_in_taskbar":true
  },
<!- What do you think should happen? ->
I'm setting it without borders,This was not the case in the 0.25.4 version

### Actual behavior

<!- What actually happens? ->
The frame border will be displayed when it is started

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by onlyou** [comment]
![snipaste201710](https://user-images.githubusercontent.com/2231544/31774848-7a9216ca-b519-11e7-89c1-1ab594c059c4.jpg)

**Comment by onlyou** [comment]
![33](https://user-images.githubusercontent.com/2231544/31775630-bfc19958-b51b-11e7-8c92-b4bcb0dc087a.gif)

**Comment by rogerwang** [comment]
CC @jtg-gg , please take a look.

**Comment by jtg-gg** [comment]
@onlyou can sent me your sample app ?

I did notice, but it is hardly noticeable on my machine, in fact I can't see it anymore after running several times, the app might be cached in memory and run faster

**Comment by onlyou** [comment]
I am very sorry
Our source code is not encrypted, we don't know how to provide it
But I feel this issue has to do with one of the questions that I've had before
Code is # 6176

**Comment by onlyou** [comment]
@jtg-gg 
I am very sorry
Our source code is not encrypted, we don't know how to provide it
But I feel this issue has to do with one of the questions that I've had before
Code is # 6176

**Comment by onlyou** [comment]
@jtg-gg 
I am very sorry
Our source code is not encrypted, we don't know how to provide it
But I feel this issue has to do with one of the questions that I've had before
This problem has been solved since the last problem
Code is # 6176

**Comment by jtg-gg** [comment]
@onlyou you can make a simple app, to show me the error

**Comment by onlyou** [comment]
I've simplified the program
Without compilation, you keep the nw files and compile your own runs
I made exe too big,
Thank you very much for your help
[ExamManager.zip](https://github.com/nwjs/nw.js/files/1400767/ExamManager.zip)

**Comment by tolrtd** [comment]
Also seeing this. App icon and page title get shown in the titlebar if transparent = true

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/98
please also patch nw27

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
@jtg-gg I'm reopening this issue according to your comment https://github.com/nwjs/nw.js/issues/6265#issuecomment-343376723

**Comment by jtg-gg** [comment]
this bug should be fixed by this https://github.com/nwjs/chromium.src/pull/104
