### ISSUE TITLE
Maximized frameless transparent window maintains right resize area exposed

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6221]
NWJS Version : SDK 0.26.0
Operating System : Win7 x64

### Expected behavior

The right side of the window should not display a border and the cursor should not change when moving over it

### Actual behavior

The right side of the window is displaying a border and when moving the cursor over it changes to the e-resize cursor, confirming that the right side resize is still in effect while maximized

### How to reproduce

Basic app template with option to maximize.
Window must be set to transparent and frameless.
Using package.nw method

`package.json`
````json
{
    "author": "test",
    "description": "test",
    "main": "index.html",
    "name": "test",
    "version": "1.0.0",
    "window": {
        "frame": false,
        "transparent": true
    }
}

````

`index.html`
````html
<!DOCTYPE html>
<html style="background:rgba(0,0,0,0.5);height:100%">
    <head>
    </head>
    <body>
        <button onclick="resize();return false;">Click to maximize/restore</button>
        <script>
                var is_maximized = false;
                var gui = require("nw.gui");
                var win = gui.Window.get();

                win.on("restore", () => is_maximized = false);
                win.on("maximize", () => is_maximized = true);

                function resize() {
                    if (is_maximized) {
                        win.restore();
                    } else {
                        win.maximize();
                    }
                }
        </script>
    </body>
</html>
````

Short recording demonstrating the problem. The window is maximized and the right side has a white border, which cannot be seen in the GitHub white background, I suggest opening this recording in a window with a dark background.

![ss](https://user-images.githubusercontent.com/9222661/31853880-f3d9a716-b67f-11e7-9c26-7c1b8ebd99f4.gif)

**Comment by Christywl** [comment]
I can reproduce this issue on Windows 8.1 with nwjs-sdk-v0.26.0.

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/98
please also patch nw27

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by pols63** [comment]
Hi. It still happen to me in Windows 10.
