### ISSUE TITLE
webview tag not block disallowed url scheme

### ISSUE THREAD

**Issue by malacca** [nwjs/nw.js#6223]
nwjs v0.26.0, windows 32bit and 64bit

test

```
<a href="scheme://something">Main</a>
<webview src="file://D:/test.html" style="display:block;width:640px; height:480px"></webview>
```

click  link [main],   response was canceled

webview open failed, and get "The load has aborted with error -301: ERR_DISALLOWED_URL_SCHEME." on console

put test file in server, change test code

```
<a href="scheme://something">Main</a>
<webview src="http://localhost/test.html" style="display:block;width:640px; height:480px"></webview>
```

test.html code

`<a href="scheme://something">Test</a>`

click link [test],  and  get

![mycatch](https://user-images.githubusercontent.com/15194457/31872228-9cc6a294-b7ec-11e7-9e51-342c1d612ade.png)

the DISALLOWED_URL_SCHEME will block in main page, but not block in webview page.

i use webview open a page designed for phone, the page have some special scheme.

so, i will get a error page

**Comment by Christywl** [comment]
I can reproduce this issue on Windows 8.1 with nwjs-sdk-v0.26.0.

**Comment by rogerwang** [comment]
The error page is expected and used to block the access to disabled scheme.

**Comment by malacca** [comment]
I also thought this is not bug, but it better to improve it

when i use webview open a website  that designed for phone 
the page redirect to disallowed url scheme (for example:  the page want open app by special scheme).

i can not do anything to block this, as i know, chrome api  can not do it

ps:  Electron can do this by listen navigate event
