### ISSUE TITLE
 User Data of v0.25.4 cause old version nwjs crash

### ISSUE THREAD

**Issue by icesunx** [nwjs/nw.js#6226]
NWJS Version : v0.25.4、v0.22.3
Operating System : windwos 7 64 bit

I run my app with v0.25.4 and run it with v0.22.3 again, the ver 0.22.3 will **crash**.
Then I run my app with v0.20.3, it work well.
Delete the  User Data, my app will work well with 0.22.
[User Data.zip](https://github.com/nwjs/nw.js/files/1410417/User.Data.zip)
I upload the user data files which include crash dump.

**Comment by Christywl** [comment]
I can reproduce this with v0.26.0 and v0.22.*.  
@rogerwang , is this a bug of v0.22.*, or a bug for the newer builds?

**Comment by rogerwang** [comment]
The crash is a bug in 0.22, which is not maintained any more. So closing this issue.

btw, upstream Chromium do not promise backward compatibility of the user data.
