### ISSUE TITLE
webview.executeScript wrong context

### ISSUE THREAD

**Issue by iteufel** [nwjs/nw.js#6229]
NWJS Version : 0.26.0
Operating System : macos

### Expected behavior

`webview.executeScript({code: 'console.log(window)'}, console.log)`
should log the window object 

### Actual behavior

`webview.executeScript({code: 'console.log(window)'}, console.log)`
logs the wrong window object
 
### How to reproduce
[webview.executeScript.example.zip](https://github.com/nwjs/nw.js/files/1412593/webview.executeScript.example.zip)

**Comment by Christywl** [comment]
I try your sample on Mac with nwjs-sdk-v0.26.0, here is my result:

<img width="1280" alt="screen shot 2017-10-25 at 9 52 29 am" src="https://user-images.githubusercontent.com/20039821/31976468-5e62497e-b8fd-11e7-9c34-39bf32c1a988.png">

**Comment by rogerwang** [comment]
It's executed in the right context. It's just the issue of accessing returned window object. Will look into this.

If you execute `document.body.style.backgroundColor = "red";` everything works fine.

**Comment by rogerwang** [comment]
Turns out it's executed in a isolated world on purpose by upstream: https://stackoverflow.com/a/24435983/180197

Will remove this limitation for NW app.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by phiSgr** [comment]
I have some workaround code that depends on the code being executed in the extension "isolated world" context. Is it possible, in the future, to have extra fields in the `InjectDetails` to determine the context?

**Comment by rogerwang** [comment]
@phiSgr yes. Please file another issue for this feature.

**Comment by rogerwang** [comment]
Will add a boolean field `mainWorld` in `InjectDetails` to control the world where the code would run. The default value would be `false` to keep align with upstream. Thanks.

**Comment by gpetrov** [comment]
@rogerwang are those new options already available? Or coming up in the new release?

**Comment by rogerwang** [comment]
Yes see
http://nwjs.readthedocs.io/en/nw27/References/webview%20Tag/#executescript-in-main-world

It's in 0.27 nightly and will be released with 0.27.0 in 1 or 2 days.
