### ISSUE TITLE
Crash on remote desktop in Windows 7

### ISSUE THREAD

**Issue by ogo-adp** [nwjs/nw.js#6230]
NWJS Version : 0.26.0
Operating System : Windows 7

### Expected behavior

No crash

### Actual behavior

Our app cannot run when nwjs runs in a remote desktop session (crash loop in renderer process). App runs fine on local session

### How to reproduce

Do a remote desktop to a Windows 7 box, then launch nw.exe (SDK) as is. 
Inspect the page and then type window.location = 'http://www.google.com'
Google page will appear normally
Then type openlayers in search box and click on https://www.openlayers.org link
We observe that when going to this page the page freeze and the renderer process goes in a crash loop just as in our app
We can't get nwjs to create a dump or obtain any error from js side

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.26.0.  Wait for a few seconds, the openlayers page loads successfully.
Device: Use Remote Desktop on Windows 10 to connect to Windows 7.
![6230](https://user-images.githubusercontent.com/20039821/32036732-260d0f48-ba54-11e7-9ab8-cb8f53c5ed47.png)

**Comment by ogo-adp** [comment]
Oh yes you are right, i've now understood what the real problem was.

We don't include the "swiftshader" folder with our app, and somehow it is needed when using the app on remote desktop ... I spent hours trying to understand the problem and forgot to check that.

Sorry for wasting your time and thanks for your response (and btw nwjs rocks :))

**Comment by rogerwang** [comment]
SwiftShader is a software 3D renderer used in Chrome that lets you use CSS 3D and WebGL even on hardware with incapable GPUs. So you can provide advanced 3D graphics independent from hardware of your users.
