### ISSUE TITLE
new chromedriver tests spawning infinitely

### ISSUE THREAD

**Issue by automate-the-web** [nwjs/nw.js#6234]
When I got a test to run using NW.js and Chromedriver using latest version, I find that the nw.js window spawns and executes the test but upon finishing, it will immediately spawn another nw.js window instance and keeps doing this until there is a lot of NW.js tests running.

I just have one main.js script being loaded into index.html which is set in package.json

and main.js is just a WebdriverIO code

```
var webdriverio = require('webdriverio');

....

client.init().url("http://x.com").end(); //this keeps running over and over

```

any ideas as to why it will be stuck in a loop spawning new nw.js instances?

**Comment by Christywl** [comment]
Could you please provide a ready sample and steps to reproduce this?

**Comment by Christywl** [comment]
close until there is more information
