### ISSUE TITLE
Transparent window displays white background

### ISSUE THREAD

**Issue by kapilmoondra** [nwjs/nw.js#6237]
NWJS Version : 0.22.3
Operating System : All Windows, Ubuntu 14, 16

### Expected behavior

Window shall always have transparent background

### Actual behavior

sometimes window appears with white background.

### How to reproduce

I haven't found any particular scenario to reproduce this. However if you open/close a transparent window frequently in an application, window displays white background

![image](https://user-images.githubusercontent.com/33033824/32066457-6ef79a40-ba9d-11e7-9667-65b8414048ca.png)

**Comment by Christywl** [comment]
I try a simple test on Windows 8.1 with nwjs-sdk-v0.26.0, doesn't reproduce this issue. The transparent window works fine.

**Comment by Yonezpt** [comment]
@kapilmoondra You keep using an old version of NW, update to the latest one which has this problem fixed as well as the one you posted before #6227

**Comment by Christywl** [comment]
@kapilmoondra , is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information
