### ISSUE TITLE
Warning message on macOS

### ISSUE THREAD

**Issue by Mann90** [nwjs/nw.js#6238]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.26
Operating System : macOS High Sierra

### Expected behavior

I expect that no warning messages should be there.

### Actual behavior

There are warning messages in the terminal.

### How to reproduce

Just run the `nwjs` in the terminal, and there will be a warning message:
`
$ /Applications/nwjs/nwjs.app/Contents/MacOS/nwjs
2017-10-26 20:38:33.806 nwjs[27311:1517080] *** WARNING: Textured window <AppNSWindow: 0x7fcbb6457620> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
`

**Comment by Christywl** [comment]
I can reproduce this on Mac 10.13 with nwjs-sdk-v0.26.0. It doesn't happen on my Mac 10.12.6.

**Comment by rogerwang** [comment]
It shares the same root cause of upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=749905

Please watch and star the upstream issue. Thanks.
