### ISSUE TITLE
Toggling fullscreen while keyboard is held keeps those buttons pressed

### ISSUE THREAD

**Issue by quantumproducer** [nwjs/nw.js#6242]
Easier to reproduce in Chrome, same bug.

Visit http://jsfiddle.net/HwR9N/3/
Click in bottom right. Hold Space key on keyboard.
Observe "Keys pressed: 32"

With Space held, use Mouse to select window options and fullscreen.
Release Space key.
Observe "Keys pressed: 32"

**Comment by Christywl** [comment]
I open the page with `nw.exe --url=http://jsfiddle.net/HwR9N/3/`, but don't see window options in the page. How should I do for this step?

**Comment by quantumproducer** [comment]
Please try:

```
const gui = require('nw.gui');
var win = gui.Window.get();

setTimeout(5000, function() {
window.win.toggleFullscreen();
}
```

**Comment by Christywl** [comment]
Your codes don't work for me, here are my codes and it works fine on Windows 8.1 with nwjs-sdk-v0.26.2. Press Space key and hold on when open http://jsfiddle.net/HwR9N/3/, you can see `Keys currently pressed: 32`. Wait for 5 seconds, the window changes to fullscreen mode, and then release Space key, `32` disappears.
```
<!DOCTYPE html>
<html>
<body>
<script>
var win = nw.Window.open("http://jsfiddle.net/HwR9N/3/",{},function(win){
setTimeout(function() {
win.toggleFullscreen();
},5000);
});
</script>
</body>
</html>
```

**Comment by quantumproducer** [comment]
Is there documentation that this was fixed in a more recent version than 0.23.X?

**Comment by Christywl** [comment]
It also works fine for me on 0.23.7.

**Comment by quantumproducer** [comment]
Ok. I did a workaround in my game project by having my initial toggle change a variable, then check for that variable on a timer and only toggle when the key is unpressed
