### ISSUE TITLE
stream file not download complete in nwjs 0.14.3

### ISSUE THREAD

**Issue by ericchan1336** [nwjs/nw.js#6249]
NWJS Version :0.14.3
Operating System :win 7 64 bit

So, I'm developing base nwjs 0.14.3, it's a bit old, I konw. But when I try to play some streamed audio file in it using cyber play, I always go the error that the file cannot be played. 

But it works fine in chrome v62. Throgh the network tab in devtool of nw, I found that the stream file is not downloaded completely. It always stops at the size of 1MB. 

But in nwjs, it stops downloading at 1MB every time I try.

So, here is my question: Is there some setting in nw that control the download size of such type of file? If there is, how can I set the size bigger? If there is no such config item, how can I make the download process complete in nw?

Any suggestions will be appreciated, thanks.

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information
