### ISSUE TITLE
make nw-gyp > v3.6.0 default for nw27

### ISSUE THREAD

**Issue by fpn** [nwjs/nw.js#6266]
NWJS Version : 0.27
Operating System : windows 10 64 bit

nw-gyp on npm is 3.4.0

NW.JS 0.27 / Chrome 63 uses Visual Studio 2017

building native modules results in:
```
  File "C:\Users\fpn\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py", line 444, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
```

Visual Studio 2017 support is in node-gyp/nw-gyp >= 3.6.0

Workaround - use the nw-gyp 3.6.2 from github

Any reason not to have nw-gyp 3.6.2 or higher on npm?

**Comment by rogerwang** [comment]
Will push the new version to npm. Thanks.

**Comment by rogerwang** [comment]
done.
