### ISSUE TITLE
Unable to download nwjs

### ISSUE THREAD

**Issue by CyberianIce** [nwjs/nw.js#6268]
It's imposible to download binaries from official website at this moment. 

`wget` returns `A TLS packet with unexpected length was received.` and fall into retry loop.

**Comment by Christywl** [comment]
Which version? I can download the latest nwjs v0.26.3 builds with `wget`. Please try again.

**Comment by CyberianIce** [comment]
Error was thrown for any zip archive (not for other files), but then it worked again within minutes. Closing issue...
