### ISSUE TITLE
Flash player not work

### ISSUE THREAD

**Issue by Nemra1** [nwjs/nw.js#6271]
NWJS Version : nwjs-v0.24.4-win-x64
Operating System :8.1

### Expected behavior
```

{
  "name": "nw-demo",
  "main": "http://xops.ml/client/index.php?init_lang=ar",
  "chromium-args": "--ppapi-flash-path=pepflashplayer.dll --ignore-certificate-errors --disable-web-security"

}
```
 im own AV chat room and i need to accses to hardware for mice and camera from browser by swf file included in my system ...
but i get outdata player
![2017-11-03_210353](https://user-images.githubusercontent.com/22897987/32392127-f8c889e2-c0dc-11e7-91a9-18ea8c882597.png)

**Comment by Christywl** [comment]
Please try to add `--ppapi-flash-version=your_flash_version` in "chromium-args".

**Comment by Nemra1** [comment]
thx @Christywl ............ok now this my .json file
```
{
  "name": "nw-demo",
  "main": "http://xops.ml/client/index.php?init_lang=ar",
  "chromium-args": "--ppapi-flash-path=pepflashplayer.dll --ignore-certificate-errors --disable-web-security --ppapi-flash-version=27.0.0.183 --reduce-security-for-testing--allow-running-insecure-content"
}
```
now after add --ppapi-flash-version=27.0.0.183
browser say couldnt load plugin
![2](https://user-images.githubusercontent.com/22897987/32440727-15ec4b68-c2fd-11e7-9316-9bac8e16f815.png)
and my plugin in NW.js  folder
![3](https://user-images.githubusercontent.com/22897987/32440766-4a7903a8-c2fd-11e7-8008-e74e578f80ab.png)
what is wrong now?

**Comment by Christywl** [comment]
If you want to use chromium-args, I think you need to add the path for pepflashplayer.dll, `--ppapi-flash-path=/your_path/pepflashplayer.dll`.
Another way, you need put `manifest.json` and `pepflashplayer.dll` in the `PepperFlash` subdirectory, not 27.0.0.183. 
![image](https://user-images.githubusercontent.com/20039821/32471422-27bb8ffc-c398-11e7-99db-bb7d2b00ed38.png)

**Comment by Nemra1** [comment]
@Christywl thx but now i need to click right to enable and nothing work
![2017-11-08_152855](https://user-images.githubusercontent.com/22897987/32551538-8fe5d7b6-c499-11e7-9901-9f8689339432.png)

**Comment by Christywl** [comment]
It works fine on my device.  I put the plugin files (including ‘manifest.json’ of it) in the ‘PepperFlash’ subdirectory under NW.js binary.
![image](https://user-images.githubusercontent.com/20039821/32471422-27bb8ffc-c398-11e7-99db-bb7d2b00ed38.png)
Here is my test:
```
{
  "name": "nw-demo",
  "main": "http://get.adobe.com/flashplayer/about/"
}
```
```
{
  "name": "nw-demo",
  "main": "http://get.adobe.com/flashplayer/about/",
  "chromium-args": "--ppapi-flash-path=PepperFlash/pepflashplayer.dll --ppapi-flash-version=27.0.0.183"
}
```
Both of them works fine.

**Comment by rogerwang** [comment]
It's better to make sure system flash plugin is not involved. NW tries to find system flash plugin pointed by `HKEY_LOCAL_MACHINE\SOFTWARE\Macromedia\FlashPlayerPepper` in the registry.

**Comment by Nemra1** [comment]
Im work on Windows 8.1 Pro 64x 
But none of this work with me

**Comment by Nemra1** [comment]
no luck to workc in node webkit
