### ISSUE TITLE
event.keyCode is incorrect for numpad keys on Mac

### ISSUE THREAD

**Issue by St333vie** [nwjs/nw.js#6272]
## _**Update:** It appears now that this issue does indeed occur in the latest version of Chrome for Mac, not just nw.js's Chrome._

======== TEMPLATE BUG FORM ========

**NWJS Version :** 26.3 (also tried 21, 24, 25)
**Operating System :** MacOs 10.11.6

**### Expected behavior**
Keys on the numeric keypad should be recognized in nw.js via event.keyCode as they do in Safara and standalone Chrome browsers. Instead, event.keyCode will report the _non-numeric equivalent_ keycode when a numkey is pressed.
_**Example:** Numeric Keypad key "1" is reported as code 49 and it should be 97._

**To reproduce:**
Simply poll for event.Keycode on a Mac or here is a Mac nw.js example (made with Construct) [LastKey2.zip](http://www.divertigo.com/KeyCodeHtml/LastKey2.zip)
This example compares the keycode detected by Construct vs Javascript directly.  They will be the same code for numeric vs non-numeric number keys.

This issue does not occur in Chrome or Safari on Mac!  See that by going [to this webpage](http://www.divertigo.com/keycodehtml) in Safari or Chrome for an example that does not experience the issue.

Furthermore, **event.code** is always correct in all cases as observed in the examples provided.  This is what I must leverage as a workaround unless there are other suggestions.

Thanks!
-Steve

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.26.3. It works fine on Linux/Windows.

**Comment by rogerwang** [comment]
Since the latest update from OP is that it's happening in upstream as well. Please report this issue to Chromium project. Thanks.
