### ISSUE TITLE
question abbout HTTP(s) requests

### ISSUE THREAD

**Issue by yattamax** [nwjs/nw.js#6273]
Hi everyone,
I have a "simple" question about nw.js and remote resources over HTTP(s)

when nw.js made a remote request, this request is handled by NodeJS or is handled by the internal chromium browser?

I explain why I ask this:
for a forensic application I need to intercept all request , and for each one I need to go in deep, specially for HTTPS connection.

an simple example in NodeJS of what I need:

```
var https = require('https');
var fs = require('fs');

function parseSession(buf) {
  return {
[TO DO SOMETHING]
  };
}

callback = function(response) {
  var str = ''
  response.on('data', function (chunk) {
    str += chunk;
  });

  response.on('end', function () {
    console.log(str);
  });
}

var options = {
  host: 'github.com',
  port: 443,
  path: '/',
  method: 'GET'
};

var R2 = https.request(options, callback)
.once('socket', (s) => {
  s.once('secureConnect', () => {
    let session = parseSession(s.getSession());
[TO DO SOMETHING]
  });
});

R2.end()

```

So I use https module for intercept SSL session.

My goal is that all HTTP/s connection use a my handler to perform connection

I can do this in ws.js? :)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
