### ISSUE TITLE
Program crashed by 'http_transport_win_cc(170) WinHttpCrackUrl'

### ISSUE THREAD

**Issue by tangyue0924** [nwjs/nw.js#6274]
NWJS Version : 0.24.3
Operating System : Win7(32/64)

### Full Error Report

ERROR: http_transport_win_cc(170) WinHttpCrackUrl: URL 未使用可识别的协议[URL did not use recognizable protocols] (0x2ee6)

### After Google...

No results said the reason for the crash. I need your help.
THX!

**Comment by Christywl** [comment]
The error is same as #6247, please try the latest nightly build to check if it's fixed.

**Comment by tangyue0924** [comment]
@Christywl Here is a crash report, it might be useful. [reports.zip](http://hongfund-desktop.oss-cn-shanghai.aliyuncs.com/reports.zip)

**Comment by Christywl** [comment]
Does it still reproduce on the latest nightly build https://dl.nwjs.io/live-build/?
Could you please upload your sample here? I'll check it on my device.

**Comment by tangyue0924** [comment]
@Christywl Sorry, it was from user's computer. I don't know how to reproduce the crash. I'll let them try the latest version(0.26.4).

**Comment by tangyue0924** [comment]
@Christywl [1109/115308.115:ERROR:registration_protocol_win.cc(56)] CreateFile: 系统找不到指定的文件。 (0x2) Emm... Crashed again without dmpfile, but it has a new log..

**Comment by zbian** [comment]
@Christywl Crashed on win7 32bit 0.26.6(nightly build 11-11).



[reports.zip](https://github.com/nwjs/nw.js/files/1463559/reports.zip)

**Comment by Christywl** [comment]
@zbian , could you please provide a sample to reproduce it?

**Comment by rogerwang** [comment]
@Christywl you could get a stack trace from the attached reports as well. See documents here: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#decode-minidump-with-minidump_stackwalk

**Comment by gwicksted** [comment]
Just in case this is helpful:

`nwjs-sdk-v0.27.0-beta1-win-x64` (latest) and `nwjs-sdk-v0.26.5-win-x64` (stable) both log this error for me on the console (Windows 10) but neither crash.

```
[16:29:16] [1113/162916.695:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol  (0x2ee6)
```

**Comment by rogerwang** [comment]
The error message is not relevant to the crash. And close until there is more information with the latest version.
