### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Ants-double** [nwjs/nw.js#6276]
version :beta0.264
myscript.js code
`exports.setText = function() {
   var el= document.getElementbyId('demo')
    el.innerHTML = 'hello';
};`
html code
`<!DOCTYPE html>
<html>

<head>
    <title>random number</title>

   
    
  
</head>

<body>
       
    <h1>test login </h1>

    <p id="demo">
        test tcp
    </p>

    <button type="button" onclick='sendlidardata()'>login</button>
    <button type="button" onclick='testFunction()'>test</button>

    <script type="text/javascript" language="javascript" src='./myscript.js'>
            var myscript = require('./myscript.js');
            // 将`el`元素传入Node函数
            myscript.setText();
            // "hello"将显示在`el`标签中
        </script>
</body>

</html>`
then ,I get an error ,Uncaught ReferenceError: exports is not defined
Thankyou ,I am a new one .hope your answer.

**Comment by oliverlife** [comment]
change <script type="text/javascript" language="javascript" src='./myscript.js'>
to <script type="text/javascript" language="javascript">

**Comment by Christywl** [comment]
@Ants-double , please try oliverlife's advice. It's ok for me.

**Comment by rogerwang** [comment]
@Christywl OP's usage is valid from Node.js. We should support it as well. Please verify.

**Comment by Christywl** [comment]
@rogerwang , I'm not clear about this usage.  We usually use `require()` to import nodejs file. But OP uses html tag `<script src="">` to import a nodejs file, is this a valid usage?

**Comment by rogerwang** [comment]
I see. Both the script tag and require() is used to load it... So closing this issue...
