### ISSUE TITLE
print a specific element

### ISSUE THREAD

**Issue by elouf** [nwjs/nw.js#6277]
Hello,

Is there a way to print a specific img element which is present in my window?
I dont't want to print the whole window and don't find the way to do this....

Thanks for your answer.

**Comment by chlp** [comment]
You can create server with [http](https://nodejs.org/api/http.html#http_http_createserver_requestlistener), save specific element to new HTML, then open new nw window with new saved page at opened server using **nw.Window.open** and print on event "loaded".

**Comment by elouf** [comment]
Thanks for your answer,

I must missing something...
i tried the following code :

```javascript
            var http = require('http');
            var server = http.createServer((req, res) => {
                res.setHeader('Content-Type', 'text/html');
                res.writeHead(200, { 'Content-Type': 'text/plain' });
                res.write('<img src="ressources/images/abeille.jpg" />');
                res.end('ok');
            }).listen(8000);
            window.open('https://127.0.0.1:8000');
```
However i can't establish the connection, so i don't understand how to access my new window...

**Comment by chlp** [comment]
It is piece of my working code (filePath - disk path to image):
```js
let fileToPrintPath = global.__dirname + '/tmp/' + filename;
let stream = fs.createReadStream(filePath).pipe(fs.createWriteStream(fileToPrintPath));
stream.on('finish', function () {
    nw.Window.open('http://localhost:37339/' + filename, {
        show: true,
        new_instance: false
    }, function (win) {
        win.maximize();
        win.on('loaded', function () {
            try {
                win.print({
                    autoprint: false,
                    landscape: true,
                    headerFooterEnabled: true,
                    headerString: 'Compass snapshot: ' + filename,
                    footerString: ''
                });
                fs.unlinkSync(fileToPrintPath);
                win.close();
            } catch (exception) {
                console.log('print exception', exception);
            }
        });
    });
});
```

**Comment by elouf** [comment]
Sadly, win is undefined when nw.Window is opened...
```javascript
            let filename = "abeille.jpg";
            let fileToPrintPath = "/Users/stdi/Desktop/" + filename;
            let filePath = global.__dirname + '/_content/ressources/images/' + filename;
            let stream = fs.createReadStream(filePath).pipe(fs.createWriteStream(fileToPrintPath));
            stream.on('finish', function () {
                nw.Window.open('http://localhost:37339/' + filename, {
                    show: true,
                    new_instance: false
                }, function (win) {
                    console.log(win)
```
console.log return undefined...
My jpg is successfully piped and i get a /Users/stdi/Desktop/abeille.jpg file

**Comment by elouf** [comment]
I finally succed in printing my doc, however the result was a blank page...

The thing is that my print preview is right (image, title, filename in footer, page number...) but nothing if i try to print or generate a pdf... have  you ever see that?

Thanks

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
