### ISSUE TITLE
Cannot view storage after live reload

### ISSUE THREAD

**Issue by sadikyalcin** [nwjs/nw.js#6281]
NWJS Version : **0.22.3**
Operating System : **OS X El Capitan Version 10.11.6**

```
var gulp = require('gulp');
gulp.task('reload', function () {
    if (location) {
        location.reload()
        .pipe(notify({ message: 'Reloaded.' }));
    }
});

gulp.watch('**/*', ['reload']);
```

### Expected behavior

After app has reloaded, be able to view storage info on 'Application' tab.

![screen shot 2017-11-10 at 11 37 39](https://user-images.githubusercontent.com/8109619/32656918-9ed3e952-c60b-11e7-99f7-28d7b4aa423b.png)

### Actual behavior

All info are empty. You have to re-open dev tools to get it working.

![screen shot 2017-11-10 at 11 38 18](https://user-images.githubusercontent.com/8109619/32656932-ac683514-c60b-11e7-94b3-f53b98cf4d24.png)

### How to reproduce

1. Create a html page with the script above added before the body tag.
2. Save something to local storage / session storage / cookies etc...
2. Run the app.
3. Open the developer tools.
4. Make a change in any file [index.html].
5. You can't view storage after app has reloaded.

**Comment by Christywl** [comment]
I tried on Mac with nwjs v0.22.3, saw your issue. But it worked fine on v0.26.5. The local storage was still displayed after I changed index.html and the app is reloaded(no need to re-open devtools). Could you please try the latest nwjs build in your side?

**Comment by sadikyalcin** [comment]
I have tried it with the latest version and can confirm it works fine.
