### ISSUE TITLE
Frequent crashes while draging

### ISSUE THREAD

**Issue by bambooCZ** [nwjs/nw.js#6283]
I've filled a bug in Chromium, because it is not firing drag events while dragging anything from webview. https://bugs.chromium.org/p/chromium/issues/detail?id=783789

NWjs is crashing quite frequently on top of that. It is happening much more on Mac OS than on Windows.

[drag-drop.zip](https://github.com/nwjs/nw.js/files/1461939/drag-drop.zip)

**Comment by Christywl** [comment]
Try it on Mac 10.12.6 and Windows 8.1 with nwjs-sdk-v0.26.5:
Drag event isn't fired when dragging something from the webview(https://nwjs.io), but the app doesn't crash. 

Which version do you use? And could you please upload the crash dump file?

**Comment by bambooCZ** [comment]
I am using v0.26.5, v0.22.3, v0.14.3. One in 30 tries in one app session crashes.

**Comment by Christywl** [comment]
I try 30+ times on Mac with nwjs-sdk-v0.26.5, don't see crash. Could you please upload your crash dump file?

**Comment by bambooCZ** [comment]
I don't know why, but I didn't managed to crash v0.26.x. I managed to crash v0.22.3.  But I am sure, that I've seen v0.26.5 crashed on this example.

[nwjs-sdk-v0.22.3-osx-x64.zip](https://github.com/nwjs/nw.js/files/1486965/nwjs-sdk-v0.22.3-osx-x64.zip)
