### ISSUE TITLE
Drag and drop to webview broken

### ISSUE THREAD

**Issue by phiSgr** [nwjs/nw.js#6285]
NWJS Version : v0.26.5
Operating System : MacOSX

### Expected behavior

I can drag from the app to the webview, as well as drag from other windows.

### Actual behavior

After a fresh start, I can drag from other windows to the webview.
After dragging in non-webview app content to the webview, which fails, I can no longer drag from other windows to the webview.

Drag from inside webview still works though.

### How to reproduce

`git clone https://github.com/googlearchive/chrome-app-samples.git`
`nwjs.app/Contents/MacOS/nwjs ~/chrome-app-samples/samples/webview-samples/browser`

Drag from other windows to the Google search bar inside webview works.
Drag from the url bar to the search bar fails.
Drag from other windows to the search bar no longer works.

Drag from other windows to the search bar works after restarting the app.

**Comment by phiSgr** [comment]
A simpler reproduction case, slightly modified from chromium issue [412373](https://bugs.chromium.org/p/chromium/issues/detail?id=412373).

Dragging from other windows to blue box works.

Dragging the text inside the app fails. Further attempt dragging from other windows fails. Dragging the black box inside the webview fails.

package.json
```
{
  "name": "drop Testcase",
  "description": "My first Chrome App.",
  "version": "0.1",
  "manifest_version": 2,
  "main": "window.html",

  "webview": {
    "partitions": [
      {
        "name": "trusted",
        "accessible_resources": [
          "<all_urls>"
        ]
      }
    ]
  }
 }
```
window.html
```
<!doctype html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8" />
    <style>
     html, body, iframe {
       width: 100%;
       height: 100%;
       border: none;
     }
    </style>
  </head>
  <body>
    <h1>Missing `drop` event Testcase</h1>
    <ol>
      <li>Drag the black box into the blue box.
      <li>On success the background will change to green.
      <li>On failure nothing happens.
    </ol>

    <webview src="file:///Users/phisgr/Downloads/ondrop/ondrop.html" partition="trusted" style="height: 300px; display: inline-flex;"></webview>
  </body>
</html>
```
ondrop.html
```
<!doctype html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8" />
    <style>
     div#drag {
       background-color: black;
       width: 100px;
       height: 100px;
     }

     div#drop {
       background-color: blue;
       width: 100px;
       height: 100px;
     }
    </style>
    <script>
     onload = function() {
       // Cancel events for drop to kick in.
       document.querySelector("#drop").addEventListener(
         "dragenter",
         function(event) {
           event.preventDefault();
       });

       // Cancel events for drop to kick in.
       document.querySelector("#drop").addEventListener(
         "dragover",
         function(event) {
           event.preventDefault();
       });

       // Listen for drop event.
       document.querySelector("#drop").addEventListener(
         "drop",
         function() {
           document.body.style.backgroundColor = "green";
           console.log("Drop Event baby!")
      });
     };
    </script>
  </head>
  <body>
    <div id=drag draggable=true></div>
    <div id=drop></div>
  </body>
</html>
```

**Comment by Christywl** [comment]
Similar to the chrome issue [783789](https://bugs.chromium.org/p/chromium/issues/detail?id=783789) in #6283?

**Comment by phiSgr** [comment]
I guess it is not. My issue is about dragging to the webview.

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.26.5. This issue doesn't happen on Windows/Linux.

**Comment by rogerwang** [comment]
@Christywl does it reproduce with Chrome browser and the sample chrome app?

**Comment by Christywl** [comment]
On Mac, it also reproduced in Chrome App.

**Comment by phiSgr** [comment]
Just tried on a Windows machine. Although dragging from app to webview in Windows do not break dragging from other windows to webview, the problem of unable to drag from app to webview still exists.

Sorry for not phrasing my concerns clearly.

**Comment by rogerwang** [comment]
@phiSgr please report this to Chromium upstream since it also reproduces in Chrome browser.

**Comment by kritikaperiwal12** [comment]
While loading HTML string in web view it is showing a blank grey box with question mark sign.
**Code:**   webView.loadHTMLString("<html><body><style><img {position: absolute;top: 50%;left: 50%;width: 500px;height: 500px;margin-top: -250px;margin-left: -250px;}html, body, #wrapper { height:100%width: 100%;margin: 0;padding: 0;border: 0;}#wrapper td {vertical-align: middle;text-align: center;}</style></head><body style='width:500px; height:500px; padding-right:30%; padding-left:30%;'><table id='wrapper'><tr><td><img src=\"file://\(filePathUrl)\"></td></tr></table></body></html>", baseURL: nil)
Can anyone help?
