### ISSUE TITLE
How to get lost focus event in app-region setting area？

### ISSUE THREAD

**Issue by ZeeRoc** [nwjs/nw.js#6286]
NWJS Version : nwjs-sdk-v0.14.7-win-ia32
Operating System : windows 10

### Expected behavior

I set the A label has lost the focus event, used to hide the menu item, but in app-region = drag area can not capture this event, how to solve?

### Actual behavior

I hope like js, set the blur event, click anywhere on the page to trigger this event, to hide the effect of the menu

![image](https://user-images.githubusercontent.com/13727732/32713530-9aca663a-c884-11e7-81bf-ddee2546674d.png)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
