### ISSUE TITLE
<webview>.setZoom() BugReport

### ISSUE THREAD

**Issue by dstiq** [nwjs/nw.js#6287]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.25.2
Operating System :
Windows 10 x64
### Expected behavior

When you created few 'webview'  with different id and names, you could '.setZoom(integer)' any of that. 

### Actual behavior
Just when create ` <webview src="https://' + some_url + '"></webview> `, and second one is same,
when you zoom first one, the SECOND one is getting same zoom params
### How to reproduce
For example you can create x3 `<webview>`  with different id and names, 'webview#1' and 'webview#2' have same `src="http://' + some_url + '"`.
'<webview#3' have another `src="' + any + '"`
try to set Zoom severally

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.26.5.

**Comment by dstiq** [comment]
Probably its working like a standart chrome zoom tool ?

**Comment by rogerwang** [comment]
@Christywl could you check is it happening in Chrome app with Chrome browser?

**Comment by Christywl** [comment]
Yes, it also happens in Chrome App with Chrome 62.

**Comment by rogerwang** [comment]
@dstiq please report this to Chromium upstream. Thanks.
