### ISSUE TITLE
onbeforeunload not working in webview

### ISSUE THREAD

**Issue by Virius** [nwjs/nw.js#6288]
NW.js v0.22.3 (also check on v0.26.5
OS: Win10 x64

### Expected behavior

If the site opened in the webview uses onbeforeunload event, a confirm dialog should occur when the page changes

### Actual behavior

dialog does not appear.

### How to reproduce

index.html

`<!DOCTYPE html>`
`<body>`
`<webview src="https://js.do" style="position: fixed;z-index: 100;bottom: 0;top: 0;left: 0;right: 0;">`
`</body>`

package.json

`{
	"name": "Test",
	"main": "index.html"
}`

- open nw.js
- change text in left textarea
- click on any link to change page

If open url through nw.Window.open all works fine. But in webview - it is not

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.26.5.

**Comment by rogerwang** [comment]
@Christywl could you check is it happening in Chrome app with Chrome browser as well?

**Comment by Christywl** [comment]
Yes, this issue also happens in Chrome App with Chrome 62.

**Comment by rogerwang** [comment]
@Virius please report this to Chromium upstream. Thanks.

**Comment by rogerwang** [comment]
upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=787881
