### ISSUE TITLE
Some videos will not play in Chrome App in NW JS

### ISSUE THREAD

**Issue by marlarius** [nwjs/nw.js#6289]
I have found that certain videos will not play in webview inside Chrome Apps running in NW JS.

For easiest reproduction of the issue, you can try installing [this sample](https://github.com/googlearchive/chrome-app-samples/tree/master/samples/webview-samples/browser).

It has also a version active on [Chrome web store](https://chrome.google.com/webstore/detail/browser-sample/edggnmnajhcbhlnpjnogkjpghaikidaa) for running directly in Chrome.

For example, these videos will not play inside NW JS, but they work fine in apps running in Chrome:

https://www.svtplay.se/video/30987/alfons-aberg/alfons-aberg-sasong-1-avsnitt-10-slutbusat-alfons-aberg
https://arenan.yle.fi/1-4219423
https://tv.nrk.no/serie/side-om-side/MUHH52000117/sesong-5/episode-1
https://demo.theoplayer.com/test-your-stream-with-statistics

It is not a Flash issue. I have Pepper Flash installed in my app and these videos do not use Flash anyway.

It is tested in version v0.26.5 in both Linux and Windows 7:

nwjs-sdk-v0.26.5-linux-x64
nwjs-sdk-v0.26.5-win-ia32

At first I thought it was a DRM issue, but these videos play inside Chrome even if I disable playing of protected contents in the settings.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.26.5.

**Comment by rogerwang** [comment]
@Christywl is it video in proprietary codecs?

**Comment by Christywl** [comment]
Check with Chrome browser, use `chrome://media-internals/` to check these videos, all of them are h264.

**Comment by rogerwang** [comment]
So close this issue as it's expected. See more information here: http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#supported-codecs-in-prebuilt-nwjs-binary

**Comment by marlarius** [comment]
Thanks guys. Didn't know about the neat chrome://media-internals/ trick :-)
Using the correct libffmpeg solves it.
