### ISSUE TITLE
Add mouse tracking support

### ISSUE THREAD

**Issue by softwarezhu** [nwjs/nw.js#629]
Hi, I think the mouse tracking support is very useful. Both MFC and QT have this feature. The window can handle the global mouse event even through the window is not focused. Can you add this feature to node-webkit?

**Comment by kitemao** [comment]
please, i have this problem now,  has been fixed?

**Comment by Mithgol** [comment]
I have already deleted the code that I used two years ago to reproduce this problem.

However, if you still observe this problem, we have to assume that it remains (i.e. either has never been fixed or has resurfaced).

You (@kitemao) should check if the problem persists not only in nw.js, but also in Chromium. If the latter's to blame, then the problem has to be reported to the Chromium's developers (yet again).
