### ISSUE TITLE
nw.js crashes when the specific PDF is loaded in the webview

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#6293]
NWJS Version : 26.6 win 64bit and 32bit SDK (also 25.4 win 64bit SDK)
Operating System : Windows 8.1 64bit

### Expected behavior

When loading PDF document in the webview inside of nwjs app, app should not crash (disappear)

### Actual behavior

When loading a specific PDF document in webview inside of nwjs app, app just disappears

### How to reproduce

Unpack the attached nwjs_pdf_webview_crash.zip and drag-and-drop crash_case folder with sample case onto nw.exe to launch it. Upon opening sample app, try interacting with pdf document loaded in webview e.g. by scrolling webview and app will crash.

I have also included crash dump in the crash_dump folder in the attached zip.

[nwjs_pdf_webview_crash.zip](https://github.com/nwjs/nw.js/files/1474412/nwjs_pdf_webview_crash.zip)

**Comment by rogerwang** [comment]
Thanks for reporting. It's crashed when requesting showing JS dialog.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by krneticz** [comment]
@rogerwang Thanks, man, that was damn fast! :) Will try and let you know.

**Comment by krneticz** [comment]
@rogerwang it is definitely fixed in nw26-f6d394a-2ae52e2-05043ec-58095c1 thank you very much! Do you think  nw26-f6d394a-2ae52e2-05043ec-58095c1 is good to go to production? When is 26.7 relese expected?

**Comment by rogerwang** [comment]
We don't have any plan to release it yet. But it's in release quality.
