### ISSUE TITLE
Serialport problem on nwjs

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [nwjs/nw.js#6297]
Hello, i get some problem with nwjs and serialport, my application is starting without any problem as long as i'm not using "var SerialPort = require("serialport");"
If i add that, my localhost is not starting at all and i get a blank page.

i tried the  nw-gyp without any success, any help would be greatly appreciated :)

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

Chances are that you didn't recompile it for NW: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/

**Comment by Cedric-Lefebvre** [comment]
thx a lot :)
