### ISSUE TITLE
webview.executeScript wrong context

### ISSUE THREAD

**Issue by dmx-patrick** [nwjs/nw.js#6299]
NWJS Version : 0.26.6
Operating System : Windows 10

### Expected behavior

I expect it to execute the script in the isolated context where my contentScripts are loaded

### Actual behavior

It executes the script in the main context

### How to reproduce

```js
webview.addEventListener('loadcommit', function(e) {
  webview.addContentScripts([{
    name: 'inject',
    matches: [ '<all_urls>'],
    js: { files: ['jquery.js'] },
    run_at: 'document_end'
  }]);
});

webview.addEventListener('contentload', function(e) {
  webview.executeScript({ code: '$("body").css("background", "red")' });
});
```

In the isolated context you have full access to the dom and I don't want to inject my libraries directly in the guest page since they could conflict with other scripts that are loaded there. If I would like to execute directly within the guest context I would have used an iframe instead of a webview.

The default behavior was changed in version 0.26.5, related issue: #6229

**Comment by rogerwang** [comment]
Will add a boolean field mainWorld in InjectDetails to control the world where the code would run. The default value would be false to keep align with upstream.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
