### ISSUE TITLE
nwjs crash often

### ISSUE THREAD

**Issue by haroldjiang** [nwjs/nw.js#6300]
we are using nwjs as hybrid app on pc windows,and sometimes it crashs without any dump file,diffcult to locate the reason,is there any way or tools can sovle this problem? thanks

**Comment by rogerwang** [comment]
What's the version are you using? And could you please provide a sample so we can reproduce?

**Comment by dstiq** [comment]
Try to run your app with cmd for example: 
` "nw.exe path" "entrypoint path" --enable-logging=stderr`
That working for me on version 0.25.2

**Comment by rogerwang** [comment]
Close until more information is available.

**Comment by proxy-m** [comment]
extensions::app.window:126 Uncaught TypeError: Cannot read property 'boundsKey_' of undefined
    at Bounds.setPosition (extensions::app.window:126)
    at Bounds.set [as left] (extensions::app.window:58)
    at NWWindow.moveTo (extensions::nw.Window:510)

[nwjs-sdk-v0.27.3-win-x64]

**Comment by proxy-m** [comment]
extensions::app.window:55 Uncaught TypeError: Cannot read property 'boundsKey_' of undefined
    at Bounds.get [as left] (extensions::app.window:55)
    at NWWindow.get (extensions::nw.Window:540)

[nwjs-sdk-v0.27.3-win-x64]

**Comment by proxy-m** [comment]
It may happens when playing with positioning/sizind of window on timeout. But not always.

**Comment by zaggerj** [comment]
> It may happens when playing with positioning/sizind of window on timeout. But not always.

can you solved this problem?
