### ISSUE TITLE
process is undefined when using --url argument

### ISSUE THREAD

**Issue by pchuong** [nwjs/nw.js#6302]
NWJS Version : 0.26.7
Operating System : Windows7

### Expected behavior
I don't know whether this is a feature or a bug, when I start nw.exe with --url argument, typeof process is undefined.

### Actual behavior
When starting nw.exe with --url, typeof process is undefined.

### How to reproduce
execute "nw.exe --url=http://www.google.com"

**Comment by rogerwang** [comment]
This is expected. Remote normal website should not have access to Node APIs by default. You can use a package.json with node-remote defined and point 'main' to the remote site.

**Comment by pchuong** [comment]
Hi Roger, the reason I can't use package.json is that I can't use dynamic port number of a local webserver through main.  Is it possible to support package.json in conjunction with using --url parameter? 

Also, without using package.json, I can't get the version of nw within the app.

**Comment by rogerwang** [comment]
Could you please elaborate it so I can understand your situation better?

**Comment by pchuong** [comment]
I have an app that can run on a browser (chrome, firefox, etc...) hosted by a service provider and the same app also can be run locally on a user's machine as a standalone application using NodeWebkit as the browser with a local webserver. Hence, running it on a local webserver required to use a dynamic port number. Using the package.json by setting main doesn't allow me to dynamically change the port number. So, I use the --url approach when starting up nw.exe. I like to be able to get the nw.exe version to display it in the dialog for legal purpose when shipping NodeWebkit as a product. Additionally, there are other events that I like to hookup to the NodeWebkit window object. Such as the window close event, so that I can safely shutdown the local webserver when the user close the NodeWebkit window.
