### ISSUE TITLE
OSX - Transparency clickthrough broken on High Sierra

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6307]
OSX High Sierra 10.13.1 Retina 5K
Clickthrough not working - tried 0.27.0rc1/0.26.7/0.17.6/0.14.7 (tried both --disable-gpu and --disable-gpu-composited).

Works fine on a Mavericks VM on High Sierra using 0.17.6 (also with --disable-gpu) and also fine on another machine with Yosemite
Attached is test app -

[TransTest.zip](https://github.com/nwjs/nw.js/files/1505126/TransTest.zip)

**Comment by Christywl** [comment]
I can reproduce this issue on Mac High Sierra with nwjs-sdk-v0.26.6. It works fine on Mac 10.12.6.

**Comment by rogerwang** [comment]
cc @jtg-gg

**Comment by Blatman** [comment]
Ah - also noticed that if devtools window is used if it is closed the transparent area becomes white ....
Cheers.

**Comment by thedracle** [comment]
Maybe these new warning messages that are popping up are related:

017-11-28 20:12:00.246 nwjs[4341:111413] *** WARNING: Textured window <AppFramelessNSWindow: 0x7fd166543290> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by rogerwang** [comment]
@Blatman does the devtools issue appear on 10.12 or earlier version of macOS?

**Comment by Blatman** [comment]
@rogerwang tried it on Yosemite (10.10.5 - MBP) and it failed also - got white background when tools closed. Possibly a separate issue?
Trying to get an El Capitan VM going but not having much luck.

**Comment by rogerwang** [comment]
@Blatman yeah. it should be different. Please submit another issue for it.

**Comment by rogerwang** [comment]
btw, with your case I get a window with nothing visible in a 10.10 and 10.12 system. But in a 10.13 system the transparent picture with a square is correctly displayed. Is that what you've got?

**Comment by Blatman** [comment]
@rogerwang unable to test 10.12 - can't get the VM working properly but on 10.10 the window works OK and shows problem - just opened #6343 for this issue.
Cheers.

**Comment by Blatman** [comment]
@rogerwang may be a red herring but I do get similar issues to you when I try the testapp in the VM - basically my  10.11 VM (Parallels) shows the window but no content(this also happens when opening SublimeText!) , I also find that dragging nwjs binaries from the host to the guest results in the symlinks in nwjs Framework.framework becoming actual folders therefore breaking the app - something is not right with Parallels .... My successful troubleshooting is on actual machine installs of OSX.

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/102
please also patch nw27

**Comment by rogerwang** [comment]
Thanks! merged into nw28, will see nw27 as well.

**Comment by Blatman** [comment]
Just tried latest 0.27 http://dl.nwjs.io/live-build/nw27/01-17-2018/ff9b366-d2ae21b-a3ef615-6c8870e/  build and click-through only works with --disable-gpu but the debug window that is opened programatically is blank with a white background. (click-through with --disable-gpu-composited does not work - which setting is meant to be used these days?).
Cheers

**Comment by jtg-gg** [comment]
@Blatman you must use these 2 params together "--disable-gpu-compositing --force-cpu-draw"
then the package.json must use
  "window":{
    "frame": false,
    "transparent": true,
    "resizable": false
}

frame: false, and resizable:false is needed for click through transparency

**Comment by jtg-gg** [comment]
@rogerwang just now I found a "regression", the window can't be maximized / fullscreen (though transparent window is defined as "resizable:false", but this feature works on existing version)
will fix this tomorrow

**Comment by Blatman** [comment]
@jtg-gg thanks for that I was using composited rather than compositing - my error.
The blank debug window with white background still occurs but I think this will probably be addressed by #6343. The click-through is fine. Thanks.

**Comment by jtg-gg** [comment]
@rogerwang I have the pull request for the regression https://github.com/nwjs/chromium.src/pull/103

**Comment by rogerwang** [comment]
@jtg-gg 👍  merged.

**Comment by thedracle** [comment]
Is there a live build for the above fix allowing maximizing the window?

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw28/01-22-2018/d70c598-55883ed-2d8d099-3b59d35/v0.28.0/

**Comment by thedracle** [comment]
Thanks Roger. 

Maximizing fixes this weird click offset issue. It's probably something to do with the page layout or some odd chrome rendering bug, and nothing to do with NWJS.

**Comment by cecilpeng** [comment]
Do nwjs 0.27.6 support it? Is it stable now?

**Comment by rogerwang** [comment]
@cecilpeng there is no plan to release 0.27.6 as 0.28.0 is to be released soon with this fix. However the live build version of 0.27.6 is in release quality.

**Comment by cecilpeng** [comment]
@rogerwang I am glad to see stable 0.28.0 soon.
