### ISSUE TITLE
Set new size and position of windows

### ISSUE THREAD

**Issue by sadikyalcin** [nwjs/nw.js#6308]
This isn't really a bug but I think it's been designed to work like this. When you open a window (including the main app window), the OS or chromium remembers the size and position the window was at. Next time you open it, it will be sized and positioned on the state you had it at before you closed it. I got around this with `resizeTo` and `setPosition` methods on the main app window after a timeout but need a better way of doing this in app for other windows...

NWJS Version : 0.26.5
Operating System : OS X El Capitan

### Expected behavior

Open window with options set on `nw.Window.open`

### Actual behavior

The size and position is set via some sort of cache from the state it was in before it was closed.

### How to reproduce

- Create a page with few links that opens new windows. I.e;

```
onClick = function(){
    nw.Window.open(url, {
        id: 'local-' + presid,
        position: 'center',
        width: 1366,
        height: 768,
        frame: true,
        //new instance causes jQuery conflict error
    }, function(win) {
            // log the width / height = 1366 / 768
            if(typeof win !== 'undefined'){
                    win.on('closed', function() {
                        console.log('view closed');
                    });
                    win.on('loaded', function() {
                        win.focus();
                });
            }
        });
    }
});
```
- After opening another window, resize it and reposition it with your mouse

- Close the window

- Re-open the window

- You can now see the window is not 1366 / 768 anymore, nor positioned in the centre of the screen

![screen-recording](https://user-images.githubusercontent.com/8109619/33267846-dc8ce0ea-d372-11e7-8b32-b8ab73594124.gif)

**Comment by Asp3ctus** [comment]
don't use "id" - props
id {String} Optional the id used to identify the window. This will be used to remember the size and position of the window and restore that geometry when a window with the same id is later opened. See also the Chrome App documentation https://developer.chrome.com/apps/app_window#type-CreateWindowOptions

**Comment by Christywl** [comment]
@sadikyalcin , could you please try again without 'id' in your test. I try a simple test without 'id' in window options on nwjs v0.26.6, it works fine.

**Comment by sadikyalcin** [comment]
Yes it does work as intended without the id but how else will I identify the windows? I'm not restricting the amount of windows opened and possibly need to know which one is which...

On another note, is it possible to get the frame height (close, minimize, maximize) via nw.js - pretty pointless to open another ticket for this and couldn't see anything in docs...
