### ISSUE TITLE
nwjs crashes on startup with --url parameter

### ISSUE THREAD

**Issue by pchuong** [nwjs/nw.js#6312]
NWJS Version : v27 nightly https://dl.nwjs.io/live-build/12-05-2017/nw27-4a542eb-da56e80-933eb7a-c0569cf/v0.27.0/
Operating System : Windows7

### Expected behavior
nw.exe shouldn't crash. Here is the dmp file: [2bd12f0e-7ec3-40f3-b4f6-7f95f3aa514c.zip](https://github.com/nwjs/nw.js/files/1531685/2bd12f0e-7ec3-40f3-b4f6-7f95f3aa514c.zip)

### Actual behavior
nw.exe crashed

### How to reproduce
run nw.exe --url="https://dev.ti.com/gallery/view/4882621/BOOSTXL_AoA_GUI/"

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build. Thanks for reporting.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/12-06-2017/nw27-4a542eb-de32390-933eb7a-c0569cf/v0.27.0/
