### ISSUE TITLE
Wrong Elf Class 64

### ISSUE THREAD

**Issue by quantumproducer** [nwjs/nw.js#6313]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.23.7
Operating System : Ubuntu 16.04 LTS

### Expected behavior

Program should launch

### How to reproduce

Download linux version at http://quantumpilot.me
run QuantumPilot

**Comment by quantumproducer** [comment]
It seems to be because the 64 bit version is required. So I tried using the 64 bit version and I get a popup "Your profile cannot be used because it runs on a previous version of NW.js" -- but both are using the same `0.23.7` version.

**Comment by Christywl** [comment]
I can't reproduce your issue. I download and try to run it on Linux(64bit), the app could be launched, just an error appears in the console.
![6313](https://user-images.githubusercontent.com/20039821/33818612-e64af630-de80-11e7-86c8-b7d8991551cb.png)

**Comment by quantumproducer** [comment]
@Christywl got it, it was due to missing greenworks files.
