### ISSUE TITLE
crash frequently on windows

### ISSUE THREAD

**Issue by wythe0102** [nwjs/nw.js#6316]
we often get crash report from our users,more client,more frequent.the belows are two time crash of all reports.how can we resolve this prolem?thans in advance.

NWJS Version : 0.12.0
Operating system: Windows NT
                  6.1.7601 23889
CPU: x86
     GenuineIntel family 6 model 60 stepping 3
     2 CPUs

Crash reason:  EXCEPTION_ACCESS_VIOLATION_EXEC
Crash address: 0xffffffff

### Expected behavior

nwjs should not crashed

### Actual behavior

nwjs  crashed many times,
twice crash lately, 

### How to reproduce
sometimes it just accidently crashed and can't reproduce it constantly.
------------------------------------------1st time------------------------------------------------------------
 1. Thread 0 (crashed)
 0  0xffffffff
    eip = 0xffffffff   esp = 0x003ef0e0   ebp = 0x003ef0e4   ebx = 0x082456f0
    esi = 0x0bcd6738   edi = 0x5f790db8   eax = 0x0abc5850   ecx = 0x008a64e8
    edx = 0x5f19f4cc   efl = 0x00010246
    Found by: given as instruction pointer in context
 1  nw.dll!mergeT<unsigned short>(unsigned short const *,int,unsigned char const *,int,unsigned short *) [skaaclip.cpp : 2087 + 0x1]
    eip = 0x5bfaaba1   esp = 0x003ef0ec   ebp = 0x003ef13c
    Found by: previous frame's frame pointer
 2  nw.dll!cricket::TurnPort::HandleChannelData(int,char const *,unsigned int,rtc::PacketTime const &) [turnport.cc : 723 + 0xd]
    eip = 0x5d6c8ba4   esp = 0x003ef144   ebp = 0x003ef14c
    Found by: call frame info
 3  nw.dll!blink::SVGFETurbulenceElement::SVGFETurbulenceElement(blink::Document &) [svgfeturbulenceelement.cpp : 57 + 0x19e]
    eip = 0x5d67b72f   esp = 0x003ef154   ebp = 0x003ef1bc
    Found by: call frame info
 4  nw.dll!blink::getStaticStringEntries<blink::SVGStitchOptions>() [svgfeturbulenceelement.cpp : 32 + 0x38]
    eip = 0x5d67b2ec   esp = 0x003ef1c4   ebp = 0x003ef1cc
    Found by: call frame info
 5  nw.dll!blink::FileUploadControlPainter::paintObject(blink::PaintInfo const &,blink::LayoutPoint const &) [fileuploadcontrolpainter.cpp : 45 + 0xe]
    eip = 0x5d65566c   esp = 0x003ef1d4   ebp = 0x003ef1d8
    Found by: call frame info
 6  nw.dll!v8::internal::Builtins::InitBuiltinFunctionTable() [builtins.cc : 1520 + 0x56d]
    eip = 0x5b7ed5c6   esp = 0x003ef1e0   ebp = 0x003ef204
    Found by: call frame info
 7  nw.dll!v8::internal::FlexibleBodyVisitor<v8::internal::MarkCompactMarkingVisitor,v8::internal::JSObject::BodyDescriptor,void>::Visit(v8::internal::Map *,v8::internal::HeapObject *) [objects-visiting.h : 249 + 0x181]
    eip = 0x5b7ff79a   esp = 0x003ef20c   ebp = 0x003ef204
    Found by: stack scannin

-------------------------------------------------2ed time----------------------------------------------------

Thread 15 (crashed)
 0  nw.exe!std::_Tree<std::_Tmap_traits<__int64,content::AppCacheStorageImpl::CacheLoadTask *,std::less<__int64>,std::allocator<std::pair<__int64 const ,content::AppCacheStorageImpl::CacheLoadTask *> >,0> >::find(__int64 const &) [xtree : 1549 + 0x0]
    eip = 0x008e9343   esp = 0x0c46f788   ebp = 0x0c46f788   ebx = 0x00741880
    esi = 0x00000004   edi = 0x00000004   eax = 0x0c46f7b0   ecx = 0x00000004
    edx = 0x00000000   efl = 0x00010202
    Found by: given as instruction pointer in context
 1  nw.exe!content::ResourceScheduler::OnAudibilityChanged(int,int,bool) [resource_scheduler.cc : 953 + 0x29]
    eip = 0x00774290   esp = 0x0c46f790   ebp = 0x0c46f7a8
    Found by: call frame info
 2  nw.exe!content::AudioRendererHost::DeleteEntry(scoped_ptr<content::AudioRendererHost::AudioEntry,base::DefaultDeleter<content::AudioRendererHost::AudioEntry> >) [audio_renderer_host.cc : 449 + 0x43]
    eip = 0x007418ea   esp = 0x0c46f7b0   ebp = 0x0c46f7c8
    Found by: call frame info
 3  nw.exe!base::internal::Invoker<2,base::internal::BindState<base::internal::RunnableAdapter<void ( media::AudioInputController::*)(scoped_ptr<media::AudioBus,base::DefaultDeleter<media::AudioBus> >)>,void ,void >,void >::Run(base::internal::BindStateBase *) [bind_internal.h : 562 + 0x15]
    eip = 0x00f7faac   esp = 0x0c46f7d0   ebp = 0x0c46f7e4
    Found by: call frame info
 4  nw.exe!base::`anonymous namespace'::PostTaskAndReplyRelay::RunReplyAndSelfDestruct() [post_task_and_reply_impl.cc : 58 + 0x7]
    eip = 0x002b38de   esp = 0x0c46f7ec   ebp = 0x0c46f7f8
    Found by: call frame info
 5  nw.exe!base::debug::TaskAnnotator::RunTask(char const *,char const *,base::PendingTask const &) [task_annotator.cc : 63 + 0x7]
    eip = 0x002b3e49   esp = 0x0c46f800   ebp = 0x0c46f8a8
    Found by: call frame info
 6  nw.exe!base::MessageLoop::RunTask(base::PendingTask const &) [message_loop.cc : 447 + 0x15]
    eip = 0x0029c368   esp = 0x0c46f8b0   ebp = 0x0c46f998
    Found by: call frame info
 7  nw.exe!base::MessageLoop::DoWork() [message_loop.cc : 564 + 0xa]
    eip = 0x0029bb82   esp = 0x0c46f9a0   ebp = 0x0c46fa1c
    Found by: call frame info
 8  nw.exe!base::MessagePumpForIO::DoRunLoop() [message_pump_win.cc : 510 + 0xb]
    eip = 0x002b46c0   esp = 0x0c46fa24   ebp = 0x0c46fc78
    Found by: call frame info
 9  nw.exe!base::MessagePumpWin::Run(base::MessagePump::Delegate *) [message_pump_win.h : 34 + 0x3c]
    eip = 0x002b4e2d   esp = 0x0c46fc80   ebp = 0x0c46fc98
    Found by: call frame info
10  nw.exe!base::MessageLoop::RunHandler() [message_loop.cc : 415 + 0x8]
    eip = 0x0029c120   esp = 0x0c46fca0   ebp = 0x0c46fcc8
    Found by: call frame info
11  nw.exe!base::RunLoop::Run() [run_loop.cc : 55 + 0x6]
    eip = 0x002a2bd8   esp = 0x0c46fcac   ebp = 0x0c46fcc8
    Found by: stack scanning
12  nw.exe!base::MessageLoop::Run() [message_loop.cc : 308 + 0x7]
    eip = 0x0029c0d6   esp = 0x0c46fcd0   ebp = 0x0c46fcec
    Found by: call frame info
13  nw.exe!base::Thread::Run(base::MessageLoop *) [thread.cc : 174 + 0x7]
    eip = 0x002aa75b   esp = 0x0c46fcf4   ebp = 0x0c46fcf4
    Found by: call frame info
14  nw.exe!content::BrowserThreadImpl::IOThreadRun(base::MessageLoop *) [browser_thread_impl.cc : 218 + 0xb]
    eip = 0x006b36ff   esp = 0x0c46fcfc   ebp = 0x0c46fdbc
    Found by: call frame info
15  nw.exe!content::BrowserThreadImpl::Run(base::MessageLoop *) [browser_thread_impl.cc : 253 + 0x9]
    eip = 0x006b3d01   esp = 0x0c46fdc4   ebp = 0x0c46fe80
    Found by: call frame info
16  nw.exe!base::Thread::ThreadMain() [thread.cc : 228 + 0x9]
    eip = 0x002aab05   esp = 0x0c46fe88   ebp = 0x0c46fe9c
    Found by: call frame info
17  nw.exe!base::`anonymous namespace'::ThreadFunc(void *) [platform_thread_win.cc : 78 + 0x8]
    eip = 0x002ab631   esp = 0x0c46fea4   ebp = 0x0c46feb8
    Found by: call frame info
18  kernel32.dll + 0x13369
    eip = 0x7614336a   esp = 0x0c46fec0   ebp = 0x0c46fec4
    Found by: call frame info
19  ntdll.dll + 0x398f1
    eip = 0x775a98f2   esp = 0x0c46fecc   ebp = 0x0c46ff04
    Found by: previous frame's frame pointer
20  ntdll.dll + 0x398c4
    eip = 0x775a98c5   esp = 0x0c46ff0c   ebp = 0x0c46ff1c
    Found by: previous frame's frame pointer

**Comment by rogerwang** [comment]
I'm afraid 0.12.x is not maintained any more. Please upgrade to the latest version.
