### ISSUE TITLE
window.location.href doesn't work in NW.js 12.3 Native Menu

### ISSUE THREAD

**Issue by RandyMustache** [nwjs/nw.js#6317]
For the purposes of my application, I've needed to create a "home" link within the NW.js native menu. The app right now is a kind of directory that leads to other NW.js apps, loading each within the main window just using standard a href in the html. That part works exactly as expected.

For the menu, I need to go back to the original app's index.html (these are all locally hosted and stored). 

My code:

```````javascript
    file.append(new gui.MenuItem({
    label: 'Home',
    click: function() {
        
        win.window.location.href = "file:///D:/myApp/index.html"
        
    }
    }));
````````

That would be the ideal way to load it, as that would just open it within the same NW.js window. But it doesn't work. At all.

What does work:
````````javascript
        win.window.history.back()  
````````
and
````````javascript
    gui.Window.open("file:///D:/myApp/index.html");
````````
Obviously back isn't viable.

Opening a new window is ok, since it seems to be the same process. But still not ideal. It really does need to be in the same window, due to potential whitelisting issues.

Also tried:
````````javascript
    win.window.location.href = ""
````````
Thanks in advance everyone.

Just a heads up, I am locked into 12.3 due to legacy issues, the question isn't "oh this will work in latest build", unfortunately, that isn't an option, so any help related to 12.3 would be awesome.

**Comment by rogerwang** [comment]
I am afraid 0.12 is not maintained any more. We'd be glad to fix issues in the latest version preventing you to upgrade. Thanks.
