### ISSUE TITLE
Mirror screen when use --use-skia-renderer argument

### ISSUE THREAD

**Issue by StrategJuvty** [nwjs/nw.js#6320]
NWJS Version : 27.0
Operating System : Win 10

### Expected behavior

Normal view as it was in NWJS 26.6.

### Actual behavior

Mirror screen: https://yadi.sk/i/nG2vOOkq3QSdkU

### How to reproduce

place --use-skia-renderer in chominium-args

**Comment by rogerwang** [comment]
Could you please elaborate? I don't understand the situation about "mirror screen".

**Comment by Christywl** [comment]
package.json:
```
{
    "main": "index.html",
    "name": "6320",
    "chromium-args": "--use-skia-renderer"
}
```
nwjs v0.27.0:
![image](https://user-images.githubusercontent.com/20039821/33812479-c078ad80-de58-11e7-9ad9-3d245236e9cc.png)

**Comment by rogerwang** [comment]
Thanks. Does Chrome 63 have the same issue?

**Comment by Christywl** [comment]
Yes, Chrome 63 also have this issue on Windows.

**Comment by rogerwang** [comment]
@StrategJuvty  Please report this issue to Chromium project. Thanks.
