### ISSUE TITLE
trap invalid opcode ip:7fdcd...

### ISSUE THREAD

**Issue by gv1dev** [nwjs/nw.js#6327]
My desktop-application uses (NWJS Version) nwjs-sdk-v0.26.0-linux-x64

and runs on, Ubuntu 64bit 16.04 (it is installed in VirtualBox 5.2.2 r119230 (Qt5.6.2))

I received the following fault in the kernel log:
Dec 13 03:11:39 my-VM kernel: [48881.531804] traps: exe[3548] trap invalid opcode ip:7fdcd4a05baf sp:7ffc3c610cb0 error:0 in libnw.so[7fdcd0163000+6879000]

After a few seconds my application was terminated as the front-end part terminated...

In my terminal from were i run the app, Ireceived the following log , but I cann't make out what it means...:

Security context: 0x23e0cf2f7c81 <String[51]: chrome-extension://ednklffcalimonpeimpkbjkjnlfcodjf>
    1: animate [chrome-extension://ednklffcalimonpeimpkbjkjnlfcodjf/js/jquery-2.2.4.min.js:~3] [pc=0x491ee26138d](this=0x1631180d9d71 <JSObject>,a=0x2e29ae3c299 <Object map = 0x196739699909>,b=1000,c=0x39ad78d822d1 <undefined>,d=0x39ad78d822d1 <undefined>)
    2: blinker [chrome-extension://ednklffcalimonpeimpkbjkjnlfcodjf/js/websockects/web...

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this?

**Comment by gv1dev** [comment]
Unfortunately to provide some source code is not an option...
But I checked the logs that are produced by the chromium and there was no info about the crash. I checked also the minidumps that were created after the crush but again no relevant info was in there.
Any other idea to acquire some logs or to debug the app is highly welcomed !
Thank you!

**Comment by GnorTech** [comment]
The reason should be that the compiled official binary has some instructions that your CPU doesn't support. Maybe your virtual CPU's model is too old. You could try to run Chromium browser there first.

**Comment by gv1dev** [comment]
I don't think that is an issue of the virtual CPU. I use Virtual Box Version5.2.2 r119230 (Qt5.6.2) , and one core.
My CPU is  Intel Core - i5-7200U.
user@user-VM:$ more /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
stepping	: 9
cpu MHz		: 2712.004
cache size	: 3072 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good n
opl xtopology nonstop_tsc pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 x2apic 
movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch avx2 rdse
ed clflushopt

**Comment by rogerwang** [comment]
@gv1dev does the Chromium browser run well in the same system?

**Comment by gv1dev** [comment]
@rogerwang  Yes the Chromium browser (Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)) runs correctly on the same system, without any problems , it looks stable.
