### ISSUE TITLE
nwjs app rejected by app store coz of private API, crash on 10.13 High Sierra, menu item contains text nwjs instead of App name

### ISSUE THREAD

**Issue by swati-srivastava** [nwjs/nw.js#6329]
My Mac app based on NWJS got rejected coz for 3 reasons:

**Usage of Private API listed below.**
'/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'  '/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit'  '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices'  '/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics

**The App doesn't work on 10.13 High Sierra**
**MyApp** OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(WWW!,OURL handler=0x7fff5129f9fc isSys=NO) err=0/noErr error	
**MyApp** Month 13 is out of bounds
**launchservicesd**	CHECKIN:0x0-0x8b08b 2436 com.test.mac
**MyApp**	LSExceptions shared instance invalidated for timeout.

**Menu Item contains "About nwjs" instead of "About MyApp"**
I cant find a way to change this. Inside App/Contents/Resources/en.lproj and other folders, all the infoplist.strings contains
CFBundleDisplayName = "MyApp";
CFBundleName = "MyApp";
CFBundleExecutable = "MyApp";

**Comment by rogerwang** [comment]
Thanks for reporting. What's the version are you using?

**Comment by swati-srivastava** [comment]
NWJS used: nwjs-sdk-v0.23.6-osx-x64

**Comment by rogerwang** [comment]
The MAS build is used to support the application store, but it's still on 0.19. Please use the build referred in http://docs.nwjs.io/en/latest/For%20Users/Advanced/Support%20for%20Mac%20App%20Store/. @sunlin-link is working on updating it to the latest stable version.

Regarding the crash on macOS 10.13, please use the latest stable version 0.27.

**Comment by rogerwang** [comment]
btw, please file multiple issues for each you found respectively.

**Comment by swati-srivastava** [comment]
What about the App Menu Item, how can I remove unwanted Menu Items?

Also, I found somewhere that from NWJS 0.19 onwards MAC Appstore uploading is supported but now it's not working. I want to support 10.13 as well as I wish to upload to my App to Appstore. Any suggestions what should I do?

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by swati-srivastava** [comment]
I need to update/remove App Menu Items. 
Please lemme know How can I achieve this.
