### ISSUE TITLE
Right click flash object in iframe crashes nw

### ISSUE THREAD

**Issue by Bigmacbook** [nwjs/nw.js#633]
I'm trying to embed a webpage with a flash object in a iframe, but flash seems to crash the app when I right click and the context menu comes up. Is there any way to fix this or do i have to wait for an update.

 I can't embed the object directly in the html because stupid flash security errors.

I'm on Windows 8.

**Comment by rogerwang** [comment]
Please try the latest 0.13.0 release. It should be fixed.
