### ISSUE TITLE
Remove / Replace Application Menu Items in NWJS Mac App

### ISSUE THREAD

**Issue by swati-srivastava** [nwjs/nw.js#6330]
Hi All,

I am using NWJS 0.23.6 version.

I renamed in Infolplist.strings of all *.lproj folders the

CFBundleDisplayName = "MyApp";
CFBundleName = "MyApp";
CFBundleExecutable = "MyApp";

Still, in App menu, I can see menu items as:
About MyApp
Exit My App
Quit MyApp
Hide MyApp

Please suggest how can I remove/rename them.

Thanks in Advance :)

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
