### ISSUE TITLE
Mouse jumps when cursor locked (PointerLock). All nwjs versions on windows 10 

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#6336]
Nothing wrong with NWJS, more details: https://bugs.chromium.org/p/chromium/issues/detail?id=781182.

Microsoft confirmed there is a bug in the Fall Creators update and PointerLock not working propely in Windows 10 (all chrome/chromium). Microsoft will fix it in 2018 on spring (!?).

New Chromium have fix (I tested 65.0.3293.0 and latest version 65.0.3297.0 working good). 

It possible to update nwjs soon? All games using PointerClick are broken on Windows 10.

**Comment by rogerwang** [comment]
Thanks for the link. According to it it's in m64 branch, which is scheduled to be released soon in 0.28 beta.

**Comment by rogerwang** [comment]
Please try this build: https://dl.nwjs.io/live-build/12-17-2017/nw28-e0ca6f7-d72f8ad-6239646-1b41f4f/v0.28.0-beta1/

**Comment by hooker99** [comment]
Thanks Roger!!! It working good!!!
