### ISSUE TITLE
Transparent Window Shows Chrome on drag Windows 7 64 bit

### ISSUE THREAD

**Issue by RobTur** [nwjs/nw.js#6337]
======== TEMPLATE BUG FORM ========

NWJS Version : nwjs-v0.27.0-win-x64
Operating System : Windows 7 64 bit

### Expected behavior

<!- What do you think should happen? ->
When creating a transparent window with no frame the app should allow drag without displaying or flashing a white toolbar at top of page

### Actual behavior

<!- What actually happens? ->
Randomly, but always with the first drag, the app chrome will flash or display at top. (titlebar) on Windows 7 64 bit and Windows 10.  This does not occur on Mac.

### How to reproduce

<!- 
index.html

html
head
/head
body style="background-color:rgba(0,0,0,0.5);-webkit-app-region: drag"
/body
/html

Package.json
{
  "name": "Test",
  "main": "index.html",
  "version": "0.0.1",
  "window": {
    "toolbar": false,
    "transparent": true,
    "frame": false,
    "title": "TITLE",
    "resizable": false,
    "fullscreen": false,
    "show": true,
    "width": 800,
    "height": 700
  }
}
/*

Run above configuration and drag the app.  On Windows 7 64 bit the title bar displays.

->

**Comment by Christywl** [comment]
Try on Windows with nwjs-sdk-v0.27.2, the title bar appears with the first drag.

![image](https://user-images.githubusercontent.com/20039821/34092924-b5094790-e400-11e7-8ead-2fec5d8d04f1.png)

Not reproduce on Linux/Mac.

**Comment by jtg-gg** [comment]
@RobTur I've made a fix, https://github.com/nwjs/chromium.src/pull/104
waiting Roger Wang to merge and make new build

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by RobTur** [comment]
@jtg-gg  Works great! 
Thank you.
