### ISSUE TITLE
can not rebuild edge module on 0.27.1 version

### ISSUE THREAD

**Issue by wythe0102** [nwjs/nw.js#6342]
======== TEMPLATE BUG FORM ========

NWJS Version :0.27.1
Operating System :   Windows_NT 6.1.7601

### Expected behavior
follow the operation on nw.js document: 
```
On Windows, you need to replace the file
<npm-path>\node_modules\node-gyp\src\win_delay_load_hook.cc with the one at https://github.com/nwjs/nw.js/blob/nw18/tools/win_delay_load_hook.cc before installing modules with node-gyp or npm.
```
nw-gyp rebuild edge success

### Actual behavior

nw-gyp rebuild edge failed

message is below:

D:\projects\yunshan-pos-frontend\node_modules\edge>nw-gyp rebuild --target=0.27.1 --arch=ia32
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.3
gyp info using node@9.2.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\projects\\yunshan-pos-frontend\\node_modules\\edge\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.nw-gyp\\0.27.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.nw-gyp\\0.27.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\nw-gyp',
gyp info spawn args   '-Dnode_lib_file="C:\\Users\\Administrator\\.nw-gyp\\0.27.1\\<(target_arch)\\node.lib"',
gyp info spawn args   '-Dnw_lib_file="C:\\Users\\Administrator\\.nw-gyp\\0.27.1\\<(target_arch)\\nw.lib"',
gyp info spawn args   '-Dmodule_root_dir=D:\\projects\\yunshan-pos-frontend\\node_modules\\edge',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\projects\\yunshan-pos-frontend\\node_modules\\edge\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Generate one project at a time in this solution. To enable parallel generation, add the "/ m" switch.
  utils.cpp
  clrfunc.cpp
  clrfuncinvokecontext.cpp
  nodejsfunc.cpp
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ nodejsfunc.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ nodejsfunc.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ nodejsfunc.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ nodejsfunc.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ clrfuncinvokecontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clrfuncinvokecontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ clrfuncinvokecontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clrfuncinvokecontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ clrfunc.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clrfunc.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ clrfunc.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clrfunc.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ utils.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ utils.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ utils.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ utils.cpp)
  nodejsfuncinvokecontext.cpp
  persistentdisposecontext.cpp
..\src\dotnet\clrfunc.cpp(330): warning C4996: 'v8::Object::SetPrototype': Was declared as rejected [D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (3320): note: See the declaration of "v8 :: Object :: SetPrototype"
  clrfuncreflectionwrap.cpp
  clractioncontext.cpp
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ nodejsfuncinvokecontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ nodejsfuncinvokecontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ nodejsfuncinvokecontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ nodejsfuncinvokecontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ persistentdisposecontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ persistentdisposecontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ persistentdisposecontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ persistentdisposecontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ clrfuncreflectionwrap.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clrfuncreflectionwrap.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ dotnet \ clrfuncreflectionwrap.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clrfuncreflectionwrap.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compilation source file .. \ src \ dotnet \ clractioncontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ dotnet \ clractioncontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
C:\Users\Administrator\.nw-gyp\0.27.1\deps\v8\include\v8.h(4186): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ common \ callbackhelper.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ common \ callbackhelper.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ common \ callbackhelper.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ common \ callbackhelper.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ common \ v8synchronizationcontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ common \ v8synchronizationcontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ common \ v8synchronizationcontext.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ common \ v8synchronizationcontext.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [], std: : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ common \ edge.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4186): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ common \ edge.cpp)
C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): error C2664: "std :: pair <std :: unique_ptr <const uint8_t [ : default_delete <_Ty >>, std :: size_t> :: pair (std :: pair <std :: unique_ptr <_Ty, s

td :: default_delete <_Ty >>, std :: size_t> &&) "Could not convert parameter 1 from" nullptr "to" nullptr && "[D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_nativeclr.vcxproj]
          with
          [
              _Ty = const uint8_t []
          ] (Compile source file .. \ src \ common \ edge.cpp)
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (4187): note: nullptr can only be converted to a pointer or handle type (compilation source file .. \ src \ common \ edge.cpp)
  v8synchronizationcontext.cpp
  callbackhelper.cpp
  edge.cpp
  coreclrembedding.cpp
  coreclrfunc.cpp
d: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ src \ coreclrembedding \ host \ libhost.h (19): warning C4099: "fx_ver_t": Type Name The "struct" Compile the source file .. \ src \ CoreCLREmbed
ding \ coreclrembedding.cp
p) [D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_coreclr.vcxproj]
  d: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ src \ coreclrembedding \ fxr / fx_ver.h (12): note: See the declaration for "fx_ver_t" (compilation source file .. \ src \ CoreCLREmbedding \ coreclrembedding.cpp )
  coreclrnodejsfunc.cpp
  coreclrfuncinvokecontext.cpp
.. \ src \ CoreCLREmbedding \ coreclrembedding.cpp (521): warning C4018: "<": Signed / unsigned mismatch [D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_coreclr.vcxproj]
.. \ src \ CoreCLREmbedding \ coreclrfunc.cpp (477): warning C4996: 'v8 :: Object :: SetPrototype': Declared as deprecated [D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_coreclr.vcxproj]
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (3320): note: See the declaration of "v8 :: Object :: SetPrototype"
  coreclrnodejsfuncinvokecontext.cpp
  utils.cpp
  pal_utils.cpp
  trace.cpp
.. \ src \ common \ utils.cpp (23): warning C4996: 'v8 :: Object :: SetPrototype': Declared as deprecated [D: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ build \ edge_coreclr.vcxproj]
  C: \ Users \ Administrator \ .nw-gyp \ 0.27.1 \ deps \ v8 \ include \ v8.h (3320): note: See the declaration of "v8 :: Object :: SetPrototype"
  fx_ver.cpp
  fx_muxer.cpp
  json.cpp
  json_parsing.cpp
d: \ projects \ yunshan-pos-frontend \ node_modules \ edge \ src \ coreclrembedding \ f
  edge_coreclr.vcxproj -> D:\projects\yunshan-pos-frontend\node_modules\edge\build\Release\\edge_coreclr.node
  edge_coreclr.vcxproj -> D:\projects\yunshan-pos-frontend\node_modules\edge\build\Release\edge_coreclr.pdb (Full PDB)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:261:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.27.1" "--arch=ia32"
gyp ERR! cwd D:\projects\yunshan-pos-frontend\node_modules\edge
gyp ERR! node -v v9.2.0
gyp ERR! nw-gyp -v v3.6.3
gyp ERR! not ok

### How to reproduce
exec this commond : nw-gyp rebuild --target=0.27.1 --arch=ia32
on windows cmd line for node module **edge** version 7.10.1

**Comment by Christywl** [comment]
I can reproduce this issue on Windows with `nw-gyp rebuild --target=0.27.2`
`nw-gyp: 3.6.3`
Not reproduce on Linux.

**Comment by rogerwang** [comment]
@Christywl does it work with 0.26.6? And what's the Visual studio version are you using?

**Comment by Christywl** [comment]
Check it with 0.26.6, it also doesn't work. The VS version is 2015.

**Comment by wythe0102** [comment]
@rogerwang 
I rebuild the printer module success. but the edge module doesn't work. below is what I tried:
1. Using visual C++ build tools 2017 doesn't work
2. Using windows-build-tools doesn't work
 hope this can help you.

**Comment by rogerwang** [comment]
@Christywl I just checked. building against 0.26.6 works for me.

@wythe0102 your issue is that edge source code is not ported for the new v8 engine (6.3) shipped with Chrome 63 and NW.js 0.27. So it's not a NW issue.
