### ISSUE TITLE
how to catch click event into <webview>  by mainapp

### ISSUE THREAD

**Issue by dstiq** [nwjs/nw.js#6344]
NWJS Version : 0.25.2
Operating System :
Windows10x64
### Expected behavior

<!- What do you think should happen? ->
```
html
<webview id="webview_1"></webview>
```
```
js
let a = document.getElementById('webview_1')
a.addEventListener('click', (e) => {console.log(e)});
```
```
devTools
"some_event_log"
```
### Actual behavior

Cant catch event in main app
Did i something wrong?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
