### ISSUE TITLE
NW crash when debugging with developer tools for Linux

### ISSUE THREAD

**Issue by wanghongjuan** [nwjs/nw.js#6347]
NWJS Version : nwjs-sdk-v0.27.2-linux-x64
Operating System : Ubuntu 16.04

### Expected behavior

No crash

### Actual behavior

This issue is random, run this sample 10 times, 6 of them are crashed.

### How to reproduce
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>.
    <script type="text/javascript">
      var request = require('request');
      setInterval(function() {
        request({
          url: 'http://www.bing.com',
          method: 'get'
        }, function(err, response, body) {
          debugger;
          if (err) return console.error(err.stack); 
          console.log(response, body);
        });
      }, 3 * 1000);
      nw.Window.get().showDevTools()
    </script>
  </body>
</html>
```
When running the breakpoint on line 16 with developer tools in the page above, NW will crash after click `Resume script execution` button, please try to click it 10 times.

I tried to run this sample on Mac OS and Windows 8.1, there is no crash.

**Comment by wanghongjuan** [comment]
Similar issue with #5882.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.27.2.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
Please verify with this build: https://dl.nwjs.io/live-build/12-25-2017/nw27-732f2d7-c520573-7a24307-547fb57/v0.27.4/

**Comment by wanghongjuan** [comment]
Thanks for your quickly fixed, it is works well now.
