### ISSUE TITLE
Running nwjs with Puppeteer for UI testing

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6350]
NWJS Version : 0.27.3
Operating System : Win10 64 bit
Google Puppeteer: https://github.com/GoogleChrome/puppeteer

I'm trying to run nwjs with Google Puppeteer to run some UI testing much easier and it seems almost to work but the main window just don't show up

I have this node test js:

```javascript
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch({
					headless: false,
					ignoreDefaultArgs: true,
					executablePath: 'windows_v0.27.3/nw.exe',
					args: ['app']
				});
	console.log('done launching ...')
})();
```

So nwjs is launched all well - just nothing displays and no errors at all.
Tried also to specify a userDataPath - and it gets generated and used but still no display.
Also enabled chrome logging and the chrome_debug.log gets created all fine but it is empty.

Any ideas @rogerwang it will be really cool if we can get Puppeteer working - it makes automated testing so much easier!

**Comment by rogerwang** [comment]
I ran it through `strace -o log -s 200 -f` and found that puppeteer is adding `--disable-extensions` which prevents NW apps from running and NW apps need that. 

Looks like `ignoreDefaultArgs` is not effective. Please report this to puppeteer. If there are further issues, please follow up here.

**Comment by Lyfeway** [comment]
hey @gpetrov, puppeteer is good for NW.js UI Testing?
I ran into a situation that NW can be opened, but `puppeteer.launch` never fulfilled. The result is timeout.

**Comment by surunzi** [comment]
I fork puppeteer and modify it to work on nw.js. It's released as an npm package [nw-puppeteer](https://www.npmjs.com/package/nw-puppeteer) and you might want to try it out.

**Comment by chouzzy** [comment]
> I forked puppeteer and modify it to work on nw.js. It's released as an npm package [nw-puppeteer](https://www.npmjs.com/package/nw-puppeteer) and you might want to try it out.

That worked extremely well here, thanks so much

**Comment by ayushmanchhabra** [comment]
I am able to launch NW.js via Puppeteer. I pointed it to where my app was via the `--nwapp` command line argument. Will explore more with time.

```javascript
import { findpath } from "nw";
import puppeteer from "puppeteer";

await launch();

async function launch() {
    const browser = await puppeteer.launch({
        headless: false,
        ignoreDefaultArgs: true,
        executablePath: findpath(),
        args: ['--nwapp=./'],
    });
    console.log('Done launching...');
}
```

**Comment by ayushmanchhabra** [comment]
Made some more progress. Now able to test NW.js using Puppeteer:
https://github.com/nwutils/nw-testing-examples/blob/main/js/puppeteer/puppeteer.test.js
