### ISSUE TITLE
Tray icon 设置无效

### ISSUE THREAD

**Issue by jsgr** [nwjs/nw.js#6351]
请问一下
var tray = new gui.Tray({
        title: "标题",
        icon: "../static/images/tray.png"
      });
这样子设置 为什么 图标无法显示，标题可以，也可以点击，就是图标无法显示。图片是 128x128 png格式的，路径是对的，我引用线上的图片地址也是不行。请问有谁知道怎么解决么？

**Comment by rogerwang** [comment]
Please use English in this project so all users can read

**Comment by Williamlook** [comment]
请问你怎么解决的？我设置的也是无效

**Comment by jsgr** [comment]
@Williamlook 
icon: "/static/images/tray.png"
这样子就可以了

**Comment by Williamlook** [comment]
我怎么不行，能帮我看看嘛

**Comment by jsgr** [comment]
@Williamlook 
方便贴一下 这一块的代码么，就是设置 tray图标的代码即可

**Comment by Williamlook** [comment]
![Uploading image.png…]()

**Comment by Williamlook** [comment]
给你发了邮件哟，看一下

**Comment by jsgr** [comment]
@Williamlook 

邮件没看到，垃圾箱也找不到
我的邮箱 1256961638@qq.com

**Comment by Williamlook** [comment]
没事，解决了，需要128*128，png我直接把ico改成.png了........感谢

**Comment by jsgr** [comment]
@Williamlook 
可以了就好，哈哈
