### ISSUE TITLE
Autocomplete= "off" is an invalid attribute in the debug version

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#6352]
Autocomplete= "off" is an invalid attribute in the debug version
I want to use this property to set up NW not to remember the password, but I still remember the password after I was successful.
`<input class="weui-input" type="password" placeholder="password" style="width:90%" autocomplete="off">`

![_15142578554943](https://user-images.githubusercontent.com/6937002/34345929-cdaca638-ea2d-11e7-839d-c030d12425bf.png)
======== TEMPLATE BUG FORM ========

NWJS Version : 0.27.2
Operating System : win10 64

**Comment by phpjishu** [comment]
@Christywl 
This problem has been all the time, from a very early version, the non debug version will not have this problem!

**Comment by Christywl** [comment]
Here is my sample:
index.html:
```
<!DOCTYPE html>
<html>
<body>

<h2>Login Form</h2>

<form action="https://www.w3schools.com/action_page.php">
  <div class="container">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname">

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" autocomplete="off">
        
    <button type="submit">Login</button>
  </div>
</form>

</body>
</html>
```
Launch the app with nwjs-sdk-v0.27.3, input Username and Password, click Login button.
Launch the app again, the password is remembered and displayed.
![image](https://user-images.githubusercontent.com/20039821/34367574-4c035d88-eae7-11e7-985e-52abba50e42d.png)

Clean up the data and input username again, focus on password, it gives you a list of username you can click to get to the password
![image](https://user-images.githubusercontent.com/20039821/34367580-5fc61946-eae7-11e7-9e6e-919e42766457.png)

**Comment by Christywl** [comment]
@rogerwang , is this similar or duplicate to #5944?

**Comment by rogerwang** [comment]
The behavior in the SDK version should be expected, see https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

**Comment by rogerwang** [comment]
close as it's expected.
