### ISSUE TITLE
can not get App object in 0.27.3

### ISSUE THREAD

**Issue by wythe0102** [nwjs/nw.js#6354]
NWJS Version : 0.27.3
Operating System : win 7

### Expected behavior
1. can not get App object using `nw.App`  according to [](http://docs.nwjs.io/en/latest/References/App/)
2. have to get the App Object
### Actual behavior

when using `nw.App` get undefined

### How to reproduce

in console , enter nw.App

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 7 with nwjs-sdk-v0.27.3, can get the returned value when entering `nw.App` in the devtools console.
