### ISSUE TITLE
nw fails to install via npm

### ISSUE THREAD

**Issue by physiii** [nwjs/nw.js#6358]
Operating System:
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Raspbian
> Description:	Raspbian GNU/Linux 9.1 (stretch)
> Release:	9.1
> Codename:	stretch

node and npm versions:
>  $ npm -v
> 5.6.0
> $ node -v
> v7.10.1

Steps to reproduce:
>  $ sudo npm install -g nw

Expected to install peacefully, actual behavior:

> $ sudo npm install -g nw
> /usr/bin/nw -> /usr/lib/node_modules/nw/bin/nw
> 
> nw@0.27.3 postinstall /usr/lib/node_modules/nw
> node scripts/install.js
> 
> Response code 404 (Not Found)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nw@0.27.3 postinstall: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the nw@0.27.3 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2017-12-28T16_51_24_473Z-debug.log

Any ideas?

**Comment by rogerwang** [comment]
Please report to the correct repo: https://github.com/nwjs/npm-installer
