### ISSUE TITLE
macOS version bug

### ISSUE THREAD

**Issue by Varunram** [nwjs/nw.js#6361]
Operating System: macOS
```
nw --version
err = 3 ../../third_party/mach_override/mach_override.c:244
err = 3 ../../third_party/mach_override/mach_override.c:258
err = 3 ../../third_party/mach_override/mach_override.c:263
nwjs 56.0.2924.76
```
`npm view nw versions` shows that I have 0.28.0-beta1sdk and 0.27.3 and so on, but Chromium doesn't seem to update.  Is there something wrong on my side? Any help is greatly appreciated. Thanks!

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs v0.27.3.

- Download the v0.27.3 build from https://nwjs.io:
```
$ ./nwjs-sdk-v0.27.3-osx-x64/nwjs.app/Contents/MacOS/nwjs --version
nwjs 63.0.3239.108 
```

- npm install -g nw:
```
$ nw --version
nwjs 63.0.3239.108 
```

**Comment by Varunram** [comment]
Thanks for the response, I dunno what happened, but uninstalling all versions of nw and then reinstalling the sdk and stuff worked. Must be some weird internal conflict I guess. Thanks again!

**Comment by LockonS** [comment]
It seems every time you run a project, nw.js generate a set of files in `~/Library/Application Support/project_name`. And deleting these generated files worked in my case. Cause I created this project with a higher version of nw.js and tried to run project with a previous version of nw.js.
