### ISSUE TITLE
error while loading shared libraries: libnw.so

### ISSUE THREAD

**Issue by mouyong** [nwjs/nw.js#6363]
NWJS Version : 0.24.4
Operating System : Ubuntu 17.10 \n \l

### Expected behavior

It should normal work.

### Actual behavior

Has am Error: ./nw: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory

### How to reproduce

https://github.com/cytle/wechat_web_devtools/

The README is my step.

I tried the question of Baidu and Google. But I didn't find the right solution.

**Comment by Christywl** [comment]
I can't reproduce this issue on Ubuntu 16.04 and 17.10.

![screenshot from 2018-01-03 07-39-43](https://user-images.githubusercontent.com/20039821/34512298-5a940b64-f059-11e7-96e9-df7b808b3b7a.png)

**Comment by mouyong** [comment]
This problem has been solved.

> https://github.com/cytle/wechat_web_devtools/issues/54

Thx for you answer.

**Comment by mouyong** [comment]
closed #6363

**Comment by Christywl** [comment]
Close this

**Comment by mouyong** [comment]
Okay.
