### ISSUE TITLE
Add proper documentation for js-flags or a link to where such documentation can be found

### ISSUE THREAD

**Issue by JonasT** [nwjs/nw.js#6364]
Please add proper documentation for js-flags or a link to it. I'd like to enable ES6 classes since node supports them already for a while, but I just can't figure out how. I tried "js-flags" `--harmony --harmony_classes --experimental-modules`...

As per http://2ality.com/2017/09/native-esm-node.html I would expect this line to work: `import * as ui from 'ui';` I use this out of an `app/main.mjs` file. However, I'm getting this error right at launch:

```
import * as ui from 'ui.mjs';
       ^

SyntaxError: Unexpected token *
```
It's pretty frustrating that it's not really obvious if this should work in nw.js at all, which flags should enable it etc, since all sites just mention this for node but not how to do it for nw.js.

Therefore, it would be nice if https://github.com/nwjs/nw.js/wiki/manifest-format#js-flags could be fixed to actually include information on which flags are supported, or where to find that information, and also how to find out which exact nw.js verison is supposed to support which flags. Also, a proper error when submitting garbage flags would be nice, since I tested `--aerboiajer` and it doesn't even tell me that this is an unknown flag (as it does for "chromium-args") with a warning or anything. How am I supposed to find out whether what I am submitting was recognized at all?

NWJS Version : nwjs 63.0.3239.108
Operating System : GNU/Linux Fedora 27 x64

**Comment by rogerwang** [comment]
The referred tutorial is about using modules in Node.js. In Chrome `<script type="module">` was [shipped in Chrome 61](https://www.chromestatus.com/features/5365692190687232) and `JavaScript module import()` was just [shipped in Chrome 63](https://www.chromestatus.com/features/5684934484164608). Both should work fine in latest NW 0.27, which is based on Chrome 63.

Chrome stable often has newer V8 version than Node.js latest stable so it has more features. In NW (thus the Node.js code in NW), we are always using Chrome's V8 version. So you should be able to use all those features by default without any flags.

I believe the error you hit is that the `mjs` extension is not accepted by Chrome module loader, you can try `.js` instead. I'll see to make Node.js module loader and Chrome module loader work together. See the off-topic discussion in #6303 but please don't continue the off-topic discussion there.

I'll add a link to NW.js documentation for `js-flags`. They are actually v8 engine flags: https://chromium.googlesource.com/v8/v8/+/master/src/flag-definitions.h

**Comment by JonasT** [comment]
Ah, I forgot to use `<script type="module">`. As for `.mjs`, I think this needs to be used for node for full support, so it'd be good if that worked in nw.js in the future.

Thanks for adding the link, that would be very helpful :smile:
