### ISSUE TITLE
0.17.6 has virus alarm on virustotal.com

### ISSUE THREAD

**Issue by iJetLi** [nwjs/nw.js#6367]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
0.17.6
Operating System :
windows

### Expected behavior
no anti-virus alarm

### Actual behavior
https://www.virustotal.com/#/file/33f46bb928015605090735c9536f24aac1770b52565d9d5ee29a1d101e401a6b/detection
virus alarm

### How to reproduce
upload to virustotal.com to check

**Comment by rogerwang** [comment]
Thanks but the alarm is false positive result of the antivirus software vendor and the issue should be reported to them.
