### ISSUE TITLE
Maximize, Restore events aren't firing at the right times in debian

### ISSUE THREAD

**Issue by danschumann** [nwjs/nw.js#6371]
NWJS Version : 0.27.3
Operating System : debian stretch

Expected behavior
On windows, this works: 
```
w = nw.Window.get()
w.on('maximize', function() { ... });
w.on('restore', function() { ... });
```

Actual behavior
On debian, the `restore` event does not fire on restore.  It does fire after I click on another window.
Example:
* click maximize `window maximizes, maximize fires`
* click restore `window restores, nothing fires`
* click on the dev tools window `window stays the same, now restore fires`

**Comment by danschumann** [comment]
My work-around is to
```
store.dispatch({type: WINDOW_RESTORE});
nw.Window.get().restore()
```

Rather than

```
w.on('restore', => store..dispatch({type: WINDOW_RESTORE})
```

**Comment by Christywl** [comment]
I try a simple test on Ubuntu with nwjs-sdk-v0.27.3, the 'restore' event could be fired normally.
index.html:
```
<script>
w = nw.Window.get()
w.on('maximize', function() { document.write('Maximize' + '<br/>');});
w.on('restore', function() { document.write('Restroe' + '<br/>');});

</script>
```
![6371](https://user-images.githubusercontent.com/20039821/34656751-3e9b0760-f459-11e7-9228-1f2177a1e0af.png)

**Comment by danschumann** [comment]
Have you tried firing restore from a custom button, with devtool opened?

**Comment by Christywl** [comment]
Could you please share your sample (with a custom button) for me? I'll check on my device.
