### ISSUE TITLE
webview devtools can no longer be embedded

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6374]
In the latest 0.27.3 and 0.27.4 the webview Devtools no longer be embed in other webview
when calling webview.showDevtools(true, other_webview) nothing happens

I tried it using a simple test files from:
https://github.com/nwjs/nw.js/tree/b7a64fc87964b5c0c622a1fa5022a0a2352842d5/test/manual/issue4709-osx-cdthotkey

It works still fine on 0.24.4

NWJS Version : 0.27.3 and 0.27.4
Operating System : Windows 10 64 bit

### Expected behavior

Devtools should be shown in the speicified webview container

### Actual behavior

Nothing displays

### How to reproduce

Load the simple files from:
https://github.com/nwjs/nw.js/tree/b7a64fc87964b5c0c622a1fa5022a0a2352842d5/test/manual/issue4709-osx-cdthotkey
and click on the show button

@rogerwang could you please check this - is pretty essential

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.27.4.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next build.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/01-09-2018/nw27-a8a102c-748f0c6-a3ef615-547fb57/v0.27.5/

**Comment by gpetrov** [comment]
fix confirmed - all working now

**Comment by rogerwang** [comment]
test case added in https://github.com/nwjs/nw.js/commit/2779509b3bc09adf7b9facf5dd0ae7a3e69bdd54
