### ISSUE TITLE
nwjs crash when choosing inspect when devtools are embedded

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6375]
When webview devtools are embedded in other webview and the user choose "inspect" from the context menu nwjs crashe without any error

Note embedding is only visible in 0.24.4 and n longer on 0.27.3 and 0.27.4 see https://github.com/nwjs/nw.js/issues/6374

NWJS Version : 0.24.4, 0.27.3, 0.27.4
Operating System : Windows 10 64 bits

### Expected behavior

When you click the "Inspect" from the context menu the node should be just inspected in the embedded devtools

### Actual behavior

nwjs crashes

### How to reproduce

Load the simple files from:
https://github.com/nwjs/nw.js/tree/b7a64fc87964b5c0c622a1fa5022a0a2352842d5/test/manual/issue4709-osx-cdthotkey
and click on the show button - and from the first webview, right click for the context menu and choose "Inspect"

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.27.4.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/01-09-2018/nw27-a8a102c-748f0c6-a3ef615-547fb57/v0.27.5/

**Comment by gpetrov** [comment]
fix confirmed - all working now
