### ISSUE TITLE
how to display the download toolbar?

### ISSUE THREAD

**Issue by KaierChou** [nwjs/nw.js#6378]
in my project, user can download some file at the same time , but i don't know whether the file is download completed.
so, how to display the download toolbar in nwjs? 
![_20180110164910](https://user-images.githubusercontent.com/24623866/34764784-8e759c50-f62a-11e7-9533-ed748b8731a9.png)
![_20180110164941](https://user-images.githubusercontent.com/24623866/34764791-942de4a4-f62a-11e7-9072-fb3068073c59.png)
Thank you and Please don't let me ask the question through google due to i can't view google website in China.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

The issue system works as issue reporting and developers' backlog. It's not for questions and answers as discussion forum. Your network issue does not justify your misuse of our issue system.
