### ISSUE TITLE
Application crashing when upgrading from 0.27.1 to 0.27.4

### ISSUE THREAD

**Issue by cotejp** [nwjs/nw.js#6379]
I tried running my application with 0.27.4 and it crashes every time I launch it. If I revert back to using 0.27.1, it works without a problem.

Here is the message in the console:

```
[42055:45059:0110/110944.393069:ERROR:service_manager.cc(157)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
>> FATAL ERROR: v8::Object::GetInternalField() Internal field out of bounds
 1: node::Abort() [/Applications/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 2: node::FatalTryCatch::~FatalTryCatch() [/Applications/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 3: v8::Object::SlowGetInternalField(int) [/Applications/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/Versions/A/nwjs Framework]
 4: node::PromiseHook(v8::PromiseHookType, v8::Local<v8::Promise>, v8::Local<v8::Value>, void*) [/Applications/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 5: node::Environment::EnvPromiseHook(v8::PromiseHookType, v8::Local<v8::Promise>, v8::Local<v8::Value>) [/Applications/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 6: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/Versions/A/nwjs Framework]
 7: 0x14f38978469d
Received signal 6
 [0x000106d14ddc]
 [0x000106d14cd1]
 [0x7fff741a9f5a]
 [0x00010dba72d4]
 [0x7fff73fd4312]
 [0x000110d2d08f]
 [0x000110d2d2f8]
 [0x00010605a1a7]
 [0x000110d1456c]
 [0x000110d226ed]
 [0x000106645187]
 [0x14f38978469d]
[end of stack trace]
```

This is on macOS High Sierra.

**Comment by Christywl** [comment]
Could you please provide your sample to reproduce this issue?

**Comment by cotejp** [comment]
As I said, its my whole application that's doing that when ported to 0.27.4. I will try to isolate the problem and provide you with a sample. Thanks.

**Comment by cotejp** [comment]
Okay, I managed to isolate the issue. I'm attaching a [sample project](https://github.com/nwjs/nw.js/files/1623360/NWjsSample.zip) that you can use to replicate it. Here is some background info:

- The sample project works in NW.js v0.27.1 but crashes in NW.js 0.27.4.

- The problem is triggered by the presence of a `Promise`. If you replace the `Promise` with a callback (which I did in `test2.js` as a demonstration), it works fine.

- It's a bit tricky to test because you need the **johnny-five** module and an Arduino to trigger the problem. 

- The problem may stem from something funky inside **johnny-five** but, as I said, the exact same code is working fine in 0.27.1.

- The **johnny-five** module has a native dependency (**serialport**) so it
 needs to be [properly rebuilt](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/) upon install.

Here is the full console output I get from running the sample project:

```
2018-01-11 10:13:40.639 nwjs[52424:5892067] *** WARNING: Textured window <AppNSWindow: 0x7fa0344a07f0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
2018-01-11 10:13:41.019 nwjs[52424:5892067] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
2018-01-11 10:13:41.528 nwjs Helper[52432:5892293] Couldn't set selectedTextBackgroundColor from default ()
[52424:45315:0111/101344.960567:ERROR:service_manager.cc(157)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
>> FATAL ERROR: v8::Object::GetInternalField() Internal field out of bounds
 1: node::Abort() [/Users/jpcote/Desktop/NwjsTest0.27.4/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 2: node::FatalTryCatch::~FatalTryCatch() [/Users/jpcote/Desktop/NwjsTest0.27.4/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 3: v8::Object::SlowGetInternalField(int) [/Users/jpcote/Desktop/NwjsTest0.27.4/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/Versions/A/nwjs Framework]
 4: node::PromiseHook(v8::PromiseHookType, v8::Local<v8::Promise>, v8::Local<v8::Value>, void*) [/Users/jpcote/Desktop/NwjsTest0.27.4/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 5: node::Environment::EnvPromiseHook(v8::PromiseHookType, v8::Local<v8::Promise>, v8::Local<v8::Value>) [/Users/jpcote/Desktop/NwjsTest0.27.4/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/libnode.dylib]
 6: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Users/jpcote/Desktop/NwjsTest0.27.4/nwjs.app/Contents/Versions/63.0.3239.132/nwjs Framework.framework/Versions/A/nwjs Framework]
 7: 0x179c4940469d
 8: 0x179c494a3ec2
 9: 0x179c494553ff
Received signal 6
 [0x000106d53ddc]
 [0x000106d53cd1]
 [0x7fff741a9f5a]
 [0x7f87c10168e0]
 [0x7fff73fd4312]
 [0x000111ccb08f]
 [0x000111ccb2f8]
 [0x0001060991a7]
 [0x000111cb256c]
 [0x000111cc06ed]
 [0x000106684187]
 [0x179c4940469d]
 [0x179c494a3ec2]
 [0x179c494553ff]
[end of stack trace]
```

I remain available if you need further info. Thanks for your help with this.

**Comment by rogerwang** [comment]
Is there any way to reproduce it without the hardware board?

**Comment by rogerwang** [comment]
With your stack trace, I just tried to fix it without reproduce it. Please try this build: https://dl.nwjs.io/live-build/01-12-2018/nw27-2b7d2db-2f0eedb-a3ef615-6c8870e/v0.27.5/

**Comment by cotejp** [comment]
You are making me so happy this morning!!! It works! Thank you, thank you, thank you . You are a genius.

**Comment by npaul007** [comment]
@rogerwang could you elaborate on what you did exactly.

I am having a similar issue with an nwjs app that worked perfectly fine on Windows.
But I can't get it to bootup on OSX. 
Its nwjs version was updated to 0.27.4 on the windows version.

I downloaded the 0.27.4 SDK from the nwjs site for OSX.
Put the files in my directory and ran nwjs.app.

The loading window for my app would bootup, then suddenly crash.

Any Ideas?

**Comment by cotejp** [comment]
Now that my sample project is working, I would like to test my whole application with 0.27.5. However, I am unable to rebuild native modules with nw-gyp because the headers are not yet available. It gives me a 404 while trying to fetch: http://node-webkit.s3.amazonaws.com/v0.27.5/nw-headers-v0.27.5.tar.gz

Is there a way around this or should I just wait for the final release?

Thanks again!

**Comment by cotejp** [comment]
@npaul007 By any chance, are you seeing that error message in the console when the application crashes? This is happening to me occasionnaly with version 0.27.1 on macOS.

```
[60160:85251:0112/110931.562478:ERROR:service_manager.cc(157)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser
>> Received signal 11 SEGV_MAPERR 07fa09df21b8
 [0x0001082f638c]
 [0x0001082f6281]
 [0x7fff741a9f5a]
 [0x000000000000]
 [0x000115338240]
 [0x7fff4868eb79]
 [0x7fff73ef6591]
 [0x7fff73eeed50]
 [0x7fff73f0320c]
 [0x7fff73ef60fd]
 [0x7fff73f03f02]
 [0x7fff73f07d16]
 [0x7fff741b3033]
 [0x7fff741b2c4d]
```

**Comment by npaul007** [comment]
@cotejp where can I access console messages?
Do I have to run my app thru the console in order to view them?

**Comment by cotejp** [comment]
Yes. This will provide the team with valuable debugging information.

**Comment by rogerwang** [comment]
close as the fix is working.

@npaul007 your issue may not be the same one as this. Please file a new issue with detail information. Thanks.

**Comment by rogerwang** [comment]
@cotejp you can just build against 0.27.4 or wait for 0.27.5 which will be released soon.

**Comment by cotejp** [comment]
@rogerwang Ok, thanks. I compiled the modules against 0.27.4 and it works with 0.27.5. 

By the way, I'm still seeing occasional crashes. I'll open another issue when I have more info. Thanks again for your help.

**Comment by rogerwang** [comment]
You can send the crash dump.

**Comment by cotejp** [comment]
> You can send the crash dump.

Unfortunately, I cannot find any crash dumps in the [location](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#find-minidump-file) specified in the documentation. Must a special flag be enabled?
