### ISSUE TITLE
Programatically check if the app version is a distributable package

### ISSUE THREAD

**Issue by mhcgolds** [nwjs/nw.js#6380]
Is there a way to check if the app is running as a version programatically? I build a my app with [nwjs-builder-phoenix](https://github.com/evshiron/nwjs-builder-phoenix). 

Example: In ASP.Net MVC you have `DEBUG` and others constants which you can use within your code to perform some actions only when debugging the app in Visual Studio, but not in the production version after a publish process.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general.
