### ISSUE TITLE
Allow more communication with embedded devtools

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6381]
Currently when for the webview embedded devtools, you have only a simple webview.showDevTools(show, [container]) API call.

Please add more extended API for controlling and communicating to the devtools.

@rogerwang We need at least methods to inspectElement(x,y), inspectElement(domNode)  and/or inspectElementByQuerySelector(selector) but access to the blackboxed: chrome.devtools api as well settings of the devtools will be really nice.

Electron have already much more extensive about about this:  https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsinspectelementx-y

Thank you!

**Comment by rogerwang** [comment]
Will look into it.

**Comment by gpetrov** [comment]
@rogerwang InspectElement should be really easy as you already have it here:
https://github.com/nwjs/nw.js/blob/a8a102ca0d374575afb4e6a8035f848972431780/src/browser/nw_chrome_browser_hooks.cc#L161

you just need to make a separate public api call for it, accepting x and y as parameters
If we also have another with css selector as parameter will be even better.

**Comment by rogerwang** [comment]
Regarding `chrome.devtools` API, NW supports it through devtools extension: https://developer.chrome.com/extensions/devtools
I think that should work for you?

**Comment by gpetrov** [comment]
Yes I'm aware of that but we have to build special devtools extension just to access the devtools api then from the regular nwjs context. I'm also aware about the --load-extension switch to load it - but will this load the extension in all devtools? both the nwjs ones and the webview one?

Ideally we would like to control the settings and the displayed panels of the webview devtools, so we can display a bit stripped down version.

**Comment by rogerwang** [comment]
Yes devtools extension is supported, in webview as well. Please see the example and latest build in #6004 .

**Comment by rogerwang** [comment]
The inspectElementAt() method was added in nw28 branch and will be available in the next nightly build.
