### ISSUE TITLE
nwUserAgent does not work

### ISSUE THREAD

**Issue by rdcvnh** [nwjs/nw.js#6384]
nwUserAgent does not work. It does work, however, on electron.js.
_________________________
NWJS Version : 0.27.4
Operating System : Windows 10 64bit

### Expected behavior

Mobile site should be displayed in iframe with user-agent set for mobile

### Actual behavior

Normal desktop page is displayed

### How to reproduce
1. Create a NW app
2. In the index.html, add an iframe and point it to **YouTube** with the **nwUserAgent** attribute set to:
"Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36"
3. Launch the app
4. Desktop version of the website is displayed regardless

**Comment by rogerwang** [comment]
Does adding `--disable-browser-side-navigation` as command line switch help?

**Comment by Christywl** [comment]
Seem `nwUserAgent` work well on my Windows/Linux with nwjs-sdk-v0.27.4.
Right click in the iframe and choose 'inspect', input navigator.userAgent in the console:
1. 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf8">
    <title>test</title>
  </head>
  <body>
    <iframe id="iframe"  nwuseragent="Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36" src="https://www.youtube.com"></iframe>
  </body>
```
2. 
![image](https://user-images.githubusercontent.com/20039821/34923403-8d5aebb8-f9d6-11e7-8b8f-9eb1dff6e2fb.png)
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf8">
    <title>test</title>
  </head>
  <body>
    <iframe id="iframe"  nwuseragent="test-user-agent" src="http://nwjs.io"></iframe>
  </body>
```
![image](https://user-images.githubusercontent.com/20039821/34923496-7197ccc4-f9d7-11e7-9e83-fc5e024c84af.png)

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by mkazlauskas** [comment]
@rogerwang I'm having the same issue. --disable-browser-side-navigation does indeed fix it.

**Comment by mkazlauskas** [comment]
@rogerwang @Christywl please let me know other info I can provide

**Comment by rogerwang** [comment]
Please provide a sample so we can reproduce it.

On Jan 26, 2018 5:31 PM, "Martynas" <notifications@github.com> wrote:

@rogerwang <https://github.com/rogerwang> @Christywl
<https://github.com/christywl> please let me know other info I can provide

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nwjs/nw.js/issues/6384#issuecomment-360729585>, or mute
the thread

**Comment by mkazlauskas** [comment]
@rogerwang The sample that @Christywl provided does reproduce it. Please add "nwfaketop" to iframe (gets rid of x-frame-options error). I've tested it on 0.27.5 with the following results:

1) `nw .` - loads desktop version of youtube
2) `nw . --disable-browser-side-navigation` - loads mobile version of youtube

Interestingly, the navigator.userAgent seems to be set correctly. I guess it just doesn't apply it to the requests headers.

**Comment by mkazlauskas** [comment]
Did you manage to reproduce it?

**Comment by diginfo** [comment]
I am still facing this issue.

The attribute nwuseragent is updated with the value that I set using javascript, however requests received by the server do not reflect this new useragent string !
