### ISSUE TITLE
Disable "Show all saved passwords..." dropdown.

### ISSUE THREAD

**Issue by wyp-blizzmi** [nwjs/nw.js#6386]
NWJS Version :  0.26.5 (tried the newest version, still happens)
nwjs-builder-phoenix: 1.14.6

When visit a remote website (like https://github.com/), click an empty password( <input type="password"/>) field, then a dropdown exists, on it writing "Show all saved paswords..." .

![2018-01-15 14-16-54](https://user-images.githubusercontent.com/25922147/34929565-8b732030-f9ff-11e7-82f8-9bea869157ef.png)

The Chinese sentence is "Show all saved paswords..." in en-US.pak

When click "Show all saved paswords...", **the whole app would exit**.

Use "npm install nw -g; nw ." won't cause the problem, only happens in app built using sdk or normal version of nwjs.

Eager for some solution, thanks in advance.

**Comment by Christywl** [comment]
On Windows, I can reproduce this issue with nwjs-sdk-v0.26.5, but can **not** reproduce this with nwjs-sdk-v0.27.*.

**Comment by wyp-blizzmi** [comment]
@Christywl Sorry for the previous wrong description. I tried again version 0.27.4, and the problem is solved.

When upgraded to 0.27.*, my project always crash. But I think it's something in my project caused that. Thank you very much for the helpful response.
