### ISSUE TITLE
The v0.27.5 lost nw.pak

### ISSUE THREAD

**Issue by langsz** [nwjs/nw.js#6389]
When I use grunt-node-webkit-builder to download the v0.27.5,it show me that
"Fatal error: ENOENT: no such file or directory, lstat 'G:\myproject\cache\0.27.5\win32\ffmpegs
umo.dll'"
then I copy the dll from another version. but it still throw a error which 
"Fatal error: ENOENT: no such file or directory, lstat 'G:\myproject\cache\0.27.5\win32\nw.pak'"

**Comment by rogerwang** [comment]
It should be reported to grunt-node-webkit-builder.
