### ISSUE TITLE
window object return in Window.open callback is undefined

### ISSUE THREAD

**Issue by FahadQurashi49** [nwjs/nw.js#6392]
Hello,

I'm upgrading my app from 0.12.3 to the latest nwjs version 0.27.5 I changed my code of window opening from:

```
var eWin:any = nw.Window.open(url, {
                "inject-js-start": scriptPath,
                "inject-js-end": scriptPath2,
                "show": false
         });
```
to:
```

nw.Window.open(url, {
                "inject_js_start": scriptPath,
                "inject_js_end": srciptPath2,
                "show": false
            }, (eWin: any) => {
                   if(!eWin) return;
            })
```
url is a remote site url and scriptPath, scriptPath2 are paths to local js files.
eWin retrun in callback is undefined, and this warning is shown on the devTools console:

> Creating sandboxed window, it doesn't have access to the chrome.app API. The chrome.app.window.create callback will be called, but there will be no object provided for the sandboxed window.

My OS is Mac OS High Sierra, I'm having same issue on windows 10.

**Comment by Christywl** [comment]
I run your codes, an error occurs:
`Uncaught SyntaxError: Unexpected token :`

```
<script>
nw.Window.open('https://nwjs.io', {
                "inject_js_start": '1.js',
                "inject_js_end": '2.js',
                "show": false
            }, (eWin: any) => {     //Uncaught SyntaxError: Unexpected token :
			 if(!eWin) return;
            });
</script>
```
Try my test, it works fine on Windows and Mac High Sierra with nwjs-sdk-v0.27.5.
```
<script>
nw.Window.open('https://nwjs.io', {
                "inject_js_start": '1.js',
                "inject_js_end": '2.js',
                "show": false
            }, (win) => {   
                console.log(win);  
            });
</script>

**Comment by FahadQurashi49** [comment]
I find out there was a problem with URLs I was using with nw.Window.open like try to run this code:
```
        // var url = 'http://arxiv.org'; // this url also don't work
         var url = 'https://scholar.google.com/';
        nw.Window.open(url, {
            "show": false
        }, function(eWin) {
            console.log("Window object returned: " + eWin);
            console.log(eWin);
        });
```

http://arxiv.org url redirects to its https version url https://arxiv.org in the browser also https://scholar.google.com/ redirects to country specific url in browser. opening these url gives warning on console:
 

> Creating sandboxed window, it doesn't have access to the chrome.app API. The chrome.app.window.create callback will be called, but there will be no object provided for the sandboxed window.

and returned undefined window object in the callback.

I tested this code on nwjs version 0.25.4 it was working fine. but on versions 0.26.6 and 0.27.5 above behavior is observed.

I think I am missing some configuration in manifest may be, my package.json is:

```
{
  "name": "helloworld",
  "main": "main.js",
  "license": "UNLICENSED",
  "nwjs-version": "0.27.5"
}

``` 

I also created a demo project: https://github.com/FahadQurashi49/nwjs-demo which represent my problem on  nwjs-sdk-v0.27.5 and nwjs-sdk-v0.26.6.

also this error in my code: 

> Uncaught SyntaxError: Unexpected token : 

was just a copy/paste mistake because my original code was in typescript

**Comment by FahadQurashi49** [comment]
I found that there was problem with the URLs I was using, like, try to run your code with http://arxiv.org and https://scholar.google.com/ it gives the warning

> Creating sandboxed window, it doesn't have access to the chrome.app API. The chrome.app.window.create callback will be called, but there will be no object provided for the sandboxed window.

also window object returned is undefined. I think I am missing some configuration in manifest, my package.json is basic

```
{
  "name": "helloworld",
  "main": "main.js",
  "license": "UNLICENSED",
  "nwjs-version": "0.27.5"
}
```

**Comment by Christywl** [comment]
Try http://arxiv.org, got undefined:
![image](https://user-images.githubusercontent.com/20039821/36718061-6e77bb96-1bdb-11e8-9f4e-faccbb9f2ef7.png)


Try https://scholar.google.com/, it returned the window object:
![image](https://user-images.githubusercontent.com/20039821/36718018-3da31100-1bdb-11e8-9847-924b60bc3bab.png)

@rogerwang , could you please help check this issue?

**Comment by james-pellow** [comment]
We are having this issue as well, and it appears to be present through 0.29.3.  Is this something anyone is working on?

**Comment by rogerwang** [comment]
I just noticed that if you use the HTTPS page it works well: https://arxiv.org/

There is a redirection if HTTP is used. The redirection triggers the bug. Will look to fix it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by james-pellow** [comment]
Thanks rogerwang!  I was curious what the solution looked like so I went looking for a commit.  I'm not seeing one around the time this was closed.  Where would I find that?

**Comment by rogerwang** [comment]
@james-pellow it's in the chromium repo: https://github.com/nwjs/chromium.src

Unfortunately we keep all the chromium changes in one patch so the change for this issue is not traceable...
The fix is to use the same RenderFrameHost upon navigation during the Window.open API call. In longer term we plan to refactor the NW Window API so this would be solved in a better way.
