### ISSUE TITLE
nwjc failure compiling spread operator in object literals

### ISSUE THREAD

**Issue by vmartins** [nwjs/nw.js#6393]
When I try to compile code via nwjs with [spread operator (...) in object literals](https://github.com/tc39/proposal-object-rest-spread), I got a message:

```
Unhandle exception: Uncaught SyntaxError: Unexpected token ... @console.log({...obj, qux: 4})[2]
Failure compiling 'test.js' (see above)
```

Sample code:

```
const obj = {foo: 1, bar: 2, baz: 3};
console.log({...obj, qux: 4})
```

NWJS Version : 0.27.5 (nwjs-sdk-v0.27.5-win-x64 and nwjs-sdk-v0.27.5-linux-x64)
Operating System : Windows 10 and Linux Mint 18

**Comment by rogerwang** [comment]
Thanks for reporting. You can use `--harmony_shipping` to enable this. In upcoming 0.28.0 this becomes the default.
