### ISSUE TITLE
XMLHttpRequest from background page fails after an iframe is removed from window

### ISSUE THREAD

**Issue by sparkyb** [nwjs/nw.js#6410]
NWJS Version : 0.27.5
Operating System : Linux (Ubuntu 14.04)

### Expected behavior

XMLHttpRequest should work in the background page.

### Actual behavior

After an iframe is deleted in a window, the XMLHttpRequest in the background page fails with 

### How to reproduce

1. Use a background JavaScript file as the project's main file.
2. Use nw.Window.open() to open a window
3. Add an <iframe> to that window's DOM (or have it be part of the initial HTML)
4. Remove the iframe from the window's DOM.
5. From the background page, execute an XHR.
6. Instead of the XHR working, the following exception is raised:

DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://bcgokjambocaplmhfjlfkafhjiacmpci/xhrbug.json': Document is already detached.

A sample is attached.

[xhrbug.zip](https://github.com/nwjs/nw.js/files/1644754/xhrbug.zip)

**Comment by Christywl** [comment]
I can reproduce this issue with the attached sample on Windows and Linux with nwjs-sdk-v0.27.5.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
