### ISSUE TITLE
Error in /proc/self/exe: free() [0.28.0-beta1]

### ISSUE THREAD

**Issue by f3l1x** [nwjs/nw.js#6414]
## Env

OS: Linux Mint x64
Version: 0.28.0-beta1 x64 normal

## Error

```
*** Error in `/proc/self/exe': free(): invalid pointer: 0x0000217d94608008 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff4d65ef7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ff4d65f837a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff4d65fc53c]
/<app>/linux64/lib/libnw.so(+0x27d668d)[0x7ff4d9b5068d]
```

## JS

This code in JS trigged it.
```
nw.Window.get().reload();
```

**Comment by rogerwang** [comment]
Please  try the latest build: https://dl.nwjs.io/live-build/nw28/01-19-2018/65cc2f4-55883ed-2d8d099-3b59d35/v0.28.0/

**Comment by Christywl** [comment]
@f3l1x , is this still reproduced with the above build? The code works fine on my linux device.

**Comment by f3l1x** [comment]
It works on last 0.28 stable. Thank you.
