### ISSUE TITLE
How NW.JS Z calls the registry program？

### ISSUE THREAD

**Issue by joinwang111** [nwjs/nw.js#6422]
I call this form with location.href = "pageoffice://http://...", and there is a problem that is normal when the first load is loaded, and it can't be loaded at second times. I've added a random number to the HTTP link, but it doesn't work, is nw.js a way of calling its own external program?

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
