### ISSUE TITLE
app icon missing

### ISSUE THREAD

**Issue by sivapdigient** [nwjs/nw.js#6423]
hi i am using macbook pro.I got one nw auto updater plugin from google search.but in this process they did not configure icon related info.any one please check this attachment and sortout my problem

step1: start the npm server => inside of server folder use the command 'npm start'

step2: inside of client-strategy-script folder use the command 'npm run package'

step3: check the releases folder(server/releases/) =>....zip

step4: extract the zip icon then you can get app file => app icon is missing in this app file

web demo link : https://www.youtube.com/watch?v=Dzae9VHNK9g
[nw-autoupdater-master 1.29.44 PM.zip](https://github.com/nwjs/nw.js/files/1663954/nw-autoupdater-master.1.29.44.PM.zip)

**Comment by sivapdigient** [comment]
i am using [nwb nwbuild -v 0.21.3-sdk]version. i want to sortout the icon issue in same sdk version i dont want latest version becuase i am facing lot of nw syntax issue so please sortout my icon missing problem in this same sdk version

**Comment by Christywl** [comment]
I followed the four steps and got the zip file. But I'm not clear how to check icon in unzipped files?
```
$ ls
1.0.0					nw-autoupdater-demo-r1.0.0-osx-x64.zip
README.md
$ ls 1.0.0/
chromedriver		minidump_stackwalk	nwjc
credits.html		nw-autoupdater-demo.app	payload
```
Btw, maybe it's nw autoupdater issue, it's better to report there.

**Comment by sivapdigient** [comment]
Hi Christywl thanks for your reply.Actually i want to change the custom icon instead of deafult nw js icon
![how can i change custom icon](https://user-images.githubusercontent.com/15324391/35495204-cbe51470-04e5-11e8-9578-74d0a2b3921a.png)
I have attached my icon here how can i replace my custom icon instead of nw icon
![icon](https://user-images.githubusercontent.com/15324391/35495300-434ae8f0-04e6-11e8-82dc-16d51e05ef50.png)

**Comment by sivapdigient** [comment]
I have configured in package.json but i cant replace my custon icon still i facing the issue 
![how can i change custom icon](https://user-images.githubusercontent.com/15324391/35495734-62504c98-04e8-11e8-94b1-5004bf278a35.png)
.Please help me to sortout this issue
![source file](https://user-images.githubusercontent.com/15324391/35495715-41e1d652-04e8-11e8-8458-51b46daef2ba.png)

**Comment by sivapdigient** [comment]
i am facing another one issue
1.copy paste or drag and drop app in desktop(macos) and update something .All the nearest desktop icon is deleted.

**Comment by Christywl** [comment]
I saw the custom icon isn't in the package. But I'm not clear if this is an nw bug or nw-autoupdater bug. @rogerwang , could you please help check this?

**Comment by sivapdigient** [comment]
hi i have created my own downloader plugin with (1 javascript : 50 lines and 1 html : 40 lines file).Thanks for your reply and one more think i am not coming here this nw issue or nw auto updator issue i want the solution anyway i have throw this nw auto updator logic in dust bin.i have created my own and again i will say thanks for your reply
