### ISSUE TITLE
No spell suggestions in right click menu

### ISSUE THREAD

**Issue by derek-wang** [nwjs/nw.js#6424]
NWJS Version : 0.21.6
Operating System : osx 10.13.3

Hi:
  i am facing an issue that i load my website in the nwjs and enabled the spell check in the package.json. Inputs shows the underline highlight on the incorrect spelling words, but only cut/copy/paste after right click on it, there is not spell suggestions. I tried with local index file, however works fine and shows spell suggestions. I'm not sure is because of loading a site url or not. Please help! Thanks
![jietu20180125-112526 2x](https://user-images.githubusercontent.com/1480112/35407993-792b4306-01c2-11e8-8eb6-fe7403c2d5ad.jpg)

**Comment by Christywl** [comment]
I can reproduce this with nwjs-sdk-v0.28.0 when set `"main": website` in `package.json`.
If set `"main":"index.html"` and add the website in the index.html, it works fine.
