### ISSUE TITLE
Node webkit iframe set localstorage item DOMException

### ISSUE THREAD

**Issue by sap1983** [nwjs/nw.js#6433]
Hi all,
    I have build an **ember project** and running it in **node-webkit**. In my ember app i am opening an iframe and trying to set LocalStorage on that **iframe** which raises a DomException :

> **Uncaught DOMException: Failed to execute 'setItem' on 'Storage': access is denied for this document.**

Its an intermidiate issue sometimes it does'nt give error and everything works fine.

**Comment by Christywl** [comment]
Could you please upload a ready sample to reproduce this issue?

**Comment by Christywl** [comment]
close until there is more information
