### ISSUE TITLE
Devtools can not inspect all js sometimes

### ISSUE THREAD

**Issue by cecilpeng** [nwjs/nw.js#6436]
NWJS Version : 0.22.2
Operating System : win7 64

In my program, some js ok, some js not. The difference is that some were loaded while page loading and some were dynamically loaded.
I can not always reproduce this. It confused me a lot when debugging. Do anyone encounter it?

**Comment by Christywl** [comment]
Is this issue reproduced on the latest nwjs build? And could you please upload a sample for this? 
If just want to get some help, you could ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Christywl** [comment]
close until there is more information
