### ISSUE TITLE
maximize-frame-bar suddenly show

### ISSUE THREAD

**Issue by Dimtime** [nwjs/nw.js#6441]
![1](https://user-images.githubusercontent.com/16452588/35693880-9ece32b6-0790-11e8-8411-77da1993bfd5.png)
```
nw.Window.open('index.htm',{frame:false },test); 
function test(e) { e.maximize(); e.moveTo(0,100); }
```
Windows 10
When we first make win.max and then win.move it - hidden bar showing to us

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 10 with nwjs-sdk-v0.28.0.
![image](https://user-images.githubusercontent.com/20039821/35711408-ba49bd64-07f7-11e8-9bbb-bdca8cba576d.png)

Did you use the latest nwjs build?

**Comment by Dimtime** [comment]
Hm... yes last nwjs and this ver OS:
![default](https://user-images.githubusercontent.com/16452588/35718197-76ec7df2-07f4-11e8-9220-14a771a5af60.png)

**Comment by Christywl** [comment]
I used: 
```
Windows 10 Home 
1709 
16299.98
```

**Comment by Dimtime** [comment]
I try get more tests and have one new delails:
what ver you have 32 or 64?
two 64 pc = bug+
one 32 pc = yes all ok

**Comment by Christywl** [comment]
I used Windows 64bit. I also try another Windows 10 64bit, it also works fine.

**Comment by Dimtime** [comment]
Hm do more tests and i dont know what it can be...
Update ver on win32 to my last on other = still nothing
Run 32 bit nw js on 64 bit =still bug

What kind of dependency there can be? ideas?

**Comment by TheJaredWilcurt** [comment]
I am not able to reproduce this. Used this code:

```js
nw.Window.open('index.htm', { frame: false }, function (win) {
    win.maximize();
    win.moveTo(0, 100);
});
```


Intended functionality works for me.
