### ISSUE TITLE
webviem error on play music

### ISSUE THREAD

**Issue by Dimtime** [nwjs/nw.js#6443]
![default](https://user-images.githubusercontent.com/16452588/35728114-870f1d58-081b-11e8-9181-a05157f2b05a.png)

with webview i get error when try listen music on https://vk.com/ 

what it can be? (win10 - nw28)

**Comment by Christywl** [comment]
Could you please upload a ready sample to reproduce this issue?

**Comment by Dimtime** [comment]
My mistake - I did not turn off:
--enable-node-worker
