### ISSUE TITLE
Trying to compile NWJS 28 for RasPi 3 with ARMv7

### ISSUE THREAD

**Issue by techborn** [nwjs/nw.js#6446]
NWJS Version : 0.28.0
Operating System : Ubuntu 16.04

### Expected behavior

Successful compilation of the latest (currently 0.28.0) NW.js release for RasPi3/ARMv7

### Actual behavior

Compilation fails

### How to reproduce

- Following https://github.com/LeonardLaszlo/nw.js-armv7-binaries/blob/master/docs/build-nwjs-v0.23.x.md with changes to point to the v0.28.0 release.

- Once I get to the `ninja -C out_gn_arm/Release node`, I get fatal "file not found" errors thrown. They are as follows:
    - `sys/types.h` thrown by `src/third_party/node-nw/deps/zlib/zconf.h:444:14`
    - `errno.h` thrown by `src/third_party/node-nw/deps/uv/include/uv-errno.h:25:10`
    - `stdio.h` thrown by `src/third_party/node-nw/deps/uv/src/inet.c:18:10`

I'm not sure what I might be missing. I'm not familiar with compiling C/C++ code.
If any other additional info is needed, let me know.

**Comment by NegativeIQ** [comment]
These will sound dumb but try

**Comment by techborn** [comment]
Did that, still throwing errors.
Tried purging and re-installing, but again still errors.
