### ISSUE TITLE
Node URL module broken on Windows

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6448]
NWJS Version : v0.28.0 SDK x64
Operating System : Windows 10 x64

### Expected behavior

return parsed url object

### Actual behavior
Uncaught NodeError: Invalid URL: https://example.org/foo#bar
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)

### How to reproduce
You can simply test this by opening an inspector and pasting the following code into the console
```
var { URL } = require('url');
var myUrl = new URL('https://example.org/foo#bar');
```

### Extra info:
The Linux v0.28.0 SDK x64 is not affected by this issue.
Windows v0.26.0 and v0.27.0 have also been affected (i didn't test further back).
This issue is directly related to #6444 which i reported yesterday.

**Comment by rogerwang** [comment]
This is fixed in git and is available at: https://dl.nwjs.io/live-build/nw28/02-05-2018/c91f2ce-5bae971-f62d7a0-44a6e80/v0.28.1/

**Comment by cTn-dev** [comment]
Thank you very much @rogerwang !
