### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by simar7777** [nwjs/nw.js#6449]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System : Windows 2008 Server runnin gon Virtual machine
Tray Nw.js should appear seperate instance for seperate user but it's running one instance and tried -user-data-dir option as well its not working 

<!- What do you think should happen? ->

Tray nw.js program should create multiple instance 

<!- What actually happens? ->

Just create tray based nw.js program and try to run twice with -user-data-dir option you should get 2 tray icons but i am getting single tray icon 

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by Christywl** [comment]
Could you please upload a ready sample to reproduce this issue?

**Comment by Christywl** [comment]
I try a simple test and can't reproduce this issue with nwjs-sdk-v0.29.0.
![image](https://user-images.githubusercontent.com/20039821/37319679-1ae27874-26ab-11e8-8ad9-5c5dca4ac854.png)

**Comment by simar7777** [comment]
Thnaks , will send you the details ...

**Comment by simar7777** [comment]
Thanks for the timely support . Yes the problem is solved. Please close the issue.
