### ISSUE TITLE
delete folder with app.filepath

### ISSUE THREAD

**Issue by Dimtime** [nwjs/nw.js#6450]
1. i open nwjs with file
2. try delete file - ok, then try delete folder with it
3. get error "close app before" (win10)

how i can get free dir without from blocking nwjs?

**Comment by TheJaredWilcurt** [comment]
Information garnered from the Gitter chatroom:

**OS:** Windows

## Steps to reproduce:

1. Download the SDK version of NW.js 0.28.0.
2. Unzip the contents to it's own folder.
3. Create a folder next to `nw.exe` called `package.nw` and put two files inside of it: `package.json` and `index.html`.
    **package.json:**
    ```json
    {
        "name": "test",
        "main": "index.html"
    }
    ```
    **index.html:**
    ```html
    <!DOCTYPE html>
    <html>
      <head>
        <title>Example</title>
      </head>
      <body>
        <h1>Hello World</h1>
        <script>
          nw.Window.get().showDevTools();
          console.log(nw.App.argv);
        </script>
      </body>
    </html>
    ```
4. Then create a folder on your desktop called `sample`.
5. Inside the `sample` folder create a `junk.txt` file with some junk text in it.
6. Then drag and drop that text file on to the `nw.exe`.
7. It will launch NW.js, show a window and dev tools. The dev tools will log an array with a path to `sample/junk.txt`.
8. Attempt to delete the `sample` folder while NW.js is still running.
    ![Folder in use, cannot delete](https://user-images.githubusercontent.com/4629794/35778521-4e60e9a0-098d-11e8-9c65-8fe356d2820d.png)

Process explorer shows NW.js has 3 hooks into this location:

![Process Explorer](https://user-images.githubusercontent.com/4629794/35778529-65840478-098d-11e8-8160-80d26da382ea.png)

You are able to delete `junk.txt`, but not the folder containing it until NW.js is closed.

@Dimtime's question is if there is a way to force NW.js to release the folder so it can be deleted, without having to close the program.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by izure1** [comment]
I have the same issue also.
The directory is not deleted, but files gone when I turned on the application for a long time.
