### ISSUE TITLE
Package.json not loading files (only Mac OS Sierra)

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#6452]
NWJS Version : tested 0.28.0 and 0.27.x.
Operating System : MacOS Sierra (**only Sierra!!!** Mavericks, El Captain fine)

I want load credits.html (nwjs contain this file). When I run the application I see "hello wolrd" (https://user-images.githubusercontent.com/11089335/26933202-c2aac846-4c5d-11e7-898d-1c0426058be1.jpg).

My package.json (this working on Mavericks, El Captain but not Sierra):
```
{
	"main": "credits.html",
	"name": "Test",
	"description": "Test",
	"chromium-args": "--in-process-gpu --disable-transparency",
	"version": "1.0.0",
	"window": {
		"title": "Test",
		"toolbar": false,
		"fullscreen": false,
		"width": 896,
		"height": 504,
		"resizable": true
	},
	"webkit": {
		"plugin": false
	}
}
```

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac(10.12.6/10.13.3) with nwjs-sdk-v0.28.1
<img width="1280" alt="screenshot-mac1" src="https://user-images.githubusercontent.com/20039821/35838666-68d3593a-0b27-11e8-9018-ecf3abfc31db.png">
<img width="1280" alt="screenshot-mac2" src="https://user-images.githubusercontent.com/20039821/35838740-bdf8e128-0b27-11e8-80e6-2a359d8d4fa5.png">

**Comment by hooker99** [comment]
Hmmm ... I tested only 0.28.0 and 0.27.x. normal (not skd). I will check the version of nwjs-sdk-v0.28.1 (+ normal). I will give you feedback soon. Thank you for your answer.

**Comment by shamun** [comment]
Same here https://github.com/nwjs/nw.js/issues/6466, bug from hell, in past old versions when chromium 57 or 55 was used then it was never happened and now its like permanent on OSX.

**Comment by credomane** [comment]
Where are you putting your package.json? Getting the default nw.js page indicates to me that package.json isn't located in the correct place or is failing to load. Would be nice if the console in the sdk version indicated where it tried to find package.json and why it failed. Anyways...

On mac it has to go into `nwjs.app/Contents/Resources/` then depending on if it is plain files or a zip file changes it a little bit.

Plain files: create a new folder named `app.nw` and put `package.json` in that. Making the full path  `nwjs.app/Contents/Resources/app.nw/package.json` 
Zip file: rename the zip to `app.nw`. Also it MUST be a zip type archive. 7z, rar, etc will NOT work. Making the full path  `nwjs.app/Contents/Resources/app.nw` 

It should work then. I don't have a Mac to test it myself. I just ran into a similar problem myself on Windows and discovered this bug report. Though my issue was my own fault. Was packaging package.nw as a 7z archive and not a zip archive.

**Comment by Christywl** [comment]
@hooker99 , does this work for you on the latest nwjs build? I try this again on Mac 10.12.6 with nwjs v0.29.0(sdk+normal), both of them work fine.

**Comment by Christywl** [comment]
close until there is more information
