### ISSUE TITLE
sos, due to heat update related problems

### ISSUE THREAD

**Issue by loser7758** [nwjs/nw.js#6455]

**Comment by loser7758** [comment]
and also,if i use this method ,we can not use cookies ,so we want to use nwjs's webkit to view our server's website with visit nwjs's local nodejs,but we can not do it because we can not Heat update

**Comment by loser7758** [comment]
问题的根本是同源策略，本地软件没有同源策略

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
Thanks.
