### ISSUE TITLE
how protect express server project?

### ISSUE THREAD

**Issue by jamilservicos** [nwjs/nw.js#6458]
"node-main": "./server/bin/main",
"main": "http://localhost:3000"

in main:
App = require('../app.js');

if I create an "app.bin" nodejs can not read!
any have solution to protect the private modules and read inside the express server?
the project has privates submodules called by other privates modules

ex:
app.js call utils.js
utils.js call database.js

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
