### ISSUE TITLE
Videos randomly freezing in 28.0/1

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#6459]
I'm using webm for video and with the newest version of NWjs they frequently freeze at random positions. At first I believed this only to be an issue on my miniPC with Win10. I then switched codec from Vorbis to VP9 in the hope of getting the problem solved. Testing this on Win7 lead to a freeze (at the end of a second video) as well. 

Everything works fine while testing in Chrome. Videos work absolutely fine in 27.3 (but I need the update, due to a pointer-lock bug on win10, that gets solved in the new version)

The project is rather large and I can't single out the issue at the moment. I just wanted to report the issue, as I have not found any information regarding the problem online.

**Comment by rogerwang** [comment]
Could you provide the web page that works fine in Chrome?

**Comment by marcgfx** [comment]
There is no web page and I can't give out the source of the full project. I was hoping that maybe some others will also have this issue (and at least find it on google). If I have time, I will make a sample, but I don't know if the issue could be related to any of my code. I just know it used to work fine and now it does not.

**Comment by marcgfx** [comment]
https://www.dropbox.com/s/8ymjh1gw2509bag/freeze_issue.zip?dl=0

I've managed to reconstruct the problem on a simpler basis, but also less reliable. It just does not happen as fast. In the sample I add a video, play it, remove it, add the next one. There are 4 videos in total. 2 videos using ogg and 2 using vp9 (that turned out green for some reason). the vp9 ones show a very weird pattern (not the video) on my mini pc with win10.
I cant get the sample to freeze on win7 (this happens infrequently in the whole project on win7).

**Comment by marcgfx** [comment]
Just tested the new build 28.2. It ran twice but then froze on the third try. That's a lot better than in previous tests, but still not fixed unfortunately. If it weren't for an issue with pointerlock on windows 10 I would happily use an older version. I don't really feel like diving into the source and start merging selected code between branches.

**Comment by marcgfx** [comment]
I've found a fix for my situation, that allows to skip the frozen video. I use a setTimeout function based on the duration of the video + 200ms. If the video has not fired the ended event already, the setTimeout function fires the callback. Not great, but at least I don't have a blocked application.

**Comment by Christywl** [comment]
I try the marcgfx's sample some times on Windows with nwjs-sdk-v0.28.3, reproduce this issue twice(play the videos for several minutes). Also reproduce on Linux Ubuntu 16.04, more frequently than Windows.

**Comment by rogerwang** [comment]
I loaded index.html with Chrome browser in windows and it freezes as well sometimes. Please report this to upstream: https://crbug.com/new

**Comment by marcgfx** [comment]
thanks for testing. should I report this to upstream, or who will?

**Comment by marcgfx** [comment]
@rogerwang @Christywl Thanks for testing! I don't think I ever ran it for that long in the browser, good thinking. Should I report this to upstream, or who will?

**Comment by rogerwang** [comment]
It would be better that you would report it.

**Comment by marcgfx** [comment]
@rogerwang @Christywl reported the issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=816423

**Comment by rogerwang** [comment]
Close as it's tracked in upstream.
