### ISSUE TITLE
how can i run an 3rd-party exe with a commandline

### ISSUE THREAD

**Issue by michapixel** [nwjs/nw.js#646]
i have:

```
$('a').on('click',function(e) {
        var linkpath = path.join(process.cwd(),'app', $(this).attr('href'));
        var cmd = path.resolve() + "\\bin\\bin.exe";
        gui.Shell.openItem(cmd + " command");
        e.preventDefault();
    });
```

but gui.Shell.openItem returns an error saying file is not in place. 
i can clearly issue gui.Shell.openItem(cmd) which will run the exe. but with arguments it fails.

any hints would be great.

**Comment by yahyameo** [comment]
I am unable to run this command from node, to run nwjs directly from node
"C:\Users\yahya\Downloads\nwjs\nw.exe C:\Opolo\opolodesktopwal"
