### ISSUE TITLE
Touch events stop responding, possible focus issue

### ISSUE THREAD

**Issue by socaldev99** [nwjs/nw.js#6461]
NWJS Version : v0.28
Operating System : Windows 10 Pro

### Expected behavior

Touch screen works normally with no interruption

### Actual behavior

After some usage of NWJS in kiosk mode, touch events stop working. The mouse and keyboard still work, and touch events work outside NWJS application. This is an application pointed directly to a web URL using window.location = 'https://....'

The last entry in the log is 
VERBOSE1:browser_accessibility_event.cc(138)] Accessibility event + EVENT_OBJECT_FOCUS/focus result=Sent source=FromWindowFocusChange target=[[id=0 rootWebArea (0, 0)-(0, 0) busy=true actions=]]

This seems to happen randomly, sometimes during heavy use and sometimes after light use but there doesn't seem to be any pattern to it happening. Closing and re-opening nwjs fixes it.

### How to reproduce

This is random and intermittent so it is difficult to reproduce. Any suggestions on how to trigger the issue or debug it would be appreciated.  Willing to try anything at this point. Thank you.

Here are things that I have tried with no success:
Disabling GPU, disabling renderer accessibility, disabling touch events, setting focus to the window on blur

**Comment by nullquery** [comment]
Same issue. Problem occurs in a frame that goes to an external web address. No iframes or framesets are used. Though content is loaded dynamically w/ AngularJS routing. Difficult to reproduce.

**Comment by rogerwang** [comment]
@socaldev99 could you please provide the full log?

**Comment by NetOneGames** [comment]
Havent tested touch for some time but found last night definitly touch is cutting out every few seconds, if framerate less than 60 it seems.  Im finding hard to replicate on simple project though.

**Comment by nullquery** [comment]
Looks like I missed this. As far as I know, the issue still occurs...
