### ISSUE TITLE
Is node.lib in https://dl.nwjs.io/v0.28.0/x64/ wrong?

### ISSUE THREAD

**Issue by yonosteward** [nwjs/nw.js#6464]
NWJS Version : v0.28 (Windows x64)
Operating System : Windows 7 (64)

When I try to build a native add-on on Windows 7 (x64), I found the following issues:

1: The node.lib in https://nodejs.org/download/release/v9.4.0/win-x64/ has a different size with the node.lib in https://dl.nwjs.io/v0.28.0/x64/. Why they have such a big difference? 

2: If I use node.lib in https://dl.nwjs.io/v0.28.0/x64/  to build a native add-on using Visual studio 2015, I got many "unresolved symbol" linking errors. On the other hand, if I use the node.lib from https://nodejs.org/download/release/v9.4.0/win-x64/, then I will be able to build successfully.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
