### ISSUE TITLE
Cannot run nwjs on Ubuntu

### ISSUE THREAD

**Issue by xcmaya** [nwjs/nw.js#6465]
NWJS Version : v0.28.0
Operating System : Ubuntu 12.04.4 LTS

After downloading nwjs v0.28 for Linux (64), the nw cannot run on Ubuntu 12.04.4 LTS. The error message is:
`./nw: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory`.

Any idea to fix this?

**Comment by jamilservicos** [comment]
try:
sudo apt-get install libatk-bridge2.0-0

if I'm not mistaken this is one of the google browser dependencies.

**Comment by rogerwang** [comment]
close as it's not a bug.
