### ISSUE TITLE
OSX - when i open, it always open default page instead of the page from package.json

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#6466]
In OSX when i open nwjs it always open as following instead of package.json file, how to on execute always open package.json?

![image](https://user-images.githubusercontent.com/107349/36037853-42e289dc-0dbe-11e8-9854-4a1d01a64663.png)

**Comment by Christywl** [comment]
It works fine on Mac for me with nwjs-sdk-v0.28.3.  Where do you put your package.json?

**Comment by rogerwang** [comment]
close until more information is available.
