### ISSUE TITLE
LTS Release for nodejs 8.9.*

### ISSUE THREAD

**Issue by CxRes** [nwjs/nw.js#6475]
Please make an LTS release with node 8.9.*!!!!!

**Comment by Christywl** [comment]
@rogerwang , could you please take a look at this?

**Comment by rogerwang** [comment]
What's the need for Node.js 8.9 ? We don't do LTS refresh without good reason.

**Comment by CxRes** [comment]
Node 8.9.x is the node LTS with security fixes. For those who are using modules tested against node LTS, moving to 9.x is not preferable which leaves us stuck with node 8.8.x, again not preferable. I know keeping two independent products (chromium and node) aligned is hard but could you please make an exception. Thanks!

**Comment by rogerwang** [comment]
The 0.14 branch is only for Win XP and legacy version of OSX. For higher version OS, please use the latest stable version.

**Comment by CxRes** [comment]
@rogerwang What the hell are you even talking about! 0.14 branch????

**Comment by rogerwang** [comment]
0.14 branch is LTS you are referring to.

**Comment by CxRes** [comment]
There has been some confusion. I am not talking about the nwjs LTS branch. I am referring to an update with nodejs LTS which is currently 8.x. The last release of nwjs with node 8.x was 0.26.1 (released 10-26-2017 with nodejs 8.8.1). Since then nodejs LTS has been updated 8.10.0 which has significant changes over 8.8.1. This is the reason I requested an update.

**Comment by rogerwang** [comment]
That's not our branching model. We don't have any branch tracking node.js LTS, as Chromium matching that version of Node would not be secure. Our stable branch tracks the latest Chromium stable and Node.js stable.

**Comment by CxRes** [comment]
nodejs 8.10.0 and 9.8.0 (on which nwjs 0.29.1 is based) are using identical versions of v8 (6.2.414.46). The matching issue does not arise...

**Comment by rogerwang** [comment]
This is only a specific case. It doesn't justify that NW stable should
track Node LTS.

**Comment by CxRes** [comment]
But from time to time node crew equalize the v8 versions on current and LTS. There are very good reasons for people (inc. myself) to build our modules against LTS branch of node which we might want to use in NWjs. It is my hope that you would consider supporting this (on those occasions when such equalization is done).

(Thanks again for considering. I will not post anymore unless you ask a specific query)...

**Comment by rogerwang** [comment]
The Chromium-Node.js integration requires that the gap of v8 versions in
those 2 projects should be kept minimum. And Node LTS stays on a specific
version for a long time while Chromium moves on. That's why NW stable
branch should track Node stable rather than LTS.
