### ISSUE TITLE
process.cwd() returns wrong path

### ISSUE THREAD

**Issue by arturadib** [nwjs/nw.js#648]
Shouldn't `process.cwd()` return the directory the user is currently at? It seems to always return the path where the app source lives regardless of where the user is running it from.
##

**Comment by lsim** [comment]
I am playing around with a 3-way merge tool, which needs to receive relative paths to the various versions of the file being merged in order to integrate with things like SourceTree. This bug makes that hard to achieve.
For scenarios/platforms where process.env.PWD contains the desired value, I have put the following in my index.html as a workaround:
<script type="text/javascript">
  process.chdir(process.env.PWD);
</script>
I believe this works for mac and linux - but not for windows.

**Comment by dhruska** [comment]
@lsim Were you able to find a solution that also works for Windows?

**Comment by lsim** [comment]
Sorry, no. I haven't yet had reason to try. What I have done in the mean
time is to switch to atom shell. I can't say for certain it doesn't have
this weakness (or others like it), but I like it so far and am not going
back to nw.js

**Comment by xenohunter** [comment]
The problem still exists. Are there some clues for its solution?

**Comment by Arti3DPlayer** [comment]
for me `process.cwd()` or `execPath` returns path like this:

`/private/var/folders/5f/2w5ss9tn6ksgwmxkl1lrqyyh0000gn/T/AppTranslocation/8C45F9CD-87C6-4902-8D10-6586815A15B6/d/Myapp.app/Contents/Resources`

**Comment by octachrome** [comment]
@rogerwang This is really hard to work around as an app developer. Could you implement a quick fix, such as storing the original working directory in a variable somewhere we can access it before NW.js changes the working directory?

**Comment by rogerwang** [comment]
Will provide a way. Thanks.

**Comment by wittend** [comment]
I love nw.js, but this has been an absolute plague to me.  It is the biggest weakness in nw.js I have found in a year of using it.  The second biggest problem is the lack of a reliable packaging solution.
I develop on Linux and distribute on Windows and (regrettably) Mac.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/). `nw.App.startPath` is provided for the start working directory.

**Comment by wittend** [comment]
T Hanks!

**Comment by octachrome** [comment]
Thanks, this fix is really appreciated.

**Comment by yesprasoon** [comment]
I am working on Mac Monterey

process.cwd() returns:
'/private/var/folders/z9/kdtwssh56qxg2sjbd8dqgx1r0000gn/T/AppTranslocation/0AAEDF9A-5C88-44EF-883F-D94D781D8999/d/nw.app/Contents/Resources/app.nw'

process.execPath returns:
'/private/var/folders/z9/kdtwssh56qxg2sjbd8dqgx1r0000gn/T/AppTranslocation/0AAEDF9A-5C88-44EF-883F-D94D781D8999/d/nw.app/Contents/Frameworks/nwjs Framework.framework/Versions/98.0.4758.82/Helpers/nwjs Helper (Renderer).app/Contents/MacOS/nwjs Helper (Renderer)'

nw.App.startPath returns
'/'

Is there any way to retrieve the actual path of the “nw.app”? Just like it comes, when we select a file from folder?
