### ISSUE TITLE
No rounded corners

### ISSUE THREAD

**Issue by denigada** [nwjs/nw.js#6483]
Hello, please dont tell me this is a duplicate because I tried everything, only solution I came up with is adding
`"transparent":true`

- and making background of body transparent
- and adding border-radius to html tag

However, when I do that, the window no longer has shadows around it. Anyone know how to have rounded corners with nw.js?

OS: OSX 10.13

**Comment by rogerwang** [comment]
Is this #175 ?

**Comment by rogerwang** [comment]
close as duplicate. Any update and discussion will be in #175
