### ISSUE TITLE
`process.execPath` is a temp path of "nw.app", how to get the file path ?

### ISSUE THREAD

**Issue by tangyue0924** [nwjs/nw.js#6484]
NWJS Version : 0.27.4
Operating System : MacOS

### Expected behavior

Could `process.execPath` returns the file path of `nw.app`

### Actual behavior

`process.execPath` returns a temp path like `/private/var/folders/yx/lnt2b8ps22z4s0h4rv4p9vyc0000gn/T/AppTranslocation/81C3DD26-733E-47E8-9761-4AC6A28EE9CC/d/nw.app`.
That's not the file path of nw.app

THX

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by yesprasoon** [comment]
I am working on Mac Monterey

`process.cwd()` returns:
'/private/var/folders/z9/kdtwssh56qxg2sjbd8dqgx1r0000gn/T/AppTranslocation/0AAEDF9A-5C88-44EF-883F-D94D781D8999/d/nw.app/Contents/Resources/app.nw'

`process.execPath` returns:
'/private/var/folders/z9/kdtwssh56qxg2sjbd8dqgx1r0000gn/T/AppTranslocation/0AAEDF9A-5C88-44EF-883F-D94D781D8999/d/nw.app/Contents/Frameworks/nwjs Framework.framework/Versions/98.0.4758.82/Helpers/nwjs Helper (Renderer).app/Contents/MacOS/nwjs Helper (Renderer)'

`nw.App.startPath` returns
'/'

Is there any way to retrieve the actual path of the “nw.app”? Just like it comes, when we select a file from folder?
