### ISSUE TITLE
Opened window events document-start and document-end never fire

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6490]
Tested on Win7 x64 with SDK 0.29.0-beta1

When opening a new window and listening for both events `document-start` and `document-end` they are never fired, but the callback is executed as expected:

````js
var newWindow = nw.Window.open(
    "https://www.google.com",
    function () {
        console.log("window opened");
    }
);
newWindow.on("document-start", function () {
    console.log("document-start");
});
newWindow.on("document-end", function () {
    console.log("document-end");
});
````

Console only shows  `window opened`

Search reveals that this issue is not the first and its fix has never been confirmed, wondering if it is still unfixed since then: https://github.com/nwjs/nw.js/issues/4788#issuecomment-216462226

**Comment by rogerwang** [comment]
Thanks for reporting. The event handler should be registered in the callback.

**Comment by Yonezpt** [comment]
If it is registered in the callback only `document-end` fires, `document-start` is never fired. I assume that's because the callback runs at the same time as `document-start`? In which case what is the purpose of `document-start`?

**Comment by rogerwang** [comment]
Correct. http://docs.nwjs.io/en/latest/References/Window/#event-document-startframe

**Comment by Yonezpt** [comment]
I see, it is more specific for `iFrame` listening rather than `Window.open`. Thanks for the clarification.
