### ISSUE TITLE
Class FIFinderSyncExtensionHost is implemented in both

### ISSUE THREAD

**Issue by Arti3DPlayer** [nwjs/nw.js#6494]
NWJS Version : 0.25.4 and 0.28.3
Operating System : OSX

I have a code where user should select a file:

```
chrome.fileSystem.chooseEntry({
        type:'saveFile',
        suggestedName: 'My file.txt',
        accepts: [{
              description: 'Text Plain (.txt)',
              extensions: ['txt']
        }]
       }, function(fileEntry) {
           // other stuff
});
```

After file has been selected in dialog window I received warning:

`objc[3331]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8cba8b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x113fc9cd8). One of the two will be used. Which one is undefined.`

**Comment by Christywl** [comment]
I run [chrome-app-samples/filesystem-access](https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/filesystem-access) on Mac with nwjs-sdk-v0.28.3, it works fine, don't see this error. Could you please upload your full sample to reproduce this issue?

**Comment by rogerwang** [comment]
close until more information is available.
