### ISSUE TITLE
Security. Unexpected behaviour when mixing node-remote and nwdisable directives on the same domain

### ISSUE THREAD

**Issue by paoven** [nwjs/nw.js#6497]
NWJS Version : 0.28.3.win-x64
Operating System : Microsoft Windows 8.1 Pro 64 bit

### Scenario

I configured a **local main** page named index.html which loads multiple iframes from a remote URL (same domain/IP). Iframe named _node_ uses node.js APIs so I had to configure accordingly **node-remote** directive in package.json. I need to prevent node.js usage and enable default browser security on _normal_ iframe. In order to do that I configured _normal_ frame with **nwdisable** and **nwfaketop** attributes.
**package.json**

```
{ 
   "name": "Test",
   "main": "index.html",
   "node-remote" : ["https://mydomain"]
 }
```

**index.html**
```<html>
<head>
</head>
<body>
	<iframe name="normal"  width="600" height="600"  src="https://mydomain/normal.html" nwdisable nwfaketop></iframe>
	<iframe name="node"  width="600" height="600"  src="https://mydomain/node.html"></iframe>
</body>
</html>
```

**normal.html**
```
<html>
<head>
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; object-src 'none'">
</head>
<body>
      <a onmouseover="alert('over')" href="#">CSP should prevent inline script</a>
</body>
</html>
```

**node.html**
```
<html>
<head>
    <script type="text/javascript">
        require('fs');
    </script>
</head>
<body>
</body>
</html>
```

### Expected behavior

Iframe _normal_ should act as a traditional iframe and, with reference to the given example, it should enforce CSP directives and of course enable all default browser security mechanisms like Same Origin Policy. 

### Actual behavior

node.js API is disabled on _normal_ frame but from a security point of view it acts as a node frame. If I remove the domain from **node-remote** directive in package.json, _normal_ iframe works as expected but of course iframe _node_ stops working.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.29.0.

**Comment by rogerwang** [comment]
The is expected. `node-remote` operates globally on a domain basis and overrides any browser security mechanism.

**Comment by rogerwang** [comment]
A little correction. The match is not on domain basis, it can match path as well. See the definition here: https://developer.chrome.com/apps/match_patterns
