### ISSUE TITLE
NW.js 0.29.0: passing --disable-software-rasterizer appears to disable hardware acceleration

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#6498]
Tested on Windows 10 x64

In Construct we pass --disable-software-rasterizer on the command line to make sure we don't get software rendering. However in NW.js 0.29.0, it appears that passing this flag causes WebGL to become unavailable. If I delete the flag from the command line, I get hardware-accelerated WebGL again. It's strange behavior since despite the name, the flag appears to now also disable hardware acceleration.

This may well be an upstream issue but thought I'd give you a heads up in case it is something to do with NW.js or there are other reports.

Demo: [package.zip](https://github.com/nwjs/nw.js/files/1789809/package.zip)
This is based on a simple Construct export. It displays the renderer info at the top. If it says canvas2d then WebGL isn't working; if it is, it should say WebGL and include the renderer string.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.29.0.

**Comment by AshleyScirra** [comment]
BTW if you want a minimal repro, you can just try:
```js
const canvas = document.createElement("canvas");
const gl = canvas.getContext("webgl");
console.log(gl);  // null if not working
```

**Comment by rogerwang** [comment]
This is reproduced in upstream Chrome browser. Using the switch disables hardware acceleration according to 'chrome://gpu' info page.
Please report this to upstream: https://crbug.com/new

**Comment by AshleyScirra** [comment]
I can't reproduce that with Chrome Canary - running `chrome --disable-software-rasterizer` on my system launches Canary and chrome://gpu says WebGL and WebGL 2 are still hardware accelerated. Maybe it's upstream but already fixed?

**Comment by rogerwang** [comment]
Could be. I was testing with Chrome stable 65.

**Comment by rogerwang** [comment]
Will try to cherry pick the upstream fix.

btw, this switch might not be used given we supports swiftshader now. It disables swiftshader which lets you use CSS 3D and WebGL even on hardware with incapable GPUs.

**Comment by rogerwang** [comment]
Please try this build as we'll release it soon: https://dl.nwjs.io/live-build/nw29/03-14-2018/4aacedc-733b9b3-24a4d36-f80f428/v0.29.1/

**Comment by AshleyScirra** [comment]
@rogerwang - looks like it's working fine now. Thanks!

**Comment by rogerwang** [comment]
Good to know it. Thanks.
