### ISSUE TITLE
WebUSB device selection menu not appearing

### ISSUE THREAD

**Issue by cactrot** [nwjs/nw.js#6500]
NWJS Version : nwjs-sdk-v0.28.0-win-ia32
Operating System : Windows 10

### Expected behavior

On Chrome 64 I can successfully get the device selection menu to open by calling requestDevice.

### Actual behavior

When I try to call requestDevice it immediately returns with "DOMException: no device selected.".

### How to reproduce

let vendorId_arg = 0xXXXX; //put vendor id here
let productId_arg = 0xXXXX; //put product id here

const filters_ids = [
			  {vendorId_arg: productId_arg},
];

let device = await navigator.usb.requestDevice({filters: filters_ids});

### more notes

I have tried calling it from the console as well as from an event listener on a button.
I event tried calling it from the background page console.

I have tried various command line arguments:
--enable-experimental-web-platform-features
--disable-webusb-security
--enable-webusb
--enable-logging=stderr
//ref https://github.com/nwjs/nw.js/issues/5808

and:
--enable-features=WebUSB 
// this works on Chrome version 64 after google disabled WebUSB for security
// ref  https://bugs.chromium.org/p/chromium/issues/detail?id=819197

Just can't seem to figure out what I'm missing.

**Comment by Christywl** [comment]
Using the sample in [#5808](https://github.com/nwjs/nw.js/issues/5808), I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.29.0.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by faboulous1** [comment]
There is a question i would like to ask, Nwjs helps us to create desktop applications, and in normal circumstances, all desktop apps have access to the usb without any sort of permissions or popup appearing. Isnt it unnecessary? And extra step that compromises user experience? I can understand nodewebkit is using the chromium under the hood, but cant we change and remove this extra step to provide better user experience??? While creating nodewebkit app , one major thing should be kept in mind, that its not a web app, its a DESKTOP App for desktop OS, so any extra things can cause big user experience compromises, that can change the developers mind of using web based apps (electron or nwjs). and can lead them to develop native apps that provide full control. Hope i can clarify this thing and i hope these extra things should be removed.
I am not sure, if i can disable this popup or not , so far i couldnt, if you know then please let me know. Thanks
