### ISSUE TITLE
nw-gyp doesn't work properly on Windows 7

### ISSUE THREAD

**Issue by yonosteward** [nwjs/nw.js#6501]
======== TEMPLATE BUG FORM ========

NWJS Version : v0.28
Operating System : Windows 7

I tried the hello.cc and binding.gyp examples from https://nodejs.org/api/addons.html. The original node-gyp can work very well. 

But the nw-gyp doesn't work and it complains that it cannot find the Python:

`C:\Users\Test: can't open file 'User\Anaconda\python.EXE': [Errno 2] No such file or directory`

It should be noted that the user name, "Test User", contains a white space. I guess that could be the reason.

**Comment by Christywl** [comment]
Same as https://github.com/nwjs/nw-gyp/issues/116

**Comment by rogerwang** [comment]
close as duplicate.
