### ISSUE TITLE
indexedDB.open in node enabled worker completely crashes NW.js

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6504]
NWJS Version : 0.29.0 SDK
Operating System : Windows 10 x64

### Expected behavior
Database should open (this is a regression, worked fine in 0.28.3)

### Actual behavior
NW.js closes (there doesn't seem to be any debug.log left behind)
### How to reproduce
[example_0.29.0.zip](https://github.com/nwjs/nw.js/files/1796293/example_0.29.0.zip)

### TLDR
Calling indexedDB.open in a web worker closes NW.js when "--enable-node-worker" is provided in package/chromium-args.

**Comment by cTn-dev** [comment]
@rogerwang could you have a look please?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
