### ISSUE TITLE
can't open link in default browser

### ISSUE THREAD

**Issue by j7126** [nwjs/nw.js#6506]
I have a link
`<a target="_blank" href="https://website.com">click here</a>`

I am trying to have it open in the default browser but it is not working. here is my code:
`      $( document ).ready(function() {
        ngui.Window.get().on('new-win-policy', function(frame, url, policy) {
          policy.ignore();
          ngui.Shell.openExternal(url);
        });
      });`

### Expected behavior

link opens https:// website.com in system default browser 

### Actual behavior

it opens in new nwjs window

**Comment by Christywl** [comment]
I can't reproduce this issue with nwjs-sdk-v0.29.0. `https://website.com` opens in my default browser.

index.html:
```
<html>
   <head></head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script>
$( document ).ready(function() { nw.Window.get().on('new-win-policy', function(frame, url, policy) { policy.ignore(); nw.Shell.openExternal(url); }); });
      </script>
	  <a target="_blank" href="https://website.com">click here</a>
   </body>
</html>
```

**Comment by Christywl** [comment]
close until there is more information

**Comment by rohan-deshpande** [comment]
You can also try `nw.Shell.openExternal(href)`
