### ISSUE TITLE
 nwjs v0.14.4 app do not run on windows 7 32bit (86x)

### ISSUE THREAD

**Issue by terryBaz** [nwjs/nw.js#6507]
NWJS Version :  v0.14.4 
Operating System : windows 7 32bit (86x)

### Expected behavior

Run the app normally ( my app is running normally on all the windows platforms except the win7 32bits!), i picked v0.14.4 of nwjs cause i wanted to support the majority of the win platforms 

### Actual behavior

when i want to run the app on a -Operating System : windows 7 32bit (86x)- i get a window with this message : 

> "the version of this file is not compatible with the version o windows you're running, check your computer's system information to see whether you need an x86 (32-bit) or x64(64-bit) version o the program, and then contact the software publisher"

> sorry the image is in Arabic but i already gave you the message above 
![29028249_173783293258504_8849732185867943936_n](https://user-images.githubusercontent.com/29728203/37259729-5a4fcf9c-258a-11e8-8ee2-d5d36021d4c8.jpg)

**Comment by rogerwang** [comment]
Please don't use 0.14 for win7 and above. The 0.14 branch is only for XP.
