### ISSUE TITLE
Bug? iframe focus vs. NW window focus 

### ISSUE THREAD

**Issue by bambooCZ** [nwjs/nw.js#6508]
Hello

this is kind of opinion based, but I belive it is a bug. 

Situation:

I have a NWjs window which contains an iframe. When the iframe is clicked the top-window gets  NWjs's blur event. IMHO this is incorrect behavior.

I have made an app which demonstrates the difference. I think that the NWjs's focus events should behave like `chrome.windows....` events, not like DOM (`window.addEventListener("blur"/"focus", ...`) events.

According to your documentation: The blur event is emitted when **the window** (not the frame) looses focus. But when the iframe is activated, the window hasn't actually lost focus.

What do you think?

[iframe-trouble.zip](https://github.com/nwjs/nw.js/files/1803758/iframe-trouble.zip)

**Comment by Christywl** [comment]
I can reproduce this issue with nwjs-sdk-v0.29.0.

**Comment by panther7** [comment]
This is old issue... +1

**Comment by rogerwang** [comment]
Will see it soon and update in #4601

close as duplicate.
