### ISSUE TITLE
VirusTotal reports an issue for the win32 version of nwjs.exe

### ISSUE THREAD

**Issue by juliandescottes** [nwjs/nw.js#6509]
I am maintaining https://github.com/piskelapp/piskel and using nwjs to package an offline version of the webapp (great tool, thanks :) ). 

A user reported that the application was flagged as containing a virus by the website VirusTotal. I reproduce this with the nwjs.exe version available on the download page, so forwarding the question here.

Original issue is https://github.com/piskelapp/piskel/issues/789 

(note that I'm on an older version of nwjs, but since the issue reproduces with the latest version I think we can start looking into that)

NWJS Version : v0.29.0
Operating System : Windows 32bits

### Expected behavior

Should not show any virus/threat warning

### Actual behavior

Shows a virus/threat warning

### How to reproduce

- Download the 0.29.0 win32 Normal exe at https://nwjs.io/downloads/
- Upload it on VirusTotal.com (gives me this link -> https://www.virustotal.com/#/file/e9fd4a3d4e923420314b6ef5c7eb2347049f5cf8251efc89bb746e88b43c961b/detection )

**Comment by rogerwang** [comment]
This is false negative in the antivirus software vendor and should be reported to them.
