### ISSUE TITLE
"--enable-features=GamepadExtensions" Chromium Arg Doesn't Work With Certain User-Agents

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#6512]
### Information
NWJS Version : v0.29.0
Operating System : Windows 7 (SP1)

### Expected behavior

![js flag](https://user-images.githubusercontent.com/15656049/37350021-119a29c4-26d8-11e8-9e33-dd380adc1e0f.PNG)
Adding this to the manifest should enable the _experimental gamepad extensions API_ but it doesn't seem to work. Am I doing something wrong or is this js flag not supported yet?

### Actual behavior

![js flag chrome](https://user-images.githubusercontent.com/15656049/37350344-da54025e-26d8-11e8-9c0d-254494b56d73.PNG)
Adding the flag to the manifest should work just like manually enabling it in chrome://flags/.

### Example for reproduction

Download: [package file.zip](https://github.com/nwjs/nw.js/files/1807478/package.file.zip)

### How to reproduce

1. Run package file with NW.js running on M65 or newer
2. Wait until haptic feedback testing website is loaded
3. Test haptic feedback using a controller that supports it (e.g. XBox 360 gamepad)
     1. Connect gamepad and press button, it should be automatically selected on the top-left
     2. Fill in the required information (e.g. 0 | 1.0 | 1.0 | 1000)
     3. Click on "rumble" button
4. Notice it doesn't work as expected because js flag isn't properly enabled

**Comment by Christywl** [comment]
@TheRealDannyyy , I try it on Windows 10 with nwjs-sdk-v0.29.0. The result is 'haptic effect errored' after clicking 'rumble' button. Is this the same as yours?
![image](https://user-images.githubusercontent.com/20039821/37384953-a7405548-278c-11e8-934f-4df3822dad55.png)

**Comment by TheRealDannyyy** [comment]
@Christywl yes same for me, it's because the required js-flag isn't enabled. 
I'm not sure why it isn't since I did everything based on the NW.js documentation.

**Comment by rogerwang** [comment]
This should be used: `--enable-features=GamepadExtensions `

**Comment by TheRealDannyyy** [comment]
@rogerwang Thanks for the info, works now!

**Comment by TheRealDannyyy** [comment]
@rogerwang I've tried that command as a js-flag, chromium arg and also added it to a shortcut as a command-line argument and nothing worked. 

Does it work on your end or am I doing something wrong?

**Comment by rogerwang** [comment]
I didn't try it with your sample. I verified that the API is there with the switch.

**Comment by rogerwang** [comment]
btw, I put it in the command line. chromium-arg should work too. but it's not a 'js-flag'.

**Comment by TheRealDannyyy** [comment]
@rogerwang Still doesn't work for me, not sure what's wrong. (Tested in Nw.js v0.29.0)
This is what I'm using: [Package File With Arg.zip](https://github.com/nwjs/nw.js/files/1824153/Package.File.With.Arg.zip)

**Comment by armaldio** [comment]
@rogerwang Nothing work for me either
I've also tried with a vanilla NW.js app and a minimal package.json file
[nw.zip](https://github.com/nwjs/nw.js/files/1831616/nw.zip)

`npm run start` or `npm run startArg`

**Comment by TheRealDannyyy** [comment]
@rogerwang Did you have the time to look into whats going wrong yet? 
I would really appreciate if this gets fixed in the v0.30.0 stable release if possible.

**Comment by rogerwang** [comment]
Yeah, will try to fix it before 0.30.0 release.

**Comment by rogerwang** [comment]
btw, can it be tested without any gamepad device?

**Comment by TheRealDannyyy** [comment]
@rogerwang I guess the easiest way to test if it works without a gamepad would be doing the following:
1. Start nw.exe with the fix
2. Press F12 to open Dev-tools
3. Go to "console" tab and run: _window.open('chrome://flags/');_
4. Search for "Gamepad Extensions" flag and check if it's enabled

(You can also feel free to share a testing build so we can do the testing for you.)

**Comment by rogerwang** [comment]
@TheRealDannyyy It's `Default` here -- means the end user doesn't set the flag. It should be enabled by the command line.

**Comment by TheRealDannyyy** [comment]
@rogerwang It works using a shortcut and command-line but I would like to enable it using the manifest.
Could you add support for it in the manifest or fix it if it's not working as intended?

**Comment by rogerwang** [comment]
`--enable-features` is supposed to work in `chromium-args` in manifest. Does it work for you?

**Comment by TheRealDannyyy** [comment]
@rogerwang I tried _--enable-features=GamepadExtensions_ with both my and Armaldio's examples above and they didn't work. There must be an issue with NW.js not reading or activating it properly.

**Comment by rogerwang** [comment]
I tried with the following manifest and it should be enabled:
```
{
  "name": "nw-demo",
  "chromium-args": "--enable-features=GamepadExtensions",
  "main": "index.html"
}
```

**Comment by rogerwang** [comment]
I should add that since it's shown "Default" in "chrome://flags", meaning it's default according to the source code and the code enabling this is hit when I use that manifest. That's what I mean by "should be enabled". It should be better with a test case that don't require a physical device.

**Comment by TheRealDannyyy** [comment]
@rogerwang I found the issue, thanks for providing the example!

This line inside my manifest file is causing the "GamepadExtensions" chromium arg not to work:
`"user-agent": "Mozilla/5.0 (%osinfo) AppleWebKit/%webkit_ver (KHTML, like Gecko, Chrome, Safari)
`

Do you know why that's causing an error? All the other chromium args work fine, despite the user-agent.
(Below are both manifest files, one is working the other one is broken because of the user-agent.)
[Download Manifest Files.zip](https://github.com/nwjs/nw.js/files/1871680/Manifest.Files.zip)

**Comment by rogerwang** [comment]
Interesting. But your broken manifest works here.

**Comment by TheRealDannyyy** [comment]
@rogerwang I honestly have no clue why it would work on your end and not on mine. I'm pretty sure that the user agent is at fault on my end but I don't know what I could do about it. 
Are there any other ways to activate this inside my project? Maybe with Javascript or something like that?

[Here](https://github.com/nwjs/nw.js/files/1871950/Broken.Package.File.Project.zip) is the project with the "broken" package file, feel free to take a look and test it. I don't know what to do next, besides waiting another year for the Chromium Dev's to finally make this feature available to everyone.

Thanks a lot for your help so far, hoping that you'll maybe find a good workaround.

**Comment by rogerwang** [comment]
The problem is that I don't have the physical device to test it. Maybe the
user agent change triggered some issue in your application...

**Comment by TheRealDannyyy** [comment]
I think so too but I have no idea how I could fix this or find out whats going wrong. The console is empty and the flag is even marked as "enabled" so there must be some hidden error going on in the background
