### ISSUE TITLE
Crash on breakpoints when binary module is used

### ISSUE THREAD

**Issue by yonosteward** [nwjs/nw.js#6514]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.28 (SDK)
Operating System : macOS 10.13.3 

I have the following files:
* test1.js:
`function foo(fun) {console.log('test1');fun();}`

  I also compile test1.js to test1.bin using `nwjc test1.js test1.bin`

* test2.js
`function foo2() {console.log('test2');}`

* Index.html
In the index.htm, I load `test1.bin` and `test2.js`.

Steps to reproduce:
1. Run the `nwjs .` to load the index.html.
2. Set a breakpoint at the foo2() in test2.js.
3. Open Devtool and run `foo(foo2)` in the console.
4. The app will crash with the error message `Received signal 11 <unknown> 000000000000`.

**Comment by Christywl** [comment]
I can reproduce this _crash_ issue on Windows/Linux/Mac with nwjs-sdk-v0.29.0.

**Comment by rogerwang** [comment]
@Christywl could you please upload the full sample?

**Comment by Christywl** [comment]
The sample for Linux(`test1.bin` is compiled by nwjs-sdk-v0.29.0 nwjc): [6514.zip](https://github.com/nwjs/nw.js/files/1809397/6514.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
