### ISSUE TITLE
Pressing "Esc" does not cancel fullscreen

### ISSUE THREAD

**Issue by Yonezpt** [nwjs/nw.js#6523]
NWJS Version : 0.29.1 sdk
Operating System : Win7 x64

### Expected behavior

When a nwjs app/window is in fullscreen pressing Escape key should exit from fullscreen

### Actual behavior

Pressing escape while in fullscreen does nothing

### How to reproduce

sample app in nwjs root folder

`package.json`
````json
{
    "name" : "sample",
    "main" : "main.html"
}
````

`main.html`
````html
<!DOCTYPE html>
<html>
<head>
    <title>sample</title>
</head>
<body>
    <script type="text/javascript">
        var isFullscreened = false;
        function enterFullscreen(element) {
            if (isFullscreened) {
                isFullscreened = false;
                document.webkitCancelFullScreen();
            } else {
                isFullscreened = true;
                element.webkitRequestFullScreen();
            }
        }
    </script>
    <div onclick="enterFullscreen(this); return false;">Click here to enter/exit fullscreen</div>
</body>
</html>
````

Click the text
App enters full screen
Press `Esc` key
App does not exit full screen

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.29.1. Pressing 'Esc' can't exit the Full screen.

_It works fine with Chrome M65._

**Comment by rogerwang** [comment]
This shouldn't be a default behavior. Apps should bind the key and process on their own.

**Comment by rogerwang** [comment]
See #4129

**Comment by Yonezpt** [comment]
@rogerwang I understand, but it is a huge problem if the key is already registered by another application outside the nwjs currently in use. This problem is also present for media playback shortcut keys which fail to register completely if the user has, for example, the MPC player opened.

http://docs.nwjs.io/en/latest/References/Shortcut/

That means that if anything has the Esc key bound to an action outside the NWJS app and the user enters fullscreen in the NWJS app, he will never be able to exit fullscreen because the hotkey failed to register:

> If registered successfully, it works even if your app does not have focus.


Furthermore the hotkey registration is global, that means that if the user presses the Esc key while the app is not in focus then the app will exit fullscreen without that being the user intention.

> it works even if your app does not have focus.

Is this really how it should be handled? For global hotkeys such as media playback keys it makes sense that they behave this way, but the Esc to exit fullscreen should not have this kind of behavior at all since it is dependent on the fullscreen app that is in focus, not a global hotkey that can quit fullscreen if the user presses Esc while on a completely different application or even a different monitor.

I request that this specific case be reconsidered and implement the Esc to exit fullscreen behavior the right way since the shortcut method is prone to failure leaving users absolutely stuck on a fullscreen app forcing them to terminate it by other means if they want to exit fullscreen.

**Comment by Yonezpt** [comment]
In hindsight, this hole issue stems another one which I believe it could be resolved by adding an extra option to the Shortcut api that allows the developer to state whether or not he wants the shortcut to be global (works even if the app is not in focus) or local (only works for the app instance it is registered and when it is in focus).

I suggest this only because even if we were to check for app focus before engaging the action bound to the shortcut, we have absolutely no way to register the same key for multiple NWJS apps, but if we had the ability to state that an X shortcut is local only (for example Esc) then we can have multiple NWJS apps bound to the same shortcut without failure and these only work when each specific app is in focus.

I believe this solution would be perfect and the default value for the option (let's call it for example `global: true` ) would be true (meaning that if the option is not set then make shortcut global) so that previous apps won't break or be forced to add that field to already registered global shortcuts.

**Comment by Yonezpt** [comment]
I just realized that my suggestion is already possible by listening to keypresses from the parent window, those will be triggered only when the window is in focus, disregard my suggestion, I was just mixed up with the global shortcut aspect and I was not able to see the obvious solution, sorry for the spam.
