### ISSUE TITLE
Crashed after reloading app when devtool is open

### ISSUE THREAD

**Issue by yonosteward** [nwjs/nw.js#6525]
NWJS Version : v0.28
Operating System : macOS 10.13.3 

I got crashes after using "reload app" when devTool is open. The error message is:

[69823:775:0317/194957.994217:FATAL:V8ObjectConstructor.cpp(97)] Check failed: get_prototype_value.
0   nwjs Framework                      0x000000010fa89ebc v8_inspector::V8StackTraceId::IsInvalid() const + 5612684
1   nwjs Framework                      0x000000010faa2132 v8_inspector::V8StackTraceId::IsInvalid() const + 5711618
2   nwjs Framework                      0x00000001123d49c2 v8_inspector::V8StackTraceId::IsInvalid() const + 48910226
3   nwjs Framework                      0x00000001123d5001 v8_inspector::V8StackTraceId::IsInvalid() const + 48911825
4   nwjs Framework                      0x00000001123d4fd6 v8_inspector::V8StackTraceId::IsInvalid() const + 48911782
5   nwjs Framework                      0x000000011216154a v8_inspector::V8StackTraceId::IsInvalid() const + 46340890
6   nwjs Framework                      0x000000011213cdba v8_inspector::V8StackTraceId::IsInvalid() const + 46191498
7   nwjs Framework                      0x000000011213bcf4 v8_inspector::V8StackTraceId::IsInvalid() const + 46187204
8   nwjs Framework                      0x0000000112163195 v8_inspector::V8StackTraceId::IsInvalid() const + 46348133
9   nwjs Framework                      0x000000011292a43a v8_inspector::V8StackTraceId::IsInvalid() const + 54503946
10  nwjs Framework                      0x0000000112151d71 v8_inspector::V8StackTraceId::IsInvalid() const + 46277441
11  nwjs Framework                      0x00000001121427bd v8_inspector::V8StackTraceId::IsInvalid() const + 46214541
12  nwjs Framework                      0x00000001121429d7 v8_inspector::V8StackTraceId::IsInvalid() const + 46215079
13  nwjs Framework                      0x00000001127f0ec6 v8_inspector::V8StackTraceId::IsInvalid() const + 53220502
14  nwjs Framework                      0x00000001127f0c01 v8_inspector::V8StackTraceId::IsInvalid() const + 53219793
15  nwjs Framework                      0x00000001127efcd7 v8_inspector::V8StackTraceId::IsInvalid() const + 53215911
16  nwjs Framework                      0x0000000112a1811b v8_inspector::V8StackTraceId::IsInvalid() const + 55477995
17  nwjs Framework                      0x0000000112a17f62 v8_inspector::V8StackTraceId::IsInvalid() const + 55477554
18  nwjs Framework                      0x0000000112a0a0b2 v8_inspector::V8StackTraceId::IsInvalid() const + 55420546
19  nwjs Framework                      0x0000000112a09b2a v8_inspector::V8StackTraceId::IsInvalid() const + 55419130
20  nwjs Framework                      0x0000000112a0cc3e v8_inspector::V8StackTraceId::IsInvalid() const + 55431694
21  nwjs Framework                      0x000000011276e52f v8_inspector::V8StackTraceId::IsInvalid() const + 52685567
22  nwjs Framework                      0x000000011293fb44 v8_inspector::V8StackTraceId::IsInvalid() const + 54591764
23  nwjs Framework                      0x0000000112ba0b8f v8_inspector::V8StackTraceId::IsInvalid() const + 57086303
24  nwjs Framework                      0x0000000112b9f63d v8_inspector::V8StackTraceId::IsInvalid() const + 57080845
25  nwjs Framework                      0x0000000112b9f512 v8_inspector::V8StackTraceId::IsInvalid() const + 57080546
26  nwjs Framework                      0x0000000112b9f49e v8_inspector::V8StackTraceId::IsInvalid() const + 57080430
27  nwjs Framework                      0x00000001128e9e16 v8_inspector::V8StackTraceId::IsInvalid() const + 54240230
28  nwjs Framework                      0x000000011290e1f7 v8_inspector::V8StackTraceId::IsInvalid() const + 54388679
29  nwjs Framework                      0x00000001136d2ce1 v8_inspector::V8StackTraceId::IsInvalid() const + 68825777
30  nwjs Framework                      0x0000000110876cd9 v8_inspector::V8StackTraceId::IsInvalid() const + 20214441
31  nwjs Framework                      0x0000000110875f5a v8_inspector::V8StackTraceId::IsInvalid() const + 20210986
32  nwjs Framework                      0x000000010fa8a6ac v8_inspector::V8StackTraceId::IsInvalid() const + 5614716
33  nwjs Framework                      0x000000010f5ccb62 v8_inspector::V8StackTraceId::IsInvalid() const + 643378
34  nwjs Framework                      0x000000010f5cc222 v8_inspector::V8StackTraceId::IsInvalid() const + 641010
35  nwjs Framework                      0x000000010fa8a6ac v8_inspector::V8StackTraceId::IsInvalid() const + 5614716
36  nwjs Framework                      0x000000010f5cfce5 v8_inspector::V8StackTraceId::IsInvalid() const + 656053
37  nwjs Framework                      0x000000010fa8a6ac v8_inspector::V8StackTraceId::IsInvalid() const + 5614716
38  nwjs Framework                      0x000000010faafa24 v8_inspector::V8StackTraceId::IsInvalid() const + 5767156
39  nwjs Framework                      0x000000010faaff39 v8_inspector::V8StackTraceId::IsInvalid() const + 5768457
40  nwjs Framework                      0x00000001135b1d6a v8_inspector::V8StackTraceId::IsInvalid() const + 67642170
41  nwjs Framework                      0x000000010faa381a v8_inspector::V8StackTraceId::IsInvalid() const + 5717482
42  nwjs Framework                      0x000000010fab16bf v8_inspector::V8StackTraceId::IsInvalid() const + 5774479
43  CoreFoundation                      0x00007fff3b69c721 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
44  CoreFoundation                      0x00007fff3b7560ac __CFRunLoopDoSource0 + 108
45  CoreFoundation                      0x00007fff3b67f260 __CFRunLoopDoSources0 + 208
46  CoreFoundation                      0x00007fff3b67e6dd __CFRunLoopRun + 1293
47  CoreFoundation                      0x00007fff3b67df43 CFRunLoopRunSpecific + 483
48  Foundation                          0x00007fff3d74fc16 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
49  nwjs Framework                      0x00000001135b22be v8_inspector::V8StackTraceId::IsInvalid() const + 67643534
50  nwjs Framework                      0x000000010fab11de v8_inspector::V8StackTraceId::IsInvalid() const + 5773230
51  nwjs Framework                      0x000000010faaf6d4 v8_inspector::V8StackTraceId::IsInvalid() const + 5766308
52  nwjs Framework                      0x000000010fad4d04 v8_inspector::V8StackTraceId::IsInvalid() const + 5919444
53  nwjs Framework                      0x00000001135dec31 v8_inspector::V8StackTraceId::IsInvalid() const + 67826177
54  nwjs Framework                      0x00000001128ea624 v8_inspector::V8StackTraceId::IsInvalid() const + 54242292
55  nwjs Framework                      0x000000010f511d7c v8_inspector::DumpAsyncTaskStacksStateForTest(v8_inspector::V8Inspector*) + 104252
56  nwjs Framework                      0x000000010f024f56 v8::internal::RuntimeCallStats::Reset() + 81958
57  nwjs Framework                      0x000000010f0249ee v8::internal::RuntimeCallStats::Reset() + 80574
58  nwjs Framework                      0x000000010f30a6b6 v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const + 153126
59  ???                                 0x00001f9fad286b1d 0x0 + 34770665368349
60  ???                                 0x00001f9fad455605 0x0 + 34770667263493
61  ???                                 0x00001f9fad292ee8 0x0 + 34770665418472

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac 10.13.3 with nwjs-sdk-v0.28.0/v0.29.1: 
- Start a simple test with nwjs
- open the devtools
- Right-click 'Reload App'

_Result:_ The app window and devtools window don't crash.

Could you please upload your sample?

**Comment by yonosteward** [comment]
I cannot reproduce it here today. Could you guess the problem from the error messages?

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by iduchy** [comment]
nwjs-sdk-v0.37.4-win-x64 crashed after reloading app when **background page devtool** is opened.
debug.txt: 
> [0424/061239.136:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)
