### ISSUE TITLE
WebSocket not working on spotify.com

### ISSUE THREAD

**Issue by Virius** [nwjs/nw.js#6527]
NWJS Version : v0.29.1
Operating System : Win10 x64

### Expected behavior

new WebSocket(address) work ok

### Actual behavior

new WebSocket(address) produce error "WebSocket connection to 'wss://gew-dealer.spotify.com/?access_token=...' failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED"

### How to reproduce

- open nw.js dev console
- execute window.location.href = 'https://open.spotify.com'
- log in to site

In console logs you will see net::ERR_NOT_IMPLEMENTED errors

Another way:

- open nw.js dev console
- execute window.location.href = 'https://open.spotify.com'
- execute new WebSocket('wss://gew-dealer.spotify.com');

will generate same error.

In Chrome all works fine. And if I start Fiddler on my computer then in nw.js all works fine too. Can anybody explain why?

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.29.1.

**Comment by rogerwang** [comment]
This looks like https://bugs.chromium.org/p/chromium/issues/detail?id=684681 .
Will check why it works fine in Chrome. Maybe it connects to a different server or using different protocol.

**Comment by rogerwang** [comment]
Ref: https://github.com/nghttp2/nghttp2/issues/793

**Comment by rogerwang** [comment]
I can reproduce this with the latest Chromium (not chrome): https://download-chromium.appspot.com/dl/Linux_x64

So should be an upstream issue.

**Comment by rogerwang** [comment]
@Virius please report your findings to upstream. Thanks. https://crbug.com/new

**Comment by Virius** [comment]
@rogerwang Created. https://bugs.chromium.org/p/chromium/issues/detail?id=823643

**Comment by rogerwang** [comment]
I just followed up in the upstream issue. btw, you should use the link https://download-chromium.appspot.com/dl/Linux_x64 which is official binary.

**Comment by Virius** [comment]
Hi. Can you explain the last comment in chromium issue discussion (https://bugs.chromium.org/p/chromium/issues/detail?id=823643#c21). I do not understand, the problem is solved? In which chromium release? When this changes will be in the nw.js?

**Comment by rogerwang** [comment]
It's in chrome 67 / nwjs 0.31. Will look to backport it to 0.30.
