### ISSUE TITLE
menu.createMacBuiltin() doesn't work properly

### ISSUE THREAD

**Issue by yonosteward** [nwjs/nw.js#6528]
NWJS Version : v0.28
Operating System : macOS 10.13.3

If we use `menu.createMacBuiltin('Hello world');` to create a menu, then the menu name will be reset to `nwjs`.

<img width="300" alt="screen shot 2018-03-19 at 2 14 22 pm" src="https://user-images.githubusercontent.com/36044803/37614051-01fc55bc-2b80-11e8-9be0-5fd0a59839b1.png">

Thus, the bugs include:
1: I expect that the menu name should be the value of `createMacBuiltin`, not `nwjs`.
2: The ways to control the name on the menu may have conflicts. Since we have app name in at least three different places, such as plist file, package.json and `createMacBuiltin`.

**Comment by Christywl** [comment]
@rogerwang , I see the doc http://docs.nwjs.io/en/latest/For%20Users/Advanced/Customize%20Menubar/#mac-os-x, the result(menu name) in this issue is normal behavior? Or a bug?
