### ISSUE TITLE
Disappearing console.warn messages

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6537]
NWJS Version : 0.29.2 SDK
Operating System : Affects both Windows x64 and Linux x64

I believe that this is a regression (was fine in 0.28+)

### Expected behavior
We should see the message that was sent to the console.

### Actual behavior
The warning content seems to be "gone".

### How to reproduce
Prerequisites: Start a simple project which will also include a compiled javascript binary file.

1. Go to inspector -> console
2. Type in console.warn('test');
3. Close the inspector and wait 10-30 seconds
4. Open inspector and check out the console
5. Instead of a warning that we typed in previously there is just a yellow line

![yellow line](https://user-images.githubusercontent.com/2289413/37870767-cf1b9312-2fdd-11e8-9661-dc842738ab45.png)

**Comment by cTn-dev** [comment]
@rogerwang Could you have a look please?

**Comment by Christywl** [comment]
I just start nw.exe v0.29.2, type console.warn('test') in devtools, close and open it again, this issue happens.

**Comment by cTn-dev** [comment]
You are right, this also happens during standard usage.
It only manifested on my end due to using console.warn inside a compiled file, i guess its hitting the same bug when its used inside directly in console.

**Comment by cTn-dev** [comment]
This has been fixed in 0.30+ builds so i am closing the ticket.
