### ISSUE TITLE
Can I change the show name when right click task bar?

### ISSUE THREAD

**Issue by weiluenju** [nwjs/nw.js#6543]
When I right click the task bar of my program, I expect see the popup menu show the productName, but it seem show the name in package.json. How can I modify it?

<img src="https://i.imgur.com/cr3571u.png"/>

NWJS Version : 0.29.3
Operating System : Windows10

### Expected behavior

Same with productName in package.json

### Actual behavior

Show as name in package.json

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
