### ISSUE TITLE
Mp3 Not working in 0.29.3

### ISSUE THREAD

**Issue by Nemra1** [nwjs/nw.js#6545]
im try  to load my chat room in main everything is work but no sound ..is working in chrome browser but not working into app when load... what i miss?

{
  "name": "n1-appv2",
  "version": "1.2",
  "description": "",
  "main": "http://sitename.ml/chat/index.php",
  "chromium-args": "--ignore-certificate-errors --allow-hidden-media-playback --disable-devtools --disable-password-generation --disable-web-securit --ppapi-flash-path=PepperFlash/21.0.0.216/pepflashplayer.dll ppapi-flash-version=21.0.0.216 --mixed-context --allow-file-access-from-files --unsafely-treat-insecure-origin-as-secure='http://sitename.ml/' --allow-running-insecure-content",
  "node-remote": "http://*.sitename.ml/*",
  "page-cache": true,
  "keywords": [
    "chat",
    "Chat sitename"
  ],
  "window": {
    "title": "sitename",
    "width": 1100,
    "height": 650,
    "icon": "icon.png",
    "toolbar": true,
    "position": "center",
    "resizable": true,
    "frame": true
  },
  "devDependencies": {
    "nw-builder": "^3.5.1"
  }
}

**Comment by Christywl** [comment]
@Nemra1 , your url in the package.json doesn't work for me, and I try a simple test with video tag, mp3 works fine with nwjs-sdk-v0.29.3.

**Comment by Nemra1** [comment]
Its example not really link... And the really link http://xops.ml/client/core.php

**Comment by Christywl** [comment]
Could you please provide an English website?  And does mp3 in `<video>` tag work for you?

**Comment by Nemra1** [comment]
mr @Christywl im try old sdk since v0.20.3  to 0.16.1 the results ( Flash player is working good and all sounds in formats ogg-mp3-wav) working fine...but since v0.21.6 +newer mp3 not working and just flash player...
