### ISSUE TITLE
no security after build ! 0.29.3 SDK

### ISSUE THREAD

**Issue by Nemra1** [nwjs/nw.js#6547]
im used 0.29.3 SDK
after build my package for example
ican extract app.exe and get all my data...why that?
![2018-04-02_165243](https://user-images.githubusercontent.com/22897987/38222294-1a529896-36e4-11e8-8790-44d5b7ff4001.png)

**Comment by Christywl** [comment]
I try to package the app to `app.exe` via `copy /b nw.exe+package.nw app.exe`. The` app.exe` could be extracted. 
@rogerwang , should nw protect the data for the `app.exe` file?

**Comment by rogerwang** [comment]
The packaging process is not for protection. To protect your code or data, consider using this feature: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/
