### ISSUE TITLE
stacktrace showing incorrect line number when using coffeescript/typescript

### ISSUE THREAD

**Issue by ladace** [nwjs/nw.js#6548]
EDIT

Hey if I write some code like this:

```
require('coffee-script/register')
require('./app.coffee')
```
`app.coffee` generates a source map, but it's in the background page.
when it throws any exceptions, they will be on the front page -- and because source maps in background page won't work in another page, I get an incorrect line number in the stacktrace when exceptions are thrown. It's a bit hard to track down the bugs then.

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by ladace** [comment]
I wonder if this is a missing feature or bug.

**Comment by Christywl** [comment]
Could you please provide a full sample to reproduce this?

**Comment by rogerwang** [comment]
close until more information is available.
