### ISSUE TITLE
The process "nwjs" is not terminated after the application is closed

### ISSUE THREAD

**Issue by Julian-maljuk** [nwjs/nw.js#6549]
NWJS Version : 0.30.0-beta1
Operating System : Windows 10

### Expected behavior

After closing the application, all processes associated with the application are closed.

### Actual behavior

The application is closed, but process "nwjs" does not finish and load the processor by 30%.

### How to reproduce

1. Open the application
2. Close the application
3. Check running processes in Task Manager

**Comment by Christywl** [comment]
I try a simple test and can't reproduce this issue on Windows with nwjs-sdk-v0.30.0-beta1. Could you please upload your sample to reproduce this?

**Comment by Julian-maljuk** [comment]
Adding this code to index.html partially solved the problem, but sometimes the process still remains active.

`<script>

    var win = window['nwgui'].Window.get();
    win.on('closed', function () {
        win = null;
    });
    win.on('close', function () {
        this.hide();
        if (win != null)
            win.close(true);
        this.close(true);
    });

  </script>`

**Comment by Julian-maljuk** [comment]
The problem was that I was building a project for the "browser" (ionic cordova build browser) platform. If do not use cordova plugins then there is no such problem.
