### ISSUE TITLE
setAlwaysOnTop doesn't work when application isn't focused (win32)

### ISSUE THREAD

**Issue by mmorrisontx** [nwjs/nw.js#655]
I have been fighting tooth and nail with this issue for over a month, at first thinking it was an issue with UAC permissions, then thinking that it was an issue in my code, then eventually discovering it occurs in all node-webkit apps.

Here's the problem:
When a node-webkit application isn't active (another application is currently "selected" and focused above it), calling setAlwaysOnTop does nothing. The application doesn't come to the front, and doesn't even appear above over node-webkit windows.

I've searched through the chromium code for hours, but am unable to find the cause. Perhaps a function call somewhere is resetting the window flags immediately after it gets HWND_TOPMOST?

I have reproduced the issue on both Windows XP and 8.

**Comment by jaruba** [comment]
I think I'm having a similar issue with ```win.setAlwaysOnTop()``` in ```nw.js v0.12.0-alpha3```.

If I use ```win.setAlwaysOnTop(true)``` in the console it works, but if I call it from JS it does nothing. It only works if I use ```setTimeout(function() { win.setAlwaysOnTop(true) },3000);``` and change the window to anything else fast.

Does it need user interaction? I'm using it from a player plugin that sends an event back, so the page will not get any user interaction.
