### ISSUE TITLE
Working with node modules [question]

### ISSUE THREAD

**Issue by sadikyalcin** [nwjs/nw.js#6556]
NWJS Version :0.29.3 [all versions really]
Operating System : OSX El Capitan

So I develop my app at `~/Sites/app/desktop/`. All my node modules are installed at `~/Sites/app/node_modules`. I just spent an hour trying to figure out why my app would not open the window when I bundled it. Even running it from terminal `~/Sites/nwjsdev/nwjs.app/Contents/MacOS/nwjs .` while `app.nw` was in there, no output was given. In the end, I opened dev tools via script and `Uncaught Error: Cannot find module 'rmdir'`. I know if I put the `node_modules` folder in `nwjs.app/Contents/Resources/`, it will work. But not really sure if this is the way. So my question really is, if such things happen how can I found out what the issue is (any crash logs) and the correct way of using node modules.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
