### ISSUE TITLE
can not load the flash plugins

### ISSUE THREAD

**Issue by lllulianjie** [nwjs/nw.js#6560]
nwjsewks  version: v0.25.4
os: windows 10
In my project, I had put the manifest.json(version 29.0.0.113 same as my local flash's version) and pepflashplayer.dll into the ‘PepperFlash’ subdirectory under NW.js binary. And it's work on my machine. But when the application is installed on someone else's machine which flash version is lower than  29.0.0.113, it show 'could not load the plugins'.

**Comment by Christywl** [comment]
@rogerwang , Is flash loading related to plugin version for nwjs?

**Comment by lllulianjie** [comment]
Hi, @rogerwang, could you please help to check? Thanks.
