### ISSUE TITLE
Angle Platform initialization failed

### ISSUE THREAD

**Issue by dsomesh** [nwjs/nw.js#6562]
NWJS Version :v0.25.4-win-x64
Operating System : Windows 10  64 bit

### Expected behavior

We are launching nw app with the following parameter-
"--enable-logging --v=1 --trace-startup --trace-startup-file=C:\\CustomerLive\\logs\\zapp\\trace.log"

On launching it generally, we get a command prompt with Elevation Type 3 written over it.

### Actual behavior

In one of the windows 10 device upon launching the app we see the following error in the command prompt.

"Angle Platform initialization failed"

Though we the app runs fine, it would be good to know why this exception is coming and if it has any impacts.

Screenshot:-

![capture](https://user-images.githubusercontent.com/19370408/38548136-a2a95816-3cce-11e8-9382-f9cf421856a3.PNG)

### How to reproduce

We do not have the exact steps to reproduce as it is happening in only one of our devices.

**Comment by rogerwang** [comment]
Thanks for reporting. Does the error message appear only when you use those arguments?

**Comment by dsomesh** [comment]
Yes.Upon only launching the app without any parameters we do not see this.Though this is not causing us any functional issues as of now, we would like to know if there can be any side effects of this.

**Comment by rogerwang** [comment]
Did you see any error msgs with `eglInitialize`?

**Comment by dsomesh** [comment]
I only see the mentioned error in console.Attaching the chromium debug logs for more info.
[trace.log](https://github.com/nwjs/nw.js/files/1902816/trace.log)
