### ISSUE TITLE
Mediarecorder in H264 - Chrome vs nw.js

### ISSUE THREAD

**Issue by kkm** [nwjs/nw.js#6569]
It works in Chrome well but in nw.js from 24 Version no longer running.
I set `mimeType: 'video/webm;codecs=H264'` and it always shows vp8 in nwjs after recording.
Look at screenshot bottom.

![](https://capturei.tikatoy.com/r/MGg7itw7YoMG.png)

Full source code:
https://gist.github.com/kkm/60ce3479ad35d923bbff6e4e8f5ae25c

**Comment by kkm** [comment]
Webrtc does not work in h264 either.
Downgrade to 28.3 and works well.

**Comment by Christywl** [comment]
I can reproduce this issue with nwjs-sdk-v0.30.0. The recorded video shows vp8.

_The video shows h264 with nwjs v0.28.3._

**Comment by kkm** [comment]
What is P2? Thanks

**Comment by kkm** [comment]
What's up and planning in next time/update?

**Comment by rogerwang** [comment]
@kkm will look to fix it soon.

**Comment by rogerwang** [comment]
How to use the sample? I put it on a https site, open it in Chrome browser and nothing happens after I click any buttons.

**Comment by rogerwang** [comment]
@Christywl do you know how to use the sample? I can't reproduce it here.

**Comment by Christywl** [comment]
@rogerwang , seem this issue doesn't exist on nwjs-sdk-v0.31.2, it shows h264.

Run the sample with nw.exe directly(I'm not use https), record a video, play it in chrome and check the type with `chrome://media-internals/`.

nwjs-sdk-v0.30.5: 

video_codec_name | vp8
-- | --

nwjs-sdk-v0.31.2:

video_codec_name | h264
-- | --

**Comment by rogerwang** [comment]
@Christywl do you mean it can't be reproduced in latest version and should be closed then?

**Comment by Christywl** [comment]
Yes, it can't be reproduced in my side. 
@kkm , please try the latest nwjs build.

**Comment by kkm** [comment]
Yeah I confirm, that works well after 31.2 Version.

Thanks!
