### ISSUE TITLE
Provide current TypeScript definitions for NWjs

### ISSUE THREAD

**Issue by darkhog** [nwjs/nw.js#6577]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.30
Operating System : n/a

### Expected behavior

<!- What do you think should happen? -> Current TypeScript definitions are available

### Actual behavior

<!- What actually happens? -> The newest available are for 0.13. Ouch.

### How to reproduce

Do I really have to spell it out?

**Comment by rogerwang** [comment]
> The newest available are for 0.13. Ouch

Where did you see this?

**Comment by darkhog** [comment]
DefinitelyTyped  
                
              
               
                 
                  Dnia 24 kwietnia 2018 02:15 Roger Wang &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   
 The newest available are for 0.13. Ouch 
 
 Where did you see this?

**Comment by campbellbrendene** [comment]
Some typings would be nice!!

**Comment by sebamatusr** [comment]
I fully support this request. Typings would be super useful.

**Comment by dafik** [comment]
here is working package https://www.npmjs.com/package/nwjs-types

**Comment by Heartnett** [comment]
> here is working package https://www.npmjs.com/package/nwjs-types

Nope, I don't trust anything with a status of "**Very much in-progress!**" Also its outdated (2 years).

![image](https://user-images.githubusercontent.com/11403655/120099632-e2129800-c13c-11eb-8716-2f388e5d57d0.png)

**Comment by cdog** [comment]
See: https://www.npmjs.com/package/@types/nw.js

**Comment by ayushmanchhabra** [comment]
Not too happy with the current type definitions. JSDoc comments can be added to the codebase to autogenerate type defs.

**Comment by liesauer** [comment]
`@types/nw.gui` `@types/nw.js` `nwjs-types`

they are all outdated.

**Comment by ayushmanchhabra** [comment]
I have been added as maintainer for @types/nw.js. The review process will now be quicker.

**Comment by ayushmanchhabra** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70077

**Comment by ayushmanchhabra** [comment]
Types are being worked on in @types/nw.js package in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/nw.js. Please open issues/PRs there.
