### ISSUE TITLE
Tray menu cannot be navigated with keyboard under Windows

### ISSUE THREAD

**Issue by jakedouglas** [nwjs/nw.js#6580]
NWJS Version : v0.30.0
Operating System : Windows 10

Works fine on macOS and Linux. Used to work at least in v0.13.4. Not sure precisely in which version it stopped working.

### Expected behavior

Arrow keys should be able to navigate the tray menu.

### Actual behavior

Pressing arrow keys does nothing.

### How to reproduce

Start any nwjs application that provides a tray menu. Open the tray menu and press arrow keys on the keyboard.

**Comment by Christywl** [comment]
I can reproduce this issue on Windows with nwjs-sdk-v0.30.0. It does work fine on Linux.

**Comment by rogerwang** [comment]
@Christywl could you please upload your sample?

**Comment by Christywl** [comment]
@rogerwang , please download the sample:
[6580.zip](https://github.com/nwjs/nw.js/files/1949776/6580.zip)

**Comment by rogerwang** [comment]
I found this is a bug in Chrome browser: https://bugs.chromium.org/p/chromium/issues/detail?id=837520
Upstream should fix it. Please star that issue for priority.

**Comment by rogerwang** [comment]
This is fixed in `nw32` branch and will be available with the next build for 0.32.0
