### ISSUE TITLE
nwjs seems to leak memory via tray menu items

### ISSUE THREAD

**Issue by jakedouglas** [nwjs/nw.js#6583]
NWJS Version : v0.30.1
Operating System : macOS 10.13.4. Other platforms might be affected as well.

The documentation is not explicit about how a tray/menu should be refreshed/manipulated after creation. However, I have tried the following approaches that all seem to result in increasing memory usage:

1. Simply reassigning `tray.menu` a new Menu object that contains new MenuItem objects
2. Using `menu.removeAt()` to remove all menu items before adding new ones
3. Using `tray.remove()`, creating a new Tray object, then assigning a new Menu object
4. Approaches 2 and 3 combined

### Expected behavior

Memory usage should not grow indefinitely as the tray menu is refreshed.

### Actual behavior

Memory usage continues to grow as the tray menu is refreshed.

### How to reproduce

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hi</title>
  </head>
  <body style="width: 100%; height: 100%;">
    <script>
      const tray = new nw.Tray({ title: 'Tray' });

      setInterval(() => {
        const menu = new nw.Menu();

        menu.append(new nw.MenuItem({ type: 'normal', label: 'A' }));
        menu.append(new nw.MenuItem({ type: 'normal', label: 'B' }));
        menu.append(new nw.MenuItem({ type: 'normal', label: 'C' }));

        tray.menu = menu;
      }, 10)
    </script>
  </body>
</html>
```

**Comment by Christywl** [comment]
Try the sample on Linux/Windows/Mac with nwjs-sdk-v0.30.1, the issue is reproduced.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by jakedouglas** [comment]
Thank you! Will this be in a release soon?

**Comment by rogerwang** [comment]
Yes. Probably in a week.

**Comment by rogerwang** [comment]
btw, the build is here and it's in release quality:
https://dl.nwjs.io/live-build/nw30/05-03-2018/0f1a574-2c58808-684c6a5-4ae2873/v0.30.3/

**Comment by jakedouglas** [comment]
Thanks!

**Comment by rogerwang** [comment]
Is the nightly build working for you?

**Comment by jakedouglas** [comment]
Sorry, I should have checked earlier. It's still leaking. Collections seem to be happening resulting in temporary drops, but the baseline continues to increase. Note that the example seems to produce the leak more quickly when the nwjs window is focused.

Test case after ~1 minute:

![image](https://user-images.githubusercontent.com/18612/39767746-50d946b6-529c-11e8-918b-def30b9c2ba7.png)

Test case after ~10 minutes:

![image](https://user-images.githubusercontent.com/18612/39768235-8af26570-529d-11e8-8282-4de62687b60e.png)

**Comment by rogerwang** [comment]
Thanks. What about Windows and Linux there?

**Comment by jakedouglas** [comment]
It seems to still be leaking on Windows and Linux as well.

**Comment by rogerwang** [comment]
It works for me. Here is the screenshot after running for 10mins, with the nightly build posted above and your example. @Christywl could you please verify as well?
![screen shot 2018-05-09 at 9 15 41 am](https://user-images.githubusercontent.com/165401/39790610-a604658a-5369-11e8-93e6-8267570aff9f.png)

**Comment by jakedouglas** [comment]
My mistake, I was accidentally using option 4 from the issue description to produce the screenshot and Windows/Linux results above.

However, using only the provided example, I still seem to have a leak, albeit slower. This was taken after ~25 minutes:

![image](https://user-images.githubusercontent.com/18612/39793708-7a18f9f4-52fb-11e8-8139-46cc647b9199.png)

What else can I provide?

**Comment by Christywl** [comment]
I check on Mac with the nightly build v0.30.3:
the window isn't focused(~30 minutes):
<img width="838" alt="screen shot 2018-05-09 at 13 29 15" src="https://user-images.githubusercontent.com/20039821/39797978-37a29eea-5391-11e8-9299-5374e2f1a6c3.png">
the window is focused(~30 minutes):
<img width="1200" alt="screen shot 2018-05-09 at 13 55 47" src="https://user-images.githubusercontent.com/20039821/39797999-45edc65a-5391-11e8-8b97-77ba91bdaa81.png">

**Comment by rogerwang** [comment]
@Christywl thanks. Does it keeps growing?

The specific number doesn't matter because it's decided by GC strategy of v8, which in turn depends on system configuration...

**Comment by Christywl** [comment]
yes, it keeps growing, but is slower than 0.30.1.

**Comment by rogerwang** [comment]
Does it have upper limit? or it just fills up system memory? And what about the release version on this.

**Comment by jakedouglas** [comment]
Do you mean that v8 might decide to continue using more memory until it's close to running out, and only GC then? The example has gone over 300mb on my system now after an hour or two. When should it stop growing in relation to available memory?

If this is normal GC behavior and not a leak, is there a way for us to specify the v8 GC settings to collect earlier? The current behavior is likely to give users the impression that our application is a memory hog.

![image](https://user-images.githubusercontent.com/18612/39820418-9d4cd008-535a-11e8-96e8-4cc2febaeeea.png)

**Comment by rogerwang** [comment]
The GC strategy is a complex topic. It's hard to predict when GC will happen. If you'd like to control it, pass `--js-flags=--expose_gc` and call `gc()` when you need it.

There are various v8 flags to tune GC, see https://github.com/nwjs/v8/blob/nw30/src/flag-definitions.h#L625
See also https://github.com/nwjs/v8/blob/nw30/src/api.cc#L933

0.30.3 will be released today with the fix for Menu and MenuItem leak. We'll continue to find if there are any other leaks with your sample. You can use the heap profiling tool in devtools to see which JS objects are live in the heap after running it for several minutes. Please share your result here.

**Comment by rogerwang** [comment]
btw, you might want to try this for testing purpose: `--js-flags="--optimize_for_size --max_old_space_size=460 --gc_interval=100"`

**Comment by jakedouglas** [comment]
By the end of yesterday the example had grown to over 1GB. Today, on the same system, I can no longer reproduce that growth and my results are more like yours. I'm thoroughly confused as to what could have changed.

I can still reproduce the growth on another system (Windows). I am adding `--js-flags=--expose_gc`, and scheduling a call to `gc()` every 5 seconds. It does not appear to keep the process from growing indefinitely. Here's some information from that system:

![image](https://user-images.githubusercontent.com/18612/39890221-fec00194-544e-11e8-83ff-c70b5fda4e38.png)

![image](https://user-images.githubusercontent.com/18612/39890362-60417e02-544f-11e8-87af-e3674a9d9357.png)

Nothing obvious is standing out to me since the bulk of the leaked memory seems to be outside of the JS object system and I don't have any sense of what should or shouldn't be present. I've attached both heap snapshots so you can examine them. They're `.txt` files in order for them to be attached to the issue but they're actually JSON.

Let me know what else I can provide.

[Heap_Snapshot_A.txt](https://github.com/nwjs/nw.js/files/1993064/Heap_Snapshot_A.txt)
[Heap_Snapshot_B.txt](https://github.com/nwjs/nw.js/files/1993065/Heap_Snapshot_B.txt)

**Comment by rogerwang** [comment]
> It does not appear to keep the process from growing indefinitely

By "indefinitely" what's the maximum number seen there? And does it lead to out of memory crash? Is there any difference if the arguments are given as in https://github.com/nwjs/nw.js/issues/6583#issuecomment-387999065 ?

**Comment by rogerwang** [comment]
btw, the heap snapshot shows only the live objects in JS heap. It doesn't include the objects that are dead and to be garbage collected. So a normal heap snapshot under increasing memory doesn't imply leak outside of the JS object system. It could be that GC just marked some objects but hasn't decided to return their memory to the system.

**Comment by jakedouglas** [comment]
Makes sense. The process calling `gc()` repeatedly is now around 450mb. I haven't gotten a chance to see whether it OOMs yet. I'll try with the other GC flags you provided and see what happens.

**Comment by rogerwang** [comment]
> It could be that GC just marked some objects but hasn't decided to return their memory to the system.

To understand this, see 'mark-sweep' in http://jayconrod.com/posts/55/a-tour-of-v8-garbage-collection

And calling `gc()` doesn't guarantee v8 will perform a full GC. It just give v8 a hint, and v8 will make its decision with the application's request.

**Comment by jakedouglas** [comment]
Using `--js-flags="--optimize_for_size --max_old_space_size=460 --gc_interval=100"`, the process grew to ~980mb, then shrank to ~850mb for a while, then ~350mb before it began growing again to over 400mb.

We're going to move forward with v0.30.3, hoping that the problem we initially experienced will be improved or fixed in practice.

It does seem problematic to me though that memory usage is so difficult to reason about, and that default settings can result in occupying 1GB or more in an example application that does not intentionally hold any significant amount of data in memory. Our nwjs application is run by end users who notice things like ostensibly high memory usage, and it can give them a poor impression. Even if we get an opportunity to explain that the memory might be reclaimed if something else on their system needed it, it's not an easy conversation to have.

Thanks for your help!
