### ISSUE TITLE
no rounded corners and border Mac OSX

### ISSUE THREAD

**Issue by denigada** [nwjs/nw.js#6584]
NWJS Version : 0.30.1
Operating System : 10.13.4

With nwjs, even when the background color is set to a similar color, the top of the app body right below the native OSX bar doesn't look native.
![screen shot 2018-04-25 at 10 14 28 pm](https://user-images.githubusercontent.com/5206952/39282148-20b9dd58-48d6-11e8-8a0e-92d194d20c05.png)
To achieve a native look, we can use a [frameless window](https://github.com/nwjs/nw.js/wiki/Frameless-window) but when the `"frame": false` is used in package.json and custom buttons are created, the result is a square shaped window with no rounded corner and no native OSX border:
![screen shot 2018-04-25 at 10 17 20 pm](https://user-images.githubusercontent.com/5206952/39282236-8b074eb6-48d6-11e8-8261-cd7663d225cb.png)

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this?

**Comment by denigada** [comment]
@Christywl this is a known an unfixed issue [also on this topic](https://github.com/nwjs/nw.js/issues/175)

**Comment by denigada** [comment]
This issue is still not fixed. There is no way I can create a frameless window with native OSX borders and shadows. Are there any plans to fix this issue @rogerwang ?

**Comment by Christywl** [comment]
duplicate issue, and discussions will be in #175.
