### ISSUE TITLE
ES6 modules with .mjs extension / loaded from disk are broken in >=0.30

### ISSUE THREAD

**Issue by JonasT** [nwjs/nw.js#6585]
NWJS Version : 0.30.0-sdk (works in 0.29.4-sdk)
Operating System : Fedora 27

### Expected behavior

ES6 modules work when referenced in the startup index.html as local file like this: `<script src="app/main.mjs" type="module"></script>`

### Actual behavior

Error: `Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.`

### How to reproduce

```
<!DOCTYPE HTML>
<html>
    <head>
        <script src="app/main.mjs" type="module"></script>
    </head>
    <body>
    </body>
</html>
```

**Comment by rogerwang** [comment]
Does it work if the extension is `js`?

**Comment by Christywl** [comment]
Seem this issue doesn't reproduce on nwjs-sdk-v0.30.2. @JonasT , could you please try the latest build nwjs v0.30.2?

**Comment by JonasT** [comment]
@Christywl try `.mjs` (not `.js`), and try `npm install nw@0.29.4-sdk` which **works fine** for me, and after `npm install nw@0.30.0-sdk` it **doesn't work**.

@rogerwang probably, but I use `.mjs` because it's es6 modules and that seems to be common for the node ecosystem.

**Comment by rogerwang** [comment]
@JonasT 0.30.2 included a patch for supporting `mjs`, please try again with that version.

**Comment by JonasT** [comment]
@rogerwang it appears that `0.30.2-sdk` isn't available on npm yet:

```
$ npm install nw@0.30.2-sdk
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nw@0.30.2-sdk
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonas/.npm/_logs/2018-04-28T02_13_43_532Z-debug.log
```

**Comment by rogerwang** [comment]
That npm module is unofficial and need a while to be available. The new version can be downloaded now from https://nwjs.io/
