### ISSUE TITLE
"name" field in package.json shown on notification

### ISSUE THREAD

**Issue by denigada** [nwjs/nw.js#6591]
NWJS Version : 0.30.2
Operating System : MAC OSX 10.13.4

There is the name field in desktop notifications:

![screen shot 2018-04-28 at 8 32 27 pm](https://user-images.githubusercontent.com/5206952/39402053-814276c2-4b23-11e8-8e6d-e1d9f02e5031.png)

**Comment by Christywl** [comment]
This seems default, @rogerwang , I don't find the docs about this, is this a bug or is there some ways to set it?

**Comment by denigada** [comment]
@rogerwang Is there any way to remove the app name from the notification?

**Comment by rogerwang** [comment]
Will look for a way to fix it. Will you post the API you are using to show it?

**Comment by denigada** [comment]
I am just using the method in the [docs](https://github.com/nwjs/nw.js/wiki/Notification) 

`var options = {
  icon: "http://yourimage.jpg",
  body: "Here is the notification text"
 };
	
var notification = new Notification("Notification Title",options);`
