### ISSUE TITLE
Window resizable false not honored on Linux

### ISSUE THREAD

**Issue by slibychyby** [nwjs/nw.js#6592]
NWJS Version : v0.30.2
Operating System : Ubuntu 16.04.4 LTS

### Expected behavior

Window should not be resizable

### Actual behavior

Window is resizable

### How to reproduce

```json
{
  "name": "test",
  "main": "index.html",
  "window": {
    "height": 600,
    "width": 300,
    "resizable": false // this doesn't work on linux
  }
}
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hi</title>
  </head>
  <body style="width: 100%; height: 100%;">
  </body>
</html>
```

**Comment by slibychyby** [comment]
works on mac and windows afaict

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.30.2. It works fine on Windows/Mac.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
