### ISSUE TITLE
PaymentRequest API not supported

### ISSUE THREAD

**Issue by ncnlinh** [nwjs/nw.js#6595]
NWJS Version : 0.30.2
Operating System : MacOS

### Expected behavior
Dialog for PaymentRequest API should show up when calling `request.show()` for the supported browser - in this case, latest Chromium version (`request` is an PaymentRequest object) 

### Actual behavior

Error in console: `DOMException: Request cancelled`

### How to reproduce

Sample code:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Payment app</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <pre id="output"></pre>
    <script>
        var methodData = [
          {
            supportedMethods: ['basic-card'],
            data: {
              supportedNetworks: ['visa', 'mastercard', 'amex'],
              supportedTypes: ['credit']
            }
          }
        ];

        var details =  {
          displayItems: [
            {
              label: "Sub-total",
              amount: { currency: "USD", value : "100.00" }, // US$100.00
            }
          ],
          total:  {
            label: "Total due",
            amount: { currency: "USD", value : "100.00" }, // US$109.00
          }
        };

        var options = {
          requestShipping: false
        };

        var request=new PaymentRequest(methodData, details, options);
        request.show().then(console.log).catch(console.err);
    </script>
  </body>
</html>
```

Error:

![image](https://user-images.githubusercontent.com/7568367/39513507-2c3dddae-4e27-11e8-9b07-38f81cb4c988.png)

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows/Mac with nwjs-sdk-v0.30.2. The dialog doesn't popup, and `DOMException: Request cancelled` is displayed in the console.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
