### ISSUE TITLE
Can't get out of fullscreen

### ISSUE THREAD

**Issue by bengyles** [nwjs/nw.js#6597]
Hi,

This seems to be a problem that I have encountered a couple of times over the years so I thought I would post a question to find a good workaround.

I added an HTML5 video to my NWJS app and clicked the full screen button by accident. This however made the whole app go fullscreen and the video only appeared half so the controls where not visible. I closed the app and now everytime I run the app again it's stuck in fullscreen modus but I want my app to just open in a window. How can I fix this? Is there a way to reset the window settings somewhere?

======== TEMPLATE BUG FORM ========

NWJS Version : all of them
Operating System : Windows 8

### Expected behavior
The app does not get stuck in full screen without being able to put it back to normal or at least load the app in non fullscreen modus the next time it starts

### Actual behavior
App is stuck in fullscreen modus and you can't get out of it

### How to reproduce
Create a basic NWJS app and add a video (you could also use youtube) to it with the controls and click the fullscreen button

**Comment by bengyles** [comment]
Of course just after finally submitting an issue I found a solution to the problem however this is not a good solution for end users.

I went to my AppData folder under my user account and deleted the folder with the name of the app I had built. This resets all app properties that Windows has saved and this way Windows uses the default settings and I'm out of fullscreen modus.

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 8 with nwjs-sdk-v0.30.2. 
```
<video width="320" height="240" controls>
  <source src="movie.ogg" type="video/ogg">
</video>
```
and
`<a herf="https://www.youtube.com/">video</a>`
