### ISSUE TITLE
Destructing classes inside async workers

### ISSUE THREAD

**Issue by VictorQueiroz** [nwjs/nw.js#6598]
NWJS Version : 0.30.0
Operating System : Debian Sid Linux 

### Expected behavior

C++ class destructor only gets triggered when all processes working with it is done

### Actual behavior

C++ class destructor getting triggered for random and unknown reasons

### How to reproduce

Create an object wrapped C++ addon and pass an instantiated random and custom class to `Nan::AsyncWorker` after some time nw.js will destroy the class you passed to it after `Execute()` is done (if you reference this class inside JS code it won't happen), not sure why's that happening but that doesn't happen in Node.js v10, not sure if it's a problem with node.js, nw.js or my code. Let me know if you need more information

**Comment by rogerwang** [comment]
From the provided information it looks like a normal expected behavior that C++ object associated with JS object should be destroyed when the JS object is GCed. And you don't know when the GC will happen, it's up to the v8 engine to decide.

**Comment by VictorQueiroz** [comment]
@rogerwang I was testing and apparently unloading a few modules and I can see that loading only the addon (without from all components and modules, only one JS file) made a difference but still get destroy after some time if I import more heavy modules. Do you have any workaround for such issue? This happens to all modules using `Nan::AsyncWorker`.

**Comment by rogerwang** [comment]
I'm still a little confused about your situation. A minimal case showing it would be helpful.

**Comment by VictorQueiroz** [comment]
Here's a small example of what I'm trying to describe:

```c++
class MyWorker : public Nan::AsyncWorker {
private:
  MyCoolClass* value;
public:
  EncoderWorker(Nan::Callback* callback, MyCoolClass* value) : 
  Nan::AsyncWorker(callback), value(value) {
  }

  void Execute() {
    //... my work with MyCoolClass instance here ...
  }
};

void Work(const Nan::FunctionCallbackInfo<Value>& info){
  MyCoolClass* instance = Nan::ObjectWrap::Unwrap<MyCoolClass>(info.This());
  Callback* callback = new Callback(Local<Function>::Cast(info[0]));
  Nan::AsyncQueueWorker(new MyWorker(callback, instance));
}
```

With this approach when `MyWorker` starts, it'll destroy `MyCoolClass`, probably because it's taking `MyCoolClass` to another thread and messing things up. What just surprised me was that if the following approach works just fine:
```c++
class MyWorker : public Nan::AsyncWorker {
private:
  MyCoolClass* value;
public:
  EncoderWorker(Nan::Callback* callback, Local<Object> value) : 
  Nan::AsyncWorker(callback) {
    SaveToPersistent("instance", value);
    value = Nan::ObjectWrap::Unwrap<MyCoolClass>(value);
  }

  void Execute() {
    //... my work with MyCoolClass instance here ...
  }
};

void Work(const Nan::FunctionCallbackInfo<Value>& info){
  Callback* callback = new Callback(Local<Function>::Cast(info[0]));
  MyCoolClass* instance = Nan::ObjectWrap::Unwrap<MyCoolClass>(info.This());
  Nan::AsyncQueueWorker(new MyWorker(callback, info.This()));
}
```

Not sure why it works in this way but not in the other, any ideas?
