### ISSUE TITLE
Split build flavor into dedicated npm package, not tags

### ISSUE THREAD

**Issue by miaulightouch** [nwjs/nw.js#6600]
`nw` package on npm with different tag for build flavor is not easy for package upgrading with `yarn upgrade --latest`. if do, `nw@sdk` would be replaced by `nw@latest`.

Please release sdk with a new dedicated package on npm. (like `nw-sdk`, or other than `nw`)

**Comment by rogerwang** [comment]
Thanks. Please submit this issue to the project/repository of the package. It's not maintained by NW.js maintainers.
