### ISSUE TITLE
[0.31.0-beta1 / Linux] tray icon issues (tooltip + implicit menu)

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#6602]
NWJS Version: 0.31.0-beta1
Operating System: Arch Linux / Cinnamon

### Issue

I'm not sure if this was changed in `0.31.0-beta1` or in an earlier release (was working in `0.26.6`, the one I've been using before upgrading), but tooltips on tray icons are broken now and always display the value of NW.js' executable name (eg. `nw`, or `foo` if the nw executable gets renamed to `foo`).

This might be related to the change of the tray icon menu, since it's now using GTK+ on certain desktop environments instead of Chromium's own widget toolkit. Instead of using the provided `tooltip` property for actual tooltips when hovering the tray icon, the tooltip value seems to be used for adding a new menu item to the tray icon menu, which gets added, even if no menu has been defined explicitly. This new menu item is redundant and confusing for applications which build their own tray icon menus and don't expect another item to be added on certain desktop environments.

~~This menu issue does only seem to happen on Gnome or Gnome-based desktop environments, on KDE Plasma for example, this behavior doesn't occur, since it's not using the GTK+ tray icon menu.~~

### Expected behavior

- Use correct tooltip text on the tray icon tooltip while hovering it
- Don't add a tray icon menu if none has been set explicitly
- Don't add a new menu item with the value of the provided tooltip text if a (custom) menu has been added to the tray icon

### How to reproduce

- use Linux
- use Gnome or a Gnome-based DE like Cinnamon

```js
const { Tray } = require("nw.gui");
new Tray({
  icon: "/path/to/icon",
  tooltip: "My application name"
});
```

Result:
- tray icon tooltip is not `My application name`, but instead `nw`
- tray icon has a menu
- menu has a menu item with the text "My application name"

**Comment by Christywl** [comment]
I can reproduce this issue on Linux Mint 18.2 Cinnamon with nwjs-sdk-v0.30.3. A little difference: 

- tray icon tooltip is not My application name, but instead nw 
==>**there is no tooltip when hovering the tray icon in my device**
- tray icon has a menu 
==> **same result**
- menu has a menu item with the text "My application name" 
==> **same result**

 It works fine with nwjs-sdk-v0.29.4.

**Comment by bastimeyer** [comment]
This seems to have been fixed in one of the recent NW.js releases. It's working fine on `0.36.0-beta1`.
