### ISSUE TITLE
[Linux / Cinnamon] freedesktop notifications change since 0.27

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#6603]
NWJS Version: 0.31.0-beta1
Operating System: Arch Linux / Cinnamon

### Description

`0.27.0` has intoduced a change in Chromium regarding desktop notification on Linux (freedesktop notifications):
https://github.com/nwjs/chromium.src/commit/5688e36bf038d9d42c01079eaa48c118c3b832fd

This change always adds a "close" button to desktop notifications if the notification server is detected as "cinnamon". The reason behind that was that the Cinnamon desktop environment didn't provide a button for closing notifications, which made all clicks on them trigger their action. I agree, that this might be confusing for some users, but this also completely changes the layout of the rendered notification, because of the added buttons. The latest Cinnamon release has fixed this and added a close button, so this workaround has become pointless since the `3.8.0` release, which can be queried alongside the notification server capabilities. This would be a fix for upstream Chromium, though...

**This all wouldn't be an issue if the notification icons weren't broken in NW.js...**
As you can see here
https://github.com/nwjs/chromium.src/blob/nw-v0.31.0-beta1/chrome/browser/notifications/notification_platform_bridge_linux.cc#L511-L517
the NW.js icon always gets added to the notification, no matter what.
On regular notification layouts without any buttons, the NW.js icon doesn't get shown and instead [only the provided notification icon](https://developer.chrome.com/apps/notifications#type-NotificationOptions) is being used. This is what the developer and user expects.
However, if there are buttons, the provided notification icon gets shown for the notification message, but also the **NW.js icon** as an addition to that. This is an issue, because the **application's own icon**, as defined in the package.json, should be used here instead.

As an alternative, the close button could simply be removed again, like the settings button has been removed in #6194.
https://github.com/nwjs/chromium.src/blob/nw-v0.31.0-beta1/chrome/browser/notifications/notification_platform_bridge_linux.cc#L619-L623

Thank you for your consideration. :smiley: 

### How to reproduce

```js
window.chrome.notifications.create( "1", {
  type: "basic",
  title: "foo",
  message: "bar",
  iconUrl: "file:///path/to/specific/notification-icon.png",
  isClickable: true
});
```

Renders differently on Cinnamon and other desktop environments and causes issues with the **static NW.js** icon because of the added "close" button which makes the notification use a different layout.

**Comment by rogerwang** [comment]
Thanks for reporting. Could you please provide screenshots as well?

**Comment by bastimeyer** [comment]
I was wrong about the change being introduced in `0.30`. This already happened in `0.27`.

- **Notifications on the Plasma desktop environment in both `< 0.27` and `>= 0.27`:**
  No close button and only the intended icon is shown
  ![notification-plasma-old-and-new](https://user-images.githubusercontent.com/467294/39776614-a3dc2706-5301-11e8-8f8f-f2228447a743.png)
- **Notifications on the Cinnamon desktop environment in `< 0.27`:**
  No close button and only the intended icon is shown
  ![notification-cinnamon-old](https://user-images.githubusercontent.com/467294/39776613-a3bba210-5301-11e8-97d1-b6ff746eaa8a.png)
- **Notifications on the Cinnamon desktop environment in `>= 0.27`:**
  Adds the close button, causing a different layout to be shown, which then includes the static NW.js icon instead of the application's icon defined in `package.json`
  ![notification-cinnamon-new](https://user-images.githubusercontent.com/467294/39776612-a3994ea4-5301-11e8-8302-ecfd3108fa87.png)

So please either fix the issue of the static NW.js icon or remove the forced close button (maybe even check if the notification server is cinnamon `>= 3.8.0`, as the desktop environment includes a close button in this version).

Thank you very much!

**Comment by Christywl** [comment]
I try this on Linux Mint 18.2 Cinnamon with nwjs-sdk-v0.30.3, get the similar result:
![6603](https://user-images.githubusercontent.com/20039821/39859060-16bd889c-5428-11e8-8bf0-a9f10acd6c28.png)

nwjs-sdk-v0.26.6:
![6603-1](https://user-images.githubusercontent.com/20039821/39859145-53f1b0f8-5428-11e8-8eb6-fbbd8690097f.png)

**Comment by bastimeyer** [comment]
Your second screenshot is showing a "Chromium Rich Notification" rendered by Chromium instead of a freedesktop notification rendered by the desktop environment.

I forgot to mention that you need to set the `--enable-features=NativeNotifications` Chromium parameter in NW.js `< 0.28`. This flag was enabled in Chromium 64 (NW.js 0.28) by default:
https://bugs.chromium.org/p/chromium/issues/detail?id=676220#c108

**Comment by bastimeyer** [comment]
I would really appreciate it if this could be fixed any time soon. It is still present in the NW.js `0.36.0-beta1` release and kind of prevents me from upgrading my application unless I ignore this annoying issue.

----

**Short recap**

The notification close button was added by the Chromium devs (https://crbug.com/804637) in order to fix a UX issue in the Cinnamon desktop environment. The problem was that there was no way to manually close a notification without clicking it, which would also always trigger its attached click action, or without waiting for it to disappear after a couple of seconds.
However, this UX issue was fixed in Cinnamon many releases ago ([on December 18th 2017 in 3.8.0](https://github.com/linuxmint/Cinnamon/blob/master/debian/changelog#L1075)) and now the workaround applied by the Chromium devs is unnecessary and changes the style/layout of the notifications because of the now unnecessary close button.

----

**How to fix**

As I've mentioned in my first post, this workaround could easily be reverted here:
https://github.com/nwjs/chromium.src/blob/nw36/chrome/browser/notifications/notification_platform_bridge_linux.cc#L173-L180
or even better, here:
https://github.com/nwjs/chromium.src/blob/nw36/chrome/browser/notifications/notification_platform_bridge_linux.cc#L622-L634
since you're already removing the settings button which gets added by default in Chromium and doesn't do anything in NW.js (was removed in #6194)

I know it's an upstream problem, but I don't see anything against reverting this workaround, as it's intended for older releases of Cinnamon.

**Thanks!**

As a side note, the absolute proper and correct way to solve this issue would be sending a `GetServerInformation` request to the notification server and checking whether its name is cinnamon and its version lower than 3.8.0, but that's something for the Chromium devs to consider.

**Comment by bastimeyer** [comment]
Fixed in Chromium and it looks like it'll be included in NW.js 0.38:
https://github.com/nwjs/chromium.src/commit/23b4f11cb22baa228000fb7361485c34d70ca07a#diff-c1dac52d37c9a066f42dd729ac44500b
