### ISSUE TITLE
enable webvr flag

### ISSUE THREAD

**Issue by stephanedemotte** [nwjs/nw.js#6605]
Hi 

I found a flag to activate webvr, but i need more :)
For now we have `"chromium-args" : "--enable-webvr"`

Someone know how to activate all vr flag ?

![image](https://user-images.githubusercontent.com/2158130/39815982-d4001fb2-5367-11e8-87b8-053545fb6976.png)

Don't find any doc on this :/

Thank you !

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
