### ISSUE TITLE
PDF Local File Printing

### ISSUE THREAD

**Issue by subu1979** [nwjs/nw.js#6608]
Hi NWJS Team,

NWJS Version :18.3
Operating System :Windows 10

### Expected behavior

Local PDF File has be printed.

### Actual behavior

Specified Local PDF File is Not Printing.

### How to reproduce

win.print({pdf_path: 'd:/Receipt_BC.pdf'});

Regards
Subramanyam

**Comment by subu1979** [comment]
"nw": "^0.30.2",
"nw-builder": "^3.5.1"

I'am getting the following Error when i run the print command win.print({pdf_path: 'd:/Receipt_BC.pdf'});

[3492:7764:0510/164318.348:ERROR:image_png_rep.cc(37)] Unable to decode PNG.
[3492:7764:0510/164318.348:ERROR:image_generic.cc(71)] Unable to decode PNG for 1.
[3492:9200:0510/164319.649:ERROR:gpu_process_transport_factory.cc(1012)] Lost UI shared context.

Regards
Subramanyam

**Comment by Christywl** [comment]
`win.print()` prints the web contents in the window. `pdf_path` field is the path of the output PDF when printing to PDF. 
http://docs.nwjs.io/en/latest/References/Window/#winprintoptions

**Comment by subu1979** [comment]
Thanks for the update.
