### ISSUE TITLE
Linux: Window should be resizable after setting resizable to true, even when initially set to false.

### ISSUE THREAD

**Issue by slibychyby** [nwjs/nw.js#6609]
NWJS Version : v0.30.3
Operating System : Ubuntu 16.04.4 LTS

### Expected behavior

Window should be resizable after setting resizable to true, even when initially set to false.

### Actual behavior

Window is not resizable.

#### Snippet 1

```json
{
  "name": "test",
  "main": "index.html",
  "window": {
    "height": 600,
    "width": 300,
    "resizable": false
  }
}
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hi</title>
  </head>
  <body style="width: 100%; height: 100%;">
    <script>
      nw.Window.get().setResizable(true)
    </script>
  </body>
</html>
```

With the snippet above, `nw.Window.get().setResizable(true)` is a no-op on Linux, works fine on Mac and Windows.

#### Snippet 2

```json
{
  "name": "test",
  "main": "index.html",
  "window": {
    "height": 600,
    "width": 300,
    "resizable": true
  }
}
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hi</title>
  </head>
  <body style="width: 100%; height: 100%;">
    <script>
      setTimeout(() => nw.Window.get().setResizable(false), 2000)
      setTimeout(() => nw.Window.get().setResizable(true), 5000)
    </script>
  </body>
</html>

```

With the snippet above, it starts as resizable, becomes unresizable after 2s, and then resizable again, all platforms.

**Comment by slibychyby** [comment]
Snippet 1 should be consistent across platforms.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.30.3.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
