### ISSUE TITLE
Upload button instead of select on folder picker nwdirectory 

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6610]
NWJS Version : 0.30.2
Operating System : Only Windows 10 64 bit
On Mac OSX this is working fine

### Expected behavior

Open System Select Folder dialog with "Select" button and "Create Folder" buttons

### Actual behavior

Select Folder dialog shows wrong button "Upload" instead of "Select" and is also missing the Create Folder" button

### How to reproduce

```html
<input id="folder-open-dialog" type="file" nwdirectory nwworkingdir="" nwdirectorydesc="Please select a folder" role="hidden" />
```

![upload_instead_select](https://user-images.githubusercontent.com/504730/39889330-dc90b6e2-5497-11e8-87fe-3286bb3a5c32.png)
Sorry for the localized dutch screenshot - but it should be clear 😄 

Maybe related to:
https://github.com/nwjs/nw.js/issues/5265

Test files:
[folder_picker_bug.zip](https://github.com/nwjs/nw.js/files/1992964/folder_picker_bug.zip)

**Comment by Christywl** [comment]
I can reproduce this issue on Windows with nwjs-sdk-v0.30.3:
![image](https://user-images.githubusercontent.com/20039821/39902965-53023c0e-5503-11e8-9768-870fd92c2f60.png)

nwjs-sdk-v0.28.3
![image](https://user-images.githubusercontent.com/20039821/39902925-25cb4a96-5503-11e8-859d-800b132ae43f.png)

It works fine on Linux and Mac .

**Comment by gpetrov** [comment]
@rogerwang could you please check this? is a simple enum to fix. I will hate to go back to 0.28.3 for just this simple folder picker ... but it is very confusing to our users.

**Comment by rogerwang** [comment]
Will see it soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by premalatha-bv** [comment]
Issue still exists with 0.37.0 version too.
If it is fixed in 0.30.0 version. Could you please move the changes to 0.37.0 version too.

Am facing same issue with 0.37.0 version.

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-win-v0.36.0&v0.37.0. It works well with v0.35.5.

**Comment by rogerwang** [comment]
Thanks.

@ffanny we should find a way to add this to automatic tests.

**Comment by ffanny** [comment]
> Thanks.
> 
> @ffanny we should find a way to add this to automatic tests.

Will try to add autotest soon.

**Comment by premalatha-bv** [comment]
Please let us know, If this changes has been added in 0.37.0 version? or any new version released for same changes? It would be very helpful for us to decide, whether we need to change to older version or continue with latest version.

**Comment by rogerwang** [comment]
It will be fixed on 0.37 branch and released with 0.37.2 soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The fix was built here: https://dl.nwjs.io/live-build/nw37/04-01-2019/8a1cce4ef/v0.37.2/
