### ISSUE TITLE
Do inject_js_start, inject_js_end in nw.Window.open work?

### ISSUE THREAD

**Issue by corwin-of-amber** [nwjs/nw.js#6612]
NWJS Version : 0.29.4-sdk , 0.31.0-beta1-sdk
Operating System : macOS

### Expected behavior

The documentation states nw.Window.open accepts an `options` argument with properties `inject_js_start`, `inject_js_end`.

### Actual behavior

I tried to put some JS code in these properties and nothing actually happens.

```
nw.Window.open("http://example.com/", {inject_js_start: "alert(5);"})
```

I tried `alert(...)`, `console.log(...)`, `var some_var = ...;` etc. The URL loads just fine but the code does not seem to ever execute.

The issue title has a question mark because I'm not sure what is supposed to happen. Am I just doing it  wrong?

**Comment by rogerwang** [comment]
The value of those should be a JS file name.

**Comment by corwin-of-amber** [comment]
Oops. Silly me.
Missed this being mentioned next to the `{String}` in Manifest doc.
