### ISSUE TITLE
Program crashed by 'http_transport_win.cc(175) WinHttpCrackUrl'

### ISSUE THREAD

**Issue by Ser-Gen** [nwjs/nw.js#6616]
NWJS Version : 0.30.4
Operating System : Windows 10 x64

Full error text
```
[0514/181211.840:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: URL-адрес не использует поддерживаемый протокол (0x2ee6)
```

Dump
[a9e84d86-98ec-401a-b1fb-f59f180d6561.zip](https://github.com/nwjs/nw.js/files/2001430/a9e84d86-98ec-401a-b1fb-f59f180d6561.zip)

I use NW to open an intranet app.
It uses ajax for messaging. Crash happens in random time, when message is sent.
But I can't identify event that leads to crash.

Tried clean `appdata/local/[app_folder]`, no luck.

Last version that working stable is `0.22.3`.

**Comment by cTn-dev** [comment]
Have you tried adding node exception handler?

```
process.on('uncaughtException', (err) => {
  console.error(err);
});
```

This is most likely a duplicate of #6153

**Comment by Ser-Gen** [comment]
Yep, I already have this handler

```
process.on('uncaughtException' ,function (e) {
	console.error('uncaughtException:', e);
	console.error(e.stack);
});
```

**Comment by Christywl** [comment]
@Ser-Gen , could you please provide a sample to reproduce this issue?

**Comment by Ser-Gen** [comment]
I'm sure, that it happens somewhere inside of huge scripts of Bitrix 24.
I will try to locate this problem, but it will takes time.

**Comment by miaulightouch** [comment]
it also happens randomly on win10 if nw >= 0.30.0.

same code, same environment would throw these info and create crash report but not every time.
` [0524/192118.746:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: ...(0x2ee6)`

**Comment by dallascao** [comment]
I confirmed this bug. It occurs when I compiled my script to *.bin with nwjc.exe

**Comment by maikonmatheus** [comment]
This is caused when you use nwjc from a platform (win32 or win64) of NWJS and, after the build, try to load the .bin in another platform. Just use the nwjc from the same platform and will works.

**Comment by rbhushasn** [comment]
Hi 
I am also getting the crash issue. If I am opening Microsoft team in the new NW window. when I am closing Microsoft team window whole app is crashing.
