### ISSUE TITLE
win.show() not focus it sometimes

### ISSUE THREAD

**Issue by sctaix** [nwjs/nw.js#6618]
NWJS Version : v0.29.3
Operating System : window10

### Expected behavior
I called win.show() function when minimized window, it should be pop up and focus it.

### Actual behavior
but sometimes minimized window icon just blinking then not popped up.

**Comment by Christywl** [comment]
`win.show()` works fine on my Windows. Could you please try the latest nwjs build? If still reproduce, please upload your sample.

**Comment by Christywl** [comment]
close until there is more information
