### ISSUE TITLE
Incorrect process.cwd() and process.execPath path for OSX to get current directory

### ISSUE THREAD

**Issue by Arti3DPlayer** [nwjs/nw.js#6619]
NWJS Version : Latest and 0.28.3
Operating System : OSX

### Expected behavior
After I packaged app with nw-builder, this line:

`var appDir = path.resolve(process.cwd(), '../../../');`

Should return me current app folder, like '~/Downlaods/myapp.app/`

### Actual behavior

It returns me path to `temporary folder`:

`/private/var/folders/5f/2w5ss9tn6ksgwmxkl1lrqyyh0000gn/T/AppTranslocation/8C45F9CD-87C6-4902-8D10-6586815A15B6/d/Myapp.app/Contents/Resources`

The same situation with:

`process.execPath`

### How to reproduce

Package your app,  download from web, unzip, run.

!Important to download from web .zip, unpack and then run app, because fresh build app is working fine. Looks like some osx security...

**Comment by Arti3DPlayer** [comment]
Ok, find an answer:

This appears to be an issue with opening the app from the "Downloads" folder (default when saving an app in Chrome on OSX, at least, not sure about other browsers). The app has to be copied to the "Applications" folder first.

**Comment by Christywl** [comment]
Similar with #648 ?

**Comment by rogerwang** [comment]
close as duplicate.

**Comment by Arti3DPlayer** [comment]
@rogerwang did you fix the issue that process from Download folder move to `AppTranslocation` path or you just add new convenient way to get current app path ?

**Comment by Arti3DPlayer** [comment]
I guess you maybe need to notice that in documentation
