### ISSUE TITLE
Video capture from iframe doesn't work

### ISSUE THREAD

**Issue by mkazlauskas** [nwjs/nw.js#6629]
NWJS Version : 0.30.4
Operating System : Tested on Linux x64 and Windows x86

### Expected behavior

`iframe` should inherit `videoCapture` permission from parent page.

### Actual behavior

MediaStream API doesn't work from within `iframe`, while it works from browser window's main page. It acts as if there was a permission dialog that was cancelled (neither accepted nor denied).

### How to reproduce

Load `<iframe src="https://webcamtests.com">` (or any other webcam test site) and try to capture video.

**Comment by Christywl** [comment]
Please try this:
`<iframe src="https://webcamtests.com" allow="camera"></iframe>`

**Comment by mkazlauskas** [comment]
Thank you, it worked! Is this some standard Chromium behavior? Where can I find documentation on "allow" values?

**Comment by Christywl** [comment]
The behavior is same with Chrome. And please see more info: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
