### ISSUE TITLE
Memory overhead for WebWorker communication not freed correctly

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6632]
NWJS Version : 0.30.5 SDK
Operating System : Ubuntu 18.04 x64 (lubuntu-desktop), Windows 10 x64

This is a bit of "unconventional" report from me, sorry about that.
As i don't know if this is expected behavior, but the huge amount of allocated memory should hopefully mean it isn't.

### Expected behavior
I don't exactly know what is happening here, but the memory required to transfer object from the main context to the worker and back should be freed after the object is transferred (yes i know the object is re-created in the other context and its not a memory transfer).
### Actual behavior
The memory is not freed, terminating the worker/s does free up a portion of the allocated memory, but there is still considerable chunk left, this problem appears to be worse on linux than on windows.
### How to reproduce

I am attaching a rather crude example app to demonstrate what i am seeing [example.zip](https://github.com/nwjs/nw.js/files/2020613/example.zip)

1. Start the app,
2. Open the inspector -> console
3. Let the app run for a few minutes

4. When the resident set size appears reasonably big you can kill the loop by `clearInterval(intervalChecker);`
5. Give it a few seconds to stop and the garbage collection kicks in, then call  `printMemUsage();`

You can see there is a pretty huge amount of memory allocated while the heap for the "main" context and also heap of each of the workers is pretty much empty.

6. call `workers.forEach((worker) => worker.terminate());`
7. call `printMemUsage();`

This shows that "most" of the allocated memory was freed (although the resident set is still way bigger than what it should be).

My results on Linux

![linux_test](https://user-images.githubusercontent.com/2289413/40282749-1e9f4006-5c74-11e8-80de-9819b4250959.png)

My results on Windows

![windows_test](https://user-images.githubusercontent.com/2289413/40282780-77e66478-5c74-11e8-9815-bc48953ce9b2.png)

I should note that the app doesn't crash, and there does seem to be some limit to which this memory allocation will grow (**~800mb**).

The behavior is little bit different on Windows as you can see (on Windows significant portion of the allocated memory gets freed after a while).

I can also confirm this that with my regular app which transfers significant amount of objects on startup between workers, that on Windows large portion of this memory is correctly freed, while on Linux it isn't.

The example code i attached is a super-abusive way of getting the memory results i wanted to show and really shouldn't represent any real world use scenario however it shows the "issue" that i am facing in my regular app where the memory allocation keeps slowly growing over time due to large amount of small messages passed between main context and workers over longer periods of time (typical uptime for my app should be **months**) so i would like to get this under control even though it shouldn't crash the app or the system if the **800mb** cap ends up holding.

**Comment by rogerwang** [comment]
Does this switch make any difference? `--js-flags="--optimize_for_size --max_old_space_size=460 --gc_interval=100"`

**Comment by cTn-dev** [comment]
@rogerwang No, there doesn't seem to be any significant difference with the extra flags from what i can see.

I ran the windows test much shorter than before, so i would says the mem usage is pretty much the same there, on linux the mem usage seems tiny bit worse, still hovering around the **800mb** in both cases.

Test results with the the additional flags below:

Linux
![linux_test_2](https://user-images.githubusercontent.com/2289413/40292323-f2013e8a-5cca-11e8-81da-6ac9af041ada.png)

Windows
![windows_test_2](https://user-images.githubusercontent.com/2289413/40292332-fffe818c-5cca-11e8-9823-68247f33c900.png)

**Comment by cTn-dev** [comment]
@rogerwang I did a bit of backwards testing (on windows only) and this appears to be a regression that got introduced in 0.28.0, this was the build with the mitigation-s for Spectre, dunno if this helps you in any way.

**Comment by rogerwang** [comment]
It works for me -- after using the js-flags in the command line the RSS usage is limited to 200+MB here.

**Comment by cTn-dev** [comment]
Really? on 0.30.5 when i use `--js-flags="--optimize_for_size --max_old_space_size=460 --gc_interval=100"` in command line or adding them into the package.json makes no difference in my tests.

I am attaching an updated exampled that has the flags you provided set in the package.json
[example2.zip](https://github.com/nwjs/nw.js/files/2025143/example2.zip)

**Comment by cTn-dev** [comment]
Could this be somehow hardware related? My development machine runs on Intel CPU that already has some of the meltdown/spectre patches applied through latest bios, when it comes to linux testing, that virtual server also runs on intel (dunno if any bios level patches have been applied there).

**Comment by rogerwang** [comment]
There is no evidence that this is meltdown/spectre related. Huge number of changes are introduced in each major upgrade in Chromium and the security patches are just small in terms of lines of code.

**Comment by cTn-dev** [comment]
I see, in that case i would focus on getting the example trigger the high memory usage for you as this looks very fishy since i see it on 2 different operating systems :/ while both of them are as up-to-date as they possibly can.
