### ISSUE TITLE
NW app not launching if ExtensionInstallBlacklistregistry key is set to block all extensions

### ISSUE THREAD

**Issue by dsomesh** [nwjs/nw.js#6634]
Expected behavior-
One of has the following key set to enable roaming profile for chromium
[HKEY_CURRENT_USER\Software\Policies\Chromium\ExtensionInstallBlacklist]
"1"="*"

Actual behavior
On launching nw a prompt appears saying that "loading of unpackaged extensions in disbaled by the Administrator".The prompt is-
![capture](https://user-images.githubusercontent.com/19370408/40292987-3519e778-5cec-11e8-8e0d-31f3b82e3252.PNG)

NWJS Version :v0.25.4-win-x64
Operating System : Windows 7 64 bit

How to reproduce
It is easily reproducible with following steps.(I reproduced in windows 7 64 bit)

Take a machine added to domain
Set the following Registry key-
[HKEY_CURRENT_USER\Software\Policies\Chromium\ExtensionInstallBlacklist]
"1"="*"
Launch the application

**Comment by dsomesh** [comment]
Any insight on this?

**Comment by rogerwang** [comment]
What about setting `ExtensionInstallWhitelist` as a workaround?

**Comment by rogerwang** [comment]
@dsomesh my bad. That value should be ineffective when wildcard is used in the black list.

**Comment by dsomesh** [comment]
I think Whitelist value value overrides the Blacklist value as per https://www.chromium.org/administrators/policy-list-3#ExtensionInstallWhitelist

**Comment by rogerwang** [comment]
@Christywl could you try overriding it by setting `extensions.management` preference in the master preference file? https://www.chromium.org/administrators/configuring-other-preferences

See the override logic here: https://cs.chromium.org/chromium/src/chrome/browser/extensions/extension_management.cc?rcl=9b11dbe5ef9b56788ff997ba9945a7b65842cd8c&l=322

**Comment by dsomesh** [comment]
Any workarounds for 0.25.4?

**Comment by Christywl** [comment]
@rogerwang , I find more info about chrome extension setting in master_preferences file: https://www.chromium.org/administrators/pre-installed-extensions
But I have no idea how to config this for nw application.

**Comment by rogerwang** [comment]
@Christywl try to add/merge the following into `Preferences` json file in the user data dir:

```
"extensions": {
  "management": {
    "*" : { "installation_mode": "allowed" }
  }
}
```

**Comment by dsomesh** [comment]
@rogerwang Any insight on how I can make this work in 0.25.4?our customer's deployment is stopped because of this.

**Comment by rogerwang** [comment]
@dsomesh we are trying to find one. I believe there is one for 0.25. Could you please try the way in my last comment as well?

**Comment by Christywl** [comment]
@rogerwang , I find master_preferences.json file in C:\Program Files (x86)\Google\Chrome\Application, and try to add the extensions setting in it,  it doesn't work. 
And in the nw application user data dir or nwjs user data dir, I try to add the extensions setting in preference file, it also doesn't work.

**Comment by dsomesh** [comment]
"extensions": {
  "management": {
    "*" : { "installation_mode": "allowed" }
  }
}

Where should I add this?I do not see any Preferences json file inside our folder in user-data-dir.
Below is the content of my user-data-dir directory.

[User Data.zip](https://github.com/nwjs/nw.js/files/2034077/User.Data.zip)

**Comment by rogerwang** [comment]
@dsomesh based on what we've found so far, I'm afraid there is no workaround in NW for this. You may need to workaround it by disabling the registry key in your launcher, or wait for the next version in which we'll fix it.

**Comment by dsomesh** [comment]
@rogerwang does this value matters only when the process is getting launched? If so, fixing it in launcher might work

**Comment by rogerwang** [comment]
@dsomesh yes, you are right.

**Comment by rogerwang** [comment]
Will look to fix it soon in the next version. Thanks for your patience.

On September 14, 2018 2:22:42 PM GMT+08:00, Somesh Dhal <notifications@github.com> wrote:
>Can we have a target milestone for this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nwjs/nw.js/issues/6634#issuecomment-421243919

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
