### ISSUE TITLE
请问怎么动态设置uaseragent为客户电脑的mac地址呢

### ISSUE THREAD

**Issue by yq5858588** [nwjs/nw.js#6640]
请问怎么动态设置uaseragent为客户电脑的mac地址呢？以前用electron的时候可以动态设置  现在nwjs不知道怎么动态设置，要不是我们的客户用xp我们也不会这么麻烦

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by yq5858588** [comment]
谷歌的地址我打不开哦真的很遗憾
