### ISSUE TITLE
When the CSS failed to load randomly, the white screen appeared. 

### ISSUE THREAD

**Issue by onlyou** [nwjs/nw.js#6643]
When the CSS failed to load randomly, the white screen appeared. When the computer was restarted, the CSS failed to load randomly.

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :0294 
Operating System :Windows7

**Comment by onlyou** [comment]
<img width="362" alt="snipaste20180524_114040" src="https://user-images.githubusercontent.com/2231544/40463369-8445560e-5f47-11e8-89b5-5c3c6e94c912.png">

**Comment by Christywl** [comment]
Could you please provide a sample to reproduce this?

**Comment by onlyou** [comment]
@Christywl 
Machine room appears randomly, single machine is difficult to test out.
