### ISSUE TITLE
Geolocation not working in webview.

### ISSUE THREAD

**Issue by janRucka** [nwjs/nw.js#6644]
Geolocation not working in webview.

Geolocation is not working if used from page loaded in webview with version 0.30.5 even if Google API Key is available (and GeolocationPermissionRequest is allowed). It is working fine with latest 0.27 .

It is because of NW.js changes in 'chrome/browser/permissions/permission_manager.cc' file:
https://github.com/nwjs/chromium.src/commit/33cd7097eede00b9c4ce59f5cf7d0e7f1eee86d8#diff-5cf98ba2baab62261c6a3d87f9799341

Code:
```
  extensions::ExtensionRegistry* extension_registry =
    extensions::ExtensionRegistry::Get(profile_);
  const extensions::Extension* extension =
    extension_registry->enabled_extensions().GetByID(canonical_requesting_origin.host());
  if (extension && extension->is_nwjs_app()) {
    callback.Run(
        std::vector<ContentSetting>(permissions.size(), CONTENT_SETTING_ALLOW));
    return kNoPendingOperation;
  }
```

Although at the first look it seems fine in case of webview it does not properly propagate 'allow' decision into NetworkLocationProvider. This file was not modified by NW.js in version 0.27.

**Comment by janRucka** [comment]
[geo.zip](https://github.com/nwjs/nw.js/files/2038693/geo.zip)

Ok here it is. Open it in NW.js and just try to use geolocation on Google maps. If you have google API key available (either in your system or inside of Nw.js(custom build needed)) it will geolocate with latest 0.27 but not with 0.30. In 0.30 it is behaving as if permission was not granted.

**Comment by janRucka** [comment]
Any progress?

**Comment by Christywl** [comment]
I can reproduce this issue now with nwjs-sdk-v0.31.1, seem it doesn't work from v0.30. 
It works fine on v0.27~v0.29

**Comment by rogerwang** [comment]
How to tell it works or not? I opened the app and it shows google map. Nothing strange here.

**Comment by Christywl** [comment]
You can try to tap the location button in the bottom right corner. I can get my location with <0.30, but fail with >=0.30.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
Ref: #6492
