### ISSUE TITLE
Mac app signing -> crashes right after launch

### ISSUE THREAD

**Issue by denigada** [nwjs/nw.js#6656]
Using NWJS version 0.31.0, when I try to sign the app with **Developer ID Application**, the build_mas.py finishes without problems, but when user tries to open the app, he gets unidentified developer warning.

When I try the script with **3rd Party Mac Developer Installer** certificate, I get this warning:
`Warning: unable to build chain to self-signed root for signer "3rd Party Mac Developer Application: My Company Name (AAAAAAAA)`

and the one signed with  **3rd Party Mac Developer Installer** certificate crashes after a split second it is launched.

I see that there isn't a up to date MAS build. Does anyone know a fix to properly sign an app to be distributed out of the App Store, **without the Unidentified Developer warning**? We have been working on this app for 7 months and now we are stuck trying to sign the app for Mac OSX.

**Comment by tankakatan** [comment]
@denigada The warning you have mentioned is probably related to incorrectly installed certificates. Please check your `keychain Access` app – it should contain both `3rd Party Mac Developer Installer`, `3rd Party Mac Developer Application`. The trust settings for that certificates should be `System Defaults`.

The crash you have described is most likely related to the app sandbox entitlement. Try to set it to `false` (in both child and parent entitlement plists), resign your app and lunch it again. If it starts correctly my theory is true. However you will not be able to distribute your app via MAS without sandbox entitlement set to `true`. Please read #6338 where i have described the possible reasons of the crash i have found.

**Comment by denigada** [comment]
I reinstalled the certificates and didn't touch their trust settings. I am still getting the same error. When I evaluate the certificate in keychain it shows it as:
![screen shot 2018-06-01 at 1 00 50 pm](https://user-images.githubusercontent.com/5206952/40853375-d8852848-659b-11e8-9a18-311db822b126.png)

All I am trying to accomplish is my users not seeing any warnings and the app is trusted. One thing I realized is when I'm signing with Developer ID certificates (which keychain access shows as trusted), I get password prompts in terminal to allow access to certificates. I dont even get that prompt when signing with 3d Party Mac Developer certificate. Can you think of a possible fix for this?

**Comment by denigada** [comment]
Signing the app with Developer ID certificates and setting the sandbox false resulted in a successful signing for me. My app doesn't show any warnings. It still doesn't work with the MAS certificate though.
