### ISSUE TITLE
CSS not reloading on window.reload

### ISSUE THREAD

**Issue by quantumproducer** [nwjs/nw.js#6658]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.31 sdk
Operating System : OSX 10.13.4

### Expected behavior

<!- What do you think should happen? ->

Reloading the window should reload the css

HTML:

```
<html>
<title>www.Combo.Zone</title>
<body style="overflow: hidden">
<link rel="stylesheet" href="style.css">
<div id="arcade">
<div id="arcade_header">
  Arcade Header
</div>
<center>
	<div id="game_container">
		<canvas id="canvas" style="width: 800px; height: 800px; cursor: none;">
		</canvas>
	</div>
</center>
<div id="arcade_footer">
  Arcade Footer
</div>
</div>
</body>

<link rel="stylesheet" type="text/css" href="arcade.css"/>
<script src="arcade.js"></script>
<script src="engine_client.js"></script>
<script src="engine_rev.js"></script>
</html>

```

CSS:

```
#arcade {
  display: grid;
  grid-template-rows: 10% 80% 10%
}

#arcade_header {
  background-color: #FF0000;
}

#arcade_footer {
  background: #FF0000;
}
```

engine_client.js
```
"use strict";

const gui = require('nw.gui');
var result = gui.Screen.Init();
console.log("Screen inited" + Object.keys(result.screens));
window.Screen = result;
console.log("window.Screen.screens" + window.Screen.screens);
var win = gui.Window.get();
console.log("gui is" + gui);
gui.Screen.on('displayBoundsChanged', function(scn) {
	console.log("display bounds changed" + scn.bounds.height);
});

win.on('resize', function(w) {
	console.log("resized" + w);
	var scrn2 = window.Screen.screens[0];
	scrn2.bounds.height = win.height;
	console.log("unmaxed with" + scrn2.bounds.height);
	window.client.reloadScreen(scrn2, true);
	console.log(win.height);
	w.reload();
	win.reload();
});
```

### Actual behavior

<!- What actually happens? ->

Nothing happens, the HTML element isn't resized appropriately.
The CSS dictates the header should be resized to 10% of the window height, same with the footer.

**Comment by Christywl** [comment]
Could you please upload your full sample here?

**Comment by quantumproducer** [comment]
Hi @Christywl , I cannot upload the full sample as Github refuses files over 100mb, and the binary exceeds that. Here is my app.nw :  https://github.com/QuantumProductions/nw_sample

**Comment by Christywl** [comment]
When I start your sample with nwjs-sdk-v0.31.5, it shows:
<img width="1280" alt="screen shot 2018-06-05 at 13 49 07" src="https://user-images.githubusercontent.com/20039821/40957350-4c5af42c-68c7-11e8-9734-1fcc64cb7935.png">


When i try to resize the window, the height of header and footer has no change. Is this result same with yours? What about 'window reload'?

**Comment by Christywl** [comment]
close until there is more information
