### ISSUE TITLE
Expression:new_time >= loop->time

### ISSUE THREAD

**Issue by daemon-7** [nwjs/nw.js#6659]
NWJS Version :0.30.1
Operating System :win7

### Expected behavior
start-up nw.exe

### Actual 
![1](https://user-images.githubusercontent.com/7839797/40826279-c8845a20-65ac-11e8-8fce-333794857602.png)

**Comment by Christywl** [comment]
I can't reproduce this issue on Windows 7 with nwjs-sdk-v0.30.1 and v0.31.0. 
nw.exe could be started successfully.
<img width="1090" alt="6659" src="https://user-images.githubusercontent.com/20039821/40959747-37c32224-68d0-11e8-8a4a-fc4d4863721d.PNG">

**Comment by tphalp** [comment]
I just experienced this same issue on Windows 7 (6.1), with v0.40.2.

![image](https://user-images.githubusercontent.com/1331818/64456977-ad2ff900-d0ae-11e9-9a96-72f9e5749908.png)

Anyone know what is causing this? I also tried an older version that we have recently used, 0.29.3 which exhibited the same error.
