### ISSUE TITLE
nwjs Helper using %100 CPU on 0.31.0

### ISSUE THREAD

**Issue by denigada** [nwjs/nw.js#6662]
NWJS Version : 0.31.0
Operating System : Mac OSX 10.13.4

When I run the app through terminal, there isn't any problem. When I run the actual built and signed app, nwjs Helper uses %100 CPU. There isn't this problem on 0.30.5

**Comment by rogerwang** [comment]
Thanks for reporting. Could you please provide a sample to reproduce?

**Comment by gpetrov** [comment]
maybe related to https://github.com/nwjs/nw.js/issues/6677

I'v experienced some nwjs Helper loops web the main process crashed due the problem above and the nwjs Helper process stay hanging but with 100% CPU

**Comment by gearintellix** [comment]
I had similar to
