### ISSUE TITLE
win.getPrinters not receive an array of JSON objects

### ISSUE THREAD

**Issue by abeluiux** [nwjs/nw.js#6663]
NWJS Version : **0.31.0**
Operating System : Win 8

`win.getPrinters(printers => { console.log(printers) })`

Print:
`$ {...} It should not happen`

NWJS Version : **0.30.5**
Operating System : Win 8

`win.getPrinters(printers => { console.log(printers) })`
Print:
`$ [...] Correct`

**Comment by Christywl** [comment]
I can reproduce this issue with nwjs-sdk-v0.31.0.
