### ISSUE TITLE
index.html requirement?

### ISSUE THREAD

**Issue by Bizarrus** [nwjs/nw.js#6664]
I've found no informations about that. That is the reason, why i create the issue.

Is the `index.html` a requirement?

I want to create an Application without an initial Window. On the documentation it will be displayed as `window: false` and `main: file.js` on the `package.json`. But i've found no more resources about these.

**Comment by rogerwang** [comment]
No. It's not a requirement. You can use JS as main as well and open window from there.

**Comment by Bizarrus** [comment]
Can someone create an simple example?

When i try to change index.html to main.js and only set on the first line an console-output, no messages appears, when i try to start it with npm start.

**Comment by Christywl** [comment]
See this doc: http://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/

**Comment by rogerwang** [comment]
close as the guide covered it already.

**Comment by Bizarrus** [comment]
The sample included only informations with `index.html`, bro.

**Comment by rogerwang** [comment]
There is a highlight section named `Use JS File as Main`.
