### ISSUE TITLE
Window.getPrinters() returns a single printer object instead an Array of printers

### ISSUE THREAD

**Issue by ddcovery** [nwjs/nw.js#6667]
NWJS Version : 0.31
Operating System : Windows 7 (32 bits)

### Expected behavior

Callback function must receive an array of json objects representing the available printers

### Actual behavior

Callback function receives an unique object (1 printer) not an array of printers json objects.

### How to reproduce

This code must work:  enumerate printers and outputs to console the printer name.

```
win.getPrinters( function(printers){

  printers.map(printer=>console.log("Printer is", printer.printerName));

});
```

But a "printers.map is not a function" error is raised because "printers" is not an array.

**Comment by rogerwang** [comment]
Thanks for reporting. This is #6663 which was just fixed.
