### ISSUE TITLE
Program crashes when using JS binary, works with plain js

### ISSUE THREAD

**Issue by denigada** [nwjs/nw.js#6671]
I tried this with version 0.31.0, 0.30.5, 0.30.0. Same thing happens with all of them

When I use binary instead of js files, the app crashes on Windows, but it works on Mac. I get this debug on windows:

[0606/001527.387:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: The URL does not use a recognized protocol (0x2ee6)

I'm using this code to import the binary file, it perfectly works on Mac:
`<script> nw.Window.get().evalNWBin(null, 'enter.bin');</script>`

**Comment by Christywl** [comment]
I try a simple test and can't reproduce this issue on Windows with nwjs-sdk-v0.30.5 and v0.31.0.
enter.js: 
`console.log('hello');`
index.html:
`<script> nw.Window.get().evalNWBin(null, 'enter.bin');</script>`

The compiled code is not cross-platform nor compatible between versions of NW.js. You need compile the code for each version.

**Comment by denigada** [comment]
So I was building for Mac and windows using nwjs-builder-phoenix, now I created the bin files again in Windows and replaced the old .bin files that were created on Mac, it is still crashing

**Comment by denigada** [comment]
I fixed the issue by compiling the javascript files in Windows and using nwjs-builder-phoenix in windows to build the app
