### ISSUE TITLE
Can I make nwjs run fully offline?

### ISSUE THREAD

**Issue by lapsio** [nwjs/nw.js#6675]
When I launch nw.js it tries to connect to Google servers. It triggers firewall alerts in corporate isolated network as hosts should never perform any network requests.

Is it possible to disable this Google sync functionality?

**Comment by rogerwang** [comment]
The sync code can be disabled by `--disable-sync`. But we're not sure it's caused by the sync code in the first place. There are various places in Chromium codebase trying to access google services, and we'd like to disable them all. merge with #5865

**Comment by lapsio** [comment]
I used chromium-args to pass `--disable-sync` and it didn't help. nw.js still tries to connect.
