### ISSUE TITLE
Window.open undefined reference with https

### ISSUE THREAD

**Issue by jacobEAdamson** [nwjs/nw.js#6676]
NWJS Version : nwjs-sdk-v0.31.0-osx-x64
Operating System : OSX 10.13.4

### Expected behavior

When trying to open a window to a valid site, the Window.open callback should be called with a valid window reference.

### Actual behavior

For some sites, the window reference sent to the callback is undefined and/or unusable

### How to reproduce

The problem is reproducible by opening a fresh nwjs app instance, opening the developer console, and running this code:

```
nw.Window.open('https://accounts.google.com', (_win) => {
    console.log(_win);
});
```

The console will output undefined. Interestingly, running the code 

```
nw.Window.open('http://accounts.google.com', (_win) => {
    console.log(_win);
});
```

Will output the correct window object every time.

This bug is especially troublesome because it is breaking the use of google oAuth, and the urls generated from the google oAuth client cannot be loaded in a new window as intended. Hopefully this can be resolved swiftly.

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.31.1.


Same issue:
```
nw --url=https://accounts.google.com --> white screen
nw --url=http://accounts.google.com --> correct page
```

**Comment by rogerwang** [comment]
Ref: #6392

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
