### ISSUE TITLE
nw.App.closeAllWindows() crashes on Mac OSX

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6677]
NWJS Version : 0.30.5
Operating System : Mac OSX 10.12.6

### Expected behavior

Should just close all open windows and quit

### Actual behavior

crash, see dmp file:
[crash.dmp.zip](https://github.com/nwjs/nw.js/files/2086990/crash.dmp.zip)

### How to reproduce
Use the minimal sample:
[test_tray_closeAllWindows.zip](https://github.com/nwjs/nw.js/files/2086991/test_tray_closeAllWindows.zip)

1. run the included sample
2. click on the tray icon - open Main Window - window gets opened
3. click on tray icon - Close All Windows and Quit

app crashes.

It works just fine on Windows and Linux

**Comment by Christywl** [comment]
I can reproduce this issue on Mac with nwjs-sdk-v0.31.1.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
