### ISSUE TITLE
Deleting/rewriting file that is being used by nwjs(WINDOWS)

### ISSUE THREAD

**Issue by Jakovb** [nwjs/nw.js#6686]
Hello!

More of a question than an issue. Is it possible and how on earth, can I pause nwjs to stop accessing a file? (pause it in general, or just that file)

Let me explain. I have a file that is sqlite3 made by nwjs, however I want to delete this file when my game closes. I tried everything and unfortunately nothing works, libraries such as fs, fs extra etc. Thing is windows doesn't let the file be touched, so I cant even scramble the file into "Gibberish/Deleted". Basically nothing I can do since my app has to run the code to delete the file, and file can't be deleted if app is running.

Kinda-a hopeless, any ideas on how could this be worked-around?

Any help is much appreciated!

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by gwicksted** [comment]
Interesting challenge.  If you cannot solve cleanly within the nwjs environment, you could try spawning a detached [child_process](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to [rimraf](https://www.npmjs.com/package/rimraf) the file after waiting a few seconds.

How was the database created?
