### ISSUE TITLE
Webview steals focus preventing global key bindings from working (NW.js 0.29.x and above)

### ISSUE THREAD

**Issue by frankhale** [nwjs/nw.js#6695]
OS: Windows x64
NW.js: 0.29 - 0.31.x (using the SDK version)
NW.js: 0.28.x works fine

Imagine this scenario, you have an index.html that contains a webview. The index.html registers some key bindings that you want to be global across the entire app. You load in your content into the webview and if the webview become focused the global key bindings will no longer work until the webview is unfocused. This is new behavior in recent versions of NW.js and it definitely did not use to work this way in the past. 

Is there any way to work around this?

**Comment by frankhale** [comment]
If need by I can make a small project to reproduce the issues

**Comment by Christywl** [comment]
@frankhale , could you please upload your sample? thanks.

**Comment by frankhale** [comment]
Sure I will provide a sample tomorrow, thank you!

**Comment by frankhale** [comment]
okay example has been developed and will be posted shortly. This behavior started in the 0.29.x releases. 0.28.x is fine.

**Comment by frankhale** [comment]
Okay here is an example. When ran a webview will load the NW.js website into a webview that will occupy the full window. If you press the F1 key the webview will be hidden and a div on the parent page will be shown. Even if you focus the webview the F1 key binding should still work. This works great in the 0.28.x branch but stopped working in the 0.29.x branch. 

In 0.29.x and above if the webview is focused the key bindings that were put on the parent page will stop working. In 0.28.x (and below) they still work.


package.json

```javascript
{
  "name": "helloworld",
  "main": "index.html"
}
```

index.html

```html
<!DOCTYPE html>
<html>

<head>
  <title>Hello World!</title>

  <style>
    html,
    body {
      overflow: hidden;
    }

    #parentContent {
      display: none;
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      font-weight: bold;
      font-size: 32pt;
    }

    #webview {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
  </style>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>

  <script>
    window.onkeydown = function (e) {
      // PRESS F1 key to hide webview and show a div at the parent page level
      if (e.keyCode === 112) {
        console.log("F1 was pressed");

        if ($("#parentContent").css("display") === "none") {
          $("#parentContent").css("display", "block");
          $("#webview").css("display", "none");
        } else {
          $("#parentContent").css("display", "none");
          $("#webview").css("display", "block");
        }
      }
    }
  </script>
</head>

<body>
  <div id="parentContent">
    This content is at the parent page level
  </div>
  <webview id="webview" src="https://nwjs.io"></webview>
</body>

</html>
```

**Comment by Christywl** [comment]
I can reproduce this issue on Linux/Windows with nwjs-sdk-v0.31.2.

**Comment by frankhale** [comment]
@Christywl if you try 0.28.3 it should work fine, can you try that?

**Comment by Christywl** [comment]
Yes, it works fine with v0.28.3.

**Comment by frankhale** [comment]
Thank you!

**Comment by frankhale** [comment]
I know it hasn't specifically been addressed yet but I wanted to mention that it's also a problem in NW.js 0.31.3 that was just released.

**Comment by frankhale** [comment]
I know there hasn't been any commentary on this recently but NW.js 0.31.4 that was just released suffers from the same issue. Just an FYI. Thank you for being very proactive on releases that correspond with Chrome / Node releases.

**Comment by rogerwang** [comment]
@Christywl Does Chrome have this issue with Chrome App or extension?

**Comment by frankhale** [comment]
Seems to only be a problem with recent versions of NW.js. Electron doesn't seem to suffer from the webview stealing focus which prevents global key bindings from working. I prefer NW.js over Electron and would really LOVE if this would get some attention =)

**Comment by frankhale** [comment]
I'm mistaken, sorry about that. Doesn't look like defining key handlers using https://github.com/madrobby/keymaster works the same as it used to in previous releases of Chromium. I'll look to see if there is some other way you can define a global key handler that will never lose focus. Looks like behavior is exactly the same in Electron as it is in NW.js. My mistake.
