### ISSUE TITLE
nwjc: segmentation fault compiling es6 module

### ISSUE THREAD

**Issue by alxproject** [nwjs/nw.js#6697]
NWJS Version : 0.31.2
Operating System : Linux amd64

### Expected behavior

Successful compile module when using
nwjc --nw-module lib.js lib.bin

### Actual behavior

segmentation fault when using the above command

### How to reproduce

If the module contains a dynamic import nwjc cannot compile it

Example work correctly 
lib.js
```
export function myfunction(mypath) {
  console.log('this can be compiled without problem');
}
```

This fail to compile
lib.js
```
export function myfunction(mypath) {
  console.log('this cannot be compiled');
  import('dynamiclib.js').then((module) => {
    console.log('module loaded');
  }).catch((err) => {
    console.log('module not loaded');
  });
}
```

The code works perfectly without compile it. Only including import() make nwjc fail to compile.

**Comment by rogerwang** [comment]
merge with #6303 thanks.

**Comment by alxproject** [comment]
But, in my case, nwjc --nw-module works correctly, it can compile modules without problem, the only problem is when the module includes a dynamic import

**Comment by rogerwang** [comment]
Yes. That's exact the case #6303 was re-opened to track: https://github.com/nwjs/nw.js/issues/6303#issuecomment-361809189

**Comment by alxproject** [comment]
You are right, thanks :)
