### ISSUE TITLE
Windows 10 Update - Error loading extension

### ISSUE THREAD

**Issue by sadikyalcin** [nwjs/nw.js#6700]
NWJS Version : 0.29.1
Operating System : Windows 10

### Expected behavior

Application to start with the default locale set which is "en"

### Actual behavior

The app doesn't start. "Error Loading Extension"

### How to reproduce

- Create a simple app with _locales
- Set default locale in manifest: `"default_locale": "en",`
- Launch application

The app has been working fine for over a year. A recent windows update has broken things I suppose. Any quick way of solving this since re-installing does not work. Upgrading nwjs is my last option as I have no automatic way of distribution. Well perhaps even upgrading nwjs might not work?!

![image001](https://user-images.githubusercontent.com/8109619/41711614-6bcfbe0c-7540-11e8-8bc7-0ef780eb31c1.png)

**Comment by Christywl** [comment]
Could you please upload your sample to reproduce this issue?

**Comment by sadikyalcin** [comment]
I can't upload actual code as company policy but created a little demo. I have solved it now but  don't really know how / why. I would like to know if you can replicate this and the actual solution.

`index.html`
`_locales`
`-- en`
`-- --messages.json`
`manifest.json`

You can run the app via the nw.exe without a problem. But if you create an executable you should see the error on launch.

1. Use enigma virtual box to create an example from the below (use pre v6 to replicate it - [versions](http://enigmaprotector.com/en/downloads/changelog.html)
2. Run the executable

The error should be replicated.

I noticed there is a locale folder for nw - which I thought there may be a conflict somehow but I don't know. Didn't make sense for me.

How I solved it:

1. Updated enigma virtual box [(latest builds)](http://enigmaprotector.com/en/downloads.html)
2. Renamed `manifest.json` to `package.json` - the manifest was from the chrome app (this was previously a chrome app).

The app still works on Win 8 and (should) work on Win 7.

[sample.zip](https://github.com/nwjs/nw.js/files/2127190/sample.zip)

**Comment by Christywl** [comment]
@rogerwang , the sample is a chrome app, and per the reporter said, it ran well via nw.exe directly. But it had a problem after packaging. 
Could you please help confirm ? Is this nwjs issue? Or a package tool issue?

**Comment by rogerwang** [comment]
@Christywl could you reproduce it? Chrome app is supported in NW.

**Comment by Christywl** [comment]
If I start the sample by nw directly, it also works fine for me. I'll try to reproduce this by the packaging tool(enigma virtual box) later.

**Comment by rogerwang** [comment]
If it's enigma virtual box then the issue should be reported to enigma virtual box.

**Comment by sadikyalcin** [comment]
@Christywl any ideas then mate? It would be good to know what the cause actually is - don't want to run into this again. I'm going to try renaming `package.json` to `manifest.json` to see if that breaks it again.
