### ISSUE TITLE
OSX - 0.32.0b1 App crashes when textbox selected

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6701]
OSX 10.13.5 High Sierra
NW.js 0.32.0b1-sdk

Attached is wee test app - basically after the first POST/submit is done if a textbox is selected the app will crash with a trap 14 error.
Issue only occurs with 0.32.0b1 it is OK with 0.31.3 and earlier.
0.31.3 node 10.5.0
0.32.0b1 node 10.4.1

Cheers

[POST-Test3 crash.zip](https://github.com/nwjs/nw.js/files/2127063/POST-Test3.crash.zip)

[chrome_debug.log](https://github.com/nwjs/nw.js/files/2127064/chrome_debug.log)

[crashontextbox.txt](https://github.com/nwjs/nw.js/files/2127065/crashontextbox.txt)

**Comment by rogerwang** [comment]
Thanks for reporting! 👍 
This is just fixed in git and will be available in the next nw32 build.
