### ISSUE TITLE
Cannot execute binary file, format error on Raspian

### ISSUE THREAD

**Issue by quantumproducer** [nwjs/nw.js#6703]
NWJS Version : 0.31.3
Operating System : Raspian

Update: I tried running node Desktop/MyFolder/MyExecutable .  I get

(function (exports, require, modulue, __filename, __dirname) { ?ELF???

Syntax error: Unexpected token ILLEGAL
...at nodejs:1043:3

The ? are characters that looks like little numbers in a box. They overlap with the character to their right.
I tried both 32 and 64 bit versions. I updated node to 10.X. Trying with the sample project from dl.nwjs.io/v0.31.3

**Comment by rogerwang** [comment]
merge with #193

**Comment by quantumproducer** [comment]
Thank you
