### ISSUE TITLE
crash 'http_transport_win.cc(175) WinHttpCrackUrl'

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#6706]
hi, last version not work for me.
The nw.js sdk does not boot !

debug.log:
`[0625/233523.307:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: L’URL n’utilise pas un protocole reconnu (0x2ee6)`

![image](https://user-images.githubusercontent.com/24865815/41887971-1cbcc3fc-78d1-11e8-9cd0-fccbb87dfef1.png)

![image](https://user-images.githubusercontent.com/24865815/41888093-ac3b7686-78d1-11e8-850f-7eac251a57bc.png)

thank

i try 2 version
 **0.31.3**
and the beta 
**0.32.0.b1**

**Comment by djmisterjon** [comment]
**after more deep test,** 
the v 0.30.5 / 05-18-2018
work fine for me.

**but if i update to** 
0.31.0 / 05-30-2018
nwjs doesn't start!
so issue are maybe from those changes ?

- Update Chromium to 67.0.3396.62
- Add nw.App.startPath to query the directory where the app starts. (#648)

thank a lot guys for help

**Comment by Christywl** [comment]
Could you please upload a sample to reproduce this issue?

**Comment by djmisterjon** [comment]
sample? , hum, i use version clean version downloaded from your website.
I also open tread here with more info , i made more test.
Something change , and made virtual environment can run it or other.
https://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=25928

am very not sure what happened between those update 
v 0.30.5 
0.31.0

maybe it the chromium ?
what do you think about ?

**Comment by acemod13** [comment]
I have a similar issue with this. Although it happens when I try to load a javascript file (after I compiled them with nwjc and putting the appropriate calls). I've included the Crashpad files.

[Crashpad.zip](https://github.com/nwjs/nw.js/files/2259594/Crashpad.zip)

**Comment by djmisterjon** [comment]
for me its fixed now .
Dev fix it.

Chromium 67 issues were addressed with the last release of Sbie 5.26 
Please download the latest version --> https://www.sandboxie.com/DownloadSandboxie
Then, create a new Sandbox with default settings (Sandbox--> Create new Sandbox---> give it a name, ensure the bottom dropdown to copy settings is set to "none" ) 
Download your program to that Sandbox and re-test.
