### ISSUE TITLE
Transparent clickthrough window

### ISSUE THREAD

**Issue by ihack2712** [nwjs/nw.js#6708]
NWJS Version : SDK 0.31.3
Operating System : Windows 10 1803 17134.112

### Expected behavior

A transparent window, click-through. Even when pixel doesn't have alpha 0.

### Actual behavior

Creates a transparent click-through window, not click-through when mouse over pixel that doesn't have alpha 0.

### How to reproduce

package.json
```json
{
  "name": "crosshair",
  "version": "1.0.0",
  "description": "crosshair.",
  "main": "crosshair.html",
  "license": "MIT",
  "window": {
    "transparent": true,
    "frame": false,
    "kiosk": false,
    "show": true,
    "show_in_taskbar": false,
    "fullscreen": false,
    "always_on_top": true,
    "resizable": false,
    "position": "center",
    "width": 1920, "height": 1080
  },
  "scripts": {"start": "./nw.exe . --disable-gpu --force-cpu-draw"}
}
```

crosshair.html
```html
<html><head><meta charset="utf-8"/><style>body,html{display:flex;width:100%;height:100%;margin:0;padding:0;justify-content:center;align-items:center}.container{display:block;width:calc((1px * 4) + (((5px / 1.5) + 1px) * 2) + (10px * 2));height:calc((1px * 2) + (5px * 2) + (10px * 2) + 2px)}.line{display:block;border:1px solid #000;background:#C7EA46}.line.y{width:2px;height:10px}.line.x{width:10px;height:2px;float:left}.col-col,.row{width:100%}.row{display:flex;height:calc((1px * 2) + 10px);justify-content:center}.row-spacer{display:block;width:100%;height:calc(5px / 2)}.col-col,.col-spacer{display:block;height:calc((1px * 2) + 2px)}.col-spacer{float:left;width:calc((5px / 1.5) + 1px)}</style></head><body style="background:rgba(0,0,0,0)"><div class="container"><div class="row"><div class="line y"></div></div><div class="row-spacer"></div><div class="col-col"><div class="line x"></div><div class="col-spacer"></div><div class="col-spacer"></div><div class="line x"></div></div><div class="row-spacer"></div><div class="row"><div class="line y"></div></div></div></body></html>
```

**Comment by Christywl** [comment]
transparency clickthrough works fine for me with your sample on Windows 10 with nwjs-sdk-v0.31.3.

**Comment by Christywl** [comment]
Click a part of the crosshair:

![image](https://user-images.githubusercontent.com/20039821/42014183-7ad4b77a-7ad3-11e8-80e7-ff7f2d5e19a4.png)

**Comment by tphalp** [comment]
So, this example works for me on nwjs-sdk-v0.31.1 (osx64). The click-through to a window behind the transparent part does indeed work. 

But the same example no longer allows click-through on nwjs-sdk-0.36.2 (osx64). If I try clicking on a background window, through the nwjs example app, it does not register.

Seems like this has been broken in some subsequent update.

**Comment by Blatman** [comment]
Just had a look with 0.36.3-sdk on 10.13.6 and indeed it looks like click-through is broken on OSX.
Tried it with/without nw2 switch and failed both cases and was using the --disable-gpu-compositing method. Have not tried the Win versions as per OP.
Cheers.

**Comment by rogerwang** [comment]
@jtg-gg would you have time to take a look?

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/136

**Comment by rogerwang** [comment]
@jtg-gg thanks for the quick fix!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
