### ISSUE TITLE
How to resue user-data-dir or safely delete it in case of multiple instances 

### ISSUE THREAD

**Issue by dalidong2009** [nwjs/nw.js#6711]
my ENV :  
os  windows 2012 server
nw version :  nwjs-sdk-v0.27.5-win-x64
I want to open nw app  multiple instances in a PC . so I use the command line parameter --user-data-dir which value is a random directory. As I open nw app much time, the file system gets  more and more --user-data-dir . Whether here has some method  to check the --user-data-dir is not being used, so I can reuse it at next tiem nw app start, or delete it .
Here has another problem for me , that is data in localStorage or indexedDB could not be reused at next time, because the next time nw app start use another user-data-dir .

**Comment by Christywl** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Arti3DPlayer** [comment]
Why do you need multiple user dirs ? Why you can create dir for each session inside user-data-dir and remove it with 'close' event.
