### ISSUE TITLE
Centos 6.9 Build Successful but hacky and unable to run hello world app

### ISSUE THREAD

**Issue by evbo** [nwjs/nw.js#6718]
Trying my best at Following the build [docs](http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/) for `Centos 6.9`, I managed to successfully build, but I ended up making a lot of hacky changes and when I go to run the [hello world](https://github.com/nwjs/nw.js/wiki/Getting-Started-with-nw.js?utm_source=qdan.me) example app, it still fails.

My question is two-fold: Is my approach for building correct and if so, why am I still unable to run nwjs hello world?

Here are my steps:
here are the repos that I cloned [for support with centos 6](https://groups.google.com/forum/#!topic/nwjs-general/rFN977MDgn4):
```
git clone -b nw12 https://github.com/nwjs/nw.js.git src/content/nw
git clone -b nw12 https://github.com/nwjs/node.git src/third_party/node-nw
git clone -b nw12 https://github.com/nwjs/v8.git src/v8
```

I chose to sync with hooks so that I knew which dependencies I was missing and needed to install, but the sync at first fails when trying to use `depot_tools` third_party binary "gsutil". That is because the master branch of `depot_tools` (no longer?) includes that binary:

https://chromium.googlesource.com/chromium/tools/depot_tools/+/master/third_party/

So, I obtained the binary elsewhere [from here](https://storage.googleapis.com/pub/gsutil.tar.gz) and placed it in my `depot_tools/third_party` directory.

Then it's failing with the following [due to this issue](https://codereview.chromium.org/2378683002):
```
depot_tools/third_party/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
CommandException: option --bypass_prodaccess not recognized
```

So I filter out the argument inside the gsutils `__main__.py` file and am able to get past that issue: `sys.argv = filter(lambda arg: arg != "--bypass_prodaccess", sys.argv)`

Then as expected I had to install a bunch of dependencies (since I'm not using ubuntu and therefore couldn't run the provided install-deps script) and I reach this failure after runnning `ninja -C out/Release nw -j4`:

```
-c ../../net/third_party/nss/ssl/ssl3con.c -o obj/net/third_party/nss/ssl/libssl.ssl3con.o
../../net/third_party/nss/ssl/ssl3con.c:2091:16: error: no member named 'pIv' in 'struct CK_NSS_AEAD_PARAMS'
    aeadParams.pIv = (unsigned char *) additionalData;
    ~~~~~~~~~~ ^
../../net/third_party/nss/ssl/ssl3con.c:2092:16: error: no member named 'ulIvLen' in 'struct CK_NSS_AEAD_PARAMS'
    aeadParams.ulIvLen = 8;
    ~~~~~~~~~~ ^
2 errors generated.
```

Although hacking chromium c code has a bad smell, I was still very fortunate to find this hack and it worked!: https://www.linuxquestions.org/questions/slackware-14/error-installing-qt5-from-sbo-4175577061/

Finally, after the build successfully completes, I use the sample hello world nwjs project and try running it with `./nw .` I get:
```
./nw .
[10134:0701/190652:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[10136:0100/000000:ERROR:zygote_linux.cc(585)] write: Broken pipe
```

**Comment by evbo** [comment]
here are the repos that I cloned for support with centos 6:
```
git clone -b nw12 https://github.com/nwjs/nw.js.git src/content/nw
git clone -b nw12 https://github.com/nwjs/node.git src/third_party/node-nw
git clone -b nw12 https://github.com/nwjs/v8.git src/v8
```

**Comment by rogerwang** [comment]
It seems that you are building 0.12. Unfortunately we don't support that version any more.

**Comment by evbo** [comment]
I used 0.12 because I thought it was the only version that might support CentOS 6. Or is that not true?

**Comment by rogerwang** [comment]
It's probably true. But I'm afraid we don't support the old version any more.
