### ISSUE TITLE
How to reduce build size on Centos 6

### ISSUE THREAD

**Issue by evbo** [nwjs/nw.js#6719]
I've managed to build nwjs on Centos 6, but the resulting binary is huge! nw binary alone is 1.5 GB. How can I get this to a manageable size? [Here is an outline of my build steps](https://github.com/nwjs/nw.js/issues/6718).

```
du -a . | sort -n -r | head -n 10
7172136	.
5133660	./obj
2756728	./obj/third_party
2161072	./obj/third_party/WebKit
2161044	./obj/third_party/WebKit/Source
1604992	./obj/third_party/WebKit/Source/core
1530052	./nw
582000	./obj/content
543072	./obj/v8
534996	./obj/v8/src
```

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
