### ISSUE TITLE
setProgressBar crash on MacOS Mojave

### ISSUE THREAD

**Issue by jtg-gg** [nwjs/nw.js#6720]
NWJS Version : 31.4
Operating System : MacOS Mojave

### Expected behavior

setProgressBar should NOT crash in MacOS Mojave

### Actual behavior

setProgressBar(0.5) crash nwjs in MacOS Mojave

### How to reproduce

run nwjs in MacOS Mojave
open devtools, copy paste this script into the devtools console
```
var win = nw.Window.get()
win.setProgressBar(0.5)
```

**Comment by jtg-gg** [comment]
@rogerwang I've made the fix here https://github.com/nwjs/nw.js/pull/6716

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
