### ISSUE TITLE
Windows array empty in chrome.windows.getAll()

### ISSUE THREAD

**Issue by McGiverGim** [nwjs/nw.js#6724]
NWJS Version : 0.31.4
Operating System : Windows 10

### Expected behavior

The method `chrome.windows.getAll()` must pass an array of windows to the function received as parameter. More info here: https://developer.chrome.com/extensions/windows#method-getAll

### Actual behavior

The array of windows is empty. It does not contain any window (neither the current window).

*This method worked in version 0.29.4, but since 0.30.0 it does not work.*

### How to reproduce

Execute the method. For example:
```
chrome.windows.getAll(function(windows) {
    ...
});
```

The windows variable contains 0 windows since version 0.30.0.

**Comment by McGiverGim** [comment]
The same seems to happen to the method:
```
chrome.windows.getCurrent(function(currentWindow) {
    currentWindowId = currentWindow.id;
});
```

The `currentWindow` is undefined.

**Comment by tolrtd** [comment]
+1 for a fix for this; this is necessary for any application with child windows.

**Comment by tolrtd** [comment]
This appears to be happening when new_instance: true is set while opening a new child window.  Still broken on 0.33.

**Comment by rogerwang** [comment]
This would depends on #5875 as currently there is no chrome.window in the app -- the windows are Chrome App windows.  Try https://developer.chrome.com/apps/app_window#method-getAll

**Comment by rogerwang** [comment]
merge with #5875 as it's expected within the current situation.

**Comment by tolrtd** [comment]
If I open a window with new_instance: true, though, it is not showing up in the list of chrome.app.windows - how can I access these?
