### ISSUE TITLE
nwjs doesn't run: CoreBluetooth library not loaded

### ISSUE THREAD

**Issue by pineapplemachine** [nwjs/nw.js#6725]
NWJS Version : Latest (v0.31.4)
Operating System : OS X 10.9.5

### Expected behavior

My WIP NW.js app should run successfully as it does on Windows.

### Actual behavior

```text
sophie:hyperlink pineapple$ nw .
dlopen /Users/pineapple/nwjs/nwjs-v0.31.4/nwjs.app/Contents/MacOS/../Versions/67.0.3396.99/nwjs Framework.framework/nwjs Framework: dlopen(/Users/pineapple/nwjs/nwjs-v0.31.4/nwjs.app/Contents/MacOS/../Versions/67.0.3396.99/nwjs Framework.framework/nwjs Framework, 257): Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
  Referenced from: /Users/pineapple/nwjs/nwjs-v0.31.4/nwjs.app/Contents/Versions/67.0.3396.99/nwjs Framework.framework/Versions/A/nwjs Framework
  Reason: image not found
Abort trap: 6
```

### Workaround

I already had to debug [an identical issue](https://github.com/electron/electron/issues/13404#issuecomment-401406040) with electron@2.0.3. (In the end I downgraded to electron@2.0.2 to solve another problem, which incidentally also solved this one when I tried reversing the workaround.)

```text
sudo ln -s /System/Library/Frameworks/IOBluetooth.framework/Frameworks/CoreBluetooth.framework /System/Library/Frameworks/CoreBluetooth.framework
```

**Comment by rogerwang** [comment]
I'm afraid that the latest Chromium version doesn't support OSX 10.9 any more. It requires at least 10.10.

**Comment by pineapplemachine** [comment]
What version of nwjs should I revert to if I want to support OSX 10.9?

**Comment by rogerwang** [comment]
Chromium dropped the support in M65. So NW.js 0.28 with Chromium 64 should be used. See #6573

**Comment by pineapplemachine** [comment]
Got it. Thanks for your help!

Worth noting for anyone else who tries to run latest on OSX 10.9 - The workaround is holding so far. I'm getting some warnings in the sdk log but the app is functioning as expected.
