### ISSUE TITLE
OAuth is not working in nwjs(0.31.3)

### ISSUE THREAD

**Issue by gurunadh5** [nwjs/nw.js#6728]
During oauth, i am getting the  something went wrong  from google.
![image](https://user-images.githubusercontent.com/3523873/42550990-892f32a4-84f2-11e8-83e4-f1502180c005.png)
I tried the oauth in latest verison of nw.js(0.31.5) also.i received same error.Please help me to resolve this issue.

**Comment by Arti3DPlayer** [comment]
I don't think it is nw.js issue

**Comment by gurunadh5** [comment]
I tried to open the gmail site also. It showed the same error.

**Comment by gpetrov** [comment]
Maybe related to just setting the **web_accessible_resources** for the oauth redirect just like explained in https://github.com/nwjs/nw.js/issues/6631

**Comment by ncnlinh** [comment]
Spent half a day to resolve this.
This issue origins from https://bugs.chromium.org/p/chromium/issues/detail?id=829220
The solution that I found is to set chrome://flags#account-consistency to "Enable Dice fix..." or "Disabled"
It's an experimental feature that broke the sign in. Perhaps our maintainer can do something about this?

**Comment by ncnlinh** [comment]
Also, it broke from 0.31.0 onwards (Chromium 67 onwards)

**Comment by GnorTech** [comment]
Fixed in nw32 branch and will be available in the next nightly build. Thanks to @ncnlinh for the findings!

**Comment by josh83abc** [comment]
Hello! On NWJS 0.42, I got the same error as in this post. Google Oauth gives "something went wrong". I tried a few things I found in here for 3 hours, but no change at all... Anyone using Google Oauth in his app?
