### ISSUE TITLE
NW.js v0.30.0+ Video Media Playback Causes Apphang/Appcrash

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#6730]
**General Information:**
- Using NW.js version 0.30.0 & newer
- Windows 7 with latest drivers
- Repo NWjs: [Package.nw](https://drive.google.com/uc?export=download&id=1INghKb_XZdH6GPLqgZRGbvGko_JYUtqk) (unzip before use)
- Repo Chrome: [Chromeapp](https://drive.google.com/uc?export=download&id=1FGui4YqQErZ2gjZWO2GhVex0gsU7MllH) (unzip and run in _chrome://apps/_)

**Problem Description:**
I'm running a packaged _Construct 2_ game (HTML5).
I've recently noticed an issue with WebM autoplay bringing my PC to its limit and crashing because of a possible memory leak within NWjs. I could not reproduce this in NWjs versions before v0.30.0 so it's safe to assume that something that got implemented in v0.30.0 is at fault.

Chromium itself doesn't seem to be at fault since I wasn't able to reproduce this using the Chromeapp and Chrome M67. I personally suspect that there is something going wrong in the autoplay policy workaround inside NWjs, at least that's the only major "new feature" that got shipped with M66.

**Steps to reproduce (instance issue):**
<1> Run the attached package.nw file using NW.js v0.30.0 or newer (AUDIO WARNING!)
<2> Let the WebM autoplay for at least 10sec.
<3> Notice heavy performance problems followed by an apphang leading to an appcrash

**Observed Result**
Autoplaying a WebM in NWjs v0.30.0+ is resulting in performance problems and a sudden crash, possibly caused by a memory leak.

**Expected Result**
The WebM should play fine like it does in Chrome or NWjs versions before v0.30.0 (tested using v0.29.0).

**Comment by TheRealDannyyy** [comment]
@rogerwang I'd really appreciate if you could look into this soon. It's a fairly critical issue, stopping a lot of Construct 2 users from using more recent versions of NWjs.

**Comment by GnorTech** [comment]
I can't reproduce it with the windows system here.

**Comment by GnorTech** [comment]
The sample runs well. No problems found as described in step 3.

**Comment by TheRealDannyyy** [comment]
@GnorTech What Nwjs version did you use? Maybe some specfic versions of NWjs aren't affected by this.

**Comment by GnorTech** [comment]
0.31.5.

**Comment by avishaymizrav** [comment]
I got the same issue on windows 10 pro 64b, build 17134.

**Comment by GnorTech** [comment]
Which NW process consume huge memory? Please look for `--type=` switch in the process full command line.

**Comment by TheRealDannyyy** [comment]
@GnorTech I'm not sure what that means. Add "--type=" as a command line and execute NWjs?

**Comment by avishaymizrav** [comment]
I also didn't understand, if you're asking if there's a "--type" arg defined in the package.json, then no.

About the process, I'm not sure why, but sometimes it runs with 4 process and sometimes with 5 process, I'm not show how to differentiate the processes, but it looks like it's always one before the last.
3rd process if there are 4, and 4th if there are 5.

**Comment by GnorTech** [comment]
I am asking `Which NW process consume huge memory?`. You can tell the difference by looking at the full command line in the detail processes view in windows task manager, looking for `--type` argument in it.

**Comment by avishaymizrav** [comment]
@GnorTech OK got it, it's the gpu-process type that's causing the issue.

**Comment by GnorTech** [comment]
Could you upload the content of 'chrome://gpu' from both Chrome browser and NW.js 0.31.5? In the latter case you can get it by launching nw with `--url=chrome://gpu`.

**Comment by avishaymizrav** [comment]
Sure, here you go

[chrome gpu.pdf](https://github.com/nwjs/nw.js/files/2218016/chrome.gpu.pdf)
[chrome gpu.docx](https://github.com/nwjs/nw.js/files/2218017/chrome.gpu.docx)

**Comment by TheRealDannyyy** [comment]
Here are my results as well:
[Chrome GPU.pdf](https://github.com/nwjs/nw.js/files/2218322/Chrome.GPU.pdf)

**Comment by GnorTech** [comment]
I see one of the differences is that the 'checker imaging' feature is turned on in NW.js. So does it make any difference if you add `--disable-checker-imaging` to the command line?

**Comment by TheRealDannyyy** [comment]
Can still reproduce with --disable-checker-imaging. Something else must be the cause.

**Comment by GnorTech** [comment]
In your `package.json`, please try removing `--ignore-gpu-blacklist`

**Comment by avishaymizrav** [comment]
Still happens here after removing --ignore-gpu-blacklist

**Comment by TheRealDannyyy** [comment]
Same for me, can still reproduce.

**Comment by GnorTech** [comment]
Is it specific to video encoded in WebM? What about video with other codecs.

**Comment by avishaymizrav** [comment]
No, my project is using OGV files and I have the same issue.

**Comment by TheRealDannyyy** [comment]
I cannot reproduce this issue using the most recent stable release of NW.js (v0.32.0).
@avishaymizrav Can you confirm this on your end as well?

**Comment by avishaymizrav** [comment]
Yeah, it's OK now!

**Comment by TheRealDannyyy** [comment]
Seems like the issue fixed itself. Closing for now.
Will reopen if someone else experiences this in NW.js v0.32.0+ again.

**Comment by xczpw** [comment]
I find it's relevant to GPU hardware acceleration.
When I add "--disable-gpu" into "chromium-args", the client seems OK. 
My NW version is 0.31.2.
