### ISSUE TITLE
Screen.DesktopCaptureMonitor crashes on v0.31+

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#6731]
NWJS Version : 0.31.5
Operating System : Elementary OS (also happens on Ubuntu 16.04)

### Expected behavior
It's not supposed to crash haha.

### Actual behavior
The very moment you run `dcm.start(true, true);` the whole App crashes

### How to reproduce

Run the default example code from the Screen section in the docs under `Screen.DesktopCaptureMonitor`:

`var dcm = nw.Screen.DesktopCaptureMonitor;
nw.Screen.Init();
dcm.on("added", function (id, name, order, type) {
   //select first stream and shutdown
   var constraints = {
      audio: {
         mandatory: {
             chromeMediaSource: "system",
             chromeMediaSourceId: dcm.registerStream(id)
          }
      },
      video: {
         mandatory: {
             chromeMediaSource: 'desktop',
             chromeMediaSourceId: dcm.registerStream(id)
         }
      }
  };

  // TODO: call getUserMedia with contraints

  dcm.stop();
});

dcm.on("removed", function (id) { });
dcm.on("orderchanged", function (id, new_order, old_order) { });
dcm.on("namechanged", function (id, name) { });
dcm.on("thumbnailchanged", function (id, thumbnail) { });
dcm.start(true, true);`

Here is the error log from the terminal:

`[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
nw: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted (core dumped)
[19615:19615:0717/220806.211265:FATAL:font_cache.cc(401)] Check failed: false. 
#0 0x7ff5a1b2b66c <unknown>

Failed to tell parent about crash.
Received signal 6
#0 0x7ff5a1b2b66c <unknown>
  r8: 00007ff59e38e770  r9: 00007ff5a612ca80 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffd3b2b81b8 r13: 000000000000004f r14: 00007ffd3b2b81c0 r15: 00007ffd3b2b7ce9
  di: 0000000000004c9f  si: 0000000000004c9f  bp: 00007ffd3b2b7c90  bx: 00007ffd3b2b7d00
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007ff59dffd428  sp: 00007ffd3b2b7b58
  ip: 00007ff59dffd428 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]`

There is also this line that shows up before the App launches, but seems like a regular error, generally works even with this error (i.e even before executing or commenting out `dcm.start(true, true);`):
`[19565:19565:0717/220805.463642:ERROR:gpu_process_transport_factory.cc(1022)] Lost UI shared context.`

Edit: I want to point out that `Screen.chooseDesktopMedia (sources, callback)` does work, but it has that chrome share window and would like to not have that.

Hopefully that all helps!

**Comment by polhaghverdian** [comment]
I have exactly they same problem. 

But if i use for example:  dcm.start(false, true); or  dcm.start(true, false); it works.
