### ISSUE TITLE
Certificate error on https://docs.nwjs.io/

### ISSUE THREAD

**Issue by Munter** [nwjs/nw.js#6739]
Visiting https://docs.nwjs.io/en/latest/ results in a certificate error:

![image](https://user-images.githubusercontent.com/331790/43195465-6e579d72-9005-11e8-9b74-1d6e2424ba66.png)

It would be nice if https: worked and if http: redirected to that secure channel

**Comment by rogerwang** [comment]
Blocked on https://github.com/rtfd/readthedocs.org/issues/2652

**Comment by Munter** [comment]
Not stale, just blocked
