### ISSUE TITLE
Override Chromium Arguments from Command Line

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#6740]
I'm using "chromium-args" : "--disable-gpu-vsync" in my project, as I've noticed that vsync causes input lag at lower framerates. Unfortunately on some systems this causes issues (white screen:   #https://github.com/nwjs/nw.js/issues/6641). So it would be great if I could specify some arguments from command line to override this setting.

e.g. devader.exe -chromium-args --disable-gpu-vsync=0

or something like that. Any ideas how I could go about this problem?

**Comment by bluthen** [comment]
I personally use something like a bootstrapper that sets up other services then calls nw.exe with whatever arguments I want (or pass through ones I want). Probably not a good solution for everyone.

I'm not familiar with the builders, but I would have expected it to pass through arguments (or an option to allow that during). Just sending --disable-gpu-vsync doesn't work huh?
