### ISSUE TITLE
nw-headers for 0.32.0 are 403 on Amazon S3

### ISSUE THREAD

**Issue by fusionstream** [nwjs/nw.js#6743]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.32.0 X64 SDK
Operating System : Windows so far

### Expected behavior

I should not be getting a 403 error when "npm install"-ing with --build-from-source

### Actual behavior

I get a 403 error when "npm install"-ing with --build-from-source

### How to reproduce
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.32.0
This commands results in a multiline error, with the relevant line being: Error: 403 response downloading http://node-webkit.s3.amazonaws.com/v0.32.0/nw-headers-v0.32.0.tar.gz

Browsing to this url also produces a 404 error.

**Comment by DimPaDev** [comment]
same for 0.32.1. the last working nw-headers url are for 0.31.5 and can be found here : 
[http://node-webkit.s3.amazonaws.com/v0.31.5/nw-headers-v0.31.5.tar.gz](url)
I hope @rogerwang fixes this soon

**Comment by GnorTech** [comment]
Fixed.
