### ISSUE TITLE
Vue-devtools not working

### ISSUE THREAD

**Issue by fprijate** [nwjs/nw.js#6744]
======== TEMPLATE BUG FORM ========

NWJS Version : nwjs-sdk-v0.32.0-win-x64
Operating System : win10

### Expected behavior
Vue-devtools should work

### Actual behavior

error: Proxy injection failed
![nwjs](https://user-images.githubusercontent.com/1025131/43363035-e9fb74d8-92fa-11e8-911d-37f5c4f85aff.png)

### How to reproduce
[test.zip](https://github.com/nwjs/nw.js/files/2238528/test.zip)

- Unzip test.zip to some folder
- cd to  selected folder
-  npm install
-  npx nw .

**Comment by Mxkkxa** [comment]
Having the same issue. I could reproduce this.

**Comment by DimPaDev** [comment]
I think It's a permission issue related to the chrome extension. I had this problem too so I added a new permission url pattern in the manifest.json of the extension and now It's working just fine : 

`   "permissions": [ 
     "http://*/*", 
     "https://*/*", 
     "file:///*", 
     "contextMenus" ,
     "*://*/*"
    ]`

**Comment by Mxkkxa** [comment]
Also a reminder for everyone out there, you must have Vue.config.devtools = true; for Vue tab to appear.

**Comment by TheJaredWilcurt** [comment]
@fprijate @Mxkkxa @DimPaDev 

@masterjg's fix has been merged into `nw-vue-devtools` and a new release (1.3.0) has been published to npm. Closing this issue.
