### ISSUE TITLE
NWJS is not responding on Linux systems when I use it with Web Workers

### ISSUE THREAD

**Issue by trofivan** [nwjs/nw.js#6746]
NWJS Version: v.0.32.1 (Tested on different 0.31 versions also and 0.32.beta)
Operating System: Linux only. Tested on Ubuntu 16.04 LTS x64 and Elementary OS 0.4.1 Loki x64

### Expected behaviour

The program must respond.

### Actual behaviour

The program not responding and if I break it (`Ctrl + C`) i seen in console that messages: 
```
[14399:14410:0802/142733.750943:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)
[14399:14410:0802/142733.761023:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)
[14399:14409:0802/142733.761203:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)
[14399:14409:0802/142733.761402:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)
[14399:14409:0802/142733.761801:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)
[14399:14410:0802/142733.761896:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)
```
But if I'am using `nwjs-builder-phoenix` and running SDK - working correctly.

### Prepare
1. Download and extract fake data to parsing: https://github.com/trofivan/myq-jobs-archive-parser/releases/download/v0.1.0/fake-data-big.zip
1. `git clone https://github.com/trofivan/myq-jobs-archive-parser.git`
1. `cd myq-jobs-archive-parser`
1. `npm i`
### Working correctly (only with nwjs-builder-phoenix SDK)
1. `npm start`
1. In the opened window click `Select folder to parse`
1. Select folder with fake data
1. Wait some time while data will have parsed.
1. Use filters
1. Close the program
### Working not correctly
1. `npm run build.dist`
1. `cd dist/myq-jobs-archive-parser-0.1.3-linux-x64/`
1. `./myq-jobs-archive-parser`
1. Select folder to parse and waiting some time.
1. **The program does not respond**. 
1. Close program (`Ctrl + C or [x] on the window`) and see console output:
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`
`[16012:16023:0802/145405.677499:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)`
`[16012:16023:0802/145405.678176:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)`
`[16012:16012:0802/145405.679403:ERROR:broker_posix.cc(104)] Error sending sync broker message: Broken pipe (32)`
`[16012:16012:0802/145405.679587:ERROR:command_buffer_proxy_impl.cc(100)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed`
1. `killall exe` - to stop the process

## PS:
* If download nwjs from the official website, working not correctly with SDK version also.
* On Linux system program not responded when comes to the game Web Worker: https://github.com/trofivan/myq-jobs-archive-parser/blob/master/src/middlewares/fetchJobs.js
* When program not responding I'm can not open Chrome dev tools and get more info.

**Comment by trofivan** [comment]
Any ideas?

**Comment by rogerwang** [comment]
I just tried your program. It works fine here in both cases...

btw, the difference may not be the builder -- I noticed webpack worked in different modes too.

**Comment by trofivan** [comment]
Hi, @rogerwang 
Thank you. Did you test it on Linux? Webpack works in different modes but result is the same if I manually start nwjs with production build

**Comment by rogerwang** [comment]
Yes. My test was on Linux.

**Comment by trofivan** [comment]
@rogerwang what a Linux distributive did you use? And could you test my build with fake data?

Build: https://github.com/trofivan/myq-jobs-archive-parser/releases/download/v0.1.3/myq-jobs-archive-parser-0.1.3-linux-x64.zip

Fake data: https://github.com/trofivan/myq-jobs-archive-parser/releases/download/v0.1.0/fake-data-big.zip

**Comment by rogerwang** [comment]
Yes. I was testing with the fake data you provided on Ubuntu 16.04.2 LTS
