### ISSUE TITLE
OSX - Transparency broken on 0.33.0b1 - OK with 0.32.2

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6750]
OSX: High Sierra 10.13.5 tested with 0.32.2-sdk and 0.33.0b1-sdk.
Test app attached - white background is visible not transparent and print button on main window can not be clicked. Also no context menu. All works OK on 0.32.2-sdk
App profiles deleted - makes no difference.

0.32.2 -
![good](https://user-images.githubusercontent.com/11089335/43685720-17c019a4-98b0-11e8-974a-1532dde66592.jpg)

0.33.0b1 -
![bad](https://user-images.githubusercontent.com/11089335/43685723-2930f0dc-98b0-11e8-8370-61f17fce2804.jpg)

[TransTest.zip](https://github.com/nwjs/nw.js/files/2260289/TransTest.zip)

**Comment by rogerwang** [comment]
Thanks for reporting. @jtg-gg will try to fix it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw33/08-30-2018/7c70451-873cbde-59417a0-3cb3442/v0.33.0/

**Comment by Blatman** [comment]
Thanks Roger,
just tried that build and the white is now transparent but the print button cannot be clicked and the context menu on right-click does not open. Both these functions work with 0.32.4 and will only work with 0.33.0 if I make transparency false and frames true.

Cheers.

**Comment by jtg-gg** [comment]
@rogerwang I think I'll assign this to you (the print button and right click context menu)
from my test if you set the frame to false (regardless it is transparent or not) those to issues happen

**Comment by jtg-gg** [comment]
@rogerwang you'll need to add
    "frame": false,
then those issues happen

**Comment by rogerwang** [comment]
Thanks. It's due to migrating to views toolkit on OSX. Will still use native cocoa for now and fix that later.

**Comment by jtg-gg** [comment]
@rogerwang I notice the changes (from cocoa to views toolkit), is there any "boolean" switch for nwjs?
if yes, can point me the location ?

**Comment by rogerwang** [comment]
see `ui/base/ui_base_features.cc:164`. The default value is set in `testing/variations/fieldtrial_testing_config.json`

It can be turned off in command line via `--disable-features=ViewsBrowserWindows,ExperimentalUi`

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by Blatman** [comment]
Thanks Roger,
works well - also noted that the height issue (#6751) is OK with this build - not sure whether it was the same area of code (MacViews) or the move to 69.0.3497.75
Cheers.
