### ISSUE TITLE
App does not release memory when removing videos

### ISSUE THREAD

**Issue by yucolabjames** [nwjs/nw.js#6756]
NWJS Version : v0.32.1 SDK
Node : v10.8.0
Chromium: 68.0.3440.84
Operating System : Win 10 x64

### Current behavior

Destroying video does not release memory, causing memory leak leading to app crash. Videos played include mp4 and mov.

### Attempt to fix

1. I saw an issue posted in Chromium's bug tracker [166830](https://bugs.chromium.org/p/chromium/issues/detail?id=166830), saying that hardware acceleration could be the cause, which prompted me to try the following but without success ` "chromium-args" : "--disable-accelerated-video --disable-accelerated-mjpeg-decode --disable-accelerated-video-decode --disable-gpu",`
2. Instead of destroying the video and recreating a new video, I tried to replace the existing video's `src` with a new URL but the memory problem still happen.
3. Am using a supposedly working fix to properly destroy video from StackOverflow but without success. [How to properly unload/destroy a VIDEO element
](https://stackoverflow.com/a/28060352/541591)

### How to reproduce

HTML 

	<div id="video-container">
		<div id="frame1"></div>
		<div id="frame2"></div>
		<div id="frame3"></div>
	</div>

JS

	$('#frame'+ID+' video')[0].pause();
	$('#frame'+ID+' video').removeAttr('src');
	$('#frame'+ID+' video')[0].load();
	$('#frame'+ID+' video').remove();

	var video = $('<video />', {
		id: videoId,
		src: videoPath,
		type: 'video/mp4',
		controls: false,
		autoplay: true
	});
	video.appendTo($('#frame'+ID));

I believe this issue could be related to https://github.com/nwjs/nw.js/issues/6730

**Comment by rogerwang** [comment]
Could you please provide a full sample so we can reproduce?
