### ISSUE TITLE
Chrome arguments does not works from cli

### ISSUE THREAD

**Issue by WHK102** [nwjs/nw.js#6765]
For example:
Not work: `./nw --url="https://example.com/" --start-fullscreen`
Not work: `./nw --url="https://example.com/" --chromium-args="--start-fullscreen"`

Howto run nw without manifest file arguments and onli cli mode?

I using https://peter.sh/experiments/chromium-command-line-switches/ from https://www.chromium.org/developers/how-tos/run-chromium-with-flags

**Comment by rogerwang** [comment]
The `start-fullscreen` parameter is supposed to work with `browser window` of Chrome, while in NW there is no browser window, but the application window. While many Chromium switches are supported by NW, those related with browser windows are not.
