### ISSUE TITLE
can't access parent function from webview

### ISSUE THREAD

**Issue by zahimich** [nwjs/nw.js#6772]
NWJS Version : **0.32.2**
Operating System : **Win 10**

**Expected behavior:**

I inject code into the webview to catch keyboard events:

webview.addEventListener("contentload", function (content) {
        let webview = document.querySelector(".content > .win.active");
        //inject keyboard events script:
        var eventsCode = "" +
            "script = document.createElement('script');" +
            "script.text =" +
            "window.removeEventListener('keydown', init_shortcuts); " +
            "window.addEventListener('keydown', init_shortcuts); " +
            "function init_shortcuts(event) {" +
                "if (event.ctrlKey && event.keyCode == 116) {" +// Ctrl + F5
                    "location.reload(true);" +
                "} else if (event.keyCode == 116) {" +// F5
                    "location.reload(false);" +
                "} else if (event.ctrlKey && event.keyCode == 70) {" +// Ctrl + f
                    "window.parent.showTextSearch();" +
                "} " +
            "}";
        webview.executeScript(
            { code: eventsCode }
        );
});

i expect "window.parent.showTextSearch();" to call the parent function.

### Actual behavior

the events work fine but the last event for CTRL+F does not work because it can't access the parent window.

### How to reproduce

to reproduce, you can try and use my code for injecting the script to the webview.

**Comment by rogerwang** [comment]
This is expected because the webview and the parent window runs in different process now. To exchange information between them, consider using postMessage or BroadcastChannel etc.

**Comment by zahimich** [comment]
i'm reading this:
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
its not working for me. is there an NWJS example of this?

**Comment by bambooCZ** [comment]
see this
https://developer.chrome.com/apps/runtime#method-connect

you will have to:
1) add content script to the webview
```
var port  = chrome.runtime.connect("I am the webview");
port.postMessage("showTextSearch");
```
2) outside the webview
```
chrome.runtime.onConnect.addListener((port) => {
    if (port.name!="I am the webview") return; // Security, of course make it more secure, than a constant string

    port.onMessage.addListener((theMessage) => {
        switch (theMessage) {
                case "showTextSearch": 
                       window.showTextSearch();
                       break;
        }
   });
});
```
