### ISSUE TITLE
Compiling a custom element and using it issue

### ISSUE THREAD

**Issue by brtheo** [nwjs/nw.js#6775]
NWJS Version : 0.32.3 x64
Operating System : Windows 10

### Expected behavior

Loading correctly the custom component

I tried putting the js code that loads the custom component binaries at the end of the body, at the top of it and in the head section as well. same results
```html
<body>
    <my-custom></my-custom>
    <script>
        nw.Window.get().evalNWBin(null, 'bin/myCustom.bin')
        customElements.define('my-custom',MyCustom)
    </script>
</body>
```

### Actual behavior

Well it's kinda weird, for like 0.5s the custom element do appears, then it fades away. 
Here's a gif of that behavior : 

[https://1drv.ms/u/s!Ajd_nLj_EcoDhtdH5oiNFwOYVLDJwg](url)

#### index.html
```html 
<html>
    <head>
    </head>
    <body>
        <my-custom></my-custom>
        <script>
            nw.Window.get().evalNWBin(null, 'bin/myCustom..bin')
            customElements.define('my-custom',MyCustom)
        </script>
    </body>
</html>
```
#### myCustom.js
```javascript
class MyCustom extends HTMLElement {
    constructor() {
        super()
        const shadowRoot = this.attachShadow({mode: "open"})
        const template = document.createElement('section')
        template.textContent = "Hello"
        shadowRoot.appendChild(template)
    }
}
```
I also tried this way of templating and same results
```javascript
const template = 
`
<section>Hello</section>
`
shadowRoot.innerHTML += template
```

**Comment by brtheo** [comment]
After more tests, it seems that all compiled dom manipulation js code produces the same results, like a simple vue app or even 
```javascript
document.body.innerHTML += "hello"
```
being compiled to binaries produces the same weird results as showing in my gif

**Comment by Ziiven** [comment]
Try the nightly build, it fixed the crash issue

**Comment by brtheo** [comment]
On version 0.33.0-beta2 and beta1, same issue, content showed for 0.5 and gone.
I used the beta compiler as well.

**Comment by brtheo** [comment]
Thank's that works!
