### ISSUE TITLE
Using video tag cause window icon missing

### ISSUE THREAD

**Issue by yannan** [nwjs/nw.js#6776]
I want to use the video tag to play something, so I replace the ffmpeg.dll file.But when click the play button, the icon of current window missing.
![qq 20180830091222](https://user-images.githubusercontent.com/7194092/44823784-eaa8ad80-ac34-11e8-8f1d-aa82201ceace.png)
![qq 20180830091249](https://user-images.githubusercontent.com/7194092/44823787-ed0b0780-ac34-11e8-82fc-536bce274a0c.png)

Here is the sample:
I use nw.Window.open to open a local server address:

```
nw.Window.open('http://127.0.0.1:10080/test.html', {
            id: 1,
            title: '1',
        }
```

test.html:

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
</head>

<body>
        <video src="http://www.w3school.com.cn/i/movie.ogg" controls="controls"></video>

</body>

</html>
```

Now I want to find some help

**Comment by rogerwang** [comment]
Please provide a sample so that we can reproduce it.

On August 30, 2018 9:13:36 AM GMT+08:00, Nan Yan <notifications@github.com> wrote:
>I want to use the video tag to play something, so I replace the
>ffmpeg.dll file.But when click the play button, the icon of current
>window missing.
>![qq
>20180830091222](https://user-images.githubusercontent.com/7194092/44823784-eaa8ad80-ac34-11e8-8f1d-aa82201ceace.png)
>![qq
>20180830091249](https://user-images.githubusercontent.com/7194092/44823787-ed0b0780-ac34-11e8-82fc-536bce274a0c.png)
>
>Now I want to find some help
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nwjs/nw.js/issues/6776

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
