### ISSUE TITLE
webkit-app-region stops responding to mouse event  with MacViews migration

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#6777]
Currently MacViews is disabled by default. This issue tracks the migration.

Ref: https://github.com/nwjs/nw.js/issues/6750#issuecomment-417557555

**Comment by rogerwang** [comment]
I just found the culprit is `-webkit-app-region: drag;` in `css/testpro.css` line 57. If I comment it out everything works fine. Will investigate it more.

CC @Blatman @jtg-gg

**Comment by rogerwang** [comment]
btw, the upstream sample works well: https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/frameless-window

**Comment by rogerwang** [comment]
The current behavior should be expected: ["Care must be taken when setting a high level DOM node to drag, any child that is intractable/clickable must be set to no-drag. "](https://developer.chrome.com/apps/app_window). So please set 'no-drag' style in the button in the application.

**Comment by Blatman** [comment]
Just tried 0.34.0alpha-sdk and with the no-drag set against the print button - no-drag and click work fine on print button but print click opens in existing window not a new one. Also the context menu does not work on right-click on the draggable main body and the window height issue is back (#6751).
The last build of 0.33.0 works fine for all these checks. Is this the MacViews again?
Cheers.

**Comment by rogerwang** [comment]
Yes. That's I'm trying to enable the MacViews as default following upstream in Chromium 70. Will see the issues.

**Comment by rogerwang** [comment]
@Blatman unfortunately it's expected that the print preview opening in the same window of the web content under the views UI framework. You can see the same behavior on Windows and Linux (and in upstream chrome browser as well). It's called ['ConstrainedWebDialogUI'](https://cs.chromium.org/chromium/src/chrome/browser/ui/webui/constrained_web_dialog_ui.h?rcl=31db9c945d55e3232920413a48a5f426dcb6e6fe&l=61) in the underlying architecture.

**Comment by Blatman** [comment]
OK thanks, looks like going forward that Print Preview will only have to be provided on content larger than the Print Preview dialog.
Just leaves the window height sizing  issue and context menu.

**Comment by rogerwang** [comment]
If the region is draggable, it's not supposed to receive the right click as well...
I'll see the sizing issue.
