### ISSUE TITLE
Can nw.js run on Chromebook?

### ISSUE THREAD

**Issue by donnyv** [nwjs/nw.js#6781]
Has anyone been able to run nw.js on Chromebooks? Working on a cross platform app and adding Chromebooks would be nice.

**Comment by bluthen** [comment]
Do you mean chromebook running in dev mode where it is basically Linux? Or android compatibility mode? Regular chromebook apps are just chrome apps and doesn't run native code by itself, makes it pretty different than a mac, windows, or linux system.

You might be interested in writing a chrome app then using nw.js to run the chrome app on the desktops. nw.js can do that.

**Comment by donnyv** [comment]
Is it possible in Dev mode?

**Comment by bluthen** [comment]
I don't see why not if you have a x86 chromebook. As for arm chromebooks, I don't see a nw.js arm build, so may be out of luck there, or trying building your own.

See: https://github.com/nwjs/nw.js/issues/3577

**Comment by jojomickymack** [comment]
You can install the linux nwjs distribution on a chromebook but it won't be able to find the graphics - it's looking for 'x11' - chromebook's graphics system is something called 'freon' I think - you're not going to be able to interact with that.

Like bluthen said, you're totally able to just make a chrome web app, which is giving you a chromium instance just like nwjs does. There's really not much of a difference.

If you really need to do nwjs or electron or any other windowing toolkit on a chromebook, you'll have everything you need if you go the crouton route - and using the xiwi platform you can actually run an x11 window in a chrome tab or window.

So the answer to the subject line question is yes - by using crouton though - and if you mean running nwjs in the native chromeos operating system _without_ crouton, the answer is no... but chrome apps are _really_ similar to a nwjs context and you can absolutely develop those on chromebooks.
