### ISSUE TITLE
Webview crashes if App was loaded from url.

### ISSUE THREAD

**Issue by iteufel** [nwjs/nw.js#6784]
NWJS Version : 0.33.0
Operating System : macOS

### Expected behavior

Webview tag should work if `main` is a url like `http://127.0.0.1:8080`.

### Actual behavior

Webview crashes with an error.
`[37375:775:0906/085859.166034:ERROR:bad_message.cc(25)] Terminating renderer for bad IPC message, reason 1`
![untitled](https://user-images.githubusercontent.com/4130931/45140575-8301dd80-b1b3-11e8-9af8-c5e023825fd4.jpeg)
0.32.4 works fine.

### How to reproduce

Serve the Example App using `python -m SimpleHTTPServer 8080`

[Example.zip](https://github.com/nwjs/nw.js/files/2355861/Example.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
