### ISSUE TITLE
Vimeo videos are not playable

### ISSUE THREAD

**Issue by peter23** [nwjs/nw.js#6785]
NWJS Version : SDK 0.33.0 Windows x64
Operating System : Windows 10 x64

### Actual behavior

NW.js cannot play videos from vimeo.com. But any browser can.
Videos from other sources work fine.

### How to reproduce

Download https://dl.nwjs.io/v0.33.0/nwjs-sdk-v0.33.0-win-x64.zip, extract and run nw.exe.
Press F12 to open Developers Console.
Enter `location.href = 'https://vimeo.com/249496518';` in the console (or any other video).
Vimeo video page will be opened but nothing happens after clicking on the Play button.
There are no visible errors on the page or in the console.

**Comment by rogerwang** [comment]
I believe it's H264 encoded, and we don't ship H264 decoder in the official binary due to license. You can look for community binary if you have the license.
