### ISSUE TITLE
Command line arguments are not quoted on OSX when passed to "open" event

### ISSUE THREAD

**Issue by Mi6a** [nwjs/nw.js#6787]
NWJS Version : 32.3
Operating System : OSX

### Expected behavior
At least some of the switches' values added directly by NW.js to command line passed to App.open event are quoted - see additional quotes around value for --user-data-dir or very first argument - path to nwjs executable:

cmd_line = ""Users/serg/project/Code Verify.app/Contents/MacOS/nwjs" --user-data-dir="/Users/serg/Library/Application Support/verifier" --no-sandbox --no-zygote --flag-switches-begin --flag-switches-end --nwapp="/Users/serg/project/Code Verify.app/Contents/Resources/app.nw""

### Actual behavior
cmd_line = "Users/serg/project/Code Verify.app/Contents/MacOS/nwjs --user-data-dir=/Users/serg/Library/Application Support/verifier --no-sandbox --no-zygote --flag-switches-begin --flag-switches-end --nwapp=/Users/serg/project/Code Verify.app/Contents/Resources/app.nw"

Observe strings with spaces are not quoted. Not sure how such command line string can be parsed and splitted properly to separate arguments.

### How to reproduce
1.Create any NW.js application
2. In any place (preferrebly code that's running on background page)
add listener for App."open" event:

  nw.App.on("open", function(cmd_line) {
     console.log(cmd_line);
  }
Try opening two application windows side by side from command line without any arguments:
$ open ./Code\ Verify.app
$ open -n ./Code\ Verify.app

Check in debugger or console what string is passed to function-handler of "open" event.
In the following code cmd_line arguments' values are not get quoted.       

####
Notes : on Windows 10 all switches' values that were originated from NW.js are properly quoted:
""D:\project\CodeVerfiy\Code Verify.exe" --user-data-dir="C:\Users\Миша\AppData\Local\verifier\User Data" --no-sandbox --no-zygote --flag-switches-begin --flag-switches-end --nwapp="D:\project\CodeVerify" --original-process-start-time=13180970083488494"

**Comment by Mi6a** [comment]
Fixing this issue is easy: removing both macroses #if defined(OS_WIN) in the following base/command_line.cc code:

CommandLine::StringType CommandLine::GetArgumentsStringInternal(
    bool quote_placeholders) const {
.....
    if (parse_switches && IsSwitch(arg, &switch_string, &switch_value)) {
      params.append(switch_string);
      if (!switch_value.empty()) {
#if defined(OS_WIN)
        switch_value =
            QuoteForCommandLineToArgvW(switch_value, quote_placeholders);
#endif
        params.append(kSwitchValueSeparator + switch_value);
      }
    } else {
#if defined(OS_WIN)
      arg = QuoteForCommandLineToArgvW(arg, quote_placeholders);
#endif
      params.append(arg);
    }
  }
  return params;
}

**Comment by Mi6a** [comment]
Not sure why posix systems should have different in this regard from Windows behavior.
Anyway parsing command line would be very buggy without switches' values being quoted.

**Comment by Blatman** [comment]
Just a thought - is this related to #7041 which has just been fixed in 0.38.0?

**Comment by rogerwang** [comment]
Yes. Thanks for reminding. Merge with #7041 as they are the same bug.
