### ISSUE TITLE
DevTools found a problem, I don't know what the reason is!

### ISSUE THREAD

**Issue by phpjishu** [nwjs/nw.js#6789]
DevTools found a problem, I don't know what the reason is!

I installed a vue-devtools on nw, and it was okay to test it in the main window, but I wanted to jam the program when it was used in a WebView devtools, and JS reported an error.

The mistake is:

```
VM200:5 GET chrome-extension://ingnebdjgobelfamkcnbgcggbkbbbhmi/build/backend.js net::ERR_BLOCKED_BY_CLIENT
```

======== TEMPLATE BUG FORM ========

NWJS Version : 0.33.0 sdk win64位
Operating System : win10

### Error screenshot

![image](https://user-images.githubusercontent.com/6937002/45341888-c652b680-b5ce-11e8-9c4a-de94c77c7910.png)

### Code attachments
[DownZip](http://nwjs.xinyisoft.cn/package.nw.zip)

**Comment by phpjishu** [comment]
@rogerwang

**Comment by TheJaredWilcurt** [comment]
You can try `nw-vue-devtools`

* https://www.npmjs.com/package/nw-vue-devtools

or `nw-vue-devtools-prebuilt`

* https://github.com/DimPaDev/nw-vue-devtools-prebuilt

**Comment by AminHuang** [comment]
@phpjishu Did you solve it?

**Comment by AminHuang** [comment]
@rogerwang I have same problem. 
nw-vue-devtools-prebuilt / react-devtools works ok  in the main window, but I find ERR_BLOCKED_BY_CLIENT when it was used in a WebView devtools

this work ok
```
../nwjs52/nwjs.app/Contents/MacOS/nwjs --url=https://reactjs.org/docs/hello-world.html --load-extension=../react-devtools3 
```

but if in webview
```
../nwjs52/nwjs.app/Contents/MacOS/nwjs . --load-extension=../react-devtools3
```
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <webview partition="persist:htmlwebview_0"  partition="persist:trusted" src="https://reactjs.org/docs/hello-world.html" ></webview>
  </body>
</html>
```
```
{
    "name": "helloworld",
    "main": "index.html",
    "dependencies": {
        "react-devtools": "^3.6.3"
    },
    "webview": {
        "partitions": [
          {
            "name": "trusted",
            "accessible_resources": [
              "<all_urls>"
            ]
          }
        ]
      },
    "devDependencies": {
        "nw-vue-devtools-prebuilt": "0.0.10"
    }
}
```
![image](https://user-images.githubusercontent.com/6110040/145151973-e96772f8-c5ed-4767-85b0-abb5170f076d.png)

Is there a problem with my usage？
