### ISSUE TITLE
Socket.IO stopped working in version 0.5.x

### ISSUE THREAD

**Issue by pkorzeniewski** [nwjs/nw.js#679]
After switching to version 0.5.x, Socket.IO (0.9.14) stopped working on Windows (maybe other platforms as well). Client can't establish connection (handshake) with server, it's stuck on 'connecting' step. I've tested it with version 0.4.2 and it works well.

**Comment by corwin-of-amber** [comment]
The flag works, but this will allow other bad certificates as well. Shouldn't there be a way to add trusted certificates to Chromium's settings?

**Comment by keenghost** [comment]
@corwin-of-amber Hi，did you get the solution for certain certificates?

**Comment by corwin-of-amber** [comment]
@keenghost No, sorry... I am still using the flag.
