### ISSUE TITLE
nw_100_percent.pak

### ISSUE THREAD

**Issue by allen1991** [nwjs/nw.js#6796]
i can not figure out , i use enigma virtual box to pack it into a .exe file , after i get a boxed.exe, it can be run in the same directory, then i move this file to the desktop  and click it , it shows  something is lose like nw_elf.dll needed , when i repeat it (pack again) , it reminds me of reinstall it and failed. it is not same as blog says.if someone has figured it out ,please inform me . chinese version is better; thanks a lot .

**Comment by allen1991** [comment]
i operate it after reading this blog [](https://www.cnblogs.com/tinyphp/p/5052327.html) chinese version

**Comment by allen1991** [comment]
[https://www.cnblogs.com/tinyphp/p/5052327.html](url) i operate it after reading this blog

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
