### ISSUE TITLE
Dlls missing version field

### ISSUE THREAD

**Issue by BogdanZavu** [nwjs/nw.js#6805]
NWJS Version : v0.33.3
Operating System : Win 10

### Expected behavior
Dlls delivered with v0.33.3 and older versions should have meaningful values for properties like 
FileVersion, Product Name, Product version and Copyright.
Offending dlls are :
ffmpeg.dll
node.dll
nw.dll
nw_elf.dll
nw.exe

### Actual behavior
Properties for the dlls above above are either empty or null Version or 0.0.0.0

### How to reproduce
Just unpack latest version ( currently v0.33.3 ):  and look at the file properties in windows explorer.

This is important for us because we have to comply with internal tools that check these fields.
We can hack around it but we strongly prefer not to.

**Comment by BogdanZavu** [comment]
@rogerwang this should be a simple, safe and fast fix for you I hope, and we would be very grateful for it :)

**Comment by rogerwang** [comment]
Thanks. Will look to fix it soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
