### ISSUE TITLE
OSX - createWriteStream object returns as Promise with 0.34.0b1

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6808]
OSX 10.13.6 High Sierra using SDK builds.

Bit of a curly one this -
createReadStream/createWriteStream appear to have an issue since 0.34.0b1 - if the file-map module is 'required' the stream object will be returned as a Promise rather than ReadStream/WriteStream.

With the file-map module required using either fs or temp will fail but fs-extra works OK if 0.34.0b1 or later is used.

fs/fse/temp all work OK with builds upto 0.33.4 - maybe there is a change with node 11 here?
The file-map module is more or less abandonware but has worked fine through to 0.33.4

file-map uses an IIFE pattern but not sure why it should affect code elsewhere just by being required - again was no problem with 0.33.4 and earlier. 

Tested with modules installed with npm/node 10.1.0

A test app is attached and has node modules included for convenience.

[StreamBug.zip](https://github.com/nwjs/nw.js/files/2403226/StreamBug.zip)

FAIL - Promise should be WriteStream object
<img width="954" alt="0340-fail" src="https://user-images.githubusercontent.com/11089335/45849363-848de280-bd29-11e8-8e60-7d3bf119ccb4.png">

**Comment by Blatman** [comment]
Sorry forgot to mention - just open the js/build.js file to alter the code for various conditions - it is commented.

**Comment by rogerwang** [comment]
Would you try it with this Node.js build? https://nodejs.org/download/v8-canary/v11.0.0-v8-canary20180910566e979d5c/

I guess it's due to the change in that version.

**Comment by Blatman** [comment]
Managed to install node 11.0.0 into nvm and then installed node modules with v11.0.0 - running 0.34.0b1 still fails but I guess you really want the app run with v11.0.0 - not sure how to do that ....

**Comment by rogerwang** [comment]
I mean is the file-map module working well with Node v11.0.0?

**Comment by Blatman** [comment]
Same as before if the file-map module is not used then the stream will work OK (0.33.4 still OK with file-map). 
I have tried the file-map in my big project (installed using v11.0.0) and it is not working well with either 0.33.4 or 0.34.0b1 - will take me a while to track down, might be different issue.

**Comment by Blatman** [comment]
OK found the issue in the big project - forgot I had done some tweaks inside the file-map module so yes it still functions OK when installed by 11.0.0 but the promise issue with 0.34.0b1 still exists (even if I use an unmodified file-map module). The original author of the module stated 'The promise returned is A+ compliant' so it seems that 0.34.0b1 is reacting to the return (when module is required) if a createWriteStream is done whereas 0.33.4 and earlier just creates a writestream as it should.
Cheers

**Comment by rogerwang** [comment]
I mean do you have a piece of code that runs in Node.js (not with NW) and shares the same issue? In this way we can isolate where the root case is.

**Comment by Blatman** [comment]
OK - I guess using nw-builder from the CLI qualifies since npm uses whatever node version is specified so I have attached my CLI version of NWB that demonstrates the issue.
blat-readme.txt in the folder will explain all - the problem still occurs when using node 11.0.0 if file-map is required.

[nwbcli-blatmod.zip](https://github.com/nwjs/nw.js/files/2407746/nwbcli-blatmod.zip)
