### ISSUE TITLE
Credential Management API: get resolves to null

### ISSUE THREAD

**Issue by igoj07** [nwjs/nw.js#6809]
NWJS Version : 0.33.3 SDK
Operating System : Win 7 x64

### Expected behavior
I would like to use Credential Management API for auto sign-in feature in my app simply like this:

1. to store user password credentials
`
var creds = new PasswordCredential({ id: "username", password: "password" });
navigator.credentials.store(creds);
`
2. to get stored user credentials
`navigator.credentials.get({password: true, mediation: 'silent'}).then(function (creds) { ... });`

### Actual behavior
Credentials are successfully stored, but calling `navigator.credentials.get` always resolves to `null`.

### How to reproduce
Try this code:
```
var creds = new PasswordCredential({id: "user", password: "pass"});

navigator.credentials.store(creds).then(function () {
    navigator.credentials.get({password: true, mediation: 'silent'}).then(function (result) {
        // result = null                             
    });
});
```
Thank you.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by igoj07** [comment]
NWJS Version : 0.34.0 SDK
Operating System : Win 7 x64

Thank you for fixing this issue, but it works for local files only, not for remote ones.

### How to reproduce 
Page `index.html` contains this code only:
```
<script>

    var creds = new PasswordCredential({id: "foo", password: "bar"});

    navigator.credentials.store(creds).then(function (success) {
        navigator.credentials.get({password: true, mediation: 'silent'}).then(
           function (storeCreds) {
                ...
           });
    });

</script>
```
For this `package.json` it works as expected:
```
{
  "name": "foo",
  "main": "index.html"
}
```
But for this one, it doesn´t work:
```
{
  "name": "foo",
  "main": "http://127.0.0.1:8080/index.html"
}
```

**Comment by itm-platform** [comment]
Same here, it logs null
```js
    const credential = new PasswordCredential({
        id: auth.username,
        password: auth.password,
    })
    navigator.credentials.store(credential).then(() => {
        console.info("Credential stored in the user agent's credential manager.", credential); // logs credential
        navigator.credentials.get({
            password: true,
            mediation: 'silent'
        })
            .then(c => console.log(c)); // logs null
```
