### ISSUE TITLE
Transparent window, no iframe, display icon and title in upper left corner.

### ISSUE THREAD

**Issue by jgf0725** [nwjs/nw.js#6810]
NWJS Version : v0.26.6-sdk
Operating System : windows

### Expected behavior
A borderless transparent window, when started, icons and titles appear in the upper left corner, user experience is very bad. But I don't know how to solve it.
eg:
![image](https://user-images.githubusercontent.com/4901192/45871003-e3516b80-bdbe-11e8-9a64-14a61b473abc.png)

### Actual behavior
It is hoped that nwjs developers can provide solutions for normal display.

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by jgf0725** [comment]
> Could you please provide a full sample (not code snippets) so we can reproduce?

![nwjs](https://user-images.githubusercontent.com/4901192/46401587-07eb0300-c730-11e8-83d4-d51e62825c21.png)

**Comment by jgf0725** [comment]
Thank you for your reply.
The complete sample download address is as follows；
download url ： https://pan.baidu.com/s/1ODqIh72cF666RM0hxWaHHQ 
password : rut1

**Comment by jgf0725** [comment]
> Could you please provide a full sample (not code snippets) so we can reproduce?

Hi, guys. Thank you for your reply.
The complete sample download address is as follows；
   download url ： https://pan.baidu.com/s/1ODqIh72cF666RM0hxWaHHQ 
   password : rut1
