### ISSUE TITLE
[Windows] libEGL and libGLESv2 are redundant (in ./ and ./swiftshaders)

### ISSUE THREAD

**Issue by cookiengineer** [nwjs/nw.js#6811]
NWJS Version : 0.33.3+ (all previous versions)
Operating System : Arch Linux Host, Windows Target

Why does the resulting nwjs build contain multiple libEGL and libGLESv2 variants? Are the ones in the root folder actually necessary?

**Comment by rogerwang** [comment]
They are different files sharing the same name. The ones in the root folder is necessary, for real hardware Gfx acceleration. Swiftshader is a high performance software based acceleration for hardware that is incapable.
