### ISSUE TITLE
PDF Viewer does steal mouse

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#6812]
NWJS version:
* 0.30.4 (ok)
* 0.31.5 (ok)
* 0.32.4 (fail)
* 0.33.4 (fail)

Chrome version:
* 69.0.3497.100 (ok)

Chromium version:
* 69.0.3497.100 (fail)

Operating system:
* Windows 10 x64 (17134.286)

### Expected behavior

PDF Viever must respect mouseover on upper element

### Actual behavior

PDF Viever does steal mouse(over)

### How to reproduce

In demo has two buttons, `Load normal page` and `Load PDF`, and custom `menu` (top right)
* On normal page, mouseover on `menu` works properly.
* On PDF, mouseover doesn't works.

[demo.zip](https://github.com/nwjs/nw.js/files/2419603/demo.zip)

**Comment by panther7** [comment]
added tested Chromium version

**Comment by rogerwang** [comment]
Since it fails too with Chromium, please report the issue to upstream.

**Comment by panther7** [comment]
reported: https://bugs.chromium.org/p/chromium/issues/detail?id=890756

**Comment by panther7** [comment]
Probably fixed in v70.0.3538.0

**Comment by panther7** [comment]
rogerwang: Could you try build nwjs 0.34 beta with this 70.0.3538.0 ?

**Comment by rogerwang** [comment]
NW 0.34.0 beta was released with 70.0.3538.22, newer than 70.0.3538.0

**Comment by panther7** [comment]
Thank you, I will try it tomorrow.

**Comment by panther7** [comment]
Sorry, probably fixed in 70.0.3538.45, could try build this. Thank you very much!

**Comment by rogerwang** [comment]
This build is synced with 70.0.3538.45: https://dl.nwjs.io/live-build/nw34/10-04-2018/63e21114a/v0.34.0/

**Comment by panther7** [comment]
Yes, fixed... it may be closed in NWjs 0.34
