### ISSUE TITLE
./build/gyp_chromium faild

### ISSUE THREAD

**Issue by ryankumar** [nwjs/nw.js#6815]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System :

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by ryankumar** [comment]
when i built ./build/gyp_chromium in ubntu 16.04 it shows folling error. please help me in it.

Updating projects from gyp files...
Using overrides found in /home/mahannee/.gyp/include.gypi
gyp: /home/mahannee/chromimum_src/src/v8/src/d8.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/third_party/webrtc/tools/tools.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/native_client/build/untrusted.gypi not found (cwd: /home/mahannee/chromimum_src/src/build) while reading includes of /home/mahannee/chromimum_src/src/build/common_untrusted.gypi while reading includes of /home/mahannee/chromimum_src/src/mojo/mojo_nacl_untrusted.gyp
gyp: Error importing pymod_do_mainmodule (grit_info): No module named grit_info
gyp: /home/mahannee/chromimum_src/src/third_party/libaddressinput/src/cpp/libaddressinput.gypi not found (cwd: /home/mahannee/chromimum_src/src/build) while reading includes of /home/mahannee/chromimum_src/src/third_party/libaddressinput/libaddressinput.gyp
gyp: /home/mahannee/chromimum_src/src/native_client/build/untrusted.gypi not found (cwd: /home/mahannee/chromimum_src/src/build) while reading includes of /home/mahannee/chromimum_src/src/build/common_untrusted.gypi while reading includes of /home/mahannee/chromimum_src/src/remoting/remoting_key_tester.gypi while reading includes of /home/mahannee/chromimum_src/src/remoting/remoting.gyp
Package nss was not found in the pkg-config search path.
Perhaps you should add the directory containing `nss.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nss' found
gyp: Call to 'pkg-config --libs-only-l nss | sed -e "s/-lssl3//"' returned exit status 0 while in /home/mahannee/chromimum_src/src/net/third_party/nss/ssl.gyp.
gyp: /home/mahannee/chromimum_src/src/third_party/libjpeg_turbo/libjpeg.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/v8/tools/gyp/v8.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/third_party/pdfium/samples/samples.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/third_party/ffmpeg/ffmpeg.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/third_party/WebKit/public/all.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: /home/mahannee/chromimum_src/src/third_party/skia/gyp/core.gypi not found (cwd: /home/mahannee/chromimum_src/src/build) while reading includes of /home/mahannee/chromimum_src/src/skia/skia_library.gypi while reading includes of /home/mahannee/chromimum_src/src/skia/skia.gyp
/bin/sh: 1: cups-config: not found
gyp: Call to 'cups-config --api-version' returned exit status 127 while in /home/mahannee/chromimum_src/src/printing/printing.gyp.
gyp: /home/mahannee/chromimum_src/src/media/cdm/ppapi/external_open_cdm/browser/media_open_cdm.gypi not found (cwd: /home/mahannee/chromimum_src/src/build) while reading includes of /home/mahannee/chromimum_src/src/media/media.gyp
gyp: /home/mahannee/chromimum_src/src/third_party/angle/build/common_defines.gypi not found (cwd: /home/mahannee/chromimum_src/src/build) while reading includes of /home/mahannee/chromimum_src/src/gpu/gpu.gyp
gyp: Error importing pymod_do_mainmodule (grit_info): No module named grit_info
gyp: /home/mahannee/chromimum_src/src/third_party/icu/icu.gyp not found (cwd: /home/mahannee/chromimum_src/src/build)
gyp: Error importing pymod_do_mainmodule (grit_info): No module named grit_info
gyp: Error importing pymod_do_mainmodule (grit_info): No module named grit_info
gyp: Error importing pymod_do_mainmodule (grit_info): No module named grit_info

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by ryankumar** [comment]
Hi Roger,

i can ask my question here. Because from the above given link i am not
getting where should i ask my doubt.



Thanks,
Ryan
