### ISSUE TITLE
Transparent Windows don't work in MacOS Mojave Dark mode

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#6818]
NWJS Version : 30.5
Operating System : MacOS Mojave

with NWJS apps we can enable Mojave dark move by adding in the **info.plist**

```
<key>NSRequiresAquaSystemAppearance</key>
<false/>
```

See https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app

This work fine for normal windows but if you have a transparent window without title, suddenly a title shows:

![macos_mojave_dark_transparent_bug](https://user-images.githubusercontent.com/504730/46426346-923a6380-c73e-11e8-8538-ecdc25a59eed.png)

**Comment by rogerwang** [comment]
CC @jtg-gg

**Comment by jtg-gg** [comment]
@gpetrov I can't reproduce this with the latest nwjs 0.34
﻿﻿﻿http://dl.nwjs.io/live-build/nw34/10-15-2018/4d940057e/v0.34.0/
