### ISSUE TITLE
Mouse event fires a display of print dialog box

### ISSUE THREAD

**Issue by doom-fr** [nwjs/nw.js#6820]
NWJS Version : nwjs 69.0.3497.100 / nwjs-sdk-v0.33.4-linux-x64
       ( tested also in nwjs-sdk-v0.26.0-linux-x64)
Operating System : Debian GNU/Linux 8

### Expected behavior
it should just print 'onMouseMove' when I move the mouse

### Actual behavior
It opens the print dialog box when I move the mouse over the canvas
This bug is a blocking bug

### How to reproduce
Here is the minimal example :
package.json
```
{
	"name": "bugPrintPopUp",
	"version": "0.0.1",
	"main": "bugPrintPopUp.html",
	"window": {
	},
	"dependencies": {
	}
}
```

bugPrintPopUp.html :
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>bug print pop up</title>
		<script>
			var canvas;
			var wp='default';
			function onWinLoad() {
				canvas = document.getElementById("myCanvas");
				canvas.addEventListener("mousemove", onMouseMove, false);
			}
			function onMouseMove(event) {
				print('onMouseMove');
			}
			window.addEventListener("load",onWinLoad,false);
		</script>
	</head>
	<body style="background-color:#dddddd; overflow:hidden;">
		<div id="container">
			<canvas id="myCanvas">
			</canvas>
		</div>
	</body>
</html>
```

Just do `nw .` and hover the canvas

**Comment by doom-fr** [comment]
Just open the html file in chromium and there the problem so might not be a problem with nw, but with chromium.

**Comment by rogerwang** [comment]
Could you please report it to Chromium upstream since it looks like a bug in Chromium?

**Comment by doom-fr** [comment]
Yes, I will do something but I don't know what as it seems to affect also Firefox 52.9.0.
Tested on a different linux Jessie machine and is the same.

The more astonish is that the problems also occurs on another machine with Widows 10 with Firefox and also with Edge.

What's the the common thread ?
The place where all these machines are ?

To help me, can you please try on your side ? (Hover the left corner of the page to trigger the event)

Thanks !

Doom

**Comment by doom-fr** [comment]
Have tested in another place and do the same on Windows with Chrome, Firefox and Edge.
 Think it was in webkit itself so I have placed an issue.

**Comment by doom-fr** [comment]
In fact just have use print function of python instead of console.log of javascript ...
%-)
