### ISSUE TITLE
z-index issue with WebViews and overlayed elements in newer NW.js versions

### ISSUE THREAD

**Issue by cdog** [nwjs/nw.js#6822]
NWJS Version: 0.33.2 and 0.33.4
Operating System: Ubuntu 18.04 LTS

### Expected behavior

Clicking anything in the modal should capture the mouse events (close modal, press action buttons, select text).

See image below:

![modal overlay](https://user-images.githubusercontent.com/690647/46603558-0e94c400-cafc-11e8-95d4-58e357ef185e.png)

### Actual behavior

Clicking anything in the modal acts on the PDF (like it is on top) regardless rendering. Seems `z-index` works for displaying the stacked elements correctly but not for input (mouse events).

### How to reproduce

HTML markup:

```
<div class="container">
  <webview src="://url/to/pdf"></webview>
  <div class="backdrop">
    <div class="modal">
      <p>This is some text within a modal body.</p>
      <button>Dismiss</button>
    </div>
  </div>
</div>
```

WebView and overlay styles:

```
.container {
  position: relative;
}

.container webview {
  bottom: 0;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  z-index: 10;
}

.container .backdrop {
  background-color: rgba(0, 0, 0, .3);
  bottom: 0;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  z-index: 20;
}

.container .modal {
  position: absolute;
  z-index: 30;
  /* ...other modal styles... */
}
```

It was working properly with NW.js `0.30.2` and `0.31.0` versions. This behaviour was introduced after upgrading to newer NW.js versions. Is there anything related to plugins in frames/webviews that was changed in recent releases (like the Chromium PDF Viewer plugin)? Thanks!

**Comment by rogerwang** [comment]
Does it reproduce with a Chrome App inside Chrome browser?

**Comment by cdog** [comment]
Hello,

Thanks for pointing out. Tested in Chromium alone and it does reproduce the issue indeed.

Tested with the following Chromium versions:

- 69.0.3497.92 (https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/576753/)
- 70.0.3538.67 (https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/587811/)
- 72.0.3591.0 (https://download-chromium.appspot.com/)

Doesn't work with Chromium 69 and 70. It works with version 72.

![pdf test](https://user-images.githubusercontent.com/690647/48134703-6d885d00-e2a3-11e8-8e70-debcd238cb62.png)

Uploaded a test case repository in case anybody wants to do a similar test:
https://github.com/cdog/chromium-webview-pdf-overlay

**Expected result:** Be able to click on "Test link" inside the overlay.
**Actual result:** "Test link" is not clickable (with mentioned Chromium version 69 and 70).

Guess this will be fixed with newer releases of NW.js.

**Comment by rohan-deshpande** [comment]
@rogerwang Can this be reopened? I have recently upgraded my app from v0.31.0 to v0.46.0 and this issue breaks my UI completely. It seems that v0.46.0 uses Chromium 83, but the bug persists, the bug does not happen when loading my app in the Chrome browser (Version 81.0.4044.122)

**Comment by rohan-deshpande** [comment]
Hi @cdog, did your issue actually get fixed when you upgraded?

**Comment by rohan-deshpande** [comment]
@rogerwang will do my best to try and create a test repo to display this issue soon

**Comment by cdog** [comment]
This was fixed on my side. Tried with both NW.js 0.44.1 and 0.46.1, also directly in Chrome (version 83).

@rohan-deshpande tested with: https://github.com/cdog/chromium-webview-pdf-overlay

Can you test with same repository, is your scenario different?

**Comment by rohan-deshpande** [comment]
Very strange, okay I will try that out and also create my own repo to see what is going on

**Comment by rohan-deshpande** [comment]
Okay, I have done an experiment with some interesting results. I got it to work but only with fully compiled production code.

So basically, the bug seems to be in my development environment which works like this

* I develop my app with [create-react-app](https://create-react-app.dev/) which has an `npm run dev` script that creates a full JS development environment at `localhost:3000`
* I point my nwjs manifest file at this address using the `node-remote` option

In previous versions of nwjs, this worked fine but after the latest updates, I cannot click the app in my development environment.

@rogerwang do you know of any changes, security wise or other that might have caused this particular setup to break?

**Comment by rohan-deshpande** [comment]
@rogerwang sorry to comment on this issue again but I actually discovered the problem, attempting to have a frameless NWJS window broke things for me. So

```
  "window": {
    "frame": false
  },
```

Was broken and

```
  "window": {
    "frame": true
  },
```

Is fine. This only happened after upgrading from `v0.31.0`. Were there any changes that would have made this happen?
