### ISSUE TITLE
how to Call Node.js modules directly from Web Workers?

### ISSUE THREAD

**Issue by jackieron** [nwjs/nw.js#6823]
Hello, I see 0.33.4 There is such a new feature in this version: Call Node.js modules directly from the DOM and Web Workers.
I understand that the node.js module can be used directly in the web worker; so I try to use it in the worker.

Main.js
Let worker = new Worker('worker.js', {type : 'module'});

Worker.js

Const fs = require('fs') //Uncaught ReferenceError: require is not defined

Import { fs } from 'fs';

Onmessage = function ()
{
}

I tried two calls to the node.js module and I get an error.
I would like to ask, how can I use this new feature, can you give me a demo reference, thank you very much;

======== TEMPLATE BUG FORM ========

NWJS Version : 0.33.4
Operating System : windows 10

**Comment by jackieron** [comment]
thank you very much!
I have tried it and it works fine.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
