### ISSUE TITLE
Set breakpoint in asynchronous callback function, program flashback

### ISSUE THREAD

**Issue by jackieron** [nwjs/nw.js#6825]
Hello, I am having a problem when using version 0.33.4 sdk When I break the breakpoint in the asynchronous callback function, then F10 steps it, the program will flash back, The strange thing is that if I don't set a breakpoint, my program will run normally. And the same code, with 0.32.0 sdk There will be no flashback problem；

next I found the following information in the debug.log file:
[1010/171541.492:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: URL 未使用可识别的协议 (0x2ee6)

I very much hope that you will get your advice, thank you very much.

======== TEMPLATE BUG FORM ========

NWJS Version :0.33.4 sdk  use --mixed-context
Operating System : Windows10

My code is as follows：

index.html
<button id="load"></button>

app.js

class File
{
    load ()
   {
     fs.readFile(filePath, $.proxy(this._onLoad, this));
   }
_onLoad (err, data)
{
this._parseData(data);   // set breakpoint in this line. then F10 flashback 
}
_parseData  (data)
{
....
}
}

let file = new File();
$(document).ready(function()
{
$('#load').click(function()
{
file.load('d\\1.fcs');
});
})

**Comment by rogerwang** [comment]
Could you please provide a full sample?

**Comment by jackieron** [comment]
hello, my sample contains three files, app.html, app.js, file.js, the code is as follow:
**app.html**
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="jquery-3.3.1.min.js"></script>
    <script src="jquery-3.3.1.min.js"></script>
    <script type="module" src="app.js"></script>
</head>

<body>

    <button type="button" id="load">LoadFile</button>

</body>

</html>

**app.js**
import { File } from './file.js';

let file = new File();

$(document).ready(function ()
{
    $('#load').click(function()
    {
        file.loadFile("d:\\1.fcs");
    })
})

file.js
let fs = require('fs');
export class File
{
    constructor()
    {

    }

    loadFile (filePath)
    {
        fs.readFile(filePath, function(err, data)
        {
            console.log(data);   // set breakpoint on this line, then press F10 ，flashback
        });
    }
}

**package.json**

{
    "main": "app.html",
    "name": "Test",
    "version": "1.0",
    "chromium-args": "--mixed-context ",
    "window": {
    	"min_width": 1260,
    	"min_height": 680,
        "position":"center",
        "frame": false
    }
}

NW VERSION: 0.33.4 sdk x64
OS: windows 10 企业版 x64

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
