### ISSUE TITLE
About jQuery references. 

### ISSUE THREAD

**Issue by jackieron** [nwjs/nw.js#6828]
Hello,  I used the jQuery library in the html page. I quote jquery once code as follows: 
**<script src="jquery-3.3.1.min.js"></script>**
 nw.js will report an error: ### Uncaught ReferenceError: $ is not defined.
 but I quote twice, the code is as follows :
**<script src="jquery-3.3.1.min.js"></script>**
**<script src="jquery-3.3.1.min.js"></script>**, 
nw.js will not report jQuery Can work normally；
I really don't know why this is the case. Have you encountered such a problem and how is it solved?

======== TEMPLATE BUG FORM ========

NWJS Version : >= 0.20 sdk x64
Operating System :  >= windows 7

**Comment by gpetrov** [comment]
you have to specify `type="text/javascript"` to your script includes

**Comment by jackieron** [comment]
hello, i tried this method,but it still can't solve the problem

**Comment by TheJaredWilcurt** [comment]
should work like a normal browser. you need to import jquery before your code runs.

**Comment by fgroupindonesia** [comment]
me too... even after using

`<script type="text/javascript">window.$ 		= window.jQuery = require('jquery');</script>`

the file.js of my own jquery selector doesn't seems working :(

i think i missed something.
