### ISSUE TITLE
Xp sp3 cannot run properly with version 0.14.7

### ISSUE THREAD

**Issue by hxg543453406** [nwjs/nw.js#6830]
Xp sp3 cannot run properly with version 0.14.7 
The installation went smoothly.When I open the application, the nw software will open and exit immediately. I did not receive any error report

**Comment by TheJaredWilcurt** [comment]
NW.js 0.14.7 is the final version of NW.js to support XP. There are many industries (including governments, hospitals, kiosks, etc) that are still using XP in 2018.

@hxg543453406 0.14.7 works with XP. You may have done something wrong with the setup, or perhaps the machine you are using is locked down and requires admin access to run the executable.

**Comment by lover2668** [comment]
Can you help provide a download link for nwjs version that supports XP?

**Comment by sdtm1016** [comment]
> Xp sp3 无法正常运行版本 0.14.7
> 安装进展顺利。当我打开应用程序时，nw 软件将立即打开并退出。我没有收到任何错误报告

后续有没有进展？
