### ISSUE TITLE
Shouldn't the logo point north-west?

### ISSUE THREAD

**Issue by daverave1212** [nwjs/nw.js#6836]
I am sorry if this is not the best place to suggest this, but I noticed something strange about the logo.
It's compass pointing to north-east.
But it's NW not NE, so the logo should point the other way?
Thanks for the time.
[Logo](https://seeklogo.com/images/N/nwjs-aka-nodewebkit-logo-8B8DF3F5A5-seeklogo.com.png)

**Comment by Blatman** [comment]
@daverave1212 I think the assumption is that compass needles normally point North  so the top of the logo is pointing NW (direction of travel) - anyway I don't mind as long as the project doesn't go West!
:-)

**Comment by rogerwang** [comment]
Thanks to @Blatman for the answer 👍
