### ISSUE TITLE
Is it possible to read the snapshot file?

### ISSUE THREAD

**Issue by korner-brazers** [nwjs/nw.js#6842]
Hello

I previously asked: https://stackoverflow.com/questions/52928327/node-webkit-is-it-possible-to-read-the-snapshot-file

I would like to know, is it possible to read the bin file?

For example, take the source code of the node-webkit, find where the file is read and read everything.

I would like to protect my code completely, and now I am thinking of transferring parts of the code to the server for better protection, so that the code would be processed on the server and the result would be returned.

I do not want to mess around with the transfer of the code to the server, so I want to know for sure the protection of the snapshot?

**Comment by OsamaAbbas** [comment]
It is possible in theory. Just as people can decode Java bytecode, they can decode v8 byte code as well. They even can reverse engineer binary executables if they had to.

But in practice, no one would do it unless it is very urgent, it is almost always easier to write the code from scratch.

Check my repo (bytenode), you will find a similar tool (like `nwjc`) that compiles your code. The difference is that it compiles the code in the Node context too, not the browser context like `nwjc`.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
