### ISSUE TITLE
whew nw.Window.open a new_instance win； in the new win,  use nw.Window.open, in callback function get undefined

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6844]
[winundefine.zip](https://github.com/nwjs/nw.js/files/2524269/winundefine.zip)
![2151540798441_ pic_hd](https://user-images.githubusercontent.com/11750641/47635632-a84a1100-db90-11e8-8652-df90ddf972c9.jpg)
![2131540798348_ pic](https://user-images.githubusercontent.com/11750641/47635638-aaac6b00-db90-11e8-8f28-2679a315c154.jpg)

**Comment by rogerwang** [comment]
This is the duplicate of #4418
