### ISSUE TITLE
Document.execCommand("paste") is not working but Document.execCommand("cut") and Document.execCommand("copy") works fine.

### ISSUE THREAD

**Issue by abhijitca** [nwjs/nw.js#6846]
NWJS Version : 0.32.4
Operating System : Windows 10 & Windows 7

### Expected behavior

Paste using execCommand("paste") should work as expected and user should able to paste the data.

### Actual behavior

Cut or copy any data and try to paste the data using execCommand("paste") nothing works.

**Comment by TheJaredWilcurt** [comment]
Unable to reproduce. Used this code:

* [cutCopyPasteRightClick.zip](https://github.com/nwjs/nw.js/files/2564012/cutCopyPasteRightClick.zip)

Cut/Copy/Pasted worked fine in `0.32.4_64-sdk` and `0.34.2_64-sdk` on Win 10 64.

**Comment by xland** [comment]
nwjs: nwjs-sdk-v0.35.4-osx-x64
os: mac 10.14.2

document.execCommand("paste")   Not  Work!

I think paste should be a method of clipboard.
like:

> nw.Clipboard.get().paste()

Electron use webContents to do this

> (new BrowserWindow({//...})).webContents.paste()

**Comment by xland** [comment]
@abhijitca ,Have you fix this issue?

@xland

**Comment by abhijitca** [comment]
No not yet But I will try all the method mention above and let you know.

Thanks for the solution.

**Comment by TheJaredWilcurt** [comment]
@abhijitca @xland 

This code will work in any version of NW.js:

* https://github.com/open-indy/Koa11y/blob/3.0/_scripts/_functions/key-bindings.js

**Comment by xland** [comment]
@TheJaredWilcurt 
document.onkeydown is a listener of key press event.
We don't want to listen that event.
We want to execute the paste action manually.

**Comment by xland** [comment]
How about this issue's progress?
@rogerwang

**Comment by bluthen** [comment]
Document.execCommand('paste') works for me, programmatically not requiring user event in a nw frame.

**Comment by xland** [comment]
@bluthen 

Thanks, I'll test this on 0.36.0(the current version) a few days later.

**Comment by xland** [comment]
@bluthen 

No, It's not working for me

nwjs: nwjs-sdk-v0.36.1-osx-x64
os: mac 10.14.2

@rogerwang
