### ISSUE TITLE
input nwdirectory open file dialog lack of new directory button

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6848]
in 0.24.4
![image](https://user-images.githubusercontent.com/11750641/47772660-60f38a00-dd22-11e8-822a-f8145589ce74.png)
in 0.34.2
![image](https://user-images.githubusercontent.com/11750641/47772677-7072d300-dd22-11e8-9f55-2e80da6854a2.png)
[demo.zip](https://github.com/nwjs/nw.js/files/2533192/nwdirectory.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
