### ISSUE TITLE
0.35.0b1 - OSX - Quit App (cmd-Q) on menubar not working since 0.34.0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6851]
MacOS 10.13.6 High Sierra

Using Quit app or cmd-Q on the Mac menubar does not work - tested back and it broke at 0.34.0
Quit from a contextmenu or using right-click method on dock icon is fine.

Use test app from #6850 

Cheers.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
