### ISSUE TITLE
Crashed on loading app after updating NWJS

### ISSUE THREAD

**Issue by rhood2548** [nwjs/nw.js#6854]
NWJS Version : 0.34.1
Operating System : macOS High Sierra

### Expected behavior

Should start the application like it does with NWJS  v0.33.4

### Actual behavior

The application gets crashed and closed immediately with followed errors:

```#
# Fatal error in , line 0
# Check failed: receiver->IsJSFunction().
#
#
#
#FailureMessage Object: 0x7ffeebd406d00   nwjs Framework                      0x0000000106c13a6c v8_inspector::V8StackTraceId::IsInvalid() const + 7742460
1   nwjs Framework                      0x00000001098f597b v8_inspector::V8StackTraceId::IsInvalid() const + 54805259
2   nwjs Framework                      0x00000001098e6d85 v8_inspector::V8StackTraceId::IsInvalid() const + 54744853
3   nwjs Framework                      0x000000010616db78 v8::internal::Object::ToInt32(int*) + 7608
4   nwjs Framework                      0x000000010ab61203 v8_inspector::V8StackTraceId::IsInvalid() const + 74120083
5   nwjs Framework                      0x00000001066f01d1 v8_inspector::V8StackTraceId::IsInvalid() const + 2354017
6   nwjs Framework                      0x0000000105ce1e64 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) + 130964
7   nwjs Framework                      0x0000000105ce13ad v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) + 128221
8   nwjs Framework                      0x0000000105ce0b1a v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::BasicBlockProfiler const&) + 126026
9   nwjs Framework                      0x000000010654bc8e v8_inspector::V8StackTraceId::IsInvalid() const + 632350```

**Comment by rogerwang** [comment]
Could you please provide a sample so we can reproduce?

A crash dump file could be helpful too: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

**Comment by rhood2548** [comment]
[dump.txt](https://github.com/nwjs/nw.js/files/2538415/dump.txt)

**Comment by rogerwang** [comment]
Thanks. But the dump trace tool complains a version error with it. Are you sure it's generated when running with 0.34.2?

**Comment by rogerwang** [comment]
Unfortunately this still reports version mismatch. Given that the crash dump doesn't work, could you send me the application or a sample reproducing this?

**Comment by rogerwang** [comment]
@theDevelopper what the NW version with your dump file? The dump file has to be paired with the exact version so that it can be properly decoded.

**Comment by theDevelopper** [comment]
I used 0.34.5 sdk

**Comment by TheJaredWilcurt** [comment]
Make sure to delete your `node_modules` and `package-lock.json` when changing NW.js versions. Also make sure your global Node install matches the same version of Node that is in NW.js. Some node modules will detect your node version and do custom builds or downloads unique to your global node version during `npm install`.

**Comment by theDevelopper** [comment]
I did a fresh install via `npm ci` but having the correct node version locally is actually I good point. I will try that as soon as I can.

**Comment by theDevelopper** [comment]
I updated my node version to match nwjs. I reinstalled all dependencies via `npm ci` and it still crashes. I also confirmed that I have specified **nwjs 0.34.5 SDK** in my `package.json` devDependencies but I do not know how to check if the binaries that the _npm-installer module_ downloaded are actually of that version. I still get a crash.

Here is  a new dump:
[dump_0.34.5_sdk.txt](https://github.com/nwjs/nw.js/files/2619122/dump_0.34.5_sdk.txt)

**Comment by rogerwang** [comment]
@theDevelopper thanks for the dump file. I can see where it failed now with the dump and the error message. But it would be better to locate the root cause if we can get a sample to reproduce. Could you please send a sample program to reproduce this? Otherwise I could workaround it, but that leaves the root cause unfixed and might have other side effects.

**Comment by rogerwang** [comment]
@theDevelopper this is a build with the workaround you could try with: https://dl.nwjs.io/live-build/nw35/12-03-2018/a3819dda7/v0.35.0/

**Comment by theDevelopper** [comment]
thanks @rogerwang 
The provided nwjs 0.35.0 build seems to solve the issue.
I will try to reproduce the issue with a minimal sample, but it might take a while as I so far was not able to figure out at what point exactly it crashes and why and was therefore unable to duplicate the issue in a small sample. Any pointers would be helpful.

**Comment by rogerwang** [comment]
Good to know it working.

The full application is ok for me too, if it's good to send.
