### ISSUE TITLE
[Help Needed for Custom tilte bar on chromium container]

### ISSUE THREAD

**Issue by meraj321** [nwjs/nw.js#6855]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========
I want to create a custom title bar on chromium window (Native) so that to display our own custom icon and minimize, maximize buttons. Please help where to look into the code to accomplish this. 
We are using Node.js webkit with chromium container. Due to business requirement I am trying to achieve it from Chromium Native container side.

Thanks,
Meraj

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
