### ISSUE TITLE
wasm_exec.js from Golang causes NW.js to crash.

### ISSUE THREAD

**Issue by protosam** [nwjs/nw.js#6857]
I am using v0.34.1 of NWjs and I'm playing around with compiling to wasm with Golang. Overall I'm aiming to get this working in a web browser and in nwjs so I don't have to do some ghetto microservice for a local application. 

index.html that I run in nwjs contains:
```
<!doctype html>
<html>
<head>
	<title>Go wasm</title>
</head>
<body>
	<script src="wasm_exec.js"></script>
</body>
</html>
``` 

I got wasm_exec.js from the Go 1.11 package. It can also be acquired from the Golang 1.11 branch on the github repository: https://github.com/golang/go/blob/dev.boringcrypto.go1.11/misc/wasm/wasm_exec.js

This works in browser without issue. I wouldn't expect NWjs to crash.

**Comment by rogerwang** [comment]
Thanks for reporting. But it doesn't crash. It just thinks it runs in Node.js and quits:
```js
        if (isNodeJS) {
                if (process.argv.length < 3) {
                        process.stderr.write("usage: go_js_wasm_exec [wasm binary] [arguments]\n");
                        process.exit(1);
                }
```
