### ISSUE TITLE
Nwjs api does not work within iframe

### ISSUE THREAD

**Issue by banbuu16** [nwjs/nw.js#6862]
NWJS Version :0.26.6
Operating System :Windows 7

### Expected behavior

When iframe page use node.js function like "require", it does not work.

HTML structure is below.

  index.html >>  iframe [index2.html] >> iframe [index3.html]

All files are local file.

index3.html import the index3.js which use node.js function, but it does not work and 
show "require is not defined" in dev tools' console.

package.json is below
*****

```json
{
    "name": "test",
    "main": "index.html",
    "nodejs": true,
    "node-remote": "\*://\*/*",
    "description": "test",
    "chromium-args": "--enable-accelerated-layers --enable-gpu-rasterization --enable-accelerated-jpeg-decoding --allow-file-access-from-files --enable-threaded-compositing --prerender=enabled --ignore-gpu-blacklist --enable-smooth-scrolling --video-threads=3",
    "js-flags": "--expose-gc --always-compact",
    "window": {
        "toolbar": false
    },
    "webkit": {
        "plugin": true
    }
}
```

Please help.

**Comment by rogerwang** [comment]
Could you please provide a full sample so I can reproduce?

**Comment by banbuu16** [comment]
Thank you for your assistance.

[sample.zip](https://github.com/nwjs/nw.js/files/2571839/sample.zip)

The above sample is been able to reproduce.
Please unzip and set under C: drive.

**Comment by TheJaredWilcurt** [comment]
I have made a simplified reproduction:

* [package.nw.zip](https://github.com/nwjs/nw.js/files/2609557/issue-6862.zip)

Issue occurs when iframe src is set to an absolute filepath.

**Comment by rogerwang** [comment]
This is intended in the WIN32 API we are using: https://stackoverflow.com/a/26305323

Will find a way to workaround it.

**Comment by rogerwang** [comment]
This is expected as the iframe is not a Node frame. See http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/

You may want to track #6860 for matching a local url as Node frame, or place the file inside your application's directory and refer to it with `chrome-extension` protocol.
