### ISSUE TITLE
evalNWBin not working in iframe

### ISSUE THREAD

**Issue by starfall909** [nwjs/nw.js#6863]
NWJS Version : v0.33.4
Operating System : Windows 10 x64

< HTML STRUCTURE >
top
--iframe (#frameView_1)
--iframe (#frameView_2)
--iframe (#frameView_3)
--iframe (#frameView_4)

### Expected behavior
iframe context based:
`top.nw.Window.get().evalNWBin(null, 'myClass.bin');
var myClass = new MyClass();
console.log(myClass);`

> ƒ myClass() { [native code] } 

### Actual behavior
iframe context based:
`top.nw.Window.get().evalNWBin(null, 'myClass.bin');
var myClass = new MyClass();
console.log(myClass);`

> undefined

works well in top frame. 
but it occur undefined error in iframe.
so I did more test but i got a same error.

`top.nw.Window.get().evalNWBin(window.frameElement, 'myClass.bin'); `
(iframe context based, not worked)

`nw.Window.get().evalNWBin(window.frames[0].frameElement., 'myClass.bin');` 
(top context based, not worked)

`nw.Window.get().evalNWBin($("#frameView_1")[0].frameElement, 'myClass.bin');` 
(top context based, not worked)

### How to reproduce

Just simple.
make same html structure above.
and load compiled javascript file in iframe context.

pure javascript file (.js) is works well in iframe context.

I hope solve this problem as soon as possible.

**Comment by ffanny** [comment]
According to my tests, 
### iframe context based:
`nw.Window.get().evalNWBin(null, 'mytestobj.bin'); var testobj = new MyClass;  console.log(testobj);`
or
`top.nw.Window.get().evalNWBin(window.frameElement, 'mytestobj.bin'); var testobj = new MyClass;  console.log(testobj);`
works well.
### top context based:
` nw.Window.get().evalNWBin(window.frames[0].frameElement,"mytestobj.bin");
  nw.Window.get().evalNWBin(window.frames[1].frameElement,"mytestobj.bin")`
Same as the iframe context code, with equally good results .

**Comment by rogerwang** [comment]
close until more information is available.
