### ISSUE TITLE
Patch release points tagging

### ISSUE THREAD

**Issue by michalvasek** [nwjs/nw.js#6864]
NWJS Version: 0.34.2

Could you please add tags to mark release points (nw-v0.34.0, nw-v0.34.1, nw-v0.34.2)
- Chromium: https://github.com/nwjs/chromium.src (MISSING TAGS)
- NW.js: https://github.com/nwjs/nw.js (TAGS OK)
- Node.js: https://github.com/nwjs/node (MISSING TAGS)
- V8: https://github.com/nwjs/v8 (MISSING TAGS)

**Expected behavior like in nw31**

1) Visit https://github.com/nwjs/chromium.src
2) Look for "Code" --> "branches" --> "tags"
3) Search for "nw-v0.31"
4) See results
- nw-v0.31.0-beta1
- nw-v0.31.5
- nw-v0.31.4
- nw-v0.31.3
- nw-v0.31.2
- nw-v0.31.1
- nw-v0.31.0

_Git bash alternative_
```
MINGW64 /c/repos/nwjs/src
$ git tag | grep "nw-v0.31"
nw-v0.31.0
nw-v0.31.0-beta1
nw-v0.31.1
nw-v0.31.2
nw-v0.31.3
nw-v0.31.4
nw-v0.31.5
```
OK, tags are there.

**Actual behavior in nw34**

1) Visit https://github.com/nwjs/chromium.src
2) Look for "Code" --> "branches" --> "tags"
3) Search for "nw-v0.34"
4) See results
- nw-v0.34.0-beta1

_Git bash alternative_
```
MINGW64 /c/repos/nwjs/src
$ git tag | grep "nw-v0.34"
nw-v0.34.0-beta1
```
NOK, missing tags "nw-v0.34.0", "nw-v0.34.1", "nw-v0.34.2".

**Comment by rogerwang** [comment]
Thanks for reporting. We don't tag those repos any more because `content/nw/DEPS` file is introduced. You can get the commit id from that file under certain tag in the `nw` repo.

The three repos are now synced with `content/nw/tools/sync.py`. See discussion here: https://groups.google.com/d/msg/nwjs-general/rZQgiYl4aCI/iP_9ooNNDAAJ

**Comment by rogerwang** [comment]
PS: the documentation is not published as I'm still working on this, but if you want to sync with a version:
1. check out the tag of the NW repo.
2. run content/nw/tools/sync.py
