### ISSUE TITLE
Are 3rd-party modules sandboxed? knex, bookshelf, pg, pg.js all cannot access Postgresql server on same network

### ISSUE THREAD

**Issue by bzkdjc** [nwjs/nw.js#6866]
NWJS Version :  0.34.3 SDK (_whitelisted on firewall, so has full access to entire network_)
Operating System :  Windows 10 x64  1809

### Expected behavior

- [knex npm module](https://www.npmjs.com/package/knex) should get connected to local Postgres server on 127.0.0.1 (same machine) or on 192.168.1.102 (same net); same behaviour for `bookshelf`.
- [pg npm module](https://www.npmjs.com/package/pg) should get connected to local Postgres server on 127.0.0.1 (same machine) or on 192.168.1.102 (same net); same behaviour for `pg.js`.

### Actual behavior

All these modules stay on infinite attempt to connect until `TimeoutException`. None of them passes the `connecting` step.

### How to reproduce

On a fresh install of NW.js v0.34.3 SDK on Windows 10 x64 1809:

0. Install PostgreSQL v10 (to simplify, put `trust` to `pg_hba.conf` for all users on all DBs on host `127.0.0.1/32` and give it full access to local net)
1. Launch `nw.exe`, but before: show the Dev Tools window in `index.html` on a script tag inside the body tag, like this:
```html
<script>
let win = nw.Window.get();
win.showDevTools();
</script>
```
2. On the Console tab of the Dev Tools window, type the following either line by line or in one 'paste':
```javascript
const { Pool, Client } = require('pg')

const client = new Client({
  user: 'postgres',
  host: '127.0.0.1',
  database: 'postgres',
  password: '',
  port: 5432,
})

client.connect()

client.query('SELECT NOW()', (err, res) => {
  console.log('err', err)
  console.log('res', res)
  client.end()
})
```
3. The `console.log`s are never reached, as `connect()` never finishes.

### How I know something's wrong: 
I took some minutes to add Electron to the same folder on the same machine. I repeated the same steps above and everything went fine without any problem: the logs are printed (`err null` and `res ResultSet{...}`). 
I removed Electron and, back to NW.js, the same problem were still there.

**Comment by rogerwang** [comment]
They are not sandboxed. Will see what's wrong soon. Thanks.

**Comment by rogerwang** [comment]
I just tried your sample here and it works for me well.

**Comment by bzkdjc** [comment]
> I just tried your sample here and it works for me well.

Wow! 
What kind of problem could I have then? 

Any idea? Any solution to try?

**Comment by bzkdjc** [comment]
Just tried on my side => same problem; same result. 

Still looking for a solution. 
Will update as soon as I find something relevant.

**Comment by rogerwang** [comment]
A wild guess is that the console log is not printed to the console? Just check the devtools, or the devtools console of the background page. In fact, I tried your code snippet by including them in a html file and point package.json to it.

**Comment by bzkdjc** [comment]
I had to activate `debug`mode on "knex.js" in order to see Timeout Error. 
The most bizarre part of this issue is that elsewhere (_e.g. electron_) it works! 

1-line to fetch one record from Postgres using knex ORM: 
```javascript
new Utilisateur({login: 'dan'}).fetch().then(d=>{console.log(d)}).catch(e=>{console.error(e)})
```
On NW.js (DevTools) 
<img width="722" alt="2018-11-14 23_29_54-devtools - chrome-extension___mjbggnfoccjkbhannaafcabegdiapdja_index html" src="https://user-images.githubusercontent.com/13347655/48519785-0f8ce400-e866-11e8-9eb7-757f8c6cd32b.png">

On Electron (Developer Tools)
<img width="896" alt="2018-11-14 23_27_46-developer tools - file____d__local_src_gappi-for-electron_index html" src="https://user-images.githubusercontent.com/13347655/48519837-482cbd80-e866-11e8-8d8e-da5e6f57198e.png">

Do you see? 
There's a timeout while attempting to acquire connection when using NWjs, while the connection is immediately acquired when using Electron where, after some debug output, we get what was `console.log`'ed at last.

=> I thought it was a 'knex' bug until I tried the same folder of code under Electron.

The same happens when using `bookshelf` or `pg` npm modules.

**Comment by rogerwang** [comment]
Could you upload a full sample app? (Not copy/paste in devtools). In this way we can rule out some factors.

**Comment by rogerwang** [comment]
Here is my test which passes here:

package.json:
```
{
  "name": "nw-demo",
  "main": "index.html"
}
```

index.html:
```
<script>
const { Pool, Client } = require('pg')

const client = new Client({
  user: 'postgres',
  host: '127.0.0.1',
  database: 'postgres',
  password: '',
  port: 5432,
})

client.connect()

client.query('SELECT NOW()', (err, res) => {
  console.log('err'+ err)
  console.log('res'+ res)
  client.end()
})
</script>
```

**Comment by rogerwang** [comment]
close until more information is available.
