### ISSUE TITLE
win.print () has stopped working

### ISSUE THREAD

**Issue by djl1965** [nwjs/nw.js#6867]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.33.0 and above
Operating System : Windows 7 and above

### Expected behavior

win.print () should open print dialog

### Actual behavior

dialog dosn't open from 0.33.0 onwards

This code works 0.32.4 but not since

	var html = "<style>@page { margin: 0; } body { margin: 1.6cm; }</style>" +
		"<div style='font-family:courier; white-space:pre-wrap'>Hello World</div>";
	var printwin = window.open ("", "_blank", "", "");
	printwin.document.write (html);
	printwin.print ();
	printwin.close ();

**Comment by rogerwang** [comment]
The initial url of the window should be given something like 'about:blank', or the blink engine thinks the document is still in loading state and block the printing request.

**Comment by djl1965** [comment]
Thanks – that works and has been tested on 34.3

 

Regards

 

Dave
