### ISSUE TITLE
￼Using nw.Shell.openExternal using the "file://" protocol don't pass url params/hashs

### ISSUE THREAD

**Issue by Leprosy** [nwjs/nw.js#6870]
NWJS Version : nw.js v0.34.4
Operating System : Ubuntu 17.10

If I do `nw.Shell.openExternal("http://www.google.com/#test")` the default browser opens the google home page, and the hash `#test` is at the end of the URI

But doing `nw.Shell.openExternal("file:///home/myuser/index.html#test")` the browser only opens the `file:///home/myuser/index.html` URI and the hash is gone.

Is there any workaround for this?

Thanks!

**Comment by TheJaredWilcurt** [comment]
Confirmed that issue occurs in 0.12.3, 0.14.7, and 0.34.2 (presumed all versions effected).
