### ISSUE TITLE
Webview often crashes

### ISSUE THREAD

**Issue by 102286545** [nwjs/nw.js#6872]
I use webview tags to make a multi-tag browser.
Some sites cause webivew to crash.
No event triggered after webview crash.

like this:
http://www.sucaidao.com/crash.png
(Please open this picture URL in the browser)

NWJS Version :all version
Operating System :windows 7,windows 10

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by 102286545** [comment]
The problem with this crash is not a specific page and a specific time, but a crash while browsing the site.
I've tried a lot of versions of nw.js that have this problem.
The code. I'm packing it in here:
http://www.sucaidao.com/codes.zip

You need to constantly open the page or close the page to trigger.
It's possible that you'll find this problem very soon, or maybe you'll find it in 1-2 minutes.
Thank you very much for answering this question.

**Comment by TheJaredWilcurt** [comment]
I am able to reproduce the bug consistently with
```json
{
  "name": "myapp",
  "main": "index.html"
}
```
```html
<!DOCTYPE html>
<html>
  <head>
    <title>My App</title>
  </head>
  <body>
    <webview allownw src="http://v.ifeng.com/201811/video_28479270.shtml"></webview>
  </body>
</html>
```
If you remove the `allownw` the bug stops.

**Comment by 102286545** [comment]
Thank you very much. I'll test it again.

**Comment by TheJaredWilcurt** [comment]
Bug does not occur in 0.20.0-beta2 and below.
Bug does occur in 0.20.0-rc1 and above.

**Comment by 102286545** [comment]
What causes this error to occur in higher versions

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by 102286545** [comment]
That's good news.

**Comment by rogerwang** [comment]
Please try this build: https://dl.nwjs.io/live-build/nw35/11-22-2018/95f36c100/v0.35.0/

**Comment by rogerwang** [comment]
The code in https://github.com/nwjs/nw.js/issues/6872#issuecomment-440894050 works well for me with the new build. 

I can reproduce the crash with OP's sample app with the new build, but it's due to a new cause, which is out of memory error. There could be a leak in the application or NW. Launching devtools on the webview and inspecting the heap would help.
