### ISSUE TITLE
how to run cluster with nwjs?

### ISSUE THREAD

**Issue by saikoux12** [nwjs/nw.js#6877]
i try to run node cluster with nwjs in windows or mac. but the child process can not run.
cluster.fork() is success.. 
does someone else have run this?

**Comment by TheJaredWilcurt** [comment]
@saikoux12 can your provide a [minrepro](https://stackoverflow.com/help/mcve)

**Comment by eikcalb** [comment]
I'm currently experiencing a similar issue

**Comment by TheJaredWilcurt** [comment]
Possible duplicate issue:
https://github.com/nwjs/nw.js/issues/6199

If so, this issue should be closed.
