### ISSUE TITLE
Projects developed by NW.JS cannot pass PUBG game security check

### ISSUE THREAD

**Issue by sdycn2012** [nwjs/nw.js#6879]
The PUBG game security detection is described as follows:

12:06:40: Starting BattlEye Service...

12:06:44: Launching game...
12:07:56: Note: File blocks can be ignored if they don't cause problems with the game.
12:07:56: [INFO] Blocked loading of file: "C:\Users\Administrator\Desktop\nwjs-v0.34.5-win-x64\nwjs-v0.34.5-win-x64\nw.exe".

![1](https://user-images.githubusercontent.com/16742453/49352851-59464d00-f6f5-11e8-80b7-c3a8b122398b.png)

This caused a lot of trouble for me.
Help! My Email:541923549@qq.com
Thank you!

**Comment by rogerwang** [comment]
Please report this issue to PUBG. Thanks.

**Comment by rogerwang** [comment]
Closing as this should be an issue of PUBG.
