### ISSUE TITLE
How to pop up a system dialog that shows the path of the system?

### ISSUE THREAD

**Issue by TongDaDa** [nwjs/nw.js#6882]
Hi, I am an NW green hands and this issue is a help requesting.

Now, I encounter a demand that shows a system path to provide to users to select it, just like file-input on a webpage.

I also try to realize it by file-input of a webpage, It's more like picking a file or folder, not a path, which is not what I want.

What I want is to pop-up system box and select an arbitrary path, which can be passed to me after the user selects it.

After looking up the NW API documentation, I am not looking for any solution.

======== TEMPLATE BUG FORM ========

NWJS Version :
70.0.3538.110

Operating System :
MacOS

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by TongDaDa** [comment]
Thanks @rogerwang

**Comment by TongDaDa** [comment]
No one replies me.

**Comment by TheJaredWilcurt** [comment]
https://github.com/nwjs/nw.js/issues/6883
