### ISSUE TITLE
How to use nw to pop up a path to select the system popup?

### ISSUE THREAD

**Issue by AryaSpinnet** [nwjs/nw.js#6883]
Hi😳, Now I have a problem, I want the user to choose a fixed path, and then after I choose to complete, I can write some files according to this path. The question is, how does the system pop-up box trigger? I only see the input on the official documentation, but it doesn't solve my problem. What I want is a system popup that can choose any path.

System Mac.
Latest NW.

**Comment by TheJaredWilcurt** [comment]
```html
<input type="file" nwdirectory onchange="theyPickedSomething(event)">
<script>
  function theyPickedSomething (event) {
    let file = event.target.files[0];
    console.log(file.path);
  }
</script>
```
I think that should work. For more information:

* http://docs.nwjs.io/en/latest/References/Changes%20to%20DOM/#attribute-nwdirectory

In the future, use the chatroom or google group for usage questions. They are in the footer on [NWJS.io](https://nwjs.io) as "Chat on Gitter" and "Mailing List".

**Comment by AryaSpinnet** [comment]
The input doesn't solve my problem, I want to find a box of system that is initiative to be selected, because the input popup-mode is required users to select a `file`, but not file, I want that is just `any path`, are you understood?
