### ISSUE TITLE
Add ffmpeg librarie to run mp4 videos

### ISSUE THREAD

**Issue by BaptisteGavalda** [nwjs/nw.js#6885]
I'm trying to display a video with nwjs but I had this error : 
`[25955:35843:1204/115855.825589:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA
_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}`
If I well understand this error occure because the ffmpeg librarie is not in nw.
So I tried to follow this tutorial : [Using MP3 & MP4 (H.264) using the video & audio tags.
](https://github.com/nwjs/nw.js/wiki/Using-MP3-%26-MP4-%28H.264%29-using-the--video--%26--audio--tags.)
I have many problems.
I'm on mac so I follow 

> Head to your Applications folder and right-click on Google Chrome. Select Show Package Contents and navigate to Versions > Most recent # > Framework > Libraries.

But their is no `ffmpegsumo.so` here so I found one on the internet.

> Copy ffmpegsumo.so to nwjs.app/Contents/Frameworks/nwjs Framework.framework/Libraries/

I copyied it but when I re-run nw my error was still here, my library could be not a good one so I want to build it myself.

> If you are building nw.js, open src/third_party/ffmpeg/chromium/scripts/build_ffmpeg.sh, and search around line 379 for the following directives:

Their is no such directories and file, where can I find it ?

I hope someone could help me. Thanks.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by TheJaredWilcurt** [comment]
@BaptisteGavalda that link is for an older version of NW.js, refer to the latest documentation

* http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs
