### ISSUE TITLE
input file nwsaveas property is ignored

### ISSUE THREAD

**Issue by odrevet** [nwjs/nw.js#6886]
NWJS Version : nw-v0.35.0
Operating System : 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux

### Expected behavior

The file dialog presented should been a 'save as' dialog

### Actual behavior

The file dialog presented is an 'open file' dialog

### How to reproduce

Create a file dialog like in the example at https://github.com/nwjs/nw.js/wiki/file-dialogs#save-file and try to save as

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw35/12-06-2018/af60c1e7c/v0.35.1/

**Comment by odrevet** [comment]
thanks your this fast fix
