### ISSUE TITLE
how to modify the process name  in the task manager?

### ISSUE THREAD

**Issue by ChaoshengZhang** [nwjs/nw.js#6887]
NWJS Version :0.34.5
Operating System :window 10

### Expected behavior

I want to modify the process name of nwjs in the task manager.

### Actual behavior

The api documentation does not have a configuration item for this.

### How to reproduce
Ctrl+Alt+Delete  View the process name and find it all nwjs

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
