### ISSUE TITLE
[IssueHuntFest] Destructing classes inside async workers

### ISSUE THREAD

**Issue by Yash-Garg** [nwjs/nw.js#6890]
NWJS Version : 0.30.0
Operating System : Debian Sid Linux

Expected behavior
C++ class destructor only gets triggered when all processes working with it is done

Actual behavior
C++ class destructor getting triggered for random and unknown reasons

How to reproduce
Create an object wrapped C++ addon and pass an instantiated random and custom class to Nan::AsyncWorker after some time nw.js will destroy the class you passed to it after Execute() is done (if you reference this class inside JS code it won't happen), not sure why's that happening but that doesn't happen in Node.js v10, not sure if it's a problem with node.js, nw.js or my code. Let me know if you need more information

**Comment by rogerwang** [comment]
That's triggered when the JS object is garbage collected. When you hold a reference to the object it won't be collected. And you can not predict when the GC kicks in.
