### ISSUE TITLE
Blocked a frame with origin "chrome-extension://fdcokklnjfheiianlphgljlimmaaidcm" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by mregiste** [nwjs/nw.js#6893]
NWJS Version : v35.0
Operating System : Windows 10

### Expected behavior

Allow access to iFrame contentWindow.location.href

### Actual behavior

index.html:6 Uncaught DOMException: Blocked a frame with origin "chrome-extension://fdcokklnjfheiianlphgljlimmaaidcm" from accessing a cross-origin frame.
    at accessLocation (chrome-extension://fdcokklnjfheiianlphgljlimmaaidcm/index.html:6:64)
    at <anonymous>:1:8
[test.zip](https://github.com/nwjs/nw.js/files/2663343/test.zip)

### How to reproduce
index.html
```
<html>
<head>
    <script type="text/javascript">
        function accessLocation() {
            let frame = document.getElementById('testFrame');
            console.log("href: " +frame.contentWindow.location.href);
        }
    </script>
</head>
<body>

    <iframe id='testFrame' src='https://accounts.google.com' style="width: 100%;height: 100%" nwfaketop/>

</body>
</html>
```

package.json
```
{
  "name": "Test",
  "main": "./index.html",
  "version": "4.2.0-dev",
  "window": {
    "title": "CSP Test",
    "show": true,
    "frame": true,
    "width": 671,
    "height": 700,
    "id": "1"
  },
  "node-remote": [
    "*://*"
  ]
}
```

Run against any version of nwjs, launch devtools and in the console enter "accessLocation()"

**Comment by rogerwang** [comment]
It works for me:

```html
<html>
<head>
    <script type="text/javascript">
        function accessLocation() {
            let frame = document.getElementById('testFrame');
            console.log("href: " +frame.contentWindow.location.href);
        }
    </script>
</head>
<body>

    <button onclick="accessLocation()">test</button>
    <iframe id='testFrame' src='https://trello.com' style="width: 100%;height: 100%" nwfaketop/>

</body>
</html>
```
```json
{
  "name": "myapp",
  "main": "index.html"
}
```

**Comment by mregiste** [comment]
My mistake, the code I posted should be for "https://accounts.google.com", Trello works fine and google fails.

**Comment by rogerwang** [comment]
Then it should be the duplicate of #6894, which was just fixed in git . Please wait for the next nightly build and try again.

**Comment by mregiste** [comment]
If I understand #6894 correctly, they are doing “—disaable-web-security” does this make my app vulnerable, my app can launch any 3rd party site and I though putting them in and iFrame and setting “nwfaketop” would protect my app

**Comment by rogerwang** [comment]
That switch is not relevant to the issue. It's not needed for the fix to be effective.

**Comment by satdevops88** [comment]
> It works for me:
> 
> ```
> <html>
> <head>
>     <script type="text/javascript">
>         function accessLocation() {
>             let frame = document.getElementById('testFrame');
>             console.log("href: " +frame.contentWindow.location.href);
>         }
>     </script>
> </head>
> <body>
> 
>     <button onclick="accessLocation()">test</button>
>     <iframe id='testFrame' src='https://trello.com' style="width: 100%;height: 100%" nwfaketop/>
> 
> </body>
> </html>
> ```
> 
> ```json
> {
>   "name": "myapp",
>   "main": "index.html"
> }
> ```

It does not work for me.
Can you help me with this?

**Comment by thehovercam** [comment]
@rogerwang This function stops working in 0.42.0.  Is there any way to fix it? 

> It works for me:
> 
> ```
> <html>
> <head>
>     <script type="text/javascript">
>         function accessLocation() {
>             let frame = document.getElementById('testFrame');
>             console.log("href: " +frame.contentWindow.location.href);
>         }
>     </script>
> </head>
> <body>
> 
>     <button onclick="accessLocation()">test</button>
>     <iframe id='testFrame' src='https://trello.com' style="width: 100%;height: 100%" nwfaketop/>
> 
> </body>
> </html>
> ```
> 
> ```json
> {
>   "name": "myapp",
>   "main": "index.html"
> }
> ```

**Comment by rogerwang** [comment]
Will look into it.

**Comment by josh83abc** [comment]
Hello Rogerwang, I also using the remote iframe access in my app and I confirm that the simple example above doesn't work anymore starting to v40.0 (I tried all NWJS version to see when it stop working). Would be great if you can have a look on it :). Thanks again for your amazing work!

**Comment by rogerwang** [comment]
This build should fixed it https://dl.nwjs.io/live-build/nw42/11-09-2019/34918be40/v0.42.4/

**Comment by rogerwang** [comment]
This should be the duplicate with #7173

**Comment by thehovercam** [comment]
Hi @rogerwang It's still not working in 0.42.4  There is no error popup, but it's 'undefined', and if I do  console.log(frame.contentWindow);  Nothing shows up in console.  Could you please verify it again?
Thank you.
Here are two screen shots of console when I test it with different versions of nwjs.

![image](https://user-images.githubusercontent.com/4604316/68721400-1462a180-0567-11ea-9fdd-74cc48b75b2b.png)

![image](https://user-images.githubusercontent.com/4604316/68721426-2f351600-0567-11ea-8387-28472960dde8.png)

```
<html>
<head>
    <script type="text/javascript">
        function accessLocation() {
            let frame = document.getElementById('testFrame');
			console.log(process.versions['node-webkit']);
			console.log(frame.contentWindow.location.href);
            console.log(frame.contentWindow);
        }
    </script>
</head>
<body>
    <button onclick="accessLocation()">test</button>
    <iframe id='testFrame' src='https://trello.com' style="width: 100%;height: 100%" nwfaketop nwdisable/>
</body>
</html>
```

**Comment by rogerwang** [comment]
Thanks I just noticed that. Please follow up in #7173 and I’ll fix it soon
