### ISSUE TITLE
disable web security doesn't work

### ISSUE THREAD

**Issue by smurfiez** [nwjs/nw.js#6894]
NWJS Version : 0.34.5-sdk
Operating System : Windows

### Expected behavior

I'm trying to access a google account via an iframe, using disable web security I'm expecting that I should be able to view at least the document location.

### Actual behavior
```
main.html:33 Uncaught DOMException: Blocked a frame with origin "chrome-extension://pnmfgloclchaammoaigmkelpmkfdkkfi" from accessing a cross-origin frame.
    at onLoad (chrome-extension://pnmfgloclchaammoaigmkelpmkfdkkfi/main.html:33:36)
    at HTMLIFrameElement.onload (chrome-extension://pnmfgloclchaammoaigmkelpmkfdkkfi/main.html:26:84)

```

I'm getting this error

### How to reproduce

```
<!DOCTYPE html>
<html>
<head>
<title>Zoek and Kopen 2</title>

  <style>

    html {
      height: 100%;
    }

    body {
      height: 92%;
    }

    iframe {
      width: 100%;
      height: 90%;
      box-sizing: border-box;
    }  
  </style>
</head>
<body>


  <iframe src="https://contacts.google.com/" nwdisable nwfaketop onload="onLoad()"></iframe>

  </iframe>

</body>
<script>
  function onLoad() {
      console.log(window.frames[0].document.location);
  }
</script>
</html>

```

nwjs is launched with`  --user-data-dir="" --disable-web-security `

**Comment by smurfiez** [comment]
Is there any workaround for this?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
btw, the switch `disable-web-security` is not relevant to the issue. It's not needed for the fix to be effective.
