### ISSUE TITLE
Download server at dl.nwjs.io is missing subdirectory in index listing

### ISSUE THREAD

**Issue by julijane** [nwjs/nw.js#6895]
Now this seems to be a strange one.

Open https://dl.nwjs.io/ and notice that the subdirectory "v0.35.0" is not listed even though it exists:
https://dl.nwjs.io/v0.35.0

**Comment by rogerwang** [comment]
Thanks. The root directory is a static page while the site serves as a cache to AWS S3, where the files reside. Will update the listing soon.

**Comment by rogerwang** [comment]
It's fixed now.
