### ISSUE TITLE
How to update files in a bundled application

### ISSUE THREAD

**Issue by AryaSpinnet** [nwjs/nw.js#6896]
I have a problem again..., that is, the resources used in the pages of my nw application are packaged into the nw application. If I want to update a picture or html, js, css changes, do I still need to use node- Is webkit-updater updated? If you use it, you will need to reinstall the application, and what I want is that in addition to the nw related changes (the resources in the html file) can be hot updated.

Hot updates, which is what the user can't detect, update the resources.

Initially I was in development mode, trying to directly replace the resource folder, and later found that the package after the production mode build is not in the development mode of the file structure.

Sorry, I know that type of problem need to go to community of Nw.Js of Google, but there no one reply me.

what should I do? 😢

I want hot-update resource in my application.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by AryaSpinnet** [comment]
There is cemetery, no community @rogerwang

**Comment by rogerwang** [comment]
Unfortunately the issue system serves as task tracking for developers, not discussion board.
