### ISSUE TITLE
nwjc command line does not work

### ISSUE THREAD

**Issue by dotbloup** [nwjs/nw.js#6897]
NWJS Version : 0.35.1-sdk
Operating System : MaxOS mojave

### actual marshmallow

> Failed to open startup resource 'natives_blob.bin'.
> Failed to open startup resource 'v8_context_snapshot.bin'.
> 
> 
> #
> # Fatal error in , line 0
> # Check failed: !create_heap_objects_.
> #
> #
> #
> #FailureMessage Object: 0x7ffee0934010
> ==== C stack trace ===============================
> 
>     0   nwjc                                0x000000010fc347d3 v8::platform::WorkerThread::Run() + 1303075
>     1   nwjc                                0x000000010faf368b v8::platform::DefaultPlatform::GetStackTracePrinter() + 43
>     2   nwjc                                0x000000010fc30795 v8::platform::WorkerThread::Run() + 1286629
>     3   nwjc                                0x000000010f9f020b v8::internal::TurboAssembler::ResetSpeculationPoisonRegister() + 3483
>     4   nwjc                                0x000000010f71a547 v8::internal::Isolate::OptionalRescheduleException(bool)+ 11063
>     5   nwjc                                0x000000010f2d300a v8::SnapshotCreator::SnapshotCreator(long const*, v8::StartupData*) + 234
>     6   nwjc                                0x000000010f2cc63d nwjc + 5693
>     7   libdyld.dylib                       0x00007fff6edffed9 start + 1
> Illegal instruction: 4

# how to reproduce
I installed nwjs using npm i nw@0.35.1-sdk -g

nwjc does work when i call it directly using 
`>/usr/local/npm_packages/lib/node_modules/nw/nwjs/nwjc  file.js file.bin` 

However, it does not work when i call it like: 
`>nwjc file.js file.bin`

I tried to add the directory to my bash_profile file but it does not work.

```
eval $(/usr/libexec/path_helper -s)
export PATH=$HOME/node_modules/:/usr/local/bin:/usr/local/npm_packages/lib/node_modules/nw/nwjs:$PATH


export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
[[ -s ~/.bashrc ]] && source ~/.bashrc
```

any idea?

**Comment by rogerwang** [comment]
As it reported, you should have those two .bin files in the same directory with nwjc.
