### ISSUE TITLE
How to use with nuxt.js?

### ISSUE THREAD

**Issue by webkitten** [nwjs/nw.js#6898]
Hi! Anybody knows how to use nw.js with nuxt.js?

**Comment by TheJaredWilcurt** [comment]
Never used Nuxt, but here is a Vue + NW.js tutorial that may be helpful in a more general way:

* https://www.youtube.com/playlist?list=PLmJs3lfUmCdT9MyG60Oo6HM7xAn79vwZ0

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
