### ISSUE TITLE
Why does nw.js see a different number of processes in task manager every time you restart it

### ISSUE THREAD

**Issue by jackieron** [nwjs/nw.js#6904]
Why the number of processes seen in task manager is different each time nw.js is restarted; And the amount of memory is different each time; I am more curious, the same program, each start, the number of processes and memory use, should be close;

I want to know what tasks each process handles; Because in my work, I found that the CPU utilization of a process is very high, I would like to ask how to debug a process alone to find the problem of excessive CPU utilization;

thanks very much!!!

NWJS Version : NW.JS 0.35.0 SDK X64
Operating System : WINDOWS 10 企业版 64位

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
