### ISSUE TITLE
Window.open not always working correctly

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#6908]
NWJS Version : v0.35.2
Operating System : Windows 10

### Expected behavior

Window.open should open the exact same window whenever called.

### Actual behavior

If called from a second window, no matter how, using window.opener.thefunction() it won't work. Even If you try something really "complex" like the second window sending a string to a function in the first, which stores it in a variable, then another function inside a setInterval checking for changes in that variable will pick the value and insert it in a window.open. Even that doesn't work.

I believe this happens when using node/nwjs code in the window. Some times the window.open works(in the complex scenario said above) partially with them or without it. But i'm using --mixed-context in my application, so I expected it to always do.

### How to reproduce

I made a function inside the main window of nwjs which is the following:
```
testopeneditor=function(){
 wndo = window.open("./editor/main.html", "", "scrollbars=1,width=550,height=620");
wndo.moveTo(screen.width/2-250,screen.height/2-175);

}
```
When executed from the main window, it works perfectly. But if in the opened window try calling it using "window.opener.testopeneditor()" it doesn't work(It opens a blank window).

**Comment by tolrtd** [comment]
I am only guessing as I don't see any more of your code, but more than likely the code is being run with the relative path "./editor/main.html" being relative to the other window you are opening it from and not from window.opener.  Try using hardcoded paths or fix your directory structure.

**Comment by elpeleq42** [comment]
It happens even using full path. As I said, for some reason, this problem is "random". With some pages it happens(and nothing shows), with others it doesn't, and some even load partially

**Comment by elpeleq42** [comment]
I truly believe this is a bug. I tested it today in my application the following way:
I opened the application and ran Developer tools. It was loaded using the local path like this:
chrome-extension://dcabhanapgfcaciefidifkflldckmhgl/index.html
the console shows some errors, but nothing that affects the application itself.
Then Opening a new window, using window.open() through the original NWjs window and checking the dev tools again, results in the same stuff.
But If I open a window(window.open or nw.Window.open) and that second window sends an command to the opener window to open another, the paths and errors changes. 
Path: file:///C:/Users/gabri/Desktop/jitjs/index.html

Image of errors:
https://i71.servimg.com/u/f71/15/27/47/75/sem_tz12.png

It also accuses "nw is not defined" in the second case. Then I made a simple page with a NWjs menubar to test, and the same happened when a second window sends to the first a call to open it(or open by itself). So it seems that if the any second window try to open a new window, that new window doesn't have access to mixed context mode, which breaks most or all of it.

@rogerwang 
(I know its kinda confusing but i'm also having trouble to understand the cause of it)

**Comment by elpeleq42** [comment]
Actually by the looks of it, using complete path may be the cause of the problem.
Whenever I use a full path, it either doesn't allow me to access the file or it's not able to run nodejs stuff within it.

https://i71.servimg.com/u/f71/15/27/47/75/sem_tz12.png
(See "Require not defined" and "nw not defined")
The original window refers to when I open the initial window of my application using relative path
The "window opened by another window" refers to when I use the full path to the HTML file

It seems that NWjs loads then differently when its full path and when its relative. In one case, the HTML is loaded as a webpage in chrome context, the other it runs normaly as it should(with mixed mode).

@rogerwang is it a bug? Or a expected behavior?

**Comment by ffanny** [comment]
According to my tests, when use full path the HTML is loaded as a webpage in chrome context as you say.
And when I use nw.Window.open (relative path), the new window always loads correctly; but window.open(relative path) couldn't satisfy the purpose.
