### ISSUE TITLE
NWJS 0.35.2 calls to IANA at startup

### ISSUE THREAD

**Issue by Reaktive** [nwjs/nw.js#6909]
When initializing, NWJS is trying to connect to the IP 239.255.255.250 ( I.A.N.A. - Internet Assigned Numbers Authority ). 

This should be avoidable so we can have fully offline and private apps developed using NWJS.

Now that the problem with[ NWJS calling home](https://github.com/nwjs/nw.js/issues/5865) is solved, we have this new one. 

The procedure when trying to detect that connection is similar to the referenced issue:

1. Install a Firewall
2. Put the firewall in "Paranoid Mode"
3. Open NWJS
4. See that firewall alert popup

**Comment by rogerwang** [comment]
It seems to be multicast address for chrome cast feature. And it may be turned off, see https://productforums.google.com/forum/#!msg/chromecast/WsbZQaDt9Q0/pem7fY6UAAAJ

Ref #5264

**Comment by Reaktive** [comment]
Great, in the meantime i'll be looking at how to turn that off. 

Thank you.

**Comment by rogerwang** [comment]
Closing as it's reported working in the mailing list: https://groups.google.com/d/msg/nwjs-general/lfnX7ZddhI0/Kx8DAjbnEwAJ

**Comment by Reaktive** [comment]
Hi guys, I just wanted to tell you that this keeps happening in the **0.46.2** version. Even if we setup a chromium flag with a proxy pointing to 127.0.0.1 and turning off media-router, we keep getting "non-requested" external connections.

Exactly the same behaviour as before, NWJS is trying to connect to the IP 239.255.255.250

**Comment by dissociativity** [comment]
This still appears to be occurring
