### ISSUE TITLE
Why cannot play some video

### ISSUE THREAD

**Issue by Bahramudin** [nwjs/nw.js#6911]
NWJS Version : 0.35.3
Operating System: Windows 10 64Bit

### Expected behavior

I have some videos in my page that some of them can play, but some not.
The one which cannot play is H264 Mp4 video format.

How let NWJS can play videos?

Thanks!!

**Comment by Bahramudin** [comment]
I have solved the problem [here](https://github.com/nwjs/nw.js/issues/5859)

**Comment by rogerwang** [comment]
closing as duplicate.
