### ISSUE TITLE
Mousewheel scroll stopped working

### ISSUE THREAD

**Issue by vankasteelj** [nwjs/nw.js#6920]
NWJS Version : 0.35.1-sdk (I believe I saw it on 0.34.x versions as well)
Operating System : Windows 10 x64

**The issue:** (using an app I'm writing) sometimes the "mousewheel scroll" stops working for no apparent reason. Scrolling the wheel on my mouse doesn't do anything.

**Some notes/debugging:**
- I can still scroll using `window.scrollTo()`
- I can still scroll dragging the scrollbar
- manually adding a `$(document).on('wheel', (e) => console.log(e))` does report wheel scrolls, but nw itself doesn't seem to see or act on it. The document doesn't scroll. It is not defaultPrevented either.
- I don't use any kind of 'wheel' event modification in my code.
- I was able to fix it with a 'wheel click' (also know as middle-click) to scroll the document with only the mouse dragging. After that, the scroll wheel worked again.
- I do have a lot "dom-banging" (I believe it's called that) in my app, using entire pages .show() and .hide(), as well as a fairly good amount of .append(), all using jQuery. Dunno if that's relevant.

**Steps to reproduce:** sorry, no idea. It happens randomly, maybe once every 10 hours of using nwjs, or even every 20 hours. Not often though.

**Comment by TheJaredWilcurt** [comment]
That's weird, I had the same thing happen to me on Chrome Canary like a week or two ago. It kept coming and going for like a week until I updated. Not sure if just restarting the browser fixed it, or if the bug was specific to that version.

Can you try the new NW.js v0.36.x

* https://nwjs.io/downloads

**Comment by TheRealDannyyy** [comment]
I think this is a Chromium issue, it happens to be fairly often as well, when using sites like Twitter.
For some reason pressing the mouse wheel button fixes it but the cause is still unknown as far as I know.

**Comment by McGiverGim** [comment]
I think I'm having the same problem all the time. Is not a random bug, I have it always.

I'm a developer of Betaflight, and we are using NW for the Blackbox Viewer application. We have a modal window that shows some data. This Window was scrollable without problem in version 0.31.4 but after updating to version 0.35.3 the scroll is not working anymore. I have tested too versions 0.35.5 and 0.36.0-beta1, without luck.

The strange thing is that if I resize the parent window, then the modal window scroll works again.

**Comment by McGiverGim** [comment]
After some tests, the bug appears in version 0.33.0. With version 0.32.4 I have no problem and it works, if it helps.

**Comment by McGiverGim** [comment]
If it helps someone... seems that latest beta fixes the problem, at least for me: 0.38.0-beta1
