### ISSUE TITLE
First opening of NW.js doesn't get all arguments

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#6921]
NWJS Version : v0.35.3
Operating System : Windows 10

### Expected behavior

When you open a file using a NW.js application, "App.fullArgv" Should catch the first argument(the file path) received, and the following ones should be catch inside 'open' event, of gui.App.

### Actual behavior

NW.js takes just one of the arguments and ignores the rest. After proper loaded, it starts firing correctly the gui.App.on('open',function(arguments))
(Also, quick comment: It's pretty hard to get the argument I want from this "open" event, could there be a easier way? Each OS has a completly different full arg)

### How to reproduce

```
    	var gui = require('nw.gui');
            var command = gui.App.fullArgv;
            alert(command)

            gui.App.on('open', function(cmdline) {

alert(cmdline)

            })
```
Try opening 2 or more files at the same time using NW.js(Select 2 or more and press enter, or do like "nwjs file1 && nwjs file2" inside the terminal) running this code. It will alert once the first time you try, then won't alert the second argument. If with an already opened instace you try again, it fires twitce the alert.

**Comment by elpeleq42** [comment]
@rogerwang still happens on NW.js v0.37.4

**Comment by ffanny** [comment]
I tried with nwjs-sdk-win-v0.37.4 and `./nw nwapplication file1 file2`, it alerts `file1,file2`.

**Comment by elpeleq42** [comment]
@ffanny 

I've made a few more tests(windows 10, nwjs-sdk-win-v0.38.2) and it seems the behavior changes depending on how one tries to open the files using nw.js(using above code):

-If I configure windows to open a certain type of file using nw.js as default, in the first opening it will only fire once, showing only the path to the first file. In the second, it fires multiple times, once for each file.
-If I drag and drop the files to nwjs.exe file, it will fire the alert once, with 2 arguments at the end. Same thing happens if I drag and drop files with it already opened.

I would like to suggest a more standardized behavior for those events. Also, if possible, it would be quite useful if the "open" event could have a filter, allowing one to get only the file path or the full argument. As it is now, its quite hard to get the right path on all platforms.
