### ISSUE TITLE
How to debug in the mode of production?

### ISSUE THREAD

**Issue by TongDaDa** [nwjs/nw.js#6925]
Now, I have a problem in the special computer that is windows system, Usually I can debug and find errors on remote-debug-url, and now I connot do that, It is difficult to find problems.

**Comment by TongDaDa** [comment]
I know, you maybe say ‘Go to the Google Community to ask for help...’, But there are no one can answer me.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by TongDaDa** [comment]
@rogerwang

**Comment by TongDaDa** [comment]
That is How to listen the remote-debugging-port on production mode.
