### ISSUE TITLE
require("express") crashes in CentOS 7.6

### ISSUE THREAD

**Issue by srguiwiz** [nwjs/nw.js#6928]
NWJS Version : 0.35.4
Operating System : CentOS 7.6

### Expected behavior

Like in other OS, when running express in an NW.js app it should work.

### Actual behavior

Doing simply require("express") it crashes.  Not even using it.  Via require("crypto"), apparently segfault with null pointer in __strcmp_sse42.

### How to reproduce

Grab a CentOS 7.6 with GUI.  Today we tested in its default, GNOME.  Only in case you're not familiar with CentOS, one way to get Node 11.6.0 to match NW.js version 0.35.4 is:
```
# get Node if not installed yet
node --version
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash - && sudo yum install -y nodejs
node --version
# then get specific version Node if needed
sudo npm install -g npm@latest
sudo npm install -g n
sudo n 11.6.0
```

Note:  In a plain CentOS 7.6 install, that is a GNOME desktop, for NW.js you may need to run an additional
```
yum install libXScrnSaver
```

Also, note in `package.json` in `scripts` the need in `centos` to run `--no-sandbox`.  That is only a secondary concern this moment, to be analysed next after this issue.

The project `package.json`:
```
{
  "name": "simple-app",
  "version": "1.0.0",
  "scripts": {
    "normally": "node_modules/.bin/nw ./desk-app --enable-logging --v=1",
    "centos": "node_modules/.bin/nw ./desk-app --no-sandbox --enable-logging --v=1",
    "just-node": "node desk-app/node-main.js"
  },
  "dependencies": {
    "express": "4.16.4",
    "nw": "0.35.4",
    "yargs": "12.0.5"
  }
}
```
The app's `desk-app/package.json`:
```
{
    "name": "simple-desk-app",
    "version": "1.0.0",
    "main": "index.html",
    "node-main": "node-main.js"
}
```
The `desk-app/index.html`:
```
<!DOCTYPE html>
<html><head><title>Simple App</title></head>
<body><h1>Simple App</h1><p>Yay, you got this far!</p></body>
</html>
```
The "safe" version `desk-app/node-main.js`:
```
console.log("checkpoint 1 before any require " + __filename);
const fs = require("fs");
console.log("checkpoint 3 after require fs " + __filename);
//const nodeCrypto = require("crypto");
//console.log("checkpoint 5 after require crypto " + __filename);
const os = require("os");
console.log("checkpoint 7 after requie os " + __filename);
const yargs = require("yargs");
console.log("checkpoint 9 after require yargs " + __filename);
try {
//  const express = require("express");
} catch (e) {
  console.log("require express exception ", e);
}
console.log("checkpoint 15 after require express " + __filename);
const pathMod = require("path");
console.log("checkpoint 17 after require path " + __filename);
```
After you do the
```
npm install
```
in CentOS 7.6 you should be able to run it with
```
npm run centos
```
and in other operating systems
```
npm run normally
```
You should see the app's window, no problem, as proof your environment works, because the problem causes have been commented out in above `desk-app/node-main.js`.

**To experience the crash** now uncomment e.g. the line with
```
  const express = require("express");
```
or the line with
```
const nodeCrypto = require("crypto");
```
and run it again.

There should be crash dumps.

Between runs, one way to get rid of any extra nw after a crash, for a clean new run or crash dump, is
```
kill -9 `pgrep nw`
```
Earlier effort ([in mailing list](https://groups.google.com/forum/#!topic/nwjs-general/NQyE5tpmwuc)) on this were in Docker, no crash dump produced.  Now seeing this problem in a machine running CentOS as main OS gets crash dump, but even after trimming to MDMP no usable output from minidump_stackwalk.

To make sure the modules are actually installed, you can try:
```
npm run just-node
```

I hope these instructions are good, but if asked I will try to provide more info.

**Comment by rogerwang** [comment]
[node-so.zip](https://github.com/nwjs/nw.js/files/2739689/node-so.zip)
Thanks. I can reproduce it.
While I'm working on the fix, you can workaround it with the attached file as replacement.

**Comment by srguiwiz** [comment]
I can confirm on first tests this file fixes more than hoped for:
It runs without crashing.
It no longer requires `--no-sandbox`.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
