### ISSUE TITLE
Make a place (in memory) to share data across pages

### ISSUE THREAD

**Issue by Mann90** [nwjs/nw.js#6933]
This is a feature request.

NWJS Version :0.35.4
Operating System : N/A

Could you make a place for saving some data in memory so that it can be shared by all pages??

1. Things like `localStorage` may work but it is persistent and it can be easily inspected in the Devtool.
2. The data in some global objects such as `nw.App` is not lost after loading a new page. (For example, if we do `nw.App.userData = {}; nw.App.userData.foo=123;`, `nw.App.userData` will be `undefined` after loading another html page.)

**Comment by bluthen** [comment]
I use nw.global for this.
