### ISSUE TITLE
Wrong default colors in MacOS Mojave dark mode 

### ISSUE THREAD

**Issue by Mann90** [nwjs/nw.js#6935]
NWJS Version : 0.35.4
Operating System : MacOS 10.14.2 (in Dark Mode)

### Expected behavior
The default colors of scrollbars and button texts should be visible. 

### Actual behavior

But now those colors are pure white and invisible.

### How to reproduce
- Make an index.html
`<html><body><button type="submit">submit</button></body></html>`
- Load it in NW.js
- The button text is shown as pure white.

**Comment by Mann90** [comment]
This bug is still in v0.35.5.
 It is very serious since it can break the UI completely. 

If the HTML is `<html><body><button type="submit">submit</button></body></html>`, the button text is completely invisible as shown in the following screenshot.

![image](https://user-images.githubusercontent.com/8889106/51321217-34e9ca00-1a30-11e9-927c-19889de8b9bd.png)

**Comment by rogerwang** [comment]
It works for me with the latest version. closing for now.
