### ISSUE TITLE
devtools is empty

### ISSUE THREAD

**Issue by Hareis** [nwjs/nw.js#6941]
Nwjs I installed nwjs SDK version is 0.35.4
Construct an initialized demo with vue-cli
Then the win. showDevTools () is triggered in the page js.

```javascript
var win = nw.Window.get();
        win.showDevTools();     
```

As you can see below, it's blank.
![image](https://user-images.githubusercontent.com/11290701/51106869-0ac5bb80-1828-11e9-8d5f-b0e06c41af17.png)

help!!

**Comment by TheJaredWilcurt** [comment]
```html
<script>
var flavor = process.versions['nw-flavor'];
if (flavor !== 'sdk') {
  document.write('You are not using the SDK version of NW.js. You are using ' + flavor);
} else {
  document.write('You are using the SDK version of NW.js');
}
</script>
```
