### ISSUE TITLE
Error calling attach: The guest has already been attached. 

### ISSUE THREAD

**Issue by mutlucan96** [nwjs/nw.js#6942]
NW.js Version: 0.35.5
OS: Ubuntu 18.10

I'm using [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars) plugin on my NW.js app. I have a `div` contains `webview` elements. When I apply OverlayScrollbars to that `div`, although everything works fine with the app and plugin, I get some error messages on my console:

```
Error calling attach: The guest has already been attached. 
GuestViewImpl.checkState @ extensions::guestView:134
```

What does this error message mean?

By the way, I have also opened an issue on OverlayScrollbars GitHub page. But They told me it's nothing to do with the plugin. But they have provided information about the plugin that might be helpful to you:

> The plugin is using (if available):
> 
> MutationObserver
> ResizeObserver
> Passive Event Listener
> request / cancel AnimationFrame
> set / clear Timeout
> How it works:
> On initialization the plugin is wrapping the content of the element to which it was initialized. A visual representation (before & after) can be found here. So there are elements which are generated by the plugin on the fly. This wrapping is happening only once, the generated elements are managed by the plugin and their attributes such as style and class gets changed accordingly to the user action / DOM changes. The content elements (in your case the webview elements) aren't touched or measured or anything like that.

**Comment by matt-cook** [comment]
Ran into the same problem in a Chrome App  also being used via NW.js. However, I'm seeing the error when installing the issue Chrome App via `chrome://extensions` "Load unpacked". Are you also using a Chrome App?
