### ISSUE TITLE
Poor performance compared to node (using psd.js)

### ISSUE THREAD

**Issue by WillBrindle** [nwjs/nw.js#6943]
NWJS Version : 0.35.5
Operating System : macOS High Sierra 10.13.6

### Expected behavior

Performance should be near native speeds. The psd files I tested with complete within a few seconds. Node version is 11.6.0 so should be matching that which nw.js is using. 

### Actual behavior

nw.js takes a very long time to complete. IThe particular example file in the reproduce steps took about 30+ seconds, but other files I've seen easily take minutes. What takes a long time is line 26 of test.js `props.img.toPng();` when img gets evaluated (lazily). It seems the slow part is:
https://github.com/meltingice/psd.js/blob/master/dist/psd.js#L1013-L1048
Or the more readable original coffeescript: 
https://github.com/meltingice/psd.js/blob/38a26b55e19e95e8b1e5dc828670ca5d1fe698a1/lib/psd/image_formats/rle.coffee#L16-L37

Which appears to not be doing anything particularly special; just a few loops, so I'm not too sure why it is so significantly slower in nw.js as opposed to node. Any pointers in the right direction would be grand.

I will point out that the psd library is pure javascript; no native code or dependencies. 

### How to reproduce

1. using the files below and 'rich-text.psd' from https://customerscanvas.com/docs/cc/psd-samples.htm
2. make a package.json with main as test.html
3. run `npm install psd`
4. run `node test.js` - observe that it comes back very quickly with 'All done'.
5. run nwjs . - observe that the page appears to just freeze up and the code takes a long time to complete

test.html:
```
<html>
    <body>
        <script>
            require('./test.js');
        </script>
    </body>
</html>
```

test.js
```
const PSD = require('psd');

function getImageForLayer(layer) {
  const info = layer.export();
  if ((info.width && info.height) === 0) {
    return null;
  }

  if (layer && !layer.hasChildren()) {
    if (info.type !== 'layer') {
      return null;
    }

    return layer.layer.image;
  }
  return null;
}


function processArtBoard(node) {
  const layers = node.descendants();

  layers.map(layer => ({ layer, img: getImageForLayer(layer) }))
    .filter(props => props.img !== null)
    .forEach((props) => {
      props.img.toPng();
    })
}

const file = 'rich-text.psd';
const psd = PSD.fromFile(file);
psd.parse();

const root = psd.tree().root();
const children = root.children();

const artboards = [];

children.filter(child => child.layer.artboard);
if (artboards.length <= 0) {
    artboards.push(root);
}

artboards.map((n, i) => processArtBoard(n));
console.log('All done');
```

**Comment by rogerwang** [comment]
This could be the v8 version differences. Node v11 is with v8 7.0 while NW v0.35 is with v8 7.1. If the sample code is running with NW v0.34 (with which v8 is 7.0), it executes fast.

**Comment by rogerwang** [comment]
I suggest trying the same code in latest Chrome stable 71, and see whether it's slow.
