### ISSUE TITLE
Prevent F12 (win) to show dev tools in SDK.

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#6944]
Hi, is possible prevent open devtools in SDK? Like F12 on Windows. (*all NWjs)

OS: Windows 10 (1809) x64

```javascript
win.window.addEventListener("keydown", (evt) => {
    if (evt.key == "F12") evt.stopPropagation();
});
```

**Comment by panther7** [comment]
Btw, `isDevToolsOpen` isn't function (http://docs.nwjs.io/en/latest/References/Window/#winisdevtoolsopen)
```javascript
var win = nw.Window.get();
typeof win.isDevToolsOpen // "undefined"
typeof win.showDevTools // "function"
```

**Comment by bluthen** [comment]
There is no dev tools is the normal non-sdk version.

**Comment by panther7** [comment]
I need devTools in SDK, but under control, if some condition, then disabled devTools.

**Comment by bluthen** [comment]
I agree that seems like a bug in the documentation or nwjs itself. For your case maybe you can set a interval with win.closeDevTools() regardless if it is opened or not. Then clear the interval when you want to allow it.

**Comment by rogerwang** [comment]
Is this switch what you need? http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-disable-devtools

**Comment by panther7** [comment]
@rogerwang Nice, is possible have this switch in runtime, like `win.disableDevTools = true / false;` ?

And, please can you fix in doc`win.isDevToolsOpen`? Actualy is undefined.
