### ISSUE TITLE
Prevent change/redirect url on nw.Window

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#6945]
NWjs: 0.35.3, 0.35.5
OS: Windows 10 (1809) x64

Tried this code:

```javascript
var win = nw.Window.get();

win.window.addEventListener("beforeunload", (evt) => {
    evt.preventDefault(); // chrome doesn't support: https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload
    evt.returnValue = false;
    return false;
});

win.window.addEventListener("unload", (evt) => {
    evt.preventDefault();
    evt.returnValue = false;
    return false;
});
```

Any idea? Or it need implement in NWjs?

**Comment by ffanny** [comment]
NWjs: 0.35.3, 0.35.5   OS: Windows 10  x64
The following code works well:
`<body>
<h1>redirect url</h1>
<a href="https://github.com/nwjs/nw.js/issues/6945">issue#6945</a>
<script>
var win = nw.Window.get();
win.showDevTools();
win.window.addEventListener("beforeunload", (evt) => {
    evt.returnValue = false;
    console.log('beforeunload');
});
</script>
</body>`

**Comment by panther7** [comment]
I don't want standard dialog, i want prevent this programely.

**Comment by panther7** [comment]
@rogerwang ?

**Comment by panther7** [comment]
Is posible, add event on webview? Like webview.addEventListener("loadstart", ...)?

I would try check, when page preventing close.
