### ISSUE TITLE
async clipboard api (navigator.clipboard) does not have permissions in nw frame

### ISSUE THREAD

**Issue by bluthen** [nwjs/nw.js#6948]
NWJS Version : 0.35.5
Operating System : Linux/All

### Expected behavior
The async clipboard api `navigator.clipboard.readText()` should work without having to do anything extra to get permission in NW frames.

**Optional:** As a bonus it would be great if you can use navigator.clipboard.readText without it being connected to a UI event.

### Actual behavior

Nothing happens, promise never resolves. It is the same behavior if you used normal browser and just never clicked the permission prompt to block or allow access to the clipboard.

### How to reproduce

The following should output the clipboard buffer to console after clicking on the button:
```
var el = document.createElement('input');
el.type='button';
el.value='click me';
el.onclick = function() {
    navigator.clipboard.readText().then((text) => { console.log(text); }, (err) => { console.error('Failed:', err); });
};
document.getElementsByTagName('body')[0].appendChild(el);
```
Also this example async clipboard api page should work: 
https://googlechrome.github.io/samples/async-clipboard/

As a bonus it would be great if you can use navigator.clipboard.readText without it being connected to a UI event (press button). In that case just running:
```
navigator.clipboard.readText().then((text) => { console.log(text); }, (err) => { console.error('Failed:', err); });
```
Should output the clipboard to console. Although it would be very nice, it isn't part of the API spec.

**Comment by rogerwang** [comment]
> ```
> navigator.clipboard.readText().then((text) => { console.log(text); }, (err) => { console.error('Failed:', err); });
> ```

I just tried this with the default app and opening devtools. It works for me.

**Comment by bluthen** [comment]
It seems like it doesn't work when you are at a https/http-localhost url. Perhaps it only works when you are in a chrome-extension page? Sorry I didn't catch that condition.

**Comment by rogerwang** [comment]
It's expected with http URL since that's Normal frame -- only Node frame gets the extra capabilities. See more at http://docs.nwjs.io/en/latest/For%20Users/Advanced/Security%20in%20NW.js/

**Comment by bluthen** [comment]
Ok. Thanks. But I even have node-remote for all URLs. These are pages I can import node modules, but can't use the async clipboard api.

`*://*/*`

**Comment by whatsdis** [comment]
hi im running in to this issue where a web app that relies on accessing clipboard will not work in nw.js

any ETA on when this might be fixed? unfortunately this is a show stopper for me and I can't continue with Nw.js until this feature is ready.

**Comment by bluthen** [comment]
The api is pretty new to be so dependent on it. You can not use the nw clipboard api or document.execCommand('paste') ?
http://docs.nwjs.io/en/latest/References/Clipboard/
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by bluthen** [comment]
Seems like this is working now for me.
