### ISSUE TITLE
Print PDF layout problem

### ISSUE THREAD

**Issue by k-oldman** [nwjs/nw.js#6950]
Print PDF is not centered, "marginsCustom" methods are invalid.
nw.Window.open(
"http://xxxxxx/xxxxx.pdf",{show: false},
function(pdfWin) {
pdfWin.on('loaded', function() {
this.print({"printer":"xxxxxx","headerFooterEnabled":false,"marginsType":3,"marginsCustom":{"marginBottom":54,"marginLeft":10,"marginRight":28,"marginTop":32}});
});
}
);

**Comment by ffanny** [comment]
nw.Window.print() supports chrome's print function options. 
For PDF files, chrome does not support adjusting margins when printing. You can confirm it in chrome.
And for other forms such as txt, html, etc., print supports adjusting margins.

**Comment by ffanny** [comment]
I don't have a printer to test, so I can only guess.
If the name of the printer used is determined to be what [nw.Window.get().getPrinters(callback)](http://docs.nwjs.io/en/latest/References/Window/#wingetprinterscallback) returns, according to my logic test, there should be no confusion.
Maybe you can also test if the two printers work correctly with Chrome printing.
