### ISSUE TITLE
Window `show_in_taskbar`  has no effect in macOS

### ISSUE THREAD

**Issue by mildmojo** [nwjs/nw.js#6956]
NWJS Version : **0.35.5**
Operating System : **macOS Sierra 10.12.6**

### Expected behavior

Setting `show_in_taskbar` to `false` in `package.json` or when calling `nw.Window.open()` should hide the NWJS icon in the dock.

### Actual behavior

The NWJS icon always appears in the dock.

#### With nw.Window.open()

```javascript
// package.json
{
  "name": "tray-test",
  "main": "index.js"
}
```

```javascript
// index.js
nw.Window.open('', {show_in_taskbar: false});
```

#### With package.json

```javascript
// package.json
{
  "name": "tray-test",
  "main": "index.js",
  "window": {
    "show_in_taskbar": false
  }
}
```

```javascript
// index.js
nw.Window.open('', {});
```

**Comment by ffanny** [comment]
With nwjs-v0.35.5-linux, Window `show_in_taskbar` & `win.setShowInTaskbar(Boolean)` has no effect.

With nwjs-v0.35.5-win, `nw.Window.open('', {show_in_taskbar: false});` & `win.setShowInTaskbar(Boolean)` can work as expected.

**Comment by raguay** [comment]
Lastest version still has this error. I can't get rid of the taskbar/dock icon.

**Comment by rogerwang** [comment]
Does `--disable-features=nw2` make any difference there?

**Comment by raguay** [comment]
No.

**Comment by raguay** [comment]
No, I've actually had this off and on. It sometimes used to work and
sometimes didn't

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by raguay** [comment]
Downloaded and it is working great. Thanks.
