### ISSUE TITLE
Using location.reload() breaks the main window on 0.36.0

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#6957]
NWJS Version : v0.36.0 Normal
Operating System : Windows 10

### Expected behavior

location.reload() should reload the current page

### Actual behavior

The window becomes blank

### How to reproduce

Use location.reload() in the main window and it becomes blank.

Also, trying to open another instance of it using window.open("index.html", "", "") opens a white blank page.

**Comment by elpeleq42** [comment]
For me it throws an error with angularjs, that was not showing before

https://i71.servimg.com/u/f71/15/27/47/75/112.png

**Comment by ffanny** [comment]
If there is still a problem with location.reload(), you can give your full reproduce code to help solve the problem. Or other more detailed information.

**Comment by elpeleq42** [comment]
Well you can download my application's code here, put in the v0.36.0 nwjs folder and test(I couldn't make a small sample)

https://www.dropbox.com/s/36y9bu73o2l642c/demo.zip?dl=0
When you open, write "reset" and press enter or click JITjs -> reset, the window goes blank, the same doesn't happen with older versions of NWjs.
Also, the location.reload code is within the files "example/toolbar.js" and "example/example.command.implementations.js". The first is simply a nw MenuItem menu that calls location.reload() and second is a function that does the same.
(I'm sorry for sending the whole code, but I don't know what could be the problem here, both things I said above do nothing but call location.reload(), and the initial load goes normal)

I honestly don't know why it's breaking...

**Comment by elpeleq42** [comment]
Same thing happens on 0.36.1 (Windows).Testing on 0.35.5 works fine.


@rogerwang

**Comment by elpeleq42** [comment]
Just noticed that, when the window goes blank, If I run location.reload() again a few more times, it may show the window normally

Seems to be some problem loading stuff after a location.reload()

**Comment by elpeleq42** [comment]
@ffanny Tested in the lastest version today (V0.36.4) and it is far less likely to break than before(still does, but It's about 10% of the time)

Was there any changes in something related to the loading/reloading ?

**Comment by elpeleq42** [comment]
Fixed the problem. Seems that, with the improvements in performance of Async and Awayt(in V8 7.2) one script(beind loaded using async tag, in the HTML file) would break the loading.
