### ISSUE TITLE
Nwjs application stick process on windows7

### ISSUE THREAD

**Issue by TongDaDa** [nwjs/nw.js#6958]
My users has run the nwJs 0.33.4 normal of the official version, but just stuck in the process and not open the window, I doubt nw is not compatible with lower-windows7, 

I had attempted the 0.8* version of nwjs(official normal version) that can be running on this computer.

The system information as follows:

System: windows7(installed from the 2009 year).

Ram 8GB

CPU 2.3 Hz

I want to know about the compatible of nwjs for a computer system.

If some lower system version doesn't support the higher nwjs version, I was thinking to develop a new application using 0.8* version of nwjs to the special users who have low system version.

**Comment by TongDaDa** [comment]
But this computer using the win-32 version is available, this computer system is 64b, I do not understand this situation.

**Comment by TheRenTOP** [comment]
### Expected behavior

Use the clip.get ([type, [raw]]) API to get the PNG content of the clipboard

### Actual behavior

Error: print on console: Invalid value for argument 1. Property '.0': Expected 'object' but got 'string'.
My code：
                let clipboard = nw.Clipboard.get();		
		let text = clipboard.get(['png'])
		console.log(text)
	
### How to reproduce
