### ISSUE TITLE
input type=file default button not rendering right on macOS Mojave dark Mode 

### ISSUE THREAD

**Issue by giridev** [nwjs/nw.js#6959]
<img width="515" alt="screenshot 2019-02-01 at 11 21 23 am" src="https://user-images.githubusercontent.com/1387266/52105514-0285c280-2615-11e9-8f75-b42b0972d9d1.png">
<img width="525" alt="screenshot 2019-02-01 at 11 22 23 am" src="https://user-images.githubusercontent.com/1387266/52105516-031e5900-2615-11e9-8e9e-0c51c470986a.png">
<img width="634" alt="screenshot 2019-02-01 at 11 29 57 am" src="https://user-images.githubusercontent.com/1387266/52105517-031e5900-2615-11e9-8c04-9f34beca859e.png">

**Comment by ffanny** [comment]
Is input( type=file) normal if you switch to the bright mode of mac Mojave?
And you can provide a more detailed description of the problem, about the image content you provide.
