### ISSUE TITLE
NWJS Downloads are not working

### ISSUE THREAD

**Issue by asteriosgr** [nwjs/nw.js#6962]
At the moment of writing this, all nwjs downloads are inaccessible. 

Since yesterday whenever I initiate a download of 0.36.0 or 0.35.X for linux or windows, the download is failing. I am guessing the same is happening to all of the downloads no matter the file. Any idea as to why this is happening? (it worked only once yesterday for a brief time and since then all downloads fail)

**Comment by monema75** [comment]
Same here. With a package.json with just nw@0.35.x as dependecies.
"end of central directory record signature not found"

**Comment by kissara** [comment]
same here, In the meantime we use the mirror https://npm.taobao.org/mirrors/nwjs/

**Comment by desperate-man** [comment]
Doesn't work for 0.32.4 as well.

**Comment by rogerwang** [comment]
This should be fixed. Please try again.

**Comment by monema75** [comment]
Yep. Wroking correctly now 👍
