### ISSUE TITLE
MacOS - Error trap on app start with 0.37.0a1

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#6964]
iMac 10.13.6  High Sierra  using NW.js 0.37.0a1-sdk

Get error box on app start (sometimes takes a few seconds to occur) - the report for Apple is a trap number 14 due to app_mode_loader however the app will survive the error process and continue to operate (usually the apps terminate) - works OK with 0.36.1 and the new nw2 switch doesn't appear to make a difference. It will generally occur every start and even when profile has been deleted.

EDIT: just tried the latest download and noticed the error will occur just opening NW.js - no app required ....

<img width="456" alt="start-error" src="https://user-images.githubusercontent.com/11089335/52361505-538f1f80-2a36-11e9-9e73-3ea805d32726.png">

![error-report](https://user-images.githubusercontent.com/11089335/52361515-5853d380-2a36-11e9-85ae-5bb6c9f631c7.jpg)

[starterrortest.zip](https://github.com/nwjs/nw.js/files/2837566/starterrortest.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by Blatman** [comment]
Still occurs in 0.37.0b1-sdk   (a02a08ca6  02-13-2019)

**Comment by rogerwang** [comment]
Just pushed another fix and launched building. Thanks.
