### ISSUE TITLE
Google Drive doesn't show contents in NWjs

### ISSUE THREAD

**Issue by bambooCZ** [nwjs/nw.js#6966]
Example running in NWjs doesn't show contents of Google Drive. The same example running in Chromium works well. It is broken even without `webview`.

[google-drive-trouble.zip](https://github.com/nwjs/nw.js/files/2845556/google-drive-trouble.zip)

## NWjs:
`./nwjs-sdk-v0.36.1-osx-x64/nwjs.app/Contents/MacOS/nwjs google-drive-trouble`
<img width="1007" alt="snimek obrazovky 2019-02-08 v 15 46 54" src="https://user-images.githubusercontent.com/8124126/52485358-fa032e00-2bb8-11e9-89a9-022a0758e238.png">

## Chromium:
`/Applications/Chromium.app/Contents/MacOS/Chromium --load-and-launch-app=google-drive-trouble`
<img width="1009" alt="snimek obrazovky 2019-02-08 v 15 51 17" src="https://user-images.githubusercontent.com/8124126/52485550-6a11b400-2bb9-11e9-95f5-8aeeb1933839.png">

**Comment by rogerwang** [comment]
Does --enable-gcm work?

**Comment by bambooCZ** [comment]
Nope

**Comment by rogerwang** [comment]
For some reason the service worker threads for the site is not running...
Will investigate more.

**Comment by panther7** [comment]
Same problem with this url: https://drive.google.com/file/d/1hBrKcbrjlGPEH5rt7ZU0zZL2Kies3XkU/view

**Comment by rogerwang** [comment]
It's hard to debug this from the side of webpage because it's code is minified. Any insight on this would be helpful...

**Comment by rogerwang** [comment]
I just found that if a user agent string from different vendor is used (e.g. --user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0'), it works well ...

**Comment by panther7** [comment]
You are right, but I can't use `webview.setUserAgentOverride`, could you fix it #6717?

**Comment by rogerwang** [comment]
I just fixed it with the same way as upstream. It will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by akirapix** [comment]
Same problem, i tried with nwjs 0.36.4 sdk and it works well, but it does not work with normal version...
