### ISSUE TITLE
<input type="file" /> crashes when click it second time.

### ISSUE THREAD

**Issue by thehovercam** [nwjs/nw.js#6968]
Windows 10,
nwjs version: 0.36.0.

I have a simple page to have a Open file dialog. It's working good when you first click "Choose File", but if you click it second time after you selected a file, whole application crashes.

To reproduce:
1. serve the following simple html page
2. Click "choose file",  select one file and click 'open' 
3. Click "choose file",  crash!
![image](https://user-images.githubusercontent.com/4604316/52589292-58b3ec00-2df3-11e9-8ebf-04cac1fdfce2.png)

```
<!doctype html>
<html lang="en">
<head>
</head>
<body>
    <input type="file" />
</body>
</html>
```

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-win&linux-v0.36.0.
And in the ubuntu terminal, error info is as follow:
ERROR:render_process_host_impl.cc(4723)] Terminating render process for bad Mojo message: Received bad user message: FileChooser: The default file name should not be an absolute path

ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
