### ISSUE TITLE
crash http_transport_win.cc(175)] WinHttpCrackUrl

### ISSUE THREAD

**Issue by KasperHovlandRasmussen** [nwjs/nw.js#6970]
If I pack my application and run the exe file. I get this error: [0214/192846.598:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl

Please help!

**Comment by KasperHovlandRasmussen** [comment]
- cause of the new update. If I use version 0.35.5, it's working.

**Comment by ffanny** [comment]
I pack a demo application with nwjs-sdk-win&linux-v0.35.5&v0.36.0&v0.36.1 and run the exe file successfully.
You can provide more info about the issue if you still fail after making a new attempt.
