### ISSUE TITLE
window.localStorage from inside extension.

### ISSUE THREAD

**Issue by shadowcodex** [nwjs/nw.js#6972]
When attempting to use `window.localStorage` inside an extension you are met with an error of

```
window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
```

However the extension is not a packaged app, it is an unpacked extension, and in manage extensions page it shows as an unpacked extension.

**Comment by rogerwang** [comment]
Thanks for reporting. Will support this.

**Comment by shadowcodex** [comment]
@rogerwang do you have an eta on that, or how would be best to implement? We are running on a tight schedule and are trying to get a chrome extension wrapped as a desktop app out pretty quick. Any info or direction would be appreciated.

I understand OSS so I don't want to be whiny or begging, just looking for an accurate timeframe. :)

**Comment by rogerwang** [comment]
Will look to support this in 0.36.3 or 0.36.4. Should be within a week.

**Comment by rogerwang** [comment]
I just checked: `window.localStorage` is already supported in NW.js app. Were you running a Chrome App? In Chrome App it's not supported. Are you suggesting that we should enable it in Chrome App?

With the current version you can turn a Chrome App into NW.js app easily by giving it Node.js permission, or provide a `package.json` manifest.

**Comment by shadowcodex** [comment]
I don't think it was a chrome app, we are registered as an extension on the chrome store.

Thats why I'm confused. It's picking up that our extension is a Chrome App when it is an extension.

What causes the the distinction?

**Comment by bdeo** [comment]
@rogerwang This is an extension @shadowcodex is referring to. It is available to all websites while browsing in chrome and is not a "bookmark" for lack of a better term as an app would be.

**Comment by rogerwang** [comment]
Could you provide a reproduce so I can understand your situation better?

**Comment by bdeo** [comment]
@rogerwang would you just need a repro of a basic chrome extension?

**Comment by shadowcodex** [comment]
@rogerwang we can work on getting something out that does reproduce the issue.

I feel though like I'm missing something on nw.js. Do you know of a guide that shows how to turn an extension into an nw app?

I hit this problem, and then when we compile to a binary we have a problem where it doesn't see the extension to mount it into the app. Which is documented here: https://github.com/evshiron/nwjs-builder-phoenix/issues/59 I have that problem on every builder.

**Comment by rogerwang** [comment]
I am not sure what the issue is like on your side. Here a simple app works with window.localStorage. Please provide a sample to reproduce your issue so I can understand your situation and fix it.
