### ISSUE TITLE
How to change the chromium-args dynamically?

### ISSUE THREAD

**Issue by TongDaDa** [nwjs/nw.js#6973]
[The same issue](https://github.com/nwjs/nw.js/issues/1782#issue-31341641)

**Comment by rogerwang** [comment]
Chromium doesn't support this. Which argument would you like to change in the runtime?

**Comment by TongDaDa** [comment]
@rogerwang  Hi 王博士，because we have a lot of users need to add 'disabled-accelerated-video-decode' argument that can play the mp4 video, and even has another condition that use disable-gpu to resolve some user who don't support gpu naturally.

So, only add these argus to special users that can work.

Before this Issue, I tried some way to resolve this problem, such as to modify package.json when start node-main.js and then to open first windows, but it just is effected on the second start.

**Comment by rogerwang** [comment]
modifying package.json and restart should work. Please file an issue if it doesn't.

**Comment by TongDaDa** [comment]
@rogerwang  yes it work for restarting nw, but I modify the package.json when I start node-main(this is first start)，and then I start nw again after I exit this process tree，these argus work. That is unclear for above descripution...


I want it to work on the first start (first open window)that is when I start this node-main file to modify package.
