### ISSUE TITLE
Virtual keyboard disable since 0.34

### ISSUE THREAD

**Issue by KrisKA-360** [nwjs/nw.js#6974]
Virtual keyboard is not automaticaly opened on touch input element since 0.34 release.
Platform : Windows 10 x64 
Best regards. Thank you.

**Comment by ffanny** [comment]
Sorry for not being able to understand your question. I hope you could provide more information based on the issue template.

**Comment by KrisKA-360** [comment]
When i use nw.js 0.33.4 with Windows 10 x64, virtual keyboard of Windows automaticaly appears when i touch text input element (Windows has to be in "tablet mode").
When i use nw.js 0.35.4 with Windows 10 x64, virtual keyboard of Windows does not appear when i touch text input element. I have to click on bottom right icon to open virtual keyboard.

**Comment by ffanny** [comment]
According to my communication with microsoft technicians, the virtual keyboard pops up automatically on tablets that are not connected to the keyboard. 

Does your computer always automatically pop up a virtual keyboard when you need to input in various applications in tablet mode?

**Comment by KrisKA-360** [comment]
All tests are made without connected keyboard.
In same context, Chrome and others applications pop up automatically the virtual keyboard.
