### ISSUE TITLE
Using the default app with Steam on Mac causes nwjs to quit unexpectedly

### ISSUE THREAD

**Issue by rogerscg** [nwjs/nw.js#6975]
NWJS Version : 33.3
Operating System : Mac OS 10.14.2 (Steam build uploading using Windows 10)

### Expected behavior
The gray NW.js background app should load when clicking "Play" on Steam.

### Actual behavior
The game crashes unexpectedly at startup.

### How to reproduce
Pretty difficult to reproduce as it requires an entire Steam pipeline, but if you do the same sort of process with Google Drive by zipping and then downloading onto your Mac, you can't run the basic NW.js program without it crashing unexpectedly.

Crash Report:
https://pastebin.com/raw/vsBgn5YQ

Again, this is simply uploading the clean build and pulling it down onto my Mac.

**Comment by ffanny** [comment]
Is your game originally running correctly on mac os but an error occurred after uploading to Steam via windows 10?

**Comment by rogerscg** [comment]
Yes. Not only that, but if I run the .app file from the command line with `open -a nw.app`, it works.

**Comment by rogerscg** [comment]
Bump.
