### ISSUE TITLE
tray.menu 点右键 菜单会在任务栏显示

### ISSUE THREAD

**Issue by gxdyxh** [nwjs/nw.js#6977]
托盘图标点击右键，会在任务栏中出现。
![22222](https://user-images.githubusercontent.com/33820361/53006987-53991180-3471-11e9-975d-7a86450666e1.png)
![33333](https://user-images.githubusercontent.com/33820361/53006997-56940200-3471-11e9-9201-d42423e13df3.png)

代码：https://github.com/zcbenz/nw-sample-apps/tree/master/Better-Tray-Menu

**Comment by rogerwang** [comment]
Thanks for reporting. But please use English in this project so all users can read.
