### ISSUE TITLE
NWJS default window instead of my app using 0.22.3

### ISSUE THREAD

**Issue by Leprosy** [nwjs/nw.js#6979]
Hi...I've this selenium script, the app is in the same folder:

```python
import time
import sys
import os
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from pathlib import Path

options = Options()
options.add_argument("nwapp=%s" % os.path.dirname(os.path.abspath(__file__)))
exec_path = "path/of/chromedriver"
driver = webdriver.Chrome(executable_path=exec_path, chrome_options=options)

time.sleep(5)
driver.quit()
```

The nwjs window opens, but instead of my app, the default window(gray one with the NWJS text in big font) appears.

Using the last version of nwjs, it works fine. Is there a workaround for the 0.22.3 version? I need to use that version, for legal reasons.

Using ubuntu 17.10
nw.js v0.22.3
Node v7.10.0
Chromium 58.0.3029.110
commit hash: efde18a-0d441f6-2d0e985-0e5235c

**Comment by ffanny** [comment]
Ubuntu 18.04.2
With CHROMEDRIVER=/path/to/nwjs-sdk-v0.22.3-linux-x64/chromedriver, I used the above script and it works fine.

**Comment by Leprosy** [comment]
Perhaps it's the distro

**Comment by Oisin-guitar62** [comment]
Have a glance at this https://lite-serversuspicious2.github.io/lantern8/ explanation

**Comment by ayushmanchhabra** [comment]
Please go through the below repo. It uses thr Service Builder API.
https://github.com/nwutils/nw-testing-python-selenium-servicebuilder-example
