### ISSUE TITLE
Documenting GitHub Issue Labels

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#6980]
There are a lot of labels available and not all are obvious for how they are used. I've created a Wiki page that can be fleshed out:

* https://github.com/nwjs/nw.js/wiki/Issue-Labels

This will be useful when new people are given access to modify/close GitHub issues.

**Comment by rogerwang** [comment]
Thanks. I'll start cleaning up labels which is not used any more.
