### ISSUE TITLE
File browse dialog causes unhandled exception in nw_elf.dll

### ISSUE THREAD

**Issue by tomysshadow** [nwjs/nw.js#6981]
NWJS Version : v0.36.2 SDK
Operating System : Windows x64

### Expected behavior

When clicking on an input of type file with a file already selected, the browse dialog should open a second time to select a different file.

### Actual behavior

When clicking on an input of type file with a file already selected, an unhandled exception occurs in nw_elf.dll, but only if the input does not have the nwsaveas attribute specified.

### How to reproduce

-Include this anywhere in your index.htm file:
`<input type="file" name="inputFilename" id="inputFilename">`

-Click the Choose File button to select any file (I tried with multiple types and names of files in My Documents, including .htm and .pdf) and click Open.
-Now that a file is selected, click Choose File button again. The program crashes before the browse dialog has a chance to open.

Here is the minidump.
[0398d705-16b7-4e45-8c98-60296b323dee.zip](https://github.com/nwjs/nw.js/files/2892020/0398d705-16b7-4e45-8c98-60296b323dee.zip)

**Comment by ffanny** [comment]
os: windows10
With nwjs-sdk-v0.36.2-win, it works well.

**Comment by tomysshadow** [comment]
I should add I am also on Windows 10. For me the issue is consistent, it happens every time. I am using the SDK build currently on the front page of nwjs.io.

**Comment by rogerwang** [comment]
@tomysshadow what's the last version working for you?

**Comment by tomysshadow** [comment]
Hi guys, sorry for the super late reply. As it turns out, I thought it was using v0.36.2 but I was actually using v0.36.1, and it was fixed in 0.36.2. So I will just use that version instead.
