### ISSUE TITLE
Webpack + Web worker, on app reload, entire nwjs process terminates

### ISSUE THREAD

**Issue by gitTerebi** [nwjs/nw.js#6982]
This problem only occurs after 0.34.5+ eg 0.36.2-sdk

Previously 0.34.5 would leave orphan nwjs process if you closed webpack dev server without closing nwjs window first.

I guess in 0.36.2 they patched it so that nwjs would autoclose itself.

Consequently.

* Start a web worker
* Reload app (via hot reload or right click menu app reload)
* About 10 seconds later entire nwjs app would terminate unexpectedly (including web dev server).

My guess is,
Hot reload -> webpack dev server restarts (or crashes) -> nwjs thinks dev server is down -> exits app (instead of hot reloading)

Just wondering if anybody else has had this problem? (Before I upload an example repo)

**Comment by ffanny** [comment]
You can ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
