### ISSUE TITLE
How to use npm package in NW.js without installing Node JS

### ISSUE THREAD

**Issue by sandeepks1** [nwjs/nw.js#6983]
I want to use this npm package(https://www.npmjs.com/package/node-ssh) in my nw.js application,
In my dev system installed node js and installed this package and successfully its working 
,But while shipping this application i dnt't want to make a dependency to node js . Without insatlling the node js can nw.js use this package.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
