### ISSUE TITLE
Entry point for an Angular v7 Material application

### ISSUE THREAD

**Issue by RonCan** [nwjs/nw.js#6984]
NWJS Version :
0.13.2
Operating System :
Ubuntu 18.04
### Expected behavior

When entered the index.html entry point, the angular router should kick in and the angular app should be displayed in the native window

### Actual behavior

An empty page appears. Only one error in console complaining about favicon

### How to reproduce

ng new my-dream-app
inside package.json add an entry "main": "src/index.html" and that's it.

I'm sure I'm going about this all wrong and there is a definite way of getting Angular v2 onwards applications to work in nw and I think it has to do with my entry point "main" in package.json

**Comment by ffanny** [comment]
With nwjs-sdk-linux-v0.13.2&v0.36.2, it will display the native window, although v0.13.2 will cause a lot of error messages at the terminal.

![window 6984](https://user-images.githubusercontent.com/19678102/53284264-b863ad00-378c-11e9-8a22-09824e4883d9.png)

**Comment by RonCan** [comment]
I can't get Angular 7 app to work, all I see is the index.html file and the
router-outlet content i.e. the actual Angular application never shows up.
Can you share an example package.json for an Angular project?

**Comment by ffanny** [comment]
In package.json, write "main":"http://localhost:4200", then it will works well.
Reference #6804

**Comment by TheJaredWilcurt** [comment]
I've written up a guide for setting up the latest NW.js with the latest Angular-CLI.

* https://dev.to/thejaredwilcurt/angular-cli-and-nwjs-for-development-49gl

**Comment by kriefsacha** [comment]
How to you build your Angular Nw.js project for production ??

**Comment by TheJaredWilcurt** [comment]
@kriefsacha 

* https://github.com/nwutils/nw-angular-cli-example

**Comment by jonnathanlopes** [comment]
> @kriefsacha @RonCan @ffanny
> 
> I've created an Angular 8 + NW example repo. Works for running locally for dev and building for dist.
> 
> * https://github.com/nwutils/nw-angular-cli-example

is generating the source code of the angular together with the nwjs compilation
