### ISSUE TITLE
lost the first touchend event

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6985]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.36.2
Operating System : mac 10.14

### Expected behavior

touchstart and touchend match in pairs

### Actual behavior

the first touchend event lost
 
### How to reproduce

[firsttouchend.zip](https://github.com/nwjs/nw.js/files/2899371/firsttouchend.zip)
![image](https://user-images.githubusercontent.com/11750641/53321548-c5f76f00-3913-11e9-90ee-c8f69c163995.png)
open demo
1. inspect the webview(in test is a webview)
2. click enabletouch button
3. click webview
![image](https://user-images.githubusercontent.com/11750641/53321619-ef17ff80-3913-11e9-997d-60aad3d12163.png)

**Comment by ffanny** [comment]
I can reproduce this issue. Will try to find the cause and fix it.

**Comment by ffanny** [comment]
It has been fixed.
Version for mac is available in https://dl.nwjs.io/live-build/nw36/02-27-2019/75a4bf8eb
