### ISSUE TITLE
Can't use CraftyJS engine

### ISSUE THREAD

**Issue by GingkathFox** [nwjs/nw.js#6989]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.13.0rc-3
Operating System : MacOS Mojave 10.14.3

### Expected behavior

The game should load with walls and a player entity.

### Actual behavior

White screen and nothing in the logs.

### How to reproduce
walls.js
```js
module.exports = wall

function wall() {
    Crafty.e('Wall, 2D, Canvas, Color') // Long wall along middle
      .attr({x: 100, y: 260, w: 300, h: 10}) 
      .color('grey');

    Crafty.e('Wall, 2D, Canvas, Color') // short wall above wall1
      .attr({x: 100, y: 140, w: 10, h: 100})
      .color('grey');

    var lWall = Crafty.e('Wall, 2D, Canvas, Color') // Left boundary wall
      .attr({x: 0, y: 0, w: 10, h: 500})
      .color('grey');

   var rWall = Crafty.e('Wall, 2D, Canvas, Color') // Right boundary wall
      .attr({x: 490, y: 0, w: 10, h: 500})
      .color('grey');

    var bWall = Crafty.e('Wall, 2D, Canvas, Color') // Bottom boundary wall
      .attr({x: 0, y: 490, w: 500, h: 10})
      .color('grey');

    var tWall = Crafty.e('Wall, 2D, Canvas, Color') // Top boundary wall
      .attr({x: 0, y: 0, w: 450, h: 10})
      .color('grey');
    // END Walls
  }
```
index.html
```html
<html>
  <head></head>
  <body>
    <div id="game"></div>
    <script type="text/javascript" src="https://rawgithub.com/craftyjs/Crafty/release/dist/crafty-min.js"></script>
    <script>
      var wall = require('Code/Functions/Walls.js')

      Crafty.init(500,500, document.getElementById('game'));
      wall()
      Crafty.e('Floor, 2D, Canvas, Color')
        .attr({x: 0, y: 250, w: 250, h: 10})
        .color('green');
      Crafty.e('2D, Canvas, Color, Twoway, Gravity')
        .attr({x: 0, y: 0, w: 50, h: 50})
        .color('#F00')
        .twoway(200)
        .gravity('Floor');
    </script>
  </body>
</html>
```

- Detail a step by step guide to reproduce the issue
1. place the walls function in a js file and the index.html in the same directory.
2. run `nw .`.
3. NW opens a blank screen, but if you remove the `wall()` call it will work.

**Comment by ffanny** [comment]
Console log: "Uncaught ReferenceError: Crafty is not defined at Object.exports.wall".

You can use src="path/to/Walls.js" in index.html to use your functions, then library crafty.js is avaliable with  src="https://rawgithub.com/craftyjs/Crafty/release/dist/crafty-min.js".

**Comment by GingkathFox** [comment]
I also have the Crafty engine installed, can i just `require()` it or do i have to `src` it too?

**Comment by GingkathFox** [comment]
also, how to i use the debug port? i cant seem to view the console.

**Comment by ffanny** [comment]
DevTools is only available in SDK flavor. It’s recommended to use SDK flavor to develop and test your app. And use other flavors for production. [build flavors](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Build%20Flavors/)

[download in here](https://nwjs.io/downloads/)

You can right click on the window to open the menu and select Inspection to open DevTools. Alternatively, you may open DevTools programmatically using NW.js API [win.showDevTools()](http://docs.nwjs.io/en/latest/References/Window/#winshowdevtoolsiframe-callback) for a window.

Then you can use different methods to practice and use DevTools to help find problems.

**Comment by GingkathFox** [comment]
what if i installed using Node? is thee a `npm i -g nw-dev` or something?

**Comment by ffanny** [comment]
To install a specific build type you may set npm config property nwjs_build_type, environment variable NWJS_BUILD_TYPE or pass command line option --nwjs_build_type:`npm install nw --nwjs_build_type=sdk` 

You can alternatively install sdk build by specifying -sdk suffix in version:
`npm install nw@0.13.3-sdk`

I reference [nw-npm].(https://www.npmjs.com/package/nw)

**Comment by GingkathFox** [comment]
thanks!
