### ISSUE TITLE
Crash when use devtool Inspector

### ISSUE THREAD

**Issue by Mann90** [nwjs/nw.js#6991]
NWJS Version : 0.36.2
Operating System : MacOS 10.14.3

After upgraded to NW 0.36.2, one application crashes very often when Devtool Inspector is open.

Here is the dumped message:
Check failed: position < size() (0 vs. 0)
0   nwjs Framework                      0x000000010995b21f v8_inspector::V8StackTraceId::IsInvalid() const + 10467343
1   nwjs Framework                      0x00000001098b344f v8_inspector::V8StackTraceId::IsInvalid() const + 9779775
2   nwjs Framework                      0x000000010cff5d2a v8_inspector::V8StackTraceId::IsInvalid() const + 67724058
3   nwjs Framework                      0x000000010cc10f6c v8_inspector::V8StackTraceId::IsInvalid() const + 63640924
4   nwjs Framework                      0x000000010cc11151 v8_inspector::V8StackTraceId::IsInvalid() const + 63641409
5   nwjs Framework                      0x000000010cc11ed6 v8_inspector::V8StackTraceId::IsInvalid() const + 63644870
6   nwjs Framework                      0x00000001086e96c4 ChromeMain + 23283780
7   nwjs Framework                      0x00000001099a744a v8_inspector::V8StackTraceId::IsInvalid() const + 10779194
8   nwjs Framework                      0x00000001099ab92b v8_inspector::V8StackTraceId::IsInvalid() const + 10796827
9   nwjs Framework                      0x00000001099ab144 v8_inspector::V8StackTraceId::IsInvalid() const + 10794804
10  nwjs Framework                      0x00000001099a536b v8_inspector::V8StackTraceId::IsInvalid() const + 10770779
11  nwjs Framework                      0x00000001099a5ab1 v8_inspector::V8StackTraceId::IsInvalid() const + 10772641
12  nwjs Framework                      0x00000001099bb588 v8_inspector::V8StackTraceId::IsInvalid() const + 10861432
13  nwjs Framework                      0x00000001098a3bd5 v8_inspector::V8StackTraceId::IsInvalid() const + 9716165
14  nwjs Framework                      0x000000010991080c v8_inspector::V8StackTraceId::IsInvalid() const + 10161660
15  nwjs Framework                      0x00000001098a3bd5 v8_inspector::V8StackTraceId::IsInvalid() const + 9716165
16  nwjs Framework                      0x00000001098c082f v8_inspector::V8StackTraceId::IsInvalid() const + 9834015
17  nwjs Framework                      0x00000001098c0d13 v8_inspector::V8StackTraceId::IsInvalid() const + 9835267
18  nwjs Framework                      0x000000010d9a5c5a v8_inspector::V8StackTraceId::IsInvalid() const + 77881930
19  nwjs Framework                      0x00000001098b509a v8_inspector::V8StackTraceId::IsInvalid() const + 9787018
20  nwjs Framework                      0x00000001098c20ff v8_inspector::V8StackTraceId::IsInvalid() const + 9840367
21  CoreFoundation                      0x00007fff47d01395 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
22  CoreFoundation                      0x00007fff47d0133b __CFRunLoopDoSource0 + 108
23  CoreFoundation                      0x00007fff47ce4dd1 __CFRunLoopDoSources0 + 195
24  CoreFoundation                      0x00007fff47ce437a __CFRunLoopRun + 1219
25  CoreFoundation                      0x00007fff47ce3c64 CFRunLoopRunSpecific + 463
26  Foundation                          0x00007fff4a04a4aa -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 280
27  nwjs Framework                      0x000000010d9a5be8 v8_inspector::V8StackTraceId::IsInvalid() const + 77881816
28  libnode.dylib                       0x000000011470c760 uv__io_poll + 940
29  libnode.dylib                       0x00000001146fd821 uv_run + 314
30  nwjs Framework                      0x00000001091ee4fb v8_inspector::V8StackTraceId::IsInvalid() const + 2681579
31  libnode.dylib                       0x000000011476f89a g_uv_runloop_once + 113
32  nwjs Framework                      0x000000010d9a61f3 v8_inspector::V8StackTraceId::IsInvalid() const + 77883363
33  nwjs Framework                      0x00000001098c1c07 v8_inspector::V8StackTraceId::IsInvalid() const + 9839095
34  nwjs Framework                      0x00000001098e6e45 v8_inspector::V8StackTraceId::IsInvalid() const + 9991221
35  nwjs Framework                      0x000000010db22f48 v8_inspector::V8StackTraceId::IsInvalid() const + 79443256
36  nwjs Framework                      0x00000001094842dd v8_inspector::V8StackTraceId::IsInvalid() const + 5392589
37  nwjs Framework                      0x000000010b837bb8 v8_inspector::V8StackTraceId::IsInvalid() const + 42828200
38  nwjs Framework                      0x00000001094834c4 v8_inspector::V8StackTraceId::IsInvalid() const + 5388980
39  nwjs Framework                      0x00000001070b4f2f ChromeMain + 175
40  nwjs Helper                         0x00000001070894ee main + 494
41  libdyld.dylib                       0x00007fff74f31ed9 start + 1

**Comment by ffanny** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Mann90** [comment]
It can be reproduced with an app with very large scale code. If there are breakpoints in the source code, the crash can happen very often. 

Is there any way to generate some core dump files for you guys to debug?

**Comment by ffanny** [comment]
See [Understanding Crash Dump](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/)

**Comment by Mann90** [comment]
[dumps.zip](https://github.com/nwjs/nw.js/files/2928637/dumps.zip)
Hello, please check the attached dump files. One is the Minidump file; the other is the error messages sent to Apple report.
