### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by jimmont** [nwjs/nw.js#6994]
NW.JS nw.js v0.34.0
Node v11.0.0-pre
Chromium 70.0.3538.67
commit hash: 9e37c96-35f2239-cdf79b5-4052bfe
macos 10.13.6 High Sierra

### Expected behavior
http-response successful

### Actual behavior
error calling API:
```
auth.esm.js:159 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=KEY&cb=1551359977697 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

### How to reproduce

implemented [firebase-web ui](https://firebaseopensource.com/projects/firebase/firebaseui-web/) (working on localhost and remotely hosted with `firebase serve` and from `.firebaseapp.com`)

package.json and main.js for nwjs project:
```
package.json
{
	"name": "firebasedemo",
	"main": "main.js",
	"domain": "fir-ui-demo-84a6c.firebaseapp.com",
	"node-remote": "<all_urls>"
}

...

main.js
	nw.Window.open('https://fir-ui-demo-84a6c.firebaseapp.com/', {
			"id": "firebaseapp"
			,"title": "firebaseapp"
			,"width": 1024
			,"height": 768
			,"min_width": 300
			,"min_height": 300
	}, (win)=>{
		win.showDevTools();
	});

```
in the ui click the button and instead of working it shows the above error (same code)
note headers change, in particular referer is shortened. What additional details could be helpful?

**Comment by ffanny** [comment]
I tried with 
main.js: `nw.Window.open('https://fir-ui-demo-84a6c.firebaseapp.com/', {...`, the url is a demo provided by [firebase](https://github.com/firebase/firebaseui-web) .

And I can use it normally with nwjs-v0.34.0&v0.36.2-sdk-linux.
If I don't understand your question correctly, please let me know.

**Comment by jimmont** [comment]
thanks @ffanny I've tried this approach and will edit my original report with the problem, using this updated source which completely reproduces the problem: when logging in using 'Sing In With Google' there is a network error message in the UI and the CORB error mentioned above for the authentication API calls.

**Comment by ffanny** [comment]
CORB error occured when with nwjs-v0.34.0, but with later version like nwjs-v0.36.3, it will not occur.

So you can use the latest version for more support.

**Comment by jimmont** [comment]
Updating to the recent version fixed the CORB error, thanks @ffany. I'm working through the remainder of the issues now. Note (this might be obvious) that using this approach requires adding `chrome-extension://localhost` exactly to develop against the localhost domain (add to the firebase console sign-in method - Authorized domains, which is weird to add the protocol as well).

**Comment by jimmont** [comment]
Note: when using the firebase web ui (linked above) in mixed context mode where `window.global` exists the web ui will not work because it has logic which appears to run in mixed contexts (both Nodejs and browsers). This prevented my implementation from working. To fix it I had to remove `window.global` **before loading the firebase scripts**:
```
<script>
delete window.global;
</script>
<script src=all the firebase>
```
