### ISSUE TITLE
New windows not opening in correct screen

### ISSUE THREAD

**Issue by sadikyalcin** [nwjs/nw.js#6996]
NWJS Version : 0.35.4 SDK / 0.36.2 SDK
Operating System : Windows

Issue:

Newly created windows does not open on the same monitor as the main window. This only happens on Windows 10. On macos it is fine.

### Expected behavior

Windows created should open the screen where the main window is.

### Actual behavior

New windows always opens on the main screen.

### How to reproduce

1. Have a dual monitor setup with extended displays.
2. Launch the app on the main screen.
3. Drag the window to the second monitor.
4. Newly created windows opens on the main monitor.

If you do the same steps on macos, it opens on the monitor where the main window is. Move the main window to the second monitor, create a new window, you will see the second window is opened on the second monitor.

Package.json:

```
{
  "name": "demo",
  "main": "index.html",
  "window": {
    "id": "mainWindow",
    "toolbar": false,
    "width": 500,
    "height": 500,
    "position": "center",
    "min_width": 500,
    "min_height": 500,
    "resizable": true,
    "frame": true,
  },
  "single-instance": true,
  "webkit": {
    "page-cache": false
  }
}

```

```
nw.Window.open('https://google.co.uk', {
    position: 'center',
    width: screen.availWidth,
    height: screen.availHeight,
    frame: false,
});
```

**Comment by rogerwang** [comment]
Does `--enable-features=nw2` fix this for you?

**Comment by sadikyalcin** [comment]
@rogerwang unfortunately not.

**0.35.4**

OSX: New windows are transparent and won't load
Windows 10: Main app window is white and won't load

**0.36.2**

OSX: Not tested
Windows 10: Windows load fine but same behaviour. New created windows open on main display.
