### ISSUE TITLE
Enable Origin Trials features

### ISSUE THREAD

**Issue by whatsdis** [nwjs/nw.js#6998]
Currently, there are no instructions on how to enable Origin Trials features on NW.js and unclear whether the latest version supports shape detection.

Please enable all origin trials features by option. # #

**Comment by ffanny** [comment]
Origin trials features like shape detection api can be enabled by `"chromium-args":"--enable-experimental-web-platform-features"` in package.json for NW app.

But according to [shape-detection-api DOC](https://github.com/WICG/shape-detection-api#overview), not all platforms support it.

And I have tested with Windows 10 and linux, Face Detection can be used in Windows 10 but not in linux. [Face detection demo](https://github.com/ffanny/nw.js/tree/reproducecode/code/shapeDetection)
