### ISSUE TITLE
await model.fit() of @tensorflow/tfjs (or @tensorflow/tfjs-node) got stuck

### ISSUE THREAD

**Issue by justincui** [nwjs/nw.js#6999]
NWJS Version : nwjs 72.0.3626.119 
Operating System : Ubuntu 18.04
@tensorflow/tfjs: v0.15.3
@tensorflow/tfjs-node: v0.3.1

### Expected behavior
"await model.fit();" should not get stuck as running by nodejs V11.10.1 directly. 

### Actual behavior
the await got stuck.

### How to reproduce
git clone https://github.com/justincui/nwjs_issue.git
cd nwjs_issue
npm install
npm install nw --nwjs_build_type=sdk
node ./index.js     ###prove it's working
./node_modules/.bin/nw .
(when the GUI displays, press F12)

**Comment by ffanny** [comment]
I can reproduce this issue with nwjs-sdk-v0.36.3-linux.

In demo directory,
`node ./index.js` and `path/to/nw ./index.js` both work.
But `path/to/nw .` has problem about model.fit().

**Comment by rogerwang** [comment]
@ffanny please try to find out the difference with the 2 workloads. And use the regular (not minified) version of the source code.

**Comment by ffanny** [comment]
Enable Mixed context by add `--mixed-context` when starting NW.js or add it to chromium-args in Manifest file, then `await model.fit()` will work well. 

In mixed context mode, a new Node context is created at the time of each browser context creation and running in a same context as browser context.
See [JavaScript Contexts in NW.js](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/)
