### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by dijiang** [nwjs/nw.js#7000]
as i follow the guide http://docs.nwjs.io/en/latest/For Developers/Building NW.js/。。on windoes
everthing is ok but when i build node， ninja -C out/Release node， error occurs in the below picture

![image](https://user-images.githubusercontent.com/8736832/53779837-adeba500-3f3c-11e9-87cc-3a672adf79a5.png)

it's just mtd and mdd problem, but i don't know how to chontrol it ?
the document is not friendly to the people who not famaily with gyp, ninja or gn...
i have spend a lot of time building it...

my full step is : 
cd src
gn gen out/nw
ninja -C out/nw nwjs
set GYP_CHROMIUM_NO_ACTION=0
set GYP_DEFINES="target_arch=x64"
python ./build/gyp_chromium -I third_party/node-nw/common.gypi -D building_nw=1 third_party/node-nw/node.gyp
ninja -C out/Debug node
。。。

what i want is just a debug version build on windows

**Comment by dijiang** [comment]
use the following if you’re doing a component build:
./build/gyp_chromium -D component=shared_library -I third_party/node-nw/common.gypi -D building_nw=1 third_party/node-nw/node.gyp

then it works

**Comment by rogerwang** [comment]
The build flags are already covered in the document. closing as invalid.
