### ISSUE TITLE
Renderer process crash: Terminating renderer for bad IPC message, reason 95

### ISSUE THREAD

**Issue by hkaya** [nwjs/nw.js#7001]
Hi,

I'm seeing a strange renderer crash after upgrading from 0.24 to 0.36. I confirmed the same behavior on 0.36.1, 0.36.4 and 0.37.0 sdk builds.

Webview processes that make XHR requests are crashing with the following error message:

```[92800:92808:0305/145204.806109:ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 95```

The issue is almost identical to https://github.com/nwjs/nw.js/issues/6197, except changing `accessible_resources` doesn't help in my case.

Here is a test app I use to reproduce the issue: https://gist.github.com/hkaya/b938a6263899a5b5aac01860841a52dd

You need to update this line: https://gist.github.com/hkaya/b938a6263899a5b5aac01860841a52dd#file-index-html-L9

Thank you!

**Comment by rogerwang** [comment]
The crash is due to `file://` url cannot be used in `origin` header of CORS request: 

https://cs.chromium.org/chromium/src/content/browser/loader/resource_dispatcher_host_impl.cc?sq=package:chromium&g=0&l=2185

It will work If the code is changed to chrome-extension URL in line 16 by simply using 'id' rather than 'base + id'.

**Comment by hkaya** [comment]
Thank you for quickly getting back to me Roger. This makes sense however I still think that file:// origins should be allowed especially since I’m setting the disable-web-security flag. This behavior also prevents loading webpages from another directory.

**Comment by rogerwang** [comment]
@hkaya you are right. I'll fix this under that flag. Thanks.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by hkaya** [comment]
@rogerwang the fix is working. Thank you!
