### ISSUE TITLE
Input file nwsaveas on Windows

### ISSUE THREAD

**Issue by ncannasse** [nwjs/nw.js#7005]
When creating an input file, it seems that nwsaveas is not working on windows:
`<input type="file" nwsaveas="test.txt"/>`
Reproduced on NWJS 0.36.4 SDK

Also, please make sure it works together with nwworkingdir:

`<input type="file" nwworkingdir="C:/Windows" nwsaveas="test.txt"/>`

I did managed to make it work by using an absolute path in `nwsaveas` in a previous version of NWJS but it no longer works.

**Comment by ffanny** [comment]
The path should be `nwworkingdir="C:\Windows"` and `nwsaveas` works well with nwjs-sdk-v0.36.4-win. 

What does 'nwsaveas is not working on windows' mean? You can describe the expected behavior and actual behavior to help understanding.

**Comment by ncannasse** [comment]
Yes, I found the problem. When launching with VSCode I was using an older version of NWJS. It's working correctly with latest.
