### ISSUE TITLE
Wrong controller mapping on linux

### ISSUE THREAD

**Issue by fcharras** [nwjs/nw.js#7006]
I'm not directly a user of nw.js, but I bought the game CrossCode that is built upon nw.js . An issue with controllers has been reported on the community forum (e.g https://steamcommunity.com/app/368340/discussions/1/3276824488730710132/ or https://steamcommunity.com/app/368340/discussions/1/1733213724901237168/ ). From what I get from those discussions, it's been stated several times that the issue comes from nw.js but I can't find a similar issue on the tracker here hence my submission in the hope that the description is enough to get attention and start an a bug hunt.

NWJS Version : tested with latest
Operating System : arch linux

### Expected behavior
Play crosscode with a DS4 or Xbox One gamepad (tested both). Buttons are correctly mapped to in game actions.

### Actual behavior
Buttons mapping is wrong, especially he right axis (which is awkwardly swapped with R2 / L2).

### How to reproduce
Launch the game CrossCode from steam on Linux, playing with a gamepad on bluetooth (tested  with DS4 and Xbox One controllers). Play game. See that the gamepad mapping is wrong.

Note that the version of nw.js can be manually upgraded by overriding the game folder files, and it doesn't fix the issue.

**Comment by NerosTie** [comment]
The same here, even with the last version of nw. In fact they (probably nwjs) use an old scheme prior to a big change into the kernel in 2017 for the Dualshock 4.

**Comment by alexmex90** [comment]
Looks like the implementation of the Gamepad API is borked on Chroimum, if I understand correctly, nw.js uses Chromium, and for some reason the Gamepad API detects incorrectly or maybe just differently the analog axis of controllers in Linux

![image](https://user-images.githubusercontent.com/43529725/61596434-811cef00-abb8-11e9-8b64-94e6e2b3a354.png)

I went to https://html5gamepad.com/ to see how HTML5 sees my controller, without any input, as you can see, it detects a 1 value in axis 2 and 5, in the case of CrossCode it may be interpreting this as right stick input. 

I don't have any windows machine to make a comparison but if the results are different seems like this is a bug in NW.js due  to an upstream bug in Chromium itself. It would be interesting to see the comparison and try to go upstream and have it fixed.

**Comment by jonas-schievink** [comment]
Please reopen, this is still an issue

**Comment by fcharras** [comment]
BTW the issue does not state it clearly, but the issue only happens when connecting the controllers over bluetooth, connecting the controllers on USB enables the correct mapping.

**Comment by jonas-schievink** [comment]
It seems that at least for the DualShock 4 controller this can be worked around by running this command to remap the axes and buttons:

```
jscal -u 8,0,1,3,2,5,4,16,17,13,308,304,305,307,310,311,312,313,314,315,316,317,318 /dev/input/js0
```

**Comment by Draic** [comment]
controllers still not work correctly. Sad that nobody from nwjs cares

**Comment by jonas-schievink** [comment]
@rogerwang can you reopen this? People are still running into this

**Comment by braiam** [comment]
Still seeing this with 045e-0b12-Microsoft Xbox Series S|X Controller
