### ISSUE TITLE
NW crash on WebMIDI sysex send recurred

### ISSUE THREAD

**Issue by g200kg** [nwjs/nw.js#7007]
NWJS Version : v0.37.0-beta1-win-x64
Operating System : windows 10 x64

in #6502 ,
I confirmed that this problem was fixed on nw29, but now this problem has recurred.
I do not know when it happened, and it may be another problem.

crash dump:
[01e2678d-9378-4a0a-9680-19c6f3cb77a8.zip](https://github.com/nwjs/nw.js/files/2948493/01e2678d-9378-4a0a-9680-19c6f3cb77a8.zip)

---

In the program below, the display of "requestMIDIAccess OK" works normally. After that, sendNoteOn has no problem, but when I run sendSysEx, the NW window closes.

(You need to connect some MIDI devices to test it)

### How to reproduce

```
<script>
let midiout=[];
alert("requestMIDIAccess start");
navigator.requestMIDIAccess({sysex:true}).then(
    function(ma){
      alert("requestMIDIAccess OK");
      let it=ma.outputs.values();
      for(let o=it.next(); !o.done; o=it.next()) {
        midiout.push(o.value);
      }
      alert("midiout found : "+midiout[0].name);
    },
    function(e){alert("requestMIDIAccess Error");},
  );
alert("requestMIDIAccess end");

function sendNoteOn(){
  midiout[0].send([0x90,0,0]);  // note On
  alert("send noteOn");
}
function sendSysEx(){
  midiout[0].send([0xf0,0x7e,0x7f,0x09,0x01,0xf7]); // GM on
  alert("send sysex message");
}
</script>

<button onclick="sendNoteOn()">Send NoteOn : send([0x90,0,0])</button>
<button onclick="sendSysEx()">Send Sysex : send([0xf0,0x7e,0x7f,0x09,0x01,0xf7])</button>
```

**Comment by ffanny** [comment]
I can reproduce with nwjs-sdk-v0.36.4&0.36.5&0.37.0-win.
The NW window crashed when run `sendSysEx()`.

**Comment by rogerwang** [comment]
What is the latest working version?

On March 10, 2019 9:58:22 AM GMT+08:00, ffanny <notifications@github.com> wrote:
>I can reproduce with nwjs-sdk-v0.36.4&0.36.5&0.37.0-win.
>The NW window crashed when run `sendSysEx()`.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nwjs/nw.js/issues/7007#issuecomment-471239216

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ffanny** [comment]
> What is the latest working version?
> […](#)
> On March 10, 2019 9:58:22 AM GMT+08:00, ffanny ***@***.***> wrote: I can reproduce with nwjs-sdk-v0.36.4&0.36.5&0.37.0-win. The NW window crashed when run `sendSysEx()`. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#7007 (comment)](https://github.com/nwjs/nw.js/issues/7007#issuecomment-471239216)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

The latest working version is 0.29.4-win.

**Comment by rogerwang** [comment]
Thanks @ffanny . Does it work within NW2 mode in 0.36 or 0.37?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by ffanny** [comment]
@rogerwang It works within NW2 mode in 0.36 & 0.37.

**Comment by rogerwang** [comment]
CC #5875 to record another issue fixed by NW2 mode.

**Comment by g200kg** [comment]
I have confirmed it is fixed at 3/11/19 nightly build.
Thank you
