### ISSUE TITLE
load-extension error in production build

### ISSUE THREAD

**Issue by thehovercam** [nwjs/nw.js#7008]
nwjs: 0.36.2_x64  
Windows 10

I want to load this extension
 https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj?hl=en
into my page's iframe. It works ok with the SDK version, but not showing in production version of nwjs.

`nwjs-sdk-v0.36.2-win-x64\nw.exe .  `  
Works great

`nwjs-v0.36.2-win-x64\nw.exe .  ` 
Not Working

I attached the code below, if you want to test, just put a simple power point file into the 'src' of the iframe.
Any helps will be much appreciated.
[TestExtensions.zip](https://github.com/nwjs/nw.js/files/2948874/TestExtensions.zip)

**Comment by ffanny** [comment]
I can reproduce with nwjs-v0.36.4-win.
[The extension](https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj?hl=en) can work with sdk version but not with normal version.

**Comment by rogerwang** [comment]
@ffanny do you have more information (e.g. screenshot or log) on how it's not working?

**Comment by ffanny** [comment]
@rogerwang When load office files using nw.js normal version with the extension, there is just a loading symbol at beginning but then no file loaded successfully  in window and just stay blank.
![image](https://user-images.githubusercontent.com/19678102/54095789-fcd58680-43e3-11e9-90fe-782848277f14.png)

**Comment by rogerwang** [comment]
@thehovercam the extension requires NaCl feature, which is included only in the SDK build. The SDK build is also meant to be used in production. I suggest you build your application with the SDK flavor.

**Comment by thehovercam** [comment]
@rogerwang Thank you for your quick response, I will use the SDK build and --disable-devtools.  Hope there is no performance difference between SDK and normal build.

**Comment by rogerwang** [comment]
closing as sdk build should be used.

**Comment by rogerwang** [comment]
@thehovercam yes, there is no difference between sdk and normal build in terms of performance.
