### ISSUE TITLE
nw: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wyqydsyq** [nwjs/nw.js#701]
I grabbed a fresh copy of the linux x64 binary on my laptop running Ubuntu 13.04. Trying to run `nw` gives me:

```
nw: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

`locate udev.so` returns:

```
/lib/x86_64-linux-gnu/libudev.so.1
/lib/x86_64-linux-gnu/libudev.so.1.2.2
```

Am I just doing something wrong?

**Comment by Adrian-Yan16** [comment]
> you can use this option cd /lib/x86_64-linux-gnu/ sudo ln -sf libudev.so.1 libudev.so.0

you should run the command "sudo ldconfig" too
