### ISSUE TITLE
Red hat issue: libatspi.0 cannot open shared file

### ISSUE THREAD

**Issue by Talha-B** [nwjs/nw.js#7011]
Hi,

I'm getting the following error when running an nw.js app on Redhat Linux 64 bit version 6.9 using the latest version of nw.js (Linux 64 normal), nwjs-v0.36.4-linux-x64:

Error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory.

Is this looking like a bug? 

Thanks

**Comment by rogerwang** [comment]
Thanks for reporting. The dependency need to be installed. This is not a bug. 
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
