### ISSUE TITLE
why resetting persistent<function> var  in native addon results in crash? ver 0.36.2

### ISSUE THREAD

**Issue by smithAchang** [nwjs/nw.js#7014]
i use persistent<function> var to transfer local<function> being saved for async future usage through its reset member function in native addon ,but it results in crash.
i test the same addon code in nodejs,it works!
i rebuild it by nw-gyp, use the libs(nw.lib,node.lib) provided  by nwjs official website,the link process will fail in link errors. when i use nodejs provided node.lib,the compiler is ok,but if .node file be used in nw,nw will crash at resetting persistent<function> clause that can be proved by self added log infos

**Comment by smithAchang** [comment]
By the way,if i delete all the persistent<function> var usages and still use the nw offical libs,the compiling process is ok,the addon also can used in nw meeting the design aim.
my problem can de simply expressed as such:whether the nw supports async callback to JS from native addon?

**Comment by ffanny** [comment]
You can provide a demo for reproducing.
And you can ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by smithAchang** [comment]
for some reason i cannot provide the codes directly,but you can use the example named "node/test/addons/async-hello-world" in nodejs project.In that example the codes use persistent function var,and i have tested it, it encounters the same link errors too!
i guess the link error is the primary cause.Although i can use the node.lib provided by nodejs to complete compile,the incompatibility will lead to failure in future

**Comment by ffanny** [comment]
I test using "node/test/addons/async-hello-world" with both node.js and nw.js, both work well.

I build the addon via `nw-gyp rebuild --target=v0.36.3 --arch=x64` and the demo:[addon-async-helloworld](https://github.com/ffanny/nw.js/tree/reproducecode/code/addon/addon-async-helloworld)

**Comment by smithAchang** [comment]
my compiler setting is  ia32+vs2015，my target is app runs on windows7 X86.
i can reproduce the problem,can you test it again ?
by the way,i find the node.lib provided by X64 is no more bigger than x86.  is the difference is vs compiler version?

**Comment by ffanny** [comment]
I test on Windows 10 with nwjs-sdk-v0.36.2-win-ia32, build the addon via `nw-gyp rebuild --target=v0.36.2 --arch=ia32` with [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools). 
Setting details are according to [nw-gyp](https://github.com/nwjs/nw-gyp#installation).

**Comment by smithAchang** [comment]
thx :) 
i can finish the compiling process.
i somewhat incorrectly included the header files.i should use the header files provided by nw, the nw modified some v8 function's signature,when i use the header files provided by nodejs,the link will fail in unresolved references.i find it through dumpbining the libs.
But i have another question,which common.gypi file should the nw-gyp configure process  use?
 i currently use the common.gypi under the node-src-dir root.
when i replace it using the common.gypi file under the nw-header-dir root,the nw-gyp config process will fail. on nwjs  official website there is no words for common.gypi file !

**Comment by ffanny** [comment]
When I just update to nw common.gypi for building and the error info prompt that 'filename_rules.gypi is not found'.  After I add the [filename_rules.gypi](https://github.com/nwjs/breakpad/blob/nw12/build/filename_rules.gypi) then build succeed.
Now the demo like [that.](https://github.com/ffanny/nw.js/tree/reproducecode/code/addon)

**Comment by smithAchang** [comment]
0K，I close this case. thx very much:)
