### ISSUE TITLE
0.19.5 MAS Version Rejection from Mac Apple Store

### ISSUE THREAD

**Issue by holemcross** [nwjs/nw.js#7015]
I recently received the following rejection from the Mac Apple Store for my desktop application for using private APIs. 

I did not receive this message before in previous releases which were accepted by Apple. I suspect Apple may have changed the private APIs they are checking and was unclear if this is due to the age of v0.19.5-MAS for being unable to address this potential change.

NWJS Version :
0.19.5-mas-beta

Operating System :
OSX 10.14.3

### Expected behavior

OSX desktop application should pass Mac Apple Store submission process without rejections.

### Actual behavior

Apple rejects the application due to private API use with the following message.

Symbol: _CGDisplayUsesForceToGray
From framework: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
Symbol: __CFIsObjC
From framework: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
In binary: Contents/Versions/55.0.2883.87/nwjs Framework.framework/Versions/A/nwjs Framework

### How to reproduce

Submit an application utilizing NW.js 0.19.5-mas-beta to the Mac Apple Store. Wait for response from Apple.

**Comment by alexandreonterroso** [comment]
I have the exact same issue. Anybody knows how to post the app in the app store?
