### ISSUE TITLE
OSX - Transparency click-through broken in 0.38.0a1-sdk

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7016]
MacOS 10.13.6 High Sierra 

Click-through not working (OK with 0.37.1-sdk) - manifest set as -
--disable-gpu-compositing --force-cpu-draw
nw2 switch makes no difference - fails either way.

Test app from #6850 can be used to test.
Cheers.

**Comment by rogerwang** [comment]
I haven't synced the patch for this to nw38 branch ... will do this soon.

**Comment by rogerwang** [comment]
This is fixed in the last build https://dl.nwjs.io/live-build/nw38/03-17-2019/3a4af5627/v0.38.0-alpha1/

Thanks for reporting.
