### ISSUE TITLE
Fullscreen mode not true fullscreen - windows behind NW.js still being rendered

### ISSUE THREAD

**Issue by rogerscg** [nwjs/nw.js#7019]
NWJS Version : 30.4
Operating System : Windows 10 64 Bit

### Expected behavior

Setting `fullscreen: true` uses true fullscreen, preventing windows behind the app to be rendered.

### Actual behavior

When using `fullscreen: true`, the app behaves as borderless windowed, not true fullscreen.

### How to reproduce

I'm using this package.json:
```"window": {
    "title": "My App",
    "frame": false,
    "width": 800,
    "height": 600,
    "icon": "assets/textures/icon.png",
    "fullscreen": true,
    "toolbar": false
  },
  "chromium-args": "--in-process-gpu --disable-transparency"
```

The game starts in full screen, but it's not a true fullscreen.

**Comment by ffanny** [comment]
Would you please provide a screenshot or other things to show that it is not a true fullscreen?
I test with nwjs-sdk-v0.30.4-win, and it starts in fullscreen like the screenshot below.
And I check the fullscreen state with [win.isFullscreen](http://docs.nwjs.io/en/latest/References/Window/#winisfullscreen) and check again after [win.leaveFullscreen()](http://docs.nwjs.io/en/latest/References/Window/#winleavefullscreen). The result are ture and false.
<img width="960" alt="fullscreen screenshot" src="https://user-images.githubusercontent.com/19678102/54598532-a3202c80-4a73-11e9-8a7d-6ef82fa286c0.png">
<img width="478" alt="fullscreen state" src="https://user-images.githubusercontent.com/19678102/54598564-ba5f1a00-4a73-11e9-84be-273bf8b666fb.png">

**Comment by TheRealDannyyy** [comment]
I think the reporter tries to point out that NWjs is using _borderless-window fullscreen_ instead of _native fullscreen_ (e.g. with full control over the brightness and resolution of the screen and so on).

**Comment by rogerwang** [comment]
Thanks for reporting. If you mean exclusive fullscreen mode that bypasses window manager, I'm afraid that current Chromium doesn't support it. We'll support it after when Chromium does so. See also https://github.com/w3c/html/issues/375

**Comment by MistakingManx** [comment]
any updates? I want it to overlay overtop Minecraft Bedrock edition when it's full screened. Or any exclusive full screen app for that matter.

My app is an overlay service.

**Comment by MistakingManx** [comment]
I had a weird interaction where it worked randomly for an hour or so and then stopped working.
