### ISSUE TITLE
Phoning home to accounts.google.com

### ISSUE THREAD

**Issue by GHLover** [nwjs/nw.js#7023]
### Expected behavior
No phoning  home to google

### Actual behavior

The software phones home to google on startup. The output on the command line is the following:   [ERROR:cert_verify_proc_nss.cc(974)] CERT_VerifyCert...for accounts.google.com failed err=-8179

### How to reproduce

Get a firewall that will warn you of any outgoing connections. Startup up the software. It will phone home to google.

I am running the app with --disable-sync --disable-background-networking --disable-component-update and it is still contacting google. It is like a virus basically trying to send data to google

**Comment by ffanny** [comment]
Would you please provide a NW app demo for reproducing? Which always phones home to google on startup.

**Comment by bluthen** [comment]
I'm not sure if this is what you need but: 
If I download nwjs v0.37.1 for linux:
Then I run `netstat -tpnc`
I start `./nw` just by itself, so it use the base plain NW.JS page and nothing else, I see in netstat:

`tcp        0      0 10.11.72.249:41016      172.217.4.205:443       ESTABLISHED 12991/./nw`

172.217.4.205 is a google IP.
https://ipinfo.io/172.217.4.205
