### ISSUE TITLE
Crash webview

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7024]
Webview crashing on this site: https://empire.goodgamestudios.com/

Tested on:
* NWjs v0.36.3 - ok
* NWjs v0.36.4 - crash
* NWjs v0.37.1 - crash
* Chromium v73.0.3683.86 - ok

Operating system:
* Windows 10 x64 (1809)

[chrome-app.zip](https://github.com/nwjs/nw.js/files/3017700/chrome-app.zip)

**Comment by panther7** [comment]
@rogerwang This is fatal bug for us, thanks for fast fix. ;-)

**Comment by panther7** [comment]
Probably, this could be problem:
* Fix: Google drive doesn't show contents (#6966)

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-linux-v0.37.0. And It works well with v0.36.3.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by panther7** [comment]
Thanks!
