### ISSUE TITLE
long string of webview dialog will be cut

### ISSUE THREAD

**Issue by caijw** [nwjs/nw.js#7025]
NWJS Version : 0.37.1-sdk and other versions
Operating System : macOS Mojave 10.14.3 

### Expected behavior

The long messageText of the dialog event should not be cut.

### Actual behavior

The long messageText of the dialog event will be cut in some versions.

0.24.4-sdk is ok while 0.37.1-sdk and others versions will cut the string.

### How to reproduce

I have write a example to reproduce this issue, please refer to:

https://github.com/caijw/nwjsApp

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-linux-v0.33.3&v0.36.3&v0.37.0. And it works well with v0.32.3.
