### ISSUE TITLE
Crash dump failing with "http://: Invalid host name" - Test case inside

### ISSUE THREAD

**Issue by GHLover** [nwjs/nw.js#7027]
NWJS Version : 0.37.1
Operating System :Fedora 29

### Expected behavior

Crash dump is uploaded to URL as defined in package.json

### Actual behavior

Crash dump fails with an invalid hostname message:

http://: Invalid host name.
Unexpected crash report id length
Failed to get crash dump id.
Report Id:

The result of this error means the crashdump is NOT uploaded and NOT saved to disk. It vanishes, which is super bad

### How to reproduce

Create any app with a defined "crash_report_url" and then call nw.App.crashBrowser();; to generate a crash dump.

Referring to http://docs.nwjs.io/en/latest/References/Manifest%20Format/#crash_report_url

There is not special note about any URL format that is needed. Some formats I have tried are:

http://localhost/crashreports
https://localhost/crashreports
localhost/crashreports
http://localhost.com/crashreports
https://localhost.com/crashreports
localhost.com/crashreports
http://127.0.0.1/crashreports
https://127.0.0.1/crashreports
127.0.0.1/crashreports

Absolutely no format will work. All return an invalid hostname.

**Comment by ffanny** [comment]
There is a sanity test case about [crash-dump-report](https://github.com/nwjs/nw.js/tree/nw21/test/sanity/crash-dump-report).
You can see that a crash server is needed when using `crash_report_url` .

The [/app/package.json](https://github.com/nwjs/nw.js/blob/nw21/test/sanity/crash-dump-report/app/package.json) is:
`
{
    "name": "crash-report-test",
    "crash_report_url": "http://localhost:2345/reportloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongurl",
    "main": "index.html"
}`

And you can find the dump files in [default path] 
(http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#understanding-crash-dump)  when not use `crash_report_url`.

**Comment by GHLover** [comment]
I have narrowed it down to what causes the bug. It appears there is a bug when "main" refers to a js file instead of an html file. You can see in this test case:

**package.json**

{
  "name": "Test",
  "main": "test.js",
  "crash_report_url": "http://testdomain.com/crashreport"
}

**test.js**

nw.App.crashBrowser();


**Result**

http://: Invalid host name.

Unexpected crash report id length
Failed to get crash dump id.
Report Id:
