### ISSUE TITLE
win.print : duplex option

### ISSUE THREAD

**Issue by drom** [nwjs/nw.js#7030]
NWJS Version : 0.37.0
Operating System : Linux OpenSuSe, Tumbleweed, Kernel 5.0.5

### Expected behavior

win.print should provide "duplex" option.
Chromium Layout engine behaves differently when printing to the duplex device.

Currently CSS property: `break-before: <right | left>;` behaves as for simplex printer.

### Actual behavior

"duplex" option is not documented and take no effect.

### How to reproduce

```js
win.print({
  pdf_path: 'file.pdf',
  duplex: 2, // ???
});
```

**Comment by ffanny** [comment]
nw.Window.print() supports chrome's print function options. And chrome print does not provide `duplex` option when printing to pdf. As `pdf_path` is the path of the output pdf when printing to pdf.
