### ISSUE TITLE
Conflict while rebasing with sync.py

### ISSUE THREAD

**Issue by michalvasek** [nwjs/nw.js#7032]
NWJS Version: 0.37.0
Operating System: Win10

After I check out the tag "nw-v0.37.0" of the "src\content\nw" repo, I am not able to sync with gclient in "src\content\nw\tools\sync.py".

```
src\content\nw\tools> python sync.py
...
> Conflict while rebasing this branch.
> Fix the conflict and run gclient again.
> See man git-rebase for details.
```

If I try to checkout the "src/third_party/node-nw" manually according to dependencies in "src\content\nw\DEPS", I get fatal.
```
$ git checkout ccd5b0187286f938cef808acb5bd0832ad5026a0
$ fatal: reference is not a tree: ccd5b0187286f938cef808acb5bd0832ad5026a0
```

Do we have documentation about how to sync?

**Comment by panther7** [comment]
Probably, git rebase deleting old commits.

**Comment by rogerwang** [comment]
sync.py is developed for the build farm to sync code. It doesn't handle the case that you have local modifications. But it's a simple script, I believe when gclient is called by it with proper switches, it could handle your use case.
