### ISSUE TITLE
nwsaveas broken in latest builds on OSX

### ISSUE THREAD

**Issue by rohan-deshpande** [nwjs/nw.js#7035]
NWJS Version : 0.37.3
Operating System : OSX Mojave 10.14.2

### Expected behavior

File should be saved with the supplied `nwsaveas` property as its file name

### Actual behavior

Files just get prompted to be saved as `Untitled` no matter what

### How to reproduce

This was working in `v0.36.3`, it's broken in `>=0.37.0`

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
