### ISSUE TITLE
Application quits when creating cached binary js

### ISSUE THREAD

**Issue by adaohenrique** [nwjs/nw.js#7036]
NWJS Version : 0.37.3
Operating System : Windows 10 x64

### Expected behavior

It doesn't crash.

### Actual behavior

NWJS closes without any warnings _only on win64_. It works fine on *linux* and *mac*.

### How to reproduce

execute this code snippet on win64-sdk version:

```javascript
const vm = require('vm')
const testScript = "console.log('It works!');"
let script = new vm.Script(testScript, {producedCachedData: true});
let cachedData = script.createCachedData();
```

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-v0.37.3&v0.34.1-win.

**Comment by betsonserviceportal** [comment]
I can reproduce this on 0.39.2

My Intranet application is starting to really frustrate users.  I have an ExtJS application, which runs fine in a browser, but within my NWJS window it's unstable.
