### ISSUE TITLE
dialog event in webview cause nwjs crash

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7038]
nw 0.37.3
[alert 2.zip](https://github.com/nwjs/nw.js/files/3072099/alert.2.zip)

![image](https://user-images.githubusercontent.com/11750641/56020005-a936bf80-5d38-11e9-8d31-929a9dca1ad9.png)
click detach button quickly， after several times 
nwjs crash

ok in nw 0.36.4

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-linux-v0.37.2 and it works well with v0.36.4.

`FATAL:logging_native_handler.cc(46)] Check failed: check_value. Error: WebView: Invalid instance ID (0) from Dialog ok
#0 0x7fc16a8dd599 <unknown>
`

**Comment by rogerwang** [comment]
@ffanny please verify this fix: https://dl.nwjs.io/live-build/nw37/04-12-2019/8ab02faa3/v0.37.4/

And try to add an auto test case for this issue.
