### ISSUE TITLE
Enable GCM no longer works in NWJS 0.37.3

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7039]
NWJS Version : 0.37.3
Operating System :
Windows 10

### Expected behavior

With the flag --enable-gcm, we should be able to register with GCM.
Using chrome.gcm.register

### Actual behavior

This works fine in 0.36.4 - but no longer in 0.37.3

### How to reproduce

See the included sample
[test_gcm.zip](https://github.com/nwjs/nw.js/files/3076476/test_gcm.zip)

Is something changed in the registration @rogerwang ? or are additional permissions needed in the manifest?

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-linux-v0.37.3 and `chrome.runtime.lastError.message:Unknown error.` And it works well with v0.37.2.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
