### ISSUE TITLE
Window control buttons are not vertically centered when window is maximized

### ISSUE THREAD

**Issue by ParticleCore** [nwjs/nw.js#7040]
![ss2](https://user-images.githubusercontent.com/9222661/56096745-26d60900-5eba-11e9-9e00-4b1ca242735f.png)

On the left is a normal maximized file explorer window, on the right is a simple maximized NW.js window. As you can see the buttons on the right are not vertically centered, they are further down than where they should be.

This was tested on Windows 10 x64 with nwjs-sdk-v0.37.1-win-x64 and nwjs-sdk-v0.37.3-win-x64

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-win-v0.37.2 and it works well with v0.36.5.
