### ISSUE TITLE
"open" event has different argument handling on Windows than on Linux, unsafe with Whitespaces on Linux

### ISSUE THREAD

**Issue by julijane** [nwjs/nw.js#7041]
NWJS Version : 0.37.3
Operating System : Linux / Windows

### Expected behavior

Arguments should be provided in the same way on all platforms. Arguments with quoted whitespace should preserve quotation characters.

### Actual behavior

The "open" event is fired when the already open application is called again. The event provides the commandline parameters given with the new invocation.

On windows said parameters are quoted, eg. if you call the exe with parameter `--foo=bar` it is provided as `--foo="bar"`. And if you call it with `--foo="bar baz"`, you get `--foo="bar baz"`.

However on Linux the quotes are missing, you end up with `--foo=bar` and `--foo=bar baz`. The latter one is quite bad, as there is no safe way to determine where the parameter ends when there are more parameters.

### How to reproduce

`nw.App.on('open', (args)=>{console.log(args)})`

and call the Application with parameters like suggested.

**Comment by ffanny** [comment]
I can confirm that on Linux I get `--foo=bar baz` when I use `--foo="bar baz"` and on Windows 10 I get `--foo="bar baz"`.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by ffanny** [comment]
The fix has been verified in [this build](https://dl.nwjs.io/live-build/nw38/04-17-2019/5f5cf1429/v0.38.0/).
I get `--foo="bar baz"` when I use `--foo='bar baz'`.
