### ISSUE TITLE
Unable to open task manager

### ISSUE THREAD

**Issue by ParticleCore** [nwjs/nw.js#7042]
This was tested on Windows 10 x64 with nwjs-sdk-v0.37.3-win-x64

Chromium has a built in Task Manager that can be accessed either via the tools menu (which is not available on the NW.js) or by pressing `Shift` + `Esc`. Since NW.js does not provide a tools menu on the top right, the shortcut is the only way to open the task manager, but it is not working. When pressing the shortcut keys nothing happens.

The built in task manager provides a more accurate and reliable resource usage than Window's default task manager, which is why it is important to have that kind of insight at least on the SDK version of NW.js

Is this an intended behavior? If yes, how can we then open the task manager? If no, is there a way around it in the mean time?

**Comment by ffanny** [comment]
Thank you. Will try to implement it.

**Comment by ffanny** [comment]
You can use `chrome.processes` [API](https://developer.chrome.com/extensions/processes) to interact with the browser's processes. A demo is provided [here](https://github.com/ffanny/nw.js/tree/reproducecode/code/process_monitor).

**Comment by elpeleq42** [comment]
> You can use `chrome.processes` [API](https://developer.chrome.com/extensions/processes) to interact with the browser's processes. A demo is provided [here](https://github.com/ffanny/nw.js/tree/reproducecode/code/process_monitor).

I tested that demo you sent, but there seems to be a few problems with it. For example:
-All titles are undefined
-Network is almost always 0(Even when downloading a file using an HTTP.get)
-New windows don't aappear on it.
-etc
