### ISSUE TITLE
Memory and CPU continue to grow, leading to process exit！

### ISSUE THREAD

**Issue by ChaoshengZhang** [nwjs/nw.js#7043]
======== TEMPLATE BUG FORM ========

NWJS Version :  0.37.3
Operating System : window10  

### Expected behavior

当我打开的时候CPU占用应该是固定不变的，内存也是一样固定不变的。
When I open it, CPU usage should be fixed, and memory should be fixed as well.

### Actual behavior

本来使用的nw的0.34.5版本的机子，但是在部分电脑上运行一段时间后内存与CPU一直在增加，当内存达到顶峰时，nw就会自动退出。然后我升级了nw版本到0.37.3，一开始运行正常了，但是重启电脑再次打开nw就会出现这个问题。请问这个问题有什么解决方案么？

The original version of NW 0.34.5 machine, but after running on some computers for a period of time, memory and CPU have been increasing, when memory reaches its peak, NW will automatically exit. Then I upgraded the NW version to 0.37.3, which started to work properly, but the problem would arise if I restarted the computer and opened NW again. What is the solution to this problem?

这里是dump信息：
Here is dump information:

Microsoft (R) Windows Debugger Version 6.12.0002.633 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Users\iFLYREC\AppData\Local\Temp\nw (2).DMP]
User Mini Dump File with Full Memory: Only application data is available

WARNING: Minidump contains unknown stream type 0x15
WARNING: Minidump contains unknown stream type 0x16
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 7 Version 15063 MP (8 procs) Free x64
Product: WinNt, suite: SingleUserTS
Machine Name:
Debug session time: Tue Apr 16 11:44:47.000 2019 (UTC + 8:00)
System Uptime: 0 days 0:10:50.627
Process Uptime: 0 days 0:01:06.000
................................................................
......
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
*** WARNING: Unable to verify checksum for nw.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for nw.dll - 
nw_7ffcd0ad0000!v8::internal::NativesCollection<2>::GetScriptsSource+0x93846:
00007ffc`d244f336 4d8b9510450000  mov     r10,qword ptr [r13+4510h] ds:00000219`137878c8=000002191378a468

### How to reproduce
请看这个视频
See this video.
[http://pq1o6lmu4.bkt.gdipper.com/3f72dc5ea2a0e1a457d47d774bb9a5fd.mp4](url)

**Comment by ffanny** [comment]
Your video URL is not available so I don't understand your question well.

**Comment by ChaoshengZhang** [comment]
复制视频地址到浏览器地址栏就可以打开了
Copy the video address to the browser address bar and open it.

**Comment by rogerwang** [comment]
Please make sure your application don't have leak first. devtools could help you. Thanks.

**Comment by ChaoshengZhang** [comment]
![test2](https://user-images.githubusercontent.com/10227693/56334015-38285980-61c9-11e9-9905-d43008d82d36.gif)

我已经看了我的开发者工具，一切都是正常的，关键这在部分机型上出现这个问题。
I've seen my developer tools, everything is normal, the key is this problem on some models.

**Comment by ChaoshengZhang** [comment]
我是通过  nw.open 重新打开一个窗口，打开后内存与cup就开始增长，代码层面看了没有问题。
I reopened a window through `nw.open` ,After opening, memory and cup begin to grow, and there is no problem at the code level.

**Comment by rogerwang** [comment]
Could you give detail on which nw process has the issue? Please provide the full command line string for the process. And provide NW crash dump if possible: http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/

And on what kind of system does it crash?

**Comment by ChaoshengZhang** [comment]
请问，nw.Window.maximize()，最大化这个方法在部分机型会引起内存与CPU的持续增加么？
Dear Author, hello,   this method of `nw.Window.maximize()` will cause the continuous increase of memory and CPU in some models?

**Comment by rogerwang** [comment]
No it shouldn't.
