### ISSUE TITLE
nwjs-ffmpeg-prebuilt  

### ISSUE THREAD

**Issue by zackCzy** [nwjs/nw.js#7044]
Where to download ffmpeg version of windows 37.3 ？

**Comment by ffanny** [comment]
All downloads version NW.js provide can be found in [nwjs.io/downloads/](https://nwjs.io/downloads/).
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
It should be asked in nwjs-ffmpeg-prebuilt project.
