### ISSUE TITLE
Win.print({printer: "xxx"}) doesn't use the specified printer for some printer names.

### ISSUE THREAD

**Issue by LaurenceMommers** [nwjs/nw.js#7046]
NWJS Version : win64 v0.38.1 (SDK)
Operating System : win10

### Expected behavior

`win.print({printer: "xxx"});`
should use the given printer ('xxx');

### Actual behavior

'Save to PDF' is used instead of the given printer.

### How to reproduce

I opened a DevTools window and executed the following code to test:
`nw.Window.open("test.pdf", {show: false}, function (w) { window.newWindow = w; });`

`window.newWindow.getPrinters(console.log)`
=> Returns 5 printers. 2 of these are: 

- '{cupsEnterprisePrinter: false, deviceName: "Microsoft XPS Document Writer", printerDescription: "", printerName: "Microsoft XPS Document Writer", printerOptions: {…}}'
- '{cupsEnterprisePrinter: false, deviceName: "\\MRICOH001\printer netherlands", printerDescription: "MyPrint Area Printers", printerName: "printer netherlands on MRICOH001", printerOptions: {…}}' **(desired printer to use)**

`window.newWindow.print({printer: "printer netherlands on MRICOH001"})`
=> 'Save to PDF' is used.

`window.newWindow.print({printer: "\\MRICOH001\printer netherlands"})`
=> 'Save to PDF' is used.

`window.newWindow.print({printer: "Microsoft XPS Document Writer"})`
=> 'Microsoft XPS Document Writer' is used.

`window.newWindow.print({printer: "[[this doesn't printer exist]]"})`
=> 'Save to PDF' is used.

It looks like this issue https://github.com/nwjs/nw.js/issues/6510.
However this time it seems to work for some of the printers (e.g. "Microsoft XPS Document Writer").

**Comment by ffanny** [comment]
nwjs-sdk-win-v0.38.1&v0.37.4
I tried with 5 printers in the picture below by `win.getPrinters`. They all work well but I don't have a real printer to test whether it has a problem.
<img width="501" alt="2019-04-30" src="https://user-images.githubusercontent.com/19678102/56947124-c227d900-6b5e-11e9-9d51-4adc95a21334.png">

**Comment by aleafworld** [comment]
The value of "printer" only supports 'deviceName' of the printers, not 'printerName'.
and you should set the string like "\\\\\\MRICOH001\\printer netherlands"

**Comment by LaurenceMommers** [comment]
This was indeed the issue, sorry for the incorrect bug report. I completely forgot about escaping the backslashes!
