### ISSUE TITLE
NW.js can't load fonts and images from memory cache

### ISSUE THREAD

**Issue by road0001** [nwjs/nw.js#7047]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :0.35.5
Operating System :Windows 10 1903

### Expected behavior
I use NW.js to create my app, the resources include images, fonts, and others, the size of images and fonts is a little big, the fonts more than about 10MB, the image more than about 4MB, they are all on my disk, app will load them from local.

### Actual behavior
When the app is loaded with NW.js, the fonts and images load slower than the html, that cause the problem, the text can't display until the fonts loaded, the same as images.
My app can also run in browser, I have a local server to deploy them, and the app can run best in chrome, although the first load is a bit slow, but the follow-up performance is very good, fonts and images are not load slow.
In dev-tools, I find in the network tags, the size of resources are "from disk cache", but this will be "from memory cache" in chrome, this is the reason of fonts and images load too slow.

### How to reproduce
- Put a large font file in app's folder.
- Set local fonts in css, and use it in html, please keep the size of font is enough large (>=10MB):
@font-face{
	font-family:'MAIN_FONT';
	src:url('../resources/fonts/msyh.ttf');
}
- The same as image, the size of image can be 4MB or more.
- Refresh the page, and observed the loading of page.

### Temporary solution
- Install the fonts for system.
- Don't use font-face to set local fonts in css.
- Set font-face to the name of font in css.
- But large image can't use this solution.

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-win-v0.3.8.1. 
And NW.js loads resources like `css, js, jpg...` from `disk cache` when I using `nw.Window.get().reload()`.
