### ISSUE TITLE
No way to change localStorage limit

### ISSUE THREAD

**Issue by CoryGH** [nwjs/nw.js#705]
When using node-webkit to run an application that relies heavily on localStorage I get:

Error: QuotaExceededError: DOM Exception 22

While performing a call to localStorage.setItem(key, value)

Everything I've seen regarding this on node-webkit suggests that localStorage is expected to default to unlimited (as in however much available disk space there is), but the hard drive is far from full and I'm getting this error - the dataset is a little over 6MB.

**Comment by oleander** [comment]
Any news on this subject?

**Comment by JordanDelcros** [comment]
Yep, still a problem...

**Comment by ashantyk** [comment]
end of 2015 an still a problem

**Comment by TomasHubelbauer** [comment]
The link to the supposed commit removing the limit is dead now. Does anyone have up-to-date info on what the local storage size limit is in NW.js?

**Comment by Dreamsavior** [comment]
I can confirm that there is a local storage limit on the latest version.

Run this from your nw.js to test:
`window.open('https://arty.name/localstorage.html')`
