### ISSUE TITLE
Error in "0.39.0-beta1"

### ISSUE THREAD

**Issue by fprijate** [nwjs/nw.js#7050]
NWJS Version : nwjs-sdk-v0.39.0-beta1-win-x64
Operating System : Win 10

Program crashes after:

```
nw.Window.get().on('close', () => {
  nw.App.quit();
});
```

    Uncaught TypeError: This event does not support filters
        at NWWindow.on (extensions::nw.Window:206)
        at eval (clientInit.js?9ffe:20)
        at Object.<anonymous> (main.js:1977)

**Comment by ffanny** [comment]
I can reproduce it with nwjs-sdk-win-v0.39.0-beta1 using `nw.Window.open("c.html",{},function(win){win.on('close', () => { });});`.

<img width="462" alt="2019-05-11" src="https://user-images.githubusercontent.com/19678102/57564028-19883d80-73d8-11e9-9334-cc4c11aed1cc.png">

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [build](http://dl.nwjs.io/live-build/).
