### ISSUE TITLE
nwjs and sqlite-cipher build exe

### ISSUE THREAD

**Issue by shrewst** [nwjs/nw.js#7053]
nw.js v0.38.3
windows 7
The sqlite-cipher library is included in the exe file, such is the axis of the problem http://prntscr.com/nphqct, and my program will be launched without my own library, let it be caress, go ahead

**Comment by ffanny** [comment]
Could you please provide more info such as error prompts to describe your problem?
And Native Node modules, built when running `npm install,` are not compatible with NW.js ABI. To use them, you have to rebuild it from source code with `nw-gyp.` See [Use Native Node Modules](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/) for details.
