### ISSUE TITLE
DevTools window open with same size as main app window

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7054]
NWJS Version : 0.37.4
Operating System : Windows 10/ Mac OS

### Expected behavior

Devtools size should be independent from the main window size specified in the manifest

### Actual behavior

Devtools open with same size as main window - very inconvenient if main window is a small window like transparent loader window, then we always have to resize the devtools window

### How to reproduce

See the included demo project

[devtools_window.zip](https://github.com/nwjs/nw.js/files/3189115/devtools_window.zip)

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-win-v0.37.4&v0.38.1 using `  "window": { "height": 200, "width": 200 }.` in manifest.
<img width="331" alt="2019-05-17" src="https://user-images.githubusercontent.com/19678102/57901155-68314e00-7896-11e9-8b2a-82d01042d050.png">
