### ISSUE TITLE
App crashes seconds after launching

### ISSUE THREAD

**Issue by acemod13** [nwjs/nw.js#7055]
NWJS Version : 0.38.x (happens on the latest version as well)
Operating System : Windows 10

### Expected behavior
Once the app launches, it stays active until the user exits the app.

### Actual behavior
If the app's js files are compiled and then packaged into an archive named package.nw (the file extension is nw), the app would load but after a few seconds, it would close. Sometimes, it would print a message like this: [0518/104704.936:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The function was completed successfully. (0x0)

### How to reproduce
(At the moment, I was able to confirm affecting RPG Maker MV)
- Compile the JS files to binary using nwjc. Any calls to another script (and is loaded with a script) need to use the specific call to properly load it.
-Compress the app's files to package.nw. Make a zip file named package.zip, then change the file extension.
-Start the app.

**Comment by HxShard** [comment]
Got same issue.
Also, in crush dump I can see something like:

`Operating system: Mac OS X
                  10.14.3 18D109
CPU: amd64
     family 6 model 158 stepping 10
     12 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_INSTRUCTION / EXC_I386_INVOP
Crash address: 0x111ad0972
Process uptime: 19 seconds

Thread 0 (crashed)
 0  nwjs Framework + 0x6a7f972
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x000000010b02666c   rbx = 0x00007fff8a4329a0
    rsi = 0x00000000000120a8   rdi = 0x00007fff8a432028
    rbp = 0x00007ffee7e24a60   rsp = 0x00007ffee7e24758
     r8 = 0x00000000000130a8    r9 = 0x0000000000000000
    r10 = 0x00007fff8a432048   r11 = 0x00007fff8a432040
    r12 = 0x00000001135195c9   r13 = 0x00007ffee7e24a20
    r14 = 0x0000000000000000   r15 = 0x00000001135a6560
    rip = 0x0000000111ad0972`

**Comment by HxShard** [comment]
Fixed by downgrading to 0.37.4.

**Comment by theDevelopper** [comment]
i have the same problem with 0.38.x. All worked fine with 0.37.4.
We see the same behaviour on Mac and Windows!

We only habe the issue if we build and bundle our app for distribution, not when we run it during development via `nw ./dist` (we use npm package nw [https://www.npmjs.com/package/nw]).
both nw and the build script use the same version.

this is kind of a blocker for us as we need to keep up with latest versions.

checked the crash dump generated by 0.38.4 on mac and got:

```
Operating system: Mac OS X
                  10.14.4 18E226
CPU: amd64
     family 6 model 142 stepping 9
     4 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_INSTRUCTION / EXC_I386_INVOP
Crash address: 0x108d77482
Process uptime: 2 seconds

Thread 0 (crashed)
 0  nwjs Framework!Abort [platform-posix.cc : 400 + 0x0]
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x00000001113a166c   rbx = 0x00007fffa09019a0
    rsi = 0x00000000000120a8   rdi = 0x00007fffa0901028
    rbp = 0x00007ffeeda38160   rsp = 0x00007ffeeda37e58
     r8 = 0x00000000000130a8    r9 = 0x00007fffa0901048
    r10 = 0x0000000000000000   r11 = 0x00007fffa0901040
    r12 = 0x000000010a7d7d86   r13 = 0x00007ffeeda38120
    r14 = 0x0000000000000000   r15 = 0x000000010a864e30
    rip = 0x0000000108d77482
    Found by: given as instruction pointer in context
 1  nwjs Framework!For [scanner-character-streams.cc : 789 + 0x17]
    rbp = 0x00007ffeeda381b0   rsp = 0x00007ffeeda38170
    rip = 0x000000010463adc8
    Found by: previous frame's frame pointer
 2  nwjs Framework!ParseFunction [parsing.cc : 65 + 0xf]
    rbp = 0x00007ffeeda38680   rsp = 0x00007ffeeda381c0
    rip = 0x0000000104623f1b
    Found by: previous frame's frame pointer
```

**Comment by theDevelopper** [comment]
tried 0.39.0-beta1 but it also crashes

**Comment by theDevelopper** [comment]
0.39.1 seems to have fixed the issue for me

**Comment by acemod13** [comment]
I can confirm that 0.39.1 fixed the crash.
