### ISSUE TITLE
Unable to get process.env on Mac

### ISSUE THREAD

**Issue by jaffoneh** [nwjs/nw.js#706]
If I run node on my machine and run process.env I am able to see the environment variables I've defined in .profile or bash_profile but when running node-webkit, I only get the system defined variables (like HOME, USER, etc) and I do not get any of the variables I defined in .profile or .bash_profile.
##

**Comment by dhruska** [comment]
I know this is very old, but I'm also experiencing this, specifically for environment variables I've defined with dotenv.

**Comment by RJSzynal** [comment]
I believe I'm seeing a similar issue.
When running nw.js from the .app (and therefore not in bash) only limited Env vars are available (including a much reduced PATH), however when running the nw executable from within the .app it runs in bash and has full access.
This causes an issue when using the shelljs module and calling the 'which' function as it doesn't find binaries which do exist.
