### ISSUE TITLE
nw.Clipboard can't set picture in the clipboard

### ISSUE THREAD

**Issue by YutaoChow** [nwjs/nw.js#7060]
NWJS Version : nwjs-v0.35.5-win-ia32
Operating System : win10/win7

### Expected behavior
I try to use Clipboard to copy picture,it success in small picture(<2MB) and get some error in big picture(>2MB);

### code
const fs = require('fs');
const clipboard = nw.Clipboard.get();
//picture path
const data  =fs.readFileSync(C:\\Users\\Ming\\AppData\\Local\\files\\1525340689393.png")；
clipboard.set(data.toString('base64'),'png',true)
![image](https://user-images.githubusercontent.com/20595456/58310914-5887ab80-7e3a-11e9-9170-56380be6d83b.png)
The size of picture is about 4MB.

**Comment by TheJaredWilcurt** [comment]
You could try
```js
let clipboard = nw.Clipboard.get();
clipboard.set([
  { type: 'png', data: imgBuf.toString('base64'), raw: true },
  { type: 'html', data: '<img src="path/to/image.png">' }
])
```
from: https://github.com/nwjs/nw.js/issues/4825
