### ISSUE TITLE
Issue after codesigning windows exe file created in nw.js framework

### ISSUE THREAD

**Issue by factualsoft** [nwjs/nw.js#7062]
Background: 
App was developed in nwjs version 0.36.4.
Created exe file using Installforge Exe file works fine

Signed the code / exe file using DigiCert, here were step by step process provided to us by digitcert: https://knowledge.digicert.com/solution/SO20528.html

Issue: 
After signing the cert, I double clicked on the exe file. An alert pops up, "Do you want to allow this app to make changes to your device?" displaying the company name as verified publisher, this was as expected by MS windows. I clicked on "Yes" button.

After this nothing happens, expectation was that the installation window pops up. When I go to task manager, I see the application consuming resources (CPU, Memory etc..).

I contacted DigiCert multiple times, they verified the exe file and they said it was signed correctly and they do not know why the application is not kicking off installation process.

Unfortunately we are stuck here. Appreciate if you could guide us.

Thanks 
Natraj

**Comment by rogerwang** [comment]
Is it an issue of Installforge ?

**Comment by factualsoft** [comment]
We don’t know what the issue is.  Do you know the fix?

Regards
Natraj
