### ISSUE TITLE
Right Click Menu for images

### ISSUE THREAD

**Issue by asteriosgr** [nwjs/nw.js#7065]
NWJS Version : Any nwjs version above 0.35.X
Operating System : Ubuntu 18.04 x64

### Expected behavior
Right click save image as, open image in new tab menu should appear.

### Actual behavior
Right click menu on non-sdk version has only the copy function.

### How to reproduce

Try to right click on an image. Then right click when selecting a text.

My question is what happened to the right click menu options for images?

**Comment by TheJaredWilcurt** [comment]
You are building an application, not a webpage in a browser. Therefore, right-click does not do what it does for webpages in browsers. You can add in your own context menu, with whatever functionality you like. There are even small JS libraries for NW.js that you can use.

* https://github.com/b1rdex/nw-contextmenu
* https://github.com/TheJaredWilcurt/nw-tray-example
