### ISSUE TITLE
App crashes when loading compiled Javascript source

### ISSUE THREAD

**Issue by Mann90** [nwjs/nw.js#7068]
NWJS Version : 0.38.4
Operating System : MacOS 10.14.5

After upgrading NW.js to v0.38.4 from v0.37.1, my app crashes very often on loading the compiled Javascript binary files. (The Javascript source code was not changed.)
----Crash message------
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffeea2bc8300   nwjs Framework                      0x0000000108dcbe19 v8_inspector::V8StackTraceId::IsInvalid() const + 13712761
1   nwjs Framework                      0x0000000108cf1273 v8_inspector::V8StackTraceId::IsInvalid() const + 12816851
2   nwjs Framework                      0x000000010c50af3b v8_inspector::V8StackTraceId::IsInvalid() const + 71642779
3   nwjs Framework                      0x000000010c4eda45 v8_inspector::V8StackTraceId::IsInvalid() const + 71522725
4   nwjs Framework                      0x0000000107db4dc8 v8::internal::ScannerStream::For(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, int, int) + 952
5   nwjs Framework                      0x0000000107d9df1b v8::internal::parsing::ParseFunction(v8::internal::ParseInfo*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*) + 171
6   nwjs Framework                      0x000000010785c32e v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) + 926
7   nwjs Framework                      0x000000010785c8b0 v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) + 208
8   nwjs Framework                      0x0000000107e39567 v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const + 87975
9   nwjs Framework                      0x00000001081755c2 v8_inspector::V8StackTraceId::IsInvalid() const + 775458
10  nwjs Framework                      0x00000001080dfb6b v8_inspector::V8StackTraceId::IsInvalid() const + 162507
Received signal 4 <unknown> 00010c4f1482
 [0x000108dcbe19]
 [0x000108cf1273]
 [0x000108dcbd31]
 [0x7fff5b635b5d]
 [0x00000000ffff]
 [0x000107db4dc8]
 [0x000107d9df1b]
 [0x00010785c32e]
 [0x00010785c8b0]
 [0x000107e39567]
 [0x0001081755c2]
 [0x0001080dfb6b]
[end of stack trace]
[0602/164257.829132:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeea2c9000, 0x2000): (os/kern) invalid address (1)
[0602/164257.920883:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)

**Comment by Mann90** [comment]
[be7ecc5a-9fdb-43e2-88bb-84eaad3651a2.dmp.zip](https://github.com/nwjs/nw.js/files/3245227/be7ecc5a-9fdb-43e2-88bb-84eaad3651a2.dmp.zip)

**Comment by GHLover** [comment]
I also am experiencing this in the same version. Other versions are not affected (yes, I compiled using the same versions)

**Comment by rogerwang** [comment]
I'm merging this with #7045 . @Mann90 could you please see the discussion there and provide a case. Thanks.
