### ISSUE TITLE
[resolved] use `require('nw.gui')` in html cause error `Uncaught Error: Cannot find module 'nw.gui' `

### ISSUE THREAD

**Issue by davy-tw** [nwjs/nw.js#707]
entry.html: (BEGIN)

<script>
  "use strict";
  console.log(require);
  var gui = require('nw.gui');
</script>

(END)

I just run this file using node-webkit and got log: (BEGIN)
function (name) {  if (name == 'nw.gui')    return nwDispatcher.requireNwGui();  return global.require(name);} entry.html:3
Uncaught Error: Cannot find module 'nw.gui' module.js:343
(END)

But when I do this in console:
`require('nw.gui')`
It returned the right Object of 'nw.gui'.

node-webkit version: v0.5.1, v0.5.0

**Comment by hhsnopek** [comment]
@david50407 thank you for figuring this out!! Glad you did, helped me a lot :smile:
