### ISSUE TITLE
(MacOS) Error on quit

### ISSUE THREAD

**Issue by vonEdfa** [nwjs/nw.js#7070]
NWJS Version : 0.38.4
Operating System : MacOS 10.14.5

### Expected behavior

NW.js should quit gracefully without errors.

### Actual behavior

About 80% of the time I exit my NW.js app I get an error in the terminal.

There seems to be a few different ones that may appear. Here's a few:
```
[43264:46851:0605/120344.598442:ERROR:process_mac.cc(91)] task_policy_set TASK_CATEGORY_POLICY: (ipc/send) invalid destination port (0x10000003)
```
```
[43246:38659:0605/120319.688383:ERROR:unix_domain_socket_acceptor.cc(73)] unlink: No such file or directory (2)
```

**Possible Wildcard:** I have [RedQuits](http://www.carsten-mielke.com/redquits.html) installed. Not sure if that should interfere or not, but might be worth pointing out.

### How to reproduce

1. Init a NW.js app (I'm using the [Getting Started](http://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/#write-nwjs-app) configuration)
2. Start it.
3. Let it run for a while (5-10s minimum).
4. Exit the app through SIGINT (`Ctrl+C`), the window's close button or through `Command+Q`.
5. Notice the errors in the terminal.

**Comment by vankasteelj** [comment]
what happens if you close it with devtools `require('nw.gui').Window.get().close(true)` ?

**Comment by vonEdfa** [comment]
Devtools doesn't seems to be available in that build?
I might be missing something, but I can't get them to show.

**Comment by vonEdfa** [comment]
Interestingly though, I don't get the error anymore (after updating to latest) when I follow my steps.

Versions:
node v12.10.0 (npm 6.11.3)
nwjs 77.0.3865.90 (npm says nw@0.41.2)
