### ISSUE TITLE
HLS.js player is not working

### ISSUE THREAD

**Issue by ntnahn** [nwjs/nw.js#7072]
NWJS Version : 0.38.4
Operating System : macOS 10.13.6

### Expected behavior

HLS.js player will work ok with .m3u8 streaming file

### Actual behavior

It cause problem and cannot load video streaming

### How to reproduce

- Add the link to official hls.js and it cannot load the demo url
````<a href="https://hls-js.netlify.com/demo/">Test hls player</a>````

**Comment by TheJaredWilcurt** [comment]
@ntnahn 

What was the last version of NW.js the video played in. If this is your first version of NW.js you've tested have you read this:

* http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/#enable-proprietary-codecs
