### ISSUE TITLE
White border on main window with frame:true (was Dark grey on previous versions)

### ISSUE THREAD

**Issue by vankasteelj** [nwjs/nw.js#7073]
Hi,

NWJS Version : 0.38.4-sdk
Operating System : Windows 10

### Expected behavior
The "frame", the outline of the window was invisible, it's now a 1 or 2px white line. On Chrome, it's a black line.

### Actual behavior
The "outline" of the app is white now, for some reason. The devtool window outline is black however.

### How to reproduce
open a nwjs window with "frame: true"

============

Here are two screenshots: 1 of the main window on a colored background (to show the white), 1 of the devtool window on a white background (to show the black).

![2019-06-10_09-52-29](https://user-images.githubusercontent.com/12599850/59180603-a5bb8b00-8b65-11e9-9412-49be164b290d.png)
![Brackets_2019-06-10_09-52-59](https://user-images.githubusercontent.com/12599850/59180609-a6ecb800-8b65-11e9-8188-ac9e05ebff1d.png)

**Comment by TheJaredWilcurt** [comment]
That 1px (or 2px on HDPI screens) border comes from Windows Theme color.

![Windows Theme settings and an NW.js app](https://user-images.githubusercontent.com/4629794/59471145-33b6a080-8e08-11e9-9898-cef68f5f14bb.png)


The border will inherit the theme color. When the app is not in focused it will be black or a very dark version of the color (orange -> dark brown in the above example). You can make a frameless app if you want complete control of all the pixels, but will need to create your own buttons for minimize/maximize/restore/close.

Example:

![screenshot of an app](https://camo.githubusercontent.com/e34a23e9e2a12498841eabc1c01428db82cfb2d6/687474703a2f2f692e696d6775722e636f6d2f6d74383052525a2e676966)

**Comment by vankasteelj** [comment]
Right, but that doesn't explain why there's a black border on Chrome (itself & devtool) and nwjs' devtool, while it's white on nwjs itself.

**Comment by TheJaredWilcurt** [comment]
Because those windows are not opting in to the OS's color theme. The devtools use a light gray title bar. You need to acknowledge that the frame surrounding your app will be different in each OS. You can either let your app live inside a standard framed window that the OS gives you, or remove the frame to have complete control over the UI in all OS's.

**Comment by vankasteelj** [comment]
Let me phrase this another way: 

- 0.32.4: dark grey border
- 0.36.4: dark grey border
- 0.37.4: white border
- 0.38.4: white border

I'm asking for the return of the dark grey border.

Examples with 0.32.4 vs 0.37.4:
![2019-06-17_08-07-26](https://user-images.githubusercontent.com/12599850/59582048-44506a80-90d7-11e9-98d1-062c31c5856d.png)
![2019-06-17_08-08-06](https://user-images.githubusercontent.com/12599850/59582049-461a2e00-90d7-11e9-9c3d-3f945755878a.png)

**Comment by vankasteelj** [comment]
as of 0.44.3, the dark grey border is back!
