### ISSUE TITLE
osx 0.39.0 crash when the `nwjs helper` is changed

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7075]
NWJS Version : 0.39.0
Operating System : osx

### Expected behavior

we can change `nwjs helper` to any other name 

![image](https://user-images.githubusercontent.com/11750641/59243131-09ff4d00-8c41-11e9-85a9-9836d4ac8639.png)

### Actual behavior

crashed

![image](https://user-images.githubusercontent.com/11750641/59243230-6ebaa780-8c41-11e9-8437-c5b612e67e6a.png)

it seems to search for nwjs helper, the picture below shows that a nwjs helper folder will be created once we run the application

![image](https://user-images.githubusercontent.com/11750641/59243242-81cd7780-8c41-11e9-8acd-23e6b7c5fdfe.png)

**Comment by theDevelopper** [comment]
could be the same than this:
https://github.com/nwjs/nw.js/issues/7055

**Comment by Blatman** [comment]
Just checked this myself and renaming is broken with 0.39.0

MacOS High Sierra 10.13.6

Procedure works up to 0.38.5 but broken on 0.39.0

App will crash with trap 3 and leave a partial nwjs Helper package in the 75.0.3770.80 folder next to hippo Helper

In the Activity Monitor hippo process will appear with correct app icon but Helper processes fail to generate. With 0.38.5 the main hippo process will be shown with the correct app icon and a variable number of hippo Helper processes will appear also.


Changes to a typical app -

hippo.app/Contents/Info.plist - CFBundleDisplayName nwjs --> hippo

hippo.app/Contents/MacOS - remains as nwjs (never had to change this before, get can't be opened error if it is renamed even with Info.plist adjusted - docs ????)


Adjust the localisation files -


hippo.app/Contents/Resources/en.lproj/InfoPlist.strings - CFBundleDisplayName nwjs --> hippo

hippo.app/Contents/Resources/en_GB.lproj - CFBundleDisplayName nwjs --> hippo



Adjust the Helper -

hippo.app/Contents/Versions/75.0.3770.80/nwjs Helper/Info.plist - CFBundleDisplayName nwjs Helper --> hippo Helper

hippo.app/Contents/Versions/75.0.3770.80/nwjs Helper/Info.plist - CFBundleExecutable nwjs Helper --> hippo Helper 

hippo.app/Contents/Versions/75.0.3770.80/nwjs Helper/Info.plist - CFBundleName nwjs Helper --> hippo Helper




hippo.app/Contents/Versions/75.0.3770.80/nwjs Helper/MacOS/ - nwjs Helper --> hippo Helper

hippo.app/Contents/Versions/75.0.3770.80/ - nwjs Helper --> hippo Helper

Note: for purposes of testing I just copied the app.icns, document.icns and app.nw folder into the Resources folder of the test package and did adjustments as above.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
