### ISSUE TITLE
nw intellisense vscode ?

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#7076]
Any of you guys are allow to get intellisense for nw ?

NWJS Version :
Operating System : win 10

### Expected behavior
see intellisense with `nw`
### Actual behavior
nw show `any`

is this feature existe ?
![image](https://user-images.githubusercontent.com/24865815/59244730-ae52a680-8be3-11e9-8848-c2ad61a6eb88.png)

**Comment by TheJaredWilcurt** [comment]
```
npm install --save-dev nwjs-types
```
