### ISSUE TITLE
[ 0.39.0 ] Removing Listening events from a window is broken

### ISSUE THREAD

**Issue by DimPaDev** [nwjs/nw.js#7077]
NWJS Version : 0.39.0
Operating System : Tested on Windows, Linux 

### Expected behavior

When a listening event is attached to a nw Window, it should be possible to remove it later.

### Actual behavior

The event is not removed from the window and the following log is being displayed in the console : 
```
Uncaught TypeError: this.appWindow[appWinEventsMap[event]].getListeners is not a function or its return value is not iterable
    at NWWindow.removeListener (extensions::nw.Window:270)
    at index.html:15
```

### How to reproduce

```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
  
  <script>
  
var win = nw.Window.get();

win.on('move', () => console.log('window move event triggered'));
win.removeListener('move', () => console.log('move event should be removed'));

// or remove all listeners 
// win.removeAllListeners();
  
  </script>
  
</html>
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
