### ISSUE TITLE
Webview website submit a post form with target = _blank

### ISSUE THREAD

**Issue by tadada** [nwjs/nw.js#7082]
**NWJS Version:** 0.14.7

**Operating System:** Windows 10 Professional

### Expected behavior
When webview website submit a post form with target = _blank,  should catch a newwindow  event with full post request.

### Actual behavior
But can only get a targetUrl, nothing else. 
Except NewWindow event, Is there some other solutions ?

**Comment by TheJaredWilcurt** [comment]
@tadada can you post the minimal amount of code for this
