### ISSUE TITLE
Method to detect 2nd launch attempt

### ISSUE THREAD

**Issue by RWGuy** [nwjs/nw.js#7083]
NWJS is now single-instance. There should be a way to inform an already running nwjs that the user attempted to run it again. For many apps this event can be used to better meet the needs of the user from the existing app. Without this functionality the user is left very confused as to why they tried to run an app and it did nothing as current behavior it just silently fails.

For example, the most obvious and universal benefit would be to restore an app from system tray if the user attempted to run it again.

I envision there being some listener event that will get called within an app if the user attempts to run it the app again

**Comment by rogerwang** [comment]
The `App.open` event will be sent to the running instance if you try to launch another instance.
