### ISSUE TITLE
Does NOT work as advertised

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [nwjs/nw.js#7084]
So supposedly the whole point of NW.js is to turn webpages, or servers, or both, into a single executable (with dependencies in the same folder of course, I know to LITERALLY make just 1 .exe file you have to use something like Enigma).

I have had success with turning webpages into an app with NW.js.

But not server + webpages.  For instance, while my localhost server runs in node just fine, it does not run in NW.js.  I get some strange chrome extension error, along with socket.io.js not found.

You need to either clarify that your product is NOT actually capable of doing everything Node can, or explain how to achieve this in the readme or someplace.

**Comment by rogerwang** [comment]
That should be a bug and we'd like to fix it. Please provide a case so that we can reproduce your issue. Thanks.

**Comment by TheJaredWilcurt** [comment]
@MelerEcckmanLawler

Here is a working example for how to make NW.js start a local webserver and navigate to the `localhost` address in the spawned window (with Node access from the DOM).

* https://github.com/nwutils/nw-local-server-example

The `README.md` on that repo explains how it's set up.

**Comment by rogerwang** [comment]
close until more information is available.
