### ISSUE TITLE
Crash in forked child process when calling node method runInNewContext.

### ISSUE THREAD

**Issue by ermod** [nwjs/nw.js#7085]
NWJS Version : 0.29.4 - 0.39.1
Operating System : Linux, Windows 10

### Expected behavior
Process created by
`child_process.fork('./src/child.js', { stdio: 'pipe' })`
should not crash when calling `runInNewContext`

### Actual behavior
When calling `runInNewContext` in a process created by
`child_process.fork('./src/child.js', { stdio: 'pipe' })`
The child process crashes with:
`FATAL ERROR: v8::Context::SetAlignedPointerInEmbedderData() Pointer is not aligned`

### How to reproduce
Create a child process with:
`child_process.fork('./src/child.js', { stdio: 'pipe' })`
In the childprocess run this code:
```
  const { runInNewContext } = require('vm');
  getStructuredStack = runInNewContext(`(function() {
      Error.prepareStackTrace = function(err, trace) {
      err.stack = trace;
      };
      Error.stackTraceLimit = Infinity;
      return function structuredStack() {
      return new Error().stack;
      };
  })()`, {}, { filename: 'structured-stack' });

  const stack = getStructuredStack();
```
To test this i have made a small test project:
[nwjs-crash-test01.zip](https://github.com/nwjs/nw.js/files/3301201/nwjs-crash-test01.zip)
Unzip it and run:
`npm install`
#### Linux
To run with NW.js:
`./node_modules/nw-builder/bin/nwbuild -r .`
To run with node:
`node src/main.js`
#### Windows
To run with NW.js:
`node  .\node_modules\nw-builder\bin\nwbuild -r .`
To run with node:
`node  .\src\main.js`

The test program will run the same 4 test with NW.js or node

1. In parent process call a node method, to verify that node is working.
2. In parent process call `runInNewContext`
3. In child process call `runInNewContext`
4. In child process call `const buf = new Buffer([0x62, 0x75, 0x66, 0x66, 0x65, 0x72])`

The last test is because that is actually the blocking problem i have,
When calling a deprecated method in node buffer it will eventual call `runInNewContext` and crash.

When running the NW.js version of the test it will open the developer tool and print the faulr output from the child process to the console.
To run all 4 test cases press the "run code" button 6 times.

**Comment by TheJaredWilcurt** [comment]
@ermod 

I don't know what I did, but I fixed it? I pulled down your example, ran it and saw the issue (in Windows 10).

I was going to try to simplify the code to make a smaller min-repro for Roger.

First thing I did was change the package.json, then I ran a linter on it, and then it just worked? So I assume you had some error in your code that was causing it. 🤷 

Here's the working version:

* [nw7085-tjw.zip](https://github.com/nwjs/nw.js/files/3303876/nw7085-tjw.zip)

If so, you can close this issue.

**Comment by ermod** [comment]
Unfortunately you had introduced a small error in child.js, 
that caused the the problem code not to be executed.
Row 27 in child.js needs to be changed.
From:
`start(test);`
To:
`start(message.test);`

**Comment by TheJaredWilcurt** [comment]
@ermod you are correct, fixing that line in my version caused the error to continue.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
please try this build: https://dl.nwjs.io/live-build/nw39/06-27-2019/fc29255fc/v0.39.2/

**Comment by ermod** [comment]
The fix works perfectly.
Thanks fore the speedy fix.

**Comment by ermod** [comment]
On a side note, I noticed that this code:
```
Error.prepareStackTrace = function(err, trace) {
  err.stack = trace;
 };
 Error.stackTraceLimit = Infinity;
 const stack = new Error().stack;
```
That produces a stack dump on NW.js 0.38.4
Do not do so on NW.js 0.39.0 and later.
Should I write a ticket for this fault?

**Comment by rogerwang** [comment]
sure
