### ISSUE TITLE
webview.addContentScripts cause TypeError: Illegal invocation

### ISSUE THREAD

**Issue by huwei765** [nwjs/nw.js#7087]
NWJS Version :v0.38.3
Operating System :window

### Expected behavior

no TypeError

### Actual behavior

an error "unCaught TypeError:Illegal invocation" displayed in the console panel
`Uncaught TypeError: Illegal invocation
    at Object.define (extensions::safeMethods:20:22)
    at extensions::guestViewContainerElement:68:28
    at registerInternalElement (extensions::guestViewContainerElement:37:28)
    at listener (extensions::guestViewContainerElement:27:5)`

### How to reproduce
the content in the index.html is,
`<script>
            window.onload = function(){
                var _webview = document.createElement("webview");
                _webview.setAttribute("partition", "trusted");
                var e = document.getElementById("foo");
                e.appendChild(_webview);
                _webview.addContentScripts([{
                    name: "contentscript",
                    matches: ["https://www.baidu.com/*"],
                    js: {files: ["build/contentScript2.js"]},
                    run_at: "document_start"
                }]);
                _webview.src = "https://www.baidu.com/";
            }
        </script>`

**Comment by Colir** [comment]
+1

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by panther7** [comment]
+1

**Comment by panther7** [comment]
Try this mini-browser and look into webview console...

[mini-browser.zip](https://github.com/nwjs/nw.js/files/4186822/mini-browser.zip)

@rogerwang

**Comment by mregiste** [comment]
I'm getting the same error, can we ignore these or are these meaningful errors that need to be fixed? I switched from iFrames to webviews as there are unresolved issues with iFrames and was hoping webviews were the answer, not sure at this point.

**Comment by mkazlauskas** [comment]
@rogerwang I have the same question as @mregiste - do we have an idea what exactly is not working here?

**Comment by mkazlauskas** [comment]
I don't know if it's related, but I noticed that inside content script `chrome.runtime.sendMessage` works, but       `chrome.runtime.onMessage.addListener` doesn't: sending message using `chrome.runtime.sendMessage` from main window doesn't get there. I'm not sure if that's expected behavior or not though. Could be that you need to send message through chrome.tabs or sth.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by panther7** [comment]
Finally, only one year, but thank you.
