### ISSUE TITLE
mac build nwjs unknown target nwjs

### ISSUE THREAD

**Issue by landongyuan** [nwjs/nw.js#7089]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :nw38
Operating System :mac 

### Actual behavior
ninja -C out/nw nwjs
ninja: Entering directory `out/nw'
ninja: error: unknown target 'nwjs', did you mean 'nasm'?

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by TheJaredWilcurt** [comment]
If this is for building `ffmpeg` for codecs

1. You can use the [prebuilt ones](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases)
1. You can reference this past issue, which may have useful information:
   * https://github.com/nwjs/nw.js/issues/5571

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
