### ISSUE TITLE
Can't Remove NWJS Icon in Notifications API

### ISSUE THREAD

**Issue by npaul007** [nwjs/nw.js#7093]
Hey guys,

On MacOS when using the native Notifications API I'm having trouble getting rid of the NWJS Icon that's to the left of each notification.

What's weird is the icon I set for my nw executable shows my personal icon just fine when I moved the .icns file to replace "app.icns" and "document.icns". with my.app/Contents/Resources.

I'm on 0.29.4 atm.

Here's my code snippet:
`new Notification("My app",{icon:"./myapp.png",body:"foobar"})`

Your help is much appreciated.

**Comment by Jakovb** [comment]
It should work,
Only thing that you could check is adding empty string on body.
`new Notification("My app", {icon: "./myapp.png", body: ""})
`
Second suggestion would be to update to 35 +. I recall having some issues on >30.

Good luck.

**Comment by npaul007** [comment]
@Jakovb  , atm I'm hesitant to update nwjs as this project is a production app and would require a lot of resources on my end to retest after updating.

Has anyone found other ways to sort this out?

**Comment by Jakovb** [comment]
@npaul007 I understand the problems with updating. However just for your case you should consider trying to see if its nwjs problem. 

Have you tried setting body string to emptry ("") in new Notificaton args?

**Comment by npaul007** [comment]
@Jakovb , I will give updating a try in a secluded environment for the sake of testing though it's not preferable.

I did however try the empty body string and the nwjs Icon still appeared.

**Comment by Jakovb** [comment]
Sorry that I can't be of more help. I'll try recalling but looking at my code now, only difference you and me have is nwjs version.
