### ISSUE TITLE
node-main is not working in Mac only

### ISSUE THREAD

**Issue by premalatha-bv** [nwjs/nw.js#7094]
node-main is not working in Mac machine, the node server is not starting.

**NWJS Version** : 0.39.0
**Operating System** : Mac or windows 10

**Expected behavior**

Text written to console or error thrown by nw.js
Windows opens
When window is closed, the process continues running

**Actual behavior**

Nothing written in console
Window opens
When window is closed the process terminates

**How to reproduce**

Create these 3 files:

package.json
{ "name": "node-main_issue", "node-main": "main.js", "main": "index.html" }

main.js
(function(){ console.log("node-main test"); })()

index.html
<h1>App</h1>

This is a minimal example of the issue, I also tried introducing programming errors into the main.js. It does not matter what I put in the main.js, it does not get loaded.

**Comment by premalatha-bv** [comment]
My wrong coding..

**Comment by premalatha-bv** [comment]
node server is not started, though the js file in node-main is executed.

**Comment by xujialiang** [comment]
when to fix it?

**Comment by premalatha-bv** [comment]
Closing as this is working as expected.

**Comment by xujialiang** [comment]
> Closing as this is working as expected.

I write console.log in main.js , but not work, how to run it?
