### ISSUE TITLE
How to use webrtc under nwjs and codec with H264?

### ISSUE THREAD

**Issue by landongyuan** [nwjs/nw.js#7095]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :38
Operating System :mac

### Expected behavior

How to use webrtc under nwjs and codec with H264?
but now， It‘s always VP8.
I want using webrtc witch H264 encoding on nwjs;How can I do?

### Actual behavior

<!- What actually happens? ->

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
