### ISSUE TITLE
webview.showDevtools,when hit on breakpoint, the devtools can not be operated

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7098]
NWJS Version : 0.39.2
Operating System : Win & MacOS

### Expected behavior

devtools can be operated;

### Actual behavior

when hit on breakpoint, the devtools can not be operated;
0.37.4 is ok

### How to reproduce

[devtools.zip](https://github.com/nwjs/nw.js/files/3345429/devtools.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
