### ISSUE TITLE
Random crashes 

### ISSUE THREAD

**Issue by betsonserviceportal** [nwjs/nw.js#7101]
NWJS Version : 
Our users are on v 34
I've been moving up with releases.  Until last night I was on v 39
I've now installed v 40 beta and have not crashed yet

Operating System : Windows 10 Pro

We have an existing ExtJS browser application which we've wrapped inside of an NWJS window.  We don't do anything fancy with NWJS.  
- use it to control the window.  
- open the window when user logs in we open our NWJS window and do window.location.href to our Intranet url.  
- override the close event and create a system tray object.  
- use the 'webview' instead of 'iframe' when opening PDFs in the NW window vs browser.

Much of the crashing I find going on is related to the creation of PDFs.  We use jsPDF and jsPDF-AutoTable to create PDFs on the fly.  We open a window with 'webview' to show the PDF.  I saw an old topic where a user had similar issues with jsPDF and they resolved it with the single instance flags, but I believe this is switch on by default.

We also have users who report their NW window has disappeared.  It was launched in the morning.  They minimized or sent it to the tray.  And at some point during the day they go back to use it and it's gone.  No where to be found.

I know these are very vague with no steps to recreate and involve an ExtJS framework and jsPDF library.

All that said, I installed v40 beta last night and have not crashed since.  Was anything put into v 40 which might deal with 'webview' or the handling of exceptions?

Side note, my debug text file is full of this same message over and over:
[0703/094845.219:ERROR:crash_report_database_win.cc(469)] failed to stat report

**Comment by rogerwang** [comment]
Could you please 
Could you please provide a sample to reproduce or the [crash dump](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/) file?

**Comment by betsonserviceportal** [comment]
Roger, since installing v40 beta, I haven't had a crash.  Another user reported to me things seem more stable.  I'll get you a crash dump if it starts to happen again.

**Comment by betsonserviceportal** [comment]
I did find a few old .DMP files.  These probably were the last to happen before my upgrade.
[NWJS_dumps.zip](https://github.com/nwjs/nw.js/files/3374881/NWJS_dumps.zip)

**Comment by garagusopdfs** [comment]
I'm experimenting random crashes on 0.40 as well, in both, the SDK and Normal version. The system was working fine with 0.34.5, but after the upgrade (of several apps), now I get random crashes.
