### ISSUE TITLE
Memory leaks dom elements [SDK Stable v0.39.2]

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#7103]
open nwjs sdk [SDK Stable v0.39.2>], and add this. 
You will see infinite grow nodes.
If you attache dom listener, they will also never removed.
```js
var i = 0;
var a = setInterval(function(){

      const div = document.createElement("div");
      document.body.appendChild(div);
      document.body.removeChild(div)
      console.log(i)
i++>200 && clearInterval(a)

      }, 30);
```
![_SDKnwjsleaks_bug](https://user-images.githubusercontent.com/24865815/60693389-16756f00-9ea8-11e9-9891-cff5c85fbb42.gif)

try this in codepen,jsfiddle , no memory leaks !.
https://jsfiddle.net/6ardwop7/7/

It a big issue! no? my app get very slow after x time i create element with dat-gui.

this video shows the extent of the problem.
https://youtu.be/6avCHNGXZLE

**Comment by alessandrofrancesconi** [comment]
I confirm the issue it is still present in 0.45.3 and it is an **HUGE** issue.

My app constantly refreshes parts of the DOM using jQuery's `append()` and `empty()`. I had very hard times last days searching for a reason of this memory issue... now I've found this thread and I've finally discovered that it was introduced in 0.39.2 (prior versions works fine instead):

In 0.39.1 (last working version):

![39](https://user-images.githubusercontent.com/1595223/79689482-741b5200-8255-11ea-832d-82a3cfd055ba.PNG)

This is what happens by just switching to 0.39.2, confirmed also in latest 0.45.3:

![Capture](https://user-images.githubusercontent.com/1595223/79689567-fd328900-8255-11ea-9d32-44239bd9fa0e.PNG)

So we are forced to stick with 0.39.1, our app must work 24h without any memory issue (it is a system monitor). Please work on this soon!

Thanks @djmisterjon for reporting it!!!

**Comment by rogerwang** [comment]
The Chrome browser has the same behavior here on OP's sample... see the video below.

However, if you close/reopen devtools, the number of DOM nodes will drop. The same happens in NW.js.

![leak](https://user-images.githubusercontent.com/165401/79691004-e0b34280-828f-11ea-9c46-5048ac041d5c.gif)

**Comment by alessandrofrancesconi** [comment]
After some tests I've found the point in time where this started to happen, at least with my code.
The last "working" release is 0.42.6, while the memory issue started in 0.43.0.

0.43 introduced Chromium 79 and Node.js v13.3.0

**Comment by alessandrofrancesconi** [comment]
@rogerwang it is not just DevTools. The entire app keeps growing in memory, even if in Release and without DevTools opened.

**Comment by rogerwang** [comment]
Could you please provide a case so I can reproduce it here?

**Comment by djmisterjon** [comment]
@alessandrofrancesconi 
I dont know if this can help, am very poor with dom html.
But on my side, like roger say,  yes reset the devTool work sometime, but also force manually GB
Sometime gb are slow to release.
![image](https://user-images.githubusercontent.com/24865815/79710335-b2833200-8292-11ea-82a0-1171b1a2baa2.png)
i Add flags "js-flags": "--expose_gc",
And than call window.gc() between a scenes or after a big loading or a (transition scenes).
This allow to fully controls and force GC where your want and avoid big major GC release at random time in your game or app (webgl).! Not tested with dom elements
![image](https://user-images.githubusercontent.com/24865815/79710490-202f5e00-8293-11ea-8bab-d1f5778ace5b.png)

**Comment by rogerwang** [comment]
NW behaves in the same way with Chrome so far. Close until more information is available.

**Comment by alessandrofrancesconi** [comment]
For my particular case, I've discovered the root cause and reported it on issue #7586
