### ISSUE TITLE
api里面有允许调整窗口大小的监控吗？

### ISSUE THREAD

**Issue by yc825106632** [nwjs/nw.js#7105]
我想在windows的窗口里面定义好html标签的高度，窗口的Resizable属性设置为true，在任意调整窗口大小的时候，发现html标签的高度不会随着窗口的高度发生变化，找遍了很多文档始终没有发现窗口调整开始时，调整中，调整后尺寸的变化API，有人遇到过相应的问题吗？你们是怎么解决的？

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
