### ISSUE TITLE
nwjs crushes when navigate on kayak.com

### ISSUE THREAD

**Issue by dansachelarie** [nwjs/nw.js#7106]
NWJS Version : 0.39.2 (same applies for older versions)
Operating System : Widnows/Linux

### Expected behavior

I have an webview where I put https://www.kayak.ie. Try to do a serch and it will just show the results of it inside the second webview. 

### Actual behavior

Nwjs crashes.

### How to reproduce

Use the following code on index.html:

<webview src="https://www.kayak.ie/?ispredir=true" id="first"></webview>
<webview id="second" style='display:none'></webview>

<script>
    first.addEventListener('newwindow',(e)=>{
        first.style.display='none';
        second.style.display='block';
        second.src = e.targetUrl;
    })
</script>

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by dansachelarie** [comment]
Add following code to index.html:

```<webview src="https://www.kayak.ie/?ispredir=true" id="first"></webview>
<webview id="second" style='display:none'></webview>

<script>
    first.addEventListener('newwindow',(e)=>{
        first.style.display='none';
        second.style.display='block';
        second.src = e.targetUrl;
    })
</script>```

**Comment by asteriosgr** [comment]
I can reproduce. This is my stderr logging before the crash:
FATAL:render_frame_host_manager.cc(1991)] Check failed: frame_tree_node_->IsMainFrame().
