### ISSUE TITLE
Window popup crash

### ISSUE THREAD

**Issue by ncannasse** [nwjs/nw.js#7108]
NWJS Version : 0.38.4 and 0.39.2
Operating System : Win10 64bit

When opening window popup menus, sometimes the application will just close without any notice. It is not 100% reproducible so might be GC-related.

It seems to happen more often when using sub menus.

**Comment by rogerwang** [comment]
Could you please provide a sample to reproduce or the [crash dump](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/) file?
