### ISSUE TITLE
Multiple nwjs.exe apps

### ISSUE THREAD

**Issue by ncannasse** [nwjs/nw.js#7110]
We have two NWJS apps, however when one is opened the other one cannot open, it will instead focus the currently opened app. Renaming the exe or changing the app icon using rcedit does not work.

So far it seems only using different NWJS versions works, but that's far from ideal.

Any advice?

**Comment by ncannasse** [comment]
Actually, this only occur when having the same name in package.json application.

**Comment by bmatusiak** [comment]
change the "name" key in package.json

**Comment by xueqino1** [comment]
another way is to run app with args "--user-data-dir="

**Comment by rogerwang** [comment]
different `name` field should be used, as it serves as the identity of the app.
