### ISSUE TITLE
Building NW.js

### ISSUE THREAD

**Issue by rgl** [nwjs/nw.js#7111]
I'm trying to automate a build of nw.js with custom settings and on the documentation at http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/ there's this paragraph:

> See our buildbot for official build configuration and steps: http://buildbot-master.nwjs.io:8010/waterfall

But how do I see the source of the waterfall job (e.g. of http://buildbot-master.nwjs.io:8010/builders/nw39_win64)? Is that on some other git repository?

This information would be nice to have on the Building NW.js page :-)

**Comment by rogerwang** [comment]
The document means you could see the commands it executes in each step, and the environment variables. Just click `stdio` link of each steps. The buildbot configuration is not open sourced.

And please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
