### ISSUE TITLE
new nw.shortcut not work

### ISSUE THREAD

**Issue by xueqino1** [nwjs/nw.js#7112]
NWJS Version :nwjs-sdk-v0.39.2-win-x64
Operating System :windows 10
it seems that the shortcut construct method has been changed,when I create a shortcut ,i got an error "Uncaught TypeError: nw.Shortcut is not a constructor"

`nw.App.registerGlobalHotKey(new nw.Shortcut({
	    key: 'ctrl+alt+a',
	    active: function() {
			console.log('clicked')
	    },
	    failed:  function(e){
	    	console.log('regist global key faild')
	    }
	}));`
### Expected behavior
create a shortcut without error
### Actual behavior
failed to create a shortcut

btw: it works fine in nwjs-sdk-v0.30.5-win-x64 .

**Comment by cyantree** [comment]
Can confirm this too for `0.39.3`. It seems to work in `0.38.4` so maybe it's related to the api rework mentioned in https://nwjs.io/blog/v0.39.0/ ?

**Comment by marc7000** [comment]
I have the same issue with `0.39.2` & `0.39.3` platform win64 & osx64.
With version `0.38.4` everything works fine.

![nw Shortcut-is-not-a-constructor-win64](https://user-images.githubusercontent.com/1118837/61439084-2c237380-a941-11e9-8724-194bc6b90ab4.png)
![nw Shortcut-is-not-a-constructor-osx64](https://user-images.githubusercontent.com/1118837/61439085-2c237380-a941-11e9-882a-5bd8a3a9bf0a.png)

**Comment by jobeninc** [comment]
This also affects me.  It works in 0.34.5 but not in 0.39.3.

**Comment by jobeninc** [comment]
From browsing through the code changes it appears that the Shortcut feature has been bound to the Chromium key accelerators in v0.39.0. 
- Is this expected to be a permanent change?  
- Can you post an example of how to use it with the new registerAccelerator/unregisterAccelerator functions rather than the API that is documented in the NW documentation? 

Thanks,

**Comment by rowenbuzz** [comment]
@rogerwang Our application uses 30+ shortcuts and is at the core of the efficiency, usability, and functionality of our application.  We are currently trying to upgrade to 0.39.3 or higher this week but now we cannot until this is resolved as it breaks our app.  Any update, fix or recommendations you could provide on this issue would be greatly appreciated.  Thank you in advance as always.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
