### ISSUE TITLE
window.moveTo(x, y) resizes window when global UI scaling is > 100% (Windows 10)

### ISSUE THREAD

**Issue by Luzzifus** [nwjs/nw.js#7113]
NWJS Version: 0.39.2 (and also earlier versions), 0.40.0 beta1
Operating System: Windows 10

### Expected behavior

`window.moveTo(x, y)` moves the window to the designated screen position with no side effects.

### Actual behavior

When the global UI scaling of Windows 10 is set to something bigger than 100%, `window.moveTo(x, y)` also resizes the window. It becomes bigger each call.

### How to reproduce

I wrote a few lines of code which makes it possible to move the nw.js window by dragging a handle element. During dragging, the described behavior occurs.

Fully functional example code:

[moveTo_bug.zip](https://github.com/nwjs/nw.js/files/3393086/moveTo_bug.zip)

**Comment by Luzzifus** [comment]
Another observation:

Even at default Windows UI scaling (100%), moving the window via `.moveTo` will resize it, if the size is below a certain threshold. For me that is 64px. If the window has a height of 64px or below before `.moveTo`, `.moveTo` will decrease the height with each call until it hits zero. Changes below `min_height` are not visible, but are still reported by the window resize event. 

Also, contrary to the initial bug behaviour, this can't even be prevented by setting `win.setResizable(false)` while moving the window. The only option I have seems to be to record the size on drag start and reapplying it after drag end.

Btw. any kind reaction would be appreciated.

**Comment by Luzzifus** [comment]
@rogerwang 
This issue still persists, is reproducible across multiple PCs for me and is even more pronounced with nw2, so I'll reference this to #7230 . Before nw2, I was compensating this by setting the window to non-resizable during dragging, but with nw2 this has no effect anymore. I use it to implement a custom app title bar with window dragging functionality. This has now become an app breaking issue for me. Another minimal demonstration code example is attached, as well as a gif of the behaviour.

![dragTest](https://user-images.githubusercontent.com/431996/71640607-5ff31b00-2c8d-11ea-8779-a674a0501de0.gif)
[dragTest.zip](https://github.com/nwjs/nw.js/files/4013982/dragTest.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200107-162000/36d4d26c4
