### ISSUE TITLE
0.38.0以上无法在win7家庭版中启动，启动为黑屏

### ISSUE THREAD

**Issue by hotbinz** [nwjs/nw.js#7115]
操作系统：windows7 家庭版
nwjs版本：0.38.4_x86
问题描述：双击打开nw.exe，屏幕一直黑屏，无响应，已经在多台电脑验证(不管是32位还是64位都有此问题)，win10无此问题

**Comment by rogerwang** [comment]
Please use English in this project so all users can read.
