### ISSUE TITLE
 Nwjs v0.38 or higher is not available in win7 Home Edition

### ISSUE THREAD

**Issue by hotbinz** [nwjs/nw.js#7116]
Nwjs v0.38 or higher is not available in win7 Home Edition
OS: WIN7 Home Edition (x86 or x64)
Nwjs version: v0.38.4
Problem Description: Download nwjs v0.38.4 does not write any code to run directly, the interface displays a black screen, can not respond. 
v0.37 no such problem.

**Comment by Eason-Wu** [comment]
ERROR:registration_protocol_win.cc(56)

**Comment by aleafworld** [comment]
me too.(in some win7 ultimate edition)
and the default file name setting for nwsaveas dialog is missing in v0.37.
so I'm still using v0.36
:(

**Comment by panther7** [comment]
I tried NWjs 0.38.4 on clean installed Windows 7 Home Premium (x64) and works.

**Comment by bluthen** [comment]
Not sure if helpful in this case, but often black screens indicate an issue with video driver. You can also try disabling acceleration using command line switches in  your package.json `"chromium-args": "--disable-gpu"`  maybe that would help.

**Comment by hotbinz** [comment]
> 
> 
> Not sure if helpful in this case, but often black screens indicate an issue with video driver. You can also try disabling acceleration using command line switches in your package.json `"chromium-args": "--disable-gpu"` maybe that would help.

Have paid for the trial, so it really works.
thank you so much
Maybe update >v0.38 in chromium Existing problems

**Comment by Eason-Wu** [comment]
I have tried in WIN7 X64 & X32 homeBasic/Professional edtion, with Compatibility mode lower level such as [ VISTARTM, VISTASP2 ... ], not WIN7RTM, it works .
