### ISSUE TITLE
File dialog with nwdirectory & multiple attributes

### ISSUE THREAD

**Issue by daiyam** [nwjs/nw.js#712]
Hi,

I would like to be able to select multiples directories or files. The attributes "nwdirectory" and "multiple" work well individually. Together, only the attribute "nwdirectory" works.

I understand that nwdirectory & multiple could have several meanings:
- select only directories
- select directories or/and files

To separate both cases, maybe we could rename nwdirectory as nwtype="directory".
So for the case "select only directories", we could have: nwtype="directory" multiple
And for "select directories or/and files":  nwtype="directory,file" multiple

Thx
##

**Comment by gunta** [comment]
+1

**Comment by xixixao** [comment]
+1, on Mac it is normal to be able to select either directory or file, using the same dialog. Folks over at Electron do it.

**Comment by skunath** [comment]
+1
