### ISSUE TITLE
new-win-policy event handler not getting called

### ISSUE THREAD

**Issue by kumarasinghe** [nwjs/nw.js#7121]
NWJS Version : 0.39.0
Operating System : Windows 7, 10

Following is not working:

```
nw.Window.open('http://ww.github.com/', {}, (nwWindow) => {
    nwWindow.on('new-win-policy', function (frame, url, policy) {
       // Never get called
     })
}
```

**Comment by hrocha1** [comment]
possibly related to #7125? can you try the same thing with local file?

**Comment by rogerwang** [comment]
yes, this is duplicate of #7125, which was just fixed in git.
