### ISSUE TITLE
Blank windows with chromium-args (in-process-gpu)

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#7122]
NWJS Version : 0.39.3 32/64 bit (Windows normal/sdk) and nwjs-v0.40.0-beta1-win-x64 (normal/sdk)

Operating System : Windows 10 32/64 bit

### Expected behavior
The application (nw.exe) should start normally like my older version 0.30.5 (I need an NW update because I need add vibration for the gamepad for some players :D). 

### Actual behavior

Using "chromium-args": "--in-process-gpu", in package.json will cause windows (including DevTools - chrome-error://chromewebdata/) to be "blank/black". 

**Screenshot:** https://pasteboard.co/IqdsHOx.png

It works when I remove "--in-process-gpu", but I have low fps on some devices (low-end).

### How to reproduce

This is my package.json. You can try load credits.html, for me windows is black/blank like on the screenshot. I can drag credits.html (or game files) to nwjs window (nw.exe) and then it works...
```
{
	"main": "credits.html",
	"chromium-args": "--in-process-gpu --disable-transparency",
	"version": "1.37.51",
	"window": {
		"toolbar": false,
		"fullscreen": true,
		"width": 900,
		"height": 510,
		"resizable": true
	},
	"webkit": {
		"plugin": false,
		"page-cache": false
	}
}

```

Similar post (but on the Mac OS): https://github.com/nwjs/nw.js/issues/5741

PS. I will check later Mac OS / Linux.

**Comment by hooker99** [comment]
I will check later Mac OS / Linux.

**Comment by hooker99** [comment]
I checked all versions of nwjs. After 0.33.4 you can not use "chromium-args": "--in-process-gpu".

But nwjs 0.33.4 has vibrations (Gamepad API) and my game with --in-process-gpu works faster on low-end devices. I will check later Mac OS / Linux.

**Comment by hooker99** [comment]
So Linux (Ubuntu) and MacOS (High Sierra 10.13.6) also have blank windows when using "chromium-args": "--in-process-gpu". I also tested again on Windows on 5 computers (various configurations: nvidia, amd etc.). I used nwjs-v0.40.0 (latest version from nightly builds) for Windows / Linux / Mac).

I tried to use version 0.32.0, because it works fine for me on Windows... but on Linux all graphics are glitched (pinky) 💃 .

There is any chance to fix it @rogerwang ? If not I will use diffrents NWJS version for Linux/Windows/MacOS. Please, let me know. Thanks.

**Comment by ol-web** [comment]
I had the same problem on win10 (didn't check other systems). My devtools window was blank, my main window was simply transparent with shadow around it. It was still usable, everything seemed to work fine by navigating through it blindly but it just didn't render any of the windows. Downgraded to 33.3 and it works perfectly now.

Maybe it's gpu/driver related? Mine is AMD R9 290x with drivers: 18.50.21.01-190212a-339148E-RadeonSoftwareAdrenalin2019

**Comment by Langerz82** [comment]
Same problem. The only solution was to downgrade to 33.3. If someone fixes it in a new revision please let us know here so we can update, Cheers. I might take a look at this issue myself if I get some spare time, I am trying to publish a game and my time is very very limited.
