### ISSUE TITLE
Bad text in menubar

### ISSUE THREAD

**Issue by Dimtime** [nwjs/nw.js#7124]
Update to nw40 and get this:
![SharedScreenshot](https://user-images.githubusercontent.com/16452588/62263398-ba5d2680-b424-11e9-88f7-c4f09f219c2e.jpg)
Maybe only i have it...  Code for repeat simple:
```
var menu = new nw.Menu({type: 'menubar'});
var menu_test = new nw.MenuItem({ label: 'test' });
menu.append(menu_test);
nw.Window.get().menu = menu;
```

**Comment by rogerwang** [comment]
Thanks for reporting. 
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
