### ISSUE TITLE
some Window events won't fire if you open remote url

### ISSUE THREAD

**Issue by hrocha1** [nwjs/nw.js#7125]
NWJS Version : nwjs-sdk-v0.40.0-win-x64
Operating System : Windows 7

### Expected behavior

Events like resize, move or loaded of Window should be emitted on all windows every time the event happens.

### Actual behavior

Events are emitted only in window with local file (like test.html). Events aren't emitted if you open remote url (like http://example.com). 

### How to reproduce

**main.js**

```
nw.Window.open('test.html', {}, function(win) {
	win.on("resize", function(w, h) {
		win.window.console.log("w, h",  w, h);
	});
});


nw.Window.open('http://example.com', {}, function(win) {
	win.on("resize", function(w, h) {
		win.window.console.log("w, h",  w, h);
	});
});
```

**test.html**

```
test
```

**package.json**

```
{
  "name": "eventstest",
  "main": "main.js"
}
```

The Window with test.html emits the resize event every time you resize it. The Window with http://example.com doesn't. Same behavior can be observed with some other events.

For example the loaded event was working fire in version nwjs-sdk-v0.37.4-win-ia32, but it's emitted only sometimes in windows with remote url and nwjs-sdk-v0.40.0-win-x64.

**Comment by rogerwang** [comment]
Thanks for reporting. 
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by hrocha1** [comment]
> Thanks for reporting.
> This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).


Seems like it's working, but navigation can break it again. For example if you load http://example.com it's working. Then if you click on "More information..." it stops working. Then if click on some random link there it starts working again. If you do similar thing locally and navigate over few local files it always works.

Tested with http://dl.nwjs.io/live-build/nw40/08-03-2019/e23c27266/v0.40.1/nwjs-sdk-v0.40.1-win-x64.zip on Windows 7 and Windows 10.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by hrocha1** [comment]
Thanks! This one looks much better, so far it has been working as expected. Events are firing and Window properties are being updated. I will be using nightly builds on my dev machine for some time and report back if there is any issue.

**Comment by hrocha1** [comment]
Looks like there is still some deep-rooted issue with Window and navigation. I managed to find yet another case when events stops firing.

If you change the test.html from the original example to

```
<a href="http://www.iana.org">http://www.iana.org</a>
<a href="https://www.iana.org">https://www.iana.org</a>

```

and then start the NW.js everything is working, events are firing. If you click on the first link it's still working. However if you do the same, but use the second link the events stop firing. I'm not sure what's the reason behind this. It's probably not the http x https difference, because I managed to find http sites that behave the same (for example http://htmltetris.com). It's also strange that events work normally if you open them directly via nw.Window.open, it's the navigation that breaks it.

**Comment by JL102** [comment]
After investigating an unrelated issue (#6859 ), it appears that focus/blur events fire correctly on version 0.33.4: https://dl.nwjs.io/v0.33.4/nwjs-sdk-v0.33.4-win-x64.zip
Unfortunately, minimize/restore events do not seem to fire correctly on that version....

**Comment by hrocha1** [comment]
I've spend some time testing this issue on more recent versions and these are my results


| version  | status |
| ------------- | ------------- |
| nwjs-sdk-v0.41.3-win-ia32  | NOT WORKING  |
| nwjs-sdk-v0.42.6-win-ia32  | OK  |
| nwjs-sdk-v0.43.3-win-ia32  | OK  |
| nwjs-sdk-v0.44.0-beta1-win-ia32  | NOT WORKING  |

Tested with resize, move and loaded events. Both with and without the "--disable-features=nw2" switch where applicable (not sure if that's relevant).

**Comment by rogerwang** [comment]
Please try this latest v0.44 build https://dl.nwjs.io/live-build/nw44/20200105-101210/87f3a0d70 
It works for me. @hrocha1

**Comment by hrocha1** [comment]
@rogerwang It doesn't work for me (tested on Windows 7 and Windows 10 1903). The current problem is that events work if you open local file or remote url, but once you navigate to remote url (click on a link, for example https://www.iana.org) it stops working.

These are my test files

[issue.zip](https://github.com/nwjs/nw.js/files/4025536/issue.zip)

**Comment by rogerwang** [comment]
@hrocha1 I was testing the same scenario. I think in your sample, the events are working, but your `win.window.console.log` would not work because it's pointing to an invalid `window` object after navigation... the DOM window object is supposed to be destroyed upon navigation.

**Comment by hrocha1** [comment]
@RobertLowe Well that's interesting. I was under impression that the window property is resolved at runtime from the win object, but maybe that's some fundamental misunderstanding of how JavaScript works. Anyway I got to this point because this has been working for me in previous NW.js version, but currently it's not. If this is wrong approach I can rewrite this part of my application, but I'm not sure what would be the correct way to do it.

**Comment by RobertLowe** [comment]
Well, hello @hrocha1

**Comment by rogerwang** [comment]
@hrocha1 I suggest rule this out for now by using other ways of logging to make sure the events are fired. You can file another issue for referring the window object.

**Comment by hrocha1** [comment]
@rogerwang Good job! That was it. 

The problem in the last version is different. Events work, but there is a problem with accessing the  `win.window` object. In versions v0.42.6 or v0.43.3 the `win.window` property returns new/correct instance of DOM `window` object after every navigation. In the latest v0.44 build it's `undefined` after first navigation.

**Comment by rogerwang** [comment]
Good to know that. Closing this issue for now and please file a new one of the window object issue.

**Comment by hrocha1** [comment]
@rogerwang 

It looks like that there are still some issues with the "close" event on windows with remote url. I'm having a problem receiving the "close" event under the NW2 mode (it works if I use --disable-features=nw2).

The breaking point is the 0.42.4 version where the NW2 mode has been introduced. Should I create a new issue for this problem?

Files to reproduce this issue:

[issue9.zip](https://github.com/nwjs/nw.js/files/4298366/issue9.zip)

closing both windows should produce a message in the log.txt, but it only does for the local file
