### ISSUE TITLE
Error: QuotaExceededError: DOM Exception 22

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#7126]
When using node-webkit (linux 64bit 0.40.0 sdk) to run an application that relies heavily on localStorage I get:

Error: QuotaExceededError: DOM Exception 22

Everything I've seen regarding this on node-webkit suggests that localStorage is expected to default to unlimited (as in however much available disk space there is), but the hard drive is far from full and I'm getting this error - the dataset is a little over 6MB.

I was sure the limit was  removed for localStorage.

**Comment by rogerwang** [comment]
Could you please provide a full sample so I can reproduce? Thanks.

**Comment by hooker99** [comment]
I didn't see you answer. I sent you also e-mail, because my game uses localStorage... My next games are already using indexeddb. I hope you will help me.

Please run this example NWJS you can storage only 5200000 characters (localStorage 5 MB limit):

`<div id="results"></div>
<script>
var iterationsData;
var results = document.getElementById('results');

(function () {

if (!('localStorage' in window)) {
    results.innerHTML = 'Your browser has no localStorage support.';
    return;
}

var n10b =    '0123456789';
var n100b =   repeat(n10b, 10);
var n1kib =   repeat(n100b, 10);
var n10kib =  repeat(n1kib, 10);
var n100kib = repeat(n10kib, 10);
var n1mib =   repeat(n100kib, 10);
var n10mib =  repeat(n1mib, 10);

var values = [n10b, n100b, n1kib, n10kib, n100kib, n1mib, n10mib];

iterationsData = [];
for (var majorIndex = 1; majorIndex < values.length; majorIndex++) {
    var major = values[majorIndex];
    var minor = values[majorIndex - 1];
    for (var i = 1; i < 10; i++) {
        for (var j = 0; j < 10; j++) {
            iterationsData.push([major, minor, i, j]);
        }
    }
}

var index = 0;
var oldLength = 0;

function iteration() {
    var data = iterationsData[index];

    major = data[0];
    minor = data[1];
    i = data[2];
    j = data[3];

    var string = repeat(major, i) + repeat(minor, j);
    var length = '' + string.length;

    if (test(string)) {
        results.innerHTML = length + ' characters were stored successfully.';
    } else {
        results.innerHTML = oldLength + ' characters were stored successfully,  but ' + length + ' weren\'t.';
        return;
    }
    oldLength = length;

    index++;
    if (index < iterationsData.length) {
        setTimeout(iteration, 0);
    } else {
        results.innerHTML = oldLength + ' characters were saved successfully, test is stopped.';
    }
}

iteration();

function test(value) {
    try {
        localStorage.test = value;
        return true;
    } catch (e) {
        return false;
    }
}

function repeat(string, count) {
    var array = [];
    while (count--) {
        array.push(string);
    }
    return array.join('');
}

})();
</script>`

NWJS, localStorage has a 5 MB limit. So, I can store only 5200000 characters. I tested on nwjs-0.43.4 64bit. Link: https://developer.chrome.com/apps/offline_storage

Thank you.

**Comment by bluthen** [comment]
does --unlimited-storage in chromium-args of your package.json help?

**Comment by hooker99** [comment]
Thank you for your response. But it doesn't work.

I think "--unlimited-storage" will work with navigator.webkitPersistentStorage ? I hope @rogerwang can help.

**Comment by hooker99** [comment]
After running the test.html file [test.zip](https://github.com/nwjs/nw.js/files/4102638/test.zip):
1) wait for the script to perform the test
2) and then press F12 (developer console)
3) type localStorage and expand (triangle)
4) Copy localStorage.test values (click button "Copy")
5) and then type localStorage.asd = (paste values), press enter
6) You will see:

Error saving setting with name: consoleHistory, value length: 10400248. Error: Failed to set the 'consoleHistory' property on 'Storage': Setting the value of 'consoleHistory' exceeded the quota.
Ten largest settings: 

Setting: 'consoleHistory', size: 5200222
Setting: 'experiments', size: 2
Setting: 'length', size: undefined
Setting: 'setItem', size: 2
Setting: 'key', size: 1
Setting: 'getItem', size: 1
Setting: 'removeItem', size: 1
Setting: 'clear', size: 0

and:

VM358:1 Uncaught DOMException: Failed to set the 'asd' property on 'Storage': Setting the value of 'asd' exceeded the quota.
    at <anonymous>:1:18
(anonymous) @ VM358:1

It looks like the limit is 10 MB

**Comment by bluthen** [comment]
Ahh yeah you are right I think that flag is for chrome.storage. Sorry.

**Comment by hooker99** [comment]
In the worst case, I will replace localStorage with indexeddb. I asking about change limit, because I don't want interfere "save game".. 20,000 people have downloaded my game. Maybe @rogerwang will help.

 Thanks for your help @bluthen .

**Comment by rogerwang** [comment]
It works for me. You'll need this setting: http://docs.nwjs.io/en/latest/References/Manifest%20Format/#dom_storage_quota

**Comment by hooker99** [comment]
Thanks you are the best!!! 
            
          
     
      
       
        Dnia 25 stycznia 2020 05:37 Roger Wang (WenRui) &lt;notifications@github.com&gt; napisał(a):
       
    
       
         It works for me. You&#39;ll need this setting:  docs.nwjs.io docs.nwjs.io

**Comment by hooker99** [comment]
It works! You are the best @rogerwang  thanks!!! 

{
	"main": "index.html",
	"name": "Your game name",
	"dom_storage_quota": 40,
}

**Comment by TomasHubelbauer** [comment]
Sorry, but could please someone share what the default local storage size is when the `dom_storage_quota` is not set? Is it the same as the browser, ~10 MB? And is there a special value for `dom_storage_quota` to make it unlimited or should I just put in the maximum numeric value? What would that be, anyway, unit32 max value of 4,294,967,295 or something else?
