### ISSUE TITLE
Can't get information from cross origin frames

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#7129]
after the last NW.js update, trying to get information from an iframe(such as title, url,etc) of a web page doesn't work anymore, and will simply throw errors like:

Uncaught TypeError: Cannot read property 'title' of null
Uncaught TypeError: Cannot read property 'window' of null
Uncaught SecurityError: Blocked a frame with origin "chrome-extension://dcabhanapgfcaciefidifkflldckmhgl" from accessing a cross-origin frame.

**Comment by elpeleq42** [comment]
still happens on 41.1(trying the exact same code on 38.4 and previous versions works fine)

**Comment by liuyi** [comment]
I resolved ths probem, like this:
1\set package.json 
"chromium-args":"--disable-web-security'" 

2\ Use window.postMessage('what your want to send","*") instead of javscript call.

That's all. It works!

**Comment by rogerwang** [comment]
This should be the same with #7173 and fixed there. Please reopen otherwise.
