### ISSUE TITLE
Focus/Blur events are not triggered

### ISSUE THREAD

**Issue by gr1los** [nwjs/nw.js#7136]
NWJS Version : 0.40.1
Operating System : Win10

### Expected behavior

Adding event listeners to both focus and blur events should call the corresponding callbacks.

### Actual behavior

The callbacks are not called. So the events are not emitted 

### How to reproduce

```javascript
const gui = require('nw.gui');

gui.Window.open('https://google.com', {
    position: 'center',
    width: 1024,
    height: 768,
    show: false,
}, (newWin) => {
    newWin.show();
    newWin.maximize(); 

    newWin.on('focus', () => {
        console.log('[EVENT] focus here');
    })

    newWin.on('blur', () => {
        console.log('[EVENT] blur here');
    })

    newWin.on('minimize', () => {
        console.log('[Event] Minimized');
    })
});
```

* The minimize event is triggered properly.

**Comment by gr1los** [comment]
Maybe related with #7125

**Comment by JL102** [comment]
After investigating an unrelated issue (#6859 ), it appears that focus/blur events fire correctly on version 0.33.4.
Unfortunately, minimize/restore events do not seem to fire correctly on that version....

**Comment by rogerwang** [comment]
Before this is fixed, you can use 'win.appWindow.contentWindow.onfocus' as workaround. Thanks.

**Comment by rogerwang** [comment]
btw, this works well under the 'nw2' mode, which will become the default. See https://github.com/nwjs/nw.js/issues/5875#issuecomment-451331857

**Comment by prominentdetail** [comment]
> Before this is fixed, you can use 'win.appWindow.contentWindow.onfocus' as workaround. Thanks.

I have this problem too and I can't get this to work. I tried the contentWindow , but it just says
Error handling response: TypeError: Cannot read property 'contentWindow' of undefined
    at chrome-extension://jdgkbifmkkkcgglljmlojibojoafmlhi/mainWin.js:59:20
    at extensions::nw.Window:728:13

**Comment by rogerwang** [comment]
@prominentdetail the workaround is not needed since NW2 mode is the default. And it appears to work well.

**Comment by prominentdetail** [comment]
@rogerwang I filed a new bug report with an attached example that will show the blur not firing on NW2.
