### ISSUE TITLE
NWJS Version : almost all

### ISSUE THREAD

**Issue by as1220as** [nwjs/nw.js#7139]
NWJS Version : almost all
Operating System :  Windows 10 64-bit

When app run pop-up prompts notice: From a higher version of nwjs.
Or Similar to prompt:User data may come from a higher version of NWJS.

Question Description:
This problem occurs in many versions, and pop-ups are prompted when the packaged application package starts.Many developers say this is due to caching issues, but personally I don't think this is the effective solution.What's more, the packages that were used normally in the early days were followed by this problem.The NWJS kernel should be independent. In practice, it is found that NWJS is affected by system Chrome browser kernel update, which may cause this problem in some cases.For example, a non-nwjs kernel version that a JavaScript script might check while doing a browser kernel check?Which developer has this problem?

**Comment by shaynem** [comment]
This is due to installing an older version of nwjs after installing a later version of nwjs.

The Data directory needs to be cleared 

C:\Users\USERNAME\AppData\Local\APPNAME
