### ISSUE TITLE
chokidar and NW.js: NW.js hangs if you start watching files with chokidar immediatley

### ISSUE THREAD

**Issue by raguay** [nwjs/nw.js#7140]
NWJS Version : 40.1
Operating System : macOS 10.14.6

### Expected behavior
I should be able to setup my watch files as part of booting the program using NW.js. I have a Svelte application for doing a notepad/todo list. After loading the todo list, I set watches on the todo files (they are NotePlan and TaskPaper files) for changes. It should just work to set up the watches for file changes.

### Actual behavior

NW.js loads until I start watching files for changes using the chokidar library for Node.js. When it starts watching files, then the render process hangs (I assume since I can't get a single DOM instance or console output on the DevTools). When you bring up the devtools, it show nothing at all in it about the webpage. Just the menu entries. Even when I see most of my programs interface (the clipboard icon for the todo list which is being watched doesn't show up), it just hangs. I have to kill it (main nwjs and the two helper programs) and restart it two to three times before it works. It is never completely consistent, but it does hang at least the first try about 90% of the time.

I changed the program to start watching 1 minute after loading using setTimeout() function. Now it loads every single time without any further issues.

### How to reproduce

Use the chokidar library to watch some files while being loaded. It should hang. If you just load the library, it works fine. So, in the boot-up sequence while it is still setting up the display, load and watch files using chokidar.

Since I'm using Svelte to manage the interface, it could be something about the heavy writing to the DOM since it is loaded by JavaScript and not HTML.

**Comment by rogerwang** [comment]
Could you please provide a full sample so I can reproduce? Thanks.
