### ISSUE TITLE
Cannot build node gyp module for nwjs 0.39+

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7145]
Hi, from Nwjs version 0.39 we can't builds sqlite3. This is critical stopper for releasing newer NWjs.

Issues:
* https://github.com/nwjs/nw-gyp/issues/130
* https://github.com/mapbox/node-sqlite3/issues/1179

**Comment by panther7** [comment]
^ @rogerwang

**Comment by rogerwang** [comment]
This should share the same root cause with #7104

**Comment by panther7** [comment]
Hm, and any progress fix this issue?

This is really stopper for use new nwjs with sqlite

**Comment by gpetrov** [comment]
any progress @rogerwang ? We would really like to build or native node modules in NWJS 0.40+ - but are stuck now in 0.38 because of this problem

**Comment by panther7** [comment]
I think, some progress: https://github.com/nwjs/v8/commit/bf62c4681425c89225fbc5216bc1bf1a42485adc ?

**Comment by rogerwang** [comment]
Fixed in #7104

**Comment by gpetrov** [comment]
@rogerwang is this something we can also integrate? As compiled node modules are really fat now

https://github.com/electron/electron/pull/20614
