### ISSUE TITLE
NWJS 0.40.2 crash dump - Webworkers re-compile causes NWJS to crash.

### ISSUE THREAD

**Issue by gitTerebi** [nwjs/nw.js#7148]
NWJS Version :0.40.2
Operating System : WIn 64x

### Expected behavior

I have project with web workers, when web workers code is updated, the app recompiles and it should refresh browser.

### Actual behavior

Sometimes it crashes and NWJS exits instead. Doesn't happen on older v0.34.5

Here is the minidump file.
[f0288ceb-9930-4b88-b796-ca0593ecae5a.zip](https://github.com/nwjs/nw.js/files/3564395/f0288ceb-9930-4b88-b796-ca0593ecae5a.zip)

I managed to run stackwalk and this is the output
[crash log.txt](https://github.com/nwjs/nw.js/files/3616261/crash.log.txt)

> Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
> Crash address: 0x7

> Thread 21 (crashed)
>  0  ntdll.dll + 0xa5f14
>     rbx = 0xffffffff   r12 = 0x00000000   r13 = 0x1c967a40   r14 = 0x1f80f858
>     r15 = 0x00000000   rip = 0x73305f14   rsp = 0x53dff900   rbp = 0x1b0c0000
>     Found by: given as instruction pointer in context

**Comment by gpetrov** [comment]
This also happens on 0.37.4

We use web workers extensively because of we have integrated the Monaco Editor in NWJS app.

The crashes happen specially if devtools is open.

[98f00e3d-9781-497d-9fe5-fa7410993913.zip](https://github.com/nwjs/nw.js/files/3566616/98f00e3d-9781-497d-9fe5-fa7410993913.zip)

@rogerwang - any advise?

**Comment by gitTerebi** [comment]
0.34.5 happens to be the last workable version of NWJS that doesn't crash.

I noticed allso with version above that, _the dev tools window doesn't save its position anymore and always resets its size._ I Thought might be profile bug, but deleting profile folders doesn't do anything.

Would keeping devtools closed stop the error?

**Comment by gpetrov** [comment]
@gitTerebi as for the devtools, there is already an open issue for it https://github.com/nwjs/nw.js/issues/7054

I really hope @rogerwang can look at both issues as they are pretty urgent, specially the crashes.

**Comment by gitTerebi** [comment]
I walked through mini dump and the crash log seems unhelpful.

> Crash reason: EXCEPTION_ACCESS_VIOLATION_READ
> Crash address: 0x7
> 
> Thread 21 (crashed)
> 0 ntdll.dll + 0xa5f14
> rbx = 0xffffffff r12 = 0x00000000 r13 = 0x1c967a40 r14 = 0x1f80f858
> r15 = 0x00000000 rip = 0x73305f14 rsp = 0x53dff900 rbp = 0x1b0c0000
> Found by: given as instruction pointer in context

Is the crash really with ntdll? Thats a windows thing.

**Comment by rogerwang** [comment]
Could you please provide a sample so I can reproduce this?

**Comment by gitTerebi** [comment]
[sample.zip](https://github.com/nwjs/nw.js/files/3620997/sample.zip)

Uploaded project sample.

- Open up 'nwjs-webworker-crash' project
- Had to include agenda as it crashes when a task runs
- There is a video watch me with a screen record of exact steps I take in program to cause crash

How to reproduce
- Have devtools open
- Click new task
- Wait for task to complete
- Click upper left hand 'click here to restart app'
- Wait about 5 secs and app crashes

I hope this is enough.
