### ISSUE TITLE
menu.popup misplaced when zoomLevel is set.

### ISSUE THREAD

**Issue by ibdknox** [nwjs/nw.js#715]
If you set the zoomLevel and popup a menu, the menu will not be correctly placed on the x axis and it gets worse the further right you go. I haven't been able to figure out exactly what the scaling factor for it is yet, it seems to be exponential not linear.

Mac OSX 10.8.3, NW 0.5.1

![screen shot 2013-05-13 at 1 52 34 pm](https://f.cloud.github.com/assets/70036/498175/13b4ad26-bc0f-11e2-8beb-f1d7c9f82012.png)

**Comment by rogerwang** [comment]
Should be fixed in latest 0.13.0
