### ISSUE TITLE
[Feature request] Add support for create webview with referer

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7150]
Suggestion feature: Add support for create webview with referer.

Like in Electron: https://electronjs.org/docs/api/webview-tag#httpreferrer

I can send referer via `webview.request.onBeforeSendHeaders`, but document.referrer is an empty string.

**Comment by Sombian** [comment]
Use chrome instead.

**Comment by panther7** [comment]
@Sombian Please, explain
