### ISSUE TITLE
DesktopCaptureMonitor: No audio

### ISSUE THREAD

**Issue by polhaghverdian** [nwjs/nw.js#7153]
NWJS Version : v0.40.2
Operating System : Windows 10

### Expected behavior

By using the desktopCapturer API, should retrieve Both screen and windows with audio + video. I only get video without audio when retreive desktop window, but get audio + video for entire screen.

### How to reproduce

`var dcm = nw.Screen.DesktopCaptureMonitor;
nw.Screen.Init();
dcm.on("added", function (id, name, order, type) {
   //select first stream and shutdown
   var constraints = {
      audio: {
         mandatory: {
             chromeMediaSource: "system",
             chromeMediaSourceId: dcm.registerStream(id)
          }
      },
      video: {
         mandatory: {
             chromeMediaSource: 'desktop',
             chromeMediaSourceId: dcm.registerStream(id)
         }
      }
  };

  console.log(id + " " + name);
  navigator.webkitGetUserMedia(constraints, success_func, fallback_func);
  dcm.stop();
});

dcm.on("removed", function (id) { });
dcm.on("orderchanged", function (id, new_order, old_order) { });
dcm.on("namechanged", function (id, name) { });
dcm.on("thumbnailchanged", function (id, thumbnail) { });
dcm.start(true, true); // get both entire screen and windows

function success_func(stream){
  console.log("GetUserMedia: Success");
  peerConnection.addStream(stream);
}`

**Comment by sivsushruth** [comment]
was this fixed ? I could only get audioTracks on screen streams, not window/application streams. 
@polhaghverdian
