### ISSUE TITLE
NWJS Licensing

### ISSUE THREAD

**Issue by nwjsEnthusiast** [nwjs/nw.js#7156]
Hello,
 
I would like to use your amazing app runtime for developing a proprietary licensed software.
 
While looking through the options available I would use the nwjs-builder-phoenix to package the app.
 
As I understand the packager would package my app and download the nwjs dependencies needed directly from your website.
 
My concern lies in the Credits.html, it lists quite a list of licenses, most are ok, but some maybe not:
- LCOV - the LTP GCOV extensions - which is licensed under GPL
- libcxx-pretty-printers - also licensed under GPL
- logilab - GPL
- mesa_headers - GPL
- Speec Dispatcher - GPL
 
Maybe some more I have missed entirely.
 
On github i can find the license file https://github.com/nwjs/nw.js/blob/nw40/LICENSE
 
And at this link https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps#which-files-should-be-shipped
 
Here it states that "And since the binary is based on Chromium, multiple open source license notices are needed including the MIT License, the LGPL, the BSD, the Ms-PL and an MPL/GPL/LGPL tri-license. (This doesn't apply to your code and you don't have to open source your code)"
 
This states that it does not apply to my code, however a GPL license is requiring me to open-source my software. I am wondering how is my code exempt from this?
 
 
Please help me understand what I am missing.
 
Thank you in advance!!
 
Best regards,
nwjsEnthusiast

**Comment by bluthen** [comment]
Several of those I believe are only used during build time as a utility (like cp of GNU coreutils) and not actually in the chromium/nwjs binary.  I believe that covers LCOV, libcxx-pretty-printers, and logilab. 

mesa_headers looks actually to be LGPL.

I'm unsure about speech dispatcher. It looks like it is only the header that is used, but that is enough. There is maybe a compile flag on if it is used or not. Need to look into that one.

There must be some chromium issue or some chromium document that can explain better than my comment though. Good thing to always check on, for sure.

**Comment by rogerwang** [comment]
Those lines of GPL are simply inherited from the Chromium project. If you navigate to 'chrome://credits' in Chrome or Chromium browser, you could see them as well. Those libraries are used in development phase, they are not linked in the final binary I think. For example, LCOV is a tool used for code coverage report. Chrome remains closed source but it gives credit to those tools too.

And your program (js, html, css) is simply distributed with NW binary together. They are loaded and executed by NW. The relationship is not the "linking" relationship defined by GPL. That means, even if NW.js is GPL (it's not though), your program doesn't need to be released under GPL license. See more info: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#IfInterpreterIsGPL

Also thanks to @bluthen for the answer.
