### ISSUE TITLE
restore add 14pixels to height and width.

### ISSUE THREAD

**Issue by Sombian** [nwjs/nw.js#7165]
To reproduce:

define both `min width` and `min height`.
define `frame: false`.
resize an app to its minimum.
maximize.
restore.

**Comment by TheJaredWilcurt** [comment]
@Sombian I think what you are trying to say is 

1. Create a window with a minimum size defined (`min_width`/`min_height`)
1. Manually resized to the window to that minimum size
1. Run `nw.Window.get().restore();`

And then the window grows in by 14 pixels to the right and bottom.

I am unable to reproduce this on Windows. You did not state an OS.

Reply back with detailed reproduction steps, OS, and NW.js version.

**Comment by Sombian** [comment]
To reproduce,
Declear min width and height.
Resize an app to its minimum.
Maximize.
Restore.

**Comment by TheJaredWilcurt** [comment]
I am unable to reproduce this issue.

* [package.nw.zip](https://github.com/nwjs/nw.js/files/3833509/package.nw.zip)

Tested on Windows 10.

**Comment by Sombian** [comment]
> I am unable to reproduce this issue.
> 
> * [package.nw.zip](https://github.com/nwjs/nw.js/files/3833509/package.nw.zip)
> 
> Tested on NW.js v0.42.3 (64-Bit) Windows 10.

weird... Perhaps its because my app is frameless?

**Comment by Sombian** [comment]
@TheJaredWilcurt could you please re-review the issue?

**Comment by TheJaredWilcurt** [comment]
With the above example, but with `"frame": false` added to the `"window"` section of the `package.json`, I am still unable to reproduce this issue on Windows 10 with the latest SDK version of NW.js. Closing until further reproduction steps are provided.
