### ISSUE TITLE
Chromium logging doesn't generate log file

### ISSUE THREAD

**Issue by pkorzeniewski** [nwjs/nw.js#717]
Enabling Chromium logging (following [1] steps), using "--enable-logging" in package.json "chromium-args", doesn't generate log file.

[1] http://www.chromium.org/for-testers/enable-logging

node-webkit version: 0.5.1
platform: Windows 7 (may also occur on other platforms)

**Comment by rogerwang** [comment]
Please try the latest 0.13.0 release. It should be fixed.
