### ISSUE TITLE
App crashes on Windows on call to Window.setBadgeLabel

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#7170]
NWJS Version : 0.40.0 - 0.41.2
Operating System : Windows 7 - x64

### Expected behavior

App to show the badge label

### Actual behavior

App crashes

### How to reproduce

Execute the following code, i.e. via dev console:

```javascript
nw.Window.get().setBadgeLabel('1')
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by panther7** [comment]
@rogerwang You can update docs, where you write only support in Linux: 
* http://docs.nwjs.io/en/latest/References/Window/#winsetbadgelabellabel
* http://docs.nwjs.io/en/latest/References/Window/#winsetprogressbarprogress
Both works in Windows (maybe in macOS)

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw41/10-06-2019/f27c5a061/v0.41.3/

@panther7 thanks for the reminder. Will do it.
