### ISSUE TITLE
ERROR:http_transport_win.cc(178)] WinHttpCrackUrl

### ISSUE THREAD

**Issue by rbhushasn** [nwjs/nw.js#7171]
NWJS Version :v0.41.2
Operating System :Windows 10 x64

Issue:
I am trying to open Microsoft Team web URL through NW. When I am Closing Microsoft Team 
 Nw Window whole app is crashing.

Expected behavior:

It should close only New instance 

Full error text

[0924/144256.285:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)
[debug.log](https://github.com/nwjs/nw.js/files/3647223/debug.log)

**Comment by nerdError** [comment]
It happened to me too (im using desktop build of Construct 3). NW.js just crashes, when im trying to login into account
