### ISSUE TITLE
Widevine DRM and required components to play video

### ISSUE THREAD

**Issue by michalvasek** [nwjs/nw.js#7176]
NWJS Version : nw.js v0.41.1
Node: v12.9.1
Chromium: 77.0.3865.78
Operating System : Win10

- NW.js is not able to find all the required components to play Netflix video in our Application based on NW.js
- There is some TODO comment in your modification in [chrome_content_client.cc](https://github.com/nwjs/chromium.src/blob/a02e311f9623d6ebdc493303a8f114da44684b9c/chrome/common/chrome_content_client.cc#L99) referenced to crbug.com/663554.

Is there something to be finished? Or how to build binaries and use the Widevine correctly?

**Comment by panther7** [comment]
NWjs 0.38.4 works properly, with widevine dll from Chrome.

**Comment by michalvasek** [comment]
Done.

Two files has to be changed. See the [commit](https://github.com/michalvasek/chromium.src/commit/b52b7d0d734886f047b42f33a48b8589b3bf63ea).
- chrome/common/chrome_content_client.cc
- third_party/widevine/cdm/widevine_cdm_version.h

Chromium defines seems to have changed, and thus Widevine (a content decryption module for the digital rights management) that worked in older verisons doesn't work anymore in versions 71 or later.
