### ISSUE TITLE
Latest Normal NWJS not auto reload when no internet occurred.

### ISSUE THREAD

**Issue by HakobiDev** [nwjs/nw.js#7178]
NWJS Version : NWJS Normal 0.42.0-beta1
Operating System : Windows 7

### Expected behavior

I want to auto reload my app when no internet connection occurred like on Google Chrome

### Actual behavior

Not Reloading still stuck on No internet connection

Details
![image](https://user-images.githubusercontent.com/40719101/66679537-fd4b3e00-eca0-11e9-86b4-b18da498bedc.png)

![Untitled](https://user-images.githubusercontent.com/40719101/66679594-28359200-eca1-11e9-8176-9ae49481c599.png)

Thanks in advance!

**Comment by bluthen** [comment]
You can set your own error page and have it reload the app. You can see my comments on a related issue where I do that.
#5365
