### ISSUE TITLE
The profile appears to be in use by another nwjs

### ISSUE THREAD

**Issue by kmughal** [nwjs/nw.js#7179]
NWJS Version : 38.2
Operating System : Linux

We have a linux box and when I start nwjs I am getting "The profile appears to be in use by another nwjs" error.

When I enter any key from keyboard it relaunches the application and it works fine. 
How to get rid of the above mentioned issue.

Regards
Kmughal

**Comment by bluthen** [comment]
I think just remove 
 `~/.config/<name-in-manifest>`

**Comment by kmughal** [comment]
Can you please shed more light?

**Comment by bluthen** [comment]
https://askubuntu.com/questions/476918/google-chrome-wont-start-after-changing-hostname

Not sure how it happens but my thought is maybe there is something weird that happend with the singleton files in the user dir. If you delete it it should be fixed.
