### ISSUE TITLE
node-remote does not recognize file:// scheme

### ISSUE THREAD

**Issue by corwin-of-amber** [nwjs/nw.js#7183]
NWJS Version : 0.41.2
Operating System : macOS 10.15

### Expected behavior

`node-remote` in manifest  is said to support URL schemes 'http', 'https', 'file', 'ftp' (here: http://docs.nwjs.io/en/latest/References/Manifest%20Format/#node-remote).

### Actual behavior

Setting `node-remote: ["file://*"]` (or any other `file://` URL pattern) results in the following error on application startup:
```
Failed to load extension from: <--location-->.
Invalid value for 'app.urls[0]': Invalid scheme.
```

Setting it to `["*://*"]` allows the application to start, but has no effect on `file://` URIs. This may be related to https://github.com/nwjs/nw.js/issues/6860.

### How to reproduce

This is a minimal `package.json` that reproduces the error:
```
{
    "name": "node-remote-issue",
    "main": "index.html",
    "node-remote": [
        "file://*"
    ]
}
```

Run `nw` in a directory containing this file.

**Comment by TheJaredWilcurt** [comment]
`node-remote` allows you to access Node from the DOM at **REMOTE** urls.

By default if your `"main"` is a local file like `"index.html"` it already has Node access from the DOM.

**Comment by corwin-of-amber** [comment]
The `"main"` file is loaded using the special scheme `chrome-extension://`.

Therefore I understood, which is supported by the information in the docs, that local files are still considered "remote".

Currently there is no way to open a `file://` URL and have it access Node. If this is intended, then I suggest the documentation should be fixed.

<img width="707" alt="Screen Shot 2019-10-22 at 15 05 12" src="https://user-images.githubusercontent.com/704372/67284011-7175b500-f4dd-11e9-9bcb-92ef4d0491d4.png">

**Comment by liuyi** [comment]
I want to load a local file:
file:///Users/aaa/work/git/test/mac/books/cache/video_player_close_btn.html

the html file can call javascript funciton in parent window, but got error:
Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.

I tried: 
note-remote, 
sandbox of iframe,
nw.App.addOriginAccessWhitelistEntry();

But always show me the error.

**Comment by liuyi** [comment]
I resolved ths probem, like this:
1\set package.json 
"chromium-args":"--disable-web-security'" 

2\ Use window.postMessage('what your want to send","*") instead of javscript call.

That's all. It works!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
