### ISSUE TITLE
[BUG]crash when downlod in iframe

### ISSUE THREAD

**Issue by ww-k** [nwjs/nw.js#7187]
NWJS Version : 0.29.0, 0.40.2, 0.41.3, 0.42.0
Operating System : mac and win

### Expected behavior
open target directory selector.

### Actual behavior
nwjs crash

### How to reproduce

use this demo

https://github.com/ww-k/nwjs_crash_demo/tree/master/download_in_iframe

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by ww-k** [comment]
thanks。0.42.1 fixed the bug。but cause another bug。#7193。
