### ISSUE TITLE
[BUG]crash on terminate web worker with enable node worker

### ISSUE THREAD

**Issue by ww-k** [nwjs/nw.js#7188]
NWJS Version : 0.29.0, 0.40.2, 0.41.3, 0.42.0
Operating System : mac and win

### Expected behavior
no crash

### Actual behavior
nwjs crash

### How to reproduce

use this demo

https://github.com/ww-k/nwjs_crash_demo/tree/master/terminate_node_worker

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by ww-k** [comment]
thanks。0.42.1 resolved the problem.
