### ISSUE TITLE
Add setting to change how "RequestAnimationFrame" works

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#7190]
By the looks of it, when chromium-based browsers(and NW.js) are minimized they either slowdown a lot or pause the execution of the RequestAnimationFrame loop. That behavior is acceptable when dealing with browsers, since those usually have many tabs to handle and it doesn't make much sense to keep animations running when they aren't being seen, but for NW.js applications(mainly games), such behavior can cause problems. 

In my case for example, I've a multiplayer game that allows servers to make use of custom maps(which are downloaded by the client upon connection). If the client is minimized, it downloads the map but doesn't load nor displays it until maximized again, adding a long extra time to the loading(also while the requestanimationframe pauses execution, audios and other scripts don't, so that can also create many problems with synchronization of scenes and such).

My suggestion is: Add a new setting to package.json(maybe a new js function aswell) to allow disabling said pause.

**Comment by rbfowler9lfc** [comment]
Such option already exists: http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-disable-raf-throttling

**Comment by elpeleq42** [comment]
oh that solves my problem, thank you!

I tried googling if there was such setting for a long time but couldn't find anything. Again, thank you!
