### ISSUE TITLE
nw.Window.close event does not have "quit" on macOS when closed by ⌘+Q 

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#7191]
It works as expected in 0.41.3, broken in 0.42.0

======== TEMPLATE BUG FORM ========

NWJS Version : 0.42.0
Operating System : macOS Catalina

### Expected behavior

According to documentation we have the following and it was working until some recent changes:

On Mac, there is an argument passed to the callback indicating whether it’s being closed by ⌘+Q. It will be set to string quit if that’s true, otherwise undefined.

### Actual behavior

user_force is undefined in the following code of nw.Window and event that is passed to listener for `close` is undefined

```javascript
function onClose(user_force) {
  if (!currentNWWindow)
    return;
  currentNWWindow.onClose.dispatchNW({instanceId: currentWidgetRoutingID}, user_force);
}
```

### How to reproduce

Can be reproduced by running something like this in dev tools and doing ⌘+Q

```javascript
nw.Window.get().on('close', (event) => alert(`event: ${ event }`))
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
