### ISSUE TITLE
Slow Startup Performance Regression In NWjs v0.41.0+

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7192]
**NWJS Version:** v0.41.0+
**Operating System:** Windows 7, Windows 10
**Reproduction Project:** [packagerepro.zip](https://github.com/nwjs/nw.js/files/3779953/packagerepro.zip)
**Additional Note:** Linux and OSX could be affected as well, not tested. No difference between using a package.nw archive or unzipped folder.

### Expected behavior
Newer versions of NWjs should start just as fast as they did before.

### Actual behavior
Newer versions start with a noticeable delay. I started NWjs at least once before doing the measurements, to avoid the 1st time caching delay that executable files usually have.

Average startup loading times*:
- v0.39.0 = ~0,5sec 
- v0.40.2 = ~0,6sec 
- v0.42.0 = ~6,2sec

(Tested using: Win7, Quad Core 3.4ghz CPU, 8gb RAM, Normal HDD)
*Before the game engine loader is being displayed.

### How to reproduce
1. Download project for reproduction
2. Download mentioned NWjs versions (in my case: SDK-Win64)
3. Put package.nw inside NWjs folder and run it
4. Notice latest versions taking longer to startup

**Comment by rogerwang** [comment]
The startup performance is good. The delay is in sync call to `nw.App.clearCache()` in `cr_createRuntime("c2canvas");` before showing the main window. In upstream the cache clearing operation is in low priority and was delayed during startup.

This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw42/10-29-2019/0a333e6cf/v0.42.1/

**Comment by TheRealDannyyy** [comment]
Can confirm that it's fixed, thanks a lot.
Any planned release date for v0.42.1?

**Comment by rogerwang** [comment]
It will be released soon.

**Comment by panther7** [comment]
I have still white screen after start (1-2secs), NWjs 0.43+

**Comment by jonnathanlopes** [comment]
> Ainda tenho a tela branca após o início (1-2seg), NWjs 0,43+
same issue in 0.45 :\
