### ISSUE TITLE
nwjs not lunching after upgraded to latest ver.

### ISSUE THREAD

**Issue by Sombian** [nwjs/nw.js#7195]
NWJS Version : latest
Operating System : windows 10 pro x64 latest

i used nwjs-builder-phoenix.
0.42.0 and older works though.

no error code too. it just dont appear.

**Comment by Sombian** [comment]
> Is your app launching if nwjs-builder-phoenix is not used?

I havent tested yet, though aint phoenix auto-download from the server? Did some expressions now unsupported cause of either node.js or chromium update?

**Comment by rogerwang** [comment]
It could be a bug in the package tool.

**Comment by Sombian** [comment]
> It could be a bug in the package tool.

following command works.
C:\Users\Sombian\waifu-material\node_modules\nwjs-builder-phoenix\caches\nwjs-sdk-v0.42.0-win-x64.zip-extracted\nwjs-sdk-v0.42.0-win-x64\nw.exe

but this.
C:\Users\Sombian\waifu-material\node_modules\nwjs-builder-phoenix\caches\nwjs-sdk-v0.42.1-win-x64.zip-extracted\nwjs-sdk-v0.42.1-win-x64\nw.exe

sure this aint an issue with phoenix but nwjs. could you please look into this?

**Comment by Sombian** [comment]
clean cache does the magic. self closing as of now.
