### ISSUE TITLE
[BUG]crash on terminate web worker in iframe with enable node worker

### ISSUE THREAD

**Issue by ww-k** [nwjs/nw.js#7196]
NWJS Version : 0.29.0, 0.42.2
Operating System :mac and win

### Expected behavior

no crash

### Actual behavior

nwjs crash

### How to reproduce

use this demo

https://github.com/ww-k/nwjs_crash_demo/tree/master/terminate_node_worker_in_iframe

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by ww-k** [comment]
http://dl.nwjs.io/live-build/nw42/11-09-2019/34918be40/v0.42.4/
fixed the bug
