### ISSUE TITLE
csv file not showing in webview since 0.37.0 - get download permission denied

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7202]
OSX 10.13.6 High Sierra using 0.42.3-sdk
0.36.4 is OK but 0.37.0 onwards fails
Have attached a test app
[WebviewMedia Test.zip](https://github.com/nwjs/nw.js/files/3824950/WebviewMedia.Test.zip)

Good 
<img width="2698" alt="workingexample" src="https://user-images.githubusercontent.com/11089335/68484611-81a7c700-0235-11ea-9296-2bc6b71152c5.png">

Fail
<img width="2696" alt="example" src="https://user-images.githubusercontent.com/11089335/68484063-8750dd00-0234-11ea-96b0-5b1c4a3e7d12.png">

Note: Tried 0.43.0b1 but non of the webviews work (also had a crash if inspect background was selected) - I had the same issue with 0.42 until the latest 0.42.3 arrived.

**Comment by rogerwang** [comment]
This is working on Windows. The browser looks up platform's registry to map file extension to mime type. On windows it returns 'text/plain' and the file is displayed, while on macOS it returns 'text/csv', which Blink [doesn't support](https://cs.chromium.org/chromium/src/third_party/blink/common/mime_util/mime_util.cc?rcl=4514de6ab53f9792d9657e9e49ccffcf7e7d3a25&l=79)

**Comment by Blatman** [comment]
OK - I guess that OSX support in Blink ceased at 0.37 so I guess the workround would be to change a csv file to text before displaying.

**Comment by Blatman** [comment]
Closing this since Blink doesn't support text/csv.
