### ISSUE TITLE
Youtube video embedding doesn't work 

### ISSUE THREAD

**Issue by josh83abc** [nwjs/nw.js#7205]
Hi guys!

I have a strange problem with youtube video embedding. 

Important : the problem only appears with some videos, apparently copyrighted videos.

The problem :

**Embedding a youtube video doesn't work when I open the video page the NW.JS way (chrome-extension://) BUT it works when I open the video page through a NW.JS web server (http://localhost/)**

See embedded picture of the problem : https://you.dj/nwjs_youtube_issue.jpg

A video which doesn't work : https://www.youtube.com/watch?v=leopt__ATR0 (Ariana Grande)
A video which does work :  https://www.youtube.com/watch?v=vmoZBKUAbFA (Some random video)
 
Any idea of what cause the issue?

Thanks!

**Comment by josh83abc** [comment]
**package.json :**
`{
  "name": "Youtube Test",
  "description": "Youtube Test",
  "version": "1.0",
  "main": "video.html"
}`

**video.html :**
`
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Youtube Test</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/leopt__ATR0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://www.youtube.com/embed/vmoZBKUAbFA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</body>
</html>
`

**Comment by TheJaredWilcurt** [comment]
http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/

**Comment by josh83abc** [comment]
Thanks Jared, but I don't think you read all my description. Some youtube videos (not all!) don't work with the chrome-extension protocol but do with the http protocol. I tried on Chrome, the behavior is the same. Any idea?

**Comment by borovinskiy** [comment]
It's played in nwjs and chrome: https://www.youtube.com/watch?v=leopt__ATR0&feature=youtu.be
It's not played https://www.youtube.com/embed/leopt__ATR0 in nwjs, chrome, firefox.

It's bug of youtube.
