### ISSUE TITLE
nwjs crashes when loading compiled js files (again)

### ISSUE THREAD

**Issue by acemod13** [nwjs/nw.js#7207]
NWJS Version: 0.42.x (happens in the most recent version as well)
Operating System: Windows 10, version 1909

### Expected behavior

The app or game should load up.

### Actual behavior

If the app's js files are compiled, the app would load but after a few seconds, it would close. No error log is shown.

### How to reproduce

Since it's the same issue as #7055 , the same steps to reproduce are the same.

**Comment by rogerwang** [comment]
Could you please provide a sample so I can reproduce it?

**Comment by acemod13** [comment]
https://drive.google.com/open?id=17R8m43Htpj6XpSDNwR0zeIGzYNUWpZH-

**Comment by acemod13** [comment]
So, I've done some investigation and turns out that the issue is the same as #7216 . Ran both a game and the sample I've uploaded and load fine.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
