### ISSUE TITLE
Delay to connect to websocket?

### ISSUE THREAD

**Issue by peq42** [nwjs/nw.js#7210]
For some reason, in the last few days I noticed that NW.js has been taking a long while to connect to websockets(and I haven't updated it nor made any modifications, it started happening after I tried to connect to a websocket without internet the other day).

Once I open my game, its supposed to connect to a websocket(I'm not using any library, just `var connection = new WebSocket("IP")` ), but for some reason, that first connection takes around 6 to 10 seconds to be made. If I refresh the game pressing F5, or make any new websocket connection, it is instantaneous(taking just 1 ms). Messages sent between my game and the server have no additional delay.

No errors are thrown, and as far as I can see there are no problems with my code(I've tested removing all the code that would run before and after it and do just the connection but it still was happening). I tried using a more recent version of NW.js aswell as older versions but the same happens.

I also tried googling if it was a problem with chrome, but I didn't find anything about it in the recent few years, thats why I decided to post here: is it a possible problem with NW.js? With Chrome? with my PC(Windows 10, fully updated)?

**Comment by rogerwang** [comment]
Could you provide a sample so I can reproduce it?

**Comment by tharatau** [comment]
Closing until a sample is provided
