### ISSUE TITLE
js-flags dont seems to work?

### ISSUE THREAD

**Issue by Sombian** [nwjs/nw.js#7212]
NWJS Version : latest
Operating System : windows 10 pro x64 latest

### Actual behavior
```js
console.log(nw.App.fullArgv); // []
console.log(nw.App.argv); // []
```

### How to reproduce
in ``package.json``
```json
{
/...
  "js-flags": "--harmony --use_strict --optimize_for_size --enable_node_worker --single_process"
/...
}
```

**Comment by rogerwang** [comment]
argv is not supposed to include js-flags. it's for command line arguments.
