### ISSUE TITLE
NW.js above version 0.38.4 not starting on Ubuntu 18.04.1; needs libatomic?

### ISSUE THREAD

**Issue by NorbarTDB** [nwjs/nw.js#7213]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.42.4 SDK (latest at time of writing)
Operating System : Ubuntu Mate 18.04.1

### Expected behavior

On attempting to launch NW.js, I'd expect it to load and operate just like older versions up to 0.38.4 (the last version that seemed to work without issue).

### Actual behavior

Versions after 0.38.4 seem to hang on initialisation with:

> [2120:2120:1114/095336.479476:ERROR:sandbox_linux.cc(371)] InitializeSandbox() called with multiple threads in process gpu-process.
> [2143:2143:1114/095336.586075:FATAL:nw_content_renderer_hooks.cc(53)] Failed to load node library (error: libatomic.so.1: cannot open shared object file: No such file or directory)
> #0 0x7fb710051629 <unknown>

It doesn't crash; it just sits there until you CTRL+C out.

Libatomic is not installed on the system; if I install it with `sudo apt-get install libatomic1`, these NW.js versions will open as expected.

So in theory, I can get it running OK. **However I'm used to NW.js not having any external dependencies (that can't be found by default on a vanilla Debian system like Ubuntu, at least); is this no longer the case?** 

Does this new external dependency on libatomic affect licensing/distribution obligations in any way? Is it just for SDK variants past 0.38.4 (I have yet to investigate non-SDK builds past 0.35.4).

Additionally, I am trying to autostart the process (I have a .deb installer through which NW.js is installed and intended to run after boot). Needless to say it doesn't come up, but nor does it seem to exit, in which case, any attempts to launch it see the following via terminal:

> Opening in existing browser session

### How to reproduce

- Fresh install of Ubuntu 18.04.1
- Download NW.js SDK build 0.42.4 and extract it
- In the extracted folder, create a barebones index.html and package.json containing just the "name" and "main" tags
- `./nw .` in the terminal; in my tests, this causes the aforementioned explosion about libatomic

**Comment by rogerwang** [comment]
libatomic1 is required by Node.js in recent versions.

**Comment by NorbarTDB** [comment]
I see, thanks for the explanation! After having a look I've found a related ticket on the Node.js issue tracker: https://github.com/nodejs/node/issues/29718

Also, possibly, where the decision may have been made to link it: https://github.com/nodejs/node/issues/28231

I guess I shall close this then, if it's out of scope for this project.

**Comment by mishagin-tim** [comment]
> libatomic1 is required by Node.js in recent versions.

If so, why is it still not distributed with nwjs? It seems that is a core lib which doesn't depend on application's domain.

**Comment by LostBeard** [comment]
Also found this issue after trying to deploy an app to various Ubuntu distros. 

Fixed the issue on Ubuntu distros by installing libatomic1 via apt.

Is it possible to distribute libatmlic1 with an NW.js app or does it have to be installed using apt or other package manager?
