### ISSUE TITLE
Possible bytecode flushing issue on 0.42.3 / 0.42.4

### ISSUE THREAD

**Issue by NorbarTDB** [nwjs/nw.js#7216]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.42.3 (and 0.42.4)
Operating System : Ubuntu Mate 18.04.1

### Expected behavior

Normal behaviour after launch (starts up and runs)

### Actual behavior

_Extremely_ similar to #7045 (this code previously ran absolutely fine on 0.35.4) 

On load, everything *looks* normal and I can boop around my UI as usual. But if I try to perform one or two certain actions in my UI (kicking off a certain code path, I suppose) things will seem to work momentarily and then go horribly wrong a random, short amount of time later. The Entire app disappears and the error log reads (though the numbers change):

```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffcd13759d0#0 0x7f04d56a9df9 <unknown>
```
Note: **If I use `--js-flags=--no-flush-bytecode` the problem goes away** and everything works perfectly. That's great (and I'm not losing anything really, seeing as bytecode flushing wasn't in 0.35.4 as far as I know), however I'm not sure if this is a good long-term solution?

### How to reproduce

Alas, I am not sure yet. Most of the UI works, I can't post the code in question, and I haven't found another way to replicate it yet. There is nothing particularly special about the code paths that fail, except that both trigger a change in the amount we're leaning on external modules like node-serialport, for instance starting or stopping communication with external serial devices. While idling those modules aren't up to much, although they are used briefly on startup to find the aforementioned devices.

**Comment by rogerwang** [comment]
The flag is fine for production.

If a sample can be provided, I will look to reproduce and fix it.

**Comment by NorbarTDB** [comment]
OK. good to know! I will try and reproduce it in a clean example.

Thanks for your time!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by zkrige** [comment]
I had to use `--js-flags=--no-flush-bytecode` in 0.42.4 to make the issue go away

**Comment by NbrTDB** [comment]
@zkrige me too, but as of 0.43.x I no longer encounter this issue, it has been fixed.
