### ISSUE TITLE
Serialport native module crashing nwjs

### ISSUE THREAD

**Issue by dilushan** [nwjs/nw.js#7218]
Im using serialport node module in nwjs (0.42.4 32 bit sdk) windows 10 system. I used nw-gyp to rebuild node modules accrording to this guide
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/#install-with-npm
But when running below code nwjs crashing like this
        
> var serialport = nw.require('serialport');
> 	const port = new serialport('COM1', function (err) {
> 	  if (err) {
> 		return console.log('Error: ', err.message)
> 	  }
> 	})

![image](https://user-images.githubusercontent.com/6021514/69005285-01c0e180-0946-11ea-8faf-494eb3058216.png)

But i can require bindings.node from console fine

![image](https://user-images.githubusercontent.com/6021514/69005341-eb675580-0946-11ea-87ea-22cb3a645c05.png)

Please note that when I follow the same procedure on 64 bit nwjs sdk serialport module working as expected.

**Comment by dilushan** [comment]
I found out serialport working fine on v0.37.0 of 32bit nwjs. So this is a problem with newer versions

**Comment by rogerwang** [comment]
I just found it shares the same root cause as https://github.com/nwjs/nw-gyp/issues/130#issuecomment-541680390 . So merging with that issue and you can use the workaround there.
