### ISSUE TITLE
Menu bar on macOS has typical browser menu with nw2

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#7219]
NWJS Version : 0.42.4
Operating System : macOS Catalina

### Expected behavior

Menu bar should be almost empty, potentially with ability to enable some of the standard browser menus programmatically.

### Actual behavior

Top menu bar has typical browser menu, but many of menu items are broken as they lead to chrome:// urls that don't have implementation / binding in nwjs

### How to reproduce

Just downloading and starting nwjs 0.42.4 on macOS.

<img width="752" alt="Screenshot 2019-11-18 13 35 54" src="https://user-images.githubusercontent.com/1192686/69080164-6d1fb780-0a09-11ea-86cb-fa1e0debf129.png">

**Comment by arudnev** [comment]
Ah, just noticed last commit (https://github.com/nwjs/nw.js/commit/a0f79cf7a1d26f59cd7e1245c0eea5d7dc448c7c), I presume that should take care of it in the next release...

**Comment by rogerwang** [comment]
Thanks for reporting. 
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by arudnev** [comment]
nwjs menu still has `About nwjs` menu item in 0.42.5 that opens broken `chrome://settings/help` url.

Should I report separate issue for that or it can be addressed as part of this one?

**Comment by rogerwang** [comment]
Will fix it soon under this one. Thanks.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
