### ISSUE TITLE
Fullscreen option in package.json not working

### ISSUE THREAD

**Issue by tokumaru-x** [nwjs/nw.js#7225]
NWJS Version : 0.42.5
Operating System : Windows 10

### Expected behavior

Setting the "fullscreen" option in the manifest file to **true** should cause the application to start in fullscreen.

### Actual behavior

Setting the "fullscreen" option in the manifest file to **true** doesn't have any effect, the application starts in a regular window.

### How to reproduce

Create the following 2 files and run them as an NW.js application:

package.json:

	{
		"name": "fullscreen test",
		"main": "index.html",
		"window": {
			"title": "Window Title",
			"fullscreen": true
		}
	}

index.html:

	<!DOCTYPE html>
	<html>
		<head>
		</head>
		<body>
			<p>Hello, World!</p>
		</body>
	</html>

NOTE: The fullscreen option appears to work fine in older NW.js versions (e.g. v0.35.3).
EDIT: This appears to be NW2 related, seeing as fullscreen still works in v0.42.3.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
