### ISSUE TITLE
nw2: How to retrieve opened windows as `nw.Window` object?

### ISSUE THREAD

**Issue by cyantree** [nwjs/nw.js#7227]
NWJS Version : 0.42.5
Operating System : Win 10

### Expected behavior

As in NW1 with `chrome.app.window.getAll()` there's an api for retrieving all opened windows and accessing their contents.

### Actual behavior

The said api doesn't work anymore. It's possible to retrieve some information with `chrome.windows.getAll({populate: true}, console.log)` however I don't know how to find the appropriate window objects from there.

### How to reproduce

- `chrome.app.window.getAll()` now only returns an empty array.

**Comment by rogerwang** [comment]
Do you want to access the DOM window or the nw.Window object?

**Comment by cyantree** [comment]
Both ways are fine to me as it is possible to get the other object by using `nw.Window.get(domWindow)` or `nwWindow.window`. Do these methods still work with nw2?

**Comment by rogerwang** [comment]
Added `nw.Window.getAll()` and it will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by cyantree** [comment]
Nice, thanks!

**Comment by cyantree** [comment]
Just tested it in `v0.42.6`. Works nicely, thanks again!
