### ISSUE TITLE
nw2: win.setShadow(false) crashes app on start with trap 14

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7232]
0.42.6 and 0.43.0 - OSX High Sierra (10.13.6)
(#5875 closed so this is re-submission)

Was trying to rework a transparent app and unable to get rid of window shadow - found this also to be the case with normal framed windows as well. I tried using win.setShadow(false) in the js and the app just crashes on startup with trap 14.

Window-test app is attached - the disabling of the shadow will work OK with nw2 disabled.
Not sure but should it be the case that transparency should also disable the window shadow? - it appears to be the case with nw1 as I have never had to set the win shadow before in my transparent apps.

[Window-test.zip](https://github.com/nwjs/nw.js/files/3878495/Window-test.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
