### ISSUE TITLE
nw2: win.setAlwaysOnTop(true) not working

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7233]
0.42.5 and 0.43.0 - OSX High Sierra (10.13.6)
(#5875 closed so this is re-submission)

Seems to be an issue using win.setAlwaysOnTop(true); during runtime.
Works OK with nw2 disabled and will work if set as a win.open parameter in manifest.
Can be tested with Window-test.zip attached to #7232 - just enable win.setAlwaysOnTop(true); in osxmenu.js and disable win.setShadow()

**Comment by AndikaTanpaH** [comment]
I confirm this can't work too in Ubuntu 16.04 32bit (I try SDK nw2)

On my Windows 10 Machine, this working as well.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
