### ISSUE TITLE
{0.5.1] disable-web-security doesnt work anymore

### ISSUE THREAD

**Issue by ladiko** [nwjs/nw.js#724]
starting with version 0.5.1 i have the issue that node-webkit throws these errors on the console:

"XMLHttpRequest cannot load http://127.0.0.1:1335/alive. Origin http://127.0.0.1 is not allowed by Access-Control-Allow-Origin.", source: http://127.0.0.1/web/app.php (0)

These errors occur with 0.4.x when used without the command line parameter --disable-web-security but with 0.5.1 it doesnt work.

**Comment by DanielJoyce** [comment]
Yes, this is stupid. It makes testing of running existing website in NW harder.

**Comment by gordonpro** [comment]
It should be allowed for cross-domain without node.js enabled. what if I only want to use json services from other domain but don't want to expose the nodejs `fs.delete()`

**Comment by frankhale** [comment]
I agree @gordonpro. I'd love to disable web security and disable node. It makes sense for my app where I load a external resource into an iframe. Unfortunately the iframe is created by an 3rd party API I have no control over. I can add nwdisable to the iframe only after the API created it. I am therefore exposed briefly to any potential malicious code that may have been put into the 3rd party API.
