### ISSUE TITLE
Links in PDF file to external html file

### ISSUE THREAD

**Issue by arning** [nwjs/nw.js#7240]
Hi,
I have follwing issue

NWJS Version :  v0.42.5
Operating System : Win10

### Actual behavior

There is a hyperlink (pdf web link) in a PDF file to an external html file.
The html file is not opened.
Following error message appears in the DevTools console:

`pdf_viewer.js:1149 Uncaught TypeError: Cannot read property 'NEW_BACKGROUND_TAB' of undefined
    at PDFViewer.handleNavigate (pdf_viewer.js:1149)
    at PluginController.handlePluginMessage_ (pdf_viewer.js:1615)
    at HTMLEmbedElement.<anonymous> (pdf_viewer.js:1476)`
  
### Expected behavior

If I open the same file in Chrome (as local file) the link does work and the html file opens.
It should do the same in nw.js.
Links that lead to a destination within the same pdf file, do work as expected in nw.js. 

Thank you!

**Comment by rogerwang** [comment]
Could you provide a sample so I can reproduce?

**Comment by arning** [comment]
Here is very simple example
[nwjs_link_in_PDF.zip](https://github.com/nwjs/nw.js/files/3892292/nwjs_link_in_PDF.zip)

If I open this in Chrome as file:\\, it works.

I am new to nw.js, so maybe I am missing something quite obvious. 
However, for us the ability to open PDFs and use links inside the PDFs is quite important.

Peter

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
This is a regression of #4915

**Comment by arning** [comment]
Thank you very much for resolving this issue!
I tested it on Linux at home and it worked (the linked file opened in a new window - is this the expected behavior?)
Anyway it's good news.
I will check it on Win10 when I'm back in office.

Cheers!

**Comment by rogerwang** [comment]
Yes that's the expected behavior. How would you like it to be handled?

**Comment by arning** [comment]
I thought that the link would open in the same window same as normal html links.
