### ISSUE TITLE
"Can't update NW.js" popup error suddenly appearing (0.42.3)

### ISSUE THREAD

**Issue by NbrTDB** [nwjs/nw.js#7241]
NWJS Version : 0.42.3 (SDK build)
Operating System : Ubuntu Mate 18.04.1

### Expected behavior

NW.js runs normally, without throwing popups (previous version 0.35.4 was fine in this regard)

### Actual behavior

(Not a bug, but unexpected): NW.js occasionally throws the following popup:

> "Can't update NW.js"
> NW.js couldn't update to the latest version, so you're missing out on new features and security fixes.
> [Reinstall NW.js]

![image](https://user-images.githubusercontent.com/21238754/69619924-53e3c000-1034-11ea-81d1-3c1265bd78ab.png)

Is this just an SDK build feature, or is it going to happen to production builds as well? As of yet I've seen it on the former, but not the latter.

If it can happen on the latter, how would I disable it? Is there a flag to set in package.json?

### How to reproduce

It seems to just pop up occasionally. What I'd really like to avoid is this popping up in production builds (thus far, I have not seen that happen). If it's just limited to the SDK builds then that's fine.

Thanks for your time!

**Comment by rogerwang** [comment]
This should be fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
