### ISSUE TITLE
nw2: nw.Window.get() dont fire events.

### ISSUE THREAD

**Issue by Sombian** [nwjs/nw.js#7243]
**NWJS Version** : stable (0.42.5)
**Operating System** : windows 10 pro x64

**Expected behaviour:**

Window object fires event.

**Actual behaviour:**

Window object fires none on nw2 mode.

**To reproduce:**

```js
// at main entry point
const app = nw.Window.get();
//...
    app.on("loaded", () => {
      console.log("loaded");
      app.show();
    });
//...
```

side-note: theres a bug where --single-process force an app to draw none.

**Comment by Sombian** [comment]
please fix.

**Comment by rogerwang** [comment]
Could you please provide a full sample so I can reproduce it?

**Comment by Sombian** [comment]
> Could you please provide a full sample so I can reproduce it?

[example.zip](https://github.com/nwjs/nw.js/files/3904750/example.zip)

here.

**Comment by Sombian** [comment]
@rogerwang could you please review the file?

**Comment by Sombian** [comment]
mosi mosi?

**Comment by Sombian** [comment]
Help~~!

**Comment by rogerwang** [comment]
I just ran your sample and it seems working well.

**Comment by Sombian** [comment]
> I just ran your sample and it seems working well.

tis?
but for me app does show but no "loaded" appear on console nor if I set `show: false` at `manifest`
app doesn't showed unless I put ``app.show();`` outside of event scoped.

**Comment by rogerwang** [comment]
I think the `loaded` event tried to fire before the event handler is registered.

**Comment by Sombian** [comment]
> I think the `loaded` event tried to fire before the event handler is registered.

does nw2 have different behavior in event registering apart from nw1 in terms of order?
if so how can i know if nw is loaded (not dom)?
thanks.

**Comment by rogerwang** [comment]
I'm not sure about the question on behaviour, as the Vue code in the example is not very clear to me. And I found it not trival to try to run it under my version of NW.

As for your 2nd question, it's more kind of a general question that depends on how you define 'loaded', please ask it in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Sombian** [comment]
> I'm not sure about the question on behaviour, as the Vue code in the example is not very clear to me. And I found it not trival to try to run it under my version of NW.
> 
> As for your 2nd question, it's more kind of a general question that depends on how you define 'loaded', please ask it in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

Vue has nothing to do with this i believe so.
Funny it works fine on `nw1`.

**Comment by rogerwang** [comment]
I believe it too. It's just that I am not sure about the context of the
code within the Vue framework.

Please provide a sample without any framework. It would be more clear.
