### ISSUE TITLE
NW2: window size in package.json  don't work.

### ISSUE THREAD

**Issue by liuyi** [nwjs/nw.js#7248]
NWJS Version :0.42.5
Operating System :Mac OS

Package.json
````javascript
{
  "name": "com.test.myapp",
  "version": "1.0.0",
  "description": "mac version of  myapp",
  "main": "app/index.html",
  "domain": "myapp.com",
  "single-instance": true,
  "icon": "app/icon.png",
  "window": {
   
    "title": "app title",
    "fullscreen": false ,
    "kiosk": false,
    "position": "center",
    "resizable": false,
    "min_width": 1024,
    "min_height": 768



  },
  "webview": {
    "partitions": [
      {
        "name": "trusted",
        "accessible_resources": [
          "<all_urls>"
        ]
      }
    ]
  },
  "nodejs": true,

  "scripts": {
    "test": "test"
  },
  "keywords": [
    "ddschool"
  ],
  "note-remote":["file://*","http://*/*"],
  "chromium-args":"--disable-web-security",  // add --disable-features=nw2  it works fine.
  "dependencies": {
    "fs-extra": "^8.1.0",
    "sqlite-sync": "^0.3.9"
  }
}
````

**Comment by rogerwang** [comment]
Does the latest nightly build work for you?
https://dl.nwjs.io/live-build/nw42/11-29-2019/bbc43fcc4/v0.42.6/

**Comment by liuyi** [comment]
I will test it  at once

**Comment by liuyi** [comment]
After test, the problem still exsit.

**Comment by rogerwang** [comment]
Could you elaborate on the problem? Which part is not working and how is it expected to do.

**Comment by liuyi** [comment]
OK, I will submit a record video

**Comment by liuyi** [comment]
![image](https://user-images.githubusercontent.com/848803/69843490-af1aea00-12a2-11ea-816f-657a17f8ef1b.png)
![image](https://user-images.githubusercontent.com/848803/69843520-d2de3000-12a2-11ea-90b0-200bcb0f2184.png)

**Comment by liuyi** [comment]
![image](https://user-images.githubusercontent.com/848803/69843664-90692300-12a3-11ea-83ce-55f1fddd19d2.png)
![image](https://user-images.githubusercontent.com/848803/69843823-14bba600-12a4-11ea-8343-0720a19c75e0.png)

**Comment by liuyi** [comment]
@rogerwang  you can click the picture to see the 1:1 image.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
