### ISSUE TITLE
nw2: "nw.Window.get(window).isKioskMode"  TypeError

### ISSUE THREAD

**Issue by nvedamurthy** [nwjs/nw.js#7258]
NWJS Version : 0.42.6
Operating Systems : OSX 10.15.1, Ubuntu 18.04.3 LTS, Windows 10
#7230 
### Expected behavior
`nw.Window.get(window).isKioskMode` should return true/false  based on if kiosk mode is enabled/disabled.
with chrome args `--disable-features=nw2`
```
>nw.Window.get(window).isKioskMode
<false
```

### Actual behavior
```Exception: TypeError: Error in invocation of nw.currentWindowInternal.isKioskInternal(): No matching signature. at NWWindow.get (extensions::nw.Window:562:36) at NWWindow.invokeGetter (<anonymous>:2:14)```

### How to reproduce
In Developer Tools,
`nw.Window.get(window).isKioskMode`

Similarly another window property `isTransparent` throws error.
```Exception: TypeError: Cannot read property 'alphaEnabled' of undefined at NWWindow.get (extensions::nw.Window:557:27) at NWWindow.invokeGetter (<anonymous>:2:14)```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
