### ISSUE TITLE
webxr webvr (chromium 79)

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#7259]
hey guys did you think we can get a update of chromium 79 with
  `"js-flags": "--webxr",`
or 
`"chromium-args": "--webxr",`

https://www.chromestatus.com/feature/5680169905815552

how this work with nwjs?
Any doc somewhere?
Thanks in advance for your awesome work.

**Comment by djmisterjon** [comment]
Edit: woupss i missing the beta 
![image](https://user-images.githubusercontent.com/24865815/70400461-1d755000-19f9-11ea-9726-32add0f247ec.png)
thanks.
BTW your have doc or tips about `webxr` in nwjs it will be cool. :)

**Comment by rogerwang** [comment]
NW will provide whatever Chromium has. Please file another issue if you find anything broken. Thanks.
