### ISSUE TITLE
How to resize node-webkit window to fill dual monitor

### ISSUE THREAD

**Issue by ABA3D** [nwjs/nw.js#7260]
I have a dual monitor setup and I'm developing a desktop app (Windows OS) and trying to resize it to fill both screens, but with no success.

`var winRs = require('nw.gui').Window.get().window;
winRs.resizeTo(
   5120 + winRs.outerWidth  - winRs.innerWidth,
   1152 + winRs.outerHeight - winRs.innerHeight
);`

Any idea or help would be very appreciated.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
Thanks.
