### ISSUE TITLE
NW2: Missing appWindow

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7262]
In NW2 missing appWindow and access to window content.

In NW1 `--disable-features=nw2` works:
```
const win = nw.Window.get();
win.appWindow.id; // window id
win.appWindow.contentWindow; // window content
```

**Comment by panther7** [comment]
Why?

We're using `chrome.runtime` for communication between windows, like `chrome.runtime.connect({ name: win.appWindow.id });`

For me, missing id windows as string, like:
```
nw.Window.open(/*some url/*, { id: win.cWindow.id });
// TypeError: Error in invocation of nw.Window.open(string url, optional nw.Window.CreateWindowOptions options, optional function callback): Error at parameter 'options': Error at property 'id': Invalid type: expected string, found integer.
```

**Comment by rogerwang** [comment]
The `appWindow` is internal and not part of the API in the documentation. So it's subject to change at any time.

**Comment by panther7** [comment]
Sorry, but have you any suggest, how comunicating with (beetween) windows, now ?

Before works via `appWindow.id` and `chrome.runtime`.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
