### ISSUE TITLE
0.43.0 kiosk mode regression

### ISSUE THREAD

**Issue by stackmagic** [nwjs/nw.js#7268]
NWJS Version : 0.43.0
Operating System : Win10

### Expected behavior

Window opens fullscreen

### Actual behavior

Window opens with 640x480

### How to reproduce

We just upgraded to 0.43.0 from 0.42.4 and now kiosk mode appears broken.

Our package.json / window contains:
* toolbar = false
* show = true
* position = mouse
* resizable = false
* always-on-top = true
* kiosk = true

Essentially, I boiled it down to the kiosk property which seems to be ignored in the new version.
Here's a small test repo: https://github.com/stackmagic/nwjs-kiosk-test

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
