### ISSUE TITLE
F12 opens devtools

### ISSUE THREAD

**Issue by keyto123** [nwjs/nw.js#7269]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 42.4 - 43.0
Operating System : Ubuntu 16.4

NWJS Version: 43.0 (didn't test with other versions)
Operating System : Windows

### Expected behavior

Pressing F12 does nothing

### Actual behavior

Devtools opens with a framed blank window

### How to reproduce

Download normal version, open nwjs and press f12

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
