### ISSUE TITLE
Chrome 79 Webview Issues

### ISSUE THREAD

**Issue by matthiasfostel** [nwjs/nw.js#7274]
Posting a link to this Google group thread about an issue of data loss from changes to the Webview code in Chromium 79.

https://bugs.chromium.org/p/chromium/issues/detail?id=1033655&q=component%3AMobile%3EWebView&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by rogerwang** [comment]
Thanks for the link, but I don't think this applies to NW apps, as each app uses its own user data directory. 
Closing for now. Please re-open if this is found in NW.

**Comment by rogerwang** [comment]
btw, the 'webview' in the bug report means the Android webview widget, not the 'webview' tag in DOM.
