### ISSUE TITLE
nwjc evalNWBinModule not working, Uncaught SyntaxError: The requested module does not provide an export named

### ISSUE THREAD

**Issue by lab4quant** [nwjs/nw.js#7275]
NWJS Version : 0.42.6
Operating System : win10 64-bit

### Expected behavior

nwjc compiled binary file should funtion the same as js file

a demo for similar function can be found here: (using the same js file)

https://observablehq.com/@quantlib/random-numbers-and-dimensionality

it loads my js file and plot a chart using d3 library

### Actual behavior

there was no error in nwjc stdout, a v8.log file generated
after loading binary file using `nw.Window.get().evalNWBinModule` then calling function export from js file, error message can be found in console: 

Uncaught SyntaxError: The requested module does not provide an export named

### How to reproduce

1. download js file from: https://cdn.jsdelivr.net/npm/@quantlib/ql@latest/ql.mjs
2. copy `ql.mjs` (from step 1) to nwjs sdk dir and run `nwjc --nw-module ql.mjs ql.bin`
    this step will generate `ql.bin` and `v8.log`
3. create a folder called `toy`, copy `ql.bin` (from step 2), `toy.html` (source provided in below), `package.json` (source provided in below) to it
4. run `nw toy` and check console message

toy.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
      // nw.Window.get().evalNWBin(null, 'ql.bin');
      nw.Window.get().evalNWBinModule(null, 'ql.bin', 'ql.js');
    </script>
  </head>
  <body style="background-color:rgba(0,0,0,0.0);">
    <!--load d3-->
    <script src="https://cdn.jsdelivr.net/npm/d3@latest/dist/d3.min.js"></script>

    <!--d3 scatter plot-->
    <script type="module">
      import {SobolRsg} from './ql.js';

      var margin = {top: 20, right: 20, bottom: 30, left: 40},
      width = 500 - margin.left - margin.right,
      height = 500 - margin.top - margin.bottom;

      //Create a svg element to store the graph in
      var svg = d3.select("body").append("svg")
        .attr("style", "background-color:rgba(0,0,0,0.0);")
        .attr("width" , width + margin.left + margin.right)
        .attr("height" , height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")")
	.style("overflow", "visible");

      //Set up scales that we can use to draw the axes
      var x = d3.scaleLinear()
            .domain([0.0,1.0])
            .range([0,width]);
      var y = d3.scaleLinear()
            .domain([0.0,1.0])
            .range([height,0]);

      //Setting up the axes
      var xAxis = d3.axisBottom().scale(x).ticks(5);

      var yAxis = d3.axisLeft().scale(y).ticks(5);

      //Add the axis to our svg element
      // x-axis
      svg.append("g")
        .attr("class", "x axis label")
        .attr("transform", "translate(" + 0 + "," + height + ")")
        .call(xAxis)
        .append("text")
        .text("x")
        .attr("x", width)
        .attr("y", -6)
	.attr("fill", "currentColor")
        .style("text-anchor", "end");
      // y-axis
      svg.append("g")
        .attr("class", "y axis label")
        .call(yAxis)
        .append("text")
        .text("y")
        .attr("transform", "rotate(-90)")
	.attr("x", 6)
        .attr("y",6)
	.attr("fill", "currentColor")
        .style("text-anchor","end");

      // sobol data set
      var rng = new SobolRsg().init(2); // this is exported from ql.mjs, it's working using js file

      var dataset = [];
      for(var i=0; i<2048; i++) {
        dataset.push(JSON.parse(JSON.stringify(rng.nextSequence().value)));
      }

      svg.selectAll("circle")
        .data(dataset)
        .enter()
        .append("circle")
        .attr("cx", function(d) {
            return d[0]*width;
          })
        .attr("cy", function(d) {
              return d[1]*height;
            })
        .attr("r", 3);
    </script>
  </body>
</html>

```

package.json

```json
{
  "name": "toy",
  "main": "toy.html",
  "window": {
    "min_width": 800,
    "min_height": 600
  }
}
```

**Comment by rogerwang** [comment]
Thanks for reporting. Currently the feature is limited to default exports as shown in the test case: https://github.com/nwjs/nw.js/tree/nw43/test/sanity/module-bin

Supporting the named exports would require some efforts as the export metadata is lost during the compilation -- the binary file contains only code for now.

**Comment by lab4quant** [comment]
@rogerwang, thanks for the reply
did you mean `export { A as B}` is not supported, but `export {A}` is supported?

my lib bundle is created by rollup.js, i also have the uncompressed version (not published)
in which the last statement is like the example you provided `export {A}` 

also, both minimized and unminimized, works with old nwjs version, i remember it was working till 0.37.x

**Comment by rogerwang** [comment]
I can look to fix it if you provide a sample. The test case has been passing in all versions.

**Comment by lab4quant** [comment]
@rogerwang, you mean sample of using uncompressed mjs file? i can't publish that as we do need to protect our code, the published one was processed by `rollup-plugin-terser` and minimized

**Comment by rogerwang** [comment]
Your module has 2107 exports. It's not using default export.

**Comment by lab4quant** [comment]
@rogerwang, my lib is done the same way as [tensorflow.js](https://github.com/tensorflow/tfjs)

i just created a test case for `tfjs`, it works, the export part is same as my lib

1. download https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@1.5.1/dist/tf-core.esm.js
2. nwjc --nw-module tf-core.esm.js tf.bin
3. create folder `tf`, and `package.json` and `tf.html` inside it (source privided below), copy `tf.bin` from step 2
4. run `nw tf`, check console output

package.json:

```json
{
  "name": "tf",
  "main": "tf.html",
  "window": {
    "min_width": 800,
    "min_height": 600
  }
}
```

tf.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
      nw.Window.get().evalNWBinModule(null, 'tf.bin', 'tf.js');
    </script>
  </head>
  <body>
    <script type="module">
      import {tensor1d, softmax} from './tf.js';
      const a = tensor1d([1, 2, 3]);
 
      console.log(a.softmax().print());
      
    </script>
  </body>
</html>

```

**Comment by rogerwang** [comment]
Thanks for your interesting finding. It turns out the initial heap space setting is too small to fix your binary, which is bigger than the TF sample. The following setting in manifest is a workaround as it increase the initial setting:

`"js-flags": "--min_semi_space_size=4",`

**Comment by lab4quant** [comment]
@rogerwang, wow, cool, the `js-flags` setting works perfectly for me
i did packed more stuff into my lib a few month back which passed limit, i guess

will there be a permanent fix? shall i leave the ticket open?

**Comment by lab4quant** [comment]
@rogerwang, i found another issue, `"chromium-args": "--start-maximized"` option stopped working for my case, i tried with latest version 0.43.3
does it have anything to do with js-flags?

**Comment by rogerwang** [comment]
@lab4quant that's #7235 .

For now using the JS flag would be the best option. Closing for now.
