### ISSUE TITLE
document-end Event not fire.

### ISSUE THREAD

**Issue by zhsunlight** [nwjs/nw.js#7276]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.43.1
Operating System : win10 64bit

### Expected behavior

Fire the window's event document-end.

### Actual behavior

document-end Event not fire after open a window.

download 0.43.1 sdk, open nwjs, and listen the window's event document-end.

**Comment by zhsunlight** [comment]
if set --disable-features=nw2, everythings will be right.

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by zhsunlight** [comment]
yes. In this demo app,  I set two event triggered alert, but got one.
[nw2_event_bug.zip](https://github.com/nwjs/nw.js/files/3977243/nw2_event_bug.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by zhsunlight** [comment]
good job. thank you very much.
