### ISSUE TITLE
NW2: win.show() restores window

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7278]
NWJS Version : 0.43.1
Operating System : Windows 10 64-bit

### Expected behavior

Calling `win.show()` after `win.maximize()` should show a maximized window.

### Actual behavior

In NW2 mode, the call to `win.show()` restores the window so it does not appear maximized. With `--disable-features=nw2` it works correctly again.

The setting for window.show in package.json does not appear to affect the issue.

The workaround is easy - just call show() before maximize() - but it's a breaking change in NW2.

### How to reproduce

Minimal repro: 
[window-show-bug.zip](https://github.com/nwjs/nw.js/files/3973268/window-show-bug.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
