### ISSUE TITLE
--disable-devtools Chromium-Arg Stopped Working

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7279]
NWJS Version: v0.43.1
Operating System: Windows 7 SP1
Repro: [DisableDevtoolsTest.zip](https://github.com/nwjs/nw.js/files/3975707/DisableDevtoolsTest.zip)

### Expected behavior
The "--disable-devtools" chromium arg should block F12 key opening and similar ways to access it.

### Actual behavior
The "--disable-devtools" chromium arg is not working as expected anymore. Dev-tools can still be opened by pressing F12 and other methods.

### How to reproduce
1. Download and extract package.nw
2. Run NWjs v0.43.1
3. Notice F12 keys still opening dev-tools

**Comment by Macmachi** [comment]
I have the same problem ! Thanks @TheRealDannyyy

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
