### ISSUE TITLE
Loss of GPU acceleration on linux in 43.1

### ISSUE THREAD

**Issue by itsybitesyspider** [nwjs/nw.js#7281]
NWJS Version :  43.1 (works as expected in 42.3)
Operating System : Linux/Debian 10

### Expected behavior

GPU acceleration should work, with good graphics performance and no error messages in terminal.

### Actual behavior

WebGL performance is poor. Error messages on start, intermixed with other output that seems unrelated:

[23877:23877:1218/222858.401626:ERROR:gl_implementation.cc(282)] Failed to load [path/to/my/project]/libGLESv2.so: [path/to/my/project]/libGLESv2.so: cannot open shared object file: No such file or directory
[23400:23400:1218/221751.532122:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization

### How to reproduce

As far as I can see, opening any nw-js app on Debian 10 should replicate this issue, but please let me know if you not are able to replicate and I'll investigate further.

**Comment by rogerwang** [comment]
Just pushed a fix. The next [nightly build](http://dl.nwjs.io/live-build/) should fix this.

**Comment by rogerwang** [comment]
Please try this build:

https://dl.nwjs.io/live-build/nw43/20191221-162000/7b760f07b/v0.43.3/

**Comment by Vehmloewff** [comment]
@rogerwang, would you mind explaining how can I install this specific build?  `npm install nw@sdk` is still at `0.43.2`.

**Comment by itsybitesyspider** [comment]
Works for me.

**Comment by rogerwang** [comment]
@Vehmloewff currently the `nw` package doesn't support nightly build.

**Comment by Vehmloewff** [comment]
Ah, thanks.
