### ISSUE TITLE
WebGL out of memory + context lost

### ISSUE THREAD

**Issue by marcgfx** [nwjs/nw.js#7283]
Happens in 33.3 and in 43.1 (rarely)

This will probably be a tough one to answer/solve, as I can not find any good resources online. 

While testing my project I never come across the problem in chrome, but when starting from NWjs both issues (out of memory/context lost) have happened multiple times. Out of memory happens on start up leading to a black screen (black webgl canvas, everything else works though). Restarting solves the problem.

I can't consistently reproduce the behavior. Context lost mostly happens if I switch to another app and do visual intensive stuff. I do have a solution for context lost, but losing context still sucks. I have to reset the textures and lose my frame buffers.

Is there a way to allocate GPU memory and prevent it from being grabbed by another application?

**Comment by marcgfx** [comment]
This probably wont help much. Still trying to find out if I can do anything about it, or am actually causing the problem. It does look like the main reason I am running into this is a very large canvas. This question might just be out of scope for NWjs, but it does not happen in the browser for some reason.

[.WebGL-000000000E0267C0] GL_OUT_OF_MEMORY: Error allocating Texture2D. HRESULT: 0x8007000E
255[.WebGL-000000000E0267C0] GL_OUT_OF_MEMORY: Context has been lost.
game.html?param=DevaderR_1_PUP_0&F11=1&test=1:1 [.WebGL-000000000E0267C0] GL_OUT_OF_MEMORY: Context has been lost.
game.html?param=DevaderR_1_PUP_0&F11=1&test=1:1 [.WebGL-000000000E0267C0] GL_OUT_OF_MEMORY: Context has been lost.

**Comment by rogerwang** [comment]
Maybe it would help to find whether there is any leaks of the JS objects with the heap profiler in devtools.

**Comment by marcgfx** [comment]
I might be understanding this incorrectly, but I assumed this is related to graphic card memory (VRAM). Or is this a simple out of memory error (not enough RAM)?
If it is related to VRAM I doubt I could see anything in the heap profiler, but I have to admit I have not extensively used that tool.
I have been able to mitigate the issue by using a smaller canvas, but I should probably try to investigate further.

**Comment by rogerwang** [comment]
Some JS objects could be backed by VRAM resources.

closing for now until there is more information. Thanks.
