### ISSUE TITLE
[NW2] Regression in window sizing

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7284]
NWJS Version : 0.43.1
Operating System : Windows 10 64-bit

### Expected behavior

Setting a window size in NW2 should set the same size as before

### Actual behavior

Setting the same size produces a different window size in NW2 mode

### How to reproduce

Minimal repro: [nw2-window-size.zip](https://github.com/nwjs/nw.js/files/3983553/nw2-window-size.zip)

This just sets the window size to 500x500.

Using alt+printscreen and pasting in to image editor to get the overall window size:
By default (with NW2): window size is 486x493
With --disable-features=nw2: window size is 502x528

**Comment by TheRealDannyyy** [comment]
Would appreciate a fix before the NW1 removal (#7230).

**Comment by rogerwang** [comment]
Will look into it soon.

btw, I recently clarified the setting of inner/outer dimension if the window: https://github.com/nwjs/nw.js/commit/9ea89729a3fa928735e8c7530728bcb554656f2e#diff-e3e2a9bfd88566b05001b02a3f51d286
So the behaviour would be different with NW1.

**Comment by rogerwang** [comment]
In your test case it's setting the outer dimension of the window, which is actually correct set (see the attached screenshot). The window under windows has a thick invisible resize handle. For the sake of cross-platform consistent application behaviour I suggest setting the inner dimension of your application's window, which is the size of the DOM window area.

<img width="656" alt="windowsize" src="https://user-images.githubusercontent.com/165401/71537930-0e315480-295e-11ea-9ece-c36e92609f30.png">

See also the upstream code here for the thick resize handle: https://cs.chromium.org/chromium/src/chrome/browser/ui/views/frame/glass_browser_frame_view.cc?rcl=9db6c8c8e3374ea24d5705672a7a33d26cb6be37&l=358

**Comment by rogerwang** [comment]
closing for now as it's working as expected.

**Comment by AshleyScirra** [comment]
> I suggest setting the inner dimension of your application's window, which is the size of the DOM window area.

How do we do that? I'm not aware of an API for that - the NW.js Window API appears to only specify one size, which according to your comment, is now the outer size.

**Comment by rogerwang** [comment]
The inner dimension can be set via `Window.resizeTo()` or the manifest as described by the documentation. Thanks.

**Comment by AshleyScirra** [comment]
Using resizeTo() seems buggy - I filed #7303 for that.
