### ISSUE TITLE
nw2: frameless app no longer have resize handle

### ISSUE THREAD

**Issue by Sombian** [nwjs/nw.js#7286]
NWJS Version : latest (nw-v0.43.2)
Operating System : windows 10 pro

### Expected behavior

app should have resize handle on each sides.

### Actual behavior

app no longer have resize handle on nw2 but nw1.

### How to reproduce

at `manifest`
set frame to false
start an app
try resize

side-node: theres a bug where restore add 14 pixels to both width and height on frameless (nw2 dont have this issue but nw1)

**Comment by Sombian** [comment]
How could this issue abandoned for this long? How could of?

**Comment by Dimtime** [comment]
I know why: few hands to solve all problems.
This often happens with non-profit projects that are developed simply on the basis of enthusiasts.
The creators of project are great, but for more growth - maybe need another methods...

**Comment by rogerwang** [comment]
CC #7230

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
