### ISSUE TITLE
nwjs43 build not generating

### ISSUE THREAD

**Issue by meraj321** [nwjs/nw.js#7287]
Hi,

I am trying to build nwjs version 43 buils it is giving me error (please see attached error 
<img width="590" alt="Capture" src="https://user-images.githubusercontent.com/44696730/71303805-d23d4300-23e3-11ea-998e-9b5357a954fe.PNG">
)while applying the patches.

Please assist.

**Comment by rogerwang** [comment]
Looks like the checked out commit is incorrect. 
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
