### ISSUE TITLE
nw.exe fails to run on windows xp

### ISSUE THREAD

**Issue by lover2668** [nwjs/nw.js#7290]
1 I downloaded nwjs 0.43.2 version, but on windows
  Click on xp to open nw.exe failed

======== TEMPLATE BUG FORM ========

NWJS Version :  0.43.2
Operating System :  windows XP  64bits

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->
![windowsXP64bit](https://user-images.githubusercontent.com/14230924/71566210-b1b26e80-2af0-11ea-980a-e1689a3cecb1.png)

**Comment by rogerwang** [comment]
The LTS version supports XP

**Comment by lover2668** [comment]
Can you help provide a download link for nwjs version that supports XP?
