### ISSUE TITLE
NW2: Event navigation get not fired

### ISSUE THREAD

**Issue by user321321** [nwjs/nw.js#7294]
NWJS Version : v0.43.3
Operating System : Windows 10

### Expected behavior
When I navigate to another page, the event should be triggered and the call should be prevented.
For example when clicking on a Link like google.

### Actual behavior
Event is not triggered.
If I add "chromium-args": "--disable-features=nw2" in package.json, the Event is triggered.

### How to reproduce
main.js

> nw.Window.open('index.html', {}, function(win) {
> 	win.on('navigation', function (frame, url, policy) {
> 		console.log("navigation called: " + url); 
> 		policy.ignore();
> 	});
> });

index.html
`<a href="https://www.google.de">Click</a>`

**Comment by user321321** [comment]
If i add 
`"chromium-args": "--disable-features=nw2",`
in the package.json, then the event gets fired.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by malixsys** [comment]
Still occurs for me in 0.43.6-sdk
```
      nw.Window.open(
        url,
        {
          width: self.options.width,
          height: self.options.height,
          position: 'center',
          focus: true
        },
        function(win) {
          debugger;
          win.on('navigation', function (frame, url, policy) {
            console.log("navigation called: " + url);
            policy.ignore();
            win.showDevTools()
          });
//...
```

**Comment by rogerwang** [comment]
@malixsys  Could you please provide a full sample (not code snippets) so we can reproduce? 

And does our test case work for you? https://github.com/nwjs/nw.js/tree/cfc9ada0081d2ff4008d250f6ea238584f4216b3/test/sanity/issue7294-navigation
