### ISSUE TITLE
cannot load local files in webview loaded with loadDataWithBaseUrl

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7295]
NWJS Version : from 0.41.0 till 0.43.3
Operating System : Windows 10

### Expected behavior

When loading a webview with loadDataWithBaseUrl and giving it a file:/// url as base url, all local links in it should be loaded normally.

### Actual behavior

Starting from NWJS 0.41.0 an error occurs when loading the links and script files:
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME

![unknown_url_scheme_bug](https://user-images.githubusercontent.com/504730/71700521-d5add280-2dc4-11ea-808e-48914c566720.png)

### How to reproduce

Load the following sample:

[webview_local_files.zip](https://github.com/nwjs/nw.js/files/4017794/webview_local_files.zip)

Place the files localfile.html and jquery-3.3.1.min.js in c:\test\webview folder

the localfile.html is read and included with loadDataWithBaseUrl and its base is set to file:///c:/test/webview/

However the jquery include gives an error net::ERR_UNKNOWN_URL_SCHEME when it is loaded.
This works all fine in NWJS 0.40 and lower

@rogerwang - hope you can solve this - as otherwise webviews are unusable for us with this bug.

**Comment by rogerwang** [comment]
<img width="748" alt="bug" src="https://user-images.githubusercontent.com/165401/71762703-c0908b00-2f0d-11ea-8713-556b5233b1c1.png">

I tried your sample but it works for me with 0.43.3.

**Comment by gpetrov** [comment]
To see the error you need to right click on the webview and open its devtools inspector. There you will see it. 

Just tested it again and it shows the unknown url scheme error on the jquery include also on 0.43.3

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
A nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200105-162000/69c924066. Please try it.

**Comment by gpetrov** [comment]
Thanks a lot! Problem is now solved in the nightly build!
