### ISSUE TITLE
NW doesn't quit without open window

### ISSUE THREAD

**Issue by keyto123** [nwjs/nw.js#7298]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 35.4 42.6 43.3
Operating System : Linux / Windows

### Expected behavior

App quits when nw.App.quit() is called

### Actual behavior

Process stay open and doesn't quit

It may be killing the wrong process as nw.App.quit() kills an exe process while the main process is an nw process

### How to reproduce
package.json
`{
    "name": "test",
    "main": "./test.js"
}
`

test.js
`nw.App.quit();`

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
