### ISSUE TITLE
nw2: Sometimes timers won't run when running the app in background

### ISSUE THREAD

**Issue by cyantree** [nwjs/nw.js#7301]
NWJS Version : 0.43.3
Operating System : Win 10 Pro 1903

Since switching to `nw2` it seems apps may get unresponsive when staying in the background. This affects timers but also global hotkeys. A bit below you'll find a simple example that hopefully helps reproducing the issue.

- It doesn't seem to happen (as often?) when simply using other non-fullscreen applications in the foreground
- It doesn't happen anymore when disabling `nw2`
- The flags `--disable-raf-throttling --disable-background-timer-throttling` don't seem to make a difference

### Expected behavior

- Timer/requestAnimationFrame continue to run

### Actual behavior

- Timer/requestAnimationFrame suddenly stop and only continue to run when app gains focus again

### How to reproduce

[nw-background-test.zip](https://github.com/nwjs/nw.js/files/4023472/nw-background-test.zip)

- Extract and run the above sample
- Wait a minute and check for the log files to be updated
- Start a fullscreen application (if possible some game) and wait a few minutes
- Have a look at the log files: If the problems occurs they haven't been updated regularely but only when you focus on the sample again

**Comment by elpeleq42** [comment]
same happens here in a project of mine(a game server). After a bit of being minimized, the bots it controls start moving less times per second(which I presume to be related to the fact that they're controlled by a function that runs inside a setInterval)

**Comment by rogerwang** [comment]
@cyantree unfortunately your sample works for me -- it gives steady output while I was playing a fullscreen movie. I tried another sample and it works well too: https://jsfiddle.net/Daniel_Hug/pvk6p/

**Comment by rogerwang** [comment]
Though I can not reproduce this, I just fixed an issue which could help on this #7297 . Wait for the next nightly build and see if it works for you.

**Comment by cyantree** [comment]
Thanks for the build. I'll try it and get back to you.

**Comment by cyantree** [comment]
I've tried the new build both in my sample and my real world application. I couldn't reproduce the issue. :) So it seems the fix also affected this issue. @elpeleq42 Does it also work for you app?
Thanks @rogerwang !
