### ISSUE TITLE
Is support of native chrome apps broken?

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7302]
NWJS Version : 0.43.3
Operating System : Windows 10

I've downloaded sample from here https://github.com/GoogleChrome/chrome-app-samples/ (any) and put it to "package.nw" folder. And when I run nw.exe nothing is happening. If I rename "manifest.json" to "package.json" everything works. That's strange.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200107-162000/36d4d26c4
