### ISSUE TITLE
[NW2] Issues using resizeTo() as replacement for assigning window width/height

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7303]
NWJS Version : reproduces in 0.43.1 & 0.44.0-beta1
Operating System : Windows 10 x64

### Expected behavior

Be able to use win.resizeTo() as a replacement for assigning window width and height in NW2 (as suggested in #7284).

### Actual behavior

In NW2 mode, window.resizeTo() is buggy when used as a replacement for assigning the window width and height. There are two issues:

- Using two calls to resizeTo() to set the width then the height causes only the height to be set. The width is lost. This is important for backwards compatibility, e.g. if calling code sets the size via separate width and height setters in calling code, which matches the old API.
- Each call to resizeTo() actually changes the position of the window as well. The window position ought to stay the same size.

### How to reproduce
 Minimal repro:
[nw2-resizeto-issues.zip](https://github.com/nwjs/nw.js/files/4025772/nw2-resizeto-issues.zip)

Click "Resize" button.
Expected: window inner size to read 600x600; window position to stay in the same place
Observed: window inner size reads 484x600 (only height was set); window position moves to left

**Comment by rogerwang** [comment]
I just fixed the issue of window moving left, and added setInnerWidth() and setInnerHeight() for this. The resizeTo() function is asynchronous so you are seeing the effect of not resizing one of the dimensions. 
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by AshleyScirra** [comment]
Thanks!

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200106-162000/12ca14bfd

**Comment by AshleyScirra** [comment]
Thanks, looks like it's all working correctly there now with the new methods.
