### ISSUE TITLE
win.window is undefined after navigation to remote url

### ISSUE THREAD

**Issue by hrocha1** [nwjs/nw.js#7304]
NWJS Version :  v0.44 (build https://dl.nwjs.io/live-build/nw44/20200105-101210/87f3a0d70)
Operating System : Windows 7

### Expected behavior

I should be able to get corresponding DOM window object even after navigating to remote url.

### Actual behavior

The win.window property is undefined after navigation to remote url (it works fine with local files).

### Code

**main.js**
```
var fs = require('fs');
var log = fs.createWriteStream("log.txt", { "flags": "w" });

nw.Window.open('test.html', {}, function (win) {
    win.on("loaded", function () {
        if (win.window) {
            log.write("window object exists \n");
        } else {
            log.write("window is undefined \n");
        }
    });
});
```

**package.json**
```
{
  "name": "winwindowtest",
  "main": "main.js"
}
```

**test.html**

```
<a href="test2.html">test2.html</a>
<a href="https://www.example.org">https://www.example.org</a>
```

**test2.html**

```
<html>
<head>
    <title>test2.html, local file</title>

</head>
<body>
    test2.html
</body>
</html>
```

### How to reproduce

1. Unpack the attached zip to a directory and run nw.exe against it.

[issue2.zip](https://github.com/nwjs/nw.js/files/4026332/issue2.zip)

2. Click on the https://www.example.org link

3. The log.txt file should look like this

```
window object exists 
window object exists 
```

but it looks like this

```
window object exists 
window is undefined  

```
because the win.window object is undefined after navitation to remote url.

If you do the same thing with local file (via the test2.html link) it works as expected.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next build.

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200107-162000/36d4d26c4

**Comment by hrocha1** [comment]
@rogerwang works for me, thanks
