### ISSUE TITLE
Uncaught TypeError: chrome.send is not a function

### ISSUE THREAD

**Issue by phpjungle** [nwjs/nw.js#7307]
How can I use the chrome extension API 'chrome.send' in NW.JS @see [chrome.send](https://chromium.googlesource.com/chromium/src.git/+/master/docs/webui_explainer.md#chrome_send)

I want to enable `audio debug recordings` in WebRTC without [[chrome://webrtc-internals]](chrome://webrtc-internals) . Is there a way to call  `chrome.send('enableAudioDebugRecordings')`  in NW.JS ? 🥺🥺🥺

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
