### ISSUE TITLE
Again fullscreen option in package.json not working 

### ISSUE THREAD

**Issue by hooker99** [nwjs/nw.js#7308]
NWJS Version : 0.43.3 (32/64 bit + sdk)
Operating System : Windows 10

Expected behavior
Setting the "fullscreen" option in the manifest file to true should cause the application to start in fullscreen.

Actual behavior
Setting the "fullscreen" option in the manifest file to true doesn't have any effect, the application starts in a regular window.

How to reproduce
Create the following 2 files and run them as an NW.js application:

package.json:

{
	"name": "fullscreen test",
	"main": "index.html",
	"window": {
		"title": "Window Title",
		"fullscreen": true
	}
}
index.html:

<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<p>Hello, World!</p>
	</body>
</html>
NOTE: The fullscreen option appears to work fine in older NW.js versions (e.g. v0.35.3).

NOTE2: Kiosk mode working OK

**Comment by rogerwang** [comment]
Does `--disable-features=nw2` make any difference there?

**Comment by TheRealDannyyy** [comment]
I'm testing this on Windows 7 and it doesn't even show any window at all. NWjs just ends up running in the background and I have to manually kill the process. With "--disable-features=nw2" it runs as expected but fullscreen isn't working with it either.

Here for reproduction: [Fullscreen Test.zip](https://github.com/nwjs/nw.js/files/4031740/Fullscreen.Test.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200108-082915/e10a3835d
