### ISSUE TITLE
NW2: Users can manually zoom using ALT/CTRL + Mousewheel 

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7309]
NWJS Version: All since NW2 Release. Tested With latest SDK.
Operating System: Windows 7 SP1
Repro: [Manual Zoom Test.zip](https://github.com/nwjs/nw.js/files/4031785/Manual.Zoom.Test.zip)

### Expected behavior
Manually zooming using ALT/CTRL + Mousewheel should be blocked by default.

### Actual behavior
Users can manually zoom using ALT/CTRL + Mousewheel. Doesn't happen in NW1 mode.

### How to reproduce
1. Download and extract package.nw
2. Run in latest NWjs with NW2 enabled
3. Notice ALT/CTRL + Mousewheel is zooming (blurry text as a result)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200108-082915/e10a3835d
