### ISSUE TITLE
chrome.app.window.getAll() causes "No current window" error

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7310]
NWJS Version : 0.43.4
Operating System : Windows 10

I've used calculator sample https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/calculator, but issue exists for all chrome apps.

If you open DevTools and type `chrome.app.window.getAll()` you will get en error 

```
(unknown) Uncaught Error: No current window
    at extensions::nw.currentWindowInternal:4:24
    at new NWWindow (extensions::nw.Window:76:44)
    at extensions::nw.Window:653:23
    at extensions::app.window:227:31
    at Array.map (<anonymous>)
    at extensions::app.window:225:19
    at <anonymous>:1:19
```

https://yadi.sk/i/t1Q-L5kJINkH-A

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200108-082915/e10a3835d
