### ISSUE TITLE
nw2: methods to set window icon have different "priority" than in nw1

### ISSUE THREAD

**Issue by hrocha1** [nwjs/nw.js#7311]
NWJS Version : v0.43.4
Operating System : Windows 7

I'm not sure if this is actually bug or intended change.

**nw1 window has priority order for setting window icon as follows**

1. nw.Window.open options parameter (HIGHEST priority)
2. package.json setting in window.icon
3. default NW.js icon
4. link rel="icon", taken from html page you open in the window (NEVER USED)

**nw2 window has priority order for setting window icon as follows**

1. nw.Window.open options parameter (HIGHEST priority)
2. link rel="icon", taken from html page you open in the window
3. package.json setting in window.icon
4. default NW.js icon (if everything above is empty)
 

This means that your application icon can change in nw2 compared to nw1 if you rely on package.json setting and open html pages with link rel="icon" element.

I can provide some test files to reproduce this change if this is indeed a bug and not an intended change.

**Comment by rogerwang** [comment]
Thanks for reporting. The nw1 behavior is a bug and it's expected in NW2.
