### ISSUE TITLE
nw2: poor Window icon quality if you use package.json or link rel="icon"

### ISSUE THREAD

**Issue by hrocha1** [nwjs/nw.js#7312]
NWJS Version : v0.44.0-beta1
Operating System : Windows 7, Windows 10

### Expected behavior

Window icon quality shouldn't depend on what method you use to set icon.

### Actual behavior

If you set icon via `package.json` or `<link rel="icon"` it (probably?) gets resized to 16x16 image and then it's used. This doesn't happen if you set the icon via `nw.Window.open` option.

![image](https://user-images.githubusercontent.com/8612911/72086300-f4512380-3306-11ea-8aac-6636a4a6a7e3.png)

### How to reproduce

1. Unpack the attached zip to a directory and run nw.exe against it.

[issue6.zip](https://github.com/nwjs/nw.js/files/4041428/issue6.zip)

2. You should be able to see different icon quality even though the same image is used in all cases.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200111-162000/313556b99

**Comment by hrocha1** [comment]
works for me, thanks
