### ISSUE TITLE
NW2: Window geometry is not remembered after close

### ISSUE THREAD

**Issue by OsamaAbbas** [nwjs/nw.js#7314]
NWJS Version :
>  nw.js v0.43.4
>  Node v13.5.0
>  Chromium 79.0.3945.117
>  commit hash: `e10a383-d20850e-2c167b7-37b2573`

Operating System :
>  LinuxMint 19.x

### Expected behavior
  When using "id" subfield, the app should remember its geometry in later launches.

### Actual behavior
  It's lost unless you disable nw2.

### How to reproduce

Put this file `package.nw/package.json` inside nwjs directory:

```json
{
  "name": "DisneyLOL",
  "main": "https://lol.disney.com/games",
  "window": {
    "id": "DisneyLOL",
    "title": "Disney LOL Games"
  }
}
```

Run the app using `./nw`, resize the app and close it. Next time it will not remember its resized geometry.

Run the app using `./nw --disable-features=nw2`, it will remember it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200112-162000/425569548
