### ISSUE TITLE
InitializeSandbox() called with multiple threads in process gpu-process

### ISSUE THREAD

**Issue by loveencounterflow** [nwjs/nw.js#7316]
I have an old app I wrote on OSX about five years ago or so. I thought I wanted to get the thing running again, but this time on Linux (Mint 19.1) so I pulled all the sources and gave it a try. Needless to say, the OSX binary won't run on Linux, so I downloaded the latest `nwjs` (SDK version as the other doesn't have devtools, right?). I didn't change the app layout or any sources in any way; I just did

```bash
nwjs-sdk-v0.43.4-linux-x64/nw ./mingkwai.app/Contents/Resources/app.nw
```

and kept my fingers crossed. What I do get is this output:

```bash
DevTools listening on ws://127.0.0.1:10138/devtools/browser/1865f5b1-23c2-4c87-9301-92217c6d93c6
[20265:20265:0111/225507.341499:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

*After* that there are some debugging messages that are my own doing (so at least part of the app is indeed still running despite the error message); however, no GUI is shown and the process just idles without terminating.

Before getting into serious debugging, could you please help me out with a few questions:

* I can certify that the same code still runs on OSX in its unmodified form because I just tried that; given this knowledge, can I just have the Linux version run the same app with the same layout by only swapping the `nw` executable? I also get a `Failed to parse extension manifest.` so I guess I'm missing or misplaced some file.

* Where does that multiple threads error occur and why? How can I get rid of it? I realized it occurs regardless of which argument I pass to `nw`; I also tried with the `npm -gi nw` version which gives me the same. This does make it look like it's completely unrelated to my code.

**Comment by rogerwang** [comment]
The error message you see is not fatal and yes the application package should be cross platform.

**Comment by loveencounterflow** [comment]
OK that pretty much closes this (except for the why). Quick question though: If the error was nonconsequential shouldn't I be seeing a browser window opening? The original app is still working but of course there's years in between so maybe an important part of the API has changed? Any ideas?
