### ISSUE TITLE
怎么实现类似Chrome的图片右键菜单

### ISSUE THREAD

**Issue by zhangdp** [nwjs/nw.js#7318]
在chrome里右键点击图片会弹出菜单，可以复制另存为等等，请问在nwjs里如何实现这个菜单？或者怎么复制图片也可以。
![image](https://user-images.githubusercontent.com/26567414/72244111-823f4e00-3628-11ea-92c7-1e36d3964423.png)

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
And please use English in this project so all users can read.
