### ISSUE TITLE
`window.open` does not load `inject_js_start` or `inject_js_end` when opening the page.

### ISSUE THREAD

**Issue by kevinkenken** [nwjs/nw.js#7320]
NWJS Version :0.43.5
Operating System :window

### Expected behavior

`window.open`  loads `inject_js_star` or `inject_js_end` when opening the page.

### Actual behavior

 `window.open` does not load `inject_js_star` or `inject_js_end` when opening the page, the new window `"position": "center"` does not work and sometimes cannot be closed.

### How to reproduce
using nw2

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by kevinkenken** [comment]
[package.nw.zip](https://github.com/nwjs/nw.js/files/4070361/package.nw.zip)

**Comment by rogerwang** [comment]
You can try to pass `inject_js_start` and `inject_js_end` as parameter of `nw.Window.open`. See an example here: https://github.com/nwjs/nw.js/blob/nw44/test/sanity/issue4286-inject-start-end/index.html

**Comment by rogerwang** [comment]
btw, I also tried the scenario that the 2 options are in `package.json` and they are applied to `nw.Window.open` correctly: https://github.com/nwjs/nw.js/tree/nw44/test/sanity/manifest-default-inject

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by kevinkenken** [comment]
After the ‘nightly build’ test, the above 2 options were resolved. However,`position` was not inherited, and `nw1` was inherited.

**Comment by rogerwang** [comment]
The `position` field in manifest should not be inherited as described by the document: http://docs.nwjs.io/en/latest/References/Manifest%20Format/#window-subfields

**Comment by rogerwang** [comment]
In NW1, the `position` field is not inherited either. It's just that the default position is centered in NW1.
