### ISSUE TITLE
NW2: User Window Metrics Not Saved/Respected

### ISSUE THREAD

**Issue by rdtsc** [nwjs/nw.js#7322]
### Environment

- **NW.js Versions**: 0.43.6 and 0.44.0 - reproducible on tag/nightly SDK/non-SDK builds.
- **Nightlies Tested**: 20200117-051334 and 20200117-162000, respectively.
- **Tested Operating Systems**: Linux (x64) and Windows 10 (x64).
- **Related Issues**: #7230

### Expected Behavior

NW2-mode windows should remember their last position and size upon launch.

### Actual Behavior

NW2-mode windows (with `window.id`) don't remember their last position and size upon relaunching NW. Windows are spawned at `(0, 0)` on the primary display with the initial size as specified in the package manifest.

A non-null `window.position` in the manifest is honored, though, it obviously has no effect on the initial size.

#### Manifest Bundle
[nw1-nw2-manifests.zip](https://github.com/nwjs/nw.js/files/4078322/nw1-nw2-manifests.zip)

#### Demo (click for full size)
![issue-capture](https://user-images.githubusercontent.com/6773893/72637053-67bdeb00-392e-11ea-85b4-5667cec8b3b2.gif)

#### NW1 Manifest
```json
{
  "name": "nwjs-window-position-history-nw1",
  "version": "1.0.0",
  "main": "data:,NW1 - OK",
  "chromium-args": "--disable-features=nw2",
  "window":
  {
    "id": "main",
    "width": 640,
    "height": 480
  }
}
```

#### NW2 Manifest
```json
{
  "name": "nwjs-window-position-history-nw2",
  "version": "1.0.0",
  "main": "data:,NW2 - Fail",
  "chromium-args": "",
  "window":
  {
    "id": "main",
    "width": 640,
    "height": 480
  }
}
```

**Comment by rogerwang** [comment]
Thanks for reporting. There was a fix for #7314 but it didn't cover this case.

**Comment by rdtsc** [comment]
> Thanks for reporting. There was a fix for #7314 but it didn't cover this case.

My apologies for missing such a fresh issue. I just eyeballed #7230 and didn't immediately see anything similar prior to filing this ticket.

Many thanks for your continued support of this project.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rdtsc** [comment]
Thanks for the quick patch.

FYI, I tested this against v0.44.0's 20200118-162000/efb396e87 build and yesterday's fix seems to have resolved the window position issue only when the last state of the window is not maximized.

If the window is closed while it's maximized, it's restored in an incorrect position and with an incorrect size. Moreover, the original window size (pre-maximized) does not seem to be respected upon window restore.

In NW1 mode, everything works as expected. If a window is closed while it's maximized, it's restored to the maximized state upon launch and the window's title bar restore control restores the window to the previous geometry as well. This is not the case in NW2 mode.

### Failing Behavior - NW2 (click for full size)
![capture](https://user-images.githubusercontent.com/6773893/72668205-6524c980-39f2-11ea-9e36-becc89e19ca5.gif)

### Expected Behavior - NW1 (click for full size)
![capture2](https://user-images.githubusercontent.com/6773893/72668283-3bb86d80-39f3-11ea-945c-b9351fc53417.gif)

### Manifests

Pretty much the same as the ones in the original issue.

#### NW2 - Failing Behavior
```json
{
  "name": "nwjs-window-position-history-nw2-7322-test",
  "version": "1.0.0",
  "main": "about:blank",
  "window":
  {
    "id": "main",
    "width": 640,
    "height": 480
  }
}
```

#### NW1 - Expected Behavior
```json
{
  "name": "nwjs-window-position-history-nw1-7322-test",
  "version": "1.0.0",
  "main": "about:blank",
  "chromium-args": "--disable-features=nw2",
  "window":
  {
    "id": "main",
    "width": 640,
    "height": 480
  }
}
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw44/20200119-184735/a8c4ae39c

**Comment by rdtsc** [comment]
Unable to reproduce this issue on the latest linux/win x64 nightlies. Thanks again for the quick fix!
