### ISSUE TITLE
‘nw2’ Sometimes the window cannot be closed

### ISSUE THREAD

**Issue by kevinkenken** [nwjs/nw.js#7326]
NWJS Version : 43.6
Operating System :window

### Expected behavior

close the window

### Actual behavior

Cannot close window

### How to reproduce
This was discovered during debugging and related to the user cache.

First in the `nw.window.open ()` callback `win.on ('close', function () {this.close (true);})`,Run and close the program;

Then I found in the "User Data/Default/Secure Preferences" file
![477ec1207a7f8b51eb2dbd80743203d](https://user-images.githubusercontent.com/38520455/72692141-3ed36b00-3b65-11ea-9553-b8f4e148b655.png)
As above;

Then comment `win.on ('close')`,Run the program and cannot close at this time.

Multiple tests have found that as long as the callback of `nw.window.open` contains `win.on ('close')`,` instanceId` will be added to the above cache file. If ‘nw.window.open’ is used dynamically (with or without `win.on ('close')`), there is a chance that the same 'instanceId' will cause `window` to not be closed.

**Comment by kevinkenken** [comment]
[package.nw.zip](https://github.com/nwjs/nw.js/files/4084147/package.nw.zip)
Please run it first and comment ‘win.on ('close') ’

**Comment by rogerwang** [comment]
I don't think you are using the API correctly -- if you attach the `close` event handler, the window should be closed by `Window.close(true)` in it.

**Comment by rogerwang** [comment]
closing until there is more information.

**Comment by kevinkenken** [comment]
I mean: After calling the `close` event normally, when I remove it in the code and open the program again, the` window` of `nw.window.open` cannot be closed.

**Comment by rogerwang** [comment]
How did you call the `close` event?

**Comment by kevinkenken** [comment]
OK, I'll provide it in about 15 hours. Now I'm going to have a rest.

**Comment by kevinkenken** [comment]
![video](https://user-images.githubusercontent.com/38520455/72858762-d4edc980-3cfc-11ea-8553-7be093711c2c.gif)

[Secure Preferences.zip](https://github.com/nwjs/nw.js/files/4094904/Secure.Preferences.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
