### ISSUE TITLE
NW2 issue : evalNWBin is buggy

### ISSUE THREAD

**Issue by josh83abc** [nwjs/nw.js#7331]
I found out, after 2 hours of debugging, that evalNWBin doesn't work well with NW2 and was working fine with NW1.

My code in the background / launcher page : 

```
nw.Window.open("http://localhost:8082/index.html", {width:400, height:300}, function(win) { 
	win.evalNWBin(null, "mycode.bin");
});
```

Problem : The evalNWBin produces Javascript error in my code related to the fact the DOM is not accessible. I tried everything to make it work. It works well with NW1.

But if in my index.html I call, nw.Window.get().evalNWBin(null, "mycode.bin"); it works fine.

I noticed that the "win" object returned by nw.Window.open gives not the same info than nw.Window.get() in the index.html.

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by rogerwang** [comment]
close until more information is available.

**Comment by josh83abc** [comment]
Hello Roger!

I have updated my app recently with the latest NWJS (47.2) and I saw that I still get an error while loading my V8 snapshot with NW2! It only works with NW1 but since you plan to remove it, I have a problem :D

Error handling response: TypeError: Cannot read property 'createElement' of undefined
    at ce (<anonymous>)
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at <anonymous>
    at NWWindow.evalNWBinInternal (extensions::nw.Window:472:20)
    at NWWindow.evalNWBin (extensions::nw.Window:453:8)
    at chrome-extension://jklhobfmppcchocjfekhndilpodhlnob/release/background.js:4:6
    at extensions::nw.Window:799:13

I made a video to show the problem here : https://you.dj/evalbin_nw2_bug.mp4

Also here is the test project used in the video : https://you.dj/evalbin_nw2_bug.zip

Image of the error : https://you.dj/evalbin_nw2_bug.png

As I said in the video, I tried to do a simple code snippet but I didn't get this error. The error is only with with my app. Since my app code is quite large, it is hard to identify the line of code which triggers the evalnwbin error, but I assume you can debug better than me.
