### ISSUE TITLE
Recent change on nwfaketop broke my app

### ISSUE THREAD

**Issue by josh83abc** [nwjs/nw.js#7333]
I have a problem with this change introduced in v0.43.5 : https://github.com/nwjs/nw.js/issues/7305

In my app I am embedding Youtube videos (the normal way, in iframe) and I was using the flags _nwdisable_ and _nwfaketop_ just in case but since v0.43.5 video doesn't load anymore.

`<iframe type="text/html" allow="autoplay" nwdisable nwfaketop width="400" height="300" src="https://www.youtube.com/embed/QYh6mYIJG2Y" frameborder="0"></iframe>`

Removing _nwfaketop_ solve the issue but it breaks the previous behavior so I think it is a bug.

Let me know :)

**Comment by rogerwang** [comment]
Fixed in #7448 . Thanks.
