### ISSUE TITLE
Cancelling file input dialog also cancels HTML dialog element

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7334]
NWJS Version : 0.43.6
Operating System : Windows 10 x64

### Expected behavior

Cancelling a file dialog created by `<input type="file">` should have no effect on HTML `<dialog>` elements

### Actual behavior

Cancelling a file dialog also cancels a showing modal `<dialog>` element

### How to reproduce

Minimal repro: [nw-file-cancel-bug.zip](https://github.com/nwjs/nw.js/files/4097261/nw-file-cancel-bug.zip)

1. Click 'Show dialog'
2. In the dialog that appears, click 'Choose file'
3. Cancel the file picker

Expected: `<dialog>` to remain showing
Observed: `<dialog>` is also closed

If you try the repro in Chrome, it works correctly. So this issue is specific to NW.js.

**Comment by rogerwang** [comment]
It works for me with the latest nightly: http://dl.nwjs.io/live-build/nw44/

**Comment by AshleyScirra** [comment]
Yes, you're right, it seems fixed there.

**Comment by padcom** [comment]
I wonder if you could re-check this. I have a similar situation in Google Chrome where cancelling the file input dialog if there was nothing pre-selected causes the wrapping dialog to automatically close.

It doesn't happen when there was something pre-selected. It then clears out the output (is that the way to reset the field?), closes the file selector popup and leaves the dialog visible. Essentially, if there was nothing preselected and you cancel it, that propagates upwards and closes the dialog.

Doesn't happen on Firefox... I think I'm going to have to report that to chromium project

**Comment by padcom** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1464911 (for reference)
