### ISSUE TITLE
Can't activate Fullscreen mode.

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#7337]
NWJS Version : nightly 0.44.0 http://dl.nwjs.io/live-build/nw44/20200122-162000/fe903783d/v0.44.0/
Operating System : win 10

### Expected behavior

Main window should go into fullscreen mode when pressing f11

### Actual behavior

Nothing happens.

### How to reproduce

run this 
[nwjsTest3.zip](https://github.com/nwjs/nw.js/files/4103515/nwjsTest3.zip)
Make sure the main window is focused and hit f11 and see that it does nothing.

**Comment by bluthen** [comment]
I don't think this is a bug. NW.js isn't a browser. If you want it to do that you can program it to do so.
Maybe something like:
```
var toggleFS = function() {
    console.log("Global desktop keyboard shortcut: " + this.key + " active."); 
    var w = nw.Window.get(window);
    if(w.isFullscreen) {
       w.leaveFullscreen();
    } else {
       w.enterFullscreen();
    }
};
window.onkeydown = function(e) { if (e.key == 'F11') { toggleFS(); }}
```

**Comment by prominentdetail** [comment]
Oh okay- thanks. That makes sense.
