### ISSUE TITLE
folder select dialog shows upload button instead of select on MacOS

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7338]
NWJS Version : 0.43.6
Operating System : MacOS 10.16.6

### Expected behavior

This is an old bug that has been resurected again, this time Mac Only.
On Windows it is all fine.

### Actual behavior

Folder picker shows upload button instead of select

<img width="979" alt="mac_selectFolder_name_upload" src="https://user-images.githubusercontent.com/504730/73084988-4630a680-3ece-11ea-9464-6401eb1473d6.png">

Also the positioning of the folder select window is really weird. It comes always in the middle of the main window and pushes the main window up.

### How to reproduce

Use this test case:

[folder_picker_bug.zip](https://github.com/nwjs/nw.js/files/4109452/folder_picker_bug.zip)

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw44/20200125-162000/5925084b5
