### ISSUE TITLE
Can't find way to enable Chrome's Native File System API

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7342]
I filed this based on an email to the NW.js group. Original message:

> I'd like to try using Chrome's new native file system API in NW.js. I know there are file system methods in Node, but using an API that is also available in the browser would let us keep our web and desktop codebases more similar.
> 
> It's currently in origin trial and has a flag in chrome://flags, but I can't figure out how to enable it in NW.js. I've tried adding the following to "chromium-args":
> --native-file-system-api
> --enable-native-file-system-api
> --enable-features=native-file-system-api

It would be good if NW.js provided a way to enable this feature. If it's enabled, `window.chooseFileSystemEntries` will be a function.

Further, if it's not already done, automatically approving any permission prompts would help it work more like the node-based file I/O methods.

**Comment by rogerwang** [comment]
I just found it can be enabled by adding `--enable-features=NativeFileSystemAPI` and it works with a simple test here. Anything more please let me know.
