### ISSUE TITLE
Many error messages re navigation since 0.43.5

### ISSUE THREAD

**Issue by srguiwiz** [nwjs/nw.js#7346]
NWJS Version : 0.43.6
Operating System : CentOS 7.7

### Expected behavior

No console error messages, as it was fine until and including 0.43.4.

### Actual behavior

Console error message

> Unsafe JavaScript attempt to initiate navigation for frame with URL 'chrome-extension://blahblahlongrandomtext/index.html' from frame with URL 'about:blank'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

### How to reproduce

Simplest NW.js app with index.html

```
<html><head><script>
  function setSrc(newSrc) {
    document.querySelector("iframe").src = newSrc;
  }
</script></head>
<body onload="setSrc('about:blank');">
<iframe src="about:blank" sandbox="allow-scripts allow-modals allow-same-origin"></script>
</body></html>
```

This is just the simplest example to reproduce and show it started with version 0.43.5.

The `about:blank` is useful in the example and in real use, but there are even more error messages if using `http://www.wikipedia.org/`.

It was discovered in much bigger code, and the console log is flooded with error messages.

Note, possibly it doesn't prevent the code from running.  But definitely the log is flooded with error messages.

**Comment by chatcan** [comment]
same problem

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
