### ISSUE TITLE
NW2: postMessage is not working

### ISSUE THREAD

**Issue by Ser-Gen** [nwjs/nw.js#7352]
NWJS Version: `0.43.6`
Operating System: Kubuntu `19.10`

### Expected behavior
In red window should be black text.

### Actual behavior
Text is not appears.

Text is posted from main window to sub, but handler of message is not executed.
`--disable-features=nw2` switch helps for now.

### How to reproduce
Prepare and start app
[nwjs_postmessage.zip](https://github.com/nwjs/nw.js/files/4141339/nwjs_postmessage.zip)

**Comment by rogerwang** [comment]
postMessage is working. It's just that the callback of `nw.Window.open` is called earlier than in NW1. It's called before the event handler is registered in the new window.

**Comment by Ser-Gen** [comment]
Sorry that doesn't check this first.
