### ISSUE TITLE
Regression of allowed String length, `buffer.constants.MAX_STRING_LENGTH`

### ISSUE THREAD

**Issue by danielsokolowski** [nwjs/nw.js#7356]
Upgraded from nw.js v0.38.4/Node v12.3.1 to nw.js v0.44.0/Node v13.6.0 and now getting `RangeError: Invalid string length` during `JSON.stringify(...)`. 

v12.3.1
```
> require('buffer').constants.MAX_STRING_LENGTH;
< 1073741799
```

v13.6.0
```
> require('buffer').constants.MAX_STRING_LENGTH;
< 268435440
```

I've reached out to node.js team and it appears their source code is correct:  https://github.com/nodejs/node/issues/31653

Running `require('os').arch()` on both 0.38.4 and 0.44.0 returns `x64`

Posting here to determine it's perhaps a regression with nw.js during node.js integration.

**Comment by danielsokolowski** [comment]
Comment copied from https://github.com/nodejs/node/issues/31653#issuecomment-582608783

> This would most likely only happen if nw.js has pointer compression enabled (see nodejs/TSC#790 for details on that feature), and not be directly related to Node.js.

**Comment by danielsokolowski** [comment]
Well looks like it's a regression back in v8 fixed 3 days ago. https://github.com/v8/v8/commit/ea56bf5513d0cbd2a35a9035c5c2996272b8b728

**Comment by rogerwang** [comment]
Thanks. Will look to merge it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by zkrige** [comment]
on 0.44.1 I'm seeing 

```
requireNode('buffer').constants.MAX_STRING_LENGTH
536870888
```

which is breaking our file downloading

**Comment by zkrige** [comment]
~2**29 is only 500MB - can't we increase that limit?

**Comment by rogerwang** [comment]
We tend to keep the same parameter as upstream. Why should we increase it?

**Comment by zkrige** [comment]
currently request.pipe(fs.writestream) is breaking on >500mb files downloads. But its probably better to keep the upstream. I'll figure out a different way of handling this
