### ISSUE TITLE
App starts with min_height and min_width instead of height and width

### ISSUE THREAD

**Issue by r0bertz** [nwjs/nw.js#7358]
NWJS Version : 0.44.0
Operating System : Linux

### Expected behavior

App starts with width and height 

### Actual behavior

App starts with min_width and min_height

### How to reproduce
Unpack nw.tar.gz which contains a helloworld app and run 'nw .' in it.
[nw.tar.gz](https://github.com/nwjs/nw.js/files/4163764/nw.tar.gz)

The package.json looks like:
```
{
  "name": "helloworld",
  "main": "index.html",
  "window": {
    "width": 1024,
    "height": 650,
    "min_width": 768,
    "min_height": 100
  }
}
```

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
