### ISSUE TITLE
NW2 issue : (Linux) NW.js crashes when an opened window has attached the 'move' event

### ISSUE THREAD

**Issue by DimPaDev** [nwjs/nw.js#7359]
NWJS Version : 0.44.0
Operating System : Linux (Reproduced on Fedora 31, gnome and kde)

### Expected behavior

When you open a new window and you attach events to it from the Window api, the application shouldn't crash even if you try to open the devtools window to inspect it.

### Actual behavior

When you open a new window and this window has attached in particular **the 'move' event** and you try to open the devtools window to inspect, the entire application crashes, if you don't attach the move event to the new window (or you add --disable-features=nw2 to chromium args) everything is fine.

Finally, I tested this on Windows 10 too and this problem doesn't exist either.

### How to reproduce

DEMO: 
[nw-test-crash-bug.zip](https://github.com/nwjs/nw.js/files/4165801/nw-test-crash-bug.zip)

**Comment by DimPaDev** [comment]
#7230

**Comment by DimPaDev** [comment]
I found out that if you open the dev tools window programmatically BEFORE attaching the 'move' event to the window, the application will NOT crash and the dev tools window will be opened. For example : 
```

        function openNewWindow() {
          console.log('ok open new window..');
          nw.Window.open('./new_win.html', {
            title: 'App Title',
            show: true,
            show_in_taskbar: true,
            position: 'center',
            width: 400,
            height: 400,
            fullscreen: false,
            frame: true,
            transparent: false,
            resizable: true,
            always_on_top: false,
            kiosk: false
          }, newWin => {

            newWin.showDevTools();

            newWin.on('loaded', () => {
              newWin.on('move', (x, y) => {
                console.log(`ok move event triggered`);
              });
            });
          });
   }
```

But, if you try to open the DevTools for a window when the 'move' event is already attached (in nw2 mode) the application will crash altogether.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by DimPaDev** [comment]
I tested it using the nightly build and it's fixed! Thank you!
