### ISSUE TITLE
Problems with window.print

### ISSUE THREAD

**Issue by Dzorogh** [nwjs/nw.js#736]
1) I can't 'print' to "Microsoft XPS Document Writer", files become empty. So I can't see any preview of page. Maybe you can add normal print preview? (or fix xps)

2) I tried to print this page at printer, but saw some strange paddings and some problems with borders (if print same page from Google Chrome - all is perfect). Why it happens?

**Comment by rogerwang** [comment]
should be fixed with 0.13.0 RC.
