### ISSUE TITLE
[Regression] Window bar app icon is low quality again

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7361]
NWJS Version: v0.44.0
Operating System: Windows 10

### Expected behavior
High quality icon should be set like in the task bar.

### Actual behavior
Low quality icon is being used in window bar
![image](https://user-images.githubusercontent.com/15656049/74020099-1cc94d80-4999-11ea-9f25-d7c53df435eb.png)

### How to reproduce
[Download Construct 3 Desktop](https://downloads.scirra.com/c3-desktop/win64/construct3-win64-c80-stable.zip) and just run it on a Windows 10 system.

**Comment by TheRealDannyyy** [comment]
Seems like NW2 is causing this, so tagging #7230

**Comment by panther7** [comment]
+1

**Comment by rogerwang** [comment]
It works for me with this sample:

https://github.com/rogerwang/4581-icon

<img width="299" alt="icon-window" src="https://user-images.githubusercontent.com/165401/75407654-81e7e180-594e-11ea-8cf8-12cedbae014c.png">

**Comment by TheRealDannyyy** [comment]
Nope. Your sample is also looking crusty.
![image](https://user-images.githubusercontent.com/15656049/75441312-bca54600-595d-11ea-8b43-307c97621141.png)

**Comment by panther7** [comment]
Agreed, icon has "sharp" render.

Check screenshots inside this issue: https://github.com/nwjs/nw.js/issues/7379#issuecomment-587004276

**Comment by rogerwang** [comment]
@TheRealDannyyy could you attach a picture with the good icon of my sample project?

**Comment by TheRealDannyyy** [comment]
![image](https://user-images.githubusercontent.com/15656049/75714326-cf0be080-5ccb-11ea-97db-1be00764940b.png)

**Comment by TheRealDannyyy** [comment]
@rogerwang Any progress on this minor issue? 

I'm not sure if I could provide more info for reproduction. At this point, just disabling NW2 should give a good comparison for between icon qualities. Would be great if we can get this fixed for the next major release.

**Comment by rogerwang** [comment]
I still can't reproduce this issue. I zoomed in with your uploaded screenshots and the NW2 icon looks better:

<img width="318" alt="屏幕快照 2020-05-28 下午5 32 13" src="https://user-images.githubusercontent.com/165401/83124835-502b1600-a109-11ea-9a28-260c405d0e14.png">
<img width="356" alt="屏幕快照 2020-05-28 下午5 32 03" src="https://user-images.githubusercontent.com/165401/83124840-51f4d980-a109-11ea-81a1-525f33311b72.png">

**Comment by TheRealDannyyy** [comment]
@rogerwang the problem is that NW2 sharpens the icon, instead of the usual behavior (see NW1 behavior). This can in some cases look better but in most cases, just reduces the quality of icons and makes them look "oversharpened" to users.

**Comment by rogerwang** [comment]
Could you provide a sample of reduced quality?

**Comment by TheRealDannyyy** [comment]
Here is another test example (download: [icon comparison.zip](https://github.com/nwjs/nw.js/files/4696506/Icon.Comparison.zip)): 
![NWIcon Comparison](https://user-images.githubusercontent.com/15656049/83159885-cda15700-a106-11ea-8571-5d2ea2765902.png)

---

You can also visit [Construct 3](https://editor.construct.net/) in both Chrome and NWjs to see the obvious difference in quality (sharpness) between icons:
![image](https://user-images.githubusercontent.com/15656049/83160991-26252400-a108-11ea-92c2-8d3c806d8014.png)

**Comment by rogerwang** [comment]
Can you confirm the regression happens first in 0.43.5? I have a sample suggests this. 

Your sample doesn't look obvious here and the construct 3 website doesn't show with any favicon when I load it in NW with `nw.exe --url=` ...

**Comment by TheRealDannyyy** [comment]
Construct 3 Download: https://downloads.scirra.com/c3-desktop/c3-nwjs-package-beta.zip
The regression happens first in 0.42.4, which is coincidentally also when NW2 got released. I think this issue might be caused by Chrome's Windows 10 custom titlebar implementation.

**Comment by rogerwang** [comment]
I didn't try the c3 package because it's a complex application and the window icon can be affected in various places. It would be helpful if you can extract the icon from it and confirm that with the simple sample ...

**Comment by TheRealDannyyy** [comment]
Here it is with the C3 icon and your provided sample: 
[NW2_C3.zip](https://github.com/nwjs/nw.js/files/4697148/NW2_C3.zip)

Same results:
![image](https://user-images.githubusercontent.com/15656049/83170738-49a29b80-a115-11ea-88e6-d08854a999c6.png)

**Comment by rogerwang** [comment]
I just made some adjustments to the drawing code of the custom title bar. But it can't be identical to the system native titlebar as the icon is resized and drawn by system GUI code in that case, while with custom titlebar the icon is shrinked and drawed by skia, which in turn uses GPU shader to draw the image.

For finer control on this I suggest using a 1:1 small icon picture, or use the native titlebar.

**Comment by TheRealDannyyy** [comment]
Thanks! Will review it when it's live.

**Comment by TheRealDannyyy** [comment]
Tested and works fine in NWjs 0.46.1, thanks for the fix!
