### ISSUE TITLE
Copy & paste between input fields adds spurious space

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7363]
NWJS Version : 0.44.0
Operating System : Windows 10 64-bit

### Expected behavior

Copy and paste to work like it does in Chrome

### Actual behavior

Pasting sometimes adds an extra space character

### How to reproduce

Minimal repro: [paste-space.zip](https://github.com/nwjs/nw.js/files/4170718/paste-space.zip)

1. Select text "a_text_" in the first field and copy
2. Select text "a_text_" in the second field and paste

Expected result: "a_text_field_also_with_content" (no space)
Observed result: "a_text_ field_also_with_content" (space inserted after the pasted text)

It seems sporadic, you may have to try a few variations to observe it. It does not happen in Chrome so appears to be specific to NW.js.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
