### ISSUE TITLE
NW2 issue : (Linux) Nw.js should NOT show the chromium default menu bar as global

### ISSUE THREAD

**Issue by DimPaDev** [nwjs/nw.js#7364]
NWJS Version : 0.44.0
Operating System : Linux

### Expected behavior

Nw.js should NOT show the chromium default menu bar as global.

Screenshot with --disable-features=nw2
![Screenshot_20200207_131636](https://user-images.githubusercontent.com/42065117/74029373-d8e04380-49ac-11ea-9b70-86e15a83a96c.jpg)

### Actual behavior

Nw.js shows the chromium default menu bar as global. 

![Screenshot_20200207_131332](https://user-images.githubusercontent.com/42065117/74029506-1b098500-49ad-11ea-91ec-a5cad6900321.jpg)

**Comment by DimPaDev** [comment]
#7230

**Comment by rogerwang** [comment]
Which Linux distribution and desktop environment are you using? Thanks.

**Comment by DimPaDev** [comment]
Fedora 31 with KDE Plasma using the global menu widget on the top panel which shows the menu of the focused application if it has one.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by DimPaDev** [comment]
I can confirm it's fixed now with the latest nightly build! thanks again!
