### ISSUE TITLE
MacOS builtin menu can not switch according to the focused Window 

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7366]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.44.0
Operating System : MacOS 10.14.6

### Expected behavior

if you have two different window that have different menu
nwjs 0.36.1 works well when you focus another window , mac's builtin menu change

### Actual behavior

nwjs 0.44.0, mac's builtin menu is always the way that is created latest 

### How to reproduce

here is the demo
[menu.zip](https://github.com/nwjs/nw.js/files/4179705/menu.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
