### ISSUE TITLE
[NW2] Right click options not working as expected (Reload app + Simulate browser restart)

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7367]
NWJS Version: Any since NW2 update
Operating System: Windows 10
Reproduction Project: [nwjs-remote-preview.zip](https://github.com/nwjs/nw.js/files/4181557/nwjs-remote-preview.zip)

### Expected behavior
Clicking the right click option to reload app should reload the app and simulating a browser restart should also work as it did in NW1 (--disable-features=nw2).

### Actual behavior
Both right click options seem to just open a new window instead of reloading.

### How to reproduce
1. Download and unzip reproduction example into NWjs folder
2. Run nwjs and right click "Reload app" or "Simulate Browser Restart"
3. Notice that expected behavior is not occurring

**Comment by TheRealDannyyy** [comment]
Fix required before NW1 removal, tagging #7230

**Comment by rogerwang** [comment]
Is this a duplicate of #7271 ?

**Comment by TheRealDannyyy** [comment]
I guess so. Will test to see if it's fixed in the next build.

**Comment by rogerwang** [comment]
I'm merging this issue with #7271. Please give update there. Thanks.

**Comment by TheRealDannyyy** [comment]
@rogerwang This is still a problem in the latest version. Reloading or simulating a restart using the right click options just opens a new window. It's even worse now and results in NWjs running in the background after closing.

Request to re-open issue for further investigation.

**Comment by rogerwang** [comment]
I just tried your sample with the latest version and it works for me.

**Comment by TheRealDannyyy** [comment]
Also seems to work for me. Maybe I tested the wrong version 4 days ago.
Thanks for the fix!
