### ISSUE TITLE
[NW2 issue] : Setting two binded windows to a fullscreen state doesn't work anymore 

### ISSUE THREAD

**Issue by DimPaDev** [nwjs/nw.js#7368]
NWJS Version : 0.44.0 
Operating System : Linux (Fedora 31, both kde and gnome), Windows 10

### Expected behavior

When you bind two windows both in size and position you should be able also to set these two windows to a fullscreen state just like in nw1 mode (--disable-features=nw2).

![nw1fullscreen](https://user-images.githubusercontent.com/42065117/74185373-ca15bd00-4c48-11ea-9d8c-0bfcd1b7f6a6.gif)

### Actual behavior

In Nw2 mode trying to set two binded windows to a fullscreen state results in a weird flickering issue which prevents the application to work normally. 

![nw2fullscreen](https://user-images.githubusercontent.com/42065117/74185497-0e08c200-4c49-11ea-8204-47abdf879e0b.gif)

### How to reproduce

Demo : [nw2-fullscreen-two-windows-bug.zip](https://github.com/nwjs/nw.js/files/4182810/nw2-fullscreen-two-windows-bug.zip)

**Comment by DimPaDev** [comment]
As it is a blocking issue I will reference this to #7230

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

Note that `restore` need to be handled as well. It should be fired when exiting fullscreen, not `resized` event. That's an issue in nw1 mode.
