### ISSUE TITLE
URGENT - It is impossible to make the window title with fixed text

### ISSUE THREAD

**Issue by shamun** [nwjs/nw.js#7374]
The title "NO-NO-NO-NO-NO-ONLY-SHOW-THIS-TITLE" never stays permanent when the site is open. How to tell title to stay as it is written?

**NOTE: Based on fixed title name a C++ software is used to capture the window for 60fps recording, when the title is changed the application process become random. How to fix the title to a fix text without allowing the title to be changed at all?**

```
{
  "main": "https://www.github.com",
  "name": "NO-NO-NO-NO-NO-ONLY-SHOW-THIS-TITLE",
  "description": "nwjs configureable browser framework",
  "chromium-args": "--mixed-context",
  "version": "0.0.1",
  "nodejs": true,
  "keywords": [
    "browser",
    "nwjs",
    "node-webkit"
  ],
  "window": {
    "title": "NO-NO-NO-NO-NO-ONLY-SHOW-THIS-TITLE",
    "icon": "icons/browser-128.png",
    "toolbar": false,
    "frame": true,
    "width": 1024,
    "height": 700,
    "min_width": 250,
    "min_height": 250,
	"position":"center"
  },
  "webkit": {
    "plugin": true
  }
}
```

**Comment by rogerwang** [comment]
This is expected. Consider overriding the title with this API: https://nwjs.readthedocs.io/en/latest/References/Window/#wintitle
