### ISSUE TITLE
NWJS Vanilla: Login to Gmail Failing on any OS

### ISSUE THREAD

**Issue by asteriosgr** [nwjs/nw.js#7375]
NWJS Versions (only on NON SDK!) :
0.44.1
0.39.2

Operating System Tested:
Linux (x64) can reproduce the issue
Windows (x64) issue is also reproduced
MacOS (x64) issue is also reproduced

### Expected behavior
When user navigates to "https://mail.google.com" we should be able to login.

### Actual behavior

Instead user is greeted with the following message: "This browser or App may not be secure."

### How to reproduce
(clean previous NWJS data or use a different user-data-dir before proceeding)
Use a Linux x64 OS or Windows x64 or MacOS
Use a non SDK version of nwjs.
Open cli and type: ./nw --url="https://mail.google.com"
Try to login.

EDIT: A dirty fix is to apply a different user agent. Any agent that does not contain "Chrome" in its string. For my case that solution is not acceptable.

**Comment by rogerwang** [comment]
This is Google's decision: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

https://groups.google.com/a/chromium.org/d/msg/embedder-dev/STyM5ZNTHMM/POj1v_cqBgAJ

I'm closing this for now since nothing can be done in NW's side.
