### ISSUE TITLE
Crash if window with opened devtools was closed

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7376]
NWJS Version: 0.44.1 (SDK), `--disable-features=nw2`
Operating System: Windows 10 x64 (latest)

### Expected behavior

Stable NWjs.

### Actual behavior

Application crash!

### How to reproduce

Try this simple demo: [open-new-window.zip](https://github.com/nwjs/nw.js/files/4205497/open-new-window.zip)
1. Open new window
1. Close opened window (via button).
1. Application crash!

**Comment by gpetrov** [comment]
We are also seeing this even with NW2
In previous 0.43.6 - devtools was first auto closed before the main window closed. But now it causes a crash if left open.

It would be really nice to restore the old behavior that if you close the main window with devtools open - on reopen it also reopens the devtools automatically

**Comment by CosmoMyzrailGorynych** [comment]
Still relevant for 0.45.x 😢

**Comment by panther7** [comment]
Seems works in 0.53.0 (maybe previously)
