### ISSUE TITLE
win.print will only print the parent window

### ISSUE THREAD

**Issue by aam-git** [nwjs/nw.js#7377]
NWJS Version : 0.44.1
Operating System : win-x64

### Expected behavior
When I call the function below, the child window should print silently

### Actual behavior
When I call the function below, the parent window prints not the child.

### How to reproduce
```javascript

const nwPrint = (data) => {

	nw.Window.open(`data:text/html,${encodeURI(data)}`, {focus: true}, (new_window) => {

		new_window.on('loaded', () => {

			new_window.print({
				"printer":"ZDesigner GK420d",
				"autoprint": true,
				"marginsType": 1,
				"headerFooterEnabled": false,
				"shouldPrintBackgrounds": false,
				"landscape": false,
				"mediaSize":{'name': 'CUSTOM', 'width_microns': 100000, 'height_microns': 150000, 'custom_display_name':'4x6 label', 'is_default': true},
				"preview": false
			});

		});
		
	});

}

nwPrint('Hello World');
```

I've tried every which way I can think of for the past few hours to make it print the child window, but its not letting me, each time I successfully mange to print, the parent window comes out.

**Comment by aam-git** [comment]
Just to add, it works fine on v0.39.3

**Comment by DrDoing** [comment]
I have the same issue. 

If you disable the nw2 Feature in your package.json : 

--disable-features=nw2

the print will work perfect. 

In issue #7230 Roger Wang ask for blocking nw1 removel issue. 
I think this issue is one. 

@rogerwang 
Is it possible to reproduce this issue, or do you need further informatione ?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
