### ISSUE TITLE
Window icon missing

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7379]
Manifest example:
```json
{
    "name": "nw-demo",
    "version": "0.0.1",
    "manifest_version": 2,
    "main": "index.html",
    "icons": {
        "16": "icon.png",
        "48": "icon.png",
        "128": "icon.png"
    }
}
```

Same problem with missing icon:
```js
nw.Window.open('index.html', { icon: "icon.png", title: "demo" })
```

0.41.x:  
![a](https://user-images.githubusercontent.com/3808250/74658875-7993e780-5193-11ea-836a-eef50e9ea61e.png)

0.42+:  
![b](https://user-images.githubusercontent.com/3808250/74658877-7a2c7e00-5193-11ea-8bbe-9b0df497de44.png)

Tested on:  
NWjs 0.41.3: works
NWjs 0.43.6: doesn't
NWjs 0.44.1: doesn't

OS: Windows 10 x64 (latest)

**Comment by panther7** [comment]
Low quality, if window.icon is included in manifest

![Image_2020-02-17 14 51 54](https://user-images.githubusercontent.com/3808250/74659749-2d49a700-5195-11ea-9c7e-83d76eecccc3.png)

#7361

**Comment by rogerwang** [comment]
Could you please provide a sample? It works for me -- the icon is not missing...

**Comment by panther7** [comment]
@rogerwang ofcourse: 
[demo.zip](https://github.com/nwjs/nw.js/files/4698266/demo.zip)

**Comment by panther7** [comment]
Hmmm... now works properly, maybe it was bug in Windows
