### ISSUE TITLE
npm install nw not working

### ISSUE THREAD

**Issue by yaser-alazm** [nwjs/nw.js#7385]
NWJS Version : 0.44.2-sdk
Operating System : Ubuntu 19.10

### Expected behavior

I want to install the package to try it for my project with : `sudo npm install -D nw` 

### Actual behavior

but what actually happens is that the package install fails with this error : 

`
nw@0.44.2-sdk postinstall /home/yaser-work/Documents/projects/nw-js-desktop app/node_modules/nw > node scripts/install.js unexpected end of file
npm WARN nw-js-desktop-app@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.44.2-sdk postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.44.2-sdk postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

Also I tried using --unsafe-perm with npm command to avoid any expected permission issues and tried different versions of NW package but still have this problem!
The problem happens just with this package, meaning that when i install any other package on my project it works with no errors at all.

Thanks

**Comment by arasrezaei** [comment]
I had the similar problem that it was stucking at postscript (`node script/install.js`), my solution was downloading nw manually and copieng its content (where excutable is) to nwjs folder inside nw module. then using `nw .` and worked!

**Comment by garys-primary** [comment]
Please fix the module. Add the install.js to nw/scripts.
It is impossible to use on MacOS anymore.

**Comment by BrettFraley** [comment]
Does anyone know if there's updates on this?
Ideally, I would like to point `npm run dev` to `node_modules/nw/[sdk versionj]/nw`
and `npm run prod` to `node_modules/nw/[main version]/nw`

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/npm-installer
I'm not sure what version this was fixed in but it is fixed in v0.91.0
