### ISSUE TITLE
can't disable throttling

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#7389]
Trying to use --disable-raf-throttling on either js-flags or chromium-args within package.json doesn't seem to disable throttling, since when I minimize my application(a server interface for my game), its main setInterval(set for 33ms) starts running once every 1000ms instead. Maximazing the application again reduces the interval back to 33ms

NW.js v0.44.2 SDK, Windows 10

I've also tested this on V0.43.2(same system) and it wasn't working either

EDIT: Also tested on v0.44.3 and it still happens

**Comment by arudnev** [comment]
You are probably looking for `--disable-background-timer-throttling`, I'm not sure `--disable-raf-throttling` is supposed to affect `setInterval` / `setTimeout`.

**Comment by elpeleq42** [comment]
> You are probably looking for `--disable-background-timer-throttling`, I'm not sure `--disable-raf-throttling` is supposed to affect `setInterval` / `setTimeout`.

I had no idea that was a flag since, from what I can see, its not on the docs nor is mentioned anywhere besides a really old update post.
