### ISSUE TITLE
Fill details of final executable with project data, not with NWjs defaults.

### ISSUE THREAD

**Issue by alessandrofrancesconi** [nwjs/nw.js#7390]
NWJS Version : 0.44.2
Operating System : Windows 10 x64

### Expected behavior

The output executable in /dist should have information in Details tab in respect to what is written in package.json file. Example "File Version", "Description", "Product name", "Product version", "Copyright".

### Actual behavior

Instead the details are always set to this:

![image](https://user-images.githubusercontent.com/1595223/75366389-f2472200-58be-11ea-987c-437451f47d51.png)

### How to reproduce

- Compile a sample app with "prod"
- Right-click on produced exe file, Properties, Details tab

**Comment by tharatau** [comment]
I'm assuming you're using a tool to automate renaming executable fields.
