### ISSUE TITLE
3D map view doesn't work on mapy.cz

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7407]
3D map view doesn't work on mapy.cz, try: https://en.mapy.cz/zakladni?m3d=1&yaw=0&l=0&pitch=-45

Probably problem with 'createImageBitmap' in Worker or can't support for blob

* Chromium 80 Works
* Windows 10 x64 (latest)

NWjs 0.43.6 works:  
![Image_2020-03-02 14 57 49](https://user-images.githubusercontent.com/3808250/75682852-62c2ba00-5c96-11ea-9fbd-31721eec0984.png)

NWjs 0.44.3 doesn't:   
![Image_2020-03-02 14 55 31](https://user-images.githubusercontent.com/3808250/75682592-f3e56100-5c95-11ea-8a29-4e2dd46175fe.png)

**Comment by bodo22** [comment]
The issue with createImageBitmap is fixed in v0.45, see issue #7372

**Comment by panther7** [comment]
fixed
