### ISSUE TITLE
Detect if running in "dev" or "prod"

### ISSUE THREAD

**Issue by alessandrofrancesconi** [nwjs/nw.js#7408]
Having these scripts:

```
"scripts": {
    "dev": "nw src/",
    "prod": "nwbuild --zip --flavor normal --platforms win64 --winIco src/assets/icon.png --buildDir dist/ src/"
  }
```

Is it possible to check if the application is running under "dev" or "prod" environments?

**Comment by bodo22** [comment]
Are you looking for [process.versions['nw-flavor']](http://docs.nwjs.io/en/latest/References/Changes%20to%20Node/#process) ?

**Comment by alessandrofrancesconi** [comment]
It worked, thank you
