### ISSUE TITLE
Crash on Windows 10 at saving window dimentions

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7412]
NWJS Version : 0.44.4
Operating System : Windows 10

### Expected behavior

Windows mentions should be stored

### Actual behavior

Crash - see

https://sentry.wappler.io/share/issue/0ce1f4a8c8a140be8d54fd5131fd50e4/

**Comment by gpetrov** [comment]
This is becoming quite an issue @rogerwang - we got many users unable to use our product because it crashes immediately on startup. We probably have to revert to 0.44.2 due to this bug.

Do you think you can address it soon?

**Comment by rogerwang** [comment]
Will look to fix it soon. Thanks.

**Comment by rogerwang** [comment]
Please try this: https://dl.nwjs.io/live-build/nw44/20200316-123559/b37f3d15b/v0.44.5/

**Comment by gpetrov** [comment]
Many thanks @rogerwang ! Seems for most users it solved the problem but there are a few more left,  specially with Windows 10 1903 build 18362

Here are the crashpad files of one:

[Crashpad.zip](https://github.com/nwjs/nw.js/files/4343520/Crashpad.zip)

When you fix it - could you please release 0.44.5 officially first, before going to 0.45?
As 0.44 is really stable and we would like to stay on it till 0.45 becomes just as stable

Thank you for your hard work!

**Comment by rogerwang** [comment]
do you happen to have crash log on sentry?

**Comment by gpetrov** [comment]
No couldn't catch this one in Sentry. Might be a single user incident. I was hoping you can see its crash in the attached crashpad logs.

All other users report that the problem is solved with the test 0.44.5

So if you could release it officially - it will be great!

**Comment by gpetrov** [comment]
this problem is solved, the last user had a different crash: https://github.com/nwjs/nw.js/issues/7420
