### ISSUE TITLE
你好！v0.42.0以上的版本，页面加载以后窗口总是按照一定的比例，而不是按照预期的设置

### ISSUE THREAD

**Issue by gouxiwen** [nwjs/nw.js#7415]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System :

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

比如设置的页面是：width：640，height：400，而实际得到的总是width：640，height：480，页面好像有一定的比例限制，查询文档也没有相关说明，希望能答复，谢谢！

**Comment by gouxiwen** [comment]
经过测试发现导致这个问题的原因是setMinimumSize在设置的时候height的最小值等于width/1.33333，即使设置小于该计算值，也会以该计算值生效，为什么会有这样的限制？

**Comment by rogerwang** [comment]
Please use only English in this project so all users can read. Thanks.
