### ISSUE TITLE
Getting Virus Detection

### ISSUE THREAD

**Issue by team-pct** [nwjs/nw.js#7418]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.44.5
Operating System : Windows 64 Bit

### Expected behavior

No AV detection

### Actual behavior

AV are detecting it as threat 

### How to reproduce
Upload nw_elf.dll to virustotal.com

https://www.virustotal.com/gui/file/dc7f76ab3cf6dd30cbb1c3767aecabdea40695232060cfde3fea54f82367ec9a/detection

**Comment by scyto** [comment]
If the nwjs team confirm there is no malicious code, please upload the file to https://www.microsoft.com/en-us/wdsi/filesubmission to get MS to look at file and change their signatures (heck i will do it if needed, i regularly submit stuff)

**Comment by scyto** [comment]
FYI i am **not** getting this on windows defender beta signatures
Service Version: 4.18.2003.6
Engine Version: 1.1.16800.2
AntiSpyware Signature Version: 1.311.1569.0
AntiVirus Signature Version: 1.311.1569.0

i..e no detection as virus on my windows machine now

**Comment by team-pct** [comment]
I am trying to contact every AV company to mark this as false positive

**Comment by gpetrov** [comment]
also always sign all the dll's and exe's files within NWJS with codesign and an official certificate.
This will produce a new signature and also give much more trust to the installers.

**Comment by jssuttles** [comment]
Hi, this is still an issue.

**Comment by bluthen** [comment]
Can't really control malware and virus detectors.

From experience it helps to sign all your stuff. I know that requires paying a CA.

**Comment by TheJaredWilcurt** [comment]
You can report false-positives to any security software company and they'll investigate and fix it on their end.
