### ISSUE TITLE
JQuery object isn't loaded/detected with new_instance enabled

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#7419]
NWJS Version : 0.44.5
Operating System : Linux

### Expected behavior

All functions in other javascript scripts should be able to perform jquery tasks including $(...).addClass(....) etc.

### Actual behavior

$ is not defined, bootstrap.js even reports that "Bootstrap's JavaScript requires jQuery" meaning it can't find it either. None of my scripts can.

 No, I don't use the require() way, I use the <script> tag to load jQuery. Saw this being a problem from me looking into this anyway.

I am assuming this is some side effect with the implementation of contexts?

### How to reproduce
Create a new window using new_instance = true
import jQuery as <script>
Try anything jquery related in your js file thats also loaded using <script> tag in the html file

Ok here is a complete code to test with:
[jquery demo.zip](https://github.com/nwjs/nw.js/files/4602554/jquery.demo.zip)

**Comment by gpetrov** [comment]
Related to https://github.com/nwjs/nw.js/issues/7344

**Comment by anesuc** [comment]
I am pretty sure this is related to #7230 as well.

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so I can reproduce?

**Comment by anesuc** [comment]
This error was happening on a relatively big project, so I'll create a new one for the purposes of the demo. Give me a sec

**Comment by anesuc** [comment]
@rogerwang Ok I've updated the post with a complete set of code to use

**Comment by rogerwang** [comment]
Thanks. I can reproduce the issue. But it shouldn't block #7230 as it fails in nw1 mode too...

**Comment by anesuc** [comment]
@rogerwang Interesting. Thought it worked before for some reason. It probably did and broke at one point in NW1 phase

**Comment by anesuc** [comment]
Any potential updates on this? Don't want to be pushy or anything, just wondering if it will be anytime soon or if it's long down the queue. I'm working on something that relies on loading other Devs' work which could freeze or crash everything else if that window freezes

**Comment by rogerwang** [comment]
will look to fix it soon

**Comment by anesuc** [comment]
Awesome! Keep up the good work!

**Comment by rogerwang** [comment]
This is fixed in #7344
