### ISSUE TITLE
NW2 Standard alert/confirm..  clip in main window

### ISSUE THREAD

**Issue by DrDoing** [nwjs/nw.js#7422]
#7230 @rogerwang 

NWJS Version : since 0.44.2 and nw2 is default 
Operating System : Windows

### Expected behavior
If you show a javascript dialog like alert/confirm prior to 0.44.2 
the msgbox was shown on the desktop. 
Since 0.44.2 (nw2) the messagebox is shown inside the main 
window. If the main window is to smal in width, the messageboxes
will be clipped. 

[Exampe-nw1-nw2.zip](https://github.com/nwjs/nw.js/files/4368745/Exampe-nw1-nw2.zip)
![20200323-03](https://user-images.githubusercontent.com/6784051/77308808-d25b2080-6cfb-11ea-897f-4a3b246517cf.png)

<!- What do you think should happen? ->
In nwjs >= 0.44.2 (nw2) the messageboxes should not be clipped by the main window.

### Actual behavior
Messageboxes will be cliped if the size of the main window ist to smal.
<!- What actually happens? ->

### How to reproduce

above there is a Exampe-nw1-nw2.zip File. 
inside there are 2 directorys: 
..
  nw1\index.html
  nw1\package.json
...
  nw2\index.html
  nw2\package.json
..
nw1 has a fix in package.json to disable nw2
first copy both files of nw1 in a nwjs main directory and start nw.exe
Resize the window to minimal witdh (about 100 to 200 pixel if possible)
Click on the button "Please Click"
There will be shown 2 message boxes in correct size. 
end nw.exe

second copy both files of nw2 in a nwjs main directory and start nw.exe
Resize the window to minimal witdh (about 100 to 200 pixel if possible)
Click on the button "Please Click"
There will be shown 2 message boxes cliped in size (width)
end nw.exe

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
