### ISSUE TITLE
when in nw2 mode, if set a breakpoint at websocket on message handler, will cause webview process crash

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7427]
nwjs : 0.44.5
macOS: 10.14.3

here is a demo
[nw2.zip](https://github.com/nwjs/nw.js/files/4391365/nw2.zip)

![image](https://user-images.githubusercontent.com/11750641/77719630-b66bbd80-7020-11ea-8fd3-9e26e2a939f0.png)

after continue to run and hit the breakpoint several times, the webview process crash
![image](https://user-images.githubusercontent.com/11750641/77719773-16fafa80-7021-11ea-99da-7ac94bd5fa43.png)

when set --disable-features=nw2 the problem solved

**Comment by chatcan** [comment]
--disable-features-nw2 can't work also;
nwjs 0.39.3 is ok；

it's very important for us; but nothing we can do;

**Comment by rogerwang** [comment]
I can reproduce it. Will look to fix it soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
please try this build https://dl.nwjs.io/live-build/nw44/20200330-035815/cc54c2fa2/v0.44.6/

**Comment by chatcan** [comment]
it works!
