### ISSUE TITLE
[ Feature Request ] - 2 Chromium Args for Spellchecking (Windows OS)

### ISSUE THREAD

**Issue by rowenbuzz** [nwjs/nw.js#7431]
**I have a client requesting a new feature in our App and for that new feature to use the Windows native spellchecking.**

NWJS Version : 0.40.1
Operating System : Windows 10 Pro (64 Bit)

_Overview_:
NW.js currently allows for spellchecking using chromium-args in the package.json:
` "chromium-args": "--enable-spell-checking"`

However, it does not seem to respond to two other chromium-args (flags) available in chrome:
1. --win-use-native-spellchecker
2. --win-use-hybrid-spellchecker

![image](https://user-images.githubusercontent.com/35744022/78361932-31842500-7587-11ea-8613-8b078cd6a14f.png)

The documentation linked from NW.js found here appears outdated:
http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#other-chromium-options

As none of the 3 links provided mention that --enable-spell-checking is available when it is working:
https://github.com/nwjs/nw.js/issues/332
...as of June 10th, 2015.

_Feature Request_:
I would prefer the hybrid-spellchecker but I'd like to request both chromium-args.

- Therefore, please add in the two chromium-args listed above so they work in NW.js
- Update the documentation for all chromium-args but at least for spellchecking options

**Comment by rowenbuzz** [comment]
Hey @rogerwang after looking through the code base and it appears this is only two lines of code per item, so 4 lines total.  Can you tackle this issue for my team?  We would really appreciate it.  Thank you.

**Comment by tlmason92** [comment]
Hi @rogerwang  I have a client that would like to do this as well.  Thank you for your help in resolving this issue.

**Comment by rogerwang** [comment]
Sure, will look to support it.

**Comment by rowenbuzz** [comment]
Thank you for tackling this @rogerwang we are looking forward to it.

**Comment by rogerwang** [comment]
I found that `win-use-native-spellchecker` and the other one is a flag, not a command line argument in Chromium.

Try to use `--enable-features= WinUseBrowserSpellChecker` or `--enable-features= WinUseHybridSpellChecker`

**Comment by tlmason92** [comment]
Hi @rogerwang,  I am trying to use the flags to allow my users to add new words in our application and have them also added in MS Word.  I have tried  implementing the flags in the following line   "chromium-args": "--disable-print-preview --enable-spell-checking --enable-features=WinUseNativeSpellChecker", however the word added in the application dictionary is not appearing in Word.  Is it possible to do that using these flags in chromium?

**Comment by tlmason92** [comment]
Bounty Posted:
https://www.bountysource.com/issues/91303655-feature-request-2-chromium-args-for-spellchecking-windows-os
@rogerwang @rowenbuzz @mrfabbri @japj @TheJaredWilcurt @jtg-gg @alex-ter @ghostoy @Christywl

**Comment by rogerwang** [comment]
You should try to use the exact feature name as in my last comment.

**Comment by rogerwang** [comment]
btw, you can try this first in Chrome browser to see if it works in your use case.

**Comment by tlmason92** [comment]
I was able to duplicate my use case in Chrome browser.  I also able to implement the solution above and it appears to be working.

**Comment by tlmason92** [comment]
@rogerwang This issue is resolved and we found we were working on an older version of nw.js 0.40.1 to be specific, after we upgraded to 0.45.4 it worked.  

This issue can be closed.
