### ISSUE TITLE
browser_switcher_service.cc(238)] XXX Init()

### ISSUE THREAD

**Issue by bulolo** [nwjs/nw.js#7436]
![image](https://user-images.githubusercontent.com/10026498/79035553-52392400-7bf2-11ea-9b3c-8a90cf82507b.png)

how to save this problem?

**Comment by panther7** [comment]
Same "problem".

**Comment by data-miner00** [comment]
same problem, works fine days ago

**Comment by jithinjosejacob** [comment]
Could be a chrome driver issue,i had to upgrade mine to 81, and facing same issue

**Comment by TBosak** [comment]
also having this issue :(

**Comment by TBosak** [comment]
Making sure chromedriver and my chrome version were matching corrected this issue for me in a separate project where I was runnning into this error.

**Comment by jeanduclos** [comment]
I got the same issue as well.

**Comment by jeanduclos** [comment]
Yes, It is something to do chromedriver.  I don't think is nothing to do with Python or Java issue since I am using RobotFramework keyworks.

**Comment by SusmithBarigidad** [comment]
getting the same issue

**Comment by jithinjosejacob** [comment]
seems like chrome driver is not compatable with new chrome version 81(which got updated last week).i downgraded the chrome to 79 and it worked without this error

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by DheerajChalil** [comment]
> This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

how to know the compatible nightly build?
PS: Version 81.0.4044.138 (Official Build) (64-bit)

#this is my chrome version

**Comment by rogerwang** [comment]
@DheerajChalil it has been released with the latest version.
