### ISSUE TITLE
Linux: wrong app name in native desktop notifications

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#7437]
NWJS Version: 46.x (not relevant)
Operating System: Linux

### Bug

When triggering a desktop notification on Linux via the chrome notification API (native notifications via the freedesktop notification spec), NW.js always sets a static "nwjs" app name property on the notification data.

The app name should instead be read from the package.json's "name" property, or even better, the [default window title](https://docs.nwjs.io/en/latest/References/Manifest%20Format/#title) (`window.title` property).

Freedesktop notification specification:
https://developer.gnome.org/notification-spec/

Issue reported on my app here:
https://github.com/streamlink/streamlink-twitch-gui/issues/715

### Reproduction

**Demo app:**
https://github.com/bastimeyer/nwjs-notification-app-name-bug

Click the "New Notification" button and see the notification that's been triggered. Instead of showing "nwjs-notification" as app name (the value from the `package.json`), it shows "nwjs".

As an example, to trigger a notification from the shell, run this:
```bash
gdbus call \
  --session \
  --dest org.freedesktop.Notifications \
  --object-path /org/freedesktop/Notifications \
  --method org.freedesktop.Notifications.Notify \
  my_app_name \
  1234 \
  gtk-dialog-info \
  "The summary" \
  "The body" \
  '["foo","bar"]' \
  '{}' \
  0
```

### Source

The app name gets set here:
https://github.com/nwjs/chromium.src/blame/nw46-log/chrome/browser/notifications/notification_platform_bridge_linux.cc#L574

`IDS_PRODUCT_NAME` is not the correct value.

**Comment by rogerwang** [comment]
Thanks for reporting. I fixed this with [`product_string`](https://nwjs.readthedocs.io/en/latest/References/Manifest%20Format/#product_string) in manifest.
