### ISSUE TITLE
RTL - scrollbar make wrong padding

### ISSUE THREAD

**Issue by alaa13212** [nwjs/nw.js#744]
I started in create right-to-left app via node-webkit.

```html
<html dir="rtl" lang="ar">
```

Everything was fine, and app was beautiful :) .
![normal](https://f.cloud.github.com/assets/1864639/566685/e3e865aa-c69b-11e2-8e4f-95d7616ed485.png)

But when the options are increased, scrollbar appeared in the left and padding added to right. 

![scroll](https://f.cloud.github.com/assets/1864639/566686/e40d34ac-c69b-11e2-89b3-d2f1d3693bf6.png)

I'm Sorry for bad english.

**Comment by rogerwang** [comment]
Please try the latest 0.13.0 release.
