### ISSUE TITLE
Crash webview/app on pinterest.com

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7444]
Open www.pinterest.com, browsing, and about after ~30sec crash, next start app will again crash. You can fix delete cache from `%localappdata%/MiniBrowser`

**Tested on:**
NWjs 0.44.5, 0.44.6, 0.45.1 (x86)
Windows 10 x64

**Mini browser:**
[mini-browser.zip](https://github.com/nwjs/nw.js/files/4493462/mini-browser.zip)

@michalvasek

**Comment by rogerwang** [comment]
The latest nightly works for me: https://dl.nwjs.io/live-build/nw45/20200418-162000/9ca32a510/v0.45.3/

**Comment by panther7** [comment]
Still crash, try this crashdump: [crashdump_nwjs0.45.3.zip](https://github.com/nwjs/nw.js/files/4498927/crashdump_nwjs0.45.3.zip)

Or try copy this: https://drive.google.com/open?id=1gB_gxD7ij9yFO9E11bQixyWAC1WpcJkW to %LocalAppData% in Windows

**Comment by panther7** [comment]
Probably deprecated...
