### ISSUE TITLE
NWJS runs out of memory and crashes

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7447]
NWJS Version : 0.44.5
Operating System : Windows and Mac

After intensive usage of the NWJS app in about two ours it runs out of memory and crashes

A lot of out of memory reports are coming in lately. 

https://sentry.wappler.io/share/issue/6748fe057494423da1463a3d0f00d54a/

@rogerwang Is this a Node memory problem that we can tackle with increase the memory limit with --max_old_space_size - and is this method still working on the latest NWJS?

**Comment by alessandrofrancesconi** [comment]
Maybe related to #7103 ?

**Comment by gpetrov** [comment]
this turned out to be looping problem in the Monaco editor code we were using in NWJS.
So it wasn't a problem with NWJS.

We do hope for a better memory/crash handling in NWJS
