### ISSUE TITLE
iFrame bug starting from v0.43.5

### ISSUE THREAD

**Issue by AdrienFrance** [nwjs/nw.js#7448]
Hello Roger!

I recently tried to update my NWJS app (https://you.dj) but I am facing a blocking issue.

My app is embedding Youtube videos and as you know youtube videos are iframe. In the newest version of NWJS the Youtube videos won't play anymore in my app and I get a "video unavailable" error.

I have investigated and I found that the issue appeared in v0.43.5 and I also found that you changed something in your iframe implementation here : https://github.com/nwjs/nw.js/issues/7305, it might be related...

Here is a video of the problem I made for you : https://you.dj/nwjs-iframe-bug.mp4

![nwjs-iframe-bug](https://user-images.githubusercontent.com/64126799/79953262-deadd700-847b-11ea-89f8-e26ef3690391.png)

The iframe code is :

`<iframe width="560" height="315" src="https://www.youtube.com/embed/tspNk3SwZ9s" frameborder="0" nwdisable nwfaketop allowfullscreen></iframe>` 

Here is the simple test case I made to try on your side : [nwjs-iframe-bug.zip](https://github.com/nwjs/nw.js/files/4514466/nwjs-iframe-bug.zip)

PS : my app (and my simple test case) runs a webserver and loads all the html5 code under http://127.0.0.1:8082/index.html, this is mandatory for some chrome APIs like webaudio/webmidi, maybe you never tried this scenario...

Thanks a lot for helping me and for making NWJS,

Stay healthy,

Adrien

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by AdrienFrance** [comment]
Roger you are just THE BEST!!!! I will be able to update my app with the latest NWJS. Keep up this amazing work, I am using NWJS for years now :)
