### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by srguiwiz** [nwjs/nw.js#7452]
NWJS Version : 0.45.4
Operating System : CentOS 7.7

### Expected behavior

Application window should appear.

### Actual behavior

Terminal window shows

```
[5964:5964:0425/013445.612715:ERROR:browser_switcher_service.cc(238)] XXX Init()
[6011:6011:0425/013445.749318:FATAL:nw_content_renderer_hooks.cc(53)] \
Failed to load node library (error: /lib64/libc.so.6: version `GLIBC_2.18' not found \
(required by ~/nwjs-example/node_modules/nw/nwjs/lib/libnode.so))
#0 0x7f115390b269 (~/nwjs-example/node_modules/nw/nwjs/lib/libnw.so+0x4636268)
```

### How to reproduce

The simplest NW.js app with index.html

```
<html>
<head>
</head>
<body>
  <p>Hi!</p>
</body>
</html>
```

Problem started to appear in 0.45.0, which says it updated to Chromium 81.

Still works in 0.44.6, which has Chromium 80.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
