### ISSUE TITLE
crash on loading C++ addon

### ISSUE THREAD

**Issue by wesleyted00** [nwjs/nw.js#7453]
NWJS Version : 0.45.4
Operating System :MacOS Catalina

### Expected behavior

C++ native addon should be loaded.

### Actual behavior

C++ native addon loading can cause app crash.

### How to reproduce
1: Make a c++ node addon from https://nodejs.org/api/addons.html#addons_hello_world
 Just use the hello.cc and build it to addon.node

 It should be noted that this addon.node can be loaded in a native Node 14.0.0 command line.

2: Make an empty NW.js app with a simplest index.html.
```
<html><body>test</body></html>
```

3: Use nwjs sdk version to run the app.

4: Open the DevTool and load the addon.node using `require('addon')`. Now the app will crash!

**Comment by rogerwang** [comment]
It should be recompiled with nw-gyp.
