### ISSUE TITLE
NW.js runs slow on Amazon EC2, when not connected remotely.

### ISSUE THREAD

**Issue by batchhero** [nwjs/nw.js#7455]
Hello, I'm running a "server" with NW.js on AWS (EC2) for a small game of mine.

When I am remotely connected to the instance, the server runs very quickly, as expected.

But, when I'm disconnected from the instance, the server becomes VERY slow. I'm unsure how to work around this, as I don't want to be constantly remotely connected to keep the server running fast. Thanks for viewing my issue!

**Comment by rbfowler9lfc** [comment]
Try adding `--disable-background-timer-throttling` to `chromium-args` in the manifest.

**Comment by batchhero** [comment]
Hi, thanks for your reply! I added that command line argument (I am using NW.js export tool with Construct 3) but the same issue is still present.
![image](https://user-images.githubusercontent.com/42481573/80589614-81b8a080-89e8-11ea-8548-6189601637b8.png)

**Comment by batchhero** [comment]
I also confirmed that argument was included with `chromium-args` in package.json

**Comment by batchhero** [comment]
I found the fix! Also add `--disable-raf-throttling` to `chromium-args`
