### ISSUE TITLE
crash "Invalid instance ID(0) from WebviewActionRequest.defaultAction"

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7457]
nwjs 0.44.6 crash with the same reason of
#7059

**Comment by chatcan** [comment]
[96406:775:0430/120855.944649:FATAL:logging_native_handler.cc(46)] Check failed: check_value. Error: WebView: Invalid instance ID (0) from WebViewActionRequest.defaultAction
0   nwjs Framework                      0x0000000111c64ef9 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 15158921
1   nwjs Framework                      0x0000000111b936d3 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 14300771
2   nwjs Framework                      0x0000000111ba794b v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 14383323
3   nwjs Framework                      0x00000001111686fb v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3638923
4   nwjs Framework                      0x000000011117600f v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3694495
5   nwjs Framework                      0x00000001103bb193 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 17939
6   nwjs Framework                      0x00000001103ba63c v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 15036
7   nwjs Framework                      0x00000001103b9bd2 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12370
8   nwjs Framework                      0x0000000110e70cd8 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 527464
9   nwjs Framework                      0x0000000110dfa4eb v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 42107
Task trace:
0   nwjs Framework                      0x0000000112889f25 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 27893429
IPC message handler context: 0x7FAEA945

[0430/120856.057632:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)

**Comment by chatcan** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/rc.html
![image](https://user-images.githubusercontent.com/11750641/80671251-e3a60280-8adb-11ea-89be-8f6161c07953.png)
![image](https://user-images.githubusercontent.com/11750641/80671290-fc161d00-8adb-11ea-9222-6cb8e729ca74.png)

**Comment by chatcan** [comment]
i find that the commit of  #7059 have been reseted in nwjs 0.44.6

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
