### ISSUE TITLE
Window.moveTo is not correct

### ISSUE THREAD

**Issue by Virius** [nwjs/nw.js#7460]
NWJS Version : 0.44.6, 0.45.4
Operating System : Windows 10 (on other OS not testing)

### Expected behavior

moveTo(-10000, -10000) move window to coordinate -10000, -10000

### Actual behavior

move to coordinate -12500, -12716

### How to reproduce

This issue is true for any negative coordinates, as well as for some positive coordinates.
Steps to reproduce
- run nw.exe and show console
- execute commands:
var w = nw.Window.get()
w.moveTo(-10000, -10000)
- Check current coordinates:
console.log(w.x, w.y)

**Comment by mishagin-tim** [comment]
Works well on version **v0.50.0**. Can be closed.
