### ISSUE TITLE
couldn't find nw fields in process.versions until a timeout

### ISSUE THREAD

**Issue by SelvarajKaruppusamy** [nwjs/nw.js#7462]
NWJS Version : 0.45.5 (latest stable)
Operating System: Windows 10

### Expected behavior

`process.versions` should have the same values irrespective of time or when it is called.

### Actual behavior

I am logging `process.versions` immediately (dump1) and after 0sec timeout (dump2). I expect both the dumps should have the same values but dump1 doesn't contain 'nw' related fields.

I have copied the code I used and my logs in below,

**Code:**
```
var versionDump1 = JSON.parse(JSON.stringify(process.versions));

setTimeout(function(){
    var versionDump2 = JSON.parse(JSON.stringify(process.versions));
    let fileData = {
        nodeOnly: versionDump1,
        nwEnabled: versionDump2
    };

    require('fs').writeFileSync('./log.txt', JSON.stringify(fileData, null, 2));

}, 0);
```

**Log:**
```
{
  "nodeOnly": {
    "http_parser": "2.8.0",
    "node": "10.1.0",
    "v8": "6.6.346.32",
    "uv": "1.20.2",
    "zlib": "1.2.11",
    "ares": "1.14.0",
    "modules": "64",
    "nghttp2": "1.29.0",
    "napi": "3",
    "openssl": "1.1.0h",
    "icu": "60.1",
    "unicode": "10.0",
    "cldr": "32.0",
    "tz": "2018c"
  },
  "nwEnabled": {
    "http_parser": "2.8.0",
    "node": "10.1.0",
    "v8": "6.6.346.32",
    "uv": "1.20.2",
    "zlib": "1.2.11",
    "ares": "1.14.0",
    "modules": "64",
    "nghttp2": "1.29.0",
    "napi": "3",
    "openssl": "1.1.0h",
    "icu": "60.1",
    "unicode": "10.0",
    "cldr": "32.0",
    "tz": "2018c",
    "nw": "0.30.5",
    "node-webkit": "0.30.5",
    "nw-commit-id": "29d01bf-33cd709-b58e580-00b3abb",
    "nw-flavor": "sdk",
    "chromium": "66.0.3359.181"
  }
}
```

### How to reproduce

- Extract the nwjs sdk that you have downloaded any copy _index.js, index.html, package.json_ files from attached.
- Launch the nw.exe and see the output in the _log.json_ file 

[experiment-process-versions.zip](https://github.com/nwjs/nw.js/files/4573232/experiment-process-versions.zip)

### Maybe this is not an issue

Maybe this is not an issue but I couldn't find and documentation that explains this behavior. If that is the case please let me know where I can find the documentation.

Thanks!

**Comment by tharatau** [comment]
Thanks for the bug report! Closing this since this bug is no longer present as of v0.74
