### ISSUE TITLE
[NW2] nw.Window.get() throws exception No current window

### ISSUE THREAD

**Issue by djcanard** [nwjs/nw.js#7467]
NWJS Version : 0.42.4 (and newer)
Operating System : Windows 10 64-bit
#7230

### Expected behavior

`nw.Window.get()` should get the current window.

### Actual behavior

It throws an exception with message `No current window`.

### How to reproduce

I tried several nw.js versions and the issue occurs since 0.42.4.
When I use `--disable-features=nw2` the exception does not occur.

I created a stripped down version of our full-blown app to demonstrate the issue.
See attachment.
[nwjs-window-get-example.zip](https://github.com/nwjs/nw.js/files/4598792/nwjs-window-get-example.zip)

**Comment by rogerwang** [comment]
You are creating a Chrome App window, not a NW window. So it's expected that `nw.Window.get()` will hit error. 

In NW2 mode the NW window is not implemented with Chrome App window anymore.

**Comment by djcanard** [comment]
We distribute our apps for several platforms; Windows, Linux, MacOS and Chromebooks using 1 codebase which is great!
So I guess we should rewrite the code that creates the window into two different mechanisms, one for ChromeOS and one for the other platforms, right? Or is there some other way to keep it one mechanism?
