### ISSUE TITLE
External ffmpeg binary is not used.

### ISSUE THREAD

**Issue by surunzi** [nwjs/nw.js#7471]
NWJS Version : 0.45.x
Operating System : Windows 10

### Expected behavior

Replacing ffmpeg.dll should make nw able to play H264 video format.

### Actual behavior

Replacing ffmpeg.dll has no effect at all.

### How to reproduce

http://demo.nimius.net/video_test/videos/test.mp4

I have just tested a few versions of nwjs, here is the conclusion:

For version 0.37.x and below, replacing ffmpeg did enable it to play h264 video format. Strangely, started from 0.38.x, it seems nwjs is not using ffmpeg to decode video at all. And it can play h264 without any modifications from version 0.38.x to 0.44.x.

Here comes the problem. h264 is not playable for nwjs 0.45.x and replacing ffmpeg has no effect. So basically there is no way to make nwjs 0.45.x support h264 right now.

**Comment by tlmason92** [comment]
@rogerwang We recently upgraded from nw.js 0.40.x to 0.45.4 and have encountered this same issue.  While we were using 0.40.1 mp4 videos played with no issues.

Please let us know how we can replace the ffmpeg.dll and enable us to play H264 video formats.

**Comment by djcanard** [comment]
Same issue here, I tested it on Windows 10 and Ubuntu 18.

**Comment by tsubasa652** [comment]
I still have this problem with version 0.46.0

OS:Mac OS Catalina 10.15.4

**Comment by Blatman** [comment]
MacOS 10.13.6 High Sierra

This problem also exists with MacOS.
Tested with 0.44.6-sdk and mp4 works fine - also as OP says nwjs works out of the box without changing the libffmpeg.dylib file (which wasn't always the case)  however 0.45.0 upto 0.47.0b1 do not work at all. :(
I tried 0.45.1-sdk with iTeufel's 0.45.1 dylib and still no good so something has changed with nwjs 0.45

Note: I have previously found that it is not usually necessary to have an exact match of version from the iTeufel site - one version has traditionally worked OK (at least on Mac) across a range of nwjs versions. Trying 0.45.1 dylib (latest) with nwjs 0.47.0b1 is still no good.

I notice that there is a bug registered for this on iTeufel's site (#91) but it looks like the wheels came off with nwjs 0.45

**Comment by iteufel** [comment]
@rogerwang It looks like proprietary_codecs is set to false when building.
http://buildbot-master.nwjs.io:8010/builders/nw46_mac64/builds/28/steps/gn/logs/stdio
https://www.chromium.org/audio-video

**Comment by rogerwang** [comment]
@iteufel I just set it to `true` and triggered a new build. Thanks.

**Comment by iteufel** [comment]
Thanks @rogerwang with the live build https://dl.nwjs.io/live-build/nw46/20200710-003549/1fc2cba92/v0.46.5/ it's working again.

**Comment by rogerwang** [comment]
Good to know it works. Closing for now.
