### ISSUE TITLE
Build native module node-pty fail with latest nwjs version

### ISSUE THREAD

**Issue by hhhoney** [nwjs/nw.js#7473]
Hello :), I found that some native modules (like `node-pty`) cannot be built under latest NW & nw-gyp.

> NWJS Version : 0.45.6 
nw-gyp version: 3.6.5
node version: 14.2.0
Operating System : macOS 10.15.4 (19E287) & Windows 10

### How to reproduce

Just run following commands
```bash
npm i --save node-pty@0.10.0-beta8
cd node_modules/node-pty
nw-gyp rebuild --arch=x64 --target=0.45.6
```

### Error Example
```bash
......
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:669:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:717:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
......
```

**Comment by GnorTech** [comment]
A workaround is to remove ~/.nw-gyp/0.45.6/src/util.h

**Comment by hhhoney** [comment]
Thanks, it works.

We will be rebuilding node modules in an automation process, so it will be a little bit awkward to perform this workaround inside our process.

Still looking forward to a new & updated release of nwjs! 😀
