### ISSUE TITLE
怎样去修改内置Chrome浏览器的一些初始设置，比如页面显示最小字体大小和最大字体大小

### ISSUE THREAD

**Issue by winston1991** [nwjs/nw.js#7475]
第一次接触这个伟大的项目，小白一个，请大神赐教！，自己感觉应该是要去调用Chrome扩展API，不知怎么去配置！

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

And please use English only in this project so all users can read it.

**Comment by winston1991** [comment]
I finally chose Electron
