### ISSUE TITLE
How do you change some of the initial Settings of the built-in Chrome browser, such as the page display minimum and maximum font sizes

### ISSUE THREAD

**Issue by winston1991** [nwjs/nw.js#7476]
1. Before reporting, try reproducing against the latest version of NWJS.
nwjs-v0.45.6-win-x64

2. Issue tracker is only for bugs and feature requests, in English only.
  Just don't know how to set it

  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========
NWJS Version :  nwjs-v0.45.6
Operating System : win7 64bit

### Expected behavior
The font in the web page is set to 4px, but the display is 12px

### Actual behavior
The font is set to 4px and the display is also 4px

**Comment by winston1991** [comment]
@rogerwang Please give me some directions

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
The issue system is for bug reporting and developer task tracking, not questions / general discussion. Thanks.

**Comment by winston1991** [comment]
@rogerwang https://groups.google.com/forum/#!forum/nwjs-general this website  is not accessible in China, Please give some directions, Thanks

**Comment by winston1991** [comment]
@rogerwang 你是中国人吗？我看你也应该姓王啊

**Comment by winston1991** [comment]
I finally chose Electron
