### ISSUE TITLE
using sqlite3 will crash

### ISSUE THREAD

**Issue by hxt0630** [nwjs/nw.js#7478]
NWJS Version : v0.45.6
Operating System : win7 win10

### Expected behavior

I can bulid node_sqlite3.node success,but strart nw.exe will crash; 

use the demo code

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
</head>

<body>
    <div id="app">

    </div>
    <script>
        var sqlite3 = require('sqlite3').verbose();
        var db = new sqlite3.Database(':memory:');

        db.serialize(function () {
            db.run("CREATE TABLE lorem (info TEXT)");

            var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
            for (var i = 0; i < 10; i++) {
                stmt.run("Ipsum " + i);
            }
            stmt.finalize();

            db.each("SELECT rowid AS id, info FROM lorem", function (err, row) {
                console.log(row.id + ": " + row.info);
            });
        });

        db.close();
    </script>
</body>

</html>

**Comment by rogerwang** [comment]
Please check https://github.com/nwjs/nw-gyp/issues/130#issuecomment-541680390

**Comment by hxt0630** [comment]
it works for me; thank you
