### ISSUE TITLE
Contain nwjs project in subfolder

### ISSUE THREAD

**Issue by brinsche** [nwjs/nw.js#7479]
I'm working on an nwjs project which wraps an existing application consisting of an index.html and another folder with more html and javascript like this:
```.
├── index.html
└── html
    └── more-html
```
Is it possible to create a nwjs project resulting in the following directory structure?:
```
.
├── app
│   ├── App.js
│   ├── custom.js
│   ├── node_modules
│   ├── nwjs-support-files
│   └── package.json
├── index.html
└── html
    └── more-html
```
`App.js` would need to be able to reference the `index.html` of the parent so something like this:
```
nw.Window.open('../index.html', {
    inject_js_start: "custom.js"
}, function(win) {});
```

https://github.com/nwjs/nw.js/issues/4672#issuecomment-288901140 talks about a flag to set the project root but it doesn't seem to be implemented or documented

I also tried constructing a url starting with `file://` scheme but then the `nw` apis don't seem to be available as described in #4806

**Comment by rogerwang** [comment]
No... as the directory where the manifest resides is the root directory of the 'chrome-extension://' protocol.

File protocol should work, I'll see that bug. So closing this one.

Another workaround would be opening a local http server.
