### ISSUE TITLE
Can't build nwjs

### ISSUE THREAD

**Issue by tsubasa806** [nwjs/nw.js#7481]
NWJS Version :nw45 0.45.6
Operating System :Mac OS Catalina 10.15.4

### Expected behavior

Generate ninja build files

### Actual behavior

$ gn gen out/nw --args='is_debug=false is_component_ffmpeg=true target_cpu="x64" use_sysroot=false'

ERROR Unresolved dependencies.
//content/nw:dump(//build/toolchain/mac:clang_x64)
  needs //chrome:nw_sym_archive(//build/toolchain/mac:clang_x64)

### How to reproduce

gclient config --name = src https://github.com/nwjs/chromium.src.git@origin/ nw45

If I follow the documentation I get this issue

https://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/

**Comment by tsubasa806** [comment]
clang --version
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by rowenbuzz** [comment]
@tsubasa806 It looks like you have an extra space from Step 1 between '@origin/' and 'nw45'

So:
gclient config --name = src https://github.com/nwjs/chromium.src.git@origin/nw45

**Comment by tsubasa652** [comment]
I just typed a space by mistake when I entered this issue

**Comment by tsubasa806** [comment]
I just typed a space by mistake when I entered this issue

**Comment by rogerwang** [comment]
It looks like you don't have proper commit/branch checkout out in the repos.
