### ISSUE TITLE
INFORMATION

### ISSUE THREAD

**Issue by devemloop** [nwjs/nw.js#7482]
NWJS Version : 0.45.6-sdk
Operating System : Windows

Exists an alternative for Electron API "app.setAsDefaultProtocolClient" in nwjs ?
i can't register a custom protocol for my application

example

**myapp://settings**

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by TheJaredWilcurt** [comment]
@devemloop This may be achievable as a stand-alone Node module. Though could potentially be easier to integrate with NW.js if it were built in, in a similar way to that of Electron.

I've found a potential way of doing this in a stand alone module and have created a repo to document this possible solution, and to be a placeholder for a possible library in the future.

* https://github.com/nwutils/setAsDefaultProtocolClient
