### ISSUE TITLE
Reliable NWjs Crash With Service Workers

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7483]
NWJS Version: v0.45.0+
Operating System: Windows 10
Reproduction: https://downloads.scirra.com/c3-desktop/c3-nwjs-package-beta.zip
Log File (forced crash only): [debug.log](https://github.com/nwjs/nw.js/files/4657394/debug.log)

### Expected behavior
NWjs shouldn't close or crash.

### Actual behavior
NWjs randomly closes or crashes with service workers enabled.

### How to reproduce
1. Download reproduction project and latest [NWjs](https://dl.nwjs.io/v0.46.0/nwjs-sdk-v0.46.0-win-x64.zip) (v0.45.0+)
2. Paste zip contents into NWjs folder and run Construct 3
3. Stay in the main menu for a while and notice crash

Force webworker crash:
1. Open Devtools and go to application
2. Uncheck everything except service workers (see below)
3. Clear site data, close devtools and focus main window
4. Notice NWjs crash after service worker update/removal

![image](https://user-images.githubusercontent.com/15656049/82455832-b84b7d80-9ab3-11ea-8ecd-d5e6bfc2070a.png)

**Comment by TheRealDannyyy** [comment]
@ashleyscirra You're an expert with web workers and probably know the exact cause for this. It seems to mainly happen when C3 is ready for offline mode (registering web worker) or similar worker removal/updates.

**Comment by cb130felix** [comment]
+1 on this, tried replicating the steps and the app closes after following the steps.

**Comment by AshleyScirra** [comment]
If it doesn't happen in Chrome, it's probably an NW.js bug.

**Comment by TheRealDannyyy** [comment]
Can't reproduce anymore with NWjs 0.46.1, closing.
