### ISSUE TITLE
Inconsistent behavior of supporting Javascript standards

### ISSUE THREAD

**Issue by wesleyted00** [nwjs/nw.js#7485]
In the latest NW.js, the lastest Javascript features (like private fields) are already supported. However, those features cannot be supported by `nwjc` tool.

The code example:
```
class Rectangle {
  #height = 0;
  #width;
  static #PI = 22 / 7; 
  constructor(height, width) {    
    this.#height = height;
    this.#width = width;
  }

  static foo1(){Rectangle.#foo2();}
  static #foo2(){console.log(Rectangle.#PI);}

}
```

**Comment by rogerwang** [comment]
Your code hit 'syntax error' in latest Chrome browser as well...
