### ISSUE TITLE
NW2: window blur event does not execute multiple event listeners

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#7488]
NWJS Version: tested with 0.45.5 and 0.46.0
Operating System: Arch Linux with KDE Plasma

### Description

The window `blur` event on the new NW2 implementation has already received a bugfix in #7327, but when adding multiple event listeners, all listeners except the first one get ignored.

When disabling NW2 in the `chromium-args` field, the issue does not occur.

### How to reproduce

See my bug demonstration here:
https://github.com/bastimeyer/nwjs-blur-event-bug

In the dev-tools console you'll see that only "blur 1" gets logged, whereas the `focus` event works as expected and logs "focus 1" and "focus 2".

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
