### ISSUE TITLE
Remote debug with normal flavor distribuition

### ISSUE THREAD

**Issue by danielmorena** [nwjs/nw.js#7495]
Is it possible to use the remote debugging option with the plain normal flavor of nwjs? As far as I understand the documentation, the chrome dev tools will be on the browser inspecting the app, not in the nwjs itself, and thus allowing to inspect via browser. Is this correct?

**Comment by rogerwang** [comment]
No. The devtools is not included/enabled in the normal flavor.

Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
