### ISSUE TITLE
NW2: with nwfaketop get chrome.windows undefined

### ISSUE THREAD

**Issue by srguiwiz** [nwjs/nw.js#7498]
NWJS Version : 0.46.2
Operating System : CentOS 7.8

### Expected behavior

A call

```
nw.Window.get(iframe.contentWindow)
```

should work even if that `iframe` is an `nwfaketop`. It worked before NW2 when in NW1.

### Actual behavior

There is an error with a surprisingly short stack trace

```
extensions::nw.Window:107 Uncaught TypeError: Cannot read property 'onWindowChanged' of undefined
    at new NWWindow (extensions::nw.Window:107)
    at extensions::nw.Window:723
```
and our code doesn't run after that.

At a breakpoint at that line `extensions::nw.Window:107` inside `function NWWindow(cWindow)` in the code

```
  chrome.windows.onWindowChanged.addListener(updateWindowAttributes);
```

the chrome.windows is undefined.

That is called from line 723 inside `apiBridge.registerCustomHook(function(bindingsAPI)` code

```
currentNWWindow = new NWWindow;
```

We have narrowed it down it occurs with an iframe that has `nwfaketop`.

Per developer tools call stack it is caused by our application calling

```
nw.Window.get(iframe.contentWindow)
```

Not knowing when code would get to line 107, I guess maybe a new [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) would be a reasonable single character fix:

```
chrome.windows?.onWindowChanged.addListener(updateWindowAttributes);
```

### How to reproduce

Simplest NW.js app with `index.html`

```
<html>
<head>
</head>
<body>
  <iframe
    src="http://www.wikipedia.org/"
    nwfaketop
    width="100%" height="80%"></iframe>
  <script>
    function loadListener(event) {
      let iframe = event.target;
      console.log(`iframe ${iframe.src} has loaded ${iframe.contentWindow.location.href}`);
      let nwWindow = nw.Window.get(iframe.contentWindow);
    }
    document.querySelector("iframe").addEventListener("load", loadListener);
    nw.Window.get().showDevTools();
  </script>
</body>
</html>
```

No rush.  For now we can run with NW2 disabled.

**Comment by srguiwiz** [comment]
Hold on.  There is actually more in the call stack in developer tools.  I am debugging more.  Maybe this isn't a bug.  I will update this as soon as I know.

**Comment by srguiwiz** [comment]
Updated description with a short `index.html` that causes the error.

**Comment by srguiwiz** [comment]
We found out for our need we are fine with
```
let nwWindow = nw.Window.get(window);
```
instead of passing the iframe's contentWindow.  Hence, we were able to switch to using NW2, i.e. no longer disabling it.

Therefore, this no longer is an issue for us.  It probably is okay to close this issue.

**Comment by rogerwang** [comment]
cc #7230
