### ISSUE TITLE
Native File System API close() method never resolves in NW.js only

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7500]
NWJS Version : 0.46.2
Operating System : Windows 10 64-bit

### How to reproduce
Demo: 
[nwjs-file-close-issue.zip](https://github.com/nwjs/nw.js/files/4754136/nwjs-file-close-issue.zip)

This uses the Native File System API (also in Chrome) to write a text file which says "Hello world" when you click "Save".

To test in Chrome, make sure the 'Native File System API' flag is enabled in chrome://flags.
To test in NW.js, make sure `"chromium-args": "--enable-features=NativeFileSystemAPI"` is specified in package.json (the provided demo already does this).

Click 'Save' and observe the console log entries and the files saved to the chosen location.

### Expected behavior

Save a single text file to the chosen location, with contents "Hello world", and console log all messages ending with "All done".

### Actual behavior

In NW.js only, the call to `writable.close()` never resolves. It therefore does not proceed to log "All done".

This also leaves the saved file in an incomplete state: the file is created but is sized 0 bytes, and there is another file with the same name but with .crswap appended (e.g. test.txt.crswap) which has the content "Hello world". Presumably the call to close() swaps these files, but this failed.

In the equivalent Chrome version with the flag set, it works correctly, so this bug is specific to NW.js.

Note: the Native File System API changed in M83 so the use of createWritable() is new.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by AshleyScirra** [comment]
Great, thanks - confirmed it's working as expected in nightly 20200612.
