### ISSUE TITLE
nw2: close event on Window is not firing if you open remote url

### ISSUE THREAD

**Issue by hrocha1** [nwjs/nw.js#7503]
NWJS Version : nwjs-sdk-v0.46.2-win-ia32
Operating System : Windows 10

### Expected behavior

Close event should happen while closing a window no matter if it's content is local file or remote url.

### Actual behavior

Close event is emitted only when closing a window with local file.

This problem happens only with nw2 mode enable. It works correctly with `--disable-features=nw2` switch.

### How to reproduce

Download the attached file, extract it and run nw.exe against the `issue10` directory.

[issue10.zip](https://github.com/nwjs/nw.js/files/4761208/issue10.zip)

**Comment by rogerwang** [comment]
CC #7230

**Comment by hrocha1** [comment]
I've made a test for this issue, hope that helps.

**Comment by rogerwang** [comment]
> I've made a test for this issue, hope that helps.

Thanks. That's very helpful. I'll look to review it.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by hrocha1** [comment]
The [nightly build](http://dl.nwjs.io/live-build/nw46/20200614-162000/eabb61c36/v0.46.3/) is passing both the NW.js test and our internal tests, thanks.
