### ISSUE TITLE
devtools are unusable when code is paused.

### ISSUE THREAD

**Issue by trusktr** [nwjs/nw.js#7510]
NWJS Version : 0.46.2
Operating System : Manjaro Linux

### Expected behavior

When I pause code in devtools, I should be able to run commands in the console to test things out, log values, etc.

### Actual behavior

It works, but it can take a few minutes before anything finally runs.

Pressing the resume button takes 30 seconds for things to resume.

TLDR, I can't debug using the `pause` feature.

Workaround: rely only on `console.log` output without pausing the code.

### How to reproduce

- load code with `<script src=""`
- Not sure if it has anything to do with it, but that code `require`s Node modules.

Unfortunately I have a private repo I can not share. I don't have a public simple reproduction yet.

The code works fine in Electron and NW.js, but no issues with devtools in Electron. There doesn't seem to be anything inherently wrong with the code, which runs fine. It's just console input in NW.js devtools is unresponsive while paused.

**Comment by trusktr** [comment]
Does this have to do with the browser context being tied to the Node context? Does that somehow block devtools from operating in certain conditions?

**Comment by TheJaredWilcurt** [comment]
Cannot reproduce. The issue is with your code or the module you are using.

![GIF showing unable to reproduce](https://user-images.githubusercontent.com/4629794/85177538-50bb5600-b24a-11ea-84cb-a27532a391a5.gif)

## [7510_Unable_to_reproduce.zip](https://github.com/nwjs/nw.js/files/4806590/7510.zip)

* `package.json`
  ```json
  {
    "name": "7510",
    "main": "index.html",
    "dependencies": {
      "nw": "sdk"
    }
  }

  ```
* `index.html`
  ```html
  <!DOCTYPE html>
  <html>
    <body>
      <h1>#7510</h1>
      <script src="index.js"></script>
    </body>
  </html>

  ```
* `index.js`
  ```js
  const fs = require('fs');
  const manifest = JSON.parse(fs.readFileSync('./package.json'));
  debugger;
  console.log(manifest);
  ```

**Comment by trusktr** [comment]
Unfortunately I don't have a simple reproduction. At the moment I have a proprietary app that I ported over from Electron. The app is working, and the console becomes unresponsive only when I pause the code. As a workaround, I can avoid pausing the code, and rely only on console.log outputs (less ideal, but doable).

**Comment by rogerwang** [comment]
Maybe the devtools opens in the same process with the application somehow, where it is not supposed to do so. You can confirm this by checking the number of renderer processes after the devtools is opened (it should open another nw process with the argument `--type=renderer`.

If you can share your application, I can try to reproduce and fix it.

**Comment by rogerwang** [comment]
close until more information is available.
