### ISSUE TITLE
Extract info about gpu

### ISSUE THREAD

**Issue by polhaghverdian** [nwjs/nw.js#7513]
Hi,

according to this old info below, it should work to extract gpu info. But does not work. 

https://github.com/nwjs/nw.js/wiki/Extract-info-about-gpu

Is their any other way to extract gpu info?  More specifically i would like to get which gpu is being used with DesktopCapture, when having both a integrated and discrete gpu.

**Comment by rogerwang** [comment]
Run `nw --url=chrome://gpu` should work. 
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
