### ISSUE TITLE
Open new web page and auto fill form

### ISSUE THREAD

**Issue by codersmoon** [nwjs/nw.js#7515]
Hi. I use Node web kit and ty for this.I want to open new web page and auto fill form on this web page.Like this:D

```
nw.Window.open('http://awebpage.com/login', {}, function (new_win) {
document.getElementsByClassName("logname").value="xxx";
});
```
I know this not work.But my question is possible at  node web kit?

**Comment by tharatau** [comment]
Short answer: yes. Long answer: try and explore that yourself.
