### ISSUE TITLE
Too many Windows after macOS restart

### ISSUE THREAD

**Issue by theDevelopper** [nwjs/nw.js#7516]
NWJS Version : 0.46.3
Operating System : macOS 10.15.5 (latest Catalina)

### Expected behaviour

I have an NWJS App running and this App has one visible main window with id and a hidden one with `new_instance: true` and an id. When restarting the OS with the option to reopen current apps then I expect to have the App opened with one visible main window.

### Actual behaviour

When restarting the OS with the option to reopen current apps then I actually see three windows. The main window is there twice (overlaying each other) and the initially hidden window is visible. I assume there is a fourth hidden one.

It looks like the "old" windows are recreated and a new main one started.

### How to reproduce

Code:
[mac-restart-issue-examle.zip](https://github.com/nwjs/nw.js/files/4863207/mac-restart-issue-examle.zip)

I have 2 html files. One for the visible window and one for the hidden one. The hidden one is created with JS like this:

```
nw.Window.open('hidden.html', {
	id: 'hidden',
	show: false,
	new_instance: true,
});
```

I then download the latest nwjs form the website and put the code inside the nw.app folder and start the app. I see one window as expected. I then restart macOS and I see three windows - how unexpected.

Last time I used this setup was version 0.41.3 and it worked as expected. So somewhere along the line it broke which prevents me form upgrading nwjs.

**Comment by theDevelopper** [comment]
any updates on this bug?

**Comment by theDevelopper** [comment]
adding `--disable-features=nw2` to the chromium-args seems to fix the issue for me. But that means it is blocker for the nw1 removal. (https://github.com/nwjs/nw.js/issues/7230)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
