### ISSUE TITLE
Incorrect handling of borders when resizable is false

### ISSUE THREAD

**Issue by sysrage** [nwjs/nw.js#7521]
NWJS Version : 0.47
Operating System : Windows 10 18363.900

### Expected behavior

When a window's resizable property is set to false, the window frame/border/etc. should not start showing black outside borders and other odd artifacts.

### Actual behavior

When resizable is set to false, windows are incorrectly gaining an outer black border on the sides and bottom. They're also gaining a 'border' between the titlebar and the window content which causes several issues. If you mouseover the close button, the button is highlighted red (as expected). When moving the mouse away, the bottom 'border' remains red. This also results in the titlebar being "too short" when content is covering the "top border".

![image](https://user-images.githubusercontent.com/166781/87706690-ed9be100-c76d-11ea-9a7c-307058b7578d.png)

![image](https://user-images.githubusercontent.com/166781/87706711-f68cb280-c76d-11ea-817f-7420d7e73bf2.png)

### How to reproduce

Set resizable to false for any window, either through the window options when opening it or by using `setResizable()`. Easiest reproduction:

1. Launch nw.exe (SDK build) with no script/HTML.
2. Open console and run: `window.nw.Window.get().setResizable(false);`
3. Immediately observe the outer black border and incorrect lighter-grey top border.
4. Mouseover the close button to observe the red being 'stuck' in the incorrect top border.

**Comment by sysrage** [comment]
This also does NOT occur when running NW.js 0.47 with `--disable-features=nw2`. Adding as a blocking bug for removing NW1.

**Comment by rogerwang** [comment]
This is fixed in git and available in the [nightly build](http://dl.nwjs.io/live-build/).

**Comment by sysrage** [comment]
Thanks! I've verified that this fixes the borders as reported in this bug. Unsure if you're leaving bugs open until an official release, but this can be closed.
