### ISSUE TITLE
Not Able to Open Bin File

### ISSUE THREAD

**Issue by wwderw** [nwjs/nw.js#7523]
I downloaded both the normal and SDK versions of NWjs for Linux off the website.

I was able to us nwjc to create a bin file that I named test.bin.  In the script tag of my main html file I put 'nw.Window.get().evalNWBin(null, 'test.bin');'.

In the root folder of the sdk version, I placed my app files in a folder named package.nw.

I then executed the nw binary and it shows a window of the correct size and everything is good, but if I pull up the console it tells me that it open the file, it doesn't exist.  I have tried it in the app folder and next to the html page just in case I wasn't getting the path right.

I did try to use node, but I was getting all kinds of errors with the install and running, so I thought maybe just try directly off the site.

Ideas, thoughts?

**Comment by wwderw** [comment]
I feel like a newb.  I was giving the location from the html file and not from the nw binary.  Sorry about that.

**Comment by jerson-arch** [comment]
I also have the same error, when opening the application it crashes and closes suddenly, when I use "evalNWBin" from the index.html
