### ISSUE TITLE
0.48.0b1 - unable to drag app.

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7533]
High Sierra (10.13.6) - 0.48.0b1-sdk

Transparent app is unable to be dragged on screen - occurs on both nw1 and nw2.
With test app should be able to drag using blue area.

Works fine with 0.47.2-sdk.

Test app attached to #7532

**Comment by rogerwang** [comment]
Thanks for reporting. Will check it soon.

**Comment by rogerwang** [comment]
I just found it's not related to transparent windows -- feature is broken with normal windows too. So I'm changing the title of this issue. This is also a bug in upstream.  https://bugs.chromium.org/p/chromium/issues/detail?id=1093121

Will fix it soon.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next build.
