### ISSUE TITLE
学习现在需要支付吗

### ISSUE THREAD

**Issue by LaoCheng-cjs** [nwjs/nw.js#7534]
我在此网站内，需要支付人民币50元才能进入交流群。是否你们官方授权的了
https://nwjs.org.cn/group.html

**Comment by 18628271760** [comment]
开源的，要你花钱去交流，肯定是歪的。

**Comment by rogerwang** [comment]
It is not affiliated with the official NW.js project.

Please use English in this project so all users can read.
