### ISSUE TITLE
A  white page generated when "download" excuted

### ISSUE THREAD

**Issue by 18628271760** [nwjs/nw.js#7535]
NWJS Version :  0.47.1-win-x64
Operating System : Win10 X64

I use NWJS package an exe,  most function as same as web side. But when excute "download file" action, PC side(powered by NWJS) generate a while page which shoule manully close. And no same situation produce on web side. I am a .Neter has no much knowledge on web side. So, is there anyone can help to find the pain point? TKS!

![White page issue](https://user-images.githubusercontent.com/38900261/89364412-006a5b80-d705-11ea-8d48-620f4ef39542.png)

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by 18628271760** [comment]
> Could you please provide a full sample (not code snippets) so we can reproduce?

Sure，but talk with my line manager, I can only provide it privately to your side ( make sure only NW.js support team can review that). So could u show me an Email address? TKS.

**Comment by 18628271760** [comment]
Hi team，
For issue&nbsp;7535, I put the full sample into the package for reproduce purpose.&nbsp;


Pls. use password login with the test account as follow:
user account: 001204
password:&nbsp;xbwl963852


And in my test account, I have already uploading an video so that u can download directly. Any question, pls.let me know.
&nbsp; &nbsp; &nbsp;&nbsp;
Appreciate the feedback from your side.&nbsp;


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Ares Chen
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nwjs/nw.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 下午3:16
收件人:&nbsp;"nwjs/nw.js"<nw.js@noreply.github.com&gt;;
抄送:&nbsp;"盾宇"<847833088@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nwjs/nw.js] A  white page generated when "download" excuted (#7535)





 
Could you please provide a full sample (not code snippets) so we can reproduce?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

海螺修改版.rar (71.14M, 2020年09月04日 15:21 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2034376525d4e9cb63dcbf571563561f020c545501025c044e550051564e505306561a075253521d5a5053010600575306520251336d648ac0f6eab5eddba080851a4504416359&code=c47e3cd0

**Comment by rogerwang** [comment]
Please send the full sample app to roger@nwjs.io . Thanks.

**Comment by lbw302301** [comment]
did you resolve this problem？i crossed the same problem
