### ISSUE TITLE
How to add "Exit Confirm" and "Loading waiting" in nw.js exe?

### ISSUE THREAD

**Issue by 18628271760** [nwjs/nw.js#7536]
NWJS Version : 0.47.1-win-x64
Operating System : win10 x64

Hi there,
I am a freshman to NW.js and handle a web package task. The task need package a web app into pc exe. And my boss wanna add "Loading waiting" ( before the first web page load, show a waitting local page or waitting flash, when load compeletelly jump to the specified page.) and "Exit Confirm" (which like the meassage box in WPF)  actions. I found  no helpful solution or demo via google and baidu.  Is the 2 action can be brought out without ask web developer do some change? I am just a .Neter which has no much knowledge about this. Any solution and suggestion is appreciated.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
