### ISSUE TITLE
Can NW.js make the icon flash as Wechat/QQ when get a message?

### ISSUE THREAD

**Issue by 18628271760** [nwjs/nw.js#7537]
nwjs version: 0.47.1-win-x64
os: Win10, x64

Hi team,
I was asked to do some research about nw.js exe. Our team are buiding a web tool which contain communication function. I got some new seach pre-research requests as follwing:
1.  Make the icon flash as Wechat/QQ/Skype when get a new message.
2.  Right click the icon on desktop, show a custom functionality bill include: (1)open (2)setting (3)Open with system (4) exit.

I have read the official document but find no solution to the above requires. Are the requires supported in current nwjs framework? Appreciate your feedback.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
