### ISSUE TITLE
0.48.0b1 - YouTube video crashes app on start

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7538]
High Sierra 10.13.6 - tested with 0.48.0b1-sdk, 0.47.3-sdk, chromium 86

Have attached a test app  - just need npm install to load up video.js modules.

YouTube video will crash badly at start with 0.48 but works fine with 0.47.3 and also Chromium 86 with index.html (couldn't get 85 easily).

The m4v and m3u8 videos will work fine on 0.48 but need the iTeufel libffmpeg.dylib to fully function. The updated dylib makes no difference to the youtube video.

<img width="1161" alt="crashlog" src="https://user-images.githubusercontent.com/11089335/89649433-af9b6400-d8b8-11ea-8b5c-c991f4f19f05.png">

[VideoCrashBug.zip](https://github.com/nwjs/nw.js/files/5041568/VideoCrashBug.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
