### ISSUE TITLE
No such file or directory "graph_tab.html" when compiling deploy (0.47.2)

### ISSUE THREAD

**Issue by KanomiDim** [nwjs/nw.js#7541]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.47.2
Operating System : Windows 10 x64

GN Args:
nwjs_sdk=false
is_debug=false
is_component_ffmpeg=true
target_cpu="x64"
ffmpeg_branding="Chrome"

I was trying to compile a deploy version of 0.47.2.

I ran the following commands:

$ set GYP_DEFINES="target_arch=x64 nwjs_sdk=0"

$ GYP_CHROMIUM_NO_ACTION=0 ./build/gyp_chromium -I third_party/node-nw/common.gypi -D building_nw=1 -D clang=1 third_party/node-nw/node.gyp

and when i ran this, i got an exception:

$ ninja -C out/nw nwjs
ninja: Entering directory `out/nw'
[1/1] Regenerating ninja files
[1/316] ACTION //chrome/browser:resources_grit(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/browser/resources_grit.d.stamp gen/chrome/grit/browser_resources.h gen/chrome/browser_resources.pak gen/chrome/browser_resources.pak.info
C:/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe ../../tools/grit/grit.py -i ../../chrome/browser/nwjs_resources.grd build -o gen/chrome --depdir . --depfile gen/chrome/browser/resources_grit.d --write-only-new=1 --depend-on-stamp -D scale_factors=2x -D _chromium -E CHROMIUM_BUILD=chromium -D toolkit_views -D use_aura -D enable_arcore=false -D enable_background_mode=true -D enable_background_contents=true -D enable_extensions=true -D enable_hangout_services_extension=false -D enable_plugins=true -D enable_print_preview=true -D enable_printing=true -D enable_service_discovery=true -D enable_supervised_users=false -D enable_vr=true -D enable_webui_tab_strip=true -D safe_browsing_mode=0 -D optimize_webui=true -E additional_modules_list_file=gen/chrome/browser/internal/additional_modules_list.txt -E root_gen_dir=gen --brotli brotli.exe -f gen/tools/gritsettings/default_resource_ids -p ../../tools/gritsettings/startup_resources_win.txt --assert-file-list obj/chrome/browser/resources_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include allowexternalscript="true" compress="gzip" file="${root_gen_dir}\chrome\browser\resources\discards\graph_tab.html" name="IDR_DISCARDS_GRAPH_TAB_HTML" type="BINDATA" use_base_dir="false" />: [Errno 2] No such file or directory: u'..\\..\\out\\nw\\gen\\chrome\\browser\\resources\\discards\\graph_tab.html'
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 29, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
  File "C:\nwjs\nwjs472\src\tools\grit\grit\grit_runner.py", line 314, in Main
    return toolobject.Run(options, args[1:])
  File "C:\nwjs\nwjs472\src\tools\grit\grit\tool\build.py", line 274, in Run
    self.Process()
  File "C:\nwjs\nwjs472\src\tools\grit\grit\tool\build.py", line 409, in Process
    self.ProcessNode(self.res, output, tmpfile)
  File "C:\nwjs\nwjs472\src\tools\grit\grit\tool\build.py", line 333, in ProcessNode
    formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "C:\nwjs\nwjs472\src\tools\grit\grit\format\data_pack.py", line 90, in Format
    value = node.GetDataPackValue(lang, util.BINARY)
  File "C:\nwjs\nwjs472\src\tools\grit\grit\node\include.py", line 109, in GetDataPackValue
    data = util.ReadFile(filename, util.BINARY)
  File "C:\nwjs\nwjs472\src\tools\grit\grit\util.py", line 214, in ReadFile
    with io.open(filename, mode, encoding=encoding) as f:
IOError: [Errno 2] No such file or directory: u'..\\..\\out\\nw\\gen\\chrome\\browser\\resources\\discards\\graph_tab.html'
[2/316] ACTION //components/resources:about_credits(//build/toolchain/win:win_clang_x64)
ninja: build stopped: subcommand failed.

I saw similar issues here:
https://gist.github.com/llamasoft/33af03b73945a84d7624460d67b922ab
https://github.com/nwjs/chromium.src/issues/145

but none of the proposed solutions worked.

**Comment by rogerwang** [comment]
Maybe the repos are not synced at the correct commit.

**Comment by KanomiDim** [comment]
what does it means?

i pulled from bracnh nw47 about a few weeks ago, right after that:


Commits on Aug 1, 2020
src: update to chromium 84.0.4147.105 …

@rogerwang
rogerwang committed 11 days ago

Commit ID:
5b392949e3ea2409fe81aa36ac1db59c1313e6db

**Comment by rogerwang** [comment]
This is fixed in git. Thanks for reporting.
