### ISSUE TITLE
Performing browser close action stopped working in NWjs v0.46.3+

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7542]
NWJS Version: v0.46.3+
Operating System: Windows 10

### Expected behavior
Basic browser actions like closing or requesting fullscreen, leads to NWjs freezing or not working as expected.

### Actual behavior
It should work like it did in NWjs versions prior to v0.46.3.

### How to reproduce
1. Download [NWjs v0.46.3+](https://dl.nwjs.io/)
2. Extract and run [package.zip](https://github.com/nwjs/nw.js/files/5063987/package.zip)
3. Press "close" or ESCAPE key to performance basic browser close
4. Notice application freezing and not closing as expected

**Comment by TheRealDannyyy** [comment]
It could be related to the browser permissions system but not sure. Can't debug it myself.

**Comment by TheRealDannyyy** [comment]
This issue is probably related to #7565 but that issue only covers the fullscreen action.

**Comment by avishaymizrav** [comment]
I just encountered this bug too, it actually starts from 0.46.0, 0.45.6 still works for me.

**Comment by rogerwang** [comment]
Could you please provide another sample? Yours is a big minified JS file and it's not clear what it is doing.

**Comment by avishaymizrav** [comment]
> Could you please provide another sample? Yours is a big minified JS file and it's not clear what it is doing.

Here's one, touch the close text or press esc to send close browser request.
[package.zip](https://github.com/nwjs/nw.js/files/5332083/package.zip)

**Comment by rogerwang** [comment]
@avishaymizrav yours are no different...

**Comment by TheAresjej** [comment]
#7629 - maybe this will help 😋

**Comment by TheRealDannyyy** [comment]
I just tested this again with a minimal repro and it seems to be caused by the game engine (Construct 2).
Not sure why, would have to get in contact withe game engine developer.
