### ISSUE TITLE
MacOS - 0.47.3-sdk crashes on start 

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7543]
High Sierra 10.13.6 

The last few builds of 0.47.3-sdk appear to be crashing on start - the dock icon bounces and the unidentified dev dialog shows. When the dialog is clicked the nwjs package closes without producing a profile, etc.

The last good build I have got is from '80365d7-680ccde-61fffcc-a4c578a'

Looks like the sys logs fill up with MacOS errors -67050 Finder and syspolicyd

**Comment by rogerwang** [comment]
Thanks for reporting. Are you running any app?

**Comment by Blatman** [comment]
@rogerwang - No, I just ran the nwjs.app (double-clicked) from within the unzipped folder to check the the nwjs splash

**Comment by rogerwang** [comment]
It works for me with 10.14 and 10.15. What about this build? http://dl.nwjs.io/live-build/nw47/20200812-162000/bc64b3d19/v0.47.3/

**Comment by Blatman** [comment]
Strange.
Tried the above build and fails when I OK the Unidentified Dev dialog. 

Can't get any nwjs logs since the crash occurs before the profile is created - I will wait for the 0.47.4 build and see if same - fortunately no issue with 0.48 - yet!

Done some more tests and I suspect 10.13 UD (Unidentified Developer) signing is affecting this.

10.13 iMac
OK - nwjs-sdk-v0.47.2-osx-x64-20200801-162000-5b392949e - got UD dialog on 1st run - allowed OK
Fail - nwjs-sdk-v0.47.3-osx-x64-20200805-162000-c94c71734 - got UD dialog on 1st run - crash
OK - nwjs-sdk-v0.47.3-osx-x64-20200806-162000-c1f5bb69f  - didn't have UD dialog on 1st run - detected previous allow?
OK - nwjs-sdk-v0.47.3-osx-x64-20200808-162000-80365d78e - already allowed previously
Fail - nwjs-sdk-v0.47.3-osx-x6420200812-162000-bc64b3d19 - got UD dialog on 1st run - crash
Fail - nwjs-sdk-v0.47.3-osx-x64-20200815-162000-7906be1fe - got UD dialog on 1st run - crash

10.14 MBP
OK - nwjs-sdk-v0.47.2-osx-x64-20200801-162000-5b392949e - no UD dialog on 1st run
OK - nwjs-sdk-v0.47.3-osx-x64-20200805-162000-c94c71734 - no UD dialog on 1st run
OK - nwjs-sdk-v0.47.3-osx-x64-20200806-162000-c1f5bb69f  - no UD dialog on 1st run
OK - nwjs-sdk-v0.47.3-osx-x64-20200808-162000-80365d78e - no UD dialog on 1st run
OK - nwjs-sdk-v0.47.3-osx-x6420200812-162000-bc64b3d19 - no UD dialog on 1st run
OK - nwjs-sdk-v0.47.3-osx-x64-20200815-162000-7906be1fe - no UD dialog on 1st run

Test with nwjs-sdk-v0.47.3-osx-x64-20200815-162000-7906be1fe
Extracted on MBP and ran OK - no UD dialog
Copied MBP run nwjs to imac and it runs OK
Copied downloaded build to imac - extracted and ran nwjs - got UD dialog and fail

So - 
if the nwjs is downloaded and run on MBP (10.14) it has no UD dialog and works OK on both machines.
if the nwjs is downloaded and run on imac (10.13) it gets UD dialog and fails on either machine. 

Seems to imply that the UD processing (10.13) on first run does something to the nwjs package making it fail on both machines whereas 10.14 is OK (there is no UD dialog process). The package must be altered by the 10.13 UD signing on first run otherwise the package should run ok on the other machine which it doesn't if the first run is done on 10.13.

I'm baffled as to why 0.48 is OK and only had issue with 0.47.3 with 0.47.2 and prior OK

**Comment by Blatman** [comment]
Tried some other stuff -

$ spctl -a -t exec -vv /Users/xxxx/Desktop/nwjs.app   (0.47.2 last build) OK
/Users/xxxx/Desktop/nwjs.app: accepted

$ spctl -a -t exec -vv /Users/xxxx/Desktop/nwjs.app (0.47.3 first build) Fails
/Users/xxxx/Desktop/nwjs.app: rejected
source=no usable signature

Also found an anomaly with 0.48 which I thought was OK. The copy I tried had the libffmpeg.dylib replaced with the old one renamed as org-libffmpeg.dylib and it ran OK but a fresh build on first run would fail. If the dylib was swapped out the build would run OK.
$ spctl -a -t exec -vv /Users/xxxx/Desktop/nwjs.app (0.48.0b1 latest build) Fails
/Users/xxxx/Desktop/nwjs.app: rejected
source=no usable signature

Just seems something has changed since 0.47.3

If it doesn't happen for you on 10.13 then I may have a polluted gatekeeper filelist maybe.

**Comment by Blatman** [comment]
OK - I'll close this as it is a bit of a rabbit hole. 
I cleaned out the gatekeeper list which had a lot of nwjs renamed entries - the 0.47 builds appear to work OK after first run with manual open via Sys Prefs Security panel, I think an overly cluttered spctl file was not helping.

FWIW - clean out was 

sudo spctl --reset-default then machine reset

Typical file entry is 
2713[UNLABELED] P0 allow execute [/Users/xxxx/Desktop/nwjs/nwjs.app]
2712[UNLABELED] P0 allow execute [/Users/xxxx/Desktop/nwjs-sdk-v0.47.3-osx-x64/nwjs.app]

I have a tendency to rename folder prior to first run and this help clutter the GK file I think
