### ISSUE TITLE
Mac: package.nw not run when placed in Contents/Resouces

### ISSUE THREAD

**Issue by renowator** [nwjs/nw.js#7545]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : Latest stable mac
Operating System : Mac OS 10.14

### Expected behavior

<!- What do you think should happen? ->
I place my app in nwjs.app/Contents/Resources/package.nw
The contents of package.nw should be run upon executing nwjs.app

### Actual behavior

<!- What actually happens? ->
The nwjs.app runs default mode with no application being run

### How to reproduce

<!- 
Download package codes from https://github.com/renowator/CryptosFaucets_Bot
Package the codes inside into package.nw
Move the package.nw zip into nwjs.app/Contents/Resources
Run nwjs.app

->

**Comment by theDevelopper** [comment]
it needs to be called `app.nw` in macOS

**Comment by renowator** [comment]
Do I need to do anything other than place it in Resources folder? Still does not work with ` app.nw `

**Comment by theDevelopper** [comment]
you find all you need in the documentation:
https://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-your-app

Place your app in the app.nw folder and it will work if your app is not malformed / does not contain error.

**Comment by renowator** [comment]
Not sure if renaming everything stops it from working. On Windows everything goes smoothly.
