### ISSUE TITLE
SSL cert expired for v0.47.3

### ISSUE THREAD

**Issue by Goondaba** [nwjs/nw.js#7552]
NWJS Version : 0.47.3
Operating System : MacOS 10.15.5

### Issue

- When trying to download version 0.47.3 through Safari or nwjs-builder-phoenix I am getting an SSL cert expired issue. This does not happen if I select v0.47.2.

**Comment by allisont** [comment]
@rogerwang , I'm seeing this issue as well when building with nw-builder using version 0.47.0 for the last few days and today got a security warning when navigating to nwjs.io in Firefox on Mac.

**Comment by allisont** [comment]
Here's the error I'm getting: { Error: certificate has expired
09:28:39     at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
09:28:39     at TLSSocket.emit (events.js:189:13)
09:28:39     at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'CERT_HAS_EXPIRED' }

**Comment by Goondaba** [comment]
@rogerwang Thanks for checking! 

Clarification: It doesn't seem to have to have anything to do with the version, as I also sometimes get the error when building using v0.47.2.

Rather, it seems to happen sporadically; if I run `build` a few times I may get the error @allisont posted, only to have it succeed on the third attempt.

**Comment by jaredmcateer** [comment]
We're on an older version, 0.41.2-sdk, and are intermittently experiencing this problem during the `node scripts/install.js` process installing from npm.

**Comment by rogerwang** [comment]
I just restarted the web servers, please try again.

**Comment by Goondaba** [comment]
@rogerwang Haven't had the issue since you restarted.

**Comment by jaredmcateer** [comment]
So far so good here as well. Thanks
