### ISSUE TITLE
setTimeout callback not executing when new_instance: true in require('child_process')

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#7554]
NWJS Version : 0.47.3
Operating System : Ubuntu

### Expected behavior

Callback shoud be executed after the set time is done

### Actual behavior

Nothing seems to happen. Or it does execute in some other context I am not able to observe (i.e I have no idea).

### How to reproduce

Start a new window with `new_instance: true` and inside that have `require('child_process')` and as part of the callback of that have the `setTimeout` and have it console.log something to see if it's working. A sample code is attached below:

[new_instance_demo.zip](https://github.com/nwjs/nw.js/files/5113889/new_instance_demo.zip)

**Comment by anesuc** [comment]
Any estimates on this? Was pretty close from the last new_instance bug fix it gave me some hope this feature would work again haha

**Comment by anesuc** [comment]
Sorry to bump this, there is a project of mine that's kinda waiting for this bug fix haha. Is there any potential timeline/estimate for this?

**Comment by rogerwang** [comment]
Will see it soon. Thanks.

**Comment by anesuc** [comment]
Fantastic thanks!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
