### ISSUE TITLE
it's possible to embed all .dll and nw.pak files into a single exe, please add the way in wiki

### ISSUE THREAD

**Issue by fyears** [nwjs/nw.js#756]
I use node-webkit, and I want to distribute app.exe in a single file, without .dll files and nw.pak.

There's no good opensource solution, but there's a **free** solution (absolutely free for personal use, and it seems to be free for commercial use without warranty) . It's "Enigma Virtual Box", on http://enigmaprotector.com/en/aboutvb.html .

All programs in https://github.com/zcbenz/nw-sample-apps run correctly.

Maybe development guys should test it, and note it as an alternative way in https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps

**Comment by FlandersBurger** [comment]
+1
