### ISSUE TITLE
Using require('process') with 0.48.1 cause app to freeze - need to force quit.

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7560]
10.13.6 - High Sierra 

0.48.0 is OK (node 14.8.0)
0.48.1 fails  (node 14.9.0)
Inbuilt process works OK but if the npm downloadable process module is used and required then bug will occur
0.48.1 will work OK if the require line is commented out.

    var wildgooseman = nw.require('process');  // this will cause white screen for Sys info window from 0.48.1 onward (uses node 14.9.0)
    console.log("nwjsvdata " + process.versions['node-webkit']);  // OK
    console.log("njsvdata " + process.versions.node);  // OK
    console.log("cwvdata " + process.versions.chromium);  // OK
 
Not sure if the FrameBuffer logs are relevant.
   
[processbug.zip](https://github.com/nwjs/nw.js/files/5152122/processbug.zip)

<img width="1164" alt="processbug" src="https://user-images.githubusercontent.com/11089335/91756958-8626dd00-ebc5-11ea-940c-09f58822e8ac.png">

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
