### ISSUE TITLE
Different behavior of nw.Window.open new_instance comparing 0.39.3 and 0.48.1

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7561]
NWJS Version : 0.48.1
Operating System : macos 10.14.4

### Expected behavior

here is a demo
[new_instance.zip](https://github.com/nwjs/nw.js/files/5162486/new_instance.zip)

![image](https://user-images.githubusercontent.com/11750641/91987531-c53d6580-ed60-11ea-83e5-67c6730f48c3.png)

in 0.39.3

![image](https://user-images.githubusercontent.com/11750641/91987669-ef8f2300-ed60-11ea-86ad-86f897654f6d.png)

and if in 0.39.3 we open a window that is not new_instance like below

![image](https://user-images.githubusercontent.com/11750641/91987758-0afa2e00-ed61-11ea-91ad-ba60474fa70c.png)

**Comment by chatcan** [comment]
#7344 
if open a new_instance window that is seperated context ; how clould i inspect the  new created node context;
by inspect forground or inspect background(that is the node context before)

**Comment by gpetrov** [comment]
The window.open has a callback that returns the new Window handle. See https://nwjs.readthedocs.io/en/latest/References/Window/#windowopenurl-options-callback

**Comment by rogerwang** [comment]
merge with #7609
