### ISSUE TITLE
Clarify what "Complete support for Node.js APIs..." means 

### ISSUE THREAD

**Issue by ofirgeller** [nwjs/nw.js#7567]
The readme says: "Complete support for Node.js APIs and all its third party modules." 

### Expected behavior

I would be able to import the 'http' module and it would have the full API as if I was running inside node js.

### Actual behavior

When I import the  http module it is missing some parts of the API, for example 'createServer'.

Is this an expected gap or am I doing something wrong? are other modules also missing or partial?

### How to reproduce

Add :" import * as http from 'http'; console.log(http.createServer); " to JS file and run.

NWJS Version : 0.48.1
Operating System : Windows 10

* Please leave aside the question of why one would like to create a server inside a nwjs application

**Comment by bluthen** [comment]
Maybe?

```
http = require('http');
console.log(http.createServer);
```

**Comment by ofirgeller** [comment]
That logs 'undefined' since the property is missing.

**Comment by bluthen** [comment]
Not sure what to say, you doing something special? Maybe you have your own http module that takes over the node one or something?

I just ran it:
```
http = require('http');
http.createServer;
ƒ createServer(opts, requestListener) {
  return new Server(opts, requestListener);
}
```

**Comment by ofirgeller** [comment]
Thanks for checking and informing me.

I do not have my own module named 'http' , also I do see the property that holds the http response code enumeration,  which is what I would expect to find on the real model, but that is all I get.

**Comment by ofirgeller** [comment]
Found out that this import:

`import http from 'http';`

resolves to "stream-http" instead of the node http module (by running var pathToModule = require.resolve('http');)

which explains why it looks similar to the node http module but does not have the server parts like "createServer"
