### ISSUE TITLE
webkitSpeechRecognition exist but doesnt work?

### ISSUE THREAD

**Issue by peq42** [nwjs/nw.js#7570]
Trying to use webkitSpeechRecognition on NWJS v0.48.1 on Windows doesnt seem to work. Running "webkitSpeechRecognition" on the SDK console returns "native function" but then  trying to run the following code(that works on latest chrome) afterwards doesnt do anything

```
SpeechRecognition = webkitSpeechRecognition
let finalTranscript = '';
let recognition = new SpeechRecognition();

recognition.interimResults = true;
recognition.maxAlternatives = 10;
recognition.continuous = true;

recognition.onresult = (event) => {
  let interimTranscript = '';
  for (let i = event.resultIndex, len = event.results.length; i < len; i++) {
    let transcript = event.results[i][0].transcript;
    if (event.results[i].isFinal) {
      finalTranscript += transcript;
    } else {
      interimTranscript += transcript;
    }
  }
    console.log(finalTranscript)
    console.log(interimTranscript)
}
recognition.start();
```

**Comment by elpeleq42** [comment]
same happens in v0.48.2 sdk, Windows 10 @rogerwang

**Comment by rogerwang** [comment]
Does it work for you with the Chromium browser (not Chrome) ?

**Comment by elpeleq42** [comment]
> Does it work for you with the Chromium browser (not Chrome) ?

actually no, although it also shows the "native code" message and asks for permission to use the microphone.

Well apparently its not a NWJS problem then. Any idea ?
