### ISSUE TITLE
Window opened with new_instance node missing shared objects

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw.js#7574]
NWJS Version : 0.48.1
Operating System : Windows 10 and MacOS

### Expected behavior

When opening new window with the new_instance flag and when no mixed mode is used, a new Window with its own browser context and a separate node content should be created.

However the node context doesn't have a separate background page and also does not have the shared globas with its window like the window, localStorage and global objects.

### Actual behavior

A completely sandboxed node environment is created that doesn't have access to anything from the corresponding window.
Also when right clicking for the context menu on the new window pop and then show background page - it shows the main background page and not its own.

### How to reproduce

Use the this test case:
[test_popup_window.zip](https://github.com/nwjs/nw.js/files/5231475/test_popup_window.zip)

You will see that when the same popup is open regularly - the require inside of the module.js produces no errors results and the logs are nicely done in the ackground page.

However if you run the popup with the new_instance - the require of module.js produces errors because those global objects are undefined and those errors are logged in the same console as the window and not on a new separate background page as it should because we don't have mixed mode.

![module_globals_error](https://user-images.githubusercontent.com/504730/93325272-590a3980-f817-11ea-8985-7acc63c5d831.png)

See also initial issue https://github.com/nwjs/nw.js/issues/7344 that was partly solved but caused this one.

@rogerwang could you check this please - it seems that it was half solved previously and the node contexts in the new_instance are very limited and sandboxed. They really should run in their own background page and have access to the window, localStorage and global objects just like

**Comment by rogerwang** [comment]
There is no background page in the new process -- every extension should have only one background page. It's a limitation from Chromium.

**Comment by gpetrov** [comment]
What about the globals then in the node context of the new_instance? Why are the "window", "localStorage" and the "global" objects not available? As in any other node context in NWJS?

**Comment by gpetrov** [comment]
@rogerwang I understand about the background page - but the shared objects should be present right?

**Comment by gpetrov** [comment]
@rogerwang do you need a new bug report about the missing global objects when new_instance is used? It is the only road block that stops us using the new_instance.

**Comment by gpetrov** [comment]
Any chance to address this issue @rogerwang ? It is really a deal breaker for us.

**Comment by rogerwang** [comment]
The DOM objects you need can be passed to the Node context.

**Comment by gpetrov** [comment]
Do you mean I have to manually pass  "window", "localStorage" and the "global" to the node context? But those should be just available as they are normally available in the separate context modes....

**Comment by rogerwang** [comment]
The availability of DOM objects in the Node context is never a part of the API. They are not supposed to be there in the separate context mode and will be removed in future versions.
