### ISSUE TITLE
Error when launching nw.Shell.openItem

### ISSUE THREAD

**Issue by userlerueda** [nwjs/nw.js#7576]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : v0.48.2
Operating System : macOS 10.15.6

### Expected behavior

When invoking `nw.Shell.openItem('/Applications/iTerm.app/Contents/MacOS/iTerm2')` I should be able to launch the application from my nwjs App.

### Actual behavior

I get an error stating `“Terminal” can’t be opened because nwjs is not allowed to open documents in Terminal.`

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->
```
import {} from "nw.js";
nw.Shell.openItem('/Applications/iTerm.app/Contents/MacOS/iTerm2')
```

**Comment by sysrage** [comment]
Haven't used macOS for awhile, but it looks like your app just doesn't have the correct permissions. This seems to indicate the same thing:

[https://forum.polymake.org/viewtopic.php?t=513](https://forum.polymake.org/viewtopic.php?t=513)

**Comment by userlerueda** [comment]
Worked out the permission problem by deleting the **File quarantine enabled** from Info.plist.
