### ISSUE TITLE
<webview> NewWindow.attach is broken on 0.48.0+

### ISSUE THREAD

**Issue by mkazlauskas** [nwjs/nw.js#7578]
NWJS Version : 0.48.0+ (tested with 0.48.0, 0.48.3, 0.49.0-beta1, all dev)
Operating System : Linux x64

### Expected behavior

After attaching new window to a webview as documented [here](https://developer.chrome.com/apps/tags/webview#type-NewWindow) you should be able to interact with the page with keyboard and mouse.

### Actual behavior

Window is attached to the webview and appears to be responsive. Can interact with the page via DevTools (e.g. set input value). However, clicking on anything within the page has no effect.

It does work correctly using 0.47.3 so I'm hoping it'll be possible to isolate what broke it.

### How to reproduce
*package.json*
```json
{
  "name": "newwindow",
  "main": "index.html"
}
```
*index.html*
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>newwindow</title>
  <style>
    html,
    body {
      width: 100%;
      height: 100%;
    }
  </style>
</head>

<body>
  <webview src="https://www.encodedna.com/javascript/demo/open-new-window-using-javascript-method.htm"></webview>
  <script>
    document.querySelector('webview').addEventListener('newwindow', e => {
      const webview = document.createElement('webview');
      webview.style.width = '50vw';
      webview.style.height = '50vh';
      webview.style.position = 'absolute';
      webview.style.border = 'solid 2px red';
      webview.style.left = '0';
      webview.style.top = '0';
      document.body.appendChild(webview);
      e.window.attach(webview);
    });
    setTimeout(() => {
      nw.Window.get(window).showDevTools();
    }, 100);
  </script>
</body>

</html>
```

Run it and click on 'Open new window' withing the demo page. Try to interact with the popup.

**Comment by rogerwang** [comment]
I can reproduce this in upstream Chrome browser with a Chrome app. So this is an upstream issue. Please report it to the Chromium project.

btw, it works well if the webview is opened in a new window.

**Comment by panther7** [comment]
@mkazlauskas 
Hi, will you create an issue on upstream?

**Comment by mkazlauskas** [comment]
> @mkazlauskas
> Hi, will you create an issue on upstream?

Hi, I tried, but couldn't. Opened another ticket on opening tickets first.

**Comment by panther7** [comment]
> > @mkazlauskas
> > Hi, will you create an issue on upstream?
> 
> Hi, I tried, but couldn't. Opened another ticket on opening tickets first.

Sorry, but i don't understand.

**Comment by mkazlauskas** [comment]
> > Hi, I tried, but couldn't. Opened another ticket on opening tickets first.
> 
> Sorry, but i don't understand.

I literally can't create a Chromium issue on `bugs.chromium.org`: opened [this](https://bugs.chromium.org/p/monorail/issues/detail?id=8467)

Maybe  you could try? I created a [minimal test case Chrome app](https://github.com/mkazlauskas/webview-bug) that reproduce the issue.

It broke on Chromium 85 (tested with 85.0.4183.83) and last good version I tested was 84.0.4147.125

**Comment by panther7** [comment]
Meybe, bacause isn't chromium issues list, try here: https://bugs.chromium.org/p/chromium/issues/list

@mkazlauskas

**Comment by mkazlauskas** [comment]
> Maybe, because isn't chromium issues list, try it here: https://bugs.chromium.org/p/chromium/issues
> 
> @mkazlauskas

Nope, that's where I tried to open it.

**Comment by panther7** [comment]
Simply created: https://bugs.chromium.org/p/chromium/issues/detail?id=1136645

@mkazlauskas

**Comment by panther7** [comment]
Thanks
