### ISSUE TITLE
Is there a problem in "window" in package.json 

### ISSUE THREAD

**Issue by sysdl132** [nwjs/nw.js#7584]
======== FORM ========

NWJS Version: 0.48.4
Operating System: windows 10 build 18362

### Expected behavior

The window opened normally

### Actual behavior

After a few minutes, the window didn't appear

### How to reproduce

- 1. create an index.html and icon.svg
- 2. create 'package.json' like this:
```
{
  "name": "forum-desktop",
  "title": "forum",
  "main": "index.html",
  "window":[
    {
      "width": 1024,
      "height": 768,
      "icon": "./icon.svg"
    }
  ],
  "maintainers":[{
   "name": "System32",
   "email": "3412913920@qq.com",
   "web": "https://sysdl132.github.io"
  }],
  "licenses": [
   {
       "type": "GPLv2",
       "url": "http://www.example.com/licenses/gpl.html"
   }
  ]
}
```
- 3. start the application
- 4. Then I can't start it

**Comment by sysdl132** [comment]
After I erase all things in "window", the app can launch normally.

**Comment by Blatman** [comment]
Does it work if you remove the square brackets? I tried this code and it failed on MacOS but ok without square brackets.

**Comment by sysdl132** [comment]
@Blatman Did you mean this?
```
<part of package.json>
  "window":
    {
      "width": 1024,
      "height": 768,
      "icon": "./icon.svg"
    },
 ```

**Comment by sysdl132** [comment]
Thanks. This solved my question.

Now I have another question. What icon format does NW.js support?

**Comment by sysdl132** [comment]
Knew it. I can use the PNG format.
