### ISSUE TITLE
Transparency not working in Windows 10 with window frames enabled

### ISSUE THREAD

**Issue by sysrage** [nwjs/nw.js#7587]
NWJS Version : 0.49
Operating System : Windows 10 2004

### Expected behavior

When a transparent window is created with frames enabled, the "normal" Windows frame (typical titlebar with thin lines on the sides and bottom of window) should be shown with a transparent background.

### Actual behavior

The window is drawn with "old style" Windows frames and transparency doesn't work.

### How to reproduce

The following code can be used to reproduce this issue.

### package.json
```json
{
  "name": "bug",
  "version": "0.1",
  "main": "./bug.html",
  "window": {
    "transparent": true
  }
}
```

### bug.html
```html
<html>
  <head>
    <title>bug</title>
    <style>body { color: #fff }</style>
  </head>
  <body>
    This is a bug.
  </body>
</html>
```

With the above code, the following is seen. Note the "bug" window is the above application while the other window is NW.js being run without any scripts (showing a "normal" frame).

![image](https://user-images.githubusercontent.com/166781/95480582-0b867580-095a-11eb-936b-b43bda5225aa.png)

If `resizable: false` is added to package.json, there is no change in behavior.

If `frame: false` is added to package.json, the frame is correctly removed and transparency works properly.

**Comment by sysrage** [comment]
This is still not working as expected with 0.51.0. Any available workaround would be appreciated. Would love to have the frame around a transparent window!

**Comment by rogerwang** [comment]
The `transparent` flag in the manifest is supposed to be used with frameless window.

**Comment by sysrage** [comment]
> The `transparent` flag in the manifest is supposed to be used with frameless window.

Okay. It would be awesome to support frames and transparency, but if that's not possible I recommend updating the documentation to point out this limitation. Thanks!

**Comment by tharatau** [comment]
Mentioned here https://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Transparent%20Window/
