### ISSUE TITLE
nw.js seems not to be able to handle pixi.js on linux

### ISSUE THREAD

**Issue by ferama** [nwjs/nw.js#7590]
NWJS Version : nwjs-sdk-v0.49.0-linux-x64
Operating System : Ubuntu 20.04

### Expected behavior

The animations on the pixi demo page should be fluid. On the same machine they run perfectly fine using Chromium 85.0.4183.121

### Actual behavior

The pixi.js demo page is choppy and laggy. 

### How to reproduce

try to run:
```
$ nw --url=https://pixijs.io/pixi-filters/tools/demo/
```

**Comment by DimPaDev** [comment]
I can reproduce this bug too. It's a blocking issue for many applications. If you run the same app with chrome/chromium or electron everything runs fine 

#7497

**Comment by rogerwang** [comment]
This seems a duplicate with #7497 . Is the workaround there work for you?

**Comment by ferama** [comment]
No improvements with the workaround
Just tested with
```
$ ./nw --url=https://pixijs.io/pixi-filters/tools/demo/ --use-cmd-decoder=passthrough
```

**Comment by rogerwang** [comment]
Fixed in this build: https://dl.nwjs.io/live-build/nw49/20201022-140828/1e6f61f30/v0.49.1/nwjs-sdk-v0.49.1-linux-x64.tar.gz
