### ISSUE TITLE
capturePage captures wrong window (NW2)

### ISSUE THREAD

**Issue by DjulLau** [nwjs/nw.js#7592]
NWJS Version : 0.49.0
Operating System : Windows 10

I recently tried upgrading my app from v0.28 to v0.49.
In this app I open a second window behind the main window to do some capture.

### Expected behavior

capturePage should capture content of the window it's called from.

### Actual behavior

capturePage captures content from the main window even it's called from the new one.
It works as before if NW2 is disabled with --disable-features=nw2

### How to reproduce

Have two html files:
- index.html with **color1** bg
- new.html with **color2** bg
- index.html script
``` javascript
    require("nw.gui").Window.open("new.html", {}, (wnd) => {
        wnd.on("loaded", (e) => {
            wnd.capturePage(buffer => {
                require('fs').writeFile('screenshot.png', buffer, (err) => {
                    if (err) throw err;
                });
            }, { format: 'png', datatype: 'buffer' });
        });
    });
```
- Open **screenshot.png** and see it's **color1**
- Add "chromium-args": "--disable-features=nw2"
- Run again
- Open **sceenshot.png** and see it's **color2**

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
CC #7230
