### ISSUE TITLE
removeAllListeners doesn't seem to remove listeners (NW2)

### ISSUE THREAD

**Issue by DjulLau** [nwjs/nw.js#7593]
NWJS Version : 0.49.0
Operating System : Windows 10

I recently tried upgrading my app from v0.28 to v0.49.
In this app I open a second window behind the main window to do some capture.
I listen to the 'loaded' event on the window to wait before doing the capture.
Then I call removeAllListeners('loaded') to stop listening to this event but I still receive the event with new version after that.

### Expected behavior

Should not receive 'loaded' event after calling removeAllListeners('loaded')

### Actual behavior

'loaded' event still received after calling removeAllListeners('loaded')

### How to reproduce

``` javascript
    require("nw.gui").Window.open("new.html", {}, (wnd) => {
        wnd.on("loaded", (e) => {
            console.debug("loaded");
            
            wnd.removeAllListeners("loaded");
            console.debug("new load");
            wnd.window.location.href = "new.html";
        });
    });
```

Output
``` console
loaded
new load
loaded
new load
loaded
new load
loaded
new load
...
```
- Add "chromium-args": "--disable-features=nw2"
- Run again
Output
``` console
loaded
new load
```

### Workaround
Use window.once('loaded') instead of window.on('loaded').

**Comment by DjulLau** [comment]
CC https://github.com/nwjs/nw.js/issues/7230

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
