### ISSUE TITLE
localStorage not working

### ISSUE THREAD

**Issue by danielklug** [nwjs/nw.js#7600]
NWJS Version : 0.49.0
Operating System : Windows 10

### Expected behavior

localStorage.setItem(key,value);
localStorage.commit();
restart nwjs
localStorage.getItem(key);
should provide the value set before

### Actual behavior

localStorage is empty when starting again

**Comment by rogerwang** [comment]
Could you provide a sample? It works for me.

**Comment by danielklug** [comment]
Will investigate further maybe I am doing something wrong. Could you tell me where the localstorage is stored on windows? in node-webkit it was in the file file__0.localstorage in "%Appdata%\local\projectName\Local Storage". Am I able to tell nwjs to read and write it from that?

**Comment by danielklug** [comment]
Ok it seems that the values are there after starting a second time. (But I don't know why I am not reading the correct values on startup/initializing) When everything is up and running the values are correct. (still investigating)

I've seen there was a data migration code in nw_chrome_browser_hooks.cc on lines 266-354. Why is that not in anymore? (Would be great to have the "old" localstorage data from node-webkit automatically migrated to the new storage)

**Comment by patrickklug** [comment]
Is there any info at all on migration of local storage from old versions of node-webkit to nw.js - this is a HUGE issue for us.

**Comment by patrickklug** [comment]
I've added a new issue for the migration question: https://github.com/nwjs/nw.js/issues/7601

**Comment by rogerwang** [comment]
> I've seen there was a data migration code in nw_chrome_browser_hooks.cc on lines 266-354. Why is that not in anymore? (Would be great to have the "old" localstorage data from node-webkit automatically migrated to the new storage)

I just commented on this in #7601 . The discussion on this can continue there.

**Comment by danielklug** [comment]
The issue isn't that the values are not persisted and read again after a restart. So this issue can be closed.

My issue is that I am reading the values too early. Is there somewhere a documentation when I am allowed to read the values from localStorage? When is it guaranteed that the localStorage is read and available?

**Comment by rogerwang** [comment]
It should be the same as in browser. If you find a difference, please provide a sample here.

**Comment by patrickklug** [comment]
We are still stuck on this bug. When we try to read from local storage in nw.js while we start our game the data is wrong.

This is a big problem because we store player-settings like music on/off or fullscreen on/off in localstorage but when we start our game, we don't get the correct values and thus start the music when we should not.

AFAIK, there is no such issue in the browser as the localstorage data always seems correct.
We need some guidance on when we can safely read from local storage in nw.js without resorting to some superstitious setTimeOut's that slows the entire startup experience down.
