### ISSUE TITLE
Migrating localstorage from node-webkit era installations to nw.js

### ISSUE THREAD

**Issue by patrickklug** [nwjs/nw.js#7601]
We are trying to update our old node-webkit user base to a nw.js version but it seems that all data in localstorage is lost upon upgrade. Is there no migration for this available?

In node-webkit local storage was stored in a file called "file__0.localstorage" inside the localappdata folder but nw.js seems to store it elsewhere.

**Comment by rogerwang** [comment]
The local storage data in 0.12 or earilier versions had been migrated to new NW versions on start. In recent versions starting from 0.41 the migrated code was removed due to conflicts with upstream handling of the storage files on disk. 

If you are upgrading from 0.12, please try to upgrade to a version before 0.41.0 first and then upgrade to the latest version. The data will be migrated in this way. Thanks.

**Comment by patrickklug** [comment]
This is not feasible, sure we could get some players to transition that way to a new version of nw.js using this approach now but what if someone else updates a few years down the track from a <0.12 version. it will just be broken again for them.

**Comment by patrickklug** [comment]
Can you tell us how localstorage is now stored? Maybe we could write some JS code to transition this ourselves?

**Comment by rogerwang** [comment]
The localstorage file should be in sqlite format.

**Comment by patrickklug** [comment]
Apologies, but I can't see where the file is in nw.js?

**Comment by rogerwang** [comment]
It's in [user data dir](https://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir)/Local Storage

**Comment by patrickklug** [comment]
Has the format of the local storage file remained the same?
May I ask what you mean with "conflicts with upstream handling of the storage files on disk", what conflicts where there?

**Comment by rogerwang** [comment]
The path posted above is where it was stored in 0.12 and earlier.

Regarding where is it stored now, I don't suggest writing directly to the Chromium storage, as it's locked when running -- writing to it conflicts with the Chromium engine. And the internal format of it is subject to change from version to version. A better approach would be writing to it through the Chromium engine with DOM APIs.

**Comment by patrickklug** [comment]
I still don't feel confident to write a migration. Can you elaborate what you meant with 

> In recent versions starting from 0.41 the migration code was removed due to conflicts with upstream handling of the storage files on disk.

Will the node-webkit localstorage files be safe to read from in the current (and future) versions of nw.js

Is there any built-in support to read the old format or will I have to include my own sql-lite database framework in every release?

**Comment by rogerwang** [comment]
> What were these upstream conflicts?
Chromium project changes the internal format of the stoarge and it stopped support the old format data.
> Will the old node-webkit localstorage files be safe to read from in the current (and future) versions of nw.js?
0.40 or earlier version of NW.js has the built-in support to read those data. The later version has not since it is not supported in Chromium.
 
> 
> Is there any built-in support to read the old format or will I have to include my own sql-lite database framework in every release from now on if I want to allow users to upgrade from any old version they might have installed?

My suggestion is to prompt the end-users to migrate to a version based on 0.40.0 or earlier version first.

**Comment by patrickklug** [comment]
> My suggestion is to prompt the end-users to migrate to a version based on 0.40.0 or earlier version first.

Respectfully, this isn't feasible and doesn't solve the problem. Not only would it be a terrible end-user experience but more to the point, several game distribution platforms only support a single 'version' to be distributed to players - We couldn't distribute multiple different versions and instruct end-users to pick from them. What's more is that old versions of nw.js are incompatible with Mac OS Catalina and long-term compatibility will just get worse, so we can't use older versions as a intermediary step. This simply is not a solution.

**Comment by rogerwang** [comment]
> Respectfully, this isn't feasible and doesn't solve the problem. Not only would it be a terrible end-user experience but more to the point, several game distribution platforms only support a single 'version' to be distributed to players - We couldn't distribute multiple different versions and instruct end-users to pick from them. What's more is that old versions of nw.js are incompatible with Mac OS Catalina and long-term compatibility will just get worse, so we can't use older versions as a intermediary step. This simply is not a solution.

In this situation you could read the sqlite db from the old version from your app and store it in the new localstorage.

**Comment by patrickklug** [comment]
Seems so, yes.
