### ISSUE TITLE
Hope that there is a parameter to control the context type of the opened  new_instance window 

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#7609]
#7344 
#7561 

before nwjs 0.47.1 , always mixed context
after always seperated context 
it's huge change for us because our app is base on that the new_insatance window is a mixed context

could you provide a parameter to control  the context type of the opened  new_instance window?

**Comment by rogerwang** [comment]
Will add this soon. Thanks.

**Comment by rogerwang** [comment]
Fixed in https://dl.nwjs.io/live-build/nw49/20201030-112130/a889442d0/v0.49.2/
