### ISSUE TITLE
::-webkit-scrollbar-track always visible, even with "background-color: transparent"

### ISSUE THREAD

**Issue by vankasteelj** [nwjs/nw.js#7611]
NWJS Version : 0.49.2 sdk
Operating System : Windows 10

### Expected behavior
The scrollbar css is as follow: 
```
::-webkit-scrollbar-track {
  background-color: transparent;
} 
```

On nwjs 0.36.x, it was displaying only the "thumb" for scrolling, not the scrollbar track, which was set to 'transparent'.

### Actual behavior

It displays a scrollbar track no matter what. 

A picture is worth a thousand words:
Before (no scrollbar) and after (scrollbar)
![Frak_PDp3RqL9m8](https://user-images.githubusercontent.com/12599850/97802791-35277980-1c46-11eb-8592-a72d51de52ea.png)
![nw_A6BfebLxQG](https://user-images.githubusercontent.com/12599850/97802793-3658a680-1c46-11eb-880b-28a4e649128f.png)

**Comment by rogerwang** [comment]
does it work with the latest Chrome?

**Comment by vankasteelj** [comment]
It seems to, using https://jsfiddle.net/3awLgj5v/ on google chrome 86.0.4240.183 for example (transparency there is set to 0.2, but it's transparent anyway, and changing it to 0 also works)

**Comment by vankasteelj** [comment]
Ah sorry, apparently Chrome now needs `overflow: overlay;` set on the parent div. My bad, thank you for the support
`
