### ISSUE TITLE
Bizarre setTimeout behaviour (duration is much, much longer than requested times)

### ISSUE THREAD

**Issue by NbrTDB** [nwjs/nw.js#7616]
This is a bit of a strange one!

NWJS Version : 0.49.2 SDK Win x64
Operating System : Windows 10 v2004 (19041.508)

### Expected behavior

When using `setTimeout()`, my expectation is that the callback executes shortly after the requested time (i.e. perhaps up to several ms later than requested, on an otherwise idle NW.js instance, but in essence, very close to the requested time interval).

### Actual behavior

When using `setTimeout()`, the callback executes _far_ later than requested. Typically a few hundred to a thousand milliseconds later. In fact, regularly spamming setTimeout, it looks like the callbacks fire all in one lump approximately every 1000ms.

### How to reproduce

At the bare minimum, just run nw.exe, open devtools, and type:

`setTimeout(()=>{console.log("DONE!")}, 5)`

Keep tapping Up and then Enter to re-run this small "benchmark"... "DONE" should appear in the console practically instantly, but frequently seems to lag. Sometimes the initial runs seem to go well, but then performance quickly drops.

Meanwhile, mashing F12 in the Chrome browser and running the same experiment, the setTimeout callback executes reliably every time, at almost exactly the time interval requested.

I'm wondering if this can be something related specifically to my system or the application I'm trying to develop with NW.js? I've even gone back to try older versions of NW.js (as far back as 0.45.4) and the behaviour is the same, yet I don't recall any issues with using that version at the time.

**Comment by rogerwang** [comment]
Is the window being covered when this happens?

**Comment by NbrTDB** [comment]
Hahahaha! Ahh, thanks... you might be on to something... it seems that having NW.js hidden behind another window is a very reliable way to reproduce the behaviour! If I plonk something like the below in, the performance of setTimeout drops in tandem with the window deciding it's hidden:

```javascript
document.addEventListener(`visibilitychange`, function () {
    console.log(`Window visible: ${!document.hidden}`); // if Window visible === false, setTimeout is slow!
  });
```

I had a feeling the 1-secondish interval was a clue... this is that change made in Chromium years ago to reduce CPU usage on background tabs, isn't it?

Alas I must now rely on my memory from yesterday, and as such I could _swear_ there were circumstances where the app window was in foreground, albeit behind devtools, or even next to it, and the same issue could occur. Having said that... I can't reproduce it this morning... so I'm inclined to think it must just be this.

I guess my next question then would be if there's a "best" way to change or override that behaviour in a vanilla build of NW.js? I could really do with reliable timing for this application when it's not in focus as it may need to run in the background often. If I'm not mistaken, offloading things into a Web Worker would bypass the performance limitation, but this isn't an ideal solution for me.

I am aware of `chrome://flags/#expensive-background-timer-throttling` and `--disable-background-timer-throttling`. I don't know how to get at the functionality of chrome://flags in NW.js, but adding `--disable-background-timer-throttling` to `chromium-args` in package.json does seem to work. Is this the best method to opt out of performance throttling in the background?

**Comment by NbrTDB** [comment]
Actually, this might still be an issue... in a vacuum with the chromium arg `--disable-background-timer-throttling` (just running `setTimeout` in the console) it does appear to work reliably. This is repeatable (if I take the flag away, the problem comes back, etc).

However, it _doesn't_ appear to work in the case of my actual application, which is strange. 

The case in question is just a function which delays resolution of a Promise by the requested interval. In essence, there is a chain of Promises involved in communicating with an external device (by way of a spawned `child_process`), and at certain points we need to wait a few milliseconds before continuing the chain. 

Tried in the console with the flag set, this Promise *does* now function as expected, even when the window is hidden, and this is again repeatable (take the flag away, and it goes back to misbehaving) but in practical use during normal program execution, its behaviour hasn't changed at all; with or without the flag, there are large, arbitrary delays of up to some ~1500ms beyond requested:

```javascript
  _pDelay (delay = 5) {
    return new Promise((resolve, reject) => {
      var ts = Date.now();
      console.log(`Waiting ${delay}ms`); // typical output: "Waiting 5ms"
      setTimeout(() => {
        console.log(`Waited ${Date.now() - ts}ms`); // typical output even with window focus: "Waited 1553ms", "Waited 915ms"
        resolve();
      }, delay);
    });
  }
```

However in the same scenario if I replace it with something more horrible like a for-loop, it works reliably every time, albeit with wonky timing:

```javascript
  _pDelay (delay = 5) {
    return new Promise((resolve, reject) => {
      var ts = Date.now();
      console.log(`Waiting ${delay}ms`); // typical output: "Waiting 5ms"
      for (var x = 0; x < 40000000; x++) {
        var y = x + 1; // do stuff
        y = y - 1; // blah
      }
      console.log(`Waited ${Date.now() - ts}ms`); // typical output: "Waited 20ms", regardless of window hidden or not, or flags
      resolve();
    });
  }
```

**Comment by rogerwang** [comment]
Does this argument make any difference for setTimeout? https://nwjs.readthedocs.io/en/latest/References/Command%20Line%20Options/#-disable-raf-throttling

**Comment by NbrTDB** [comment]
Thanks for the suggestion, but alas it seems not. I've tried a variety of window focused/not focused/devtools focused/devtools closed, with and without `--disable-raf-throttling` and `--disable-background-timer-throttling` but there is no effect once `setTimeout` is employed within the Promise chain.

I should note this application hardly does anything at this point; it's very early in development and the UI is comprises non-functional placeholders. The performance monitor during the Promise chain shows out of 76303ms total time, 76259ms was spent doing nothing at all!

![image](https://user-images.githubusercontent.com/21238754/98362621-7abcbb80-2025-11eb-81e4-d2fb577e6f02.png)

In fact it even shows the calls to `_pDelay` execute extremely quickly: 

![image](https://user-images.githubusercontent.com/21238754/98362852-dab36200-2025-11eb-86f5-f25e551386e0.png)

But in between, just a large gap of nothing for hundreds of ms or more, instead of the anticipated 5ms wait (sorry, I don't suppose any of this is really useful info):

![image](https://user-images.githubusercontent.com/21238754/98362913-f880c700-2025-11eb-9162-ed9d7cfef51a.png)

I haven't tried more esoteric things like making a more concise Promise (something like `return new Promise(resolve => setTimeout(resolve, ms));`) but also have no reason to believe that would really change anything either.

**Comment by NbrTDB** [comment]
Just had a thought, there is one other thing that might be relevant maybe, since we're talking about window focus; this application does start up an initial, tiny window as a splash screen, then loads the main window in after to avoid seeing any flashes of un-styled UI. Is there any way this could have an effect, since the application proper is essentially running in a "secondary" window?

```javascript
var splashScreen = nw.Window.get();
var mainScreen;
console.log(`Loading`);
nw.Window.open(`html/ui.html`, {
  new_instance: true,
  transparent: true,
  frame: false,
  icon: `../images/graphics/ui_logo.png`,
  position: `center`,
  width: 1024,
  height: 768,
  resizable: true,
  fullscreen: false,
  show: false
}, function (ui) {
  mainScreen = ui;
  mainScreen.on(`loaded`, function () {
    console.log(`Loaded main window`);
    mainScreen.show();
    splashScreen.close();
  });
});
```

**Comment by NbrTDB** [comment]
I've narrowed it down to _something_ to do with using setTimeout after communicating with the spawned external process, or at least, once data is received back through the pipe.

Everything behaves fine until a response is received from this child process; once that happens, it's like NW.js locks up for a bit during setTimeout (but _not_ if no timeout is used, e.g. when using a for loop to delay the Promise chain, or just chaining any other Promises that don't involve use of setTimeout, the problem doesn't occur)

For this test I had the child process (a Python script) listening to stdin to respond to a test message. So the data going back and forth is essentially the below JSON strings:

To the python process:
`{"cmd":"test"}`

And in reply:
`{"resp":"response"}`

The console indicates that the process of queuing the command, transmitting it, and receiving the response is reliably fast (never see any hang-ups here). It's always _after_ the response is received, during the subsequent setTimeout of the subsequent Promise. The delay is not guaranteed to happen; more often it will than it won't, but sometimes the Promise chain executes a delay smoothly:

![image](https://user-images.githubusercontent.com/21238754/98540062-3af40f00-2285-11eb-9f47-02b04820bf5c.png)

If I chain successive test commands instead, then there is no delay, but the moment setTimeout is used, there it is again:

![image](https://user-images.githubusercontent.com/21238754/98540493-ef8e3080-2285-11eb-8f9d-bc0dd4c189cd.png)

If anyone has any ideas about why an event triggering `childProcess.stdout.on('data')` with a tiny string of JSON would result in subsequently hanging setTimeout for hundreds of milliseconds, please let me know! 

In the meantime, in case this is not just some horrendous mistake of my own doing, I suppose I will try to create a minimum viable reproduction of the issue for others to test. At this point I'm not even sure if this appropriate as an NW.js issue.

**Comment by NbrTDB** [comment]
Closing; a more specific description of the problem and a testable example that reproduces the issue is provided in #7619 

Thanks for your time so far, I appreciate it!
