### ISSUE TITLE
nw.exe's memory dump captured password

### ISSUE THREAD

**Issue by meraj321** [nwjs/nw.js#7621]
NWJS Version : 49.1
Operating System : windows 10

### Expected behavior

ne.exe's memory dump file should not contain password entered by user.

### Actual behavior

ne.exe's memory dump file contains password entered by user.

### How to reproduce
1: Create a HTML login page asking for user name and password.
2: Enter user name and password in the login page.
3: Go to task manager ->Details, right click on nw.exe and click "Create dump file".
4: memory dump file will be created in %temp% folder.
5: Open memory dump file in notepad and search for the password, it will find the password.

Thanks,
Meraj

**Comment by rogerwang** [comment]
This is a Chromium issue. Please follow in upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1013091
