### ISSUE TITLE
App crashes and prints debug.log in binary folder

### ISSUE THREAD

**Issue by t-mish** [nwjs/nw.js#7622]
NWJS Version : 0.49.1 SDK
Operating System : Windows 7 x64, MacOS x64, Linux Ubuntu x64

### Expected behavior

Normal working flow

### Actual behavior

App crashes and print debug.log file with following content

> [1118/122804.925:ERROR:filesystem_win.cc(129)] GetFileAttributes [PATH TO APPDATA]/User Data\Crashpad\attachments\9d59750d-2a9e-4ee5-a520-1d82521a886f>: The system cannot find the path specified. (0x3)

> [1118/122804.945:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: The operation completed successfully. (0x0)

> [1118/123754.986:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)

### How to reproduce

nw.exe --url=https://web.telegram.org/#/im

### Possible solution

**Devs says that it will be fixed in chromium 88.0.4302.0**
https://support.google.com/chrome/thread/76470778?hl=en

**Comment by rogerwang** [comment]
Hello, the information you provided looks irrelavant to the crash as they are the error messages from the crash reporter.

Could you please provide a sample so I can reproduce your issue?

**Comment by mishagin-tim** [comment]
Ok, my sample is based on nw-samples-apps/frameless-window.. I simply add webview tag with https://web.telegram.org/#/im URL. Wait until site is already loaded. Then see how it crashes.

Note, that nw.exe process is still working in process explorer and consumes a huge amount of RAM.

[frameless-window.zip](https://github.com/nwjs/nw.js/files/5560490/frameless-window.zip)

**Comment by mishagin-tim** [comment]
Super easy sample
nw.exe --url=https://web.telegram.org/#/im

**Comment by mishagin-tim** [comment]
Still crashes on nw51 with Chromium 88.0.4324.0

**Comment by alexeychikk** [comment]
I had a similar error when I forgot to add `"main": "index.html"` in my `package.json`.
