### ISSUE TITLE
Ubuntu 18.04 without sudo

### ISSUE THREAD

**Issue by zertex** [nwjs/nw.js#7626]
Ubuntu 18.04
NW.JS 0.50.0

Why I can't execute NW without sudo?

**Comment by mishagin-tim** [comment]
Maybe because you don't have a permission to execute files in that folder?
See command **chmod**

**Comment by zertex** [comment]
![log](https://user-images.githubusercontent.com/6353201/99909547-54bc3a00-2cfa-11eb-89aa-5cccf65579f7.png)

Access Denied
Ubuntu 18.04 - clean install
