### ISSUE TITLE
Flash files are not covering whole window

### ISSUE THREAD

**Issue by Wizard13** [nwjs/nw.js#7628]
NWJS Version : 0.50.0 32bit sdk
Operating System : Windows 7 SP1 x4bit

### Expected behavior

Flash files should open covering whole window

### Actual behavior

Flash files open covering just the top of the window

### How to reproduce

I know that Flash is being phased out, but I use nw.js to load some local flash files with direct links to .swf files. Up until v0.49.2 (chromium 86) all swf files would load covering the whole window. With v0.50.0 (chromium 87) swf files are now covering the top of the window, with the rest being just grey. If this happens because of changes in chromium 87, I'm fine with it, I'll just use v0.49.2. I'm attaching screenshots of loading swf file that just displays flash information.
v0.49.2: https://imgur.com/9FYQQKc
v0.50.0: https://imgur.com/N5Q5lge
EDIT: loading swf files indirectly by using html files works even with v0.50.0

**Comment by Blatman** [comment]
Yup - same thing with MacOS 10.13.6 and 0.50.1 - in my case swf is running in iframe

<img width="652" alt="flashtop" src="https://user-images.githubusercontent.com/11089335/99906229-e2cdfb80-2ccd-11eb-8eda-9eb100d79194.png">

**Comment by Wizard13** [comment]
It appears that flash files are using their original size and the browser is not expanding them to the whole screen like in all previous versions.
@rogerwang do you think this a chromium 87 change so there is nothing can be done about it?

**Comment by Wizard13** [comment]
This is a problem in chromium 87. Last version that handles correctly direct loading of SWF files is chromium 86.
