### ISSUE TITLE
Fullscreen not working (on v47+)

### ISSUE THREAD

**Issue by TheAresjej** [nwjs/nw.js#7629]
NWJS Version : Stable 0.52.0 - Win x64
Operating System : Windows 10 LTS (1809 / OS Build 17763.1613)

### Expected behavior

**_v0.46.0 (latest working version)_**
![image](https://user-images.githubusercontent.com/19390797/99911116-87623480-2cf2-11eb-8f89-b8ea03ccb296.png)
![image](https://user-images.githubusercontent.com/19390797/99911122-8d581580-2cf2-11eb-9e62-76fc268c455a.png)

### Actual behavior

**_v0.52.0_**
![image](https://user-images.githubusercontent.com/19390797/99911185-e58f1780-2cf2-11eb-87b1-35cabc4c800d.png)
![image](https://user-images.githubusercontent.com/19390797/99911197-fb044180-2cf2-11eb-9e00-24c0127e4bf9.png)

### How to reproduce

1. Download [Tempate](https://web.tresorit.com/l/GSQ2Y#Yi_O0M6bSkFm2MPJRrI5Kg) (same project with two versions of nw.js)
2. Click on Fullscreen Button
3. Old - working
4. New - bug 😞

![image](https://user-images.githubusercontent.com/19390797/99911407-7b777200-2cf4-11eb-88ef-9a0d92875f8a.png)

**Comment by HakobiDev** [comment]
Same here @rogerwang

**Comment by TheRealDannyyy** [comment]
I just found this and I think this might be related or even the cause for your problem.
https://github.com/nwjs/nw.js/issues/7657

**Comment by TheAresjej** [comment]
@AshleyScirra any news? 😟 (this problem makes it impossible to use newer versions of nw.js for construct2)

**Comment by AshleyScirra** [comment]
This issue is filed for NW.js, not Construct. It's not something we can fix or have responsibility for.

**Comment by TheAresjej** [comment]
Enabling the _**Resizable window**_ option works as expected (#7657)
![image](https://user-images.githubusercontent.com/19390797/110936641-813fa480-8331-11eb-8458-aedcaa3617b2.png)

**Comment by TheAresjej** [comment]
The problem has been solved in version 53. 🙌
