### ISSUE TITLE
Excessive/Constant writing to disk

### ISSUE THREAD

**Issue by Tatwi** [nwjs/nw.js#7634]
======== TEMPLATE BUG FORM ========

NWJS Version : nwjs-sdk-v0.49.2-win-x64 and nwjs-v0.49.2-win-x64
Operating System : Windows 10 Home 64Bit 20H2

### Expected behavior

I would expect that an empty web app wouldn't be constantly writing to my SSD.

Running my web app in a Google Chrome (87.0.4280.66) incognito window, using a simple Python web server, has no appreciable hard drive activity after it loads, just the occasional blip. This is the behavior I would expect.

### Actual behavior

It constantly writes to the drive. Even an empty project does this.

### How to reproduce

1. Extract nwjs-sdk-v0.49.2-win-x64.zip or nwjs-v0.49.2-win-x64.zip
2. Open the folder
3. Double click on nw.exe
4. Open Task Manager and/or Resource Monitor
5. Be horrified how by many MB/s are _constantly_ being written to your solid state drive _for reasons unknown_.

### Comments

I only noticed this issue today, but after testing a few older version (from as far back as Dec 2018), I'm seeing the same behavior in the older versions too.

What exactly is happening here?

I will admit that my usage and knowledge of NW.js is simply extract/copy/paste/use, but isn't that kind of the point NW.js, to be that simple to use? It works great and I like it, but this inexplicable excessive writing is a problem.

Thank you for your time and consideration! :)

**Comment by djmisterjon** [comment]
you maybe doing something wrong for me when is idle, nothing happened.
![image](https://user-images.githubusercontent.com/24865815/100825849-f9d7c080-3426-11eb-8a5e-aa37dfb5d473.png)

**Comment by Tatwi** [comment]
It seems fine now, which is great! The other day both my web app (RocketTux) and the plain NW.js files were writing a constant 4MB/s each time I opened them, lasting until I closed them. The longest test was 10-15 minute when I made tea and the plain exe was still writing when I got back. Today? No problems. Curiously, I haven't changed anything in the interim.
![seems_normal_now](https://user-images.githubusercontent.com/9004870/101085621-b2b01380-357d-11eb-9266-302754687706.PNG)
Life sure is weird sometimes. I guess I will close this one shrug and a smile. =)

**Comment by jianglinchun** [comment]
I had the same problem.
I installed pgAdmin4 version 5.2 on my MAC OS 11.3.1
The pgAdmin4 main process was crashed.
The nwjs helper process consume nearly 2T write to my ssd from about 5pm to 11pm.
My ssd got high temperature to 86.

For your reference.
