### ISSUE TITLE
0.50.0 incorrect args in c++ method

### ISSUE THREAD

**Issue by SHELLes84** [nwjs/nw.js#7636]
NWJS Version : 0.50.0 x32, 0.50.1 x32
Operating System : Win10 x64 20H2

### Expected behavior

Hello. I update NWJS in my x32 project from 0.43.0 to 0.50.1
And project don't work. I try understand what wrong - and i found it
When i get args in my function - first args[0] is correct. All next args are wrong.

### Actual behavior
In NWJS 0.49.2 - all ok
In NWJS 0.50.0 - error
In NWJS 0.50.1 - error

### How to reproduce
I write small test project to show the problem. In progect i received 2 number, calc sum, and return answer to console.

main.cpp
```
void test(const FunctionCallbackInfo<Value>& args)
{
	Isolate* isolate = args.GetIsolate();
	const Local<Context>& context(isolate->GetCurrentContext());

	double value1 = args[0].As<Number>()->Value();
	double value2 = args[1].As<Number>()->Value();
	// return sum of number
	Local<Number> num = Number::New(isolate, value1 + value2);
	args.GetReturnValue().Set(num);
}

void Initialize(Local < Object > exports)
{
	NODE_SET_METHOD(exports, "test", test);
}
NODE_MODULE( NODE_GYP_MODULE_NAME, Initialize )
```

exec test func from console
```
var nMynode = require('../mynode');
nMynode.test(6.5, 7.0); 
```
answer in console
`6.5 `

In MSVS 2019 debugger i see:
value1 = 6.5
value2 = 5.16e-144

**Comment by rogerwang** [comment]
Your code may have an issue -- it creates handle without any handle scope.

**Comment by SHELLes84** [comment]
I see many tutorial (for example [https://www.youtube.com/watch?v=O4Rlq_NSkoM](url), [https://www.youtube.com/watch?v=VPhPOEpZ3cI](url) and see this code as valid((
