### ISSUE TITLE
Sometimes webview's method addContentScripts injects script into "mainWorld"

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7637]
NWJS Version: 0.50
Operating System: Windows 10

### Expected behavior

Each time script is injected into webview via addContentScripts method it should be run in an isolated world and it shouldn't interfere with existing scripts on webview, loaded via <script src="..."></script>

### Actual behavior

But sometimes injected script behaves exactly as if it was injected into "mainWorld" https://nwjs.readthedocs.io/en/latest/References/webview%20Tag/#executescript-in-main-world

### How to reproduce

It is not an on-demand reproducible error. It appears in an unpredictable way.

**Comment by rogerwang** [comment]
Please try the latest build: http://dl.nwjs.io/live-build/nw50/20201128-025700/1b058a3a2/v0.50.2/

**Comment by Sunvas** [comment]
It seems like the problem was solved.
