### ISSUE TITLE
If NW.js support Mac version of 11.0.1??

### ISSUE THREAD

**Issue by malin1988** [nwjs/nw.js#7638]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 30.5
Operating System : Mac 11.0.1

### Expected behavior

Not Crash

### Actual behavior

sometimes crash

### How to reproduce

Our app can be downloaded from http://app.a.ke.com，you can run it and it will crash sometimes，which never happens before on Mac OS.
Could you tell me if NW.js has a stabel version to support Mac of 11.0.1，and which NW version it is，thank you.

**Comment by rogerwang** [comment]
You are using 0.30.5. Please try the latest version. Thanks.

**Comment by rogerwang** [comment]
close until more information is available.
