### ISSUE TITLE
Compile it as a library and then make it available throught c code

### ISSUE THREAD

**Issue by litch0** [nwjs/nw.js#7647]
NWJS Version : Latest (if possible)
Operating System : Linux, windows and Macos

good day, I am working on a project that needs a webview, but i am in a big trouble. I started looking to use Cef but it is very Large and make some parts of my project break. Then I looked into building an embeder for servo and / or netsurf and I also gived up because of the complexity.
Then I discovered that you guys, so my question is: Is it possible to build it as a shared library and then call it from c code?
My objectives  are:
* Platform independent window with some events (resize, close, new document request (if possible) )
* open a specific url like (http) doens't need https but it would be good to have
* execute javascript and (if possible) webassembly
* Inter process communication if possible (I can use sockets if they are not possibe)

**Comment by bluthen** [comment]
If it is always it's own window. I think it would be way easier just to execute nw it as an external process. Then use pipes, or websocket to communicate.

**Comment by litch0** [comment]
the problem is ship node with the app

**Comment by litch0** [comment]
But ok, Thanks for the info
