### ISSUE TITLE
net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by zynydfcdhj** [nwjs/nw.js#7653]
NWJS Version : nwjs 0.35.5
Operating System : win10

I'm having trouble using the webview  api for  extensions to redirect a url
I can redirect to any http or https address but not a file location anyone know why...?

`var requestFilter = {urls: ["*://domain.com/js/index.bundle.*.js"],types:["script"]},handler = function(details) {
return {redirectUrl:chrome.extension.getURL('test.js')}
};
webview.request.onBeforeRequest.addListener(handler, requestFilter,['blocking']);`

package.json
`"web_accessible_resources":["test.js"],`

final effect:
net::ERR_BLOCKED_BY_CLIENT

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so I can reproduce?

**Comment by ayushmxn** [comment]
@zynydfcdhj Closing this for now. If you can provide steps to reproduce, I'd be happy to reopen it.
