### ISSUE TITLE
The nwjc cannot protect string.

### ISSUE THREAD

**Issue by weiluenju** [nwjs/nw.js#7655]
Source Code:

`var password = "test";`

Bin file:

![password](https://user-images.githubusercontent.com/10330207/104996615-25f4e280-5a63-11eb-8e58-f729a19cf955.PNG)

Is this normal?

NWJS Version : 0.50.3
Operating System : Windows10

**Comment by rogerwang** [comment]
This is a duplicate question. Please check https://github.com/nwjs/nw.js/issues/3404#issuecomment-101151518
