### ISSUE TITLE
Why webview tag not fill window layout?

### ISSUE THREAD

**Issue by arbuzovan** [nwjs/nw.js#7660]
NWJS Version :0.50.3
Operating System :Windows 10

I use tag `<webview>`with Google to source. It rendered, but webtag get not all layout.

My index.html code:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
	<style>
		#foo {
		  height:100%;
		  width:100%;
		  margin: 0;
		}
		
		
	</style>
  </head>
  <body>
	<webview id="foo" src="https://www.google.com/"></webview>
  </body>
</html>
```

My package.json code:
```
{
  "name": "helloworld",
  "main": "index.html"
}
```
Screen:
![Image 1](https://user-images.githubusercontent.com/30685348/105191105-c45a7400-5b47-11eb-8f3c-7c3dae5bf6dc.png)

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by Blatman** [comment]
FWIW - I tried it on MacOS and the same but found that it works OK with position: absolute; or position: fixed; included with the style (probably why I haven't noticed it before) - not sure whether that is how it is meant to work but heyho.

The following link discusses the same issue -
https://stackoverflow.com/questions/28194413/chrome-web-app-webview-height-issue
