### ISSUE TITLE
Using color picker html element's eye dropper will crash program.

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#7669]
NWJS Version : 0.51.0
Operating System : win10

When using the eyedropper in the color picker html element, when moving it all the way to the top of a secondary monitor (positioned on left side of main monitor) it will crash the program.

**Comment by ayushmxn** [comment]
This issue is non-actionable. If you're able to provide steps to reproduce/sample code, I'd be happy to reopen it.
