### ISSUE TITLE
Context menu opens at top left of window rather than mouse position since 0.49

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7672]
High Sierra - 10.13.6   tested with 0.48.4-sdk/0.49.0-sdk/0.52.0b1-sdk

Since 0.49.0 user context menu will open at top left of window - until 0.48.4 the menu would open at the position clicked by the mouse. The event object from the later loads looks a bit different and although the e.x and e.y are correct it almost seems as though the width/height values of 1 are being used.
In this test if the red area (body tag) is right-clicked the user menu position will fail with 0.49 or later.
If the green area (html tag) is right-clicked the default system menu will work ok with all loads.

<img width="803" alt="nogood" src="https://user-images.githubusercontent.com/11089335/107126419-b3c82e80-68a7-11eb-9ee2-12611c9d66aa.png">

0.49.0 event
<img width="801" alt="event-fail" src="https://user-images.githubusercontent.com/11089335/107126427-bc206980-68a7-11eb-817f-8098fead5361.png">

0.48.4 event
<img width="804" alt="event-ok" src="https://user-images.githubusercontent.com/11089335/107126431-c0e51d80-68a7-11eb-933a-4082504e4b77.png">

Test App -
[contextmenutest.zip](https://github.com/nwjs/nw.js/files/5937390/contextmenutest.zip)

**Comment by mishagin-tim** [comment]
@rogerwang Thats because nwjs can't work with non-integers as a coordinates for context menu. I've already met this.

**Comment by Blatman** [comment]
Just tried 0.55.0-sdk and it looks like this issue is fixed.
Note: BTW - the build downloaded had a commit hash of invalid hash

**Comment by ayushmxn** [comment]
@Blatman good to close this?

**Comment by Blatman** [comment]
Ah yes  -  it was fixed at some stage but just not signed off.
