### ISSUE TITLE
Downloading NWjs keeps failing (contact server admin)

### ISSUE THREAD

**Issue by TheRealDannyyy** [nwjs/nw.js#7673]
NWJS Version: https://dl.nwjs.io/v0.49.0/nwjs-sdk-v0.49.0-win-x64.zip
Operating System: Windows 10 using latest Firefox (also fails in Chrome)

### Expected behavior
It should download fine, like always.

### Actual behavior
![image](https://user-images.githubusercontent.com/15656049/107223054-00ca1300-6a16-11eb-8f54-e8fffc7975c3.png)

### How to reproduce
1. Start download
2. Notice message

**Comment by rogerwang** [comment]
It works for me. Which IP address does `dl.nwjs.io` resolve there?

**Comment by TheRealDannyyy** [comment]
> It works for me. Which IP address does `dl.nwjs.io` resolve there?
`Tracing route to dl-us-east.nwjs.io [34.206.150.92]`

**Comment by TheJaredWilcurt** [comment]
Can confirm. Same error.

When I `ping dl.nwjs.io` I get the same, `dl-us-east.nwjs.io [34.206.150.92]`

**Workaround:**

* Mirror: https://npm.taobao.org/mirrors/nwjs/v0.51.1/

**Comment by rogerwang** [comment]
Should be fixed now. Please try again.

**Comment by TheRealDannyyy** [comment]
All fine. Thanks for the quick fix!
