### ISSUE TITLE
Regression: Webview plus its devtools crash in v0.50.3 and onwards under amusingly specific conditions

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nwjs/nw.js#7676]
NWJS Version: from v0.50.3 to v0.51.1
Operating System: Windows, at least

### Expected behavior

Webviews should not crash.

![](https://user-images.githubusercontent.com/3174357/100041114-2444df00-2e65-11eb-953a-be104b23bdfc.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/3174357/107869382-f8784900-6ee9-11eb-938f-73a33663bf8a.png)

They do. Ok, now the real context of the issue.

At issue #7588, @rogerwang released a nightly build to fix an issue with nw.js not exiting properly when devtools are attached to a webview. In that particular nightly build, everything worked perfectly. But version 0.50.3 which was intended to publish this fix publicly has broken the pairing of webview and devtools completely.

In my game editor, when a webview with a game loads, devtools are mounted into another webview to inspect the first one. It seems that both webviews crash when devtools are mounted because I can observe the game's page loading and showing their content before going dead.

### How to reproduce

This happens when the webview which serves as a slot for devtools has `allownw` plus `nwfaketop` _and_ when it had a page loaded into it before. Removing one of these factors solves the issue for me.

I have a script that *partially* reproduces the issue: only devtools crash, but not the page it inspected. Execute in any nw app: 

```js
const webviewPage = document.createElement('webview');
webviewPage.setAttribute('partition', 'persist:trusted');
webviewPage.setAttribute('allownw', '');
webviewPage.setAttribute('nwfaketop', '');

const webviewTools = document.createElement('webview');
webviewPage.setAttribute('partition', 'persist:trusted');
webviewTools.setAttribute('allownw', '');
webviewTools.setAttribute('nwfaketop', '');

document.body.appendChild(webviewPage);
document.body.appendChild(webviewTools);

webviewPage.src = webviewTools.src = `https://tsherif.github.io/webgl2examples/oit.html`; // init some page

setTimeout(() => { // wait 5s so both pages load
    webviewTools.showDevTools(true, webviewTools);
}, 5000);
```

**Comment by rogerwang** [comment]
Fixed in https://dl.nwjs.io/live-build/nw51/20210215-031757/47776c5ec/v0.51.2/
