### ISSUE TITLE
Allow JavaScript from Apple events issue

### ISSUE THREAD

**Issue by Unknown-IDs** [nwjs/nw.js#7677]
Hello reader,

I am trying to make my Popcorn-Time (which uses nw.js) interact with my touch bar on my MacBook Pro as a new project. In order to make this work I need to be able to execute JavaScript through AppleScript.

Does anyone know how I can enable this?
<img width="698" alt="Screen Shot 2021-02-13 at 18 53 14" src="https://user-images.githubusercontent.com/76119380/107859185-0a011880-6e38-11eb-9a31-da6d9378d77e.png">

And in the com.nw-builder.popcorn-time.plist I added a property "AllowJavascriptFromAppleEvents" that is set to 1.
<img width="577" alt="Screen Shot 2021-02-13 at 18 52 20" src="https://user-images.githubusercontent.com/76119380/107859183-09688200-6e38-11eb-8cf4-0ed026730ce7.png">

So far no luck on getting it worked, hopefully someone here can help me out. 

Best regards.

**Comment by djmisterjon** [comment]
It seem not related to nwjs but apple os.
These seem two steps !

Enable the Develop menu in Safari if not already enabled in Safari’s Advanced preferences.
Enable Allow JavaScript from Apple Events in the Develop menu
https://www.jamf.com/jamf-nation/discussions/24713/modifying-com-apple-safari-plist-file-with-macos-sierra-10-12

**Comment by Unknown-IDs** [comment]
@djmisterjon thank you for your replay, unfortunately that is not the solution. I already have Safari and Chrome enabled to allow JavaScript from Apple events. For so far I can tell, Popcorn-Time is using Chrome:
![Screen Shot 2021-02-15 at 01 10 32](https://user-images.githubusercontent.com/76119380/107893303-b6bbc280-6f2a-11eb-973a-f0de8f097c36.png)

I already asked about this issue at [https://github.com/popcorn-official/popcorn-desktop](https://github.com/popcorn-official/popcorn-desktop), they told me it has more to do with nwjs, which Popcorn Time runs on.

**Comment by Unknown-IDs** [comment]
I finally manage to get it work by a lot of searching and trying, I found the right "JSON" file where I had to put property named "allow_javascript_apple_events"! 
![Screen Shot 2021-02-15 at 01 38 30](https://user-images.githubusercontent.com/76119380/107894116-d6ed8080-6f2e-11eb-9482-81ea8fa91deb.png)
