### ISSUE TITLE
NWJS 0.51.0 Speech Recognition dont work after export to desktop Game

### ISSUE THREAD

**Issue by constructVOD** [nwjs/nw.js#7679]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.5.1
Operating System : Win 10 64bit

### Expected behavior

<!- Hard to say, my network works fine and all works only using preview or browser chrome ->

### Actual behavior

<!- Game dont want to connect with Net->

### How to reproduce
-  Just need to open Speech Recognition Example and export using NWJS

- I receive text informnation 'Network Error"

**Comment by ayushmxn** [comment]
Issue is inactionable. If you add in more info such as steps to reproduce, I'll reopen it
