### ISSUE TITLE
Debug Tools keep on getting smaller window on restart

### ISSUE THREAD

**Issue by Regiden** [nwjs/nw.js#7680]
NWJS Version : 51.1
Operating System : Windows 10

### Expected behavior

The Debug Tools should keep the position and size when you restart the app and open the debug tools. Including snapping.

### Actual behavior

Debug tools keep progressively getting smaller with each restart if not manually set.

### Steps

Simply start nw.js without anything and open the debug tools via the context menu. Now use WindowsKey + Left/Right to snap the window to one of the sides. Close nw.js and restart. Open the debug tools again. No the they suddenly have less width/height.
This process can be repeated and the debug tools will get smaller over time. 

If its any help, I have my taskbar set to the left. But this problem also occurs when having the tools on another monitor without any taskbar. Completely maximizing the window does work, but well... takes away literally all the space. Seems to always cut away some width/height with each restart.

**Comment by panther7** [comment]
Yes, devtools are smaller and smaller after startup.

**Comment by panther7** [comment]
Still in NWjs 0.52.0

**Comment by panther7** [comment]
Still in NWjs 0.53.0

**Comment by sysrage** [comment]
I'm seeing this, too. Would love a fix or workaround!

**Comment by panther7** [comment]
Still in NWjs 0.57.0 :-/

**Comment by robtoll** [comment]
Very old bug this. Any workarounds or fixes on the horizon?

**Comment by TheJaredWilcurt** [comment]
Verified Issue occurs on the following versions:

OS            | Version | Arch | Status
:--             | :--         | :--     | :--
Win7 64   | 0.14.7    | 64    |  ✅ Stays same size
Win7 64   | 0.33.4    | 64    |  ✅ Stays same size
Win7 64   | 0.42.5    | 64    |  ❌ Gets BIGGER!
Win7 64   | 0.49.2    | 64    |  ❌ Gets smaller
Win7 64   | 0.60.0    | 32    |  ❌ Gets smaller
Win7 64   | 0.60.0    | 64    |  ❌ Gets smaller

**Comment by sysrage** [comment]
@rogerwang I'd appreciate if you could take a look at this. Some Windows 10 results:

OS | Version | Arch | Status
-- | -- | -- | --
Win10 64 | 0.14.7 | 64 | ✅ Stays same size
Win10 64 | 0.33.4 | 64 | ✅ Stays same size
Win10 64 | 0.34.5 | 64 | ✅ Stays same size
Win10 64 | 0.35.5 | 64 | ✅ Stays same size
Win10 64 | 0.40.0 | 64 | ✅ Stays same size
Win10 64 | 0.41.3 | 64 | ✅ Stays same size
Win10 64 | 0.42.3 | 64 | ✅ Stays same size
Win10 64 | 0.42.4 | 64 | ❌ Gets BIGGER!
Win10 64 | 0.43.0 | 64 | ❌ Gets BIGGER!
Win10 64 | 0.43.3 | 64 | ❌ Gets BIGGER!
Win10 64 | 0.43.4 | 64 | ❌ Gets BIGGER!
Win10 64 | 0.43.5 | 64 | ✅ Stays same size
Win10 64 | 0.44.0 | 64 | ✅ Stays same size
Win10 64 | 0.46.0 | 64 | ✅ Stays same size
Win10 64 | 0.47.0 | 64 | ✅ Stays same size
Win10 64 | 0.48.0 | 64 | ✅ Stays same size
Win10 64 | 0.48.4 | 64 | ✅ Stays same size
Win10 64 | 0.49.0 | 64 | ❌ Gets smaller
Win10 64 | 0.60.0 | 32 | ❌ Gets smaller
Win10 64 | 0.60.0 | 64 | ❌ Gets smaller

**Comment by sysrage** [comment]
FYI, you don't have to restart anything to reproduce. You can just keep closing and re-opening the DevTools window.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
