### ISSUE TITLE
Renaming of nwjs process to custom name

### ISSUE THREAD

**Issue by vaibhavrmore1** [nwjs/nw.js#7692]
As mentioned by  @VasiliyIsaichkin

Using command-tool from https://github.com/electron/rcedit or https://github.com/VasiliyIsaichkin/rcedit/tree/master/bin/rcedit.exe to rename process

`rcedit MyApp.exe --set-version-string "FileDescription" "MyApp"`

It doesn't allow me to install the exe . Therefore throws an error, "rcedit is not a command".

Is the tool expired and something else to be modified?
Or the latest version of the tool is available for use?

**Comment by ayushmxn** [comment]
This doesn't seem to be related to NW.js
