### ISSUE TITLE
Mac OS — What version?

### ISSUE THREAD

**Issue by jonaslund** [nwjs/nw.js#7699]
There is no documentation on what version supports what Mac OS version.
The current version 0.52.0 is not supported on Mac OS 10.10.5, but which version is?

**Comment by bluthen** [comment]
I personally map the upstream chromium version that nwjs is based on to figure which is supported with nwjs. Or sometimes look at what version chrome itself supported that version of MacOS.

I show it being Chromium 88, so you can give NWJS v0.50.x a try.
