### ISSUE TITLE
Enable or Expose SODA API (Speech On Device API) 

### ISSUE THREAD

**Issue by mscreenie** [nwjs/nw.js#7701]
Hi. I'd like to request a feature or know if it's possible.

Chrome (I'm not sure if Chromium too) has recently release SODA (Speech On Device API). It seems after enabling this a download occurs of what is presumably a language pack and speech models. 

It allows offline speech to text and closed captioning of Web videos. 

It would be super useful to enable this. I'd like to develop a feature for those with hearing difficulties. 

I would think enabling this would allow a whole new class of different applications.

Thank you

**Comment by ayushmxn** [comment]
https://nwjs.readthedocs.io/en/latest/References/Command%20Line%20Options/
https://peter.sh/experiments/chromium-command-line-switches/#enable-speech-dispatcher
Closing for now. If any problems arise, ping me here I'd happy to reopen!
