### ISSUE TITLE
Resizing NW.js window causes strange popup resolution box in top right corner

### ISSUE THREAD

**Issue by NbrTDB** [nwjs/nw.js#7706]
NW.js SDK v0.50.1

For brevity I'll skip the template as it's only a brief question!

When the user resizes a window (e.g. via dragging, or via maximising), a white/translucent box appears in the top-right of the NW.js window showing the newly adjusted window resolution.

How do we turn this off? My Google-fu is weak on this one, it seems, and I couldn't find it mentioned in the docs (perhaps I don't know what to look for).

Is this just because it's an SDK build?

**Comment by mishagin-tim** [comment]
Yes, it is

**Comment by NbrTDB** [comment]
Thanks for the info! OK, that makes sense; is there a way to turn it off for dev builds?

**Comment by tharatau** [comment]
Hope the issue was resolved. Please use the mailing list for questions, thanks!
