### ISSUE TITLE
Blurry text 

### ISSUE THREAD

**Issue by skyfyx** [nwjs/nw.js#7710]
NWJS Version : 0.52.3
Operating System : Windows

### Actual behavior

when I run my application the text in it is really blurry. But when I look in the browser it is not.
Maybe i missed an option ? 

### How to reproduce

Create an application on windows and launch.

Thanks for your help

**Comment by ayushmxn** [comment]
@skyfyx issue is non-actionable. If you had a minimal repro, I'd be happy to reopen the issue.
