### ISSUE TITLE
Packaging recommendations no longer active

### ISSUE THREAD

**Issue by medains** [nwjs/nw.js#7722]
NWJS Version : latest
Operating System : all

### Expected behavior

Documentation refers to active projects for packaging and distribution.

### Actual behavior

nw.js/docs/For Users/Package and Distribute.md 

Recommended:  nwjs-builder-phoenix (archived by developer)
Also mentions: nw-builder (over 2 years since last commit)

Lack of maintenance on these projects will make them poorer and poorer choices as vulnerabilities in dependencies go unpatched etc...

Forking the recommended builder project and bringing it under the nwjs project banner seems like a sensible approach.

**Comment by bluthen** [comment]
Already open, Related #7693
