### ISSUE TITLE
file:// is ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7732]
NWjs 0.53.1 (and lower works properly)
NWjs 0.54.0 is *broken*

Windows 10 x64 (latest)

Example: [demo.zip](https://github.com/nwjs/nw.js/files/6568772/demo.zip)

NWjs 0.54.0
![2021-05-31 10 06 28](https://user-images.githubusercontent.com/3808250/120162150-637b3080-c1f8-11eb-87fd-7327ba9865b3.png)

NWjs 0.53.1
![2021-05-31 10 06 51](https://user-images.githubusercontent.com/3808250/120162154-6413c700-c1f8-11eb-8921-649bd8bf8d11.png)

**Comment by TheJaredWilcurt** [comment]
I was able to reproduce this on Windows 10.

Possible workarounds:

* Relocate file to a relative subdirectory and use relative linking
  * `file.png`
  * `../file.png`
* Use Node.js to read in the file contents and convert them to base 64 encoding, then embed it into the `src` attribute on the element

**Comment by panther7** [comment]
Relative path linking i cant using. FileReader and conver to base64 is overhead for me, but actually is it the only fix. :-/

@TheJaredWilcurt

**Comment by nebular** [comment]
does not work on OSX either :(

**Comment by TheJaredWilcurt** [comment]
@rogerwang can you confirm is this was an intentional change, or regression?

**Comment by rogerwang** [comment]
It should be a regression. Will look into it. Thanks.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
