### ISSUE TITLE
Expose a way to listen to native WM_POINTER* messages on Windows

### ISSUE THREAD

**Issue by sirisian** [nwjs/nw.js#7735]
I have a kiosk where I need to see if it's idle, but in some cases the user is touching an iframe. Touch events over iframes aren't listenable in the browser so my application has no idea if the kiosk is actually idle.

Windows doesn't allow WM_POINTER* events to be hooked from a DLL so I can't write a node library or anything to accomplish this outside of nw.js. (I tried just to be sure nothing has changed).

If it isn't too much work it would be nice to have a simple API on win to listen for native pointer events.

Alternatively if you know of another way to detect touch events (or just that there was a touch event) over an iframe then feel free to close this. I've come up empty.

**Comment by ayushmxn** [comment]
https://nwjs.readthedocs.io/en/latest/References/webview%20Tag/
Webview may be of use to you.

Also, please ask questions via the [mailing list](https://groups.google.com/g/nwjs-general) - so you can get your questions answered faster.
