### ISSUE TITLE
Load nwjc generated bin as main script in application manifest

### ISSUE THREAD

**Issue by cdog** [nwjs/nw.js#7736]
NWJS Version : 0.54.0 (latest)
Operating System : MacOS

### Expected behavior

Starting application from `app.bin` or `app.js` should run the same.

![expected](https://user-images.githubusercontent.com/690647/121085935-d2511e80-c7e2-11eb-9450-8a03fec32064.png)

### Actual behavior

Trying to load `app.bin` as `main` script prompts to save the file instead of executing it.

![actual](https://user-images.githubusercontent.com/690647/121085953-d715d280-c7e2-11eb-9fff-e87057cab117.png)

### How to reproduce

Application code `app.js`:

```js
nw.Window.open('https://nwjs.io/', {}, function(win) {});
```

Applicaton manifest `package.json`:

```json
{
  "main": "app.js",
  "name": "nw-demo"
}
```

Launch the application and see new window is created loading pointed source.

Compile source with `nwjc`:

```bash
$ nwjc app.js app.bin
```

Update `package.json` to load `app.bin` as `main` script:

```json
{
  "main": "app.bin",
  "name": "nw-demo"
}
```

Launch the application.

**Comment by cdog** [comment]
Per documentation `win.evalNWBin` can be used to load compiled JavaScript:

```js
nw.Window.get().evalNWBin(frame, 'binary.bin');
```

Is there any way to load a `.bin` file as main script? My application doesn't use any HTML as entrypoint (which would already open a window) - it is a background script which handles other windows when needed.

Basically the `.bin` file opens the application window:

```js
nw.Window.open('https://nwjs.io/', {}, function(win) {});
```

Please let me know. Thanks.

**Comment by ayushmxn** [comment]
@cdog Currently you can only load the binary via `evalNWBin`. That could be a neat feature request although Roger will have to weigh in on if that is viable/possible.
