### ISSUE TITLE
How to turn off the security policy of Google browser

### ISSUE THREAD

**Issue by Thunder7991** [nwjs/nw.js#7737]
NWJS Version : 0.53.0 
Operating System :Win 10
When uploading a folder, it will prompt the pop-up window of the number of files displayed inside the folder.
How to turn off the pop-up prompt of "please only operate once when you trust the website" in the upload folder of Google browser?

![image](https://user-images.githubusercontent.com/61643801/121155307-44287700-c87a-11eb-9493-86911a8c59c3.png)

**Comment by Thunder7991** [comment]
It has been a long time. Do you have any predecessors who know how to solve this problem?

**Comment by ayushmxn** [comment]
https://peter.sh/experiments/chromium-command-line-switches/
@Thunder7991 this may help

Please ask questions via the [mailing list](https://groups.google.com/g/nwjs-general).
