### ISSUE TITLE
How to manage chrome extensions?

### ISSUE THREAD

**Issue by cheungchingli** [nwjs/nw.js#7742]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :0.54.0
Operating System :Mac Monterey 12.0

### Expected behavior

<!- What do you think should happen? ->
I want to open the ```chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html```, but got ```ERR_BLOCKED_BY_CLIENT```, maybe nw should have some buttons to open the main page.

### Actual behavior

<!- What actually happens? ->
Got ```ERR_BLOCKED_BY_CLIENT```
### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by ayushmxn** [comment]
https://nwjs.readthedocs.io/en/latest/References/Chrome%20Extension%20APIs/
