### ISSUE TITLE
nw.exe getting 301 HTTP status code on making HTTP request to localhost

### ISSUE THREAD

**Issue by common-tasks** [nwjs/nw.js#7751]
NWJS Version : 0.25.4
Operating System: Windows 10

The angular application in the HTML page loaded by nw.exe makes an HTTP request to localhost, it is like http://localhost:portnumber/endpointuri. And there is a rest endpoint that listens to the request and sends the response.
It's a multi-user environment logged in to the same operating system and for one of the user HTTP requests is going to some other IP that is not the current IP and getting rejected by getting status code as 301.
On deleting the profile data %localappdata%\AppName\User Data, everything starts working.

Do you store any previous network-related information in the User Data which gets corrupted over a period of time?

**Comment by bluthen** [comment]
301 status codes are cachable by browsers, which would probably include nw.js.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html

`A response received with a status code of 200, 203, 206, 300, 301 or 410 MAY be stored by a cache and used in reply to a subsequent request`

**Comment by frank-dspeed** [comment]
@anurag2911 did that solve the issue if yes please close this.

**Comment by ayushmxn** [comment]
Closing for now. If this is still an issue, ping me here and I'll reopen.
