### ISSUE TITLE
Sessions are not maintained between NWJS application restarts

### ISSUE THREAD

**Issue by sunilrebel** [nwjs/nw.js#7752]
NWJS Version : 0.45.6 and 0.52.0 (tested both)
Operating System : MacOS and Windows 7 (32 bit) (tested both)

### Expected behavior

When a user logins into any website, the session is created. 
After closing the NWJS desktop application and starting it back (or restarting the system) the user should be already logged in to the website based on previous session, just like Google Chrome browser.

### Actual behavior

From past 1 week, without even changing anything in desktop application, the sessions are not maintained of all websites.
Now all of the users, needs to login to each and every website everytime the software is restarted.

### How to reproduce

package.json
```
{
  "name": "app",
  "version": "31.0.1",
  "description": "app",
  "author": "app",
  "license": "UNLICENSED",
  "main": "main.html",
  "nodejs": true,
  "single-instance": true,
  "page-cache": false,
  "scripts": {
    "start": "nw ."
  },
  "node-remote": "<all_urls>",
  "window": {
    "show": true,
    "frame": false,
    "position": "center",
    "width": 800,
    "height": 460,
    "min_width": 800,
    "min_height": 460,
    "resizable": false,
    "icon": "resources/images/favicon.png"
  },
  "dependencies": {
    "crypto": "latest",
    "crypto-js": "latest",
    "jquery": "latest",
    "lodash-core": "^4.17.19",
    "log4js": "latest",
    "node-machine-id": "latest",
    "rimraf": "latest",
    "semver": "latest",
    "shelljs": "latest"
  },
  "chromium-args": "--enable-logging=stderr --disable-gpu --user-data-dir='/Users/sunil/sunil/temp/userdatadir/profile1'"
}
```

`main.html` imports `main.js` via `script` tag
`main.js` has `onClick` event listener on a button
`onClick` opens up a new window with a website url (we can try any website here, like github.com) using below code
```
                        nw.Window.open(url, {
                            show: displayWindow,
                            position: 'center',
                            width: Math.round(screen.width),
                            height: Math.round(screen.height),
                        }, def.handler);
```

`def.handler` does nothing, but injecting any js file if required and handle message passing between the window

1. Click on the button to open the window
1. Login into the website which is opened in window
1. Next close the software/application completely
1. Open it up and click on the same button to open same url, it is not already logged in. User have to login again now. This is the problem.

**Comment by frank-dspeed** [comment]
nwjs does not maintain the state like a browser would do you need to handle that your self. nwjs is not a browser replacement it is a framework to build apps and is a chrome apps platform it is not a browser the whole browser part is missing.

**Comment by ayushmxn** [comment]
@sunilrebel check out https://github.com/seald/nedb

**Comment by ayushmxn** [comment]
If you still have problems after using nedb ping me here and I'll reopen the issue.
