### ISSUE TITLE
Import ES6 modules from Node context

### ISSUE THREAD

**Issue by toyssamurai** [nwjs/nw.js#7753]
Is it even possible to import ES6 modules from within the Node context? I've managed to get it work from the "node-main" script, but that's pretty much the only place I could get it to work.

**Comment by CxRes** [comment]
This has been a long standing issue that I first raised in the nwjs forums maybe four years ago. For some more recent context look at #7639.

**Comment by CxRes** [comment]
A temporary way to solve this would be to use the [esm](https://github.com/standard-things/esm) module. This will hijack the require to provide es module loading (effectively you will use this and not the native import/export implementation all throughout). But in my initial testing it seems work pretty well!

**Comment by ayushmxn** [comment]
Duplicate of #7639
