### ISSUE TITLE
import.meta.url showing an extension path not the script path

### ISSUE THREAD

**Issue by TomasHubelbauer** [nwjs/nw.js#7758]
I've reproduced on the latest version of NW.js and I've [searched for `import.meta.url` to no results](https://github.com/nwjs/nw.js/issues?q=is%3Aissue+import.meta.url).

I am not sure if this is technically possible with how NW.js works, but currently `import.meta.url` prints a path into a web extension as opposed to a file system path of the script. If this is possible to be somehow intercepted and converted to the file system path, that would be very useful as it would provide an ESM-canonical way of figuring out the current script's path on the file system. Thank you

NWJS Version : nwjs-sdk-v0.54.1-osx-x64
Operating System : macOS

### Expected behavior

`import.meta.url` should return a `file:///` path.

### Actual behavior

`import.meta.url` returns `chrome-extension://dicgdfmjdcflpdchdnbjfppblikeeofl/index.js`.

### How to reproduce

- Download the latest SDK
- Copy it to a new folder
- Create `index.html` referencing `index.js` and `package.json` with `index.html` for `main`
- Add this to `index.js`:
  ```js
  window.addEventListener('load', () => {
    document.body.append(import.meta.url);
  });
  ```
- Run `nwjs-sdk-v0.54.1-osx-x64/nwjs.app/Contents/MacOS/nwjs .`
- See the incorrect path printed:
  
<img width="571" alt="image" src="https://user-images.githubusercontent.com/6831144/127733528-1a39450b-7bb1-4bb1-909e-207eca5db8d4.png">

**Comment by frank-dspeed** [comment]
that is the real path you can not retrive the path this way at this point you need to retrive import meta from the node-main when that supports esm and then set that value somewhere

**Comment by TomasHubelbauer** [comment]
I see. I also tried `__dirname` and `__filename` to see if they maybe are injected into the browser context like `require` is, but they do not seem to be. Just putting this out here if anyone finds it useful in the future.

**Comment by TomasHubelbauer** [comment]
Fair enough, I do not have any experience with Chromium apps, only web apps, so this was news to me. I expected to see `file://` URLs. I do have a little bit of experience with Chrome extensions though where if I remember right. the same thing applies, so I see what you mean.

**Comment by frank-dspeed** [comment]
@TomasHubelbauer the chrome app and extension url is what enables the whole chrome apps and extension api support in your main background Page.

You get access to all internal API's like Screen and so on. You can Modify any URL and so on for example you can even disable cors via that as you can intercept requests and modify headers.

**Comment by frank-dspeed** [comment]
@TomasHubelbauer please close this issue if the question is answered.
