### ISSUE TITLE
Is there a way to implement tileserver-gl inside nw ?

### ISSUE THREAD

**Issue by Kobrairaq** [nwjs/nw.js#7760]
Im trying to make a tileserver-gl working with a nw desktop program so when the program start the server start with it if some one can help me out ?

**Comment by frank-dspeed** [comment]
@Kobrairaq this is not the right place to ask such questions ask it on stackoverflow post me the link here and close the issue and i will write you a answer on stackoverflow. Shot answer yes it is possible to start the server  via the nodejs process management.
