### ISSUE TITLE
"node-main" silently fails if there bug in it

### ISSUE THREAD

**Issue by CxRes** [nwjs/nw.js#7761]
NWJS Version : 0.55.0 (64bit windows)
Operating System : Windows 10 x64

### Expected behavior

When there a bug in node-main, nwjs should complain about the bug (I would expect in devtools for background page).

### Actual behavior

When there a bug in node-main, nwjs fails silently. `process.mainModule.exports` is not populated. 

### How to reproduce

main.js
```js
nw.Window.open('./index.html', {
  show: true,
  position: 'center',
});

```
node-main.js
```js
module.exports.foo = 'foo';
```
index.html
```html
<script>console.log(process.mainModule.exports)</script>
```

The above should work as expected and when you check in the devtools you see:
![nwjsErrorCase1](https://user-images.githubusercontent.com/2706227/127825544-6d080ec6-aafc-4c2d-9c21-76a89dee37c9.png)

Now introduce a bug in node-main.js:
```js
const x = 1;
x = 2;
module.exports.foo = 'foo';
```

Now if you open devtools all you see is:
![nwjsErrorCase2](https://user-images.githubusercontent.com/2706227/127825669-8efbd66e-db6d-46cc-89f9-2b0a9a212032.png)

No error in the background page:
![nwjsNoError](https://user-images.githubusercontent.com/2706227/127826816-18ad7eee-1ccf-4f6b-a785-cc7e4c2a42c2.png)

Obviously, exports is not populated! But no where, whether devtools for the background page or the browser page is the bug reported.

**Comment by frank-dspeed** [comment]
you need to start with the --inspect-brk=<port> option and debug it in a external window.

**Comment by CxRes** [comment]
@frank-dspeed Could you please elabourate "debug in an external window"? I started with the --inspect-brk flag, setting port and the node-main file name on command line and in the js flags. Both did not work :(

Also, in my experience nodejs cli flags generally do not seem to work with nw command. Do you want me to specify them with nw command or elsewhere?

**Comment by CxRes** [comment]
**I AM 100% CERTAIN THIS IS A BUG AND HAVE NEW INFORMATION AND HAVE OPENED A NEW ISSUE. SEE LINK ABOVE!!!**
