### ISSUE TITLE
IFRAMES with the nwdisable and nwfaketop attributes cannot call alert(), confirm() or prompt()

### ISSUE THREAD

**Issue by Jermolene** [nwjs/nw.js#7763]
NWJS Version : v0.55.0
Operating System : macOS Big Sur 11.4

### Expected behavior

HTML pages stored in the file system and displayed via an iframe with the `nwdisable` and `nwfaketop` attributes should be able to call `alert()`, `confirm()` or `prompt()` with the expected results.

### Actual behavior

The methods fail with an error `A different origin subframe tried to create a JavaScript dialog. This is no longer allowed and was blocked`.This appears to be due to an upstream change in the Chrome Platform:

https://www.chromestatus.com/feature/5148698084376576

### Background

[TiddlyDesktop](https://github.com/Jermolene/TiddlyDesktop) is an application based on nw.js that lets users edit [TiddlyWiki](https://tiddlywiki.com/) HTML files. We’ve been using nw.js since January 2014.

The TiddlyWiki HTML files are stored in the filesystem, and loaded into a window via an iframe with the `nwdisable` and `nwfaketop` attributes to make the HTML file think that it is displayed in a top-level browser window.

With the latest nw.js v.0.55.0 it is no longer possible for these embedded HTML files to call `alert()`, `confirm()` or `prompt()`. This appears to be due to an upstream change in the Chrome Platform:

https://www.chromestatus.com/feature/5148698084376576

Would it be possible to suppress the same origin checks when using  `nwdisable` and `nwfaketop`, or is there another way to restore the old behaviour?

**Comment by frank-dspeed** [comment]
It should be possible to send post https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site

please try that and if that does not work i will look more deep into it

removing the same origin policy for a nwdisabled iframe would 100% breake the security model

**Comment by Jermolene** [comment]
> It should be possible to send post https://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site
>
> please try that and if that does not work i will look more deep into it

It is not possible to use that technique because we need to load existing TiddlyWiki HTML files belonging to the user, and those files already include `confirm()` calls.

> removing the same origin policy for a nwdisabled iframe would 100% breake the security model

I didn't mean to remove it entirely. The problem is that `nwdisable` and `nwfaketop` are supposed to make the embedded iframe be indistinguishable from a top level window, but that no longer holds true if the iframe cannot call `confirm()` etc. Isn't that a regression?

I was hoping that it might be possible to avoid the same origin checks when displaying browser dialogs from iframes with those flags.

**Comment by frank-dspeed** [comment]
For me it sounds like a complex scenario i am not sure what i would do. The only thing that is clear is that enabling confirm(), alert(), inside a subframe is not the right thing to do. I think it is possible to shim that functions so that you modify the window global of the iframed page.

i am 100% sure there is a better way to get the desired effect.

i have no time to inspect where and why your wiki pages call that functios but there must be a better way.

**Comment by Jermolene** [comment]
> For me it sounds like a complex scenario i am not sure what i would do. The only thing that is clear is that enabling confirm(), alert(), inside a subframe is not the right thing to do.

I was not suggesting that they be enabled inside all subframes, just within those that meet the special criteria of having the `nwtop` and `nwdisable` attributes.

> I think it is possible to shim that functions so that you modify the window global of the iframed page.

There would be no way that I can see of polyfilling the behaviour of `alert()` or `confirm()` because both of them suspend JS execution while the dialog is displayed. It would not be possible to emulate those semantics in JS.

> i am 100% sure there is a better way to get the desired effect.
>
> i have no time to inspect where and why your wiki pages call that functios but there must be a better way.

I appreciate your answers.

Our project has been using nw.js for 7 years. We've benefitted from nw.js's rigorous approach to backwards compatibility for all of that time, and been able to upgrade to each new version without issues (apart from some tweaks necessitated by the big changes back in v0.13.x).

You may be right that there may be another way to achieve what we do, but we've been doing it this way for 7 years without any problems until updating to this release.

**Comment by frank-dspeed** [comment]
blocking js execution is a no brainer

```js
// JS is single th so the whole JS loop is now blocked.
while (true) {
}
```

**Comment by Jermolene** [comment]
Hi @frank-dspeed I appreciate your suggestions.

The problem is that tying up the CPU like that will prevent JS from processing events, and hence it won't receive message from the parent frame.

**Comment by frank-dspeed** [comment]
@Jermolene your maybe right so the only way to solve that is patch the wikipages with correct code that uses promises. so that the implementation is shim able. 

and refactore the code to only execute inside promises as it should be

**Comment by Jermolene** [comment]
Hi @frank-dspeed 

> @Jermolene your maybe right so the only way to solve that is patch the wikipages with correct code that uses promises. so that the implementation is shim able.

With respect, there is another way to solve it: to fix this regression in nw.js.

> and refactore the code to only execute inside promises as it should be

I appreciate your suggestions, but it is not feasible in this case. TiddlyWiki has been widely used for 15 years, so there are many tens or hundreds of thousands of wikis already in use, and we need to retain compatibility with those existing files.

**Comment by frank-dspeed** [comment]
After long thinking i finally got the point your using file:// urls right?

did you think about putting a small express static app into your app and simply point the window to that url for example 127.0.0.1:20999 as soon as the app and your files do come from the same url the same origin does not matter any more any way i found out there is a chrome command line switch that could help:

https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by Jermolene** [comment]
Thanks @frank-dspeed much appreciated

> After long thinking i finally got the point your using file:// urls right?

That's correct. We open a local HTML file that is part of the application, and then that HTML file loads the untrusted HTML files belonging to users via a file:// URI in an iframe with "nwdisabletop" and "nwfaketop" attributes.

> did you think about putting a small express static app into your app and simply point the window to that url for example 127.0.0.1:20999 as soon as the app and your files do come from the same url the same origin does not matter any more 

That would involve considerable re-engineering for our application. As I mentioned, TiddlyDesktop dates from the very earliest days of nwjs, and still uses the "mixed-content" mode from when it was the default way of working. Our code freely mixes the DOM and Node.js, which was originally the promise of those early versions of nw.js (and is still supported today).

> any way i found out there is a chrome command line switch that could help:
> 
> https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

I've been unable to get this to work in the latest nw.js.

**Comment by frank-dspeed** [comment]
@Jermolene we can close this issue here i think as google will remove the functions from the platform and i do not think that nw js needs to provide this functions as they can be implemented in user land the good news is that you do not need to overwrite anything as alert will simply not exist so you can load any alert function that you like

https://twitter.com/Rich_Harris/status/1422930436850860033

**Comment by Jermolene** [comment]
Thanks @frank-dspeed 

> @Jermolene we can close this issue here i think as google will remove the functions from the platform and i do not think that nw js needs to provide this functions as they can be implemented in user land the good news is that you do not need to overwrite anything as alert will simply not exist so you can load any alert function that you like

The fundamental point here is that nw.js has long offered (and documented) a "nwfaketop" attribute on iframes which is described in the docs as making the iframe behave as if it is a toplevel window. This new behaviour with alert/confirm/prompt breaks that feature.

So, the regression is that nwjs used to offer a way of using iframes that made the code in the iframe behave as if it was a top level window, and that that feature is now broken.

I appreciate your suggestions for workarounds, but this still seems to be a regression. And if @rogerwang cannot fix it then you should keep this issue open until the docs have been updated to reflect this.

**Comment by frank-dspeed** [comment]
@Jermolene no your wrong it is a change in chromium 92 and in 93 alert and prompt will maybe gone total.

**Comment by Jermolene** [comment]
> @Jermolene no your wrong it is a change in chromium 92 and in 93 alert and prompt will maybe gone total.

Thanks @frank-dspeed I understand what Chrome is doing, but am I wrong in saying that in nwjs the "faketop" attribute is documented as giving top level window semantics to the contents of an iframe?

**Comment by frank-dspeed** [comment]
@Jermolene your correct with that and it is still doing that but the exemption is the alert and prompt confirm stuff

and that will as sayed get removed so everything should be fine.

**Comment by Jermolene** [comment]
Thanks @frank-dspeed I appreciate your responses

> @Jermolene your correct with that and it is still doing that but the exemption is the alert and prompt confirm stuff

But that exception means that the documentation is no longer accurate, doesn't it?

If the nw.js docs need changing then this is a regression for nw.js.

> and that will as sayed get removed so everything should be fine.

No, it won't be fine. None of the workarounds we've discussed will work for us without rewriting our app.

**Comment by frank-dspeed** [comment]
faketop will for example 

```js
   if ( window.location !== window.parent.location )
    {
      
        // The page is in an iFrames
        document.write("The page is in an iFrame");
    } 
    else {
          
        // The page is not in an iFrame
        document.write("The page is not in an iFrame");
    }
```

**Comment by Jermolene** [comment]
> faketop will for example
> 
> ```js
>    if ( window.location !== window.parent.location )
>     {
>       
>         // The page is in an iFrames
>         document.write("The page is in an iFrame");
>     } 
>     else {
>           
>         // The page is not in an iFrame
>         document.write("The page is not in an iFrame");
>     }
> ```

Yes that's also my understanding of the current behaviour of faketop.

**Comment by frank-dspeed** [comment]
@Jermolene your right you need to rewrite your TidyWiki stuff as the whole Web will stop supporting this alert and confirm and prompt stuff. This is a Regression of the whole WWW. and NWJS will stick with the WWW standard.

**Comment by frank-dspeed** [comment]
@Jermolene if you got commercial interrest in that and need help with the migration i am familar with such complex scenarios i can put some energie into it if it is worth the effort.

**Comment by Jermolene** [comment]
> @Jermolene your right you need to rewrite your TidyWiki stuff as the whole Web will stop supporting this alert and confirm and prompt stuff. This is a Regression of the whole WWW. and NWJS will stick with the WWW standard.

Thanks @frank-dspeed as I've explained, our situation is unusual in that we're displaying existing user files which we can't rewrite.

**Comment by frank-dspeed** [comment]
@Jermolene you can always rewrite and you will rewrite them or run them in a proper context that offers alert and prompt as also confirm functions.

**Comment by frank-dspeed** [comment]
@Jermolene as last resort of compat you will for example need to parse the files before you render them.

**Comment by frank-dspeed** [comment]
there are many ways to archive your goals we would need to experiment a bit as no one at present as done that migration path but it is do able that is 100% verifyed.

**Comment by frank-dspeed** [comment]
@Jermolene https://developer.chrome.com/origintrials/#/register_trial/2541156089743802369 this should give you 6 extra month for the migration

**Comment by Jermolene** [comment]
Thanks @frank-dspeed 

> @Jermolene https://developer.chrome.com/origintrials/#/register_trial/2541156089743802369 this should give you 6 extra month for the migration

The same origin trial won't help us because we are loading the users files from `file://` URI.

> @Jermolene you can always rewrite and you will rewrite them

As I've explained, it is not feasible to rewrite all the TiddlyWiki files out there.

> or run them in a proper context that offers alert and prompt as also confirm functions.

I think you're suggesting moving to using localhost instead of `file://` URIs. I agree that that approach may be worthy of investigation, but it's a major rearchitecting of our application, and so I'd like to avoid it if we can.

> @Jermolene as last resort of compat you will for example need to parse the files before you render them.

I'm not sure if that's a serious suggestion. Parsing and mutating HTML/JS files seems a heavy price to retain functionality that we have been using for 7 years.

> there are many ways to archive your goals we would need to experiment a bit as no one at present as done that migration path but it is do able that is 100% verifyed.

I appreciate your suggestions, but none of them help us achieve our goals so far.

**Comment by Jermolene** [comment]
There is a new flag `--disable-features='SuppressDifferentOriginSubframeJSDialogs'` that can be added to our `chromium-args` to restore the old behaviour. It's working great for us now.

Many thanks to @phoenixeliot for https://github.com/Jermolene/TiddlyDesktop/pull/237 and to @frank-dspeed.
