### ISSUE TITLE
OSX - Transparency click-through broken with 0.56.0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7774]
MacOS High Sierra 10.13.6  NW.js 0.56.0-sdk (also fails on 10.14.6 Mojave)

Test app attached

Click-through doesn't work but if window is double-clicked the frame does a dance and separates into layers. A further double-click will bring the window back to normal.
Normal pre double-click:

![normal](https://user-images.githubusercontent.com/11089335/131218490-d221808d-e9b2-4e7c-87ca-9afc1a181f59.jpg)

Broken after double-click:

![broken](https://user-images.githubusercontent.com/11089335/131218497-b1b8c084-a3e0-4a33-959f-1467b44108ad.jpg)

All is OK with 0.55.0 and prior.

[TransTest-simple.zip](https://github.com/nwjs/nw.js/files/7070727/TransTest-simple.zip)

Note: has something changed with the nw context and requires 'cos half my apps won't start with 0.56.0 - I am still trying to pin it down.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
