### ISSUE TITLE
OSX - nw.require broken with 0.56.0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7775]
MacOS High Sierra 10.13.6  0.56.0-sdk (also broken on 10.14.6 Mojave)

nw.require is broken with some projects (happens a lot if main: in manifest is js file but this test app is using index.html and it occurs.) Background context logging is clear but browser/window context gives errors.
Works OK with 0.55.0 and earlier.
Problem is shown if System Information menu option is selected ( the content of this sub-window relies on node module access).

Example:

![broken](https://user-images.githubusercontent.com/11089335/131230029-91be75c7-92d5-42ea-876c-72a4c0ef5d46.jpg)

[appsrc.zip](https://github.com/nwjs/nw.js/files/7071432/appsrc.zip)

The node modules in this test app are early (prob. c. v8) and OK with 0.55.0 but not 0.56.0 - tried upgrading modules to 16.8.0 and still get the errors with 0.56.0 however the later modules break 0.55.0 which is not unexpected.

The problem seems to revolve around the nw. namespace

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
