### ISSUE TITLE
Lost local data on NWJS upgrade

### ISSUE THREAD

**Issue by ftaiolivista** [nwjs/nw.js#7778]
I have upgrade an NWJS App that was build as chrome-app with NWJS version 0.37.3 to  NWJS version 0.53.0.

All was ok except that when update the app on a MAC the new App dont find and use old app local data.

If I reinstalled the old app, the app find again old data but not new data so I think that the two version are using different local data folder, but if I check nw.App.dataPath from the applications they point to the same data folder /User/<*user*>/Library/Application Support/<*My app name*>/Default".

The app manifest ID is not changed.

What am I missing?

**Comment by ftaiolivista** [comment]
After mode checks I found that the two apps build results in two different chrome.runtime.id. 

But my manifest "key" was not changed .

**Comment by semmel** [comment]
Have you changed the `"name"` in `package.json` manifest for the upgrade?

It seems that the [unique Chrome extension id](https://stackoverflow.com/questions/21497781/how-to-change-chrome-packaged-app-id-or-why-do-we-need-key-field-in-the-manifest) aka `chrome.runtime.id` depends solely on the value of the `"name"` in `package.json`. [Setting the `"key"` in the manifest](https://developer.chrome.com/docs/extensions/mv3/manifest/key/) has no effect in NWJS. 

So even if the `--user-data-dir` is the same across app upgrades, changing `"name"` in the manifest will make your upgrade use a completely new `chrome-extension://...` origin, which cannot access existing WebStorage at the other origin.

**Comment by ftaiolivista** [comment]
Name field is present and unchanged. 
The only value changed in package.json (MYAPP.app/Contents/Resources/app.nw/package.json) is the version field that was incremented.

```
{
    "app": {
        "background": {
            "scripts": [
                "scripts/background.js"
            ]
        }
    },
    "chromium-args": "--ignore-certificate-errors",
    "default_locale": "en",
    "description": "MYAPP",
    "icons": {
        "128": "images/favicon/apple-icon-128x128.png",
        "16": "images/favicon/favicon-16x16.png"
    },
    "key": ".....herethekey",
    "manifest_version": 2,
    "name": "MYAPP",
    "permissions": [
        "<all_urls>",
        "storage",
        "browser",
        "unlimitedStorage",
        {
            "fileSystem": [
                "write",
                "retainEntries",
                "directory"
            ]
        },
        "videoCapture",
        "usb",
        {
            "usbDevices": [
                {
                    "productId": 2162,
                    "vendorId": 41320
                }
            ]
        },
        "nativeMessaging",
        "webview"
    ],
    "version": "310"
}

```

**Comment by semmel** [comment]
I don't recognise `"app"`, `"icons"` from the [NWJS manifest documentation](http://docs.nwjs.io/en/latest/References/Manifest%20Format/).

Also I have a `"main"` field with my `"index.html"` and `"manifest_version": 3`. So my tests are not 100% comparable to your configuration. 

Maybe I'll try an experiment with [the domain field `"domain"`](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#domain). I'll report here...

**Comment by semmel** [comment]
### Manifest `"domain"` sets `chrome.runtime.id`
my `package.json`

```json
{
  "domain": "de.mycompany.myapp",
  "name": "yalst",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "window": {
    "width": 800,
    "height": 800,
    "id":"hello-nwjs-test-app",
    "title": "Hello NWJS!"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "chromium-args": "--enable-experimental-web-platform-features --enable-spell-checking --experimental-fetch"
}
```
![Screenshot 2022-03-07 at 18 21 45](https://user-images.githubusercontent.com/296476/157086063-5cc2e1b9-ebbd-423f-9282-d53af14445d9.png)


If only I'd have known before! 
Don't know yet if it is worth migrating the origin for all our users from `chrome-extension://nfbjghbppdojc...hcmnlpo` to `chrome-extension://de.mycompany.myapp`

**Comment by tharatau** [comment]
Hope the issue was resolved. Please use the mailing list for discussions, thanks!

**Comment by semmel** [comment]
> … Please use the mailing list for discussions, thanks!

@tharatau 
Mails totally lack code formatting. Also referencing other issues and posting screenshots are a real pain, reactions 👍👎 not even possible, and searching is awkward.
No, but thanks.

**Comment by tharatau** [comment]
Honestly I prefer GitHub issues too but that's what Roger wants (its even mentioned in the issue template)
