### ISSUE TITLE
Ability to specify thumbnail size for DesktopCaptureMonitor

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#7779]
Is it possible to add the ability to be able to specify thumbnail size? Might have an API in Chrome as Electron supports this feature.

Thanks

**Comment by ayushmxn** [comment]
You can access most of the chrome API in your NW application. I wasn't able to find it but I may have missed it while looking over the docs. Closing this for now. Feel free to comment here if you weren't able to find it and would like this as an NW feature.
