### ISSUE TITLE
NW.js 0.56.0 not published to npm

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#7781]
issu with npm , last version is `0.55.0`
![image](https://user-images.githubusercontent.com/24865815/132812728-e15cadf2-a0b2-4f30-9ad6-10d416c47d64.png)

**Comment by TheJaredWilcurt** [comment]
Confirmed:

* https://www.npmjs.com/package/nw?activeTab=versions

**Comment by djmisterjon** [comment]
> **Confirmed:**
> 
> * https://www.npmjs.com/package/nw?activeTab=versions
> 
> **Workarounds:**
> 
> * continue using 0.55 for the time being until 0.56 is published to npm
> * Manually download 0.56
>   
>   * https://dl.nwjs.io/v0.56.0

yes this is what i did, but it looks like other people are having the same problem with some libraries !
These may just be a coincidence ? ! Or ...🙄
![image](https://user-images.githubusercontent.com/24865815/132940310-ea7cc6bc-1f9e-4292-b44a-b202a3c2be26.png)

**Comment by djmisterjon** [comment]
![image](https://user-images.githubusercontent.com/24865815/133038795-94895527-de2b-4701-aa34-08a749ce84bb.png)
fixed thanks
