### ISSUE TITLE
nw did not work on second js with new window

### ISSUE THREAD

**Issue by jiyeme** [nwjs/nw.js#7784]
NWJS Version : 0.56.0
Operating System : Windows 10

### Expected behavior

window & nw can work normally;

### Actual behavior
Error:
> Cannot find module 'nw.gui'
> nw is not defined
> window is not defined

### How to reproduce

> English is not my native language.

```
helloworld:.
        │  a.js
        │  b.js
        │  c.js
        │  index.html
        │  index2.html
        │  package.json
```

`index.html`
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<p>Page Index</p>

<script>
    nw.Window.open("./index2.html", {
        new_instance: true
    })
</script>
</body>
</html>
```

`index2.html`
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<p>Page index2</p>

<script>
    const win = nw.Window.get();
    console.log(win)
    win.title = "index2"
    console.log(nw)
</script>  
<script src="./a.js"></script>
</body>
</html>
```

`a.js`
```javascript
console.log('a', nw)
nw.Window.get().title = "a"
require('./b.js')
// module.exports = {};
```

`b.js`
```javascript
console.log('b - global', global)
// console.log('b - nw', require("nw.gui")) // Cannot find module 'nw.gui'
// console.log('b - nw', nw)   // nw is not defined
// console.log('b - window', window)   // window is not defined
nw.Window.get().title = "b"
require('./c.js')
module.exports = {};
```

`c.js`
```javascript
console.log('c', nw)
nw.Window.get().title = "c"
module.exports = {};
```

`package.json`
```json
{
    "name": "helloworld",
    "main": "index2.html",
    "productName": "helloworld",
    "appname": "helloworld",
    "version": "1.0",
    "node-remote": "<all_urls>"
}
```

1. run it, everything is OK.   The title is changed to `c`.
2. change the value of `main` in `package.json` to `index.html`.
3. run it.
4. the title of second window is changed to `a` but not `c`.
5. open the devtool
6. You can see `nw is not defined`.

if run `index2.html` directly, `nw` can work normally on `a.js`, `b.js` and `c.js`.
but if run `index.html` and jump to `index2.html`, `nw` was just worked on `a.js`.

**Comment by Blatman** [comment]
Try 0.56.1 as there was a fix for a require issue (#7775) in late 0.56.0 - at least for Mac, maybe it also works for Win.

**Comment by jiyeme** [comment]
> 
> 
> Try 0.56.1 as there was a fix for a require issue (#7775) in late 0.56.0 - at least for Mac, maybe it also works for Win.

Thanks for your reply.
I have tried it, but it didn't work.

**Comment by Blatman** [comment]
Yup, sure enough - I tried it on Mac and it fails as you say even with 0.56.1 - looks like the fix was only a partial maybe.

**Comment by jiyeme** [comment]
Add ` --mixed-context` flag can solve this problem.
