### ISSUE TITLE
nw57 - Download versions incorrect

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7785]
Just in case nobody noticed the latest builds for nw57 (Chromium 94) ( http://dl.nwjs.io/live-build/) are still labelled as 0.56.1 as well as the commit hash being invalid.
Cheers.
<img width="255" alt="splash" src="https://user-images.githubusercontent.com/11089335/134778223-f1a598ff-79c1-4f9c-9177-8517361c9460.png">

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
