### ISSUE TITLE
The windows 7 operating system cannot run

### ISSUE THREAD

**Issue by Thunder7991** [nwjs/nw.js#7787]
NWJS Version :0.56
Operating System : win7

The windows 7 operating system cannot run. Clicking the. EXE file will not pop up the interface, but it can run in win10.

**Comment by rogerwang** [comment]
Could you please provide a sample to reproduce or the [crash dump](http://docs.nwjs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/) file?

**Comment by rogerwang** [comment]
see https://github.com/nwjs/nw.js/issues/7780#issuecomment-931826205

**Comment by panther7** [comment]
Hi @rogerwang, still does not fixed. We tried on laptop with Windows 7.

**Comment by rogerwang** [comment]
Did you see blank window or no window?

**Comment by rogerwang** [comment]
try install Microsoft VC redistributable. or diagnose with dependency
walker on node.dll.

**Comment by panther7** [comment]
Installed latest VC (https://docs.microsoft.com/cs-CZ/cpp/windows/latest-supported-vc-redist), laptop reboot, still no window.

**Comment by panther7** [comment]
Yes, works after install VC Redist for x86
