### ISSUE TITLE
0.57.0: debug log messages from Chromium 94 (Bluetooth availability / default browser status)

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#7789]
NWJS Version : 0.57.0
Operating System : Linux (irrelevant)

### Issue

After the update to Chromium 94 in 0.57.0, the following error log messages do always get printed to stderr:

```
[116925:116939:0929/170615.406593:ERROR:chrome_browser_main_extra_parts_metrics.cc(228)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[116925:116939:0929/170615.406633:ERROR:chrome_browser_main_extra_parts_metrics.cc(231)] crbug.com/1216328: Checking Bluetooth availability ended.
[116925:116939:0929/170615.406644:ERROR:chrome_browser_main_extra_parts_metrics.cc(234)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[116925:116939:0929/170615.415654:ERROR:chrome_browser_main_extra_parts_metrics.cc(238)] crbug.com/1216328: Checking default browser status ended.
```

They were added via this commit in upstream Chromium for debugging certain flaky tests:
https://chromium.googlesource.com/chromium/src/+/dc4d407c573675344fa03d5d1830723a88a04a2a%5E%21/#F1
https://bugs.chromium.org/p/chromium/issues/detail?id=1216328

I'm not sure why this hasn't been removed yet or why this is included in production builds when the reason it was added is flaky tests.

Git blame in NW.js's Chromium repo:
https://github.com/nwjs/chromium.src/blame/nw57/chrome/browser/metrics/chrome_browser_main_extra_parts_metrics.cc#L227-L238

The log messages are not a real issue because they are just checking the BT availability or default browser status, but every end user of an NW.js application will see this, and these messages should therefore be removed/silenced, because they are confusing.

Adding `--no-default-browser-check` to `chromium-args` unfortunately didn't make the default browser log message go away because it's not used in the `shell_integration::GetDefaultBrowser` method itself.

**Comment by yan00s** [comment]
did you solve the problem?

**Comment by bastimeyer** [comment]
Upstream has recently changed the log messages, and the nw59 branch has the updated messages included:
https://github.com/nwjs/chromium.src/blob/nw59/chrome/browser/metrics/chrome_browser_main_extra_parts_metrics.cc#L225-L238

I don't think though that they should be included in NW.js, because it's not meant to be used as the system's default browser, so all this logging does is confuse end users, which isn't great for app developers.

The log messages will be removed from Chromium eventually as they are meant for debugging a race condition according to their bugtracker. So it's up to NW.js to temporarily remove them now and introduce a merge conflict later on (which should be fairly easy to resolve).

**Comment by bastimeyer** [comment]
The default web browser log messages are now disabled on Linux in the latest release:
https://github.com/nwjs/chromium.src/blame/nw60/chrome/browser/metrics/chrome_browser_main_extra_parts_metrics.cc#L234-L242

Upstream commit:
https://github.com/chromium/chromium/commit/df6c9e0a0802cf1e5620c5c5c711dd5231da7cc5

This is fine for me, as the confusing message will most likely never be seen by users on Windows and macOS, and the bluetooth log message can be ignored.

Feel free to close.
