### ISSUE TITLE
I use chinese OS but the window.navigator.language output "en-US"

### ISSUE THREAD

**Issue by q84629462** [nwjs/nw.js#779]
Now what can i do to get the user os language
I searched for a long time, did not find a way

Content on this page does not help me
https://github.com/rogerwang/node-webkit/issues/24

**Comment by robaweb** [comment]
Have the same issue!
Windows 8.1 nw 0.11.6, after building with node-webkit-builder, packing into msi file and installing navigator.language and process.env.LANG are empty
But in develop mode and builded with node-webkit-builder without packing in msi navigator.language return correct language.

**Comment by watdafox** [comment]
Easy fix: take the folder "locales" generated by NW 9 or present in the zip packages of NW11 & 12. Copy it next to your node-webkit executable. Tadaa.

The issue apparently comes from NW generating an empty `locales` folder at start instead of filling it with lang.pak files

**Comment by rogerwang** [comment]
'locales' folder should be shipped with your application.

**Comment by pouu69** [comment]
where is locales files?
