### ISSUE TITLE
win.zoomLevel = <int> makes nwjs crash

### ISSUE THREAD

**Issue by vankasteelj** [nwjs/nw.js#7792]
NWJS Version : 0.57.0 (sdk)
Operating System : Windows 10 x64

`win.zoomLevel`  seems to be broken, I've just updated from 0.49.x to 0.57.0 and the 'integer' values like 0, 1, 2 make the window crash. Alhtough by default, the zoomLevel value is `0`, going to something else and back to 0 makes it crash as well. 

Workaround: currently, I can make the window not crash by using the values 0.99 instead of 1, and 0.01 instead of 0.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
