### ISSUE TITLE
Very slow first launch on MacOS (20-30s), not usable :/

### ISSUE THREAD

**Issue by josh83abc** [nwjs/nw.js#7795]
Hello! 
The first time I launch a blank NWJS app on MacOS, nothing happen for around 20-30s and it looks like the app is frozen. See the video : https://you.dj/nwjs_slow.mov
The second load is instant.
What is happening during the first load? 
This can't be usable for now because too confusing for the users (I got tons of emails on the support stating the app doesn't start on macos).
Thanks,
Erik

**Comment by rogerwang** [comment]
I saw something similar. What's happening here is macOS scanning the whole application files to check its signature.

**Comment by kakysha** [comment]
This is Rosetta doing its thing https://en.wikipedia.org/wiki/Rosetta_(software)

**Comment by josh83abc** [comment]
Just for info, I did the full release process of my NWJS app : signing / notarization / macstore upload and no difference, still 20 seconds loading time :/

Thanks Kakysha for the info, it might be Rosetta, I am not sure how to check... Maybe one day NWJS will be for M1 :)))) ?
