### ISSUE TITLE
NWJS 0.57.1 & 0.56.0 does not re-open a window after a Simulate browser restart (or Reload app).

### ISSUE THREAD

**Issue by garfield69** [nwjs/nw.js#7798]
NWJS Version : 0.57.1 and 0.56.1 and .056.0
Operating System : Windows10 and Ubuntu21

### Expected behaviour

When a user right clicks inside my app's window and selects either the `Simulate Browser Restart`, or the `Reload app` from that menu, NWJS should open the app's window again after performing the restart/reload. 

### Actual behaviour

The window is closed and the nwjs tasks are left running. Only way out appears to use the task manager to kill all the nwjs tasks.

### How to reproduce

you can test this for your self by creating the hello-world test as described in your documentation https://github.com/nwjs/nw.js/wiki/Getting-Started-with-nw.js and performing the actions as described in the Expected Behaviour section.

Notes: If I revert to NWJS 0.55.0 then the app behaves as expected.
Also MacOSx  0.57.1 works as expected.

**Comment by zzador** [comment]
Same here. Both functions not working. Makes Developement nearly impossible. Restarting NWjs after every code-change ist NOT AN OPTION.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
