### ISSUE TITLE
Process not found when compiling latest version

### ISSUE THREAD

**Issue by KanomiDim** [nwjs/nw.js#7799]
NWJS Version : 57.2
Operating System : Windows 10

Hey!

I've tried to compile the latest version of nwjs, and went through the documentation, just as i usually do (once in a while i'm upgrading to the newest version)

The last build i made successfully on the same environment was NWJS 48.2, and it worked out just fine.

Recently, I took 57.2, and i encountered the following issue:

![process_not_found_nwjs572_issue](https://user-images.githubusercontent.com/68009729/137616554-b5c500c3-f3a6-402d-a629-c32367951254.png)

There are lines of "ERROR: The process "#" not found"

Did i forget something? is there anything different?

Thanks,
Dima.

**Comment by ayushmxn** [comment]
What OS are you on?
