### ISSUE TITLE
nw.exe version 0.57.1 crashing on windows 10 due to error "Failed to load node library (error: 126)"

### ISSUE THREAD

**Issue by anurag-2911** [nwjs/nw.js#7801]
======== TEMPLATE BUG FORM ========

NWJS Version : 0.57.1
Operating System :Windows 10 , Version 20 H2 (OS build 19042,1288)

### Expected behavior
I built my company application on nw.js version 0.57.1 and tested it on few machines, it worked without any error on few versions but on some, it crashed.

When I checked the chrome debug logs, it has an error:

[9720:8352:1017/223913.414:FATAL:nw_content_renderer_hooks.cc(53)] Failed to load node library (error: 126)
Backtrace:
	GetMainTargetServices [0x00007FFA34EE7C52+1014482]
	GetMainTargetServices [0x00007FFA34E648A2+476962]
	GetMainTargetServices [0x00007FFA34E764E0+549728]
	GetMainTargetServices [0x00007FFA358C21CA+11345994]
	GetMainTargetServices [0x00007FFA358B4180+11288576]
	cppgc::internal::BaseSpace::RemoveAllPages [0x00007FFA336EE118+1202024]
	cppgc::internal::BaseSpace::RemoveAllPages [0x00007FFA336ECD0F+1196895]
	cppgc::internal::BaseSpace::RemoveAllPages [0x00007FFA336ED435+1198725]
	ChromeMain [0x00007FFA31A3119E+414]
	GetPakFileHashes [0x00007FF7ACF02601+5633]
	GetPakFileHashes [0x00007FF7ACF019AE+2478]
	GetHandleVerifier [0x00007FF7AD044532+867426]
	BaseThreadInitThunk [0x00007FFA979D7034+20]
	RtlUserThreadStart [0x00007FFA98E42651+33]

Crash report:

[reports.zip](https://github.com/nwjs/nw.js/files/7361985/reports.zip)

**Comment by anurag2911** [comment]
I am attaching my application also, you can install and it will create a folder Novell/ZenWorks/zapp , in that zapp.exe (nw.exe renamed as zapp.exe) is the application you need to launch.

https://www.dropbox.com/s/36dgy9683wjwaso/novell-zenworks-application-20.2.0.991.x86_64.zip?dl=0
