### ISSUE TITLE
Official documentation needs an update

### ISSUE THREAD

**Issue by dallascao** [nwjs/nw.js#7802]
When compiling to binary, the official doc here
https://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

The code is 

`nw.Window.get().evalNWBin(frame, 'binary.bin');`

However, it seems this stops working in later versions. I make thing work by using:

`require('nw.gui').Window.get().evalNWBin(null, 'binary.bin');`

I am not sure if the official doc needs an update.

**Comment by baconbrad** [comment]
With `nw` it is implied that `var nw = require('nw.gui');` was referenced previously or the `nw` object is already available in the context. This is typical of open source documentation to avoid a lot of redundant boiler plate code all over the docs and discourage people from repeated unnecessary requires if they copy and paste example code. [Additionally `nw.gui` is the legacy way of requiring the API.](https://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/#example-2-using-nwjs-apis) It returns the same `nw` object. If not already available there is a contextual issue with your app.
