### ISSUE TITLE
reCaptcha crashes nwjs

### ISSUE THREAD

**Issue by kr4ssi** [nwjs/nw.js#7810]
======== TEMPLATE BUG FORM ========

NWJS Version :
20211206-060130/889179c6a/v0.60.0
20211124-004828/e18eda53c/v0.59.0
0.58.0 SDK
0.57.0 SDK
0.56.0 SDK
0.55.0 SDK

WORKS:
0.54.1 SDK

Operating System : Linux Mint 20.2

### Expected behavior

Show reCaptcha-tiles

### Actual behavior

crashes

### How to reproduce

`$ ./nw`
F12
`window.open('https://www.google.com/recaptcha/api2/demo')`
click checkbox

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
