### ISSUE TITLE
Reloading a new instance child window causes crash

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#7813]
**Steps to reproduce:**

1. Create a new instance child window
1. Reload the child (more than once)

**Expected:** Window reloads
**Actual:** Crashes with `STATUS_ACCESS_VIOLATION`

Reported by @sdurham on Gitter. I was able to reproduce this.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Parent</title>
  </head>
  <body>
    <button onclick="nw.Window.open('child.html', { new_instance: true })">New Instance</button>
  </body>
</html>
```
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Child</title>
  </head>
  <body>
    <button onclick="nw.Window.get().reload()">Reload</button>
    <button onclick="nw.Window.get().reloadIgnoringCache()">Reload Ignoring Cache</button>
    <button onclick="location.reload()">Location</button>
  </body>
</html>
```

* **[nw7813.zip](https://github.com/nwjs/nw.js/files/7645982/nw7813.zip)** <---------------------------

Version | win.reload    | win.reloadIgnoringCache | location.reload
:--     | :--           | :--                     | :-
0.33.3  | ✔️           | ✔️                      | ✔️
0.33.4  | ❌           | ❌                      | ❌
0.58.0  | ❌           | ❌                      | ❌

* https://github.com/nwjs/nw.js/compare/nw-v0.33.3...nw-v0.33.4

**Comment by sdurham** [comment]
Wow thanks for following up and filing this!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by TheJaredWilcurt** [comment]
Tested with:

Version | win.reload    | win.reloadIgnoringCache | location.reload
:--     | :--           | :--                     | :-
0.33.3  | ✔️           | ✔️                      | ✔️
[0.60.0-win-32-sdk](http://dl.nwjs.io/live-build/nw60/20211206-015246/75bc43584/v0.60.0/nwjs-sdk-v0.60.0-win-ia32.zip)|❌|❌|❌
[0.60.0-win-64-sdk](http://dl.nwjs.io/live-build/nw60/20211206-010521/75bc43584/v0.60.0/nwjs-sdk-v0.60.0-win-x64.zip)|❌|❌|❌
[0.60.0-win-32](http://dl.nwjs.io/live-build/nw60/20211206-035629/75bc43584/v0.60.0/nwjs-v0.60.0-win-ia32.zip) | ❌ | ❌ | ❌
[0.60.0-win-64](http://dl.nwjs.io/live-build/nw60/20211206-051517/889179c6a/v0.60.0/nwjs-v0.60.0-win-x64.zip) | ❌ | ❌ | ❌

Will check again on a future release/build.

**Comment by TheJaredWilcurt** [comment]
Verified that the issue no longer occurs in the latest official release 0.59.1.

Tested on Win 10 with SDK flavor.
