### ISSUE TITLE
MacOS 0.60.0 builds crash on launch with High Sierra

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7815]
MacOS 10.13.6 High Sierra  NWjs 0.60.0-sdk and normal

Crash on launch occurs (icons flashes for a moment in dock).
Works OK with Mojave (10.14).
Info.plist indicates that Chromium/NWjs should be good for 10.11 or greater.

Image shows 2 logs produced -

<img width="1018" alt="crashlogs" src="https://user-images.githubusercontent.com/11089335/145016429-6018ada9-f85b-438d-a353-8d52c2dda59a.png">

This happens if the NWjs binary is started (double-clicked) anywhere (eg: standalone on desktop or within app folder with app files).

nwjs profile folder deleted and newly created one still fails. 0.59 builds work OK.

**Comment by rogerwang** [comment]
Could you provide a sample app? It works for me here on High Sierra.

**Comment by Blatman** [comment]
Thanks for looking at that Roger - I redownloaded and ran the binary (cleared profile) and still failed (doesn't need app) however I tried the same binary on a 10.11 El Capitan install (different machine) and it started OK so for some reason  my 10.13 build doesn't like v0.60 - I will have to try and figure it out.

**Comment by Blatman** [comment]
@rogerwang -  I will close this since I just tried the latest build posted (1/4/22) and it launches OK so the earlier build must have had some anomaly in it. (note: tried earlier build again and still failed)

**Comment by rogerwang** [comment]
Thanks.
