### ISSUE TITLE
website might have certificate issues

### ISSUE THREAD

**Issue by peq42** [nwjs/nw.js#7816]
I'll post this without any formatting but, nwjs.io, the website, may have a certificate issue or similar, as chrome(latest version, 96) pointed it as not safe last time I tried to visit to check for a new version of NW.js

**Comment by CareyJWilliams** [comment]
I've had occasional issues when downloading binaries as well recently (I hadn't connected the dots, but seeing this issue makes me wonder).

**Comment by TheJaredWilcurt** [comment]
Confirmed that the cert expired:

![cert](https://user-images.githubusercontent.com/4629794/145238443-687d05b9-d741-4fb3-8d2c-84be56fc37d2.png)

@rogerwang

**Comment by rogerwang** [comment]
It works for me. What IP does it resolve there?

**Comment by AlexIII** [comment]
I too have no problems with the cert

![image](https://user-images.githubusercontent.com/10047074/145243498-280ce570-6f25-4319-aab5-2940bb744933.png)

**Comment by TheJaredWilcurt** [comment]
Correction, I'm not getting the issue anymore, I think my computers just had something cached.

![encrypt](https://user-images.githubusercontent.com/4629794/145243725-8e07f995-0a14-4f13-abeb-ed1365e8f90d.png)

```
ping nwjs.io

Pinging nwjs.io [45.79.75.204] with 32 bytes of data:
Reply from 45.79.75.204: bytes=32 time=71ms TTL=52
Reply from 45.79.75.204: bytes=32 time=75ms TTL=52
Reply from 45.79.75.204: bytes=32 time=75ms TTL=52
Reply from 45.79.75.204: bytes=32 time=80ms TTL=52

Ping statistics for 45.79.75.204:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 71ms, Maximum = 80ms, Average = 75ms
```

**Comment by hthetiot** [comment]
Certificate issue confirmed, failed to load on Android and MacOs chrome.

SSL test results on second certificate
> Wed, 01 Dec 2021 17:50:22 UTC (expired 6 days, 23 hours ago)   EXPIRED

Source: https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=nwjs.io

**Comment by rogerwang** [comment]
Thanks for the link. After restarting apache, the report is good now...

**Comment by TheJaredWilcurt** [comment]
The ssllabs link shows 2022 and 2025 certs now. 👍
