### ISSUE TITLE
Shaders disk cache

### ISSUE THREAD

**Issue by ncannasse** [nwjs/nw.js#7821]
Hi,

we're running a large NWJS middleware App using WebGL2 (https://github.com/heapsio/hide) and when opening a 3D scene, most of the CPU time is spent in GLSL shader compilation.

Further opening of the same scene is a lot faster due to compiled shaders being cached, but when restarting the app the cache is lost. Is there some way to enable multiple-runs shader cache ?

There seems to exists a shader disk cache feature in chromium but I haven't been able to find more information on that (https://source.chromium.org/chromium/chromium/src/+/main:gpu/ipc/host/shader_disk_cache.h)

Alternatively, we would like to switch from Angle to OpenGL for the underlying engine as OpenGL offers faster shader compilation.

Any help would be greatly appreciated.

**Comment by djmisterjon** [comment]
> 

you can probably found a way to keep data persistance and shaders by add `--user-data-dir='./myfolder'` and maybe some task
![image](https://user-images.githubusercontent.com/24865815/146426371-3b685a03-2129-4aad-91a5-48c65e86a310.png)

**Comment by tharatau** [comment]
Hope the issue was resolved. Please use the mailing list for questions, thanks!
