### ISSUE TITLE
Chromium Download in progress dialog

### ISSUE THREAD

**Issue by JohnLego** [nwjs/nw.js#7822]
![bug](https://user-images.githubusercontent.com/76930753/146579408-d81477a4-a4f9-4dd3-8782-6ff72a72f9e1.png)
I would like to report a bug in NW.js 0.59.0 Normal Build.
When downloading a file, if it is not complete, the Download in progress dialog pops up, when clicking continue downloading, it attempts to open the chrome://downloads page but says this site can't be reached. It is so strange to see that NW.js is just Chromium Browser in a window form with heavy resemblance since some parts look and act like Google Chrome. Is there any way to override this dialog with something else or use e.preventDefault();

**Comment by peq42** [comment]
> . It is so strange to see that NW.js is just Chromium Browser in a window form with heavy resemblance since some parts look and act like Google Chrome. 
"NW.js (previously known as node-webkit) lets you call all Node.js modules directly from **DOM** and enables a new way of writing applications with all Web technologies."

NW.js mixes chromium and node.js, thus making it easier to make interfaces for programs and/or games, while being more powerful than a pure web browser, so... yea its technically part chromium. If you look at the release notes, you can always see an update for chromium

**Comment by ayushmxn** [comment]
Could you please provide a sample repro? And if you've resolved your problem, could you post your solution/workaround here so people who come across a similar problem can benefit? I'm closing this for now.
