### ISSUE TITLE
ERROR:registration_protocol_win.cc

### ISSUE THREAD

**Issue by lutaoTommy** [nwjs/nw.js#7825]
When  I   try to run  nw.exe
NO  GUI   appears，but  runs in the background
The debug  info:  [1221/154540.802:ERROR:registration_protocol_win.cc(102)] CreateFile: 系统找不到指定的文件。 (0x2)

NWJS Version :  nwjs-v0.58.0-win-ia32
Operating System :  Win10 x64

**Comment by sysrage** [comment]
More detail about your environment is needed. The 32-bit version of NW.js 0.58.0 runs without issue in my Windows 10 64-bit (10.0.19044.1415) environment. 

The translated error message is "The system can not find the file specified", which indicates you have a "corrupt" installation of NW.js. Try downloading and extracting a new copy.

**Comment by ayushmxn** [comment]
@lutaoTommy closed since issue is non-actionable. If you provide more info, I'd be happy to reopen it. If you've resolved your problem, then that's great!
