### ISSUE TITLE
nwjs 0.59.1 macOS - crash on Window native api usage (setBadgeLabel, setProgressBar, requestAttention) - RESULT_CODE_KILLED_BAD_MESSAGE

### ISSUE THREAD

**Issue by AndryBray** [nwjs/nw.js#7826]
there is some issue executing setBadgeLabel / setProgressBar / requestAttention **only with macOS** (10.14.x and 12.x)

STEP TO REPRODUCE:
1. open last nwjs
2. go to dev tools / console
3. run **nw.Window.get().setBadgeLabel("1")** 

Chrome crashes with **RESULT_CODE_KILLED_BAD_MESSAGE** error

The same with 
```
nw.Window.get().setProgressBar(50)
```

It works well on Windows instead.

**Comment by djmisterjon** [comment]
work fine for me !
![image](https://user-images.githubusercontent.com/24865815/147848422-44111cfd-d022-475e-89ed-8171907537c6.png)
```json
{
    "node": "17.1.0",
    "v8": "9.6.180.12",
    "uv": "1.42.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.18.1",
    "modules": "102",
    "nghttp2": "1.45.1",
    "napi": "8",
    "llhttp": "6.0.4",
    "openssl": "3.0.0+quic",
    "icu": "69.1",
    "unicode": "13.0",
    "nw": "0.59.0",
    "node-webkit": "0.59.0",
    "nw-commit-id": "0033ef9-e8487e4-25576af-e70a543",
    "nw-flavor": "sdk",
    "chromium": "96.0.4664.55"
}
```

**Comment by AndryBray** [comment]
hi @rogerwang 
any idea about this?
thanks

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
