### ISSUE TITLE
Cannot open some sites using window.open()

### ISSUE THREAD

**Issue by FahadQurashi49** [nwjs/nw.js#7828]
NWJS Version : 0.59.1
Operating System : macOS Catilina

### Expected behavior

should open website https://pubs.acs.org/search/advanced with window.open()

### Actual behavior

App crashed with window showing "Can't open this page":
![image](https://user-images.githubusercontent.com/14121797/148200604-cca690de-2462-4458-af94-a13f84b8c426.png)

### How to reproduce
open website https://pubs.acs.org/search/advanced with window.open(),
to reproduce run this sample code:

index.html:
```
<html>
    <head>
        <title>
            test nw
        </title>
    </head>
    <body>
        <div>test nw: </div>
        <script>
            nw.Window.open("https://pubs.acs.org/search/advanced", {}, (eWin) => {
                eWin.showDevTools();
                debugger;
                console.log(eWin); });
        </script>
    </body>
</html>
``` 

package.json:
```
{
  "name": "nw-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
Since the page crash I cannot open the devTools, this page opens in chrome browser. Sample application zip file is attached also dump file is also attached:

[nw-test.zip](https://github.com/nwjs/nw.js/files/7814111/nw-test.zip)
[dump.zip](https://github.com/nwjs/nw.js/files/7814132/dump.zip)

**Comment by UtterDonkey** [comment]
I'm having the same issue with https://pixelbulb.online/login-API
Is your site running wordpress?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by cdog** [comment]
Please see: https://github.com/nwjs/nw.js/issues/7736.

**Comment by pd-l2ork** [comment]
@rogerwang is there a way to circumvent this issue in older versions? As you may already know, in pd-l2ork (my project) newer versions are significantly slower, while older (currently 0.28.3) suffer from this bug. Or, would it be possible to backport this to 0.28.3?
