### ISSUE TITLE
How to force show system popup of camera/microphone permission?

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7832]
If I run code `navigator.mediaDevices.getUserMedia({audio:true,video:true}).then(...)` for the first time, user will get system popup like this:

![Access microphone](https://user-images.githubusercontent.com/16304454/109384175-138c8500-78fc-11eb-914b-eb258165429d.png)

After clicking on button, user's choice somewhere and somehow is stored. And it is impossible to show this popup again in case user have changed his mind. How can I force show this popup again?

**Comment by semmel** [comment]
You could try the [`chrome.Settings` API](https://developer.chrome.com/docs/extensions/reference/contentSettings/).

```javascript
// to set
chrome.contentSettings.microphone.set({
   primaryPattern:"https://*", 
   scope: "regular", 
   setting: "allow" // set to "ask" to trigger the native permission prompt again
});
// to query the current state
chrome.contentSettings.microphone.get(
   {primaryUrl:"https://*"}, 
   ({setting}) => console.log(setting)
);
// or
navigator.permissions.query({name: "microphone"})
.then(({state}) => { console.log(state); }
```

**Comment by Sunvas** [comment]
Thank you! It works.

**Comment by pd-l2ork** [comment]
> You could try the [`chrome.Settings` API](https://developer.chrome.com/docs/extensions/reference/contentSettings/).
> 
> ```js
> // to set
> chrome.contentSettings.microphone.set({
>    primaryPattern:"https://webcammictest.com/*", 
>    scope: "regular", 
>    setting: "allow" // set to "ask" to trigger the native permission prompt again
> });
> // to query the current state
> chrome.contentSettings.microphone.get(
>    {primaryUrl:"https://webcammictest.com/*"}, 
>    ({setting}) => console.log(setting)
> );
> // or
> navigator.permissions.query({name: "microphone"})
> .then(({state}) => { console.log(state); }
> ```

@semmel How would you do this for an app that runs locally and does not access internet/external webpage? I have an app where nw.js serves as a front-end editor over a network socket, asking chromium to use proxy 127.0.0.1. However, the backend (coded in C) is the one that seeks permission to microphone and camera and sends over the network various js instructions for drawing/relocating visual content, etc. With a recent upgrade of OSX, the OS stupidly ignores requests to allow access to mic and camera using getUserMedia, so even though I indicate that in the code, it never asks for permission and therefore fails to access microphone and camera. In the past, on OSX it was the main app that needed the OS permission to access the mic and camera, which would then transfer onto child processes, as well. This still works if I open the app via terminal (in which Terminal seeks permission to access mic/camera). I am hoping that the approach you are proposing may fix it, although I am not holding my breath... OSX has really gotten terrible to develop for...

**Comment by semmel** [comment]
@pd-l2ork Isn't there a kind of manifest file for mac OS apps as well – I remember the `.plist` format – in which you list the app's device requirements as well?

I've never captured the mic on mac OS natively – if that's what you're asking. Sorry.

**Comment by pd-l2ork** [comment]
So, I finally figured out how to fix this. Manifest wasn't enough. I also had to sign the app. Information on the internet about this, including OSX developer resources is practically non-existent. Try the latest version available on the https://l2ork.music.vt.edu page. It works over here just fine on Mojave and Big Sur.
