### ISSUE TITLE
Disable rounded corners on Windows 11

### ISSUE THREAD

**Issue by vlad-solomon** [nwjs/nw.js#7838]
I don't really mind the rounded corners on the windowed versions of the build, but even when  I specify in the package.json that fullscreen should be set to true, I can see the rounded corners.

Is there any way they would be disabled, or am I missing a really easy fix?

**Comment by sysrage** [comment]
Take it up with Microsoft. NW.js doesn't have control over window decorations. If you don't like the look, you can use a frameless window and build your own borders.

**Comment by vlad-solomon** [comment]
@sysrage That's no problem, I don't mind doing my own borders. I just asked to be sure I wasn't missing anything. Thanks for being passive aggressive I guess?

**Comment by vlad-solomon** [comment]
For anyone wondering, or having the same problem, this is easily fixed by taking advantage on the Fullscreen API.
```js
document.addEventListener("DOMContentLoaded", () => {
	window.addEventListener("fullscreenerror", (e) => console.error("Fullscreen error: ", e));
	document.documentElement.requestFullscreen();
});
```

This simple listener turns on fullscreen right as the DOM loads, so modify that in any way you'd like to turn on fullscreen at any other moment.

**Comment by TheJaredWilcurt** [comment]
**Frameless example:**

* https://github.com/nwutils/frameless-example

More NW.js examples and community stuff at https://nwutils.io

**Comment by jankreimeier** [comment]
The frame styling can actually be disabled by adding the following chrome flag:

`"chromium-args": "--disable-dwm-composition"`

Source:
- [NWjs - chromium-args](https://nwjs.readthedocs.io/en/latest/References/Manifest%20Format/#chromium-args).
- [Chromium - command line switches](https://peter.sh/experiments/chromium-command-line-switches/#disable-dwm-composition)

Disabling this feature results in frameless windows without any rounded corners (as we used it on previous windows version without the flag).

**Comment by vlad-solomon** [comment]
This is exactly what I wanted. Thank you very much
