### ISSUE TITLE
nw.js version v0.61.0 pings to google periodically.

### ISSUE THREAD

**Issue by common-tasks** [nwjs/nw.js#7839]
NWJS Version :v0.61.0
Operating System: Windows 10

When I built my application and launched nw.exe enabling chromium logs then I can see it periodically logs the following :
[7920:4068:0212/213034.163:VERBOSE1:network_delegate.cc(34)] NetworkDelegate::NotifyBeforeURLRequest: https://optimizationguide-pa.googleapis.com/v1:GetModels?key=dummytoken

For example : nw.exe --enable-logging --v=1.
Go to %localappdata%\AppName\User Data and check chrome_debug.log file
[chrome_debug.log](https://github.com/nwjs/nw.js/files/8053951/chrome_debug.log)

Our customers do not want the application to ping google periodically, Please suggest any command-line switch or nw.js version where this issue is not present.

**Comment by ayushmxn** [comment]
@common-tasks the discussion in #5865 may be helpful. Closing this since it's being tracked there.
