### ISSUE TITLE
Having some trouble building from tags

### ISSUE THREAD

**Issue by corwin-of-amber** [nwjs/nw.js#7840]
NWJS Version : 0.61.0
Operating System : macOS 12

### Expected behavior

I want to build NWjs via a release tag, e.g. nw-v0.61.0. So I would expect to be able to use the tag where the branch name appears in [the build instructions](https://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/).

### Actual behavior

Only https://github.com/nwjs/nw.js actually has the release tags, so this approach clearly does not apply to the other repos. I tried using the branch name in Chromium, node, and v8, and only use the tag for nw.js. But the branch has moved on since tagging, I am getting millions of build errors, similar to the ones that I saw in some recent build log: http://buildbot-master.nwjs.io:8010/builders/nw61_sdk_mac64/builds/0

That build error was resolved by adjusting the revision of Chromium source in the DEPS, so I only assume that my errors also stem from a version mismatch.

### How to reproduce

Following the instructions as described.

**Comment by corwin-of-amber** [comment]
Actually, I was talking silly before — the errors in the attached log are in fact warnings and they are non-fatal. In fact if I let the build continue past them I do get a built `nwjs.app`; so perhaps it is just the case that the Chromium build version (in this case, 98.0.4758.82) should not change within the same minor revision of NW.js, in which case building the respective branch tip is always correct?

**Comment by rogerwang** [comment]
The `DEPS` file in the nw.js repo controls the commit used to build for all the other repos.

**Comment by corwin-of-amber** [comment]
Thanks! I noticed DEPS but I have very little understanding of the inner workings of depot tools. How can a DEPS file in an inner directory, `content/nw`, affect the commit used by the Chromium root..? Anyway, as long as it works, thumbs up 👍

**Comment by rogerwang** [comment]
The build instructions need to be updated. The repos are synced by https://github.com/nwjs/nw.js/blob/nw61/tools/sync.py now.
