### ISSUE TITLE
Is NWJS compatible to Chrome Extensions Manifest V3?

### ISSUE THREAD

**Issue by semmel** [nwjs/nw.js#7841]
NWJS applications using [V3 incompatible API](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/)  might break when updated in 2023.

### Expected behavior

With the [Manifest V2 deadline in summer 2023](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/), NWJS should migrate slowly to [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/).

### Actual behavior

NWJS supports all `chrome.*` V2 API from the [Chrome Extensions](http://docs.nwjs.io/en/latest/References/Chrome%20Extension%20APIs/). This works great. 

### How to reproduce

NWJS Version : 0.61.0
Operating System : mac OS

Add `"manifest_version": 3,` to `package.json`, to make NWJS support Chrome Extensions V3.

Is there any risk in putting NWJS 0.61.0 into V3 mode? 
Can adding that line break anything internally in NWJS?
Does NWJS demand V2 or is it already compatible with V3?

**Comment by Sunvas** [comment]
Manifest V3 is against remotely hosted code, against all anonymous functions and evals. Are you sure you want to ban all this?

**Comment by semmel** [comment]
I don't know if there is a choice. As I understand, from Summer 2023 Chrome will terminate V2. It's nice to prepare for that event by adopting V3 now. 

I don't care about `eval` which many regard as dangerous. What you mean with "anonymous functions" I am not so sure. Certainly not lambdas `() => {}`?

**Comment by Sunvas** [comment]
> I don't care about `eval` which many regard as dangerous.
Dude, how are you going to get updates to your product without downloading & evaluating remotely hosted code?

> What you mean with "anonymous functions" I am not so sure. Certainly not lambdas `() => {}`?
I mean construction `new Function` . Such evaluations is used, for example, in vuejs, for parsing vue's directives.

**Comment by semmel** [comment]
@Sunvas 
> Dude, how are you going to get updates to your product without downloading & evaluating remotely hosted code?

Our remotely hosted runs in the [Browser Context](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#browser-context). 
IMO updates to the code which has full system access to the computer it is installed on, should be performed by app updates. Executing remote code breaks user trust.

> I mean construction new Function . Such evaluations is used, for example, in vuejs, for parsing vue's directives.

A discussion about [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) is irrelevant here. It is a reality, already in place in ES modules, can be enforced by [HTTP CSP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) by servers, and as you say will be enforced by Google with Manifest V3. The question is, if NWJS is already compatible. 

At least our app does not show any new errors when we switch to Manifest V3 in NWJS `v0.62.1`.
Keeping 🤞🏻

**Comment by Sunvas** [comment]
@semmel 

>  should be performed by app updates.
Without centralized application store (like Chrome Webstore) it doesn't make sense.

> Executing remote code breaks user trust.
Not in every application: I take care of my users myself. So, I hope that using remotely hosted code will not be banned in NWJS in foreseeable future.

**Comment by marlarius** [comment]
This might also impact Chrome packaged apps. The nwjs team long ago stated that nwjs will continue support Chrome Apps. However, as far as I know, manifest v3 is not defined for Chrome apps at all, so in case v2 is no longer supported, this might mean goodbye to Chrome apps. Is this correct?

BTW, in contrast to Google's original announcement 3-4 years ago, Chrome apps still work fine in Chrome. You just can't upload new apps, but you can update existing apps. I am pretty sure that Google have decided to let apps run until manifest v2 is no longer supported.

**Comment by ayushmxn** [comment]
I'm think it will be after NW1 code is removed. NW1 implemented a window using a Chrome app while NW2 uses the browser native window. See #5875 for more info. Let me know if I missed anything @rogerwang!
