### ISSUE TITLE
nw.js should bundle a LTS version of nodejs with latest nwjs features and fixes

### ISSUE THREAD

**Issue by fuyi-li** [nwjs/nw.js#7842]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : all
Operating System : all

### Expected behavior

<!- What do you think should happen? ->
nw.js should bundle a LTS version of nodejs witth latest nwjs features and fixes

### Actual behavior

<!- What actually happens? ->
For example, current NodeJS LTS is 16.4.0, but there is no nwjs bounded with this version of nodeJS.

nwjs suggests users to use the latest version, which bundles NodeJS 17, which will be end of life 2022-06-01. Once it is end of life, no security fixes will go into v17. npm upgrade will not support any odd-numbered version except the current release. That means after June 2022, npm upgrade can't be done unless upgrade nodejs.

That means, if we need to upgrade npm due to security issues, then we need to upgrade nodejs and we need to upgrade nwjs.

NodeJS clearly suggests "**Production** applications should only use Active LTS or Maintenance LTS releases.", hence NWJS should bundle Active LTS nodeJS.

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by rogerwang** [comment]
The v8 version of the Node.js bundled in NW has to match the one used in Chromium. That's the reason NW is always following the newest version of Node.js.

Although Node 17 will be in end of life in June, I'll update it to v18 or later, which comes with the latest security updates.
