### ISSUE TITLE
DevTools 0.62.0 - log line ref missing shows as 0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7845]
A bit odd but just noticed that console log line refs are missing - they are OK upto and including 0.61.1

MacoS 10.13 High Sierra - tested with NW.js 0.61.1 sdk and 0.62.0 sdk

0.61.1 -

<img width="1210" alt="devtools-0611" src="https://user-images.githubusercontent.com/11089335/155857409-0d7f7e2c-c66f-4395-a2dd-eb472457de1d.png">

0.62.0 -

<img width="1211" alt="devtools-0620" src="https://user-images.githubusercontent.com/11089335/155857403-25feb628-550f-45e2-baa9-ff98503fd918.png">

**Comment by rogerwang** [comment]
Thanks. This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
