### ISSUE TITLE
single-instance  Configuration does not take effect

### ISSUE THREAD

**Issue by houlijiang** [nwjs/nw.js#7846]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System :
nwjs-v0.61.0-win-x64
### Expected behavior

<!- What do you think should happen? ->
package.json：single-instance：false
Multiple instances can be started at the same time

### Actual behavior

<!- What actually happens? ->
Configuration does not take effect

### How to reproduce
package.json：single-instance：false

**Comment by sysrage** [comment]
Per the documentation, the option `single-instance` is deprecated since NW.js 0.13.0: https://nwjs.readthedocs.io/en/latest/References/Manifest%20Format/#single-instance

With any version after 0.13.0, `single-instance` is *always* `true`.

**Comment by zkrige** [comment]
Any suggestions on how to do multi instances then?

**Comment by BrianBothwell** [comment]
> Any suggestions on how to do multi instances then?

This is not the correct forum for asking advice. Join Discord or Gitter or post to the mailing list. This bug is invalid and should be closed.
