### ISSUE TITLE
Call javascript on file download??

### ISSUE THREAD

**Issue by btwael** [nwjs/nw.js#785]
Hi! node-webkit!

Can I call Javascript code when URL is not supported by node-webkit( file to download) ?
and use Javascript code without open a File Dialog for choosing dir where file will be downloaded??

I hope that my idea is clear, and sorry for my bad english.
@rogerwang

**Comment by collinsp** [comment]
new-win-policy doesn't trigger when a download occurs from an iframe. For example I have a page that displays a PDF in an iframe.

<iframe src=foo.pdf></iframe>

If I want to prevent the file dialog from automatically appearing, I should be able to:
    win.on('new-win-policy', function(frame, url, policy) {
      console.log('new-win-policy');
      policy.ignore();
    });

But this is never fired.

**Comment by micoboyet** [comment]
Hi, any updates on this? I also need the download dialog event so that I can put an event during the download progress.

new-win-policy did not work.

Thanks.

**Comment by rogerwang** [comment]
It's now supported through chrome.download API.

https://developer.chrome.com/extensions/downloads

http://stackoverflow.com/questions/26179686/how-can-i-capture-the-download-progress-in-chrome-extension
