### ISSUE TITLE
npm non-native modules 's not working when build app

### ISSUE THREAD

**Issue by gacontuyenchien1** [nwjs/nw.js#7850]
NWJS Version : Latest( 0.62.0)
Operating System : Window 10 pro 10.0.19042

### Expected behavior
Can use non-native npm modules. In this case: express
### Actual behavior
It is working when I use ```npm start```, but when I build the app. It's not working.
Native module "os" is still working for both cases.
### How to reproduce
This is my test project for this feature.
https://github.com/gacontuyenchien1/NwjsBuildApp
Thank for helping me.

**Comment by sysrage** [comment]
This is a build tool and/or usage issue, not a bug with NW.js. I explained proper React/NW.js usage to the reporter on Gitter.
