### ISSUE TITLE
Webview permission partitions causing crash on start since 0.58.0

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7853]
MacOS 10.13 High Sierra 
NW.js 0.58  ~ 0.62

trusted-audio and trusted-video permissions causing crashes in NW.js - uptil now these appear to have been valid options.

Since 0.58.0 NW.js will crash on launch if "trusted-audio" and "trusted-video" are used as permission partitions. 0.57.0 and earlier are OK.

:: package.json ::

  "webview": {
    "partitions": [
        {
          "name": "trusted",
          "accessible_resources": [ "<all_urls>" ]
        },
        {
          "name": "trusted-audio",
          "accessible_resources": [ "<all_urls>" ]
        },
        {
          "name": "trusted-video",
          "accessible_resources": [ "<all_urls>" ]
        }
     ]
  },

:: HTML ::

<webview id="wbv" partition="trusted-audio" src="test.mp3" class="wbv"></webview>

<webview partition="trusted-video" src="test.mp4" class="wbv"></webview>

Two debug logs are attached which show the FATAL.

Interesting on line 41 of the 0.58.0 log shows the profile folder in Application Support as 'media' when the folder is actually 'mediatest'.

The fix for me is to simply use "trusted" only.

[chrome_debug-0580def.log](https://github.com/nwjs/nw.js/files/8232475/chrome_debug-0580def.log)

[chrome_debug-0620def.log](https://github.com/nwjs/nw.js/files/8232478/chrome_debug-0620def.log)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
