### ISSUE TITLE
SHA256 Checksum does not match for v0.62.1

### ISSUE THREAD

**Issue by qbroker** [nwjs/nw.js#7857]
NWJS Version : 0.62.1
Operating System : Linux Mint 19 Cinnamon 3.8.9, Kernel 4.15.0-173-generic

### Expected behavior
SHA256 checksum should match for v0.62.1

### Actual behavior
SHA256 checksum for v0.62.1 does not match, v0.62.0 on the same system gives a match

### How to reproduce
Console log:
Checksum for v0.62.0 is OK
user@CMP-1 ~/nwjs $ curl -O https://dl.nwjs.io/v0.62.0/SHASUMS256.txt
user@CMP-1 ~/nwjs $ grep nwjs-sdk-v0.62.0-linux-x64.tar.gz SHASUMS256.txt | sha256sum -c
nwjs-sdk-v0.62.0-linux-x64.tar.gz: OK

Checksum for v0.62.1 no match
user@CMP-1 ~/nwjs $ curl -O https://dl.nwjs.io/v0.62.1/SHASUMS256.txt
user@CMP-1 ~/nwjs $ grep nwjs-sdk-v0.62.1-linux-x64.tar.gz SHASUMS256.txt | sha256sum -c
nwjs-sdk-v0.62.1-linux-x64.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

Have a nice day, Okido

**Comment by rogerwang** [comment]
Thanks for reporting. There was a cache problem on one of the mirrors. It's fixed now.

**Comment by qbroker** [comment]
Thanks, it works as expected, Okido
