### ISSUE TITLE
Cpp support

### ISSUE THREAD

**Issue by rdwnsjjd** [nwjs/nw.js#7863]
Does your project supports cpp in backend and web-framework such as reactjs and vuejs in frontend?

**Comment by bluthen** [comment]
It has node, which itself has api's can load and load native code, or you can use modules that help like node-ffi-napi that can make things easier. On start you can write a waper js function to call that native code and start it up.

Then you can load a html page and javascript and have it act like a normal browser with react or whatever.

**Comment by TheJaredWilcurt** [comment]
I think that's a good answer, feel free to re-open if you have additional questions or use the community chatrooms (Gitter, Discord) listed on https://nwutils.io
