### ISSUE TITLE
Clicking "inspect" on the chrome://inspect window for a shared worker kills nwjs on Windows

### ISSUE THREAD

**Issue by sdurham** [nwjs/nw.js#7867]
NWJS Version : 0.63.1, but also earlier versions, I don't now which version broke it (or if it ever worked).
Operating System : Windows 10 pro
This works fine on Mac, so I'm developing there for now so I can debug shared workers.

### Expected behavior
Chrome inspect links open a separate devtools window for debugging workers.

### Actual behavior
On windows 10 at least, nwjs simply vanishes completely.

### How to reproduce
Start a shared worker -- it could be simple, maybe from the test suite. I have a whole thing set up with webpack so don't have a simple test case handy.
Then do window.open('chrome://inspect#workers').
Your worker should be in the list. Click on inspect... poof goes the app.

**Comment by sdurham** [comment]
@rogerwang Can we get this fixed?
This makes it incredibly difficult to develop/debug worker related code on Windows :(

**Comment by sdurham** [comment]
I'll fiddle with this some more but:

To reproduce, maybe use an example like here from the repo:
[test/sanity/worker-sharedworker/index.html](https://github.com/nwjs/nw.js/tree/nw65/test/sanity/worker-sharedworker)

so perhaps enter that directory, launch nwjs.
Then on the loaded app, right click to inspect. Then go to shared workers and try to inspect the worker.

On windows this crashes the app.

**Comment by sdurham** [comment]
Wherever you usually run nwjs for testing, use these files:

package.json
```
{
  "name": "worker-sharedworker",
  "main": "index.html",
  "version": "1.0.0",
}
```

sharedworker.js:
```
onconnect = function(e) {
  var port = e.ports[0];
  try{
    port.postMessage('success');
  } catch (e) {
    port.postMessage(e.message);
  }
}
```

and this index.html
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>worker-sharedworker</title>
</head>
<body>
  <button id="start" onclick="startWorker()">Shart SharedWorker</button>
  <script>

  function startWorker() {
    var worker = new SharedWorker('sharedworker.js');
    worker.port.onmessage = function(e) {
      var h1 = document.createElement('h1');
      h1.setAttribute('id', 'result');
      h1.innerHTML = e.data;
      document.body.appendChild(h1);
    }
    window.open('chrome://inspect#workers');
  }
  </script>
</body>
</html>
```

When you click the button, it opens the chrome:inspect window.
Click on inspect for the worker. A window briefly appears then the app vanishes.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by sdurham** [comment]
Woo hoo thanks works great now!

Thanks Roger!
