### ISSUE TITLE
Crash when loading a file only if i don't right click and click "Inspect"

### ISSUE THREAD

**Issue by Daxelarne** [nwjs/nw.js#7869]
NWJS Version : v0.63.1 x64
Operating System : Windows x64

### Expected behavior

I'm loading an xlsx file, using ExcelJs, from the server to load to display some data

### Actual behavior

If i right click and select "Inspect" before loading the xlsx, it work as intended. But if i don't, nwjs close instantly

### How to reproduce

Here is my JS function

```
document.getElementById("loading").style.display="block";
document.getElementById("searchchrono").disabled=true;

await fs.copyFileSync('SERVER FILE.xlsx', `LOCAL COPY.xlsx`);

await new Promise(resolve => setTimeout(resolve, 1000));

var chrono = new excel.Workbook();
chrono.xlsx.readFile('LOCAL COPY.xlsx').then(async () => {
    const chronows=chrono.getWorksheet('2022');
    for(var kk=2;chronows.getCell(`A${kk}`).value!=null;kk++) {
        if(chronows.getCell(`A${kk}`).value==numdevis) {
            document.getElementById("client").value=chronows.getCell(`D${kk}`).value
            if(chronows.getCell(`E${kk}`).value!=null) {
                document.getElementById("bvlab").value=chronows.getCell(`E${kk}`).value
            }
            if(chronows.getCell(`F${kk}`).value!=null) { 
                descProduit=chronows.getCell(`F${kk}`).value
            }
        }
    }
}).then(()=> {
    document.getElementById("loading").style.display="none";
    document.getElementById("searchchrono").disabled=false;
})
```

I tried everything, the part that seems to make it crash is the xlsx.readFile(), i does work fine with a lighter xlsx file tho

Thanks for the help in advance (sorry for the english, i'm french)

**Comment by TheJaredWilcurt** [comment]
Unable to reproduce issue. Code worked as expected. Attached is my attempt to reproduce the issue. If you could narrow the problem down to the fewest lines of code required to reproduce the issue consistently, a new issue could be opened with that code sample.

* [failed reproduction.zip](https://github.com/nwjs/nw.js/files/8547401/7869.zip)

**Comment by Daxelarne** [comment]
As i said "i does work fine with a lighter xlsx file tho"
yes a 4 cell excel work but it crash with a 4MB Excel document.
