### ISSUE TITLE
NW.js crashes when using Menubar in 0.63.0+

### ISSUE THREAD

**Issue by stephcache** [nwjs/nw.js#7870]
si utilise le menubar, node webkit ouvre et ce ferme tout de suite

var nw = require('nw.gui');
var win = nw.Window.get();
var fs = require('fs');
var php = require('phpjs');
var path = require('path');
var chemin = path.resolve();

$(function()
{
	$("#version p:nth-child(1)").append(process.versions['node-webkit']);
	$("#version p:nth-child(2)").append(process.versions['node']);
	$("#version p:nth-child(3)").append(process.versions['chromium']);

// Create an empty menubar
var menu = new nw.Menu({type: 'menubar'});

// Create a submenu as the 2nd level menu
var submenu = new nw.Menu();
submenu.append(new nw.MenuItem({ label: 'Item A' }));
submenu.append(new nw.MenuItem({ label: 'Item B' }));

// Create and append the 1st level menu to the menubar
menu.append(new nw.MenuItem({
  label: 'First Menu',
  submenu: submenu
}));

// Assign it to `window.menu` to get the menu displayed
nw.Window.get().menu = menu;

});

**Comment by TheJaredWilcurt** [comment]
@rogerwang I was able to reproduce this:

**Issue does not occur in:**

* 0.62.2

**Issue does occur in:**

* 0.63.0
* 0.63.1

**Diff:**

* https://github.com/nwjs/nw.js/compare/nw-v0.62.2...nw-v0.63.0

**Reproduction link:**

* [7870.zip](https://github.com/nwjs/nw.js/files/8543218/7870.zip)

**Comment by stephcache** [comment]
The problem is the same on version 0.64

**Comment by sysrage** [comment]
I am also seeing this crash. The minimal repro is simply opening `nw.exe` by itself and entering the following into the console:
```js
nw.Window.get().menu = new nw.Menu({ type: 'menubar' });
```

@rogerwang can you please take a look?

**Comment by TheJaredWilcurt** [comment]
Stackoverflow question also ran into this:

* https://stackoverflow.com/questions/72328273/react-nw-js-menubar-setup-crash

**Comment by stephcache** [comment]
Still no resolution of the problem in version 0.65!!!!

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
