### ISSUE TITLE
nw-gyp rebuild fail

### ISSUE THREAD

**Issue by xxwangkaimin** [nwjs/nw.js#7871]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.14.7
Operating System : Windows x64

### Expected behavior

nw-gyp rebuild --target=0.14.7 --arch=x86

### Actual behavior

gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.6
gyp info using node@12.22.8 | win32 | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.14.7/nw-headers-v0.14.7.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.108.195:80
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\development\\nodejs\\node.exe" "C:\\development\\nodejs\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.14.7" "--arch=x86"
gyp ERR! cwd C:\work-code\nw\nw-vue-app\node_modules\@thiagoelg\node-printer
gyp ERR! node -v v12.22.8
gyp ERR! nw-gyp -v v3.6.6
gyp ERR! not ok

### How to reproduce

install python and set python path

npm i -g nw-gyp node-gyp

cd project

npm i @thiagoelg/node-printer

cd /node_modules/@thiagoelg/node-printer

nw-gyp rebuild --target=0.14.7 --arch=x86

**Comment by ayushmxn** [comment]
Building NW.js seems to be riddled with issues. You're more likely to get help if you ask on [Gitter](https://gitter.im/nwjs/nw.js), [Google Group](https://groups.google.com/g/nwjs-general) or [Discord](https://discord.gg/tyx267vKRH). If you figured it out, could you share your solution here? I'm trying to build NW.js :P
