### ISSUE TITLE
NW2 - regression - 0.64.0 transparency broken background is white with NW2

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7872]
OS: 10.13.6 High Sierra
NWjs: 0.64.0-sdk

Transparency works fine if --disable-features=nw2 is used in manifest otherwise background is white.
NW2 works OK with 0.63.1 and earlier.

<img width="599" alt="whitewithnw2" src="https://user-images.githubusercontent.com/11089335/165899138-c5f568da-18c7-408a-899b-8a58ee97b0bf.png">

[TransTest-simple.zip](https://github.com/nwjs/nw.js/files/8588764/TransTest-simple.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
