### ISSUE TITLE
MacOS - Default nwjs window not showing on launch with 0.64.1 build

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7874]
OS: 10.13.6 High Sierra
Index of /live-build/nw64/20220504-031647/9319ca174/v0.64.1/   (sdk)

Initial run requires signing/opening permissions as usual but when NWjs has launched the icon is in the dock OK and the native menubar is present but no window with splash screen showing.

The 'nwjs Helper (Renderer)' process is missing from the Activity Monitor.

Tried re-downloading the latest nightly and deleting nwjs profile but still faulty.

Everything works fine with 0.64.0 build and  'nwjs Helper (Renderer)' process is present.

**Comment by rogerwang** [comment]
Thanks for testing. But it works for me. The only update is Node.js v18.0.0, which requires macOS 10.15 or later. Maybe that's the cause?

**Comment by Blatman** [comment]
@rogerwang - thanks for that. I just tried the build on 12.2 and it works so maybe the Info.plist min version needs to be bumped from 10.11 to 10.15

Note: Also tried it on 10.14.6 Mojave and it worked OK.

I will close this since it appears that NWjs on Mac is supported from 10.15 (Catalina) onward from 0.64.1
