### ISSUE TITLE
Nodejs: New experimental fetch

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7885]
With new NWjs 0.64.1 has arrived with Nodejs v18 with ["new experimental fetch"](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V18.md#fetch-experimental), but this broking our project. Is any chance add Nodejs parameter `--no-experimental-fetch`?
Add to `js-args` and `chromium-args` does not works.

**Comment by panther7** [comment]
Probably fixed in [NodeJs 18.1.0](https://github.com/nodejs/node/pull/42939)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
