### ISSUE TITLE
Application crashed when loading JSDOM

### ISSUE THREAD

**Issue by Jagdeep1** [nwjs/nw.js#789]
Hi All,

I am very new to node-webkit but it looks very interesting project. I have a node code where I am using jsdom https://github.com/tmpvar/jsdom. My node-webkit application is getting crashed when I am trying to load jsdom.
1) Does it not support jsdom
2) Is there any other way to execute my app without actually loading jsdom in node-webkit?

Thanks & Regards
Jagdeep

**Comment by brettz9** [comment]
I am requiring an npm package which relies on jsdom. When I introspect within my package, I see that `document` is not defined there, while I also cannot use jsdom.
