### ISSUE TITLE
Video stream from surveillance camera does not play, but plays in Chrome browser

### ISSUE THREAD

**Issue by Allasso** [nwjs/nw.js#7891]
Note: I realize this is a very specific use-case.  However, I am able to log in to the camera in Chrome web browser (version 101.0.4951.64) and everything works fine (same or similar back-end, correct?)  I hope that maybe someone might recognize this as related to some issue, with a fix/workaround.  (Note also that I am testing on 0.64.0, as 0.64.1 does not run on my system, but that is another issue altogether.)

NWJS Version : 0.64.0
Operating System : MacOS 10.13.6

### Expected behavior

When surveillance camera page is loaded, after logging in, should see camera footage streaming live inside the player (HTML5 video) of the page.

### Actual behavior

Pages loads fine, but the player of the page is blank, but black.  It appears as though the video is loaded, but not playing.

### How to reproduce

Create app with HTML page and JS file.  Link JS file in HTML page.  Add code (example, as this is on the local network) `window.location.href = "http://192.168.1.252";`.

Open app, and log in.

Debugging this is extremely difficult as I don't own the code the camera is downloading, thus I am not able to manipulate it.  Also it uses reams of minified code making things more difficult.

I get this error repeatedly on a fast loop:

"Uncaught (in promise) InvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source."

I realize the code to which this error refers is specific to the camera, but wonder what might cause an object to be removed from its parent media source.

I also have an indication the the video may actually be loaded but not streaming, because when I right-click the player and click on "media info", the "speed" value keeps changing, but no other values.  The info window in Chrome browser will show the decoded, currenttime, bufstart and bufended values gradually increasing. (The attached screen shot shows the info window to which I refer.)  Also it seems something is loaded because otherwise I would either get a spinning "loading" indicator, or it would finally show a message, "stream could not be found."

Another curious thing is that the page/camera has a "playback" mode which will stream video that has been recorded on the camera's sd card, and it plays just fine.

Again, I know this is all very specific, but hoping it might jog someone's memory about a related issue.

<img width="349" alt="Screen Shot 2022-05-23 at 9 33 17 AM" src="https://user-images.githubusercontent.com/8195897/169860184-51e20380-e33d-4f1c-a80e-e0c29f1b0639.png">

**Comment by Allasso** [comment]
As far as regression goes, this issue also exists as early as 0.49.1.

**Comment by sysrage** [comment]
You are likely missing the codecs needed for the video stream: <https://nwjs.readthedocs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#enable-proprietary-codecs>

**Comment by ayushmxn** [comment]
I'm closing this for now. Ping me here if you come across an issue after integrating the relevant codecs!

**Comment by Allasso** [comment]
Oh wow, so sorry for not following up with a reply on this.  Yes, the codecs fixed the issue.
