### ISSUE TITLE
Modal window in NW.js

### ISSUE THREAD

**Issue by muhammad-bassiouni** [nwjs/nw.js#7894]
How can I create modal window in NW.js, I can't find a direct way to do that and I have seen pull requests before related to this issue but it seems that there is no progress.

**Comment by TheJaredWilcurt** [comment]
There is no "modal" concept in Chromium. The closest would be `alert('value')`, which is generally frowned upon.

You can however create your own modal using the HTML/CSS/JavaScript. This is how every page on the internet does it.

There are a ton of tutorials and libraries and plugins available for you to Google. Depending on if you are doing Vanilla JS, or jQuery, or Vue.js, etc, it will all be slightly different. But the idea is the same, an absolute positioned div with a dimmed background color covers everything, and a div inside that centers the content, and you toggle if it is visible or not.

**Comment by ishanuda** [comment]
Hi @muhammad-bassiouni,
You can use a library like atertify js.
https://alertifyjs.com/

It's a nice and simple library to use.
