### ISSUE TITLE
--enable-node-worker overwrites global fetch method with incompatible node one (regression 0.64.1)

### ISSUE THREAD

**Issue by AshleyScirra** [nwjs/nw.js#7895]
NWJS Version : 0.64.1
Operating System : Windows 10 64-bit

### Expected behavior

When passing `--enable-node-worker`, the global fetch method should remain the browser implemented one, not the node one.

### Actual behavior

When passing `--enable-node-worker`, the global fetch method in workers is replaced with the node implemented one, which is not browser compatible (e.g. it cannot handle being passed a Request object) which breaks content.

### How to reproduce
Minimal repro: [node-worker-fetch.zip](https://github.com/nwjs/nw.js/files/8797979/node-worker-fetch.zip)
This enables `--enable-node-worker` and uses fetch in both the main context and a worker. In the worker it fails because it uses an incompatible node implementation. The only workaround seems to be to remove `--enable-node-worker`, but that then removes the ability to use any node APIs at all.

Presumably there is some special handling to ensure node does not overwrite the fetch method in the main context. This should be done for other contexts like workers too.

This is a regression in 0.64.1 as it updated to Node.js 18 which includes new support for the global fetch method by default. 0.64.0 is not affected as it does not use Node.js 18.

**Comment by panther7** [comment]
#7885

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by AshleyScirra** [comment]
Thanks!
