### ISSUE TITLE
Feature Request: Event for going into and out of native split screen

### ISSUE THREAD

**Issue by schockocraft** [nwjs/nw.js#7899]
NWJS Version : Stable v0.64.0
Operating System : Microsoft Windows 10 Pro 10.0.19042.1466

### Expected behavior
An event fires when activating split screen, and another when deactivating it.

### Actual behavior
The only event firing are the `window.on('move')` and `window.on('resize')` events, from where one can only estimate if split screen is activated or not.

### How to reproduce
On Windows: Drag the window, and move the cursor to the right or left edge of the screen, or press Windows+Left/Windows+Right.
The Window will enter Split Screen mode. Move the window again, and it will automatically restore.

in both cases only the two `window.on('move')` and `window.on('resize')` events will fire.

**Comment by ayushmxn** [comment]
I'm not sure if this is the right place for this kind of request?

cc @TheJaredWilcurt @sysrage

**Comment by sysrage** [comment]
AFAIK, Chromium would need to implement an event specific to entering/leaving split-screen. This seems unlikely, but possible.

I'm also not understanding why this information would be needed. Split screen isn't really a different "mode", it's just changing the window dimensions to fill half the screen. You should be able to determine if a window is filling half the screen by using `nw.Screen.screens`.

**Comment by schockocraft** [comment]
well, sure, but a window can also fill half the screen *without* being in split screen mode, there is now way to determine if it actually is in split screen or not, which is what i'd like to have though.

**Comment by ayushmxn** [comment]
I think it makes more sense for this to be a standalone library/script which uses the NW API.
