### ISSUE TITLE
Starting the program crashes and exits

### ISSUE THREAD

**Issue by wenreshui** [nwjs/nw.js#7903]
NWJS Version :0.49.2
Operating System :
Starting the program crashes and exits, log is: 

[0615/111150.444:ERROR:icu_util.cc(247)] Couldn't mmap icu data file
[0615/111150.445:FATAL:icu_util.cc(310)] Check failed: result. 
Backtrace:
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A5E58F3+7260835]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A57F6C1+6842481]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A58BEE7+6893719]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A58CA0B+6896571]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A57738F+6808895]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A6C3B5B+8170763]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A4F7565+6285077]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A4F6741+6281457]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A525C75+6475301]
	v8::internal::TorqueGeneratedExportedMacrosAssembler::StoreSortStateTempArray [0x5A4F719C+6284108]
	ChromeMain [0x57EC11BD+301]
	Ordinal0 [0x0090226B+8811]
	Ordinal0 [0x009015F4+5620]
	GetHandleVerifier [0x00A0BBEA+730490]
	BaseThreadInitThunk [0x76C2FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77857A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77857A6E+238]

[0615/111151.182:ERROR:filesystem_win.cc(129)] GetFileAttributes C:\Users\zhangming\AppData\Local\software-center\User Data\Crashpad\attachments\acb04df8-d136-4160-b187-d873b551ebdb: 系统找不到指定的路径。 (0x3)
[0615/111151.195:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: 操作成功完成。 (0x0)

**Comment by ayushmxn** [comment]
Could you provide a repro/sample code?
