### ISSUE TITLE
Run node command in NWJS

### ISSUE THREAD

**Issue by ishanuda** [nwjs/nw.js#7906]
Hi,
I would like to know if there is a way to run node command using the `nwjs.exe` file?

In the local PC with installed Node.JS we can use the node command to run a js file as follows.
Ex: `node index.js`

If this is not possible in NWJS application, I would like to request this as a feature in the environment so that the aforementioned commands can be run.

Thank you.

**Comment by TheJaredWilcurt** [comment]
It sounds like what you want is a portable version of Node.js, which already exists (you'll have to google it) and will be a much smaller footprint than something that ships an entire browser.

If you want to use a Node script as the entry point for your application, that is possible with NW.js, by setting it in the `main` of your `package.json` to `file.js`. Alternatively, you can use `node-main` to run a script prior to your `main` window launching. This is often used to spin up a web server prior to the window opening.

In your application, if you want to import or run Node.js files, you can use `require('./file.js')` at any point.

**Comment by ishanuda** [comment]
hi,
Thank you very much for the information.
