### ISSUE TITLE
bug...The frame set transparent invalid right-click menu

### ISSUE THREAD

**Issue by jorshxp** [nwjs/nw.js#7908]
package.json config:
=======================================
{
  "name": "MN",
  "main": "index.html",
  "nodejs":true,
  "window": {
    "frame": false,  //important here
    "toolbar": false,
    "width": 800,
    "height": 580,
    "show":false,
    "position": "center",
    "transparent": true //important here
  },
  "webkit":{
    "plugin":true
  }
}
===========================
index.html script
============================
var rmenu = new gui.Menu();
        rmenu.append(new gui.MenuItem({
            label: 'lock pos',
            click: function(){
                alert('lock pos OK!');
            }
        }));

document.body.addEventListener('contextmenu', function(ev) {
        alert('test'); //here not work, then set frame true it's can work
        ev.preventDefault();
        rmenu.popup(ev.x, ev.y);
        return false;
    });
==========================

how can it's work?

**Comment by ayushmxn** [comment]
@jorshxp Kind of hard to understand what's going on. I'm assuming there's a variable assignment which is something like `var gui = nw;`. A repro would be easier to understand.
