### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND..

### ISSUE THREAD

**Issue by donghang1994** [nwjs/nw.js#7911]
NWJS Version :0.65.0
Operating System : Linux

I use it in combination with WebAssembly, at Linux. and report such an error, can’t find wasm file, but it's under my directory.
What is the reason for this.

![Uploading image.png…]()

**Comment by donghang1994** [comment]
![7ff16967451fa94c8982188c80681bf6](https://user-images.githubusercontent.com/91657327/177150595-08b2d23b-74ed-4ee6-a51c-fb98c1dac0a9.png)

**Comment by donghang1994** [comment]
@rogerwang

**Comment by ayushmxn** [comment]
Do you have a link to a repro?

**Comment by ayushmxn** [comment]
Closing this for now. Ping me here if the issue still persists and please provide a link to repro/steps to reproduce.
