### ISSUE TITLE
nw stucks on sync-rpc error

### ISSUE THREAD

**Issue by smartm0use** [nwjs/nw.js#7912]
NWJS Version : nwjs 103.0.5060.53
Operating System : Ubuntu 20.04

I extract the linux version (nwjs-v0.66.0-linux-x64) and I copy in it my zipped nodejs application (package.nw). Then I run the following command:
`cat ./nw package.nw > app && chmod +x app`

I get the following error:
**[0704/163505.900482:ERROR:zip_reader.cc(137)] Cannot open ZIP archive '/tmp/.io.nwjs.gkyaAm/node_modules/sync-rpc/lib/worker.js'**

And nw stucks on it...

**Comment by TheJaredWilcurt** [comment]
In the example in the docs it assumes you have created a `.zip` file that has a `package.json` in its root, and then you renamed the `.zip` to `.nw`. The renaming is not needed, you could do `cat ./nw file.zip > YourAppName && chmod +x YourAppName`.

With that said...


# **DON'T DO THIS**.


Despite `cat ./nw package.nw > app && chmod +x app` being mentioned in the docs, it is **not recommended**. Packaging your app into the binary means that it needs to be extracted on every launch of the app. This causes very slow start up times while the files are unzipped to a temp folder on the computer. Every time the app is launched.

You're better off just putting a `package.nw` folder next to the `nw` executable with a `package.json` in the `package.nw` folder. Then zipping the whole thing up.

* /App-For-Distribution.zip
  * nw.exe (can be renamed to yourapp.exe)
  * ...Other NW.js files (ffmpeg.dll, icudtl.dat, etc)
  * package.nw/
    * package.json
    * other app files (index.html, etc)

Then someone just needs to download, unzip, double-click to run your app.
