### ISSUE TITLE
Domain=NSCocoaErrorDomain Code=260 in terminal log when writing to new file in Downloads directory

### ISSUE THREAD

**Issue by SheetJSDev** [nwjs/nw.js#7913]
NWJS Version : 0.66.0 (npm, latest), 103.0.5063.53 (`npx nw --version`, latest) 
Operating System : macOS Monterey 12.4

### Expected behavior

No message when saving to a new file in the Downloads directory

### Actual behavior

Terminal displays a message like

```
2022-07-05 20:54:20.309 nwjs[11050:1118961] NSURLIsPackageKey lookup returned Error Domain=NSCocoaErrorDomain Code=260 "The file “test.xlsx” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/sheetjs/Downloads/test.xlsx/, NSFilePath=/Users/sheetjs/Downloads/test.xlsx, NSUnderlyingError=0x600003daa070 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} for path /Users/sheetjs/Downloads/test.xlsx.
```

Note: This appears to be a message.  Files are still written.  This message did not show in older versions of macOS.

### How to reproduce

`package.json` bare minimum:

```json
{
  "name": "test",
  "main": "index.html",
  "dependencies": {
    "nw": "~0.66.0"
  }
}
```

`index.html` initiate download in a `DOMContentLoaded` event:

```html
<!DOCTYPE html>
<html><body><script>
var fs = require('fs');
document.addEventListener('DOMContentLoaded', () => {
  var input = document.createElement('input');
  input.style.display = 'none';
  input.setAttribute('nwsaveas', 'test.xlsx');
  input.setAttribute('type', 'file');
  document.body.appendChild(input);
  input.addEventListener('cancel',function(){ alert("Save was canceled!"); });
  input.addEventListener('change',function(e){
    var filename=this.value;
    fs.writeFile(filename, "test", function(err) {
      if(!err) return alert("Saved to " + filename);
      alert("Error: " + (err.message || err));
    });
  });
  input.click();
});
</script></body></html>
```

Run in a terminal with

```zsh
% npm i
% npx nw .
```

Select "Downloads" from the list and enter the name "test.xlsx" if it is not already set:

<img width="344" alt="nwsaveas" src="https://user-images.githubusercontent.com/6070939/177440932-01915b27-b8e5-4380-9bda-ffa3385b9eab.png">
 
If the file does not exist, the referenced error shows up in the terminal (but the file will be created).  If the file does exist, it will prompt to Replace file and no message will be displayed.

**Comment by ayushmxn** [comment]
I was unable to [reproduce](https://github.com/ayushmxn/nw-repro/tree/dev-7913) on Ubuntu 22.04. Seems to be platform specific.

**Comment by ayushmxn** [comment]
Since this is just a message which doesn't affect any application behaviour, it can be safely ignored.
