### ISSUE TITLE
I cant use flash

### ISSUE THREAD

**Issue by VyrekXD** [nwjs/nw.js#7915]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : 0.66.0 and 0.36.4
Operating System : Windows x64

### Expected behavior

Code: https://github.com/VyrekXD/ClubPenguinClient

So i use first the latest version and i was trying to use flash in a restored version of club penguin (the web is not the problem because i can use pale moon easily) it just doesnt run the flash player in either versions

### Actual behavior

It should at least run flash in one of the two versions

### How to reproduce

1. Clone my repo
2. Use the test command in package.json and try click in "Iniciar sesion" inside the web
3. Try to use flash

**Comment by erezcohen** [comment]
Hi @VyrekXD, so does it work?
Were you able to run flash in nw?

**Comment by VyrekXD** [comment]
Hi i ended up using electronjs

**Comment by erezcohen** [comment]
But you cannot use electron with flash as well no?
Unless you pick an old version

**Comment by VyrekXD** [comment]
> But you cannot use electron with flash as well no?
> Unless you pick an old version

Yes, you are correct you can check how I did it on SecretAgencyClubPenguin/ClubPenguinClient
