### ISSUE TITLE
window.navigator.webkitGetUserMedia taking too much time to respond in nwjs 0.59.2

### ISSUE THREAD

**Issue by rakesh-anchan** [nwjs/nw.js#7917]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version : v0.59.2
Operating System : Windows10

### Expected behavior

webkitGetUserMedia should not take more than , 300ms

### Actual behavior

window.navigator.webkitGetUserMedia taking too much time to respond in nwjs 0.59.2 intermittently. We have noticed delay of 10- 15 minutes in getting streams
 
**Note: This was working fine in v0.45.7**

### How to reproduce

- Open nwjs sdk for v0.59.2
- Open developer tool and console
- Run below code snippet
 var startTime = new Date();
console.info(startTime);
window.navigator.webkitGetUserMedia({"video":false, "audio":true}, function(stream){
      endTime = new Date()
      console.info('Stream', stream, [endTime-startTime+"ms"])
}, function(err){
console.info("error")});

-  Same behavior is seen in v0.66.0 as well
-

**Comment by ayushmxn** [comment]
@rakesh-anchan I used `v0.66.1` and consistently got less than 300ms.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/14110965/179408290-95f64092-dae6-4da8-82c5-92ae148a3b9b.png">

**Comment by rakesh-anchan** [comment]
@ayushmxn With our further analysis on the issue, we found that, api takes more time, if the nodewebkit main window is in minimized state. 

When we move the window to foreground, we get the response.

**Comment by ayushmxn** [comment]
That's weird! Is it possible to make a small repro so I can dig into this? Seems NW.js related.

Just to clarify:

> if the nodewebkit main window is in minimized state.

Do you mean when the app is minimized on your computer?

> When we move the window to foreground

And conversely do you mean when it's maximised on your screen?

**Comment by rakesh-anchan** [comment]
![test](https://user-images.githubusercontent.com/44994574/179789528-cbb9da90-393a-4e48-9ed9-5c4689f7a9a8.gif)

I have attached video of reproducing the issue win v0.66.0 version

**Comment by ayushmxn** [comment]
@rakesh-anchan were you able to find a workaround?

**Comment by rakesh-anchan** [comment]
@ayushmxn No, we could not get the workaround and ticket (https://bugs.chromium.org/p/chromium/issues/detail?id=1343275&q=webkitGetUserMedia&can=2) which we raised in chromium site, says that, it is behavioral change done on chromium to meet the media feature compliance.

As of now we had to change the behavior in our application, whenre application was brought to focus before calling webkitgetusermedia api.

**Comment by fippo** [comment]
Have you tried adding the blink-features option to the command line args? It is a allowlisted flag [here](https://github.com/nwjs/chromium.src/blob/nw18/content/public/common/content_switches.cc#L362) and the process is documented [here](https://nwjs.readthedocs.io/en/latest/References/Command%20Line%20Options/#other-chromium-options)

**Comment by ayushmxn** [comment]
@rakesh-anchan I'll be afk till Monday if you want to give this a go. This looks promising given [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1343275#c14) on the Chromium ticket.

**Comment by ayushmxn** [comment]
I get a `DOMException: Requested device not found` error on adding the [disable blink feature flag](https://github.com/ayushmxn/nw-repro/blob/d9b671bf72a09ac2c939bf6a4088f667911a9ec5/app/package.json#L5) so unable to confirm if it works.

**Comment by tharatau** [comment]
@rakesh-anchan upstream ticket comment #16 may help

**Comment by MistakingManx** [comment]
I am experiencing this issue, my solution since it's for Windows only, was to use "nircmd" to focus the window when it needs to listen, `nir win activate process nw.exe`.

Is there a better method, though?
