### ISSUE TITLE
feature request, possible to use a golang package to automatically download nw.js in different machine platform and use remote url as gui just like go-astilectron and go rod

### ISSUE THREAD

**Issue by passerbyo** [nwjs/nw.js#7919]
Thanks for reporting an issue! Spend 60 seconds reading this...

1. Before reporting, try reproducing against the latest version of NWJS.
2. Issue tracker is only for bugs and feature requests, in English only.
  
  Anything else? Use our mailing list for questions: 
  https://groups.google.com/forum/#!forum/nwjs-general

======== TEMPLATE BUG FORM ========

NWJS Version :
Operating System :

### Expected behavior

<!- What do you think should happen? ->

### Actual behavior

<!- What actually happens? ->

### How to reproduce

<!- 

- Detail a step by step guide to reproduce the issue
- A copy of your code would help. Include: JS, HTML. 
- If you have a crash report, copy it in. 
- Test your steps on a fresh environment to see if you still have an issue
- Post!

->

**Comment by ayushmxn** [comment]
@passerbyo After going through the [link Jared posted](https://github.com/nwjs/nw.js/issues/7918#issuecomment-1185566451), I think [Wails](https://github.com/wailsapp/wails) is what you're looking for.

**Comment by ayushmxn** [comment]
Closing this for now. Ping me here if you have any more questions!
