### ISSUE TITLE
Ignore HTTPS and turn on the camera

### ISSUE THREAD

**Issue by q7486828035** [nwjs/nw.js#7920]
NWJS Version :  v0.14.7

Operating System : Windows Xp

I use win Open opens a new page. The protocol is http. Opening the camera prompts that HTTPS protocol is required. How can I remove this restriction?

**Comment by bluthen** [comment]
Start a localhost http reverse proxy, connect to localhost.

**Comment by ayushmxn** [comment]
Please ask questions in the [mailing list](https://groups.google.com/g/nwjs-general) or the [Gitter chatroom](https://gitter.im/nwjs/nw.js).
