### ISSUE TITLE
Can nw upgrade not bind node and Chromium

### ISSUE THREAD

**Issue by ostwindli** [nwjs/nw.js#7921]
RT

**Comment by ayushmxn** [comment]
How else would one get Node and Chromium bug fixes and features in NW.js?

**Comment by TheJaredWilcurt** [comment]
Closing this.

NW.js's is fundementally designed to be a Chromium browser with Node.js built in. It will never separate the two in the way you wish.

You could look into alternative solutions, if this is an important need. Technologies that have a backend separate from the render. There are pros and cons to combining or separating these concepts.

* https://xpda.net
