### ISSUE TITLE
🎈How to parse dmp file using symbol files

### ISSUE THREAD

**Issue by ostwindli** [nwjs/nw.js#7922]
I use 0.57.1-sdk.

How to parse dmp file using symbol files? 

I followed the instructions:
[https://nwjs.readthedocs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#understanding-crash-dump](https://nwjs.readthedocs.io/en/latest/For%20Developers/Understanding%20Crash%20Dump/#understanding-crash-dump) and it didn't work. 

The symbol file I got from here:

[https://dl.nwjs.io/v0.57.1/nwjs-symbol-v0.57.1-osx-x64.zip](https://dl.nwjs.io/v0.57.1/nwjs-symbol-v0.57.1-osx-x64.zip)

but，the extension is not `.sym`, it is `.breakpad`. 

I exec like this:
`./minidump_stackwalk  dc95b273-0863-4e5a-bdea-3c71c506a5f6.dmp  /path/to/symbols/....`

I get like this:

`...
19  libdispatch.dylib + 0x13bfd
    rsp = 0x000070000ea6f098   rip = 0x00007ff815595bfd
    Found by: stack scanning

Loaded modules:
0x10c55b000 - 0x10c586fff  nwjs  0.0.0.0  (main)  (WARNING: No symbols, nwjs, 4E7C70708AFD3C889F02B149AB5007080)
0x10c714000 - 0x10c71bfff  AutomaticAssessmentConfiguration  1.0.0.0
0x10c931000 - 0x10caf4fff  libffmpeg.dylib  0.0.0.0
0x10f7e0000 - 0x10f84bfff  dyld  0.0.0.0  (WARNING: No symbols, dyld, DD9E80DEFB3B349B96A446874AD34D110)
0x10ff7d000 - 0x10ff84fff  FileProviderOverride  0.0.0.0
0x10ffaf000 - 0x10ffb6fff  CloudDocsFileProvider  0.0.0.0
0x110154000 - 0x11016ffff  FinderSyncCollaborationFileProviderOverride  0.0.0.0
0x112f11000 - 0x112f20fff  libobjc-trampolines.dylib  228.0.0.0
0x11a885000 - 0x11a88cfff  IOUSBLib  0.0.0.0
0x11a91e000 - 0x124e81fff  nwjs Framework  4606.0.81.0  (WARNING: No symbols, nwjs Framework, 87A9EA49BC473F4C8B7817631E820BEB0)
0x7ff81546d000 - 0x7ff81546efff  libsystem_blocks.dylib  79.1.0.0  (WARNING: No symbols, libsystem_blocks.dylib, CCC417A892653B0CAF9598B57ABE5E430)
0x7ff81546f000 - 0x7ff8154aafff  libxpc.dylib  2236.100.61.0
0x7ff8154ab000 - 0x7ff8154c3fff  libsystem_trace.dylib  1375.100.9.0
0x7ff8154c4000 - 0x7ff815555fff  libcorecrypto.dylib  1218.100.47.0
0x7ff815556000 - 0x7ff815581fff  libsystem_malloc.dylib  374.100.5.0  (WARNING: No symbols, libsystem_malloc.dylib, CD1AD5BA470D33FFA8645FC3A18AB7C30)
0x7ff815582000 - 0x7ff8155c8fff  libdispatch.dylib  1325.100.36.0  (WARNING: No symbols, libdispatch.dylib, 31D69D559895326CAD61621C5CA873140)
0x7ff8155c9000 - 0x7ff815606fff  libobjc.A.dylib  228.0.0.0  (WARNING: No symbols, libobjc.A.dylib, 6D51B7B2136E336D95CA442AF1009EC20)
0x7ff815607000 - 0x7ff815609fff  libsystem_featureflags.dylib  56.0.0.0
0x7ff81560a000 - 0x7ff815692fff  libsystem_c.dylib  1507.100.9.0
0x7ff815693000 - 0x7ff8156ebfff  libc++.1.dylib  1300.23.0.0
0x7ff8156ec000 - 0x7ff815701fff  libc++abi.dylib  1300.23.0.0
0x7ff815702000 - 0x7ff815739fff  libsystem_kernel.dylib  8020.101.4.0  (WARNING: No symbols, libsystem_kernel.dylib, 26A59789B8463ED496DC8DBEF3C0C8E70)
0x7ff81573a000 - 0x7ff815745fff  libsystem_pthread.dylib  486.100.11.0  (WARNING: No symbols, libsystem_pthread.dylib, 2F6C275D7E143D31A924E1BB41D2415F0)
...
`

Who knows this? 
Thanks

**Comment by ostwindli** [comment]
Helper Wanted @rogerwang

**Comment by ayushmxn** [comment]
>  Use our mailing list for questions: https://groups.google.com/forum/#!forum/nwjs-general

I'm not too familiar with parsing `dmp` files but I think you'd get a faster response if you ask your question in the mailing list or [Gitter chatroom](https://gitter.im/nwjs/nw.js)
