### ISSUE TITLE
Request: use same default image rendering setting as chrome

### ISSUE THREAD

**Issue by boundmaidlea** [nwjs/nw.js#7924]
NWJS Version : Stable v0.64.0
Operating System : Windows 10

### Expected behavior

Scaled-down icons and other images look the same in NW.js apps as they do in the same app in chrome

### Actual behavior

instead of using `image-rendering: -webkit-optimize-contrast;` as the default value, selected when `image-rendering` is not specified or set to `auto`, NW.js uses `image-rendering: smooth;` aka `image-rendering: optimizeSpeed;` (both are interestingly not valid keywords for both actual chrome and the chromium engine of nw.js, and can therefore not even be seen in actual chrome at all) which makes downscaled icons very blurry. while it is an easy fix once i figured out what was the cause, doing so took me 2h.

### How to reproduce
Downscale an image with hight contrast lines to a value by which the original icon size can not be divided without remainder.

### Example:
Using icons with 48x48 pixels size in the file, scaled to 32x32px
NW.js default on the Left, Chrome default & NW.js with `image-rendering: -webkit-optimize-contrast;` on the right:
![image](https://user-images.githubusercontent.com/106570003/180820184-e3ea1784-7391-4df6-b8f5-e8b94facc401.png)
Same image in double size:
![image](https://user-images.githubusercontent.com/106570003/180821111-21660035-c2d0-4bce-aa32-442636a28329.png)

**Comment by ayushmxn** [comment]
Just so I understand, are you saying that NW.js sets `image-rendering` to `smooth` when it should set it to `-webkit-optimize-contrast`?

**Comment by boundmaidlea** [comment]
i am basically referring to what `image-rendering: auto;` results to in in the end, i don't know how the chromium engine works internally.

In chrome `image-rendering: auto;` = `image-rendering: -webkit-optimize-contrast;`, while in NW.js it results in rendering that seems to be similar to what `image-rendering: smooth;` should result in, even though actually specifying `image-rendering: smooth;` doesn't even work.

**Comment by boundmaidlea** [comment]
as i don't know if that difference is intentional or not, i also don't know if this is a bug report (if it is unintentional) or feature request (if it is intentional) :D

**Comment by ayushmxn** [comment]
I went through the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) and the [CSS spec](https://drafts.csswg.org/css-images/#the-image-rendering) which says that the initial value which is set to `auto` is "UA dependant" meaning that each browser has a different initial value set. I'll keep updating this as I learn more.

**Comment by ayushmxn** [comment]
Closing this since not sure how to proceed. Feel free to open another issue or add more clarification to the current one.
