### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING Since this morning without any modifications

### ISSUE THREAD

**Issue by ToHold** [nwjs/nw.js#7926]
NWJS Version : 0.66.1.0
Operating System : Windows 10

### Expected behavior

It just should give me datas from API, in JSON format.

### Actual behavior

I get 200 OK Http response but with this error "net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)".
It is certainly my fault, but it works well during more than 2 years. I haven't changed anything and this morning it tells me this. I can't understand. When I try my request on other browser or on postman it works well.

### How to reproduce
 Here's a part of the code :

```
       getCodificationsAsync(callback){  
		let _this = this;  
		callback = callback || function(){};  
		$.ajax({  
			method: "GET",  
			headers: {  
				'Authorization': `Bearer ${_this.core.user.token}`,  
			},  
			url: _this.core.api + "/getcodifications",  
			success: function(data){  
				let codifications = data;  
				codifications.forEach((codif,index) => {  
					if(isOldCodification(codif)){  
						codif = convertOldToNewCodification(codif);  
					}
					codifications[index] = codif;  
				});
				_this.codifications = codifications;  
				callback(codifications);  
			},  
			error: function(data){  
			}
		});  

		let isOldCodification = (codif)=>{  
			if(codif.colortables)  
			return true;  
			else  
			return false;  
		}  
		let convertOldToNewCodification = (codif) => {  
			let codifToConvert = codif;  
			let colorTable = codif.colortables;  
			let cellsToConvertColor = codifToConvert.content.filter(el=>el.type=="celldescr");  
			cellsToConvertColor.forEach((cell) => {  
				cell.entities.forEach((entity) => {  
					entity.color = getColorFromTable(colorTable,entity.color);  
				})  
			});  
			return codifToConvert;  
		}  
		let getColorFromTable = (table, color) => {  
			return table.content[color];  
		}  
	}  
```

I use nginx/1.18.0 for the server, Symfony 4.4.21 for the api and php-fpm7.4

Here's response headers : 

```
HTTP/1.1 200 OK
Server: nginx/1.18.0
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: max-age=0, must-revalidate, private
Date: Wed, 27 Jul 2022 09:24:26 GMT
Expires: Wed, 27 Jul 2022 09:24:26 GMT
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Permitted-Cross-Domain-Policies: none
```

**Comment by ToHold** [comment]
It works for another request. I am completly lost.

**Comment by ToHold** [comment]
Well I find a way to make it works. I just removed the "Transfer-Encoding" header from server's response. It works but I still can't understand why with the "Transfer-Encoding" set as "chunked" it doesn't work.

**Comment by bluthen** [comment]
Might be updated chromium is more strict about chunked encoding. Do you have similar issue in normal chrome browser?

**Comment by ayushmxn** [comment]
Maybe this can help your use case?
https://stackoverflow.com/questions/19907628/transfer-encoding-chunked

**Comment by ayushmxn** [comment]
This doesn't seem to related to NW.js. Closing this for now. Ping me here if you're able to pinpoint an issue!
