### ISSUE TITLE
Failing to compile node (error: expected '{' after '\$' escape sequence)

### ISSUE THREAD

**Issue by KanomiDim** [nwjs/nw.js#7935]
Error compile with latest nw67.

OS: Windows 10

$ ninja -C src/out/Release_x64 node
ninja: Entering directory `src/out/Release_x64'
[1/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\md4\openssl.md4_one.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[2/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\md5\openssl.md5_one.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[3/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.cversion.obj
FAILED: obj/third_party/node-nw/deps/openssl/openssl/crypto/openssl.cversion.obj
ninja -t msvc -e environment.x64 -- "..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl" -m64 /nologo /showIncludes /FC @obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.cversion.obj.rsp /c ..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c /Foobj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.cversion.obj /Fdobj\third_party\node-nw\deps\openssl\openssl.c.pdb
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(63,33): warning: unknown escape sequence '\ ' [-Wunknown-escape-sequence]
        return "OPENSSLDIR: \"" OPENSSLDIR "\"";
                                ^~~~~~~~~~
<command line>(32,32): note: expanded from here
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
                               ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(63,33): warning: unknown escape sequence '\ ' [-Wunknown-escape-sequence]
        return "OPENSSLDIR: \"" OPENSSLDIR "\"";
                                ^~~~~~~~~~
<command line>(32,47): note: expanded from here
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
                                              ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(75,33): warning: unknown escape sequence '\s' [-Wunknown-escape-sequence]
        return "MODULESDIR: \"" MODULESDIR "\"";
                                ^~~~~~~~~~
<command line>(30,36): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                   ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(75,33): warning: unknown escape sequence '\$' [-Wunknown-escape-sequence]
        return "MODULESDIR: \"" MODULESDIR "\"";
                                ^~~~~~~~~~
<command line>(30,40): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                       ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(75,33): error: expected '{' after '\$' escape sequence
        return "MODULESDIR: \"" MODULESDIR "\"";
                                ^~~~~~~~~~
<command line>(30,61): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                            ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(75,33): warning: unknown escape sequence '\l' [-Wunknown-escape-sequence]
        return "MODULESDIR: \"" MODULESDIR "\"";
                                ^~~~~~~~~~
<command line>(30,65): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                                ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\cversion.c(75,33): error: expected '{' after '\l' escape sequence
        return "MODULESDIR: \"" MODULESDIR "\"";
                                ^~~~~~~~~~
<command line>(30,69): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                                    ^~
6 warnings and 2 errors generated.
[4/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.trace.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[5/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\modes\openssl.cfb128.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[6/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\mdc2\openssl.mdc2dgst.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[7/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\modes\openssl.cbc128.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[8/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\mdc2\openssl.mdc2_one.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[9/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\md4\openssl.md4_dgst.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[10/1106] COPY ..\..\third_party\icu\windows\icudt.dll icudt.dll
[11/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\modes\openssl.ccm128.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[12/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.provider_core.obj
FAILED: obj/third_party/node-nw/deps/openssl/openssl/crypto/openssl.provider_core.obj
ninja -t msvc -e environment.x64 -- "..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl" -m64 /nologo /showIncludes /FC @obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.provider_core.obj.rsp /c ..\..\third_party\node-nw\deps\openssl\openssl\crypto\provider_core.c /Foobj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.provider_core.obj /Fdobj\third_party\node-nw\deps\openssl\openssl.c.pdb
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
..\..\third_party\node-nw\deps\openssl\openssl\crypto\provider_core.c(886,32): warning: unknown escape sequence '\s' [-Wunknown-escape-sequence]
                    load_dir = MODULESDIR;
                               ^~~~~~~~~~
<command line>(30,36): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                   ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\provider_core.c(886,32): warning: unknown escape sequence '\$' [-Wunknown-escape-sequence]
                    load_dir = MODULESDIR;
                               ^~~~~~~~~~
<command line>(30,40): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                       ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\provider_core.c(886,32): error: expected '{' after '\$' escape sequence
                    load_dir = MODULESDIR;
                               ^~~~~~~~~~
<command line>(30,61): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                            ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\provider_core.c(886,32): warning: unknown escape sequence '\l' [-Wunknown-escape-sequence]
                    load_dir = MODULESDIR;
                               ^~~~~~~~~~
<command line>(30,65): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                                ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\provider_core.c(886,32): error: expected '{' after '\l' escape sequence
                    load_dir = MODULESDIR;
                               ^~~~~~~~~~
<command line>(30,69): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                                    ^~
4 warnings and 2 errors generated.
[13/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\md5\openssl.md5_dgst.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[14/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.threads_win.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
1 warning generated.
[15/1106] CC obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.info.obj
FAILED: obj/third_party/node-nw/deps/openssl/openssl/crypto/openssl.info.obj
ninja -t msvc -e environment.x64 -- "..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl" -m64 /nologo /showIncludes /FC @obj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.info.obj.rsp /c ..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c /Foobj\third_party\node-nw\deps\openssl\openssl\crypto\openssl.info.obj /Fdobj\third_party\node-nw\deps\openssl\openssl.c.pdb
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
In file included from <built-in>:342:
<command line>(32,9): warning: 'OPENSSLDIR' macro redefined [-Wmacro-redefined]
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
        ^
<command line>(31,9): note: previous definition is here
#define OPENSSLDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib"
        ^
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(172,16): warning: unknown escape sequence '\ ' [-Wunknown-escape-sequence]
        return OPENSSLDIR;
               ^~~~~~~~~~
<command line>(32,32): note: expanded from here
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
                               ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(172,16): warning: unknown escape sequence '\ ' [-Wunknown-escape-sequence]
        return OPENSSLDIR;
               ^~~~~~~~~~
<command line>(32,47): note: expanded from here
#define OPENSSLDIR "C:\\Program\ Files\\Common\ Files\\SSL"
                                              ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(176,16): warning: unknown escape sequence '\s' [-Wunknown-escape-sequence]
        return MODULESDIR;
               ^~~~~~~~~~
<command line>(30,36): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                   ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(176,16): warning: unknown escape sequence '\$' [-Wunknown-escape-sequence]
        return MODULESDIR;
               ^~~~~~~~~~
<command line>(30,40): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                       ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(176,16): error: expected '{' after '\$' escape sequence
        return MODULESDIR;
               ^~~~~~~~~~
<command line>(30,61): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                            ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(176,16): warning: unknown escape sequence '\l' [-Wunknown-escape-sequence]
        return MODULESDIR;
               ^~~~~~~~~~
<command line>(30,65): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                                ^~
..\..\third_party\node-nw\deps\openssl\openssl\crypto\info.c(176,16): error: expected '{' after '\l' escape sequence
        return MODULESDIR;
               ^~~~~~~~~~
<command line>(30,69): note: expanded from here
#define MODULESDIR "C:\nwjs\nwjs671\src\$|CONFIGURATION_NAME\obj\lib\openssl-modules"
                                                                    ^~
6 warnings and 2 errors generated.
[16/1106] CC obj\third_party\node-nw\deps\histogram\src\histogram.hdr_histogram.obj
clang-cl: warning: argument unused during compilation: '-std:c++17' [-Wunused-command-line-argument]
..\..\third_party\node-nw\deps\histogram\src\hdr_histogram.c(143,23): warning: incompatible pointer types passing 'uint32_t *' (aka 'unsigned int *') to parameter of type 'unsigned long *' [-Wincompatible-pointer-types]
    _BitScanReverse64(&leading_zero, value);
                      ^~~~~~~~~~~~~
C:\nwjs\nwjs671\src\third_party\llvm-build\Release+Asserts\lib\clang\15.0.0\include\intrin.h(249,48): note: passing argument to parameter '_Index' here
unsigned char _BitScanReverse64(unsigned long *_Index, unsigned __int64 _Mask);
                                               ^
In file included from ..\..\third_party\node-nw\deps\histogram\src\hdr_histogram.c:18:
..\..\third_party\node-nw\deps\histogram\src/hdr_atomic.h(23,13): warning: unused function 'hdr_atomic_store_pointer' [-Wunused-function]
static void hdr_atomic_store_pointer(void** pointer, void* value)
            ^
2 warnings generated.
ninja: build stopped: subcommand failed.

**Comment by rogerwang** [comment]
There is `CONFIGURATION_NAME` in the log. So it's not properly configured. You'll need to check the config command line as well as environment variables.

btw, 
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by KanomiDim** [comment]
what does it mean?
where can i configure that parameter?
