### ISSUE TITLE
How to call garbage collector in NW app

### ISSUE THREAD

**Issue by JobAssistant** [nwjs/nw.js#7953]
There is no any explanation how to call GC in NW app. To do it in node js adding an --expose-gc flag will be enough. How to do it from NW app level, just calling global.gc() don't work.

**Comment by ayushmxn** [comment]
Please ask questions on [Gitter](https://gitter.im/nwjs/nw.js), [Google Group](https://groups.google.com/g/nwjs-general) or [Discord](https://discord.gg/tyx267vKRH).
