### ISSUE TITLE
NW.js Export Of Construct Game Graphical Glitch

### ISSUE THREAD

**Issue by hammanneric6** [nwjs/nw.js#7954]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
I use NWjs as an exporter for a game I am making in Construct 3.  I don't know that I expect an answer on this I'm just trying to figure out if anyone knows if this is NWjs because the Construct devs don't think its Construct.  I can verify that it isn't anything in the game.  Nothing in the game looks remotely close to the issue I'm seeing.

Below are screenshots that I got from a player.  There are large white or red rectangles that you can see in the screenshots that look like some sort of mesh.  Nothing in the game links to these as far as I can tell, they seem to be random and they are just stuck on the screen like some sort of dead zone.  They appeared after around 50 hours of play from what the player says.  I unfortunately don't have any sort of bug code or anything as even moving the saves to my computer results in no issues.

My best guess is that this would be hardware related because, as mentioned, it doesn't show on my computer.  According to the user they have an NVidia RTX 2060 and their drivers are up to date.  Other info on their system is below.  If anyone has an idea I'd appreciate any info but I understand there isn't a ton to go on.

### Additional Info

- Operating System: Windows 10
- NW.js Version: Version 0.60.0 (stuck on this version due to compatibility with construct)
- Repro Link:
- Code snippet:
- Crash report:

![20220821071619_1](https://user-images.githubusercontent.com/11020190/186545084-519c9d83-ccb1-45ae-9695-b3d9075c0c47.jpg)
![20220821071532_1](https://user-images.githubusercontent.com/11020190/186545088-bfdcc75d-fa95-4147-9027-9f02008169bc.jpg)

**Comment by ayushmxn** [comment]
This is definitely hardware related. I'm out of my depth here but maybe changing some chromium flags could help?
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by frank-dspeed** [comment]
for me that looks like you got a error message that is overlayed your game dev so i will talk game dev slang or at last try it. I am chromium engineer. We use FrameBuffers to draw so the result of the screen is the result of a Image that gets written to the Buffer of your Graphics Card Directly. 

So Far so good we see the rectangle we know it gets drawn and overwriten at last this looks exactly like that. 

it looks like the message gets rendered but then some shader processes it and thats why it is so obscured

**Comment by ayushmxn** [comment]
Thanks for the explanation but you left out the conclusion. If I understand correctly it is a bug in Google's ANGLE library or the relevant downstream GL library.

**Comment by frank-dspeed** [comment]
@ayushmxn it must not be angel related i expect even something more evil deep inside anywhere in the data pipe lines.
to debug that we would need to run the game with transperent graphics :) so that it simply does what it does but it should not render the output so that we see what is inside that message. 

We can also if that is not possible use the devtools combined with a special build that exposes the MOJO:IPC transactions that are used to transfer the data internal from one process to a other inside chromium if that runs for example on windows there is:

https://github.com/tomer8007/chromium-ipc-sniffer

**Comment by frank-dspeed** [comment]
## Conclusion 
I do not think that this is a real bug it is simply something that did not show up before but was there before.

The new rework to a more raw graphics layer exposes that. There is something wrong in the game code but we can not see it without going deeper but the problem domain is not nwjs or chromium while sure we can fix that also there and workaround that. 

The root cause is in the game.

**Comment by ayushmxn** [comment]
https://github.com/nwjs/chromium.src/issues/156
@frank-dspeed Looks like you have experience with Chromium, would you be open to fixing NW.js bugs? Also whenever you get the time could you looks into this? It's preventing me from working on NW. I think I've narrowed down where the error could be occurring but still haven't found a fix.

**Comment by frank-dspeed** [comment]
@ayushmxn i lead the whole LaCroOS Effort at present i am refactoring the builds of over 1000 Repos at once via codemods. NWJS will not exist anymore soon. Over the Years we created indipendent projects like Project Fugu to port stuff directly into the core and now with the new build system finaly we will be able to Fix everything fast.

**Comment by hammanneric6** [comment]
@frank-dspeed 
Hello,

Sorry I'm late to reply here, the last few days have gotten away from me.  I wanted to say thank you for looking into this.  It sounds like you have a lot on your plate so I appreciate you taking the time to consider this problem, I know its small in the grand scheme of things.

I wish I had more info I could give but I can't seem to reproduce it on my machine unfortunately.  It could potentially be something in the game but, well, to be honest I've been working on this project for a few years.  I'd guess I have a fairly intimate knowledge of what every single sprite looks like, and there's nothing like that that I can think of.

I would not be surprised however if it was somehow something in the game, just confused as to how it could be.  My thought was more similar to your first one where there was something wrong with the rendering but I am 100% not an expert on that sort of thing.  I just posted this on the off chance someone would look at it and be like "oh yes, that, I know what that is"

In any case, you mentioned something that caught my eye.  The program I use to make this game is Construct 3, which has an exporter that is NW.js to wrap the game into a Windows application.  You mentioned that NW.js isn't going to be around much longer.  I feel I'm out of my depth here, but is this Project Fugu, or LaCroOS something that is going to replace it?

**Comment by frank-dspeed** [comment]
@hammanneric6 you do not understand me fully let me give you some pseudo code 

```
const rectangleWeCallItGlitch = {} // is a Error Message from chrome rendered under the zindex of the sprite i do not know why it is at all rendered. 

const your tileWritingPipeline = {} // Something that schuffels sprites and renders them but also applys some kind of lighting effect on the sprites or the canvas

const someTotalDiffrentCodeElseWhere = {} this object is causing the rectangleWeCallGlitch but we do not know its content we only see that what we call glitch and because of position and shape we can guess that this is a nativ system message

```

## Mysterie left
- What is the content of the message
- What is causing the Message
- Why does it appear there on such a spot like a canvas where we write tiles too
  - maybe this screenshot shows a fullscreen representation and simply some thing total external from the game writes to the framebuffer of the system?


## Low Level Graphics details
The Graphics Card reads a file or reference to a FrameBuffer which contains a single picture (everything you see on screen) many applications can write to parts of that buffer or file to modify the picture and so modify what is on the display

something writes the system message and after that something clear applys a effect over that and thats why we call that glitch.

**Comment by frank-dspeed** [comment]
@hammanneric6 about Project Fugu and replacing NWJS yes NWJS is already replaced 

The Concept of it was needed because we had no Real Way to easy Connect a Platform Related Host to a Running Browser that creates a Window as we define it. 

and your wrapping program is maybe the cause of the Error Message that construct 3 is the reason not chromium.

For your game for example i would suggest you to switch as soon as Possible as you Package it to:

WPEWebkit with the gstreamer backend

https://github.com/WebPlatformForEmbedded/WPEWebKit

This is like NWJS a Isolated Content Module based on Webkit Chromium is also based on WebKit but we wrapped it and renamed it to blink which is the rendering engine under the content module which is what is used in NWJS 

You can save your self a lot of time and trouble when you switch to WPE + gstreamer backend + nodejs also using the gstreamer backend

thats the most solid WebDriven App platform that would run also on embedded.

If you want it compatible then use Puppeteer for example then launche a window with it and then connect content scripts to it via 
```js
page.evalFunction(()=>{
  // you can access the browser dom here from nodejs
})
```

so you could bundle your app as single nodejs app + puppeteer.

**Comment by frank-dspeed** [comment]
## For People who come new to the issue
This issue talks about Embedded Game Development if you want to produce something that runs on the web use puppeteer.

infos for embedded development with the new WPEWebKit https://wpewebkit.org/

**Comment by hammanneric6** [comment]
@frank-dspeed 
Thanks for explaining.  I think I get what you mean, its a bit past my expertise, or maybe a lot past honestly, but I appreciate it nontheless.

As for your other point, you are referencing this WPEWebkit.  I wanted to ask you one more question.  I think I already know the answer but I'm curious because I'm out of my depth.  Construct 3 basically has exporters that it allows you to use.  NW.js was the choice for, well, since I can remember.  In the list of exporters I don't see WPEWebkit.  I do however see one called WebView2.  The exporter has a help link that links to this page: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Based on what you linked I'm assuming that isn't the same thing you are talking about right?  I ask because I'd be willing to try changing exporters but that obviously comes with its own host of potential issues so I wanted to know if it would even make sense to switch.  From what I can tell this WebView2 also runs off chromium so I don't know that it would change anything.

**Comment by frank-dspeed** [comment]
@hammanneric6 what are the real targeted machines? Windows PC? Window and Linux?

**Comment by hammanneric6** [comment]
@frank-dspeed 

Well, its windows, mac, and linux.  Construct has WebView2 for windows OS, WKWebView for MacOS and then I guess I'd have to just keep using NW.js for linux because neither of the others support it.  I was just curious if that WebView2 was the same or some slight variation of the one you were talking about.

**Comment by frank-dspeed** [comment]
@hammanneric6 if your interrested you can publish your nwjs build some where and send me a link i can then extract the game from there. and Create a export for newer formats

**Comment by hammanneric6** [comment]
@frank-dspeed 

Nah that's okay I couldn't ask you to do that.  Not to mention the game is in early access, it would be an ongoing series of exports, thanks though.

**Comment by frank-dspeed** [comment]
@hammanneric6 lol i was asking for that because i would create a tool to do that but i need to know the structure thats why i would need one time the package from you i do not know how constructor 3 exactly produces its results

i would fast reverse engineer that and write a small js script that you can then use with any constructor 3 NWJS export

**Comment by hammanneric6** [comment]
@frank-dspeed 
Sorry, the rest of Sunday sort of blew past me.  Maybe I missed something, what would be the benefit of this exporter you would make?  Would it fix the above issue or just be better or something?

**Comment by frank-dspeed** [comment]
@hammanneric6 it would allow you to rexport it in newer environments that are not listed under current packaging methods.

I am not a constructor 3 user but what i saw in the first place was:
- Its a online editor
- allowing to do pre defined exports one is NWJS
- it will not give you raw source code to work with

so i tought it would be cool to create a constructor 3 extractor that allows you to repackage and even rexport your project to other platforms and this way you can fix bugs and everything else.

**Comment by hammanneric6** [comment]
@frank-dspeed 

Hello, hmm thanks for the offer but I think I'm okay.  The offer is interesting but I've got my hands full just making the game.  Managing exports in a more hands on fashion is probably more than I can handle.  Aside from that there is stuff built into the game engine that interacts with Steam and the OS in general that is relying on parts of NW.js so I'm not sure how much I could really change before I just break something.

Thanks though, I appreciate you spending the time and answering the questions I had.

**Comment by frank-dspeed** [comment]
Ah your welcome and sure you can always change anything it is code 👍🏻
