### ISSUE TITLE
slow loading first time each day  then fast

### ISSUE THREAD

**Issue by xthdraft** [nwjs/nw.js#7956]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ ] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Additional Info

- Operating System:
- NW.js Version:
- Repro Link:
- Code snippet:
- Crash report:

**Comment by xthdraft** [comment]
I'm using v63.  When I load my app for the first time in the day, the app takes several seconds to load.  After that it takes about 1 second.  The next day, first load takes several seconds, then subsequent loads 1 second.  Next day, same behaviour, etc
I'm guessing its a cache issue.  Any suggestions to make the cache extend to more than a single day? Thanks.

**Comment by bluthen** [comment]
Are you on MacOS arm?

**Comment by xthdraft** [comment]
Windows 10  i7 laptop.  Loading nw.js by itself takes approx 12 seconds on
first load of day, then repeated loads from cold boot takes 1 second.  Each
day this behaviour repeats.

**Comment by bluthen** [comment]
I tried on a windows 10 I never ran nwjs on and it took less than a second. Is it your antivirus scanning it maybe, or what nwjs is doing?

**Comment by LiamPruditsch** [comment]
Another possibility would be that your project has circular dependencies that are resolved before the window opens. I once had about 30 of them in my project and it took about 7 seconds the first time.

**Comment by xthdraft** [comment]
Following advice from bluthen, I changed some setting in windows defender.
Allow app through firewall > Virus & threat protection > Add to exclusions : I added  the folders which use nw.js app and the apps now load instantly.   Thanks  for all advice.
