### ISSUE TITLE
On macos NWjs crashes after attempt to reopen fullscreen window with specified width( or height)

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7964]
- Operating System: macos
- NW.js Version: 0.68

### How to reproduce

**main.html**
```
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Demo</title>
</head>
<body>
	<button id="open">Open</button>
<script>
document.getElementById("open").addEventListener("click",function(){
	
	nw.Window.open("https://google.com",{
		id:"open2",
		width:~~(screen.width/4*3)
	});
});
</script>
</body>
</html>
```

**package.json**
```
{
	"main": "/main.html",
	"name": "demo",
	"nodejs": "false",
	"chromium-args": "--enable-spell-checking"
}
```

**Steps:**
0. Run application on macos.
1. Enter fullscreen (green button).
2. Press "Open" button.
3. Enter fullscreen mode (green button) in opened window (google.com).
4. Close opened window (google.com).
5. Press "Open" button again.
6. ??? NWjs crashed...

**Comment by adityatoshniwal** [comment]
@rogerwang  this is happening for 0.78.1 as well. We're using latest NW.js in pgAdmin.

**Comment by akshay-joshi** [comment]
@rogerwang

Any update on this or an ETA? We have pinned the version to 0.77.0 in pgAdmin 4 and are unable to update the latest because of this issue.

**Comment by akshay-joshi** [comment]
@rogerwang 

Could you provide an update on this issue? We're currently unable to upgrade to the latest NWJs version due to this.
