### ISSUE TITLE
BUG: Event 'open' stop works after once triggered

### ISSUE THREAD

**Issue by panther7** [nwjs/nw.js#7969]
* NWjs 0.66.1 - ok
* NWjs 0.67.1 - ok
* NWjs 0.68.1 - fail

Windows 11 22H2 (22622.601) x64

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Demo</title>
  </head>
  <body>
    <script>
      nw.App.on('open', (params) => {
        console.log(params);
      });
  
      setTimeout(() => nw.Window.get().showDevTools(), 100);    
    </script>
  </body>
</html>
```

**Comment by panther7** [comment]
Maybe again as #7860.

@rogerwang

**Comment by panther7** [comment]
Hmmm... roger, you did deleted line after merge chromium 105 ...mistake?

![2022-09-22 16 06 10](https://user-images.githubusercontent.com/3808250/191768930-d01f9e40-78ba-43d6-94e8-ccc5e56d238a.png)

**Comment by rogerwang** [comment]
Thanks for finding this. Some modifications were left behind when upgrading to Chromium 105. Will apply them all.

**Comment by ayushmxn** [comment]
I understand that. My question is are the list of modifications saved somewhere or do you know them by memory (trying to understand the codebase)?

**Comment by rogerwang** [comment]
It's a single big master patch. You can get it by comparing NW with the upstream.
