### ISSUE TITLE
How to change contents of navigator.userAgentData.brands?

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#7970]
In regular chromium* browsers property `navigator.userAgentData.brands` has 3 items, but in NWjs it has only 2. And that's the way how sites could detect that they are run in NWjs environment.  So how to such behaviour?

**Comment by metallizer75** [comment]
Some sites with cloudflare protection do not pass captcha with nw.js. I think the problem is just in userAgentData.brands. Need to add  the ability to change this array, or at least do the same values as chrome gives out.

**Comment by tharatau** [comment]
Please ask questions in the mailing list, thanks!

**Comment by Sunvas** [comment]
Discussion on google groups https://groups.google.com/g/nwjs-general/c/s2yXqfsKXhE
