### ISSUE TITLE
how to create nwjs contextmenu on website system  following mouse click

### ISSUE THREAD

**Issue by linkaimeng** [nwjs/nw.js#7986]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
i have  a website system running well,i would like to create contextmenu(no menubar) above this website system following mouse click,ican't find the way out.
### Expected/Proposed Behavior
i can using nwjs packaging this website system and create contextmenu above this website system following mouse click.
### Additional Info

- Operating System:win10 
- NW.js Version:0.69.1
- Repro Link:
- Code snippet:
- Crash report:

**Comment by ayushmxn** [comment]
https://nwjs.readthedocs.io/en/latest/References/Menu/
There's an example of how to create a Menu in the docs. Closing this for now. Post here if you have any problems and I'll reopen the issue!
