### ISSUE TITLE
MacOS - latest 0.70.0 not launching on M1 12.6 - unsupported

### ISSUE THREAD

**Issue by Blatman** [nwjs/nw.js#7988]
- Operating System: Monterey 12.6 
- NW.js Version: 0.70.0
- Hardware: MBPro M1 running Rosetta

Latest 0.70.0 sdk and normal builds for Mac are showing as unsupported. 0.69.1 was fine.

<img width="503" alt="notsupported" src="https://user-images.githubusercontent.com/11089335/198291976-ae67069f-7baa-4dc6-9ed8-d5a95a5ef8cb.png">

**Comment by rogerwang** [comment]
Thanks for reporting! This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
