### ISSUE TITLE
nw.js scrollbar dosen't work

### ISSUE THREAD

**Issue by linkaimeng** [nwjs/nw.js#7992]
### Current/Missing Behavior
 i using nw.js warp up a web system，nw.js scrollbar dosen't work, dosen't show scrollbar  to let user to drag.

my nw.js package.json is :
![image](https://user-images.githubusercontent.com/2948213/199385337-043acadf-cacf-4288-8371-2d222c3e2d33.png)

### Expected/Proposed Behavior
i expect nw.js can spupport scrollbar 
### Additional Info

- Operating System:
- NW.js Version: 0.69.1
- Repro Link:
- Code snippet:
- Crash report:

**Comment by vankasteelj** [comment]
I do have a scrollbar. Does your page have an html element that is bigger than 1024*768? Because if behaves the same as a web navigator, so if there is no content to scroll to, it won't show you a scrollbar
