### ISSUE TITLE
Read files with nw.exe

### ISSUE THREAD

**Issue by AndresQuiVal** [nwjs/nw.js#7995]
@I'm trying to develop a node.js app that reads from a file outside of the main project directory, said that, for instance, the folder structure is as this, and the file that reads the file is `index,js`

```
./project
    ....
    index,js
    package.json
    ....
```

and the directory which contains the folder is like this

```
./some-parent-directory
    /project
    data.json
```

therefore the project should read the contents of the file, WHICH NOTE, the contents are dynamic, therefore it cant be packed inside the `package.nw`

Now, when packing the files and folders of the project within the .zip folder, and renaming it as `package.nw`, putting it inside the `nw.exe` directory, and finally creating inside the `nw.exe` directory the file named `data.json` the app seems not to read the contents of the file, is that beacuse of permissions of the app, or how can i solve it?? thanks

**Comment by tharatau** [comment]
'``
"node-remote": [ "file://*" ]
```
Have you tried adding this^ in your `package.json`?

**Comment by tharatau** [comment]
Please ask questions on the mailing list.
