### ISSUE TITLE
weird url / file not found errors

### ISSUE THREAD

**Issue by indexofrefraction** [nwjs/nw.js#7997]
i'm getting strange url / file not found errors for seemingly random files

requests like "data.xml" result in
chrome-extension://hnmfddijdnakoibnaaoaaidoiplfbagp/index.html/data.xml
instead of :
chrome-extension://hnmfddijdnakoibnaaoaaidoiplfbagg/data.xml

my app can't even start due to these errors
any ideas ?

edit : I sometimes also get " Aw, Snap! Error Code 5 " ... with immediate crashes

**Comment by tharatau** [comment]
@indexofrefraction could you provide steps to reproduce or code snippets?
