### ISSUE TITLE
Specify architecture for `Downloads` in README.md.

### ISSUE THREAD

**Issue by rafrafek** [nwjs/nw.js#7999]
> ## Downloads
> * **v0.70.1:** (Nov 3, 2022, based off of Node.js v19.0.0, Chromium 107.0.5304.88) : [release notes](https://nwjs.io/blog/v0.70.1/)  
>  **NOTE** You might want the **SDK build**. Please read the release notes.
>  * Linux: [32bit](https://dl.nwjs.io/v0.70.1/nwjs-v0.70.1-linux-ia32.tar.gz) / [64bit](https://dl.nwjs.io/v0.70.1/nwjs-v0.70.1-linux-x64.tar.gz)
>  * Windows: [32bit](https://dl.nwjs.io/v0.70.1/nwjs-v0.70.1-win-ia32.zip) / [64bit](https://dl.nwjs.io/v0.70.1/nwjs-v0.70.1-win-x64.zip)
>  * Mac 10.10+: [64bit](https://dl.nwjs.io/v0.70.1/nwjs-v0.70.1-osx-x64.zip)
>  * Use [Legacy build](http://nwjs.io/downloads/) for Win XP and early OSX.

Please specify architecture e. g. `x86`, `amd64`, `armv7`, `arm64` etc. for _Downloads_ in README.md.

**Comment by tharatau** [comment]
Feel free to open a PR

**Comment by rafrafek** [comment]
Are all downloads x86 (`x86` / `amd64`)? Or are there any arm builds available?

**Comment by tharatau** [comment]
All official builds are amd (ia32/x64). There is an unofficial build for [Linux ARM](https://github.com/LeonardLaszlo/nw.js-armv7-binaries/) and [MacOS ARM](https://github.com/corwin-of-amber/nw.js/releases).
