### ISSUE TITLE
Mobile emulation?

### ISSUE THREAD

**Issue by metallizer75** [nwjs/nw.js#8001]
Is there a way to enable mobile device emulation on nwjs? May be via command line chrome swithces or programmatically. 
I did not even find a manual way to turn it on - nwjs devtools don' have a toggle device button.

**Comment by tharatau** [comment]
https://chromedriver.chromium.org/mobile-emulation
I haven't tried this out I you maybe be able to use the `chromedriver` from the SDK build.

https://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Test%20with%20ChromeDriver/
There will be some NW specific changes to be made. The docs may be out of date so let me know if you run into any problems.
