### ISSUE TITLE
The srv2022x64 runs abnormally

### ISSUE THREAD

**Issue by bigMuster** [nwjs/nw.js#8002]
When running nwjs on srv2022x64 system, the message "Cannot open your profile properly. Some functions may not be available. Please check that the personal data exists and that you have the right to read and write its contents."

- Operating System:
- NW.js Version:v0.14.7-win-x64

**Comment by tharatau** [comment]
Trying running the latest version. Do you have a specific reason to use v0.14.7? Closing until more information can be provided.
