### ISSUE TITLE
Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked

### ISSUE THREAD

**Issue by mariodiciccio** [nwjs/nw.js#8005]
How can i remove this?
I add to chromium-args in package.json --disable-blink-features=BlockCredentialedSubresources, but don't works.

"chromium-args": "--disable-blink-features=BlockCredentialedSubresources"

Any ideas?

Thank you very much, please, help me!! 

- Operating System: MacOS 11.7
- NW.js Version: 0.48.4

nwjs message:
[Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.
index.html:22 GET http://user:pass@192.168.1.1/cgi-bin/snapshot.cgi 401 (Unauthorized)

**Comment by tharatau** [comment]
https://github.com/whatwg/fetch/pull/465#issuecomment-779643387
There might be a way around it as mentioned in the comment linked above. I haven't looked into it too deeply but hopefully this helps!
