### ISSUE TITLE
How do I use load bin file in a pure NodeJS project

### ISSUE THREAD

**Issue by lincdh** [nwjs/nw.js#8007]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ √] Bug Report
- [ ] Feature Request

- [√ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
I run the app file-explorer cloned from https://github.com/zcbenz/nw-sample-apps with bin file generated with `--nw-module`. I try both `require("nw").Window.get().evalNWBinModule` and `require('nw.gui').Window.get().evalNWBinModule`, the app does not load `folder_view.bin`

![Screen Shot 2022-12-18 at 17 25 15](https://user-images.githubusercontent.com/21136244/208293208-fe9f1a57-69d0-4235-85cf-91cad1f0a9a3.png)

### Expected/Proposed Behavior

The app loads `folder_view.bin` and works like it loads `folder_view.js`.

### Additional Info

- Operating System: MacOS 12
- NW.js Version: ^0.71.0
- Repro Link:
- Code snippet:
- Crash report:

**Comment by tharatau** [comment]
The `nw-sample-apps` repo has not been updated in a while. This should be opened in that repo and not here. If it turns out to be an issue with the NW API, I'll reopen this.
