### ISSUE TITLE
Apple M2 is not supported?

### ISSUE THREAD

**Issue by Sunvas** [nwjs/nw.js#8009]
### Current/Missing Behavior

nwjs can't be run on Apple M2 . When I try run it via Finder nothing happens, but when I try run it via terminal command `open nwjs.app`  it shows an error:

`The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10669 "(null)" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}`

### Expected/Proposed Behavior
Application should be run.

### Additional Info

- Operating System: macos 13.1 (22C65)
- NW.js Version: 0.71.1

**Comment by tharatau** [comment]
Currently no. For Apple ARM related discussions see #7620.
