### ISSUE TITLE
Linux (Ubuntu): posix_spawn: Permission denied (13)

### ISSUE THREAD

**Issue by oxou** [nwjs/nw.js#8011]
### Issue Type

- [x] Bug Report
- [X] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior
NWjs does not even open.  
But calling `nw --version` does work.

### Expected/Proposed Behavior
Window opens with everything working as expected.

### Additional Info

- Operating System: Ubuntu 22.04.1 LTS
- NW.js Version: nwjs 108.0.5359.95
- Crash report: https://pastebin.com/cUwtx4bt

**Comment by tharatau** [comment]
Could you provide minimal steps to reproduce the issue? For example, when executing `./nw`, is there a `package.json` in your current working directory?

**Comment by oxou** [comment]
> Could you provide minimal steps to reproduce the issue? For example, when executing `./nw`, is there a `package.json` in your current working directory?

Issue occurs with or without `package.json`. The file is located in the same directory as `nw`
This issue also occurs on Ubuntu MATE, a different flavor of Ubuntu but nonetheless the same base OS.

Here's a video:

https://user-images.githubusercontent.com/102489121/209811363-069061ea-cca8-4046-8933-6bc996c0a939.mp4

**Comment by oxou** [comment]
I've tried to run `0.71.0` but even that fails.. I don't know what else to try.

**Comment by tharatau** [comment]
I can't find a `package.json` or a `package.nw` directory alongside the `nw` executable. The docs explain this here:
https://nwjs.readthedocs.io/en/latest/For%20Users/Package%20and%20Distribute/

**Comment by oxou** [comment]
Sorry but I have provided the video showcasing the problem.
The `package.json` file does exist, I showcased 2 cases: With and without the file.
The resulting error is the same, this exact configuration works flawlessly on Windows platforms.

**Comment by tharatau** [comment]
What does the `package.json` look like? That will help me reproduce.

**Comment by oxou** [comment]
> What does the `package.json` look like? That will help me reproduce.

https://github.com/oxou/concept-nurki-browser/blob/main/package.json

**Comment by oxou** [comment]
Though this issue occurs without package.json. Even a clean base of NW.js is crashing.

**Comment by tharatau** [comment]
Based off the error message `posix_spawn: Permission denied`, have you tried `sudo ./nw`?

**Comment by oxou** [comment]
@tharatau While not shown in the video above, I have tried that beforehand and the issue persists.  I'll see if I'm able to investigate manually through some debugging tools in Linux.

**Comment by oxou** [comment]
I'm closing this issue as the problem seems to have been resolved:
- Operating System: Ubuntu 22.04.2 LTS
- NW.js Version: nwjs 111.0.5563.65

![2](https://user-images.githubusercontent.com/102489121/226104564-e3cd26aa-969c-4151-952f-4d976ad9789e.png)
