### ISSUE TITLE
Mac OS “nwjs” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by wktdev** [nwjs/nw.js#8014]
I am on Mac Mini Monterey OS

When I try to open nwjs I get the error: 

`“nwjs” cannot be opened because the developer cannot be verified.`

How do I fix this?

**Comment by wktdev** [comment]
I was too quick to post.

I needed to go to:  nwjs.app/Contents/MacOS/nwjs. instead of launching the icon.

Very confusing

**Comment by bluthen** [comment]
NWJS isn't meant to be used by end users itself but as to become part of your own app. If you ever distribute your app based on nwjs on MacOS you'll need to sign and notorize it.
