### ISSUE TITLE
Mac OS prevent mouse gesture (navigation, zoom...)

### ISSUE THREAD

**Issue by NicoLB22** [nwjs/nw.js#8015]
Hello,

This is not an issue reporting but a question.
After a quite long search I still can't figure out how to prevent the default OSX magic mouse gesture.
Is there a way to disable the window navigation and zoom made from the swipe on the Mac OS mouse ?

I tried javascript solutions with the different wheel and scroll events but without success.

Thanks a lot for your help.

### Additional Info

- Operating System: MacOS High Sierra (10.13.6)
- NW.js Version: 0.64.0
- Web framework: Angular 13.3

**Comment by tharatau** [comment]
I'm not sure if this is NW.js related - could be related to MacOS settings?

cc @sysrage

**Comment by NicoLB22** [comment]
Thanks for your reply.
I tried to find some informations about this, even on Apple Developer forum and Electron community, but I didn't find any answer. I've also inspected some Electron Apps that seems to prevent this feature but without success...
It does not seem that there is some plist properties about this or chromium args (the `--disable-pinch` has no effect for this).

**Comment by tharatau** [comment]
Maybe try telling your use case. That may help in coming up with a solution?

**Comment by tharatau** [comment]
I'm closing this. Try asking on the mailing list, Gitter or Discord.
