### ISSUE TITLE
Open the resource manager interface, the cancel button is displayed in English, but the system is in a Chinese environment

### ISSUE THREAD

**Issue by dingpeiyang** [nwjs/nw.js#8026]
nw.js version： 0.14.7
operating system ：Linux
![image](https://user-images.githubusercontent.com/48374209/218388723-4d88cd2a-c0b1-4913-ac9d-e08a981ca885.png)

**Comment by tharatau** [comment]
Does not seem to be related to NW.js. My guess t is to do with the language settings of VMWare.
