### ISSUE TITLE
How do you know if you're running in a nw environment in the page after the location.href jump

### ISSUE THREAD

**Issue by yf339339** [nwjs/nw.js#8028]
How do you know if you're running in a nw environment in the page after the location.href jump

- Operating System: windows 10
- NW.js Version:  0.14.7

**Comment by tharatau** [comment]
You can check for the `nw` global variable:
```javascript
if (nw) {
 // your code
}
```

**Comment by yf339339** [comment]
thanks，It doesn't work，I use location.href in app.html to jump to another website that I want to determine if it runs in the nw environment

**Comment by bluthen** [comment]
> thanks，It doesn't work，I use location.href in app.html to jump to another website that I want to determine if it runs in the nw environment

Do you have node-remote set in package.json?

**Comment by yf339339** [comment]
thanks，not set，let me set it up and try it

**Comment by tharatau** [comment]
Closing this, llease use the mailing list for questions.
