### ISSUE TITLE
NW.js 0.73.0 stopped working in Windows 7

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#8029]
I tested this on Windows 7 (64-Bit). Tested with NW.js 32 and 64-bit releases (Normal and SDK). All 4 had the same issue on launch:

> The procedure entry point SetProcessMitigationPolicy could not be located in the dynamic link library KERNEL32.dll.

![error](https://user-images.githubusercontent.com/4629794/220155640-6f53f875-16e7-4f13-8c99-95ae388ed75f.png)

This was initially reported by a user on Discord: NotCl4y.

## Additional Info

* **Operating System:** Windows 7
* **NW.js Version:** 0.73.0
* **Repro Link:** Just download, extract, and double-click `nw.exe`
* **Crash report:** No crash report generated

**Comment by TheJaredWilcurt** [comment]
I assume Chromium or Node.js is looking for SetProcessMitigationPolicy. According to [its documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setprocessmitigationpolicy), it was added in Windows 8.

@rogerwang

**Comment by tharatau** [comment]
Chromium 110 dropped support for Windows 7

**Comment by rogerwang** [comment]
> Chromium 110 (NW.js v0.73.x) dropped support for Windows 7

That's right. Thanks
https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023?hl=en
