### ISSUE TITLE
Unchecked runtime.lastError: Invalid value for bounds. Bounds must be at least 50% within visible screen space.

### ISSUE THREAD

**Issue by mobljs** [nwjs/nw.js#8031]
windows 10 , nwjs 0.68.1 , 

I want to move the window , either by win.moveTo( ) win.moveBy( )  win.x = num , I can not move the window to the right (bigger than half of the screen).

**Comment by tharatau** [comment]
Could you provide a code snippet? I was unable to reproduce.
