### ISSUE TITLE
Disable Autofill Address Save Prompt

### ISSUE THREAD

**Issue by skylarmt** [nwjs/nw.js#8038]
After updating NW.js, my app sometimes pops up a notification asking if I want to save the address I just typed in. I need this to not happen, but I can't find a Chromium flag for disabling it.

### Additional Info

- Operating System: Linux
- NW.js Version: 0.73.0

**Comment by tharatau** [comment]
Without any sample code I can't help much. Try using the autocomplete attribute for input fields. If you find there is a bug, ping me here and I'll reopen this.
