### ISSUE TITLE
User is not able to launch 0.74.0 NW.js on Windows 2012R2 and Windows 8.1.

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [nwjs/nw.js#8041]
- Operating System:
Windows 8.1 64 and Windows 2012 R2 64
- 0.74.0 NW.js Version:
- Build
https://nwjs.io/downloads/

We use nwjs for pgAdmin4 community and I checked that we could not launch pgadmin4 on Windows 2012R2 and Windows 8.1.
And After investigation, we have observed that the same issue is also reproducible on the nwjs build.

<img width="592" alt="Screen Shot 2023-03-17 at 12 01 00 PM" src="https://user-images.githubusercontent.com/43006122/225835114-934f5d8e-795d-4598-b7e0-4de73762cd2d.png">
<img width="1787" alt="Screen Shot 2023-03-17 at 11 48 30 AM" src="https://user-images.githubusercontent.com/43006122/225835200-b0fccca4-03d5-421c-b949-6e5badc4e82b.png">

**Comment by rbfowler9lfc** [comment]
Most probably related to Chromium 110 dropping support for Windows 7, 8.x and Server 2012, see Roger's comment: https://github.com/nwjs/nw.js/issues/8029#issuecomment-1437423422

**Comment by rogerwang** [comment]
Thanks. Yes, they are not supported by Chromium anymore.
