### ISSUE TITLE
Tooltip not not displaying on menu items

### ISSUE THREAD

**Issue by djmisterjon** [nwjs/nw.js#8042]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
tooltips show nothing after x delay mouse hover a item menue

### Expected/Proposed Behavior
should show a tooltip on any items ! 

### Additional Info

ex:
```ts
  const item = new nw.MenuItem( {
        tooltip: 'blabla',
    } );
```
tested on **normal** item but also **checkbox** ! 
![image](https://user-images.githubusercontent.com/24865815/226138521-2bdcb13e-186f-4b4a-b8ae-8537084e33ea.png)

--- 

![image](https://user-images.githubusercontent.com/24865815/226138672-7f76b2c4-838e-48e2-9d1f-2ba379666e58.png)

**Comment by TheJaredWilcurt** [comment]
You marked this as a bug, what was the last version of NW.js in which this feature worked?

Can you make a minimal version of some code where the feature works in one version of NW.js, but not in the latest. (MinRepro)

**Comment by djmisterjon** [comment]
> You marked this as a bug, what was the last version of NW.js in which this feature worked?
> 
> Can you make a minimal version of some code where the feature works in one version of NW.js, but not in the latest. (MinRepro)


repro step:
- open a instance of nwjs (sdk)
- open the chrome devtool
- paste
```ts
let m = new nw.Menu();
m.append( new nw.MenuItem({ label: 'Item A', tooltip:'info' }) );
m.popup( 0, 0 );
```

- bring your mouse hover the item of the ctx menu juste poped and wait min ~1000 ms.

for last worked version idk sorry! first time i use this field.
Seem no issue related before, only for tray icon, and have not time to test whole !200 versions avalables.

**Comment by djmisterjon** [comment]
![image](https://user-images.githubusercontent.com/24865815/226146550-3fe90383-0496-4344-91f8-3220d1f335a7.png)
