### ISSUE TITLE
IsolatedSandboxedIframe doesn't work at nw.js 

### ISSUE THREAD

**Issue by desruptor** [nwjs/nw.js#8053]
### Issue Type

I have a trouble with launching iframe using sandbox property via NW.
i have main page. it includes a child page as out-of-process-iframe(oopif):
```
<iframe src="index-child.html" sandbox="allow-scripts"></iframe>
<script>
    setInterval(() => {
        console.log("main iterate once");
    }, 1000)
</script>
```
child page:
```
<script>
    setTimeout(() => {
        console.log("child do the work");
        while (true) {
        }
    }, 3000)
</script>
```
I have added the launching args of NW with '--enable-features=IsolateSandboxedIframes' 
I have checked this is working decision at chrome: when the child frame is started its work the main page is not locked.
But when i try to launch it with NW the main page emits several times console.log and then it stucked when the child frame start its while cycle.

### Additional Info

- Operating System: ubuntu\windows
- NW.js Version: 0.68.1 and higher

**Comment by tharatau** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/14110965/233710759-e9444657-24d3-4cad-8bc3-b2a2e7284685.png)
 Works for me on 0.75.0 (tested on Windows and Linux)
