### ISSUE TITLE
Windows Defender flagged nw.exe as Trojan:Win32/Doplik

### ISSUE THREAD

**Issue by andreescocard** [nwjs/nw.js#8054]
### Current/Missing Behavior

After download finishes Windows Defender pops a message showing threats were found.
Virus total flags as virus too: https://www.virustotal.com/gui/file/4906524473eb3f7b530d4993906f4418141aba025dced23a4f541ddd110769ec

### Expected/Proposed Behavior

Windows Defender not flagging executable as trojan.

### Additional Info

- Operating System: Windows 11 Pro
- NW.js Version: nwjs-v0.74.0-win-x64.zip

**Comment by ElPrudi** [comment]
Same here on Windows 10. Cant build anything with [nw-builder](https://github.com/nwutils/nw-builder) without Windows Defender automatically deleting the executable.

**Comment by rogerwang** [comment]
This is a false positive in Windows Defender.

**Comment by ElPrudi** [comment]
Yes, but this shouldn't be a thing at all. I can't make apps build on nw.js if user have to specifically allow it to run, or in my case download it again because Windows Defender automatically deletes the executable.

**Comment by bluthen** [comment]
How to control, what malware/antivirus programs want to do?

I think some malware writers use things like nwjs, python, pyinstaller, node, and other open source software. In turn sometimes the signatures for those end up in the vendors database and legit software ends up getting flagged.

1. The software I work on we give instructions to whitelist our software for different antivirus/malware detectors.
2. Make sure our executable/installer are signed.
3. If particular complaints keep coming up, we try to submit our app as something unfairly detected to the vendor of the antivirus/malware.

But also see comments in #7725 #6507 #5457 #4023 #3946 #7418

**Comment by jssuttles** [comment]
I ran into this today. Windows Defender removed my entry point html file.
![image](https://user-images.githubusercontent.com/8527741/231628017-30c06d59-57fe-43b6-8032-fbe6bc221a23.png)

**Comment by anker9** [comment]
Looks like u ar' tryin' to put zipped sources into nw.exe. and then run nw.exe
It's really 'fine' malware tactic - put self-data to normal .exe, so WD triggered((
Btw i have same issue)))) In dat case i 'solved' this just using Enigma Virtual Box from  nwjs docs

**Comment by tharatau** [comment]
https://github.com/nwjs/nw.js/issues/8054#issuecomment-1497841550

**Comment by ElPrudi** [comment]
Really? Just randomly close it?

Damn, this is getting more and more hilarious.

**Comment by bluthen** [comment]
What is a better solution @ElPrudi ? I don't like things getting flagged either, but again, how do you control what those vendors do?

**Comment by andreescocard** [comment]
I am just curious to understand why using electron the executable don't get flagged the same way.
Anyway i gave up using nw.js, to everyone that will use the software have to add it on whitelist is inviable for me.

**Comment by bluthen** [comment]
@andreescocard 
It does happen to electron also, but maybe there are more people to submit builds to the malware detector vendors:

https://github.com/electron/electron/issues/4485

Electron also I think signs their builds. Anyway good luck!

**Comment by top-5** [comment]
This issue happens with both Windows Defender and Kaspersky, which both identify `nw.exe` as the culprit :
`Trojan:Win32/Doplik` - `This program is dangerous and executes commands from an attacker.`
