### ISSUE TITLE
webview's "beforeunload" event do'nt work

### ISSUE THREAD

**Issue by a379933101** [nwjs/nw.js#8056]
<webview id="foo" src="test.html" style="width:100%;height: 100%;" partition="trusted" allownw></webview>

test.html:
<body>
        <a href="test2.html" >test2</a>
        <script>
             window.addEventListener('beforeunload', (event) => {
                event.preventDefault();
                event.returnValue = '';
            });
        </script>
    </body>
 
the code ' window.addEventListener('beforeunload' .. '  have no effect

**Comment by a379933101** [comment]
<webview id="foo" src="test.html" style="width:100%;height: 100%;" partition="trusted" allownw></webview>

**Comment by a379933101** [comment]
webview id="foo" src="test.html" style="width:100%;height: 100%;" partition="trusted" allownw>

**Comment by panther7** [comment]
It did not ever worked... #6945

**Comment by tharatau** [comment]
Duplicate of #6945
