### ISSUE TITLE
With `fullscreen: true` in `package.json`, the Document is inactive

### ISSUE THREAD

**Issue by ElPrudi** [nwjs/nw.js#8057]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior

I tested `fullscreen: true` in `package.json` to automatically start in fullscreen. Then I call `document.exitFullscreen()` to exit the fullscreen mode. Then this error message appears:

```
TypeError: Failed to execute 'exitFullscreen' on 'Document': Document not active
```

### Expected/Proposed Behavior

It seems like this is not the expected behavior as neither the documentation nor the schema suggestion mention this problem. Either the documentation should be updated or this issue should be fixed. 

### Additional Info

- Operating System: Windows 10
- NW.js Version: 0.75.0
- Repro Link:
- Code snippet:
- Crash report:

**Comment by ElPrudi** [comment]
While it does work, it is never explained why the document is inactive and I don't think this is intended.

**Comment by tharatau** [comment]
I am not too sure - my guess is that NW's's Fullscreen API differs from the [browser's API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API).
