### ISSUE TITLE
URL.createObjectURL fails on 0.76.1

### ISSUE THREAD

**Issue by Kruithne** [nwjs/nw.js#8075]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior

`URL.createObjectURL(new Blob([]))` is the minimal code needed to reproduce the issue. In 0.76.1 the following error message is produced, regardless of input.

```Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.```

### Expected/Proposed Behavior

The expected behavior is that a URL to the blob is returned, such as:

```blob:chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/b1957c09-3e5c-48d3-b545-8052ddb77d3c```

This works as expected on 0.75.0.

### Additional Info

- Operating System: Windows
- NW.js Version: 0.76.1
- Repro Link:
- Code snippet: `URL.createObjectURL(new Blob([]))`
- Crash report:

**Comment by rogerwang** [comment]
It works for me. I started nw, opened the devtools window and then posted the snippet.

**Comment by skymen** [comment]
From my testing, this is only broken inside workers, not on the main thread

- Worker disabled:
https://drive.google.com/file/d/1KO2yJpoG3yo7fXO0i64iWeTAwpZG_5-A/view?usp=drive_link

- Worker enabled:
https://drive.google.com/file/d/1_k4_dQT8B1XWPcjUNGnqAAdNGaMxV330/view?usp=drive_link

(Sorry, file too big for Github)

The bug still happens in 0.77.0

**Comment by johnyc3** [comment]
> This issue seems to be resolved in 0.78.1

Still failing for me.

**Comment by anker9** [comment]
Same fail on 0.79.1 win64
Same code works fine on 0.75.1

**Comment by ellementul** [comment]
I have the same problem with pixi.js

**Comment by rogerwang** [comment]
Could you provide a small code sample to reproduce, not an entire application?

**Comment by AshleyScirra** [comment]
I think I found a minimal repro for this: 
[nwjs-issue8075.zip](https://github.com/nwjs/nw.js/files/12737560/nwjs-issue8075.zip)

It's true that `URL.createObjectURL(blob)` fails in a worker only in recent versions of NW.js, but *only* when specifying `"chromium-args": "--enable-node-worker"` in package.json, which some frameworks (like ours) do.

In this case, in the context of the worker, the `Blob` constructor actually appears to be a version from Node.js (apparently from `node:internal/blob`) that overrides the browser one. Therefore since it's not a real Blob that the browser understands, methods like `URL.createObjectURL` fail, but also checks like `instanceof Blob` also fail.

Hopefully this is enough information to be able to fix the issue now - we're seeing reports of this from time to time (e.g. [here](https://www.construct.net/en/forum/construct-3/how-do-i-8/nw-js-exports-black-screen-178842)).

**Comment by AshleyScirra** [comment]
Any news on this? We are still getting reports of this causing problems, e.g.: https://github.com/Scirra/Construct-bugs/issues/7466
My previous comment includes a minimal repro and appears to identify the `--enable-node-worker` command line argument as the problem.

**Comment by sieusaovang** [comment]
Lỗi 3d object xuất njsw đã được sửa chưa?

**Comment by dop2000** [comment]
Any update on this? We had to disable the worker in our game and now getting lots of reports of poor performance from users..

**Comment by AshleyScirra** [comment]
Has any NW.js developer had the chance to review [my minimal repro](https://github.com/nwjs/nw.js/issues/8075#issuecomment-1737141230) yet? Tagging @rogerwang for attention. We're still getting regular reports of this, e.g. [here](https://www.construct.net/en/forum/construct-3/how-do-i-8/export-errors-179653) and [here](https://www.construct.net/en/forum/construct-3/general-discussion-7/black-screen-nwjs-exports-179660), both posted today.

**Comment by AshleyScirra** [comment]
Another report of this today [here](https://github.com/Scirra/Construct-bugs/issues/7663). Any news?

**Comment by rogerwang** [comment]
Please test this build: https://dl.nwjs.io/live-build/nw85/20240305-222312/9b99df3ea/v0.85.1/

**Comment by dop2000** [comment]
Thank you, @rogerwang  !

@AshleyScirra  , I tested in remote preview and it appears to be working. Is it possible to build a C3 project with this new version (85.1)?

**Comment by AshleyScirra** [comment]
@rogerwang - is an official NW.js 0.85.1 release coming up for this? Apparently the issue is affecting some Construct games, and it would be useful to know if a release is scheduled, or if we ought to be using a one-off build (which I'm a bit reluctant about as normally nightly releases are not as reliable)

**Comment by AshleyScirra** [comment]
@rogerwang - thanks for the fix!

**Comment by CosmoMyzrailGorynych** [comment]
By gods! Thank you! This issue was blocking ct.js update to use WebGPU as the issue broke pixi.js v8.

**Comment by CosmoMyzrailGorynych** [comment]
@rogerwang apparently there are still issues with createObjectURL. Tested in v0.86.0 and 0.87.0.
`URL.createObjectURL(new Blob([]))` — throws the same error.

My chromium args are:
```
  "chromium-args": "--mixed-context --enable-features=nw2 --load-extensions --force-color-profile=srgb --disable-features=ColorCorrectRendering",
```

**Comment by CosmoMyzrailGorynych** [comment]
@rogerwang the same error happens on nw.js-enabled `webview` tags. Removing `allownw` attribute on them is enough to fix the error — the price is, again, not great.

**Comment by ssnangua** [comment]
> I think I found a minimal repro for this: [nwjs-issue8075.zip](https://github.com/nwjs/nw.js/files/12737560/nwjs-issue8075.zip)
> 
> It's true that `URL.createObjectURL(blob)` fails in a worker only in recent versions of NW.js, but _only_ when specifying `"chromium-args": "--enable-node-worker"` in package.json, which some frameworks (like ours) do.
> 
> In this case, in the context of the worker, the `Blob` constructor actually appears to be a version from Node.js (apparently from `node:internal/blob`) that overrides the browser one. Therefore since it's not a real Blob that the browser understands, methods like `URL.createObjectURL` fail, but also checks like `instanceof Blob` also fail.
> 
> Hopefully this is enough information to be able to fix the issue now - we're seeing reports of this from time to time (e.g. [here](https://www.construct.net/en/forum/construct-3/how-do-i-8/nw-js-exports-black-screen-178842)).

Thanks to the error cause analyzed by @AshleyScirra , I found a temporary solution:
```html
<!-- Fix Blob Start -->
<script>delete window.Blob;</script>
<script src="https://cdn.jsdelivr.net/npm/blob-polyfill@9.0.20240710/Blob.min.js"></script>
<!-- Fix Blob End -->

<script>
    const objectURL = URL.createObjectURL(new Blob(["test"]));
    console.log(objectURL); // 'data:;base64,dGVzdA=='
</script>
```
But it is still a problem, I hope it can be solved reasonably.
