### ISSUE TITLE
Certificate expired error

### ISSUE THREAD

**Issue by McGiverGim** [nwjs/nw.js#8076]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [X] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
Certificate error when downloading nw.js sdk.
We have a github action that builds our software, but it's giving random errors about the certificate expired.
```
[06:10:09] Starting 'debug'...
Error building NW apps: Error: certificate has expired
```
Going to https://www.ssllabs.com/ssltest/analyze.html?d=nwjs.io shows the problem with the certificate too.
![image](https://github.com/nwjs/nw.js/assets/2673520/209cf68b-6d5f-4064-ba2e-b68197d4a536)

### Expected/Proposed Behavior
Renew the certificate.
### Additional Info

- Operating System: -
- NW.js Version: 0.72.0
- Repro Link: -
- Code snippet: -
- Crash report: -

**Comment by rogerwang** [comment]
Thanks for reporting. It's fixed now.
