### ISSUE TITLE
"Mainfest file missing or unreadable" in barebones project

### ISSUE THREAD

**Issue by GabZanMacaw** [nwjs/nw.js#8079]
### Issue Type

- [X] Bug Report
- [X] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior

I get a "Manifest file missing or unreadable" in any project I make. No crash dump, console output or anything other than this error.

![image](https://github.com/nwjs/nw.js/assets/98890458/cce14851-5db8-4174-b318-22165579d26f)

### Expected/Proposed Behavior

There's nothing wrong with my project.json file or my code so I'd expect it to work, or at least give me a more useful error message.

### Additional Info

- Operating System: Windows 11
- NW.js Version: [v0.77.0](https://dl.nwjs.io/v0.77.0/nwjs-v0.77.0-win-x64.zip)
- Code:

index.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
  </head>
  <body></body>
</html>
```

project.json:
```json
{
  "name": "test",
  "main": "index.html"
}
```

Structure:
![image](https://github.com/nwjs/nw.js/assets/98890458/f175c1b6-c1a6-469f-82b0-cc8192db97e6)

nw.js is located in `c:\Users\gabriel\Desktop\nwjs-v0.77.0-win-x64`.

Run command:
```powershell
C:\Users\gabriel\Desktop\test> c:\Users\gabriel\Desktop\nwjs-v0.77.0-win-x64\nw.exe .
```

I tried using both the SDK version and the Normal version... have no idea what I'm doing wrong.

**Comment by bluthen** [comment]
The file should be package.json not project.json

**Comment by GabZanMacaw** [comment]
Oh wow, that's embarrassing. Thank you and I'm so sorry
