### ISSUE TITLE
`webkitSpeechRecognition` always throws a network error

### ISSUE THREAD

**Issue by malisipi** [nwjs/nw.js#8080]
### Issue Type

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js? `0.77.0`

### Current/Missing Behavior

`webkitSpeechRecognition` API always throws a network error. (Click the button to start speech recognition)

![image](https://github.com/nwjs/nw.js/assets/87281783/99a76f45-6062-4941-a746-fbc286d7bca4)
![image](https://github.com/nwjs/nw.js/assets/87281783/1df440a2-95c7-4be2-bfd9-92a86719c1f9)

> Image from NW.JS

### Expected/Proposed Behavior

`webkitSpeechRecognition` API is recognizes the audio correctly and alerts as text

![image](https://github.com/nwjs/nw.js/assets/87281783/ff7a91ee-786f-4e19-a402-3b6bc4698575)

> Image from Chrome

### Additional Info

- Operating System: `Garuda Linux` `Linux 6.3.8-zen1-1-zen` `x86_64`
- NW.js Version: `0.77.0`
- Repro Link: https://github.com/malisipi/nwjs-bug-report-speech-recognition [Download as .zip](https://github.com/malisipi/nwjs-bug-report-speech-recognition/archive/refs/heads/main.zip)

**Comment by malisipi** [comment]
Also there're a [old issue](https://github.com/nwjs/nw.js/issues/7679) about it. However it's not fixed since the issue creator not provide a repro link.

**Comment by UtterDonkey** [comment]
It's not an NW.js issue. Try downloading chromium and you get the same issue, webkitSpeechRecognition doesn't work in chromium and has to be manually supported by software using chromium (Chrome, edge, etc.)

**Comment by malisipi** [comment]
Thank you for the response. I will look for another solution.
