### ISSUE TITLE
NW.js 0.77.0 64Bit (Normal & SDK) cannot be started under Windows 8 cause of DLL Error

### ISSUE THREAD

**Issue by zzador** [nwjs/nw.js#8087]
Trying to start NW.js (Normal or SDK) under Windows 8 instantly crashes with the error message:

The procedure entry point "DiscardVirtualMemory" was not found in the DLL "...\nw.dll"

**Comment by ayushmanchhabra** [comment]
@zzador Chromium dropped support for Windows 7 and 8 in v110 (NW.js v0.73.0). The last version to support it is NW.js v0.72.x.

See here for more info:
https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023?hl=en

https://github.com/nwjs/nw.js/issues/8029

**Comment by zzador** [comment]
Thank you for the fast response!
