### ISSUE TITLE
Cannot generate executable stops with error -> "package.json not found in srcDir file glob patterns" 

### ISSUE THREAD

**Issue by abhidaa1233** [nwjs/nw.js#8088]
### Issue Type
I am using "npm run prod" to generate the executable. Whenever I am trying to generate it throws error "package.json not found in srcDir file glob patterns". Tried downgrading different versions of nwjs, nw-build, nodejs, npm etc but didn't work out.
In my project I am using I am using Angularjs, nodejs, html, css along with nwJs.
I will provide information on my folder structure :
Project ->
................node-modules
.................src--->
.......................app
........................css
.........................lib
.........................index.html
.........................package.json
...............package-lock.json
...............package.json

The package.json outide src folder ->
             {
              "name": "My_Project",
             "version": "1.0.0",
             "description": "",
             "main": "index.html",
             "scripts": {
             "dev": "nw src/",
             "prod": "nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/src/"
             },
            "keywords": [],
            "author": "",
            "license": "ISC",
            "devDependencies": {
                   "nw": "^0.76.1-sdk",
                   "nw-builder": "^4.2.3"
              }
           }
The package.json inside src folder ->
              {
               "name": "src",
               "version": "1.0.0",
               "description": "",
              "main": "index.html",
              "directories": {
              "lib": "lib"
               },
             "scripts": {
                  "test": "echo \"Error: no test specified\" && exit 1"
              },
  "window": {
    "title": "Office1",
    "icon": "",
    "toolbar": true,
    "frame": true,
    "resizable": true,
    "width": 1200,
    "height": 700,
    "min_width": 1200,
    "min_height": 700,
    "fullscreen": false,
    "position": "center"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

- [ ] Bug Report

Error : [ ERROR ] 2023-07... package.json not found in srcDir file glob patterns.
file:///...My_Project_Path/node_modules/nw-builder/src/util/versionManifest.js:26
    throw new Error("package.json not found in srcDir file glob patterns.");

### Current/Missing Behavior
 Could not generate executable file

### Expected/Proposed Behavior
Normal smooth executable generation

### Additional Info

- Operating System: WIndows 10
- NW.js Version:  0.76.1-sdk
- nw-builder Version: 4.2.3

**Comment by ayushmanchhabra** [comment]
This is a nw-builder issue. Could you please open this there?

**Comment by abhidaa1233** [comment]
ok thank you @ayushmanchhabra
