### ISSUE TITLE
Mouse right click options not working after latest updates

### ISSUE THREAD

**Issue by abhidaa1233** [nwjs/nw.js#8089]
### Issue Type
- [ ] Bug Report
Currently I am using versions -> nw: 0.77.0, nw-build : 4.3.2, nodejs: 20.1.0, chromium : 114.0.5735.199.
The current issue is that I cannot open dev tools or reoad app as before I did by right clicking mouse anywhere in the app, it used to show options like reload, inspect etc. Now upon right click its showing nothing.
 I think maybe after the chromium update its behaving like this as per the nwjs latest blog post NwJs supports chromium 114.0.5735.91 (https://chromereleases.googleblog.com/2023/05/stable-channel-update-for-desktop_30.html).
Please let me know if there is any workaround to enable dev tools.

Thank you

- [ ] Successfully reproduced against the latest version of NW.js?

### Expected/Proposed Behavior
Should show option on mouse right click

### Additional Info

- Operating System: Windows 10
- NW.js Version:  0.77.0
- Repro Link:
- Code snippet:
- Crash report:

**Comment by ayushmanchhabra** [comment]
@abhidaa1233 Are you using the normal or sdk build?

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/npm-installer/issues/86
I think what happened is that when you upgraded the `nw` package, it upgraded from `0.76.1-sdk` to `0.77` (that's just how npm works).

https://nwutils.io/nw-builder/mode-get.html
You can instead download NW.js binaries via `nw-builder` itself and add the CLI command as a post install step:

An example:
```
"scripts": {
  "postinstall": "nwbuild --mode=get --version=0.77 --flavor=sdk"
}
```

**Comment by abhidaa1233** [comment]
Thankx @ayushmanchhabra you understood the problem, what I did is remove normal nw and installed sdk of version 0.77.0 by npm i nw@0.770-sdk and it worked normally
