### ISSUE TITLE
How to enable sounds?

### ISSUE THREAD

**Issue by d3x0r** [nwjs/nw.js#8100]
`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`

How do I enable sounds for a site?  In Chrome I can get to the address bar and enable sounds...  I don't see how to launch with an address bar.

I would have really hoped since this is more of a platform for applications than a generic browser that this would have just been enabled.

I tried to launch with 'chrome://settings' as a URL but NWJS just exited... however 'chrome://flags' worked (but the sound settings are under settings not flags, so that didn't really help).

**Comment by ElPrudi** [comment]
This is done via a chromium arg. Here is the [full list](https://peter.sh/experiments/chromium-command-line-switches/). You need to put `--no-user-gesture-required` into your package.json in the chromium args string.

**Comment by d3x0r** [comment]
that doesn't work on chrome so it's not a chrome flag.. and I still get `flashboard.js:291 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD` on nwjs.

``` json
{
	"name": "required",
	"main":"http://localhost:8082/flashboard.html",
	"window": {
		"fullscreen":true
	},
	"chromium-args": "--no-user-gesture-required"	
}
```

**Comment by ElPrudi** [comment]
Just looked it up again and it works for me, when I have these flags:

```json
{
    "chromium-args": "--disable-user-media-security --allow-hidden-media-playback --autoplay-policy=no-user-gesture-required"
}
```

**Comment by d3x0r** [comment]
That combination of flags seems to work for me, thank you very much.
