### ISSUE TITLE
App crashes on Linux with version 79

### ISSUE THREAD

**Issue by linusha** [nwjs/nw.js#8106]
### Issue Type

- [x] Bug Report

- [x] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior

A simple app only displaying static HTML will crash with the newest `nw.js` version (0.79) on linux. The app opens successfully, but will crash after a few seconds, as soon as one hovers over the window. 0.78.1 worked.

### Expected/Proposed Behavior

The app should not crash.

### Additional Info

- Operating System: 
```
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.2.6-76060206-generic
```
- NW.js Version: 0.79
- Code snippet:

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1 id="test">Hello World!</h1>
  </body>
</html>
```

package.json
```
{
  "name": "helloworld",
  "main": "index.html"
}
```
- Crash report:
```
[37729:37729:0818/173557.064570:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.
[0818/173557.095826:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0818/173601.590652:WARNING:process_reader_linux.cc(144)] no stack mapping
[0818/173601.591107:WARNING:process_reader_linux.cc(144)] no stack mapping
Received signal 11 <unknown> 192c50001048
#0 0x7f0624a60ee3 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6860ee2)
#1 0x7f0624a72341 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6872340)
#2 0x7f061de42520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#3 0x7f0624b84ebf (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6984ebe)
#4 0x7f0624b7ddc5 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x697ddc4)
#5 0x7f0624a74d38 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6874d37)
#6 0x7f0620b9fc82 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x299fc81)
#7 0x7f0622db146f (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x4bb146e)
#8 0x7f0623c5dec3 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5a5dec2)
#9 0x7f0623c64685 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5a64684)
#10 0x7f0623c4356a (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5a43569)
#11 0x7f062114d021 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x2f4d020)
#12 0x7f0624a0d384 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x680d383)
#13 0x7f0624a25163 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6825162)
#14 0x7f0624a24bd9 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6824bd8)
#15 0x7f0624a25635 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6825634)
#16 0x7f06249ca509 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x67ca508)
#17 0x7f0624a25994 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6825993)
#18 0x7f06249edd3e (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x67edd3d)
#19 0x7f062a3d5600 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0xc1d55ff)
#20 0x7f0623ecb773 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5ccb772)
#21 0x7f0623eccb2e (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5cccb2d)
#22 0x7f0623eca1e6 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5cca1e5)
#23 0x7f0623eca4e2 (/home/linus/Desktop/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5cca4e1)
#24 0x7f06205d22ca ChromeMain
#25 0x7f061de29d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
  r8: 0000000000000001  r9: 0000000000000001 r10: 0000379400601100 r11: 0000000000000000
 r12: 0000192c50001040 r13: 0000000000000000 r14: 0000192c50001040 r15: 0000000000000000
  di: 00007f062b14a0b0  si: 00007ffe347e5a78  bp: 00007ffe347e60e0  bx: 00007f062b14a0b0
  dx: 0000000010600002  ax: 0000000010600002  cx: 0000192c50008020  sp: 00007ffe347e60b0
  ip: 00007f0624b80610 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000027
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000192c50001048
[end of stack trace]
```

**Comment by layerswing** [comment]
I have the same issue.

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy


`[9052:9052:0820/143714.670350:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.
[0820/143714.689653:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0820/143718.736771:WARNING:process_reader_linux.cc(144)] no stack mapping
[0820/143718.737427:WARNING:process_reader_linux.cc(144)] no stack mapping
Received signal 11 <unknown> 2e94f0001048
#0 0x7f85d9a60ee3 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6860ee2)
#1 0x7f85d9a72341 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6872340)
#2 0x7f85d2e42520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#3 0x7f85d9b84ebf (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6984ebe)
#4 0x7f85d9b7ddc5 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x697ddc4)
#5 0x7f85d9a74d38 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6874d37)
#6 0x7f85d5b9fc82 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x299fc81)
#7 0x7f85d7db146f (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x4bb146e)
#8 0x7f85d8c5dec3 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5a5dec2)
#9 0x7f85d8c64685 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5a64684)
#10 0x7f85d8c4356a (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5a43569)
#11 0x7f85d614d021 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x2f4d020)
#12 0x7f85d9a0d384 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x680d383)
#13 0x7f85d9a25163 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6825162)
#14 0x7f85d9a24bd9 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6824bd8)
#15 0x7f85d9a25635 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6825634)
#16 0x7f85d99ca509 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x67ca508)
#17 0x7f85d9a25994 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x6825993)
#18 0x7f85d99edd3e (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x67edd3d)
#19 0x7f85df3d5600 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0xc1d55ff)
#20 0x7f85d8ecb773 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5ccb772)
#21 0x7f85d8eccb2e (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5cccb2d)
#22 0x7f85d8eca1e6 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5cca1e5)
#23 0x7f85d8eca4e2 (/home/bkb/programok/node/nwjs-sdk-v0.79.0-linux-x64/lib/libnw.so+0x5cca4e1)
#24 0x7f85d55d22ca ChromeMain
#25 0x7f85d2e29d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
  r8: 0000000000000001  r9: 0000000000000001 r10: 00001ac800601100 r11: 0000000000000000
 r12: 00002e94f0001040 r13: 0000000000000000 r14: 00002e94f0001040 r15: 0000000000000000
  di: 00007f85e014a0b0  si: 00007ffc2f770148  bp: 00007ffc2f7707b0  bx: 00007f85e014a0b0
  dx: 0000000010600002  ax: 0000000010600002  cx: 00002e94f0008020  sp: 00007ffc2f770780
  ip: 00007f85d9b80610 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000027
 trp: 000000000000000e msk: 0000000000000000 cr2: 00002e94f0001048
[end of stack trace]`

**Comment by layerswing** [comment]
I've dowloaded **nwjs-sdk-v0.79.0-linux-x64** and running **nw** does the same error.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
