### ISSUE TITLE
[nw 79.0 SDK] DevTools debugger is disabled

### ISSUE THREAD

**Issue by garfield69** [nwjs/nw.js#8108]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

### Current Behaviour

The console log is showing the following error message at start up of 79.0
```
DevTools debugger is disabled because it is attached to a process that hosts multiple top-level frames, where DevTools debugger doesn't work properly. Please relaunch the browser with --disable-features=ProcessPerSiteUpToMainFrameThreshold to enable debugger.
```
### Expected Behaviour

no error ;-)

### Additional Info

- Operating System: Windows 10
- NW.js Version: 79.0 SDK
- Code snippet:
index.html
```HTML
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1 id="test">Hello World!</h1>
  </body>
</html>
```
package.json
```json
{
  "name": "helloworld",
  "main": "index.html"
}
```

This is more a case of FYI, I don't actually require the debugger for anything ATM, but clearly something is now broken that did not appear on the previous release so I though you should know about it ;-)

**Comment by Matt-Maerz** [comment]
I can confirm and it is needed ;D
The NodeJS debugger also displays the error message

This allows you to open it, just for info:
chrome.developerPrivate.openDevTools({ renderViewId: -1, renderProcessId: -1, extensionId: chrome.runtime.id });

**Comment by Sunvas** [comment]
The same problem I've described in #8096 and in Google Groups https://groups.google.com/g/nwjs-general/c/jmTAkmrrMSg

**Comment by linusha** [comment]
Just in case - I also encountered this and if that is feasible for you, adding `chromeArgs: --disable-features=ProcessPerSiteUpToMainFrameThreshold` to my `package.json` resolved the problem.
I have to say however that I do not know the exact implications of this flag, which was no issue for me since I am currently only in a local experimentation stage. Not sure if that is something one wants enabled for production apps.

**Comment by garfield69** [comment]
this https://chromium.googlesource.com/chromium/src/+/8e087a65f0a71016641504e900830dae86c9a647 provides some background but its all double-dutch to me ;-)

**Comment by jssuttles** [comment]
I see this problem as well. I run nwjs using the --remote-debugging flag. So, this comes up when you pull it up in chrome://inspect.

**Comment by jssuttles** [comment]
This looks like maybe there is a recent version of Chromium that fixes this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1469276&q=DevTools%20debugger%20is%20disabled%20because%20it%20is%20attached%20to%20a%20process%20that%20hosts%20multiple%20top-level%20frames&can=2

**Comment by garfield69** [comment]
I just tried out **nw 80.0 nightly** from https://dl.nwjs.io/live-build/nw80/20230914-151112/3a8b1147b/v0.80.0/nwjs-sdk-v0.80.0-win-x64.zip
and can confirm that the error message no longer appears on the development tools console logs ;-)
