### ISSUE TITLE
how to change the website base path?

### ISSUE THREAD

**Issue by liesauer** [nwjs/nw.js#8117]
currently, the base path is where the package.json is, how can i change to somewhere like `%APPDATA%/myapp/dist`, and then all the relative html/css/js resloved from that path.

**Comment by ayushmanchhabra** [comment]
@liesauer Only way I can see it working is from the current base path, you refer to `%APPDATA%/myapp/dist`.

Also please ask questions via the mailing list. GitHub issue tracker is mainly for bug reports and feature requests.
