### ISSUE TITLE
nw is not defined in PDF Viewer

### ISSUE THREAD

**Issue by liesauer** [nwjs/nw.js#8120]
`"node-remote": ["<all_urls>"]` is not working

![image](https://github.com/nwjs/nw.js/assets/8676741/7326774e-d9e5-4b54-bb06-46b50152a4fd)

**Comment by ayushmanchhabra** [comment]
https://nwjs.readthedocs.io/en/latest/References/Manifest%20Format/#node-remote
The match pattern used in the docs is not being used here. I am not sure if that is related to the `ReferrenceError`. I'll need a little more info to debug this (a minimal reproduction).

**Comment by liesauer** [comment]
that was weird, i did nothing, it's ok now.
![image](https://github.com/nwjs/nw.js/assets/8676741/26ad34ac-bb1e-4202-ba44-3aca0a4f0b90)
