### ISSUE TITLE
Normal build of 0.80.0 for osx x64 crashes on launch

### ISSUE THREAD

**Issue by arudnev** [nwjs/nw.js#8123]
Normal build crashes on launch, SDK build works as expected

Broken: https://dl.nwjs.io/v0.80.0/nwjs-v0.80.0-osx-x64.zip
Working: https://dl.nwjs.io/v0.80.0/nwjs-sdk-v0.80.0-osx-x64.zip

### Additional Info

- Operating System: macOS 13.5.2
- NW.js Version: 0.80.0 x64 normal build
- Crash report: [nwjs-0.80.0-osx-x64-crash.txt](https://github.com/nwjs/nw.js/files/12665594/nwjs-0.80.0-osx-x64-crash.txt)

**Comment by arudnev** [comment]
It seems that the latest working normal build for osx x64 was 0.78.1, all subsequent releases (0.79.0, 0.79.1, 0.80.0) are broken

**Comment by arudnev** [comment]
I presume this is a duplicate of https://github.com/nwjs/nw.js/issues/8111

**Comment by rogerwang** [comment]
#
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
