### ISSUE TITLE
add Dialog functions

### ISSUE THREAD

**Issue by pingping666** [nwjs/nw.js#8124]
可不可以增加Dialog相关的函数，类似于electron中的那样，用于选择文件夹或文件等等，而不是仅仅只有扩展后的input标签。

Can add Dialog related functions, similar to those in electron, to select folders or files, etc., instead of just the expanded input tag?

**Comment by Sunvas** [comment]
To select folders, you can use https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory
