### ISSUE TITLE
Transparent clickthrough window not working on MacOS Sonoma 14.0

### ISSUE THREAD

**Issue by tarunj370** [nwjs/nw.js#8125]
### Issue Type

- [YES] Bug Report

- [YES] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior
Clickthrough in the transparent window is working till macOS Ventura 13. Tested in the latest build v0.80.0. The behavior is broken after the macOS upgrade to Sonoma 14.0.

### Expected/Proposed Behavior
Clickthrough should work in the macOS 14.0 too.

### Additional Info

- Operating System: macOS Sonoma 14.0
- NW.js Version: v0.80.0
- Repro Link: NA
- Code snippet:
```"chromium-args": "--disable-gpu-compositing --force-cpu-draw --mixed-context"```
- Crash report: NA

**Comment by ayushmanchhabra** [comment]
@tarunj370 could you provide some sample code/a minimal repro demonstrating this?

**Comment by ayushmanchhabra** [comment]
Min repro:

index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" />
</head>

<body>
    <h1>Hello World!</h1>
</body>

</html>
```

package.json
```json
{
    "name": "my-nwjs-app",
    "main": "index.html",
    "scripts": {
        "dev": "nw ."
    },
    "window": {
        "frame": false,
        "transparent": true,
        "resizable": false
    },
    "chromium-args": "--disable-gpu-compositing --force-cpu-draw",
    "devDependencies": {
        "nw": "0.80.0-sdk"
    }
}
```

**Comment by ayushmanchhabra** [comment]
@rogerwang I was trying to test the transparent window this behaviour on the [latest Chromium build](https://download-chromium.appspot.com/). I noticed that in the source, [options.alphaEnabled is set](https://github.com/nwjs/nw.js/blob/nw80/src/resources/api_nw_newwin.js#L804-L805).

I tried to create a new transparent window via Chromium DevTools but got a type error. Please advise on how to go about reproing transparent window behavior in Chrome/Chromium, thanks!

Command:
```shell
chrome.windows.create({ alphaEnabled: true }, () => {});
```

Error:
```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'create')
```

**Comment by tarunj370** [comment]
Any update on this @ayushmanchhabra @rogerwang ?

**Comment by rogerwang** [comment]
Is there any chance you could take a look @jtg-gg ?

**Comment by jtg-gg** [comment]
sorry @rogerwang I've moved on to different project
supporting this on my own time, will require lots of effort

**Comment by tarunj370** [comment]
> @rogerwang I was trying to test the transparent window behaviour on the [latest Chromium build](https://download-chromium.appspot.com/). I noticed that in the source, [options.alphaEnabled is set](https://github.com/nwjs/nw.js/blob/nw80/src/resources/api_nw_newwin.js#L804-L805).
> 
> I tried to create a new transparent window via Chromium DevTools but got a type error. Please advise on how to go about reproing transparent window behavior in Chrome/Chromium, thanks!
> 
> Command:
> 
> ```shell
> chrome.windows.create({ alphaEnabled: true }, () => {});
> ```
> 
> Error:
> 
> ```shell
> Uncaught TypeError: Cannot read properties of undefined (reading 'create')
> ```
> 
> If this behaviour is reproduced on latest Chromium build then a bug report can be filed in the Chromium bug tracker.

@ayushmanchhabra

The `chrome.windows.create` method is specific to Chrome extensions and is not available for use in regular web pages or standalone JavaScript. It can only be used within the context of a Chrome extension.
