### ISSUE TITLE
NW-GYP new release request

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#8130]
Here are the changes that have been merged in since the last release 1 year ago:

* Added a note to the documentation
* Fixed an issue where file paths could not contain spaces, now they can
  * FIX: Wrap file paths in quotes
* Fixed an issue where Node v19+ stopped working because `process.config` is now `Object.frozen`
  * FIX: `JSON.parse(JSON.stringify(process.config))`

**Diff:**

* https://github.com/nwjs/nw-gyp/compare/966ca060299ea3a31ccd81b35916ccb26980faed...node-gyp-3.6.2

The user that made the PR's to fix these issues is requesting a new release.

**Comment by panther7** [comment]
Maybe need rename branch, actually name is "node-gyp-3.6.2", but is released 3.6.6

**Comment by ayushmanchhabra** [comment]
@panther7 Have you tried using node-gyp and passing the NW.js node headers to it via the `--nodedir` option? That's how I've implemented it in nw-builder. I have to apply a patch to the headers and I've opened a PR for this here https://github.com/nwjs/node/pull/57

**Comment by rogerwang** [comment]
What's your npmjs.com account name for this? I can add you to the package maintainers list.

**Comment by TheJaredWilcurt** [comment]
`thejaredwilcurt`

https://www.npmjs.com/~thejaredwilcurt

**Comment by rogerwang** [comment]
done.

**Comment by ayushmanchhabra** [comment]
@TheJaredWilcurt can this be closed?
