### ISSUE TITLE
Error during Win7 operation

### ISSUE THREAD

**Issue by xiyuvi** [nwjs/nw.js#8131]
![ed268ba214aeadd46c8e2db2dd52e5d](https://github.com/nwjs/nw.js/assets/38217058/5efde848-21cd-44a5-bd0f-b92f644b36eb)
Hello, I encountered this error while running my program on Win7，His English meaning is: "Unable to locate the program input point SetProcessMitigationPolicy on the dynamic link library KERNEL32.dll
Using "nw.js v0.74.0" and below can avoid this error message, while using versions 0.74.0 and above will result in error messages.

I searched on Google and the possible reason is that Win7 did not update the system patch, which resulted in the inability to find functions that rely on NW. However, my Win7 does not have a network environment and cannot upgrade the system patch. Therefore, I would like to see if you have any solutions.

If it's too troublesome for you to solve, you can close this bug and ignore it. Thank you for developing nw.js

**Comment by bluthen** [comment]
nwjs 0.74.0 is based on chromium 111.

I believe the last version of chromium to support windows 7 is 109.

That is my guess as to what is happening.

nwjs 0.72.0 is based on chromium 109.
