### ISSUE TITLE
The official nwjs-sdk-v0.81.1-osx-arm64 binary is damaged.

### ISSUE THREAD

**Issue by hokein** [nwjs/nw.js#8135]
I encountered the error when running it on MacOS 13.6 (M1 Pro). I redownloaded it multiple times, the error still persists (for other version as well).

<img width="259" alt="image" src="https://github.com/nwjs/nw.js/assets/2557445/66cedf1d-7c00-45b1-b05a-59791667ca8c">

**Comment by tarunj370** [comment]
@hokein you will have to sign the binary in order to run it on your machine.

**Comment by LucasBeiknejad** [comment]
It's also possibly by simply running
```
xattr -c nwjs.app
```
