### ISSUE TITLE
visible_on_all_workspaces does not work on Linux anymore and win.canSetVisibleOnAllWorkspaces() returns an object

### ISSUE THREAD

**Issue by anesuc** [nwjs/nw.js#8146]
### Issue Type

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

### Additional Info
Setting visible_on_all_workspaces does not work anymore (migrated from a really old version of Nw.js where this worked. and checking with win.canSetVisibleOnAllWorkspaces() returns a object rather than a bool which can be seen bellow:
```
[
    "linux",
    "linux"
]
```

- Operating System:
- NW.js Version :0.82.0
- Repro Link:
- Code snippet:
win.canSetVisibleOnAllWorkspaces();
- Crash report:
no report

**Comment by ayushmanchhabra** [comment]
@rogerwang I have a PR up which should fix this issue.
