### ISSUE TITLE
Ability to denote element as maximise/restore button for Win11 Snap support

### ISSUE THREAD

**Issue by UtterDonkey** [nwjs/nw.js#8147]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ ] Bug Report
- [x] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behaviour

When making a custom titlebar on a frameless windows, it isn't possible to hover over the maximise/restore button to display the [snap layout menu in Windows 11](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu). I believe this is already possible in electron as it is supported in VS Code.

This feature may not be needed if this is implemented: https://github.com/nwjs/nw.js/issues/5999

### Expected/Proposed Behaviour

Some way of specifying an element as the maximise/restore button (eg. a CSS property like `-webkit-app-reigon`) so that when it is hovered, the native snap layout menu can be displayed on Windows 11.

### Additional Info

- Operating System: Windows 11

**Comment by ayushmanchhabra** [comment]
@UtterDonkey can this closed as subset of #5999?

**Comment by tiagorangel2011** [comment]
There is no need for more info. We just want the ability to use Windows 11's snap feature that shows when you hover the maximize button on a custom titlebar.

**Comment by UtterDonkey** [comment]
> @UtterDonkey can this closed as subset of #5999?

Yes, probably
