### ISSUE TITLE
https://dl.nwjs.io/ timing out

### ISSUE THREAD

**Issue by garfield69** [nwjs/nw.js#8158]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report

I am unable to download the 0.83 SDK or NORMAL build for Linux from https://nwjs.io/downloads/
The browser returns a timeout.
I can download the windows and the mac files OK
Also the Other Downloads 0.83 link https://dl.nwjs.io/v0.83.0/, the Nightly builds link https://dl.nwjs.io/live-build/  timeout
The Previous Releases link https://dl.nwjs.io/ takes me to the index, but the links on that page timeout (tried the last four links).
Just me?

**Comment by payneWeave** [comment]
Not just you.

**Comment by rogerwang** [comment]
It should be OK now. Please check again or wait for the DNS update.

**Comment by payneWeave** [comment]
Looks like it is working for me now. Thank you!

**Comment by garfield69** [comment]
Yes, all working now. Thank you.
