### ISSUE TITLE
Error Message on 50.12-r1.1 at boot

### ISSUE THREAD

**Issue by Ten41** [nwjs/nw.js#8171]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ X] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

Error message displaying at startup

### Current/Missing Behavior
Enabled tweak adamantine-cloth-wear (adamantine_cloth_wear_armor_hook::incWearTimer)
Enabled tweak adamantine-cloth-wear (adamantine_cloth_wear_helm_hook::incWearTimer)
Enabled tweak adamantine-cloth-wear (adamantine_cloth_wear_gloves_hook::incWearTimer)
Enabled tweak adamantine-cloth-wear (adamantine_cloth_wear_shoes_hook::incWearTimer)
Enabled tweak adamantine-cloth-wear (adamantine_cloth_wear_pants_hook::incWearTimer)
**_Could not activate tweak craft-age-wear (craft_age_wear_hook::ageItem)_**
Enabled tweak flask-contents (flask_contents_hook::getItemDescription)
Enabled tweak reaction-gloves (reaction_gloves_hook::produce)
Enabled tweak eggs-fertile (eggs_fertile_hook::getItemDescription)
Enabled tweak partial-items (partial_items_hook_bar::getItemDescription)
Enabled tweak partial-items (partial_items_hook_drink::getItemDescription)
Enabled tweak partial-items (partial_items_hook_glob::getItemDescription)
Enabled tweak partial-items (partial_items_hook_liquid_misc::getItemDescription)
Enabled tweak partial-items (partial_items_hook_powder_misc::getItemDescription)
Enabled tweak partial-items (partial_items_hook_cloth::getItemDescription)
Enabled tweak partial-items (partial_items_hook_sheet::getItemDescription)
Enabled tweak partial-items (partial_items_hook_thread::getItemDescription)
Running script: dfhack-config/init/default.dfhack.init
Running script: hack/init/dfhack.default.init
Running script: hack/init/dfhack.keybindings.init
Running script: hack/init/dfhack.tools.init
Running script: dfhack-config/init/dfhack.init
Running script: dfhack-config/init/dfhack.control-panel-preferences.init
Running script: dfhack-config/init/dfhack.control-panel-system.init
DFHack is ready. Have a nice day!
DFHack version 50.12-r1.1 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
[DFHack]#
### Additional Info

- Operating System:
- NW.js Version:
- Repro Link:
- Code snippet:
- Crash report:

**Comment by ayushmanchhabra** [comment]
This stack trace does not look like it is from NW.js but a native C++ application. Correct me if I'm wrong I'll reopen the issue.
