### ISSUE TITLE
Is it possible to get webgl context in c++ node module like in emscripten?

### ISSUE THREAD

**Issue by hellozyemlya** [nwjs/nw.js#8172]
Question is simple - since nodejs and webpage executed in same context, is it possible to give an access to webgl context to a nodejs native module? So, for example, some other GL-based libraries can be easily reused?

**Comment by ayushmanchhabra** [comment]
Do you mean passing the WebGL context into a NW.js Node Addon?

index.html
```
<script>
const addon = require('./build/Release/addon');
const context = canvas.getContext('webgl');
addon(context);
</script>
```

**Comment by ayushmanchhabra** [comment]
My C++ is not that great so was unable to get a working example. Maybe you could use this repo as a starting point:
https://github.com/nwutils/nw-node-addon-example
