### ISSUE TITLE
crashed when load addon

### ISSUE THREAD

**Issue by xueqino1** [nwjs/nw.js#8179]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

 Bug Report
- [ ] Successfully reproduced against the latest version of NW.js?
yes
### Current/Missing Behavior

I compiled iohook addon with command "cmake-js rebuild --runtime=nw --runtimeVersion=0.37.3 --arch=x64", it works fine in nwjs 0.37.3.
now I need to update nwjs to  0.63.1, and I compiled iohook with command "cmake-js rebuild --runtime=nw --runtimeVersion=0.63.1 --arch=x64", it's finished without any errors and generated iohook.node uiohook.dll successfully . but when nwjs 0.63.1  loads iohook, nwjs crashed.  I also tested some other nwjs versions, 0.37.4 works, but  0.58.0 0.69.1 0.86.0  are all crashed. it seems all versions upper than 0.37.4 don't work. I tested some node versions (V17.8.0 , V15.14.0 etc) with compile command "cmake-js rebuild --runtime=node --runtimeVersion=x.x.x --arch=x64", it works fine.

test step:
run nw.exe, F12 open devtools, input 'const a = require("iohook") ' in  console, then the devtools window quit, and the main window show crashed.

I got the crashpad file, but I don't have enough knowledge to analyze it.could you take a look? thanks so much.[76f65f70-ca57-4c4a-b95d-5f530f99c7ec.dmp](https://github.com/nwjs/nw.js/files/15050611/76f65f70-ca57-4c4a-b95d-5f530f99c7ec.dmp)
### Additional Info

- Operating System:windows 10
- NW.js Version: 0.63.1
- Repro Link:
- Code snippet:
- Crash report:
![a1](https://github.com/nwjs/nw.js/assets/20064641/3f1920bd-0177-44d0-b6d8-ba51a86112bf)
![a2](https://github.com/nwjs/nw.js/assets/20064641/05f5dee0-f622-4787-b349-c474b69b8e71)

**Comment by ayushmanchhabra** [comment]
I think this should be opened as an issue on the CMake.js repo.

**Comment by ayushmanchhabra** [comment]
NW.js Node addons are compiled by using custom headers. My guess is that CMake.js is not downloading those custom headers for versions above 0.37.3. The headers can be downloaded using this format `https://dl.nwjs.io/v{VERSION}/nw-headers-v{VERSION}.tar.gz`

**Comment by xueqino1** [comment]
> NW.js Node addons are compiled by using custom headers. My guess is that CMake.js is not downloading those custom headers for versions above 0.37.3. The headers can be downloaded using this format `https://dl.nwjs.io/v{VERSION}/nw-headers-v{VERSION}.tar.gz`

thanks for your reply, but I don't think so. first , it works normally in nwjs0.37.4 which I use for the first time too. second, when cmake compiles for other nwjs versions, I can see it downloads the hearder files in the log
