### ISSUE TITLE
crash on open

### ISSUE THREAD

**Issue by Red-Owl** [nwjs/nw.js#8180]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x ] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Additional Info

- Operating System: ubuntu x64 23.10
- NW.js Version: 0.87
- Repro Link:
- Code snippet:
- Crash report: "crash on open"

full source attachment:
[rs232_not_finish.zip](https://github.com/nwjs/nw.js/files/15076952/rs232_not_finish.zip)

in old version .86 run perfect

**Comment by ayushmanchhabra** [comment]
Try to create a minimal repro. The attachment runs but freezes for me.
