### ISSUE TITLE
Security warning stops running nwjs on MacOS

### ISSUE THREAD

**Issue by pragma-git** [nwjs/nw.js#8196]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [X] Bug Report
- [ ] Feature Request

- [X] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior
Cannot run downloaded nwjs due to macos security concerns.  Previously the downloaded nwjs.app could be made to run by  right-click on the app and select 'Open' (the first time only, after that it worked by double-clicking)

### Expected/Proposed Behavior
I expected to be able to run the downloaded nwjs version by right-clicking nwjs.app and selecting 'Open' as before

### Additional Info

Problem is solved by this command (which I have not seen documented on the download page)
 `sudo xattr -r -d com.apple.quarantine /Applications/nwjs.app`

One solution may be to hint this on the download page?  

The installation procedure I use is to unzip the downloaded file `nwjs-sdk-v0.89.0-osx-arm64`, and then copy the `nwjs.app` from the unzipped folder into `/Applications`

- Operating System: Macos Ventura
- NW.js Version: 0.89 SDK
- Repro Link: nwjs software download page [https://nwjs.io/downloads/](https://nwjs.io/downloads/)
- Code snippet:
- Crash report:

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/nw.js/issues/7117
The app needs to be signed to run (and notarized to distribute via App Store).
