### ISSUE TITLE
When using url in main, global object not available in page

### ISSUE THREAD

**Issue by hellozyemlya** [nwjs/nw.js#8201]
When using url in main, there is no global object and I cant import any node packages. Is it possible to return global object back?

**Comment by bluthen** [comment]
Not sure I tottally understand your question. But maybe you didn't set node-remote correctly for whatever you are trying to do?
https://nwjs.readthedocs.io/en/stable/References/Manifest%20Format/#node-remote

**Comment by fgt1t5y** [comment]
In package.json, set "node-remote" field same as "main" field.
