### ISSUE TITLE
Strange red tray icon

### ISSUE THREAD

**Issue by peq42** [nwjs/nw.js#8203]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [X] Bug Report
- [ ] Feature Request

- [X] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior
I tried updating my project's nwjs version to the latest one(v0.90) and there's always a red square icon on the tray. My project has a png icon defined, and the .exe file has the icon altered via resource hacker, so that is extra strange. On top of that, it seems that sometimes closing the project window won't properly close it(nwjs will still run in the background, not allowing me to open my project again), until I either right click that red icon -> close or force close through the task bar.

I'm not entirely sure but I think a few previous versions do it too. Last one I tested that DIDN'T have it was v0.87

### Expected/Proposed Behavior
None of the above should happen

### Additional Info

- Operating System: Windows 10 Pro
- NW.js Version: v0.90
- Repro Link: open any project
- Crash report: none

**Comment by jonlepage** [comment]
> On top of that, it seems that sometimes closing the project window won't properly close it(nwjs will still run in the background, not allowing me to open my project again)

is it the come back of ghost process ?
https://github.com/nwjs/nw.js/issues/7633#issuecomment-749297180

**Comment by peq42** [comment]
I worry that maybe

**Comment by bmatusiak** [comment]
this is also here in v0.89.0

**Comment by jonlepage** [comment]
make a shortcut with bat for kill all node and nw process.
Also take the opportunity to clean the OS process
![image](https://github.com/user-attachments/assets/613d063a-0e64-48f5-896b-1a5fb3cbcc6f)

**Comment by sljer** [comment]
![image](https://github.com/user-attachments/assets/4cb4b96a-622f-42c6-aebb-d7b4148f3b5c)

**Comment by shixued** [comment]
me too ! I test V0.90~V0.88

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/nw.js/issues/7236#issuecomment-2302925889
This comment might have some helpful workarounds.

**Comment by shixued** [comment]
> [#7236 (comment)](https://github.com/nwjs/nw.js/issues/7236#issuecomment-2302925889) This comment might have some helpful workarounds.

I test the  v0.87.0 is OK.
Is it possible that the latest version has any features?

**Comment by peq42** [comment]
it might be related to the slow migration to nw2/removal of nw1

Also the issue doesn't always happen, but at random. Specially when the application stops responding and gets force closed

**Comment by zkrige** [comment]
Is there any fix for this yet?
