### ISSUE TITLE
occasional crashes in window10 during runtime 

### ISSUE THREAD

**Issue by GraceLee1028** [nwjs/nw.js#8208]
NWJS Version : 0.14.7-sdk
Operating System : Fedora 26 x64

Expected behavior
It does not crash.

Actual behavior
It crash randomly.

dump file
[Uploading d918af3a-23c6-4e3b-85bf-d4ecce84d1f2.dmp…]()

**Comment by ayushmanchhabra** [comment]
I don't think you uploaded the dmp file correctly. Clicking the link redirects me to the current page. What does the stack trace show in the terminal after it crashes?
