### ISSUE TITLE
old nwjs version need sdk for arm

### ISSUE THREAD

**Issue by foolzhang** [nwjs/nw.js#8211]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ ] Bug Report
- [X] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Expected/Proposed Behavior
we use old nwjs version 0.57.1, but it's not support arm, in short time , we hava no plan to upgrade nwjs version, so we decide build arm sdk by ourself , is there any guide wiki or something useful link ,thanks

### Additional Info

- Operating System: Mac m1
- NW.js Version: 0.57.1

**Comment by ayushmanchhabra** [comment]
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/nw57-arm64_2021-12-08
Here is the unofficial prebuilt version of 0.57.0 for Linux ARM.

https://github.com/corwin-of-amber/nw.js/releases/tag/nw-v0.57.1%2BM1
Here is the unofficial prebuilt version of 0.57.0 for MacOS ARM.

For help building, you could try asking in theae respective repos.

**Comment by foolzhang** [comment]
ok thanks @ayushmanchhabra maybe i will try later
i am just afraid of it's unofficial 😓
