### ISSUE TITLE
[Bug Report ] browser context script type module , can't import node builtin modules

### ISSUE THREAD

**Issue by Hocti** [nwjs/nw.js#8229]
Here is a example `index.html`

<!DOCTYPE html>
<html lang="en">
<body>

    <script>
    nw.Window.get().showDevTools();

    const path = require('node:path');
    console.log('path:',path);
    </script>

    <script type="module">
        import path from "node:path" 
        console.log('path:',path);
    </script>

</body>
</html>

and here is the error message on devTool:
`node:path:1  Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

first script tag work fine for sure, 
but when `type="module"` the it would fail

**Comment by ayushmanchhabra** [comment]
NW.js does not support importing Node ESM modules in browser context. This should work:
```patch
<script type="module">
-    import path from "node:path" 
+    const path = require("node:path");
    console.log('path:',path);
</script>
```
