### ISSUE TITLE
Random window appearing when reloading

### ISSUE THREAD

**Issue by fenix272** [nwjs/nw.js#8230]
I'm using nw.js 0.93. When i click the reload context menu option to make nw.js reload the app, sometimes(it seems random) a new window appears with the google search page. Why is that?

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/nw.js/issues/4505#issuecomment-2466179722
Does this help?

**Comment by fenix272** [comment]
Yes, it does, thank you. No more google windows!
