### ISSUE TITLE
Start exe, the main window icon is normal, and the sub window icon is red

### ISSUE THREAD

**Issue by Moyoung-Li** [nwjs/nw.js#8233]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [x] Bug Report
- [ ] Feature Request

- [x] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
nw.jsV0.93.0,Open the online webpage link，Start exe,the main window icon is normal,In my webpage, JavaScript uses window.open to open subpages,the sub window icon is red
### Expected/Proposed Behavior
Hope the sub window icon is consistent with the main window icon
### Additional Info

- Operating System: window10, 64
- NW.js Version: v0.93.0
- Repro Link: 
- Code snippet:
- Crash report:

**Comment by ayushmanchhabra** [comment]
Please provide a code snippet to reproduce this behaviour

**Comment by LostBeard** [comment]
I had this issue also. Not sure if it is a bug. I expected the new window to have the same icon as the main window also.

You can specify the window icon when you call `window.open` using the `icon` subfield mentioned here [Window subfields](https://nwjs.readthedocs.io/en/latest/References/Manifest%20Format/#window-subfields). Then your window will have whatever icon you want.
