### ISSUE TITLE
Page Visibility API

### ISSUE THREAD

**Issue by Subash** [nwjs/nw.js#846]
Use this code to reproduce the bug.
```js
require('nw.gui').Window.get().hide();
console.log(document.webkitHidden);
```

**Comment by ludalex** [comment]
I can confirm this little bug is still there. Unfortunately it's blocking one of my project :(
As a workaround, Is there a way to force `document.webkitHidden` property to be true?

**Comment by MadLittleMods** [comment]
:+1:

**Comment by SchizoDuckie** [comment]
![image](https://cloud.githubusercontent.com/assets/111710/19322757/94823cb0-90ba-11e6-8de5-08e0b0d8a932.png)

Happy to report this is working in v0.17.6, issue can be closed.

**Comment by rogerwang** [comment]
@SchizoDuckie good to know it. Thanks.
