### ISSUE TITLE
Embedding custom objects

### ISSUE THREAD

**Issue by plashenkov** [nwjs/nw.js#85]
Hello!

Is it possible to embed custom, special developed objects to a page in node-webkit?
Like Adobe Flash, QuickTime, NPAPI modules do---all they can be embedded in usual browser.
In other words, is it possible to write and to embed custom controls to the page?
Is there any technique?

Thank you!

**Comment by rx4hvn** [comment]
@sreeshas Do you have any kind of sample, where flash is working in linux?
I tried lots of method but not able to load flash in linux :(
