### ISSUE TITLE
"nwworkingdir" doesn't work in some conditions

### ISSUE THREAD

**Issue by kingFighter** [nwjs/nw.js#850]
Just use `manual_tests/test` as the test case. When `nwworkingdir` is set to "C:\\Windows", the default path is not right(even under administrator privilege), but others("C:\\Users", "C:\\User\\Public") is fine.
OS:Win7 64bit
node-webkit: v0.6.*

BTW: the `nwworkingdir` works fine when it is opened the first time.
And it works fine in `Linux debian 64bit` `node-webkit v0.6.1 v0.6.2`

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
