### ISSUE TITLE
Layout issues when using "window": {"show": false} in package.json

### ISSUE THREAD

**Issue by dennisimo** [nwjs/nw.js#851]
I've created a layout which is double the width of the viewport, for sliding between two different sections (section 1 inside the viewport, section 2 hidden to the right).

![issue-1](https://f.cloud.github.com/assets/195526/760809/cc4efd40-e7b7-11e2-8f79-5249fb1f4e18.png)

The HTML/CSS/JS works in Chrome and works in node-webkit, until I set `"window": {"show": false}` in package.json.

With the setting applied, I can see the far left of the layout very briefly, but then the layout is quickly redrawn as if to centre the layout with equal amounts overflowing out of either side of the viewport.

![issue-2](https://f.cloud.github.com/assets/195526/760818/12f1e53c-e7b8-11e2-83c8-cb57370bb059.png)

Can anyone tell me what might be causing this to happen and how it could be resolved?

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
