### ISSUE TITLE
Main window inactive and cannot be reactivated programmatically after alert()

### ISSUE THREAD

**Issue by JPGygax68** [nwjs/nw.js#856]
Hi, and thanks for providing this really cool piece of software!

Regarding my problem, there's little more to say than what's in the heading, except that I tried all kinds of ways to re-activate the main window, including with/without setTimeout(), native window.focus(), jQuery $(window).focus(), and even the native nw.gui: gui.Window.get().focus(); none of them have any effect.

**Comment by rogerwang** [comment]
Should be fixed in latest 0.13 version.
