### ISSUE TITLE
How to write all console(dev console) log to file

### ISSUE THREAD

**Issue by SaikiranDaripelli** [nwjs/nw.js#862]
How can be redirect all the console.log and etc. log to a file instead of Chrome Developer tools console?

I need this since, i will be disabling devtools when i give my application to clients and i will need the log to triage or reproduce issue.

**Comment by ramotswa** [comment]
We're on 14.7 and setting "chromium-args": "--enable-logging", in the package.json, along with setting the chrome_log_file env variable on our windows table (as per [here](https://www.chromium.org/for-testers/enable-logging)) seems to have done the trick. 
Now have all console.log statements pushed to a file on disk.

**Comment by oudebooijink** [comment]
https://www.npmjs.com/package/nwconsole did it for me.
