### ISSUE TITLE
layout is wrong with foundation-4.2.3

### ISSUE THREAD

**Issue by richardcypher** [nwjs/nw.js#884]
I'm running the example of foundation in node-webkit and the layout is wrong when the window is small and it never change back to what it should be anymore even I maximize the window.
this is what I got in nw:
![image](https://f.cloud.github.com/assets/2770171/810486/9662793e-eeb8-11e2-92a8-eb9ab85ed444.png)

and this is what I got in chrome:
![image](https://f.cloud.github.com/assets/2770171/810491/b199cc48-eeb8-11e2-8d4c-ebc21afb07b1.png)

and I'm using node-webkit-v0.6.2 ubuntu 13.04 64bit

**Comment by rogerwang** [comment]
should be working with latest 0.13 version.
