### ISSUE TITLE
setImmediate() is not available (though global.setImmediate exists)

### ISSUE THREAD

**Issue by Mithgol** [nwjs/nw.js#897]
Stefan Thomas [reports:](https://groups.google.com/forum/#!topic/node-webkit/TACZdwBZ5jk)

> I'm not sure if this is a bug, but I think so.
> 
> **Expected behavior:**   node-webkit copies `setImmediate` over from Node.js `global` to `window`.
> 
> **Actual behavior:**   It doesn't:

```
> setImmediate
ReferenceError: setImmediate is not defined

> global.setImmediate
function () {
   var t = NativeModule.require('timers');
   return t.setImmediate.apply(this, arguments);
}
```

> What makes this particularly irritating is that the `setImmediate` shim provided by NobleJS is fooled by `global.setImmediate` and doesn't trigger.
> 
> https://github.com/NobleJS/setImmediate
> 
> So ultimately you end up with no `setImmediate` at all, even if your app includes the shim.
##

**Comment by xixilive** [comment]
:+1

**Comment by Christywl** [comment]
Per the above comments, this is not a nwjs issue? @rogerwang

**Comment by Arti3DPlayer** [comment]
I've installed https://www.npmjs.com/package/fast-csv   lib to parse csv and got this error with simple example 

```
var stream = fs.createReadStream("my.csv");
 
var csvStream = csv()
    .on("data", function(data){
         console.log(data);
    })
    .on("end", function(){
         console.log("done");
    });
 
stream.pipe(csvStream);
```
