### ISSUE TITLE
Window Move Event possible?

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#903]
The one thing you cannot easily do right now is detect if someone moves the window - you can detect resizing, maximising/minimizing but not moving.

Any chance of a 'move' event on the nw Window object just to complete this?

**Comment by abdulwajid725** [comment]
I am working on a project where I need to get window position only when window movement stops . using 'move' event I am not able to achieve my goal as it constantly fires the event on movement..Is there any event which can be fired only when window movement stops.

**Comment by necival85** [comment]
> I am working on a project where I need to get window position only when window movement stops . using 'move' event I am not able to achieve my goal as it constantly fires the event on movement..Is there any event which can be fired only when window movement stops.

just use a clearTimeout / setTimeout combo... like 10ms the final setTimeout wont be cleared and your event fires 10ms after move end
