### ISSUE TITLE
Select camera for getUserMedia?

### ISSUE THREAD

**Issue by vibber** [nwjs/nw.js#909]
Hi there,
I've been wanting to build an app that uses camera input via the getUserMedia feature.
In the settings of Chrome I am able to select another camera than the default. 

However in Node-webkit I obviously don't have the same settings panel. I have been looking for a Chromium-args setting that allows me to change the camera but no luck.
Currently the getUserMedia API does not allow for specifying the camera - a browser default setting is always used.

Does anybody have the solution?

Attached a screen shot of the Chrome setting that allows to select camera (although in this screen shot I only had one camera connected)
![screen shot 2013-07-22 at 12 04 51](https://f.cloud.github.com/assets/4029429/834211/5a5cadc0-f2b8-11e2-995c-3688f48af8b3.png)

**Comment by xenyou** [comment]
@rogerwang 
So, is there a solution now?
This issue is closed and #632 is also closed, but I still don't know how to select a camera.

**Comment by xenyou** [comment]
Sorry, I found the way myself.
https://simpl.info/getusermedia/sources/
