### ISSUE TITLE
showItemInFolder not working on Win 7 SP1

### ISSUE THREAD

**Issue by inscore** [nwjs/nw.js#913]
When I attempt to show an item in a folder via gui.Shell.showItemInFolder(path) on Win 7 SP1 nothing happens. I'm not seeing any errors in the console, and the same code works properly on OSX.
##

**Comment by hems** [comment]
@jocabola yes it helps ( :

happy new year :8ball:

**Comment by docotronic** [comment]
Sometimes on Windows gui.Shell.showItemInFolder('C:\foo\bar.txt') works instead of gui.Shell.showItemInFolder('C:\\foo\\bar.txt'). Not sure why, but did the trick for me.
