### ISSUE TITLE
Adding an API to configure proxy [$85]

### ISSUE THREAD

**Issue by clowwindy** [nwjs/nw.js#916]
In 0.6.3 an API to get proxy for url has been added. Can we have an API to set proxy?

Chrome has a proxy API, which doesn't affect system settings. I'm wondering if nw could have the same feature.

http://developer.chrome.com/extensions/proxy.html

**Comment by benuts** [comment]
@tommoor Have you find any solution to autologin in proxy configuration ? My app is meant to run alone without any interaction so I must find a way to do that..

**Comment by bestplay** [comment]
After gui.App.setProxyConfig Devtools show Empty
-------------------------------------------------------------
With 12.0 & 12.2 for win7 32bit .
And operating system is win7 64bit.

After set proxy by setProxyConfig. and proxy works good.
But Devtools show Empty.

My proxy string pass to setProxyConfig is : 
"http=192.168.2.2:8087;https=192.168.2.2:8087;socks=direct://" OR
"http=192.168.2.2:8087;direct://"

Both cause the same result.

Remote debugging via local socket?
And how can I passby the local socket for remote debugging?

**Comment by Aluxian** [comment]
+1 I have the same problem as @bestplay :(

**Comment by Synthetisoft** [comment]
This can be done by CLI argument in Electron (Previously named Atom Shell) via a commit that was made a while ago right? Should it not now be easy to add to nw.js?

**Comment by rogerwang** [comment]
@ayapi the support for auto detect proxy and PAC url will be added in the next 0.12.4 release. Thanks for your patience.

**Comment by ayapi** [comment]
Thank you very much!

**Comment by TomAshley303** [comment]
I know a lot of people would love to use nwjs for web automation and so being able to rotate proxies with logins and no user interaction required is essential. There are other use-cases as well.

**Comment by trubit** [comment]
Please merge commit by rogerwang c45f686
