### ISSUE TITLE
App stuck by udp

### ISSUE THREAD

**Issue by zbcjackson** [nwjs/nw.js#92]
I am just starting to use node-webkit. I wrote a little chat app. But after binding using udp api, the app get stuck, even when I use worker to bind. There is no response, or it's too slow to response. Do you have any idea?
Here is the main script:

``` javascript
$(function(){
    var worker = new Worker("js/udp.js");
    worker.addEventListener("message", function(e){
        $("<div>").text(e.data.message).appendTo("#messages");
    });

    var name = "Jackson";

    $("#send").click(function(){
        var message = $("#message").val();
        worker.postMessage({cmd: "send", msg: {"name": name, "message": message}});
    });

    worker.postMessage({cmd: "start"});

    $(window).unload(function(){
        worker.postMessage({cmd: "stop"});
    });
});

```

And the worker script udp.js:

``` javascript
var sys = require('util');
var net = require('net');
var dgram = require('dgram');
var Q = require('q');

var client = dgram.createSocket("udp4");
client.on("message", function(msg, rinfo){
    var msgInfo = e.data.split(":");
    self.postMessage({name: msgInfo[0], message: msgInfo[1]});
    console.log("["+ new Date().toLocaleTimeString() + "]: " + msg + " from " +
        rinfo.address + ":" + rinfo.port);
});

self.addEventListener('message', function(e) {
    var data = e.data;
    switch (data.cmd){
        case "start":
            client.bind(8888);
            break;
        case "stop":
            client.close();
            break;
        case "send":
            send(data.msg.name + ":" + data.msg.message);
            break;
    }
}, false);

function send(message, address, broadcast){
    address = address || "10.86.66.255";
    broadcast = broadcast !== false;

    var messageBuffer = new Buffer(message);
    var deferred = Q.defer();
    client.setBroadcast(broadcast);
    // client.send(messageBuffer, 0, messageBuffer.length, 8888, address);

    client.send(messageBuffer, 0, messageBuffer.length, 8888, address, function(err, bytes){
        if(err){
            deferred.reject();
        }else{
            deferred.resolve();
        }
    });
    return deferred.promise;
}
```

**Comment by acidhax** [comment]
This was closed, but I'm running into an issue with v0.11.6 and UDP not actually going out to the network?

**Comment by TomKaltz** [comment]
@acidhax Did you ever get this resolved?  I believe I'm having the same problem with UDP not working.

**Comment by acidhax** [comment]
It just wouldn't work! I had to execute a node script externally with an additional node.exe bundle, and communicate via IPC.

**Comment by TomKaltz** [comment]
@acidhax Yeah I was just about to start implementing the same work-around.

**Comment by TomKaltz** [comment]
Anyone ever get this to work?

**Comment by imShara** [comment]
Progress? client.send doesn't work in node-webkit, but works with plain node

**Comment by acidhax** [comment]
This will probably never get fixed. I had to execute a nodejs process, and communicate via IPC.

**Comment by rogerwang** [comment]
This should be working with latest version now. 

In 0.13 we changed to an optimized architecture so more features can be supported, see http://nwjs.io/blog/whats-new-in-0.13/ and it's good for keeping up with Chromium upstream -- we released with Node.js v6.0 and new Chromium versions within 1 day after upstream release.

The new version would fixed many issues reported here and we're scrubbing them. Please leave a message if it isn't and we'll check it.

**Comment by imShara** [comment]
@rogerwang, yep, it's working with 0.14, thanks.
@acidhax, it's time for optimizations :)
