### ISSUE TITLE
Data from Scheme URL

### ISSUE THREAD

**Issue by inscore** [nwjs/nw.js#934]
I've edited my plist file so that I can launch my app via a scheme url. However I can't seem to find a way to access the data I pass in the url as params.

Does node-webkit provide an api to access scheme urls? I looked but couldn't find any code that appeared to be handeling scheme urls.

**Comment by rogerwang** [comment]
#1769 is merged. So we could close this?

**Comment by rogerwang** [comment]
fixed in #4240
