### ISSUE TITLE
Please utilize H.264 and MP3 decoders built into Windows

### ISSUE THREAD

**Issue by zatch** [nwjs/nw.js#935]
Hi Roger,

I posted this question in the node-webkit Google group, but I figured I would submit an actual feature request here.

I'm looking for a way to legitimately support H.264 video in a node-webkit app without licensing decoder patents.  I know Mozilla recently managed this with Firefox by letting the operating system handle decoding.  Since Windows 7 and 8 both come packaged with the proper codecs, Mozilla can support the encoding without licensing the codecs or packaging them with Firefox.  Is it possible to do the same with node-webkit?

My related Google group post:
https://groups.google.com/forum/#!topic/node-webkit/G-YHvdfhcj8

Thanks,
Zach

**Comment by rogerwang** [comment]
Please see more updates in #1393 on h264 support.
