### ISSUE TITLE
Node-webkit cannot be submitted to MacOSX App Store

### ISSUE THREAD

**Issue by trevorlinton** [nwjs/nw.js#936]
Due to private api's being used node-webkit isn't passing Apple's review for their app store.  This would require looking into why private api's are being used.  Most likely either debug code or possibly older SDK's using deprecating API's.

See:
https://groups.google.com/d/msg/node-webkit/qP_x9Z0lEO4/0Fo7mnT45z0J

For Apple's response.

**Comment by eliasisrael** [comment]
Did it work, @trevorlinton? Can NWJS be submitted to the app store?

**Comment by syabro** [comment]
yep, what's the current status about Mac App store?

**Comment by alexeyst** [comment]
See an update about this here: https://github.com/nwjs/nw.js/issues/3258#issuecomment-82647821.
