### ISSUE TITLE
Conflict with MS Office 2003

### ISSUE THREAD

**Issue by ghost** [nwjs/nw.js#945]
When I first start my app, then try to open MS Office 2003 file (word or excel), the machine is dead lock. I have to kill my app to make everything ok again.

This problem exists in Windows XP and node-webkit version > 0.3.7.

Version 0.3.7 is ok.

**Comment by Mithgol** [comment]
For the record, [MS Office could conflict with Google Chrome](https://productforums.google.com/forum/#!msg/chrome/DqcxbNwHbDI/Q7GcgDEiuosJ); fortunately, that problem has been resolved in Chrome 21.0.1180.83 or earlier.
