### ISSUE TITLE
Provide a automatic packaging tool

### ISSUE THREAD

**Issue by zcbenz** [nwjs/nw.js#99]
Currently packaging standalone node-webkit apps requires lots of manual steps on different platforms, we should provide to tool to do that automatically, at least following features should be provided:
- Detect and download newest binaries.
- Automatically make packages for all platforms.
- Provide deb and rpm packages for Linux.
- Set package and .exe icons.
- Register apps as file type and URL scheme handlers (see #255).

**Comment by matthew-dean** [comment]
> Register apps as file type and URL scheme handlers

Is this ever going to happen? This issue and the issue it refers to have both been closed, even though this feature lack has never been addressed. Why is this closed without the packaging goals either being completed or amended?

**Comment by Mithgol** [comment]
This issue (titled “Provide a automatic packaging tool”) was closed, I suppose, because the “Issues” section of [`nw-builder`](https://github.com/nwjs/nw-builder) replaced it.

However, the previous issue (#255) is still valid and I have just reopened it.

**Comment by makkesk8** [comment]
This can be done easily using gulp and 'gulp-nw-builder'. Infact I'm already doing it, But i'm targeting only one specific platform but you can expand whenever you wish.

Example (works only using win32 but can be modified easily) :  https://gist.github.com/makkesk8/9bec9773e018dc3d0992
