### ISSUE TITLE
problem loading serialport

### ISSUE THREAD

**Issue by yapcheahshen** [nwjs/nw.js#998]
i failed to load serialport from node-webkit,
here is my configuration and stack dump.
# 

node 
process.arch == "ia32"

npm ls
├─┬ node-gyp@0.10.9
├─┬ nw-gyp@0.7.3-4
├─┬ serialport@1.1.3

cd node_modules\serialport
node ..\nw-gyp\bin\nw-gyp.js configure --target=0.7.0
node ..\nw-gyp\bin\nw-gyp.js build
node ..\nw-gyp\bin\nw-gyp.js -d build

when i try to require("serialport")

Uncaught Error: The specified procedure could not be found.

C:\ksanapc\node_modules\serialport\build\Debug\serialport.node module.js:359
Module.load module.js:359
Module._load module.js:315
Module.require module.js:367
require module.js:383
bindings C:\ksanapc\node_modules\serialport\node_modules\bindings\bindings.js:76
(anonymous function) C:\ksanapc\node_modules\serialport\serialport.js:7
Module._compile module.js:459
Module._extensions..js module.js:477
Module.load module.js:359
Module._load module.js:315
Module.require module.js:367
require module.js:383
window.require
(anonymous function)

**Comment by Yvanovitch** [comment]
According to [this ticket](https://github.com/nwjs/nw-gyp/issues/107?_pjax=%23js-repo-pjax-container), you have to set the target nwjs version in the build command.
You can optionally set the target_arch with "ia32" or "x64"
```
npm install -g nw-gyp
cd node_modules/serialport/
nw-gyp configure --target="0.22.1" --target_arch="ia32"
nw-gyp build --target="0.22.1" --target_arch="ia32"
```
